xform: constrain index scans on computed columns in more cases
cockroachdb/cockroach pull request #100242
Opened 2023-03-31 00:03 UTC by msirek

IN list predicates on index columns which are the inputs to computed
column expressions can't currently constrain the scan if the computed                                                        
columns are a prefix of the index key, e.g.      
```sql
CREATE TABLE t1 (
    id VARCHAR(32) NOT NULL,
    b INT2 NOT NULL AS (CAST(substr(id, 2:::INT8, 1:::INT8) AS INT8)) VIRTUAL,
    CONSTRAINT pkey PRIMARY KEY (b ASC, id ASC));

-- This uses a constrained scan.
SELECT * FROM t1 WHERE id IN ('12345');

-- This does not.
SELECT * FROM t1 WHERE id IN ('12345', '6789');
```

Function `computedColFilters` derives filters on computed columns by
calling `findConstantFilterCols` on all required and optional filters to
find the constants in single-column single-span constraints, then
converts them into single-column single-span predicates on computed
columns.

This change introduces a new, similar function `combineComputedColFilters` 
which combines the steps of finding span key values and building up new
predicates based on them within the same nested loops, so if the derived
predicate needs to be AND'ed with the span keys they were derived from
or nested under an OR term, this can be done.

New terms can be generated from spans with a single key based on one or
more columns, though each `FiltersItem` is processed in isolation, so
there are cases `computedColFilters` can handle which
`combineComputedColFilters` can't.

Fixes: #100206

Release note (performance improvement): This adds support for
constrained scans using computed columns which are part of an index
when there is an IN list or OR'ed predicate on the columns that appear
in the computed column expression.

2023-03-31 00:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/100242)
<!-- Reviewable:end -->

2023-03-31 15:20 UTC, msirek commented
This PR fixes https://github.com/cockroachlabs/support/issues/2196

2023-03-31 16:53 UTC, michae2 commented
I wonder if this will also fix https://github.com/cockroachdb/cockroach/issues/99557 ?

2023-03-31 17:25 UTC, mgartner reviewed
Nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NRsg67T6j-4ahde5QS_:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRsdTB0AplmtwfedQ3a:-NRsdTB0AplmtwfedQ3b:b-tcv055) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L330)):*
> ```Go
> //
> //	(a IS 3 AND b IS 4 AND c IS 7) OR
> //	(a IS 5 AND b IS 6 AND c IS 11)
> ```

I believe this transformation is not equivalent in the presence of`NULL`:

```
SELECT (1, 2) IN ((1, NULL))
=> 
NULL

SELECT 1 IS NOT DISTINCT FROM 1 AND 2 IS NOT DISTINCT FROM NULL
=>
false
```

I use `IS NOT DISTINCT FROM` instead of `IS` above because there is no binary `IS` operator in SQL - memo.IsExpr translates to `IS NOT DISINTCT FROM`.

So we might have to limit this to cases where the columns are `NOT NULL` _and_ where none of the constant values are `NULL`.

Or, would it be simpler to make this transformation instead? And would it be equivalent in all cases with NULL?

```
(a, b) IN ((3, 4), (5, 6))
=>
(a, b, a+b) IN ((3, 4, 3+4), (5, 6, 5+6))
```
___
*[`pkg/sql/opt/xform/general_funcs.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC:-NRseKq6CLUVnilIbCiD:b-vz4ecb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L351)):*
> ```Go
> // Also note, this function handles IN list predicates but could be extended to
> // handle ORed predicates too (see TODO below).
> func (c *CustomFuncs) combineComputedColFilters(
> ```

Since this function is fairly complex, I think it'd be prudent to have some unit tests for it. Some data-driven tests could be best - similar to the ones in `pkg/sql/opt/partialidx` and `pkg/sql/opt/idxconstraint` that deal with just scalar expressions.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRse8CJ9fcnWa_C1grT:-NRse8CJ9fcnWa_C1grU:b54fb6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L396)):*
> ```Go
> 				var newOp opt.ScalarExpr
> 				// Build the initial conjunction
> 				for m := 0; m < cons.Columns.Count(); m++ {
> ```

This function is quite complex, with four nested loops. Is there a thoughtful way to break it up to make it easier to understand?


<!-- Sent from Reviewable.io -->

2023-04-04 21:44 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRsdTB0AplmtwfedQ3a:-NS8_Mju4LRYtpSJKlxU:bbo983k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L330)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I believe this transformation is not equivalent in the presence of`NULL`:

```
SELECT (1, 2) IN ((1, NULL))
=> 
NULL

SELECT 1 IS NOT DISTINCT FROM 1 AND 2 IS NOT DISTINCT FROM NULL
=>
false
```

I use `IS NOT DISTINCT FROM` instead of `IS` above because there is no binary `IS` operator in SQL - memo.IsExpr translates to `IS NOT DISINTCT FROM`.

So we might have to limit this to cases where the columns are `NOT NULL` _and_ where none of the constant values are `NULL`.

Or, would it be simpler to make this transformation instead? And would it be equivalent in all cases with NULL?

```
(a, b) IN ((3, 4), (5, 6))
=>
(a, b, a+b) IN ((3, 4, 3+4), (5, 6, 5+6))
```
</blockquote></details>

If a null from the original IN expression would have made it into the span, that span would have been incorrectly constructed to begin with and would have generated incorrect results. Since we're only copying constants from spans, not from predicates, I believe it is impossible for a predicate such as `(1, 2) IN ((1, NULL))` to cause the null to generate a new predicate here.

Also, IN expressions with nulls are not marked as tight:
https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/memo/constraint_builder.go#L304-L316

And non-tight constraints are ignored in the fix. 

I've added this comment to make it more clear:
```
// Note that new predicates are derived from constraint spans, not predicates,
// so a predicate such as (a,b) IN ((null,4), (5,6)) will not derive anything
// because the null is not placed in a span, and also IN predicates with nulls
// are not marked as tight, and this function does not process non-tight
// constraints.
```

So, IS op (`IS NOT DISTINCT FROM`) is required because if a null has made it into the span, for whatever reason, in order to correctly represent a predicate from that span, that's the op to use.

The pre-existing single-value code is also using IS:
https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L304-L306
This handles cases like `a IS NULL`.

There is no similar multicolumn case such as `(a, b) IS NULL` which builds tight spans with nulls, and OR terms such as `(a IS NULL AND b IS NULL) OR (a = 1 AND b = 2)` aren't currently handled (and are also not tight). So, since there is no testable use case, I've added a check to bail out if null is seen in the original constraint.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC:-NSD7IsA354yihARum4E:b4t1wc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L351)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Since this function is fairly complex, I think it'd be prudent to have some unit tests for it. Some data-driven tests could be best - similar to the ones in `pkg/sql/opt/partialidx` and `pkg/sql/opt/idxconstraint` that deal with just scalar expressions.
</blockquote></details>

I'm not sure how straightforward that would be. These functions also reference `cat.Table`, `memo.ScanPrivate`, `opt.TableMeta`, `CustomFuncs`, so may be difficult to translate into a stand-alone unit test outside of the test catalog framework.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRse8CJ9fcnWa_C1grT:-NS8ZOfw7I0tXxW-Y0d-:b-2bz39z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L396)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This function is quite complex, with four nested loops. Is there a thoughtful way to break it up to make it easier to understand?
</blockquote></details>

Sure, I consolidated the deepest level into function calls.  PTAL
The inner 2 nesting levels show how ORs are built over ANDs, so that should be clear to understand (build an OR for each constraint span, and an AND for each set of combined IN list values within that). The top level loops are just handling the separate constraint sets and `FiltersItem`s separately.


<!-- Sent from Reviewable.io -->

2023-04-05 14:58 UTC, msirek commented
> I wonder if this will also fix https://github.com/cockroachdb/cockroach/issues/99557 ?

@michae2 Yes, it does. I've marked that one fixed by this.

2023-04-10 15:44 UTC, mgartner reviewed
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRsdTB0AplmtwfedQ3a:-NSffjarErHiLYc7jLqG:b-yi98ma) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L330)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If a null from the original IN expression would have made it into the span, that span would have been incorrectly constructed to begin with and would have generated incorrect results. Since we're only copying constants from spans, not from predicates, I believe it is impossible for a predicate such as `(1, 2) IN ((1, NULL))` to cause the null to generate a new predicate here.

Also, IN expressions with nulls are not marked as tight:
https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/memo/constraint_builder.go#L304-L316

And non-tight constraints are ignored in the fix. 

I've added this comment to make it more clear:
```
// Note that new predicates are derived from constraint spans, not predicates,
// so a predicate such as (a,b) IN ((null,4), (5,6)) will not derive anything
// because the null is not placed in a span, and also IN predicates with nulls
// are not marked as tight, and this function does not process non-tight
// constraints.
```

So, IS op (`IS NOT DISTINCT FROM`) is required because if a null has made it into the span, for whatever reason, in order to correctly represent a predicate from that span, that's the op to use.

The pre-existing single-value code is also using IS:
https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L304-L306
This handles cases like `a IS NULL`.

There is no similar multicolumn case such as `(a, b) IS NULL` which builds tight spans with nulls, and OR terms such as `(a IS NULL AND b IS NULL) OR (a = 1 AND b = 2)` aren't currently handled (and are also not tight). So, since there is no testable use case, I've added a check to bail out if null is seen in the original constraint.

</blockquote></details>

Sounds good. Thanks for adding the clarifying comment, extra checks, and tests.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC:-NSfgTtlE7_-YwXmo2YJ:b47a4ff) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L351)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I'm not sure how straightforward that would be. These functions also reference `cat.Table`, `memo.ScanPrivate`, `opt.TableMeta`, `CustomFuncs`, so may be difficult to translate into a stand-alone unit test outside of the test catalog framework.
</blockquote></details>

Shouldn't be too bad, but up to you. It looks like the metadata is the main dependency - passing around the `cat.Table` is just another way to get similar information, but not necessary.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NSfnLCU3tJAngDSJZTd:b-zi8dco) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
> ```Go
> 		//    Span 1 of Constraint 1 should be combined with Span 1 of Constraint 2,
> 		//    etc...
> 		for j, n := 0, props.Constraints.Length(); j < n; j++ {
> ```

nit: There's probably some opportunities here to avoid unnecessary work if we have a set of all the outer colums in all computed column expressions - then we can skip filters in the top loop that don't reference those columns, and constraints that don't constraint those columns.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NSfdqWC1ADZ_38lQDyS:b-1hca9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
> ```Go
> 					// to use in folding the computed column expression, go to the next
> 					// span.
> 					continue
> ```

Do you have a test that exercises this case? I'm struggling to come up with an example where this case is hit. But it's a bit worrying to ignore spans of a tight constraint when deriving new filters from them. There's a risk that we generate semantically inequivalent filters. It might be safer to give up in this case and `return nil`.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfmnwCBaervOP_W5Xg:-NSfmnwCBaervOP_W5Xh:blfvca6) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L436)):*
> ```Go
> }
> 
> func (c *CustomFuncs) buildConjunctionFromConstraint(
> ```

nit: a comment here would be helpful.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfbRbR2_Y1NWitum56:-NSfbRbR2_Y1NWitum57:b-u8ym66) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L456)):*
> ```Go
> 		// Note: Nulls could be handled here, but there is currently no supported
> 		// test case for this situation, so it is explicitly disallowed for now.
> 		if d, isDatum := originalConstVal.(tree.Datum); isDatum {
> ```

`ConstructConstVal` returns an `opt.ScalarExpr`, so I this case isn't possible.  The check for `*memo.NullExpr` below should be sufficient.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 476 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSflq7J5ncJ9VkqiETy:-NSflq7J5ncJ9VkqiETz:bip4en5) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L476)):*
> ```Go
> }
> 
> func (c *CustomFuncs) buildCombinedConjunction(
> ```

nit: add a comment here

nit: it looks like this function is adding computed column expressions to the filter, so maybe a better name is something ilke `addComputedColEqualityExprs`?
___
*[`pkg/sql/opt/xform/general_funcs.go` line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfowUl2KD2299t9-SF:-NSfowUl2KD2299t9-SG:b-cmqh4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L488)):*
> ```Go
> 		// any entries present in the map.
> 		delete(constFilterCols, computedColID)
> 		if c.tryFoldComputedCol(tabMeta, computedColID, constFilterCols) {
> ```

AFAICT, the main advantage of using `tryFoldComputedCol` here instead of constructing the computed column expression directly is because it can recursively fold expressions. So can you add a test to exercise that, like:

```
CREATE TABLE t (
  a INT,
  b INT AS (a + 10) VIRTUAL,
  c INT AS (b + 20) VIRTUAL,
  d INT,
  INDEX (c, d)
);

SELECT * FROM t WHERE (a, d) IN ((1, 2), (3, 4));
```
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NSfl6vTAseouJ4Lzdv8:bsoa8ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
> ```Go
> 		// Must delete old entries since this set of constants is only valid
> 		// for the current span.
> 		delete(constFilterCols, colID)
> ```

Shouldn't we always use an empty map each time buildCombinedConjunction is called? If [...]

2023-04-14 03:37 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRsdTB0AplmtwfedQ3a:-NSwm8A282IBEmtDkt3p:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L330)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sounds good. Thanks for adding the clarifying comment, extra checks, and tests.
</blockquote></details>

Sure
___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NSx2D22DYOOz-dxlE6d:b-m3gr0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: There's probably some opportunities here to avoid unnecessary work if we have a set of all the outer colums in all computed column expressions - then we can skip filters in the top loop that don't reference those columns, and constraints that don't constraint those columns.
</blockquote></details>

OK, I pushed a commit to add tracking of computed column expression columns to table metadata. It's not a trivial change, so I'm not sure we'd want to backport this commit (at least to 22.2). Maybe backporting to 23.1 is desirable since no customers have it yet, and doing so would reduce code conflicts for future backports.


<!-- Sent from Reviewable.io -->

2023-04-14 18:46 UTC, msirek reviewed
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NT04k0J5qqjV1hWMoII:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC:-NT03q4p4VuyPhOWaa5o:b-5x7875) ([raw file](https://github.com/cockroachdb/cockroach/blob/d966848eb2aefb82af70436bc6e213e65033b10e/pkg/sql/opt/xform/general_funcs.go#L351)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Shouldn't be too bad, but up to you. It looks like the metadata is the main dependency - passing around the `cat.Table` is just another way to get similar information, but not necessary.
</blockquote></details>

Hmm, I'm having a bit of a time wrapping my head around this. I've added some more tests involving nested CASE statements and different combinations of terms. Maybe when I get some more time I'll do a closer study of all the data driven tests.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NT-v-HC-ZH7ZV_pSKwa:b-e3nbz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you have a test that exercises this case? I'm struggling to come up with an example where this case is hit. But it's a bit worrying to ignore spans of a tight constraint when deriving new filters from them. There's a risk that we generate semantically inequivalent filters. It might be safer to give up in this case and `return nil`.
</blockquote></details>

Great point!
I couldn't think of a test case either.  It _might_ be safe, because we're not actually replacing filters, but adding new filters. However, without a test case it's safer to give up entirely.
Made the change.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 436 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfmnwCBaervOP_W5Xg:-NT-fV9p42hKsD5kIiir:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L436)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: a comment here would be helpful.
</blockquote></details>

Done



_Code quote:_
```Go
func (c *CustomFuncs) buildConjunctionFromConstraint(
```
___
*[`pkg/sql/opt/xform/general_funcs.go` line 456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfbRbR2_Y1NWitum56:-NT-gLzH4BuPQL0Sv2aw:b-xvc6l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L456)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`ConstructConstVal` returns an `opt.ScalarExpr`, so I this case isn't possible.  The check for `*memo.NullExpr` below should be sufficient.
</blockquote></details>

Removed the `DNull` check.



_Code quote:_
```Go
Nulls could be handled here, but there is currently no supported
```
___
*[`pkg/sql/opt/xform/general_funcs.go` line 476 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSflq7J5ncJ9VkqiETy:-NT-grAGD1rWSKqfbCIk:b4do6hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L476)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add a comment here

nit: it looks like this function is adding computed column expressions to the filter, so maybe a better name is something ilke `addComputedColEqualityExprs`?
</blockquote></details>

OK, this is combining predicates on both computed columns and non-computed columns into the same conjunction, so that is why I used 'Combined' in the name, and would like to keep that point that it's not just computed columns.
Renamed to: `buildConjunctionOfEqualityPredsOnComputedAndNonComputedCols`

Added a comment to the function.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfowUl2KD2299t9-SF:-NT-lo6z2KSkeyRXDkvZ:b-91oa5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L488)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

AFAICT, the main advantage of using `tryFoldComputedCol` here instead of constructing the computed column expression directly is because it can recursively fold expressions. So can you add a test to exercise that, like:

```
CREATE TABLE t (
  a INT,
  b INT AS (a + 10) VIRTUAL,
  c INT AS (b + 20) VIRTUAL,
  d INT,
  INDEX (c, d)
);

SELECT * FROM t WHERE (a, d) IN ((1, 2), (3, 4));
```
</blockquote></details>

When trying to create this table I got an error:
```
ERROR: VIRTUAL COMPUTED COLUMN expression cannot reference computed columns
SQLSTATE: 42P16
```
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NT-p-_g4cWwlA79GJ0t:b-z8pikj) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Shouldn't we always use an empty map each time buildCombinedConjunction is called? If so, it'd be safer to loop through all elements of the map and delete them at the beginning of this function.
</blockquote></details>

If the map is empty we won't be able to fold the expression.  The call to `buildConjunctionFromConstraint` populates the map with the constants from columns the computed col expression might need to use. This line is just deleting the target column of the folding because the folding function skips folding if that entry is already populated.

Though, I looked closer and I believe it's safer to make `buildConjunctionFromConstraint` clear the map if it returns `ok=false` because we know in that case the map should not be used for the current constraint. I've added this code.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfpWWJ2xtkxgNakM33:-NT-rtsk23izxtNMzsz-:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/testdata/rules/select#L2133)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You can combine `expect` here: `expect=(GenerateConstrainedScans,SplitDisjunction)`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-15 03:57 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NT22ALQ0KsYrhZdBraV:bnofpdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Great point!
I couldn't think of a test case either.  It _might_ be safe, because we're not actually replacing filters, but adding new filters. However, without a test case it's safer to give up entirely.
Made the change.
</blockquote></details>

OK, so I found a test case for this:
```
CREATE TABLE t100206 (
        a INT NOT NULL,
        b INT NOT NULL,
        c INT NOT NULL AS (a+b) VIRTUAL,
        d INT,
        CONSTRAINT pkey PRIMARY KEY (c ASC, b ASC, a ASC));

# The presence of a non-single-key constraint should not prevent derivation
# of filters on computed columns.
opt expect=GenerateConstrainedScans
SELECT * FROM t100206 WHERE (a,b) IN ((3,4), (5,6)) AND a > 4
----
select
 ├── columns: a:1!null b:2!null c:3!null d:4
 ├── cardinality: [0 - 2]
 ├── key: (1,2)
 ├── fd: (1-3)-->(4), (1,2)-->(3)
 ├── scan t100206
 │    ├── columns: a:1!null b:2!null c:3!null d:4
 │    ├── constraint: /3/2/1
 │    │    ├── [/7/4/3 - /7/4/3]
 │    │    └── [/11/6/5 - /11/6/5]
 │    ├── cardinality: [0 - 2]
 │    ├── key: (1,2)
 │    └── fd: (1-3)-->(4), (1,2)-->(3)
 └── filters
      └── a:1 > 4 [outer=(1), constraints=(/1: [/5 - ]; tight)]
```

With the `return nil` we don't get a constrained scan here, so I've reverted the code back to using `continue`.


<!-- Sent from Reviewable.io -->

2023-04-21 16:59 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NTZjvrD2nCT0w4VmEtj:ba1m2yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, I pushed a commit to add tracking of computed column expression columns to table metadata. It's not a trivial change, so I'm not sure we'd want to backport this commit (at least to 22.2). Maybe backporting to 23.1 is desirable since no customers have it yet, and doing so would reduce code conflicts for future backports.
</blockquote></details>

I've updated the memo expression tree walking function with what we discussed the other day, instead of relying on `Factory.Replace`, which I think is safer to backport.


<!-- Sent from Reviewable.io -->

2023-05-05 15:10 UTC, msirek reviewed
Someone is asking if this will be ready in a backport in the June time frame, needed for when they go into production.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NUgS28pD9KAtbcU_Agh:bjdrge0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2023-05-05 21:22 UTC, mgartner requested changes
> Reviewed 12 of 15 files at r4, 5 of 5 files at r5, 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NUhl3jy1WZSfr4Y4sln:b-4ub6sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I've updated the memo expression tree walking function with what we discussed the other day, instead of relying on `Factory.Replace`, which I think is safer to backport.
</blockquote></details>

I don't understand why the second commit is necessary. Columns referenced in computed column expressions should already be available in the scalar props of the computed column filters. This is mostly equivalent to what you are doing, without any big changes (the only difference is that we'll have some false positives due to CHECK constraints being in the optional filters, but that's not a huge concern unless we have a benchmark showing a problem):

```sql
if !cons.Columns.ColSet().Intersects(optionalFilters.OuterCols()) {
  continue
}
```

Alternatively, you can pass in the result of `CustomFuncs.computedColFilters` which is readily available in the calling function `GetOptionalFiltersAndFilterColumns`, and avoid the CHECK constraint false positives.

If neither of those work, then I'd opt for eliminating the second commit. I don't think the complexity is worth it with a measurable improvement to the performance.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NUhdQfTD2gx3VKQd506:b3hhsnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, so I found a test case for this:
```
CREATE TABLE t100206 (
        a INT NOT NULL,
        b INT NOT NULL,
        c INT NOT NULL AS (a+b) VIRTUAL,
        d INT,
        CONSTRAINT pkey PRIMARY KEY (c ASC, b ASC, a ASC));

# The presence of a non-single-key constraint should not prevent derivation
# of filters on computed columns.
opt expect=GenerateConstrainedScans
SELECT * FROM t100206 WHERE (a,b) IN ((3,4), (5,6)) AND a > 4
----
select
 ├── columns: a:1!null b:2!null c:3!null d:4
 ├── cardinality: [0 - 2]
 ├── key: (1,2)
 ├── fd: (1-3)-->(4), (1,2)-->(3)
 ├── scan t100206
 │    ├── columns: a:1!null b:2!null c:3!null d:4
 │    ├── constraint: /3/2/1
 │    │    ├── [/7/4/3 - /7/4/3]
 │    │    └── [/11/6/5 - /11/6/5]
 │    ├── cardinality: [0 - 2]
 │    ├── key: (1,2)
 │    └── fd: (1-3)-->(4), (1,2)-->(3)
 └── filters
      └── a:1 > 4 [outer=(1), constraints=(/1: [/5 - ]; tight)]
```

With the `return nil` we don't get a constrained scan here, so I've reverted the code back to using `continue`.

</blockquote></details>

In this case, what is the non-single-key span, and what happens to it in the constructed filter?
___
*[`pkg/sql/opt/xform/general_funcs.go` line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfowUl2KD2299t9-SF:-NUheGlc3D4lLAwUfpMm:b-1c58wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L488)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

When trying to create this table I got an error:
```
ERROR: VIRTUAL COMPUTED COLUMN expression cannot reference computed columns
SQLSTATE: 42P16
```
</blockquote></details>

So what's the advantage of using `tryFoldComputedCol` then? All these inserts and deletes into the `constFilterCols` map are difficult to reason about. Did you consider creating a new function similar to `tryFoldComputedCol` that takes a static map of constants and returns the computed column constant be simpler?
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NUhhf_J0-WxC_UJUaiz:b-84xhcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If the map is empty we won't be able to fold the expression.  The call to `buildConjunctionFromConstraint` populates the map with the constants from columns the computed col expression might need to use. This line is just deleting the target column of the folding because the folding function skips folding if that entry is already populated.

Though, I looked closer and I believe it's safer to make `buildConjunctionFromConstraint` clear the map if it returns `ok=false` because we know in that case the map should not be used for the current constraint. I've added this code.
</blockquote></details>

Ok. The use of the constant map is hard to follow here. Is there a way to simplify it so its easier to understand how the constants are flowing through these functions?
___
*[`pkg/sql/opt/xform/general_funcs.go` line 402 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUhhczN8Qm-FzvEAEtb:-NUhhczN8Qm-FzvEAEtc:brd3orx) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fb966cf8c29f94ef214596c95c037bc1585c74/pkg/sql/opt/xform/general_funcs.go#L402)):*
> ```Go
> 					continue
> 				}
> 				// Build the initial conjunction from the constraint
> ```

nit: add period to the end
___
*[`pkg/sql/opt/xform/general_funcs.go` line 478 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUhgrqCDqbfJp15Tcqp:-NUhgrqCDqbfJp15Tcqq:b-cwuxoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fb966cf8c29f94ef214596c95c037bc1585c74/pkg/sql/opt/xform/general_funcs.go#L478)):*
> ```Go
> 	ok = conjunction != nil
> 	if !ok {
> 		maps.Clear(constFilterCols)
> ```

nit: IMO a simple for loop to delete all the entries is more straightforward than pulling in a new dependency, and more robust since the dependency is described as "experimental and deprecated".


<!-- Sent from Reviewable.io -->

2023-05-05 21:23 UTC, mgartner reviewed
Also, this is fairly complex and we should backport it behind a session setting that is disabled by default.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NUhn0_-3-HEV-RVNvTO:b-3ms0n2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)



<!-- Sent from Reviewable.io -->

2023-05-06 00:14 UTC, msirek reviewed
Sure. I've added a new session setting through another commit in preparation for backport.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NUiOOov9lRJlaKfAp3m:bggkj3w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NUhsuIU95q8YlIokxjB:b-9k2vo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
> Columns referenced in computed column expressions should already be available in the scalar props of the computed column filters.

I'm not sure I follow.  We are trying to derive computed column filters. We don't have any filters in hand which we can examine to figure out which columns are involved. `optionalFilters` is empty in the very first test case:
```
exec-ddl
CREATE TABLE t100206 (
        a INT NOT NULL,
        b INT NOT NULL,
        c INT NOT NULL AS (a+b) VIRTUAL,
        d INT,
        CONSTRAINT pkey PRIMARY KEY (c ASC, b ASC, a ASC));
----

# This should derive the value of c from a and b.
opt expect=GenerateConstrainedScans
SELECT a,b,c FROM t100206 WHERE (a,b) IN ((3,4), (5,6))
----
```
... and `requiredFilters` just holds the single filter in the query. The existence of this filter doesn't tell us anything about expressions in computed column definitions. In the calling frame, `GetOptionalFiltersAndFilterColumns`, `computedColFilters` is nil.  Just because we've defined a computed column in a table doesn't mean we'll have a filter on the columns referenced in the expression defining it (in this case, columns `a` and `b`).
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NUhx4dzAmgn873Ig83V:b-r9gzui) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
> what is the non-single-key span

The non-single-key span is `[/5 - ]`

> and what happens to it in the constructed filter?

It is ignored because it can't be used to derive any terms, and it is ANDed with other terms (so can be safely ignored).
So, from `(a,b) IN ((3,4), (5,6))` we derive:
```
((a IS NOT DISTINCT FROM 3 AND b IS NOT DISTINCT FROM 4 AND c IS NOT DISTINCT FROM 7) OR
 (a IS NOT DISTINCT FROM 5 AND b IS NOT DISTINCT FROM 6 AND c IS NOT DISTINCT FROM 11))
```
and our final set of filters is:
```
(a,b) IN ((3,4), (5,6)) AND 
a > 4 AND
((a IS NOT DISTINCT FROM 3 AND b IS NOT DISTINCT FROM 4 AND c IS NOT DISTINCT FROM 7) OR
 (a IS NOT DISTINCT FROM 5 AND b IS NOT DISTINCT FROM 6 AND c IS NOT DISTINCT FROM 11))
```

The key point is that skipping over the `a > 4 ` term does not remove it from the pre-existing filters, so it will still be applied.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfowUl2KD2299t9-SF:-NUi5s-GAFXcL7-knL2_:b3yjrup) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L488)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So what's the advantage of using `tryFoldComputedCol` then? All these inserts and deletes into the `constFilterCols` map are difficult to reason about. Did you consider creating a new function similar to `tryFoldComputedCol` that takes a static map of constants and returns the computed column constant be simpler?
</blockquote></details>

I've refactored the code to remove all of the maintenance on `constFilterCols`.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NUi4e415L91OhHsNtTJ:b-yjcw5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ok. The use of the constant map is hard to follow here. Is there a way to simplify it so its easier to understand how the constants are flowing through these functions?
</blockquote></details>

Simplified it by making `buildConjunctionFromConstraint` create a brand new map each time it's called and return the constructed map to the caller.  This way no other maintenance on the map is required.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 402 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUhhczN8Qm-FzvEAEtb:-NUhzjQ6BaepmYV2fH9A:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fb966cf8c29f94ef214596c95c037bc1585c74/pkg/sql/opt/xform/general_funcs.go#L402)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add period to the end
</blockquote></details>

Done
___
*[`pkg/sql/opt/xform/general_funcs.go` line 478 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUhgrqCDqbfJp15Tcqp:-NUi024-38UHOknSXjVb:b7jsxj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/00fb966cf8c29f94ef214596c95c037bc1585c74/pkg/sql/opt/xform/general_funcs.go#L478)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: IMO a simple for loop to delete all the entries is more straightforward than pulling in a new dependency, and more robust since the dependency is described as "experimental and deprecated".
</blockquote></details>

Made the suggested change


<!-- Sent from Reviewable.io -->

2023-05-08 13:36 UTC, mgartner reviewed
Looking great! I think the second commit can be simplified, see my comment below.

> Reviewed 4 of 14 files at r6, 10 of 10 files at r7, 9 of 9 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NUvZyT78QpCNBnF_3KD:b-l8jvll)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/vars.go` line 2589 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUvZKtCEUoU7snmoc8a:-NUvZKtCEUoU7snmoc8b:bq9k5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc8dbc47fb49c2f7d8fabf6ba5b7a3f533ba9612/pkg/sql/vars.go#L2589)):*
> ```Go
> 
> 	// CockroachDB extension.
> 	`optimizer_use_improved_computed_column_filters_derivation`: {
> ```

nit: if you wanted to shorten this, you could use "derive" as the verb, like `optimizer_derive_improved_computed_column_filters`.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NUvVjVTAwrowAupLDW_:bpp201n) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> Columns referenced in computed column expressions should already be available in the scalar props of the computed column filters.

I'm not sure I follow.  We are trying to derive computed column filters. We don't have any filters in hand which we can examine to figure out which columns are involved. `optionalFilters` is empty in the very first test case:
```
exec-ddl
CREATE TABLE t100206 (
        a INT NOT NULL,
        b INT NOT NULL,
        c INT NOT NULL AS (a+b) VIRTUAL,
        d INT,
        CONSTRAINT pkey PRIMARY KEY (c ASC, b ASC, a ASC));
----

# This should derive the value of c from a and b.
opt expect=GenerateConstrainedScans
SELECT a,b,c FROM t100206 WHERE (a,b) IN ((3,4), (5,6))
----
```
... and `requiredFilters` just holds the single filter in the query. The existence of this filter doesn't tell us anything about expressions in computed column definitions. In the calling frame, `GetOptionalFiltersAndFilterColumns`, `computedColFilters` is nil.  Just because we've defined a computed column in a table doesn't mean we'll have a filter on the columns referenced in the expression defining it (in this case, columns `a` and `b`).
</blockquote></details>

I see - the computed column expressions aren't part of the `optionalFilters` because they contain non-constants. Sorry for the confusion.

I'd recommend using the outer columns of the shared properties that we already compute when we add a computed column expression to the metadata. For example, change the signature of `TableMeta.AddComputedCol` to this:

```
func (tm *TableMeta) AddComputedCol(colID ColumnID, computedCol ScalarExpr, outerCols ColSet)
```

And change this line: https://github.com/cockroachdb/cockroach/blob/4539072e48942b77721b1e3044235c1013266dc4/pkg/sql/opt/optbuilder/select.go#L879

To this:

```
tabMeta.AddComputedCol(colID, scalar, sharedProps.OuterCols)
```

And you can populate `ColsInComputedColsExpressions` without the tree walking code and optgen changes.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NUvXWvq8G9d42SsR_0j:b-wsvas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> what is the non-single-key span

The non-single-key span is `[/5 - ]`

> and what happens to it in the constructed filter?

It is ignored because it can't be used to derive any terms, and it is ANDed with other terms (so can be safely ignored).
So, from `(a,b) IN ((3,4), (5,6))` we derive:
```
((a IS NOT DISTINCT FROM 3 AND b IS NOT DISTINCT FROM 4 AND c IS NOT DISTINCT FROM 7) OR
 (a IS NOT DISTINCT FROM 5 AND b IS NOT DISTINCT FROM 6 AND c IS NOT DISTINCT FROM 11))
```
and our final set of filters is:
```
(a,b) IN ((3,4), (5,6)) AND 
a > 4 AND
((a IS NOT DISTINCT FROM 3 AND b IS NOT DISTINCT FROM 4 AND c IS NOT DISTINCT FROM 7) OR
 (a IS NOT DISTINCT FROM 5 AND b IS NOT DISTINCT FROM 6 AND c IS NOT DISTINCT FROM 11))
```

The key point is that skipping over the `a > 4 ` term does not remove it from the pre-existing filters, so it will still be applied.

</blockquote></details>

Thanks for the explanation.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NUvYIp-0t888rVVZm68:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Simplified it by making `buildConjunctionFromConstraint` create a brand new map each time it's called and return the constructed map to the caller.  This way no other maintenance on the map is required.
</blockquote></details>

Nice, thanks!


<!-- Sent from Reviewable.io -->

2023-05-10 18:47 UTC, msirek reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NV5y3oED7ptnIAmVm4t:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/vars.go` line 2589 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NUvZKtCEUoU7snmoc8a:-NV5xGJMAJDudE_UnoZP:b-h87bho) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc8dbc47fb49c2f7d8fabf6ba5b7a3f533ba9612/pkg/sql/vars.go#L2589)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: if you wanted to shorten this, you could use "derive" as the verb, like `optimizer_derive_improved_computed_column_filters`.
</blockquote></details>

That's possible, but that name would read as if the filters have been improved (i.e., we previously derived filters which were not so good, and now they are better). But really it's the derivation method itself that has been improved so that we derive filters in more cases.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfnLCU3tJAngDSJZTc:-NV5bpK9A8e8plTLTDfW:b-4pdpcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L388)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see - the computed column expressions aren't part of the `optionalFilters` because they contain non-constants. Sorry for the confusion.

I'd recommend using the outer columns of the shared properties that we already compute when we add a computed column expression to the metadata. For example, change the signature of `TableMeta.AddComputedCol` to this:

```
func (tm *TableMeta) AddComputedCol(colID ColumnID, computedCol ScalarExpr, outerCols ColSet)
```

And change this line: https://github.com/cockroachdb/cockroach/blob/4539072e48942b77721b1e3044235c1013266dc4/pkg/sql/opt/optbuilder/select.go#L879

To this:

```
tabMeta.AddComputedCol(colID, scalar, sharedProps.OuterCols)
```

And you can populate `ColsInComputedColsExpressions` without the tree walking code and optgen changes.
</blockquote></details>

Thanks, I've updated the code as suggested.  I left the `VariableExpr` interface in, because I think it would be very useful for helping avoid circular dependencies in the future.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfdqWC1ADZ_38lQDyR:-NV5y0Y70P4Z_nRipmHk:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L399)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Thanks for the explanation.
</blockquote></details>

Sure
___
*[`pkg/sql/opt/xform/general_funcs.go` line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NSfl6vTAseouJ4Lzdv7:-NV5y1rK5bFxJ5ngb3-q:blbw6xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dbc61607a12b4eb45658d0f6155aef2306e420/pkg/sql/opt/xform/general_funcs.go#L506)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Nice, thanks!
</blockquote></details>

No problem


<!-- Sent from Reviewable.io -->

2023-05-10 19:55 UTC, mgartner reviewed
> Reviewed 16 of 17 files at r10, 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/opt/metadata.go` line 662 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NV6DU2MDOsMtcoGh88g:-NV6DU2MDOsMtcoGh88h:bcts7jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c02106c03affe16ca11f3a499688b3b3699566/pkg/sql/opt/metadata.go#L662)):*
> ```Go
> 			mappedColsInComputedColsExpressions :=
> 				tabMeta.ColsInComputedColsExpressions.CopyAndMaybeRemap(colMap)
> 			referencedColsInComputedExpressions.UnionWith(mappedColsInComputedColsExpressions)
> ```

We don't need to do this in the loop. We can do a single remap outside the loop:

```sql
referencedColsInComputedExpressions = tabMeta.ColsInComputedColsExpressions.CopyAndMaybeRemap(colMap)
```
___
*[`pkg/sql/opt/operator.go` line 107 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NV6BeBV-ntguM6pv6Up:-NV6BeBW2Fc7eGEVl9bb:bplale9) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c02106c03affe16ca11f3a499688b3b3699566/pkg/sql/opt/operator.go#L107)):*
> ```Go
> // VariableExpr is a variable expression, which is an expression that represents
> // a column reference.
> type VariableExpr interface {
> ```

I think we should leave this and the optgen changes out until we have a use-case that needs it. No reason to have dead code.


<!-- Sent from Reviewable.io -->

2023-05-10 22:03 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/metadata.go` line 662 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NV6DU2MDOsMtcoGh88g:-NV6fHBL9I-i9CyDHTWO:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c02106c03affe16ca11f3a499688b3b3699566/pkg/sql/opt/metadata.go#L662)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We don't need to do this in the loop. We can do a single remap outside the loop:

```sql
referencedColsInComputedExpressions = tabMeta.ColsInComputedColsExpressions.CopyAndMaybeRemap(colMap)
```
</blockquote></details>

Done
___
*[`pkg/sql/opt/operator.go` line 107 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NV6BeBV-ntguM6pv6Up:-NV6fKh-6WwXeSviDOTZ:b-y02lq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/58c02106c03affe16ca11f3a499688b3b3699566/pkg/sql/opt/operator.go#L107)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think we should leave this and the optgen changes out until we have a use-case that needs it. No reason to have dead code.
</blockquote></details>

OK, removed it


<!-- Sent from Reviewable.io -->

2023-05-15 15:11 UTC, mgartner approved these changes
Nice! <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 20 of 20 files at r12, 11 of 11 files at r13, 14 of 14 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NVUxkelBkIOyERAEhhy:b-mb3vxt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)



<!-- Sent from Reviewable.io -->

2023-05-15 21:47 UTC, msirek reviewed
TFTR!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100242#-:-NVWNY-W2arhPQZS5RV_:bihs03x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @rytaft)



<!-- Sent from Reviewable.io -->

2023-05-15 23:11 UTC, merged

2023-05-18 18:41 UTC, msirek commented
This fix has been backported, so should be available in v23.1.2 and v22.1.10, but it is disabled by default in those releases. To enable it, the following session setting must be set to true:
```sql
SET optimizer_use_improved_computed_column_filters_derivation = true;
```