roachtest: allow callers to cancel background steps in mixedversion
cockroachdb/cockroach pull request #100754
Opened 2023-04-05 21:05 UTC by renatolabs

This commit updates the signature of functions in the `mixedversion` package that create steps that run in the background; this includes functions in the `Helper` struct, as well as in the main `mixedversion.Test` struct. These functions now all return a `mixedversion.StopFunc` that test authors can call when they wish to stop a background function without causing the test to fail.

When the stop function is called, the context passed to the background functions is canceled; however, that context cancelation is captured by the framework and logged as an expected termination. If the context is canceled through other means, the test will fail as usual.

Epic: CRDB-19321

Release note: None

2023-04-05 21:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/100754)
<!-- Reviewable:end -->

2023-04-05 21:20 UTC, renatolabs commented
This is a stacked PR, please review them in order (but feel free to review the second one before the first one is merged):

* #100754 **(this PR)**
* #100755 

To be reviewed here: the entire diff.

2023-04-24 11:42 UTC, herkolategan requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmK0293hTVZGgXHNWQ:-NTmK0293hTVZGgXHNWR:b-g6cyr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel#L25)):*
> ```Starlark
>         "//pkg/util/timeutil",
>         "//pkg/util/version",
>         "@com_github_pkg_errors//:errors",
> ```

Any reason not to opt for `github.com/cockroachdb/errors`, since `roachtest` already uses it.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmV8Yh1JkoIWWHRKYO:-NTmV8Yh1JkoIWWHRKYP:bcxsnv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L229)):*
> ```Go
> 		// cancel the underlying context.
> 		//
> 		// There should be one channel in `bgChans` for each hook in
> ```

Nit: `should be` put doubts in my head for some reason. "There is one channel in `bgChans` for each"... might be more assuring.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmbdRAB53VxuBO9c3n:-NTmbdRAB53VxuBO9c3o:brh2a1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L238)):*
> ```Go
> 	}
> 
> 	shouldStop chan struct{}
> ```

I've noticed we have a util `Stopper` which is used in `roachtest` (https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L71)
It might be a bit heavy weight, or not fit this scenario, just curious if you considered it along the way?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmw9rB0OAkM_waib6o:-NTmw9rB0OAkM_waib6p:bl0bnkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go#L34)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/ctxgroup"
> 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
> 	"github.com/pkg/errors"
> ```

Ref to question regarding `cockroachdb/errors` above.


<!-- Sent from Reviewable.io -->

2023-04-24 17:42 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmK0293hTVZGgXHNWQ:-NToLImq7904fG7rm-29:bwmcrop) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel#L25)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Any reason not to opt for `github.com/cockroachdb/errors`, since `roachtest` already uses it.
</blockquote></details>

Huh, that's what I meant to have used, something went wrong with my auto import. Thanks for catching, fixed.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmV8Yh1JkoIWWHRKYO:-NToLUnIDC8TpREfb_HJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L229)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Nit: `should be` put doubts in my head for some reason. "There is one channel in `bgChans` for each"... might be more assuring.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmbdRAB53VxuBO9c3n:-NToLWKM0DT_uQLLRh9n:b-44gyso) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L238)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

I've noticed we have a util `Stopper` which is used in `roachtest` (https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L71)
It might be a bit heavy weight, or not fit this scenario, just curious if you considered it along the way?
</blockquote></details>

I'm a little ambivalent on this one. `Stopper` has a lot of features we wouldn't need here, and the semantics don't quite line up exactly. Stopper lets you stop all tasks whereas here we want the ability to stop functions individually. So if we used `Stopper`, we'd need one stopper for each function, and the code wouldn't be signficantly simpler after the change.


<!-- Sent from Reviewable.io -->

2023-04-24 18:36 UTC, smg260 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 722 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToTt1JCJxQjk7JvRIo:-NToTt1JCJxQjk7JvRIp:b-7wtkym) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L722)):*
> ```Go
> // hook is run concurrently. `stopChans` should either be `nil` for
> // steps that are not meant to be run in the background, or contain
> // one stop channel (`shouldStop`) for each hook.
> ```

Can this be made into an assertion/check? Seems like it could be subject to misuse resulting in an invalid slice index.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToUsXRDidrYZ4F8ldt:-NToUsXRDidrYZ4F8ldu:b-hklzh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L745)):*
> ```Go
> 	}
> 
> 	if len(steps) <= 1 {
> ```

Semantically does a single hook run in the same way as multiple hooks concurrently? 

If so, is this branch necessary?


<!-- Sent from Reviewable.io -->

2023-04-24 20:02 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 722 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToTt1JCJxQjk7JvRIo:-NTop-oY9cSuU5WE8FIT:b-x239r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L722)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Can this be made into an assertion/check? Seems like it could be subject to misuse resulting in an invalid slice index.
</blockquote></details>

This would only result in an error if there's an internal error (internal to the `mixedversion` package, not exposed by any public API). If there's such an error and we get a panic, arguably that's ok since we'll get a stack trace.

I might be misunderstanding your suggestion, please clarify if so.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToUsXRDidrYZ4F8ldt:-NTopedz0sZBJo0eNwa0:b5h97gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L745)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Semantically does a single hook run in the same way as multiple hooks concurrently? 

If so, is this branch necessary?
</blockquote></details>

Depends on what's implied by "the same way".

If you're asking why we don't just use `concurrentRunStep` in the single step case, the reason is mostly so that the test plan generated is be more readable, i.e., so that we're able to say:

```
- downgrade node 2 to 22.2
- run "func A"
- downgrade node 3 to 22.2
```

instead of 

```
- downgrade node 2 to 22.2
- run steps concurrently:
    - run "func A"
- downgrade node 3 to 22.2
```

These "single concurrent runs" would add up and get noisy without providing much value or clarity.


<!-- Sent from Reviewable.io -->

2023-04-24 20:20 UTC, smg260 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 722 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToTt1JCJxQjk7JvRIo:-NTotqQLEYaA3yfpvdI0:bw3z7aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L722)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This would only result in an error if there's an internal error (internal to the `mixedversion` package, not exposed by any public API). If there's such an error and we get a panic, arguably that's ok since we'll get a stack trace.

I might be misunderstanding your suggestion, please clarify if so.
</blockquote></details>

More a general comment about the function being susceptible to a caller breaking the implied (via the comment) contract, however if its more of an internal helper function, not a big deal.

e.g. Would it not be possible for someone to pass a `stopChans` satisfying` 0 < len(stopChans) <  len(hooks)`, in which case the `stopChanFor` function would behave incorrectly?
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToUsXRDidrYZ4F8ldt:-NToszoW5u199Y2-J5tX:bdw4qls) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L745)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Depends on what's implied by "the same way".

If you're asking why we don't just use `concurrentRunStep` in the single step case, the reason is mostly so that the test plan generated is be more readable, i.e., so that we're able to say:

```
- downgrade node 2 to 22.2
- run "func A"
- downgrade node 3 to 22.2
```

instead of 

```
- downgrade node 2 to 22.2
- run steps concurrently:
    - run "func A"
- downgrade node 3 to 22.2
```

These "single concurrent runs" would add up and get noisy without providing much value or clarity.
</blockquote></details>

That makes sense, but since its just for output aesthetics, would it not make sense to decorate when generating the test plan? i.e. during test plan generation, if a concurrent step with only one step is encountered, you could print appropriately?

Not a deal breaker. More of a thought. 


<!-- Sent from Reviewable.io -->

2023-04-25 08:56 UTC, herkolategan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NTmbdRAB53VxuBO9c3n:-NTrbveW5WJt-OnlMi5c:bd6gyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/317a9d84c7f8a570a75e2ea30a41423549009446/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L238)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm a little ambivalent on this one. `Stopper` has a lot of features we wouldn't need here, and the semantics don't quite line up exactly. Stopper lets you stop all tasks whereas here we want the ability to stop functions individually. So if we used `Stopper`, we'd need one stopper for each function, and the code wouldn't be signficantly simpler after the change.
</blockquote></details>

Makes sense, I agree the simplicity fits better here.


<!-- Sent from Reviewable.io -->

2023-04-25 15:51 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 722 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToTt1JCJxQjk7JvRIo:-NTt5hAI9AvkRvjSWDh1:b-2y5qb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L722)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

More a general comment about the function being susceptible to a caller breaking the implied (via the comment) contract, however if its more of an internal helper function, not a big deal.

e.g. Would it not be possible for someone to pass a `stopChans` satisfying` 0 < len(stopChans) <  len(hooks)`, in which case the `stopChanFor` function would behave incorrectly?

</blockquote></details>

The only way this could happen is if there's a programming error in the `mixedversion` package (since the management of `hooks` and `stopChans` happen inside the package, they are both private fields not directly manipulated by callers). If the size of `stopChans` were in the range above, the function will panic and I think that's ok, it should only happen if there's a bug in the framework and trying to account for it might be too defensive (we'd just return an error anyway -- a panic is probably better since it halts execution exactly at the point where the assumption is not held).
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go` line 745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100754#-NToUsXRDidrYZ4F8ldt:-NTt59pVBl9le52htWpH:b-klzanh) ([raw file](https://github.com/cockroachdb/cockroach/blob/90d840d56cb054c54f914d0a31c1bdcde28b75e4/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L745)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

That makes sense, but since its just for output aesthetics, would it not make sense to decorate when generating the test plan? i.e. during test plan generation, if a concurrent step with only one step is encountered, you could print appropriately?

Not a deal breaker. More of a thought. 
</blockquote></details>

It could be handled at the presentation level, though I think it doesn't necessarily improves things much. I also plan to change this part of the code in the near future: right now when multiple user hooks are expected to run at the same time, they always run concurrently; I want them to run sequentially sometimes too. I'll consider changing how this is handled when I make that change.


<!-- Sent from Reviewable.io -->

2023-04-25 19:29 UTC, smg260 approved these changes
> Reviewed 3 of 9 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)



<!-- Sent from Reviewable.io -->

2023-04-25 20:02 UTC, renatolabs commented
TFTR!

bors r=smg260

2023-04-25 20:04 UTC, herkolategan approved these changes

2023-04-25 20:06 UTC, renatolabs commented
bors r=smg260,herkolategan

2023-04-25 22:30 UTC, merged