kv: Add stats for delegate snapshots
cockroachdb/cockroach pull request #100762
Opened 2023-04-05 21:41 UTC by andrewbaptist

This PR adds two new stats for delegate snapshots to track failure of sending snapshots. There are failures either before data is transferred or after the snapshot is received. Both stats are useful.

Epic: none

Release note: None

2023-04-05 21:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/100762)
<!-- Reviewable:end -->

2023-04-11 13:53 UTC, kvoli requested changes
Some nits and questions.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-:-NSka-LcDHSXzHG3eUK_:b-vx3mev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSh_HOz7H8ou6lGNNoz):*
Could you include the metric names in the commit and also release note. EDIT: Looks like they were added in a previous commit - It would still be good to include the affected metric names here.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSh_OguBgR4U1tQaplS):*
nit: explain what they might be used for here.
___
*[`pkg/kv/kvserver/store_snapshot.go` line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSk_BVY3qCWsb67hMcb:-NSk_BVY3qCWsb67hMcc:btws0lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/store_snapshot.go#L1057)):*
> ```Go
> 		defer ss.Close(ctx)
> 	default:
> 		return sendSnapshotError(s, stream,
> ```

Should `sendSnapshotError` be renamed to `receiveSnapshotError`? I notice that down below we are bumping `s.metrics.RangeSnapshotRecvFailed.Inc(1)` but the function is called `sendXXX`. 
___
*[`pkg/kv/kvserver/store_snapshot.go` line 1060 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkYD-_32BKSS6zuZB3:-NSkYD-_32BKSS6zuZB4:b43y2x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/store_snapshot.go#L1060)):*
> ```Go
> 			errors.Errorf("%s,r%d: unknown snapshot strategy: %s",
> 				s, header.State.Desc.RangeID, header.Strategy),
> 			rec,
> ```

Why not put `sp.GetConfiguredRecording()` here? Is there any overhead to calling  `GetConfiguredRecording` when not necessary (not error case)?
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSha22P-k5fO8Pl7OCt:-NSha22P-k5fO8Pl7OCu:b-lsc6sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L379)):*
> ```Go
> // enough. There are two reasons this is inconsistent.
> // 1) Raft snapshots still sometimes sneak in. (#96841)
> // 2) THe delegate hasn't since the updated descriptor in time.
> ```

nit: 'The'.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUJ5A8Fiu_Pr6g6Qw:-NSkUJ5A8Fiu_Pr6g6Qx:b-iajhzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L379)):*
> ```Go
> // enough. There are two reasons this is inconsistent.
> // 1) Raft snapshots still sometimes sneak in. (#96841)
> // 2) THe delegate hasn't since the updated descriptor in time.
> ```

nit: seen.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUYfMEY9hpdo3GSfd:-NSkUYfMEY9hpdo3GSfe:b-ihho9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L611)):*
> ```Go
> 		desc := tc.AddVotersOrFatal(t, scratchKey, tc.Targets(2, 3)...)
> 
> 		store3, _ := desc.GetReplicaDescriptor(3)
> ```

Why did you remove the assertion that the replica descriptor was found?
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUjoxAxDvWsHyTBXi:-NSkUjoxAxDvWsHyTBXj:b-7kooul) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L655)):*
> ```Go
> 
> 		// Add a replica that will be the delegated sender, and another so we have
> 		// quorum with this node down
> ```

nit: period.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkVqXf9q1aAGpGqJ9n:-NSkVqXf9q1aAGpGqJ9o:b-zbqe6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L680)):*
> ```Go
> 		})
> 	})
> 	// Test that the delegate that doesn't have
> ```

nit: Complete comment.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkWYNg2edgOz3BoX9a:-NSkWYNg2edgOz3BoX9b:b-ood83x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L777)):*
> ```Go
> 		senders.desc = append(senders.desc, store1)
> 		senders.mu.Unlock()
> 		// First try to use node 3 (index 2) as the delegate, but fall back to the leaseholder on failure.
> ```

The code above has store 4 first, then store 1 - I don't see node 3 anywhere. Are you referring to 0 indexed server 3?


<!-- Sent from Reviewable.io -->

2023-04-17 14:38 UTC, andrewbaptist reviewed
TFTR! A lot of good catches. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-:-NTEdV-Z41mul4bTYDe1:bvt6qcf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSh_HOz7H8ou6lGNNoz):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Could you include the metric names in the commit and also release note. EDIT: Looks like they were added in a previous commit - It would still be good to include the affected metric names here.
</blockquote></details>

Added them to the release notes and fixed a bug where one was misnamed in the metadata.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSh_OguBgR4U1tQaplS):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: explain what they might be used for here.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/store_snapshot.go` line 1057 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSk_BVY3qCWsb67hMcb:-NTE_zRi-Fni8lf-gI5u:b-task03) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/store_snapshot.go#L1057)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should `sendSnapshotError` be renamed to `receiveSnapshotError`? I notice that down below we are bumping `s.metrics.RangeSnapshotRecvFailed.Inc(1)` but the function is called `sendXXX`. 
</blockquote></details>

This is a little confusing. The method is saying that it is "sending a snapshot error" back to the recipient, however, this node is the receiver, so it is updating the counter tracking that it received a snapshot in error. I added a comment to make this more clear on that method.
___
*[`pkg/kv/kvserver/store_snapshot.go` line 1060 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkYD-_32BKSS6zuZB3:-NTEbhflDZIRoM1cMrvy:b-n5v4hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/store_snapshot.go#L1060)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why not put `sp.GetConfiguredRecording()` here? Is there any overhead to calling  `GetConfiguredRecording` when not necessary (not error case)?
</blockquote></details>

Good idea, thanks! Changed to keep the calls to `GetConfiguredRecording` close to their usage.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSha22P-k5fO8Pl7OCt:-NTEc58a2CyVZDILYZz8:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L379)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: 'The'.
</blockquote></details>

Fixed
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUJ5A8Fiu_Pr6g6Qw:-NTEcCaXDuyper52QKBf:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L379)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: seen.
</blockquote></details>

Fixed
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUYfMEY9hpdo3GSfd:-NTEcYG5Cn7BpY-lql22:b-awlhq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L611)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Why did you remove the assertion that the replica descriptor was found?
</blockquote></details>

I'm not sure - I added them back. I may have been handling the case where there was a race with that store not having it, but I didn't need that to be in the final version.
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 655 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkUjoxAxDvWsHyTBXi:-NTEd0ol0EMapyx8EZZb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L655)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: period.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkVqXf9q1aAGpGqJ9n:-NTEdTQQ2Y-adB1Iw3Yp:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L680)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: Complete comment.
</blockquote></details>

Fixed
___
*[`pkg/kv/kvserver/replica_learner_test.go` line 777 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-NSkWYNg2edgOz3BoX9a:-NTEdQJG340-C9TXPl5c:b9xzxy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d11d509a8d06d2a810e2979f09d6aa2515ca701f/pkg/kv/kvserver/replica_learner_test.go#L777)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The code above has store 4 first, then store 1 - I don't see node 3 anywhere. Are you referring to 0 indexed server 3?
</blockquote></details>

I fixed the comment. Thanks!


<!-- Sent from Reviewable.io -->

2023-04-18 04:29 UTC, kvoli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100762#-:-NTHbyTx4nM-I9owZyyZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)



<!-- Sent from Reviewable.io -->

2023-04-18 13:59 UTC, merged