cdc: fix sarama case sensitivity
cockroachdb/cockroach pull request #100929
Opened 2023-04-07 17:44 UTC by HonoreDB

Fixes #100706 by lowercasing compression codecs and passing them through transparently to Sarama rather than doing our own validation.

Release note (enterprise change): The kafka_sink_config Compression and RequiredAcks options are now case-insensitive.

2023-04-07 17:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/100929)
<!-- Reviewable:end -->

2023-04-07 18:05 UTC, miretskiy requested changes

2023-04-07 18:05 UTC, miretskiy commented on pkg/ccl/changefeedccl/sink_kafka.go
> +	*j = compressionCodec(c)
how does that work? Isn't c always == none?

2023-04-10 15:41 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100929#gh-1160869046:-NSfoAky5Su1kO_ISs9E:b-sz4lrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/71afbb8ce4925ab50efc32865890d51795f46b6d/pkg/ccl/changefeedccl/sink_kafka.go#L148)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can we not do this?  iterate until we get out of bounds error
and then catch it... Just not necessary.

I don't understand why we can't just call toUpper when doing validation.

If you are worried about upgrading sarama (and it claims to support new codec that we don't know about), then just write a test -- basically what you have here, that goes through every 
compression code and makes sure that we have thhat codec in the saramCompressionCodecOptions.

</blockquote></details>

Done. That was indeed the worry, I've moved it to a test.
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100929#gh-1160869660:-NSfoH_jAwX87PyvnhUb:b-ady1zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/71afbb8ce4925ab50efc32865890d51795f46b6d/pkg/ccl/changefeedccl/sink_kafka.go#L161)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

how does that work? Isn't c always == none?
</blockquote></details>

c.UnmarshalText is a pointer method that sets c.


<!-- Sent from Reviewable.io -->

2023-04-10 15:49 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100929)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)



<!-- Sent from Reviewable.io -->

2023-04-25 18:11 UTC, HonoreDB commented
bors r=[miretskiy]

2023-04-25 18:45 UTC, merged