ttl: remove deprecated TTLSpec.AOST field
cockroachdb/cockroach pull request #101119
Opened 2023-04-10 16:02 UTC by ecwall

Fixes #101104

This change removes `TTLSpec.AOST` in 23.2 which was needed for 22.2/23.1 compatibility.

Release note: None

2023-04-10 16:03 UTC, ecwall commented on pkg/sql/execinfrapb/processors_ttl.proto
> -  // TODO(ewall): remove in 24.1
Compatibility was required until 24.1 when this comment was made, but is now only needed until 23.2.

2023-04-10 16:11 UTC, rafiss requested changes
As per the new support for version skipping (see [groups.google.com/a/cockroachlabs.com/g/eng/c/Y-YahlK5jsE/m/X2u6KOdwAQAJ](https://groups.google.com/a/cockroachlabs.com/g/eng/c/Y-YahlK5jsE/m/X2u6KOdwAQAJ)), I think we need to wait until the 23.2 release is out to do this.

in other words, users can go from 22.2 directly to 23.2

2023-04-11 21:36 UTC, ecwall commented
Putting on hold until 24.1 then.

2023-10-10 15:09 UTC, andyyang890 commented
I think this still needs to wait until `BinaryMinSupportedVersionKey` is bumped up to `V23_1`, not sure if that's going to happen immediately after branch cut.

2023-10-10 16:26 UTC, ecwall commented
> I think this still needs to wait until `BinaryMinSupportedVersionKey` is bumped up to `V23_1`, not sure if that's going to happen immediately after branch cut.

This doesn't depend on a version gate. We just need to make sure that it is merged after the branch cut so that it does not go in a 23.2 release.

2023-10-10 19:03 UTC, rafiss approved these changes

2023-10-10 19:15 UTC, ecwall commented
bors r=rafiss

2023-10-10 19:51 UTC, merged