ttl: allow inbound foreign keys on TTL tables
cockroachdb/cockroach pull request #101376
Opened 2023-04-12 19:28 UTC by ecwall

Fixes #76407

This change allows TTL tables to have inbound foreign keys. If the inbound foreign key has the ON DELETE CASCADE option, the TTL job will work as usual. If it has the ON DELETE RESTRICT option, the TTL job will fail if a row references the TTL table (see #101372).

Release note (sql change): Allow inbound foreign keys on TTL tables.

2023-04-12 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/101376)
<!-- Reviewable:end -->

2023-04-13 17:25 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101376)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @otan)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101376#-NSvdJE1-fVvmy_yema5):*
it seems like it would be better if we kept some of the TTL validation -- if there are inbound foreign keys with `RESTRICT`, then enabling TTL should be prevented. do you have a preference for allowing it but showing errors?


<!-- Sent from Reviewable.io -->

2023-04-13 18:15 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101376)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101376#-NSvdJE1-fVvmy_yema5):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems like it would be better if we kept some of the TTL validation -- if there are inbound foreign keys with `RESTRICT`, then enabling TTL should be prevented. do you have a preference for allowing it but showing errors?
</blockquote></details>

I thought about that, but I think the validation will either be pretty complex or incomplete because foreign keys with RESTRICT can be transitive:
```
CREATE TABLE level0 (id int PRIMARY KEY);
CREATE TABLE

CREATE TABLE level1 (id int PRIMARY KEY, level0_id int REFERENCES level0 (id) ON DELETE CASCADE);
CREATE TABLE

CREATE TABLE level2 (id int PRIMARY KEY, level1_id int REFERENCES level1 (id) ON DELETE RESTRICT);
CREATE TABLE

INSERT INTO level0 VALUES (0);
INSERT 0 1

INSERT INTO level1 VALUES (1, 0);
INSERT 0 1

INSERT INTO level2 VALUES (2, 1);
INSERT 0 1

DELETE FROM level0 WHERE id = 0;
ERROR: delete on table "level1" violates foreign key constraint "level2_level1_id_fkey" on table "level2"
SQLSTATE: 23503
DETAIL: Key (id)=(1) is still referenced from table "level2".
CONSTRAINT: level2_level1_id_fkey
```

I created #101372 to decide out how to handle this gracefully which I'll be working on next. I think we can probably just support this use case properly by ignoring these rows with about the same amount of complexity as adding validation to block the use case.


<!-- Sent from Reviewable.io -->

2023-04-13 18:40 UTC, rafiss approved these changes
cool, i'm fine with resolving it in that issue

2023-04-13 19:16 UTC, ecwall commented
bors r=rafiss

2023-04-13 22:39 UTC, ecwall commented
bors r=rafiss

2023-04-13 23:42 UTC, merged

2023-05-02 08:58 UTC, zepatrik commented
@ecwall do you know when this will be released? Will this be part of v23 or included in some minor release on v22?

2023-06-20 20:31 UTC, dikshant commented
@zepatrik This has been in since 23.1.2 which is now out. Latest is 23.1.3.
https://www.cockroachlabs.com/docs/releases/index.html#production-releases

2023-06-22 13:08 UTC, ecwall commented
> @zepatrik This has been in since 23.1.2 which is now out. Latest is 23.1.3. https://www.cockroachlabs.com/docs/releases/index.html#production-releases

This PR has not been backported. https://www.cockroachlabs.com/docs/releases/v23.1#v23-1-2-sql-language-changes mentions outbound foreign keys.

2023-06-22 13:12 UTC, ecwall commented
Backporting to 23.1 as this has been asked for on community slack also https://cockroachdb.slack.com/archives/CP4D9LD5F/p1687429303145649?thread_ts=1687353826.783279&cid=CP4D9LD5F