ui: display configurable timezone in DB Console
cockroachdb/cockroach pull request #101752
Opened 2023-04-18 15:14 UTC by zachlite

This commit makes it so all timestamps displayed in DB Console (with the exception of Advanced Debug pages) use the timezone set by the cluster setting `ui.display_timezone`.

Only Coordinated Universal Time and America/New_York are supported. Supporting additional timezones can be achieved by adding more timezones to the enum passed to `ui.display_timezone` when the setting is registered, and modifying the webpack configs to make sure the relevant timezone data is included. See #99848 for more details.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-5536 
Release note (ui): Added the ability for users to view timestamps in DB Console in their preferred timezone via the cluster setting `ui.display_timezone`. Currently supported timezones are Coordinated Universal Time and America/New_York.

Loom: https://www.loom.com/share/9533173bf68e45f4ac6a09860b04b98a

2023-04-18 15:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/101752)
<!-- Reviewable:end -->

2023-04-19 15:09 UTC, maryliag requested changes
Great work!
We have two cases of formats:
- When is just a value (on details page for example), and in this case we want to show the date with the timezone label. This case is working as expected by your PR. For this cases the format is the `DATE_FORMAT_24_TZ`

- Tables that have a timestamp: because all of the values on the column would have the same timezone, adding to it every time is just using extra space without adding new information, which increases the horizontal scrolling without the need. On this cases we add the timezone label on the column title and then the values don't have the label. You would use the format `DATE_FORMAT`. We do have some examples of column name where we pass a value and the title will change it (check Statement time/Transaction time), so you can do a similar thing here and pass the timezone label to the columns that you removed the `(UTC)` on this PR and use the correct label instead.

> Reviewed 75 of 75 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-:-NTP22D64B2EdQi3Yflj:b5ztwdk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)



<!-- Sent from Reviewable.io -->

2023-04-19 16:03 UTC, xinhaoz reviewed
Initial pass and looks great! Just one comment about the `yarn.lock`

2023-04-20 10:57 UTC, koorosh reviewed
> Reviewed 75 of 75 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT1Mo0C_FGysnNwDMS):*
Is it documented somewhere in the code for future us?
`modifying the webpack configs` might not be so obvious to update
so would like to know that it is mentioned somewhere.
___
*[`pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT30kt9fGWhgqqiOn-:-NTT30kt9fGWhgqqiOn0:b-4fksyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts#L122)):*
> ```XML
>     const closestDataPointTimeMillis = u.data[0][u.posToIdx(left)];
>     timeStamp.textContent = FormatWithTimezone(
>       moment(closestDataPointTimeMillis),
> ```

should we check `closestDataPointTimeMillis` for valid value?
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT987DAqCT7kPnIrGs:-NTT987DAqCT7kPnIrGt:bllwk3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L306)):*
> ```XML
>   }
> 
>   private getTimestampString(timestamp: Moment) {
> ```

nit. Since this method doesn't return string anymore, I suggest to rename it (ie `getTimestampComp`?)
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightDetailsTables.tsx` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT9evsB0UAxd1u-Vm0:-NTT9evsB0UAxd1u-Vm1:b-4l71pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightDetailsTables.tsx#L78)):*
> ```XML
>       cell: (item: ContentionEvent) =>
>         item.startTime ? (
>           <Timestamp
> ```

nit. it is common pattern to use ternary operator to handle Null values. `Timestamp` component could manage this case internally I suppose.
```
<Timestamp time={} format={} failbackString={"N/A"} />
```
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTFQGI0JBeKQPYQblc:-NTTFQGI0JBeKQPYQbld:b-jl0lsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L64)):*
> ```XML
> }
> 
> interface InternalProps extends LineGraphProps, WithTimezoneProps {}
> ```

Suggesting to use `Type` over `interface` here.
`InternalProps` includes both LineGraphProps and WithTimezoneProps, so in fact that is a union of props that are exported with wrapped component and is not internal.
- use `LineGraphProps` type as exported props of wrapped component;
- use `OwnProps` (common naming convention for components wrapped in HOCs) instead of `LineGraphProps`;

```typescript

export interface OwnProps extends MetricsDataComponentProps { 
...
}

export type LineGraphProps = OwnProps & WithTimezoneProps;

```
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTEJVu2usHZNhgBu_8:-NTTEJVv9m8Y483uQ5mY:b-rom0rh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L160)):*
> ```XML
> // Once we receive updates to props, we push new data to the
> // uPlot object.
> export class _LineGraph extends React.Component<InternalProps, {}> {
> ```

`_LineGraph` is it a JS naming convention? 🤔 
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/events/index.tsx` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTHrz76z7EkI5IsMq5:-NTTHrz76z7EkI5IsMq6:b460m75) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/containers/events/index.tsx#L81)):*
> ```XML
> export const EventRow = (props: EventRowProps) => {
>   const { event } = props;
>   const timezone = useContext(TimezoneContext) as string;
> ```

Why it is explicitly casted to `string`? Should it return string anyway?


<!-- Sent from Reviewable.io -->

2023-04-24 18:19 UTC, zachlite reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @maryliag, and @xinhaoz)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT1Mo0C_FGysnNwDMS):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Is it documented somewhere in the code for future us?
`modifying the webpack configs` might not be so obvious to update
so would like to know that it is mentioned somewhere.
</blockquote></details>

I mention it here: https://github.com/cockroachdb/cockroach/blob/a2f31ca7e486c9c5f338db59c17df5fa8ab13690/pkg/ui/ui.go#L49
___
*[`pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT30kt9fGWhgqqiOn-:-NToM0H65_DUDjd_W6eh:b-usrp8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/plugins.ts#L122)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

should we check `closestDataPointTimeMillis` for valid value?
</blockquote></details>

I don't think this value can be invalid.
___
*[`pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx` line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT987DAqCT7kPnIrGs:-NToM7EC3zh1Qti2-QyV:b-iy7f2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx#L306)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. Since this method doesn't return string anymore, I suggest to rename it (ie `getTimestampComp`?)
</blockquote></details>

Changed to `getTimestamp`
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightDetailsTables.tsx` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTT9evsB0UAxd1u-Vm0:-NToMXio7mGUoCvtZe_0:bu3j19v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightDetailsTables.tsx#L78)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. it is common pattern to use ternary operator to handle Null values. `Timestamp` component could manage this case internally I suppose.
```
<Timestamp time={} format={} failbackString={"N/A"} />
```
</blockquote></details>

Good suggestion. Implemented!
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTFQGI0JBeKQPYQblc:-NToMUAf6gZt0E0YwDYj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L64)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Suggesting to use `Type` over `interface` here.
`InternalProps` includes both LineGraphProps and WithTimezoneProps, so in fact that is a union of props that are exported with wrapped component and is not internal.
- use `LineGraphProps` type as exported props of wrapped component;
- use `OwnProps` (common naming convention for components wrapped in HOCs) instead of `LineGraphProps`;

```typescript

export interface OwnProps extends MetricsDataComponentProps { 
...
}

export type LineGraphProps = OwnProps & WithTimezoneProps;

```
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTEJVu2usHZNhgBu_8:-NToTVFy30Z5kAbj-gvA:bvjobs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx#L160)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`_LineGraph` is it a JS naming convention? 🤔 
</blockquote></details>

Renamed with the prefix `Internal`
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/events/index.tsx` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTTHrz76z7EkI5IsMq5:-NToMVgq4y4PAVl15CuG:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0aeeafba7c1ea1e5f77288a4ee3949f01f7c803c/pkg/ui/workspaces/db-console/src/views/cluster/containers/events/index.tsx#L81)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Why it is explicitly casted to `string`? Should it return string anyway?
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2023-04-24 18:54 UTC, koorosh reviewed
> Reviewed 29 of 36 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz and @zachlite)

___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx` line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NToZqsgDV_8QyrCNrCm:-NToZqsgDV_8QyrCNrCn:bc38zhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e11b51ae5a4dec9b8073e692ac326c47d72e29/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L115)):*
> ```XML
> function formatSessionStart(session: ISession) {
>   const start = moment.unix(Number(session.start.seconds)).utc();
>   return <Timestamp time={start} format={DATE_FORMAT} />;
> ```

Should it also use `DATE_FORMAT_24_TZ` format? 
___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTo_36CCY_LWLg0dOZC:-NTo_36CCY_LWLg0dOZD:b-lvm0rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e11b51ae5a4dec9b8073e692ac326c47d72e29/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L126)):*
> ```XML
>     .utc();
> 
>   return <Timestamp time={start} format={DATE_FORMAT} />;
> ```

Should it use `DATE_FORMAT_24_TZ` as well?

Wondering if it possible to setup linter to prohibit usage of `DATE_FORMAT` anywhere except debugging pages...
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx` line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTo_Z6U3Wg3x1nQGBO4:-NTo_Z6U3Wg3x1nQGBO5:b-z5n2tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e11b51ae5a4dec9b8073e692ac326c47d72e29/pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx#L303)):*
> ```XML
>         <Timestamp
>           time={TimestampToMoment(item.stats.last_exec_timestamp)}
>           format={DATE_FORMAT}
> ```

Should it use `DATE_FORMAT_24_TZ` format?
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx` line 325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NTo_sjvBDLX9A_PqVGD:-NTo_sjvBDLX9A_PqVGE:b-z5n2tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e11b51ae5a4dec9b8073e692ac326c47d72e29/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L325)):*
> ```XML
>         <Timestamp
>           time={TimestampToMoment(stmt.stats.last_exec_timestamp)}
>           format={DATE_FORMAT}
> ```

Should it use `DATE_FORMAT_24_TZ` format?


<!-- Sent from Reviewable.io -->

2023-04-24 20:29 UTC, zachlite reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx` line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-NToZqsgDV_8QyrCNrCm:-NTowcebDVsWygRSf0NY:byirsfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7e11b51ae5a4dec9b8073e692ac326c47d72e29/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L115)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Should it also use `DATE_FORMAT_24_TZ` format? 
</blockquote></details>

Marylia requested that anything inside a table column use `DATE_FORMAT`, and that I add the timezone to the column title.


<!-- Sent from Reviewable.io -->

2023-04-24 20:45 UTC, maryliag approved these changes
Nice updates! Looks great!
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 26 of 36 files at r2, 7 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101752#-:-NTp-mud2V17d3lFYWx4:b-z8gcyz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)



<!-- Sent from Reviewable.io -->

2023-04-24 21:21 UTC, merged