sql: add sqlsmith support to test partial visibility of indexes
cockroachdb/cockroach pull request #101861
Opened 2023-04-19 18:53 UTC by rytaft

Sometimes generate a partially invisible index instead of a fully invisible index.

Informs #82363

Release note: None

2023-04-19 18:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/101861)
<!-- Reviewable:end -->

2023-04-20 13:34 UTC, rharding6373 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101861)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @renatolabs, @rytaft, and @srosenberg)

___
*[`pkg/internal/sqlsmith/alter.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-NTTrHPQ6JxuSwL4_V6S:-NTTrHPQ6JxuSwL4_V6T:b-85e1mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4aeea2501cc9a75ceb56c0bff2976ed5d3898a/pkg/internal/sqlsmith/alter.go#L371)):*
> ```Go
> 		visibility = 0.0
> 		if s.coin() {
> 			visibility = rand.Float64() // [0.0, 1.0)
> ```

Use s.rnd to generate the float.
___
*[`pkg/workload/schemachange/operation_generator.go` line 1054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-NTTrwAL6lzZTsMA23Pq:-NTTrwAL6lzZTsMA23Pr:bd1k024) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4aeea2501cc9a75ceb56c0bff2976ed5d3898a/pkg/workload/schemachange/operation_generator.go#L1054)):*
> ```Go
> 		visibility = 0.0
> 		if og.randIntn(2) == 0 {
> 			visibility = rand.Float64()
> ```

Use og.params.rng to generate the float.


<!-- Sent from Reviewable.io -->

2023-04-20 13:40 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once the rand calls are fixed. Thanks for adding this is sqlsmith right away! Fun fact: we're so good at not using rand, that we recently had a test infra bug when we did accidentally use rand where its use ended up not really being random: https://cockroachlabs.slack.com/archives/C02HWA24541/p1677090759256619?thread_ts=1676337090.577609&cid=C02HWA24541

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-:-NTTsTvMBmAL4VP2opT9:b97mbnl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2, @renatolabs, @rytaft, and @srosenberg)



<!-- Sent from Reviewable.io -->

2023-04-20 14:59 UTC, rytaft reviewed
Interesting! TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-:-NTUA3c76F8qNmKFcHl0:b-xman5g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2, @renatolabs, @rharding6373, and @srosenberg)

___
*[`pkg/internal/sqlsmith/alter.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-NTTrHPQ6JxuSwL4_V6S:-NTU9PrU8X9O_P1xliMR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4aeea2501cc9a75ceb56c0bff2976ed5d3898a/pkg/internal/sqlsmith/alter.go#L371)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Use s.rnd to generate the float.
</blockquote></details>

Done.
___
*[`pkg/workload/schemachange/operation_generator.go` line 1054 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101861#-NTTrwAL6lzZTsMA23Pq:-NTU9d3a7O696GXSxVXr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae4aeea2501cc9a75ceb56c0bff2976ed5d3898a/pkg/workload/schemachange/operation_generator.go#L1054)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Use og.params.rng to generate the float.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 15:32 UTC, merged