xform: ensure a DistributeOp is built for uniq checks with enforce_home_region
cockroachdb/cockroach pull request #102103
Opened 2023-04-24 03:45 UTC by msirek

The main mechanism for statically detecting a query has no home region
when the `enforce_home_region` session setting is on is the checking of
the Distribute operation which is built for a query when its operations
don't deal solely with home region rows. For operations embedded as
scalar expressions inside mutation ops (for performing uniqueness checks
and foreign key checks), since there is no required distribution when
optimizing these, the Distribute Op is never built, so these checks     
may fail to enforce the home region when the plan doesn't use lookup join.

The fix is to modify `BuildChildPhysicalPropsScalar` to require a 
distribution matching that of `mem.RootProps` when the parent op is 
`UniqueChecksItemOp` or `FKChecksItemOp`.

Also, sometimes hash join with full scan may be picked over lookup join
because the precision of the `float64` cost is not enough to distinguish
between unit or smaller differences when `LargeDistributeCost` (1e100)  
is added to the cost.

The fix is to set `LargeDistributeCost` to 1e14, the largest cost which
may be used and still allow the ability to distinguish between 2 costs  
which differ by .01.

Also, a fix is added to avoid statically erroring out locality-optimized
search of lookup joins, as their `enforce_home_region` erroring should be
handled dynamically during execution.

Fixes: #102049 

Release note (bug fix): This patches fixes the behavior of the 
enforce_home_region session setting, which previously may have allowed  
hash join to be favored over lookup join, or failed to error out remote
accesses done by uniqueness checks for mutations on REGIONAL BY ROW     
tables. Also, static erroring of some locality-optimized lookup joins is
fixed to now be handled dynamically during query execution.

2023-04-24 03:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/102103)
<!-- Reviewable:end -->

2023-04-24 15:13 UTC, rytaft requested changes
Thanks for the quick fix!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-:-NTnobhV6FSUOovt0YXk:b-e69qx5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/xform/coster.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnU0lApYkXbPWE_pO:-NTnnU0lApYkXbPWE_pP:b-f1d46a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/coster.go#L196)):*
> ```Go
> 	// a plan with the forced index, it may cause a plan with different index to
> 	// get selected, and error out.
> 	LargeDistributeCost = 1e14
> ```

This still makes me uncomfortable (same comment I've had in the past). Why can't we make this hugeCost and just modify the error message in execbuilder for cases where we're forcing the index? e.g., if an index is forced and enforce_home_region is used, we can say "cannot force the requested index and comply with enforce_home_region" or something like that.
___
*[`pkg/sql/opt/xform/physical_props.go` line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnkQKe5lmjvnOB4uwP:-NTnkQKe5lmjvnOB4uwQ:b2h9pdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/physical_props.go#L292)):*
> ```Go
> 			return physical.MinRequired
> 		}
> 		// If enforcing a home region, require the root distribution of the
> ```

why does it matter whether we're enforcing a home region? Wouldn't we always want the distribution of these postqueries to match the root? And is this the right place to put this? Seems like it should apply to every postquery, not just these two types. Is there a place we can iterate through all the postqueries and apply physical props?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlEsZ3qEmsBUPFhj1:-NTnlEsZ3qEmsBUPFhj2:b-vqgz40) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L30)):*
> ```
> statement ok
> CREATE TABLE employees (
> 	emp_no     INT8 NOT NULL,
> ```

nit: remove tabs
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlhqM4SytzP-bWU39:-NTnlhqM4SytzP-bWU3A:b-prrgqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3419e178bdba544f74d9c9e14a4682efd18028/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L242)):*
> ```
> SET enforce_home_region_follower_reads_enabled = true
> 
> # A lookup join with a CTE as input should succeed.
> ```

did you want to add another test where a lookup join with a CTE succeeds?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlSXA5VMvpfjOvoJ3:-NTnlSXA5VMvpfjOvoJ4:bb684ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L319)):*
> ```
> # An insert with uniqueness checks which access all regions should error out.
> retry
> statement error pq: Query has no home region\. Try adding a filter on employees\.crdb_region and/or on key column \(employees\.emp_no\)\. For more information, see https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html#control-whether-queries-are-limited-to-a-single-region
> ```

Not needed for this PR, but feels like this error message could be improved for this case.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlsH2E5ZZ9zLjOsms:-NTnlsH2E5ZZ9zLjOsmt:bblt174) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L366)):*
> ```
> # A UDF with no home region should fail.
> retry
> statement error pq: Query has no home region\. Try adding a LIMIT clause\. For more information, see https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html#control-whether-queries-are-limited-to-a-single-region
> ```

would a limit clause help in this case (ditto below)?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnm6Uh2eCRAwS3904L:-NTnm6Uh2eCRAwS3904M:b6za2kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L458)):*
> ```
> # Delete accessing all regions should fail.
> retry
> statement error pq: Query has no home region\. Try adding a filter on messages_rbr\.crdb_region and/or on key column \(messages_rbr\.message\)\. For more information, see https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html#control-whether-queries-are-limited-to-a-single-region
> ```

this error message doesn't make sense now. There *is* a filter on `messages_rbr.message`.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 1504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnC6Z8g47psQetnW9:-NTnnC6Z8g47psQetnWA:b8m4lzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L1504)):*
> ```
> retry
> statement error pq: Query has no home region\. Try adding a filter on xy\.region and/or on key column \(xy\.rowid\)\. For more information, see https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html#control-whether-queries-are-limited-to-a-single-region
> INSERT INTO xy (z, x, y) VALUES (1, 1, 1);
> ```

Do you have any tests for inserting into a table where no uniqueness checks are required?


<!-- Sent from Reviewable.io -->

2023-04-24 16:10 UTC, mgartner commented
Is #102049 considered a release-blocker? If not, let's remove the `backport-23.1.0` label here.

2023-04-24 19:39 UTC, msirek reviewed
OK, removed the `backport-23.1.0` label.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-:-NTo_ihWBEly7pTeXMqK:b718ikp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/coster.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnU0lApYkXbPWE_pO:-NToeGbKCJFRStNphRq2:bvk46u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/coster.go#L196)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This still makes me uncomfortable (same comment I've had in the past). Why can't we make this hugeCost and just modify the error message in execbuilder for cases where we're forcing the index? e.g., if an index is forced and enforce_home_region is used, we can say "cannot force the requested index and comply with enforce_home_region" or something like that.
</blockquote></details>

OK. I found the change to required the root expression's distribution for scalar expressions was enough to prefer the lookup join plan over the hash join plan, so I don't think using `1e14` is required here. I tried setting LargeDistributeCost to hugeCost, and I'm not seeing any errors in the regression tests. I also couldn't find a test case where hinting an index allowed a query plan using a different index to be picked (the original problem). So, I've changed LargeDistributeCost to hugeCost as part of this PR. If we find a test case in the future which exhibits the original problem we can put in that "cannot force the requested index and comply with enforce_home_region" error you suggested.
___
*[`pkg/sql/opt/xform/physical_props.go` line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnkQKe5lmjvnOB4uwP:-NTogCYu0osFTfqWUhdI:bn4jbmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/physical_props.go#L292)):*
> why does it matter whether we're enforcing a home region?

I was trying to limit the scope of this, since it's for backport, but you're right, any scalar built from a relational expression should require the local distribution.  I've gone ahead and made this change, and it's probably safe because the Distribute op doesn't really do anything currently. I believe this is the correct location for this change because it ensures all paths which need to get child physical props will use the proper distribution. The parent itself may not have a required distribution, as a scalar doesn't typically have a required distribution. 
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlEsZ3qEmsBUPFhj1:-NTohuKP-ZkEifFTEXj5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L30)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: remove tabs
</blockquote></details>

Done
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlhqM4SytzP-bWU39:-NTohvmNAA7lGz2atN8l:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3419e178bdba544f74d9c9e14a4682efd18028/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L242)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you want to add another test where a lookup join with a CTE succeeds?
</blockquote></details>

Done
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlSXA5VMvpfjOvoJ3:-NToj81NCEvscKoFnkR_:b-8t7mfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L319)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Not needed for this PR, but feels like this error message could be improved for this case.
</blockquote></details>

OK, I've opened #102175 to explore the possibilities.



_Code quote:_
```
EXPLAIN INSERT INTO employees
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnlsH2E5ZZ9zLjOsms:-NTojLAS-q9u_vHUqUi9:b5n3kwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L366)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would a limit clause help in this case (ditto below)?
</blockquote></details>

The limit would have to be inside the UDF.  The hint has actually changed with the latest code updates. The hint could maybe indicate the query adjustments need to be made inside the UDF definition. #102175 can handle this.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnm6Uh2eCRAwS3904L:-NTojlcS8-sJS3RCUMTr:b5t8agb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L458)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this error message doesn't make sense now. There *is* a filter on `messages_rbr.message`.
</blockquote></details>

With the latest code update, this recommends a filter on `account_id` now.



_Code quote:_
```
Delete accessing all regions should fail.
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 1504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnC6Z8g47psQetnW9:-NTojtkcD3D4K2cYsIub:btqnd3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L1504)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have any tests for inserting into a table where no uniqueness checks are required?
</blockquote></details>

I don't think there's such a thing. Even without a PK there are uniqueness checks.  We'd have to improve locality-optimized join to kick in in more cases.


<!-- Sent from Reviewable.io -->

2023-04-24 20:23 UTC, rytaft reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/xform/coster.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnU0lApYkXbPWE_pO:-NTothTV14VrR1cIAmPT:b-7bk192) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/coster.go#L196)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK. I found the change to required the root expression's distribution for scalar expressions was enough to prefer the lookup join plan over the hash join plan, so I don't think using `1e14` is required here. I tried setting LargeDistributeCost to hugeCost, and I'm not seeing any errors in the regression tests. I also couldn't find a test case where hinting an index allowed a query plan using a different index to be picked (the original problem). So, I've changed LargeDistributeCost to hugeCost as part of this PR. If we find a test case in the future which exhibits the original problem we can put in that "cannot force the requested index and comply with enforce_home_region" error you suggested.
</blockquote></details>

ok sounds good, thanks!
___
*[`pkg/sql/opt/xform/physical_props.go` line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTotv-FA5Q1nJgoi_X-:-NTotv-FA5Q1nJgoi_X0:bmxdxx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d48e2edc70b0b3b12280b6a9cfcdfd3937d783/pkg/sql/opt/xform/physical_props.go#L286)):*
> ```Go
> 				},
> 			}
> 			childProps.Distribution = mem.RootProps().Distribution
> ```

Did you mean to make this change here? If so, maybe this should happen outside of the switch? (or at least add a comment...)
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 1504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnC6Z8g47psQetnW9:-NTovEJN754xiXwUi-R-:b-ki55yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L1504)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I don't think there's such a thing. Even without a PK there are uniqueness checks.  We'd have to improve locality-optimized join to kick in in more cases.
</blockquote></details>

There is -- there are three cases where you don't need uniqueness checks (assuming there are no other unique indexes in the table):
1. The PK is of type UUID with default `gen_random_uuid()`
2. The PK is a composite key that includes `crdb_region` as the first column
3. `crdb_region` is a computed column based on the PK column
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTouinW1cJ3ERIDEBE2:-NTouinW1cJ3ERIDEBE3:b-und3hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d48e2edc70b0b3b12280b6a9cfcdfd3937d783/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L206)):*
> ```
> CREATE TABLE messages_rbr_alt (
>     account_id INT NOT NULL,
>     messageemail_id   UUID DEFAULT gen_random_uuid(),
> ```

did you mean to make this change?


<!-- Sent from Reviewable.io -->

2023-04-24 23:02 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/coster.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnU0lApYkXbPWE_pO:-NTpUWVN2IKKO7LKVgwU:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/sql/opt/xform/coster.go#L196)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ok sounds good, thanks!
</blockquote></details>

Sure
___
*[`pkg/sql/opt/xform/physical_props.go` line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTotv-FA5Q1nJgoi_X-:-NTpI63Q4Z9hQh9ti0kJ:bj2u4vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d48e2edc70b0b3b12280b6a9cfcdfd3937d783/pkg/sql/opt/xform/physical_props.go#L286)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you mean to make this change here? If so, maybe this should happen outside of the switch? (or at least add a comment...)
</blockquote></details>

Yes, the first child of `ArrayFlattenOp` is a relational expression, so this fits the pattern.  I was just trying to avoid having 2 `if` statements in the common case. Anyway, I have changed it as suggested to set this in one location.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 1504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTnnC6Z8g47psQetnW9:-NTpTseaB7nzLG7pMkJ2:b-eqmy99) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4d3d6f37ebcce61992da5e5e5ed47e2f0ecd66/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L1504)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

There is -- there are three cases where you don't need uniqueness checks (assuming there are no other unique indexes in the table):
1. The PK is of type UUID with default `gen_random_uuid()`
2. The PK is a composite key that includes `crdb_region` as the first column
3. `crdb_region` is a computed column based on the PK column
</blockquote></details>

Thank you! I've modified the schema of `xy` using case 1 to restore the original testing of dynamic erroring of the INSERT tests.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-NTouinW1cJ3ERIDEBE2:-NTpJOzOEOM2HK6pGho4:b-9oiqpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3d48e2edc70b0b3b12280b6a9cfcdfd3937d783/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L206)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you mean to make this change?
</blockquote></details>

Good catch. Must have been a spurious ctrl-V.
Fixed.


<!-- Sent from Reviewable.io -->

2023-04-24 23:13 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-:-NTpXnWa9G5sFkanr6T-:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2023-04-25 00:08 UTC, msirek reviewed
TFTR!
bors r=rytaft

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102103#-:-NTpjOTHCmlaP7aq7p5m:b1yj9cx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2023-04-25 00:37 UTC, merged

2023-04-25 21:16 UTC, rytaft commented
blathers backport 23.1.0