sqlstats: fix flaky test TestSQLStatsLatencyInfo
cockroachdb/cockroach pull request #102198
Opened 2023-04-24 22:50 UTC by maryliag

Sometimes the statements were taking a longer time than expected to complete, making the check for the latency max to fail.
This commits adds a bigger margin for the statement execution time, to avoid flakes.
It also improves error messages to make it easier to identify which ones has failed.

Fixes #101926

Release note: None

2023-04-24 22:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/102198)
<!-- Reviewable:end -->

2023-04-26 17:34 UTC, gtr requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTybmuvEG0NQ9S-5lLq:-NTybmuvEG0NQ9S-5lLr:b-dmbet4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51ff4d70037c433ef661d8e05924776873f3c71/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
> ```Go
> 			require.Positive(t, max, "expected max latency greater than 0")
> 			require.GreaterOrEqual(t, max, min, "expected max latency greater than min latency")
> 			require.LessOrEqual(t, max, tc.latencyMax, "expected max latency greater than test latency %f", tc.latencyMax)
> ```

Should this error message be `"expected max latency less than or equal to test latency %f"` ?


<!-- Sent from Reviewable.io -->

2023-04-26 18:21 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)

___
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTybmuvEG0NQ9S-5lLq:-NTyn9ky-UrpjVb0Udun:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e51ff4d70037c433ef661d8e05924776873f3c71/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

Should this error message be `"expected max latency less than or equal to test latency %f"` ?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-04-26 18:48 UTC, maryliag reviewed
The issue is not the latency of the test itself (which would be solved by the suceedsSoon). Here I'm testing if it calculates the max and percentile of statements correctly, so I assumed the time the statement would take, but it was taking a little more, so is just increasing the acceptable margin here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-:-NTysveB6-GgFUqPsu44:bjqggsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr)



<!-- Sent from Reviewable.io -->

2023-04-26 18:53 UTC, j82w commented
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTyu7jPCWEhkYTyFKRE:-NTyu7jPCWEhkYTyFKRF:b-7wgb7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9dfcd4b342c3312408d4b7b747d92002754986c/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
> ```Go
> 			require.Positive(t, max, "expected max latency greater than 0")
> 			require.GreaterOrEqual(t, max, min, "expected max latency greater than min latency")
> 			require.LessOrEqual(t, max, tc.latencyMax, "expected max latency less or equal test latency %f", tc.latencyMax)
> ```

How about measuring the time it took to execute the statement and using that as a max instead of depending on a hard coded value?


<!-- Sent from Reviewable.io -->

2023-04-26 18:55 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @j82w)

___
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTyu7jPCWEhkYTyFKRE:-NTyusi99BbF5ffEI7xq:b-j0l9np) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9dfcd4b342c3312408d4b7b747d92002754986c/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

How about measuring the time it took to execute the statement and using that as a max instead of depending on a hard coded value?
</blockquote></details>

the time it took is the max value already


<!-- Sent from Reviewable.io -->

2023-04-26 18:58 UTC, j82w commented
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTyu7jPCWEhkYTyFKRE:-NTyvHnB9N2R3z-zHSB-:b-n92ph5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9dfcd4b342c3312408d4b7b747d92002754986c/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the time it took is the max value already
</blockquote></details>

I mean something like this:

stopWatch       timeutil.CPUStopWatch
stopWatch.Start()
testConn.Exec(t, tc.statement)
elapsed = stopWatch.Elapsed()
....
require.LessOrEqual(t, max, elapsed, "expected max latency less or equal test latency %f", elapsed)


<!-- Sent from Reviewable.io -->

2023-04-26 20:13 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @gtr and @j82w)

___
*[`pkg/sql/sqlstats/sslocal/sql_stats_test.go` line 1519 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-NTyu7jPCWEhkYTyFKRE:-NTzBjMA9Y5PIGyR1G7x:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9dfcd4b342c3312408d4b7b747d92002754986c/pkg/sql/sqlstats/sslocal/sql_stats_test.go#L1519)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

I mean something like this:

stopWatch       timeutil.CPUStopWatch
stopWatch.Start()
testConn.Exec(t, tc.statement)
elapsed = stopWatch.Elapsed()
....
require.LessOrEqual(t, max, elapsed, "expected max latency less or equal test latency %f", elapsed)

</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-04-26 20:16 UTC, j82w approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-:-NTzCUyZ9PLC9YcOtl3I:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gtr)



<!-- Sent from Reviewable.io -->

2023-04-26 21:49 UTC, maryliag commented
bors r+

2023-04-26 22:02 UTC, gtr reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-:-NTz_eHZDZOEuqArp0ne:b-uwkowd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2023-04-26 22:05 UTC, gtr approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102198#-:-NTzaVcFDcM240ZxZnB9:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @j82w)



<!-- Sent from Reviewable.io -->

2023-04-26 22:06 UTC, maryliag commented
bors r+

2023-04-27 17:14 UTC, merged