changefeedccl: fix webhook sink retries
cockroachdb/cockroach pull request #102639
Opened 2023-04-28 20:55 UTC by jayshrivastava

Release note (bug fix): The `Retry.Max` field of the `webhook_sink_config` option for changefeeds was not correctly defined in the docs. The existing docs mention that it is "The maximum amount of time the sink will retry a single HTTP request to send a batch", but this is incorrect. It actually represents the number of retries that will be attempted.

Also, before this change, there was a bug where the maximum time we would wait before retrying was 4 seconds. With this change, there is no maximum - we will keep doubling the initial backoff until we hit `Retry.Max` attempts.

Fixes: https://github.com/cockroachdb/cockroach/issues/102467
Epic: None

2023-04-28 20:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/102639)
<!-- Reviewable:end -->

2023-05-08 14:09 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102639#-NUvgAm91jDcjREKgyHb):*
Is that so?  Because after giving up, changefeed still retires, does it not?
So, in a sense, it is max number of attempts for a single batch...?
___
*[`pkg/ccl/changefeedccl/sink_webhook.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102639#-NUvgSsZ5pT6a6ONRsZu:-NUvgSsZ5pT6a6ONRsZv:b-muw5ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/8597079fe734ce33471387cf7ef5f198f7627a54/pkg/ccl/changefeedccl/sink_webhook.go#L223)):*
> ```Go
> 	retryCfg.MaxRetries = int(cfg.Retry.Max)
> 	retryCfg.InitialBackoff = time.Duration(cfg.Retry.Backoff)
> 	retryCfg.MaxBackoff = retryCfg.InitialBackoff * time.Duration(int(math.Pow(2.0, float64(retryCfg.MaxRetries))))
> ```

I think we should stop doing these fancy things.  Really though, would 10 seconds or 30 seconds not be good enough for max backoff? Why would we want to it grow to hours?


<!-- Sent from Reviewable.io -->

2023-05-08 14:31 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102639)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102639#-NUvgAm91jDcjREKgyHb):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is that so?  Because after giving up, changefeed still retires, does it not?
So, in a sense, it is max number of attempts for a single batch...?
</blockquote></details>

I updated the message to be more clear :) 
___
*[`pkg/ccl/changefeedccl/sink_webhook.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102639#-NUvgSsZ5pT6a6ONRsZu:-NUvkjwG6mvjkv8XBcMX:b-187roe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8597079fe734ce33471387cf7ef5f198f7627a54/pkg/ccl/changefeedccl/sink_webhook.go#L223)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should stop doing these fancy things.  Really though, would 10 seconds or 30 seconds not be good enough for max backoff? Why would we want to it grow to hours?
</blockquote></details>

Of course. I should have thought about that. Let's do 30 seconds. Google recommends 32 or 64. https://cloud.google.com/iot/docs/how-tos/exponential-backoff


<!-- Sent from Reviewable.io -->

2023-05-09 00:15 UTC, miretskiy approved these changes

2023-05-09 15:42 UTC, merged