[DNM] sql: multi-row VALUES insert fast-path UNIQUE WITHOUT INDEX support
cockroachdb/cockroach pull request #102995
Opened 2023-05-10 05:59 UTC by msirek

This adds support for building and executing simple INSERT statements with a multi-row VALUES clause into a table with UNIQUE WITHOUT INDEX constraints (including those implicitly built on REGIONAL BY ROW unique indexes).

Epic: CRDB-26290
Informs: #58047

Release note (performance improvement): This patch adds support for fast-path multi-row VALUES insert into REGIONAL BY ROW tables with unique indexes.

2023-05-10 05:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/102995)
<!-- Reviewable:end -->

2023-06-14 22:05 UTC, yuzefovich reviewed
> Reviewed 11 of 14 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/insert_fast_path.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvsyuc4nMgfuoBlsxn:-NXvsyuc4nMgfuoBlsxo:bup1u0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7830a32c59d68fcafdb8d73a919668e4fab4004/pkg/sql/insert_fast_path.go#L191)):*
> ```Go
> 		// Combine them together to get the final index prefix key to search.
> 		for _, templateRow := range c.DatumsFromConstraint {
> 			// Each row must have its own memory as it is part of a batch.
> ```

I'm confused by this - I'd assume that the BatchRequest would only contain the span generated based on the combined row which should internally copy datums into `roachpb.Key`s, no?
___
*[`pkg/sql/insert_fast_path.go` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvw9xVExhBR2vLNr77:-NXvw9xVExhBR2vLNr78:b-jlqexk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4748ce3e165bf3336ba02f9b05840b808ca05778/pkg/sql/insert_fast_path.go#L487)):*
> ```Go
> 
> 		// Perform the FK checks.
> 		// TODO(radu): we could run the FK batch in parallel with the main batch (if
> ```

nit: do you plan on addressing this TODO as well? It seems like it'd be nice to do it since you're in this area.
___
*[`pkg/sql/opt/exec/factory.opt` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvu62q0YdXZ2u0YuaU:-NXvu62q0YdXZ2u0YuaV:b-itzjhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7830a32c59d68fcafdb8d73a919668e4fab4004/pkg/sql/opt/exec/factory.opt#L468)):*
> ```
> #  - all FK checks can be performed using direct lookups into unique indexes.
> #  - all UNIQUE WITHOUT INDEX checks can be performed using direct lookups
> #  - into an index (could be a key prefix and not the entire key).
> ```

nit: probably we don't want `-` before "into an index"?


<!-- Sent from Reviewable.io -->

2023-06-15 00:40 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvsyuc4nMgfuoBlsxn:-NXwRwMF9ET23pk0XG6b:b-i09nux) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7830a32c59d68fcafdb8d73a919668e4fab4004/pkg/sql/insert_fast_path.go#L191)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm confused by this - I'd assume that the BatchRequest would only contain the span generated based on the combined row which should internally copy datums into `roachpb.Key`s, no?
</blockquote></details>

Good catch.  I updated the logic to allocate the combined row once, and updated the comment.
___
*[`pkg/sql/insert_fast_path.go` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvw9xVExhBR2vLNr77:-NXwHNMW2PRL4xmrkhE-:b2g1v8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4748ce3e165bf3336ba02f9b05840b808ca05778/pkg/sql/insert_fast_path.go#L487)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do you plan on addressing this TODO as well? It seems like it'd be nice to do it since you're in this area.
</blockquote></details>

There was more work I wanted to do in uniqueness checks in general, to support more cases (more forms of INSERT statements). But I cut it short in favor of switching to partial stats work.  If we were to defer the partial stats work a bit longer, I'd rather give priority to those missing cases above this TODO.  Also, only the FK checks could be done in parallel with the insert, because uniqueness checks could be trying to read from the same index as being inserted, and we don't want to "see" the newly-inserted row.  So, in that case we'd have to run the uniqueness check before the insert(s) anyway. So, this would be an enhancement for cases which only have FK checks and no uniqueness checks, which this PR is not covering.
___
*[`pkg/sql/opt/exec/factory.opt` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvu62q0YdXZ2u0YuaU:-NXwUDg29RLtg190GjEb:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7830a32c59d68fcafdb8d73a919668e4fab4004/pkg/sql/opt/exec/factory.opt#L468)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: probably we don't want `-` before "into an index"?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-06-15 17:49 UTC, msirek commented
@michae2 Would READ COMMITTED changes overlap or conflict with this PR?

2023-06-15 20:34 UTC, yuzefovich reviewed
Nice work! The execution bits look good to me, I'll defer to others on the optimizer changes.

> Reviewed 2 of 7 files at r4, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NY-l-G0CFFFDXZCPqjS:bj0529k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/insert_fast_path.go` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvw9xVExhBR2vLNr77:-NY-hReo-cUV0WacZ7Fz:b-uk6ot8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4748ce3e165bf3336ba02f9b05840b808ca05778/pkg/sql/insert_fast_path.go#L487)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

There was more work I wanted to do in uniqueness checks in general, to support more cases (more forms of INSERT statements). But I cut it short in favor of switching to partial stats work.  If we were to defer the partial stats work a bit longer, I'd rather give priority to those missing cases above this TODO.  Also, only the FK checks could be done in parallel with the insert, because uniqueness checks could be trying to read from the same index as being inserted, and we don't want to "see" the newly-inserted row.  So, in that case we'd have to run the uniqueness check before the insert(s) anyway. So, this would be an enhancement for cases which only have FK checks and no uniqueness checks, which this PR is not covering.
</blockquote></details>

Ack, thanks for the context.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 3651 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY-kVXZ5s4I1svaETW9:-NY-kVXZ5s4I1svaETWA:belqmvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f1da74626d2b508bd6006f6e4fa3de581b20544/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L3651)):*
> ```
> statement ok
> SET tracing = on,kv,results; INSERT INTO user_settings2 (id2, user_id, value)
> VALUES (9, '5ebfedee-0dcf-41e6-a315-5fa0b51b9992', 'foo'),
> ```

It might be good to have a test where the INSERT that requires both an FK check and a uniqueness check fails only FK check, only Uniq check, and both (to make sure that the error message is as expected).


<!-- Sent from Reviewable.io -->

2023-06-16 17:51 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 487 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NXvw9xVExhBR2vLNr77:-NY4JNHx0eFSsvUgLH_c:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4748ce3e165bf3336ba02f9b05840b808ca05778/pkg/sql/insert_fast_path.go#L487)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Ack, thanks for the context.
</blockquote></details>

Sure
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 3651 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY-kVXZ5s4I1svaETW9:-NY4Jopq2EhpoBOlmzvu:b3qfwrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f1da74626d2b508bd6006f6e4fa3de581b20544/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L3651)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It might be good to have a test where the INSERT that requires both an FK check and a uniqueness check fails only FK check, only Uniq check, and both (to make sure that the error message is as expected).
</blockquote></details>

Sure. I already had tests for the first 2 cases: https://github.com/msirek/cockroach/blob/cd8c30b3e62768a0e49423ef4ef6fd78e4ce3127/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L3582-L3589

I've gone ahead and added a test where there's both a uniqueness violation and an FK violation (the uniqueness violation is reported, the same as in non-fast path insert).


<!-- Sent from Reviewable.io -->

2023-06-21 16:54 UTC, mgartner reviewed
I've left some comments for the first commit. In the future, you could put a commit like the first in its own PR - it's a self-contained and large change that would be good to review on its own.

> Reviewed 9 of 14 files at r1, 1 of 7 files at r4, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NYTrqUh8AxuxHWBFvcI:b-e8nvwa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTZUbgBWkCUDRKBusF:-NYTZUbh2ziukaBymwLu:bzcmpav) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L140)):*
> ```Go
> func (b *Builder) findKeyColOrd(
> 	keyCol opt.ColumnID, lookupJoin *memo.LookupJoinExpr, indexOrd cat.IndexOrdinal,
> ) (inputColOrd int, indexColOrd int, ok bool) {
> ```

nit: `inputColOrd` => `tableColOrd`
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 222 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTbCPA0OwOzcsuOgbd:-NYTbCPA0OwOzcsuOgbe:b-cugu3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L222)):*
> ```Go
> 		var skipProjectExpr *memo.ProjectExpr
> 		for skipProjectExpr, ok = check.(*memo.ProjectExpr); ok; skipProjectExpr, ok = check.(*memo.ProjectExpr) {
> 			check = skipProjectExpr.Input
> ```

This pattern matching is good motivation for using optgen pattern matching for these fast-path patterns: https://github.com/cockroachdb/cockroach/pull/104760. Should we wait for that PR to merge and use the features it provides?

Also, do you have tests that exercise all these different patterns - I don't see them.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NYTgPhR2Jv2iUjOEVxy:bskcudx) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
> ```Go
> 		inputExpr := lookupJoin.Input
> 		// Ignore any select (used to deal with NULLs).
> 		if sel, isSelect := inputExpr.(*memo.SelectExpr); isSelect {
> ```

Ignoring all SELECTs seems dangerous. I don't think we can be 100% sure that something like a partial index predicate is not pushed from a join filter into a Select. Is there a way we can guarantee that the Select we are ignoring is only used to filter out NULLs?

nit: Can you update the comment to point out that NULLs are handled during execution of the fast past in `insertFastPathRun.AddUniqChecks`?
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-NYTipG3785XtDjeMFN3:bn4w0qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
> ```Go
> 		}
> 		// A WithScan typically wraps multiple rows from a VALUES clause being
> 		// inserted, so peek into it.
> ```

If a single row of constants is being inserted, the VALUES clause will be inlined into the uniqueness check and there will be no WithScan. That's probably a case we should cover as well (we can in a future PR).
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 244 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTj6xI2_pzCE-6bvWc:-NYTj6xI2_pzCE-6bvWd:b7mmgh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L244)):*
> ```Go
> 		}
> 		// Verify this is the WithScan corresponding to this insert.
> 		if withScan.With != ins.WithID {
> ```

nit: you could combine this with the `if` conditional above.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTjMbpEABSIPdakjXO:-NYTjMbpEABSIPdakjXP:b-3al7hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L278)):*
> ```Go
> 				return mkFastPathUniqueCheckErr(md, c, values, out.ReferencedIndex)
> 			}
> 		} else {
> ```

Is the lookup expression case going to be common? We don't currently handle this for FK checks.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 1045 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTnK4RBESvtTn7tSlm:-NYTnK4RBESvtTn7tSln:bhnoszr) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L1045)):*
> ```Go
> 		if !found {
> 			panic(errors.AssertionFailedf(
> 				"Insert fast path failed uniqueness check, but could not find unique columns for row, %v", keyVals))
> ```

nit: `Insert` => `insert`
___
*[`pkg/sql/opt/norm/project_funcs.go` line 75 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTkfr08rDJIrQugLcU:-NYTkfr08rDJIrQugLcV:be22z4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/norm/project_funcs.go#L75)):*
> ```Go
> // may be incorrect when projection expressions reference columns. It is up to
> // the caller to validate the cases which are allowed to merge a projection with
> // values.
> ```

Is "no outer columns in projection expressions" the only requirement for merging a multi-row Values? If so, we should add that check in this function to prevent misuse.
___
*[`pkg/sql/row/fk_spans.go` line 22 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTLnvkCNAeVP0-6rfw:-NYTLnvl01bj4koiMxXR:b-wc5n0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/row/fk_spans.go#L22)):*
> ```Go
> // FKUniqCheckSpan returns a span that can be scanned to ascertain existence of
> // a specific row in a given index.
> func FKUniqCheckSpan(
> ```

nit: Should we name this `ExistenceCheckSpan` since it's used more generally now?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4210 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTqQ0gE-m0QSKQM6bj:-NYTqQ0gE-m0QSKQM6bk:b-6x3r46) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/testdata/unique#L4210)):*
> ```
> # Insert of multi-row VALUES into table with UNIQUE WITHOUT INDEX and a
> # usable index on a prefix of those columns should use insert fast-path.
> query T
> ```

Can you add a test with multiple uniquess checks? It'd be great to have a bigger variety of tests here and matching logic tests that cover most of the new code paths.


<!-- Sent from Reviewable.io -->

2023-06-23 06:58 UTC, msirek reviewed
Sure

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NYb-yaK0Mr38OqHUJKR:bb74ce2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTZUbgBWkCUDRKBusF:-NYYvAsQ9epf0w9Pqgs2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L140)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `inputColOrd` => `tableColOrd`
</blockquote></details>

Done
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 222 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTbCPA0OwOzcsuOgbd:-NYYxjEI-fF4kqkQAxGf:bd66v7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L222)):*
> This pattern matching is good motivation for using optgen pattern matching for these fast-path patterns: [#104760](https://github.com/cockroachdb/cockroach/pull/104760). Should we wait for that PR to merge and use the features it provides?

Isn't that PR related to avoiding optimization for placeholder fast path queries? Insert fast path processing happens in the execbuilder, which can't really use optgen as the expected output is an `exec.Node`.  I'm not really sure what's being suggested here. 

The code above isn't really pattern matching per se (for example we don't want to inspect every Distribute operation), but is instead just skipping over operations which may be present to get to the main operation which checks for the existence of rows, like a Scan or a LookupJoin.

Most skipping operations were added because of one or more test cases which needed it.
For example, this test in regional_by_row_hash_sharded_index_query_plan skips the projection:
```
CREATE TABLE t_unique_hash_pk (
  id INT PRIMARY KEY USING HASH
) LOCALITY REGIONAL BY ROW;

EXPLAIN (VERBOSE) INSERT INTO t_unique_hash_pk(id) VALUES (4321);
```

This test in regional_by_row_query_behavior exercises the skipping of the Distribute operation:
```
INSERT INTO regional_by_row_table (pk, pk2, a, b) VALUES
(10, 10, 11, 12)
RETURNING crdb_region, pk
```
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NYZf4Tc1HF0H3ntY_EP:b-2knv41) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
> Is there a way we can guarantee that the Select we are ignoring is only used to filter out NULLs?

The comment about nulls was copied from foreign key checking code:
https://github.com/cockroachdb/cockroach/blob/aaeec2a1489a753caabfd05597d131ff99336006/pkg/sql/opt/exec/execbuilder/mutation.go#L612

I couldn't find a test case dealing with NULLs, but found a Select is created to ignore the row(s) which were just inserted. The `ignorableNECheck` closure deals with these cases, I've moved this into a standalone function and added a call to it on the Select condition as well (the pre-existing usage was on the lookup join condition).

I've also written similar function `ignorablePKNEConstCheck` for the single-row insert case.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-NYauit24jgmM-MZ_02h:b-u7rnhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If a single row of constants is being inserted, the VALUES clause will be inlined into the uniqueness check and there will be no WithScan. That's probably a case we should cover as well (we can in a future PR).
</blockquote></details>

Yeah, `ignorablePKNEConstCheck` handles it, though it's not as rigorous as the multirow case where we match on withScan column IDs.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 244 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTj6xI2_pzCE-6bvWc:-NYavc9PBINm-QMlIMTb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L244)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you could combine this with the `if` conditional above.
</blockquote></details>

Done
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTjMbpEABSIPdakjXO:-NYavvGK0mwMjLV1dQvv:b-dwsfgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L278)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is the lookup expression case going to be common? We don't currently handle this for FK checks.
</blockquote></details>

Maybe. If I had more time I'd improve the FK cases we handle now, but need to defer it. Another option is to try to look for an expression in the memo group which can currently be handled instead of always analyzing the best-cost expression.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 1045 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTnK4RBESvtTn7tSlm:-NYawdu-7uHAHBjHUThL:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L1045)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `Insert` => `insert`
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/project_funcs.go` line 75 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTkfr08rDJIrQugLcU:-NYazuMyAKRRTGzphkVM:bk3ilyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/norm/project_funcs.go#L75)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is "no outer columns in projection expressions" the only requirement for merging a multi-row Values? If so, we should add that check in this function to prevent misuse.
</blockquote></details>

I believe so. OK, I've added an assertion in this function.
___
*[`pkg/sql/row/fk_spans.go` line 22 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTLnvkCNAeVP0-6rfw:-NYb-1f22diuO_b4rLFG:bn8u19r) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/row/fk_spans.go#L22)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should we name this `ExistenceCheckSpan` since it's used more generally now?
</blockquote></details>

Hmm, not sure. It's already been renamed to reflect the 2 cases it's handling, which might help someone debugging get a hint of the processing being done. Maybe if it starts getting used in more places we could think of a better name.


<!-- Sent from Reviewable.io -->

2023-06-26 04:02 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4210 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTqQ0gE-m0QSKQM6bj:-NYpr6gp7mS36c9hZcI7:b-s8kbvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/testdata/unique#L4210)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add a test with multiple uniquess checks? It'd be great to have a bigger variety of tests here and matching logic tests that cover most of the new code paths.
</blockquote></details>

Added more tests. A lot of the new logic is triggered by REGIONAL BY ROW test cases, so is covered more in `regional_by_row_query_behavior`.


<!-- Sent from Reviewable.io -->

2023-06-26 20:59 UTC, mgartner reviewed
> Reviewed 1 of 7 files at r10, 2 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 222 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTbCPA0OwOzcsuOgbd:-NYsvUH11QlJejApuVTP:bjnvm90) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L222)):*
> Isn't that PR related to avoiding optimization for placeholder fast path queries?

Oh of course. Ignore that comment completely.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NYtV3ku5LaaZdZ_OJbC:b-hpq0r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> Is there a way we can guarantee that the Select we are ignoring is only used to filter out NULLs?

The comment about nulls was copied from foreign key checking code:
https://github.com/cockroachdb/cockroach/blob/aaeec2a1489a753caabfd05597d131ff99336006/pkg/sql/opt/exec/execbuilder/mutation.go#L612

I couldn't find a test case dealing with NULLs, but found a Select is created to ignore the row(s) which were just inserted. The `ignorableNECheck` closure deals with these cases, I've moved this into a standalone function and added a call to it on the Select condition as well (the pre-existing usage was on the lookup join condition).

I've also written similar function `ignorablePKNEConstCheck` for the single-row insert case.
</blockquote></details>

Good catch. Did you add a test case that would have caught this bug?
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTjMbpEABSIPdakjXO:-NYsQWOH78HwOagFv9Ct:b6quqny) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L278)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Maybe. If I had more time I'd improve the FK cases we handle now, but need to defer it. Another option is to try to look for an expression in the memo group which can currently be handled instead of always analyzing the best-cost expression.
</blockquote></details>

I was suggesting to remove support for lookup expressions, if it's not a critical case, not support it for FKs too.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtP3HTCoK7tAOJPU1M:-NYtP3HTCoK7tAOJPU1N:b-76mqgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2948)):*
> ```
> vectorized: true
> ·
> • insert fast path
> ```

Why did this test change in the first commit? I thought it covers multi-row inserts.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 3477 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtPTyv6k-cmT0KeQOK:-NYtPTyv6k-cmT0KeQOL:b-383k1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L3477)):*
> ```
> query T
> EXPLAIN INSERT INTO users2 (crdb_region, name, email)
> VALUES ('ap-southeast-2', 'Craig Roacher', 'craig@cockroachlabs.com')
> ```

ditto: why is this case handled by the first commit?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-NYtQlon4GocTjCm4fbn:b-68qrmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
> ```
>   UNIQUE WITHOUT INDEX (b, c),
>   UNIQUE WITHOUT INDEX (a, b, d),
>   UNIQUE WITHOUT INDEX (a),
> ```

These unique constraints should omit a prefix of index columns, like they do in a RBR table. A `UNIQUE INDEX` would make more sense if you're holding all columns in the index unique. 

When I try to do that, I can't get the fast-path to work. Here's what I tried:

```
statement ok
SET experimental_enable_unique_without_index_constraints = true

statement ok
CREATE TABLE t (
  r STRING NOT NULL,
  a INT NOT NULL,
  b INT,
  CHECK (r IN ('east', 'west', 'central')),
  PRIMARY KEY (r, a),
  UNIQUE WITHOUT INDEX (a)
)

query T
EXPLAIN
INSERT INTO t VALUES ('east', 10, 20), ('west', 30, 40)
----
distribution: local
vectorized: true
·
• root
│
├── • insert
│   │ into: t(r, a, b)
│   │
│   └── • buffer
│       │ label: buffer 1
│       │
│       └── • render
│           │
│           └── • values
│                 size: 3 columns, 2 rows
│
└── • constraint-check
    │
    └── • error if rows
        │
        └── • lookup join (semi)
            │ table: t@t_pkey
            │ lookup condition: (r IN ('central', 'east', 'west')) AND (column2 = a)
            │ pred: column1 != r
            │
            └── • scan buffer
                  estimated row count: 2
                  label: buffer 1
```

This is possibly related: I can't get the fast-path to work in a RBR table either. It seems like the `DEFAULT gen_random_uuid()` is required, but I don't see why.

```
statement ok
CREATE TABLE users2 (
  id UUID PRIMARY KEY,
  name STRING NOT NULL,
  email STRING NOT NULL UNIQUE,
  INDEX (name)
) LOCALITY REGIONAL BY ROW

query T
EXPLAIN INSERT INTO users2 (id, crdb_region, name, email) VALUES
  ('e1806944-1d6d-45c0-b8a3-637062b6b71b', 'ap-southeast-2', 'Craig Roacher', 'craig@cockroachlabs.com'),
  ('00000000-0000-0000-0000-000000000000', 'ap-southeast-2', 'other', 'other@cockroachlabs.com')
----
distribution: local
vectorized: true
·
• root
│
├── • insert
│   │ into: users2(id, name, email, crdb_region)
│   │
│   └── • buffer
│       │ label: buffer 1
│       │
│       └── • render
│           │
│           └── • values
│                 size: 4 columns, 2 rows
│
├── • constraint-check
│   │
│   └── • error if rows
│       │
│       └── • lookup join (semi)
│           │ table: users2@users2_pkey
│           │ lookup condition: (crdb_region IN ('ap-southeast-2', 'ca-central-1', 'us-east-1')) AND (column1 = id)
│           │ pred: column2 != crdb_region
│           │
│           └── • scan buffer
│                 estimated row count: 2
│                 label: buffer 1
│
└── • constraint-check
    │
    └── • error if rows
        │
        └── • lookup join (semi)
            │ table: users2@users2_email_key
            │ lookup condition: (crdb_region IN ('ap-southeast-2', 'ca-central-1', 'us-east-1')) AND (column4 = email)
            │ pred: (column1 != id) OR (column2 != crdb_region)
            │
            └── • scan buffer
                  estimated row count: 2
                  label: buffer 1
```


<!-- Sent from Reviewable.io -->

2023-06-26 22:10 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 222 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTbCPA0OwOzcsuOgbd:-NYtYO-WA1yPAerRHfLS:bb74ce2) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L222)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> Isn't that PR related to avoiding optimization for placeholder fast path queries?

Oh of course. Ignore that comment completely.


</blockquote></details>

Sure
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NYtcV5eA_DJzPHHF2QS:bcjz9gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good catch. Did you add a test case that would have caught this bug?
</blockquote></details>

I've been unable to find a bug this would have caught, but this test case fails the `ignorablePKNEConstCheck` check and so exits early from checking for fast path processing eligibility:
https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/logictest/testdata/logic_test/unique#L141-L143
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTjMbpEABSIPdakjXO:-NYte2_V1bIICDpgs9_p:bb9wsfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L278)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was suggesting to remove support for lookup expressions, if it's not a critical case, not support it for FKs too.
</blockquote></details>

This is pretty essential given the types of query plans generated for REGIONAL BY ROW tables. For example, this simple case no longer uses insert fast path without lookup expression support:
https://github.com/cockroachdb/cockroach/blob/f7d50903c566c852405f10ab461720a6fa1a0286/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2809-L2820
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtP3HTCoK7tAOJPU1M:-NYtfZuaAcj1LvcnwswM:b-samoz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2948)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why did this test change in the first commit? I thought it covers multi-row inserts.
</blockquote></details>

A function call to `gen_random_uuid` is in the insert expression, so we choose not to inline it here:
https://github.com/cockroachdb/cockroach/blob/5dadd707f489ad2d5a97a52655141a028d82e2a1/pkg/sql/opt/optbuilder/mutation_builder.go#L1464-L1478
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 3477 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtPTyv6k-cmT0KeQOK:-NYtfz78Ed_6xxE-0eId:b4f4er9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L3477)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

ditto: why is this case handled by the first commit?
</blockquote></details>

Same reason, the call to `gen_random_uuid`.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-NYti4A64F6G7k4HQmqN:b23ytzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

These unique constraints should omit a prefix of index columns, like they do in a RBR table. A `UNIQUE INDEX` would make more sense if you're holding all columns in the index unique. 

When I try to do that, I can't get the fast-path to work. Here's what I tried:

```
statement ok
SET experimental_enable_unique_without_index_constraints = true

statement ok
CREATE TABLE t (
  r STRING NOT NULL,
  a INT NOT NULL,
  b INT,
  CHECK (r IN ('east', 'west', 'central')),
  PRIMARY KEY (r, a),
  UNIQUE WITHOUT INDEX (a)
)

query T
EXPLAIN
INSERT INTO t VALUES ('east', 10, 20), ('west', 30, 40)
----
distribution: local
vectorized: true
·
• root
│
├── • insert
│   │ into: t(r, a, b)
│   │
│   └── • buffer
│       │ label: buffer 1
│       │
│       └── • render
│           │
│           └── • values
│                 size: 3 columns, 2 rows
│
└── • constraint-check
    │
    └── • error if rows
        │
        └── • lookup join (semi)
            │ table: t@t_pkey
            │ lookup condition: (r IN ('central', 'east', 'west')) AND (column2 = a)
            │ pred: column1 != r
            │
            └── • scan buffer
                  estimated row count: 2
                  label: buffer 1
```

This is possibly related: I can't get the fast-path to work in a RBR table either. It seems like the `DEFAULT gen_random_uuid()` is required, but I don't see why.

```
statement ok
CREATE TABLE users2 (
  id UUID PRIMARY KEY,
  name STRING NOT NULL,
  email STRING NOT NULL UNIQUE,
  INDEX (name)
) LOCALITY REGIONAL BY ROW

query T
EXPLAIN INSERT INTO users2 (id, crdb_region, name, email) VALUES
  ('e1806944-1d6d-45c0-b8a3-637062b6b71b', 'ap-southeast-2', 'Craig Roacher', 'craig@cockroachlabs.com'),
  ('00000000-0000-0000-0000-000000000000', 'ap-southeast-2', 'other', 'other@cockroachlabs.com')
----
distribution: local
vectorized: true
·
• root
│
├── • insert
│   │ into: users2(id, name, email, crdb_region)
│   │
│   └── • buffer
│       │ label: buffer 1
│       │
│       └── • render
│           │
│           └── • values
│                 size: 4 columns, 2 rows
│
├── • constraint-check
│   │
│   └── • error if rows
│       │
│       └── • lookup join (semi)
│           │ table: users2@users2_pkey
│           │ lookup condition: (crdb_region IN ('ap-southeast-2', 'ca-central-1', 'us-east-1')) AND (column1 = id)
│           │ pred: column2 != crdb_region
│           │
│           └── • scan buffer
│                 estimated row count: 2
│                 label: buffer 1
│
└── • constraint-check
    │
    └── • error if rows
        │
        └── • lookup join (semi)
            │ table: users2@users2_email_key
            │ lookup condition: (crdb_region IN ('ap-southeast-2', 'ca-central-1', 'us-east-1')) AND (column4 = email)
            │ pred: (column1 != id) OR (column2 != crdb_region)
            │
            └── • scan buffer
                  estimated row count: 2
                  label: buffer 1
```
</blockquote></details>

This RBR table case isn't currently handled because `InsertExpr.Input` contains a projection expression 
`crdb_region IN ('ap-southeast-2', 'ca-central-1', 'us-east-1')`, which fails this check:
https://github.com/cockroachdb/cockroach/blob/7f9c6e2196896be35f82b3f189fd9419234531b9/pkg/sql/opt/exec/execbuilder/mutation.go#L459-L461

This is the illegal case where `MergeProjectWithValues` can't be called because there are expressions involving columns and more than one input row being merged. If the insert statement doesn't include the `crdb_region` column, fast path is chosen:
```sql
EXPLAIN INSERT INTO users2 (id, name, email)  [...]

2023-07-03 16:21 UTC, rytaft reviewed
I didn't have time to finish reviewing this before I left for vacation, so I'll push the few comments I had. Don't wait for me to review it if it's ready to go before I come back, but I can take another look if it's still in progress.

> Reviewed 7 of 14 files at r1, 1 of 7 files at r4, 5 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NZRYM6-Bo_1D01XOVWF:brqjvb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_a4Lc6JC2QcrTlgt9:-NY_a4Lc6JC2QcrTlgtA:b-t6i9cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/insert_fast_path.go#L175)):*
> ```Go
> 		for _, ord := range c.InsertCols {
> 			if inputRow[ord] == tree.DNull {
> 				numNulls++
> ```

nit: since you only need to know if there are any nulls, you could change this to a boolean `hasNulls` and just break here.
___
*[`pkg/sql/opt/exec/factory.go` line 270 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_caCz5ZvTNnaFGCAr:-NY_caCz5ZvTNnaFGCAs:bb1ixed) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/factory.go#L270)):*
> ```Go
> 	// constraint which are part of the index key to look up. The number of
> 	// entries corresponds with the number of KV lookups. For example, for a
> 	// locality-optimized operation accessing 1 local region and 2 remote regions,
> ```

Why is it a locality optimized operation? There's no possibility for a short-circuit here, right? Maybe "multi-region" operation would be more accurate?
___
*[`pkg/sql/opt/exec/factory.opt` line 467 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_YzTo7p8GNy9W2QEV:-NY_YzTp-5bhgI7NGvSN:b-p6v309) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/factory.opt#L467)):*
> ```
> #  - there are no self-referencing foreign keys;
> #  - all FK checks can be performed using direct lookups into unique indexes.
> #  - all UNIQUE WITHOUT INDEX checks can be performed using direct lookups
> ```

UNIQUE WITHOUT INDEX -> uniqueness
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 180 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_eIEQ-AeJwXpo2Aqx:-NY_eIEQ-AeJwXpo2Aqy:b7o8sst) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L180)):*
> ```Go
> 			return execPlan{}, false, nil
> 		}
> 		if !projectExpr.Passthrough.Equals(projectExpr.Input.Relational().OutputCols) {
> ```

nit: `projectExpr.Input` can be `insInput`
___
*[`pkg/sql/opt/norm/factory.go` line 181 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_ZrgJ2F4EZp759zvP:-NY_ZrgJ2F4EZp759zvQ:bdk7ku9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/norm/factory.go#L181)):*
> ```Go
> 	f.mem = nil
> 	// Make sure the factory has a non-nil memo structure.
> 	f.Init(f.ctx, f.evalCtx, nil /* catalog */)
> ```

Why is this needed?


<!-- Sent from Reviewable.io -->

2023-07-05 23:05 UTC, michae2 reviewed
Still reading, just pushing a few comments. This is looking good!

> [@michae2](https://github.com/michae2) Would READ COMMITTED changes overlap or conflict with this PR?

The overlaps are small, I will rebase on top of this PR after it goes in.

> Reviewed 2 of 14 files at r1, 1 of 7 files at r4, 1 of 7 files at r10, 1 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NZcGh6T5_LyeRW8AkTV:b-odkaj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 81 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcE9Y4-lmC2wBt6DGG:-NZcE9Y4-lmC2wBt6DGH:b-wweknw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L81)):*
> ```Go
> 	// uniqSpanMap is used to de-duplicate uniqueness checks. Only used if there
> 	// is more than one input row.
> 	uniqSpanMap map[string]struct{}
> ```

nit: I don't think it makes sense to maintain this O(rows)-memory-consuming hash table when we expect it to never catch duplicates in the happy case. (And in the case where it does catch a duplicate, we'll have to roll back the transaction anyway, so the case it is making faster doesn't seem worth optimizing.) (I think it makes more sense for FK checks, when we expect duplicates of the same referenced row in the happy case, and that is worth optimizing.)
___
*[`pkg/sql/insert_fast_path.go` line 203 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcCl2X8G0EW7D_nJUZ:-NZcCl2X8G0EW7D_nJU_:b-mw7wa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L203)):*
> ```Go
> 				// Datums from single-table constraints are already present in
> 				// DatumsFromConstraint. Fill in other values from the input row.
> 				if combinedRow[c.InsertCols[j]] == nil {
> ```

nit: Wouldn't it be simpler to know the starting index of the input columns ahead of time?
___
*[`pkg/sql/insert_fast_path.go` line 261 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcHq9w-bfpav2BWpe0:-NZcHq9x97q5XY3X_zMV:bd0n5fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L261)):*
> ```Go
> 		}
> 
> 		span, err := c.generateSpan(inputRow)
> ```

Should FK checks also be using `DatumsFromConstraint`? (In other words, do we support FK references to RBR indexes where the region is not included in the FK?)


<!-- Sent from Reviewable.io -->

2023-07-06 06:34 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/insert_fast_path.go` line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_a4Lc6JC2QcrTlgt9:-NZdhret6J1py26zfEvp:bol96zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/insert_fast_path.go#L175)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: since you only need to know if there are any nulls, you could change this to a boolean `hasNulls` and just break here.
</blockquote></details>

Modified as suggested
___
*[`pkg/sql/insert_fast_path.go` line 81 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcE9Y4-lmC2wBt6DGG:-NZdgU0f7PlXaqo8sVGm:b-l9ovyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L81)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I don't think it makes sense to maintain this O(rows)-memory-consuming hash table when we expect it to never catch duplicates in the happy case. (And in the case where it does catch a duplicate, we'll have to roll back the transaction anyway, so the case it is making faster doesn't seem worth optimizing.) (I think it makes more sense for FK checks, when we expect duplicates of the same referenced row in the happy case, and that is worth optimizing.)
</blockquote></details>

Good point. Most likely an app won't be making the mistake of inserting duplicates in the same batch. Removed `uniqSpanMap`.
___
*[`pkg/sql/insert_fast_path.go` line 203 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcCl2X8G0EW7D_nJUZ:-NZdiKBo-RWMs-sNFioG:bc37hfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L203)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Wouldn't it be simpler to know the starting index of the input columns ahead of time?
</blockquote></details>

We can't just iterate through the Datums in  `DatumsFromConstraint[0]` to find the first nil entry and remember it.  It would be unsafe to make the assumption that all rows in the `DatumsFromConstraint` slice have the same populated entries in the same positions.  
___
*[`pkg/sql/insert_fast_path.go` line 261 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NZcHq9w-bfpav2BWpe0:-NZdlSKxB7zvwVd2jZKM:b-d1p6u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/insert_fast_path.go#L261)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should FK checks also be using `DatumsFromConstraint`? (In other words, do we support FK references to RBR indexes where the region is not included in the FK?)
</blockquote></details>

I think there are a number of improvements we could probably make to the FK check code to allow fast path in more cases, including possibly using `DatumsFromConstraint`. But that is work for a separate PR. I'm trying to keep this PR more self-contained.
___
*[`pkg/sql/opt/exec/factory.go` line 270 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_caCz5ZvTNnaFGCAr:-NZdmaSx05uyROpO5UmC:bzentl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/factory.go#L270)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why is it a locality optimized operation? There's no possibility for a short-circuit here, right? Maybe "multi-region" operation would be more accurate?
</blockquote></details>

This was worded confusingly. I meant that the `DatumsFromConstraint` built from analyzing a locality-optimized operation would contain 3 entries. Updated it to:
```
// DatumsFromConstraint contains constant values from the WHERE clause
// constraint which are part of the index key to look up. The number of  
// entries corresponds with the number of KV lookups. For example, when built  
// from analyzing a locality-optimized operation accessing 1 local region and  
// 2 remote regions, the resulting DatumsFromConstraint would have 3 entries.
```
___
*[`pkg/sql/opt/exec/factory.opt` line 467 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_YzTo7p8GNy9W2QEV:-NZdn7cw0UQjegdj9Lr_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/factory.opt#L467)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

UNIQUE WITHOUT INDEX -> uniqueness
</blockquote></details>

Done
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 180 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_eIEQ-AeJwXpo2Aqx:-NZdnT8M5EKB4A0gvvqu:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L180)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: `projectExpr.Input` can be `insInput`
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/factory.go` line 181 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NY_ZrgJ2F4EZp759zvP:-NZdnsKz4LpkU10UxEcO:b-5mk6de) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/norm/factory.go#L181)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Because calling `MergeProjectWithValues` from the execbuilder causes a panic since norm.Factory.mem gets set to nil. We wouldn't want to merge the projection with VALUES during optimization because that's a waste of memory, unless we already knew the statement qualified for insert fast path. But since all of the fast path checking happens in the execbuilder instead of the optimizer, we won't know until we get to the execbuilder phase whether or not `MergeProjectWithValues` should be called. This may be a good argument for moving the uniqueness and FK check fast path qualification code into the optimizer at some point.
```go
[06:06:33] --- done: ../../../../ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior with config multiregion-9node-3region-3azs: 6 tests, 0 failures
    logic.go:4046: 
        ../../../../ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior:224: error while processing
    logic.go:4046: 
        ../../../../ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior:224: 
        expected success, but found
        (XX000) internal error: runtime error: invalid memory address or nil pointer dereference
        catch.go:29: in ShouldCatch()
        DETAIL: stack trace:
        github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
        github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:286: func1()
        runtime/panic.go:890: gopanic()
        runtime/panic.go:260: panicmem()
        runtime/signal_unix.go:835: sigpanic()
        github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:447: NextRank()
        github.com/cockroachdb/cockroach/pkg/sql/opt/memo/expr.og.go:21356: MemoizeTuple()
        github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.og.go:12872: ConstructTuple()
        github.com/cockroachdb/cockroach/pkg/sql/opt/norm/project_funcs.go:119: MergeProjectWithValues()
        github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/mutation.go:735: tryBuildFastPathInsert()
        github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/mutation.go:85: buildInsert()
        github. [...]

2023-07-06 14:06 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NZfE09mARz0K_3ZYbdL:bcfuuce) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I've been unable to find a bug this would have caught, but this test case fails the `ignorablePKNEConstCheck` check and so exits early from checking for fast path processing eligibility:
https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/logictest/testdata/logic_test/unique#L141-L143
</blockquote></details>

A test with a partial unique without index constraint should have ran into this bug. For example, the select filter applied to the WithScan below cannot be ignored:

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  r STRING NOT NULL,
  a INT,
  b INT,
  UNIQUE (r, a) WHERE b > 0,
  UNIQUE WITHOUT INDEX (a) WHERE b > 0,
  CHECK (r IN ('east', 'west'))
)
----

opt
INSERT INTO t VALUES (1, 'east', 10, 100), (2, 'west', 20, 200)
----
insert t
 ├── columns: <none>
 ├── insert-mapping:
 │    ├── column1:7 => t.k:1
 │    ├── column2:8 => t.r:2
 │    ├── column3:9 => t.a:3
 │    └── column4:10 => t.b:4
 ├── check columns: check1:11
 ├── partial index put columns: partial_index_put1:12
 ├── input binding: &1
 ├── cardinality: [0 - 0]
 ├── volatile, mutations
 ├── project
 │    ├── columns: partial_index_put1:12!null check1:11!null column1:7!null column2:8!null column3:9!null column4:10!null
 │    ├── cardinality: [2 - 2]
 │    ├── fd: (10)-->(12), (8)-->(11)
 │    ├── values
 │    │    ├── columns: column1:7!null column2:8!null column3:9!null column4:10!null
 │    │    ├── cardinality: [2 - 2]
 │    │    ├── (1, 'east', 10, 100)
 │    │    └── (2, 'west', 20, 200)
 │    └── projections
 │         ├── column4:10 > 0 [as=partial_index_put1:12, outer=(10)]
 │         └── column2:8 IN ('east', 'west') [as=check1:11, outer=(8)]
 └── unique-checks
      └── unique-checks-item: t(a)
           └── project
                ├── columns: a:21!null
                ├── cardinality: [0 - 2]
                └── semi-join (lookup t@t_r_a_key,partial)
                     ├── columns: k:19!null a:21!null b:22!null
                     ├── lookup expression
                     │    └── filters
                     │         ├── t.r:14 IN ('east', 'west') [outer=(14), constraints=(/14: [/'east' - /'east'] [/'west' - /'west']; tight)]
                     │         └── a:21 = t.a:15 [outer=(15,21), constraints=(/15: (/NULL - ]; /21: (/NULL - ]), fd=(15)==(21), (21)==(15)]
                     ├── cardinality: [0 - 2]
                     ├── select
                     │    ├── columns: k:19!null a:21!null b:22!null
                     │    ├── cardinality: [0 - 2]
                     │    ├── with-scan &1
                     │    │    ├── columns: k:19!null a:21!null b:22!null
                     │    │    ├── mapping:
                     │    │    │    ├──  column1:7 => k:19
                     │    │    │    ├──  column3:9 => a:21
                     │    │    │    └──  column4:10 => b:22
                     │    │    └── cardinality: [2 - 2]
                     │    └── filters
                     │         └── b:22 > 0 [outer=(22), constraints=(/22: [/1 - ]; tight)]
                     └── filters
                          └── k:19 != t.k:13 [outer=(13,19), constraints=(/13: (/NULL - ]; /19: (/NULL - ])]
```
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-NZfFwwh8EfArAZgBwsR:b-4ribtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Yeah, `ignorablePKNEConstCheck` handles it, though it's not as rigorous as the multirow case where we match on withScan column IDs.
</blockquote></details>

Is `ignorablePKNEConstCheck` a valid check in the general case? What if the unique without index constraint is partial and has a filter matching the same form. For example:

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  r STRING NOT NULL,
  a INT,
  b INT,
  UNIQUE (r, a) WHERE k != 1,
  UNIQUE WITHOUT INDEX (a) WHERE k != 1,
  CHECK (r IN ('east', 'west'))
)
----

opt
INSERT INTO t VALUES (2, 'east', 10, 100)
----
insert t
 ├── columns: <none>
 ├── insert-mapping:
 │    ├── column1:7 => t.k:1
 │    ├── column2:8 => t.r:2
 │    ├── column3:9 => t.a:3
 │    └── column4:10 => t.b:4
 ├── check columns: check1:11
 ├── partial index put columns: partial_index_put1:12
 ├── cardinality: [0 - 0]
 ├── volatile, mutations
 ├── values
 │    ├── columns: column1:7!null column2:8!null column3:9!null column4:10!null check1:11!null partial_index_put1:12!null
 │    ├── cardinality: [1 - 1]
 │    ├── key: ()
 │    ├── fd: ()-->(7-12)
 │    └── (2, 'east', 10, 100, true, true)
 └── unique-checks
      └── unique-checks-item: t(a)
           └── project
                ├── columns: a:21!null
                ├── cardinality: [0 - 1]
                ├── key: ()
                ├── fd: ()-->(21)
                └── project
                     ├── columns: a:21!null
                     ├── cardinality: [0 - 1]
                     ├── key: ()
                     ├── fd: ()-->(21)
                     └── inner-join (cross)
                          ├── columns: t.k:13!null t.a:15!null a:21!null
                          ├── cardinality: [0 - 1]
                          ├── multiplicity: left-rows(zero-or-one), right-rows(exactly-one)
                          ├── key: ()
                          ├── fd: ()-->(13,15,21)
                          ├── values
                          │    ├── columns: a:21!null
                          │    ├── cardinality: [1 - 1]
                          │    ├── key: ()
                          │    ├── fd: ()-->(21)
                          │    └── (10,)
                          ├── limit
                          │    ├── columns: t.k:13!null t.a:15!null
                          │    ├── cardinality: [0 - 1]
                          │    ├── key: ()
                          │    ├── fd: ()-->(13,15)
                          │    ├── select
                          │    │    ├── columns: t.k:13!null t.a:15!null
                          │    │    ├── key: (13)
                          │    │    ├── fd: ()-->(15)
                          │    │    ├── limit hint: 1.00
                          │    │    ├── scan t@t_r_a_key,partial
                          │    │    │    ├── columns: t.k:13!null t.a:15!null
                          │    │    │    ├── constraint: /14/15
                          │    │    │    │    ├── [/'east'/10 - /'east'/10]
                          │    │    │    │    └── [/'west'/10 - /'west'/10]
                          │    │    │    ├── key: (13)
                          │    │    │    ├── fd: ()-->(15)
                          │    │    │    └── limit hint: 0.13
                          │    │    └── filters
                          │    │         └── t.k:13 != 2 [outer=(13), constraints=(/13: (/NULL - /1] [/3 - ]; tight)]
                          │    └── 1
                          └── filters (true)
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtP3HTCoK7tAOJPU1M:-NZfGtAX-MRb_QKwqXw6:b141588) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70b [...]

2023-07-10 18:15 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-N_-J5AO3SP6476puKl9:b6yhlh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is `ignorablePKNEConstCheck` a valid check in the general case? What if the unique without index constraint is partial and has a filter matching the same form. For example:

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  r STRING NOT NULL,
  a INT,
  b INT,
  UNIQUE (r, a) WHERE k != 1,
  UNIQUE WITHOUT INDEX (a) WHERE k != 1,
  CHECK (r IN ('east', 'west'))
)
----

opt
INSERT INTO t VALUES (2, 'east', 10, 100)
----
insert t
 ├── columns: <none>
 ├── insert-mapping:
 │    ├── column1:7 => t.k:1
 │    ├── column2:8 => t.r:2
 │    ├── column3:9 => t.a:3
 │    └── column4:10 => t.b:4
 ├── check columns: check1:11
 ├── partial index put columns: partial_index_put1:12
 ├── cardinality: [0 - 0]
 ├── volatile, mutations
 ├── values
 │    ├── columns: column1:7!null column2:8!null column3:9!null column4:10!null check1:11!null partial_index_put1:12!null
 │    ├── cardinality: [1 - 1]
 │    ├── key: ()
 │    ├── fd: ()-->(7-12)
 │    └── (2, 'east', 10, 100, true, true)
 └── unique-checks
      └── unique-checks-item: t(a)
           └── project
                ├── columns: a:21!null
                ├── cardinality: [0 - 1]
                ├── key: ()
                ├── fd: ()-->(21)
                └── project
                     ├── columns: a:21!null
                     ├── cardinality: [0 - 1]
                     ├── key: ()
                     ├── fd: ()-->(21)
                     └── inner-join (cross)
                          ├── columns: t.k:13!null t.a:15!null a:21!null
                          ├── cardinality: [0 - 1]
                          ├── multiplicity: left-rows(zero-or-one), right-rows(exactly-one)
                          ├── key: ()
                          ├── fd: ()-->(13,15,21)
                          ├── values
                          │    ├── columns: a:21!null
                          │    ├── cardinality: [1 - 1]
                          │    ├── key: ()
                          │    ├── fd: ()-->(21)
                          │    └── (10,)
                          ├── limit
                          │    ├── columns: t.k:13!null t.a:15!null
                          │    ├── cardinality: [0 - 1]
                          │    ├── key: ()
                          │    ├── fd: ()-->(13,15)
                          │    ├── select
                          │    │    ├── columns: t.k:13!null t.a:15!null
                          │    │    ├── key: (13)
                          │    │    ├── fd: ()-->(15)
                          │    │    ├── limit hint: 1.00
                          │    │    ├── scan t@t_r_a_key,partial
                          │    │    │    ├── columns: t.k:13!null t.a:15!null
                          │    │    │    ├── constraint: /14/15
                          │    │    │    │    ├── [/'east'/10 - /'east'/10]
                          │    │    │    │    └── [/'west'/10 - /'west'/10]
                          │    │    │    ├── key: (13)
                          │    │    │    ├── fd: ()-->(15)
                          │    │    │    └── limit hint: 0.13
                          │    │    └── filters
                          │    │         └── t.k:13 != 2 [outer=(13), constraints=(/13: (/NULL - /1] [/3 - ]; tight)]
                          │    └── 1
                          └── filters (true)
```
</blockquote></details>

The `t.k:13 != 2` predicate is an ignorable filter, and this case is legal for insert fast path. If we used a INSERT value of k=1, the partial index would not have been used. So far, my initial worry about filters being applied which can't be ignored has been a purely theoretical concern. I have not found a test case that could cause problems. In any case, I have tightened up the `ignorablePKNEConstCheck` to match predicate constants with constants from the INSERT row, and don't do fast path if they don't match. 

Note that fast path uniqueness checks will be unnecessarily disallowed in most partial index cases due to `ignorablePKNEConstCheck`, but maybe it's better to exercise an abundance of caution in the first pass of this feature. We may find out later that `ignorablePKNEConstCheck` is unecessary and could be removed.

```
statement ok  
CREATE TABLE t (  
  k INT PRIMARY KEY,  
  r STRING NOT NULL,  
  a INT,  
  b INT,  
  UNIQUE (r, a),  
  UNIQUE WITHOUT INDEX (a) WHERE k != 1,  
  CHECK (r IN ('east', 'west'))  
)  
  
\# This case could theoretically use insert fast path , but we currently don't  
\# out of an abundance of caution because there's a SelectExpr with a filter  
\# which isn't the internally-generated primary key inequality check.  
query T  
EXPLAIN  
INSERT INTO t VALUES (3, 'east', 10, 100)  
\----  
distribution: local  
vectorized: true  
·  
• root  
│  
├── • insert  
│   │ into: t(k, r, a, b)  
│   │  
│   └── • values  
│         size: 5 columns, 1 row  
│  
└── • constraint-check  
    │  
    └── • error if rows  
        │  
        └── • cross join  
            │  
            ├── • values  
            │     size: 1 column, 1 row  
            │  
            └── • limit  
                │ count: 1  
                │  
                └── • filter  
                    │ filter: (k != 1) AND (k != 3)  
                    │  
                    └── • scan  
                          missing stats  
                          table: t@t\_r\_a\_key  
                          spans: \[/'east'/10 - /'east'/10\] \[/'west'/10 - /'west'/10\]
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior` line 2948 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtP3HTCoK7tAOJPU1M:-N_-u4iu5NqBqK6XTx97:b-4gd4mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior#L2948)):*
added:
> The VALUES clause may contain any constant expression  
that could be evaluated and folded to a constant, including function  
calls such as `gen_random_uuid`.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-N_-uhP81M_kXWh8LpOn:bozi1kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
> If there's not a specific edge case we're trying to solve for a customer, we should focus on the simplest cases first, like a single-row insert into a RBR table...

That's the target, single-row and multi-row insert into an RBR table.  This is handled by the first two commits. Multi-row insert should be a very common use case because it optimizes insert performance by batching the inserts into a group of rows instead of having to process a new statement for every row inserted. And single-row insert is still a common case, for example if an app only has a single row it needs to insert. The latency cost of the uniqueness checks also takes up a larger percentage of the overall time in the single-row case, so it is very beneficial to handle this case.

This PR is solving the case where the INSERT does not specify the `crdb_region` column value(s), and the value of the gateway region is used in the INSERT. The case where INSERT does specify the `crdb_region` column value(s) is non-trivial, so deferred to a later  [...]

2023-07-10 23:35 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`-- commits` line 9 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-N_1-cMYAEHZyF6YzPoc):*
`gen_random_uuid()` isn't folded to a constant. `gateway_region()` can be, but if used in a multi-value insert, then the fast path does not work. So `gen_random_uuid()` is special then?
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-N_0qWy38_-toKLtEv3V:bji301i) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
> The `t.k:13 != 2` predicate is an ignorable filter, and this case is legal for insert fast path.

Can you explain why that filter is ignorable? If it is not applied to the input rows then what prevents a uniqueness check being performed on a row that doesn't satisfy the predicate?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-N_107em3Zk6xrqXvThN:bfssfgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
> This PR is solving the case where the INSERT does not specify the `crdb_region` column value(s), and the value of the gateway region is used in the INSERT.

The commit message and release note needs to be clear about what cases are supported. It currently reads as if there are no restrictions, which will confuse SEs and users.

I'd prefer to take more time and solve fewer cases in order to find a pattern that is simpler and will work for the majority of cases in the long-term. AFAICT there's no customers waiting on a particular case, so I don't think we're in any time crunch (@rytaft correct me if I'm wrong about that).

I think it'd be interesting to experiment with adding optimizer fast path expressions (e.g., `InsertFastPathExpr`) and constructing them directly within optbuilder. Much of the complexity and many of the limitations with the current approach come from using an expression tree as a way to communicate the terms of FK and uniqueness checks from the optbuilder to the execbuilder. Would it be difficult to look for a lookup index for each check in the optbuilder and only fallback to using the expression-based checks if we couldn't find one or the mutation input was not suitable for fast-pathing? Or are there cases that require this to be an exploration-time decision — is there some type of mutation input where a fast-path would not be preferred (e.g., a values clause with many rows that would cause many lookups; we already the fast path to 10k rows in the values clause, so maybe that's already covered)? 


<!-- Sent from Reviewable.io -->

2023-07-11 00:56 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`-- commits` line 9 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-N_1-cMYAEHZyF6YzPoc):*
OK, that was wrongly worded. Updated it to:
> The VALUES clause may contain any expression         
that could be evaluated without referencing columns, such as a call to
function `gen_random_uuid`.

`gen_random_uuid()` should work in a multi-value insert too.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-N_1JsSC66vaO0D0JO_N:b-l0xctz) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> The `t.k:13 != 2` predicate is an ignorable filter, and this case is legal for insert fast path.

Can you explain why that filter is ignorable? If it is not applied to the input rows then what prevents a uniqueness check being performed on a row that doesn't satisfy the predicate?
</blockquote></details>

It's because this internally-generated predicate is meant to filter out the row which was just added.  Non-fastpath checks occur after the row is inserted, so for the statement `INSERT INTO t VALUES (2, 'east', 10, 100)`, `k != 2` filters out the row which was just inserted so it won't fail the column `a` duplicate check on itself.

In the fast path case, the uniqueness check is done before the insert, and we want to see all rows which are in the index.  Also, since the row with `k=2` has not been inserted yet, this predicate will always evaluate to `true`.  If there happens to be a pre-existing row with `k=2`, then the new row would fail the primary key duplicate check.


<!-- Sent from Reviewable.io -->

2023-07-12 15:57 UTC, mgartner commented
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-N_9nu26-7RyNxJVY02b:b8uafwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It's because this internally-generated predicate is meant to filter out the row which was just added.  Non-fastpath checks occur after the row is inserted, so for the statement `INSERT INTO t VALUES (2, 'east', 10, 100)`, `k != 2` filters out the row which was just inserted so it won't fail the column `a` duplicate check on itself.

In the fast path case, the uniqueness check is done before the insert, and we want to see all rows which are in the index.  Also, since the row with `k=2` has not been inserted yet, this predicate will always evaluate to `true`.  If there happens to be a pre-existing row with `k=2`, then the new row would fail the primary key duplicate check.
</blockquote></details>

Yes, that filter is meant to filter out the insert row, but there is also a filter to filter out rows that should not be included in the unique partial index. Dropping them would be incorrect.


<!-- Sent from Reviewable.io -->

2023-07-15 02:45 UTC, rytaft reviewed
> Reviewed 1 of 14 files at r1, 2 of 11 files at r11, 2 of 8 files at r14, 4 of 7 files at r20, 2 of 6 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @msirek, and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/scope.go` line 219 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-N_MQYOw2683zfzeeS95:-N_MQYOx8IEI5y6LT16I:b-6zi763) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa3faf7cb8d8dc5317928dd90f437e3e709e2726/pkg/sql/opt/optbuilder/scope.go#L219)):*
> ```Go
> }
> 
> // appendOrdinaryColumnshandleSingleRowInsertFromTable adds all non-mutation and non-system columns from the
> ```

nit: comment doesn't match function name now
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-N_ML4X10K25DG0XiewR:b-ya995n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
> AFAICT there's no customers waiting on a particular case, so I don't think we're in any time crunch ([@rytaft](https://github.com/rytaft) correct me if I'm wrong about that).

As I discussed with @mgartner offline, we do have a customer waiting for this feature. See https://github.com/cockroachlabs/support/issues/1978 for details. This case needs to be solved for 23.2, and is more important than partial stats.

> Maybe [@rytaft](https://github.com/rytaft) knows if there are specific cases we want to cover.

The most important case is RBR tables. `UNIQUE WITHOUT INDEX` is an experimental feature, and I don't think it's used by any customers. So I wouldn't add any special logic to support `UNIQUE WITHOUT INDEX` unless it's also useful for RBR. There's no harm in testing different `UNIQUE WITHOUT INDEX` cases if they happen to be supported, but it's probably more useful to focus on `UNIQUE WITHOUT INDEX` cases that mimic RBR tables (similar to @mgartner's example above).

Also, there are at least a couple of different RBR cases we'd like to support. In the issue linked above, we need to support RBR tables where the `crdb_region` column is computed.

Happy to discuss more offline if it's still not clear what are the important cases to support.


<!-- Sent from Reviewable.io -->

2023-07-21 14:31 UTC, msirek commented
Looking into #104760 to see if the new FastPath optgen rule support could help simplify things...

2023-07-21 19:09 UTC, mgartner commented
I was confused when I suggested #104760 - and I think we agreed that is unrelated to this. It's wildly confusing because there are two (at least) "fast paths": insert fast path and placeholder fast path. #104760 is related to placeholder fast paths.

2023-07-21 19:45 UTC, msirek reviewed
I was initially confused as well, but it looks like that PR also includes the framework for writing totally unrelated fast path rules, so I think I can use that portion to write my own insert fast path rule

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-N_tymAr19w0JE0i7aNA:b3m22k9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-07-21 22:03 UTC, DrewKimball commented
To be clear, #104760 allows you to write rules that skip optimization and go straight from a normalized plan to a fully optimized one. This is useful for placeholders because it allows use to avoid fully re-optimizing on every execution. This is orthogonal to the insert fast-path, which is an optimized _execution_ operator. It seems from like this PR is concerned with the latter case, so maybe #104760 isn't relevant?

We need to clarify the terminology around fast-paths for sure.

2023-07-31 05:12 UTC, msirek commented
Pushed a reworking of the code to run CI tests.
Will be adding some more comments to commit messages later.

2023-07-31 05:17 UTC, msirek commented
> To be clear, #104760 allows you to write rules that skip optimization and go straight from a normalized plan to a fully optimized one. This is useful for placeholders because it allows use to avoid fully re-optimizing on every execution. This is orthogonal to the insert fast-path, which is an optimized _execution_ operator. It seems from like this PR is concerned with the latter case, so maybe #104760 isn't relevant?

Thanks. If there were enough information in the memo after optbuild from which to build fast path uniqueness checks, then I could have used #104760 to write a fast path rule. But there isn't, so yeah, it isn't directly relevant. I ended up creating an exploration rule instead.

2023-08-01 05:09 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-NahqNGI0sdOoVesqgt5:b-w2g4hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes, that filter is meant to filter out the insert row, but there is also a filter to filter out rows that should not be included in the unique partial index. Dropping them would be incorrect.
</blockquote></details>

The above test case adds the `b > 0` check as a column in the projection, so we fail this check:
https://github.com/msirek/cockroach/blob/5a8f1f0e39d292a5b41249271baa2bb0a460ca07/pkg/sql/opt/xform/insert_funcs.go#L91-L97

... and never enter the fast path flow.

The following test case produces a filter which almost matches what `ignorablePKNEConstCheck` checks for:

```sql
statement ok
CREATE TABLE regional_by_row_table (
  pk int,
  pk2 int NOT NULL,
  a int NOT NULL,
  b int NOT NULL,
  j JSON,
  INDEX (a),
  UNIQUE (b),
  INVERTED INDEX (j),
  PRIMARY KEY(pk, pk2)
) LOCALITY REGIONAL BY ROW

statement ok
CREATE UNIQUE INDEX uniq_idx ON regional_by_row_table(a) WHERE pk2 != 3

# We should plan uniqueness checks for all unique indexes in
# REGIONAL BY ROW tables.
query T
SELECT * FROM [EXPLAIN INSERT INTO regional_by_row_table (pk, pk2, a, b) VALUES (1, 2, 3, 4)] OFFSET 2
----
```
This is not using fast path though because there is more than 1 filter (there is also the normal NE primary key check filter), and the function returns false unless there is exactly one filter. That primary key check filter should always be generated.

For multi-row insert with a partial index predicate like `WHERE pk2 != b`, that fails the projection check mentioned above.

So, so far I am not seeing a way for fast path to get chosen when there is a partial index predicate being used as a Select filter.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-NaiTCrKEZZyjL09Fgeo:bz1kzsh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
@rytaft Thanks, yes, I think we should discuss the cases which need support.  The following from the support issue seems unclear:
> for cross regional unique constraints check only scan active regions such as east1 and east2 ignoring west2 which is considered a witness region for a RBR table

Fast path uniqueness checks would have to access all regions, but I'm not sure what a witness region is or if this is something we've committed to supporting.

The inserts in the support issue (statement bundles) were single-row inserts. Should we limit the cases handled to single-row inserts as @mgartner was suggesting?  Note that the single-row insert hash-sharded cases the customer needs end up taking the "multi-row" code path, where a lookup join is used to read the index instead of a constrained scan.  Multi-row inserts to hash-sharded RBR tables aren't currently supported.
___
*[`pkg/sql/opt/optbuilder/scope.go` line 219 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-N_MQYOw2683zfzeeS95:-NaiBu10Ewp7FauFay4t:bnj1s4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa3faf7cb8d8dc5317928dd90f437e3e709e2726/pkg/sql/opt/optbuilder/scope.go#L219)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: comment doesn't match function name now
</blockquote></details>

Fixed, thanks


<!-- Sent from Reviewable.io -->

2023-08-02 14:58 UTC, mgartner reviewed
> I ended up creating an exploration rule instead.

What is the advantage to performing this logic at exploration-time instead of execbuilder-time? It seems like we'd need to move the uniqueness checks inlining to an exploration rule as well in order to get the benefit of making this insert fast path logic simpler for the single-value case. We'd also need to be able to decide if the insert fast path is valid entirely at exploration-time, rather than some of the decision being decided at execbuilder-time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NaqfPRkB5OlLi4elaL2:b-n8zabn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/insert_fastpath.go` line 43 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NaqieM01mxKbbdIdQUR:-Naqgr6c9Ps8cHFv7yJZ:b2ydhz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/insert_fastpath.go#L43)):*
> ```Go
> 	// columns. For each, the value in the array indicates the index of the column
> 	// in the input table.
> 	InsertCols []TableColumnOrdinal
> ```

We can use optimizer constructs here rather than mimicking execbuilder ones. You can define this information in optgen by adding `IndexOrdinal`, `ColList`, `ScalarListExpr` for the datums and we should be able to construct the error message at execbuilder time like we do here: https://github.com/cockroachdb/cockroach/blob/bb857aae80e1f20f67b457e7a8e790f208aa8cb5/pkg/sql/opt/exec/execbuilder/mutation.go#L781
___
*[`pkg/sql/opt/xform/insert_funcs.go` line 424 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-Naqcf7QEGQmn5n2SfOq:-Naqcf7R1NYFBZK4XkXh:b-4yzdbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/xform/insert_funcs.go#L424)):*
> ```Go
> 		// Verify the right column is a primary key column (index ordinal 0).
> 		rightVariable := t.Right.(*memo.VariableExpr)
> 		_, _, ok = c.findKeyColOrd(rightVariable.Col, tableID, 0 /* primary index */)
> ```

nit: You can  replace `0 /* primary index */` with `cat.PrimaryIndex`.


<!-- Sent from Reviewable.io -->

2023-08-02 15:09 UTC, msirek reviewed
I have more changes coming which pushes some of the logic into the optbuild phase, so hold off on reviewing further for now.
For things like placeholders, we still need some deferred logic to grab the actual Datums to use, etc...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NaqmU7R82nLpd_ZE925:bfzjolj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-Nan5huF44bRqKCRgJAe:b-uuox5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
> I think it'd be interesting to experiment with adding optimizer fast path expressions (e.g., InsertFastPathExpr) and constructing them directly within optbuilder. Much of the complexity and many of the limitations with the current approach come from using an expression tree as a way to communicate the terms of FK and uniqueness checks from the optbuilder to the execbuilder. Would it be difficult to look for a lookup index for each check in the optbuilder and only fallback to using the expression-based checks if we couldn't find one or the mutation input was not suitable for fast-pathing? Or are there cases that require this to be an exploration-time decision...

I've looked into this. Here are some reasons which make that tricky or would force us to re-invent the wheel:
- It wouldn't handle placeholders without special logic.
    * The `TupleExpr` in the Values expression holds `PlaceHolderExpr`s at optbuild time.  So, `InsertFastPathFKUniqCheck.DatumsFromConstraint` couldn't be populated directly. We'd have to save the placeholders we're interested in and then fill in placeholder Datums later when they become available. If `InsertFastPathFKUniqCheck` is a part of unique check properties in `UniqueChecksItemPrivate`, as it currently now is, we'd have to add a new version of it to the memo at exploration time anyway, with the Datums filled in.
- We'd have to combine all filters and check constraints from the table to find the `crdb_region`s we need to visit. All of this logic is already built in when generating constrained scans or lookup joins with indexes.  Logic such as, detecting when an index is visible or invisible, detecting when it's legal to use a partial index, generating the proper spans for the scan with the proper data type.  If we add new logic for uniqueness checks that duplicates the decisions which constrained scan generation or lookup join generation need to consider, then it's another place in the code that needs to be maintained.  By using exploration rule results, we know the logic is always up-to-date.
- 


<!-- Sent from Reviewable.io -->

2023-08-02 15:22 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-Naqp4pjAn3PLZubp_F0:b-hx7sum) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
>As discussed offline, this is probably not relevant / out of scope for this change, but [@msirek](https://github.com/msirek) will follow up with the field team to understand the use cases that need to be supported.

Yeah, their use case is hash-sharded RBR table with unique index, single-row insert.

>I haven't reviewed this PR in detail so I'll defer to you and [@mgartner](https://github.com/mgartner), but I'll reiterate that we should aim to implement the simplest, cleanest solution that will support the customer's use cases, and nothing m

The new changes I will push later will reduce the complexity. I told @drewdeally we're only going to support the single-row case in the first pass, but he said they might want support for the multi-row case, and he'll ask them about that. But maybe we won't have time to do it in 23.2.


<!-- Sent from Reviewable.io -->

2023-08-02 15:29 UTC, rytaft reviewed
> Reviewed 1 of 4 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @drewdeally, @mgartner, @michae2, @msirek, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 4876 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYtQlon4GocTjCm4fbm:-NaqrIvrDCGyrurOJ10h:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5608eb3dc6cd2d7929e79c88b70bb75318acb28a/pkg/sql/opt/exec/execbuilder/testdata/unique#L4876)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

>As discussed offline, this is probably not relevant / out of scope for this change, but [@msirek](https://github.com/msirek) will follow up with the field team to understand the use cases that need to be supported.

Yeah, their use case is hash-sharded RBR table with unique index, single-row insert.

>I haven't reviewed this PR in detail so I'll defer to you and [@mgartner](https://github.com/mgartner), but I'll reiterate that we should aim to implement the simplest, cleanest solution that will support the customer's use cases, and nothing m

The new changes I will push later will reduce the complexity. I told @drewdeally we're only going to support the single-row case in the first pass, but he said they might want support for the multi-row case, and he'll ask them about that. But maybe we won't have time to do it in 23.2.
</blockquote></details>

SGTM


<!-- Sent from Reviewable.io -->

2023-08-03 22:26 UTC, msirek reviewed
RFAL
Note, there is a temporary ugly hack in `factory_gen.go` needed because optgen assumes that only the first expression in a list expression needs replacement when `Replace` or `CopyAndReplaceDefault` is called, but I wanted to get what I have available for review.
Suggestions are welcome on how to handle this differently. I will be trying to figure out a better solution as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NaxTeVs4oWa2sYICH7C:b-gkca2n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/insert_fastpath.go` line 43 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NaqieM01mxKbbdIdQUR:-Nawxqup01WhlJZVz7gY:b-opg7el) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/insert_fastpath.go#L43)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We can use optimizer constructs here rather than mimicking execbuilder ones. You can define this information in optgen by adding `IndexOrdinal`, `ColList`, `ScalarListExpr` for the datums and we should be able to construct the error message at execbuilder time like we do here: https://github.com/cockroachdb/cockroach/blob/bb857aae80e1f20f67b457e7a8e790f208aa8cb5/pkg/sql/opt/exec/execbuilder/mutation.go#L781
</blockquote></details>

I've moved the initialization of the error check function back to the execbuilder and removed the MatchMethod. The other elements are updated as suggested.  `DatumsFromConstraint` is a new element I added (not execbuilder specific) which is a sparse 2-dimensional array of Datums found in index constraint spans, which are optimizer structures. Were you suggesting to try to re-write this into a `ScalarListExpr`? It might be difficult and might make issues harder to debug.  Also, right now `optgen` is aware of the `InsertFastPathFKUniqCheck` type. Are you suggesting to get rid of this type and place its elements directly in `UniqueChecksItemPrivate`?  Just wondering if there's a reason not to group all of these related items together in a structure.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NaxI2Yw9EY7XQWGWbxH:b-ki3cp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

A test with a partial unique without index constraint should have ran into this bug. For example, the select filter applied to the WithScan below cannot be ignored:

```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  r STRING NOT NULL,
  a INT,
  b INT,
  UNIQUE (r, a) WHERE b > 0,
  UNIQUE WITHOUT INDEX (a) WHERE b > 0,
  CHECK (r IN ('east', 'west'))
)
----

opt
INSERT INTO t VALUES (1, 'east', 10, 100), (2, 'west', 20, 200)
----
insert t
 ├── columns: <none>
 ├── insert-mapping:
 │    ├── column1:7 => t.k:1
 │    ├── column2:8 => t.r:2
 │    ├── column3:9 => t.a:3
 │    └── column4:10 => t.b:4
 ├── check columns: check1:11
 ├── partial index put columns: partial_index_put1:12
 ├── input binding: &1
 ├── cardinality: [0 - 0]
 ├── volatile, mutations
 ├── project
 │    ├── columns: partial_index_put1:12!null check1:11!null column1:7!null column2:8!null column3:9!null column4:10!null
 │    ├── cardinality: [2 - 2]
 │    ├── fd: (10)-->(12), (8)-->(11)
 │    ├── values
 │    │    ├── columns: column1:7!null column2:8!null column3:9!null column4:10!null
 │    │    ├── cardinality: [2 - 2]
 │    │    ├── (1, 'east', 10, 100)
 │    │    └── (2, 'west', 20, 200)
 │    └── projections
 │         ├── column4:10 > 0 [as=partial_index_put1:12, outer=(10)]
 │         └── column2:8 IN ('east', 'west') [as=check1:11, outer=(8)]
 └── unique-checks
      └── unique-checks-item: t(a)
           └── project
                ├── columns: a:21!null
                ├── cardinality: [0 - 2]
                └── semi-join (lookup t@t_r_a_key,partial)
                     ├── columns: k:19!null a:21!null b:22!null
                     ├── lookup expression
                     │    └── filters
                     │         ├── t.r:14 IN ('east', 'west') [outer=(14), constraints=(/14: [/'east' - /'east'] [/'west' - /'west']; tight)]
                     │         └── a:21 = t.a:15 [outer=(15,21), constraints=(/15: (/NULL - ]; /21: (/NULL - ]), fd=(15)==(21), (21)==(15)]
                     ├── cardinality: [0 - 2]
                     ├── select
                     │    ├── columns: k:19!null a:21!null b:22!null
                     │    ├── cardinality: [0 - 2]
                     │    ├── with-scan &1
                     │    │    ├── columns: k:19!null a:21!null b:22!null
                     │    │    ├── mapping:
                     │    │    │    ├──  column1:7 => k:19
                     │    │    │    ├──  column3:9 => a:21
                     │    │    │    └──  column4:10 => b:22
                     │    │    └── cardinality: [2 - 2]
                     │    └── filters
                     │         └── b:22 > 0 [outer=(22), constraints=(/22: [/1 - ]; tight)]
                     └── filters
                          └── k:19 != t.k:13 [outer=(13,19), constraints=(/13: (/NULL - ]; /19: (/NULL - ])]
```
</blockquote></details>

Note that with the new implementation, the above test case can legally use insert fast path because the partial index predicate is added to the new FastPathIndexCheck in the optbuilder.  Since the unique without index check should only be applied when `b > 0` and the index only scans rows where `b > 0`, this exact match means a constrained scan is built, and we never scan rows via the scan which shouldn't be checked.
___
*[`pkg/sql/opt/xform/insert_funcs.go` line 424 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-Naqcf7QEGQmn5n2SfOq:-Nawr4Vg-krDZAo9T417:b-684017) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/xform/insert_funcs.go#L424)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You can  replace `0 /* primary index */` with `cat.PrimaryIndex`.
</blockquote></details>

findKeyColOrd is removed in the latest implementation.


<!-- Sent from Reviewable.io -->

2023-08-03 23:18 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NaxgPYM9y9DLVN5u4yX:b-u3qr8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Note that with the new implementation, the above test case can legally use insert fast path because the partial index predicate is added to the new FastPathIndexCheck in the optbuilder.  Since the unique without index check should only be applied when `b > 0` and the index only scans rows where `b > 0`, this exact match means a constrained scan is built, and we never scan rows via the scan which shouldn't be checked.
</blockquote></details>

disregard this comment... making some more changes here.


<!-- Sent from Reviewable.io -->

2023-08-04 00:19 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 234 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTgPhR2Jv2iUjOEVxx:-NaxuKpPA8_TGNJv7XKa:b-i3wuj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L234)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

disregard this comment... making some more changes here.
</blockquote></details>

OK, I've changed this so that if there is a uniqueness check with a partial index predicate, fast path is  
disallowed in the optbuilder.


<!-- Sent from Reviewable.io -->

2023-08-04 00:21 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 238 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NYTipG3785XtDjeMFN2:-NaxubHeD0oJYpN70Fp6:b-7l7d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ceb1bfb137d86d48012f29e868e2b255801330/pkg/sql/opt/exec/execbuilder/mutation.go#L238)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The above test case adds the `b > 0` check as a column in the projection, so we fail this check:
https://github.com/msirek/cockroach/blob/5a8f1f0e39d292a5b41249271baa2bb0a460ca07/pkg/sql/opt/xform/insert_funcs.go#L91-L97

... and never enter the fast path flow.

The following test case produces a filter which almost matches what `ignorablePKNEConstCheck` checks for:

```sql
statement ok
CREATE TABLE regional_by_row_table (
  pk int,
  pk2 int NOT NULL,
  a int NOT NULL,
  b int NOT NULL,
  j JSON,
  INDEX (a),
  UNIQUE (b),
  INVERTED INDEX (j),
  PRIMARY KEY(pk, pk2)
) LOCALITY REGIONAL BY ROW

statement ok
CREATE UNIQUE INDEX uniq_idx ON regional_by_row_table(a) WHERE pk2 != 3

# We should plan uniqueness checks for all unique indexes in
# REGIONAL BY ROW tables.
query T
SELECT * FROM [EXPLAIN INSERT INTO regional_by_row_table (pk, pk2, a, b) VALUES (1, 2, 3, 4)] OFFSET 2
----
```
This is not using fast path though because there is more than 1 filter (there is also the normal NE primary key check filter), and the function returns false unless there is exactly one filter. That primary key check filter should always be generated.

For multi-row insert with a partial index predicate like `WHERE pk2 != b`, that fails the projection check mentioned above.

So, so far I am not seeing a way for fast path to get chosen when there is a partial index predicate being used as a Select filter.
</blockquote></details>

Fast path is now disabled in the optbuilder if the unique constraint has a predicate.


<!-- Sent from Reviewable.io -->

2023-08-04 02:40 UTC, msirek reviewed
OK, I fixed the issue in `factory_gen.go` by creating a separate `FastPathUniqueChecks`.  Since each of these checks has a single relational expression, the `Replace` and `CopyAndReplaceDefault` are now properly called with any special-casing required.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NayOxYp8bbCxVEe7zzv:b-o8g7dg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-08-04 22:58 UTC, msirek commented
I'm breaking this into smaller commits and will push that out later.

2023-08-07 20:12 UTC, mgartner commented
Is this ready for review @msirek?

2023-08-07 20:20 UTC, msirek reviewed
In terms of code reorganization, yes.  I was considering whether any of these commits might need a unit test, but if you feel like re-starting the review, feel free to.  I don't have any further code reorganization changes coming.  I had some questions for you from your last comments on whether you were asking for `opt.InsertFastPathFKUniqCheck` to be eliminated (and maybe the elements added individually to `FastPathUniqueChecksItemPrivate`), so maybe that's something you could look at first.  Those items are now in the first commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NbGcYma5-9jpID2-3YY:bsml3iy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-08-10 18:33 UTC, mgartner requested changes
I only had time to look at the first commit so I haven't seen how it all fits together, but this approach seems more natural. The first commit should have tests for the new logic - is there a way to add those?

I'd recommend putting change that just move functions around, like you did with the remap functions, in their own commit because it makes reviewing those changes almost trivial. You don't have to do that here, but something to keep in mind in the future.

> Reviewed 2 of 30 files at r23, 2 of 4 files at r25, 1 of 3 files at r28, 9 of 28 files at r32, 25 of 27 files at r34.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NbVhbGz6ZTARUuxmR7N:b19msc0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/insert_fastpath.go` line 43 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NaqieM01mxKbbdIdQUR:-NbUsHaE17o5NHpJefkp:b-31t7pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/insert_fastpath.go#L43)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I've moved the initialization of the error check function back to the execbuilder and removed the MatchMethod. The other elements are updated as suggested.  `DatumsFromConstraint` is a new element I added (not execbuilder specific) which is a sparse 2-dimensional array of Datums found in index constraint spans, which are optimizer structures. Were you suggesting to try to re-write this into a `ScalarListExpr`? It might be difficult and might make issues harder to debug.  Also, right now `optgen` is aware of the `InsertFastPathFKUniqCheck` type. Are you suggesting to get rid of this type and place its elements directly in `UniqueChecksItemPrivate`?  Just wondering if there's a reason not to group all of these related items together in a structure.
</blockquote></details>

I was suggesting defining this in optgen, like:

```
[Private]
define FastPathUniqueChecksItemPrivate {
    ReferencedTableID TableID
    ReferencedIndex IndexOrdinal
    InsertCols ColList
    DatumsFromConstraint ScalarListExpr
}
```

Where `DatumsFromConstraint` is like the `Rows` field of the `Values` expression: a ScalarListExpr of Tuples. It could also be a ScalarListExpr of ScalarListExprs of Datums, if that's easier.

Why would this make debugging more difficult?

If there is a strong reason to diverge from the common pattern for this struct, then I suggest we move this file to the `memo` package so that it's in the same package as other memo structs.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 345 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVf6s6B9HtyxXu8FCg:-NbVf6s6B9HtyxXu8FCh:b-dsjp32) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L345)):*
> ```Go
> 	// ORed predicate, eg. (col1 = 1 AND col2 = 2) OR (col1 = 3 AND col2 = 4)...
> 	if isValues && len(valuesExpr.Rows) == 1 && valuesExpr.Rows[0].Op() == opt.TupleOp {
> 		tupleExpr, _ := valuesExpr.Rows[0].(*memo.TupleExpr)
> ```

nit: reduce nesting by returning early if the checks don't pass, like:

```go
if !isValues || len(valuesExpr.Row) > 1 ... {
    return nil
}
```
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 352 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVepxICTrBPrS_Q-S3:-NbVepxICTrBPrS_Q-S4:bmsi32u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L352)):*
> ```Go
> 				if i >= len(withScanExpr.InCols) {
> 					scanFilters = scanFilters[:0]
> 					break
> ```

nit: rather than truncate the slice and break, can we just `return nil` here and in a couple places below?
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 440 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVaRjI-QVERSYHrbTI:-NbVaRjI-QVERSYHrbTJ:b-swlq9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L440)):*
> ```Go
> 	var scanFilters memo.FiltersExpr
> 	// Fast path is disabled if this check is for a unique partial index,
> 	// or a UNIQUE WITHOUT INDEX with a partial index predicate.
> ```

nit: I would just say a "UNIQUE WITHOUT INDEX with a partial index predicate". The "unique partial index" is confusing in this context because unique indexes don't need checks. From the optimizer's perspective the RBR unique indexes are just a unique index plus a UNIQUE WITHOUT INDEX.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 501 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVh4VX0K6_qh2yz15g:-NbVh4VX0K6_qh2yz15h:bifkdq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L501)):*
> ```Go
> 	// fast path cannot be applied.
> 	if foundScan && len(scanFilters) != 0 {
> 		newScanPrivate := f.CustomFuncs().DuplicateScanPrivate(&scanExpr.ScanPrivate)
> ```

Is `uniqueChecksHelper.buildTableScan` avoided here because the execution can't handle a Project of virtual computed columns - so we only want to build a scan?


<!-- Sent from Reviewable.io -->

2023-08-14 20:43 UTC, msirek reviewed
> I only had time to look at the first commit so I haven't seen how it all fits together, but this approach seems more natural. The first commit should have tests for the new logic - is there a way to add those?

Thanks. I've added 2 unit tests in the 2nd and 3rd commits.  There is also now a unit test in the execbuilder code in the 4th commit.

>I'd recommend putting change that just move functions around, like you did with the remap functions, in their own commit because it makes reviewing those changes almost trivial. You don't have to do that here, but something to keep in mind in the future.

Sure, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-Nbpk7ov3Xg6vrIgI0xL:ba8n26t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/insert_fastpath.go` line 43 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NaqieM01mxKbbdIdQUR:-NbhKeve296lzp91zY0V:b-umw9xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3784cfe4713b0f74c3d30390165b7524ca4d8350/pkg/sql/opt/insert_fastpath.go#L43)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was suggesting defining this in optgen, like:

```
[Private]
define FastPathUniqueChecksItemPrivate {
    ReferencedTableID TableID
    ReferencedIndex IndexOrdinal
    InsertCols ColList
    DatumsFromConstraint ScalarListExpr
}
```

Where `DatumsFromConstraint` is like the `Rows` field of the `Values` expression: a ScalarListExpr of Tuples. It could also be a ScalarListExpr of ScalarListExprs of Datums, if that's easier.

Why would this make debugging more difficult?

If there is a strong reason to diverge from the common pattern for this struct, then I suggest we move this file to the `memo` package so that it's in the same package as other memo structs.


</blockquote></details>

OK, updated as suggested.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 345 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVf6s6B9HtyxXu8FCg:-NbhBAEt1vXCuASd16vT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L345)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: reduce nesting by returning early if the checks don't pass, like:

```go
if !isValues || len(valuesExpr.Row) > 1 ... {
    return nil
}
```
</blockquote></details>

Done
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 352 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVepxICTrBPrS_Q-S3:-NbhBTm05sTUBH8pjvAL:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: rather than truncate the slice and break, can we just `return nil` here and in a couple places below?
</blockquote></details>

Done
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 440 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVaRjI-QVERSYHrbTI:-NbhBexS3Qbypj2U2mtV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L440)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I would just say a "UNIQUE WITHOUT INDEX with a partial index predicate". The "unique partial index" is confusing in this context because unique indexes don't need checks. From the optimizer's perspective the RBR unique indexes are just a unique index plus a UNIQUE WITHOUT INDEX.
</blockquote></details>

Done
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 501 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVh4VX0K6_qh2yz15g:-NbhFdnIAg2nLnQpuJm7:b-4do0di) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L501)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is `uniqueChecksHelper.buildTableScan` avoided here because the execution can't handle a Project of virtual computed columns - so we only want to build a scan?
</blockquote></details>

It may make things more complicated if we try to specifically search for and process a projection of a virtual computed column, and my understanding is we wish to target a very narrow set of cases in the first pass.  In some cases, where we build a Values expression, the projection may be merged with the Values by a rewrite, in which case we'll find the value and handle it. In other cases where we have a WithScanExpr of a Values expression, and a projection, the projection may not be merged.  I think that if and when foreign key fast path checking code gets refactored, the need to build a WithScanExpr may go away and the current simple handling will also handle those cases.

It sounds like calling `uniqueChecksHelper.buildTableScan` is preferred over `DuplicateScanPrivate` though, so I've updated the code to use the former. 


<!-- Sent from Reviewable.io -->

2023-09-05 21:27 UTC, msirek commented
@mgartner Friendly reminder about this one. I know you're on call this week, but maybe next week you might have some spare cycles to look back at it.

2023-09-13 23:07 UTC, mgartner commented
Sorry for the delay. I'll take a look tomorrow.

2023-09-14 22:20 UTC, mgartner commented
I'm still working on the review and have some comments for the first commit. But before I leave those, I wanted to explore an alternative that came to mind while reviewing this.

From the get-go, one of the main problems we set out to solve here was:

> How can we find suitable lookup indexes for unique checks **from the memo?**

Are we over-constraining the problem here? Shouldn't we really be solving for:

> How can we find suitable lookup indexes for unique checks **any way possible**?

I believe we constrained ourselves to using the memo because we were following the lead of FK checks, which do the same. But I don't believe we need to, and I'm not convinced it will be a better solution in the long-run. I searched for some reasoning behind this particular part of the fast-path FK checks design, and I couldn't find any. So I'm inclined to believe that we simply used the memo because it was the easiest path forward for FK checks at the time and maybe still today—the multi-table relationship makes them more of a brain-bender than uniqueness checks.

So if we don't have to search the memo for a lookup index, can we find a lookup index on our own during the execbuilder phase? I believe the answer is yes, and this prototype I put together shows that it works in a few cases I tested. I haven't yet been able to think of any cases where this method would fail in theory, but maybe someone else can?

Here's the prototype, with more context in the commit message, let me know what your thoughts are: https://github.com/cockroachdb/cockroach/pull/110688





<!-- Sent from Reviewable.io -->

2023-09-15 06:43 UTC, msirek reviewed
Thanks for looking into this. That prototype does seem simpler. On the first pass I can't see any issues with the approach. I'm going to try fleshing it out and see how it holds up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NeMZ63E1HaqZn0gJWqA:b-wtrxe5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-09-18 02:38 UTC, msirek reviewed
I made some code changes to the prototype, and It looks like the approach taken would work. It would, however, mean that the execbuilder is now taking on the role of the optimizer in determining which logical operations (unique checks) need to be handled, and deciding the physical plan (the indexes to use).  

My understanding of the purpose of the execbuilder is that it's only supposed to handle a translation of the optimized operation tree, in the form of memo expressions, into an operation tree that the execution engine understands. Pushing more logic into the execbuilder seems a little backwards and blurs the lines between SQL layer components. There has been discussion in the past about moving some of the decisions the distsql engine makes into the optimizer, so that those decisions can be cost based. This is another reason to build the fast path plan in the optimizer. If, for example, there were multiple indexes which could handle a given uniqueness check, and one of the indexes had a leaseholder preference matching the gateway region, the optimizer could detect this and pick this index as it would incur a lower latency cost.  

So, while the current approach has more parts to it and lines of code than this prototype, I believe it fits better into the separation of duties assigned to CRDB components and aligns with the goal of keeping as much query plan decision-making as possible in the optimizer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-Ne_wa2DBCrcKDpjF6uq:b-s11dy3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-09-18 19:44 UTC, mgartner commented
Cool! How did the complexity compare to this approach as you filled in some of the gaps in the prototype? Are the changes available to look at?

I agree that the execbuilder is usually performing simple translations from optimizer expressions into execution plan nodes, so the location of this logic seems out of place. In the long-term, it doesn't need to reside in execbuilder—it's only there because that's where the insert fast-path decision making is currently being done. In the future it could be moved into the optimizer and improved further.

But I don't think the location of the logic isn't the most important difference between the two solutions. The key difference is in how the lookup indexes are found: pattern matching an optimizer expression translated from a uniqueness check or searching the catalog with the uniqueness check information in the catalog. I believe the lossy translations of the former and the fragility of expression pattern matching is what creates the majority of the limitations and complexity.

What are the current benefits of the pattern-matching approach that justify the complexity and the limitations?





<!-- Sent from Reviewable.io -->

2023-09-18 22:08 UTC, msirek reviewed
> Are the changes available to look at?

Not complete, but I added 2 commits on top of yours here, and included the new tests from `regional_by_row_query_behavior` which are mostly passing:
https://github.com/cockroachdb/cockroach/pull/110861/commits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NeeJsYD2RZb-8yEXZ5a:b-sntvsq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-09-20 05:49 UTC, msirek reviewed
> In the long-term, it doesn't need to reside in execbuilder—it's only there because that's where the insert fast-path decision making is currently being done. In the future it could be moved into the optimizer and improved further.

I'm having trouble seeing how this would happen without a good deal of rework. The prototype is working with a `Datums` row and producing a `roachpb.Span`. Things which the optimizer doesn't currently work on. The optimizer generally works on memo expressions. This is in the same vein as your previous comment:
> We can use optimizer constructs here rather than mimicking execbuilder ones. You can define this information in optgen by adding IndexOrdinal, ColList, ScalarListExpr for the datums and we should be able to construct...

It seems like we already went down the path of deciding that the optimizer is the correct location for building fast path uniqueness checks in a previous review cycle using structures that the optimizer deals with, which is the reason why the effort was put in to move the implementation out of the execbuilder. Moving the logic at a later time might never get done with all the other features which need attention. Better to build it in the proper location the first time around.

> But I don't think the location of the logic isn't the most important difference between the two solutions. The key difference is in how the lookup indexes are found: pattern matching an optimizer expression translated from a uniqueness check or searching the catalog with the uniqueness check information in the catalog. I believe the lossy translations of the former and the fragility of expression pattern matching is what creates the majority of the limitations and complexity.

> What are the current benefits of the pattern-matching approach that justify the complexity and the limitations?

Instead of being fragile and limited, I believe the current approach is more robust because it leverages the optimizer interfaces, which get updated for each new feature which is added. For example, if we have a hash-sharded index, given an equality predicate on the index column, the optimizer is able to derive an equality condition on the computed shard column to find the exact shard it is assigned to and only perform the uniqueness check in that shard instead of all shards. In the prototype, we'd need to explicitly add code to handle computation of the shard column (currently it probes all shards). Hash-sharded indexes are a major use case for this feature. 

Any new feature which comes along might then need special handling added in the fast path code. But by using optimizer interfaces, it just works. All predicate derivations are handled for us. Index selection is handled for us. All invisible indexes are automatically ignored. Costing is done, if needed. Any other changes which are added for constrained scans (locking?) could detect how the index is used and build the appropriate structures, etc.  Altogether it may lighten the load of extending fast path uniqueness checks to support more features in the future. If fast path uniqueness checks are not implemented in the optimizer in the first pass, it's a good bet it will be a while (or never) before the logic is moved over there, meaning addition of new features would be adding more and more logic into the execbuilder (to support fast path) which should exist in the optimizer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-Nel28mC0A-YgcEb-Zd_:b50vjrl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-09-21 21:47 UTC, msirek commented
The last 2 pushes update the code to the latest master and add the Locking attribute to fast path checks, copied over from the Scan which the check was built upon.

2023-09-22 17:05 UTC, rharding6373 reviewed
Wow, this is impressive work! I've reviewed 5/9 commits so far with mostly just clarification questions to understand it better. If you wanted to I think you could split some of the commits off into their own PRs (e.g., the Autocommit commit) but I'm not sure that would make the whole thing more manageable, and splitting off some of the meaty commits would lose some comment history, so not sure that's desirable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-Nexphel5ToNCPo_-5dT:b-mlmrc1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/explain_bundle.go` line 338 at r57](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexjoaS2PgbRUjmg1oG:-NexjoaS2PgbRUjmg1oH:bd0hknu) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b1b0cf6cb4437583e7020f6cff2f4233053085/pkg/sql/explain_bundle.go#L338)):*
> ```Go
> 		memo.ExprFmtHideQualifications|memo.ExprFmtHideScalars|memo.ExprFmtHideTypes|memo.ExprFmtHideNotVisibleIndexInfo|memo.ExprFmtHideFastPathChecks,
> 	))
> 	b.z.AddFile("opt-vv.txt", formatOptPlan(memo.ExprFmtHideQualifications|memo.ExprFmtHideNotVisibleIndexInfo|memo.ExprFmtHideFastPathChecks))
> ```

Why omit it from opt-vv.txt? Seems like it would be useful to include the plan for the fast path check in stmt bundles. If it will be used for some checks in production, how will we debug if it turns out there are issues with the fast path? 

Including it would also be consistent with the treatment of `EXPLAIN(TYPES)` below.
___
*[`pkg/sql/opt/exec/factory.go` line 256 at r59](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexomMQEUZRp9VidC3d:-NexomMQEUZRp9VidC3e:byjwqsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/42bceff242a8c8b6dcee7803fa2fd70a3f204f56/pkg/sql/opt/exec/factory.go#L256)):*
> ```Go
> // ConstructInsertFastPath). It identifies the index into which we can perform
> // the lookup.
> type InsertFastPathFKUniqCheck struct {
> ```

optional nit: maybe rename this and others to `InsertFastPathCheck` instead.
___
*[`pkg/sql/opt/memo/interner.go` line 1197 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexhI1NDXd1HKLoo9SN:-NexhI1NDXd1HKLoo9SO:bccwg7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8701eaf5fc364ab839fcd67fdddd240fd5bb8a2c/pkg/sql/opt/memo/interner.go#L1197)):*
> ```Go
> 	}
> 	for i := range l {
> 		if l[i].ReferencedTableID != r[i].ReferencedTableID {
> ```

Should we also use `h.IsRelExprEqual` to compare the `Check` `RelExpr`, too?
___
*[`pkg/sql/opt/optbuilder/testdata/unique-checks-insert` line 2134 at r57](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-Nexlcxm1oAOORFPYtLO:-Nexlcxm1oAOORFPYtLP:bck62lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b1b0cf6cb4437583e7020f6cff2f4233053085/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L2134)):*
> ```
>       │              └── t.a:24 = 10
>       └── fast-path-unique-checks-item: &{0 0 [] [] {  record best-effort}}
>            └── values
> ```

Is this arm of the explain tree from making a non-nil fast path so we don't break `RelExpr`? Trying to understand what 

```
fast-path-unique-checks-item: &{0 0 [] [] {  record best-effort}}
           └── values
```

means, and why we have both this and a fleshed out fast path check above it.
___
*[`pkg/sql/opt/xform/testdata/rules/insert` line 187 at r58](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-Nexn7KwEfiWhPuh_n6-:-Nexn7KwEfiWhPuh_n60:bs674w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdf323eba3690047e76f66c73c3c27a00611aee/pkg/sql/opt/xform/testdata/rules/insert#L187)):*
> ```
>       │         │         ├── columns: t.k:26!null t.r:27!null t.c:30
>       │         │         ├── constraint: /27/30/26
>       │         │         │    ├── [/'east' - /'east']
> ```

I thought that fast path unique checks were characterized by a single KV lookup, but this looks like at least 2 KV look ups (for east and west) plus an index join. Am I not reading or understanding this right?


<!-- Sent from Reviewable.io -->

2023-09-25 16:27 UTC, rharding6373 reviewed
I've reviewed the remaining files and don't have any additional feedback, but I'd like to check out the benchmark results (are the ones in the commit message up-to-date?) and have responses to the open comments before giving a stamp of approval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NfC8lyI-acqNsceXVQL:b-c10oij)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @msirek, @rytaft, and @yuzefovich)

___
*[`pkg/sql/opt/bench/uniq_test.go` line 54 at r63](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NfC8zMN9hA_SmMGLv-9:-NfC8zMO3haLVlH7Hsyu:b-38hcgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/04780957dd9312aa63e94bb8a26d4d237a276242/pkg/sql/opt/bench/uniq_test.go#L54)):*
> ```Go
> }
> 
> func BenchmarkUniqInsert(b *testing.B) {
> ```

This might have gotten lost in the sea of comments, but could you please re-share the latest benchmark results? Thanks!


<!-- Sent from Reviewable.io -->

2023-09-25 23:41 UTC, mgartner requested changes
I've left my comments for the first commit. The first commit also needs:

1. optbuilder tests that show the new expressions being built for the cases covered by the new code.
2. norm tests for the new pruning normalization rules.
3. TestInterner tests for the new checks in interner_test.go - this might have caught the missing check that Rachael found

> If you wanted to I think you could split some of the commits off into their own PRs

+1 building this incrementally would speed up time-to-merge. It doesn't help that Reviewable is struggling with so many commit revisions.

> Reviewed 3 of 28 files at r32, 1 of 3 files at r38, 37 of 37 files at r40, 3 of 5 files at r47, 49 of 49 files at r48.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NfDgvAaA03PfxYQ4Gue:b-r49y8u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2, @msirek, and @yuzefovich)

___
*[`pkg/sql/opt/norm/rules/prune_cols.opt` line 542 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJDkQE5X_bYE77LG33:-NeJDkQE5X_bYE77LG34:b-ozoq38) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/norm/rules/prune_cols.opt#L542)):*
> ```
> )
> 
> # PruneReturningCols removes columns from the Insert operator's ReturnCols
> ```

nit: Prune**Insert**ReturnCols
___
*[`pkg/sql/opt/ops/mutation.opt` line 302 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJAgk-3EkABp5EYDTn:-NeJAgk-3EkABp5EYDTo:baxa8xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/ops/mutation.opt#L302)):*
> ```
>     # columns for a uniqueness check, in the order of the ReferencedIndexOrdinal
>     # columns. For each, the value in the array indicates the index of the
>     # column in the input table.
> ```

nit: This last sentence confuses me. A ColList is a list of column IDs, not ordinals. I believe that these column IDs contain the values being inserted, and the position in this list corresponds with the ordinal of the referenced index columns. Is that correct?
___
*[`pkg/sql/opt/ops/mutation.opt` line 305 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJBore1msXF2LbFSr-:-NeJBore1msXF2LbFSr0:b-k170uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/ops/mutation.opt#L305)):*
> ```
>     InsertCols ColList
> 
>     # DatumsFromConstraint contains constant values from the WHERE clause
> ```

This `WHERE` clause is from partial unique constraints? Or somewhere else?
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 501 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVh4VX0K6_qh2yz15g:-NeJM00LA_ViVXvzwbpb:bl3ey34) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L501)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It may make things more complicated if we try to specifically search for and process a projection of a virtual computed column, and my understanding is we wish to target a very narrow set of cases in the first pass.  In some cases, where we build a Values expression, the projection may be merged with the Values by a rewrite, in which case we'll find the value and handle it. In other cases where we have a WithScanExpr of a Values expression, and a projection, the projection may not be merged.  I think that if and when foreign key fast path checking code gets refactored, the need to build a WithScanExpr may go away and the current simple handling will also handle those cases.

It sounds like calling `uniqueChecksHelper.buildTableScan` is preferred over `DuplicateScanPrivate` though, so I've updated the code to use the former.
</blockquote></details>

I was genuinely curious, not necessarily preferring `buildTableScan`. DuplicateScanPrivate would be fine and seems simpler.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 96 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJNAH_5vgSvjvEu6dd:-NeJNAH_5vgSvjvEu6de:b-w26wz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L96)):*
> ```Go
> 			// any existing rows. The check prevents rows from matching themselves by
> 			// adding a filter based on the primary key.
> 			uniqueCheckItems, _ := h.buildInsertionCheck()
> ```

Can you leave a TODO to avoid the extra work of building the fast paths for this case?
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 136 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJNGR0Cikq-1V3mkuW:-NeJNGR0Cikq-1V3mkuX:bfn993q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L136)):*
> ```Go
> 			// any existing rows. The check prevents rows from matching themselves by
> 			// adding a filter based on the primary key.
> 			uniqueCheckItems, _ := h.buildInsertionCheck()
> ```

ditto: add a TODO here to avoid the extra work of building the fast paths for this case
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 334 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJHydhCajVNG8wZ6j8:-NeJHydhCajVNG8wZ6j9:bvscy24) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L334)):*
> ```Go
> 	if withScanScopeIsValues {
> 		valuesExpr = withScanScopeValues
> 		isValues = true
> ```

nit: simplify this to

```go
withScanExpr, isWithScan := withScanScope.expr.(*memo.WithScanExpr)
values, isValues := withScanScope.expr.(*memo.ValuesExpr)
```
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 428 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJKom40_dabmqX0shK:-NeJKom40_dabmqX0shL:b-yrmrz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L428)):*
> ```Go
> 		))
> 	}
> 	// Find the ScanExpr which reads from the table this unique check applies to.
> ```

nit: mention what cases there would be a project here and why it's safe to skip over the projects - I presume because we won't support tables with computed columns yet?
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 513 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJMvye3hmIpFy2LpYo:-NeJMvye3hmIpFy2LpYp:b-cyoq2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L513)):*
> ```Go
> 	} else {
> 		// Things blow up if a RelExpr is nil, so construct a minimal dummy relation
> 		// that will not be used.
> ```

Can we just return `nil` as the second return value of this function instead?
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 315 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NfDdvYM1AVssYh8UpZd:-NfDdvYM1AVssYh8UpZe:b-tzl3i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8701eaf5fc364ab839fcd67fdddd240fd5bb8a2c/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L315)):*
> ```Go
> // path uniqueness check).
> func (h *uniqueCheckHelper) buildFiltersForFastPathCheck(
> 	withScanScope *scope, scanExpr *memo.ScanExpr,
> ```

This deserves some more explanation of how it works. It looks like you're either pulling out a Values expression from the unique check that's already been inlined, or you're trying to find a Values expression in the Insert's input. Is that correct?

Also, I think the naming like `withScanScope` is adding confusion here because it's not necessarily a WithScan expression. You could consider the names `uniqueCheckScope`. And `in [...]

2023-09-27 15:21 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, and @yuzefovich)

___
*[`pkg/sql/explain_bundle.go` line 338 at r57](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexjoaS2PgbRUjmg1oG:-NfINogcBtg3qPaT5O9r:b-nldkeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/99b1b0cf6cb4437583e7020f6cff2f4233053085/pkg/sql/explain_bundle.go#L338)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why omit it from opt-vv.txt? Seems like it would be useful to include the plan for the fast path check in stmt bundles. If it will be used for some checks in production, how will we debug if it turns out there are issues with the fast path? 

Including it would also be consistent with the treatment of `EXPLAIN(TYPES)` below.
</blockquote></details>

Good point. Modified it to include fast path check expressions.
___
*[`pkg/sql/opt/exec/factory.go` line 256 at r59](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexomMQEUZRp9VidC3d:-NfIW8j88A4zJOS4s_rY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/42bceff242a8c8b6dcee7803fa2fd70a3f204f56/pkg/sql/opt/exec/factory.go#L256)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional nit: maybe rename this and others to `InsertFastPathCheck` instead.
</blockquote></details>

Done
___
*[`pkg/sql/opt/memo/interner.go` line 1197 at r48](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NexhI1NDXd1HKLoo9SN:-NfIX2cd72G2OYdGpvnQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8701eaf5fc364ab839fcd67fdddd240fd5bb8a2c/pkg/sql/opt/memo/interner.go#L1197)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we also use `h.IsRelExprEqual` to compare the `Check` `RelExpr`, too?
</blockquote></details>

Done
___
*[`pkg/sql/opt/norm/rules/prune_cols.opt` line 542 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJDkQE5X_bYE77LG33:-NfIXL4s77QwSG4LqHKK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/norm/rules/prune_cols.opt#L542)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Prune**Insert**ReturnCols
</blockquote></details>

Done
___
*[`pkg/sql/opt/ops/mutation.opt` line 302 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJAgk-3EkABp5EYDTn:-NfIadi_E7fNP7BGPN-j:b-egnzl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/ops/mutation.opt#L302)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: This last sentence confuses me. A ColList is a list of column IDs, not ordinals. I believe that these column IDs contain the values being inserted, and the position in this list corresponds with the ordinal of the referenced index columns. Is that correct?
</blockquote></details>

Reworded this to:
```
	# InsertCols contains the table column ordinals of the referenced index key
	# columns. The position in this list corresponds with the ordinal of the
	# referenced index column (its position in the index key).
```
___
*[`pkg/sql/opt/ops/mutation.opt` line 305 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJBore1msXF2LbFSr-:-NfIcvpJESvb3kn9vYGs:bq2tp6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/ops/mutation.opt#L305)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This `WHERE` clause is from partial unique constraints? Or somewhere else?
</blockquote></details>

Mention of a WHERE clause is confusing, perhaps.  The values are from the insert row or check constraint. Updated it to:
```
    # DatumsFromConstraint contains constant values from the insert row for the
    # columns in the unique constraint. Columns not available directly from the
    # insert row or computed from insert row values (computed column) may be
    # filled in from a CHECK constraint on the column. The number of entries
    # corresponds with the number of KV lookups. For example, when built from
    # analyzing a locality-optimized operation accessing 1 local region and 2
    # remote regions, the resulting DatumsFromConstraint would have 3 entries.
```
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 501 at r34](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NbVh4VX0K6_qh2yz15g:-NfM2NnT83sUnJIJn3U6:bwf3al3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b27ccb9ae45dd4cc7f12d67099152d9b2da0ba7/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L501)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I was genuinely curious, not necessarily preferring `buildTableScan`. DuplicateScanPrivate would be fine and seems simpler.
</blockquote></details>

OK. Looking at this again, it seems like calling `buildTableScan` may be more robust as it will always build the correct fields under the Scan, and DuplicateScanPrivate is not coded to copy all scan private fields.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 96 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJNAH_5vgSvjvEu6dd:-NfIinjf3TstOSC1n6_o:b2fzz89) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L96)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you leave a TODO to avoid the extra work of building the fast paths for this case?
</blockquote></details>

Added a buildFastPathCheck parameter to buildInsertionCheck to handle this.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 136 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJNGR0Cikq-1V3mkuW:-NfK1IQ_5LjHm5gW0s4G:b2fzz89) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L136)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

ditto: add a TODO here to avoid the extra work of building the fast paths for this case
</blockquote></details>

Added a buildFastPathCheck parameter to buildInsertionCheck to handle this.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 334 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJHydhCajVNG8wZ6j8:-NfK8REr9ehR2dylUPAB:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L334)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: simplify this to

```go
withScanExpr, isWithScan := withScanScope.expr.(*memo.WithScanExpr)
values, isValues := withScanScope.expr.(*memo.ValuesExpr)
```
</blockquote></details>

Done
___
*[`pkg/sql/opt/optbuilder/mutation_builder_unique.go` line 428 at r40](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-NeJKom40_dabmqX0shK:-NfM0REW9LhPM2sLTlCR:b-hn4dw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cccbbf6bfe90193c5924cce87f9170f6e472a05/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L428)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: mention what cases there would be a project here and why it's safe to skip over the projects - I presume because we won't support tables with computed columns yet?
</blockquote></details>

OK, added:
```
		// Projections may have been added such as for computed column expressions.
		// Skip over these to fi [...]

2023-09-28 03:31 UTC, msirek reviewed
> The first commit also needs:
> 1. optbuilder tests that show the new expressions being built for the cases covered by the new code.

The commit titled "memo: optbuild unit tests for fast path unique check exprs" has these tests, in file pkg/sql/opt/optbuilder/testdata/unique-checks-insert.  

> 2. norm tests for the new pruning normalization rules.

I found PruneInsertInputCols is never fired and there doesn't seem to be a use case for it, so removed it.  I've added some norm tests for PruneInsertReturnCols.

> 3. TestInterner tests for the new checks in interner_test.go

Added TestInterner tests

>> If you wanted to I think you could split some of the commits off into their own PRs

>+1 building this incrementally would speed up time-to-merge. It doesn't help that Reviewable is struggling with so many commit revisions.

I've split the first 3 commits off into a separate PR:  https://github.com/cockroachdb/cockroach/pull/111403
Once that merges I can either rebase this PR, or split off the next couple commits, etc.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102995#-:-NfMEY-zEVXwx01XrpDQ:b-7hg8nz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, @rharding6373, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-10-02 17:36 UTC, msirek commented
RFAL, either in this PR, or in the split off PR: https://github.com/cockroachdb/cockroach/pull/111403

2023-10-02 17:38 UTC, yuzefovich commented
It's been a while since I looked at this PR, is there a particular commit(s) that you'd like me to take a look at?

2023-10-02 17:54 UTC, msirek commented
> It's been a while since I looked at this PR, is there a particular commit(s) that you'd like me to take a look at?

Thanks! The execution side changes haven't really changed much, except there is now unit test `TestAddUniqChecks` in 5c0000a00e7637582a640eb81b1f63f4c895974f and file mutation.go in b7f76651ba70a01d039c93886718052c87e8f380 looks a bit different.

2023-10-10 00:09 UTC, closed without merging

2023-10-10 00:09 UTC, msirek commented
The changes in this PR have been merged as separate PRs:
#111403
#111786
#111822
#112059

The last commit, [xform: minimize the number of KV lookups for fast-path unique checks](https://github.com/cockroachdb/cockroach/pull/102995/commits/4e0bf0b87f0c0e56bbe9bd1bb0cf8938e7d0878b), was not merged, but could be opened as a possible future improvement.