roachtest: add v=5 and timeout for decommission
cockroachdb/cockroach pull request #103141
Opened 2023-05-11 20:10 UTC by kvoli

The `decommission` roachtests previously did not enable vmodule logging for key decommission related files. This commit adds this.

This commit also adds an individual timeout for the `decommission/nodes=4/duration=x` roachtest. This test repeatedly decommissions a node, which shouldn't take longer than 5 minutes. The timeout is added to expedite failure, when failure is imminent.

Related: #103029

Epic: none

Release note: None

2023-05-11 20:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103141)
<!-- Reviewable:end -->

2023-05-11 21:50 UTC, AlexTalks requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/decommission.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103141#-NVBmZAMC53YLapqBvmH:-NVBmZAMC53YLapqBvmI:bs1zk7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb87ac688bf0c4977e242661b94d279f6d581b70/pkg/cmd/roachtest/tests/decommission.go#L334)):*
> ```Go
> 			}
> 
> 			if _, err := h.decommission(ctx, targetNodeList, pinnedNode, "--wait=all", "--checks=skip"); err != nil {
> ```

I think this needs to be removed, no?


<!-- Sent from Reviewable.io -->

2023-05-11 21:51 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/decommission.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103141#-NVBmZAMC53YLapqBvmH:-NVBn2S39APRTNykNuXR:b75z5va) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb87ac688bf0c4977e242661b94d279f6d581b70/pkg/cmd/roachtest/tests/decommission.go#L334)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

I think this needs to be removed, no?
</blockquote></details>

It does need to be removed - good catch


<!-- Sent from Reviewable.io -->

2023-05-11 21:53 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103141)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/decommission.go` line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103141#-NVBmZAMC53YLapqBvmH:-NVBnO7w9D7OQziZVRl-:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb87ac688bf0c4977e242661b94d279f6d581b70/pkg/cmd/roachtest/tests/decommission.go#L334)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It does need to be removed - good catch
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2023-05-11 21:56 UTC, AlexTalks approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103141#-:-NVBoEAeCYEjsTViRSeP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)



<!-- Sent from Reviewable.io -->

2023-05-12 00:03 UTC, kvoli commented
Ran all the `decommission/` roachtests to verify this change is fine.

```
roachtest run 'decommission/' --cockroach='./cockroach'
...
--- PASS: decommission/drains (93.41s)
--- PASS: decommission/randomized (168.20s)
--- PASS: decommission/slow (238.70s)
--- PASS: decommission/mixed-versions (556.72s)
--- PASS: drain-and-decommission/nodes=9 (2716.09s)
--- PASS: decommission/nodes=4/duration=1h0m0s (3706.84s)
PASS
```

TYFTR

2023-05-12 00:03 UTC, kvoli commented
bors r=alextalks

2023-05-12 01:16 UTC, merged