sql/catalog: avoid fetching descriptors when fetching comments
cockroachdb/cockroach pull request #103106
Opened 2023-05-11 12:49 UTC by fqazi

Previously, we refactored the code to fetch comments, descriptors, and zone config together in all cases. A side effect of this change was that the crdb_internal.kv_system_comments table was substantially slower for larger tables leading to big regressions. To address this, this patch adds a method of only fetching comments within the collections. 

Additionally, we added many builtins into both functions, which meant our existing virtual index look-up could end up falling back too frequently to full scans. Also, a virtual index is added on the kv_catalog_comments table for fast point look-ups when referencing descriptors.

Informs: https://github.com/cockroachdb/cockroach/issues/102851
Fixes: https://github.com/cockroachdb/cockroach/issues/102613

Release note (bug fix): Optimize over-head of
pg_catalog.pg_description and pg_catalog.pg_shdescription, which can lead to performance regression relative to 22.2

2023-05-11 12:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103106)
<!-- Reviewable:end -->

2023-05-11 16:22 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @msirek)

___
*[`pkg/sql/crdb_internal.go` line 5467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAZl6P8mrQoGPqUYvo:-NVAZl6P8mrQoGPqUYvp:b8iw4z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/crdb_internal.go#L5467)):*
> ```Go
> 						return false, err
> 					}
> 					if ok, err := p.HasPrivilege(ctx, sysTable, privilege.SELECT, p.User()); err != nil {
> ```

we could probably save time by avoiding this SELECT check. the `system.comments` table gives the `public` role SELECT privileges, and that's immutable. so we don't necessarily _need_ to check it here
___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVA_ahiClAmf0UVtlCa:bfcurtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
> ```Go
> 							// support are indexes.
> 							if oid != 0 && !catid.IsOIDUserDefined(oid) {
> 								return true, nil
> ```

is this correct? we should only return `true` if any rows were generated.
___
*[`pkg/sql/pg_catalog.go` line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_oguEHBAsMUv9UOf:-NVA_oguEHBAsMUv9UOg:b-sgo4jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1152)):*
> ```Go
> 					table, ok := desc.(catalog.TableDescriptor)
> 					if !ok {
> 						return true, nil
> ```

ditto. we should only return `true` if any rows were generated
___
*[`pkg/sql/pg_catalog.go` line 1162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_sM1EdzIey7V8IFh:-NVA_sM1EdzIey7V8IFi:b-sgo4jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1162)):*
> ```Go
> 					if (!table.IsVirtualTable() && table.GetParentID() != db.GetID()) ||
> 						table.Dropped() || !canSeeDescriptor {
> 						return true, nil
> ```

ditto. we should only return `true` if any rows were generated
___
*[`pkg/sql/pg_catalog.go` line 1758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAaK5hEFJEQnpQU169:-NVAaK5hEFJEQnpQU16A:b-cqnmg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1758)):*
> ```Go
> 		dbContext catalog.DatabaseDescriptor,
> 		addRow func(...tree.Datum) error) error {
> 		_, err := getPgCatalogDescriptionByID(ctx, p, dbContext, addRow, 0)
> ```

this is a nit, but rather than overloading the parameter so that id==0 fetches everything, i think this would look cleaner if there was one function that fetched, and another one that populated.


<!-- Sent from Reviewable.io -->

2023-05-11 17:00 UTC, chengxiong-ruan requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @msirek, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAZl6P8mrQoGPqUYvo:-NVAiNz9E9FylRtKkgsX:bxm3dco) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/crdb_internal.go#L5467)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we could probably save time by avoiding this SELECT check. the `system.comments` table gives the `public` role SELECT privileges, and that's immutable. so we don't necessarily _need_ to check it here
</blockquote></details>

the down side is that `system.comments` only has primary index which starts with the `type` column instead of descriptor id :( , that's fixable by adding new index though..
___
*[`pkg/sql/pg_catalog.go` line 1633 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAjegW5NsUhGoSQnwF:-NVAjegW5NsUhGoSQnwG:b-gapbf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1633)):*
> ```Go
> 	FROM
> 		"".crdb_internal.kv_catalog_comments
>   WHERE object_id=$1;`,
> ```

looks like the only difference between this query and the one above is the where condition? we could share the common part and compose the query, the arguments can be an empty slice for the query above I think.


<!-- Sent from Reviewable.io -->

2023-05-11 17:01 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @fqazi, and @msirek)

___
*[`pkg/sql/crdb_internal.go` line 5467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAZl6P8mrQoGPqUYvo:-NVAkb30B0rAL_FspkCz:b-3bm0mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/crdb_internal.go#L5467)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

the down side is that `system.comments` only has primary index which starts with the `type` column instead of descriptor id :( , that's fixable by adding new index though..
</blockquote></details>

not sure i follow what you mean. i'm just saying we don't need to do a privilege check on system.comments; how does that relate to the primary index?


<!-- Sent from Reviewable.io -->

2023-05-11 17:19 UTC, chengxiong-ruan commented
*[`pkg/sql/crdb_internal.go` line 5467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAZl6P8mrQoGPqUYvo:-NVAoXRfCCklLJ_vQIpk:b-nh1xgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/crdb_internal.go#L5467)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not sure i follow what you mean. i'm just saying we don't need to do a privilege check on system.comments; how does that relate to the primary index?
</blockquote></details>

oh, sorry, I misread what you said, my quick glance thought you were saying select from the comments table. oops


<!-- Sent from Reviewable.io -->

2023-05-11 17:34 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @msirek, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAZl6P8mrQoGPqUYvo:-NVAph4E80FOw9NaGdmd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/crdb_internal.go#L5467)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

oh, sorry, I misread what you said, my quick glance thought you were saying select from the comments table. oops
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVAd4bVB6toY2RpWDxK:b-m4rma2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this correct? we should only return `true` if any rows were generated.
</blockquote></details>

So, this is done because it's an incomplete index, even if no rows are produced matched indicating they were able to generate a result set conclusively. Otherwise, a full scan will happen again. We know the non-user-defined OIDs will never result in a valid output from anything using these virtual tables (since they're aimed for index/constraint look-ups),  so we can safely short-circuit. I'll add a comment to clarify this part:

// We have a non-user defined OID, so we can concretely,
/ say there should be no rows. Since the only other OIDs we
// support for these virtual tables are indexes/constraints. 
// We can mark the result as populated, we know the underlying 
// table will generate no rows.
___
*[`pkg/sql/pg_catalog.go` line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_oguEHBAsMUv9UOf:-NVAehBv4bzaheiGf5m9:b-i8p200) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto. we should only return `true` if any rows were generated
</blockquote></details>

// If the descriptor is not a table, then we have a complete result
// from this virtual index. We can mark the result as populated,
// because we know the underlying table will generate no rows, since 
// the ID being queried is *not* a table.
___
*[`pkg/sql/pg_catalog.go` line 1162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_sM1EdzIey7V8IFh:-NVAf43S6LO4atTxYJdl:b-5jnz7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1162)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto. we should only return `true` if any rows were generated
</blockquote></details>

// Skip over tables from a different DB, ones which aren't visible
// or are dropped. From a virtual index viewpoint, we will consider
// this result set as populated, since the underlying full table will
// also skip the same descriptors.
___
*[`pkg/sql/pg_catalog.go` line 1633 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAjegW5NsUhGoSQnwF:-NVAojWf52WY3r5N7v41:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1633)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

looks like the only difference between this query and the one above is the where condition? we could share the common part and compose the query, the arguments can be an empty slice for the query above I think.
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 1758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAaK5hEFJEQnpQU169:-NVAfbiKCRsrkj4J5-WS:bvyto8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1758)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is a nit, but rather than overloading the parameter so that id==0 fetches everything, i think this would look cleaner if there was one function that fetched, and another one that populated.
</blockquote></details>

I agree, though not sure how to deal with the builtins, unless we push those down into getComments?


<!-- Sent from Reviewable.io -->

2023-05-11 18:01 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @fqazi, and @msirek)

___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVAvbBa9ntnKkYiymq5:b-c1gpgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

So, this is done because it's an incomplete index, even if no rows are produced matched indicating they were able to generate a result set conclusively. Otherwise, a full scan will happen again. We know the non-user-defined OIDs will never result in a valid output from anything using these virtual tables (since they're aimed for index/constraint look-ups),  so we can safely short-circuit. I'll add a comment to clarify this part:

// We have a non-user defined OID, so we can concretely,
/ say there should be no rows. Since the only other OIDs we
// support for these virtual tables are indexes/constraints. 
// We can mark the result as populated, we know the underlying 
// table will generate no rows.
</blockquote></details>

i see. this `makeAllRelationsVirtualTableWithDescriptorIDIndex` function is used by a few different virtual indexes. which one are you optimizing here? it seems like pg_attribute and pg_class are the only ones that have `includesIndexEntries == true`
___
*[`pkg/sql/pg_catalog.go` line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_oguEHBAsMUv9UOf:-NVAyHsQEVlQvzvrYVKA:btndgms) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1152)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

// If the descriptor is not a table, then we have a complete result
// from this virtual index. We can mark the result as populated,
// because we know the underlying table will generate no rows, since 
// the ID being queried is *not* a table.
</blockquote></details>

i see, thanks
___
*[`pkg/sql/pg_catalog.go` line 1162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_sM1EdzIey7V8IFh:-NVAyChy8pKiMcOir_xX:bchejqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1162)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

// Skip over tables from a different DB, ones which aren't visible
// or are dropped. From a virtual index viewpoint, we will consider
// this result set as populated, since the underlying full table will
// also skip the same descriptors.
</blockquote></details>

nice, this makes sense to me
___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVAxcht2MtkryEI9if0:bd77o2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
> ```Go
> 						if errors.Is(err, catalog.ErrDescriptorNotFound) ||
> 							catalog.HasInactiveDescriptorError(err) {
> 							// We have a non-user defined OID, so we can concretely,
> ```

hm this is kind of a hack right? the range of user-defined OIDs is not logically related to the range of OIDs assigned to indexes.

in other words, isn't it possible that there is an index whose OID is less than `oidext.CockroachPredefinedOIDMax`?
___
*[`pkg/sql/pg_catalog.go` line 1152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAwo5W5adI5lGXM6_Z:-NVAwo5W5adI5lGXM6__:b-4rnfgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1152)):*
> ```Go
> 					// If the descriptor is not a table, then we have a complete result
> 					// from this virtual index. We can mark the result as populated,
> 					// because we know the underlying table will generate no rows, since
> ```

is "underlying table" the right phrase to use here? should it say "underlying descriptor" instead? 


<!-- Sent from Reviewable.io -->

2023-05-11 18:24 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @msirek, and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVAyfNK73OLtqb7lMge:b-8o0top) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see. this `makeAllRelationsVirtualTableWithDescriptorIDIndex` function is used by a few different virtual indexes. which one are you optimizing here? it seems like pg_attribute and pg_class are the only ones that have `includesIndexEntries == true`
</blockquote></details>

pg_description is the same and should have `includesIndexEntries` since ID can either be a descriptor or an OID reference to an index/ constraint.
___
*[`pkg/sql/pg_catalog.go` line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_oguEHBAsMUv9UOf:-NVAz2aP0OGniAr24NRC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see, thanks
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 1162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_sM1EdzIey7V8IFh:-NVAz3Ax0VkVwIKley_f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1162)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice, this makes sense to me
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVB2YaN42SES9OAM5jl:b-l7bz6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm this is kind of a hack right? the range of user-defined OIDs is not logically related to the range of OIDs assigned to indexes.

in other words, isn't it possible that there is an index whose OID is less than `oidext.CockroachPredefinedOIDMax`?
</blockquote></details>

True, I switched this over to a safer hack, the problem is builtins. So, if an OID maps to one we pretty much just skip trying to join it.
___
*[`pkg/sql/pg_catalog.go` line 1152 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAwo5W5adI5lGXM6_Z:-NVAyt41BMuTgYlGkRjH:b-k3p230) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is "underlying table" the right phrase to use here? should it say "underlying descriptor" instead? 
</blockquote></details>

Done.

Good point


<!-- Sent from Reviewable.io -->

2023-05-11 19:23 UTC, chengxiong-ruan approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @msirek, and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBF_PxD5N5Rau6CHfJ:b-6uiege) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

True, I switched this over to a safer hack, the problem is builtins. So, if an OID maps to one we pretty much just skip trying to join it.
</blockquote></details>

yeah, good point from rafi and thanks for doing it the safer way. I don't think we would see a non-existing predefined OID, but yeah this is better.
___
*[`pkg/sql/pg_catalog.go` line 1621 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVBFDOL1rbPTuqGkexf:-NVBFDOL1rbPTuqGkexg:b-jhgmpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f367819bb7ba85cf55815d91ffbf9e843b51830c/pkg/sql/pg_catalog.go#L1621)):*
> ```Go
> 		queryArgs = []interface{}{descriptorID}
> 	}
> 	queryText.WriteString(";")
> ```

nit: Is `;` required? I guess not heh


<!-- Sent from Reviewable.io -->

2023-05-11 19:39 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @fqazi, and @msirek)

___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBJWYd4l7rCfQ-e4WR:b-pfshcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

yeah, good point from rafi and thanks for doing it the safer way. I don't think we would see a non-existing predefined OID, but yeah this is better.
</blockquote></details>

well actually is the new way technically safe? the fundamental problem here is that OIDs are not globally unique. we still could have an index OID that is the same as a builtin OID. i guess it's rare, but the `oidHasher` could still make an OID like that..


<!-- Sent from Reviewable.io -->

2023-05-11 19:44 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @msirek, and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBK-r21dXOEirYmklc:bx0k2i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

well actually is the new way technically safe? the fundamental problem here is that OIDs are not globally unique. we still could have an index OID that is the same as a builtin OID. i guess it's rare, but the `oidHasher` could still make an OID like that..
</blockquote></details>

@rafiss Honestly, there is a risk of collision. However, I don't see a good out here.  If we don't have any way of skipping OID's the query @dikshant posted will take ~7 seconds. The other changes get it down from 10 seconds, but that's still pretty bad, and this was milliseconds before.


<!-- Sent from Reviewable.io -->

2023-05-11 20:31 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @fqazi, and @msirek)

___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVBVa6JE6D1KF2SdMHI:bb817bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

pg_description is the same and should have `includesIndexEntries` since ID can either be a descriptor or an OID reference to an index/ constraint.
</blockquote></details>

i don't see anywhere where `pg_description` uses this. can you point it out to me?
___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBTm5dB8gi_dWBNjv9:b6k0bc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
I see that point. I have more of an issue with the strong language used in the comment:
```
							// We have a non-user defined OID, so we can concretely,
							// say there should be no rows. Since the only other OIDs we
							// support for these virtual tables are indexes/constraints.
							// We can mark the result as populated, we know the underlying
							// table will generate no rows.
```

This should be reworded to say that we could end up incorrectly skipping indexes/constraints since those OIDs can collide with builtin function OIDs.

> If we don't have any way of skipping OID's the query [@dikshant](https://github.com/dikshant) posted will take ~7 seconds.

I also am skeptical of this. Where is the 7 seconds coming from? If it's just because of this join, then maybe the optimizer could pick a better plan.

And I'm sure we could think of other ideas too. For example, what if we change `func (h oidHasher) getOid()` so that it always returns OIDs greater than `CockroachPredefinedOIDMax`? or always greater than `len(builtinOidsArray)`?


<!-- Sent from Reviewable.io -->

2023-05-11 20:48 UTC, chengxiong-ruan commented
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBZ2o0EoN8W6dT6bjo:b-8b2jza) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

I see that point. I have more of an issue with the strong language used in the comment:
```
							// We have a non-user defined OID, so we can concretely,
							// say there should be no rows. Since the only other OIDs we
							// support for these virtual tables are indexes/constraints.
							// We can mark the result as populated, we know the underlying
							// table will generate no rows.
```

This should be reworded to say that we could end up incorrectly skipping indexes/constraints since those OIDs can collide with builtin function OIDs.

> If we don't have any way of skipping OID's the query [@dikshant](https://github.com/dikshant) posted will take ~7 seconds.

I also am skeptical of this. Where is the 7 seconds coming from? If it's just because of this join, then maybe the optimizer could pick a better plan.

And I'm sure we could think of other ideas too. For example, what if we change `func (h oidHasher) getOid()` so that it always returns OIDs greater than `CockroachPredefinedOIDMax`? or always greater than `len(builtinOidsArray)`?
</blockquote></details>

Interesting (and good) idea...I want to say +1 to it, it's reasonable if we only expect index/constraints here, so only possible conflicts is from the hasher itself. I suppose changing the way how index/constraint OID are generated is fine, correct?


<!-- Sent from Reviewable.io -->

2023-05-11 20:50 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @fqazi, and @msirek)

___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBZy5GEBhx0REf-q-C:belj9wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
> I suppose changing the way how index/constraint OID are generated is fine, correct?
yeah, that's fine to do


<!-- Sent from Reviewable.io -->

2023-05-11 20:54 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @msirek, and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVBYqDL0GYO7mozX_fW:b-iotzl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't see anywhere where `pg_description` uses this. can you point it out to me?
</blockquote></details>

Sorry, I meant it uses partial indexes. It doesn't use that flag for them but implements the same behaviour since we have to special case for builtins.
___
*[`pkg/sql/pg_catalog.go` line 1134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVAxcht2MtkryEI9if-:-NVBY7LCBAl5g6eX6GFD:b-aaztbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4a967b3d2b9bbb95dbe8fdc6d9e2faf912b6d1f/pkg/sql/pg_catalog.go#L1134)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> I suppose changing the way how index/constraint OID are generated is fine, correct?
yeah, that's fine to do
</blockquote></details>

I think modifying the hasher would be a safer approach. I'll revert this part, and we can do that as a follow on because it will *impact* a lot of tests. Optimizer-wise, here is the plan (but there isn't much I can see here we don't have stats or any influence on user queries):



_Code snippet:_
```Go
  planning time: 3ms
  execution time: 7.5s
  distribution: local
  vectorized: true
  maximum memory usage: 310 KiB
  network usage: 0 B (0 messages)
  sql cpu time: 6.8s
  estimated RUs consumed: 0

  • hash join
  │ nodes: n1
  │ actual row count: 83
  │ estimated max memory allocated: 180 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 240µs
  │ equality: (oid) = (relnamespace)
  │
  ├── • filter
  │   │ nodes: n1
  │   │ actual row count: 2
  │   │ sql cpu time: 12µs
  │   │ filter: (nspname NOT IN ('bench', 'gp_toolkit', 'information_schema', 'pgagent')) AND (nspname NOT LIKE 'pg_%')
  │   │
  │   └── • virtual table
  │         nodes: n1
  │         actual row count: 5
  │         sql cpu time: 58µs
  │         table: pg_namespace@primary
  │
  └── • virtual table lookup join
      │ nodes: n1
      │ actual row count: 301
      │ sql cpu time: 6.8s
      │ table: pg_class@pg_class_oid_idx
      │ equality: (objoid) = (oid)
      │
      └── • filter
          │ nodes: n1
          │ actual row count: 2,235
          │ sql cpu time: 23µs
          │ filter: objsubid = 0
          │
          └── • virtual table
                nodes: n1
                actual row count: 2,235
                sql cpu time: 2ms
                table: pg_description@primary
(47 rows)

Time: 7.523s total (execution 7.523s / network 0.000s)
```


<!-- Sent from Reviewable.io -->

2023-05-12 17:46 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @fqazi, and @msirek)

___
*[`pkg/sql/crdb_internal.go` line 5445 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVG3359-x8toECjREsg:-NVG3359-x8toECjREsh:bfa4yja) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe85b4b194010b3736865e74b59fbb485df8ce5/pkg/sql/crdb_internal.go#L5445)):*
> ```Go
> 			incomplete: false,
> 			populate: func(ctx context.Context, unwrappedConstraint tree.Datum, p *planner, db catalog.DatabaseDescriptor, addRow func(...tree.Datum) error) (matched bool, err error) {
> 				all, err := p.Descriptors().GetAllComments(ctx, p.Txn())
> ```

since this is going to call GetAllComments anyway, what's the advantage of making an index?
___
*[`pkg/sql/crdb_internal.go` line 5455 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVG2gKc7ZFuwprMg-_R:-NVG2gKdCrCFs8944gkk:bwnixor) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe85b4b194010b3736865e74b59fbb485df8ce5/pkg/sql/crdb_internal.go#L5455)):*
> ```Go
> 						return false, err
> 					}
> 					if ok, err := p.HasPrivilege(ctx, sysTable, privilege.SELECT, p.User()); err != nil {
> ```

nit: just like the other check you removed, we can remove this privilege check on the system table


<!-- Sent from Reviewable.io -->

2023-05-12 17:48 UTC, rafiss commented
it seems like this might have affected `TestCompletions` -- likely not a coincidence since the CLI completions do rely on fetching comments.

2023-05-12 17:49 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @fqazi, and @msirek)

___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVG448LEfQtJqPkVW0Y:bpu371r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Sorry, I meant it uses partial indexes. It doesn't use that flag for them but implements the same behaviour since we have to special case for builtins.
</blockquote></details>

OK i see, but my question is: why are we changing `makeAllRelationsVirtualTableWithDescriptorIDIndex`? which table are you trying to optimize the performance of?


<!-- Sent from Reviewable.io -->

2023-05-12 18:47 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103106)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @dikshant, @msirek, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5445 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVG3359-x8toECjREsg:-NVG3tMP1JFUsnWEQuzX:bvw8bp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe85b4b194010b3736865e74b59fbb485df8ce5/pkg/sql/crdb_internal.go#L5445)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since this is going to call GetAllComments anyway, what's the advantage of making an index?
</blockquote></details>

It behaves better for loop joins, and the comments are normally cached between invocations (plus the comments table itself is pretty sparse/empty in most cases).
___
*[`pkg/sql/crdb_internal.go` line 5455 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVG2gKc7ZFuwprMg-_R:-NVG4tvw8DsHluz8vpsx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abe85b4b194010b3736865e74b59fbb485df8ce5/pkg/sql/crdb_internal.go#L5455)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: just like the other check you removed, we can remove this privilege check on the system table
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 1138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103106#-NVA_ahhCuI3bKR2e1MD:-NVG4vy65uCpRdnlpZsS:b-y6haz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ea95bd0a8b0d9c16b738b395b2e8cd5944625c7/pkg/sql/pg_catalog.go#L1138)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

OK i see, but my question is: why are we changing `makeAllRelationsVirtualTableWithDescriptorIDIndex`? which table are you trying to optimize the performance of?
</blockquote></details>

This helps on the pg_class side of things if we have a join with pg_description. Specifically when the OIDs are builtins, each time we hit a built-in a full scan of the table happens, because populated is false.


<!-- Sent from Reviewable.io -->

2023-05-12 23:36 UTC, fqazi commented
@chengxiong-ruan @rafiss TFTR!

bors r+

2023-05-13 02:36 UTC, fqazi commented
Flake in a backup and restore test, trying again.

bors r+

2023-05-13 03:11 UTC, merged

2023-05-15 17:26 UTC, rafiss commented
blathers backport 23.1