allocator2: add cand to replace for rebalance
cockroachdb/cockroach pull request #103298
Opened 2023-05-15 14:29 UTC by kvoli

This commit fills in these range analyzed constraint functions:

```
candidatesNonVoterConstraintsUnsatisfied
candidatesToReplaceVoterForRebalance
candidatesToReplaceNonVoterForRebalance
```

Epic: none

Release note: None

2023-05-16 00:54 UTC, sumeerbhola reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 909 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVVWrBk4GdT6xc0A16G:-NVVWrBk4GdT6xc0A16H:bxtljwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e431e792f27dfdb65d40881963451432205039c9/pkg/kv/kvserver/allocator/allocator2/constraint.go#L909)):*
> ```Go
> 					toRemoveVoters, rac.constraints.satisfiedByReplica[voterIndex][i]...)
> 			}
> 		}
> ```

nit: can you copy the comment you added ("Always include ...") here too.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 951 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVVYy5c8N4JMnrtBqQC:-NVVYy5c8N4JMnrtBqQD:buh9nhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e431e792f27dfdb65d40881963451432205039c9/pkg/kv/kvserver/allocator/allocator2/constraint.go#L951)):*
> ```Go
> 
> 	// Only need to remove a non-voter if some conjunction is oversatisfied
> 	// purely due to non-voters.
> ```

I think this needs changing. If a conjunction needs 3 replicas and we have 2 voters and 2 non-voters then something needs to be removed. Since this happens after `candidatesVoterConstraintsUnsatisfied()` and there is no change ongoing on this range, we must have decided not to remove the voter (and it makes sense to not fiddle with the voter since they are involved in quorum). So I think here we should do `if neededReplicas < actualVoterReplicas + actualNonVoterReplicas`.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVWzFh14WAj1WdG-C25:-NVWzFh14WAj1WdG-C26:b50cw92) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L990)):*
> ```Go
> 
> 	// Find all the constraints which the store being rebalanced away from was
> 	// required for satisfaction.
> ```

The code in `constraintsForAddingVoter()` and `candidatesToConvertFromNonVoterToVoter()` only looks at `voterConstraints` if they are not nil. See the 2 if-blocks one of which is `if rac.voterConstraints.isEmpty() && !rac.constraints.isEmpty()` and the other `if !rac.voterConstraints.isEmpty()`. This utilizes the assumption we have added that the `voterContraints` are at least as tight as `constraints` (in their conjunctions). I think we should do the same here.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1000 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-SYf7bZM6yM9IvaD:-NVX-SYf7bZM6yM9IvaE:b-m5lj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1000)):*
> ```Go
> 			}
> 		}
> 		if candidateSatisfyingConstraint &&
> ```

since the `storeID` will only appear in one index i, I think we can hoist this into the for loop and don't need `candidateSatisfyingConstraint` (and we'll only be checking one of `constraints` and `voterConstraints` so we can just return there).
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1002 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-pkS9s2gE4JkXsBq:-NVX-pkS9s2gE4JkXsBr:bqkgkul) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1002)):*
> ```Go
> 		if candidateSatisfyingConstraint &&
> 			int(c.numReplicas) > len(rac.constraints.satisfiedByReplica[voterIndex][i])+
> 				len(rac.constraints.satisfiedByReplica[nonVoterIndex][i])-1 {
> ```

Is this expression saying that only include `c` if `int(c.numReplicas) >= len(rac.constraints.satisfiedByReplica[voterIndex][i])+len(rac.constraints.satisfiedByReplica[nonVoterIndex][i])`, i.e., the constraint is not over-satisfied?
The -1 instead of >= threw me off.
I think this opens up a question: the "usage" comment was
```
// Rebalance:
//   Only if !notEnoughVoters() && !notEnoughNonVoters() && no constraints unsatisfied.
//   cc := candidatesToReplaceVoterForRebalance(storeID)
//   cc := candidatesToReplaceNonVoterForRebalance(storeID)
```
Which implies that no constraint will be over-satisfied.
But maybe this usage comment is a mistake.
We definitely want to ensure first that there are enough voters and non-voters, but what if we can't fix an under-satisfaction and have an over-satisfied constraint. Should rebalancing still work. My current thinking is to say it is ok if it does not (and that we can improve this later if necessary). If we stick with this assumption, this predicate should be trivially true. And if it is not true and we return with an empty constraint will we just rebalance to an arbitrary node which has nothing to do with any of the constraints in this span config?


<!-- Sent from Reviewable.io -->

2023-05-16 13:57 UTC, kvoli reviewed
Updated w/ review comments. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NVZqNmnEcdnIiwK0bYp:b-1u5fl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 909 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVVWrBk4GdT6xc0A16G:-NVZ_bXd7dz5p-Q3rpY5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e431e792f27dfdb65d40881963451432205039c9/pkg/kv/kvserver/allocator/allocator2/constraint.go#L909)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you copy the comment you added ("Always include ...") here too.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 951 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVVYy5c8N4JMnrtBqQC:-NVZa1Eg8R9Q6-kMnE-5:bf3ive6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e431e792f27dfdb65d40881963451432205039c9/pkg/kv/kvserver/allocator/allocator2/constraint.go#L951)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this needs changing. If a conjunction needs 3 replicas and we have 2 voters and 2 non-voters then something needs to be removed. Since this happens after `candidatesVoterConstraintsUnsatisfied()` and there is no change ongoing on this range, we must have decided not to remove the voter (and it makes sense to not fiddle with the voter since they are involved in quorum). So I think here we should do `if neededReplicas < actualVoterReplicas + actualNonVoterReplicas`.
</blockquote></details>

Ack - that makes sense. Updated.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1000 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-SYf7bZM6yM9IvaD:-NVZhHXU5qFJX7OBIiWZ:b-8tfq4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1000)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

since the `storeID` will only appear in one index i, I think we can hoist this into the for loop and don't need `candidateSatisfyingConstraint` (and we'll only be checking one of `constraints` and `voterConstraints` so we can just return there).
</blockquote></details>

I was wondering about this, done.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1002 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-pkS9s2gE4JkXsBq:-NVZhUSiCWKy2JvwVErI:bp8bd2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1002)):*
> Is this expression saying that only include `c` if `int(c.numReplicas) >= len(rac.constraints.satisfiedByReplica[voterIndex][i])+len(rac.constraints.satisfiedByReplica[nonVoterIndex][i])`, i.e., the constraint is not over-satisfied?

It is saying no constraint is not oversatisfied when ignoring the replica being replaced, or no constraint is undersatisfied when ignoring the replica being replaced . These are the same.  I updated to `>=`.

> If we stick with this assumption, this predicate should be trivially true. And if it is not true and we return with an empty constraint will we just rebalance to an arbitrary node which has nothing to do with any of the constraints in this span config?

You're saying that if the constraint which the to-be replaced replica satisfies is oversatisfied, which shouldn't occur due to our assumption that no constraint is under-satisfied before rebalancing? 

I don't think its good that we would end up rebalancing towards a node with no relation to the span config, if there are under-satisfied constraints. It implies that there will be necessary "repair" after the rebalance, potentially wasting snapshots. My opinion is it would be better if we asserted on `!notEnoughVoters() && !notEnoughNonVoters() && no constraints unsatisfied` for each range we consider for rebalancing and handled them as ranges needing attention if the assertion fails.


<!-- Sent from Reviewable.io -->

2023-05-16 15:50 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVWzFh14WAj1WdG-C25:-NV_F3BM4bPb_7f49chv:b-hym37x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L990)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The code in `constraintsForAddingVoter()` and `candidatesToConvertFromNonVoterToVoter()` only looks at `voterConstraints` if they are not nil. See the 2 if-blocks one of which is `if rac.voterConstraints.isEmpty() && !rac.constraints.isEmpty()` and the other `if !rac.voterConstraints.isEmpty()`. This utilizes the assumption we have added that the `voterContraints` are at least as tight as `constraints` (in their conjunctions). I think we should do the same here.
</blockquote></details>

Updated this as well, lmk if this is what you meant.


<!-- Sent from Reviewable.io -->

2023-05-16 18:47 UTC, sumeerbhola requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1002 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-pkS9s2gE4JkXsBq:-NV_sPjE01ddfGkRQ66b:bswdemu) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1002)):*
> You're saying that if the constraint which the to-be replaced replica satisfies is oversatisfied, which shouldn't occur due to our assumption that no constraint is under-satisfied before rebalancing?

Yep.

> I don't think its good that we would end up rebalancing towards a node with no relation to the span config, if there are under-satisfied constraints. It implies that there will be necessary "repair" after the rebalance, potentially wasting snapshots. My opinion is it would be better if we asserted on `!notEnoughVoters() && !notEnoughNonVoters() && no constraints unsatisfied` for each range we consider for rebalancing and handled them as ranges needing attention if the assertion fails.

Sounds good -- this is what I was leaning towards in my earlier comment.
Then the `return nil` cases become an error return.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NV_qv8qEfFdIZC_o9dB:-NV_qv8qEfFdIZC_o9dC:bgpzn93) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c61ba962a3f96a7f0c4373df9cd46cd573fc36/pkg/kv/kvserver/allocator/allocator2/constraint.go#L952)):*
> ```Go
> 	}
> 	// Remove a non-voter if some conjunction is oversatisfied, include an
> 	// all-replica constraint if the needed replicas is greater than actual.
> ```

nit: something is grammatically off with this sentence.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 996 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NV_r_Vf8xkZlqKlaxop:-NV_r_Vf8xkZlqKlaxoq:baleqat) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c61ba962a3f96a7f0c4373df9cd46cd573fc36/pkg/kv/kvserver/allocator/allocator2/constraint.go#L996)):*
> ```Go
> 				}
> 			}
> 		}
> ```

nit: could return nil at the end of the `if !rac.voterConstraints.isEmpty()` block so that it is clearer that there is no remaining logic for this code path.


<!-- Sent from Reviewable.io -->

2023-05-17 01:20 UTC, kvoli reviewed
Updated w/ assertion errors in relevant places. I started on testing but I ran into some issues that I haven't looked into -  commit with wip datadriven test https://github.com/cockroachdb/cockroach/commit/4af7610abdaca26e957f3ac4ff250c89d4fae944

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NVbHJoN5mKMB2dT0wKm:blihs26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1002 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVX-pkS9s2gE4JkXsBq:-NVaZSjL4srEm-WYJ1cu:b-6s0ck6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dca07df54c1a4fcf617aab01fabd24bf54efa328/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1002)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> You're saying that if the constraint which the to-be replaced replica satisfies is oversatisfied, which shouldn't occur due to our assumption that no constraint is under-satisfied before rebalancing?

Yep.

> I don't think its good that we would end up rebalancing towards a node with no relation to the span config, if there are under-satisfied constraints. It implies that there will be necessary "repair" after the rebalance, potentially wasting snapshots. My opinion is it would be better if we asserted on `!notEnoughVoters() && !notEnoughNonVoters() && no constraints unsatisfied` for each range we consider for rebalancing and handled them as ranges needing attention if the assertion fails.

Sounds good -- this is what I was leaning towards in my earlier comment.
Then the `return nil` cases become an error return.

</blockquote></details>

Updated to return error here as well as other functions with similar assertions.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NV_qv8qEfFdIZC_o9dB:-NVa0e7J2CRSO2h8GT5y:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c61ba962a3f96a7f0c4373df9cd46cd573fc36/pkg/kv/kvserver/allocator/allocator2/constraint.go#L952)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: something is grammatically off with this sentence.
</blockquote></details>

Reworded.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 996 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NV_r_Vf8xkZlqKlaxop:-NVa09aH1013m3_pH66X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c61ba962a3f96a7f0c4373df9cd46cd573fc36/pkg/kv/kvserver/allocator/allocator2/constraint.go#L996)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: could return nil at the end of the `if !rac.voterConstraints.isEmpty()` block so that it is clearer that there is no remaining logic for this code path.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 17:26 UTC, sumeerbhola requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NVejw934jpUIT-90qfD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVejW740W2QGvzpw4VF):*
nit: sentence reads strange.
How about:
Also add assertions which return an error when method preconditions are not met.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1047 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVegQgs4T0dNd0r9R_B:-NVegQgs4T0dNd0r9R_C:b-4djjng) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1047)):*
> ```Go
> func (rac *rangeAnalyzedConstraints) candidatesToReplaceVoterForRebalance(
> 	storeID roachpb.StoreID,
> ) (toReplace constraintsDisj, err error) {
> ```

`toReplace` should be a `constraintsConj` since we never have multiple conjunctions.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1055 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVefgrGCNVIrkKEvu7H:-NVefgrGCNVIrkKEvu7I:by87xpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1055)):*
> ```Go
> 	if !rac.voterConstraints.isEmpty() {
> 		for i, c := range rac.voterConstraints.constraints {
> 			// Find the first voter-constraint which the removing voter store
> ```

nit: "removing voter store" is a bit hard to parse since "removing voter" is attempting to be an adjective.
How about "Find the voter constraint which the voter store being replaced satisfies ..."

(dropped "the first" since the `satisfiedByReplica` only mentions a store once)
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1066 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVeggnB7-D9T4HBZkTn:-NVeggnB7-D9T4HBZkTo:b-jjsfkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1066)):*
> ```Go
> 			}
> 		}
> 		return nil, nil
> ```

this return is now an error case, since (a) we are required to find the storeID, (b) the constraint it satisfies must be exactly satisfied.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1071 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVegzDz7wH0SN26CS8h:-NVegzDz7wH0SN26CS8i:b-7in7up) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1071)):*
> ```Go
> 	if rac.voterConstraints.isEmpty() && !rac.constraints.isEmpty() {
> 		for i, c := range rac.constraints.constraints {
> 			// Find the first all-replica constraint which the removing voter store
> ```

same comment about "removing voter store"
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVehXG3ABB1rDMLeymQ:-NVehXG3ABB1rDMLeymR:b-q8hn75) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1101)):*
> ```Go
> 	}
> 
> 	if !rac.constraints.isEmpty() {
> ```

I will fix the normalization such that if there is always a non-nil Constraint if there are non-zero non-voters. And to ensure both Constraints and VoterConstraints are not nil. That will allow this code to be
```
if rac.constraints.isEmpty() {
   return nil, errors.Errorf("no non-voters configured")
}
```

Otherwise there is special casing needed in this method and `candidatesToReplaceVoterForRebalance` since we may not have populated the `satisfiedBy` slices. 


<!-- Sent from Reviewable.io -->

2023-05-23 15:49 UTC, kvoli reviewed
Updated w/ feedback and began on testing. I'll ping when it is ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NW8I8LUDolF09HV2Rmq:b-2cxu3r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`-- commits` line 13 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVejW740W2QGvzpw4VF):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: sentence reads strange.
How about:
Also add assertions which return an error when method preconditions are not met.
</blockquote></details>

It does read weird. I've updated to this suggestion.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1047 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVegQgs4T0dNd0r9R_B:-NVemiwb1wy31ghAFKB8:ba4n0ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1047)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`toReplace` should be a `constraintsConj` since we never have multiple conjunctions.
</blockquote></details>

I'm guessing the num_replicas (as in`internedConstraintsConj`) isn't important to also return here, as we know it is exactly one replica.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1055 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVefgrGCNVIrkKEvu7H:-NW8I5SE7lDOj8FhM0mp:b-5b3vpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1055)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: "removing voter store" is a bit hard to parse since "removing voter" is attempting to be an adjective.
How about "Find the voter constraint which the voter store being replaced satisfies ..."

(dropped "the first" since the `satisfiedByReplica` only mentions a store once)
</blockquote></details>

Reworded this.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1066 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVeggnB7-D9T4HBZkTn:-NW8I1C22uPvQHHfDPjq:b-s7j7tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1066)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this return is now an error case, since (a) we are required to find the storeID, (b) the constraint it satisfies must be exactly satisfied.
</blockquote></details>

Updated to return an err down below.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1071 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVegzDz7wH0SN26CS8h:-NW8HzWCCZy8Tei27dOT:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1071)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same comment about "removing voter store"
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVehXG3ABB1rDMLeymQ:-NW8Hvyy4c5ce6162gv_:bmagezf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I will fix the normalization such that if there is always a non-nil Constraint if there are non-zero non-voters. And to ensure both Constraints and VoterConstraints are not nil. That will allow this code to be
```
if rac.constraints.isEmpty() {
   return nil, errors.Errorf("no non-voters configured")
}
```

Otherwise there is special casing needed in this method and `candidatesToReplaceVoterForRebalance` since we may not have populated the `satisfiedBy` slices. 
</blockquote></details>

Ack - still need to update this.


<!-- Sent from Reviewable.io -->

2023-05-24 18:10 UTC, sumeerbhola reviewed
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1047 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVegQgs4T0dNd0r9R_B:-NWDwg5887w7LdWESo-d:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1047)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'm guessing the num_replicas (as in`internedConstraintsConj`) isn't important to also return here, as we know it is exactly one replica.
</blockquote></details>

Yep


<!-- Sent from Reviewable.io -->

2023-05-30 20:55 UTC, kvoli reviewed
I added some testing but it is not exhaustive.  PTAL @sumeerbhola and lmk what you think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NWiRJ-s10mon_q5j2ca:b-uuch3l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVehXG3ABB1rDMLeymQ:-NWhuQ7-8m9bEizW_5Q0:b5u2yw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1101)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Ack - still need to update this.
</blockquote></details>

Updated this for `candidatesToReplaceForNonVoterRebalance`. Also added an assertion failure for when there are constraints which aren't matched.


<!-- Sent from Reviewable.io -->

2023-05-30 21:31 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NWiZf2xEDJXumbOqu8Z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/constraint.go` line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NVehXG3ABB1rDMLeymQ:-NWiW4fdCNz-_6nsC0Bu:bsrfkwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ee47dece39682fcf773bb6f227045d353c1e424/pkg/kv/kvserver/allocator/allocator2/constraint.go#L1101)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Updated this for `candidatesToReplaceForNonVoterRebalance`. Also added an assertion failure for when there are constraints which aren't matched.
</blockquote></details>

Looks good
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiYsHNDDgUHNKCaH8D:-NWiYsHNDDgUHNKCaH8E:b-15ds02) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L53)):*
> ```
> ----
> 
> analyze-constraints config-name=multi-region1 release=false
> ```

do we need this `release=false` directive, or can the test retain the analyzed constraints struct until the next call to `analyze-constraints`?
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 229 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiXpQuCs5u3QomaQjz:-NWiXpQuCs5u3QomaQk-:bxniziz) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L229)):*
> ```
> # There are too many voters (4/3) and non-voters (3/2). +region=d,+zone=d2d is
> # oversatisfied (2/1) by s5 and s8, s6 satisfies no non-voter constraints.
> # Expect all of these as candidates. We prefer removng non-voters before
> ```

nit: removing
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 230 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiXrff0Tcv9NxrkT6R:-NWiXrff0Tcv9NxrkT6S:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L230)):*
> ```
> # oversatisfied (2/1) by s5 and s8, s6 satisfies no non-voter constraints.
> # Expect all of these as candidates. We prefer removng non-voters before
> # removng voting replicas.
> ```

ditto
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 335 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiYbqX7rxJJWHVPFk7:-NWiYbqX7rxJJWHVPFk8:b-n7dnzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L335)):*
> ```
> # Missing a voter to satisfy +region=a,-zone=a1:1, have a non-voter (s10) which
> # satisfies this constraint. Expect nonVoterToVoter suggests removing s10.
> analyze-constraints config-name=multi-region1 release=false show=false
> ```

I'd rather see the output, i.e., show=true, otherwise it is hard for a reader to quickly check.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZCxK38RVyVedpkPV:-NWiZCxK38RVyVedpkPW:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L378)):*
> ```
> # Missing voter constraint (+region=a,-zone=a1), expect a role swap and
> # voter unsatisfied constraint disjunction.
> analyze-constraints config-name=multi-region1 release=false show=false
> ```

ditto
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 420 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZFkX1CVZ5zZMHP6S:-NWiZFkX1CVZ5zZMHP6T:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L420)):*
> ```
> # Too many voters (4/3) and not enough non-voters (1/2). Voter store 3 and 11
> # satisfy an all replica constraint but no non-empty voter 
> analyze-constraints config-name=multi-region1 release=false show=false
> ```

ditto
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 510 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZHYvE41Ly4cPW-Bb:-NWiZHYvE41Ly4cPW-Bc:b-1pxqki) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L510)):*
> ```
> release 
> ----
> released
> ```

Are there any specific things you think are not well tested yet? If so, could you enumerate them in a TODO here so we can pick them up in the future.


<!-- Sent from Reviewable.io -->

2023-05-30 21:55 UTC, kvoli reviewed
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-:-NWie-Sk0wsRPehDLFlY:b-80sls6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiYsHNDDgUHNKCaH8D:-NWibFxRBXZsQXtutyb2:b-at9j6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L53)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do we need this `release=false` directive, or can the test retain the analyzed constraints struct until the next call to `analyze-constraints`?
</blockquote></details>

Not really necessary, removed.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 229 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiXpQuCs5u3QomaQjz:-NWibbkgBexVzPv1VGCo:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L229)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: removing
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 230 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiXrff0Tcv9NxrkT6R:-NWibcN-9TH0k0sgTDP3:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L230)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 335 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiYbqX7rxJJWHVPFk7:-NWibd9D6aNIBhRFvfUI:b-1r3l5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L335)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'd rather see the output, i.e., show=true, otherwise it is hard for a reader to quickly check.
</blockquote></details>

I removed the `show=...` flag.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZCxK38RVyVedpkPV:-NWibhK6CP2HaRXEmBVx:bw7rr44) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L378)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed show flag.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 420 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZFkX1CVZ5zZMHP6S:-NWibmKq9rIVZOgmS1pC:bw7rr44) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L420)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed show flag.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints` line 510 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103298#-NWiZHYvE41Ly4cPW-Bb:-NWicWlEAzIbHmq8t5ff:b-5y8bj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/666d4bf92d5f6d9be792276604a6628a5f7c74d5/pkg/kv/kvserver/allocator/allocator2/testdata/range_analyzed_constraints#L510)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are there any specific things you think are not well tested yet? If so, could you enumerate them in a TODO here so we can pick them up in the future.
</blockquote></details>

All of the candidate functions are tested on a rac where we expect a return value at least once.

Added a list of additional tests to add.


<!-- Sent from Reviewable.io -->

2023-05-30 21:58 UTC, kvoli commented
Updated to include epic and tracking issue link in commit message.

2023-05-30 22:52 UTC, kvoli commented
bors r=sumeerbhola

2023-05-31 00:36 UTC, merged