build: mark some optimizer libraries as `testonly`
cockroachdb/cockroach pull request #103313
Opened 2023-05-15 15:43 UTC by mgartner

The `pkg/sql/opt/bench`, `pkg/sql/opt/testutils/testcat`, and
`pkg/sql/opt/testutils/testexpr` libraries have been marked `testonly`.
This prevents them from being linked into a `cockroach` binary.

Epic: None

Release note: None

2023-05-15 16:32 UTC, rickystewart requested changes
```
ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/opbench/BUILD.bazel:4:11: in go_library rule //pkg/sql/opt/opbench:opbench: non-test target '//pkg/sql/opt/opbench:opbench' depends on testonly target '//pkg/sql/opt/testutils/testcat:testcat' and doesn't have testonly attribute set
ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/opbench/BUILD.bazel:4:11: Analysis of target '//pkg/sql/opt/opbench:opbench' failed
```

2023-05-16 15:55 UTC, rickystewart approved these changes
Thanks, looks great.

2023-05-16 15:55 UTC, rickystewart approved these changes
Thanks, looks great.

2023-05-16 16:29 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103313#-:-NV_O8sg61jCuFKpLcVU:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-05-17 15:26 UTC, mgartner commented
TFTRs!

bors r+

2023-05-17 19:56 UTC, merged