logictest: disable DistSQL while updating DistSQL span resolver
cockroachdb/cockroach pull request #103397
Opened 2023-05-16 10:39 UTC by yuzefovich

Over the last half a year we made a couple of changes that changed which session data internal queries are using, and as a result internal queries can now use DistSQL in most places. This can now lead to rare flakes in `fakedist-*` logic test configurations where we're updating the DistSQL span resolver after having started the cluster, meaning that internal queries that are using DistSQL might be running concurrently with the span resolver update. This is not allowed by the interface, so this commit should fix these rare flakes by explicitly disabling DistSQL on the cluster until after the span resolver is updated. We do so when connecting to each node in the cluster in order to avoid async replication delay for cluster settings update propagation.

I believe this violation of the interface is the root cause for segfault we saw in #100108, so this commit reverts the debugging introduced in response to that ticket.

Additionally, previously we updated the span resolver only on a single node in the cluster, and this commit updates it on all nodes in the cluster, which seems more reasonable.

Release note: None

2023-05-16 10:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103397)
<!-- Reviewable:end -->

2023-05-18 20:31 UTC, michae2 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/logictest/logic.go` line 1458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103397#-NVkXwHJD8bBdiPTG9iH:-NVkXwHJD8bBdiPTG9iI:bygzy2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e1aa994f637519bf0bc4b2bb6196691735a982a/pkg/sql/logictest/logic.go#L1458)):*
> ```Go
> 		// is needed since the internal queries could use DistSQL if it's not
> 		// disabled.
> 		for nodeIdx := 0; nodeIdx < cfg.NumNodes; nodeIdx++ {
> ```

I think there is a `serverutils.SetClusterSetting` that does this exact thing?

Oh, will this work if internal queries have already started executing between the `StartNewTestCluster` and the `conn.Exec`? Isn't there a way to pass settings to `StartNewTestCluster` already set, through `params.Settings` or something?


<!-- Sent from Reviewable.io -->

2023-05-18 20:31 UTC, michae2 reviewed
Nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103397#-:-NVkYuUaC2iEJpRmexqo:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)



<!-- Sent from Reviewable.io -->

2023-05-18 21:44 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103397)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

___
*[`pkg/sql/logictest/logic.go` line 1458 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103397#-NVkXwHJD8bBdiPTG9iH:-NVklg9i3lzZ2-awbIB2:b-1wc6x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e1aa994f637519bf0bc4b2bb6196691735a982a/pkg/sql/logictest/logic.go#L1458)):*
Nice, changed to use this helper method, didn't know about it.

> Oh, will this work if internal queries have already started executing between the `StartNewTestCluster` and the `conn.Exec`? Isn't there a way to pass settings to `StartNewTestCluster` already set, through `params.Settings` or something?

Good catch. Indeed, we want to prevent usage of DistSQL until after we're done updating the span resolver, done.


<!-- Sent from Reviewable.io -->

2023-05-18 22:13 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103397#-:-NVkvI6C82IKPxhRed0k:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2023-05-19 07:15 UTC, yuzefovich commented
TFTR!

bors r+

2023-05-19 07:51 UTC, merged