Adding FROM_IP and TO_IP builtins
cockroachdb/cockroach pull request #10349
Opened 2016-10-31 22:40 UTC by nathanejohnson

This ads two methods, FROM_IP and TO_IP builtins.

FROM_IP() takes a single BYTES value representing a binary IPV6 type and returns an appropriate string representation of that IP.  For IPV4 addresses, this is in dotted decimal format (i.e., 1.2.3.4) and for IPV6, it is in colon seprated format in shortest form(i.e., 2001::1).  Note that IPV4 can be encoded in this format as well, by prefixing two bytes of FF to the normal 8 byte (this is handled for you automatically in the next method).

TO_IP() takes a string representing either an IPV4 or IPV6 address and returns BYTES binary representation.  This is useful for storing IP data into a BYTES column.

Storing IP data in BYTES types allows you to do range queries, as an example:

    root@:26257> create table foo(ip bytes not null);
    CREATE TABLE
    root@:26257> insert into foo(ip) values (to_ip('2002:0db8:85a3:1234:1234:8a2e:0370:7334'));
    INSERT 1
    root@:26257> insert into foo(ip) values (to_ip('2000:0db8:85a3:1234:1234:8a2e:0370:7334'));
    INSERT 1
    root@:26257> insert into foo(ip) values (to_ip('2000:0db8:85a3:0000:0000:8a2e:0370:7334'));
    INSERT 1
    root@:26257> insert into foo(ip) values (to_ip('1.2.3.4'));
    INSERT 1
    root@:26257> select from_ip(ip) as ip from foo;
    +---------------------------------------+
    |                  ip                   |
    +---------------------------------------+
    | 2002:db8:85a3:1234:1234:8a2e:370:7334 |
    | 2000:db8:85a3:1234:1234:8a2e:370:7334 |
    | 2000:db8:85a3::8a2e:370:7334          |
    | 1.2.3.4                               |
    +---------------------------------------+
    (4 rows)
    root@:26257> select from_ip(ip) as ip from foo where ip between to_ip('1.1.1.1') and to_ip('2.2.2.2');
    +---------+
    |   ip    |
    +---------+
    | 1.2.3.4 |
    +---------+
    (1 row)
    root@:26257> select from_ip(ip) as ip from foo where ip between to_ip('2000::1') and to_ip('2002::1');
    +---------------------------------------+
    |                  ip                   |
    +---------------------------------------+
    | 2000:db8:85a3:1234:1234:8a2e:370:7334 |
    | 2000:db8:85a3::8a2e:370:7334          |
    +---------------------------------------+
    (2 rows)
    root@:26257>

2016-10-31 22:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=10349) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=10349) before we can accept your contribution.<br/>

2016-11-03 05:34 UTC, knz commented
Thanks for this! Any reason why you chose to make the functions autodetect the address format, instead of using a 2nd argument to specify it explicitly?

2016-11-04 20:16 UTC, nathanejohnson commented
@knz I know that in C, the inet_pton and inet_ntop requires an af parameter, is this how you would prefer it implemented?  Or would it be sufficient to add more rigorous checking that the parsed IP type is actually sane?  As it stands, the built in ParseIP seems pretty reliable at differentiating ipv4 from ipv6, and not requiring the AF parameter at least when calling from_ip would allow ipv6 and ipv4 to be stored in the same column and the formatting implied by select from_ip(ip) from foo;  would make sense for both types.  That was the goal at any rate.

2016-11-04 21:48 UTC, knz commented
So what I had in mind was to_addr and from_addr, with support for both ipv4/ipv6 and ethernet mac addresses.

2016-11-07 05:23 UTC, knz commented
Ok so I rescind my previous comment after Ben's good point on Gitter.

2016-11-07 05:27 UTC, knz requested changes

2016-11-07 05:27 UTC, knz commented on pkg/sql/parser/builtins.go
> +				if sv == "<nil>" {
Can you add a comment here that explains in which circumstances "<nil>" is returned.

2016-11-07 05:27 UTC, knz commented on pkg/sql/parser/builtins.go
> +				return NewDBytes(DBytes(net.ParseIP(string(*ipdstr)))), nil
You need to check the result of ParseIP here; as per the doc it returns nil if the address is invalid, in which case to_ip returns DNull.

2016-11-08 14:36 UTC, knz approved these changes
If you could squash these two commits before we merge, that'd be chill.

2016-11-08 15:05 UTC, knz commented
Thanks for the contribution :)

2016-11-08 15:13 UTC, knz commented
Oh wait sorry I forgot, could you paste the explanatory text now at the head of the PR into the commit message? We use "git log" quite more than GitHub's history.

2016-11-08 15:16 UTC, nathanejohnson commented
@knz updated.

2016-11-08 15:29 UTC, knz commented on pkg/sql/parser/builtins.go
> +				if sv == "<nil>" {
One last question, can you briefly explain here in the PR what is the rationale for returning NULL on error, instead of a conversion error?

2016-11-08 15:29 UTC, knz commented on pkg/sql/parser/builtins.go
> +					return DNull, nil
ditto

2016-11-08 17:00 UTC, knz commented
Beautiful.
Here's a cookie for you! :cookie:
(jk, we'll ack you in the release notes too :smile: )

2016-11-08 17:00 UTC, merged

2016-12-01 15:45 UTC, jseldess commented
Regenerated the functions docs to pick these up.

2016-12-23 02:44 UTC, jseldess commented
Descriptions added to docs as part of https://github.com/cockroachdb/docs/pull/948