roachtest: metamorphic ARM64 and FIPS clusters
cockroachdb/cockroach pull request #103710
Opened 2023-05-22 00:42 UTC by srosenberg

Previously, all roachtests used (cloud) machine types with the AMD64 (cpu) architecture. Recently [1], new CI infrastructure was added to run a clone of all the nightly roachtests, configured with FIPS; i.e., same AMD64 machine types, different AMI and crdb binary, patched with FIPS-certified openssl native code.

As of this PR, we add the capability to execute any roachtest in a cluster, configured with either
ARM64, FIPS, or AMD64 (default). This is controlled via the two CLI args: `metamorphic-arm64-probability` and `metamorphic-fips-probability`. The former denotes the probability (over the uniform distribution) of a new cluster provisioned using ARM64 VMs. The latter denotes the probability of a new AMD64 cluster provisioned with the FIPS-compliant (kernel) configuration.
In case a test is compatible only with AMD64, it's effectively excluded from the set; i.e., both
probabilities apply to compatible tests only.

Note, the two probabilties don't have to add up to 1. E.g., `metamorphic-arm64-probability==0.4`,
`metamorphic-fips-probability==0.2` denotes that ARM64 clusters are chosen ~40% of the time, whereas of the remaining ~60% AMD clusters, FIPS is chosen ~20%
of the time; i.e., ~12% of all clusters will use FIPS.

Note, the values '0' and '1' are absolute. Setting both to '0' is tantamount to the behavior before this PR. Setting either to '1' enforces _all_ clusters
are provisioned with either ARM64 or FIPS.
In case, a test is _not_ compatible with the chosen configuration, its provisioning will fail. Thus, '1' is typically used for manual (debug) runs.

This PR builds on [1], which enabled ARM64 provisioning for AWS in roachprod. We add ARM64 provisioning for GCE, i.e., T2A, as well as refactor 'arch' argument to
denote one of: AMD64, ARM64, FIPS, where the latter isn't formally a CPU architecture; however, it simplifies provisioning and binary staging.
We also modify roachprod.List to display CPU architecture, other than AMD64, with the machine type; this should make it easier to see which clusters are running ARM64 and FIPS configurations, as we ramp up their testing.

Epic: none
Release note: None

Resolves: https://github.com/cockroachdb/cockroach/issues/94957
Informs: https://github.com/cockroachdb/cockroach/issues/94986

[1] https://github.com/cockroachdb/cockroach/pull/99224
[2] https://github.com/cockroachdb/cockroach/pull/103243

2023-05-22 00:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103710)
<!-- Reviewable:end -->

2023-05-25 04:49 UTC, srosenberg commented on pkg/cmd/roachtest/tests/restore.go
> +			backup:  makeBackupSpecs(backupSpecs{cloud: spec.AWS}),
This fixes the noise from the cluster creation error: https://github.com/cockroachdb/cockroach/issues/78601#issuecomment-1561784414

2023-05-25 14:47 UTC, renatolabs reviewed
That's a lot of changes, more than I thought this would take!

Would be good to run a couple of runs (at least one full run) of tests in this branch before merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-:-NWIMsWZ3-adMaA1wGba:b-1x9j52)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rail, @smg260, and @srosenberg)

___
*[`pkg/build/info.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEXl41Appuo6MZQ8Of:-NWEXl41Appuo6MZQ8Og:b-m690cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/build/info.go#L174)):*
> ```Go
> 		Channel:           ch,
> 		EnvChannel:        envChannel,
> 		EnabledAssertions: enabledAssertions,
> ```

Is this part of this PR? I don't see how it's related.
___
*[`pkg/cmd/roachtest/cluster.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEYWwuCIVzShJpgLCd:-NWEYWwuCIVzShJpgLCe:b-9eipee) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L87)):*
> ```Go
> 	// failure), roachtest can be invoked with --metamorphic-encryption-probability=0
> 	encryptionProbability float64
> 	// Total probability with which new ARM64 clusters are provisioned, modulo test specs. which are incompatible.
> ```

Might be worth being more specific in terms of behavior of test spec + this parameter.

(I know there's more info in the commit, but comments are more accessible than git blame, especially when you need to traverse the ancestry).
___
*[`pkg/cmd/roachtest/cluster.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWE_HMY4XJ-X_B8_Sqa:-NWE_HMZ78KWtvpwCdRx:b-u8unln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L133)):*
> ```Go
> 	}
> 	// Check that the binary ELF format matches the expected architecture.
> 	cmd := exec.Command("file", "-b", abspath)
> ```

Another option would be to use https://pkg.go.dev/debug/elf.
___
*[`pkg/cmd/roachtest/cluster.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEa4VMCVlDXCiKhmUj:-NWEa4VN9Q0oUqgQaM_y:b-w5gjxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L198)):*
> ```Go
> }
> 
> func findBinaryOrLibrary(
> ```

This function's behavior turned even more nuanced with the changes in this PR. A high level comment would be quite helpful IMO (especially the implicit naming conventions).
___
*[`pkg/cmd/roachtest/cluster.go` line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEaNKMAPMOnkoRi_da:-NWEaNKMAPMOnkoRi_db:b-39zcs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L231)):*
> ```Go
> 	}
> 	nameSuffixes := []string{archInfo.DebugArchitecture, archInfo.ReleaseArchitecture}
> 	find := func(dir, name string) string {
> ```

I personally don't see what this `find` function is adding. If it were removed, all its current uses could still be replaced by one-liner calls to `exec.LookPath` and that explicitness is arguably more understandable.
___
*[`pkg/cmd/roachtest/cluster.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEc4ak8H2cVOgZCQB6:-NWEauIr5M9e6UII9UO0:bioccay) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L287)):*
> ```Go
> 
> func initBinariesAndLibraries() {
> 	//TODO(srosenberg): enable metamorphic local clusters; currently, local==true means run all tests locally.
> ```

Do we actually want that? Many tests wouldn't work with `local` by design (and forcing that is not fruitful IMO).

Perhaps a better direction would be to have a structured way for a test to say if it supports local execution or not (instead of every test doing their own checks during test runtime).
___
*[`pkg/cmd/roachtest/cluster.go` line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEcXiD11vCwHmVb4nC:-NWEcXiD11vCwHmVb4nD:b-69xbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L293)):*
> ```Go
> 		defaultOsName = runtime.GOOS
> 		if arm64Probability == 1 {
> 			// N.B. if arm64Probability != 1, then we're running a metamorphic local cluster where amd64 is still default.
> ```

I don't understand this comment -- what's a metamorphic local cluster?
___
*[`pkg/cmd/roachtest/cluster.go` line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI77_s3GpyF2y12Vyj:-NWI77_s3GpyF2y12Vyk:blmn7so) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L302)):*
> ```Go
> 
> 	// Finds a binary. If the binary 'isRequired', but not found, exit and print the error.
> 	findDefaultBinary := func(binName string, userSpecified string, arch vm.CPUArch, isRequired bool, checkEA bool) (string, error) {
> ```

The `DFefault` part is confusing to me -- it takes into account the `userSpecified` parameter, which is not "default". Maybe... `resolveBinaryPath` or something along those lines?
___
*[`pkg/cmd/roachtest/cluster.go` line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI6FGZ9UQ2BxlORpX9:-NWI6FGZ9UQ2BxlORpXA:b97wmec) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L309)):*
> ```Go
> 		abspath, err := findBinary(path, defaultOsName, arch, checkEA)
> 		if err != nil {
> 			if !isRequired {
> ```

Arguably more readable as

```go
err := errors.Newf("ERROR: unable to find required binary %q for %q: %s\n", binName, arch, err)
if isRequired {
    fmt.Fprintf(os.Stderr, "%v", err)
    os.Exit(1)
}
return err
```
___
*[`pkg/cmd/roachtest/cluster.go` line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI2GmoAXDZ6iOFDouq:-NWI2GmoAXDZ6iOFDour:bax3aht) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L324)):*
> ```Go
> 				fmt.Fprintf(os.Stderr, "ERROR: found %q at: %s instead of the user-specified path: %s\n", binName, abspath, userSpecified)
> 				os.Exit(1)
> 			}
> ```

Same comment as above about rearranging the error logic.


We could also improve the error message here for the `err != nil` scenario.
___
*[`pkg/cmd/roachtest/cluster.go` line 382 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI8_XV9_5pESLThViv:-NWI8_XV9_5pESLThViw:bvegflr) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L382)):*
> ```Go
> 	}
> 	// Looks like we have all the binaries we'll need. Let's print them out.
> 	fmt.Printf("\nFound the following binaries:\n")
> ```

Nit: is the extra `\n` intentional?
___
*[`pkg/cmd/roachtest/main.go` line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIAtr2CNuWgo46d1UA:-NWIAtr30550o8ssGn8x:bexqkjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/main.go#L162)):*
> ```Go
> 					fmt.Printf("AMD64 clusters will be provisioned with probability %.2f\n", amd64Probability)
> 				}
> 				if fipsProbability > 0 {
> ```

Missing `&& amd64Probability > 0`?
___
*[`pkg/cmd/roachtest/main.go` line 195 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIDk3E3OXhO-k3_-Gx:-NWIDk3I3X2ViAen2m3g:b-67csca) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/main.go#L195)):*
> ```Go
> 	rootCmd.PersistentFlags().Float64Var(
> 		&fipsProbability, "metamorphic-fips-probability", defaultFIPSProbability,
> 		"conditi [...]

2023-05-26 15:28 UTC, srosenberg reviewed
> That's a lot of changes, more than I thought this would take!

Exactly my sentiment. I thought it'd be a fairly small change, but given the sprawl of roachtest, even small changes end up being entangled. My hope is that every the subsequent (refactoring) PR it will be slightly easier to refactor how we do "metamorphic" things inside roachtest. This PR just does it naively to keep the sprawl radius bounded.

> Would be good to run a couple of runs (at least one full run) of tests in this branch before merging.

Absolutely! I am going to do at least a couple of full runs over the weekend before declaring it's ready to be merged.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-:-NWNPQse8odqH3lvJcvK:buj1uyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rail, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/cluster.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWE_HMY4XJ-X_B8_Sqa:-NWNQNhe99kwSFQTGoV8:b-y69i8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L133)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Another option would be to use https://pkg.go.dev/debug/elf.
</blockquote></details>

Thanks for the pointer; I'll check it out. However, I'll probably keep as is since this code is not on any critical path; but in case, the ELF api is easy to use, I'll replace.
___
*[`pkg/cmd/roachtest/cluster.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEa4VMCVlDXCiKhmUj:-NWNQbj-7AM2TSJp90nI:b6bxafa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L198)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This function's behavior turned even more nuanced with the changes in this PR. A high level comment would be quite helpful IMO (especially the implicit naming conventions).
</blockquote></details>

Agreed. The whole business of "finding" binaries and libraries seems more complicated than it needs to be; will add a comment.
___
*[`pkg/cmd/roachtest/cluster.go` line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEaNKMAPMOnkoRi_da:-NWNR4AH1TTjw-xB1GVL:be07atn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L231)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I personally don't see what this `find` function is adding. If it were removed, all its current uses could still be replaced by one-liner calls to `exec.LookPath` and that explicitness is arguably more understandable.
</blockquote></details>

Yep, I tried not to change _everything_ in an effort to reduce the changes in this PR, but I now see your point; will simplify.
___
*[`pkg/cmd/roachtest/cluster.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEc4ak8H2cVOgZCQB6:-NWNRXLJBt2HwyX_sPjp:b-m31qo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L287)):*
> Perhaps a better direction would be to have a structured way for a test to say if it supports local execution or not (instead of every test doing their own checks during test runtime).

Right. This could be analogous to specifying a compatible cluster architecture. I will tighten the TODO comment.
___
*[`pkg/cmd/roachtest/cluster.go` line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEcXiD11vCwHmVb4nC:-NWNRivQ7FuKr5Xk1_og:bb6t9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L293)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I don't understand this comment -- what's a metamorphic local cluster?
</blockquote></details>

Yeah, it's ambiguous in this context. The "metamorphic" part is the CPU architecture. One could actually run either AMD64 or ARM64 in a local cluster. I did this on my M with all the currently supported tests (via roachtest local). Granted, it's probably a rarely used option, we get more coverage this way. I'll disambiguate the comment.
___
*[`pkg/cmd/roachtest/cluster.go` line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI77_s3GpyF2y12Vyj:-NWNSQNr3aFh5OtyHgXh:b9m6uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L302)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

The `DFefault` part is confusing to me -- it takes into account the `userSpecified` parameter, which is not "default". Maybe... `resolveBinaryPath` or something along those lines?
</blockquote></details>

Agreed, I like the suggested replacement; will use that or see if any better refactoring is possible. I admit both the name and the hepler function bothered me.
___
*[`pkg/cmd/roachtest/cluster.go` line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI6FGZ9UQ2BxlORpX9:-NWNSiKUBMz-IL5B4ORV:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L309)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Arguably more readable as

```go
err := errors.Newf("ERROR: unable to find required binary %q for %q: %s\n", binName, arch, err)
if isRequired {
    fmt.Fprintf(os.Stderr, "%v", err)
    os.Exit(1)
}
return err
```
</blockquote></details>

Yep.
___
*[`pkg/cmd/roachtest/cluster.go` line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI2GmoAXDZ6iOFDouq:-NWNTD8hEEs3DFk_4qUH:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L324)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Same comment as above about rearranging the error logic.


We could also improve the error message here for the `err != nil` scenario.
</blockquote></details>

Yep.
___
*[`pkg/cmd/roachtest/cluster.go` line 382 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI8_XV9_5pESLThViv:-NWNTHc32QIhInDPkFkb:b-w6g7qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L382)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: is the extra `\n` intentional?
</blockquote></details>

Just for formatting's sake, so it looks like this,

```
Locating and verifying binaries for os="linux", arch="amd64"
WARN: unable to find "cockroach-short" for "amd64": binary or library "cockroach-short" not found (or was not executable)
Locating and verifying binaries for os="linux", arch="arm64"
WARN: unable to find "cockroach-short" for "arm64": binary or library "cockroach-short" not found (or was not executable)
Locating and verifying binaries for os="linux", arch="fips"
WARN: unable to find "cockroach-short" for "fips": binary or library "cockroach-short" not found (or was not executable)
WARN: unable to find library libgeos, ignoring: binary or library "libgeos" not found (or was not executable)
WARN: unable to find library libgeos_c, ignoring: binary or library "libgeos_c" not found (or was not executable)

Found the following binaries:
        cockroach "amd64" at: /home/srosenberg/go/src/github.com/cockroachdb/cockroach/artifacts/cockroach.linux-gnu-amd64
        cockroach "arm64" at: /home/srosenberg/go/src/github.com/cockroachdb/cockroach/artifacts/cockroach.linux-arm64
        cockroach "fips" at: /home/srosenberg/go/src/github.com/co [...]

2023-05-30 04:05 UTC, srosenberg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rail, @renatolabs, and @smg260)

___
*[`pkg/build/info.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEXl41Appuo6MZQ8Of:-NWekrXpDJ6dkIdeZRS9:bkumaz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/build/info.go#L174)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Is this part of this PR? I don't see how it's related.
</blockquote></details>

We now validate if the requested `cockroach-short` was indeed compiled with runtime assertions (i.e., crdb_test build tag).
___
*[`pkg/cmd/roachtest/cluster.go` line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEYWwuCIVzShJpgLCd:-NWel38T9UY1KAOG78DF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L87)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Might be worth being more specific in terms of behavior of test spec + this parameter.

(I know there's more info in the commit, but comments are more accessible than git blame, especially when you need to traverse the ancestry).
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWE_HMY4XJ-X_B8_Sqa:-NWel5ppCJOMxT3mlLa2:b-of6o09) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L133)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Thanks for the pointer; I'll check it out. However, I'll probably keep as is since this code is not on any critical path; but in case, the ELF api is easy to use, I'll replace.
</blockquote></details>

I looked at the debug/elf and debug/macho. In case of macho, there are actually two cases to handle, `macho.NewFile` and `macho.NewFatFile`; the latter is a "universal binary", typically used by libs and binaries (e.g., /usr/lib/wc) which embed multiple (compiled) cpu architectures. (Nice write up about this format [1].) In summary, that's three cases to handle, namely 1 elf and 2 macho. It doesn't seem worth the effort, considering `file` already encodes this logic and much more.

[1] https://www.jviotti.com/2021/07/23/a-deep-dive-on-macos-universal-binaries.html
___
*[`pkg/cmd/roachtest/cluster.go` line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEa4VMCVlDXCiKhmUj:-NWemIor2ynA6yfZvzDe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L198)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Agreed. The whole business of "finding" binaries and libraries seems more complicated than it needs to be; will add a comment.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEaNKMAPMOnkoRi_da:-NWemL0E6V04pPSklee7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L231)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Yep, I tried not to change _everything_ in an effort to reduce the changes in this PR, but I now see your point; will simplify.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEc4ak8H2cVOgZCQB6:-NWemNI9EWsxjU7_4UYA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L287)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

> Perhaps a better direction would be to have a structured way for a test to say if it supports local execution or not (instead of every test doing their own checks during test runtime).

Right. This could be analogous to specifying a compatible cluster architecture. I will tighten the TODO comment.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWEcXiD11vCwHmVb4nC:-NWemOkZCEzcHXTeI-Zu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4f993552c62e64b82c086b09686852feac6650b/pkg/cmd/roachtest/cluster.go#L293)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Yeah, it's ambiguous in this context. The "metamorphic" part is the CPU architecture. One could actually run either AMD64 or ARM64 in a local cluster. I did this on my M with all the currently supported tests (via roachtest local). Granted, it's probably a rarely used option, we get more coverage this way. I'll disambiguate the comment.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI77_s3GpyF2y12Vyj:-NWemPw--thuqsc0JKBX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L302)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Agreed, I like the suggested replacement; will use that or see if any better refactoring is possible. I admit both the name and the hepler function bothered me.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 309 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI6FGZ9UQ2BxlORpX9:-NWemQx76iW9xAE6N8fd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L309)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Yep.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/cluster.go` line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWI2GmoAXDZ6iOFDouq:-NWemRrkDJYU5zGombPV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/cluster.go#L324)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Yep.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/main.go` line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIAtr2CNuWgo46d1UA:-NWemU9g-8m9fTpyHIdI:btl81eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/main.go#L162)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

No, since conditional probability of `0`, i.e., `P(fips | amd64)` is still `0`.
</blockquote></details>

Ignore the above, I misread your comment. The reason the right conjunct is redundant is because `amd64Probability > 0` is implied by the above check. I added a comment to clarify it.
___
*[`pkg/cmd/roachtest/main.go` line 195 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIDk3E3OXhO-k3_-Gx:-NWemhDf9OVlFvcbq-2x:bkx33nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/main.go#L195)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Open to other suggestions... I have to admit that making it `conditional` may not be the most intuitive option; I certainly had to pause a few times; will give it another thought to see if we can simplify.
</blockquote></details>

Sticking with the _conditional_ probability. In essence, you hav [...]

2023-05-31 13:45 UTC, rail reviewed
> Reviewed 3 of 21 files at r1, 9 of 24 files at r2, 31 of 37 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachprod/flags.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWm0Eyv06fB2LyW7DnS:-NWm0Eyv06fB2LyW7DnT:b5g03c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a25050ce9c62d9c755264e502d2612dccd5e7da7/pkg/cmd/roachprod/flags.go#L112)):*
> ```Go
> 		"geo", false, "Create geo-distributed cluster")
> 	createCmd.Flags().StringVar(&createVMOpts.Arch, "arch", "",
> 		"architecture override for VM [amd64, arm64, fips]; N.B. fips implies amd64 with openssl")
> ```

Ideally `fips` would be something like `variant` or `tolachain-variant`, but let's not overengineer this for now. Sometimes it's safer to have the variant included in the arch, so we don't miss it when comparing arches. 


<!-- Sent from Reviewable.io -->

2023-05-31 15:56 UTC, smg260 requested changes
Just minor comments. phew..

> Reviewed 3 of 21 files at r1, 9 of 24 files at r2, 1 of 3 files at r4, 35 of 37 files at r5, 4 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-:-NWmWRzL8aU9LEyQyiCl:bar2y6i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachprod/flags.go` line 263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWmDEmo57pcJshqo1-v:-NWmDEmo57pcJshqo1-w:backdef) ([raw file](https://github.com/cockroachdb/cockroach/blob/a25050ce9c62d9c755264e502d2612dccd5e7da7/pkg/cmd/roachprod/flags.go#L263)):*
> ```Go
> 		"grafana-config", "", "URI to grafana json config, supports local and http(s) schemes")
> 
> 	grafanaStartCmd.Flags().StringVar(&grafanaArch, "arch", "",
> ```

Probably obvious, but why can't this just use the vm arch?
___
*[`pkg/cmd/roachtest/cluster.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWmMz19ENCjYlquiPpP:-NWmMz1AActDg6IQQGdw:bo37yqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/32261e284f36dd59948f7d62d584f532554640af/pkg/cmd/roachtest/cluster.go#L143)):*
> ```Go
> 	fileFormat := strings.ToLower(out.String())
> 	if arch == vm.ArchARM64 {
> 		if !strings.Contains(fileFormat, "arm64") &&
> ```

nit: here, an additional  nested `if` is used, instead adding the condition to the first `if`, whereas below for `ArchAMD64`, the converse is used; a large single 

IMO the go way might be the larger predicate, and eliminate the nested if - with a side effect being that both branches will always return an error, and `else` is not necessary.

Also, each of the `string.Contains` are also done inconsistently though achieving the same thing (!contains && !contains) vs !(contains || contains)

So maybe something like:
```
if arch == vm.ArchARM64 && !string.Contains(..) && !string.Contains (..) { 
  return "", err 
}

if arch == vm.ArchAMD64 && !string.Contains(..) && !string.Contains (..) { 
  return "", err
}

```
___
*[`pkg/cmd/roachtest/test_runner.go` line 633 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIIH8Y3z5lOzkXbWLH:-NWmSapU95MLxnCxLfvI:b1a0lmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/test_runner.go#L633)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Then, it's kinda ambiguous as to where `arch` came from. How about dropping the brackets but in the former case, saying `Using metamorphic...`?
</blockquote></details>

The messaging is fine, but just remove the parentheses (which is what I think Renato meant): 
e.g. `Using specified arch=%q for %s`

or more test-centric (but would need to be consistent across the `test_runner` logging:

`%s: using specified arch=%q, specName, arch)`
`%s: using metamorphically selected arch=%q`, specName, arch)`


<!-- Sent from Reviewable.io -->

2023-05-31 18:54 UTC, srosenberg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachprod/flags.go` line 112 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWm0Eyv06fB2LyW7DnS:-NWn33dGAjmjFEKcvFDy:b-jdkw28) ([raw file](https://github.com/cockroachdb/cockroach/blob/a25050ce9c62d9c755264e502d2612dccd5e7da7/pkg/cmd/roachprod/flags.go#L112)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Ideally `fips` would be something like `variant` or `tolachain-variant`, but let's not overengineer this for now. Sometimes it's safer to have the variant included in the arch, so we don't miss it when comparing arches. 
</blockquote></details>

Yep, as I noted in the previous PR, it's a leaky abstraction [1], but it simplified the scope of changes in roachprod and roachtest. To be revisited if/when a new architecture is added :)

[1] https://github.com/cockroachdb/cockroach/pull/103243#issuecomment-1553956725
___
*[`pkg/cmd/roachprod/flags.go` line 263 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWmDEmo57pcJshqo1-v:-NWn3lKGDey0hBVEf_MO:b-u9e6nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a25050ce9c62d9c755264e502d2612dccd5e7da7/pkg/cmd/roachprod/flags.go#L263)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Probably obvious, but why can't this just use the vm arch?
</blockquote></details>

Primarily because arch isn't exposed in the existing vm metadata. This is only partially true since clouds do report `cpuPlatform`, we just don't parse it as of yet. The second reason is to leave it loosely specified so that we could in theory have mixed-architecture clusters, e.g., nodes running amd64 and arm64. In that case, it's not immediately clear which binaries to pull for prom/grafana unless it's always running on the last node (as is the current default in roachprod). I'll capture these (and related) notes into a follow-up issue. For now, we require providing an explicit `--arch` with roachprod whereas roachtest passes cluster's arch.
___
*[`pkg/cmd/roachtest/cluster.go` line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWmMz19ENCjYlquiPpP:-NWn7q3c3BsNQcEWfESW:b-tmw0tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/32261e284f36dd59948f7d62d584f532554640af/pkg/cmd/roachtest/cluster.go#L143)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

nit: here, an additional  nested `if` is used, instead adding the condition to the first `if`, whereas below for `ArchAMD64`, the converse is used; a large single 

IMO the go way might be the larger predicate, and eliminate the nested if - with a side effect being that both branches will always return an error, and `else` is not necessary.

Also, each of the `string.Contains` are also done inconsistently though achieving the same thing (!contains && !contains) vs !(contains || contains)

So maybe something like:
```
if arch == vm.ArchARM64 && !string.Contains(..) && !string.Contains (..) { 
  return "", err 
}

if arch == vm.ArchAMD64 && !string.Contains(..) && !string.Contains (..) { 
  return "", err
}

```
</blockquote></details>

Good point, I'll simplify. 
___
*[`pkg/cmd/roachtest/test_runner.go` line 633 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWIIH8Y3z5lOzkXbWLH:-NWn8Q0lBjI7GPwiMGhC:b-qhdxnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/880c55cd906a3c86cb3b86d5d12fa8e47eef337a/pkg/cmd/roachtest/test_runner.go#L633)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

The messaging is fine, but just remove the parentheses (which is what I think Renato meant): 
e.g. `Using specified arch=%q for %s`

or more test-centric (but would need to be consistent across the `test_runner` logging:

`%s: using specified arch=%q, specName, arch)`
`%s: using metamorphically selected arch=%q`, specName, arch)`
</blockquote></details>

The reason parentheses are there is because of ambiguity. E.g., if arm64Probability is 1, then the choice is no longer random. Similarly, if the cluster is reused, then we are no longer using the specification of a given test, necessarily. In any case, I'll remove the parens since they seem to be misleading.


<!-- Sent from Reviewable.io -->

2023-06-01 14:24 UTC, smg260 approved these changes

2023-06-01 16:47 UTC, herkolategan approved these changes
Excellent! Definitely a larger change than expected.

> Reviewed 3 of 21 files at r1, 9 of 24 files at r2, 29 of 37 files at r5, 7 of 9 files at r6, 4 of 4 files at r7, 34 of 34 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-:-NWrqYED3tr4f3sLctFU:b-qb6now)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail, @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 309 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/103710#-NWrmp896QUCM3g2ae_p:-NWrmp896QUCM3g2ae_q:b-4hpu2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a27e4eb0f084147919207ce2bb58006a4a649207/pkg/cmd/roachtest/cluster.go#L309)):*
> ```Go
> 	// This could be revisited after we have a way to specify which clouds a given test supports,
> 	//	see https://github.com/cockroachdb/cockroach/issues/104029.
> 	defaultOsName := "linux"
> ```

Nit: `defaultOSName`


<!-- Sent from Reviewable.io -->

2023-06-02 20:58 UTC, srosenberg commented
TFTR! I am going to merge while still doing further testing. With the new metamorphic defaults (both `0`), there should be no change in behavior in the nightly runs. A subsequent PR will enable them in CI.

bors r=smg260,herkolategan

2023-06-02 21:44 UTC, merged