builtins: implement armor/dearmor pgcrypto functions
cockroachdb/cockroach pull request #103723
Opened 2023-05-22 15:50 UTC by andyyang890

Informs #21001

Release note (sql change): The `armor` and `dearmor` functions
from `pgcrypto` are now implemented.

2023-05-22 15:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103723)
<!-- Reviewable:end -->

2023-05-22 15:50 UTC, andyyang890 commented
Depends on #103720

2023-05-23 15:28 UTC, knz requested changes
let's pause this until we make progress on this convo https://github.com/cockroachdb/cockroach/pull/103720#pullrequestreview-1439977045

2023-06-01 14:55 UTC, rafiss commented
We've decided to deprioritize work on PGP related functions for now.

2023-06-24 03:27 UTC, closed without merging