xform: fix incorrect computed colummn predicate derivation
cockroachdb/cockroach pull request #103818
Opened 2023-05-24 05:42 UTC by msirek

This fixes a regression in #100242 where predicates derived on         
computed columns could cause incorrect results.                               

For example, given the table
```sql
CREATE TABLE t103755 (
        a INT NOT NULL,
        b INT NOT NULL,
        c INT NOT NULL AS (a+1) VIRTUAL,
        d INT,
        CONSTRAINT pkey PRIMARY KEY (c ASC, a ASC));
```
The query `SELECT * FROM t103755 WHERE a IN (VALUES(4)) OR a < 0` could
derive predicates `c=5 AND a=4` when it is incorrect to do so.

The problem is that the OR condition is not properly identified, and    
instead of quitting the derivation, we continue to the next span and/or 
constraint and process more terms. The `continue` is needed for cases 
such as:
    `SELECT * FROM t103755 WHERE (a,b) IN ((3,4), (5,6)) AND a > 4`     
where the ANDed inequality `a > 4` exists as a single-span single
`constraint.Set`, where it's desirable to ignore the inequality and not
give up on deriving terms.

This fix corrects the conditional statement identifying a single ANDed  
inequality by bailing out of predicate derivation only if the term has       
more that one span or more than one constraint in the `constraint.Set`.
    
Fixes #103755

Release note (bug fix): This fixes an incorrect results bug where 
predicates on computed columns are derived when an ORed predicate              
on a column in the computed column expression is present. This bug 
only affects releases where session setting
`optimizer_use_improved_computed_column_filters_derivation` is true.
CRDB v23.2 is the only release where this setting is true by default.

2023-05-24 05:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/103818)
<!-- Reviewable:end -->

2023-05-24 14:28 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD6ea118eh0pebWtJs:-NWD6ea118eh0pebWtJt:bmwo4vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L383)):*
> ```Go
> 		}
> 		// Handle only tight constraint sets for now, which is the IN list case.
> 		// TODO(msirek): Handle OR'ed terms. These may be split across multiple
> ```

This TODO should be deleted now, right?
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWD-fX5BEJO4rgpiaKe:bjrim9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
> ```Go
> 			}
> 
> 			for k := 0; k < cons.Spans.Count(); k++ {
> ```

The triple-nested for-loops are making this code complex and hard to reason about. I suggest we take a step back and re-work this approach a bit simplify it and gain more confidence in its correctness. Some ideas (in order of my preference):

1. Did you consider modifying [`idxConstraintCtx.makeSpansForTupleIn`](https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/idxconstraint/index_constraints.go#L535) in the index constraint builder to handle this computed column case, instead of synthesizing new filters from constraints? It looks like it wouldn't be trivial, but it might be simpler than synthesizing filters like this - hard to say for sure until we try it. Other benefits would be that we're not synthesizing filters that aren't likely to lead to faster plans, and the changes could be thoroughly tested with the existing `idxconstraint` unit tests.

2. If we want to continue with synthesizing filters, we should consider building them only when there is the potential of them leading to a better plan - that is, when a computed column expression references the constrained columns. As a rough example, something like:

```
for each computed column:
    for each filter:
        if filter.Constraints.HasMultiColumnConstValues(cols referenced in computed column expression) {
            constValues := filter.Constraints.ExtractMultiColumnConstValues()
            // Use the constant values to calculate computed column value
            // Build new filters
```

Extracting the constant values is one of the tricky parts and separating it out logically allows it to be unit tested. HasMultiColumnConstValues and ExtractMultiColumnConstValues would be similar to HasSingleColumnNonNullConstValues and ExtractSingleColumnNonNullConstValues, but much more complexity - which is why I think option (1) might be preferable.

3. Regardless of (1) or (2), we should have more unit tests for this tricky code. I suggest writing some new data-driven tests so we can directly test a wide variety of input filters and computed column expressions (see my suggestion here: https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC). Exploration tests with `opt` don't provide the best coverage over this code because they don't make the input obvious (the normalized filters and computed columns), and they don't show the output (the synthesized filters).
___
*[`pkg/sql/opt/xform/general_funcs.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD6oq95l0ATI5Bri90:-NWD6oq95l0ATI5Bri91:bkr7wjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L413)):*
> ```Go
> 					// deriving predicates.
> 					if props.Constraints.Length() == 1 && cons.Spans.Count() == 1 {
> 						continue
> ```

I think `break` is equivalent here and is easier to understand then `continue`, because there won't be further iterations of this loop.

Is is safe to break and continue with the loop over the constraints? I think we might need to break out to the next iteration of the outer-most loop, the filters loop. Can you come up with a test case where this might be a problem?


<!-- Sent from Reviewable.io -->

2023-06-01 05:38 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWDWOqd2sOBunDeUATj):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

v23.2 is not released so we shouldn't say this.
</blockquote></details>

Removed this and referenced v23.1 and v22.2 releases in the note.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD6ea118eh0pebWtJs:-NWh0EiKB2PaUl94uRJP:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L383)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This TODO should be deleted now, right?
</blockquote></details>

Done
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWh0H1G75Oy0YFxX4dB:bvjf1vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The triple-nested for-loops are making this code complex and hard to reason about. I suggest we take a step back and re-work this approach a bit simplify it and gain more confidence in its correctness. Some ideas (in order of my preference):

1. Did you consider modifying [`idxConstraintCtx.makeSpansForTupleIn`](https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/idxconstraint/index_constraints.go#L535) in the index constraint builder to handle this computed column case, instead of synthesizing new filters from constraints? It looks like it wouldn't be trivial, but it might be simpler than synthesizing filters like this - hard to say for sure until we try it. Other benefits would be that we're not synthesizing filters that aren't likely to lead to faster plans, and the changes could be thoroughly tested with the existing `idxconstraint` unit tests.

2. If we want to continue with synthesizing filters, we should consider building them only when there is the potential of them leading to a better plan - that is, when a computed column expression references the constrained columns. As a rough example, something like:

```
for each computed column:
    for each filter:
        if filter.Constraints.HasMultiColumnConstValues(cols referenced in computed column expression) {
            constValues := filter.Constraints.ExtractMultiColumnConstValues()
            // Use the constant values to calculate computed column value
            // Build new filters
```

Extracting the constant values is one of the tricky parts and separating it out logically allows it to be unit tested. HasMultiColumnConstValues and ExtractMultiColumnConstValues would be similar to HasSingleColumnNonNullConstValues and ExtractSingleColumnNonNullConstValues, but much more complexity - which is why I think option (1) might be preferable.

3. Regardless of (1) or (2), we should have more unit tests for this tricky code. I suggest writing some new data-driven tests so we can directly test a wide variety of input filters and computed column expressions (see my suggestion here: https://reviewable.io/reviews/cockroachdb/cockroach/100242#-NRseKq6CLUVnilIbCiC). Exploration tests with `opt` don't provide the best coverage over this code because they don't make the input obvious (the normalized filters and computed columns), and they don't show the output (the synthesized filters).
</blockquote></details>

Thanks. I agree, and it makes sense to handle the logic in `indexConstraintCtx` code since other predicates such as `(a=1 AND b=1) OR (a=2 AND b=2)` aren't marked as `TightConstraints`, but could be further analyzed by makeSpansForExpr to be 'tight'. I looked into `makeSpansForTupleIn`, and modifying that code would require special purpose analysis of IN expressions, and we'd need different logic to handle cases such as `(a=1 AND b=1) OR (a=2 AND b=2)`, so couldn't be reused. I found that `constraintsBuilder.buildConstraintForTupleIn` can build a single tight constraint for an IN expression if the constraint building code is taught to bypass the code which adds a constraint on each column in the tuple individually:
https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/memo/constraint_builder.go#L329-L334
I've added a parameter to control whether those extra constraints are built.

`CombineComputedColFilters` has been simplified to contain a single loop over spans and to process only a single constraint. It and some supporting functions had to be moved from `xform` to `norm` to avoid cyclic dependencies.

Regarding writing a`HasMultiColumnConstValues`, that has the same function as the call to `span.HasSingleKey` combined with the checking for constant values in `constColsMap`, so might have been needed if another approach were taken, but would be redundant in the current logic.

I've force-pushed the new logic. 
PTAL when you have time.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD6oq95l0ATI5Bri90:-NWpPyYx-utTP1GPFnms:be95ka5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L413)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think `break` is equivalent here and is easier to understand then `continue`, because there won't be further iterations of this loop.

Is is safe to break and continue with the loop over the constraints? I think we might need to break out to the next iteration of the outer-most loop, the filters loop. Can you come up with a test case where this might be a problem?
</blockquote></details>

After the refactoring, the condition is simplified to this:
```go
		if !span.HasSingleKey(f.evalCtx) {
			// If we don't have a single value, or combination of single values
			// to use in folding the computed column expression, don't use this
			// constraint.
			return nil
		}
```


<!-- Sent from Reviewable.io -->

2023-06-01 14:22 UTC, mgartner reviewed
> Reviewed 1 of 3 files at r1, 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrGjgpA4c3n-UEVyeg:-NWrGjgpA4c3n-UEVyeh:b-8g4mi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L634)):*
> ```Go
> 	// Attempt to build a single tight constraint from a scalar expression and use
> 	// it to derive predicates/constraints on computed columns.
> 	if c.computedColSet.Intersects(c.keyCols) {
> ```

nit: Should the check for `c.skipComputedColPredDerivation` be moved here?
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrGSkn6OHoDN3PKqWP:-NWrGSkn6OHoDN3PKqWQ:b-i55kg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L635)):*
> ```Go
> 	// it to derive predicates/constraints on computed columns.
> 	if c.computedColSet.Intersects(c.keyCols) {
> 		switch e.(type) {
> ```

nit: you can simplify this switch and remove the extra type assertion in the `default` case:

```go
	switch t := e.(type) {
	case *memo.FiltersExpr, *memo.FiltersItem, *memo.AndExpr, *memo.OrExpr:
	case opt.ScalarExpr:
		// t is a ScalarExpr here.
	}
```
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 644 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrJ-8QBPnaQuHNE8QU:-NWrJ-8QBPnaQuHNE8QV:b-4awgvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L644)):*
> ```Go
> 			scalar, ok = e.(opt.ScalarExpr)
> 			shouldDeriveComputedColConstraints := !c.skipComputedColPredDerivation &&
> 				c.evalCtx.SessionData().OptimizerUseImprovedComputedColumnFiltersDerivation
> ```

Why does the session setting need to be checked here in addition to `c.skipComputedColPredDerivation`? Isn't that latter based on the former already?
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWrIKntExejtPufPJKW:b-6295xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
> ```Go
> // to use tight constraints from those filters to derive new tight constraints
> // on computed columns present in the index.  If successful, ok=true and a new
> // list of filters with new tight filters at the front, original filters
> ```

It's odd to build up a constraint, and then use that constraint to generate filters. Can we avoid building new filters?

IIUC the main purpose of building the filters is to fold the computed column expression - it seems like it would be simpler to replace the column references in the computed column expression with constant values. During replacement, normalization rules should transform the entire expression into a constant value, if possible. I was originally thinking this could be done in `makeSpansForTupleIn`. It's already extracting constants for non-computed columns, which could replace variables in computed column expressions.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWrF4F_4DdKKpteNpAA:b-4gkbzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
> I looked into `makeSpansForTupleIn`, and modifying that code would require special purpose analysis of IN expressions, and we'd need different logic to handle cases such as `(a=1 AND b=1) OR (a=2 AND b=2)`, so couldn't be reused.

We didn't handle this type of expression before, correct? I'd prefer to be cautious and not introduce new behavior in a backport, if it's possible. Would backing out the improvement into a future PR reduce some of the changes here?


<!-- Sent from Reviewable.io -->

2023-06-01 14:53 UTC, rytaft commented
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWrRYQ6El15Bzw8dQcK:b9ehvxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> I looked into `makeSpansForTupleIn`, and modifying that code would require special purpose analysis of IN expressions, and we'd need different logic to handle cases such as `(a=1 AND b=1) OR (a=2 AND b=2)`, so couldn't be reused.

We didn't handle this type of expression before, correct? I'd prefer to be cautious and not introduce new behavior in a backport, if it's possible. Would backing out the improvement into a future PR reduce some of the changes here?
</blockquote></details>

When moving large chunks of code and making changes, it's helpful for reviewers if you split it into two commits (which you can squash before merging): one commit where you just move code without making any other changes, and another commit where you actually make the changes. 


<!-- Sent from Reviewable.io -->

2023-06-01 14:55 UTC, rytaft commented
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWrS3SB9_jb95ikD_2Q:b-737chx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

When moving large chunks of code and making changes, it's helpful for reviewers if you split it into two commits (which you can squash before merging): one commit where you just move code without making any other changes, and another commit where you actually make the changes. 
</blockquote></details>

(although it looks like Marcus already took a look, so maybe this isn't necessary. Just something to consider for the future)


<!-- Sent from Reviewable.io -->

2023-06-01 15:58 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrGjgpA4c3n-UEVyeg:-NWrQoH--HNqLlIarOqG:bt2k8er) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L634)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should the check for `c.skipComputedColPredDerivation` be moved here?
</blockquote></details>

Done, plus moved checking of c.evalCtx.SessionData().OptimizerUseImprovedComputedColumnFiltersDerivation there as well.
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrGSkn6OHoDN3PKqWP:-NWrRede3o5biYfEmO9V:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L635)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: you can simplify this switch and remove the extra type assertion in the `default` case:

```go
	switch t := e.(type) {
	case *memo.FiltersExpr, *memo.FiltersItem, *memo.AndExpr, *memo.OrExpr:
	case opt.ScalarExpr:
		// t is a ScalarExpr here.
	}
```

</blockquote></details>

Done
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 644 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrJ-8QBPnaQuHNE8QU:-NWrRyEgDp_6dLTSAZB9:b6raa7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L644)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why does the session setting need to be checked here in addition to `c.skipComputedColPredDerivation`? Isn't that latter based on the former already?
</blockquote></details>

`skipComputedColPredDerivation` could either be true or false when the session setting is true.  I've added a comment to the field to clarify its purpose:
```go
	// skipComputedColPredDerivation disables computed column predicate derivation
	// independent of the session setting which also controls this, and is
	// generally used to prevent infinite recursion in makeSpansForExpr when
	// processing derived predicates.
	skipComputedColPredDerivation bool
```
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWrTWA-94H9MtecmhG8:b-1nleyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
> It's odd to build up a constraint, and then use that constraint to generate filters. Can we avoid building new filters?

The parameters of the methods in `indexConstraintCtx` such as `makeSpansForExpr` are set up to process a scalar expression (boolean expression) into a Constraint, so that is the most natural way to build a new index constraint as opposed to trying to manually build it ourselves. We might get some detail wrong.  The AND and OR predicate we build is a precise specification of the constraint we want these functions to build.

> IIUC the main purpose of building the filters is to fold the computed column expression

This is only part of the purpose. Full combined filters including both computed columns and the columns those expressions are based are are required, as mentioned in this comment:
https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/norm/general_funcs.go#L991-L993

In that example if we started with `(a,b) IN ((3,4), (5,6))` we have to specify that we only want to apply derived predicate `c=7` when `a` is 3 and `b` is 4, and only apply `c=11` when `a` is 3 and `b` is 4.  If we were to only build new filter `(c IS 7) OR (c IS 11)` that represents a constraint with spans of:
```
[/7 - /7]
[/11 - /11]
```
and we'd end up will total filters of `(a,b) IN ((3,4), (5,6)) AND ((c IS 7) OR (c IS 11))`  
The `(a,b) IN ((3,4), (5,6))` portion of the filter could not generate any spans and we'd end up with a final set of spans as the above instead of the desired:
```
[/7/3/4 - /7/3/4]
[/11/5/6 - /11/5/6]
```

> I was originally thinking this could be done in `makeSpansForTupleIn`. It's already extracting constants for non-computed columns, which could replace variables in computed column expressions.

`makeSpansForTupleIn` is very specific to multicolumn IN clauses and would only handle those constructs. It would work, but would not help for predicates with arbitrary combinations of AND and OR expressions.  Pushing the logic, as you suggested, into the index constraint builder has made it easy to handle AND and OR expressions by allowing us to only work on the local predicate being processed within the nested ANDs and ORs. That predicate may take any form, for example, `a BETWEEN 3 and 3`. If we had to provide special logic for every type of boolean expression possible to build a new constraint, that would be a big task. Luckily, we already have function `memo.BuildConstraints`, which could be called on that `a BETWEEN 3 and 3` to build a representation of that predicate in a common form, as a`Constraint`, which tells us exactly how many values it's equating column `a` with.  Think of the `Constraint` as a generalized representation of the information we need for building new constraints, but not directly, but by using the pre-existing functions out there which already know how to correctly build every possible constraint based on the input specification of a scalar boolean expression (namely functions `memo.BuildConstraints` and `makeSpansForTupleIn`).

Anyway, maybe we can chat about it in Google Meet if some of the details or motivation for this approach are unclear.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWrbhboEk2kNTftNmum:b-qyb9ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
> We didn't handle this type of expression before, correct? I'd prefer to be cautious and not introduce new behavior in a backport, if it's possible. Would backing out the improvement into a future PR reduce some of the changes here?

The original backport already introduced new behavior.  I suppose it's possible to try to disable some of the new logic in the backport version of the code, like that in `makeSpansForAnd`, but then it's possible the customer we're backporting this for might be using computed column expressions of other forms which wouldn't be supported.  This is already protected behind a session setting so there should be no impact to customers that don't explicitly turn on the session setting.

> When moving large chunks of code and making changes, it's helpful for reviewers if you split it into two commits (which you can squash before merging): one commit where you just move code without making any other changes, and another commit where you actually make the changes.

Thanks. Hopefully the code move isn't too confusing.  It's just one large chunk, and the only real overlap is in `CombineComputedColFilters`.  @mgartner let me know if you'd like me to split the code move into a separate commit (which would have to be the 1st commit, because otherwise it wouldn't compile).


<!-- Sent from Reviewable.io -->

2023-06-01 16:50 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWrrKjw2Rm5Q3F-AC2w:b-9kyldj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> It's odd to build up a constraint, and then use that constraint to generate filters. Can we avoid building new filters?

The parameters of the methods in `indexConstraintCtx` such as `makeSpansForExpr` are set up to process a scalar expression (boolean expression) into a Constraint, so that is the most natural way to build a new index constraint as opposed to trying to manually build it ourselves. We might get some detail wrong.  The AND and OR predicate we build is a precise specification of the constraint we want these functions to build.

> IIUC the main purpose of building the filters is to fold the computed column expression

This is only part of the purpose. Full combined filters including both computed columns and the columns those expressions are based are are required, as mentioned in this comment:
https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/norm/general_funcs.go#L991-L993

In that example if we started with `(a,b) IN ((3,4), (5,6))` we have to specify that we only want to apply derived predicate `c=7` when `a` is 3 and `b` is 4, and only apply `c=11` when `a` is 3 and `b` is 4.  If we were to only build new filter `(c IS 7) OR (c IS 11)` that represents a constraint with spans of:
```
[/7 - /7]
[/11 - /11]
```
and we'd end up will total filters of `(a,b) IN ((3,4), (5,6)) AND ((c IS 7) OR (c IS 11))`  
The `(a,b) IN ((3,4), (5,6))` portion of the filter could not generate any spans and we'd end up with a final set of spans as the above instead of the desired:
```
[/7/3/4 - /7/3/4]
[/11/5/6 - /11/5/6]
```

> I was originally thinking this could be done in `makeSpansForTupleIn`. It's already extracting constants for non-computed columns, which could replace variables in computed column expressions.

`makeSpansForTupleIn` is very specific to multicolumn IN clauses and would only handle those constructs. It would work, but would not help for predicates with arbitrary combinations of AND and OR expressions.  Pushing the logic, as you suggested, into the index constraint builder has made it easy to handle AND and OR expressions by allowing us to only work on the local predicate being processed within the nested ANDs and ORs. That predicate may take any form, for example, `a BETWEEN 3 and 3`. If we had to provide special logic for every type of boolean expression possible to build a new constraint, that would be a big task. Luckily, we already have function `memo.BuildConstraints`, which could be called on that `a BETWEEN 3 and 3` to build a representation of that predicate in a common form, as a`Constraint`, which tells us exactly how many values it's equating column `a` with.  Think of the `Constraint` as a generalized representation of the information we need for building new constraints, but not directly, but by using the pre-existing functions out there which already know how to correctly build every possible constraint based on the input specification of a scalar boolean expression (namely functions `memo.BuildConstraints` and `makeSpansForTupleIn`).

Anyway, maybe we can chat about it in Google Meet if some of the details or motivation for this approach are unclear.
</blockquote></details>

Correction:
`namely functions memo.BuildConstraints and makeSpansForTupleIn`  -->
`namely functions memo.BuildConstraints and makeSpansForExpr`


<!-- Sent from Reviewable.io -->

2023-06-01 20:37 UTC, mgartner commented
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWsfME16RuZ-LHvetXY:bkkxr3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
> The original backport already introduced new behavior.

I'm referring to handling the `OR` expressions. You've removed those TODOs in this PR.


<!-- Sent from Reviewable.io -->

2023-06-01 21:15 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWsgMdw4Yv6PE_oM0mh:b-rlr597) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> The original backport already introduced new behavior.

I'm referring to handling the `OR` expressions. You've removed those TODOs in this PR.
</blockquote></details>

Right.  Excluding the new code in `makeSpansForAnd` would remove handling of `OR` expressions.
What I meant here was that the original backport was already adding support for more expressions (`IN` expressions), so that shows we can backport new behavior, and I think we did so because it is hidden behind a session setting. The same logic applies to backporting new behavior in the form of support for `OR` expressions, except it involves more code. So, if we want to backport less code, we merge the full changes to master and for backport we exclude or disable the code called from `makeSpansForAnd` (function `deriveComputedColumnConstraints`).


<!-- Sent from Reviewable.io -->

2023-06-01 22:14 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWt0V2O9a4OqA29JLGv:b-3g6fpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Right.  Excluding the new code in `makeSpansForAnd` would remove handling of `OR` expressions.
What I meant here was that the original backport was already adding support for more expressions (`IN` expressions), so that shows we can backport new behavior, and I think we did so because it is hidden behind a session setting. The same logic applies to backporting new behavior in the form of support for `OR` expressions, except it involves more code. So, if we want to backport less code, we merge the full changes to master and for backport we exclude or disable the code called from `makeSpansForAnd` (function `deriveComputedColumnConstraints`).
</blockquote></details>

I have separated off the `makeSpansForAnd` code into a separate commit.


<!-- Sent from Reviewable.io -->

2023-06-01 22:58 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWt9dgg9YORmPEBfEjE:b-f0bauo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Correction:
`namely functions memo.BuildConstraints and makeSpansForTupleIn`  -->
`namely functions memo.BuildConstraints and makeSpansForExpr`
</blockquote></details>

Sure, happy to hop on a call tomorrow and discuss some more. I don't think I was communicating my suggestion very clearly, so I through together a very quick and dirty prototype to show the idea: https://github.com/mgartner/cockroach/commit/42cd98e42550d84a20269e2d386843ab06be8e8c
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWt9z8rAKDTBipk8uTY:bl6f3ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
> What I meant here was that the original backport was already adding support for more expressions (`IN` expressions), so that shows we can backport new behavior, and I think we did so because it is hidden behind a session setting.

We should strive to backport as little changes as possible, only what is absolutely necessary, in order to maintain quality. It can take a while for randomized tests or ourselves to catch bugs, so there is value in a "baking" period for changes. In this case we got rather lucky that an external researcher caught it so quickly.


<!-- Sent from Reviewable.io -->

2023-06-02 00:10 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWtOa8Q-iVd6idFDeq1:b-bojub7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Sure, happy to hop on a call tomorrow and discuss some more. I don't think I was communicating my suggestion very clearly, so I through together a very quick and dirty prototype to show the idea: https://github.com/mgartner/cockroach/commit/42cd98e42550d84a20269e2d386843ab06be8e8c
</blockquote></details>

OK, we can discuss it tomorrow.  If we handle the multicolumn IN clause in `makeSpansForTupleIn`, then we'd also have to add support for the single-column IN clause in a different function because that is what the customer's test case had.

For example, your prototype fix does not handle the test case in #100206

The original support issue motivating this is https://github.com/cockroachlabs/support/issues/2196
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWtNQKQ29ir2Y1hA5U-:byguagx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> What I meant here was that the original backport was already adding support for more expressions (`IN` expressions), so that shows we can backport new behavior, and I think we did so because it is hidden behind a session setting.

We should strive to backport as little changes as possible, only what is absolutely necessary, in order to maintain quality. It can take a while for randomized tests or ourselves to catch bugs, so there is value in a "baking" period for changes. In this case we got rather lucky that an external researcher caught it so quickly.
</blockquote></details>

It sounds like you are favoring a totally different fix for backport than the original, more generalized #100242; something which only handles IN expressions and nothing else.


<!-- Sent from Reviewable.io -->

2023-06-02 13:11 UTC, mgartner reviewed
Thanks for breaking it up into two commits. The first commit LGTM, just have some minor nits. Can you move the second commit out of this PR, so we can merge this as-is and review the second commit separately?

In the future it'd be great to (1) avoid having to use the memo's constraint builder in the index constraint builder, and (2) avoid building scalar expressions that are passed back into `makeSpansForExpr`. I think (2) shouldn't be too difficult, but (1) might require some reworking of the index constraint builder. 

> Reviewed 6 of 12 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-:-NWwC5Du1SgCW8v81KeT:b-kobks7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWw6mYaEwzuCJ5p2ou8:b-uxa8qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, we can discuss it tomorrow.  If we handle the multicolumn IN clause in `makeSpansForTupleIn`, then we'd also have to add support for the single-column IN clause in a different function because that is what the customer's test case had.

For example, your prototype fix does not handle the test case in #100206

The original support issue motivating this is https://github.com/cockroachlabs/support/issues/2196
</blockquote></details>

Right, we'd have to update `makeSpansForSingleColumn`, too. 
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 649 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWw9Dll6zQhwc8EVYqG:-NWw9Dlm650DOFbvo_bG:b-tnf1ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/0249776923fe972ffb5c1a129a59de282a57b67f/pkg/sql/opt/idxconstraint/index_constraints.go#L649)):*
> ```Go
> 				// predicates, with additional derived IS conjuncts on computed
> 				// columns based on columns in the constraint spans.
> 				computedColumnFilters := norm.CombineComputedColFilters(
> ```

Can you leave a `TODO(msirek/mgartner)` here for replacing this with some logic that can build the index constraint directly from the single constraint we'e already built. It should be simpler and more efficient than building a scalar expression to pass back to `makeSpansForExpr`, and I think it would remove the need for `skipComputedColPredDerivation` to prevent infinite recursion.
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 1202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWwBQOx9Rcr3OQDVOuC:-NWwBC1n3cXxoIrHDbaa:b-pn13qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0249776923fe972ffb5c1a129a59de282a57b67f/pkg/sql/opt/idxconstraint/index_constraints.go#L1202)):*
> ```Go
> 	computedColSet opt.ColSet
> 
> 	colsInComputedColsExpressions opt.ColSet
> ```

nit: add brief comments to explain what these sets contain.
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWw7OqF36oOqm_ivfC8:b-wq3tyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

It sounds like you are favoring a totally different fix for backport than the original, more generalized #100242; something which only handles IN expressions and nothing else.
</blockquote></details>

I'm mostly hesitant of the additional complexity for edge cases. The optimizer has to be pragmatic in what is optimizes. There's many optimizations it could make, but each adds computational cost and code complexity. There's already many ways to write an expression that will fool the index constraint builder (or the regular constraint builder, or the partial index implicator, etc.) and lead to an non-optimal scan. That's ok, as long as we cover the expressions that are most likely to be in a query. E.g., it's great to handle an expression like `(a, b) IN ((1, 2), (3, 4))`, but we should be skeptical about the need to handle an expression like `(a, b) IN ((1, 2), (3, 4)) AND a > 4` if it requires a lot of complexity.


<!-- Sent from Reviewable.io -->

2023-06-02 14:57 UTC, msirek reviewed
OK, I've moved the 2nd commit out of this PR.

> In the future it'd be great to (1) avoid having to use the memo's constraint builder in the index constraint builder.

OK. I'm just curious what's the reason for the hesitancy is using it.

> (2) avoid building scalar expressions that are passed back into `makeSpansForExpr`. 

Sure, I've created the TODO you requested in the other comment.  

If we really don't like mixing conversions like this, Constraint -> FiltersExpr -> Contraint in the index constraint builder, I'm curious if it would be worthwhile to add a new predicate transformation phase/subsystem in the future, modeled after the index constraint builder, but using the memo constraint builder instead. It could walk the expression tree and build a new representation of ANDed and ORed constraints.  Not only filter derivation could be done there, but maybe other conversions like CNF -> DNF, DNF -> CNF. The different filter forms may trigger index access in more cases, and building filters would allow other transformation rules to possibly get fired from those filters.  Anyway, just something to think about...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-:-NWwYHtECza_O1-EToSA:b4u2xi1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 758 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWrIKntExejtPufPJKV:-NWwX-uKANEDYRbVcS2w:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e623a34b8557bd19ed02bcf06319c8a7eb182b2/pkg/sql/opt/idxconstraint/index_constraints.go#L758)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Right, we'd have to update `makeSpansForSingleColumn`, too. 
</blockquote></details>

ack
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 649 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWw9Dll6zQhwc8EVYqG:-NWwWyz4DVtLKbjUnCQQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0249776923fe972ffb5c1a129a59de282a57b67f/pkg/sql/opt/idxconstraint/index_constraints.go#L649)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you leave a `TODO(msirek/mgartner)` here for replacing this with some logic that can build the index constraint directly from the single constraint we'e already built. It should be simpler and more efficient than building a scalar expression to pass back to `makeSpansForExpr`, and I think it would remove the need for `skipComputedColPredDerivation` to prevent infinite recursion.
</blockquote></details>

Done
___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 1202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWwBQOx9Rcr3OQDVOuC:-NWwYDup9OGKVTQvu5Uj:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0249776923fe972ffb5c1a129a59de282a57b67f/pkg/sql/opt/idxconstraint/index_constraints.go#L1202)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add brief comments to explain what these sets contain.
</blockquote></details>

Done
___
*[`pkg/sql/opt/xform/general_funcs.go` line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWD-fX5BEJO4rgpiaKd:-NWwVQcZ-auODZk9Uya0:b-zfvis2) ([raw file](https://github.com/cockroachdb/cockroach/blob/33ae9ac9fcb216afa5108bdad80e771c865be9a3/pkg/sql/opt/xform/general_funcs.go#L400)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm mostly hesitant of the additional complexity for edge cases. The optimizer has to be pragmatic in what is optimizes. There's many optimizations it could make, but each adds computational cost and code complexity. There's already many ways to write an expression that will fool the index constraint builder (or the regular constraint builder, or the partial index implicator, etc.) and lead to an non-optimal scan. That's ok, as long as we cover the expressions that are most likely to be in a query. E.g., it's great to handle an expression like `(a, b) IN ((1, 2), (3, 4))`, but we should be skeptical about the need to handle an expression like `(a, b) IN ((1, 2), (3, 4)) AND a > 4` if it requires a lot of complexity.
</blockquote></details>

Understood. For that case, `(a, b) IN ((1, 2), (3, 4)) AND a > 4`, it is handled by the first commit.


<!-- Sent from Reviewable.io -->

2023-06-02 15:49 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> OK, I've moved the 2nd commit out of this PR.

Thanks!

> OK. I'm just curious what's the reason for the hesitancy is using it.

AFAICT there's no reason we need to walk the expression tree multiple times and build a constraint just to throw it away. I think there's a simpler and more efficient method possible, but it'd take some elbow grease to refactor the index constraint builder to make it all work. 

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-:-NWwlyq8BU3C5kZkbXuM:b-jtyxhh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)

___
*[`pkg/sql/opt/idxconstraint/index_constraints.go` line 649 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-NWw9Dll6zQhwc8EVYqG:-NWwlbXj1E1IvjpwraY7:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0249776923fe972ffb5c1a129a59de282a57b67f/pkg/sql/opt/idxconstraint/index_constraints.go#L649)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-06-02 16:01 UTC, msirek reviewed
OK. TFTR!
bors r=mgartner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103818#-:-NWwpfNk4Gila9jsewUA:b-n9j6m5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek)



<!-- Sent from Reviewable.io -->

2023-06-02 17:04 UTC, merged