kvserver: add cluster setting to disable queues
cockroachdb/cockroach pull request #104170
Opened 2023-05-31 21:14 UTC by aadityasondhi

This patch introduces a new set of cluster settings to disable work queues in the `Store` object. It makes use of the underlying `disabled` property of the `BaseQueue`.

Fixes: #102031

Release note: None

2023-05-31 21:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/104170)
<!-- Reviewable:end -->

2023-06-01 20:25 UTC, andrewbaptist requested changes
Update the comment in `queue.go` related to the disabled field. It currently says:
`// Some tests in this package disable queues.` 
But now it is also configurable through these new settings.

Also update the `MaybeRemove` method in `queue.go` to check the disabled flag.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-:-NWsaa-iAen7JuTd7KOO:b-qjxq75)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/kv/kvserver/consistency_queue.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-NWsb4YB3NVpm2Tp42tw:-NWsb4YB3NVpm2Tp42tx:b-84ag3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9b6bd7df3ff9220f6313e7fa8edff8f311e94/pkg/kv/kvserver/consistency_queue.go#L109)):*
> ```Go
> 	kvserverbase.ConsistencyQueueEnabled.SetOnChange(&store.cfg.Settings.SV, func(ctx context.Context) {
> 		q.SetDisabled(!kvserverbase.ConsistencyQueueEnabled.Get(&store.cfg.Settings.SV))
> 	})
> ```

nit: I would do this a little differently since this is the exact same code on every queue. Add a parameter - something like `disabledConfig *settings.BoolSetting` to `queueConfig` and then pass in the parameter itself. This will avoid missing it on new queue creations, and it also prevents it from creating a queue and then having to disable it right afterwards.
___
*[`pkg/kv/kvserver/split_queue.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-NWsbutv9A3dtS5SB-pq:-NWsbutv9A3dtS5SB-pr:bmwnbcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9b6bd7df3ff9220f6313e7fa8edff8f311e94/pkg/kv/kvserver/split_queue.go#L183)):*
> ```Go
> }
> 
> func (sq *splitQueue) enabled() bool {
> ```

Remove this redundant setting.


<!-- Sent from Reviewable.io -->

2023-06-06 19:21 UTC, aadityasondhi reviewed
TFTR!

I ended up not adding a `disabled` check to `MaybeRemove` based on this comment:

 https://github.com/cockroachdb/cockroach/blob/24f141b2cffd8325ca2e4504b2dabecb6132b81c/pkg/kv/kvserver/scanner.go#LL251C1-L253C1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-:-NXH8ml-59ZelW5Bnf8j:b-xofd2i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvserver/consistency_queue.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-NWsb4YB3NVpm2Tp42tw:-NXH8hpJ2HhLPiyROklK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9b6bd7df3ff9220f6313e7fa8edff8f311e94/pkg/kv/kvserver/consistency_queue.go#L109)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I would do this a little differently since this is the exact same code on every queue. Add a parameter - something like `disabledConfig *settings.BoolSetting` to `queueConfig` and then pass in the parameter itself. This will avoid missing it on new queue creations, and it also prevents it from creating a queue and then having to disable it right afterwards.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/split_queue.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-NWsbutv9A3dtS5SB-pq:-NXH8lHK2dfliYaVjwK0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9c9b6bd7df3ff9220f6313e7fa8edff8f311e94/pkg/kv/kvserver/split_queue.go#L183)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Remove this redundant setting.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-07 19:13 UTC, andrewbaptist approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for the iteration on this!

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104170#-:-NXMGiNkAmSmyxPMfVgZ:bajkmb7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)



<!-- Sent from Reviewable.io -->

2023-06-07 21:47 UTC, aadityasondhi commented
bors r+

2023-06-07 22:57 UTC, aadityasondhi commented
bors r+

2023-06-07 23:39 UTC, merged