sql: prevent dropped user from accessing the cluster
cockroachdb/cockroach pull request #104215
Opened 2023-06-01 17:03 UTC by rafiss

fixes https://github.com/cockroachdb/cockroach/issues/20718

Release note (bug fix): Previously if a user was logged in while a different session dropped that user, the dropped user would still inherit privileges from the `public` role. Now, CockroachDB checks that the user exists before allowing it to inherit privileges from the `public` role.

In addition, any active web sessions are now revoked when a user is dropped.

2023-06-01 17:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/104215)
<!-- Reviewable:end -->

2023-06-01 23:52 UTC, andyyang890 requested changes
Thanks for fixing this! Just had one minor question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-:-NWtMs8R3obXGwf5Dybz:b-l2mtv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/authorization.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtKuem9UnwMxuVkjeU:-NWtKuem9UnwMxuVkjeV:bi48pxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/authorization.go#L178)):*
> ```Go
> 	// Check if the 'public' pseudo-role has privileges.
> 	if privs.CheckPrivilege(username.PublicRoleName(), privilegeKind) {
> 		// Before returning true, make sure the user actually exists.
> ```

Is there a reason we don't check that the user exists if the public pseudo-role does not have privileges? i.e. why not unnest this check and move it before checking the public pseudo-role?
___
*[`pkg/sql/drop_role.go` line 454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtIAlpBZ3pjt0LFqt0:-NWtIAlpBZ3pjt0LFqt1:bai6bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/drop_role.go#L454)):*
> ```Go
> 		numRoleSettingsRowsDeleted += rowsDeleted
> 
> 		rowsDeleted, err = params.p.InternalSQLTxn().ExecEx(
> ```

The compiler is complaining that this value for `rowsDeleted` isn't being used. Maybe replace it with an underscore?
___
*[`pkg/sql/tests/drop_role_concurrent_session_test.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtMuBF7hfygJ8yi07p:-NWtMiIg1rtsjyfXBAVJ:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/tests/drop_role_concurrent_session_test.go#L31)):*
> ```Go
> // Test that if a user is dropped while a session is active, the session can
> // no longer access objects in the cluster.
> func TestDropRoleConcurrentSession(t *testing.T) {
> ```

Nice test!


<!-- Sent from Reviewable.io -->

2023-06-05 19:12 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/sql/authorization.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtKuem9UnwMxuVkjeU:-NXBwgBK3xC72_IbgMmu:b7dl9b8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/authorization.go#L178)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Is there a reason we don't check that the user exists if the public pseudo-role does not have privileges? i.e. why not unnest this check and move it before checking the public pseudo-role?
</blockquote></details>

my reasoning was that inheriting from `public` is the only way that a dropped user can end up passing this privilege check. if the public role does not have privileges, then the next  check below (`p.checkRolePredicate`) is guaranteed to fail since the dropped user will not be anywhere in the role hierarchy. it's better to avoid the call to RoleExists unless it's needed, since it does cause an extra lookup.

i'll add some comments
___
*[`pkg/sql/drop_role.go` line 454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtIAlpBZ3pjt0LFqt0:-NXByLavDb6SCPcLj7i4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/drop_role.go#L454)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

The compiler is complaining that this value for `rowsDeleted` isn't being used. Maybe replace it with an underscore?
</blockquote></details>

done
___
*[`pkg/sql/tests/drop_role_concurrent_session_test.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-NWtMuBF7hfygJ8yi07p:-NXByNhF9bZRlLO2tKFb:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce3a4599281f369e30bba7f00ba59860cec5ecb5/pkg/sql/tests/drop_role_concurrent_session_test.go#L31)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

thanks!


<!-- Sent from Reviewable.io -->

2023-06-06 05:49 UTC, andyyang890 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104215#-:-NXEFB4o1XFcwK1b7d2P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-06-07 18:57 UTC, rafiss commented
tftr!

bors r+

2023-06-07 19:29 UTC, merged