server: make SpanStats authoritative
cockroachdb/cockroach pull request #104423
Opened 2023-06-06 17:47 UTC by zachlite

This commit guarantees that SpanStats uses up-to-date range
descriptors on all nodes. The dependency on DistSender is removed
and is replaced with a dependency on rangedesc.Scanner.

rangedesc.Scanner is used to:
1) Locate nodes that house replicas of a span to avoid cluster-wide fan-outs.
2) Find Range Descriptors that touch a span, to build a SpanStatsResponse.

This commit also fixes https://github.com/cockroachdb/cockroach/issues/103809, where a SpanStatsResponse incorrectly returned
the replica_count for a span, instead of the range_count.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-24928
Issue: https://github.com/cockroachdb/cockroach/issues/103957
Release note (bug fix): SpanStats is no longer subject to stale
information, and should be considered authoritative.

2023-06-06 17:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/104423)
<!-- Reviewable:end -->

2023-06-07 15:04 UTC, knz approved these changes
Great work. Thanks for this change. Don't forget to update the test expectation in TestAdminAPITableStats.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104423#-:-NXLNcHO9UE8mJDpoYk8:b-l34d4s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104423#-NXLMQU80IFIRRAerHTy):*
tip: add a blank line after the colon and in-between the two list items to fix the markdown formatting.  (You can also upgrade the PR description after that)


<!-- Sent from Reviewable.io -->

2023-06-15 18:03 UTC, arulajmani requested changes
> Reviewed 1 of 5 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @zachlite)

___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104423#-NY-BOvn5LNHyBBasjWW):*
To confirm, this only runs on the system tenant, right? 

If not, we might need to use a `rangedesc.Iterator` instead, much like `crdb_internal.ranges_no_leases` does.


<!-- Sent from Reviewable.io -->

2023-06-15 18:04 UTC, arulajmani approved these changes
Didn't mean to publish just yet. Change looks good, just a question in-line. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104423#-:-NY-DZGrE0dLoRM3Cv0w:b-70htae)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @zachlite)



<!-- Sent from Reviewable.io -->

2023-06-15 18:15 UTC, zachlite reviewed
Yep, span stats are fulfilled by the system tenant (KV nodes). Other tenant requests for span stats are forwarded through tenantConnect.

TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104423#-:-NY-G5VJ2nawmXXp3R9c:b9zwlmw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)



<!-- Sent from Reviewable.io -->

2023-06-15 19:15 UTC, merged