dev,generate-cgo: externalize cgo files gen into a seperate binary
cockroachdb/cockroach pull request #104554
Opened 2023-06-07 21:24 UTC by healthy-pod

Previously, we only needed to gen cgo files using `dev` so that was were that logic lived. Now, we need to gen cgo files outside dev to fix an issue with gcassert [see #65485].

This code change externalizes the code into a separate binary and let's `dev gen cgo` point to it.

Release note: None
Epic: None

Informs #65485

2023-06-07 21:33 UTC, rickystewart approved these changes

2023-06-07 21:33 UTC, rickystewart commented on pkg/cmd/generate-cgo/main.go
> +	args := []string{"info", "execution_root", "--color=no"}
Doesn't really make much sense that `workspace` and `bazel-bin` have to be passed in, but `execution_root` does not. I would say just have `generate-cgo` look all of them up by itself.

2023-06-07 21:36 UTC, rickystewart requested changes

2023-06-07 21:36 UTC, rickystewart commented on pkg/cmd/dev/generate.go
> +		"//pkg/cmd/generate-cgo:generate-cgo",
Should add:

```
"--run_under=cd [workspace] && ",
```

Or something like this to make sure the binary is executed in the workspace directory.

2023-06-07 22:02 UTC, rickystewart approved these changes

2023-06-07 22:44 UTC, healthy-pod commented
bors r=rickystewart

2023-06-07 23:06 UTC, healthy-pod commented
bors retry

2023-06-08 00:42 UTC, healthy-pod commented
bors retry

2023-06-08 00:43 UTC, healthy-pod commented
bors r-

2023-06-08 00:43 UTC, healthy-pod commented
bors r+ single-on

2023-06-08 00:43 UTC, healthy-pod commented
bors r-

2023-06-08 00:44 UTC, healthy-pod commented
bors single on

2023-06-08 00:45 UTC, healthy-pod commented
bors r+ single on

2023-06-08 03:47 UTC, healthy-pod commented
bors r+ single on

2023-06-08 04:15 UTC, merged