optbuilder: fix internal error in project set with column expressions
cockroachdb/cockroach pull request #104756
Opened 2023-06-13 00:20 UTC by msirek

This fixes rare internal errors in queries which are evaluated using project set operations involving simple column expressions.

In the optbuilder, `buildZip` calls `buildScalar` on an input expression and uses the resulting scalar expression as the input to a zip item. When the `outScope` argument to `buildScalar` is non-nil, that's interpreted as a projection operation, and if the passed-in `scalar` expression is a `scopeColumn`, it's treated as a passthrough column and no output scalar expression is built for it.

The solution taken is similar to that of `optbuilder.Builder.buildAggArg`, and `ConstructVariable` is called to manually build the scalar expression representing the column reference.

Epic: none
Fixes: #95315

Release note (bug fix): This patch fixes rare internal errors which occur when a query uses a "project set" operation involving simple column expressions.

2023-06-13 00:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/104756)
<!-- Reviewable:end -->

2023-06-13 14:09 UTC, rytaft reviewed
Nice find!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NXp4hNa0Kd1rE5QwDfD:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp2e3fChXNcZlcAPeH:-NXp2e3gALC0KOFGCYER:blkq68z) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/logictest/testdata/logic_test/join#L1157)):*
> ```
> 
> statement ok
> CREATE TABLE t95315 (c1 INT, c2 FLOAT);
> ```

would help to add a comment saying that this is a regression test for issue #95315 
___
*[`pkg/sql/opt/exec/execbuilder/testdata/join` line 2238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp2ne02XTD-Ik1jc37:-NXp2ne02XTD-Ik1jc38:blkq68z) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/exec/execbuilder/testdata/join#L2238)):*
> ```
> 
> statement ok
> CREATE TABLE t95315 (c1 INT, c2 FLOAT);
> ```

would help to add a comment saying that this is a regression test for issue #95315 


<!-- Sent from Reviewable.io -->

2023-06-13 15:10 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXp7z5d7CLMW1bp1_1s:bw2tqym) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
> ```Go
> 
> 			// Update the output column to refer to the new column ID.
> 			outScope.cols[len(outScope.cols)-1].id = newColID
> ```

If `buildScalar` incorrectly thinks that a column can be passed-through, rather than projected, it's because that column is part of the `inScope` passed to `buildScalar`. So I think we're passing the wrong scope to `buildScalar`. I think we should be passing `inScope.replace()` (or maybe `inScope.push()`). I tried both quickly and they both broke another test, so there's something wonky to iron out there.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/join` line 2244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7lAYAyUTwTyUi48Q:-NXp7lAYAyUTwTyUi48R:bbeld5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/exec/execbuilder/testdata/join#L2244)):*
> ```
> query T
> EXPLAIN(VERBOSE) SELECT 1,c1,c2 FROM t95315 JOIN
>         ROWS FROM (CAST(c1 AS INT), CAST(c2 AS INT)) USING (c1, c2);
> ```

Given this bug is in optbuilder, I think it makes more sense to move this test to an optbuiler test where we can see column IDs and the optimizer plan in [pkg/sql/optbuilder/testdata/srfs](https://github.com/cockroachdb/cockroach/blob/ff87db04dd4e167b2a8a618dca8a16e5eb173c8f/pkg/sql/opt/optbuilder/testdata/srfs). 


<!-- Sent from Reviewable.io -->

2023-06-13 15:32 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXpMsN-0qJDat60o_tb:b-tiwtjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If `buildScalar` incorrectly thinks that a column can be passed-through, rather than projected, it's because that column is part of the `inScope` passed to `buildScalar`. So I think we're passing the wrong scope to `buildScalar`. I think we should be passing `inScope.replace()` (or maybe `inScope.push()`). I tried both quickly and they both broke another test, so there's something wonky to iron out there.
</blockquote></details>

Well, the expression is starting out as a CAST expression, then within `buildZip` when we resolve the type, the CAST is elided, so it is converted into a simple column expression.  Maybe type checking needs to be done earlier so that we can see before inScope is built that the final expression is a `scopeColumn`?
___
*[`pkg/sql/logictest/testdata/logic_test/join` line 1157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp2e3fChXNcZlcAPeH:-NXpMcXH6_cvXRdE4Wrl:b-f4m8jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/logictest/testdata/logic_test/join#L1157)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would help to add a comment saying that this is a regression test for issue #95315 
</blockquote></details>

Done, and also moved this to the srfs test.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/join` line 2238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp2ne02XTD-Ik1jc37:-NXpNTKUBHGAMc54JMAl:bhn39ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/exec/execbuilder/testdata/join#L2238)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would help to add a comment saying that this is a regression test for issue #95315 
</blockquote></details>

Done, and moved this test to optbuilder.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/join` line 2244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7lAYAyUTwTyUi48Q:-NXpMaea1xOc3mgUtbi2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/exec/execbuilder/testdata/join#L2244)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Given this bug is in optbuilder, I think it makes more sense to move this test to an optbuiler test where we can see column IDs and the optimizer plan in [pkg/sql/optbuilder/testdata/srfs](https://github.com/cockroachdb/cockroach/blob/ff87db04dd4e167b2a8a618dca8a16e5eb173c8f/pkg/sql/opt/optbuilder/testdata/srfs). 
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-13 15:45 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXpQ8GI1_oAzY6AGNJ8:b-nbasu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Well, the expression is starting out as a CAST expression, then within `buildZip` when we resolve the type, the CAST is elided, so it is converted into a simple column expression.  Maybe type checking needs to be done earlier so that we can see before inScope is built that the final expression is a `scopeColumn`?
</blockquote></details>

I was thinking this is maybe more of an issue that there is no good way to represent in a project set expression the passthrough of a column, since we build each scalar as a zip item, so we have to project the column to a new column id since it's not a direct passthrough.


<!-- Sent from Reviewable.io -->

2023-06-14 19:21 UTC, msirek reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXvLTat2wRG0uCpCm6w:bnauq3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

I was thinking this is maybe more of an issue that there is no good way to represent in a project set expression the passthrough of a column, since we build each scalar as a zip item, so we have to project the column to a new column id since it's not a direct passthrough.
</blockquote></details>

I've updated the code to use populateSynthesizedColumn per our discussion outside of this PR.


<!-- Sent from Reviewable.io -->

2023-06-14 20:53 UTC, DrewKimball reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXvdLkh2qz16nJoR8n0:b79khz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
>If `buildScalar` incorrectly thinks that a column can be passed-through, rather than projected, it's because that column is part of the `inScope` passed to `buildScalar`. So I think we're passing the wrong scope to `buildScalar`. I think we should be passing `inScope.replace()` (or maybe `inScope.push()`). I tried both quickly and they both broke another test, so there's something wonky to iron out there.

>I was thinking this is maybe more of an issue that there is no good way to represent in a project set expression the passthrough of a column, since we build each scalar as a zip item, so we have to project the column to a new column id since it's not a direct passthrough.

I think we should dig more into this - the `ProjectSet` has no input columns, so why is `buildScalar` thinking any columns are in scope? We should be hitting this case in `finishBuildScalarRef`: https://github.com/cockroachdb/cockroach/blob/ae25f4d06a7257f5e30f327217cef85757f20c23/pkg/sql/opt/optbuilder/project.go#L334-L349


<!-- Sent from Reviewable.io -->

2023-06-14 20:55 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXvg9I-4iIyOd8tpy7C:b-kbwavx) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

>If `buildScalar` incorrectly thinks that a column can be passed-through, rather than projected, it's because that column is part of the `inScope` passed to `buildScalar`. So I think we're passing the wrong scope to `buildScalar`. I think we should be passing `inScope.replace()` (or maybe `inScope.push()`). I tried both quickly and they both broke another test, so there's something wonky to iron out there.

>I was thinking this is maybe more of an issue that there is no good way to represent in a project set expression the passthrough of a column, since we build each scalar as a zip item, so we have to project the column to a new column id since it's not a direct passthrough.

I think we should dig more into this - the `ProjectSet` has no input columns, so why is `buildScalar` thinking any columns are in scope? We should be hitting this case in `finishBuildScalarRef`: https://github.com/cockroachdb/cockroach/blob/ae25f4d06a7257f5e30f327217cef85757f20c23/pkg/sql/opt/optbuilder/project.go#L334-L349
</blockquote></details>

Using `inScope.push()` at the top of `buildZip` sounds like it should be correct, what tests were failing as a result of that?


<!-- Sent from Reviewable.io -->

2023-06-15 14:02 UTC, mgartner commented
*[`pkg/sql/opt/optbuilder/srfs.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NXp7z5d7CLMW1bp1_1r:-NXvu2o96aWQixMgJZxi:b-wvfpzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c80dc7e2e3f2f3e4b2db82b7939c45b95f8bd1/pkg/sql/opt/optbuilder/srfs.go#L142)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Using `inScope.push()` at the top of `buildZip` sounds like it should be correct, what tests were failing as a result of that?
</blockquote></details>

This test was failing with "aggregate function is not allowed in this context": https://github.com/cockroachdb/cockroach/blob/b343c3b0373dd1bb3767e7038fa521e2ea3a59e2/pkg/sql/opt/optbuilder/testdata/subquery#L2295

When using `inScope.push()`, `finishBuildScalarRef` was marking column references as outer columns of subqueries, if `b.subquery` was set. This was causing errors when building an aggregate function with the subquery argument. Temporarily unsetting `b.subquery` solved this. Here's the changes I made: https://github.com/mgartner/cockroach/commit/3633a9973a68ecaa67a3d66ab575e7ed767b6562


<!-- Sent from Reviewable.io -->

2023-06-15 23:05 UTC, DrewKimball commented
I think this is a bug in `endAggFunc` - it collects all columns referenced while building the arguments in order to find the correct grouping scope, but in the case of a subquery some of those columns might have originated from the subquery, so they can't be used for this purpose.

2023-06-15 23:17 UTC, DrewKimball commented
This diff did the trick I think:
```
diff --git a/pkg/sql/opt/optbuilder/scope.go b/pkg/sql/opt/optbuilder/scope.go
index f31453995a2..b8d37757c8d 100644
--- a/pkg/sql/opt/optbuilder/scope.go
+++ b/pkg/sql/opt/optbuilder/scope.go
@@ -703,7 +703,12 @@ func (s *scope) endAggFunc(cols opt.ColSet) (g *groupby) {
                }
        }

-       panic(errors.AssertionFailedf("aggregate function is not allowed in this context"))
+       //panic(errors.AssertionFailedf("aggregate function is not allowed in this context"))
+       s.verifyAggregateContext()
+       if s.groupby == nil {
+               s.initGrouping()
+       }
+       return s.groupby
 }

 // verifyAggregateContext checks that the current scope is allowed to contain
diff --git a/pkg/sql/opt/optbuilder/srfs.go b/pkg/sql/opt/optbuilder/srfs.go
index 039e79ab595..d378174f1b1 100644
--- a/pkg/sql/opt/optbuilder/srfs.go
+++ b/pkg/sql/opt/optbuilder/srfs.go
@@ -74,6 +74,12 @@ var _ tree.TypedExpr = &srf{}
 //
 //     zip([1,2,3], ['a','b']) = [(1,'a'), (2,'b'), (3, null)]
 func (b *Builder) buildZip(exprs tree.Exprs, inScope *scope) (outScope *scope) {
+       // Create a temporary scope for building zip expressions. The inScope is not
+       // used because it contains an expression and ProjectSet has no input
+       // expression.  The alias must be preserved for correctly building zip
+       // expressions that are subqueries.
+       tempScope := inScope.push()
+       tempScope.alias = inScope.alias
        outScope = inScope.push()

        // We need to save and restore the previous value of the field in
@@ -82,7 +88,7 @@ func (b *Builder) buildZip(exprs tree.Exprs, inScope *scope) (outScope *scope) {
        defer b.semaCtx.Properties.Restore(b.semaCtx.Properties)
        b.semaCtx.Properties.Require(exprKindFrom.String(),
                tree.RejectAggregates|tree.RejectWindowApplications|tree.RejectNestedGenerators)
-       inScope.context = exprKindFrom
+       tempScope.context = exprKindFrom

        // Build each of the provided expressions.
        zip := make(memo.ZipExpr, 0, len(exprs))
@@ -96,7 +102,7 @@ func (b *Builder) buildZip(exprs tree.Exprs, inScope *scope) (outScope *scope) {
                if err != nil {
                        panic(err)
                }
-               texpr := inScope.resolveType(expr, types.Any)
+               texpr := tempScope.resolveType(expr, types.Any)

                var def *tree.ResolvedFunctionDefinition
                funcExpr, ok := texpr.(*tree.FuncExpr)
@@ -123,7 +129,7 @@ func (b *Builder) buildZip(exprs tree.Exprs, inScope *scope) (outScope *scope) {
                        outCol = outScope.addColumn(scopeColName(tree.Name(alias)), texpr)
                }

-               scalar := b.buildScalar(texpr, inScope, outScope, outCol, nil)
+               scalar := b.buildScalar(texpr, tempScope, outScope, outCol, nil)
                numExpectedOutputCols := len(outScope.cols) - startCols
                cols := make(opt.ColList, 0, numExpectedOutputCols)
                for j := startCols; j < len(outScope.cols); j++ {
```

2023-06-16 19:14 UTC, mgartner commented
Do you feel strongly that that's a better solution than temporarily unsetting `b.subquery` like I did? It matches some existing logic: https://github.com/cockroachdb/cockroach/blob/080fd89661460290f09f2291d875ce4b5a5e4699/pkg/sql/opt/optbuilder/groupby.go#L708-L712

2023-06-16 22:54 UTC, DrewKimball commented
Unsetting the subquery might be a bit better, but I think the whole way we're handling outer columns in the optbuilder is suspect. Why are we trying to gather outer columns as we build expressions, when we could retrieve them after the expression is built using the `OuterCols` property? The current approach seems vulnerable to gathering "outer" columns that aren't actually "outer".

So what I'm trying to say is, when we want the columns referenced by an aggregate argument, we shouldn't pass a `colRefs` argument to `buildScalar` - instead, we should build the argument and then check `OuterCols`. Similarly with the outer columns for a subquery - we should just check the `OuterCols` field for the input(s) of the subquery. I'm wary of fixes that don't address this, since it's not clear what the consequences will be in other edge cases.

2023-06-18 20:51 UTC, rytaft reviewed
> Why are we trying to gather outer columns as we build expressions, when we could retrieve them after the expression is built using the `OuterCols` property? The current approach seems vulnerable to gathering "outer" columns that aren't actually "outer".

This is by design. `optbuilder` builds expressions and performs semantic analysis based on the provided AST, not by inspecting what it has already built. Since any number of normalization rules may fire and change the expression into something else entirely, the `optbuilder` should not rely on the logical properties that we use in other places. However we decide to fix this issue and other issues with the `optbuilder` going forward, I think it's important to stick to this principle of non-inspection.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NYFEyKz6u2Qu_QSYAFX:b-5v8x17)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @msirek)



<!-- Sent from Reviewable.io -->

2023-06-21 14:16 UTC, mgartner commented
> This is by design...

Very interesting - thanks for this context! It makes sense that in order to catch invalid parts of a query we need to operate on the AST and not a normalized expression which may eliminate parts of a query entirely.





<!-- Sent from Reviewable.io -->

2023-06-21 17:42 UTC, DrewKimball commented
>This is by design. optbuilder builds expressions and performs semantic analysis based on the provided AST, not by inspecting what it has already built. Since any number of normalization rules may fire and change the expression into something else entirely, the optbuilder should not rely on the logical properties that we use in other places. However we decide to fix this issue and other issues with the optbuilder going forward, I think it's important to stick to this principle of non-inspection.

Thanks for the explanation. In that case, maybe it would be better to track which columns a subquery produces, alongside the columns it references (which is what `outerCols` seems to really be). That way, we could get the actual outer-column references by taking the difference between referenced and produced columns.

@mgartner thinking more about the idea to temporarily unset the subquery, I don't think it's correct (at least as-is). The other place where we unset it, it's because we're going to set the outer columns later and don't want `finishBuildScalarRef` to do it before we know which scope we're grouping in. If we just unset the subquery and completely prevent the outer columns from being set, that feels like it'll cause issues elsewhere.

2023-06-21 19:06 UTC, rytaft commented
> maybe it would be better to track which columns a subquery produces, alongside the columns it references (which is what outerCols seems to really be). That way, we could get the actual outer-column references by taking the difference between referenced and produced columns.

Maybe I'm confused. An outer column that's returned from a subquery is still an outer column, no?

2023-06-21 20:05 UTC, DrewKimball commented
>Maybe I'm confused. An outer column that's returned from a subquery is still an outer column, no?

Sorry, a better word might be `projected` - if the subquery (or a nested subquery) projects columns in its from clause, they are in scope and therefore not outer even though they're referenced in the subquery. That's the problem Marcus ran into [here](https://github.com/cockroachdb/cockroach/pull/104756#issuecomment-1593132002) - `a` is not an outer column because it originates from `v95470`.

2023-06-21 21:16 UTC, rytaft commented
> Sorry, a better word might be "projected" - if the subquery (or a nested subquery) projects columns in its from clause, they are in scope and therefore not outer even though they're referenced in the subquery. That's the problem Marcus ran into https://github.com/cockroachdb/cockroach/pull/104756#issuecomment-1593132002 - a is not an outer column because it originates from v95470.

Ah got it, makes sense, thanks!

2023-06-22 15:13 UTC, msirek reviewed
So, if we want to create an extra scope so `buildScalar` will build column expressions for us, does that mean that we should also redo how aggregate expressions are generated?  Aggregates, like zips, don't pass through columns but build expressions on them:
https://github.com/cockroachdb/cockroach/blob/080fd89661460290f09f2291d875ce4b5a5e4699/pkg/sql/opt/optbuilder/groupby.go#L660-L664

If it is incorrect for SRFs to have special handling for column expressions, is it also incorrect for aggregate processing to do this special handling?  

It seems like we've been saying, we need another nested scope because `buildScalar` incorrectly thinks that a column can be passed-through, rather than projected. But it almost seems like `buildScalar` was originally written for projections, but then was later used for different operations that didn't support pass-through columns or needed to do extra processing on the column. Could it be that new callers of buildScalar` have had to create a new scope just to get around this issue?  

Anyway, just pointing out that aggregates have special handling for `scopeColumn`s too.  Is there a reason why it would be correct to do special handling in the aggregates case, but not SRFs?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NYYZYUI2PnJ7O2EGsil:bk7xybt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2023-06-22 17:53 UTC, DrewKimball approved these changes
@msirek sorry for the long detour... I think your changes here will work, and unfortunately pushing a new scope like we discussed doesn't seem simple. In any event, it's probably not worth spending much more time on. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

 One last thought about passthrough columns - `ProjectSet` can actually pass through columns, but they have to be part of the input expression, and we just use an empty `Values` for the input. So maybe there's something there?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NYZBjD4-w8-yk3h7_44:bw65twu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @msirek, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NYZDhuN7PMTZeU5wui6:-NYZDhuN7PMTZeU5wui7:bczaghp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d5b0b83176b06f0eb99ae732aeb2b0df7f4e40/pkg/sql/opt/optbuilder/srfs.go#L140)):*
> ```Go
> 			// Pre-existing function `populateSynthesizedColumn` does the necessary
> 			// steps for us.
> 			b.populateSynthesizedColumn(&outScope.cols[len(outScope.cols)-1], scalar)
> ```

[nit] I think you could use `outCol` in place of `&outScope.cols[len(outScope.cols)-1]`.


<!-- Sent from Reviewable.io -->

2023-06-22 17:56 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> too. The detour was educational for me. I appreciate everyones input and patience!

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NYZEdp84YlR4rIb3ITI:b-c4bedu)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @rytaft)

___
*[`pkg/sql/opt/optbuilder/srfs.go` line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-NYZDhuN7PMTZeU5wui6:-NYZEb-xAoJDdCBGe0UR:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4d5b0b83176b06f0eb99ae732aeb2b0df7f4e40/pkg/sql/opt/optbuilder/srfs.go#L140)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I think you could use `outCol` in place of `&outScope.cols[len(outScope.cols)-1]`.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-06-26 14:55 UTC, msirek reviewed
TFTRs!
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104756#-:-NYsByA22gClqJQ4J7Op:bg1822s)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @rytaft)



<!-- Sent from Reviewable.io -->

2023-06-26 15:44 UTC, merged