allocator2: add cluster state mutators
cockroachdb/cockroach pull request #104842
Opened 2023-06-14 02:06 UTC by kvoli

This patch populates the cluster state `processNodeLoadResponse` method and pending change associated methods.

Upon receiving a node load response, the tracked pending changes are checked for updates - the change's effects were reported in the store's load  or enacted by the leaseholder.

Additional datadriven test helpers are added to parse test file input. The intention is for these to be used for testing candidate selection and rebalancing.

Informs: #103320

Epic: CRDB-25222

Release note: None

2023-06-14 19:11 UTC, sumeerbhola requested changes
flushing some comments. mostly nits.

> Reviewed 7 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-:-NXvJNCj8T_cd8j2J7TH:bwn9kqh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvESBkBKkzJ_dl9XqY:-NXvESBkBKkzJ_dl9XqZ:bjd01ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L198)):*
> ```Go
> }
> 
> func makeAddReplicaChange(
> ```

we will need additional methods for NON_VOTER => VOTER and VOTER => NON_VOTER transitions, yes?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvEmzhEL71Z3eb0c2s:-NXvEmzhEL71Z3eb0c2t:b-vz4gev) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L224)):*
> ```Go
> }
> 
> func makeRemoveReplicaChange(rLoad rangeLoad, remove storeIDAndReplicaState) replicaChange {
> ```

maybe add a code comment that we are assuming the replica being removed is not the leaseholder.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvFPz12OzZjqpXK8zn:-NXvFPz12OzZjqpXK8zo:bxn20ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L256)):*
> ```Go
> 	if remove.isLeaseholder {
> 		// The existing leaseholder is being removed. The incoming replica will
> 		// take the lease load, in addition to the replica load.
> ```

I have forgotten the exact state transitions associated with a "joint config" when doing a rebalance. Presumably we transition the incoming one through LEARNER => VOTER_INCOMING => VOTER_FULL before we start downgrading the outgoing one to VOTER_DEMOTING_LEARNER? Which is what allows the lease to be transferred to the incoming voter?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvAeR7CS1cBbtFzGqd:-NXvAeR7CS1cBbtFzGqe:b-jw03e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L399)):*
> ```Go
> }
> 
> func newStoreState(storeID roachpb.StoreID, nodeID roachpb.NodeID) *storeState {
> ```

same question about lack of StoreDescriptor parameter.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvHwXp7LEfUJO04OJC:-NXvHwXp7LEfUJO04OJD:b7jq618) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L510)):*
> ```Go
> type rangeState struct {
> 	// replicas is the adjusted replicas. It is always consistent with
> 	// the storeState.adjusted.replicas in the corresponding stores.
> ```

This comment is stale and predates the partial consistency we are allowing via `loadReplicas`. I don't think this is consistent with `loadReplicas` and will be consistent with what the leaseholder says.

It does reflect `pendingChanges`.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvIz7m6rsnACrO2oMD:-NXvIz7m6rsnACrO2oME:bybekq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L538)):*
> ```Go
> 	i := 0
> 	n := len(rs.pendingChanges)
> 	for ; i < n; i++ {
> ```

I suppose the caller knows why this pending change is being removed, either because it has been enacted, or it has failed, and in the latter case the caller will undo the effect on `rangeState.replicas`?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvAsHPDsXNK-UAIAvy:-NXvAsHPDsXNK-UAIAvz:bnvdk9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L579)):*
> ```Go
> 	ranges map[roachpb.RangeID]*rangeState
> 	// storeList contains identical stores to those in the store state map. The
> 	// list is kept for deterministic iteration over stores.
> ```

is the deterministic iteration needed for tests?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvB3Ie3ZI7ea6w16q7:-NXvB3Ie3ZI7ea6w16q8:bsbst4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L588)):*
> ```Go
> 	// the single source of truth of a rangeState is the leaseholder.
> 	pendingChanges    map[changeID]*pendingReplicaChange
> 	pendingChangeList []*pendingReplicaChange
> ```

why the slice in addition to the map?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvJHlZ4aOYU29uoMIp:-NXvJHlZ4aOYU29uoMIq:b-tync7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L614)):*
> ```Go
> //======================================================================
> 
> func (cs *clusterState) processNodeLoadResponse(resp *nodeLoadResponse) error {
> ```

(note to self) resume reading here
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXv5qpr6kR1iEqQejNw:-NXv5qpr6kR1iEqQejNx:by1zh40) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/load.go#L156)):*
> ```Go
> 	// Mean load for the non-top-k ranges. This is used to estimate the load
> 	// change for transferring them.
> 	meanNonTopKRangeLoad rangeLoad
> ```

The use here was why `rangeLoad` did not have a `RangeID` field.
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXv6DA51OiWTEQx4xVx:-NXv6DA51OiWTEQx4xVy:bnizrch) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/load.go#L159)):*
> ```Go
> }
> 
> func newStoreLoad(storeID roachpb.StoreID, nodeID roachpb.NodeID) storeLoad {
> ```

Assuming we are agreed on the `Allocator.SetStore(store roachpb.StoreDescriptor) error` interface method, won't we have the `StoreDescriptor` at this point? 
___
*[`pkg/kv/kvserver/allocator/allocator2/load.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXv6Ygp74hn8PH5Yqcq:-NXv6Ygp74hn8PH5Yqcr:bgoyh8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/load.go#L163)):*
> ```Go
> 		StoreID:    storeID,
> 		NodeID:     nodeID,
> 		topKRanges: []rangeLoad{},
> ```

why this initialization, since it is now a slice?
btw, it was a map because various code paths in the allocator kernel needed to lookup the load given the rangeID.


<!-- Sent from Reviewable.io -->

2023-06-14 22:43 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 362 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvrQ9e3srgNzbTO6rK:-NXvrQ9e3srgNzbTO6rL:b-llz0ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L362)):*
> ```Go
> 		// Unilateral removal from loadPendingChanges happens if the load reported
> 		// by the store shows that this pending change has been enacted. We no
> 		// longer need to adjust the load for this pending change.
> ```

This is the one case where removal from here can lead the removal from {clusterState,rangeState}.pendingChanges.
But since in this distributed allocator integration we will manufacture the set of replicas "reported by the store" based on the leaseholder's state, this won't actually happen.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvseGlEV-9jCidcnlH:-NXvseGlEV-9jCidcnlI:b9yulps) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L621)):*
> ```Go
> 
> 	now := cs.clock.Now()
> 	cs.gcPendingChanges(now)
> ```

nit: I think we should do this once before every rebalancing pass, instead of doing it every time any node provides us a response.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvsuzt3z5xCrpVCf2z:-NXvsuzu7c-w_VSAwTIs:b9au5b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L637)):*
> ```Go
> 	}
> 
> 	// Handle the leaseholder store messages first. These have do not effect load
> ```

These do not affect load ...
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvvIfRAPQ3vkL8JobX:-NXvvIfRAPQ3vkL8JobY:b21pg3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L649)):*
> ```Go
> 			for _, replica := range rangeMsg.replicas {
> 				ss := cs.stores[replica.StoreID]
> 				ss.adjusted.replicas[rangeMsg.RangeID] = replica.replicaState
> ```

I think we also need to remove from stores that no longer have replicas. We have the old state in `rs` we can take the set difference with `rangeMsg.replicas` or to start with just do the unilateral removal and then addition. So things that are unchanged will get removed and added.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvuVZEDs7G-utA1bqf:-NXvuVZEDs7G-utA1bqg:b-mah1hu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L673)):*
> ```Go
> 					remainingChanges = append(remainingChanges, change)
> 				}
> 			}
> ```

don't we need to do `rs.pendingChanges = remainingChanges` after the loop?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvwNGV13o2x2SO6My8:-NXvwNGV13o2x2SO6My9:be6bak2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L696)):*
> ```Go
> 	ns.reportedCPU = resp.reportedCPU
> 	ns.adjustedCPU = resp.reportedCPU
> 	ns.nodeLoad = resp.nodeLoad
> ```

when do we update `ns.stores`? I suppose we only need to handle new stores on an existing node?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvwmB_0GNsqG9X11HQ:-NXvwmB_0GNsqG9X11HR:b-q4ov3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L700)):*
> ```Go
> 		// NB: The store must exist, we checked it above.
> 		ss := cs.stores[msg.StoreID]
> 		initialLoadSeqNum := ss.loadSeqNum
> ```

can we simply increment it here instead of waiting until after the code block below?
The multi-threading story is not yet worked out, but we could start with just holding one mutex for both updates and rebalancing.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvx7GG1bA750e0otuY:-NXvx7GG1bA750e0otuZ:b-cv7trx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L704)):*
> ```Go
> 		oldLoadReplicas := ss.adjusted.loadReplicas
> 		for _, r := range msg.storeRanges {
> 			// Upate the last heard from time for the range, creating a new range state
> ```

nit: Update
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 736 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXw2Ueh0oMoa0INnEKR:-NXw2Ueh0oMoa0INnEKS:bjn399c) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L736)):*
> ```Go
> 			// approach for invalidation for load updates given the kernel prototype.
> 			//
> 			// TODO(kvoli): Unify this with subsumesChange.
> ```

I think we can unify this now.
We have a `change` which has the `prev` and `next` state, and we have the `newRepl, inNew` which we can use to synthesize the latest `replicaIDAndType`. So we remove the pending change (a) it is subsumed, or (b) enactedAtTime is set and `latestLoadTime.Sub(change.enactedAtTime) > lagForChangeReflectedInLoad ` (the logic from my other PR).
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 770 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXw3jlt0q47Z84m7-7U:-NXw3jlt0q47Z84m7-7V:b-2rdkqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L770)):*
> ```Go
> }
> 
> func (cs *clusterState) setStore(store roachpb.StoreDescriptor) error {
> ```

(stopped here, will resume tomorrow)


<!-- Sent from Reviewable.io -->

2023-06-15 14:37 UTC, sumeerbhola requested changes
haven't read the tests yet

> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-:-NXzUC5w8GW8bCZszIxg:b-eap0zi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzLxeE6X9R5tPIpVrr:-NXzLxeFDU3_Co5GrzvE:b-nm5t0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L802)):*
> ```Go
> 	// Update the locality of any other stores on the same node. It is unlikely
> 	// the locality changed, however possible after a restart, in which case the
> 	// old locality would be updated one at a time.
> ```

Do we really need to do this? Transient inconsistency seems ok, and presumably we will get `setStore` calls for these other stores with the new descriptor.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzO3XQ02nkU-MbkU4C:-NXzO3XQ02nkU-MbkU4D:bm25ye3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L860)):*
> ```Go
> 	}
> 	for _, rmChange := range removeChangeIds {
> 		cs.undoPendingChange(rmChange)
> ```

This will also undo from the the load values in `storeState.adjusted` yes?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzOAVg6r1Y8MUngvYt:-NXzOAVg6r1Y8MUngvYu:btuqspk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L864)):*
> ```Go
> 
> 	// Find any enacted pending changes which were enacted more than
> 	// enactedPendingChangeGCDuration duration ago. These can also be GC'd.
> ```

I think we should eliminate this code and do this GC only when we receive a new load message from this store. If the store is not sending us updates there is something wrong. And in that case we don't want to undo the load effect of the changes since we know they have happened.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 873 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzOg3r9p0XYB2yQmCF:-NXzOg3s0yUx6TajRJZW:bhdv7hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L873)):*
> ```Go
> 				!change.enactedAtTime.After(gcEnactedBeforeTime) {
> 				// NB: We only need to undo the load adjustments and load replicas. The
> 				// change was enacted, so it will already be removed from the
> ```

nit: so it was already removed ...
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzOy2-CYVCQsTIjyq1:-NXzOy2-CYVCQsTIjyq2:bzbq0a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L889)):*
> ```Go
> 	// TODO(sumeerbhola,kvoli): This won't handle rejecting changes which have
> 	// been partially reported as complete by the store load. Handle this or
> 	// reason that it won't happen.
> ```

I think its reasonable to make it a noop. That is, if we don't find the change in clusterState or rangeState then we have either gc'd it or it has been enacted, and we can ignore it. In the enacted case, it may still be in `storeState.adjusted.loadPendingChanges` but we don't need to do anything there since it will be removed eventually when more recent load information is reported.

If I am reading correctly, the current code in `undoPendingChange` already has this noop behavior.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzQu29AiJQfzI1cDPv:-NXzQu29AiJQfzI1cDPw:bcwvznx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L939)):*
> ```Go
> 	if change.isRemoval() {
> 		// The change is to remove a replica.
> 		var idx int
> ```

where is `idx` used?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 1003 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzSZ3uAEYaCrF98JZY:-NXzSZ3uAEYaCrF98JZZ:b-hzkfts) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L1003)):*
> ```Go
> }
> 
> func (cs *clusterState) undoReplicaChange(change replicaChange, undoRepls bool) {
> ```

I think we need a code comment that says that there are two categories of pending change data-structures:
- load-adjusting:
- authoritative: from the leaseholder

And define which category each of the three (clusterState.pendingChanges, rangeState.pendingChanges, storeState.adjusted.loadPendingChanges) fall into. And which data-structures each of these influence.

Usually removal from authoritative will happen before the load-adjusting one, but it can also be in reverse (as we discussing in our meeting yesterday).

Then a parameter like `undoRepls`, can be defined as an enum that is `undoAll` or `undoLoadAdjusting`.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 1066 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzRvzJCxAmSHqs2rrP:-NXzRvzJCxAmSHqs2rrQ:bczpl91) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L1066)):*
> ```Go
> }
> 
> // removePendingChangeTracking removes the given from the cluster and range
> ```

the given change ...


<!-- Sent from Reviewable.io -->

2023-06-15 14:42 UTC, sumeerbhola requested changes
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/clusterstate/multi_store_no_changes` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzUX2s19-4eEP66A4O:-NXzUX2s19-4eEP66A4P:bpzrarn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/testdata/clusterstate/multi_store_no_changes#L30)):*
> ```
>   store-id=8 attrs=teal locality-code=8:9:10:
> 
> remove-node node-id=4
> ```

aren't the stores still there in the removed state? If yes, should we print them, so that the test can verify that behavior too.
___
*[`pkg/kv/kvserver/allocator/allocator2/testdata/clusterstate/pending_changes` line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzVDy_-NGh_tizGvWH:-NXzVDya06UoyyGzyoPc:bhpm87k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/testdata/clusterstate/pending_changes#L120)):*
> ```
> # sending a lease store message to mark the change as enacted; send a load
> # message which should drop the load adjustments but leave the change as
> # pending in the cluster and range state.
> ```

nice test


<!-- Sent from Reviewable.io -->

2023-07-05 13:20 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvESBkBKkzJ_dl9XqY:-NZR5wUX5bN6YsLduNxB:bdehbcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L198)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

we will need additional methods for NON_VOTER => VOTER and VOTER => NON_VOTER transitions, yes?
</blockquote></details>

Yes. I added a TODO, since it isn't required yet.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvEmzhEL71Z3eb0c2s:-NZR7gwG2SDia5m9j7u3:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L224)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

maybe add a code comment that we are assuming the replica being removed is not the leaseholder.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvFPz12OzZjqpXK8zn:-NZR7hx99fSCRpRWh4px:b-5ifemi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L256)):*
> Presumably we transition the incoming one through LEARNER => VOTER\_INCOMING => VOTER\_FULL before we start downgrading the outgoing one to VOTER\_DEMOTING\_LEARNER

The joint config transitiion for rebalnace I've seen, where B is added and A is removed: 
1. B LEARNER (snapshot)
2. ENTER JOINT: B VOTER_INCOMING, A VOTER_DEMOTING_LEARNER
3. A transfers the lease to B
4. EXIT JOINT: B VOTER, A LEARNER

The lease is transferred as the coordinating replica (outgoing leaseholder) finalizes the change, before proposing an empty change for exiting the joint config.

The incoming voter doesn't transition through to VOTER_FULL until the joint config is exited, it remains at VOTER_INCOMING.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvAeR7CS1cBbtFzGqd:-NZa2VO7Erm0xXOb6_aV:b8v0yxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L399)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question about lack of StoreDescriptor parameter.
</blockquote></details>

This is just a helper to init the struct.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 538 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvIz7m6rsnACrO2oMD:-NZSiBzT3YcYbxUcn6b9:b-d0xdie) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L538)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I suppose the caller knows why this pending change is being removed, either because it has been enacted, or it has failed, and in the latter case the caller will undo the effect on `rangeState.replicas`?
</blockquote></details>

Yeah, the caller is responsible for undoing the effect - this is just a helper method to remove from the pending change list tracked on the range.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvAsHPDsXNK-UAIAvy:-NZSVp4Y8ciRoS4ivKyz:bp593q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L579)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is the deterministic iteration needed for tests?
</blockquote></details>

It is needed for some tests in `cluster_state_test.go`. The storelist isn't used in non-testing code, so I removed it, adding a helper `testingGetStoreList` in the `cluster_state_test.go`instead.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvB3Ie3ZI7ea6w16q7:-NZSiV6nBtaGmVdIThSj:bnr14m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L588)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why the slice in addition to the map?
</blockquote></details>

The slice is used for GC only atm - the alternative is to create a list from the map first. 
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 614 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvJHlZ4aOYU29uoMIp:-NZa4JVB3Zwko_GCnyg4:b-zb5ugf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L614)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(note to self) resume reading here
</blockquote></details>

Replying here to clear our comments to respond.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvseGlEV-9jCidcnlH:-NZa2bu3AwRd2QmlsIVQ:b4ruo3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L621)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: I think we should do this once before every rebalancing pass, instead of doing it every time any node provides us a response.
</blockquote></details>

That sounds good.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvsuzt3z5xCrpVCf2z:-NZSgLl858j2OvZZq8TN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L637)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

These do not affect load ...
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvvIfRAPQ3vkL8JobX:-NZSncRx9PLKXIbi_U6M:b-dew6ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L649)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we also need to remove from stores that no longer have replicas. We have the old state in `rs` we can take the set difference with `rangeMsg.replicas` or to start with just do the unilateral removal and then addition. So things that are unchanged will get removed and added.
</blockquote></details>

Good catch - I've updated to unilaterlly removal+addition from `storeState.adjusted.replicas` and `rangeState.replicas` for each`rangeMsg`.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvuVZEDs7G-utA1bqf:-NZSj5bu0QedtCN84W79:bib3y1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L673)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

don't we need to do `rs.pendingChanges = remainingChanges` after the [...]

2023-10-14 03:18 UTC, sumeerbhola requested changes
This looks good.
There is one substantive comment about getting rid of `storeLoadMsg.storeRanges` and the ripple effect from it -- given we will have a decentralized allocator to start with, it makes a bunch of things easier to reason about.

> Reviewed 2 of 14 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-:-NggAYtS4Dk5h3y_zl24:beq13tl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 510 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvHwXp7LEfUJO04OJC:-NgelbPPEbToPN0gBjjL:b-62ax37) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L510)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This comment is stale and predates the partial consistency we are allowing via `loadReplicas`. I don't think this is consistent with `loadReplicas` and will be consistent with what the leaseholder says.

It does reflect `pendingChanges`.
</blockquote></details>

I don't know what I was thinking when writing this review comment. It is consistent with `storeState.adjusted.replicas` (as written in the code comment) and not necessarily consistent with `storeState.adjusted.loadReplicas`.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXvseGlEV-9jCidcnlH:-Ngen69d9SLIcHIAf74V:b-iusa41) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L621)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

That sounds good.
</blockquote></details>

TODO to make this change?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NXzLxeE6X9R5tPIpVrr:-Ngg5iYz3H_c8UTw-WOQ:b4rw0q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0097ce44185a0495da1ad402df25c8b27c02f562/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L802)):*
> Are you concerned with the perf cost of checking?

Not really. It just seems too defensive since these other calls will happen. And it seems more principled to not have side-effects on other stores.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-Ngeet8I3nPNTIU-IJJH:-Ngeet8I3nPNTIU-IJJI:b123jrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L88)):*
> ```Go
> 	// rit.replicaId equal to LEARNER, VOTER_DEMOTING* are left as-is. If next
> 	// is trying to remove a replica, this store is still seeing some of the
> 	// load.
> ```

The comment here and in the switch statement both relate to load. We now have two kinds of pending changes: authoritative and load-adjusting. Perhaps the choice above to pretend that VOTER_INCOMING is the same as VOTER_FULL is acceptable since the allocator does not need to do anything more (the range will eventually exit the joint config), though it is a bit odd. Perhaps we should add a parameter to `subsumesChange`, and adjust the behavior in this method based on whether we are dealing with a load-adjusting change or not.

Revised: In light of the later comments, this will only be called for the authoritative changes, to decide whether they have been enacted. So we shouldn't need a parameter.
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NgehMND-mSNgM1U8hkL:-NgehMND-mSNgM1U8hkM:b2xqxws) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L200)):*
> ```Go
> // makeAddReplicaChange creates a replica change which adds the replica type
> // to the store addStoreID. The load impact of adding the replica does not
> // account for whether the replica is becoming the leaseholder or not.
> ```

Is this "does not account for" part a deficiency that we need to address later, or can we assume that for normal systems the lease will not typically be transferred to this new replica (unless some other unrelated failure happens) and that the allocator will have a chance later to examine the lease preferences?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NgeiBdK0e5nzdTIVVP-:-NgeiBdK0e5nzdTIVVP0:bdos60m) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L248)):*
> ```Go
> }
> 
> // makeRebalanceReplicaChanges creates to replica changes, adding a replica and
> ```

s/to/two/
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 792 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NgemJ1L2gf0FEms94GT:-NgemJ1L2gf0FEms94GU:bjnuzjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L792)):*
> ```Go
> 			break
> 		}
> 	}
> ```

should this panic if the `storeID` was not found?
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 859 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-NgewUdx-l5JKz5ZgiZk:-NgewUdx-l5JKz5ZgiZl:b-sbyufr) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L859)):*
> ```Go
> 	}
> 
> 	// Handle the leaseholder store messages first. These have do not affect load
> ```

s/have//
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 879 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-Ngex2sc46rB9XO8vwW-:-Ngex2sc46rB9XO8vwW0:bf3w89u) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L879)):*
> ```Go
> 			// Set the range state replicas to be equal to the range leaseholder
> 			// replicas. The pending changes which aren't enacted in the range
> 			// message are hanled and added back below.
> ```

nit: handled
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 934 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-Ngezw-S8GrYMZKYY-Wm:-Ngezw-S8GrYMZKYY-Wn:b-cio9iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L934)):*
> ```Go
> 		// NB: The store must exist, we checked it above.
> 		ss := cs.stores[msg.StoreID]
> 		// The store's load seqeunce number is incremented on each load change. The
> ```

sequence
___
*[`pkg/kv/kvserver/allocator/allocator2/cluster_state.go` line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104842#-Ngf15OE4brKfiO2b26N:-Ngf15OE4brKfiO2b26O:b-5nfrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/91c87b8a282d1da7ca0386b6cc3e1674be29d283/pkg/kv/kvserver/allocator/allocator2/cluster_state.go#L942)):*
> ```Go
> 			// Update the last heard from time for the range, creating a new range state
> 			// if we have never heard about this range before.
> 			rs, ok := cs.ranges[r.RangeID]
> ```

I don't think the load information should fiddle with `clusterState.ranges`. `clusterState.ranges` is authoritative state coming from leaseholders, while this store reported load information should only be fiddling with `loadReplicas`. There is no requirement that the ranges in `loadReplicas` be in `clusterState.ranges`.
This is also consistent with the idea that we don't h [...]

2024-08-29 12:55 UTC, kvoli commented
Closing this dangling PR for now. We may pick back up the `allocator2` work in the near future.

2025-02-20 22:57 UTC, kvoli commented
Going to extract the relevant parts from this PR into a fresh one. Some concepts are no longer relevant.

2025-03-05 15:43 UTC, kvoli commented
Subsumed by https://github.com/cockroachdb/cockroach/pull/141945.

2025-03-05 15:43 UTC, closed without merging