changefeedccl: add lagging_ranges, total_ranges, progress metrics
cockroachdb/cockroach pull request #105280
Opened 2023-06-21 13:59 UTC by samiskin

Resolves https://github.com/cockroachdb/cockroach/issues/102146
Resolves https://github.com/cockroachdb/cockroach/issues/97009

This PR adds `aggregator_total_ranges`, `aggregator_lagging_ranges`, and `aggregator_progress` metrics to be able to measure the health of each aggregator node individually over time.  A Lagging Ranges graph has also been added to the db console page that just shows the total number of lagging ranges across the cluster.

Every `changefeed.lagging_ranges_log_frequency` (default 2 minutes), each aggregator will check each of its ranges, recording the total count, then comparing them against its frontier to determine how many are behind by more than `changefeed.lagging_ranges_threshold` (default 10 minutes).

A graph for it has been added to the dbconsole.  The following images were taken while simulating unhealthy ranges by having certain keys resolved timestamps not be emitted by the kvfeed when a cluster setting was enabled.
<img width="964" alt="Screenshot 2023-06-21 at 9 54 22 AM" src="https://github.com/cockroachdb/cockroach/assets/6236424/fb6ad9d9-fc96-4afd-9df4-8d79b306fd4a">

A `checkpoint_progress` sli metric has also been added to act in a similar capacity to `max_behind_nanos`.  I elected to keep it as just the timestamp since it's still possible in graphing tools to determine the lag (ex: grafana query would be `time()*1000 -
(changefeed_aggregator_progress{scope!=""}/1000/1000)`).

<img width="791" alt="Screenshot 2023-06-21 at 9 45 41 AM" src="https://github.com/cockroachdb/cockroach/assets/6236424/c67fa73f-6665-4ecd-87e7-5923f6984289">

I also added the new info to the default grafana dashboard for roachtests
<img width="1302" alt="Screenshot 2023-06-21 at 9 53 06 AM" src="https://github.com/cockroachdb/cockroach/assets/6236424/238ad1f1-1b20-485d-909c-977c178e36cb">

Release note (ops change): New aggregator_total_ranges and aggregator_lagging_ranges metrics have been added to track how many ranges are behind a configurable changefeed.lagging_ranges_threshold duration. checkpoint_progress and aggregator_progress metrics have also been added to track the timestamp of the changefeed's persisted checkpoint and each individual aggregators progress.  checkpoint_progress can be used for a similar purpose to max_behind_nanos but now with support for per-changefeed metrics labels.

2023-06-21 20:37 UTC, miretskiy requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @renatolabs, @samiskin, and @smg260)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNgul6p7BDjK9rdkY:-NYTNgul6p7BDjK9rdkZ:bx54cyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L96)):*
> ```Go
> 	flushFrequency        time.Duration // how often high watermark can be checkpointed.
> 	lastSpanFlush         time.Time     // last time expensive, span based checkpoint was written.
> 	lastLaggingRangeCheck time.Time     // last time all ranges were healthchecked
> ```

nit: lastHealthCheck might be a better name?
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1571 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTOxv61jOnDnft0D32:-NYTOxv61jOnDnft0D33:b-c9zqqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L1571)):*
> ```Go
> 	behindRanges := 0
> 
> 	// Both ranges and ca.frontier.Entries are in ascending timestamp order, so
> ```

I don't think ranges is in the ascending timestamp order (and neither is ca.frontier).
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTigO46tZBp6cdlfy4:-NYTigO46tZBp6cdlfy5:b-2wey70) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L1573)):*
> ```Go
> 	// Both ranges and ca.frontier.Entries are in ascending timestamp order, so
> 	// scanning across both together will handle every overlap.
> 	ca.frontier.Entries(func(sp roachpb.Span, ts hlc.Timestamp) span.OpResult {
> ```

In general, I'm a fan of exporting "basic" stats (number of ranges, number of unhealthy ranges) and relying on grafana to determine derivative metrics (like health percentage).

In this case, however, there is an argument to be made to export derivative metric (health %-ge) directly.
In a happy case, we expect that frontier is up to date, and that nothing is behind.  Only if we know we have ranges that are behind do we need to go through the trouble of figuring the rest out.  I.e. the work you do above -- namely, kvfeed.AllRangeSpans call -- is wasted in majority cases.

I understand that this computation doesn't happen often -- but it does happen every 10 minutes; meaning that every 10 minutes or so, there will be a non-insignificant dip in changefeed aggregator performance because every 10 minutes a call that used to take next to nothing (advance frontier) will suddenly take longer, perhaps significantly longer if kvfeed.AllRangeSpans call returns large number of spans (span iterator is not free).

If we are to export derivative metrics, then, the logic becomes -- peek span frontier -- if it's up to date, then we export 1.0; otherwise, we get all ranges, and execute this logic.

An alternative (to exporting derivative metrics) is to try to do what you're doing.. but in a cheap(er) way.
I'm just brainstorming here, so use some "salt shaker".

This function is called whenever noteResolvedSpan is called.  The nice thing about noteResolvedSpan method is that it is called with a ResolvedSpan argument -- but it's actually not a span -- it's a range. We can maintain a list of ranges, which we refresh (reset) whenever frontier advances.  We only really need to have a map[string]->struct{} to keep track of the starting key of the range.
(this map maybe initialized at start to contain initial key map -- or perhaps find a way to piggy back on kvfeed so that we don't call AllRangeSpans multiple times; probably okay though to call it here).
So, we'll basically know an almost up to date count of ranges and their starting key.
So, periodically, Peek at the frontier span -- if it's old, then determine how many ranges are old.
For each range start key -- call frontier.SpanEntries(Span{startKey, startKey + 1}).   Determine if the intersection is old or not.  Update metric appropriately.
___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNRvE-UCxGLS1-8qw:-NYTNRvE-UCxGLS1-8qx:bh3vtnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeedbase/settings.go#L95)):*
> ```Go
> // LaggingRangesLogFrequency controls how often an aggregator checks all of its
> // ranges for whether or not they are sufficiently lagging behind.
> var LaggingRangesLogFrequency = settings.RegisterDurationSetting(
> ```

It's not "Log" frequency per say, is it? 
___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNVaH-ZQpinfYoz_I:-NYTNVaI5uZuol_Hmjil:bhw1wuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeedbase/settings.go#L109)):*
> ```Go
> 	"changefeed.lagging_ranges_threshold",
> 	"controls how far behind a range must be from the present to be considered as 'lagging' behind in metrics",
> 	10*time.Minute,
> ```

lower it perhaps?  
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYUfDwS6_2X-QLu5Ffc:-NYUfDwS6_2X-QLu5Ffd:b8x3uwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_test.go#L1228)):*
> ```Go
> 		skippedRanges := make(map[string]bool, 0)
> 
> 		var shouldFilter int32 = 1
> ```

might as well use atomic.Int32
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYUfKNyCuUX4TIARGgc:-NYUfKNyCuUX4TIARGgd:b-j6rd9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_test.go#L1266)):*
> ```Go
> 
> 		testutils.SucceedsSoon(t, func() error {
> 			count := laggingRanges.Value()
> ```

nice test.


<!-- Sent from Reviewable.io -->

2023-06-22 14:47 UTC, samiskin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, @renatolabs, and @smg260)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNgul6p7BDjK9rdkY:-NYYZT7-48Liwt_J-xXc:b-7bpkr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L96)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: lastHealthCheck might be a better name?
</blockquote></details>

Changed to `lastRangeHealthCheck`
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1571 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTOxv61jOnDnft0D32:-NYYPfhkE_KiBMFU4uUn:b-p5wtux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L1571)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't think ranges is in the ascending timestamp order (and neither is ca.frontier).
</blockquote></details>

Oh whoops I meant to say "key order", where frontier uses tree.Do which is in "nondecreasing order of interval start", and the range iterator is by default Ascending
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTigO46tZBp6cdlfy4:-NYYQT0UCYBX1zJFQEXI:b-8hinaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L1573)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

In general, I'm a fan of exporting "basic" stats (number of ranges, number of unhealthy ranges) and relying on grafana to determine derivative metrics (like health percentage).

In this case, however, there is an argument to be made to export derivative metric (health %-ge) directly.
In a happy case, we expect that frontier is up to date, and that nothing is behind.  Only if we know we have ranges that are behind do we need to go through the trouble of figuring the rest out.  I.e. the work you do above -- namely, kvfeed.AllRangeSpans call -- is wasted in majority cases.

I understand that this computation doesn't happen often -- but it does happen every 10 minutes; meaning that every 10 minutes or so, there will be a non-insignificant dip in changefeed aggregator performance because every 10 minutes a call that used to take next to nothing (advance frontier) will suddenly take longer, perhaps significantly longer if kvfeed.AllRangeSpans call returns large number of spans (span iterator is not free).

If we are to export derivative metrics, then, the logic becomes -- peek span frontier -- if it's up to date, then we export 1.0; otherwise, we get all ranges, and execute this logic.

An alternative (to exporting derivative metrics) is to try to do what you're doing.. but in a cheap(er) way.
I'm just brainstorming here, so use some "salt shaker".

This function is called whenever noteResolvedSpan is called.  The nice thing about noteResolvedSpan method is that it is called with a ResolvedSpan argument -- but it's actually not a span -- it's a range. We can maintain a list of ranges, which we refresh (reset) whenever frontier advances.  We only really need to have a map[string]->struct{} to keep track of the starting key of the range.
(this map maybe initialized at start to contain initial key map -- or perhaps find a way to piggy back on kvfeed so that we don't call AllRangeSpans multiple times; probably okay though to call it here).
So, we'll basically know an almost up to date count of ranges and their starting key.
So, periodically, Peek at the frontier span -- if it's old, then determine how many ranges are old.
For each range start key -- call frontier.SpanEntries(Span{startKey, startKey + 1}).   Determine if the intersection is old or not.  Update metric appropriately.


</blockquote></details>

I like the idea of only running this when the frontier is behind cause I can still maintain the validity of the "unhealthy ranges" metric, which is the one I really care about, while converting total_ranges to healthy % since I can just return 1 for normal case as you said.

I didn't want to do just healthy % because if there was just 1 unhealthy range it would be hard to notice on a graph.

If its acceptable to call AllRangeSpans in the unhealthy case, the resolvedSpan idea sounds a little too involved to be worth it to me.
___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNRvE-UCxGLS1-8qw:-NYYZ_1W6YnHtPDYF8-8:b-ubtkds) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeedbase/settings.go#L95)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It's not "Log" frequency per say, is it? 
</blockquote></details>

Changed to `range_health_check_frequency`
___
*[`pkg/ccl/changefeedccl/changefeedbase/settings.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTNVaH-ZQpinfYoz_I:-NYYZY1b18EXOG9A3Oq3:brhasxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeedbase/settings.go#L109)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

lower it perhaps?  
</blockquote></details>

Lowered to 5 minutes


<!-- Sent from Reviewable.io -->

2023-06-22 15:08 UTC, samiskin commented
@miretskiy Actually I changed my mind to make it `lagging_range_percentage` instead so that it's not weirdly a value that's 0 while you haven't ran any changefeeds yet and then suddenly 1 once you start one.  Would rather it be a value that's normally 0 and you can alert on it ever rising.

2023-06-22 16:59 UTC, miretskiy reviewed
OKay; you probably need to update graphs/description.

> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-:-NYYz52z6p1rQ4aeKvpE:bj2dkm6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @renatolabs, @samiskin, and @smg260)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1573 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYTigO46tZBp6cdlfy4:-NYZ1oJlAgzhi7FBuv9_:b-94la4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_processors.go#L1573)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

I like the idea of only running this when the frontier is behind cause I can still maintain the validity of the "unhealthy ranges" metric, which is the one I really care about, while converting total_ranges to healthy % since I can just return 1 for normal case as you said.

I didn't want to do just healthy % because if there was just 1 unhealthy range it would be hard to notice on a graph.

If its acceptable to call AllRangeSpans in the unhealthy case, the resolvedSpan idea sounds a little too involved to be worth it to me.
</blockquote></details>

I don't know how involved it is really... keeping track of map[string]=>struct doesn't sound bad...
But okay.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1556 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYYzhZtEualEI-KdyE7:-NYYzhZtEualEI-KdyE8:b-d0nsxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c450b1656a638f03a19838c906264aa1f7b8394/pkg/ccl/changefeedccl/changefeed_processors.go#L1556)):*
> ```Go
> 
> 	// Don't bother calling the expensive AllRangeSpans if we know nothing is unhealthy
> 	if timeutil.Since(ca.frontier.Frontier().GoTime()) < lagThreshold {
> ```

lagThreshold could be 0; I don't think we'd want to run this operation every time.
Perhaps 0 should mean: disable
(if you agree -- please update setting description to indicate that 0 disables)
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1584 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYZ-bDF4DIB7tDrxk5C:-NYZ-bDF4DIB7tDrxk5D:b6btkug) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c450b1656a638f03a19838c906264aa1f7b8394/pkg/ccl/changefeedccl/changefeed_processors.go#L1584)):*
> ```Go
> 		for rangeIdx < len(ranges) && !sp.Overlaps(ranges[rangeIdx]) {
> 			rangeIdx++
> 		}
> ```

This logic seems to be a bit ... strange.  Not obvious from the code if it's correct or not...
How would you feel if you were to refactor kvfeed.AllRangeSpans into something like:
```
func ForEachSpanRanges(ctx context.Context, ds *kvcoord.DistSender, spans []roachpb.Span, onRange func(r *roachpb.RangeDescriptor) {
  ...
}
```
Have AllRangeSpans call ForEachSpanRanges to built up its list of ranges, etc.

Here, you can then do something like:
```

// return frontier for the specified range.
rangeFrontier := func(sp roachpb.Span) (result hlc.Timestamp) {
    frontier.SpanEntris(sp, func(s roachpb.Span, ts hlc.Timestamp) (done span.OpResult) {
		if result.IsEmpty() || result.Less(ts) {
                    result = ts
                 }
		return span.ContinueMatch
	})
    return result
}

numRanges := 0
behindRanges := 0

kvfeed.ForEachSpanRanges(...., func(r *roachpb.RangeDescriptor) {
   numRanges++
   if rangeFrontier(....) < threshold {
      behindRanges++
   }
}
...
```


<!-- Sent from Reviewable.io -->

2023-08-09 17:42 UTC, shermanCRL commented
What are we waiting on here?

2023-08-09 17:45 UTC, samiskin commented
Just a little more dev, working on it right now

2023-08-15 14:12 UTC, miretskiy commented
@samiskin any updates on this PR?

2023-08-28 15:05 UTC, samiskin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105280)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, @renatolabs, and @smg260)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1584 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYZ-bDF4DIB7tDrxk5C:-NcweQHO82wGEwcZzmnP:b-jvk76v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ab1b02b8f9dcd89425dde5af8d0849c211cf90f/pkg/ccl/changefeedccl/changefeed_processors.go#L1584)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This logic seems to be a bit ... strange.  Not obvious from the code if it's correct or not...
How would you feel if you were to refactor kvfeed.AllRangeSpans into something like:
```
func ForEachSpanRanges(ctx context.Context, ds *kvcoord.DistSender, spans []roachpb.Span, onRange func(r *roachpb.RangeDescriptor) {
  ...
}
```
Have AllRangeSpans call ForEachSpanRanges to built up its list of ranges, etc.

Here, you can then do something like:
```

// return frontier for the specified range.
rangeFrontier := func(sp roachpb.Span) (result hlc.Timestamp) {
    frontier.SpanEntris(sp, func(s roachpb.Span, ts hlc.Timestamp) (done span.OpResult) {
		if result.IsEmpty() || result.Less(ts) {
                    result = ts
                 }
		return span.ContinueMatch
	})
    return result
}

numRanges := 0
behindRanges := 0

kvfeed.ForEachSpanRanges(...., func(r *roachpb.RangeDescriptor) {
   numRanges++
   if rangeFrontier(....) < threshold {
      behindRanges++
   }
}
...
```

</blockquote></details>

I moved the code into a frontier.countLaggingSpans function which I then tested more closely in a `TestFrontierCountLaggingRanges` test

I didn't want to do the refactor you mentioned because I liked that I would only have to do one O(n) pass over each list the way I set it up.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYUfDwS6_2X-QLu5Ffc:-NcwfOsfCbr0bIumgXrV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_test.go#L1228)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

might as well use atomic.Int32
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 1266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105280#-NYUfKNyCuUX4TIARGgc:-NcwfP8fCQmaZyX9KOU-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd3dd524f18ec99a73a06ed689bad02cb9a3221/pkg/ccl/changefeedccl/changefeed_test.go#L1266)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nice test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 15:26 UTC, miretskiy commented
bors r-

2023-09-14 16:04 UTC, jayshrivastava commented
Merged https://github.com/cockroachdb/cockroach/pull/108757 instead of this

2023-09-14 16:04 UTC, closed without merging