server: close net.Conn unconditionally after accepting
cockroachdb/cockroach pull request #106072
Opened 2023-07-03 17:20 UTC by ecwall

Previously after the server accepted a connection, it was closed in multiple paths and in multiple layers after it was done being used. Now it is always closed in the same layer that accepted it after the serveConn callback returns.

Release note: None

2023-07-03 17:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/106072)
<!-- Reviewable:end -->

2023-07-05 20:20 UTC, knz requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/pgwire/pre_serve.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbgklNENKLDYYDCvc0:-NZbgklO0ZeyEHZBb7FO:b6jo63p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a52d92bae9e87f9fa6a6635d80f4185035340b/pkg/sql/pgwire/pre_serve.go#L220)):*
> ```Go
> 
> 	_ = s.sendErr(ctx, s.st, conn, err)
> 	_ = conn.Close()
> ```

If you remove this one you need to edit the code in `pkg/server/server_controller_sql.go` to close the conn after `sendSQLRoutingError` is called (on the error path).
___
*[`pkg/sql/pgwire/pre_serve.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbhBUlD-Q0HP8G5n-U:-NZbhBUm-QttIF9jna3W:b-3wzymh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba397b6a2dc77530bac1afc2923c9b137d50944/pkg/sql/pgwire/pre_serve.go#L332)):*
> ```Go
> 		} else {
> 			return conn, st, errors.New("cannot read cancel key")
> 		}
> ```

I'm noticing there is a bug here from when I refactored this:
when `readCancelKey` returns without error, the code here should still `return` inconditionally. The code under the `switch` becomes invalid.

When the `conn.Close` was still there (before your change) the bug was invisible, it would just result in some bogus error in the first read below the `switch`. But now you're not closing the conn any more the bug becomes apparent.
___
*[`pkg/sql/pgwire/pre_serve.go` line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbhW2M6QMhx9L-FtEu:-NZbhW2M6QMhx9L-FtEv:b-lsgga3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba397b6a2dc77530bac1afc2923c9b137d50944/pkg/sql/pgwire/pre_serve.go#L379)):*
> ```Go
> 				State:     PreServeCancel,
> 				CancelKey: key,
> 			}, nil
> ```

ditto cancel
___
*[`pkg/util/netutil/net.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbgWeG8BlFZwUg1yjk:-NZbgWeG8BlFZwUg1yjl:b-iuoo3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba397b6a2dc77530bac1afc2923c9b137d50944/pkg/util/netutil/net.go#L187)):*
> ```Go
> 		err := s.stopper.RunAsyncTask(ctx, "tcp-serve", func(ctx context.Context) {
> 			defer func() {
> 				_ = rw.Close()
> ```

Are you sure about this? Why does this need to change?


<!-- Sent from Reviewable.io -->

2023-07-07 11:47 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/pgwire/pre_serve.go` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbgklNENKLDYYDCvc0:-NZk4un91yboi9Tk3Eh6:b-7n96pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5a52d92bae9e87f9fa6a6635d80f4185035340b/pkg/sql/pgwire/pre_serve.go#L220)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

If you remove this one you need to edit the code in `pkg/server/server_controller_sql.go` to close the conn after `sendSQLRoutingError` is called (on the error path).
</blockquote></details>

AFAICT the `conn net.Conn` param of `serverController.sqlMux` always comes from `TCPServer.ServeWith` so it will be closed after the `serveConn func(context.Context, net.Conn)` callback completes.
___
*[`pkg/sql/pgwire/pre_serve.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbhBUlD-Q0HP8G5n-U:-NZk8ElS-oHiS0lHjhHQ:b-rorbsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba397b6a2dc77530bac1afc2923c9b137d50944/pkg/sql/pgwire/pre_serve.go#L332)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm noticing there is a bug here from when I refactored this:
when `readCancelKey` returns without error, the code here should still `return` inconditionally. The code under the `switch` becomes invalid.

When the `conn.Close` was still there (before your change) the bug was invisible, it would just result in some bogus error in the first read below the `switch`. But now you're not closing the conn any more the bug becomes apparent.
</blockquote></details>

Maybe I am misunderstanding, but the code under the switch will never run because either the `if` returns or the `else` returns. I can remove the `else` if you like, but that is just a code style change.
___
*[`pkg/util/netutil/net.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbgWeG8BlFZwUg1yjk:-NZk8hivEmlMZ7zMbDLM:b-ij21c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ba397b6a2dc77530bac1afc2923c9b137d50944/pkg/util/netutil/net.go#L187)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Are you sure about this? Why does this need to change?
</blockquote></details>

I was having trouble following where the connection was being closed because it happens in many different layers in different branches (it is also hard to tell if every single branch ends up closing it somewhere).

I think we can always do it here instead and the various layers inside `serveConn(ctx, rw)` just need to return in order for the connection to end up closing instead of being coupled to closing it directly.

There are other resources we create in the server that I think could follow the same pattern to reduce the chance of it not being closed properly (either a branch is missing the `resource.close()` call or panic happens - the defer will be called regardless) and to reduce coupling between the various layers of `useResource(resource)` and the resource's lifecycle.
```
resource := createResource()
defer resource.close()
useResource(resource)
```


<!-- Sent from Reviewable.io -->

2023-07-07 13:08 UTC, knz approved these changes
I did a double take the first time around but thanks to Evan's explanation all became clear.
LGTM - but @rafiss pls have a look too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-:-NZkSpRUBPgzqSYHbTxM:b-xxly1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/sql/pgwire/pre_serve.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbhBUlD-Q0HP8G5n-U:-NZkSW3LAcg7e_RRPEe7:bynfctc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be76e67dab868fb016eba381a36d7dd0ee4dda5/pkg/sql/pgwire/pre_serve.go#L332)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Maybe I am misunderstanding, but the code under the switch will never run because either the `if` returns or the `else` returns. I can remove the `else` if you like, but that is just a code style change.
</blockquote></details>

lol you're right. thanks.
___
*[`pkg/util/netutil/net.go` line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZbgWeG8BlFZwUg1yjk:-NZkSeMi2wt3AJkMfLsT:b-3yovdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0be76e67dab868fb016eba381a36d7dd0ee4dda5/pkg/util/netutil/net.go#L187)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

I was having trouble following where the connection was being closed because it happens in many different layers in different branches (it is also hard to tell if every single branch ends up closing it somewhere).

I think we can always do it here instead and the various layers inside `serveConn(ctx, rw)` just need to return in order for the connection to end up closing instead of being coupled to closing it directly.

There are other resources we create in the server that I think could follow the same pattern to reduce the chance of it not being closed properly (either a branch is missing the `resource.close()` call or panic happens - the defer will be called regardless) and to reduce coupling between the various layers of `useResource(resource)` and the resource's lifecycle.
```
resource := createResource()
defer resource.close()
useResource(resource)
```
</blockquote></details>

thanks for explaining.


<!-- Sent from Reviewable.io -->

2023-07-07 14:24 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/pgwire/server.go` line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZkiuUmCRoa3ChiJ2zC:-NZkiuUmCRoa3ChiJ2zD:b-cmw8pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda82c5283063dc54c954bedadda8580e27dea8/pkg/sql/pgwire/server.go#L1263)):*
> ```Go
> 	telemetry.Inc(sqltelemetry.CancelRequestCounter)
> 	backendKeyDataBits, err := buf.GetUint64()
> 	// The connection that issued the cancel is not a SQL session -- it's an
> ```

i think this one might be an undesired change. the idea here was that for cancel requests, we immediately close the connection before processing the request. the reason is that the pgwire cancel protocol is unauthenticated, so we don't want to reveal whether the request is being processed or not, which after this change can be inferred based on how long it takes for the server to close the connection


<!-- Sent from Reviewable.io -->

2023-07-07 18:18 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`pkg/sql/pgwire/server.go` line 1263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-NZkiuUmCRoa3ChiJ2zC:-NZlYhlpE2VW7dS91xL3:b-m4svq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dda82c5283063dc54c954bedadda8580e27dea8/pkg/sql/pgwire/server.go#L1263)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this one might be an undesired change. the idea here was that for cancel requests, we immediately close the connection before processing the request. the reason is that the pgwire cancel protocol is unauthenticated, so we don't want to reveal whether the request is being processed or not, which after this change can be inferred based on how long it takes for the server to close the connection
</blockquote></details>

That's good to know. It looks like `serverController.sqlMux()` was already handling this by wrapping the cancelations in `RunAsyncTask`. I changed `SQLServerWrapper.serveConn()` to match this behavior and added comments to each based on what you wrote.

IMO this is better than calling `conn.close()` directly because it achieves the same thing without being tied to the connection lifecycle.


<!-- Sent from Reviewable.io -->

2023-07-07 19:11 UTC, rafiss approved these changes
ty!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106072#-:-NZll1jqAS9bLfFM_O_Q:b2nidcn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)



<!-- Sent from Reviewable.io -->

2023-07-07 19:59 UTC, ecwall commented
bors r=rafiss,knz

2023-07-07 20:46 UTC, merged