ui: fix crash on key visualizer
cockroachdb/cockroach pull request #106323
Opened 2023-07-06 18:39 UTC by maryliag

Fixes #106318

The value for requests response could be null, Long or number, and depending on the format it could cause a crash when trying to convert the value to number.
This commit does the correct checks and conversion to number.

Release note (bug fix): Key Visualizer not longer crashes with invalid conversion to int message.

2023-07-06 18:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/106323)
<!-- Reviewable:end -->

2023-07-06 18:58 UTC, zachlite approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106323#-:-NZgZR39Eg6zIhsRRGLs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)



<!-- Sent from Reviewable.io -->

2023-07-06 20:10 UTC, xinhaoz approved these changes

2023-07-06 20:49 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106323)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106323#gh-1254814074:-NZgxke8CkX8Rovd5rlc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a17607d98531637893a82be10f4b2cdad03e5/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L37)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

prefer `===`
</blockquote></details>

done
___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106323#gh-1254814244:-NZgxlHi-Y84I8hP4gON:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a17607d98531637893a82be10f4b2cdad03e5/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L41)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

nit: prefer `??`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-07-06 21:12 UTC, zachlite requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106323)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106323#-NZh21jpAOAkuV4nbeMh:-NZh21jpAOAkuV4nbeMi:b-t69uup) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4f753514526687fd1649a5f73af0e5f8b8e2b08/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L48)):*
> ```XML
>   for (const sample of samples) {
>     for (const stat of sample.buckets) {
>       const numRequests = this.getRequestsAsNumber(stat.requests);
> ```

We need to remove `this`, since `getRequestsAsNumber` is just a plain old function now.


<!-- Sent from Reviewable.io -->

2023-07-06 21:31 UTC, zachlite approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106323#-:-NZh6aC_-pjbDiecZP24:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh, @maryliag, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2023-07-07 00:28 UTC, maryliag commented
TFTR!
bors r+

2023-07-07 01:05 UTC, merged