roachprod: Add DNS support for services
cockroachdb/cockroach pull request #106497
Opened 2023-07-10 09:29 UTC by herkolategan

This change lays the foundation for adding DNS providers to `roachprod`. It is required to be able to keep track of multiple services that are running on the same VM. For example running multiple external process tenants on the same host. A service denotes a unit of functionality provided though a given host and port (e.g., a SQL port serving a specific tenant).

An implementation for local clusters is introduced as well as an interface for managing DNS records. The local implementation does not use true DNS services, but emulates it through local storage. This is to avoid the complexities of a per operating system implementation for local-only DNS resolution. The feature is currently disabled for cloud clusters. Once a DNS cloud provider implementation is done for the interface the feature can be enabled more widely.

Each VM needs to have a public DNS name for the DNS `services` functionality to work. The typical layout of DNS records for services pertaining to a cluster will look as follows:

<tenant>.<service>.<cluster>.<zone> -> host:port
For example:
```
system.sql.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (26257)
system.sql.cluster-name.roachprod-managed.crdb.io -> cluster-name-0002.roachprod.crdb.io : sql port (26257)
system.sql.cluster-name.roachprod-managed.crdb.io -> cluster-name-0003.roachprod.crdb.io : sql port (26257)
````

When multiple tenants are running on the same VM (0001) the records will take this form:
```
tenant1.sql.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (29001)
tenant2.sql.cluster-name.roachprod-managed.crdb.io -> cluster-name-0001.roachprod.crdb.io : sql port (29002)
````
Note the DNS SRV records here point to the same host, but different ports.

Services will also need to find open ports on VMs when multiple services are running on the VM to avoid a port collision. To facilitate this a new script has been added to scan for open ports given a starting port. Having nondeterministic ports introduces a dependency on the DNS service to be able to determine which services are running on which ports. For now a fallback is provided to supply the default ports if no DNS provider is present.

It is now possible to specify ports for SQL and UI services via `StartOpts`. These ports are used when registering DNS records against a DNS provider. This provides the functionality to not only start external service processes on different ports, but the host cluster as well. To facilitate this the port resolution is done prior to starting a cluster, as nodes need the information beforehand to be able to join the cluster.

Epic: CRDB-18499

2023-07-10 09:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/106497)
<!-- Reviewable:end -->

2023-08-09 21:32 UTC, renatolabs reviewed
Nice work! Left some questions, mostly trying to understand how all the pieces fit together.

Random question: is there a specific reason for the underscore characters in the domains (e.g., `_system-sql._tcp....`)? Are you planning to implement cloud providers next?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-:-NbRCAba1z0pejy9P7cr:bj5ig5z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

___
*[`pkg/roachprod/install/cockroach.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbQxKU47fucO16HVmjG:-NbQxKU47fucO16HVmjH:b-ul1754) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L271)):*
> ```Go
> 	}
> 	// Local clusters do not support specifying ports. An error is returned if we
> 	// detect that they were set.
> ```

Does this mean that if a test _does_ intend to specify a custom port, the only way to do that is to gate it on `cloud != Local`?
___
*[`pkg/roachprod/install/services.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR5vDMCHljeSq61IJ8:-NbR5vDMCHljeSq61IJ9:b-1l9tg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L126)):*
> ```Go
> func (c *SyncedCluster) DiscoverServices(
> 	nodes Nodes, tenantName string, serviceType ServiceType,
> ) ([]ServiceDesc, error) {
> ```

`ServiceDescriptors`?
___
*[`pkg/roachprod/install/services.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR7DGdAdiZkL_YSKb1:-NbR7DGdAdiZkL_YSKb2:b-x06jyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L175)):*
> ```Go
> 	// Finally, fall back to the default ports if no services are found. This is
> 	// useful for backwards compatibility with clusters that were created before
> 	// the introduction of service discovery, or without a DNS provider.
> ```

Does it mean that we want to eventually remove this code? 
___
*[`pkg/roachprod/install/services.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR7QQK6HgCMMqj4MHr:-NbR7QQK6HgCMMqj4MHs:b-876v98) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L183)):*
> ```Go
> 		case ServiceTypeUI:
> 			port = config.DefaultAdminUIPort
> 		}
> ```

Should we return an error on the `default` clause?
___
*[`pkg/roachprod/install/services.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR6WJLBKxXrdDpUBW-:-NbR6WJLBKxXrdDpUBW0:btu3xgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L193)):*
> ```Go
> 	}
> 
> 	// If there are multiple services, prefer the one with the highest priority.
> ```

(I'm probably reading this PR in a strange order), but when I was reviewing the implementation of the `local` provider, I don't remember anything about priority. Where in the contract is this specified? Also, I'm curious about a scenario where we would have multiple services with different priorities?
___
*[`pkg/roachprod/install/services.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR239nBBVfzrKq0N-S:-NbR239nBBVfzrKq0N-T:b4b8m4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L289)):*
> ```Go
> 		// For local clusters, we need to keep track of the ports we've already used
> 		// so that we don't use them again, when this function is called in
> 		// parallel.
> ```

Took me a while to understand how this logic works, and it's quite unfortunate. I unfortunately don't have a better idea to deal with this off the top of my head.

Also, if I understand it right, there's still a more general race (regardless of `local`) if two concurrent `roachprod` calls tried to start the same cluster, yes? Fixing _that_ race seems more difficult and probably not worthwhile.
___
*[`pkg/roachprod/install/services.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR3vIb8dZPPmEFFwxX:-NbR3vIb8dZPPmEFFwxY:b47zeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L294)):*
> ```Go
> 			for _, p := range ports {
> 				if p >= localClusterPortCache.offset {
> 					localClusterPortCache.offset = p + 1
> ```

Aren't these port numbers guaranteed to be in increasing order? Could we set `offset` to `lastPort + 1`?

(PS: `offset` doesn't sound like a great name since it's storing a `start port`, not an offset.)
___
*[`pkg/roachprod/install/services.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR4usI3JI5911k6LHM:-NbR4usI3JI5911k6LHN:b-4uc1rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L317)):*
> ```Go
> 	res, err := c.runCmdOnSingleNode(ctx, l, node, buf.String(), false, l.Stdout, l.Stderr)
> 	if err != nil || res.Err != nil {
> 		return nil, errors.CombineErrors(err, res.Err)
> ```

I thought the contract of `runCmdOnSingleNode` was that you didn't have to use this sort of `CombineErrors`.
___
*[`pkg/roachprod/install/services.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR4hTh14uNjeuIld-x:-NbR4hTh14uNjeuIld-y:b-zi7cl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L319)):*
> ```Go
> 		return nil, errors.CombineErrors(err, res.Err)
> 	}
> 	ports, err = stringToIntegers(strings.TrimPrefix(res.Stdout, "open ports:"))
> ```

Nit: I'd probably drop the `open ports:` prefix and let the script communicate its success via exit codes. This creates an unnecessary coupling between the script and this logic.
___
*[`pkg/roachprod/install/scripts/open_ports.sh` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbQzHugD-BT6-3v-CQ9:-NbQzHugD-BT6-3v-CQA:b-keisit) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/scripts/open_ports.sh#L21)):*
> ```Shell
> 
> set +e
> for ((port = start_port; port <= 65535; port++)); do
> ```

We probably want to avoid ports in the ephemeral range? (see #107551).
___
*[`pkg/roachprod/install/scripts/open_ports.sh` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR4V0A8KOUvip-6E_h:-NbR4V0A8KOUvip-6E_i:b-leh0nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/scripts/open_ports.sh#L22)):*
> ```Shell
> set +e
> for ((port = start_port; port <= 65535; port++)); do
>   if ! lsof -i :"$port" >/dev/null 2>&1; then
> ```

Is `lsof` something that is generally available on all Linux distributions?
___
*[`pkg/roachprod/vm/dns.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbRBRUu2G-W2hAQmBA9:-NbRBRUu2G-W2hAQmBAA:bi0d0d2) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/vm/dns.go#L58)):*
> ```Go
> // FanOutDNS collates a collection of VMs by their DNS providers and invoke the
> // callbacks in parallel. This function is lenient and skips VMs that do not
> // have a DNS provider or if the provider is not a DNSProvider.
> ```

Is this because we haven't implemented cloud providers yet? Do we plan to make these errors "real" errors in the future?

Specially curious about the interface cast below -- looks like a bad error to swallow.


<!-- Sent from Reviewable.io -->

2023-08-10 14:41 UTC, smg260 requested changes
> Reviewed 3 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106497)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cluster_init.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUmP2J8FRgNgjGs53e:-NbUmP2J8FRgNgjGs53f:b-5n8owh) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/cmd/roachtest/tests/cluster_init.go#L44)):*
> ```Go
> 		c.Wipe(ctx, false /* preserveCerts */)
> 		t.L().Printf("starting test with init node %d", initNode)
> 		startOpts := option.DefaultStartOpts()
> ```

Can `startOpts` be lifted?
___
*[`pkg/roachprod/install/cockroach.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUo6Qu4l3021Us6oXJ:-NbUo6Qu4l3021Us6oXK:b-1yluaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L116)):*
> ```Go
> 	// SQLPort is the port on which the cockroach process is listening for SQL
> 	// connections. Specifying 0 will find an open port.
> 	SQLPort int
> ```

Nit: Perhaps specify "default" over "0" in the comments.  e.g. 

`//Default (0) will find an open port.
___
*[`pkg/roachprod/install/cockroach.go` line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUq9HY1dZw0pWRiJMg:-NbUq9HY1dZw0pWRiJMh:bsmhb6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L715)):*
> ```Go
> 		joinTargets := startOpts.GetJoinTargets()
> 		addresses := make([]string, len(joinTargets))
> 		for i, joinNode := range startOpts.GetJoinTargets() {
> ```

nit: looks like `i` is unreferenced.
___
*[`pkg/roachprod/vm/local/dns.go` line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUssM159JRrMrGkpUY:-NbUssM22qNMfQQtRQub:bjrpcm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/vm/local/dns.go#L168)):*
> ```Go
> // operations or roachprod processes that access shared system resources do
> // not conflict.
> func (n *dnsProvider) acquireFilesystemLock() (unlockFn func(), _ error) {
> ```

This func exists a couple of levels up in `roachprod.go` - might it be worth to refactor to somewhere accessible to both?


<!-- Sent from Reviewable.io -->

2023-08-15 17:00 UTC, herkolategan reviewed
Regarding the underscores https://en.wikipedia.org/wiki/SRV_record. It stems from the SRV record convention https://datatracker.ietf.org/doc/html/rfc2782.
As for providers, I already have a draft for Cloud Providers, specifically Google Cloud DNS.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-:-NbUBl-W2Jx8xXiZ6dAE:b-pbwfyd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachtest/tests/cluster_init.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUmP2J8FRgNgjGs53e:-Nbn68fP7vVvOaq_n-w9:b-pohpth) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/cmd/roachtest/tests/cluster_init.go#L44)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Can `startOpts` be lifted?
</blockquote></details>

Looks like it, good catch. Done.
___
*[`pkg/roachprod/install/cockroach.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUo6Qu4l3021Us6oXJ:-Nbn6B7uEL-Q12bgGV65:b-5hy0q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L116)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Nit: Perhaps specify "default" over "0" in the comments.  e.g. 

`//Default (0) will find an open port.
</blockquote></details>

Good point, makes it clearer. Done.
___
*[`pkg/roachprod/install/cockroach.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbQxKU47fucO16HVmjG:-NbU33Y22cu6Vw_pHpp1:bu93a9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L271)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Does this mean that if a test _does_ intend to specify a custom port, the only way to do that is to gate it on `cloud != Local`?
</blockquote></details>

Yes, and it's probably not ideal. I've thought about making an exception when starting a single node. The other option would be to allow specifying multiple ports for multiple nodes in the `Start` call, or maybe some virtualisation layer for local ports.
___
*[`pkg/roachprod/install/cockroach.go` line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbUq9HY1dZw0pWRiJMg:-Nbn6lodDS_ncF4k1Yua:b-ochwld) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/cockroach.go#L715)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

nit: looks like `i` is unreferenced.
</blockquote></details>

referenced in `addresses[i]` below to fill the array.
___
*[`pkg/roachprod/install/services.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR5vDMCHljeSq61IJ8:-NbU4J_T0ZTCvSwlMziD:b-3ts12f) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L126)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

`ServiceDescriptors`?
</blockquote></details>

Yes! Done. And spotted another instance, also updated.
___
*[`pkg/roachprod/install/services.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR7DGdAdiZkL_YSKb1:-NbU4OdLD5QRET8vUb0M:b-2weuyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L175)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Does it mean that we want to eventually remove this code? 
</blockquote></details>

Ideally yes, if we intend to rely fully on DNS we should error if the service is not found. I want to eventually have the confidence to make those changes, but to prevent disruption only after we are sure the DNS code and Cloud DNS is stable. Once a Cloud DNS provider implementation is merged, I'll add a warning here to track it (I'll add a TODO now as well so I remember).
___
*[`pkg/roachprod/install/services.go` line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR7QQK6HgCMMqj4MHr:-NbU52I43qE64Mmir19E:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L183)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Should we return an error on the `default` clause?
</blockquote></details>

Good idea. Done.
___
*[`pkg/roachprod/install/services.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR6WJLBKxXrdDpUBW-:-NbU54j00bXC5KdJhgXB:b-6il8c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L193)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

(I'm probably reading this PR in a strange order), but when I was reviewing the implementation of the `local` provider, I don't remember anything about priority. Where in the contract is this specified? Also, I'm curious about a scenario where we would have multiple services with different priorities?
</blockquote></details>

We probably have no use for different priorities. I at one point thought I should sort on priority for records returned by the underlying DNS, but it's not of much use for us at this point. I'll remove the comment, and update it to reflect that it will arbitrarily select the first service when multiple services are available.
___
*[`pkg/roachprod/install/services.go` line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR239nBBVfzrKq0N-S:-NbU6U6KAGTsJm85RYbJ:b-f47sn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L289)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Took me a while to understand how this logic works, and it's quite unfortunate. I unfortunately don't have a better idea to deal with this off the top of my head.

Also, if I understand it right, there's still a more general race (regardless of `local`) if two concurrent `roachprod` calls tried to start the same cluster, yes? Fixing _that_ race seems more difficult and probably not worthwhile.
</blockquote></details>

Noted, I'll make a comment.
___
*[`pkg/roachprod/install/services.go` line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR3vIb8dZPPmEFFwxX:-NbU6ilJ1AVSkbh1xcJO:b-yirsse) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L294)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Aren't these port numbers guaranteed to be in increasing order? Could we set `offset` to `lastPort + 1`?

(PS: `offset` doesn't sound like a great name since it's storing a `start port`, not an offset.)
</blockquote></details>

True, can just use the last port. I'll also update the naming as you're right it's not an offset.
___
*[`pkg/roachprod/install/services.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR4usI3JI5911k6LHM:-NbU75zP8SUxguFePQje:b-fsn5mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L317)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I thought the contract of `runCmdOnSingleNode` was that you didn't have to use this sort of `CombineErrors`.
</blockquote></details>

Correct, not sure what my thought process was there, let me fix that.
___
*[`pkg/roachprod/install/services.go` l [...]

2023-08-16 18:50 UTC, renatolabs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Left some questions, but they are non blocking. Feel free to address anything in this or an upcoming PR. Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-:-NbzffJ05pybuHEqB2-_:b-ts7orl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

___
*[`pkg/roachprod/install/cockroach.go` line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbzbQXY3qGXcvjXKjWU:-NbzbQXY3qGXcvjXKjWV:b87cpay) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8415bf029ec38c97aed8be87750c37bb46e0e4/pkg/roachprod/install/cockroach.go#L277)):*
> as these have not been specified explicitly by the user.

When are these variables set to their default values? Might be worth being more explicit in the comments.
___
*[`pkg/roachprod/install/services.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR6WJLBKxXrdDpUBW-:-Nbzash_-fgC0w-ecorE:byil7oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L193)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

We probably have no use for different priorities. I at one point thought I should sort on priority for records returned by the underlying DNS, but it's not of much use for us at this point. I'll remove the comment, and update it to reflect that it will arbitrarily select the first service when multiple services are available.
</blockquote></details>

I'm still not clear on _when_ multiple services could exist. Is there a correct execution that could lead to this situation? If not, it sounds like it would be better to return an error than a potentially wrong `ServiceDesc` which could lead to confusing test failures.
___
*[`pkg/roachprod/vm/dns.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbRBRUu2G-W2hAQmBA9:-NbzfN8a-UC_yXIu_jMs:b-cdu9jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/vm/dns.go#L58)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Real errors are the next step here, once there is a Cloud DNS provider. I planned on doing this in parts so the PRs are reasonably sized, hence allowing the feature not to be on here without an error for now.
Having said that the empty DNSProvider is the only lenient check that is needed, and if that is set to a provider that doesn't implement it, it should definitely error. I'll update.
</blockquote></details>

It doesn't seem like this was updated? I still see `return nil` if the interface is not implemented.
___
*[`pkg/roachprod/vm/dns.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbzeoS79yueaK2oPonl:-NbzeoS79yueaK2oPonm:b-dkpzyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8415bf029ec38c97aed8be87750c37bb46e0e4/pkg/roachprod/vm/dns.go#L94)):*
> ```Go
> // action. If lenient is true, then the action is not executed if the provider
> // is not specified or not a DNSProvider, and no error is returned.
> func ForDNSProvider(named string, action func(DNSProvider) error, lenient bool) error {
> ```

It seems like there's currently only one caller of `ForDNSProvider`, which uses `lenient=true`. Couple of questions:

* Do we need to make this a parameter at all?
* (This is more about the `ForDNSProvider` caller): seems like this check is not really necessary since, by construction, we're skipping empty providers.

TLDR: might be simpler to just remove the `lenient` parameter altogether.


<!-- Sent from Reviewable.io -->

2023-08-17 10:06 UTC, herkolategan reviewed
Thanks for the feedback & reviews, very helpful!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-:-Nc1rxqA2RftEaRvU83U:b-qhafur)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @smg260)

___
*[`pkg/roachprod/install/cockroach.go` line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbzbQXY3qGXcvjXKjWU:-Nc1pBuC8YRvBt-Vz4mr:b-r2dpla) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8415bf029ec38c97aed8be87750c37bb46e0e4/pkg/roachprod/install/cockroach.go#L277)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> as these have not been specified explicitly by the user.

When are these variables set to their default values? Might be worth being more explicit in the comments.
</blockquote></details>

I'll add this to the comment. The defaults come from `roachprod.DefaultStartOpts`. This does bother me a little though, and I've thought a few times about adding something that makes it apparent the ports have been explicitly set.
___
*[`pkg/roachprod/install/services.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbR6WJLBKxXrdDpUBW-:-Nc1qaAe3RTME0UI32Ke:b-bt5olw) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/install/services.go#L193)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm still not clear on _when_ multiple services could exist. Is there a correct execution that could lead to this situation? If not, it sounds like it would be better to return an error than a potentially wrong `ServiceDesc` which could lead to confusing test failures.
</blockquote></details>

There was a discussion on the possibility of having more than one SQL instance serving the same tenant on the same VM. This is to handle that case, although not ideal. And it's currently not disallowed to start another instance for the same tenant on the same VM. The only major difference is if you then need to find both you'll need to use the `DiscoverServices` function instead. I'm not opposed to changing this to an error until we end up doing testing of that sort.
___
*[`pkg/roachprod/vm/dns.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbRBRUu2G-W2hAQmBA9:-Nc1BzDo5Ckm-CWDusUd:b-ur03ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c97fd25c2bcc5cace62bf65c8f282d8b757b2d/pkg/roachprod/vm/dns.go#L58)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

It doesn't seem like this was updated? I still see `return nil` if the interface is not implemented.
</blockquote></details>

Argghh!! My bad, I reverted something and forgot about that change. Thanks for catching it!
___
*[`pkg/roachprod/vm/dns.go` line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106497#-NbzeoS79yueaK2oPonl:-Nc1rhc77-cSCFsBQfHD:b-fbx4hx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8415bf029ec38c97aed8be87750c37bb46e0e4/pkg/roachprod/vm/dns.go#L94)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

It seems like there's currently only one caller of `ForDNSProvider`, which uses `lenient=true`. Couple of questions:

* Do we need to make this a parameter at all?
* (This is more about the `ForDNSProvider` caller): seems like this check is not really necessary since, by construction, we're skipping empty providers.

TLDR: might be simpler to just remove the `lenient` parameter altogether.
</blockquote></details>

True, I'll make the function stricter, and rely on the caller to only use available providers.


<!-- Sent from Reviewable.io -->

2023-08-21 14:39 UTC, herkolategan commented
bors r=renatorlabs,smg260

2023-08-21 14:40 UTC, smg260 approved these changes

2023-08-21 14:41 UTC, herkolategan commented
bors r=renatolabs,smg260

2023-08-21 15:17 UTC, merged