storage: avoid allocating in EngineKey.Validate
cockroachdb/cockroach pull request #106484
Opened 2023-07-08 18:25 UTC by jbowens

This function previously allocated unnecessarily, because it validated through decoding the key as both a MVCCKey and a LockTableKey and ensuring that one succeeded. If the key was a LockTableKey, `ToMVCCKey` would allocate an error (including stack traces, etc) and `ToLockTableKey` would allocate during decoding. If the key was a MVCCKey, `ToLockTableKey` would allocate an error (including stack traces, etc).

Now, Validate never allocates for valid keys and a randomized unit test ensures this.

Fix #106464.

Epic: none
Release note: none

2023-07-08 18:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/106484)
<!-- Reviewable:end -->

2023-07-10 17:50 UTC, sumeerbhola requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106484)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`pkg/storage/engine_key.go` line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-sEBZ4lrhmtTdnCpW:-N_-sEBZ4lrhmtTdnCpX:b-sd6so9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L199)):*
> ```Go
> 
> 	// It's a lock table key. Check that it has the prefix.
> 	if !bytes.HasPrefix(k.Key, keys.LocalRangeLockTablePrefix) {
> ```

nit: the rest of this code may be better placed in keys.go as a `ValidateLockTableSingleKey` function, given the similarities.
___
*[`pkg/storage/engine_key.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-qklG-7ZNupj1P2-4:-N_-qklG-7ZNupj1P2-5:bhkzwl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L212)):*
> ```Go
> 	b = b[len(keys.LockTableSingleKeyInfix):]
> 	var err error
> 	b, err = encoding.ValidateDecodeBytesAscending(b)
> ```

Was `encoding.DecodeBytesAscending` allocating despite the comment in `DecodeLockTableSingleKey`? I am trying to understand why we are not using `DecodeLockTableSingleKey`.

And was this allocation reduction needed because of the use in `Experimental.KeyValidationFunc`?


<!-- Sent from Reviewable.io -->

2023-07-11 14:13 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106484)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[`pkg/storage/engine_key.go` line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-sEBZ4lrhmtTdnCpW:-N_4HYBwDeAQSn7rHf8v:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L199)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: the rest of this code may be better placed in keys.go as a `ValidateLockTableSingleKey` function, given the similarities.
</blockquote></details>

Good call, done.
___
*[`pkg/storage/engine_key.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-qklG-7ZNupj1P2-4:-N_4GpEOCMNeyybszsBm:brfwna5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L212)):*
> Was `encoding.DecodeBytesAscending` allocating despite the comment in `DecodeLockTableSingleKey`? I am trying to understand why we are not using `DecodeLockTableSingleKey`.

Yeah, it was. Which comment are you referring to? We have no destination buffer available to pass into the second parameter, which forces `DecodeBytesAscending` to allocate.

> And was this allocation reduction needed because of the use in `Experimental.KeyValidationFunc`?

Yeah, on a large cluster with high compaction concurrency these allocations during version edit allocation showed up. They initially caught my eye because I was worried we were accidentally discarding errors about invalid keys, but it turned out that discarding was intentional.


<!-- Sent from Reviewable.io -->

2023-07-12 19:17 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-:-N_AXEFZ-UDtLEz27D61:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`pkg/storage/engine_key.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-qklG-7ZNupj1P2-4:-N_AW5zU9lEAqztkGxf0:b-63jwbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L212)):*
> Which comment are you referring to?

https://github.com/cockroachdb/cockroach/blob/7339e0f900eba75db210874612d6e5aa561c854a/pkg/keys/keys.go#L521-L524

> We have no destination buffer available to pass into the second parameter, which forces `DecodeBytesAscending` to allocate.

Since `deepCopy` is false, the allocation will "only" happen in this code https://github.com/cockroachdb/cockroach/blob/7339e0f900eba75db210874612d6e5aa561c854a/pkg/util/encoding/encoding.go#L803-L805

Anyway, the comment may have been accurate only in the limited workloads I looked at for the allocation.


<!-- Sent from Reviewable.io -->

2023-07-13 02:06 UTC, jbowens reviewed
TFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-:-N_Bzwgt3f3HTE2_XD1d:b-6zs9ju)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

___
*[`pkg/storage/engine_key.go` line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106484#-N_-qklG-7ZNupj1P2-4:-N_BzrfL01YOkT-ofyMK:bk6u2wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bf3dfadbef051f94128af716a948d28fab2eaf9/pkg/storage/engine_key.go#L212)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Which comment are you referring to?

https://github.com/cockroachdb/cockroach/blob/7339e0f900eba75db210874612d6e5aa561c854a/pkg/keys/keys.go#L521-L524

> We have no destination buffer available to pass into the second parameter, which forces `DecodeBytesAscending` to allocate.

Since `deepCopy` is false, the allocation will "only" happen in this code https://github.com/cockroachdb/cockroach/blob/7339e0f900eba75db210874612d6e5aa561c854a/pkg/util/encoding/encoding.go#L803-L805

Anyway, the comment may have been accurate only in the limited workloads I looked at for the allocation.
</blockquote></details>

Ahhh, I see.


<!-- Sent from Reviewable.io -->

2023-07-13 02:46 UTC, merged