sql: fix panic in request_job_execution_details
cockroachdb/cockroach pull request #107254
Opened 2023-07-20 12:14 UTC by adityamaru

This was fixed in  https://github.com/cockroachdb/cockroach/pull/106904 but it looks like some file movement in #105624 got rid of the nil check. This patch re-adds the nil check along with a test, and also some additional safeguards to not collect any execution details for non-existent jobs.

Fixes: #106970
Release note: None

2023-07-20 12:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/107254)
<!-- Reviewable:end -->

2023-07-20 12:39 UTC, rafiss approved these changes

2023-07-20 14:29 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[`pkg/jobs/utils.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_ngy07Eni6VH7kACxM:-N_ngy07Eni6VH7kACxN:b-lxingc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/jobs/utils.go#L148)):*
> ```Go
> func JobExists(ctx context.Context, jobID jobspb.JobID, db isql.DB) (bool, error) {
> 	var exists bool
> 	if err := db.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
> ```

hm, actually looking closer, it seems undesirable for this check to run in a separate transaction. it should run in the same txn as the one in the `evalCtx` of the builtin


<!-- Sent from Reviewable.io -->

2023-07-20 14:42 UTC, adityamaru commented
Thats a good point, I'll change the signature to accept a txn instead of an isql.DB.

2023-07-20 15:15 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[`pkg/sql/jobs_profiler_execution_details.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nrBAr88AJ42znKJh_:-N_nrBAr88AJ42znKJha:b4tsxay) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/jobs_profiler_execution_details.go#L190)):*
> ```Go
> 		return err
> 	} else if !exists {
> 		log.Warningf(ctx, "execution details requested for non-existent job %d", jobID)
> ```

don't think we need to log anything here. should we instead return a "not found" error?
___
*[`pkg/sql/sem/builtins/builtins.go` line 7724 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nrMmT9CHa14mVc5IF:-N_nrMmT9CHa14mVc5IG:b-x804gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/sem/builtins/builtins.go#L7724)):*
> ```Go
> 				}
> 
> 				if len(args) != 1 {
> ```

is this needed? this overload already defines the args list to be of size 1, so if someone provides 2 params, this overload would never be invoked.


<!-- Sent from Reviewable.io -->

2023-07-20 15:17 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[`pkg/sql/jobs_profiler_execution_details.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nruIL35qQ28UHfVoh:-N_nruIL35qQ28UHfVoi:b-qx6jep) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/jobs_profiler_execution_details.go#L179)):*
> ```Go
> func (p *planner) RequestExecutionDetailFiles(ctx context.Context, jobID jobspb.JobID) error {
> 	execCfg := p.ExecCfg()
> 	if !execCfg.Settings.Version.IsActive(ctx, clusterversion.V23_1) {
> ```

this was pre-existing, but this check seems off. shouldn't it be checking `V23_2`? or if not, then why do we need it? this code is only on master, so this check will always return true.


<!-- Sent from Reviewable.io -->

2023-07-20 17:06 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107254)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/jobs/utils.go` line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_ngy07Eni6VH7kACxM:-N_oG6g91NQ5hKYTzOBg:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/jobs/utils.go#L148)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, actually looking closer, it seems undesirable for this check to run in a separate transaction. it should run in the same txn as the one in the `evalCtx` of the builtin
</blockquote></details>

fixed
___
*[`pkg/sql/jobs_profiler_execution_details.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nruIL35qQ28UHfVoh:-N_oBac12Gdpa1kiNBBv:b-jhtkdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/jobs_profiler_execution_details.go#L179)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this was pre-existing, but this check seems off. shouldn't it be checking `V23_2`? or if not, then why do we need it? this code is only on master, so this check will always return true.
</blockquote></details>

Initially when this method was written, all we needed to ensure was that the `system.job_info` table exists. This condition would be true if we were upgraded to 23.1. Now though I'm realizing that some pieces of information that we collect (egs: labelled goroutines) will only be available on 23.2+ so it makes sense to check V23_2. Thanks for catching this!
___
*[`pkg/sql/jobs_profiler_execution_details.go` line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nrBAr88AJ42znKJh_:-N_oBUxx09fNuD3AZhY4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/jobs_profiler_execution_details.go#L190)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

don't think we need to log anything here. should we instead return a "not found" error?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 7724 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-N_nrMmT9CHa14mVc5IF:-N_oBW1aAnYAd2pfBjLg:b-9dqgpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa50c759cb54722e6d48c9a44915908c79f5d3b/pkg/sql/sem/builtins/builtins.go#L7724)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this needed? this overload already defines the args list to be of size 1, so if someone provides 2 params, this overload would never be invoked.
</blockquote></details>

not needed, removed


<!-- Sent from Reviewable.io -->

2023-07-21 03:58 UTC, rafiss approved these changes
this looks great! thanks for the fix and all the cleanup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107254#-:-N_qaDsT6zHGR-ONXo9n:bejglly)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)



<!-- Sent from Reviewable.io -->

2023-07-21 11:42 UTC, adityamaru commented
TFTR!

bors r=rafiss

2023-07-21 12:15 UTC, merged