cli: enhance diagnosing contention with redacted debug zips
cockroachdb/cockroach pull request #107355
Opened 2023-07-21 15:35 UTC by fqazi

Previously a redacted zip, we would exclude retries and key information for contended keys since they could contain PII data. This patch does the following:

- Adds a new builtin is_system_table_key which allows us to know if a key belongs to a system table
- Modified redacted debug zips to include data for system keys in contention tables conditionally (if they belong to system tables)
- Include retries and last_retry_reason information for queries in cluster insights to help diagnose contention

Fixes: #104593

2023-07-21 15:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/107355)
<!-- Reviewable:end -->

2023-07-26 14:04 UTC, chrisseto approved these changes
LGTM! I think the commit message could be a bit more motivated. Could add an example situation where this new information will be useful?

2023-07-28 04:47 UTC, rafiss requested changes
nice! just had small nits

2023-07-28 04:47 UTC, rafiss commented on pkg/sql/sem/builtins/builtins.go
> +			Volatility: volatility.Immutable,
nit: this should be stable or volatile, since this function is not deterministic.

2023-07-28 04:47 UTC, rafiss commented on docs/generated/sql/functions.md
> +<tr><td><a name="crdb_internal.is_system_table_key"></a><code>crdb_internal.is_system_table_key(raw_key: <a href="bytes.html">bytes</a>) &rarr; <a href="bool.html">bool</a></code></td><td><span class
this is an internal function, so it should not appear in the docs. use `Undocumented:     true,` on the builtin.

2023-08-01 14:47 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107355)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Santamaura)

___
*[`docs/generated/sql/functions.md` line 3231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107355#gh-1277084578:-NalZCcaCblibzQmi28e:b9qca76) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bce9061e70584b3bdd0d5c4a4bbe5c3407014fa/docs/generated/sql/functions.md#L3231)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is an internal function, so it should not appear in the docs. use `Undocumented:     true,` on the builtin.
</blockquote></details>

Done.

Good catch!


<!-- Sent from Reviewable.io -->

2023-08-02 02:18 UTC, fqazi commented
bors r+

2023-08-09 04:09 UTC, rafiss approved these changes
thanks for the improvement!

> Reviewed 2 of 6 files at r1, 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107355#-:-NbNTvHZ7cVKrj9nYKdw:bifbvs3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)



<!-- Sent from Reviewable.io -->

2023-08-09 14:09 UTC, fqazi commented
@rafiss TFTR!

2023-08-09 15:44 UTC, fqazi commented
bors r+

2023-08-09 19:39 UTC, merged