ui: add an overridable logger
cockroachdb/cockroach pull request #107718
Opened 2023-07-27 14:39 UTC by fantapop

A setLogger and getLogger method are added to cluster-ui so that the cockroach cloud console can use them to pass a custom logger which embellishes each log invocation with the cluster version and cluster id.

CC-24092

Release Note: none

2023-07-27 14:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/107718)
<!-- Reviewable:end -->

2023-07-27 16:16 UTC, sjbarag requested changes
Looking pretty good! When these components are used in the hosted product, we ship logs off to Datadog using their [error tracking features](https://docs.datadoghq.com/logs/log_collection/javascript/#error-tracking). That third param to `logger.error()` lets Datadog attach a parsed JS error (with the stack trace included) to the log line, which is suuuuper handy!

My only blockers here are on getting that error plumbed through in a few cases. There's a few docs nits too, but either way they should be pretty quick to knock out.

Thanks for putting this together @fantapop! Congrats on your first non-authors CRDB PR :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-:-NaN6R4lCrNPatGeX343:bkrmn2c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fantapop)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN2yDi6uqoAGQrB1NI:-NaN2yDi6uqoAGQrB1NJ:bpbpw0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts#L64)):*
> ```XML
> 
>   if (sqlResultsAreEmpty(result)) {
>     if (result.error) {
> ```

Bummer that `result.error` isn't evern `instanceof Error`, or we could pass it as the third parameter in `getLogger().error()`!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN38kAAKs0scPAH4y8:-NaN38kAAKs0scPAH4y9:b-abhvo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L278)):*
> ```XML
>         getLogger().error(
>           `Database Details API - encountered an error decoding zone config string: ${zoneConfigHexString}`,
>         );
> ```

`e` may be a JS `Error` here! To make sure it's captured alongside this message, let's pass it into `logger.error()` here :)



_Suggestion:_
```XML
        getLogger().error(
          `Database Details API - encountered an error decoding zone config string: ${zoneConfigHexString}`,
          /* additional context */ undefined,
          e,
        );
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN3k6VEJ6oYtWNO2qi:-NaN3k6VEJ6oYtWNO2qj:b-il0jxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts#L320)):*
> ```XML
>         getLogger().error(
>           `Table Details API - encountered an error decoding zone config string: ${hexString}`,
>         );
> ```

Ditto — `e` may be a JS `Error`, so let's pass it along!



_Suggestion:_
```XML
        getLogger().error(
          `Table Details API - encountered an error decoding zone config string: ${hexString}`,
          /* additional context */ undefined,
          e, 
        );
```
___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN3xNG29KJ2c-u183k:-NaN3xNG29KJ2c-u183l:b-zfww0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L30)):*
> ```XML
>     yield put(actions.receivedUserSQLRoles(result.roles));
>   } catch (e) {
>     getLogger().warn(e.message);
> ```

ooooooone more



_Suggestion:_
```XML
    getLogger().warn(e.message, /* extra context*/ undefined, e);
```
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN4wtp3O-nb3zJzJ7w:-NaN4wtp3O-nb3zJzJ7x:bxmr65m) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L14)):*
> ```XML
> type JSONValue = JSONPrimitive | JSONObject | JSONArray
> type JSONObject = { [member: string]: JSONValue }
> type JSONArray = JSONValue[]
> ```

Nice! If you prefer a single recursive `type`, feel free to switch to:



_Code quote (i):_
```XML
type JSONPrimitive = string | number | boolean | null
type JSONValue = JSONPrimitive | JSONObject | JSONArray
type JSONObject = { [member: string]: JSONValue }
type JSONArray = JSONValue[]
```



_Code snippet (ii):_
```XML
type JSONValue = 
  | null
  | boolean
  | number
  | string
  | JSONValue[]
  | Recorod<string, JSONValue>;
```
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN5Eo75OX0vl03_1tw:-NaN5Eo75OX0vl03_1tx:bikangm) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L20)):*
> ```XML
>     info(msg: string, context?: Record<string, JSONValue>, error?: unknown): void;
>     warn(msg: string, context?: Record<string, JSONValue>, error?: unknown): void;
>     error(msg: string, context?: Record<string, JSONValue>, error?: unknown): void;
> ```

nit: mind adding some [tsdoc comments](https://tsdoc.org/pages/tags/param/) here, mostly to document the params? I imagine something like:

```
interface Logger {
  /**
   * Logs a message with additional context and an error at a debug level.
   * @param msg - the string message to log
   * @param context - additional structured context to include with the message when shipped to a remote service
   * @param error - a possible JS Error to include with the message when shipped to a remote service
   */
}
```

That'll get us the fancy VSCode / GoLand / anything-that-uses-tsserver hover documentation :)
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN6HmZ0k_tqynh-nkD:-NaN6Hm_03NU-dfURHrS:b8cog0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L26)):*
> ```XML
> 
> // setLogger sets the logger returned by getLogger. It was added to allow
> // cockroach cloud to pass in a custom logger which attaches additional metadata
> ```

nit: tsdoc format please!
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN6K-j2herVbnGRfyB:-NaN6K-j2herVbnGRfyC:b8cog0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L33)):*
> ```XML
> 
> // getLogger returns the last logger set by setLogger.  If a logger hasn't been
> // set, console is returned.
> ```

nit: tsdoc format please!



_Code quote:_
```XML
// getLogger returns the last logger set by setLogger.  If a logger hasn't been
// set, console is returned.
```


<!-- Sent from Reviewable.io -->

2023-07-27 16:21 UTC, sjbarag commented
Looks like you had a few formatting lint failures, FWIW: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11088386?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true&showLog=11088377_3349_244.253.258.3590.3591&logFilter=debug&logView=flowAware

Good news is they're all automatically fixable. `pnpm lint:fix` in `pkg/ui/workspaces/cluster-ui` should take care of it for ya!

2023-07-28 09:30 UTC, fantapop reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107718)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN2yDi6uqoAGQrB1NI:-NaQZa--877v4xP-Syyd:b-pmo3pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts#L64)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Bummer that `result.error` isn't evern `instanceof Error`, or we could pass it as the third parameter in `getLogger().error()`!
</blockquote></details>

How do you feel about passing it into the context instead of in the message?  If we leave it in the message, it feels like we should at least stringify it.  Maybe something like:
```ts
      getLogger().error(
        'Insights encounter an error while retrieving contention information.',
        { resultError: result.error },
      );
```

One other thing I noticed is that `executeInternalSql` does throw RequestError which extends from error on any non-200 response.
https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L118-L125

It looks like those generally bubble up a few layers and are caught and then displayed directly on the page rather than being logged anywhere:

https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L131-L133

It seems like I should additionally search for any catch handlers and log errors that show up here as well.  Thoughts?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN38kAAKs0scPAH4y8:-NaQdP3IEAE0xotWlhQh:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L278)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

`e` may be a JS `Error` here! To make sure it's captured alongside this message, let's pass it into `logger.error()` here :)
</blockquote></details>

:thumbsup: 
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts` line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN3k6VEJ6oYtWNO2qi:-NaQde4X7M-V4K-0Gz9N:b-1wnqsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts#L320)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Ditto — `e` may be a JS `Error`, so let's pass it along!
</blockquote></details>

I must have had blinders on while I was adding these.  Thanks for pointing them out.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN3xNG29KJ2c-u183k:-NaQe-BW7zc_51H6BQAx:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L30)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

ooooooone more
</blockquote></details>

:thumbsup: 
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN4wtp3O-nb3zJzJ7w:-NaQfjye5kKc_8z77L5_:bwfw6ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L14)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Nice! If you prefer a single recursive `type`, feel free to switch to:
</blockquote></details>

yep, its better.  VSCode is complaining about it.  Apparently have to use object syntax though.

https://stackoverflow.com/questions/70405503/how-to-create-recursive-type#answer-70405610
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN5Eo75OX0vl03_1tw:-NaQnawa26uZRrgMPEH0:b-1we2ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L20)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

nit: mind adding some [tsdoc comments](https://tsdoc.org/pages/tags/param/) here, mostly to document the params? I imagine something like:

```
interface Logger {
  /**
   * Logs a message with additional context and an error at a debug level.
   * @param msg - the string message to log
   * @param context - additional structured context to include with the message when shipped to a remote service
   * @param error - a possible JS Error to include with the message when shipped to a remote service
   */
}
```

That'll get us the fancy VSCode / GoLand / anything-that-uses-tsserver hover documentation :)
</blockquote></details>

yeah, sounds good. I spent some time trying to make this less repetitive but didn't come up with anything as useful as just repeating it all. 
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN6HmZ0k_tqynh-nkD:-NaQpHiDCk-ccinDBFVg:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L26)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

nit: tsdoc format please!
</blockquote></details>

:thumbsup: 
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN6K-j2herVbnGRfyB:-NaQpJhD7j-pBytEVw_e:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L33)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

nit: tsdoc format please!
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2023-07-28 10:00 UTC, fantapop reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107718)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN2yDi6uqoAGQrB1NI:-NaQvREnDQAPivAaOYsx:buly4u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts#L64)):*
<details><summary><i>Previously, fantapop (Christopher Fitzner) wrote…</i></summary><blockquote>

How do you feel about passing it into the context instead of in the message?  If we leave it in the message, it feels like we should at least stringify it.  Maybe something like:
```ts
      getLogger().error(
        'Insights encounter an error while retrieving contention information.',
        { resultError: result.error },
      );
```

One other thing I noticed is that `executeInternalSql` does throw RequestError which extends from error on any non-200 response.
https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L118-L125

It looks like those generally bubble up a few layers and are caught and then displayed directly on the page rather than being logged anywhere:

https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx#L131-L133

It seems like I should additionally search for any catch handlers and log errors that show up here as well.  Thoughts?
</blockquote></details>

A search on `catch` shows quite a lot of handlers which are putting the error into a failed actions handler.  Do you know what ends up happening with these?
for example https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts#L42-L44


<!-- Sent from Reviewable.io -->

2023-07-28 23:35 UTC, sjbarag approved these changes
Looks great! +1 to adding not-JS-errors to the context object. They'll still get serialized IIRC but at least they'll be out-of-band from the messages.

Thanks for the quick docs changes! Approved on the assumption you'll add those errors to the `context` with a reasonable name. Feel free to DM me in Slack if you have any more questions :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-:-NaTqf1j3Zh-Uci7XyWT:b-b8gnh3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fantapop)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN2yDi6uqoAGQrB1NI:-NaTpPs7BjpFim3si40O:b-w6flne) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts#L64)):*
<details><summary><i>Previously, fantapop (Christopher Fitzner) wrote…</i></summary><blockquote>

A search on `catch` shows quite a lot of handlers which are putting the error into a failed actions handler.  Do you know what ends up happening with these?
for example https://github.com/cockroachdb/cockroach/blob/51aa6257c063f60fb76044f9cccc47e259930d00/pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.sagas.ts#L42-L44
</blockquote></details>

Passing it into the context works for me!

Let's focus on the currently-logged errors for now IMO. Once we enable logging and have confirmed everything reports as-expected, we can do a second pass (or help the SMEs on that code do a second pass). Some tagged logging is better than the zero tagged logging we have today :)

As for what's happening with the errors that are pushed into Redux — I assume they're being rendered in the UI — possibly via an Error Boundary? Though those are usually for 
___
*[`pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaTq_93-poX_CXLBmvH:-NaTq_93-poX_CXLBmvI:b-cremwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbbe15abe212bc8acfdcee1204675c6d42ae6613/pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx#L74)):*
> ```XML
>       errors.length === 1
>         ? `Error Loading ${props.page}`
>         : `Multiple errors seen Loading ${props.page}: ${errors}`,
> ```

This is slick :)



_Code quote:_
```XML
      errors.length === 1
        ? `Error Loading ${props.page}`
        : `Multiple errors seen Loading ${props.page}: ${errors}`,
```
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN4wtp3O-nb3zJzJ7w:-NaTq8ZZ0wszPxe3UT2f:bywpp2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L14)):*
<details><summary><i>Previously, fantapop (Christopher Fitzner) wrote…</i></summary><blockquote>

yep, its better.  VSCode is complaining about it.  Apparently have to use object syntax though.

https://stackoverflow.com/questions/70405503/how-to-create-recursive-type#answer-70405610
</blockquote></details>

Ooooooh fancy!
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN5Eo75OX0vl03_1tw:-NaTqK0kAlHMvFYkcTTj:b-z0qm39) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L20)):*
<details><summary><i>Previously, fantapop (Christopher Fitzner) wrote…</i></summary><blockquote>

yeah, sounds good. I spent some time trying to make this less repetitive but didn't come up with anything as useful as just repeating it all. 
</blockquote></details>

Bummer! It doesn't look too repetitive, and it's at least clear. Thanks for doing that!
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaTqFna0Rc_wft399qZ:-NaTqFna0Rc_wft399q_:big62wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbbe15abe212bc8acfdcee1204675c6d42ae6613/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L31)):*
> ```XML
>   context?: Record<string, JSONValue>,
>   error?: unknown,
> ) => void;
> ```

Looks unused now! Mind removing this before you `bors r+`?


<!-- Sent from Reviewable.io -->

2023-07-31 13:11 UTC, fantapop reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107718)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaN2yDi6uqoAGQrB1NI:-Nag3h4K2rSrr1xNkbmI:b4cqrmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/37c6bf7c3fb776590b4ae5095144523ff908a720/pkg/ui/workspaces/cluster-ui/src/api/contentionApi.ts#L64)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Passing it into the context works for me!

Let's focus on the currently-logged errors for now IMO. Once we enable logging and have confirmed everything reports as-expected, we can do a second pass (or help the SMEs on that code do a second pass). Some tagged logging is better than the zero tagged logging we have today :)

As for what's happening with the errors that are pushed into Redux — I assume they're being rendered in the UI — possibly via an Error Boundary? Though those are usually for 
</blockquote></details>

It looks like your comment here was cutoff.  Sounds good for following up with the other errors.
___
*[`pkg/ui/workspaces/cluster-ui/src/util/logger.ts` line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107718#-NaTqFna0Rc_wft399qZ:-Nag2F0AAklrm9FW0o6c:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbbe15abe212bc8acfdcee1204675c6d42ae6613/pkg/ui/workspaces/cluster-ui/src/util/logger.ts#L31)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Looks unused now! Mind removing this before you `bors r+`?
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2023-07-31 16:52 UTC, fantapop commented
bors r+

2023-07-31 17:53 UTC, merged