sql: unskip TestSchemaChangePurgeFailure
cockroachdb/cockroach pull request #108053
Opened 2023-08-02 19:23 UTC by chengxiong-ruan

Informs #51796

There has been a lot of changes since the test was first written and looks some of integer variables are not used to control the schema changer flow at all. Specifically the concept of "Async Schema Changer" was misleading. This commit changes the test to test the purging behavior by comparing the key counts before and after rollback. We don't need to test how many attempts.

Release note: None
Release justification: test only change

2023-08-02 21:21 UTC, fqazi requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[`pkg/sql/schema_changer_test.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108053#-Nas6C_v5vrkkYRnKSLo:-Nas6C_v5vrkkYRnKSLp:b-khnsa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da7d4b8ddb601d7822e9f4ed999b2bf05c30110/pkg/sql/schema_changer_test.go#L1681)):*
> ```Go
> 		}
> 
> 		require.Equal(t, countBeforeRollback, maxValue+2+chunkSize)
> ```

Maybe some commentary around why this becomes plus 2 here. The other numbers make sense
___
*[`pkg/sql/schema_changer_test.go` line 1684 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108053#-Nas6MZh8r3WKUzcakHE:-Nas6MZh8r3WKUzcakHF:b-aeit0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da7d4b8ddb601d7822e9f4ed999b2bf05c30110/pkg/sql/schema_changer_test.go#L1684)):*
> ```Go
> 		// No garbage left behind.
> 		testutils.SucceedsSoon(t, func() error {
> 			return sqltestutils.CheckTableKeyCount(ctx, kvDB, codec, 1, maxValue+1)
> ```

Why is there a delay? If it's GC-related, then can it be made more concrete?


<!-- Sent from Reviewable.io -->

2023-08-02 21:23 UTC, fqazi approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)



<!-- Sent from Reviewable.io -->

2023-08-02 21:44 UTC, chengxiong-ruan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108053)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schema_changer_test.go` line 1681 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108053#-Nas6C_v5vrkkYRnKSLo:-NasBqMI6_Rmqk3NiYTL:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da7d4b8ddb601d7822e9f4ed999b2bf05c30110/pkg/sql/schema_changer_test.go#L1681)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe some commentary around why this becomes plus 2 here. The other numbers make sense
</blockquote></details>

done.
___
*[`pkg/sql/schema_changer_test.go` line 1684 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108053#-Nas6MZh8r3WKUzcakHE:-NasBsSY2DEg9alzLF1S:bpt967g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4da7d4b8ddb601d7822e9f4ed999b2bf05c30110/pkg/sql/schema_changer_test.go#L1684)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Why is there a delay? If it's GC-related, then can it be made more concrete?
</blockquote></details>

also added a comment


<!-- Sent from Reviewable.io -->

2023-08-03 01:14 UTC, chengxiong-ruan commented
TFTR!
bors r+

2023-08-03 01:53 UTC, merged