plpgsql: add support for ELSIF branches
cockroachdb/cockroach pull request #108211
Opened 2023-08-04 20:11 UTC by DrewKimball

This patch adds support for executing PLpgSQL `IF` statements with `ELSIF` branches (else if). `IF` statements were already executed as CASE statements under the hood, so this change only requires building the `ELSIF` branches and appending them to the `whens` list.

Informs #105254

Release note (sql change): Added support for specifying PLpgSQL `IF` statements with `ELSIF` branches.

2023-08-04 20:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/108211)
<!-- Reviewable:end -->

2023-08-04 20:29 UTC, mgartner requested changes
Very nice!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-:-Nb1ENIT-ESJLqiffy6X:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1BsIi74wfYwIE7FcM:-Nb1BsIjCy9VihuQEWmJ:bb3rw31) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L265)):*
> ```Go
> 			elsifScopes := make([]*scope, len(t.ElseIfList))
> 			for j := range t.ElseIfList {
> 				elsifScopes[j] = b.buildPLpgSQLStatements(t.ElseIfList[j].Stmts, s.push())
> ```

Should we be pushing a new scope and sending that as an argument to `buildPLpgSQLStatements`? The first thing `buildPLpgSQLStatements` does is push another new scope. Seems like we might be making unnecessary scopes.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1Dqy8BKetkUh0hCsD:-Nb1Dqy8BKetkUh0hCsE:btwrulj) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L280)):*
> ```Go
> 			for j := range elsifScopes {
> 				if elsifScopes[j] == nil {
> 					return nil
> ```

Can you add some test cases for non-terminal elsif cases? I guess you'd have to have a non-terminal `IF` inside an `ELSIF` to achieve that?
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1EE7y0DMTR_y45F23:-Nb1EE7y0DMTR_y45F24:b-wt1aah) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L288)):*
> ```Go
> 			cond := b.buildPLpgSQLExpr(t.Condition, types.Bool, s)
> 			thenScalar := b.ob.factory.ConstructSubquery(thenScope.expr, &memo.SubqueryPrivate{})
> 			whens := memo.ScalarListExpr{b.ob.factory.ConstructWhen(cond, thenScalar)}
> ```

nit: initialize `whens` to the exact length with `make`?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1D8M_1GDexwDlCaNc:-Nb1D8M_1GDexwDlCaNd:b-vfqx9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L866)):*
> ```
> SELECT f(100);
> ----
> 0
> ```

Might not hurt to add some tests with ELSIFs inside a Loop.


<!-- Sent from Reviewable.io -->

2023-08-04 21:33 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1BsIi74wfYwIE7FcM:-Nb1NBWV8N_7b_-0p8PW:bir1ih5) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L265)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we be pushing a new scope and sending that as an argument to `buildPLpgSQLStatements`? The first thing `buildPLpgSQLStatements` does is push another new scope. Seems like we might be making unnecessary scopes.
</blockquote></details>

`buildPLpgSQLStatements` doesn't push a new scope, it uses whatever is passed in directly.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1Dqy8BKetkUh0hCsD:-Nb1O9841SYJOP13TkXA:b-fflhqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L280)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you add some test cases for non-terminal elsif cases? I guess you'd have to have a non-terminal `IF` inside an `ELSIF` to achieve that?
</blockquote></details>

Great idea. Done.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1EE7y0DMTR_y45F23:-Nb1SDSI0jgk2-Hl4AN_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L288)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: initialize `whens` to the exact length with `make`?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1D8M_1GDexwDlCaNc:-Nb1SEOn1TM-OPgnuAvq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L866)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Might not hurt to add some tests with ELSIFs inside a Loop.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-04 21:50 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-:-Nb1WqKd9qk3tmaB6Odj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-Nb1BsIi74wfYwIE7FcM:-Nb1VkFF5c7qMQ5GMR6d:b2ex9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/10e2dffac27a0335a0beaa7e3018feb94814c862/pkg/sql/opt/optbuilder/plpgsql.go#L265)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`buildPLpgSQLStatements` doesn't push a new scope, it uses whatever is passed in directly.
</blockquote></details>

Oh sorry, guess I got confused with `build`.


<!-- Sent from Reviewable.io -->

2023-08-07 23:23 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Looks great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-:-NbHJ2rLC8972jyEuA6b:b-2t11ox)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 828 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-NbHITihEjE9EeyDpNZl:-NbHITihEjE9EeyDpNZm:bid9rcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87c89c5d923bfe0c646831345cb1f2b0deb9f4b/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L828)):*
> ```
> $$ LANGUAGE PLpgSQL;
> 
> # Testing IF statements with ELSIF branches.
> ```

Could you also add a test case with nested IF / ELSIFs? Something like:
```
create or replace function f(a int, b int) returns int language plpgsql as $$ 
begin 
  if a > 1 then 
    if b > 1 then 
      return 2; 
    else 
      return 1; 
    end if; 
  elsif a = 1 then 
    if b > 1 then 
      return 0; 
    else 
      return -1; 
    end if; 
  end if; 
end $$;
```


<!-- Sent from Reviewable.io -->

2023-08-08 22:04 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108211)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_plpgsql` line 828 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108211#-NbHITihEjE9EeyDpNZl:-NbMA_YF8zD5Ep5HNWHn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b87c89c5d923bfe0c646831345cb1f2b0deb9f4b/pkg/sql/logictest/testdata/logic_test/udf_plpgsql#L828)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you also add a test case with nested IF / ELSIFs? Something like:
```
create or replace function f(a int, b int) returns int language plpgsql as $$ 
begin 
  if a > 1 then 
    if b > 1 then 
      return 2; 
    else 
      return 1; 
    end if; 
  elsif a = 1 then 
    if b > 1 then 
      return 0; 
    else 
      return -1; 
    end if; 
  end if; 
end $$;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 22:25 UTC, DrewKimball commented
TFTRs!

bors r+

2023-08-10 23:18 UTC, merged