workload: use sync/atomic's native types to ensure proper alignment
cockroachdb/cockroach pull request #108400
Opened 2023-08-08 23:40 UTC by sean-

From Go's atomic/sync's BUG section[1]:

> On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to
> arrange for 64-bit alignment of 64-bit words accessed atomically via
> the primitive atomic functions (types Int64 and Uint64 are
> automatically aligned). The first word in an allocated struct, array,
> or slice; in a global variable; or in a local variable (because the
> subject of all atomic operations will escape to the heap) can be
> relied upon to be 64-bit aligned.

[1]: https://pkg.go.dev/sync/atomic#pkg-note-BUG

Epic: none
Release note: None

2023-08-08 23:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/108400)
<!-- Reviewable:end -->

2023-08-11 15:19 UTC, BramGruneir requested changes
So to start, there should be a linter for this, or else it's going to happen again.  But I assume that will be in a separate PR.  Perhaps work that one up and put it in a draft PR.

Secondly, I think a lot of these cases won't cause any issues.  (e.g. declared variables outside of a struct, first element in a struct) But I agree that's it just best practice to convert them all.

Looks good overall, just a few small questions.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-:-Nb_7VFLEkPaFmvq8U5H:bwyzapa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, @sean-, and @srosenberg)

___
*[`pkg/workload/jsonload/json.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_8KaMDQIKsfflKbSP:-Nb_8KaMDQIKsfflKbSQ:b6x0s0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/jsonload/json.go#L56)):*
> ```Go
> 	computed    bool
> 
> 	writeSeqAtomic *atomic.Int64
> ```

Why add this?  Why not just replace the writeSeq?
___
*[`pkg/workload/jsonload/json.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_8X_m5WIivtkSDyIh:-Nb_8X_m5WIivtkSDyIi:b-ixgd94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/jsonload/json.go#L109)):*
> ```Go
> 
> // Tables implements the Generator interface.
> func (w *jsonLoad) Tables() []workload.Table {
> ```

Why are these a w?  ugh.  Not your fault, just breaks convention and made the code hard to read.  

ahh!  They're all just w for every workload!  
___
*[`pkg/workload/kv/kv.go` line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_9BXd6qm2-SmSKKft:-Nb_9BXd6qm2-SmSKKfu:bsyrw0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/kv/kv.go#L561)):*
> ```Go
> 	g               keyGenerator
> 	t               keyTransformer
> 	numEmptyResults *atomic.Int64 // accessed atomically
> ```

I guess you can remove the redundant comment.
___
*[`pkg/workload/tpcc/audit.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_9jyzBtCV_Q7Ixe9a:-Nb_9jyzBtCV_Q7Ixe9b:b-g06mz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/tpcc/audit.go#L33)):*
> ```Go
> 
> 	// transaction counts
> 	newOrderTransactions    atomic.Uint64
> ```

Are these actually accessed atomically?  (maybe the should be)


<!-- Sent from Reviewable.io -->

2023-08-11 16:29 UTC, sean- reviewed
I looked for existing off-the-shelf linters that would catch this, and it doesn't look like they detect anything on non-arm32.  I suspect the existing linters aren't actually checking for this BUG, but haven't verified it yet.  For now, I wanted to start making progress on this bug so we could get crdb on ARM into production, and then come back and revisit systematically ensuring there are no atomic alignment regressions later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-:-Nb_QBE79viY5LKaJ7IF:b-mg0ssr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir, @DarrylWong, @rachitgsrivastava, and @srosenberg)

___
*[`pkg/workload/jsonload/json.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_8KaMDQIKsfflKbSP:-Nb_O8I94WeHiWfu3X97:b6uk9se) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/jsonload/json.go#L56)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why add this?  Why not just replace the writeSeq?
</blockquote></details>

Heh.  I tried doing that first.  The idiom for workloads is to have a package-local set of variables that are passed as pointers. 
 I looked briefly for a function setter `Flag` implementation that I could use to satisfy the `Flag` interface for `flagset`, but didn't find it.  Ultimately I didn't want to rat-hole on this problem, but this was exactly what I started doing.  Scroll up to line 49 and 78 and I think it'll make sense.
___
*[`pkg/workload/jsonload/json.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_8X_m5WIivtkSDyIh:-Nb_PYx0D5lqILBnicTD:b-imxah3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/jsonload/json.go#L109)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why are these a w?  ugh.  Not your fault, just breaks convention and made the code hard to read.  

ahh!  They're all just w for every workload!  
</blockquote></details>

Yup, I've done a few tours in workload now and this took me a bit to grapple with.  The cargo-cult is strong with this utility.
___
*[`pkg/workload/kv/kv.go` line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_9BXd6qm2-SmSKKft:-Nb_PnpJAnJRzMPwdSoG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/kv/kv.go#L561)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I guess you can remove the redundant comment.
</blockquote></details>

Done.
___
*[`pkg/workload/tpcc/audit.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-Nb_9jyzBtCV_Q7Ixe9a:-Nb_Pxv06tFl5xyVJTEc:biffzcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b77b5962fd73291d88f5952ca64206920bee0d25/pkg/workload/tpcc/audit.go#L33)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are these actually accessed atomically?  (maybe the should be)
</blockquote></details>

Yeah, further down in some of the `check*()`.


<!-- Sent from Reviewable.io -->

2023-08-11 18:42 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-:-Nb_ty_O7YFTbyaqeCBT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @rachitgsrivastava, and @srosenberg)



<!-- Sent from Reviewable.io -->

2023-08-11 18:58 UTC, srosenberg reviewed
> I  looked for existing off-the-shelf linters that would catch this, and it doesn't look like they detect anything on non-arm32. I suspect the existing linters aren't actually checking for this BUG, but haven't verified it yet. For now, I wanted to start making progress on this bug so we could get crdb on ARM into production, and then come back and revisit systematically ensuring there are no atomic alignment regressions later.

There is a longstanding issue [1] to add a check to `go vet`. Unfortunately, it didn't materialize despite a number of people being afflicted. Are we aware of anyone running into this on arm32 or planning to run on arm32 in production? A full audit is no small feat, and it does look like we would need to roll our own linter.

[1] https://github.com/golang/go/issues/11891

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-:-Nb_x2Gi7GI3nOdq8DLa:bgi413e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @rachitgsrivastava)



<!-- Sent from Reviewable.io -->

2023-08-11 21:51 UTC, sean- reviewed
@srosenberg My understanding is this is an issue that spans both arm32 and arm64, not just arm32.  From [go/analysis/passes/atomicalign/atomicalign.go](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.12.0:go/analysis/passes/atomicalign/atomicalign.go;l=5-9):

```
// Package atomicalign defines an Analyzer that checks for non-64-bit-aligned
// arguments to sync/atomic functions. On non-32-bit platforms, those functions
// panic if their argument variables are not 64-bit aligned. It is therefore
// the caller's responsibility to arrange for 64-bit alignment of such variables.
// See [https://golang.org/pkg/sync/atomic/#pkg-note-BUG](https://golang.org/pkg/sync/atomic/#pkg-note-BUG)
```

I'm not an arm64 expert, but it looks like the load/store exclusive functions (`ldaxr`/`stlxr`) will cause an alignment fault on arm64 when accessing non-aligned values.  This is to say, an `int32` that is not aligned on arm64 will panic with an alignment fault.  I found an ARMv8 instruction set overview, and section 3.5.2, 3.5.3, and 5.2.7 reads:

> 3.5.2: Exclusive load-store of a byte, halfword, word and doubleword. Exclusive access to a pair of doublewords permit atomic updates of a pair of pointers, for example circular list inserts. All exclusive accesses must be naturally aligned, and exclusive pair access must be aligned to twice the data size (i.e. 16 bytes for a 64-bit pair).

> 3.5.3: Explicitly synchronising load and store instructions implement the release-consistency (RCsc) memory model, reducing the need for explicit memory barriers, and providing a good match to emerging language standards for shared memory. The instructions exist in both exclusive and non-exclusive forms, and require natural address alignment. See §5.2.8 for more details.

> 5.2.7: Natural alignment is required: an unaligned address will cause an alignment fault. A memory access generated by a load exclusive pair or store exclusive pair must be aligned to the size of the pair, and when a store exclusive pair succeeds it will cause a single-copy atomic update of the entire memory location.

As such, I'm replacing all variables used by `sync/atomic` with `atomic.Int*`, which automatically perform the right padding, regardless of the architecture, to prevent improper future cargo-culting and potential misuse.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108400#-:-NbaWgwj85JQmId6OxB3:b-ilt1u3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)



<!-- Sent from Reviewable.io -->

2023-08-11 21:53 UTC, sean- commented
bors r+

2023-08-11 22:26 UTC, merged

2023-08-12 00:30 UTC, srosenberg commented on pkg/workload/tpcc/audit.go
> +	if a.paymentTransactions.Load() < minSignificantTransactions {
Note the mutex above. Atomic loads are a de-optimization in this case.

2023-08-12 00:39 UTC, srosenberg commented
> I'm not an arm64 expert, but it looks like the load/store exclusive functions (ldaxr/stlxr) will cause an alignment fault on arm64 when accessing non-aligned values. This is to say, an int32 that is not aligned on arm64 will panic with an alignment fault. 

I don't think that's correct. For exclusive load/store, it's only the pairs which must be aligned. All other accessed can be _unaligned_,

> Unaligned addresses are permitted for most loads and stores, including paired register accesses, floating point and SIMD registers, with the exception of exclusive and ordered accesses (see §3.5.2).

Here is an example of an _unaligned_ exclusive load of a 32-bit field: https://go.dev/play/p/fkp3TnYWKyF
On mac silicon this will emit, `LDAXRW`, which works as expected,

```
  unaligned_atomics.go:17       0x10008a058             885ffc44                LDAXRW (R2), R4
```

> As such, I'm replacing all variables used by sync/atomic with atomic.Int*, which automatically perform the right padding, regardless of the architecture, to prevent improper future cargo-culting and potential misuse.

We have to be careful with these replacements. They can result in performance degradations, as well as, memory footprint explosion. I haven't gone through every change of what's already been committed, but I did find a case where atomics are now used inside a critical section.

Lastly, please do a smoke test run [1] before merging any changes which may negatively impact the nightlies. 

[1] https://cockroachlabs.atlassian.net/wiki/spaces/TE/pages/146538717/Roachtest#Roachtest-OverridingSELECT_PROBABILITY