changefeedccl: add changefeed_progress and aggregator_progress sli metrics
cockroachdb/cockroach pull request #108757
Opened 2023-08-15 05:10 UTC by samiskin

Resolves #97009

An aggregator_progress sli metric has been added to track the timestamp progress of each individual aggregator node, which can help identify single aggregators that lag behind the rest.  A checkpoint_progress sli metric has also been added to act in a similar capacity to max_behind_nanos.

I elected to keep everything as just the timestamp rather than a max_behind setup since it's still possible in graphing tools to determine the lag (ex: grafana query would be `time()*1000 -
(changefeed_aggregator_progress{scope!=""}/1000/1000))`.

Release note (ops change): changefeed metrics now include checkpoint_progress and aggregator_progress metrics to track the timestamp of the changefeed's persisted checkpoint and each individual aggregators progress. checkpoint_progress can be used for a similar purpose to max_behind_nanos but now with support for per-changefeed metrics labels.

2023-08-15 05:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/108757)
<!-- Reviewable:end -->

2023-08-15 05:11 UTC, samiskin commented
This is just the progress metrics portion of https://github.com/cockroachdb/cockroach/pull/105280 so that it is backportable.

2023-08-15 14:47 UTC, jayshrivastava requested changes
We should add unit tests for these metrics.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-:-Nbte1840cLhF2JZDvoi:b7v250b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @samiskin, and @shermanCRL)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 1333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbteBom3ux6YTJqEkqE:-NbteBom3ux6YTJqEkqF:bt90iwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/changefeed_processors.go#L1333)):*
> ```Go
> 		}
> 		cf.metrics.mu.Unlock()
> 		cf.sliMetrics.CheckpointProgress.Update(newResolved.WallTime)
> ```

nit: let's move this out of this if block and use `if checkpointed {}` instead
___
*[`pkg/ccl/changefeedccl/metrics.go` line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbtcKb58k2BM70tILMr:-NbtcKb58k2BM70tILMs:bhdbbyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/metrics.go#L560)):*
> ```Go
> 	metaAggregatorProgress := metric.Metadata{
> 		Name:        "changefeed.aggregator_progress",
> 		Help:        "The timestamp of the least up-to-date range being tracked by the aggregator",
> ```

How does the aggregate guage aggregate values provided by all aggregators? I'm worried that it takes the max, so it might show the most recent timestamp for all aggregators. 

I think we should make the help text more descriptive for all our metrics. I'm also having trouble putting words together to describe what this measures. I think we should say this is "The lowest frontier timestamp of any aggregator. NB: This is not persisted in memory, so it may regress". Because it's not persistent in memory, do we really want this metric? I'm also not sure how much value it provides unless you have this metric per-changefeed.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbteOUuC4j96i9gOf6o:-NbteOUuC4j96i9gOf6p:b41km3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/metrics.go#L564)):*
> ```Go
> 		Unit:        metric.Unit_TIMESTAMP_NS,
> 	}
> 	metaCheckpointProgress := metric.Metadata{
> ```

This metric is more useful than the aggregator one, but I'm worried about how it aggregates. 


<!-- Sent from Reviewable.io -->

2023-08-21 20:20 UTC, jayshrivastava requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108757)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @miretskiy, and @samiskin)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOdsOcAXRhSf454AnI):*
nit: use full metric names `changefeed.checkpoint_progress`

@miretskiy 
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOhsLQANqgGlPCXFxw:-NcOhsLQANqgGlPCXFxx:b-qpoatb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L278)):*
> ```Go
> 	ca.sliMetrics.mu.Lock()
> 	ca.sliMetricsID = ca.sliMetrics.mu.id
> 	ca.sliMetrics.mu.id++
> ```

Does this ++ and -- stuff really work? Say 3 aggregators start and get the IDs 0, 1, and 2, which leaves `ca.sliMetrics.mu.id` equal to 3. If aggregator 0 shuts down,  it decrements `ca.sliMetrics.mu.id` to 2. Then, if a new aggregator starts, it will use the `id` 2. This means two running aggregators have the same id right? I think the same problems applies to the current max behind nanos metric.

I think the API for this struct could be better
```
type sliProgressMetrics {  
   mu struct {
       syncutil.Mutex  
       id int
       resolved   map\[int\]hlc.Timestamp  
       checkpoint map\[int\]hlc.Timestamp  
   }
}

func (*sliProgressMetrics) clear (id) {}

func (*sliProgressMetrics) setResolved (id) {}

func (*sliProgressMetrics) setCheckpoint (id) {}

func (*sliProgressMetrics) newID () id int {}

You can make `setResolved` and `setCheckpoint` noops if the id is cleared. 
```


 
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 693 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOg95TAwYHYPpBtNTB:-NcOg95TAwYHYPpBtNTC:b-x31vk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L693)):*
> ```Go
> 	// The resolved sliMetric data backs the aggregator_progress metric
> 	if advanced && ca.sliMetricsID != -1 {
> 		ca.sliMetrics.mu.resolved[ca.sliMetricsID] = ca.frontier.Frontier()
> ```

You need to lock the mutex here.

I also don't like this -1 check and how we copy and modify ca.sliMetrics.mu.id into ca.sliMetricsID.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 397 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOdcqg7pEStBgTeEb0:-NcOdcqg7pEStBgTeEb1:b-lg1q64) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/metrics.go#L397)):*
> ```Go
> 	metaChangefeedMaxBehindNanos = metric.Metadata{
> 		Name:        "changefeed.max_behind_nanos",
> 		Help:        "(Deprecated in favor of checkpoint_progress) The most any changefeed's persisted checkpoint is behind the present",
> ```

nit:  use the full metric name `changefeed.checkpoint_progress`
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOdNHkBj-KzQiigq9l:-NcOdNHkBj-KzQiigq9m:b6qkygy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_test.go#L503)):*
> ```Go
> 				return errors.Newf("waiting for checkpoint_progress to advance from %d (value=%d)", lastTimestamp, progress)
> 			})
> 		}
> ```

Can you cancel the changefeed and assert the metrics drop back to 0?


<!-- Sent from Reviewable.io -->

2023-08-21 20:25 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108757)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @miretskiy, and @samiskin)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOdsOcAXRhSf454AnI):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

nit: use full metric names `changefeed.checkpoint_progress`

@miretskiy
</blockquote></details>

Woops I accidentally tag. Pls ignore.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOhsLQANqgGlPCXFxw:-NcOlDpz53mgqo9lQUMO:bsc6b6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L278)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Does this ++ and -- stuff really work? Say 3 aggregators start and get the IDs 0, 1, and 2, which leaves `ca.sliMetrics.mu.id` equal to 3. If aggregator 0 shuts down,  it decrements `ca.sliMetrics.mu.id` to 2. Then, if a new aggregator starts, it will use the `id` 2. This means two running aggregators have the same id right? I think the same problems applies to the current max behind nanos metric.

I think the API for this struct could be better
```
type sliProgressMetrics {  
   mu struct {
       syncutil.Mutex  
       id int
       resolved   map\[int\]hlc.Timestamp  
       checkpoint map\[int\]hlc.Timestamp  
   }
}

func (*sliProgressMetrics) clear (id) {}

func (*sliProgressMetrics) setResolved (id) {}

func (*sliProgressMetrics) setCheckpoint (id) {}

func (*sliProgressMetrics) newID () id int {}

You can make `setResolved` and `setCheckpoint` noops if the id is cleared. 
```
</blockquote></details>

A unit test with multiple changefeeds might be useful.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 693 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOg95TAwYHYPpBtNTB:-NcOlPDBEVuNuoQVSnmC:b24iiih) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L693)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

You need to lock the mutex here.

I also don't like this -1 check and how we copy and modify ca.sliMetrics.mu.id into ca.sliMetricsID.
</blockquote></details>

The -1 thing can go away if we use the different API above.


<!-- Sent from Reviewable.io -->

2023-08-24 18:33 UTC, samiskin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108757)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @jayshrivastava, and @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOhsLQANqgGlPCXFxw:-Nccn8IB-s3174vmVw_l:b3egen) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L278)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

A unit test with multiple changefeeds might be useful.
</blockquote></details>

Its never decremented, they're only incremented, so each ID is only used once.  When the aggregator shuts down it sets its own recorded id to -1 just to avoid it from setting values afterwards.

I added functions to sliMetrics and added a second feed to the test 👍.  Most of the multi-feed metric aggregation stuff is tested in the first test that just messes with the metrics directly.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 693 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOg95TAwYHYPpBtNTB:-NccnkxY8E6f6gFLB1pN:b-4nedug) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L693)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

The -1 thing can go away if we use the different API above.
</blockquote></details>

Good catch, its a function call now to handle the locks, but we still need a -1 just to know not to set any more values after we've deleted them
___
*[`pkg/ccl/changefeedccl/metrics.go` line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbtcKb58k2BM70tILMr:-NbtexfPE9-bl9QQ3ucb:bth5lmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/metrics.go#L560)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

How does the aggregate guage aggregate values provided by all aggregators? I'm worried that it takes the max, so it might show the most recent timestamp for all aggregators. 

I think we should make the help text more descriptive for all our metrics. I'm also having trouble putting words together to describe what this measures. I think we should say this is "The lowest frontier timestamp of any aggregator. NB: This is not persisted in memory, so it may regress". Because it's not persistent in memory, do we really want this metric? I'm also not sure how much value it provides unless you have this metric per-changefeed.
</blockquote></details>

(Forgot to submit this comment last time) The main point of this is to identify per-node issues, so lets say all your changefeeds had the aggregator_progress value for the same node stop increasing as much, you could pick out that that node probably has some specific issue.
If you had one feed per scope, you could also use this to have a clue as to whether its just a small set of ranges that are having issues.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbteOUuC4j96i9gOf6o:-NccogucCC4y7yGLV4Qg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/metrics.go#L564)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

This metric is more useful than the aggregator one, but I'm worried about how it aggregates.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOdNHkBj-KzQiigq9l:-NccohmVCBNuQGSOl1yh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_test.go#L503)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Can you cancel the changefeed and assert the metrics drop back to 0?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 14:57 UTC, jayshrivastava approved these changes
Very nice PR! Thanks for working on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-:-NcwdVcO3MGymS3e876r:b-jdhayb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @miretskiy, and @samiskin)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NcOhsLQANqgGlPCXFxw:-NcwdBPvEZMESbUEGL6C:bkrl0v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e649a26e3c245803b78c5a68b27fbacbc5e91e/pkg/ccl/changefeedccl/changefeed_processors.go#L278)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

Its never decremented, they're only incremented, so each ID is only used once.  When the aggregator shuts down it sets its own recorded id to -1 just to avoid it from setting values afterwards.

I added functions to sliMetrics and added a second feed to the test 👍.  Most of the multi-feed metric aggregation stuff is tested in the first test that just messes with the metrics directly.
</blockquote></details>

Oh yeah duh. Idk why I thought it was doing a `-=1`.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108757#-NbtcKb58k2BM70tILMr:-NcwdMkc1YNTP_pmlks0:bpuczkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b137086bb36d544b813244df4511e6716bb9c37/pkg/ccl/changefeedccl/metrics.go#L560)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

(Forgot to submit this comment last time) The main point of this is to identify per-node issues, so lets say all your changefeeds had the aggregator_progress value for the same node stop increasing as much, you could pick out that that node probably has some specific issue.
If you had one feed per scope, you could also use this to have a clue as to whether its just a small set of ranges that are having issues.
</blockquote></details>

Right. Scopes are very important here. We should encourage our customers to use them more. Even if they don't, knowing which node it is would be super helpful.


<!-- Sent from Reviewable.io -->

2023-08-28 14:58 UTC, samiskin commented
bors r+

2023-08-28 15:26 UTC, samiskin commented
bors r-

2023-08-29 20:10 UTC, jayshrivastava commented
bors r+

2023-08-29 21:37 UTC, merged