pgwire: avoid mentioning "tenants" in pre-serve metric names
cockroachdb/cockroach pull request #109076
Opened 2023-08-19 15:37 UTC by knz

Epic: CRDB-29380
Release note: None

2023-08-19 15:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/109076)
<!-- Reviewable:end -->

2023-08-20 00:01 UTC, stevendanna requested changes

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Number of SQL bytes received prior to routing the connectionto the target SQL server",
```suggestion
		Help:        "Number of SQL bytes received prior to routing the connection to the target SQL server",
```

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Counter of the number of SQL connections created prior to routing the connection to the target SQL server",
For consistency with the others, you could do:

```suggestion
		Help:        "Number of SQL connections created prior to routing the connection to the target SQL server",
```

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Number of SQL bytes sent prior to routing the connectionto the target SQL server",
```suggestion
		Help:        "Number of SQL bytes sent prior to routing the connection to the target SQL server",
```

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Number of SQL connection failures prior to routing the connectionto the target SQL server",
```suggestion
		Help:        "Number of SQL connection failures prior to routing the connection to the target SQL server",
```

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Memory usage for SQL connections prior to routing the connectionto the target SQL server",
```suggestion
		Help:        "Memory usage for SQL connections prior to routing the connection to the target SQL server",
```

2023-08-20 00:01 UTC, stevendanna commented on pkg/sql/pgwire/pre_serve.go
> +		Help:        "Current memory usage for SQL connections prior to routing the connectionto the target SQL server",
```suggestion
		Help:        "Current memory usage for SQL connections prior to routing the connection to the target SQL server",
```

2023-08-21 07:43 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/sql/pgwire/pre_serve.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299280976:-NcM214TDB1st9MGqjVX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L42)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

For consistency with the others, you could do:

```suggestion
		Help:        "Number of SQL connections created prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pre_serve.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299280929:-NcM21JfBoSN7Rphy8mv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L48)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

```suggestion
		Help:        "Number of SQL bytes received prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pre_serve.go` line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299280982:-NcM21fsD5Mf-bE4VmZ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L54)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

```suggestion
		Help:        "Number of SQL bytes sent prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pre_serve.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299281006:-NcM21y_0J1JsgOlRiEq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L60)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

```suggestion
		Help:        "Number of SQL connection failures prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pre_serve.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299281022:-NcM22kgAhvOmW2MZp5A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L66)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

```suggestion
		Help:        "Memory usage for SQL connections prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.
___
*[`pkg/sql/pgwire/pre_serve.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299281028:-NcM23-hDZXedSWwN5j2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L72)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

```suggestion
		Help:        "Current memory usage for SQL connections prior to routing the connection to the target SQL server",
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 10:54 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109076)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`pkg/sql/pgwire/pre_serve.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109076#gh-1299281028:-NcMiktFDjXpzIOVXb70:bwmb33q) ([raw file](https://github.com/cockroachdb/cockroach/blob/045ec1562217c751684fdd4d907ee1402d2fb54b/pkg/sql/pgwire/pre_serve.go#L72)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Looks like this one slipped through still.
</blockquote></details>

Indeed. Fixed.


<!-- Sent from Reviewable.io -->

2023-08-21 11:46 UTC, stevendanna approved these changes
Thanks!

2023-08-21 11:54 UTC, knz commented
TFYR!

bors r=stevendanna

2023-08-21 12:47 UTC, merged