server: add more info the combined statement endpoint
cockroachdb/cockroach pull request #109040
Opened 2023-08-18 20:38 UTC by maryliag

Previously, it was hard to know which tables were
used to populate the SQL Activity, making debug for it complicated.
This commit adds extra information to the
`combinedstmts` to help:
- olderAggregatedTsReturned
- stmtsSourceTable
- txnsSourceTable

Returning a value for `olderAggregatedTsReturned` will also allow us to show proper warning when the older timestamp doesn't match the start date of the selected time period on the Search Criteria.

Part Of #108989

Release note: None

2023-08-18 20:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/109040)
<!-- Reviewable:end -->

2023-08-19 17:45 UTC, koorosh requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDdQsR9vRbUFgs-QRP:-NcCA4DCCtNZuRzMYpgl:b-9hrh01) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L342)):*
> ```Go
> 			fmt.Sprintf(`
> SELECT COALESCE(min(aggregated_ts), now())
> FROM %s %s`, table, whereClause), args...)
> ```

I have concern about this statement, I ran `EXPLAIN ANALYZE` on this query and it used full scan on it.
```sql
EXPLAIN ANALYZE SELECT COALESCE(min(aggregated_ts), now()) FROM crdb_internal.statement_statistics WHERE true AND aggregated_ts >= now() AND aggregated_ts <= now();
```
result:
```
planning time: 9ms
  execution time: 9ms
  distribution: local
  vectorized: true

  • render
  │
  └── • group (scalar)
      │ nodes: n1
   ...
                  │
                  └── • scan
                        ....
                        table: statement_statistics@fingerprint_stats_idx  ----------------------  WARNING: the row count estimate is inaccurate, consider running 'ANALYZE statement_statistics'
                        spans: FULL SCAN (SOFT LIMIT)
```

Most of the indexes on `system.statement\_statistics` table defined with condition  `WHERE app\_name NOT LIKE '$ internal%'` so I suggest to include this clause in WHERE condition of the statement:
```sql
EXPLAIN ANALYZE 
  SELECT COALESCE(min(aggregated_ts), now()) FROM crdb_internal.statement_statistics 
  WHERE true 
    AND aggregated_ts >= now()  
    AND aggregated_ts <= now() 
    AND app_name NOT LIKE '$ internal%' -- <- add this
```
which gives us:
```
          └── • scan
                nodes: n1
                ...
                table: statement_statistics@execution_count_idx (partial index)
                spans: [/'2023-08-18 17:31:07.875656+00' - /'2023-08-19 17:40:35.478088+00']
```
___
*[`pkg/server/serverpb/status.proto` line 1644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDI8vyEHhI-6n02jfE:-NcDI8vyEHhI-6n02jfF:b-nh3qlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/serverpb/status.proto#L1644)):*
> ```proto
>   // OlderAggregatedTsReturned is the timestamp of the oldest entry returned,
>   // or NOW() if there is no data returned.
>   google.protobuf.Timestamp older_aggregated_ts_returned = 8 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> ```

The naming of field is a bit confusing.


<!-- Sent from Reviewable.io -->

2023-08-19 17:59 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDvv7W-pc9IJdWRzQQ:-NcDvv7W-pc9IJdWRzQR:bfhz5h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L345)):*
> ```Go
> 
> 		if err != nil {
> 			return timeutil.Now(), err
> ```

What is the motivation to return `now()` instead of NULL in case of error or empty results?


<!-- Sent from Reviewable.io -->

2023-08-19 19:36 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/combined_statement_stats.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDdQsR9vRbUFgs-QRP:-NcEHEWd9Z_EYBbtSxKs:b-wq1s0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L342)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I have concern about this statement, I ran `EXPLAIN ANALYZE` on this query and it used full scan on it.
```sql
EXPLAIN ANALYZE SELECT COALESCE(min(aggregated_ts), now()) FROM crdb_internal.statement_statistics WHERE true AND aggregated_ts >= now() AND aggregated_ts <= now();
```
result:
```
planning time: 9ms
  execution time: 9ms
  distribution: local
  vectorized: true

  • render
  │
  └── • group (scalar)
      │ nodes: n1
   ...
                  │
                  └── • scan
                        ....
                        table: statement_statistics@fingerprint_stats_idx  ----------------------  WARNING: the row count estimate is inaccurate, consider running 'ANALYZE statement_statistics'
                        spans: FULL SCAN (SOFT LIMIT)
```

Most of the indexes on `system.statement\_statistics` table defined with condition  `WHERE app\_name NOT LIKE '$ internal%'` so I suggest to include this clause in WHERE condition of the statement:
```sql
EXPLAIN ANALYZE 
  SELECT COALESCE(min(aggregated_ts), now()) FROM crdb_internal.statement_statistics 
  WHERE true 
    AND aggregated_ts >= now()  
    AND aggregated_ts <= now() 
    AND app_name NOT LIKE '$ internal%' -- <- add this
```
which gives us:
```
          └── • scan
                nodes: n1
                ...
                table: statement_statistics@execution_count_idx (partial index)
                spans: [/'2023-08-18 17:31:07.875656+00' - /'2023-08-19 17:40:35.478088+00']
```
</blockquote></details>

We actually have a cluster setting to decide if we're returning internal statements on this endpoint or not, so I added the changes to take that into consideration. The default value is to filter out internal, so now is doing that correctly! Nice callout!
___
*[`pkg/server/combined_statement_stats.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDvv7W-pc9IJdWRzQQ:-NcEHRbLAhz7f_VPGtt3:b-o986d) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L345)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

What is the motivation to return `now()` instead of NULL in case of error or empty results?
</blockquote></details>

I get compile error if I try to just return null, since the function expects a Time. I changed to just the empty Time component, which ends up also returning NOW, but at east shows that we don't really care the value itself
___
*[`pkg/server/serverpb/status.proto` line 1644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDI8vyEHhI-6n02jfE:-NcEHiEJ4TH2JoFaCHXQ:b-a1hdzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/serverpb/status.proto#L1644)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

The naming of field is a bit confusing.
</blockquote></details>

Made a slight change, let me know if is more clear now. We do select a time period, but we might not have data for that full period, so let's say we request from august 10 to august 19, but we only have data starting on aug 15, so that is the value returned here. A following PR will use this value to show a warning in the UI.

Let me know if the name is better now.


<!-- Sent from Reviewable.io -->

2023-08-19 21:29 UTC, koorosh reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDdQsR9vRbUFgs-QRP:-NcENbug5M8aaN6Dh-XU:btojbfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L342)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We actually have a cluster setting to decide if we're returning internal statements on this endpoint or not, so I added the changes to take that into consideration. The default value is to filter out internal, so now is doing that correctly! Nice callout!
</blockquote></details>

Great!
___
*[`pkg/server/combined_statement_stats.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDvv7W-pc9IJdWRzQQ:-NcEenVMBfg2qMgrJDfW:b-ecslvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L345)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I get compile error if I try to just return null, since the function expects a Time. I changed to just the empty Time component, which ends up also returning NOW, but at east shows that we don't really care the value itself
</blockquote></details>

It requires following changes to make it work with `null`:
1. Remove `(gogoproto.nullable) = false` attribute from `oldest_aggregated_ts_returned` field in ptoto message
```proto
google.protobuf.Timestamp oldest\_aggregated\_ts\_returned = 8 [(gogoproto.stdtime) = true];
```
2. Return pointer to time.Date in `getOldestDate` and change returned values to either `nil` or address of value
```go
getOldestDate := func(table string) (\*time.Time, error) {
```

My concern about returning current time is to avoid confusion when users reset stats so there's no records in tables but `oldest aggregated ts` would return current time which in turn would be problematic.
___
*[`pkg/server/combined_statement_stats.go` line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcEdfoDEPt6P7gBsagP:-NcEdfoDEPt6P7gBsagQ:b-lzmx30) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe467272c2e83266a12fd436c8ad4243e501097f/pkg/server/combined_statement_stats.go#L375)):*
> ```Go
> 		}()
> 
> 		return tree.MustBeDTimestampTZ(row[0]).Time, nil
> ```

`tree.MustBeDTimestampTZ` panics if it cannot retrieve the value. Should we be more tolerant and use `AsDTimestampTZ` that indicates where the value parsed or not? 
___
*[`pkg/server/serverpb/status.proto` line 1644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDI8vyEHhI-6n02jfE:-NcEgAkI3Qsr8wD2lByb:bswact) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/serverpb/status.proto#L1644)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Made a slight change, let me know if is more clear now. We do select a time period, but we might not have data for that full period, so let's say we request from august 10 to august 19, but we only have data starting on aug 15, so that is the value returned here. A following PR will use this value to show a warning in the UI.

Let me know if the name is better now.
</blockquote></details>

Got it! Thanks for detailed explanation it is clear now! Thank you!


<!-- Sent from Reviewable.io -->

2023-08-20 03:48 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/server/combined_statement_stats.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcDvv7W-pc9IJdWRzQQ:-NcG2JHw59tgn-JjsHtD:b-1lwg9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c2a133eed8a005ef10905384db1087bf7939ba/pkg/server/combined_statement_stats.go#L345)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It requires following changes to make it work with `null`:
1. Remove `(gogoproto.nullable) = false` attribute from `oldest_aggregated_ts_returned` field in ptoto message
```proto
google.protobuf.Timestamp oldest\_aggregated\_ts\_returned = 8 [(gogoproto.stdtime) = true];
```
2. Return pointer to time.Date in `getOldestDate` and change returned values to either `nil` or address of value
```go
getOldestDate := func(table string) (\*time.Time, error) {
```

My concern about returning current time is to avoid confusion when users reset stats so there's no records in tables but `oldest aggregated ts` would return current time which in turn would be problematic.
</blockquote></details>

Nice! I made the changes and now returns `null` when no data is returned :) 
thank you for the detailed steps
___
*[`pkg/server/combined_statement_stats.go` line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcEdfoDEPt6P7gBsagP:-NcG2S7oEOTtEjfGhUIF:b3j0pc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe467272c2e83266a12fd436c8ad4243e501097f/pkg/server/combined_statement_stats.go#L375)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

`tree.MustBeDTimestampTZ` panics if it cannot retrieve the value. Should we be more tolerant and use `AsDTimestampTZ` that indicates where the value parsed or not?
</blockquote></details>

the value should ne null or timestamp, so I added a check for DNull first, then make the call the parse the timestamp, now it will probably return null or the timestamp.


<!-- Sent from Reviewable.io -->

2023-08-20 08:03 UTC, koorosh reviewed
LGTM, great! 
Also want to clarify if we need to do the same check for transaction statistics?

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcGxHxMColdFusduOJI:bcty07e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 375 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-NcEdfoDEPt6P7gBsagP:-NcGu1RJ2pCYg035iaE9:b-wp8edu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe467272c2e83266a12fd436c8ad4243e501097f/pkg/server/combined_statement_stats.go#L375)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

the value should ne null or timestamp, so I added a check for DNull first, then make the call the parse the timestamp, now it will probably return null or the timestamp.
</blockquote></details>

Nice! 🎉


<!-- Sent from Reviewable.io -->

2023-08-20 14:45 UTC, maryliag reviewed
On transaction statistics we also return statement statistics, so it will go over the same parts of the code, I just had to made an adjustement.

Examples of responses when:

Statement page with results:
```
"stmtsTotalRuntimeSecs": 89.46363,
  "txnsTotalRuntimeSecs": 0,
  "oldestAggregatedTsReturned": "2023-08-20T14:00:00Z",
  "stmtsSourceTable": "crdb\_internal.statement\_statistics\_persisted",
  "txnsSourceTable": ""
```


Statement page with no results:
```
"stmtsTotalRuntimeSecs": 0,
  "txnsTotalRuntimeSecs": 0,
  "oldestAggregatedTsReturned": null,
  "stmtsSourceTable": "crdb\_internal.statement\_statistics",
  "txnsSourceTable": ""
```

Transactions page with results:
```
"stmtsTotalRuntimeSecs": 90.2161,
  "txnsTotalRuntimeSecs": 47.55528,
  "oldestAggregatedTsReturned": "2023-08-20T14:00:00Z",
  "stmtsSourceTable": "crdb\_internal.statement\_statistics\_persisted",
  "txnsSourceTable": "crdb\_internal.transaction\_statistics\_persisted"
```

Transactions page with no results:
````
"stmtsTotalRuntimeSecs": 0,
  "txnsTotalRuntimeSecs": 0,
  "oldestAggregatedTsReturned": null,
  "stmtsSourceTable": "crdb\_internal.statement\_statistics",
  "txnsSourceTable": "crdb\_internal.transaction\_statistics"
```
````


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcIMqwIEpOiHzEupmWu:b-j44es0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)



<!-- Sent from Reviewable.io -->

2023-08-21 11:54 UTC, koorosh reviewed
Sorry if my question was misleading. 
 `getOldestDate` function is only called to get oldest timestamp for `statement_activity` tables but not `transaction_activity` tables. I'm not sure if it is necessary or not.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcH-qih8Kx8LxHTgzlO:b-9kbqst)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2023-08-21 12:40 UTC, maryliag reviewed
That was on purpose, because the statements data would reach the limit and be deleted first and that is used by both statements and transactions, so having just one of them is enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcN5lEoD-GAznDfxnTz:b-tffhr5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)



<!-- Sent from Reviewable.io -->

2023-08-21 12:47 UTC, koorosh reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcN7eiAD8krxVpEvvIS:b-yncq5v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2023-08-21 12:47 UTC, koorosh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109040#-:-NcN7m043xprDS_Q15FL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2023-08-21 13:13 UTC, maryliag commented
TFTR!

bors r+

2023-08-21 14:20 UTC, merged

2023-08-21 14:26 UTC, maryliag commented
blathers backport 23.1