schemachanger: Disable ALTER TABLE multiple commands by default
cockroachdb/cockroach pull request #109818
Opened 2023-08-31 15:59 UTC by Xiang-Gu

Disable ALTER TABLE stmt with multiple ADD COLUMN, DROP COLUMN, ALTER PK commands (which is
added in #99526) by default. Customers can enable it by setting `use_declarative_schema_changer` to `unsafe` or `unsafe_always`, or forcefully enable declarative schema changer on `ALTER TABLE` stmts by setting cluster setting `sql.schema.force_declarative_statements='+ALTER TABLE';`.
The plan is to enable it again by default after v23.2 (be it v24.1 or v23.3).

Fixes #108870
Epic: None
Release note: None

2023-08-31 15:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/109818)
<!-- Reviewable:end -->

2023-09-01 16:13 UTC, fqazi requested changes
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-NdGT-j22nnGgyEBGm_T):*
Make this third person, and ideally closer to our recommended wiki way of writing commit messages.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-NdGWDKr-vOYYfpNV2ps:-NdGWDKs09ZdO5Jrf6rs:bkmr81g) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L228)):*
> ```Go
> 			return
> 		}
> 		newSchemaChangerMode := getDeclarativeSchemaChangerModeForStmt(b, n)
> ```

Couldn't we just have keyed off the number of commands in the ALTER statement instead? That would have been a more straightforward check.


<!-- Sent from Reviewable.io -->

2023-09-05 14:42 UTC, chrisseto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109818)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_jfnu7ODZRMJLfySS):*
nit: Could you say a bit about why this code is unnecessary? Maybe something like "We assert there is exactly one test per end to end test. Therefore we don't need to _blah_"
___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_kOYT3MGoQ4C7x-jn):*
nit: This summary sounds like we're disabling many `ALTER TABLE` statements. Maybe something like `Use LSC for multi-change ALTER TABLE statements by default`?
___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_kEuR1rskhbl-N9wz):*
Can we add a note about why we're disabling this statement by default?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_lSlV7CIpuTS7ZEhG:-Nd_lCQM29-H5jaQo1Pa:bbsuieq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L189)):*
> ```Go
> 
> // getDeclarativeSchemaChangerModeForStmt returns the mode specific for `n`.
> // It consults session variable `use_declarative_schema_changer` (blanket)
> ```

nit: The phrasing of the comment feels a bit off. It took a couple reads to understand what it was saying. How would you feel about something along the lines of:
```
... returns the mode for `n`.
If the session variable `use_declarative_schema_changer` is <values>, it returns <mode>.
If the cluster setting `sql.schema.force_declarative_statements`, matches `n`, it returns <mode>.
Otherwise it returns <mode>`
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_mkkN4LrkLe6iWnNE:-Nd_mkkN4LrkLe6iWnNF:b-zsbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L200)):*
> ```Go
> 	stmtsForceControl := getStatementsForceControl(&b.ClusterSettings().SV)
> 	if forcedEnabled := stmtsForceControl.CheckControl(n); forcedEnabled {
> 		ret = sessiondatapb.UseNewSchemaChangerUnsafe
> ```

super nit: why not `return sessiondatapb.UserNewSchemaChangerUnsafe` here?
___
*[`pkg/sql/schemachanger/sctest/end_to_end.go` line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_j4WoAM_LvhBcb19T:-Nd_j4WoAM_LvhBcb19U:bf5h69q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f9c01119e2a920d77bfd158d8caee96ccd82e8d/pkg/sql/schemachanger/sctest/end_to_end.go#L122)):*
> ```Go
> 				// test cluster, here the SQLRunner is only used to populate the mocked
> 				// catalog state.
> 				var deps *sctestdeps.TestState
> ```

nit: this looks like it can be moved to be directly above `deps` declaration. We should keep predeclarations as close to their actual declaration as possible to minimize the overhead of trying to understand why something is being predeclared. It would also be good to add a note about why this being predeclared rather than using the standard `:=` operator. (Seems to be the usage of `LogSideEffectf` in `BeforeStage`)


<!-- Sent from Reviewable.io -->

2023-09-05 15:44 UTC, Xiang-Gu reviewed
Thanks for the feedback. I have addressed your comments and please take another look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-:-Nda-pBu0hDo6YDE5Q9D:byeoli3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @fqazi)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-NdGT-j22nnGgyEBGm_T):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Make this third person, and ideally closer to our recommended wiki way of writing commit messages.
</blockquote></details>

Done.
___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_kOYT3MGoQ4C7x-jn):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: This summary sounds like we're disabling many `ALTER TABLE` statements. Maybe something like `Use LSC for multi-change ALTER TABLE statements by default`?
</blockquote></details>

done
___
*[`-- commits` line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_kEuR1rskhbl-N9wz):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

Can we add a note about why we're disabling this statement by default?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-NdGWDKr-vOYYfpNV2ps:-Nd_sw9cCPj0asN6LRie:bj2hecq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L228)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Couldn't we just have keyed off the number of commands in the ALTER statement instead? That would have been a more straightforward check.
</blockquote></details>

unfortunately this is not enough. E.g. we'd like the following example to be  *enabled* by default:
```
alter table t add column j int default 20, add column k int default 30;
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 189 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_lSlV7CIpuTS7ZEhG:-Nd_utxs2k2uOgLIa2qq:b-qino6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L189)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: The phrasing of the comment feels a bit off. It took a couple reads to understand what it was saying. How would you feel about something along the lines of:
```
... returns the mode for `n`.
If the session variable `use_declarative_schema_changer` is <values>, it returns <mode>.
If the cluster setting `sql.schema.force_declarative_statements`, matches `n`, it returns <mode>.
Otherwise it returns <mode>`
```
</blockquote></details>

done, what do you think of the rewritten comments?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_mkkN4LrkLe6iWnNE:-Nd_v6_W4Jg7VdOVJlDz:b-ffjua2) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a519fb562c49d95ad7282a8742ddefe7a8cc0d/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L200)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

super nit: why not `return sessiondatapb.UserNewSchemaChangerUnsafe` here?
</blockquote></details>

nothing important. I guess just personal coding preference?
___
*[`pkg/sql/schemachanger/sctest/end_to_end.go` line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-Nd_j4WoAM_LvhBcb19T:-Nd_vaXm5PfKMFXSn2m-:b-pdd9l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f9c01119e2a920d77bfd158d8caee96ccd82e8d/pkg/sql/schemachanger/sctest/end_to_end.go#L122)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: this looks like it can be moved to be directly above `deps` declaration. We should keep predeclarations as close to their actual declaration as possible to minimize the overhead of trying to understand why something is being predeclared. It would also be good to add a note about why this being predeclared rather than using the standard `:=` operator. (Seems to be the usage of `LogSideEffectf` in `BeforeStage`)
</blockquote></details>

I actually prefer this way bc this declaration line of `deps` signals the beginning of a new block of logic, and it's before `refFactory` bc it needs `refFactory` to initialize itself.

I put a simple line explaining why it's not declared and initialized in the same line with `:=` (yes, it's bc of the usage of `LogSideEffectf`)


<!-- Sent from Reviewable.io -->

2023-09-05 19:01 UTC, fqazi approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109818#-:-Ndai2IcE4TTwKAjQ_Mx:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @chrisseto)



<!-- Sent from Reviewable.io -->

2023-09-05 19:28 UTC, Xiang-Gu commented
TFTR!

bors r+

2023-09-05 20:11 UTC, merged