release-23.1.10-rc: testing: rewrite TestRepartitioning as SQLTranslator tests
cockroachdb/cockroach pull request #110070
Opened 2023-09-05 23:13 UTC by ecwall

Backport 7/7 commits from #109911.

/cc @cockroachdb/release

---

Fixes #49112
Fixes https://github.com/cockroachdb/cockroach/issues/109935
Fixes https://github.com/cockroachdb/cockroach/issues/109985

This rewrites TestRepartitioning subtests as SQLTranslator tests so that they
can be unskipped.

Release note: None

2023-09-05 23:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110070)
<!-- Reviewable:end -->

2023-09-06 14:22 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/partitionccl/partition_test.go` line 1302 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/110070#-NderkOoAnseymOFw3Sl:-NderkOoAnseymOFw3Sm:b-qkbf1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/adeceedc68a16339093bb44012b000835563873f/pkg/ccl/partitionccl/partition_test.go#L1302)):*
> ```Go
> }
> 
> func TestPrimaryKeyChangeZoneConfigs(t *testing.T) {
> ```

it seems like this test was removed and not replaced (but it was correctly included in the master branch PR)


<!-- Sent from Reviewable.io -->

2023-09-06 15:07 UTC, ecwall reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110070)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/partitionccl/partition_test.go` line 1302 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/110070#-NderkOoAnseymOFw3Sl:-Ndf12kc8MaXRZiAd3Yb:b-ennps8) ([raw file](https://github.com/cockroachdb/cockroach/blob/adeceedc68a16339093bb44012b000835563873f/pkg/ccl/partitionccl/partition_test.go#L1302)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems like this test was removed and not replaced (but it was correctly included in the master branch PR)
</blockquote></details>

I did the same thing here as the other backport. I just added it back here as well.


<!-- Sent from Reviewable.io -->

2023-09-06 16:14 UTC, rafiss approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110070)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-09-06 16:35 UTC, merged