sql: update UDF references in `ALTER TABLE`
cockroachdb/cockroach pull request #110130
Opened 2023-09-06 17:58 UTC by chrisseto

Previously, `ALTER TABLE ... ADD CONSTRAINT` statements  that referenced a UDF did not appropriately update UDFs' `DependedOnBy` field to reference the table/constraint that utilized it. This would surface as the validation error reported in #109414, `relation X: depends-on function X has no corresponding depended-on-by back reference`. This commit ensures that the back references are updated by copying a hook from `CREATE TABLE`.

Epic: None
Fixes: #109414
Release note (bug fix): `ALTER TABLE ... ADD CONSTRAINT CHECK ...` statements that utilize a UDF in the CHECK no longer cause a validation error.

2023-09-06 17:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110130)
<!-- Reviewable:end -->

2023-09-07 20:27 UTC, rafiss requested changes
looks great! just had very minor testing comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-:-NdlK0vF2tbu2kls5SaQ:b-l32t85)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJLCc71Or24Wv1grx:-NdlJLCd45ZjlUyyxBOm:b1o48n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L444)):*
> ```
> subtest issue-109414-minimal
> 
> statement ok
> ```

very cool that we got a repro for this!

one thing which may not be obvious is that if you send all the queries at once like this, they are al run in the same transaction (it's a PG compat thing). to make this more clear, could we
- add a BEGIN/COMMIT around the _whole_ thing, so it's clear it's all the same transaction
- or add a BEGIN/COMMIT around _each_ command, so each one is forced to run in a different transaction
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJlV64jZUZ7-aRcrw:-NdlJlV64jZUZ7-aRcrx:bygzov4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L448)):*
> ```
> CREATE FUNCTION has_account(account_id UUID) RETURNS BOOL LANGUAGE SQL AS $$ SELECT EXISTS(SELECT * FROM accounts WHERE id = account_id) $$;
> CREATE TABLE account_ref ( account_id UUID NOT NULL );
> ALTER TABLE account_ref ADD CONSTRAINT diy_fk CHECK (has_account(account_id));
> ```

nit: it might be useful to throw in an assertion here, like check the output of `SHOW CREATE TABLE account_ref`
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJzE70QRKlVFr1SaS:-NdlJzE70QRKlVFr1SaT:b-3cssou) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L453)):*
> ```
> # of itself, so it's been included as it may catch other regressions that the
> # minimal case wouldn't.
> subtest issue-109414-full
> ```

both comments above apply to this subtest too


<!-- Sent from Reviewable.io -->

2023-09-11 17:24 UTC, chrisseto reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-:-Ne4GMO05Z0rQ3b0lh6D:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJLCc71Or24Wv1grx:-Ne4GPGq45mYrfviLieB:bkjmpsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L444)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

very cool that we got a repro for this!

one thing which may not be obvious is that if you send all the queries at once like this, they are al run in the same transaction (it's a PG compat thing). to make this more clear, could we
- add a BEGIN/COMMIT around the _whole_ thing, so it's clear it's all the same transaction
- or add a BEGIN/COMMIT around _each_ command, so each one is forced to run in a different transaction
</blockquote></details>

done and I managed to simplify the reproduction a bit further.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJlV64jZUZ7-aRcrw:-Ne4GUu_559c9nzTlO1l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L448)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: it might be useful to throw in an assertion here, like check the output of `SHOW CREATE TABLE account_ref`
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NdlJzE70QRKlVFr1SaS:-Ne4GVJvCJJ2Zhd_zI6l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e583cb96e09b7a3122d8365362662b9249200332/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L453)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

both comments above apply to this subtest too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-13 15:53 UTC, rafiss approved these changes
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-:-NeEEiLk0lb276tubPC4:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-09-13 16:16 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110130)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NeEIvLwAVRKeZ8w0TNu:-NeEIvLwAVRKeZ8w0TNv:b-1131ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/aba86c0c25fe3e756c9db9583b60ab2c09808492/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L469)):*
> ```
> statement ok
> CREATE TABLE accounts_a (id UUID NOT NULL);
> CREATE TABLE accounts_b (id UUID NOT NULL);
> ```

ah, the test is failing due to something the logic tests do called column family randomization. basically, it will add non-default column families, so the output of SHOW is affected. you can fix it by making the CREATE statement be explicit about column families, like this:
```
CREATE TABLE accounts_a (id UUID NOT NULL, FAMILY "primary" (id, rowid))
```


<!-- Sent from Reviewable.io -->

2023-09-14 19:12 UTC, chrisseto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110130)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/udf_in_constraints` line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110130#-NeEIvLwAVRKeZ8w0TNu:-NeK60py29x4Ymume_97:b-dny70e) ([raw file](https://github.com/cockroachdb/cockroach/blob/aba86c0c25fe3e756c9db9583b60ab2c09808492/pkg/sql/logictest/testdata/logic_test/udf_in_constraints#L469)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah, the test is failing due to something the logic tests do called column family randomization. basically, it will add non-default column families, so the output of SHOW is affected. you can fix it by making the CREATE statement be explicit about column families, like this:
```
CREATE TABLE accounts_a (id UUID NOT NULL, FAMILY "primary" (id, rowid))
```
</blockquote></details>

aaaaah, thank you! Fixed.


<!-- Sent from Reviewable.io -->

2023-09-15 14:05 UTC, chrisseto commented
bors r=rafiss

2023-09-15 14:44 UTC, merged