ui: surface flow control metrics in overload dashboard
cockroachdb/cockroach pull request #110135
Opened 2023-09-06 19:51 UTC by irfansharif

Some of this new flow control machinery changes the game for IO admission control. This commits surfaces relevant metrics to the overload dashboard:
- kvadmission.flow_controller.{regular,elastic}_requests_admitted
- kvadmission.flow_controller.{regular,elastic}_wait_duration-p75
- kvadmission.flow_controller.{regular,elastic}_requests_waiting
- kvadmission.flow_controller.{regular,elastic}_blocked_stream_count
- kvadmission.flow_controller.{regular,elastic}_tokens_deducted

While here, we replace the storage.l0-{sublevels,num-files} metrics with the admission.io.overload instead. The former showed the raw counts instead of normalizing it based on AC target thresholds. And the y-axis scales for sublevels vs. files are an order of magnitude apart, so slightly more annoying to distinguish.

Release note: None

2023-09-06 19:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110135)
<!-- Reviewable:end -->

2023-09-06 19:53 UTC, irfansharif commented
Looks like this. I might be crowding the Overload dashboard a bit much so I'm happy to cull things out.

<img width="741" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/b0626e72-7004-47d9-aabd-67760cf29d71">

<img width="743" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/4935d086-65fc-4771-90e0-f5fef2295b48">

<img width="739" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/c2ed9b55-d734-46d8-a49c-7fca596bdcc4">

<img width="739" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/b4edfd3c-54fb-49e3-9c30-4dbcfe134982">

2023-09-06 21:21 UTC, sumeerbhola requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @irfansharif)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-NdgM92t1Z_t6As7ZOWq):*
Are requests_admitted or tokens_deducted useful when aggregated across all destination stores?

I can see some value provided by wait_duration, requests_waiting, blocked_stream_count since as aggregated gauges or deltas they provide at a glance an upper bound on how bad things are.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-NdgL9hn8yBtH1YUtVb7:-NdgL9hn8yBtH1YUtVb8:bym4kfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/472deb29bd2f7a78b9098cb512dea38733a07250/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L163)):*
> ```XML
>             <Metric
>               key={nid}
>               name="cr.node.kvadmission.flow_controller.regular_requests_admitted"
> ```

Not having these metrics per destination store is going to make it hard to understand what is happening when we see queuing at a node.
I realize this is not in scope for this PR, but can we support Prometheus metrics with the destination store label? If yes, it should be a priority to add them.


<!-- Sent from Reviewable.io -->

2023-09-21 01:08 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110135)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @sumeerbhola)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-NdgM92t1Z_t6As7ZOWq):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are requests_admitted or tokens_deducted useful when aggregated across all destination stores?

I can see some value provided by wait_duration, requests_waiting, blocked_stream_count since as aggregated gauges or deltas they provide at a glance an upper bound on how bad things are.
</blockquote></details>

No strong opinions; removed.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-NdgL9hn8yBtH1YUtVb7:-NepG4dtEL5sJEBYUU3f:beztfg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/472deb29bd2f7a78b9098cb512dea38733a07250/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Not having these metrics per destination store is going to make it hard to understand what is happening when we see queuing at a node.
I realize this is not in scope for this PR, but can we support Prometheus metrics with the destination store label? If yes, it should be a priority to add them.
</blockquote></details>

https://github.com/cockroachdb/cockroach/issues/111011.


<!-- Sent from Reviewable.io -->

2023-09-21 13:33 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-:-NerwOQT4er5EG8HFCaH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @irfansharif)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-Nerw7bq4Ftpi3wwGlWe:-Nerw7bq4Ftpi3wwGlWf:b1nf5ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee842ea6c16ba3e2c44378c3a67b6b3fc6ca5c8/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L161)):*
> ```XML
>             <Metric
>               key={nid}
>               name="cr.node.kvadmission.flow_controller.regular_requests_admitted"
> ```

did you forget to remove these *requests_admitted and *tokens_deducted metrics here?


<!-- Sent from Reviewable.io -->

2023-09-21 14:25 UTC, irfansharif reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-:-Nes7IM05C_ph3E2nIl0:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110135#-Nerw7bq4Ftpi3wwGlWe:-Nes7JHf3x0jZPXLTkC8:b73xycp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cee842ea6c16ba3e2c44378c3a67b6b3fc6ca5c8/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L161)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did you forget to remove these *requests_admitted and *tokens_deducted metrics here?
</blockquote></details>

I'd forgotten to push out the SHA.


<!-- Sent from Reviewable.io -->

2023-09-21 14:39 UTC, irfansharif commented
bors r-

2023-09-21 15:57 UTC, merged

2024-01-04 21:23 UTC, florence-crl commented
Updated release note in description and added to docs in https://github.com/cockroachdb/docs/pull/18193