spanconfig: remove ability to disable span configs
cockroachdb/cockroach pull request #110253
Opened 2023-09-08 14:31 UTC by andrewbaptist

Span configs are integral to correct operation of queues and the ability
to disable this infrastructure is no longer necessary. This commit
removes the customer facing knob `spanconfig.store.enabled` as well as
the environment setting `COCKROACH_DISABLE_SPAN_CONFIGS` and modifies
all the tests to stop using this setting. `store_test.go` still sets
`cfg.SpanConfigDisabled` but all other tests are converted to use
`ManagerDisableJobCreation` instead which keeps the span config
infrastructure but disables the internal job to reconcile span configs
after certain changes like an upgrade.

Epic: none

Release note (ops change): Removes the cluster setting
`spanconfig.store.enabled` and the ability to use
`COCKROACH_DISABLE_SPAN_CONFIGS`.

2023-09-08 14:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110253)
<!-- Reviewable:end -->

2023-09-08 21:21 UTC, andrewbaptist commented
Only the last PR needs to be reviewed, the others are part of #108809

2023-09-14 15:42 UTC, arulajmani requested changes
Thanks for taking on this cleanup! It's been long overdue. 

> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 13 of 24 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-:-NeJLaSH03QvItQzIj9F:b-evp34o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andrewbaptist, @DarrylWong, and @rachitgsrivastava)

___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-Ne9i0-UCn4lOKnVMlbs):*
After this patch, are we in a place where we can get rid of the `SystemConfig` as well? Should we file a followup cleanup issue about that?
___
*[`pkg/kv/kvserver/store.go` line 2173 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJJCsG44uDdwGs9qxu:-NeJJCsG44uDdwGs9qxv:bf698y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/store.go#L2173)):*
> ```Go
> 	}
> 
> 	// Some tests don't set the SpanConfigSubscriber.
> ```

This seems a bit weird -- why are some tests deliberately not setting the `SpanConfigSubscriber`? Isn't that akin to disabling the span configurations infrastructure, which is something this patch is trying to improve? 
___
*[`pkg/sql/logictest/logic.go` line 2142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJFn1lDTgW2InrWsi0:-NeJFn1m72bfXXhjLZgw:bc4cc03) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/sql/logictest/logic.go#L2142)):*
> ```Go
> 	parseDirectiveOptions(t, path, clusterDirective, func(opt string) {
> 		switch opt {
> 		case "disable-span-configs":
> ```

We should remove "disable-span-configs" as an option from the comment around cluster-opts as well.
___
*[`pkg/jobs/job_info_storage_test.go` line 242 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLUBS9Wz8kBlbS5wl:-NeJLUBS9Wz8kBlbS5wm:b-xg6sje) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/job_info_storage_test.go#L242)):*
> ```Go
> 			},
> 		},
> 		DisableSpanConfigs: true,
> ```

Same comment as elsewhere about why it's safe to remove this knob from here.
___
*[`pkg/jobs/registry_test.go` line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLJlQ3Dvae33kEnVn:-NeJLJlQ3Dvae33kEnVo:b839sdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/registry_test.go#L336)):*
> ```Go
> 			},
> 		},
> 		DisableSpanConfigs: true,
> ```

Do we understand why the tests in this file were disabling span configurations to begin with? Does removing this testing knob make them flaky, or was the test fooling itself?
___
*[`pkg/jobs/update_test.go` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJL2pi-rlTB5Wxxs81:-NeJL2pi-rlTB5Wxxs82:b-ge6vew) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/update_test.go#L57)):*
> ```Go
> 			},
> 		},
> 		DisableSpanConfigs: true,
> ```

Do we know why this test was disabling span configurations to begin with? Was it for a legit reason that needs to be addressed, or was the test fooling itself?
___
*[`pkg/jobs/update_test.go` line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLCDK9NwTfyAUaFbq:-NeJLCDK9NwTfyAUaFbr:benpsw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/update_test.go#L200)):*
> ```Go
> 			},
> 		},
> 		DisableSpanConfigs: true,
> ```

Same comment as above.
___
*[`pkg/kv/kvserver/store_test.go` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHEIOCk3KAT10JY3X:-NeJHEIOCk3KAT10JY3Y:b20spys) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/store_test.go#L223)):*
> ```Go
> 	// to do the same (with some effort). That's unlikely to happen soon, so
> 	// let's continue to use the system config span.
> 	cfg.SystemConfigProvider = config.NewConstantSystemConfigProvider(
> ```

We shouldn't be using the `SystemConfigProvider` for tests anymore -- it's entirely been replaced by the span configurations infrastructure, so tests using this harness aren't giving us the coverage we need. 

Let's address this comment as part of this cleanup.
___
*[`pkg/kv/kvserver/protectedts/ptcache/cache_test.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHbxX08PxrNGnNB8-:-NeJHbxX08PxrNGnNB80:b-qftet6) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/kv/kvserver/protectedts/ptcache/cache_test.go#L163)):*
> ```Go
> 		base.TestServerArgs{
> 			// Disable span configs to avoid measuring protected timestamp lookups
> 			// performed by the AUTO SPAN CONFIG RECONCILIATION job.
> ```

This comment seems to imply we were disabling span configurations for a good reason -- was that not so? Does this diff make this test flakey?
___
*[`pkg/sql/tests/split_test.go` line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJKdmY5AOXY7VL5WrP:-NeJKdmY5AOXY7VL5WrQ:b-snyj9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/sql/tests/split_test.go#L72)):*
> ```Go
> 
> 	s, sqlDB, kvDB := serverutils.StartServer(t, base.TestServerArgs{
> 		// The test needs to be refactored to work with the secondary tenants.
> ```

We sort of do, it's because it was disabling span configurations! Does it work now?
___
*[`pkg/sql/tests/split_test.go` line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJKBdl5nQ10zrAC-dR:-NeJKBdl5nQ10zrAC-dS:b9bhx1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/sql/tests/split_test.go#L78)):*
> ```Go
> 		ScanMinIdleTime:    time.Millisecond,
> 		ScanMaxIdleTime:    time.Millisecond,
> 		DisableSpanConfigs: true,
> ```

Do we know why this test was disabling span configurations to begin with? I'm left scratching my head, but I could be missing something.
___
*[`pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHwkYCGgn-y99Wx9w:-NeJHwk_6jp1t6uD43SP:b-hpjk1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go#L45)):*
> ```Go
> 		// Disable all automatic jobs creation and adoption.
> 		ServerArgs: base.TestServerArgs{
> 			DisableSpanConfigs: true,
> ```

The comment above seems to indicate that it wants no automatic jobs to be running in the system. Enabling the span configurations infrastructure will result in the creation of a `AUTO SPAN CONFIG JOB`. Does this test flake with your change? Or was the test fooling itself?
___
*[`pkg/kv/kvserver/mvcc_gc_queue.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJJ13E3dq8EXT0HJ3G:-NeJJ13E3dq8EXT0HJ3H:b-jncsdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/mvcc_gc_queue.go#L122)):*
> ```Go
> 
> // EnqueueInMvccGCQueueOnSpanConfigUpdateEnabled controls whether replicas
> // are enqueued into the mvcc queue, following a span config update which
> ```

"mvcc gc queue"
___
*[`pkg/kv/kvserver/mvcc_gc_queue.go` line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJJ76s-0hX_ccm3xlg:-NeJJ76s-0hX_ccm3xlh:b-q8xmdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/mvcc_gc_queue.go#L124)):*
> ```Go
> // are enqueued into the mvcc queue, following a span config update which
> // affects the replica.
> // TODO(baptist): Enable this once we have better AC control and have verified
> ```

Did you mean to inc [...]

2023-09-22 14:51 UTC, andrewbaptist reviewed
TFTR - and for pointing out the `ManagerDisableJobCreation` option. That is much better to use.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-:-NexLE9T6a5eUL-Fd5_K:b-ybu7l3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, @DarrylWong, and @rachitgsrivastava)

___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-Ne9i0-UCn4lOKnVMlbs):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

After this patch, are we in a place where we can get rid of the `SystemConfig` as well? Should we file a followup cleanup issue about that?
</blockquote></details>

I filed #110999 and started a PR. I don't understand all the implications of it, so may chat with you next week on this. The biggest problems are related to the replication reports which are broken today for MT, but still exist. 
___
*[`pkg/kv/kvserver/store.go` line 2173 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJJCsG44uDdwGs9qxu:-NeoIegI9GOOLK_EX3DB:b-er31ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/store.go#L2173)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This seems a bit weird -- why are some tests deliberately not setting the `SpanConfigSubscriber`? Isn't that akin to disabling the span configurations infrastructure, which is something this patch is trying to improve?
</blockquote></details>

This was weird, and I didn't have this here first, but I needed to put it back. I added a TODO comment to this and might try this in a follow-up patch during stability. Ideally, this can be removed.
___
*[`pkg/sql/logictest/logic.go` line 2142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJFn1lDTgW2InrWsi0:-NeoJHDT66ssOTr3kC2A:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/sql/logictest/logic.go#L2142)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should remove "disable-span-configs" as an option from the comment around cluster-opts as well.
</blockquote></details>

Done
___
*[`pkg/jobs/job_info_storage_test.go` line 242 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLUBS9Wz8kBlbS5wl:-NeoJV8NAbJ8spJdF5As:b-2hby3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/job_info_storage_test.go#L242)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as elsewhere about why it's safe to remove this knob from here.
</blockquote></details>

I just removed all the checks and saw what broke. I couldn't tell how much this was cut/paste, had been added to make the test pass, or was required to de-flake. I'm running all these tests with stress to make sure they aren't flaky after removal, but I don't know why this was added in many places as some were unnecessary.

I plan to watch post-merge and ensure there are no flakes due to span configs, but I stressed all these tests now and they pass locally.
___
*[`pkg/jobs/registry_test.go` line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLJlQ3Dvae33kEnVn:-NeoKbHd3_5SuGAYnryP:bv53uqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/registry_test.go#L336)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we understand why the tests in this file were disabling span configurations to begin with? Does removing this testing knob make them flaky, or was the test fooling itself?
</blockquote></details>

This seemed like a "cut-and-paste" usage.
___
*[`pkg/jobs/update_test.go` line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJL2pi-rlTB5Wxxs81:-NeoKot_7nnuSGEhBiTk:b-q8fkrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/update_test.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we know why this test was disabling span configurations to begin with? Was it for a legit reason that needs to be addressed, or was the test fooling itself?
</blockquote></details>

Also seemed like a cut-and-paste.
___
*[`pkg/jobs/update_test.go` line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLCDK9NwTfyAUaFbq:-NeoKtG06f4TdZMTQvLj:b-q8fkrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/update_test.go#L200)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Also seemed like a cut-and-paste.
___
*[`pkg/kv/kvserver/store_test.go` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHEIOCk3KAT10JY3X:-NeuTwNc3kYlUnksGMw1:b-fwzi76) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/store_test.go#L223)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We shouldn't be using the `SystemConfigProvider` for tests anymore -- it's entirely been replaced by the span configurations infrastructure, so tests using this harness aren't giving us the coverage we need. 

Let's address this comment as part of this cleanup.
</blockquote></details>

I added a TODO to this and will clean up in the follow-up PR.
___
*[`pkg/kv/kvserver/protectedts/ptcache/cache_test.go` line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHbxX08PxrNGnNB8-:-NeuUOkaDPfNeJSm1Kw3:b-iibupa) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/kv/kvserver/protectedts/ptcache/cache_test.go#L163)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This comment seems to imply we were disabling span configurations for a good reason -- was that not so? Does this diff make this test flakey?
</blockquote></details>

Good point. The test didn't flake for me either way locally, but I changed to use `ManagerDisableJobCreation` to make sure it didn't accidentally make this flakey again. 
___
*[`pkg/sql/tests/split_test.go` line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJKdmY5AOXY7VL5WrP:-NexJqT3DF1FCL4i3-Rp:bs3jf4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/sql/tests/split_test.go#L72)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We sort of do, it's because it was disabling span configurations! Does it work now?
</blockquote></details>

Fixed - and created #111112
___
*[`pkg/sql/tests/split_test.go` line 78 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJKBdl5nQ10zrAC-dR:-NexJxYfC2G42ZuOMkHy:bo1pcfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/sql/tests/split_test.go#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we know why this test was disabling span configurations to begin with? I'm left scratching my head, but I could be missing something.
</blockquote></details>

Not really - I'm guessing it was trying to avoid some queues running, but it doesn't make much sense. 
___
*[`pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHwkYCGgn-y99Wx9w:-NexK6Q65V_hVr_wWqqT:bgepisj) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go#L4 [...]

2023-09-27 15:18 UTC, arulajmani reviewed
I only have one high level comment before this PR should be ready to go -- it's about addressing the TODO such that we don't need to account for a nil `KVSubscriber`. Otherwise, we're simply trading a testing knob for a nil check. 

That being said, maybe this PR can be split into 2 -- one which cleans up all these tests that were mistakenly disabling span configurations (or using too heavy a hammer). Another could be the actual removal of the knob itself. 

The first of these 2 PRs should be ready to go, if you want to make the split. I think that'll mean that the only usage of this testing knob will be in `store_test.go`, which in itself is a huge win. Happy to chat about this offline, if you want.

> Reviewed 15 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-:-NfMBlu37nGwhA5ZAC1U:b-s2vr1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andrewbaptist, @DarrylWong, and @rachitgsrivastava)

___
*[`-- commits` line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-Ne9i0-UCn4lOKnVMlbs):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I filed #110999 and started a PR. I don't understand all the implications of it, so may chat with you next week on this. The biggest problems are related to the replication reports which are broken today for MT, but still exist.
</blockquote></details>

I don't think that's quite right -- `systemSpanConfigStore` is used by protected timestamps, and that things legit. I don't think we want to get rid of it. 

I meant we should get rid of the `SystemConfig`(see `pkg/config/system.go`) which was used by KV to access zone configurations prior to the introduction of `SpanConfigurations`. Sorry for not being clearer, these are confusingly named.
___
*[`pkg/jobs/job_info_storage_test.go` line 242 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLUBS9Wz8kBlbS5wl:-NfMAzAM6ov_XYfwyb7k:b-fuhee) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/job_info_storage_test.go#L242)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I just removed all the checks and saw what broke. I couldn't tell how much this was cut/paste, had been added to make the test pass, or was required to de-flake. I'm running all these tests with stress to make sure they aren't flaky after removal, but I don't know why this was added in many places as some were unnecessary.

I plan to watch post-merge and ensure there are no flakes due to span configs, but I stressed all these tests now and they pass locally.
</blockquote></details>

Okay, that sounds like a good strategy. Thanks for stressing them locally.
___
*[`pkg/jobs/registry_test.go` line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJLJlQ3Dvae33kEnVn:-NfMBEcLEqjfuMFDsCKU:bg7c6f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/jobs/registry_test.go#L336)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This seemed like a "cut-and-paste" usage.
</blockquote></details>

Ack. Glad we're finding and getting rid of these!
___
*[`pkg/kv/kvserver/store_test.go` line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHEIOCk3KAT10JY3X:-NfMBK3O4OS1a7edtJqp:b-2mxuzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e83bd47c6b397a7ba944bf1101bc3265f01a7433/pkg/kv/kvserver/store_test.go#L223)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I added a TODO to this and will clean up in the follow-up PR.
</blockquote></details>

I think addressing this TODO should be the crux of this PR. Otherwise, we're simply trading the testing knob for a nil `KVSubscriber`, right? 
___
*[`pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go` line 45 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NeJHwkYCGgn-y99Wx9w:-NfMB_1HAxLBeFgA-YfS:b-wvdulf) ([raw file](https://github.com/cockroachdb/cockroach/blob/116abdd18fd897415fb45fa1e542e10117f35a9b/pkg/upgrade/upgrades/backfill_job_info_table_migration_test.go#L45)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

It didn't flake, but I still think it is better to not have the span jobs running as this test expects specific job behavior.
</blockquote></details>

Ack. The `ManagerDisableJobCreation` seems like the way to go.


<!-- Sent from Reviewable.io -->

2023-09-27 17:15 UTC, andrewbaptist commented
I'm attempting to spilt - let me see if this works, and if so, I'll leave the second commit without the nil check out for now and address that later on.

2023-09-27 20:50 UTC, andrewbaptist commented
OK - it worked to split this out. Can you take one more pass. Thanks!

2023-09-27 21:30 UTC, arulajmani approved these changes
Nice, thanks for splitting this out. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  

> Reviewed 1 of 17 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-:-NfNY40Q9F0FEo3eG1lh:b15he56)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @andrewbaptist, @DarrylWong, and @rachitgsrivastava)

___
*[`-- commits` line 4 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/110253#-NfNX9iU2sV7Ng3JTw-L):*
Should we update the commit message/PR title? Or maybe clarify that by "removing the ability to disable span configurations" we mean the public cluster setting that could be toggled -- one usage of the testing knob still remains. 

It might also be worth adding some words about the tests that have been updated as part of this patch.


<!-- Sent from Reviewable.io -->

2023-09-28 13:48 UTC, andrewbaptist commented
bors r=arulajmani

2023-09-28 14:29 UTC, merged