sql: switch discarded stats logging to a time interval
cockroachdb/cockroach pull request #110271
Opened 2023-09-08 17:23 UTC by gtr

To mitigate the OOM issues induced by frequent logging upon the end of
every transaction in the case of discarded stmt/txn stats, this commit
introduces a switch from per-transaction logging to time-interval-based
logging. An internal cluster setting,
`sql.metrcs.discarded_stats.log_interval`, is added to adjust this
interval.

Informs: https://cockroachlabs.atlassian.net/browse/SREOPS-7255

Release note (sql change): discarded stats warning log frequency is now
controlled by a cluster setting, defaulting to a 1-minute interval.

2023-09-08 17:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110271)
<!-- Reviewable:end -->

2023-09-11 12:35 UTC, maryliag reviewed
Is this related to https://github.com/cockroachdb/cockroach/issues/98818? I don't see the connection to the issue you tagged

Can you do performance testing to check if this change is not causing regression?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-:-Ne3E9n3DpFYPWP22Uy4:bowvtwj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @srosenberg)



<!-- Sent from Reviewable.io -->

2023-09-11 12:49 UTC, j82w requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110271)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @gtr, and @srosenberg)

___
*[`pkg/sql/sqlstats/cluster_settings.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3CtzW2X5BCE9FZ7Mn:-Ne3CtzW2X5BCE9FZ7Mo:be8xjkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/cluster_settings.go#L122)):*
> ```Go
> var DiscardedStatsLogInterval = settings.RegisterDurationSetting(
> 	settings.TenantWritable,
> 	"sql.metrics.discarded_stats.log_interval",
> ```

How about `sql.metrics.discarded_stats_log.interval`? That way it leave it open to add other settings in the future like `.enabled`.
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3Er4gDmkYRH2iHNCh:-Ne3Er4gDmkYRH2iHNCi:bx2cmbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L40)):*
> ```Go
> 	// that were discarded due to reaching the SQL statistics memory limit
> 	// since the last log emission.
> 	discardedStmtCount uint64
> ```

Please add tests.
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3GaGSEAhYsuNkXZLY:-Ne3GaGSEAhYsuNkXZLZ:b-ky7rpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L60)):*
> ```Go
> 
> // NewStatsCollector returns an instance of sqlstats.StatsCollector.
> func NewStatsCollector(
> ```

Is the the StatsCollector used for more than 1 txn?
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3Exvj4HdsCSmx-Eyt:-Ne3Exvj4HdsCSmx-Eyu:bmgx2qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L69)):*
> ```Go
> 		ApplicationStats: appStats,
> 		phaseTimes:       phaseTime.Clone(),
> 		// Initialize to the current time to prevent immediate log emission after startup
> ```

How is it possible to hit the capacity on startup to cause immediate log emission?
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3G7os7wm7DsH1zLnc:-Ne3G7os7wm7DsH1zLnd:bgq56fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L128)):*
> ```Go
> 
> 	// Update the counts of discarded statements and transactions.
> 	s.discardedStmtCount += discardedStmts
> ```

Does this need to be thread safe?
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3HNig9eU00bDX4HAd:-Ne3HNig9eU00bDX4HAe:b-g7ouer) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L133)):*
> ```Go
> 
> 	// Check if it's time to log.
> 	now := timeutil.Now()
> ```

Why get logInterval or now before checking the count?
___
*[`pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go` line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110271#-Ne3GqAQ3ZB_FVGQoLaO:-Ne3GqAQ3ZB_FVGQoLaP:b-r1qxxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ea1e5ba2eea33e702850e917929d50f87a31c1/pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go#L137)):*
> ```Go
> 		if now.Sub(s.lastLoggedTimestamp) > logInterval {
> 			if s.discardedStmtCount > 0 {
> 				log.Warningf(ctx, "%d statement statistics discarded due to memory limit", s.discardedStmtCount)
> ```

Can the log messages me merged to keep all the info together and reduce the number of logs?
`log.Warningf(ctx, "statistics discarded due to memory limit. Statement discard count: %d, Transaction discard count: %d", s.discardedStmtCount)`


<!-- Sent from Reviewable.io -->

2023-09-20 13:06 UTC, j82w commented
Moved to: https://github.com/cockroachdb/cockroach/pull/110805

2023-09-20 13:06 UTC, closed without merging