util/pretty: mitigate stack overflows of Pretty
cockroachdb/cockroach pull request #110374
Opened 2023-09-11 20:35 UTC by mgartner

#### errorutil: moved kv-specific errors out of errorutil

Errors for missing store and node descriptors have been moved from the
errorutil package to the kvpb package, because the errorutil package is
a low-level package to aid in working with errors in general. It should
not contain facilities for creating specific errors as this muddles the
package and can lead to import cycles.

Release note: None

#### errorutil: move SendReport to new sentryutil package

The `SendReport` function has been moved out of the errorutil package
and into a new sentryutil package. This avoids muddling the errorutil
package with a Sentry-specific function, and it breaks errorutil's
dependence on `pkg/settings` and `pkg/util/log/logcrash`.

Release note: None

#### util/pretty: mitigate stack overflows of Pretty

This commit reduces the chance of a stack overflow from recursive calls
of `*beExec.be`. The `Pretty` function will now return an internal error
if the recursive depth of `be` surpasses 10,000.

Informs #91197

Release note: None

2023-09-11 20:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110374)
<!-- Reviewable:end -->

2023-09-11 21:06 UTC, knz reviewed
The approach taken here works if we choose to _error_ out when the SQL is sufficiently complex.
But is that the right UX wrt user expectations?

We are looking here at a formatter. If the SQL is sufficiently complex, we still have an option to _render_ the SQL -- using the simple formatter (the one that's not pretty).
What of avoiding an `error` return in `Pretty()` and instead have it call `.AST.String()` if memory was exceeded?

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-Ne52xUz2O49ZrYsNv4y:b98xdp7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/util/pretty/pretty.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52jzR8y_cn77li6ao:-Ne52jzS04SzxXoIFsbH:b-u1a5zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L119)):*
> ```Go
> }
> 
> const maxBeDepth = 100_000
> ```

arguably i could see us use 10.000 here (anything above 1000 looks suspicious to me).


<!-- Sent from Reviewable.io -->

2023-09-11 21:07 UTC, michae2 requested changes
Thanks! I agree with @knz that we should make an effort to try to render the SQL even if it is slightly ugly.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-Ne53EW34X7u1mg68-kS:b-ri0mvt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/cmd/reduce/reduce/reducesql/reducesql.go` line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52uUi6sppQd8FxfX5:-Ne52uUi6sppQd8FxfX6:b-nkjhlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/cmd/reduce/reduce/reducesql/reducesql.go#L443)):*
> ```Go
> 		p, err := cfg.Pretty(stmt)
> 		if err != nil {
> 			panic(err)
> ```

Maybe instead of panic we should revert to using `stmt`?
___
*[`pkg/internal/sqlsmith/sqlsmith.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52zyZ3LMO1Dy62FiD:-Ne52zyZ3LMO1Dy62FiE:bnyfwmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/internal/sqlsmith/sqlsmith.go#L195)):*
> ```Go
> 		p, err := prettyCfg.Pretty(stmt)
> 		if err != nil {
> 			panic(err)
> ```

Same comment here.
___
*[`pkg/sql/explain_bundle.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne4z5ZN-X2kFWqU0w7t:-Ne4z5ZN-X2kFWqU0w7u:b-e4flhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/sql/explain_bundle.go#L266)):*
> ```Go
> 		b.stmt, err = cfg.Pretty(b.plan.stmt.AST)
> 		if err != nil {
> 			return err
> ```

If we hit this error, instead of giving up on saving the statement, I propose we copy this logic from the `b.plan.stmt.AST == nil` case above so that the bundle still has something useful:

```go
		b.stmt = stmtRawSQL
		// If we're collecting a redacted bundle, redact the raw SQL completely.
		if b.flags.RedactValues && b.stmt != "" {
			b.stmt = string(redact.RedactedMarker())
		}
```

If you want to save the formatting error, could add something like `"\n-- failed to format SQL: %v"` to the b.stmt.
___
*[`pkg/util/pretty/pretty.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne515iG670wqP2aoyCI:-Ne515iH09ndozsboSbw:b1xddvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L119)):*
> ```Go
> }
> 
> const maxBeDepth = 100_000
> ```

Personally I would go even smaller (maybe 10k) but this is also fine.
___
*[`pkg/util/pretty/pretty.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52CB-BbHu3In2a0xy:-Ne52CB-BbHu3In2a0xz:b-a2153e) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L125)):*
> ```Go
> 	defer func() { b.beDepth-- }()
> 	if b.beDepth > maxBeDepth {
> 		return nil, errors.AssertionFailedf("max call stack depth of be exceeded")
> ```

Another idea, if @knz doesn't like this, is to panic instead of adding error handling to every stack frame.


<!-- Sent from Reviewable.io -->

2023-09-11 21:08 UTC, knz commented
> Another idea, if @knz doesn't like this, is to panic instead of adding error handling to every stack frame.

lol, yes I am known to advertise for this type of error handling, which would be super justified here.

2023-09-11 21:13 UTC, mgartner reviewed
I agree that the UX could improve, but I'd argue this is already a vast improvement. An internal error is strictly better than a crashed node.

IMO it should be up to the caller of Pretty to decide what to do if there is an error, but if you both feel strongly that it should just spit out a "non-pretty" string I can make that change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-Ne53nPm-3ybPDFHXQyn:b-r5qerz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[`pkg/util/pretty/pretty.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne515iG670wqP2aoyCI:-Ne54SYNA4XEYNEgs5xO:b-trqk28) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L119)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Personally I would go even smaller (maybe 10k) but this is also fine.
</blockquote></details>

Heh, you two are on the same page today, huh? :wink: Done.
___
*[`pkg/util/pretty/pretty.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52jzR8y_cn77li6ao:-Ne54rh01Lp3IPnbzkz9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L119)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

arguably i could see us use 10.000 here (anything above 1000 looks suspicious to me).
</blockquote></details>

Done.
___
*[`pkg/util/pretty/pretty.go` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52CB-BbHu3In2a0xy:-Ne54YG_CI8kNLQfr4HM:bur4x1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/util/pretty/pretty.go#L125)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Another idea, if @knz doesn't like this, is to panic instead of adding error handling to every stack frame.
</blockquote></details>

A panic here won't be guaranteed to be caught by a `recover`. I originally wanted to do this but from what I could tell the code path for the explain bundle would not recover from the panic, so it'd end up crashing the node.


<!-- Sent from Reviewable.io -->

2023-09-11 21:20 UTC, mgartner commented
> A panic here won't be guaranteed to be caught by a recover. I originally wanted to do this but from what I could tell the code path for the explain bundle would not recover from the panic, so it'd end up crashing the node.

Or are you suggesting to add `recover` to the `Pretty` function?

2023-09-11 21:22 UTC, knz commented
> Or are you suggesting to add recover to the Pretty function?

yes, that.  panic-based error handling should never cross package boundaries.

2023-09-12 14:15 UTC, mgartner reviewed
> yes, that. panic-based error handling should never cross package boundaries.

:+1: Done.

I added two more commits to avoid some import cycles. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-Ne8S-slAvwXKrR22veM:bitm238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[`pkg/cmd/reduce/reduce/reducesql/reducesql.go` line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52uUi6sppQd8FxfX5:-Ne8U2f7C0sfFg89FADn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/cmd/reduce/reduce/reducesql/reducesql.go#L443)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Maybe instead of panic we should revert to using `stmt`?
</blockquote></details>

Done.
___
*[`pkg/internal/sqlsmith/sqlsmith.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne52zyZ3LMO1Dy62FiD:-Ne8UZQf9iKVpp2Vx7ja:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/internal/sqlsmith/sqlsmith.go#L195)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Same comment here.
</blockquote></details>

Done.
___
*[`pkg/sql/explain_bundle.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne4z5ZN-X2kFWqU0w7t:-Ne8WGTSEQFzVyzG2koH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98795648699aa5dec85395aeb8b3ff9bcd4df5be/pkg/sql/explain_bundle.go#L266)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

If we hit this error, instead of giving up on saving the statement, I propose we copy this logic from the `b.plan.stmt.AST == nil` case above so that the bundle still has something useful:

```go
		b.stmt = stmtRawSQL
		// If we're collecting a redacted bundle, redact the raw SQL completely.
		if b.flags.RedactValues && b.stmt != "" {
			b.stmt = string(redact.RedactedMarker())
		}
```

If you want to save the formatting error, could add something like `"\n-- failed to format SQL: %v"` to the b.stmt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 15:30 UTC, knz reviewed
> Reviewed 28 of 28 files at r3, 10 of 10 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`-- commits` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne8zqZXEdNETFuo6B1t):*
:100: nice
___
*[`pkg/kv/kvpb/errors.go` line 1631 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne8yw1b7gS0HCgeaAgZ:-Ne8yw1b7gS0HCgeaAg_:b34hzl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2533a0752f678f62ec1f2b3b8a2f109c5a9ff6bc/pkg/kv/kvpb/errors.go#L1631)):*
> ```Go
> 
> // StoreDescNotFoundError is reported when a stored descriptor is missing.
> type StoreDescNotFoundError struct {
> ```

For the sake of error encode/decode, I recommend you keep a single data type (maybe with a boolean var to distinguish node/store); then you will want to add this to the init function:

```go
errorutilpath := reflect.TypeOf(errorutil.XXX_TBD{}).PkgPath()
errors.RegisterTypeMigration(errorutilpath, "*errorutil.descriptorNotFound", &DescNotFoundError)
```

where `XXX_TBD` is a sentinel type remaining behind in `errorutil` to enable retrieving the PkgPath via reflect.
___
*[`pkg/sql/explain_bundle.go` line 261 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-fY_5W-y6J62LfhR:-Ne9-fY_5W-y6J62LfhS:bbxg6f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/explain_bundle.go#L261)):*
> ```Go
> 		b.stmt, err = cfg.Pretty(b.plan.stmt.AST)
> 		if err != nil {
> 			// Use the raw statement string if pretty-printing fails.
> ```

I'm not keen on having a blanket ignore of the object in `err`. This feels like a candidate for `errors.Is`. If there's any other error later in the Pretty interface that is more "Serious" we won't want that to get ignored.
___
*[`pkg/sql/show_create_clauses.go` line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-qxm8XjgkKLLHvtP:-Ne9-qxm8XjgkKLLHvtQ:b-j7466p) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/show_create_clauses.go#L173)):*
> ```Go
> 		}
> 		query, err = cfg.Pretty(parsed.AST)
> 		if err != nil {
> ```

ditto my previous comment about `errors.Is`
___
*[`pkg/sql/show_create_clauses.go` line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-J_k4AAyH7P6MJan:-Ne9-J_k4AAyH7P6MJao:btz1s91) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/show_create_clauses.go#L174)):*
> ```Go
> 		query, err = cfg.Pretty(parsed.AST)
> 		if err != nil {
> 			log.Warningf(ctx, "error pretty-printing query for view %s (%v): %+v",
> ```

What is this warning going to help with? What should an operator do if they see it?
___
*[`pkg/sql/sem/builtins/builtins.go` line 11162 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-VXq3mnCaXbj_n9V:-Ne9-VXq3mnCaXbj_n9W:b-9xwead) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/sem/builtins/builtins.go#L11162)):*
> ```Go
> 		p, err := p.Pretty(stmts[idx].AST)
> 		if err != nil {
> 			return "", err
> ```

I think this is a case where we probably want an alternate representation if this one fails. This code is used when displaying queries in DB Console.
___
*[`pkg/util/pretty/pretty.go` line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-zNM8iIbEJpkcVkx:-Ne9-zNM8iIbEJpkcVky:b372nin) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/util/pretty/pretty.go#L141)):*
> ```Go
> 	defer func() { b.beDepth-- }()
> 	if b.beDepth > maxBeDepth {
> 		panic(errors.AssertionFailedf("max call stack depth of be exceeded"))
> ```

possibly a custom error marker here to enable `errors.Is`.


<!-- Sent from Reviewable.io -->

2023-09-13 21:56 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[`-- commits` line 18 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne8zqZXEdNETFuo6B1t):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

:100: nice
</blockquote></details>

:+1: 
___
*[`pkg/kv/kvpb/errors.go` line 1631 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne8yw1b7gS0HCgeaAgZ:-NeFUwfp5_ElHUpG-uaY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2533a0752f678f62ec1f2b3b8a2f109c5a9ff6bc/pkg/kv/kvpb/errors.go#L1631)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

For the sake of error encode/decode, I recommend you keep a single data type (maybe with a boolean var to distinguish node/store); then you will want to add this to the init function:

```go
errorutilpath := reflect.TypeOf(errorutil.XXX_TBD{}).PkgPath()
errors.RegisterTypeMigration(errorutilpath, "*errorutil.descriptorNotFound", &DescNotFoundError)
```

where `XXX_TBD` is a sentinel type remaining behind in `errorutil` to enable retrieving the PkgPath via reflect.
</blockquote></details>

Done.
___
*[`pkg/sql/explain_bundle.go` line 261 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-fY_5W-y6J62LfhR:-NeANu0B-o5PobHt-hh7:b-ovind) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/explain_bundle.go#L261)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm not keen on having a blanket ignore of the object in `err`. This feels like a candidate for `errors.Is`. If there's any other error later in the Pretty interface that is more "Serious" we won't want that to get ignored.
</blockquote></details>

Great catch. Done.
___
*[`pkg/sql/show_create_clauses.go` line 173 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-qxm8XjgkKLLHvtP:-NeFVCc1-6v_90Qq_KNI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/show_create_clauses.go#L173)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto my previous comment about `errors.Is`
</blockquote></details>

Done.
___
*[`pkg/sql/show_create_clauses.go` line 174 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-J_k4AAyH7P6MJan:-NeFV29BEq59nXkMSw4w:b-fgmihv) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/show_create_clauses.go#L174)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What is this warning going to help with? What should an operator do if they see it?
</blockquote></details>

It wasn't intended for an operator. I thought it might aid us in debugging in the future, but I'm not sure exactly how. I've removed it.
___
*[`pkg/sql/sem/builtins/builtins.go` line 11162 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-VXq3mnCaXbj_n9V:-NeFRLrS904i3lhkRip7:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/sql/sem/builtins/builtins.go#L11162)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I think this is a case where we probably want an alternate representation if this one fails. This code is used when displaying queries in DB Console.
</blockquote></details>

Makes sense, done.
___
*[`pkg/util/pretty/pretty.go` line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-Ne9-zNM8iIbEJpkcVkx:-NeFRkBu68GRArkmBgg9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/340f65d641e53aa7dd32b4684cfa9ff404350d87/pkg/util/pretty/pretty.go#L141)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

possibly a custom error marker here to enable `errors.Is`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-14 13:45 UTC, knz reviewed
> Reviewed 7 of 31 files at r6, 9 of 10 files at r7, 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/kv/kvpb/errors.go` line 1662 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIvU6OBtPP0bDg9SLf:-NeIvU6P2XlHjaAvtgso:b-a084vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/kv/kvpb/errors.go#L1662)):*
> ```Go
> func (e *DescNotFoundError) SafeFormatError(p errors.Printer) (next error) {
> 	if e.isStore {
> 		p.Printf("store descriptor with store ID %d was not found", e.storeID)
> ```

nit: maybe
```go
s := redact.SafeString("node")
id := uint64(e.NodeID)
if e.isStore {
  s = "store"
  id = uint64(e.StoreID)
}
p.Printf("%s descriptor with %s ID %d was not found", s, s, id)
```


(you could even collapse the two ID members into a single integer field)
___
*[`pkg/sql/sem/builtins/builtins.go` line 11161 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIvzM16kBiK1_l1Sy1:-NeIvzM2161SnSP3YHKq:b-42vd6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/sql/sem/builtins/builtins.go#L11161)):*
> ```Go
> 	for idx := range stmts {
> 		p, err := p.Pretty(stmts[idx].AST)
> 		if err != nil {
> ```

`errors.Is`


<!-- Sent from Reviewable.io -->

2023-09-14 14:12 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @michae2)

___
*[`pkg/kv/kvpb/errors.go` line 1662 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIvU6OBtPP0bDg9SLf:-NeIxwfQBO_AsCW0UUts:b14qjgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/kv/kvpb/errors.go#L1662)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: maybe
```go
s := redact.SafeString("node")
id := uint64(e.NodeID)
if e.isStore {
  s = "store"
  id = uint64(e.StoreID)
}
p.Printf("%s descriptor with %s ID %d was not found", s, s, id)
```


(you could even collapse the two ID members into a single integer field)
</blockquote></details>

:+1: Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 11161 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIvzM16kBiK1_l1Sy1:-NeIyjCn2qqUDl1MVRIV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/sql/sem/builtins/builtins.go#L11161)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`errors.Is`
</blockquote></details>

Done.
___
*[`pkg/util/pretty/pretty.go` line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIwt3yDTP0OEQLhPzK:-NeIwt3yDTP0OEQLhPzL:b-hcngqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/util/pretty/pretty.go#L135)):*
> ```Go
> // maxBeDepth is the maximum allowed recursive call depth of be. If the depth
> // exceeds this value, be will panic.
> const maxBeDepth = 10_000
> ```

I raised this back to 100,000 because [this test](https://github.com/cockroachdb/cockroach/blob/619f395b88e7089d12d7c4a44eaf409507d7f42c/pkg/sql/logictest/testdata/logic_test/sqllite#L7-L411) was failing to [pretty-round-trip](https://github.com/cockroachdb/cockroach/blob/82ea94705e353726623cbd879a4b53f1feac00c5/pkg/testutils/sqlutils/pretty.go#L22).


<!-- Sent from Reviewable.io -->

2023-09-14 14:36 UTC, knz approved these changes
LGTM modulo settling on the max size constant.

> Reviewed 1 of 19 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-NeJ6n3p8Vpi9FbN0uyW:b-gvhoe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/util/pretty/pretty.go` line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIwt3yDTP0OEQLhPzK:-NeJ6fIU278kn4Sy_y5r:b-hbq1ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/util/pretty/pretty.go#L135)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I raised this back to 100,000 because [this test](https://github.com/cockroachdb/cockroach/blob/619f395b88e7089d12d7c4a44eaf409507d7f42c/pkg/sql/logictest/testdata/logic_test/sqllite#L7-L411) was failing to [pretty-round-trip](https://github.com/cockroachdb/cockroach/blob/82ea94705e353726623cbd879a4b53f1feac00c5/pkg/testutils/sqlutils/pretty.go#L22).
</blockquote></details>

I would rather change the test than the constant here. These tests were not principled.


<!-- Sent from Reviewable.io -->

2023-09-15 15:16 UTC, mgartner commented
*[`pkg/util/pretty/pretty.go` line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIwt3yDTP0OEQLhPzK:-NeOP5ezEnRew3MQFM2H:bh58ge8) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/util/pretty/pretty.go#L135)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I would rather change the test than the constant here. These tests were not principled.
</blockquote></details>

The test looks like a regression test and it's not a terribly obscure case—it's an insert of ~400 rows. Shouldn't we be able to handle such a statement?


<!-- Sent from Reviewable.io -->

2023-09-15 16:39 UTC, knz commented
>  Shouldn't we be able to handle such a statement?

I would expect so, but not with a recursion depth of 100000. What is the effective recursion depth used for it?

2023-09-15 19:12 UTC, mgartner commented
The depth for that test grows to 19,361.

2023-09-15 20:58 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you for fixing this!

> Reviewed 8 of 28 files at r3, 6 of 31 files at r6, 25 of 25 files at r9, 11 of 11 files at r10, 15 of 19 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-:-NePcha3C3Rc_1bHV9V2:b-l7y28j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @mgartner)

___
*[`pkg/util/pretty/pretty.go` line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIwt3yDTP0OEQLhPzK:-NePa9-h-iyPYH4MEMki:b-8a0gaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/util/pretty/pretty.go#L135)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The test looks like a regression test and it's not a terribly obscure case—it's an insert of ~400 rows. Shouldn't we be able to handle such a statement?
</blockquote></details>

:shrug: I'm ok either way.

(Personally I think Go's default stack limit of 1 GiB is giant but I'm coming from a previous codebase where we could only use 20 KiB stacks, so I'm biased.)


<!-- Sent from Reviewable.io -->

2023-09-19 14:41 UTC, mgartner commented
*[`pkg/util/pretty/pretty.go` line 135 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/110374#-NeIwt3yDTP0OEQLhPzK:-NehsgCQ27JMXV5zAzaM:bxc5h32) ([raw file](https://github.com/cockroachdb/cockroach/blob/964e2ecc7ee657ab5e33d3d2fbae352b099be41f/pkg/util/pretty/pretty.go#L135)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

:shrug: I'm ok either way.

(Personally I think Go's default stack limit of 1 GiB is giant but I'm coming from a previous codebase where we could only use 20 KiB stacks, so I'm biased.)
</blockquote></details>

I updated it to 50,000, which allows the test to pass with plenty of buffer and also catches the stack overflow. Let me know what y'all think.


<!-- Sent from Reviewable.io -->

2023-09-19 15:19 UTC, knz commented
i'm ok with it.

2023-09-19 22:17 UTC, mgartner commented
TFTRs!

bors r+

2023-09-20 17:32 UTC, merged