compose/gss: unskip TestGSSFileDescriptorCount
cockroachdb/cockroach pull request #110370
Opened 2023-09-11 19:44 UTC by rafiss

The test did not work since it did not pass in the root password correctly.

fixes https://github.com/cockroachdb/cockroach/issues/110194

Release note: None

2023-09-11 19:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/110370)
<!-- Reviewable:end -->

2023-09-13 06:07 UTC, andyyang890 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NeC6TIa3z4zscfzfNzd:-NeC6TIa3z4zscfzfNze:bue11ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bf635f3677560f6469f3708713ed5c0d31f2546/pkg/acceptance/compose/gss/psql/gss_test.go#L192)):*
> ```Go
> }
> 
> func TestGSSFileDescriptorCount(t *testing.T) {
> ```

Would you mind adding a comment explaining what this test is validating exactly? From what I could glean by going through the git blame history, it was originally added to catch a bug where "replay cache file descriptors were incorrectly kept open" (https://github.com/cockroachdb/cockroach/commit/a018d826a0aaba7a6206fadb128f49408c67f951), but even that explanation feels like it's missing a lot of background context.
___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NeC6xwyA6dLehAYhMW7:-NeC6xwyA6dLehAYhMW8:bxi3eky) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bf635f3677560f6469f3708713ed5c0d31f2546/pkg/acceptance/compose/gss/psql/gss_test.go#L222)):*
> ```Go
> 	const adminURL = "https://cockroach:8080"
> 	fdCount := openFDCount(t, adminURL, cookie)
> 	if fdCount > numLogins {
> ```

From reading this condition, it seems like we expect each login to generate one more open file descriptor. Why is that?


<!-- Sent from Reviewable.io -->

2023-09-19 21:57 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NeC6TIa3z4zscfzfNzd:-NejRRKu2p-kN7HnfTIW:b-pw4zon) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bf635f3677560f6469f3708713ed5c0d31f2546/pkg/acceptance/compose/gss/psql/gss_test.go#L192)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Would you mind adding a comment explaining what this test is validating exactly? From what I could glean by going through the git blame history, it was originally added to catch a bug where "replay cache file descriptors were incorrectly kept open" (https://github.com/cockroachdb/cockroach/commit/a018d826a0aaba7a6206fadb128f49408c67f951), but even that explanation feels like it's missing a lot of background context.
</blockquote></details>

Added a comment with a bit more history, but I don't fully understand the issue myself apart from knowing that you need to call the cleanup function when a kerberos connection is done, and we didn't do that before.
___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NeC6xwyA6dLehAYhMW7:-NejRN5ZC_7coYsoSM_S:bypxiqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bf635f3677560f6469f3708713ed5c0d31f2546/pkg/acceptance/compose/gss/psql/gss_test.go#L222)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

From reading this condition, it seems like we expect each login to generate one more open file descriptor. Why is that?
</blockquote></details>

I think that was wrong, or at least not guaranteed. I have changed this a little.


<!-- Sent from Reviewable.io -->

2023-09-19 22:14 UTC, andyyang890 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NeC6TIa3z4zscfzfNzd:-NejTxGq1beCuFaLUQTo:b-k6rpao) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bf635f3677560f6469f3708713ed5c0d31f2546/pkg/acceptance/compose/gss/psql/gss_test.go#L192)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Added a comment with a bit more history, but I don't fully understand the issue myself apart from knowing that you need to call the cleanup function when a kerberos connection is done, and we didn't do that before.
</blockquote></details>

Sounds good, thanks!
___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTHkw12NE3tMqQdgw:-NejTHkw12NE3tMqQdgx:b-3ru1) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L16)):*
> ```Go
> 
> //go:bu ild gss_compose
> // +bu ild gss_compose
> ```

nit: extra spaces



_Suggestion:_
```Go
//go:build gss_compose
// +build gss_compose
```
___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTsGmCzZaCrV2HbEO:-NejTsGmCzZaCrV2HbEP:b-tsqaki) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L213)):*
> ```Go
> 	// Login once to initialize the kerberos replay cache.
> 	out, err := exec.Command("psql", "-c", "SELECT 1", "-U", user).CombinedOutput()
> 	if IsError(err, "GSS authentication requires an enterprise license") {
> ```

Do we not care if it's any other kind of error?


<!-- Sent from Reviewable.io -->

2023-09-20 04:06 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTHkw12NE3tMqQdgw:-Nekkic25WJ1AFKTvQz0:bnuay8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L16)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: extra spaces
</blockquote></details>

oh yeah, this is actually important, since the build tag determines what code the CI test runs. it was left left over from when i was debugging locally. thanks for the catch!
___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTsGmCzZaCrV2HbEO:-Nekl2Db32zi6vg4fBr-:b7bauv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L213)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Do we not care if it's any other kind of error?
</blockquote></details>

this was from when the test was originally written, but i agree it seems wrong. i'll try without.


<!-- Sent from Reviewable.io -->

2023-09-20 05:26 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTsGmCzZaCrV2HbEO:-Nel2456BqQ1O2DSyReD:b-o6k2gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L213)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this was from when the test was originally written, but i agree it seems wrong. i'll try without.
</blockquote></details>

actually, it seems like the error is expected. the `IsError` check seems wrong - it should actually be `!IsError`, based on the tests in `TestGSS`. i think this was never known since this test was skipped in the same PR it was added in

also, i noticed in the tests above that the error checking expects that we wrap the error with the command output


<!-- Sent from Reviewable.io -->

2023-09-20 05:52 UTC, andyyang890 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-:-Nel8DdADhzC6g_brpKE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTsGmCzZaCrV2HbEO:-Nel7V2NAyY2jcnT6pE2:b-msdf0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L213)):*
re `!IsError`: nice find! thanks for adding a comment too

> also, i noticed in the tests above that the error checking expects that we wrap the error with the command output

interesting, i guess that means `out` is the thing that should actually contain the expected error message?


<!-- Sent from Reviewable.io -->

2023-09-20 14:44 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110370)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890)

___
*[`pkg/acceptance/compose/gss/psql/gss_test.go` line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/110370#-NejTsGmCzZaCrV2HbEO:-Nen1dLGCu_BRtuEcAMN:b-aw01p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db9ddb9a6abbeae51d88a267aa920b6657f3bfd5/pkg/acceptance/compose/gss/psql/gss_test.go#L213)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

re `!IsError`: nice find! thanks for adding a comment too

> also, i noticed in the tests above that the error checking expects that we wrap the error with the command output

interesting, i guess that means `out` is the thing that should actually contain the expected error message?
</blockquote></details>

yeah `out` is the stdout/stderr, and it will have the textual error message. `err` is non-nil if the program exited with a nonzero exit code, but the error message just has the exit code and nothing else.

also, `errors.Wrap(nil, "...")` returns nil, so if the program had a zero exit code, `err` will still be nil after wrapping


<!-- Sent from Reviewable.io -->

2024-05-09 17:19 UTC, closed without merging