sql: fix index corruption in udfs with fk cascades
cockroachdb/cockroach pull request #111018
Opened 2023-09-21 03:19 UTC by rharding6373

This PR fixes an issue in which UDFs making a FK cascade could cause index corruption. It adds inbound foreign key origin tables to the statement tree, which is used to test for tables with multiple mutations.

No release note is necessary, since UDF mutation and FK cascade support is new in this release.

Epic: CRDB-25388
Informs: #87289

Release note: None

2023-09-21 03:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/111018)
<!-- Reviewable:end -->

2023-09-21 21:30 UTC, DrewKimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NetdmAV-DkIm1N19obG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2023-09-21 23:23 UTC, michae2 reviewed
Thanks for working on this!

I think this is slightly too strict. IIUC, I think it will disallow the following, which, unlike [this example](https://github.com/cockroachdb/cockroach/pull/103920#pullrequestreview-1484148310), does *not* cause index corruption:

```sql
CREATE TABLE jar (j INT PRIMARY KEY);
CREATE TABLE cookie (i INT PRIMARY KEY, j INT REFERENCES jar (j) ON UPDATE CASCADE ON DELETE CASCADE, INDEX (j));
INSERT INTO jar VALUES (0), (2);
INSERT INTO cookie VALUES (0, 0);

CREATE FUNCTION f2(k INT) RETURNS INT AS $$
  UPDATE cookie SET j = 2 WHERE i = k RETURNING i
$$ LANGUAGE SQL;

-- this should not cause corruption, and should be allowed
-- (the cascade to cookie will always be strictly after the function call)
UPDATE jar SET j = j + 1 WHERE j = f2(0);

-- can check by comparing
SELECT i, j FROM cookie@primary;
SELECT i, j FROM cookie@cookie_j_idx;
```

Because we [step the transaction sequence point](https://github.com/cockroachdb/cockroach/blob/fe0244d59a82211ef3e2d98420d579f7dd28a886/pkg/sql/distsql_running.go#L2075-L2081) before cascades, I think we need to do the equivalent thing and call [statementTree.Pop](https://github.com/cockroachdb/cockroach/blob/fe0244d59a82211ef3e2d98420d579f7dd28a886/pkg/sql/opt/optbuilder/statement_tree.go#L97-L110) before calling statementTree.CanMutateTable with any cascaded tables. But I'm not quite sure if that can be done safely in this part of optbuilder. :thinking:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NetrCefDFar1B4ahcjs:b-dw4jat)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2023-09-21 23:33 UTC, michae2 reviewed
One way to do it would be to walk the set of FK cascades immediately after the [current call to Pop](https://github.com/cockroachdb/cockroach/blob/c24f0ae1f4964ff4666d4573dd0370eaafc8cead/pkg/sql/opt/optbuilder/builder.go#L279). (Or alternatively, maybe it could somehow become part of Pop if that would be simpler?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-Neu4GTYEUvyuSEq9bL_:b4de9e4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2023-09-26 23:59 UTC, mgartner reviewed
I think you're correct @michae2 (I may need some more time to convince myself, though :confused: ). Do you think this pattern is common enough in a real-world use case to worry about for now? I'm skeptical that using mutating UDFs in a filter is common or useful. If it is used, I wonder if the behavior is well-understood by the user since it's so hard to wrap your brain around. Maybe we can just slap a TODO and/or make an issue and call it a day for now?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NfIuydN1UNi8bynu1I2:bnhhgak)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/opt/optbuilder/util.go` line 517 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfItDhJBDiOk4CzBbkK:-NfItDhJBDiOk4CzBbkL:b-kx2cbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/927b13f521d13c9a13958c11f31f8906d14dfae2/pkg/sql/opt/optbuilder/util.go#L517)):*
> ```Go
> }
> 
> func (b *Builder) checkMultipleMutations(tab cat.Table, typ mutationType, visited intsets.Fast) {
> ```

nit: You could add a small non-recursive function that doesn't require a `visited` arg since all the callers are passing in an empty set.
___
*[`pkg/sql/opt/optbuilder/util.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfIuf9NCSmZ3XzVy-o-:-NfIuf9NCSmZ3XzVy-o0:b-b4gip6) ([raw file](https://github.com/cockroachdb/cockroach/blob/927b13f521d13c9a13958c11f31f8906d14dfae2/pkg/sql/opt/optbuilder/util.go#L542)):*
> ```Go
> 		fk := tab.InboundForeignKey(i)
> 		if (fk.DeleteReferenceAction() != tree.NoAction && typ != simpleInsert) ||
> 			fk.UpdateReferenceAction() != tree.NoAction {
> ```

I believe we can avoid `tree.Restrict` actions too, since they don't mutate tables. I believe we support RESTRICT cascades, but I haven't verified, but noticed this: https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L127-L131


<!-- Sent from Reviewable.io -->

2023-09-27 03:39 UTC, rharding6373 reviewed
I did an equivalent to @michae2 's suggestion, which is to add a bool to `CanMutateTable` to indicate that this mutation is evaluated at the end of the statement. When true, it adds the mutation to the parent statement (if it exists) instead of the current statement. It appears to work. I need to add update the unit tests to exercise the new behavior, but wanted to get feedback/CI results due to the added complexity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NfJgYIW8NGfpVCc3SEj:b-bvck9b)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/opt/optbuilder/util.go` line 517 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfItDhJBDiOk4CzBbkK:-NfJasiz3gBRZaAbvZQp:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/927b13f521d13c9a13958c11f31f8906d14dfae2/pkg/sql/opt/optbuilder/util.go#L517)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: You could add a small non-recursive function that doesn't require a `visited` arg since all the callers are passing in an empty set.
</blockquote></details>

Refactored.
___
*[`pkg/sql/opt/optbuilder/util.go` line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfIuf9NCSmZ3XzVy-o-:-NfJalmZ32HRj9Z_zBwk:b-82yi2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/927b13f521d13c9a13958c11f31f8906d14dfae2/pkg/sql/opt/optbuilder/util.go#L542)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I believe we can avoid `tree.Restrict` actions too, since they don't mutate tables. I believe we support RESTRICT cascades, but I haven't verified, but noticed this: https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L127-L131
</blockquote></details>

Good call, done and added to the test case.


<!-- Sent from Reviewable.io -->

2023-09-27 14:17 UTC, mgartner approved these changes
Very nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NfLzkjy47_4433BhkZu:bup7q37)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

___
*[`pkg/sql/opt/optbuilder/statement_tree.go` line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfLzUe26Hecmh5NXLaO:-NfLzUe26Hecmh5NXLaP:b1o7lsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fc2c73cfdf610e21bb30dad52080932174775f9/pkg/sql/opt/optbuilder/statement_tree.go#L152)):*
> ```Go
> 	if isPostStmt {
> 		offset = 2
> 	}
> ```

nit: A short explanation of why we're checking two statements up the tree in the isPostStmt case might be helpful.


<!-- Sent from Reviewable.io -->

2023-09-27 22:03 UTC, michae2 requested changes
Nice! I think this just needs a small adjustment, mentioned below.

Also, not sure if related to that adjustment, but when playing with your branch I seem to get different results for `EXPLAIN` vs no `EXPLAIN`. Not sure why that is. For example, this fails for me with the error (just adding `EXPLAIN` to the example above):

```sql
CREATE TABLE jar (j INT PRIMARY KEY);
CREATE TABLE cookie (i INT PRIMARY KEY, j INT REFERENCES jar (j) ON UPDATE CASCADE ON DELETE CASCADE, INDEX (j));
INSERT INTO jar VALUES (0), (2);
INSERT INTO cookie VALUES (0, 0);

CREATE FUNCTION f2(k INT) RETURNS INT AS $$
  UPDATE cookie SET j = 2 WHERE i = k RETURNING i
$$ LANGUAGE SQL;

EXPLAIN UPDATE jar SET j = j + 1 WHERE j = f2(0);
```

But passes without the `EXPLAIN`.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NfNTi5W3sHkIfwCMXLf:b-26yd9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/statement_tree.go` line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-NfNWsq-AJxCssbp5Vf1:-NfNWsq-AJxCssbp5Vf2:bcwxieg) ([raw file](https://github.com/cockroachdb/cockroach/blob/156669d439dd4772fe4e8bc74a782878b55dbfac/pkg/sql/opt/optbuilder/statement_tree.go#L156)):*
> ```Go
> 		// check evaluations, so all updates in the current statement will be
> 		// visible.
> 		offset = 2
> ```

Very clever. I think it just needs some slight adjustment: if we are adding directly to the parent, I think we should be putting it into the parent's `childrenGeneralMutationTables` instead of the parent's `generalMutationTables`. This is because we don't want it to conflict with any additional checks for the current statement.

Also, I don't think we should be checking `curr.childrenConflictWithMutation` when curr is the parent, nor checking `n.conflictsWithMutation` when i = len(st.stmts-1).


<!-- Sent from Reviewable.io -->

2023-09-28 22:18 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111018#-:-NfSrgQeAqG4oZB2KUZq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2023-09-29 23:29 UTC, rharding6373 commented
TFTR!

bors r+

2023-09-30 00:10 UTC, merged