sql/pg_catalog: add dropped columns into pg_attribute
cockroachdb/cockroach pull request #111019
Opened 2023-09-21 03:36 UTC by fqazi

Previously, the attribute number generated inside pg_attribute could be sparse because there would be gaps after columns were or dropped. This could be problematic for ORMs since this would mean that attribute numbers could be sparse, and they may not be designed to handle such gaps. To address this, this patch adds dropped synthetic columns into the pg_attribute table, which allows these tools to work correctly.

Fixes: #110545

Release note (bug fix): pg_attribute could have sparsely populated attnum's since dropped columns were not included.

2023-09-21 03:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/111019)
<!-- Reviewable:end -->

2023-09-21 21:48 UTC, rafiss requested changes
nice, just a few nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-:-NethWA855oeQvhZywAU:b-9t5vl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/pg_catalog.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Netgx7m6V8ptx4lijLM:-Netgx7m6V8ptx4lijLN:b-r9trwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L413)):*
> ```Go
> 	) error {
> 		populatedColumns := intsets.Fast{}
> 		maxColumnID := 0
> ```

i think this should be called `maxPGAttributeNum`, and it should be based on the attnum rather than the ID
___
*[`pkg/sql/pg_catalog.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Neth7lc54UQ3SxgKOuX:-Neth7lc54UQ3SxgKOuY:br26wk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L492)):*
> ```Go
> 		// The next column ID may not be populated on certain relations like
> 		// sequences, so only use if it's available.
> 		if int(table.GetNextColumnID()) > maxColumnID {
> ```

why do we need this? i think if we do the above comment of tracking pgAttNums, we may not need this
___
*[`pkg/sql/pg_catalog.go` line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-NethNAQAG2GSOLqEh0H:-NethNAR3vilK2Fr43He:bhjcb1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L500)):*
> ```Go
> 		missingColumnType := types.Any
> 		if populatedColumns.Len() != maxColumnID {
> 			for colID := 1; colID <= maxColumnID; colID++ {
> ```

nit: instead of `colID` this should be called `colOrdinal`
___
*[`pkg/sql/pg_catalog.go` line 1882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-NetgBgsCkwAtmyAIk0f:-NetgBgsCkwAtmyAIk0g:b-vrqljt) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L1882)):*
> ```Go
> 					indoption := tree.NewDArray(types.Int)
> 
> 					colIDs := make([]descpb.ColumnID, 0, index.NumKeyColumns())
> ```

nit: can this be renamed to `collAttNums`?
___
*[`pkg/sql/pg_catalog.go` line 1922 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Netg7p8DYFYuqCPLioN:-Netg7p8DYFYuqCPLioO:bog0kra) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L1922)):*
> ```Go
> 					indnkeyatts := len(colIDs)
> 					for i := 0; i < index.NumSecondaryStoredColumns(); i++ {
> 						colIDs = append(colIDs, index.GetStoredColumnID(i))
> ```

should this also be the pgAttNum?


<!-- Sent from Reviewable.io -->

2023-09-22 15:25 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Netgx7m6V8ptx4lijLM:-NexNlni0HlIlv_qtcF1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L413)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this should be called `maxPGAttributeNum`, and it should be based on the attnum rather than the ID
</blockquote></details>

Done.
___
*[`pkg/sql/pg_catalog.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Neth7lc54UQ3SxgKOuX:-NexNmYY4NZ1EQKk5PFk:b-rdb8mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L492)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do we need this? i think if we do the above comment of tracking pgAttNums, we may not need this
</blockquote></details>

If we drop columns at the end of the table, we still want dropped entries to stay stable. We should see an entry if we drop the last column and query.  It should be there if we add a new column after entry. Otherwise, the behaviour won't be stable (not sure if we should worry about that).
___
*[`pkg/sql/pg_catalog.go` line 1922 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Netg7p8DYFYuqCPLioN:-NexPQI1BHaKBKz1Qqfk:b-4sm21s) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L1922)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this also be the pgAttNum?
</blockquote></details>

Yes that is definitely incorrect too, let me update that


<!-- Sent from Reviewable.io -->

2023-09-22 15:25 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1922 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-Netg7p8DYFYuqCPLioN:-NexUlcJ7fxdmbC7USgL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93a99eafc600f2585d15e8105d1d74f875539e10/pkg/sql/pg_catalog.go#L1922)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yes that is definitely incorrect too, let me update that
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-22 15:43 UTC, rafiss approved these changes
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111019#-:-NexYlag5UsMhtBCqwfy:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-09-22 16:05 UTC, fqazi commented
@rafiss TFTR!

bors r+

2023-09-22 16:45 UTC, merged