config: add a flag to allow disabling SQL services
cockroachdb/cockroach pull request #111298
Opened 2023-09-26 19:31 UTC by andrewbaptist

This change reduces the long startup time waiting for SQL services to start for tests that are KV layer and below.

Epic: none

Release note: None

2023-09-26 19:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/111298)
<!-- Reviewable:end -->

2023-09-26 19:40 UTC, andrewbaptist commented
As an example of a test before and after, I added a change to TestServerStartClock (as part of this PR).
Running
```
./dev test pkg/server -f TestServerStartClock --stress
```

Before:
```
//pkg/server:server_test                                                 PASSED in 2.9s
  Stats over 1000 runs: max = 2.9s, min = 1.2s, avg = 1.6s, dev = 0.2s
```

After:
```
//pkg/server:server_test                                                 PASSED in 2.2s
  Stats over 1000 runs: max = 2.2s, min = 0.8s, avg = 1.0s, dev = 0.2s
```

2023-09-27 15:26 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-:-NfMF-G325ZiUWP-LOyg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/server/config.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfIJ9sk6TMIVSEeANvW:-NfIJ9sk6TMIVSEeANvX:b-fie9le) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a27941951a22d9c02e07aa569ac74672124df8c/pkg/server/config.go#L251)):*
> ```Go
> 	DisableHTTPListener bool
> 
> 	//DisableSQLServer disables starting the SQL service for the given test. This
> ```

nit: missing space at the start of these comments
___
*[`pkg/server/config.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfIJFu8EtyRNoSoFrQn:-NfIJFu8EtyRNoSoFrQo:ba3uo39) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a27941951a22d9c02e07aa569ac74672124df8c/pkg/server/config.go#L252)):*
> ```Go
> 
> 	//DisableSQLServer disables starting the SQL service for the given test. This
> 	//also disables all upgrades as they rely on SQL and typically cuts ~1s off
> ```

nit: consider rephrasing this comment to not explicitly reference the "1s" number -- it might not age well.


<!-- Sent from Reviewable.io -->

2023-09-27 17:01 UTC, andrewbaptist reviewed
TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-:-NfM_afi6mrVi55jqKaw:bb73zsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @herkolategan, and @renatolabs)

___
*[`pkg/server/config.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfIJ9sk6TMIVSEeANvW:-NfM_Y114qIjdhhMFeOy:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a27941951a22d9c02e07aa569ac74672124df8c/pkg/server/config.go#L251)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: missing space at the start of these comments
</blockquote></details>

Fixed
___
*[`pkg/server/config.go` line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfIJFu8EtyRNoSoFrQn:-NfM_Z4LBNc3m2FEIRcd:b-4j07i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a27941951a22d9c02e07aa569ac74672124df8c/pkg/server/config.go#L252)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: consider rephrasing this comment to not explicitly reference the "1s" number -- it might not age well.
</blockquote></details>

Good point! Fixed


<!-- Sent from Reviewable.io -->

2023-09-27 17:01 UTC, andrewbaptist commented
bors r=arulajmani

2023-09-27 17:23 UTC, knz requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @herkolategan, and @renatolabs)

___
*[`pkg/server/server.go` line 2067 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfMdSGpC2KF5DNVvZlH:-NfMdSGqA-LYOB5ZNtEw:b-9fmqc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8544e5ae631368057e6fa66ffc5f2fbbe959dd91/pkg/server/server.go#L2067)):*
> ```Go
> 	s.node.recordJoinEvent(ctx)
> 
> 	if !s.cfg.DisableSQLServer {
> ```

You will need to also modify the following:

- `AcceptClients` and `AcceptInternalClients` in this file
- `(*testServer).Activate` in `testserver.go`  (but keep the goroutine that handles shutdown that's launched at the end of Activate
- `(*testServer).StartTenant` and `.StartSharedProcessTenant`
___
*[`pkg/server/server_test.go` line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfMeSdR1AufnJfnCYph:-NfMeSdR1AufnJfnCYpi:b-br4vpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8544e5ae631368057e6fa66ffc5f2fbbe959dd91/pkg/server/server_test.go#L172)):*
> ```Go
> 			},
> 		},
> 		DisableSQLServer: true,
> ```

A test in this package is not too telling sadly, because this package disables a few features in test server.

Try instead to create a test in `testutils/testcluster/testcluster_test.go`
And ensure it runs without errors with `dev test ... -- --test_env=COCKROACH_TEST_TENANT=true`.


<!-- Sent from Reviewable.io -->

2023-09-27 17:37 UTC, andrewbaptist commented
bors r-

2023-09-29 15:03 UTC, andrewbaptist reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @dhartunian, @herkolategan, @knz, and @renatolabs)

___
*[`pkg/server/server.go` line 2067 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfMdSGpC2KF5DNVvZlH:-NfS_m-1AVGAyQEPbaq_:b-sw8hhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8544e5ae631368057e6fa66ffc5f2fbbe959dd91/pkg/server/server.go#L2067)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

You will need to also modify the following:

- `AcceptClients` and `AcceptInternalClients` in this file
- `(*testServer).Activate` in `testserver.go`  (but keep the goroutine that handles shutdown that's launched at the end of Activate
- `(*testServer).StartTenant` and `.StartSharedProcessTenant`
</blockquote></details>

Thanks for these pointers! I updated all these methods to correctly handle this flag (either by not starting or throwing a clear error if it's a tenant test).  
___
*[`pkg/server/server_test.go` line 172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfMeSdR1AufnJfnCYph:-NfWQhVc1gOSsDnHHno-:beiajkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8544e5ae631368057e6fa66ffc5f2fbbe959dd91/pkg/server/server_test.go#L172)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

A test in this package is not too telling sadly, because this package disables a few features in test server.

Try instead to create a test in `testutils/testcluster/testcluster_test.go`
And ensure it runs without errors with `dev test ... -- --test_env=COCKROACH_TEST_TENANT=true`.
</blockquote></details>

I tested changing `TestClusterStart` to add the flag and verified it fails when called with `COCKROACH_TEST_TENANT=true` with a clear message saying that DisableSQLServer can't be used with tenant tests. I added it to all the tests that can support it (the ones that were setting `TestIsSpecificToStorageLayerAndNeedsASystemTenant`. 

running 
```
./dev test pkg/testutils/testcluster  --count=10 --stress -- --test_env=COCKROACH_TEST_TENANT=false
```

Before:
```
//pkg/testutils/testcluster:testcluster_test                             PASSED in 46.8s
  Stats over 10 runs: max = 46.8s, min = 25.9s, avg = 34.8s, dev = 7.9s
```

After:
```
//pkg/testutils/testcluster:testcluster_test                             PASSED in 37.6s
  Stats over 10 runs: max = 37.6s, min = 24.2s, avg = 26.9s, dev = 3.9s
```


<!-- Sent from Reviewable.io -->

2023-09-29 15:08 UTC, knz reviewed
Very nice, thanks.

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-:-NfWU2H11ZmZaswbvMLv:b-h1hkmp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @dhartunian, @herkolategan, and @renatolabs)

___
*[`pkg/server/tenant.go` line 908 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTCcj3uP_cHJry_mi:-NfWTCcj3uP_cHJry_mj:byro7sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/server/tenant.go#L908)):*
> ```Go
> func (s *SQLServerWrapper) AcceptClients(ctx context.Context) error {
> 	if s.sqlServer.cfg.DisableSQLServer {
> 		return errors.AssertionFailedf("programming error: attempt to set DisableSQLServer on a system with a tenant")
> ```

Here and below, let's rephrase this error to make it clearer what the person reading this can do about it:

```
programming error: DisableSQLServer is incompatible with cluster virtualization\n
Consider using TestServerArgs{DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant}
```
___
*[`pkg/server/testserver.go` line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTpQ77us5npRqg84I:-NfWTpQ77us5npRqg84J:b-z3p5ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/server/testserver.go#L592)):*
> ```Go
> 
> 	if ts.params.DisableSQLServer {
> 		return errors.AssertionFailedf("programming error: attempt to set DisableSQLServer on a system with a tenant")
> ```

ditto above
___
*[`pkg/testutils/testcluster/testcluster_test.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTz0j9rFuA-fR0PZF:-NfWTz0j9rFuA-fR0PZG:b2d4dh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/testutils/testcluster/testcluster_test.go#L153)):*
> ```Go
> 		ServerArgs: base.TestServerArgs{
> 			DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
> 			DisableSQLServer:  true,
> ```

Please ensure that all these tests work both with and without your new flag (`testutils.RunTrueAndFalse`).


<!-- Sent from Reviewable.io -->

2023-09-29 15:10 UTC, knz commented
also maybe consider placing the error constructor in a helper in package `serverutils` so the code is generated just once.

2023-09-29 16:40 UTC, andrewbaptist reviewed
I added this to serverutils. That helps with cut and paste and allows us to evolve the error. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-:-NfWa8s0AFPhWKpri8mU:br8g7bk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @dhartunian, @herkolategan, @knz, and @renatolabs)

___
*[`pkg/server/tenant.go` line 908 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTCcj3uP_cHJry_mi:-NfWa6dI2NVrODmUR-wk:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/server/tenant.go#L908)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Here and below, let's rephrase this error to make it clearer what the person reading this can do about it:

```
programming error: DisableSQLServer is incompatible with cluster virtualization\n
Consider using TestServerArgs{DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant}
```
</blockquote></details>

Done
___
*[`pkg/server/testserver.go` line 592 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTpQ77us5npRqg84I:-NfWa7ii5YxIFXDMmGdG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/server/testserver.go#L592)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto above
</blockquote></details>

Done
___
*[`pkg/testutils/testcluster/testcluster_test.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTz0j9rFuA-fR0PZF:-NfWXLjZ-zE3ovrwjrjc:bqlzlqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/testutils/testcluster/testcluster_test.go#L153)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please ensure that all these tests work both with and without your new flag (`testutils.RunTrueAndFalse`).
</blockquote></details>

Yes - I checked this and they all do.
After this patch:
```
diff --git a/pkg/testutils/testcluster/testcluster_test.go b/pkg/testutils/testcluster/testcluster_test.go
index dffd35a20a8..9b67db23b89 100644
--- a/pkg/testutils/testcluster/testcluster_test.go
+++ b/pkg/testutils/testcluster/testcluster_test.go
@@ -37,7 +37,7 @@ func TestClusterStart(t *testing.T) {
        defer leaktest.AfterTest(t)()
        defer log.Scope(t).Close(t)

-       tc := StartTestCluster(t, 3, base.TestClusterArgs{})
+       tc := StartTestCluster(t, 3, base.TestClusterArgs{ServerArgs: base.TestServerArgs{DisableSQLServer: true}})
        defer tc.Stopper().Stop(context.Background())
 }
```

Here is the error when running with TEST_TENANT
```
% ./dev test pkg/testutils/testcluster  -- --test_env=COCKROACH_TEST_TENANT=true
$ bazel test pkg/testutils/testcluster:all --test_env=GOTRACEBACK=all --test_output errors --test_env=COCKROACH_TEST_TENANT=true
...
INFO: From Testing //pkg/testutils/testcluster:testcluster_test:
==================== Test output for //pkg/testutils/testcluster:testcluster_test:
...
test logs left over in: /Users/abaptist/go/test/_tmp/48376418aa47ecb961754d8a2240227a/logTestClusterStart1551654134
--- FAIL: TestClusterStart (4.15s)
    test_log_scope.go:167: test logs captured to: /Users/abaptist/go/test/_tmp/48376418aa47ecb961754d8a2240227a/logTestClusterStart1551654134
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:101: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
        (override via COCKROACH_TEST_TENANT)
    testcluster.go:479: programming error: DisableSQLServer is incompatible with cluster virtualization
        Consider using TestServerArgs{DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant}
    panic.go:522: -- test log scope end --
FAIL
```



<!-- Sent from Reviewable.io -->

2023-09-29 16:55 UTC, knz reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @dhartunian, @herkolategan, and @renatolabs)

___
*[`pkg/server/tenant.go` line 909 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWqj850-cZP-eEUzxG:-NfWqj850-cZP-eEUzxH:b-r04vb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2dfbf9c9342c889918b55c13536f2c828ab3d4/pkg/server/tenant.go#L909)):*
> ```Go
> func (s *SQLServerWrapper) AcceptClients(ctx context.Context) error {
> 	if s.sqlServer.cfg.DisableSQLServer {
> 		return serverutils.PreventDisableSQLForTenantError
> ```

pro tip: make the error a constructor function, this way it will report the stack trace of where the error was found.
(not blocking)
___
*[`pkg/testutils/testcluster/testcluster_test.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTz0j9rFuA-fR0PZF:-NfWqsheDrsPIs9myO2b:b-uydksq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/testutils/testcluster/testcluster_test.go#L153)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Yes - I checked this and they all do.
After this patch:
```
diff --git a/pkg/testutils/testcluster/testcluster_test.go b/pkg/testutils/testcluster/testcluster_test.go
index dffd35a20a8..9b67db23b89 100644
--- a/pkg/testutils/testcluster/testcluster_test.go
+++ b/pkg/testutils/testcluster/testcluster_test.go
@@ -37,7 +37,7 @@ func TestClusterStart(t *testing.T) {
        defer leaktest.AfterTest(t)()
        defer log.Scope(t).Close(t)

-       tc := StartTestCluster(t, 3, base.TestClusterArgs{})
+       tc := StartTestCluster(t, 3, base.TestClusterArgs{ServerArgs: base.TestServerArgs{DisableSQLServer: true}})
        defer tc.Stopper().Stop(context.Background())
 }
```

Here is the error when running with TEST_TENANT
```
% ./dev test pkg/testutils/testcluster  -- --test_env=COCKROACH_TEST_TENANT=true
$ bazel test pkg/testutils/testcluster:all --test_env=GOTRACEBACK=all --test_output errors --test_env=COCKROACH_TEST_TENANT=true
...
INFO: From Testing //pkg/testutils/testcluster:testcluster_test:
==================== Test output for //pkg/testutils/testcluster:testcluster_test:
...
test logs left over in: /Users/abaptist/go/test/_tmp/48376418aa47ecb961754d8a2240227a/logTestClusterStart1551654134
--- FAIL: TestClusterStart (4.15s)
    test_log_scope.go:167: test logs captured to: /Users/abaptist/go/test/_tmp/48376418aa47ecb961754d8a2240227a/logTestClusterStart1551654134
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:101: automatically injected virtual cluster under test; see comment at top of test_server_shim.go for details.
        (override via COCKROACH_TEST_TENANT)
    testcluster.go:479: programming error: DisableSQLServer is incompatible with cluster virtualization
        Consider using TestServerArgs{DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant}
    panic.go:522: -- test log scope end --
FAIL
```

</blockquote></details>

That's not what I meant. I can see it works _today_ but we must prevent a regression which will cause these case to subtly fail when `DisableSQLServer: false` is passed.

So what I mean is something like this:

```go
testutils.RunTrueAndFalse("sql-enabled", func(t *testing.T, enabled bool) {
   var testTenant base.TestTenantOptions
   if !enabled {
      testTenant = base.TestIsSpecificToStorageLayerAndNeedsASystemTenant
   }
   serverArgs = base.ServerArgs{DefaultTestTenant: testTenant, DisableSQLServer: true}
   ... remainder of test, e.g. via function call ...
})
```       


<!-- Sent from Reviewable.io -->

2023-09-29 16:55 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @dhartunian, @herkolategan, and @renatolabs)

___
*[`pkg/testutils/testcluster/testcluster_test.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111298#-NfWTz0j9rFuA-fR0PZF:-NfWrTBP0HP2b5AZX-U_:b-2p1rm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f8f51f9171bad07b7f8900ee6e48e21ac0eb59/pkg/testutils/testcluster/testcluster_test.go#L153)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

That's not what I meant. I can see it works _today_ but we must prevent a regression which will cause these case to subtly fail when `DisableSQLServer: false` is passed.

So what I mean is something like this:

```go
testutils.RunTrueAndFalse("sql-enabled", func(t *testing.T, enabled bool) {
   var testTenant base.TestTenantOptions
   if !enabled {
      testTenant = base.TestIsSpecificToStorageLayerAndNeedsASystemTenant
   }
   serverArgs = base.ServerArgs{DefaultTestTenant: testTenant, DisableSQLServer: true}
   ... remainder of test, e.g. via function call ...
})
```
</blockquote></details>

i meant to write `DisableSQLServer: enabled`


<!-- Sent from Reviewable.io -->

2023-10-02 20:05 UTC, knz approved these changes
> Reviewed 1 of 4 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111298)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @arulajmani, @dhartunian, @herkolategan, and @renatolabs)



<!-- Sent from Reviewable.io -->

2023-10-02 21:27 UTC, andrewbaptist commented
bors r=knz

2023-10-02 22:13 UTC, merged