ui: switch order of metrics
cockroachdb/cockroach pull request #111467
Opened 2023-09-28 23:39 UTC by maryliag

On chart Replication -> Ranges, swithc order of Metrics so that the `Unavailable` metric is the red line.
Otherwise could be confusing seeing any other as Red, and the `Unavailable` as green.

Fixes #107637

Before
<img width="857" alt="Screenshot 2023-09-28 at 7 49 55 PM" src="https://github.com/cockroachdb/cockroach/assets/1017486/88af7e07-3c58-463d-963c-d47a3dd3f7c3">

After
<img width="915" alt="Screenshot 2023-09-28 at 7 50 33 PM" src="https://github.com/cockroachdb/cockroach/assets/1017486/29eae033-51b0-4399-89d9-06ecea82fa48">

Release note: None

2023-09-28 23:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/111467)
<!-- Reviewable:end -->

2023-09-29 14:33 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfWLNXJ1VxTUINVcbTS:-NfWLNXJ1VxTUINVcbTT:b-bsnqah) (no related file):*
Would it be more robust to explicitly define expected color for series like this?
https://github.com/cockroachdb/cockroach/blob/1e1877c787b216882f652ab711eddb08fba82189/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L181-L189

___


<!-- Sent from Reviewable.io -->

2023-09-29 20:10 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfWLNXJ1VxTUINVcbTS:-NfXYw7Y9BRhvmXJVkxV:bb7f2mf) (no related file):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Would it be more robust to explicitly define expected color for series like this?
https://github.com/cockroachdb/cockroach/blob/1e1877c787b216882f652ab711eddb08fba82189/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L181-L189
</blockquote></details>

done

___


<!-- Sent from Reviewable.io -->

2023-10-02 09:57 UTC, koorosh requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfjjL-4-R8fzwoRPkhD:-NfjjL-582nSPaQPWAyb:bwmpzcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/338c35724a9e90f87f16651413df22523cd8a6fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L40)):*
> ```XML
>   } = props;
> 
>   const rangesColorPalette = [
> ```

Pulling list of colors out of `configureUPlotLineChart` doesn't resolve main concern - it still doesn't guarantee proper mapping specific color to specific metric. Changing order would break this, and it is not obvious that we want to keep specific color to specific metric.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfjhYzI1DAmJKn7dht_:-NfjhYzI1DAmJKn7dhta:bjva6o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/338c35724a9e90f87f16651413df22523cd8a6fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L65)):*
> ```XML
>     >
>       <Axis label="ranges">
>         <Metric name="cr.store.ranges" title="Ranges" />
> ```

Why don't just specify desired color for specific metric (ie `<Metric name="cr.store.ranges" title="Ranges" color="#XXXXX" />`?

Then it is possible to handle this inside of `configureUPlotLineChart` function.

```diff

Subject: [PATCH] Set custom color to metrics.
---
Index: pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts b/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
--- a/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts	(date 1696240383735)
@@ -46,6 +46,7 @@
   key: string;
   area: boolean;
   fillOpacity: number;
+  color?: string;
 };
 
 export function formatMetricData(
@@ -68,6 +69,7 @@
         key: s.props.title || s.props.name,
         area: true,
         fillOpacity: 0.1,
+        color: s.props.color
       });
     }
   });
@@ -95,7 +97,11 @@
   // below to cycle through the colors. This ensures that we always
   // start from the same color for each graph so a single-series
   // graph will always have the first color, etc.
-  const strokeColors = [...seriesPalette];
+  const strokeColors = _.without(
+    seriesPalette,
+    // Exclude custom colors provided in metrics from default list of colors.
+    ...formattedRaw.filter(r => !!r.color).map(r => r.color)
+  );
 
   const tooltipPlugin = () => {
     return {
@@ -179,8 +185,15 @@
       // Generate a series object for reach of our results
       // picking colors from our palette.
       ...formattedRaw.map(result => {
-        const color = strokeColors.shift();
-        strokeColors.push(color);
+        let color: string;
+        // Assign custom provided color, otherwise assign from
+        // the list of default colors.
+        if (!!result.color) {
+          color = result.color
+        } else {
+          color = strokeColors.shift();
+          strokeColors.push(color);
+        }
         return {
           show: true,
           scale: "yAxis",
Index: pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
--- a/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx	(date 1696239646735)
@@ -46,12 +46,12 @@
       <Axis label="ranges">
         <Metric name="cr.store.ranges" title="Ranges" />
         <Metric name="cr.store.replicas.leaders" title="Leaders" />
-        <Metric name="cr.store.replicas.leaseholders" title="Lease Holders" />
+        <Metric name="cr.store.replicas.leaseholders" title="Lease Holders" color="green" />
         <Metric
           name="cr.store.replicas.leaders_not_leaseholders"
           title="Leaders w/o Lease"
         />
-        <Metric name="cr.store.ranges.unavailable" title="Unavailable" />
+        <Metric name="cr.store.ranges.unavailable" title="Unavailable" color="red"/>
         <Metric
           name="cr.store.ranges.underreplicated"
           title="Under-replicated"
Index: pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx b/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx
--- a/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx	(date 1696239646726)
@@ -90,6 +90,7 @@
   tenantSource?: string;
   title?: string;
   rate?: boolean;
+  color?: string;
 
   // How much to multiply the value of the underlying metric, for example if the
   // metric was a duration stored in seconds you'd need a scale of 1_000_000_000


```


<!-- Sent from Reviewable.io -->

2023-10-03 16:29 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfjjL-4-R8fzwoRPkhD:-NfqMrdX0iHT-07bDJeA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/338c35724a9e90f87f16651413df22523cd8a6fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L40)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Pulling list of colors out of `configureUPlotLineChart` doesn't resolve main concern - it still doesn't guarantee proper mapping specific color to specific metric. Changing order would break this, and it is not obvious that we want to keep specific color to specific metric.
</blockquote></details>

Done
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfjhYzI1DAmJKn7dht_:-NfqMtjU2vCCVu5sZ5Fg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/338c35724a9e90f87f16651413df22523cd8a6fc/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L65)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Why don't just specify desired color for specific metric (ie `<Metric name="cr.store.ranges" title="Ranges" color="#XXXXX" />`?

Then it is possible to handle this inside of `configureUPlotLineChart` function.

```diff

Subject: [PATCH] Set custom color to metrics.
---
Index: pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts b/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
--- a/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts	(date 1696240383735)
@@ -46,6 +46,7 @@
   key: string;
   area: boolean;
   fillOpacity: number;
+  color?: string;
 };
 
 export function formatMetricData(
@@ -68,6 +69,7 @@
         key: s.props.title || s.props.name,
         area: true,
         fillOpacity: 0.1,
+        color: s.props.color
       });
     }
   });
@@ -95,7 +97,11 @@
   // below to cycle through the colors. This ensures that we always
   // start from the same color for each graph so a single-series
   // graph will always have the first color, etc.
-  const strokeColors = [...seriesPalette];
+  const strokeColors = _.without(
+    seriesPalette,
+    // Exclude custom colors provided in metrics from default list of colors.
+    ...formattedRaw.filter(r => !!r.color).map(r => r.color)
+  );
 
   const tooltipPlugin = () => {
     return {
@@ -179,8 +185,15 @@
       // Generate a series object for reach of our results
       // picking colors from our palette.
       ...formattedRaw.map(result => {
-        const color = strokeColors.shift();
-        strokeColors.push(color);
+        let color: string;
+        // Assign custom provided color, otherwise assign from
+        // the list of default colors.
+        if (!!result.color) {
+          color = result.color
+        } else {
+          color = strokeColors.shift();
+          strokeColors.push(color);
+        }
         return {
           show: true,
           scale: "yAxis",
Index: pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
--- a/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx	(date 1696239646735)
@@ -46,12 +46,12 @@
       <Axis label="ranges">
         <Metric name="cr.store.ranges" title="Ranges" />
         <Metric name="cr.store.replicas.leaders" title="Leaders" />
-        <Metric name="cr.store.replicas.leaseholders" title="Lease Holders" />
+        <Metric name="cr.store.replicas.leaseholders" title="Lease Holders" color="green" />
         <Metric
           name="cr.store.replicas.leaders_not_leaseholders"
           title="Leaders w/o Lease"
         />
-        <Metric name="cr.store.ranges.unavailable" title="Unavailable" />
+        <Metric name="cr.store.ranges.unavailable" title="Unavailable" color="red"/>
         <Metric
           name="cr.store.ranges.underreplicated"
           title="Under-replicated"
Index: pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx b/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx
--- a/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx	(revision d5aac4eada76071cd44f6c272748e0dd1d91886d)
+++ b/pkg/ui/workspaces/db-console/src/views/shared/components/metricQuery/index.tsx	(date 1696239646726)
@@ -90,6 +90,7 @@
   tenantSource?: string;
   title?: string;
   rate?: boolean;
+  color?: string;
 
   // How much to multiply the value of the underlying metric, for example if the
   // metric was a duration stored in seconds you'd need a scale of 1_000_000_000


```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-03 16:38 UTC, koorosh reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfqOJt53nrQpq1RF4cH:-NfqOJt53nrQpq1RF4cI:b-5d3ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e8f5cf642688360aee2568d60220a7b0434cc0/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L75)):*
> ```XML
>       tenantSource={tenantSource}
>       tooltip={`The number of replicas on each node.`}
>       showMetricsInTooltip={true}
> ```

Is this change relevant to this PR? (same for places with added `showMetricsInTooltip={true}` prop)


<!-- Sent from Reviewable.io -->

2023-10-03 17:10 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx` line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-NfqOJt53nrQpq1RF4cH:-NfqW96Y1-zH8dvTBeax:b509h6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e8f5cf642688360aee2568d60220a7b0434cc0/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx#L75)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Is this change relevant to this PR? (same for places with added `showMetricsInTooltip={true}` prop)
</blockquote></details>

I think you're looking at the stage of the merge conflict, after I rebased with master. If you select to see the diff on this file based on master, this line won't show up


<!-- Sent from Reviewable.io -->

2023-10-03 18:26 UTC, koorosh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111467#-:-NfqmZGt5xgN7GNKlHbi:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)



<!-- Sent from Reviewable.io -->

2023-10-03 19:00 UTC, maryliag commented
TFTR!

bors r+

2023-10-03 20:10 UTC, merged