cdc: Expand mix-version test to use new mux rangefeed setting
cockroachdb/cockroach pull request #111498
Opened 2023-09-29 13:32 UTC by miretskiy

Expand cdc mix-version test to enable mux rangefeed and the use of new rangefeed scheduler in during mixed version test.

Expand regular cdc tests to support new rangefeed scheduler setting.

Closes #110348
Epic: CRDB-26372

Release note: None

2023-09-29 13:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/111498)
<!-- Reviewable:end -->

2023-09-29 16:09 UTC, jayshrivastava requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWevtN9IR0VPo0m97_:-NfWevtN9IR0VPo0m97a:b-fbjx40) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2427)):*
> ```Go
> 	cfc.logger.Printf("Setting kv.rangefeed.scheduler.enabled to %t", cfc.flags.RangeFeedScheduler.enabled())
> 	if _, err := cfc.db.Exec(
> 		"SET CLUSTER SETTING kv.rangefeed.scheduler.enabled = $1", cfc.flags.RangeFeedScheduler.enabled(),
> ```

For both of these, you should call `enabled()` once and save the value. The return value can change each time u call it.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWf18N8EnoZGpPtdku:-NfWf18N8EnoZGpPtdkv:bxhz7tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/522df7667ada964489bc8034a9b047f7bd594a6c/pkg/cmd/roachtest/tests/mixed_version_backup.go#L90)):*
> ```Go
> 	}
> 
> 	v231 = version.MustParse("v23.1.0")
> ```

Did you mean to delete this?
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWgc9w6t6pkFQ8HUBj:-NfWgc9w6t6pkFQ8HUBk:b-5h7n1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L438)):*
> ```Go
> 	// (and since v222 is the earliest version supported by mixed version testing,
> 	// this method may be called without additional version checks).
> 	setMuxRangeFeedEnabled := func(ctx context.Context, l *logger.Logger, r *rand.Rand, h *mixedversion.Helper) error {
> ```

nit: these can both just be one function. They also don't need to be closures. They can be methods on the `*tester`.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWfa6-3BQBRGi9WZD8:-NfWfa6-3BQBRGi9WZD9:blq2t64) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L455)):*
> ```Go
> 
> 	// Register hooks.
> 	mvt.OnStartup("use mux", setMuxRangeFeedEnabled)
> ```

These are all executed concurrently, so it's possible that the changefeed starts before the settings are changed.

If you look at `createChangefeed`, there is a channel which waits for the workload to be initialized before starting. I think we can use another channel for these settings.


<!-- Sent from Reviewable.io -->

2023-09-29 16:21 UTC, miretskiy reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWevtN9IR0VPo0m97_:-NfWj2S_CKswLNFzv4Qi:b-pnirlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2427)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

For both of these, you should call `enabled()` once and save the value. The return value can change each time u call it.
</blockquote></details>

not needed -- I made enable() memoize result on the first value:
```
if f.v != nil {
		return *f.v
	}
	if rand.Int()%2 == 0 {
		f.v = &featureEnabled
		return true
```
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWf18N8EnoZGpPtdku:-NfWiyZdAftGgwOf6jOn:b-o5d5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/522df7667ada964489bc8034a9b047f7bd594a6c/pkg/cmd/roachtest/tests/mixed_version_backup.go#L90)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Did you mean to delete this?
</blockquote></details>

Yes; these moved to version.go -- didn't feel right to use constants defined in "backup" test.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWgc9w6t6pkFQ8HUBj:-NfWjDtE--H_VCyXKBCt:b318ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L438)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

nit: these can both just be one function. They also don't need to be closures. They can be methods on the `*tester`.
</blockquote></details>

I wanted to keep them separate -- was initially thinking that I will need more complex version gates.
But regardless, these are different settings, and they will probably be retired/deprecated at different times.
It sort of makes sense to keep them separate, and also use different "coin" because both settings can be set independently.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWfa6-3BQBRGi9WZD8:-NfWjbnF4YAXDDZ2a-6k:b-e7yqsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L455)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

These are all executed concurrently, so it's possible that the changefeed starts before the settings are changed.

If you look at `createChangefeed`, there is a channel which waits for the workload to be initialized before starting. I think we can use another channel for these settings.
</blockquote></details>

Perfect :) 
More randomness.


<!-- Sent from Reviewable.io -->

2023-09-29 16:25 UTC, jayshrivastava approved these changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWevtN9IR0VPo0m97_:-NfWk3HS8F-bFDOTbtV-:b-619lsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2427)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

not needed -- I made enable() memoize result on the first value:
```
if f.v != nil {
		return *f.v
	}
	if rand.Int()%2 == 0 {
		f.v = &featureEnabled
		return true
```
</blockquote></details>

Oops. Youre right
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWgc9w6t6pkFQ8HUBj:-NfWkO_39n484ZH4n_Cs:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L438)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wanted to keep them separate -- was initially thinking that I will need more complex version gates.
But regardless, these are different settings, and they will probably be retired/deprecated at different times.
It sort of makes sense to keep them separate, and also use different "coin" because both settings can be set independently.
</blockquote></details>

Ack.
___
*[`pkg/cmd/roachtest/tests/version.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWkWyFA-OgKO2JZeSg:-NfWkWyGBDO64yZRvyzc:bgcgf18) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/version.go#L39)):*
> ```Go
> 	// restores. We are only interested in releases where we are still
> 	// actively fixing bugs in patch releases.
> 	minActivelySupportedVersion = v222
> ```

nit: consider adding backup/restore to the name.


<!-- Sent from Reviewable.io -->

2023-09-29 16:26 UTC, miretskiy commented
> nit: consider adding backup/restore to the name.

I don't think it talks about restart -- this is the min supported version by mixed version testing framework.

2023-09-29 17:10 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/version.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWkWyFA-OgKO2JZeSg:-NfWum395F0-90WjitLP:b-bqzpqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/version.go#L39)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

nit: consider adding backup/restore to the name.
</blockquote></details>

I was confused because the comment on the variable says "should be active for this test to perform any backups or restores"


<!-- Sent from Reviewable.io -->

2023-09-29 17:12 UTC, miretskiy commented
bors r+

2023-09-29 17:58 UTC, renatolabs commented
Discussed with Yevgeniy, I have a couple of comments and I think this will flake. Canceling for now.

bors r-

2023-09-29 19:18 UTC, renatolabs requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXGQJA7BwPJciiDWzX:-NfXGQJA7BwPJciiDWzY:b-kggt9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L404)):*
> ```Go
> )
> 
> func (f *featureFlag) enabled() bool {
> ```

Consider passing a random number generator to this function. The mixedversion library goes a long way to make sure that, while a lot of steps are randomized, running the test with the same random seed (via `COCKROACH_RANDOM_SEED`) leads to the same test run. This allows us to attempt to reproduce test failures without changing the code -- we just need to copy the seed reported in the error message and run the test with that seed.

In this function, we're using the global RNG to decide whether to enable or disable the feature flag, going against that principle and making the reproduction of test failures more difficult -- one will need to look at the logs and hardcode certain values via code changes.

*****

Something else to consider, potentially for the future: custom probabilities for whether a setting is enabled (or any random choices). I think it leads to more interesting scenarios, and our experience with the mixed-version backup test supports that.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXFmrS8MtC9EEjV4x8:-NfXFmrS8MtC9EEjV4x9:bdswnu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2421)):*
> ```Go
> 	cfc.logger.Printf("Setting changefeed.mux_rangefeed.enabled to %t", cfc.flags.MuxRangefeed.enabled())
> 	if _, err := cfc.db.Exec(
> 		"SET CLUSTER SETTING changefeed.mux_rangefeed.enabled = $1", cfc.flags.MuxRangefeed.enabled(),
> ```

I'm not sure it's a good idea for us to flip these cluster settings every time a changefeed is created. Two cases that come to mind where this behaviour is not ideal are: 1) a test wants finer control of when and how the settings are set (I think the mixedversion test, for example, does); and 2) if a test creates N changefeeds, it's unexpected (to me) to change these settings randomly each time.

I think these settings should live outside `Create()`. They could still be packaged into a function to make their consumption easier.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXHiI74G8_dcMXkk_h:-NfXHiI74G8_dcMXkk_i:b-qc33rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2425)):*
> ```Go
> 		return -1, err
> 	}
> 	cfc.logger.Printf("Setting kv.rangefeed.scheduler.enabled to %t", cfc.flags.RangeFeedScheduler.enabled())
> ```

The mixedversion test also uses this changefeed creator, and the function is called when the cluster is still running older versions. This will cause the test to fail deterministically on every run of the mixed-version test.

(Another reason to remove these cluster settings from `Create()` IMO).
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXJiolEvWZEnSAoAkP:-NfXJiolEvWZEnSAoAkQ:b-cd2424) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L437)):*
> ```Go
> 	// MuxRangefeed in various forms is available starting from v22.2
> 	// (and since v222 is the earliest version supported by mixed version testing,
> 	// this method may be called without additional version checks).
> ```

This is not accurate -- by default, mixedversion tests may perform up to 3 upgrades in a test run -- this means that for master, clusters may be bootstrapped at 22.1. This is configurable though: if you wanted, there's an option to specify how many upgrades you want to run. That said, it's probably better to just gate this cluster setting with `version.MustParse("v" + h.Context().FromVersion).AtLeast(v222)`
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXKrpR703KlCwofQFM:-NfXKrpR703KlCwofQFN:b34194d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L446)):*
> ```Go
> 	// Rangefeed scheduler available in 23.2
> 	setRangeFeedSchedulerEnabled := func(ctx context.Context, l *logger.Logger, r *rand.Rand, h *mixedversion.Helper) error {
> 		if h.LowestBinaryVersion().AtLeast(v232) {
> ```

In its current implementation, `LowestBinaryVersion` doesn't work when called during `AfterUpgradeFinalized`, as it's done here (this should be better documented, apologies). It will fail to parse a meaningful version when every node is upgraded to current cockroach since that doesn't have a "released" version.

Two options:

1. Explicitly check for this condition:

```go
// the version we upgraded to is the current, and the set of upgraded nodes is "every node"
allNodesUpgradedToCurrent := h.Context().ToVersion == clusterupgrade.MainVersion && len(h.Context().ToVersionNodes) == len(tester.crdbNodes)
if allNodesUpgradedToCurrent || h.LowestBinaryVersion().AtLeast(v232) {
   // ...
}
```

2. Check the cluster version directly:

```go
_, db := h.RandomDB()
cv, err := clusterupgrade.ClusterVersion(ctx, db)
if cvIsAtLeast(cv, "23.1") {
    // ...
}
```
___
*[`pkg/cmd/roachtest/tests/version.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWkWyFA-OgKO2JZeSg:-NfX4LXbBnRGKNx2GW0y:b-lbs5t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/version.go#L39)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I was confused because the comment on the variable says "should be active for this test to perform any backups or restores"
</blockquote></details>

Yes, this variable is related to the backup test specifically. It's the minimum version before which that test won't attempt any backups or restores. The mixedversion framework itself doesn't have an official "minimum version" requirement since the few SQL statements it performs have been around for a long time (i.e., setting cluster version, preserve_downgrade_option, etc).

I suggest moving this back to `mixed_version_backup.go`. Feel free to include `backup` in the name somewhere if you feel that makes the intention clearer.


<!-- Sent from Reviewable.io -->

2023-10-02 18:16 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXGQJA7BwPJciiDWzX:-Nfkidc7574DNv4A4tEy:brt6gcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L404)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Consider passing a random number generator to this function. The mixedversion library goes a long way to make sure that, while a lot of steps are randomized, running the test with the same random seed (via `COCKROACH_RANDOM_SEED`) leads to the same test run. This allows us to attempt to reproduce test failures without changing the code -- we just need to copy the seed reported in the error message and run the test with that seed.

In this function, we're using the global RNG to decide whether to enable or disable the feature flag, going against that principle and making the reproduction of test failures more difficult -- one will need to look at the logs and hardcode certain values via code changes.

*****

Something else to consider, potentially for the future: custom probabilities for whether a setting is enabled (or any random choices). I think it leads to more interesting scenarios, and our experience with the mixed-version backup test supports that.
</blockquote></details>

Sure -- added plumbing for passing rng from mix version.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXFmrS8MtC9EEjV4x8:-NflY0Co608kiLMWNS36:bpkxid7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2421)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

I'm not sure it's a good idea for us to flip these cluster settings every time a changefeed is created. Two cases that come to mind where this behaviour is not ideal are: 1) a test wants finer control of when and how the settings are set (I think the mixedversion test, for example, does); and 2) if a test creates N changefeeds, it's unexpected (to me) to change these settings randomly each time.

I think these settings should live outside `Create()`. They could still be packaged into a function to make their consumption easier.
</blockquote></details>

Sure; good point.  Made changes to make sure the settings applied once per the lifetime of the creator.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXHiI74G8_dcMXkk_h:-NflY4qx7iK0kRTR_v3E:b390chv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2425)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

The mixedversion test also uses this changefeed creator, and the function is called when the cluster is still running older versions. This will cause the test to fail deterministically on every run of the mixed-version test.

(Another reason to remove these cluster settings from `Create()` IMO).
</blockquote></details>

didn't remove from create -- but made it happen once per lifetime of the cdc creator.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWevtN9IR0VPo0m97_:-NflYAo61LrpNha2mT7H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2427)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Oops. Youre right
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXJiolEvWZEnSAoAkP:-NflYF2CEB6ZI7aJcYQv:bv2t25t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L437)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This is not accurate -- by default, mixedversion tests may perform up to 3 upgrades in a test run -- this means that for master, clusters may be bootstrapped at 22.1. This is configurable though: if you wanted, there's an option to specify how many upgrades you want to run. That said, it's probably better to just gate this cluster setting with `version.MustParse("v" + h.Context().FromVersion).AtLeast(v222)`
</blockquote></details>

okay -- looks like I got confused by minversion variable.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXKrpR703KlCwofQFM:-NflaIXT6raHFMUq71sZ:b-f3hta7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L446)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

In its current implementation, `LowestBinaryVersion` doesn't work when called during `AfterUpgradeFinalized`, as it's done here (this should be better documented, apologies). It will fail to parse a meaningful version when every node is upgraded to current cockroach since that doesn't have a "released" version.

Two options:

1. Explicitly check for this condition:

```go
// the version we upgraded to is the current, and the set of upgraded nodes is "every node"
allNodesUpgradedToCurrent := h.Context().ToVersion == clusterupgrade.MainVersion && len(h.Context().ToVersionNodes) == len(tester.crdbNodes)
if allNodesUpgradedToCurrent || h.LowestBinaryVersion().AtLeast(v232) {
   // ...
}
```

2. Check the cluster version directly:

```go
_, db := h.RandomDB()
cv, err := clusterupgrade.ClusterVersion(ctx, db)
if cvIsAtLeast(cv, "23.1") {
    // ...
}
```
</blockquote></details>

Okay. Done.
___
*[`pkg/cmd/roachtest/tests/version.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfWkWyFA-OgKO2JZeSg:-Nflaiw086NZQAZ8Rr-w:bwh2y8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/version.go#L39)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Yes, this variable is related to the backup test specifically. It's the minimum version before which that test won't attempt any backups or restores. The mixedversion framework itself doesn't have an official "minimum version" requirement since the few SQL statements it performs have been around for a long time (i.e., setting cluster version, preserve_downgrade_option, etc).

I suggest moving this back to `mixed_version_backup.go`. Feel free to include `backup` in the name somewhere if you feel that makes the intention clearer.
</blockquote></details>

Okay -- yeah, this was confusing.  Going to move back to backup, and rename.


<!-- Sent from Reviewable.io -->

2023-10-02 20:20 UTC, renatolabs commented
@miretskiy did you mean to push changes to this branch?

2023-10-02 21:19 UTC, miretskiy commented
Yes, sorry -- still working on this/testing.  Got side tracked.

On Mon, Oct 2, 2023 at 4:20 PM Renato Costa ***@***.***>
wrote:

> @miretskiy <https://github.com/miretskiy> did you mean to push changes to
> this branch?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/111498#issuecomment-1743700354>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVDHBVJ3MEYHFLGN6W3X5MOZTAVCNFSM6AAAAAA5MPOYK6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONBTG4YDAMZVGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-02 21:21 UTC, renatolabs commented
Got it -- no problem; was just confused because the comments seemed to suggest a change was pushed. 👍

2023-10-03 15:11 UTC, miretskiy reviewed
@renatolabs ready for another look, I think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-:-Nfq44t_0WYY7kFduWUi:b-tuf4jv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @renatolabs, and @smg260)



<!-- Sent from Reviewable.io -->

2023-10-04 21:28 UTC, renatolabs requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXFmrS8MtC9EEjV4x8:-NfwHcdi0mGzrN_HImiB:b-29koi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2421)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Sure; good point.  Made changes to make sure the settings applied once per the lifetime of the creator.
</blockquote></details>

Not going to block the PR, but I'm still not a huge fan of automatically setting these settings on `Create().` IMO, it should be easy for a test to create both a randomized settings changefeed and a "default" (no cluster settings changed) changefeed. Currently only the former is easy.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXHiI74G8_dcMXkk_h:-NfwI_gd33HY_iHrMOvM:b-f705yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2425)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

didn't remove from create -- but made it happen once per lifetime of the cdc creator.
</blockquote></details>

Won't it still fail? We are still trying to set a setting that doesn't exist at the time the changefeed is created (since the cluster will be running an older version).

Edit: confirmed the test does fail for this reason.
___
*[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 427 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfwJi1_5P6a1cIMXgwW:-NfwJi1_5P6a1cIMXgwX:brxf4oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/340cbe5022bf9c7bb0d05393ab70e22c32fa7bb9/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L427)):*
> ```Go
> 
> func (cmvt *cdcMixedVersionTester) muxRangeFeedSupported(h *mixedversion.Helper) bool {
> 	return version.MustParse("v" + h.Context().FromVersion).AtLeast(v222)
> ```

I believe when I suggested this check, we were talking exclusively about `OnStartup`. This won't work `InMixedVersion` reliably. Consider the following scenario:

* mixedversion starts the upgrade test from a cluster running 22.1
* we restart nodes to 22.2, setting `preserve_downgrade_option` to 22.1 (`FromVersion: 22.1.X`, `ToVersion: 22.2.X`)
* we then rollback the upgrade, restarting all nodes back to their 22.1.X version (`FromVersion: 22.2.X`, `ToVersion: 22.1.X`)
    * `muxRangeFeedSupported` is called during this rollback stage: `FromVersion.AtLeast(v222)` is true. However, if our `h.Exec` call picks one of the nodes running 22.1.X, the call will fail.

`LowestBinaryVersion()` will almost work here, but not quite (since it wasn't built with `AfterUpgradeFinalized` in mind. I'll put a PR up tomorrow (have something on a local branch) that I think will simplify this logic.


<!-- Sent from Reviewable.io -->

2023-10-05 14:20 UTC, miretskiy commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @smg260)
> 
> _[`pkg/cmd/roachtest/tests/cdc.go` line 2421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXFmrS8MtC9EEjV4x8:-NfwHcdi0mGzrN_HImiB:b-29koi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2421)):_
> 
> Previously, miretskiy (Yevgeniy Miretskiy) wrote…
> Not going to block the PR, but I'm still not a huge fan of automatically setting these settings on `Create().` IMO, it should be easy for a test to create both a randomized settings changefeed and a "default" (no cluster settings changed) changefeed. Currently only the former is easy.
> 
> _[`pkg/cmd/roachtest/tests/cdc.go` line 2425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXHiI74G8_dcMXkk_h:-NfwI_gd33HY_iHrMOvM:b-f705yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2425)):_
> 
> Previously, miretskiy (Yevgeniy Miretskiy) wrote…
> > didn't remove from create -- but made it happen once per lifetime of the cdc creator.
> 
> Won't it still fail? We are still trying to set a setting that doesn't exist at the time the changefeed is created (since the cluster will be running an older version).
> 
> Edit: confirmed the test does fail for this reason.
> 
> _[`pkg/cmd/roachtest/tests/mixed_version_cdc.go` line 427 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfwJi1_5P6a1cIMXgwW:-NfwJi1_5P6a1cIMXgwX:brxf4oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/340cbe5022bf9c7bb0d05393ab70e22c32fa7bb9/pkg/cmd/roachtest/tests/mixed_version_cdc.go#L427)):_
> 
> > ```go
> > func (cmvt *cdcMixedVersionTester) muxRangeFeedSupported(h *mixedversion.Helper) bool {
> > 	return version.MustParse("v" + h.Context().FromVersion).AtLeast(v222)
> > ```
> 
> I believe when I suggested this check, we were talking exclusively about `OnStartup`. This won't work `InMixedVersion` reliably. Consider the following scenario:
> 
> * mixedversion starts the upgrade test from a cluster running 22.1
> * we restart nodes to 22.2, setting `preserve_downgrade_option` to 22.1 (`FromVersion: 22.1.X`, `ToVersion: 22.2.X`)
> * we then rollback the upgrade, restarting all nodes back to their 22.1.X version (`FromVersion: 22.2.X`, `ToVersion: 22.1.X`)
>   
>   * `muxRangeFeedSupported` is called during this rollback stage: `FromVersion.AtLeast(v222)` is true. However, if our `h.Exec` call picks one of the nodes running 22.1.X, the call will fail.
> 
> `LowestBinaryVersion()` will almost work here, but not quite (since it wasn't built with `AfterUpgradeFinalized` in mind. I'll put a PR up tomorrow (have something on a local branch) that I think will simplify this logic.

This whole thing is highly confusing.  Need a way to determine if it is safe to apply particular cluster setting or not.
I'm almost inclined to just ignore the errors when updating the settings.

2023-10-05 17:57 UTC, renatolabs commented
>  Need a way to determine if it is safe to apply particular cluster setting or not.

Once #111858 is merged, you should be able to update both of your `*Supported` functions to replace the logic with a call to `h.LowestBinaryVersion().AtLeast(versionClusterSettingIntroduced)`.

> This whole thing is highly confusing

I sympathize with the feeling. In my opinion, mixed-version states are inherently complex so, while we can and do, to the best of our current ability, provide helpers with abstractions and higher level APIs, tests still need to do spend some time thinking about under what conditions something should or should not work.

> I'm almost inclined to just ignore the errors when updating the settings.

Let's try a bit more to not do that, I think it's pretty avoidable in this case.

*****

Note that the current failure in this branch happens not because of mixed-version states, but because `changefeedCreator` is _always_ trying to flip both settings non-conditionally. This won't work with the current mixed-version test because the changefeed is created when the cluster starts, and at that point, the cluster could be running an arbitrary (up to 3 major releases old) binary.

2023-10-12 13:52 UTC, renatolabs commented
@miretskiy please rebase this branch to get updates from #111912. Once that's done, you should be able to use `h.ClusterVersionAtLeast` to find out when a cluster setting is available, and I believe that will simplify the logic in this test.

As usual, please feel free to reach out if you see any problems.

2023-11-23 14:35 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @smg260)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-NfXFmrS8MtC9EEjV4x8:-NjwaBZZ5Wq0fzXDV35d:b-d9aal2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e664ed8cffcf2ed12e791be00aba94c34e309c5f/pkg/cmd/roachtest/tests/cdc.go#L2421)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not going to block the PR, but I'm still not a huge fan of automatically setting these settings on `Create().` IMO, it should be easy for a test to create both a randomized settings changefeed and a "default" (no cluster settings changed) changefeed. Currently only the former is easy.
</blockquote></details>

Coming back to this point -- What I previously suggested as a nice to have (leaving cluster settings alone when creating the changefeed) might actually be a correctness issue now.

We are always setting the cluster setting to _some_ value when creating the changefeed. But if the test starts at a version that does not recognize it, setting it to `featureDisabled` (as the mixed-version test is doing) is going to fail. Maybe we need 3-valued logic (enabled, disabled, unset).


<!-- Sent from Reviewable.io -->

2023-11-23 14:35 UTC, renatolabs commented
Other than the comment above, code LGTM!

2023-11-27 22:26 UTC, miretskiy commented
good point, @renatolabs ... Added unset option.

2023-11-28 20:22 UTC, renatolabs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111498#-:-NkMaA5UCnMrcWZENKlG:by6fmpn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava, @miretskiy, and @smg260)



<!-- Sent from Reviewable.io -->

2023-11-29 14:02 UTC, miretskiy commented
bors r+

2023-11-29 14:07 UTC, renatolabs commented
BTW: we probably want to backport this to at least 23.2, and maybe 23.1 as well?

2023-11-29 14:40 UTC, merged