sql: separate "internal key" and "display name" for system privileges
cockroachdb/cockroach pull request #111653
Opened 2023-10-03 15:17 UTC by knz

In a way akin to 56e07c1a8df66946df7fa15f5b9d3cf4089eeab6, this change introduces a distinction between the *name* of a system privilege, which is the one facing end-users; and the *internal key* of the privilege, which is stored in `system.privileges`.

This distinction exists to allow us to rename the user-facing privileges towards better UX and clearer docs without having to rewrite the contents of `system.privileges`.

The internal key is meant to remain immutable after a privilege is added in the source code. For privileges that will be added in the future, we can now even envision storing numbers or UUIDs instead in `system.privileges`.

For backward-compatibility, the internal key for a system privilege is also recognized as input in SQL syntax.

(An argument could be made that we would be better served by `system.privilege` containing an array of integers with the internal IDs, but this change aims to avoid _any_ migration whatsoever, and currently the system table already contains strings.)

Informs #110927.
Epic: CRDB-29380

2023-10-03 16:52 UTC, ecwall commented on pkg/sql/privilege/kind.go
> +	case DEPRECATEDGRANT:
Is this the only one that is different? I think it can be removed entirely now that it was migrated a few versions ago.

2023-10-04 19:41 UTC, rafiss requested changes
this direction seems ok to go in, thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NfwCKOl90zyj2G1wYaj:b-emx7m4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @knz)

___
*[`pkg/sql/crdb_internal.go` line 8580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwAp28A1fsrLppNBFm:-NfwAp28A1fsrLppNBFn:bmb235a) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/crdb_internal.go#L8580)):*
> ```Go
> CREATE VIEW crdb_internal.kv_system_privileges AS
> SELECT username, path,
>        crdb_internal.privilege_name(privileges),
> ```

nit: use `AS` to give these well-defined column names
___
*[`pkg/sql/privilege/kind.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwBGSKEZNwUTTRq4s6:-NfwBGSKEZNwUTTRq4s7:bz79ln6) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/kind.go#L74)):*
> ```Go
> // KindKey is the value stored in system tables, etc, that represent
> // the privilege internally. It is not visible to end-users.
> type KindInternalKey string
> ```

why did we get rid of the stringer here? it seems that `func (Kind) String()` is no longer defined, but it was still used above. also, it seems less error-prone since with this change it's easy for someone to forget to update this switch statement
___
*[`pkg/sql/privilege/privilege.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwC3qN8ngG1POllW3S:-NfwC3qN8ngG1POllW3T:b-6gtefr) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/privilege.go#L303)):*
> ```Go
> 		case OriginFromUserInput:
> 			var ok bool
> 			k, ok = ByDisplayName[KindDisplayName(strings.ToUpper(s))]
> ```

don't we need to also keep allowing the user to specify the internal key?


<!-- Sent from Reviewable.io -->

2023-10-09 02:24 UTC, yuzefovich reviewed
I'm picking up this from Raphael to push it over the finish line.

> Reviewed 26 of 26 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NgHEkZC9GGCFSPLVew1:b-3i8dbd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 8580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwAp28A1fsrLppNBFm:-NgH4Riq2wEqTFxLskjr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/crdb_internal.go#L8580)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: use `AS` to give these well-defined column names
</blockquote></details>

Done.
___
*[`pkg/sql/privilege/kind.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwBGSKEZNwUTTRq4s6:-NgH6D4uBhdUJAaV5Ikm:bqpo6n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/kind.go#L74)):*
My guess is that the rationale is something like this: the removal of automatically generated `String()` implementation allows us to provide custom `DisplayName()` to make user-visible changes as we please. The fact that `String()` is no longer implemented pushes engineers to choose either `InternalKey` or `DisplayName`.

However, it does make it so that our "lintonbuild" config fails to compile because in many (?) places we use `privilege.Kind` with `%s` format directive which is no longer valid. @knz can you share your perspective on this before I start updating all those places? (I'm assuming in vast majority we'll be using `DisplayName`, right?

> it seems less error-prone since with this change it's easy for someone to forget to update this switch statement

I don't think it's a concern because in `init()` below we iterate over all kinds, and for all non-deprecated ones we call `InternalKey`; thus, if someone forgets to add another case to the switch, the build will be red.
___
*[`pkg/sql/privilege/kind.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#gh-1344433096:-NgH7EEo5Ei6yKLxaWz6:b-2l3tyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/kind.go#L84)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

Is this the only one that is different? I think it can be removed entirely now that it was migrated a few versions ago.
</blockquote></details>

Ack, I removed it.
___
*[`pkg/sql/privilege/privilege.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwC3qN8ngG1POllW3S:-NgH9DQd2l53qS1Uj4eK:b-3suk9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/privilege.go#L303)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

don't we need to also keep allowing the user to specify the internal key?
</blockquote></details>

Yes, I believe we need to, done.


<!-- Sent from Reviewable.io -->

2023-10-09 18:13 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/privilege/kind.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwBGSKEZNwUTTRq4s6:-NgKcuqCBsqNdid9kqJI:b-a0j1g6) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/kind.go#L74)):*
> The fact that `String()` is no longer implemented pushes engineers to choose either `InternalKey` or `DisplayName`.

correct.

> I'm assuming in vast majority we'll be using `DisplayName`, right?

correct, but we'd need to be careful for those cases that generate SQL syntax.
___
*[`pkg/sql/privilege/privilege.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwC3qN8ngG1POllW3S:-NgKd4KVBGS9I51_Ckh3:b-r2rplw) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/privilege.go#L303)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes, I believe we need to, done.
</blockquote></details>

Can you double check? I intended the `ByDisplayName` map to be already initialized (via `init`  function) to contain both names and internal keys.


<!-- Sent from Reviewable.io -->

2023-10-09 20:42 UTC, yuzefovich reviewed
I think the CI should be green, so this is RFAL, @ecwall @rafiss 

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NgLAHoG0VvH6B0ClzgV:b-kkxbh1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/privilege/kind.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwBGSKEZNwUTTRq4s6:-NgL8gmACyaro6R1Bfly:bbzmj9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/kind.go#L74)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

> The fact that `String()` is no longer implemented pushes engineers to choose either `InternalKey` or `DisplayName`.

correct.

> I'm assuming in vast majority we'll be using `DisplayName`, right?

correct, but we'd need to be careful for those cases that generate SQL syntax.
</blockquote></details>

Turns out that there were just a handful of places like this, and in all of them I think `DisplayName()` is the right choice.
___
*[`pkg/sql/privilege/privilege.go` line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NfwC3qN8ngG1POllW3S:-NgKzfG0Et_ccP6brOfa:byh57j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/987df64773c03ca08b0ded3423b059d47475b05b/pkg/sql/privilege/privilege.go#L303)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you double check? I intended the `ByDisplayName` map to be already initialized (via `init`  function) to contain both names and internal keys.
</blockquote></details>

Oh, right, I missed that, reverted my change.
___
*[`pkg/sql/privilege/privilege.go` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgL8rlA86pb-44AMHro:-NgL8rlA86pb-44AMHrp:biv0ahe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7104a70cd5c5a1980629b90b8f0a876b6e2ee25/pkg/sql/privilege/privilege.go#L136)):*
> ```Go
> 	for i, p := range pl {
> 		if i > 0 {
> 			s.SafeString(", ")
> ```

Want to bring attention to this change - previously we had `privilege.List.String()` which joined strings with `", "` separator, we removed that implementation, so in some logic tests we started seeing a different error message where multiple privileges were joined just by a comma. Adding a space here should fix those tests, but it also seems like a nice change on its own. Thoughts?


<!-- Sent from Reviewable.io -->

2023-10-09 21:28 UTC, yuzefovich reviewed
> Reviewed 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/grant_database` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLKeZj58iQvA85ErDC:-NgLKeZj58iQvA85ErDD:b-2rzj4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf9a4fedb461aa32150deb026e371bae94748d/pkg/sql/logictest/testdata/logic_test/grant_database#L12)):*
> ```
> a              root     ALL             true
> 
> statement error user root must have exactly \[ALL\] privileges on database "a"
> ```

Here is another minor difference - we now use `privilege.List.SortedDisplayNames` in a few places which returns `[]string`, and when that gets stringified, we see square brackets around the names. Seems reasonable.


<!-- Sent from Reviewable.io -->

2023-10-09 23:03 UTC, yuzefovich reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @knz, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 8609 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLdmSU1Sz6e9lXG_HC:-NgLdmSU1Sz6e9lXG_HD:bs08i93) ([raw file](https://github.com/cockroachdb/cockroach/blob/0674b5bd41975442e7421cfaab35d8323daac35c/pkg/sql/crdb_internal.go#L8609)):*
> ```Go
>        crdb_internal.privilege_name(privileges) AS privileges,
>        crdb_internal.privilege_name(grant_options) AS grant_options,
>        user_id
> ```

Hm, there is a difficulty here: `user_id` column was added to `system.privileges` during 23.1 cycle, so in mixed 22.2-23.1+ cluster this view might result in an error if it happens to be queried on the older node. I'm not quite sure what to do here since I don't think that we have infrastructure to gate the schema of this virtual view based on the cluster version.

Do we actually need to care about this 22.2-23.1+ cluster state? I don't think we're implementing version skipping from 22.2 to 23.2, so it seems that we actually don't care about this. This would mean that we add a skip for `local-mixed-22_2-23_1` logic test config to a couple of files.

The view is currently only used to power `SHOW GRANTS` which doesn't actually use `user_id` column, so in theory we could adjust the schema to omit this column.  This view was added recently in #104565 and was backported to 22.2 and 23.1.

@ecwall thoughts on this?


<!-- Sent from Reviewable.io -->

2023-10-10 01:23 UTC, yuzefovich reviewed
Apologies for all the pushes, this is RFAL, @ecwall @rafiss.

> Reviewed 2 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NgMA7-v0nUv9_by_Rdx:ber54dq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @ericharmeling, @knz, @msbutler, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 8609 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLdmSU1Sz6e9lXG_HC:-NgMAC4HDTH_MYDRb0lJ:b3vb957) ([raw file](https://github.com/cockroachdb/cockroach/blob/0674b5bd41975442e7421cfaab35d8323daac35c/pkg/sql/crdb_internal.go#L8609)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, there is a difficulty here: `user_id` column was added to `system.privileges` during 23.1 cycle, so in mixed 22.2-23.1+ cluster this view might result in an error if it happens to be queried on the older node. I'm not quite sure what to do here since I don't think that we have infrastructure to gate the schema of this virtual view based on the cluster version.

Do we actually need to care about this 22.2-23.1+ cluster state? I don't think we're implementing version skipping from 22.2 to 23.2, so it seems that we actually don't care about this. This would mean that we add a skip for `local-mixed-22_2-23_1` logic test config to a couple of files.

The view is currently only used to power `SHOW GRANTS` which doesn't actually use `user_id` column, so in theory we could adjust the schema to omit this column.  This view was added recently in #104565 and was backported to 22.2 and 23.1.

@ecwall thoughts on this?
</blockquote></details>

I added a skip for `local-mixed-22_2-23_1` in two places. This means that `SHOW SYSTEM GRANTS` might not work in mixed version 22.2-23.2 cluster when issued against the older node (apparently, we'll have experimental support for this). The alternative is to change the schema to remove `user_id` column, but this would make the virtual table schema differ from the system table, so I chose the skip option.


<!-- Sent from Reviewable.io -->

2023-10-10 08:17 UTC, knz commented
> Do we actually need to care about this 22.2-23.1+ cluster state? I don't think we're implementing version skipping from 22.2 to 23.2

Indeed, we have chosen not to implement version skipping from 22.2 to 23.2 so I think we are safe.

2023-10-16 16:11 UTC, yuzefovich commented
Friendly ping @rafiss @ecwall

2023-10-20 15:20 UTC, rafiss approved these changes
thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NhCezAn81VMogv7pDEh:bsv417h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @ericharmeling, @knz, @msbutler, and @yuzefovich)

___
*[`pkg/sql/crdb_internal.go` line 8609 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLdmSU1Sz6e9lXG_HC:-NhCe3bACtmlu8_hgT0J:bg47kx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0674b5bd41975442e7421cfaab35d8323daac35c/pkg/sql/crdb_internal.go#L8609)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I added a skip for `local-mixed-22_2-23_1` in two places. This means that `SHOW SYSTEM GRANTS` might not work in mixed version 22.2-23.2 cluster when issued against the older node (apparently, we'll have experimental support for this). The alternative is to change the schema to remove `user_id` column, but this would make the virtual table schema differ from the system table, so I chose the skip option.
</blockquote></details>

we no longer need to support mixed 22.2/23.2 clusters, so i guess that's why we didn't end up needing a change here?
___
*[`pkg/sql/privilege/kind.go` line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NhCeDH8AqgXDFrHjGWu:-NhCeDH8AqgXDFrHjGWv:b-tbuwao) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b2c63942d9cb1675d376800cc84625eaff8f6b/pkg/sql/privilege/kind.go#L30)):*
> ```Go
> 	CREATE Kind = 2
> 	DROP   Kind = 3
> 	// This is a placeholder to make sure that 4 is not reused.
> ```

actually, i think it might be safe to reuse 4 at this point. i guess no need to try that unless there's a need.
___
*[`pkg/sql/privilege/privilege.go` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgL8rlA86pb-44AMHro:-NhCeeVdAaMsb6XPoFTH:bqda3f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7104a70cd5c5a1980629b90b8f0a876b6e2ee25/pkg/sql/privilege/privilege.go#L136)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Want to bring attention to this change - previously we had `privilege.List.String()` which joined strings with `", "` separator, we removed that implementation, so in some logic tests we started seeing a different error message where multiple privileges were joined just by a comma. Adding a space here should fix those tests, but it also seems like a nice change on its own. Thoughts?
</blockquote></details>

i agree, thanks
___
*[`pkg/sql/logictest/testdata/logic_test/grant_database` line 12 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLKeZj58iQvA85ErDC:-NhCer_w9goHcCJXY8sw:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/01bf9a4fedb461aa32150deb026e371bae94748d/pkg/sql/logictest/testdata/logic_test/grant_database#L12)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Here is another minor difference - we now use `privilege.List.SortedDisplayNames` in a few places which returns `[]string`, and when that gets stringified, we see square brackets around the names. Seems reasonable.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-10-21 01:08 UTC, yuzefovich reviewed
TFTR!

bors r+

> Reviewed 11 of 11 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-:-NhEl4np7UPQXdCD6nUq:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall, @ericharmeling, @msbutler, and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 8609 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NgLdmSU1Sz6e9lXG_HC:-NhDg2zb7JXOdlnwIlH_:boks8ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/0674b5bd41975442e7421cfaab35d8323daac35c/pkg/sql/crdb_internal.go#L8609)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we no longer need to support mixed 22.2/23.2 clusters, so i guess that's why we didn't end up needing a change here?
</blockquote></details>

Right, we no longer need the skip, so I removed a couple from the logic tests.
___
*[`pkg/sql/privilege/kind.go` line 30 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/111653#-NhCeDH8AqgXDFrHjGWu:-NhElRap1-5ihzCYCoal:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b2c63942d9cb1675d376800cc84625eaff8f6b/pkg/sql/privilege/kind.go#L30)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

actually, i think it might be safe to reuse 4 at this point. i guess no need to try that unless there's a need.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2023-10-21 02:20 UTC, merged