kvflowcontroller: fix logging of blocked streams
cockroachdb/cockroach pull request #112660
Opened 2023-10-18 23:42 UTC by sumeerbhola

There were two bugs that are fixed:
- The blocked_stream_count metric was incorrectly capped to 100.
- Streams were being logged with stats that were never blocked.

Some additonal improvements/fixes:
- Controller.mu was being unnecessarily acquired for read paths that don't care about concurrent additions to the map.
- WorkClass.SafeFormat was calling redact.SafePrinter.Print in some cases so "elastic" was not being treated as unsafe.

There is a unit test to test the overflow logic of the logs, and to verify that the metric is correct even when the logs overflow.

Epic: none

Release note: None

2023-10-18 23:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/112660)
<!-- Reviewable:end -->

2023-10-19 03:11 UTC, aadityasondhi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-:-Nh4uf3YBmRxBwn3sZLq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_test.go` line 449 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-Nh4stVP-maTsYroepc7:-Nh4stVP-maTsYroepc8:bscux8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd1d6483c9f2c5e19725bc2310d16bbf6946d/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_test.go#L449)):*
> ```Go
> }
> 
> func TestControllerLogging(t *testing.T) {
> ```

Thanks for adding this.


<!-- Sent from Reviewable.io -->

2023-10-23 14:16 UTC, sumeerbhola commented
@pavelkalinnikov @erikgrinaker this will need to be backported, so would be great if one of you could take a look.

2023-10-24 11:44 UTC, pavelkalinnikov reviewed
I'm going to take a close look later today (need to finish one blocker first).

In the meantime, one nit to the structure of this PR: by PR description, it seems like it makes 4 changes. It would make the review easier if the 4 changes were 4 separate commits. Also makes easier to pick the changes need to be backported.

2023-10-24 13:35 UTC, sumeerbhola reviewed
> In the meantime, one nit to the structure of this PR: by PR description, it seems like it makes 4 changes. It would make the review easier if the 4 changes were 4 separate commits. Also makes easier to pick the changes that need to be backported.

I would like to backport all.
- The bug fixes are essential.
- mutex contention is something we have noticed, so we may as well remove the unnecessary acquisitions. Note that this is not a synchronization refactoring. Its simply removal of 3 unnecessary acquisitions, given we already have a `sync.Map`.
- The s/Print/Printf is literally a single character change -- redacting these will cause us grief when troubleshooting.

Regarding separating into 4 separate commits:
- The bug fixes are in one piece of code. Separating it out would hinder rather than help.
- The two other changes are extremely tiny (mutex contention, Printf). I could move them out, and will definitely keep it in mind for future PRs, but seems like busy work given the current state of the PR. Let me know if you feel strongly about this and I will make the change.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-:-NhWs0HMCoUPAQX_9HQi:b-g1c3e5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @pavelkalinnikov)

___
*[`pkg/util/admission/admissionpb/admissionpb.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112660#gh-1365949567:-NhWrDRP0PxqMpoFJ259:b-gx873a) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd1d6483c9f2c5e19725bc2310d16bbf6946d/pkg/util/admission/admissionpb/admissionpb.go#L213)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Is this change needed/intended?
</blockquote></details>

Yes. These strings were being redacted since `Print` does not enforce that it is passed a string literal, but `Printf` does:
```
// For printf, a linter checks that the format string is  
// a constant literal, so the implementation can assume it's always  
// safe.
```

 Noticed when adding `TestControllerLogging`.


<!-- Sent from Reviewable.io -->

2023-10-24 16:16 UTC, pavelkalinnikov approved these changes

2023-10-24 16:16 UTC, pavelkalinnikov commented on pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go
> +					if shouldLogBlocked && wc == elastic {
Also, what if `shouldLogBlocked == false` for `elastic`, but not for `regular`? Will we print nothing? Shouldn't we still print the `regular` stuff?

Upd: ok, seems like we rely on the fact that `log.Every` will eventually fire, and it doesn't matter much for which work class. So the choice of `elastic` is arbitrary, and could have been `regular` too.

LGTM, but feel free to improve commenting to remove some of this confusion.

2023-10-24 16:24 UTC, pavelkalinnikov commented
> The two other changes are extremely tiny (mutex contention, Printf). I could move them out, and will definitely keep it in mind for future PRs, but seems like busy work given the current state of the PR. Let me know if you feel strongly about this and I will make the change.

Not feeling strongly in this case, but yeah, generally PRs with "and" in the description are usually candidates for a multi-commit or multi-PR structure.

2023-10-24 17:27 UTC, sumeerbhola reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-:-NhXiKsh2nlt35Tmq_FT:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112660#gh-1370442721:-NhXfSSu8jnn99DKXlCa:bapiyc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd1d6483c9f2c5e19725bc2310d16bbf6946d/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L223)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

The outer loop iterates `admissionpb.NumWorkClasses` times, and `wc` is the current iteration. `blockedStreamLogger` is local to the current iteration. Why do we need to expand it to be an array of `admissionpb.NumWorkClasses` elements? Did you intend to do it outside the outer loop? Or perhaps leave as it was before?
</blockquote></details>

Oops. This was a previous iteration of this change that I forgot to undo. Glad you noticed.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112660#gh-1370441798:-NhXfrmmBstfveP3fd0Z:b-4xcb6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd1d6483c9f2c5e19725bc2310d16bbf6946d/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L259)):*
> Took a few cycles to understand why specifically `elastic`. Is this because it's the last iteration of the outer loop?

This was arbitrary. I added a code comment.

> Also, what if `shouldLogBlocked == false` for `elastic`, but not for `regular`? Will we print nothing? Shouldn't we still print the `regular` stuff?

I added a code comment.

```
// Every 30s this predicate will evaluate to true, and we will log  
// all the streams (elastic and regular) that experienced some  
// blocking since the last time such logging was done. If a  
// high-enough log verbosity is specified, shouldLogBacked will  
// always be true, but since this method executes at the frequency  
// of scraping the metric, we will still log at a reasonable rate.
```

Arguably, this use of `log.Every` is a bit intricate, but (a) I didn't want to change too much with this backport, (b) it is questionable whether having a separate goroutine to periodically do this is any simpler.

> Upd: ok, seems like we rely on the fact that `log.Every` will eventually fire, and it doesn't matter much for which work class. So the choice of `elastic` is arbitrary, and could have been `regular` too.

Correct.
___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_test.go` line 454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112660#gh-1370424209:-NhXhirb9HJxzCo0buxX:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/065bd1d6483c9f2c5e19725bc2310d16bbf6946d/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_test.go#L454)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Get the previous value before setting it, and set it back to the original?

Not sure what the isolation between test runs is, assuming worst. If want to run all the tests in this package with vmodule logging enabled, and suddenly vmodule logging disappears, that would be a slightly unpleasant debugging session.
</blockquote></details>

Good point. Done.


<!-- Sent from Reviewable.io -->

2023-10-25 14:27 UTC, pavelkalinnikov requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112660)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-NhbAjPk16Sl2TFHGY4t:-NhbAjPk16Sl2TFHGY4u:b-g5kioh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d1821606c75306021b37754e373679a9a06b97/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L222)):*
> ```Go
> 		)
> 
> 		// blockedStreamLogger controls periodic ob blocked streams in WorkClass
> ```

Something's up with this sentence. "controls periodic logging of"?


<!-- Sent from Reviewable.io -->

2023-10-25 14:28 UTC, pav-kv approved these changes
Still LTGM. Thanks.

2023-10-25 14:33 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112660)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go` line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/112660#-NhbAjPk16Sl2TFHGY4t:-NhbEverCjSnUlloLNrn:bkvi9uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d1821606c75306021b37754e373679a9a06b97/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go#L222)):*
<details><summary><i>Previously, pavelkalinnikov (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Something's up with this sentence. "controls periodic logging of"?
</blockquote></details>

I suddenly seem unable to write a sentence correctly.
Fixed.


<!-- Sent from Reviewable.io -->

2023-10-25 20:00 UTC, sumeerbhola commented
TFTRs!

2023-10-25 20:01 UTC, sumeerbhola commented
bors r=pavelkalinnikov,aadityasondhi

2023-10-25 21:08 UTC, merged