admission: add tracing for admission work queue
cockroachdb/cockroach pull request #113168
Opened 2023-10-26 19:14 UTC by aadityasondhi

This patch adds some stats about the admission work queue to a tracing span if available as a structured event. This will allow us to know how long work items spend in the queue when debugging increased latency.

Informs #112126

Release note: None

2023-10-26 19:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/113168)
<!-- Reviewable:end -->

2023-10-26 19:29 UTC, aadityasondhi commented
I am running experiments to see this in action. Will post here shortly.

2023-10-27 13:50 UTC, sumeerbhola requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @adityamaru)

___
*[`pkg/util/admission/work_queue.go` line 806 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NhlLZMk28STEHDn8ZLB:-NhlLZMk28STEHDn8ZLC:bseb57) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1c131091f5cef5a342c59ff77f26f7a6fa3909/pkg/util/admission/work_queue.go#L806)):*
> ```Go
> 		log.Eventf(ctx, "deadline expired, waited in %s queue for %v",
> 			workKindString(q.workKind), waitDur)
> 		recordAdmissionWorkQueueStats(ctx, startTime, waitDur, q.workKind, true)
> ```


- There is a fast-path above which never waits. Should we do something like the `ConcurrentRequestLimiter` does and create a child span if that fast path is not taken https://github.com/cockroachdb/cockroach/blob/2e809427221f95c0c2a3ee9000f8d98ad5ed516e/pkg/util/limit/limiter.go#L54C1-L56. IIUC, then we will automatically have sum aggregates like the
```
  0.000ms      0.000ms    [exportRequestLimiter: {count: 8, duration 9m15s}]
```
 we get from that limiter.

- Isn't there duplication here in that we are doing both `log.Eventf` and recording the structured event? Shouldn't we only do the latter. The former also has a path for the `EventLog` and I don't quite understand when in CRDB that path would be taken even if there was no tracing span.


 
___
*[`pkg/util/admission/work_queue.go` line 829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NhlNvEs5zUuAeH6xu0V:-NhlNvEs5zUuAeH6xu0W:bmzfwt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1c131091f5cef5a342c59ff77f26f7a6fa3909/pkg/util/admission/work_queue.go#L829)):*
> ```Go
> func recordAdmissionWorkQueueStats(
> 	ctx context.Context,
> 	startTime time.Time,
> ```

is the `startTime` useful? When visually looking at the trace this seems something one can infer from the timestamp of the trace statement and the `waitDur`. But I don't quite understand what we do programmatically with these structured events, hence the question.


<!-- Sent from Reviewable.io -->

2023-11-07 17:30 UTC, aadityasondhi commented
Example of a trace with this patch:

<img width="1728" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/1a3a41d0-6a62-4355-8b60-0e933cb900c8">

2023-11-07 17:39 UTC, aadityasondhi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113168)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @sumeerbhola)

___
*[`pkg/util/admission/work_queue.go` line 806 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NhlLZMk28STEHDn8ZLB:-NierDTj8FKgLO_Cg-ig:bhzaskm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1c131091f5cef5a342c59ff77f26f7a6fa3909/pkg/util/admission/work_queue.go#L806)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

- There is a fast-path above which never waits. Should we do something like the `ConcurrentRequestLimiter` does and create a child span if that fast path is not taken https://github.com/cockroachdb/cockroach/blob/2e809427221f95c0c2a3ee9000f8d98ad5ed516e/pkg/util/limit/limiter.go#L54C1-L56. IIUC, then we will automatically have sum aggregates like the
```
  0.000ms      0.000ms    [exportRequestLimiter: {count: 8, duration 9m15s}]
```
 we get from that limiter.

- Isn't there duplication here in that we are doing both `log.Eventf` and recording the structured event? Shouldn't we only do the latter. The former also has a path for the `EventLog` and I don't quite understand when in CRDB that path would be taken even if there was no tracing span.
</blockquote></details>

Good call on both things. Done!
___
*[`pkg/util/admission/work_queue.go` line 829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NhlNvEs5zUuAeH6xu0V:-NieE7CJAnYG_rry2xdN:b-vyrwmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1c131091f5cef5a342c59ff77f26f7a6fa3909/pkg/util/admission/work_queue.go#L829)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is the `startTime` useful? When visually looking at the trace this seems something one can infer from the timestamp of the trace statement and the `waitDur`. But I don't quite understand what we do programmatically with these structured events, hence the question.
</blockquote></details>

I had not given it much thought. I saw that we return it in the error so decided maybe we should put it in this structured event as well. But you are right, we can get the start time through the trace. Especially since we are creating a child span. See screenshot below!


<!-- Sent from Reviewable.io -->

2023-11-07 20:50 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-:-NifYFgDBaualtY1u3ql:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi and @adityamaru)

___
*[`pkg/util/admission/admissionpb/admission_stats.proto` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NifXK8lE2aP_9AOYp10:-NifXK8lE2aP_9AOYp11:btxsrp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed853530c8bb2347b19c88ef75f5aab3c331ff30/pkg/util/admission/admissionpb/admission_stats.proto#L25)):*
> ```proto
>   string work_kind = 2;
>   // Set to true if deadline was exceeded.
>   bool deadline_expired = 3;
> ```

s/deadline_expired/deadline_exceeded/

that makes it consistent with the code comments and the parameter name in `recordAdmissionWorkQueueStats`. Also, "deadline exceeded" is the more common term relative to "deadline expired" (e.g. `context.DeadlineExceeded` error).


<!-- Sent from Reviewable.io -->

2023-11-08 15:55 UTC, aadityasondhi reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-:-NijdMEy221P2BFaPj_A:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @sumeerbhola)

___
*[`pkg/util/admission/admissionpb/admission_stats.proto` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113168#-NifXK8lE2aP_9AOYp10:-NijdLsj9dxCsmVp8a8v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed853530c8bb2347b19c88ef75f5aab3c331ff30/pkg/util/admission/admissionpb/admission_stats.proto#L25)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/deadline_expired/deadline_exceeded/

that makes it consistent with the code comments and the parameter name in `recordAdmissionWorkQueueStats`. Also, "deadline exceeded" is the more common term relative to "deadline expired" (e.g. `context.DeadlineExceeded` error).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-08 15:56 UTC, aadityasondhi commented
bors r=sumeerbhola

2023-11-08 16:58 UTC, merged