sql: do not allow aggregate functions in recursive ctes
cockroachdb/cockroach pull request #113631
Opened 2023-11-01 20:44 UTC by rharding6373

Postgres disallows aggregate functions in recursive CTEs since they can never terminate. This PR makes CRDB return the same invalid recursion error.

Epic: None
Fixes: #113625

Release note (bug fix): Returns an invalid recursion error if a query attempts to use an aggregate function in a recursive CTE instead of allowing the query to build and execute, which could lead to unexpected results.

2023-11-01 20:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/113631)
<!-- Reviewable:end -->

2023-11-01 20:46 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113631#-NiBcbU12nZu2zewL_Vd):*
What about window functions? Set-returning functions?


<!-- Sent from Reviewable.io -->

2023-11-01 20:57 UTC, rharding6373 commented
Postgres doesn't error for window function, though it doesn't really make sense, e.g., `WITH RECURSIVE x(n) AS (SELECT 1::bigint UNION ALL SELECT count(*) over () FROM x) SELECT * FROM x;` will also not terminate, but doesn't error in postgres. Set-returning functions are fine.

2023-11-02 02:39 UTC, rharding6373 commented
Hm, the asyncpg query succeeds on postgres, despite the use of `array_agg`. Also interesting that it didn't fail after the first push. It'll need a closer look.

2023-11-04 00:41 UTC, michae2 requested changes
> Reviewed 4 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/logictest/testdata/logic_test/with` line 1325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/113631#-NiMZMIL7w9ndRBlwF0C:-NiMZMIL7w9ndRBlwF0D:b5tjxne) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4ca46156aa1e861a5f42b3aeed4c227b134ea5/pkg/sql/logictest/testdata/logic_test/with#L1325)):*
> ```
> # Regression test for #113625
> statement error pgcode 42P19 pq: aggregate functions are not allowed in a recursive query's recursive term
> WITH RECURSIVE x(n) AS (SELECT 1 UNION ALL SELECT count(*) FROM x) SELECT * FROM x;
> ```

Could you add another testcase with the aggregation inside the non-recursive term? (I think Postgres allows that.)


<!-- Sent from Reviewable.io -->

2026-07-24 16:04 UTC, closed without merging