server: ensure TestStatusLocalLogs flushes logs
cockroachdb/cockroach pull request #113734
Opened 2023-11-03 07:50 UTC by dhartunian

Previously, this test would not flush logs to disk before attempting to read, resulting in errors.

The test is otherwise resilient to additional logs making it into the response mixed with the specific ones we emit here.

Also contains a minor fix for a conditional that was using the wrong variable. This does not affect test outcomes.

Resolves: #112375

Epic: None

Release note: None

2023-11-03 07:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/113734)
<!-- Reviewable:end -->

2023-11-06 15:45 UTC, abarganier approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113734#-:-Ni_IrOaCW5YXucb8Jg4:b-hidk3u)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-11-06 15:46 UTC, abarganier requested changes
Hmm, or wait... It's still failing on CI? :thinking: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113734#-:-Ni_J-yj7rFTI0clfKFD:b-haqsfc)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-11-20 21:20 UTC, dhartunian commented
closing in favor of https://github.com/cockroachdb/cockroach/pull/114563

2023-11-20 21:20 UTC, closed without merging