roachtest: move schemachange/mixed-version to new framework
cockroachdb/cockroach pull request #113890
Opened 2023-11-06 19:24 UTC by annrpom

This patch updates the `schemachange/mixed-versions` roachtest to use the new mixed version testing framework - which in turn provides testing enhancements.

Fixes: #110533
Epic: None

Release note: None

2023-11-06 19:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/113890)
<!-- Reviewable:end -->

2023-11-09 22:52 UTC, DarrylWong requested changes
I'll let rafi or renato comment on correctness since my understanding of schemachange is limited here. I left a few comments though. Looks good :thumbsup: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NiqGf239sbzUL5ZOEBA:b-f12g6o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqDfyd51Mml-QYMwM_:-NiqDfyd51Mml-QYMwMa:buksnpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L58)):*
> ```Go
> }
> 
> func newSchemaChangeMixedVersionTester(
> ```

In my opinion I don't think this test is complicated enough to need a tester struct/function. Unless there's future plans to add more tests with different parameters you could get away with removing it and moving `uploadAndInitSchemaChangeWorkload` and  `runSchemaChangeWorkloadStepAndValidate` into `runSchemaChangeMixedVersions`.

But i'm not married to the idea if someone else feels strongly about it :shrug: 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqEm_J9YzfGwnL0Kac:-NiqEm_J9YzfGwnL0Kad:by93myg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L76)):*
> ```Go
> 	ctx context.Context, l *logger.Logger, rand *rand.Rand, h *mixedversion.Helper,
> ) error {
> 	if err := scmvt.c.PutE(ctx, l, scmvt.t.DeprecatedWorkload(), "./workload", scmvt.c.All()); err != nil {
> ```

I think the other tests upload the workload outside of the mixed version testing framework? I don't think it would be wrong to do it in a startup hook but maybe we should keep it consistent.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niq0ycEEV8rc-KtGqV6:-Niq0ycF2wCrn9xtmAbX:b6m9qvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L79)):*
> ```Go
> 		return err
> 	}
> 	if err := scmvt.c.PutE(ctx, l, scmvt.t.Cockroach(), "./cockroach-doctor", scmvt.c.All()); err != nil {
> ```

I wonder if we if need to upload a new cockroach binary here or if you could just use `test.DefaultCockroachPath`? My memory is a little fuzzy but I think the non current releases shouldn't overwrite the default binary path that is uploaded at the start of every test. 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqAYc4EPhUi2BNUH5a:-NiqAYc4EPhUi2BNUH5b:b-baolv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L92)):*
> ```Go
> 	scmvt.numFeatureRuns += 1
> 	l.Printf("Workload step run: %d", scmvt.numFeatureRuns)
> 	runCmd := []string{
> ```

Not a blocker or necessary but it would be nice if we started using `roachtestutil.NewCommand`  for stuff like this. Just makes it nicer to read IMO.



_Code snippet:_
```Go
runCmd := roachtestutil.NewCommand("./workload run schemachange").
	Flag("verbose", 1).
	Flag("max-ops", scmvt.maxOps).
	Flag("concurrency", scmvt.concurrency).
	Arg("{pgurl:1-%d}", scmvt.c.Spec().NodeCount).
	String()
```
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqBNmx3JknuCv40tnW:-NiqBNmx3JknuCv40tnX:b3zqe40) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L109)):*
> ```Go
> 	}
> 	// Now we validate that nothing is broken after the random schema changes have been run.
> 	runCmd = []string{
> ```

Same as above wrt using roachtestutil.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niq927Q4IhXcwNDjG4d:-Niq927Q4IhXcwNDjG4e:b-diapn) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L128)):*
> ```Go
> ) {
> 	scmvt := newSchemaChangeMixedVersionTester(c, t, maxOps, concurrency, 0 /* numFeatureRuns */)
> 	mvt := mixedversion.NewTest(ctx, t, t.L(), c, c.All(), mixedversion.AlwaysUseLatestPredecessors, mixedversion.AlwaysUseFixtures)
> ```

Do we need to always use fixtures here? I see that's how it was before but unless it's a correctness issue it'd be better to leave it out. (I have no idea if it is).
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqHB9E5Yt5JOGzYw9D:-NiqHB9E5Yt5JOGzYw9E:b8p7n4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L131)):*
> ```Go
> 
> 	schemaChangeAndValidationStep := scmvt.runSchemaChangeWorkloadStepAndValidate
> 	if buildVersion.Major() < 20 {
> ```

I don't think the new framework will ever run on a version this old.


<!-- Sent from Reviewable.io -->

2023-11-10 20:15 UTC, annrpom reviewed
thanks for your review & for your patience with me/my questions heh

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NiursJD8--pu83-Y1cR:bqdhbnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqDfyd51Mml-QYMwM_:-NiqovCY8xRM_6d3XniC:b-cgg4vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L58)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

In my opinion I don't think this test is complicated enough to need a tester struct/function. Unless there's future plans to add more tests with different parameters you could get away with removing it and moving `uploadAndInitSchemaChangeWorkload` and  `runSchemaChangeWorkloadStepAndValidate` into `runSchemaChangeWorkloadStepAndValidate`.

But i'm not married to the idea if someone else feels strongly about it :shrug:
</blockquote></details>

true - we spoke offline about this, but for the sake of tracking: i did this for my own readability :100:, but i kind of realize that yes it is a bit unnecessary~ i just went ahead and changed it
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqEm_J9YzfGwnL0Kac:-Niu9TeW5dV7t0zuIuFu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L76)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

I think the other tests upload the workload outside of the mixed version testing framework? I don't think it would be wrong to do it in a startup hook but maybe we should keep it consistent.
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niq0ycEEV8rc-KtGqV6:-Niu9W1p1wiUEOxhFKFl:b1zt3ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L79)):*
> I wonder if we if need to upload a new cockroach binary here or if you could just use `test.DefaultCockroachPath`

right, it seems to me like we can just use test.DefaultCockroachPath here
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqAYc4EPhUi2BNUH5a:-NiuOi01EQ80GMKJ7fp5:b-7rl0jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L92)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Not a blocker or necessary but it would be nice if we started using `roachtestutil.NewCommand`  for stuff like this. Just makes it nicer to read IMO.
</blockquote></details>

done 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqBNmx3JknuCv40tnW:-NiuSqgAEymGf6KWNaJo:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L109)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Same as above wrt using roachtestutil.
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niq927Q4IhXcwNDjG4d:-Niukb9j9ibLcjR8DMWS:b-7b5t5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L128)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

Do we need to always use fixtures here? I see that's how it was before but unless it's a correctness issue it'd be better to leave it out. (I have no idea if it is).
</blockquote></details>

i am under the impression that the random schemachange workload should be able to perform schema changes on some data that exists previously (but not necessarily need such data), but i am also under the impression that what we want would be a correctness check (which doesn't seem to align with needing to always use fixtures)

anyone feel free to correct me if i am wrong!
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NiqHB9E5Yt5JOGzYw9D:-NiuStbGBd8hWNlSeprW:b-a3cu9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L131)):*
<details><summary><i>Previously, DarrylWong wrote…</i></summary><blockquote>

I don't think the new framework will ever run on a version this old.
</blockquote></details>

ah good point :100: 


<!-- Sent from Reviewable.io -->

2023-11-10 22:28 UTC, renatolabs reviewed
Just a few questions and small modifications to the test. Thanks for working on this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NivLRkqD8C4yNCrwZjw:b76jie3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @rafiss)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niq0ycEEV8rc-KtGqV6:-NivFc5v3B2zcnY6w8xs:b-9kpd0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb244c2456076a3b1af0331fb92f8b707abdefef/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L79)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

> I wonder if we if need to upload a new cockroach binary here or if you could just use `test.DefaultCockroachPath`

right, it seems to me like we can just use test.DefaultCockroachPath here
</blockquote></details>

Confirming this is safe, previous release binaries are namespaced in their own directories.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niv9_CK5yXUvSuI6Sz8:-Niv9_CK5yXUvSuI6Sz9:b-t9zdus) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L33)):*
> ```Go
> 		// This tests the work done for 20.1 that made schema changes jobs and in
> 		// addition prevented making any new schema changes on a mixed cluster in
> 		// order to prevent bugs during upgrades.
> ```

This comment seems outdated now?
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niv9cj49ClL7hV5q_v8:-Niv9cj49ClL7hV5q_v9:bk0zj3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L40)):*
> ```Go
> 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 			maxOps := 100
> 			concurrency := 5
> ```

For consideration and my own understanding: why do we choose these values? 100 ops seems like very little, could we change this to at least 1000?
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NivARIl5ELprat7OXxd:b-d6vwew) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> ```Go
> ) {
> 	numFeatureRuns := 0
> 	mvt := mixedversion.NewTest(ctx, t, t.L(), c, c.All(), mixedversion.AlwaysUseLatestPredecessors)
> ```

Just curious: do we "rediscover" bugs if we run it without `AlwaysUseLatestPredecessors`? If so, which ones?
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivAj5A4R7uoqO6MZJ4:-NivAj5A4R7uoqO6MZJ5:b-u148wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L57)):*
> ```Go
> 	mvt := mixedversion.NewTest(ctx, t, t.L(), c, c.All(), mixedversion.AlwaysUseLatestPredecessors)
> 
> 	if err := c.PutE(ctx, t.L(), t.DeprecatedWorkload(), "./workload", c.All()); err != nil {
> ```

A more common setup for these tests is to have the `workload` running on an arbitrary (but generally the last) node in the cluster and having the workload itself pick the gateway crdb node (which most workloads already do).

In other words, we don't need to upload `workload` to every node :slightly_smiling_face: 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivHFPY2OCylMbmpuVj:-NivHFPY2OCylMbmpuVk:b-8jyhc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L57)):*
> ```Go
> 	mvt := mixedversion.NewTest(ctx, t, t.L(), c, c.All(), mixedversion.AlwaysUseLatestPredecessors)
> 
> 	if err := c.PutE(ctx, t.L(), t.DeprecatedWorkload(), "./workload", c.All()); err != nil {
> ```

Nit: can be just `c.Put()`
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivEzhS3gZwjjeOXWCd:-NivEzhT0Py24D8XyWVb:br0dcze) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L63)):*
> ```Go
> 	// Run the schemachange workload on a random node, along with validating the schema changes for the cluster on a random node.
> 	schemaChangeAndValidationStep := func(
> 		ctx context.Context, l *logger.Logger, rand *rand.Rand, h *mixedversion.Helper,
> ```

Small comment: I thought we had a linter that stopped us from having variable names that shadowed package names? It seems we don't anymore. I could swear I've hit that linter before :smile: 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivCSKC1GdsI-M668fQ:-NivCSKC1GdsI-M668fR:b-uwkwk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L66)):*
> ```Go
> 	) error {
> 		numFeatureRuns += 1
> 		l.Printf("Workload step run: %d", numFeatureRuns)
> ```

For my own understanding: what value do you get out of this counter? It seems easy enough to know how many times the workload has run by looking at the test plan.

Nothing wrong with the counter, just want to understand if there's some usability problem to solve.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivGlyL0PjCG8DPm8Mm:-NivGlyL0PjCG8DPm8Mn:b-g706r4) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L67)):*
> ```Go
> 		numFeatureRuns += 1
> 		l.Printf("Workload step run: %d", numFeatureRuns)
> 		runCmd := roachtestutil.NewCommand("./workload run schemachange").
> ```

Now that you added support for deterministic schemachange operations (:tada:), we should make use of it here to help reproducing test failures with something like:

```go
workloadSeed := rng.Int63()
roachtestutil.NewCommand("COCKROACH_RANDOM_SEED=%d ./workload run schemachange", workloadSeed)
```
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivCdPT3XMdsLmoA3vA:-NivCdPT3XMdsLmoA3vB:bvszl6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L71)):*
> ```Go
> 			Flag("max-ops", maxOps).
> 			Flag("concurrency", concurrency).
> 			Arg("{pgurl:1-%d}", c.Spec().NodeCount).
> ```

Nit: This could be `("{pgurl:%s}", c.All())`. Preferred because it's nice to keep the representation of the nodes internal.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivDt8K229VMrFFij3z:-NivDt8K229VMrFFij4-:b3y5pt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L81)):*
> ```Go
> 		if c.IsLocal() {
> 			// TODO(before merge): is there a c.localCertsDir equivalent to use here?
> 			fmt.Println("ignore lint err for now")
> ```

Not sure I understand what's happening here. Let me know if you have questions about the secure cluster setup.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 84 at r2](https://reviewable.io/review [...]

2023-11-13 20:53 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niv9_CK5yXUvSuI6Sz8:-Nj89nXz8uYZETgnAptI:b8q4b6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L33)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

This comment seems outdated now?
</blockquote></details>

ah - thank you for catching this
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niv9cj49ClL7hV5q_v8:-Nj8ConxAXPppJ7E4MQQ:b-fuuowd) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L40)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

For consideration and my own understanding: why do we choose these values? 100 ops seems like very little, could we change this to at least 1000?
</blockquote></details>

good question - I think Stan asked this question 2 years ago (https://cockroachlabs.slack.com/archives/C0331MYJ8BW/p1649129613095089?thread_ts=1649084584.440829&cid=C0331MYJ8BW). I asked a colleague and they said: "The only reason was intermittent failures might get worse".


i shall bump the number of maxOps :dancers: and stress it
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-Nj95uz92Qr4Kh2gz2lc:bw8x7qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Just curious: do we "rediscover" bugs if we run it without `AlwaysUseLatestPredecessors`? If so, which ones?
</blockquote></details>

Hmmm none that I can specify. Wanted to make note: whenever I have a test that doesn't start at v23.1.*, the roachtest tends to fail with something like:
```
"workerId": 4,

  "clientTimestamp": "20:41:49.230931",

  "ops": \[

   "BEGIN",

   {

    "sql": "CREATE SEQUENCE IF NOT EXISTS public.seq10",

    "potentialExecErr": "XXUUU"

   },

   {

    "sql": "ALTER TABLE public.table12 ALTER COLUMN \\"IrrelevantColumnName\\" DROP NOT NULL",

    "expectedExecErr": "42P01"

   }

  \],

  "expectedExecErrors": "42P01",

  "expectedCommitErrors": "",

  "message": "ROLLBACK; Successfully got expected execution error.: ERROR: relation \\"public.table12\\" does not exist (SQLSTATE 42P01)"

 }

 Error: \*\*\*UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: index "IrrelevantIndexName" does not exist (SQLSTATE 42704)
```

cc: @rafiss would you by chance know why this is happening? this "alter column irrelevantcolumnname" seems to have existed during operation generation from 21.2.0
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivHFPY2OCylMbmpuVj:-Nj8HPUe9PSwmTgEkuYj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L57)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: can be just `c.Put()`
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivAj5A4R7uoqO6MZJ4:-Nj8HQLp6YhbA1d0nIC_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L57)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

A more common setup for these tests is to have the `workload` running on an arbitrary (but generally the last) node in the cluster and having the workload itself pick the gateway crdb node (which most workloads already do).

In other words, we don't need to upload `workload` to every node :slightly_smiling_face:
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivEzhS3gZwjjeOXWCd:-Nj8LT7c0vgtcDWZ2eNK:b2nhk5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L63)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Small comment: I thought we had a linter that stopped us from having variable names that shadowed package names? It seems we don't anymore. I could swear I've hit that linter before :smile:
</blockquote></details>

O.O
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivCSKC1GdsI-M668fQ:-Nj8MNYE9dolrbqlU1W3:bhi401r) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L66)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

For my own understanding: what value do you get out of this counter? It seems easy enough to know how many times the workload has run by looking at the test plan.

Nothing wrong with the counter, just want to understand if there's some usability problem to solve.
</blockquote></details>

yeah this just seems like an artifact of the past - i do agree that the test plan most likely means that we don't have a strong need for this counter anymore, but i figured that there isn't any harm in keeping it in
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivGlyL0PjCG8DPm8Mm:-Nj8Xvjw0yKFiSJqTHIQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L67)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Now that you added support for deterministic schemachange operations (:tada:), we should make use of it here to help reproducing test failures with something like:

```go
workloadSeed := rng.Int63()
roachtestutil.NewCommand("COCKROACH_RANDOM_SEED=%d ./workload run schemachange", workloadSeed)
```
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivCdPT3XMdsLmoA3vA:-Nj8Swwt7tppjpJCv6Sz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L71)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: This could be `("{pgurl:%s}", c.All())`. Preferred because it's nice to keep the representation of the nodes internal.
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivDt8K229VMrFFij3z:-Nj8TAiM37JHSA0qCNoE:b5ikeak) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L81)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Not sure I understand what's happening here. Let m [...]

2023-11-14 17:05 UTC, rafiss requested changes
looks good overall! my comments are all pretty minor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NjDmm8P0uH13Nk8pwiL:b-2c90ig)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjDh8Lo2-efvswa7qDL:b-qrftwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> Just curious: do we "rediscover" bugs if we run it without `AlwaysUseLatestPredecessors`? If so, which ones?

more of a meta-question, but what value do we get out of the default behavior of not using the latest predecessor? i see two cases:
- we have not discovered a bug yet. in this case, the bug will exist in the latest predecessor, as well as in versions before the latest predecessor.
- we have discovered the bug. in this case, only more recent predecessor versions will have the fix, and if we test with older versions, we are liable to "re-discover" the bug.

> cc: [@rafiss](https://github.com/rafiss) would you by chance know why this is happening? this "alter column irrelevantcolumnname" seems to have existed during operation generation from 21.2.0

I am not sure.. but I see that the error is `ERROR: index "IrrelevantIndexName" does not exist`, but the commands above are actually touching `IrrelevantColumnName`. is something missing from the logs?
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivEzhS3gZwjjeOXWCd:-NjDleJ36T0P5ZdI-hJ7:b-243fri) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L63)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

O.O
</blockquote></details>

nit: rename `rand` to `r` or `rng`
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NjDgvuWDAQNrsz_zm2i:-NjDgvuWDAQNrsz_zm2j:bq0ckp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/68040466a00a93a7b1f0fbc9490d714fd1a200a7/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L29)):*
> ```Go
> 	r.Add(registry.TestSpec{
> 		// schemachange/mixed-versions tests random schema changes (via the schemachange workload)
> 		// in a mixed version state, validating that the cluster is still healthy (via .
> ```

nit: the comment is incomplete
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NjDm0rz4f0tfTPnstjk:-NjDm0rz4f0tfTPnstjl:b-y4hpph) ([raw file](https://github.com/cockroachdb/cockroach/blob/68040466a00a93a7b1f0fbc9490d714fd1a200a7/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L64)):*
> ```Go
> 		numFeatureRuns += 1
> 		l.Printf("Workload step run: %d", numFeatureRuns)
> 		workloadSeed := rand.Int63()
> ```

nit: let's get the seed using `_, workloadSeed := randutil.NewTestRand()`

i believe that does something a bit smarter so that tests are seeded consistently across runs based on their name. actually, i'm not sure if that applies to roachtests or only to unit tests, but probably better to make the way we get a seed consistent across the codebase.


<!-- Sent from Reviewable.io -->

2023-11-14 17:32 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @rafiss)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjDqJIkAYaSAPUdu4fR:bwcy95k) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> what value do we get out of the default behavior of not using the latest predecessor

* An upgrade path closer to what customers might actually go through. Not everyone is running the latest patch release at all times, especially in self-hosted.
* A bug may only become apparent later. For example, v22.2.4 and below could have some behaviour that only becomes relevant when we start running 23.1.
* Just because a bug exists across all patch releases does not mean they are equally likely to manifest in all of them. This is especially the case historically when larger backports happened somewhat regularly.

These were some of the motivations for the default behaviour. That said, it does come with the trade-off that we might re-discover bugs. In cases where that's a problem for a test, the "always use latest" option is available. I think tests should use the default when possible.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NjDm0rz4f0tfTPnstjk:-NjDrskkCPmZlSNAEcd6:b-oz3vwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/68040466a00a93a7b1f0fbc9490d714fd1a200a7/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L64)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's get the seed using `_, workloadSeed := randutil.NewTestRand()`

i believe that does something a bit smarter so that tests are seeded consistently across runs based on their name. actually, i'm not sure if that applies to roachtests or only to unit tests, but probably better to make the way we get a seed consistent across the codebase.
</blockquote></details>

I'd recommend not using that. That package is primarily written with unit tests in mind, doing string matching on test function names, and that doesn't translate well to roachtests.

In addition, these mixedversion functions should see the same `rand.Rand` instances when the same `COCKROACH_RANDOM_SEED` is passed. That should be the main way to reproduce test failures and get consistent random choices across runs:

https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#reproducing-failures


<!-- Sent from Reviewable.io -->

2023-11-15 03:43 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-Niv9cj49ClL7hV5q_v8:-NjG-jrA17szRMPb6_fU:b82bgh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L40)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

good question - I think Stan asked this question 2 years ago (https://cockroachlabs.slack.com/archives/C0331MYJ8BW/p1649129613095089?thread_ts=1649084584.440829&cid=C0331MYJ8BW). I asked a colleague and they said: "The only reason was intermittent failures might get worse".


i shall bump the number of maxOps :dancers: and stress it
</blockquote></details>

1000 ops seems ok - i don't see any intermittent failures getting worse and throwing an unexpected error or anything. let's stick with this and see how the nightlies like it
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjFA-xw7dpEvjZWITn6:b-i7oc7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> what value do we get out of the default behavior of not using the latest predecessor

* An upgrade path closer to what customers might actually go through. Not everyone is running the latest patch release at all times, especially in self-hosted.
* A bug may only become apparent later. For example, v22.2.4 and below could have some behaviour that only becomes relevant when we start running 23.1.
* Just because a bug exists across all patch releases does not mean they are equally likely to manifest in all of them. This is especially the case historically when larger backports happened somewhat regularly.

These were some of the motivations for the default behaviour. That said, it does come with the trade-off that we might re-discover bugs. In cases where that's a problem for a test, the "always use latest" option is available. I think tests should use the default when possible.
</blockquote></details>

For posterity: we were running into some weird command failure with `cockroach debug doctor examine`:

```
run\_154213.137443734\_n1\_cockroach-debug-doct: 15:42:13 cluster.go:2189: > ./cockroach debug doctor examine cluster --certs-dir certs
ERROR: current transaction is aborted, commands ignored until end of transaction block
SQLSTATE: 25P02
```

The trend looked like it fell under the fact that we would stage the current binary on every mixed-version setup - meaning that there would be times where we would see failures due to the fact that the workload really only works 1 back from the current version it is on.

The solution discussed with Rafi was to set AlwaysUseLatestPredecessor, but Renato mentioned we could just stage the workload binary to align with the upgrade being performed.

I will do the latter in a follow-up PR

I tried working this out with
```
if err := c.Stage(ctx,  t.L(),  "workload",  helper.Context().FromVersion.Version.String(),  "",  workloadNode,  ); err != nil {  
return err  
}
```
in my OnStartup hook, but end up with an incorrect workload link - it points to cockroach-edge storage bucket and the suffix of the URL looks something like `cockroach/workload.v23.1.11` - am I doing something wrong here? 
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivEzhS3gZwjjeOXWCd:-NjFBQgy0TnjMeZgw2GM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: rename `rand` to `r` or `rng`
</blockquote></details>

done
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NjDgvuWDAQNrsz_zm2i:-NjF9xMh1H45d33bfQdI:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/68040466a00a93a7b1f0fbc9490d714fd1a200a7/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the comment is incomplete
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-15 15:38 UTC, DarrylWong approved these changes
Not too familiar with the latest predecessor issue but besides that it lgtm

2023-11-15 18:44 UTC, renatolabs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work! :clap: 

The only comment I'd recommend addressing before merging is the one about `--local` mode. Others are nice to have but can be follow up work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NjJHdpY4EcJOVU1JYjr:b-ictm42)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @rafiss)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjJEBL02MardAkn7NKm:b-h1x9fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
A couple of comments:

> The solution discussed with Rafi was to set AlwaysUseLatestPredecessor

I'm confused how this is related to the schemachange workload only working up to 1 version back. `AlwaysUseLatestPredecessors` forces the test to always to pick the latest patch release when using previous releases; `workload` would not be involved.

FWIW, I ran this test 20 times on my gceworker _without_ `AlwaysUseLatestPredecessors` and didn't observe any failures. I still think it's a good idea to not use this option unless it flakes. It's your team's call, but IMO the test is stronger without it.

> Renato mentioned we could just stage the workload binary to align with the upgrade being performed

This suggestion was to deal with the fact that `workload schemachange` only works up to 1 version back. It would unfortunately be a little more complicated than the code you shared, which makes me think that roachtest should provide a higher level API. I'll add this to test eng's backlog, so you can ignore this suggestion for now.

> looked like it fell under the fact that we would stage the current binary on every mixed-version setup

Do we understand why `debug doctor` would fail in this way? And more generally, if the test failed in a similar way in a nightly run, would SQL Foundations have enough information in the artifacts to diagnose the issue? This `debug doctor` command should be a bit more verbose and mention which statement failed; unless this information is available somewhere other than stdout/stderr.
___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NjJH-h5CMPK-xhckmh9:-NjJH-h5CMPK-xhckmhA:bf97otn) ([raw file](https://github.com/cockroachdb/cockroach/blob/686072fc7e2667e22fb9c7f6cb68310936969dea/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L84)):*
> ```Go
> 		runCmd = roachtestutil.NewCommand("%s debug doctor examine cluster", test.DefaultCockroachPath).
> 			Flag("certs-dir", certs).
> 			String()
> ```

I'd strongly recommend adding something like the code below so that this test will work in local mode:

```go
randomNode := h.RandomNode(r, c.All())
doctorURL := fmt.Sprintf("{pgurl:%d}", randomNode)

  // ...
  Flag("url", doctorURL).
  String()
```


<!-- Sent from Reviewable.io -->

2023-11-15 19:06 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjJMv6j4m2x1x-nlJYe:b-46pfnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> The solution discussed with Rafi was to set AlwaysUseLatestPredecessor, but Renato mentioned we could just stage the workload binary to align with the upgrade being performed.

small correction: we had discussed using `MaxUpgrades(1)` to solve the problem of the workload only being compatible with the branch it was build from and the major version before that.


<!-- Sent from Reviewable.io -->

2023-11-15 19:11 UTC, annrpom commented
> we had discussed using MaxUpgrades(1) to solve the problem of the workload only being compatible with the branch it was build from and the major version before that.

my memory serves me wrong everytime (apologies) - i just had a misunderstanding of AlwaysUseLatestPredecessors and accidentally put some words in Rafi's mouth 💯

2023-11-15 19:13 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjJNkfJERqg7FEzuXZQ:bfw0jmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> Just because a bug exists across all patch releases does not mean they are equally likely to manifest in all of them. This is especially the case historically when larger backports happened somewhat regularly.

i don't really follow the intuition for this. if a bug is undiscovered, i'd expect it to be just as likely to appear in the latest patch release

also, i feel like not using the latest predecessor will stop making sense as soon as we discover the first bug for which we need to backport a fix. after that happens, then we know for certain that running on earlier predecessor versions is likely to hit the same bug.


<!-- Sent from Reviewable.io -->

2023-11-15 20:00 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @rafiss)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjJXmmg82O-_7DPIowK:bcrqohp) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
> if a bug is undiscovered, i'd expect it to be just as likely to appear in the latest patch release

I think there is enough non-determinism in every component of the database that backported changes can make certain ordering of events (and their implications) more or less likely to occur. I unfortunately don't have a good example offhand of a bug that would only be revealed by using older versions, but the codebase is complex enough that I believe it's not hard to imagine that it's not impossible to have certain things  be more likely in certain patch releases than in others.

I also think this is more important when the feature tested involves dealing with persisted state (in this case, jobs, descriptors, etc).

> not using the latest predecessor will stop making sense as soon as we discover the first bug for which we need to backport a fix

I agree; My (again, optional) suggestion is to not have that option unless it's known to be necessary.


<!-- Sent from Reviewable.io -->

2023-11-15 21:59 UTC, rafiss approved these changes
lgtm! 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-:-NjJz65O2M0TbXBenepY:b-nzoors)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_schemachange.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113890#-NivARIk27gE174_9Orj:-NjJz9aE8DboxbbGgPUf:b-qwh2oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/86b26f36aad9652a31ef45c9065d5b9284df2359/pkg/cmd/roachtest/tests/mixed_version_schemachange.go#L55)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> if a bug is undiscovered, i'd expect it to be just as likely to appear in the latest patch release

I think there is enough non-determinism in every component of the database that backported changes can make certain ordering of events (and their implications) more or less likely to occur. I unfortunately don't have a good example offhand of a bug that would only be revealed by using older versions, but the codebase is complex enough that I believe it's not hard to imagine that it's not impossible to have certain things  be more likely in certain patch releases than in others.

I also think this is more important when the feature tested involves dealing with persisted state (in this case, jobs, descriptors, etc).

> not using the latest predecessor will stop making sense as soon as we discover the first bug for which we need to backport a fix

I agree; My (again, optional) suggestion is to not have that option unless it's known to be necessary.
</blockquote></details>

i see. well i guess i'd be fine either way, just getting paranoid about avoiding flakes


<!-- Sent from Reviewable.io -->

2023-11-20 16:02 UTC, annrpom commented
> I'd strongly recommend adding something like the code below so that this test will work in local mode:

done!

I have an issue open on the `debug doctor` command here: https://github.com/cockroachdb/cockroach/issues/114722

bors r+

2023-11-20 17:29 UTC, merged

2023-11-21 16:16 UTC, renatolabs commented
Should we backport this to 23.2 / 23.1?

2023-11-22 20:41 UTC, annrpom commented
blathers backport 23.2 23.1