dbconsole: add KV admission slots exhaustion chart
cockroachdb/cockroach pull request #114199
Opened 2023-11-09 22:39 UTC by aadityasondhi

This patch replaces the total slots and used slots with a graph of admission slot exhaustion duration. This is a better indicator of CPU resource exhaustion in AC.

Fixes: #113773.

Release note: None

2023-11-09 22:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114199)
<!-- Reviewable:end -->

2023-11-09 22:40 UTC, aadityasondhi commented
Will post a screenshot of how the new graph looks shortly.

2023-11-10 21:19 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114199#-Niv5bWn6_75p58ixDSc:-Niv5bWn6_75p58ixDSd:b-g12o4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e46912daa5ac976850028a621eb76f524848f6e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L127)):*
> ```XML
>               nodeDisplayName(nodeDisplayNameByID, nid)
>             }
>             sources={[nid]}
> ```

need a `nonNegativeRate`


<!-- Sent from Reviewable.io -->

2023-11-14 16:16 UTC, aadityasondhi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114199#-Niv5bWn6_75p58ixDSc:-NjDbf9CD7MnwDtU_DIG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e46912daa5ac976850028a621eb76f524848f6e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L127)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

need a `nonNegativeRate`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-14 16:49 UTC, sumeerbhola approved these changes
:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114199#-:-NjDjBiX23P-N0bS8j4p:b3kr9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114199#-Niv5bWn6_75p58ixDSc:-NjDj-FOARengPWkzmpb:b-l2qy5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e46912daa5ac976850028a621eb76f524848f6e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L127)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you check that this is working as expected by running a single node cluster with  kv0 with high concurrency and large block size that will trigger overload.


<!-- Sent from Reviewable.io -->

2023-11-14 16:58 UTC, aadityasondhi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114199#-Niv5bWn6_75p58ixDSc:-NjDlDGg0F4OCGiogtql:bo1p5gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e46912daa5ac976850028a621eb76f524848f6e/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L127)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you check that this is working as expected by running a single node cluster with  kv0 with high concurrency and large block size that will trigger overload.
</blockquote></details>

Yeah that is the plan, will post results shortly


<!-- Sent from Reviewable.io -->

2023-11-14 17:55 UTC, aadityasondhi commented
@sumeerbhola 

<img width="986" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/fafeecde-31be-487f-8ad7-b06a9ef6ca86">

2023-11-14 22:09 UTC, aadityasondhi commented
bors r=sumeerbhola

2023-11-14 23:22 UTC, merged