sql: ALTER PK carries over comments from old to new primary index
cockroachdb/cockroach pull request #114354
Opened 2023-11-13 17:14 UTC by Xiang-Gu

Fixes #114081

Release note (sql change): Previously, when session variable `use_declarative_schema_changer=off`, ALTER PK will delete any comments associated with the old primary index and with the old primary key constraint. This is inconsistent with the behavior with when `use_declarative_schema_changer=on`, which is the default setting, where those comments would be carried over to the new primary index. Furthermore, the old behavior is buggy (one such bug is #114081).

2023-11-13 17:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114354)
<!-- Reviewable:end -->

2023-11-13 19:30 UTC, Xiang-Gu commented
We decided to not backport this change to 23.2 because in 23.2 the default setting uses the declarative schema changer and it won't run into the issue.

2023-11-13 21:05 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9SjtU10t-kLVV7Jcw):*
this should be `Release note (bug fix)`
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9SnXe2wMhDwMFShIq):*
nit: "will" -> "would"
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9SyV32NnxDjyCM23D):*
"behavior is buggy" is too broad for a release note. Check out the guidelines at https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Descriptions

This could instead say "The old behavior also caused a bug that could prevent the `SHOW CREATE TABLE` command from working."
___
*[`pkg/sql/schema_changer.go` line 1565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UjG88NZ26sE3OhJ7:-Nj9UjG88NZ26sE3OhJ8:bg09myt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d1479743f71d7fa9f1215f6d9ba4fdfaad1d22/pkg/sql/schema_changer.go#L1565)):*
> ```Go
> 			}
> 
> 			// If a primary index swap or any indexes are being dropped clean up any
> ```

it looks like this old behavior was initially added to fix a different bug: https://github.com/cockroachdb/cockroach/pull/76277

does your latest fix still work for that case?
___
*[`pkg/sql/schema_changer.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9Teth0ZVNlTBEbQSR:-Nj9Teth0ZVNlTBEbQSS:b1ep0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1569)):*
> ```Go
> 			// the comments associated with the old indexes to the new ones.
> 			if pkSwap := m.AsPrimaryKeySwap(); pkSwap != nil {
> 				oldIndexIDs := append([]descpb.IndexID{pkSwap.PrimaryKeySwapDesc().OldPrimaryIndexId}, pkSwap.PrimaryKeySwapDesc().OldIndexes...)
> ```

nit: these lines would be much less verbose if we declared a variable:
```
pkSwapDesc := pkSwap.PrimaryKeySwapDesc()
```
___
*[`pkg/sql/schema_changer.go` line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UORs5UxL3cyi0xPs:-Nj9UORs5UxL3cyi0xPt:b-p0rmdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1576)):*
> ```Go
> 						return err
> 					}
> 					newIndexDesc, err := catalog.MustFindIndexByID(scTable, newIndexIDs[i])
> ```

is there a contract somewhere that oldIndexIDs and newIndexIDs will always be the same length, and that the elements will be in an equivalent order to allow the swap below?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9V1BD9LKxN4_phW2s:-Nj9V1BE9Hp8GfxSG1Y6:b-xl6dfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1608)):*
> ```
> 
> # Ensure `SHOW CREATE` does not break (issue #114081).
> statement ok
> ```

would it be better for the assertion to actually show the result of this query? (i.e. use an `onlyif config local-legacy-schema-changer` directive, then check for the names)


<!-- Sent from Reviewable.io -->

2023-11-13 21:10 UTC, chrisseto approved these changes
LGTM! Just a couple comment nits

2023-11-13 21:10 UTC, chrisseto commented on pkg/sql/logictest/testdata/logic_test/alter_primary_key
> +# Ensure `SHOW CREATE` does not break (issue #114081).
nit: Can you include a short description of #114081 ? If someone is reading through this code, having to navigate to a different resource to even get a hint of what's happening can be frustrating.

What would you think about:
```
# Ensure that comment references have been appropriately updated by running `SHOW CREATE` (See issue #114081 for details)
```

2023-11-13 21:10 UTC, chrisseto commented on pkg/sql/show_create_clauses.go
> +	subID   int // the column, or index, or constraint ID that this comment is associated to.
nit (assuming that subID is short for SubjectID):
```suggestion
	subID   int // the column, index, or constraint ID that is the subject of this comment
```

2023-11-13 21:10 UTC, chrisseto commented on pkg/sql/schema_changer.go
> +			// the comments associated with the old indexes to the new ones.
small grammatical nit:
```suggestion
			// If `m` is a primary index swap, which results in the creation of a
			// primary index and possibly new, rewritten, secondary indexes, carry over
			// the comments associated with the old indexes to the new ones.
```

2023-11-14 16:12 UTC, Xiang-Gu reviewed
Thanks for your feedback and I've addressed them all. @rafiss When you get a chance, can you give it another look? Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-:-NjDaQSVEvkcnIkDphli:b-c3xe6x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @rafiss)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9SjtU10t-kLVV7Jcw):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this should be `Release note (bug fix)`
</blockquote></details>

Done.
___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9SyV32NnxDjyCM23D):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"behavior is buggy" is too broad for a release note. Check out the guidelines at https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Descriptions

This could instead say "The old behavior also caused a bug that could prevent the `SHOW CREATE TABLE` command from working."
</blockquote></details>

Done.
___
*[`pkg/sql/schema_changer.go` line 1565 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UjG88NZ26sE3OhJ7:-NjDV604EKc1-GrlTlOh:b-9nos7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d1479743f71d7fa9f1215f6d9ba4fdfaad1d22/pkg/sql/schema_changer.go#L1565)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like this old behavior was initially added to fix a different bug: https://github.com/cockroachdb/cockroach/pull/76277

does your latest fix still work for that case?
</blockquote></details>

yes, that fix was later overridden by this commit (https://github.com/cockroachdb/cockroach/commit/55cd39856b5b4d40b6979b045cdd9eb6b0a04560) where we changed the behavior from "dropping comments" to "carrying over comments" in declarative schema changer. This PR is to change the legacy schema changer to match that behavior.
___
*[`pkg/sql/schema_changer.go` line 1567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#gh-1391710006:-NjDVaiG-kxJG2ezRj36:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1567)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

small grammatical nit:
```suggestion
			// If `m` is a primary index swap, which results in the creation of a
			// primary index and possibly new, rewritten, secondary indexes, carry over
			// the comments associated with the old indexes to the new ones.
```
</blockquote></details>

Done.
___
*[`pkg/sql/schema_changer.go` line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UORs5UxL3cyi0xPs:-NjDWFHl4oo_u6T2Auyt:b-hyc80k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1576)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is there a contract somewhere that oldIndexIDs and newIndexIDs will always be the same length, and that the elements will be in an equivalent order to allow the swap below?
</blockquote></details>

It's a soft contract. So the intention is definitely for them to be in sync, as in comments [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/structured.proto#L561-L564). The way we append to those two slices [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_primary_key.go#L504-L505) ensures that, but I didn't see any checks. Do you think it'd be better if I add some guardrails here to ensure 1. their length is the same, and 2. they don't have duplicates, and if so, return an assertionError?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#gh-1391703436:-NjDYXISCCqsLrpgTQD3:b-5x7ght) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1607)):*
<details><summary><i>Previously, chrisseto (Chris Seto) wrote…</i></summary><blockquote>

nit: Can you include a short description of #114081 ? If someone is reading through this code, having to navigate to a different resource to even get a hint of what's happening can be frustrating.

What would you think about:
```
# Ensure that comment references have been appropriately updated by running `SHOW CREATE` (See issue #114081 for details)
```
</blockquote></details>

changed to an actual query to show the output of `show create`
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9V1BD9LKxN4_phW2s:-NjDYZSZ2LDymV_0V3XG:b-prmfrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1608)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be better for the assertion to actually show the result of this query? (i.e. use an `onlyif config local-legacy-schema-changer` directive, then check for the names)
</blockquote></details>

I like this idea! It also makes it more obvious that the results are identical but in slightly different order. Done


<!-- Sent from Reviewable.io -->

2023-11-16 20:36 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @Xiang-Gu)

___
*[`pkg/sql/schema_changer.go` line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UORs5UxL3cyi0xPs:-NjOpIYUD9X2xVbfEhjR:b-dween) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1576)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

It's a soft contract. So the intention is definitely for them to be in sync, as in comments [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/structured.proto#L561-L564). The way we append to those two slices [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_primary_key.go#L504-L505) ensures that, but I didn't see any checks. Do you think it'd be better if I add some guardrails here to ensure 1. their length is the same, and 2. they don't have duplicates, and if so, return an assertionError?
</blockquote></details>

i think we can skip that, since i'd consider the comment you linked enough of a contract.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1604 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-NjOq-3l5an0WXRpFyv8:-NjOq-3l5an0WXRpFyv9:b-rpm83e) ([raw file](https://github.com/cockroachdb/cockroach/blob/891b3569c8aa20df041f613a3c9a68f378ba4f15/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1604)):*
> ```
> ----
> COMMENT ON INDEX public.pkey_comment@i2 IS 'idx2';
> COMMENT ON INDEX public.pkey_comment@pkey IS 'idx';
> ```

interesting, i would have expected the new primary key to be called `pkey_comment_pkey` (like how the old schema changer names it) why did we pick this `pkey` name?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-NjOpjxL1mchh4k04xyh:-NjOpjxL1mchh4k04xyi:b-qqtx57) ([raw file](https://github.com/cockroachdb/cockroach/blob/891b3569c8aa20df041f613a3c9a68f378ba4f15/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1610)):*
> ```
> onlyif config local-legacy-schema-changer
> query T
> SELECT substring(create_statement, strpos(create_statement, 'COMMENT')) FROM [SHOW CREATE pkey_comment];
> ```

nice!  if we add an ORDER BY to the results, could we could the same result in both configs?


<!-- Sent from Reviewable.io -->

2023-11-16 21:46 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @rafiss)

___
*[`pkg/sql/schema_changer.go` line 1576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-Nj9UORs5UxL3cyi0xPs:-NjP4dQt1GcXOVNoDxpd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f599811028d5974105a7f40c3229e875093cce06/pkg/sql/schema_changer.go#L1576)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we can skip that, since i'd consider the comment you linked enough of a contract.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1604 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-NjOq-3l5an0WXRpFyv8:-NjP4gVV0LDUkB4vjHNn:b2kykau) ([raw file](https://github.com/cockroachdb/cockroach/blob/891b3569c8aa20df041f613a3c9a68f378ba4f15/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1604)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

interesting, i would have expected the new primary key to be called `pkey_comment_pkey` (like how the old schema changer names it) why did we pick this `pkey` name?
</blockquote></details>

It's an interesting debate -- do we think the new primary key should reuse the old primary key's name (dsc) or uses a new name (lsc). IMO, I'm inclined to DSC simply bc we are also carrying over the comments associated with the old primary index.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-NjOpjxL1mchh4k04xyh:-NjP58ig2MU_XvLKFrjd:b4y83pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/891b3569c8aa20df041f613a3c9a68f378ba4f15/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1610)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice!  if we add an ORDER BY to the results, could we could the same result in both configs?
</blockquote></details>

we could except that the name of the new primary key does not match, as illustrated above.


<!-- Sent from Reviewable.io -->

2023-11-16 21:47 UTC, Xiang-Gu commented
TFTR!

bors r+

2023-11-16 21:48 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chrisseto and @Xiang-Gu)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_primary_key` line 1604 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114354#-NjOq-3l5an0WXRpFyv8:-NjP5nMb0eLZhWh9B2oT:b-yra42t) ([raw file](https://github.com/cockroachdb/cockroach/blob/891b3569c8aa20df041f613a3c9a68f378ba4f15/pkg/sql/logictest/testdata/logic_test/alter_primary_key#L1604)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

It's an interesting debate -- do we think the new primary key should reuse the old primary key's name (dsc) or uses a new name (lsc). IMO, I'm inclined to DSC simply bc we are also carrying over the comments associated with the old primary index.
</blockquote></details>

ah i see - if the name previously was explicitly named as `pkey`, then i agree with the new behavior too.


<!-- Sent from Reviewable.io -->

2023-11-16 23:11 UTC, merged