multiregion: fix flake in TestRegionLivenessProber
cockroachdb/cockroach pull request #114346
Opened 2023-11-13 15:39 UTC by fqazi

Previously, the TestRegionLivenessProber had too narrow of a timing window to detect region failure since the default timeout to declare a region dead was around ~40 seconds. As a result, SucceedsSoon could timeout before the failure was fully detected, leading to intermittent failures. This patch addresses this by extending the timeout for detecting the region failure.

Fixes: #114245

Release note: None

2023-11-13 15:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114346)
<!-- Reviewable:end -->

2023-11-13 19:19 UTC, rafiss requested changes

2023-11-13 19:19 UTC, rafiss commented on pkg/ccl/multiregionccl/regionliveness_test.go
> +	//skip.UnderStress(t)
nit: uncomment this or delete the line.

2023-11-13 19:19 UTC, rafiss commented on pkg/ccl/multiregionccl/regionliveness_test.go
> +	}, time.Minute*2)
instead of making the test take longer, is there a way to make the timeout shorter? is that bad for other reasons?

2023-11-13 20:23 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/multiregionccl/regionliveness_test.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114346#gh-1391580409:-Nj9Ldur0ZzplzTcPfka:bfvxa3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ebd8ed08467f2531037de484efc189e5c19fa1f/pkg/ccl/multiregionccl/regionliveness_test.go#L171)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of making the test take longer, is there a way to make the timeout shorter? is that bad for other reasons?
</blockquote></details>

Good point, reduced the TTL instead


<!-- Sent from Reviewable.io -->

2023-11-13 20:27 UTC, rafiss approved these changes
lgtm!

2023-11-13 21:57 UTC, fqazi commented
@rafiss TFTR!

bors r+

2023-11-14 01:36 UTC, fqazi commented
bors r+

2023-11-14 02:43 UTC, merged