storage: skip counting used bytes during EvalAddSStable
cockroachdb/cockroach pull request #114413
Opened 2023-11-14 13:33 UTC by dt

During EvalAddSSTable we check if the device is close to full to prevent overfilling it via bulk operations. We do this by calling engine.Capacity().

At some point however engine.Capacity started not retrieving the device bytes available and used -- in a quick o(1) sys call -- but started also traversing the store directories to count the actual size of each file. This shows up in the profile of a tight loop of adding virtual sstables, where this filepath.Walk is the majority of the cost of these calls.

The AddSStable call does not actually care how much of the device used space is in-use by the files in the store dir vs other files, as it is only checking if the device is full or not, so it never uses the 'Used' field returned by Capacity() so it can pass an option to simply skip counting these files up and return a summary with only the two device numbers populated.

Release note: none.
Epic: none.

2023-11-14 13:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114413)
<!-- Reviewable:end -->

2023-11-14 14:06 UTC, adityamaru approved these changes

2023-11-14 16:35 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

___
*[`pkg/storage/pebble.go` line 1936 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114413#-NjDeHhjBlF4z2pA5Aag:-NjDeHhjBlF4z2pA5Aah:bj9bxyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9a665abd1aedb301b04e2bec222fa89011d287/pkg/storage/pebble.go#L1936)):*
> ```Go
> 	}
> 
> 	available := p.maxSize - totalUsedBytes
> ```

Not counting `totalUsedBytes` also affects this computation of `available`, which is a problem if `SizeSpec.InBytes` was set.
I was initially going to suggest that we simply have another method which gives us the filesystem available and capacity, but `AddSSTable` should care about the value configured in `SizeSpec`.

What is the rate at which AddSSTable is calling this? One possibility would be to move the `useCached` logic from `Store.Capacity` into this file and have a maximum cache staleness of say 10s.


<!-- Sent from Reviewable.io -->

2023-11-14 22:51 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @stevendanna, and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 1936 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114413#-NjDeHhjBlF4z2pA5Aag:-NjDpHKr9EZb0Yicwwh8:b8b14uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9a665abd1aedb301b04e2bec222fa89011d287/pkg/storage/pebble.go#L1936)):*
Ah, good catch. 

I changed it to an early return, so if set, we just return filesystem available and capacity and skip getting into crib-specifics like maxSize/used/etc. I don't think we need a separate method since this one already has fs available and capacity available, and an appropriate return type, and we can skip the extra computation we don't need with a parameter.

AddSSTable has a contract that it pauses the job that called it if the device on which the store to which the sst is being added is kept is over 95% full. It doesn't care if it is full of crdb data or other data, just that it is approaching full, so fs available and capacity is all it needs. If the allocator/gossip is using crdb data and/or `MaxSize` to make allocation decisions, they can still do so, just by not skipping the additional logic in this method, but for addsstable I don't think we need to do anything beyond the single call to get the fs stats.

> What is the rate at which AddSSTable is calling this?

Currently around 250QPS I think (we observed 2000 SSTs added in 8s, which was almost entirely spent in this Walk call as far as we could tell).


<!-- Sent from Reviewable.io -->

2023-11-15 14:57 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @itsbilal, and @stevendanna)

___
*[`pkg/storage/pebble.go` line 1936 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114413#-NjDeHhjBlF4z2pA5Aag:-NjITriXBqLrOytWwGGe:b-taee98) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9a665abd1aedb301b04e2bec222fa89011d287/pkg/storage/pebble.go#L1936)):*
> AddSSTable has a contract that it pauses the job that called it if the device on which the store to which the sst is being added is kept is over 95% full.

Just curious -- where is this contract specified? And why is the contract in terms of device utilization and not in terms of the size limit specified for the store?


<!-- Sent from Reviewable.io -->

2023-11-26 00:08 UTC, dt commented
Actually I'll just move the RemoteSST check above the store device capacity remaining check since remote ssts don't take up any capacity so they don't need to do the check, either in its current pointlessly expensive form or some cheaper form.

2023-11-26 00:08 UTC, closed without merging