sql/stats: Correctly cancel stats background context on quiesce.
cockroachdb/cockroach pull request #114598
Opened 2023-11-16 19:19 UTC by benbardin

Currently, this can get stuck while quiescing in `ensureAllTables()`, where a SQL query is issued and cannot be completed.

Fixes: #114296
Release note: None

2023-11-16 19:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114598)
<!-- Reviewable:end -->

2023-11-17 08:10 UTC, stevendanna requested changes

2023-11-17 08:10 UTC, stevendanna commented on pkg/sql/stats/automatic_stats.go
> -							return
If you are going remove the stopper.ShouldQuiesce() I would add a `<-ctx.Done()` branch to ensure we are making an equivalent change. Same in the other two locations.

2023-11-17 14:17 UTC, stevendanna approved these changes
Thanks for looking into this! This change makes sense to me.

2023-11-17 17:07 UTC, benbardin commented
bors r+

2023-11-17 17:07 UTC, benbardin commented
TFTR!

2023-11-17 18:32 UTC, merged