changefeedccl: memory opt in sarama metadata fetching
cockroachdb/cockroach pull request #114740
Opened 2023-11-20 18:15 UTC by wenyihu6

Prior to this commit, sarama clients fetch metadata for all topics periodically.
This takes a substantial amount of memory when users create too many topics.
This patch changes the configuration for sarama clients so that we only fetch
metadata for a minimal set of topics that have been necessary.

Fixes: #113576
Release Note: none 
TODO (wenyihu6): add test

2023-11-20 18:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114740)
<!-- Reviewable:end -->

2023-11-27 14:22 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkG9-v7BfexSk64oPQy:-NkG9-v8BXjEL5bEHftV:b-bfl5gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/ccl/changefeedccl/sink_kafka.go#L265)):*
> ```Go
> 			// RefreshMetadata manually to check for any connection error.
> 			// TODO(wenyihu6): check if this is what we want
> 			_ = client.Close()
> ```

I added this part of changes as a separate commit since I'm not sure if we want this. We can discuss more during our 1:1 today if it is complex. 


<!-- Sent from Reviewable.io -->

2023-11-27 15:00 UTC, miretskiy requested changes
Blathers is wrong -- nice job on  writing the roachtest.

I have mostly nits/suggestions on how to improve the test.  Good job on  this!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-:-NkGHrXv34DySQE_j5jU:b-cu417m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkG9-v7BfexSk64oPQy:-NkGA52-5Mg1KeobxDxM:b-c2hnt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/ccl/changefeedccl/sink_kafka.go#L265)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I added this part of changes as a separate commit since I'm not sure if we want this. We can discuss more during our 1:1 today if it is complex.
</blockquote></details>

I think we need this -- otherwise, I think that the Dial() would actually be useless
as no network requests will be made and thus we won't know about
connectivity errors.

Let's return the error -- this is consistent with what was happening before.
NewClient code in sarama does:
```
if conf.Metadata.Full {  
  // do an initial fetch of all cluster metadata by specifying an empty list of topics  
  err := client.RefreshMetadata()  
  if err == nil {  
  } else if errors.Is(err, ErrLeaderNotAvailable) || errors.Is(err, ErrReplicaNotAvailable) || errors.Is(err, ErrTopicAuthorizationFailed) || errors.Is(err, ErrClusterAuthorizationFailed) {  
   // indicates that maybe part of the cluster is down, but is not fatal to creating the client  
   Logger.Println(err)  
  } else {  
   close(client.closed) // we haven't started the background updater yet, so we have to do this manually  
   \_ = client.Close()  
   return nil, err  
  }  
}
```
That is we call RefreshMetadata and sometimes we would return an error which we would treat as
as error to return to the caller.  Thus we should do the same.

You also do not need to ignore `client.Close()` error here; instead you can do:
```
if err := client.RefreshMetadata(); err != nil {
   return errors.CombineErrors(err, client.Close())
}
```
___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1085 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkG9_XC-mYnyK8QUOjb:-NkG9_XC-mYnyK8QUOjc:b-ksc13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/ccl/changefeedccl/sink_kafka.go#L1085)):*
> ```Go
> 	config.Producer.Return.Successes = true
> 	config.Producer.Partitioner = newChangefeedPartitioner
> 	config.Metadata.Full = false
> ```

I know we don't have comments on the other params, but let's start to make things better.
Let's add a short comment, something like `// do not fetch metadata for all topics, just the ones we need`
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1484 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGBtyN8r64NaZWgJWl:-NkGBtyN8r64NaZWgJWm:b-ithy45) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1484)):*
> ```Go
> 		Cluster:          r.MakeClusterSpec(4, spec.Arch(vm.ArchAMD64)),
> 		Leases:           registry.MetamorphicLeases,
> 		CompatibleClouds: registry.AllExceptAWS,
> ```

why except AWS? I think this should work on all clouds?  
I think this is a copy-paste issue.  It's fine to leave it as is since this is consistent with
other tests, but I have filed https://github.com/cockroachdb/cockroach/issues/115093
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1504 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGHJic0TtVouQ-5J69:-NkGHJic0TtVouQ-5J6A:bmjajei) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1504)):*
> ```Go
> 			t.Status("creating kafka topics")
> 			for i := 0; i < 1000; i++ {
> 				if err := kafka.createTopic(ctx, "topicname"+fmt.Sprintf("%v", i)); err != nil {
> ```

use "%d" format; or if you prefer, strconv.Itoa(i)
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGGab-8yJlsDk8My6j:-NkGGab00wrTW0BpELLh:b-rw2k3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1521)):*
> ```Go
> 			results, err := ct.cluster.RunWithDetails(ct.ctx, t.L(),
> 				ct.cluster.Range(1, c.Spec().NodeCount-1),
> 				"grep \"client/metadata fetching metadata for all topics from broker\" logs/cockroach.log")
> ```

I think we should also verify that the log contains the message we do expect to see.
I think you can do this by simplifying your grep pattern:  Grep for
`client/metadata fetching metadata for`.  This will match *both* the thing we expect
not to see -- `client/metadata fetching metadata for all topics` -- as well as the thing
we expect to see `client/metadata fetching metadata for [topicname0 topicname1 ....]`.

So, after you got the grep output, do the error checking and then make sure that
Stdout does not contain the thing we don't want to see and contains the thing we do want
to see.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1532 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGGJNK7MHvhP4x70Me:-NkGGJNK7MHvhP4x70Mf:bhedugp) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1532)):*
> ```Go
> 					t.Fatalf("expected empty stdout but got %s", res.Stdout)
> 				}
> 				if res.Stderr != "" {
> ```

Probably not needed -- grep prints on stdout; and if anything is printed on stderr, it should also exit with error code (and if it's some sort of an "error info" message -- I don't know, like "disk full" -- we don't care about that).


<!-- Sent from Reviewable.io -->

2023-11-27 15:02 UTC, miretskiy commented
I think you should squash the commits together.

2023-11-28 14:13 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGGab-8yJlsDk8My6j:-NkLGmep55ifIL5yBbRS:b-uxut5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1521)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should also verify that the log contains the message we do expect to see.
I think you can do this by simplifying your grep pattern:  Grep for
`client/metadata fetching metadata for`.  This will match *both* the thing we expect
not to see -- `client/metadata fetching metadata for all topics` -- as well as the thing
we expect to see `client/metadata fetching metadata for [topicname0 topicname1 ....]`.

So, after you got the grep output, do the error checking and then make sure that
Stdout does not contain the thing we don't want to see and contains the thing we do want
to see.
</blockquote></details>

Just realized a chicken and egg situation here - calling Dial() here causes sarama to print `client/metadata fetching metadata for all topics from broker` again. We could try changing sarama.Logger inside `Dial()` but it feel unnecessary and might make the code confusing. 


<!-- Sent from Reviewable.io -->

2023-11-28 16:57 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 1085 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkG9_XC-mYnyK8QUOjb:-NkLrCOH5ETpsPkR2jxI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/ccl/changefeedccl/sink_kafka.go#L1085)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I know we don't have comments on the other params, but let's start to make things better.
Let's add a short comment, something like `// do not fetch metadata for all topics, just the ones we need`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-28 16:58 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1484 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGBtyN8r64NaZWgJWl:-NkLrEjF8nZXBJrd7UxR:btyz802) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1484)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why except AWS? I think this should work on all clouds?  
I think this is a copy-paste issue.  It's fine to leave it as is since this is consistent with
other tests, but I have filed https://github.com/cockroachdb/cockroach/issues/115093
</blockquote></details>

I will try looking into this issue after I finish my current milestones. From a brief look, it looks like this convention was introduced by https://github.com/cockroachdb/cockroach/commit/5eb4a53a0d1e6d2c9e49c4382f931e98bbe0968d.


<!-- Sent from Reviewable.io -->

2023-11-28 16:58 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1504 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGHJic0TtVouQ-5J69:-NkLrRsY49y88fRBvELh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1504)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

use "%d" format; or if you prefer, strconv.Itoa(i)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-28 16:58 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGGab-8yJlsDk8My6j:-NkLrTvYE6SQPP_KNxAl:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1521)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Just realized a chicken and egg situation here - calling Dial() here causes sarama to print `client/metadata fetching metadata for all topics from broker` again. We could try changing sarama.Logger inside `Dial()` but it feel unnecessary and might make the code confusing.
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2023-11-28 18:47 UTC, wenyihu6 commented
Do you might know why sarama outputs `client/metadata fetching metadata for [‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×›] from broker ‹×›` with the ‹×› placeholders rather than the actual strings? I tried printing the string and they were replaced by the actual string `client/metadata fetching metadata for [‹customer› ‹history› ‹new_order› ‹district› ‹item› ‹order_line› ‹warehouse› ‹order› ‹stock›] from broker ‹10.142.1.135:9092›` and the test passed. But if I do not try printing it, the test fails.

2023-11-28 19:07 UTC, miretskiy commented
> Do you might know why sarama outputs `client/metadata fetching metadata for [‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×› ‹×›] from broker ‹×›` with the ‹×› placeholders rather than the actual strings? I tried printing the string and they were replaced by the actual string `client/metadata fetching metadata for [‹customer› ‹history› ‹new_order› ‹district› ‹item› ‹order_line› ‹warehouse› ‹order› ‹stock›] from broker ‹10.142.1.135:9092›` and the test passed. But if I do not try printing it, the test fails.

You are looking at redacted file.  It replaces all topic names with "<X>" markers because topic names could be sensitive.
There is also an unredacted file as well...

2023-11-28 19:16 UTC, miretskiy reviewed
just few remaining nits (test improvements).

2023-11-28 20:36 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408265981:-NkMdTzN4fxUG6szeDtP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/ccl/changefeedccl/sink_kafka.go#L262)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: perhaps move this comment outside if err:..
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-28 20:37 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1503 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408267780:-NkMdWyG7JpuEwUmCrym:b-31aih5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/cmd/roachtest/tests/cdc.go#L1503)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

does it take long time to create many topics?
nit: consider having `const numTopics = ...` and use "creating %d kafka topics" status message above.
</blockquote></details>

I cut it to 10 mainly because we are checking to make sure we are not fetching metadata for every topics here. 


<!-- Sent from Reviewable.io -->

2023-11-28 20:38 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1530 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408271791:-NkMdisk3L2CglKqa5CE:b-impaqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/cmd/roachtest/tests/cdc.go#L1530)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

couldn't you just check to make sure that stdout contains
`fmt.Sprintf("fetching metadata for %v topics", allTpccTargets)`

(the %v should print the list, space separated, surrounded by [] -- like you see in the logs).
</blockquote></details>

I think the order that the elements of the slice are printed does not seem to be consistent tho. 
![Screenshot 2023-11-28 at 3.33.21 PM.png](https://files.reviewableusercontent.io/images/reviewable/56973754/226ncOoDEQcjj_pl28S-CEcI/Screenshot%202023-11-28%20at%203.33.21%20PM.png)


<!-- Sent from Reviewable.io -->

2023-11-28 20:41 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1539 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408273686:-NkMe0kb-NNuxLhHBlAr:b-t5w5kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/cmd/roachtest/tests/cdc.go#L1539)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think checking for all topic names explicitly is probably an overkill.
You can simply take "topicname" and make it into a constant with an "obvious" value -- something like `const ignoreTopicPrefix = "ignore_topic_do_not_fetch".  Simply check to see if stdout contains a single instance of that topic prefix. 
</blockquote></details>

Agreed. I changed it back to creating 100 topics as well.


<!-- Sent from Reviewable.io -->

2023-11-28 20:41 UTC, wenyihu6 commented
*[`pkg/cmd/roachtest/tests/cdc.go` line 1532 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114740#-NkGGJNK7MHvhP4x70Me:-NkMeWq-CQX7TJDycb5Q:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/93d358263690432ca1f13a273d20ac1385452a5b/pkg/cmd/roachtest/tests/cdc.go#L1532)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably not needed -- grep prints on stdout; and if anything is printed on stderr, it should also exit with error code (and if it's some sort of an "error info" message -- I don't know, like "disk full" -- we don't care about that).
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2023-11-30 14:23 UTC, wenyihu6 commented
Friendly ping on this review - hoping to merge it this week.

2023-12-12 16:12 UTC, miretskiy approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114740)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 260 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408266586:-NlTmBB3B_AeFejF0jF4:bdvnkna) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/ccl/changefeedccl/sink_kafka.go#L260)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I think some unit tests failed with accessing nil pointer when I excluded this check.
</blockquote></details>

I suspect that's because we use OverrideClientConfig knob (https://github.com/cockroachdb/cockroach/blob/b7b0b433f8db34eaf59872dfb376187f02f588b6/pkg/ccl/changefeedccl/sink_kafka.go#L277-L277)...
```
OverrideClientInit: func(config \*sarama.Config) (kafkaClient, error) {  
  return nil, nil  
},
```
I think it would be better to change those tests to return a non-nil,  &fakeKafkaClient{config} instead.


<!-- Sent from Reviewable.io -->

2023-12-13 03:21 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 260 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/114740#gh-1408266586:-NlWBHRV6nDcCTR_w21F:biz2vq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf6dd86c1a760f39ebff7f79405dc9489bbb0258/pkg/ccl/changefeedccl/sink_kafka.go#L260)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I suspect that's because we use OverrideClientConfig knob (https://github.com/cockroachdb/cockroach/blob/b7b0b433f8db34eaf59872dfb376187f02f588b6/pkg/ccl/changefeedccl/sink_kafka.go#L277-L277)...
```
OverrideClientInit: func(config \*sarama.Config) (kafkaClient, error) {  
  return nil, nil  
},
```
I think it would be better to change those tests to return a non-nil,  &fakeKafkaClient{config} instead.
</blockquote></details>

Done. Changed it to return fakeKafkaClient and nil error instead.

```
OverrideClientInit: func(config *sarama.Config) (kafkaClient, error) {
				client := &fakeKafkaClient{config}
				return client, nil
			},

```


<!-- Sent from Reviewable.io -->

2023-12-13 04:14 UTC, wenyihu6 commented
The last push was to fix the comment & rebase on master.

TFTR!

bors r=miretskiy

2023-12-13 07:32 UTC, merged