lexbase: fix double-escaping in json + sql display format
cockroachdb/cockroach pull request #114707
Opened 2023-11-19 13:25 UTC by chanYe-EAST

This fixes an issue #107518 .

Introduce a new flag, EncNoDoubleEscape, that prevents the escaping of backslashes when they are used as escape characters.

Release note: None

2023-11-19 13:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/114707)
<!-- Reviewable:end -->

2023-11-21 17:09 UTC, rharding6373 requested changes
Thanks for the draft PR! It's nice work. 

The new functionality could use some tests. A new test in `pkg/sql/lexbase/encode_test.go` kind of like `TestEncodeSQLStringSpecial` but uses `lexbase.EncodeSQLStringWithFlags` would be appropriate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-:-NjmjhtMEJc2ymHdq7c4:b37ooee)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chanYe-EAST)

___
*[`pkg/sql/lexbase/encode.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-NjmhXfH-6UK2d1D-9EM:-NjmhXfH-6UK2d1D-9EN:br7w3yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L56)):*
> ```Go
> 	// EncNoDoubleEscape indicates that not escape backslashes used
> 	// as escapes.
> 	EncNoDoubleEscape
> ```

The new declaration needs to move above `EncFirstFreeFlagBit`.
___
*[`pkg/sql/lexbase/encode.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-NjmoPw3Cc6-2mv_ulBn:-NjmoPw3Cc6-2mv_ulBo:b-3fpauq) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L179)):*
> ```Go
> 			nextCh := in[i + 1]
> 			// Hexadecimal Unicode character value.
> 			if (nextCh == 'u' || nextCh == 'U') && i + 5 < len(in) {
> ```

optional: I think this code would be well-suited for a case statement, something like:

```
switch nextCh {
  case 'u', 'U': // Hexadecimal unicode.
    if i + 5 < len(in)
       ... 
  case 'x': // Hexadecimal byte.
    ...
  case 'b', 'f', 'n', ... , '0', '1', ...: // Octal byte.
}

```

I think what you have here works, but I had to reason out whether `nextCh` was modified in the hexadecimal unicode path before reaching the hexadecimal byte condition etc. The case statement makes it easier to reason about and removes the need for the `escapedMap`.
___
*[`pkg/sql/lexbase/encode.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-Njmo0y1Asg8k-9Zk6jl:-Njmo0y1Asg8k-9Zk6jm:b82b4nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L204)):*
> ```Go
> 			}
> 			// Octal byte value and other escaped sequences.
> 			if escapedMap[ch] {
> ```

At this point in the code, isn't `ch` always '\\'? Did you mean `nextCh`?


<!-- Sent from Reviewable.io -->

2023-11-22 13:45 UTC, chanYe-EAST commented
Thank you for your detailed feedbacks!

> The new functionality could use some tests. A new test in pkg/sql/lexbase/encode_test.go kind of like TestEncodeSQLStringSpecial but uses lexbase.EncodeSQLStringWithFlags would be appropriate.

Done. If the test cases are not enough, please let me know.

> The new declaration needs to move above EncFirstFreeFlagBit.

Done.

> optional: I think this code would be well-suited for a case statement, something like:

I agree, case statement is more suited for this.
And also removed ```escapedMap``` and put all things in case statement.

> At this point in the code, isn't ch always '\'? Did you mean ```nextCh```?

My bad. Thank you for pointing out. =)

+) I changed the code to add 'e'' when nothing was escaped by the function but already-escaped characters were found. For example, input string ```{\"a\": \"b\u0099c\"}``` will have output string ```e'{\"a\": \"b\u0099c\"}'```. Is this right behavior?

2023-12-10 18:02 UTC, da-ket reviewed
I am confused how to handle the cases `e'\foo'` and `e'\\foo'`. In both cases, the same string `\foo` is passed to the `EncodeStringWithFlags` function, making it hard to distinguish between them. Note that in Postgres, `e'\foo'` is represented as `\x0Coo`, while `e'\\foo'` is represented as `\foo`. Could you give me any ideas/suggestions about this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-:-NlJm09P3LNuXdlre0XT:b-9z6fcn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/lexbase/encode.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-NjmhXfH-6UK2d1D-9EM:-NlJld7FD51nvBADvgJh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L56)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

The new declaration needs to move above `EncFirstFreeFlagBit`.
</blockquote></details>

Done.
___
*[`pkg/sql/lexbase/encode.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-NjmoPw3Cc6-2mv_ulBn:-NlJlg-N2yFfgda--QfV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L179)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional: I think this code would be well-suited for a case statement, something like:

```
switch nextCh {
  case 'u', 'U': // Hexadecimal unicode.
    if i + 5 < len(in)
       ... 
  case 'x': // Hexadecimal byte.
    ...
  case 'b', 'f', 'n', ... , '0', '1', ...: // Octal byte.
}

```

I think what you have here works, but I had to reason out whether `nextCh` was modified in the hexadecimal unicode path before reaching the hexadecimal byte condition etc. The case statement makes it easier to reason about and removes the need for the `escapedMap`.
</blockquote></details>

Done.
___
*[`pkg/sql/lexbase/encode.go` line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-Njmo0y1Asg8k-9Zk6jl:-NlJlgzr7qGK3P7CEU0U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/215e958e5af421e7ac9ee7562ad800b1c47cde38/pkg/sql/lexbase/encode.go#L204)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

At this point in the code, isn't `ch` always '\\'? Did you mean `nextCh`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-11 02:33 UTC, da-ket reviewed
```
create database t; create table t.t (s string);
--- CREATE DATABASE
--- CREATE TABLE

insert into t.t values (e'\foo');
--- INSERT 0 1

insert into t.t values (e'\\foo');
--- INSERT 0 1

select * from t.t;
---    s
--- --------
---   \foo
---   \foo
(2 rows)

\set display_format sql

--- Without NoDoubleEscape flag
select * from t.t;
--- CREATE TABLE results (
---   s STRING
--- );
---
--- INSERT INTO results VALUES (e'\\foo');
--- INSERT INTO results VALUES (e'\\foo');
--- -- 2 rows

--- With NoDoubleEscape flag
select * from t.t;
--- CREATE TABLE results (
---   s STRING
--- );
---
--- INSERT INTO results VALUES (e'\foo');
--- INSERT INTO results VALUES (e'\foo');
--- -- 2 rows
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-:-NlLdBgx9M1vcfj1jh-G:b-ted9ny)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2023-12-15 09:08 UTC, da-ket reviewed
My apologies, please ignore all previous comments and commits. I didn't notice that double escaped unicode characters are valid. (e.g., `SELECT (e'{\"a\": \"b\\u0099c\"}')::JSONB;` is valid.) So, I think just avoiding double-escaping quotes is fine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-:-Nlg_VgmEJrMFe3hLUrB:b-omccss)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2023-12-15 17:06 UTC, rharding6373 commented
Hi @da-ket, sorry for the delay getting back on this pull request. I will take another look at this today.

2023-12-15 22:44 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you for fixing this! I'm glad it turned out to be much simpler than initially thought.

I'm going to make a simple fix for the linter, then add to the merge queue after all the tests are green. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114707#-:-Nljd29M2GPGv_j8T6sE:b-dcjyok)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-12-16 01:27 UTC, da-ket commented
Thanks for the review! I'm also glad it can be solved with much smaller modifications.

2023-12-17 20:52 UTC, rharding6373 commented
Tests are green. Thanks again!

bors r=rharding6373

2023-12-17 21:33 UTC, merged