sql: ignore trailing whitespace in varchar
cockroachdb/cockroach pull request #115054
Opened 2023-11-24 14:54 UTC by chanYe-EAST

If the extra characters are all whitespaces, they're truncated.

Fixes: #114862

Release note: None

2023-11-24 14:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/115054)
<!-- Reviewable:end -->

2023-11-27 18:35 UTC, rharding6373 requested changes
Thanks for the contribution! Could you also add a logic test like the examples you have in the issue to pkg/sql/logictest/testdata/logic_test/typing? Something like:

```
statement ok
CREATE TEMP TABLE t(v varchar(1));

statement ok
INSERT INTO t (fv) VALUES ('c     ');

query T
SELECT * FROM t
----
c
```

But you can also insert a couple more values.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-NkH1bLZ3y3Am3rg9sAC:b-3dznwu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chanYe-EAST)

___
*[`pkg/sql/sem/tree/datum.go` line 6324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkH-mCvEMoLLI9mxK00:-NkH-mCvEMoLLI9mxK01:bdgjqse) ([raw file](https://github.com/cockroachdb/cockroach/blob/579c6ddb35b7fae6673f6c2393e08033911e48be/pkg/sql/sem/tree/datum.go#L6324)):*
> ```Go
> 			sv = strings.TrimRight(sv, " ")
> 		case oid.T_varchar:
> 			// varchar types truncate extra whitespace.
> ```

I agree that you should be able to use `strings.TrimRight` here. I think the code after the switch statement should handle checking the lengths.


<!-- Sent from Reviewable.io -->

2023-11-28 08:02 UTC, chanYe-EAST commented
Thanks for the review! I added a couple of test cases and changed the code to use`strings.TrimRight` when the length of characters exceeds the `varchar` size.

2023-11-28 17:35 UTC, rharding6373 reviewed
Thanks for the changes! I have a few more comments and test suggestions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-NkLzqXc17QPV1Runp47:bhpya11)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chanYe-EAST)

___
*[`pkg/sql/sem/tree/datum.go` line 6326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLzD2ABpGI0ul9bx6F:-NkLzD2ABpGI0ul9bx6G:b-m34y77) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/sem/tree/datum.go#L6326)):*
> ```Go
> 			// varchar types truncate trailing whitespace when more
> 			// characters than the varchar size are provided.
> 			if utf8.RuneCountInString(sv) > int(typ.Width()) {
> ```

I think this needs a check for `typ.Width() > 0`. See test suggestion below on how to exercise this.
___
*[`pkg/sql/sem/tree/datum.go` line 6327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLseLD7KLFUsU1dZYM:-NkLseLD7KLFUsU1dZYN:b-vp9lm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/sem/tree/datum.go#L6327)):*
> ```Go
> 			// characters than the varchar size are provided.
> 			if utf8.RuneCountInString(sv) > int(typ.Width()) {
> 				sv = strings.TrimRight(sv, " ")
> ```

Hm, after further manual testing against postgres this is still not right, since we should only trim sv to the length of the varchar. For example, the test you added with value ('c     ') should have one space after the c.

I think that it's still ok to to use `TrimRight`, but pad the result string with spaces. This should be safe to do given the conditions above.
___
*[`pkg/sql/logictest/testdata/logic_test/typing` line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLy_gh9hhUWoWdoCeb:-NkLs6SG5Y_KLIDmMo0V:b-uo75by) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/logictest/testdata/logic_test/typing#L334)):*
> ```
> # Issue #115054: ignore trailing whitespace in varchar
> statement ok
> CREATE TABLE t115054 (v varchar(2));
> ```

Could you add another test table with a varchar with no length and similar test cases? This should exercise the case when `typ.Width()` is 0, in which case no spaces should be trimmed.


<!-- Sent from Reviewable.io -->

2023-11-29 09:44 UTC, da-ket commented
Thanks for the comments!

> I think this needs a check for typ.Width() > 0.  See test suggestion below on how to exercise this.

Done.

> Hm, after further manual testing against postgres this is still not right, since we should only trim sv to the length of the varchar. For example, the test you added with value ('c ') should have one space after the c.
>
> I think that it's still ok to to use TrimRight, but pad the result string with spaces. This should be safe to do given the conditions above.

I was also concerned about it behaving differently from postgres, and I agree to pad the result string with spaces.

I guess this code is for handling kind of human error, so instead of considering performance, tried to put short and simple code. But if you say the performance here is important, then it might be better to truncate only the necessary number of whitespaces and eliminate the padding process.

> Could you add another test table with a varchar with no length and similar test cases? This should exercise the case when typ.Width() is 0, in which case no spaces should be trimmed.

Done. And also added one error case that trimmed string length exceeds the size of `varchar`. To check if there's any space at the end of the value, I used a `json_agg`.

2023-11-30 07:02 UTC, da-ket commented
@rharding6373 Hmm, I've given more thought about this issue. Could you check which approach would be better between the two commits (700c1fa, 890415b)?

890415b acts same but cheaper. I believe counting runes through iteration might be expensive (especially when the length of string is long), and calling it twice in every `varchar` type could be inefficient. Additionally, I've eliminated the padding whitespaces, and compare `len(sv)` first for a faster path without counting runes.

2023-12-01 06:08 UTC, da-ket reviewed
Thanks for the review! I didn't realize that I had to use Reviewable, so I wrote everything on GitHub directly. I apologize for that. There are two commits. 700c1fa was made to address review comments, and 890415b was aimed at making 700c1fa cheaper. If `utf8.RuneCountInString` can be considered inexpensive, 890415b is an unnecessary optimization.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-NkYu0KqDfqN-5f-80mZ:bxk6z1k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/sem/tree/datum.go` line 6324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkH-mCvEMoLLI9mxK00:-NkYruRT9vdqPTIdqR4n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/579c6ddb35b7fae6673f6c2393e08033911e48be/pkg/sql/sem/tree/datum.go#L6324)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I agree that you should be able to use `strings.TrimRight` here. I think the code after the switch statement should handle checking the lengths.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/datum.go` line 6326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLzD2ABpGI0ul9bx6F:-NkYs-43AZcHl45m1GDh:b-896fjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/sem/tree/datum.go#L6326)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think this needs a check for `typ.Width() > 0`. See test suggestion below on how to exercise this.
</blockquote></details>

Done 
___
*[`pkg/sql/sem/tree/datum.go` line 6327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLseLD7KLFUsU1dZYM:-NkYs_D3BEZrwL3Mvjs4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/sem/tree/datum.go#L6327)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Hm, after further manual testing against postgres this is still not right, since we should only trim sv to the length of the varchar. For example, the test you added with value ('c     ') should have one space after the c.

I think that it's still ok to to use `TrimRight`, but pad the result string with spaces. This should be safe to do given the conditions above.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/typing` line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLy_gh9hhUWoWdoCeb:-NkYsabU5oaCetdL9Ptp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/logictest/testdata/logic_test/typing#L334)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add another test table with a varchar with no length and similar test cases? This should exercise the case when `typ.Width()` is 0, in which case no spaces should be trimmed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-05 04:20 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I think that both of these approaches are fine, so let's keep and use the second, more performant, commit. Thank you for making all the changes and exploring these options!

Do you mind squashing the commits? Once that's done and the tests are confirmed green, I will add your change to the merge queue (or I will check out your branch and squash them later this week).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-NksAGQ9BW4QmDw3_-fr:b-auu9nk)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`pkg/sql/sem/tree/datum.go` line 6327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NkLseLD7KLFUsU1dZYM:-Nks4Eav4x74ptmLAveN:b-1jylu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413eb3b0e5e5c35b565ecb297580e8a710763a0/pkg/sql/sem/tree/datum.go#L6327)):*
<details><summary><i>Previously, da-ket (daket) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I wasn't familiar with this formatting syntax. Neat!
___
*[`pkg/sql/logictest/testdata/logic_test/typing` line 349 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-NksBMtHBYLDTqx4Yo57:-NksBMtHBYLDTqx4Yo58:b-f8kzrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/890415bff46a4843c5ae231adf2f0c92bff37bf2/pkg/sql/logictest/testdata/logic_test/typing#L349)):*
> ```
> 
> query T nosort
> SELECT json_agg(v ORDER BY v) FROM t115054_1
> ```

The json_agg trick to more easily see whitespace is neat, too.


<!-- Sent from Reviewable.io -->

2023-12-05 04:26 UTC, rharding6373 commented
Note for code owners: The only test failure currently is `TestRefreshThrottling`, which is a known flake.

2023-12-05 13:19 UTC, da-ket reviewed
Thanks for the review! I just squashed the commits into one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-Nku7-zLBehbUvNYqVOD:b8oqj6p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)



<!-- Sent from Reviewable.io -->

2023-12-05 18:14 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115054#-:-NkvB2MM4FQ-BDOJFZdF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-12-05 18:16 UTC, rharding6373 commented
bors r=rharding6373

2023-12-05 21:43 UTC, merged