changefeedccl: fix custom key column when used with CDC queries
cockroachdb/cockroach pull request #115163
Opened 2023-11-28 15:13 UTC by wenyihu6

Previously, CDC custom key column caused incorrect behaviour with CDC queries,
leading to a `retryable error: No column with name <name> in this row`. This was
because we forgot to add columns to `colsByName` map when generating projection
rows for CDC queries. This caused
[`DatumNamed`](https://github.com/cockroachdb/cockroach/blob/8d74d10e77f020dd0f5c98003f7976b63531de18/pkg/ccl/changefeedccl/cdcevent/event.go#L116-L122)
to return a column not found error, This patch addresses the issue by populating
the `colsByName` map during the addition of columns for CDC queries. Note that
the issue with supporting `ALTER CHANGEFEED` with CDC queries remains
unresolved.
Fixes: https://github.com/cockroachdb/cockroach/issues/114196
Release note (bug fix): CDC custom key column now functions with CDC queries
correctly. For example, `CREATE CHANGEFEED WITH key_column=..., unordered AS
SELECT * FROM table` now works correctly instead of hanging.

2023-11-28 15:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/115163)
<!-- Reviewable:end -->

2023-11-28 15:20 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLVCyt30wNJbWv2yzT:-NkLVCyt30wNJbWv2yzU:bz14er7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/changefeed_test.go#L3371)):*
> ```Go
> 		// b="dog".
> 		assertPayloads(t, foo, []string{
> 			`foo: ["dog1"]->{"a": 1, "b": "dog1", "c": "cat1"}`,
> ```

Could you help me understand why changefeed sometimes emit `"after" -> ....` and sometimes does not? For example, https://github.com/cockroachdb/cockroach/blob/ba6423f916dc4006bb590c786cf53ad2b0213417/pkg/ccl/changefeedccl/changefeed_test.go#L3447 doesn't emit `after` but https://github.com/cockroachdb/cockroach/blob/ba6423f916dc4006bb590c786cf53ad2b0213417/pkg/ccl/changefeedccl/changefeed_test.go#L1522C1-L1522C79 does emit `after`. Does it have to do with how CDC queries are used?


<!-- Sent from Reviewable.io -->

2023-11-28 15:48 UTC, miretskiy requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115163)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @wenyihu6)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLWTbP0evSZtspBCf7):*
Not exactly the right wording -- changefeed is not hanging -- it's retrying forever.

And I actually think it shouldn't -- we should ensure that the error returned by DatumNamed
is treated as a fatal error.  You should make this change, and you can do it by changing
```
if !ok {  
  return nil, errors.Errorf("No column with name %s in this row", n)  
}
```
to 
```
 return nil, changefeedbase.WithTerminalError(errors.Errorf("No column with name %s in this row", n) )
```
or... perhaps changing errors.Errorf to `errors.AssertionFailedf` (which is treated as terminal error).
___
*[`pkg/ccl/changefeedccl/cdcevent/projection.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLayQNARgD1IIfLqnX:-NkLayQNARgD1IIfLqnY:b4m57fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/cdcevent/projection.go#L57)):*
> ```Go
> 	p.datums = append(p.datums, rowenc.EncDatum{})
> 	p.allCols = append(p.allCols, ord)
> 	p.colsByName[name] = ord
> ```

Okay -- I don't think this will work correct.  You'll probably discover this as you add more tests cases suggested
below.  Basically, colsByName is a map, and maps need to be initialized via `make(...)`.  You also probably need to copy column names when you construct projection (like we do with primary keys)_...
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLYwwWAYTHbTi9IUwR:-NkLYwwWAYTHbTi9IUwS:b-ydgi9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/changefeed_test.go#L3365)):*
> ```Go
> 		sqlDB.Exec(t, `INSERT INTO foo VALUES (1, 'dog1', 'cat1')`)
> 		foo := feed(t, f,
> 			`CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT * FROM foo WHERE b='dog1'`)
> ```

This test needs to be expanded.  You can either use table driven tests where you pass in various configuraiton options to this test... Or... You can create bunch of subtests withing.
You can take this line + everything up to assert below, and keep copy pasting different test cases.
For example:
```
   t.Run("star", func(t *testing.T) {
        foo := feed(t, f,
			`CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT * FROM'`)
         ....
   })
   t.Run("start_with_where", func(t *testing.T) {
       foo := feed(t, f,
			`CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT * FROM foo WHERE b='dog1'`)
   })
```

What I would like is to see tests that
* Select explicit columns ("SELECT a, c...")
* Try to use *computed* column as a key_column; for example `CREATE CHANGEFEED WITH key_column='double_b' SELECT a, concat(b, b) AS double_b, c FROM ...` (quite honestly, I'm not sure if it works -- and if not, we probably need to make it work).
* Figure out if you can use special, hidden system columns as a key_column -- for example `crdb_internal_mvcc_timestamp` column.  (You might have to explicitly select this column for it to have a chance of working).
* Figure out if you can use the *previous* state of the row as a key_column: `CREATE CHANGEFEED WITH key_column='old_dog' SELECT a, c, cdc_prev.b AS old_dog FROM ...`
* Take a look at various existing tests cdceval package for inspiration.

A lot of the above suggestions (like the use of computed columns) may not work.  If that's the case, you need
to file an issue for that and it's okay to focus this PR on the simple case.  And... You can still keep the above tests -- even if they don't work -- because you can add `t.SkipWithIssue(....)` call at the start of the test to indicate that we are skipping something that's known not to work.

(note to self: we really need to get @andyyang890 help to perhaps turn these types of tests into datadriven/ logictests).
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLVCyt30wNJbWv2yzT:-NkLXo5AAJTNZ7IsIeRL:b96srjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/changefeed_test.go#L3371)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Could you help me understand why changefeed sometimes emit `"after" -> ....` and sometimes does not? For example, https://github.com/cockroachdb/cockroach/blob/ba6423f916dc4006bb590c786cf53ad2b0213417/pkg/ccl/changefeedccl/changefeed_test.go#L3447 doesn't emit `after` but https://github.com/cockroachdb/cockroach/blob/ba6423f916dc4006bb590c786cf53ad2b0213417/pkg/ccl/changefeedccl/changefeed_test.go#L1522C1-L1522C79 does emit `after`. Does it have to do with how CDC queries are used?
</blockquote></details>

Yeah; this is the envelope funcitonality in changefeed.  
https://www.cockroachlabs.com/docs/v23.1/changefeed-messages
The envelope "wrapps" the message with some structure.  The default for regular changefeed is
to use "wrapped" envelope; while the default for CDC query is to use "bare" envelope (basically,
we emit whatever you SELECT).  However, you can use wrapped envelope if you want with cdc query
by adding "WITH envelope='wrapped'" option to your changefeed statement.


<!-- Sent from Reviewable.io -->

2023-11-29 15:48 UTC, wenyihu6 commented
things that don't work with custom key columns so far:
1. using a key column that user created in CDC queries
```
CREATE CHANGEFEED WITH key_column='double_b', unordered AS SELECT concat(b, c) AS double_b FROM foo
```
2. selecting on a virtual column does not work
```
CREATE TABLE foo (a INT PRIMARY KEY, b STRING, c STRING, d STRING AS (concat(b, c)) VIRTUAL)
CREATE CHANGEFEED WITH key_column='d', unordered AS SELECT d FROM foo 
```
4. selecting on a hidden column works
```
CREATE TABLE foo (a INT PRIMARY KEY, b STRING NOT VISIBLE)
CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT b FROM foo
```
5. selecting on cdc_prev or cdc_is_delete doesn't seem to work, and cdc_is_delete is not recognized as a function either when used in CDC queries 
```
```
6. selecting on

2023-11-29 17:16 UTC, wenyihu6 commented
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLWTbP0evSZtspBCf7):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Not exactly the right wording -- changefeed is not hanging -- it's retrying forever.

And I actually think it shouldn't -- we should ensure that the error returned by DatumNamed
is treated as a fatal error.  You should make this change, and you can do it by changing
```
if !ok {  
  return nil, errors.Errorf("No column with name %s in this row", n)  
}
```
to 
```
 return nil, changefeedbase.WithTerminalError(errors.Errorf("No column with name %s in this row", n) )
```
or... perhaps changing errors.Errorf to `errors.AssertionFailedf` (which is treated as terminal error).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-29 17:19 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLYwwWAYTHbTi9IUwR:-NkR4Gy1DI8XffNpo8Cu:besd950) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/changefeed_test.go#L3365)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This test needs to be expanded.  You can either use table driven tests where you pass in various configuraiton options to this test... Or... You can create bunch of subtests withing.
You can take this line + everything up to assert below, and keep copy pasting different test cases.
For example:
```
   t.Run("star", func(t *testing.T) {
        foo := feed(t, f,
			`CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT * FROM'`)
         ....
   })
   t.Run("start_with_where", func(t *testing.T) {
       foo := feed(t, f,
			`CREATE CHANGEFEED WITH key_column='b', unordered AS SELECT * FROM foo WHERE b='dog1'`)
   })
```

What I would like is to see tests that
* Select explicit columns ("SELECT a, c...")
* Try to use *computed* column as a key_column; for example `CREATE CHANGEFEED WITH key_column='double_b' SELECT a, concat(b, b) AS double_b, c FROM ...` (quite honestly, I'm not sure if it works -- and if not, we probably need to make it work).
* Figure out if you can use special, hidden system columns as a key_column -- for example `crdb_internal_mvcc_timestamp` column.  (You might have to explicitly select this column for it to have a chance of working).
* Figure out if you can use the *previous* state of the row as a key_column: `CREATE CHANGEFEED WITH key_column='old_dog' SELECT a, c, cdc_prev.b AS old_dog FROM ...`
* Take a look at various existing tests cdceval package for inspiration.

A lot of the above suggestions (like the use of computed columns) may not work.  If that's the case, you need
to file an issue for that and it's okay to focus this PR on the simple case.  And... You can still keep the above tests -- even if they don't work -- because you can add `t.SkipWithIssue(....)` call at the start of the test to indicate that we are skipping something that's known not to work.

(note to self: we really need to get @andyyang890 help to perhaps turn these types of tests into datadriven/ logictests).
</blockquote></details>

Added more tests and tracked some usage that doesn't work [here](https://github.com/cockroachdb/cockroach/issues/114196). Confirmed that SELECT 'crdb_internal_mvcc_timestamp` works but can't add as a unit test easily since the value is always changing. 


```
// Different mvcc time every time expected  
\`select\_mvcc\_timestamp\`: {  
  createTableStmt:      \`CREATE TABLE foo (a INT PRIMARY KEY, b STRING)\`,  
  createChangeFeedStmt: \`CREATE CHANGEFEED WITH key\_column='crdb\_internal\_mvcc\_timestamp', unordered AS SELECT crdb\_internal\_mvcc\_timestamp FROM foo WHERE crdb\_internal\_mvcc\_timestamp > 0\`,  
  stmts:                \[\]string{\`INSERT INTO foo VALUES (0, 'dog')\`, \`INSERT INTO foo VALUES (1, 'dog1')\`},  
  payloadsAfterStmts:   \[\]string{\`foo: \[1701232020914949000.0000000000\]->{"crdb\_internal\_mvcc\_timestamp": 1701232020914949000.0000000000}\`},  
},
```


<!-- Sent from Reviewable.io -->

2023-11-29 17:19 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkLVCyt30wNJbWv2yzT:-NkR4sEuAz0g-IVLTaHZ:b-a7jug4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec4f50d80f5aaeac4d79cedf620f299ef0115bf/pkg/ccl/changefeedccl/changefeed_test.go#L3371)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Yeah; this is the envelope funcitonality in changefeed.  
https://www.cockroachlabs.com/docs/v23.1/changefeed-messages
The envelope "wrapps" the message with some structure.  The default for regular changefeed is
to use "wrapped" envelope; while the default for CDC query is to use "bare" envelope (basically,
we emit whatever you SELECT).  However, you can use wrapped envelope if you want with cdc query
by adding "WITH envelope='wrapped'" option to your changefeed statement.
</blockquote></details>

I see. Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2023-11-29 17:45 UTC, miretskiy approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115163)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3457 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkRAWKU5MzQO8hi6K9J:-NkRAWKU5MzQO8hi6K9K:bi49vsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0437796bda0689c8adf4089e7ffedbc1efa69a75/pkg/ccl/changefeedccl/changefeed_test.go#L3457)):*
> ```Go
> 		t.Run(name, func(t *testing.T) {
> 			if test.skipWithIssue != "" {
> 				t.Skip(test.skipWithIssue)
> ```

I think we should be using skip.WithIssue(....) call instead of direct t.Skip.
Or... Maybe, just "print" a message to say that the test is being ignored
(if you want to avoid using skip.WithIssue because it's not necessarily a test
issue, but merely a gap in the functionality).


<!-- Sent from Reviewable.io -->

2023-11-29 17:54 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3457 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkRAWKU5MzQO8hi6K9J:-NkRChL41rI9DEx4tCto:b-f564gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0437796bda0689c8adf4089e7ffedbc1efa69a75/pkg/ccl/changefeedccl/changefeed_test.go#L3457)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we should be using skip.WithIssue(....) call instead of direct t.Skip.
Or... Maybe, just "print" a message to say that the test is being ignored
(if you want to avoid using skip.WithIssue because it's not necessarily a test
issue, but merely a gap in the functionality).
</blockquote></details>

Do you want me to create a separate issue here or just leave the original issue unclosed?


<!-- Sent from Reviewable.io -->

2023-11-29 17:56 UTC, wenyihu6 commented
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 3457 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/115163#-NkRAWKU5MzQO8hi6K9J:-NkRD2WT7Vv8MVCBZJ1u:bvyvcai) ([raw file](https://github.com/cockroachdb/cockroach/blob/0437796bda0689c8adf4089e7ffedbc1efa69a75/pkg/ccl/changefeedccl/changefeed_test.go#L3457)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Do you want me to create a separate issue here or just leave the original issue unclosed?
</blockquote></details>

I'm not sure exactly how to print a message and ignore the test without skip.WithIssue? Do you mean something simple like creating a boolean and skipping inside the for loop?


<!-- Sent from Reviewable.io -->

2023-11-29 21:08 UTC, wenyihu6 commented
This last push fixed a linter issue to use skip.WithIssue instead of t.Skip().

2023-11-29 21:08 UTC, wenyihu6 commented
TFTR!

bors r=miretskiy

2023-11-29 21:55 UTC, merged

2023-12-21 20:37 UTC, wenyihu6 commented
blathers backport 23.1 23.2

2024-01-09 17:02 UTC, celiala commented
blathers backport 23.1.14-rc