sql: only allow altering a column type when an assignment cast is allowed
cockroachdb/cockroach pull request #115442
Opened 2023-12-01 19:08 UTC by andrew-delph

Fixes: #82416

Release note (sql change): Reject changing column types unless an explicitly cast is provided where cannot automatically cast. This replicates logic in Postgres. Prior to this change, casts such as BOOL to INT were possible without explicitly casting.

2023-12-01 19:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/115442)
<!-- Reviewable:end -->

2023-12-01 20:58 UTC, rafiss requested changes
thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115442#-:-NkbAGl-9I2SjoamDniZ:b3akoa5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrew-delph and @mgartner)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115442#-Nkb9Fdu2GpnlH2QTbeG):*
nit: "postures" -> "postgres"
___
*[`pkg/sql/alter_column_type.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115442#-Nkb9KKz3XIxMOZ6d5KV:-Nkb9KKz3XIxMOZ6d5KW:b79r88t) ([raw file](https://github.com/cockroachdb/cockroach/blob/649572566503cb90c0f508ce0a18cf08e650580a/pkg/sql/alter_column_type.go#L342)):*
> ```Go
> 		// Validate that the column can be automatically cast to toType without explicit casting.
> 		if validCast := cast.ValidCast(col.GetType(), toType, cast.ContextAssignment); !validCast {
> 			return pgerror.WithCandidateCode(
> ```

nit: use this constructor:
```
return errors.WithHintf(  
  pgerror.Newf(  
   pgcode.DatatypeMismatch,  
   "column %q cannot be cast automatically to type %s",  
   col.GetName(),  
   toType.SQLString(),  
  ),  "You might need to specify \"USING %s\".", s,  
)
```


<!-- Sent from Reviewable.io -->

2023-12-26 16:59 UTC, yuzefovich commented
Friendly ping @mgartner

2024-01-02 16:36 UTC, mgartner approved these changes
Thanks for the contribution! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115442#-:-NnA1DRCDHxTRrYpUt6M:b755kst)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrew-delph and @rafiss)



<!-- Sent from Reviewable.io -->

2024-01-02 18:24 UTC, rafiss approved these changes
lgtm!

bors r+

2024-01-02 20:10 UTC, merged