engineccl: Reimplement FileCipherStreamV2
cockroachdb/cockroach pull request #115549
Opened 2023-12-04 18:03 UTC by bdarnell

First commit is from #115365. #115454 is related and makes v1 look a little better in the benchmarks. 

The new implementation, fileCipherStreamV2, is currently only hooked up
in tests and benchmarks. It's not used in production until we decide on
a feature flagging strategy.

The major change is to defer more to the standard library, and
specifically to pass larger batches to the stdlib at once. Previously we
made a separate call to the crypto library for every 16-byte block; now
we pass the entire buffer at once. The downside is random access is more
expensive. The previous implementation was basically constant-time,
while the new one performs multiple heap allocations for every "seek".

To summarize the performance results below, v2 is significantly slower
than v1 for tiny (16 byte) non-sequential operations. It is about the
same performance for small sequential operations, and substantially
faster for large sequential operations (about twice as fast as the
original version).

The FIPS version is now even faster (for large sequential writes) than
non-FIPS. This is because Go's implementation of CTR mode has not been
as extensively optimized as openssl's. There are open PRs that may
improve this in the future, such as golang/go#53503

```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=false/block=16/-24                 7521            137392 ns/op         238.50 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=false/block=256/-24               15793             75349 ns/op         434.88 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=false/block=1024/-24              16778             71159 ns/op         460.49 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=false/block=16384/-24             17083             69697 ns/op         470.15 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=true/block=16/-24                  7797            137415 ns/op         238.46 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=true/block=256/-24                15794             75635 ns/op         433.24 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=true/block=1024/-24               16785             71195 ns/op         460.26 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=128/seq=true/block=16384/-24              17169             69813 ns/op         469.37 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=false/block=16/-24                 7510            142334 ns/op         230.22 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=false/block=256/-24               14797             81525 ns/op         401.94 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=false/block=1024/-24              15715             76005 ns/op         431.13 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=false/block=16384/-24             15985             74794 ns/op         438.11 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=true/block=16/-24                  7558            142334 ns/op         230.22 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=true/block=256/-24                14826             80456 ns/op         407.28 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=true/block=1024/-24               15757             76231 ns/op         429.85 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=192/seq=true/block=16384/-24              16063             74763 ns/op         438.29 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=false/block=16/-24                 7304            146606 ns/op         223.51 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=false/block=256/-24               13947             85653 ns/op         382.57 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=false/block=1024/-24              14589             81277 ns/op         403.16 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=false/block=16384/-24             14989             80079 ns/op         409.19 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=true/block=16/-24                  7274            145928 ns/op         224.55 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=true/block=256/-24                13935             85680 ns/op         382.45 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=true/block=1024/-24               14690             81366 ns/op         402.73 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=true/block=16384/-24              15002             80120 ns/op         408.99 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=false/block=16/-24                  615           1896677 ns/op          17.28 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=false/block=256/-24                9006            119509 ns/op         274.19 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=false/block=1024/-24              23329             51281 ns/op         638.99 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=false/block=16384/-24             29162             40910 ns/op         800.97 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=true/block=16/-24                  8750            132576 ns/op         247.16 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=true/block=256/-24                26404             45361 ns/op         722.39 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=true/block=1024/-24               28626             41808 ns/op         783.78 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=128/seq=true/block=16384/-24              29336             40935 ns/op         800.48 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=false/block=16/-24                  574           2042367 ns/op          16.04 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=false/block=256/-24                8706            129528 ns/op         252.98 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=false/block=1024/-24              21183             56446 ns/op         580.52 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=false/block=16384/-24             26109             45655 ns/op         717.73 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=true/block=16/-24                  8504            137355 ns/op         238.56 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=true/block=256/-24                23960             50296 ns/op         651.50 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=true/block=1024/-24               25696             46679 ns/op         701.99 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=192/seq=true/block=16384/-24              26198             45587 ns/op         718.80 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=false/block=16/-24                  531           2206987 ns/op          14.85 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=false/block=256/-24                7694            139498 ns/op         234.90 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=false/block=1024/-24              19524             61046 ns/op         536.77 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=false/block=16384/-24             23745             50562 ns/op         648.07 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=true/block=16/-24                  8245            148016 ns/op         221.38 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=true/block=256/-24                21739             55280 ns/op         592.76 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=true/block=1024/-24               23212             51531 ns/op         635.89 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=2 [...]

2023-12-04 18:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/115549)
<!-- Reviewable:end -->

2023-12-04 18:28 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Go's large block throughput is disappointing, multi GB/s is typical when using AES-NI

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-:-Nkq4X39B0Ah9KNXxGu4:b-8wjcxt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @bdarnell, and @rsevinsky-cr)

___
*[`pkg/ccl/storageccl/engineccl/ctr_stream.go` line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-Nkq3PNY5gF8f6SiBcws:-Nkq3PNY5gF8f6SiBcwt:b9d2cr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1a20dde69acf2774a4413ead1ff0e7974b4b48/pkg/ccl/storageccl/engineccl/ctr_stream.go#L233)):*
> ```Go
> func (s *fileCipherStreamV2) Encrypt(fileOffset int64, data []byte) {
> 	var ctr cipher.Stream
> 	func() {
> ```

It would likely be beneficial to have a simple fast path that does everything under the lock when `len(data)` is small, e.g.

```go
if s.mu.fileOffset == fileOffset {
  if len(data) < 128 {
    s.mu.ctr.XORKeyStream(data, data)
    s.mu.ctr.fileOffset += len(data)
    return
  }
}
``` 


<!-- Sent from Reviewable.io -->

2023-12-04 19:28 UTC, sumeerbhola requested changes
It is hard to read these performance comparisons without benchstat-style comparison. So I pulled the ones for `key=256` and `block=16384`, since 16384 is comparable to our ssblock size (post compression).

without fips:
```
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=false/block=16384/-24             14989             80079 ns/op         409.19 MB/s
BenchmarkFileCipherStream/fips=false/impl=v1/key=256/seq=true/block=16384/-24              15002             80120 ns/op         408.99 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=false/block=16384/-24             23745             50562 ns/op         648.07 MB/s
BenchmarkFileCipherStream/fips=false/impl=v2/key=256/seq=true/block=16384/-24              23805             50438 ns/op         649.66 MB/s
```

with fips:
```
BenchmarkFileCipherStream/fips=true/impl=v1/key=256/seq=false/block=16384/-24               2446            483249 ns/op          67.81 MB/s
BenchmarkFileCipherStream/fips=true/impl=v1/key=256/seq=true/block=16384/-24                2443            480180 ns/op          68.24 MB/s
BenchmarkFileCipherStream/fips=true/impl=v2/key=256/seq=false/block=16384/-24             101763             11161 ns/op        2936.06 MB/s
BenchmarkFileCipherStream/fips=true/impl=v2/key=256/seq=true/block=16384/-24              104826             11190 ns/op        2928.36 MB/s
```

The seq={false,true} does not matter in this case.

The benchmark is aligning the blocks we are passing to be encrypted with the AES block size of 16 bytes, which is not going to be the common case. I would prefer if the benchmark deliberately misaligned these. 

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-:-NkqEojF5JL_WTbw9uby:b-elocf4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @bdarnell, and @rsevinsky-cr)

___
*[`pkg/ccl/storageccl/engineccl/ctr_stream.go` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-Nkq7Cg2BhgwaMHXmXiZ:-Nkq7Cg2BhgwaMHXmXi_:b-romg2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1a20dde69acf2774a4413ead1ff0e7974b4b48/pkg/ccl/storageccl/engineccl/ctr_stream.go#L37)):*
> ```Go
> 	// DEPRECATED: The V1 implementation had a distinction between a 12-byte
> 	// "nonce" and a 4-byte "counter". This was incorrect and we now treat the
> 	// IV/nonce as a single 128-bit value.
> ```

Can you elaborate on what was incorrect?

Concatenating the nonce and counter is mentioned as a secure alternative in https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_(CTR) "In case of a non-random nonce (such as a packet counter), the nonce and counter should be concatenated (e.g., storing the nonce in the upper 64 bits and the counter in the lower 64 bits of a 128-bit counter block)."

We are picking the nonce by simply calling `rand.Read` so it is not a cryptographically secure random value.

That link talks briefly about a chosen plaintext attack, which addition suffers from, but it is clearly not detailed enough to guide our choice. I didn't bother finding and reading more detailed articles, but someone should, before we change things here.
___
*[`pkg/ccl/storageccl/engineccl/ctr_stream.go` line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-NkqAutD4tJsSTbjn6A5:-NkqAutEB8Y7OiVOyooF:bq36mwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1a20dde69acf2774a4413ead1ff0e7974b4b48/pkg/ccl/storageccl/engineccl/ctr_stream.go#L262)):*
> ```Go
> 		}
> 	}
> 	ctr.XORKeyStream(data, data)
> ```

Glancing at the code in `cipher.ctr` it seems to be doing something very similar to what happens in `fileCipherStream` and `cTRBlockCipherStream` in that it is working on 16 byte blocks. So I am wondering where the performance improvement is coming from in the non fips case. Is it the overhead we pay in `cTRBlockCipherStream.transform` each time for setting up the IV (`ctr.refill` does a simpler counter increment), or is `subtle.XORBytes` more efficient than the xor in `cTRBlockCipherStream.transform`?
Could you grab a cpu profile of the existing code using the benchmark you recently added?


<!-- Sent from Reviewable.io -->

2023-12-04 20:05 UTC, bdarnell commented
> Go's large block throughput is disappointing, multi GB/s is typical when using AES-NI

Yep. There's a third-party library (https://github.com/starius/aesctrat) that gets 5+GB/s, and it may be merged into the go standard library in https://github.com/golang/go/pull/53503. 

> It would likely be beneficial to have a simple fast path that does everything under the lock when len(data) is small

Perhaps. But it's difficult to evaluate that since there's no concurrency in a simple benchmark. Since we care more about large operations is it worth exploring a small-op fast path?

> The seq={false,true} does not matter in this case.

> The benchmark is aligning the blocks we are passing to be encrypted with the AES block size of 16 bytes, which is not going to be the common case. I would prefer if the benchmark deliberately misaligned these.

With 16KB blocks, the effect of sequential vs random reads is negligible. The same applies to alignment - it would make a big difference for 16 byte reads, but it's not significant at larger block sizes. I could run it if you want but as you note it's already overwhelming.

> Concatenating the nonce and counter is mentioned as a secure alternative in https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Counter_(CTR) "In case of a non-random nonce (such as a packet counter), the nonce and counter should be concatenated (e.g., storing the nonce in the upper 64 bits and the counter in the lower 64 bits of a 128-bit counter block)."

64-bit nonce and 64-bit counter is fine, because you're not going to overflow a 64-bit counter. We were using a 96-bit nonce and 32-bit counter, though, which does conceivably wrap around (we don't use single files big enough for it to matter, but it's within reach). When it does, the confidentiality of the data is severely weakened.

CTR mode is under-specified (at least I can't find a formal spec that says how exactly to do it), but for our purposes it's important that we match the way that the go standard library and openssl do it, which in both cases is a 128-bit value that is both "nonce" and "counter". 

> We are picking the nonce by simply calling rand.Read so it is not a cryptographically secure random value.

Hmm? crypto/rand.Read is cryptographically secure.

> Glancing at the code in cipher.ctr it seems to be doing something very similar to what happens in fileCipherStream and cTRBlockCipherStream in that it is working on 16 byte blocks. So I am wondering where the performance improvement is coming from in the non fips case. Is it the overhead we pay in cTRBlockCipherStream.transform each time for setting up the IV (ctr.refill does a simpler counter increment), or is subtle.XORBytes more efficient than the xor in cTRBlockCipherStream.transform?

Somewhat surprisingly, it seems to mainly be about the XOR. subtle.XORBytes is indeed more efficient (I have a separate PR for it in https://github.com/cockroachdb/cockroach/pull/115454). The additional improvement relative to that PR seems to come from doing all the XORBytes at once instead of alternating 16 bytes of AES and 16 bytes of XOR.

2023-12-04 20:43 UTC, sumeerbhola reviewed
> Hmm? crypto/rand.Read is cryptographically secure.

ah yes, I misread the import.

> The same applies to alignment - it would make a big difference for 16 byte reads, but it's not significant at larger block sizes. I could run it if you want but as you note it's already overwhelming.

I would prefer if we did all the runs such that they are not aligned, since it's simpler/better than staring at the implementation and convincing ourselves when the alignment is not performance impacting. And it will catch unintended regressions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-:-NkqYjJb6B87pM2HPk3G:bgumigi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @bdarnell, and @rsevinsky-cr)



<!-- Sent from Reviewable.io -->

2023-12-05 15:10 UTC, bdarnell commented
> There's a third-party library (https://github.com/starius/aesctrat) that gets 5+GB/s, and it may be merged into the go standard library in golang/go#53503.

While we're doing this, should we go all the way and adopt one of these optimized implementations? We could use the third-party library (which would be more code changes that would have to be put behind a build tag so it's not used in FIPS builds) or add the upstream Go PR to our patched toolchains (we're already applying one custom patch for all our builds). The downside is that we'd be taking security-critical code from a new source that isn't yet vetted by e.g. the Go or OpenSSL maintainers.

2023-12-06 17:59 UTC, rsevinsky-cr reviewed
From a security perspective, I would recommend GCM mode, as opposed to CTR mode. AFAIK, CTR mode isn't authenticated, whereas GCM is.

2023-12-06 20:50 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115549#-:-Nl-tMBbAfqtRiALMvhi:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi and @bdarnell)



<!-- Sent from Reviewable.io -->

2023-12-06 20:50 UTC, bdarnell commented
> AFAIK, CTR mode isn't authenticated, whereas GCM is.

Correct. We chose CTR mode because we didn't believe that GCM could support the interface we required (essentially a filesystem, with random access reads, etc). I'd be happy to be wrong on this point, though. The AEAD interface is more complicated than a stream cipher and I'm not familiar with how it's used in practice (I've only seen it as wrapped in a higher-level protocol like TLS). 

I think it would be more feasible to use GCM if we integrated it into pebble at a higher level (pebble isn't really random access, it's a block at a time) but that would be a pretty big move (and while pebble is the bulk of our data storage, it's not 100% and we'd still have other places where we aren't able to take advantage of pebble's sstable block structure).

I'd be happy to talk more about what we might be able to do here that would be better than CTR mode (and how high a priority we should put on moving to authenticated encryption).

2024-01-29 10:05 UTC, merged