dev: make `gen testlogic` also invoke `gen schemachanger`
cockroachdb/cockroach pull request #115658
Opened 2023-12-05 23:09 UTC by yuzefovich

This commit makes it so that `dev gen testlogic` is executed, under the hood it also calls `dev gen schemachanger`. This is needed in case some of the logic test files are added / renamed / removed to update the schemachanger comparator tests.

Epic: None

Release note: None

2023-12-05 23:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/115658)
<!-- Reviewable:end -->

2023-12-05 23:51 UTC, rickystewart commented
> This commit makes it so that dev gen testlogic is executed, under the hood it also calls dev gen schemachanger. This is needed in case some of the logic test files are added / renamed / removed to update the schemachanger comparator tests.

Hmm. Can you add a few more words about why this is correct/useful to do? Is it very likely that you will encounter this case where the schemachanger comparator tests need to be updated due to logic test updates? While it may be true that you need to do this re-generation depending on what you updated, you may have to generate *other code* as well. However we don't expand `gen testlogic` to subsume every other code generation target: it does exactly what it says it does, which is generating the logic test code. Not to say this PR shouldn't be merged, but I'm trying to understand what problem is being fixed here.

One aspect of this is that since `dev testlogic` invokes `dev gen testlogic`, you will be slowing down every invocation of `dev gen testlogic` to generate the schemachanger stuff that I don't actually think they need. I don't think it's actually necessary for those people.

2023-12-05 23:52 UTC, rickystewart commented
Another way of asking the question is, why is it important that everyone eat the cost of doing `gen schemachanger` whenver they `gen testlogic`, when you yourself could just type `dev gen testlogic schemachanger`. What problem does it fix for them?

2023-12-05 23:57 UTC, yuzefovich commented
Recently I needed to add / move / rename logic test files a couple of times, and I would do `./dev gen testlogic`. But then the CI would complain as [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12993845&buildTypeId=Cockroach_BazelEssentialCi) due to me forgetting to update schemachanger comparator tests. My understanding is that those tests are always generated based on the logic test files (they ignore `ccl` logictests though it seems), so it seems like a reasonable thing to always update the schemachanger whenever `gen testlogic` is invoked - chances are the comparator tests need an update. (One example where it's not needed is adding / removing logic test configs from the existing logic test files, then it'd be redundant work. Perhaps there are others.)

> One aspect of this is that since `dev testlogic` invokes `dev gen testlogic`, you will be slowing down every invocation of `dev testlogic` to generate the schemachanger stuff that I don't those people actually need.

I'm surprised by this - what's the rationale of it? Do we need this bit?

In my mind, generating logic tests needs to be done by the engineers whenever they modify logic test files, and then we have a linter to catch mistakes. Whenever we're actually executing the logic tests, I'd just assume that all unit tests are already properly generated.

2023-12-06 00:27 UTC, rickystewart approved these changes
WFM

2023-12-06 00:27 UTC, rickystewart commented on pkg/cmd/dev/generate.go
> +        dev generate testlogic     # logictest generated code (subset of 'dev generate bazel', includes 'dev generate schemachanger')
Do me a favor and remove the "subset of `dev generate bazel`" thing as it's no longer accurate.

2023-12-06 00:29 UTC, rickystewart requested changes
Oh, wait, you can't merge this. The unit tests are broken.

2023-12-06 00:31 UTC, rickystewart commented
> I'm surprised by this - what's the rationale of it? Do we need this bit?

> In my mind, generating logic tests needs to be done by the engineers whenever they modify logic test files, and then we have a linter to catch mistakes. Whenever we're actually executing the logic tests, I'd just assume that all unit tests are already properly generated.

It's a tradeoff, but this is the way that we went when the big refactor of logic tests to use code generation. The way you suggested makes sense. Ultimately I think the reason this was preferred is that code generation used to be unnecessary and the change that was made caused it to become necessary, so auto-generating means that no one can ever be mistakenly under the impression that their changes are applied when they are not. This was especially important in the transition period as people were getting used to the new way of doing things.

However you can turn off the generation with `--no-gen`.

2023-12-06 00:36 UTC, yuzefovich reviewed
> Oh, wait, you can't merge this. The unit tests are broken.

Should be fixed now.

Thanks for the context on auto generation. Do you think it's time to disable the generation by default since the transition went smoothly and we can now optimize the build times in tests forgetting how things were before? Would we save much? Probably a second or two on each `dev testlogic` invocation?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115658#-:-NkwXht68I7p5U85uxk1:b-78unme)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart and @Xiang-Gu)

___
*[`pkg/cmd/dev/generate.go` line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115658#gh-1416465986:-NkwXH5n2jzc5Pe1xfeA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b562e2dd267e5c1bf535f57adf251a47aaafa64/pkg/cmd/dev/generate.go#L50)):*
<details><summary><i>Previously, rickystewart (Ricky Stewart) wrote…</i></summary><blockquote>

Do me a favor and remove the "subset of `dev generate bazel`" thing as it's no longer accurate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-06 00:40 UTC, rickystewart approved these changes

2023-12-06 02:00 UTC, yuzefovich commented
TFTR!

bors r+

2023-12-06 02:08 UTC, yuzefovich commented
bors r+

2023-12-06 03:05 UTC, yuzefovich commented
Seems like a flake again.

bors r+

2023-12-06 03:51 UTC, merged