changefeedccl: support attributes in pubsub sink
cockroachdb/cockroach pull request #116089
Opened 2023-12-11 20:01 UTC by jayshrivastava

This change adds support for including the table name along with each row/batch sent by the v2 pubsub sink (enabled by default). The table name is passed inside pubsub attributes. Attributes are stored in a `map[string]string` and passed emitted alongside each with each message/batch.

To enable this feature, the environment variable `COCKROACH_ENABLE_TABLE_NAME_PUSBUB_ATTRIBUTE` needs to be set to true.

The key for the table name in the attribute map will be `TABLE_NAME`. Because this change needs to be backported, it is as small as possible to minimize risk. This feature can be expanded upon later to be more generic (ex. use changefeed options, cdc queries to specify custom attributes, metadata for different sinks etc).

Release note: None
Closes: https://github.com/cockroachdb/cockroach/issues/115426

2023-12-11 20:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/116089)
<!-- Reviewable:end -->

2023-12-13 20:34 UTC, miretskiy requested changes
> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/sink.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZGbp-0KVkKaJ0NrG-:-NlZGbp02AEk5x6rk8xy:b-kdc30u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink.go#L88)):*
> ```Go
> 	// error may be returned if a previously enqueued message has failed.
> 	EmitRow(ctx context.Context, topic TopicDescriptor, key, value []byte,
> 		updated, mvcc hlc.Timestamp, alloc kvevent.Alloc, tableName string) error
> ```

I'm curious: can't we use or extend TopicDescriptor already passed to this function to carry tableName?
Like: doesn't it have StatementTimeName?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZs3567MMUfQv1D4F6:-NlZs3567MMUfQv1D4F7:bktxv63) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L251)):*
> ```Go
> 
> 	psb.messages = append(psb.messages, &pb.PubsubMessage{
> 		Data: content, Attributes: map[string]string{"TABLE_NAME": psb.tableName}})
> ```

Do we unconditionally include these attributes?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZs9iVDb4Dme9GIW0B:-NlZs9iVDb4Dme9GIW0C:bf6zvbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L251)):*
> ```Go
> 
> 	psb.messages = append(psb.messages, &pb.PubsubMessage{
> 		Data: content, Attributes: map[string]string{"TABLE_NAME": psb.tableName}})
> ```

Looking at this code -- makes me sad -- we allocate &pb.PubsubMessage structures all the time.
So sad... Especially since the pb.PubsubMessage has Reset method... But that's for another cleanup CL...

We would probably need to have "attributes cache" to avoid allocating these maps.  Okay to leave a TODO.


<!-- Sent from Reviewable.io -->

2023-12-15 18:34 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/sink.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZGbp-0KVkKaJ0NrG-:-NliiZrv22zW5XZVfvdl:b78leaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink.go#L88)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm curious: can't we use or extend TopicDescriptor already passed to this function to carry tableName?
Like: doesn't it have StatementTimeName?
</blockquote></details>

I thought about it (actually I think I coded it using this method and abandoned it). The topic desc gets instantiated from the job record and we don't have the table name in the job record. So, we either add the table name or we have to look it up. It's much easier to look up the table name from the row. Also, I like having a separate parameter for row related metadata and keep the topic data in its own param. In a follow up PR, we will change it from just tableName string to something generic like struct{}.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZs3567MMUfQv1D4F6:-NlijScp2X9mqoaDntqd:bjrgq3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L251)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we unconditionally include these attributes?
</blockquote></details>

Yeah we shouldn't. I added a check and test case for nil attributes.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZs9iVDb4Dme9GIW0B:-NlijWHvEVFoG_x_SmrZ:b-28td6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L251)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Looking at this code -- makes me sad -- we allocate &pb.PubsubMessage structures all the time.
So sad... Especially since the pb.PubsubMessage has Reset method... But that's for another cleanup CL...

We would probably need to have "attributes cache" to avoid allocating these maps.  Okay to leave a TODO.
</blockquote></details>

I updated the code so we instantiate it once per batch buffer and save it. This way, each new message doesn't alloc a new map.


<!-- Sent from Reviewable.io -->

2023-12-19 17:47 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/sink.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZGbp-0KVkKaJ0NrG-:-Nm29YUm5oetdYEOHG1d:b-k3rn7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink.go#L88)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I thought about it (actually I think I coded it using this method and abandoned it). The topic desc gets instantiated from the job record and we don't have the table name in the job record. So, we either add the table name or we have to look it up. It's much easier to look up the table name from the row. Also, I like having a separate parameter for row related metadata and keep the topic data in its own param. In a follow up PR, we will change it from just tableName string to something generic like struct{}.
</blockquote></details>

I agree that it's easier to get the table from the row... What I don't understand is why can't we have topic descriptor always carry table name.
Consider the place where we obtain table descriptor (encodeAndEmit):
```
topic, err := c.topicForEvent(updatedRow.Metadata)  
if err != nil {  
  return err  
}
```

the `updatedRow.Metadata` already has TableName set.  Why not have topicForEvent just use metadata.TableName to return appropriate table descriptor?

I understand that currently, in this version, you only conditionally set tableName to non-empty
string if tableNameAttributedEnabled:
```
	tableName := ""
	if tableNameAttributeEnabled {
		tableName = updatedRow.TableName
	}
```
But... why? Why not just have topic descriptor carry table name?

If you are worried about future changes and perhaps having to extend things -- you might want to consider
introducing an additional interface.... something like:
```
type Attributer interface {
   TableName() string
   AnotherAttribute() int
  ...
}
```
Have topic descriptor lookup optionally wrap TopicDescriptor with "Attributer" interface.  At the place
where you need it -- e.g. pubsub sink:
```
if attributer, ok := topic.(Attributer); ok {
    // We should include additional message attributes
}
```
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm29MiZ3DqZz-HYW0xg:-Nm29Mi_DkAdSqTP1i-D:b-ll0mlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c0ecb291e401e7879368730b47b5b03f3a4d453/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L252)):*
> ```Go
> 	}
> 
> 	// No need to allocate
> ```

is this meant to be a todo?


<!-- Sent from Reviewable.io -->

2023-12-19 21:32 UTC, jayshrivastava commented
Verified using the local emulator that it works
```
Received Message {
  data: b'{"Key":["paris", "dddddddd-dddd-4000-8000-00000000...'
  ordering_key: ''
  attributes: {
    "TABLE_NAME": "vehicles"
  }
}.
Received Message {
  data: b'{"Key":["new york", "11111111-1111-4100-8000-00000...'
  ordering_key: ''
  attributes: {
    "TABLE_NAME": "vehicles"
  }
}.
Received Message {
  data: b'{"Key":["seattle", "55555555-5555-4400-8000-000000...'
  ordering_key: ''
  attributes: {
    "TABLE_NAME": "vehicles"
  }
}.
Received Message {
  data: b'{"Key":["washington dc", "44444444-4444-4400-8000-...'
  ordering_key: ''
  attributes: {
    "TABLE_NAME": "vehicles"
  }
}.
Received Message {
  data: b'{"Key":["san francisco", "77777777-7777-4800-8000-...'
  ordering_key: ''
  attributes: {
    "TABLE_NAME": "vehicles"
  }
}.
```

2023-12-19 22:13 UTC, miretskiy requested changes
> Reviewed 1 of 6 files at r2, 5 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 190 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2eAKO2tBBXME8mg6u:-Nm2eAKO2tBBXME8mg6v:b-oc7m1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/batching_sink.go#L190)):*
> ```Go
> 	payload.mvcc = mvcc
> 	payload.alloc = alloc
> 	payload.attributes.tableName = topic.GetTableName()
> ```

since we store topicDescriptor with payload.... why do we need to have payload.attributes?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm37o-z-3fdLUUAC2l7:-Nm37o-z-3fdLUUAC2l8:b-2mpc5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L47)):*
> ```Go
> }
> 
> var tableNameAttributeEnabled = envutil.EnvOrDefaultBool("COCKROACH_ENABLE_TABLE_NAME_PUSBUB_ATTRIBUTE", false)
> ```

I almost question this env var... I know we discussed it before, and agreed to use this as an opt in mechanism...
But wouldn't having a url parameter (e.g. `with_table_name_attribute` or whatnot) be a form of opt in that does not require entire cluster restart to pick up?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2yCIB09zHaN3lZJ9O:-Nm2yCIB09zHaN3lZJ9P:bcsjoew) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L151)):*
> ```Go
> 	}
> 	sinkClient.mu.topicCache = make(map[string]struct{})
> 	sinkClient.attributesMu.cache = cache.NewUnorderedCache(cache.Config{
> ```

I don't know if we need to have an lru cache...
in the cases when you have many topics published to the same sink -- it's likely to be
small(ish) number.  And even if you rename ALL topics (and so, presumably, your LRU cache
might kick in) -- again, I just don't see how it matters if we store e.g. 10 elements in a map, or 20...
Basically, consider using regular map.

Also, consider taking this cache and just putting it inside regular mu (which already has topicCache).
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2zGKZEXITPWdl9Eo0:-Nm2zGK_EXsSavmjzV6I:b-f6u0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L270)):*
> ```Go
> 	if tableNameAttributeEnabled {
> 		psb.sc.attributesMu.Lock()
> 		defer psb.sc.attributesMu.Unlock()
> ```

it's a bit sad we need to acquire this lock...
But ... do we need to acquire the lock?

Does it make sense to have attributes per buffer? Is it that much extra?
If you think it has to be on sink level, then maybe try sync.Map or some such
to avoid grabbing a lock.


<!-- Sent from Reviewable.io -->

2023-12-21 15:35 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 190 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2eAKO2tBBXME8mg6u:-NmC-zRf4KTDZVNu7IOX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/batching_sink.go#L190)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

since we store topicDescriptor with payload.... why do we need to have payload.attributes?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm37o-z-3fdLUUAC2l7:-NmC0-Wd6LjOEu_AVnKH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L47)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I almost question this env var... I know we discussed it before, and agreed to use this as an opt in mechanism...
But wouldn't having a url parameter (e.g. `with_table_name_attribute` or whatnot) be a form of opt in that does not require entire cluster restart to pick up?
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2yCIB09zHaN3lZJ9O:-NmC00KzDDC-lYOdii5V:bfzr1xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L151)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I don't know if we need to have an lru cache...
in the cases when you have many topics published to the same sink -- it's likely to be
small(ish) number.  And even if you rename ALL topics (and so, presumably, your LRU cache
might kick in) -- again, I just don't see how it matters if we store e.g. 10 elements in a map, or 20...
Basically, consider using regular map.

Also, consider taking this cache and just putting it inside regular mu (which already has topicCache).
</blockquote></details>

Done. Now it's just a map per-buffer.
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-Nm2zGKZEXITPWdl9Eo0:-NmC044r28S2cTNheudt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dedd23d792aea40d7a3bea11836a1b0b5028a469/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L270)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

it's a bit sad we need to acquire this lock...
But ... do we need to acquire the lock?

Does it make sense to have attributes per buffer? Is it that much extra?
If you think it has to be on sink level, then maybe try sync.Map or some such
to avoid grabbing a lock.
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NlZGbp-0KVkKaJ0NrG-:-NmC05f53UlbEzVg-gau:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5829675f7414943d535c9c04423e2f28ad28d41/pkg/ccl/changefeedccl/sink.go#L88)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I agree that it's easier to get the table from the row... What I don't understand is why can't we have topic descriptor always carry table name.
Consider the place where we obtain table descriptor (encodeAndEmit):
```
topic, err := c.topicForEvent(updatedRow.Metadata)  
if err != nil {  
  return err  
}
```

the `updatedRow.Metadata` already has TableName set.  Why not have topicForEvent just use metadata.TableName to return appropriate table descriptor?

I understand that currently, in this version, you only conditionally set tableName to non-empty
string if tableNameAttributedEnabled:
```
	tableName := ""
	if tableNameAttributeEnabled {
		tableName = updatedRow.TableName
	}
```
But... why? Why not just have topic descriptor carry table name?

If you are worried about future changes and perhaps having to extend things -- you might want to consider
introducing an additional interface.... something like:
```
type Attributer interface {
   TableName() string
   AnotherAttribute() int
  ...
}
```
Have topic descriptor lookup optionally wrap TopicDescriptor with "Attributer" interface.  At the place
where you need it -- e.g. pubsub sink:
```
if attributer, ok := topic.(Attributer); ok {
    // We should include additional message attributes
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-21 15:41 UTC, miretskiy approved these changes
> Reviewed 1 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116089)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 74 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NmC0guX5Ad_6lUUGBlv:-NmC0guX5Ad_6lUUGBlw:b2j2vox) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab795430c970f579f3fc018d1cc4d544363d2bf/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L74)):*
> ```Go
> // The number of distinct attribute maps to cache per-sink client (which is
> // the same as per-changefeed).
> var attributesCacheSize = 128
> ```

is this used?
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 253 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NmC10EW-75pXyHvGqRZ:-NmC10EW-75pXyHvGqR_:b-mfp4dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab795430c970f579f3fc018d1cc4d544363d2bf/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L253)):*
> ```Go
> 	msg := &pb.PubsubMessage{Data: content}
> 	if psb.sc.withTableNameAttribute {
> 		attrMap, ok := psb.attributesCache[attributes]
> ```

this doesn't work as a cache since you never initialize attributesCache (make(map[]....), so it's nil and will always return !ok; 
___
*[`pkg/ccl/changefeedccl/sink_pubsub_v2.go` line 255 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/116089#-NmC1Dci8bmuc16H3GE1:-NmC1Dci8bmuc16H3GE2:b-3zkrlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ab795430c970f579f3fc018d1cc4d544363d2bf/pkg/ccl/changefeedccl/sink_pubsub_v2.go#L255)):*
> ```Go
> 		attrMap, ok := psb.attributesCache[attributes]
> 		if !ok {
> 			attrMap = map[string]string{"TABLE_NAME": attributes.tableName}
> ```

you need to set psb.attributesCache[attributes] = attrMap


<!-- Sent from Reviewable.io -->

2023-12-21 19:42 UTC, jayshrivastava commented
bors r+

2023-12-21 21:11 UTC, merged