sql,opt: add hint for STRAIGHT join
cockroachdb/cockroach pull request #116013
Opened 2023-12-11 08:22 UTC by kevinmingtarja

Our current join hints (a INNER HASH JOIN b, a LEFT LOOKUP JOIN b, etc) fixes both the join order and the join algorithm. This commit adds the syntax and support for hinting the join order without hinting the join algorithm. This will be useful for the (few) cases where the optimizer processes the tables in a suboptimal order.

Resolves: #115308

Release note (sql change): It is now possible to hint to the optimizer that it should plan a straight join by using the syntax `... INNER STRAIGHT JOIN ...`. If the hint is provided, the optimizer will now fix the join order as given in the query, even if it estimates that a different plan using join reordering would have a lower cost.

2023-12-11 08:22 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=116013) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=116013) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=116013) it.</sub>

2023-12-11 08:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/116013)
<!-- Reviewable:end -->

2023-12-11 09:54 UTC, kevinmingtarja commented
Hi, I think one flaky test ([acceptance/version-upgrade](https://teamcity.cockroachdb.com/viewLog.html?buildId=13076354&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_LocalRoachtest#testNameId1758813801847915075)) is failing on the latest CI run, should we re-run it?

2023-12-14 17:16 UTC, rharding6373 reviewed
Thanks for the contribution, this looks pretty good! I have one test suggestion. I will defer the rest of the review to Michael, though, since he's thought about this feature more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-:-NldJ3QJDUSXBHwdpDuW:bs4lxse)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kevinmingtarja and @michae2)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NldGor651Y9SNoEJost:b9ptrbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
> ```Go
> 			// is inherently part of the join's logic.
> 			panic(pgerror.Newf(pgcode.Syntax,
> 				"%s can only be used with INNER joins", tree.AstStraight,
> ```

It would be great to have some logic tests that exercise this failure mode (and validate that the hint only works with `INNER`). Adding a subtest to `pkg/sql/logictest/testdata/logic_test/inner-join` seems like a good home for this kind of test, and it can use a lot of what you have already int the optbuilder test. Something like:

```
subtest straight_join

statement ok
CREATE TABLE t1 (x INT, PRIMARY KEY (x))

statement ok
CREATE TABLE t2 (x INT, y INT, PRIMARY KEY (x), INDEX idx_y (y))

statement ok
[INSERT some values into t1 and t2 here]

query I
SELECT * FROM t1 INNER STRAIGHT JOIN t2 ON t1.x = t2.y
----
[some output from the join here]

query I
SELECT * FROM t2 INNER STRAIGHT JOIN t1 ON t1.x = t2.y
----
[some output from the join here]

statement error pgcode: 42601 pq: STRAIGHT can only be used with INNER joins
SELECT * FROM t1 LEFT OUTER STRAIGHT JOIN t2 ON t1.x = t2.y

statement error pgcode: 42601 pq: STRAIGHT can only be used with INNER joins
SELECT * FROM t1 FULL STRAIGHT JOIN t2 ON t1.x = t2.y

subtest end
```


<!-- Sent from Reviewable.io -->

2023-12-14 17:43 UTC, mgartner commented
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NldPYzP7ZSkDUgrt_6w:b-f1w9mo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It would be great to have some logic tests that exercise this failure mode (and validate that the hint only works with `INNER`). Adding a subtest to `pkg/sql/logictest/testdata/logic_test/inner-join` seems like a good home for this kind of test, and it can use a lot of what you have already int the optbuilder test. Something like:

```
subtest straight_join

statement ok
CREATE TABLE t1 (x INT, PRIMARY KEY (x))

statement ok
CREATE TABLE t2 (x INT, y INT, PRIMARY KEY (x), INDEX idx_y (y))

statement ok
[INSERT some values into t1 and t2 here]

query I
SELECT * FROM t1 INNER STRAIGHT JOIN t2 ON t1.x = t2.y
----
[some output from the join here]

query I
SELECT * FROM t2 INNER STRAIGHT JOIN t1 ON t1.x = t2.y
----
[some output from the join here]

statement error pgcode: 42601 pq: STRAIGHT can only be used with INNER joins
SELECT * FROM t1 LEFT OUTER STRAIGHT JOIN t2 ON t1.x = t2.y

statement error pgcode: 42601 pq: STRAIGHT can only be used with INNER joins
SELECT * FROM t1 FULL STRAIGHT JOIN t2 ON t1.x = t2.y

subtest end
```
</blockquote></details>

Outer joins can be reordered in some cases. For example, here's a test case for join ordering (apologies if the output isn't straightforward to read) that shows two different orderings considered for a query with two adjacent left joins: https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/xform/testdata/rules/join_order#L1544-L1609

I would expect `l LEFT STRAIGHT JOIN r` to lock in the ordering of joining `r` to `l`. 


<!-- Sent from Reviewable.io -->

2023-12-14 17:50 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kevinmingtarja, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/memo/expr.go` line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldQpVV94iRYgQeOMt5:-NldQpVV94iRYgQeOMt6:b-lm2lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/memo/expr.go#L527)):*
> ```Go
> 	// DisallowHashJoinStoreRight, DisallowLookupJoinIntoRight,
> 	// DisallowInvertedJoinIntoRight, and DisallowMergeJoin.
> 	AllowAllJoinsIntoRight = disallowAll ^ DisallowHashJoinStoreRight ^ DisallowLookupJoinIntoRight ^ DisallowInvertedJoinIntoRight ^ DisallowMergeJoin
> ```

The current logic here: https://github.com/cockroachdb/cockroach/blob/f3424859b4173f4b0774f7ad4c78b6661efcc07c/pkg/sql/opt/xform/join_order_builder.go#L408-L413

Will prevent reordering if there is _any_ join flag present. So I suggest creating a seperate join flag under `PreferLookupJoinIntoRight` called something like `DisallowReordering` and using just that.


<!-- Sent from Reviewable.io -->

2023-12-15 20:25 UTC, kevinmingtarja reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/memo/expr.go` line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldQpVV94iRYgQeOMt5:-Nli0WiGB0_bkNNLsyS1:b-egnyxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/memo/expr.go#L527)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The current logic here: https://github.com/cockroachdb/cockroach/blob/f3424859b4173f4b0774f7ad4c78b6661efcc07c/pkg/sql/opt/xform/join_order_builder.go#L408-L413

Will prevent reordering if there is _any_ join flag present. So I suggest creating a seperate join flag under `PreferLookupJoinIntoRight` called something like `DisallowReordering` and using just that.
</blockquote></details>

Got it, that will be cleaner.
___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-Nli08K-3V328cMKIrNF:b-vc8wxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Outer joins can be reordered in some cases. For example, here's a test case for join ordering (apologies if the output isn't straightforward to read) that shows two different orderings considered for a query with two adjacent left joins: https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/xform/testdata/rules/join_order#L1544-L1609

I would expect `l LEFT STRAIGHT JOIN r` to lock in the ordering of joining `r` to `l`.
</blockquote></details>

Ah I missed that, thanks for pointing it out @mgartner!


<!-- Sent from Reviewable.io -->

2023-12-18 04:45 UTC, kevinmingtarja reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NlvA5WyBFKZu1qmvmBC:b-gjixdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, kevinmingtarja (Kevin Mingtarja) wrote…</i></summary><blockquote>

Ah I missed that, thanks for pointing it out @mgartner!
</blockquote></details>

Hi, I have a follow up question. Does this mean we should disable the `CommuteRightJoin` and `CommuteLeftJoin` rule as well to prevent the inputs from being swapped?

Which means in CommuteJoinFlags(), we should probably add an OR on `p.Flags.Has(memo.DisallowReordering)` right (line 586)?
https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/norm/join_funcs.go#L582-L588


<!-- Sent from Reviewable.io -->

2023-12-19 02:30 UTC, kevinmingtarja reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NlzlZ-vAVVc27bpJTYo:bmrdynx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, kevinmingtarja (Kevin Mingtarja) wrote…</i></summary><blockquote>

Hi, I have a follow up question. Does this mean we should disable the `CommuteRightJoin` and `CommuteLeftJoin` rule as well to prevent the inputs from being swapped?

Which means in CommuteJoinFlags(), we should probably add an OR on `p.Flags.Has(memo.DisallowReordering)` right (line 586)?
https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/norm/join_funcs.go#L582-L588
</blockquote></details>

My understanding isn't the clearest yet, but I believe if we don't disable `CommuteRightJoin` and `CommuteLeftJoin`, it is still possible for the optimizer to convert `a LEFT JOIN b` to `b RIGHT JOIN a` (even if we set the `DisallowReordering` flag), and we don't want this right?

But if we set the join flag as `disallowAll ^ DisallowHashJoinStoreRight ^ DisallowLookupJoinIntoRight ^ DisallowInvertedJoinIntoRight ^ DisallowMergeJoin` (which is what I did originally), I think this won't happen as we are explicitly disallowing the joins that processes the right table first. 

So even if in the memo, the reordering from commute left/right is "enumerated", it does not get explored as the optimizer will see from the join flags that those joins that processes the right table first are disallowed.


<!-- Sent from Reviewable.io -->

2024-01-02 20:33 UTC, mgartner reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kevinmingtarja, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NnAJuLq9iQyAmod_fO6:b-freesc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, kevinmingtarja (Kevin Mingtarja) wrote…</i></summary><blockquote>

My understanding isn't the clearest yet, but I believe if we don't disable `CommuteRightJoin` and `CommuteLeftJoin`, it is still possible for the optimizer to convert `a LEFT JOIN b` to `b RIGHT JOIN a` (even if we set the `DisallowReordering` flag), and we don't want this right?

But if we set the join flag as `disallowAll ^ DisallowHashJoinStoreRight ^ DisallowLookupJoinIntoRight ^ DisallowInvertedJoinIntoRight ^ DisallowMergeJoin` (which is what I did originally), I think this won't happen as we are explicitly disallowing the joins that processes the right table first. 

So even if in the memo, the reordering from commute left/right is "enumerated", it does not get explored as the optimizer will see from the join flags that those joins that processes the right table first are disallowed.
</blockquote></details>

Great find! Thanks for bringing up `CommuteRightJoin` and `CommuteLeftJoin`. I think you're absolutely correct, your original implementation will force the optimizer to pick the non-commuted joins, even though those rules are still applied and the commuted joins are explored. Let's stick with your original.

It may be more efficient to not apply/explore those rules at all, but there could be some complications there, so let's not do that for now (specifically, `CommuteRightJoin` is a normalization rule that makes it simpler for other rules to pattern match on joins—they only need to match left joins, not right joins too. Disabling `CommuteRightJoin` could lead to unexpectedly poor plans when rules dependent on it aren't applied).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NnAq_J9D9rGo7Mssumf:-NnAq_J9D9rGo7Mssumg:b-2jvcn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L1)):*
> ```
> # LogicTest: local
> ```

This is a good integration test, but I think this also deserves some more extensive and "unit-y" optimizer tests. I see two main things to test:

1. That join reordering is not explored with the `STRAIGHT` keyword. I think this is a good place to test that: https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/xform/testdata/rules/join_order
2. That a really high cost is given to commuted joins so that non-commuted joins are picked as the best plan by the optimizer. I think this is a good place to test that: https://github.com/cockroachdb/cockroach/blob/5d626ba4298dc8f9e0f9a0f9535d1c15efa2a83c/pkg/sql/opt/xform/testdata/coster/join#L100-L104

In both places it'd be great to test INNER, LEFT, and RIGHT joins.

If you have any questions about how these tests work, let me know.


<!-- Sent from Reviewable.io -->

2024-01-11 00:55 UTC, michae2 reviewed
Nice work @kevinmingtarja! This is looking great!

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-:-Nnq-w0BEGj-8StHvvH1:b-ff4ko7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kevinmingtarja, @mgartner, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NnplnVVEDDVo_NJGNKy:b-je1vwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great find! Thanks for bringing up `CommuteRightJoin` and `CommuteLeftJoin`. I think you're absolutely correct, your original implementation will force the optimizer to pick the non-commuted joins, even though those rules are still applied and the commuted joins are explored. Let's stick with your original.

It may be more efficient to not apply/explore those rules at all, but there could be some complications there, so let's not do that for now (specifically, `CommuteRightJoin` is a normalization rule that makes it simpler for other rules to pattern match on joins—they only need to match left joins, not right joins too. Disabling `CommuteRightJoin` could lead to unexpectedly poor plans when rules dependent on it aren't applied).
</blockquote></details>

Just chiming in to agree that it would be nice to also support `l LEFT STRAIGHT JOIN r` if possible!

IMO we should allow `InnerJoin`, `LeftOuterJoin`, `LeftSemiJoin`, `LeftAntiJoin`, `IntersectAllJoin`, and `ExceptAllJoin` here (though I don't think we can produce plans with those latter 4 join types and the `STRAIGHT` hint yet).
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Nnpvjgu8e_O5KgRd7g8:-Nnpvjgu8e_O5KgRd7g9:bab8lpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L73)):*
> ```
> # thus enforcing t1 to be on the right side of the join.
> query T
> EXPLAIN (VERBOSE) SELECT * FROM t2 INNER STRAIGHT JOIN t1 ON t1.x = t2.y
> ```

It would be interesting to add another testcase which naturally produces a hash join into the left side and see that we get a hash join into the right side instead. Maybe something like:

```sql
SELECT * FROM t1 INNER JOIN t2 ON t1.x + 1 = t2.y * 2;
```


<!-- Sent from Reviewable.io -->

2024-01-29 06:06 UTC, kevinmingtarja reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rharding6373)

___
*[`pkg/sql/opt/optbuilder/join.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NldGor651Y9SNoEJoss:-NpIkwBLAvsbAEBiyjqc:b-qyv3vu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/optbuilder/join.go#L106)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Just chiming in to agree that it would be nice to also support `l LEFT STRAIGHT JOIN r` if possible!

IMO we should allow `InnerJoin`, `LeftOuterJoin`, `LeftSemiJoin`, `LeftAntiJoin`, `IntersectAllJoin`, and `ExceptAllJoin` here (though I don't think we can produce plans with those latter 4 join types and the `STRAIGHT` hint yet).
</blockquote></details>

Got it! I have removed the restriction on the join type, so now `l LEFT STRAIGHT JOIN r` and `l RIGHT STRAIGHT JOIN r` is possible, plus I've added test cases for those as well.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NnAq_J9D9rGo7Mssumf:-NpIlbozDCndbMKs-whR:bvytat4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L1)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is a good integration test, but I think this also deserves some more extensive and "unit-y" optimizer tests. I see two main things to test:

1. That join reordering is not explored with the `STRAIGHT` keyword. I think this is a good place to test that: https://github.com/cockroachdb/cockroach/blob/b0e509b273235abc88d28a2dc0385c6b47c59c1b/pkg/sql/opt/xform/testdata/rules/join_order
2. That a really high cost is given to commuted joins so that non-commuted joins are picked as the best plan by the optimizer. I think this is a good place to test that: https://github.com/cockroachdb/cockroach/blob/5d626ba4298dc8f9e0f9a0f9535d1c15efa2a83c/pkg/sql/opt/xform/testdata/coster/join#L100-L104

In both places it'd be great to test INNER, LEFT, and RIGHT joins.

If you have any questions about how these tests work, let me know.
</blockquote></details>

Thanks for the pointers @mgartner ! This was super helpful, I've added test cases for INNER, LEFT, and RIGHT joins for (1), and for LEFT and RIGHT joins for (2).

For (2), I used `exploretrace` to output the transformation step that involves the commuted join with huge cost, since `opt` and `memo` only shows the best plan. Let me know if this works or if there's a better way to capture this in the test!
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Nnpvjgu8e_O5KgRd7g8:-NpIn-hE8-pAutQ99VR-:b12na16) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L73)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It would be interesting to add another testcase which naturally produces a hash join into the left side and see that we get a hash join into the right side instead. Maybe something like:

```sql
SELECT * FROM t1 INNER JOIN t2 ON t1.x + 1 = t2.y * 2;
```
</blockquote></details>

That's a good idea. I've added a test for that by adding a new unindexed column `t2.z` and use that as the join key, which will naturally produce a hash join with `t1` as the "build" side.


<!-- Sent from Reviewable.io -->

2024-02-02 00:47 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> This looks good to me! Great job @kevinmingtarja. I just have a few last suggestions about the execbuilder test.

@mgartner do you have any comments?

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-:-NpbDJldASM4smAUxpMR:b-8nfsq6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kevinmingtarja, @mgartner, and @rharding6373)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NpbFOszAoR7v34jC0n7:-NpbFOt-7JQ11Tt-juaD:b-fiofq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/365ea77b03447dfadd6da09c375da9c938d1b7ba/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L16)):*
> ```
>     "created_at": "2018-01-01 1:00:00.00000+00:00",
>     "row_count": 100,
>     "distinct_count": 100
> ```

Let's stick a `"null_count": 0` in here, too, just to be sure.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NpbFZms9H__zlNq1WhT:-NpbFZms9H__zlNq1WhU:b-o6h0es) ([raw file](https://github.com/cockroachdb/cockroach/blob/365ea77b03447dfadd6da09c375da9c938d1b7ba/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L28)):*
> ```
>     "distinct_count": 10000
>   }
> ]'
> ```

Using `"columns": ["y", "z"]` actually creates a single multi-column stat rather than the more usual two single-column stats. Let's revise this a little to something like:

```
statement ok
ALTER TABLE t2 INJECT STATISTICS '[
  {
    "columns": ["x"],
    "created_at": "2018-01-01 1:00:00.00000+00:00",
    "row_count": 10000,
    "distinct_count": 10000,
    "null_count": 0
  },
  {
    "columns": ["y"],
    "created_at": "2018-01-01 1:00:00.00000+00:00",
    "row_count": 10000,
    "distinct_count": 10000,
    "null_count": 0
  },
  {
    "columns": ["z"],
    "created_at": "2018-01-01 1:00:00.00000+00:00",
    "row_count": 10000,
    "distinct_count": 10000,
    "null_count": 0
  }
]'
```
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NpbBvNj8DdplVeL0s7j:-NpbBvNk0iYgm_IqB4aq:bh3kuah) ([raw file](https://github.com/cockroachdb/cockroach/blob/365ea77b03447dfadd6da09c375da9c938d1b7ba/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L218)):*
> ```
> # Now, the best plan should no longer be picked, as we're forcing the join order.
> query T
> EXPLAIN (VERBOSE) SELECT * FROM t1 LEFT STRAIGHT JOIN t2 ON t1.x = t2.z
> ```

It would be nice to also confirm that `EXPLAIN (VERBOSE) SELECT * FROM t1 RIGHT STRAIGHT JOIN t2 ON t1.x = t2.z` also produces the same plan except with a right outer hash join on top.


<!-- Sent from Reviewable.io -->

2024-02-02 17:21 UTC, kevinmingtarja reviewed
Thanks for the review and suggestions @michae2 ! I've just pushed the fixes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-:-NpepW7O67u_BRTuDDDy:bfduo60)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @rharding6373)



<!-- Sent from Reviewable.io -->

2024-02-02 18:19 UTC, mgartner requested changes
> Reviewed 3 of 11 files at r1, 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kevinmingtarja and @rharding6373)

___
*[`pkg/sql/parser/sql.y` line 13795 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Npezngp-suBrZlQnBKn:-Npezngp-suBrZlQnBKo:b-ohishm) ([raw file](https://github.com/cockroachdb/cockroach/blob/92919501d6082e513ba5e9142cd08462010a752b/pkg/sql/parser/sql.y#L13795)):*
> ```Yacc
> //  - STRAIGHT forces the join order, but not the algorithm; in other words, the
> //    left table is always read before the right table. `STRAIGHT` can only
> //    be used with INNER joins (though this is not enforced by the syntax).
> ```

The part about only being used with INNER joins is no longer correct.

nit: "in other words, the left table is always read before the right table" is not technically correct. I would just remove that part to avoid confusion.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/straight_join` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-NnAq_J9D9rGo7Mssumf:-Npf1jL46_xHe0AtBcBU:b7jdjoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c918bdbfcdb14ef944e7033bb304789e43b9ee2f/pkg/sql/opt/exec/execbuilder/testdata/straight_join#L1)):*
> For (2), I used `exploretrace` to output the transformation step that involves the commuted join with huge cost, since `opt` and `memo` only shows the best plan. Let me know if this works or if there's a better way to capture this in the test!

Works for me. Nice job finding and making use of the `exploretrace` test command!
___
*[`pkg/sql/opt/xform/testdata/rules/join_order` line 3542 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Npf-_qvBpWbMxnXDYkl:-Npf-_qvBpWbMxnXDYkm:b-ms497p) ([raw file](https://github.com/cockroachdb/cockroach/blob/92919501d6082e513ba5e9142cd08462010a752b/pkg/sql/opt/xform/testdata/rules/join_order#L3542)):*
> ```
>  ├── scan straight_join2
>  └── filters
>       └── straight_join1.x = y
> ```

I think it'd be good to have some tests with 2 joins where both or only one of the joins has a `STRAIGHT` hint. 


<!-- Sent from Reviewable.io -->

2024-02-02 19:15 UTC, kevinmingtarja reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/parser/sql.y` line 13795 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Npezngp-suBrZlQnBKn:-NpfEgGK4TaaOpfQBb1P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92919501d6082e513ba5e9142cd08462010a752b/pkg/sql/parser/sql.y#L13795)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The part about only being used with INNER joins is no longer correct.

nit: "in other words, the left table is always read before the right table" is not technically correct. I would just remove that part to avoid confusion.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/testdata/rules/join_order` line 3542 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-Npf-_qvBpWbMxnXDYkl:-NpfEazk6lnQbhO0UY0R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/92919501d6082e513ba5e9142cd08462010a752b/pkg/sql/opt/xform/testdata/rules/join_order#L3542)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think it'd be good to have some tests with 2 joins where both or only one of the joins has a `STRAIGHT` hint.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 18:30 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Great work! Thanks again for contributing!

bors r+

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116013#-:-NpuXBiy89tuDQzX71_d:b-ry0x4g)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kevinmingtarja and @rharding6373)



<!-- Sent from Reviewable.io -->

2024-02-05 23:38 UTC, merged

2024-02-06 02:24 UTC, kevinmingtarja commented
Thanks for all the help and review folks!