regionliveness: detect if the region enum is not public
cockroachdb/cockroach pull request #116376
Opened 2023-12-13 19:48 UTC by fqazi

Previously, the regionlivneess used a cached set of region descriptor
that could be stale for a given txn time. This works fine in most cases,
but if the region is going through a mutation we can either have queries
with a syntax error or an error for the enum value not being public,
where the second error was not handled. This patch will address this by
ignoring errors related to an enum not being public.

Fixes: #116309

Release note: None

2023-12-13 19:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/116376)
<!-- Reviewable:end -->

2023-12-13 21:14 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116376)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/types/errors.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116376#-Nl_-Ndm2bW2CNsBJLMS:-Nl_-Ndm2bW2CNsBJLMT:b-4tuin1) ([raw file](https://github.com/cockroachdb/cockroach/blob/952889107e3c2a3d95caa1c5fd21767928008faa/pkg/sql/types/errors.go#L38)):*
> ```Go
> // enumValueIsNotPublicYetError
> func IsNewEnumValueIsNotPublicYetError(err error) bool {
> 	return errors.Is(err, &enumValueIsNotPublicYetError{})
> ```

`errors.Is` is not correct here. that only works to compare against a specific instance of an error (see the docs on the function)

we'd need to use `errors.HasType(err, (*enumValueIsNotPublicYetError)(nil))`

or we could avoid some complexity by doing something like below
___
*[`pkg/sql/types/types.go` line 2720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116376#-NlZzZP-9M7IMuDC_D-Z:-NlZzZP-9M7IMuDC_D-_:b-tln0bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/952889107e3c2a3d95caa1c5fd21767928008faa/pkg/sql/types/types.go#L2720)):*
> ```Go
> 			// physical representation.
> 			if t.TypeMeta.EnumData.IsMemberReadOnly[i] {
> 				return 0, newEnumValueIsNotPublicYetError(logical)
> ```

this could be a little lighter weight if we made a global error var:
```
var EnumValueNotYetPublicError = errors.New("enum value is not yet public")
```

then here we could do something like:
```
return errors.WithMessagef(EnumValueNotYetPublicError, "cannot use enum value %q", logical)
```


<!-- Sent from Reviewable.io -->

2023-12-13 21:46 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116376)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/types/types.go` line 2720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116376#-NlZzZP-9M7IMuDC_D-Z:-Nl_8K1A01m4LanVCgPO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952889107e3c2a3d95caa1c5fd21767928008faa/pkg/sql/types/types.go#L2720)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this could be a little lighter weight if we made a global error var:
```
var EnumValueNotYetPublicError = errors.New("enum value is not yet public")
```

then here we could do something like:
```
return errors.WithMessagef(EnumValueNotYetPublicError, "cannot use enum value %q", logical)
```
</blockquote></details>

Done.
___
*[`pkg/sql/types/errors.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116376#-Nl_-Ndm2bW2CNsBJLMS:-Nl_8IkH5p22c_yWtaik:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/952889107e3c2a3d95caa1c5fd21767928008faa/pkg/sql/types/errors.go#L38)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`errors.Is` is not correct here. that only works to compare against a specific instance of an error (see the docs on the function)

we'd need to use `errors.HasType(err, (*enumValueIsNotPublicYetError)(nil))`

or we could avoid some complexity by doing something like below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 21:52 UTC, rafiss approved these changes
lgtm!

> Reviewed 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116376#-:-Nl_9bDp92Ygjqh_sIFw:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)



<!-- Sent from Reviewable.io -->

2023-12-14 03:38 UTC, fqazi commented
@rafiss TFTR!

bors r+

2023-12-14 04:34 UTC, merged