changefeedccl: don't ignore error in ExpectErrWithTimeout
cockroachdb/cockroach pull request #116843
Opened 2023-12-20 04:41 UTC by nvanbenschoten

This commit fixes a bug in ExpectErrWithTimeout where incorrect errors were ignored. This bug was recently introduced in f9a720d, so we've been missing test coverage in changefeed_test.go for a few months.

Epic: None
Release note: None

2023-12-20 04:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/116843)
<!-- Reviewable:end -->

2023-12-20 16:52 UTC, miretskiy requested changes
I believe this is being merged in https://github.com/cockroachdb/cockroach/pull/116645

2023-12-20 17:14 UTC, nvanbenschoten commented
Oh nice, happy to close this then. Mind pushing that through when you get a chance? Also, we'll want to backport that PR to the release branches mentioned here.

2023-12-20 17:14 UTC, closed without merging

2023-12-20 17:54 UTC, yuzefovich commented
Why do we want to backport this to 22.2 and 23.1? It doesn't seem like #110751 was backported there.

2023-12-27 01:55 UTC, nvanbenschoten commented
https://github.com/cockroachdb/cockroach/pull/110751 was backported to v22.2 and v23.1, but it wasn't linked to the original PR because the commit was tacked on to https://github.com/cockroachdb/cockroach/pull/110635 and https://github.com/cockroachdb/cockroach/pull/110636. So we do need to backport https://github.com/cockroachdb/cockroach/pull/110751.