CRDB-28040 : JWKS fetch from jwks_uri
cockroachdb/cockroach pull request #117054
Opened 2023-12-23 16:19 UTC by BabuSrithar

This commit adds capability to fetch remote JWKS from issuer's jwks_uri endpoint. This will satisfy the requirement to have an ability to automatically fetch the new JWK when the existing JWK is rotated - without human intervention or custom scripts.

Changes include

1. The existing order of token signature verification first and rest of claims next is modified to get issuer first and then the token signature verification. This change is requied to determine the issuer for which the jwks has to be fetched remotely.

2. Use JWKS configured through cluster setting first and fallback to fetching from jwks_uri only when the JWKS is not configured or the configured JWKS does not contain the key that is used to sign the presented token. If the key exists in configured JWKS, do not attempt to fetch from jwks_uri. [Cluster Setting takes precedence over jwks_uri]

3. Modification to exiting test cases to match the new order of verification steps.

The change is backward compatible and not changes required in existing deployments and JWT Auth usage.

2023-12-23 16:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117054)
<!-- Reviewable:end -->

2024-01-06 00:14 UTC, kevin-v-ngo commented
https://github.com/cockroachdb/cockroach/issues/103505

2024-01-08 18:35 UTC, bdarnell requested changes
I think we probably want a cluster setting to turn this on, at least if there's no caching - for deployments that expect to keep their JWKS cluster settings up to date, we don't want to DoS their identity server if someone spams invalid tokens. If we had caching it would probably be fine to do without a cluster setting. (and if we had caching do we even want the hard-coded JWKS config or should it just always be loaded automatically?)

> Reviewed 3 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-:-NneLXhj-Y7kIrVX085O:bweze67)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne7jnh5oeb9srWuZw2:-Nne7jnh5oeb9srWuZw3:b5tr1nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L148)):*
> ```Go
> 	unverifiedToken, err := jwt.Parse(tokenBytes)
> 	if err != nil {
> 		log.Errorf(ctx, "token parse failed %v", err.Error())
> ```

In general, we don't like to both log and return errors. Elsewhere in this file we just do `return errors.Newf(...)`, so I would remove all of the `log.Errorf` calls. 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne84BUCpS6C2NufS3B:-Nne84BUCpS6C2NufS3C:b-vl7keb) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L172)):*
> ```Go
> 	keyExists := false
> 	if authenticator.mu.conf.jwks.Len() > 0 {
> 		jwsMessage, err := jws.Parse(tokenBytes)
> ```

This looks redundant - isn't `jwsMessage` the same as `unverifiedToken`?
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne8StuDiPboQada2eD:-Nne8StuDiPboQada2eE:b8drm13) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L173)):*
> ```Go
> 	if authenticator.mu.conf.jwks.Len() > 0 {
> 		jwsMessage, err := jws.Parse(tokenBytes)
> 		if err != nil || jwsMessage.Signatures() == nil || len(jwsMessage.Signatures()) == 0 {
> ```

In Go, `len(nil)` is 0, so you don't need a separate `nil` check. 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneEx778J1e6VjYoXUV:-NneEx78DMgjWAJOBXUo:bv12njz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L190)):*
> ```Go
> 
> 	// Now that both the issuer and key-id are matched, parse the token again to validate the signature.
> 	parsedToken, err := jwt.Parse(tokenBytes, jwt.WithKeySet(jwkSet), jwt.WithValidate(true), jwt.InferAlgorithmFromKey(true))
> ```

Did you look at the `WithVerifyAuto` option? It looks like it might give us a way to plug our HTTP fetcher into the library itself so we don't have to do our own key matching. (and we only have to parse the input once). There's also a `jwk.Cache` object that may be able to handle caching for us although I haven't looked at it closely enough to see whether it can support our combination of a pre-configured key set and the remote URL. 

https://pkg.go.dev/github.com/lestrrat-go/jwx/v2@v2.0.18/jwt#WithVerifyAuto
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGSD-0QyI2Q089ktb:-NneGSD-0QyI2Q089ktc:bpgq102) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L24)):*
> ```
> 
> # see authentication_jwt_test.go for examples of how to generate these tokens.
> jwt_cluster_setting issuers=issuer
> ```

Don't we still want a test that verifies that with `jwt_cluster_setting enabled=true` but no issuers, we get an error? 
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGl9Y3d4UTvCHl3zQ:-NneGl9Y3d4UTvCHl3zR:b-6hp8wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L48)):*
> ```
> 
> # see authentication_jwt_test.go for examples of how to generate these tokens.
> jwt_cluster_setting issuers=["issuer","issuer2"]
> ```

As above, I think we still want a failure test here, in which the cluster setting specifies issuer but the token is from issuer2. 


<!-- Sent from Reviewable.io -->

2024-01-09 10:16 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne7jnh5oeb9srWuZw2:-NnhcYNkD2gXgh8nPaBu:b-agmvfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L148)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In general, we don't like to both log and return errors. Elsewhere in this file we just do `return errors.Newf(...)`, so I would remove all of the `log.Errorf` calls.
</blockquote></details>

Ah, ok. My intent was to log detailed errors for debugging provide only minimal error message to client, so that we avoid leaking security configs.  I can move to "return  errors.WithDetailf(...)" which seems to fit this requirement. Would that be ok ? 


<!-- Sent from Reviewable.io -->

2024-01-09 10:17 UTC, BabuSrithar commented
I would prefer caching over another cluster setting here. We already have many settings just for JWT auth.  Even after having caching, we might have to still keep JWKS config to ensure backward compatibility - right ? 





<!-- Sent from Reviewable.io -->

2024-01-09 10:21 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne84BUCpS6C2NufS3B:-Nnhimpw63mUaNS3_Z--:b-tf7f94) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L172)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This looks redundant - isn't `jwsMessage` the same as `unverifiedToken`?
</blockquote></details>

They are different. `unverifiedToken` is Token type and `jwsMessage` is Message type. 
Token type does not contain signatures. 


<!-- Sent from Reviewable.io -->

2024-01-09 10:30 UTC, BabuSrithar reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne7jnh5oeb9srWuZw2:-NnhlH4_BO2pxodjn1Q5:b-enjrfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L148)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

Ah, ok. My intent was to log detailed errors for debugging provide only minimal error message to client, so that we avoid leaking security configs.  I can move to "return  errors.WithDetailf(...)" which seems to fit this requirement. Would that be ok ?
</blockquote></details>

Made the change to `errors.WithDetailf(...)`
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne8StuDiPboQada2eD:-NnhlOp36VB2668J0BN4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L173)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In Go, `len(nil)` is 0, so you don't need a separate `nil` check.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-09 10:37 UTC, BabuSrithar commented
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGSD-0QyI2Q089ktb:-Nnhm7zX-jTo-NtF720P:b1t4fbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't we still want a test that verifies that with `jwt_cluster_setting enabled=true` but no issuers, we get an error?
</blockquote></details>

I can add that. 

Related question : I found this whole file little redundant, given the test cases we have in `pkg/ccl/jwtauthccl/authentication_jwt_test.go` 

Do you know if we need to maintain both these ? 


<!-- Sent from Reviewable.io -->

2024-01-09 14:42 UTC, bdarnell requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne7jnh5oeb9srWuZw2:-Nnid_Vp-RjXYZVJP2JC:bncm2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L148)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

Made the change to `errors.WithDetailf(...)`
</blockquote></details>

Hmm, I think error details are hidden from our own error telemetry but they're still exposed to the client. If that's the concern then we may still want to swallow these errors, but I don't think logging at every point that generates an error is the right way to do that. It would be better to just use `errors.WithDetailf` here and have something at a higher layer catch all errors from the authenticator to decide how to log or return them. (This would also cover our other kinds of authenticators, and may already be done). 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne84BUCpS6C2NufS3B:-NnicujM-lG8EmgU-MI-:bf0gbog) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L172)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

They are different. `unverifiedToken` is Token type and `jwsMessage` is Message type. 
Token type does not contain signatures.
</blockquote></details>

Ah, I misread that one is `jwt.Parse` and the other is `jws.Parse`
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGSD-0QyI2Q089ktb:-NnieN5X2oO9M5zNv7iU:b2db8yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L24)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

I can add that. 

Related question : I found this whole file little redundant, given the test cases we have in `pkg/ccl/jwtauthccl/authentication_jwt_test.go` 

Do you know if we need to maintain both these ?
</blockquote></details>

I'm not sure. I'm reluctant to delete any tests that are already written since it's unclear whether we'd still have full coverage if we deleted anything, but I don't think we need to add new tests in both places. Normally I'd prefer the data-driven test but they're hard to read and write for anything dealing with security tokens so it's probably better to make authentication_jwt_test.go our main test here.

One reason to keep at least a few data-driven tests is to ensure that we remain compatible with the old tokens hard-coded in this file. Otherwise we could change both the generator and the consumer so that the Go tests would pass but we wouldn't actually be compatible. 


<!-- Sent from Reviewable.io -->

2024-01-29 17:16 UTC, BabuSrithar reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne7jnh5oeb9srWuZw2:-NpL1HCE5o_2Yx2BZY5B:b-xg3bia) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L148)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Hmm, I think error details are hidden from our own error telemetry but they're still exposed to the client. If that's the concern then we may still want to swallow these errors, but I don't think logging at every point that generates an error is the right way to do that. It would be better to just use `errors.WithDetailf` here and have something at a higher layer catch all errors from the authenticator to decide how to log or return them. (This would also cover our other kinds of authenticators, and may already be done).
</blockquote></details>

Have removed newly added `errors.WithDetailf` and logs. Just returning what make sense to return to the client. 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-Nne84BUCpS6C2NufS3B:-NpL1ZSE6tH2L9LegqYG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L172)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Ah, I misread that one is `jwt.Parse` and the other is `jws.Parse`
</blockquote></details>

Done.
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneEx778J1e6VjYoXUV:-NpL1bbq4oOU9fo9VjNA:b-sch3mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L190)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Did you look at the `WithVerifyAuto` option? It looks like it might give us a way to plug our HTTP fetcher into the library itself so we don't have to do our own key matching. (and we only have to parse the input once). There's also a `jwk.Cache` object that may be able to handle caching for us although I haven't looked at it closely enough to see whether it can support our combination of a pre-configured key set and the remote URL. 

https://pkg.go.dev/github.com/lestrrat-go/jwx/v2@v2.0.18/jwt#WithVerifyAuto
</blockquote></details>

We are using lestrrat-go/jwx/v1 

The AutoVerify of this version seem to only supports auto fetch of jwks from jku field of JWT. The JWTs we issue do not have jku set. I am seeing if we can use other With* options to avoid double parsing / custom key matching. 


https://pkg.go.dev/github.com/lestrrat-go/jwx/jws#VerifyAuto
`Currently it only supports verification via \`jku\` which will be fetched using the object specified in jws.JWKSetFetcher. Note that URLs in \`jku\` can only have https scheme.`

https://github.com/lestrrat-go/jwx/blob/8c53d0ae52d5ab1e2b37c5abb67def9e7958fd65/jws/jws.go#L263
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGSD-0QyI2Q089ktb:-NpLCupO1zIAr-tCN9yT:bmlzj8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L24)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure. I'm reluctant to delete any tests that are already written since it's unclear whether we'd still have full coverage if we deleted anything, but I don't think we need to add new tests in both places. Normally I'd prefer the data-driven test but they're hard to read and write for anything dealing with security tokens so it's probably better to make authentication_jwt_test.go our main test here.

One reason to keep at least a few data-driven tests is to ensure that we remain compatible with the old tokens hard-coded in this file. Otherwise we could change both the generator and the consumer so that the Go tests would pass but we wouldn't actually be compatible.
</blockquote></details>

Have added this case to authentication_jwt_test.go > TestIssuerCheck
___
*[`pkg/ccl/testccl/authccl/testdata/jwt` line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneGl9Y3d4UTvCHl3zQ:-NpLD65F6wSKrsyhViw2:b-46jiq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/testccl/authccl/testdata/jwt#L48)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

As above, I think we still want a failure test here, in which the cluster setting specifies issuer but the token is from issuer2.
</blockquote></details>

This case is already there in authentication_jwt_test.go > TestIssuerCheck


<!-- Sent from Reviewable.io -->

2024-01-30 05:51 UTC, bdarnell reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-:-NpNtryWDAIq9tU5bq_R:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneEx778J1e6VjYoXUV:-NpNtc7L-Y3h-WI3uege:b-9dlf50) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L190)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

We are using lestrrat-go/jwx/v1 

The AutoVerify of this version seem to only supports auto fetch of jwks from jku field of JWT. The JWTs we issue do not have jku set. I am seeing if we can use other With* options to avoid double parsing / custom key matching. 


https://pkg.go.dev/github.com/lestrrat-go/jwx/jws#VerifyAuto
`Currently it only supports verification via \`jku\` which will be fetched using the object specified in jws.JWKSetFetcher. Note that URLs in \`jku\` can only have https scheme.`

https://github.com/lestrrat-go/jwx/blob/8c53d0ae52d5ab1e2b37c5abb67def9e7958fd65/jws/jws.go#L263
</blockquote></details>

OK, we can leave that until we upgrade to v2. Maybe we should start to add the jku field, or maybe there are other options we can combine. 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NpNuhBxDc0WSyMtt74Y:bi3jk3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
> ```Go
> 		_, keyExists = authenticator.mu.conf.jwks.LookupKeyID(tokenKeyId)
> 	}
> 	// if key not found in jwks, fetch remote jwks from issuerUrl and try again.
> ```

I'm not sure it makes sense to have both a statically-configured key set and a dynamic fallback. I think users will either want to set the static key in the cluster setting and *only* use that key, or they want it dynamically refreshed and then it doesn't make sense to have a maybe-stale key in the setting. It's probably better to have this as two different modes instead of a fallback. 


<!-- Sent from Reviewable.io -->

2024-01-30 07:32 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NpOFvmrDeUKfKeIBJy4:b-6h81p5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not sure it makes sense to have both a statically-configured key set and a dynamic fallback. I think users will either want to set the static key in the cluster setting and *only* use that key, or they want it dynamically refreshed and then it doesn't make sense to have a maybe-stale key in the setting. It's probably better to have this as two different modes instead of a fallback.
</blockquote></details>

The original request had the ask to fallback. I think it makes sense in the current scenario where the jwks is periodically set  by customers and the fallback will cover the windows where the setting is stale. When the setting is still valid, it avoid a network call in auth flow, it might help with latency. This will also be no-op for customers when they upgrade and does not need any more settings.  But I dont have strong opinion. If you feel strongly about it,  I can remove the fallback and make it either or, in which case we need to introduce an explicit setting. 


<!-- Sent from Reviewable.io -->

2024-01-30 07:32 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneEx778J1e6VjYoXUV:-NpOHAaNCbNVCsKnQe8B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L190)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

OK, we can leave that until we upgrade to v2. Maybe we should start to add the jku field, or maybe there are other options we can combine.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-30 11:40 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NpP8_F_BfAZUQUdme5A:b-jcsxa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

The original request had the ask to fallback. I think it makes sense in the current scenario where the jwks is periodically set  by customers and the fallback will cover the windows where the setting is stale. When the setting is still valid, it avoid a network call in auth flow, it might help with latency. This will also be no-op for customers when they upgrade and does not need any more settings.  But I dont have strong opinion. If you feel strongly about it,  I can remove the fallback and make it either or, in which case we need to introduce an explicit setting.
</blockquote></details>

The original request asked for a fallback but I think they'd change their mind if they thought about it. In the fallback mode, you don't have a hard break if your key expires, but you do have a sudden decrease in performance, which for many users is just as bad (leading to metastable failure). I think it's better to make the remote fetch the normal case (which will make any performance impact visible). 

Additionally it's simply easier to use since you just have to enable/disable instead of pasting in a big blob (and periodically update it). This is also more compatible with the options available in the v2 library. 

We can keep the static JWKS setting for backwards compatibility, but users will need to opt in to the remote fetch to have any automatic refresh. 


<!-- Sent from Reviewable.io -->

2024-01-30 16:42 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NpQEfxY0wmKb36UKfih:b-ufy5ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The original request asked for a fallback but I think they'd change their mind if they thought about it. In the fallback mode, you don't have a hard break if your key expires, but you do have a sudden decrease in performance, which for many users is just as bad (leading to metastable failure). I think it's better to make the remote fetch the normal case (which will make any performance impact visible). 

Additionally it's simply easier to use since you just have to enable/disable instead of pasting in a big blob (and periodically update it). This is also more compatible with the options available in the v2 library. 

We can keep the static JWKS setting for backwards compatibility, but users will need to opt in to the remote fetch to have any automatic refresh.
</blockquote></details>

Ok. I have added a new systems setting called "jwks_auto_fetch_enabled" for JWT Auth. 
This will address making these mode either or. It will also act a reactive shield for DoS caused by invalid tokens. 


<!-- Sent from Reviewable.io -->

2024-01-31 07:57 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NpTV1ZT2TjNxkyAfc3z:bovyu93) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

*systems setting = cluster setting
</blockquote></details>

In v2, you need to use `jwk.Whitelist` in addition to the `VerifyAuto` setting. Instead of a boolean for auto-fetch, let's make a setting for `jwks_uri_allow_list` and you enable auto-fetch by setting a non-empty allow list. 
___
*[`pkg/ccl/jwtauthccl/settings.go` line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpTW5KlD8e6Nmz84TaE:-NpTW5KlD8e6Nmz84TaF:b-5nscfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/75c4c7616e2201b14c502958c78cf076e1def560/pkg/ccl/jwtauthccl/settings.go#L82)):*
> ```Go
> 	JWKSAutoFetchEnabledSettingName,
> 	"enables or disables automatic fetching of JWKs from the issuer's well-known endpoint. "+
> 		"If this is enabled, the JWKSSetting will be ignored.",
> ```

JWKSSetting is an internal name but this is a user-facing help string. It should use the public setting name `server.jwt_authentication.jwks`. 


<!-- Sent from Reviewable.io -->

2024-01-31 08:19 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/settings.go` line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpTW5KlD8e6Nmz84TaE:-NpTa9YkAFk_qFU5SeAb:bb93uyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/75c4c7616e2201b14c502958c78cf076e1def560/pkg/ccl/jwtauthccl/settings.go#L82)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

JWKSSetting is an internal name but this is a user-facing help string. It should use the public setting name `server.jwt_authentication.jwks`.
</blockquote></details>

Thanks for catching this. Fixed. 


<!-- Sent from Reviewable.io -->

2024-02-05 19:05 UTC, emnet-crl approved these changes
> Reviewed 3 of 5 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar, @bdarnell, and @dhartunian)



<!-- Sent from Reviewable.io -->

2024-02-09 18:34 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NneEx778J1e6VjYoXUV:-NqE8WyC4wQo9Rhu-Pzf:b-8k3oaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc0c5e52645e657d136c71b337a591cce35589d6/pkg/ccl/jwtauthccl/authentication_jwt.go#L190)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://cockroachlabs.atlassian.net/browse/CRDB-35990 to track v2 upgrade. 


<!-- Sent from Reviewable.io -->

2024-02-12 05:22 UTC, bdarnell approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117054)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BabuSrithar and @dhartunian)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NqQjjf44fjcwPdcF_lj:b-splwvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, BabuSrithar (BabuSrithar) wrote…</i></summary><blockquote>

I missed this comment somehow. Just noticed it. 

We already have issuers whitelist setting (`server.jwt_authentication.issuers`). We construct jwks_uri from issuer's openid-configuration only after verifying the issuer first. I think `jwks_uri_allow_list` will be redundant to `issuers` whitelist?
</blockquote></details>

They're close but not quite the same. While the issuer's openid-discovery document is on its own domain, jwks_uri may point to a different domain and therefore we can't necessarily derive a JWKS URI whitelist from our issuer whitelist. But maybe that's OK and we can treat it as redundant: we can automatically allow any URI that is linked by our trusted issuer. (so when we use VerifyAuto in v2 we can just pass a whitelist that accepts anything). The boolean is OK with me, then. 


<!-- Sent from Reviewable.io -->

2024-02-12 17:54 UTC, BabuSrithar commented
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117054#-NpNuhBxDc0WSyMtt74X:-NqTQ46nD3uCAKNDAZAV:bbebzk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ceb3a2fb4fd9e42949405c505301838598118b1/pkg/ccl/jwtauthccl/authentication_jwt.go#L178)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

They're close but not quite the same. While the issuer's openid-discovery document is on its own domain, jwks_uri may point to a different domain and therefore we can't necessarily derive a JWKS URI whitelist from our issuer whitelist. But maybe that's OK and we can treat it as redundant: we can automatically allow any URI that is linked by our trusted issuer. (so when we use VerifyAuto in v2 we can just pass a whitelist that accepts anything). The boolean is OK with me, then.
</blockquote></details>

Yes, in V2 we can pass accept all whitelist and the JWKS URI if derived from a trusted source already. 


<!-- Sent from Reviewable.io -->

2024-02-12 17:55 UTC, BabuSrithar commented
bors r+

2024-02-12 20:13 UTC, merged

2024-02-28 22:10 UTC, dhartunian commented
blathers backport 23.2

2024-03-06 20:24 UTC, mikeCRL commented
@BabuSrithar 👋 The commit message in this PR lacks a `Release note: ` statement so, by default, it is not being included in the `v24.1.0-alpha.1` release notes or resulting in a DOC issue, for further docs consideration.

Can you please confirm:
* Should this have a public release note? If so, could you please suggest text?
* Should this be considered for a documentation change?

2024-03-07 02:37 UTC, BabuSrithar commented
@mikeCRL , sorry that I did not include `Release note:`. 

This ticket does need doc update. We have a doc jira ticket created (https://cockroachlabs.atlassian.net/browse/DOC-9694)

Regarding the doc text : Here is my note for Doc / PM - https://cockroachlabs.atlassian.net/browse/CRDB-28040?focusedCommentId=209665

2024-03-07 05:23 UTC, mikeCRL commented
@BabuSrithar Thank you. Is this OK for a release note? Any edits?

Introduced a new cluster setting, `server.jwt_authentication.jwks_auto_fetch.enabled`, enabling automatic fetching of JSON Web Key Sets (JWKS) from an issuer's remote endpoint. This prevents an administrator's need to update the JWKS specified in `server.jwt_authentication.jwks` - whether manually or by custom script - when the identity provider's keys rotate. This direct specification of JWKS remains the default, as the new cluster setting defaults to `false`.

2024-03-07 17:45 UTC, BabuSrithar commented
@mikeCRL , that note looks good to me.