gossip: Include highWaterStamps map in gossip debug info
cockroachdb/cockroach pull request #117011
Opened 2023-12-22 15:32 UTC by a-robinson

This can be useful information when debugging gossip-related problems (e.g. to determine how much of the data being set around the gossip network is directly accounted for by the highWaterStamps) and it's very easy to include.

Epic: none

Release note (ops change): The gossip status advanced debug page now includes information about the server's high water stamps for every other node it knows about in the gossip cluster.

---

In my particular case, it was valuable when looking into why the amount of data being gossiped was so large (as measured via the `gossip_(bytes|infos)_(sent|received)` prometheus metrics).

Given a large cluster where nodes many nodes are decommissioned over time, you can end up with an ever-accumulating amount of gossip from old nodes -- "distsql-draining:<node-id>" and "distsql-version:<node-id>". These keys can stick around forever (as I've previously called out on #51838), and if you don't manually clear them (using `crdb_internal.unsafe_clear_gossip_info()`) then they can have a larger effect on gossip than I'd have expected because they cause the old decommmissioned node IDs to be kept around in every node's highWaterStamps map, and that highWaterStamp map gets copied into [*every* gossip Request and Response](https://github.com/cockroachdb/cockroach/blob/master/pkg/gossip/gossip.proto#L29-L66), which can add up to a ton of extra data getting shipped around if you have a lot of decommissioned nodes.

I have a bunch more thoughts on inefficiencies in the gossip network and how it scales at larger cluster sizes and/or when there are a lot of decommissioned nodes, but don't know how much interest there is in them. If y'all are interested, let me know and I'm happy to share some notes and ideas.

2023-12-22 15:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117011)
<!-- Reviewable:end -->

2024-01-06 03:59 UTC, shralex approved these changes
Thank you for the PR, Alex! I think we are approaching a point where more investment in Gossip is warranted, and will certainly reach out, it would be great to collaborate. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117011#-:-NnRulse3TfBTfOmjDWX:b3wotoi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @a-robinson)

___
*[`pkg/gossip/gossip.proto` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117011#-NnRuaRb6ws4o11cT7Q6:-NnRuaRb6ws4o11cT7Q7:bgr162h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a3033cbbb33f01fb1703c0c0d07fdc26d130d1/pkg/gossip/gossip.proto#L134)):*
> ```proto
>   ServerStatus server = 3 [(gogoproto.nullable) = false];
>   Connectivity connectivity = 4 [(gogoproto.nullable) = false];
>   map<int32, int64> high_water_stamps = 5 [(gogoproto.castkey) = "github.com/cockroachdb/cockroach/pkg/roachpb.NodeID", (gogoproto.nullable) = false];
> ```

Is there any concern about backward compatibility when this field is marked non-nullable ?


<!-- Sent from Reviewable.io -->

2024-01-08 22:55 UTC, a-robinson reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117011)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @shralex)

___
*[`pkg/gossip/gossip.proto` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117011#-NnRuaRb6ws4o11cT7Q6:-NnfGYZh3rD8bEwJpY5b:bv18l30) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a3033cbbb33f01fb1703c0c0d07fdc26d130d1/pkg/gossip/gossip.proto#L134)):*
<details><summary><i>Previously, shralex wrote…</i></summary><blockquote>

Is there any concern about backward compatibility when this field is marked non-nullable ?
</blockquote></details>

I can't say I've gone back to read the gogoproto spec to confirm what's expected, but I did just test it out in both directions and it's worked ok:

* From node containing this patch to node not containing this patch -> the result included an empty object for the `highWaterStamps` field, i.e. `
"highWaterStamps": {}`
* From node not containing this patch to node containing this patch -> the result omitted the `highWaterStamps` field entirely.

But if you'd rather I do something else here (nullable = true, I guess?), I'm happy to change it. Just let me know.


<!-- Sent from Reviewable.io -->

2024-01-08 23:33 UTC, shralex commented
bors r+

2024-01-08 23:34 UTC, shralex requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117011)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @a-robinson)

___
*[`pkg/gossip/gossip.proto` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117011#-NnRuaRb6ws4o11cT7Q6:-NnfQFlcEwOG4dQ8RwU2:btdo304) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4a3033cbbb33f01fb1703c0c0d07fdc26d130d1/pkg/gossip/gossip.proto#L134)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I can't say I've gone back to read the gogoproto spec to confirm what's expected, but I did just test it out in both directions and it's worked ok:

* From node containing this patch to node not containing this patch -> the result included an empty object for the `highWaterStamps` field, i.e. `
"highWaterStamps": {}`
* From node not containing this patch to node containing this patch -> the result omitted the `highWaterStamps` field entirely.

But if you'd rather I do something else here (nullable = true, I guess?), I'm happy to change it. Just let me know.
</blockquote></details>

Thank you for checking!


<!-- Sent from Reviewable.io -->

2024-01-08 23:35 UTC, shralex approved these changes

2024-01-09 01:26 UTC, merged