sql: use high priority for populating RoleMemberCache
cockroachdb/cockroach pull request #117258
Opened 2024-01-02 23:42 UTC by Xiang-Gu

Previously, when the RoleMemberCache is invalid, it launches a new txn in a singleflight to read from `system.role_members` table to populate the cache. If, however, the original txn has previously laid a write intent on the same system table, then we end up having a deadlock: original txn waits for this new txn; this new txn waits for original txn. 

Fixes #117144
Release note (bug fix): Fixed a bug where concurrent GRANTs can cause deadlocks.

2024-01-02 23:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117258)
<!-- Reviewable:end -->

2024-01-03 19:25 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnFlv2f7NtWsHmpeTrx):*
This seems reasonable as a partial solution to https://github.com/cockroachdb/cockroach/issues/117144, but it doesn't solve the problem if the GRANT transaction is also high priority. What are our plans to address that?
___
*[`pkg/sql/authorization.go` line 609 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnFmDI7B-NL21POBtd_:-NnFmDI7B-NL21POBtda:bjvb52f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdd3072ed28dac2b17e7676eeb451d589df74c4/pkg/sql/authorization.go#L609)):*
> ```Go
> 			var m map[username.SQLUsername]bool
> 			err = execCfg.InternalDB.Txn(ctx, func(ctx context.Context, newTxn isql.Txn) error {
> 				// Run the membership read as high-priority, thereby pushing any intents
> ```

Should we package the reproduction that you outlined in #117144 into a test?


<!-- Sent from Reviewable.io -->

2024-01-04 18:09 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @Xiang-Gu)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnFlv2f7NtWsHmpeTrx):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems reasonable as a partial solution to https://github.com/cockroachdb/cockroach/issues/117144, but it doesn't solve the problem if the GRANT transaction is also high priority. What are our plans to address that?
</blockquote></details>

the main way i see to improve this for high priority transactions is the idea to remove the logic that preserves locks across retries (https://cockroachlabs.slack.com/archives/C06B2A4R659/p1703193548750879?thread_ts=1703191425.539129&cid=C06B2A4R659). should we get an issue filed for that?

another (maybe hacky) approach could be to skip the cache if we can detect that we are using a transaction that has been retried. i'm not sure if there's a way to check that from looking at the `kv.Txn`.


<!-- Sent from Reviewable.io -->

2024-01-04 19:48 UTC, nvanbenschoten commented
> the main way i see to improve this for high priority transactions is the idea to remove the logic that preserves locks across retries (https://cockroachlabs.slack.com/archives/C06B2A4R659/p1703193548750879?thread_ts=1703191425.539129&cid=C06B2A4R659). should we get an issue filed for that?

We are tracking this in https://github.com/cockroachdb/cockroach/issues/117020. However, any change to the transaction model is requires care, as it directly impacts user transactions, can break functioning applications, and needs to preserve backwards compatibility. We do want to pursue this, but it will be a multi-release effort.

> another (maybe hacky) approach could be to skip the cache if we can detect that we are using a transaction that has been retried.

Are retries a prerequisite here? Are there cases where a transaction has written to `system.role_members` earlier in a single epoch and then access the RoleMemberCache later in that same epoch?

>  i'm not sure if there's a way to check that from looking at the kv.Txn.

`kv.Txn.Epoch() > 0` will tell us that.

2024-01-04 21:51 UTC, rafiss commented
> Are retries a prerequisite here? Are there cases where a transaction has written to system.role_members earlier in a single epoch and then access the RoleMemberCache later in that same epoch?

I do think retries are a prereq here. If a transaction has written to system.role_members earlier in this epoch, then the role_members table version would be incremented here: https://github.com/cockroachdb/cockroach/blob/008b6927f6888e0c136f92bb19c608203e20ea7c/pkg/sql/grant_role.go#L210-L215

That would cause us to skip using the cache here: https://github.com/cockroachdb/cockroach/blob/008b6927f6888e0c136f92bb19c608203e20ea7c/pkg/sql/authorization.go#L544-L546

(The exception is if an admin user directly writes to the `role_members` table with an INSERT, but that is not a use case we support anyway.)

2024-01-08 16:28 UTC, rafiss commented
>  it doesn't solve the problem if the GRANT transaction is also high priority. What are our plans to address that?

another way to address it would be to add another priority level that is something like `MaxSystemPriority` here: https://github.com/cockroachdb/cockroach/blob/58502d1125b70dafeea34b96733967a387f9ef0d/pkg/roachpb/data.go#L1074-L1085

It would be higher than `MaxUserPriority`, but would only be used by internally created transactions, such as this singleflight operation.

2024-01-08 16:47 UTC, rafiss commented
The idea in https://github.com/cockroachdb/cockroach/issues/117493 also would achieve the same result, and doesn't need the introduction of a new priority level.

2024-01-08 21:50 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @Xiang-Gu)

___
*[`pkg/sql/authorization.go` line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf1qiy7wVqv1k3NtCK:-Nnf1qiy7wVqv1k3NtCL:b-2vdxhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization.go#L545)):*
> ```Go
> 
> 	tableVersion := tableDesc.GetVersion()
> 	if tableDesc.IsUncommittedVersion() {
> ```

in order to handle high priority transactions, let's skip the cache if we detect that `kv.Txn.Epoch() > 0` (meaning that this is a txn retry). the test you added can have another mode that runs the GRANTs in a high priority transaction, by using `SET default_transaction_priority = 'high'. verify that it fails before adding the `kv.Txn.Epoch() > 0` check, but passes after.
___
*[`pkg/sql/authorization_test.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf2FVwBC9kWNZ6iC90:-Nnf2FVwBC9kWNZ6iC91:bx9d0c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization_test.go#L137)):*
> ```Go
> 	//    the singleflight to re-populate the now-invalid MembershipCache,
> 	//    which would previously have caused a deadlock.
> 	time.Sleep(5 * time.Second)
> ```

we should be able to avoid using a sleep here. could we use `testutils.SucceedsSoon` and verify that the GRANT appears in the result of SHOW QUERIES?


<!-- Sent from Reviewable.io -->

2024-01-08 22:33 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/authorization_test.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf2FVwBC9kWNZ6iC90:-NnfA_7l10vuVkNIVbAn:bjb3fda) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization_test.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should be able to avoid using a sleep here. could we use `testutils.SucceedsSoon` and verify that the GRANT appears in the result of SHOW QUERIES?
</blockquote></details>

I tried that initially and realize that having `GRANT` showing up in SHOW QUERIES isn't enough because the repo of the issue requires a retry on this GRANT once txn1 commits, and if we commit txn1 after this GRANT shows up in SHOW QUERIES, then it's possible that this GRANT won't experience any retries and can thus complete successfully as well. 

One way to ensure that retry happens upon txn1 commits is to ask txn1 wait for a few seconds so that its write-timestamp is bumped up so that upon commit, txn2 will encounter a WriteTooOldRetryError and a retry ensues. 

But I agree that sleeping isn't very elegant; I just cannot think of another way to achieve this.

ps: I didn't notice this nuance until when I was trying to write the test where I realized that everything would just work without the sleep (or the retry). I was glad that we waited for a while before committing `txn1` when we were finding a repro. Otherwise, if we do things "too fast", we will see txn2 unblocked and completes successfully and we would miss the repro. Maybe that's also why we didn't catch this type of deadlock in our automated tests bc things happen very fast in a test and a retry is almost never encountered, unless injected purposefully.


<!-- Sent from Reviewable.io -->

2024-01-08 22:35 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/authorization_test.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf2FVwBC9kWNZ6iC90:-NnfCWe7DUFPq6Pa6HwR:bpv15dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization_test.go#L137)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

I tried that initially and realize that having `GRANT` showing up in SHOW QUERIES isn't enough because the repo of the issue requires a retry on this GRANT once txn1 commits, and if we commit txn1 after this GRANT shows up in SHOW QUERIES, then it's possible that this GRANT won't experience any retries and can thus complete successfully as well. 

One way to ensure that retry happens upon txn1 commits is to ask txn1 wait for a few seconds so that its write-timestamp is bumped up so that upon commit, txn2 will encounter a WriteTooOldRetryError and a retry ensues. 

But I agree that sleeping isn't very elegant; I just cannot think of another way to achieve this.

ps: I didn't notice this nuance until when I was trying to write the test where I realized that everything would just work without the sleep (or the retry). I was glad that we waited for a while before committing `txn1` when we were finding a repro. Otherwise, if we do things "too fast", we will see txn2 unblocked and completes successfully and we would miss the repro. Maybe that's also why we didn't catch this type of deadlock in our automated tests bc things happen very fast in a test and a retry is almost never encountered, unless injected purposefully.
</blockquote></details>

Do you have thoughts on other approaches here to gracefully ensure a retry in `txn2`?


<!-- Sent from Reviewable.io -->

2024-01-09 17:25 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/authorization.go` line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf1qiy7wVqv1k3NtCK:-NnjFR7020s_GCXaKkl0:buv94ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization.go#L545)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in order to handle high priority transactions, let's skip the cache if we detect that `kv.Txn.Epoch() > 0` (meaning that this is a txn retry). the test you added can have another mode that runs the GRANTs in a high priority transaction, by using `SET default_transaction_priority = 'high'. verify that it fails before adding the `kv.Txn.Epoch() > 0` check, but passes after.
</blockquote></details>

done, I have added logic to skip using singleflight if in retry.


<!-- Sent from Reviewable.io -->

2024-01-09 18:20 UTC, Xiang-Gu commented
I'm now trying to figure out if the interval after which a txn's write ts is bumped up can be lowered, so that we can reduce the sleep duration for `txn1` in the test.

2024-01-10 05:03 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @Xiang-Gu)

___
*[`pkg/sql/authorization_test.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf2FVwBC9kWNZ6iC90:-Nnli8iSB43IkaE1ylTn:b-gksfqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization_test.go#L137)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

Do you have thoughts on other approaches here to gracefully ensure a retry in `txn2`?
</blockquote></details>

the important part is to check that the lock has a waiter on it. try checking for this in a `testutils.SucceedsSoon`:
```
select count(*) from crdb_internal.cluster_locks l join crdb_internal.cluster_queries q on l.txn_id = q.txn_id where query like 'GRANT%';
```
___
*[`pkg/sql/authorization_test.go` line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnlaNDa-2KSvMTOutwv:-NnlaNDa-2KSvMTOutww:b-fnyum4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5c13a80d6d9b5972f426dab65c2fcaf36967d0/pkg/sql/authorization_test.go#L150)):*
> ```Go
> 	}
> 
> 	t.Run("concurrent GRANTs", func(t *testing.T) {
> ```

nit: to make this a bit more table-driven:
```
for _, priority := range []string{"NORMAL", "HIGH"} {
  t.Run(fmt.Sprintf("priority=%s", priority), func(t *testing.T) {
    runConcurrentGrantsWithPriority(t, priority)
  }
}
```


<!-- Sent from Reviewable.io -->

2024-01-10 05:19 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @Xiang-Gu)

___
*[`-- commits` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnlmeXjC8ibxEi0YUl7):*
An alternative here is to make the decision based on the txn's priority, instead of whether or not it has retried. So for instance, we would only bypass the cache for high-priority txns. That might be preferable because high-priority txns are more rare than normal priority txns that have retried. Was that considered?

We also only need this guard until we address https://github.com/cockroachdb/cockroach/issues/117493, but that can't be backported, so it's great that we found a full solution here which is backportable.


<!-- Sent from Reviewable.io -->

2024-01-10 23:30 UTC, Xiang-Gu reviewed
@rafiss So I did some experiments on this one and after some fumbling, I decided to go with the sleep approach (and by setting a cluster setting to a very small value, I was able to push the sleep time down to 0.5s). 

I tried approaches that avoids using sleep but instead use `succeedSoon` to check something (e.g. check `txn2` is running or `txn2` is being blocked, etc.) as a way to "sleep"/delay before we commit `txn1`. The major obstacle is those approach actually takes much longer than 0.5s (e.g. queries and joining crdb_internal.cluster_locks and crdb_internal.cluster_queries took 6-7s). 

The PR is ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-:-Nnpg_t4B6pGPQ1TPqa9:b-ka56c4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`-- commits` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnlmeXjC8ibxEi0YUl7):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

An alternative here is to make the decision based on the txn's priority, instead of whether or not it has retried. So for instance, we would only bypass the cache for high-priority txns. That might be preferable because high-priority txns are more rare than normal priority txns that have retried. Was that considered?

We also only need this guard until we address https://github.com/cockroachdb/cockroach/issues/117493, but that can't be backported, so it's great that we found a full solution here which is backportable.
</blockquote></details>

Good point! Why not both? I have modified the code to skip cache if `txn` is a high priority AND in retry.
___
*[`pkg/sql/authorization_test.go` line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-Nnf2FVwBC9kWNZ6iC90:-NnpdK15-rhUMa49VyXO:b-27rh3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ac01285e1bf882b70944372885bd3d6383e8ecb/pkg/sql/authorization_test.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the important part is to check that the lock has a waiter on it. try checking for this in a `testutils.SucceedsSoon`:
```
select count(*) from crdb_internal.cluster_locks l join crdb_internal.cluster_queries q on l.txn_id = q.txn_id where query like 'GRANT%';
```
</blockquote></details>

The issue is not only about that we need to ensure `txn2` started running and blocking; It is more about needing `txn1` to wait a while so that when `txn1` commits, it needs to bump up its write timestamp to cause `txn2` to enter retry. 
___
*[`pkg/sql/authorization_test.go` line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NnlaNDa-2KSvMTOutwv:-NnpdJKZ2mn0z7k9RJva:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5c13a80d6d9b5972f426dab65c2fcaf36967d0/pkg/sql/authorization_test.go#L150)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: to make this a bit more table-driven:
```
for _, priority := range []string{"NORMAL", "HIGH"} {
  t.Run(fmt.Sprintf("priority=%s", priority), func(t *testing.T) {
    runConcurrentGrantsWithPriority(t, priority)
  }
}
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-11 16:01 UTC, nvanbenschoten reviewed
The change to `pkg/sql/authorization.go` <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>.

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-:-NntEpIC7YUxaeWWSBz6:bwdtrl6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @Xiang-Gu)

___
*[`pkg/sql/authorization.go` line 624 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NntEuhc0MEUkoZfRTRP:-NntEuhc0MEUkoZfRTRQ:biqivy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/994963bd1b02c711939d1ca4ac53ee2d8edb5448/pkg/sql/authorization.go#L624)):*
> ```Go
> 				// attempts to read the same system table, is blocked by the
> 				// GRANT/REVOKE txn.
> 				if err := newTxn.KV().SetUserPriority(roachpb.MaxUserPriority); err != nil {
> ```

How often do we expect these transactions to run? Until we address https://github.com/cockroachdb/cockroach/issues/95227, a frequent, unending stream of high-priority reads can starve a conflicting writer. Should we be concerned about that in this case?


<!-- Sent from Reviewable.io -->

2024-01-11 16:32 UTC, rafiss approved these changes
just small nits. lgtm!

2024-01-11 19:14 UTC, Xiang-Gu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117258)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/authorization.go` line 624 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117258#-NntEuhc0MEUkoZfRTRP:-NntuP0MDzM_OEOJ3GE_:b-m57xi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/994963bd1b02c711939d1ca4ac53ee2d8edb5448/pkg/sql/authorization.go#L624)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How often do we expect these transactions to run? Until we address https://github.com/cockroachdb/cockroach/issues/95227, a frequent, unending stream of high-priority reads can starve a conflicting writer. Should we be concerned about that in this case?
</blockquote></details>

This is only run whenever there is a cache miss. 
- A new user/role is created and accessed
- A GRANT/REVOKE is issued, invalidate the cache, and now needs to repopulate the cache for all users/roles accessed.

In other words, this will only be run frequently if there is a lot, lot of `CREATE USER/ROLE` and `GRANT/REVOKE` in the workload. I recall a similar issue for descriptor lease renewal where if the system have high hundreds or thousands of descriptors and with the default renewal interval of 2.5min, the system is full of those high-priority, lease renewal txns and that have caused starvation problems.

But I suppose it'd be very rare to have a workload that `GRANT/REVOKE/CREATE USER` in that level of frequency (?) so in general I'm less concerned with the starvation in this case.
___
*[`pkg/sql/authorization_test.go` line 100 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117258#gh-1449114724:-NntwHiv96N4Hkm1UUZs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/994963bd1b02c711939d1ca4ac53ee2d8edb5448/pkg/sql/authorization_test.go#L100)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's use `skip.UnderDuress`
</blockquote></details>

done
___
*[`pkg/sql/authorization_test.go` line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/117258#gh-1449114783:-NntwNVS53Ae4gDXEiJW:b1jugj) ([raw file](https://github.com/cockroachdb/cockroach/blob/994963bd1b02c711939d1ca4ac53ee2d8edb5448/pkg/sql/authorization_test.go#L157)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: `"concurrent GRANTs with %s priority"` is verbose. to make it easier to view the test name and run the test, this should be. `t.Run(fmt.Sprintf("priority=%s", priority), ...`

whenever the test results are shown, it will look like: `TestConcurrentGrants/priority=NORMAL`

with the more verbose description, it would look like: `TestConcurrentGrants/concurrent_GRANTs_with_NORMAL_priority`, which is redundant
</blockquote></details>

good point! Done


<!-- Sent from Reviewable.io -->

2024-01-11 19:20 UTC, Xiang-Gu commented
TFTR!

bors r+

2024-01-12 00:00 UTC, merged