logmetrics: code/cruft cleanup of LogMetricsRegistry
cockroachdb/cockroach pull request #117514
Opened 2024-01-08 19:52 UTC by abarganier

The LogMetricsRegistry had a few unsightly bits to its code that deserved some cleanup. Among these are:

1. Unnecessary `logMetricsStruct` variable. This was likely added due to me missing the fact that you can add individual metrics to a `metric.Registry` using `.AddMetric()`, meaning we don't need a separate struct to use for the `.AddMetricsStruct()` function.
2. Unnecessary mutex guarding the list of counters tracked by LogMetricsRegistry. The underlying counters are backed by atomic integers, and we never modify the set of counters after initialization, meaning this mutex is unneeded.
3. Unnecessary complexity by using a slice of counters instead of a map. The `LogMetricsRegistry.counters` member is more easily reasoned about as a map than a slice, where we use iota-based types to index into it. Using a slice was a premature optimization made during the original code review process, but in hindsight, the added complexity and difficulty in reading/understanding the code is unlikely to be worth whatever marginal performance improvement that it brings.
4. Adding a new metric requires a developer to update many places. The more places that need to be touched, the more opportunity there are for mistakes.

This patch aims to clean up the items mentioned above.

Release note: none

Epic: CRDB-21266

2024-01-08 19:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117514)
<!-- Reviewable:end -->

2024-01-09 17:24 UTC, petermattis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117514)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @jmcarp)

___
*[`pkg/util/log/logmetrics/metrics.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-NnjEwRb04PLmlMO8fg-:-NnjEwRb04PLmlMO8fg0:b-ut1jvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c2944b7bbfc076b6d6dbf0eba298b969b7817b/pkg/util/log/logmetrics/metrics.go#L92)):*
> ```Go
> 	// counters contains references to all the counters
> 	// tracked by LogMetricsRegistry, keyed by metric type.
> 	counters map[log.Metric]*metric.Counter
> ```

This doesn't need to be and shouldn't be a map for performance. See https://github.com/cockroachdb/cockroach/pull/117548 which I developed independently not realizing you were working on this.


<!-- Sent from Reviewable.io -->

2024-01-10 15:54 UTC, abarganier reviewed
Thanks for the feedback; less is more. I've unified the changes from https://github.com/cockroachdb/cockroach/pull/117548 into this PR. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-:-Nno3Wc-C_zXdapnOBeN:b-rgksaf)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @jmcarp, and @petermattis)

___
*[`pkg/util/log/logmetrics/metrics.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-NnjEwRb04PLmlMO8fg-:-Nno433U60of0veLX3Sr:b362ugp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0c2944b7bbfc076b6d6dbf0eba298b969b7817b/pkg/util/log/logmetrics/metrics.go#L92)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This doesn't need to be and shouldn't be a map for performance. See https://github.com/cockroachdb/cockroach/pull/117548 which I developed independently not realizing you were working on this.
</blockquote></details>


Done. 


<!-- Sent from Reviewable.io -->

2024-01-10 18:28 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-:-Nnoc_it8ZBNEGNssZ3E:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @jmcarp)

___
*[`pkg/util/log/logmetrics/metrics.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-NnocNwl239UHqB0jPD6:-NnocNwm2iP2OoFHKaPN:brn16sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/322847ee1c62ce22c6194a1206a8401db1ff84ea/pkg/util/log/logmetrics/metrics.go#L23)):*
> ```Go
> 	// logMetricsReg is a singleton instance of the logMetricsRegistry.
> 	logMetricsReg          = newLogMetricsRegistry()
> 	FluentSinkConnAttempts = metric.Metadata{
> ```

You can unexport all of these `metric.Metadata` variables. In general, you should only export variables which you actually need to use externally.


<!-- Sent from Reviewable.io -->

2024-01-11 15:21 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117514)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @jmcarp, and @petermattis)

___
*[`pkg/util/log/logmetrics/metrics.go` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117514#-NnocNwl239UHqB0jPD6:-Nnt6GFgCrFyECvWAu42:b4zm0iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/322847ee1c62ce22c6194a1206a8401db1ff84ea/pkg/util/log/logmetrics/metrics.go#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can unexport all of these `metric.Metadata` variables. In general, you should only export variables which you actually need to use externally.
</blockquote></details>

Ah, right. Fixed.


<!-- Sent from Reviewable.io -->

2024-01-11 16:47 UTC, petermattis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117514)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @jmcarp)



<!-- Sent from Reviewable.io -->

2024-01-11 18:23 UTC, abarganier commented
TFTR! 

bors r=petermattis

2024-01-11 19:50 UTC, merged