zip: explain redaction for span config boundary keys
cockroachdb/cockroach pull request #117547
Opened 2024-01-09 16:16 UTC by abarganier

Data deemed essential for debugging is considered acceptable to keep unredacted from a compliance perspective in dumps of debug data, such as a debug zip. Two instances where this applies are for range boundary keys, and span config boundary keys.

This isn't immediately obvious, so this patch adds a comment to the zip table registry for the `system.span_configurations` table to clarify why `start_key` and `end_key` are not considered sensitive.

Release note: none

Epic: CRDB-20791

2024-01-09 16:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117547)
<!-- Reviewable:end -->

2024-01-09 16:57 UTC, andrewbaptist requested changes
Based on the current debugging, I would make a stronger statement here. The start and end keys today can only be applied to metadata objects and these objects are converted to numbers. So while in general keys can contain sensitive data the span_configuration keys in specific can not. 

Maybe something along the lines of:
// Boundary keys for span configs, which are derived from zone configs, are typically on metadata object boundaries (database, table, or index), and not arbitrary range boundaries and therefore do not contain sensitive information.  Therefore they can remain unredacted."

However looking more carefully there is a sequence of steps that can create an unredacted value (but I think this would apply to more places than just here.

```
alter table users partition by LIST(city) (PARTITION a VALUES IN ('rome')) ;
alter partition a of table users configure zone using num_replicas=5;

select start_key from system.span_configurations;
> \xfe8af28912726f6d650001
```

```
% ./cockroach debug decode-key --user-key fe8af28912726f6d650001
/Tenant/2/Table/106/1/"rome"
```

We might want to give some "PCI guidance" on "responsibilities of the customer" to not partition on sensitive data values: https://www.cockroachlabs.com/docs/cockroachcloud/pci-dss

2024-02-08 15:55 UTC, abarganier commented
@andrewbaptist Sorry for the delay, I've updated the comments to better describe the scenario.

Regarding documentation updates, I'd like to loop in @adbrenn to get their take on it. I don't think it could hurt to at least provide some guidance/warning to customers in our public facing PCI documentation. Let me know what you think!

2024-02-09 21:30 UTC, andrewbaptist approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks for taking the time to clean up this text.

2024-02-12 15:23 UTC, adbrenn commented
Hey team - 

> We might want to give some "PCI guidance" on "responsibilities of the customer" to not partition on sensitive data values: https://www.cockroachlabs.com/docs/cockroachcloud/pci-dss

I think that documentation updates would be more valuable as guidance to the broader CRDB user base as this could be applicable to any sensitive information, i.e. SSNs are not of concern of PCI, but a customer should try to set up CRDB to not partition on sensitive data values to avoid SSNs being exposed unnecessarily. I'll chat with the docs team about where we think the best place to included the suggested highlights.

2024-02-28 16:22 UTC, abarganier commented
Sounds good, thank you @adbrenn 

I think we can handle those docs updates separately, so I'm going to merge this.

TFTRs! 

bors r=andrewbaptist

2024-02-28 17:55 UTC, merged