changefeedccl: use queue instead of channel in pubsub sink
cockroachdb/cockroach pull request #117692
Opened 2024-01-11 19:55 UTC by jayshrivastava

In this (#111829) investigation, it was observed that there was a lot of wasted CPU performing unions in intsets. This is caused by the parallel io package which relies on performing unions to check for conflicting keys.

See comments #115536 for more details.

Closes: https://github.com/cockroachdb/cockroach/issues/115536
Release note: None
Epic: None

2024-01-11 19:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/117692)
<!-- Reviewable:end -->

2024-01-12 18:12 UTC, miretskiy requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-NnyrdYxEue1J3QFZ_hV:-NnyrdYxEue1J3QFZ_hW:b9x4mhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/008129265c055e75bdca741cbfc0df39903e4565/pkg/ccl/changefeedccl/parallel_io.go#L145)):*
> ```Go
> }
> 
> func newRequestQueue(sz int) *requestQueue {
> ```

I'm not sure this queue is needed...  Can the caller (batching sink) -- just try to acquire
intpool resource?  Let's discuss.
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nny0-mEEsErXGvEn40R:-Nny0-mEEsErXGvEn40S:b-kb7d4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/008129265c055e75bdca741cbfc0df39903e4565/pkg/ccl/changefeedccl/parallel_io.go#L368)):*
> ```Go
> 		}
> 
> 		// Check for incoming requests and ush back on the producer if we have too many pending requests.
> ```

s/ush/push/
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nny099aCBOxemLoL3C5:-Nny099aCBOxemLoL3C6:b-f0couu) ([raw file](https://github.com/cockroachdb/cockroach/blob/008129265c055e75bdca741cbfc0df39903e4565/pkg/ccl/changefeedccl/parallel_io.go#L370)):*
> ```Go
> 		// Check for incoming requests and ush back on the producer if we have too many pending requests.
> 		waitForRequest := make(chan struct{})
> 		close(waitForRequest)
> ```

declare (file scope):
```
var closedCh = func() chan struct{} {
  c := make(chan struct{})
  close(c)
  return c
}()
```
and do `waitForRequest = closedCh` to avoid allocating channel on every request.
___
*[`pkg/ccl/changefeedccl/sink.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nny-hXIBtnFVUSX9mme:-Nny-hXIBtnFVUSX9mmf:bdf8peg) ([raw file](https://github.com/cockroachdb/cockroach/blob/12ce879a77d139a51632c0b3b7799137d67e6524/pkg/ccl/changefeedccl/sink.go#L179)):*
> ```Go
> 		" that allows for a higher throughput",
> 	// TODO: delete the original pubsub sink code
> 	util.ConstantWithMetamorphicTestBool("changefeed.new_pubsub_sink.enabled", true),
> ```

Would prefer to have this done in a separate PR.
Also, might make sense to address the TODO.


<!-- Sent from Reviewable.io -->

2024-01-17 22:27 UTC, jayshrivastava commented
Still working on this.

2024-01-24 20:12 UTC, miretskiy reviewed
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 380 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nox59RqEbpq-7LUSm3A:-Nox59Rr7njIFDHFuanM:btkrdw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86fa19356a1dbd89a2d58966576b86354db1a4/pkg/ccl/changefeedccl/batching_sink.go#L380)):*
> ```Go
> 		}
> 
> 		req, send, err := ioEmitter.AdmitRequest(ctx, batchBuffer)
> ```

If I understand correctly, one of the complexities in structuring this code
is the fact that we have to check for "s.doneCh" whenever we try to submit new request;
or wait for them to finish.

Have you considered passing in s.doneCh to IOEmitter so that it can wait for 
ctx.Done and doneCh, and whatever other internal channels it needs to?

Would that result in a more encapsulated code where AdmintRequest would not have
to return a channel, and instead will handle things internall (much like you have here)?
___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 405 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-NowpCWt5pQYQXyjE7hY:-NowpCWu3KouhkMejbg-:bomgzjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86fa19356a1dbd89a2d58966576b86354db1a4/pkg/ccl/changefeedccl/batching_sink.go#L405)):*
> ```Go
> 		}
> 
> 		// Terminal case. The request was admitted, it must be sent. There
> ```

I view terminal in fatal terms :) 
Maybe rephrase the comment?
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nown_ud6Z5njnz5qwCB:-Nown_ud6Z5njnz5qwCC:b-apxbp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86fa19356a1dbd89a2d58966576b86354db1a4/pkg/ccl/changefeedccl/parallel_io.go#L43)):*
> ```Go
> 	ioHandler IOHandler
> 
> 	q         *quotapool.IntPool
> ```

nit: perhaps call it `quota`?


<!-- Sent from Reviewable.io -->

2024-01-25 18:44 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 380 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Nox59RqEbpq-7LUSm3A:-Np0vqIM7MswbKL5ys-M:bo342hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86fa19356a1dbd89a2d58966576b86354db1a4/pkg/ccl/changefeedccl/batching_sink.go#L380)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

If I understand correctly, one of the complexities in structuring this code
is the fact that we have to check for "s.doneCh" whenever we try to submit new request;
or wait for them to finish.

Have you considered passing in s.doneCh to IOEmitter so that it can wait for 
ctx.Done and doneCh, and whatever other internal channels it needs to?

Would that result in a more encapsulated code where AdmintRequest would not have
to return a channel, and instead will handle things internall (much like you have here)?
</blockquote></details>

I had this at one point, but I wasn't a fan of it. I think the better change would be to eliminate the done channel and use context cancellation instead.
___
*[`pkg/ccl/changefeedccl/batching_sink.go` line 405 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-NowpCWt5pQYQXyjE7hY:-Np0vpQbEvuJL7byRwJZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a86fa19356a1dbd89a2d58966576b86354db1a4/pkg/ccl/changefeedccl/batching_sink.go#L405)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I view terminal in fatal terms :) 
Maybe rephrase the comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 20:29 UTC, miretskiy approved these changes
Giving <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> ; considering adding @rharding6373 to review this code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-:-Np1J4ecDSa6nH0yfDms:bx872kg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava)



<!-- Sent from Reviewable.io -->

2024-01-25 22:26 UTC, rharding6373 reviewed
I left a handful of educational questions. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-:-Np1ifF-CrFU2BHyJw0O:b4shw3l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @miretskiy)

___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 129 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1hz8t4snS1P9V02Co:-Np1hz8t4snS1P9V02Cp:biuu1xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L129)):*
> ```Go
> 	a *quotapool.IntAlloc
> 
> 	// If the request conflicts with in-flight requests, this is the time at
> ```

Clarification question: The time is always updated when placed in the queue, right? Is the part of this comment about conflicts the intended use case for `pendingQueueAdmitTime`?
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1fgfhBo2gt7x6BC3X:-Np1fgfhBo2gt7x6BC3Y:b-fic823) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L159)):*
> ```Go
> // requestQuota is the number of requests which can be admitted into the
> // parallelio system before blocking the producer.
> var requestQuota = settings.RegisterIntSetting(
> ```

Why does this setting live here instead of changefeedbase/settings.go?
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 345 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1cpyjCtCvLpfr9B0V:-Np1cpyjCtCvLpfr9B0W:b-rma6uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L345)):*
> ```Go
> 		// Copy the arrival time for the metrics recorder below.
> 		// Otherwise, it would be possible for res to be admitted to the
> 		// resultCh and freed before we read rec.arrivalTime.
> ```

Off topic but for my education, what is `rec.arrivalTime`?


<!-- Sent from Reviewable.io -->

2024-01-29 21:33 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @rharding6373)

___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 129 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1hz8t4snS1P9V02Co:-NpM7Rth1RXFrP3-AfSg:b9pn58g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L129)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Clarification question: The time is always updated when placed in the queue, right? Is the part of this comment about conflicts the intended use case for `pendingQueueAdmitTime`?
</blockquote></details>

Yes, the time is written when the request is placed in the queue. The pending queue is for requests which cannot immediately be emitted.
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 159 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1fgfhBo2gt7x6BC3X:-NpM76cm6vdj1AroVrjA:brhszno) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L159)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why does this setting live here instead of changefeedbase/settings.go?
</blockquote></details>

Repeating Yev's answer - we don't have hard rule on this. Public settings can go in settings.go, private ones can go close to their call site / use site.
___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 345 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1cpyjCtCvLpfr9B0V:-NpM7bC9Dwc-5CWEiDr7:bpuzf6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L345)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Off topic but for my education, what is `rec.arrivalTime`?
</blockquote></details>

Ah. This is a typo. It should be `pendingQueueAdmitTime`. I renamed it in this change. Thanks for catching it.


<!-- Sent from Reviewable.io -->

2024-01-29 21:34 UTC, jayshrivastava reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117692)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @rharding6373)

___
*[`pkg/ccl/changefeedccl/parallel_io.go` line 345 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/117692#-Np1cpyjCtCvLpfr9B0V:-NpM8HvX34nvO6GTd58R:bqtwct2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5612fd58065b3050a28fa8a1fc297f44fb08888f/pkg/ccl/changefeedccl/parallel_io.go#L345)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Ah. This is a typo. It should be `pendingQueueAdmitTime`. I renamed it in this change. Thanks for catching it.
</blockquote></details>

Correction* it should be resultTime


<!-- Sent from Reviewable.io -->

2024-01-29 22:05 UTC, jayshrivastava commented
The throughput of the sink looks good 
<img width="501" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/90ffc411-c512-41e3-96da-4cae89b8674c">

The fact that the keys are capping at 3000 likely means that throttling is kicking in.
<img width="438" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/fa0c9693-a701-49ea-a949-291391c728f3">
 It's very spiky... Probably because of the config below. 

<img width="628" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/20427431-0058-4651-a40b-d04422bcd242">

2024-01-29 22:12 UTC, jayshrivastava commented
bors r+

2024-01-29 22:12 UTC, jayshrivastava commented
https://grafana.testeng.crdb.io/d/crdb-console-changefeeds-byname/crdb-console-changefeeds-by-test-run-and-name?from=1706565131061&to=1706566358334&var-DS_PROMETHEUS=Prometheus&var-test_run_id=jayants-1706564753&var-test_name=cdc-pubsub-sink&var-cluster=&orgId=1

2024-01-29 23:24 UTC, merged