sql: support copy encoding utf8 syntax
cockroachdb/cockroach pull request #118010
Opened 2024-01-20 13:28 UTC by lpessoa

Fixes #114200

Adding support to  the ENCODING option for COPY.
- Included ENCODING in grammar file.
- Processing parsed value and validating it is set to UTF8
- Removed Unimplemented syntax tessts

2024-01-20 13:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/118010)
<!-- Reviewable:end -->

2024-01-22 17:16 UTC, rafiss requested changes
thanks for your contribution! my  comments are minor

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118010#-:-NomA8hv9n2i6G1vgUEE:b-io6yo4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lpessoa)

___
*[`pkg/sql/copy_from.go` line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118010#-Nom8Zsx0-RI3dJwbari:-Nom8Zsx0-RI3dJwbarj:b68zlir) ([raw file](https://github.com/cockroachdb/cockroach/blob/06685a232c19d12bcefddb4d91f3d893e03553bd/pkg/sql/copy_from.go#L105)):*
> ```Go
> 		format:          opts.CopyFormat,
> 		csvExpectHeader: opts.Header,
> 		encoding:        "utf8",
> ```

i don't think encoding should be set here. it should be below (see next comment)
___
*[`pkg/sql/copy_from.go` line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118010#-Nom8xPWE2S6lTJ43PHs:-Nom8xPWE2S6lTJ43PHt:b-bsv0p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/06685a232c19d12bcefddb4d91f3d893e03553bd/pkg/sql/copy_from.go#L196)):*
> ```Go
> 		if strings.ToUpper(e) != "UTF8" {
> 			return c, pgerror.New(pgcode.FeatureNotSupported, "only 'utf8' ENCODING is supported")
> 		}
> ```

there should be a line here like:
```
c.encoding = e
```
___
*[`pkg/sql/sem/tree/copy.go` line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118010#-Nom894IBDrSLPrw_0vb:-Nom894IBDrSLPrw_0vc:bwzxdvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/06685a232c19d12bcefddb4d91f3d893e03553bd/pkg/sql/sem/tree/copy.go#L65)):*
> ```Go
> 	Header      bool
> 	Quote       *StrVal
> 	Encoding    Expr
> ```

i think this would be simpler as `*StrVal`. i don't see a need to support arbitrary expressions here, since this should always just be a string
___
*[`pkg/sql/parser/parse_test.go` line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118010#-Nom98XAEcvkg0urGpY0:-Nom98XAEcvkg0urGpY1:b-9deada) ([raw file](https://github.com/cockroachdb/cockroach/blob/06685a232c19d12bcefddb4d91f3d893e03553bd/pkg/sql/parser/parse_test.go#L350)):*
> ```Go
> 
> 		{`COPY t FROM STDIN OIDS`, 41608, `oids`, ``},
> 		{`COPY t FROM STDIN FREEZE`, 41608, `freeze`, ``},
> ```

can you also add additional tests in: pkg/sql/parser/testdata/copy

you can update the test expectations by using: `./dev test pkg/sql/parser -f=TestParseDatadriven/copy --rewrite`


<!-- Sent from Reviewable.io -->

2024-01-23 12:59 UTC, lpessoa commented
Thanks for the feedback @rafiss. No sure if I understood this part `you can update the test expectations by using: ./dev test pkg/sql/parser -f=TestParseDatadriven/copy --rewrite`. Do I have to fill up testdata with the copy scenarios and then run the command?

2024-01-24 05:00 UTC, rafiss commented
> Do I have to fill up testdata with the copy scenarios and then run the command?

yeah that's how to do it. i'd recommend adding a few lines like this:
```
parse
COPY "copytab" FROM STDIN (ENCODING 'utf8')
----

parse
COPY "copytab" FROM STDIN (HEADER true, ESCAPE '%', ENCODING 'utf8')
----
```

then running `./dev test pkg/sql/parser -f=TestParseDatadriven/copy --rewrite`

2024-01-29 21:48 UTC, rafiss approved these changes
thanks for your contribution!

bors r+

2024-01-29 22:41 UTC, merged