comparator: Skip `VALIDATE CONSTRAINT` stmt
cockroachdb/cockroach pull request #118247
Opened 2024-01-23 20:36 UTC by Xiang-Gu

`VALIDATE CONSTRAINT` stmt is supported both in LSC and DSC. However, due to implementation detail differences, after the validation, the constraint will have a new constraintID in DSC, whereas the constraint retains the old constraintID in LSC. This has unfortunately come to affect our descriptor state identity check which compares the string output of `SHOW CREATE t` and the *order* of constraints depends on the constraintID, causing a potential descriptor state mismatch.

This commit fixes this issue by skipping VALIDATE CONSTRAINT stmt. Some alternative solution considered are: 1. force this `VALIDATE CONSTRAINT` stmt to be executed in LSC (or DSC) only; 2. bake in this difference into the descriptor identity check. I didn't think of a way to do approach 1 yet, but approach 2 would need careful and possibly a great amount of rewriting. Thus, I decided to go with skipping as a stop gas solution.

Informs #113366
Release note: None

2024-01-23 20:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/118247)
<!-- Reviewable:end -->

2024-01-24 19:01 UTC, fqazi requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118247)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/sctest/comparator.go` line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118247#-Nowq7s5-BGYfzqKMOMA:-Nowq7s5-BGYfzqKMOMB:be1ne17) ([raw file](https://github.com/cockroachdb/cockroach/blob/5703b0000264394bef79dccb0a5bb593af4d5b28/pkg/sql/schemachanger/sctest/comparator.go#L552)):*
> ```Go
> 			nonValidateConstraintCmds := make([]tree.AlterTableCmd, 0)
> 			for _, cmd := range atCmd.Cmds {
> 				if _, ok := cmd.(*tree.AlterTableValidateConstraint); !ok {
> ```

Just playing devils advocated here, but can't just sort these on named or something? It seems about equal work as removing them almost.


<!-- Sent from Reviewable.io -->

2024-01-24 19:28 UTC, fqazi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118247#-:-NowwQOX6i5bM-TQCq6E:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118247#-Noww0XW5Rznl_mpYQCI):*
*gap
___
*[`pkg/sql/schemachanger/sctest/comparator.go` line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118247#-Nowq7s5-BGYfzqKMOMA:-Noww1gsE4H0JfbUjUDe:b-fav1ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/5703b0000264394bef79dccb0a5bb593af4d5b28/pkg/sql/schemachanger/sctest/comparator.go#L552)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just playing devils advocated here, but can't just sort these on named or something? It seems about equal work as removing them almost.
</blockquote></details>

Nevermind, this modifies the input, not the output I got thrown off looking at the code.


<!-- Sent from Reviewable.io -->

2024-01-25 16:00 UTC, Xiang-Gu commented
TFTR!

bors r+

2024-01-25 17:54 UTC, merged