sql: add a error pgcode to circular dependency restriction #108223
cockroachdb/cockroach pull request #118583
Opened 2024-02-01 16:54 UTC by zyf123123

sql: add a error pgcode to circular dependency restriction #108223
This PR adds a PostgreSQL error code to the test case, along with changes in logictest.
Please review this PR and let me know if any further changes or adjustments are required.

2024-02-01 16:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/118583)
<!-- Reviewable:end -->

2024-02-13 21:04 UTC, rafiss requested changes
thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118583#-:-NqZHAi81xArzeJPm3iC:b3akoa5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @zyf123123)

___
*[`.DS_Store` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118583#-NqZH7Nq9LUdBxigc7Nl:-NqZH7Nq9LUdBxigc7Nm:b-tiui3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/547cbc575bff0a0393a5fc19b8e793b1d070205a/.DS_Store#L0)):*
make sure to remove this file from your commit
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118583#-NqZGelZ3YaOEQipLkb_:-NqZGelZ3YaOEQipLkba:b6npyl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/547cbc575bff0a0393a5fc19b8e793b1d070205a/pkg/sql/catalog/funcdesc/func_desc.go#L557)):*
> ```Go
> 	for _, dep := range desc.DependsOn {
> 		if dep == id {
> 			return pgerror.Newf(pgcode.UndefinedColumn,
> ```

i don't think `UndefinedColumn` is the right code to use here. let's use `InvalidFunctionDefinition`
___
*[`pkg/sql/catalog/funcdesc/func_desc.go` line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118583#-NqZH4qCE89vWEi6jAef:-NqZH4qCE89vWEi6jAeg:bbxw7hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/547cbc575bff0a0393a5fc19b8e793b1d070205a/pkg/sql/catalog/funcdesc/func_desc.go#L601)):*
> ```Go
> 	for _, dep := range desc.DependsOn {
> 		if dep == id {
> 			return pgerror.Newf(pgcode.UndefinedColumn,
> ```

let's use `InvalidFunctionDefinition`


<!-- Sent from Reviewable.io -->

2024-02-14 02:33 UTC, zyf123123 commented
Thank you for your review! I have made changes to the files in response to your feedback.

2024-02-14 15:21 UTC, rafiss approved these changes
lgtm! thanks for your work

bors r+

2024-02-14 16:28 UTC, merged