admission,ui: add graphs for elastic cpu limiter
cockroachdb/cockroach pull request #118763
Opened 2024-02-05 16:53 UTC by aadityasondhi

This patch adds two new graphs to the Overload page in the metrics dashboard:

* `Elastic CPU Utilization`: graphs `admission.elastic_cpu.utilization` against `admission.elastic_cpu.utilization_limit`.
* `Elastic CPU Exhausted Duration Per Second`: graphs `elastic_cpu.nanos_exhausted_duration`.

Fixes #118493.

Release note (ui change): The Overload Dashboard page now includes two additional graphs:
- Elastic CPU Utilization - This is used the show the CPU utilization by elastic work, compared to the limit set for elastic work.
- Elastic CPU Exhausted Duration Per Second - This is used to show the duration of CPU exhastion by elastic work, in microseconds.

2024-02-05 16:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/118763)
<!-- Reviewable:end -->

2024-02-06 15:00 UTC, sumeerbhola requested changes
can you do a quick run of the admission_control_elastic_backup and add some screenshots of what the new graphs look like?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-:-NpyvNo14I-I4bUWgDJL:b74a3kj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-Npyv2SvEEMethTWq4uj:-Npyv2SwA3WmuN3kVLWD:b-l1x33i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3739db5466a0f1c72fd5313ad0542176d10365/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L101)):*
> ```XML
>           <>
>             <Metric
>               key={nid}
> ```

just curious: the "CPU Percent" graph above doesn't have the `key={nid}` or the `downsampleMax`. What does the former do? And what made it necessary to specify the downsampling scheme for this graph?


<!-- Sent from Reviewable.io -->

2024-02-06 19:47 UTC, aadityasondhi reviewed
Yeah sorry, I meant to add the screenshots but forgot.

![image.png](https://files.reviewableusercontent.io/images/reviewable/20070511/ejNmZbstKpZc7JJMPVxuXPhk/image.png)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-:-NpzuFrb5jhWhR4tz667:b-mb53sb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-Npyv2SvEEMethTWq4uj:-NpztShB-oRhrAbxPndZ:b3n24xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3739db5466a0f1c72fd5313ad0542176d10365/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just curious: the "CPU Percent" graph above doesn't have the `key={nid}` or the `downsampleMax`. What does the former do? And what made it necessary to specify the downsampling scheme for this graph?
</blockquote></details>

Thanks for the callout. As for the `key={nid}`,  it seems to be unnecessary based on internal convo. `downsampleMax` was a copy-paste from elsewhere, should be the same as the CPU percent graph.

Removed both.


<!-- Sent from Reviewable.io -->

2024-02-06 19:47 UTC, aadityasondhi commented
Currently running the backup roachtest here: http://aadityasondhi-elastic-cpu-gce-0001.roachprod.crdb.io:26258/#/metrics/overload/cluster?start=1707246976&end=1707248776.

2024-02-06 19:49 UTC, aadityasondhi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118763)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-Npyv2SvEEMethTWq4uj:-NpzxqGk5-80Z9fzvVp_:be5wa8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3739db5466a0f1c72fd5313ad0542176d10365/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L101)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Thanks for the callout. As for the `key={nid}`,  it seems to be unnecessary based on internal convo. `downsampleMax` was a copy-paste from elsewhere, should be the same as the CPU percent graph.

Removed both.
</blockquote></details>

Link to internal convo: https://cockroachlabs.slack.com/archives/C063CP41TG9/p1707244117005589


<!-- Sent from Reviewable.io -->

2024-02-07 15:54 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118763#-:-Nq3Go81AiGPWRUIRZ6q:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-02-07 17:12 UTC, merged