release-23.2: roachtest: print issue number after test failure
cockroachdb/cockroach pull request #119021
Opened 2024-02-09 18:35 UTC by renatolabs

Backport 1/1 commits from #118914.

/cc @cockroachdb/release

---

This commit updates the GitHub issue poster so that information about
the issue is returned when an issue is created or a comment
added. The roachtest test runner uses this information in the TeamCity
output so that we can easily see the issue corresponding to a test
failure directly in the TC overview page.

Epic: none

Release note: None

Release justification: test only changes.

2024-02-09 18:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/119021)
<!-- Reviewable:end -->

2024-02-12 17:08 UTC, herkolategan requested changes
Should we backport this https://github.com/cockroachdb/cockroach/pull/119019 with this change as well?

2024-02-12 17:28 UTC, renatolabs commented
> Should we backport this #119019 with this change as well?

I missed that, thanks!

2024-02-12 17:35 UTC, herkolategan approved these changes

2024-02-12 18:16 UTC, merged