server: fix TestStructuredEventLogging test
cockroachdb/cockroach pull request #119728
Opened 2024-02-28 16:19 UTC by koorosh

Before, `TestStructuredEventLogging` test could fail because of following potential problems:
- it used `FlushFiles()` async function to ensure that logs are persisted, and it wasn't guaranteed that validation of results is done after flushing completed.
- it used 10 seconds interval to wait for logs to persist, and `DefaultMetricsSampleInterval` is also equals to 10 seconds so there's a chance that logs won't be persisted before validation.

Current change introduces:
- new testing knob to override default metrics sample interval and use it in test. It doesn't fix an issue directly, but allows to reduce time for test execution and also increase time to wait until logs persisted.
- `log.FlushAllSync` used instead of `log.FlushFiles` to persist logs synchronously.

Related issue: https://github.com/cockroachdb/cockroach/issues/119363
Related issue: https://github.com/cockroachdb/cockroach/issues/117735

Release note: None

2024-02-28 16:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/119728)
<!-- Reviewable:end -->

2024-02-29 14:56 UTC, dhartunian requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119728)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @koorosh, and @xinhaoz)

___
*[`pkg/server/server.go` line 1884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-NrpMAj4D_L0RElwqRik:-NrpMAj4D_L0RElwqRil:b-9bhzgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d159cff6943d1f11374f30fac0f8ea714eb101e2/pkg/server/server.go#L1884)):*
> ```Go
> 	metricsSampleInterval := base.DefaultMetricsSampleInterval
> 
> 	if serverKnobs := s.cfg.TestingKnobs.Server; serverKnobs != nil {
> ```

I'd prefer to add knobs to the `env_sampler` package instead of complicating `server.go` with more knobs and conditional logic.
___
*[`pkg/server/tenant.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-NrpMKAJB02xP4KtHeMn:-NrpMKAJB02xP4KtHeMo:b-wvxvto) ([raw file](https://github.com/cockroachdb/cockroach/blob/d159cff6943d1f11374f30fac0f8ea714eb101e2/pkg/server/tenant.go#L678)):*
> ```Go
> 	if serverKnobs := s.cfg.TestingKnobs.Server; serverKnobs != nil {
> 		if serverKnobs.(*TestingKnobs).MetricsSampleInterval != time.Duration(0) {
> 			metricsSampleInterval = serverKnobs.(*TestingKnobs).MetricsSampleInterval
> ```

This is a good example of why I'd prefer to the logic to stay in the sampler, then we don't have to duplicate code that can get out of sync in tenant and server.


<!-- Sent from Reviewable.io -->

2024-03-01 12:13 UTC, stevendanna commented
I removed the MT and server required reviews. But I agree with @dhartunian comment that it would be nice to move the logic to a place where we don't need it duplicated in server.

2024-03-04 13:43 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119728)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @xinhaoz)

___
*[`pkg/server/server.go` line 1884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-NrpMAj4D_L0RElwqRik:-Ns8h08dAL0SoG4jFOu7:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d159cff6943d1f11374f30fac0f8ea714eb101e2/pkg/server/server.go#L1884)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'd prefer to add knobs to the `env_sampler` package instead of complicating `server.go` with more knobs and conditional logic.
</blockquote></details>

Done. 
___
*[`pkg/server/tenant.go` line 678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-NrpMKAJB02xP4KtHeMn:-Ns8h4kV-zLzAfOdaWtD:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/d159cff6943d1f11374f30fac0f8ea714eb101e2/pkg/server/tenant.go#L678)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This is a good example of why I'd prefer to the logic to stay in the sampler, then we don't have to duplicate code that can get out of sync in tenant and server.
</blockquote></details>

Ack


<!-- Sent from Reviewable.io -->

2024-03-04 19:07 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just a naming nit, and a suggestion to use a test hook instead, if you want.

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-:-Ns9qGCR0T1wtnQKxFlv:b-6bx6ht)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @koorosh, and @xinhaoz)

___
*[`pkg/server/env_sampler.go` line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-Ns9qmOjAQ-gUymA1Dg2:-Ns9qmOjAQ-gUymA1Dg3:bo5nqm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5dc1b144910f123f13b50a15c8b3cfa461b065/pkg/server/env_sampler.go#L59)):*
> ```Go
> 	testingKnobs base.TestingKnobs,
> ) error {
> 	metricsSampleInterval := base.DefaultMetricsSampleInterval
> ```

Have you considered using `testutils.TestingHook` to set `base.DefaultMetricsSampleInterval` and then reset after the test? Then you can avoid making a testing knob entirely.
___
*[`pkg/server/testing_knobs.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-Ns9pDzg6Lg-qlbnT4Ho:-Ns9pDzg6Lg-qlbnT4Hp:b-btlrct) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5dc1b144910f123f13b50a15c8b3cfa461b065/pkg/server/testing_knobs.go#L177)):*
> ```Go
> 
> 	// MetricsSampleInterval overrides base.DefaultMetricsSampleInterval when used to construct sampleEnvironmentCfg.
> 	MetricsSampleInterval time.Duration
> ```

nit: can you change the name to `EnvironmentSampleInterval`? It makes it more clear that this interval is just for env sampling. Otherwise it's too ambiguous what this means.  It collects more than just metrics, so I don't think it should have the Metrics name in it.


<!-- Sent from Reviewable.io -->

2024-03-06 11:25 UTC, koorosh reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-:-NsIUyUI13yfj8YZZq6z:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, and @xinhaoz)

___
*[`pkg/server/env_sampler.go` line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-Ns9qmOjAQ-gUymA1Dg2:-NsIUIkS1-Ti6ukp9neo:b-8xsdsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5dc1b144910f123f13b50a15c8b3cfa461b065/pkg/server/env_sampler.go#L59)):*
Unfortunately, `base.DefaultMetricsSampleInterval` is a `const` and cannot be changed with this hook. 
It also has such comment for `DefaultMetricsSampleInterval`:
> // NB: this can't easily become a variable as the UI hard-codes it to 10s.  
> // See https://github.com/cockroachdb/cockroach/issues/20310.
___
*[`pkg/server/testing_knobs.go` line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119728#-Ns9pDzg6Lg-qlbnT4Ho:-NsIUvlx6s_WZcEX9emd:bg583c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a5dc1b144910f123f13b50a15c8b3cfa461b065/pkg/server/testing_knobs.go#L177)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can you change the name to `EnvironmentSampleInterval`? It makes it more clear that this interval is just for env sampling. Otherwise it's too ambiguous what this means.  It collects more than just metrics, so I don't think it should have the Metrics name in it.
</blockquote></details>

Done. Thanks for suggestion!


<!-- Sent from Reviewable.io -->

2024-03-06 20:00 UTC, koorosh commented
bors r+

2024-03-06 21:09 UTC, merged