release-23.2: sql: set locality for all tables on MR system database
cockroachdb/cockroach pull request #119965
Opened 2024-03-05 22:03 UTC by fqazi

Previously, table locality was set for only a subset of system tables, and the upgrade logic lacked the ability to set locality for newly created tables. This caused upgrades to version 24.1 on multi-region (MR) clusters to fail due to new tables lacking locality settings. To address this, the upgrade logic now consistently sets locality when creating system tables. Additionally, the optimization logic for system databases sets global locality as the default for new tables.

Epic: CC-24173
Fixes: #119948
Release note: None

2024-03-05 22:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/119965)
<!-- Reviewable:end -->

2024-03-06 13:15 UTC, JeffSwenson approved these changes
LGTM

2024-03-06 13:16 UTC, JeffSwenson commented
I'll produce a custom release for the Serverless MR host clusters that contains this change once it is merged.

2024-03-07 15:58 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119965)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsObInG22eVJQgqsprq):*
this says 24.1, but is it supposed to be 23.2?
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsOcZLWAnVC2Vjm5A9v):*
"Additionally, the optimization logic for system databases sets global locality as the default for new tables." that doesn't seem true, it uses regional tables by default right?
___
*[`pkg/sql/region_util.go` line 2476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsObaFs9t-oGtMuaP03:-NsObaFs9t-oGtMuaP04:b-67423b) ([raw file](https://github.com/cockroachdb/cockroach/blob/126864e60f3491bd53eb47417b2040ce7a724a0f/pkg/sql/region_util.go#L2476)):*
> ```Go
> 		"table_statistics":       {},
> 		"web_sessions":           {},
> 		"region_liveness":        {},
> ```

super nit: all of these strings are constants in the `catconstants` package, so we could use those
___
*[`pkg/sql/region_util.go` line 2608 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsObv9o7EVPFarCHL5Z:-NsObv9o7EVPFarCHL5_:biehaq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/126864e60f3491bd53eb47417b2040ce7a724a0f/pkg/sql/region_util.go#L2608)):*
> ```Go
> 		// Some system tables only come into effect once the
> 		// version changes, so skip over those.
> 		if sqlerrors.IsUndefinedRelationError(err) {
> ```

nit: would it be better to be explicit here? we could add a `version.IsActive` check, and only skip the tables we know are created during upgrade. if we get errors for other tables, then this should return an error
___
*[`pkg/sql/region_util.go` line 2638 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsOcA5ADI082mCq9HAQ:-NsOcA5ADI082mCq9HAR:b-ediuhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/126864e60f3491bd53eb47417b2040ce7a724a0f/pkg/sql/region_util.go#L2638)):*
> ```Go
> 		descriptor, err := getDescriptor(tableName)
> 		// Some system tables only come into effect once the
> 		// version changes, so skip over those.
> ```

nit: same as above, should we use `IsActive`?


<!-- Sent from Reviewable.io -->

2024-03-07 17:43 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119965)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsObInG22eVJQgqsprq):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this says 24.1, but is it supposed to be 23.2?
</blockquote></details>

Done.
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsOcZLWAnVC2Vjm5A9v):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

"Additionally, the optimization logic for system databases sets global locality as the default for new tables." that doesn't seem true, it uses regional tables by default right?
</blockquote></details>

Done.

Ugh...yeah its regional by table.
___
*[`pkg/sql/region_util.go` line 2476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-NsObaFs9t-oGtMuaP03:-NsOnuLS4yV3-l2QCe4u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/126864e60f3491bd53eb47417b2040ce7a724a0f/pkg/sql/region_util.go#L2476)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: all of these strings are constants in the `catconstants` package, so we could use those
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-07 17:58 UTC, rafiss approved these changes
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119965#-:-NsP3Lt69u04iwU2QcRr:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-07 20:27 UTC, merged

2024-03-07 22:09 UTC, rafiss commented
blathers backport 23.2.3-rc