sql, security: use values from the SUBJECT role option to match again…
cockroachdb/cockroach pull request #119958
Opened 2024-03-05 20:44 UTC by souravcrl

…st a client

certificate for a user

informs #110616
fixes CRDB-35940
Epic CRDB-34126

Release note (enterprise change): We use values from SUBJECT role option to match against a client certificate for a user. The client certificate in X.509 standard contains a subject which represents an X.509 DN. We use the RFC 2253 parsed string from this representation to be used as an LDAP DN subject in the client `CertificateUserScope` object while evaluating the certificate for auth. Thus, in `UserAuthCertHook` we will be evaluating both for the cert scope userName to match the db user and cert scope subject to match the set subject role option.

2024-03-05 20:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/119958)
<!-- Reviewable:end -->

2024-03-12 08:52 UTC, bdarnell reviewed
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nsl1zcG8JAmemjgA7Tw):*
We only want one release note for this series of changes, and Rafi already put one in #119135. I think we should just say `Release note: None` for this one (Keep the rest of the text, but as the body of the commit message instead of the release note). 

Wrap the lines in the commit message at 80 columns. The first line can't be wrapped so just shorten it to fit. Something like "sql,security: Match certificate DN against SUBJECT role option". 
___
*[`pkg/security/auth.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslnyFrENISXQ3p11XR:-NslnyFrENISXQ3p11XS:b-98ra3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L43)):*
> ```Go
> // authenticate on any tenant strictly for backward compatibility with the
> // older certificates.
> type CertificateUserScope struct {
> ```

Add a comment about the overall data model:

A certificate must specify the SQL user name in either the CN or a DNS SAN entry, so one certificate has multiple candidate usernames. Additionally, if the subject role option is set, the cert's subject must match it (each cert has exactly one subject). The GetCertificateUserScope function expands a cert into a set of "scopes" with each possible username (and tenant ID), with the same subject in each scope. 
___
*[`pkg/security/auth.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NsllyMq0jl56-rEgvzL:-NsllyMq0jl56-rEgvzM:bfefg1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L119)):*
> ```Go
> 	_, err := asn1.Unmarshal(cert.RawSubject, &RDNSeq)
> 	if err != nil {
> 		RDNSeq = cert.Subject.ToRDNSequence()
> ```

When would it happen that we can't parse RawSubject but the cert itself has a Subject? 

If we do fall back to the Subject, we lose the original order, right? This needs a comment. 
___
*[`pkg/security/auth.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslnGbU0K-vrGmiKwUF:-NslnGbU0K-vrGmiKwUG:b-aemh85) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L122)):*
> ```Go
> 	}
> 
> 	slices.Reverse(RDNSeq)
> ```

I'm concerned that if the libraries default to the "reverse" order, there may be confusion if we aren't using the same order as the library internals. Should we leave it in the original format here and only reverse it when we're generating or parsing the human-readable form?
___
*[`pkg/security/auth.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslmIBf7Rr9FI_1w7Xy:-NslmIBf7Rr9FI_1w7Xz:b-79f285) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L129)):*
> ```Go
> 
> 	const (
> 		encodedUserID          = "0.9.2342.19200300.100.1.1"
> ```

Add a comment:

Go only parses a subset of the possible fields in a DN (https://github.com/golang/go/issues/25667). We add the remaining ones defined in section 3 of RFC 4514 (https://datatracker.ietf.org/doc/html/rfc4514#section-3)
___
*[`pkg/sql/pgwire/auth.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nsl3dCNBRoq9RTWZgqF:-Nsl3dCNBRoq9RTWZgqG:b-n4wofb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/sql/pgwire/auth.go#L165)):*
> ```Go
> 	}
> 	c.sessionArgs.IsSuperuser = isSuperuser
> 	c.sessionArgs.RoleSubject = subject
> ```

Is there a reason why you're putting RoleSubject in the SessionArgs? I'd expect it to be treated like pwRetrievalFn and passed as an argument to the authentication function but not saved in the session.
___
*[`pkg/security/auth_test.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nslq3XOE3QrSdd_7esI:-Nslq3XOE3QrSdd_7esJ:b93vi73) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L43)):*
> ```Go
> // "foo" creates a single peer certificate with the CommonName "foo". The spec
> // "foo,dns:bar,dns:blah" creates a single peer certificate with the CommonName "foo" and a
> // DNSNames "bar" and "blah". "(OU=Tenants)foo,dns:bar" creates a single
> ```

There's only one use of this parenthesized format in this file. I think it would be nice to move CN=foo into the parens instead of the special case that it has now. 
___
*[`pkg/security/auth_test.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslpYUi-CLP6hpJHddq:-NslpYUi-CLP6hpJHddr:bwb1ufv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L76)):*
> ```Go
> 				CommonName:         names[0],
> 				Organization:       subjectDN["O"],
> 				OrganizationalUnit: subjectDN["OU"],
> ```

This should probably panic if there is anything in DN besides O and OU (or we could use our parsing function to construct the pkix.Name)
___
*[`pkg/security/auth_test.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslpFWbBbQK8zJfpecr:-NslpFWbBbQK8zJfpecs:b-vbheip) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L78)):*
> ```Go
> 				OrganizationalUnit: subjectDN["OU"],
> 			}
> 			peerCert.RawSubject, _ = asn1.Marshal(peerCert.Subject)
> ```

We never want to ignore an error. In a test like this it's ok to panic if marshalling fails. 
___
*[`pkg/security/auth_test.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslqeTj9XiaMTOhzRY3:-NslqeTj9XiaMTOhzRY4:bcgir25) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L336)):*
> ```Go
> 		// Secure mode, client cert having full DN, foo user with subject role option set, subject role option string != TLS DN.
> 		{false, "foo", fooUser, "", true, false, false, roachpb.MustMakeTenantID(123),
> 			true, `certificate authentication failed for user "foo"`},
> ```

The most important part of this change is that certificates with mismatched subjects are not accepted, so we need more negative tests. We've shown here that an empty subject is not accepted if the role option is set, but we should have more tests involving at least two different DNs to show that partial matches aren't allowed (should consider DNs which differ only in one of the fields, and where the set of fields in one DN is a subset of the fields in the other). 


<!-- Sent from Reviewable.io -->

2024-03-14 19:11 UTC, rafiss requested changes
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-NsyMyQH50lUR3KyD8jY:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @souravcrl)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nsl1zcG8JAmemjgA7Tw):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We only want one release note for this series of changes, and Rafi already put one in #119135. I think we should just say `Release note: None` for this one (Keep the rest of the text, but as the body of the commit message instead of the release note). 

Wrap the lines in the commit message at 80 columns. The first line can't be wrapped so just shorten it to fit. Something like "sql,security: Match certificate DN against SUBJECT role option".
</blockquote></details>

One other thing to clarify for future release notes you write: these notes should be written with our users as the intended audience. That means we shouldn't put details like function names or implementation details in the release note. Instead, the release note should describe product behavior. The details you have are good for the part of the commit message before the release note. (See guidelines here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes)
___
*[`pkg/security/auth.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NsyMO9_5HBvNF1hXqwa:-NsyMO9_5HBvNF1hXqwb:b-zbpiie) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L266)):*
> ```Go
> 
> // formatSubjectDN returns a formatted subject distinguished name
> func formatSubjectDN(subject *ldap.DN) string {
> ```

you shouldn't need this `formatSubjectDN` function. the string formatting logic is smart enough to handle nils, so above you can do:
```
		return errors.WithDetailf(
			errors.Errorf(
				"certificate authentication failed for user %q (DN: %s)",
				systemIdentity,
				roleSubject,
			),
			"The client certificate is valid for %s.", FormatUserScopes(certUserScope),
		)
```


<!-- Sent from Reviewable.io -->

2024-03-15 20:37 UTC, souravcrl reviewed
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-Nt2pGTV3TqTMZ4m2DJX:bb72pd0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @rafiss)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nsl1zcG8JAmemjgA7Tw):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

One other thing to clarify for future release notes you write: these notes should be written with our users as the intended audience. That means we shouldn't put details like function names or implementation details in the release note. Instead, the release note should describe product behavior. The details you have are good for the part of the commit message before the release note. (See guidelines here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes)
</blockquote></details>

done
___
*[`pkg/security/auth.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslnyFrENISXQ3p11XR:-Nt-hKnV5k4EA-0yXHOr:bbu8ie5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L43)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add a comment about the overall data model:

A certificate must specify the SQL user name in either the CN or a DNS SAN entry, so one certificate has multiple candidate usernames. Additionally, if the subject role option is set, the cert's subject must match it (each cert has exactly one subject). The GetCertificateUserScope function expands a cert into a set of "scopes" with each possible username (and tenant ID), with the same subject in each scope.
</blockquote></details>

done. I have removed generated subject DN from here since the scope userName and subject CN may not match. Thus having the subject DN here is confusing.
___
*[`pkg/security/auth.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NsllyMq0jl56-rEgvzL:-NsyM62r13vJmKJdAXm3:b-ccso8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L119)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

When would it happen that we can't parse RawSubject but the cert itself has a Subject? 

If we do fall back to the Subject, we lose the original order, right? This needs a comment.
</blockquote></details>

I will be returning an error here. Actually `x509.Certificate` library uses `asn1.Unmarshal` internally and then `cert.Subject.FillFromRDNSequence()` to generate subject, so without `cert.RawSubject` being set, we won't have a subject. Incidentally, this case arose because in the tests we were earlier directly setting the subject field without setting rawSubject which will not be the case if are parsing from a certificate file. Fixed the test suite as well to reflect this now.

The problem lies with `Subject.ToRDNSequence()` which reverses the order and moves non parseable fields to the end which won't be required here.
___
*[`pkg/security/auth.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslnGbU0K-vrGmiKwUF:-NsyOlhPA45N3caZXRo_:buhsi0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L122)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm concerned that if the libraries default to the "reverse" order, there may be confusion if we aren't using the same order as the library internals. Should we leave it in the original format here and only reverse it when we're generating or parsing the human-readable form?
</blockquote></details>

This is required because `RDNSeq.String()` also reverses the order of fields. The x509 library possibly intended to use `cert.Subject.ToRDNSequence` and `RDNSequence.String()` in succession which is done in the library function `cert.Subject.String()`. I have left a comment detailing this.
___
*[`pkg/security/auth.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslmIBf7Rr9FI_1w7Xy:-NsyRK-gAX_daHz2SKbp:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L129)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Add a comment:

Go only parses a subset of the possible fields in a DN (https://github.com/golang/go/issues/25667). We add the remaining ones defined in section 3 of RFC 4514 (https://datatracker.ietf.org/doc/html/rfc4514#section-3)
</blockquote></details>

done
___
*[`pkg/security/auth.go` line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NsyMO9_5HBvNF1hXqwa:-Nt03H4BDVxbQRhqXPcT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth.go#L266)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you shouldn't need this `formatSubjectDN` function. the string formatting logic is smart enough to handle nils, so above you can do:
```
		return errors.WithDetailf(
			errors.Errorf(
				"certificate authentication failed for user %q (DN: %s)",
				systemIdentity,
				roleSubject,
			),
			"The client certificate is valid for %s.", FormatUserScopes(certUserScope),
		)
```
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nsl3dCNBRoq9RTWZgqF:-Nt0V4LJ7ejSc62mGjCZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/sql/pgwire/auth.go#L165)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is there a reason why you're putting RoleSubject in the SessionArgs? I'd expect it to be treated like pwRetrievalFn and passed as an argument to the authentication function but not saved in the session.
</blockquote></details>

done
___
*[`pkg/security/auth_test.go` line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Nslq3XOE3QrSdd_7esI:-Nt2n-9s-6q-Ce3nd5vT:b-pzc0vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L43)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

There's only one use of this parenthesized format in this file. I think it would be nice to move CN=foo into the parens instead of the special case that it has now.
</blockquote></details>

modified the implementation to have entire DN in paranthesis.
___
*[`pkg/security/auth_test.go` line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslpYUi-CLP6hpJHddq:-Nt2YQsXByG730pyQV2v:bs9xk0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L76)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should probably panic if there is anything in DN besides O and OU (or we could use our parsing function to construct the pkix.Name)
</blockquote></details>

handled that in `generateRDNSequenceFromSpecMap`.
___
*[`pkg/security/auth_test.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NslpFWbBbQK8zJfpecr:-Nt2Yc-kDLniLnYFuqsO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9b757fe8826098d84a3cbd1b122eb42ebd6aa72/pkg/security/auth_test.go#L78)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We never want to ignore an error. In a test like this it's ok to panic if marshalling fails.
</blockquote></details>

done
___
*[`pkg/security/auth_test.go` line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119 [...]

2024-03-17 16:40 UTC, bdarnell reviewed
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/security/auth.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCEHWb5NuvxJMLntGL:-NtCEHWb5NuvxJMLntGM:bg31gls) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L152)):*
> ```Go
> 				attr.Type = "DC"
> 			case commonName:
> 				attr.Value = sqlUserName
> ```

This doesn't look right. Doesn't this mean that if the cert matches the other subject fields but not CN, we'll accept it anyway?

Also, if this is necessary, there's no guarantee that the CN field exists in dn.Attributes so we might have to add one. 
___
*[`pkg/security/auth.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBzm5B9x7lSf3vuEfq:-NtBzm5B9x7lSf3vuEfr:bxh7nht) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L254)):*
> ```Go
> 		}
> 
> 		certSubject, err := generateSubjectDNSequence(peerCert, systemIdentity.Normalized())
> ```

If this can fail, maybe we should skip it if roleSubject is not set. 
___
*[`pkg/sql/exec_util.go` line 2204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBv-e_-USh0Q6F5XW9:-NtBv-e_-USh0Q6F5XWA:b9yi5jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/exec_util.go#L2204)):*
> ```Go
> 	// RoleSubject refers to subject set for a given user role. This is nil if no
> 	// subject is set for the role assigned to user
> 	RoleSubject *ldap.DN
> ```

It looks like we never set this field now and it should be removed.
___
*[`pkg/sql/pgwire/auth_methods.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBvFZE0tdx45T66dNK:-NtBvFZE0tdx45T66dNL:b-uxa2tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/pgwire/auth_methods.go#L449)):*
> ```Go
> 			execCfg.RPCContext.TenantID,
> 			cm,
> 			c.GetRoleSubject(),
> ```

This should use the new ldap.DN argument (and then the AuthConn can go back to being anonymous). 

Unless I've missed something, we never set RoleSubject in this version of the PR, so how are the tests passing?
___
*[`pkg/security/auth_test.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCH4DgCINV-qMqMoxJ:-NtCH4DgCINV-qMqMoxK:b2va4qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth_test.go#L394)):*
> ```Go
> 		// Secure mode, client cert having full DN, foo user with subject role option set matching TLS cert subject.
> 		{false, "(" + subjectDNString + ")", fooUser, "", true, true, false, roachpb.MustMakeTenantID(123),
> 			true, `user "foo" is not allowed`},
> ```

Why aren't these two allowed?


<!-- Sent from Reviewable.io -->

2024-03-17 20:10 UTC, souravcrl reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-NtD1EXjDTfeWAesxqAz:bb71pro)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @rafiss)

___
*[`pkg/security/auth.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCEHWb5NuvxJMLntGL:-NtCvchVD2rhK3LM__SS:butmvtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L152)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This doesn't look right. Doesn't this mean that if the cert matches the other subject fields but not CN, we'll accept it anyway?

Also, if this is necessary, there's no guarantee that the CN field exists in dn.Attributes so we might have to add one.
</blockquote></details>

We will be treating matching on CN field of DN as vacuous, since role option expects CN to be always equal to sqlUserName. `CertUserScope` contains the user name to be evaluated against db Name. This user name is obtained from both CN(if provided) and SAN entries after applying `cert-principal-map`. Hence that is the actual value which should match db name.

I have moved the implementation to distinguishedName package since we are generating DN here from x509 certificates which should be a common operation for the package.
___
*[`pkg/security/auth.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBzm5B9x7lSf3vuEfq:-NtCxipm2o-PqyUvVeMg:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L254)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If this can fail, maybe we should skip it if roleSubject is not set.
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth_methods.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBvFZE0tdx45T66dNK:-NtCxtDA2MxOQTgs0bSX:b-f0oxta) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/pgwire/auth_methods.go#L449)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should use the new ldap.DN argument (and then the AuthConn can go back to being anonymous). 

Unless I've missed something, we never set RoleSubject in this version of the PR, so how are the tests passing?
</blockquote></details>

updated to `roleSubject` from new ldap.DN argument

Tests are passing because the value obtained from c.GetRoleSubject() is nil and Validate function does not match roleSubject with certSubject in that case.
___
*[`pkg/security/auth_test.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCH4DgCINV-qMqMoxJ:-NtCzkQAAnLasqhRk-EN:b7hvdhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth_test.go#L394)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why aren't these two allowed?
</blockquote></details>

So for both of these test cases, we are expecting `privateHookSuccess` to be false, which means when we are calling auth, we are calling with `clientConnection` = false. In the auth fn, when this value is false, we are expecting sqlUserName to be node(otherwise it fails with error message `user is not allowed`).
___
*[`pkg/sql/exec_util.go` line 2204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBv-e_-USh0Q6F5XW9:-NtCxo9z1xo0jrSabTcM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/exec_util.go#L2204)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It looks like we never set this field now and it should be removed.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-03-18 04:51 UTC, bdarnell reviewed
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/security/auth.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCEHWb5NuvxJMLntGL:-NtEqpc92FU9oCBcqvH2:b-jh2brc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L152)):*
> We will be treating matching on CN field of DN as vacuous, since role option expects CN to be always equal to sqlUserName.

We know that the role subject matches the SQL user name, but this is the cert subject, and it's still important to match the cert CN.

> This user name is obtained from both CN(if provided) and SAN entries after applying cert-principal-map. Hence that is the actual value which should match db name.

Aha, this is the real reason - we've already matched the CN, mapped it through the principal map, and that's how we were able to load the role subject in the first place. 

So we're covered, but I think this is a confusing way to do it and I'm worried we'll break it when we add an index on the subject role option to lift the restriction that CN==sqlUsername. Especially now that it's moved to the distinguishedname package, this GenerateDN function should just be a kind of "improved parse" that fixes the UID and DC fields (maybe rename it to ParseDNFromCertificate too?). The logic that handles CN specially should probably live in ValidateUserScope. I think I'd manually compare the RDNs list and skip over the CN field if it's present instead of modifying it. 
___
*[`pkg/sql/pgwire/auth_methods.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBvFZE0tdx45T66dNK:-NtEphLcD-VvqgYOOhhm:bw8qxrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/pgwire/auth_methods.go#L449)):*
> Validate function does not match roleSubject with certSubject in that case.

But the test at `auth_test.go:399` asserts that we get an error. How was this returning an error if c.GetRoleSubject was nil?


<!-- Sent from Reviewable.io -->

2024-03-18 09:52 UTC, souravcrl reviewed
Updated `ParseDNFromCertificate` to remove handling for CN and added a `MatchDN` fn to compare 2 DN ignoring CN attribute. Added test for the same. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-NtFxzOr5N9g6fgMyswy:b-gia4y4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @rafiss)

___
*[`pkg/security/auth.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCEHWb5NuvxJMLntGL:-NtFxMrJ1oXM5pkqRHVb:b-95b7pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L152)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> We will be treating matching on CN field of DN as vacuous, since role option expects CN to be always equal to sqlUserName.

We know that the role subject matches the SQL user name, but this is the cert subject, and it's still important to match the cert CN.

> This user name is obtained from both CN(if provided) and SAN entries after applying cert-principal-map. Hence that is the actual value which should match db name.

Aha, this is the real reason - we've already matched the CN, mapped it through the principal map, and that's how we were able to load the role subject in the first place. 

So we're covered, but I think this is a confusing way to do it and I'm worried we'll break it when we add an index on the subject role option to lift the restriction that CN==sqlUsername. Especially now that it's moved to the distinguishedname package, this GenerateDN function should just be a kind of "improved parse" that fixes the UID and DC fields (maybe rename it to ParseDNFromCertificate too?). The logic that handles CN specially should probably live in ValidateUserScope. I think I'd manually compare the RDNs list and skip over the CN field if it's present instead of modifying it.
</blockquote></details>

Updated the fn name to be `ParseDNFromCertificate` and removed special handling for CN also. Also added a fn `MatchDN` which matches 2 ldap principals ignoring the CN field. I have also added a test case for verifying especially this condition when CN does not match but rest of the certificate DN matches and we have a dns which equals the roleSubject's CN.
___
*[`pkg/sql/pgwire/auth_methods.go` line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBvFZE0tdx45T66dNK:-NtFt93h7lOVNApkzRdX:br5pq6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/sql/pgwire/auth_methods.go#L449)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> Validate function does not match roleSubject with certSubject in that case.

But the test at `auth_test.go:399` asserts that we get an error. How was this returning an error if c.GetRoleSubject was nil?
</blockquote></details>

If I understood correctly, there is a `publicHookSuccess` which does cert scope and DN checking for all users and `privateHookSuccess` which does it only `node` user.  In case of `publicHookSuccess`: true, we check the return value of the hook with `clientConnection` set to true. The return value should be true. Similarly, in case of `privateHookSuccess`: true, we check the return value of the hook with `clientConnection` set to false. The return value should be true. 
In case of normal user connection(not `node` connection), `privateHookSuccess` is false and error value is `user "foo" is not allowed` obtained from hook fn itself and does not proceed to validate users scope or match roleSubject and certSubject.

In the same test we are calling the auth hook twice, once with `clientConnection` set to true and other time set to false.
___
*[`pkg/security/auth_test.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCH4DgCINV-qMqMoxJ:-NtFwfSE4OEGZ-syrwyS:b-47m4ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth_test.go#L394)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

So for both of these test cases, we are expecting `privateHookSuccess` to be false, which means when we are calling auth, we are calling with `clientConnection` = false. In the auth fn, when this value is false, we are expecting sqlUserName to be node(otherwise it fails with error message `user is not allowed`).
</blockquote></details>

In the same test we are calling the auth hook twice, once with `clientConnection` set to true and other time set to false.


<!-- Sent from Reviewable.io -->

2024-03-18 16:56 UTC, bdarnell reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/security/auth.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBzm5B9x7lSf3vuEfq:-NtG3X1Y6xrGZ-9lENaI:ban15pk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L254)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

done
</blockquote></details>

Parsing the DN but ignoring the error if roleSubject is nil seems odd; it seems better to put this in an `if roleSubject != nil { certSubject, err = ParseDN...}`. You'll just have to be careful with variable scopes. 
___
*[`pkg/security/distinguishedname/parse.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtG3zuBC07zu82Y2PaX:-NtG3zuBC07zu82Y2PaY:byymdx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4272e401ce4ee0f52a6e61cb852d0048695b1e4b/pkg/security/distinguishedname/parse.go#L122)):*
> ```Go
> // MatchDN matches 2 distinguished names and returns true if they differ by only
> // the Common Name(CN) field.
> func MatchDN(d *ldap.DN, other *ldap.DN) bool {
> ```

Name the function `MatchDNWithoutCN` to make sure we don't use it incorrectly in the future. 

This data model is more complicated than I thought; I wasn't expecting the nested loops. And this implies new edge cases. And this opens up new edge cases (I'm not sure if there are other rules enforced for TLS certs and the CN field, but at least based on https://ldap.com/ldap-dns-and-rdns/ it would be legal for one of the RDNs in a DN to have multiple Attributes, a CN and something else). It seems incorrect to skip an RDN because it has a CN attribute; this should be limited to RDNs that are *only* a CN. And even then this is getting more complicated than I'm comfortable with.

We can simplify the code by getting rid of the logic that treats CN as equivalent to a missing CN - I don't think we actually want that. The two DNs should still have the same structure and if one has the CN, the other should have a CN in the same position. So that would be something like 

```
func hasOnlyCNAttribute(rdn *ldap.RelativeDN) bool {
    // I think the check for CN needs to be case-insensitive too
    return len(rdn.Attributes) == 1 && rdn.Attributes[0].Type == "CN"
}

func MatchDNWithoutCN(d, other *ldap.DN bool) {
    if len(d.RDNs) != other.RDNs { return false }
    for i := range d.RDNs {
        if hasOnlyCNAttribute(d.RDNS[i]) && hasOnlyCNAttribute(other.RDNs[i])) {
            continue
        }
        if !d.RDNs[i].Equal(other.RDNs[i]) { return false }
    }
}
```
___
*[`pkg/security/auth_test.go` line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtCH4DgCINV-qMqMoxJ:-NtHUJvXAOjgBuDibP3c:b-dzpp4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth_test.go#L394)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

In the same test we are calling the auth hook twice, once with `clientConnection` set to true and other time set to false.
</blockquote></details>

Ah, I see. What a strange test design. 


<!-- Sent from Reviewable.io -->

2024-03-19 09:05 UTC, souravcrl reviewed
Updated implementation for `MatchDNWithoutCN`. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-NtKwnZgA-LHprv9ybsC:b3hcn2u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @rafiss)

___
*[`pkg/security/auth.go` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtBzm5B9x7lSf3vuEfq:-NtKvyDiEIlROJDHMr8u:b-grhn25) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c2df9fa256e011b2682033bf710a1072f8d4b5/pkg/security/auth.go#L254)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Parsing the DN but ignoring the error if roleSubject is nil seems odd; it seems better to put this in an `if roleSubject != nil { certSubject, err = ParseDN...}`. You'll just have to be careful with variable scopes.
</blockquote></details>

updated the implementation.
___
*[`pkg/security/distinguishedname/parse.go` line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtG3zuBC07zu82Y2PaX:-NtKvuh47dzuIJNBtPyM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4272e401ce4ee0f52a6e61cb852d0048695b1e4b/pkg/security/distinguishedname/parse.go#L122)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Name the function `MatchDNWithoutCN` to make sure we don't use it incorrectly in the future. 

This data model is more complicated than I thought; I wasn't expecting the nested loops. And this implies new edge cases. And this opens up new edge cases (I'm not sure if there are other rules enforced for TLS certs and the CN field, but at least based on https://ldap.com/ldap-dns-and-rdns/ it would be legal for one of the RDNs in a DN to have multiple Attributes, a CN and something else). It seems incorrect to skip an RDN because it has a CN attribute; this should be limited to RDNs that are *only* a CN. And even then this is getting more complicated than I'm comfortable with.

We can simplify the code by getting rid of the logic that treats CN as equivalent to a missing CN - I don't think we actually want that. The two DNs should still have the same structure and if one has the CN, the other should have a CN in the same position. So that would be something like 

```
func hasOnlyCNAttribute(rdn *ldap.RelativeDN) bool {
    // I think the check for CN needs to be case-insensitive too
    return len(rdn.Attributes) == 1 && rdn.Attributes[0].Type == "CN"
}

func MatchDNWithoutCN(d, other *ldap.DN bool) {
    if len(d.RDNs) != other.RDNs { return false }
    for i := range d.RDNs {
        if hasOnlyCNAttribute(d.RDNS[i]) && hasOnlyCNAttribute(other.RDNs[i])) {
            continue
        }
        if !d.RDNs[i].Equal(other.RDNs[i]) { return false }
    }
}
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-03-26 09:33 UTC, bdarnell approved these changes
> Reviewed 1 of 3 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @rafiss, and @souravcrl)

___
*[`pkg/security/distinguishedname/parse.go` line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Ntu2R6e4oKSWEfScMLx:-Ntu2R6e4oKSWEfScMLy:b5r8i1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0c5f97df3a5b6d7008699d65797c6c72b714de/pkg/security/distinguishedname/parse.go#L26)):*
> ```Go
> // ValidateDN validates a distinguished name string to verify that it is
> // well-formed and valid for the given user.
> func ValidateDN(u username.SQLUsername, dnStr string) error {
> ```

Now that we're no longer comparing `u` with the `CN`, I think it might be better to remove the username argument from this function and have the sql layer be responsible for "root cannot have a subject". 
___
*[`pkg/security/distinguishedname/parse.go` line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Ntu282rBZy6A_ohQkHU:-Ntu282rBZy6A_ohQkHV:b2f9fp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0c5f97df3a5b6d7008699d65797c6c72b714de/pkg/security/distinguishedname/parse.go#L37)):*
> ```Go
> 	for _, rdn := range dn.RDNs {
> 		for _, attr := range rdn.Attributes {
> 			if !slices.Contains(fieldsList, attr.Type) {
> ```

Are these supposed to be case-sensitive uppercase or should we do `strings.ToUpper(attr.Type)`?


<!-- Sent from Reviewable.io -->

2024-03-26 20:19 UTC, souravcrl reviewed
Please take a final look Ben @bdarnell as I will need to backport these later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-NtwPTAS2P54pPD7Zryl:beb255k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @bdarnell, and @rafiss)

___
*[`pkg/security/distinguishedname/parse.go` line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Ntu2R6e4oKSWEfScMLx:-NtwMM4y8vesr9vXEoOf:b9pnton) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0c5f97df3a5b6d7008699d65797c6c72b714de/pkg/security/distinguishedname/parse.go#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Now that we're no longer comparing `u` with the `CN`, I think it might be better to remove the username argument from this function and have the sql layer be responsible for "root cannot have a subject".
</blockquote></details>

moved the implementation to `role_options.go`
___
*[`pkg/security/distinguishedname/parse.go` line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-Ntu282rBZy6A_ohQkHU:-NtwKdVS08a5-NP0VckY:b7ash6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0c5f97df3a5b6d7008699d65797c6c72b714de/pkg/security/distinguishedname/parse.go#L37)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Are these supposed to be case-sensitive uppercase or should we do `strings.ToUpper(attr.Type)`?
</blockquote></details>

RFC4514 does not specify case sensitivity but oracle docs and azure reference RFC4512 sec 2.5 for case insensitivity. Updating my implementation hence. ref: https://docs.oracle.com/cd/E19693-01/819-0995/bcatd/index.html#:~:text=An%20attribute%20name%20can%20contain,section%202.5%20of%20RFC%204512.


<!-- Sent from Reviewable.io -->

2024-03-27 06:07 UTC, bdarnell approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @rafiss)



<!-- Sent from Reviewable.io -->

2024-03-27 06:34 UTC, rafiss approved these changes
great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-:-Ntyb_9lChyCrCI3GVQa:by276bc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @souravcrl)

___
*[`pkg/security/auth.go` line 206 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119958#-NtyZz5W3KV9KcIkmiBK:-NtyZz5W3KV9KcIkmiBL:bsr09yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f08679c015653e2f7b2d9517d1643f10eafc410f/pkg/security/auth.go#L206)):*
> ```Go
> 			var err error
> 			if certSubject, err = distinguishedname.ParseDNFromCertificate(peerCert); err != nil {
> 				return errors.Errorf("could not parse certificate subject DN")
> ```

nit: this might be a useful error to wrap, so that it contains more debugging information:
```
return errors.Wrapf(err, "could not parse certificate subject DN")
```


<!-- Sent from Reviewable.io -->

2024-03-27 08:19 UTC, souravcrl commented
TFTR!

bors r=bdarnell

2024-03-27 08:20 UTC, souravcrl commented
bors r-

2024-03-27 08:21 UTC, souravcrl commented
bors r=bdarnell,rafiss

2024-03-27 09:01 UTC, merged