sql: allow reset sql activity with REPAIRCLUSTERMETADATA privilege
cockroachdb/cockroach pull request #120546
Opened 2024-03-15 14:35 UTC by koorosh

Before, there was a misalignment in permissions required to reset SQL stats. It was allowed to reset stats with `REPAIRCLUSTERMETADATA` permission by calling appropriate statusServer endpoints, but it required admin role to reset stats with builtin functions.

This change allows users with `REPAIRCLUSTERMETADATA` privilege to run following builtin functions:
- `reset_sql_stats`
- `reset_activity_tables`
- `reset_insights_tables`

Release note: None.

Resolves: #96876

2024-03-15 16:57 UTC, rafiss requested changes
thanks! just small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-:-Nt221rD2CUb28pe8lKC:b-bk9qng)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @koorosh, and @xinhaoz)

___
*[`pkg/sql/sem/builtins/builtins.go` line 7268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21Up8ArUIl-IQrKVl:-Nt21Up8ArUIl-IQrKVm:b9psyii) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7268)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx context.Context, evalCtx *eval.Context, args tree.Datums) (tree.Datum, error) {
> 				isAdmin, err := evalCtx.SessionAccessor.HasAdminRole(ctx)
> ```

you can remove the calls to HasAdminRole. the REPAIRCLUSTERMETADATA check will always pass for admins
___
*[`pkg/sql/sem/builtins/builtins.go` line 7277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21gJwDtc01AV-9-ib:-Nt21gJwDtc01AV-9-ic:b-i68cxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7277)):*
> ```Go
> 				hasPriv, err := evalCtx.SessionAccessor.HasGlobalPrivilegeOrRoleOption(ctx, privilege.REPAIRCLUSTERMETADATA)
> 				if err != nil {
> 					return nil, errors.New("crdb_internal.reset_sql_stats() requires REPAIRCLUSTERMETADATA privilege")
> ```

it is incorrect to throw away the `err` here. this should just be 
```
if err != nil {
  return nil, err
}
```
___
*[`pkg/sql/sem/builtins/builtins.go` line 7280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21rYfCEm2n5E5_2Jq:-Nt21rYfCEm2n5E5_2Jr:b-cwejmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7280)):*
> ```Go
> 				}
> 				if !isAdmin && !hasPriv {
> 					return nil, errors.New("crdb_internal.reset_sql_stats() requires either admin or REPAIRCLUSTERMETADATA privilege")
> ```

i would just make this say 
```
errors.New("crdb_internal.reset_sql_stats() requires either REPAIRCLUSTERMETADATA privilege")
```

all admins have that privilege, so this message is still true and more concise
___
*[`pkg/sql/sem/builtins/builtins.go` line 7307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21z_0E9thVo5hlV45:-Nt21z_1ANdcdb0ptHN5:b-lzevu) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7307)):*
> ```Go
> 					return nil, err
> 				}
> 				hasPriv, err := evalCtx.SessionAccessor.HasGlobalPrivilegeOrRoleOption(ctx, privilege.REPAIRCLUSTERMETADATA)
> ```

same comments as above
___
*[`pkg/sql/sem/builtins/builtins.go` line 7339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt22-Si5pPkEgaLK896:-Nt22-Si5pPkEgaLK897:b-lzevu) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7339)):*
> ```Go
> 					return nil, err
> 				}
> 				hasPriv, err := evalCtx.SessionAccessor.HasGlobalPrivilegeOrRoleOption(ctx, privilege.REPAIRCLUSTERMETADATA)
> ```

same comments as above


<!-- Sent from Reviewable.io -->

2024-03-15 18:27 UTC, koorosh reviewed
@rafiss TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-:-Nt2MU5N0vtpzAxKdPNk:b-8f33ia)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @rafiss, and @xinhaoz)

___
*[`pkg/sql/sem/builtins/builtins.go` line 7268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21Up8ArUIl-IQrKVl:-Nt2L-iC3cUz-gRt3T2R:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7268)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you can remove the calls to HasAdminRole. the REPAIRCLUSTERMETADATA check will always pass for admins
</blockquote></details>

Done
___
*[`pkg/sql/sem/builtins/builtins.go` line 7277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21gJwDtc01AV-9-ib:-Nt2L0rl7XEztbXvb0m0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7277)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it is incorrect to throw away the `err` here. this should just be 
```
if err != nil {
  return nil, err
}
```
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 7280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21rYfCEm2n5E5_2Jq:-Nt2MDfC2HZg6UxKjD-o:b-jsh6yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7280)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i would just make this say 
```
errors.New("crdb_internal.reset_sql_stats() requires either REPAIRCLUSTERMETADATA privilege")
```

all admins have that privilege, so this message is still true and more concise
</blockquote></details>

Indeed, thanks! 
___
*[`pkg/sql/sem/builtins/builtins.go` line 7307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt21z_0E9thVo5hlV45:-Nt2MSW-38vDe9L6reB8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7307)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same comments as above
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 7339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-Nt22-Si5pPkEgaLK896:-Nt2MTB_-p5QybDXaqFr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79994d69e2f860017d1e5b1e4d2c7da11995f36c/pkg/sql/sem/builtins/builtins.go#L7339)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same comments as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-15 18:38 UTC, rafiss approved these changes
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-:-Nt2P9n5CPeeu41dlC4n:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-03-18 13:40 UTC, dhartunian reviewed
@koorosh can we test the new permissions? Not sure if these builtins have tests already that we can add the permission to.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120546#-:-NtGmBRp17q3g4yrEOcK:b-ux29oq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @rafiss, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-03-18 18:50 UTC, koorosh commented
Closing as it duplicates https://github.com/cockroachdb/cockroach/pull/116844

2024-03-18 18:50 UTC, closed without merging

2024-03-18 20:58 UTC, rafiss commented
@koorosh https://github.com/cockroachdb/cockroach/pull/116844 is too large to backport to older release branches, so if you were planning to backport, you should still use this smaller PR.