sql: grant to all tables did not skip privileges on sequences
cockroachdb/cockroach pull request #120685
Opened 2024-03-19 01:33 UTC by fqazi

Previously, grant privilege to all tables attempted to apply privileges meant only for tables on to sequences. This could lead to validation error preventing certain combinations like "GRANT BACKUP ON ALL TABLES..." from working correctly. To address this, this patch adds support for correctly propogating the object type and skipping over unsupported privileges. When an unsupported privilege is encountered on an object other then a sequence a warning is now logged.

Fixes: #117861

Release note (bug fix): GRANT <...> ON ALL TABLES could fail if sequences existed and they did not support a privilege (for example BACKUP).

2024-03-19 01:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/120685)
<!-- Reviewable:end -->

2024-03-19 14:08 UTC, rafiss requested changes
just had a nit to clean things up a bit, nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120685#-:-NtM1K2nEz9-XVz8Qkvh:b-vzrp6f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/grant_revoke.go` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120685#-NtM0r501dpHSOrKnenQ:-NtM0r501dpHSOrKnenR:biwzzyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/431ec658ae3a16c0e444e146c06e6110d95c4cc8/pkg/sql/grant_revoke.go#L288)):*
> ```Go
> 				// Ensure we are only setting privilleges valid for this object type.
> 				// i.e. We only expect this for sequences.
> 				validPrivs, err := privilege.GetValidPrivilegesForObject(objType)
> ```

nit: all the new logic could be done once outside of the for loop
___
*[`pkg/sql/grant_revoke.go` line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120685#-NtM1UJ8DhVUlcSgtluk:-NtM1UJ8DhVUlcSgtlul:b-gnvo2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/431ec658ae3a16c0e444e146c06e6110d95c4cc8/pkg/sql/grant_revoke.go#L302)):*
> ```Go
> 					}
> 					if objType != privilege.Sequence {
> 						log.Warningf(ctx, "object type %s does not support privilege %v", objType, missingPrivs.SortedDisplayNames())
> ```

instead of a warning log, could we send this with `BufferClientNotice`? then i think it would also make sense to remove the `objType != privilege.Sequence` check


<!-- Sent from Reviewable.io -->

2024-03-19 16:05 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120685)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/grant_revoke.go` line 302 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120685#-NtM1UJ8DhVUlcSgtluk:-NtMSKDM4Ji_NXcCgLsa:b-89a7ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/431ec658ae3a16c0e444e146c06e6110d95c4cc8/pkg/sql/grant_revoke.go#L302)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of a warning log, could we send this with `BufferClientNotice`? then i think it would also make sense to remove the `objType != privilege.Sequence` check
</blockquote></details>

Good point and I generalized the logic from the original SEQUENCE logic.


<!-- Sent from Reviewable.io -->

2024-03-19 19:17 UTC, rafiss approved these changes
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120685#-:-NtN8LQX9Sd96sc_BKo2:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-03-19 19:22 UTC, fqazi commented
@rafiss TFTR!

bors r+

2024-03-19 20:32 UTC, merged

2024-04-09 17:40 UTC, fqazi commented
blathers backport 23.2

2024-04-09 17:40 UTC, fqazi commented
blathers backport 23.1