roachtest: add acceptance/benchmark-leasing for session based leasing
cockroachdb/cockroach pull request #120800
Opened 2024-03-20 23:54 UTC by fqazi

This patch adds a new test to confirm the benefits of session based leasing in a multi-region scenario. The simulated scenario is one where the lease manager cannot refresh all descriptors in time with expiry based leasing. This means that once the lease expires we need to reacquire it. This test intentionally selects a large number of descriptors to achieve this. The session based model will not need any reacquisition's, since these do not require a refresh, showing the latency benefits on select queries (on infrequently accessed tables).

We will compare how long the two different settings take selecting these tables multiple times.

Fixes: #119871
Release note: None

2024-03-20 23:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/120800)
<!-- Reviewable:end -->

2024-03-21 15:45 UTC, renatolabs reviewed
Mostly nits regarding roachtest APIs. My main comment is that this shouldn't be an acceptance test.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +	defaultOpts := install.MakeClusterSettings(install.SecureOption(true))
Nit: this is unnecessary. Clusters are already secure by default.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +					c.All())
Nit: this last argument is optional -- it already defaults to `c.All()`.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +				conn.Close()
Nit: to avoid leaked goroutines, it would be better to place this `defer` call right after `c.Conn`.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +				c.Stop(ctx, t.L(), option.DefaultStopOpts(), c.All())
Same as previous comments: no need for last argument.

Out of curiosity -- why do we need to restart the server? Do the settings only become effective on restart?

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +						conn, err := c.ConnE(ctx, t.L(), node)
Nit: `c.Conn`.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +			if modeIdx == 0 {
Nit: probably more readable for this predicate to reference `sessionBasedLeasingEnabled` than `modeIdx`?

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +						conn, err := c.ConnE(ctx, t.L(), node)
Nit: `c.Conn`.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +			// Next spawn a thread on each node to select from all the tables created
Seems like it's `numWorkers` threads on each node?

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +			c.Stop(ctx, t.L(), option.DefaultStopOpts())
Why do we need to stop the server? If we do need it, we probably want to stop the timer _before_ the call to `Stop`, right?

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/multiregion_leasing.go
> +		t.Fatal("Expected session based leasing to be faster with many descriptors.")
For your own sanity when this fails, it's probably better to log the durations. I don't see them logged anywhere.

2024-03-21 15:45 UTC, renatolabs commented on pkg/cmd/roachtest/tests/acceptance.go
> +				timeout:       time.Hour,
Can we move this test to a non-acceptance location? The test is verifying a new feature, so it shouldn't really be an "acceptance" test -- acceptance tests are supposed to be smoke tests.

2024-03-21 17:13 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534150066:-NtX-3sg78zt5k9z4J3L:b4vxpxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L62)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: `c.Conn`.
</blockquote></details>

i don't think it should be `c.Conn`, since it's illegal to call `t.Fatal` inside of a goroutine that is not the main test goroutine


<!-- Sent from Reviewable.io -->

2024-03-21 17:41 UTC, renatolabs reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @rafiss)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534150066:-NtX5KLQ1mh6sxkMgQcO:b-jr68yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L62)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think it should be `c.Conn`, since it's illegal to call `t.Fatal` inside of a goroutine that is not the main test goroutine
</blockquote></details>

Correct, my bad. That said, it wouldn't be a bad idea to open a single connection pool at the beginning of the test and reusing it here.


<!-- Sent from Reviewable.io -->

2024-03-22 21:45 UTC, rafiss requested changes
glad we're seeing good improvements! could you post the results in the PR description?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-:-Ntc7-qOArIYIpfMUo_9:bbw0zyz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc58-IBAaDx1G-zqXk:-Ntc58-IBAaDx1G-zqXl:bg2t5l1) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L27)):*
> ```Go
> 
> // Benchmarks and confirms the performance of the leasing infrastructure.
> func runAcceptanceMultiRegionBenchmarkLeasing(ctx context.Context, t test.Test, c cluster.Cluster) {
> ```

in addition to not being an acceptance test, should we make this a roachtest that uses a multiregion cluster, so we can see the results more clearly?
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534151590:-Ntc5kOfBOEcfYFyVYSm:bx65f9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L58)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: probably more readable for this predicate to reference `sessionBasedLeasingEnabled` than `modeIdx`? 
</blockquote></details>

or even better, why not just do this outside of the `for ... range []bool{true, false}` loop?
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534150066:-Ntc6cAG22SAbg-kBnj9:b-ry9297) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L62)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Correct, my bad. That said, it wouldn't be a bad idea to open a single connection pool at the beginning of the test and reusing it here.
</blockquote></details>

i agree too, making the connection pool outside of the worker goroutine makes more sense
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc4ckJD_nlyntlsLpB:-Ntc4ckJD_nlyntlsLpC:brv0gd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L106)):*
> ```Go
> 							for i := workerId * tablesPerWorker; i < (workerId+1)*tablesPerWorker; i++ {
> 								for j := 1; j <= len(c.All()); j++ {
> 									createTbl := fmt.Sprintf("SELECT * FROM table_%d_%d;", j, i)
> ```

would it be worth adding at least a few rows to each table?
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc2t951fQ4z_xO-FQb:-Ntc2t951fQ4z_xO-FQc:bnansyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L118)):*
> ```Go
> 				}
> 			}
> 			t.Status("Benchmarking Session Based Leasing: ", sessionBasedLeasingEnabled)
> ```

this will end up showing "benchmarking session based leasing: false" which is a bit confusing.

maybe instead make it say something like `t.Status(fmt.Sprintf("starting benchmark session_based_leasing=%b", sessionBasedLeasingEnabled))`
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc66IeDodNT5u39Qng:-Ntc66IeDodNT5u39Qnh:b7dj7f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L119)):*
> ```Go
> 			}
> 			t.Status("Benchmarking Session Based Leasing: ", sessionBasedLeasingEnabled)
> 			startTime := timeutil.Now()
> ```

this seems like the wrong place to start the timer. it should be started before the calls to GoCtx right?
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc6p5q2v8Mk8eqtq6p:-Ntc6p5q2v8Mk8eqtq6q:b-7fumfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L135)):*
> ```Go
> 	// Track the percentage improvement between the two.
> 	improvementPct := ((durations[1] * 100) / durations[0]) - 100
> 	t.Status(fmt.Sprintf("session based leasing produced an improvement of %d%%", improvementPct))
> ```

let's also log the raw durations here


<!-- Sent from Reviewable.io -->

2024-03-23 01:59 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc58-IBAaDx1G-zqXk:-Ntcrjoq9OsWvBA2JxCY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L27)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in addition to not being an acceptance test, should we make this a roachtest that uses a multiregion cluster, so we can see the results more clearly?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534148180:-NtbPPBc9HVgoYxUu0_i:bx6fut7) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L49)):*
> Out of curiosity -- why do we need to restart the server? Do the settings only become effective on restart?

I'll document it in the code too. But 24.1 defaults to session based leasing, and the legacy behaviour can be activated via a cluster setting but needs a full node restart.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534156422:-NtbaTbJ9dY4RW0J0GQi:b-ppa5py) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L85)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Seems like it's `numWorkers` threads on each node?
</blockquote></details>

renamed to numWorkersPerNode
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc4ckJD_nlyntlsLpB:-Ntcs-F24KSKY6Q3XWFS:buiu4fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L106)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be worth adding at least a few rows to each table?
</blockquote></details>

I'm trying to keep the surface area to a minimum, so this should mainly be time spent on the queries side looking up descriptors.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc2t951fQ4z_xO-FQb:-Ntcsz3k9aZhWNSHGkip:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L118)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this will end up showing "benchmarking session based leasing: false" which is a bit confusing.

maybe instead make it say something like `t.Status(fmt.Sprintf("starting benchmark session_based_leasing=%b", sessionBasedLeasingEnabled))`
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc66IeDodNT5u39Qng:-Ntct2Rj2pXznmSfrIeE:b-d3naqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L119)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this seems like the wrong place to start the timer. it should be started before the calls to GoCtx right?
</blockquote></details>

True, I moved this up.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534161372:-Ntbacv6-pt5F2vx5N3j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L123)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Why do we need to stop the server? If we do need it, we probably want to stop the timer _before_ the call to `Stop`, right?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534162674:-NtbaoIHEMTQnjsFNum2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L130)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

For your own sanity when this fails, it's probably better to log the durations. I don't see them logged anywhere.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Ntc6p5q2v8Mk8eqtq6p:-Ntct6TVCIim1voOxEE8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/multiregion_leasing.go#L135)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's also log the raw durations here
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120800#gh-1534174847:-NtcrgV32jO8BBPvzqCZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07076f330b30b69a18ea76f5e0d7ec8add7aa8da/pkg/cmd/roachtest/tests/acceptance.go#L116)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Can we move this test to a non-acceptance location? The test is verifying a new feature, so it shouldn't really be an "acceptance" test -- acceptance tests are supposed to be smoke tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 13:48 UTC, renatolabs approved these changes
LGTM

2024-03-27 13:49 UTC, fqazi commented
@renatolabs @rafiss TFTR!

bors r+

2024-03-27 18:20 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120800)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120800#-Nu07PeKCk0C1VUpI-_T:-Nu07PeL75Qe9L6G45vO:b-vyz8md) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a398896285dd28315557764db2ac14a94a5ea91/pkg/cmd/roachtest/tests/multiregion_leasing.go#L115)):*
> ```Go
> 					t.Fatal(err)
> 				}
> 				defer connPool.Close()
> ```

the defer in a loop doesn't work that well. i think instead, outside of this loop, we want
```
defer func() {
  for _, pool := range connPoolPerNode {
    pool.Close()
  }
}()
```


<!-- Sent from Reviewable.io -->

2024-03-27 19:39 UTC, fqazi commented
bors r+

2024-03-27 22:56 UTC, merged

2024-03-28 14:49 UTC, fqazi commented
@renatolabs Let me adjust that