sql: allow ALTER DATABASE PRIMARY REGION to work on system tenants
cockroachdb/cockroach pull request #121293
Opened 2024-03-28 18:33 UTC by jasminejsun

Previously, on a multi-region setup the system database could not be modified to be multi-region and it was blocked from being made multi-region aware. To address this, we are now allowing ALTER DATABASE PRIMARY REGION to work on system tenants.

Fixes: #63365
Epic: CRDB-33032

Release note (sql change): Previously, we added support for settings reegion on the system database, which was limited to tenants only. We lifted this limitation to allow ALTER DATABASE PRIMARY REGION to work on system tenants.

2024-03-28 18:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/121293)
<!-- Reviewable:end -->

2024-03-29 21:48 UTC, annrpom commented on pkg/sql/alter_database.go
> +					"`sql.multiregion.preview_multiregion_system_database.enabled` "+
nit: could we also add details of this cluster setting (name, how it is not enabled by default) in the release notes

2024-03-29 21:48 UTC, annrpom commented on pkg/cmd/roachtest/tests/multi_region_system_database.go
> +			//Perform rolling restart to propagate region information to non-primary nodes
nit: we also might want to document this in the release notes

2024-04-02 19:34 UTC, fqazi requested changes
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @jasminejsun)

___
*[`pkg/cmd/roachtest/tests/multi_region_system_database.go` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121293#-NuVHNG8BypwVSb1gEYk:-NuVHNG8BypwVSb1gEYl:bwfpstn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0fde6c4e988f5984352219ce6f7c4dc0e062bf/pkg/cmd/roachtest/tests/multi_region_system_database.go#L117)):*
> ```Go
> 				t.WorkerStatus("stop")
> 				stopOpts := option.DefaultStopOpts()
> 				c.Stop(ctx, t.L(), stopOpts, c.Node(i))
> ```

I think this does a graceful kill, lets be a bit more aggressive:

```	c.Run(ctx, install.WithNodes(c.Node(i), "killall -9 cockroach")```
___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 310 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121293#-NuVHvY113VAMUwy6Ea-:-NuVHvY113VAMUwy6Ea0:bcg1gfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef0fde6c4e988f5984352219ce6f7c4dc0e062bf/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L310)):*
> ```Go
> }
> 
> func TestMRSystemDatabase(t *testing.T) {
> ```

I'm thinking we just modify the multi-tenant multi-region one above to also test the system tenant. What do you think?


<!-- Sent from Reviewable.io -->

2024-04-04 14:14 UTC, fqazi requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @jasminejsun)

___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/121293#-NudReNd5shdkCRAQr1h:-NudReNd5shdkCRAQr1i:btic2z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd7939e0949ba6ae2aecdd20bf8b66a651dfa507/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L84)):*
> ```Go
> 	tDB.CheckQueryResults(t, `SELECT * FROM crdb_internal.invalid_objects`, [][]string{})
> 
> 	_, err = sqlDB.Exec(`SET CLUSTER SETTING sql.multiregion.preview_multiregion_system_database.enabled = true`)
> ```

Okay perfect, now lets just modify the tests below to check with both tDB and sqlDB. We can use a loop to pick one of the databases and confirm the same properties hold.


<!-- Sent from Reviewable.io -->

2024-04-08 19:12 UTC, fqazi approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121293)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jasminejsun)

___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/121293#-Nuz735g0MVVnv49lDiW:-Nuz735g0MVVnv49lDiX:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3cae02855db38e2ceee76208078cb1e7fae414/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L91)):*
> ```Go
> 	sDB.Exec(t, `ALTER DATABASE system ADD REGION "us-east3"`)
> 
> 	testCases := []struct {
> ```

Nice!


<!-- Sent from Reviewable.io -->

2024-04-08 19:46 UTC, jasminejsun commented
bors r+

2024-04-08 20:33 UTC, merged