regionliveness: treat replica errors as timeouts
cockroachdb/cockroach pull request #121485
Opened 2024-04-01 20:06 UTC by fqazi

Previously, we would only treat timeout errors are region availability issues for queries, which would trigger a liveness probe. We will instead go a step further and treat any re triable replica errors to probe the liveness of a region. There are cases were a slow proposal error will or other errors will be surfaced earlier. This patch will modify the region liveness code to retry these errors. We are also going to update the multi-region multi-tenant test to be more stable by making sure that any span config changes are propagated before starting the test.

Fixes: #121327

Release note: None

2024-04-01 20:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/121485)
<!-- Reviewable:end -->

2024-04-02 05:07 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121485)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @srosenberg)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSC-qk7Z9zsnt5Dv0Q):*
i may have the wrong understanding -- but i thought these were not actually retried? the errors are just used to detect up/down.

also, some of these sentences might have had some missed wording, so it's a little hard to follow this
___
*[`pkg/cmd/roachtest/tests/multitenant.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSAnMu0YJmTtOjKDaW:-NuSAnMu0YJmTtOjKDaX:bxsr94o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6444545a495a9d6d4e95aeec750329ca3fa8e2c7/pkg/cmd/roachtest/tests/multitenant.go#L162)):*
> ```Go
> 	// propagated, we'll shut down the tenant and wait for them to get
> 	// applied.
> 	tdb, tdbCloser := openDBAndMakeSQLRunner(t, tenants[0].pgURL)
> ```

nit: we have the same exact code in `TestColdStartLatency`. should we make a shared function that does this?

(curious what you think; not sure if it's worth it)
___
*[`pkg/sql/regionliveness/prober.go` line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSB6LZ3Tv3MXSiFFsy:-NuSB6L_-mxjKrrk6XNC:bpzh3rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6444545a495a9d6d4e95aeec750329ca3fa8e2c7/pkg/sql/regionliveness/prober.go#L346)):*
> ```Go
> 	return pgerror.GetPGCode(err) == pgcode.QueryCanceled ||
> 		errors.HasType(err, (*timeutil.TimeoutError)(nil)) ||
> 		startup.IsRetryableReplicaError(err) ||
> ```

i  think it's a bit misleading to use the `IsRetryableReplicaError` function here -- we aren't actually going to retry these right? since this is just used for the purpose of deciding if a region is alive or not, it might be more clear to spell out the errors explicitly here:
```
		errors.HasType(err, (*kvpb.ReplicaUnavailableError)(nil)) ||
		errors.HasType(err, (*kvpb.AmbiguousResultError)(nil)) ||
		pgerror.GetPGCode(err) == pgcode.RangeUnavailable
```


<!-- Sent from Reviewable.io -->

2024-04-02 16:30 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121485)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @srosenberg)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSC-qk7Z9zsnt5Dv0Q):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i may have the wrong understanding -- but i thought these were not actually retried? the errors are just used to detect up/down.

also, some of these sentences might have had some missed wording, so it's a little hard to follow this
</blockquote></details>

Sorry, yeah this was really poorly worded (updated this commit message):

regionliveness: probe on replica errors for liveness on rbr system tables

Previously, we probed for region liveness issues only after encountering
a timeout error when accessing regional-by-row tables. This approach
missed retriable replica errors (such as slow proposals), which also
indicate potential availability problems. This patch now treats
retriable replica errors as a trigger for region liveness probes,
improving the speed of issue detection. Additionally, we'll update the
multi-region multi-tenant test to ensure the timely propagation of span
configuration changes.
___
*[`pkg/cmd/roachtest/tests/multitenant.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSAnMu0YJmTtOjKDaW:-NuUYJ-iEHwgoUM4E45i:b-yhhs0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/6444545a495a9d6d4e95aeec750329ca3fa8e2c7/pkg/cmd/roachtest/tests/multitenant.go#L162)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we have the same exact code in `TestColdStartLatency`. should we make a shared function that does this?

(curious what you think; not sure if it's worth it)
</blockquote></details>

Good point, I made this code shared between the two of them.
___
*[`pkg/sql/regionliveness/prober.go` line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuSB6LZ3Tv3MXSiFFsy:-NuUXtQf8P8yW1rdVy_U:b-2no0wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6444545a495a9d6d4e95aeec750329ca3fa8e2c7/pkg/sql/regionliveness/prober.go#L346)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i  think it's a bit misleading to use the `IsRetryableReplicaError` function here -- we aren't actually going to retry these right? since this is just used for the purpose of deciding if a region is alive or not, it might be more clear to spell out the errors explicitly here:
```
		errors.HasType(err, (*kvpb.ReplicaUnavailableError)(nil)) ||
		errors.HasType(err, (*kvpb.AmbiguousResultError)(nil)) ||
		pgerror.GetPGCode(err) == pgcode.RangeUnavailable
```
</blockquote></details>

Good point, I'll directly propagate the checks here and also dropped 
AmbiguousResultError since that shouldn't be a worry on reads.


<!-- Sent from Reviewable.io -->

2024-04-02 17:07 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121485)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/util_mutiltregion.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuUlmtnByFIPMLNJm2J:-NuUlmto2ccQi8C1_Cae:b-fbapnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/53132001eb68aec42d6bf6fb3eacc6b4da3d80d7/pkg/cmd/roachtest/tests/util_mutiltregion.go#L1)):*
> ```Go
> package tests
> ```

i think this file would be better in `pkg/testutils`; to avoid weird dependencies


<!-- Sent from Reviewable.io -->

2024-04-02 18:42 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121485)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, @srosenberg, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/util_mutiltregion.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuUlmtnByFIPMLNJm2J:-NuV6HtU9RstFxtCgwZj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53132001eb68aec42d6bf6fb3eacc6b4da3d80d7/pkg/cmd/roachtest/tests/util_mutiltregion.go#L1)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this file would be better in `pkg/testutils`; to avoid weird dependencies
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-02 18:48 UTC, rafiss approved these changes
nice fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-:-NuV86zw9E7I0TtsxIwB:bhpddey)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, @srosenberg, and @yuzefovich)

___
*[`pkg/testutils/sqlutils/util_mutiltregion.go` line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121485#-NuV7v8d-bezzrSk-RsP:-NuV7v8d-bezzrSk-RsQ:b-6s7kc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa782956ca9d9dc3ef7f408e99635ef418fd89a/pkg/testutils/sqlutils/util_mutiltregion.go#L2)):*
> ```Go
> package sqlutils
> ```

nit: this file needs a header for the license (and to pass the linter)


<!-- Sent from Reviewable.io -->

2024-04-02 20:37 UTC, fqazi commented
@rafiss TFTR!

bors r+

2024-04-02 22:11 UTC, merged