sql/pg_catalog pg_default_acl is populated by ALTER DEFAULT PRIVILEGES
cockroachdb/cockroach pull request #121506
Opened 2024-04-01 22:23 UTC by Dedej-Bergin

When granting or revoking privileges in schemas you are currently
unable to seem them on the pg_default_acl table. These code
changes make it so that the appropriate rows related to default
schema privileges are added and removed on pg_default_acl to
reflect the current state of default privileges on schemas.

Fixes #114032.
Release note (sql change): default schema privilege changes will
now be reflected and can be monitored in the pg_default_acl table.

2024-04-01 22:23 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=121506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=121506) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=121506) it.</sub>

2024-04-01 22:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/121506)
<!-- Reviewable:end -->

2024-04-03 16:39 UTC, fqazi requested changes
Nice work! A couple of minor comments

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-:-NuZp6Ks3wBA6Z7pmT3M:bjo2251)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZn_-02SMK_TI-24_z):*
Nit: see
___
*[`pkg/sql/pg_catalog.go` line 1376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZoC7K9wJpolU-3YGl:-NuZoC7K9wJpolU-3YGm:bg6rx22) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1376)):*
> ```Go
> 		h := makeOidHasher()
> 
> 		privilegeWithID := func(schemaID descpb.ID) func(defaultPrivilegesForRole catpb.DefaultPrivilegesForRole) error {
> ```

Nit: Lets have a name with the word populate. I think that would be more descriptive.
___
*[`pkg/sql/pg_catalog.go` line 1494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZolZF3EouZbkTvQdr:-NuZolZF3EouZbkTvQds:b-1m5rnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1494)):*
> ```Go
> 						}
> 
> 						if objectType == privilege.Types || objectType == privilege.Routines {
> ```

Do we still need the type check if publicHasUsage / roleHasAllPrivileges is only set for routines / types? Wondering if we can simplify this more.
___
*[`pkg/sql/pg_catalog.go` line 1568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZp2Oi3J_Euxcvds0y:-NuZp2Oi3J_Euxcvds0z:b-tyi2k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1568)):*
> ```Go
> 		}
> 
> 		return dbContext.GetDefaultPrivilegeDescriptor().ForEachDefaultPrivilegeForRole(privilegeWithID(0))
> ```

Use descpb.InvalidID add a comment saying which parameter /* schemaID */


<!-- Sent from Reviewable.io -->

2024-04-03 16:50 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`pkg/sql/pg_catalog.go` line 1376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZoC7K9wJpolU-3YGl:-NuZrc5dBm-EEuEhk8nk:bwa1hbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1376)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Lets have a name with the word populate. I think that would be more descriptive.
</blockquote></details>

nit: i think a name like `addPrivilegeRow` or `populatePrivilegeRow` would be good. (there's no need to have `WithID` in the name, since there is no corresponding `WithoutID` function. a reader of the code already can see that the function accepts an ID parameter by looking at the function signature.)


<!-- Sent from Reviewable.io -->

2024-04-03 20:44 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZn_-02SMK_TI-24_z):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: see
</blockquote></details>

Thanks I updated it
___
*[`pkg/sql/pg_catalog.go` line 1376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZoC7K9wJpolU-3YGl:-Nu_gti52Zo0K1QuKA96:b556hug) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1376)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think a name like `addPrivilegeRow` or `populatePrivilegeRow` would be good. (there's no need to have `WithID` in the name, since there is no corresponding `WithoutID` function. a reader of the code already can see that the function accepts an ID parameter by looking at the function signature.)
</blockquote></details>

Thanks I changed it to populatePrivilegeRow
___
*[`pkg/sql/pg_catalog.go` line 1494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZolZF3EouZbkTvQdr:-Nu_gyYf8u41VFJC3qIr:bsjf12r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1494)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we still need the type check if publicHasUsage / roleHasAllPrivileges is only set for routines / types? Wondering if we can simplify this more.
</blockquote></details>

We don't need it thanks, I removed that line to reduce if statement nested and added a comment for clarity.
___
*[`pkg/sql/pg_catalog.go` line 1568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NuZp2Oi3J_Euxcvds0y:-Nu_h6XZ8h_XOq-4EDbR:bxl3g6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cb0299568a7c9114a2b15e0af14b2f7b73cd429/pkg/sql/pg_catalog.go#L1568)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Use descpb.InvalidID add a comment saying which parameter /* schemaID */
</blockquote></details>

Added it, thanks


<!-- Sent from Reviewable.io -->

2024-04-04 14:16 UTC, fqazi approved these changes
This looks good!


<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-:-NudSt2F4Mi6dI_V8w_T:b-plpfet)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Dedej-Bergin)



<!-- Sent from Reviewable.io -->

2024-04-05 19:16 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`pkg/sql/pg_catalog.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NujeFZk1jGjnTpHx79y:-NujeFZk1jGjnTpHx79z:bjeew4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/db76ae801b7f3b08f560d8a04b37ff97c61fc24a/pkg/sql/pg_catalog.go#L1539)):*
> ```Go
> 						rowOid,             // row identifier oid
> 						roleOid,            // defaclrole oid
> 						oidZero,            // defaclnamespace oid
> ```

instead of `oidZero`, we should pass in `h.schemaOid(schemaID)` for `defaclnamespace`
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-Nujdp488jr842FseiZU:-Nujdp488jr842FseiZV:by26ili) ([raw file](https://github.com/cockroachdb/cockroach/blob/db76ae801b7f3b08f560d8a04b37ff97c61fc24a/pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl#L415)):*
> ```
> ----
> oid         defaclrole  defaclnamespace  defaclobjtype  defaclacl
> 3426387245  2264919399  0                r              {foo=adrw/}
> ```

the results for `defaclnamespace` should have the schema OID, not 0. i think i see the issue -- i'll add a comment there

also, since this assertion just needs to check the per-schema privileges, let's change the query to `SELECT * FROM pg_catalog.pg_default_acl WHERE defaclnamespace != 0`. it will reduce noise in the test.


<!-- Sent from Reviewable.io -->

2024-04-05 20:33 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/pg_catalog.go` line 1539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-NujeFZk1jGjnTpHx79y:-NujxNjmDsVsSOI8e8Zu:b4iob2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/db76ae801b7f3b08f560d8a04b37ff97c61fc24a/pkg/sql/pg_catalog.go#L1539)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of `oidZero`, we should pass in `h.schemaOid(schemaID)` for `defaclnamespace`
</blockquote></details>

Thanks for making me aware of this bug, I changed oidZero to schemaOid(schemaID)
___
*[`pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl` line 415 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-Nujdp488jr842FseiZU:-NujxYrrEsYfKUzOGrd_:bkv2xra) ([raw file](https://github.com/cockroachdb/cockroach/blob/db76ae801b7f3b08f560d8a04b37ff97c61fc24a/pkg/sql/logictest/testdata/logic_test/pg_catalog_pg_default_acl#L415)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the results for `defaclnamespace` should have the schema OID, not 0. i think i see the issue -- i'll add a comment there

also, since this assertion just needs to check the per-schema privileges, let's change the query to `SELECT * FROM pg_catalog.pg_default_acl WHERE defaclnamespace != 0`. it will reduce noise in the test.
</blockquote></details>

Made the change this is definitely a nicer output to read, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-04-05 20:50 UTC, rafiss approved these changes
nice work, and congrats on your first PR! when you're ready to merge, just add a comment that has the line "bors r+" (needs to be on its own line)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121506#-:-Nuk0VWO4hesHCa1tANK:bx2pcem)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)



<!-- Sent from Reviewable.io -->

2024-04-05 20:59 UTC, Dedej-Bergin commented
bors r+

2024-04-06 00:46 UTC, merged