[WIP] ui: make custom chart tool work at store level
cockroachdb/cockroach pull request #122151
Opened 2024-04-10 20:19 UTC by abarganier

2024-04-10 20:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/122151)
<!-- Reviewable:end -->

2024-04-16 13:27 UTC, koorosh requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122151)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaruUN5GcIyegZQhBj:-NvaruUN5GcIyegZQhBk:b-otwrfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L216)):*
> ```XML
>     }
>     return isStoreMetric(nodesSummary.nodeStatuses[0], metricName)
>       ? Object.values(nodesSummary.storeIDsByNodeID).flatMap(s => s)
> ```

I think it should also filter out stores for selected node (in case only specific node selected as a source)
![Screenshot 2024-04-16 at 15.28.33.png](https://files.reviewableusercontent.io/images/reviewable/3106437/SLAJhdgXsM999MpvpOqec0Op/Screenshot%202024-04-16%20at%2015.28.33.png)

Also it makes confusing when node metrics selected with single node selected as a source with `per node/store` option selected. I'd suggest that `per node/store` option should be disabled or does nothing as only single node selected as a source.
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaqRhK0IsXizoCFwci:-NvaqRhK0IsXizoCFwcj:bnt75qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L249)):*
> ```XML
>           ));
>         });
>       } else if (m.perSource) {
> ```

This `else if` condition looks identical to the first one with only exception how `title` and `key` fields defined. It could be simplified by conditionally build those strings only. WDYT?


<!-- Sent from Reviewable.io -->

2024-04-16 21:20 UTC, abarganier reviewed
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-:-Nvclz3hBXP0u_8qnl_2:bz5m8k4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaruUN5GcIyegZQhBj:-NvcYWcw304eBR7cVxUk:b-p2six5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L216)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I think it should also filter out stores for selected node (in case only specific node selected as a source)
![Screenshot 2024-04-16 at 15.28.33.png](https://files.reviewableusercontent.io/images/reviewable/3106437/SLAJhdgXsM999MpvpOqec0Op/Screenshot%202024-04-16%20at%2015.28.33.png)

Also it makes confusing when node metrics selected with single node selected as a source with `per node/store` option selected. I'd suggest that `per node/store` option should be disabled or does nothing as only single node selected as a source.
</blockquote></details>

Thanks for catching this, I hadn't considered it!

I think keeping the `per node/store` option still makes sense, though.

For example, if I take a store-level metric like `cr.store.capacity.used` and chart it, it shows things cluster-wide:
![Screenshot 2024-04-16 at 4.47.11 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/lRFu8kjMNefL7JKpU23TfFAa/Screenshot%202024-04-16%20at%204.47.11%E2%80%AFPM.png)

If I then select a specific node as a source, it switches to show the sum of the metric across all the stores on that node:
![Screenshot 2024-04-16 at 4.47.42 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/vnJ4lxgIMRtqC9vMKB3QPJe9/Screenshot%202024-04-16%20at%204.47.42%E2%80%AFPM.png)

Then, if I select the "Per Node/Store" checkbox, it shows me the metric for each individual store available for the node:
![Screenshot 2024-04-16 at 4.47.57 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/B1gdKcsgdm16ZsiVYi17-h9O/Screenshot%202024-04-16%20at%204.47.57%E2%80%AFPM.png)
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaqRhK0IsXizoCFwci:-NvcgR3OAte0PkQD9D21:bqwj2q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L249)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

This `else if` condition looks identical to the first one with only exception how `title` and `key` fields defined. It could be simplified by conditionally build those strings only. WDYT?
</blockquote></details>

Doesn't the previous one have an additional nested level of iteration though, for the tenant IDs? 

As in, the `else if (m.perSource)` block creates a `<Metric>` for each source, but the previous `if` block creates a `<Metric>` for each source, for each tenant. 

Let me know if I'm misunderstanding!


<!-- Sent from Reviewable.io -->

2024-04-17 19:36 UTC, koorosh approved these changes
:<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>: Just few nits to adjust commented below.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-:-NvhY8WY8BVePFyTOj1a:b-uy2ld0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaruUN5GcIyegZQhBj:-NvhSX5S-quKmvPUFdS7:bygk1jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L216)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Thanks for catching this, I hadn't considered it!

I think keeping the `per node/store` option still makes sense, though.

For example, if I take a store-level metric like `cr.store.capacity.used` and chart it, it shows things cluster-wide:
![Screenshot 2024-04-16 at 4.47.11 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/lRFu8kjMNefL7JKpU23TfFAa/Screenshot%202024-04-16%20at%204.47.11%E2%80%AFPM.png)

If I then select a specific node as a source, it switches to show the sum of the metric across all the stores on that node:
![Screenshot 2024-04-16 at 4.47.42 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/vnJ4lxgIMRtqC9vMKB3QPJe9/Screenshot%202024-04-16%20at%204.47.42%E2%80%AFPM.png)

Then, if I select the "Per Node/Store" checkbox, it shows me the metric for each individual store available for the node:
![Screenshot 2024-04-16 at 4.47.57 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/B1gdKcsgdm16ZsiVYi17-h9O/Screenshot%202024-04-16%20at%204.47.57%E2%80%AFPM.png)
</blockquote></details>

🔥🔥🔥
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvaqRhK0IsXizoCFwci:-NvhVcBXAQWmRK5M9fNP:b-i3r9ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/4714225ffb4ef8b3009da111c1994853c9f3ab49/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L249)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Doesn't the previous one have an additional nested level of iteration though, for the tenant IDs? 

As in, the `else if (m.perSource)` block creates a `<Metric>` for each source, but the previous `if` block creates a `<Metric>` for each source, for each tenant. 

Let me know if I'm misunderstanding!
</blockquote></details>

You're right, i've missed that nested iteration!
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvhXaP27neRAePVU9g4:-NvhXaP37U9J_URRmK8y:b-3zcpfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deae9b285a5cc3158d908ada10cee6ca3dff0b/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L226)):*
> ```XML
>     if (isStoreMetric(nodesSummary.nodeStatuses[0], metricState.metric)) {
>       // If a specific node is selected, return the storeIDs associated with that node.
>       // Otherwise, we're at the cluster level, so we cna
> ```

nit. sentence isn't completed.
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvhVqykBp4Ijff1-wTG:-NvhVqykBp4Ijff1-wTH:b-v1lh10) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deae9b285a5cc3158d908ada10cee6ca3dff0b/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L263)):*
> ```XML
>               downsampler={m.downsampler}
>               derivative={m.derivative}
>               sources={this.getSources(nodesSummary, m)}
> ```

nit. you have `const sources = this.getSources(nodesSummary, m);` (above the `flatMap` call) which can be used instead of calling it every time.


<!-- Sent from Reviewable.io -->

2024-04-18 18:47 UTC, abarganier reviewed
TFTR! Addressed nits. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-:-NvmXAtQBqWm-NnIi5J4:bn0h7f1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @koorosh)

___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvhXaP27neRAePVU9g4:-NvmWzUB1UO3pvx37V_W:b-gfd8cy) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deae9b285a5cc3158d908ada10cee6ca3dff0b/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L226)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. sentence isn't completed.
</blockquote></details>

Ah, thanks for catching! Fixed.
___
*[`pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx` line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-NvhVqykBp4Ijff1-wTG:-NvmX1S5CeOKoxPPcfbL:b-4j5o0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/22deae9b285a5cc3158d908ada10cee6ca3dff0b/pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx#L263)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

nit. you have `const sources = this.getSources(nodesSummary, m);` (above the `flatMap` call) which can be used instead of calling it every time.
</blockquote></details>

Good catch! Fixed to be more consistent when `m.perSource && !m.perTenant` (the following `else if`). 


<!-- Sent from Reviewable.io -->

2024-04-18 19:15 UTC, koorosh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122151#-:-NvmccEZ--doCIxWDgvN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)



<!-- Sent from Reviewable.io -->

2024-04-19 14:33 UTC, abarganier commented
bors r=koorosh

2024-04-19 16:22 UTC, rail commented
bors retry
(it crashed)

2024-04-19 18:22 UTC, merged