server: adding API side redaction support for debug zip
cockroachdb/cockroach pull request #122181
Opened 2024-04-11 11:19 UTC by kousiknath

Debug zip has many files like nodes.json, gossip.json, status.json, details.json, ranges.json etc which contain un-redacted hostname / ip addresses. Some self hosted customers are very particular about security and they have objections sharing such critical data out of their network. This PR addresses this problem. If redaction flag is set to true in the debug zip command, these changes make sure that host name / ip addresses coming from internal APIs get redacted and show up as "<redacted>" in the dumped json files.

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-19369
Release note: None

2024-04-11 11:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/122181)
<!-- Reviewable:end -->

2024-04-11 17:26 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD8_Vu6Z-vZKIGn9DX):*
nit: Ideally, it would be nice to have one commit per-endpoint. This would make life easier for the reviewer, as they could focus on one diff per-endpoint. We could then have a final commit that updates the debug zip code to actually make use of the new redaction capabilities. 



_Code quote:_
```
nodes.json, gossip.json, status.json, details.json, ranges.json
```
___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-NvD9zuV4ETqHwxLZSI0:b2kcml6) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
> ```Go
> 		var nodesStatus *serverpb.NodesResponse
> 		err := zc.runZipFn(ctx, s, func(ctx context.Context) error {
> 			nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})
> ```

Isn't it still possible for the individual `NodeDetails` objects that are part of `nodesList` to be written to the node-level `status.json` file(s)? 

For example: https://github.com/cockroachdb/cockroach/blob/eaea30ee27ea666988d064be187a62154f380ebe/pkg/cli/zip_per_node.go#L187

In this case I don't think `status.json` for each node would be properly redacted.



_Code quote:_
```Go
			nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})
```
___
*[`pkg/server/status.go` line 755 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvDB2q324zj73ItV3Gh:-NvDB2q324zj73ItV3Gi:buihnnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L755)):*
> ```Go
> 
> 	return resp
> }
> ```

nit: For each of these redaction functions, maybe we should comment a TODO that links to https://github.com/cockroachdb/cockroach/issues/109594



_Code quote:_
```Go
func (s *statusServer) redactGossipResponse(resp *gossip.InfoStatus) *gossip.InfoStatus {
	for i := range resp.Server.ConnStatus {
		resp.Server.ConnStatus[i].Address = "<redacted>"
	}

	return resp
}
```


<!-- Sent from Reviewable.io -->

2024-04-12 17:44 UTC, bdarnell reviewed
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @kousiknath)

___
*[`pkg/server/status.go` line 751 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvILlUy9UqzyOlzIvjI:-NvILlUy9UqzyOlzIvjJ:boffhe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L751)):*
> ```Go
> func (s *statusServer) redactGossipResponse(resp *gossip.InfoStatus) *gossip.InfoStatus {
> 	for i := range resp.Server.ConnStatus {
> 		resp.Server.ConnStatus[i].Address = "<redacted>"
> ```

In logs, we use the special string `github.com/cockroachdb/redact.RedactedMarker()`; we should probably do the same here. Note that the redacted marker is `‹×›`, but those are not the ascii characters you might think they are. 
___
*[`pkg/server/status.go` line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINHle2-51YaNbv9qX:-NvINHlf5CZ25xRqC2Uv:bikw4z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L1848)):*
> ```Go
> 
> 		for j := range resp.Nodes[i].Desc.Locality.Tiers {
> 			if resp.Nodes[i].Desc.Locality.Tiers[j].Key == "dns" {
> ```

I don't think we want to treat `key==dns` as a special case - either redact all the locality info or none of it. 
___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NvINdd97VOYyg1CmVEg:b-si1muk) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
> ```Go
> func (s *statusServer) redactRangesResponse(resp *serverpb.RangesResponse) *serverpb.RangesResponse {
> 	for i := range resp.Ranges {
> 		for j := range resp.Ranges[i].Locality.Tiers {
> ```

Pull the loop over Locality.Tiers into a separate function so it can be shared with the previous one. 
___
*[`pkg/server/status_test.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIOif27sSKaJBvx3DE:-NvIOif27sSKaJBvx3DF:btu3lmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L30)):*
> ```Go
> 
> 	require.Equal(t, "<redacted>", res.Address.AddressField)
> 	require.Equal(t, "<redacted>", res.SQLAddress.AddressField)
> ```

We could have a general test in all of these to encode the response to json, call `os.Hostname` to find out the current node's hostname, then ensure that the hostname doesn't appear in the json in redacted mode. It wouldn't catch everything but it might catch some regression in the future. 
___
*[`pkg/server/status_test.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIO2pz04TVRE1OxW8-:-NvIO2pz04TVRE1OxW80:b-jmgmql) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L35)):*
> ```Go
> // TestDetailsUnRedacted checks if the `DetailsResponse` contains un-redacted fields
> // when the `Redact` flag is not set in the `DetailsRequest`
> func TestDetailsUnRedacted(t *testing.T) {
> ```

Nit: I wouldn't capitalize the `R` in `Unredacted`

The redacted/unredacted pairs could be done as subtests to remove a little redundancy, although maybe it's not worth it. 
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvIP7-Z8777_b-_tk6d:buuiuhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
> ```Go
> 		require.Equal(t, "<redacted>", res.Nodes[i].Desc.HTTPAddress.AddressField)
> 
> 		for j := range res.Nodes[i].Desc.Locality.Tiers {
> ```

Are any locality tiers set in this test? 


<!-- Sent from Reviewable.io -->

2024-04-17 08:08 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD8_Vu6Z-vZKIGn9DX):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Ideally, it would be nice to have one commit per-endpoint. This would make life easier for the reviewer, as they could focus on one diff per-endpoint. We could then have a final commit that updates the debug zip code to actually make use of the new redaction capabilities.
</blockquote></details>

Thanks for the suggestion. Will take care of it from the next time. 
___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-Nva87Ui8-UpxcsuFK4j:b-semjp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Isn't it still possible for the individual `NodeDetails` objects that are part of `nodesList` to be written to the node-level `status.json` file(s)? 

For example: https://github.com/cockroachdb/cockroach/blob/eaea30ee27ea666988d064be187a62154f380ebe/pkg/cli/zip_per_node.go#L187

In this case I don't think `status.json` for each node would be properly redacted.
</blockquote></details>

I think we discussed it before. 
The nodes list in this code `nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})` is further used for other ops. Hence, we are calling nodesList again with redaction flag in the following code block just after few lines from the first nodesList call=:



_Code snippet:_
```Go
if code := status.Code(errors.Cause(err)); code == codes.Unimplemented {  
  // running on non system tenant, use data from redacted NodesList()  
  nodesListRedacted, \_ := zc.status.NodesList(ctx, &serverpb.NodesListRequest{Redact: zipCtx.redact})
```
___
*[`pkg/server/status.go` line 751 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvILlUy9UqzyOlzIvjI:-NvbQCNS4rgse1uTHPYQ:b8r6quy) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L751)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

In logs, we use the special string `github.com/cockroachdb/redact.RedactedMarker()`; we should probably do the same here. Note that the redacted marker is `‹×›`, but those are not the ascii characters you might think they are.
</blockquote></details>

Nice suggestion, I replaced all `"<redacted>"` with `redact.RedactedMarker()`
___
*[`pkg/server/status.go` line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINHle2-51YaNbv9qX:-Nva9z04Ds7ur6qo4FFv:b-yyev8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L1848)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think we want to treat `key==dns` as a special case - either redact all the locality info or none of it.
</blockquote></details>

I don't know its use cases of `locality` in debug zip as well as pros and cons of redacting whole `locality`. 
Is it okay to completely remove it? @bdarnell from TSE / debugging perspective?
___
*[`pkg/server/status_test.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIOif27sSKaJBvx3DE:-NvbUxIjBDWi_Gz_YN4X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L30)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We could have a general test in all of these to encode the response to json, call `os.Hostname` to find out the current node's hostname, then ensure that the hostname doesn't appear in the json in redacted mode. It wouldn't catch everything but it might catch some regression in the future.
</blockquote></details>

Done.
___
*[`pkg/server/status_test.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIO2pz04TVRE1OxW8-:-NvaDZ1100r9jyppUTG9:b8w3rxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L35)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Nit: I wouldn't capitalize the `R` in `Unredacted`

The redacted/unredacted pairs could be done as subtests to remove a little redundancy, although maybe it's not worth it.
</blockquote></details>

Using `r` now and for the rest, I am keeping the tests as they are.
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-Nva_Fei4jLhI0_6fGFS:b-sxrvlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Are any locality tiers set in this test?
</blockquote></details>

Looks like there is no `Tiers` in `Locality` :| .


<!-- Sent from Reviewable.io -->

2024-04-17 15:16 UTC, bdarnell reviewed
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @kousiknath)

___
*[`pkg/server/status.go` line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINHle2-51YaNbv9qX:-NvgbkuB3eqCW1_6CCDC:bn0y7i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L1848)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

I don't know its use cases of `locality` in debug zip as well as pros and cons of redacting whole `locality`. 
Is it okay to completely remove it? @bdarnell from TSE / debugging perspective?
</blockquote></details>

I don't know how important `locality` is, but I think encrypting it with `cluster-secret` will be sufficient. For now we can fully redact it and replace it with cluster-secret later. 
___
*[`pkg/server/status.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvgbWrTA6l5mjISImuH:-NvgbWrTA6l5mjISImuI:bplvra3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d96d8f8a78fbf64972d2d9273cf249fb11812c7/pkg/server/status.go#L120)):*
> ```Go
> 
> 	// redactedMarker is redacted marker string for fields to be redacted in API response
> 	redactedMarker = string(redact.RedactedMarker())
> ```

Nit: Make this a `const` instead of a `var`
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvgcAJX9ALRubJvYgJJ:bvgs04o) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

Looks like there is no `Tiers` in `Locality` :| .
</blockquote></details>

Yes, I think we'll need to be more careful about setting up an input that covers all the fields we care about instead of just the base TestServerArgs. Or maybe a unit test that calls `redactNodesResponse` directly so we don't have to get everything going through TestServer. 


<!-- Sent from Reviewable.io -->

2024-04-18 11:15 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/server/status.go` line 1848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINHle2-51YaNbv9qX:-NvkOX-hAGTelE7PFXeo:b-78b9om) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L1848)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't know how important `locality` is, but I think encrypting it with `cluster-secret` will be sufficient. For now we can fully redact it and replace it with cluster-secret later.
</blockquote></details>

Ok. I removed the specific condition based on "dns" key, rather redacting all the values inside `Tiers` inside `Locality` struct.
___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NvkQmWo7_hFc0xdcrKa:b-ji6ksg) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Pull the loop over Locality.Tiers into a separate function so it can be shared with the previous one.
</blockquote></details>

The loops is of 1 line only. Also, one `Locality.Tiers` loop is on `Nodes[x].Desc`, another is on `Ranges[i]`. So does not look  like they can be shared.
___
*[`pkg/server/status.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvgbWrTA6l5mjISImuH:-NvkIey82HV0nH3r5O-Z:bi0gu0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d96d8f8a78fbf64972d2d9273cf249fb11812c7/pkg/server/status.go#L120)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Nit: Make this a `const` instead of a `var`
</blockquote></details>

Tried doing that already, it says `Const initializer redact.RedactedMarker() is not a constant`
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvkWDRAD7Wtnj7Ndxh0:b5lpzf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes, I think we'll need to be more careful about setting up an input that covers all the fields we care about instead of just the base TestServerArgs. Or maybe a unit test that calls `redactNodesResponse` directly so we don't have to get everything going through TestServer.
</blockquote></details>

I think we wanted to test end to end flow of these APIs, hence wanted to get as much as real response as possible. Thus spinning up directly helps. Looks like the test server kv is not returning any `Locality` information. Is there any way to return that information actually? 


<!-- Sent from Reviewable.io -->

2024-04-18 11:16 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvkupswBAWr82xohs87:b-glfyf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

I think we wanted to test end to end flow of these APIs, hence wanted to get as much as real response as possible. Thus spinning up directly helps. Looks like the test server kv is not returning any `Locality` information. Is there any way to return that information actually?
</blockquote></details>

Ok, I added an unit test for `redactNodesResponse`


<!-- Sent from Reviewable.io -->

2024-04-18 14:41 UTC, bdarnell approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @kousiknath)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvldoBg5hxdIilIjMdw):*
It looks like you now have two commits with the same message; please squash them back together before merging. 
___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NvlcRvu6e2e2cc0JQKM:bl319mp) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

The loops is of 1 line only. Also, one `Locality.Tiers` loop is on `Nodes[x].Desc`, another is on `Ranges[i]`. So does not look  like they can be shared.
</blockquote></details>

I'm talking about the inner loop only - isn't that a `serverpb.Locality` in both places? It's a small loop now but it gets more complicated when we introduce `cluster-secret` encryption, which is why I want to pull it out now. 
___
*[`pkg/server/status.go` line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvgbWrTA6l5mjISImuH:-NvlcMp016CWP5CnS_pY:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d96d8f8a78fbf64972d2d9273cf249fb11812c7/pkg/server/status.go#L120)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

Tried doing that already, it says `Const initializer redact.RedactedMarker() is not a constant`
</blockquote></details>

OK
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvldVYrEGAcfDh_kP5f:b5p85rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
> Is there any way to return that information actually?

Maybe there's a way to add locality information to TestServerArgs, or to make it do this by default, but I don't think it's worth it. I think it's better to have a unit test like this. 


<!-- Sent from Reviewable.io -->

2024-04-18 18:43 UTC, abarganier requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dhartunian, and @kousiknath)

___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-NvmTlrK9C_Nsy_Ngtd7:b-ocqvek) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

I think we discussed it before. 
The nodes list in this code `nodesList, err = zc.status.NodesList(ctx, &serverpb.NodesListRequest{})` is further used for other ops. Hence, we are calling nodesList again with redaction flag in the following code block just after few lines from the first nodesList call=:
</blockquote></details>

I understand that we're making a separate, redacted request for the cluster-wide `nodes.json` file.

However, the *unredacted* `NodesList()` is still being written to `nodes/<node_id>/status.json`, which is what I was referring to in my original comment. 

Here's the sequence:
1. [The unredacted `nodesList` is provided to the `forAllNodes` function.](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L304). We also provide a [callback](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L305), which is invoked within `forAllNodes`.
2. [For each node in the `nodesList` that we provided to `forAllNodes`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L120), we invoke the [callback provided to `forAllNodes`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L131),  passing it the unredacted `nodeDetails` from the `nodesList`.
3. Those unredacted `nodeDetails` are [received as an argument to `collectPerNodeData`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_per_node.go#L147), which was the callback given to `forAllNodes`.
4. A code path exists for those unredacted `nodeDetails` to be written to `nodes/<node_id>/status.json`, even if the user indicated that they wanted redaction.

This would be a leak of sensitive data.


<!-- Sent from Reviewable.io -->

2024-04-19 08:32 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`-- commits` line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvldoBg5hxdIilIjMdw):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It looks like you now have two commits with the same message; please squash them back together before merging.
</blockquote></details>

Yesh, I just squashed them.
___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-NvpGu_D1HoGJ82KIrQE:bp5a0co) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I understand that we're making a separate, redacted request for the cluster-wide `nodes.json` file.

However, the *unredacted* `NodesList()` is still being written to `nodes/<node_id>/status.json`, which is what I was referring to in my original comment. 

Here's the sequence:
1. [The unredacted `nodesList` is provided to the `forAllNodes` function.](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L304). We also provide a [callback](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L305), which is invoked within `forAllNodes`.
2. [For each node in the `nodesList` that we provided to `forAllNodes`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L120), we invoke the [callback provided to `forAllNodes`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip.go#L131),  passing it the unredacted `nodeDetails` from the `nodesList`.
3. Those unredacted `nodeDetails` are [received as an argument to `collectPerNodeData`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_per_node.go#L147), which was the callback given to `forAllNodes`.
4. A code path exists for those unredacted `nodeDetails` to be written to `nodes/<node_id>/status.json`, even if the user indicated that they wanted redaction.

This would be a leak of sensitive data.
</blockquote></details>

In my 2nd last commit, I addressed this already I think. From `zip_cluster_wide/collectClusterData()`, we are now returning a redacted nodes list as well along with the usual unredacted nodes list. And inside `runDebugZip`, we pass the redacted nodes list while calling `forAllNodes()`. You can check the diff and please let me know if still I am missing anything here.
___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NvpSrgs7afJyvXgxSGM:b-j3wanu) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm talking about the inner loop only - isn't that a `serverpb.Locality` in both places? It's a small loop now but it gets more complicated when we introduce `cluster-secret` encryption, which is why I want to pull it out now.
</blockquote></details>

Looks like they are different `Locality`.
- The `NodesResponse .Locality` comes from `roachpb`
- Whereas, the `RangesResponse.Locality` comes from `serverpb`
___
*[`pkg/server/status_test.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvIP7-Z8777_b-_tk6c:-NvpToKP5VNdO9f51qLr:bb77u1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status_test.go#L106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> Is there any way to return that information actually?

Maybe there's a way to add locality information to TestServerArgs, or to make it do this by default, but I don't think it's worth it. I think it's better to have a unit test like this.
</blockquote></details>

Yeah


<!-- Sent from Reviewable.io -->

2024-04-19 18:41 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @kousiknath)

___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NvreM3y8FdY3FtZQebV:bywyzeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

Looks like they are different `Locality`.
- The `NodesResponse .Locality` comes from `roachpb`
- Whereas, the `RangesResponse.Locality` comes from `serverpb`
</blockquote></details>

Ah, OK. We could maybe do something with generics but it's probably not worth it. 


<!-- Sent from Reviewable.io -->

2024-04-22 13:57 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @kousiknath)

___
*[`pkg/cli/zip.go` line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nw550Va6EEKvVTCn65h:-Nw550Va6EEKvVTCn65i:bz7px7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e87cb929e4ca4b784508327a92de43cccf1298b/pkg/cli/zip.go#L293)):*
> ```Go
> 			// and livenessByNodeID is null. For a KV server, the nodeList will
> 			// be a list of KV nodes along with the corresponding node liveness data.
> 			nodesList, redactedNodesList, livenessByNodeID, err := zc.collectClusterData(ctx)
> ```

why don't we simply return the redacted nodes list every time as the first return value? Then its redacted status relies on `zipCtx.redact` and the caller gets the correctly redacted object.

it looks like the `nodesList` is only used in the two function calls below and I think sending the redacted list of `collectCPUProfiles` should be fine, it probably only needs their IDs.


<!-- Sent from Reviewable.io -->

2024-04-22 21:28 UTC, abarganier requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @kousiknath)

___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-Nw5oDmk-Qgt9Ll9H208:b-7l1kk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

In my 2nd last commit, I addressed this already I think. From `zip_cluster_wide/collectClusterData()`, we are now returning a redacted nodes list as well along with the usual unredacted nodes list. And inside `runDebugZip`, we pass the redacted nodes list while calling `forAllNodes()`. You can check the diff and please let me know if still I am missing anything here.
</blockquote></details>

Ah okay, sorry, I missed the point where you passed the redacted response to `forAllNodes()`. 

Despite that, I still don't quite understand how this works.

This means that each `serverpb.NodeDetails` that's passed to `collectPerNodeData()` has been redacted, correct? 

Here's the code in this PR that redacts that information server-side:
```
func (s *statusServer) redactNodeListResponse(nodeListResponse *serverpb.NodesListResponse) *serverpb.NodesListResponse {
	for i := range nodeListResponse.Nodes {
		nodeListResponse.Nodes[i].Address.AddressField = redactedMarker
		nodeListResponse.Nodes[i].SQLAddress.AddressField = redactedMarker
	}

	return nodeListResponse
}
``` 

Meanwhile, in the `collectPerNodeData()` function, we have [this code](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_per_node.go#L198-L202):
```
sqlAddr := nodeDetails.SQLAddress
if sqlAddr.IsEmpty() {
	sqlAddr = nodeDetails.Address
}
```

Shouldn't those fields have been redacted? How can this code continue to function with this information redacted?

I tried testing this locally. 

First, I added a print statement to print out the addresses in the above code block within `collectPerNodeData()`. Then, I started a single node cluster:
```
$ ./cockroach start-single-node --insecure
```
Then, I ran a redacted `debug zip`:
```
$ ./cockroach debug zip ~/Downloads/testzip.zip --insecure
```

Here's what printed:
```
nodeDetails.SQLAddress: crlMBP-NR362FWT1GODM0.local:26257
nodeDetails.Address: crlMBP-NR362FWT1GODM0.local:26257
```

Don't we expect this to be redacted? If it *is* redacted, then aren't we unable to determine the correct address? 


<!-- Sent from Reviewable.io -->

2024-04-23 15:27 UTC, abarganier commented
(Accidentally hit the close button, sorry 😓)

2024-04-29 06:55 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/cli/zip.go` line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nw550Va6EEKvVTCn65h:-NwDmlBX084tvbsBO3hc:bo6umzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e87cb929e4ca4b784508327a92de43cccf1298b/pkg/cli/zip.go#L293)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why don't we simply return the redacted nodes list every time as the first return value? Then its redacted status relies on `zipCtx.redact` and the caller gets the correctly redacted object.

it looks like the `nodesList` is only used in the two function calls below and I think sending the redacted list of `collectCPUProfiles` should be fine, it probably only needs their IDs.
</blockquote></details>

I thought the function `collectCPUProfiles` would fail, but looks like it does not use the Address fields from the `NodeDetails` objects. It only uses the `Node.Id` field. So, I am removing the existing `nodesList` and keeping the new `redactedNodesList`. It should be fine.
___
*[`pkg/cli/zip_cluster_wide.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvD9zuV4ETqHwxLZSI-:-Nwccfc3DoMZghrkl9-s:b-ybz93m) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/cli/zip_cluster_wide.go#L113)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ah okay, sorry, I missed the point where you passed the redacted response to `forAllNodes()`. 

Despite that, I still don't quite understand how this works.

This means that each `serverpb.NodeDetails` that's passed to `collectPerNodeData()` has been redacted, correct? 

Here's the code in this PR that redacts that information server-side:
```
func (s *statusServer) redactNodeListResponse(nodeListResponse *serverpb.NodesListResponse) *serverpb.NodesListResponse {
	for i := range nodeListResponse.Nodes {
		nodeListResponse.Nodes[i].Address.AddressField = redactedMarker
		nodeListResponse.Nodes[i].SQLAddress.AddressField = redactedMarker
	}

	return nodeListResponse
}
``` 

Meanwhile, in the `collectPerNodeData()` function, we have [this code](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_per_node.go#L198-L202):
```
sqlAddr := nodeDetails.SQLAddress
if sqlAddr.IsEmpty() {
	sqlAddr = nodeDetails.Address
}
```

Shouldn't those fields have been redacted? How can this code continue to function with this information redacted?

I tried testing this locally. 

First, I added a print statement to print out the addresses in the above code block within `collectPerNodeData()`. Then, I started a single node cluster:
```
$ ./cockroach start-single-node --insecure
```
Then, I ran a redacted `debug zip`:
```
$ ./cockroach debug zip ~/Downloads/testzip.zip --insecure
```

Here's what printed:
```
nodeDetails.SQLAddress: crlMBP-NR362FWT1GODM0.local:26257
nodeDetails.Address: crlMBP-NR362FWT1GODM0.local:26257
```

Don't we expect this to be redacted? If it *is* redacted, then aren't we unable to determine the correct address?
</blockquote></details>

Fixed it. 
___
*[`pkg/server/status.go` line 2347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NvINdd97VOYyg1CmVEf:-NwcciX3-_BUubcK1p1F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/726f538413ec373be3ecfe60ceb26e10e76bf783/pkg/server/status.go#L2347)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Ah, OK. We could maybe do something with generics but it's probably not worth it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-29 23:06 UTC, dhartunian reviewed
I think this design needs some iteration instead of adding a second arg to lots of methods. Details below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-:-Nwg5llw5wCDMbXrkSp-:b-s3zio)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @kousiknath)

___
*[`pkg/cli/zip.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg4NOJA0wJcJ0ZnMmr:-Nwg4NOJA0wJcJ0ZnMms:b-5lwmxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L97)):*
> ```Go
> 	ctx context.Context,
> 	nodesList *serverpb.NodesListResponse,
> 	redactedNodesList *serverpb.NodesListResponse,
> ```

We need to find a solution here that does not involve passing two of the same object to this function. I don't understand the need for it.

The only usage of `nodesList` that I see is to grab `SQLAddress`. If that's the only requirement, let's just pass in SQLAddress directly from the caller. I think limiting the usage of two different copies of this data structure will prevent confusion and errors.
___
*[`pkg/cli/zip.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg3EbC-kOUxXGpxR3p:-Nwg3EbC-kOUxXGpxR3q:b-u827xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L153)):*
> ```Go
> 	for i := range redactedNodesList.Nodes {
> 		if redactedNodesList.Nodes[i].NodeID == nodeId {
> 			return &redactedNodesList.Nodes[i]
> ```

why are you returning a pointer if you just deref afterwards anyway?
___
*[`pkg/cli/zip.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg5HWV-rqrfZBvijNP:-Nwg5HWV-rqrfZBvijNQ:b-rbny2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L321)):*
> ```Go
> 			// Collect the per-node data.
> 			if err := zc.forAllNodes(ctx, nodesList, redactedNodesList, func(ctx context.Context, nodeDetails serverpb.NodeDetails, nodesStatus *statuspb.NodeStatus, redactedNodeDetails serverpb.NodeDetails) error {
> 				return zc.collectPerNodeData(ctx, nodeDetails, nodesStatus, livenessByNodeID, redactedNodeDetails)
> ```

This design is confusing. There are two node lists, and two nodeDetails objects now which is confusing.

As mentioned above, I think you should look at the usage of `nodesList` and split the args into what you need from the **unredacted** list, and then separately take the redacted list as an argument. 
___
*[`pkg/cli/zip_cluster_wide.go` line 22 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg3b-j8V5uJv5yDoY6:-Nwg3b-j8V5uJv5yDoY7:b-hxbtrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip_cluster_wide.go#L22)):*
> ```Go
> 	"google.golang.org/grpc/codes"
> 	"google.golang.org/grpc/status"
> 	"sort"
> ```

nit: import ordering


<!-- Sent from Reviewable.io -->

2024-04-30 11:03 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/cli/zip.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg4NOJA0wJcJ0ZnMmr:-NwieHc-35RJKucR_uvl:bdc4i6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L97)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

We need to find a solution here that does not involve passing two of the same object to this function. I don't understand the need for it.

The only usage of `nodesList` that I see is to grab `SQLAddress`. If that's the only requirement, let's just pass in SQLAddress directly from the caller. I think limiting the usage of two different copies of this data structure will prevent confusion and errors.
</blockquote></details>

Added a comment on the previous comment.
___
*[`pkg/cli/zip.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg5HWV-rqrfZBvijNP:-NwicpQJCfcBXKtopEqZ:b-lqx2hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L321)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This design is confusing. There are two node lists, and two nodeDetails objects now which is confusing.

As mentioned above, I think you should look at the usage of `nodesList` and split the args into what you need from the **unredacted** list, and then separately take the redacted list as an argument.
</blockquote></details>

The `NodeDetails` struct itself is very small containing only `nodeID`, `Address` and `SQLAddress` fields. We need full `redactedNodeDetails` object definitely so that we can log it in json. 

At the same time, we need `NodeId`, `SQLAddress` fields from unredacted `nodeDetails` object (basically, 2 out of 3 fields we need from `nodeDetails`anyway). So, passing `nodeID` and `SQLAddress` individually actually does not make it any simple either. 


<!-- Sent from Reviewable.io -->

2024-04-30 12:50 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @kousiknath)

___
*[`pkg/cli/zip.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg3EbC-kOUxXGpxR3p:-Nwiy_2SB6TX2l-FW_kK:bo15av5) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L153)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why are you returning a pointer if you just deref afterwards anyway?
</blockquote></details>

additionally, since you deref above from this function that can return nil, this can result in a runtime panic.
___
*[`pkg/cli/zip.go` line 321 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg5HWV-rqrfZBvijNP:-NwiykWz4faH7NDkd0Mk:bj4mt55) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L321)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

The `NodeDetails` struct itself is very small containing only `nodeID`, `Address` and `SQLAddress` fields. We need full `redactedNodeDetails` object definitely so that we can log it in json. 

At the same time, we need `NodeId`, `SQLAddress` fields from unredacted `nodeDetails` object (basically, 2 out of 3 fields we need from `nodeDetails`anyway). So, passing `nodeID` and `SQLAddress` individually actually does not make it any simple either.
</blockquote></details>

Ok. I won't belabor it.
___
*[`pkg/server/status_test.go` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NwiwzlX-Lx3Yvc9qTyI:-NwiwzlX-Lx3Yvc9qTyJ:b7v9sph) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/server/status_test.go#L1)):*
> ```Go
> package server
> ```

this file will need the BSL license on top. linter should flag this.


<!-- Sent from Reviewable.io -->

2024-04-30 17:51 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/cli/zip.go` line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwg3EbC-kOUxXGpxR3p:-Nwk7ZWR2ZS6f4b-Z71D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/cli/zip.go#L153)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

additionally, since you deref above from this function that can return nil, this can result in a runtime panic.
</blockquote></details>

Done.
___
*[`pkg/server/status_test.go` line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NwiwzlX-Lx3Yvc9qTyI:-Nwk6epG9f_Ibdsss96J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73aca2024462153440fd3bba5f8891fb41966d11/pkg/server/status_test.go#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

this file will need the BSL license on top. linter should flag this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 22:29 UTC, dhartunian reviewed
You have some additional linter/static check failures. Take a look at the failed GH Actions and click through to the engflow runs that are linked in the output to investigate.

The test `TestUnavailableZip` is failing. You can run it locally via `./dev test pkg/cli --filter=TestUnavailableZip`. It got stuck for a long time for me. I explained what I think the problem is below.

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-:-Nwl1M3A7uHFUvSdydLO:b-ltk1yy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @kousiknath)

___
*[`pkg/cli/zip_cluster_wide.go` line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl0YvsB2dw_TtCkdkH:-Nwl0YvsB2dw_TtCkdkI:bbzj2vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L17)):*
> ```Go
> 	"fmt"
> 	"sort"
> 	
> ```

stray whitespace: please configure your editor to remove trailing whitespace. you should have the `crlfmt` linter set up as a file watcher.
___
*[`pkg/cli/zip_cluster_wide.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl57st1l-DPp_aphz3:-Nwl57st1l-DPp_aphz4:b-6u7ycr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L109)):*
> ```Go
> 	}
> 
> 	nodesListRedacted, _ := zc.status.NodesList(ctx, &serverpb.NodesListRequest{Redact: zipCtx.redact})
> ```

You have to handle the error that's returned here. otherwise if you proceed, you might have a bad response.

Consider moving this call lower in the method because clusters with unavailable nodes will hit this failure first before the one below and it could cause some confusion in the output since "requesting nodes" won't have been emitted first for instance.

Also, wrap this in a `runZipFn` like the call below since that adds a timeout. The reason the `TestUnavailableZip` test fails is because it's getting stuck here without a timeout and hanging until it gives up. The wrapper ensures that we can proceed even on a cluster with uneven availability.
___
*[`pkg/server/status_test.go` line 1 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl0iyVBblKP_xaE0cf:-Nwl0iyVBblKP_xaE0cg:b-8zncxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/server/status_test.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

nit: if you copy/paste, update the year on a new file.
___
*[`pkg/server/status_test.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl6Rwi2UqDLDY95gFK:-Nwl6Rwi2UqDLDY95gFL:blzmlzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/server/status_test.go#L45)):*
> ```Go
> 
> 	jsonResponse, _ := json.Marshal(res)
> 	hostname, _ := os.Hostname()
> ```

All of these errors above (and below in the rest of the file and tests should have `require.NoError(t, err)`. Especially the API calls to the server can fail for all sorts of reasons.


<!-- Sent from Reviewable.io -->

2024-05-02 12:38 UTC, kousiknath reviewed
This is fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-:-NwtJ75DExbLO38O9aMO:b9e018z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/cli/zip_cluster_wide.go` line 17 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl0YvsB2dw_TtCkdkH:-NwsDseLC504PCZWlPTQ:bo6w7ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L17)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

stray whitespace: please configure your editor to remove trailing whitespace. you should have the `crlfmt` linter set up as a file watcher.
</blockquote></details>

I don't see any extra / trailing whitespace on any line. Also, the extra new line exists in other file also.
___
*[`pkg/cli/zip_cluster_wide.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl57st1l-DPp_aphz3:-NwsRswmCFLD5OltHEUQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L109)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

You have to handle the error that's returned here. otherwise if you proceed, you might have a bad response.

Consider moving this call lower in the method because clusters with unavailable nodes will hit this failure first before the one below and it could cause some confusion in the output since "requesting nodes" won't have been emitted first for instance.

Also, wrap this in a `runZipFn` like the call below since that adds a timeout. The reason the `TestUnavailableZip` test fails is because it's getting stuck here without a timeout and hanging until it gives up. The wrapper ensures that we can proceed even on a cluster with uneven availability.
</blockquote></details>

Done.
___
*[`pkg/server/status_test.go` line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl6Rwi2UqDLDY95gFK:-NwsUisWCANM43GigzWE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/server/status_test.go#L45)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

All of these errors above (and below in the rest of the file and tests should have `require.NoError(t, err)`. Especially the API calls to the server can fail for all sorts of reasons.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-03 22:05 UTC, dhartunian reviewed
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @kousiknath)

___
*[`pkg/cli/zip.go` line 321 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NwtZR-I6UkYdPet0pJJ:-NwtZR-I6UkYdPet0pJK:b-ssqgxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c05d3af64b3ab2373f31bb6635d83d5b2b81b082/pkg/cli/zip.go#L321)):*
> ```Go
> 			// Collect the CPU profiles, before the other per-node requests
> 			// below possibly influences the nodes and thus CPU profiles.
> 			if err := zc.collectCPUProfiles(ctx, nodesList, livenessByNodeID); err != nil {
> ```

why did this change back to `nodesList`?
___
*[`pkg/cli/zip_cluster_wide.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl57st1l-DPp_aphz3:-NwtYe_YB7bevtMjGboE:b1wyc5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L109)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can now remove this declaration and rename the return var to `nodesListRedacted` that you added (line 83) and it will match the existing `nodesList` declaration and usage.


<!-- Sent from Reviewable.io -->

2024-05-06 07:33 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @bdarnell, and @dhartunian)

___
*[`pkg/cli/zip.go` line 321 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-NwtZR-I6UkYdPet0pJJ:-NxBi1UU9hTBY94YmMgt:b-44rja6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c05d3af64b3ab2373f31bb6635d83d5b2b81b082/pkg/cli/zip.go#L321)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why did this change back to `nodesList`?
</blockquote></details>

Inside `collectCPUProfiles()`, we are using `NodeId`. So, whether we use redacted or un-redacted nodes list, they are same. Hence, I reverted it back to original.
___
*[`pkg/cli/zip_cluster_wide.go` line 109 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-Nwl57st1l-DPp_aphz3:-NxBjS4t58wNxpzjeqiF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d148757df043b1e8247537853e36039451ea0c69/pkg/cli/zip_cluster_wide.go#L109)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

You can now remove this declaration and rename the return var to `nodesListRedacted` that you added (line 83) and it will match the existing `nodesList` declaration and usage.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 17:02 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for all the changes.

I found some additional hostname information that should be redacted, but filed a separate issue for those that you can address with a separate PR: https://github.com/cockroachdb/cockroach/issues/123678

> Reviewed 1 of 8 files at r1, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-:-NxDqJW36pFyjL-Noq50:b-hmk0p2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @bdarnell)



<!-- Sent from Reviewable.io -->

2024-05-07 16:31 UTC, abarganier approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122181#-:-NxItHP4BQ5mnC1b4sJe:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @bdarnell and @dhartunian)



<!-- Sent from Reviewable.io -->

2024-05-08 14:03 UTC, dhartunian commented
bors r+

2024-05-08 17:41 UTC, dhartunian commented
@kousiknath you need to rebase on `master` because there was a change merged recently that causes a failure in the test you added when bors tries to merge. Just need to re-record the output.

2024-05-09 07:01 UTC, kousiknath commented
bors r+

2024-05-09 07:28 UTC, merged