sql/delegate: added object_type and object_name to show grants
cockroachdb/cockroach pull request #122197
Opened 2024-04-11 14:43 UTC by Dedej-Bergin

Previously, we used the relation_name column to show all objects however we now have objects such as function and types that are not relations so the name of this column was changed to object_name in these code changes. Additionally with the larger variety in types a new column object_type is added that identifies the type of an object.

Fixes: #119775
Release note (sql change): object_type can now be seen with the show grants command and relation_name column is now shown as object_name.

2024-04-11 14:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/122197)
<!-- Reviewable:end -->

2024-04-11 21:05 UTC, rafiss requested changes
nice work! it looks like you need to update a few other logic tests. the test results in the CI can tell you which files to adjust

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-:-NvDvb6uCop7BBfpSJ0S:b5miea4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`pkg/sql/delegate/show_grants.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDwPnB0z2ThLwlK5w7:-NvDwPnB0z2ThLwlK5w8:b-iczevf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L66)):*
> ```Go
>   FROM "".information_schema.table_privileges tp
>   LEFT JOIN
>        "".information_schema.sequences s ON tp.table_name = s.sequence_name`
> ```

unfortunately we can't just join on name here. it is possible for the table name and sequence name to be the same if they are in different schemas.

for example:
```
CREATE SCHEMA s1;
CREATE SCHEMA s2;
CREATE TABLE s1.abc (a INT);
CREATE SEQUENCE s2.abc;
```

so we would want 
```
LEFT JOIN "".information_schema.sequences s ON (
  tp.table_catalog = s.sequence_catalog AND
  tp.table_schema = s.sequence_schema AND
  tp.table_name = s.sequence_name
)
```
___
*[`pkg/sql/delegate/show_grants.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDu_hh6P1hgiWOE60N:-NvDu_hh6P1hgiWOE60O:bc85xnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L93)):*
> ```Go
> SELECT *
>   FROM (
>         SELECT name AS connection_name,
> ```

nit: i think we should also add the object_type column here.
___
*[`pkg/sql/delegate/show_grants.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDvKK86TfN-gw0NGA-:-NvDvKK93JkWrtkKYrln:b4ntw6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L339)):*
> ```Go
> 		}
> 	} else {
> 		nameCols = "database_name, schema_name, object_type, object_name,"
> ```

nit: let's put object_type after object_name. it's more natural for all the names to be next to each other in the output
___
*[`pkg/sql/delegate/show_grants.go` line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDujMT97un-OWMDVYo:-NvDujMT97un-OWMDVYp:b-8x8610) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L361)):*
> ```Go
> 			`SELECT database_name, schema_name, object_type, routine_signature AS object_name, grantee, privilege_type, is_grantable FROM (`)
> 		source.WriteString(routineQuery)
> 		source.WriteByte(')')
> ```

this is not related to the original issue, but this part of the code should also add a UNION ALL with the externalConnectionsQuery. i think we should just go ahead and fix it now, but let's do it in a different PR
___
*[`pkg/sql/logictest/testdata/logic_test/role` line 1892 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDrbVN-3582aHvesSk:-NvDrbVN-3582aHvesSl:bj9otcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/logictest/testdata/logic_test/role#L1892)):*
> ```
> grant usage on sequence test_sequence to roach;
> 
> query TTTTTTB colnames,rowsort
> ```

nit: add a comment to say that the purpose of this test is to verify the object_type column
___
*[`pkg/sql/logictest/testdata/logic_test/role` line 1893 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDrgad7qWR83TRBIIK:-NvDrgad7qWR83TRBIIL:b-5miy85) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/logictest/testdata/logic_test/role#L1893)):*
> ```
> 
> query TTTTTTB colnames,rowsort
> select * from [show grants for roach]
> ```

nit: there's no advantage in doing `select * from [show grants for roach]` versus just `show grants from roach`

the main reason to use the `[]` syntax here is if we only care about certain column names, like: `select object_type, object_name, grantee from [show grants for roach]`. this is useful so that the test output doesn't get too big to read easily, so we might want to make that change to only look at relevant columns here.


<!-- Sent from Reviewable.io -->

2024-04-15 20:21 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122197)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @rafiss)

___
*[`pkg/sql/delegate/show_grants.go` line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDwPnB0z2ThLwlK5w7:-NvXy18C1XkLmU8Mb5Sn:bc18ytx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L66)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

unfortunately we can't just join on name here. it is possible for the table name and sequence name to be the same if they are in different schemas.

for example:
```
CREATE SCHEMA s1;
CREATE SCHEMA s2;
CREATE TABLE s1.abc (a INT);
CREATE SEQUENCE s2.abc;
```

so we would want 
```
LEFT JOIN "".information_schema.sequences s ON (
  tp.table_catalog = s.sequence_catalog AND
  tp.table_schema = s.sequence_schema AND
  tp.table_name = s.sequence_name
)
```
</blockquote></details>

Thanks Rafi, I went ahead and made this change!
___
*[`pkg/sql/delegate/show_grants.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDu_hh6P1hgiWOE60N:-NvXy8-PE08BEgSq-eni:b-hpijrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L93)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: i think we should also add the object_type column here.
</blockquote></details>

Thanks Rafi, I was thinking to add object_type for external connections on the next pull request to fix this PR: #122199 ... if that's okay? Otherwise I can add it here.
___
*[`pkg/sql/delegate/show_grants.go` line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDvKK86TfN-gw0NGA-:-NvYNoGSAIjQF6lBLHF9:btewuhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L339)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's put object_type after object_name. it's more natural for all the names to be next to each other in the output
</blockquote></details>

Sounds good, definitely makes more sense to have object_type after object_name.  I went ahead and made this change, thanks!
___
*[`pkg/sql/delegate/show_grants.go` line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDujMT97un-OWMDVYo:-NvYO0fq6vTx24We8TAz:b-1tn13d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/delegate/show_grants.go#L361)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is not related to the original issue, but this part of the code should also add a UNION ALL with the externalConnectionsQuery. i think we should just go ahead and fix it now, but let's do it in a different PR
</blockquote></details>

Thanks Rafi, I'll do it in the next PR: #122199 since it's already opened, but next time for something similar I'll make sure not to open another PR for it.
___
*[`pkg/sql/logictest/testdata/logic_test/role` line 1892 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDrbVN-3582aHvesSk:-NvYP9JF92_YZS0rJvRO:b-79t02u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/logictest/testdata/logic_test/role#L1892)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: add a comment to say that the purpose of this test is to verify the object_type column
</blockquote></details>

I added the comment.
___
*[`pkg/sql/logictest/testdata/logic_test/role` line 1893 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-NvDrgad7qWR83TRBIIK:-NvYPEIR0lNo-L9jcM5z:bua6xck) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a1ae13d7db9115772c96228e94aed6d0b42a592/pkg/sql/logictest/testdata/logic_test/role#L1893)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: there's no advantage in doing `select * from [show grants for roach]` versus just `show grants from roach`

the main reason to use the `[]` syntax here is if we only care about certain column names, like: `select object_type, object_name, grantee from [show grants for roach]`. this is useful so that the test output doesn't get too big to read easily, so we might want to make that change to only look at relevant columns here.
</blockquote></details>

It's definitely better to not have the select * part, I went ahead and made the change, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-04-17 15:54 UTC, rafiss approved these changes
lgtm! nice work

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122197#-:-Nvgl0nZ1QE5JrtP8toK:b-m0nb8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @dt)



<!-- Sent from Reviewable.io -->

2024-04-17 16:36 UTC, Dedej-Bergin commented
bors r+

2024-04-17 20:08 UTC, merged

2024-04-18 21:03 UTC, Dedej-Bergin commented
blathers backport 23.2