stats: set the type resolver when dealing with virtual comp cols
cockroachdb/cockroach pull request #122313
Opened 2024-04-12 22:42 UTC by yuzefovich

We forgot to set the type resolver on the sema context that we create when dealing with virtual computed columns, and as a result stats collection on tables with such columns now might fail altogether. In a separate change I'll audit all callers of `MakeSemaContext` to prevent such a mistake in the future.

Fixes: #122312.

Release note (bug fix): CockroachDB could fail to collect table statistics on tables that have virtual computed columns of user-defined type if `optimizer_use_virtual_computed_column_stats` is enabled. The setting is introduced in 23.2.4 version, so only this particular version is affected.

2024-04-12 22:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/122313)
<!-- Reviewable:end -->

2024-04-12 22:55 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Wow, thank you! How did you find this?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122313#-:-NvJWRJd00HYYJE6FJNj:b-agn3v4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)



<!-- Sent from Reviewable.io -->

2024-04-12 22:56 UTC, michae2 commented
(This also needs to go back to 23.1.)

2024-04-12 23:02 UTC, yuzefovich commented
It wasn't me - Adam found it on the DRT cluster https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1712950658649649.

2024-04-12 23:26 UTC, michae2 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122313)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122313#-NvJcBgPCTymRBZW5YRI):*
Instead of `optimizer_use_virtual_computed_column_stats` this should be cluster setting `sql.stats.virtual_computed_columns.enabled`


<!-- Sent from Reviewable.io -->

2024-04-12 23:32 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122313)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122313#-NvJcBgPCTymRBZW5YRI):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Instead of `optimizer_use_virtual_computed_column_stats` this should be cluster setting `sql.stats.virtual_computed_columns.enabled`
</blockquote></details>

Good catch, done.


<!-- Sent from Reviewable.io -->

2024-04-12 23:34 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122313#-:-NvJeKbs02VzC3lEA0Vp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)



<!-- Sent from Reviewable.io -->

2024-04-13 00:09 UTC, yuzefovich commented
TFTR!

bors r+

2024-04-13 00:41 UTC, merged