roachtest/multiregion_leasing: fix flaky benchmark test
cockroachdb/cockroach pull request #122655
Opened 2024-04-18 20:37 UTC by fqazi

Previously, the leasing benchmark was flaky because of latency issues between the roachtest machine and the server could vary. This test would intentionally create a large number of tables and select from each one on each node, with the purpose of showing a regression when expiry based table leasing was used. This unfortunately could also be impacted between the latency observed and the benchmark could flake even with multiple samples. To address this, this patch will execute the select statements at the server side without waiting on the client, and time at the server. Additionally the query used is modified to only lease out the descriptor and not fetch *any* data so that its pure leasing benchmark.

Fixes: #122344

Release note: None

2024-04-22 16:43 UTC, rafiss requested changes
nice fix, thanks!

i kicked off a test in CI here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14950609?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-:-Nw5g5iR8xvv73CzW2px:bwioa6l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @fqazi, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5dnw5CNcFDnr5IkYn:-Nw5dnw5CNcFDnr5IkYo:b-cufozs) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L162)):*
> ```Go
> 						output, err := c.RunWithDetailsSingleNode(ctx,
> 							t.L(),
> 							install.WithNodes(install.Nodes{install.Node(nodeIdx)}),
> ```

nit; use `option.WithNodes(c.Node(nodeIdx))`
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5e8379h7dd49aiTLA:-Nw5e838Aw6OwvGHOJMA:bqks9zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L163)):*
> ```Go
> 							t.L(),
> 							install.WithNodes(install.Nodes{install.Node(nodeIdx)}),
> 							fmt.Sprintf("time -p ./cockroach sql -f %s --url=%q --certs-dir="+install.CockroachNodeCertsDir+" > /dev/null",
> ```

nit: this can just be:
```
fmt.Sprintf(
	"time -p ./cockroach sql -f %s --url='{pgurl:%d}' > /dev/null",
	selectQueryFileName,
	nodeIdx),
)
```
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5f7i9D7V-4jAdgtw7:-Nw5f7i9D7V-4jAdgtw8:b1fejmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L192)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			durations[modeIdx] = totalTime.Load()
> ```

to make sure the `durations` slice is still readable when printing, let's make this
```
durations[modeIdx] = time.Duration(totalTime.Load()) * time.Millisecond
```
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5fvWq8RkpNkQJvUhY:-Nw5fvWq8RkpNkQJvUhZ:bpn0guk) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L193)):*
> ```Go
> 			}
> 			durations[modeIdx] = totalTime.Load()
> 			t.Status(fmt.Sprintf("benchmark completed for session_based_leasing=%t in %d", sessionBasedLeasingEnabled, totalTime.Load()))
> ```

and here, let's use `durations[modeIdx]` instead of `totalTime.Load()`
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5g0FY9HWNlQje2142:-Nw5g0FY9HWNlQje2143:bupq48e) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L211)):*
> ```Go
> 	// We see an up to 50% improvement in this scenario, so fail fatally if we miss
> 	// a percentage of that mark.
> 	if percentage < 15 {
> ```

nit: the comment says 50 but the code says 15


<!-- Sent from Reviewable.io -->

2024-04-23 00:24 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122655)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @rafiss, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5e8379h7dd49aiTLA:-Nw76jCNDkX8obxGXazi:b9n2zpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L163)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this can just be:
```
fmt.Sprintf(
	"time -p ./cockroach sql -f %s --url='{pgurl:%d}' > /dev/null",
	selectQueryFileName,
	nodeIdx),
)
```
</blockquote></details>

Done.

Good, catch. I forgot about that syntax.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5f7i9D7V-4jAdgtw7:-Nw773ylDCkfjVRQDQAx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L192)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to make sure the `durations` slice is still readable when printing, let's make this
```
durations[modeIdx] = time.Duration(totalTime.Load()) * time.Millisecond
```
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multiregion_leasing.go` line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-Nw5fvWq8RkpNkQJvUhY:-Nw77EKEDqe-wZtYPcYt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edfc031403f34252e9eef17c6587e3cff227d4ca/pkg/cmd/roachtest/tests/multiregion_leasing.go#L193)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and here, let's use `durations[modeIdx]` instead of `totalTime.Load()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-23 14:31 UTC, rafiss approved these changes
thanks for fixing up the test!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122655#-:-NwAMfi51p2RNn2ah9vT:bwvt29x)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)



<!-- Sent from Reviewable.io -->

2024-04-23 14:56 UTC, fqazi commented
@rafiss TFTR!

bors r+

2024-04-23 16:48 UTC, merged