workload/schemachange: add comma types in workload
cockroachdb/cockroach pull request #122935
Opened 2024-04-23 21:43 UTC by annrpom

This patch expands the schema change workload to add support for `ALTER TABLE` statements (`DROP COLUMN`/`ADD COLUMN`/`ALTER PRIMARY KEY`) that have been enabled with our "comma syntax".

Epic:
Fixes:

Release note: None

2024-04-23 21:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/122935)
<!-- Reviewable:end -->

2024-04-25 18:59 UTC, annrpom commented
Opening this up for comments

2024-05-15 22:14 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122935)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, and @herkolategan)

___
*[`pkg/workload/schemachange/operation_generator.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyGYss7hD2AUJ7IHKy:-NxyGYss7hD2AUJ7IHKz:b-emshfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L238)):*
> ```Go
> 			return nil, err
> 		}
> 	}
> ```

nit: this could be condensed a bit
```
tableName := og.specifiedTable
if tableName == nil {
	var err error
	tableName, err = og.randTable(ctx, tx, og.pctExisting(true), "")
	if err != nil {
		return nil, err
	}

}
```

___
*[`pkg/workload/schemachange/operation_generator.go` line 1667 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyGH4GEI5aJCusujQk:-NxyGH4GEI5aJCusujQl:b51l13j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L1667)):*
> ```Go
> 			return nil, err
> 		}
> 	}
> ```

nit: same as above
___
*[`pkg/workload/schemachange/operation_generator.go` line 2831 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyJR1w5nx3XE0tDx-k:-NxyJR1w5nx3XE0tDx-l:b-155x55) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L2831)):*
> ```Go
> 		}
> 
> 		stmt, err := commaOpFuncs[op](og, ctx, tx)
> ```

wouldn't we need to set `specifiedTable` before all of the calls to `commaOpFuncs`? (i.e., before this loop?)


<!-- Sent from Reviewable.io -->

2024-06-17 19:36 UTC, annrpom commented on pkg/workload/schemachange/optype.go
> +	createTable:                       500,
kindly ignore the value of this right now, but wdyt of cranking this sucker up to 10?

2024-06-17 19:45 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122935)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @herkolategan, and @rafiss)

___
*[`pkg/workload/schemachange/operation_generator.go` line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyGYss7hD2AUJ7IHKy:-O-bgybP-IaRn1PQmc1D:btugjcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L238)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this could be condensed a bit
```
tableName := og.specifiedTable
if tableName == nil {
	var err error
	tableName, err = og.randTable(ctx, tx, og.pctExisting(true), "")
	if err != nil {
		return nil, err
	}

}
```

</blockquote></details>

done -- ty!
___
*[`pkg/workload/schemachange/operation_generator.go` line 1667 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyGH4GEI5aJCusujQk:-O-bgzWa8YhlSyYzMsXs:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L1667)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: same as above
</blockquote></details>

done
___
*[`pkg/workload/schemachange/operation_generator.go` line 2831 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-NxyJR1w5nx3XE0tDx-k:-O-biXRh5uHtDMBiLAcM:b-1p50xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ced8c36a682767b29e0504f60d0da533440e2a38/pkg/workload/schemachange/operation_generator.go#L2831)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

wouldn't we need to set `specifiedTable` before all of the calls to `commaOpFuncs`? (i.e., before this loop?)
</blockquote></details>

the first time around, we shan't and just use the first query's table https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/operation_generator.go#L2803

although -- i am not quite sure if that is any better than just selecting an existing table. i can change it to just pick a table first


<!-- Sent from Reviewable.io -->

2024-06-17 19:56 UTC, annrpom commented on pkg/workload/schemachange/error_screening.go
> +var ErrSchemaChangesDisallowedDueToPkSwap = errors.New("no schema changes allowed on selected table due to PK swap")
ah this might be a problem in our mixed-verion tests

2024-06-20 19:38 UTC, rafiss requested changes
thanks for digging in more!

it does look like there are a few other fixes here that are not purely related to the comma syntax work. maybe it would be helpful to have the other fixes in a different commit. if doing that is a lot of extra work, a different approach that would help is to add reviewable comments in the different parts of the code and explain what issue is being fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-:-O-r8eTE0iZyjWaiE4mm:b-5pvt28)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @DarrylWong, and @herkolategan)

___
*[`pkg/sql/sem/builtins/builtins.go` line 7744 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r7aCODSvzEXp-nZSM:-O-r7aCODSvzEXp-nZSN:b-6pjbtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/sql/sem/builtins/builtins.go#L7744)):*
> ```Go
> 		},
> 		tree.Overload{
> 			Types:      tree.ParamTypes{{Name: "table_name", Typ: types.String}, {Name: "column_name", Typ: types.String}},
> ```

nit: this should take a table OID rather than a table name. the same table can exist in multiple schemas, so only including the table name as a parameter leaves the possibility for ambiguous results.

from reading this closer, it seems like this actually might support specifying a qualified table name (like `schema_name.table_name`). if that already does work, then maybe we can just rename the parameter to `qualified_table_name`.
___
*[`pkg/sql/sem/builtins/builtins.go` line 7747 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r7vJe3LFddF1s4J83:-O-r7vJf5TIL2De3uZHi:b-j3syya) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/sql/sem/builtins/builtins.go#L7747)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx context.Context, evalCtx *eval.Context, args tree.Datums) (tree.Datum, error) {
> 				tableName := tree.MustBeDString(args[0])
> ```

could this be implemented as a SQL query that looks at the descriptor, rather than needing to introduce a new function to the planner interface?
___
*[`pkg/workload/schemachange/error_screening.go` line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r3wolAJDlwbd86oVS:-O-r3womBSePXFSvxCMU:b-644pq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/error_screening.go#L64)):*
> ```Go
> 	ctx context.Context, tx pgx.Tx, columnName string,
> ) (string, error) {
> 	col, err := og.scanString(ctx, tx, `SELECT quote_ident($1)`, columnName)
> ```

nit: i don't think we should need to go through an extra SQL query to achieve this quotation. i think one of the following might work:
- use `lexbase.EncodeRestrictedSQLIdent` instead of this query
- at the time of fetching the column, change the existing query that does that to call `quote_ident`
___
*[`pkg/workload/schemachange/error_screening.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r7IlJ4oGMkXAHPYfV:-O-r7IlJ4oGMkXAHPYfW:baosi05) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/error_screening.go#L88)):*
> ```Go
> 	}
> 	active, err := og.scanBool(ctx, tx,
> 		`SELECT crdb_internal.is_column_active($1, $2)`, tableName.String(), columnName)
> ```

nit: can this just be part of the original query, rather than needing to run as a separate query?
___
*[`pkg/workload/schemachange/operation_generator.go` line 1127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r4wnp4rvzUxqHa3rQ:-O-r4wnp4rvzUxqHa3rR:b-1c4fhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/operation_generator.go#L1127)):*
> ```Go
> 	fmtCtx := tree.NewFmtCtx(tree.FmtBareIdentifiers)
> 	def.Format(fmtCtx)
> 	stmt.sql = fmtCtx.CloseAndGetString()
> ```

nit: `stmt.sql = tree.AsStringWithFlags(def, tree.FmtBareIdentifiers)` should be more concise
___
*[`pkg/workload/schemachange/operation_generator.go` line 1812 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r5X-n7L4xTCj_Bwpx:-O-r5X-n7L4xTCj_Bwpy:b-svau5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/operation_generator.go#L1812)):*
> ```Go
> 	fmtCtx := tree.NewFmtCtx(tree.FmtSerializable)
> 	fmtCtx.FormatName(constraintName)
> 	stmt.sql = fmt.Sprintf(`ALTER TABLE %s DROP CONSTRAINT %s`, tableName, fmtCtx.CloseAndGetString())
> ```

nit: using `tree.Serialize(tree.Name(constraintName))` might be a more convenient way
___
*[`pkg/workload/schemachange/operation_generator.go` line 2496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r69iC9K8ApgpVI3yR:-O-r69iC9K8ApgpVI3yS:b-rjgnnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/operation_generator.go#L2496)):*
> ```Go
> 				pgcode.UndefinedTable), nil
> 		}
> 		fmt.Println("table exists")
> ```

nit: extra print
___
*[`pkg/workload/schemachange/operation_generator.go` line 2534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r6Ift0mienrk9p6NA:-O-r6IfuAgYU4HHniT6K:bcivx02) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/operation_generator.go#L2534)):*
> ```Go
> 
> 	if og.specifiedTable != nil {
> 		fmt.Println("here", q)
> ```

nit: extra print statement
___
*[`pkg/workload/schemachange/optype.go` line 333 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#gh-1643346228:-O-r6nLH6tuaAUZawYVc:bl29b6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/optype.go#L333)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

kindly ignore the value of this right now, but wdyt of cranking this sucker up to 10?
</blockquote></details>

that seems reasonable!
___
*[`pkg/workload/schemachange/query_util.go` line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/122935#-O-r6yEe2RIyy3x9DG77:-O-r6yEe2RIyy3x9DG78:b-2j1xnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3bdc1cc5293ca0521545f294d91ad930f52e04b/pkg/workload/schemachange/query_util.go#L117)):*
> ```Go
> // schemas.
> func specificTableDescQuery(tableName string) string {
> 	return fmt.Sprintf(`SELECT * FROM descriptors WHERE descriptor ? 'table' AND name = '%s' AND NOT
> ```

can we pass in the schema name here to avoid the possibility of name collision?


<!-- Sent from Reviewable.io -->

2024-08-05 17:49 UTC, closed without merging

2024-08-05 17:49 UTC, annrpom commented
closing this in favor of a new PR; the comments/commits of this PR are outdated and largely addressed by https://github.com/cockroachdb/cockroach/pull/127271