sql: log session variable settings that are set in the connection string
cockroachdb/cockroach pull request #123015
Opened 2024-04-24 21:49 UTC by lyang24

This commit logs session variables passed on the connection url. The goal is to provide more information on trouble shooting issues. The output could be redacted for security purpose.

Fixes: #122934

Release note: None

2024-04-24 21:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/123015)
<!-- Reviewable:end -->

2024-05-15 19:57 UTC, rafiss requested changes
thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-:-Nxxp86u9I3VUIDkdkjN:b3akoa5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @lyang24)

___
*[`pkg/sql/exec_util.go` line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-NxxVXvA3sZg688Nk912:-NxxVXvA3sZg688Nk913:b-6r9i6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/686b5f9a2f101b0807251b50449e2cfb0a239b14/pkg/sql/exec_util.go#L2201)):*
> ```Go
> 	s.Printf("[")
> 	for k, v := range sd {
> 		s.Printf("%s:%s;", k, v)
> ```

i think `k` actually would be safe to print without redaction. it always refers to the name of a session variable, so it's not sensitive info.

also, i think it would be a bit more readable with `=` and some whitespace.

so  this could be:
```
s.Printf("[")
addSemiColon := false
for k, v := range sd {
  if addSemiColon {
    s.Print("; ")
  }
  s.Printf("%s=%s", redact.SafeString(k), v)
  addSemiColon = true
}
s.Printf("]")
```
___
*[`pkg/sql/pgwire/pre_serve_options.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-NxxgKGKA-zPCWlsHTgT:-NxxgKGKA-zPCWlsHTgU:b-7thhjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/686b5f9a2f101b0807251b50449e2cfb0a239b14/pkg/sql/pgwire/pre_serve_options.go#L244)):*
> ```Go
> 		}
> 	}
> 	log.Infof(ctx, "connection was made with session defaults: %s and custom session defaults: %s",
> ```

instead of logging this here, let's do it after the session is fully authenticated. a good place for this is the `processCommands` function in pkg/sql/pgwire/conn.go. right after `LogAuthOK` is called, we can also add:
```
	ac.LogAuthInfof(ctx,
		"session created with SessionDefaults=%s and CustomOptions=%s",
		c.sessionArgs.SessionDefaults,
		c.sessionArgs.CustomOptionSessionDefaults,
	)
```

(also, using `LogAuthInfo` makes the message go into the SESSIONS log channel, rather than the main log channel.


<!-- Sent from Reviewable.io -->

2024-05-17 23:35 UTC, lyang24 reviewed
Thanks for the feedback, I have addressed the comments please take another look when you have time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-:-Ny7uAlU-cKtchQlxPjl:bdh720f)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/exec_util.go` line 2201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-NxxVXvA3sZg688Nk912:-Ny7tgLG-e7AWgMXgG3C:b-2w9asw) ([raw file](https://github.com/cockroachdb/cockroach/blob/686b5f9a2f101b0807251b50449e2cfb0a239b14/pkg/sql/exec_util.go#L2201)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think `k` actually would be safe to print without redaction. it always refers to the name of a session variable, so it's not sensitive info.

also, i think it would be a bit more readable with `=` and some whitespace.

so  this could be:
```
s.Printf("[")
addSemiColon := false
for k, v := range sd {
  if addSemiColon {
    s.Print("; ")
  }
  s.Printf("%s=%s", redact.SafeString(k), v)
  addSemiColon = true
}
s.Printf("]")
```
</blockquote></details>

Thanks great suggestion, i added SafeString to avoid the semicolon being wrapped in to redact mode. should we take an extra step to make the kv sorted by key in the output?
```
redact.SafeString("; ")
```
___
*[`pkg/sql/pgwire/pre_serve_options.go` line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123015#-NxxgKGKA-zPCWlsHTgT:-Ny7u56WC5UY_VeFc7G3:b8412ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/686b5f9a2f101b0807251b50449e2cfb0a239b14/pkg/sql/pgwire/pre_serve_options.go#L244)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of logging this here, let's do it after the session is fully authenticated. a good place for this is the `processCommands` function in pkg/sql/pgwire/conn.go. right after `LogAuthOK` is called, we can also add:
```
	ac.LogAuthInfof(ctx,
		"session created with SessionDefaults=%s and CustomOptions=%s",
		c.sessionArgs.SessionDefaults,
		c.sessionArgs.CustomOptionSessionDefaults,
	)
```

(also, using `LogAuthInfo` makes the message go into the SESSIONS log channel, rather than the main log channel.
</blockquote></details>

thanks for the knowledge, this is done.


<!-- Sent from Reviewable.io -->

2024-05-20 21:13 UTC, rafiss approved these changes
thanks for your contribution! i've rebased the PR and updated affected logging tests.

i added the logic to print the keys in alphabetical order so that tests are stable.


bors r+

2024-05-20 21:49 UTC, merged