sql: grant/revoke on a large number of objects can create a lot of jobs
cockroachdb/cockroach pull request #123414
Opened 2024-05-01 21:27 UTC by Dedej-Bergin

Previously we would create multiple jobs for granting on multiple tables and types within one transaction.  This caused a performance slowdown, these code changes skip the making of multiple jobs and just execute the grants in a batch.

Fixes:#117643
Release note(performance improvement): multiple grants on tables and types within one transaction now run faster.

2024-05-01 21:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/123414)
<!-- Reviewable:end -->

2024-05-02 20:33 UTC, fqazi requested changes
This looks good, just a few suggestions

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-:-Nwv-eoF5uowNVhoxIuS:b-t2njw2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
*large number of (scale makes a difference)
___
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-NwuyiDr6tuh40Jcd1Bg:b-3h5lus) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
> ```Go
> 		// wait for channel before starting the sleep
> 		<-messages
> 		time.Sleep(2 * time.Second)
> ```

This will work okayish. We could also confirm this by having the lease manager block this committing as an extra source of truth.


i.e. We would set the cluster setting: `sql.catalog.descriptor_lease_duration` to a low value like 15-30 seconds. Then have this transaction run queries like "SELECT 1" until it hits an error. What will happen is that once the lease duration has passed any other transactions is not allowed to use the old versions of the PROMO_CODES descriptor.
___
*[`pkg/sql/schema_changer_test.go` line 7862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-Nwuy7sH0CNIHEgRkUtS:-Nwuy7sH0CNIHEgRkUtT:b-jeflq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7862)):*
> ```Go
> 
> 	// post to channel to start sleep timer in go routine
> 	messages <- struct{}{}
> ```

Another option is to just do

close(messages)


<!-- Sent from Reviewable.io -->

2024-05-02 21:30 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

*large number of (scale makes a difference)
</blockquote></details>

since this change is a performance improvement, we should include a microbenchmark that shows that improvement. (or if this improves an existing one, then show the results.)

to see an example of a microbenchmark so you can write a similar one, take a look at: https://github.com/cockroachdb/cockroach/blob/6036490534b7576d6d01fdf6ecd5275bf520261a/pkg/sql/stats/automatic_stats_test.go#L274

then you can compare the old and new performance by using:
```
N=10 BENCHTIMEOUT=24h PKG=./pkg/sql/ BENCHES=BenchmarkYourNameHere ./scripts/bench 'old-commit' 'new-commit'
```

(if you're adding a new benchmark, it's helpful to put it in its own commit before your other code changes, so you can use the above script.)
___
*[`pkg/sql/grant_revoke.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvB7dI2ky0lEeJk707:-NwvB7dI2ky0lEeJk708:bnqhqii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L429)):*
> ```Go
> 			}
> 		case *schemadesc.Mutable:
> 			if err := p.writeSchemaDescChange(
> ```

nit: should this also be updated to use the batch?
___
*[`pkg/sql/grant_revoke.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvBANA8bpXgY8L1gbM:-NwvBANA8bpXgY8L1gbN:bnqhqii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L448)):*
> ```Go
> 			}
> 		case *funcdesc.Mutable:
> 			if err := p.writeFuncSchemaChange(ctx, d); err != nil {
> ```

nit: should this also be updated to use the batch?
___
*[`pkg/sql/schema_changer_test.go` line 7825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAgDvErsyy-lngEuD:-NwvAgDvErsyy-lngEuE:bwo263y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7825)):*
> ```Go
> }
> 
> func TestGrantAndSelectsWithinTransaction(t *testing.T) {
> ```

nit: could you add a comment to the test that explains what it is testing?
___
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-NwvAo9LCfTu9VyVOVHf:bdds3kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This will work okayish. We could also confirm this by having the lease manager block this committing as an extra source of truth.


i.e. We would set the cluster setting: `sql.catalog.descriptor_lease_duration` to a low value like 15-30 seconds. Then have this transaction run queries like "SELECT 1" until it hits an error. What will happen is that once the lease duration has passed any other transactions is not allowed to use the old versions of the PROMO_CODES descriptor.
</blockquote></details>

why is a 2 second sleep necessary?
___
*[`pkg/sql/schema_changer_test.go` line 7869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAw_oClSF31Q87LWD:-NwvAw_oClSF31Q87LWE:b-58a13e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7869)):*
> ```Go
> 
> 	err = group.Wait()
> 	require.True(t, duration > 1500 * time.Millisecond)
> ```

why do we want this 1500ms assertion? (this could use a comment)


<!-- Sent from Reviewable.io -->

2024-05-03 19:29 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since this change is a performance improvement, we should include a microbenchmark that shows that improvement. (or if this improves an existing one, then show the results.)

to see an example of a microbenchmark so you can write a similar one, take a look at: https://github.com/cockroachdb/cockroach/blob/6036490534b7576d6d01fdf6ecd5275bf520261a/pkg/sql/stats/automatic_stats_test.go#L274

then you can compare the old and new performance by using:
```
N=10 BENCHTIMEOUT=24h PKG=./pkg/sql/ BENCHES=BenchmarkYourNameHere ./scripts/bench 'old-commit' 'new-commit'
```

(if you're adding a new benchmark, it's helpful to put it in its own commit before your other code changes, so you can use the above script.)
</blockquote></details>

Thanks, I changed multiple grants to a Multiple/large amounts of grants.
___
*[`pkg/sql/grant_revoke.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvB7dI2ky0lEeJk707:-Nwyyjte6gjTnHEVrQ4a:b-agr2a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L429)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should this also be updated to use the batch?
</blockquote></details>

I think the problem was mainly happening on tables and types, so it was decided not to update schema since the issue is not common there, but if you think that it would be good to use batch for schema grants than I could add that change in.

Let me know if you still think we should use batch for schema grants?
___
*[`pkg/sql/grant_revoke.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvBANA8bpXgY8L1gbM:-NwyzRwz0EDkIeZ6-1eH:b-ahlp3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L448)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should this also be updated to use the batch?
</blockquote></details>

I think the problem was mainly happening on tables and types, so it was decided not to update functions since the issue is not common there, but if you think that it would be good to use batch for function grants than I could add that change in.

Let me know if you still think we should use batch for function grants?
___
*[`pkg/sql/schema_changer_test.go` line 7825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAgDvErsyy-lngEuD:-Nwzu1LQ2QnHEmftovz6:b-o2si7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7825)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you add a comment to the test that explains what it is testing?
</blockquote></details>

Definitely, just added it thanks Rafi!
___
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-Nwzu5oQ0nx_CR2do61o:b-xd4en2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is a 2 second sleep necessary?
</blockquote></details>

The sleep is in there because with a sleep on the transaction1 commit we end up holding transaction2, which is a functionality that we want to test/protect from someone breaking this commit/wait process in the future.  For the duration of the sleep being 2 seconds, I could lower it if that would be better.  I went ahead and added a comment for this sleep.

Also at the moment I'm looking into modifying the test to use `sql.catalog.descriptor_lease_duration`
___
*[`pkg/sql/schema_changer_test.go` line 7862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-Nwuy7sH0CNIHEgRkUtS:-Nwz6sDS0vBLS_qdbJhv:b-w0kug) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7862)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Another option is to just do

close(messages)
</blockquote></details>

Sounds good I went ahead and made this change
___
*[`pkg/sql/schema_changer_test.go` line 7869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAw_oClSF31Q87LWD:-NwzunpRAx-sLeVFyrVH:b-vyo5mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7869)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do we want this 1500ms assertion? (this could use a comment)
</blockquote></details>

Thanks Rafi, I went ahead and added a comment for this.  Here we are verifying that transaction2 did hold, it should hold for up to 2 seconds, so we check that the duration is at least 1.5 seconds (1500ms). If you want I could reduce the wait time here.


<!-- Sent from Reviewable.io -->

2024-05-03 21:22 UTC, Dedej-Bergin commented
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thanks, I changed multiple grants to a Multiple/large amounts of grants.
</blockquote></details>

Thanks Rafi! I just now modified the benchmark_expectations file with the new improved benchmarks, I will look into BenchmarkEnsureAllTables as well


<!-- Sent from Reviewable.io -->

2024-05-03 21:54 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-Nx-P36f6R6e2bGmPB8q:b-60oe35) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

The sleep is in there because with a sleep on the transaction1 commit we end up holding transaction2, which is a functionality that we want to test/protect from someone breaking this commit/wait process in the future.  For the duration of the sleep being 2 seconds, I could lower it if that would be better.  I went ahead and added a comment for this sleep.

Also at the moment I'm looking into modifying the test to use `sql.catalog.descriptor_lease_duration`
</blockquote></details>

replied to this in the comment below
___
*[`pkg/sql/schema_changer_test.go` line 7869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAw_oClSF31Q87LWD:-Nx-P1Nl8_Yox4eiGkNb:bkepdg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7869)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thanks Rafi, I went ahead and added a comment for this.  Here we are verifying that transaction2 did hold, it should hold for up to 2 seconds, so we check that the duration is at least 1.5 seconds (1500ms). If you want I could reduce the wait time here.
</blockquote></details>

ah ok that's what i was wondering! if the `sleep` was just there to check that one txn finished before the other, it would actually be better to just create a boolean variable, like `txn1Committed` or use a channel. we'd have to think a bit about how to make sure it's set atomically in order to make the test not be flaky. we can talk through ideas next week.

the main reason is that it's always best to avoid adding sleeps in tests. relying on sleeps makes tests flaky usually.


<!-- Sent from Reviewable.io -->

2024-05-07 14:10 UTC, Dedej-Bergin commented
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thanks Rafi! I just now modified the benchmark_expectations file with the new improved benchmarks, I will look into BenchmarkEnsureAllTables as well
</blockquote></details>

I just added to microbenchmark tests for grants on types and grants on tables, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-05-07 14:13 UTC, Dedej-Bergin commented
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-NxIOFwm5FjhxHbpomJR:b9upc9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

replied to this in the comment below
</blockquote></details>

We got rid of the sleeps and channel, and are now using 2 go routines and a concurrent safe boolean to get this test to provide the same coverage with a runtime in milliseconds. Thanks for your help!


<!-- Sent from Reviewable.io -->

2024-05-07 14:14 UTC, Dedej-Bergin commented
*[`pkg/sql/schema_changer_test.go` line 7869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAw_oClSF31Q87LWD:-NxIOufA7GXgdTu5yedH:b9upc9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7869)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah ok that's what i was wondering! if the `sleep` was just there to check that one txn finished before the other, it would actually be better to just create a boolean variable, like `txn1Committed` or use a channel. we'd have to think a bit about how to make sure it's set atomically in order to make the test not be flaky. we can talk through ideas next week.

the main reason is that it's always best to avoid adding sleeps in tests. relying on sleeps makes tests flaky usually.
</blockquote></details>

We got rid of the sleeps and channel, and are now using 2 go routines and a concurrent safe boolean to get this test to provide the same coverage with a runtime in milliseconds. Thanks for your help!


<!-- Sent from Reviewable.io -->

2024-05-07 15:16 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

I just added to microbenchmark tests for grants on types and grants on tables, thanks Rafi!
</blockquote></details>

The benchmarks show that it's running a lot faster now! Grants on 1000 tables is 2,500% faster!

**

Benchmark Results with new Changes:



BenchmarkGrantTables/numTables=10

BenchmarkGrantTables/numTables=10-10               48   25188102 ns/op

BenchmarkGrantTables/numTables=100

BenchmarkGrantTables/numTables=100-10              6 195067576 ns/op

BenchmarkGrantTables/numTables=1000

BenchmarkGrantTables/numTables=1000-10             1 1828938834 ns/op

  

BenchmarkGrantTypes/numTypes=10

BenchmarkGrantTypes/numTypes=10-10               32   36117533 ns/op

BenchmarkGrantTypes/numTypes=100

BenchmarkGrantTypes/numTypes=100-10              4 328903364 ns/op

BenchmarkGrantTypes/numTypes=1000

BenchmarkGrantTypes/numTypes=1000-10             1 3449303583 ns/op

  
  

Benchmark Results without new Changes:

  

BenchmarkGrantTables/numTables=10

BenchmarkGrantTables/numTables=10-10               9 111688116 ns/op

BenchmarkGrantTables/numTables=100

BenchmarkGrantTables/numTables=100-10              2 720130208 ns/op

BenchmarkGrantTables/numTables=1000

BenchmarkGrantTables/numTables=1000-10             1 51262939792 ns/op

  

BenchmarkGrantTypes/numTypes=10

BenchmarkGrantTypes/numTypes=10-10               8 129941745 ns/op

BenchmarkGrantTypes/numTypes=100

BenchmarkGrantTypes/numTypes=100-10              1 1030206208 ns/op

BenchmarkGrantTypes/numTypes=1000

BenchmarkGrantTypes/numTypes=1000-10             1 10553151833 ns/op

**


<!-- Sent from Reviewable.io -->

2024-05-07 16:08 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @fqazi, and @rafiss)

___
*[`pkg/sql/stats/automatic_stats_test.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxIn_a35BpEPlHRv_BQ:-NxIn_a35BpEPlHRv_BR:b-3lwe03) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd49d7108362f7ac363da2dae81712e4913275a/pkg/sql/stats/automatic_stats_test.go#L312)):*
> ```Go
> }
> 
> func BenchmarkGrantTables(b *testing.B) {
> ```

nit: is there a reason these new benchmarks are added to `stats` package? They seem orthogonal to the table stats feature.


<!-- Sent from Reviewable.io -->

2024-05-07 16:14 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @yuzefovich)

___
*[`pkg/sql/stats/automatic_stats_test.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxIn_a35BpEPlHRv_BQ:-NxIogz54EeHU-oTyoS7:b-irz14v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd49d7108362f7ac363da2dae81712e4913275a/pkg/sql/stats/automatic_stats_test.go#L312)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: is there a reason these new benchmarks are added to `stats` package? They seem orthogonal to the table stats feature.
</blockquote></details>

a better place for the test would be pkg/sql/grant_revoke_test.go


<!-- Sent from Reviewable.io -->

2024-05-07 16:44 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @fqazi, and @yuzefovich)

___
*[`pkg/sql/grant_revoke.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvB7dI2ky0lEeJk707:-NxIw8ch4yO1993EkuBt:bfom9vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L429)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

I think the problem was mainly happening on tables and types, so it was decided not to update schema since the issue is not common there, but if you think that it would be good to use batch for schema grants than I could add that change in.

Let me know if you still think we should use batch for schema grants?
</blockquote></details>

i do think it would be nice to keep all the different code paths consistent. unless there's a reason we can't use the batch here (like it would break an existing test), i think we should use it in all the branches.
___
*[`pkg/sql/grant_revoke.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvBANA8bpXgY8L1gbM:-NxIwMpsCnCCbwHzFEWP:b-6xoaza) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L448)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

I think the problem was mainly happening on tables and types, so it was decided not to update functions since the issue is not common there, but if you think that it would be good to use batch for function grants than I could add that change in.

Let me know if you still think we should use batch for function grants?
</blockquote></details>

see above comment


<!-- Sent from Reviewable.io -->

2024-05-07 17:23 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @fqazi, and @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

The benchmarks show that it's running a lot faster now! Grants on 1000 tables is 2,500% faster!

**

Benchmark Results with new Changes:



BenchmarkGrantTables/numTables=10

BenchmarkGrantTables/numTables=10-10               48   25188102 ns/op

BenchmarkGrantTables/numTables=100

BenchmarkGrantTables/numTables=100-10              6 195067576 ns/op

BenchmarkGrantTables/numTables=1000

BenchmarkGrantTables/numTables=1000-10             1 1828938834 ns/op

  

BenchmarkGrantTypes/numTypes=10

BenchmarkGrantTypes/numTypes=10-10               32   36117533 ns/op

BenchmarkGrantTypes/numTypes=100

BenchmarkGrantTypes/numTypes=100-10              4 328903364 ns/op

BenchmarkGrantTypes/numTypes=1000

BenchmarkGrantTypes/numTypes=1000-10             1 3449303583 ns/op

  
  

Benchmark Results without new Changes:

  

BenchmarkGrantTables/numTables=10

BenchmarkGrantTables/numTables=10-10               9 111688116 ns/op

BenchmarkGrantTables/numTables=100

BenchmarkGrantTables/numTables=100-10              2 720130208 ns/op

BenchmarkGrantTables/numTables=1000

BenchmarkGrantTables/numTables=1000-10             1 51262939792 ns/op

  

BenchmarkGrantTypes/numTypes=10

BenchmarkGrantTypes/numTypes=10-10               8 129941745 ns/op

BenchmarkGrantTypes/numTypes=100

BenchmarkGrantTypes/numTypes=100-10              1 1030206208 ns/op

BenchmarkGrantTypes/numTypes=1000

BenchmarkGrantTypes/numTypes=1000-10             1 10553151833 ns/op

**
</blockquote></details>

copying again for better readability. great improvement!
```
goos: darwin
goarch: arm64
                           │ old-bench.txt │            new-bench.txt            │
                           │    sec/op     │   sec/op     vs base                │
GrantTables/numTables=10      256.22m ± 2%   31.91m ± 3%  -87.55% (p=0.000 n=10)
GrantTables/numTables=100     2363.0m ± 2%   223.0m ± 2%  -90.56% (p=0.000 n=10)
GrantTables/numTables=1000     25.135 ± 1%    2.134 ± 2%  -91.51% (p=0.000 n=10)
geomean                         2.478        247.6m       -90.01%

                           │ old-bench.txt │             new-bench.txt             │
                           │     B/op      │     B/op       vs base                │
GrantTables/numTables=10      84.73Mi ± 1%    12.28Mi ± 1%  -85.51% (p=0.000 n=10)
GrantTables/numTables=100    815.82Mi ± 0%    97.48Mi ± 0%  -88.05% (p=0.000 n=10)
GrantTables/numTables=1000   8443.1Mi ± 2%   1010.8Mi ± 1%  -88.03% (p=0.000 n=10)
geomean                       835.7Mi         106.6Mi       -87.25%

                           │ old-bench.txt │            new-bench.txt            │
                           │   allocs/op   │  allocs/op   vs base                │
GrantTables/numTables=10      573.79k ± 0%   77.43k ± 0%  -86.51% (p=0.000 n=10)
GrantTables/numTables=100     5493.2k ± 0%   604.3k ± 0%  -89.00% (p=0.000 n=10)
GrantTables/numTables=1000    56.518M ± 1%   5.885M ± 2%  -89.59% (p=0.000 n=10)
geomean                        5.627M        650.6k       -88.44%
```


<!-- Sent from Reviewable.io -->

2024-05-07 19:53 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuyiDr6tuh40Jcd1Bf:-NxJb6nlEkqJWqGfQyKO:b-jn1lvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7850)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

We got rid of the sleeps and channel, and are now using 2 go routines and a concurrent safe boolean to get this test to provide the same coverage with a runtime in milliseconds. Thanks for your help!
</blockquote></details>

The concurrent safe boolean with 2 go routines would have not held if the commit on txn2 did not hold at all and committed right away, so changes where made to use a 15 second lease duration which now makes the test take almost 1 minute to run.
___
*[`pkg/sql/schema_changer_test.go` line 7869 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvAw_oClSF31Q87LWD:-NxJbaZ35-LzNxzndtzm:b-jn1lvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/schema_changer_test.go#L7869)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

We got rid of the sleeps and channel, and are now using 2 go routines and a concurrent safe boolean to get this test to provide the same coverage with a runtime in milliseconds. Thanks for your help!
</blockquote></details>

The concurrent safe boolean with 2 go routines would have not held if the commit on txn2 did not hold at all and committed right away, so changes where made to use a 15 second lease duration which now makes the test take almost 1 minute to run.


<!-- Sent from Reviewable.io -->

2024-05-07 21:15 UTC, fqazi reviewed
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @rafiss, and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7825 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxJtgeJ9x_qJ1wlqZGS:-NxJtgeJ9x_qJ1wlqZGT:b-lns347) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3dc685ad5c9b32dac9314547a405e42c71ad0dc/pkg/sql/schema_changer_test.go#L7825)):*
> ```Go
> }
> 
> // TestGrantAndSelectsWithinTransaction tests two concurrent
> ```

So, the intent of this test is to confirm that once the grant published a new version of the descriptor, it will wait for the new version to be completely adopted. i.e. Ensure that any other transactions using the old version either commit or their leases expire.
___
*[`pkg/sql/schema_changer_test.go` line 7871 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxJtV2_1JF3EReSPySC:-NxJtV2_1JF3EReSPySD:b-9fhvee) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3dc685ad5c9b32dac9314547a405e42c71ad0dc/pkg/sql/schema_changer_test.go#L7871)):*
> ```Go
> 	group.GoCtx(func(ctx context.Context) error {
> 		<-messages
> 		err := txn1.Commit()
> ```

I think we expect txn1 to hit an error on the commit because of the deadline


<!-- Sent from Reviewable.io -->

2024-05-08 21:53 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwuxK2o5-sGTpJUuoZk):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

copying again for better readability. great improvement!
```
goos: darwin
goarch: arm64
                           │ old-bench.txt │            new-bench.txt            │
                           │    sec/op     │   sec/op     vs base                │
GrantTables/numTables=10      256.22m ± 2%   31.91m ± 3%  -87.55% (p=0.000 n=10)
GrantTables/numTables=100     2363.0m ± 2%   223.0m ± 2%  -90.56% (p=0.000 n=10)
GrantTables/numTables=1000     25.135 ± 1%    2.134 ± 2%  -91.51% (p=0.000 n=10)
geomean                         2.478        247.6m       -90.01%

                           │ old-bench.txt │             new-bench.txt             │
                           │     B/op      │     B/op       vs base                │
GrantTables/numTables=10      84.73Mi ± 1%    12.28Mi ± 1%  -85.51% (p=0.000 n=10)
GrantTables/numTables=100    815.82Mi ± 0%    97.48Mi ± 0%  -88.05% (p=0.000 n=10)
GrantTables/numTables=1000   8443.1Mi ± 2%   1010.8Mi ± 1%  -88.03% (p=0.000 n=10)
geomean                       835.7Mi         106.6Mi       -87.25%

                           │ old-bench.txt │            new-bench.txt            │
                           │   allocs/op   │  allocs/op   vs base                │
GrantTables/numTables=10      573.79k ± 0%   77.43k ± 0%  -86.51% (p=0.000 n=10)
GrantTables/numTables=100     5493.2k ± 0%   604.3k ± 0%  -89.00% (p=0.000 n=10)
GrantTables/numTables=1000    56.518M ± 1%   5.885M ± 2%  -89.59% (p=0.000 n=10)
geomean                        5.627M        650.6k       -88.44%
```
</blockquote></details>

Thanks Rafi!
___
*[`pkg/sql/grant_revoke.go` line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvB7dI2ky0lEeJk707:-NxPAk8iAamzMZdikdoo:b-bhw77d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L429)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i do think it would be nice to keep all the different code paths consistent. unless there's a reason we can't use the batch here (like it would break an existing test), i think we should use it in all the branches.
</blockquote></details>

I just made the changes for this, it's definitely better this way, thanks Rafi!
___
*[`pkg/sql/grant_revoke.go` line 448 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NwvBANA8bpXgY8L1gbM:-NxPAsHn0ST3lsj1TBJ6:b-bhw77d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d3571cf4cab3addda306b111ddda4e3c274c5e2/pkg/sql/grant_revoke.go#L448)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

see above comment
</blockquote></details>

I just made the changes for this, it's definitely better this way, thanks Rafi!
___
*[`pkg/sql/schema_changer_test.go` line 7825 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxJtgeJ9x_qJ1wlqZGS:-NxPB4Jv5DF2eMRXk_yN:bhsk771) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3dc685ad5c9b32dac9314547a405e42c71ad0dc/pkg/sql/schema_changer_test.go#L7825)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

So, the intent of this test is to confirm that once the grant published a new version of the descriptor, it will wait for the new version to be completely adopted. i.e. Ensure that any other transactions using the old version either commit or their leases expire.
</blockquote></details>

Sounds good, I changed the name for this test to TestLeaseTimeoutWithConcurrentTransactions, removed the code that checks that grants on tables no longer creates a job(s) and I added a separate test in grant_table to do the test that no jobs are being created.
___
*[`pkg/sql/schema_changer_test.go` line 7871 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxJtV2_1JF3EReSPySC:-NxK43Mq1bxankDpzgDF:b-dr4wp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3dc685ad5c9b32dac9314547a405e42c71ad0dc/pkg/sql/schema_changer_test.go#L7871)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think we expect txn1 to hit an error on the commit because of the deadline
</blockquote></details>

sounds good, I added a comment for this, thanks Faizan!
___
*[`pkg/sql/stats/automatic_stats_test.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxIn_a35BpEPlHRv_BQ:-NxK4C0j6Xx1elx6LwgE:b-76eipk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd49d7108362f7ac363da2dae81712e4913275a/pkg/sql/stats/automatic_stats_test.go#L312)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

a better place for the test would be pkg/sql/grant_revoke_test.go
</blockquote></details>

sounds good I went ahead and moved it to grant_revoke_test.go, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-05-08 22:56 UTC, rafiss reviewed
this looks good! my comments are all minor, and non-blocking (and also had some questions for the future). the main thing to add is just to add a skip under heavyweight test configurations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-:-NxPPnCu3TWuTxV6S1Z3:b-6bylsd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @fqazi, and @yuzefovich)

___
*[`pkg/sql/grant_revoke.go` line 395 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPLeDXDzvguUOhXlDF:-NxPLeDXDzvguUOhXlDG:b-5jxooj) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/grant_revoke.go#L395)):*
> ```Go
> 			}
> 		case *tabledesc.Mutable:
> 			if !d.Dropped() {
> ```

this is unrelated to your PR, but as a separate followup, i wonder if we should have this `!d.Dropped()` check for the other cases also. seems like it could prevent some unneeded work. wdyt @fqazi ?
___
*[`pkg/sql/schema_changer_test.go` line 7832 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMiD77Jh-UBJpNbYC:-NxPMiD77Jh-UBJpNbYD:bn2ryzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7832)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 	ctx := context.Background()
> ```

since it looks like we do need this test to be timing related, i think it would be better to skip this under expensive configurations. there's a helper function called `skip.UnderDuress(t, "reason")`, which will skip the test if the race or deadlock detector is on, or if it's being run under stress. those are all situations in which we want to avoid slow tests. can you use that helper function, note the reason for the skip when it's called?
___
*[`pkg/sql/schema_changer_test.go` line 7834 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMFO56MH021uitdBf:-NxPMFO56MH021uitdBg:b-xoit9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7834)):*
> ```Go
> 
> 	settings := cluster.MakeTestingClusterSettings()
> 	lease.LeaseDuration.Override(ctx, &settings.SV, 15*time.Second)
> ```

this is more of a question for @fqazi -- i thought this lease duration no longer was relevant with session based leasing?

also, is this going to be reliable? i thought the actual duration would get jittered?
___
*[`pkg/sql/schema_changer_test.go` line 7871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPPeGW0IeHizvHK9cT:-NxPPeGW0IeHizvHK9cU:b-vs42dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7871)):*
> ```Go
> 	// txn1.commit() completes with an error due to lease timeout on txn2.commit().
> 	err = txn1.Commit()
> 	require.Error(t, err)
> ```

we could add something here to make sure it's the correct error, like this:
```
	require.ErrorContains(t, err, "RETRY_COMMIT_DEADLINE_EXCEEDED")
```


<!-- Sent from Reviewable.io -->

2024-05-09 14:03 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @rafiss, and @yuzefovich)

___
*[`pkg/sql/grant_revoke.go` line 395 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPLeDXDzvguUOhXlDF:-NxSeWz86ll2_S4MV7H2:b-sveorb) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/grant_revoke.go#L395)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is unrelated to your PR, but as a separate followup, i wonder if we should have this `!d.Dropped()` check for the other cases also. seems like it could prevent some unneeded work. wdyt @fqazi ?
</blockquote></details>

Yeah, probably better to have the dropped check in other cases too.


<!-- Sent from Reviewable.io -->

2024-05-09 14:52 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7832 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMiD77Jh-UBJpNbYC:-NxSojnL4U_CQBHiSVae:b1hftnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7832)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since it looks like we do need this test to be timing related, i think it would be better to skip this under expensive configurations. there's a helper function called `skip.UnderDuress(t, "reason")`, which will skip the test if the race or deadlock detector is on, or if it's being run under stress. those are all situations in which we want to avoid slow tests. can you use that helper function, note the reason for the skip when it's called?
</blockquote></details>

Just added it, thanks Rafi!
___
*[`pkg/sql/schema_changer_test.go` line 7871 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPPeGW0IeHizvHK9cT:-NxSoClNCaYGdyNKhJIj:b-5gchd) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7871)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we could add something here to make sure it's the correct error, like this:
```
	require.ErrorContains(t, err, "RETRY_COMMIT_DEADLINE_EXCEEDED")
```
</blockquote></details>

I see, this is very nice, just added it, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-05-09 16:05 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7834 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMFO56MH021uitdBf:-NxT4ueB3id_27DUNiko:bhgbynx) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7834)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is more of a question for @fqazi -- i thought this lease duration no longer was relevant with session based leasing?

also, is this going to be reliable? i thought the actual duration would get jittered?
</blockquote></details>

Yeah the duration still applies on session based in terms of when old versions get evicted (i.e. transaction using the old version are retried due to the deadline). Even with jitter the intent was to speed up the test and confirm we wait for any dependent txn to be kicked.


<!-- Sent from Reviewable.io -->

2024-05-09 16:56 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7834 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMFO56MH021uitdBf:-NxTGq1y09Dp_AWdUYhZ:b7lf4gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7834)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah the duration still applies on session based in terms of when old versions get evicted (i.e. transaction using the old version are retried due to the deadline). Even with jitter the intent was to speed up the test and confirm we wait for any dependent txn to be kicked.
</blockquote></details>

i see thanks

so if the setting is set to 15s, and there is jitter, does that mean the test could be flaky since it only checks: `require.Greaterf(t, duration, 15*time.Second)`


<!-- Sent from Reviewable.io -->

2024-05-09 17:00 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @rafiss, and @yuzefovich)

___
*[`pkg/sql/schema_changer_test.go` line 7834 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMFO56MH021uitdBf:-NxTHZQ54o2Kkr0dRHeI:b-ju06f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7834)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see thanks

so if the setting is set to 15s, and there is jitter, does that mean the test could be flaky since it only checks: `require.Greaterf(t, duration, 15*time.Second)`
</blockquote></details>

Yeah, it could be flaky. Lets just drop the timing angle all together, since the deadline error confirms that the deadline came into play. @Dedej-Bergin 


<!-- Sent from Reviewable.io -->

2024-05-09 21:02 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @yuzefovich)

___
*[`pkg/sql/grant_revoke.go` line 395 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPLeDXDzvguUOhXlDF:-NxU8c8R5kP3-DGG76Xs:b-3jnfir) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/grant_revoke.go#L395)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, probably better to have the dropped check in other cases too.
</blockquote></details>

Sounds good, just added it, thanks!
___
*[`pkg/sql/schema_changer_test.go` line 7834 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxPMFO56MH021uitdBf:-NxU4tZd9LJKcNY080GC:b5a0krr) ([raw file](https://github.com/cockroachdb/cockroach/blob/52a55e722c72c9535a84bec5966c201e68c7f16d/pkg/sql/schema_changer_test.go#L7834)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, it could be flaky. Lets just drop the timing angle all together, since the deadline error confirms that the deadline came into play. @Dedej-Bergin
</blockquote></details>

Sounds good, just removed the timing related code, thanks!


<!-- Sent from Reviewable.io -->

2024-05-09 21:11 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @yuzefovich)

___
*[`pkg/sql/stats/automatic_stats_test.go` line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-NxIn_a35BpEPlHRv_BQ:-NxUAT1P18AmjHY1eDRL:b949m7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd49d7108362f7ac363da2dae81712e4913275a/pkg/sql/stats/automatic_stats_test.go#L312)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

sounds good I went ahead and moved it to grant_revoke_test.go, thanks Rafi!
</blockquote></details>

lgtm! great work on taking care of all the followups and making a big perf improvement


<!-- Sent from Reviewable.io -->

2024-05-09 23:21 UTC, fqazi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r7, 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123414#-:-NxUeIRn7HpJ2RxuBf08:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)



<!-- Sent from Reviewable.io -->

2024-05-10 00:45 UTC, rafiss commented
there's a linting failure:
```
=== NAME  TestLint/TestMissingLeakTest
    gen-lint_test.go:430: 
        sql/schema_changer_test.go: TestLeaseTimeoutWithConcurrentTransactions: missing defer leaktest.AfterTest
```

to resolve it, move the `skip` so it's after the defers
```
	skip.UnderDuress(t, "slow test")
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)
```

2024-05-13 15:01 UTC, Dedej-Bergin commented
bors r+

2024-05-13 15:58 UTC, Dedej-Bergin commented
bors r+

2024-05-13 16:29 UTC, merged

2024-05-14 07:27 UTC, renatolabs commented
There was another lint failure introduced in this PR that only shows up in `Bazel Extended CI` (see [internal discussion](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1715294884134249)).