cli: debugzip sensitive fields redaction guarded through cluster settings
cockroachdb/cockroach pull request #123544
Opened 2024-05-03 09:32 UTC by kousiknath

Even though redaction is enabled while taking debug zip, some customers would be fine sharing sensitive information like host name, ip addresses. This PR introduces a cluster setting which can be switched on or off to control whether such sensitive fields should be redacted. If off, sensitive fields won't get redacted. If on, those fields will get redacted.
   
Epic: https://cockroachlabs.atlassian.net/issues/CRDB-38270
Release note: None

2024-05-03 09:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/123544)
<!-- Reviewable:end -->

2024-05-03 21:47 UTC, dhartunian requested changes
> Reviewed 11 of 11 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kousiknath)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-On0lEQb3LINB6RDm):*
Add new cluster setting to release note as `(ops change)`.
___
*[`pkg/cli/settings.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-Oqa7AqMMp3s-mRW7:-Nx-Oqa7AqMMp3s-mRW8:b-z6llk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/settings.go#L1)):*
> ```Go
> package cli
> ```

add license
___
*[`pkg/cli/settings.go` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-OxpQ-2xtF8ffqL2h:-Nx-OxpQ-2xtF8ffqL2i:bw5jycv) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/settings.go#L15)):*
> ```Go
> 	settings.ApplicationLevel,
> 	DebugZipSensitiveFieldsRedactionEnabledSettingName,
> 	"enables or disabled hostname / ip address redaction in debug zip",
> ```

nit: "disables"
___
*[`pkg/cli/zip.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-PSLL5VwC44E7l97w:-Nx-PSLL5VwC44E7l97x:b2v8nx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/zip.go#L327)):*
> ```Go
> 
> 			// Collect the per-node data.
> 			if err := zc.forAllNodes(ctx, nodesList, redactedNodesList, func(ctx context.Context, nodeDetails serverpb.NodeDetails, nodesStatus *statuspb.NodeStatus, redactedNodeDetails serverpb.NodeDetails, settings *cluster.Settings) error {
> ```

You passed the `settings` variable down but didn't use it, but see comment below, you won't need it here.
___
*[`pkg/cli/zip_cluster_wide.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-PKHM8dkpw7snJoFX:-Nx-PKHM8dkpw7snJoFY:b-rmy9y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/zip_cluster_wide.go#L226)):*
> ```Go
> 
> func shouldRedact() bool {
> 	return zipCtx.redact && DebugZipSensitiveFieldsRedactionEnabled.Get(&serverCfg.Settings.SV)
> ```

I think the `zipCtx.redact` flag should still be passed, but its implementation on the server-side should only apply if the cluster setting is enabled. That change should be made in the gRPC handlers that take the newly added `Redact` flag.

Additionally, the global var `serverCfg` is initialized on the **client** side during CLI execution to provide this object when necessary on the client side. Using it to retrieve cluster settings won't work since the CLI doesn't have access to them when it connects to the cluster to retrieve a debug zip.


<!-- Sent from Reviewable.io -->

2024-05-06 15:35 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/cli/zip.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-PSLL5VwC44E7l97w:-NxDXcAI78hfyYlkvAaa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/zip.go#L327)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

You passed the `settings` variable down but didn't use it, but see comment below, you won't need it here.
</blockquote></details>

Done.
___
*[`pkg/cli/zip_cluster_wide.go` line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-PKHM8dkpw7snJoFX:-NxDXdds0wq093jO8j29:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/zip_cluster_wide.go#L226)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I think the `zipCtx.redact` flag should still be passed, but its implementation on the server-side should only apply if the cluster setting is enabled. That change should be made in the gRPC handlers that take the newly added `Redact` flag.

Additionally, the global var `serverCfg` is initialized on the **client** side during CLI execution to provide this object when necessary on the client side. Using it to retrieve cluster settings won't work since the CLI doesn't have access to them when it connects to the cluster to retrieve a debug zip.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 17:07 UTC, dhartunian reviewed
This looks good, just rebase on `master` once the other PR is merged, and add docs changes and release note.

> Reviewed 5 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-:-NxDrMfA0pwkTH6IC2Ub:br0wd8z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kousiknath)

___
*[`pkg/server/cluster_settings.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDrabA35esYcv0znl4:-NxDrabA35esYcv0znl5:bzae55r) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/cluster_settings.go#L61)):*
> ```Go
> // DebugZipSensitiveFieldsRedactionEnabled guards whether hostname / ip address and other sensitive fields
> // should be redacted in the debug zip
> var DebugZipSensitiveFieldsRedactionEnabled = settings.RegisterBoolSetting(
> ```

You need to run `./dev gen` to get the settings docs generated. Those changes will need to be in the commit for it to pass the linter.
___
*[`pkg/server/status.go` line 746 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDr2zPAlhpx-0hyFE3:-NxDr2zPAlhpx-0hyFE4:b-68n0ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/status.go#L746)):*
> ```Go
> 	}
> 
> 	if req.Redact && DebugZipSensitiveFieldsRedactionEnabled.Get(&s.st.SV) {
> ```

Why did the `req != nil` disappear? is that not possible?


<!-- Sent from Reviewable.io -->

2024-05-07 10:14 UTC, kousiknath reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/server/cluster_settings.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDrabA35esYcv0znl4:-NxHXN7U19sjMQLjGSR4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/cluster_settings.go#L61)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

You need to run `./dev gen` to get the settings docs generated. Those changes will need to be in the commit for it to pass the linter.
</blockquote></details>

Done.
___
*[`pkg/server/status.go` line 746 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDr2zPAlhpx-0hyFE3:-NxHXSCcBm3SNFsIYJvG:bdpe1hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/status.go#L746)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Why did the `req != nil` disappear? is that not possible?
</blockquote></details>

Since `req.NodeId` is already used above, putting `req != nil` check here makes the linter believe that `nil` request is a possible input for this function. Thus it creates linter error.
___
*[`pkg/cli/settings.go` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-Oqa7AqMMp3s-mRW7:-NxHXrKF58wCE0e1zdW4:b-9h1jwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/06c4a8d5ea59828083ba2d3896625eb3dd5b8a34/pkg/cli/settings.go#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

add license
</blockquote></details>

The file is no longer required.


<!-- Sent from Reviewable.io -->

2024-05-07 13:40 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kousiknath)

___
*[`pkg/server/cluster_settings.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDrabA35esYcv0znl4:-NxIGnXY0CPyQevUgg3x:b-qg7ura) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/cluster_settings.go#L61)):*
<details><summary><i>Previously, kousiknath (Kousik Nath) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You didn't add the generated file to the commit.


<!-- Sent from Reviewable.io -->

2024-05-09 08:48 UTC, kousiknath reviewed
Made the changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-:-NxRXXs-3mwmMDD3d1rg:b-fcqwu8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`-- commits` line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-Nx-On0lEQb3LINB6RDm):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Add new cluster setting to release note as `(ops change)`.
</blockquote></details>

Done.
___
*[`pkg/server/cluster_settings.go` line 61 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NxDrabA35esYcv0znl4:-NxRX543DPRc9QseOpB2:b387id2) ([raw file](https://github.com/cockroachdb/cockroach/blob/946279a08b855d9e2b7c7e3e9cfa547476852484/pkg/server/cluster_settings.go#L61)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

You didn't add the generated file to the commit.
</blockquote></details>

Are you referring to the files changed under `docs/generated/settings`? Those changes are actually reflected in github.
![image.png](https://files.reviewableusercontent.io/images/reviewable/3245522/i6RBnyHVtGZd8PcjHOq6a4J5/image.png)


<!-- Sent from Reviewable.io -->

2024-05-14 07:50 UTC, arjunmahishi reviewed
Taking over this PR. Making the following changes: 
- the setting name is currently `debug.zipredact_sensitive.enabled`. Will change this to `debug.zip.redact_addresses.enabled` based on the [discussion here](https://cockroachlabs.atlassian.net/browse/CRDB-38270?focusedCommentId=224280).
- Rebase
- Fix formatting in the PR description and commit message

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-:-Nxq2UjFBhivRIF8vKi3:b4hcfxk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)



<!-- Sent from Reviewable.io -->

2024-05-21 15:26 UTC, dhartunian approved these changes
@arjunmahishi <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> just adjust the release note. thx.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-:-NyQk_Hg3_4GB0ns-RXW:bivt8tr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arjunmahishi and @kousiknath)

___
*[`-- commits` line 13 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NyQkROO39xzuJRCrYJ4):*
@arjunmahishi can you add a customer-facing explanation of what this setting does?


<!-- Sent from Reviewable.io -->

2024-05-21 16:55 UTC, arjunmahishi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123544)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

___
*[`-- commits` line 13 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/123544#-NyQkROO39xzuJRCrYJ4):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

@arjunmahishi can you add a customer-facing explanation of what this setting does?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-21 17:33 UTC, arjunmahishi commented
bors r+

2024-05-21 18:28 UTC, merged