ttl/ttlbase: Set ttl_delete_rate_limit to 100 instead of current 0 (u…
cockroachdb/cockroach pull request #124184
Opened 2024-05-14 21:53 UTC by Dedej-Bergin

…nlimited)

Previously we were using no rate limiting by default, and this could cause a slowdown. By changing the default rate limit to 100, we will avoid many possible slowdows caused by having no rate limiter.

Fixes: #122698

Release note (performance improvement): We are now setting ttl_delete_rate_limit to 100, this sets the default rate limit for deleting expired rows to 100.

2024-05-14 21:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/124184)
<!-- Reviewable:end -->

2024-05-16 20:13 UTC, rafiss approved these changes

2024-05-16 20:16 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124184)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124184#-Ny21WL20mNf5o1STYZv):*
nit: maybe instead of "performance improvement" we should make this "sql change". both could make sense here, but i think "sql change" is a bit better since we don't actually have a tangible performance number to point to


<!-- Sent from Reviewable.io -->

2024-05-17 15:09 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124184)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124184#-Ny21WL20mNf5o1STYZv):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: maybe instead of "performance improvement" we should make this "sql change". both could make sense here, but i think "sql change" is a bit better since we don't actually have a tangible performance number to point to
</blockquote></details>

Thanks Rafi, I just made this change


<!-- Sent from Reviewable.io -->

2024-05-17 15:09 UTC, rafiss approved these changes

2024-05-17 17:02 UTC, Dedej-Bergin commented
bors r+

2024-05-17 17:35 UTC, merged