release-23.2: cli/doctor, doctor: use right jobs table, skip dropped descs
cockroachdb/cockroach pull request #124365
Opened 2024-05-17 20:28 UTC by annrpom

Backport 2/2 commits from #123298.

/cc @cockroachdb/release

---

### cli/doctor: doctor should read from the right jobs table
In https://github.com/cockroachdb/cockroach/issues/97762, we started writing a job's payload (and progress)
information to the `system.jobs_info` table. As a result, we
had to change the parts of our code that relied on the `system.jobs`
table to use `crdb_internal.system_jobs` instead (since that table
would inaccurately report that some `payload`s were `NULL`).
This change did not occur for the in-memory representation of the jobs
table created by debug doctor -- which can result in missing job
false-positives. This patch updates debug doctor's representation of
the jobs table by referring to `crdb_internal.system_jobs` instead.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/122675

Release note: None

---

### doctor: skip validation for dropped descriptors
In some cases, dropped descriptors appear in our `system.descriptors`
table with dangling job mutations without an associated job.
This patch teaches debug doctor examine to skip validation
on such dropped descriptors.

Epic: none

Fixes: https://github.com/cockroachdb/cockroach/issues/123477
Fixes: https://github.com/cockroachdb/cockroach/issues/122956

Release note: none

2024-05-17 20:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/124365)
<!-- Reviewable:end -->

2024-05-20 20:06 UTC, rafiss approved these changes

2024-05-20 20:11 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124365)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @nameisbhaskar, and @vidit-bhat)

___
*[`pkg/sql/doctor/doctor_test.go` line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124365#-NyMcO5u4mHk9BGgTOeS:-NyMcO5u4mHk9BGgTOeT:b2ros2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/081b47156ba4755695af5b47f6420c25d2361cae/pkg/sql/doctor/doctor_test.go#L200)):*
> ```Go
> 			},
> 			valid:    true,
> 			expected: "Examining 1 descriptors and 0 namespace entries...\n",
> ```

nit: just noticed this. why are we removing the expected error check?
___
*[`pkg/sql/doctor/doctor_test.go` line 419 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124365#-NyMcO_Z-1D60ctr6C_O:-NyMcO_Z-1D60ctr6C_P:b2ros2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/081b47156ba4755695af5b47f6420c25d2361cae/pkg/sql/doctor/doctor_test.go#L419)):*
> ```Go
> 			},
> 			valid:    true,
> 			expected: "Examining 2 descriptors and 1 namespace entries...\n",
> ```

nit: just noticed this. why are we removing the expected error check?


<!-- Sent from Reviewable.io -->

2024-06-24 21:30 UTC, annrpom reviewed
resolving nits since they were addressed https://github.com/cockroachdb/cockroach/pull/124302#issuecomment-2121137588

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124365#-:-O0B97ak76mLkZ09WzwD:b3ldn4i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar and @vidit-bhat)



<!-- Sent from Reviewable.io -->

2024-08-07 02:49 UTC, rafiss approved these changes

2024-08-07 02:49 UTC, merged