acceptance: use `docker compose` (part 2)
cockroachdb/cockroach pull request #124876
Opened 2024-05-30 18:10 UTC by rail

Previously, we used docker-compose (V1) to run acceptance tests. docker compose is a plugin now and not a separate command, which supports V2 compose files. See
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2 for the details.

See also: #124865

Epic: none
Release note: None

2024-05-30 18:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/124876)
<!-- Reviewable:end -->

2024-05-30 18:15 UTC, Dedej-Bergin approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124876#-:-Nz9hYbw5q32fBQpGpF6:bb6ywmx)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2024-05-30 18:15 UTC, rickystewart approved these changes

2024-05-30 18:19 UTC, rickystewart requested changes
Looks like this breaks the test.

2024-05-31 14:01 UTC, rickystewart approved these changes

2024-05-31 14:02 UTC, rail commented
bors r=rickystewart,Dedej-Bergin

2024-05-31 15:01 UTC, merged