changefeedccl: Fix sink leaks in a few places
cockroachdb/cockroach pull request #126512
Opened 2024-07-01 19:28 UTC by asg0451

There are some places where we neglect to close
sinks, which lead to goroutine leaks and thus test
failures in the new Kafka sink PR.

Epic: CRDB-38892

Release note: none

2024-07-01 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/126512)
<!-- Reviewable:end -->

2024-07-02 15:55 UTC, wenyihu6 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451)

___
*[`pkg/ccl/changefeedccl/sink.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8Jd4DXwqOfNX8l9Q:-O0o8Jd4DXwqOfNX8l9R:bijwpa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L158)):*
> ```Go
> 	}
> 	if err := sink.Dial(); err != nil {
> 		if err := sink.Close(); err != nil {
> ```

Do you think it is possible to call sink.Close() inside sink.Dial() to be cleaner here? It feels to me that it is the sink responsibility to do the clean up here. 
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8iCc6owSS_Nq0oaz:-O0o8iCc6owSS_Nq0ob-:b-6ksphl) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/alter_changefeed_test.go#L68)):*
> ```Go
> 							return s
> 						}
> 						return &externalConnectionKafkaSink{sink: s, ignoreDialError: true}
> ```

Adding a new field ignoreDialError to a struct just for testing feels unsafe. Do you think we can use testingknobs here instead?


<!-- Sent from Reviewable.io -->

2024-07-02 17:14 UTC, asg0451 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8Jd4DXwqOfNX8l9Q:-O0oQaOh2zRhv5F7XEgX:b-k7v0uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L158)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Do you think it is possible to call sink.Close() inside sink.Dial() to be cleaner here? It feels to me that it is the sink responsibility to do the clean up here.
</blockquote></details>

I don't think that's idiomatic. Typically if a struct has a Close() method defined on it, you're expected to have to call it. In this case for a lot of sinks Dial() is a no-op anyway, whereas the constructor might spin up goroutines that need to be torn down.
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8iCc6owSS_Nq0oaz:-O0oR6i22aQ33EMR_DtI:bhg59x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/alter_changefeed_test.go#L68)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Adding a new field ignoreDialError to a struct just for testing feels unsafe. Do you think we can use testingknobs here instead?
</blockquote></details>

This is actually a testing only struct so I don't think it's unsafe: https://github.com/asg0451/cockroach/blob/9011c7d89905031b77c1a348fdb85b8e65436fc5/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L34


<!-- Sent from Reviewable.io -->

2024-07-06 04:01 UTC, andyyang890 reviewed
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451 and @wenyihu6)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O156PHA6Hf501vX_GI3):*
nit: don't capitalize the first word after the package prefix
___
*[`pkg/ccl/changefeedccl/sink.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8Jd4DXwqOfNX8l9Q:-O15BYAhDA1lr7clZ7JT:b8u1kkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L158)):*
<details><summary><i>Previously, asg0451 (Miles Frankel) wrote…</i></summary><blockquote>

I don't think that's idiomatic. Typically if a struct has a Close() method defined on it, you're expected to have to call it. In this case for a lot of sinks Dial() is a no-op anyway, whereas the constructor might spin up goroutines that need to be torn down.
</blockquote></details>

+1 to not calling `Close` inside `Dial`, I don't think that would make sense in the non-error case
___
*[`pkg/ccl/changefeedccl/sink.go` line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O15AWdO4Mp9lnqLXoo9:-O15AWdO4Mp9lnqLXooA:b-qokqg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L159)):*
> ```Go
> 	if err := sink.Dial(); err != nil {
> 		if err := sink.Close(); err != nil {
> 			return nil, errors.CombineErrors(err, errors.Wrap(err, `failed to close sink`))
> ```

Is the intent here to combine the error from `sink.Dial` with the error from `sink.Close`? If so, I think that's not actually happening because the `err` from the `sink.Dial` is shadowed by the `err` from `sink.Close`. Maybe rename the variables to `dialErr` and `closeErr`?
___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O158zGm72G2O6JmHJlw:-O158zGm72G2O6JmHJlx:b3qhau7) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink_pubsub.go#L502)):*
> ```Go
> 
> func (p *deprecatedGcpPubsubClient) close() error {
> 	if p.client == nil {
> ```

Moving this code changes the behavior since now the `p.forEachTopic` below won't be called if `p.client == nil`. Is that okay here?
___
*[`pkg/ccl/changefeedccl/sink_kafka_connection_test.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O15B6QH0a4DI3YQZX88:-O15B6QH0a4DI3YQZX89:bvgh7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L36)):*
> ```Go
> type externalConnectionKafkaSink struct {
> 	sink            Sink
> 	ignoreDialError bool
> ```

Do you mind explaining why we might want to ignore the dial error sometimes? Could you also add that as a comment above this field?


<!-- Sent from Reviewable.io -->

2024-07-08 13:42 UTC, asg0451 reviewed
> Dismissed @wenyihu6 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink.go` line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8Jd4DXwqOfNX8l9Q:-O1HYiEh2OVpL00sAe7t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L158)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

+1 to not calling `Close` inside `Dial`, I don't think that would make sense in the non-error case
</blockquote></details>

Done.
___
*[`pkg/ccl/changefeedccl/sink.go` line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O15AWdO4Mp9lnqLXoo9:-O1HYliQ-vjmwvqTsQT5:bumzmf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink.go#L159)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Is the intent here to combine the error from `sink.Dial` with the error from `sink.Close`? If so, I think that's not actually happening because the `err` from the `sink.Dial` is shadowed by the `err` from `sink.Close`. Maybe rename the variables to `dialErr` and `closeErr`?
</blockquote></details>

good catch thx
___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O158zGm72G2O6JmHJlw:-O1HZ8n51Z9aR11iTBRk:bx2mlmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/sink_pubsub.go#L502)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Moving this code changes the behavior since now the `p.forEachTopic` below won't be called if `p.client == nil`. Is that okay here?
</blockquote></details>

i think it's ok, since the only way p.client is nil is if we're Closing before Dialing. Which happens now (more frequently -- it might be able to happen without this pr though) because we close sinks after creating them instead of leaking them.

Without this change, if we call forEachTopic before dialing, it results in a nil ptr deref.


<!-- Sent from Reviewable.io -->

2024-07-08 14:51 UTC, andyyang890 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-:-O1Hp2tRAIUxtVWGXGk2:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @asg0451 and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_kafka_connection_test.go` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O1Hp-Y2AlktqzArX18Y:-O1Hp-Y2AlktqzArX18Z:b-8yjd3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/aea98e1f61697f39277e391f4e7df357c0ecf4d7/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L36)):*
> ```Go
> type externalConnectionKafkaSink struct {
> 	sink Sink
> 	// ignoreDialError causes this wrapper to ignore errors calling it's inner
> ```

nit: s/it's/its


<!-- Sent from Reviewable.io -->

2024-07-10 03:45 UTC, rharding6373 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice find! Do you know of a reason why we shouldn't backport this change? Seems like it fixes a bug.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-:-O1Pih4yCiStapftBf4f:bm4hk2f)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @andyyang890, @asg0451, and @wenyihu6)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O1Pe9rn8Lr9FjRQ5zem):*
This should have a "bug fix" release note, since it appears that this could leak in prod.
___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8iCc6owSS_Nq0oaz:-O1PjQiG-f6Qk6Ris7kF:brb3toa) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/alter_changefeed_test.go#L68)):*
<details><summary><i>Previously, asg0451 (Miles Frankel) wrote…</i></summary><blockquote>

This is actually a testing only struct so I don't think it's unsafe: https://github.com/asg0451/cockroach/blob/9011c7d89905031b77c1a348fdb85b8e65436fc5/pkg/ccl/changefeedccl/sink_kafka_connection_test.go#L34
</blockquote></details>

Agree this should be ok since it's only accessible in tests.


<!-- Sent from Reviewable.io -->

2024-07-11 16:30 UTC, asg0451 reviewed
I know of no such reason

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-:-O1XbjCE2nHFrIW-_9Il:b-6obk5u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andyyang890, @rharding6373, and @wenyihu6)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O1Pe9rn8Lr9FjRQ5zem):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This should have a "bug fix" release note, since it appears that this could leak in prod.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-11 16:31 UTC, asg0451 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andyyang890, @rharding6373, and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/alter_changefeed_test.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O0o8iCc6owSS_Nq0oaz:-O1XcVIQ6A7TjVyfoa9I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fc585df4214566989ef509d0a7ec0c2a9d5aae/pkg/ccl/changefeedccl/alter_changefeed_test.go#L68)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Agree this should be ok since it's only accessible in tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-12 13:53 UTC, wenyihu6 approved these changes

2024-07-12 14:19 UTC, andyyang890 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-:-O1bIwSxD8g_zOCzAQ2t:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asg0451, @rharding6373, and @wenyihu6)

___
*[`-- commits` line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126512#-O1bIqEjDct8UxfNclVq):*
nit: s/changfeed/changefeed


<!-- Sent from Reviewable.io -->

2024-07-15 14:38 UTC, asg0451 commented
bors r=rharding6373,andyyang890,wenyihu6

2024-07-15 15:03 UTC, merged