workload/schemachange: get drop column ready, increase opweight of create table
cockroachdb/cockroach pull request #126965
Opened 2024-07-10 22:22 UTC by annrpom

2024-07-10 22:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/126965)
<!-- Reviewable:end -->

2024-07-10 23:10 UTC, annrpom commented
@rafiss: thank you for the `lexbase.EncodeRestrictedSQLIdent` pointer; i went with this instead of the fetching column change because the latter affected too many ops for me to feel non-nauseous about. i'd imagine this change will need to get applied to other ops. if the workload fails because of that, feel free to assign those issues to me

2024-07-11 00:07 UTC, fqazi approved these changes
@annrpom Nice work! <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-:-O1U6NrE88rhnPMt0wHX:b-8mpbi5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar, @rafiss, and @srosenberg)



<!-- Sent from Reviewable.io -->

2024-07-11 16:12 UTC, rafiss requested changes
nice work! just had some nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-:-O1XZIVbBdAM3oOI1Nif:b4pswln)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @nameisbhaskar, and @srosenberg)

___
*[`pkg/workload/schemachange/error_screening.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XXJeC05x-cmC8sOmO:-O1XXJeC05x-cmC8sOmP:baw2sqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b95c570737c4801e23c902f41359ce6af4c375a/pkg/workload/schemachange/error_screening.go#L491)):*
> ```Go
> 	}
> 
> 	notAllowed, err := og.scanBool(
> ```

nit: naming a boolean variable with the word `not` in the name always feels confusing to me. also both `allowed` and `notAllowed` don't convey what we _actually_ are looking at here. i feel like a better name to minimize confusion here is `isIndexDropping`
___
*[`pkg/workload/schemachange/error_screening.go` line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XXwB95JWZmfDtXget:-O1XXwB95JWZmfDtXgeu:b-8q9llm) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f6883dfb94893e255ca780086c19250bdf366f/pkg/workload/schemachange/error_screening.go#L200)):*
> ```Go
>        AND attrelid = $1::REGCLASS
>        AND pg_get_expr(adbin, adrelid) ILIKE '%%' || $2 || '%%'
> )`, tableName.String(), columnName)
> ```

is `tableName.String()` the correct thing to use here? i believe that will result in a double-quoted string if the table name has mixed case characters, and i don't think we want to pass in a double-quoted string for a placeholder argument. i believe we actually want `lexbase.EscapeSQLString(string(tableName))` here.

the main difference is we should use `name.String()` if the name is being used as an identifier in the statement, and we should use `string(name)` is the name is being used as a string constant in the statement. in this case, it's a string constant that is being case to the `regclass` type.

another example of this is here: https://github.com/cockroachdb/cockroach/blob/8e4578b0e205020ded494b2274185ad3a6c84029/pkg/sql/delegate/show_partitions.go#L100-L101


<!-- Sent from Reviewable.io -->

2024-07-11 16:15 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126965)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @nameisbhaskar, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 1578 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XZpXP26_Z5DtrSGlX:-O1XZpXP26_Z5DtrSGlY:by5iim5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a170c45e24fbae9136aa9729721aad4f6e2a7920/pkg/workload/schemachange/operation_generator.go#L1578)):*
> ```Go
> 	var buf bytes.Buffer
> 	lexbase.EncodeRestrictedSQLIdent(&buf, columnName, lexbase.EncNoFlags)
> 	stmt.sql = fmt.Sprintf(`ALTER TABLE %s DROP COLUMN %s`, tableName, buf.String())
> ```

nit: an even quicker way to do it is with `EscapeSQLIdent` to avoid needing to declare a buffer:
```
fmt.Sprintf(`ALTER TABLE %s DROP COLUMN %s`, tableName, lexbase.EscapeSQLIdent(columnName))
```


<!-- Sent from Reviewable.io -->

2024-07-11 19:24 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126965)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar, @rafiss, and @srosenberg)

___
*[`pkg/workload/schemachange/error_screening.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XXJeC05x-cmC8sOmO:-O1Y49tW96LLtbNlaZ75:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b95c570737c4801e23c902f41359ce6af4c375a/pkg/workload/schemachange/error_screening.go#L491)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: naming a boolean variable with the word `not` in the name always feels confusing to me. also both `allowed` and `notAllowed` don't convey what we _actually_ are looking at here. i feel like a better name to minimize confusion here is `isIndexDropping`
</blockquote></details>

done
___
*[`pkg/workload/schemachange/error_screening.go` line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XXwB95JWZmfDtXget:-O1Y3Oqx1QbBVX1P3TaU:bgam3uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/08f6883dfb94893e255ca780086c19250bdf366f/pkg/workload/schemachange/error_screening.go#L200)):*
> that will result in a double-quoted string if the table name has mixed case characters

oh yes it does -- TIL... hm FWIW i don't think we generate any tables out of the form ` table_name SIMILAR TO 'table_w[0-9]_+%`

or at least if we do, we don't choose those tables (https://github.com/cockroachdb/cockroach/blob/a170c45e24fbae9136aa9729721aad4f6e2a7920/pkg/workload/schemachange/operation_generator.go#L3578)

our other error_screening does it this way https://github.com/cockroachdb/cockroach/blob/08f6883dfb94893e255ca780086c19250bdf366f/pkg/workload/schemachange/error_screening.go#L208-L222 as well, but i'm not opposed to doing the "more correct" thing here

although, does `string(tableName)` work? i think we can only do string(bleh) on a tree.Name so only on the schema, object, catalog?
___
*[`pkg/workload/schemachange/operation_generator.go` line 1578 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126965#-O1XZpXP26_Z5DtrSGlX:-O1Y4K8d4mcR-A9TLPg1:bgjbsmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a170c45e24fbae9136aa9729721aad4f6e2a7920/pkg/workload/schemachange/operation_generator.go#L1578)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: an even quicker way to do it is with `EscapeSQLIdent` to avoid needing to declare a buffer:
```
fmt.Sprintf(`ALTER TABLE %s DROP COLUMN %s`, tableName, lexbase.EscapeSQLIdent(columnName))
```
</blockquote></details>

:o done


<!-- Sent from Reviewable.io -->

2024-07-11 21:02 UTC, annrpom commented
This might be weird, but I plan on having 1 PR at the end of all of this that I merge at the same time so we dont get a flaky schemachange workload. My theory is that the first commit will introduce flakiness to the workload since it was "protecting" us from doing anything (hence CI on this PR)

I'll make some stacked PRs that have a sets of commits that make sense

2024-07-18 18:22 UTC, closed without merging

2024-07-18 18:22 UTC, annrpom commented
ok i'll just close the precursor PRs out since people have mainly been looking at the big one