ui: fix query fetching store ids for db/tables
cockroachdb/cockroach pull request #127015
Opened 2024-07-11 18:00 UTC by xinhaoz

These queries were updated in #118904 to make them more performant.
In that change we mistakenly removed the null check before reading
the `rows` field, causing pages using this request to crash if this
query fails.

Epic: none
Fixes: #126348

Release note (bug fix): Database overview and db details
pages should not crash if the range information is not
available.Backport:
  * 1/1 commits from "ui: fix query fetching store ids for db/tables" (#126419)
  * 1/1 commits from "cluster-ui: remove quotes in table name in db details" (#126961)

Please see individual PRs for details.

/cc @cockroachdb/release

2024-07-11 18:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/127015)
<!-- Reviewable:end -->

2024-07-12 14:08 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127015)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/databases/util.tsx` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127015#-O1bFzdj6ZRp8NmFXw_1:-O1bFzdj6ZRp8NmFXw_2:b-l599j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6791e6a8ba078bca11147bde0d8c33bd9e7b41/pkg/ui/workspaces/cluster-ui/src/databases/util.tsx#L312)):*
> ```XML
> export const formatSQLTableName = (tableName: string): string => {
>   return tableName.replace(/"([^"]+)"/g, (_, part) => {
>     // If it has a space or period keep it in quotes.
> ```

this isn't the only case where quotes aren't needed. it's also important to keep the quotes if the name is mixed-case, has commas, and also a few other situations.

here is the go function that detects if quotes are needed or not: https://github.com/cockroachdb/cockroach/blob/bb780b728a6830ad9bcb6d3796f5e22d01912b13/pkg/sql/lexbase/predicates.go#L76-L99


<!-- Sent from Reviewable.io -->

2024-07-12 15:12 UTC, xinhaoz commented
*[`pkg/ui/workspaces/cluster-ui/src/databases/util.tsx` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127015#-O1bFzdj6ZRp8NmFXw_1:-O1bN2DJ77sCiDC6BIUf:b-ul1tuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6791e6a8ba078bca11147bde0d8c33bd9e7b41/pkg/ui/workspaces/cluster-ui/src/databases/util.tsx#L312)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this isn't the only case where quotes aren't needed. it's also important to keep the quotes if the name is mixed-case, has commas, and also a few other situations.

here is the go function that detects if quotes are needed or not: https://github.com/cockroachdb/cockroach/blob/bb780b728a6830ad9bcb6d3796f5e22d01912b13/pkg/sql/lexbase/predicates.go#L76-L99
</blockquote></details>

Thanks for the link, I'll definitely be saving that!

This function is used purely for visual changes on how table names are shown in the db pages since the quotes were distracting so This change won't affect how the table names were being sent to any of our APIs - currently all the table names are being quoted via functions in [safesql.ts](https://github.com/cockroachdb/cockroach/blob/e2b09c10a0ed488fb1aba5dfa76eee8fe1f0d2bd/pkg/ui/workspaces/cluster-ui/src/api/safesql.ts)  so they have the right format for sql requests.

I'm wondering if that changes your opinion here, or if you think it should just align with how it would be encoded in sql? For example I feel like having mixed case may not be a motivation (visually) to quote the name part, but maybe commas and special characters would be? In any case let me know and I can make the appropriate changes!


<!-- Sent from Reviewable.io -->

2024-07-12 15:26 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127015)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/databases/util.tsx` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127015#-O1bFzdj6ZRp8NmFXw_1:-O1bXtTn-94m_sKQF4uR:bqhz41t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6791e6a8ba078bca11147bde0d8c33bd9e7b41/pkg/ui/workspaces/cluster-ui/src/databases/util.tsx#L312)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Thanks for the link, I'll definitely be saving that!

This function is used purely for visual changes on how table names are shown in the db pages since the quotes were distracting so This change won't affect how the table names were being sent to any of our APIs - currently all the table names are being quoted via functions in [safesql.ts](https://github.com/cockroachdb/cockroach/blob/e2b09c10a0ed488fb1aba5dfa76eee8fe1f0d2bd/pkg/ui/workspaces/cluster-ui/src/api/safesql.ts)  so they have the right format for sql requests.

I'm wondering if that changes your opinion here, or if you think it should just align with how it would be encoded in sql? For example I feel like having mixed case may not be a motivation (visually) to quote the name part, but maybe commas and special characters would be? In any case let me know and I can make the appropriate changes!
</blockquote></details>

i feel like it's best to use the exact same quoting rules. as a developer, if i notice something interesting in the DB console, i would want to be able to just copy/paste the name i see there and be able to use it to query for more information.

even apart from that, it's a bit confusing if we are not consistent about how we display SQL identifiers. it will make it harder for customers to remember when they need quotes and when they don't.


<!-- Sent from Reviewable.io -->

2024-07-12 15:33 UTC, xinhaoz commented
*[`pkg/ui/workspaces/cluster-ui/src/databases/util.tsx` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/127015#-O1bFzdj6ZRp8NmFXw_1:-O1bZ90I3Q6rja6awokw:bwyxab8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac6791e6a8ba078bca11147bde0d8c33bd9e7b41/pkg/ui/workspaces/cluster-ui/src/databases/util.tsx#L312)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i feel like it's best to use the exact same quoting rules. as a developer, if i notice something interesting in the DB console, i would want to be able to just copy/paste the name i see there and be able to use it to query for more information.

even apart from that, it's a bit confusing if we are not consistent about how we display SQL identifiers. it will make it harder for customers to remember when they need quotes and when they don't.
</blockquote></details>

Fair point. I'll close this backport (and related ones) and re-open once the revision lands on master.


<!-- Sent from Reviewable.io -->

2024-07-12 16:20 UTC, xinhaoz commented
Closing - discussed offline and we'll backport a version that shows the table names to match output from something like `SHOW TABLES` to give a more user-friendly experience. Users can still see the sql encoded string via the create table statement in the table details page.

2024-07-12 16:20 UTC, closed without merging