jwtauthccl: Move HTTP client timeout into a cluster setting
cockroachdb/cockroach pull request #127145
Opened 2024-07-15 06:23 UTC by pritesh-lahoti

Currently, the external calls made during JWT authentication use a default HTTP client timeout. We would like to make this configurable similar to OIDC by exposing this through a cluster setting. This change introduces server.jwt_authentication.client.timeout to capture this intent.

Fixes: #126546
Epic: CRDB-39971

Release note (enterprise change, ops change): A new public cluster setting server.jwt_authentication.client.timeout has been introduced to capture the HTTP client timeout for external calls made during JWT authentication.

2024-07-17 16:55 UTC, souravcrl requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20Zwn55bPwJKtGULtZ:-O20Zwn55bPwJKtGULt_:btunvmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt.go#L101)):*
> ```Go
> 		httpClient: httputil.NewClient(
> 			httputil.WithClientTimeout(clientTimeout),
> 			httputil.WithDialerTimeout(clientTimeout),
> ```

Do we want to wait that long for dialer timeouts since server maybe not reachable and having dialer timeout as 30s will unintentionally prolong erroring?
___
*[`pkg/ccl/jwtauthccl/settings.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20aFEK2xPHQ3UOSGZ3:-O20aFEK2xPHQ3UOSGZ4:b-5v47bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/settings.go#L111)):*
> ```Go
> 		"(e.g. fetching JWKS, etc.)",
> 	30*time.Second,
> 	settings.NonNegativeDuration,
> ```

Is the value for crdb client context timer configurable? If so, should we throw a warning if operators are trying to set a value higher that database client context timeout?
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 1032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20avJi-U4Lo4JqUbdi:-O20avJi-U4Lo4JqUbdj:b-1uikkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L1032)):*
> ```Go
> 	verifier := ConfigureJWTAuth(ctx, s.AmbientCtx(), s.ClusterSettings(), s.StorageClusterID())
> 	errMsg, err := verifier.ValidateJWTLogin(
> 		ctx,
> ```

Should we manually set the context being passed to http handle as expired in the mock implementation since we have access to it here? I feel unit tests should not wait on timer timeouts even if for a short duration of a millisecond as it might cause the test to flake. If there are instances  of tests where we doing this, then I think this maybe ok.


<!-- Sent from Reviewable.io -->

2024-07-17 16:57 UTC, souravcrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20Zwn55bPwJKtGULtZ:-O20boLe2d3YGhr5-Zs9:b6yg5fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt.go#L101)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Do we want to wait that long for dialer timeouts since server maybe not reachable and having dialer timeout as 30s will unintentionally prolong erroring?
</blockquote></details>

Client timeouts maybe justifiable if the server is busy with too many requests. In this case do you feel dialing time will also be more?


<!-- Sent from Reviewable.io -->

2024-07-17 18:50 UTC, souravcrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/settings.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20aFEK2xPHQ3UOSGZ3:-O20yNgPE3rj2wWV0Nay:bezhcqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/settings.go#L111)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Is the value for crdb client context timer configurable? If so, should we throw a warning if operators are trying to set a value higher that database client context timeout?
</blockquote></details>

actually this is configurable via connection string parameter `connect_timeout` and is defaulted to 15s here:
https://github.com/cockroachdb/cockroach/blob/49e828ae140febb9aa174f4d93e79e448999ef7f/pkg/cmd/cockroach-sql/main.go#L80-L85


<!-- Sent from Reviewable.io -->

2024-07-18 06:03 UTC, pritesh-lahoti reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20Zwn55bPwJKtGULtZ:-O23O5o3EADvUs9Q23Gh:b-6v7hfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt.go#L101)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Client timeouts maybe justifiable if the server is busy with too many requests. In this case do you feel dialing time will also be more?
</blockquote></details>

We could set the dialer timeout a bit lower, but 30s is standard. `http.DefaultTransport` also has 30s dialer timeout.
The cluster setting allows customers to tweak this timeout as desired.
___
*[`pkg/ccl/jwtauthccl/settings.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20aFEK2xPHQ3UOSGZ3:-O23OoKDAYlhKSpGIeEa:b3s6cy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/settings.go#L111)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

actually this is configurable via connection string parameter `connect_timeout` and is defaulted to 15s here:
https://github.com/cockroachdb/cockroach/blob/49e828ae140febb9aa174f4d93e79e448999ef7f/pkg/cmd/cockroach-sql/main.go#L80-L85
</blockquote></details>

The HTTP client timeout is applicable for all the outbound requests and they need not necessarily originate from the CRDB client, although with jwtauthccl, this is not the case as of today (unlike oidcccl).
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 1032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20avJi-U4Lo4JqUbdi:-O23QJyD5OfnTsaYdpN4:b47ed2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L1032)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Should we manually set the context being passed to http handle as expired in the mock implementation since we have access to it here? I feel unit tests should not wait on timer timeouts even if for a short duration of a millisecond as it might cause the test to flake. If there are instances  of tests where we doing this, then I think this maybe ok.
</blockquote></details>

We do not use this `ctx` at the time of making the HTTP request.
```
var getHttpResponse = func(ctx context.Context, url string, authenticator *jwtAuthenticator) ([]byte, error) {
	resp, err := authenticator.mu.conf.httpClient.Get(context.Background(), url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return body, nil
}
```
The timeout is governed by the `httpClient`.

We are using a similar test within oidcccl. With `<-waitChan`, it is guaranteed that the server will never return even with a different timeout. Having said, will continue to keep an eye out in case there is any flakiness.


<!-- Sent from Reviewable.io -->

2024-07-31 08:33 UTC, souravcrl requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20Zwn55bPwJKtGULtZ:-O36qN4l5p5fzFeNUlTr:b40us1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt.go#L101)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

We could set the dialer timeout a bit lower, but 30s is standard. `http.DefaultTransport` also has 30s dialer timeout.
The cluster setting allows customers to tweak this timeout as desired.
</blockquote></details>

Can we keep the values same as the `StandardHTTPTimeout` of 3s as we haven't observed any issues with this configuration for JWT/JWKS fetch yet? The second part of my reasoning is tied to `PG_CONNECT` timeout which is managed by client PG libraries and is part of connection string. Even CRDB has a client managed param `connect_timeout` which is 15s by default and setting higher dialer/client timeout is not consistent with that setting.
___
*[`pkg/ccl/jwtauthccl/settings.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20aFEK2xPHQ3UOSGZ3:-O36rT5R8YSBP9HY-Dgx:bhypdbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/settings.go#L111)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

The HTTP client timeout is applicable for all the outbound requests and they need not necessarily originate from the CRDB client, although with jwtauthccl, this is not the case as of today (unlike oidcccl).
</blockquote></details>

Please refer to my comment above regarding `PG_CONNECT` and `connect_timeout` to consider having this validation. Both of these are PG client side settings and may not fit for evaluation here for cluster setting's value but default value should be either `StandardHTTPTimeout` or some value less than default `connect_timeout` value. 
___
*[`pkg/ccl/jwtauthccl/authentication_jwt_test.go` line 1032 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20avJi-U4Lo4JqUbdi:-O36tZDJ6FpG17CLhZyL:bl4uzec) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt_test.go#L1032)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

We do not use this `ctx` at the time of making the HTTP request.
```
var getHttpResponse = func(ctx context.Context, url string, authenticator *jwtAuthenticator) ([]byte, error) {
	resp, err := authenticator.mu.conf.httpClient.Get(context.Background(), url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return body, nil
}
```
The timeout is governed by the `httpClient`.

We are using a similar test within oidcccl. With `<-waitChan`, it is guaranteed that the server will never return even with a different timeout. Having said, will continue to keep an eye out in case there is any flakiness.
</blockquote></details>

```
defer func() {
		waitChan <- struct{}{}
		close(waitChan)
		testServer.Close()
	}()
``` 
This defer get called after test timeout and test may not timeout for variety of reason(like stress test conditions). In that case test timeout maybe greater than pipeline test timeout value which can cause the flake. Since we can't access the context this seems to be the only way to test the timeout. We should monitor this for flakiness as you mentioned.


<!-- Sent from Reviewable.io -->

2024-07-31 13:32 UTC, pritesh-lahoti reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kyle-a-wong and @souravcrl)

___
*[`pkg/ccl/jwtauthccl/authentication_jwt.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20Zwn55bPwJKtGULtZ:-O37zVi07Qsnoxd9PNzH:blqlr9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/authentication_jwt.go#L101)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Can we keep the values same as the `StandardHTTPTimeout` of 3s as we haven't observed any issues with this configuration for JWT/JWKS fetch yet? The second part of my reasoning is tied to `PG_CONNECT` timeout which is managed by client PG libraries and is part of connection string. Even CRDB has a client managed param `connect_timeout` which is 15s by default and setting higher dialer/client timeout is not consistent with that setting.
</blockquote></details>

Updated the timeout to 15s
___
*[`pkg/ccl/jwtauthccl/settings.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-O20aFEK2xPHQ3UOSGZ3:-O37zXZ6AmvTqMH0OZs8:blqlr9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e22dabab625cc77a7a739acd5426be463f11a2f8/pkg/ccl/jwtauthccl/settings.go#L111)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Please refer to my comment above regarding `PG_CONNECT` and `connect_timeout` to consider having this validation. Both of these are PG client side settings and may not fit for evaluation here for cluster setting's value but default value should be either `StandardHTTPTimeout` or some value less than default `connect_timeout` value.
</blockquote></details>

Updated the timeout to 15s


<!-- Sent from Reviewable.io -->

2024-07-31 18:44 UTC, souravcrl approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127145#-:-O395s7o5TfTt-zObYXf:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pritesh-lahoti)



<!-- Sent from Reviewable.io -->

2024-08-01 05:36 UTC, pritesh-lahoti commented
bors r=souravcrl

2024-08-01 06:04 UTC, merged