sql: support partial stats at extremes without specifying columns
cockroachdb/cockroach pull request #127836
Opened 2024-07-29 14:58 UTC by Uzair5162

This commit adds support to collect partial statistics at extremes without specifying a column, such as:

`CREATE STATISTICS my_stat FROM t USING EXTREMES`

This will collect partial stats on a default set of columns, which are all single columns that are prefixes of forwards indexes.

Closes: #127832

Release note (sql): Partial stats at extremes can now be collected on all valid columns of a table using the `CREATE STATISTICS <stat_name> FROM <table_name> USING EXTREMES` syntax, without an `ON <col_name>` clause. Valid columns are all single column prefixes of a forward index.

2024-07-29 14:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/127836)
<!-- Reviewable:end -->

2024-07-29 18:35 UTC, DrewKimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-:-O2zlf5jAP7QgHxLQs94:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @Uzair5162)

___
*[`pkg/sql/create_stats.go` line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O2zjBWWECP2uYG6Tr9C:-O2zjBWWECP2uYG6Tr9D:b-78uqr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ba9ca8cf7a47b3512148b3a66fbb869d0158f/pkg/sql/create_stats.go#L486)):*
> ```Go
> 	}
> 
> 	// Only collect statistics on single columns that are prefixes of forwards
> ```

[nit] `forwards` -> `forward`


<!-- Sent from Reviewable.io -->

2024-07-29 20:49 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/create_stats.go` line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O2zjBWWECP2uYG6Tr9C:-O3-FJNeB9YdkgC_GEK1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb1ba9ca8cf7a47b3512148b3a66fbb869d0158f/pkg/sql/create_stats.go#L486)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `forwards` -> `forward`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-30 17:42 UTC, michae2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @Uzair5162)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33RwFT4e-7WZnV8sn1):*
nit: another forwards -> forward
___
*[`pkg/sql/create_stats.go` line 732 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33hv8uDk3rI40t9kGc:-O33hv8uDk3rI40t9kGd:b6wdb42) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L732)):*
> ```Go
> 				singleColDetails.ColumnStats = []jobspb.CreateStatsDetails_ColStat{colStat}
> 				planCtx := dsp.NewPlanningCtx(ctx, innerEvalCtx, innerP, txn.KV(), FullDistribution)
> 				if err = dsp.planAndRunCreateStats(
> ```

Using separate distsql invocations for each index makes sense to me, but I'm still thinking through the ramifications. I'm trying to figure out if we would need a separate planner and/or transaction for each invocation.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 3365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33iHkV48fJ4nHFfjqY:-O33iHkV48fJ4nHFfjqZ:b-e4wzz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/logictest/testdata/logic_test/distsql_stats#L3365)):*
> ```
>   INDEX(b, c, d),
>   INDEX(d),
>   INVERTED INDEX (j)
> ```

More kinds of index to test:
* hash-sharded index like `INDEX (e) USING HASH`
* partial index like `INDEX (f) WHERE c > 5`
* expression index like `INDEX ((g + 1))`

It would also be nice to add a test with a `LOCALITY REGIONAL BY ROW` table. I can help with this.


<!-- Sent from Reviewable.io -->

2024-07-30 17:42 UTC, michae2 commented
Meant to say: awesome work!!!!

2024-07-30 22:15 UTC, michae2 requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @Uzair5162)

___
*[`pkg/sql/create_stats.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34eEV-3n9Dm1wJRJEV:-O34eEV-3n9Dm1wJRJEW:blhnak3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L492)):*
> ```Go
> 			}
> 			if idx.NumKeyColumns() != 0 {
> 				colID := idx.GetKeyColumnID(0)
> ```

I think for an implicitly partitioned index (such as the primary index of a `LOCALITY REGIONAL BY ROW` table, or a hash-sharded index such as `INDEX (e) USING HASH`) we actually want to do something smarter, and collect stats over the first column _after_ the partition key. But I think this will also require changes to this function to build the correct spans: https://github.com/cockroachdb/cockroach/blob/329b8ca1ae039d59e6ffcb6d4c6ecc53a0af403a/pkg/sql/stats/bounds/extremes.go#L59

So it's probably better to skip over indexes for which `idx.IsSharded()` or `idx.ImplicitPartitioningColumnCount() > 0` are true.
___
*[`pkg/sql/create_stats.go` line 732 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33hv8uDk3rI40t9kGc:-O34Uz4L16Cw4P9ZWXpW:b-266g3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L732)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Using separate distsql invocations for each index makes sense to me, but I'm still thinking through the ramifications. I'm trying to figure out if we would need a separate planner and/or transaction for each invocation.
</blockquote></details>

After thinking more, `dsp.planAndRunCreateStats` is synchronous, so these will run serially. Running serially in a single transaction is fine, and these should each be fairly short since they're each performing a constrained scan. So this looks good to me.
___
*[`pkg/sql/distsql_plan_stats.go` line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34Zscp-jaHBBd6ff5t:-O34Zscp-jaHBBd6ff5u:b63f6op) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/distsql_plan_stats.go#L174)):*
> ```Go
> 			// The total expected number of rows is the same number that was measured
> 			// most recently, plus some overhead for possible insertions.
> 			float64(tableStats[0].RowCount) * (1 + overhead),
> ```

`rowsExpected` is used to estimate the overall progress of `CREATE STATISTICS`, which we report live as the job runs. I think this will be incorrect for `CREATE STATISTICS USING EXTREMES` in two ways: (a) this calculation assumes a full table scan, rather than a partial constrained scan, and (b) for this variant of `USING EXTREMES` a single job will consist of multiple invocations of `planAndRunCreateStats` instead of a single invocation, so this `rowsExpected` is only a portion of the total.

So for `USING EXTREMES` I have two ideas:
1. we should probably use `RowCount * overhead` instead of `RowCount * (1 + overhead)`
2. and then we should maybe either multiply this `rowsExpected` by the number of indexes we expect to scan, or maybe better: plumb a count of the number of indexes into sample_aggregator so that we can divide the reported progress here: https://github.com/cockroachdb/cockroach/blob/558771f5090b3133476da85a0becc24309ff1888/pkg/sql/rowexec/sample_aggregator.go#L268


<!-- Sent from Reviewable.io -->

2024-08-08 16:16 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`-- commits` line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33RwFT4e-7WZnV8sn1):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: another forwards -> forward
</blockquote></details>

Done.
___
*[`pkg/sql/create_stats.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34eEV-3n9Dm1wJRJEV:-O3mjeXtB376yfX6hRZX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L492)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think for an implicitly partitioned index (such as the primary index of a `LOCALITY REGIONAL BY ROW` table, or a hash-sharded index such as `INDEX (e) USING HASH`) we actually want to do something smarter, and collect stats over the first column _after_ the partition key. But I think this will also require changes to this function to build the correct spans: https://github.com/cockroachdb/cockroach/blob/329b8ca1ae039d59e6ffcb6d4c6ecc53a0af403a/pkg/sql/stats/bounds/extremes.go#L59

So it's probably better to skip over indexes for which `idx.IsSharded()` or `idx.ImplicitPartitioningColumnCount() > 0` are true.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_plan_stats.go` line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34Zscp-jaHBBd6ff5t:-O3Irt3lAovLVdmiwKm8:b-ncx2g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/distsql_plan_stats.go#L174)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

`rowsExpected` is used to estimate the overall progress of `CREATE STATISTICS`, which we report live as the job runs. I think this will be incorrect for `CREATE STATISTICS USING EXTREMES` in two ways: (a) this calculation assumes a full table scan, rather than a partial constrained scan, and (b) for this variant of `USING EXTREMES` a single job will consist of multiple invocations of `planAndRunCreateStats` instead of a single invocation, so this `rowsExpected` is only a portion of the total.

So for `USING EXTREMES` I have two ideas:
1. we should probably use `RowCount * overhead` instead of `RowCount * (1 + overhead)`
2. and then we should maybe either multiply this `rowsExpected` by the number of indexes we expect to scan, or maybe better: plumb a count of the number of indexes into sample_aggregator so that we can divide the reported progress here: https://github.com/cockroachdb/cockroach/blob/558771f5090b3133476da85a0becc24309ff1888/pkg/sql/rowexec/sample_aggregator.go#L268
</blockquote></details>

Good catch! We also use `rowsExpected` in our sample size calculation so changing it to `RowCount * overhead` should also give us more appropriate sample sizes for partial stats collections.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_stats` line 3365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O33iHkV48fJ4nHFfjqY:-O3mjpnu0WB2VF-hQ8hf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/logictest/testdata/logic_test/distsql_stats#L3365)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

More kinds of index to test:
* hash-sharded index like `INDEX (e) USING HASH`
* partial index like `INDEX (f) WHERE c > 5`
* expression index like `INDEX ((g + 1))`

It would also be nice to add a test with a `LOCALITY REGIONAL BY ROW` table. I can help with this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-08 17:22 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

___
*[`pkg/sql/create_stats.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34eEV-3n9Dm1wJRJEV:-O3n-hJH7l35VQswvmeX:bp16jju) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L492)):*
<details><summary><i>Previously, Uzair5162 (Uzair Ahmad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hypothetically the optimizer should be able to figure out that it needs to scan each partition using the EXTREMES filter. If we don't handle this case here, we should open a tracking issue for it.


<!-- Sent from Reviewable.io -->

2024-08-09 21:02 UTC, michae2 approved these changes
Nice work, @Uzair5162! Just one last comment, and then this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-:-O3ssNLOAOXrc8yu_Jd7:b-eehqbw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @Uzair5162)

___
*[`pkg/sql/create_stats.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34eEV-3n9Dm1wJRJEV:-O3oPPXD5yqO2i_lfHYJ:brdimdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L492)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Hypothetically the optimizer should be able to figure out that it needs to scan each partition using the EXTREMES filter. If we don't handle this case here, we should open a tracking issue for it.
</blockquote></details>

@DrewKimball, these plans don't go through the optimizer; we construct physical plans directly in https://github.com/cockroachdb/cockroach/blob/8a21ac3940ab440030467ebe2feb7abde1030145/pkg/sql/distsql_plan_stats.go#L269

I agree, we should open a GH issue about USING EXTREMES on hash-sharded indexes and RBR tables.
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 274 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O3sv3FBC4N1mfygB12l:-O3sv3FBC4N1mfygB12m:b3t4odb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f203c5a743ff989011e296660076be5fb9bb8201/pkg/sql/rowexec/sample_aggregator.go#L274)):*
> ```Go
> 						// Adjust the fraction to account for the indexes that have already
> 						// been processed.
> 						fractionCompleted = (float32(s.spec.CurIndex) + fractionCompleted) / float32(s.spec.NumIndexes)
> ```

During an upgrade, if we're using the new binary we might receive a spec with NumIndexes=0 from one of the old binaries. We should handle this case by falling back to the old fractionCompleted logic.


<!-- Sent from Reviewable.io -->

2024-08-09 23:13 UTC, Uzair5162 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127836)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/create_stats.go` line 492 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O34eEV-3n9Dm1wJRJEV:-O3tPZNN49c_u0LeQnYN:b9xwc7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1be4b6a29932ec1f305d03c84be07b8ae243da10/pkg/sql/create_stats.go#L492)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

@DrewKimball, these plans don't go through the optimizer; we construct physical plans directly in https://github.com/cockroachdb/cockroach/blob/8a21ac3940ab440030467ebe2feb7abde1030145/pkg/sql/distsql_plan_stats.go#L269

I agree, we should open a GH issue about USING EXTREMES on hash-sharded indexes and RBR tables.
</blockquote></details>

Opened: https://github.com/cockroachdb/cockroach/issues/128725
___
*[`pkg/sql/rowexec/sample_aggregator.go` line 274 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/127836#-O3sv3FBC4N1mfygB12l:-O3tMnCw5TJLEDeUNHmQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f203c5a743ff989011e296660076be5fb9bb8201/pkg/sql/rowexec/sample_aggregator.go#L274)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

During an upgrade, if we're using the new binary we might receive a spec with NumIndexes=0 from one of the old binaries. We should handle this case by falling back to the old fractionCompleted logic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-12 16:59 UTC, Uzair5162 commented
bors r+

2024-08-12 18:08 UTC, merged