schemachanger: Add notice for inbound FKs with row level TTL
cockroachdb/cockroach pull request #127935
Opened 2024-07-30 23:13 UTC by rimadeodhar

This PR adds a notice when a user attempts to add a foreign key on a table with row level TTL enabled. Additionally, it also adds a notice when we enable row level TTL on a table which has inbound foreign keys. The notice alerts the user that adding FKs on referencing a table with row level TTL can lead to inefficiencies in the TTL deletion job due to the extra work needed to also drop dependent rows.

Informs: https://github.com/cockroachdb/cockroach/issues/125103 Epic: none
Release note (sql change): Attempting to add foreign keys referencing a table with row level TTL enabled will generate a notice informing the user about potential impact on the row level TTL deletion job. Similarly, a notice is generated while attempting to enable row level TTL on a table that has inbound foreign key references.

2024-07-30 23:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/127935)
<!-- Reviewable:end -->

2024-07-31 01:44 UTC, fqazi approved these changes
Looks good, just some minor nits

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-:-O35SNQL-agy45Z0HUMO:bd0zsan)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rimadeodhar)

___
*[`pkg/sql/alter_table.go` line 2218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O35S90X6XmTyeK1d3Id:-O35S90X6XmTyeK1d3Ie:bipg6xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/alter_table.go#L2218)):*
> ```Go
> in other tables will need to be updated as well. To improve performance
> of the TTL job, consider setting the value of ttl_delete_batch_size to
> a reasonable number.`, tableDesc.GetName()))
> ```

Nit: should we say lower?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O35Rrvb-K40RGUCkxL_:-O35Rrvb-K40RGUCkxLa:b-sbtrn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L394)):*
> ```Go
> 		b.EvalCtx().ClientNoticeSender.BufferClientNotice(
> 			b,
> 			pgnotice.Newf(`
> ```

Nit: Do we want to share this message via the sqlerrors package?


<!-- Sent from Reviewable.io -->

2024-07-31 12:45 UTC, spilchen reviewed
Just had a suggestion for how we could refine the checks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-:-O37oUA0Dw5Gdvu0-kth:bp0ozo2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rimadeodhar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O37mA-Z1vuWFnPFG7Eb:-O37mA-Z1vuWFnPFG7Ec:b-qcavi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L385)):*
> ```Go
> 	}
> 
> 	// 12. Adding a foreign key dependency on a table with row-level TTL enabled can
> ```

Is it only an issue if the FK wasn't defined with `ON DELETE NO ACTION`? If that was used, any deletion for TTL should not cascade to the dependent table.


<!-- Sent from Reviewable.io -->

2024-07-31 13:46 UTC, fqazi requested changes, later dismissed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rimadeodhar, and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O37mA-Z1vuWFnPFG7Eb:-O381Sf922VR3yoBynqP:byo1x99) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L385)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is it only an issue if the FK wasn't defined with `ON DELETE NO ACTION`? If that was used, any deletion for TTL should not cascade to the dependent table.
</blockquote></details>

Also adding to this the default action is: ON DELETE NO ACTION. So, I think both checks need to be modified.


<!-- Sent from Reviewable.io -->

2024-08-01 17:17 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/alter_table.go` line 2218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O35S90X6XmTyeK1d3Id:-O3DwBpMEGlZyHJ07xax:brd96vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/alter_table.go#L2218)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: should we say lower?
</blockquote></details>

nit: let's avoid hardcoding newlines in the notice, since that isn't a standard thing we do with other errors/messages
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O35Rrvb-K40RGUCkxL_:-O3Dw6eN3lkk0E-UHDCn:b-p433ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L394)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Do we want to share this message via the sqlerrors package?
</blockquote></details>

the messages are slightly different, so i think it's fine to keep these separate


<!-- Sent from Reviewable.io -->

2024-10-11 19:22 UTC, rimadeodhar reviewed
I have updated the checks to only apply when the TTL job deletes can have a cascading impact. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-:-O8x0pJ49u0G_hOTMF0N:bnagkb3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-O37mA-Z1vuWFnPFG7Eb:-O8x0zRo7BZ6Lg2I-XDa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b69388ba314b5ba46b37c9618df6489ff6955ed4/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L385)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Also adding to this the default action is: ON DELETE NO ACTION. So, I think both checks need to be modified.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-15 20:03 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127935#-:-O9GlswqC_QDDZG3jvHG:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)



<!-- Sent from Reviewable.io -->

2024-10-16 16:06 UTC, rimadeodhar commented
TFTR!

bors r=spilchen

2024-10-16 19:06 UTC, rimadeodhar commented
Re-trying now that the blocking review has been dismissed:

bors r=spilchen

2024-10-16 20:02 UTC, merged