kvflowcontrol: introduce token counter interface
cockroachdb/cockroach pull request #128195
Opened 2024-08-02 16:35 UTC by kvoli

Introduce the `TokenCounter` interface, underneath a new `pkg`, `kvflowcontrolstream`. The `TokenCounter` will be used by replication flow control v2 in a similar, but distinct manner from the token buckets in v1. Notably, the `TokenCounter` supports returning an encapsulated handle that may be used in waiting for available tokens, `TokenWaitingHandle`.

Resolves: #128014
Release note: None

2024-08-02 16:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/128195)
<!-- Reviewable:end -->

2024-08-02 18:43 UTC, sumeerbhola requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JN6KX4exst2DiYruI:-O3JN6KX4exst2DiYruJ:bgbj3e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L20)):*
> ```Go
> )
> 
> // RangeController provides flow control for replication traffic in KV, for a
> ```

should this add:
... range, at the leader.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JLgyp8sFaEJxPmLru:-O3JLgyp8sFaEJxPmLrv:bd6l2iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L21)):*
> ```Go
> 
> // RangeController provides flow control for replication traffic in KV, for a
> // range.
> ```

Do we need to document any invariants about `raftMu` or replica `mu` being held before calling these?

I'm ok with postponing this to later. Once we have `RangeControllerOptions`, we will need to document what are the consistency invariants wrt what these methods inform it, and what it can grab from methods it can call, say on `RaftInterface`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JOLmmANKnNpPxxFr1:-O3JOLmmANKnNpPxxFr2:brgc5tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L51)):*
> ```Go
> 	// removing it from watching the existing work class, if the work class is
> 	// different.
> 	UpdateHandle(StreamWatcherHandleID, admissionpb.WorkClass)
> ```

UpdateHandle goes away since the send-queue is always `RaftLowPri`.
We also don't need the `WorkClass` parameter in `NotifyWhenAvailable`, which reduces the surface area to test.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JHdVb7XTtyPT7PM-X:-O3JHdVb7XTtyPT7PM-Y:bxs4253) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L26)):*
> ```Go
> type TokenCounter interface {
> 	// TokensAvailable returns true if tokens are available. If false, it returns
> 	// a handle that may be uses for waiting for tokens to become available.
> ```

nit: used
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3JJ5Au93eS48V989pe:b-rq7s4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
> ```Go
> 	// unsatisfied with the return values, it can resume waiting using
> 	// WaitChannel.
> 	TryDeductAndUnblockNextWaiter(tokens kvflowcontrol.Tokens) (granted kvflowcontrol.Tokens, haveTokens bool)
> ```

I think we are always calling this with a parameter value of 0.

Which makes sense in that (a) the eval case does not want to deduct tokens, (b) the `storeStreamSendTokensWatcher` (send tokens) case we delegate the deduction to `TokensAvailableNotification` since the watcher does not want to be kept up-to-date on how many tokens a `replicaSendStream` needs. In (b) we also only have at most one waiter, so there isn't any harm done by the fact that we unblock the "next waiter" before the `replicaSendStream` has deducted tokens.

We also wouldn't need this separation of `WaitChannel` and `TryDeductAndUnblockNextWaiter` if case (a) did not demand a channel, to do a select.

Overall, I think this is still the right-ish interface, but how about we change this method to
`ConfirmHaveTokensAndUnblockNextWaiter() bool`.


<!-- Sent from Reviewable.io -->

2024-08-02 19:17 UTC, andrewbaptist reviewed
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JVhj9A8UmusKiuI85:-O3JVhj9A8UmusKiuI86:biq3pgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L29)):*
> ```Go
> 	// HandleRaftEvent handles the provided raft event for the range. This should
> 	// be called while holding raftMu.
> 	HandleRaftEvent(ctx context.Context, e RaftEvent) error
> ```

nit: Consider adding `RaftMuLocked` to this and other methods. This is the typical pattern as makes auditing callers easier. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JVL7R54FEs7Kda5uY:-O3JVL7R54FEs7Kda5uZ:b-ulqgai) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L36)):*
> ```Go
> 	SetReplicas(ctx context.Context, replicas roachpb.ReplicaSet) error
> 	// SetLeaseholder sets the leaseholder of the range.
> 	SetLeaseholder(ctx context.Context, replica roachpb.ReplicaID)
> ```

nit: consider splitting the `SetReplicas` and `SetLeaseholder` methods out to a different interface. This will simplify testing. 

Also I'm assuming the reason that the implementation needs these at all is to handle changes that occur. However I'm a little concerned about the async nature of these updates and whether the "cache" in the implementation will be stale at different points in time. At a minimum define when these are called. For example for the `SetLeaseholder` is it when the proposal for the lease is received, when it is appended to the raft log, when the state is updated or when the new leaseholder applies the log. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3JTx_e3YzVzSHsWgKd:b-56ol8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we are always calling this with a parameter value of 0.

Which makes sense in that (a) the eval case does not want to deduct tokens, (b) the `storeStreamSendTokensWatcher` (send tokens) case we delegate the deduction to `TokensAvailableNotification` since the watcher does not want to be kept up-to-date on how many tokens a `replicaSendStream` needs. In (b) we also only have at most one waiter, so there isn't any harm done by the fact that we unblock the "next waiter" before the `replicaSendStream` has deducted tokens.

We also wouldn't need this separation of `WaitChannel` and `TryDeductAndUnblockNextWaiter` if case (a) did not demand a channel, to do a select.

Overall, I think this is still the right-ish interface, but how about we change this method to
`ConfirmHaveTokensAndUnblockNextWaiter() bool`.
</blockquote></details>

I agree this interface isn't ideal. It seems much nicer to have it look something like (`WaitChannel(tokens kvflowcontrol.Tokens) <- chan kvflowcontrol.Tokens`)  Is there a difference between the `TryDeduct` here and the one in `TokenCounter`? 


<!-- Sent from Reviewable.io -->

2024-08-02 19:47 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JN6KX4exst2DiYruI:-O3JcTIv6tH98oZMKMwK:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L20)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this add:
... range, at the leader.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JLgyp8sFaEJxPmLru:-O3JYVkC6-dMwfZn9gsC:bxep2as) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L21)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need to document any invariants about `raftMu` or replica `mu` being held before calling these?

I'm ok with postponing this to later. Once we have `RangeControllerOptions`, we will need to document what are the consistency invariants wrt what these methods inform it, and what it can grab from methods it can call, say on `RaftInterface`.
</blockquote></details>

I was going to postpone until later, however given the rename of methods to include locked, I added it for each now.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JVhj9A8UmusKiuI85:-O3J_JTl7fYzq6lCAKSV:by6rfuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L29)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Consider adding `RaftMuLocked` to this and other methods. This is the typical pattern as makes auditing callers easier.
</blockquote></details>

Good idea, updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JVL7R54FEs7Kda5uY:-O3J_VcpBw5ErAzrN5nP:b-7tzr7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L36)):*
> Also I'm assuming the reason that the implementation needs these at all is to handle changes that occur

Naturally, the leaseholder and replica set can change.

> However I'm a little concerned about the async nature of these updates and whether the "cache" in the implementation will be stale at different points in time.

These aren't async, they are synchronous w.r.t the caller. The leaseholder is fine to be eventually consistent, the replica set won't be, see below.

> At a minimum define when these are called. For example for the `SetLeaseholder` is it when the proposal for the lease is received, when it is appended to the raft log, when the state is updated or when the new leaseholder applies the log.

I'd prefer to leave that to the caller implementation to specify, given these are interfaces. The replica set change follows a well established pattern so I won't comment on that. For the leaseholder, its harmless for it to be eventually consistent and is handled under raft ready, prior to calling the controller with entries.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JOLmmANKnNpPxxFr1:-O3JVtRS8TrOY8I7VwKi:bv4n6i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L51)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

UpdateHandle goes away since the send-queue is always `RaftLowPri`.
We also don't need the `WorkClass` parameter in `NotifyWhenAvailable`, which reduces the surface area to test.
</blockquote></details>

Ack, I was thinking this was the case. Updated. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JHdVb7XTtyPT7PM-X:-O3JW6fnDRN_U-HLf1yz:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: used
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3JWPf34kemes_WbpN6:brsk9rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
We are always calling with a parameter of 0 in the prototype. Updated to `ConfirmHaveTokensAndUnblockNextWaiter() bool`.

> I agree this interface isn't ideal. It seems much nicer to have it look something like (`WaitChannel(tokens kvflowcontrol.Tokens) <- chan kvflowcontrol.Tokens`) Is there a difference between the `TryDeduct` here and the one in `TokenCounter`?

They are different, this method is signaling the next caller waiting on tokens, trying to deduct tokens and returning whether there were any tokens.  TryDeduct is simply deducting tokens. Since we removed the deduction part, this method is for checking positive tokens and signaling.  


<!-- Sent from Reviewable.io -->

2024-08-02 20:30 UTC, andrewbaptist reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 36 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JVL7R54FEs7Kda5uY:-O3Jj21R1OEo1ST2bTcC:brrr1ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L36)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Also I'm assuming the reason that the implementation needs these at all is to handle changes that occur

Naturally, the leaseholder and replica set can change.

> However I'm a little concerned about the async nature of these updates and whether the "cache" in the implementation will be stale at different points in time.

These aren't async, they are synchronous w.r.t the caller. The leaseholder is fine to be eventually consistent, the replica set won't be, see below.

> At a minimum define when these are called. For example for the `SetLeaseholder` is it when the proposal for the lease is received, when it is appended to the raft log, when the state is updated or when the new leaseholder applies the log.

I'd prefer to leave that to the caller implementation to specify, given these are interfaces. The replica set change follows a well established pattern so I won't comment on that. For the leaseholder, its harmless for it to be eventually consistent and is handled under raft ready, prior to calling the controller with entries.
</blockquote></details>

That's reasonable - thanks for the clarification! 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JjMxADs6sGCcTTmqc:-O3JjMxADs6sGCcTTmqd:b-by1rx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0149f9274845eee00b7af92c46597df5af08e867/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L28)):*
> ```Go
> 	//
> 	// No mutexes should be held.
> 	WaitForEval(ctx context.Context, pri admissionpb.WorkPriority) error
> ```

nit: The comment say "until there are enough tokens", but there is no token count passed to this. Is it waiting until the token count is positive?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JizLI5c26Hze2sAM-:-O3JizLI5c26Hze2sAM0:bfgsyjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0149f9274845eee00b7af92c46597df5af08e867/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L41)):*
> ```Go
> 	//
> 	// Requires replica.raftMu and replica.mu to be held.
> 	SetReplicasLocked(ctx context.Context, replicas roachpb.ReplicaSet) error
> ```

nit: Update the name of this method as well.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3Jlv1J4uJurHJIMzaa:b-s0ae91) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

We are always calling with a parameter of 0 in the prototype. Updated to `ConfirmHaveTokensAndUnblockNextWaiter() bool`.

> I agree this interface isn't ideal. It seems much nicer to have it look something like (`WaitChannel(tokens kvflowcontrol.Tokens) <- chan kvflowcontrol.Tokens`) Is there a difference between the `TryDeduct` here and the one in `TokenCounter`?

They are different, this method is signaling the next caller waiting on tokens, trying to deduct tokens and returning whether there were any tokens.  TryDeduct is simply deducting tokens. Since we removed the deduction part, this method is for checking positive tokens and signaling.
</blockquote></details>

Can you clarify in the comment what the "possibly available" means. Are there spurious wake-ups or is it because you are racing with other waiters who might grab the tokens before you call `Confirm`. 

Also the interface is still a little clunky. I'm probably missing some context, however it seems like you could have it be:

`WaitChannel() <-chan bool` with the bool signifying whether there were tokens available. 

My understanding of how its used is something like this:
```
for {
	select {
	case <-handle.WaitChannel():
		if handle.ConfirmHaveTokensAndUnblockNextWaiter() {
			// Do something
		}
	}
}
```

Wouldn't this be easier if it returned a bool and you could just write
```
for {
	select {
	case ready := <-handle.WaitChannel():
		if ready {
			// Do something
		}
	}
}
```


<!-- Sent from Reviewable.io -->

2024-08-02 20:52 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 28 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JjMxADs6sGCcTTmqc:-O3Jnznx2R-RR9JnCqXD:bmtoulx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0149f9274845eee00b7af92c46597df5af08e867/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L28)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: The comment say "until there are enough tokens", but there is no token count passed to this. Is it waiting until the token count is positive?
</blockquote></details>

It is waiting for positive, nice catch. I've updated the comment to make this clear.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JizLI5c26Hze2sAM-:-O3JolV8BiqeKOApNVpk:banhge5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0149f9274845eee00b7af92c46597df5af08e867/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L41)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Update the name of this method as well.
</blockquote></details>

This requires both raft mu and replica mu, so I went with `Locked`, as opposed to `RaftMuLockedReplicaLocked` or similar.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3JpB5P8NFT7dhih2Va:b-i782o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
> Can you clarify in the comment what the "possibly available" means. Are there spurious wake-ups or is it because you are racing with other waiters who might grab the tokens before you call `Confirm`.


We hold the mutex when signaling the the channel but that mutex needs to be dropped before the signaler returns. Another request can race to deduct tokens in-between signaling and the signaled goroutine being awoken, as the channel is buffered and non-blocking.

See [this comment](https://github.com/sumeerbhola/cockroach/blob/2064b279e95bbd68b0a7898503168d384cd0158c/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/token_counter.go#L59-L97) in the prototype for more details, along with usages of the signalCh. 

> Wouldn't this be easier if it returned a bool and you could just write

The channel is only ever being signaled when **there are positive tokens**,  the second example is a subset of the first. 


<!-- Sent from Reviewable.io -->

2024-08-02 21:48 UTC, sumeerbhola requested changes
looks good. Only some remaining questions about locking.

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-:-O3K3A6s9pnSe3DYSh6R:b7t7mv3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JzRUB9aVPQ0R0Tfms:-O3JzRUB9aVPQ0R0Tfmt:b-ixbhk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de9b39199ac5392c64f927439bb80d7810a49d6/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L26)):*
> ```Go
> 	// This blocks until there are positive tokens available for the request to
> 	// be admitted for evaluation. Note the number of tokens required by the
> 	// request is not considered, only the priority of the request.
> ```

consider adding a parenthetical remark:
(since it is it not known until after eval)
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3K-GdE4nk510-UqApa:-O3K-GdE4nk510-UqApb:bvy3dvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de9b39199ac5392c64f927439bb80d7810a49d6/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L33)):*
> ```Go
> 	//
> 	// Requires replica.raftMu to be held.
> 	HandleRaftEventRaftMuLocked(ctx context.Context, e RaftEvent) error
> ```

There is a pathway from `handleReadyState` to `newReplicaSendStream` to `NextUnstableIndexRLocked`. So is this also holding replica mu, or is there a bug in the prototype?
Remembering the discussion from https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1721137761404479, I think we needed to ensure replica mu was held for methods called on Raft that mutated raft state, since metrics etc. could call read-only methods while holding replica mu in read mode. So it would make sense that calling `RawNode.NextUnstableIndex` without holding replica mu is harmless (since it does not mutate state). Which makes me wonder why we even have `raftInterfaceImpl.NextUnstableIndex` which acquires replica mu. Am I missing something?

Similar question about `StableIndexRLocked` and `GetAdmittedRLocked`.

Are SetAdmittedLocked and MakeMsgApp the only Raft state mutators we use in RACv2? The former is not even needed by the core code, since only the integration calls it. Then we only need to be careful in the code code in ensuring that we are only calling MakeMsgApp along paths that hold raftMu but do not hold replica mu. Does that sound correct-ish?


<!-- Sent from Reviewable.io -->

2024-08-05 14:33 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 26 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JzRUB9aVPQ0R0Tfms:-O3XmmZI61IdiBNrpSeD:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de9b39199ac5392c64f927439bb80d7810a49d6/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L26)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

consider adding a parenthetical remark:
(since it is it not known until after eval)
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 33 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3K-GdE4nk510-UqApa:-O3Xj01g2Sy1zNFi6YiM:btfx64f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de9b39199ac5392c64f927439bb80d7810a49d6/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L33)):*
> Which makes me wonder why we even have `raftInterfaceImpl.NextUnstableIndex` which acquires replica mu. Am I missing something? Similar question about `StableIndexRLocked` and `GetAdmittedRLocked`.

`FollowerState()` at least requires a read lock on the replica, as there are some mutation methods, such as appending entries when flushing the proposal buffer, which don't acquire raftMu but do acquire an exclusive lock on `replica.mu`. 

> Are SetAdmittedLocked and MakeMsgApp the only Raft state mutators we use in RACv2? 

Yes, these are the only methods which mutate raft state.


<!-- Sent from Reviewable.io -->

2024-08-05 16:47 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YPDLfDN_x7SjwRcDx:-O3YPDLfDN_x7SjwRcDy:bnf5msl) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L21)):*
> ```Go
> // StreamTokenCounterProvider is the interface for retrieving token counters
> // for a given stream.
> type StreamTokenCounterProvider interface {
> ```

Code structure question: why is this hierarchy of interfaces needed, instead of a collection of concrete types? Is this code going to be extensively mocked?

This has a Java interface-heavy feel, and I'm just wondering how much this is needed. It's not obvious from structuring the work like this - interfaces first. Maybe having implementations first, and adding interfaces when needed (e.g. the moment you need to mock them) would make this need more obvious.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YNLtM4qFaQTqh4VlE:-O3YNLtM4qFaQTqh4VlF:b-1g5ppx) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L24)):*
> ```Go
> 	// EvalTokenCounterForStream returns the evaluation token counter for the
> 	// given stream.
> 	EvalTokenCounterForStream(kvflowcontrol.Stream) TokenCounter
> ```

Go naming minimalizm nit: the `TokenCounter` return type eliminates the need to have "TokenCounter" in the method name. "ForStream" kinda as well, given the parameter is a `Stream` as well as the interface name has it, and there are no other methods taking something other than a stream. So the pair of methods could be just `Eval(Stream) TokenCounter`, `Send(Stream) TokenCounter`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YM0vl-tXbFyve4r7b:-O3YM0vl-tXbFyve4r7c:batsyp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L35)):*
> ```Go
> 
> // StreamTokenWatcher is the interface for watching and waiting on available
> // elastic tokens. The watcher registers a notification, which will be called
> ```

Why only elastic? Is this to do with the fact that send-queue always waits/uses elastic tokens? Could be worth noting it in the comments.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YMOgZ1EdZ_XJe4LML:-O3YMOgZ1EdZ_XJe4LMM:bqg0aet) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L54)):*
> ```Go
> // TokenGrantNotification is an interface for notifying when tokens are
> // available.
> type TokenGrantNotification interface {
> ```

How about a `func(context.Context)` callback in the interface above, to avoid the interface boilerplate?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3YQhzc1YIbv8vQ0He2:bmkkdx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Can you clarify in the comment what the "possibly available" means. Are there spurious wake-ups or is it because you are racing with other waiters who might grab the tokens before you call `Confirm`.


We hold the mutex when signaling the the channel but that mutex needs to be dropped before the signaler returns. Another request can race to deduct tokens in-between signaling and the signaled goroutine being awoken, as the channel is buffered and non-blocking.

See [this comment](https://github.com/sumeerbhola/cockroach/blob/2064b279e95bbd68b0a7898503168d384cd0158c/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/token_counter.go#L59-L97) in the prototype for more details, along with usages of the signalCh. 

> Wouldn't this be easier if it returned a bool and you could just write

The channel is only ever being signaled when **there are positive tokens**,  the second example is a subset of the first.
</blockquote></details>

Are we basically implementing a cond-var loop here? And the reason we're using a channel is make the waits cancelable?
Or there is more to this particular structuring?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YITGIAADZfS1ouQBk:-O3YITGIAADZfS1ouQBl:b4jpixl) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L24)):*
> ```Go
> // tokens to become available, and to check if tokens are available without
> // blocking.
> type TokenCounter interface {
> ```

Why do we need this interface? Could we use its implementation directly, or we need a second implementation (e.g. for mocking in tests)? Could we introduce the interface when it's needed for the second implementation if there is one?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YFjbJ4V_p5PMi7Agg:-O3YFjbJ4V_p5PMi7Agh:bexbpn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
> ```Go
> 	// TokensAvailable returns true if tokens are available. If false, it returns
> 	// a handle that may be used for waiting for tokens to become available.
> 	TokensAvailable(admissionpb.WorkClass) (available bool, tokenWaitingHandle TokenWaitingHandle)
> ```

Any reason to have `WorkClass` part of the methods, instead of having a couple of `TokenCounter`s (one per priority)? Does the implementation have any cross-work-class logic (such as deduct lower-pri tokens while also deducting high-pri tokens), or is simply a union of per-class logic and the cross-class logic sits above the interface?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YGfWt8qrsxaVLFTFs:-O3YGfWt8qrsxaVLFTFt:bh4wteq) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
> ```Go
> 	// TokensAvailable returns true if tokens are available. If false, it returns
> 	// a handle that may be used for waiting for tokens to become available.
> 	TokensAvailable(admissionpb.WorkClass) (available bool, tokenWaitingHandle TokenWaitingHandle)
> ```

Any reason not to have 2 separate methods: `TokensAvailable() bool` (or `TokensAvailable() kvflowcontrol.Tokens`), and `GetHandle()`? Optimization purposes?


<!-- Sent from Reviewable.io -->

2024-08-05 17:12 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YPDLfDN_x7SjwRcDx:-O3YVudq3ER68pMkzrOQ:bumw6qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L21)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Code structure question: why is this hierarchy of interfaces needed, instead of a collection of concrete types? Is this code going to be extensively mocked?

This has a Java interface-heavy feel, and I'm just wondering how much this is needed. It's not obvious from structuring the work like this - interfaces first. Maybe having implementations first, and adding interfaces when needed (e.g. the moment you need to mock them) would make this need more obvious.
</blockquote></details>

Would you be satisfied with a TODO to remove interfaces if/when they are determined not necessary for unit testing.

I would like to avoid getting bogged down in a debate at this stage -- some of the interface-heaviness in the prototype was to allow concurrency of implementation, to have a negotiated contract, and we do want to retain some of that concurrency in this phase of the project.


<!-- Sent from Reviewable.io -->

2024-08-05 17:20 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YPDLfDN_x7SjwRcDx:-O3YSdYS7Ts7BGhAr88w:b7c7e1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L21)):*
This is pretty much verbatim copied from the prototype. I agree this could just be a concrete type, these didn't get heavily mocked in the earlier testing we had.

> Maybe having implementations first, and adding interfaces when needed (e.g. the moment you need to mock them) would make this need more obvious.

That said, there is some benefit to defining ifaces for certain components first, to enable work parallelism. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YNLtM4qFaQTqh4VlE:-O3YTNsK8u8pfmGTjxVD:bjqmu5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L24)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Go naming minimalizm nit: the `TokenCounter` return type eliminates the need to have "TokenCounter" in the method name. "ForStream" kinda as well, given the parameter is a `Stream` as well as the interface name has it, and there are no other methods taking something other than a stream. So the pair of methods could be just `Eval(Stream) TokenCounter`, `Send(Stream) TokenCounter`.
</blockquote></details>

Good idea, updated to just eval/send. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YM0vl-tXbFyve4r7b:-O3YTtkI3_VjQJzLG5Cv:b-6i76o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L35)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Why only elastic? Is this to do with the fact that send-queue always waits/uses elastic tokens? Could be worth noting it in the comments.
</blockquote></details>

Yes, however the structure is slightly more general to allow for any stream (send/eval), just deducting elastic specifically.  I've added a comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YMOgZ1EdZ_XJe4LML:-O3YUgnzBIR_YD0om5rB:be3ponn) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L54)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

How about a `func(context.Context)` callback in the interface above, to avoid the interface boilerplate?
</blockquote></details>

Sure, either is fine, the boilerplate isn't that egregious. I've updated to a func.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3YXLHYCjQj-mQv4xAP:byavunq) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Are we basically implementing a cond-var loop here? And the reason we're using a channel is make the waits cancelable?
Or there is more to this particular structuring?
</blockquote></details>

Fairly similar to a cond-var loop. The channel is returned because we may wish to wait on multiple such channels (for eval), instead of blocking return here. See the link above for details on usage in the prototype.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YITGIAADZfS1ouQBk:-O3YWcr85LX8WXZNtnQA:bs3rz99) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L24)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Why do we need this interface? Could we use its implementation directly, or we need a second implementation (e.g. for mocking in tests)? Could we introduce the interface when it's needed for the second implementation if there is one?
</blockquote></details>

This one is for testing, we could introduce it when testing, later but materially we use the iface below here, so it makes sense to include both at once.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YFjbJ4V_p5PMi7Agg:-O3YWLlG2JB2J6R4V_iB:bnao66m) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Any reason to have `WorkClass` part of the methods, instead of having a couple of `TokenCounter`s (one per priority)? Does the implementation have any cross-work-class logic (such as deduct lower-pri tokens while also deducting high-pri tokens), or is simply a union of per-class logic and the cross-class logic sits above the interface?
</blockquote></details>

They do have cross-work logic. Regular tokens deduct from both elastic and regular.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YGfWt8qrsxaVLFTFs:-O3YWnEa3EkGKtvaqDes:bv5nflq) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Any reason not to have 2 separate methods: `TokensAvailable() bool` (or `TokensAvailable() kvflowcontrol.Tokens`), and `GetHandle()`? Optimization purposes?
</blockquote></details>

TryDeduct is used for that purpose mostly. We could update this method to just return a handle or nil but the current approach is fairly clear.


<!-- Sent from Reviewable.io -->

2024-08-05 18:01 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 21 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YPDLfDN_x7SjwRcDx:-O3YaaUi3uLwUEgIr_mR:b-nzh41n) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L21)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This is pretty much verbatim copied from the prototype. I agree this could just be a concrete type, these didn't get heavily mocked in the earlier testing we had.

> Maybe having implementations first, and adding interfaces when needed (e.g. the moment you need to mock them) would make this need more obvious.

That said, there is some benefit to defining ifaces for certain components first, to enable work parallelism.
</blockquote></details>

A TODO to de-interface is fine. Interfaces have a non-zero cost (the indirection, no inlining, extra allocations in some cases), so it would be nice to get rid of them if they aren't actually end up needed.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3YdjZ3B942bcxtzPHY:b-m30xvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Fairly similar to a cond-var loop. The channel is returned because we may wish to wait on multiple such channels (for eval), instead of blocking return here. See the link above for details on usage in the prototype.
</blockquote></details>

Could be worth adding a typical usage in the interface comment, akin to what Andrew wrote above.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YFjbJ4V_p5PMi7Agg:-O3Y_YnC-vzJ-Ty7NKRM:b4xl2d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

They do have cross-work logic. Regular tokens deduct from both elastic and regular.
</blockquote></details>

Is this cross-class logic worth documenting (e.g. in the interface comment, to avoid duplicating it in all methods)? Or it's completely transparent and the caller/user doesn't need to be aware of it?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YeW5RDtYDrh2_tVCq:-O3YeW5RDtYDrh2_tVCr:brpy0vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L46)):*
> ```Go
> type TokenWaitingHandle interface {
> 	// WaitChannel is the channel that will be signaled if tokens are possibly
> 	// available. If signaled, the caller must call
> ```

Are we aiming to serialize all token waits / wake-ups through this channel / pattern?

Seemingly, there can be a race when multiple goroutines are woken up:
1. One g reads a signal from `WaitChannel`.
2. Token counter is updated, and signals the `WaitChannel` again.
3. Another g reads from `WaitChannel`.
4. Steps 2-3 repeated K times.
5. Now K+2 goroutines are racing for the tokens with the "confirm" method.

Is this race considered ok, or should the signal be "owned" by the first g exclusively until it calls the "confirm" method?

Would be worth clarifying the semantics we want to guarantee here.


<!-- Sent from Reviewable.io -->

2024-08-05 18:49 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YM0vl-tXbFyve4r7b:-O3YnYOb4SpoasOPROtk:b-ndcky6) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L35)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Yes, however the structure is slightly more general to allow for any stream (send/eval), just deducting elastic specifically.  I've added a comment.
</blockquote></details>

Would this be needed to wait for eval, or it's only for send tokens? (used only by send-queue)

If it's only send tokens, consider renaming to `SendTokenWatcher` (or `ElasticSendTokenWatcher` although that's maybe too verbose).

There is a bit of a conflict between generality and concreteness here. If we only use this for elastic send tokens, then the generality (supporting non-elastic / non-send tokens) is considered harmful / potential footgun.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 40 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YmtnS3GLU6-EaZcSR:-O3YmtnS3GLU6-EaZcSS:b-tkxbh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L40)):*
> ```Go
> 	// counter. When elastic tokens are available, the provided
> 	// TokenGrantNotification is called. It is the caller's responsibility to
> 	// call CancelHandle when tokens are no longer needed, or when the caller is
> ```

Could you expand what the "caller is done" means? Is it different from "tokens are no longer needed"? Does it assume the callback has been called (so "done" is the lifetime of this watch/wait)?

Is `CancelHandle` needed to be called from within the `TokenGrantNotification` callback (I assume no)?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3Yodyk3EIkUXNHHiC-:bne3ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
> ```Go
> 	// call CancelHandle when tokens are no longer needed, or when the caller is
> 	// done.
> 	NotifyWhenAvailable(
> ```

Consider doubling-down on the "elastic only" aspect, and naming this method accordingly. E.g.: `WatchElastic`. I'm assuming the implementation will call the `TokenCounter` methods with elastic work-class (according to comments), so better make it explicit?

Alternatively, if you want to have generality (like you indicated in another comment above) you could omit saying in the comments that it waits for elastic tokens specifically, and leave this as a type implementation detail. Could put an "example" in the comment saying that we will use it only for one combination (send+elastic).
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Yp_Rx-4xvHi2MVDwK:bigqtvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
> ```Go
> 	// done.
> 	NotifyWhenAvailable(
> 		TokenCounter,
> ```

What's the cardinality relation between `StreamTokenWatcher` and `TokenCounter`? Is it 1:1, 1:many, etc?

Just wondering whether `TokenCounter` needs to be an explicit parameter here, or can be hidden inside the implementation (e.g. upon init of this type).
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yo-mxB8z1jhOjCxYK:-O3Yo-mxB8z1jhOjCxYL:b-js9ugu) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L48)):*
> ```Go
> 	// CancelHandle cancels the given handle, stopping it from being notified
> 	// when tokens are available.
> 	CancelHandle(StreamWatcherHandleID)
> ```

Can there be a race in which the callback is invoked, and `CancelHandle` arrives after? Is this fine? Could be worth documenting this case, e.g. saying that `CancelHandle` is idempotent / no-op if already notified.


<!-- Sent from Reviewable.io -->

2024-08-05 19:10 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YM0vl-tXbFyve4r7b:-O3Yvl0KA4rt4CO1F1Yb:b-pf2lqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L35)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Would this be needed to wait for eval, or it's only for send tokens? (used only by send-queue)

If it's only send tokens, consider renaming to `SendTokenWatcher` (or `ElasticSendTokenWatcher` although that's maybe too verbose).

There is a bit of a conflict between generality and concreteness here. If we only use this for elastic send tokens, then the generality (supporting non-elastic / non-send tokens) is considered harmful / potential footgun.
</blockquote></details>

I've renamed to `SendTokenWatcher` and also updated `NotifyWhenAvailable` to take in a stream instead of a token counter. The watcher will now need to be initialized with a token counter provider, but this does make it clearer that its only watching for send tokens.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 40 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YmtnS3GLU6-EaZcSR:-O3YuZPJ7VAvrRqoePdY:bw9qstg) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L40)):*
> Could you expand what the "caller is done" means? Is it different from "tokens are no longer needed"? Does it assume the callback has been called (so "done" is the lifetime of this watch/wait)?

The stream could be closed for various reasons, in which case we don't require tokens. The caller could also be done because its been granted the tokens it requires.

> Does it assume the callback has been called (so "done" is the lifetime of this watch/wait)? [...]  Is `CancelHandle` needed to be called from within the `TokenGrantNotification` callback (I assume no)?

No. The callback can be concurrent with cancellation and doesn't require it to be called.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3Yw9THEpgsaZR6Bjaz:bgd2p92) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Consider doubling-down on the "elastic only" aspect, and naming this method accordingly. E.g.: `WatchElastic`. I'm assuming the implementation will call the `TokenCounter` methods with elastic work-class (according to comments), so better make it explicit?

Alternatively, if you want to have generality (like you indicated in another comment above) you could omit saying in the comments that it waits for elastic tokens specifically, and leave this as a type implementation detail. Could put an "example" in the comment saying that we will use it only for one combination (send+elastic).
</blockquote></details>

See the other comment, I've updated to pass in a stream instead of the counter. The elastic distinction for send queueing is somewhat clearer now, so I don't think its necessary to also include it in the method naming, if the iface references `Send`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Yt5D1-I6oD9fzqLsU:b13wmtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

What's the cardinality relation between `StreamTokenWatcher` and `TokenCounter`? Is it 1:1, 1:many, etc?

Just wondering whether `TokenCounter` needs to be an explicit parameter here, or can be hidden inside the implementation (e.g. upon init of this type).
</blockquote></details>

StreamTokenWatcher is one per node. We could nest the provider inside if we wish, in order to pull out the elastic token counter for the relevant stream.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yo-mxB8z1jhOjCxYK:-O3YtZAmBQRQS5HGXEHm:bv6vqls) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L48)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Can there be a race in which the callback is invoked, and `CancelHandle` arrives after? Is this fine? Could be worth documenting this case, e.g. saying that `CancelHandle` is idempotent / no-op if already notified.
</blockquote></details>

The race is fine and yes it could occur. CancelHandle can be called at any time, at most once. Notify would continue to be called until CancelHandle is. I've added a comment about at most once calling. It could also be made idempotent if we wish but it wasn't necessary in practice and also caught some bugs by panic'ing instead.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3JJ5Au93eS48V989pd:-O3YrqfX1GdaSBpJUEP2:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a5d2e3eb1e073cff6cc3208ae6f0ac14dbd551/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L58)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Could be worth adding a typical usage in the interface comment, akin to what Andrew wrote above.
</blockquote></details>

Added.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 27 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YFjbJ4V_p5PMi7Agg:-O3YpHj_E1qR-GQA_9zk:b-vwx4ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L27)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Is this cross-class logic worth documenting (e.g. in the interface comment, to avoid duplicating it in all methods)? Or it's completely transparent and the caller/user doesn't need to be aware of it?
</blockquote></details>

Its completely transparent, the caller doesn't need to be aware, like in v1.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 46 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YeW5RDtYDrh2_tVCq:-O3YpUbB-ftDlW7NcMFW:b-7dzuub) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L46)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Are we aiming to serialize all token waits / wake-ups through this channel / pattern?

Seemingly, there can be a race when multiple goroutines are woken up:
1. One g reads a signal from `WaitChannel`.
2. Token counter is updated, and signals the `WaitChannel` again.
3. Another g reads from `WaitChannel`.
4. Steps 2-3 repeated K times.
5. Now K+2 goroutines are racing for the tokens with the "confirm" method.

Is this race considered ok, or should the signal be "owned" by the first g exclusively until it calls the "confirm" method?

Would be worth clarifying the semantics we want to guarantee here.
</blockquote></details>

The race is considered okay. The race you mention would happen when there  [...]

2024-08-05 19:29 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 35 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3YM0vl-tXbFyve4r7b:-O3Z-fDT5taFpYwH-iyJ:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/44b3f1a98310317779c23b4defdffd26bfd33401/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L35)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I've renamed to `SendTokenWatcher` and also updated `NotifyWhenAvailable` to take in a stream instead of a token counter. The watcher will now need to be initialized with a token counter provider, but this does make it clearer that its only watching for send tokens.
</blockquote></details>

SGTM.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yo-mxB8z1jhOjCxYK:-O3YyBptBheq5E7G_b3K:b-slz73l) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L48)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The race is fine and yes it could occur. CancelHandle can be called at any time, at most once. Notify would continue to be called until CancelHandle is. I've added a comment about at most once calling. It could also be made idempotent if we wish but it wasn't necessary in practice and also caught some bugs by panic'ing instead.
</blockquote></details>

Is the "at most once" asserted by means of checking that this "watch" no longer exists? If so, wouldn't the race between a callback and cancel be problematic and lead to a panic (the callback is invoked and removes the watch; then the watch is canceled but not found)? Unless we restrict that cancel can only be called if the wait callback hasn't been called, which means there should be synchronization between the callback and the cancel call? Do we have this synchronization on the caller?

I.e. do we need to specify this contract more precicely: `CancelHandle` must be called at most once, and must not be called if `TokenGrantNotification` was invoked. Alternatively to this stricter contract, idempotency would smooth out this race automatically.

Also, are there cases when `CancelHandle` **must** be called? I.e. should we say that the cancel must be eventually called (exactly once) if the callback was not triggered? Or it's not harmful to leave the watch dangling?


<!-- Sent from Reviewable.io -->

2024-08-05 19:45 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yo-mxB8z1jhOjCxYK:-O3Z2sHw7XqXBcEPLn4R:b963095) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L48)):*
> Is the "at most once" asserted by means of checking that this "watch" no longer exists? If so, wouldn't the race between a callback and cancel be problematic and lead to a panic (the callback is invoked and removes the watch; then the watch is canceled but not found)? Unless we restrict that cancel can only be called if the wait callback hasn't been called, which means there should be synchronization between the callback and the cancel call? Do we have this synchronization on the caller?

The synchronization is in the caller. In the prototype, the replica send stream mutex was acquired to check on the watcher handle among other things.

> I.e. do we need to specify this contract more precicely: `CancelHandle` must be called at most once, and must not be called if `TokenGrantNotification` was invoked. Alternatively to this stricter contract, idempotency would smooth out this race automatically.

It doesn't matter if TokenGrantNotification was invoked or not but CancelHandle must be called at most once. This is getting pretty far into the weeds of a contract which could very well change upon implementation, we can make it idempotent if we really want, but that decision is probably best left up to the implementer of the watcher.

> Also, are there cases when `CancelHandle` **must** be called? I.e. should we say that the cancel must be eventually called (exactly once) if the callback was not triggered? Or it's not harmful to leave the watch dangling?

No, it doesn't have to be called if the callback was not triggered. Its as harmful as leaving the any other goroutine dangling on a select, just some overhead.


<!-- Sent from Reviewable.io -->

2024-08-05 19:46 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 48 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yo-mxB8z1jhOjCxYK:-O3Z4-p2EYYCAMG7fKdT:b-pmctwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L48)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> Is the "at most once" asserted by means of checking that this "watch" no longer exists? If so, wouldn't the race between a callback and cancel be problematic and lead to a panic (the callback is invoked and removes the watch; then the watch is canceled but not found)? Unless we restrict that cancel can only be called if the wait callback hasn't been called, which means there should be synchronization between the callback and the cancel call? Do we have this synchronization on the caller?

The synchronization is in the caller. In the prototype, the replica send stream mutex was acquired to check on the watcher handle among other things.

> I.e. do we need to specify this contract more precicely: `CancelHandle` must be called at most once, and must not be called if `TokenGrantNotification` was invoked. Alternatively to this stricter contract, idempotency would smooth out this race automatically.

It doesn't matter if TokenGrantNotification was invoked or not but CancelHandle must be called at most once. This is getting pretty far into the weeds of a contract which could very well change upon implementation, we can make it idempotent if we really want, but that decision is probably best left up to the implementer of the watcher.

> Also, are there cases when `CancelHandle` **must** be called? I.e. should we say that the cancel must be eventually called (exactly once) if the callback was not triggered? Or it's not harmful to leave the watch dangling?

No, it doesn't have to be called if the callback was not triggered. Its as harmful as leaving the any other goroutine dangling on a select, just some overhead.
</blockquote></details>

Also see:

https://github.com/sumeerbhola/cockroach/blob/5c2a50ec4d0dcf2502d742ac9036d39995886abc/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/stream.go#L2154-L2161

For how the race is handled.


<!-- Sent from Reviewable.io -->

2024-08-05 19:54 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Z2Pa0CLL-JeTyzrUY:b-qtnpao) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

StreamTokenWatcher is one per node. We could nest the provider inside if we wish, in order to pull out the elastic token counter for the relevant stream.
</blockquote></details>

Right, so now the `StreamTokenWatcher` sort of [multiplexes](https://github.com/cockroachdb/cockroach/blob/7674c5924b67083d4393927f6a87cf603f663ade/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/store_stream.go#L253) across all per-stream `TokenCounter`s, it's 1-to-many. I wonder though if there is benefit in making the watcher per-stream, so that it's 1-to-1.

In the prototype, most of the logic is implemented in the `tokenWatcher` sub-type, and `storeStreamSendTokensWatcher` is basically just a container for many of them. So my question is: should this interface mirror the `tokenWatcher` instead of `storeStreamSendTokensWatcher`? And then the `Stream` would have a `StreamTokenWatcher` returned by some `stream.GetSendWatcher()`. This would make the `map` searches on every watch call unnecessary.

Are there some benefits of making the `StreamTokenWatcher` a singleton?


<!-- Sent from Reviewable.io -->

2024-08-05 20:02 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Z7UtYB5D_nKL9ek8q:bc9c01k) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Right, so now the `StreamTokenWatcher` sort of [multiplexes](https://github.com/cockroachdb/cockroach/blob/7674c5924b67083d4393927f6a87cf603f663ade/pkg/kv/kvserver/kvflowcontrol/kvflowconnectedstream/store_stream.go#L253) across all per-stream `TokenCounter`s, it's 1-to-many. I wonder though if there is benefit in making the watcher per-stream, so that it's 1-to-1.

In the prototype, most of the logic is implemented in the `tokenWatcher` sub-type, and `storeStreamSendTokensWatcher` is basically just a container for many of them. So my question is: should this interface mirror the `tokenWatcher` instead of `storeStreamSendTokensWatcher`? And then the `Stream` would have a `StreamTokenWatcher` returned by some `stream.GetSendWatcher()`. This would make the `map` searches on every watch call unnecessary.

Are there some benefits of making the `StreamTokenWatcher` a singleton?
</blockquote></details>

I guess the benefit is the `watchTokens` goroutine? Having one per stream would be an overkill?


<!-- Sent from Reviewable.io -->

2024-08-05 20:16 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Z6wxy2b2nUxoChfvA:b-zhn7au) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
> So my question is: should this interface mirror the `tokenWatcher` instead of `storeStreamSendTokensWatcher`? And then the `Stream` would have a `StreamTokenWatcher` returned by some `stream.GetSendWatcher()`. This would make the `map` searches on every watch call unnecessary.

It could, that'd be a reasonable change to make here, we would include a `SendTokenWatcher` provider in the range controller init options and use it when initializing a replica send stream. I've updated the code to reflect this.

> I guess the benefit is the `watchTokens` goroutine? Having one per stream would be an overkill?

The prototype used 1 goroutine per-stream (and work class, but now its all elastic). Having one per-stream is still probably the direction we should go, assuming these are shared across all ranges on the node.


<!-- Sent from Reviewable.io -->

2024-08-05 20:17 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3Z9CUu1qhUCvJhGaov:b-m68zr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

> So my question is: should this interface mirror the `tokenWatcher` instead of `storeStreamSendTokensWatcher`? And then the `Stream` would have a `StreamTokenWatcher` returned by some `stream.GetSendWatcher()`. This would make the `map` searches on every watch call unnecessary.

It could, that'd be a reasonable change to make here, we would include a `SendTokenWatcher` provider in the range controller init options and use it when initializing a replica send stream. I've updated the code to reflect this.

> I guess the benefit is the `watchTokens` goroutine? Having one per stream would be an overkill?

The prototype used 1 goroutine per-stream (and work class, but now its all elastic). Having one per-stream is still probably the direction we should go, assuming these are shared across all ranges on the node.
</blockquote></details>

Although, the `watchTokens` goroutine is per-stream in the prototype - is this the intention to keep it like this? Dunno if it could become problematic in large clusters (hundreds of runnable gs potentially?). But if it's intended and is fine, then there seems to be no much benefit in making the watcher a singleton? It logically sounds like a per-stream concept.


<!-- Sent from Reviewable.io -->

2024-08-05 20:26 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3ZAYiV-r3co-tdMq6l:b5whx97) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

See the other comment, I've updated to pass in a stream instead of the counter. The elastic distinction for send queueing is somewhat clearer now, so I don't think its necessary to also include it in the method naming, if the iface references `Send`.
</blockquote></details>

I prefer to change this back to accepting a `TokenCounter`. The caller already has a `TokenCounter` and should not have to pass a `Stream` that the callee then needs to use to lookup the `TokenCounter` via `StreamTokenCounterProvider`. RACv1 had a bunch of such indirection, and I'd like to avoid such unnecessary lookups and locking.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3ZBhnTDYdvwWomiybe:b-lta4nh) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Although, the `watchTokens` goroutine is per-stream in the prototype - is this the intention to keep it like this? Dunno if it could become problematic in large clusters (hundreds of runnable gs potentially?). But if it's intended and is fine, then there seems to be no much benefit in making the watcher a singleton? It logically sounds like a per-stream concept.
</blockquote></details>

We need a container for the per-stream watcher, even if we expose the per-stream watcher as its own type. If we ever get concerned about the number of streams, we need to be able to garbage collect these per-stream watchers, which means the container also needs to know when to remove them from its map. Having all methods flow via the container makes that viable.


<!-- Sent from Reviewable.io -->

2024-08-05 20:32 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 39 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3ZDStQEfWgyMXLI8Mi:-O3ZDStQEfWgyMXLI8Mj:bvyyzor) ([raw file](https://github.com/cockroachdb/cockroach/blob/658b444266482584c7f1e1e7e9036990e73ae99f/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L39)):*
> ```Go
> //
> // TODO(kvoli): Consider de-interfacing if not necessary for testing.
> type SendTokenWatcherProvider interface {
> ```

Does this need to exist outside the lifetime of the send stream? Same for `StreamTokenCounterProvider`.

I.e. do we just need a "send stream" interface that, once created, provides both the token counters and the token watcher (and maybe some other supporting things)? Or these objects somehow need to outlive the stream in some cases?

Probably ok to have these stubs in place now, and it'll become clearer when some meaty implementations are added. This is more for my understanding of the semantics.


<!-- Sent from Reviewable.io -->

2024-08-05 20:35 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3ZEh6-4Z1v9SQbA26U:b9044te) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We need a container for the per-stream watcher, even if we expose the per-stream watcher as its own type. If we ever get concerned about the number of streams, we need to be able to garbage collect these per-stream watchers, which means the container also needs to know when to remove them from its map. Having all methods flow via the container makes that viable.
</blockquote></details>

Yeah, SGTM to decouple the per-stream interface vs the physical container / goroutines. In the extreme, all things could be run by a singleton object / pool, yet the watcher "interface" per stream can use it at the "backend".


<!-- Sent from Reviewable.io -->

2024-08-05 20:36 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3ZESpK1MVZ6zbobcEE:-O3ZESpK1MVZ6zbobcEF:b-mhnry1) ([raw file](https://github.com/cockroachdb/cockroach/blob/658b444266482584c7f1e1e7e9036990e73ae99f/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L64)):*
assumed this changed due to
> How about a `func(context.Context)` callback in the interface above, to avoid the interface boilerplate?

I believe this will always allocate when `NotifyWhenAvailable` is called, due to the need to capture the state for the closure (a word for the `replicaSendStream` pointer, and another for its function pointer). In comparison, with an interface, the two words needed for the interface are already included.


<!-- Sent from Reviewable.io -->

2024-08-05 20:40 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3ZG0NZ-GNaxwRWrlac:ba70jjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I prefer to change this back to accepting a `TokenCounter`. The caller already has a `TokenCounter` and should not have to pass a `Stream` that the callee then needs to use to lookup the `TokenCounter` via `StreamTokenCounterProvider`. RACv1 had a bunch of such indirection, and I'd like to avoid such unnecessary lookups and locking.
</blockquote></details>

Isn't the `Stream` supposed to contain a `TokenCounter` inited pretty much at creation, which can be returned without locking and lookups? Or there is some decoupling/indirection there?


<!-- Sent from Reviewable.io -->

2024-08-05 20:41 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3ZG4Q86kH6b6XNfU5y:b69si20) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Yeah, SGTM to decouple the per-stream interface vs the physical container / goroutines. In the extreme, all things could be run by a singleton object / pool, yet the watcher "interface" per stream can use it at the "backend".
</blockquote></details>

I would prefer to go back to the singleton with a `NotifyWhenAvailable(TokenCounter ...)` interface. It ensures everything flows through the "container" whether the container is dumb-ish, like now, or becomes more sophisticated. This enables more sophisticated garbage collection of state. It also removes unnecessary abstractions we are having to introduce like `SendTokenWatcherProvider`.


<!-- Sent from Reviewable.io -->

2024-08-05 20:42 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3ZGW00-eRC6FcWKj4W:b-pezswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Isn't the `Stream` supposed to contain a `TokenCounter` inited pretty much at creation, which can be returned without locking and lookups? Or there is some decoupling/indirection there?
</blockquote></details>

Which `Stream`? The `replicaSendStream` does get init'd with the counter on creation.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 43 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yp_Rx-4xvHi2MVDwJ:-O3ZDw-i0bpUBlmaWDpq:b-w8cm2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L43)):*
> Although, the `watchTokens` goroutine is per-stream in the prototype - is this the intention to keep it like this?

Intention is keeping it per-stream. There weren't any issues with this approach in the prototype, when running a large number of stores, so lets keep it unless we run into problems, which we can tackle then.


> We need a container for the per-stream watcher, even if we expose the per-stream watcher as its own type. If we ever get concerned about the number of streams, we need to be able to garbage collect these per-stream watchers, which means the container also needs to know when to remove them from its map. Having all methods flow via the container makes that viable.

The per-stream watchers wouldn't be GC'd from a map until the newer map type is added in golang anyway. I'm going to **revert** back to the older interface and when we implement the watcher, we can discuss further how these may be refined.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 39 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3ZDStQEfWgyMXLI8Mi:-O3ZEsMU1dm4iPFE_bKi:bogt39f) ([raw file](https://github.com/cockroachdb/cockroach/blob/658b444266482584c7f1e1e7e9036990e73ae99f/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L39)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Does this need to exist outside the lifetime of the send stream? Same for `StreamTokenCounterProvider`.

I.e. do we just need a "send stream" interface that, once created, provides both the token counters and the token watcher (and maybe some other supporting things)? Or these objects somehow need to outlive the stream in some cases?

Probably ok to have these stubs in place now, and it'll become clearer when some meaty implementations are added. This is more for my understanding of the semantics.
</blockquote></details>

They may need to outlive the lifetime, returning tokens after close etc.  
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3ZESpK1MVZ6zbobcEE:-O3ZGU6H7jtM3ULOrSl_:b9h2zhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/658b444266482584c7f1e1e7e9036990e73ae99f/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L64)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

assumed this changed due to
> How about a `func(context.Context)` callback in the interface above, to avoid the interface boilerplate?

I believe this will always allocate when `NotifyWhenAvailable` is called, due to the need to capture the state for the closure (a word for the `replicaSendStream` pointer, and another for its function pointer). In comparison, with an interface, the two words needed for the interface are already included.
</blockquote></details>

I'll revert.


<!-- Sent from Reviewable.io -->

2024-08-05 20:52 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 64 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3ZESpK1MVZ6zbobcEE:-O3ZIOkNAcjhwO4bJWJf:b2nhoia) ([raw file](https://github.com/cockroachdb/cockroach/blob/658b444266482584c7f1e1e7e9036990e73ae99f/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L64)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I'll revert.
</blockquote></details>

TIL


<!-- Sent from Reviewable.io -->

2024-08-05 20:56 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @kvoli, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3ZJiUFBEf7bN-odXox:bn7vubu) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Which `Stream`? The `replicaSendStream` does get init'd with the counter on creation.
</blockquote></details>

I mean `replicaSendStream`, yeah. It references the `parent *replicaState` which contains the token counters. Aren't they always initialized throughout the send stream lifetime?


<!-- Sent from Reviewable.io -->

2024-08-05 21:00 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @pav-kv, and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go` line 42 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-O3Yodyk3EIkUXNHHiBz:-O3ZKjDi4znzuPmwsudt:b-k3qal5) ([raw file](https://github.com/cockroachdb/cockroach/blob/81c71163bcab77e39f379a18bbbe28241c8c6f20/pkg/kv/kvserver/kvflowcontrol/rac2/store_stream.go#L42)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

I mean `replicaSendStream`, yeah. It references the `parent *replicaState` which contains the token counters. Aren't they always initialized throughout the send stream lifetime?
</blockquote></details>

Yeah, they should always be initialized.


<!-- Sent from Reviewable.io -->

2024-08-05 21:15 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r9, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128195#-:-O3ZORTt7iBZ-1mEkY5q:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist and @pav-kv)



<!-- Sent from Reviewable.io -->

2024-08-05 21:19 UTC, kvoli commented
TYFTR

bors r=sumeerbhola

2024-08-05 21:48 UTC, merged