sqlliveness: handle AmbiguousResultError gracefully on insert
cockroachdb/cockroach pull request #128902
Opened 2024-08-13 16:10 UTC by fqazi

Previously, when inserting a new SQL liveness session, we extended the expiry between each InitPut to ensure that an expired session was never inserted. This worked well, but if an ambiguous result error was encountered, the row could already exist in the table with the old timestamp leading to a condition failed error.  To address this, this patch will also assign a new session ID if we encounter an ambiguous result error. This will ensure that we do not collide with the old session ID.

Fixes: #127301
Release note (bug fix): Starting up nodes could fail with: "could not insert session ...: unexpected value", if an ambigous result error was hit inserting into the sqlliveness table.

2024-08-13 16:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/128902)
<!-- Reviewable:end -->

2024-08-14 11:37 UTC, spilchen requested changes
This looks great. I had a few minor nits for readability, but feel free to disregard them if you prefer the original approach.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-:-O4Fec5_Edt3wvlnwHQx:bk93n5i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @jeffswenson)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4FcHfB5gvwhiY0PVTB:-O4FcHfB5gvwhiY0PVTC:beg38i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance.go#L217)):*
> ```Go
> 		// Allocate a new session ID initially or if we hit
> 		// an ambiguous result error.
> 		if createNewSession {
> ```

nit: do we need a variable for this? Could we just check if s.id is the empty string.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4FdSnUBmUg9sKpNFXV:-O4FdSnUBmUg9sKpNFXW:b-5dp7lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance.go#L218)):*
> ```Go
> 		// an ambiguous result error.
> 		if createNewSession {
> 			id, err = slstorage.MakeSessionID(region, uuid.MakeV4())
> ```

nit: do we need id? Can we just set s.id directly.



_Suggestion:_
```Go
s.id, err = slstorage.MakeSessionID(region, uuid.MakeV4())
```
___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4Fce-52p_u7oTujPU5:-O4Fce-52p_u7oTujPU6:b-mvxndt) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance.go#L249)):*
> ```Go
> 			// since there may be a row that exists.
> 			if errors.HasType(err, (*kvpb.AmbiguousResultError)(nil)) {
> 				createNewSession = true
> ```

Is this a rare enough event that we should emit a log message when we get in here?
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4FeLLz4BzAqluSSY5K:-O4FeLLz4BzAqluSSY5L:b1hkhw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L80)):*
> ```Go
> 	})
> 	sqlInstance.Start(ctx, nil)
> 	// We expect two attempts to insert, since we inject a replica unavailable
> ```

I think this comment is out of date now that we have another retry attempt.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4Fe8g-2Qlw_HUB_wqo:-O4Fe8g-2Qlw_HUB_wqp:b6zzob8) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L98)):*
> ```Go
> 		}
> 		if session.ID() == failureMu.lastSessionID || len(failureMu.lastSessionID) == 0 {
> 			return errors.AssertionFailedf("new session ID should have been assigned after an ambigous"+
> ```

nit: spelling



_Suggestion:_
```Go
ambiguous
```


<!-- Sent from Reviewable.io -->

2024-08-16 04:08 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jeffswenson and @spilchen)

___
*[`pkg/sql/sqlliveness/slinstance/slinstance.go` line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4Fce-52p_u7oTujPU5:-O4OKMISCWRH97bmllbu:b20k5po) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance.go#L249)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this a rare enough event that we should emit a log message when we get in here?
</blockquote></details>

Done.

Good point, let me add a message here.
___
*[`pkg/sql/sqlliveness/slinstance/slinstance_test.go` line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-O4FeLLz4BzAqluSSY5K:-O4OLJog5K7E83brC0Id:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27329adf306da38f3224f2d3a5a010e64999d011/pkg/sql/sqlliveness/slinstance/slinstance_test.go#L80)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I think this comment is out of date now that we have another retry attempt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-19 12:23 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128902#-:-O4e_u1y4jqe3PEoLx4T:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jeffswenson)



<!-- Sent from Reviewable.io -->

2024-08-19 13:23 UTC, fqazi commented
@spilchen TFTR!

bors r+

2024-08-19 13:51 UTC, merged