sql,ccl: add auth behaviors for authorization
cockroachdb/cockroach pull request #129845
Opened 2024-08-29 04:25 UTC by souravcrl

We currently lack auth behavior functions for authorization which can be
configured as part of AuthMethod itself. This PR adds these AuthBehaviors for
authorization, specifically: 
1. Authorizer which retrieves authorization information from an external
authorization system and is a component of the AuthMethod for that auth system.
It also maps the information it to sql identities like roles or subject role
option.
2. RolesGrantFn which defines how the mapped sql identities can be fetched as
sql group roles and be granted to the sql user session.

Release note: None

2024-08-29 04:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/129845)
<!-- Reviewable:end -->

2024-08-29 04:28 UTC, souravcrl commented
Please review only the last commit `sql,ccl: add auth behaviors for authorization` for this PR as others are reviewed in their respective PRs.

2024-08-29 07:53 UTC, pritesh-lahoti reviewed
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*




_Suggestion:_
```
to
```
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5RxbXI-TLJ10OVpOL9:-O5RxbXI-TLJ10OVpOLA:b-w3jal6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L34)):*
> ```Go
> 	roleMapper          RoleMapper
> 	authorizer          Authorizer
> 	grantRolesFn        RolesGrantFn
> ```

nit: for being consistent, as RoleMapper is also a function type.
RoleMapper could also potentially map to multiple roles, so I'd prefer `RoleGranter` over `RolesGranter`.



_Suggestion:_
```Go
RoleGranter
```
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S4SqXB6J_8SkVq0R4:-O5S4SqXB6J_8SkVq0R5:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L127)):*
> ```Go
> ) error {
> 	if b.authorizer != nil {
> 		if groups, err := b.authorizer(ctx, systemIdentity, clientConnection); err != nil {
> ```

nit



_Suggestion:_
```Go
sqlGroups
```
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5RyZxd4zn2FjjUb1s3:-O5RyZxe67aE8uvCFiOK:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L128)):*
> ```Go
> 	if b.authorizer != nil {
> 		if groups, err := b.authorizer(ctx, systemIdentity, clientConnection); err != nil {
> 			return errors.Newf("error retriving group roles for authorize: %v", err)
> ```

nit



_Suggestion:_
```Go
return errors.Newf("error retrieving groups from authorizer: %v", err)
```
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S4_sdDpOblFo-gy7U:-O5S4_sdDpOblFo-gy7V:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L139)):*
> ```Go
> // returns an error if SetRolesGrant has not been called.
> func (b *AuthBehaviors) GrantRoles(
> 	ctx context.Context, systemIdentity username.SQLUsername, groups []username.SQLUsername,
> ```

nit



_Suggestion:_
```Go
sqlGroups
```
___
*[`pkg/sql/pgwire/auth_methods.go` line 989 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S44y_0WZSpibP6ftV:-O5S44y_0WZSpibP6ftW:bfwaaus) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_methods.go#L989)):*
> ```Go
> 			return nil, authError
> 		} else {
> 			log.Infof(ctx, "LDAP authorization: retrieved ldap groups are %+v", ldapGroups)
> ```

nit: We may choose to not log groups on every successful fetch. They are already being logged below in case of any failure.
___
*[`pkg/sql/pgwire/authorizer.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6fCODrxI96WwzwBM:-O5S6fCODrxI96WwzwBN:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/authorizer.go#L44)):*
> ```Go
> 	ctx context.Context,
> 	systemIdentity username.SQLUsername,
> 	groups []username.SQLUsername,
> ```

nit



_Suggestion:_
```Go
sqlGroups
```


<!-- Sent from Reviewable.io -->

2024-08-30 05:53 UTC, souravcrl reviewed
addressed changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-:-O5Wq74m0nyysbDlHIy5:b-a2tdab)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*
done
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5RxbXI-TLJ10OVpOL9:-O5UfFeV7DSQWaDIWPG8:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L34)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: for being consistent, as RoleMapper is also a function type.
RoleMapper could also potentially map to multiple roles, so I'd prefer `RoleGranter` over `RolesGranter`.
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 127 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S4SqXB6J_8SkVq0R4:-O5UgLBf8jo8GRjuXnWH:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L127)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5RyZxd4zn2FjjUb1s3:-O5UgMKE2VgxweC8zyyw:b-ch0bgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L128)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit
</blockquote></details>

removed this as authenticator also uses the error from the set method in auth_method.go instead of wrapping it here.
___
*[`pkg/sql/pgwire/auth_behaviors.go` line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S4_sdDpOblFo-gy7U:-O5Ugt7g-7jY7_v48L58:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_behaviors.go#L139)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth_methods.go` line 989 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S44y_0WZSpibP6ftV:-O5UiHiD7-ym3slhwBhU:b7pqfi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/auth_methods.go#L989)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: We may choose to not log groups on every successful fetch. They are already being logged below in case of any failure.
</blockquote></details>

changed the messaging to say `LDAP authorization sync succeeded; attempting to assign roles`
___
*[`pkg/sql/pgwire/authorizer.go` line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6fCODrxI96WwzwBM:-O5UiiKf-ua1Wfsv2Yho:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9940b9c5847c9f186ed130ef368f520710e5c6e/pkg/sql/pgwire/authorizer.go#L44)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-08-30 05:58 UTC, pritesh-lahoti approved these changes
Thank you for all the changes!

> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-:-O5WrAR38OU-q0UpiFrz:b-e46pwh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

done
</blockquote></details>

nit: looks like this is yet to be addressed.
Also, need to rename `RolesGrantFn` to `RoleGranter` below in (2).


<!-- Sent from Reviewable.io -->

2024-08-30 06:56 UTC, souravcrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: looks like this is yet to be addressed.
Also, need to rename `RolesGrantFn` to `RoleGranter` below in (2).
</blockquote></details>

My bad. I wrongly added a commit, then removed it and amended the current one leading to this. Have addressed it now.


<!-- Sent from Reviewable.io -->

2024-08-30 08:03 UTC, pritesh-lahoti approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

My bad. I wrongly added a commit, then removed it and amended the current one leading to this. Have addressed it now.
</blockquote></details>

nit: Need to rename `RolesGrantFn` to `RoleGranter` below in (2).


<!-- Sent from Reviewable.io -->

2024-09-12 17:51 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @souravcrl)

___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O6bLUjW17EnOEyBw3DI:b-w4hy6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9e8745e751a29d235f8b1b4c11f22894eed7c0/pkg/sql/pgwire/auth_methods.go#L994)):*
> ```Go
> 			for idx := range ldapGroups {
> 				var err error
> 				if sqlGroupRoles[idx], err = username.MakeSQLUsernameFromUserInput(ldapGroups[idx].String(), username.PurposeValidation); err != nil {
> ```

just for my own knowledge: is the `String` function correct here? i wasn't sure what it would look like, since it seems like the implementation might result in some names that are not actually SQL usernames
```
// String returns a normalized string representation of this DN which is the
// join of all relative DNs with a ",".
func (d *DN) String() string {
	rdns := make([]string, len(d.RDNs))
	for i := range d.RDNs {
		rdns[i] = d.RDNs[i].String()
	}
	return strings.Join(rdns, ",")
}
```
___
*[`pkg/sql/pgwire/auth_methods.go` line 1001 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLvgV7jR7ZmxAFeRD:-O6bLvgV7jR7ZmxAFeRE:b-gbm5co) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9e8745e751a29d235f8b1b4c11f22894eed7c0/pkg/sql/pgwire/auth_methods.go#L1001)):*
> ```Go
> 		}
> 	})
> 	b.SetRoleGranter(func(ctx context.Context, user username.SQLUsername, sqlGroups []username.SQLUsername) error {
> ```

wanted to make sure i understand this part: is this a TODO where we should fill this in later?


<!-- Sent from Reviewable.io -->

2024-09-13 07:46 UTC, souravcrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @rafiss)

___
*[`-- commits` line 68 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O5S6rJc9EF13SlphNJl):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: Need to rename `RolesGrantFn` to `RoleGranter` below in (2).
</blockquote></details>

done
___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O6e7N2tB6snukSTa9Gl:b2bdfml) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9e8745e751a29d235f8b1b4c11f22894eed7c0/pkg/sql/pgwire/auth_methods.go#L994)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just for my own knowledge: is the `String` function correct here? i wasn't sure what it would look like, since it seems like the implementation might result in some names that are not actually SQL usernames
```
// String returns a normalized string representation of this DN which is the
// join of all relative DNs with a ",".
func (d *DN) String() string {
	rdns := make([]string, len(d.RDNs))
	for i := range d.RDNs {
		rdns[i] = d.RDNs[i].String()
	}
	return strings.Join(rdns, ",")
}
```
</blockquote></details>

I was unsure how we are going to use the group distinguished names. We have a similar implementation for gss api users we obtain in `gssapi.go`:
https://github.com/cockroachdb/cockroach/blob/42f5ac82b1908d44ec862e23deb4c3d94e948e61/pkg/ccl/gssapiccl/gssapi.go#L60-L64
As I see there are 2 possible representations we need to handle:
1. Extract the common name from the group distinguished name and set that as the SQL username(to be used to fetch crdb sql group roles in roleGranter)
2. Extract the full distinguished name and and match that against group roles( we match against subject role option where we set the full DN and then retrieve the role in roleGranter using the obtained DN here)

For above 2 cases, SQLusername seemed like a common representation which can be used to denote both. Furthermore, if we are to extend roleGranter to JWT authMethod, we can have member group common names as claims in JWT which can be retrieved and set as return output in the authorizer fn.
___
*[`pkg/sql/pgwire/auth_methods.go` line 1001 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLvgV7jR7ZmxAFeRD:-O6eKR3E9ve8T3vbNuXg:bcivi2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9e8745e751a29d235f8b1b4c11f22894eed7c0/pkg/sql/pgwire/auth_methods.go#L1001)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

wanted to make sure i understand this part: is this a TODO where we should fill this in later?
</blockquote></details>

Yes, this is the TODO for the RoleGranter which gets calls a part of Authorize() in `handleAuthentication()`. This could be implemented in multiple ways depending on if we want to sync CN or the full DN to match against the group SQL role.


<!-- Sent from Reviewable.io -->

2024-09-13 09:57 UTC, souravcrl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @rafiss)

___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O6emy9E7rUxfcSs5BXs:bdymwbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9e8745e751a29d235f8b1b4c11f22894eed7c0/pkg/sql/pgwire/auth_methods.go#L994)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

I was unsure how we are going to use the group distinguished names. We have a similar implementation for gss api users we obtain in `gssapi.go`:
https://github.com/cockroachdb/cockroach/blob/42f5ac82b1908d44ec862e23deb4c3d94e948e61/pkg/ccl/gssapiccl/gssapi.go#L60-L64
As I see there are 2 possible representations we need to handle:
1. Extract the common name from the group distinguished name and set that as the SQL username(to be used to fetch crdb sql group roles in roleGranter)
2. Extract the full distinguished name and and match that against group roles( we match against subject role option where we set the full DN and then retrieve the role in roleGranter using the obtained DN here)

For above 2 cases, SQLusername seemed like a common representation which can be used to denote both. Furthermore, if we are to extend roleGranter to JWT authMethod, we can have member group common names as claims in JWT which can be retrieved and set as return output in the authorizer fn.
</blockquote></details>

Note sometimes entra ID can have common name(CN) like Sourav Sarangi (E63CF6F3) for users as well as groups with full DN being (CN=Sourav Sarangi (E63CF6F3),OU=AADDC Users,DC=crlcloud,DC=dev). This could be a problem as SQL usernames cannot `(` and `)` special characters. So, wanted to check with you @rafiss for the best representation going forward.


<!-- Sent from Reviewable.io -->

2024-09-17 06:03 UTC, souravcrl reviewed
@rafiss needed you inputs on the interfaces for authorizer and roleGranter, if we needed some more amends keeping in mind the changes required for authZ on crdb.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-:-O6yZgy9EQnZaCBxnmL6:b-gn28un)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @rafiss)



<!-- Sent from Reviewable.io -->

2024-09-18 21:43 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @souravcrl)

___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O764MI3CXrgFdS8t1yM:btpfidw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L994)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Note sometimes entra ID can have common name(CN) like Sourav Sarangi (E63CF6F3) for users as well as groups with full DN being (CN=Sourav Sarangi (E63CF6F3),OU=AADDC Users,DC=crlcloud,DC=dev). This could be a problem as SQL usernames cannot `(` and `)` special characters. So, wanted to check with you @rafiss for the best representation going forward.
</blockquote></details>

i think option 1 makes more sense. if we use that approach, we should be able to translate from the `ldap.DN` to the SQL username here by looking for the common name field. then we should stop using the `(*DN).String()` function


<!-- Sent from Reviewable.io -->

2024-09-18 22:20 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @souravcrl)

___
*[`pkg/sql/pgwire/auth_methods.go` line 931 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O767FOt1uYBANludfQw:-O767FOt1uYBANludfQx:bz9c0o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L931)):*
> ```Go
> 		// The DN of user from LDAP server is set as the system identity DN which
> 		// can then be used for authenticator & authorizer AuthBehaviors fn.
> 		externalUserDN, err := username.MakeSQLUsernameFromUserInput(ldapUserDN.String(), username.PurposeValidation)
> ```

i'm also looking back at this part of the code here. i feel like this also may be incorrect. i definitely think it could be a problem to just ignore the error.

i think it would make more sense if `SetSystemIdentity` accepted `string` as the parameter type.

we should always make sure that any variable of the type `username.SQLUsername` corresponds to an actual user in the CRDB system.users table

i made this draft PR to show what i think: https://github.com/cockroachdb/cockroach/pull/130979 i will clean this up in a little bit.


<!-- Sent from Reviewable.io -->

2024-09-19 05:47 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @souravcrl)

___
*[`pkg/sql/pgwire/auth_methods.go` line 931 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O767FOt1uYBANludfQw:-O77nbOQBAcN_O0qAvtY:b-s72963) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L931)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm also looking back at this part of the code here. i feel like this also may be incorrect. i definitely think it could be a problem to just ignore the error.

i think it would make more sense if `SetSystemIdentity` accepted `string` as the parameter type.

we should always make sure that any variable of the type `username.SQLUsername` corresponds to an actual user in the CRDB system.users table

i made this draft PR to show what i think: https://github.com/cockroachdb/cockroach/pull/130979 i will clean this up in a little bit.
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/130979 is ready for review now

i think this refactor should not be too intrusive, and it should make the code easier to reason about. previously, many parts of the code were confusing the dbUser and the systemIdentity for each other. the incorrect typing is also what led to this odd-looking conversion from DN to SQLUsername.
___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O77o-Es6SVpqYAd8F6N:b3tgnrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L994)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think option 1 makes more sense. if we use that approach, we should be able to translate from the `ldap.DN` to the SQL username here by looking for the common name field. then we should stop using the `(*DN).String()` function
</blockquote></details>

we can do option 1 in a follow-up PR if that's easier. all the other changes in this PR lgtm!


<!-- Sent from Reviewable.io -->

2024-09-19 11:04 UTC, souravcrl reviewed
Thank you for the review!


bors r=pritesh-lahoti,rafiss

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-:-O78wjAT370J3TSj35V0:b909tpv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti and @rafiss)

___
*[`pkg/sql/pgwire/auth_methods.go` line 931 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O767FOt1uYBANludfQw:-O78um-J2_NADV-PGntz:b5icsvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L931)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/pull/130979 is ready for review now

i think this refactor should not be too intrusive, and it should make the code easier to reason about. previously, many parts of the code were confusing the dbUser and the systemIdentity for each other. the incorrect typing is also what led to this odd-looking conversion from DN to SQLUsername.
</blockquote></details>

I have gone through the PR and feel it improves the external systemIdentity nomenclature throughout the code. Will be merging this PR accordingly.
___
*[`pkg/sql/pgwire/auth_methods.go` line 994 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/129845#-O6bLUjW17EnOEyBw3DH:-O78wEOHCLjh_B9wFoL6:b-o6vmob) ([raw file](https://github.com/cockroachdb/cockroach/blob/b08724547f0610babdf10925112358b466f6e369/pkg/sql/pgwire/auth_methods.go#L994)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we can do option 1 in a follow-up PR if that's easier. all the other changes in this PR lgtm!
</blockquote></details>

will take this up in a separately. Option 1 should hold good for group CNs(common names) and we should proceed accordingly.


<!-- Sent from Reviewable.io -->

2024-09-19 11:31 UTC, merged