kvserver: compact liveness range periodically
cockroachdb/cockroach pull request #129827
Opened 2024-08-28 19:13 UTC by iskettaneh

This commit adds a cluster setting (turned off by default) that sets the period at which manual liveness range compactions are done.

This is done in a goroutine rather than in MVCC GC queue because:

1) This is meant to be a stop gap as this in not needed in 24.3 onwards. Therefore, a simple change like this should achieve the goal.

2) The MVCC GC queue runs against leaseholder replicas only. This means that we need to send a compaction request to the other liveness replicas.

Fixes: #128968

Epic: None

Release note: None

2024-08-28 19:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/129827)
<!-- Reviewable:end -->

2024-09-02 12:48 UTC, stevendanna reviewed
Just took a look out of curiosity.

It might be helpful to have a bit of commentary somewhere on why we aren't doing this via the mvcc gc queue.

2024-09-02 12:48 UTC, stevendanna commented on pkg/server/node.go
> +		livenessRangeCompactInterval.Get(&n.storeCfg.Settings.SV))
I wonder if it might be better to arrange this such that the interval can be adjusted without restarting the node?

2024-09-02 12:48 UTC, stevendanna commented on pkg/server/node.go
> +						if keys.NodeLivenessSpan.Overlaps(repl.Desc().KeySpan().AsRawSpanWithNoLocals()) {
[nit] Maybe pull `repl.Desc().KeySpan().AsRawSpanWithNoLocals()` into a local var for use here and below?

2024-09-03 17:47 UTC, iskettaneh reviewed
Done. I changed the commit description to reflect that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-:-O5sze4m7KcDC8-f3yW8:bq6glwh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @nvanbenschoten, and @stevendanna)

___
*[`pkg/server/node.go` line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129827#gh-1740832793:-O5szklh4rgbNUkF1i-K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c826e7ddbb9d3a4ae453ac26a306e9ea623090/pkg/server/node.go#L824)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I wonder if it might be better to arrange this such that the interval can be adjusted without restarting the node?
</blockquote></details>

Done.
___
*[`pkg/server/node.go` line 1135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129827#gh-1740866707:-O5s3yRsDzaSrH9eGhYS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c826e7ddbb9d3a4ae453ac26a306e9ea623090/pkg/server/node.go#L1135)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] Maybe pull `repl.Desc().KeySpan().AsRawSpanWithNoLocals()` into a local var for use here and below?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 18:59 UTC, andrewbaptist requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh, @nvanbenschoten, and @stevendanna)

___
*[`pkg/server/node.go` line 1132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yN9EQDq86WK4h5DBV:-O5yN9EQDq86WK4h5DBW:bl9c6ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1132)):*
> ```Go
> 	}
> 
> 	_ = stopper.RunAsyncTask(ctx, "liveness-compaction", func(ctx context.Context) {
> ```

nit: Log an `Errorf` if this call returns an error. That normally won't happen, but it can help with debugging if it ever does.
___
*[`pkg/server/node.go` line 1139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yOPatAhQPXMFd3VsT:-O5yOPatAhQPXMFd3VsU:b353kf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1139)):*
> ```Go
> 		livenessRangeCompactInterval.SetOnChange(&n.storeCfg.Settings.SV, func(ctx context.Context) {
> 			interval := getCompactionInterval()
> 			ticker.Reset(interval)
> ```

I don't think this is safe to do. I'm not 100% sure of the implications of changing it from another goroutine, but typically the SetOnChange for a ticker will write to a channel and the main loop will select on that channel. See cidr.go for an example of this. I looked at the go docs on this, and it wasn't clear to me what happens in cases where this is racing with the timer completing, but it would probably be better to not touch the ticker from a different goroutine.
___
*[`pkg/server/node.go` line 1164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yOpAUBKEcF5CBq8PZ:-O5yOpAUBKEcF5CBq8P_:b1w3trq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1164)):*
> ```Go
> 								}.Encode()
> 
> 							log.Infof(ctx, "attempting to compact liveness replica: %+v", repl)
> ```

nit: I don't think we need 2 log messages. Consider grabbing a 'startTime' here and logging the time interval in the 'finished' log below.


<!-- Sent from Reviewable.io -->

2024-09-04 19:00 UTC, andrewbaptist reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh, @nvanbenschoten, and @stevendanna)

___
*[`pkg/server/node.go` line 1165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yPDzi4XLotIqcr2tx:-O5yPDzi4XLotIqcr2ty:b-7dwebi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1165)):*
> ```Go
> 
> 							log.Infof(ctx, "attempting to compact liveness replica: %+v", repl)
> 							if err := store.TODOEngine().CompactRange(startEngineKey, endEngineKey); err != nil {
> ```

nit: Ideally don't use the TODO engine.


<!-- Sent from Reviewable.io -->

2024-09-04 19:54 UTC, iskettaneh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @nvanbenschoten, and @stevendanna)

___
*[`pkg/server/node.go` line 1139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yOPatAhQPXMFd3VsT:-O5y_zDk5ZEWtfNPDnMk:b-4exzf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1139)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I don't think this is safe to do. I'm not 100% sure of the implications of changing it from another goroutine, but typically the SetOnChange for a ticker will write to a channel and the main loop will select on that channel. See cidr.go for an example of this. I looked at the go docs on this, and it wasn't clear to me what happens in cases where this is racing with the timer completing, but it would probably be better to not touch the ticker from a different goroutine.
</blockquote></details>

That's an excellent point! I added a buffered channel to signal to the goroutine to change the interval.

I have one concern though that I want to clarify with you.

I am concerned about the following scenario
1) The `<-stopper.ShouldQuiesce()` case is true. This means that we will exit the async task
2) If now we attempt to change the interval, the channel will block (when the size limit is reached), and no one will read from it since the only function that reads that channel now exited.

Do you have any recommendation on how to avoid the scenario above?
___
*[`pkg/server/node.go` line 1165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yPDzi4XLotIqcr2tx:-O5yX5MvAQXt93sGXbEk:b-junu63) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1165)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Ideally don't use the TODO engine.
</blockquote></details>

I see that there is (1) StateEngine(), and (2) LogEngine(). Which one of the two I should use for liveness compaction?


<!-- Sent from Reviewable.io -->

2024-09-04 20:07 UTC, andrewbaptist reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh, @nvanbenschoten, @stevendanna, and @tbg)

___
*[`pkg/server/node.go` line 1139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yOPatAhQPXMFd3VsT:-O5yazu_3hL-Huu8I0KF:bh4nrw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1139)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

That's an excellent point! I added a buffered channel to signal to the goroutine to change the interval.

I have one concern though that I want to clarify with you.

I am concerned about the following scenario
1) The `<-stopper.ShouldQuiesce()` case is true. This means that we will exit the async task
2) If now we attempt to change the interval, the channel will block (when the size limit is reached), and no one will read from it since the only function that reads that channel now exited.

Do you have any recommendation on how to avoid the scenario above?
</blockquote></details>

That is a good point! In our code base, this typically won't be a problem because once ShouldQuiesce returns we won't change settings anymore. However I agree it would be better to handle this better. By making it a buffered channel with a small capacity (say 2) it shouldn't hit this. 

The better alternative is to `try` to deliver to the channel. Something like:
```
select {
case ch <- newInterval:
default:
}
```

This will prevent the `SetOnChange` from blocking.
___
*[`pkg/server/node.go` line 1165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yPDzi4XLotIqcr2tx:-O5ycRb37GFzkHkNouXn:b-gl8bqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1165)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

I see that there is (1) StateEngine(), and (2) LogEngine(). Which one of the two I should use for liveness compaction?
</blockquote></details>

I'm 95% sure it is the `StateEngine`, but I'm pinging @tbg to check for sure.  As of today, I think the methods return the same value. If nothing else it will be good to validate that we only need one engine here. My understanding is that the `StateEngine` is for reading from and the `LogEngine` is for writing new logs to.


<!-- Sent from Reviewable.io -->

2024-09-04 20:29 UTC, iskettaneh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @nvanbenschoten, @stevendanna, and @tbg)

___
*[`pkg/server/node.go` line 1139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yOPatAhQPXMFd3VsT:-O5yhari9Vp0KS7w_NQK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1139)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

That is a good point! In our code base, this typically won't be a problem because once ShouldQuiesce returns we won't change settings anymore. However I agree it would be better to handle this better. By making it a buffered channel with a small capacity (say 2) it shouldn't hit this. 

The better alternative is to `try` to deliver to the channel. Something like:
```
select {
case ch <- newInterval:
default:
}
```

This will prevent the `SetOnChange` from blocking.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 21:22 UTC, iskettaneh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129827)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @nvanbenschoten, @stevendanna, and @tbg)

___
*[`pkg/server/node.go` line 1165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129827#-O5yPDzi4XLotIqcr2tx:-O5ytrs21KP9_6rjscV7:b7144tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f4cda88fa7c81f70b40940ede21027bd39ac3c5/pkg/server/node.go#L1165)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I'm 95% sure it is the `StateEngine`, but I'm pinging @tbg to check for sure.  As of today, I think the methods return the same value. If nothing else it will be good to validate that we only need one engine here. My understanding is that the `StateEngine` is for reading from and the `LogEngine` is for writing new logs to.
</blockquote></details>

Based on https://github.com/cockroachdb/cockroach/commit/5b6302b2ed2a83f49b55329ce3cac5f6135d0aea, it seems that in the future, the plan is to use a separate log engine. At the current time, all three functions return the same engine.

I changed the commit to use the StateEngine.


<!-- Sent from Reviewable.io -->

2024-09-05 00:29 UTC, andrewbaptist approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks for the quick turnaround on changes!

2024-09-05 15:27 UTC, iskettaneh commented
bors r+

2024-09-05 16:29 UTC, merged

2024-09-12 13:23 UTC, iskettaneh commented
blathers backport 24.2 24.1 23.2

2024-09-13 19:20 UTC, iskettaneh commented
blathers backport 24.1.5-rc 24.2.3-rc 23.2.12-rc