tablemetadatacache: add cluster settings to automate job execution
cockroachdb/cockroach pull request #130198
Opened 2024-09-05 22:28 UTC by xinhaoz

This commit adds the ability to automate running the `UDPATE TABLE
METADATA` job. Two new cluster settings are introduced to control
the interval the job is run at:
- `tablemetadata.data_valid_duration` non-negative duration setting, which
specifies the duration for which the data in system.table_metadata is
considered valid. This duration will be used as a threshold to inform the system
on when we should run the job to refresh data. Default 20m.
- `tablemetadatacache.automatic_updates.enabled` boolean setting, which
defaults to false. If true, the system will execute the update job
on according to the interval setting above.

Fixes: https://github.com/cockroachdb/cockroach/issues/130098
Epic: [CRDB-37558](https://cockroachlabs.atlassian.net/browse/CRDB-37558)

Release note (ops change): New cluster settings have been added
which controls the refresh behaviour for the cached data shown
in the db pages in db console.
- `tablemetadata.data_valid_duration` non-negative duration setting, which
specifies the duration for which the data in system.table_metadata is
considered valid. If the cache's last update time  exceeds this threshold,
users visiting the db pages will trigger a cache refresh. Default 20m.
- `tablemetadatacache.automatic_updates.enabled` enables the cache to
be automatically updated according the validity interval. Default false.

2024-09-05 22:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/130198)
<!-- Reviewable:end -->

2024-09-06 20:01 UTC, angles-n-daemons requested changes
looks good! couple of comments and questions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-:-O67th4-9xFXRs5ILsVh:bc7ev5a)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/cluster_settings.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67lYA13u3qtJw40JTN:-O67lYA13u3qtJw40JTO:b-odm7x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/cluster_settings.go#L23)):*
> ```Go
> var tableMetadataCacheAutoUpdatesEnabled = settings.RegisterBoolSetting(
> 	settings.ApplicationLevel,
> 	"tablemetadatacache.automatic_updates.enabled",
> ```

might be a bit late for this, but I think we can just call this table metadata instead of table metadata cache. for system related statistics (table size, num ranges, etc) I feel that there's an assumption on precomputation and staleness of the metadata (links for MySQL and Postgres related settings below)

[`information_schema_stats_expiry`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_information_schema_stats_expiry)
[`autovacuum\_naptime`](https://www.postgresql.org/docs/current/runtime-config-autovacuum.html#GUC-AUTOVACUUM-MAX-WORKERS)
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67n1t28BB-2W8Qsw5B:-O67n1t28BB-2W8Qsw5C:b9lp6ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L31)):*
> ```Go
> // updateJobExecFn specifies the function that is run on each iteration of the
> // table metadata update job. It can be overriden in tests.
> var updateJobExecFn func(context.Context, isql.Executor) error = updateTableMetadataCache
> ```

I recommend making this a property on the tableMetadataUpdateJobResumer struct, so that there's less package globals.

There's (light) precedence for finding a resumer in tests:
 - [roachtest](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/cluster_to_cluster.go#L1432)
 - [sql package test](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/stats/create_stats_job_test.go#L903)

If possible, I'd recommend finding the resumer, doing a type assertion and then injecting the mock testing function into the test. The jobs.Registry struct has a function `GetResumerForClaimedJob` which could help get a direct handle to the resumer in question. Not sure if this comment is totally clear, lmk if it makes sense
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67mkBSCUtx2cCuvdo-:-O67mkBSCUtx2cCuvdo0:b3foevg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L36)):*
> ```Go
> // table metadata update job. It is not thread-safe and should only be used in
> // tests prior to starting the cluster.
> func MockJobExecFn(fn func(context.Context, isql.Executor) error) {
> ```

Will this be used outside of tests? If not, I recommend moving it to the test package. There it will neither show up in the package namespace, nor the final cockroach binary
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67qoVN5VHEp4EwPI0D:-O67qoVN5VHEp4EwPI0E:bpqqusy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L88)):*
[this call to timer.Stop can be safely removed](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/timer.go#L44)

> Note that unlike the standard library's Timer type, this Timer will
> not begin counting down until Reset is called for the first time
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67uWeJB7rJzYrX0Z2r:-O67uWeJB7rJzYrX0Z2s:bvdxyhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L92)):*
> ```Go
> 	for {
> 		if tableMetadataCacheAutoUpdatesEnabled.Get(&execCtx.ExecCfg().Settings.SV) {
> 			timer.Reset(tableMetadataCacheValidDuration.Get(&execCtx.ExecCfg().Settings.SV))
> ```

One question is what happens if the user enables the automatic updates and sets the duration to zero? If it causes the server to spin, it might be worth guarding against that use case.


<!-- Sent from Reviewable.io -->

2024-09-06 20:43 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/sql/tablemetadatacache/cluster_settings.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67lYA13u3qtJw40JTN:-O682su_2Wq4Fr0FqZfB:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/cluster_settings.go#L23)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

might be a bit late for this, but I think we can just call this table metadata instead of table metadata cache. for system related statistics (table size, num ranges, etc) I feel that there's an assumption on precomputation and staleness of the metadata (links for MySQL and Postgres related settings below)

[`information_schema_stats_expiry`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_information_schema_stats_expiry)
[`autovacuum\_naptime`](https://www.postgresql.org/docs/current/runtime-config-autovacuum.html#GUC-AUTOVACUUM-MAX-WORKERS)
</blockquote></details>

Renamed.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67n1t28BB-2W8Qsw5B:-O67ysxw3fi6TDmzRv_f:bj3o0zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L31)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I recommend making this a property on the tableMetadataUpdateJobResumer struct, so that there's less package globals.

There's (light) precedence for finding a resumer in tests:
 - [roachtest](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/cluster_to_cluster.go#L1432)
 - [sql package test](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/stats/create_stats_job_test.go#L903)

If possible, I'd recommend finding the resumer, doing a type assertion and then injecting the mock testing function into the test. The jobs.Registry struct has a function `GetResumerForClaimedJob` which could help get a direct handle to the resumer in question. Not sure if this comment is totally clear, lmk if it makes sense
</blockquote></details>

I'm a little confused about the examples in the links - aren't they just looking for the job id in the jobs table to see if it's running? For this test I don't think we want to mock the entire resumer, just the update logic portion (i.e. what occurs in every loop). There's an alternative way to inject this with testing knobs but it seemed a little overkill to introduce another set of testing knobs to the system, which are also evaluated during runtime, when we could just mock the update logic upfront - what are your thoughts here? I'll dig around a little to see if there are other methods of mocking job executions more granularly. Open to more suggestions here as well.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67mkBSCUtx2cCuvdo-:-O67yQmxDd55BZdMLoGt:b7kwia6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L36)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Will this be used outside of tests? If not, I recommend moving it to the test package. There it will neither show up in the package namespace, nor the final cockroach binary
</blockquote></details>

No it'll only be used for testing. We'll need to export the `updateJobExecFn` var if we move this fn to the testing pkg which we'd then just able to set directly in the test.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67qoVN5VHEp4EwPI0D:-O67yNJs2H0wLRUFN9EH:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L88)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

[this call to timer.Stop can be safely removed](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/timer.go#L44)

> Note that unlike the standard library's Timer type, this Timer will
> not begin counting down until Reset is called for the first time
</blockquote></details>

Nice, done.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67uWeJB7rJzYrX0Z2r:-O67yFmxCNA3fMh3agZF:b-l7ynih) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L92)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

One question is what happens if the user enables the automatic updates and sets the duration to zero? If it causes the server to spin, it might be worth guarding against that use case.
</blockquote></details>

Good call - let's enforce a conservative minimum of 1 minute for now. Added as a validator, lmk if you think the min should be increased.


<!-- Sent from Reviewable.io -->

2024-09-09 17:19 UTC, angles-n-daemons approved these changes
nice looks good to me
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-:-O6Mmyra1l8f8qY2p3a4:b-xxuo9o)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67n1t28BB-2W8Qsw5B:-O6MlbiW-sFOqNA14Oud:b-rdgvbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L31)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I'm a little confused about the examples in the links - aren't they just looking for the job id in the jobs table to see if it's running? For this test I don't think we want to mock the entire resumer, just the update logic portion (i.e. what occurs in every loop). There's an alternative way to inject this with testing knobs but it seemed a little overkill to introduce another set of testing knobs to the system, which are also evaluated during runtime, when we could just mock the update logic upfront - what are your thoughts here? I'll dig around a little to see if there are other methods of mocking job executions more granularly. Open to more suggestions here as well.
</blockquote></details>

Ah, I think where I started was kind of confusing. Yeah I was thinking something along the lines of what you described by the testing knobs. Something to the effect of:

```go
type tableMetadataUpdateJobResumer struct {
    job * jobs.Job
    updateFn func(context.Context, isql.Executor) error
}
```

You could use the jobId to get a handle to the resumer (so you could patch the updateFn). Thinking about this more though, it seems like the timing would make it tricky. Consider this comment resolved
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67uWeJB7rJzYrX0Z2r:-O6MmoTx3l_it3DJKoX6:b-so569q) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L92)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Good call - let's enforce a conservative minimum of 1 minute for now. Added as a validator, lmk if you think the min should be increased.
</blockquote></details>

That sounds perfect to me


<!-- Sent from Reviewable.io -->

2024-09-09 17:27 UTC, dhartunian reviewed
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @kyle-a-wong, and @xinhaoz)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MMys7CDKZySCOkGhW):*
nit `UPDATE`
___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MMtRf3DM8v7IiZ97u):*
nit: `control`.
___
*[`pkg/sql/tablemetadatacache/cluster_settings.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67lYA13u3qtJw40JTN:-O6MNCxo1FTxafqa6jjn:b-hmp61s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/cluster_settings.go#L23)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Renamed.
</blockquote></details>

Relatedly, can we reconsider these cluster setting names? I think creating a namespace for this stuff would be nice, maybe `obs.` as a prefix, or even putting them under `sql.stats.` might be better. Having `tablemetadata` at the top level feels messy.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67qoVN5VHEp4EwPI0D:-O6MOOU9-4gkdg8pFMV7:b-3198p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L88)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Nice, done.
</blockquote></details>

I don't see this change in the latest diff.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MoDjT8nqimxcU9iIk:-O6MoDjT8nqimxcU9iIl:bu7tqyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L107)):*
> ```Go
> 
> 		// Run table metadata update job.
> 		log.Infof(ctx, "running table metadata update job")
> ```

take it or leave it, but could we log which signal told the job to run?
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MO3uHC7vxB_YcGXoM:-O6MO3uHC7vxB_YcGXoN:b27nkv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe20718691936646f15131b096c334fcc865c9a4/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L74)):*
> ```Go
> 	// Register callbacks to signal the job to reset the timer when timer related settings change.
> 	scheduleSettingsCh := make(chan struct{})
> 	tableMetadataCacheAutoUpdatesEnabled.SetOnChange(&execCtx.ExecCfg().Settings.SV, func(_ context.Context) {
> ```

is it possible for `Resume` to be run twice on a node even though this is a "forever" job? that would register the callbacks multiple times. I guess that might be fine since `scheduleSettingsCh` would be different.


<!-- Sent from Reviewable.io -->

2024-09-11 15:14 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MMys7CDKZySCOkGhW):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit `UPDATE`
</blockquote></details>

Done.
___
*[`-- commits` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MMtRf3DM8v7IiZ97u):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: `control`.
</blockquote></details>

Done.
___
*[`pkg/sql/tablemetadatacache/cluster_settings.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67lYA13u3qtJw40JTN:-O6SSoeN3aP4pgrbAzAg:b-bgsgqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/cluster_settings.go#L23)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Relatedly, can we reconsider these cluster setting names? I think creating a namespace for this stuff would be nice, maybe `obs.` as a prefix, or even putting them under `sql.stats.` might be better. Having `tablemetadata` at the top level feels messy.
</blockquote></details>

SGTM, added `obs` prefix for now!
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67n1t28BB-2W8Qsw5B:-O6STJbREJkgrTPlDW7s:b4mg9ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L31)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Ah, I think where I started was kind of confusing. Yeah I was thinking something along the lines of what you described by the testing knobs. Something to the effect of:

```go
type tableMetadataUpdateJobResumer struct {
    job * jobs.Job
    updateFn func(context.Context, isql.Executor) error
}
```

You could use the jobId to get a handle to the resumer (so you could patch the updateFn). Thinking about this more though, it seems like the timing would make it tricky. Consider this comment resolved
</blockquote></details>

Ahh gotcha. I'll leave this for now and we can introduce it as a testing knob later if it's more well-suited.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67qoVN5VHEp4EwPI0D:-O6SVD34CO8N5dtHE59X:b-nvftkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L88)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I don't see this change in the latest diff.
</blockquote></details>

Done for real.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MoDjT8nqimxcU9iIk:-O6SVIIw8MFj4JChO5GM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L107)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

take it or leave it, but could we log which signal told the job to run?
</blockquote></details>

Done.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6MO3uHC7vxB_YcGXoM:-O6STPwOBj-uts9LK79z:b-3h1x6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe20718691936646f15131b096c334fcc865c9a4/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L74)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is it possible for `Resume` to be run twice on a node even though this is a "forever" job? that would register the callbacks multiple times. I guess that might be fine since `scheduleSettingsCh` would be different.
</blockquote></details>

Yeah I was thinking about this as well. I'm not sure under what circumstances, or if it's even possible that, a job may be abandoned by a node and then picked up again by the same node. In the end I thought it was alright since as you mentioned the scheduleSettinsCh would be different. I also found that this was being done in the span config reconciliation forever job - https://github.com/cockroachdb/cockroach/blob/e9a6d3d7c935dd347a4254729edf2db8c764dcbf/pkg/spanconfig/spanconfigjob/job.go#L130.


<!-- Sent from Reviewable.io -->

2024-09-13 15:43 UTC, kyle-a-wong reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67mkBSCUtx2cCuvdo-:-O6g12WC6UcX5K4dzX9M:b7845g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L36)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

No it'll only be used for testing. We'll need to export the `updateJobExecFn` var if we move this fn to the testing pkg which we'd then just able to set directly in the test.
</blockquote></details>

I think instead of us defining this custom mocking function, we should use `testutils.TestingHook`. `updateJobExecFn` would have to be updated to be public, but then you can do the following in your test below:

```
defer testutils.TestingHook(&tablemetadatacache.UpdateJobExecFn,
  func(ctx context.Context, ie isql.Executor) error {
     // mock implementation
  })

```


<!-- Sent from Reviewable.io -->

2024-09-13 15:58 UTC, kyle-a-wong requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6g41P2AwsnYrwTAI0_:-O6g41P2AwsnYrwTAI0a:buz9q5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15f7182257ef98224d28db33608ab949a16db56/pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go#L177)):*
> ```Go
> 		conn.Exec(t, `SET CLUSTER SETTING obs.tablemetadata.automatic_updates.enabled = f`)
> 		initialCount := getMockCallCount()
> 		err := waitForJobRuns(1, 200*time.Millisecond)
> ```

Do you think you should also set the `TableMetadataCacheValidDuration` value to be relatively low to ensure that there are no automatic updates. If a bug is introduced where automatic_upates isn't respected, but the cache valid duration is, It could be the case that the default time (20m) hasn't elapsed but it is still doing automatic updates.



_Code quote:_
```Go
		conn.Exec(t, `SET CLUSTER SETTING obs.tablemetadata.automatic_updates.enabled = f`)
		initialCount := getMockCallCount()
		err := waitForJobRuns(1, 200*time.Millisecond)
```
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go` line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6g4_WF3OvYJ7x_6FEC:-O6g4_WF3OvYJ7x_6FED:b-kmji9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15f7182257ef98224d28db33608ab949a16db56/pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go#L187)):*
> ```Go
> 		for i := 1; i < len(mockCalls); i++ {
> 			timeBetweenCalls := mockCalls[i].Sub(mockCalls[i-1])
> 			require.GreaterOrEqual(t, timeBetweenCalls, 50*time.Millisecond,
> ```

I'm not sure if it makes sense for these assertions to be in a separate t.Run(). It isn't inherently obvious that if this subtest fails, it's actually failing due to code running in `"AutomaticUpdatesEnabled"`


<!-- Sent from Reviewable.io -->

2024-09-13 16:03 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons and @dhartunian)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O67mkBSCUtx2cCuvdo-:-O6g3g4IArf38s1N3qDY:be4l1d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b473783c761e3f7f48faf565a2e766f051ca7b8/pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go#L36)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

I think instead of us defining this custom mocking function, we should use `testutils.TestingHook`. `updateJobExecFn` would have to be updated to be public, but then you can do the following in your test below:

```
defer testutils.TestingHook(&tablemetadatacache.UpdateJobExecFn,
  func(ctx context.Context, ie isql.Executor) error {
     // mock implementation
  })

```
</blockquote></details>

Ooh, nice find - done. Let's just get rid of this separate testing package for now I think it was not necessary to split and removing it gets rid of some unnecessary pkg exports.


<!-- Sent from Reviewable.io -->

2024-09-13 16:07 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6g41P2AwsnYrwTAI0_:-O6g7DsKCtSvifDWxXmb:bbj816q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15f7182257ef98224d28db33608ab949a16db56/pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go#L177)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Do you think you should also set the `TableMetadataCacheValidDuration` value to be relatively low to ensure that there are no automatic updates. If a bug is introduced where automatic_upates isn't respected, but the cache valid duration is, It could be the case that the default time (20m) hasn't elapsed but it is still doing automatic updates.
</blockquote></details>

The validity duration should still have the previously set short value of 50ms. Copied it over to this subtest too in case code changes over there.
___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go` line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6g4_WF3OvYJ7x_6FEC:-O6g7JGP1qD2JHgmgNlX:b7t3kxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15f7182257ef98224d28db33608ab949a16db56/pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go#L187)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

I'm not sure if it makes sense for these assertions to be in a separate t.Run(). It isn't inherently obvious that if this subtest fails, it's actually failing due to code running in `"AutomaticUpdatesEnabled"`
</blockquote></details>

Merged.


<!-- Sent from Reviewable.io -->

2024-09-13 16:11 UTC, kyle-a-wong approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130198)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/130198#-O6g41P2AwsnYrwTAI0_:-O6g85-L1QZc5WmoIbbw:baa3s7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a15f7182257ef98224d28db33608ab949a16db56/pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go#L177)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

The validity duration should still have the previously set short value of 50ms. Copied it over to this subtest too in case code changes over there.
</blockquote></details>

Cool thanks! One thing i forgot to mention was that if you run this subtest individually, it wouldn't have the previous subtest's settings, resulting in the situation i mentioned above. 


<!-- Sent from Reviewable.io -->

2024-09-13 17:01 UTC, xinhaoz commented
TFTR!
bors r+

2024-09-13 17:36 UTC, merged