catalog/lease: clean up orphaned session based leases
cockroachdb/cockroach pull request #130563
Opened 2024-09-12 13:53 UTC by fqazi

Previously, our logic for cleaning up orphaned leases relied on a node starting up with the same SQL instance ID, which would trigger it to delete its previously owned rows. This works fine on-premises where the SQL instance IDs are stable, but on serverless, these may change. If an excessive buildup of expired leases occurs, schema change wait operations may start failing because our session cache can only track up to 1024 dead sessions. This will cause IsAlive checks for SQL sessions to incorrectly identify sessions as live due to cache eviction. To address this, this patch updates the CRDB start-up logic to delete any dead sessions from the system.lease table. This job runs in the background and performs liveness checks synchronously to avoid cache issues.

Fixes: #130529

Release note (bug fix): serverless clusters may not be able to finalize to newer releases if more than 1024 sessions exist inside the system.lease table.

2024-09-12 13:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/130563)
<!-- Reviewable:end -->

2024-09-18 20:19 UTC, rafiss reviewed
thanks for adding this! i had some questions about the potential impact this could have

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-:-O75kn9J1XxSUoD1Lmcq:b921rgz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/lease.go` line 1916 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-O75jWqJE7iagAzIRN_D:-O75jWqJE7iagAzIRN_E:b-3t8kjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8530db40e1423e7cc259343817ba9347c212dcb2/pkg/sql/catalog/lease/lease.go#L1916)):*
> ```Go
> 	// Get a list of distinct session IDs that exist in the system.lease
> 	// table.
> 	const DistinctSessionQuery = `SELECT DISTINCT(session_id) FROM system.lease`
> ```

should we be worried about this doing a full table scan? if this task is getting run periodically, we could add a small `LIMIT` on this, like even something between 1-10. eventually, all of the stale sessions would get picked up.
___
*[`pkg/sql/catalog/lease/lease.go` line 1958 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-O75kCCf5bFN_fFHzXM-:-O75kCCf5bFN_fFHzXM0:b-k1f8mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8530db40e1423e7cc259343817ba9347c212dcb2/pkg/sql/catalog/lease/lease.go#L1958)):*
> ```Go
> 	ctxGrp.GoCtx(func(ctx context.Context) error {
> 		// Receive orphaned sessions and delete rows related to them.
> 		const DeleteOrphanedSessions = `DELETE FROM system.lease WHERE session_id=$1`
> ```

this also will do a full table scan.

would it be worth making an index for session ID? that has its own complications so i don't know if it's worth it.

even without the full table scan, it could still end up being a large delete. should we do it in batches?


<!-- Sent from Reviewable.io -->

2024-09-19 18:11 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/lease/lease.go` line 1916 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-O75jWqJE7iagAzIRN_D:-O79oMxf7uWVaDHuQ5Lt:b5okqet) ([raw file](https://github.com/cockroachdb/cockroach/blob/8530db40e1423e7cc259343817ba9347c212dcb2/pkg/sql/catalog/lease/lease.go#L1916)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should we be worried about this doing a full table scan? if this task is getting run periodically, we could add a small `LIMIT` on this, like even something between 1-10. eventually, all of the stale sessions would get picked up.
</blockquote></details>

This task is only run at startup only, so its not periodic at least. I changed the logic to be per-region and use an AOST query, which should reduce risk of contention / retries for the scan. The distinct part we can't really limit, since we need to know which things are "alive".  Unless we add a builtin that is uncached for liveness.
___
*[`pkg/sql/catalog/lease/lease.go` line 1958 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-O75kCCf5bFN_fFHzXM-:-O7ARvxa7Wz3e6hpRQ7A:b8n7per) ([raw file](https://github.com/cockroachdb/cockroach/blob/8530db40e1423e7cc259343817ba9347c212dcb2/pkg/sql/catalog/lease/lease.go#L1958)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this also will do a full table scan.

would it be worth making an index for session ID? that has its own complications so i don't know if it's worth it.

even without the full table scan, it could still end up being a large delete. should we do it in batches?
</blockquote></details>

I changed this to be batched at a 100 rows at a time. Its still sadly a full table scan.

Adding indexes here would suck because it would need another complex migration and extra code to write KVs manually :scream: 


<!-- Sent from Reviewable.io -->

2024-11-26 22:43 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130563)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/lease.go` line 1958 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-O75kCCf5bFN_fFHzXM-:-OCebYYHDtxID0HIX5-4:bxe1wsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8530db40e1423e7cc259343817ba9347c212dcb2/pkg/sql/catalog/lease/lease.go#L1958)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I changed this to be batched at a 100 rows at a time. Its still sadly a full table scan.

Adding indexes here would suck because it would need another complex migration and extra code to write KVs manually :scream:
</blockquote></details>

seems like the batch size  change was missed, it's still deleting everything at once
___
*[`pkg/sql/catalog/lease/lease.go` line 1921 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-OCebVMT5WBVhFywpY87:-OCebVMT5WBVhFywpY88:b-kdz1wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db4f0a2caf359a366fa1a3e01669ed67089bc05/pkg/sql/catalog/lease/lease.go#L1921)):*
> ```Go
> 		"SELECT EXISTS (SELECT * FROM [SHOW REGIONS FROM DATABASE system])")
> 	if err != nil {
> 		log.Warningf(ctx, "unable to query if system database is multi-region: %s", err)
> ```

nit: use `%v` for the error
___
*[`pkg/sql/catalog/lease/lease.go` line 1951 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-OCebHYP9KrDsGDfHVaZ:-OCebHYP9KrDsGDfHVa_:b-4aefwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db4f0a2caf359a366fa1a3e01669ed67089bc05/pkg/sql/catalog/lease/lease.go#L1951)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Warningf(ctx, "unable to read session IDs for oprhaned leases: %s", err)
> ```

nit: use `%v` for the err

nit: fix "oprhaned" -> "orphaned"
___
*[`pkg/sql/catalog/lease/lease.go` line 1956 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-OCebmSc6ZLIx3K5zWtw:-OCebmSc6ZLIx3K5zWtx:bn4e810) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db4f0a2caf359a366fa1a3e01669ed67089bc05/pkg/sql/catalog/lease/lease.go#L1956)):*
> ```Go
> 
> 	cleanupCh := make(chan sqlliveness.SessionID)
> 	ctxGrp := ctxgroup.WithContext(ctx)
> ```

nit: do we need a `stopper.WithCancelOnQuiesce(ctx)` for this ctx? or we already good since we have `RunAsyncTask` below?
___
*[`pkg/sql/catalog/lease/lease.go` line 1965 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-OCeaxUA-xie0prECyDf:-OCeaxUA-xie0prECyDg:bp32fil) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db4f0a2caf359a366fa1a3e01669ed67089bc05/pkg/sql/catalog/lease/lease.go#L1965)):*
> ```Go
> 			alive, err := m.storage.livenessProvider.BlockingReader().IsAlive(ctx, session)
> 			if err != nil {
> 				log.Warningf(ctx, "failed to get liveness for session: %s with:  %s", session.String(), err)
> ```

nit: remove `.String()` and use `%v` for the error

```
log.Warningf(ctx, "failed to get liveness for session: %s with: %v", session, err)
```
___
*[`pkg/sql/catalog/lease/lease.go` line 2003 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130563#-OCebN3y28UB7VxAvqBE:-OCebN3y28UB7VxAvqBF:b-kdz1wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8db4f0a2caf359a366fa1a3e01669ed67089bc05/pkg/sql/catalog/lease/lease.go#L2003)):*
> ```Go
> 	})
> 	if err := ctxGrp.Wait(); err != nil {
> 		log.Warningf(ctx, "failed to delete leases for expired sessions: %s", err)
> ```

nit: use `%v` for the error


<!-- Sent from Reviewable.io -->

2025-02-06 20:36 UTC, closed without merging