cli: CLI prints out previous error message when executing a quit command
cockroachdb/cockroach pull request #130736
Opened 2024-09-14 08:01 UTC by hanpen24

Previously, when executing the quit command in the CLI, the last SQL error message would be displayed again. 
This was inadequate because there is no need to show a previous SQL error when executing a quit command. 
To address this, this patch modifies the behavior so that when commands like quit or \q are executed, any previous error messages are cleared.

Fixes: #85613

Release note (bug fix):CLI prints out previous error message when executing a quit command.

2024-09-14 08:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/130736)
<!-- Reviewable:end -->

2024-09-14 14:18 UTC, rafiss approved these changes
thanks for your contribution!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130736#-:-O6ktat--m2V-JGd5R2n:bvdps3i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-09-14 16:35 UTC, rafiss requested changes
it seems that this change caused an existing test to fail, so this may not be the right solution.

https://github.com/cockroachdb/cockroach/blob/5d9f6cb7f4a0a272af26c6c560d8debc7c2b8395/pkg/cli/interactive_tests/test_last_statement.tcl#L14-L23

The test expects to see `hello 1` in the output (with `1` being the exit code from the CLI), but it doesn't see that.

2024-09-15 01:29 UTC, hanpen24 commented
Thank you for pointing that out. I'll check it.

2024-10-08 09:55 UTC, hanpen24 commented
@rafiss 
I apologize for the delayed response.

In this test case, we expect that even when the shell is explicitly exited with \q, the exit status of 1 from the previous command will be displayed. However, if the user intentionally exits the shell with \q, it should be considered a normal exit, and the exit status should be 0.

Therefore, I believe the expected result in the test case should be revised to "hello 0."

2024-10-10 15:29 UTC, rafiss commented
@hanpen24 Thank you for investigating the test. I agree with your reasoning - so let's adjust the test to expect a 0 exit code (and change any related comments in the test).

2024-10-13 14:24 UTC, hanpen24 commented
@rafiss 
Thank you for your feedback! I have updated the test to expect a 0 exit code as discussed, and I have also modified the relevant comments in the test. Please let me know if there are any further adjustments needed.

2024-10-14 13:23 UTC, rafiss approved these changes
thank you for your contribution!

bors r+

2024-10-14 13:51 UTC, merged