ui: add AlertBar component
cockroachdb/cockroach pull request #130829
Opened 2024-09-16 19:42 UTC by dhartunian

This component will be used to signal throttling notifications for free and unlicensed clusters.

This commit introduces the component and provides some configurability for rendering a few different kinds of messages that are reflected in the storybook examples.

It's likely the props interface will change once the backend API becomes available.

Resolves: CRDB-40935
Release Note: None

2024-09-16 19:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/130829)
<!-- Reviewable:end -->

2024-09-16 19:45 UTC, dhartunian commented
Example renders:
<img width="1768" alt="Screenshot 2024-09-16 at 15 44 51" src="https://github.com/user-attachments/assets/e3c2b558-4295-4198-a839-d3a4bb526047">
<img width="1771" alt="Screenshot 2024-09-16 at 15 44 59" src="https://github.com/user-attachments/assets/26c028aa-a5c4-4fe2-9984-c242b9ea7396">
<img width="1766" alt="Screenshot 2024-09-16 at 15 45 08" src="https://github.com/user-attachments/assets/dfde0cdf-74d8-43d2-a83b-c851faba3eb3">
<img width="1767" alt="Screenshot 2024-09-16 at 15 45 17" src="https://github.com/user-attachments/assets/baa76b8b-8ef0-4319-8fc6-cb08a2dcca18">
<img width="1768" alt="Screenshot 2024-09-16 at 15 45 25" src="https://github.com/user-attachments/assets/15b466cf-fce9-4741-964b-7e25ee6ba0b5">
<img width="1765" alt="Screenshot 2024-09-16 at 15 45 35" src="https://github.com/user-attachments/assets/c4e96007-24b4-48ed-ae3f-4856105c9ebe">

2024-09-17 15:57 UTC, angles-n-daemons requested changes
couple of quick questions, no changes required

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-:-O7-gu1WE9ih3q6v2Rnj:b9m3i6z)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-O7-fzUJ6grmnmyuTKho:-O7-fzUJ6grmnmyuTKhp:bi5e15h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf9c4eedac0e11bd480401a47aa4a1040808854/pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx#L19)):*
> ```XML
> import styles from "./alertBar.module.styl";
> 
> type License = "Enterprise" | "Free" | "None";
> ```

Are we able to pull protobuf definitions here?
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-O7-a9rH9Mu8Q5jS3J_c:-O7-a9rH9Mu8Q5jS3J_d:bdk2ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf9c4eedac0e11bd480401a47aa4a1040808854/pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx#L41)):*
> ```XML
>     />
>   ))
>   // .add(
> ```

should these be committed as comments?


<!-- Sent from Reviewable.io -->

2024-09-23 19:27 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130829)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons)

___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-O7-fzUJ6grmnmyuTKho:-O7VLLLB1EtOdvHnSr2r:b-86s10z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf9c4eedac0e11bd480401a47aa4a1040808854/pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx#L19)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Are we able to pull protobuf definitions here?
</blockquote></details>

No because the license proto is not included in the frontend definitions.
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-O7-a9rH9Mu8Q5jS3J_c:-O7VLR83Cb1VYyM0uuMO:brlf26s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebf9c4eedac0e11bd480401a47aa4a1040808854/pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx#L41)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

should these be committed as comments?
</blockquote></details>

Removed :)


<!-- Sent from Reviewable.io -->

2024-09-23 20:09 UTC, angles-n-daemons approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130829#-:-O7VV71WARY2d7byOeRh:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-09-23 21:38 UTC, dhartunian commented
TFTR!

bors r+

2024-09-23 22:04 UTC, merged