sql: support SHOW TYPES WITH COMMENT
cockroachdb/cockroach pull request #131183
Opened 2024-09-23 10:09 UTC by sambhav-jain-16

Previously SHOW TYPES WITH COMMENT were missing
for show tables, this is inconsistent with show databases and show tables. The code changes in this PR make show types work similar to show tables and show databases.

Release note (sql change): Added SHOW TYPES WITH COMMENT functionality similar to show schemas, show databases and show tables;

Fixes: https://github.com/cockroachdb/cockroach/issues/126009

2024-09-23 10:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131183)
<!-- Reviewable:end -->

2024-10-02 19:08 UTC, Dedej-Bergin commented
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8Dc-Ms6x9c1x2DVA3L:b683s6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
> ```Go
> 				) c
> 			ON
> 				 	types.oid::text like '%%' || c.object_id::text`, catalogkeys.TypeCommentType)
> ```

So to types.oid we always add 100000. We cannot use like here as when we are matching ids we need to be exact.  Lets subtract 100000 from types.oid and then do an exact match with c.object_id.


<!-- Sent from Reviewable.io -->

2024-10-02 19:13 UTC, Dedej-Bergin requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @sambhav-jain-16)



<!-- Sent from Reviewable.io -->

2024-10-02 19:29 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8Dh3qO3ocNnvrguMPZ:b6bdijn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

So to types.oid we always add 100000. We cannot use like here as when we are matching ids we need to be exact.  Lets subtract 100000 from types.oid and then do an exact match with c.object_id.
</blockquote></details>

I have updated this piece of code to resolve the above commnet


<!-- Sent from Reviewable.io -->

2024-10-02 20:50 UTC, Dedej-Bergin commented
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8DyvuJ8BM-19qci96m:bdxmk7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

I have updated this piece of code to resolve the above commnet
</blockquote></details>

Great thank you. There is one more thing that I just found out. We cannot use system.comments since it requires strict user permissions.  I know delegateShowSchemas and delegateShowDatabases uses system.comments but that is actually a bug.

The right table to use is pg_catalog.pg_description it also has the oid that we want for the join so we don't actually need to do the -100000 in this case.

![Screenshot 2024-10-02 at 4.49.11 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/8R6KmyHiXr22U9x1E2LlMVSF/Screenshot%202024-10-02%20at%204.49.11%E2%80%AFPM.png)

We should be ready to approve after this change, thanks for your contribution @sambhav-jain-16 !


<!-- Sent from Reviewable.io -->

2024-10-03 05:15 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8FnBNZ8JKMeq5BHdbZ:buhr2b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Great thank you. There is one more thing that I just found out. We cannot use system.comments since it requires strict user permissions.  I know delegateShowSchemas and delegateShowDatabases uses system.comments but that is actually a bug.

The right table to use is pg_catalog.pg_description it also has the oid that we want for the join so we don't actually need to do the -100000 in this case.

![Screenshot 2024-10-02 at 4.49.11 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/8R6KmyHiXr22U9x1E2LlMVSF/Screenshot%202024-10-02%20at%204.49.11%E2%80%AFPM.png)

We should be ready to approve after this change, thanks for your contribution @sambhav-jain-16 !
</blockquote></details>

Actually, I just tried this and for some reason I'm getting 2 comments, can you check if you are getting the same thing?
```
  schema |      name       |   owner   |                                             comment
---------+-----------------+-----------+--------------------------------------------------------------------------------------------------
  public | roach_dwellings | roachprod | First-CRDB-comment-on-types
  public | roach_dwellings | roachprod | Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.
  public | roach_legs      | roachprod | Second-CRDB-comment-on-types
  public | roach_legs      | roachprod | Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.
(4 rows)
```


<!-- Sent from Reviewable.io -->

2024-10-03 05:18 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8FnstI2-IAl18T7yNt:buqlv7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

Actually, I just tried this and for some reason I'm getting 2 comments, can you check if you are getting the same thing?
```
  schema |      name       |   owner   |                                             comment
---------+-----------------+-----------+--------------------------------------------------------------------------------------------------
  public | roach_dwellings | roachprod | First-CRDB-comment-on-types
  public | roach_dwellings | roachprod | Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.
  public | roach_legs      | roachprod | Second-CRDB-comment-on-types
  public | roach_legs      | roachprod | Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.
(4 rows)
```
</blockquote></details>

Looks like `pg_description` table has a default comment for each type created. Can you check when filtering on the exact oid in the table for your type?


<!-- Sent from Reviewable.io -->

2024-10-03 16:11 UTC, Dedej-Bergin commented
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8I8XsSAuvAAeRVtA7q:bc2hgbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

Looks like `pg_description` table has a default comment for each type created. Can you check when filtering on the exact oid in the table for your type?
</blockquote></details>

Can you send me the exact repro steps that you used with the output for it?  Thanks.


<!-- Sent from Reviewable.io -->

2024-10-04 05:05 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8KuSJ9A0MS77wHz9oF:b-cblpwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Can you send me the exact repro steps that you used with the output for it?  Thanks.
</blockquote></details>

```
CREATE TYPE roach_dwellings AS ENUM ('roach_motel','roach_kitchen','roach_bathroom','roach_house');
CREATE TYPE roach_legs AS (legs INT);


COMMENT ON TYPE roach_dwellings IS 'First-CRDB-comment-on-types';

COMMENT ON TYPE roach_legs IS 'Second-CRDB-comment-on-types';


SELECT
  nsp.nspname AS schema,
  types.typname AS name,
  rl.rolname AS owner,
  comment
FROM
  defaultdb.pg_catalog.pg_type AS types
  LEFT JOIN defaultdb.pg_catalog.pg_roles AS rl on (types.typowner = rl.oid)
  JOIN defaultdb.pg_catalog.pg_namespace AS nsp ON (types.typnamespace = nsp.oid)
  LEFT JOIN
				(
					SELECT 
						objoid, description as comment
					FROM
						%[1]s.pg_catalog.pg_description
				) c
			ON
				 	(types.oid::int - 100000) = c.objoid
WHERE types.typtype IN ('e','c') AND
      types.typrelid IN (0, types.oid) AND
      nsp.nspname NOT IN ('information_schema', 'pg_catalog', 'crdb_internal', 'pg_extension')
ORDER BY (nsp.nspname, types.typname);
```


<!-- Sent from Reviewable.io -->

2024-10-04 13:56 UTC, Dedej-Bergin commented
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8MnoZjAQ52YnicWR7D:b-ep7ogp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

```
CREATE TYPE roach_dwellings AS ENUM ('roach_motel','roach_kitchen','roach_bathroom','roach_house');
CREATE TYPE roach_legs AS (legs INT);


COMMENT ON TYPE roach_dwellings IS 'First-CRDB-comment-on-types';

COMMENT ON TYPE roach_legs IS 'Second-CRDB-comment-on-types';


SELECT
  nsp.nspname AS schema,
  types.typname AS name,
  rl.rolname AS owner,
  comment
FROM
  defaultdb.pg_catalog.pg_type AS types
  LEFT JOIN defaultdb.pg_catalog.pg_roles AS rl on (types.typowner = rl.oid)
  JOIN defaultdb.pg_catalog.pg_namespace AS nsp ON (types.typnamespace = nsp.oid)
  LEFT JOIN
				(
					SELECT 
						objoid, description as comment
					FROM
						%[1]s.pg_catalog.pg_description
				) c
			ON
				 	(types.oid::int - 100000) = c.objoid
WHERE types.typtype IN ('e','c') AND
      types.typrelid IN (0, types.oid) AND
      nsp.nspname NOT IN ('information_schema', 'pg_catalog', 'crdb_internal', 'pg_extension')
ORDER BY (nsp.nspname, types.typname);
```
</blockquote></details>

Thank you for the repro steps, but can you paste the repro steps with the output as well.  You can run this on cockroach demo and run each command one by one and then copy over the commands and output to here.


<!-- Sent from Reviewable.io -->

2024-10-04 14:27 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8Muqw8-CqMzhbkUWto:br965gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thank you for the repro steps, but can you paste the repro steps with the output as well.  You can run this on cockroach demo and run each command one by one and then copy over the commands and output to here.
</blockquote></details>

Posting the repro steps with output

```
demo@127.0.0.1:26257/demoapp/movr> CREATE TYPE roach\_dwellings AS ENUM ('roach\_motel','roach\_kitchen','roach\_bathroom','roach\_house');
CREATE TYPE roach\_legs AS (legs INT);               

CREATE TYPE



Time: 5ms total (execution 5ms / network 0ms)



CREATE TYPE



Time: 3ms total (execution 3ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> COMMENT ON TYPE roach\_dwellings IS 'First-CRDB-comment-on-types';                         
COMMENT ON TYPE

Time: 4ms total (execution 4ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> COMMENT ON TYPE roach\_legs IS 'Second-CRDB-comment-on-types';

COMMENT ON TYPE

Time: 4ms total (execution 4ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> SELECT                                                                                                       
                                ->   nsp.nspname AS schema,                                                                                     
                                ->   types.typname AS name,                                                                                     
                                ->   rl.rolname AS owner,                                                                                       
                                ->   comment                                                                                                    
                                -> FROM                                                                                                         
                                ->   pg\_catalog.pg\_type AS types                                                                                
                                ->   LEFT JOIN pg\_catalog.pg\_roles AS rl on (types.typowner = rl.oid)                                           
                                ->   JOIN pg\_catalog.pg\_namespace AS nsp ON (types.typnamespace = nsp.oid)                                      
                                ->   LEFT JOIN                                                                                                  
                                ->                 (                                                                                            
                                ->                     SELECT                                                                                   
                                ->                         objoid, description as comment                                                       
                                ->                     FROM                                                                                     
                                ->                         pg\_catalog.pg\_description                                                            
                                ->                 ) c                                                                                          
                                ->             ON                                                                                               
                                ->                      (types.oid::int - 100000) = c.objoid                                                    
                                -> WHERE types.typtype IN ('e','c') AND                                                                         
                                ->       types.typrelid IN (0, types.oid) AND                                                                   
                                ->       nsp.nspname NOT IN ('information\_schema', 'pg\_catalog', 'crdb\_internal', 'pg\_extension')               
                                -> ORDER BY (nsp.nspname, types.typname);                                                                       
  schema |      name       | owner |                      comment
---------+-----------------+-------+----------------------------------------------------
  public | roach\_dwellings | demo  | First-CRDB-comment-on-types
  public | roach\_dwellings | demo  | Calculates square of the correlation coefficient.
  public | roach\_legs      | demo  | Second-CRDB-comment-on-types
  public | roach\_legs      | demo  | Calculates square of the correlation coefficient.
(4 rows)

Time: 20ms total (execution 20ms / network 0ms)
```


<!-- Sent from Reviewable.io -->

2024-10-07 14:43 UTC, Dedej-Bergin requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @sambhav-jain-16)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8bPouo8B0ysfWyJrt8:bkw7f8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

Posting the repro steps with output

```
demo@127.0.0.1:26257/demoapp/movr> CREATE TYPE roach\_dwellings AS ENUM ('roach\_motel','roach\_kitchen','roach\_bathroom','roach\_house');
CREATE TYPE roach\_legs AS (legs INT);               

CREATE TYPE



Time: 5ms total (execution 5ms / network 0ms)



CREATE TYPE



Time: 3ms total (execution 3ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> COMMENT ON TYPE roach\_dwellings IS 'First-CRDB-comment-on-types';                         
COMMENT ON TYPE

Time: 4ms total (execution 4ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> COMMENT ON TYPE roach\_legs IS 'Second-CRDB-comment-on-types';

COMMENT ON TYPE

Time: 4ms total (execution 4ms / network 0ms)
```

```
demo@127.0.0.1:26257/demoapp/movr> SELECT                                                                                                       
                                ->   nsp.nspname AS schema,                                                                                     
                                ->   types.typname AS name,                                                                                     
                                ->   rl.rolname AS owner,                                                                                       
                                ->   comment                                                                                                    
                                -> FROM                                                                                                         
                                ->   pg\_catalog.pg\_type AS types                                                                                
                                ->   LEFT JOIN pg\_catalog.pg\_roles AS rl on (types.typowner = rl.oid)                                           
                                ->   JOIN pg\_catalog.pg\_namespace AS nsp ON (types.typnamespace = nsp.oid)                                      
                                ->   LEFT JOIN                                                                                                  
                                ->                 (                                                                                            
                                ->                     SELECT                                                                                   
                                ->                         objoid, description as comment                                                       
                                ->                     FROM                                                                                     
                                ->                         pg\_catalog.pg\_description                                                            
                                ->                 ) c                                                                                          
                                ->             ON                                                                                               
                                ->                      (types.oid::int - 100000) = c.objoid                                                    
                                -> WHERE types.typtype IN ('e','c') AND                                                                         
                                ->       types.typrelid IN (0, types.oid) AND                                                                   
                                ->       nsp.nspname NOT IN ('information\_schema', 'pg\_catalog', 'crdb\_internal', 'pg\_extension')               
                                -> ORDER BY (nsp.nspname, types.typname);                                                                       
  schema |      name       | owner |                      comment
---------+-----------------+-------+----------------------------------------------------
  public | roach\_dwellings | demo  | First-CRDB-comment-on-types
  public | roach\_dwellings | demo  | Calculates square of the correlation coefficient.
  public | roach\_legs      | demo  | Second-CRDB-comment-on-types
  public | roach\_legs      | demo  | Calculates square of the correlation coefficient.
(4 rows)

Time: 20ms total (execution 20ms / network 0ms)
```
</blockquote></details>

Thank you for typing out the commands and output on here @sambhav-jain-16 !  

So I think the issue may be here
 ```
(types.oid::int - 100000) = c.objoid
```

We no longer need the -100000 anymore, because we are no longer using the system.comments table.


<!-- Sent from Reviewable.io -->

2024-10-08 17:36 UTC, Dedej-Bergin commented
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8hBYJ1BONmUJ02gqC5:bh6jeos) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thank you for typing out the commands and output on here @sambhav-jain-16 !  

So I think the issue may be here
 ```
(types.oid::int - 100000) = c.objoid
```

We no longer need the -100000 anymore, because we are no longer using the system.comments table.
</blockquote></details>

Hi @sambhav-jain-16 ,

So we need to also check for classoid, which could look something like this:



_Code snippet:_
```Go
        commentColumn, commentJoin := ``, ``
        if n.WithComment {
                commentColumn = `, comment`
                commentJoin = fmt.Sprintf(`
                        LEFT JOIN
                                (
                                        SELECT
                                                objoid, description as comment
                                        FROM
                                                pg_catalog.pg_description
                                        WHERE
                                                classoid = %d
                                ) c
                        ON
                                        (types.oid::int - 100000) = c.objoid`, catconstants.PgCatalogTypeTableID)
        }
```


<!-- Sent from Reviewable.io -->

2024-10-08 18:12 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8hKI0WDo8H4gp01quG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Hi @sambhav-jain-16 ,

So we need to also check for classoid, which could look something like this:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-08 18:22 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @michae2)

___
*[`pkg/sql/delegate/show_types.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-O8Dc-Ms6x9c1x2DVA3K:-O8hMYg18ucx9oBDjWca:bnd1ake) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0ac62f0561ac864310c81980e795f5f0c3b5b7f/pkg/sql/delegate/show_types.go#L38)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Great, but very minor last change, I think we need a %s.pg_catalog.pg_description for the database name, so this would be the exact code.
</blockquote></details>

Oops, missed this. 
Thanks for pointing out !


<!-- Sent from Reviewable.io -->

2024-10-08 18:43 UTC, Dedej-Bergin approved these changes
Thank you for your contribution @sambhav-jain-16! To get this merged just run bors r+ in a separate line.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131183#-:-O8hQxhLDCtgDncgmkUS:b-jmvyzw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2)



<!-- Sent from Reviewable.io -->

2024-10-08 18:54 UTC, sambhav-jain-16 commented
TFTR!

bors r+

2024-10-08 19:26 UTC, merged