sql: internal error with BUCKET_COUNT = NULL
cockroachdb/cockroach pull request #131212
Opened 2024-09-23 15:34 UTC by vidit-bhat

Previously, the `EvalShardBucketCount` function did not properly handle the case where `BUCKET_COUNT` was set to `NULL`, causing evaluation errors. This change adds explicit handling for `NULL` values, ensuring that `BUCKET_COUNT` cannot be set to `NULL` and returns an appropriate error message.

Epic: none
Fixes: #130353
Release note: None

2024-09-23 15:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131212)
<!-- Reviewable:end -->

2024-09-25 18:21 UTC, spilchen requested changes
Looks good. I just had a comment on the error message used.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-:-O7ePU3b3V4KmpGc-VPG:b-550bjy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @vidit-bhat)

___
*[`pkg/sql/catalog/tabledesc/table.go` line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-O7eOgLqAkCqtk4ZxnLW:-O7eOgLqAkCqtk4ZxnLX:b-qvzkjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5e3cd72823021f4dcd8c3f482cc1a14b586fe7/pkg/sql/catalog/tabledesc/table.go#L290)):*
> ```Go
> 		// Check if shardBuckets is NULL
> 		if shardBuckets == tree.DNull {
> 			return 0, pgerror.Newf(pgcode.InvalidParameterValue, `"BUCKET_COUNT" cannot be NULL`)
> ```

Can we use `invalidBucketCountMsg` as the error message? I believe it still makes sense even when the count is NULL.


<!-- Sent from Reviewable.io -->

2024-09-25 19:57 UTC, vidit-bhat commented
> Looks good. I just had a comment on the error message used.
> 
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-:-O7ePU3b3V4KmpGc-VPG:b-550bjy)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vidit-bhat)
> 
> _[`pkg/sql/catalog/tabledesc/table.go` line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-O7eOgLqAkCqtk4ZxnLW:-O7eOgLqAkCqtk4ZxnLX:b-qvzkjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff5e3cd72823021f4dcd8c3f482cc1a14b586fe7/pkg/sql/catalog/tabledesc/table.go#L290)):_
> 
> > ```go
> > 		// Check if shardBuckets is NULL
> > 		if shardBuckets == tree.DNull {
> > 			return 0, pgerror.Newf(pgcode.InvalidParameterValue, `"BUCKET_COUNT" cannot be NULL`)
> > ```
> 
> Can we use `invalidBucketCountMsg` as the error message? I believe it still makes sense even when the count is NULL.

Done

2024-09-25 20:17 UTC, spilchen requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131212)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @vidit-bhat)

___
*[`pkg/sql/catalog/tabledesc/table.go` line 290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-O7epG-M8jazhyIYlMrg:-O7epG-M8jazhyIYlMrh:b-rtjlgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ae65ae98a2ee6a82c7908a04ec0f74e6b2a6de/pkg/sql/catalog/tabledesc/table.go#L290)):*
> ```Go
> 		// Check if shardBuckets is NULL
> 		if shardBuckets == tree.DNull {
> 			return 0, pgerror.Newf(pgcode.InvalidParameterValue, invalidBucketCountMsg, buckets)
> ```

Can we pass in "NULL" for the 3rd parm? I'm hoping the error message will say we passed in NULL if we do.



_Suggestion:_
```Go
return 0, pgerror.Newf(pgcode.InvalidParameterValue, invalidBucketCountMsg, "NULL")
```


<!-- Sent from Reviewable.io -->

2024-09-25 20:57 UTC, vidit-bhat commented
> > Reviewed 2 of 2 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131212)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vidit-bhat)
> 
> _[`pkg/sql/catalog/tabledesc/table.go` line 290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-O7epG-M8jazhyIYlMrg:-O7epG-M8jazhyIYlMrh:b-rtjlgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ae65ae98a2ee6a82c7908a04ec0f74e6b2a6de/pkg/sql/catalog/tabledesc/table.go#L290)):_
> 
> > ```go
> > 		// Check if shardBuckets is NULL
> > 		if shardBuckets == tree.DNull {
> > 			return 0, pgerror.Newf(pgcode.InvalidParameterValue, invalidBucketCountMsg, buckets)
> > ```
> 
> Can we pass in "NULL" for the 3rd parm? I'm hoping the error message will say we passed in NULL if we do.
> 
> _Suggestion:_
> 
> ```go
> return 0, pgerror.Newf(pgcode.InvalidParameterValue, invalidBucketCountMsg, "NULL")
> ```

Oops yes. Updated.

2024-09-25 22:16 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for contributing.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131212#-:-O7fFOp7D8tAtcRytmOI:b-b6m9p7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @vidit-bhat)



<!-- Sent from Reviewable.io -->

2024-09-26 01:42 UTC, vidit-bhat commented
TFTR!
bors r=spilchen

2024-09-26 02:13 UTC, merged

2024-09-30 15:12 UTC, rafiss commented
we should backport this fix, since older branches are affected and the issue was causing a crash

blathers backport 23.1 23.2 24.1 24.2