diagnostics: send along license information on diag report
cockroachdb/cockroach pull request #131249
Opened 2024-09-23 20:38 UTC by angles-n-daemons

diagnostics: send along license information on diag report

To support the license change in CRDB, we'll need to begin sending license information along with diagnostics reports. This change accomplishes this by making the license getter in `license_check.go` public, and attatching its OrganizationID, LicenseID, LicenseExpiry, and Environment to the outgoing payload.

This PR also moves the `LicenseTestingKnobs` from being part of the `server.TestingKnobs` to the `base.TestingKnobs` to avoid an import cycle in the utilccl tests.

Fixes: CRDB-41230
Epic: CRDB-40209

Release note: none

2024-09-23 20:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131249)
<!-- Reviewable:end -->

2024-09-24 19:42 UTC, dhartunian reviewed
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7_YH9845dZ15knw8iO:-O7_YH9845dZ15knw8iP:b-gvifjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b809e29f36e9262b82ec2baa8cb1c97f3631460/pkg/server/diagnostics/diagnostics.go#L122)):*
> ```Go
> 	q.Set("license_id", clusterInfo.LicenseID.String())
> 	q.Set("license_expiry", strconv.Itoa(int(clusterInfo.LicenseExpiry)))
> 	q.Set("environment", clusterInfo.Environment)
> ```

Are we ok with sending zero values for these when they're unset?
___
*[`pkg/server/diagnostics/reporter.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7_YMo1B18ICxjle95U:-O7_YMo1B18ICxjle95V:b-agb3hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b809e29f36e9262b82ec2baa8cb1c97f3631460/pkg/server/diagnostics/reporter.go#L401)):*
> ```Go
> 		OrganizationID:   uuid.UUID(license.OrganizationId),
> 		LicenseExpiry:    license.ValidUntilUnixSec,         // requires a context, settings, time source
> 		LicenseID:        uuid.UUID(license.OrganizationId), // requires a context, settings, time source
> ```

Can you elaborate on this comment here, it's not clear what you mean in isolation about context/settings/timesource. Feel free to insert a multi-line comment in the middle of the struct literal.


<!-- Sent from Reviewable.io -->

2024-09-24 20:33 UTC, angles-n-daemons commented
Successfully tested payload against registration service

2024-09-25 11:27 UTC, spilchen reviewed
I reviewed the changes to the license testing knobs out of curiosity. I have a few minor comments, but overall, it looks good to me.

> Reviewed 1 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-:-O7cvKwq3DlmkKNXzq0S:bmvq6lj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7ct55O4S9HC9hSpPol:-O7ct55O4S9HC9hSpPom:b-147hy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/diagnostics.go#L83)):*
> ```Go
> 	OrganizationID []byte
> 	LicenseID      []byte
> 	LicenseExpiry  int64
> ```

nit: It would be helpful to clarify the unit (e.g., seconds since epoch) in the variable name or as a comment for the reader.
___
*[`pkg/server/diagnostics/reporter.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7cs_bZ7jotiRkTiBop:-O7cs_bZ7jotiRkTiBoq:b-npe6pc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/reporter.go#L398)):*
> ```Go
> 
> 	environment := ""
> 	if license.Environment != licenseccl.License_Environment(0) {
> ```

Is the check for zero needed? I thought `License_Environment.String()` already handles that case.


<!-- Sent from Reviewable.io -->

2024-09-25 18:53 UTC, angles-n-daemons reviewed
awesome, thank you

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-:-O7eWvHM1ztKncYkuflk:bbtmovr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @spilchen, and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7_YH9845dZ15knw8iO:-O7eWpitBhPaftIhIIdT:b-ir5of5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b809e29f36e9262b82ec2baa8cb1c97f3631460/pkg/server/diagnostics/diagnostics.go#L122)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Are we ok with sending zero values for these when they're unset?
</blockquote></details>

Good question, checked with Dan and modified what we're sending across
___
*[`pkg/server/diagnostics/reporter.go` line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7_YMo1B18ICxjle95U:-O7eWgQtAaWUVjH9E2G7:b2hky23) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b809e29f36e9262b82ec2baa8cb1c97f3631460/pkg/server/diagnostics/reporter.go#L401)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you elaborate on this comment here, it's not clear what you mean in isolation about context/settings/timesource. Feel free to insert a multi-line comment in the middle of the struct literal.
</blockquote></details>

This was a leftover comment from a different way of retrieving the license ttl, removed it from this changeset
___
*[`pkg/server/diagnostics/reporter.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7cs_bZ7jotiRkTiBop:-O7eWSsO0nMW7Xx9ZL4Y:b-kpmhr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/reporter.go#L398)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is the check for zero needed? I thought `License_Environment.String()` already handles that case.
</blockquote></details>

We want the value to be an empty string, and not the stringified zero value (which is not empty)


<!-- Sent from Reviewable.io -->

2024-09-25 19:30 UTC, spilchen requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`pkg/server/diagnostics/reporter.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7cs_bZ7jotiRkTiBop:-O7ee5uw1Bb7mvIR-QIG:b-9m7lc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/reporter.go#L398)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

We want the value to be an empty string, and not the stringified zero value (which is not empty)
</blockquote></details>

Hmm, doesn't it return an empty string for 0? I think that's the `Unspecified` enum value.

`pkg/ccl/utilccl/licenseccl/license.go`
```
func (u License_Environment) String() string {
	switch u {
	case Unspecified:
		return ""
	case Production:
		return "production"
	case PreProduction:
		return "pre-production"
	case Development:
		return "development"
	default:
		return "other"
	}
}
```


<!-- Sent from Reviewable.io -->

2024-09-30 19:58 UTC, angles-n-daemons reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @spilchen, and @xinhaoz)

___
*[`pkg/server/diagnostics/reporter.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7cs_bZ7jotiRkTiBop:-O83Vlbq-2yiC7N4mVK9:bqnxgbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/reporter.go#L398)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Hmm, doesn't it return an empty string for 0? I think that's the `Unspecified` enum value.

`pkg/ccl/utilccl/licenseccl/license.go`
```
func (u License_Environment) String() string {
	switch u {
	case Unspecified:
		return ""
	case Production:
		return "production"
	case PreProduction:
		return "pre-production"
	case Development:
		return "development"
	default:
		return "other"
	}
}
```
</blockquote></details>

I must have misread that, I'll change it to use the string function now


<!-- Sent from Reviewable.io -->

2024-10-01 19:41 UTC, dhartunian reviewed
> Reviewed 3 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @DarrylWong, @spilchen, @vidit-bhat, and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88XnWp403PHPCncvtc:-O88XnWq8eWX0XillC7m:b-cygoiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e247dd2b69f265a91e838cb2218bd6382f0a192a/pkg/server/diagnostics/diagnostics.go#L115)):*
> ```Go
> 		}
> 		if license.OrganizationId != nil {
> 			organizationID = (*uuid.UUID)(license.OrganizationId).String()
> ```

This casting can panic and should be removed, or at least guarded by a check.
It's unclear to me if the byte slice here is an encoded UUID into a 16 bit byte slice, or the byte array of a stringified UUID. 

I'd like to use `string(license.OrganizationId)` here instead, otherwise this will panic if the slice isn't of the right length. If the license contains a non-standard orgID that's fine, we don't need to validate here.

I believe you can eliminate the null check through this as well, `string()` on a nil byte slice will just return the empty string.
___
*[`pkg/server/diagnostics/diagnostics.go` line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88aOmE5EtIUump6so_:-O88ZpFx0Zyh-vMO1lhD:b8dxe8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e247dd2b69f265a91e838cb2218bd6382f0a192a/pkg/server/diagnostics/diagnostics.go#L118)):*
> ```Go
> 		}
> 		if license.LicenseId != nil {
> 			licenseID = (*uuid.UUID)(license.LicenseId).String()
> ```

Same issue here with unsafe cast.

Use `string()` here as well on the byte slice. You can possibly eliminate the nil check here too, although I do see how it's more helpful here to only set expiry to non-empty string if the license is present.


<!-- Sent from Reviewable.io -->

2024-10-01 20:40 UTC, spilchen reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @DarrylWong, @dhartunian, @vidit-bhat, and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 139 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88lv4V-PW0IRF7eQnl:-O88lv4V-PW0IRF7eQnm:b-83ltyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e247dd2b69f265a91e838cb2218bd6382f0a192a/pkg/server/diagnostics/diagnostics.go#L139)):*
> ```Go
> 	q.Set("organization_id", organizationID)
> 	q.Set("license_id", licenseID)
> 	q.Set("license_expiry", licenseExpiry)
> ```

nit: I'm not sure who uses this, but should we include the unit (e.g., seconds) in the name to prevent any confusion with a different format?
___
*[`pkg/server/diagnostics/reporter.go` line 122 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88eDbj3tUlDvn_p91C:-O88eDbj3tUlDvn_p91D:b-eafnek) ([raw file](https://github.com/cockroachdb/cockroach/blob/e247dd2b69f265a91e838cb2218bd6382f0a192a/pkg/server/diagnostics/reporter.go#L122)):*
> ```Go
> 			// Consider something like rand.Float() > resetFreq/reportFreq here to sample
> 			// stat reset periods for reporting.
> 			if true || logcrash.DiagnosticsReportingEnabled.Get(&r.Settings.SV) {
> ```

Was the `true ||` change intentional, or is it leftover debug code?


<!-- Sent from Reviewable.io -->

2024-10-02 16:12 UTC, angles-n-daemons reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @spilchen, @vidit-bhat, and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88XnWp403PHPCncvtc:-O8Ckys0-nXMfMefhoQk:b-9ngl07) ([raw file](https://github.com/cockroachdb/cockroach/blob/04e2bfe6008797428ef66bb14f769114f85e77bd/pkg/server/diagnostics/diagnostics.go#L115)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This casting can panic and should be removed, or at least guarded by a check.
It's unclear to me if the byte slice here is an encoded UUID into a 16 bit byte slice, or the byte array of a stringified UUID. 

I'd like to use `string(license.OrganizationId)` here instead, otherwise this will panic if the slice isn't of the right length. If the license contains a non-standard orgID that's fine, we don't need to validate here.

I believe you can eliminate the null check through this as well, `string()` on a nil byte slice will just return the empty string.
</blockquote></details>

It wouldn't work, the byte array representation doesn't stringify in the same way - consider the below code block:

```
string(license.OrganizationId) // prints �x�L�sAR�8w�	
(*uuid.UUID)(license.OrganizationId).String() // prints 9b7815dd-134c-4273-8152-1ff73877a409
```

I think there's a fromBytes method or something similar I can use. Otherwise I can do a few assertions before executing the cast.
___
*[`pkg/server/diagnostics/reporter.go` line 122 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O88eDbj3tUlDvn_p91C:-O8D-8SE52sKGeKGI0aJ:btgt9l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04e2bfe6008797428ef66bb14f769114f85e77bd/pkg/server/diagnostics/reporter.go#L122)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Was the `true ||` change intentional, or is it leftover debug code?
</blockquote></details>

oop, this is leftover debug code


<!-- Sent from Reviewable.io -->

2024-10-02 18:08 UTC, spilchen requested changes
I'm good with these changes overall. There’s just one remaining comment that I think needs to be addressed—I’ve left my feedback there.

> Reviewed 1 of 9 files at r3, 1 of 1 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-:-O8DPWQe1k-ZwDu_O2ud:bg3p7pg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @DarrylWong, @dhartunian, @vidit-bhat, and @xinhaoz)

___
*[`pkg/server/diagnostics/reporter.go` line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7cs_bZ7jotiRkTiBop:-O8DOEP0CPD75p41QQIT:b49yi10) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/reporter.go#L398)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I must have misread that, I'll change it to use the string function now
</blockquote></details>

You may already have this in the works, but just in case—it looks like I haven’t seen the change come through yet.


<!-- Sent from Reviewable.io -->

2024-10-02 18:21 UTC, angles-n-daemons reviewed
Ah no, it was still there - just pulled it out now, thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-:-O8DShw_9cIVi4kozqi-:b-2p6ztu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @spilchen, @vidit-bhat, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-10-02 18:27 UTC, angles-n-daemons reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @dhartunian, @spilchen, @vidit-bhat, and @xinhaoz)

___
*[`pkg/server/diagnostics/diagnostics.go` line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-O7ct55O4S9HC9hSpPol:-O8DU2Bf7IvDYGzIBcrv:b3ig2mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e26b91cc785c45ef7a80e8e96f9e678a8ae27e70/pkg/server/diagnostics/diagnostics.go#L83)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: It would be helpful to clarify the unit (e.g., seconds since epoch) in the variable name or as a comment for the reader.
</blockquote></details>

sounds great, adding this


<!-- Sent from Reviewable.io -->

2024-10-02 22:22 UTC, spilchen approved these changes
Thanks for making the revisions. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131249#-:-O8EJj1z2wE5_XfhF8F1:b-cim0g5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons, @DarrylWong, @dhartunian, @vidit-bhat, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-10-02 22:36 UTC, angles-n-daemons commented
np, thanks for the review.

2024-10-02 22:36 UTC, angles-n-daemons commented
bors r+

2024-10-03 22:43 UTC, angles-n-daemons commented
bors r+

2024-10-04 14:35 UTC, angles-n-daemons commented
bors r+

2024-10-04 15:39 UTC, merged