server: add tablemetadata job cluster settings to job status api
cockroachdb/cockroach pull request #131385
Opened 2024-09-25 21:27 UTC by xinhaoz

Add the cluster setting values for the update table metadata job to the job status api.

Epic: CRDB-37558
Release note: None

2024-09-25 21:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131385)
<!-- Reviewable:end -->

2024-09-25 21:52 UTC, kyle-a-wong requested changes
Can you add a small test that tests cluster settings changes are reflected in subsequent API calls

2024-09-26 13:56 UTC, kyle-a-wong approved these changes
lgtm

2024-09-26 13:58 UTC, xinhaoz commented
tftr!
bors r+

2024-09-26 14:49 UTC, merged