sql: ALTER COLUMN TYPE does not check partial index definitions
cockroachdb/cockroach pull request #131590
Opened 2024-09-30 13:32 UTC by Dedej-Bergin

Previously we would allow ALTER COLUMN TYPE to succeed on a column even when we have a partial index on it.  This would cause issues down the line for example at insert and is inconsistent with postgres.  This fix now checks for partial index and errors out like postgres when your run the ALTER COLUMN TYPE command on a column with a partial index.

Fixes: #72456

Release note (bug fix): ALTER COLUMN TYPE now errors out when we have a partial index dependent on the column being altered.

2024-10-01 11:34 UTC, spilchen requested changes
You were on the right track. I just had a couple of suggestions for modifications.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-:-O86qTOB2YalIMFG8NAM:b-dvy7ux)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86q3oT9axxLZ1KXZGY):*
Let's include the epic in the commit message: CRDB-25314
___
*[`pkg/sql/catalog/schemaexpr/expr.go` line 518 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86oyedE1GTOjElVqTb:-O86oyee309rh7ZF8347:baujs6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/catalog/schemaexpr/expr.go#L518)):*
> ```Go
> ) error {
> 	for _, index := range tableDesc.AllIndexes() {
> 		if index.IsPartial() {
> ```

Should we verify that the column is included in the partial index?
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86qofD62HYiyEtE4wb:-O86qofD62HYiyEtE4wc:b-yhs8on) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1218)):*
> ```
> DROP TABLE t_int;
> 
> subtest end
> ```

I usually aim to include a single `subtest end` at the bottom of the test. Since you've already added one, you can probably remove this line.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pbUrD6GezOwxJYIB:-O86pbUrD6GezOwxJYIC:b-hzw5dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1223)):*
> ```
> 
> statement ok
> set enable_experimental_alter_column_type_general='true';
> ```

I don't think we need this statement. We already call this higher up in the testcase.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O86pPWKDKV3zLUz281F:b-es9551) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
> ```
> statement ok
> set enable_experimental_alter_column_type_general='true';
> set use_declarative_schema_changer = off;
> ```

I think we call this test for the `local-legacy-schema-changer` config. So, I don't think we need this.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pkVtCVXWd7iQ2AQI:-O86pkVtCVXWd7iQ2AQJ:bdkz9zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1233)):*
> ```
> 
> statement error pq: cannot alter type of column "b" because it is referenced by partial index "idx"
> alter table a alter column b set data type timestamp  using a::timestamp;
> ```

We should expand this test and verify that we can alter the type of other columns not included in the partial index.


<!-- Sent from Reviewable.io -->

2024-10-01 12:59 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86q3oT9axxLZ1KXZGY):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Let's include the epic in the commit message: CRDB-25314
</blockquote></details>

Thanks, just updated it.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86qofD62HYiyEtE4wb:-O875wWSAlH3XQhyy7A8:b-832uwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1218)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I usually aim to include a single `subtest end` at the bottom of the test. Since you've already added one, you can probably remove this line.
</blockquote></details>

Thanks, I just removed it.
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pbUrD6GezOwxJYIB:-O8786Yw79s0rtxMpKvR:b-91i5pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1223)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I don't think we need this statement. We already call this higher up in the testcase.
</blockquote></details>

Okay great, I just removed it, thanks!
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O878BN0BzWRcJ4efuyo:b41nhqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I think we call this test for the `local-legacy-schema-changer` config. So, I don't think we need this.
</blockquote></details>

Right, I just added onlyif config local-legacy-schema-changer just now and removed this line, thanks!


<!-- Sent from Reviewable.io -->

2024-10-01 18:21 UTC, spilchen requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86q3oT9axxLZ1KXZGY):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Thanks, just updated it.
</blockquote></details>

Apologies, I meant to say that you should include this in the commit message. I thought there was a git hook in place to ensure the commit message follows the correct format.
```
Epic: CRDB-25314
```
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O88HtVcChH03xV18uRI:bpjees0) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Right, I just added onlyif config local-legacy-schema-changer just now and removed this line, thanks!
</blockquote></details>

We should be seeing the same error when the commands are run through the DSC. Are you observing a different outcome?


<!-- Sent from Reviewable.io -->

2024-10-01 19:58 UTC, Dedej-Bergin commented
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O88KAwc-L_hB8GRGk1Z:b-ymed6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

We should be seeing the same error when the commands are run through the DSC. Are you observing a different outcome?
</blockquote></details>

Yes a bit different, for the new code changes I just added, with these repro steps:

```
create table roach\_village ( roach\_id int primary key, first\_name text, last\_name text, legs int );
create index idx on roach\_village(last\_name) where first\_name = 'papa roach';
alter table roach\_village alter column first\_name set data type timestamp  using first\_name::timestamp;
alter table roach\_village alter column last\_name set data type timestamp  using last\_name::timestamp;
```

 I was thinking to make it work like this:

![Screenshot 2024-10-01 at 3.56.16 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/V7R10oF_YIU5Zs6PrNjUF-v7/Screenshot%202024-10-01%20at%203.56.16%E2%80%AFPM.png)

For DSC on the second one it seems to error out with unimplemented... not sure if that's the error message we want:
![Screenshot 2024-10-01 at 3.55.56 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/_j8mq_emUxYzUyKr2aHQRc69/Screenshot%202024-10-01%20at%203.55.56%E2%80%AFPM.png)


<!-- Sent from Reviewable.io -->

2024-10-01 21:20 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86q3oT9axxLZ1KXZGY):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Apologies, I meant to say that you should include this in the commit message. I thought there was a git hook in place to ensure the commit message follows the correct format.
```
Epic: CRDB-25314
```
</blockquote></details>

Just added this, for some reason I thought this happens automatically.
___
*[`pkg/sql/catalog/schemaexpr/expr.go` line 518 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86oyedE1GTOjElVqTb:-O88x0105ODMMUcEvoLG:b330obh) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/catalog/schemaexpr/expr.go#L518)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we verify that the column is included in the partial index?
</blockquote></details>

Yes just added this code, thanks @spilchen!
___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pkVtCVXWd7iQ2AQI:-O88x7FFEWYATYFaG8z_:blxf8fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1233)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

We should expand this test and verify that we can alter the type of other columns not included in the partial index.
</blockquote></details>

Just added the expanded test, thanks!


<!-- Sent from Reviewable.io -->

2024-10-02 11:05 UTC, spilchen requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O8BszAu2ATL8Lhhgao_:b-9siexy) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Yes a bit different, for the new code changes I just added, with these repro steps:

```
create table roach\_village ( roach\_id int primary key, first\_name text, last\_name text, legs int );
create index idx on roach\_village(last\_name) where first\_name = 'papa roach';
alter table roach\_village alter column first\_name set data type timestamp  using first\_name::timestamp;
alter table roach\_village alter column last\_name set data type timestamp  using last\_name::timestamp;
```

 I was thinking to make it work like this:

![Screenshot 2024-10-01 at 3.56.16 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/V7R10oF_YIU5Zs6PrNjUF-v7/Screenshot%202024-10-01%20at%203.56.16%E2%80%AFPM.png)

For DSC on the second one it seems to error out with unimplemented... not sure if that's the error message we want:
![Screenshot 2024-10-01 at 3.55.56 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/_j8mq_emUxYzUyKr2aHQRc69/Screenshot%202024-10-01%20at%203.55.56%E2%80%AFPM.png)
</blockquote></details>

The unimplemented error is expected for now—that’s what #127014 will address. In the meantime, can you try using a simpler type conversion instead of a complex one? A simple conversion is one that doesn’t require a backfill. This is supported in the DSC now and should let us run the test in both modes. For example, converting from `TEXT` to `CHAR(20)` would qualify as a simple conversion.


<!-- Sent from Reviewable.io -->

2024-10-02 19:46 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O8Di1Dh3f2TY9TV56Na:b-yqemdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

The unimplemented error is expected for now—that’s what #127014 will address. In the meantime, can you try using a simpler type conversion instead of a complex one? A simple conversion is one that doesn’t require a backfill. This is supported in the DSC now and should let us run the test in both modes. For example, converting from `TEXT` to `CHAR(20)` would qualify as a simple conversion.
</blockquote></details>

So it seems that DSC doesn't block when the column is part of the predicate.
![Screenshot 2024-10-02 at 3.32.33 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/cI_kxiFVD-Q0o5zcjRETd4wh/Screenshot%202024-10-02%20at%203.32.33%E2%80%AFPM.png)


<!-- Sent from Reviewable.io -->

2024-10-02 20:37 UTC, Dedej-Bergin commented
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O8DuXnh081NJ8Pbws1h:bd50k36) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

So it seems that DSC doesn't block when the column is part of the predicate.
![Screenshot 2024-10-02 at 3.32.33 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/cI_kxiFVD-Q0o5zcjRETd4wh/Screenshot%202024-10-02%20at%203.32.33%E2%80%AFPM.png)
</blockquote></details>

Actually we seem to error out on the predicate, but on the column that has the index we seem to not error out on DSC.
Is this something we should change in the DSC?

![Screenshot 2024-10-02 at 4.36.44 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/Z6ahYVUALkEGYPTloFwMZMUE/Screenshot%202024-10-02%20at%204.36.44%E2%80%AFPM.png)


<!-- Sent from Reviewable.io -->

2024-10-02 22:19 UTC, spilchen requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O8EI_K71yXNuGYNpKF6:b-nlofdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Actually we seem to error out on the predicate, but on the column that has the index we seem to not error out on DSC.
Is this something we should change in the DSC?

![Screenshot 2024-10-02 at 4.36.44 PM.png](https://files.reviewableusercontent.io/images/reviewable/164547647/Z6ahYVUALkEGYPTloFwMZMUE/Screenshot%202024-10-02%20at%204.36.44%E2%80%AFPM.png)
</blockquote></details>

Thanks for running these tests. The DSC behavior is correct: it should fail only when modifying the partial expression and succeed when modifying a key column. Key columns can be changed because we’ll rewrite the index if a backfill is needed, or, if no backfill is required, the on-disk encoding of the column in the index remains unchanged (e.g., `BIGINT` to `SMALLINT`).

Could you remove the key column check in the legacy code? Sorry for not mentioning this earlier!


<!-- Sent from Reviewable.io -->

2024-10-03 14:23 UTC, Dedej-Bergin commented
*[`pkg/sql/logictest/testdata/logic_test/alter_column_type` line 1224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-O86pPWKDKV3zLUz281E:-O8HkR8ZD0SikARNZiCv:b-gtg5cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/464bdddeca94afe2cb3efbf84eeb005e2f1efe76/pkg/sql/logictest/testdata/logic_test/alter_column_type#L1224)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Thanks for running these tests. The DSC behavior is correct: it should fail only when modifying the partial expression and succeed when modifying a key column. Key columns can be changed because we’ll rewrite the index if a backfill is needed, or, if no backfill is required, the on-disk encoding of the column in the index remains unchanged (e.g., `BIGINT` to `SMALLINT`).

Could you remove the key column check in the legacy code? Sorry for not mentioning this earlier!
</blockquote></details>

No worries, just made the changes. The test-case results are now coming back the same for both DSC and legacy, thanks!


<!-- Sent from Reviewable.io -->

2024-10-03 14:42 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131590#-:-O8HpJNLBoOI7xcRzZlD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Dedej-Bergin)



<!-- Sent from Reviewable.io -->

2024-10-03 14:57 UTC, Dedej-Bergin commented
bors r+

2024-10-03 15:27 UTC, merged