kvserver: disable quota pool when kvflowcontrol mode is apply-to-all
cockroachdb/cockroach pull request #131683
Opened 2024-10-01 18:56 UTC by kvoli

In #131423, we added a cluster setting to selectively disable the quota pool. Now also selectively disable the quota pool if "kvadmission.flow_control.mode" is set to "apply_to_all", meaning that all replication traffic is subject to replication admission control.

The quota pool now has the follow enablement conditions, all of which need to be true to enabled:

```
(1) "kv.raft.proposal_quota.enabled" is true
(2) "kvadmission.flow_control.mode" is set to "apply_to_elastic"
(3) the range is not the NodeLiveness range
```

Also ensure that the quota pool is closed or created upon a setting change.

Resolves: #131438
Release note: None

2024-10-01 18:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131683)
<!-- Reviewable:end -->

2024-10-01 20:33 UTC, kvoli commented
This isn't ready for review yet @sumeerbhola, there are actually some v1 kvflowcontrol integration tests that are failing, not unexpectedly given they set apply_to_all. The general approach should be good for review though.

2024-10-01 22:37 UTC, sumeerbhola requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131683)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89BPgO3xM_yFXCmM08:-O89BPgO3xM_yFXCmM09:b-nh6x3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L102)):*
> ```Go
> //
> //  1. "kv.raft.proposal_quota.enabled" is true
> //  2. "kvadmission.flow_control.mode" is set to "apply_to_elastic"
> ```

or `kvadmission.flow_control.enabled = false`?
___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89C5k32I8siFnXsZFX:-O89C5k32I8siFnXsZFY:b-dmgk04) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L112)):*
> ```Go
> }
> 
> func (r *Replica) updateProposalQuotaRaftMuLocked(
> ```

Is it fine to observe the change here because this will be called from handleRaftReady and that will happen at least at the tick interval for a non-quiescent replica?
___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89DPzn9ONHbSBY_vHr:-O89DPzn9ONHbSBY_vHs:b-r09y5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L152)):*
> ```Go
> 			}
> 		}
> 		return
> ```

why are we returning here? `shouldInitQuotaPool` may be true. Or we could have a quotaPool and enabled has changed to false, so we need to destroy it.


<!-- Sent from Reviewable.io -->

2024-10-01 22:38 UTC, kvoli commented
> This isn't completely ready for review yet @sumeerbhola, there are actually some v1 kvflowcontrol integration tests that are failing `TestFlowControlRaftTransportBreak` (I was incorrect earlier, I had actually run something like `-f TestFlowControl.*V2.*`, so the v2 tests were passing, but not v1), not unexpectedly given they set apply_to_all. The general approach should be good for a pass though.

Pushed a fix which should resolve the issue, it was due to destroying the lastUpdated map when disabling the quota pool, outside of a leadership change. Not doing that resolves the problem.

2024-10-01 22:55 UTC, kvoli reviewed
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-:-O89HycR27pA44LxNLwU:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89BPgO3xM_yFXCmM08:-O89ELDV95cPugsx1YiM:btwre7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L102)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

or `kvadmission.flow_control.enabled = false`?
</blockquote></details>

Yeah `kvadmission.flow_control.enabled = false` was missing - plumbed through and updated the test.
___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89C5k32I8siFnXsZFX:-O89EMkV7sQE89ELp1_g:b2w4mzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L112)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is it fine to observe the change here because this will be called from handleRaftReady and that will happen at least at the tick interval for a non-quiescent replica?
</blockquote></details>

Yes, for this reason. I'll add a comment explaining it.
___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89DPzn9ONHbSBY_vHr:-O89EPTf3nDIV1AR2Ih-:b7ud3db) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ae0cc407f3b00c7762ff174ab56c0d7e160841f/pkg/kv/kvserver/replica_proposal_quota.go#L152)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why are we returning here? `shouldInitQuotaPool` may be true. Or we could have a quotaPool and enabled has changed to false, so we need to destroy it.
</blockquote></details>

This was a bug, fixed.


<!-- Sent from Reviewable.io -->

2024-10-02 00:13 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-:-O89ZiqD7IlFI8NQgYtu:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89ZOva4nxwFtu2tTu6:-O89ZOva4nxwFtu2tTu7:b-7bcj88) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb5229b17e0ac7134c6ae469577e403b5515db0/pkg/kv/kvserver/replica_proposal_quota.go#L314)):*
> ```Go
> 		r.mu.quotaReleaseQueue = nil
> 		r.mu.proposalQuota = nil
> 		r.mu.lastProposalAtTicks = r.mu.ticks // delay imminent quiescence
> ```

This `lastProposalAtTicks` change in this method is generally confusing (even before this PR). It was only set when becoming the leader. Do we really need to do this update here.


<!-- Sent from Reviewable.io -->

2024-10-02 13:38 UTC, kvoli reviewed
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-:-O8CRt9wD3Ob6OkXyx0z:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_proposal_quota.go` line 314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131683#-O89ZOva4nxwFtu2tTu6:-O8CRu3N9N_FxQMCtwbk:bvcta2) ([raw file](https://github.com/cockroachdb/cockroach/blob/deb5229b17e0ac7134c6ae469577e403b5515db0/pkg/kv/kvserver/replica_proposal_quota.go#L314)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This `lastProposalAtTicks` change in this method is generally confusing (even before this PR). It was only set when becoming the leader. Do we really need to do this update here.
</blockquote></details>

I don't think so, removed. I was thinking it might be necessary to fix the bug I mentioned in a comment above but I don't think they were at all related after actually fixing it.


<!-- Sent from Reviewable.io -->

2024-10-02 14:01 UTC, kvoli commented
Actually, looks like that might have been necessary to prevent quiescing immediately after destroying the quota pool.

2024-10-02 15:23 UTC, kvoli commented
> Actually, looks like that might have been necessary to prevent quiescing immediately after destroying the quota pool.

nvm (again), this was a metamorphic constant causing this, which was erroneously labeled: https://github.com/cockroachdb/cockroach/pull/131754.

2024-10-02 15:49 UTC, kvoli commented
I pushed some test only changes to address `kvflowcontrol.mode` being a metamorphic constant and removed:

> This lastProposalAtTicks change in this method is generally confusing (even before this PR). It was only set when becoming the leader. Do we really need to do this update here.

I'll merge once CI goes green.

2024-10-02 15:50 UTC, kvoli commented
bors r=sumeerbhola

2024-10-02 16:39 UTC, merged