replica_rac2: pass leaderTerm to lowPriOverrideState.getEffectivePrio…
cockroachdb/cockroach pull request #131616
Opened 2024-09-30 19:11 UTC by sumeerbhola

…rity

We use this to strengthen the invariant for retrieval of the priority override state, since we don't want to accidentally have an entry accounted for as normal priority on the leader be considered low priority at a follower.

Epic: CRDB-37515

Release note: None

2024-09-30 19:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131616)
<!-- Reviewable:end -->

2024-09-30 21:15 UTC, kvoli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131616#-:-O83mUl5-aAVtqEkpaLN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)



<!-- Sent from Reviewable.io -->

2024-10-07 13:31 UTC, pav-kv requested changes

2024-10-07 13:31 UTC, pav-kv commented on pkg/kv/kvserver/kvflowcontrol/replica_rac2/admission.go
> +		// getEffectivePriority should never be asking for the effective priority
If this side channel was integrated with `LogTracker` and observed all state changes, this invariant would be more viable. For that, we would need a better `Step(MsgApp)` API which would tell us exactly what happened.

2024-10-07 17:39 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131616)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/admission.go` line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131616#gh-1790211059:-O8c0Au6AKe2aOeBtpa0:b-xj31r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/17245f8362749a910863441e329d05ae39eeb671/pkg/kv/kvserver/kvflowcontrol/replica_rac2/admission.go#L175)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

If this side channel was integrated with `LogTracker` and observed all state changes, this invariant would be more viable. For that, we would need a better `Step(MsgApp)` API which would tell us exactly what happened.
</blockquote></details>

What I was trying to avoid with this PR is a situation:
```
side-channel: leaderTerm:10, entries: [30,40], low=false
side-channel: leaderTerm:11, entries: [20,35], low=true
get-effective: leaderTerm: 10, index:30
```
Last call retrieves true and garbage collects up to 30. Now the later call `get-effective(leaderTerm: 10, index:20)` will not have the right state to return.

But as you pointed out, we can't enforce the leaderTerm being identical. Also, we can't not garbage collect since we could also have a situation
```
side-channel: leaderTerm:10, entries: [30,40], low=false
side-channel: leaderTerm:11, entries: [35,45], low=true
get-effective: leaderTerm: 10, index:30
```
The problem is that we are keeping one leaderTerm in `lowPriOverrideState`.

In the latter example, we could also have `get-effective: leaderTerm: 11, index:30`, since index 30 was not overwritten.

I am going to close this PR. I don't think this is worth solving at this point in time. Also, the worst that early GC can do is flip a low=true to a low=false, which is permitted based on our weak correctness criteria:

```
// We specify a weak correctness requirement: if a leader has not overridden
// to LowPri, the lowPriOverrideState should not think it has. This prevents a
// situation where an entry is consuming regular tokens on the leader, but
// will be admitted as elastic work on the follower.
```


<!-- Sent from Reviewable.io -->

2024-10-07 21:44 UTC, closed without merging