sql: index backfiller can end up writing non-stored columns in families
cockroachdb/cockroach pull request #131967
Opened 2024-10-04 19:44 UTC by fqazi

During a drop column schmea change its possible for column families to exist temporarily until they get cleaned up at a later stage. These column families would be empty because they don't have any stored columns from the new primary index. When we added logic to skip this logic, we added extra logic ignore composite datums, which was unnecessary. As a result, we can end up writing composite columns into the primary index, even if their families will be cleaned up. This can later make tables unreadable with invalid data. To address this, this patch will skip over any column families without stored columns, even if they have composite datums.

Fixes: #131948

Release note (bug fix): Dropping a column stored standalone in a family that is of a composite datums (i.e. collated strings) can leave tables unreadable.

2024-10-04 19:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/131967)
<!-- Reviewable:end -->

2024-10-07 12:53 UTC, spilchen reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/rowenc/index_encoding.go` line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8b0fop2Ca98Ljt83Pq:-O8b0fop2Ca98Ljt83Pr:byp595q) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ccb599939480d41f30948966efa567f290df7/pkg/sql/rowenc/index_encoding.go#L1173)):*
> ```Go
> 			// may exist temporarily while adding a column.
> 			if !storedColumns.Contains(family.DefaultColumnID) {
> 				if cdatum, ok := values[colMap.GetDefault(family.DefaultColumnID)].(tree.CompositeDatum); !ok ||
> ```

Do we know the original reason for this optimization? The comment a few lines above only mentions adding columns. Do we have test coverage for adding composite columns to ensure this change is safe?


<!-- Sent from Reviewable.io -->

2024-10-07 14:19 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/rowenc/index_encoding.go` line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8b0fop2Ca98Ljt83Pq:-O8bLBAB3QJAvD8ykpMf:b-gbk23) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ccb599939480d41f30948966efa567f290df7/pkg/sql/rowenc/index_encoding.go#L1173)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we know the original reason for this optimization? The comment a few lines above only mentions adding columns. Do we have test coverage for adding composite columns to ensure this change is safe?
</blockquote></details>

I wasn't able to track down why I made the change in the original review. It started off with the simple case, but at some point got the composite type thing added. I can't think of a rational reason for why it would have been needed.

Fair point, let me beef up the coverage here too.


<!-- Sent from Reviewable.io -->

2024-10-07 14:58 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/rowenc/index_encoding.go` line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8b0fop2Ca98Ljt83Pq:-O8bU1uj-yVbFJGY5QyK:bqh5krn) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ccb599939480d41f30948966efa567f290df7/pkg/sql/rowenc/index_encoding.go#L1173)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I wasn't able to track down why I made the change in the original review. It started off with the simple case, but at some point got the composite type thing added. I can't think of a rational reason for why it would have been needed.

Fair point, let me beef up the coverage here too.
</blockquote></details>

I think it was added from a misunderstanding of the later code below:

```
			if cdatum, ok := values[colMap.GetDefault(colID)].(tree.CompositeDatum); ok {
				if cdatum.IsComposite() {
					columnsToEncode = append(columnsToEncode, ValueEncodedColumn{ColID: colID, IsComposite: true})
					continue
				}
```

^ This would never kick in this case anyway because there is only one column, so no other composite columns could exist in the family.


<!-- Sent from Reviewable.io -->

2024-10-07 16:42 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-:-O8br7HoC8kVPLSLwKcU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/rowenc/index_encoding.go` line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8b0fop2Ca98Ljt83Pq:-O8br3H9-15en801tz4k:b-7aitaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/610ccb599939480d41f30948966efa567f290df7/pkg/sql/rowenc/index_encoding.go#L1173)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think it was added from a misunderstanding of the later code below:

```
			if cdatum, ok := values[colMap.GetDefault(colID)].(tree.CompositeDatum); ok {
				if cdatum.IsComposite() {
					columnsToEncode = append(columnsToEncode, ValueEncodedColumn{ColID: colID, IsComposite: true})
					continue
				}
```

^ This would never kick in this case anyway because there is only one column, so no other composite columns could exist in the family.
</blockquote></details>

Thanks for clarifying.


<!-- Sent from Reviewable.io -->

2024-10-07 21:13 UTC, fqazi commented
@spilchen Take another look, since the previous fix would break composite primary keys

2024-10-07 21:29 UTC, michae2 requested changes
I just fixed something very similar in https://github.com/cockroachdb/cockroach/pull/132120. I thought we did need to store composite columns in the primary index. For example:

```sql
CREATE TABLE abc (a INT NOT NULL, b FLOAT NOT NULL, c INT, FAMILY (a), FAMILY (b), FAMILY (c));
INSERT INTO abc VALUES (4, -0, 6);
ALTER TABLE abc ADD PRIMARY KEY (a, b);
SHOW CREATE TABLE abc;
SELECT * FROM abc;
```

I believe that this table needs to have -0 (a composite value) stored in the column family (b), otherwise the SELECT will return 0 instead of -0.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-:-O8cr6Rc0f1OthlgcVFc:b-9se2u4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @spilchen)



<!-- Sent from Reviewable.io -->

2024-10-08 00:44 UTC, fqazi reviewed
@michae2 Right, so the problem the backfiller code had was that we *always* wrote composite keys, since during a drop column the family is cleaned up much later. This patch makes it so that we only write composite columns if they are still part of the key or stored. For non-composite columns they are only written if they are stored. 

DROP COLUMN rewrites the primary index and while thats happening  the column families will contain the dropped column, until everything is final. So, the backfiller needs to cross reference against the primary index definition, so that the correct stuff gets written.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-:-O8dWP5l4k1qYfDGNoIC:b-dkrwdw)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @spilchen)



<!-- Sent from Reviewable.io -->

2024-10-08 13:25 UTC, spilchen approved these changes
Most recent change looks good. 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-:-O8gIWTa0ebK_MXNylUA:b-acaq4i)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)



<!-- Sent from Reviewable.io -->

2024-10-08 13:40 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I think this is correct, just some questions / nits.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-:-O8gLi6FCKatdR6c3nxX:bghzxya)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @fqazi and @rytaft)

___
*[`-- commits` line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gDz9oC9Hz_v8JTUCA):*
typos: "schema", "it's"
___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gEFpw9KK7kgIm-hiM):*
nit: Wasn't the logic to ignore composite datums necessary, but insufficient? It seems like the problem was a lack of checking `index.CollectKeyColumnIDs().Contains()`?
___
*[`-- commits` line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gJPPw8ExQ-3A2zCn7):*
nit: (influenced by the other PR) this is kind of a scary release note, it might help to spell out the required conditions a little more. Is it something like:
1. A table with multiple column families.
2. A column family containing a single column.
3. That column family is not the first column family.
4. That column must be of type FLOAT4/8, DECIMAL, JSON, collated string type, or array.
5. That column is then dropped.
___
*[`pkg/sql/rowenc/index_encoding.go` line 1179 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gF2go6dgvvfkNYhwS:-O8gF2go6dgvvfkNYhwT:b-rz3nda) ([raw file](https://github.com/cockroachdb/cockroach/blob/a074ef072d72839be98e0d244ab055b908ae2439/pkg/sql/rowenc/index_encoding.go#L1179)):*
> ```Go
> 			if !storedColumns.Contains(family.DefaultColumnID) && !storeCompositeKey {
> 				return nil
> 			}
> ```

This logic seems correct.

It's pretty similar to `row.(*RowHelper).SkipColumnNotInPrimaryIndexValue`, which is used by `prepareInsertOrUpdateBatch`. Maybe there's a way to factor out the duplicated logic?

Though now that I look at it, `SkipColumnNotInPrimaryIndexValue` only uses `index.CollectPrimaryStoredColumnIDs()`. It looks like `getStoredColumnsForPrimaryIndex` is doing more than that in some cases. Should we change `SkipColumnNotInPrimaryIndexValue` to use `getStoredColumnsForPrimaryIndex`?


<!-- Sent from Reviewable.io -->

2024-10-08 18:51 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @fqazi, @michae2, @rytaft, and @spilchen)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gEFpw9KK7kgIm-hiM):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Wasn't the logic to ignore composite datums necessary, but insufficient? It seems like the problem was a lack of checking `index.CollectKeyColumnIDs().Contains()`?
</blockquote></details>

Updated the language: 

When we added a check to skip this
logic, we added extra logic ignore composite datums, which was partially correct but insufficient (i.e. it didn't properly check if a composite
datum needed to be stored, and always assumed this was the case).
___
*[`-- commits` line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gJPPw8ExQ-3A2zCn7):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: (influenced by the other PR) this is kind of a scary release note, it might help to spell out the required conditions a little more. Is it something like:
1. A table with multiple column families.
2. A column family containing a single column.
3. That column family is not the first column family.
4. That column must be of type FLOAT4/8, DECIMAL, JSON, collated string type, or array.
5. That column is then dropped.
</blockquote></details>

Release note (bug fix): Addressed a rare bug where dropping a column of FLOAT4/8, DECIMAL, JSON, collated string type, or array types that were stored in a single column family could make a table unreadable.

I also added conditions in the PR, let me know if you have any ideas to make it less scary.


<!-- Sent from Reviewable.io -->

2024-10-08 18:52 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131967)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2, @rytaft, and @spilchen)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gEFpw9KK7kgIm-hiM):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Wasn't the logic to ignore composite datums necessary, but insufficient? It seems like the problem was a lack of checking `index.CollectKeyColumnIDs().Contains()`?
</blockquote></details>

Updated the language: 

When we added a check to skip this
logic, we added extra logic ignore composite datums, which was partially correct but insufficient (i.e. it didn't properly check if a composite
datum needed to be stored, and always assumed this was the case).
___
*[`-- commits` line 19 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gJPPw8ExQ-3A2zCn7):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: (influenced by the other PR) this is kind of a scary release note, it might help to spell out the required conditions a little more. Is it something like:
1. A table with multiple column families.
2. A column family containing a single column.
3. That column family is not the first column family.
4. That column must be of type FLOAT4/8, DECIMAL, JSON, collated string type, or array.
5. That column is then dropped.
</blockquote></details>

Release note (bug fix): Addressed a rare bug where dropping a column of FLOAT4/8, DECIMAL, JSON, collated string type, or array types that were stored in a single column family could make a table unreadable.

I also added conditions in the PR, let me know if you have any ideas to make it less scary.
___
*[`pkg/sql/rowenc/index_encoding.go` line 1179 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131967#-O8gF2go6dgvvfkNYhwS:-O8hTP4E8FDGKcVXO0Gg:biseszu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a074ef072d72839be98e0d244ab055b908ae2439/pkg/sql/rowenc/index_encoding.go#L1179)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

This logic seems correct.

It's pretty similar to `row.(*RowHelper).SkipColumnNotInPrimaryIndexValue`, which is used by `prepareInsertOrUpdateBatch`. Maybe there's a way to factor out the duplicated logic?

Though now that I look at it, `SkipColumnNotInPrimaryIndexValue` only uses `index.CollectPrimaryStoredColumnIDs()`. It looks like `getStoredColumnsForPrimaryIndex` is doing more than that in some cases. Should we change `SkipColumnNotInPrimaryIndexValue` to use `getStoredColumnsForPrimaryIndex`?
</blockquote></details>

Done.

Good point and I have made this logic shared


<!-- Sent from Reviewable.io -->

2024-10-08 19:14 UTC, rafiss commented
Are we going to need backports for this?

2024-10-08 21:01 UTC, fqazi commented
@rafiss Yeah this will need backports. Tagged them on here.

2024-10-08 21:01 UTC, fqazi commented
@spilchen @michae2 TFTR!

bors r+

2024-10-08 21:57 UTC, merged

2024-10-08 22:07 UTC, michae2 commented
(hold off on backport while I get https://github.com/cockroachdb/cockroach/pull/132120 and siblings merged...)