drtprod: put tpcc init and run scripts on workload-scale
cockroachdb/cockroach pull request #132162
Opened 2024-10-08 12:33 UTC by vidit-bhat

This patch ensures that we put the `tpcc_init.sh`
and `tpcc_run.sh` file while creating `workload-scale`

Epic: none
Release note: None

2024-10-08 12:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/132162)
<!-- Reviewable:end -->

2024-10-09 04:52 UTC, shailendra-patel commented on pkg/cmd/drt/scripts/tpcc_init.sh
> +PGURLS=$(./roachprod pgurl drt-scale:1-150 | sed s/\'//g)
nit: passing only cluster name `drt-scale` would give pgurl for all nodes. In case if we decide to not have exact 150 nodes.

2024-10-09 04:52 UTC, shailendra-patel commented on pkg/cmd/drt/scripts/tpcc_init.sh
> +  --warehouses 3000 \
For 150 scale node the plan is to have 150K warehouses.

2024-10-09 04:52 UTC, shailendra-patel commented on pkg/cmd/drt/scripts/tpcc_init.sh
> +TPCC_DB=cct_tpcc
Any reason why are we changing the db name from `tpcc` to `cct_tpcc`.

2024-10-09 04:52 UTC, shailendra-patel commented on pkg/cmd/drt/scripts/tpcc_run.sh
> +      $PGURLS | tee $LOG
`--warehouses 3000, --active-warehouses 1500` value of this flags need to be changed.

Also we need to think about values of following flags to get the cpu around 60%.
```
-concurrency 128
--max-rate 7000 
```

2024-10-09 18:40 UTC, nameisbhaskar commented
As discussed, lets hold back on this change. I would prefer it to be more generic scripts that takes inputs from teh YAML file for parameters like warehouses. This can go in after https://github.com/cockroachdb/cockroach/pull/131942 changes. After that I have another change in the queue where we have parameterised tpocc init.

2024-10-09 18:41 UTC, nameisbhaskar requested changes
We will revisit this.

2024-10-15 07:43 UTC, closed without merging

2024-10-15 07:43 UTC, vidit-bhat commented
Closed in favour of https://github.com/cockroachdb/cockroach/pull/132307