sql/schemachanger: clean up SequenceOwner elements during restore
cockroachdb/cockroach pull request #132202
Opened 2024-10-08 21:26 UTC by fqazi

Previously, when restoring a backup taken in middle of a DROP COLUMN, where a column had a sequence owner assigned, it was possible for the backup to be unrestorable. This would happen because the sequence reference would have been dropped in the plan, but the seqeunce owner element was still within the state. To address this, this test updates the rewrite logic to clean up any SequenceOwner elements which have the referenced sequence already removed.

Fixes: #130778

Release note (bug fix): Addressed a rare bug that could prevent backups taken during a DROP COLUMN operation with a sequence owner from restoring with the error: "rewriting descriptor ids: missing rewrite for <id> in SequenceOwner..."

2024-10-08 21:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/132202)
<!-- Reviewable:end -->

2024-10-09 17:45 UTC, Dedej-Bergin commented
*[`pkg/sql/catalog/rewrite/rewrite.go` line 771 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132202#-O8mN4JT6qsWYjyqIsHv:-O8mN4JT6qsWYjyqIsHw:b-e7lve8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3849f33eb3c19509651938f94f2d8feb35ceca2f/pkg/sql/catalog/rewrite/rewrite.go#L771)):*
> ```Go
> 		}
> 
> 		// maybeRemoveMissingReference potentially removes and element based on
> ```

nitpick: should be 'an' element instead of 'and' element

`// maybeRemoveMissingReference potentially removes and element`


<!-- Sent from Reviewable.io -->

2024-10-09 18:35 UTC, Dedej-Bergin commented
Nice fix! Just have some small naming related comments.





<!-- Sent from Reviewable.io -->

2024-10-09 19:20 UTC, Dedej-Bergin commented
*[`pkg/sql/catalog/rewrite/rewrite.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132202#-O8mWa009vGuPxLlySly:-O8miG7K6yhVOfKtwBsX:bdfic96) ([raw file](https://github.com/cockroachdb/cockroach/blob/3849f33eb3c19509651938f94f2d8feb35ceca2f/pkg/sql/catalog/rewrite/rewrite.go#L773)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Not a fan of using the word maybe in this function name.  Could we split this up into 2 functions like this:
```
		missingReferenceIsSequence := func(element scpb.Element, missingID descpb.ID) (removed bool) {
			return reflect.TypeOf(element) == reflect.TypeOf(&scpb.SequenceOwner{}) && 
				element.(*scpb.SequenceOwner).SequenceID == missingID
		}

		removeMissingReference := func(element scpb.Element, missingID descpb.ID) {
			state.Targets = append(state.Targets[:i], state.Targets[i+1:]...)
			state.CurrentStatuses = append(state.CurrentStatuses[:i], state.CurrentStatuses[i+1:]...)
			state.TargetRanks = append(state.TargetRanks[:i], state.TargetRanks[i+1:]...)
			i--
		}
```

And we could make the if statement below look like this:

```
				if missingReferenceIsSequence(t.Element(), *id) {
					removeMissingReference(t.Element(), *id)
					// No rewrite is needed and we are done
					return nil
				}
```
</blockquote></details>

Alternative:

```
missingReferenceIsSequence := func(element scpb.Element, missingID descpb.ID) (removed bool) {
				switch e := element.(type) {
				case *scpb.SequenceOwner:
					if e.SequenceID == missingID {
						return true
					}
				}
				return false
			}
```


<!-- Sent from Reviewable.io -->

2024-10-09 19:20 UTC, Dedej-Bergin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132202#-:-O8miPBU75kIf8_PJMj4:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)



<!-- Sent from Reviewable.io -->

2024-10-10 02:23 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132202)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Dedej-Bergin)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132202#-O8mWa009vGuPxLlySly:-O8oE0EK8BY2PSjsYcmc:bgogqpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3849f33eb3c19509651938f94f2d8feb35ceca2f/pkg/sql/catalog/rewrite/rewrite.go#L773)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Alternative:

```
missingReferenceIsSequence := func(element scpb.Element, missingID descpb.ID) (removed bool) {
				switch e := element.(type) {
				case *scpb.SequenceOwner:
					if e.SequenceID == missingID {
						return true
					}
				}
				return false
			}
```
</blockquote></details>

I simplified this further, so that the switch below is just used. So, its much simpler after that change and I replaced the deletion code with function calls.


<!-- Sent from Reviewable.io -->

2024-10-10 04:22 UTC, fqazi commented
@Dedej-Bergin TFTR!

bors r+

2024-10-10 12:24 UTC, fqazi commented
Hit a test flake

bors retry

2024-10-10 13:15 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132202)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132202#-O8mWa009vGuPxLlySly:-O8qZPsJ2UhWX0M8kdBx:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3849f33eb3c19509651938f94f2d8feb35ceca2f/pkg/sql/catalog/rewrite/rewrite.go#L773)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I simplified this further, so that the switch below is just used. So, its much simpler after that change and I replaced the deletion code with function calls.
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2024-10-10 14:18 UTC, rafiss commented
I believe this will need backports. Have you thought about how far back it should go?

2024-10-10 14:20 UTC, rafiss requested changes
the new test that was added in this PR failed: 
```
    end_to_end.go:213: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/sctest/end_to_end.go:213
        	            				github.com/cockroachdb/cockroach/pkg/sql/schemachanger/sctest/end_to_end.go:164
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:118
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:337
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:342
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:211
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:184
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:144
        	            				github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:117
        	            				github.com/cockroachdb/cockroach/pkg/sql/schemachanger/sctest/end_to_end.go:70
        	            				github.com/cockroachdb/cockroach/pkg/sql/schemachanger/sctest/test_server_factory.go:97
        	            				github.com/cockroachdb/cockroach/pkg/sql/schemachanger/sctest/end_to_end.go:65
        	            				pkg/sql/schemachanger/schemachanger_test/bazel-out/k8-fastbuild/bin/pkg/sql/schemachanger/sctest_generated_test.go:414
        	Error:      	Not equal: 
        	            	expected: "/* setup */\nCREATE TABLE t (i INT PRIMARY KEY, j INT, k int);\nCREATE SEQUENCE sq1 OWNED BY t.j;\nCOMMENT ON TABLE t IS 't has a comment';\nCOMMENT ON COLUMN t.j IS 'j has a comment';\nINSERT INTO t VALUES(-1);\nINSERT INTO t VALUES(-2);\nINSERT INTO t VALUES(-3);\n----\n...\n+object {100 101 t} -> 104\n+object {100 101 sq1} -> 105\n\n/* test */\nALTER TABLE t DROP COLUMN j;\n----\nbegin transaction #1\n# begin StatementPhase\nchecking for feature: ALTER TABLE\nincrement telemetry for sql.schema.alter_table\nincrement telemetry for sql.schema.alter_table.drop_column\nwrite *eventpb.AlterTable to event log:\n  mutationId: 1\n  sql:\n    descriptorId: 104\n    statement: ALTER TABLE ‹defaultdb›.‹public›.‹t› DROP COLUMN ‹j›\n    tag: ALTER TABLE\n    user: root\n  tableName: defaultdb.public.t\n## StatementPhase stage 1 of 1 with 9 MutationType ops\nupsert descriptor #104\n  ...\n         oid: 20\n         width: 64\n  -  - id: 2\n  -    name: j\n  -    nullable: true\n  -    ownsSequenceIds:\n  -    - 105\n  -    type:\n  -      family: IntFamily\n  -      oid: 20\n  -      width: 64\n     - id: 3\n       name: k\n  ...\n       columnNames:\n       - i\n  -    - j\n  +    - crdb_internal_column_2_name_placeholder\n       - k\n       name: primary\n  ...\n     id: 104\n     modificationTime: {}\n  +  mutations:\n  +  - column:\n  +      id: 2\n  +      name: crdb_internal_column_2_name_placeholder\n  +      nullable: true\n  +      ownsSequenceIds:\n  +      - 105\n  +      type:\n  +        family: IntFamily\n  +        oid: 20\n  +        width: 64\n  +    direction: DROP\n  +    mutationId: 1\n  +    state: WRITE_ONLY\n  +  - direction: ADD\n  +    index:\n  +      constraintId: 2\n  +      createdExplicitly: true\n  +      encodingType: 1\n  +      foreignKey: {}\n  +      geoConfig: {}\n  +      id: 2\n  +      interleave: {}\n  +      keyColumnDirections:\n  +      - ASC\n  +      keyColumnIds:\n  +      - 1\n  +      keyColumnNames:\n  +      - i\n  +      name: crdb_internal_index_2_name_placeholder\n  +      partitioning: {}\n  +      sharded: {}\n  +      storeColumnIds:\n  +      - 3\n  +      storeColumnNames:\n  +      - k\n  +      unique: true\n  +      version: 4\n  +    mutationId: 1\n  +    state: BACKFILLING\n  +  - direction: ADD\n  +    index:\n  +      constraintId: 3\n  +      createdExplicitly: true\n  +      encodingType: 1\n  +      foreignKey: {}\n  +      geoConfig: {}\n  +      id: 3\n  +      interleave: {}\n  +      keyColumnDirections:\n  +      - ASC\n  +      keyColumnIds:\n  +      - 1\n  +      keyColumnNames:\n  +      - i\n  +      name: crdb_internal_index_3_name_placeholder\n  +      partitioning: {}\n  +      sharded: {}\n  +      storeColumnIds:\n  +      - 3\n  +      storeColumnNames:\n  +      - k\n  +      unique: true\n  +      useDeletePreservingEncoding: true\n  +      version: 4\n  +    mutationId: 1\n  +    state: DELETE_ONLY\n     name: t\n     nextColumnId: 4\n  -  nextConstraintId: 2\n  +  nextConstraintId: 4\n     nextFamilyId: 1\n  -  nextIndexId: 2\n  +  nextIndexId: 4\n     nextMutationId: 1\n     parentId: 100\n  ...\n       - 3\n       storeColumnNames:\n  -    - j\n  +    - crdb_internal_column_2_name_placeholder\n       - k\n       unique: true\n  ...\n       time: {}\n     unexposedParentSchemaId: 101\n  -  version: \"2\"\n  +  version: \"3\"\ndelete comment ColumnCommentType(objID: 104, subID: 2)\n# end StatementPhase\n# begin PreCommitPhase\n## PreCommitPhase stage 1 of 2 with 1 MutationType op\nundo all catalog changes within txn #1\npersist all catalog changes to storage\n## PreCommitPhase stage 2 of 2 with 14 MutationType ops\nupsert descriptor #104\n  ...\n         oid: 20\n         width: 64\n  -  - id: 2\n  -    name: j\n  -    nullable: true\n  -    ownsSequenceIds:\n  -    - 105\n  -    type:\n  -      family: IntFamily\n  -      oid: 20\n  -      width: 64\n     - id: 3\n       name: k\n  ...\n     createAsOfTime:\n       wallTime: \"1640995200000000000\"\n  +  declarativeSchemaChangerState:\n  +    authorization:\n  +      userName: root\n  +    currentStatuses: <redacted>\n  +    jobId: \"1\"\n  +    nameMapping:\n  +      columns:\n  +        \"1\": i\n  +        \"3\": k\n  +        \"4294967294\": tableoid\n  +        \"4294967295\": crdb_internal_mvcc_timestamp\n  +      families:\n  +        \"0\": primary\n  +      id: 104\n  +      indexes:\n  +        \"2\": t_pkey\n  +      name: t\n  +    relevantStatements:\n  +    - statement:\n  +        redactedStatement: ALTER TABLE ‹defaultdb›.‹public›.‹t› DROP COLUMN ‹j›\n  +        statement: ALTER TABLE t DROP COLUMN j\n  +        statementTag: ALTER TABLE\n  +    revertible: true\n  +    targetRanks: <redacted>\n  +    targets: <redacted>\n     families:\n     - columnIds:\n  ...\n       columnNames:\n       - i\n  -    - j\n  +    - crdb_internal_column_2_name_placeholder\n       - k\n       name: primary\n  ...\n     id: 104\n     modificationTime: {}\n  +  mutations:\n  +  - column:\n  +      id: 2\n  +      name: crdb_internal_column_2_name_placeholder\n  +      nullable: true\n  +      ownsSequenceIds:\n  +      - 105\n  +      type:\n  +        family: IntFamily\n  +        oid: 20\n  +        width: 64\n  +    direction: DROP\n  +    mutationId: 1\n  +    state: WRITE_ONLY\n  +  - direction: ADD\n  +    index:\n  +      constraintId: 2\n  +      createdExplicitly: true\n  +      encodingType: 1\n  +      foreignKey: {}\n  +      geoConfig: {}\n  +      id: 2\n  +      interleave: {}\n  +      keyColumnDirections:\n  +      - ASC\n  +      keyColumnIds:\n  +      - 1\n  +      keyColumnNames:\n  +      - i\n  +      name: crdb_internal_index_2_name_placeholder\n  +      partitioning: {}\n  +      sharded: {}\n  +      storeColumnIds:\n  +      - 3\n  +      storeColumnNames:\n  +      - k\n  +      unique: true\n  +      version: 4\n  +    mutationId: 1\n  +    state: BACKFILLING\n  +  - direction: ADD\n  +    index:\n  +      constraintId: 3\n  +      createdExplicitly: true\n  +      encodingType: 1\n  +      foreignKey: {}\n  +      geoConfig: {}\n  +      id: 3\n  +      interleave: {}\n  +      keyColumnDirections:\n  +      - ASC\n  +      keyColumnIds:\n  +      - 1\n  +      keyColumnNames:\n  +      - i\n  +      name: crdb_internal_index_3_name_placeholder\n  +      partitioning: {}\n [...]

2024-10-10 14:21 UTC, rafiss approved these changes
looks like it just needs a rebase and rewrite.

but in case you didn't see my earlier comment, please make sure to add backport labels.

2024-10-10 14:22 UTC, fqazi commented
@rafiss Let me rebase this and add labels

2024-10-10 14:39 UTC, fqazi commented
bors r+

2024-10-10 15:56 UTC, merged