sql/delegate: use `pg_description` in place of `system.comments` table
cockroachdb/cockroach pull request #132211
Opened 2024-10-09 07:14 UTC by sambhav-jain-16

Show schemas with comment and show databases with comment rely on system.comments table. This table is only accessible with users that have specific permissions. This change aims to use the `pg_catalog.pg_description` table so that the statements are available just not for root/admin users.

Fixes: https://github.com/cockroachdb/cockroach/issues/132201
Release note: None

2024-10-09 07:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/132211)
<!-- Reviewable:end -->

2024-10-09 21:28 UTC, Dedej-Bergin requested changes
Thanks for your contribution @sambhav-jain-16 ! Just some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-:-O8n8Hew42zh7V9XZg01:bb87tz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sambhav-jain-16)

___
*[`pkg/sql/delegate/show_schemas.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-O8n8kVxBrGHcTiv9Cbx:-O8n8kVxBrGHcTiv9Cby:be912hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9f660cabdeead371efc975be8277a55e69ac5c/pkg/sql/delegate/show_schemas.go#L29)):*
> ```Go
> 	commentColumn, commentJoin := ``, ``
> 	if n.WithComment {
> 		commentColumn = `, comment`
> ```

We can take the code here as well as from delegateShowTypes and delegateShowDatabases and move it into this common method:
This common method can be put inside delegate.go

```
func (d *delegator) getCommentQuery(commentTableName string, classOidType int) (string, string) {
       commentColumn := `, comment`
       commentJoin := fmt.Sprintf(`
                       LEFT JOIN
                               (
                                       SELECT
                                               objoid, description as comment
                                       FROM
                                               %s
                                       WHERE
                                               classoid = %d
                               ) c
                       ON
                                       (types.oid::int - 100000) = c.objoid`, commentTableName, classOidType)

       return commentColumn, commentJoin
}
```

And it can be called from delegateShowSchemas, delegateShowTypes, and delegateShowDatabases like this to reduce duplicate code:
```
 if n.WithComment { 
     dbName := lexbase.EscapeSQLIdent(d.evalCtx.SessionData().Database)
     commentTableName := dbName + ".pg_catalog.pg_description";
     commentColumn, commentJoin = d.getCommentQuery(commentTableName, catconstants.PgCatalogNamespaceTableID)
 }
```


<!-- Sent from Reviewable.io -->

2024-10-09 21:30 UTC, Dedej-Bergin reviewed
Also it would be good if we added logictest testcases for this, where we use a non-admin user that would normally fail if we used system.comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-:-O8nAlTR51h9LtIBgOjo:b-fstmdr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sambhav-jain-16)



<!-- Sent from Reviewable.io -->

2024-10-10 11:22 UTC, sambhav-jain-16 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132211)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`pkg/sql/delegate/show_schemas.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-O8n8kVxBrGHcTiv9Cbx:-O8q8eNEDRNgw9t31dPL:bwlrepg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9f660cabdeead371efc975be8277a55e69ac5c/pkg/sql/delegate/show_schemas.go#L29)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

We can take the code here as well as from delegateShowTypes and delegateShowDatabases and move it into this common method:
This common method can be put inside delegate.go

```
func (d *delegator) getCommentQuery(commentTableName string, classOidType int) (string, string) {
       commentColumn := `, comment`
       commentJoin := fmt.Sprintf(`
                       LEFT JOIN
                               (
                                       SELECT
                                               objoid, description as comment
                                       FROM
                                               %s
                                       WHERE
                                               classoid = %d
                               ) c
                       ON
                                       (types.oid::int - 100000) = c.objoid`, commentTableName, classOidType)

       return commentColumn, commentJoin
}
```

And it can be called from delegateShowSchemas, delegateShowTypes, and delegateShowDatabases like this to reduce duplicate code:
```
 if n.WithComment { 
     dbName := lexbase.EscapeSQLIdent(d.evalCtx.SessionData().Database)
     commentTableName := dbName + ".pg_catalog.pg_description";
     commentColumn, commentJoin = d.getCommentQuery(commentTableName, catconstants.PgCatalogNamespaceTableID)
 }
```
</blockquote></details>

@Dedej-Bergin The equality condition for show_schemas, show_types and show_databases are different so IMO we shouldn't create a common function for the same. LMK if this sounds good to you.


<!-- Sent from Reviewable.io -->

2024-10-10 16:58 UTC, Dedej-Bergin approved these changes
Thanks for your contribution @sambhav-jain-16 ! Feel free to run bors r+ to merge these changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-:-O8rMAZcESUie5dhUCg7:blulf5v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sambhav-jain-16)

___
*[`pkg/sql/delegate/show_schemas.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132211#-O8n8kVxBrGHcTiv9Cbx:-O8rLpgV1nonOBjcADnH:b-k44wid) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c9f660cabdeead371efc975be8277a55e69ac5c/pkg/sql/delegate/show_schemas.go#L29)):*
<details><summary><i>Previously, sambhav-jain-16 (Sambhav Jain) wrote…</i></summary><blockquote>

@Dedej-Bergin The equality condition for show_schemas, show_types and show_databases are different so IMO we shouldn't create a common function for the same. LMK if this sounds good to you.
</blockquote></details>

I agree that it's not as nice as originally thought since we also need the equality conditions, but I think the common function still works well here.


<!-- Sent from Reviewable.io -->

2024-10-10 17:02 UTC, sambhav-jain-16 commented
TFTR!

bors r+

2024-10-10 18:03 UTC, merged