server: Add http server metrics
cockroachdb/cockroach pull request #132714
Opened 2024-10-15 22:27 UTC by kyle-a-wong

Adds http server metrics to observer response times of requests. This uses a newly defined HistogramVec metric that is not aggregated or persisted to tsdb. It will only be exported to eternal collectors

Release note: None

2024-10-15 22:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/132714)
<!-- Reviewable:end -->

2024-10-17 15:37 UTC, angles-n-daemons requested changes
Hoping to make this important change slowly and surely, I'd like to ask two favors:
 1. Create a benchmark of the HTTP handler in three configurations, with the metrics middleware on, off and without the metrics middleware. A template has been provided for the above.
 2. Something perhaps to talk about in the meeting today, but it seems like this PR captures perhaps 1.5 of the ["golden signals"](https://sre.google/sre-book/monitoring-distributed-systems/). Discuss in tech pod whether we should explicitly cover the three most important ones, Rate, Error, and Duration (RED for short).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-:-O9PrUvyEtXuafnDdsPo:bm0mdk6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/server/api_v2_metrics.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pld3UC2oNAWyz7I9H:-O9Pld3UC2oNAWyz7I9I:b-agh1hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L6)):*
> ```Go
> // included in the /LICENSE file.
> 
> package server
> ```

I would name these `http_metrics.go` instead of `api_v2_metrics`
___
*[`pkg/server/api_v2_metrics.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pm9HV1YbTNX26g5pU:-O9Pm9HV1YbTNX26g5pV:b-cl0sv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L32)):*
> ```Go
> var serverHTTPMetricsEnabled = settings.RegisterBoolSetting(
> 	settings.ApplicationLevel,
> 	"server.http.metrics.enabled",
> ```

nice, this is an awesome addition
___
*[`pkg/server/api_v2_metrics.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PlkxL1V7QpAkhzCq1:-O9PlkxL1V7QpAkhzCq2:b-so3g0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L62)):*
> ```Go
> func NewHttpServerMetrics(reg *metric.Registry, settings *cluster.Settings) *HttpServerMetrics {
> 	ops := metric.NewHistogramVecOpts(metric.Metadata{
> 		Name:        "http.server.request.duration",
> ```

Unless you feel strongly otherwise, this should include the unit type `http.server.request.duration_ms`.
___
*[`pkg/server/api_v2_metrics.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Ppfrc6dbqIYBnp7bc:-O9Ppfrc6dbqIYBnp7bd:b5i3yn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L115)):*
> ```Go
> // removed
> func formatPathVars(path string) string {
> 	return pathVarsRegex.ReplaceAllString(path, "<$1>")
> ```

nice, pretty cool
___
*[`pkg/server/api_v2_metrics_test.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PrD1v2HULlmKlADYS:-O9PrD1v2HULlmKlADYT:b9sl8hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L56)):*
> ```Go
> 		})
> 
> 		serverHTTPMetricsEnabled.Override(context.Background(), &clusterSettings.SV, false)
> ```

An interesting question here is whether changing the cluster setting actually "un-registers" the metrics. Not sure if that utility exists currently, but did you think about that at all
___
*[`pkg/server/api_v2_metrics_test.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PsM6B3_27yva1JXfj:-O9PsM6B3_27yva1JXfk:b-vyu49q) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L108)):*
> ```Go
> 			fmt.Sprintf("%s GET %s", strconv.Itoa(http.StatusOK), formatPathVars(pathUri)):                   uint64(3),
> 			fmt.Sprintf("%s POST %s", strconv.Itoa(http.StatusOK), formatPathVars(pathUri)):                  uint64(1),
> 			fmt.Sprintf("%s POST %s", strconv.Itoa(http.StatusInternalServerError), formatPathVars(pathUri)): uint64(1),
> ```

nice, this is an awesome check
___
*[`pkg/server/api_v2_metrics_test.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pqnv315NF_7Q0xHeE:-O9Pqnv315NF_7Q0xHeF:bgj3zx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L121)):*
> ```Go
> 	testcases := []testcase{
> 		{name: "no variable", path: "/testpath/", expectedPath: "/testpath/"},
> 		{name: "variable with regex", path: "/testpath/{param:[0-9]+}/", expectedPath: "/testpath/<param>/"},
> ```

I'm confused, shouldn't the path be a literal example of the regex? Something to the effect of:

`/testpath/param:1921`
___
*[`pkg/server/api_v2_metrics_test.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pz5eJ94rDphxL25kX:-O9Pz5eJ94rDphxL25kY:bh99fid) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L134)):*
> ```Go
> 	}
> }
> ```

This is going to be more important for the grpc metrics (if we add them) but to get familiar with the practice I recommend adding a benchmark here. Something to the effect of:

```go
func BenchHTTPMetricsEnabled(b *testing.B) {
clusterSettings := cluster.MakeTestingClusterSettings()
	serverMetrics := NewHttpServerMetrics(metric.NewRegistry(), clusterSettings)
	router := mux.NewRouter()
	serverMetrics.registerMetricsMiddleware(router)
	router.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(time.Millisecond)
		w.WriteHeader(http.StatusOK)
	}))

	for i := 0; i < b.N; i++ {
		getReq1, err := http.NewRequest("GET", server.URL+"/mypath/1/", nil)
		require.NoError(t, err)
		getReq2, err := http.NewRequest("GET", server.URL+"/mypath/2/", nil)
		require.NoError(t, err)
		postReq2, err := http.NewRequest("POST", server.URL+"/mypath/2/", nil)
		require.NoError(t, err)
		putReq3, err := http.NewRequest("PUT", server.URL+"/mypath/1/", nil)
		require.NoError(t, err)
	}
}

// do the same but disable metrics
func BenchHTTPMetricsDisabled...

// do the same but do not register the metrics middleware
func BenchHTTPNoMetrics...
```

to run this, you would run `go test ./pkg/server/... -bench=BenchHTTPMetricsEnabled`


<!-- Sent from Reviewable.io -->

2024-10-17 18:16 UTC, kyle-a-wong reviewed
This does capture those 3. Prometheus histograms essentially create 3 metrics: <metricName>_bucket, <metricName>_sum, and <metricname>_count. 

Rate: You can use the <metricname>_count metric with rate() function to get the requests/sec.
Duration: you can use the <metricname>_bucket to with histogram_percentile to get duration percentiles
Error: You can filter on "statusCode" label to get error rates / durations 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-:-O9QYoUm6JYHK9XPMb-s:bw1608u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, @dhartunian, and @xinhaoz)

___
*[`pkg/server/api_v2_metrics.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pld3UC2oNAWyz7I9H:-O9Q_66P32KQYzBPJgJU:b-ydonir) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L6)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I would name these `http_metrics.go` instead of `api_v2_metrics`
</blockquote></details>

Done. Good idea.
___
*[`pkg/server/api_v2_metrics.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PlkxL1V7QpAkhzCq1:-O9QXJnk6FZCDi9t534h:bouhn8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L62)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Unless you feel strongly otherwise, this should include the unit type `http.server.request.duration_ms`.
</blockquote></details>

Done. Added "seconds" to it because its currently recording in "seconds". Lmk if you have opinions about this 
___
*[`pkg/server/api_v2_metrics_test.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PrD1v2HULlmKlADYS:-O9QUgnO4XmI43fhaF1_:b-mkr52) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L56)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

An interesting question here is whether changing the cluster setting actually "un-registers" the metrics. Not sure if that utility exists currently, but did you think about that at all
</blockquote></details>

Hm. The utility does exist but the current implementation always registers the metric, whether or not metrics is enabled or not. 

Is the concern that this is unnecessarily using memory by keeping old metrics if it is enabled for some time and disabled?
___
*[`pkg/server/api_v2_metrics_test.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pqnv315NF_7Q0xHeE:-O9QSru16EfOeoMaTGn4:b-sllw3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L121)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I'm confused, shouldn't the path be a literal example of the regex? Something to the effect of:

`/testpath/param:1921`
</blockquote></details>

no, this path string is the template path string used when creating route handlers with mux.  This path string is what is returned from `mux.CurrentRoute(r).GetPathTemplate()` and what we are passing to `formatPathVars` in the production code
___
*[`pkg/server/api_v2_metrics_test.go` line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pz5eJ94rDphxL25kX:-O9QeT8fB9t8fjFwGKis:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L134)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

This is going to be more important for the grpc metrics (if we add them) but to get familiar with the practice I recommend adding a benchmark here. Something to the effect of:

```go
func BenchHTTPMetricsEnabled(b *testing.B) {
clusterSettings := cluster.MakeTestingClusterSettings()
	serverMetrics := NewHttpServerMetrics(metric.NewRegistry(), clusterSettings)
	router := mux.NewRouter()
	serverMetrics.registerMetricsMiddleware(router)
	router.Handle("/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(time.Millisecond)
		w.WriteHeader(http.StatusOK)
	}))

	for i := 0; i < b.N; i++ {
		getReq1, err := http.NewRequest("GET", server.URL+"/mypath/1/", nil)
		require.NoError(t, err)
		getReq2, err := http.NewRequest("GET", server.URL+"/mypath/2/", nil)
		require.NoError(t, err)
		postReq2, err := http.NewRequest("POST", server.URL+"/mypath/2/", nil)
		require.NoError(t, err)
		putReq3, err := http.NewRequest("PUT", server.URL+"/mypath/1/", nil)
		require.NoError(t, err)
	}
}

// do the same but disable metrics
func BenchHTTPMetricsDisabled...

// do the same but do not register the metrics middleware
func BenchHTTPNoMetrics...
```

to run this, you would run `go test ./pkg/server/... -bench=BenchHTTPMetricsEnabled`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 06:35 UTC, arjunmahishi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/util/metric/metric.go` line 1309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9TGYHQEBj3fMuloTCk:-O9TGYHQEBj3fMuloTCl:b1qolg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b02db704abf226dae6599b2635141b9df0b60054/pkg/util/metric/metric.go#L1309)):*
> ```Go
> }
> 
> func NewHistogramVecOpts(metadata Metadata, histOpts prometheus.HistogramOpts) HistogramVecOpts {
> ```

Couple of comments here (non-blocking):

1. Might be worth considering to not expose `prometheus.HistogramOpts` directly to users. This locks us into the prometheus based histogram implementation. Also, if this only expects users to configure the buckets, it can just take the buckets configuration. If the user ends up using any untested configuration, it could lead to unexpected behaviour.
2. The other histogram implementation (the persisted one) exposes some presets for the options. This HistogramVec could also do something similar (maybe even reuse the same thing?). This can help keep the buckets across similar metrics consistent. Example: https://github.com/cockroachdb/cockroach/blob/42f40f59cae3c0fd8842e194d6991c951ab4382f/pkg/util/metric/histogram_buckets.go#L59-L66
___
*[`pkg/server/api_v2_metrics.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pld3UC2oNAWyz7I9H:-O9TEuE97XJd0g0HSIbZ:b-e75uv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L6)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Done. Good idea.
</blockquote></details>

There's a typo :) 
htp_metrics.go -> http_metrics.go


<!-- Sent from Reviewable.io -->

2024-10-18 15:04 UTC, kyle-a-wong reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, @dhartunian, and @xinhaoz)

___
*[`pkg/util/metric/metric.go` line 1309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9TGYHQEBj3fMuloTCk:-O9V8tjR49NyTO8sxJda:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b02db704abf226dae6599b2635141b9df0b60054/pkg/util/metric/metric.go#L1309)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Couple of comments here (non-blocking):

1. Might be worth considering to not expose `prometheus.HistogramOpts` directly to users. This locks us into the prometheus based histogram implementation. Also, if this only expects users to configure the buckets, it can just take the buckets configuration. If the user ends up using any untested configuration, it could lead to unexpected behaviour.
2. The other histogram implementation (the persisted one) exposes some presets for the options. This HistogramVec could also do something similar (maybe even reuse the same thing?). This can help keep the buckets across similar metrics consistent. Example: https://github.com/cockroachdb/cockroach/blob/42f40f59cae3c0fd8842e194d6991c951ab4382f/pkg/util/metric/histogram_buckets.go#L59-L66
</blockquote></details>

Done.
___
*[`pkg/server/api_v2_metrics.go` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pld3UC2oNAWyz7I9H:-O9Uzi3e5UxHKcGnLDSM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L6)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

There's a typo :) 
htp_metrics.go -> http_metrics.go
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 15:19 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, @kyle-a-wong, and @xinhaoz)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9LwHjW2oa_m28IH1_z):*
nit: check spelling.

Can you outline what metrics become available here? It's also unclear if they're labeled in any way. Can you also create an issue and link it here?
___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9VAoCM6UgtRTHjCEOb):*
Would also be nice to see somewhere in this diff what the new metrics look like. The tests don't expose this clearly, the docstrings don't, and neither does the commit message. Any one of those will suffice. I'd like to quickly get a sense of what this looks like in `_status/vars` when we enable it.
___
*[`pkg/server/api_v2_metrics.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PlkxL1V7QpAkhzCq1:-O9VAeBo3MSFzAf6poNl:b-ri6yc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L62)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Done. Added "seconds" to it because its currently recording in "seconds". Lmk if you have opinions about this
</blockquote></details>

Can we namespace with `server.` first? Do we have other metrics that start with `http.` already?
___
*[`pkg/server/http_metrics_test.go` line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9VBcSJEmaAUo5DNhyn:-O9VBcSJEmaAUo5DNhyo:b-m5lpz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a16ba458b14646b700ba6355c52ff0ee8d079f/pkg/server/http_metrics_test.go#L152)):*
> ```Go
> }
> 
> func BenchmarkHTTPMetrics(b *testing.B) {
> ```

Can you add the benchmark results to the commit message?


<!-- Sent from Reviewable.io -->

2024-10-18 19:11 UTC, kyle-a-wong reviewed
> Dismissed @angles-n-daemons from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, @dhartunian, and @xinhaoz)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9LwHjW2oa_m28IH1_z):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: check spelling.

Can you outline what metrics become available here? It's also unclear if they're labeled in any way. Can you also create an issue and link it here?
</blockquote></details>

Done
___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9VAoCM6UgtRTHjCEOb):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Would also be nice to see somewhere in this diff what the new metrics look like. The tests don't expose this clearly, the docstrings don't, and neither does the commit message. Any one of those will suffice. I'd like to quickly get a sense of what this looks like in `_status/vars` when we enable it.
</blockquote></details>

Done.
___
*[`pkg/server/api_v2_metrics.go` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pm9HV1YbTNX26g5pU:-O9VDSoM9wD71uWiyp3S:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L32)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

nice, this is an awesome addition
</blockquote></details>

ack
___
*[`pkg/server/api_v2_metrics.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PlkxL1V7QpAkhzCq1:-O9VDY4FDtUzBUT_Y86C:b1zaeji) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L62)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we namespace with `server.` first? Do we have other metrics that start with `http.` already?
</blockquote></details>

Done. Also changed to use nanos instead of seconds and updated docs and names accordingly. 

We don't have metrics that start with either `http` or `server`, But I switched it to begin with server as you suggested. 
___
*[`pkg/server/api_v2_metrics.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Ppfrc6dbqIYBnp7bc:-O9VDIyh6BnkNnlv8XxV:bb7cwne) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L115)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

nice, pretty cool
</blockquote></details>

ack.
___
*[`pkg/server/api_v2_metrics_test.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PsM6B3_27yva1JXfj:-O9VE7WfBK6H3ok8tek2:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L108)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

nice, this is an awesome check
</blockquote></details>

ack
___
*[`pkg/server/http_metrics_test.go` line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9VBcSJEmaAUo5DNhyn:-O9W1Zzu6Y7kaE_kb58P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75a16ba458b14646b700ba6355c52ff0ee8d079f/pkg/server/http_metrics_test.go#L152)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you add the benchmark results to the commit message?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 14:53 UTC, angles-n-daemons approved these changes
Ah got it, that's awesome.

This is g2g on my end, thanks again for adding this.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-:-O9jXzc-1PaTGzN-m28S:b-xg11h2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/server/api_v2_metrics.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PlkxL1V7QpAkhzCq1:-O9jYQXW6sI_FFgrpm-h:bo68wum) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics.go#L62)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Done. Also changed to use nanos instead of seconds and updated docs and names accordingly. 

We don't have metrics that start with either `http` or `server`, But I switched it to begin with server as you suggested.
</blockquote></details>

nice, thanks for these changes
___
*[`pkg/server/api_v2_metrics_test.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9PrD1v2HULlmKlADYS:-O9jYwUg8W4w-kUL7KY2:bg12pi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L56)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

Hm. The utility does exist but the current implementation always registers the metric, whether or not metrics is enabled or not. 

Is the concern that this is unnecessarily using memory by keeping old metrics if it is enabled for some time and disabled?
</blockquote></details>

Oh I see, hmm I think that makes sense. I suppose the concern is that those metrics will be included in scrape, tsdb write if it goes from on to off (I think).

That being said, it isn't a big concern. I'm good with this implementation.
___
*[`pkg/server/api_v2_metrics_test.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132714#-O9Pqnv315NF_7Q0xHeE:-O9jZBuCCinOATanlh7e:b8d4a75) ([raw file](https://github.com/cockroachdb/cockroach/blob/63a7d67a22768a4a784cb73d605cce769d7f885a/pkg/server/api_v2_metrics_test.go#L121)):*
<details><summary><i>Previously, kyle-a-wong (Kyle Wong) wrote…</i></summary><blockquote>

no, this path string is the template path string used when creating route handlers with mux.  This path string is what is returned from `mux.CurrentRoute(r).GetPathTemplate()` and what we are passing to `formatPathVars` in the production code
</blockquote></details>

Oh I see..makes sense, thanks for clarifying


<!-- Sent from Reviewable.io -->

2024-10-21 15:09 UTC, kyle-a-wong commented
tftr!

bors r+

2024-10-21 16:09 UTC, merged