kvserver: only start split tracing if we might record it
cockroachdb/cockroach pull request #132859
Opened 2024-10-17 18:53 UTC by andrewbaptist

Previously we always started tracing in the replicate queue but only recorded the span if expensive logging was enabled. Now we check earlier in the process.

Part of: #104035

Release note: None

2024-10-17 18:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/132859)
<!-- Reviewable:end -->

2024-10-18 14:36 UTC, kvoli requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132859)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-O9V2OLeAyUqzGlWEu4I):*
split queue?
___
*[`pkg/kv/kvserver/split_queue.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-O9V2iDf6CxC6DOhJexd:-O9V2iDf6CxC6DOhJexe:b-jmc64z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c053896517daefec6f698dc9a65b240abcb8e7b/pkg/kv/kvserver/split_queue.go#L250)):*
> ```Go
> 		opts = append(opts, tracing.WithRecording(tracingpb.RecordingVerbose))
> 	}
> 	ctx, sp := tracing.EnsureChildSpan(ctx, sq.Tracer, "split", opts...)
> ```

Do we only need to ensure the child span if expensive logging is enabled as well?


<!-- Sent from Reviewable.io -->

2024-10-18 16:22 UTC, andrewbaptist reviewed
TFTR!

I fixed the commit typo.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-:-O9VQvrv5rnAXzDiiiml:b-saph1d)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-O9V2OLeAyUqzGlWEu4I):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

split queue?
</blockquote></details>

Fixed
___
*[`pkg/kv/kvserver/split_queue.go` line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-O9V2iDf6CxC6DOhJexd:-O9VQYsGADFKunxhkbQE:bkdz37h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c053896517daefec6f698dc9a65b240abcb8e7b/pkg/kv/kvserver/split_queue.go#L250)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Do we only need to ensure the child span if expensive logging is enabled as well?
</blockquote></details>

My understanding is that we still want the "span" to be started for this, but we don't need to start verbose logging. An example would be the case where someone was manually enqueuing from the UI with tracing. In that case we would already have tracing set up on the context, but we want to start the span so the jaeger trace shows a new section.


<!-- Sent from Reviewable.io -->

2024-10-18 17:19 UTC, kvoli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132859#-:-O9Vd8Z98I2p8U2jE7a0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)



<!-- Sent from Reviewable.io -->

2024-10-18 17:58 UTC, merged