workload/schemachange: setColumnType operations will occasionally fail
cockroachdb/cockroach pull request #133131
Opened 2024-10-21 22:50 UTC by Dedej-Bergin

Previously this test would fail due to 0A000 and 2BP01 even though those failures are expected.
In these code changes we properly handle these errors.

Epic: CRDB-25314

Fixes: #66662
Release note: None

2024-10-21 22:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/133131)
<!-- Reviewable:end -->

2024-10-22 13:09 UTC, spilchen requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @nameisbhaskar, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oI9T-Bv9pZif3flhB:-O9oI9T-Bv9pZif3flhC:b-d8qrsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2531)):*
> ```Go
> 			{code: pgcode.CannotCoerce, condition: kind == schemachange.ColumnConversionImpossible},
> 		})
> 		stmt.potentialExecErrors.add(pgcode.FeatureNotSupported)
> ```

Is this added because we complain that "not supported inside a transaction"? If so, please add a comment. We can get rid of this over the course of the alter type epic as this is a restriction in legacy schema changer only.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oGawg6a0MtCOe8a3u:-O9oGawhEy1ANd2UWAZ-:befltqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2539)):*
> ```Go
> 	})
> 
> 	stmt.potentialExecErrors.add(pgcode.DependentObjectsStillExist)
> ```

Why was this added? I thought the `colIsRefByComputed` check you added earlier should already handle the `DependentObjectsStillExist` error.
___
*[`pkg/workload/schemachange/optype.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oJ5QlEtcdT_Nj8ytq:-O9oJ5QlEtcdT_Nj8ytr:b-pp4oy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/optype.go#L271)):*
> ```Go
> 	alterTableAddConstraintForeignKey: 1,
> 	alterTableAddConstraintUnique:     1,
> 	alterTableAlterColumnType:         1,
> ```

There might be other errors we should look for before enabling:
- if the column we are attempting to alter has a TTL expression, we will fail with `pgcode.InvalidTableDefinition`
- if the column we are attempting to alter is used as a identity column and we try to convert it to a non-int, we will fail with `pgcode.InvalidParameterValue`
- we don't specify the `USING` expression, so it's possible that we could pick a data type that doesn't have an automatic cast. This would return a `pgcode.DatatypeMismatch` error.


<!-- Sent from Reviewable.io -->

2024-10-22 14:33 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oI9T-Bv9pZif3flhB:-O9o_rKe5U-sxc500mOI:b-xuio7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2531)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this added because we complain that "not supported inside a transaction"? If so, please add a comment. We can get rid of this over the course of the alter type epic as this is a restriction in legacy schema changer only.
</blockquote></details>

Yes, and sounds good, just added the comment, thanks!
___
*[`pkg/workload/schemachange/operation_generator.go` line 2539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oGawg6a0MtCOe8a3u:-O9o_C1WCWaPyiSRNeDD:b-43jnyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2539)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Why was this added? I thought the `colIsRefByComputed` check you added earlier should already handle the `DependentObjectsStillExist` error.
</blockquote></details>

It's supposed to, but it doesn't catch everything.  I just now tried removing the potentialExecErrors line and was able to repro the issue.

```
Schema Workload Stats
Total Schema Statements Executed = 9
Total Schema Statements Succeeded = 9
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 5
Total Transactions Rolled Back = 8
Total Transactions Executed = 13
test logs left over in: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
--- FAIL: TestWorkload (6.62s)
    test_log_scope.go:165: test logs captured to: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
    test_log_scope.go:76: use -show-logs to present logs inline
    schema_change_external_test.go:131: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:131
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: cannot alter type of column "col1_w0_3" because computed column "crdb_internal_col1_w0_3_shard_16" depends on it (SQLSTATE 2BP01)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3197
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:503
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:600
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:120
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_arm64.s:1222
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: cannot alter type of column "col1_w0_3" because computed column "crdb_internal_col1_w0_3_shard_16" depends on it (SQLSTATE 2BP01)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
    schema_change_external_test.go:96: backup, tracing data, and system table dumps in /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
    panic.go:626: -- test log scope end --
FAIL
I241022 14:14:07.876469 1 (gostd) testmain.go:85  [-] 1  Test //pkg/ccl/testccl/workload/schemachange:schemachange_test exited with error code 1
================================================================================
Target //pkg/ccl/testccl/workload/schemachange:schemachange_test up-to-date:
  _bazel/bin/pkg/ccl/testccl/workload/schemachange/schemachange_test_/schemachange_test
ERROR: Test failed, aborting
INFO: Elapsed time: 356.526s, Critical Path: 144.07s
INFO: 769 processes: 235 remote cache hit, 13 internal, 521 darwin-sandbox.
INFO: Build completed successfully, 769 total actions
//pkg/ccl/testccl/workload/schemachange:schemachange_test             NO STATUS
  /private/var/tmp/_bazel_bdedej/3d5e8839f3c3e22b0d07becaa01ecc28/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin_arm64-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_757_of_1000/test.log

Executed 1 out of 1 test: 1 was skipped.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
ERROR: exit status 3
bdedej@crlMBP-Q332WJTGM9MjU1 cockroach % git diff
diff --git a/pkg/workload/schemachange/operation_generator.go b/pkg/workload/schemachange/operation_generator.go
index 73374cbf758..86446811834 100644
--- a/pkg/workload/schemachange/operation_generator.go
+++ b/pkg/workload/schemachange/operation_generator.go
@@ -2528,6 +2528,8 @@ func (og *operationGenerator) setColumnType(ctx context.Context, tx pgx.Tx) (*op
                stmt.expectedExecErrors.addAll(codesWithConditions{
                        {code: pgcode.CannotCoerce, condition: kind == schemachange.ColumnConversionImpossible},
                })
+               // We can get rid of this over the course of the alter type epic
+               // as this is a restriction in the legacy schema changer only
                stmt.potentialExecErrors.add(pgcode.FeatureNotSupported)
        }
 
@@ -2536,8 +2538,6 @@ func (og *operationGenerator) setColumnType(ctx context.Context, tx pgx.Tx) (*op
                {code: pgcode.DependentObjectsStillExist, condition: columnHasDependencies || colIsRefByComputed},
        })
 
-       stmt.potentialExecErrors.add(pgcode.DependentObjectsStillExist)
-
        stmt.sql = fmt.Sprintf(`%s ALTER TABLE %s ALTER COLUMN %s SET DATA TYPE %s`,
                setSessionVariableString, tableName.String(), columnForTypeChange.name.String(), newTypeName.SQLString())
        return stmt, nil
diff --git a/pkg/workload/schemachange/optype.go b/pkg/workload/schemachange/optype.go
index 5c0fc0a33fb..f393031f365 100644
--- a/pkg/workload/schemachange/optype.go
+++ b/pkg/workload/schemachange/optype.go
@@ -268,7 +268,7 @@ var opWeights = []int{
        alterTableAddColumn:               1,
        alterTableAddConstraintForeignKey: 1,
        alterTableAddConstraintUnique:     1,
-       alterTableAlterColumnTy [...]

2024-10-22 15:02 UTC, Dedej-Bergin reviewed
I do want to point out that with these code changes, there is a new error that is now exposed.

This is with `alterTableAlterColumnType:         20,` and even then it still takes over 100 iterations to hit.  So with a weight of 1 this would probably only be hit every 3 runs with stress.

My thoughts are to open this up as a separate issue and to still set alterTableAlterColumnType to 1 for this PR, so that we can get some test coverage.  Although I'm not entirely sure if that is the best way to handle this.

Let me know what you think, maybe there's a simple solution to this issue that I could implement inside this PR, thanks!

```
{
 "workerId": 1,
 "clientTimestamp": "14:51:27.740433",
 "ops": [
  "BEGIN",
  {
   "sql": "INSERT INTO public.table_w0_9 (col9_w0_10) VALUES ('1974-08-15 12:02:00.000803+00':::TIMESTAMPTZ),('1974-06-17 19:07:45.000236+00':::TIMESTAMPTZ),('1992-07-17 13:57:01.000489+00':::TIMESTAMPTZ)",
   "potentialExecErr": "23502,23505,23514"
  },
  "COMMIT"
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": ""
}
Schema Workload Stats
Total Schema Statements Executed = 25
Total Schema Statements Succeeded = 25
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 17
Total Transactions Rolled Back = 9
Total Transactions Executed = 26
test logs left over in: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/ae64776402bdf2501e8ccdea0e09f210/logTestWorkload63108737
--- FAIL: TestWorkload (7.47s)
    test_log_scope.go:165: test logs captured to: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/ae64776402bdf2501e8ccdea0e09f210/logTestWorkload63108737
    test_log_scope.go:76: use -show-logs to present logs inline
    schema_change_external_test.go:131: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:131
        	Error:      	Received unexpected error:
        	            	***FAIL; Failed to receive an execution error when errors were expected
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3218
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:503
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:600
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:120
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_arm64.s:1222
        	            	Wraps: (4) ***FAIL; Failed to receive an execution error when errors were expected
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.leafError
        	Test:       	TestWorkload
    schema_change_external_test.go:96: backup, tracing data, and system table dumps in /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/ae64776402bdf2501e8ccdea0e09f210/logTestWorkload63108737
    panic.go:626: -- test log scope end --
FAIL
I241022 14:51:28.966472 1 (gostd) testmain.go:85  [-] 1  Test //pkg/ccl/testccl/workload/schemachange:schemachange_test exited with error code 1
================================================================================
Target //pkg/ccl/testccl/workload/schemachange:schemachange_test up-to-date:
  _bazel/bin/pkg/ccl/testccl/workload/schemachange/schemachange_test_/schemachange_test
ERROR: Test failed, aborting
INFO: Elapsed time: 294.741s, Critical Path: 50.72s
INFO: 780 processes: 663 remote cache hit, 12 internal, 105 darwin-sandbox.
INFO: Build completed successfully, 780 total actions
//pkg/ccl/testccl/workload/schemachange:schemachange_test             NO STATUS
  /private/var/tmp/_bazel_bdedej/3d5e8839f3c3e22b0d07becaa01ecc28/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin_arm64-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_112_of_1000/test.log

Executed 1 out of 1 test: 1 was skipped.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
ERROR: exit status 3
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-:-O9ohgsi51LthPdtRfVb:baws7x)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @spilchen, and @srosenberg)



<!-- Sent from Reviewable.io -->

2024-10-22 16:12 UTC, spilchen requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin, @nameisbhaskar, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oI9T-Bv9pZif3flhB:-O9oxw64ErV3j9yInAWW:b68ctv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2531)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Yes, and sounds good, just added the comment, thanks!
</blockquote></details>

nit: lets call out what in the legacy schema changer depends on this. Namely the restriction that alter type cannot be executed inside a transaction.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oGawg6a0MtCOe8a3u:-O9oyUQACDHnjnnUXPMb:bqc0q2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2539)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

It's supposed to, but it doesn't catch everything.  I just now tried removing the potentialExecErrors line and was able to repro the issue.

```
Schema Workload Stats
Total Schema Statements Executed = 9
Total Schema Statements Succeeded = 9
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 5
Total Transactions Rolled Back = 8
Total Transactions Executed = 13
test logs left over in: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
--- FAIL: TestWorkload (6.62s)
    test_log_scope.go:165: test logs captured to: /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
    test_log_scope.go:76: use -show-logs to present logs inline
    schema_change_external_test.go:131: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:131
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: cannot alter type of column "col1_w0_3" because computed column "crdb_internal_col1_w0_3_shard_16" depends on it (SQLSTATE 2BP01)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3197
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:503
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:600
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:120
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_arm64.s:1222
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: cannot alter type of column "col1_w0_3" because computed column "crdb_internal_col1_w0_3_shard_16" depends on it (SQLSTATE 2BP01)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
    schema_change_external_test.go:96: backup, tracing data, and system table dumps in /Users/bdedej/go/src/github.com/cockroachdb/cockroach/y/_tmp/4110c2a4c923e6761145259044ae6cd3/logTestWorkload1324955314
    panic.go:626: -- test log scope end --
FAIL
I241022 14:14:07.876469 1 (gostd) testmain.go:85  [-] 1  Test //pkg/ccl/testccl/workload/schemachange:schemachange_test exited with error code 1
================================================================================
Target //pkg/ccl/testccl/workload/schemachange:schemachange_test up-to-date:
  _bazel/bin/pkg/ccl/testccl/workload/schemachange/schemachange_test_/schemachange_test
ERROR: Test failed, aborting
INFO: Elapsed time: 356.526s, Critical Path: 144.07s
INFO: 769 processes: 235 remote cache hit, 13 internal, 521 darwin-sandbox.
INFO: Build completed successfully, 769 total actions
//pkg/ccl/testccl/workload/schemachange:schemachange_test             NO STATUS
  /private/var/tmp/_bazel_bdedej/3d5e8839f3c3e22b0d07becaa01ecc28/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin_arm64-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_757_of_1000/test.log

Executed 1 out of 1 test: 1 was skipped.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
ERROR: exit status 3
bdedej@crlMBP-Q332WJTGM9MjU1 cockroach % git diff
diff --git a/pkg/workload/schemachange/operation_generator.go b/pkg/workload/schemachange/operation_generator.go
index 73374cbf758..86446811834 100644
--- a/pkg/workload/schemachange/operation_generator.go
+++ b/pkg/workload/schemachange/operation_generator.go
@@ -2528,6 +2528,8 @@ func (og *operationGenerator) setColumnType(ctx context.Context, tx pgx.Tx) (*op
                stmt.expectedExecErrors.addAll(codesWithConditions{
                        {code: pgcode.CannotCoerce, condition: kind == schemachange.ColumnConversionImpossible},
                })
+               // We can get rid of this over the course of the alter type epic
+               // as this is a restriction in the legacy schema changer only
                stmt.potentialExecErrors.add(pgcode.FeatureNotSupported)
        }
 
@@ -2536,8 +2538,6 @@ func (og *operationGenerator) setColumnType(ctx context.Context, tx pgx.Tx) (*op
                {code: pgcode.DependentObjectsStillExist, condition: columnHasDependencies || colIsRefByComputed},
        })
 
-       stmt.potentialExecErrors.add(pgcode.DependentObjectsStillExist)
-
        stmt.sql = fmt.Sprintf(`%s ALTER TABLE %s ALTER COLUMN %s SET DATA TYPE %s`,
                setSessionVariableString, tableName.String(), columnForTypeChange.name.String(), newTypeName.SQLString())
        return stmt, nil
diff --git a/pkg/workload/schemachange/optype.go b/pkg/workload/schemachange/optype.go
index 5c0fc0a33fb..f393031f365 100644
--- a/pkg/workload/schemachange/optype.go
+++ b/pkg/workload/schemachange/optype.go
@@ -268,7 +268,7 @@ var opWeights = []int{
        alterTableAddColumn:               1,
        alterTableAddConstraintForeignKey: 1,
        alterTableAddConstraintUnique:     1,
-       alterTableAlterColumnType:         1,
+       alterTableAlterColumnType:         20,
        alterTableAlterPrimaryKey:         1,
        alterTableDropColumn:            [...]

2024-11-01 14:00 UTC, Dedej-Bergin reviewed
The error that I pointed out just before this is now handled properly with our code changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-:-OAc-br27uDYMLdw-d4h:b-f6gver)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nameisbhaskar, @spilchen, and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oI9T-Bv9pZif3flhB:-OAc-oZa1RUvuFIvo_ZU:b-3jnfir) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2531)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: lets call out what in the legacy schema changer depends on this. Namely the restriction that alter type cannot be executed inside a transaction.
</blockquote></details>

Sounds good, just added it, thanks!
___
*[`pkg/workload/schemachange/operation_generator.go` line 2539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oGawg6a0MtCOe8a3u:-OAc-vHO5WyKAyyw8yGg:b-3zrmm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2539)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we have the DDL for the table? I'm curious to know why `colIsRefByComputed` didn't find the computed column dependency.
</blockquote></details>

So the reason colIsRefByComputed didn't find it, was because we were running another concurrent alter command on that column at the same time and colIsRefByComputed can not handle such scenarios.  However the new hasOngoingAlterPKSchemaChange can handle it so I added that.  I also changed it to potential as there is a potential false negative that can make the test fail.
___
*[`pkg/workload/schemachange/operation_generator.go` line 2543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9ozqVaDjhmMeMZy9D2:-OAc0ZV2E3ImO5m3ZOxv:b-4mpwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/20b04bfb2d95f95400698acb7c513bdaba943cda/pkg/workload/schemachange/operation_generator.go#L2543)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: lets leave a comment for each of these to indicate why they are being added.
</blockquote></details>

Sounds good, I added the comments, thanks!


<!-- Sent from Reviewable.io -->

2024-11-01 15:14 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-:-OAcHfmq7Mjj9QQnqzeO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar and @srosenberg)

___
*[`pkg/workload/schemachange/operation_generator.go` line 2539 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133131#-O9oGawg6a0MtCOe8a3u:-OAcH_R47qtaOE5allDI:b-4evfna) ([raw file](https://github.com/cockroachdb/cockroach/blob/78113f9e550801e989281c441523b3003dd4f16c/pkg/workload/schemachange/operation_generator.go#L2539)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

So the reason colIsRefByComputed didn't find it, was because we were running another concurrent alter command on that column at the same time and colIsRefByComputed can not handle such scenarios.  However the new hasOngoingAlterPKSchemaChange can handle it so I added that.  I also changed it to potential as there is a potential false negative that can make the test fail.
</blockquote></details>

Thanks for tracking this down.


<!-- Sent from Reviewable.io -->

2024-11-01 15:45 UTC, Dedej-Bergin commented
bors r+

2024-11-01 17:41 UTC, merged