sql: fix trigger interaction with computed columns
cockroachdb/cockroach pull request #133328
Opened 2024-10-24 06:07 UTC by DrewKimball

This commit makes the following changes to the way row-level BEFORE triggers interact with computed columns:
* BEFORE triggers now observe NULL values in place of computed columns.
* Modifications to computed columns by BEFORE triggers are ignored.
* Computed columns are re-computed after row-level BEFORE triggers execute.

These changes make the behavior consistent with that of Postgres.

Fixes #132979

Release note: None

2024-10-24 06:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/133328)
<!-- Reviewable:end -->

2024-11-01 16:45 UTC, mgartner requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133328)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/opt/optbuilder/trigger.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcbRYZ5-PnV62Cgghy:-OAcbRYZ5-PnV62Cgghz:b-pywiyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/sql/opt/optbuilder/trigger.go#L136)):*
> ```Go
> 	// the computed columns.
> 	if eventType == tree.TriggerEventInsert || eventType == tree.TriggerEventUpdate {
> 		mb.recomputeComputedColsForTrigger(eventType)
> ```

I think an optbiulder test or two for this would be useful to show how this recomputation is planned.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcap4kCg1T23etbIYP:-OAcap4kCg1T23etbIYQ:b-cmw1d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/sql/opt/optbuilder/trigger.go#L830)):*
> ```Go
> // hasRowLevelTriggers returns true if the table has any row-level triggers that
> // match the given action time and event type.
> func (mb *mutationBuilder) hasRowLevelTriggers(
> ```

This function is not used in this PR - remove it?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcbB6D0OFcgSk6t1vA:-OAcbB6D0OFcgSk6t1vB:bjspmk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2601)):*
> ```
> # see NULLs. In addition, while a BEFORE trigger can modify a computed column,
> # the changed value is ignored. In contrast, the computed column *does* show
> # the effect of modifications to the columns it depends on.
> ```

Does a `WHEN` expression see NULLs for the computed column, or the pre-trigger value of the column? Can you add some tests for this case?


<!-- Sent from Reviewable.io -->

2024-11-04 18:26 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133328)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @mw5h)

___
*[`pkg/sql/opt/optbuilder/trigger.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcbRYZ5-PnV62Cgghy:-OAd83s32o3ycyx86mD1:b-gh93gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/sql/opt/optbuilder/trigger.go#L136)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think an optbiulder test or two for this would be useful to show how this recomputation is planned.
</blockquote></details>

Good idea, Done.
___
*[`pkg/sql/opt/optbuilder/trigger.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcap4kCg1T23etbIYP:-OAsPsnvCoG0B4sKeiDd:b-6ys94u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/sql/opt/optbuilder/trigger.go#L830)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This function is not used in this PR - remove it?
</blockquote></details>

:facepalm: Oops, removed it.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 2601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-OAcbB6D0OFcgSk6t1vA:-OAsPwFr12gAeZwzCwuw:b-54e54) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0f31ae9e8c7af9927f1d02adbcc8d6619bbf50/pkg/ccl/logictestccl/testdata/logic_test/triggers#L2601)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does a `WHEN` expression see NULLs for the computed column, or the pre-trigger value of the column? Can you add some tests for this case?
</blockquote></details>

It sees NULLs, I'll add some tests.


<!-- Sent from Reviewable.io -->

2024-11-06 15:28 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nicely done!

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133328#-:-OB14tQDDhAu0QqHMpl1:b-msncp4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mw5h)



<!-- Sent from Reviewable.io -->

2024-11-06 16:58 UTC, DrewKimball commented
TFTR!

bors r+

2024-11-06 17:37 UTC, DrewKimball commented
bors r-

2024-11-06 17:51 UTC, DrewKimball commented
Needed a rebase.

2024-11-06 22:30 UTC, mgartner commented
bors r+

2024-11-06 23:16 UTC, merged