rac2: order testingRCRange.mu before RaftMu in tests
cockroachdb/cockroach pull request #133686
Opened 2024-10-29 16:00 UTC by kvoli

`testingRCRange.mu` was being acquired, and held before acquiring `RaftMu` in `testingRCRange.admit()`, which conflicted with different ordering (reversed). This was a test only issue with `TestRangeController`.

Order `testingRCRange.mu` before `RaftMu` in `admit()`.

Fixes: #133650
Release note: None

2024-10-29 16:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/133686)
<!-- Reviewable:end -->

2024-10-29 16:08 UTC, kvoli commented
Passes 1k runs under `--stress --deadlock`:

```bash
dev test pkg/kv/kvserver/kvflowcontrol/rac21-vs-fcTestRangeController/handle_raft_event --deadlock --stress
...
//pkg/kv/kvserver/kvflowcontrol/rac2:rac2_test                           PASSED in 1.5s
  Stats over 1000 runs: max = 1.5s, min = 0.7s, avg = 0.8s, dev = 0.1s
```

2024-10-29 16:42 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133686)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO7BtR62ltQ3echvdJ):*
the code comment in this PR says raftMu is ordered before testingRCRange.mu (which is the correct phrasing).

```
		// We need to ensure that r.mu isn't held before (and while) holding
		// RaftMu, in order to order the locks correctly (RaftMu before
		// testingRCRange.mu).
```
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO8BhZ2TVxGMCVn__R:-OAO8BhZ2TVxGMCVn__S:bdute16) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f226e8fb2c1f5e1e90c7de62f6bd43bde4eb861/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L508)):*
> ```Go
> }
> 
> func (r *testingRCRange) admit(ctx context.Context, storeID roachpb.StoreID, av AdmittedVector) {
> ```

I think we need a code comment where `testingRCRange.mu` is declared on what the lock ordering is. And possibly include why -- I think it is because methods like `testingRCRange.{SendMsgApp,SendMsgAppRaftMuLocked}` need to acquire `testingRCRange.mu` and are called with `raftMu` held.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO8nWN2tWvdvsz38bu:-OAO8nWN2tWvdvsz38bv:b-698o7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f226e8fb2c1f5e1e90c7de62f6bd43bde4eb861/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L534)):*
> ```Go
> 		// Ensure that Match doesn't lag behind the highest index in the
> 		// AdmittedVector.
> 		repl.info.Match = max(repl.info.Match, v)
> ```

shouldn't we be doing this updating of `repl` which lives in `r.mu.r.replicaSet` in the closure above while holding `r.mu`?


<!-- Sent from Reviewable.io -->

2024-10-29 16:59 UTC, kvoli reviewed
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-:-OAOCv7H7jknXfDqz7dr:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO7BtR62ltQ3echvdJ):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the code comment in this PR says raftMu is ordered before testingRCRange.mu (which is the correct phrasing).

```
		// We need to ensure that r.mu isn't held before (and while) holding
		// RaftMu, in order to order the locks correctly (RaftMu before
		// testingRCRange.mu).
```
</blockquote></details>

Fixed. The lock ordering notation / wording always gives me the run around.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO8BhZ2TVxGMCVn__R:-OAOBUF64EamZ3Ueiboy:b-wpbmn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f226e8fb2c1f5e1e90c7de62f6bd43bde4eb861/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L508)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a code comment where `testingRCRange.mu` is declared on what the lock ordering is. And possibly include why -- I think it is because methods like `testingRCRange.{SendMsgApp,SendMsgAppRaftMuLocked}` need to acquire `testingRCRange.mu` and are called with `raftMu` held.
</blockquote></details>

Yeah that is why. Added.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-OAO8nWN2tWvdvsz38bu:-OAOBaMj1UsBOLWf__YL:b-f0rfgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f226e8fb2c1f5e1e90c7de62f6bd43bde4eb861/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L534)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't we be doing this updating of `repl` which lives in `r.mu.r.replicaSet` in the closure above while holding `r.mu`?
</blockquote></details>

Yes we should, interesting that it didn't trip the race detector (which I didn't run locally because it doesn't work with deadlock).

Fixed.


<!-- Sent from Reviewable.io -->

2024-10-29 18:06 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133686#-:-OAOSErP39nD65SvU-_r:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)



<!-- Sent from Reviewable.io -->

2024-10-29 18:07 UTC, kvoli commented
TYFTR!

bors r=sumeerbhola

2024-10-29 18:50 UTC, merged

2024-10-30 15:41 UTC, kvoli commented
blathers backport 24.3

2024-10-30 18:04 UTC, kvoli commented
blathers backport 24.3