sql: TestIndexBackfillMergeRetry failed
cockroachdb/cockroach pull request #134346
Opened 2024-11-05 22:03 UTC by Dedej-Bergin

This test fails under duress so we are skipping it.

Fixes: #134033
Release note: None

2024-11-05 22:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/134346)
<!-- Reviewable:end -->

2024-11-06 07:10 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134346)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134346#-OB-IAJT2DK1tjBkY-AN):*
the name of the commit (and also the name of the PR) should not describe what test failed. it should describe what the PR is doing. so in this case the title should be:

```
sql: skip TestIndexBackfillMergeRetry under duress
```

take a look at: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title
___
*[`pkg/sql/mvcc_backfiller_test.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134346#-OB-IayL9PzivwOqimGB:-OB-IayM20Sj1Jn4GU75:by8i6bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33e678bfabb9cfe258f178cd24b531b2c8824fa/pkg/sql/mvcc_backfiller_test.go#L60)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 
> 	skip.UnderDuress(t, "TODO(#134033) test fails under duress")
> ```

we can remove the TODO here. normally if we reference an issue in a TODO, it means we're keeping the issue open so we come back later to address it. but in this case we have no plans to return and change anything here.


<!-- Sent from Reviewable.io -->

2024-11-06 07:11 UTC, rafiss commented
added backport labels since this flaked on an older branch

2024-11-06 15:51 UTC, Dedej-Bergin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134346)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134346#-OB-IAJT2DK1tjBkY-AN):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the name of the commit (and also the name of the PR) should not describe what test failed. it should describe what the PR is doing. so in this case the title should be:

```
sql: skip TestIndexBackfillMergeRetry under duress
```

take a look at: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#Commit-title
</blockquote></details>

Sounds good, thanks I updated the PR name and the commit message.
___
*[`pkg/sql/mvcc_backfiller_test.go` line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134346#-OB-IayL9PzivwOqimGB:-OB19vKY7RSsbttBCLGg:b-ngtfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33e678bfabb9cfe258f178cd24b531b2c8824fa/pkg/sql/mvcc_backfiller_test.go#L60)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we can remove the TODO here. normally if we reference an issue in a TODO, it means we're keeping the issue open so we come back later to address it. but in this case we have no plans to return and change anything here.
</blockquote></details>

Sounds good, I removed the TODO thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-11-06 18:46 UTC, rafiss approved these changes

2024-11-06 18:47 UTC, Dedej-Bergin commented
bors r+

2024-11-06 18:47 UTC, Dedej-Bergin commented
TFTR! @rafiss

2024-11-06 21:32 UTC, Dedej-Bergin commented
bors r+

2024-11-06 22:47 UTC, merged