sql/schemachanger: Prevent Temporary Disappearance of Altered Columns
cockroachdb/cockroach pull request #134411
Opened 2024-11-06 14:32 UTC by spilchen

Previously, during an ALTER COLUMN ... TYPE operation, the column being modified could briefly disappear, leading to "column does not exist" errors for any queries attempting to access it. This issue arose from the incorrect ordering of dependency rules, which has now been addressed.

The changes to the dependency rules during the column type alteration are as follows:
- The name of the new column is not set until we are ready to make it public. Previously, the column name was assigned too early in the pre-commit phase, which necessitated additional shadow transient column name logic. This new approach simplifies the process and eliminates the need for that extra rename logic.
- The ColumnName and Column elements for both the old and new columns are swapped within the same stage.

I have also maintained the existing rules for cases where the column type is not being altered by utilizing the IsAlterColumnTypeOp and IsNotAlterColumnTypeOp predicates.

I updated existing tests to query the column during each stage of the alter. This allowed me to reproduce the issue.

Epic: CRDB-25314
Closes #133996
Release note: none

2024-11-06 14:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/134411)
<!-- Reviewable:end -->

2024-11-08 21:54 UTC, fqazi requested changes
Please add the deps command to: pkg/sql/schemachanger/scplan/testdata/alter_table_alter_column_type so that we can confirm which rules are firing as well.

> Reviewed 57 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-:-OBClCs008HWGNaI7ifg:b-8j7q04)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go` line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-OBCiRmpDeWJwftTns1p:-OBCiRmpDeWJwftTns1q:b26bubz) ([raw file](https://github.com/cockroachdb/cockroach/blob/59a59b3e73c8624e5be3590167963d10265d33f1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go#L230)):*
> ```Go
> 
> 	// This rule is similar to the previous one but applies specifically to ALTER COLUMN ... TYPE operations.
> 	// It uses SameStagePrecedence to enable the swapping of dropped and added columns within the same stage.
> ```

Just as a sanity what happens to the plan without SameStagePrecedence?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_column.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-OBCiyqF7pFqiUSWt75T:-OBCiyqF7pFqiUSWt75U:b-86zcsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/59a59b3e73c8624e5be3590167963d10265d33f1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_column.go#L21)):*
> ```Go
> 
> 	registerDepRule(
> 		"column existence precedes column dependents",
> ```

Nit: could we reduce duplication here some how by having a helper function?

registerDepRule(
		"column existence precedes column dependents",
append(ColumnExistencePrecedes(isColumnDependentExcept),
IsNotAlterColumnTypeOp("table-id", "col-id"))


<!-- Sent from Reviewable.io -->

2024-11-12 13:52 UTC, spilchen reviewed
Thanks for taking a look.

> Please add the deps command to: pkg/sql/schemachanger/scplan/testdata/alter\_table\_alter\_column\_type so that we can confirm which rules are firing as well.

I did have to update `pkg/sql/schemachanger/scplan/testdata/alter_table_alter_column_type`. You can see that I had to make changes to it because the column name is being set in a later stage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-:-OBVRMZ14Fes_7e_IbYI:b12xd7x)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_column.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-OBCiyqF7pFqiUSWt75T:-OBVb_HB-J5UPTxCGfgK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/59a59b3e73c8624e5be3590167963d10265d33f1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_column.go#L21)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: could we reduce duplication here some how by having a helper function?

registerDepRule(
		"column existence precedes column dependents",
append(ColumnExistencePrecedes(isColumnDependentExcept),
IsNotAlterColumnTypeOp("table-id", "col-id"))
</blockquote></details>

Done
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go` line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-OBCiRmpDeWJwftTns1p:-OBVaXwr2Wa7h7-WwGPI:b-yhv4pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/59a59b3e73c8624e5be3590167963d10265d33f1/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go#L230)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just as a sanity what happens to the plan without SameStagePrecedence?
</blockquote></details>

Without this change, the old column transitions out of the public state (i.e., becomes invisible to end users) in the previous stage, but the new column has not yet been made public. This causes any query for the column during that stage to fail with `column "<col-name>" does not exist`.


<!-- Sent from Reviewable.io -->

2024-11-12 14:46 UTC, fqazi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134411#-:-OBVpmMx0GqN4niJDbln:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)



<!-- Sent from Reviewable.io -->

2024-11-12 19:17 UTC, spilchen commented
bors r+

2024-11-12 20:27 UTC, merged