admission: per-store work queue metrics
cockroachdb/cockroach pull request #134854
Opened 2024-11-11 18:42 UTC by aadityasondhi

This patch splits store work queue metrics to be per-store. It also does some general clean up around the `storeGrantCoordinators` code to centralize initialization of requesters and metrics.

Fixes #131562

Release note: None

2024-11-11 18:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/134854)
<!-- Reviewable:end -->

2024-11-12 16:01 UTC, sumeerbhola requested changes
nice!
Do we need to change overload.tsx?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-:-OBW5W8L-A77lJhUjrti:b8lqhot)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @itsbilal)

___
*[`pkg/server/node.go` line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-OBW33Kd6Y6_4x5vX8O-:-OBW33Kd6Y6_4x5vX8O0:b-j7mg29) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d638cbf0c859e2fc8180f9daf0e083eca07159d/pkg/server/node.go#L1371)):*
> ```Go
> 			WriteStallCount: m.WriteStallCount,
> 			DiskStats:       diskStats,
> 			MetricsRegistry: store.Registry(),
> ```

Adding `MetricsRegistry` to `admission.StoreMetrics` doesn't seem very principled. The caller only wants this once and these are not Pebble metrics. An alternative would be to change `StoreGrantCoordinators.SetPebbleMetricsProvider` to pass in an interface that allows retrieval of the `*metric.Registry` for a store.

Something like `StoreGrantCoordinators.SetPebbleMetricsProviderAndMetricRegistry` which receives a
```
type MetricsRegistryProvider interface {
  GetMetricsRegistry(roachpb.StoreID) *metric.Registry
}
```


<!-- Sent from Reviewable.io -->

2024-12-04 19:46 UTC, aadityasondhi reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-:-ODICGwa9GmduRJokSQF:b-896fix)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/server/node.go` line 1371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-OBW33Kd6Y6_4x5vX8O-:-ODICIOP-ucTpIBfwmi3:b-ioz347) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d638cbf0c859e2fc8180f9daf0e083eca07159d/pkg/server/node.go#L1371)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Adding `MetricsRegistry` to `admission.StoreMetrics` doesn't seem very principled. The caller only wants this once and these are not Pebble metrics. An alternative would be to change `StoreGrantCoordinators.SetPebbleMetricsProvider` to pass in an interface that allows retrieval of the `*metric.Registry` for a store.

Something like `StoreGrantCoordinators.SetPebbleMetricsProviderAndMetricRegistry` which receives a
```
type MetricsRegistryProvider interface {
  GetMetricsRegistry(roachpb.StoreID) *metric.Registry
}
```
</blockquote></details>

I made the change, it is in a separate commit for now. Let me know what you think.


<!-- Sent from Reviewable.io -->

2024-12-08 22:09 UTC, sumeerbhola requested changes
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134854)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @itsbilal)

___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-ODcJLN9CEgPlEV88i9n:-ODcJLN9CEgPlEV88i9o:b-kyhw38) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b376e3cc435ec8f05b49ba7a3fb029fcac5076/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L69)):*
> ```XML
>     <LineGraph
>       title="Admission IO Tokens Exhausted Duration Per Second"
>       sources={storeSources}
> ```

how does this look when running a multi-store roachtest?
___
*[`pkg/server/node.go` line 1408 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-ODcIU5b0IJoOR7Uibzf:-ODcIU5b0IJoOR7Uibzg:b-6vgxmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b376e3cc435ec8f05b49ba7a3fb029fcac5076/pkg/server/node.go#L1408)):*
> ```Go
> 	storeID roachpb.StoreID,
> ) *metric.Registry {
> 	registryMap := mrp.n.stores.GetStoreMetricRegistryMap()
> ```

why is this calling a method that needs to generate a map when this method only needs the registry for `storeID`? It could just pass this `storeID` parameter to `Stores` and get the registry.


<!-- Sent from Reviewable.io -->

2025-01-06 21:02 UTC, aadityasondhi commented
Roachtest running with multiple stores:

<img width="986" alt="image" src="https://github.com/user-attachments/assets/181e5403-6da2-4bb3-b67e-42015a08acc4" />

For all overload store metrics, we show each individual store and the corresponding max among all stores in that node.

2025-01-06 21:05 UTC, aadityasondhi reviewed
Apologies for the delay in getting back to this. It kept falling through the cracks.

I think it is good for a final review before merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-:-OFxQsXKALgAqyawFEcL:b-25wdug)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/server/node.go` line 1408 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-ODcIU5b0IJoOR7Uibzf:-OFxQ_ww1yBt1n5PYOfI:bwx42rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b376e3cc435ec8f05b49ba7a3fb029fcac5076/pkg/server/node.go#L1408)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this calling a method that needs to generate a map when this method only needs the registry for `storeID`? It could just pass this `storeID` parameter to `Stores` and get the registry.
</blockquote></details>

Ah I did not realize we had that reference :face_palm:. I have fixed it now.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx` line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-ODcJLN9CEgPlEV88i9n:-OFxQTOB94wUg4nJpTg3:b-30v6is) ([raw file](https://github.com/cockroachdb/cockroach/blob/34b376e3cc435ec8f05b49ba7a3fb029fcac5076/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how does this look when running a multi-store roachtest?
</blockquote></details>

Good call, turns out I was doing this all wrong. I have now fixed it. See the screenshot above.


<!-- Sent from Reviewable.io -->

2025-01-06 22:25 UTC, aadityasondhi commented
Requesting review from @cockroachdb/obs-prs for the UI code changes, since I have very little prior experience changing this code.

2025-01-07 22:40 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo the changes in dashboards/ which I have little experience with too.

> Reviewed 4 of 7 files at r6, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134854#-:-OG1v98k1O-oYu1_lhXa:bqopham)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons and @itsbilal)



<!-- Sent from Reviewable.io -->

2025-01-08 17:26 UTC, dhartunian approved these changes
frontend changes LGTM

2025-01-08 17:37 UTC, aadityasondhi commented
TFTRs!

bors r=sumeerbhola,dhartunian

2025-01-08 18:36 UTC, merged