tablemetadatacache,ui: change error messaging for failed tmj update
cockroachdb/cockroach pull request #134902
Opened 2024-11-11 22:39 UTC by kyle-a-wong

Previously, error messages from the table metaddata update job were surfaced in the UI on the table overview page. These errors are usually overly verbose and don't provide any actionable info to the end user.

In addition to this, error messages can be very big if the error is a result of a span stats fanout failure, which can contain errors for each fanned out request.

Now, db-console will simply report that an error occured in the job and that the data is stale. The error returned from failed SpanStats requests will now have a generic "An error has occurred while fetching span stats."

Epic: None
Release note: None

2024-11-11 22:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/134902)
<!-- Reviewable:end -->

2024-11-12 15:15 UTC, angles-n-daemons requested changes
one small request, looks good otherwise

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-:-OBVwNUl6dtxTmiWkpKq:bd851c8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-OBVvroD9JHP5SClsRBu:-OBVvroD9JHP5SClsRBv:bn5ue1w):*
spelling: metaddata
___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-OBVwCNZ1mP8Vz_B4lDX:-OBVwCNZ1mP8Vz_B4lDY:b-66uvly) ([raw file](https://github.com/cockroachdb/cockroach/blob/5df7efd83ba786bc3f403d7d055aec9f8bffe31b/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L206)):*
> ```Go
> 
> 	if len(res.Errors) > 0 {
> 		// For now, we won't write partial results to the cache.
> ```

Can we log the errors, so if something is failing repeatedly we could see the actual error message?

eg:
```go
for err := range res.Errors {
    log.Error(ctx, err)
}
```


<!-- Sent from Reviewable.io -->

2024-11-12 15:32 UTC, kyle-a-wong reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-OBVwCNZ1mP8Vz_B4lDX:-OBVzUyL06aB_f8CCZ_Q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5df7efd83ba786bc3f403d7d055aec9f8bffe31b/pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go#L206)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Can we log the errors, so if something is failing repeatedly we could see the actual error message?

eg:
```go
for err := range res.Errors {
    log.Error(ctx, err)
}
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-12 19:15 UTC, kyle-a-wong reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134902)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @xinhaoz)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-OBVvroD9JHP5SClsRBu:-OBWnQOf5no3vQOkaAiK:bb7f2mf):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

spelling: metaddata
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-11-12 19:18 UTC, angles-n-daemons approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134902#-:-OBWo7yS16UDT0YNFw37:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-11-12 19:43 UTC, kyle-a-wong commented
tftr!

bors r+

2024-11-12 21:08 UTC, merged