raft: allow inflights size to dynamically increase
cockroachdb/cockroach pull request #135225
Opened 2024-11-14 22:35 UTC by kvoli

`Inflights.Add()` could encounter an OOB panic if more than the configured `Inflights.size` entries were added via `Add()`, despite stating support for this behavior:

```go
// [..] However, Add() is still valid and allowed, for cases when this pacing
// is implemented at the higher app level. The tracker correctly tracks all the
// in-flight entries.
```

Allow the buffer to grow dynamically larger than `Inflights.size`, as it should remain bounded by the `RangeController` in cases where `Full()` is not already checked (such as Raft's on flow control machinery).

Fixes: #135223
Release note: None

2024-11-14 22:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/135225)
<!-- Reviewable:end -->

2024-11-14 22:46 UTC, pav-kv reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/raft/tracker/inflights.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgqMRXAQwMI0Jnal_n:-OBgqMRXAQwMI0Jnal_o:bw8z4wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/51dfa68d92e176c298e4191f35e1bb1b11a65292/pkg/raft/tracker/inflights.go#L81)):*
> ```Go
> 		next -= size
> 	}
> 	if next >= len(in.buffer) {
> ```

Is this branch ever reached at all?

When we get to the last entry (say `size=100`):

```golang
next := 0 + 100
size := 100
if 100 >= 100 {
    next -= 100
}
// next == 0
```
___
*[`pkg/raft/tracker/inflights.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgpy3tAPGR0UjCWwDD:-OBgpy3tAPGR0UjCWwDE:beotf8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/51dfa68d92e176c298e4191f35e1bb1b11a65292/pkg/raft/tracker/inflights.go#L102)):*
> ```Go
> 	}
> 	newBuffer := make([]inflight, newSize)
> 	copy(newBuffer, in.buffer)
> ```

This will never shrink now? Potentially concerning.


<!-- Sent from Reviewable.io -->

2024-11-14 23:34 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/raft/tracker/inflights.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgzVQE7pkPnKHwo7Qn:-OBgzVQE7pkPnKHwo7Qo:bl33acv) ([raw file](https://github.com/cockroachdb/cockroach/blob/51dfa68d92e176c298e4191f35e1bb1b11a65292/pkg/raft/tracker/inflights.go#L77)):*
> ```Go
> func (in *Inflights) Add(index, bytes uint64) {
> 	next := in.start + in.count
> 	size := in.size
> ```

I am very confused by the logic that manages `in.buffer`. It seems a very peculiar implementation of a circular buffer.
The modulus logic here uses `in.size` and not `len(in.buffer)`. Which suggests that say `in.size` was 100 and the stable number of entries were only 2 (due to Add alternating with FreeLE), we would still grow the buffer to 100. Which seems to go against the claim:
```
We grow on demand
// instead of preallocating to inflights.size to handle systems which have
// thousands of Raft groups per process.
```

It seems to me that the original logic should have been to grow up to `in.size` when there were actually that many in-flight entries.

Also, this suggests this PR is not quite right since the modulus logic is incorrect (the buffer could be bigger than `size`). It should do:
```
if in.count == len(in.buffer) {
   // grow
}
```
Then compute `next` using the current length of the buffer.

As a quick fix I think it is ok to grow and never shrink. But I think we should in the future move `rac2.CircularBuffer` into a util package and rewrite this code to use it.


<!-- Sent from Reviewable.io -->

2024-11-14 23:34 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/raft/tracker/inflights.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgpy3tAPGR0UjCWwDD:-OBh0jyp79aOCa_miN1W:b9ppnij) ([raw file](https://github.com/cockroachdb/cockroach/blob/51dfa68d92e176c298e4191f35e1bb1b11a65292/pkg/raft/tracker/inflights.go#L102)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

This will never shrink now? Potentially concerning.
</blockquote></details>

When were we ever shrinking before?


<!-- Sent from Reviewable.io -->

2024-11-15 00:21 UTC, kvoli reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/raft/tracker/inflights.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgzVQE7pkPnKHwo7Qn:-OBhAmJqB1S6gg5Iqevq:b-4ormce) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ebc78e55322adb1e18ccace926180ec0b8c1823/pkg/raft/tracker/inflights.go#L77)):*
> Also, this suggests this PR is not quite right since the modulus logic is incorrect (the buffer could be bigger than `size`). It should do:

I'm not following how `in.count >= in.size` with this change (but I'm also questioning many things about this change myself), the only modifications to `in.size` and `len(in.buffer)` are made in `grow` outside of init, and the method there explicitly sets `in.size` to be equal to `len(in.buffer)` should it ever be smaller (or the `newSize` really).
___
*[`pkg/raft/tracker/inflights.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgqMRXAQwMI0Jnal_n:-OBhAYIp-f569bcmR79k:b-6xgc4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ebc78e55322adb1e18ccace926180ec0b8c1823/pkg/raft/tracker/inflights.go#L81)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Is this branch ever reached at all?

When we get to the last entry (say `size=100`):

```golang
next := 0 + 100
size := 100
if 100 >= 100 {
    next -= 100
}
// next == 0
```
</blockquote></details>

Doesn't this assume `len(in.buffer) == in.size`? That doesn't appear to hold, rather `len(in.buffer) <= in.size`. 
___
*[`pkg/raft/tracker/inflights.go` line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgpy3tAPGR0UjCWwDD:-OBhAjqkAQ7lo0Dc4w6d:b8uyt2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ebc78e55322adb1e18ccace926180ec0b8c1823/pkg/raft/tracker/inflights.go#L102)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

When were we ever shrinking before?
</blockquote></details>

Don't think so from looking around.


<!-- Sent from Reviewable.io -->

2024-11-15 00:36 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/raft/tracker/inflights.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgzVQE7pkPnKHwo7Qn:-OBhEhC-8Muvkzv5ByeC:b-t9pw8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ebc78e55322adb1e18ccace926180ec0b8c1823/pkg/raft/tracker/inflights.go#L77)):*
> Which suggests that say `in.size` was 100 and the stable number of entries were only 2 (due to Add alternating with FreeLE), we would still grow the buffer to 100.

I think the above would not happen only if it shrank to 0.
```
	if in.count == 0 {
		// inflights is empty, reset the start index so that we don't grow the
		// buffer unnecessarily.
		in.start = 0
	}
```


<!-- Sent from Reviewable.io -->

2024-11-15 01:18 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135225)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/raft/tracker/inflights.go` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135225#-OBgzVQE7pkPnKHwo7Qn:-OBhOAGf6bqtE-7syAj9:b-wylj2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ebc78e55322adb1e18ccace926180ec0b8c1823/pkg/raft/tracker/inflights.go#L77)):*
> I'm not following how `in.count >= in.size` with this change

Maybe I am misunderstanding the question: `in.size` is the limit we no longer respect in lazy replication mode, so `in.count` can exceed it. Isn't that attempt what caused the panic.


<!-- Sent from Reviewable.io -->

2024-11-15 02:10 UTC, kvoli commented
I'm in favor of closing this and adopting https://github.com/cockroachdb/cockroach/pull/135237 @pav-kv.

2024-11-15 03:00 UTC, kvoli commented
Closing in favor of https://github.com/cockroachdb/cockroach/pull/135237.

2024-11-15 03:00 UTC, closed without merging