kvserver: add TestFlowControlSendQueueManyInflight test
cockroachdb/cockroach pull request #135331
Opened 2024-11-15 21:14 UTC by kvoli

Add a new RACv2 integration test:
`TestFlowControlSendQueueManyInflight`, which attempts to do the following:

```sql
-- We will exhaust the tokens across all streams while admission is blocked,
-- using a single 16 MiB (deduction, the write itself is small) write. Then,
-- we will write a thousand or so entries (@ 4KiB deduction) which should be
-- queued towards one of the replica send streams, while the other has a send
-- queue prevented from forming. Lastly, we will unblock admission and stress
-- the raft in-flights tracker as the queue is drained.
```

Part of: #132614
Release note: None

2024-11-15 21:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/135331)
<!-- Reviewable:end -->

2024-11-18 19:14 UTC, sumeerbhola requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135331)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/testdata/flow_control_integration_v2/send_queue_many_inflight` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-OC-ffGR4ZJF3qS-qRAt:-OC-ffGR4ZJF3qS-qRAu:b-nae72s) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0572f33ab3df33bf11e32d740419f1e5bc23f3/pkg/kv/kvserver/testdata/flow_control_integration_v2/send_queue_many_inflight#L130)):*
> ```
> ORDER BY name ASC;
> 
>   kvflowcontrol.send_queue.bytes                                    | 4.0 MiB  
> ```

why is this still 4MiB? Shouldn't the send-queue be drained?
___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 4942 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-OC-g-2U2vyoF4xnKWGD:-OC-g-2U2vyoF4xnKWGE:b959go8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0572f33ab3df33bf11e32d740419f1e5bc23f3/pkg/kv/kvserver/flow_control_integration_test.go#L4942)):*
> ```Go
> 	disableWorkQueueGranting.Store(false)
> 	var tokenDeduction atomic.Int64
> 	tokenDeduction.Store(1 /* 1b */)
> ```

was this set to 1B since there are some unknown requests that come through initially? Were they not filtered by the `isTestGeneratedPut`?


<!-- Sent from Reviewable.io -->

2024-11-19 22:21 UTC, kvoli reviewed
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-:-OC5W3oBDPHmLZMtDhc1:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/testdata/flow_control_integration_v2/send_queue_many_inflight` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-OC-ffGR4ZJF3qS-qRAt:-OC5Vh074wrE3xSboL0j:b5l06v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0572f33ab3df33bf11e32d740419f1e5bc23f3/pkg/kv/kvserver/testdata/flow_control_integration_v2/send_queue_many_inflight#L130)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is this still 4MiB? Shouldn't the send-queue be drained?
</blockquote></details>

Ah nice catch. The queue is drained here, the stats are stale. I was missing:

```go
OverrideAlwaysRefreshSendStreamStats: true,
```

To keep the stats fresh on any query. Fixed.
___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 4942 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-OC-g-2U2vyoF4xnKWGD:-OC5V_sc17tUWZaK8xvU:b1aax0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0572f33ab3df33bf11e32d740419f1e5bc23f3/pkg/kv/kvserver/flow_control_integration_test.go#L4942)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was this set to 1B since there are some unknown requests that come through initially? Were they not filtered by the `isTestGeneratedPut`?
</blockquote></details>

This is just me being cautious, I didn't see any issues.


<!-- Sent from Reviewable.io -->

2024-11-20 01:05 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135331#-:-OC65T7RApdY_YZVMit2:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)



<!-- Sent from Reviewable.io -->

2024-11-25 19:19 UTC, kvoli commented
Rebase to resolve merge conflicts.

2024-11-25 21:11 UTC, kvoli commented
Extended CI failure is on bench. TYFTR!

bors r=sumeerbhola

2024-11-25 22:19 UTC, merged