sql/schemachanger: make create sequence revertible
cockroachdb/cockroach pull request #135758
Opened 2024-11-19 22:52 UTC by fqazi

Previously, the concept of reversibility was constant and decided inside the declarative schema changer opgen. While this works fine for simple single statement transactions more complex schema changes involving multiple objects may have different parameters. For example ADD COLUMN SERIAL needs to be able to revert plans after a sequence is created, since that sequence will not be accessible. To help support this patch does the following

1) Revertibility can now be either static or determined by the elements
   within a given plan.
2) Adding Column elements is now considered revertible if the object is
   newly created.
3) Sequence creation is now always considered revertible, since the
   object cannot be for other schema changes until the full transaction
   is complete.

Informs: #126900

Release note: None

2024-11-19 22:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/135758)
<!-- Reviewable:end -->

2024-11-21 12:32 UTC, spilchen requested changes
This looks great! I do have a few questions, mostly for my own understanding.

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-:-OCDhALd4FhX7By_aDmt:b1hypu6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/specs.go` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAR6Dg8cxuQjNjOJ9E:-OCAR6Dg8cxuQjNjOJ9F:b-1666l) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/specs.go#L15)):*
> ```Go
> }
> 
> type RevertibleFn func(e scpb.Element, ctx *opGenContext) bool
> ```

nit: I don't think having parameter names clarifies things. I suggest leaving them out.



_Suggestion:_
```Go
type RevertibleFn func(scpb.Element, *opGenContext) bool
```
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/specs.go` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCARdyH-RzV6rSwTPXc:-OCARHnd8nqw0w5EGbTT:b-smtuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/specs.go#L24)):*
> ```Go
> }
> 
> func notRevertible(e scpb.Element, _ *opGenContext) bool {
> ```

nit: suggest you replace `e` with `_` since its not used
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_column.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDgWhg5g_LMa6j0KsE:-OCDgWhg5g_LMa6j0KsF:b-2h81dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/opgen_column.go#L35)):*
> ```Go
> 			),
> 			to(scpb.Status_PUBLIC,
> 				revertibleFunc(func(e scpb.Element, state *opGenContext) bool {
> ```

Is there any concern about how this change might behave in a mixed-version cluster? Unlike the dependency rules, there’s no version gate here. I assume it’s not an issue, but I wanted to raise it to confirm.
___
*[`pkg/sql/schemachanger/sctest/framework.go` line 952 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCB0FoG8USyJPH0A25d:-OCB0FoG8USyJPH0A25e:b1n703x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/sctest/framework.go#L952)):*
> ```Go
> func hasLatestSchemaChangeSucceeded(t *testing.T, tdb *sqlutils.SQLRunner) bool {
> 	result := tdb.QueryStr(t, fmt.Sprintf(
> 		`SELECT status FROM [SHOW JOBS] WHERE job_type IN ('%s') ORDER BY finished DESC, job_id DESC LIMIT 1`,
> ```

I guess there was a case where two concurrent jobs finished at the same time?
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_validation/alter_table_alter_column_type_validation__rollback_1_of_3.explain` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDgEcm8EfmrOOpNw2X:-OCDgEcm8EfmrOOpNw2Y:b2zcq9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_validation/alter_table_alter_column_type_validation__rollback_1_of_3.explain#L0)):*
I'm curious why these files are showing up in your PR. Was there something missed in a prior change?
___
*[`pkg/sql/schemachanger/testdata/end_to_end/create_sequence_add_column/create_sequence_add_column__statement_2_of_2.explain` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDf42Y5V34ij21HrdT:-OCDf42Y5V34ij21HrdU:bi9f4uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/testdata/end_to_end/create_sequence_add_column/create_sequence_add_column__statement_2_of_2.explain#L129)):*
> ```
>  │              ├── MakeValidatedColumnNotNullPublic {"ColumnID":1,"TableID":105}
>  │              ├── MakeBackfilledIndexMerging {"IndexID":1,"TableID":105}
>  │              ├── MakeWriteOnlyColumnPublic {"ColumnID":1,"TableID":105}
> ```

Are we concerned that the column might reach the public state, but if a legitimate failure occurs before the non-revertible phase, it could unexpectedly disappear for other applications? I guess this happens only because we are also creating a sequence in the same transaction.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAyHZKCEn5A0HGHybP:-OCAyHZKCEn5A0HGHybQ:bhaxtkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L276)):*
> ```Go
> // AddOpEdges adds an op edges connecting the nodes for two statuses of a target.
> func (g *Graph) AddOpEdges(
> 	t *scpb.Target, from, to scpb.Status, revertible bool, canFail bool, ops ...scop.Op,
> ```

nit: I kind of like the old code before.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/target.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAShUs5OwZevTvAaQ1:-OCAShUs5OwZevTvAaQ2:b14eyyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/target.go#L213)):*
> ```Go
> 
> 	// Check for absence of phase and revertibility constraints
> 	if s.revertible != nil {
> ```

Does this need to call the `revertible` function now? A pointer check alone won’t confirm if it’s revertible.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/edge.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCB-OQk8ge2UIlj4Vsf:-OCB-OQk8ge2UIlj4Vsg:bxw8lfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/scgraph/edge.go#L37)):*
> ```Go
> 	// revertible indicates that no operation which destroys information
> 	// permanently or publishes new information externally has yet been
> 	// run for this target. A non-revertible edge can only exist if
> ```

This might just be my lack of knowledge of the schema changer. But I’m not entirely sure what this new comment is trying to convey. Specifically, I’m unclear on the meaning of "generated" in this context and what is meant by an "operation function."


<!-- Sent from Reviewable.io -->

2024-11-25 19:13 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135758)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_column.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDgWhg5g_LMa6j0KsE:-OCZcix08ZPF41oYxnBO:b-pgt3y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/opgen_column.go#L35)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is there any concern about how this change might behave in a mixed-version cluster? Unlike the dependency rules, there’s no version gate here. I assume it’s not an issue, but I wanted to raise it to confirm.
</blockquote></details>

This is safe at the moment because we don't have declarative schema changes in transactions. So, we don't have to worry about creating a sequence and it getting used in the same txn yet (until we add IDENTITY / SERIAL support).

So, if we have existing schema changes they will have some type of data element only getting the old behaviour.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/target.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAShUs5OwZevTvAaQ1:-OCZXb93ApELOwPkkgtg:b-yipbjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/target.go#L213)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Does this need to call the `revertible` function now? A pointer check alone won’t confirm if it’s revertible.
</blockquote></details>

No, the only thing being validated here was that is the revertible function is not in the spec:

// The transition above is equivalent, so it cannot override the revertibility in any way.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/create_sequence_add_column/create_sequence_add_column__statement_2_of_2.explain` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDf42Y5V34ij21HrdT:-OCZ_hisEk9RmdO3ye8I:b-vaq7ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/testdata/end_to_end/create_sequence_add_column/create_sequence_add_column__statement_2_of_2.explain#L129)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Are we concerned that the column might reach the public state, but if a legitimate failure occurs before the non-revertible phase, it could unexpectedly disappear for other applications? I guess this happens only because we are also creating a sequence in the same transaction.
</blockquote></details>

Right, so this is the sequence was created in the same txn. We are saying its fair game for it disappear from an applications view if it rolls back earlier. Otherwise, there is a danger of pushing backfills into non-revertible phases, and those operations can fail.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/edge.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCB-OQk8ge2UIlj4Vsf:-OCZZzo5D75lM4ewUcWt:bb1qs9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/scgraph/edge.go#L37)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

This might just be my lack of knowledge of the schema changer. But I’m not entirely sure what this new comment is trying to convey. Specifically, I’m unclear on the meaning of "generated" in this context and what is meant by an "operation function."
</blockquote></details>

Done.

This was a left over comment from a previous prototype. But the idea behind that one was that stages where opgen generates zero operations will always be revertible. The current approach empower opgen to inject revertibility instead.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAyHZKCEn5A0HGHybP:-OCZ_Qlq4C5-cudu8h3E:b-mkr1ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L276)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: I kind of like the old code before.
</blockquote></details>

Done

Left over from a previous prototype, good point.
___
*[`pkg/sql/schemachanger/sctest/framework.go` line 952 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCB0FoG8USyJPH0A25d:-OCZ_VJ88wCSS-75MQCC:b-6busql) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/sctest/framework.go#L952)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I guess there was a case where two concurrent jobs finished at the same time?
</blockquote></details>

Done.

Yeah, and this is already in master I'll rebase to remove this change.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_validation/alter_table_alter_column_type_validation__rollback_1_of_3.explain` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCDgEcm8EfmrOOpNw2X:-OCZecYb10rADZJmzFmU:bc0ad3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_validation/alter_table_alter_column_type_validation__rollback_1_of_3.explain#L)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I'm curious why these files are showing up in your PR. Was there something missed in a prior change?
</blockquote></details>

Done.

These shouldn't be here left overs from a previous prototype trying a different approach. cleaned them up.


<!-- Sent from Reviewable.io -->

2024-11-25 21:35 UTC, spilchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thank you for your responses—they helped clarify your changes for me.

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-:-OC_Eqw8-k4FLUkg6O5h:b-97miwj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/internal/opgen/target.go` line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135758#-OCAShUs5OwZevTvAaQ1:-OC_ERLzDuC8_a5cr-ly:b9mgcov) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb2825d8a39f90618ca2562249ffcc25d6cbe299/pkg/sql/schemachanger/scplan/internal/opgen/target.go#L213)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

No, the only thing being validated here was that is the revertible function is not in the spec:

// The transition above is equivalent, so it cannot override the revertibility in any way.
</blockquote></details>

Okay, I think I get it now. Thanks.


<!-- Sent from Reviewable.io -->

2024-11-25 21:36 UTC, fqazi commented
@spilchen TFTR!

bors r+

2024-11-25 22:19 UTC, merged