sql: added a NOTICE that a table created using CREATE TABLE AS does n…
cockroachdb/cockroach pull request #135845
Opened 2024-11-20 20:04 UTC by Dedej-Bergin

…ot inherit the primary key

Previously we had no notice when the user runs CREATE TABLE ... AS statement. Now we have a notice making the user aware of it's limitations.

Fixes: #131675
Release note (sql change): Now when we run the CREATE TABLE ... AS statement we have a notice making the user aware of it's limitations.

2024-11-20 20:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/135845)
<!-- Reviewable:end -->

2024-11-21 17:09 UTC, rafiss requested changes
nice work so far, i just had minor nits and questions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-:-OCEgpBf61YI3EBvqfRl:bco9y3v)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-OCEfbBvCk1VA2KCbbyL:-OCEfbBvCk1VA2KCbbyM:bgydsaz):*
These release notes are customer facing, so we should use more formal language. specifically, these notes should not use "we." see the guidelines at: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes
> -   Use **past tense** (e.g., "Added the xxx statement...", "Fixed a bug...") or **present tense** ("CockroachDB now supports...", "It is now possible to...").

this one could be:
```
Release note (sql change): Added an informational notice to the result of `CREATE TABLE ... AS` statements that describes that indexes and constraints are not copied to the new table.
```
___
*[`pkg/sql/pgwire/testdata/pgtest/multiple_active_portals` line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-OCEfJAFAAInFq67FZny:-OCEfJAFAAInFq67FZnz:b-euqrn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/288e4525c3440dc1c7f7e5a6889a5f9f89ec5633/pkg/sql/pgwire/testdata/pgtest/multiple_active_portals#L1327)):*
> ```
> ----
> 
> until
> ```

nit: let's update this test so it doesn't care about notices, as that's not the purpose of the test. the way to do that is to change this line to:
```
until ignore=NoticeResponse
```
___
*[`pkg/sql/logictest/testdata/logic_test/create_table` line 1125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-OCEfQes97Hj6qezJ72T:-OCEfQes97Hj6qezJ72U:bqsa4in) ([raw file](https://github.com/cockroachdb/cockroach/blob/288e4525c3440dc1c7f7e5a6889a5f9f89ec5633/pkg/sql/logictest/testdata/logic_test/create_table#L1125)):*
> ```
> );
> 
> statement notice NOTICE: CREATE TABLE ... AS does not copy over indexes, default expressions, or constraints; the new table has a hidden rowid primary key column
> ```

we'd previously discussed the benefits of using the `query T noticetrace` syntax to test this -- it allows us to use the `--rewrite` flag. is there a reason you changed back to `statement notice`?


<!-- Sent from Reviewable.io -->

2024-11-21 18:35 UTC, Dedej-Bergin reviewed
Great I just went ahead and made this change, thanks Rafi!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-:-OCF-HHHEeA9VxZ7kTyX:b-e3z53y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-OCEfbBvCk1VA2KCbbyL:-OCExUz1ErYAiW8LkRTH:base4vy):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

These release notes are customer facing, so we should use more formal language. specifically, these notes should not use "we." see the guidelines at: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes
> -   Use **past tense** (e.g., "Added the xxx statement...", "Fixed a bug...") or **present tense** ("CockroachDB now supports...", "It is now possible to...").

this one could be:
```
Release note (sql change): Added an informational notice to the result of `CREATE TABLE ... AS` statements that describes that indexes and constraints are not copied to the new table.
```
</blockquote></details>

Sounds good I went ahead and updated this and skimmed over/did a quick refresher on the link you sent for future Release Notes, thanks Rafi!
___
*[`pkg/sql/pgwire/testdata/pgtest/multiple_active_portals` line 1327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-OCEfJAFAAInFq67FZny:-OCEyLk7AkZ2FNYzwyMK:b-isbxwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/288e4525c3440dc1c7f7e5a6889a5f9f89ec5633/pkg/sql/pgwire/testdata/pgtest/multiple_active_portals#L1327)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's update this test so it doesn't care about notices, as that's not the purpose of the test. the way to do that is to change this line to:
```
until ignore=NoticeResponse
```
</blockquote></details>

Nice, went ahead and made this change, thanks Rafi!


<!-- Sent from Reviewable.io -->

2024-11-21 20:19 UTC, rafiss approved these changes
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135845#-:-OCFNCzM0KSKgUd5kSP_:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin)



<!-- Sent from Reviewable.io -->

2024-11-21 20:19 UTC, Dedej-Bergin commented
bors r+

2024-11-21 20:50 UTC, merged