kvserver: bring TestStoreRangeLease to a leader lease world
cockroachdb/cockroach pull request #136229
Opened 2024-11-26 18:02 UTC by arulajmani

This patch renames  what was previously TestStoreRangeLease by adding a EpochLease suffix to it. Then, we rewrite TestStoreRangeLease to use leader leases instead.

References https://github.com/cockroachdb/cockroach/issues/133763

Release note: None

2024-11-26 18:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/136229)
<!-- Reviewable:end -->

2024-11-28 15:19 UTC, iskettaneh requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136229)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/client_lease_test.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136229#-OCnLhPL9VwIc8axCAmB:-OCnLhPL9VwIc8axCAmC:b-g3o6yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4b6f39a31789c2601ab600ee6b8f8a267c862d/pkg/kv/kvserver/client_lease_test.go#L64)):*
> ```Go
> 	// we can remove this. Leader leases require us to reject lease requests
> 	// on replicas that are not the leader, as otherwise we'll
> 	kvserver.RejectLeaseOnLeaderUnknown.Override(ctx, &st.SV, true)
> ```

What happens if this was removed?


<!-- Sent from Reviewable.io -->

2024-11-28 15:31 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136229)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/kv/kvserver/client_lease_test.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136229#-OCnLhPL9VwIc8axCAmB:-OCnOLNCBgpsxLWGp88P:b69hyu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a4b6f39a31789c2601ab600ee6b8f8a267c862d/pkg/kv/kvserver/client_lease_test.go#L64)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

What happens if this was removed?
</blockquote></details>

It's not needed. Detritus from trying to stabilize this.


<!-- Sent from Reviewable.io -->

2024-11-28 15:42 UTC, iskettaneh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136229#-:-OCnR-YVCt5VCMS7a6lC:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2024-11-28 15:44 UTC, arulajmani commented
Thanks!

bors r+

2024-11-28 16:34 UTC, merged