kvserver: add TestFlowControlSendQueueRangeSplitMergeMixedVersion
cockroachdb/cockroach pull request #136765
Opened 2024-12-04 22:12 UTC by kvoli

Add a new flow control integration test, described by this comment:

```sql
-- This test is running with kvadmission.flow_control.mode="apply_to_elastic"
-- and the cluster version set to the previous version. We will exhaust the
-- elastic tokens towards s3. Then, we will split and merge the range,
-- expecting no send queue to form for any stream, as apply_to_elastic is the
-- flow control mode. We also expect that the split and merge will proceed
-- without issue. Note that admission is currently blocked on n3(s3).
```

Part of: https://github.com/cockroachdb/cockroach/issues/132614
Release note: None

2024-12-04 22:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/136765)
<!-- Reviewable:end -->

2024-12-06 20:11 UTC, sumeerbhola requested changes
Is the first commit even needed for this test to pass, given no send-queue?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-:-ODSY9QB0pxFKZFPlKxc:b-anvaxs)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODSZIMWD1k5w0twMP0M:-ODSZIMWD1k5w0twMP0N:bcoduxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e468b4c6d603921a09daeec8e0063226d9ab2bf/pkg/kv/kvserver/flow_control_integration_test.go#L5560)):*
> ```Go
> 
> 	h.put(ctx, roachpb.Key(desc.StartKey), 1, admissionpb.BulkNormalPri)
> 	h.comment(`(Sent 2 MiB BulkNormalPri put request to pre-split range)`)
> ```

I'm wondering whether we could improve this test, by not bothering with the NormalPri requests, and instead now sending another 2MiB BulkNormalPri request but not wait for its evaluation (since it will block). Then split the range which should proceed fine.

Then send another two 2MiB BulkNormalPri requests to the LHS and RHS which will also block. Then initiate the merge. The RHS RangeController will close, so that request will fall to just enqueuing on the local WorkQueue, which is enabled, and that will succeed. But the LHS ones will still be waiting.

That way we are testing that token exhaustion with work waiting for tokens has no effect on splits and merges. And slightly testing some other things which we haven't tested well before (like RHS RangeController closing when merge completes and the request admission falling back to just local WorkQueue admission).


<!-- Sent from Reviewable.io -->

2024-12-07 00:05 UTC, kvoli reviewed
TYFTR!

> Is the first commit even needed for this test to pass, given no send-queue?

It is not needed in any way. I added it originally to test the behavior, assuming subsume is marked as a write.

The test doesn't really have much purpose without it (I thought), however your suggestion changes that.

I'll ping when this is ready for review again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-:-ODTK3RTCnTgr2PCeRfp:b-wsa6us)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODSZIMWD1k5w0twMP0M:-ODTQaIdErqqhF04dJJr:bj51jqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e468b4c6d603921a09daeec8e0063226d9ab2bf/pkg/kv/kvserver/flow_control_integration_test.go#L5560)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm wondering whether we could improve this test, by not bothering with the NormalPri requests, and instead now sending another 2MiB BulkNormalPri request but not wait for its evaluation (since it will block). Then split the range which should proceed fine.

Then send another two 2MiB BulkNormalPri requests to the LHS and RHS which will also block. Then initiate the merge. The RHS RangeController will close, so that request will fall to just enqueuing on the local WorkQueue, which is enabled, and that will succeed. But the LHS ones will still be waiting.

That way we are testing that token exhaustion with work waiting for tokens has no effect on splits and merges. And slightly testing some other things which we haven't tested well before (like RHS RangeController closing when merge completes and the request admission falling back to just local WorkQueue admission).
</blockquote></details>

Sounds good to me. I'll go ahead and push through these changes.


<!-- Sent from Reviewable.io -->

2024-12-10 14:18 UTC, kvoli commented
Pushed through these changes, the test is still flaky over a stress duration.

2024-12-10 21:26 UTC, sumeerbhola reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODSZIMWD1k5w0twMP0M:-ODmSljD2ZOaXDpDgIBW:b-j6rd9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e468b4c6d603921a09daeec8e0063226d9ab2bf/pkg/kv/kvserver/flow_control_integration_test.go#L5560)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Sounds good to me. I'll go ahead and push through these changes.
</blockquote></details>

nice test!
___
*[`pkg/kv/kvserver/testdata/flow_control_integration_v2/range_split_merge_mixed_version` line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODmR3PV89v35XhXaM-v:-ODmR3PW5SsDdcW-jYei:b-kmw8po) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98032cef9ceaa324deea14896ace7cb55484d3/pkg/kv/kvserver/testdata/flow_control_integration_v2/range_split_merge_mixed_version#L40)):*
> ```
> 
> 
> -- Send queue and flow token metrics from n1, post-split and 1 MiB put on
> ```

is "1Mib put on each side" stale?


<!-- Sent from Reviewable.io -->

2024-12-10 22:45 UTC, kvoli reviewed
I wasn't able to resolve flaky behavior w/o ensuring the buffer of tokens is approx. equal to the size of the blocked requests. We would pass through waiting for all tokens to be returned and >0 tracked tokens, because each write was the size of the elastic token pool, so we had a turnstile problem -- the test would then ultimately fail on the testdata diff, as not all tokens had actually been returned, we only observed an intermediate state.

Pushed some changes described in this comment as well:

```go
	// We expect that there are no tracked tokens initially, as there are no
	// tokens available towards s3. Therefore, we wait for the total tracked
	// tokens to be greater than zero before proceeding to check that all tokens
	// are returned. This prevents an edge case where the test will fail because
	// not all tokens are actually returned, due to not having yet sent the
	// elastic pri entries to followers, passing the all token returned check
	// here but not later in the testdata file.
```

I'll wait to see if CI holds on the PR before re-requesting review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-:-ODmjAXC4LAamcWtZTC4:b-4d3d32)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/testdata/flow_control_integration_v2/range_split_merge_mixed_version` line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODmR3PV89v35XhXaM-v:-ODmj1aE0oqIisIblqDM:by1y2qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a98032cef9ceaa324deea14896ace7cb55484d3/pkg/kv/kvserver/testdata/flow_control_integration_v2/range_split_merge_mixed_version#L40)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is "1Mib put on each side" stale?
</blockquote></details>

It was, however I needed to update the test, so it is no longer stale, see the general reply.
___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5560 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODSZIMWD1k5w0twMP0M:-ODmj8wsBrfprJYiPDNy:bvtk9y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e468b4c6d603921a09daeec8e0063226d9ab2bf/pkg/kv/kvserver/flow_control_integration_test.go#L5560)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice test!
</blockquote></details>

Thanks :)


<!-- Sent from Reviewable.io -->

2024-12-11 14:44 UTC, kvoli commented
Should hold out now, added another check that the 0 tokens is sustained.

2024-12-11 19:02 UTC, kvoli commented
Extended CI failure is unrelated:
- `TestLogGrowthWhenRefreshingPendingCommands/lease-type=LeaseLeader/proposeOnFollower=true`

2024-12-11 20:37 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-:-ODrRGil9cXhH7MoPk5P:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5668 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODrPi7XAlew6GEuWScC:-ODrPi7XAlew6GEuWScD:bub0b9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c03da24d5ebd785471f0bf0c485d2c98b588be/pkg/kv/kvserver/flow_control_integration_test.go#L5668)):*
> ```Go
> 	// elastic pri entries to followers, passing the all token returned check
> 	// here but not later in the testdata file.
> 	h.waitForTotalTrackedTokensGE(ctx, merged.RangeID, 1<<20 /* 1MiB expTotalTrackedTokensGE */, 0 /* serverIdx */)
> ```

What if the this test code is slower than the rangeController and friends and the tracked tokens increase from 0 and all get returned, so total tracked becomes 0, before this `waitForTotalTrackedTokensGE` is able to observe?

Not trying to make your life more difficult here, but I am slightly worried that we may not have fully solved the flakiness. I suppose we could always add a cumulative value to `rac2.Tracker` if/when we end up needing it.


<!-- Sent from Reviewable.io -->

2024-12-11 21:34 UTC, kvoli reviewed
TYFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-:-ODrd7KL5HUzEccVSNm0:b-akydb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/flow_control_integration_test.go` line 5668 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/136765#-ODrPi7XAlew6GEuWScC:-ODrcZXw0pF48UdeANe5:bw1sgbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c03da24d5ebd785471f0bf0c485d2c98b588be/pkg/kv/kvserver/flow_control_integration_test.go#L5668)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What if the this test code is slower than the rangeController and friends and the tracked tokens increase from 0 and all get returned, so total tracked becomes 0, before this `waitForTotalTrackedTokensGE` is able to observe?

Not trying to make your life more difficult here, but I am slightly worried that we may not have fully solved the flakiness. I suppose we could always add a cumulative value to `rac2.Tracker` if/when we end up needing it.
</blockquote></details>

I did consider this possibility but ignored it after it didn't fall out in stress testing. I think that the waitForTotalTrackedTokensForDuration is likely sufficient in of itself, given it waits for at least 2s so we could remove the GE if it comes to it.

Going to keep this in mind and if it begins flaking nightly/PRs then I'll adopt the suggestion.


<!-- Sent from Reviewable.io -->

2024-12-11 22:08 UTC, merged