ui: use error body over status text for err messages
cockroachdb/cockroach pull request #136772
Opened 2024-12-04 23:41 UTC by xinhaoz

THe `statusText` field in the Response object is not available in http/2. Previously we were using statusText as the error message for api/v2 errors, which left the error message blank in those cases.

This commit replaces statusText uses with the response body as the error message string. If we are unable to decode the error response then we'll read the statusText field, defaulting to the status code if it is unavailable.

Epic: none
Fixes: #136038

Release note: None

2024-12-04 23:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/136772)
<!-- Reviewable:end -->

2024-12-05 15:29 UTC, xinhaoz commented
Going to update with some tests for the new function extracting error body.

2024-12-09 16:12 UTC, xinhaoz commented
Tests added.

2024-12-09 17:11 UTC, angles-n-daemons requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgEpQN-i9Zr07yJYNR:-ODgEpQN-i9Zr07yJYNS:b-kmv3al) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts#L1)):*
> ```XML
> // Copyright 2024 The Cockroach Authors.
> ```

nice, really appreciate these tests.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgF9YpByW5VUYvpXp3:-ODgF9YpByW5VUYvpXp4:b-dpv02s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts#L30)):*
> ```XML
>   });
> 
>   it.each([
> ```

Request for a test where `response.status.toString()` is used.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgEfT--nPF2gE-aD6s:-ODgEfT--nPF2gE-aD6t:b-vm2eam) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts#L69)):*
> ```XML
>     "should throw error when encountering non-200 status: $description",
>     async ({ path, request, response, body, expected }) => {
>       // fetchMock.mockResponseOnce(body, { ...response });
> ```

Can these comments be removed?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgDhrdCjli_hlG5Rny:-ODgDhrdCjli_hlG5Rnz:b-cu1u9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L63)):*
> ```XML
>   }
> 
>   return fetch(withBasePath(path), params)
> ```

If you feel comfortable refactoring here, I feel like this bit of changed code could benefit from async await syntax. Eg:

```ts
export const fetchData = async <P extends...

  const response = await fetch(withBasePath(path), params);
  if (!response.ok) {
    const error = await getErrorBodyFromResponse(response);
    throw new RequestError(response.status, error);
  }
  const buffer = new Uint8Array(await response.arrayBuffer());
  return respBuilder.decode(buffer);
}
```

Not required for approval however, feel free only if you feel comfortable bundling those changes.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgC6ZwCvCrISq03sOZ:-ODgC6ZwCvCrISq03sO_:b-4rjdku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L106)):*
> ```XML
>         throw new RequestError(
>           response.status,
>           errorBody || response.statusText,
> ```

Won't errorBody already contain the response.statusText if it exists?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBW6c1o9QTz-6Vnc7:-ODgBW6c1o9QTz-6Vnc8:bq81jqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L115)):*
> ```XML
> }
> 
> async function getErrorBodyFromResponse(response: Response): Promise<string> {
> ```

Nice, this function looks good. It might be worth adding a doc describing the sequence of steps it works though.

eg.
```js
// getErrorBodyFromResponse attempts to extract an error message from a 
// failed RPC call. It looks for this error in the following places:
//   - If the response is a text or json blob, it returns them directly.
//   - Otherwise, if the response can be deserialized to a proto Error type...
...
```
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBOZr53M2EJDUulit:-ODgBOZs4UkAA5XmF4Zu:b-xlxd01) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L140)):*
> ```XML
>   }
> 
>   return Promise.resolve(response.statusText || response.status.toString());
> ```

I think Promise.resolve is unnecessary here.


<!-- Sent from Reviewable.io -->

2024-12-09 18:29 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgDhrdCjli_hlG5Rny:-ODgfEe_0CZkEuz9eEgd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L63)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

If you feel comfortable refactoring here, I feel like this bit of changed code could benefit from async await syntax. Eg:

```ts
export const fetchData = async <P extends...

  const response = await fetch(withBasePath(path), params);
  if (!response.ok) {
    const error = await getErrorBodyFromResponse(response);
    throw new RequestError(response.status, error);
  }
  const buffer = new Uint8Array(await response.arrayBuffer());
  return respBuilder.decode(buffer);
}
```

Not required for approval however, feel free only if you feel comfortable bundling those changes.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgC6ZwCvCrISq03sOZ:-ODgfHOZBqPP21Yclp7y:b15g1ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L106)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Won't errorBody already contain the response.statusText if it exists?
</blockquote></details>

The returned error body might be empty (although that part is really on us as well), so I put this here so that we could try to avoid returning an empty error message whenever possible. I've moved that logic to the getErrorBodyFromResponse function instead.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBW6c1o9QTz-6Vnc7:-ODgd_i44mm_8oJLaEpj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L115)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Nice, this function looks good. It might be worth adding a doc describing the sequence of steps it works though.

eg.
```js
// getErrorBodyFromResponse attempts to extract an error message from a 
// failed RPC call. It looks for this error in the following places:
//   - If the response is a text or json blob, it returns them directly.
//   - Otherwise, if the response can be deserialized to a proto Error type...
...
```
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBOZr53M2EJDUulit:-ODgdKR4BujxW38955sr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L140)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

I think Promise.resolve is unnecessary here.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgF9YpByW5VUYvpXp3:-ODgdmPo1vIdbG_aGYno:bp15xny) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts#L30)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Request for a test where `response.status.toString()` is used.
</blockquote></details>

Done - I modified the tests to check the full RequestError.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts` line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgEfT--nPF2gE-aD6s:-ODgegKK-RiVbmPu44PG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.spec.ts#L69)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Can these comments be removed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 21:59 UTC, angles-n-daemons requested changes
Nice, just one small comment on the JSDoc but otherwise good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-:-ODm_KyS96ImRPKF1Yt_:b-sfc5x2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgC6ZwCvCrISq03sOZ:-ODmZV4d0pn3503PHOgZ:b90val5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L106)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

The returned error body might be empty (although that part is really on us as well), so I put this here so that we could try to avoid returning an empty error message whenever possible. I've moved that logic to the getErrorBodyFromResponse function instead.
</blockquote></details>

oh perfect, thanks!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBW6c1o9QTz-6Vnc7:-ODmZdSN-v4w9ltj63if:b-kgrkcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L115)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Might be worth adding the last to sources:

```
//   - If the response has a statusText property then it is used.
//   - If none of the above options were found, the status code is returned.
```



<!-- Sent from Reviewable.io -->

2024-12-10 22:02 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgC6ZwCvCrISq03sOZ:-ODma6X37JFfBNrWt3lz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L106)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

oh perfect, thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 22:03 UTC, xinhaoz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons, @dhartunian, and @kyle-a-wong)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-ODgBW6c1o9QTz-6Vnc7:-ODmaB4i-2HL-JCG5T5_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8c7c70d3d7763dc658bb85d9f23bf3bdc9a5148/pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts#L115)):*
<details><summary><i>Previously, angles-n-daemons (Brian Dillmann) wrote…</i></summary><blockquote>

Might be worth adding the last to sources:

```
//   - If the response has a statusText property then it is used.
//   - If none of the above options were found, the status code is returned.
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-10 22:21 UTC, angles-n-daemons approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136772#-:-ODmeQy89UfMwW7l9lWZ:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @kyle-a-wong, and @xinhaoz)



<!-- Sent from Reviewable.io -->

2024-12-11 16:03 UTC, xinhaoz commented
TFTR! Failed unit tests are unrelated.
bors r+

2024-12-11 16:57 UTC, merged

2024-12-12 18:19 UTC, xinhaoz commented
blathers backport 24.3