roachtest: increase the token return time with disk bandwidth limit
cockroachdb/cockroach pull request #137019
Opened 2024-12-09 15:21 UTC by andrewbaptist

Previously the test would wait 10m for tokens to be returned. Without the disk bandwidth limit set, they typically return almost immediately but with a limit they can take ~30m to return in some cases even after the workload is stopped and the system is idle. This change fixes some of the perturbation/metamorphic/* tests that are hitting this slow token return.

Epic: none
Fixes: #136982
Fixes: #136553
Informs: #137017

Release note: None

2024-12-09 15:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/137019)
<!-- Reviewable:end -->

2024-12-09 18:14 UTC, kvoli requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137019)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @csgourav, and @shailendra-patel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-ODgbH_f75cC2LK5jJEe:-ODgbH_f75cC2LK5jJEf:b-uhrvj0):*
nit: it is referenced below, but the test [sic] isn't known here  yet, consider mentioning it here or updating the commit header.
___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-ODgbYQW83eWQTgXgIyd:-ODgbYQW83eWQTgXgIye:b-ys385e) ([raw file](https://github.com/cockroachdb/cockroach/blob/039a2d28193d34a454ccedef834b90a5403448b8/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L136)):*
> ```Go
> 			// TODO(pav-kv): also validate that the write throughput was kept under
> 			// control, and the foreground traffic was not starved.
> 			roachtestutil.ValidateTokensReturned(ctx, t, c, c.CRDBNodes(), time.Minute)
> ```

The commit header:

```
roachtest: increase the token return time with disk bandwidth limit
```

The wait duration is decreasing from 10 minutes, to 1 minute unless the `diskBandwidthLimit` is enabled. 

I suggest either updating the commit message/header, or leaving the token return time unchanged for non-disk-bw-limit variations. 

Also, do you have any stats handy that confirm the decrease from 10 minutes, to 1 minute, is sufficient to prevent flakes? 


<!-- Sent from Reviewable.io -->

2024-12-10 17:59 UTC, andrewbaptist reviewed
TFTR!

Changes made, let me know if you have additional comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-:-ODli8dy19tN21eInAqZ:bhkzrgn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @csgourav, @kvoli, and @shailendra-patel)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-ODgbH_f75cC2LK5jJEe:-ODliDOLCxIqImGEtVf9:bitm7ma):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: it is referenced below, but the test [sic] isn't known here  yet, consider mentioning it here or updating the commit header.
</blockquote></details>

Updated to add the test name here. 
___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-ODgbYQW83eWQTgXgIyd:-ODlhtLPEKcV3ATZAViy:b-9mefw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/039a2d28193d34a454ccedef834b90a5403448b8/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L136)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

The commit header:

```
roachtest: increase the token return time with disk bandwidth limit
```

The wait duration is decreasing from 10 minutes, to 1 minute unless the `diiskBandwidthLimit` is enabled. 

I suggest either updating the commit message/header, or leaving the token return time unchanged for non-disk-bw-limit variations. 

Also, do you have any stats handy that confirm the decrease from 10 minutes, to 1 minute, is sufficient to prevent flakes?
</blockquote></details>

I left this as 1 minute after looking through the last several runs for this test where it was always in the 1-2s range. It might be easier to catch any regressions in this behavior on this test with a lower bound.


<!-- Sent from Reviewable.io -->

2024-12-10 18:49 UTC, kvoli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-:-ODltxKb2utfTEBZRh1Y:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @csgourav, and @shailendra-patel)

___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137019#-ODgbYQW83eWQTgXgIyd:-ODltnK44Ek32gYPQVEt:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/039a2d28193d34a454ccedef834b90a5403448b8/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L136)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I left this as 1 minute after looking through the last several runs for this test where it was always in the 1-2s range. It might be easier to catch any regressions in this behavior on this test with a lower bound.
</blockquote></details>

ack


<!-- Sent from Reviewable.io -->

2024-12-10 19:02 UTC, andrewbaptist commented
TFTR!

bors r=kvoli

2024-12-10 20:02 UTC, merged