sql: extend drop region for system db
cockroachdb/cockroach pull request #137929
Opened 2024-12-23 16:07 UTC by annrpom

This patch ensures that references to a dropping region get cleaned up for the system database.

Epic: none
Fixes:

Release note: None

2024-12-23 16:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/137929)
<!-- Reviewable:end -->

2025-01-08 21:52 UTC, rafiss requested changes
looks good so far!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-:-OG6trxB1su5FmW_-7ER:b-xo2sg4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/alter_database.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6hCtL-7A8nD59ON7k:-OG6hCtL-7A8nD59ON7l:b-2u4io9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/alter_database.go#L492)):*
> ```Go
> 			for _, t := range tablesToClean {
> 				updateQuery := fmt.Sprintf(
> 					`UPDATE system.%s SET crdb_region = '%s' WHERE crdb_region = '%s'`, t, dbDesc.RegionConfig.PrimaryRegion, n.Region)
> ```

i do feel that updating is safer so we don't remove any metadata which might still be important. but i still wonder -- do we know if it would be safe to delete from any of these tables right away?
___
*[`pkg/sql/type_change.go` line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6sbQo-HUEBJhBAx4D:-OG6sbQo-HUEBJhBAx4E:b-5j6ri3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L416)):*
> ```Go
> 			for _, member := range typeDesc.EnumMembers {
> 				if t.isTransitioningInCurrentJob(&member) && enumMemberIsRemoving(&member) {
> 					if typeDesc.Kind == descpb.TypeDescriptor_MULTIREGION_ENUM {
> ```

super nit: we could reduce the indentation here by inverting the conditions:
```
	if !t.isTransitioningInCurrentJob(&member) ||
		!enumMemberIsRemoving(&member) ||
		typeDesc.Kind != descpb.TypeDescriptor_MULTIREGION_ENUM {
		continue
	}
```
___
*[`pkg/sql/type_change.go` line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6t8-c1T4KKDdWJfGE:-OG6t8-c1T4KKDdWJfGF:bfveq7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L418)):*
> ```Go
> 					if typeDesc.Kind == descpb.TypeDescriptor_MULTIREGION_ENUM {
> 						if err := func() error {
> 							rows, err := txn.QueryIteratorEx(ctx, "select-invalid-instances", txn.KV(),
> ```

nit: we can use `QueryBufferedEx` here, since we are just adding all the rows into a slice anyway.

then we can get rid of the anonymous `func() error` function, and remove the cleanup logic around `rows.Close`
___
*[`pkg/sql/type_change.go` line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6tejh24VD1Cx3a-Pv:-OG6tejh24VD1Cx3a-Pw:b6gpoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L1088)):*
> ```Go
> 			//  system db (?) how do?
> 			if member.Direction == descpb.TypeDescriptor_EnumMember_REMOVE {
> 				if desc.GetName() == "sql_instances" {
> ```

let's use `desc.GetID() == keys.SQLInstancesTableID`


<!-- Sent from Reviewable.io -->

2025-01-08 21:55 UTC, fqazi reviewed
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)

___
*[`pkg/sql/alter_database.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6hCtL-7A8nD59ON7k:-OG6tx3-3b0uwaY9obYj:b-a2p9ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/alter_database.go#L492)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i do feel that updating is safer so we don't remove any metadata which might still be important. but i still wonder -- do we know if it would be safe to delete from any of these tables right away?
</blockquote></details>

I think we should be deleting rows if they are no longer active? i.e. Check if the session is still alive using sql\_liveness\_is\_alive, if it isn't then delete the row. We should block dropping regions if the row is active. Any unclaimed rows in sqlinstances can be removed.

I think there is danger if we blindly update if for some reason the node in a region wasn't brought down.


<!-- Sent from Reviewable.io -->

2025-01-09 14:08 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/alter_database.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6hCtL-7A8nD59ON7k:-OGANcOyBJgUXzKg97-A:b-rq4nz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/alter_database.go#L492)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think we should be deleting rows if they are no longer active? i.e. Check if the session is still alive using sql\_liveness\_is\_alive, if it isn't then delete the row. We should block dropping regions if the row is active. Any unclaimed rows in sqlinstances can be removed.

I think there is danger if we blindly update if for some reason the node in a region wasn't brought down.
</blockquote></details>

The existing function `regionliveness.CleanupSystemTableForRegion` might be useful here too. So we'd first ensure that all the sessions from that region are not active, then call this function.


<!-- Sent from Reviewable.io -->

2025-01-09 15:38 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/alter_database.go` line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6hCtL-7A8nD59ON7k:-OGA_txg3hxBhohuy-wD:b-d3rqdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/alter_database.go#L492)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

The existing function `regionliveness.CleanupSystemTableForRegion` might be useful here too. So we'd first ensure that all the sessions from that region are not active, then call this function.
</blockquote></details>

ah right! apologies i do remember discussing this with Faizan; ty you all for the pointers
___
*[`pkg/sql/type_change.go` line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6sbQo-HUEBJhBAx4D:-OGAXxlG5TV6yeUUOdWE:bggf81u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L416)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: we could reduce the indentation here by inverting the conditions:
```
	if !t.isTransitioningInCurrentJob(&member) ||
		!enumMemberIsRemoving(&member) ||
		typeDesc.Kind != descpb.TypeDescriptor_MULTIREGION_ENUM {
		continue
	}
```
</blockquote></details>

done demorgans donemorgans
___
*[`pkg/sql/type_change.go` line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6t8-c1T4KKDdWJfGE:-OGAY8-V5q-OtnUky5DU:bj4mykf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L418)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: we can use `QueryBufferedEx` here, since we are just adding all the rows into a slice anyway.

then we can get rid of the anonymous `func() error` function, and remove the cleanup logic around `rows.Close`
</blockquote></details>

done -- ah good point
___
*[`pkg/sql/type_change.go` line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OG6tejh24VD1Cx3a-Pv:-OGA_evqAB0qlNjDaNQ_:b2ni9d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1799d5f429a185f0b0bfd2a2f6bf7850e29d2222/pkg/sql/type_change.go#L1088)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

let's use `desc.GetID() == keys.SQLInstancesTableID`
</blockquote></details>

oki


<!-- Sent from Reviewable.io -->

2025-01-09 15:46 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/alter_database.go` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGAi_-E5s8gYMq56Yjm:-OGAi_-E5s8gYMq56Yjn:b-gbeqiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L516)):*
> ```Go
> 			// (if any) of the dropping region from the table.
> 			if _, err := txn.ExecEx(ctx, "remove-region-liveness-ref", txn.KV(),
> 				sessiondata.NodeUserSessionDataOverride, `DELETE FROM system.region_liveness
> ```

I did have a clarifying q here: is there any assumption we can make about the region_liveness table where if a region has an entry in here with unavailable_at timestamp, we don't have to scan the other system tables for any active sessions?


<!-- Sent from Reviewable.io -->

2025-01-09 19:06 UTC, rafiss reviewed
this lgtm! i'll leave the final approval for Faizan since this is his area of expertise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-:-OGBSIqYAYsTl4MPxHHh:b-wdz55q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/alter_database.go` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGAi_-E5s8gYMq56Yjm:-OGBRgHk3azYpm9Aqtuu:b-w98i5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L516)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

I did have a clarifying q here: is there any assumption we can make about the region_liveness table where if a region has an entry in here with unavailable_at timestamp, we don't have to scan the other system tables for any active sessions?
</blockquote></details>

i am not quite sure. it seems safer to just keep what you have now. i'm imagining a scenario where a region becomes unavailable due to a network partition, and then once the partition is over, the nodes in the other region come back up and are broken since we've removed all these rows. hmm but then again, if that were the case, all those sqlliveness sessions would not be alive... curious if Faizan has thoughts here.
___
*[`pkg/sql/alter_database.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBPxJK1q8eUXVb6x47:-OGBPxJK1q8eUXVb6x48:bqmtg3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L489)):*
> ```Go
> 			return nil, err
> 		}
> 		if err := p.ExecCfg().InternalDB.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
> ```

nit: is this intentionally using a separate transaction? as opposed to avoiding `InternalDB`/`txn.QueryRowEx` and just using `p.QueryRowEx` below
___
*[`pkg/sql/alter_database.go` line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBQXx-Bkpu-oJ7So4p:-OGBQXx-Bkpu-oJ7So4q:b-eqftvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L508)):*
> ```Go
> 							n.Region,
> 						),
> 						"You must not have any active sessions that are in this region. "+
> ```

nit: "terminate all sessions" might be misleading in this hint. a liveness session doesn't come from a user's SQL session. instead, perhaps we should say "Ensure that there no nodes that still belong to region %q"
___
*[`pkg/sql/alter_database.go` line 509 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBQLaV1Aar3if-5jwL:-OGBQLaV1Aar3if-5jwM:bk2usg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L509)):*
> ```Go
> 						),
> 						"You must not have any active sessions that are in this region. "+
> 							"Terminate all sessions before attemptoing to drop region %q", n.Region,
> ```

nit: "attempting"
___
*[`pkg/sql/type_change.go` line 420 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBR9wm-RoWIeaSpx0n:-OGBR9wm-RoWIeaSpx0o:b-4tuovv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/type_change.go#L420)):*
> ```Go
> 					continue
> 				}
> 				if err := func() error {
> ```

nit: this `func() error` doesn't give us much now, so i think we should just take this logic out of the anonymous function.


<!-- Sent from Reviewable.io -->

2025-01-10 14:58 UTC, fqazi approved these changes
Nice work @annrpom!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-:-OGFiD134L0aT8ykUBYA:bywzdgf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom and @rafiss)



<!-- Sent from Reviewable.io -->

2025-01-10 16:17 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/alter_database.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBPxJK1q8eUXVb6x47:-OGFbcY5BTCPavdtbVGz:b-7gv8zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L489)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: is this intentionally using a separate transaction? as opposed to avoiding `InternalDB`/`txn.QueryRowEx` and just using `p.QueryRowEx` below
</blockquote></details>

i remember being specified that we should do these changes in a txn (https://cockroachlabs.atlassian.net/browse/CRDB-42977); which is what led me to use `InternalDB.Txn`, but i don't quite remember why that specification was in place
___
*[`pkg/sql/alter_database.go` line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBQXx-Bkpu-oJ7So4p:-OGFb-BFD-CvjUauT_8k:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L508)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: "terminate all sessions" might be misleading in this hint. a liveness session doesn't come from a user's SQL session. instead, perhaps we should say "Ensure that there no nodes that still belong to region %q"
</blockquote></details>

done
___
*[`pkg/sql/alter_database.go` line 509 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBQLaV1Aar3if-5jwL:-OGFb1394KMumrzd9eUZ:b-w72ivh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L509)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: "attempting"
</blockquote></details>

haste :3
___
*[`pkg/sql/alter_database.go` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGAi_-E5s8gYMq56Yjm:-OGFtHDW4zwx2zwsVrI6:b-eq8o26) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L516)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i am not quite sure. it seems safer to just keep what you have now. i'm imagining a scenario where a region becomes unavailable due to a network partition, and then once the partition is over, the nodes in the other region come back up and are broken since we've removed all these rows. hmm but then again, if that were the case, all those sqlliveness sessions would not be alive... curious if Faizan has thoughts here.
</blockquote></details>

safer is fair; i can keep like this
___
*[`pkg/sql/type_change.go` line 420 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBR9wm-RoWIeaSpx0n:-OGFbOfa228szH02Xpiy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/type_change.go#L420)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this `func() error` doesn't give us much now, so i think we should just take this logic out of the anonymous function.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2025-01-10 19:48 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/alter_database.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBPxJK1q8eUXVb6x47:-OGGkUIREU_1kZ21mqN9:brvdvsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L489)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

i remember being specified that we should do these changes in a txn (https://cockroachlabs.atlassian.net/browse/CRDB-42977); which is what led me to use `InternalDB.Txn`, but i don't quite remember why that specification was in place
</blockquote></details>

it seems that that ticket just says "in a transaction" but doesn't specify that it should be a separate transaction. let's just reuse the transaction that ALTER DATABASE is running in by using `p.QueryRowEx`. it seems safer, since then the deletions will get rolled back if something else goes wrong.


<!-- Sent from Reviewable.io -->

2025-01-13 15:59 UTC, annrpom reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/alter_database.go` line 489 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGBPxJK1q8eUXVb6x47:-OGVO0og3rfRUS_26WJi:b-g7pros) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ee245ed92c28cb1d1106c0bf9f0c33556e8d38/pkg/sql/alter_database.go#L489)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it seems that that ticket just says "in a transaction" but doesn't specify that it should be a separate transaction. let's just reuse the transaction that ALTER DATABASE is running in by using `p.QueryRowEx`. it seems safer, since then the deletions will get rolled back if something else goes wrong.
</blockquote></details>

done -- good point


<!-- Sent from Reviewable.io -->

2025-01-13 21:11 UTC, rafiss approved these changes
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-:-OGWVX55B1w2bZbqgZDH:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/alter_database.go` line 507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/137929#-OGWVDhl2tLtGofujRsZ:-OGWVDhl2tLtGofujRs_:b-85tvu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0107f13c84d109590b42e51bb00530cccff7e397/pkg/sql/alter_database.go#L507)):*
> ```Go
> 					),
> 					"You must not have any active sessions that are in this region. "+
> 						"Ensure that there no nodes that still belong to region %q", n.Region,
> ```

nit: "Ensure that there are no nodes ..." or "Ensure that no nodes still belong to ..."

(my bad for missing a word in my previous comment)


<!-- Sent from Reviewable.io -->

2025-01-13 21:13 UTC, annrpom commented
TFTR! ('-')7

bors r+

2025-01-14 00:09 UTC, merged