sql: wrap session trace messages at 80 chars
cockroachdb/cockroach pull request #16702
Opened 2017-06-23 20:22 UTC by jordanlewis

Looking at a session trace with `SHOW SESSION TRACE` can be difficult
because the log messages can be very long and cause the output table to
display in an ugly way unless one's terminal window is very wide.

Now, the log messages are wrapped at 80 characters to prevent this
issue.

2017-06-23 20:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/16702)
<!-- Reviewable:end -->

2017-06-23 20:24 UTC, a-robinson approved these changes
> Now, the log messages are wrapped at 80 characters to > prevent this
> issue.

👏

2017-06-23 20:29 UTC, tschottdorf commented
LGTM, assuming you didn't have to actually vendor this new import.

2017-06-23 20:30 UTC, jordanlewis commented
It was already available. We use it for the SQL CLI.

2017-06-23 20:30 UTC, tschottdorf commented on pkg/sql/session.go
> +			parser.NewDString(msg), // message
Why is this comment not aligned any more? #justnittythings

2017-06-23 20:31 UTC, jordanlewis commented on pkg/sql/session.go
> +			parser.NewDString(msg), // message
Fixed

2017-06-23 20:42 UTC, andreimatei commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16702#-:-KnLgLfzhDzxKafGujQy:b-v6ynew)*
<!-- Sent from Reviewable.io -->

2017-06-23 22:32 UTC, jordanlewis commented
Had to rework this a bit because of the way `SHOW TRACE` ran a regex on the data within `crdb_internal.session_trace`. Now, that regex is run by the code that populates `session_trace` instead of in the SQL expression that generates the final output for `SHOW TRACE`. The `session_trace` table now has a `context` column (containing e.g. `[n1,s1]`) and a `message` column (containing the rest of the log line).

2017-06-26 11:16 UTC, knz requested changes
Wait a second what is going on here. Why do this on the server side? It seems to me that any SQL GUI client would do this wrapping for you.

If the problem is wide columns in the SQL CLI, this problem is not specific to traces! It would be true of any wild-columnar data! 

**The correct solution is to keep the data produced by the server as-is, and add a proper formatting default in `cli/format_table.go`.**

As a matter of fact there is already such an option available in the TableFormatter we use for the `pretty` format. It's just disabled currently. I would suggest to make `pretty` wrap by default, and add another option to not-wrap.

This is especially important so that users of the `record` and the `raw` formats still get the option to get unwrapped trace data!

2017-06-26 13:44 UTC, tamird commented
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/session.go, line 32 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16702#-KnZcyT2jz7dTCu6xoJz:-KnZcyT2jz7dTCu6xoK-:b-297sc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c586ac711078c3ba0d6a93c78f987beadabcd7e2/pkg/sql/session.go#L32)):*
> ```Go
> 	"golang.org/x/net/trace"
> 
> 	"regexp"
> ```

group with other stdlib imports?

---

*[pkg/sql/session.go, line 1322 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16702#-KnZdIJoDp4bXB72TH9T:-KnZdIJoDp4bXB72TH9U:b-bw5hr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c586ac711078c3ba0d6a93c78f987beadabcd7e2/pkg/sql/session.go#L1322)):*
> ```Go
> 		unwrappedMsg := lrr.msg
> 
> 		matches := contextRegexp.FindStringSubmatch(lrr.msg)
> ```

scope more narrowly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16702)*
<!-- Sent from Reviewable.io -->

2017-06-26 14:51 UTC, jordanlewis commented
@knz good point - I got a little overzealous with this. I guess a better solution would be to introduce some kind of auto-wrapping, like you're saying, or alternatively normalize the procedure of changing the cli format style when viewing this kind of data.

Anyone interested in leaving in the extra `context` column or shall I just abandon this whole thing?

2017-06-26 14:53 UTC, knz commented
+1 on the separate precomputed context column

2017-06-26 15:05 UTC, andreimatei commented
I'm -1 on the context column.  I think we should keep the `session_trace` table pretty raw; that "context" is part of the log message. If we want to extract it, we should probably do it when the messages as recording (by transforming the context tags into span event attributes).
You can do this text transformation in the `SHOW TRACE` output if you feel strongly, by changing the SQL on that view.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16702#-:-KnZuYrNDTGE1lBAbHbK:b-gq3v4p)*
<!-- Sent from Reviewable.io -->

2017-06-26 15:06 UTC, closed without merging

2017-06-26 15:06 UTC, jordanlewis commented
Thanks guys I'll let this one die off :)