acceptanceccl: add benchmark for RESTORE of TPCH-10
cockroachdb/cockroach pull request #17209
Opened 2017-07-25 16:57 UTC by danhhz

2017-07-25 16:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/17209)
<!-- Reviewable:end -->

2017-07-29 16:24 UTC, dt approved these changes

2017-07-29 16:25 UTC, dt requested changes

2017-07-29 16:25 UTC, dt commented on pkg/ccl/acceptanceccl/backup_test.go
> +			const backupBaseURI = "azure://backup-test/benchmarks/tpch/scalefactor-10?AZURE_ACCOUNT_NAME=cockroachbackuptest&AZURE_ACCOUNT_KEY=FzWMkVNcHorQ2IPG5il987GEmEzSxmV8WxXOZHzKV4XfvNTXHEDdBrsAIMB2/UutS
You wanna redact this key?

2017-07-31 14:59 UTC, danhhz commented on pkg/ccl/acceptanceccl/backup_test.go
> +			const backupBaseURI = "azure://backup-test/benchmarks/tpch/scalefactor-10?AZURE_ACCOUNT_NAME=cockroachbackuptest&AZURE_ACCOUNT_KEY=FzWMkVNcHorQ2IPG5il987GEmEzSxmV8WxXOZHzKV4XfvNTXHEDdBrsAIMB2/UutS
😳

2017-07-31 14:59 UTC, danhhz commented
RFAL

2017-07-31 15:34 UTC, dt approved these changes

2017-07-31 19:19 UTC, merged

2017-07-31 19:19 UTC, danhhz commented
TFTR!