sql: permit CANCEL QUERY to take array of ids
cockroachdb/cockroach pull request #20514
Opened 2017-12-06 04:40 UTC by nvanbenschoten

Release note (sql change): CANCEL QUERY can now cancel multiple queries
at a time.

2017-12-06 04:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/20514)
<!-- Reviewable:end -->

2017-12-06 04:49 UTC, BramGruneir commented
LGTM, but probably best to wait on a veteran SQLer to weigh in.

2017-12-06 15:21 UTC, knz requested changes
This is not the right approach.

The thing should take a subquery as operand.
If you really want to use an array you can then say `cancel query (select unnest(array[...]))`

An array is too restrictive and also memory-inefficient. cancel query can operate on a streaming fashion and mandating arrays would not allow that.

2018-07-21 01:54 UTC, nvanbenschoten commented
Replaced/greatly improved by #25157. Thanks @knz!

2018-07-21 01:54 UTC, closed without merging