sql/distsqlrun: refactor mergeJoiner to implement RowSoruce
cockroachdb/cockroach pull request #21219
Opened 2018-01-04 01:08 UTC by petermattis

The performance diff at smaller input sizes is due to the removal of the
`log.VEventf` lines.

```
name                           old time/op    new time/op    delta
MergeJoiner/InputSize=0-8        3.39µs ± 2%    2.30µs ± 2%  -32.22%  (p=0.000 n=10+9)
MergeJoiner/InputSize=4-8        5.66µs ± 1%    4.19µs ± 1%  -25.91%  (p=0.000 n=10+8)
MergeJoiner/InputSize=16-8       8.76µs ± 1%    7.14µs ± 1%  -18.55%  (p=0.000 n=9+10)
MergeJoiner/InputSize=256-8      66.6µs ± 1%    64.3µs ± 1%   -3.50%  (p=0.000 n=9+9)
MergeJoiner/InputSize=4096-8      987µs ± 1%     991µs ± 1%     ~     (p=0.089 n=10+10)
MergeJoiner/InputSize=65536-8    16.1ms ± 3%    16.4ms ± 3%     ~     (p=0.113 n=9+10)
```

Release note: None

2018-01-04 01:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/21219)
<!-- Reviewable:end -->

2018-01-04 01:09 UTC, petermattis commented
I broke this change into a series of smaller commits so that the reviewer can see the transformations I made before arriving at the final state.

2018-01-04 01:42 UTC, petermattis commented
> The performance diff at smaller input sizes is due to the removal of the log.VEventf lines.

This actually isn't the cause of the performance delta. It is something to do with the last commit. I'm investigating.

2018-01-04 01:56 UTC, petermattis commented
The difference is actually due to not using `DrainAndClose`. That method spawns a goroutine if there is more than one input to drain:

```
		for _, input := range srcs[1:] {
			wg.Add(1)
			go func(input RowSource) {
				DrainAndForwardMetadata(ctx, input, dst)
				wg.Done()
			}(input)
		}
```

The refactored `mergeJoiner` drains inputs serially. I'm mildly surprised this makes a difference, but there you go.

2018-01-05 05:18 UTC, rjnn requested changes
FWIW I found it easier to review it by viewing all the diffs at once, although I do appreciate that you gave me the option of doing it both ways. Reviewable also borked out on me, so doing this the old fashioned way.

The stream group accumulator and stream merger changes LGTM. Let's get another set of eyes on the merge joiner state machine, and a resolution on the double `ConsumerDone`.

2018-01-05 05:18 UTC, arjunravinarayan commented on pkg/sql/distsqlrun/mergejoiner.go
> +	// The loops below form a restartable state machine the iterates over a batch
Elegant! Thanks for the comment. Would be good to get one more review on the refactored merge joiner state machine. @RaduBerinde, do you mind taking a quick look at this function?

2018-01-05 14:47 UTC, petermattis reviewed
TFTR!

2018-01-05 14:47 UTC, petermattis commented on pkg/sql/distsqlrun/mergejoiner.go
> +// valuesProcessor ran out of rows or encountered an error. It is ok for err to
Copy pasta. Fixed.

2018-01-05 14:47 UTC, petermattis commented on pkg/sql/distsqlrun/stream_group_accumulator.go
>  // state to the next group, so that a subsequent peekAtCurrentGroup() will
Removed that portion of the sentence.

2018-01-05 20:13 UTC, RaduBerinde approved these changes
Thanks for breaking it up into commits! LGTM!

2018-01-05 20:19 UTC, petermattis commented
> This should probably be a FastIntSet (though I don't think that should be part of this PR, just pointing it out)

Heh, I noticed that too. Do you have any sense for how big typical merge-join batches are?

@arjunravinarayan you need to acknowledge the changes you requested.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21219#-:-L26y4n2V2QNuAQxNaot:b-twpqtg)*
<!-- Sent from Reviewable.io -->

2018-01-05 20:21 UTC, arjunravinarayan commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r7, 3 of 4 files at r9, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21219#-:-L26yzyqag2-WEIp4U_7:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2018-01-05 20:26 UTC, petermattis commented
Hmm, I guess github wants something else (see the red X next to @arjunravinarayan above), but it is allowing me to merge, so away we go.

2018-01-05 20:26 UTC, merged

2018-01-05 20:37 UTC, arjunravinarayan commented
I figured out what the problem was: reviewable borked out on me last night and I used github reviews, and I "requested changes", which put a big X. I needed to "approve" them in GitHub, not reviewable.

2018-01-05 20:38 UTC, RaduBerinde commented
*[pkg/sql/distsqlrun/mergejoiner.go, line 167 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/21219#-L1yhb4Z_L3bGrHloPE0-r7-167:-L271N5vgd_Apr5GBzyL:b-p61ik9) ([raw file](https://github.com/cockroachdb/cockroach/blob/914565af6dbe75112928aafd87fb18d12c214f19/pkg/sql/distsqlrun/mergejoiner.go#L167)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Elegant! Thanks for the comment. Would be good to get one more review on the refactored merge joiner state machine. @RaduBerinde, do you mind taking a quick look at this function?
</blockquote></details>

It looks good to me. This part is easier to review with the separate commits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21219)*
<!-- Sent from Reviewable.io -->

2018-01-05 20:41 UTC, RaduBerinde commented
It's hard to give a blanket statement, but it's common for the merge-join batches to be small (e.g. 1-row batches when joining on a key).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21219#-:-L271aOi4YMub-KAZPsc:b5bt9cz)*
<!-- Sent from Reviewable.io -->