[wip][wip][dnm] RFCs: add range merges RFC
cockroachdb/cockroach pull request #24394
Opened 2018-04-01 03:04 UTC by benesch

This is very much a WIP. I wrote it mostly to collect my own thoughts on range merges. At this stage I'm most interested in getting buy-in on building a general-case prototype, as opposed to the special-cases I lay out in the alternatives section, but I'm of course eager to get feedback on the rest of this design.

2018-04-01 03:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/24394)
<!-- Reviewable:end -->

2018-04-01 04:59 UTC, benesch commented
Just stumbled across https://github.com/cockroachdb/cockroach/issues/2433. Some of the XXXs I left for myself look to be answered there.

2018-04-01 15:30 UTC, tschottdorf commented
Why `[wip][wip]`? To really drive the wip'ness home :smiley:?

Could you discuss the thundering herd? I.e. if we have 1000 adjacent empty ranges and merges suddenly become available, what will happen?

I wrote a long comment about the colocation of replicas, apologies for the wall of text. In the absence of brain farts on my part, though, I think this is all workable. Let me know what you think (happy to chat offline if it's too confused).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 21 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-vHIz7eD6iKJJ9q4Q:-L9-vHIz7eD6iKJJ9q4R:bmzdc4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L21)):*
> ```Markdown
> This causes several problems, ordered from least to most important:
> 
>   1. **User confusion.** Creating a table introduces new ranges, but dropping a
> ```

There's also the real point that you can't change the range size and have it be applied, unless it happens to be smaller than before. And then you're locked into that.

---

*[docs/RFCS/20180330_range_merges.md, line 26 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-v7bvDoqHl8c3h2ev:-L9-v7bvDoqHl8c3h2ew:b551otj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L26)):*
> ```Markdown
> 
>   2. **Bookkeeping overhead.** Every range requires a fixed amount of metadata
>      and must be periodically scanned by the queues (XXX is this true?).
> ```

Yeah this is true, though holding all the ranges in memory is likely the bigger deal.

---

*[docs/RFCS/20180330_range_merges.md, line 40 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-w1EW-gJEuW5RvmDP:-L9-w1EW-gJEuW5RvmDQ:blnyn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L40)):*
> ```Markdown
> undo button, we're currently unwilling to introduce load-based splitting—an
> important feature to unlock performance on skewed workloads—until we can clean
> up after ourselves when the load disappears.
> ```

Queue-like workloads (which are  common) are also a problem because they leave behind an ever-growing tail of empty ranges and that can really mess with latencies as these empty ranges tend to get queried.

---

*[docs/RFCS/20180330_range_merges.md, line 65 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-wdGIDmiKyT17Vb3-:-L9-wdGIDmiKyT17Vb30:b-gxtv91) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L65)):*
> `MERGE AT` returns an error unless `x` is a split point created via a prior `SPLIT AT`. Additionally, it does not guarantee that the two ranges on either side of `x` are actually merged; rather it lifts the restriction that they must be separate. For example, ... 

---

*[docs/RFCS/20180330_range_merges.md, line 80 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-EC88UwOgLx0m45d:-L90-EC88UwOgLx0m45e:but86xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L80)):*
> A merge of _R_ and its right neighbor _S_

---

*[docs/RFCS/20180330_range_merges.md, line 95 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-RwM-gcJRqz0ggzT:-L90-RwM-gcJRqz0ggzU:bltf1hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L95)):*
> ```Markdown
> have a special replicated range-ID local key set that indicates it is not to be
> merged into the range to its left. I'll hereafter refer to this key as the
> "sticky" bit.
> ```

The sticky bit will be inserted into the range split transaction, right? That is you'll plumb it down into `AdminSplit(sticky=true)`. (That makes sense since if you're not doing it atomically, you have to teach the split queue to be sensitive to it, etc).

---

*[docs/RFCS/20180330_range_merges.md, line 101 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-u7E-rVdK3HtAGIK:-L90-u7E-rVdK3HtAGIL:bqn1ci2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L101)):*
> ```Markdown
> command to allow the merge queue to proceed with its evaluation.
> 
> XXX: We might want to run a migration in 2.1 to backfill the sticky bit. It's
> ```

I think we may want to introduce merges behind a cluster setting which defaults to false for clusters that are not bootstrapped into 2.1 or higher, and have a note in the docs that tells operators to activate it and re-run any manual splits they care about. (And periodically log at `Warning` until the setting is flipped; nobody should leave it off).
This is a bit of work, but it'd be a shame if we locked existing clusters into their potentially horribly laid out key space. Or, of course, we provide a tool that undoes all automatic splits and we encourage folks to use it after the upgrade. But I'm also worried about the size of the set-sticky migration; it'd have to write a whole boatload of keys and could run for a long time. If it weren't for that concern, the second solution seems better.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L9027GvBjSdCnsJe7Na:bh3hd2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
> ```Markdown
> Ideally we'll just reuse the split queue's logic here, conjuring up a range
> to ask about by summing together _Q_ and _R_'s range stats. _L<sub>Q</sub>_
> responds immediately to _L<sub>Q</sub>_ with whether it will proceed with the merge.
> ```

I think you mean L_R here, but I'm actually confused about everything after this sentence. It looks like you put `R` in charge of subsuming its left neighbor, but it works the other way around  (so that a range's start key never changes through splits or merges, which is important for the sticky bit). So you want the lease at `Q` and have it execute an `AdminSplit` on `Q` that eats `R`. So the way I imagine this is

1. leaseholder of `R` sends `SuggestMerge` to `Q`
1. on success, leaseholder of `R` colocates `R` with `Q` and then
1. transfers its lease to the replica colocated with leaseholder of `Q`
1. noticing that the replica+lease colocation is complete, leaseholder of `Q` invokes `AdminMerge`

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L90oisI67dxmmRpEZ0J:bko7fao) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
I'm pretty sure `AdminMerge` was never completely correct. The main concern is that `R` is autonomous and hard to lock down while you need it stalled. For starters, you have to prove that when you call `AdminMerge`, the replica configuration doesn't change out from under you. If it does, you've lost - you can't merge ranges that aren't colocated and things *will* explode.

I don't actually think that can happen even today because the merge transaction writes intents on both range descriptors, and any replication change needs to write an intent there as well. So that base is covered: you know that if the replicas are colocated initially, they are colocated when your merge commits.

For the leaseholders, it's trickier. If the leaseholders are colocated at the time of the merge, then there can be a correct merge (I'm also pretty sure tha [...]

2018-04-01 17:18 UTC, bdarnell commented
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 26 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-v7bvDoqHl8c3h2ev:-L91-_146rF3LUnnXtPy:bkpz4n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L26)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Yeah this is true, though holding all the ranges in memory is likely the bigger deal.
</blockquote></details>

Currently the biggest impact is actually that we loop over all ranges every 100ms for the raft ticker. I think we can fix this without merges by storing quiesced and unquiesced ranges separately, though. 

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L911CwH3bhGrpdY5SLW:bgt1f0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
> ```Markdown
> manual `SPLIT AT` and which ranges were split due to exceeding a size threshold
> that they no longer exceed. Maybe we take the conservative approach and give
> every existing range the sticky bit?
> ```

I'd go the other way and say that nothing is initially sticky. Users are far more likely to have data that has split too small than to have manual splits which need to persist even though size threshold are no longer met. In my experience, manual splits are used to help with cold starts, but once the system has been running those original split points are no longer special. I don't think there's a need to apply a permanent sticky bit retroactively. 

---

*[docs/RFCS/20180330_range_merges.md, line 139 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L912vOZ43lPcyftLT5V:-L912vOZ43lPcyftLT5W:b-1qfsa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L139)):*
> ```Markdown
> polling?) Once it receives the lease, it coordinates with the replicate queue to
> align the remainder of _Q_'s replicas with _R_'s. Once all replicas are aligned,
> it executes an `AdminMerge` on _Q_ and the merge is complete.
> ```

One of the tricky parts of this process is that once the replicas are aligned, we must disallow any other replica moves of either range until the merge has completed, but we must also not leave the ranges permanently stuck in place if node running the AdminMerge dies. (But I think @tschottdorf is right and the fact that merges and replica changes use transactions on the same keys saves us here)

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L91AIt69P37OLT_sWEd:b-tjmyaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
> I'm pretty sure AdminMerge was never completely correct.

Right, it was never finished when we realized how hard the remaining bits were going to be and we had more important things to work on at the time.

> I think something that might work here is that you use an intent in the merge transaction again, but this time it's to collide with anyone trying to change the lease of R.

I really don't want to complicate the lease process if we can help it.

I think there's a simpler way here. Once the leases are colocated, we set an in-memory "do not transfer" flag on the Replica. This guarantees that the leases will be colocated until our liveness expires, so we can use the end of our current liveness as the transaction expiration. That way, if the transaction can't complete before our time is up, it will be guaranteed to abort. 

---

*[docs/RFCS/20180330_range_merges.md, line 145 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L913Oxh7YBURWAxlYXn:-L913Oxh7YBURWAxlYXo:b-4om27u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L145)):*
> ```Markdown
> 
> XXX:
>   * Does `AdminMerge` properly handle in-flight traffic to _Q_ and _R_, or do we
> ```

AdminMerge probably needs the same treatment on Q that AdminSplit does: a command-queue write lock for the EndTransaction that runs the merge trigger to ensure the final stats are accurate. We also need some to-be-developed mechanism to lock down R completely during the merge (while still allowing it to unlock if the merge aborts). 

---

*[docs/RFCS/20180330_range_merges.md, line 148 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9172DJ7WGWkKeAsg0B:-L9172DJ7WGWkKeAsg0C:bxcd1eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L148)):*
> ```Markdown
>     need to somehow "lock" them while the merge is in progress?
> 
>   * Is `AdminMerge` correct? Tobi suggests its correctness has likely rotted.
> ```

There has very likely been rot, in addition to the unfinished parts related to locking down the RHS. We'll need to go through splitTrigger, Store.SplitRange, and splitPostApply to make sure that everything there has a counterpart in the merge path. 

---

*[docs/RFCS/20180330_range_merges.md, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L917fhF8XSvqPCs9Tnt:-L917fhF8XSvqPCs9Tnu:b-v9n2q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L156)):*
> ```Markdown
> merging at once.
> 
> Thrashing should be minimal, as _L<sub>Q</sub>_ will reject any
> ```

What about alternating splits and merges? We should ensure that there is a gap between the split and merge threshold so that ranges that are just split are unlikely to immediately become mergeable (even if there is a dip in load or some data deleted). We may want a safeguard like "don't auto-merge a range that has split in the last 24h" (in fact, if we made all splits "sticky" for 24h, would we even want a concept of a permanent sticky bit?)

---

*[docs/RFCS/20180330_range_merges.md, line 160 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L918BPz1qMIkkOZDFOe:-L918BPz1qMIkkOZDFOf:b-bj5j9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L160)):*
> ```Markdown
> and _P_.
> 
> The merge queue will temporarily pause if the cluster is unbalanced to avoid
> ```

How will this imbalance be detected? Why would merges cause further imbalances?

---

*[docs/RFCS/20180330_range_merges.md, line 192 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L918h5j0tgUMJ_4wQNy:-L918h5j0tgUMJ_4wQNz:b-tp9v2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L192)):*
> ```Markdown
>   table cannot receive any external traffic.
> 
>   What if we only merged empty ranges? The allocator could be much dumber about
> ```

If we know the range is empty (and will stay empty), we can leave the allocator out of the process entirely. Just change the endpoints of the other range and let the empty one be GC'd wherever it is. "And will stay empty" is the tricky part - aside from the special case of dropped tables, guaranteeing this seems to require a large enough portion of the general solution that the special case may not be worth it. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 18:25 UTC, tschottdorf commented
Added some more impl suggestions for the actual commit trigger. And I realized I hadn't actually finished reading the document the last time, so the thrashing question is retracted :see_no_evil:

---

Review status: 0 of 1 files reviewed at latest revision, 16 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L91Jjs5CYKFRgvxR-jT:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd go the other way and say that nothing is initially sticky. Users are far more likely to have data that has split too small than to have manual splits which need to persist even though size threshold are no longer met. In my experience, manual splits are used to help with cold starts, but once the system has been running those original split points are no longer special. I don't think there's a need to apply a permanent sticky bit retroactively. 
</blockquote></details>

:+1: 

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L91JtVa0vO4VW7erlIb:b2plxp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> I'm pretty sure AdminMerge was never completely correct.

Right, it was never finished when we realized how hard the remaining bits were going to be and we had more important things to work on at the time.

> I think something that might work here is that you use an intent in the merge transaction again, but this time it's to collide with anyone trying to change the lease of R.

I really don't want to complicate the lease process if we can help it.

I think there's a simpler way here. Once the leases are colocated, we set an in-memory "do not transfer" flag on the Replica. This guarantees that the leases will be colocated until our liveness expires, so we can use the end of our current liveness as the transaction expiration. That way, if the transaction can't complete before our time is up, it will be guaranteed to abort. 

</blockquote></details>

Are you saying we use a txn deadline that is equal to the expiration of the lease on the RHS? That's not how the txn deadline works, the txn deadline compares against the provisional commit timestamp, and that has nothing to do with real time. I hope I'm mistaken about what you're suggesting because I'm always interested in a simpler solution.

---

*[docs/RFCS/20180330_range_merges.md, line 145 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L913Oxh7YBURWAxlYXn:-L91Lad99ZqB-sIuu84Y:b-9ols5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L145)):*
> We also need some to-be-developed mechanism to lock down R completely during the merge (while still allowing it to unlock if the merge aborts).

If we cover all of it via the command queue (the nice thing about merges is that we don't have to recompute anything, though note that we likely want to if `ContainsEstimates` is set) and have the lease pinned, we can

1. at commit evaluation time on `replQ` (if evaluation succeeds) we act similar to the gc queue:
    1. set `replR.mu.destroyed` (in-mem only)
    1. cancel all pending proposals
    1. new: send a canary proposal (to flush out anything else)
    1. now we know `R` is "locked" though at the Raft-level it is still active. (this prevents recreation; we can't just drop it from the store map now).
    1. run the merge trigger evaluation logic. On error, return side effect that undoes the above (i.e. clears `replR.mu.destroyed` CPut-style to avoid clearing a replica corruption error that has happened in the meantime)
    1. note that this needs to lay down a raft tombstone for R in the command's writebatch which prevents all future reincarnations (`MinReplicaID=\infty`). This is an unreplicated key but here we want this done on all replicas, so if there are issues with that we can instead use a side effect which puts it in the writebatch downstream of Raft.
1. at apply time, we already have `acquireMergeLock` which freezes R's Raft
    1. if there is a forced error at apply time (that's not replica corruption), need to still undo the locking on RHS.
1. add to GC queue
1. GC queue should also be sensitive to the tombstones we laid down: if it finds one of those it tries to GC (should always succeed). This is important to clean up after a crash between WriteBatch application and GC.

To block the command queue of the RHS, we can tamper with its command queue directly (similar to how `replR.mu.destroyed` is handled). This seems doable. Wonder if I missed anything.

---

*[docs/RFCS/20180330_range_merges.md, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L917fhF8XSvqPCs9Tnt:-L91RbHcEfQySwJs-ReB:bt7uagl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L156)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What about alternating splits and merges? We should ensure that there is a gap between the split and merge threshold so that ranges that are just split are unlikely to immediately become mergeable (even if there is a dip in load or some data deleted). We may want a safeguard like "don't auto-merge a range that has split in the last 24h" (in fact, if we made all splits "sticky" for 24h, would we even want a concept of a permanent sticky bit?)
</blockquote></details>

Are you aware of any splits that are carried out by users for reasons other than performance? I'm worried that there is some outlandish reason for wanting something split that I don't anticipate, and that we would violate here.

---

*[docs/RFCS/20180330_range_merges.md, line 165 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L91QSfc7i1ca1jdLTXf:-L91QSfc7i1ca1jdLTXg:b-e5j249) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L165)):*
> ```Markdown
> ## Prototype ordering
> 
> I'm planning to start by implementing the merge queue with enough smarts to
> ```

The merge queue is kind of the easy part. The hard part is to actually make `AdminMerge` work correctly, and then to test it. If we can't achieve that, then the merge queue (which I'm much more comfortable you can put together) is moot. How do you feel about starting this bottom-up by trying to make `AdminMerge` correct while introducing a suite of correctness tests that stress our `current + suggested fixes in this RFC` `AdminMerge` implementation? In (unit or acceptance or roach) testing, we have good control over lease and replica placement and can force things to happen very fast.

If within this cycle you arrive at an `AdminMerge` that's trusted, that would be fantastic and I personally wouldn' even care what else you get done. I'd much rather you frantically hack together the merge queue (and we just label it experimental) than the other way around! And you may actually be able to enlist someone else for the merge queue who isn't as familiar with the innards of the core layer.

---

*[docs/RFCS/20180330_range_merges.md, line 192 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L918h5j0tgUMJ_4wQNy:-L91Q6iX5sjhNgZIZ1cJ:b-fyk0ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L192)):*
<details><summary><i>Previously, bdarnell ( [...]

2018-04-01 18:25 UTC, tschottdorf commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 18:33 UTC, petermattis commented
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 26 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-v7bvDoqHl8c3h2ev:-L91Sk-R3RHivL2UL4B9:bamwouw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Currently the biggest impact is actually that we loop over all ranges every 100ms for the raft ticker. I think we can fix this without merges by storing quiesced and unquiesced ranges separately, though. 
</blockquote></details>

The memory usage appears to be non-trivial. The `kv/split/nodes=3` roachtest manually splits a table into 500k ranges without inserting any data and memory usage grows to something like 12GiB. I haven't investigated why. Note that is 10x more ranges per node than we're expecting and it isn't clear that the memory usage is a problem in real clusters. 

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L91TEWQ8jc-YrEmZJB3:bj1kghn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

As a counter-point, for the TPC-C performance work we manually split the items table (100k rows, a few megabytes of data) in order to spread it out across a cluster. It is possible that adjusting the zone config for that table to use a smaller max-range size would have also worked. Note that this table is read-only. A small read-only table is useful to split for improved load distribution. We wouldn't want range merging to work against that, though I'm also not convinced we need manual splits to be sticky.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 18:38 UTC, tschottdorf commented
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L91UxQqAthMgoc_2JXZ:b-wfbgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

As a counter-point, for the TPC-C performance work we manually split the items table (100k rows, a few megabytes of data) in order to spread it out across a cluster. It is possible that adjusting the zone config for that table to use a smaller max-range size would have also worked. Note that this table is read-only. A small read-only table is useful to split for improved load distribution. We wouldn't want range merging to work against that, though I'm also not convinced we need manual splits to be sticky.
</blockquote></details>

But post merging, wouldn't you just set a zone config that mandates ~few mb ranges? Actually you could do that today, but you likely didn't want to bother with querying `crdb_internal.ranges` to wait until that has gone through.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 18:42 UTC, petermattis commented
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L91Vp7B8w4J-j_aVeI-:berxvhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

But post merging, wouldn't you just set a zone config that mandates ~few mb ranges? Actually you could do that today, but you likely didn't want to bother with querying `crdb_internal.ranges` to wait until that has gone through.
</blockquote></details>

Yes, setting a zone config probably would work (I stated as much). So not really a counter-point, but an additional point that we should keep in mind. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 19:01 UTC, benesch commented
> Why [wip][wip]? To really drive the wip'ness home 😃?

Yessir. :stuck_out_tongue_winking_eye: 

> I wrote a long comment about the colocation of replicas, apologies for the wall of text. In the absence of brain farts on my part, though, I think this is all workable. Let me know what you think (happy to chat offline if it's too confused).

Hah, that was exactly what I was after. I figured if I tossed out a partial RFC you and Ben would jump in and help fill in the rest. You two certainly haven't disappointed. :)

---

Review status: 0 of 1 files reviewed at latest revision, 18 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 21 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-vHIz7eD6iKJJ9q4Q:-L91OtE0-yRAsqHQ1D_g:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L21)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

There's also the real point that you can't change the range size and have it be applied, unless it happens to be smaller than before. And then you're locked into that.
</blockquote></details>

Good point. Done.

---

*[docs/RFCS/20180330_range_merges.md, line 26 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-v7bvDoqHl8c3h2ev:-L91OwjG2ydIiG4CTWBX:b-fgow1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L26)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Currently the biggest impact is actually that we loop over all ranges every 100ms for the raft ticker. I think we can fix this without merges by storing quiesced and unquiesced ranges separately, though. 
</blockquote></details>

Fleshed this section out a bit. The Raft ticker problem is now noted in the alternatives section below.

---

*[docs/RFCS/20180330_range_merges.md, line 40 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-w1EW-gJEuW5RvmDP:-L91R0u9EQ7rfvv3ttxf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L40)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Queue-like workloads (which are  common) are also a problem because they leave behind an ever-growing tail of empty ranges and that can really mess with latencies as these empty ranges tend to get queried.
</blockquote></details>

Done.

---

*[docs/RFCS/20180330_range_merges.md, line 65 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9-wdGIDmiKyT17Vb3-:-L91R47EE3O_ocJccvAp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L65)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> `MERGE AT` returns an error unless `x` is a split point created via a prior `SPLIT AT`. Additionally, it does not guarantee that the two ranges on either side of `x` are actually merged; rather it lifts the restriction that they must be separate. For example, ... 
</blockquote></details>

Done.

---

*[docs/RFCS/20180330_range_merges.md, line 80 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-EC88UwOgLx0m45d:-L91RUsk0gL1UeT6zYk1:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> A merge of _R_ and its right neighbor _S_
</blockquote></details>

Thanks, done.

---

*[docs/RFCS/20180330_range_merges.md, line 95 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-RwM-gcJRqz0ggzT:-L91RYKQ-w-FnC7_xs9E:b78wuyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L95)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The sticky bit will be inserted into the range split transaction, right? That is you'll plumb it down into `AdminSplit(sticky=true)`. (That makes sense since if you're not doing it atomically, you have to teach the split queue to be sensitive to it, etc).
</blockquote></details>

Ugh, it's not quite so simple though. We'll want to be able to set the bit even if the split already exists.

---

*[docs/RFCS/20180330_range_merges.md, line 101 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-u7E-rVdK3HtAGIK:-L91RuO3E2O1-g7XPf_U:bf9tsqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L101)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I think we may want to introduce merges behind a cluster setting which defaults to false for clusters that are not bootstrapped into 2.1 or higher, and have a note in the docs that tells operators to activate it and re-run any manual splits they care about. (And periodically log at `Warning` until the setting is flipped; nobody should leave it off).
This is a bit of work, but it'd be a shame if we locked existing clusters into their potentially horribly laid out key space. Or, of course, we provide a tool that undoes all automatic splits and we encourage folks to use it after the upgrade. But I'm also worried about the size of the set-sticky migration; it'd have to write a whole boatload of keys and could run for a long time. If it weren't for that concern, the second solution seems better.
</blockquote></details>

Ack, this definitely needs more thought.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L91SWe12RsKql2n4aOo:bpg3kfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I think you mean L_R here, but I'm actually confused about everything after this sentence. It looks like you put `R` in charge of subsuming its left neighbor, but it works the other way around  (so that a range's start key never changes through splits or merges, which is important for the sticky bit). So you want the lease at `Q` and have it execute an `AdminSplit` on `Q` that eats `R`. So the way I imagine this is

1. leaseholder of `R` sends `SuggestMerge` to `Q`
1. on success, leaseholder of `R` colocates `R` with `Q` and then
1. transfers its lease to the replica colocated with leaseholder of `Q`
1. noticing that the replica+lease colocation is complete, leaseholder of `Q` invokes `AdminMerge`
</blockquote></details>

The two phases are distinct, though. There's the colocation phase where `R` pulls `Q` over to the same ranges, then the merge phase where `Q` merges into `R`. So I _think_ what's written here is viable.

I agree it's confusing and stupid, though, for these phases to look in different directions. The colocation phase should just look rightward. I'll rework this.

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L91L1iZDP1f70cp-dG0:b-5ldpot) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Are you saying we use a txn deadline that is equal to the expiration of the lease on the RHS? That's not how the txn deadline works, the txn deadli [...]

2018-04-01 20:56 UTC, tschottdorf commented
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 95 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-RwM-gcJRqz0ggzT:-L91wag34yfz2jByooX3:b-9pf5lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L95)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ugh, it's not quite so simple though. We'll want to be able to set the bit even if the split already exists.
</blockquote></details>

`AdminSplit` is the thing that runs the distributed split transaction, so the new code in `AdminSplit` will be something like `txn.Get(stickyKey); if !bitIsSet { txn.Put(stickyKey) }`, i.e. it's idempotent.

---

*[docs/RFCS/20180330_range_merges.md, line 101 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-u7E-rVdK3HtAGIK:-L91wo2HEuU_JHKd6PI6:b-wen8ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L101)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ack, this definitely needs more thought.
</blockquote></details>

FWIW, I like Ben's suggestion to just turn it on, though I'm not sure the real world doesn't have a case in which that's a bad idea. We can also introduce the cluster setting to turn it off (but have it on by default) so that folks have a chance to turn it off *before* they bump the cluster version.

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L91wzXV6FlXIN9h9f5w:bgg5b4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes, setting a zone config probably would work (I stated as much). So not really a counter-point, but an additional point that we should keep in mind. 
</blockquote></details>

Apologies, reading is not my strong suit today. There was a time in high school where I'd routinely just forget about whole exercises in math exams. Feel reminded of that today.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L91xSO-77X3r3r_dott:bp0a6sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

The two phases are distinct, though. There's the colocation phase where `R` pulls `Q` over to the same ranges, then the merge phase where `Q` merges into `R`. So I _think_ what's written here is viable.

I agree it's confusing and stupid, though, for these phases to look in different directions. The colocation phase should just look rightward. I'll rework this.
</blockquote></details>

Ack, I'll hold off until you've done so.

---

*[docs/RFCS/20180330_range_merges.md, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L917fhF8XSvqPCs9Tnt:-L91y9Ws8GwVQZDwZon5:b-4dpy7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L156)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

> We may want a safeguard like "don't auto-merge a range that has split in the last 24h"

Agreed, though I was thinking a threshold on the order of minutes, not hours.

> in fact, if we made all splits "sticky" for 24h, would we even want a concept of a permanent sticky bit?

I think we still would. If I run `ALTER TABLE ... SPLIT AT generate_series(1, 100)` today, I'm going to be mighty confused when I come back tomorrow and the splits have all disappeared. I'm very willing to be convinced otherwise, though. I expect the sticky bit will be one of the last things I tackle.
</blockquote></details>

Also doesn't seem that the sticky bit informs any of the other mechanisms, right? It's just a take it or leave it addon.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 22:01 UTC, bdarnell commented
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 101 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90-u7E-rVdK3HtAGIK:-L928a8Q7nDS3M4Phlfe:b-ktth18) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L101)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

FWIW, I like Ben's suggestion to just turn it on, though I'm not sure the real world doesn't have a case in which that's a bad idea. We can also introduce the cluster setting to turn it off (but have it on by default) so that folks have a chance to turn it off *before* they bump the cluster version.
</blockquote></details>

Even if we "just turn it on", it will need to be behind a cluster version. I like the idea of having a setting that can be toggled while the upgrade is in its non-finalized state (but be aware of the auto-finalize proposal in #24377)

---

*[docs/RFCS/20180330_range_merges.md, line 105 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L911CwH3bhGrpdY5SLV:-L928tWaDLGqHalJKX5e:b-18q8p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L105)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Apologies, reading is not my strong suit today. There was a time in high school where I'd routinely just forget about whole exercises in math exams. Feel reminded of that today.
</blockquote></details>

Yeah, by saying that no pre-2.1 splits are sticky we might break a few use cases, and they'll need to either set zone configs with small limits or manually re-run their splits to set the sticky bit. I consider this preferable to the alternative of "all pre-2.1 splits are sticky". 

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L929C_J9BPjpJu7f1-g:b-i25qzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ack, I'll hold off until you've done so.
</blockquote></details>

FWIW, I think things make sense as described here. The queue runs on replicas looking leftward, and if it makes sense from their perspective it hands off to the leftward range for the rest of the process (which can now proceed with input from both ranges). 

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L929XSyCvwYJuA9PRtH:b-8x19b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
> Are you saying we use a txn deadline that is equal to the expiration of the lease on the RHS? That's not how the txn deadline works, the txn deadline compares against the provisional commit timestamp, and that has nothing to do with real time.

Yes, exactly, but I see now that I'd need a new change: EndTransaction needs to consult the timestamp cache, so that a new leaseholder can't commit a transaction started by the previous leaseholder. 

---

*[docs/RFCS/20180330_range_merges.md, line 156 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L917fhF8XSvqPCs9Tnt:-L92Bum96-oC6HDW0jT4:b-5d5ady) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L156)):*
> Are you aware of any splits that are carried out by users for reasons other than performance? I'm worried that there is some outlandish reason for wanting something split that I don't anticipate, and that we would violate here.

Maybe as a poor-man's partitioning? But without zone constraints I can't see why that would matter for anything but performance. 

> Agreed, though I was thinking a threshold on the order of minutes, not hours.

For manual splits we'd definitely want hours, if not days. For auto-splits minutes might be OK, but still seems aggressive to me. If we set the limit less than 24h, some clusters will have traffic patterns that split every morning and re-merge at night. (is that OK? Maybe, but it seems better to me to just leave the splits in place)

> I think we still would. If I run ALTER TABLE ... SPLIT AT generate_series(1, 100) today, I'm going to be mighty confused when I come back tomorrow and the splits have all disappeared.

I see manual splits as primarily aimed at the cold start problem. As long as I split less than 24h before my launch/announcement/whatever, I'd be fine and the ranges will grow into their unmergeable sizes pretty quickly. The question is whether it's reasonable for admins savvy enough to do manual pre-splitting to also be able to schedule their pre-splitting within 24h of of the traffic spike. 

I think having the sticky bit is better than not having it, but note that if we drop it, we also don't need the `MERGE AT` command, so it's heavier than it initially looks.

---

*[docs/RFCS/20180330_range_merges.md, line 160 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L918BPz1qMIkkOZDFOe:-L92DGU03EeLLsHQZcr7:brp0992) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L160)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

In the wost case, merges could pull three replicas off underfull nodes and transfer them to overfull nodes. And even if you're doing neutral work (moving a replica from an overfull store to another overfull store, say), you're preventing a preemptive snapshot that could have balanced the cluster.

Doesn't seem like it would be too hard to pause the merge queue when the store pool thinks some stores are overfull/underfull.
</blockquote></details>

Or conversely when a merge opportunity has been identified, the replication queue should try to make room for it to happen (the ranges to merge are already going to be below-average in size). 

---

*[docs/RFCS/20180330_range_merges.md, line 192 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L918h5j0tgUMJ_4wQNy:-L92DYTU5W3pzcLxzztN:b-ml8jx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L192)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Having thought about the general case a bit now, it's my impression that tackling it head-on is worth it.
</blockquote></details>

That's my thought as well.

---

*[docs/RFCS/20180330_range_merges.md, line 76 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9289Xb4fOWzOE-_KKS:-L9289Xb4fOWzOE-_KKT:b-e7snk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L76)):*
> ```Markdown
> the split point will remain.
> 
> `MERGE AT` returns an error if any of the listed split points were not created
> ```

I think `MERGE AT` should at least attempt a merge if the split points were not created by `SPLIT AT`. Similarly, even if the split points were created by `SPLIT AT`, if the merge fails it should return with an error like "ranges too large to merge". 

If it *only* removes the sticky bit without attempting the merge, I'd call it `UNSPLIT AT`. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-01 22:51 UTC, tschottdorf commented
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L92LWEp20zeetLxvz6G:b-8rwtp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
> where Q merges into R

FWIW, this is exactly the opposite of what's happening, no? `R` merges into `Q` (i.e., after the merge, `Q` is still there but larger). This confusion permeates the text below and maybe explains why I'm confused. I understand that there will be a phase where `R` colocates itself with `Q` and then hands over to `Q` for the actual merge.

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L92LprC4IO_0sbhi8q_:b-3gk67) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> Are you saying we use a txn deadline that is equal to the expiration of the lease on the RHS? That's not how the txn deadline works, the txn deadline compares against the provisional commit timestamp, and that has nothing to do with real time.

Yes, exactly, but I see now that I'd need a new change: EndTransaction needs to consult the timestamp cache, so that a new leaseholder can't commit a transaction started by the previous leaseholder. 
</blockquote></details>

I'm still confused about what you're suggesting. We have a transaction that will commit on `Q` and `R` is the lease we care about. Both use the same node's epoch, but I'm not sure how that helps. You can't have anything below Raft look into `R` (or use the current time) because what you'll find is not the same on all replicas (for example a follower may have a far-behind version of `R` that has a past leaseholder, we can work around that but again, you wanted something simple). Can you ELI5 ("explain like I'm five")?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-02 04:19 UTC, benesch commented
<img width="976" alt="image" src="https://user-images.githubusercontent.com/882976/38182885-78b81c2e-360a-11e8-8184-5e06b415e18f.png">

Check out that blip at 4:04. Four range merges in a real cluster! Pay the catastrophic failure that occurs next no mind. That's Raft complaining about a missing log, but it resolves after a restart so how bad can it be? :trollface:

2018-04-02 17:33 UTC, bdarnell commented
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L96OzsE3F7-yA0xsUJD:buhd232) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'm still confused about what you're suggesting. We have a transaction that will commit on `Q` and `R` is the lease we care about. Both use the same node's epoch, but I'm not sure how that helps. You can't have anything below Raft look into `R` (or use the current time) because what you'll find is not the same on all replicas (for example a follower may have a far-behind version of `R` that has a past leaseholder, we can work around that but again, you wanted something simple). Can you ELI5 ("explain like I'm five")?
</blockquote></details>

Nevermind, you're right. I wasn't thinking enough about the followers and was just trying to synchronize between the two Replicas on the leader. But I don't see how the intent proposal above addresses the problem of lagging followers either. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-03 21:42 UTC, benesch commented
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L9BqJGs7MLNloOOKZme:b-i0zif1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> where Q merges into R

FWIW, this is exactly the opposite of what's happening, no? `R` merges into `Q` (i.e., after the merge, `Q` is still there but larger). This confusion permeates the text below and maybe explains why I'm confused. I understand that there will be a phase where `R` colocates itself with `Q` and then hands over to `Q` for the actual merge.
</blockquote></details>

Hmm, I'm confused about why you're confused. I looked at it again and it seems correct. _R_ considers a merge leftward with _Q_. If things looks good, it says, "hey _Q_, how do you feel about this?" If _Q_ likes it too, _Q_ moves into alignment with _R_ AND cedes the lease to _R_'s leaseholder. Then _R_'s leaseholder, having _Q_'s lease now, merges _R_ into _Q_.

The benefit here is that you'll never have to roundtrip to find out of the sticky bit is set. (The sticky bit necessarily needs to be set on the RHS of a split because ranges are inclusive on the LHS.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-04 18:13 UTC, nvanbenschoten commented
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 76 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9289Xb4fOWzOE-_KKS:-L9GbRTzDfDhbiqO-KY9:b-d05f0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L76)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think `MERGE AT` should at least attempt a merge if the split points were not created by `SPLIT AT`. Similarly, even if the split points were created by `SPLIT AT`, if the merge fails it should return with an error like "ranges too large to merge". 

If it *only* removes the sticky bit without attempting the merge, I'd call it `UNSPLIT AT`. 
</blockquote></details>

+1 to both of those points. `SPLIT AT` has been so useful because it allows us to bypass any magic and performs its operation synchronously. Ideally `MERGE AT` would have the same properties.

---

*[docs/RFCS/20180330_range_merges.md, line 103 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9GfREe7kwlgJjNYoeu:-L9GfREe7kwlgJjNYoev:b3w079f) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L103)):*
> ```Markdown
> 
> To preserve these user-created split points, we need to store state. I
> tentatively propose using a replicated range-ID local key. Every range to the
> ```

An alternative approach would be to make this a range local key and put it right next to the split point itself. This would allow the sticky bit to be more easily worked with since it would be addressable. It would also naturally force the key onto the right side of the manual split, which fits with the rest of the proposal here.

---

*[docs/RFCS/20180330_range_merges.md, line 137 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9Gh1zFEPjjEGCPqLqj:-L9Gh1zFEPjjEGCPqLqk:b-xryvjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L137)):*
> ```Markdown
> ```
> 
> Now _Q_'s leaseholder _L<sub>Q</sub>_ has perfect information. The merge
> ```

Perfect information? In a distributed system? That must be nice :smiley: 

Unfortunately, since we're not locking both ranges while we process this suggestion, it will always be racey. For instance, while this series of rebalances and lease transfers is taking place, Q and R could continue to grow. We'll need to consider what happens if a split of Q races with a merge of R into Q.

EDIT: I see you proposed this as a question below and that this is already a lively discussion!

Another race we'll need to explore is a series of ranges each concurrently attempting to merge into the range on their left. Again, I don't think we'll be able to avoid this entirely, but it does introduce an interesting question. Should we favor small ranges merging left into large ranges, large ranges merging left into small ranges, or have no preference? A situation that demonstrates why we should think about this is the case where an empty range is sandwiched between two other ranges. Without any preference for who kicks off the merge, this case could regularly end up in a racing double merge. This could be avoided in the common case by only adding ranges that are less than half the `max_range_size` to the merge queue.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-04 21:43 UTC, tschottdorf commented
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L9Hb3xH4Jo0sYsv141w:b-kh645) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
I wrote another wall of text. I'm afraid this isn't easily digested and may contain overcomplicated and incorrect solutions. But I think it does a decent job at exposing a number of problems we need to solve. I'm happy to talk these through offline.

The exposition is also lacking, but I've rewritten this numerous times already and I think it's time to involve more eyes in that process.

## Making sure the RHS is up to date at the time of merge trigger

First of all, we must also solve the "RHS catch-up problem": when the merge trigger executes, the subsumed replica must be at a log position after we locked down the leaseholder (ie. it has the latest writes). I think this is most adequately addressed by a round of long-poll RPCs to all the replicas of `R` after having locked down the leaseholder and proposed a noop write with a trigger in it (that signals the polls). Trying to do this from below Raft is a non-starter. So from now on I will assume that whenever a merge trigger runs and the RHS is present, it will be up to date.

## Snapshots

Something else we have to worry about is that we must not send any snapshots that contain a merge trigger in the log entries. The recipient won't be able to apply the merge trigger; we must send a higher-index snapshot that postdates the merge.

## AdminMerge Lock-Down

We make sure that the `AdminMerge` transaction can only commit with the node running the `AdminMerge` holding the lease for `Q` (i.e. we pass the lease sequence into the merge trigger).

## Leaseholder Lock-Down

So our only problem left (hopefully) is to lock down (lease and data of) `R`. To lock down the current lease on `L`, we communicate directly with the lease holder before committing the merge trigger (there are details to be figured out here, but basically this should work).

Now we need to prevent followers from stealing a lease unless the merge is aborted. I still believe that the best way to achieve that is to insert a cheap check that runs after a lease acquisition on `L` before using the lease.

### Lease Check

The check simply retrieves `keys.RangeDescriptorKey(desc.StartKey)`. If that key is a deletion intent (it'll be anchored on `Q`), we need to push it before continuing. If the read comes back with a descriptor that's not ours (i.e. empty or changed), we know we've been merged away, reject all requests (with a range key mismatch error), and move ourselves to the mergatory described below. Note that in trying to push the intent, we wait for the merge to commit (unless we decide to push with high priority, in which case we would abort. Since we also want to merge expiration-based ranges, I think waiting makes sense but I could be convinced otherwise).

Note that as far as the data goes, it's OK if `R` sticks around for a while and uses its Raft machinery and gets a lease, even after `QR` exists. The lease and Raft state are both keyed by range ID, so there will be no conflict between the post-merge range `QR` and `R`:

```
  .-- keyed by RangeID of R
  |     .-- keyed by RangeID of QR (=post-merge Q)
  |     |          .-- RangeDescriptorKey(R)
  v     |          v
[----)  v          [------R's-data------)
      [----)       [-------QR's-(data)---------------)
```

There's no requirement to synchronously knock out `R` as the lease trigger applies. This is helpful because in the general case we can't guarantee that, see the "Handling Q-rebalances" section below.

Note: `(*Replica).assertStateLocked` will fire if run, since the on-disk descriptor and the in-memory copy have diverged.

### Mergatory

The "mergatory" (bad pun on merge+purgatory, not suggested name) is a list of replicas that the store still owns, but which have been merged away and don't own their data keyspace any more. We could avoid having a mergatory if we eagerly ran GC on a replica while moving it into the mergatory, but this can be problematic for performance, so keep that in mind.

Replicas in the mergatory are ignored by `LookupReplica` and are unable to interfere with the range that subsumed them due to the lease check described later and the disjointness of the rangeID-based keyspace.

The mergatory is visited by the GC queue with high priority.

## GCQueue

The GC queue is ultimately responsible for removing the data. Assuming that it finds out (via the meta ranges) that a range has been merged away, it has to distinguish two cases by answering the question:

> Is the keyspace that originally belonged to `R` claimed by another replica on this store?

This is a question that's easy to answer by looking into the local store map (with sufficient synchronization). It can only be true if the range is in the mergatory (another good assertion).  Another good assertion is that if a replica comes from the mergatory, it must definitely be GC'ed.

If the answer to the question above is "yes", only the rangeID-keyed keyspace is wiped, and otherwise the data as well.

## Handling Q-rebalances

### Away

Consider the scenario in which a replica of `Q` gets rebalanced off a follower node before it has any chance to apply the trigger. `R` will sit around forever wondering what went wrong. The lease check will take care of when the replica is next woken up by a queue. The replica will move to mergatory and will be removed.

### Back

Note that in addition to the previous scenario. `Q` (or parts of `Q` overlapping `R`; `Q` may have split in the meantime) comes back (in its post-merge size `QR`), and that `R` has not been removed yet. In that case, the snapshot for `Q` will intersect `R`. We simply make sure that this wakes up `R` and so it should move itself to mergatory and stop blocking the snapshot (since the mergatory replicas are not considered as owning any part of the addressable keyspace). This is similar to a mechanism for splits today.

## Note: Eager Intent Resolution

Note that the eager intent resolution with the GC will resolve the intent on the range descriptor of `R` eagerly. This means that if the node restarts and there is an intent, then the intent is ignored (because that implies that the merge trigger has not been processed yet). This is a subtle invariant; with the possiblity of "committed intents", the situation complicates fundamentally. (There is a similar property for splits which, if absent, would make the world more complicated).

## Avoiding RangeID-Keyspace Leaks

The case in which a replica gets put into mergatory just before the process dies is noteworthy. In that case, when the server starts, it won't instantiate the replica in the first place (as there's no range descriptor). A naive solution is to try to be sensitive to tombstones, but those may have been wiped away with the range `QR` rebalancing off the node.

Note that making the mergatory synchronous does not solve this problem (see the Q-away case above). We can address this by making sure that any nontrivial `RangeID`-keyspace (nontrivial means that it contains more than a replica tombstone) also contains a key that mentions the start key. The server startup process can then iterate through those keys and, for each of them, checks whether the corresponding range is initialized. If not, the corresponding rangeID prefix is wiped.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-05 13:02 UTC, tschottdorf commented
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/20180330_range_merges.md, line 144 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L90oisI67dxmmRpEZ0I:-L9KsqjrBi18hOnnsat8:b-lzbrbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I wrote another wall of text. I'm afraid this isn't easily digested and may contain overcomplicated and incorrect solutions. But I think it does a decent job at exposing a number of problems we need to solve. I'm happy to talk these through offline.

The exposition is also lacking, but I've rewritten this numerous times already and I think it's time to involve more eyes in that process.

## Making sure the RHS is up to date at the time of merge trigger

First of all, we must also solve the "RHS catch-up problem": when the merge trigger executes, the subsumed replica must be at a log position after we locked down the leaseholder (ie. it has the latest writes). I think this is most adequately addressed by a round of long-poll RPCs to all the replicas of `R` after having locked down the leaseholder and proposed a noop write with a trigger in it (that signals the polls). Trying to do this from below Raft is a non-starter. So from now on I will assume that whenever a merge trigger runs and the RHS is present, it will be up to date.

## Snapshots

Something else we have to worry about is that we must not send any snapshots that contain a merge trigger in the log entries. The recipient won't be able to apply the merge trigger; we must send a higher-index snapshot that postdates the merge.

## AdminMerge Lock-Down

We make sure that the `AdminMerge` transaction can only commit with the node running the `AdminMerge` holding the lease for `Q` (i.e. we pass the lease sequence into the merge trigger).

## Leaseholder Lock-Down

So our only problem left (hopefully) is to lock down (lease and data of) `R`. To lock down the current lease on `L`, we communicate directly with the lease holder before committing the merge trigger (there are details to be figured out here, but basically this should work).

Now we need to prevent followers from stealing a lease unless the merge is aborted. I still believe that the best way to achieve that is to insert a cheap check that runs after a lease acquisition on `L` before using the lease.

### Lease Check

The check simply retrieves `keys.RangeDescriptorKey(desc.StartKey)`. If that key is a deletion intent (it'll be anchored on `Q`), we need to push it before continuing. If the read comes back with a descriptor that's not ours (i.e. empty or changed), we know we've been merged away, reject all requests (with a range key mismatch error), and move ourselves to the mergatory described below. Note that in trying to push the intent, we wait for the merge to commit (unless we decide to push with high priority, in which case we would abort. Since we also want to merge expiration-based ranges, I think waiting makes sense but I could be convinced otherwise).

Note that as far as the data goes, it's OK if `R` sticks around for a while and uses its Raft machinery and gets a lease, even after `QR` exists. The lease and Raft state are both keyed by range ID, so there will be no conflict between the post-merge range `QR` and `R`:

```
  .-- keyed by RangeID of R
  |     .-- keyed by RangeID of QR (=post-merge Q)
  |     |          .-- RangeDescriptorKey(R)
  v     |          v
[----)  v          [------R's-data------)
      [----)       [-------QR's-(data)---------------)
```

There's no requirement to synchronously knock out `R` as the lease trigger applies. This is helpful because in the general case we can't guarantee that, see the "Handling Q-rebalances" section below.

Note: `(*Replica).assertStateLocked` will fire if run, since the on-disk descriptor and the in-memory copy have diverged.

### Mergatory

The "mergatory" (bad pun on merge+purgatory, not suggested name) is a list of replicas that the store still owns, but which have been merged away and don't own their data keyspace any more. We could avoid having a mergatory if we eagerly ran GC on a replica while moving it into the mergatory, but this can be problematic for performance, so keep that in mind.

Replicas in the mergatory are ignored by `LookupReplica` and are unable to interfere with the range that subsumed them due to the lease check described later and the disjointness of the rangeID-based keyspace.

The mergatory is visited by the GC queue with high priority.

## GCQueue

The GC queue is ultimately responsible for removing the data. Assuming that it finds out (via the meta ranges) that a range has been merged away, it has to distinguish two cases by answering the question:

> Is the keyspace that originally belonged to `R` claimed by another replica on this store?

This is a question that's easy to answer by looking into the local store map (with sufficient synchronization). It can only be true if the range is in the mergatory (another good assertion).  Another good assertion is that if a replica comes from the mergatory, it must definitely be GC'ed.

If the answer to the question above is "yes", only the rangeID-keyed keyspace is wiped, and otherwise the data as well.

## Handling Q-rebalances

### Away

Consider the scenario in which a replica of `Q` gets rebalanced off a follower node before it has any chance to apply the trigger. `R` will sit around forever wondering what went wrong. The lease check will take care of when the replica is next woken up by a queue. The replica will move to mergatory and will be removed.

### Back

Note that in addition to the previous scenario. `Q` (or parts of `Q` overlapping `R`; `Q` may have split in the meantime) comes back (in its post-merge size `QR`), and that `R` has not been removed yet. In that case, the snapshot for `Q` will intersect `R`. We simply make sure that this wakes up `R` and so it should move itself to mergatory and stop blocking the snapshot (since the mergatory replicas are not considered as owning any part of the addressable keyspace). This is similar to a mechanism for splits today.

## Note: Eager Intent Resolution

Note that the eager intent resolution with the GC will resolve the intent on the range descriptor of `R` eagerly. This means that if the node restarts and there is an intent, then the intent is ignored (because that implies that the merge trigger has not been processed yet). This is a subtle invariant; with the possiblity of "committed intents", the situation complicates fundamentally. (There is a similar property for splits which, if absent, would make the world more complicated).

## Avoiding RangeID-Keyspace Leaks

The case in which a replica gets put into mergatory just before the process dies is noteworthy. In that case, when the server starts, it won't instantiate the replica in the first place (as there's no range descriptor). A naive solution is to try to be sensitive to tombstones, but those may have been wiped away with the range `QR` rebalancing off the node.

Note that making the mergatory synchronous does not solve this problem (see the Q-away case above). We can address this by making sure that any nontrivial `RangeID`-keyspace (nontrivial means that it contains more than a replica tombstone) also contains a key that mentions the start key. The server startup process can then iterate through those keys and, for each of them, checks whether the corresponding range is initialized. If not, the corresponding rangeID prefix is wiped.

</blockquote></details>

Eh, already found the first buglet. We have to handle intents on the range descriptors at server start time, but only if the node didn't execute the merge trigger and hasn't received a snapshot of `QR` in the meant [...]

2018-04-05 15:24 UTC, bdarnell commented
> First of all, we must also solve the "RHS catch-up problem": when the merge trigger executes, the subsumed replica must be at a log position after we locked down the leaseholder (ie. it has the latest writes). I think this is most adequately addressed by a round of long-poll RPCs to all the replicas of R

The leader knows the last acknowledged log position of each follower. It lags application by a little bit, but I think it's good enough to treat this as a local problem instead of one requiring coordination. The leader waits for all replicas to ack the last log entry in the RHS before sending the EndTransaction, then all the replicas block in the merge trigger until the RHS's applied index has caught up. This is a little hand-wavy (do we need to worry about deadlocks if the raft scheduler runs out of threads?), but I think there's an answer here without adding special long-poll RPCs (it's also possible that long-poll RPCs are a cleaner solution than whatever synchronization we end up needing here). 

> Something else we have to worry about is that we must not send any snapshots that contain a merge trigger in the log entries. The recipient won't be able to apply the merge trigger; we must send a higher-index snapshot that postdates the merge.

The snapshot must be sent with a higher *applied* index. The entry with the merge trigger need not be truncated away. I think this is already covered: we don't send unapplied log entries with our snapshots. 

> We make sure that the AdminMerge transaction can only commit with the node running the AdminMerge holding the lease for Q (i.e. we pass the lease sequence into the merge trigger).

Is it the merge trigger (upstream of raft) or Store.MergeRange (downstream of raft)? Store.MergeRange is the one that worries me more. 

> To lock down the current lease on L, we communicate directly with the lease holder before committing the merge trigger (there are details to be figured out here, but basically this should work).

Who is "we" here? And what are Q and L here? I'm pretty sure R is the RHS; do Q and L both refer to the LHS or are they something different?

> I still believe that the best way to achieve that is to insert a cheap check that runs after a lease acquisition on L before using the lease.

Don't you mean R? I'm still very wary of adding anything that can block lease acquisition.

> Consider the scenario in which a replica of Q gets rebalanced off a follower node before it has any chance to apply the trigger. R will sit around forever wondering what went wrong. The lease check will take care of when the replica is next woken up by a queue.

I don't think the *followers* of R do anything different here. They will respond to anything the leader sends them. The lockdown only applies to the leader of R, which should be co-located with the leader of Q at the time of the merge. I think the question here is what happens if the leader dies immediately after performing the merge and new leaders of both Q and R get elected.

2018-04-05 20:45 UTC, tschottdorf commented
> The leader knows the last acknowledged log position of each follower. It lags application by a little bit, but I think it's good enough to treat this as a local problem instead of one requiring coordination. The leader waits for all replicas to ack the last log entry in the RHS before sending the EndTransaction, then all the replicas block in the merge trigger until the RHS's applied index has caught up. This is a little hand-wavy (do we need to worry about deadlocks if the raft scheduler runs out of threads?), but I think there's an answer here without adding special long-poll RPCs (it's also possible that long-poll RPCs are a cleaner solution than whatever synchronization we end up needing here).

Yeah, that might be a good alternative.

> Is it the merge trigger (upstream of raft) or Store.MergeRange (downstream of raft)? Store.MergeRange is the one that worries me more.

Downstream. I'm suggesting that application of the merge trigger catches a `forcedError`. By "Is it the merge trigger (upstream of raft)", do you mean evaluation of the merge `EndTransaction`? We should ideally catch it there too, but if the lockdown of the RHS is properly reversible (which it needs to be anyway) I think it's OK if we didn't do that.

> Who is "we" here? And what are Q and L here? I'm pretty sure R is the RHS; do Q and L both refer to the LHS or are they something different?

Sorry, there's only `Q` and `R` (I say `QR` when I mean the post-merge `Q`). `Q` is also the `LHS` and `R` is the `RHS`. Would have been to easy had I been anywhere close to consistent.

> Don't you mean R? I'm still very wary of adding anything that can block lease acquisition.

Yeah, `R`, sorry. So don't we absolutely positively have to block lease acquisition? If we don't block lease acquisition we allow replicas of L to get a lease and "do things", which is 100% incorrect if `L` has been merged already. Note that the check is "free" and only has an effect when there's a merge going on. And note that we acquire the lease, we just don't allow it to be used for data that `L` holds or once held unless we know which of the two it is.

Whatever alternative you have in mind (do you have one? I'd be interested to hear) it needs to work even if `R` is not colocated with `Q` and never gets to see the merge trigger. See the `Q-Away` section.

There are approximately 100 lose ends already in this PR. I think we should get some dedicated real world time to attack some of these between the three of us and decide what can work and what can't. I'm happy to do the prep work and condense the problems and ideas collected so far into something more digestible. WDY @bdarnell?

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-:-L9MVFD61uvCZUWgQ9Bb:b-2r4f9j)*
<!-- Sent from Reviewable.io -->

2018-04-09 18:18 UTC, bdarnell commented
> By "Is it the merge trigger (upstream of raft)", do you mean evaluation of the merge EndTransaction? 

Yes

> Downstream. I'm suggesting that application of the merge trigger catches a forcedError.

This means that some replicas could experience an error while applying this command while others don't. This would have to be something like a replicaCorruptionError (which means we'd need to make sure that mechanism really works, and figure out what it means to make it reversible). 

> Yeah, R, sorry. So don't we absolutely positively have to block lease acquisition?

We must not allow both a merge and a lease acquisition to succeed. One way is to block lease acquisitions if there is any chance a merge that could succeed is in flight. The other way is to ensure that the merge will fail if a new lease is acquired on R. 

My incomplete suggestion for the latter is to use transaction deadlines: Before time T, the merge can commit, but the lease can't change hands. Afterwards, the reverse is true. The problem with this is of course that the EndTransaction can be proposed but not yet applied. If we were dealing with a single range, the EndTransaction would be well-ordered with respect to the lease attempt (and the new lease will invalidate all commands proposed under the old lease). With two ranges, that's trickier if not impossible. 

> Whatever alternative you have in mind (do you have one? I'd be interested to hear) it needs to work even if R is not colocated with Q and never gets to see the merge trigger. See the Q-Away section.

When we start the merge transaction, we verify that Q and R are co-located, and we write an intent to the range descriptor which ensures that this can't change unless our transaction is aborted. So by the time any rebalancing can occur, we know the disposition of the merge transaction. If the merge succeeded, we shouldn't try to move the dead range R. If Q completes and immediately moves, everything should generally be fine. We just can't copy Q to a store that has a stale replica of R. Am I missing something here? I think the problems with the lease-timestamp proposal mainly have to do with out-of-date replicas instead of non-colocated ones.

> I think we should get some dedicated real world time to attack some of these between the three of us and decide what can work and what can't. I'm happy to do the prep work and condense the problems and ideas collected so far into something more digestible. WDY @bdarnell?

SGTM

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-:-L9fLna36OYKj7EFpV5M:b-2gektn)*
<!-- Sent from Reviewable.io -->

2018-04-10 18:42 UTC, tschottdorf commented
> This means that some replicas could experience an error while applying this command while others don't. This would have to be something like a replicaCorruptionError (which means we'd need to make sure that mechanism really works, and figure out what it means to make it reversible).

No, then we're talking past each other. I'm saying that in addition to the usual check `lease at apply time == lease at propose time`, we additionally check that `lease at propose time == the leaseholder we wanted`, so this would be the same for all the replicas. Maybe we don't need this particular check but we need to pay attention that the node that runs the `AdminMerge` *is* actually the leaseholder (as you know our admin commands try to only run on the lease holder, but aren't particularly concerned with guaranteeing it). Without such a provision, we could lose the lease but still commit the merge and cause trouble that way, but I think your next suggestion nicely takes care of that.

> My incomplete suggestion for the latter is to use transaction deadlines:

I see where you're going with this, but I don't know how you would actually make it work. As you said, by the time the decision is made on whether the commit happens on `Q`, you can't guarantee that a lease change won't happen on `R`.

> When we start the merge transaction, we verify that Q and R are co-located, and we write an intent to the range descriptor which ensures that this can't change unless our transaction is aborted. So by the time any rebalancing can occur, we know the disposition of the merge transaction. If the merge succeeded, we shouldn't try to move the dead range R. If Q completes and immediately moves, everything should generally be fine. We just can't copy Q to a store that has a stale replica of R. Am I missing something here? I think the problems with the lease-timestamp proposal mainly have to do with out-of-date replicas instead of non-colocated ones.

See the Q-away example. The merge commits on `Q` (which means a majority have it in their logs and probably apply it pretty soon therafter). The majority now rebalances a replica (of  the new, wider `Q`) from the minority away, but that minority replica never actually got the merge before. That replica (of `Q`) never gets to see the merge in the future too, right? Everyone just stops talking to it when the conf change is proposed and it probably GCs itself really soon (or it's just down most of the time and comes back). You're left with a lone replica of `R` that can cause trouble. So yes, the replicas are colocated as the merge commits, but then immediately after things may shift around even though not all followers of `Q` know about it.

Morally, the way I like to think about my suggestion is to tag the range `R` with a flag that says "you can only get a lease and remove this flag if you've checked with the meta ranges that you're still a proper range and not merged away" (which also serves to serialize with the merge, if any). But we don't have to check the meta, we can check our local range descriptor (even though it may not belong to us any more after the merge, this happens to still work).

---

Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-:-L9kmSPR6k-bpY2JSFL0:bifb4sd)*
<!-- Sent from Reviewable.io -->

2018-04-18 21:33 UTC, benesch commented
Ok, I've updated this with an initial draft of the plan from our meeting. I wouldn't encourage reviewing before I've done one more content pass and an editing pass for your sake, but I'd certainly welcome the reviews!

---

Review status: 0 of 1 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 129 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9027GvBjSdCnsJe7N_:-L9HAWEH4QkcAcAy2RBA:b-3vmh0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d911d375da765f37913388ac8aea44448106397/docs/RFCS/20180330_range_merges.md#L129)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The root of my confusion is that `AdminMerge` runs on `Q`, the left range. Your description sounds like it wants `AdminMerge` to run on `R`, the right range.
</blockquote></details>

It doesn't care? Even though you started by looking at _R_, you end up with _Q_ and so you can call AdminMerge(_Q_).

---

*[docs/RFCS/20180330_range_merges.md, line 103 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9GfREe7kwlgJjNYoeu:-L9vbcis8cFJXXhrOaNR:bmjob1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L103)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

An alternative approach would be to make this a range local key and put it right next to the split point itself. This would allow the sticky bit to be more easily worked with since it would be addressable. It would also naturally force the key onto the right side of the manual split, which fits with the rest of the proposal here.
</blockquote></details>

Ack. I don't know enough about 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-:-L9sWtTVEEBwwGL4JHSo:bzeiqpy)*
<!-- Sent from Reviewable.io -->

2018-04-22 18:39 UTC, bdarnell commented
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 103 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-L9GfREe7kwlgJjNYoeu:-LAiI1ap2Rwh5m1oc5K0:b6wt557) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3a8658d6f63d789225b0f7ce4949ef74c66052/docs/RFCS/20180330_range_merges.md#L103)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

...the various types of keys to know what the tradeoffs are here.
</blockquote></details>

+1

We could do this with less plumbing if SPLIT AT wrote the (addressible range-local) sticky key first, then performed the split (the split itself could be oblivious to the sticky bit). However, then we'd have at least a temporary situation in which a sticky key would be written to the middle of an unsplit range. That's a bit odd (especially if the gateway handling the split crashes before finishing the job), but maybe we could have the GC queue notice these keys and either remove them or finish the split. 

---

*[docs/RFCS/20180330_range_merges.md, line 22 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiFWgHEvt3ON7QqwAz:-LAiFWgHEvt3ON7QqwB-:byshhjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L22)):*
> ```Markdown
> 
>   1. **User confusion.** Creating a table introduces new ranges, but dropping a
>      table does not remove its ranges. Adjusting the maximum range size
> ```

Note that there's a bit of follow-up work here: We'll be able to merge dropped tables down to a single range, but we don't be able to merge a dropped table away completely until we change SystemConfig.ComputeSplitKey to only split for tables that exist (instead of splitting for every id less than the max seen). 

---

*[docs/RFCS/20180330_range_merges.md, line 122 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiL-Yv36JXJkbeTrE1:-LAiL-Yv36JXJkbeTrE2:bwdbuul) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L122)):*
> ```Markdown
> 
> If the merge queue discovers no reasons to reject the merge, it sends a
> SuggestMergeRequest to range _Q_:
> ```

Do we need a new RPC or is this just AdminMerge? (with a new first step before the transaction starts to make sure that we really want to continue with the merge)

---

*[docs/RFCS/20180330_range_merges.md, line 163 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiN0Ii8LDqMJqRd6AH:-LAiN0Ii8LDqMJqRd6AI:btvulf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L163)):*
> ```Markdown
>    First the transaction updates _Q_'s local range descriptor to extend to _R_'s
>    end key. This ensures that the transaction record is located on _Q_, which
>    will be important later. (XXX: I've forgotten why this is important. Probably
> ```

It's important because we assume that committed transactions never leave behind unresolved intents on the range-local copy of the range descriptor. If we see an intent on the range descriptor, we know that the transaction is either pending or aborted and either way we should continue to use the pre-intent version. We have to create the transaction record here so that it can resolve its local intents synchronously. 

---

*[docs/RFCS/20180330_range_merges.md, line 195 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiPZVr66Q3lD5IqVNz:-LAiPZVs8vewJHbgQO0H:b3mciku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L195)):*
> ```Markdown
>    longer owns its user data. (XXX: how?)
> 
>    XXX: There are synchronization issues to work out here.
> ```

This may already be done. We have acquireSplitMergeLock and Store.MergeRange. I'm not sure if there are additional synchronization issues to work out here. 

---

*[docs/RFCS/20180330_range_merges.md, line 199 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiQsRc3gOur5_0lYlg:-LAiQsRc3gOur5_0lYlh:bczfp12) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L199)):*
> ```Markdown
>  4. **Replica garbage collection**
> 
>     Some time later, the replica garbage collection queue notices that _R_ has
> ```

It should be rare for this to happen via the replica GC queue. Normally we can clean it up immediately on applying the merge commit. The only time when it needs to reach the GC queue is if the node is down while the merge commits, then range Q is rebalanced off of the node. When it comes back up it will have a pre-split copy of Q (which can be GC'd in the usual way) as well as a copy of R. This can mostly be GC'd in the usual way, but when the queue does its consistent range descriptor lookup to determine whether the node is a current member of the range, it must consider "R no longer exists" as an outcome. 

---

*[docs/RFCS/20180330_range_merges.md, line 252 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiUQ2_65Ed8KCE9ix_:-LAiUQ2_65Ed8KCE9ixa:b-ciqmbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L252)):*
> ```Markdown
> leaseholder can derive whether IsMerging should be set by looking for an intent
> on its range descriptor. If this intent refers to an in-progress transaction,
> the new leaseholder sets the IsMerging flag on the replica. Note that this means
> ```

This has the surprising result that a new leaseholder may set IsMerging *before* it has handled a GetSnapshotForMerge. I don't think that would cause any actual problems (as long as GetSnapshotForMerge is able to bypass the IsMerging check), but it would be conceptually simpler if the flag were set as soon as the deletion intent were written. (I'm not sure it's worth inspecting all writes for this, though)

---

*[docs/RFCS/20180330_range_merges.md, line 260 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiaAoc-TzXm24VKuIA:-LAiaAoc-TzXm24VKuIB:bphz1iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L260)):*
> ```Markdown
> merge transaction has committed. When initializing its replicas, it will see an
> intent on _R_'s range descriptor. If the merge has committed, we want to be sure
> that... XXX actually, I'm confused again. What's the big deal if we instantiate
> ```

I think the only thing we need to do here is to try and push the transaction (going into the txnWaitQueue) if necessary to resolve that intent as quickly as possible. 

---

*[docs/RFCS/20180330_range_merges.md, line 266 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAibeCm2IaEbXlMV0co:-LAibeCm2IaEbXlMV0cp:bdmplau) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L266)):*
> ```Markdown
> 
> XXX: What happens if a range merges then immediately splits at exactly the same
> key? The stores are likely to be very confused.
> ```

This should be OK in theory since the second split can't start its transaction until the merge's intents are all resolved, and everything else happens synchronously in the commit triggers. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-23 15:12 UTC, bdarnell commented
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 163 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiN0Ii8LDqMJqRd6AH:-LAmwEUeBReB8jB65vl_:b-hsyn3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L163)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

> It's important because we assume that committed transactions never leave behind unresolved intents on the range-local copy of the range descriptor.

What is it exactly that goes wrong if we leave behind an intent for a committed txn?
</blockquote></details>

It's mainly a problem for splits: A rebooted Replica needs to know what its bounds are. If a split completed but the replica doesn't know about it, it would continue to incorrectly use the larger bounds (potentially stomping on the new RHS range) until it processed the intent resolution. It's less of a problem for merges since using the pre-merge bounds is the more conservative option.

Also, as a practical matter, we update the in-memory range descriptor when the transaction commits. If the transaction record were not local to the range, we'd need some sort of hook on intent resolution instead. 

---

*[docs/RFCS/20180330_range_merges.md, line 252 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394#-LAiUQ2_65Ed8KCE9ix_:-LAmxSCT-s6wMtvNFrtG:b413b8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0c669f7307f42c062b2c42d837bc60958ff7b5a/docs/RFCS/20180330_range_merges.md#L252)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Good point. Noted.

One other option: GetSnapshotForMerge could be responsible for deleting _R_'s
range descriptor? I think that would solve the race.
</blockquote></details>

I think we went back and forth on that in the meeting. IIRC, the argument for doing a Delete to write the intent followed by GetSnapshotForMerge (instead of a single command that does both) is that adding a new transactional KV op is not something we have much experience with and felt likely to have edge cases that we could avoid by making the new command independent of the transaction. I'm not completely convinced of this, though. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-27 23:27 UTC, benesch commented
The prototype is here but don't look too closely: 

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-:-LB8Q_6t1M317KwJhowv:bqfxh15)*
<!-- Sent from Reviewable.io -->

2018-04-28 04:40 UTC, benesch commented
Er, here: http://github.com/cockroachdb/cockroach/tree/merges

Also, I guess we already keep replica tombstones and generate `RaftGroupDeleted` errors if we see a message for a tombstoned range. How perfect!

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-:-LB9XwmT3KRmmRdlFCN5:b-ho9cin)*
<!-- Sent from Reviewable.io -->

2018-04-30 13:59 UTC, a-robinson commented
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LApZxG9Ex6UaUx3R0g6:-LApZxG9Ex6UaUx3R0g7:bqz7y7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L23)):*
> ```Markdown
>   1. **User confusion.** Creating a table introduces new ranges, but dropping a
>      table does not remove its ranges. Adjusting the maximum range size
>      downwards will split existing ranges where necessary, but adjusting it
> ```

s/it/minimum range size/

Which is actually a separate zone config field which we don't do much of anything with today, but presumably should if we're going to do size-based merging.

---

*[docs/RFCS/20180330_range_merges.md, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LBJHh2iDSoI8S-t_Hxo:-LBJHh2iDSoI8S-t_Hxp:b-jvyyzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L86)):*
> ```Markdown
> prototype. Please excuse the stream of conciousness in the meantime.
> 
> ### Merge queue
> ```

Is there a discussion somewhere about how the system will decide when it should merge ranges? If we can't decide that well enough to avoid merge/split thrashing, then the mechanism itself isn't very useful.

---

*[docs/RFCS/20180330_range_merges.md, line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LBD80Uh8JDznBP-mrCa:-LBD80Uh8JDznBP-mrCb:bpvnjnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L111)):*
> ```Markdown
> 
> So the merge queue will also reject a merge of _R_ into _Q_ if _R_'s sticky bit
> is set. The sticky bit can be cleared with an `ALTER TABLE ... MERGE AT`
> ```

s/MERGE AT/UNSPLIT AT/

---

*[docs/RFCS/20180330_range_merges.md, line 250 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LBJZZuc1lOH0Ga9bd5J:-LBJZZuc1lOH0Ga9bd5K:bf8rk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L250)):*
> ```Markdown
> on its range descriptor. If this intent refers to an in-progress transaction,
> the new leaseholder sets the IsMerging flag on the replica. Note that this means
> that after _every_ forced lease transfer the new leaseholder must check for an
> ```

By "forced lease transfer" do you just mean "lease acquisition"? "Transfer" typically refers to one replica voluntarily handing off its lease to another.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-30 14:02 UTC, a-robinson commented
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-04-30 22:25 UTC, bdarnell commented
> Actually, on second thought, wouldn't there be external intents on the meta2 records? Weird.

Yes, there would be non-local intents. But it's still possible for the meta2 intents to be resolved and the transaction record on Q to get cleaned up without a trace before R's wait command gets there. 

> In fact, perhaps just trying to transactionally read the meta2 range descriptor is sufficient? That request will just block, I think, until the merge transaction commits. Now that I think about it, maybe that's exactly what you all meant when you said "enter the transaction wait queue."

I hadn't quite thought it through in this much detail, but yeah, that would work (we need to make sure that the order of descriptor updates is [Q, meta2, R]). Read from Q.StartKey to R.EndKey in meta2: the read of Q will block until the transaction is done, and then the presence or absence of R's descriptor will tell you whether the merge succeeded or not (must be careful here of a merge immediately followed by a split - even if the bounds match the old Q and R, the merge could have completed and created R' with a new RangeID)

> Problem two is that I'm not sure how to indicate to followers that they should self-destruct. R's leader, one way or another, finds out that the merge transaction commits.

I was thinking that all the replicas would enter the transaction wait queue. This was assuming that this was triggered by a replicated command (like writing the delete intent to the range descriptor) instead of the read-only GetSnapshotForMerge. 

>  If this leader remembers just a little bit of state (a set of merged-away range IDs),

We already keep replica tombstones around forever, so we'd just need to make sure we don't erase them on merge. It feels a little dirty to me to rely on this although I guess this is already a fallback for cases where the follower was down when the merge committed and Q was replicated away, so it's better to rely on the existing mechanisms than something new.

2018-05-01 11:44 UTC, benesch commented
> Yes, there would be non-local intents. But it's still possible for the meta2 intents to be resolved and the transaction record on Q to get cleaned up without a trace before R's wait command gets there.

Good point. It turns out, though, that the merge tests don't split off meta2 ranges (duh!) so in a simple merge test where there exist only two ranges in the entire keyspace, the meta2 intents are necessarily local to the first range. Mystery solved.

> I hadn't quite thought it through in this much detail, but yeah, that would work (we need to make sure that the order of descriptor updates is [Q, meta2, R]). Read from Q.StartKey to R.EndKey in meta2: the read of Q will block until the transaction is done, and then the presence or absence of R's descriptor will tell you whether the merge succeeded or not (must be careful here of a merge immediately followed by a split - even if the bounds match the old Q and R, the merge could have completed and created R' with a new RangeID)

Yep, that's just about exactly what my prototype is doing.

> It feels a little dirty to me to rely on this although I guess this is already a fallback for cases where the follower was down when the merge committed and Q was replicated away, so it's better to rely on the existing mechanisms than something new.

Yeah, if we implement phase two and require replicas to be colocated, we'll no longer rely on this for the happy case. 

---

Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LBJHh2iDSoI8S-t_Hxo:-LBQU9R3C9jZJMUhr4pv:b-4aibe7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L86)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is there a discussion somewhere about how the system will decide when it should merge ranges? If we can't decide that well enough to avoid merge/split thrashing, then the mechanism itself isn't very useful.
</blockquote></details>

Only in my head, I think. I was actually planning on introducing the merge queue as described here to start. If it wouldn't be split, merge it! The thrashing will make for some useful chaos testing. Then we probably want some fudge factor that can be dialed up or down via a cluster setting. (E.g., only split/merge ranges that are more than 5% above/below the threshold.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-:-LBQSlJm-G0yCWB13fhp:b-he34n7)*
<!-- Sent from Reviewable.io -->

2018-05-01 13:43 UTC, a-robinson commented
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[docs/RFCS/20180330_range_merges.md, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LBJHh2iDSoI8S-t_Hxo:-LBQwOW3AnwhgEO15Duv:bgkni77) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L86)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Only in my head, I think. I was actually planning on introducing the merge queue as described here to start. If it wouldn't be split, merge it! The thrashing will make for some useful chaos testing. Then we probably want some fudge factor that can be dialed up or down via a cluster setting. (E.g., only split/merge ranges that are more than 5% above/below the threshold.)
</blockquote></details>

Give me a holler when you get around to that part of it :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394)*
<!-- Sent from Reviewable.io -->

2018-07-21 18:58 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180330_range_merges.md, line 214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/24394#-LHy9mRL2OzYF2rXvLNJ:-LHy9mRL2OzYF2rXvLNK:b-8hwcno) ([raw file](https://github.com/cockroachdb/cockroach/blob/db913f52d8f40beae6a587989b6b088d576437e8/docs/RFCS/20180330_range_merges.md#L214)):*
> ```Markdown
> magic that holds _R_ still for exactly the right amount of time.
> 
> To the command queue, GetSnapshotForMerge appears as a read that touches all
> ```

Doesn't it need to be declared as a *write* that touches all keys so that we prevent writes at higher timestamps?

Likewise, what happens to reads at lower timestamps? Are they still permitted to run concurrently with the GetSnapshotForMerge req? I don't see any issues with that, but we should clarify here.


<!-- Sent from Reviewable.io -->

2018-07-21 19:49 UTC, benesch commented
> Doesn't it need to be declared as a write that touches all keys so that we prevent writes at higher timestamps?

Yep. The code gets this right: https://github.com/cockroachdb/cockroach/blob/6a69ebdab7c4f10e0a0ad28de59207b066557973/pkg/storage/batcheval/cmd_get_snapshot_for_merge.go#L40-L57

> Likewise, what happens to reads at lower timestamps? Are they still permitted to run concurrently with the GetSnapshotForMerge req? I don't see any issues with that, but we should clarify here.

They are permitted provided they make it through the mergeCompleteCh before it closes. Hmm. I wonder if there are some clock offset problems to worry about here.

FYI I haven't updated this RFC in a long time and I wasn't planning to until the 2.1 freeze sets in. LMK if you think there's an area in particular that would benefit from more ahead-of-time discussion though.

2018-07-23 11:36 UTC, nvanbenschoten commented
> They are permitted provided they make it through the mergeCompleteCh before it closes. Hmm. I wonder if there are some clock offset problems to worry about here.

We shouldn't have to worry about clock offset since the merge entails direct communication between leaseholder nodes so the new leaseholder's HLC can't have a smaller time than the latest permitted read on the RHS. We do still need to bump the timestamp cache on the new leaseholder over the span of the old RHS though. Looks like there's a TODO for this. https://github.com/cockroachdb/cockroach/blob/54a811d075f9bf46de57a5de4ab40e523193e677/pkg/storage/store.go#L2396

> FYI I haven't updated this RFC in a long time and I wasn't planning to until the 2.1 freeze sets in. LMK if you think there's an area in particular that would benefit from more ahead-of-time discussion though.

No this is fine, no need to clean this up while you're still working on the code.

2019-01-08 00:59 UTC, petermattis commented
I'm fine with merging as-is.

2019-04-09 18:07 UTC, nvanbenschoten commented
Merging this as-is.

bors r+

2019-04-09 18:08 UTC, nvb approved these changes

2019-04-09 18:08 UTC, nvanbenschoten commented
bors r+

2019-04-09 19:11 UTC, nvanbenschoten commented
@benesch it looks like this is a CLA issue. Do you mind force pushing to kick off another CI run?

2019-04-10 20:27 UTC, benesch commented
Done, but I don't think it helped anything. Ugh.

2019-04-10 20:27 UTC, benesch commented
<img width="831" alt="image" src="https://user-images.githubusercontent.com/882976/55910928-dde33380-5bdf-11e9-8dcb-793a19462275.png">

🤦‍♂️

2019-04-10 20:28 UTC, benesch commented
please?

bors r+

2019-04-10 20:31 UTC, benesch commented
Well, CLA assistant still thinks this isn't signed, but Bors is running now. 🤔

2019-04-10 21:48 UTC, benesch commented
Welp, Bors noticed and crashed loudly, but now the CLA is signed, so ¯\_(ツ)_/¯ .

bors r+

2019-04-10 21:50 UTC, benesch commented
Bors crashed again.

bors r+

2019-04-10 22:16 UTC, merged