[wip] ui: upgrade React 15.4 => 16.3
cockroachdb/cockroach pull request #24616
Opened 2018-04-09 21:05 UTC by vilterp

Release note: None

2018-04-09 21:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/24616)
<!-- Reviewable:end -->

2018-04-10 15:16 UTC, couchand requested changes
kind of surprised this is all that's needed, but great!

2018-04-10 15:16 UTC, couchand commented on pkg/ui/package.json
> +    "react": "^16.3.1",
plz also update the `@types` for these

2018-04-10 15:16 UTC, couchand commented on pkg/ui/src/views/app/containers/timewindow/timewindow.spec.tsx
> +Enzyme.configure({ adapter: new Adapter() });
maybe put this config in a test helper?

2018-04-10 15:20 UTC, couchand commented
oh goodness, and a bunch of types incompatibilities 😱

2018-04-10 15:34 UTC, couchand commented
You're probably not seeing type issues cause `@types/react` and `@types/react-dom` are still out-of-date...

2018-04-10 15:36 UTC, couchand commented
Re: `react-sticky`, already have an open issue to get rid of it, I don't think we need it at all.  #19522

2018-04-10 22:33 UTC, vilterp commented
Ok, after a day of wrangling, I think I've gotten most of the `@types/` upgrades, and we're still at one peer dep issue (`react-sticky`); may attempt to rip it out per #19522.

2018-04-10 22:35 UTC, mrtracy commented
The change to Table specializations is LGTM

2018-04-11 19:11 UTC, couchand commented
When you squash can you also link the commit to #18795 please?

2018-04-12 16:59 UTC, vilterp commented on pkg/ui/package.json
> +    "react": "^16.3.1",
Done; think I got them all.

2018-04-12 17:45 UTC, couchand commented
looks great!  request from @josueeee: can you add some `padding: 12 0` to the config

2018-04-12 17:45 UTC, couchand approved these changes

2018-04-12 17:45 UTC, couchand commented on pkg/ui/src/views/app/containers/layout/index.tsx
> +    return (
+1 noticed this when adding the titles, meant to come back and do the reformat but forgot.  thanks!

2018-04-13 22:59 UTC, vilterp commented
Problems with `position: sticky`:
- thin grey line shows up under header whether we are scrolled down or not

Problems with `react-sticky`:
- current version has peer deps issue (depends on React 15)
- new version doesn't have typings

2018-04-16 19:14 UTC, vilterp commented
bors r+

2018-04-16 19:28 UTC, vilterp commented
bors r-

2018-04-16 19:29 UTC, vilterp commented
fixed nit

bors r+

2018-04-16 20:05 UTC, merged