[wip] workload: workload for interleaved table delete
cockroachdb/cockroach pull request #27060
Opened 2018-06-28 18:01 UTC by emsal1863

This is a new workload generator that is meant to test the performance
of operations on heavily interleaved tables. This workload creates one
parent table and five child tables interleaved with the parent, with a
configurable number of rows for each.

After creating the tables and
filling them up with rows, the generator then deletes the entries from
the parent table, causing a cascade.

Release note: None

2018-06-28 18:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27060)
<!-- Reviewable:end -->

2018-06-29 20:41 UTC, BramGruneir commented
To simulate a proper workload, we need 4 different possible operations for this workload

* Inserts - this should insert a session and at least one in each child table. (using the same ratios as the setup)
* Queries - This is a series of around 6 or 7 queries
* Updates - Similar to the queries operation, but also updates created with the current datetime.
* Deletes - Performs batches of cascading deletes (batch size is adjustable)

And for all of these workload, we should be able to specify which portion of the operations are for the east or west.

2018-07-02 13:20 UTC, emsal1863 commented
@BramGruneir is it necessary to be able to run any/all the operations in a single workload run or is are they supposed to be mutually exclusive?

2018-07-02 14:16 UTC, BramGruneir commented
It would be nice to be able to run each all the time.  In our testing, i expect we'll be running two instances that perform some inserts, queries and updates, and one solo one that performs deletes.  

I think the easiest way to do this is to set each to some percent out of 100.  If they add up to more than 100, just fail.

2018-07-06 15:54 UTC, BramGruneir commented
So you're still missing a few key things:

1) The setup of the localities.  Ideally these should be configurable as well.
2) Local vs Non-local.  We need to issue some percentage of statements locally (normally a very high percent if not 100%).  Just putting in east percent isn't enough.
3) Maybe setting the interval to delete, not sure if it's needed.
4) We're going to need to add some new update/retrieve queries that use the other child tables.  Maybe even one that joins everything together.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-:-LGkGdWaE8haAyZOK2Qy:bjkwhjt)*
<!-- Sent from Reviewable.io -->

2018-07-06 16:50 UTC, BramGruneir commented
Oh, and we have to setup the lease preferences as well.

---







*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-:-LGkUwuVDNXFLMhqRHLk:b-uqvzrg)*
<!-- Sent from Reviewable.io -->

2018-07-28 13:40 UTC, BramGruneir requested changes
Sorry about the delay in getting to this.

A number of updates are still needed I think, but nothing too onerous.

Also, we need to update the insert workload to be all within a single transaction (optionally).

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-:-LIW6C1S2YYdLnCRzyh9:bjea56a)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3CBn8snAAKmm15Ua:-LIW3CBn8snAAKmm15Ub:ba72brj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L38)):*
> ```Go
> 	zoneLocationsStmt = `
> UPSERT INTO system.locations VALUES
> 	('zone', 'us-east1-b', 33.0641249, -80.0433347),
> ```

This needs to be settable based on the three regions passed in via the command line.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3MBG51Eyk0nj1puI:-LIW3MBG51Eyk0nj1puJ:bywyply) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L100)):*
> ```Go
> 	insertQueryVariants   = `INSERT INTO variants(session_id, key, value, created, updated) VALUES ($1, $2, $3, now(), now())`
> 	insertQueryParameters = `INSERT INTO parameters(session_id, key, value, created, updated) VALUES ($1, $2, $3, now(), now())`
> 	insertQueryDevices    = `INSERT INTO devices(id, session_id, device_id, name, make, macaddress, model, serialno, created, updated) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())`
> ```

For longer lines, please use the backtick method to make these more readable.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3YFg9-KS0R0UdAVS:-LIW3YFg9-KS0R0UdAVT:b-igzrtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L187)):*
> ```Go
> WHERE session_id = $2
> `
> 	deleteSetSize = 100
> ```

Is this needed?  You've got a configurable param now.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3cFdAHHVd5z4COzn:-LIW3cFdAHHVd5z4COzo:b-ak5vuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L239)):*
> ```Go
> 		g.flags.Meta = map[string]workload.FlagMeta{
> 			`batch`: {RuntimeOnly: true},
> 		}
> ```

Please make the 3 regions configurable, and required to start the workload.  
Even being direct as setting `east=region1 west=region2 central=regrion3 local=east/west/central`

Then we need:
let's rename all params that are for setup only, to have a prefix of setup`setup-sessions`. .... hmm... that might be the only one.

Also, make sure that deletePercent, insertPercent, updatePercent, retrievePercent all add up to less than or equal to 100.
Set the defaults to -1 and add an explanation that we will set the default based on the local region unless these are set.

I'm thinking we can get rid of the finer grained insertLocalPercents, and just go with an overall Percents.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW5pjT7sGmsVnxUlJj:-LIW5pjT7sGmsVnxUlJk:b8fdkbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L675)):*
> ```Go
> func (w *interleavedPartitioned) generateSessionID(rng *rand.Rand, rowIdx int) string {
> 	sessionIDBase := randString(rng, 98)
> 	if (rowIdx % 100) >= w.eastPercent {
> ```

This would be better as a random number.  Why no reuse pickLocality?

I think you can complete remove this function actually.


<!-- Sent from Reviewable.io -->

2018-08-02 13:35 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3CBn8snAAKmm15Ua:-LIupYOH0cOFXPFq3tiE:b-1il898) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L38)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This needs to be settable based on the three regions passed in via the command line.
</blockquote></details>

Anything wrong with the hard coded geo coordinates?
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3YFg9-KS0R0UdAVS:-LIupv_93n0XLeI1HN5T:bxxzip2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L187)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is this needed?  You've got a configurable param now.
</blockquote></details>

To clarify: the way this is programmed is that `deleteSetSize` queries, each with `LIMIT w.deleteBatchSize`, execute on east, then on west, and alternates. I'll still change this to be configurable but it will involve introducing a new config parameter


<!-- Sent from Reviewable.io -->

2018-08-02 13:44 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW5pjT7sGmsVnxUlJj:-LIuqnEdDHMu405kcmRM:b-qm4jdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L675)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This would be better as a random number.  Why no reuse pickLocality?

I think you can complete remove this function actually.
</blockquote></details>

This one is for `init` while the other one is for actually running the workload. For `init`, initializing the child tables relies on this deterministic behaviour. 


<!-- Sent from Reviewable.io -->

2018-08-02 13:53 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3cFdAHHVd5z4COzn:-LIuuCw22jkeRqqo-RzU:b-slndpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L239)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please make the 3 regions configurable, and required to start the workload.  
Even being direct as setting `east=region1 west=region2 central=regrion3 local=east/west/central`

Then we need:
let's rename all params that are for setup only, to have a prefix of setup`setup-sessions`. .... hmm... that might be the only one.

Also, make sure that deletePercent, insertPercent, updatePercent, retrievePercent all add up to less than or equal to 100.
Set the defaults to -1 and add an explanation that we will set the default based on the local region unless these are set.

I'm thinking we can get rid of the finer grained insertLocalPercents, and just go with an overall Percents.
</blockquote></details>

There isn't any query in here that actually uses the name of the central region.

Adding up to 100 is done in the `Validate` function in the `Hooks`. 

Is this an error?


<!-- Sent from Reviewable.io -->

2018-08-02 14:08 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3CBn8snAAKmm15Ua:-LIux7gs5UMqLPIoWZyG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L38)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Anything wrong with the hard coded geo coordinates?
</blockquote></details>

Done
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3MBG51Eyk0nj1puI:-LIux8fpAyyBpOO7hB33:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

For longer lines, please use the backtick method to make these more readable.
</blockquote></details>

Done
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3YFg9-KS0R0UdAVS:-LIux9Ft7r7a900wI6hG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L187)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

To clarify: the way this is programmed is that `deleteSetSize` queries, each with `LIMIT w.deleteBatchSize`, execute on east, then on west, and alternates. I'll still change this to be configurable but it will involve introducing a new config parameter
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-08-02 15:15 UTC, BramGruneir requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvBxrx84cC-Y_DtfB5:-LIvBxrx84cC-Y_DtfB6:bvvrip1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/cmd/roachtest/interleavedpartitioned.go#L57)):*
> ```Go
> 
> 			// Just to initialize the database
> 			cmdInit := "./workload run interleavedpartitioned --init --east --sessions 0" +
> ```

don't call run, call init --drop to initialize the db.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvC8CH3xnntKaDMi3a:-LIvC8CH3xnntKaDMi3b:bvswtng) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/cmd/roachtest/interleavedpartitioned.go#L91)):*
> ```Go
> 
> 			cmdCentral := fmt.Sprintf(
> 				"./workload run interleavedpartitioned --insert-percent 0 --retrieve-percent 0 --update-percent 0  --delete-percent 100 --delete-set-size %d --rows-per-delete %d"+duration+histograms+" {pgurl:7-9}",
> ```

This should only be run on a single node in central.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3CBn8snAAKmm15Ua:-LIv9MFWAHNCPpdawXXq:b-ogtcu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L38)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Should probably make this 3, one for east, one for west and one for central, the geo coordinates themselves might as well be set to where gce is for east, west and central.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3cFdAHHVd5z4COzn:-LIvBhMPD6OeH7G1OycZ:b433cz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L239)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

There isn't any query in here that actually uses the name of the central region.

Adding up to 100 is done in the `Validate` function in the `Hooks`. 

Is this an error?
</blockquote></details>

Ah, that might work.  Might be worth testing it manually to be sure.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW5pjT7sGmsVnxUlJj:-LIvAq7Y7CqMCY_dYB8I:bnhyx6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L675)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

This one is for `init` while the other one is for actually running the workload. For `init`, initializing the child tables relies on this deterministic behaviour. 
</blockquote></details>

yes, but I don't think you need two of them.  You can achieve the same deterministic behaviour using a single function here.  
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIv9rDMCqU8zTzNHs8c:-LIv9rDMCqU8zTzNHs8d:b-e5czsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L241)):*
> ```Go
> 
> 	eastPercent          int
> 	east                 bool
> ```

Can't really use this now, since this might be on central where there is no action.  Set it to a string and validate that it is east/west/central
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvACOZD0TAZSOOUud-:-LIvACOZD0TAZSOOUud0:b-yn9i9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L282)):*
> ```Go
> 		g.flags.IntVar(&g.deletePercent, `delete-percent`, 50, `Percentage (0-100) of operations that are delete queries`)
> 		g.flags.IntVar(&g.rowsPerDelete, `rows-per-delete`, 20, `Number of rows per delete operation`)
> 		g.flags.IntVar(&g.deleteSetSize, `delete-set-size`, 100, `Number of delete queries for a particular zone before switching over`)
> ```

I think you can just always switch over.
This should really be run on a single node in central.
It should delete a batch on the east, then a batch on the west, and repeat.  
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvAmWU8gODP0yK0ai3:-LIvAmWU8gODP0yK0ai4:b-t5h6ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L287)):*
> ```Go
> 
> 		g.flags.StringVar(&g.eastZoneName, `east-zone-name`, `us-east1-b`, `name of the zone to be used as east`)
> 		g.flags.StringVar(&g.westZoneName, `west-zone-name`, `us-east1-b`, `name of the zone to be used as west`)
> ```

Not a good default here.


<!-- Sent from Reviewable.io -->

2018-08-02 17:35 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvBxrx84cC-Y_DtfB5:-LIvbFTs5wBcUCOyUCmq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/cmd/roachtest/interleavedpartitioned.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

don't call run, call init --drop to initialize the db.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvC8CH3xnntKaDMi3a:-LIvbGQt25lRL-5xBSXR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/cmd/roachtest/interleavedpartitioned.go#L91)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This should only be run on a single node in central.
</blockquote></details>

Done.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3cFdAHHVd5z4COzn:-LIvbJG60-uFE3RSoVUh:bnxr01r) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L239)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Ah, that might work.  Might be worth testing it manually to be sure.
</blockquote></details>

- did testing
- maybe there should just be one percent field called `localPercent` across all ops?
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIv9rDMCqU8zTzNHs8c:-LIvbQ0h359fmEcIEdQH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L241)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can't really use this now, since this might be on central where there is no action.  Set it to a string and validate that it is east/west/central
</blockquote></details>

Done.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvACOZD0TAZSOOUud-:-LIvbNky9lk1JxmjsSd5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L282)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think you can just always switch over.
This should really be run on a single node in central.
It should delete a batch on the east, then a batch on the west, and repeat.  
</blockquote></details>

Done.
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIvAmWU8gODP0yK0ai3:-LIvbOrwEJO9jH-STdVS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d812dfa08dee18d72423ae1727abb33d52811bc/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L287)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Not a good default here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-02 18:14 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3CBn8snAAKmm15Ua:-LIvq7He2ACdcmbISpBO:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L38)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Should probably make this 3, one for east, one for west and one for central, the geo coordinates themselves might as well be set to where gce is for east, west and central.
</blockquote></details>

Done
___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW5pjT7sGmsVnxUlJj:-LIvq8xFEyTAGYBJMfyC:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L675)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

yes, but I don't think you need two of them.  You can achieve the same deterministic behaviour using a single function here.  
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-08-02 18:58 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

This is looking good.  Please test it out to make sure it's working right and lets get it in!

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-:-LIw-GEv5R31SUXfGVLw:b-7rgmdk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-LIW3cFdAHHVd5z4COzn:-LIvzX85ES9CFhPVc_V0:b-lcsull) ([raw file](https://github.com/cockroachdb/cockroach/blob/fedbf7bf9b71e87e16419051f6bee0c047a6249b/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L239)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

- did testing
- maybe there should just be one percent field called `localPercent` across all ops?
</blockquote></details>

I like that simplification.


<!-- Sent from Reviewable.io -->

2018-08-03 15:42 UTC, BramGruneir approved these changes
The description is slight wrong, east and west run inserts, queries and updates.  

LGTM

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27060#-:-LJ-RuVF2S2BsqQTR2WD:b-omiblf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-03 15:58 UTC, emsal1863 commented
bors r+

2018-08-03 17:37 UTC, emsal1863 commented
bors r+

2018-08-03 17:55 UTC, merged