WIP: distsql: support window functions in distsql
cockroachdb/cockroach pull request #27140
Opened 2018-07-03 23:45 UTC by yuzefovich

Addresses: #24425.

This is true WIP, but I would appreciate any feedback that catches your eyes right away. Please, ignore two test files I added (I simply separated logic tests that currently pass from the rest).

Release note: None

2018-07-03 23:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27140)
<!-- Reviewable:end -->

2018-07-19 21:42 UTC, yuzefovich commented
Folks, it is finally ready for review! I plan on writing a doc outlining all the details of the current implementation shortly, so if something doesn't make sense, feel free to skip it for now, hopefully the doc will make that "something" clear.

2018-07-19 21:51 UTC, yuzefovich commented
@nvanbenschoten It'd be great if you could take a look at changes to `window.go` and `target.go`. I changed the behavior of reusing certain renders - namely, I don't want to allow for `IndexedVar`s and indices from `PARTITION BY` and `ORDER BY` clauses of window functions to refer to columns that are arguments to window functions (DistSQL version "consumes" those columns once corresponding window function is processed, so they are no longer available at the final stage).

2018-07-20 16:58 UTC, yuzefovich reviewed
I've done some benchmarks on 4 node roachprod cluster with TPCH dataset, and I see significant improvements in performance (at least for certain types of queries).

Comparison on **orders** table (1500000 rows)

| Query | Local | DistSQL | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY o_orderdate) FROM orders ORDER BY o_orderkey LIMIT 10;` | 4.710326731s | 3.771656567s | **-19.93%** |
| `SELECT sum(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 7.002787961s | 5.428136964s | **-22.49%** |
| `SELECT avg(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 18.721406889s | 11.428444414s | **-38.96%** |
| `SELECT avg(o_totalprice) OVER w, sum(o_custkey) OVER w FROM orders WINDOW w AS (PARTITION BY o_orderdate ORDER BY o_orderkey) ORDER BY o_orderkey LIMIT 10;` | 21.529759311s | 13.100725237s | **-39.15%** |
| `SELECT count(*) OVER w1, rank() OVER w2, avg(o_totalprice) OVER w1, sum(o_custkey) OVER w2, max(o_shippriority) OVER w2 FROM orders WINDOW w1 AS (PARTITION BY o_orderdate), w2 AS (PARTITION BY o_orderpriority ORDER BY o_orderkey) ORDER BY o_orderkey LIMIT 10;` | 28.727354088s | 23.996502202s | **-16.47%** |

Comparison on **lineitem** table (6001215 rows)

| Query | Local | DistSQL | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY l_shipdate) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 12.512830163s | 12.788312411s | **+2.20%** |
| `SELECT sum(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 30.373837678s | 15.364624232s | **-49.41%** |
| `SELECT avg(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 76.332633962s | 28.034687872s | **-63.27%** |
| `SELECT avg(l_quantity) OVER w, sum(l_linenumber) OVER w FROM lineitem WINDOW w AS (PARTITION BY l_receiptdate ORDER BY l_orderkey) ORDER BY l_orderkey LIMIT 10;` | OOM error | 30.529308856s | **-infinity%** |
| `SELECT row_number() OVER w1, sum(l_discount) OVER w2, last_value(l_comment) OVER w1, min(l_suppkey) OVER w2 FROM lineitem WINDOW w1 AS (PARTITION BY l_shipmode ORDER BY l_orderkey), w2 AS (PARTITION BY l_commitdate) ORDER BY l_orderkey LIMIT 10;` | OOM error | 35.888225934s | **-infinity%** |

2018-07-21 15:56 UTC, bladefist commented
It's very exciting this fixes the OOM errors, that was my primary issue as well. Great job.

2018-07-23 13:05 UTC, nvb submitted a review, later dismissed
Thanks for performing the local vs distributed comparison and recording the numbers. They look great!

> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LI6EU5HD6j66fpmlsly:bgujg69)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI5xv9wBNVhTE1UkRgt:-LI5xv9wBNVhTE1UkRgu:bkzm7yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2787)):*
> ```Go
> 
> type windowFuncsSorter struct {
> 	funcs []*windowFuncHolder
> ```

nit: it would be more idiomatic to define this as `type windowFuncsSorter []*windowFuncHolder`.
___
*[pkg/sql/distsql_physical_planner.go, line 2818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CadRAVBHaml_ymLK:-LI6CadRAVBHaml_ymLL:b-fdilrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2818)):*
> ```Go
> // above "windowing level". (See comment for replaceIndexVarsAndAggFuncs method
> // of windowNode for context.)
> func (dsp *DistSQLPlanner) createPlanForWindow(
> ```

This is a pretty huge method. Think it's worth splitting up?
___
*[pkg/sql/distsql_physical_planner.go, line 2826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI69smI8fegbpo3kLmS:-LI69smI8fegbpo3kLmT:b-mktte2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2826)):*
> ```Go
> 	}
> 
> 	// Sort window functions by their ardIdxStart.
> ```

argIdxStart
___
*[pkg/sql/distsql_physical_planner.go, line 2835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6AOb06Dwq83FVv0-m:-LI6AOb06Dwq83FVv0-n:b-y84yzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2835)):*
> ```Go
> 	for numWindowFuncProcessed < len(n.funcs) {
> 		notProcessedIdx := -1
> 		for funcIdx := 0; funcIdx < len(n.funcs); funcIdx++ {
> ```

Can we avoid this quadratic behavior? The whole approach of maintaining the `isWindowFuncProcessed` slice seems strange to me. Maybe I'm missing why it's necessary.
___
*[pkg/sql/window.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CygP0SwQ9mfXShJt:-LI6CygP0SwQ9mfXShJu:buiucwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/window.go#L59)):*
> ```Go
> 	// as arguments to window functions plus (possibly) some columns that are simply
> 	// being passed through windowNode (i.e. with no window functions). We do not
> 	// want to reuse these renders because they might be"consumed" by DistSQL
> ```

be"consumed" - missing space.

What does it mean for a render to be consumed by DistSQL? What are the implications here?


<!-- Sent from Reviewable.io -->

2018-07-23 21:12 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CadRAVBHaml_ymLK:-LI7lrQO1atnuT11dSpC:b-cq9jtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2818)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a pretty huge method. Think it's worth splitting up?
</blockquote></details>

I'm not sure - some methods in this file are of comparable length, but I agree that the method is big. I'm curious to learn what folks who have touched this file before think.
___
*[pkg/sql/distsql_physical_planner.go, line 2826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI69smI8fegbpo3kLmS:-LI7mv0ZC3mQbscl7cQp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2826)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

argIdxStart
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2835 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6AOb06Dwq83FVv0-m:-LI7n4Gn5ogf6XA80jYZ:b-69xapd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2835)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we avoid this quadratic behavior? The whole approach of maintaining the `isWindowFuncProcessed` slice seems strange to me. Maybe I'm missing why it's necessary.
</blockquote></details>

I think we could avoid quadratic behavior in this case, but this quadratic is like a drop in the ocean - in comparison to other work being done in the outer loop, the inner loop should be taking a tiniest fraction of all the time (and in comparison to computing window functions themselves, the inner loop is almost literally nothing). So I'd argue it is not worth the effort to look deeper in it.

I'm maintaining `isWindowFuncProcessed` as an optimization. Namely, I shift indices of PARTITION BY/ORDER BY clauses only of unprocessed functions (shifting these indices for already processed ones has no effect because we have set up the corresponding windowers).
___
*[pkg/sql/window.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CygP0SwQ9mfXShJt:-LI7q1405kV3_mFGKTcx:bsnodc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/window.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

be"consumed" - missing space.

What does it mean for a render to be consumed by DistSQL? What are the implications here?
</blockquote></details>

Quick summary of how a windower processes its window functions: it puts the output of a window function as the `windowFn.argIdxStart`th column of the processor output and does not output columns-arguments at all, so by "consuming" the columns I mean that those columns are not being outputted. If reused render "points" to an argument column to some window function, after processing that window function the render will be pointing to some garbage because the initial column is no longer there.

The consequence of this change is that rows in `wrappedRenderVals` will likely to become longer (with more datums) which corresponds to increased memory usage (which is not necessary for the local execution currently). The reasoning behind such decision is that we don't want to pass around the full initial row between `windower` processors of different stage (the approach with keeping around only columns that are referenced by some `IndexedVar`s, I think, is very prone to bugs). I will extract changes related to renders in a separate PR since build fails because of them, and we can continue our discussion there.


<!-- Sent from Reviewable.io -->

2018-07-25 14:30 UTC, jordanlewis requested changes
Did a first pass. Mostly didn't review the physical planner code yet. Very nice work so far. The performance improvements look great, and I think we can probably make them even better. A couple of high level comments:

I think you should change the windower to operate on EncDatums and EncDatumRows directly instead of Datums. Currently, I believe the work that the processor does to convert back and forth between the two representations (and most importantly, to make different memory allocations to hold the two representations) is unnecessary. It may help to talk in person about this.

Also, you should add some tests to a new file, `pkg/sql/logictest/testdata/planner_test/distsql_window`, that generate some EXPLAIN(DISTSQL) plans and verify that they're a certain way. There are other examples of this kind of test in that direction. These will function as unit tests for the distsql_physical_planner code you added, which would otherwise be only indirectly tested.

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIGk_ux568tL75XSuFx:b-rwg4ot)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CadRAVBHaml_ymLK:-LIGq0wq6w2LX2jnC9xw:bggyhzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2818)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm not sure - some methods in this file are of comparable length, but I agree that the method is big. I'm curious to learn what folks who have touched this file before think.
</blockquote></details>

I would say that splitting it up at least a little bit could be useful just for comprehension's sake. I would also consider adding comments above all of the main "legs of the journey" so to speak to make it more obvious what the different phases of computation do.
___
*[pkg/sql/distsql_physical_planner.go, line 2249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGj6AC2iCi-R9-NuI6:-LIGj6AD9aDC2JF6WnD1:bjr96kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2249)):*
> ```Go
> 		plan, err = dsp.createPlanForWindow(planCtx, n)
> 		// TODO(yuzefovich): figure out how to propagate the error correctly.
> 		if err != nil {
> ```

I think you should follow the example of the other cases and just set plan and err. The code below will propagate the error correctly.
___
*[pkg/sql/distsql_physical_planner.go, line 2795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGl2l2BXfVILWmxyBK:-LIGl2l2BXfVILWmxyBL:btt39wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2795)):*
> ```Go
> 
> // createPlanForWindow creates a physical plan for computing window functions.
> // We add new stage of windower processors for each different partitioning found
> ```

nit: We add *a* new stage of..
___
*[pkg/sql/distsql_physical_planner.go, line 2796 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGl7NS5eP4KrXG40q6:-LIGl7NS5eP4KrXG40q7:ba4c55z) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2796)):*
> ```Go
> // createPlanForWindow creates a physical plan for computing window functions.
> // We add new stage of windower processors for each different partitioning found
> // in window functions.
> ```

perhaps: in the query's window functions.
___
*[pkg/sql/distsqlrun/processors.proto, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjY5qE55qKZJtxn38:-LIGjY5qE55qKZJtxn39:b-d6d6br) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L832)):*
> ```protobuf
> // argument, (windowFn.ArgCount - 1) columns are removed.
> message WindowerSpec {
>   enum Func {
> ```

I would consider reusing the AggregatorSpec's Func enum so that these two won't get out of sync if someone needs to add a new aggregation function.
___
*[pkg/sql/distsqlrun/processors.proto, line 883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjlwkB63xwfMpcSCa:-LIGjlwkB63xwfMpcSCb:b-qwfj45) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L883)):*
> ```protobuf
>     // BoundType indicates which type of boundary is used.
>     enum BoundType {
>       UNBOUNDED_PRECEDING = 0; // represents UNBOUNDED PRECEDING type of boundary
> ```

nit: align the // comments to the same column so it's easier to read.
___
*[pkg/sql/distsqlrun/processors.proto, line 893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjr7BCLcFXQoWNWAo:-LIGjr7BCLcFXQoWNWAp:b-pdcjf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L893)):*
> ```protobuf
>     message Bound {
>       optional BoundType boundType = 1 [(gogoproto.nullable) = false];
> ```

nit: get rid of the extra newlines between these messages here and below. If they have no comments, it's just noisy to have extra newlines.
___
*[pkg/sql/distsqlrun/windower.go, line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGn94O8d3JkNHdlzqi:-LIGn94O8d3JkNHdlzqj:biwfg9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L257)):*
> ```Go
> 		if meta != nil {
> 			if meta.Err != nil {
> 				w.moveToDraining(nil /* err */)
> ```

I think you should pass `meta.Err` here instead of nil.
___
*[pkg/sql/distsqlrun/windower.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGouHb75mWuclO-O4F:-LIGouHb75mWuclO-O4G:b-16vpc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L303)):*
> ```Go
> 		for _, encRow := range encodedPartition {
> 			// Set up Idx of IndexedRow as row's index among all rows of all partitions.
> 			partition = append(partition, tree.IndexedRow{Idx: rowIdx, Row: w.decodeRow(encRow)})
> ```

I'm confused why this is necessary - it's better to keep the row around as an EncDatumRow rather than having to allocate new memory to capture the EncDatum's underlying Datums to. You can ensure that the EncDatumRow is fully decoded without having to make a new slice for it.
___
*[pkg/sql/distsqlrun/windower.go, line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGnqyv0bCJPxpSB88s:-LIGnqywB-Ov0jdtseZS:b-mhti0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L327)):*
> ```Go
> // encodeRow encodes given row.
> func (w *windower) encodeRow(row tree.Datums) sqlbase.EncDatumRow {
> 	encRow := make(sqlbase.EncDatumRow, len(row))
> ```

You can avoid this allocation - have the windower store a `sqlbase.EncDatumRow` of the proper length and simply write into it when you need to encode. The semantics of DistSQL should ensure that returning an "unsafe" row like this is safe - downstream row consumers always make a copy if they need to hold onto a row past the next time that they'll invoke your Next function.

This should be a decent win - allocating an extra row per Next is pretty expensive.
___
*[pkg/sql/logictest/testdata/planner_test/window, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGkEX97YTmHCamZdtu:-LIGkEX97YTmHCamZdtv:b-4uqi53) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/logictest/testdata/planner_test/window#L1)):*
> [...]

2018-07-25 15:55 UTC, asubiotto submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGj6AC2iCi-R9-NuI6:-LIGqvMZA7ZOf6Ew2ybX:b45scf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2249)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you should follow the example of the other cases and just set plan and err. The code below will propagate the error correctly.
</blockquote></details>

+1 However, `shouldPlanTestMetadata` ignores the error so you should probably have an `err != nil` check before that block.
___
*[pkg/sql/distsqlrun/windower.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGsiOcBQSUutuhSx-6:-LIGsiOcBQSUutuhSx-7:b-fkkchb) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L116)):*
> ```Go
> 	outputTypes  []sqlbase.ColumnType
> 	datumAlloc   sqlbase.DatumAlloc
> 	rowAlloc     sqlbase.EncDatumRowAlloc
> ```

This makes me think you should probably add a memory monitor and track allocations.
___
*[pkg/sql/distsqlrun/windower.go, line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGn94O8d3JkNHdlzqi:-LIGrqu_Dstll4TcTxHx:btyjm7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L257)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you should pass `meta.Err` here instead of nil.
</blockquote></details>

I think this is fine, we do this everywhere else since we want to send the whole meta (below) rather than just the err.
___
*[pkg/sql/distsqlrun/windower.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGwQsyDtM9zkelq5ET:-LIGwQszEekXVWA--vGW:bqjdolp) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L264)):*
> ```Go
> 		if row == nil {
> 			log.VEvent(w.ctx, 1, "accumulation complete")
> 			w.inputDone = true
> ```

Is `inputDone` necessary?
___
*[pkg/sql/distsqlrun/windower.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGymFw7RqnsEHTCrG0:-LIGymFw7RqnsEHTCrG1:b-ql5usa) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L281)):*
> ```Go
> 				w.scratch, err = row[int(col)].Encode(&w.inputTypes[int(col)], &w.datumAlloc, preferredEncoding, w.scratch)
> 				if err != nil {
> 					panic(fmt.Sprintf("unexpected error while encoding: %v", err))
> ```

I would return an error here instead of panicing.
___
*[pkg/sql/distsqlrun/windower.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGzC1X2kzJWsqjdelk:-LIGzC1X2kzJWsqjdell:bbeppch) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L285)):*
> ```Go
> 			}
> 
> 			bucket := int(crc32.Update(0, crc32Table, w.scratch))
> ```

When keying by encoded columns we usually use a `map[string]row` (e.g. `hashJoiner` or `distinct`)


<!-- Sent from Reviewable.io -->

2018-07-28 23:51 UTC, yuzefovich reviewed
Indeed, after all the suggestions, the performance improvement is even better - I've done a few benchmarks, and additional improvements over what I had in the first iteration of this PR is in double digits!

I added `planner_test/distsql_window` with a few tests, but I'm not sure how many of them are necessary. Please let me know if I should include additional tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIYBr3-CI4uOays-GPT:b-3a0wsz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LI6CadRAVBHaml_ymLK:-LIY27KT0dkQWSz2JDpC:bceumui) ([raw file](https://github.com/cockroachdb/cockroach/blob/5706a62e5a5cdbbf0ce004ef6a5a4bf0ed1d0b23/pkg/sql/distsql_physical_planner.go#L2818)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would say that splitting it up at least a little bit could be useful just for comprehension's sake. I would also consider adding comments above all of the main "legs of the journey" so to speak to make it more obvious what the different phases of computation do.
</blockquote></details>

I extracted a few methods out of the main planning code and added  some additional comments to describe what's happening. Please let me know whether (and how) I should refactor it further.
___
*[pkg/sql/distsql_physical_planner.go, line 2249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGj6AC2iCi-R9-NuI6:-LIIBGhKAKVBe-Bm_G96:b-5vhb20) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2249)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

+1 However, `shouldPlanTestMetadata` ignores the error so you should probably have an `err != nil` check before that block.
</blockquote></details>

Thanks for suggestions.
___
*[pkg/sql/distsql_physical_planner.go, line 2795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGl2l2BXfVILWmxyBK:-LIHi7aW4yxsWAS-0Gh7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2795)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: We add *a* new stage of..
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2796 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGl7NS5eP4KrXG40q6:-LIHiDVx0_iIeYyeWGwQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsql_physical_planner.go#L2796)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

perhaps: in the query's window functions.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/processors.proto, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjY5qE55qKZJtxn38:-LIHR3BC7UpIVXxRpSUT:bxpian0) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L832)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would consider reusing the AggregatorSpec's Func enum so that these two won't get out of sync if someone needs to add a new aggregation function.
</blockquote></details>

Done. Good idea, I thought about it at some point but didn't see how to do it. Please let me know if the way I've just done it is not the best.
___
*[pkg/sql/distsqlrun/processors.proto, line 883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjlwkB63xwfMpcSCa:-LIGy6c6EaEXPmh6pvHS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L883)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: align the // comments to the same column so it's easier to read.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/processors.proto, line 893 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGjr7BCLcFXQoWNWAo:-LIGy5TTAHlvuldUKhLw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/processors.proto#L893)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: get rid of the extra newlines between these messages here and below. If they have no comments, it's just noisy to have extra newlines.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGsiOcBQSUutuhSx-6:-LIHRI6c6LD6XC69r5_r:b-b0zvpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L116)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This makes me think you should probably add a memory monitor and track allocations.
</blockquote></details>

Great idea. I plan to add memory accounting and stats collection/display in the follow-up PR. I already have it in a separate branch.
___
*[pkg/sql/distsqlrun/windower.go, line 257 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGn94O8d3JkNHdlzqi:-LIGxFoz4czlDqayr515:b12estx) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this is fine, we do this everywhere else since we want to send the whole meta (below) rather than just the err.
</blockquote></details>

I copied the behavior from https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/aggregator.go#L440. I think I'll stick with `nil` as Alfonso suggests.
___
*[pkg/sql/distsqlrun/windower.go, line 264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGwQsyDtM9zkelq5ET:-LIHU6Xy-7LcT5vvG4Vd:brc7jjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L264)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is `inputDone` necessary?
</blockquote></details>

I think yes. The expected behavior of the processor is to first accumulate all rows and only after that to be able to emit rows. I use `inputDone` as a flag showing that emitting rows is "safe" - i.e. produces correct output. If `inputDone` is `false`, but `emitRow` is called, I move the processor to draining (which I've just added while pondering your question).
___
*[pkg/sql/distsqlrun/windower.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGymFw7RqnsEHTCrG0:-LIHV52L3R620Lp1Xe44:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L281)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would return an error here instead of panicing.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIGzC1X2kzJWsqjdelk:-LIHhrtYAZEk394v_tXu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55dd1c94bd57afa7dd978af32f7bfab989cfc2fc/pkg/sql/distsqlrun/windower.go#L285)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

When keying by encoded columns we usually use a `map[string]row` (e.g. `hashJoiner` or `distinct`)
</blockquote></details>

Done.
___
*[pkg/s [...]

2018-07-28 23:56 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 462 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIYJ8Ul8HxrfULJbMh1:-LIYJ8Ul8HxrfULJbMh2:by8sju3) ([raw file](https://github.com/cockroachdb/cockroach/blob/946f01e4b93e632947c1993314e2d02fc7490988/pkg/sql/distsqlrun/windower.go#L462)):*
> ```Go
> 							sortedPartitionsCache[windowFnIdx] = make([]indexedRows, len(partitions))
> 						}
> 						sortedPartitionsCache[windowFnIdx][partitionIdx] = partition.makeCopy()
> ```

I couldn't figure out how to avoid making this extra allocation. Simply assigning `partition` was not enough since later calls to `sort.Sort` would have resorted already cached partitions. Probbly I'm missing something.


<!-- Sent from Reviewable.io -->

2018-07-30 14:28 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIf_O4hEcTf3VEiTREE:-LIf_O4hEcTf3VEiTREF:b-ajio0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L744)):*
> ```Go
> type indexedRow struct {
> 	idx int
> 	row sqlbase.EncDatumRow
> ```

I wonder whether this should be a pointer. If I'm not mistaken, currently a copy of `EncDatumRow` is made when initializing `indexedRow`; however, windowers will not modify underlying encoded rows, so we can safely store a pointer to original row.


<!-- Sent from Reviewable.io -->

2018-07-31 11:58 UTC, RaduBerinde reviewed
This is complicated stuff, very nice job!

I like the one stage per partitioning architecture, it works out nicely.

I looked over the protos and the planning code. Mostly minor comments and suggestions for improving readability. I will take another look at the planning code in more detail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIk5DMzADACy0-Jx6_F:bu3fcgi)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2802 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk7cW91isByFsP7Smw:-LIk7cW91isByFsP7Smx:b-jolzcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2802)):*
> ```Go
> }
> 
> // findUnprocessedWindowFnsWithSamePartition loops through all window functions
> ```

[nit] It's good to separate out the high level from the details, and put the details inside the function. All the caller should really care about is that it identifies a set of unprocessed window functions that use the same partitioning and updates `isWindowFunc` accordingly, right?
___
*[pkg/sql/distsql_physical_planner.go, line 2814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6Pfx7Hk8pP5hH1jn:-LIk6Pfx7Hk8pP5hH1jo:b9slw0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2814)):*
> ```Go
> //
> // This function returns columns from PARTITION BY clause that all window functions
> // in samePartitionFuncsIdx share along with indices of those functions in n.funcs
> ```

samePartitionFuncsIdx is an internal variable, it doesn't help to use it to describe what the function does
___
*[pkg/sql/distsql_physical_planner.go, line 2820 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6m5OBNWdWyd8TRof:-LIk6m5OBNWdWyd8TRog:b-rhqr25) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2820)):*
> ```Go
> 	isWindowFuncProcessed []bool,
> 	windowFuncOutputColumnIdx map[*windowFuncHolder]int,
> ) ([]uint32, []int) {
> ```

Give names to the return values so it's clear what they are. This is good practice whenever it's not evident.

Wouldn't the code be simpler if this returned`[]*windowFuncHolder` instead of indices? I couldn't see a place where we actually care about the indices themselves, other than to access the holder.

Similarly, it would probably be easier if instead of `isWindowFuncProcessed` we would maintain a slice of unprocessed holders.
___
*[pkg/sql/distsql_physical_planner.go, line 2841 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk8nby3DuPqP7y4jEl:-LIk8nby3DuPqP7y4jEm:brjogee) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2841)):*
> ```Go
> 	samePartitionFuncsIdx = append(samePartitionFuncsIdx, notProcessedIdx)
> 	isWindowFuncProcessed[notProcessedIdx] = true
> 	windowFuncOutputColumnIdx[windowFnToProcess] = windowFnToProcess.argIdxStart
> ```

I would leave the updating of `windowFuncOutputColumnIdx` outside this function. It should be trivial to update it using the results of the function, and it's easier to document that way.

Or, given that there are other functions using the same set of arguments, another option would be to define a struct containing `windowFns, isWindowFuncProcessed, windowFuncOutputColumnIdx` (mabe mroe, documenting them in the struct) and having this and `adjustColumnIndices` be methods on that struct. That way you don't have to look inside some other function to figure out what the argument means (or have it explained multiple times).
___
*[pkg/sql/distsql_physical_planner.go, line 2884 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIkBTfE2ApsK7lYZvx5:-LIkBTfE2ApsK7lYZvx6:b-thpc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2884)):*
> ```Go
> 			// 1. both f1 and f2 are in samePartitionFuncsIdx:
> 			// a) f1.argCount == 0
> 			// - handled correctly because we'll insert a new column
> ```

[nit] indent everything under `1.`, and again after `a)` so it's more readable. Also try to maintain consistent line-wrapping (80 columns), some lines look much shorter and it's harder to read.
___
*[pkg/sql/distsql_physical_planner.go, line 2943 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk2_fG4yhjssfG-KFd:-LIk2_fG4yhjssfG-KFe:bl6hxfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2943)):*
> ```Go
> // found in the query's window functions.
> //
> // The result of a window function computation is put at windowFn.argIdxStart index,
> ```

Starting here, this should be inside the function.
___
*[pkg/sql/distsql_physical_planner.go, line 2974 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk1pIKBr1r0kzRJy0t:-LIk1pIKBr1r0kzRJy0u:b-hykjba) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2974)):*
> ```Go
> 	isWindowFuncProcessed, numWindowFuncProcessed := make([]bool, len(n.funcs)), 0
> 
> 	for numWindowFuncProcessed < len(n.funcs) {
> ```

Given that there's a lot of code in this loop, it would be good to have a comment above the loop with a high level description of what we're doing (maybe as a numbered list of steps). It should be clear from the comment how the stages are being determined.
___
*[pkg/sql/distsql_physical_planner.go, line 2989 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk2MF65PQDSaH6EsDZ:-LIk2MF65PQDSaH6EsD_:bscz0xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2989)):*
> ```Go
> 		}
> 
> 		// Populating output types of this stage since windowers
> ```

Expand this comment (maybe include an example).
___
*[pkg/sql/distsql_physical_planner.go, line 3002 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk0AAk8ZkuB3LgasTF:-LIk0AAk8ZkuB3LgasTG:b-fs0xe1) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L3002)):*
> ```Go
> 			// The function might be an aggregate, so let's try looking up
> 			// corresponding aggregate function.
> 			builtinIdx, ok := distsqlrun.AggregatorSpec_Func_value[funcStr]
> ```

[nit] this branching could be consolidated so the logic is easier to follow
```go
if aggBuiltin, ok := distsqrun.AggregatorSpec_Func_value[funcStr]; ok {
  funcSpec.WindowFunc = ...
} else if winBuiltin, ok := ...; ok {
  ...
} else {
  return error
}
```

This could also be in a separate function so the main function is easier to read.
___
*[pkg/sql/distsql_physical_planner.go, line 3027 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk123M7XR_Xn_HoQ34:-LIk123M7XR_Xn_HoQ35:b-muqs3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L3027)):*
> ```Go
> 			newResultTypes = append(newResultTypes, plan.ResultTypes[inputColIdx:windowFn.argIdxStart]...)
> 
> 			// TODO: should we panic? This condition indicates a problem in
> ```

It's always preferable to error in these cases. Even if the error indicates a bug, it might only show up with a certain query, we shouldn't take down the entire server because of it.
___
*[pkg/sql/distsql_physical_planner.go, line 3032 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk57Fs5CTwaH_5aOMT:-LIk57Fs5CTwaH_5aOMU:b-p19l02) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L3032)) [...]

2018-07-31 20:48 UTC, yuzefovich reviewed
Yeah, window functions are pretty complicated, and the code I produced so far is complicated as well, hopefully you guys will have more suggestions on how to make it more comprehensible (I've been reading through this so much that I cannot see that myself :/ ).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIlyltLEa7xRfVgqwyB:b-hkwixf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2802 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk7cW91isByFsP7Smw:-LIkqEEK6mI3zoBj2Xz1:b-mm6tze) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2802)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It's good to separate out the high level from the details, and put the details inside the function. All the caller should really care about is that it identifies a set of unprocessed window functions that use the same partitioning and updates `isWindowFunc` accordingly, right?
</blockquote></details>

Right, good point.
___
*[pkg/sql/distsql_physical_planner.go, line 2814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6Pfx7Hk8pP5hH1jn:-LIkhut9A_DR0Nceyxmz:b6vjbwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2814)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

samePartitionFuncsIdx is an internal variable, it doesn't help to use it to describe what the function does
</blockquote></details>

Agreed. I rewrote the comment, but, in general, is it reasonable to use names of return values in the comment to the function?
___
*[pkg/sql/distsql_physical_planner.go, line 2820 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6m5OBNWdWyd8TRof:-LIkieaZCW8wuMGpW4W0:baxiib5) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2820)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Give names to the return values so it's clear what they are. This is good practice whenever it's not evident.

Wouldn't the code be simpler if this returned`[]*windowFuncHolder` instead of indices? I couldn't see a place where we actually care about the indices themselves, other than to access the holder.

Similarly, it would probably be easier if instead of `isWindowFuncProcessed` we would maintain a slice of unprocessed holders.
</blockquote></details>

I also use `isWindowFuncProcessed` to distinguish how to update the indices in `adjustColumnIndices` - if `isWindowFuncProcessed[f] == true`, then I'm updating `windowFuncOutputColumnIdx[f]`; if it is `false`, then I'm updating `f.argIdxStart`. If I were to switch to slice of unprocessed holders, I would need to go through the slice to figure out how to update an index for a particular `f`, that would be quadratic behavior. I don't think performance difference here is important, so please let me know if you still think that I should change my approach with `isWindowFuncProcessed` as a map from `windowFuncHolder` to `bool` (which I've introduced after your comments).
___
*[pkg/sql/distsql_physical_planner.go, line 2841 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk8nby3DuPqP7y4jEl:-LIkwaNN-sCchrlNXm6J:b-n5jcmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2841)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would leave the updating of `windowFuncOutputColumnIdx` outside this function. It should be trivial to update it using the results of the function, and it's easier to document that way.

Or, given that there are other functions using the same set of arguments, another option would be to define a struct containing `windowFns, isWindowFuncProcessed, windowFuncOutputColumnIdx` (mabe mroe, documenting them in the struct) and having this and `adjustColumnIndices` be methods on that struct. That way you don't have to look inside some other function to figure out what the argument means (or have it explained multiple times).
</blockquote></details>

I moved it outside of the function. Indeed, it looks a lot better now.
___
*[pkg/sql/distsql_physical_planner.go, line 2884 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIkBTfE2ApsK7lYZvx5:-LIklCSk9T9be4CsN6ON:b-1gcela) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2884)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] indent everything under `1.`, and again after `a)` so it's more readable. Also try to maintain consistent line-wrapping (80 columns), some lines look much shorter and it's harder to read.
</blockquote></details>

Will do my best.
___
*[pkg/sql/distsql_physical_planner.go, line 2974 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk1pIKBr1r0kzRJy0t:-LIlwa0c4vVJyn1Y4j6M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2974)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Given that there's a lot of code in this loop, it would be good to have a comment above the loop with a high level description of what we're doing (maybe as a numbered list of steps). It should be clear from the comment how the stages are being determined.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2989 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk2MF65PQDSaH6EsDZ:-LIlyDvEDUBAOlMdZZM5:b88bbed) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2989)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Expand this comment (maybe include an example).
</blockquote></details>

Included an example. Please let me know if a more complex example would be beneficial (for example, with window functions with different partitioning).
___
*[pkg/sql/distsql_physical_planner.go, line 3002 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk0AAk8ZkuB3LgasTF:-LIljAJnBPtqNYvL0sqT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L3002)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this branching could be consolidated so the logic is easier to follow
```go
if aggBuiltin, ok := distsqrun.AggregatorSpec_Func_value[funcStr]; ok {
  funcSpec.WindowFunc = ...
} else if winBuiltin, ok := ...; ok {
  ...
} else {
  return error
}
```

This could also be in a separate function so the main function is easier to read.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 3027 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk123M7XR_Xn_HoQ34:-LIkzzta1zfSgTM_kPGB:b-raow4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L3027)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's always preferable to error in these cases. Even if the error indicates a bug, it might only show up with a certain query, we shouldn't take down the entire server because of it.
</blockquote></details>

Makes sense, thank you. I wonder whether I should change all `panic`s I added into errors.
___
*[pkg/sql/distsql_physical_planner.go, line 3032 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk57Fs5CTwaH_5aOMT:-LIlyQ7I4nrfPTC0XttA:b-896fix) ( [...]

2018-08-02 11:30 UTC, RaduBerinde commented
___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LIuORwy4uQfVIqAQwpm:brn20q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I tried extracting these functions into a new file in `distsqlplan` package but encountered "import cycle" problem. So I moved functions for converting into specs into `distsql_physical_planner`.
</blockquote></details>

What was the import cycle? `distsqlplan` depends on `distsqlrun`, so it shouldn't be possible for a piece of code to create a cycle when in `distsqlplan` but not when in `distsqlrun`..


<!-- Sent from Reviewable.io -->

2018-08-02 13:18 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LIulnFt1PEzt4MdIJTw:b-i13b59) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What was the import cycle? `distsqlplan` depends on `distsqlrun`, so it shouldn't be possible for a piece of code to create a cycle when in `distsqlplan` but not when in `distsqlrun`..
</blockquote></details>

I tried extracting all methods (for both to spec and from spec conversions) into a new file `window_frame.go` within `distsqlplan` package and then used one of them (convert spec of window frame to `tree.WindowFrame`) from `windower.go` within `distsqlrun`, so that created a cycle. I've just extracted spec-creating methods into `window_frame.go`.


<!-- Sent from Reviewable.io -->

2018-08-02 14:48 UTC, RaduBerinde reviewed
Sorry for the late reply (for some reason I missed the email).

[nit] Consider moving all the functions in `distsql_physical_planner.go` that are specific to window fns into a new file `distsql_plan_window.go`, since that file is getting pretty big.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIuyiAvBOQRevYy_0O2:b-mgq1ke)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6Pfx7Hk8pP5hH1jn:-LIuxmD03gd7Pi01LfGP:b-t3382t) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2814)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Agreed. I rewrote the comment, but, in general, is it reasonable to use names of return values in the comment to the function?
</blockquote></details>

Yeah, it's part of the function definition.
___
*[pkg/sql/distsql_physical_planner.go, line 2820 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6m5OBNWdWyd8TRof:-LIuzGgp33MVWAGyUjMD:b2ybns7) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2820)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I also use `isWindowFuncProcessed` to distinguish how to update the indices in `adjustColumnIndices` - if `isWindowFuncProcessed[f] == true`, then I'm updating `windowFuncOutputColumnIdx[f]`; if it is `false`, then I'm updating `f.argIdxStart`. If I were to switch to slice of unprocessed holders, I would need to go through the slice to figure out how to update an index for a particular `f`, that would be quadratic behavior. I don't think performance difference here is important, so please let me know if you still think that I should change my approach with `isWindowFuncProcessed` as a map from `windowFuncHolder` to `bool` (which I've introduced after your comments).
</blockquote></details>

We have a bunch of maps like that which gets tedious and hard to follow. It's especially cumbersome to understand what they are when you're just looking at a function that takes them as args. As a general principle, if you find yourself passing the same set of arguments to multiple functions, they probably need to be consolidated somehow.

I would consolidate them into a struct like:
```go
type windowFuncInfo struct {
  holder *windowFuncHolder
  funcIdx int
  isProcessed bool
  outputColIdx int
}
```
and pass around a slice of `[]windowFuncInfo` which every function uses and modifies accordingly. Each field should have a comment explaining what it is and at what stage it is set.

`findUnprocessedWindowFnsWithSamePartition` could then return a `[]*windowFuncInfo` with each pointer pointing to an entry in the "main" slice (we never append to it so that should be fine; alternatively you can make the main slice also be `[]*windowFuncInfo`)

You can also document the mechanics of what we're doing in a comment for the struct, and refer to this in other places (`// See the comment for windowFuncInfo`).

I would also consider adding a parent struct that stores more of the state that's used throughout, and change functions to be methods on this type, eg
```go
type windowPlanState struct {
  infos []windowFuncInfo
  n *windowNode
  evalCtx *tree.EvalContext
  plan *physicalPlan
}
```
___
*[pkg/sql/distsql_physical_planner.go, line 2884 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIkBTfE2ApsK7lYZvx5:-LIv2-Fr-SKXnD2IN5SM:br06oxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2884)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Will do my best.
</blockquote></details>

Looks good, thanks!
___
*[pkg/sql/distsql_physical_planner.go, line 2974 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk1pIKBr1r0kzRJy0t:-LIv26PTDF8kBVS9Ihg8:b-k0chxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2974)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great, very helpful!
___
*[pkg/sql/distsql_physical_planner.go, line 2989 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk2MF65PQDSaH6EsDZ:-LIv2JYTBkLKb7swSv5i:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2989)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Included an example. Please let me know if a more complex example would be beneficial (for example, with window functions with different partitioning).
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/distsqlrun/processors.proto, line 869 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIjxpLq4UITMUWtYLNB:-LIv2kOUC40Gj6dS-J8w:b-ea0ubd) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/processors.proto#L869)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

PG seems to be using 'value PRECEDING' in the docs and 'OFFSET_PRECEDING' in the code. I have no strong opinion about this, but maybe `OFFSET` incorporates the meaning the best, what do you think?
</blockquote></details>

They are using `'value' PRECEDING`, it becomes more confusing without the quotes. OFFSET_PRECEDING sounds good to me. I would document where that offset is stored. In fact, consider reordering them into groups of similar semantics and document each group. OFFSET_PRECEDING and OFFSET_FOLLOWING into one group, UNBOUNDED_* in another group, CURRENT_ROW in another.
___
*[pkg/sql/distsqlrun/processors.proto, line 878 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIjx-mt95ePc_kqYJ_I:-LIv5AXH7NLMkomkYSDh:b-v1w8fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/processors.proto#L878)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's a bit hacky to tunnel the VALUE_ offset through a Datum. I would add two separate fields, an integer for one case and a `bytes` for the other. That will also make the code that uses them a bit cleaner.
___
*[pkg/sql/distsqlrun/processors.proto, line 884 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIv5qnj0lCAgkZacPD4:-LIv5qnj0lCAgkZacPD5:bqyhbgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f361d2275daeb878d8e377bd0d5a1526505183a/pkg/sql/distsqlrun/processors.proto#L884)):*
> ```protobuf
>       // should be empty as well.
>       optional bytes offset = 2;
>       optional DatumInfo offset_type = 3;
> ```

This can be non-nullable, it is only used when `offset` isn't empty.
___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LIuxISABptwoI8eBK8i:b-8g42zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I tried extracting all methods (for both to spec and from spec conversions) into a new file `window_frame.go` within `distsqlplan` package and then used one of them (convert spec of window frame to `tree.WindowFrame`) from `windower.go` within `distsqlrun`, so that created a cycle. I've just extracted spec-creating methods into `window_frame.go`.
</blockquote></details>

I see. Yeah I think it's good to separate them even if they seem related right now - eventually we will create distributed plans directly which will affec [...]

2018-08-02 18:24 UTC, yuzefovich reviewed
Thanks for the comments!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIvAuys27q93RTFbMaw:b-a09w3v)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2814 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6Pfx7Hk8pP5hH1jn:-LIv9o2NBbY_BdYvW76F:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2814)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, it's part of the function definition.
</blockquote></details>

Got it, thanks.
___
*[pkg/sql/distsql_physical_planner.go, line 2820 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6m5OBNWdWyd8TRof:-LIvhaY8CzV7V-kZ76kY:bevmo4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2820)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We have a bunch of maps like that which gets tedious and hard to follow. It's especially cumbersome to understand what they are when you're just looking at a function that takes them as args. As a general principle, if you find yourself passing the same set of arguments to multiple functions, they probably need to be consolidated somehow.

I would consolidate them into a struct like:
```go
type windowFuncInfo struct {
  holder *windowFuncHolder
  funcIdx int
  isProcessed bool
  outputColIdx int
}
```
and pass around a slice of `[]windowFuncInfo` which every function uses and modifies accordingly. Each field should have a comment explaining what it is and at what stage it is set.

`findUnprocessedWindowFnsWithSamePartition` could then return a `[]*windowFuncInfo` with each pointer pointing to an entry in the "main" slice (we never append to it so that should be fine; alternatively you can make the main slice also be `[]*windowFuncInfo`)

You can also document the mechanics of what we're doing in a comment for the struct, and refer to this in other places (`// See the comment for windowFuncInfo`).

I would also consider adding a parent struct that stores more of the state that's used throughout, and change functions to be methods on this type, eg
```go
type windowPlanState struct {
  infos []windowFuncInfo
  n *windowNode
  evalCtx *tree.EvalContext
  plan *physicalPlan
}
```
</blockquote></details>

I love these suggestions - the improvement in readability is significant, IMHO!
___
*[pkg/sql/distsqlrun/processors.proto, line 869 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIjxpLq4UITMUWtYLNB:-LIvrNAbCZtwUhY6edf5:b-y86rz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/processors.proto#L869)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

They are using `'value' PRECEDING`, it becomes more confusing without the quotes. OFFSET_PRECEDING sounds good to me. I would document where that offset is stored. In fact, consider reordering them into groups of similar semantics and document each group. OFFSET_PRECEDING and OFFSET_FOLLOWING into one group, UNBOUNDED_* in another group, CURRENT_ROW in another.
</blockquote></details>

Ok, I will be using `OFFSET_*` here and will open a PR for this change in the local package.
___
*[pkg/sql/distsqlrun/processors.proto, line 878 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIjx-mt95ePc_kqYJ_I:-LIvr0S83VHD0hoHIHrg:byn1ztq) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/processors.proto#L878)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a bit hacky to tunnel the VALUE_ offset through a Datum. I would add two separate fields, an integer for one case and a `bytes` for the other. That will also make the code that uses them a bit cleaner.
</blockquote></details>

Done. I wonder whether I should extract these three fields into another message `Offset`.
___
*[pkg/sql/distsqlrun/processors.proto, line 884 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIv5qnj0lCAgkZacPD4:-LIvrKI64cxej0vUaOu-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f361d2275daeb878d8e377bd0d5a1526505183a/pkg/sql/distsqlrun/processors.proto#L884)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This can be non-nullable, it is only used when `offset` isn't empty.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LIvCBTBBG_yrl9SvhUN:b-e7qcmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I see. Yeah I think it's good to separate them even if they seem related right now - eventually we will create distributed plans directly which will affect just the planning side, and independent of that we might change the way we execute things which will affect just the execution side.
</blockquote></details>

Got it, makes sense.

Do functions from newly added `distsqlplan/window_frame.go` belong to `distsql_plan_window.go`?
___
*[pkg/sql/distsqlrun/windower.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIf_O4hEcTf3VEiTREE:-LIvCZHHEnh4CzdEfURc:b-yom1m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L744)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a slice (3 words), why would we store a pointer to it?
</blockquote></details>

Due to insufficient knowledge of internals of Go, I thought that using pointers would be more efficient.


<!-- Sent from Reviewable.io -->

2018-08-03 02:05 UTC, RaduBerinde reviewed
Thanks for the updates!  Planning code <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LIxV82CCree8I_bpUIE:bme1hhn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_physical_planner.go, line 2820 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk6m5OBNWdWyd8TRof:-LIxWxbcC2OhWR6xAN0n:b9efrar) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsql_physical_planner.go#L2820)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I love these suggestions - the improvement in readability is significant, IMHO!
</blockquote></details>

Thanks, it is much easier to follow now.
___
*[pkg/sql/distsql_plan_window.go, line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxUOYR53sTAgKJKOsy:-LIxUOYR53sTAgKJKOsz:blz5mxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L249)):*
> ```Go
> }
> 
> func (s *windowPlanState) addRenderingIfNecessary() error {
> ```

[nit] could use a comment
___
*[pkg/sql/distsql_plan_window.go, line 259 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxWCJI6T6yZ5fzlCq9:-LIxWCJI6T6yZ5fzlCqA:bbu0w06) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L259)):*
> ```Go
> 		}
> 	}
> 	if numWindowFuncsAsIs != len(s.infos) {
> ```

[nit] maybe add a comment explaining this.  Could the same window func appear multiple times? If it could,  something like `SELECT func(a), func(a) + 1` would have `numWindowFuncsAsIs = len(s.infos) = 1` but it still needs rendering
___
*[pkg/sql/distsql_plan_window.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxW7SN-S5CrB9H6PS0:-LIxW7SN-S5CrB9H6PS1:b-9w9aid) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L261)):*
> ```Go
> 	if numWindowFuncsAsIs != len(s.infos) {
> 		// Not all window functions' outputs are used directly, so we need rendering.
> 		needRendering = true
> ```

this flag isn't useful, we can invert the condition and `return` here
___
*[pkg/sql/distsql_plan_window.go, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxUcVAEoTcOjM3rxC6:-LIxUcVAEoTcOjM3rxC7:b1f1ebs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L328)):*
> ```Go
> }
> 
> type replaceWindowFuncsVisitor struct {
> ```

[nit] add a comment explaining what the visitor does.
___
*[pkg/sql/distsqlrun/processors.proto, line 878 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIjx-mt95ePc_kqYJ_I:-LIxWjdw0SvIX0JNHt84:b-84yn1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/processors.proto#L878)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done. I wonder whether I should extract these three fields into another message `Offset`.
</blockquote></details>

Not sure, probably not worth it since it's only used here
___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LIxSth-6g1DK4sEn3BE:bypykxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Got it, makes sense.

Do functions from newly added `distsqlplan/window_frame.go` belong to `distsql_plan_window.go`?
</blockquote></details>

Either way is fine.


<!-- Sent from Reviewable.io -->

2018-08-03 14:37 UTC, yuzefovich reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LJ-D8FVC316zYR_gFV0:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_plan_window.go, line 249 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxUOYR53sTAgKJKOsy:-LJ-AToKBWeV9v1on57n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L249)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could use a comment
</blockquote></details>

Done.
___
*[pkg/sql/distsql_plan_window.go, line 259 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxWCJI6T6yZ5fzlCq9:-LJ-8p-hAjH9q4Xy35-W:blztbuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L259)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe add a comment explaining this.  Could the same window func appear multiple times? If it could,  something like `SELECT func(a), func(a) + 1` would have `numWindowFuncsAsIs = len(s.infos) = 1` but it still needs rendering
</blockquote></details>

I expanded the comment.

The same window function might appear multiple times, but its every occurrence is replaced by a different `windowFuncHolder` (and each is computed independently - opportunity for refactoring), so the logic of checking `numWindowFuncsAsIs == len(s.infos)` still holds.
___
*[pkg/sql/distsql_plan_window.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxW7SN-S5CrB9H6PS0:-LJ-7YfS9LL_OIbfridQ:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L261)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this flag isn't useful, we can invert the condition and `return` here
</blockquote></details>

Nice, thanks!
___
*[pkg/sql/distsql_plan_window.go, line 328 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIxUcVAEoTcOjM3rxC6:-LJ-CDzq0cK24wW6bdyD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fb25bd03a78bad3fbc53c6879718cfafaeafd08/pkg/sql/distsql_plan_window.go#L328)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment explaining what the visitor does.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIk-G2J6poYX-yqSKK0:-LJ-CJXL0Ub4U8ytEv5S:b-vfnvd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/41acc352eff543466f6a8b3411c180470ef22397/pkg/sql/distsqlrun/windower.go#L663)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Either way is fine.
</blockquote></details>

Ok, I'll keep it in a separate file then.


<!-- Sent from Reviewable.io -->

2018-08-06 17:34 UTC, jordanlewis requested changes
Couple last comments, but this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>!

Forgot to mention this earlier, but it would be good to see how the 1-node performance of this stacks up against the local sql version. Have you looked into that? I don't think it will be a blocker if it's slower, but it would be good to know anyway. And if it's faster, then that would be great!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LJFIJGv0C8wnsbLCMxT:bt8kfiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/distsqlplan/window_frame.go, line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFHCH77aZ7UUuRkOt4:-LJFHCH77aZ7UUuRkOt5:bvmv081) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlplan/window_frame.go#L24)):*
> ```Go
> )
> 
> func mapToSpecMode(m tree.WindowFrameMode) distsqlrun.WindowerSpec_Frame_Mode {
> ```

I would make all the functions in this file methods on their respective types, so you don't pollute the function namespace of `distsqlplan` more than you have to.
___
*[pkg/sql/distsqlrun/windower.go, line 462 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIYJ8Ul8HxrfULJbMh1:-LJFH_2620nw8kvnYXzl:b-rwvsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/946f01e4b93e632947c1993314e2d02fc7490988/pkg/sql/distsqlrun/windower.go#L462)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I couldn't figure out how to avoid making this extra allocation. Simply assigning `partition` was not enough since later calls to `sort.Sort` would have resorted already cached partitions. Probbly I'm missing something.
</blockquote></details>

This probably means you're reusing memory in your partitions slice... but that might not be a bad thing. I think this might be able to get fixed but we can do it later if it proves to be a performance issue.
___
*[pkg/sql/distsqlrun/windower.go, line 355 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFFunU5VdBr74LWjJf:-LJFFunU5VdBr74LWjJg:bn8bqlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L355)):*
> ```Go
> 	}
> 
> 	w.moveToDraining(nil /* err */)
> ```

Is this really a non-exceptional case? if we call `emitRow` and `inputDone` is false, doesn't that indicate a programming error? I would return an error here if you think this is an impossible case.
___
*[pkg/sql/distsqlrun/windower.go, line 603 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFGhyHBAUndRpUAhKO:-LJFGhyHBAUndRpUAhKP:bn6eit6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L603)):*
> ```Go
> }
> 
> func convertToWindowFrameBoundType(bt WindowerSpec_Frame_BoundType) tree.WindowFrameBoundType {
> ```

I would make this a method on WindowerSpec_Frame_BoundType. You can put methods like that in `processors.go` - there should be a few examples of stuff like this already.
___
*[pkg/sql/distsqlrun/windower.go, line 624 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFH2T77mvsnDPb9aio:-LJFH2T77mvsnDPb9aip:b-4685tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L624)):*
> ```Go
> // to original - if offsetExprs were present in original WindowFrameBounds,
> // they are not included.
> func convertToWindowFrameBounds(b WindowerSpec_Frame_Bounds) tree.WindowFrameBounds {
> ```

make a method
___
*[pkg/sql/distsqlrun/windower.go, line 634 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFH3QiDnqWvLg8XpcX:-LJFH3QiDnqWvLg8XpcY:b-4685tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L634)):*
> ```Go
> }
> 
> func convertToWindowFrame(f *WindowerSpec_Frame) *tree.WindowFrame {
> ```

make a method


<!-- Sent from Reviewable.io -->

2018-08-06 19:48 UTC, yuzefovich reviewed
Here are some benchmarks on 1 node roachprod cluster with TPCH dataset. Numbers are pretty bad, but I intend to address them shortly in a follow-up PR.

Comparison on **orders** table (1500000 rows)

| Query | Local | DistSQL | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY o_orderdate) FROM orders ORDER BY o_orderkey LIMIT 10;` | 3.023270155s | 5.78931469s | **+91.49%** |
| `SELECT sum(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 6.198205174s | 8.256055458s | **+33.20%** |
| `SELECT avg(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 17.303959973s | 19.989431154s | **+15.52%** |
| `SELECT avg(o_totalprice) OVER w, sum(o_custkey) OVER w FROM orders WINDOW w AS (PARTITION BY o_orderdate ORDER BY o_orderkey) ORDER BY o_orderkey LIMIT 10;` | 20.018077996s | 21.549266051s | **+7.65%** |

Comparison on **lineitem** table (6001215 rows)

| Query | Local | DistSQL | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY l_shipdate) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 13.851707421s | 27.826481555s | **+100.89%** |
| `SELECT sum(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 26.043522206s | 38.206965506s | **+46.7%** |
| `SELECT avg(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 71.051479611s | 79.565357269s | **+11.98%** |

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-:-LJFm0WT4cEMd8keCzIn:bxnv9ef)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlplan/window_frame.go, line 24 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFHCH77aZ7UUuRkOt4:-LJFWg_6BAXavAp4PWwA:b-xatoze) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlplan/window_frame.go#L24)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would make all the functions in this file methods on their respective types, so you don't pollute the function namespace of `distsqlplan` more than you have to.
</blockquote></details>

I introduced methods that return constructors of all spec-related objects. Please let me know if this is a bad practice.
___
*[pkg/sql/distsqlrun/windower.go, line 462 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LIYJ8Ul8HxrfULJbMh1:-LJFRxtH0hvYBdhccw3t:b-e8f6er) ([raw file](https://github.com/cockroachdb/cockroach/blob/946f01e4b93e632947c1993314e2d02fc7490988/pkg/sql/distsqlrun/windower.go#L462)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This probably means you're reusing memory in your partitions slice... but that might not be a bad thing. I think this might be able to get fixed but we can do it later if it proves to be a performance issue.
</blockquote></details>

Sounds good, added a `TODO`.
___
*[pkg/sql/distsqlrun/windower.go, line 355 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFFunU5VdBr74LWjJf:-LJFRPP311DZrTB4y51S:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L355)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is this really a non-exceptional case? if we call `emitRow` and `inputDone` is false, doesn't that indicate a programming error? I would return an error here if you think this is an impossible case.
</blockquote></details>

Good point, done.
___
*[pkg/sql/distsqlrun/windower.go, line 603 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFGhyHBAUndRpUAhKO:-LJFTHha7bOLVV7Qlviz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L603)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would make this a method on WindowerSpec_Frame_BoundType. You can put methods like that in `processors.go` - there should be a few examples of stuff like this already.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 624 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFH2T77mvsnDPb9aio:-LJFTMvh7B7ZjyUNAkXi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L624)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

make a method
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/windower.go, line 634 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/27140#-LJFH3QiDnqWvLg8XpcX:-LJFTNxY64wmVpTNSH9c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ecc6818f8cf9a281ed37a3d9d8097100dcdf027/pkg/sql/distsqlrun/windower.go#L634)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

make a method
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-06 20:45 UTC, jordanlewis approved these changes
> Reviewed 2 of 12 files at r3, 1 of 7 files at r5, 2 of 6 files at r6, 4 of 6 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27140)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-08-06 21:19 UTC, yuzefovich commented
Thanks everyone for the comments!

I'm dismissing blocks from @asubiotto and @nvanbenschoten since it seems that they have already provided all the input.

2018-08-06 21:22 UTC, yuzefovich commented
bors r+

2018-08-06 21:22 UTC, yuzefovich commented
bors r+

2018-08-06 21:24 UTC, yuzefovich commented
bors r+

2018-08-06 21:41 UTC, merged