storage: handle lease acquisition during merge
cockroachdb/cockroach pull request #27266
Opened 2018-07-09 04:15 UTC by benesch

Ensure that, upon acquiring a lease, replicas check whether a merge is
in progress and, if so, block all traffic unless the merge aborts. Add a
test to exercise this scenario.

Release note: None

2018-07-09 04:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27266)
<!-- Reviewable:end -->

2018-07-09 15:09 UTC, bdarnell approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27266)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-09 15:11 UTC, tbg requested changes
The code changes LGTM, I personally would've tried to avoid a test that pulls as many levers. Is that not testing something your test does or do you think it would've turned out approximately as complex?

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-:-LGz_nWh8en2fproPrUz:b-3hyio4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 641 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-LGzXss96is4ns_6l7FF:-LGzXssA1CKrWFXXN16i:bq4mgzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff1fe15914d18d2f7c954b3f2648c9311386fab/pkg/storage/client_merge_test.go#L641)):*
> ```Go
> // in a merge loses its lease while a merge is in progress, the new leaseholder
> // does not incorrectly serve traffic before the merge completes.
> func TestStoreRangeMergeRHSLeaseExpiration(t *testing.T) {
> ```

Couldn't you just simulate the actual merge instead of trying to intercept the real one? After all, all that matters is the right kind of intent on the meta descriptor.  All that was left to do after that is expire the lease and get a new one. Wouldn't that have made this test much less high-maintenance at about the same coverage?

BTW, regarding maybeWatchForMerge, what happens if the meta2 record for the range descriptor actually lives on the range that is being merged away? I think the RangeLookups would itself get stuck on the merge channel, and depending on what the actual merge txn does, it'll also deadlock itself (hopefully not, but is that clear)? That seems worth a test as well.
___
*[pkg/storage/client_merge_test.go, line 729 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-LGzY8xP3QF3oA877H4_:-LGzY8xP3QF3oA877H4a:b-4bjgbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff1fe15914d18d2f7c954b3f2648c9311386fab/pkg/storage/client_merge_test.go#L729)):*
> ```Go
> 	// should notice the second store's lease is expired and try to acquire it.
> 	getErr := make(chan error)
> 	go func() {
> ```

This is unsynchronized with `mtc.Stop` which seems problematic. Can you waitgroup this (or use a stopper if there's one around)? Ditto the other goroutine (and any others I've missed).


<!-- Sent from Reviewable.io -->

2018-07-09 19:20 UTC, benesch reviewed
> Is that not testing something your test does or do you think it would've turned out approximately as complex?

I'm mostly worried about not testing the merge code itself. E.g., what if the merge transaction gets reordered in a broken way? A test that simulates its own merge transaction wouldn't notice that.

I also think that most of the complexity stems not from holding open the merge transaction but trying to verify that a request sent while the merge transaction is open does not complete until the transaction commits. That problem persists even with a simulated merge transaction. How do you verify a happens-before in a test? You can't really. One option would be to introduce a testing knob that calls back whenever a request blocks on mergeCompleteCh. Then we could simplify verify that the callback fires for our sentinel get request.

Thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-:-LH-RVpf9ipoq5O4NlME:bhk9bco)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 641 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-LGzXss96is4ns_6l7FF:-LGzcVxl-roPcuLNH0C6:bbyvtfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff1fe15914d18d2f7c954b3f2648c9311386fab/pkg/storage/client_merge_test.go#L641)):*
> BTW, regarding maybeWatchForMerge, what happens if the meta2 record for the range descriptor actually lives on the range that is being merged away? I think the RangeLookups would itself get stuck on the merge channel, and depending on what the actual merge txn does, it'll also deadlock itself (hopefully not, but is that clear)? That seems worth a test as well.

Yeah, the plan we discussed somewhere is to never allow the meta ranges to be merged. Definitely worth a test though.
___
*[pkg/storage/client_merge_test.go, line 729 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-LGzY8xP3QF3oA877H4_:-LGzbaVQ6Gl7DMB3z1Zt:b-4s40wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff1fe15914d18d2f7c954b3f2648c9311386fab/pkg/storage/client_merge_test.go#L729)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is unsynchronized with `mtc.Stop` which seems problematic. Can you waitgroup this (or use a stopper if there's one around)? Ditto the other goroutine (and any others I've missed).
</blockquote></details>

How so? The test function can't return until it reads from getErr.


<!-- Sent from Reviewable.io -->

2018-07-10 18:45 UTC, tbg requested changes
> How do you verify a happens-before in a test?

Yeah, that is always tricky. I'm personally OK with just making the failure mode in that case a flaky one (as I think you've done here).
You could replace the channel with a cond, which you could then manually check in your test. That doesn't exactly prove that requests would block (they may not check the cond correctly) but it confines the "happens-before" to a much smaller area of the test. OTOH, a cond would make it harder for reads to bail out if they got held up for too long.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-:-LH4VDXk45gEMW3rwObb:b-p6w15o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 729 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-LGzY8xP3QF3oA877H4_:-LH4V4pS3KdbXhoptADE:b4h1dyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff1fe15914d18d2f7c954b3f2648c9311386fab/pkg/storage/client_merge_test.go#L729)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

How so? The test function can't return until it reads from getErr.
</blockquote></details>

Oh, totally missed that. Carry on.


<!-- Sent from Reviewable.io -->

2018-07-10 18:45 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27266#-:-LH4Vq5AC6WRbSsE0ADt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-11 00:17 UTC, benesch commented
OK, merging as is to keep things moving along! TFTRs.

bors r=tschottdorf,bdarnell

2018-07-11 00:52 UTC, merged