opt: lookup join rules
cockroachdb/cockroach pull request #27275
Opened 2018-07-09 12:06 UTC by RaduBerinde

This change adds two exploration rules that convert joins to lookup
joins. Note that lookup join has very large cost because the exec path
is not currently implemented; the only way to test the rules right now
is with the new `exploretrace`.

Note that because we needed a custom function from `norm` (which
needed the factory and hence can't be moved to `xfunc`), `xform` now
embeds `norm.CustomFuncs`.

Release note: None

2018-07-09 12:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27275)
<!-- Reviewable:end -->

2018-07-09 14:36 UTC, justinj reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-:-LGzSZ5I4A9NBqvUAhvb:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/rules/join.opt, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzOt__4uOCzchmno3f:-LGzOt__4uOCzchmno3g:b-dsvkvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/rules/join.opt#L55)):*
> ```
> (ConstructLookupJoin (OpName) $left $scanDef $on)
> 
> # GenerateLoopJoinWithFilter creates a LookupJoin alternative for a Join which
> ```

nit: `GenerateLookupJoinWithFilter`
___
*[pkg/sql/opt/xform/rules/join.opt, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzP-sQE5GRlBTYzAKs:-LGzP-sQE5GRlBTYzAKt:b-tz8spq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/rules/join.opt#L56)):*
> ```
> 
> # GenerateLoopJoinWithFilter creates a LookupJoin alternative for a Join which
> # has a Select->Scan complex as its right input. The filter can get merged with
> ```

"complex expression"?


<!-- Sent from Reviewable.io -->

2018-07-09 15:37 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-:-LGzgFQ4EQfUfJ6NNemu:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzaxkA0YUZ52-FL37b:-LGzaxkA0YUZ52-FL37c:bfqqqix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L439)):*
> ```Go
> 	firstCol := md.TableColumn(scanDef.Table, idx.Column(0).Ordinal)
> 	for i := range leftEq {
> 		if rightEq[i] == firstCol {
> ```

why are you iterating through `leftEq` but indexing into `rightEq`? I suppose it doesn't matter if they are the same length, but it adds some unnecessary head scratching...
___
*[pkg/sql/opt/xform/custom_funcs.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzdOMa-iZ2f5NuHOAD:-LGzdOMb0u3BYylCHVn4:b-p2vfmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L472)):*
> ```Go
> 		for j := range rightEq {
> 			if rightEq[j] == idxCol {
> 				found = j
> ```

This would probably be easier if you use the equivalent columns from the FDs since they are just `ColSet`s


<!-- Sent from Reviewable.io -->

2018-07-09 17:14 UTC, andy-kimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-:-LH-1AFr-SKycTP3KU_M:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzhzl03TkeHLDCJ71Z:-LGzhzl1-uFKEb1D-YEz:bme7cvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L424)):*
> ```Go
> //  - the scan has no limit, and
> //  - a prefix of the scan index columns have equality constraints.
> func (c *CustomFuncs) CanDoLookupJoin(
> ```

NIT: maybe `CanUseLookupJoin`?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzjNAD5Gkws1HPx7vF:-LGzjNAD5Gkws1HPx7vG:bzgzba3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L435)):*
> ```Go
> 	onExpr := memo.MakeNormExprView(c.e.mem, on)
> 	leftEq, rightEq := harvestEqualityColumns(inputProps.OutputCols, scanDef.Cols, onExpr)
> 	// Check if the first column in the index has an equality constraint.
> ```

NIT: Outside the `exec` files, we consistently add a blank line before comments that aren't at the beginning of a block. This makes the code less dense (and I think easier to read/scan). I'd typically add whitespace after blocks as well, if the following code is not "related" to the previous block (e.g. whitespace before the `inputProps := c.e.mem.GroupProperties` code above, since that's relatively unrelated to the previous check of `scanDef`. I use a similar principle when deciding where to break paragraphs in prose.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzu9pZ8SHV1MS9_Y8-:-LGzu9pZ8SHV1MS9_Y80:b3imdif) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L460)):*
> ```Go
> 	}
> 	idx := md.Table(scanDef.Table).Index(scanDef.Index)
> 	numCols := idx.LaxKeyColumnCount()
> ```

NIT: `numIndexCols` would be more descriptive. There are so many possible column sets it gets confusing which is which.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzdOMa-iZ2f5NuHOAD:-LGztl9qBzNBWY9VdsP-:b-qs3lyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L472)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This would probably be easier if you use the equivalent columns from the FDs since they are just `ColSet`s
</blockquote></details>

Radu and I discussed this a couple weeks back. I think he plans to eventually switch to use the FD set when harvesting columns.


<!-- Sent from Reviewable.io -->

2018-07-09 17:54 UTC, RaduBerinde reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-:-LH-3h9fBAZmAFRMCl0d:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzaxkA0YUZ52-FL37b:-LH-4JFW8cy0UOZX4vuZ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L439)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why are you iterating through `leftEq` but indexing into `rightEq`? I suppose it doesn't matter if they are the same length, but it adds some unnecessary head scratching...
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzdOMa-iZ2f5NuHOAD:-LH-4Ph74--ofK68FYRw:b-59jzmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L472)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Radu and I discussed this a couple weeks back. I think he plans to eventually switch to use the FD set when harvesting columns.
</blockquote></details>

Yeah, for now I just used the same approach used by merge join. I definitely need to work on this to use the FDs and simplify the remaining ON condition (and figure out a way to only calculate it once for a given join).
___
*[pkg/sql/opt/xform/rules/join.opt, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzP-sQE5GRlBTYzAKs:-LH-4jZh7QGneV3GGphm:b-psd31p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/rules/join.opt#L56)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

"complex expression"?
</blockquote></details>

My intention was to use it as a noun.. Switched to "combination"


<!-- Sent from Reviewable.io -->

2018-07-09 18:29 UTC, rytaft approved these changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27275)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27275#-LGzdOMa-iZ2f5NuHOAD:-LH-IFLk7oIjm4-1bcdI:bq0ncok) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f68a7816acdfc80135b9652f16889d69cc038/pkg/sql/opt/xform/custom_funcs.go#L472)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, for now I just used the same approach used by merge join. I definitely need to work on this to use the FDs and simplify the remaining ON condition (and figure out a way to only calculate it once for a given join).
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2018-07-10 03:01 UTC, RaduBerinde commented
bors r+

2018-07-10 15:21 UTC, RaduBerinde commented
bors r+

2018-07-10 15:41 UTC, merged