storage: Respect the ReturnRangeInfo options on Admin requests
cockroachdb/cockroach pull request #27311
Opened 2018-07-10 03:09 UTC by a-robinson

This would have been nice to have for the implementation of
EXPERIMENTAL_RELOCATE LEASE in #26436 to make it easier to obtain the
range information for each range whose lease is transferred by the
command. Instead, a separate range lookup must be issued. This would
also be useful for EXPERIMENTAL_RELOCATE and any other statements that
operate on ranges and then return which ranges were operated on (except
SCATTER, whose implementation is already special-cased to always return
the needed info).

With this included in v2.1, we can start using it where appropriate in
the v2.2 release.

Release note: None

2018-07-10 03:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27311)
<!-- Reviewable:end -->

2018-07-10 03:29 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27311)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27311#-LH1Dist-1b080XNzQBW:-LH1Dist-1b080XNzQBX:b-7zu939) ([raw file](https://github.com/cockroachdb/cockroach/blob/5babc472899179d487ab2d18005e85a0dc4cdfe2/pkg/storage/replica.go#L2589)):*
> ```Go
> 	}
> 
> 	if ba.Header.ReturnRangeInfo {
> ```

Do you think it makes sense to pull this code and the identical code in `evaluateCommand` up into `Replica.Send`?


<!-- Sent from Reviewable.io -->

2018-07-11 16:42 UTC, a-robinson reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27311)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27311#-LH1Dist-1b080XNzQBW:-LH97C0P0bib57coxml-:b-7pnj16) ([raw file](https://github.com/cockroachdb/cockroach/blob/5babc472899179d487ab2d18005e85a0dc4cdfe2/pkg/storage/replica.go#L2589)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think it makes sense to pull this code and the identical code in `evaluateCommand` up into `Replica.Send`?
</blockquote></details>

It may make sense to pull it out into a helper function to avoid duplicating the logic for populating the `RangeInfo`s, but it seemed too awkward to do in `Replica.Send` because the `RangeInfo`s go into the `ResponseHeader` on the individual `Response` types in the `ResponseUnion`, not the `Header` that goes directly in the `BatchResponse`, so we'd have to iterate through all the `Response`s in the `BatchResponse`, pull them out and modify their `ResponseHeader`s, then put them back in. Or something like that.

I've just put the code into a helper function for now,


<!-- Sent from Reviewable.io -->

2018-07-11 16:47 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27311#-:-LH9EKhUBDLAO_5ohLS6:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-11 16:54 UTC, a-robinson commented
bors r+

2018-07-11 17:36 UTC, a-robinson commented
Flaked on https://github.com/cockroachdb/cockroach/issues/27405

bors r+

2018-07-11 18:20 UTC, a-robinson commented
#27405 again :(

I'll wait until https://github.com/cockroachdb/cockroach/pull/27406 is in.

2018-07-11 18:49 UTC, a-robinson commented
bors r+

2018-07-11 19:03 UTC, merged