opt: fix crash related to ordering with equivalent columns
cockroachdb/cockroach pull request #27351
Opened 2018-07-10 23:34 UTC by RaduBerinde

When we have a group of equivalent columns in an OrderingChoice, we
have to pick (for sorting) one that is produced by the plan. The
current code incorrectly assumes that any of them works.

Fixes #27347.

Release note: None

2018-07-10 23:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27351)
<!-- Reviewable:end -->

2018-07-11 13:48 UTC, justinj reviewed
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-:-LH8_spp36O0STiunc6u:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LH8_U819GRv-YHFtzlA:-LH8_U819GRv-YHFtzlB:b-jnwx30) ([raw file](https://github.com/cockroachdb/cockroach/blob/0072b399f81e976b7252339db6ad2c163df11a74/pkg/sql/opt/exec/execbuilder/testdata/orderby#L814)):*
> ```
> # Verify that we set up the ordering of the inner scan correctly (see #27347).
> query TTTTT
> EXPLAIN (VERBOSE) SELECT * FROM xyz WHERE z=1 AND x=y ORDER BY x;
> ```

[optional] maybe doing a second one of these that's ordered by `y` would guarantee that the issue here will always be correctly surfaced?


<!-- Sent from Reviewable.io -->

2018-07-11 14:05 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LH8_U819GRv-YHFtzlA:-LH8ddYW-pI_eNGiZqP0:b-7smd5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0072b399f81e976b7252339db6ad2c163df11a74/pkg/sql/opt/exec/execbuilder/testdata/orderby#L814)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

[optional] maybe doing a second one of these that's ordered by `y` would guarantee that the issue here will always be correctly surfaced?
</blockquote></details>

Agreed - can you add a regression test that would fail without your new fix?


<!-- Sent from Reviewable.io -->

2018-07-11 14:26 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LH8_U819GRv-YHFtzlA:-LH8ihAO-vxVYwoor8rs:b-33ef3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0072b399f81e976b7252339db6ad2c163df11a74/pkg/sql/opt/exec/execbuilder/testdata/orderby#L814)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Agreed - can you add a regression test that would fail without your new fix?
</blockquote></details>

This is the regression test.. It crashes without my fix.

It's not important whether it's `x` or `y` in the `ORDER BY`. It's important that the first column in the group `x` (what `AnyID()` returns) is not produced by the `scan`.


<!-- Sent from Reviewable.io -->

2018-07-11 14:27 UTC, andy-kimball reviewed
In what case are all the relational output columns not in the `execPlan`? Are you sure there's not a bug

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-:-LH8j2VjEgP5edrmGyy4:bqhuay9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LH8_U819GRv-YHFtzlA:-LH8jJLx9NPRWnZrpObX:bhqf994) ([raw file](https://github.com/cockroachdb/cockroach/blob/0072b399f81e976b7252339db6ad2c163df11a74/pkg/sql/opt/exec/execbuilder/testdata/orderby#L814)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is the regression test.. It crashes without my fix.

It's not important whether it's `x` or `y` in the `ORDER BY`. It's important that the first column in the group `x` (what `AnyID()` returns) is not produced by the `scan`.
</blockquote></details>

But if it's not produced by the scan, how come it's a relational output column for the scan?


<!-- Sent from Reviewable.io -->

2018-07-11 14:30 UTC, RaduBerinde commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LH8_U819GRv-YHFtzlA:-LH8jmOJ7bS2cWA1gfpS:b-13nmjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0072b399f81e976b7252339db6ad2c163df11a74/pkg/sql/opt/exec/execbuilder/testdata/orderby#L814)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But if it's not produced by the scan, how come it's a relational output column for the scan?
</blockquote></details>

It isn't..


<!-- Sent from Reviewable.io -->

2018-07-11 15:54 UTC, RaduBerinde commented
I am implementing a cleaner solution suggested by Andy (trim down the OrderingChoice), but with the  assertions I added I am finding a bunch of issues that need fixing. Hold off on reviewing for now.

2018-07-12 16:19 UTC, RaduBerinde commented
Updated, RFAL

2018-07-12 18:19 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> nice change!

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-:-LHEhEqz9_uF-GDOxCsG:b-iu510j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/prune_cols.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHEe63G3tYKt0Hpy627:-LHEe63G3tYKt0Hpy628:b-dgjwu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00392d9eb4b5bbd9482b88efaa1dd5e76e493db0/pkg/sql/opt/norm/prune_cols.go#L210)):*
> ```Go
> 	defCopy := *def
> 	defCopy.Ordering = defCopy.Ordering.Copy()
> 	defCopy.Ordering.ProjectCols(outCols)
> ```

Feels like these few lines could be part of a helper function called by all three `ProjectOrdering` functions.
___
*[pkg/sql/opt/xform/physical_props.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHEgfpPDtGlWkOFM8RI:-LHEgfpPDtGlWkOFM8RJ:b-sga3ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/00392d9eb4b5bbd9482b88efaa1dd5e76e493db0/pkg/sql/opt/xform/physical_props.go#L162)):*
> ```Go
> 
> 	case opt.LimitOp, opt.OffsetOp, opt.RowNumberOp, opt.GroupByOp:
> 		// Limit/Offset/RowNumber require the ordering in their private.
> ```

Update comment to include GroupBy


<!-- Sent from Reviewable.io -->

2018-07-12 18:23 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/prune_cols.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHEe63G3tYKt0Hpy627:-LHEiXMh338GP-vGurAb:b-yb4tco) ([raw file](https://github.com/cockroachdb/cockroach/blob/00392d9eb4b5bbd9482b88efaa1dd5e76e493db0/pkg/sql/opt/norm/prune_cols.go#L210)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Feels like these few lines could be part of a helper function called by all three `ProjectOrdering` functions.
</blockquote></details>

`def` is a different type in each case
___
*[pkg/sql/opt/xform/physical_props.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHEgfpPDtGlWkOFM8RI:-LHEiUYp48iKnQbXgds2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00392d9eb4b5bbd9482b88efaa1dd5e76e493db0/pkg/sql/opt/xform/physical_props.go#L162)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment to include GroupBy
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-12 18:28 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/prune_cols.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHEe63G3tYKt0Hpy627:-LHEjLZq3NInjIF2YWa0:bbnnxwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/00392d9eb4b5bbd9482b88efaa1dd5e76e493db0/pkg/sql/opt/norm/prune_cols.go#L210)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`def` is a different type in each case
</blockquote></details>

I was thinking you could pass `def.Ordering` or something to the helper function -- but I see your point, it gets a bit messy. Probably not worth it.


<!-- Sent from Reviewable.io -->

2018-07-13 00:35 UTC, RaduBerinde commented
bors r+

2018-07-13 01:00 UTC, merged

2018-07-13 01:24 UTC, andy-kimball commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, have a few comments that aren't vital, sorry they're late.





<!-- Sent from Reviewable.io -->

2018-07-13 01:24 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGB82rC_T4G2NRLCHZ:-LHGB82rC_T4G2NRLCH_:b-3qaxhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/norm/custom_funcs.go#L240)):*
> ```Go
> // not output columns of the given group. Can only be called if
> // HasColsInOrdering is true.
> func (c *CustomFuncs) ProjectOrdering(group memo.GroupID, ordering memo.PrivateID) memo.PrivateID {
> ```

NIT: Maybe a better name would be `PruneOrdering`, since all it ever does is remove columns? Also, it would have naming symmetry with the `PruneCols` rules.
___
*[pkg/sql/opt/props/ordering_choice.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHErc2EBQCABzcIk9L9:-LHErc2EBQCABzcIk9LA:bd1jrjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/props/ordering_choice.go#L298)):*
> ```Go
> //   (3,4)   => false
> //
> func (oc *OrderingChoice) CanProject(cs opt.ColSet) bool {
> ```

NIT: `CanProjectCols` would create better naming symmetry with `ProjectCols`.
___
*[pkg/sql/opt/xform/physical_props.go, line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGCSsm-6twJzpnrmJM:-LHGCSsm-6twJzpnrmJN:b-bi8d4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/xform/physical_props.go#L147)):*
> ```Go
> 	// Ordering property.
> 	switch mexpr.Operator() {
> 	case opt.ProjectOp, opt.SelectOp, opt.IndexJoinOp, opt.LookupJoinOp:
> ```

I think we should put `opt.SelectOp` in its own `case`, since its input columns are always the same as its output columns, and therefore doesn't need to make the pruning check. Its logic can stay just as it was.
___
*[pkg/sql/opt/xform/physical_props.go, line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGDIR_B22_b1JUQ2l6:-LHGDIR_B22_b1JUQ2l7:b-482ckf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/xform/physical_props.go#L201)):*
> ```Go
> 	}
> 
> 	if !childProps.Ordering.Any() {
> ```

Should this be only run with `-race` flag?


<!-- Sent from Reviewable.io -->

2018-07-13 02:36 UTC, RaduBerinde reviewed
Opened #27453 to address the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-:-LHGUP3N04sz3CjWTFU5:b-k21u8y)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGB82rC_T4G2NRLCHZ:-LHGTjLPD_B1BNd-nIzy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/norm/custom_funcs.go#L240)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Maybe a better name would be `PruneOrdering`, since all it ever does is remove columns? Also, it would have naming symmetry with the `PruneCols` rules.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/ordering_choice.go, line 298 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHErc2EBQCABzcIk9L9:-LHGTmra6MKmAsqYT81K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/props/ordering_choice.go#L298)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: `CanProjectCols` would create better naming symmetry with `ProjectCols`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/physical_props.go, line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGCSsm-6twJzpnrmJM:-LHGU82FE-GnUpxgH3ps:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/xform/physical_props.go#L147)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think we should put `opt.SelectOp` in its own `case`, since its input columns are always the same as its output columns, and therefore doesn't need to make the pruning check. Its logic can stay just as it was.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/physical_props.go, line 201 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27351#-LHGDIR_B22_b1JUQ2l6:-LHGS_9R79-YXO7hQQOO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe1a590449e9f52d0605325a7ea4d9cd11f06ec0/pkg/sql/opt/xform/physical_props.go#L201)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should this be only run with `-race` flag?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->