opt: plan inverted index queries
cockroachdb/cockroach pull request #27433
Opened 2018-07-12 15:43 UTC by justinj

This commit uses this optimizer to plan inverted index queries. The
functionality is the same as in the existing planner, modulo that it
does not currently support efficient `->` filters.

Andy and I previously discussed defining the index as a path,value,pk
table, but I think for the time being that introduces a lot of
additional questions and invalidates a lot of existing assumptions, for
example, that the primary index is always covering. Open to discuss this
more if people have opinions on how it should work.

Release note: None

2018-07-12 15:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27433)
<!-- Reviewable:end -->

2018-07-12 19:36 UTC, rytaft requested changes
Exciting to see this!

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-:-LHEzPnTCqXDPCtqxNDZ:bqvic1x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEmcrmCseMCxqkHchy:-LHEmcrn8Rw3rjNGTngx:bbn3e5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/testutils/testcat/test_catalog.go#L251)):*
> ```Go
> 
> 	// inverted is true when this index is an inverted index.
> 	inverted bool
> ```

All other fields are exported -- is there a reason this one is not?
___
*[pkg/sql/opt/xform/rules/scan.opt, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEmsnVCQhziztQwFOO:-LHEmsnWCFP9Frz_nyfR:bcazqde) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/rules/scan.opt#L11)):*
> ```
> (Scan $def:* & (CanGenerateIndexScans $def)) => (GenerateIndexScans $def)
> 
> # GenerateInvertedIndexScans.
> ```

Expand this comment a bit to explain what it does.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEnH9y0mBG-eZDCB-L:-LHEnH9y0mBG-eZDCB-M:buvpiqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L128)):*
> ```
> 
> opt
> SELECT s FROM a ORDER BY k DESC
> ```

If you change this to `SELECT * ...` does it keep the reverse scan?
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEpWau2izt7lxGZ5b4:-LHEpWau2izt7lxGZ5b5:bad4xwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L631)):*
> ```
>  ├── columns: k:1(int!null)
>  ├── key: (1)
>  └── index-join a
> ```

Why do you need an index join here? Can't you get away with just scanning the inverted index?


<!-- Sent from Reviewable.io -->

2018-07-12 20:04 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEmcrmCseMCxqkHchy:-LHF-ReR1GZoEejiQsBK:b-n7txjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/testutils/testcat/test_catalog.go#L251)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

All other fields are exported -- is there a reason this one is not?
</blockquote></details>

No reason - changed it for consistency.
___
*[pkg/sql/opt/xform/rules/scan.opt, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEmsnVCQhziztQwFOO:-LHF-TiTDlS3wGTN5HiV:b-lrgeh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/rules/scan.opt#L11)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Expand this comment a bit to explain what it does.
</blockquote></details>

Oops - meant to fill this in before pushing.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEnH9y0mBG-eZDCB-L:-LHF2xVe7s1sTWzWri5i:bg51gvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L128)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

If you change this to `SELECT * ...` does it keep the reverse scan?
</blockquote></details>

Oh, I didn't realize this changed, it doesn't, I'll just remove the extra column for now.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEpWau2izt7lxGZ5b4:-LHF2nLP5aTgb7iXZQCO:bsarayv) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L631)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why do you need an index join here? Can't you get away with just scanning the inverted index?
</blockquote></details>

Weird, I thought the index join was gone here, but looking into it now I see that it's slightly involved to get rid of it, will look into that.


<!-- Sent from Reviewable.io -->

2018-07-12 20:36 UTC, rytaft reviewed
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-15 20:05 UTC, RaduBerinde requested changes
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-:-LHUXwFh5QMcRzTKGbHj:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/builder.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHUXt1U4PxhG6QIawxh:-LHUXt1U4PxhG6QIawxi:b-qqglo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cf8d264a78866520fdad7e9769e501fedc2a025/pkg/sql/opt/optbuilder/builder.go#L64)):*
> ```Go
> 	AllowImpureFuncs bool
> 
> 	// AllowBlacklistOps is a control knob: if set, when building a scalar, if a
> ```

Nice to see this go!
___
*[pkg/sql/opt/xform/rules/scan.opt, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHUTJJd7SpUxowzPR7m:-LHUTJJe-s7AX1H9DgpX:b6d02h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/77190674131d01cf292c2b93bf8f35e8f649ce85/pkg/sql/opt/xform/rules/scan.opt#L11)):*
> ```
> (Scan $def:* & (CanGenerateIndexScans $def)) => (GenerateIndexScans $def)
> 
> # GenerateInvertedIndexScans creates alternate expressions for filters that can
> ```

This should be in `select.opt`
___
*[pkg/sql/opt/xform/rules/scan.opt, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHUTL3yBmMKNvi270ja:-LHUTL3yBmMKNvi270jb:b-6hs33) ([raw file](https://github.com/cockroachdb/cockroach/blob/77190674131d01cf292c2b93bf8f35e8f649ce85/pkg/sql/opt/xform/rules/scan.opt#L15)):*
> ```
> [GenerateInvertedIndexScans, Explore]
> (Select
>   (Scan $def:* & (CanGenerateIndexScans $def))
> ```

Would be nice to have a more specific function, maybe `CanGenerateInvertedIndexScans`. Just so the rule doesn't match at all in the common case of no inverted indexes.
___
*[pkg/sql/opt/xform/testdata/rules/scan, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEpWau2izt7lxGZ5b4:-LHUWkHP6OpisVgnH-7p:bttq95n) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L631)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Weird, I thought the index join was gone here, but looking into it now I see that it's slightly involved to get rid of it, will look into that.
</blockquote></details>

I think you should leave a TODO here for this and explore a fix in a separate PR, since we've been going back and forth quite a bit on how to fix it.


<!-- Sent from Reviewable.io -->

2018-07-16 19:24 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/xform/testdata/rules/scan, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHEpWau2izt7lxGZ5b4:-LHZ2ekZ4KzONjzMd50g:b-8sik3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/77e04945ebc83712d61240862008180b62d8d831/pkg/sql/opt/xform/testdata/rules/scan#L631)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think you should leave a TODO here for this and explore a fix in a separate PR, since we've been going back and forth quite a bit on how to fix it.
</blockquote></details>

Done, agreed.
___
*[pkg/sql/opt/xform/rules/scan.opt, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHUTJJd7SpUxowzPR7m:-LHZ3lQi9A9VOo3m6SqJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77190674131d01cf292c2b93bf8f35e8f649ce85/pkg/sql/opt/xform/rules/scan.opt#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be in `select.opt`
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/rules/scan.opt, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHUTL3yBmMKNvi270ja:-LHZ3lot7xc7pblsLbEO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77190674131d01cf292c2b93bf8f35e8f649ce85/pkg/sql/opt/xform/rules/scan.opt#L15)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would be nice to have a more specific function, maybe `CanGenerateInvertedIndexScans`. Just so the rule doesn't match at all in the common case of no inverted indexes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-16 19:48 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-:-LHZce-c7K6X1SDdDQ6X:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHZc1Tg2Hn_pwbrJVNq:-LHZc1Th5wyD6JgZMFyz:b-vsich4) ([raw file](https://github.com/cockroachdb/cockroach/blob/35099047932e369028fb52e2d8095df306ae6983/pkg/sql/opt/xform/custom_funcs.go#L67)):*
> ```Go
> 	md := c.e.mem.Metadata()
> 	tab := md.Table(scanOpDef.Table)
> 	// Index 1 is the primary index and is never inverted.
> ```

Don't you mean Index 0? (Or maybe say "the first index")


<!-- Sent from Reviewable.io -->

2018-07-17 14:14 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-LHZc1Tg2Hn_pwbrJVNq:-LHc_o9M5p5nGDM-MMif:b-9v86yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/35099047932e369028fb52e2d8095df306ae6983/pkg/sql/opt/xform/custom_funcs.go#L67)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Don't you mean Index 0? (Or maybe say "the first index")
</blockquote></details>

Yes, fixed, good catch!


<!-- Sent from Reviewable.io -->

2018-07-17 15:11 UTC, justinj reviewed
@RaduBerinde any remaining concerns with this PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-:-LHckcUA5vpnxaLj3w12:b-v21vuc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-17 15:25 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-17 15:25 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27433#-:-LHcpvU8Eg5JZHpFmFiH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-07-17 17:13 UTC, justinj commented
Rebased (+ flake)

bors r+

2018-07-18 14:51 UTC, justinj commented
this is still a flake

bors r+

2018-07-18 15:14 UTC, merged