opt: Push null rejection filters below GroupBy operators
cockroachdb/cockroach pull request #27521
Opened 2018-07-13 20:01 UTC by andy-kimball

Null rejection filters can simplify outer joins into inner joins,
which is especially important for decorrelating subqueries. This
commit adds an additional RejectNullsGroupBy rule that is able to
push a synthesized null rejection filter like "col IS NOT NULL"
below a GroupBy operator in some special cases. This rule allows
all the TPCH and Hibernate queries to be fully decorrelated.

To enable this new rule to fire in decorrelation cases, additional
FDs for Apply operators need to be derived.

2018-07-13 20:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27521)
<!-- Reviewable:end -->

2018-07-16 18:51 UTC, rytaft requested changes
> This rule allows all the TPCH and Hibernate queries to be fully
> decorrelated.

🎉🎉🎉

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 9 of 9 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-:-LHZQG_x4DlNR_7WUaRb:b-rv43u4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYrCzK0RU6vct_oBOT:-LHYrCzK0RU6vct_oBOU:bary26p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/decorrelate.go#L188)):*
> ```Go
> 	for _, elem := range c.f.mem.LookupList(aggsExpr.Aggs()) {
> 		op := c.f.mem.NormExpr(elem).Operator()
> 		if op != opt.CountRowsOp && !opt.AggregateIgnoresNulls(op) {
> ```

isn't it enough to call `opt.AggregateIgnoresNulls`, since it should return false if op is `opt.CountRowsOp`?
___
*[pkg/sql/opt/norm/reject_nulls.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYrofQ9ebCfRGmD0AA:-LHYrofQ9ebCfRGmD0AB:bdqomh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/reject_nulls.go#L23)):*
> ```Go
> 
> // HasNullRejectingFilter returns true if the filter causes some of the columns
> // of input to be non-null. If the input contains columns (x, z), filters such
> ```

update the comment to change `input` to `nullRejectCols` (and explain what that means)
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZDtY60Nsh6JibpIup:-LHZDtY60Nsh6JibpIuq:buj866e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L213)):*
> ```Go
> 	//   3. No other input columns are referenced by other aggregate functions in
> 	//      the GroupBy (all functions must refer to the same column), with the
> 	//      exception of AnyNotNull, covered in #3.
> ```

I think you meant covered in #4
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZI0B87V66DH_XYRPx:-LHZI0B95xdz4CiD1-uK:b5iwwff) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rules/reject_nulls.opt#L25)):*
> ```
> #   SELECT min(b.y) FROM a LEFT JOIN b ON True GROUP BY a.x HAVING min(b.y)=1
> #
> # The min(b.y)=1 expression filters rows where min(z) is null, and because of
> ```

min(z) -> min(b.y)
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZIhFQ7d00wIhVurzQ:-LHZIhFR8iDGP9ELvcf_:b-3x3qft) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rules/reject_nulls.opt#L56)):*
> ```
> # Citations: [1]
> [RejectNullsLeftJoin, Normalize]
> (Select
> ```

Since these rules have moved out of `select.opt`, do we need to add a "high priority" flag to ensure that they are ordered before the predicate push-down rules?
___
*[pkg/sql/opt/norm/testdata/props/reject_nulls, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZLbnR4WPFmrckxBYy:-LHZLbnR4WPFmrckxBYz:bk423ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/testdata/props/reject_nulls#L355)):*
> ```
> 
> # Multiple aggregate functions on same column.
> opt
> ```

did you mean to make this `build` instead of `opt` to see the properties? Looks like the props disappeared after optimization.
___
*[pkg/sql/opt/norm/testdata/rules/reject_nulls, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZN0wkBIMnd5NZkEIe:-LHZN0wl3LAht68PKEJK:b-v50ec2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/testdata/rules/reject_nulls#L42)):*
> ```
>  └── true [type=bool]
> 
> # Can push to both sides with inner join.
> ```

This test doesn't seem to be related to null rejection... I must have forgotten to remove it before. 
___
*[pkg/sql/opt/props/func_dep.go, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYnPQpCZ0c5IoI0EcD:-LHYnPQpCZ0c5IoI0EcE:b-7j6sa2) ([raw file](https://github.com/cockroachdb/cockroach/blob/49469b6cd7f8bad91c59eacfdee1eb95915fdc9a/pkg/sql/opt/props/func_dep.go#L985)):*
> ```Go
> 			fd := &inner.deps[i]
> 			if fd.equiv {
> 				f.addDependency(fd.from, fd.to, fd.strict, fd.equiv)
> ```

should this dependency also be added if `f.hasKey` is false? (the comment above implies it should...)


<!-- Sent from Reviewable.io -->

2018-07-16 20:16 UTC, RaduBerinde reviewed
Great! Just some comments/questions for now, still digesting it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-:-LHZj1Jc7lRhHbPhoB6X:bqt9fxh)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rule_props_builder.go, line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZeQPTBwGZwBxhBDNC:-LHZeQPTBwGZwBxhBDND:b-sajny9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L214)):*
> ```Go
> 	//      the GroupBy (all functions must refer to the same column), with the
> 	//      exception of AnyNotNull, covered in #3.
> 	//   4. Ignore AnyNotNull aggregate if its input column is functionally
> ```

This isn't a criteria like the others, I think this just belongs under 3.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZfnfH2uSmcVSZa5u9:-LHZfnfH2uSmcVSZa5uA:b-xi46fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L222)):*
> ```Go
> 	var anyNotNullCols opt.ColSet
> 	var savedInColID opt.ColumnID
> 	for i := aggs.ChildCount() - 1; i >= 0; i-- {
> ```

why are we looping backwards?
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZepf_A-k2Mig0-IBw:-LHZepf_A-k2Mig0-IBx:b-cgxkrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L226)):*
> ```Go
> 		aggOp := agg.Operator()
> 		if aggOp == opt.AnyNotNullOp {
> 			// AnyNotNullOp shares a ColumnID with its input, so no need to dig
> ```

[nit] this seems like a fragile assumption (we may use it in other ways in the future)
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZg0UJ5jpb7o1sJDpN:-LHZg0UJ5jpb7o1sJDpO:b-6hcc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L232)):*
> ```Go
> 				continue
> 			}
> 			// Else column is not functionally determined by grouping columns, so
> ```

[nit] this branching logic would be more clear if this entire loop was in a helper function and we could just `return opt.ColSet{}` in the failed cases
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZhK2S6lRLyKC-QUSp:-LHZhK2S6lRLyKC-QUSq:b-3jlzta) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L233)):*
> ```Go
> 			}
> 			// Else column is not functionally determined by grouping columns, so
> 			// can't reject NULLs.
> ```

In this case, shouldn't we still check the other branch?  `AnyNotNull` has properties #1 and #2 so it could conceivably satisfy it. I realize this probably doesn't happen, but it would match better with the description above
___
*[pkg/sql/opt/props/func_dep.go, line 977 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZT0Su1QBY_IXATuOo:-LHZT0Su1QBY_IXATuOp:b-nrv3u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/49469b6cd7f8bad91c59eacfdee1eb95915fdc9a/pkg/sql/opt/props/func_dep.go#L977)):*
> ```Go
> // 4. Equivalence dependencies in the inner query still hold for the Apply
> //    operator.
> // 5. If each apply join input has a key, then the union of those keys forms a
> ```

Unclear here what "each join input" means. Isn't this just "if both the outer and the inner have keys, their concatenation is a key on the apply join result"?


<!-- Sent from Reviewable.io -->

2018-07-16 20:41 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/logical.go, line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZjy-I-4PiL3eKI4K-:-LHZjy-I-4PiL3eKI4K0:bao350o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/props/logical.go#L156)):*
> ```Go
> 
> 		// RejectNullCols is the subset of nullable output columns that can
> 		// potentially be made not-null by one of the RejectNull normalization
> ```

This is a bit of a circular definition, since understanding the RejectNull rule requires understanding `RejectNullCols`. It looks like this is not just a hint like PruneCols; initializing this has correctness implications, so we need to define it well. I am still trying to figure out what that definition is. The trouble is that it seems to mean different things on different operators - for joins, it's a "hint" for what columns we might care about, but for groupby it means that we determined that we can push down a null-rejection filter on that column.

The logic to initialize RejectNullCols for groupby feels more like what I'd expect to be in the match part of `RejectNullsGroupBy` rather than a logical property - have you considered that? The rule would not look at RejectNullCols for the groupby, but it would look at RejectNullCols for the groupby input; RejectNullCols becomes a "hint" that we set on outer joins.
___
*[pkg/sql/opt/props/logical.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZkGHA23pKsZZYcgu4:-LHZkGHA23pKsZZYcgu5:b-lgc8am) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/props/logical.go#L167)):*
> ```Go
> 		// tree a window into the structure of the tree several layers down. In
> 		// particular, the null rejection rules use this property to determine when
> 		// it's advantageous to synthesize a new filter. Without this information,
> ```

a new "IS NOT NULL" filter


<!-- Sent from Reviewable.io -->

2018-07-16 21:05 UTC, rytaft commented
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZtr5oDdXMxf7BZj_l:-LHZtr5oDdXMxf7BZj_m:bdn3f1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L158)):*
> ```Go
> 	relational.Rule.PruneCols.DifferenceWith(onProps.OuterCols)
> 
> 	// Null Rejection
> ```

Seems like a bunch of other operators should pass through `RejectNullCols` from their input. At least Select and Project.... 


<!-- Sent from Reviewable.io -->

2018-07-17 08:18 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/decorrelate.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYrCzK0RU6vct_oBOT:-LHab__D5O5KHMJaRuKq:b-yl8h9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/decorrelate.go#L188)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

isn't it enough to call `opt.AggregateIgnoresNulls`, since it should return false if op is `opt.CountRowsOp`?
</blockquote></details>

But we don't want `CountRows` returning `false` here. While it does not ignore nulls, we can map it to a function which does ignore nulls (i.e. `Count`).
___
*[pkg/sql/opt/norm/reject_nulls.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYrofQ9ebCfRGmD0AA:-LHadlQzBGOXcuHww7z4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/reject_nulls.go#L23)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update the comment to change `input` to `nullRejectCols` (and explain what that means)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZtr5oDdXMxf7BZj_l:-LHadp14C7qSFGtHIwjN:b-dmdm3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L158)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like a bunch of other operators should pass through `RejectNullCols` from their input. At least Select and Project.... 
</blockquote></details>

We could certainly expand this list, but my goal for this PR is to enable one particular case (GroupBy of Joins). Each additional case requires careful thought and work - there are subtle pitfalls that can cause incorrect rewrites and infinite loops, for example. I think it's best to leave that for future PRs.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZDtY60Nsh6JibpIup:-LHb39gT0Y1nLU5wv4KX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L213)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you meant covered in #4
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZeQPTBwGZwBxhBDNC:-LHb398T9OvIxXHrGuc5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L214)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This isn't a criteria like the others, I think this just belongs under 3.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZfnfH2uSmcVSZa5u9:-LHazBAT80-eytTkUfKW:bj0wkkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L222)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

why are we looping backwards?
</blockquote></details>

So we don't need to re-evaluate `ChildCount()` every time through the loop. I changed to use an `end` temp variable, which accomplishes the same thing.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZepf_A-k2Mig0-IBw:-LHbFYnW5D9XbUg16iTy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L226)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this seems like a fragile assumption (we may use it in other ways in the future)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZg0UJ5jpb7o1sJDpN:-LHbFZif-jATJ5VgqH-7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L232)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this branching logic would be more clear if this entire loop was in a helper function and we could just `return opt.ColSet{}` in the failed cases
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZhK2S6lRLyKC-QUSp:-LHazk226PN-juCwXo-7:bxpghu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L233)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In this case, shouldn't we still check the other branch?  `AnyNotNull` has properties #1 and #2 so it could conceivably satisfy it. I realize this probably doesn't happen, but it would match better with the description above
</blockquote></details>

I don't want to allow that case, since I can't test it. It's always safe to just disallow null rejection. I changed the comment to reflect.
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZI0B87V66DH_XYRPx:-LHag5yqAwzJ3ZK6xIF-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rules/reject_nulls.opt#L25)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

min(z) -> min(b.y)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/reject_nulls.opt, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZIhFQ7d00wIhVurzQ:-LHagu08146sOt3ZMfZh:bq7anv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rules/reject_nulls.opt#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Since these rules have moved out of `select.opt`, do we need to add a "high priority" flag to ensure that they are ordered before the predicate push-down rules?
</blockquote></details>

Hmm, good point. It still runs first after my change because `reject_nulls.opt` is before `select.opt` in alphabetical order. But better to be explicit.
___
*[pkg/sql/opt/norm/testdata/props/reject_nulls, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZLbnR4WPFmrckxBYy:-LHaoIkf4cmTwzqXMxXv:b5r7772) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/testdata/props/reject_nulls#L355)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

did you mean to make this `build` instead of `opt` to see the properties? Looks like the props disappeared after optimization.
</blockquote></details>

Yes, should be `build`, since that's easier to understand (though `opt` also shows we did right thing, since `left-join` became `inner-join`).
___
*[pkg/sql/opt/norm/testdata/rules/reject_nulls, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZN0wkBIMnd5NZkEIe:-LHaonE0E6-VoE3ugyGc:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/testdata/rules/reject_nulls#L42)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This test doesn't seem to be related to null rejection... I must have forgotten to remove it before. 
</blockquote></details>

Remo [...]

2018-07-17 13:10 UTC, rytaft requested changes
> Reviewed 22 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/decorrelate.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHYrCzK0RU6vct_oBOT:-LHcGQbM0fj_7FA9TOfp:b5vjmdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/decorrelate.go#L188)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

But we don't want `CountRows` returning `false` here. While it does not ignore nulls, we can map it to a function which does ignore nulls (i.e. `Count`).
</blockquote></details>

Got it - thanks!
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHZtr5oDdXMxf7BZj_l:-LHcGfn11Rblzd1WXZwx:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8632f514fe3b4dd14baca0cdd4a4f5f549836533/pkg/sql/opt/norm/rule_props_builder.go#L158)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We could certainly expand this list, but my goal for this PR is to enable one particular case (GroupBy of Joins). Each additional case requires careful thought and work - there are subtle pitfalls that can cause incorrect rewrites and infinite loops, for example. I think it's best to leave that for future PRs.
</blockquote></details>

Ok!
___
*[pkg/sql/opt/norm/rule_props_builder.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHcIRPe2p8YEOAqBlwA:-LHcIRPf8Dgw_hne1NxH:b-w2la7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d586fe27ed5302b16f560dced44533652d4707e/pkg/sql/opt/norm/rule_props_builder.go#L278)):*
> ```Go
> //      by #1, the presence of nulls does not alter the result, the aggregate
> //      function would return null if its input contains only null values.
> //   3. The aggregate function is not AnyNotNull.
> ```

Reading this again, I don't really see why the aggregate function can't be `AnyNotNull`. Doesn't this function do just what we want? It ignores input Nulls, and returns Null if the input is empty. You could still ignore it if the input column is functionally determined by the group by cols and there is another aggregate satisfying the criteria, but otherwise, why not pass along the null rejection request?


<!-- Sent from Reviewable.io -->

2018-07-17 13:54 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rule_props_builder.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHcIRPe2p8YEOAqBlwA:-LHcVw8T-jN-3zhmQmeb:bcx8n8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d586fe27ed5302b16f560dced44533652d4707e/pkg/sql/opt/norm/rule_props_builder.go#L278)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Reading this again, I don't really see why the aggregate function can't be `AnyNotNull`. Doesn't this function do just what we want? It ignores input Nulls, and returns Null if the input is empty. You could still ignore it if the input column is functionally determined by the group by cols and there is another aggregate satisfying the criteria, but otherwise, why not pass along the null rejection request?
</blockquote></details>

Because `AnyNotNull` is only added as a side-effect of other rules, and we'd have no way to test it in this context. If I can't test something, the next best thing is to exclude it. I can add a sentence explaining why we're not allowing it.


<!-- Sent from Reviewable.io -->

2018-07-17 14:12 UTC, rytaft approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rule_props_builder.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHcIRPe2p8YEOAqBlwA:-LHc_479DYJnMW3FkUNN:b-qfo22g) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d586fe27ed5302b16f560dced44533652d4707e/pkg/sql/opt/norm/rule_props_builder.go#L278)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Because `AnyNotNull` is only added as a side-effect of other rules, and we'd have no way to test it in this context. If I can't test something, the next best thing is to exclude it. I can add a sentence explaining why we're not allowing it.
</blockquote></details>

Sounds good -- adding this info to the comment would help.


<!-- Sent from Reviewable.io -->

2018-07-17 15:25 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-:-LHcqEb9EiEJ7kHJ6reI:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-07-18 15:13 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rule_props_builder.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27521#-LHcIRPe2p8YEOAqBlwA:-LHhwenL1bQB9FfvZc5x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d586fe27ed5302b16f560dced44533652d4707e/pkg/sql/opt/norm/rule_props_builder.go#L278)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Sounds good -- adding this info to the comment would help.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-18 15:16 UTC, rytaft approved these changes
> Reviewed 4 of 26 files at r5, 22 of 22 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27521)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-07-18 15:43 UTC, andy-kimball commented
bors r+

2018-07-18 16:16 UTC, merged