opt: enforce FDs on distinct counts
cockroachdb/cockroach pull request #27619
Opened 2018-07-16 20:11 UTC by madhavsuresh

A dependent of a functional dependency can not
have more distinct rows than it's determinant.
This PR enforces that logic.

Release note: None

2018-07-16 20:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27619)
<!-- Reviewable:end -->

2018-07-16 20:51 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Just some nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-:-LHZrDuJ5zs4hPDxbahw:b-sm2mzh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZpuonBMCdLvzeRpdC:-LHZpuonBMCdLvzeRpdD:bb7ruv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/statistics_builder.go#L1058)):*
> ```Go
> 					if sb.colStat(util.MakeFastIntSet(dep)).DistinctCount >
> 						sb.colStat(util.MakeFastIntSet(col)).DistinctCount {
> 						//update distinct count for column
> ```

[nit] `// Update distinct count for column.`
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZqZLX0xdNXeKPoPxA:-LHZqZLX0xdNXeKPoPxB:bf5yb8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L135)):*
> ```
> 
> opt
> SELECT x,y FROM a where y=1 AND x > 0 AND x <= 7
> ```

`x, y` and `WHERE y = 1`
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZq_I01F2zkANHmOxc:-LHZq_I01F2zkANHmOxd:b3kjjvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L155)):*
> ```
> # Test enforceFDOnDistinctCounts
> opt
> SELECT x,y FROM a where x=1 AND y > 0 AND y <= 7
> ```

`x, y` and`WHERE x = 1`


<!-- Sent from Reviewable.io -->

2018-07-16 20:52 UTC, justinj reviewed
commit message grammar nit: `it's` -> `its`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-:-LHZibQaAVFSHkW_8fDK:bcadldj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1056 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZqs8yEu836yGNqPSB:-LHZqs8yEu836yGNqPSC:b-4rkyzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa11bb0237d0b382278e51336755ab855a3a4b0c/pkg/sql/opt/memo/statistics_builder.go#L1056)):*
> ```Go
> 			if _, ok := sb.s.ColStats[opt.ColumnID(col)]; ok {
> 				if _, okDep := sb.s.ColStats[opt.ColumnID(dep)]; okDep {
> 					if sb.colStat(util.MakeFastIntSet(dep)).DistinctCount >
> ```

shouldn't the first return value of `sb.s.ColStats[opt.ColumnID(col)]` be the same as `sb.colStat(util.MakeFastIntSet(col))` (and same with `dep`)?


<!-- Sent from Reviewable.io -->

2018-07-16 20:53 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-:-LHZrRMkCG9MJ_BGtLY0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZo1hE-AtANyvkQa74:-LHZo1hE-AtANyvkQa75:b-7zj3u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/statistics_builder.go#L1059)):*
> ```Go
> 						sb.colStat(util.MakeFastIntSet(col)).DistinctCount {
> 						//update distinct count for column
> 						sb.ensureColStat(opt.ColumnID(dep), sb.colStat(util.MakeFastIntSet(col)).DistinctCount, inputStatsBuilder)
> ```

[nit] I'd assign `sb.colStat(util.MakeFastIntSet(col)).DistinctCount` to a variable above so you don't need to call it twice. Maybe also assign `sb.colStat(util.MakeFastIntSet(dep)).DistinctCount` to a variable to make it symmetric and more readable.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZotFu0n7q0ScZdik4:-LHZotFu0n7q0ScZdik5:b-dxcs78) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L135)):*
> ```
> 
> opt
> SELECT x,y FROM a where y=1 AND x > 0 AND x <= 7
> ```

[nit] it's a bit tricky to tell if the expected output is correct. I'm not sure there's anything to be done at this point since you haven't updated the selectivity logic yet, but maybe you could play around with using different stats and/or larger range predicates to try to get the distinct counts to be different from each other?

It would also help to add a comment to explain how this test case is different from the next one.


<!-- Sent from Reviewable.io -->

2018-07-16 20:59 UTC, rytaft commented
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZo1hE-AtANyvkQa74:-LHZsqqF359kCOqHNMTi:b-2iyo8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/statistics_builder.go#L1059)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'd assign `sb.colStat(util.MakeFastIntSet(col)).DistinctCount` to a variable above so you don't need to call it twice. Maybe also assign `sb.colStat(util.MakeFastIntSet(dep)).DistinctCount` to a variable to make it symmetric and more readable.
</blockquote></details>

Ignore this -- Justin's comment is correct.


<!-- Sent from Reviewable.io -->

2018-07-16 21:21 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1058 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZpuonBMCdLvzeRpdC:-LHZss-3CKsbJ9t_gC94:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/statistics_builder.go#L1058)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `// Update distinct count for column.`
</blockquote></details>

Done
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1059 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZo1hE-AtANyvkQa74:-LHZw2ho4b54qJ8Wp2m-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/statistics_builder.go#L1059)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ignore this -- Justin's comment is correct.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1056 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZqs8yEu836yGNqPSB:-LHZw3fA6vzwhsMcgHjg:ba4ksat) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa11bb0237d0b382278e51336755ab855a3a4b0c/pkg/sql/opt/memo/statistics_builder.go#L1056)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

shouldn't the first return value of `sb.s.ColStats[opt.ColumnID(col)]` be the same as `sb.colStat(util.MakeFastIntSet(col))` (and same with `dep`)?
</blockquote></details>

Yup, thanks for catching that. Done.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZqZLX0xdNXeKPoPxA:-LHZsqKiDLu3G5YpXgfh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L135)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`x, y` and `WHERE y = 1`
</blockquote></details>

Done
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZotFu0n7q0ScZdik4:-LHZxk_r0rdyT_JiO7Ob:b-xzqyd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L135)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] it's a bit tricky to tell if the expected output is correct. I'm not sure there's anything to be done at this point since you haven't updated the selectivity logic yet, but maybe you could play around with using different stats and/or larger range predicates to try to get the distinct counts to be different from each other?

It would also help to add a comment to explain how this test case is different from the next one.
</blockquote></details>

Yea I agree, the output is not intuitive. I will add more test cases. 
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZq_I01F2zkANHmOxc:-LHZspnC2tZmgS76zLUN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f17318aee8fd4b1c39b47fedc65b25a5b4e69b6/pkg/sql/opt/memo/testdata/stats/scan#L155)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`x, y` and`WHERE x = 1`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-07-16 21:33 UTC, rytaft requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1057 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzHrBCaAcJ6aLQHQ_:-LHZzHrBCaAcJ6aLQHQa:b-ea7liw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/statistics_builder.go#L1057)):*
> ```Go
> 				if depStats, okDep := sb.s.ColStats[opt.ColumnID(dep)]; okDep {
> 					if depStats.DistinctCount > detStats.DistinctCount {
> 						// Update distinct count for column
> ```

[nit] add period.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZyun1B1MsBKCQWQ5O:-LHZyun22zGa1DjyHmw_:b-5ptwzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L155)):*
> ```
> # Test enforceFDOnDistinctCounts.
> # x is a primary key, and thus this equality constraint
> # has one distinct value. Since y is a (fd) determinant of x,
> ```

Don't you mean x is a determinant of y (y is the dependant)? And the distinct count on x needs to be pushed to y.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZz5UVDzyj_ce-aMmV:-LHZz5UWDwyhkkOiHYid:bdm4nxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L157)):*
> ```
> # has one distinct value. Since y is a (fd) determinant of x,
> # the distinct count on y needs to be pushed onto x.
> ```

[nit] extra space
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzVdTCuggNhuO3U8z:-LHZzVdTCuggNhuO3U9-:b-jjbh7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L159)):*
> ```
> 
> opt
> SELECT x,y FROM a where x=1 AND y > 0 AND y <= 7
> ```

[nit] where -> WHERE (and above too)
___
*[pkg/sql/opt/memo/testdata/stats/select, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzdF99zzaXZarom50:-LHZzdF99zzaXZarom51:bk9g7dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/select#L408)):*
> ```
> 
> opt
> SELECT x,y FROM a WHERE y=1 AND x > 0 AND x <= 7
> ```

Why did you duplicate the test cases here? I think `select` is actually the right place for them, so I'd remove them from `scan`.
___
*[pkg/sql/opt/memo/testdata/stats/select, line 426 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzxzt8OYAEV7Xkcrv:-LHZzxzt8OYAEV7Xkcrw:b-vok159) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/select#L426)):*
> ```
>            └── const: 1 [type=int]
> 
> # Test enforceFDOnDistinctCounts.
> ```

[nit] I'd move this title above the previous test case so you can explain that the previous case is showing when the rule *does not* apply


<!-- Sent from Reviewable.io -->

2018-07-16 21:39 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1057 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzHrBCaAcJ6aLQHQ_:-LH_0wqq0-25qIlNa2Sq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/statistics_builder.go#L1057)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] add period.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/select, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzdF99zzaXZarom50:-LH_0xW5EeDm1eGLu9b8:b-yko8lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/select#L408)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you duplicate the test cases here? I think `select` is actually the right place for them, so I'd remove them from `scan`.
</blockquote></details>

Ah yea, this push has them removed from scan. They were meant to just be in select. 
___
*[pkg/sql/opt/memo/testdata/stats/select, line 426 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzxzt8OYAEV7Xkcrv:-LH_11D--ioMYVi_X8Mv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/select#L426)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'd move this title above the previous test case so you can explain that the previous case is showing when the rule *does not* apply
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZyun1B1MsBKCQWQ5O:-LH_12EbEqXJK5vDotlH:b-j7a1nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L155)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Don't you mean x is a determinant of y (y is the dependant)? And the distinct count on x needs to be pushed to y.
</blockquote></details>

Yikes, thanks for catching this. Yes, that is what I meant!
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZz5UVDzyj_ce-aMmV:-LH_14bGEuhK0cXarrM0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L157)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra space
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LHZzVdTCuggNhuO3U8z:-LH_158M2JFlFvYw0dxm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1253bdbe1fecc220116bd7b71efa6e98d5148d0/pkg/sql/opt/memo/testdata/stats/scan#L159)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] where -> WHERE (and above too)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-16 23:25 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1043 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_HOD47a4dKBSusNrY:-LH_HOD50xdIUljvAsjw:blyldj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/statistics_builder.go#L1043)):*
> ```Go
> 	}
> 
> 	sb.enforceFDOnDistinctCounts(inputStatsBuilder)
> ```

Why is this the right place to analyze FD's? As far as I can see, `applyConstraint` is called only for the `Scan` operator. Is that your intent? What about `Select` and `Join`?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1051 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_IpX3ET6YyIWZIn4_:-LH_IpX3ET6YyIWZIn4a:b-j06m6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/statistics_builder.go#L1051)):*
> ```Go
> 	fd := inputStatsBuilder.props.FuncDeps
> 	outputCols := inputStatsBuilder.props.OutputCols
> 	outputCols.ForEach(func(det int) {
> ```

This algorithm seems costly. We end up computing 1 closure per output column (could be many of those), and then 2 lookups per dependant in the resulting closures. Did you consider something like this instead:

Each time a new `ColStat` is lazily added to a `Statistic`, loop over the other `ColStat`s. For any other `ColStat` that has a lower distinct count, check to see if the new `ColStat` is functionally determined by the other `ColStat`. There should be very few `ColStat`s in a given statistic, so O(N**2) isn't nearly as bad here. Furthermore, this would handle `ColStat`s with multiple columns, which your current logic does not handle.

Note that I may not have that quite right; it's coming from my "fast" intuition and I haven't verified it. But I want to make sure we've thought through each alternate possibilities and rejected them for good reasons.
___
*[pkg/sql/opt/memo/testdata/stats/select, line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_KWha7FHmydOIikM8:-LH_KWha7FHmydOIikM9:b-ndm15g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/testdata/stats/select#L434)):*
> ```
> # the distinct count on x needs to be pushed onto y.
> opt
> SELECT x,y FROM a WHERE x=1 AND y > 0 AND y <= 7
> ```

This is not a great example, because there's only 1 row max to begin with. I'd change it so that you're not operating on key columns and there are multiple rows. In general, you need more tests that show more interesting cases. I'd probably create another table with more than 2 columns and possibly a multi-col key, as it's hard to make interesting examples with only 2 columns, where 1 of them is a key.


<!-- Sent from Reviewable.io -->

2018-07-17 01:03 UTC, rytaft reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1043 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_HOD47a4dKBSusNrY:-LH_fZXf8bGd1_8J_kAf:b-6j1w6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/statistics_builder.go#L1043)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why is this the right place to analyze FD's? As far as I can see, `applyConstraint` is called only for the `Scan` operator. Is that your intent? What about `Select` and `Join`?
</blockquote></details>

Looks like it's getting called both here and below in `applyConstraintSet`, which is called by `Select` (`Join` doesn't call that yet but it still has a lot of TODOs).  But I agree (also discussed in the comment below) that `enforceFDOnDistinctCounts` should also be called when a new `colSet` is added via a call to `colStat`.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1051 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_IpX3ET6YyIWZIn4_:-LH_coCWC16xCRMWRN0P:bqcz6j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/statistics_builder.go#L1051)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This algorithm seems costly. We end up computing 1 closure per output column (could be many of those), and then 2 lookups per dependant in the resulting closures. Did you consider something like this instead:

Each time a new `ColStat` is lazily added to a `Statistic`, loop over the other `ColStat`s. For any other `ColStat` that has a lower distinct count, check to see if the new `ColStat` is functionally determined by the other `ColStat`. There should be very few `ColStat`s in a given statistic, so O(N**2) isn't nearly as bad here. Furthermore, this would handle `ColStat`s with multiple columns, which your current logic does not handle.

Note that I may not have that quite right; it's coming from my "fast" intuition and I haven't verified it. But I want to make sure we've thought through each alternate possibilities and rejected them for good reasons.
</blockquote></details>

I think that's a good point about updating the `ColStat`s when they are added -- we probably need to call a function like this in the `colStat` functions as well.  And changing the algorithm to reduce the calls to `ComputeClosure` also makes sense.

But I do think we need to update all the existing elements of `ColStats` here, since we'll need correct distinct counts to calculate selectivity, and these distinct counts won't get recalculated later (also, there won't be that many -- at most as many columns as were part of the constraint set).


<!-- Sent from Reviewable.io -->

2018-07-17 15:12 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1051 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_IpX3ET6YyIWZIn4_:-LHcac4FDsdwDFOEkJBJ:bpoxite) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/statistics_builder.go#L1051)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think that's a good point about updating the `ColStat`s when they are added -- we probably need to call a function like this in the `colStat` functions as well.  And changing the algorithm to reduce the calls to `ComputeClosure` also makes sense.

But I do think we need to update all the existing elements of `ColStats` here, since we'll need correct distinct counts to calculate selectivity, and these distinct counts won't get recalculated later (also, there won't be that many -- at most as many columns as were part of the constraint set).
</blockquote></details>

I hadn't considered that alternative. I agree that the given algorithm is costly and a bit naive. What you propose makes a lot of sense. I think localizing distinctCount updates to a single code path also makes sense from a code organization perspective. 

Is there a better way to get a determinant->dependent mapping? It seems like a common question in the stats code is going to be "given col a, what are it's dependents". 

I think your proposed algorithm makes sense, an alternative could be 
-when updating distinct count, find all determinants of the col
-find min of all determinants distinct count, if min is lower than col distinct count, update. 

I don't think it matters for this simple case, but generally, how do we determine which algorithm to use. So far, there are three proposed alternatives, and each will perform different based on the query and schema. Perhaps there is one that will perform better over a large fraction of queries and schemas. Is there a principled approach to determining which algorithm to choose? 
___
*[pkg/sql/opt/memo/testdata/stats/select, line 434 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-LH_KWha7FHmydOIikM8:-LHcmy-q7jmZ95qtNh5g:bsuvemb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf42ab74e0f34dc456a4c50821a45501b249957/pkg/sql/opt/memo/testdata/stats/select#L434)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is not a great example, because there's only 1 row max to begin with. I'd change it so that you're not operating on key columns and there are multiple rows. In general, you need more tests that show more interesting cases. I'd probably create another table with more than 2 columns and possibly a multi-col key, as it's hard to make interesting examples with only 2 columns, where 1 of them is a key.
</blockquote></details>

Working on updating the test cases. 


<!-- Sent from Reviewable.io -->

2018-07-20 22:05 UTC, madhavsuresh reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-:-LHtiUEu9Twm2bT9EmPp:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-07-20 22:12 UTC, madhavsuresh reviewed
Scratch that! All the test cases didn't push. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27619#-:-LHtk4yF8_j80QTuKY8l:b-6kmx7g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2020-04-27 17:31 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=27619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=27619) before we can accept your contribution.<br/><hr/>**madhavsuresh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=27619) it.</sub>

2020-04-27 18:45 UTC, closed without merging

2020-04-27 19:13 UTC, jordanlewis commented
@madhavsuresh 

![](https://media2.giphy.com/media/rHR8qP1mC5V3G/source.gif)