storageccl: track which external APIs are most used
cockroachdb/cockroach pull request #27654
Opened 2018-07-17 19:42 UTC by dt

When polishing or optimizing support for a external storage providers
like S3 or Azure, it will be helpful to know which ones see the most
usage. Since the storage URIs are obviously scrubbed from the queries in
telemetry, this was previously difficult to track.

Release note: none.

2018-07-17 19:49 UTC, madelynnblue approved these changes

2018-07-17 19:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27654)
<!-- Reviewable:end -->

2018-07-18 14:23 UTC, knz requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27654)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/storageccl/export_storage.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27654#-LHhlFhV3FmTUGwCyScs:-LHhlFhW7HCc5opPykOB:b-p56uaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec172934731a770de2df193ea4bd02faf62f463/pkg/ccl/storageccl/export_storage.go#L184)):*
> ```Go
> 	switch dest.Provider {
> 	case roachpb.ExportStorageProvider_LocalFile:
> 		telemetry.Count("external-io.nodelocal")
> ```

huh

I thought we had agreed the interface should be 

- at the top level:

`var countVar = telemetry.Counter(...)`

- and at every point of use

`countVar.Inc()`

to avoid a map lookup on every use!


<!-- Sent from Reviewable.io -->

2018-07-18 14:35 UTC, dt commented
@knz we agreed on that *for performance/contention-sensitive callers*. 

These are to external storage IO, used in bulk IO like BACKUP and RESTORE -- the cost of a mutex around a map lookup is inconsequential compared to the moving gigabytes to/from cloud storage, so I don't think that pattern is required here, and the simple direct `Count()` call is the easiest to read.

2018-07-18 14:44 UTC, knz commented
> @knz we agreed on that for performance/contention-sensitive callers.

I am not keen on having two APIs. This will place the onus on individual engineers to make an educated guess as to whether something is perf sensistive or not. This seems unreasonable.

2018-07-18 14:51 UTC, dt commented
That feels like premature optimization to me -- this form is simple, clear and readable. Yes, we have an API for callers who actually need to trade some simplicity to eliminate per-increment overhead, but I don't think we should force everyone to use it just because some call sites will need it.

2018-07-18 15:00 UTC, dt commented
Also, until we actually see any contention and/or lookup overhead show up in a profile, I think we should stick with the quick, simple and readable version -- as long as the underlying design allows for that later optimization *when the need arises*. I think we've done that here -- we built our API such that that optimization is possible (and even relatively easy), but I don't think that means we need to apply it everywhere right away until we see evidence to the contrary.

2018-07-23 14:50 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27654#-:-LI6bjWTEbP-pFsp52q-:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-23 14:51 UTC, dt commented
bors r+

2018-07-23 16:35 UTC, merged