[WIP] storage: removing use of engine.NewSnapshot()
cockroachdb/cockroach pull request #27713
Opened 2018-07-18 16:58 UTC by petermattis

RocksDB snapshots touch interesting and different code paths inside of
RocksDB. In particular, snapshots change compaction logic so that
versions on either side of the snapshot are retained. RocksDB iterators
already provide snapshot-like functionality, but do so in a different
fashion by maintaining a reference to the sstables that exited at the
time they were created (and the memtables). The downside to using
iterators for snapshots is that they pin both the sstables and memtables
for their lifetime, so they are best suited for short lifetimes.

Most uses of snapshots can be easily replaced by
engine.NewReadOnly(). The snapshot used by storage.OutgoingSnapshot
deserved attention because it can be held until the snapshot is
sent. But notice that OutgoingSnapshot already held open an iterator on
the snapshot which has the same pinning behavior as a normal iterator.

Release note: None

2018-07-18 16:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27713)
<!-- Reviewable:end -->

2018-07-18 17:00 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHiKFh47UDCPWaQcjAS:br2c4yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
> ```Go
> 	//
> 	//     consistency_queue_test.go:376: stats still in need of adjustment: {ContainsEstimates:false LastUpdateNanos:0 IntentAge:0 GCBytesAge:0 LiveBytes:45 LiveCount:1 KeyBytes:33 KeyCount:1 ValBytes:12 ValCount:1 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
> 	readonly := cArgs.EvalCtx.Engine().NewReadOnly()
> ```

@tschottdorf I'm very surprised that this doesn't work. It should work. Do you have any insights? I've verified that the only methods called on the read-only engine are `NewIterator` and `Close`. 
___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKQlS8NgmAO0rgrEj:-LHiKQlS8NgmAO0rgrEk:b-mde3gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L102)):*
> ```Go
> 		})
> 		iter.Close()
> 	}
> ```

I'll get rid of this hack before merging. This is a WIP.


<!-- Sent from Reviewable.io -->

2018-07-18 18:34 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHieGjz0ZTgmGj2_tlg:bf59gd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@tschottdorf I'm very surprised that this doesn't work. It should work. Do you have any insights? I've verified that the only methods called on the read-only engine are `NewIterator` and `Close`. 
</blockquote></details>

The only explanation I have is that iterators may not work the way snapshots do. That is, in the sequence `A; Batch(Put(k), Put(stats)); A.Read(k) Batch(Put(l), Put(stats)), A.Read(stats)` it matters whether `A` is `CreateSnapshot` or `CreateIterator`.  I assume the iterator sees the second batch even though a snapshot wouldn't. A unit test would show.


<!-- Sent from Reviewable.io -->

2018-07-18 18:35 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHif9g968PaZH7QfqPT:bm2hbfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The only explanation I have is that iterators may not work the way snapshots do. That is, in the sequence `A; Batch(Put(k), Put(stats)); A.Read(k) Batch(Put(l), Put(stats)), A.Read(stats)` it matters whether `A` is `CreateSnapshot` or `CreateIterator`.  I assume the iterator sees the second batch even though a snapshot wouldn't. A unit test would show.
</blockquote></details>

Oops, the example should `A.read(stats)` first. Anyway, you get the idea. If the iterator doesn't see a consistent snapshot, this test failure is expected.


<!-- Sent from Reviewable.io -->

2018-07-18 20:32 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHj4X491S3D-IxLzv56:btdsgxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Oops, the example should `A.read(stats)` first. Anyway, you get the idea. If the iterator doesn't see a consistent snapshot, this test failure is expected.
</blockquote></details>

The iterator sees a consistent snapshot, or my understanding of RocksDB is really broken. I'll figure out what is going on here.


<!-- Sent from Reviewable.io -->

2018-07-19 00:39 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHjxbDhARok0snZPsEw:b-9u2hc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The iterator sees a consistent snapshot, or my understanding of RocksDB is really broken. I'll figure out what is going on here.
</blockquote></details>

Ah-ha! `ComputeStatsForRange` uses a normal iterator while `MakeStateLoader` uses a prefix iterator. These are two different iterators (see the loop to initialize them below) created at slightly different times and that is enough for the concurrent writes being performed by the test to sneak in. I need to have `MakeStateLoader` use the same iterator as `ComputeStatsForRange`, which isn't difficult, just a bit of plumbing. I think this same problem affects some of the other uses of `NewReadOnly` in this PR. Perhaps the right thing to do is to leave `NewSnapshot` and have that return an engine that uses the same iterator for normal and prefix iteration. 

PS Thank you for `TestConsistencyQueueRecomputeStats`. This would have been nasty to track down in the wild. 


<!-- Sent from Reviewable.io -->

2018-07-19 00:42 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/gc_queue.go, line 577 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHjyvvaBHY3mWZgY4b9:-LHjyvvaBHY3mWZgY4bA:bh6u4cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/gc_queue.go#L577)):*
> ```Go
> 	// RunGC has an open ReplicaDataIterator while it calls MVCCIterate (via
> 	// processLocalKeyRange).
> 	readonly := repl.store.Engine().NewSnapshot()
> ```

This is the other remaining use of `NewSnapshot()`. No fundamental reason it can't be fixed. 


<!-- Sent from Reviewable.io -->

2018-07-19 04:39 UTC, tbg requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/gc_queue_test.go, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkoA7q2QvJe3mke6eg:-LHkoA7q2QvJe3mke6eh:b-83xmmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/gc_queue_test.go#L500)):*
> ```Go
> 	gcInfo, err := func() (GCInfo, error) {
> 		// TODO(peter): this should be NewReadOnly().
> 		readonly := tc.repl.store.Engine().NewSnapshot()
> ```

`readonly` tickles my OCD as it should be `readOnly`.
___
*[pkg/storage/replica_proposal.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkoNkWEp_YMb1jaNR8:-LHkoNkX95Z8tD5J7bcC:b268quv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/replica_proposal.go#L181)):*
> ```Go
> 	// (i.e. not in the middle of an AddSSTable).
> 	readonly := r.store.engine.NewReadOnly()
> 	// This is somewhat hacky: because we're using the readonly engine from a
> ```

Yeah, this looks too hacky. Can you pass the iterator over into the goroutine? That's still not super pretty, but better than relying on magic internal caching properties.
___
*[pkg/storage/replica_raftstorage.go, line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkobVJC8hpDmduvVUL:-LHkobVJC8hpDmduvVUM:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/replica_raftstorage.go#L384)):*
> ```Go
> 	r.raftMu.Lock()
> 	snap := r.store.engine.NewReadOnly()
> 	// This is somewhat hacky: the readonly engine caches the iterator. We want
> ```

Ditto.
___
*[pkg/storage/replica_raftstorage.go, line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkodYT5M7psvfOZQt7:-LHkodYT5M7psvfOZQt8:b-spw9ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/replica_raftstorage.go#L452)):*
> ```Go
> // Close releases the resources associated with the snapshot.
> func (s *OutgoingSnapshot) Close() {
> 	if s.Iter != nil {
> ```

Why is this necessary now? Ah, I see. New code in store_snapshot.go.
___
*[pkg/storage/store_snapshot.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkogF59wGYZBklhPie:-LHkogF59wGYZBklhPif:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/store_snapshot.go#L225)):*
> ```Go
> 	rangeID := header.State.Desc.RangeID
> 
> 	// NB: close the replica data iterator before iterating over the entries in
> ```

Ditto
___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHiKFh32_lJ3EdQvQnR:-LHkov-P-yH2vjAXs1jK:b-a62l7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah-ha! `ComputeStatsForRange` uses a normal iterator while `MakeStateLoader` uses a prefix iterator. These are two different iterators (see the loop to initialize them below) created at slightly different times and that is enough for the concurrent writes being performed by the test to sneak in. I need to have `MakeStateLoader` use the same iterator as `ComputeStatsForRange`, which isn't difficult, just a bit of plumbing. I think this same problem affects some of the other uses of `NewReadOnly` in this PR. Perhaps the right thing to do is to leave `NewSnapshot` and have that return an engine that uses the same iterator for normal and prefix iteration. 

PS Thank you for `TestConsistencyQueueRecomputeStats`. This would have been nasty to track down in the wild. 
</blockquote></details>

Either way works for me, but the resulting code should be free of hacks. It seems hard to manage multiple iterators because you have no way to force them to see the same "snapshot".
___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkpEaVEZF4k_GT1gsi:-LHkpEaVEZF4k_GT1gsj:b-5vecsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L96)):*
> ```Go
> 	// TODO(peter): probably better to add a flag to NewReadOnly() to do this. Or
> 	// perhaps NewSnapshot() should do this internally.
> 	for _, prefix := range [2]bool{false, true} {
> ```

But this isn't enough, right? They're still seeing different snapshots...


<!-- Sent from Reviewable.io -->

2018-07-19 11:35 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27713)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_recompute_stats.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27713#-LHkpEaVEZF4k_GT1gsi:-LHmJOGw00fnxGgkXOzQ:bx4evkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f06eceef8cd6654065994b0f9e22695b25382fe/pkg/storage/batcheval/cmd_recompute_stats.go#L96)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

But this isn't enough, right? They're still seeing different snapshots...
</blockquote></details>

I haven't uploaded a fix. My comments above were about diagnosing the problem.


<!-- Sent from Reviewable.io -->

2018-07-31 16:10 UTC, petermattis commented
There isn't any urgency to this PR, so I'm going to close it for now as I won't have time in the near future to finish it off.

2018-07-31 16:10 UTC, closed without merging