sql,  opt: support SRFs in the SELECT list
cockroachdb/cockroach pull request #27773
Opened 2018-07-19 23:47 UTC by rytaft

This PR contains two commits:

1. Change the return type of single-column generator functions to be the type of the column rather than tuple{column type}. This matches Postgres behavior and is necessary to support SRFs in the optbuilder.
2. Add support for SRFs in the optimizer. 

See the commit messages for more details.

2018-07-19 23:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27773)
<!-- Reviewable:end -->

2018-07-20 01:34 UTC, RaduBerinde reviewed
:1st_place_medal: 

Looked over the 2nd commit, just some nits. Very clean change!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-:-LHpIPyR5AlUAHHBgCkX:b9ajqyb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/project.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpIKCFBIrUtAcEk7mw:-LHpIKCFBIrUtAcEk7mx:b-sybcdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/project.go#L84)):*
> ```Go
> 	defer func(replaceSRFs bool) { inScope.replaceSRFs = replaceSRFs }(inScope.replaceSRFs)
> 
> 	b.semaCtx.Properties.Require("SELECT", tree.RejectNestedGenerators)
> ```

This infrastructure is great! :100: @knz
___
*[pkg/sql/opt/optbuilder/scalar.go, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpIa8C0MMI6aoMbjtR:-LHpIa8C0MMI6aoMbjtS:b-1y9xwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scalar.go#L309)):*
> ```Go
> 		if len(t.cols) == 1 {
> 			return b.finishBuildScalarRef(&t.cols[0], label, inScope, outScope)
> 		} else {
> ```

[nit] no need for `else`
___
*[pkg/sql/opt/optbuilder/scope.go, line 741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpIktz-5Vdlke5jgDH:-LHpIku--AfDAZzocWDg:bfhobs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scope.go#L741)):*
> ```Go
> }
> 
> // replaceSRF replaces a raw SRF with an srf struct. When this struct is later
> ```

[nit] the function doesn't actually do the replacing, maybe "returns an srf struct that can be used to replace a raw SRF"
___
*[pkg/sql/opt/optbuilder/scope.go, line 790 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpGpQv0aH2ZzEgksRS:-LHpGpQv0aH2ZzEgksRT:bqxl68j) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scope.go#L790)):*
> ```Go
> 	// We need to save and restore the previous value of the replaceSRFs field in
> 	// case we are recursively called within a subquery context.
> 	defer func(replaceSRFs bool) { s.replaceSRFs = replaceSRFs }(s.replaceSRFs)
> ```

[nit] Could do this which is more straightforward to read:
```
if s.replaceSRFs {
  defer func() { s.replaceSRfs = true }()
  s.replaceSRFs = false
}
```

___
*[pkg/sql/opt/optbuilder/srfs.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpGNvn0SwJfhfaBPMG:-LHpGNvn0SwJfhfaBPMH:b-3fe3qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/srfs.go#L35)):*
> ```Go
> 
> 	// expr is the resolved function expression.
> 	expr *tree.FuncExpr
> ```

[nit] consider embedding `*tree.FuncExpr` instead, so you don't have to define the pass-through methods&


<!-- Sent from Reviewable.io -->

2018-07-20 18:04 UTC, andy-kimball reviewed
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_exec_factory.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsk-9pE7qjIfkioTs0:-LHsk-9pE7qjIfkioTs1:bzbkhto) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada948d570531d124da9e79569945b3ce94289ca/pkg/sql/opt_exec_factory.go#L570)):*
> ```Go
> 		exprs:           exprs,
> 		funcs:           make([]*tree.FuncExpr, len(exprs)),
> 		numColsPerGen:   numColsPerGen,
> ```

Isn't `numColsPerGen` always equal to `len(tupType.Types)` if `expr.ResolvedType()` is `types.TTuple` and equal to `1` otherwise? How come it needs to be passed around?
___
*[pkg/sql/opt/exec/execbuilder/testdata/srfs, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsnXrAEQMswZvgbe36:-LHsnXrAEQMswZvgbe37:bnzehzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/exec/execbuilder/testdata/srfs#L66)):*
> ```
>       └── emptyrow  ·         ·                      ()                                        ·
> 
> subtest correlated_SRFs
> ```

I think these tests should be expanded. I'd try cases like:
1. the input to `ProjectSet` is more complex (maybe a join)
2. the SRF is correlated to outer columns (i.e. `generate_series` is itself in a correlated subquery)
3. multiple generate_series in the project list, all of them correlated
___
*[pkg/sql/opt/optbuilder/groupby.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHspEhJ1Uujds8TeSPN:-LHspEhJ1Uujds8TeSPO:bugigo) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/groupby.go#L275)):*
> ```Go
> // HAVING clause.
> func (b *Builder) buildHaving(having tree.Expr, inScope *scope) memo.GroupID {
> 	b.semaCtx.Properties.Require("HAVING", tree.RejectWindowApplications|tree.RejectGenerators)
> ```

How does this work when there are subqueries present? I'd think we'd need to set up a new `semaCtx` for subqueries, or else we'd incorrectly reject generators in subqueries. Can you make sure to add a test case for that (i.e. generator in subquery in HAVING), whether it's legal or not?
___
*[pkg/sql/opt/optbuilder/project.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsq4l_3QqdKu78dmNG:-LHsq4l_3QqdKu78dmNH:b-5k7ea1) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/project.go#L84)):*
> ```Go
> 	defer func(replaceSRFs bool) { inScope.replaceSRFs = replaceSRFs }(inScope.replaceSRFs)
> 
> 	b.semaCtx.Properties.Require("SELECT", tree.RejectNestedGenerators)
> ```

Similar to `HAVING`, it seems like this would incorrectly reject generators in a subquery that's part of a projection list. Isn't that allowed?


<!-- Sent from Reviewable.io -->

2018-07-21 20:24 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_exec_factory.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsk-9pE7qjIfkioTs0:-LHyURxo0IS8HydSoFmi:b3j8k8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada948d570531d124da9e79569945b3ce94289ca/pkg/sql/opt_exec_factory.go#L570)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't `numColsPerGen` always equal to `len(tupType.Types)` if `expr.ResolvedType()` is `types.TTuple` and equal to `1` otherwise? How come it needs to be passed around?
</blockquote></details>

It is equal except for one edge case: If `unnest()` is called with an array of tuples, then the output column is a tuple, but `numColsPerGen` is still 1. (There are some test cases for this edge case in `logic_test/srfs`)
___
*[pkg/sql/opt/optbuilder/scalar.go, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpIa8C0MMI6aoMbjtR:-LHyVJk_ArE9Tn8hhnWB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scalar.go#L309)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] no need for `else`
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpIktz-5Vdlke5jgDH:-LHyVMCT6OiaT-qxXoqx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scope.go#L741)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the function doesn't actually do the replacing, maybe "returns an srf struct that can be used to replace a raw SRF"
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 790 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpGpQv0aH2ZzEgksRS:-LHyVPQN-ko5zcpcEHzO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/scope.go#L790)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Could do this which is more straightforward to read:
```
if s.replaceSRFs {
  defer func() { s.replaceSRfs = true }()
  s.replaceSRFs = false
}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-23 05:01 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/srfs, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsnXrAEQMswZvgbe36:-LI4TcyiA_bOLk2Rki2h:bk5sjx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/exec/execbuilder/testdata/srfs#L66)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think these tests should be expanded. I'd try cases like:
1. the input to `ProjectSet` is more complex (maybe a join)
2. the SRF is correlated to outer columns (i.e. `generate_series` is itself in a correlated subquery)
3. multiple generate_series in the project list, all of them correlated
</blockquote></details>

Added some tests. I wasn't able to find a query for case #2 which could be decorrelated. We may need to add some new rules to get that to work...
___
*[pkg/sql/opt/optbuilder/srfs.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHpGNvn0SwJfhfaBPMG:-LI4I3Y-7N1HFEEWlzG_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/srfs.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider embedding `*tree.FuncExpr` instead, so you don't have to define the pass-through methods&
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-23 06:46 UTC, knz requested changes
Very nice job. It made me smile.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but I think perhaps there is a properties.restore missing (or perhaps a comment). Thanks!

> Reviewed 7 of 15 files at r1, 19 of 19 files at r5, 19 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-:-LI4semV2Oehw0hTrCUu:brp9sij)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt_exec_factory.go, line 570 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsk-9pE7qjIfkioTs0:-LI4otn22BpRpEmFQFcf:bmi8pos) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada948d570531d124da9e79569945b3ce94289ca/pkg/sql/opt_exec_factory.go#L570)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It is equal except for one edge case: If `unnest()` is called with an array of tuples, then the output column is a tuple, but `numColsPerGen` is still 1. (There are some test cases for this edge case in `logic_test/srfs`)
</blockquote></details>

:100:
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 143 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4qC2d07wb_LjHY585:-LI4qC2d07wb_LjHY586:bg60ipx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L143)):*
> ```Go
> 		}
> 		if ev.IsJoinApply() {
> 			if ev.Child(1).Operator() == opt.ZipOp {
> ```

nice :100:
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 840 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4qPPKEQr9SEu6DRr2:-LI4qPPKEQr9SEu6DRr3:b-sr4rh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L840)):*
> ```Go
> 	ctx := input.makeBuildScalarCtx()
> 	exprs, resultCols, numColsPerGen, outputCols, err := b.initZipBuild(
> 		ev.Child(1), input.outputCols.Copy(), ctx,
> ```

just curious: why do you need to copy the output columns here?
___
*[pkg/sql/opt/optbuilder/groupby.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4qt7u4SHZMHx43zpe:-LI4qt7v9ccyEmrM9cvo:b6ch3v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/optbuilder/groupby.go#L276)):*
> ```Go
> // HAVING clause.
> func (b *Builder) buildHaving(having tree.Expr, inScope *scope) memo.GroupID {
> 	b.semaCtx.Properties.Require("HAVING", tree.RejectWindowApplications|tree.RejectGenerators)
> ```

is a restore needed here and below for GROUP BY?

If yes, please add it; otherwise, please add a comment to indicate which other part of the code has it.
___
*[pkg/sql/opt/optbuilder/srfs.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4rlcD8vHTvn-qpMZB:-LI4rlcD8vHTvn-qpMZC:b-vumrpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/optbuilder/srfs.go#L46)):*
> ```Go
> func (s *srf) TypeCheck(ctx *tree.SemaContext, desired types.T) (tree.TypedExpr, error) {
> 	if ctx.Properties.Derived.SeenGenerator {
> 		return nil, pgerror.UnimplementedWithIssueErrorf(26234, "nested set-returning functions")
> ```

I don't understand how this error can happen -- it seems to me that typecheck cannot be called on a srf object.
I mean I get that it works (there's a test for it) but I don't understand how the code is getting here. Mind adding a comment?


<!-- Sent from Reviewable.io -->

2018-07-23 18:02 UTC, rytaft reviewed
Thanks for the reviews! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-:-LI7FhA49gznGu_0QGeH:bc7d8fp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 840 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4qPPKEQr9SEu6DRr2:-LI6Kb3P41mZYeSCztz5:b-c8iqji) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L840)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

just curious: why do you need to copy the output columns here?
</blockquote></details>

Since `initZipBuild` modifies the `outputCols` parameter, it could modify the underlying slice or map of `input.outputCols`. But it seems like `input.outputCols` is not used again, so I think you're right that this is unnecessary. Fixed and added a comment to the function. 
___
*[pkg/sql/opt/optbuilder/groupby.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHspEhJ1Uujds8TeSPN:-LI7Ehm80W1M0nXGOuCd:bfv09pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/groupby.go#L275)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How does this work when there are subqueries present? I'd think we'd need to set up a new `semaCtx` for subqueries, or else we'd incorrectly reject generators in subqueries. Can you make sure to add a test case for that (i.e. generator in subquery in HAVING), whether it's legal or not?
</blockquote></details>

I added some tests. @knz was right that I needed a restore. (It actually works without it because `Properties.Require` is currently set for every operator -- but I realize that we shouldn't rely on that in general)
___
*[pkg/sql/opt/optbuilder/groupby.go, line 276 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4qt7u4SHZMHx43zpe:-LI7CdXe9jZ0SUlHI-Ib:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/optbuilder/groupby.go#L276)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

is a restore needed here and below for GROUP BY?

If yes, please add it; otherwise, please add a comment to indicate which other part of the code has it.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/project.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LHsq4l_3QqdKu78dmNG:-LI7Cn66BW5Lu-Z_1ITl:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/32a6087fb593df417f71cc7f0d82ab1d800ea190/pkg/sql/opt/optbuilder/project.go#L84)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Similar to `HAVING`, it seems like this would incorrectly reject generators in a subquery that's part of a projection list. Isn't that allowed?
</blockquote></details>

Added a test.
___
*[pkg/sql/opt/optbuilder/srfs.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-LI4rlcD8vHTvn-qpMZB:-LI7Edpo4SnDZw4TQ0qn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58803a50ed09c0500321e2510285176909c117f/pkg/sql/opt/optbuilder/srfs.go#L46)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand how this error can happen -- it seems to me that typecheck cannot be called on a srf object.
I mean I get that it works (there's a test for it) but I don't understand how the code is getting here. Mind adding a comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-23 18:31 UTC, knz approved these changes
> Reviewed 1 of 15 files at r1, 19 of 19 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-23 19:23 UTC, rytaft reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27773#-:-LI7aACg8dXH4a6VF9Or:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-23 20:08 UTC, merged