roachtest: update store dump creation comments
cockroachdb/cockroach pull request #27794
Opened 2018-07-20 08:10 UTC by tschottdorf

I recreated the `backup` fixture. The other one had a wrong version in
the comment to begin with.

Release note: None

2018-07-20 08:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27794)
<!-- Reviewable:end -->

2018-07-20 11:27 UTC, petermattis requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo comment nit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27794#-:-LHrRJR9AnGZhgF8i47u:bk2w169)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/clearrange.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27794#-LHrR3yqCUXgeqiYLVg9:-LHrR3yqCUXgeqiYLVgA:bnrvs1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1478da6b4c1108f506b68dc279560d57634dd870/pkg/cmd/roachtest/clearrange.go#L33)):*
> ```Go
> 		Run: func(ctx context.Context, t *test, c *cluster) {
> 			// Created via:
> 			// roachtest --cockroach cockroach-v2.0-8 store-gen --stores=10 bank \
> ```

That's not quite accurate. I generated the store dump with a cockroach built from master (i.e 2.1) and the cluster version at the time was 2.0-8. I think it is confusing to put the cluster version in the binary name  here. 


<!-- Sent from Reviewable.io -->

2018-07-21 13:56 UTC, petermattis approved these changes

2018-07-21 13:56 UTC, petermattis commented
> I would've preferred to mention the SHA here, but I don't have it. What do you suggest? We don't want to just say "cockroach" or it'll be too easy to forget to put the right binary in place when using this comment to regenerate the fixtures.

Yeah, a SHA would have been ideal. Perhaps mention in the comment that the cockroach binary had cluster version v2.0-8 and was built after the SHA that included your fix.

2018-07-24 14:15 UTC, tschottdorf commented
bors r=petermattis

I'm going to leave the comment as-is because I didn't actually regenerate that fixture after #27639 (only the backup test needed fixing, not the restore one). We'll remember to put a SHA the next time we have to regenerate them.

2018-07-24 14:59 UTC, merged