sql: type check frame boundaries in WINDOW clause
cockroachdb/cockroach pull request #27933
Opened 2018-07-25 21:33 UTC by yuzefovich

Adds offsets' type checking of frame boundaries
if specified in WINDOW clause of SELECT statement.

Fixes: #27926.

Release note (bug fix): Now offsets of frame
boundaries are handled correctly when specified
in WINDOW clause.

2018-07-25 21:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27933)
<!-- Reviewable:end -->

2018-07-25 21:44 UTC, yuzefovich reviewed
There might be a more suitable place to put this type check in, but I'm not sure where that is.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIIORfd9LLlq3NTfPnB:b-x0rsrk)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-26 01:02 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIJ5AsJ0rVpb1DoeGZ0:-LIJ5AsJ0rVpb1DoeGZ1:bbvpnzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63dda4d6be4d15b0b792db91dc29215402f1d01/pkg/sql/window.go#L373)):*
> ```Go
> 	}
> 	if !modifyRef {
> 		windowDef := *referencedSpec
> ```

This doesn't immediately seem correct to me. The bound expressions should be type checked in the same place as the rest of the window definition. You should find out where that is. It's possible that it's in `constructWindowDefinitions` with the calls to `computeRenderAllowingStars`, but I'm not sure.


<!-- Sent from Reviewable.io -->

2018-07-26 14:44 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIJ5AsJ0rVpb1DoeGZ0:-LIM1GLh3Xh6VzmN3eNN:b-m8m97u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a63dda4d6be4d15b0b792db91dc29215402f1d01/pkg/sql/window.go#L373)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This doesn't immediately seem correct to me. The bound expressions should be type checked in the same place as the rest of the window definition. You should find out where that is. It's possible that it's in `constructWindowDefinitions` with the calls to `computeRenderAllowingStars`, but I'm not sure.
</blockquote></details>

I couldn't find a place that does type checking of `SelectClause` where `WINDOW` clause of the whole query lives (not sure if there is such), so Raphael and I agreed that an appropriate place to do this is in `constructWindowDefinitions` of `window.go`.


<!-- Sent from Reviewable.io -->

2018-07-26 14:49 UTC, yuzefovich reviewed
I wonder whether I should add type checking of PARTITION BY and ORDER BY clauses in there as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIM3-eLDoMTaPyjk73R:b3vj92i)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-26 14:50 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIM3DeE0VGRu8bMLK8B:-LIM3DeE0VGRu8bMLK8C:b-3evtgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bde982c773e524959086314136d00af0af15c1/pkg/sql/window.go#L288)):*
> ```Go
> 			return pgerror.NewErrorf(pgerror.CodeWindowingError, "window %q is already defined", name)
> 		}
> 		if windowDef.Frame != nil {
> ```

I think this needs to be down below in `range n.funcs` after handling the PARTITION BY and ORDER BY clauses.


<!-- Sent from Reviewable.io -->

2018-07-26 14:52 UTC, nvb reviewed
> I wonder whether I should add type checking of PARTITION BY and ORDER BY clauses in there as well.

Are they not being type checked? That would be very surprising. We can add instrumentation to find out, no need to guess.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIM3QfW4Imy3g7aL5Vh:b-fn38t1)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-26 15:15 UTC, yuzefovich reviewed
I think type checking of PARTITION BY and ORDER BY is done within `computeRenderAllowingStars` in `range n.funcs`, so I moved the code I added in there as well as you were suggesting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIM8CcU1Z6sDaTtwqlC:bfjdktp)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIM3DeE0VGRu8bMLK8B:-LIM3nDx8gO-B_MxRm5k:bqogazx) ([raw file](https://github.com/cockroachdb/cockroach/blob/68bde982c773e524959086314136d00af0af15c1/pkg/sql/window.go#L288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this needs to be down below in `range n.funcs` after handling the PARTITION BY and ORDER BY clauses.
</blockquote></details>

In that case, type checking will be performed for every window function that uses a particular window from `WINDOW` clause. If it is where I put it, type checking will be only done once for every window from `WINDOW` clause (even it is not used). I don't have strong opinion about it, so if you think it should go into `range n.funcs`, I'll move it.


<!-- Sent from Reviewable.io -->

2018-07-26 16:39 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but please rebase and re-gen your test.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIMRVi718uFVOXPuAYB:bjgnpa4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 2168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIMRNiX8Mzv2UqkJcE2:-LIMRNiX8Mzv2UqkJcE3:bn8vert) ([raw file](https://github.com/cockroachdb/cockroach/blob/b09b4a294deacdffca275a6e8e9c47662405d73f/pkg/sql/logictest/testdata/logic_test/window#L2168)):*
> ```
> 
> query RRR
> SELECT avg(price) OVER w1, avg(price) OVER w2, avg(price) OVER w1 FROM products WINDOW w1 AS (PARTITION BY group_name ORDER BY group_id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), w2 AS (ORDER BY group_id ROWS 1 PRECEDING)
> ```

Please rebase and re-gen the reference output. I just merged a change here and you'd get a bors failure otherwise.


<!-- Sent from Reviewable.io -->

2018-07-26 18:15 UTC, yuzefovich reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-:-LIMiFRK-ss-TJlGlt-Q:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 2168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27933#-LIMRNiX8Mzv2UqkJcE2:-LIMhgw66bNZJlb6Tgui:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b09b4a294deacdffca275a6e8e9c47662405d73f/pkg/sql/logictest/testdata/logic_test/window#L2168)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please rebase and re-gen the reference output. I just merged a change here and you'd get a bors failure otherwise.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-07-28 09:08 UTC, nvb approved these changes

2018-07-28 13:48 UTC, yuzefovich commented
bors r+

2018-07-28 14:14 UTC, merged