sql: improve handling of decimal zeroes
cockroachdb/cockroach pull request #27978
Opened 2018-07-27 01:58 UTC by mjibson

Previously we had inconsistent handling of decimal zeroes. Various forms
(-0, -0.00, +0.00) were correctly handled from a "what is this equal to"
perspective, but we were not consistent in keeping the digits after the
decimal point. Furthermore, postgres always removes negatives when making
-0 for ints and decimals (not floats).

This behavior (removing the negative from -0 automatically) existed in the
higher level apd tests but we were subverting it by using apd.Decimal.Neg
directly. apd has been updated to do this for Decimals now.

Our constant evaluation has also caused us some problems. We use the
go/constant package, but it evaluates numbers as floats. When we applied
the + operator our NumVal type would remove its OrigString representation
and thus use only the constant's Value, which, as a float, didn't contain
the trailing digits after the decimal (in cases like +0.000). Now the +
operator is a pass through.

The - operator remains the same, but has special logic to detect -0 and
leave the original string

The added logic tests have been compared to postgres and now we match
them exactly for many more things.

Of note is that, in postgres, `SELECT -0::float` returns -0 (in opposition
to the decimal behavior). This is why the test in TestParseDatumStringAs
removed only the -0 test for decimals and not floats.

Release note (sql change): More correct handling of decimal
0s. Specifically, -0 is coerced to 0 and values like 0.00 retain the
digits after the decimal point.

2018-07-27 01:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/27978)
<!-- Reviewable:end -->

2018-07-27 06:52 UTC, knz requested changes
Thanks for tackling this. I like that you have found solutions for negative zero, however in the process I believe you broke sorting. See my comments below.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-:-LIPVbzK5Wxdv3k8336z:b4rd6ws)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LIPVVqJBDla721JKxdq:b9lah02) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
> ```
> ----
> -1         false  false  false
> -Infinity  false  false  false
> ```

Aw, since when is -Infinity greater than -1?
___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPTojq381DBZMBFRpz:-LIPTojsExDkrAgk9NUP:b1vwh2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L200)):*
> ```
> 1          false  false  false
> Infinity   false  false  false
> NULL       NULL   NULL   NULL
> ```

Ouch, that won't do. NULLs and NaN must continue to sort for decimal like they do for floats, before other values. 

This is a behavior that's intendedly different from postgres, as discussed here #27603
___
*[pkg/sql/sem/tree/constant.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPUUxO1LKd6JPHrdGC:-LIPUUxO1LKd6JPHrdGD:b-dmk7oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/sem/tree/constant.go#L556)):*
> ```Go
> 				case token.SUB:
> 					// We always coerce -0 to 0 everywhere else, so this can be a passthrough.
> 					if cv.Value.String() == "0" {
> ```

Calling `String()` here is super expensive. Is there a way to access the value and make a cheaper comparison instead?
___
*[pkg/util/encoding/decimal.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPV7cm0yqtLjZB1kpD:-LIPV7cm0yqtLjZB1kpE:b-oxhh0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/util/encoding/decimal.go#L551)):*
> ```Go
> 	}
> 
> 	// We only encode "0" as decimalZero. All others ("0.0", "-0", etc) are
> ```

Why did you move this down in this function?


<!-- Sent from Reviewable.io -->

2018-07-27 07:24 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LIPb1EH2f7s1ZPCOvN1:bkm877e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Aw, since when is -Infinity greater than -1?
</blockquote></details>

This query uses `ORDER BY 1` and `rowsort`, so the order it shows up here in the text is unrelated to SQL semantics.
___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPTojq381DBZMBFRpz:-LIPbvYHByEIM2sF5m6p:b-816h6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L200)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ouch, that won't do. NULLs and NaN must continue to sort for decimal like they do for floats, before other values. 

This is a behavior that's intendedly different from postgres, as discussed here #27603
</blockquote></details>

Same.
___
*[pkg/util/encoding/decimal.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPV7cm0yqtLjZB1kpD:-LIPbK6bA2r6PUYPuFqa:b60ty72) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/util/encoding/decimal.go#L551)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Why did you move this down in this function?
</blockquote></details>

No semantic change, but I thought it made more sense to test for Form first, and then only do the IsZero check if it was Finite. IsZero already achieves that because it only returns true if it is Finite, but I think this is clearer when reading the code.


<!-- Sent from Reviewable.io -->

2018-07-27 08:49 UTC, knz requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LIPv6VD5iOplunMKrBv:bk2p7na) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This query uses `ORDER BY 1` and `rowsort`, so the order it shows up here in the text is unrelated to SQL semantics.
</blockquote></details>

Yeah then that means the test is broken. Since the SQL query uses ORDER BY the "rowsort" breaks the test (the test thus fails to verify that ORDER BY actually does its job).

Please remove "rowsort", re-gen the output and let's check the sort still works properly.
___
*[pkg/util/encoding/decimal.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPV7cm0yqtLjZB1kpD:-LIPvKr41ppWXSSxIi_b:b-x5jujw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/util/encoding/decimal.go#L551)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

No semantic change, but I thought it made more sense to test for Form first, and then only do the IsZero check if it was Finite. IsZero already achieves that because it only returns true if it is Finite, but I think this is clearer when reading the code.
</blockquote></details>

Ok, agreed. Thanks for explaining.


<!-- Sent from Reviewable.io -->

2018-07-29 05:03 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LIZP9EwD_ps5buxRlFy:b-mtpnk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yeah then that means the test is broken. Since the SQL query uses ORDER BY the "rowsort" breaks the test (the test thus fails to verify that ORDER BY actually does its job).

Please remove "rowsort", re-gen the output and let's check the sort still works properly.
</blockquote></details>

Ahh this was my misunderstanding then. I understood `ORDER BY 1` to be a noop, I didn't know it meant "sort by the first column". Will fix.


<!-- Sent from Reviewable.io -->

2018-07-29 11:55 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LI_t6HCCU-BEXEIiYy4:b-n34bob) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Ahh this was my misunderstanding then. I understood `ORDER BY 1` to be a noop, I didn't know it meant "sort by the first column". Will fix.
</blockquote></details>

Yes this ORDER BY behavior is very odd. I pulled my hair out when I discovered it too.


<!-- Sent from Reviewable.io -->

2018-08-06 21:15 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LJG4SDh30-6zsPi4n8y:bpmsgcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes this ORDER BY behavior is very odd. I pulled my hair out when I discovered it too.
</blockquote></details>

I think this has been fixed.
___
*[pkg/sql/sem/tree/constant.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPUUxO1LKd6JPHrdGC:-LJG4ThxEgw56EME8UTt:b-2698t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/sem/tree/constant.go#L556)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Calling `String()` here is super expensive. Is there a way to access the value and make a cheaper comparison instead?
</blockquote></details>

I tried using constant.Compare here instead. How does this look to you?


<!-- Sent from Reviewable.io -->

2018-08-07 09:11 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Good work!

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-:-LJIe0L5899yfwFXbimS:b-pv0wtg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/logictest/testdata/logic_test/decimal, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPVVqJBDla721JKxdp:-LJIdkPlEQw1TmD4mUp-:b-qezqq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/logictest/testdata/logic_test/decimal#L191)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I think this has been fixed.
</blockquote></details>

clever solution for the sorting :100: 
___
*[pkg/sql/sem/tree/constant.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27978#-LIPUUxO1LKd6JPHrdGC:-LJIdx0F3PAJ4nQYaJ0k:b-pcoly7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed1e3cdf8ef74bbc881cba4739d3349ba74f1dc2/pkg/sql/sem/tree/constant.go#L556)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I tried using constant.Compare here instead. How does this look to you?
</blockquote></details>

I like! :beers: 


<!-- Sent from Reviewable.io -->

2018-08-07 18:15 UTC, mjibson commented
bors r+

2018-08-07 19:02 UTC, merged