distsql: avoid generating ids for and registering local flows
cockroachdb/cockroach pull request #28046
Opened 2018-07-30 17:26 UTC by asubiotto

Results on a kv --read-percent=100 workload indicate a ~7.5% throughput
improvement.

Before:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   60.0s        0         860707        14345.6      1.1      0.9
   2.6      4.5     50.3
```

After:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   60.0s        0         924902        15415.3      1.0      0.9
   2.4      3.8     28.3
```

Release note: None

2018-07-30 17:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28046)
<!-- Reviewable:end -->

2018-07-30 17:55 UTC, rjnn approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-:-LIgKEBN6799jq-F6qYo:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-07-30 22:23 UTC, jordanlewis requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28046)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlplan/physical_plan.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIhHQrrDtXNbfIOvjRk:-LIhHQrrDtXNbfIOvjRl:buxzoos) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlplan/physical_plan.go#L756)):*
> ```Go
> ) map[roachpb.NodeID]distsqlrun.FlowSpec {
> 	// Only generate a flow ID for a remote plan because it will need to be
> 	// referenced by remote nodes when connecting streams.
> ```

Might as well note that we skip this for performance reasons on local flows, not correctness reasons.
___
*[pkg/sql/distsqlrun/flow.go, line 582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIh1xJn85y3OoKLojMa:-LIh1xJn85y3OoKLojMb:bfxxsx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlrun/flow.go#L582)):*
> ```Go
> 	sp := opentracing.SpanFromContext(ctx)
> 	sp.Finish()
> 	if f.status != FlowNotStarted && len(f.inboundStreams) > 0 {
> ```

Rather than keep this implicit, I would prefer to see a boolean on the flow that records whether or not it was registered. Or at the very least a comment here that explains that flows with 0 inbound streams never get registered.
___
*[pkg/sql/distsqlrun/flow.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIh2AcqBR0VRXeU7VN7:-LIh2AcqBR0VRXeU7VN8:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlrun/flow.go#L598)):*
> ```Go
> // read docs/RFCS/query_cancellation.md.
> func (f *Flow) cancel() {
> 	if len(f.inboundStreams) == 0 {
> ```

ditto
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 518 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIhHLLQAqUivx4estLK:-LIhHLLQAqUivx4estLL:b-izi3ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/7daf82b4aaf79d40fda3acc1a02243522f99cc1b/pkg/sql/distsqlrun/flow_registry_test.go#L518)):*
> ```Go
> // flowRegistry is draining and the we can also clean that flow up (the flow
> // will get a draining error). This used to crash.
> func TestSyncFlowAfterDrain(t *testing.T) {
> ```

Why delete this test? Sync Flows might still be a thing, right?


<!-- Sent from Reviewable.io -->

2018-07-31 16:39 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28046)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlplan/physical_plan.go, line 756 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIhHQrrDtXNbfIOvjRk:-LIkuGEw924qCiTjFW6w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlplan/physical_plan.go#L756)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Might as well note that we skip this for performance reasons on local flows, not correctness reasons.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow.go, line 582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIh1xJn85y3OoKLojMa:-LIkw3zZCtoq07BvfQoS:bc8w0vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlrun/flow.go#L582)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Rather than keep this implicit, I would prefer to see a boolean on the flow that records whether or not it was registered. Or at the very least a comment here that explains that flows with 0 inbound streams never get registered.
</blockquote></details>

Done. Added an `isLocal` method (thought it was better than a boolean)
___
*[pkg/sql/distsqlrun/flow.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIh2AcqBR0VRXeU7VN7:-LIkwC5p46WfgSW8FOWq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af71fe7093e69fbcc98324cdca8a4b5ce6242af/pkg/sql/distsqlrun/flow.go#L598)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_registry_test.go, line 518 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-LIhHLLQAqUivx4estLK:-LIlBqeL3r2qtHHWy3q-:b9z2x7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7daf82b4aaf79d40fda3acc1a02243522f99cc1b/pkg/sql/distsqlrun/flow_registry_test.go#L518)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why delete this test? Sync Flows might still be a thing, right?
</blockquote></details>

True, added the test back in, changed the flow into a remote flow, and fixed a bug where we weren't decrementing the waitgroup on a draining error in the flow registry.


<!-- Sent from Reviewable.io -->

2018-07-31 17:39 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28046#-:-LIlPxtjB9gxbaegKRRi:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-07-31 17:40 UTC, asubiotto commented
bors r+

2018-07-31 18:02 UTC, merged