opt: minor orderByCols cleanup in optbuilder
cockroachdb/cockroach pull request #28115
Opened 2018-07-31 21:15 UTC by RaduBerinde

The projections in DISTINCT ON will need treatment similar to the
ORDER BY projections. We refactor things a bit so that the existing
infrastructure can be reused: `orderByCols` is renamed to `extraCols`
and is now de-duplicated against `cols`; for convenience when copying
an ordering, we remember the ordering cols as a ColSet.

Release note: None

2018-07-31 21:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28115)
<!-- Reviewable:end -->

2018-08-01 15:04 UTC, rytaft requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-:-LIq04W79TWljyzEdvuV:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/scope.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIpyFXPCV8dZ4xUxk92:-LIpyBqeBJ5yMtWJSA9f:blle8yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L45)):*
> ```Go
> 
> 	// extraCols contains columns specified by the ORDER BY clause which don't
> 	// appear in cols.
> ```

Don't forget to update this comment to include DISTINCT ON cols
___
*[pkg/sql/opt/optbuilder/scope.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIq-L5n4wIpXFKPTCe4:-LIq-L5n4wIpXFKPTCe5:bvhqb41) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L311)):*
> ```Go
> 
> // colSetWithExtraCols returns a ColSet of all the columns in this scope,
> // including orderByCols.
> ```

orderByCols -> extraCols
___
*[pkg/sql/opt/optbuilder/scope.go, line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIq-_LM55hGTouk3Syw:-LIq-_LM55hGTouk3Syx:b-nw2tkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L847)):*
> ```Go
> 
> 	if len(outScope.extraCols) > 0 {
> 		// We need to add a projection to remove the ORDER BY columns.
> ```

also here - don't forget to change ORDER BY to extra cols


<!-- Sent from Reviewable.io -->

2018-08-01 15:25 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28115)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/scope.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIpyFXPCV8dZ4xUxk92:-LIq4mUJBpkAQc2LrK6G:bvr2xvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L45)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Don't forget to update this comment to include DISTINCT ON cols
</blockquote></details>

Will update in the DISTINCT ON change.
___
*[pkg/sql/opt/optbuilder/scope.go, line 311 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIq-L5n4wIpXFKPTCe4:-LIq4fiz6fXa2SzJ_m3g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L311)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

orderByCols -> extraCols
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 847 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28115#-LIq-_LM55hGTouk3Syw:-LIq4knz5nK8aKlUbOKm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c5714afeb5d2406fd880ee20f49c349a56da1c4/pkg/sql/opt/optbuilder/scope.go#L847)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

also here - don't forget to change ORDER BY to extra cols
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-01 15:27 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28115)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-01 18:02 UTC, RaduBerinde commented
bors r+

2018-08-01 18:22 UTC, merged