[WIP] opt: add support for numeric references
cockroachdb/cockroach pull request #28159
Opened 2018-08-01 18:11 UTC by madhavsuresh

Trying to figure out how to test on local machine - hold off on review for now.

2018-08-01 18:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28159)
<!-- Reviewable:end -->

2018-08-06 17:25 UTC, madhavsuresh reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJFGU9150U8TKCeIwyV:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-06 17:52 UTC, RaduBerinde reviewed
Looks good overall!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJFLlHA1SxrSazGI0rM:b-89nrqy)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFI0kA3WLzhQ1og5IE:-LJFI0kA3WLzhQ1og5IF:b-l58rwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L54)):*
> ```Go
> }
> 
> func (oc *optCatalog) FindTableByTableRef(ctx context.Context, tableID int64) (opt.Table, error) {
> ```

[nit] add `// FindTableByTableRef is part of the .. interface.`
___
*[pkg/sql/opt_catalog.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHUIb9rqH2kXtgZpi:-LJFHUIb9rqH2kXtgZpj:b-cx0492) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L62)):*
> ```Go
> 	}
> 
> 	dbDesc, err := sqlbase.GetDatabaseDescFromID(ctx, oc.resolver.Txn(), desc.ParentID)
> ```

err not checked
___
*[pkg/sql/opt_catalog.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHZo43VtCB9y9FFBf:-LJFHZo43VtCB9y9FFBg:b-ijq1tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L240)):*
> ```Go
> }
> 
> // LookupColumnOrdinal exposes optTable.lookupColumnOrdinal.
> ```

Most of this comment belongs inside the function (the caller should not care about private internals). I'd just say `// LookupColumnOrdinal is part of the opt.Table interface.`
___
*[pkg/sql/opt_catalog.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFKX1WB3OlcIGZvjYc:-LJFKX1WB3OlcIGZvjYd:bfsmqk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt_catalog.go#L57)):*
> ```Go
> 	// TODO(madhavsuresh): this does not completely mirror planner.getTableDescByID.
> 	// It does not use the descriptorCache
> 	desc, err := sqlbase.GetTableDescFromID(ctx, oc.resolver.Txn(), sqlbase.ID(tableID))
> ```

It's probably better if this path avoids the cache, given that it's used for testing. @knz should confirm.
___
*[pkg/sql/opt/catalog.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHtc19b66hnqaRduk:-LJFHtc19b66hnqaRdul:b3idrf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt/catalog.go#L198)):*
> ```Go
> 	Column(i int) Column
> 
> 	// LookupColumnOrdinal returns the ordinal of the column with the given ID. A
> ```

[nit] mention that this is the internal column ID and has no relation to ColumnIDs in the optimizer. I'd remove the comment about the cache.
___
*[pkg/sql/opt/catalog.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFJq8HAgjCxlrI8xus:-LJFJq8HAgjCxlrI8xut:b-5he20v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/catalog.go#L226)):*
> ```Go
> 	// given table name.  Returns an error if the table does not exist.
> 	FindTable(ctx context.Context, name *tree.TableName) (Table, error)
> 	FindTableByTableRef(ctx context.Context, tableID int64) (Table, error)
> ```

Blank line and add a comment. Consider renaming to `FindTableByID`
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJFMRrB3-PYp5NIE4WE:buzppif) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
> ```
> query error pq: cannot use "\*" without a FROM clause
> SELECT * FROM [53() AS num_ref_alias]
> ```

Would `SELECT 1 FROM [53() AS num_ref_alias]` work?
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFJI2eEHVG4tVKoMfW:-LJFJI2eEHVG4tVKoMfX:bequ8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt/testutils/testcat/test_catalog.go#L48)):*
> ```Go
> )
> 
> func (tc *Catalog) FindTableByTableRef(ctx context.Context, tableID int64) (opt.Table, error) {
> ```

[nit] add a comment


<!-- Sent from Reviewable.io -->

2018-08-06 18:05 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFI0kA3WLzhQ1og5IE:-LJFPMsq9who5j9HWi1T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add `// FindTableByTableRef is part of the .. interface.`
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHUIb9rqH2kXtgZpi:-LJFPP1p5AVoVmWbS2yH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

err not checked
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHZo43VtCB9y9FFBf:-LJFPQQf7QrbYThBrpfh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt_catalog.go#L240)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Most of this comment belongs inside the function (the caller should not care about private internals). I'd just say `// LookupColumnOrdinal is part of the opt.Table interface.`
</blockquote></details>

Done.
___
*[pkg/sql/opt/catalog.go, line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFHtc19b66hnqaRduk:-LJFPRr80J6kGR0CNFMW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt/catalog.go#L198)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] mention that this is the internal column ID and has no relation to ColumnIDs in the optimizer. I'd remove the comment about the cache.
</blockquote></details>

Done.
___
*[pkg/sql/opt/catalog.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFJq8HAgjCxlrI8xus:-LJFPSPOAoKbbxWvd_pm:b-we8vcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/catalog.go#L226)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Blank line and add a comment. Consider renaming to `FindTableByID`
</blockquote></details>

Done. Renamed.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJFPTXY3iLo6p5VndYf:b-obc5ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would `SELECT 1 FROM [53() AS num_ref_alias]` work?
</blockquote></details>

Yea it does. Does what you'd expect, returns `1` per row. 
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFJI2eEHVG4tVKoMfW:-LJFP_X201-HW0FStTea:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf810b53030196320e1e2a7c9cfc98b00c556c6/pkg/sql/opt/testutils/testcat/test_catalog.go#L48)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-07 14:58 UTC, rytaft requested changes
Great stuff!! Most of my comments are nits.

> Reviewed 3 of 9 files at r1, 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJJtOCR3QE4N8bEWgbi:b-p2alpc)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaM4dClrXHb3rFoZf:-LJFaM4dClrXHb3rFoZg:b6hoxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L54)):*
> ```Go
> }
> 
> // FindTableByID is part of the Catalog interface
> ```

[nit] period at end of function comment. Here and below.
___
*[pkg/sql/opt_catalog.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaf-9A-zRq7q6hWzi:-LJFaf-9A-zRq7q6hWzj:b8bd1mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L73)):*
> ```Go
> 	wrapper, ok := oc.wrappers[desc]
> 	if !ok {
> 		// Is this a normalized table name?
> ```

Not sure I understand this comment - I think the comment should be:
`// Make fully qualified table name.`
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJFaz7nDFNubfMzQtLD:b-ept4ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
> ```Go
> 	}
> 
> 	if err := oc.resolver.CheckPrivilege(ctx, desc, privilege.SELECT); err != nil {
> ```

Do you need to add a CheckPrivilege check in `FindTableByID` too?
___
*[pkg/sql/opt/catalog.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJoDoy9vnoSI_4NRln:-LJJoDoy9vnoSI_4NRlo:bhbe730) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/catalog.go#L200)):*
> ```Go
> 	// LookupColumnOrdinal returns the ordinal of the column with the given ID.
> 	// Note that this takes the internal column ID, and has no relation to
> 	// ColumnIDs in the optimizer
> ```

 [nit] add period
___
*[pkg/sql/opt/catalog.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJoWhgAuOWhx-21A0D:-LJJoWhgAuOWhx-21A0E:bomf81k) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/catalog.go#L228)):*
> ```Go
> 	FindTable(ctx context.Context, name *tree.TableName) (Table, error)
> 
> 	// FindTableByID returns Table interface for the database table
> ```

[nit] Table -> a Table
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpe052xflgQ-lT7b_:-LJJpe06DJM1t18USa-n:b-9iw93l) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L161)):*
> ```
> ·          spans     ALL              ·                                          ·
> 
> query error pq: descriptor not found
> ```

does this match the error message of the heuristic planner? seems like "error: relation [666] does not exist" would be more helpful than "descriptor not found". Then maybe you could use the same tests as the heuristic planner?
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJJpxmx4C_tPA8jRGin:belzpkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
> ```
> 
> query III
> SELECT * FROM [53(4,3,1) AS num_ref_alias]
> ```

Did you add these logic tests here because they don't work in the heuristic planner? If so, maybe add a comment to that effect.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 205 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJq9J6EKbdRBgHbtYs:-LJJq9J6EKbdRBgHbtYt:b-az0ino) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L205)):*
> ```
> 
> query III
> SELECT * FROM [53(1,3,4) AS num_ref_alias(col1,col2,col3)]
> ```

maybe add test directive "colnames" to check that the column names are correct
___
*[pkg/sql/opt/optbuilder/select.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJqcFBE0Yz1GcA7mXs:-LJJqcFBE0Yz1GcA7mXt:b-3546k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/select.go#L149)):*
> ```Go
> 
> func (b *Builder) buildScanWithTableRef(tab opt.Table, tn *tree.TableName, inScope *scope,
> 	ref *tree.TableRef) (outScope *scope) {
> ```

[nit] usually we break long lines at the parentheses. e.g.:
```
func (b *Builder) buildScanWithTableRef(
  ...
) (outScope *scope) {
```
___
*[pkg/sql/opt/optbuilder/select.go, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJr4Tj1ADHrXv_5r0C:-LJJr4Tj1ADHrXv_5r0D:b-yjhwb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/select.go#L155)):*
> ```Go
> 
> 	var colsToAdd []int
> 	// See tree.TableRef: "Note that a nil [Columns] array means 'unspecified' (all columns)."
> ```

[nit] 80 columns for comments
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJs8R03Az_Vs_edb5g:-LJJs8R03Az_Vs_edb5h:b1w0xnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/testdata/select#L1123)):*
> ```
> # These columns are off by one from what
> # the logictests will run. This is due
> # to the implementation of the test_catalog
> ```

Is it easy to fix test_catalog to do the right thing? That seems better than having off-by-one tests.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJsav-6MexAlP-iwY7:-LJJsav028O0m5nNAMGv:b-fcl9cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/testutils/testcat/test_catalog.go#L48)):*
> ```Go
> )
> 
> func (tc *Catalog) FindTableByID(ctx context.Context, tableID int64) (opt.Table, error) {
> ```

Still needs a comment


<!-- Sent from Reviewable.io -->

2018-08-07 15:18 UTC, knz commented
@BramGruneir could you have a look at this on behalf of the sql frontend team, I'm really swamped

2018-08-07 17:53 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaM4dClrXHb3rFoZf:-LJKJhlBA7R_QufS0d8G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L54)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] period at end of function comment. Here and below.
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaf-9A-zRq7q6hWzi:-LJKJiOo-haPYm7WTe0k:b2knbxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L73)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Not sure I understand this comment - I think the comment should be:
`// Make fully qualified table name.`
</blockquote></details>

Ah, this was a comment I made for myself. Removed. 
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJKJlU68cmXOSQuWl1V:bmu3j19) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you need to add a CheckPrivilege check in `FindTableByID` too?
</blockquote></details>

Added it. It doesn't look like the heuristic planner checks the privilege in it's FindTableByRef code path - but it also doesn't check it in FindTableByName as well. I'm not entirely sure how to test privileges within opt. Is this something that would be tested outside of opt?
___
*[pkg/sql/opt/catalog.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJoDoy9vnoSI_4NRln:-LJKK5mfBX0nKUw0dcWY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/catalog.go#L200)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

 [nit] add period
</blockquote></details>

Done.
___
*[pkg/sql/opt/catalog.go, line 228 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJoWhgAuOWhx-21A0D:-LJKK6WiENznd7VqzaMH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/catalog.go#L228)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] Table -> a Table
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpe052xflgQ-lT7b_:-LJKKJC7AU144XbWmxgH:b-1zp5ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L161)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

does this match the error message of the heuristic planner? seems like "error: relation [666] does not exist" would be more helpful than "descriptor not found". Then maybe you could use the same tests as the heuristic planner?
</blockquote></details>

I agree, updated the error messages. See comment below, there's still one case where the optimizer and heuristic planner don't match. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJKK8mc7DNg0-BqHEjj:beb8pnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Did you add these logic tests here because they don't work in the heuristic planner? If so, maybe add a comment to that effect.
</blockquote></details>

Yea there's two reasons, 1) to add tests that work within the optimizers test framework, 2) On this query: `SELECT * FROM [53() as t]`, the heuristic planner and optimizer have different outputs. It's unclear which one is "correct". The optimizer fails, the heuristic planner outputs `()`. It doesn't seem like an important issue to solve within the optimizer though. 

Added a comment including this. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 205 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJq9J6EKbdRBgHbtYs:-LJKKSboDJGBp1JcYake:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L205)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

maybe add test directive "colnames" to check that the column names are correct
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/select.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJqcFBE0Yz1GcA7mXs:-LJKS_RbBJbLdtHaIBGF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/select.go#L149)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] usually we break long lines at the parentheses. e.g.:
```
func (b *Builder) buildScanWithTableRef(
  ...
) (outScope *scope) {
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/select.go, line 155 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJr4Tj1ADHrXv_5r0C:-LJKSiQh4LhjlaQWC-kP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/select.go#L155)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] 80 columns for comments
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJs8R03Az_Vs_edb5g:-LJKSlos-BpbfNR8TqG5:b-j4b9n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/optbuilder/testdata/select#L1123)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is it easy to fix test_catalog to do the right thing? That seems better than having off-by-one tests.
</blockquote></details>

Changed it. I added a magic number so this would be consistent with the logictests for this functionality. For a reasons I didn't investigate, the first user table has id `53`. It makes more sense that these two tests are the same now (despite 53 being somewhat random). 
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 48 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJsav-6MexAlP-iwY7:-LJKU8QwAtO_icJcSaT3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/testutils/testcat/test_catalog.go#L48)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Still needs a comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-07 19:44 UTC, rytaft requested changes
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/data_source.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKgvzm4gWJN-SJLvOa:-LJKgvzm4gWJN-SJLvOb:b-3ovyds) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/data_source.go#L90)):*
> ```Go
> 	return planDataSource{
> 		info: sqlbase.NewSourceInfoForSingleTable(sourceName, columns),
> ```

[nit] this extra line seems unnecessary since you wouldn't be touching this file otherwise....
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJKhE_R9HIYoYuY3atS:b-7z27tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Added it. It doesn't look like the heuristic planner checks the privilege in it's FindTableByRef code path - but it also doesn't check it in FindTableByName as well. I'm not entirely sure how to test privileges within opt. Is this something that would be tested outside of opt?
</blockquote></details>

I'm not sure -- do you know, @RaduBerinde?
___
*[pkg/sql/opt_catalog.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKh8HR2DqwYqWGJBQk:-LJKh8HR2DqwYqWGJBQl:b-1mj369) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt_catalog.go#L59)):*
> ```Go
> 	// It does not use the descriptorCache.
> 	desc, err := sqlbase.GetTableDescFromID(ctx, oc.resolver.Txn(), sqlbase.ID(tableID))
> 	// See
> ```

Unfinished comment
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJKi3gh9F_MA78UAQr2:b-rtzajw) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Yea there's two reasons, 1) to add tests that work within the optimizers test framework, 2) On this query: `SELECT * FROM [53() as t]`, the heuristic planner and optimizer have different outputs. It's unclear which one is "correct". The optimizer fails, the heuristic planner outputs `()`. It doesn't seem like an important issue to solve within the optimizer though. 

Added a comment including this. 
</blockquote></details>

I agree it's not an important case, but it would be really nice to avoid duplication of the tests. I feel like this particular issue could be fixed pretty easily. It's not such a different case than selecting from an empty table, which works fine in the optimizer. For example:
```
root@:26257/t> create table empty (x int);
CREATE TABLE

Time: 14.12351ms

root@:26257/t> alter table empty drop column x;
ALTER TABLE

Time: 175.789817ms

root@:26257/t> select * from empty;
--
(0 rows)

Time: 736.517µs

root@:26257/t> explain (opt) select * from empty;
+-------------------------+
|          text           |
+-------------------------+
| scan empty              |
|  ├── columns:           |
|  ├── stats: [rows=1000] |
|  └── cost: 1010         |
+-------------------------+
(4 rows)
```
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKtszeAgourcJiXKGI:-LJKtszeAgourcJiXKGJ:b-p22rvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/optbuilder/testdata/select#L1152)):*
> ```
> SELECT * FROM [53(5) AS t]
> ----
> error: column [5] does not exist [4]
> ```

Why is there an extra [4] at the end?
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKtyF2Bvq0BfafYc_b:-LJKtyF34BARm05XwA66:b-t0behe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/testutils/testcat/create_table.go#L117)):*
> ```Go
> 	// We need to keep track of the tableID from
> 	// numeric references.
> 	// TODO(madhav): 53 is a magic number derived
> ```

I don't think this needs to be a TODO - just a regular comment seems fine....


<!-- Sent from Reviewable.io -->

2018-08-07 20:00 UTC, RaduBerinde approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJKxl0v2D4VvEECIVOn:b-lz10fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'm not sure -- do you know, @RaduBerinde?
</blockquote></details>

It can be tested with a logictest, to make sure we get an error (see `logictest/testdata/logic_test/privileges_table`).

In the heuristic planner, the checks are interleaved in the build code, there are many calls to `CheckPrivilege` throughout `sql`. We get away with checking in a single place in opt for now, but only because we only handle read-only queries.


<!-- Sent from Reviewable.io -->

2018-08-07 23:01 UTC, madhavsuresh reviewed
Added another check to see if the table has been dropped (and associated tests).  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJL_bB7Esa0lbYAgSKh:b5tu15n)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJLY-I96UkMtetVQpoP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It can be tested with a logictest, to make sure we get an error (see `logictest/testdata/logic_test/privileges_table`).

In the heuristic planner, the checks are interleaved in the build code, there are many calls to `CheckPrivilege` throughout `sql`. We get away with checking in a single place in opt for now, but only because we only handle read-only queries.
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKh8HR2DqwYqWGJBQk:-LJKyukv205h6GrcebU6:bcp9w5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt_catalog.go#L59)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Unfinished comment
</blockquote></details>

Deleted. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJKwvtA1j5cdM68sr5T:brbthix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I agree it's not an important case, but it would be really nice to avoid duplication of the tests. I feel like this particular issue could be fixed pretty easily. It's not such a different case than selecting from an empty table, which works fine in the optimizer. For example:
```
root@:26257/t> create table empty (x int);
CREATE TABLE

Time: 14.12351ms

root@:26257/t> alter table empty drop column x;
ALTER TABLE

Time: 175.789817ms

root@:26257/t> select * from empty;
--
(0 rows)

Time: 736.517µs

root@:26257/t> explain (opt) select * from empty;
+-------------------------+
|          text           |
+-------------------------+
| scan empty              |
|  ├── columns:           |
|  ├── stats: [rows=1000] |
|  └── cost: 1010         |
+-------------------------+
(4 rows)
```

</blockquote></details>

Hmm, yea I see what you're saying. Where it fails is here: https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/optbuilder/util.go#L29. The column list is empty because of the way the scope is built in buildScanByTableRef. I guess I'm not sure what the correct SQL semantics here should be. Either way makes sense to me. Would we want to keep all of the columns as hidden columns (that doesn't seem correct, couldn't the hidden columns be accessed in a nested query?) 

With respect to duplication of tests - would we need tests in execbuilder/ anyway? Even if the output is the same? 
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKtszeAgourcJiXKGI:-LJKyxwpDg8syq0NwD2N:b883x8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/optbuilder/testdata/select#L1152)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is there an extra [4] at the end?
</blockquote></details>

Debug output, Reran/rewrote tests. 
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKtyF2Bvq0BfafYc_b:-LJKz0Lz-QK_MEtikQrP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/testutils/testcat/create_table.go#L117)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think this needs to be a TODO - just a regular comment seems fine....
</blockquote></details>

Done.
___
*[pkg/sql/data_source.go, line 90 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJKgvzm4gWJN-SJLvOa:-LJKyu90AWS-iSq_eS5K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/data_source.go#L90)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] this extra line seems unnecessary since you wouldn't be touching this file otherwise....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-08 12:42 UTC, knz commented
I had a typo. d'oh.

bors r+

2018-08-08 12:42 UTC, knz commented
wow I'm so sorry I was thinking I was commenting on another issue. ignore the noise.

2018-08-08 13:30 UTC, knz reviewed
> Reviewed 1 of 9 files at r1, 1 of 5 files at r3, 3 of 8 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFKX1WB3OlcIGZvjYc:-LJOgGCyCa-EdkuJNIdZ:b-tf8vhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt_catalog.go#L57)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's probably better if this path avoids the cache, given that it's used for testing. @knz should confirm.
</blockquote></details>

Yes please remove the TODO, explain in the comment that this bypasses the cache, and call the cache bypassing out in the release note.
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJOga2WCYRNN6Srxswx:b2z3mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well to be fully precise the current way the `opt` code tests privileges is preparing us for a world of hurt when this needs to be extended to support mutations and DDL.

At the very least add a TODO here and above to mention this is not a satisfactory state of affairs. Also maybe file an issue (unless there is already one, @justinj?) to clean this up later and refer to that issue in the TODO.
___
*[pkg/sql/opt_catalog.go, line 275 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOh-fAC6v9b_WHZ6xU:-LJOh-fB8r3DnJmd1a_4:b796g0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt_catalog.go#L275)):*
> ```Go
> 		return col, nil
> 	}
> 	return col, error(fmt.Errorf("column [%d] does not exist", colID))
> ```

please consider `pgerror.NewErrorf` here with a suitable error code.
___
*[pkg/sql/table_ref_test.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOhDLW-mZ-BKC7PLf4:-LJOhDLW-mZ-BKC7PLf5:bkorlv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/table_ref_test.go#L39)):*
> ```Go
> 	// The error paths are different.
> 	stmt := `
> SET experimental_opt='off';
> ```

Two things:

1) do not believe that should be needed -- if the rest of your PR is correct, this test should pass with the optimizer code, and the errors should be the same

2) if you indeed need to disable the optimizer here, then you must also implement the corresponding set of unit tests for the code in your PR.
___
*[pkg/sql/logictest/testdata/logic_test/drop_table, line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOhVr95WaF3cYCtpY-:-LJOhVr95WaF3cYCtpY0:bof0mi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/logictest/testdata/logic_test/drop_table#L36)):*
> ```
> SELECT * FROM a
> 
> statement error pq: table is being dropped
> ```

What is this test testing? I do not understand why you added it.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJOhudfAJDcQgYDGiPx:bcgtyu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Yea it does. Does what you'd expect, returns `1` per row. 
</blockquote></details>

Huh what? I'd expect a selection of zero columns to return rows with zero columns. Where is this "1" coming from?
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOiBowDvIdHa118boL:b-qw7810) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Hmm, yea I see what you're saying. Where it fails is here: https://github.com/cockroachdb/cockroach/blob/0b000bb737fd547b522635e7d4d38a9e12b21e65/pkg/sql/opt/optbuilder/util.go#L29. The column list is empty because of the way the scope is built in buildScanByTableRef. I guess I'm not sure what the correct SQL semantics here should be. Either way makes sense to me. Would we want to keep all of the columns as hidden columns (that doesn't seem correct, couldn't the hidden columns be accessed in a nested query?) 

With respect to duplication of tests - would we need tests in execbuilder/ anyway? Even if the output is the same? 
</blockquote></details>

The semantics are explained in the comment which you correctly quoted:

```
// See tree.TableRef: "Note that a nil [Columns] array means 'unspecified'
// (all columns). whereas an array of length 0 means 'zero columns'."
```

So the syntax `[NN() ...]` selects zero columns, not all.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOiX0E6jDpiYRY6w9y:-LJOiX0E6jDpiYRY6w9z:b3wllg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/test_catalog.go#L55)):*
> ```Go
> 		}
> 	}
> 	return nil, fmt.Errorf("table %d not found", tableID)
> ```

1) use `pgerror.NewErrorf`
2) make the error the same as for regular names, `relation [%d] not found`.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 222 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOiemPDAWnWfwQJRin:-LJOiemPDAWnWfwQJRio:bf9hnkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/test_catalog.go#L222)):*
> ```Go
> func (tt *Table) LookupColumnOrdinal(colID uint32) (int, error) {
> 	if int(colID) > len(tt.Columns) || int(colID) < 1 {
> 		return int(colID), error(fmt.Errorf("column [%d] does not exist", colID))
> ```

ditto error code


<!-- Sent from Reviewable.io -->

2018-08-08 13:49 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOkB2N3Y3_j_0-d82w:b9uxey4) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The semantics are explained in the comment which you correctly quoted:

```
// See tree.TableRef: "Note that a nil [Columns] array means 'unspecified'
// (all columns). whereas an array of length 0 means 'zero columns'."
```

So the syntax `[NN() ...]` selects zero columns, not all.
</blockquote></details>

@knz I don't think the issue is that `[NN() ...]` is selecting all columns, the issue is that it causes an error in the optimizer if combined with `SELECT *`, while in the heuristic planner there is no error.

@madhav, I don't think this is standard SQL (at least it doesn't seem like Postgres supports it), but in general we've been trying to replicate the behavior of the heuristic planner unless there is a compelling reason to depart from it.  

Regarding how to implement this, good point about the hidden columns. I guess one option would be to add a "dummy" hidden column to prevent that error from triggering. It's definitely a hack, but it's a simple way to make this work with minimal changes to `scope`. @andy-kimball or @RaduBerinde, do you have any better ideas?


<!-- Sent from Reviewable.io -->

2018-08-08 13:59 UTC, rytaft requested changes
> Reviewed 5 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOp-reAhaBynKuC-qR:-LJOp-reAhaBynKuC-qS:b-2saz41) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt_catalog.go#L72)):*
> ```Go
> 	}
> 
> 	if err := filterTableState(desc); err != nil {
> ```

Do we need to add this check to `FindTable` as well?


<!-- Sent from Reviewable.io -->

2018-08-08 14:00 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOoTuACYXJLrlNCjvS:bx8658p) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

@knz I don't think the issue is that `[NN() ...]` is selecting all columns, the issue is that it causes an error in the optimizer if combined with `SELECT *`, while in the heuristic planner there is no error.

@madhav, I don't think this is standard SQL (at least it doesn't seem like Postgres supports it), but in general we've been trying to replicate the behavior of the heuristic planner unless there is a compelling reason to depart from it.  

Regarding how to implement this, good point about the hidden columns. I guess one option would be to add a "dummy" hidden column to prevent that error from triggering. It's definitely a hack, but it's a simple way to make this work with minimal changes to `scope`. @andy-kimball or @RaduBerinde, do you have any better ideas?
</blockquote></details>

For context: zero-column tables are valid in CockroachDB SQL, regardless of support for numeric referneces. Consider this:

```
create table foo(x int);
alter table foo drop column x;
insert into foo values (1), (2);
select * from foo;
```

This should work and return two (!) rows of zero (!) columns. I think we have unit tests for this.

Now maybe the difference with a regular table is that in my example there is a hidden `rowid` column, whereas in the code / example here (in this PR) we're excluding all columns including the hidden rowid column.

I am not 100% sure how to solve this but I would be comfortable to "solve" this by rejecting the notation `NN()` during planning and say with an error "an explicit list of column IDs must include at least one column".

Even in the envisioned case for numeric references to handle view descriptors, this would be adequate (a numeric reference inside a view descriptor will always include at least the PK columns, even if only hidden)

Would that help?
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOpZrMAO-jkxACkiQr:-LJOpZrMAO-jkxACkiQs:bc04l3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L186)):*
> ```
> SELECT * FROM [53(4,3,1) AS num_ref_alias]
> ----
> 100  10  1
> ```

Oh and by the way an unrelated point: if a column is marked hidden in the table descriptor, then selecting that column using a numeric reference should also yield a hidden column in the logical plan. Can you add a test for that?


<!-- Sent from Reviewable.io -->

2018-08-08 14:01 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOplkQ1NJuU2Od44-o:b3j5smu) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

For context: zero-column tables are valid in CockroachDB SQL, regardless of support for numeric referneces. Consider this:

```
create table foo(x int);
alter table foo drop column x;
insert into foo values (1), (2);
select * from foo;
```

This should work and return two (!) rows of zero (!) columns. I think we have unit tests for this.

Now maybe the difference with a regular table is that in my example there is a hidden `rowid` column, whereas in the code / example here (in this PR) we're excluding all columns including the hidden rowid column.

I am not 100% sure how to solve this but I would be comfortable to "solve" this by rejecting the notation `NN()` during planning and say with an error "an explicit list of column IDs must include at least one column".

Even in the envisioned case for numeric references to handle view descriptors, this would be adequate (a numeric reference inside a view descriptor will always include at least the PK columns, even if only hidden)

Would that help?



</blockquote></details>

Sorry in my example SQL above you need to swap the two lines:

```
create table foo(x int);
insert into foo values (1), (2);
alter table foo drop column x;
select * from foo;
```


<!-- Sent from Reviewable.io -->

2018-08-08 14:04 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOqTu-3hz7MDbs9eDk:b-xyewlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
> I am not 100% sure how to solve this but I would be comfortable to "solve" this by rejecting the notation NN() during planning and say with an error "an explicit list of column IDs must include at least one column".

I like that idea. If we do that, then should we change the existing planner code to also give the same error?


<!-- Sent from Reviewable.io -->

2018-08-08 14:08 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/drop_table, line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOhVr95WaF3cYCtpY-:-LJOr3lL-fP2V-77MMNE:b8iaout) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/logictest/testdata/logic_test/drop_table#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What is this test testing? I do not understand why you added it.
</blockquote></details>

The table above was dropped, I wanted to test this code path: https://github.com/cockroachdb/cockroach/pull/28159/files#diff-009df3bea1535b5639b1af5a45ff44f9R72
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJOr-ZDCqpqGAqpUrmM:b-vlu1vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Huh what? I'd expect a selection of zero columns to return rows with zero columns. Where is this "1" coming from?
</blockquote></details>

Will return an error as per comment below. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOqDEn3pUUUbY8pfkq:bevm8pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

> I am not 100% sure how to solve this but I would be comfortable to "solve" this by rejecting the notation NN() during planning and say with an error "an explicit list of column IDs must include at least one column".

I like that idea. If we do that, then should we change the existing planner code to also give the same error?

</blockquote></details>

Thanks for the comments @knz! That sounds good to me as well. That's a very easy change to make within the existing planner.


<!-- Sent from Reviewable.io -->

2018-08-08 14:17 UTC, RaduBerinde commented
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJOtZwzAUuoPMrsTRs8:b-pqd4sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Will return an error as per comment below. 
</blockquote></details>

@knz the query I asked for was `SELECT 1 FROM [53() AS num_ref_alias]`, where a 1 per row is correct.


<!-- Sent from Reviewable.io -->

2018-08-08 14:24 UTC, RaduBerinde approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/select.go, line 148 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOufNk0hoOtYAx4wnZ:-LJOufNk0hoOtYAx4wn_:b4yy23i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/optbuilder/select.go#L148)):*
> ```Go
> }
> 
> func (b *Builder) buildScanWithTableRef(
> ```

[nit] would be good to have a comment with a sample SQL query, given that this syntax is fairly obscure
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOup3M3tkXqyZK28fG:-LJOup3M3tkXqyZK28fH:btzfh3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/create_table.go#L115)):*
> ```Go
> 	}
> 
> 	// We need to keep track of the tableID from
> ```

[nit] reformat at 80 cols


<!-- Sent from Reviewable.io -->

2018-08-08 14:25 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/drop_table, line 36 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOhVr95WaF3cYCtpY-:-LJOvHJT7vIrvSldGc8T:bd5l6n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/logictest/testdata/logic_test/drop_table#L36)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

The table above was dropped, I wanted to test this code path: https://github.com/cockroachdb/cockroach/pull/28159/files#diff-009df3bea1535b5639b1af5a45ff44f9R72
</blockquote></details>

thanks.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 175 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFMRrB3-PYp5NIE4WD:-LJOvJxM2foEO5R4yOpa:b1v9282) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt/exec/execbuilder/testdata/select#L175)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@knz the query I asked for was `SELECT 1 FROM [53() AS num_ref_alias]`, where a 1 per row is correct.
</blockquote></details>

oh thanks for clarifying.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJOvMLI9Atu9UTmm_PZ:b-lyecee) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Thanks for the comments @knz! That sounds good to me as well. That's a very easy change to make within the existing planner.
</blockquote></details>

Yes if you can make both code paths fail with the same error, go ahead.


<!-- Sent from Reviewable.io -->

2018-08-08 17:11 UTC, madhavsuresh reviewed
I have kept the tests in opt/ as well as the table_ref_tests.go. Though, it seems that perhaps the opt/ tests are no longer necessary? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJPW10P1ZfKDIx-q_0W:bqhenez)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt_catalog.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFKX1WB3OlcIGZvjYc:-LJP14f4BqOEDy0yMqyo:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aca2b1acb7e664165bc5a76c74fa3dd81e288b1/pkg/sql/opt_catalog.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes please remove the TODO, explain in the comment that this bypasses the cache, and call the cache bypassing out in the release note.
</blockquote></details>

Done. 
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJPVd8k99MOTklUVg08:b-71v27o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Well to be fully precise the current way the `opt` code tests privileges is preparing us for a world of hurt when this needs to be extended to support mutations and DDL.

At the very least add a TODO here and above to mention this is not a satisfactory state of affairs. Also maybe file an issue (unless there is already one, @justinj?) to clean this up later and refer to that issue in the TODO.
</blockquote></details>

Done. Added a TODO. Will follow up with @justinj on issues. 
___
*[pkg/sql/opt_catalog.go, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOp-reAhaBynKuC-qR:-LJP0tDR4XBg_s24hYNA:bjldbt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt_catalog.go#L72)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do we need to add this check to `FindTable` as well?
</blockquote></details>

I would think so. I can add that in a separate PR. 
___
*[pkg/sql/opt_catalog.go, line 275 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOh-fAC6v9b_WHZ6xU:-LJOvoDf5QiNcryUL1CI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt_catalog.go#L275)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please consider `pgerror.NewErrorf` here with a suitable error code.
</blockquote></details>

Done.
___
*[pkg/sql/table_ref_test.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOhDLW-mZ-BKC7PLf4:-LJP8z7X19CUq7QiVu2v:b-3jipwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/table_ref_test.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Two things:

1) do not believe that should be needed -- if the rest of your PR is correct, this test should pass with the optimizer code, and the errors should be the same

2) if you indeed need to disable the optimizer here, then you must also implement the corresponding set of unit tests for the code in your PR.
</blockquote></details>

Given our discussion below, the opt code now passes the table_ref_test. 
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJP95rY9HFoEb6c44-5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes if you can make both code paths fail with the same error, go ahead.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOpZrMAO-jkxACkiQr:-LJPOVxG0Pr1sDaVscGU:b4d10km) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L186)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Oh and by the way an unrelated point: if a column is marked hidden in the table descriptor, then selecting that column using a numeric reference should also yield a hidden column in the logical plan. Can you add a test for that?
</blockquote></details>

Thanks for catching this. Added tests for this. 
___
*[pkg/sql/opt/optbuilder/select.go, line 148 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOufNk0hoOtYAx4wnZ:-LJP0nSC20wOrHfpaMcp:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/optbuilder/select.go#L148)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be good to have a comment with a sample SQL query, given that this syntax is fairly obscure
</blockquote></details>

Done. 
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 115 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOup3M3tkXqyZK28fG:-LJP-xyfE1JEME2KNhWP:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/create_table.go#L115)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] reformat at 80 cols
</blockquote></details>

Done. 
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 55 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOiX0E6jDpiYRY6w9y:-LJOyja43a6Bx1hQQibH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/test_catalog.go#L55)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) use `pgerror.NewErrorf`
2) make the error the same as for regular names, `relation [%d] not found`.

</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 222 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOiemPDAWnWfwQJRin:-LJOyj43BK7xpxh81JdK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt/testutils/testcat/test_catalog.go#L222)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto error code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-08 17:59 UTC, rytaft requested changes
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/data_source.go, line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPbf5uCgEi1-0VDdTr:-LJPbf5uCgEi1-0VDdTs:b6nq5iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/data_source.go#L227)):*
> ```Go
> 	if tref.Columns != nil && len(tref.Columns) == 0 {
> 		return planDataSource{}, pgerror.NewErrorf(pgerror.CodeSyntaxError,
> 			"An explicit list of column IDs must include at least one column")
> ```

[nit] I think error messages are supposed to start with a lower-case letter
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJPc5hr3z8CLdHiubby:b-ru4ceg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Done. Added a TODO. Will follow up with @justinj on issues. 
</blockquote></details>

I'd add a TODO on both calls to CheckPrivileges, just to make sure we don't miss it.
___
*[pkg/sql/opt_catalog.go, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJOp-reAhaBynKuC-qR:-LJPbMde0bzH99LxAaOG:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a0159ce695acddcd0a2eab60f4e02bc15f86b71/pkg/sql/opt_catalog.go#L72)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

I would think so. I can add that in a separate PR. 
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/table_ref_test.go, line 117 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPcS3Q4EaAWLESuHJs:-LJPcS3Q4EaAWLESuHJt:b-k6ezhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/table_ref_test.go#L117)):*
> ```Go
> 		{fmt.Sprintf("[%d(%d) as t]@[%d]", tID, bID, secID), `(d)`, ``},
> 		{fmt.Sprintf("[%d(%d) as t]@[%d]", tID, cID, secID), `(c)`, ``},
> 		{fmt.Sprintf("[%d(%d) as t]@[%d]", tID, cID, secID), `(c)`, ``},
> ```

duplicate test
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJPcwz8BObiIy_b3KKJ:bx2yol) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good - now you can remove these tests (or move them to logictests if they are not there already)
___
*[pkg/sql/opt/optbuilder/select.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPd_NfCAFE_IiTvbkT:-LJPd_Ng-XX9P86n6qQa:blpfunf) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/select.go#L92)):*
> ```Go
> 
> 	case *tree.TableRef:
> 		if source.Columns != nil && len(source.Columns) == 0 {
> ```

[nit] I would move this check inside `buildScanWithTableRef` so the code is all contained there. Putting it here does save a call to `resolveTableRef`, but there's not much benefit to optimizing for the error case.
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPeIvuD5FGN7kKfh3a:-LJPeIvuD5FGN7kKfh3b:bw2mek5) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/testdata/select#L1209)):*
> ```
> SELECT * FROM [54(3) AS t]
> ----
> panic: presentation property doesn't apply to non-relational operators
> ```

Why is this causing a panic? I think this case should act just like `SELECT * FROM no_cols_table`

It would be good to also add one test case like this:
`SELECT rowid FROM [54(3) AS t]`


<!-- Sent from Reviewable.io -->

2018-08-08 18:55 UTC, madhavsuresh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/data_source.go, line 227 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPbf5uCgEi1-0VDdTr:-LJPmlIFA6PvJgRI3_WO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/data_source.go#L227)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think error messages are supposed to start with a lower-case letter
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJFaz7mCiBLn5D1UMjp:-LJPmiau9Cyzk6T4458N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab0bc27aebff5ceb4f9f863d24c30e3bfed6520d/pkg/sql/opt_catalog.go#L88)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'd add a TODO on both calls to CheckPrivileges, just to make sure we don't miss it.
</blockquote></details>

Done.
___
*[pkg/sql/table_ref_test.go, line 117 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPcS3Q4EaAWLESuHJs:-LJPn5hT9kdZKRIdnITe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/table_ref_test.go#L117)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

duplicate test
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJJpxmx4C_tPA8jRGim:-LJPsusU4zmwK7mILNSK:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/861da08f081cfe2bf7193f8d73dd32a49e2d2fcb/pkg/sql/opt/exec/execbuilder/testdata/select#L184)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks good - now you can remove these tests (or move them to logictests if they are not there already)
</blockquote></details>

Done. 
___
*[pkg/sql/opt/optbuilder/select.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPd_NfCAFE_IiTvbkT:-LJPi3hjE0PfknPw_9fT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/select.go#L92)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I would move this check inside `buildScanWithTableRef` so the code is all contained there. Putting it here does save a call to `resolveTableRef`, but there's not much benefit to optimizing for the error case.
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/select, line 1209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPeIvuD5FGN7kKfh3a:-LJPnpLCB3h7GNdtqiEc:b3hq2wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/testdata/select#L1209)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is this causing a panic? I think this case should act just like `SELECT * FROM no_cols_table`

It would be good to also add one test case like this:
`SELECT rowid FROM [54(3) AS t]`
</blockquote></details>

There's a panic as well with a table with no columns in optbuilder:
```
exec-ddl
CREATE TABLE no_cols_table ()
----

build
SELECT * FROM no_cols_table
----
```
The panic is here:
https://github.com/cockroachdb/cockroach/blob/6e447149bf54669e4e3332164ce9fcc8aa7c1ec4/pkg/sql/opt/xform/physical_props.go#L61

For now I've removed this test from optbuilder, since it causes the tests to panic out.


Thanks for that suggestion - added the test. 


<!-- Sent from Reviewable.io -->

2018-08-08 19:19 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for all the work on this!

> Reviewed 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJPyT9w3pCtNZfuBqah:bekpoxw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/testdata/select, line 1209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPeIvuD5FGN7kKfh3a:-LJPx3MLAGLmnRlF73mJ:bfkh50e) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/testdata/select#L1209)):*
<details><summary><i>Previously, madhavsuresh wrote…</i></summary><blockquote>

There's a panic as well with a table with no columns in optbuilder:
```
exec-ddl
CREATE TABLE no_cols_table ()
----

build
SELECT * FROM no_cols_table
----
```
The panic is here:
https://github.com/cockroachdb/cockroach/blob/6e447149bf54669e4e3332164ce9fcc8aa7c1ec4/pkg/sql/opt/xform/physical_props.go#L61

For now I've removed this test from optbuilder, since it causes the tests to panic out.


Thanks for that suggestion - added the test. 
</blockquote></details>

That's definitely a bug... not sure when that got introduced, but can you file an issue to address in another PR? Feel free to assign it to me.


<!-- Sent from Reviewable.io -->

2018-08-08 21:15 UTC, madhavsuresh reviewed
Thanks for the reviews!!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-:-LJQNzd43xOsGJ5dFrlm:b9gm0iw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/testdata/select, line 1209 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28159#-LJPeIvuD5FGN7kKfh3a:-LJQ-UDE0H0vvASiS-wK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05a02edc2ec6f825c363a94e4364931586123020/pkg/sql/opt/optbuilder/testdata/select#L1209)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

That's definitely a bug... not sure when that got introduced, but can you file an issue to address in another PR? Feel free to assign it to me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-08 21:55 UTC, madhavsuresh commented
bors r+

2018-08-08 23:38 UTC, merged