client, kv: move logic out of Txn, rewrite some of the TxnCoordSender
cockroachdb/cockroach pull request #28185
Opened 2018-08-02 00:19 UTC by andreimatei

This patch moves most of the logic from the client.Txn into the
 kv.TxnCoordSender and reorganizes much of the TxnCoordSender in the
 process.
 The split between the client.Txn and the TxnCoordSender caused a lot of
 grief historically. The main problem is that both the Txn and the TCS
 each have their own copy of the roachpb.Transaction proto. They both
 use their copy for different things. We attempt to keep the two protos
 in sync, but we can't ensure that as there's no common locking between
 the two layers.
 This patch keeps the client.Txn as a mostly stateless shim, allowing
 one to mock everything underneath. This is nice, as previously "mocking
 KV" was a less clear proposition - does one mock all the logic in the
 Txn or just the TCS? Now the TCS has all the logic and all the locking
 necessary for serializing accesses to the "transaction state" - notably
 the proto.
 The Txn and TCS communicate through a (now expanded) client.TxnSender
 interface.

 Within the TCS, the biggest change is that everything that has to do
 with the heartbeat loop has been moved to a new interceptor.

2018-08-02 00:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28185)
<!-- Reviewable:end -->

2018-08-06 13:08 UTC, nvb requested changes
> Reviewed 32 of 41 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/sender.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE-Grd0hjwwMNZsOGn:-LJE-Grd0hjwwMNZsOGo:bw5fvr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L130)):*
> ```Go
> 	// This is used to support historical queries (AS OF SYSTEM TIME queries and
> 	// backups). This method must be called on every transaction retry (but note
> 	// that retries should be rare for read-only queries with no clock uncertainty).
> ```

Are they possible at all?
___
*[pkg/internal/client/sender.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0fhiEzqB403aXqTz:-LJE0fhiEzqB403aXqU-:b-fdf2kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L136)):*
> ```Go
> 	// and timestamp.
> 	// An uninitialized timestamp can be passed to leave the timestamp alone.
> 	ManualRestart(context.Context, roachpb.UserPriority, hlc.Timestamp)
> ```

Do we need `BumpEpochAfterConcurrentRetryError` if we have this?
___
*[pkg/internal/client/sender.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0w5D6x-mwXbM0_M4:-LJE0w5D6x-mwXbM0_M5:b-ate9i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L151)):*
> ```Go
> 	IsSerializablePushAndRefreshNotPossible() bool
> 
> 	Epoch() uint32
> ```

This is such a large interface now that we should put some effort into ordering its methods effectively.
___
*[pkg/internal/client/sender.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE1StD0C7j_XXnP3OF:-LJE1StD0C7j_XXnP3OG:b-v83rir) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L204)):*
> ```Go
> }
> 
> // NewMockTransactionalSender creates a MockTransactionalSender.
> ```

Make a note that the txn is cloned.
___
*[pkg/internal/client/txn.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE2Mx0BcA9EOVlVRKz:-LJE2Mx0BcA9EOVlVRL-:b-h6dcnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L57)):*
> ```Go
> 
> 	// mu holds fields that need to be synchronized for concurrent request execution.
> 	mu struct {
> ```

It's surprising to me that we still have this lock. I would expect all locking to be internal to the TxnCoordSender.
___
*[pkg/internal/client/txn.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE22Y977NwcejJA776:-LJE22Y977NwcejJA777:bqydr2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L61)):*
> ```Go
> 		ID        uuid.UUID
> 		debugName string
> 		isolation enginepb.IsolationType
> ```

Do we need these two fields? Can't we just set it on the proto?
___
*[pkg/internal/client/txn.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE1xRc1l8nsLHGOHyP:-LJE1xRc1l8nsLHGOHyQ:bmq0y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L66)):*
> ```Go
> 		// NormalUserPriority will be used.
> 		// TODO(andrei): Can this go away now that userPriority and Proto.Priority
> 		// are initialized at the same time?
> ```

I'd pull on this string now.
___
*[pkg/internal/client/txn.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE27bV6SlIgIy4sC0w:-LJE27bV6SlIgIy4sC0x:bzfr42i) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L74)):*
> ```Go
> 		// useful for catching retriable errors that have escaped inner
> 		// transactions, so that they don't cause a retry of an outer transaction.
> 		previousIDs map[uuid.UUID]struct{}
> ```

Add a TODO that this should go away when we move to a TxnAttempt model.
___
*[pkg/internal/client/txn.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE2jis6XrRlfeCydVN:-LJE2jis6XrRlfeCydVO:bb7462z) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L280)):*
> ```Go
> }
> 
> // // SetTxnAnchorKey sets the key at which to anchor the transaction record. The
> ```

TODO
___
*[pkg/internal/client/txn.go, line 759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4aCg42kxZzS33tbE:-LJE4aCg42kxZzS33tbF:bfv4ys2) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L759)):*
> ```Go
> // IsRetryableErrMeantForTxn returns true if err is a retryable
> // error meant to restart this client transaction.
> func (txn *Txn) IsRetryableErrMeantForTxn(retryErr roachpb.HandledRetryableTxnError) bool {
> ```

Can we get rid of this?
___
*[pkg/internal/client/txn.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE3zYo9Xpe6qfSpPpN:-LJE3zYo9Xpe6qfSpPpO:b-oz5q0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L819)):*
> ```Go
> 		txn.mu.Lock()
> 		txn.resetDeadlineLocked()
> 		txn.replaceSenderMaybeLocked(ctx, retryErr, requestTxnID)
> ```

"maybe locked"? I think you mean `maybeReplaceSenderLocked`.
___
*[pkg/internal/client/txn_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4qyq1RNDulBbaFZ6:-LJE4qyq1RNDulBbaFZ7:buxay67) ([raw file](https://github.com/cockroachdb/cockroach/blob/624aacde7c260053e86ccc89d419a15328ad5226/pkg/internal/client/txn_test.go#L174)):*
> ```Go
> // TestTxnRequestTxnTimestamp verifies response txn timestamp is
> // always upgraded on successive requests.
> func TestTxnRequestTxnTimestamp(t *testing.T) {
> ```

Did this test survive? It looks legit.

EDIT: looks like it did!
___
*[pkg/kv/txn_coord_sender.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEC85d0YmoIIavw40K:-LJEC85d0YmoIIavw40L:b5dm5f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L47)):*
> ```Go
> // be sent.
> //go:generate stringer -type=txnState
> type txnState int
> ```

Nice! I'm really glad to see these states simplified.
___
*[pkg/kv/txn_coord_sender.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEIIBk98ywPivA9LY0:-LJEIIBk98ywPivA9LY1:b-65nmfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L233)):*
> ```Go
> 	ctx context.Context, ba roachpb.BatchRequest,
> ) (*roachpb.BatchResponse, *roachpb.Error) {
> 	if _, ok := ba.GetArg(roachpb.BeginTransaction); ok {
> ```

I'm not sure how I feel about this change. Seems like it would be a lot cleaner to just remove the unnecessary assertion in `txnIntentCollector`. It's not giving us anything and moving to something like this just so that we can enforce the assertion isn't great. It's introducing strange circular dependencies and preventing interceptors from the local reasoning that currently makes them straightforward to think about.
___
*[pkg/kv/txn_coord_sender.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEJ5dx89PBYBWrU-CU:-LJEJ5dx89PBYBWrU-CV:b-2br86g) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L462)):*
> ```Go
> 	tcs.interceptorStack = [...]txnInterceptor{
> 		&tcs.interceptorAlloc.txnHeartbeat,
> 		&tcs.interceptorAlloc.txnSeqNumAlloc [...]

2018-08-06 23:55 UTC, andreimatei reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJGegEy2P7uesL3VXSW:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/sender.go, line 130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE-Grd0hjwwMNZsOGn:-LJEtH7S2yjDzy2s6RrS:b-2b1bex) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are they possible at all?
</blockquote></details>

I don't know... I'd leave it...
___
*[pkg/internal/client/sender.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0fhiEzqB403aXqTz:-LJF6pzX6wpNFwGGhfhE:b520gy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L136)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need `BumpEpochAfterConcurrentRetryError` if we have this?
</blockquote></details>

i've collapsed the two; good idea
___
*[pkg/internal/client/sender.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0w5D6x-mwXbM0_M4:-LJGPLK9DZWoS2rmxatm:bpvvse1) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L151)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is such a large interface now that we should put some effort into ordering its methods effectively.
</blockquote></details>

I've put the "write" methods before the read-only.
Happy to take suggestions.
___
*[pkg/internal/client/sender.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE1StD0C7j_XXnP3OF:-LJF7-da7_f2SP1SisUr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L204)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note that the txn is cloned.
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE2Mx0BcA9EOVlVRKz:-LJF743g7uL4nqCgdO7U:b-8d1by7) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L57)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's surprising to me that we still have this lock. I would expect all locking to be internal to the TxnCoordSender.
</blockquote></details>

well but the sender itself needs to be protected by a lock, unfortunately
___
*[pkg/internal/client/txn.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE22Y977NwcejJA776:-LJGHkV74zXWlGuusGjf:bfq3jdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L61)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need these two fields? Can't we just set it on the proto?
</blockquote></details>

well the txn no longer has access to the proto, and these fields are not quite write-only. I'm not sure what to do about them. Might leave them for now.
___
*[pkg/internal/client/txn.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE1xRc1l8nsLHGOHyP:-LJG0ti77W2wlZsOROew:b-444djp) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd pull on this string now.
</blockquote></details>

I pulled a bit and did a bit of cleanup, but I think we need to keep this field. It's useful when `txn.SetUserPriority()` is called a 2nd, presumably after a restart, to turn the call into a no-op instead of complaining that the txn has already been initialized.
___
*[pkg/internal/client/txn.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE27bV6SlIgIy4sC0w:-LJF7GDy4jQ7MDGuQ5mx:b-nxvjfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a TODO that this should go away when we move to a TxnAttempt model.
</blockquote></details>

meh. I think such a TODO would only make sense to people who already know what it's about and wouldn't help anybody else.
___
*[pkg/internal/client/txn.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE2jis6XrRlfeCydVN:-LJF7Ujc1npQn3SzMAiB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L280)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4aCg42kxZzS33tbE:-LJGIeVD3FeC9Y4M4snV:bqpd2zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L759)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we get rid of this?
</blockquote></details>

I don't think so... I mean, I don't think anything changed with regards to this; we test this in `txn.Exec()` and make the error not retriable so that a client doesn't retry.
Are you saying that we should catch it at a different layer?
___
*[pkg/internal/client/txn.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE3zYo9Xpe6qfSpPpN:-LJF7YmnCrIi613qIgVh:b-osewqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L819)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"maybe locked"? I think you mean `maybeReplaceSenderLocked`.
</blockquote></details>

well it's "replaceSenderMaybe;Locked". I prefer the "maybe" at the end (Google style), so that the method name starts with something more meaningful.
___
*[pkg/internal/client/txn_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4qyq1RNDulBbaFZ6:-LJEv6P3BM6eO5ftO28Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/624aacde7c260053e86ccc89d419a15328ad5226/pkg/internal/client/txn_test.go#L174)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did this test survive? It looks legit.

EDIT: looks like it did!
</blockquote></details>

Done.
___
*[pkg/kv/txn_coord_sender.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEC85d0YmoIIavw40K:-LJEy71D4p3HTqa9r8yq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice! I'm really glad to see these states simplified.
</blockquote></details>

Done.
___
*[pkg/kv/txn_coord_sender.go, line 233 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEIIBk98ywPivA9LY0:-LJFI1F_067yMt6YXLvM:bmg0b1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L233)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary [...]

2018-08-07 18:24 UTC, andreimatei reviewed
r3 is #28344

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJKc_ZS9d5RhcqzZz64:bpy5y12)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-08 20:25 UTC, nvb requested changes
Nice, this is looking really good. Mostly just nits at this point. I'm very happy with how readable this is becoming.

> Reviewed 3 of 42 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJQBsYB7zWTIOdt3PAX:b8wbl3z)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/sender.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0w5D6x-mwXbM0_M4:-LJQ9SVd3IH-9tbXEAZc:b-b5vpbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L151)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've put the "write" methods before the read-only.
Happy to take suggestions.
</blockquote></details>

That looks good. Thanks.
___
*[pkg/internal/client/txn.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE22Y977NwcejJA776:-LJQ9cLPBjJLYssRunHV:b-cty5tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L61)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well the txn no longer has access to the proto, and these fields are not quite write-only. I'm not sure what to do about them. Might leave them for now.
</blockquote></details>

Aren't we still duplicating state then?
___
*[pkg/internal/client/txn.go, line 759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4aCg42kxZzS33tbE:-LJQ9rpoDmPF6ClKcLlK:bs8hndu) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L759)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think so... I mean, I don't think anything changed with regards to this; we test this in `txn.Exec()` and make the error not retriable so that a client doesn't retry.
Are you saying that we should catch it at a different layer?
</blockquote></details>

Eh, I guess I'll hold my grievances for a later change.
___
*[pkg/internal/client/txn.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE3zYo9Xpe6qfSpPpN:-LJQ9xks9n8VjRwobBOq:b-xtkiba) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L819)):*
> I prefer the "maybe" at the end (Google style), so that the method name starts with something more meaningful.

Yeah but that's not what we do everywhere else. It seems very off in this codebase. I'd switch it.
___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQAdyjCXteclo5ULnt:b-cl40kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

but this is better!
</blockquote></details>

It's also completely inconsistent with our codebase. consistency > personal preference.
___
*[pkg/kv/txn_coord_sender.go, line 997 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJQAzgp12bg7SZkjh6u:-LJQAzgp12bg7SZkjh6v:b-bdx36f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5d6d666dde5168c7fc7ce26823ad223d0b54e5/pkg/kv/txn_coord_sender.go#L997)):*
> ```Go
> 	// Reset the state for the retry.
> 	tc.mu.txnState = txnPending
> ```

nit: stray line.
___
*[pkg/kv/txn_interceptor_metrics.go, line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJQBdPX9pepcVU3uMBd:-LJQBdPX9pepcVU3uMBe:b3soqka) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5d6d666dde5168c7fc7ce26823ad223d0b54e5/pkg/kv/txn_interceptor_metrics.go#L33)):*
> ```Go
> 
> 	mu struct {
> 		sync.Locker // the TxnCoordSender's lock
> ```

Why do we need this lock? One of the biggest benefits of this architecture is that the interceptors don't even need to realize they're operating under lock. I don't think any of the interceptors need to have it unless they're launching async tasks. Likewise, let's collapse this struct.


<!-- Sent from Reviewable.io -->

2018-08-08 21:57 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/sender.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE0w5D6x-mwXbM0_M4:-LJQGOmzDkQH3qjSHds7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/sender.go#L151)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That looks good. Thanks.
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE22Y977NwcejJA776:-LJQGVuf6l8YYRLlHrKG:b-icsebg) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L61)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Aren't we still duplicating state then?
</blockquote></details>

we are duplicating state, yes. But I think it's OK enough - think of it as an implementation detail that the TCS also has this state, and it's read-only there. The Txn needs it in order to provide its API. It'd be good for this API to be different - to only allow setting these when the transaction is created and not changed afterwards.
Anyway, I wouldn't be arguing about these fields if I knew exactly what to do with them.
___
*[pkg/internal/client/txn.go, line 759 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE4aCg42kxZzS33tbE:-LJQHexu-tXQm8QzoHsY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L759)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Eh, I guess I'll hold my grievances for a later change.
</blockquote></details>

Done.
___
*[pkg/internal/client/txn.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE3zYo9Xpe6qfSpPpN:-LJQHjee5mYmke4YqsCt:b2wpsfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L819)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I prefer the "maybe" at the end (Google style), so that the method name starts with something more meaningful.

Yeah but that's not what we do everywhere else. It seems very off in this codebase. I'd switch it.
</blockquote></details>

But consistency for consistency's sake is not a thing. Everybody who understands what "maybe" means as a prefix (not that there's much to understand) will understand it as a suffix too. And as people open their mind to the possibility of putting it at the end, it will surely take off.
___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQJJHo5mzkr3vH07d_:b-x90s0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's also completely inconsistent with our codebase. consistency > personal preference.
</blockquote></details>

litigating elsewhere
___
*[pkg/kv/txn_interceptor_metrics.go, line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJQBdPX9pepcVU3uMBd:-LJQSHMlC9xHurNBx2pF:bjxytu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f5d6d666dde5168c7fc7ce26823ad223d0b54e5/pkg/kv/txn_interceptor_metrics.go#L33)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we need this lock? One of the biggest benefits of this architecture is that the interceptors don't even need to realize they're operating under lock. I don't think any of the interceptors need to have it unless they're launching async tasks. Likewise, let's collapse this struct.
</blockquote></details>

yeah... Although how do you square that thought with the fact that the method is called `SendLocked` (which I think is a good thing)?
I've remove the lock though.


<!-- Sent from Reviewable.io -->

2018-08-08 22:30 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/txn.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJE3zYo9Xpe6qfSpPpN:-LJQeFRS3w9U70pqljeU:bgkli40) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/internal/client/txn.go#L819)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But consistency for consistency's sake is not a thing. Everybody who understands what "maybe" means as a prefix (not that there's much to understand) will understand it as a suffix too. And as people open their mind to the possibility of putting it at the end, it will surely take off.
</blockquote></details>

compromised on a new name


<!-- Sent from Reviewable.io -->

2018-08-08 22:36 UTC, nvb reviewed
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQfcmO5gFXx17WDHWi:bvxo163) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

litigating elsewhere
</blockquote></details>

This wasn't changed.


<!-- Sent from Reviewable.io -->

2018-08-08 22:52 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQhIPUBvx5CQrggjtK:b-amn4hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This wasn't changed.
</blockquote></details>

changed; I was voted out in a 3-way pack first, no talking after scenario.


<!-- Sent from Reviewable.io -->

2018-08-08 23:01 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQlYgA8Skl58-hMyRe:b-stqn95) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

changed; I was voted out in a 3-way pack first, no talking after scenario.
</blockquote></details>

https://getyarn.io/yarn-clip/e4f43f12-95de-44b4-8dea-04a3f702e394


<!-- Sent from Reviewable.io -->

2018-08-08 23:02 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJQkirb1ppnvYC-NJ-k:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/txn_coord_sender.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-LJEK6S2-1tIqRZKx9AH:-LJQkyJq9I2T2u6_U-7N:b4kt7z4) ([raw file](https://github.com/cockroachdb/cockroach/blob/035cec90d98ced59c803dfd7c3b37f8e50cadceb/pkg/kv/txn_coord_sender.go#L670)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

changed; I was voted out in a 3-way pack first, no talking after scenario.
</blockquote></details>

![4x13_It_Gets_Better_(62).png](https://files.reviewableusercontent.io/images/reviewable/5438456/WSHp_jT6S0STxuE7JlRyI0OU/4x13_It_Gets_Better_(62).png)

This vote wasn't a mistake.


<!-- Sent from Reviewable.io -->

2018-08-08 23:04 UTC, andreimatei reviewed
bors r+

come on baby light my fire

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJQmAin0ZtgYaS9o935:bx3bq9t)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-09 01:31 UTC, andreimatei commented
Nathan, I've moved the seq num interceptor up in the stack to put it above the span refresher, which does retries (and in doing so was causing a race because the seq num interceptor kept changing the batch).

2018-08-09 03:15 UTC, nvb reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28185#-:-LJRfclp6aROLuK3yA53:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-09 03:45 UTC, merged