sql: Adds support for GROUPS mode of window framing
cockroachdb/cockroach pull request #28244
Opened 2018-08-03 15:11 UTC by yuzefovich

Adds support for GROUPS mode of window framing that
allows specifying the frame in terms of peer groups
which is like a mix of ROWS and RANGE introduced in
SQL:2011.

Incremental change towards: #27100.

Release note (sql change): CockroachDB now supports
GROUPS mode of window frame specification.

2018-08-03 15:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28244)
<!-- Reviewable:end -->

2018-08-08 14:04 UTC, knz reviewed
Can you please extend the commit message with a copious explanation of what this feature does with some examples. This will be useful for the docs team, but foremost to me as a reviewer to establish a baseline (what you expect your code to achieve) that I can use to evaluate the implementation.

Thanks in advance.

> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJOqKU0E0RiUO3lo1A_:b-8h1cc5)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-08 15:14 UTC, nvb requested changes
> Reviewed 12 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP3_N98E_3U5YIyIVK:-LJP3_NA9uKKB0yDrPN4:b-1j0utp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/window.go#L787)):*
> ```Go
> 			frameRun.RowIdx = 0
> 			frameRun.PeerGroupNumByRowIdx = make([]int, partition.Len())
> 			frameRun.PeerGroups = make([]*tree.PeerGroup, 0, tree.PeerGroupsInitialSize)
> ```

We can use a sliding window for these two structures as well, right? For instance, if the option is `GROUPS 1 PRECEDING` then we should only need to maintain this information for the current and previous peer group.
___
*[pkg/sql/window.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP4Rx88ncIBYDo6WXN:-LJP4Rx88ncIBYDo6WXO:b9zlr4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/window.go#L800)):*
> ```Go
> 			// Compute peer groups.
> 			peerGroupNum := 0
> 			for idx := 0; idx < frameRun.PartitionSize(); {
> ```

It seems unfortunate that we now need to compute all peer groups at once. How does this affect the efficiency of window functions without the `GROUPS` option? I think moving to a sliding window approach allows this to reduce to computing peer groups one at a time for the standard non-GROUPS case like we did before.
___
*[pkg/sql/distsqlrun/windower.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP5HWwDwmeRUB2MkkG:-LJP5HWwDwmeRUB2MkkH:bwmesx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/distsqlrun/windower.go#L474)):*
> ```Go
> 			frameRun.Rows = partition
> 			frameRun.RowIdx = 0
> 			frameRun.PeerGroupNumByRowIdx = make([]int, partition.Len())
> ```

Same comments as above.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 2338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP5LbG0UxvCJuji2CA:-LJP5LbG0UxvCJuji2CB:bvrscbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/logictest/testdata/logic_test/window#L2338)):*
> ```
> 
> query TTRRR
> SELECT group_name, product_name, price, avg(price) OVER (GROUPS BETWEEN 1 PRECEDING AND 2 PRECEDING), avg(price) OVER (ORDER BY price GROUPS BETWEEN CURRENT ROW AND CURRENT ROW) FROM products ORDER BY group_id
> ```

Nice tests as always! Add one more with very large GROUP spec in both directions.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP2XuQ5zrRLogLtFE0:-LJP2XuQ5zrRLogLtFE1:b-fk1owk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/sem/builtins/window_builtins.go#L199)):*
> ```
> wfr.PeerGroups[wfr.PeerGroupNumByRowIdx[wfr.RowIdx]]
> ```

nit: Pull this into a well-named variable so that this is easier to read.


<!-- Sent from Reviewable.io -->

2018-08-09 19:14 UTC, yuzefovich reviewed
I added a few examples in the commit message, but I think that better understanding of `GROUPS` mode might come from looking at the logic tests I added (there is a column which is the number of the peer group of the row) - I confirmed the results with beta PG 11 and my own understanding, so hopefully tests don't contain any errors. I think the easiest way would be to use `array_agg` as a window function, but currently it has a bug, and the PR to fix it is not merged yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJV56dg-vo_sMORX1RU:b-kmi6d9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/window.go, line 787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP3_N98E_3U5YIyIVK:-LJV-XklAVRH-p8_5zZN:b7xibva) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/window.go#L787)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can use a sliding window for these two structures as well, right? For instance, if the option is `GROUPS 1 PRECEDING` then we should only need to maintain this information for the current and previous peer group.
</blockquote></details>

Good point.

After our discussion, I implemented a helper `struct` based on a ring buffer that stores only necessary information.
___
*[pkg/sql/window.go, line 800 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP4Rx88ncIBYDo6WXN:-LJV0Y01BmnCFMi4ddVW:b-pvvee0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/window.go#L800)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems unfortunate that we now need to compute all peer groups at once. How does this affect the efficiency of window functions without the `GROUPS` option? I think moving to a sliding window approach allows this to reduce to computing peer groups one at a time for the standard non-GROUPS case like we did before.
</blockquote></details>

Addressed by the peer helper.
___
*[pkg/sql/distsqlrun/windower.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP5HWwDwmeRUB2MkkG:-LJV0e7kE1Ptky1yJjX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/distsqlrun/windower.go#L474)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same comments as above.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/window, line 2338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP5LbG0UxvCJuji2CA:-LJPgzMR0Kqg18u94b9-:bevhm6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/logictest/testdata/logic_test/window#L2338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice tests as always! Add one more with very large GROUP spec in both directions.
</blockquote></details>

Thanks! I added a lot of bounds options hoping to cover all possible valid combinations.
___
*[pkg/sql/sem/builtins/window_builtins.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJP2XuQ5zrRLogLtFE0:-LJV-NNp0cO2I5gsgHg0:b-jxb481) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2333969d499b753fc61e6ae5af8ea160adf546/pkg/sql/sem/builtins/window_builtins.go#L199)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> wfr.PeerGroups[wfr.PeerGroupNumByRowIdx[wfr.RowIdx]]
> ```

nit: Pull this into a well-named variable so that this is easier to read.
</blockquote></details>

This line was changed and should be pretty understandable now, please let me know if I should refactor it.


<!-- Sent from Reviewable.io -->

2018-08-14 17:53 UTC, yuzefovich commented
@nvanbenschoten @jordanlewis @knz Please take a look when you get a chance.

2018-08-14 18:23 UTC, nvb requested changes
> Reviewed 17 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtb5Vi8ddTkmoTGgCA:-LJtb5Vi8ddTkmoTGgCB:b-27qfqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L23)):*
> ```Go
> }
> 
> // PeerGroupsIndicesHelper computes peer groups using given PeerGroupChecker.
> ```

using the given
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtfMAuDgefISm5IKRC:-LJtfMAuDgefISm5IKRD:b-1vj4ve) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L35)):*
> ```Go
> 	peerGrouper           PeerGroupChecker
> 	headPeerGroupNum      int  // number of the peer group at the head of the queue
> 	tailPeerGroupRowCount int  // number of rows within the peer group at the tail of the queue
> ```

Why do we need this extra state? Isn't it already in `groups`?
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcIHn4TuHDajV4VQu:-LJtcIHn4TuHDajV4VQv:bu3oq2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L82)):*
> ```Go
> 			// Frame starts after all peer groups of the partition.
> 			p.allPeerGroupsSkipped = true
> 			// TODO: we won't need info about peer groups in this case. Should we free up the memory?
> ```

Add a name to this todo.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcRnCEZJHNUlw7ERu:-LJtcRnCEZJHNUlw7ERv:b-il1wvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L91)):*
> ```Go
> 	// Compute the first peer group that is within the frame.
> 	p.groups.Add(&IndexedValue{Idx: startIdxOfFirstPeerGroupWithinFrame})
> 	p.tailPeerGroupRowCount = 1
> ```

Are we overwriting what we just set above?
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJte36ZBFFwh_z82x60:-LJte36ZBFFwh_z82x61:b-ttwrly) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L169)):*
> ```Go
> 	// Compute the next peer group that is just entering the frame.
> 	p.groups.Add(&IndexedValue{Idx: nextPeerGroupStartIdx})
> 	p.tailPeerGroupRowCount = 1
> ```

This looks strange to me too. What's going on with `tailPeerGroupRowCount`?
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtey_y5zmu37DC7GLU:-LJtey_y5zmu37DC7GLV:b-kfpsrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L181)):*
> ```Go
> }
> 
> // Reset allows us to reuse the same helper for all partitions when computing
> ```

Why split this from init?


<!-- Sent from Reviewable.io -->

2018-08-14 18:58 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtb5Vi8ddTkmoTGgCA:-LJtgX9aCWuwYIWzZNkA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L23)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

using the given
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtfMAuDgefISm5IKRC:-LJth09A5p3IQMxtGs7J:b-jx5ysh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we need this extra state? Isn't it already in `groups`?
</blockquote></details>

The way I use `RingBuffer` is that it contains `IndexedValue`s with empty `Value` and `Idx` equal to index of the first peer of the peer group that `IndexedValue` represents, so in order to calculate `PeerRowCount` I look at the difference between `Idx`s of two consecutive peer groups with a special case of the tail peer group - since it doesn't have the following peer group, I store its row count in this `tailPeerGroupRowCount`.

I agree, it's pretty dirty way of doing it, but I couldn't come up with another way to reuse existing code of `RingBuffer`. Please let me know if you have ideas of how to make `RingBuffer` more general - so that we can use for this helper and for sliding window.

One way I can see to make it more clear is to set `Value` to peer row count and operate with `DInt`s. What do you think?
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcIHn4TuHDajV4VQu:-LJtiNKa5lf9Lg_P1K4H:bcu5y2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a name to this todo.
</blockquote></details>

Done.

This TODO is more like an actual question. My thinking is that we could free up the underlying memory, but we probably will be reusing the same helper later. Probably we should keep the memory.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcRnCEZJHNUlw7ERu:-LJtjzHFBKf8RA13GDrF:bnirsr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L91)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we overwriting what we just set above?
</blockquote></details>

Yes, we added a new peer group to the end of the queue, so the tail has only one row so far.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJte36ZBFFwh_z82x60:-LJtkImh-rSM4J2OugEO:b-bbzf3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This looks strange to me too. What's going on with `tailPeerGroupRowCount`?
</blockquote></details>

Same as above - new peer group is at the tail of the queue, so we update `tailPeerGroupRowCount`.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtey_y5zmu37DC7GLU:-LJtldEZERXfzVj1VWU2:b-l1ylhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L181)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why split this from init?
</blockquote></details>

No reason, fixed.


<!-- Sent from Reviewable.io -->

2018-08-15 04:30 UTC, nvb requested changes
> Reviewed 1 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtfMAuDgefISm5IKRC:-LJvkmSr1cZ8ne54yXoW:byz6wdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L35)):*
> since it doesn't have the following peer group, I store its row count in this tailPeerGroupRowCount.

Why not just add one more element to the end of the RingBuffer then? This would eventually be set to `wfr.PartitionSize()` when we get to the end of the partition.

> I agree, it's pretty dirty way of doing it, but I couldn't come up with another way to reuse existing code of RingBuffer. Please let me know if you have ideas of how to make RingBuffer more general - so that we use both in for this helper and for sliding window.

The idiomatic thing to do here (given Go's lack of generics) would be to change `RingBuffer's` `values []*IndexedValue`  slice to `values []interface{}`. This would allow any client to store whatever type then need in the buffer. For instance, the `slidingWindow` could store `indexedValue`s while the `PeerGroupsIndicesHelper` could store `int`s. They would then type assert the `interface{}` values they get out. Once you make the container that generic, it could even be moved into a `util` package.
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcIHn4TuHDajV4VQu:-LJvkzgV82HsVHOU55lK:bclcpcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L82)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.

This TODO is more like an actual question. My thinking is that we could free up the underlying memory, but we probably will be reusing the same helper later. Probably we should keep the memory.
</blockquote></details>

Yeah, this seems fine as is.


<!-- Sent from Reviewable.io -->

2018-08-15 14:49 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtfMAuDgefISm5IKRC:-LJy2R2L8ETOeqAoi4Ni:b-ve9xbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> since it doesn't have the following peer group, I store its row count in this tailPeerGroupRowCount.

Why not just add one more element to the end of the RingBuffer then? This would eventually be set to `wfr.PartitionSize()` when we get to the end of the partition.

> I agree, it's pretty dirty way of doing it, but I couldn't come up with another way to reuse existing code of RingBuffer. Please let me know if you have ideas of how to make RingBuffer more general - so that we use both in for this helper and for sliding window.

The idiomatic thing to do here (given Go's lack of generics) would be to change `RingBuffer's` `values []*IndexedValue`  slice to `values []interface{}`. This would allow any client to store whatever type then need in the buffer. For instance, the `slidingWindow` could store `indexedValue`s while the `PeerGroupsIndicesHelper` could store `int`s. They would then type assert the `interface{}` values they get out. Once you make the container that generic, it could even be moved into a `util` package.
</blockquote></details>

Great suggestion! I was wondering whether in Go there is an equivalent to `Object` class from Java.

I did as you advised, and now we don't need that special case for the last peer group, and the code seems a little cleaner. Still, it is pretty ugly, but I'm not sure if we can avoid that. Let me know if you have another great suggestions :)
___
*[pkg/sql/sem/tree/window_funcs_util.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJtcIHn4TuHDajV4VQu:-LJy343y4SsyBc6p9Hyw:b-54avio) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2cc0454bb2c2b2dfbefcf67ce39de1df2834d1f/pkg/sql/sem/tree/window_funcs_util.go#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, this seems fine as is.
</blockquote></details>

Ok, thanks.


<!-- Sent from Reviewable.io -->

2018-08-15 15:34 UTC, nvb requested changes
> Reviewed 9 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCboUCsp9wMjyIhmO:-LJyCboUCsp9wMjyIhmP:bufucq) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/sql/sem/tree/window_funcs_util.go#L28)):*
> ```Go
> 
> // PeerGroup contains information about a single peer group.
> type PeerGroup struct {
> ```

Does this need to be exported?
___
*[pkg/util/ring_buffer.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDCBg7xXABQUcTnag:-LJyDCBg7xXABQUcTnah:b-8gj6o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> 
> package util
> ```

I think it's actually justified to create a new `pkg/util/ring` package and put these two files in it. We'd then rename `RingBuffer` to just `Buffer`.
___
*[pkg/util/ring_buffer.go, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCJ_FE2ULgComdXMk:-LJyCJ_FE2ULgComdXMl:bufucq) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L18)):*
> ```Go
> 
> // RingBufferInitialSize defines the initial size of the ring buffer.
> const RingBufferInitialSize = 8
> ```

Does this need to be exported?
___
*[pkg/util/ring_buffer.go, line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyC8_z3mu5mxsb1Hg6:-LJyC8_z3mu5mxsb1Hg7:bqhjoc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L20)):*
> ```Go
> const RingBufferInitialSize = 8
> 
> // RingBuffer is a deque maintained over a ring buffer.
> ```

Make a note that this is backed by a slice as opposed to a linked-list to distinguish it from https://golang.org/pkg/container/ring/.
___
*[pkg/util/ring_buffer.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCj8h7cjh12pktZ6a:-LJyCj8h7cjh12pktZ6b:buoj11b) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L26)):*
> ```Go
> 	tail   int // the index of the first position right after the end of the deque.
> 
> 	nonEmpty bool // indicates whether the deque is empty, necessary to distinguish
> ```

go nit: if a comment is going to extend to a second line, place it above the code instead of to its right.
___
*[pkg/util/ring_buffer.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD6821Lav2ol4ZTpq:-LJyD6821Lav2ol4ZTpr:b-ujgy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L31)):*
> ```Go
> 
> // Len returns the number of elements in the deque.
> func (r *RingBuffer) Len() int {
> ```

Doesn't need to operate on a pointer.
___
*[pkg/util/ring_buffer.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD9Y4CDsAi2x4ayrN:-LJyD9Y4CDsAi2x4ayrO:b-ujgy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L97)):*
> ```Go
> 
> // Get returns an element at position pos in the deque (zero-based).
> func (r *RingBuffer) Get(pos int) interface{} {
> ```

Doesn't need to operate on a pointer.
___
*[pkg/util/ring_buffer.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDAEJ0ALpdH3QltVl:-LJyDAEJ0ALpdH3QltVm:b-ujgy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L105)):*
> ```Go
> 
> // GetFirst returns an element at the front of the deque.
> func (r *RingBuffer) GetFirst() interface{} {
> ```

Doesn't need to operate on a pointer.
___
*[pkg/util/ring_buffer.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDAad5JmoInFiVsd5:-LJyDAad5JmoInFiVsd6:b-ujgy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L113)):*
> ```Go
> 
> // GetLast returns an element at the front of the deque.
> func (r *RingBuffer) GetLast() interface{} {
> ```

Doesn't need to operate on a pointer.
___
*[pkg/util/ring_buffer_test.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD-Kd3dsU6Moa-IEe:-LJyD-Kd3dsU6Moa-IEf:b-hsexup) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer_test.go#L26)):*
> ```Go
> 
> func testRingBuffer(t *testing.T, count int) {
> 	ring := RingBuffer{}
> ```

nit: `var ring RingBuffer`


<!-- Sent from Reviewable.io -->

2018-08-15 17:11 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/window_funcs_util.go, line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCboUCsp9wMjyIhmO:-LJyIped9rP9rzIS4rC5:b4yyme9) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/sql/sem/tree/window_funcs_util.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be exported?
</blockquote></details>

Nope, thanks for the catch.
___
*[pkg/util/ring_buffer.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDCBg7xXABQUcTnag:-LJyIBmE02t-cBW_9zpT:b-s2rc75) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L15)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think it's actually justified to create a new `pkg/util/ring` package and put these two files in it. We'd then rename `RingBuffer` to just `Buffer`.
</blockquote></details>

Good point, thanks.
___
*[pkg/util/ring_buffer.go, line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCJ_FE2ULgComdXMk:-LJyIkAQ1RVUNkFZ6SlN:b-qf5j66) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be exported?
</blockquote></details>

Nope, I forget sometimes about lower vs capital letters, thanks.
___
*[pkg/util/ring_buffer.go, line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyC8_z3mu5mxsb1Hg6:-LJyGd3WE-AW9yXP0NWL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note that this is backed by a slice as opposed to a linked-list to distinguish it from https://golang.org/pkg/container/ring/.
</blockquote></details>

Done.
___
*[pkg/util/ring_buffer.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyCj8h7cjh12pktZ6a:-LJyGeSqETGiaqTA52KF:b8pj62w) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

go nit: if a comment is going to extend to a second line, place it above the code instead of to its right.
</blockquote></details>

I like this convention.
___
*[pkg/util/ring_buffer.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD6821Lav2ol4ZTpq:-LJyGy4ADHFfv6Da0nEI:bl5o2pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't need to operate on a pointer.
</blockquote></details>

I switched to value receivers for all `Get` methods, but isn't it faster to have pointer receivers because they do not require copying the value? I mean we need to be careful not to modify the value through the pointer, but if we are careful, it should be faster, right? Also, is it ok to have a mix of value and pointer receivers for a single struct?
___
*[pkg/util/ring_buffer.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD9Y4CDsAi2x4ayrN:-LJyGqKwCcbr4ymV-CXW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't need to operate on a pointer.
</blockquote></details>

Done.
___
*[pkg/util/ring_buffer.go, line 105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDAEJ0ALpdH3QltVl:-LJyGr2X5LACJdxs5Eq4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't need to operate on a pointer.
</blockquote></details>

Done.
___
*[pkg/util/ring_buffer.go, line 113 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyDAad5JmoInFiVsd5:-LJyGrZU6DSxyEH8dnXD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L113)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Doesn't need to operate on a pointer.
</blockquote></details>

Done.
___
*[pkg/util/ring_buffer_test.go, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD-Kd3dsU6Moa-IEe:-LJyHjvKC6YcbvpxO4h0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer_test.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `var ring RingBuffer`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-15 18:07 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJykn-aBVmQi0QFFvCz:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/ring_buffer.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD6821Lav2ol4ZTpq:-LJykQZ_5Y2tXdawtmxw:bnzloam) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L31)):*
> but isn't it faster to have pointer receivers because they do not require copying the value? I mean we need to be careful not to modify the value through the pointer, but if we are careful, it should be faster, right?

This does require copying the value, but the value is only 48 bytes, so it shouldn't make much of a difference.

> Also, is it ok to have a mix of value and pointer receivers for a single struct?

Yes, that's ok.

The primary benefit of doing this is that it can avoid forcing a value to escape from the stack. Since we're almost always going to be using its other methods though, that probably doesn't matter. Feel free to switch these back if you'd like.


<!-- Sent from Reviewable.io -->

2018-08-15 18:28 UTC, yuzefovich reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJyps4b9uedoK4I4D6A:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/ring_buffer.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-LJyD6821Lav2ol4ZTpq:-LJypu4UCvIYtV4jFZ81:b4e02h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/054cb58c84cdd260bb8b31fc59d80148e7f3c2e4/pkg/util/ring_buffer.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> but isn't it faster to have pointer receivers because they do not require copying the value? I mean we need to be careful not to modify the value through the pointer, but if we are careful, it should be faster, right?

This does require copying the value, but the value is only 48 bytes, so it shouldn't make much of a difference.

> Also, is it ok to have a mix of value and pointer receivers for a single struct?

Yes, that's ok.

The primary benefit of doing this is that it can avoid forcing a value to escape from the stack. Since we're almost always going to be using its other methods though, that probably doesn't matter. Feel free to switch these back if you'd like.
</blockquote></details>

Thanks for the explanation, I'll follow your suggestion and have a mix of pointer and value receivers.


<!-- Sent from Reviewable.io -->

2018-08-15 19:00 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, great work and really nice tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJyxUo4Ee45k24Mg4Hq:b-g4s9qd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-08-15 20:06 UTC, yuzefovich reviewed
Thanks for the review!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28244#-:-LJzBWKV4gP3btjJ7FoD:b-bk4x2e)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-15 20:14 UTC, yuzefovich commented
bors r-

2018-08-16 01:09 UTC, yuzefovich commented
bors r+

2018-08-16 01:40 UTC, yuzefovich commented
bors r+

2018-08-16 02:14 UTC, yuzefovich commented
Let's try one more time.

bors r+

2018-08-16 07:02 UTC, knz commented
I rebased this for you.

bors r+

2018-08-16 07:25 UTC, merged