sql: Introduce fast path delete for cascading interleaved tables
cockroachdb/cockroach pull request #28330
Opened 2018-08-07 14:45 UTC by emsal1863

This patch introduces fast deletes for interleaved tables with ON DELETE
CASCADE. Deleting from a table with other tables interleaved in it will
now simply call KV DelRanges instead of going through all of the
foreign key checks and cascades for the interleaved tables.

This fast path is *not* activated when:
* The table or any of its interleaved tables have any secondary indices
* The table or any of its interleaved tables are referenced by any other
table outside of them by foreign key
* Any of the interleaved relationships are not ON DELETE CASCADE

Release note: None

closes #27990

2018-08-07 14:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28330)
<!-- Reviewable:end -->

2018-08-07 14:53 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqVUA5ZvKkFPs76lx:-LJJqVUA5ZvKkFPs76ly:bby54pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8818be2ad796d63a0832c99839e01c02dca65002/pkg/sql/delete.go#L350)):*
> ```Go
> }
> 
> func canDeleteFastInterleaved(table TableDescriptor, fkTables sqlbase.TableLookupsByID) bool {
> ```

I'm not actually entirely sure how I'm going to test this as I'm not too sure how to deal with table descriptors from the tests.
___
*[pkg/sql/delete.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqoy86C_iJ89oJm9V:-LJJqoy86C_iJ89oJm9W:b9im1ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/8818be2ad796d63a0832c99839e01c02dca65002/pkg/sql/delete.go#L489)):*
> ```Go
> 
> 		for i, span := range scan.spans {
> 			if span.EndKey.Compare(span.EndKey.PrefixEnd()) == -1 {
> ```

I feel like using `span.EndKey.PrefixEnd()` is sort of a hack and if there's a better way to get to the end of the interleaved keys I'd happily take it.

Using KV tracing I found that the `PrefixEnd` here returns something like `/Table/<TableA>/<index>/<value>/NULL` (I'd like to clarify what that means actually).

When you do a `DelRange` from the beginning of the span to this value it does delete all of the interleaved keys, because all of them will have values like `/Table/<TableA>/<index>/value/#/<TableB>/...`, but I don't really know if this is really the most secure way we could be doing this.


<!-- Sent from Reviewable.io -->

2018-08-07 17:54 UTC, andreimatei commented
No release note? Seems like a good win.

2018-08-08 12:07 UTC, spencerkimball commented
It’s probably best not to use DelRange but instead issue individual deletes. This avoids pressure on the write timestamp cache if there are many deletes, which will cause txns to retry unnecessarily. If the individual deletes are in a batch should be as fast.

2018-08-08 19:55 UTC, BramGruneir requested changes
> Reviewed 1 of 2 files at r3, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqVUA5ZvKkFPs76lx:-LJQ-BFk71_6iTJIZgU0:b-qifpk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L350)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

I'm not actually entirely sure how I'm going to test this as I'm not too sure how to deal with table descriptors from the tests.
</blockquote></details>

Unit test is the only way I think of.
___
*[pkg/sql/delete.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqoy86C_iJ89oJm9V:-LJQ4Jwi02lTqt1uN9dJ:b-o05g0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L489)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

I feel like using `span.EndKey.PrefixEnd()` is sort of a hack and if there's a better way to get to the end of the interleaved keys I'd happily take it.

Using KV tracing I found that the `PrefixEnd` here returns something like `/Table/<TableA>/<index>/<value>/NULL` (I'd like to clarify what that means actually).

When you do a `DelRange` from the beginning of the span to this value it does delete all of the interleaved keys, because all of them will have values like `/Table/<TableA>/<index>/value/#/<TableB>/...`, but I don't really know if this is really the most secure way we could be doing this.
</blockquote></details>

I don't understand your question here.  What's the concern with using prefixend?

Also, what is this compare for?  
___
*[pkg/sql/delete.go, line 352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ-kIv2vCtCSa2wGuk:-LJQ-kIv2vCtCSa2wGul:b1gxnq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L352)):*
> ```Go
> func canDeleteFastInterleaved(table TableDescriptor, fkTables sqlbase.TableLookupsByID) bool {
> 
> 	// If there are no interleaved tables then don't take this path.
> ```

Why not? This whole check seems unneeded to me.  And you don't even use the totalInterleaved value anywhere else.  So if you do choose to keep it, just turn it into a bool and quickly exist if one is found.
___
*[pkg/sql/delete.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ0CUyEANsgx_bPw3n:-LJQ0CUzBfPb1XFmnghD:b-my33j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L358)):*
> ```Go
> 	}
> 	if totalInterleaved == 0 {
> 		log.Warning(context.TODO(), "Base table has no interleaved tables")
> ```

leftover debugging code, a bunch of it
___
*[pkg/sql/delete.go, line 364 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ36me00aAXTD1mEb2:-LJQ36me00aAXTD1mEb3:b-crkxa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L364)):*
> ```Go
> 	// contains all table IDs that are directly or indirectly interleaved into `table`,
> 	// including `table` itself
> 	interleavedMemo := make(map[sqlbase.ID]struct{})
> ```

I don't understand the need for the memo here.  You can't have circular interleaved tables.
___
*[pkg/sql/delete.go, line 366 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ32JPA6Tz_wu26HV2:-LJQ32JQ2bnmq-iiaHB4:bdv8683) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L366)):*
> ```Go
> 	interleavedMemo := make(map[sqlbase.ID]struct{})
> 	interleavedQueue := make([]sqlbase.ID, 0)
> 	interleavedQueue = append(interleavedQueue, table.ID)
> ```

I think you can just create the queue with the single item directly.
___
*[pkg/sql/delete.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ2Mfn-osmWsyOeWwP:-LJQ2Mfq-FLYFyBdqiAn:bm03d71) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L369)):*
> ```Go
> 
> 	// if the base table is interleaved in another table, fail
> 	// TODO let this succeed if this is part of another table's fast path (???).
> ```

TODOs are fine to leave in the code, but use our standard formatting

TODO(emmanuel): consider letting this succeed if this is part of another table's fast path.

That being said, I don't understand this one.
___
*[pkg/sql/delete.go, line 396 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ3Qfe8oYqm_DGXkvb:-LJQ3QfgBdLvp6vvdabk:bxim1kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L396)):*
> ```Go
> 
> 			// interleavedIdxs will contain all of the table and index IDs of the indexes interleaved in this one
> 			interleavedIdxs := make(map[sqlbase.ID]map[sqlbase.IndexID]struct{})
> ```

Why do you need this map?  Just push the table id of the interleaved table on the queue.  Am I missing some other check?  Also, put this at the end, so the other checks can fail earlier before you go adding to the queue.
___
*[pkg/sql/delete_test.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4r5M8LiUNPGIdc-Q:-LJQ4r5M8LiUNPGIdc-R:b-p4dp0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L74)):*
> ```Go
> 
> 	drop := func(tables ...string) {
> 		// dropping has to be done in reverse so no drop causes a foreign key violation
> ```

Or just drop with cascade I think.
___
*[pkg/sql/delete_test.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4zV8CVmNa-pLea3X:-LJQ4zV8CVmNa-pLea3Y:bl85lva) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L82)):*
> ```Go
> 	}
> 
> 	// This function is to be called at the beginning of each sub-benchmark to set up the necessary tables.
> ```

This is not a benchmark.
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJQ4kKACYcHHIQndwxu:bu57bz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
> ```Go
> 	t.Run("canDeleteFastInterleaved, two children", testCheck(true, "parent", "child", "sibling", "grandchild"))
> 	t.Run("canDeleteFastInterleaved, two children", testCheck(true, "parent", "child", "grandchild"))
> 	//t.Run("canDeleteFastInterleaved, two children", testCheck(false, "parent", "childNoCascade")) // turning this on returns a "panic: missing table" triggered by trying to get the table descriptor for childNoCascade.
> ```

Ick.  Why is that?
___
*[pkg/sql/tablewriter_delete.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ55CRBOmusVfnzU3P:-LJQ55CRBOmusVfnzU3Q:b-hz8qno) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/tablewriter_delete.go#L100)):*
> ```Go
> 	ctx context.Context, scan *scanNode, autoCommit autoCommitOpt, traceKV bool,
> ) (rowCount int, err error) {
> 	log.Info(ctx, "doing fastDelete")
> ```

remove this debug line
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ5ggF35aa1jmwBK5I:-LJQ5ggF35aa1jmwBK5J:by06dmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/logictest/testdata/logic_test/interleaved#L386)):*
> ```
> ----
> 1
> ```

please add some tests to see if the fastpath is used for tracing, then you can test the edge cases where it can't be used and en [...]

2018-08-08 21:14 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 396 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ3Qfe8oYqm_DGXkvb:-LJQEpDA5XIVCXY5Glf1:b-7vkubr) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L396)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why do you need this map?  Just push the table id of the interleaved table on the queue.  Am I missing some other check?  Also, put this at the end, so the other checks can fail earlier before you go adding to the queue.
</blockquote></details>

Below there's a check to determine if any of the foreign key references referencing the current index are different from the interleaved foreign key reference. Essentially it checks `idx.ReferencedBy` against `idx.InterleavedBy` to see if `ReferencedBy` contains any external references.

I don't see how it's possible to check these external references without this map, or another map of some sort (maybe I only need to store the table IDs instead of table and index ID?). I do agree on the point about pushing to the queue only at the end.


<!-- Sent from Reviewable.io -->

2018-08-08 21:25 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ0CUyEANsgx_bPw3n:-LJQQ2D07MpYRzphVt6-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L358)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

leftover debugging code, a bunch of it
</blockquote></details>

Done.
___
*[pkg/sql/delete.go, line 364 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ36me00aAXTD1mEb2:-LJQQ2X52mIr2BDLkmFV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L364)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I don't understand the need for the memo here.  You can't have circular interleaved tables.
</blockquote></details>

Done.
___
*[pkg/sql/delete.go, line 366 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ32JPA6Tz_wu26HV2:-LJQQ4FS-28jHt8r0Y5Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L366)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think you can just create the queue with the single item directly.
</blockquote></details>

Done.
___
*[pkg/sql/delete.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ2Mfn-osmWsyOeWwP:-LJQQ62H59BujEvS4UWD:bs3g8gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L369)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

TODOs are fine to leave in the code, but use our standard formatting

TODO(emmanuel): consider letting this succeed if this is part of another table's fast path.

That being said, I don't understand this one.
</blockquote></details>

Done (for the other one, removed this one; will elaborate this one later)
___
*[pkg/sql/tablewriter_delete.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ55CRBOmusVfnzU3P:-LJQQOSM-CJzeDxbUYri:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/tablewriter_delete.go#L100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

remove this debug line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-09 14:57 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqoy86C_iJ89oJm9V:-LJUAamL0Ltc7J5Rdm0C:b-fdzq21) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L489)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I don't understand your question here.  What's the concern with using prefixend?

Also, what is this compare for?  
</blockquote></details>

Done.

also we've ironed out the details for the possible problem and unless we change our KV encoding for interleaved tables, using PrefixEnd should be fine.


<!-- Sent from Reviewable.io -->

2018-08-09 15:12 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete_test.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4r5M8LiUNPGIdc-Q:-LJUEHBP98mb7tiYzJ3v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L74)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Or just drop with cascade I think.
</blockquote></details>

Done.
___
*[pkg/sql/delete_test.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4zV8CVmNa-pLea3X:-LJUEM2U52ho3wWLwDXe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L82)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This is not a benchmark.
</blockquote></details>

Done.
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJUC2sDC--ZP4g9R-_W:behrzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Ick.  Why is that?
</blockquote></details>

It doesn't look like the table is getting dropped so I have a feeling this might be some sort of bug with `GetTableDescriptor` in testutils.


<!-- Sent from Reviewable.io -->

2018-08-09 19:04 UTC, BramGruneir requested changes
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ2Mfn-osmWsyOeWwP:-LJV37tW3ojTI0c1HCev:b32wtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L369)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done (for the other one, removed this one; will elaborate this one later)
</blockquote></details>

ok
___
*[pkg/sql/delete.go, line 396 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ3Qfe8oYqm_DGXkvb:-LJV3HtG6kWFnjzUxpkY:b7yclp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L396)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Below there's a check to determine if any of the foreign key references referencing the current index are different from the interleaved foreign key reference. Essentially it checks `idx.ReferencedBy` against `idx.InterleavedBy` to see if `ReferencedBy` contains any external references.

I don't see how it's possible to check these external references without this map, or another map of some sort (maybe I only need to store the table IDs instead of table and index ID?). I do agree on the point about pushing to the queue only at the end.
</blockquote></details>

Why not forward check instead of back checking?  Get the indexes and fks of the interleaved tables before adding them to the queue. 


<!-- Sent from Reviewable.io -->

2018-08-09 20:48 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqVUA5ZvKkFPs76lx:-LJVPT2y0M0CLXbmBRDp:b-lzam1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L350)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Unit test is the only way I think of.
</blockquote></details>

Done (unit test work still going) 
___
*[pkg/sql/delete.go, line 352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ-kIv2vCtCSa2wGuk:-LJVQtMf9c05sHNGqVgS:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not? This whole check seems unneeded to me.  And you don't even use the totalInterleaved value anywhere else.  So if you do choose to keep it, just turn it into a bool and quickly exist if one is found.
</blockquote></details>

Done
___
*[pkg/sql/delete.go, line 369 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ2Mfn-osmWsyOeWwP:-LJVQSmNC2P2HVLIzdcx:bc2ktpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L369)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Removed this as well. Perhaps it's best to add TODOs when we have more discussion about using the interleaved fast path in more cases.
___
*[pkg/sql/delete.go, line 396 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ3Qfe8oYqm_DGXkvb:-LJVPX5I2eUt6faFYj3r:b-jkmzee) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete.go#L396)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why not forward check instead of back checking?  Get the indexes and fks of the interleaved tables before adding them to the queue. 
</blockquote></details>

Done

We had a discussion about this earlier offline and this issue appears to be resolved

- back checking is actually necessary to check for external references that aren't interleaved
- easiest simplification here seems to be checking if the lengths of InterleavedBy and ReferencedBy are the same but that doesn't check to make sure all of the indexes match
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ5ggF35aa1jmwBK5I:-LJVQEe60u9QNnDXNBO3:b-896fjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/logictest/testdata/logic_test/interleaved#L386)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

please add some tests to see if the fastpath is used for tracing, then you can test the edge cases where it can't be used and ensure it isn't.
</blockquote></details>

Done 


<!-- Sent from Reviewable.io -->

2018-08-14 16:59 UTC, emsal1863 commented
All CR comments have been addressed; @spencerkimball the second/third commit in this PR contains the implementation with `Del` instead of `DelRange`. Here are the performance numbers for each:

fast path:

```
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved-8             2000000000             0.08 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_sibling-8     1000000000             0.23 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_grandchild-8             1000000000             0.22 ns/op
```

fast path with scan + del instead of delrange:

```
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved-8             2000000000             0.19 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_sibling-8       100000         10123 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_grandchild-8                 2000        511899 ns/op
``` 

So there is a sizable slowdown when switching away from `DelRange`.

Here's the numbers from master:
```
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved-8         	      20	  50800162 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_sibling-8 	       1 1557171104 ns/op
BenchmarkMultiRowFKChecks/deleteRowsFromParent_interleaved_grandchild-8         	       1 2397660316 ns/op
```

2018-08-14 18:30 UTC, BramGruneir requested changes
Save a branch with the point delete commit in it, and then remove the extra commit form this branch.  (just post a link to the other branch).

After that, I'll give it one more pass, but I think this is just about ready to go.

> Reviewed 2 of 3 files at r11, 2 of 3 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-:-LJtfVoZ5ipjTtRZ1dA-:b-e0f2z0)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 476 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJtfQQvEX5pTFKgfVDe:-LJtfQQvEX5pTFKgfVDf:b-kjdfd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee61a0a27695cec0cb169d8dc0878825940a05b7/pkg/sql/delete.go#L476)):*
> ```Go
> 	}
> 
> 	log.Info(ctx, "delete: fast path is available")
> ```

Leftover debugging log.
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJtg17g11xOEK-rTJb7:bjm2yac) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

It doesn't look like the table is getting dropped so I have a feeling this might be some sort of bug with `GetTableDescriptor` in testutils.
</blockquote></details>

See if you can recreate this in a test in a new branch.  Make it as minimal as possible then we can post an issue for it as a bug.  
___
*[pkg/sql/tablewriter_delete.go, line 94 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJtgYekCIvoK0exdHSq:-LJtgYekCIvoK0exdHSr:bkqkb6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a242626416942ea856e7577888fdde02e2783f7/pkg/sql/tablewriter_delete.go#L94)):*
> ```Go
> }
> 
> func (td *tableDeleter) fastDeleteInterleaved(
> ```

This could obviously be cleaned up, but since it's being cut, I'll leave it alone.


<!-- Sent from Reviewable.io -->

2018-08-14 18:52 UTC, emsal0 reviewed
> Save a branch with the point delete commit in it, and then remove the extra commit form this branch. (just post a link to the other branch).

https://github.com/emsal1863/cockroach/tree/interleaved-fast-path-deletes-point

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-:-LJtk8MuEdRAbXvmfJhD:b5359h4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 476 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJtfQQvEX5pTFKgfVDe:-LJtlXwb31bGjj5H9yDg:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee61a0a27695cec0cb169d8dc0878825940a05b7/pkg/sql/delete.go#L476)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Leftover debugging log.
</blockquote></details>

Done
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJtlYvq-69jhsnr5xL-:bebrt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

See if you can recreate this in a test in a new branch.  Make it as minimal as possible then we can post an issue for it as a bug.  
</blockquote></details>

Will do


<!-- Sent from Reviewable.io -->

2018-08-14 20:19 UTC, BramGruneir requested changes
Almost there!

> Reviewed 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-:-LJu4k2V3f-8kmASQmqS:b-debr86)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJu3PiN1KlbJMHpWfKS:b-fov0fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
> ```Go
> func canDeleteFastInterleaved(table TableDescriptor, fkTables sqlbase.TableLookupsByID) bool {
> 
> 	// If there are no interleaved tables then don't take the fast path.
> ```

Please add a comment here about why we don't want the fast path if there are no interleaved tables.  This would be to avoid overusing range_del.
___
*[pkg/sql/delete.go, line 364 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3tBGAwdbkTUKmvcB:-LJu3tBGAwdbkTUKmvcC:byng249) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L364)):*
> ```Go
> 	}
> 
> 	// contains all table IDs that are directly or indirectly interleaved into `table`,
> ```

This comment is wrong.
___
*[pkg/sql/delete.go, line 366 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3ucZ9PnW35L42CJl:-LJu3ucZ9PnW35L42CJm:b-xmkii0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L366)):*
> ```Go
> 	// contains all table IDs that are directly or indirectly interleaved into `table`,
> 	// including `table` itself
> 	interleavedQueue := []sqlbase.ID{table.ID}
> ```

This should be defined right before the for statement that uses it.
___
*[pkg/sql/delete.go, line 371 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3bq98f_qP-JsPM8f:-LJu3bq98f_qP-JsPM8g:b-b5e9ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L371)):*
> ```Go
> 	for _, idx := range fkTables[table.ID].Table.AllNonDropIndexes() {
> 		if len(idx.Interleave.Ancestors) > 0 {
> 			log.Warning(context.TODO(), "Base table is interleaved in another one")
> ```

This shouldn't be a warning, but a trace statement perhaps?  Or just remove it entirely.
___
*[pkg/sql/delete.go, line 395 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4C4kEsH0h5ujfDhy:-LJu4C4kEsH0h5ujfDhz:b-ihhebn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L395)):*
> ```Go
> 			interleavedIdxs := make(map[sqlbase.ID]map[sqlbase.IndexID]struct{})
> 			for _, ref := range idx.InterleavedBy {
> ```

nit: extra empty line.
___
*[pkg/sql/delete.go, line 401 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4N2hANO5djSEftkC:-LJu4N2hANO5djSEftkD:bvn9ju2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L401)):*
> ```Go
> 				interleavedIdxs[ref.Table][ref.Index] = struct{}{}
> 
> 				// Append the next tables to inspect to the queue
> ```

this comment is in the wrong place and doesn't tell you more than what the code actual does.  
___
*[pkg/sql/delete.go, line 426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4YCwA60CIrvzA5tB:-LJu4YCwA60CIrvzA5tC:b-c59hrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L426)):*
> ```Go
> 				interleavedQueue = append(interleavedQueue, ref.Table)
> 			}
> ```

extra line
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJu4pVyEleLXd-wEItK:bfdf5sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Then reference that new issue here.  Or remove the testcase entirely, just make sure you have coverage.


<!-- Sent from Reviewable.io -->

2018-08-14 20:45 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJu6AmmBQSZQ9gFpqsC:b-2hmxfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a comment here about why we don't want the fast path if there are no interleaved tables.  This would be to avoid overusing range_del.
</blockquote></details>

Done - updated comment

To be clear, DelRange is used for the regular fast path as well. The real reason for why we fail the fast path in this case is that there are several cases when, in the absence of any interleaved tables, the span modification done by the fast path will actually result in errant behaviour. 
___
*[pkg/sql/delete.go, line 364 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3tBGAwdbkTUKmvcB:-LJu7g2a8wYjjFzNtvHY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L364)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This comment is wrong.
</blockquote></details>

Done
___
*[pkg/sql/delete.go, line 366 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3ucZ9PnW35L42CJl:-LJu7gwq3B7zNGughew-:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L366)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This should be defined right before the for statement that uses it.
</blockquote></details>

Done
___
*[pkg/sql/delete.go, line 371 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3bq98f_qP-JsPM8f:-LJu7_e8BIGiQf6Mf-kQ:b3t26yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L371)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This shouldn't be a warning, but a trace statement perhaps?  Or just remove it entirely.
</blockquote></details>

Done - removed
___
*[pkg/sql/delete.go, line 395 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4C4kEsH0h5ujfDhy:-LJu7hPq396FULa-uWPO:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L395)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: extra empty line.
</blockquote></details>

Done
___
*[pkg/sql/delete.go, line 401 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4N2hANO5djSEftkC:-LJu7iBxBuWcK0bZDCKG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L401)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

this comment is in the wrong place and doesn't tell you more than what the code actual does.  
</blockquote></details>

Done
___
*[pkg/sql/delete.go, line 426 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu4YCwA60CIrvzA5tB:-LJu7iuT0vgTQZ9a0y-q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L426)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

extra line
</blockquote></details>

Done
___
*[pkg/sql/delete_test.go, line 150 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJQ4kK99qhEf4wMXmtT:-LJu80pq3KqQ5dPPcGPV:b-yt7cs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/26147dacdfbd7316ce005be72c9c32fa6bf6724c/pkg/sql/delete_test.go#L150)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Then reference that new issue here.  Or remove the testcase entirely, just make sure you have coverage.
</blockquote></details>

Done - removed test case. Sending this issue will be its own task.


<!-- Sent from Reviewable.io -->

2018-08-15 14:53 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

After you squash obviously.  But I'm still curious about why it fails if there are no interleaved tables.  Are you missing a test or check?  

> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-:-LJy3gYwAgn94Ib8PSsY:b-3vz5tu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJy3MNTD905GC4ekW_L:b7lrori) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done - updated comment

To be clear, DelRange is used for the regular fast path as well. The real reason for why we fail the fast path in this case is that there are several cases when, in the absence of any interleaved tables, the span modification done by the fast path will actually result in errant behaviour. 

</blockquote></details>

Can you specify what errant behaviour?  What happens?  What's missing?  What's different?


<!-- Sent from Reviewable.io -->

2018-08-15 14:53 UTC, BramGruneir requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqVUA5ZvKkFPs76lx:-LJy3v0GBTXstZg2sv95:bbtnnah) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L350)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done (unit test work still going) 
</blockquote></details>

This test work is done right?


<!-- Sent from Reviewable.io -->

2018-08-15 16:57 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJJqVUA5ZvKkFPs76lx:-LJyWEivD0A4ZsFghnrW:b2nhswy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f59080c72c4551c17189c92a5ba6bd202842fe0/pkg/sql/delete.go#L350)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This test work is done right?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2018-08-15 17:12 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJyXeMD5MtJ3jomyIqs:b-rv2pk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you specify what errant behaviour?  What happens?  What's missing?  What's different?
</blockquote></details>

There are a couple of cases where taking this fast path when there aren't any interleaved tables will cause the spans to be modified in such a way that an unintended number of rows will be deleted. Maybe some more investigation needs to be done in order to determine why this is the case, but it appears the way that PrefixEnd interacts with the EndKeys of the spans that come about when scanning tables without any other tables interleaved in them.

Here's an example of one such logic test failure that happens if this check is not here:

```
(statement prior to failure)
query II
SELECT * FROM [DELETE FROM a WHERE b IN (6,7) RETURNING a,b] LIMIT 0
----

testdata/logic_test/statement_source:67: SELECT * FROM a ORDER BY b
expected:
    100  2
    -2   3
    7    8
but found (query options: "") :
    100  2
    -2   3
    3    4
    -4   5
    5    6
    -6   7
    7    8
```

Another involving SHOW TRACE:

```
testdata/logic_test/show_trace:298: SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
expected:
    sql txn           Scan /Table/55/{1-2}
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 Scan to (n1,s1):1
    sql txn           DelRange /Table/55/1 - /Table/55/2
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 DelRng, 1 BeginTxn, 1 EndTxn to (n1,s1):1
    sql txn           fast path completed
    sql txn           rows affected: 2

but found (query options: "") :
    sql txn           Scan /Table/55/{1-2}
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 Scan to (n1,s1):1
    sql txn           DelRange /Table/55/1 - /Table/55/3
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 DelRng, 1 BeginTxn, 1 EndTxn to (n1,s1):1
    sql txn           fast path completed
    sql txn           rows affected: 2
```


<!-- Sent from Reviewable.io -->

2018-08-15 17:48 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJygsxZ2p3EbpfzpJJN:b-hgk8yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

There are a couple of cases where taking this fast path when there aren't any interleaved tables will cause the spans to be modified in such a way that an unintended number of rows will be deleted. Maybe some more investigation needs to be done in order to determine why this is the case, but it appears the way that PrefixEnd interacts with the EndKeys of the spans that come about when scanning tables without any other tables interleaved in them.

Here's an example of one such logic test failure that happens if this check is not here:

```
(statement prior to failure)
query II
SELECT * FROM [DELETE FROM a WHERE b IN (6,7) RETURNING a,b] LIMIT 0
----

testdata/logic_test/statement_source:67: SELECT * FROM a ORDER BY b
expected:
    100  2
    -2   3
    7    8
but found (query options: "") :
    100  2
    -2   3
    3    4
    -4   5
    5    6
    -6   7
    7    8
```

Another involving SHOW TRACE:

```
testdata/logic_test/show_trace:298: SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
expected:
    sql txn           Scan /Table/55/{1-2}
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 Scan to (n1,s1):1
    sql txn           DelRange /Table/55/1 - /Table/55/2
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 DelRng, 1 BeginTxn, 1 EndTxn to (n1,s1):1
    sql txn           fast path completed
    sql txn           rows affected: 2

but found (query options: "") :
    sql txn           Scan /Table/55/{1-2}
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 Scan to (n1,s1):1
    sql txn           DelRange /Table/55/1 - /Table/55/3
    dist sender send  querying next range at /Table/55/1
    dist sender send  r1: sending batch 1 DelRng, 1 BeginTxn, 1 EndTxn to (n1,s1):1
    sql txn           fast path completed
    sql txn           rows affected: 2
```
</blockquote></details>

It turns out:

* The first issue here is to do with another bug involving the RETURNING CLAUSE, which has been dealt with
* The second failure here is still a valid concern and is still only avoided by including this interleaved check


<!-- Sent from Reviewable.io -->

2018-08-15 18:05 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/delete.go, line 352 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJu3PiN1KlbJMHpWfKR:-LJykb4I41l0bZ3ph-Zx:bq94wsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a213b4d0060065b7528cb89441120692e34dc266/pkg/sql/delete.go#L352)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

It turns out:

* The first issue here is to do with another bug involving the RETURNING CLAUSE, which has been dealt with
* The second failure here is still a valid concern and is still only avoided by including this interleaved check
</blockquote></details>

Done - It turns out that the SHOW TRACE error didn't really affect the number of rows deleted at all, and that discrepancy in the EndKey is a discrepancy in the Index ID rather than any row's primary key (so it's not deleting any extra rows!)

Updated the comment with the now-correct reasoning


<!-- Sent from Reviewable.io -->

2018-08-15 18:32 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Woo, squash and merge!

> Reviewed 1 of 2 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-:-LJyr3aCA91Bk3Tjujlh:b-rhoicv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/delete.go, line 182 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqzvT0H0TLLXHYziF:-LJyqzvU20UUGaBXNQU8:bx22tqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/delete.go#L182)):*
> ```Go
> 
> 	// fastPathInterleaved indicates whether the delete operation can run
> 	// the interleaved fast path (all interleaved tables have no indexes and ON DELETE CASCADE)
> ```

nit: add a period
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 369 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqdkG3-SONrZTOw2E:-LJyqdkG3-SONrZTOw2F:b-rd5e2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/logictest/testdata/logic_test/interleaved#L369)):*
> ```
> 
> subtest interleaved_join_on_other_columns
> subtest InterleavedDeleteFastPath
> ```

You have a blank subtest here.  Just delete the top one.
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 743 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqj4B43iW2bw3x6J4:-LJyqj4B43iW2bw3x6J5:b99tx6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/logictest/testdata/logic_test/interleaved#L743)):*
> ```
> output row: [9]
> output row: [10]
> rows affected: 10
> ```

Please drop the tables used in the subtest


<!-- Sent from Reviewable.io -->

2018-08-15 18:52 UTC, emsal0 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28330)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/delete.go, line 182 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqzvT0H0TLLXHYziF:-LJyv4bl4E9APLYg4CUV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/delete.go#L182)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: add a period
</blockquote></details>

Done
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 369 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqdkG3-SONrZTOw2E:-LJyv5sK0Hh5WpQFuZNL:bvahtn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/logictest/testdata/logic_test/interleaved#L369)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

You have a blank subtest here.  Just delete the top one.
</blockquote></details>

Done - Turns out there were logic tests here that were removed (whoops) -- re-added them
___
*[pkg/sql/logictest/testdata/logic_test/interleaved, line 743 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/28330#-LJyqj4B43iW2bw3x6J4:-LJyv8O0Dh-3O5QvQw6r:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1961b8d2ee51a4d2f820fe6bc4291ea43c84edd/pkg/sql/logictest/testdata/logic_test/interleaved#L743)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please drop the tables used in the subtest
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-08-15 19:44 UTC, emsal1863 commented
bors r+

2018-08-15 20:13 UTC, merged