storage: make lease rebalancing decisions at the store level
cockroachdb/cockroach pull request #28340
Opened 2018-08-07 17:28 UTC by a-robinson

In order to better balance the QPS being served by each store to avoid
overloaded nodes.

Fixes #21419

Release note (performance improvement): Range leases will be
automatically rebalanced throughout the cluster to even out the amount
of QPS being handled by each node.

2018-08-07 17:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28340)
<!-- Reviewable:end -->

2018-08-07 17:29 UTC, a-robinson commented
Tested primarily via tpc-c on roachprod and the new roachtest. I should give allocsim a look too but am going to start integrating replica-rebalancing decisions as a follow-up.

2018-08-15 16:59 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with some nits.

But I worry about the test being appropriate with KV. 

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LJyW_dX9ru_imb4RqD6:b-7xmy91)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/rebalance_load.go, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyW5Tu-geSNeTZ6K70:-LJyW5Tu-geSNeTZ6K71:b-bbsg10) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3cbe23f293bbbe60e5232041fc372f34de6d9e0/pkg/cmd/roachtest/rebalance_load.go#L16)):*
> ```Go
> // for names of contributors.
> 
> package main
> ```

So this is still checking with kv to make sure the leases are evenly distributed.

But the workload is evenly distributed.

Perhaps KV is not the right load for this and instead use something that stresses some parts more than others.  And instead checks to see if QPS is evenly distributed.  (This might be tough without load based rebalancing)
___
*[pkg/storage/allocator.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyF2TUBhYvit2pm_N8:-LJyF2TUBhYvit2pm_N9:btg1qb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/allocator.go#L1037)):*
> ```Go
> 	// rebalancing is enabled? In happy cases it's nice to keep this working
> 	// to even out the number of leases in addition to the number of replicas,
> 	// but it's certainly a blunt instrument that could undo what we want.
> ```

I think this might be a good idea.  But of course, requires a lot of testing.
___
*[pkg/storage/replicate_queue.go, line 563 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyFOroASioY8nXXHk2:-LJyFOroASioY8nXXHk3:b-szsedz) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/replicate_queue.go#L563)):*
> ```Go
> 			return false, nil
> 		}
> 		if err := rq.transferLease(ctx, repl, target); err != nil {
> ```

I think you can simplify this.
```go
err := rq.transferLease(ctx, repl, target)
return err == nil, err
```

And reverse if case above from  `target != (roachpb.ReplicaDescriptor{})` to `target == (roachpb.ReplicaDesciptor{})` and early exit. to avoid nesting.
___
*[pkg/storage/store_rebalancer.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyU6Q52-j8NwV25uAC:-LJyU6Q52-j8NwV25uAD:bhq7758) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L129)):*
> ```Go
> 
> 	for localDesc.Capacity.QueriesPerSecond > qpsMaxThreshold {
> 		log.Infof(ctx, "considering load-based lease transfers for s%d with %.2f qps (mean=%.2f, upperThreshold=%2.f)",
> ```

Are these debug messages? Need to be venet 3 I think.
___
*[pkg/storage/store_rebalancer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyUQhlE2OVisoudPTJ:-LJyUQhlE2OVisoudPTK:bwn7rrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L152)):*
> ```Go
> 
> // TODO(a-robinson): Should we take the number of leases on each store into
> // account here or just continue to let that happen in allocator.go?
> ```

How much do lease counts matter if we're balancing on qps anyway?
___
*[pkg/storage/store_rebalancer.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyUZgW9c_hIZZHwTJL:-LJyUZgW9c_hIZZHwTJM:b-4wfdhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L187)):*
> ```Go
> 		}
> 
> 		// TODO: Don't bother moving leases whose QPS is below some fraction of the
> ```

nit: format the todo with your name.  If we still rebalance leases based on counts, this is needed.  If we turn that off, then this is fine.


<!-- Sent from Reviewable.io -->

2018-08-15 19:42 UTC, a-robinson reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LJz0uMMEKBb0Ua1ozUz:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyW5Tu-geSNeTZ6K70:-LJyqRXy7rsigmB4Qlz3:b32mul9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3cbe23f293bbbe60e5232041fc372f34de6d9e0/pkg/cmd/roachtest/rebalance_load.go#L16)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So this is still checking with kv to make sure the leases are evenly distributed.

But the workload is evenly distributed.

Perhaps KV is not the right load for this and instead use something that stresses some parts more than others.  And instead checks to see if QPS is evenly distributed.  (This might be tough without load based rebalancing)
</blockquote></details>

Not quite -- this is checking that the 3 leases for the table are evenly distributed, not that all leases are evenly distributed. This was a very simple test that passes with this change and fails most of the time without it because the total number of ranges in a new cluster greatly exceeds the number of ranges (3) in the table used by `kv`. Without load-based rebalancing, the leases for the `kv` table will typically all just stay on the node that had the initial range lease before the `ALTER TABLE ... SPLIT` command, since the other nodes have enough leases for other various ranges that the cluster is still considered balanced.

I agree that you could get slightly different test coverage with a couple other workloads, but in general all the tests I can think of would be testing that a minority of hot ranges get balanced properly, which this one does as well, just in a very simple way.
___
*[pkg/storage/allocator.go, line 1037 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyF2TUBhYvit2pm_N8:-LJys8sb9OeRBGZLFrZi:b-4x61nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/allocator.go#L1037)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think this might be a good idea.  But of course, requires a lot of testing.
</blockquote></details>

Yeah, I don't know that we have the time to fully remove this right now. We'll have to try out a couple antagonistic workloads before sticking with this, though.
___
*[pkg/storage/replicate_queue.go, line 563 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyFOroASioY8nXXHk2:-LJyuaWr1Tisa_9Y2nj3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/replicate_queue.go#L563)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think you can simplify this.
```go
err := rq.transferLease(ctx, repl, target)
return err == nil, err
```

And reverse if case above from  `target != (roachpb.ReplicaDescriptor{})` to `target == (roachpb.ReplicaDesciptor{})` and early exit. to avoid nesting.
</blockquote></details>

Done.
___
*[pkg/storage/store_rebalancer.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyU6Q52-j8NwV25uAC:-LJyvNpvEDFvRRS6cc84:bp9gs0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L129)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Are these debug messages? Need to be venet 3 I think.
</blockquote></details>

Sorry, I meant to have this outside the loop. Fixed.

I do think it'll be nice to actually log this at info level, since it'll only happen a max of once a minute and even then only on heavily loaded clusters with a significant qps imbalance.
___
*[pkg/storage/store_rebalancer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyUQhlE2OVisoudPTJ:-LJyujl458cqj9pBQgLm:bmz6ipa) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L152)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

How much do lease counts matter if we're balancing on qps anyway?
</blockquote></details>

There's still a (small) fixed cost per lease for things like running the replica through all the various queues. It makes the time it takes to drain a node or recover from a node crash more predictable. Also, it may seem silly, but it looks a lot better to new users if the number of leases on each node is roughly even.

It seems desirable to keep lease count roughly even. I'd be happy to hear counterarguments, though, since that would make things simpler. Maybe simplicity is reason enough.
___
*[pkg/storage/store_rebalancer.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyUZgW9c_hIZZHwTJL:-LJyvbY3DVg0ozeR-OZQ:bncsq2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L187)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: format the todo with your name.  If we still rebalance leases based on counts, this is needed.  If we turn that off, then this is fine.
</blockquote></details>

Thanks for calling this out. I create TODOs without a name when I want to make sure they're resolved before merging the code.


<!-- Sent from Reviewable.io -->

2018-08-15 20:06 UTC, BramGruneir submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

This is great, and a big step forward.

> Reviewed 11 of 11 files at r4, 9 of 9 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LJzBBGl-ZP7PMFUq5US:bt2i29l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/rebalance_load.go, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyW5Tu-geSNeTZ6K70:-LJz9gTd3aQAucSbbCos:b-81nlyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3cbe23f293bbbe60e5232041fc372f34de6d9e0/pkg/cmd/roachtest/rebalance_load.go#L16)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Not quite -- this is checking that the 3 leases for the table are evenly distributed, not that all leases are evenly distributed. This was a very simple test that passes with this change and fails most of the time without it because the total number of ranges in a new cluster greatly exceeds the number of ranges (3) in the table used by `kv`. Without load-based rebalancing, the leases for the `kv` table will typically all just stay on the node that had the initial range lease before the `ALTER TABLE ... SPLIT` command, since the other nodes have enough leases for other various ranges that the cluster is still considered balanced.

I agree that you could get slightly different test coverage with a couple other workloads, but in general all the tests I can think of would be testing that a minority of hot ranges get balanced properly, which this one does as well, just in a very simple way.
</blockquote></details>

SGTM!
___
*[pkg/storage/store_rebalancer.go, line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyU6Q52-j8NwV25uAC:-LJzA9ac1b0SRYOjmDiy:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L129)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Sorry, I meant to have this outside the loop. Fixed.

I do think it'll be nice to actually log this at info level, since it'll only happen a max of once a minute and even then only on heavily loaded clusters with a significant qps imbalance.
</blockquote></details>

SGTM
___
*[pkg/storage/store_rebalancer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyUQhlE2OVisoudPTJ:-LJzAK6FB1sqBzN-gy3Z:b-byfe1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/40afa04147db37e6e2205201738667316b89e5d9/pkg/storage/store_rebalancer.go#L152)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

There's still a (small) fixed cost per lease for things like running the replica through all the various queues. It makes the time it takes to drain a node or recover from a node crash more predictable. Also, it may seem silly, but it looks a lot better to new users if the number of leases on each node is roughly even.

It seems desirable to keep lease count roughly even. I'd be happy to hear counterarguments, though, since that would make things simpler. Maybe simplicity is reason enough.
</blockquote></details>

Less movement of leases is better overall.  Which I think is a strong argument on it's own.

Anyway, not blocking for this PR.  But good for a follow up.
___
*[pkg/storage/store_rebalancer.go, line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJzAlCwAPIjDn0ffFCK:-LJzAlCwAPIjDn0ffFCL:b-xmmdv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L198)):*
> ```Go
> 		// just unnecessary churn with no benefit to move leases responsible for,
> 		// for example, 1 qps on a store with 5000 qps.
> 		const minQPSFraction = .001
> ```

Is it worth pulling this const up to highlight it outside of the function?


<!-- Sent from Reviewable.io -->

2018-08-15 21:07 UTC, a-robinson reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_rebalancer.go, line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJzAlCwAPIjDn0ffFCK:-LJzPFDgAUpBpia12xi7:b4387yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L198)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is it worth pulling this const up to highlight it outside of the function?
</blockquote></details>

It'd have to be given a more descriptive name if it was pulled outside, so I'd go with no.


<!-- Sent from Reviewable.io -->

2018-08-15 21:08 UTC, a-robinson commented
cc @nvanbenschoten in case you wanted to take a look at this before submitting. Feel free to pass on doing so, but I wanted to give you a chance if you're interested.

2018-08-17 01:36 UTC, nvb requested changes
Nice work @a-robinson! I'm really excited that we're getting this in for 2.1.

> Reviewed 2 of 3 files at r1, 11 of 11 files at r4, 9 of 9 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LK4WXryEV_aYZcPIpS4:btsqn0q)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[docs/generated/settings/settings.html, line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4RXwO3bUwfxvBloyc:-LK4RXwO3bUwfxvBloyd:b-smc0sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/docs/generated/settings/settings.html#L21)):*
> ```HTML
> <tr><td><code>kv.allocator.load_based_lease_rebalancing.enabled</code></td><td>boolean</td><td><code>true</code></td><td>set to enable rebalancing of range leases based on load and latency</td></tr>
> <tr><td><code>kv.allocator.range_rebalance_threshold</code></td><td>float</td><td><code>0.05</code></td><td>minimum fraction away from the mean a store's range count can be before it is considered overfull or underfull</td></tr>
> <tr><td><code>kv.allocator.stat_based_rebalancing.enabled</code></td><td>boolean</td><td><code>true</code></td><td>set to enable rebalancing of range replicas based on write load and disk usage</td></tr>
> ```

Did this get out of sync with the code?
___
*[pkg/cmd/roachtest/rebalance_load.go, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyW5Tu-geSNeTZ6K70:-LK4WHRk0MuKWI8wmedZ:bnrdvdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3cbe23f293bbbe60e5232041fc372f34de6d9e0/pkg/cmd/roachtest/rebalance_load.go#L16)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

SGTM!
</blockquote></details>

Had the same question as @BramGruneir. That reasoning checks out with me.

Probably worth describing what happens without `kv.allocator.stat_based_rebalancing.enabled=true` somewhere in the test.
___
*[pkg/storage/allocator.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Qchu7DMonMazeiOe:-LK4Qchu7DMonMazeiOf:b8t3co3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/allocator.go#L44)):*
> ```Go
> 	// baseLoadBasedLeaseRebalanceThreshold is the equivalent of
> 	// leaseRebalanceThreshold for load-based lease rebalance decisions (i.e.
> 	// "follow-the-workload"). Its the base threshold for decisions that gets
> ```

decisions that get adjusted
___
*[pkg/storage/allocator.go, line 1011 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4RBWn9klGb1AU9FOV:-LK4RBWn9klGb1AU9FOW:b-ap1uc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/allocator.go#L1011)):*
> ```Go
> // TODO(a-robinson): Should this be changed to avoid even thinking about lease
> // counts now that we try to spread leases and replicas based on QPS? As is it
> // may fight back a little bit against store-level QPS--based rebalancing.
> ```

double "-"
___
*[pkg/storage/replica_rankings.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Ujp8Bcdqq7mCh_fv:-LK4Ujp8Bcdqq7mCh_fw:b-t47cuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L62)):*
> ```Go
> 	rr.mu.Lock()
> 	defer rr.mu.Unlock()
> 	if len(rr.mu.byQPS) == 0 && rr.mu.accumulator.qps.Len() > 0 {
> ```

The interaction between `byQPS` and `rrAccumulator` in this function is subtle. It looked very strange to me until I realized why you gave it these semantics (so that all 128 top replicas are considered and we don't end up staring at the top few every time the StoreRebalancer runs, right?). I'd call that out somewhere. Also call out that because of this behavior we have to be careful about increasing `numTopReplicasToTrack` or we could end up adding large delays between when the hottest few replicas are considered for rebalancing.
___
*[pkg/storage/replica_rankings.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4ON4v2XxLOTlU28kF:-LK4ON4v2XxLOTlU28kG:b-kx8qz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L75)):*
> ```Go
> func (a *rrAccumulator) addReplica(repl replicaWithStats) {
> 	heap.Push(&a.qps, repl)
> 	if a.qps.Len() > numTopReplicasToTrack {
> ```

This is almost always going to be the case during steady-state operations, right? In that case, it seems like there's a natural fast-path that falls out where we compare against the head of the priority queue and only pop and push if the new replica will result in the head being evicted.
___
*[pkg/storage/replica_rankings.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4PQNZAHzEDJoJ0VQG:-LK4PQNZAHzEDJoJ0VQH:bj4qvwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L80)):*
> ```Go
> }
> 
> type rrAccumulator struct {
> ```

I'd add a comment to this as well because it is used externally of the `replicaRankings` abstraction. That will help justify why we have this extra layer of structure instead of having `replicaRankings` hold an `rrPriorityQueue` directly.
___
*[pkg/storage/store_rebalancer.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4S6Lh1B5FVU5QO54y:-LK4S6Lh1B5FVU5QO54z:b-orgfzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L45)):*
> ```Go
> // compares to the load on other stores in the cluster and transferring leases
> // or replicas away if the local store is overloaded.
> type StoreRebalancer struct {
> ```

There's an interesting reason why this can't be a queue itself. Might be worth adding that to this comment.
___
*[pkg/storage/store_rebalancer.go, line 208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4TcnU5ZPAO1SjvTfp:-LK4TcnU5ZPAO1SjvTfq:b7nur6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L208)):*
> ```Go
> 		desc := replWithStats.repl.Desc()
> 		log.VEventf(ctx, 3, "considering lease transfer for r%d with %.2f qps", desc.RangeID, replWithStats.qps)
> 		// TODO(a-robinson): Should we sort these to first examine the stores with lower QPS?
> ```

Sorting or even just randomizing sounds like a good idea to me. Otherwise, won't there be a system-wide tendency to transfer leases to replicas at the front of their range descriptors. The comment on `RangeDescriptor.Replicas` says the order is arbitrary, but I'm not sure that that's true in practice.


<!-- Sent from Reviewable.io -->

2018-08-18 20:22 UTC, a-robinson reviewed
TFTR! I think the only question that may deserve more thought is the naming of the cluster settings. Using the inherited setting names is convenient, but we could do better if we don't mind throwing them out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LKDGKbo9_6TlPgodbdZ:b6cy9v0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[docs/generated/settings/settings.html, line 21 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4RXwO3bUwfxvBloyc:-LKDCrWoCYHu_qdixxIW:b3efq46) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/docs/generated/settings/settings.html#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did this get out of sync with the code?
</blockquote></details>

Good catch, looks like I messed that up. Fixed, although I couldn't figure out how to get the file regenerated automatically.
___
*[pkg/cmd/roachtest/rebalance_load.go, line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LJyW5Tu-geSNeTZ6K70:-LKDGJei-RlJQfDuusmD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3cbe23f293bbbe60e5232041fc372f34de6d9e0/pkg/cmd/roachtest/rebalance_load.go#L16)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Had the same question as @BramGruneir. That reasoning checks out with me.

Probably worth describing what happens without `kv.allocator.stat_based_rebalancing.enabled=true` somewhere in the test.
</blockquote></details>

Done.
___
*[pkg/storage/allocator.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Qchu7DMonMazeiOe:-LKDDDiO6Qr159f-Swxq:b-wgnix7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/allocator.go#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

decisions that get adjusted
</blockquote></details>

Done. After this settles down I'd like to rename all the "load-based lease rebalance" naming to reference follow-the-workload instead.
___
*[pkg/storage/allocator.go, line 1011 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4RBWn9klGb1AU9FOV:-LKDDPBR3sjC9JxNE2_T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/allocator.go#L1011)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

double "-"
</blockquote></details>

Done.
___
*[pkg/storage/replica_rankings.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Ujp8Bcdqq7mCh_fv:-LKDVXkFAlwFhVrvsgUy:b-16bgxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L62)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The interaction between `byQPS` and `rrAccumulator` in this function is subtle. It looked very strange to me until I realized why you gave it these semantics (so that all 128 top replicas are considered and we don't end up staring at the top few every time the StoreRebalancer runs, right?). I'd call that out somewhere. Also call out that because of this behavior we have to be careful about increasing `numTopReplicasToTrack` or we could end up adding large delays between when the hottest few replicas are considered for rebalancing.
</blockquote></details>

That's one reason, although given that the `storeRebalancer` continues until it either runs out of replicas or determines the store is balanced, I don't think it's a very important one.

The issue that was more on my mind was that we could be (and often will be, given that sufficient rebalancing activity triggers a re-gossiping of the store descriptor) loading a new accumulator while the `storeRebalancer` is partway through iterating over all the replicas, causing us to have to re-inspect a bunch of the same replicas again. I guess that's not a huge deal either, though, as long as it doesn't happen repeatedly.

It seems like maybe the consumer of the rankings should just pull out all the rankings at once (similar to how the producer puts all the rankings in at once via the accumulator). 
___
*[pkg/storage/replica_rankings.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4ON4v2XxLOTlU28kF:-LKDRWD7723v3_LYH2Em:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L75)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is almost always going to be the case during steady-state operations, right? In that case, it seems like there's a natural fast-path that falls out where we compare against the head of the priority queue and only pop and push if the new replica will result in the head being evicted.
</blockquote></details>

Good point, done.
___
*[pkg/storage/replica_rankings.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4PQNZAHzEDJoJ0VQG:-LKDUYfOEAhxGpnmF3Rq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd add a comment to this as well because it is used externally of the `replicaRankings` abstraction. That will help justify why we have this extra layer of structure instead of having `replicaRankings` hold an `rrPriorityQueue` directly.
</blockquote></details>

Done.
___
*[pkg/storage/store_rebalancer.go, line 45 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4S6Lh1B5FVU5QO54y:-LKDEBDbA7I6Fp1skIa1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There's an interesting reason why this can't be a queue itself. Might be worth adding that to this comment.
</blockquote></details>

Done.
___
*[pkg/storage/store_rebalancer.go, line 208 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4TcnU5ZPAO1SjvTfp:-LKDbo671OuroVrRwzmj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/store_rebalancer.go#L208)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorting or even just randomizing sounds like a good idea to me. Otherwise, won't there be a system-wide tendency to transfer leases to replicas at the front of their range descriptors. The comment on `RangeDescriptor.Replicas` says the order is arbitrary, but I'm not sure that that's true in practice.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-18 20:47 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> I think the only question that may deserve more thought is the naming of the cluster settings. Using the inherited setting names is convenient, but we could do better if we don't mind throwing them out.

I don't have any strong opinions about this. @BramGruneir do you?

> Reviewed 1 of 9 files at r8, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-:-LKDmI571T323nQNCfS3:bji0k4m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/storage/allocator.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Qchu7DMonMazeiOe:-LKDlIr57RSNxD18st7c:bv3lhyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd5df74f4ad3f317643d5c0ca53f7a351f693c60/pkg/storage/allocator.go#L44)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Done. After this settles down I'd like to rename all the "load-based lease rebalance" naming to reference follow-the-workload instead.
</blockquote></details>

"follow-the-workload" SGTM.
___
*[pkg/storage/replica_rankings.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Ujp8Bcdqq7mCh_fv:-LKDlijS7a13S1kTsOEy:b-64fpga) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L62)):*
> The issue that was more on my mind was that we could be (and often will be, given that sufficient rebalancing activity triggers a re-gossiping of the store descriptor) loading a new accumulator while the storeRebalancer is partway through iterating over all the replicas, causing us to have to re-inspect a bunch of the same replicas again. I guess that's not a huge deal either, though, as long as it doesn't happen repeatedly.

It's relatively cheap to inspect replicas that don't need to be rebalanced though, right?

> It seems like maybe the consumer of the rankings should just pull out all the rankings at once (similar to how the producer puts all the rankings in at once via the accumulator).

That would be easier to understand. This is kind of prescriptive at the moment, so I think it makes sense to push the specialized complexity to the consumer. Feel free to leave a TODO instead of having that slow down the merge.


<!-- Sent from Reviewable.io -->

2018-08-20 18:06 UTC, a-robinson reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_rankings.go, line 62 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28340#-LK4Ujp8Bcdqq7mCh_fv:-LKNVwZd6n4bqYyKGchr:b-uannq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fcd916f5f14453dbbb3bb39e9e7aea71927e077/pkg/storage/replica_rankings.go#L62)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> The issue that was more on my mind was that we could be (and often will be, given that sufficient rebalancing activity triggers a re-gossiping of the store descriptor) loading a new accumulator while the storeRebalancer is partway through iterating over all the replicas, causing us to have to re-inspect a bunch of the same replicas again. I guess that's not a huge deal either, though, as long as it doesn't happen repeatedly.

It's relatively cheap to inspect replicas that don't need to be rebalanced though, right?

> It seems like maybe the consumer of the rankings should just pull out all the rankings at once (similar to how the producer puts all the rankings in at once via the accumulator).

That would be easier to understand. This is kind of prescriptive at the moment, so I think it makes sense to push the specialized complexity to the consumer. Feel free to leave a TODO instead of having that slow down the merge.
</blockquote></details>

Yeah, done.


<!-- Sent from Reviewable.io -->

2018-08-20 18:59 UTC, BramGruneir commented
>> I think the only question that may deserve more thought is the naming of the cluster settings. Using the inherited setting names is convenient, but we could do better if we don't mind throwing them out.

> I don't have any strong opinions about this. @BramGruneir do you?

I have no problem throwing out the old ones.  But we have to be sure that we stop a cluster upgrade if someone is using an old one that not set to the default.  They most likely changed it for a reason.





<!-- Sent from Reviewable.io -->

2018-08-20 19:04 UTC, a-robinson commented
> I have no problem throwing out the old ones. But we have to be sure that we stop a cluster upgrade if someone is using an old one that not set to the default. They most likely changed it for a reason.

Is there any precedent for that? Using the stats-based rebalancing feature has been pretty strongly discouraged. People may be using it in test clusters, but I'd be pretty surprised if it's being used in any real production environments. Also, I want to remove the old stats-based rebalancing code as part of #28852, so the old setting isn't gonna be very useful.

2018-08-20 19:11 UTC, BramGruneir commented
> Is there any precedent for that? Using the stats-based rebalancing feature has been pretty strongly discouraged. People may be using it in test clusters, but I'd be pretty surprised if it's being used in any real production environments. Also, I want to remove the old stats-based rebalancing code as part of #28852, so the old setting isn't gonna be very useful.

How do we know that nobody anyone's using it?  It's there's an option of it and I'd bet people have toyed with it.  I have no idea how we go about deprecating a cluster setting.  
But we should warn people (at least in upgrade notes) that this is the case.





<!-- Sent from Reviewable.io -->

2018-08-20 19:13 UTC, BramGruneir approved these changes
> Reviewed 13 of 13 files at r10, 9 of 9 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28340)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-08-20 19:13 UTC, a-robinson commented
We've removed cluster settings before (https://github.com/cockroachdb/cockroach/blob/master/pkg/settings/registry.go#L36), we've just never done anything like stopping an upgrade due to them. I'd think doing the same as before (retiring the setting and including a release note) is sufficient.

2018-08-20 19:14 UTC, BramGruneir commented
SGTM





<!-- Sent from Reviewable.io -->

2018-08-20 20:05 UTC, a-robinson commented
bors r+

I'll follow up with the setting changes.

2018-08-20 20:20 UTC, merged