cli: new command 'start-single-node'
cockroachdb/cockroach pull request #28495
Opened 2018-08-11 22:51 UTC by knz

Fixes #24118.
Fixes #21429.

Suggested/requested by @bdarnell:

> There are currently two ways to initialize a cluster: Starting the
  first node without a --join flag, or starting all nodes with --join
  flags and running a separate cockroach init command. This redundancy
  is confusing (our docs use both methods without explaining the
  difference) and it's easy to accidentally initialize a new cluster
  by restarting your first node with the wrong flags. (This could have
  catastrophic consequences in 1.1 because data from the two clusters
  could get mixed. We've added safeguards against this in 2.0 but it's
  still an easy way to break things.)
> I think that we should deprecate this implicit initialization mode
  and make the --join flag mandatory when starting a node (and
  therefore the init command would be mandatory too). To avoid adding
  too much complexity to single-node clusters, I propose a new
  `cockroach start-single-node` command to perform the start and init
  combination that is today implicit in the absence of a --join flag.
> This would have a side benefit that we would know when the user
  intends to keep the cluster as a single node instead of adding more
  later. The `start-single-node` command could therefore set the
  replication factor to 1 to disable the "underreplicated ranges"
  warning.

This patch implements the new `start-single-node` command as follows:

- the new command does not accept `--join`.
- it attempts to set the replication factor to 1 upon starting up.

Meanwhile `cockroach start` is changed to produce a deprecation
warning if `--join` is not specified.

Release note (cli change): a new command `cockroach start-single-node`
is introduced to start single-node clusters with replication disabled.

Release note (cli change): using `cockroach start` without `--join` is
now deprecated and this mode of execution will be removed in a later
version of CockroachDB. Consider using `cockroach start-single-node`
instead or combine `cockroach start` with `cockroach init`.

2018-08-11 22:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28495)
<!-- Reviewable:end -->

2018-08-13 15:50 UTC, bdarnell reviewed
I think this is a good idea, but I don't think we should merge it for 2.1 at this point because it's too disruptive to the docs. We use the start-without-join mode in some places (including the "start a local cluster" tutorial) and we'd need to audit all the docs and tutorials to make sure we aren't giving people instructions that will lead to a "don't do it this way" warning as their first impression. 

Product may also want to weigh in since this is a significant change to the initial user experience. 

Should `start-single-node` also default to `--listen-addr=localhost`?

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-:-LJnxmtF6OQIg95cG3yR:bd08her)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/start.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnwpUZ02O0Hjt23OIY:-LJnwpUZ02O0Hjt23OIZ:btjzk2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L77)):*
> ```Go
> storage devices, specified via --store flags.
> 
> Specify the --join flag to point to any other healthy node ( or list
> ```

This needs to be updated to reflect the fact that it is now normal to start nodes (at least the first one, by necessity) with `--join` pointing to a node that hasn't been started yet. 
___
*[pkg/cli/start.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnxNY98vSR0SlD_W5h:-LJnxNY98vSR0SlD_W5i:bq868qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L676)):*
> ```Go
> 			if initialBoot && disableReplication {
> 				cmd := []string{
> 					"zone", "set", "." + config.DefaultZoneName,
> ```

It's more complicated than this - setting the default zone won't automatically cascade into the other system zones that get default zone configs. 


<!-- Sent from Reviewable.io -->

2018-08-13 16:07 UTC, knz commented
I'm good with keeping this open for a few weeks. I appreciate the pressure it would put on docs. However I do recommend we merge it early in the release cycle so we can start working on the UX improvements early on.

2019-07-08 14:57 UTC, knz commented
@bdarnell do you want to revive this?

2019-07-08 18:13 UTC, bdarnell commented
That question should probably go to PM/docs/support to see if we have the docs bandwidth to update everything, and if this would be enough of an improvement to be worth going through the deprecation cycle.

2019-08-01 10:58 UTC, knz reviewed
Rebased, PTAL.

> Should start-single-node also default to --listen-addr=localhost?

I don't know. I don't think so - the windows dev would be starting their single-node cluster in a linux vm and expect it to be reachable from the host.
What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-:-LlBovd5-Rcv-ig6QLZ7:bp91yap)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/cli/start.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnwpUZ02O0Hjt23OIY:-LlBnQj_5MaYSz0N4s7f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L77)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This needs to be updated to reflect the fact that it is now normal to start nodes (at least the first one, by necessity) with `--join` pointing to a node that hasn't been started yet. 
</blockquote></details>

Done.
___
*[pkg/cli/start.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnxNY98vSR0SlD_W5h:-LlBoops7mgI4QLBh2Hs:b-19dguq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L676)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's more complicated than this - setting the default zone won't automatically cascade into the other system zones that get default zone configs. 
</blockquote></details>

I still have to investigate this.


<!-- Sent from Reviewable.io -->

2019-08-01 18:45 UTC, bdarnell requested changes
> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[pkg/cli/start.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnwpUZ02O0Hjt23OIY:-LlDUKNAD8gqFyeV0hET:bx7w46m) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L77)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still isn't saying what I was looking for. We need to say something about how the join nodes don't need to be started yet. Something like:

Specify the --join flag to point to another node or nodes that are part of the same cluster. The other nodes do not need to be started yet, and if the address of the other nodes to be added are not yet known it is legal for the first node to join itself. 
___
*[pkg/cli/start.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlDTu126iQAef1vQxlz:-LlDTu126iQAef1vQxm-:bnum0iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b0fed7cebf84414e8f663e6e389e278e871a38/pkg/cli/start.go#L568)):*
> ```Go
> 
> 		if waitForInit {
> 			initialBoot = true
> ```

This is the multi-node join path, not start-single-node. This seems to disagree with the previous comment about this variable. 
___
*[pkg/cli/start.go, line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlDUAS33hweeQ5Sy9Ra:-LlDUAS33hweeQ5Sy9Rb:b-wsfcbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b0fed7cebf84414e8f663e6e389e278e871a38/pkg/cli/start.go#L705)):*
> ```Go
> 				cmd := []string{
> 					"sql",
> 					"-e", "alter range default configure zone using num_replicas = 1",
> ```

I guess this works, but I'm surprised to see this go through the full command machinery. Is there not some function in sql_util we could use more directly?


<!-- Sent from Reviewable.io -->

2019-08-01 20:51 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/cli/start.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnwpUZ02O0Hjt23OIY:-LlDoU5_4FGl_rEq-8TQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L77)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This still isn't saying what I was looking for. We need to say something about how the join nodes don't need to be started yet. Something like:

Specify the --join flag to point to another node or nodes that are part of the same cluster. The other nodes do not need to be started yet, and if the address of the other nodes to be added are not yet known it is legal for the first node to join itself. 
</blockquote></details>

Done.
___
*[pkg/cli/start.go, line 676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LJnxNY98vSR0SlD_W5h:-LlDtW4V4Fg3IZ1WPOpx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/08688e833cd1becf1f09c815b4e042ad8047710a/pkg/cli/start.go#L676)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I still have to investigate this.
</blockquote></details>

Done.
___
*[pkg/cli/start.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlDTu126iQAef1vQxlz:-LlDtS0sAdPbFBdMtgzK:b-5864v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b0fed7cebf84414e8f663e6e389e278e871a38/pkg/cli/start.go#L568)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is the multi-node join path, not start-single-node. This seems to disagree with the previous comment about this variable. 
</blockquote></details>

This entire approach was incorrect/flawed. I used a simpler/better approach. PTAL.
___
*[pkg/cli/start.go, line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlDUAS33hweeQ5Sy9Ra:-LlDtUuS0Rcp2ZAB3Adv:byr4ffv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b0fed7cebf84414e8f663e6e389e278e871a38/pkg/cli/start.go#L705)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I guess this works, but I'm surprised to see this go through the full command machinery. Is there not some function in sql_util we could use more directly?
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2019-08-01 21:08 UTC, bdarnell approved these changes
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/context.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlE-UFL-GWelxnF6ywf:-LlE-UFL-GWelxnF6ywg:b-dmmkfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0668607834a40ba5137d0bf74d1b09dafba779/pkg/cli/context.go#L111)):*
> ```Go
> 	serverCfg.SocketFile = ""
> 	serverCfg.JoinList = nil
> 	serverCfg.DefaultSystemZoneConfig = config.DefaultZoneConfig()
> ```

Looks like this first line should be removed (or just remove the word `System`?)


<!-- Sent from Reviewable.io -->

2019-08-01 21:24 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28495)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/cli/context.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28495#-LlE-UFL-GWelxnF6ywf:-LlE27abEZcstFvk7xaZ:br4qre0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c0668607834a40ba5137d0bf74d1b09dafba779/pkg/cli/context.go#L111)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Looks like this first line should be removed (or just remove the word `System`?)
</blockquote></details>

typo indeed. fixed.


<!-- Sent from Reviewable.io -->

2019-08-02 02:06 UTC, knz commented
TFYR

bors r+

2019-08-02 02:30 UTC, merged