WIP distsql: refactor plan and run to prepare for recursive evaluation of subqueries
cockroachdb/cockroach pull request #28580
Opened 2018-08-14 16:55 UTC by arjunravinarayan

Please hold off on reviewing until this PR is ready for submission.

2018-08-14 16:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28580)
<!-- Reviewable:end -->

2018-08-16 18:40 UTC, knz submitted a review, later dismissed
Woo excellent :tada: 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> on principle but I'd like a final cursory look after:
- verification that the memory accounting for subquery evaluation is not unbounded (see my comment below) 
- some additional explanatory comments to verify my understanding (also see my comment below)

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK3-Rk7Df2qBoSK2kXZ:by74jti)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_running.go, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3-tyb3kfHE1gX4QT9:-LK3-tycBlL5ZtPRpoSI:b-w8kda0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded8177c5c76edcc0bcc76f403017b4c3358ec1/pkg/sql/distsql_running.go#L473)):*
> ```Go
> 		return r.status
> 	}
> 	// If no columns are needed by the output, they are only looking for whether
> ```

Clarify what the word 'they' refers to in this comment.
___
*[pkg/sql/distsql_running.go, line 568 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30l--Eou7g7s0p_4E:-LK30l--Eou7g7s0p_4F:b-cvrdtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L568)):*
> ```Go
> 
> // PlanAndRunSubqueries returns false if an error was encountered and sets that
> // error in the provided receiver.
> ```

I would appreciate as a reviewer if you could interleave explanatory comments throughout the body of this function.
___
*[pkg/sql/distsql_running.go, line 573 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30qHC18iWrLbWXO5X:-LK30qHC18iWrLbWXO5Y:b-1b17xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L573)):*
> ```Go
> 	subqueryPlans []subquery, recv *DistSQLReceiver, maybeDistribute bool,
> ) bool {
> ```

nit: we usually omit an empty line at the start of the body.
___
*[pkg/sql/distsql_running.go, line 587 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30SCGE07fO9eMIK3C:-LK30SCGE07fO9eMIK3D:bt47ub5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L587)):*
> ```Go
> 			dsp.distSQLSrv.Settings,
> 		)
> 		subqueryMonitor.Start(ctx, evalCtx.Mon, mon.BoundAccount{})
> ```

Curiosity: what is the parent account here?
___
*[pkg/sql/distsql_running.go, line 598 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30ZjJ0d8hhnsNv-Le:-LK30ZjJ0d8hhnsNv-Lf:bvtfx2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L598)):*
> ```Go
> 		var distributeSubquery bool
> 		if maybeDistribute {
> 			// TODO(arjun): plumb the distsql mode in here. We know it's not
> ```

Please file an issue, link it from this TODO, and add a test that shows where this matters (and a TODO next to the test to indicate the test must be changed when the issue is addressed).


<!-- Sent from Reviewable.io -->

2018-08-16 18:41 UTC, knz reviewed
Also as a courtesy to the rest of the team who will see the PR desc in git log and the daily mail, perhaps you could include a before/after benchmark comparison on a simple query with subqueries. So we get an estimate of the overhead.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK31aHuBQZCBwd1TWPt:b1736st)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-16 20:45 UTC, asubiotto submitted a review, later dismissed
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK3Iaq45Bgm2YzpnfEp:bcqwi0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
> ```Go
> 
> 	evalContextFactory := func() *extendedEvalContext {
> 		evalCtx := ex.evalCtx(ctx, planner, planner.ExtendedEvalContext().StmtTimestamp)
> ```

Why do you need to pass in an `evalContextFactory` instead of just one `evalCtx`? A comment here might be good.
___
*[pkg/sql/distsql_running.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3AK_X9oql6U63FOF_:-LK3AK_YBRouHdcZDcij:b-qecrai) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba2c8b9e4ad2cee8c9b5aa1267c879410510587/pkg/sql/distsql_running.go#L546)):*
> ```Go
> // to be closed.
> func (dsp *DistSQLPlanner) PlanAndRun(
> 	ctx context.Context, evalCtx *extendedEvalContext, planCtx *PlanningCtx, txn *client.Txn,
> ```

nit: function signatures should have one argument per line if the arg list is too long
___
*[pkg/sql/distsql_running.go, line 400 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Fu3M19_yRRP5E6PF:-LK3Fu3M19_yRRP5E6PG:b-xt03yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L400)):*
> ```Go
> }
> 
> func (receiver *DistSQLReceiver) cloneDistSQLReceiver() *DistSQLReceiver {
> ```

I would name this method just `clone`. Also it might be worth calling out that cloning a distsql receiver doesn't clone all fields (and maybe point out why not). What I mean by this is that for example `status` is not copied over so that you don't start with a receiver in the `ConsumerClosed` state.
___
*[pkg/sql/distsql_running.go, line 408 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Fma74cQXHpdaafQb:-LK3Fma74cQXHpdaafQc:be1r1vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L408)):*
> ```Go
> 		txn:         receiver.txn,
> 		updateClock: receiver.updateClock,
> 		stmtType:    tree.Rows,
> ```

Shouldn't this also be `receiver.stmtType`?
___
*[pkg/sql/distsql_running.go, line 571 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3IDOT78u_WDw2_x6l:-LK3IDOT78u_WDw2_x6m:bb8ugzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L571)):*
> ```Go
> func (dsp *DistSQLPlanner) PlanAndRunSubqueries(
> 	ctx context.Context, planner *planner, evalContextFactory func() *extendedEvalContext,
> 	subqueryPlans []subquery, recv *DistSQLReceiver, maybeDistribute bool,
> ```

nit: should be one arg per line

re: `maybeDistribute`, maybe you can just call it `distribute`? The semantics of the previous `distribute` bool are not necessarily that it will be distributed.
___
*[pkg/sql/distsql_running.go, line 594 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3LRo9B6UHR-tgtdeF:-LK3LRoA1dHaVEV1iP37:b454isr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L594)):*
> ```Go
> 	}
> 
> 	for i, subqueryPlan := range subqueryPlans {
> ```

Haven't thought hard about this but any possibility we could run these concurrently?
___
*[pkg/sql/distsql_running.go, line 604 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3LoR632gYkKMzPhuH:-LK3LoR632gYkKMzPhuI:b-uc2lv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L604)):*
> ```Go
> 				ctx, sessiondata.DistSQLAuto, dsp, subqueryPlan.plan)
> 		}
> 		if distributeSubquery {
> ```

This might also benefit from extracting the `planningCtx` creation functionality.

Do you need to create a new `planningCtx` for each subquery?
___
*[pkg/sql/distsql_running.go, line 623 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3NS1f0Mrj4WT5oGk3:-LK3NS1f0Mrj4WT5oGk4:bfz54gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L623)):*
> ```Go
> 
> 		subqueryRecv := recv.cloneDistSQLReceiver()
> 		var rows *sqlbase.RowContainer
> ```

This might be an extension but a receiver gets `EncDatum`s pushed to it. It might be worth it to add the ability to use a `diskBackedRowContainer` for any overflow to the receiver or at least apply some backpressure (like https://github.com/cockroachdb/cockroach/pull/24709/files#diff-19f0fc44125ba5c821702b74b18364beR57).
___
*[pkg/sql/distsql_running.go, line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3R8Jn56ilyi_91yRt:-LK3R8Jn56ilyi_91yRu:b8vkq5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L642)):*
> ```Go
> 		case distsqlrun.SubqueryExecModeAllRows, distsqlrun.SubqueryExecModeAllRowsNormalized:
> 			var result tree.DTuple
> 			for i := 0; i < rows.Len(); i++ {
> ```

Could also do `for rows.Len() > 0 { rows.At(0); rows.PopFirst()` to discard rows as you go although I guess they won't be accounted for anymore in that case...  Hmm but the `Close` after evaluating will do that anyway... Which might be an issue because all the results will be unaccounted for.
___
*[pkg/sql/distsql_running.go, line 683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3HB78-OCb9FyYhvdd:-LK3HB78-OCb9FyYhvde:b-5d691m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L683)):*
> ```Go
> 			}
> 		default:
> 			rows.Close(evalCtx.Ctx())
> ```

Hmm, I don't like the fact that these `rows.Close` calls are peppered around although I'm not sure I would like each iteration of the loop to be wrapped in a function with a `defer rows.Close` where you create it (but it might be better), what do you think?
___
*[pkg/sql/testutils.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Acu84w1ekfTUpoHk:-LK3Acu91mA5cIdq010H:b-3l0u5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba2c8b9e4ad2cee8c9b5aa1267c879410510587/pkg/sql/testutils.go#L124)):*
> ```Go
> 	)
> 
> 	evalCtx := p.ExtendedEvalContext()
> ```

Might be a good idea to extract this common planCtx creation into a method of `DistSQLPlanner` (i.e. `NewPlanningCtx` could be this higher level `planCtx` creation). Also does this need the `validExtendedEvalCtx` set?


<!-- Sent from Reviewable.io -->

2018-08-16 21:02 UTC, rjnn reviewed
Thank you for the wonderful reviews! I have addressed a partial set of comments, and will do the rest tomorrow, and update the PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK3XViACcCEy4jZpyiS:b5e4e38)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK3VR8T2qNPLGeBGjja:b-8kq9gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do you need to pass in an `evalContextFactory` instead of just one `evalCtx`? A comment here might be good.
</blockquote></details>

We need a separate `evalCtx` for each subquery. Comment added.
___
*[pkg/sql/distsql_running.go, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3-tyb3kfHE1gX4QT9:-LK3RgIu3x-gjeGfUYmT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ded8177c5c76edcc0bcc76f403017b4c3358ec1/pkg/sql/distsql_running.go#L473)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Clarify what the word 'they' refers to in this comment.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 400 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Fu3M19_yRRP5E6PF:-LK3VuNZCcvao2qPj9H_:bs6b0h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L400)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would name this method just `clone`. Also it might be worth calling out that cloning a distsql receiver doesn't clone all fields (and maybe point out why not). What I mean by this is that for example `status` is not copied over so that you don't start with a receiver in the `ConsumerClosed` state.
</blockquote></details>

Done, although do push back if it is not done to your satisfaction.
___
*[pkg/sql/distsql_running.go, line 408 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Fma74cQXHpdaafQb:-LK3VzFO3P7h1o_bdFBY:bh347oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L408)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't this also be `receiver.stmtType`?
</blockquote></details>

No, the result of a subquery is always `tree.Rows`.
___
*[pkg/sql/distsql_running.go, line 568 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30l--Eou7g7s0p_4E:-LK3W2mX2JFY45oSSjVE:b-hcxqcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L568)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would appreciate as a reviewer if you could interleave explanatory comments throughout the body of this function.
</blockquote></details>

Added some.
___
*[pkg/sql/distsql_running.go, line 571 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3IDOT78u_WDw2_x6l:-LK3Usvb0i3ep87XcbLv:b-itupdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L571)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: should be one arg per line

re: `maybeDistribute`, maybe you can just call it `distribute`? The semantics of the previous `distribute` bool are not necessarily that it will be distributed.
</blockquote></details>

Fixed linter issue.
I called it maybeDistribute because we then compute a new `distribute` variable based off of this. But I can change it if you insist.
___
*[pkg/sql/distsql_running.go, line 587 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30SCGE07fO9eMIK3C:-LK3WHIpCCmLHXnk-Aah:bjnijvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L587)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Curiosity: what is the parent account here?
</blockquote></details>

The parent monitor is the one that comes from the `evalCtx`. cc @asubiotto is this ok?
___
*[pkg/sql/distsql_running.go, line 594 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3LRo9B6UHR-tgtdeF:-LK3V-_VBAegzJVRaWeh:b5am7c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L594)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Haven't thought hard about this but any possibility we could run these concurrently?
</blockquote></details>

Possibly. But not in this PR. I think this will be rendered moot once #28264 is addressed.
___
*[pkg/sql/distsql_running.go, line 604 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3LoR632gYkKMzPhuH:-LK3WW2n5wwLKWCOBuQO:b-x4klfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L604)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This might also benefit from extracting the `planningCtx` creation functionality.

Do you need to create a new `planningCtx` for each subquery?
</blockquote></details>

I do not fully understand things to give you a concrete response, and will investigate and update you. Thank you for these astute questions.
___
*[pkg/sql/distsql_running.go, line 623 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3NS1f0Mrj4WT5oGk3:-LK3X-UC76RIc6crnmx9:b-ehaju6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L623)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This might be an extension but a receiver gets `EncDatum`s pushed to it. It might be worth it to add the ability to use a `diskBackedRowContainer` for any overflow to the receiver or at least apply some backpressure (like https://github.com/cockroachdb/cockroach/pull/24709/files#diff-19f0fc44125ba5c821702b74b18364beR57).
</blockquote></details>

I think this will be rendered moot once #28264 is addressed, so we should not do that here, although it is a good thought.
___
*[pkg/sql/distsql_running.go, line 642 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3R8Jn56ilyi_91yRt:-LK3XAQsBJFgWRHLj2Ja:bn1rl0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L642)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could also do `for rows.Len() > 0 { rows.At(0); rows.PopFirst()` to discard rows as you go although I guess they won't be accounted for anymore in that case...  Hmm but the `Close` after evaluating will do that anyway... Which might be an issue because all the results will be unaccounted for.
</blockquote></details>

But we want to throw away the rows when we're done with them. Are you saying I'm not doing that properly?
___
*[pkg/sql/distsql_running.go, line 683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3HB78-OCb9FyYhvdd:-LK3XEKx0w-9BRumr-yW:bsreq2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L683)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, I don't like the fact that these `rows.Close` calls are peppered around although I'm not su [...]

2018-08-17 14:47 UTC, jordanlewis requested changes
Great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK7IVlMA8kVJAJy1J7I:b-9dwnzc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsql_running.go, line 495 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7IZX-Br69K-p5BSRF:-LK7IZX-Br69K-p5BSRG:b6da5ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L495)):*
> ```Go
> 	// planNodeToRowSource is not set up to handle decoding the row.
> 	if r.noColsRequired {
> 		datum := tree.DBool(row != nil)
> ```

Can you just return an empty r.row here? I'm not sure if anyone consumes that datum? Maybe they do and I just missed it though.
___
*[pkg/sql/distsql_running.go, line 603 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7IzIP6DagrJKWC8Me:-LK7IzIQAjzXTSctBhQO:blwlvso) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L603)):*
> ```Go
> 			// DistSQLOff (otherwise maybeDistribute would be false) but it might be
> 			// Auto or Always and we need to propagate that setting.
> 			distributeSubquery = shouldDistributePlan(
> ```

This is already plumbed in! Just pass in `planner.SessionData().DistSQLMode`.
___
*[pkg/sql/distsql_running.go, line 639 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7JQ1J3t2THbHQYdcg:-LK7JQ1J3t2THbHQYdch:bc4orc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L639)):*
> ```Go
> 		subqueryRecv.resultWriter = subqueryRowReceiver
> 		subqueryPlans[planIdx].started = true
> 		dsp.Run(&subqueryPlanCtx, planner.txn, &subqueryPhysPlan, subqueryRecv, evalCtx)
> ```

I think you need to check `subqueryRecv.Error()` and `subqueryRecv.commErr` here and bail out early if either are non-nil. Otherwise, I think errors will be swallowed, especially in the OneRow mode where you set the error if there are 0 rows - in the error case, there will also be 0 rows, and then we'll overwrite the error with a fresh error.

Furthermore, I think you actually need to propagate the `subqueryRecv.Error()` directly to the outer DistSQL receiver, `recv`. I think actually just doing `recv.SetError(subqueryRecv.Error())` here will suffice.

You should add a test for this. Write a query with a subquery that forces an error - you can use something like `crdb_internal.force_error('code', 'message')` - and make sure that the error is propagated all the way up to the pgwire client.
___
*[pkg/sql/distsql_running.go, line 644 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7Cgdu-Ul785wHc-6l:-LK7Cgdu-Ul785wHc-6m:bxb1mzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L644)):*
> ```Go
> 		case distsqlrun.SubqueryExecModeExists:
> 			// For EXISTS expressions, all we want to know if there is at least one row.
> 			hasRows := rows.Len() != 0
> ```

If we're just checking if there's a row at all, do you still have to do the shenanigans with creating a row with a single bool in it in the distsql receiver?


<!-- Sent from Reviewable.io -->

2018-08-17 18:33 UTC, rjnn reviewed
I believe all comments are addressed. @jordanlewis PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK88OWY8C2Oa5FMT9U6:b-qjc2ll)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK87VD76TvVl9ct3Tr-:bafvy9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

We need a separate `evalCtx` for each subquery. Comment added.
</blockquote></details>

We do not. I was wrong. Good call. cc @jordanlewis now that we're reusing the same `evalCtx` for all the subqueries.
___
*[pkg/sql/distsql_running.go, line 598 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK30ZjJ0d8hhnsNv-Le:-LK85VlA2NHU4oLn1S3M:b-lipag4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L598)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please file an issue, link it from this TODO, and add a test that shows where this matters (and a TODO next to the test to indicate the test must be changed when the issue is addressed).
</blockquote></details>

This is rendered moot by Jordan's suggestion.
___
*[pkg/sql/distsql_running.go, line 604 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3LoR632gYkKMzPhuH:-LK86rtpDxymkEqFvjUM:bkfu3ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/distsql_running.go#L604)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I do not fully understand things to give you a concrete response, and will investigate and update you. Thank you for these astute questions.
</blockquote></details>

We do need to create a new planningCtx for each subquery, because the context is dependent on whether the subquery can be distributed, which is a per-subquery decision.
___
*[pkg/sql/distsql_running.go, line 495 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7IZX-Br69K-p5BSRF:-LK83YUM8uUehFI6htcO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L495)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you just return an empty r.row here? I'm not sure if anyone consumes that datum? Maybe they do and I just missed it though.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 603 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7IzIP6DagrJKWC8Me:-LK7z3Fm-0Zln5mUY3no:b-ioxi27) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L603)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is already plumbed in! Just pass in `planner.SessionData().DistSQLMode`.
</blockquote></details>

Done. Thank you!
___
*[pkg/sql/distsql_running.go, line 639 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7JQ1J3t2THbHQYdcg:-LK85OymCEYxYsitrFOl:b-ds5079) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L639)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think you need to check `subqueryRecv.Error()` and `subqueryRecv.commErr` here and bail out early if either are non-nil. Otherwise, I think errors will be swallowed, especially in the OneRow mode where you set the error if there are 0 rows - in the error case, there will also be 0 rows, and then we'll overwrite the error with a fresh error.

Furthermore, I think you actually need to propagate the `subqueryRecv.Error()` directly to the outer DistSQL receiver, `recv`. I think actually just doing `recv.SetError(subqueryRecv.Error())` here will suffice.

You should add a test for this. Write a query with a subquery that forces an error - you can use something like `crdb_internal.force_error('code', 'message')` - and make sure that the error is propagated all the way up to the pgwire client.
</blockquote></details>

Done. Nice test idea. Added.
___
*[pkg/sql/distsql_running.go, line 644 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK7Cgdu-Ul785wHc-6l:-LK83_FV-RyxmxBNHRfX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5fd8fa2b7100dcc3d14fc477018108c83644a7/pkg/sql/distsql_running.go#L644)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If we're just checking if there's a row at all, do you still have to do the shenanigans with creating a row with a single bool in it in the distsql receiver?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-17 18:49 UTC, jordanlewis approved these changes
> Reviewed 2 of 2 files at r2, 4 of 5 files at r3, 1 of 4 files at r6, 1 of 3 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK8CgZ70uJsvmsKJX_w:b483jel) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

We do not. I was wrong. Good call. cc @jordanlewis now that we're reusing the same `evalCtx` for all the subqueries.
</blockquote></details>

I'm suspicious of this.... didn't we need to copy the evalCtx because otherwise the memory monitor is weirdly shared and closed at inappropriate times? Isn't this what fixed the problem with the second subquery crashing due to memory account issues?


<!-- Sent from Reviewable.io -->

2018-08-17 19:56 UTC, rjnn reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK8SODtCdq6E8HWk1gG:bp3pzq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm suspicious of this.... didn't we need to copy the evalCtx because otherwise the memory monitor is weirdly shared and closed at inappropriate times? Isn't this what fixed the problem with the second subquery crashing due to memory account issues?
</blockquote></details>

The memory monitor has always been shared. We were sharing the planning context which we shouldn't do.
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 509 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK8RwPME7eJb3JL1iRZ:-LK8RwPME7eJb3JL1iR_:b-4n5qdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6c77e4569f8fce048b55f30d51029d87ef1a8ca/pkg/sql/logictest/testdata/logic_test/subquery#L509)):*
> ```
> 
> statement ok
> EXECUTE c('running')
> ```

@knz, any thoughts as to why this is failing? I extracted this exact test from `TestCancelSchemaChange`. As you can see in the above ones, the simpler prepared statements with placeholders in subqueries execute fine. What placeholder data am I improperly propagating for this query to fail with an expression evaluation infinite loop and stack overflow? Once we identify the exact failure, I'll groom this test into a minimal version that doesn't involve job cancellation.


<!-- Sent from Reviewable.io -->

2018-08-17 20:11 UTC, arjunravinarayan commented
___
*[pkg/sql/logictest/testdata/logic_test/subquery, line 509 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK8RwPME7eJb3JL1iRZ:-LK8VgSrCwwyztK7u1nJ:b70s8kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6c77e4569f8fce048b55f30d51029d87ef1a8ca/pkg/sql/logictest/testdata/logic_test/subquery#L509)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

@knz, any thoughts as to why this is failing? I extracted this exact test from `TestCancelSchemaChange`. As you can see in the above ones, the simpler prepared statements with placeholders in subqueries execute fine. What placeholder data am I improperly propagating for this query to fail with an expression evaluation infinite loop and stack overflow? Once we identify the exact failure, I'll groom this test into a minimal version that doesn't involve job cancellation.
</blockquote></details>

I was wrong; all the prepared statements fail in `experimental_opt=off' mode, which means the problem is a lot more straightforward. Placeholders are not being propagated into subqueries, and that needs fixing.


<!-- Sent from Reviewable.io -->

2018-08-17 20:16 UTC, arjunravinarayan commented
___
*[pkg/sql/conn_executor_exec.go, line 964 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK3Iaq45Bgm2YzpnfEo:-LK8WpGG4uurYsequBAv:bo8vk1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5031ad14e42e221d6c3bf7dc54857f84b8734acb/pkg/sql/conn_executor_exec.go#L964)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

The memory monitor has always been shared. We were sharing the planning context which we shouldn't do.
</blockquote></details>

Your suspicion was correct. We shouldn't be sharing anything. This was being masked by `validExtendedEvalContext` not being set correctly. Smoothed everything out, and returned to the factory.


<!-- Sent from Reviewable.io -->

2018-08-17 20:30 UTC, rjnn reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_executor_exec.go, line 966 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-LK8_5pI8X06UAgP5bJy:-LK8_5pI8X06UAgP5bJz:by3rh2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23767fbd9936ba96743bdec27928b542427d2192/pkg/sql/conn_executor_exec.go#L966)):*
> ```Go
> 		evalCtxFactory := func() *extendedEvalContext {
> 			evalCtx := ex.evalCtx(ctx, planner, planner.ExtendedEvalContext().StmtTimestamp)
> 			evalCtx.Placeholders = &planner.semaCtx.Placeholders
> ```

This propagation of the placeholders map to the subqueries fixes the new logic tests w.r.t. placeholders.


<!-- Sent from Reviewable.io -->

2018-08-17 21:13 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r5, 2 of 2 files at r11, 5 of 5 files at r12, 1 of 4 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LK8iyWbBV3GszzqYgkg:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->

2018-08-18 00:30 UTC, arjunravinarayan commented
bors r-

on second thoughts, I'll let this lie for another day or two if you want some time to look at it @knz.

2018-08-18 08:59 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> please go ahead

> Reviewed 2 of 2 files at r11, 5 of 5 files at r12, 1 of 4 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28580#-:-LKBFbNA6EOUIUlCW0bj:b-r4kply)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-18 10:34 UTC, arjunravinarayan commented
Bors r=jordanlewis,knz

TFTRs everyone!

2018-08-19 23:03 UTC, arjunravinarayan commented
The execution panic is coming from an intentional `crdb_internal.force_log_fatal`, and the surrounding test is about testing if a server encountering a fatal error that does not have `logtostderr` enabled does correctly panic it to the CLI...

I am not familiar enough with the docker tests to say anything with confidence, but this test does not appear to be flaky. It appears you are the expert on TestDockerCLI, so if you think this is a legit execution panic, that must be so. I am unable to reproduce this locally. I've rebased to ensure it's not merge skew of some sort, and it's passing on TeamCity... Are you able to decipher anything additional from the failing log output?

2018-08-20 08:04 UTC, knz commented
Ok I'll have a look at this again today. Sorry for that. Can you rebase once more?

2018-08-20 09:34 UTC, arjunravinarayan commented
Rebased, thanks.

2018-08-20 11:58 UTC, knz commented
The rebase was borked, the result doesn't build.

2018-08-20 12:29 UTC, arjunravinarayan commented
bors r=knz,jordanlewis

(OKed by @knz offline)

2018-08-20 12:30 UTC, knz commented
yep :+1:  thanks!

2018-08-20 12:44 UTC, merged

2018-08-20 12:54 UTC, jordanlewis commented
🎉