rfcs: introduce node liveness epoch into table descriptor leases
cockroachdb/cockroach pull request #28628
Opened 2018-08-15 16:33 UTC by vivekmenezes

Release note: None

2018-08-15 16:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28628)
<!-- Reviewable:end -->

2018-08-15 17:59 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJycO93B_Cgf8jCcqMe:-LJycO93B_Cgf8jCcqMf:bu6qabz) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L150)):*
> ```Markdown
> acquired and released.
> 
> All nodes will assume a fixed `lease_duration` in minutes (we'll
> ```

This is a step backwards from today. `lease_duration` is not fixed; it's a cluster setting. We perform the lease_duration addition once when the lease is granted and then store it in the lease record so that every node agrees on when each lease expires. This proposal doesn't handle changes to the lease duration gracefully since each node calculates it independently. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJyeTiODNNaeuCaIeKw:-LJyeMxmCUr3R9an-aJ7:bpdy2d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L177)):*
> ```Markdown
> 
> * `liveness := nodeLiveness.Self()`
> * `if L >= liveness.Expiration + lease_duration then return error`
> ```

This is inside the lease-acquisition transaction, not the transaction using the lease. 

This doc doesn't discuss the transaction using the lease at all. Currently, we use the lease by setting the txn deadline to the minimum of the expirations of all table leases used. Now that becomes meaningless as all leases have infinite expirations. What takes its place? 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJygjMGBa_LEmlj1nVq:-LJygjMGBa_LEmlj1nVr:b9xfhzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L207)):*
> ```Markdown
> `{Epoch: E, Expiration: Q}`, it is allowed to delete all leases
> for node `N` with `epoch < E` using a transaction with timestamp
> `T`, where `T > Q + lease_duration`.
> ```

History is not kept for liveness records. Q will be within 10 seconds of Now for any live nodes. That puts `Q + lease_duration` in the future, and you can't run a transaction in the future. There will need to be some additional state and logic here to remember which epoch/expiration pairs we've seen long enough to delete them. 

If a node dies at epoch E-1, the liveness record for epoch E is not written until some other node tries to increment its liveness and take one of its (range) leases. If we see an epoch that expired in the past, this lease-cleanup process will also need to be responsible for incrementing the epoch in some cases. 


<!-- Sent from Reviewable.io -->

2018-08-15 19:42 UTC, vivekmenezes reviewed
I appreciate you reviewing this.

There is one minor risk:

A node has a lease on an table at version V, the version changes to V+1 but the node doesn't hear via gossip
that it has descriptor version has changed. It will not upgrade its leases thereby blocking a schema change
until the node is restarted.

I could always add a slow polling mechanism that reads the entire system config every once in a while
and check that the node is holding latest version leases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-:-LJz3cAAE26oO7OGHmCS:bg9da45)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJycO93B_Cgf8jCcqMe:-LJywlXu5Btwb-cy6RtD:b-9bn5bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L150)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is a step backwards from today. `lease_duration` is not fixed; it's a cluster setting. We perform the lease_duration addition once when the lease is granted and then store it in the lease record so that every node agrees on when each lease expires. This proposal doesn't handle changes to the lease duration gracefully since each node calculates it independently. 
</blockquote></details>

I've just added a section on configuring lease_duration.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJyeTiODNNaeuCaIeKw:-LJz34sC0Ueb0gcFvuZV:b-sa1w5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L177)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is inside the lease-acquisition transaction, not the transaction using the lease. 

This doc doesn't discuss the transaction using the lease at all. Currently, we use the lease by setting the txn deadline to the minimum of the expirations of all table leases used. Now that becomes meaningless as all leases have infinite expirations. What takes its place? 
</blockquote></details>

I've added a section "using leases"
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJygjMGBa_LEmlj1nVq:-LJz3KQfBk-lySax-ZJp:b-vxfghr) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L207)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

History is not kept for liveness records. Q will be within 10 seconds of Now for any live nodes. That puts `Q + lease_duration` in the future, and you can't run a transaction in the future. There will need to be some additional state and logic here to remember which epoch/expiration pairs we've seen long enough to delete them. 

If a node dies at epoch E-1, the liveness record for epoch E is not written until some other node tries to increment its liveness and take one of its (range) leases. If we see an epoch that expired in the past, this lease-cleanup process will also need to be responsible for incrementing the epoch in some cases. 
</blockquote></details>

See the "Note" at the end of this section. 

Won't the node doing the cleanup increment the epoch for the dead node from the storage layer?


<!-- Sent from Reviewable.io -->

2018-08-15 20:56 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJycO93B_Cgf8jCcqMe:-LJzE8_N7lKZG1UtEtd4:b-t1bggs) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L150)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I've just added a section on configuring lease_duration.
</blockquote></details>

That's an unfortunate bit of complexity to force on the user, but OK. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJygjMGBa_LEmlj1nVq:-LJzDSvUE41ob0QIFgxQ:b2xy6tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/efee738764d45db77819cb39e65c5e6120317459/docs/RFCS/20151009_table_descriptor_lease.md#L207)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

See the "Note" at the end of this section. 

Won't the node doing the cleanup increment the epoch for the dead node from the storage layer?
</blockquote></details>

That note is an observation about the passage of time; be more explicit about what it means.

I don't think there's anything at the storage layer that would force an epoch increment for a node which held no leases at the time it went down. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 209 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LJzM73HA1qCMmRn37Fa:-LJzM73HA1qCMmRn37Fb:b39uel2) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c33640ec91b384b7feba5b7f4d92bc48cd1f4e/docs/RFCS/20151009_table_descriptor_lease.md#L209)):*
> ```Markdown
> a fixed timestamp, `D > T` is true. A schema change modifying
> the table has to have a timestamp `SC > D`. therefore
> `SC > T` follows, ensuring the correct use of the lease.
> ```

Timestamp D is used when a node releases its own lease. But when the lease is considered abandoned by another node, that linkage is broken. If a node has its liveness epoch bumped while it is still in fact alive, it could still have a pending transaction using the old lease. The txn deadline is still a necessary piece of the puzzle. 


<!-- Sent from Reviewable.io -->

2018-08-29 15:01 UTC, vivekmenezes commented
I'm closing this in favor of writing a brand new RFC on epoch based leases. I thinking of changing the leasing mechanism to be a single lease on the entire table descriptor table at a timestamp. More in the new RFC. Thanks for your comments.

2018-09-17 15:01 UTC, vivekmenezes commented
@andreimatei @bdarnell I've decided to update the prior rfc because I felt it was nice to discuss the changes in the context of the old implementation. The new design introduces a new system table which will replace the old system table and plans to maintain a single epoch lease for the entire schema. Thanks for reviewing this!

2018-09-17 16:22 UTC, bdarnell requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcH4Mg7eQCvqEbwc4I:-LMcH4Mg7eQCvqEbwc4J:b-8dvau4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L1)):*
> ```Markdown
> - Feature Name: schema_lease
> ```

Please make a new document. The new text references "the old design" at the same time that it (partially) deletes the documentation of that design. A new RFC will preserve the original and allow the new design to be described without being interleaved with the old one. 


<!-- Sent from Reviewable.io -->

2018-09-17 20:51 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcLCDB25G0NV7mNyXl:-LMcLCDB25G0NV7mNyXm:b-1d08th) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L150)):*
> ```Markdown
>   // as a debugging tool.
>   optional uint32 version;
>   // The modification_time will be deprecated.
> ```

Is this a semantic change or are you just removing the redundant storage? This field is currently used in various places so it has its own migration concerns (that are not currently addressed in the backwards compatibility section). I think I'd prefer to just keep this field around. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcL5JtEUHzLWr5ySuU:-LMcL5JtEUHzLWr5ySuV:b-aze8gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L151)):*
> ```Markdown
>   optional uint32 version;
>   // The modification_time will be deprecated.
>   ...
> ```

What about `up_version`, which was introduced since the original RFC and is now commented as being "on the path to deprecation"?
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcMR0g-0ICWyzCCfRT:-LMcMR0h-EbjUfa-v-9M:b-z63nwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L188)):*
> ```Markdown
> 
> A lease is defined for the entire schema:
> 1. The name to id map for the databases and tables.
> ```

How does this work? This mapping is currently controlled by the `system.namespace` table, which doesn't have the versioning scheme of table descriptors and doesn't appear to be discussed in this doc.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 198 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcNIie62BnF8nRnBkR:-LMcNIie62BnF8nRnBkS:bzdf1lo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L198)):*
> ```Markdown
> 
> ```sql
> CREATE TABLE system.schemalease (
> ```

I think we should store `lease_duration` in this table to help with configurability. That would eliminate the tricky two-setting process. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcP3Ir1fbnkUsbjlHa:-LMcP3Ir1fbnkUsbjlHb:b-30gjzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L255)):*
> ```Markdown
> Lease acquisition will perform the following steps in a transaction:
> 
> * `liveness := nodeLiveness.Self()`
> ```

`nodeLiveness.Self()` is not a transactional operation (which is fine, and in fact preferable - we don't want to introduce more reads on the liveness table because they can be disruptive; we should rely on the existing gossip mechanisms). So this is just the following INSERT in a transaction by itself. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcPxVU7ZDdWz5FikyP:-LMcPxVVCNl9V2oetuCo:b9bta8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L258)):*
> ```Markdown
> * `INSERT INTO system.schemalease VALUES (<nodeID>, <liveness.Epoch>) RETURNING id`
> 
> Where a lease is associated with the write timestamp `L` of the lease
> ```

What exactly is L? The MVCC timestamp of the schemalease record? I'd rather add an explicit timestamp column than use the MVCC timestamp.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 280 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcROAI7nVvtw9AdXh9:-LMcROAI7nVvtw9AdXhA:bv5bs41) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L280)):*
> ```Markdown
> A node will release an older lease when it is not in use through:
> 
> * `DELETE FROM system.schemalease WHERE (id, NodeID, Epoch) = (<id>, <nodeID>, <epoch>)`
> ```

Why use all three fields instead of just `id` (which is the primary key)?

On the other hand, why introduce an ID here instead of using the full tuple as the PK like before? 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcSJWBA9DmdSEsLhT5:-LMcSJWBA9DmdSEsLhT6:btaisob) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L299)):*
> ```Markdown
> Since `F` is always marching forward, it is best that a transaction
> set its deadline at the very end just before commit time, so as to
> pick up the greatest possible deadline.
> ```

Note that it is only possible to set the deadline just before commit time if we also check that our liveness epoch is unchanged since the beginning of the transaction. Any loss of liveness will invalidate the schema leases and will probably require all pending transactions to restart (this is rare enough that I wouldn't worry about trying to continue transactions across loss of liveness)
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 326 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMd8KBi6VRh8ehIlwTc:-LMd8KBi6VRh8ehIlwTd:bjhr10v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L326)):*
> ```Markdown
> 
> * Get (descriptor, modificationTimestamp) for id = <descID>
> * Ensure that no leases written before the modificationTimestamp exist 
> ```

How exactly is this done? This step also needs to guarantee that no new leases with older timestamps can be written. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMd99yn53Kdjpm6KRiQ:-LMd99yn53Kdjpm6KRiR:b-i6h3w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L363)):*
> ```Markdown
> long as the `ModificationTime` of the descriptor is less than or
> equal to the transaction's timestamp. If the lease is unable to
> satisfy this the descriptor cache will need to read all versions
> ```

Why does this need to read all versions instead of just doing a read at the transaction's timestamp? 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 374 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMdB__TCOsLxaH7V_YT:-LMdB__TCOsLxaH7V_YU:b-fdc3ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L374)):*
> ```Markdown
> The KV API will be extended to suport a new scan operation:
> 
> `ScanTimestampWindow(startKey, endKey, fromTimestamp, toTimestamp)` which returns all the KV
> ```

This probably makes sense as an option on the existing Scan operation (use the existing timestamp as the "to" timestamp and add a new field for "from") instead of a new command. 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 382 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMdC5b66n9Aj1kX-EfU:-LMdBl1I06urh_s7K6kP:b-qoijj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L382)):*
> ```Markdown
> on the entire schema, it would be inefficie [...]

2018-09-27 17:10 UTC, andreimatei requested changes
I've stopped reading this because I'd like to clarify something fundamental: why does a `lease_duration` exist? What's its point?
The way I imagined the thing, these schema leases would behave the same as epoch-based range leases: they'd expire as soon as the liveness record with the respective epoch expires. No extra duration beyond that.
So, once a node manages a to bump another node b's epoch, all of b leases are donezo. Why do anything else?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-:-LNQzELz-Oyjkj70fo5c:bqnwgmn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcH4Mg7eQCvqEbwc4I:-LNQs18-DoG7cDBvViBX:b-8jowxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Please make a new document. The new text references "the old design" at the same time that it (partially) deletes the documentation of that design. A new RFC will preserve the original and allow the new design to be described without being interleaved with the old one. 
</blockquote></details>

+1. I think a new doc is the way to go.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQtUgI1ASyF1OSgY46:-LNQtUgI1ASyF1OSgY47:b2huoby) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L90)):*
> ```Markdown
> are:
> 
> 1. Scale: Clusters need to scale to cache thousands of descriptors and hundreds
> ```

"to cache... hundres of node"? What does it mean to cache a node? You mean *on* hundreds of nodes?
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQt5Rr2GJTrohDdX_Q:-LNQt5Rr2GJTrohDdX_R:b66ygcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L91)):*
> ```Markdown
> 
> 1. Scale: Clusters need to scale to cache thousands of descriptors and hundreds
> of nodes while using less than 1% of resources on managing leases. (#23510)
> ```

Please put proper links if you reference other documents.
But I don't think we should reference such issues; ideally all the relevant information would be here.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQtRVa0kKLACkgq0PG:-LNQtRVa0kKLACkgq0PH:baeav0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L92)):*
> ```Markdown
> 1. Scale: Clusters need to scale to cache thousands of descriptors and hundreds
> of nodes while using less than 1% of resources on managing leases. (#23510)
> From a product statndpoint, we'd like to demo cockroach as a multi-tenant
> ```

statndpoint
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQtftj371XfZQRq6Dw:-LNQtftj371XfZQRq6Dx:btj4jdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L95)):*
> ```Markdown
> database supporting 100s of `CREATE DATABASE` each holding 100s of
> `CREATE TABLE`.
> 2. Long deadlines: Leasing should aim to reduce the chance of a error/retry due to a
> ```

I'd clarify this; I think the goal should be that there's no such thing as a "deadline exceeded error" absent schema changes and node failures.
I don't think anything needs to be particularly "long" as automatically extended (in a way that also affects transactions that started before an "extension") 
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQsaqI787bJEa3vslC:-LNQsaqI787bJEa3vslD:b-gkdtb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L99)):*
> ```Markdown
> time are more likely to trigger this error/retry. (#18684)
> In particular, we'd like to have a scheme that continuously extends the
> deadline of the lease without renewing the lease.
> ```

what's the "deadline of a lease"? You want "deadline of a txn"?
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 103 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQuWSm7GVyft9H5QGO:-LNQuWSm7GVyft9H5QGP:b-qx10bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L103)):*
> ```Markdown
> original implementation only leased table descriptors and had a rather
> flimsy implementation of a database cache. (#14332)
> 4. Timestamp view of the entire schema: The old leasing mechanism was
> ```

I don't understand this point very well. What kind of combinations of descriptors were possible to be used by a node under the old scheme that become precluded by the new scheme?
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQv1YV4qnMo2YCUzby:-LNQv1YV4qnMo2YCUzbz:b120om7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L119)):*
> ```Markdown
> 
> For the rest of the discussion parts of the schema like databases and
> tables are called schema elements.
> ```

s/schema element/descriptor ?
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQvlIfChRnTg4gogoG:-LNQvlIfChRnTg4gogoH:bbo8ayh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L150)):*
> ```Markdown
>   // as a debugging tool.
>   optional uint32 version;
>   // The modification_time will be deprecated.
> ```

this is comment on a field that doesn't exist? I'm not sure what's going on.
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LMcMR0g-0ICWyzCCfRT:-LNQx6ZQ53ZfrjUMCC-E:b-dzxwyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L188)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How does this work? This mapping is currently controlled by the `system.namespace` table, which doesn't have the versioning scheme of table descriptors and doesn't appear to be discussed in this doc.
</blockquote></details>

I agree that this needs more words. But I would like to get rid of the namespace table, at least for table names if not for database names (if that's what's being proposed).
___
*[docs/RFCS/20151009_table_descriptor_lease.md, line 193 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LNQxRdgDnu-vA2pQ5Dc:-LNQxRdgDnu-vA2pQ5Dd:b-6dpwo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a722470f78bd1630686b01ec9b81e23890c8c929/docs/RFCS/20151009_table_descriptor_lease.md#L193)):*
> ```
> A table or database that is part of this lease must be read at the hlc timestamp of the lease,
> ```

What does this mean?


<!-- Sent from Reviewable.io -->

2019-01-07 03:45 UTC, vivekmenezes commented
I've finally gotten down to reviving this thread. I've pushed a new commit. I'll reply to all the comments soon.

2019-01-07 03:46 UTC, vivekmenezes commented
@dt @lucy-zhang feel free to chime in with comments. Thanks!

2019-01-21 03:36 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, and @vivekmenezes)

___
*[docs/RFCS/20190104_schema_lease.md, line 90 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWi6VXT1oBvD0B5giqD:-LWi6VXT1oBvD0B5giqE:bqazo5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L90)):*
> ```Markdown
> ### Why leases?
> 
> The `ModificationTime` in this discussion is the database hlc timestamp at which
> ```

The previous paragraph said "The ModificationTime on the descriptor can be deprecated and is not discussed here". Looks like this needs to be updated to talk about the MVCC timestamp instead. 
___
*[docs/RFCS/20190104_schema_lease.md, line 120 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWi75Dj048xGQvpxwlR:-LWi75Dj048xGQvpxwlS:bs06emh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L120)):*
> ```Markdown
> to be defined validity window. We call such a validity window
> a temporary validity window for the version, and it is enforced
> while using a cached copy of a schema element.
> ```

Why is it relevant that the schema element is cached?
___
*[docs/RFCS/20190104_schema_lease.md, line 150 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWi8RU3-br8tw2J70ZS:-LWi8RU3-br8tw2J70ZT:b-2iztxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L150)):*
> ```Markdown
>   // at this timestamp, and this timestamp is used to read
>   // the schema for this lease. This is split up into two
>   // columns to allow flexible sql operations with it.
> ```

Elsewhere we store HLC timestamps as DECIMAL; I think it would be better to do the same here. 
___
*[docs/RFCS/20190104_schema_lease.md, line 158 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWi8EpP0vhXAwO4wNUe:-LWi8EpP0vhXAwO4wNUf:bc4plr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L158)):*
> ```Markdown
> ```
> 
> In truth, NodeID and Epoch are the only two fields required here.
> ```

Above, "leases will be tied to a specific database timestamp". If a UUID were used instead of the HLCWallTime and HLCLogical columns, how is that tie maintained?
___
*[docs/RFCS/20190104_schema_lease.md, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWi8igV01ZCFRWWyICZ:-LWi8igV01ZCFRWWyIC_:b-vcoomf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L161)):*
> ```Markdown
> Another field is required only to disambiguate during lease transition time
> when a node can be using two leases: A new lease, and an old lease
> being used by extant transactions. We could have used a UUID
> ```

If uniqueness is the only requirement, I'd strongly prefer to use a UUID (with perhaps a non-HLC TIMESTAMP column for debugging purposes). Including an HLC timestamp when one is not strictly necessary invites incorrect use. 
___
*[docs/RFCS/20190104_schema_lease.md, line 214 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWiBOYb23h20Ndxf2L-:-LWiBOYb23h20Ndxf2L0:b-1xq2fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L214)):*
> ```Markdown
> commit timestamp `T` is within [`ModificationTime`, `expiration`).
> 
> Older versions of a schema element have a fixed expiration timestamp.
> ```

How is the fixed expiration timestamp of an older version of a schema element discovered/queried? 

The current version `v` is tied to a lease. Version `v-2` and older have fixed expirations. `v-1` doesn't yet have a fixed endpoint, and yet it is not read at the lease's timestamp. I think the discussion of the lease timestamp above needs to be updated to discuss that this is an upper bound for schema reads performed under the lease, not an exact value. 
___
*[docs/RFCS/20190104_schema_lease.md, line 224 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWiDFMr4l0VATVYftCS:-LWiDFMr4l0VATVYftCT:bve4vrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L224)):*
> ```Markdown
> pushed beyond `expiration` the transaction sets its deadline to `expiration`.
> Since `expiration` is always marching forward for leased descriptors, it is
> best that a transaction set its deadline at the very end just before commit
> ```

Setting a deadline based on epoch expiration means that the EndTransaction will have a deadline as little as ~5s in the future (and never more than 9s). This is a significant reduction from the typical case today where deadlines are set minutes away. This seems like it might make some scenarios more fragile.

Consider a multi-row (and multi-range) upsert in an implicit transaction. SQL assembles the entire thing as a single write batch, including the EndTransaction and its deadline. DistSender splits it up, sending the Put batches (possibly collecting pushed timestamps if there is concurrent read traffic), then sends the EndTransaction. If this process takes more than 10s and concurrent reads push our timestamp, it will fail and retry. The retry will face the same time limit and potentially fail in a loop. (Previously, even if a transaction got unlucky and hit the schema lease deadline, the retry would be at the start of a new lease and have several minutes to work with). 

Note that even though we baked a `last_known_epoch_expiration` into the transaction, the leasing node has presumably been heartbeating its liveness record so its lease is still good. The failure here is unnecessary if only we can find a way to safely integrate this fact. I think maybe we should add a node id and epoch to the EndTransaction deadline field, to allow the deadline to be extended if a later expiration for this epoch is known. (but see below about lease releases; it may not be safe)
___
*[docs/RFCS/20190104_schema_lease.md, line 229 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWiH3UX-0KFEIfbOpV7:-LWiH1is8b1hfInKT0g-:b-6s88ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L229)):*
> ```Markdown
> the same as origTimestamp.
> 
> The lease should never be released while a transaction is using a
> ```

And what if the lease is broken (we fail to update our liveness and other node increments our epoch and deletes our lease)?
___
*[docs/RFCS/20190104_schema_lease.md, line 236 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28628#-LWiHTUb5dvmyBBisOcY:-LWiHTUb5dvmyBBisOcZ:beqlfqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a9567c828c26335e8afddd2274de0072abd170e/docs/RFCS/20190104_schema_lease.md#L236)):*
> ```Markdown
> using a transaction with timestamp `D`. A transaction at
> timestamp `T` that used the lease and saw a table at version `v` is
> guaranteed to have `T < D`. We will later discuss how a schema change
> ```

I don't think that's guaranteed unless you require that lease releases wait until after the deadlines set on all transactions that used the lease have expired. 

1. The node acquires a lease at time T1
1. Liveness heartbeats sets epoch expiration to T4
1. A transaction begins at T2. 
1. The transaction attempts to commit with a deadline of T4
1. The transaction is pushed to T4 by a fast clock on another node, but successfully commits
1. Due to an RPC error, the node that started the transaction never sees the response and reports an ambiguous failure to the client (even though the transaction really succeeded). [...]

2020-03-31 18:52 UTC, ajwerner commented
Closing this as rejected. That being said, ideas here will make there way into new leasing constructs. 

This proposal encouraged the expanded use of node liveness as a leasing mechanism. We'd like to move away from that. Perhaps eventually we'll create a node-level session concept to reduce the cost of heartbeating individual leases but the tight coupling to node liveness now seems problematic

2020-03-31 18:52 UTC, closed without merging