sql: fix (really: add) the handling of bit arrays
cockroachdb/cockroach pull request #28807
Opened 2018-08-19 03:18 UTC by knz

Fixes #20991.
Informs #26128.

As described in #28814 there was a mismatch between the original
implementation of BIT in CockroachDB, which was inspired by MySQL, and
that required by the PostgreSQL dialect. That prior PR #28814 thus
disabled the functionality pending a replacement.

This patch provides this replacement.

PostgreSQL bit arrays are arbitrary long strings of bits, possibly
longer (or shorter) than 64 bits, with odd number of bits. They also
support concatenation, which integers do not. They are also different
from strings, because they support bitwise logic operators, which
strings do not. Their literal values are also different from both
integer and string values, noted with `B'....'` (note the capital B;
and see discussion below).

This patch provides the correct handling of bit arrays in
CockroachDB. It does this as follows:

- a new literal syntax `B'....'` for bit array literals.
- a new coltype TBitArray.
- a new datum type DBitArray.
- new operator overloads specialized for bit arrays.
- a new ColumnType BIT (see discussion below).
- a new KV encoding type BitArray. Complete with separate
  value and key encodings.

The new bit array type is conditional on a cluster version, so that
lower version nodes in a cluster do not get confused by the new key
encoding.

Regarding the new ColumnType BIT: this now becomes a first class
SemanticType instead of a VisibleType on INT. As discussed in #28814
any column previously created with an INT semantic type and BIT in the
VisibleType is untouched.

With regards to sorting, bit arrays sort lexicographically from the
leftmost bit. In memory the bits are stored in words of 64 bits, with
the leftmost bit in the MSB of the word, so as to enable efficient
comparisons.

To ensure the ordering is preserved in the key encoding we encode as
follows:

- each word in turn using varint encoding, then
- a word list terminator, which is guaranteed to not occur in the
  words before that, then
- a varint that indicates the number of used bits in the last word.

To decode, we must first scan through the word list until we find the
terminator, to determine the number of words; then we scan again to
decode the words in memory, then we use the last varint together with
the number of decoded words to compute the final bit array size.

Release note (bug fix): CockroachDB now supports the BIT and VARBIT (BIT
VARYING) data types like PostgreSQL: this is a bit array. See the
PostgreSQL documentation for details. Only the bit array literal
notation with a capital B (e.g. `B'10001'`) is currently supported;
the syntax with a small b (e.g. `b'abcd'`) continues to denote *byte*
arrays as in previous versions of CockroachDB.

Release note (backward-incompatible change): CockroachDB happened to
support the notation `B'abcde'` previously to express byte array
literals, although this was not documented. This is not supported any
more; the notation `B'100011'` will now express *bit* array literals
like in PostgreSQL. The notation `b'...'` remains for byte array
literals.

b273321

2018-08-19 16:17 UTC, justinj commented
Haven't read the change but I vaguely remember @andreimatei having an objection to this a while back?

2018-08-19 17:13 UTC, knz commented
I'd love to hear the objection but all the while I'd like to point out we do need this for client compatibility.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2018-08-20 16:35 UTC, andreimatei commented
The closest thing I can think of was the fact that I was complaining a while back about "char" being an alias for "string".

2018-08-20 16:36 UTC, justinj commented
Ok, ignore me then!

2018-08-21 13:48 UTC, knz commented
@nvanbenschoten I implemented the encoding like we discussed yesterday and that fixes all the remaining problems! :tada:

2018-08-28 10:27 UTC, knz commented
rebased

2018-08-30 15:15 UTC, justinj approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>! Great job on getting all this done, looks like a ton of work.

Consider adding some tests of this to the Hibernate acceptance tests - we've been bitten before by the amount of introspection Hibernate does and I think making sure we can create a table with this type would be really valuable.

> Reviewed 12 of 69 files at r2, 8 of 25 files at r3, 24 of 42 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLANoiYAFeIhRgVj8hM:b-nh3mj0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/coltypes/aliases.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAD4fwC2jU00M6w5lm:-LLAD4fxCi6bNFmdNPSW:b-mx57oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/sql/coltypes/aliases.go#L124)):*
> ```Go
> // NewBitArrayType creates a new BIT type with the given bit width.
> func NewBitArrayType(width int, varying bool) (*TBitArray, error) {
> 	if width < 1 {
> ```

Why does this error even if `varying` is true?
___
*[pkg/sql/logictest/testdata/logic_test/bit, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAH7pt63bU1h5jOvar:-LLAH7pt63bU1h5jOvas:b-1or9y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/sql/logictest/testdata/logic_test/bit#L12)):*
> ```
> 
> statement ok
> CREATE TABLE bits(a BIT, b BIT(4), c VARBIT, d VARBIT(4))
> ```

I think this might be missing tests for `BIT[]` and `VARBIT[]`?
___
*[pkg/sql/logictest/testdata/logic_test/bit, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLADnDOE_dewcwDqO_R:-LLADnDOE_dewcwDqO_S:b-x4m8pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/sql/logictest/testdata/logic_test/bit#L68)):*
> ```
> subtest results
> 
> query TITITITI colnames
> ```

I like this style of logic test :thumbsup: 
___
*[pkg/util/bitarray/bitarray.go, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAIaRnESGZRUakIUNp:-LLAIaRoAWMRoGFPqADB:b-othf8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray.go#L34)):*
> ```Go
> // For portability, the size of the backing word is guaranteed to be 64
> // bits.
> type BitArray struct {
> ```

May or may not be necessary or beneficial depending on the usage patterns of `BitArray`, but I like the trick in `bytes.Buffer` of keeping a static `[1]word` which `word` can initially point to to avoid heap allocations in the common case of small arrays. As we discovered though, this can open the door to very subtle bugs if these are ever passed by value, so might not be worth it.
___
*[pkg/util/bitarray/bitarray_test.go, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAMKyy3-V_RkMfcFBD:-LLAMKyy3-V_RkMfcFBE:b-9immve) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray_test.go#L473)):*
> ```Go
> }
> 
> func TestConcat(t *testing.T) {
> ```

:thumbsup: at the coverage here, this also seems like a candidate for random testing? asserting that `Concat(Parse(x), Parse(y)) = Parse(Concat(x, y))`. Only if you feel like it though, these tests seem pretty comprehensive.
___
*[pkg/util/encoding/encoding.go, line 1185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAM7SZ7R5ZsmSOKtK2:-LLAM7SZ7R5ZsmSOKtK3:b7qfvzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/encoding/encoding.go#L1185)):*
> ```Go
> 	Tuple        Type = 16
> 	BitArray     Type = 17
> 	BitArrayDesc Type = 18 // BitArray encoded descendingly
> ```

Why is this a thing when none of the other tags have it?


<!-- Sent from Reviewable.io -->

2018-08-31 19:48 UTC, knz reviewed
Thanks for the review! RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLGWufyEqRbSDbBKxX0:b-6sx6b6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/coltypes/aliases.go, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAD4fwC2jU00M6w5lm:-LLGKGonCGJX15S9hgu7:bq49zdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/sql/coltypes/aliases.go#L124)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Why does this error even if `varying` is true?
</blockquote></details>

Because the syntax `VARBIT(0)` is incorrect. This function only gets called when the parentheses are specified in the syntax.
___
*[pkg/sql/logictest/testdata/logic_test/bit, line 12 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAH7pt63bU1h5jOvar:-LLGQ7D38TdC6EqG5unQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/sql/logictest/testdata/logic_test/bit#L12)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this might be missing tests for `BIT[]` and `VARBIT[]`?
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAIaRnESGZRUakIUNp:-LLGKag8EuwF23oER26W:bm757vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray.go#L34)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

May or may not be necessary or beneficial depending on the usage patterns of `BitArray`, but I like the trick in `bytes.Buffer` of keeping a static `[1]word` which `word` can initially point to to avoid heap allocations in the common case of small arrays. As we discovered though, this can open the door to very subtle bugs if these are ever passed by value, so might not be worth it.
</blockquote></details>

Let's care about this when it shows up in profiles.
___
*[pkg/util/bitarray/bitarray_test.go, line 473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAMKyy3-V_RkMfcFBD:-LLGSmln1tRj0ovkOmwS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray_test.go#L473)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

:thumbsup: at the coverage here, this also seems like a candidate for random testing? asserting that `Concat(Parse(x), Parse(y)) = Parse(Concat(x, y))`. Only if you feel like it though, these tests seem pretty comprehensive.
</blockquote></details>

Done.
___
*[pkg/util/encoding/encoding.go, line 1185 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAM7SZ7R5ZsmSOKtK2:-LLGWkIe1dzEWHo7_BWn:b-7a95rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/encoding/encoding.go#L1185)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Why is this a thing when none of the other tags have it?
</blockquote></details>

Because otherwise it breaks the code in `pkg/keys/printer.go` (code which shouldn't exist IMHO, but there we are)


<!-- Sent from Reviewable.io -->

2018-09-01 18:55 UTC, nvb requested changes
Got through a first pass mostly focusing on `sql`. Need to do a closer one on the encoding package.

> Reviewed 12 of 69 files at r2, 5 of 25 files at r3, 21 of 42 files at r4, 8 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLLU1F14YLNv3GBWfUJ:bcqjkn5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/data.go, line 437 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLQVPe4aez9NEH0HWK:-LLLQVPe4aez9NEH0HWL:bsjqpds) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/roachpb/data.go#L437)):*
> ```Go
> // receiver, sets the tag and clears the checksum.
> func (v *Value) SetBitArray(t bitarray.BitArray) {
> 	words, _ := t.EncodingParts()
> ```

Why not pull all of this logic into a `encoding.UpperBoundNonsortingUntaggedBitArraySize` function like we have for decimal?
___
*[pkg/sql/values_test.go, line 186 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLRGJf-1LxBR2WzPbN:-LLLRGJf-1LxBR2WzPbO:byu6xiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/values_test.go#L186)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	ba := bitarray.MakeBitArrayFromInt64(8, 58, 7)
> ```

Just inline this.
___
*[pkg/sql/coltypes/interface.go, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLRbuVCMObqTp5DbcN:-LLLRbuVCMObqTp5DbcO:b6f1x30) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/coltypes/interface.go#L60)):*
> ```Go
> }
> 
> func (*TBitArray) columnType()       {}
> ```

It would sure be nice if these were sorted.
___
*[pkg/sql/pgwire/types.go, line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLSyIs6lyTSrEQk0rk:-LLLSyIs6lyTSrEQk0rl:bgecbbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/pgwire/types.go#L201)):*
> ```Go
> 		for i := 0; i < len(words)-1; i++ {
> 			w := words[i]
> 			byteBuf[0] = byte(w >> 56)
> ```

Does `BigEndian.PutUint64(byteBuf[:], uint64(w))` work?


<!-- Sent from Reviewable.io -->

2018-09-01 21:23 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/data.go, line 437 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLQVPe4aez9NEH0HWK:-LLM-FVB30qgDHwECkh0:bs5tljc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/roachpb/data.go#L437)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why not pull all of this logic into a `encoding.UpperBoundNonsortingUntaggedBitArraySize` function like we have for decimal?
</blockquote></details>

'cause it is used just in one place. Look at SetDuration above and SetTime above that.
___
*[pkg/sql/values_test.go, line 186 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLRGJf-1LxBR2WzPbN:-LLM-W0d76na5huV6X_Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/values_test.go#L186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Just inline this.
</blockquote></details>

Done.
___
*[pkg/sql/coltypes/interface.go, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLRbuVCMObqTp5DbcN:-LLM-csq14EAfsTJjWCM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/coltypes/interface.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It would sure be nice if these were sorted.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/types.go, line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLSyIs6lyTSrEQk0rk:-LLM-y2b8W3Sgq6H8wBf:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/pgwire/types.go#L201)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `BigEndian.PutUint64(byteBuf[:], uint64(w))` work?
</blockquote></details>

Thanks! Done.


<!-- Sent from Reviewable.io -->

2018-09-03 19:21 UTC, nvb approved these changes
This is very well done. Congrats on your first SQL data type!

> Reviewed 9 of 69 files at r2, 1 of 25 files at r3, 10 of 42 files at r4, 5 of 13 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLVYHEG3scGhJSBI71R:b-7xzkx5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/coltypes/interface.go, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLLRbuVCMObqTp5DbcN:-LLVVRsf2oYO5XRFFRnR:bi9estx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8dac0b07665ed462862e726d7ca993f5af58da04/pkg/sql/coltypes/interface.go#L60)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:pray: 
___
*[pkg/sql/sem/tree/datum.go, line 585 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVWsZD9KSynXX6mazn:-LLVWsZD9KSynXX6mazo:bm321jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/sql/sem/tree/datum.go#L585)):*
> ```Go
> // IsComposite implements the CompositeDatum interface.
> func (d *DBitArray) IsComposite() bool {
> 	return true
> ```

Is this true? I thought we had found a key encoding that round-trips. Also, there nothing was added to `HasCompositeKeyEncoding`.
___
*[pkg/sql/sqlbase/structured.proto, line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVZL0G-bURRVbbdSXQ:-LLVZL0G-bURRVbbdSXR:b-fc6ebk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/sql/sqlbase/structured.proto#L31)):*
> ```protobuf
> // ----------------------------
> //
> // | SQL type          | Semantic Type  | Visible Type | Precision | Width | Notes            |
> ```

Nice comment!
___
*[pkg/util/bitarray/bitarray.go, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAIaRnESGZRUakIUNp:-LLV_-8x9g1BWYWJNBSt:bvtek80) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray.go#L34)):*
Yeah, this is a good idea. Up to you whether you want to tackle it in the initial implementation. If not though, let's at least document the possible optimization in a TODO.

> Let's care about this when it shows up in profiles.

What profiles? Are we planning on creating a benchmark or workload that uses the new data type? Do we already have any that stress SQL expression evaluation?
___
*[pkg/util/bitarray/bitarray.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLV_eL5-6CPp4rPkL-o:-LLV_eL5-6CPp4rPkL-p:b-a8axwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L48)):*
> ```Go
> 	//   0 if lastBitsUsed = 0  or len(word) == 0
> 	//   otherwise, (len(words)-1)*numBitsPerWord + lastBitsUsed
> 	words []word
> ```

Out of curiosity, why `[]word` over `[]byte`? Are you trying to enforce word-alignment? Does that allow for more efficient bitwise operations? Please add the explanation to this comment.
___
*[pkg/util/bitarray/bitarray.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVa6voArEJ9-uBqt2_:-LLVa6voArEJ9-uBqt2a:b-ely4f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L53)):*
> ```Go
> 	// participate in the value stored. It can only be zero
> 	// for empty bit arrays; otherwise it's always between 1 and
> 	// numBitsPerWord.
> ```

It's a little surprising that the range of this value for non-empty bit arrays is `[1,numBitsPerWord]` instead of `[0,numBitsPerWord-1]`. Does that mean we waste an entire word if num bits is a multiple of 64?
___
*[pkg/util/bitarray/bitarray.go, line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVcIk2Cl89cS0SnWHD:-LLVcIk2Cl89cS0SnWHE:b8aniuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L95)):*
> ```Go
> }
> 
> // ToWidth resizes the bit array to the specified size.
> ```

This could use a more detailed description. If the method truncates, which end does it truncate from? If it pads extra bits, which end do they get added to?
___
*[pkg/util/bitarray/bitarray.go, line 96 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVd7dt3l4AvRAJX5xe:-LLVd7dt3l4AvRAJX5xf:bjxt59t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L96)):*
> ```Go
> 
> // ToWidth resizes the bit array to the specified size.
> func (d BitArray) ToWidth(n uint) BitArray {
> ```

`s/n/bitLen/`
___
*[pkg/util/bitarray/bitarray.go, line 106 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVdDvRCilIJr2iy8aF:-LLVdDvRCilIJr2iy8aG:b-qbdh57) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L106)):*
> ```Go
> 		words, lastBitsUsed := EncodingPartsForBitLen(n)
> 		copy(words, d.words[:len(words)])
> 		if len(words) > 0 {
> ```

When would `len(words) == 0`? Only when `n == 0`? That's probably worth a separate case to make it clear, which would allow us to simplify this case.
___
*[pkg/util/bitarray/bitarray.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVdt-wDmZyuHuNczKX:-LLVdt-wDmZyuHuNczKY:b-d6xx5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L125)):*
> ```Go
> 
> // Size returns the size in bytes of the bit array and its components.
> func (d BitArray) Size() uintptr {
> ```

nit: consider naming this `Sizeof` so that it can't be as easily confused with `BitLen()`.
___
*[pkg/util/bitarray/bitarray.go, line 236 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVh8pw4JUClQF6Qucz:-LLVh8pw4JUClQF6Qud-:b8v7488) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L236)):*
> ```Go
> // byteReprs contains the bit representation of the 256 possible
> // groups of 8 bits.
> var byteReprs = func() []string {
> ```

It will be a bit cleaner to make this an array:

```
var byteReprs = func() [256]string {
	var ret [256]string
	for i := range ret {
		// Change this format if numBitsPerWord changes.
		ret[i] = fmt.Sprintf("%08b", i)
	}
	return ret
}()
```

That will also give you more type safety. For instance, `byteReprs[256]` will no longer compile.
___
*[pkg/util/bitarray/bitarray.go, line 248 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVhn-8E1GF8O1-BczJ:-LLVhn-8E1GF8O1-BczK:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L248)):*
> ```Go
> func (d BitArray) Format(buf *bytes.Buffer) {
> 	bitLen := d.BitLen()
> 	buf.Grow(int(bitLen))
> ```

:thumbsup: 
___
*[pkg/util/bitarray/bitarray.go, line 286 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVcn8z8Mdg32CnP2pF:-LLVcn8z8Mdg32CnP2pG:b-ftqst4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L286)):*
> ```Go
> // the requested bit array size.
> func SizesForBitLen(bitLen uint) (uint, uint64) {
> 	numWords := (bitLen + numBitsPerWord - 1) / numBitsPerWord
> ```

`// ceiling`
___
*[pkg/util/bitarray/bitarray.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVepfB0FAScdU6BHN0:-LLVepfB0FAScdU6BHN1:bxajzat) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L349)):*
> ```
> lastbitsused
> ```

nit: camel case.
___
*[pkg/util/bitarray/bitarray.go, line 361 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVf8C09y [...]

2018-09-04 00:00 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/datum.go, line 585 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVWsZD9KSynXX6mazn:-LLWm5FA-1EGF3Wrmb-2:b-f6ad32) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/sql/sem/tree/datum.go#L585)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this true? I thought we had found a key encoding that round-trips. Also, there nothing was added to `HasCompositeKeyEncoding`.
</blockquote></details>

No it's not -- this was a mistaken remnant from an earlier version of the PR. Removed. Good catch.
___
*[pkg/util/bitarray/bitarray.go, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLAIaRnESGZRUakIUNp:-LLWmQua5blYw-ppKIV3:b-7yd1q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b86be47b01b6921e2b63833fac327992bb433a2/pkg/util/bitarray/bitarray.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, this is a good idea. Up to you whether you want to tackle it in the initial implementation. If not though, let's at least document the possible optimization in a TODO.

> Let's care about this when it shows up in profiles.

What profiles? Are we planning on creating a benchmark or workload that uses the new data type? Do we already have any that stress SQL expression evaluation?
</blockquote></details>

Added a TODO.
___
*[pkg/util/bitarray/bitarray.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLV_eL5-6CPp4rPkL-o:-LLWmT-K4BVNp-AmBfE6:b-h6ek2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, why `[]word` over `[]byte`? Are you trying to enforce word-alignment? Does that allow for more efficient bitwise operations? Please add the explanation to this comment.
</blockquote></details>

This is literally explained in the comment above the type definition.
___
*[pkg/util/bitarray/bitarray.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVa6voArEJ9-uBqt2_:-LLWnWMt6szb9wqVU3ij:byq9z58) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's a little surprising that the range of this value for non-empty bit arrays is `[1,numBitsPerWord]` instead of `[0,numBitsPerWord-1]`. Does that mean we waste an entire word if num bits is a multiple of 64?
</blockquote></details>

Added a comment to clarify.
___
*[pkg/util/bitarray/bitarray.go, line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVcIk2Cl89cS0SnWHD:-LLWo_gN61JTWwlXYhQK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This could use a more detailed description. If the method truncates, which end does it truncate from? If it pads extra bits, which end do they get added to?
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 96 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVd7dt3l4AvRAJX5xe:-LLWoi_p5OF6ZV79r7DH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/n/bitLen/`
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 106 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVdDvRCilIJr2iy8aF:-LLWp4Lp0lNMj0jfy58i:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L106)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When would `len(words) == 0`? Only when `n == 0`? That's probably worth a separate case to make it clear, which would allow us to simplify this case.
</blockquote></details>

Good idea. Done.
___
*[pkg/util/bitarray/bitarray.go, line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVdt-wDmZyuHuNczKX:-LLWpC1L-N2H2b1SOHLf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider naming this `Sizeof` so that it can't be as easily confused with `BitLen()`.
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 236 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVh8pw4JUClQF6Qucz:-LLWpOOx4f0-kckp0n-U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It will be a bit cleaner to make this an array:

```
var byteReprs = func() [256]string {
	var ret [256]string
	for i := range ret {
		// Change this format if numBitsPerWord changes.
		ret[i] = fmt.Sprintf("%08b", i)
	}
	return ret
}()
```

That will also give you more type safety. For instance, `byteReprs[256]` will no longer compile.
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 286 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVcn8z8Mdg32CnP2pF:-LLWpc0y-O5pm_sXuWbk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L286)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`// ceiling`
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 349 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVepfB0FAScdU6BHN0:-LLWpk2Y364buf9LC07z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L349)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> lastbitsused
> ```

nit: camel case.
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 361 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVf8C09ycbo2OsXG2L:-LLWppB59UDP9WyOItyl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L361)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Here and in the next few lines

`s/64/numBitsPerWord/`
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 384 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVfDx4C9TnNs_uu6uM:-LLWpxcF0F7l5QbAQgaP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L384)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/64/numBitsPerWord/`
</blockquote></details>

Done.
___
*[pkg/util/bitarray/bitarray.go, line 470 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVfkQQ-av5LBqZWuUK:-LLWq0SS6GKuqi5yWB1S:b-896fix) ([raw file](https://github.com/cockr [...]

2018-09-04 00:04 UTC, knz commented
@nvanbenschoten happy to merge if you're happy about my answer about the encoding.

2018-09-04 00:54 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/bitarray/bitarray.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLV_eL5-6CPp4rPkL-o:-LLWvB0j4wTOcFROdOpV:b-kfrr8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L48)):*
Are you referring to the following comment?

> ```
> // This uses a packed encoding (i.e. multiple bits per word) for
> // memory efficiency and speed of bitwise operations, but there is
> // something fancy needed to handle sorting values properly: the last ...
> ```

That does not sufficiently answer my question. It compares storing a single bit per word vs. storing multiple bits per word. I'm asking about a packed encoding where the backing array is typed with `byte` elements instead of `word` elements. This would be more memory efficient because we would only waste up to 7 bits in the final element instead of up to 63.

I take it from your answer that word-sized bitwise instructions are the reason to compromise on the memory efficiency. In that case, please call out this comparison explicitly (ideally on the `words` field itself).

Also, `s/bit.nat/big.nat/` now that this has changed.
___
*[pkg/util/bitarray/bitarray.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVa6voArEJ9-uBqt2_:-LLWx6GJAxOsDbknJufI:b-7n4c6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L53)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Added a comment to clarify.
</blockquote></details>

Thanks, that helps!
___
*[pkg/util/encoding/encoding.go, line 1047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVisZK4RZrSgwoscuH:-LLWzNQU37VoIoKrCKQV:b7p7kqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/encoding/encoding.go#L1047)):*
> encodeBytesAscendingWithoutTerminatorOrPrefix requires a byte slice as input, where the data is already organized in big endian. The new BitArray type does not provide this; allocating a byte array, running BigEndian.ToUint64 and then encoding via encodeBytesAscendingWithoutTerminatorOrPrefix looks waaay too expensive.
>
> Instead, one would need to re-implement the logic of encodeBytesAscendingWithoutTerminatorOrPrefix to operate on uint64 values directly. This is non-trivial and would only be needed for this (rather uncommon) data type

I think we can work around this with a bit of unsafe magic, which is somewhat par for the course in our `encoding` package. See https://play.golang.org/p/o05zNf5R_3C. We can then pass the resulting unsafe byte slice directly to `encodeBytesAscendingWithTerminator` without any mem copies. How does that sound?


<!-- Sent from Reviewable.io -->

2018-09-04 00:59 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/bitarray/bitarray.go, line 48 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLV_eL5-6CPp4rPkL-o:-LLX4SW96Af9_jjmVNnd:btwedtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/bitarray/bitarray.go#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are you referring to the following comment?

> ```
> // This uses a packed encoding (i.e. multiple bits per word) for
> // memory efficiency and speed of bitwise operations, but there is
> // something fancy needed to handle sorting values properly: the last ...
> ```

That does not sufficiently answer my question. It compares storing a single bit per word vs. storing multiple bits per word. I'm asking about a packed encoding where the backing array is typed with `byte` elements instead of `word` elements. This would be more memory efficient because we would only waste up to 7 bits in the final element instead of up to 63.

I take it from your answer that word-sized bitwise instructions are the reason to compromise on the memory efficiency. In that case, please call out this comparison explicitly (ideally on the `words` field itself).

Also, `s/bit.nat/big.nat/` now that this has changed.
</blockquote></details>

Done.

The memory efficiency is a non-argument. A heap allocator will allocate byte arrays larger than a few bytes in groups of 8 or 16 bytes anyway.
___
*[pkg/util/encoding/encoding.go, line 1047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVisZK4RZrSgwoscuH:-LLX4cHtDAHFyphE4JYT:b-pj28qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/encoding/encoding.go#L1047)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> encodeBytesAscendingWithoutTerminatorOrPrefix requires a byte slice as input, where the data is already organized in big endian. The new BitArray type does not provide this; allocating a byte array, running BigEndian.ToUint64 and then encoding via encodeBytesAscendingWithoutTerminatorOrPrefix looks waaay too expensive.
>
> Instead, one would need to re-implement the logic of encodeBytesAscendingWithoutTerminatorOrPrefix to operate on uint64 values directly. This is non-trivial and would only be needed for this (rather uncommon) data type

I think we can work around this with a bit of unsafe magic, which is somewhat par for the course in our `encoding` package. See https://play.golang.org/p/o05zNf5R_3C. We can then pass the resulting unsafe byte slice directly to `encodeBytesAscendingWithTerminator` without any mem copies. How does that sound?
</blockquote></details>

No that's incorrect - x86 (and x86-64 and many other modern architectures) store words in memory little-endian, so you get the LSB at the lower addresses, the opposite of what we want.


<!-- Sent from Reviewable.io -->

2018-09-04 01:23 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

But please consider my suggestion for a table-driven encoding test as well. These are often some of the best forms of documentation for encoding routines.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLX9sJyBJ-HuLUJ4enA:b-m8o9fb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/util/encoding/encoding.go, line 1047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVisZK4RZrSgwoscuH:-LLX6uSI-TlsYAbD7bbQ:b8s6sav) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/encoding/encoding.go#L1047)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

No that's incorrect - x86 (and x86-64 and many other modern architectures) store words in memory little-endian, so you get the LSB at the lower addresses, the opposite of what we want.
</blockquote></details>

Hm yeah, you're right. I was thinking that endianness wouldn't matter because this would still round-trip, but it would affect sorting. In that case please just leave a small comment about why we're somewhat unintuitively using a varint encoding for each word.
___
*[pkg/util/encoding/encoding_test.go, line 610 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLX8PpD85051uTT2Jfo:-LLX8PpD85051uTT2Jfp:b-wdga5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfca88a705ebb60d59e0d594d26515b8f62f732f/pkg/util/encoding/encoding_test.go#L610)):*
> ```Go
> 
> func TestKeyEncodeDecodeBitArray(t *testing.T) {
> 	rng, seed := randutil.NewPseudoRand()
> ```

nit: Randomized testing is nice, but it would also be good to have a table-driven test like `TestEncodeDecodeBytes` and `TestEncodeDecimal` that includes all edge-cases and a few basic cases like:

```
B''
B'0'
B'1'
B'00'
B'01'
B'10'
B'1...64 times...'
B'1...65 times...'
etc.
```

In this package, these tests serve both as sanity checks and as documentation.


<!-- Sent from Reviewable.io -->

2018-09-04 02:39 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/encoding/encoding.go, line 1047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVisZK4RZrSgwoscuH:-LLXEIa89xCGAl3gK8TH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/encoding/encoding.go#L1047)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Hm yeah, you're right. I was thinking that endianness wouldn't matter because this would still round-trip, but it would affect sorting. In that case please just leave a small comment about why we're somewhat unintuitively using a varint encoding for each word.
</blockquote></details>

Done.
___
*[pkg/util/encoding/encoding_test.go, line 610 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLX8PpD85051uTT2Jfo:-LLXRdhL0gcMEPbkd4_V:b-u5owhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfca88a705ebb60d59e0d594d26515b8f62f732f/pkg/util/encoding/encoding_test.go#L610)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Randomized testing is nice, but it would also be good to have a table-driven test like `TestEncodeDecodeBytes` and `TestEncodeDecimal` that includes all edge-cases and a few basic cases like:

```
B''
B'0'
B'1'
B'00'
B'01'
B'10'
B'1...64 times...'
B'1...65 times...'
etc.
```

In this package, these tests serve both as sanity checks and as documentation.
</blockquote></details>

Good advice. Done. In  fact, by adding this test I discovered a bug in my encoding :) Fixed too.


<!-- Sent from Reviewable.io -->

2018-09-04 03:07 UTC, knz commented
Banzai! And TFYR

bors r+

2018-09-04 03:25 UTC, merged

2018-09-04 03:41 UTC, nvb reviewed
Awesome job getting this in!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-:-LLXeUEP6Ir25qNsgCGb:b3s5mm3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/util/encoding/encoding.go, line 1047 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28807#-LLVisZK4RZrSgwoscuH:-LLXdyEQAp_16HnfVBwf:bp94vm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6df1a975f8ea54d701e2ce927a95b80e9042688/pkg/util/encoding/encoding.go#L1047)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Using varints here does have one major benefit that became clear when looking at the test cases you just added - it's significantly more efficient in encoding sparse bit arrays! My statement from above that `we have no reason to believe the data distribution of other words in a BitArray will be anything other than random` isn't true in this case.


<!-- Sent from Reviewable.io -->

2018-09-04 03:58 UTC, knz commented
> Using varints here does have one major benefit that became clear when looking at the test cases you just added - it's significantly more efficient in encoding sparse bit arrays! My statement from above that we have no reason to believe the data distribution of other words in a BitArray will be anything other than random isn't true in this case.

I personally have no reason to believe that bit arrays will tend to be sparse in practice... I wouldn't use that argument to justify this encoding without peeking into actual user workloads.

2018-09-07 19:06 UTC, rytaft commented
Are you planning to backport this? I have another change to `sql/sem/tree/eval.go`, and wondering if I should wait for your backport. Thanks!





<!-- Sent from Reviewable.io -->

2018-09-07 20:18 UTC, knz commented
I don't know! Ask Andy Woods

2018-09-07 20:55 UTC, rytaft commented
@awoods187 -- do we want to backport this support for bit arrays?

2018-09-07 21:26 UTC, RaduBerinde commented
If we foresee running into many merge conflicts, I think we should backport regardless of business reasons.

2018-09-09 22:29 UTC, bdarnell commented
I don't think we should backport this. It's a new feature post-freeze, and it has compatibility implications (changing the meaning of the BIT type and capital-B-prefixed byte literals). I'd be OK with backporting the removal of the old BIT type, though. 

I'm not a fan of making bit/byte literals case-sensitive as a transitional strategy. Even though CRDB only documented lowercase `b` for byte literals and postgres only documented capital `B`, both were implemented in a case-insensitive way, and it's surprising to introduce this case-sensitivity in the otherwise-case-insensitive SQL language (even case-sensitive languages like python that have prefixes like this make them case-insensitive).

2018-09-10 03:34 UTC, knz commented
Regarding b/B it's really about slowly deprecating the small b for byte arrays, but there's only so much we can do in one release. Also the two types of literals cannot auto convert to each others types so the error messages will be clear.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2018-09-10 14:48 UTC, knz commented
Just a detail for the record: BIT was already removed *prior to the fork* meaning that the 2.1 betas never had BIT to start with. So backporting this would not "change the meaning of BIT".

It would change b/B though. Although I wonder how much that matters in practice.

2018-09-11 15:13 UTC, knz commented
I'd say do the backport and manually resolve the merge conflicts as if the bitarray type was not available.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2018-09-11 17:14 UTC, rytaft commented
👍