distsqlrun: bump MinAcceptedVersion to 21
cockroachdb/cockroach pull request #28977
Opened 2018-08-22 21:16 UTC by mjibson

This change makes 2.0 nodes not schedule distsql work on 2.1 nodes. This
change is being made because we don't adequately test clusters in
a skewed version environment. This means we could have missed actual
breaking changes that should have bumped the min version but didn't. In
lieu of that testing, prevent cross version work from being done.

This does mean that SQL workloads in a version upgrade environment will
experience performance loss if the entire cluster can't be used and data
has to be streamed to a gateway.

Release note (sql change): Prevent 2.0 nodes from scheduling distsql
work on 2.1 nodes.

2018-08-22 21:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/28977)
<!-- Reviewable:end -->

2018-08-22 22:12 UTC, andreimatei reviewed
LGTM

pls say something about import in the commit message, otherwise it's too scary. Also put something in `version_history.txt`. Also technically this PR has nothing to do with 2.1 - I assume you're going to backport?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-:-LKYg1f46DDBddqkqvyK:bacvzr4)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-23 06:32 UTC, mjibson commented
Yes, going to backport this.

2018-08-23 19:08 UTC, mjibson commented
Added some IMPORT comments.

2018-08-24 15:06 UTC, andreimatei requested changes
"However it is also possible there are other unknown breakages in distsql land"
- what's up with this? We can't generally be scared that there might always be breakages in "DistSQL land" - if we were we wouldn't have a distinction between version and min_accepted_version. Say that you're not confident in import specifically, or argue more for a general bankruptcy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-:-LKgSaEI2Iqkfad9Go_r:b89s3gt)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/version_history.txt, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-LKgSVkRBAb3sD7q6nbB:-LKgSVkRBAb3sD7q6nbC:b-nnwjmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd316117972bddbfe3ff4692958505f48a7bf88/pkg/sql/distsqlrun/version_history.txt#L83)):*
> ```
>       requested. The new processor spec would be ignored by old versions.
> - MinAcceptedVersion: 21
>     - Bump in preparation for the 2.1 release.
> ```

this comment doesn't say anything... Say something about import.


<!-- Sent from Reviewable.io -->

2018-08-24 21:32 UTC, mjibson commented
This isn't about just IMPORT. I had a discussion with Arjun about this. While testing IMPORT I found a bunch of bugs in various parts of the system (jobs mostly, not something IMPORT-specific; also #29018 which appears to be KV-related) that manifest in cross version clusters. Bumping the min version here is done because we don't properly test cross version clusters, and so we actually haven't verified that distsql-related things work correctly. In short: until we actually write some tests to verify that we don't have bugs in known circumstances, we're going to do something safer and make sure we can't trigger one.

2018-08-27 16:20 UTC, andreimatei reviewed
If we're in a perpetual scare, we should remove the `min_accepted_version` mechanism (or at the very least write instructions asking temporarily for updates to the version to also bump the min_version with a link to an issue where a testing plan can be discussed).
But why are we so scared, exactly? You quote problems with jobs and #29018. Do either of these have anything to do with DistSQL?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-:-LKw9sTPEsVF4o7nkCDR:b-58akym)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-27 16:28 UTC, rjnn reviewed
Jumping in, we aren't in a perpetual scare. @mjibson and I had a discussion about the large volume of code changes, which are not sufficiently tested in mixed-version settings. Some preliminary testing with IMPORT indicated that there were problems. We discussed various fixes, and concluded that while it was possible to port some bugfixes that would result in mixed version clusters working, this would

1. require a large engineering burden on the IMPORT team
2. still leave us with a testing burden on mixed-version clusters for IMPORT after the engineering work is completed.
3. still leave unresolved the large volume of code changes in SQL execution that have not been properly tested in mixed-version settings

Thus, we determined that for this major release, bumping the min accepted version was an acceptable course of action.

We have not made a determination about future major releases. We can add this to the list of questions the SQL execution team will discuss going forward in the 2.2 development cycle. We will need add comprehensive mixed-version testing automation (which will require changes to roachtest, which is currently incapable of deploying mixed version clusters) so that we can get the required confidence in distributing queries across mixed-version clusters before enabling them. Right now, this is the safest course of action, and involves slight degradation in query performance (but no degradation in overall cluster capability) during a cluster upgrade.

I hope this helps clarify the situation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-:-LKwBbzq0KpeHIzcDDFt:bt7wjq2)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-27 16:38 UTC, andreimatei commented
LGTM

The only thing under discussion here is whether an unqualified "- Bump in preparation for the 2.1 release." is a good enough comment, which I maintain that it isn't.

2018-08-27 19:27 UTC, andreimatei reviewed
better, thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28977#-:-LKwqd456MJAKzPlP_VB:b-4asoem)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-27 19:28 UTC, mjibson commented
bors r+

2018-08-27 20:32 UTC, merged