sql: stop using a cancelled context to retry a schema change
cockroachdb/cockroach pull request #29163
Opened 2018-08-28 01:29 UTC by vivekmenezes

Some other cleanup of schema change synchronous execution
code path.

related to #28991

Release note: None

2018-08-28 01:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/29163)
<!-- Reviewable:end -->

2018-08-28 01:46 UTC, andreimatei requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

no test? :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LKyCV0eDKJqrd-HU2k9:b6ptrhu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LKyB8fO88Rbg3cedfe1:bpppm8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
> ```Go
> }
> 
> func (scc *schemaChangerCollection) isEmpty() bool {
> ```

I liked it more before; now we need to document that one cannot call `execSchemaChanges()` on an empty object?
If you leave it, then perhaps assert that it's not empty?
___
*[pkg/sql/exec_util.go, line 920 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyBo_G8LSAmiJvl6I8:-LKyBo_G8LSAmiJvl6I9:b-j7zpfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L920)):*
> ```Go
> 						firstError = err
> 					}
> 				} else if err == sqlbase.ErrDescriptorNotFound || err == context.Canceled {
> ```

nit: do `err == ctx.Err()` which will catch DeadlineExceeded too.
Rant: it's infuriating that the go library uses a sentinel error here, when `ctx` is supposed to be an interface. `context.Canceled` is the worst sentinel in the history of sentinels because you always want to extend this error with more damn info.


<!-- Sent from Reviewable.io -->

2018-08-28 13:59 UTC, vivekmenezes reviewed
Is there known way to terminate a request?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL-nRQa27zw9RleoytM:b-14nsy0)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LL-kfIVAnF5Loi5TPZQ:b-8vmqf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I liked it more before; now we need to document that one cannot call `execSchemaChanges()` on an empty object?
If you leave it, then perhaps assert that it's not empty?
</blockquote></details>

well I just felt that this code was being called on every request and thought that this structure would be more performant. I'll add an assert that it's not empty.


<!-- Sent from Reviewable.io -->

2018-08-28 14:10 UTC, vivekmenezes reviewed
I'll take CANCEL SESSION for a spin. Coming up

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL-rjuv2wpp8QUtcX-4:b-guzflw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-28 14:59 UTC, andreimatei commented
Or close a connection (db.Close()), or use the InternalExecutor with your
own context.

On Tue, Aug 28, 2018 at 10:12 AM vivekmenezes <notifications@github.com>
wrote:

> *@vivekmenezes* commented on this pull request.
>
> I'll take CANCEL SESSION for a spin. Coming up
>
> *Reviewable
> <https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL-rjuv2wpp8QUtcX-4:b-guzflw>*
> status: [image: :shipit:] complete! 0 of 0 LGTMs obtained (and 1 stale)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/29163#pullrequestreview-150141877>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAXBcRMTs4Y8lZBmmZg5eQ7kkRjMeTFlks5uVU-2gaJpZM4WOwdq>
> .
>

2018-08-29 02:12 UTC, vivekmenezes reviewed
I was unable to use db.Close() because it would not close the session before executing the command on the session. I'm unable to use CANCEL QUERY because the schema change is not listed as an executing query once it has committed. I've added in a testing knob that calls cancelSession directly to cancel the context. One of the problems with doing this is while it tests this change correctly, it also retries the schema change (the original transaction), which fails saying that the index already exists.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL2RQ9pDOaVfEY5lP-h:b-gai0nk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-29 19:03 UTC, andreimatei reviewed
What about `cancel session` or that connection closing test I pointed to on slack (I think it was using pgx for lower level access)?
Separately, do you think the schema change should keep the query in the registry? Seems to me like it'd be what a user expected.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL62uQQ7dv4Lkhu7hUK:b-5ol52g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-29 20:56 UTC, vivekmenezes reviewed
I've been able to get this to work using CANCEL SESSION. Looks like I've uncovered another problem, when the context gets cancelled the schema change execution correctly stops, but then the executor reruns the "CREATE INDEX " statement! There is a bug somewhere in the executor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL6Sv6bDBzJeLcvcKka:badu0rb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-29 21:06 UTC, vivekmenezes reviewed
I'm on it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL6VeIZDiIcNAJzCk8A:b-o0ac96)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-08-30 16:07 UTC, vivekmenezes reviewed
So using the gosql.DB client would retry the schema change request if the connection was closed. Using a connection instead resolved the problem. I've added a comment explaining this to the test.

I've also added another related commit that stops rollbacks in the event of a grpc error. Using a whitelisting approach to retrying is turning out to be a bit painful, but it's still better than a blacklist.

Please take a look. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LLA_9vc-R7Rh3dk47fM:bj795ds)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-04 16:03 UTC, vivekmenezes commented
@andreimatei any thoughts on this?

2018-09-04 17:49 UTC, andreimatei requested changes
LGTM

nit: I find `sql: grpc errors will not rollback a schema change.` hard to understand; are you saying that that's a bad thing, or is that the desired state?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LL_fJe-2Yke3xCgHrSH:brbqp3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LL_aJOcC3uhcBa1v3Th:b-ram25u) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

well I just felt that this code was being called on every request and thought that this structure would be more performant. I'll add an assert that it's not empty.
</blockquote></details>

more performant by eliminating one function call per transaction?
___
*[pkg/sql/schema_changer.go, line 1217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_aX5f4bVYt0iVd0kT:-LL_aX5f4bVYt0iVd0kU:bgg3uls) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer.go#L1217)):*
> ```Go
> 	// ErrorsSeen is called with all the errors seen by the
> 	// synchronous code path.
> 	ErrorsSeen func(err error)
> ```

`OnError()` ?
___
*[pkg/sql/schema_changer_test.go, line 3480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_aeln9HtmTwnDOtwv:-LL_aelo7d4qPo8oYpOi:bkrlbcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3480)):*
> ```
> a canceled context  ... returns with no error
> ```

You mean the COMMIT for something something doesn't return an error ?
___
*[pkg/sql/schema_changer_test.go, line 3492 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_dJiW2Itvm--Ai03C:-LL_dJiW2Itvm--Ai03D:b-hq6ogs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3492)):*
> ```Go
> 	params.Knobs = base.TestingKnobs{
> 		SQLSchemaChanger: &sql.SchemaChangerTestingKnobs{
> 			RunBeforeBackfill: func() error {
> ```

how about we pass the statement ctx to `RunBeforeBackfill` and, instead of `notifyContextCancel`, we poll on its `Err()`? I think that'd be easier to read.
Otherwise, please add a comment or renamed `notifyContextCancel` to `<something>Cancel*ed*`
___
*[pkg/sql/schema_changer_test.go, line 3536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bfQsCxfvBouoAnvZ:-LL_bfQsCxfvBouoAnv_:bmnac8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3536)):*
> ```Go
> 		defer wg.Done()
> 		ctx := context.TODO()
> 		// When using db.Exec(), CANCEL SESSION below will result in the
> ```

wait what? Is this https://github.com/lib/pq/issues/422? Cause it so, it apparently was fixed. Has our vendored lib/pq not gotten the fix?
___
*[pkg/sql/schema_changer_test.go, line 3544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_cCAy28jWLP7Omtpm:-LL_cCAy28jWLP7Omtpn:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3544)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		if _, err := conn.ExecContext(ctx, `CREATE INDEX foo ON t.public.test (v)`); err != gosqldriver.ErrBadConn {
> ```

long line
___
*[pkg/sql/schema_changer_test.go, line 3551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bvs14b7PrtY4-3Xq:-LL_bvs14b7PrtY4-3Xr:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3551)):*
> ```Go
> 	<-notifyBackfill
> 
> 	if _, err := db.Exec(`CANCEL SESSIONS (SELECT session_id FROM [SHOW SESSIONS] WHERE last_active_query LIKE 'CREATE INDEX%')`); err != nil {
> ```

long line
___
*[pkg/sql/schema_changer_test.go, line 3551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_cMiB6tHmwDfXcVZw:-LL_cMiB6tHmwDfXcVZx:bu4jebg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3551)):*
> ```Go
> 	<-notifyBackfill
> 
> 	if _, err := db.Exec(`CANCEL SESSIONS (SELECT session_id FROM [SHOW SESSIONS] WHERE last_active_query LIKE 'CREATE INDEX%')`); err != nil {
> ```

`conn.Close()` didn't work?
___
*[pkg/sql/schema_changer_test.go, line 3575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_f1lR00HxwqfD7Avq:-LL_f1lR00HxwqfD7Avr:b8evalc) ([raw file](https://github.com/cockroachdb/cockroach/blob/460ec6879702cf2f634aab567b1754e9536ef294/pkg/sql/schema_changer_test.go#L3575)):*
> ```Go
> 				if !seenNodeUnavailable {
> 					seenNodeUnavailable = true
> 					return errors.Errorf("node unavailable")
> ```

this seems a bit flimsy. Have you tried creating a `TestCluster` and stopping one of the nodes?


<!-- Sent from Reviewable.io -->

2018-09-11 15:52 UTC, vivekmenezes reviewed
reworded the commit message to say "ensure grpc ..."

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LM8KAor8BH9N0Y4AY_B:bi5xx2o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LM899Ki7MegGacTfvOp:bb7s9mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

more performant by eliminating one function call per transaction?
</blockquote></details>

yeah
___
*[pkg/sql/schema_changer.go, line 1217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_aX5f4bVYt0iVd0kT:-LM89oD52DrWga8Vmc_s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer.go#L1217)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`OnError()` ?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 3480 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_aeln9HtmTwnDOtwv:-LM8BnQO5hcxTEz-PGwn:b-4jqqo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3480)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> a canceled context  ... returns with no error
> ```

You mean the COMMIT for something something doesn't return an error ?

</blockquote></details>

reworded this comment
___
*[pkg/sql/schema_changer_test.go, line 3492 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_dJiW2Itvm--Ai03C:-LM8DEbP28-tc-t4Zqxv:b-b5qjrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3492)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about we pass the statement ctx to `RunBeforeBackfill` and, instead of `notifyContextCancel`, we poll on its `Err()`? I think that'd be easier to read.
Otherwise, please add a comment or renamed `notifyContextCancel` to `<something>Cancel*ed*`
</blockquote></details>

renamed to cancelSessionDone
___
*[pkg/sql/schema_changer_test.go, line 3536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bfQsCxfvBouoAnvZ:-LM8EhvlCU6DjFBrn4vx:bmvrut4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3536)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wait what? Is this https://github.com/lib/pq/issues/422? Cause it so, it apparently was fixed. Has our vendored lib/pq not gotten the fix?
</blockquote></details>

looks like https://github.com/lib/pq/pull/730 hasn't been picked up. @mjibson you made that fix.
___
*[pkg/sql/schema_changer_test.go, line 3544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_cCAy28jWLP7Omtpm:-LM8EuVFBQ316lYcuQTM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3544)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 3551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bvs14b7PrtY4-3Xq:-LM8C0zyBFZrpqiFaEZB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3551)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 3551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_cMiB6tHmwDfXcVZw:-LM8C2TfChKx2n3CpeZT:bx8wx3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3551)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`conn.Close()` didn't work?
</blockquote></details>

No that didn't work. I think it waited until the request completed. But now I forget.
___
*[pkg/sql/schema_changer_test.go, line 3575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_f1lR00HxwqfD7Avq:-LM8KGb83gkMlVcHzxFW:brvy1j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/460ec6879702cf2f634aab567b1754e9536ef294/pkg/sql/schema_changer_test.go#L3575)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this seems a bit flimsy. Have you tried creating a `TestCluster` and stopping one of the nodes?
</blockquote></details>

I'm asking around to see if we can do better here.


<!-- Sent from Reviewable.io -->

2018-09-11 16:11 UTC, andreimatei submitted a review, later dismissed
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LM8OdO90Mvczaf-MEUr:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LM8MwgNBpnfzK9u1Eb3:b-27u2az) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

yeah
</blockquote></details>

but I believe the patch now does the same amount of function calls on regular txns and adds one to schema change ones :)
In any case, I was trying to joke about saving a function call. Even if that somehow was achieved, I think that's hardly worth it for a worst API.
___
*[pkg/sql/schema_changer_test.go, line 3536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bfQsCxfvBouoAnvZ:-LM8MGy84Q1qi4F-M53j:b-mjukec) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3536)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

looks like https://github.com/lib/pq/pull/730 hasn't been picked up. @mjibson you made that fix.
</blockquote></details>

this comment as written is quite alarming. I think it's worth updating the vendored lib so we don't have to write it. Or at the very least we should verify that it's that bug at work and reference it.
But orthogonally, my vote is for trying harder to just close a connection rather than use `cancel session`. I think I pointed you to a test that uses pgx specifically for testing closing of connections. Have you considered that?
___
*[pkg/sql/schema_changer_test.go, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LM8OV0t9pDVsEAon_0m:-LM8OV0t9pDVsEAon_0n:b4ax92v) ([raw file](https://github.com/cockroachdb/cockroach/blob/20b6090aabfe49d368deec34e790cc59f1b13c9c/pkg/sql/schema_changer_test.go#L20)):*
> ```Go
> 	"context"
> 	gosql "database/sql"
> 	gosqldriver "database/sql/driver"
> ```

any reason for the named import? (it's unusual)
___
*[pkg/sql/schema_changer_test.go, line 3482 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LM8OCjyEQ6AeQvB5-jr:-LM8OCjyEQ6AeQvB5-js:bnuclvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/20b6090aabfe49d368deec34e790cc59f1b13c9c/pkg/sql/schema_changer_test.go#L3482)):*
> ```Go
> // This test checks that when a transaction containing schema changes
> // needs to be retried it gets retried internal to cockroach. This test
> // currently fails because a schema changeg transaction is not retried.
> ```

changeg

Technically this test does not "fail". Consider pasting it to the issue and removing it :)


<!-- Sent from Reviewable.io -->

2018-09-11 19:46 UTC, vivekmenezes reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/exec_util.go, line 881 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LKyB8fO88Rbg3cedfe0:-LM8WO16BShfyVW4vs24:b-oi03fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30911edb7546b1fba8f90472e3dddd99c91243a4/pkg/sql/exec_util.go#L881)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

but I believe the patch now does the same amount of function calls on regular txns and adds one to schema change ones :)
In any case, I was trying to joke about saving a function call. Even if that somehow was achieved, I think that's hardly worth it for a worst API.
</blockquote></details>

reverted this back to what it was
___
*[pkg/sql/schema_changer_test.go, line 3536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LL_bfQsCxfvBouoAnvZ:-LM8TdEIE3mK8kVQCTT6:b9buq3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e243b2fe7a3b5761e0cbb067235a5189f46342b0/pkg/sql/schema_changer_test.go#L3536)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment as written is quite alarming. I think it's worth updating the vendored lib so we don't have to write it. Or at the very least we should verify that it's that bug at work and reference it.
But orthogonally, my vote is for trying harder to just close a connection rather than use `cancel session`. I think I pointed you to a test that uses pgx specifically for testing closing of connections. Have you considered that?
</blockquote></details>

I just tried using pgx again and again ran into the same problem where the Close() is only activated once all requests on the connection complete.

I'm not sure what out policy is regarding cherrypicking new vendored libraries into the release branch. I think doing so for a test would be misguided. I've left a TODO to look into it later.
___
*[pkg/sql/schema_changer_test.go, line 20 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LM8OV0t9pDVsEAon_0m:-LM98hRbBB5olX-4mXHp:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/20b6090aabfe49d368deec34e790cc59f1b13c9c/pkg/sql/schema_changer_test.go#L20)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

any reason for the named import? (it's unusual)
</blockquote></details>

fixed
___
*[pkg/sql/schema_changer_test.go, line 3482 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-LM8OCjyEQ6AeQvB5-jr:-LM8TEqc3Ch0TnHuThcP:b-7jo1v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/20b6090aabfe49d368deec34e790cc59f1b13c9c/pkg/sql/schema_changer_test.go#L3482)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

changeg

Technically this test does not "fail". Consider pasting it to the issue and removing it :)
</blockquote></details>

I know we've done that in the past, but I personally think that's not the right choice. Code should be run.


<!-- Sent from Reviewable.io -->

2018-09-12 16:46 UTC, vivekmenezes commented
@andreimatei I know we've gone back and forth a lot on this PR. Is there anything more you'd like me to do? Thanks

2018-09-12 17:03 UTC, andreimatei reviewed
Well you got an LGTM a long time ago which, at least for me, means that I don't really want to look at this more :)
But I do think that the comment about "database client retrying the request on another connection" should not exist except in the presence of some documented issue, and this is a great time to address the vendoring TODO you've added :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LMDiUOAEi-DOTvMKr_i:b-odxjas)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-12 17:22 UTC, vivekmenezes reviewed
Bless you! Although despite the LGTM I still like to address all your comments, after all you have taken the time to make them. And you do aim high, and I strive to keep getting better :-)

The only reason I've added the TODO here is because I don't want the vendoring to be picked up by the release backport.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29163#-:-LMDn3aJ9j2QIhHjnarb:b85ayju)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-12 17:38 UTC, vivekmenezes commented
bors r=andreimatei

2018-09-12 17:41 UTC, vivekmenezes commented
bors r+

2018-09-13 14:14 UTC, vivekmenezes commented
bors r+

2018-09-14 01:43 UTC, merged

2018-09-21 14:54 UTC, knz commented
does this need a backport?

2018-09-24 14:29 UTC, vivekmenezes commented
yes, sent out a backport PR

On Fri, Sep 21, 2018 at 10:55 AM kena <notifications@github.com> wrote:

> does this need a backport?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/29163#issuecomment-423560900>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALOpBNp3Fk9Rh1rwe3v2KPEqclQrq6wiks5udP3rgaJpZM4WOwdq>
> .
>