changefeedccl: error when a watched table backfills
cockroachdb/cockroach pull request #29367
Opened 2018-08-30 19:02 UTC by danhhz

When a table is currently being backfilled for a schema change (e.g.
adding a column with a default value), it's unclear what the expectation
is for any rows that are changed during the backfill. Our current
invariant is that rows are emitted with an updated timestamp and a later
SELECT ... AS OF SYSTEM TIME for that row would exactly match the
emitted data. During the backfill, there is nothing we can emit that
would definitely meet that invariant (because the backfill can be
aborted and rolled back).

In the meantime, this commit makes sure that we error whenever a
backfill happens, even if it's fast enough that we never get it from
leasing.

This also paves the way for switching to RangeFeed, which doesn't have
the convenient `fetchSpansForTargets` hook that the ExportRequest based
poller was (ab)using.

Closes #28643

Release note (bug fix): CHANGEFEEDs now error when a watched table
backfills (instead of undefined behavior)

2018-08-30 19:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/29367)
<!-- Reviewable:end -->

2018-08-30 19:03 UTC, danhhz commented
@vivekmenezes can you review the second commit, please? It's got some assumptions about leasing and schema change backfills that I want to make sure I got right. Feel free to ignore the first commit, @mrtracy will review that one.

2018-09-04 14:49 UTC, danhhz commented
@mrtracy @vivekmenezes thoughts on this?

2018-09-04 16:47 UTC, vivekmenezes approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_RDfJ3d9QoGZ49z0Z:-LL_RDfJ3d9QoGZ49z0_:bll9uq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_processors.go#L171)):*
> ```Go
> 	}(ctx)
> 	ca.tableHistUpdaterDoneCh = make(chan struct{})
> 	go func(ctx context.Context) {
> ```

Any reason for not using poller.RunTask() ?
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_Ry7m-EcxNR1uUIdZ:-LL_Ry7m-EcxNR1uUId_:b3bdbju) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_stmt.go#L328)):*
> ```Go
> 			return errors.Errorf(`CHANGEFEEDs cannot operate on tables being backfilled`)
> 		}
> 	}
> ```

it will be cool if you can move the above logic surrounding Mutations to sit in sqlbase/structured.go . I've consciously tried to keep it there so that future refactoring work will be easier.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_TSoM2wrCO5t_zjae:-LL_TSoN5pEDW9HM43KY:b-7itycc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_test.go#L434)):*
> ```Go
> 			`unique: [2]->{"a": 2, "b": "2"}`,
> 		})
> 	})
> ```

Really nice job with the testing!


<!-- Sent from Reviewable.io -->

2018-09-04 17:13 UTC, danhhz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_RDfJ3d9QoGZ49z0Z:-LL_XitQ2chepKftgUsp:b-4io4yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_processors.go#L171)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Any reason for not using poller.RunTask() ?
</blockquote></details>

Good idea! I hadn't thought of it. Tried it just now, but looks like it's really awkward for distsql to handle an error during `Start`, so I think I'll keep this the way it is
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_Ry7m-EcxNR1uUIdZ:-LL_YjD73NjdVFxYnG13:b-sd7906) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_stmt.go#L328)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

it will be cool if you can move the above logic surrounding Mutations to sit in sqlbase/structured.go . I've consciously tried to keep it there so that future refactoring work will be easier.
</blockquote></details>

Absolutely! Done
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_TSoM2wrCO5t_zjae:-LL_Ynr_5ItoKSX-MmSp:b2qy0n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4585a05cfcc3d63f50ab7b6aed8ad5badadba4c/pkg/ccl/changefeedccl/changefeed_test.go#L434)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Really nice job with the testing!
</blockquote></details>

It caught TONS of bugs while I was writing the PR. Totally worth the effort


<!-- Sent from Reviewable.io -->

2018-09-04 17:28 UTC, vivekmenezes approved these changes

2018-09-04 17:58 UTC, mrtracy requested changes
Commit 1 is <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a couple of nits, nice tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-:-LL_j4Rn8MmE7E-JomLJ:bxgcfnh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/table_history.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_gBCuCIeSfTNtU2si:-LL_gBCuCIeSfTNtU2sj:b-82w7mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9e7aa23eabfe6ee75b7b1743dbddb4fc66779c/pkg/ccl/changefeedccl/table_history.go#L87)):*
> ```Go
> 
> // WaitForTS blocks until the given timestamp is greater or equal to the
> // high-water or error timestamp. In the latter case, the error is returned.
> ```

I think this is the other way around; it waits until the given timestamp is less than or equal to the high-water or error timestamp.
___
*[pkg/ccl/changefeedccl/table_history.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_fZRC8kjdEhqA37g4:-LL_fZRC8kjdEhqA37g5:bkz5ezh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9e7aa23eabfe6ee75b7b1743dbddb4fc66779c/pkg/ccl/changefeedccl/table_history.go#L168)):*
> ```Go
> 	}
> 
> 	m.mu.Lock()
> ```

I think you should move this above the validateErr check, and remove the Lock/Unlock inside of the validateErr check block.  This whole area works inside of the mutex.


<!-- Sent from Reviewable.io -->

2018-09-04 19:27 UTC, danhhz reviewed
@mrtracy RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-:-LLa2T47DxExoDSd_iUN:bbjkww6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/table_history.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_gBCuCIeSfTNtU2si:-LL_zHWa6AoFy5_9_tml:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9e7aa23eabfe6ee75b7b1743dbddb4fc66779c/pkg/ccl/changefeedccl/table_history.go#L87)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I think this is the other way around; it waits until the given timestamp is less than or equal to the high-water or error timestamp.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/table_history.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_fZRC8kjdEhqA37g4:-LLa-FgN7q9_wLf3eNuY:b-rlnrlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9e7aa23eabfe6ee75b7b1743dbddb4fc66779c/pkg/ccl/changefeedccl/table_history.go#L168)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I think you should move this above the validateErr check, and remove the Lock/Unlock inside of the validateErr check block.  This whole area works inside of the mutex.
</blockquote></details>

I was hoping this way would make it easier to reason about, but sounds like my intuition was wrong. I moved this whole thing into a new method, which I think is even better (one lock followed immediately by a defer at the very start of the new method)


<!-- Sent from Reviewable.io -->

2018-09-04 19:30 UTC, mrtracy approved these changes
Still LGTM, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-:-LLa33do8I1YRJZPTD67:bq48par)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/table_history.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LL_fZRC8kjdEhqA37g4:-LLa2rnlAlnc3RFjZEfl:b-u6ki1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f9e7aa23eabfe6ee75b7b1743dbddb4fc66779c/pkg/ccl/changefeedccl/table_history.go#L168)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was hoping this way would make it easier to reason about, but sounds like my intuition was wrong. I moved this whole thing into a new method, which I think is even better (one lock followed immediately by a defer at the very start of the new method)
</blockquote></details>

Yes, looks nicer.
___
*[pkg/ccl/changefeedccl/table_history.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LLa2yS10Djwvmp8Y3Wg:-LLa2yS10Djwvmp8Y3Wh:b5kjqau) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2a49837888c85c66957ebdfddb89e38c9af0bc1/pkg/ccl/changefeedccl/table_history.go#L47)):*
> ```Go
> // The `ValidateThroughTS` method allows a user to block until some given
> // timestamp is greater (or equal) to either the high-water or the error
> // timestamp. In the latter case, it returns the error.
> ```

Sorry, missed this. Same comment problem that you just fixed below.  This one is unexported, but now its inconsistent.


<!-- Sent from Reviewable.io -->

2018-09-04 20:30 UTC, danhhz reviewed
Thanks for the reviews!

bors r=mrtracy,vivekmenezes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-:-LLaGmJfCscWSmuzE228:bn39uxz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/table_history.go, line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29367#-LLa2yS10Djwvmp8Y3Wg:-LLaG2PHBiQ9KbLAbC0G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2a49837888c85c66957ebdfddb89e38c9af0bc1/pkg/ccl/changefeedccl/table_history.go#L47)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Sorry, missed this. Same comment problem that you just fixed below.  This one is unexported, but now its inconsistent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-04 21:01 UTC, merged