sql: fix a panic in TestSQLEncode
cockroachdb/cockroach pull request #29549
Opened 2018-09-04 19:18 UTC by arjunravinarayan

Fixes #29545.

This change involves additional test cases that are CC-by-4.0 licensed. Gated on @ben for merging to okay the way these test cases are imported.

2018-09-04 19:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/29549)
<!-- Reviewable:end -->

2018-09-04 19:25 UTC, jordanlewis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29549)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lex/encode_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-LLa16LQEzBLN2Yoodg-:-LLa16LQEzBLN2Yoodg0:b-2kbxdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ad2ef1626b83f7d7266436a53271f1f729742/pkg/sql/lex/encode_test.go#L90)):*
> ```Go
> 		"                                                                              |",
> 		"3.1.3  2 continuation bytes: \"��\"                                             |",
> 		"3.1.4  3 continuation bytes: \"���\"                                            |",
> ```

I hate to ask, but are these really testing what we want if we embed them in longer strings? Wouldn't we have to isolate all of the strings to make sure we're testing en/decoding the actual utf8 strings themselves? To make this a really good test I think we'd also have to make expected output... though I do understand this is a pain and we're just trying to catch egregious crash bugs right now. Maybe it's fine as-is. Curious what @knz thinks.


<!-- Sent from Reviewable.io -->

2018-09-05 15:11 UTC, arjunravinarayan commented
___
*[pkg/sql/lex/encode_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-LLa16LQEzBLN2Yoodg-:-LLeGy4d4to2YBCtLg6N:baygqpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ad2ef1626b83f7d7266436a53271f1f729742/pkg/sql/lex/encode_test.go#L90)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I hate to ask, but are these really testing what we want if we embed them in longer strings? Wouldn't we have to isolate all of the strings to make sure we're testing en/decoding the actual utf8 strings themselves? To make this a really good test I think we'd also have to make expected output... though I do understand this is a pain and we're just trying to catch egregious crash bugs right now. Maybe it's fine as-is. Curious what @knz thinks.
</blockquote></details>

These are the test files as-is, and I think there's some value to them. Yes, we do want end-of-string tests, and that's why I added that one-off known-to-previously-crash test case at the top.

We don't have a decoder, so I can't do a roundtrip test. However, I guess I could find a known-good UTF-8 encoder, run these inputs through them, and check that we match that output exactly.

The primary motivation of this PR is to fix a panic, shoring up the testing is incidental. Would you mind if I filed an issue and moved on?


<!-- Sent from Reviewable.io -->

2018-09-05 15:39 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29549)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lex/encode_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-LLa16LQEzBLN2Yoodg-:-LLeNhpk07RpF3qXfW6g:b-885qkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ad2ef1626b83f7d7266436a53271f1f729742/pkg/sql/lex/encode_test.go#L90)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

These are the test files as-is, and I think there's some value to them. Yes, we do want end-of-string tests, and that's why I added that one-off known-to-previously-crash test case at the top.

We don't have a decoder, so I can't do a roundtrip test. However, I guess I could find a known-good UTF-8 encoder, run these inputs through them, and check that we match that output exactly.

The primary motivation of this PR is to fix a panic, shoring up the testing is incidental. Would you mind if I filed an issue and moved on?
</blockquote></details>

Fair enough. I'd say don't bother filing the issue if you think this is fine as well - I just couldn't help mentioning the obvious :)


<!-- Sent from Reviewable.io -->

2018-09-05 15:40 UTC, jordanlewis approved these changes

2018-09-05 17:11 UTC, rjnn reviewed
TFTR @jordanlewis. I'm going to hold this PR until @bdarnell is back and OKs the license addition.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-:-LLehk598uUOodeeiHKb:bjqun2f)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-09-06 14:18 UTC, tschottdorf commented on pkg/sql/lex/encode_test.go
> +		// Regression test for #
missing issue number

2018-09-06 19:25 UTC, rjnn reviewed
I have removed the CC-by-4.0 test cases (and thus the license gating). That can wait for later. PTAL @jordanlewis. I now have a simple logic test that ensures that we error out correctly when we encounter invalid UTF-8 byte strings. This is tested only with DistSQL, as local SQL does not serialize and deserialize the string, it simply pretty prints out the escaped invalid UTF-8 as-is. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-:-LLkKv38B9z_gWmZIbZQ:b-3zy234)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lex/encode_test.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29549#-LLa0QSldHN1PUXXmScy-r2-39:-LLkLC049qiVMsqVAxtb:b-jrlzrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/186133b54c9a95f1dec25128e1012c982d67b823/pkg/sql/lex/encode_test.go#L39)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

missing issue number
</blockquote></details>

No longer relevant, I've decided not to add tests here. Thank you.


<!-- Sent from Reviewable.io -->

2018-09-06 19:47 UTC, jordanlewis approved these changes
LGTM thanks!

2018-09-06 19:48 UTC, arjunravinarayan commented
bors r=jordanlewis

2018-09-06 20:15 UTC, merged