opt: Eliminate Union All if one side has zero cardinality
cockroachdb/cockroach pull request #29644
Opened 2018-09-06 14:49 UTC by itsbilal

Adds a norm rule to opt to replace a Union All with a simpler
projection if one side cannot have any rows.

Fixes #29153

2018-09-06 14:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/29644)
<!-- Reviewable:end -->

2018-09-06 15:07 UTC, justinj reviewed
Looks great - cc @andy-kimball for his thoughts

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-:-LLjP9Nn9kEcBiiwvcFu:bp5tsqt)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 509 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjPNF4-Cj309nhCNoD:-LLjPNF4-Cj309nhCNoE:b8tg638) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/custom_funcs.go#L509)):*
> ```Go
> // ProjectColMapSide implements the side-agnostic logic from ProjectColMapLeft
> // and ProjectColMapRight.
> func (c *CustomFuncs) ProjectColMapSide(colMapID memo.PrivateID, fromList opt.ColList) memo.GroupID {
> ```

I think this function could be slightly more general/succinct if you made it take two `opt.ColList`s and then performed the mapping between those two, rather than taking the `SetOpColMap` as the first argument. This would also save an extra call to `LookupPrivate`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjNGD23-OwZNwfmvXk:-LLjNGD23-OwZNwfmvXl:bwjh311) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/custom_funcs.go#L513)):*
> ```Go
> 	colMap := c.mem.LookupPrivate(colMapID).(*memo.SetOpColMap)
> 
> 	for idx := 0; idx < len(fromList); idx += 1 {
> ```

nit: `i := range fromList`
___
*[pkg/sql/opt/norm/rules/select.opt, line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjNb2G0Df9brO6sB3w:-LLjNb2G0Df9brO6sB3x:bcyl8jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/rules/select.opt#L332)):*
> ```
> (ConstructEmptyValues (OutputCols $input))
> 
> # MergeUnionAllLeft replaces a union all with a right side having a
> ```

A rule named`Merge...` usually implies there's two operators that are being combined into one - this type of rule is more commonly named `Eliminate...`
___
*[pkg/sql/opt/norm/rules/select.opt, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjOoYYCZ55yXgxDz7l:-LLjOoYYCZ55yXgxDz7m:b-bbm7km) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/rules/select.opt#L341)):*
> ```
> )
> =>
> (Project
> ```

It's too bad we can't somehow get rid of this `Project` - it has the same problem as #28905 unfortunately.
___
*[pkg/sql/opt/norm/testdata/rules/select, line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjNqMwDfsjvMwoAdYe:-LLjNqMwDfsjvMwoAdYf:b-jmm174) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/testdata/rules/select#L1173)):*
> ```
> 
> # --------------------------------------------------
> # MergeUnionAllRight
> ```

Perhaps also add a test where they're both empty, not because we expect any particular behaviour, but so we have an example of such a case. Also some execbuilder/logic tests that exercise this logic would be good too to make sure that the column mapping is correct.


<!-- Sent from Reviewable.io -->

2018-09-06 16:52 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 509 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjPNF4-Cj309nhCNoD:-LLjS3Ru6nlAOeVU0AI9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/custom_funcs.go#L509)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this function could be slightly more general/succinct if you made it take two `opt.ColList`s and then performed the mapping between those two, rather than taking the `SetOpColMap` as the first argument. This would also save an extra call to `LookupPrivate`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/select.opt, line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjNb2G0Df9brO6sB3w:-LLjS-wx5ZjZy9E95hj9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/rules/select.opt#L332)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

A rule named`Merge...` usually implies there's two operators that are being combined into one - this type of rule is more commonly named `Eliminate...`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/select, line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjNqMwDfsjvMwoAdYe:-LLjn26ZBT20neViHCwV:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e77275a2cbce84b9250bbd87c21aa3300e244c9/pkg/sql/opt/norm/testdata/rules/select#L1173)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Perhaps also add a test where they're both empty, not because we expect any particular behaviour, but so we have an example of such a case. Also some execbuilder/logic tests that exercise this logic would be good too to make sure that the column mapping is correct.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-09-07 15:07 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-:-LLoZm-z33LHJuW_onVG:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-07 15:18 UTC, andy-kimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

2018-09-07 15:18 UTC, andy-kimball commented on pkg/sql/opt/norm/custom_funcs.go
> +func (c *CustomFuncs) ProjectColMapSide(toList opt.ColList, fromList opt.ColList) memo.GroupID {
No need to export this method, since it's a helper. I'd make it `projectColMapSide` and move it below the other 2 functions.

2018-09-07 15:52 UTC, rytaft requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/union, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLohiDv8uFkr4IKy3vt:-LLohiDw3OynbTFw-qtD:bijqaxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/exec/execbuilder/testdata/union#L73)):*
> ```
> # Check that UNION ALL columns are mapped correctly
> query I
> SELECT a FROM (SELECT a FROM abc UNION ALL SELECT k FROM uniontest)
> ```

`execbuilder` is usually reserved for `EXPLAIN` queries. Queries involving data should be included in the logic tests so we can test that the heuristic planner and the optimizer return the same result.

I'd either move these tests to logic tests, or change them to use `EXPLAIN`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLoihOI7JEoCihpwGXj:-LLoihOJ9bYytsrc3Kay:b92p6gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/norm/custom_funcs.go#L515)):*
> ```Go
> 		toCol := toList[idx]
> 
> 		pb.addSynthesized(c.f.ConstructVariable(c.f.InternColumnID(fromCol)), toCol)
> ```

I think these should be passthrough columns, not synthesized columns


<!-- Sent from Reviewable.io -->

2018-09-07 15:58 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLoihOI7JEoCihpwGXj:-LLoji4H8BiZFC8xEbDN:b-11rpya) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/norm/custom_funcs.go#L515)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think these should be passthrough columns, not synthesized columns
</blockquote></details>

I don't think they can be without renumbering the columns throughout the entire child tree, can they? Since the norm rule needs to preserve the column IDs output by this expression? I've thought a bit about how to make that work but couldn't think of a nice way (this is the same problem as why #28905 can't be a norm rule)


<!-- Sent from Reviewable.io -->

2018-09-07 16:02 UTC, rytaft commented
___
*[pkg/sql/opt/norm/custom_funcs.go, line 515 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLoihOI7JEoCihpwGXj:-LLol1Z_CDAJtoBjt7yW:bybfmrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/norm/custom_funcs.go#L515)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I don't think they can be without renumbering the columns throughout the entire child tree, can they? Since the norm rule needs to preserve the column IDs output by this expression? I've thought a bit about how to make that work but couldn't think of a nice way (this is the same problem as why #28905 can't be a norm rule)
</blockquote></details>

Ah good point - never mind


<!-- Sent from Reviewable.io -->

2018-09-07 16:02 UTC, rytaft approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644)* status: :shipit: complete! 2 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-09-07 20:06 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29644)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLjM-YDLivwR-3tnSOD-r2-509:-LLpd17T9CeOrcnJhuwu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/norm/custom_funcs.go#L509)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

No need to export this method, since it's a helper. I'd make it `projectColMapSide` and move it below the other 2 functions.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/union, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29644#-LLohiDv8uFkr4IKy3vt:-LLpd-juEN6yqewcnsxa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/875fa757a2a1723eb84ac0f959c9a1770b6cc95a/pkg/sql/opt/exec/execbuilder/testdata/union#L73)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

`execbuilder` is usually reserved for `EXPLAIN` queries. Queries involving data should be included in the logic tests so we can test that the heuristic planner and the optimizer return the same result.

I'd either move these tests to logic tests, or change them to use `EXPLAIN`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-07 20:39 UTC, itsbilal commented
bors r+

2018-09-07 20:41 UTC, itsbilal commented
bors r+

2018-09-07 20:48 UTC, itsbilal commented
bors r+

2018-09-07 20:48 UTC, benesch commented
bors delegate+

2018-09-07 20:49 UTC, itsbilal commented
bors r+

2018-09-07 22:10 UTC, merged