distsql: eagerly evaluate constant expressions
cockroachdb/cockroach pull request #30216
Opened 2018-09-13 20:33 UTC by solongordon

exprHelper now normalizes its expression upon initialization. This
causes constant subexpressions to be evaluated up front, rather than re-
evaluating them every time `eval` or `evalFilter` is called, and thus
avoids a hefty per-row cost for expensive expressions. For example, the
SELECT query in the example below now returns in ~100ms rather than
~10s.

```
CREATE TABLE t (x int[]);
INSERT INTO t SELECT array[x] FROM generate_series(1, 10000) AS x;
SELECT * FROM t WHERE x = (SELECT array_agg(generate_series(1,10000)));
```

This also uncovered a bug in the normalizer where `NOT IN ()` returned
false rather than true.

Fixes #30167

Release note: None

2018-09-13 20:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30216)
<!-- Reviewable:end -->

2018-09-13 20:36 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30216)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMJcrg9ENdQ_D5j6yly:-LMJcrg9ENdQ_D5j6ylz:b9y13d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/distsqlrun/expr.go#L86)):*
> ```Go
> 	// Normalize. This evaluates constant values so they don't need to be
> 	// repeatedly re-evaluated, for example in the case of filter application.
> 	typedExpr, err = evalCtx.NormalizeExpr(typedExpr)
> ```

Interested to hear thoughts on whether `NormalizeExpr` is a good fit here. Much of the normalization logic is unnecessary/redundant here. But it also felt like overkill to write a whole new `Visitor` which would duplicate much of the `NormalizeVisitor`'s logic.


<!-- Sent from Reviewable.io -->

2018-09-13 20:56 UTC, RaduBerinde commented
This is a planning aspect and doesn't belong in `distsqlrun`.. It should be done in the planner. See `distsqlplan.MakeExpression` - it is already doing a traversal to replace subqueries. It could also re-normalize when there are subqueries.

Note that @rytaft just merged #30134 which performs normalization when building plans; it should cover cases unrelated to subqueries.

2018-09-17 13:35 UTC, jordanlewis commented
Unfortunately, a case like in the linked issue isn't fixable by normalizing during planning, because of the lossy nature of the FmtParsable text encoding. The only way that I can see to prevent bad behavior without a larger overhaul to the serialization format (or case by case fixing expressions as they're deemed problematic) is normalizing once the expression is parsed.

2018-09-17 14:18 UTC, solongordon commented
Yup. And like I mentioned in my previous comment, I acknowledge that a lot of the normalization logic is superfluous here, but I'm doubtful it's enough of a performance hit to be worth factoring out all the constant eval parts into a new Visitor.

2018-09-17 14:28 UTC, jordanlewis requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30216)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMJcrg9ENdQ_D5j6yly:-LMbv9nE4DZfaTJqUoI0:b-26itsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/distsqlrun/expr.go#L86)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Interested to hear thoughts on whether `NormalizeExpr` is a good fit here. Much of the normalization logic is unnecessary/redundant here. But it also felt like overkill to write a whole new `Visitor` which would duplicate much of the `NormalizeVisitor`'s logic.
</blockquote></details>

Isn't there already a constant subexpression evaluation visitor somewhere that could be repurposed? Either way, I think I would prefer to see something that only does that part - if NormalizeVisitor ever gets extended, this part might get slower without anybody noticing.
___
*[pkg/sql/sem/tree/normalize.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMbvfu64zjj1Kn02YwC:-LMbvfu64zjj1Kn02YwD:b3icfzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/sem/tree/normalize.go#L474)):*
> ```Go
> 			if len(tupleCopy.D) == 0 {
> 				// NULL IN <empty-tuple> is false.
> 				if expr.Operator == In {
> ```

Was this a bug?


<!-- Sent from Reviewable.io -->

2018-09-17 14:33 UTC, RaduBerinde commented
I'm ok with this as a late fix, but please add a TODO explaining that this is a temporary fix until we fix the serialization issue, and leave the (or another) issue open to track that.

2018-09-17 14:47 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30216)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/expr.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMJcrg9ENdQ_D5j6yly:-LMbwnaX9j7KHLQYhS5C:b6365r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/distsqlrun/expr.go#L86)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Isn't there already a constant subexpression evaluation visitor somewhere that could be repurposed? Either way, I think I would prefer to see something that only does that part - if NormalizeVisitor ever gets extended, this part might get slower without anybody noticing.
</blockquote></details>

No, I wasn't able to find one. I wasn't sure it was worth it to write a new one but agree it would be preferable if it's reasonably straightforward. I'll take a stab.
___
*[pkg/sql/sem/tree/normalize.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMbvfu64zjj1Kn02YwC:-LMbzMKN--DK5jxxOuqK:b-mici6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/sem/tree/normalize.go#L474)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Was this a bug?
</blockquote></details>

Yup, I mentioned it in the commit msg. Surprisingly this wasn't exercised by any existing tests. Maybe `NOT IN ()` is usually simplified prior to normalization?


<!-- Sent from Reviewable.io -->

2018-09-18 13:46 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30216)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/tree/normalize.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-LMbvfu64zjj1Kn02YwC:-LMgvTUX85cDVaiIm9MA:b-b3copc) ([raw file](https://github.com/cockroachdb/cockroach/blob/333770daefc13a9219d125014cddb5f5693ea708/pkg/sql/sem/tree/normalize.go#L474)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yup, I mentioned it in the commit msg. Surprisingly this wasn't exercised by any existing tests. Maybe `NOT IN ()` is usually simplified prior to normalization?
</blockquote></details>

Pulled this out into #30319.


<!-- Sent from Reviewable.io -->

2018-09-18 14:56 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30216#-:-LMhAirB8q2q2cUfUQTk:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-18 15:01 UTC, solongordon commented
bors r+

2018-09-18 15:24 UTC, merged

2018-09-21 14:55 UTC, knz commented
this may want a backport?