opt: add SimplifyZeroCardinalityGroup
cockroachdb/cockroach pull request #30312
Opened 2018-09-17 18:42 UTC by justinj

This commit adds SimplifyZeroCardinalityGroup, which is a new manual
rule which replaces a group which has been proven to have zero rows with
an empty ValuesOp.

This rule is different from most other rules because it depends on the
logical properties of the group being constructed, so it gets checked in
onConstruct rather than normal rule checking. This means that we can
sometimes create groups which end up getting immediately discarded, but
since this is something of an edge case I think that's not a huge deal.

This replaces DetectSelectContradiction.

There's an annoying edge case with negative limits - I'm not super fond
of the solution I ended up at, but I couldn't think of anything
substantially better given the restrictions. Open to suggestions here.

Release note: None

2018-09-17 18:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30312)
<!-- Reviewable:end -->

2018-09-17 20:15 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/factory.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMd9QZV8RM30aoUoAvn:-LMd9QZV8RM30aoUoAvo:b-2tdk4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b9eac770e186eacf0e54b992d818e1988b036a6/pkg/sql/opt/norm/factory.go#L183)):*
> ```Go
> 	if ev.IsRelational() && e.Operator() != opt.ValuesOp && e.Operator() != opt.LimitOp {
> 		if ev.Logical().Relational.Cardinality.IsZero() {
> 			if f.matchedRule == nil || f.matchedRule(opt.SimplifyZeroCardinalityGroup) {
> ```

Perhaps we should not do this for ops which `CanHaveSideEffects`, in which case we could mark a Limit with negative (or possibly negative) limit as having side effects?


<!-- Sent from Reviewable.io -->

2018-09-17 21:42 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/factory.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMd9QZV8RM30aoUoAvn:-LMdTk1i3cke7MVveT8H:b-687ymm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b9eac770e186eacf0e54b992d818e1988b036a6/pkg/sql/opt/norm/factory.go#L183)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Perhaps we should not do this for ops which `CanHaveSideEffects`, in which case we could mark a Limit with negative (or possibly negative) limit as having side effects?
</blockquote></details>

That's a lovely fix! Done.


<!-- Sent from Reviewable.io -->

2018-09-18 15:26 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

@andy-kimball should take a look to make sure we're not misusing `CanHaveSideEffects`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMhHU-X7TB4IzvyvUA1:b-vcrqon)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhH3O49pOIsEt0vcjl:-LMhH3O49pOIsEt0vcjm:ba5kqen) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/memo/logical_props_builder.go#L881)):*
> ```Go
> 	// ------------
> 	if constLimit < 0 {
> 		relational.CanHaveSideEffects = true
> ```

Should this be set if limit.Operator() is not opt.ConstOp? If it's some expression (e.g. subquery) which can return -1, it would generate an error.


<!-- Sent from Reviewable.io -->

2018-09-18 15:41 UTC, andy-kimball reviewed
This seems right to me. In fact, it's a bug that we don't set it now, since we have to set it when a runtime error is possible. It's annoying that Postgres made this a runtime error rather than just silently using `LIMIT=0`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMhKf8c4ayhZNFYAdoY:b-uko5od)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 880 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhKNdGE21oXeve5Sbz:-LMhKNdGE21oXeve5Sc-:beh11a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/memo/logical_props_builder.go#L880)):*
> ```Go
> 	// Side Effects
> 	// ------------
> 	if constLimit < 0 {
> ```

Wouldn't this be true if the limit is not a constant, since it might evaluate to negative? I think we need to set `CanHaveSideEffects` unless `constLimit >= 0` (and make sure to add a test case or two).
___
*[pkg/sql/opt/norm/testdata/rules/zero_cardinality, line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhJttCEOrlqMVnmIo2:-LMhJttCEOrlqMVnmIo3:btrufmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/norm/testdata/rules/zero_cardinality#L16)):*
> ```
> # SimplifyZeroCardinalityGroup
> # --------------------------------------------------
> ```

I'd add a negative case that ensures folding doesn't occur in presence of side effects, probably using a different side effect than `LIMIT -1`, since you're testing that elsewhere.


<!-- Sent from Reviewable.io -->

2018-09-18 15:47 UTC, rytaft commented
I think with this change you should be able to remove all of the instances of this code in the statistics_builder:
```
	s := &relProps.Stats
	if zeroCardinality := s.Init(relProps); zeroCardinality {
		// Short cut if cardinality is 0.
		return
	}
```





<!-- Sent from Reviewable.io -->

2018-09-18 16:14 UTC, RaduBerinde commented
> I think with this change you should be able to remove all of the instances [..]

The rule is applied after rules and stats are calculated, so this code would still run no?

2018-09-18 16:44 UTC, andy-kimball reviewed
Is the zeroCardinality stats code there for correctness (i.e. to prevent crashes that would otherwise occur), or is it there to improve the estimates? If the latter, we should still get rid of it, because it's extra complication (including extra testing). Once Justin's rule rewrites the tree, the only place we need it is for `Values`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMhYygA3OtiM6CYFVNs:b-x5mtk4)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-09-18 17:05 UTC, justinj reviewed
Made some changes - there's the expected sad proliferation of `side-effects` having expressions in the tests. I've left the stats code there until there's a consensus on if it should stay around or not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMhb6dQ-e-AMSf9J6So:b-aojqmk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 880 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhKNdGE21oXeve5Sbz:-LMhaUp56vkwE3naU_df:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/memo/logical_props_builder.go#L880)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Wouldn't this be true if the limit is not a constant, since it might evaluate to negative? I think we need to set `CanHaveSideEffects` unless `constLimit >= 0` (and make sure to add a test case or two).
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 881 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhH3O49pOIsEt0vcjl:-LMhIct0CTaJzgXKaqnj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/memo/logical_props_builder.go#L881)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be set if limit.Operator() is not opt.ConstOp? If it's some expression (e.g. subquery) which can return -1, it would generate an error.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/join, line 1626 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhd-xx7xjvcY1CD1Wx:-LMhd-xx7xjvcY1CD1Wy:brp9jat) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/join#L1626)):*
> ```
> # --------------------------------------------------
> # TODO(justin): figure out if there's a good way to make this still apply.
> opt disable=SimplifyZeroCardinalityGroup expect=EliminateAntiJoin
> ```

@andy-kimball do you have any idea what can be done here? once the new rule applies the subquery is no longer correlated and doesn't get hoisted, so `EliminateAntiJoin` doesn't run (can push this to a future PR).
___
*[pkg/sql/opt/norm/testdata/rules/zero_cardinality, line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMhJttCEOrlqMVnmIo2:-LMhaYxrCxHmwGbr-B8-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f37ccac11625cd72d552a71ca3d77c10d7e8240/pkg/sql/opt/norm/testdata/rules/zero_cardinality#L16)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd add a negative case that ensures folding doesn't occur in presence of side effects, probably using a different side effect than `LIMIT -1`, since you're testing that elsewhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-18 19:53 UTC, rytaft reviewed
> Is the zeroCardinality stats code there for correctness (i.e. to prevent crashes that would otherwise occur), or is it there to improve the estimates?

It's for both -- there are some panics later in the code if we encounter a filter with a contradiction. For example:
```
	if c.IsContradiction() {
		panic("applyConstraint called on constraint with contradiction")
	}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMiE9_U-5kRH4neIYlC:bqomffg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-18 20:13 UTC, rytaft requested changes
> Reviewed 10 of 14 files at r1, 2 of 4 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiFNAV8VlabOgjOOgi:-LMiFNAV8VlabOgjOOgj:bq3qqka) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/memo/testdata/stats/join#L101)):*
> ```
> 
> norm
> SELECT * FROM a JOIN b ON false
> ```

to check that the stats code still works, maybe it would be best to change this to `build` rather than `norm`
___
*[pkg/sql/opt/norm/testdata/rules/bool, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiGoxi5aZbPQDYFbcR:-LMiGoxi5aZbPQDYFbcS:bspg0zu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/bool#L265)):*
> ```
> 
> opt
> SELECT * FROM a INNER JOIN b ON NULL
> ```

Is this still testing `SimplifyFilters`?
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiH5HI4Rp13CGgEjcV:-LMiH5HI4Rp13CGgEjcW:b-yw4pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/limit#L74)):*
> ```
>  └── const: 5100000000 [type=int]
> 
> # Don't eliminate in case of zero or negative limit.
> ```

update comment for 0 limit
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiH9Cg4DMQwOqBYL2b:-LMiH9Cg4DMQwOqBYL2c:bwv1xd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/limit#L186)):*
> ```
>       └── f + 1.1 [type=float, outer=(3)]
> 
> # Don't push zero limit into Scan.
> ```

update comment or remove test
___
*[pkg/sql/opt/norm/testdata/rules/select, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiHMj83fYMrapoRaPq:-LMiHMj83fYMrapoRaPr:bd0zvy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/select#L62)):*
> ```
>       └── s = 'foo' [type=bool, outer=(4), constraints=(/4: [/'foo' - /'foo']; tight)]
> 
> opt
> ```

add `expect=MergeSelects` here and below (unless these tests should be in a different section?)
___
*[pkg/sql/opt/norm/testdata/rules/zero_cardinality, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiIMELBNRC25E258FC:-LMiIMELBNRC25E258FD:b-t142xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/zero_cardinality#L14)):*
> ```
> 
> # --------------------------------------------------
> # SimplifyZeroCardinalityGroup
> ```

Seems like most of these tests are for SELECT, which was already handled by the old rule. Can you add a few tests for other operators with 0 cardinality (e.g., join)?


<!-- Sent from Reviewable.io -->

2018-09-19 16:22 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiFNAV8VlabOgjOOgi:-LMm_8K9DUMuHYiTA7uy:b-mqtp6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/memo/testdata/stats/join#L101)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

to check that the stats code still works, maybe it would be best to change this to `build` rather than `norm`
</blockquote></details>

I made this change but the stats info looks very wrong now. It looks like the stat code for an inner join doesn't interpret a `false` filter? Not sure if that's a problem in reality, though, since we'll be normalizing then?
___
*[pkg/sql/opt/norm/testdata/rules/bool, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiGoxi5aZbPQDYFbcR:-LMmaR9n7AmMSkKDCAVt:b-574t7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/bool#L265)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this still testing `SimplifyFilters`?
</blockquote></details>

yup - added some expectations
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 74 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiH5HI4Rp13CGgEjcV:-LMmabUs7OBE73c28FRz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/limit#L74)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update comment for 0 limit
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/limit, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiH9Cg4DMQwOqBYL2b:-LMmaqcu8AWhdvAAKROc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/limit#L186)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

update comment or remove test
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/select, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiHMj83fYMrapoRaPq:-LMmb7ERCqyXooK8AVwC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/select#L62)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

add `expect=MergeSelects` here and below (unless these tests should be in a different section?)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/zero_cardinality, line 14 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiIMELBNRC25E258FC:-LMmcHCP8tteO3kK-J8A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/norm/testdata/rules/zero_cardinality#L14)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like most of these tests are for SELECT, which was already handled by the old rule. Can you add a few tests for other operators with 0 cardinality (e.g., join)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-19 17:08 UTC, RaduBerinde commented
___
*[pkg/sql/opt/memo/testdata/stats/join, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiFNAV8VlabOgjOOgi:-LMmnJyyACeuNvBet_Jl:b-pt6cjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/memo/testdata/stats/join#L101)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I made this change but the stats info looks very wrong now. It looks like the stat code for an inner join doesn't interpret a `false` filter? Not sure if that's a problem in reality, though, since we'll be normalizing then?
</blockquote></details>

It's because it's `Filters - > False` instead of just `False`


<!-- Sent from Reviewable.io -->

2018-09-19 17:41 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-:-LMmuot13jE7ECrHPEy2:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMiFNAV8VlabOgjOOgi:-LMmu8tjARMHHygJsCuL:bc2ftz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1815c8e0d1d48990ac72ff1b94d3faf791a80c8c/pkg/sql/opt/memo/testdata/stats/join#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's because it's `Filters - > False` instead of just `False`
</blockquote></details>

Ah yea Radu is right. I don't think we should go out of our way to make stats do the right thing here, so maybe it's best to just change this test back to `norm`.
___
*[pkg/sql/opt/norm/testdata/rules/zero_cardinality, line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30312#-LMmufE53kYPOHM_7Qya:-LMmufE53kYPOHM_7Qyb:b-k6ezhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/58113464982ddb52f1b006da3f74dcb936a70116/pkg/sql/opt/norm/testdata/rules/zero_cardinality#L54)):*
> ```
> 
> opt expect=SimplifyZeroCardinalityGroup
> SELECT * FROM b INNER JOIN b b2 ON False
> ```

duplicate test


<!-- Sent from Reviewable.io -->

2018-09-20 16:36 UTC, justinj commented
TFTRs!

bors r+

2018-09-20 16:49 UTC, merged