tscache: add Metrics for read/write latency
cockroachdb/cockroach pull request #30383
Opened 2018-09-18 19:18 UTC by m-schneider

Release note: None

2018-09-18 19:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30383)
<!-- Reviewable:end -->

2018-09-19 14:45 UTC, nvb requested changes
It's not clear to me that we'll want to keep these metrics after the investigation, but thanks for putting this together! Let's see how it goes and whether you think the metrics are useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-:-LMmH55J-40NM2q-PCjL:bbzskml)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/tscache/metrics.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHKLH6Bq1RmPNTgTz:-LMmHKLH6Bq1RmPNTgU-:bmvhxpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L35)):*
> ```Go
> 	Pages         *metric.Gauge
> 	PageRotations *metric.Counter
> 	Latency       *metric.Histogram
> ```

I think it will be valuable to have separate a latency histogram for lookups (`getMax`) and insertion (`Add`). We expect them to have different performance characteristics.
___
*[pkg/storage/tscache/metrics.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHCji-NTaNX9OcsbU:-LMmHCji-NTaNX9OcsbV:bvks2cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L61)):*
> ```Go
> 		Name:        "tscache.skl.read.latency",
> 		Help:        "Latency reading from the read timestamp cache",
> 		Measurement: "Page Rotations",
> ```

We'll need a different measurement name here.
___
*[pkg/storage/tscache/metrics.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHJ_e1kyL0hVgikir:-LMmHJ_e1kyL0hVgikis:b-1kzc9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L79)):*
> ```Go
> 		Name:        "tscache.skl.write.latency",
> 		Help:        "Latency writing to timestamp cache",
> 		Measurement: "Page Rotations",
> ```

And here.


<!-- Sent from Reviewable.io -->

2018-09-19 15:22 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30383)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/tscache/metrics.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHKLH6Bq1RmPNTgTz:-LMmQ0l9-7x1plzl40p_:biaq1fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think it will be valuable to have separate a latency histogram for lookups (`getMax`) and insertion (`Add`). We expect them to have different performance characteristics.
</blockquote></details>

I did add separate histograms, one for read and the other for writes.
___
*[pkg/storage/tscache/metrics.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHCji-NTaNX9OcsbU:-LMmPTJP3sDWxyIgiE8V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L61)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We'll need a different measurement name here.
</blockquote></details>

Done.
___
*[pkg/storage/tscache/metrics.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHJ_e1kyL0hVgikir:-LMmPTrr7btmB2nSPknm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L79)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-19 15:34 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30383)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/tscache/metrics.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30383#-LMmHKLH6Bq1RmPNTgTz:-LMmSnydEt9WJpCAGMbA:bwbklxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/67078a5c9346ed23526b0d8b3ac77bc127b6a2a4/pkg/storage/tscache/metrics.go#L35)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I did add separate histograms, one for read and the other for writes.
</blockquote></details>

Those are for the read and write components of the cache (the tscache actually contains two `intervalSkl`s). We should add separate histograms for the two operations we perform on each as well.


<!-- Sent from Reviewable.io -->

2019-02-19 20:13 UTC, closed without merging