rfc: Cascading Zone Configs
cockroachdb/cockroach pull request #30426
Opened 2018-09-19 19:04 UTC by ridwanmsharif

Adds an RFC to discuss proposals and design for cascading zone configs.
Discusses changes to the `ZoneConfig` structure, why it is needed, the
different ways we could change it and designs what the change  should
look like

Release note: None

2018-09-19 19:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30426)
<!-- Reviewable:end -->

2018-09-20 14:58 UTC, petermattis reviewed
I've only skimmed this so far, but it looks directionally good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-:-LMrUMSACz_QJCOAxFGJ:bnoj7nd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LMrU0Dw9cBzOeQm6TdY:-LMrU0DxBzS-FeQ1A9lZ:bnjmmyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc768a3f8741a7d945bfe85af98fe3bcafdc8537/docs/RFCS/20180919_cascading_zone_configs.md#L91)):*
> ```Markdown
> by the Zone hierarchy above until they find a config with the field explicitly set.
> 
> After [adding caching], we must ensure the Zone configs are fully set before cached.
> ```

Didn't Spencer's caching PR just land? You're thinking of caching the fully resolved zone config, so its probably worth calling out that the worst case chain of inheritance won't be a performance concern.


<!-- Sent from Reviewable.io -->

2018-09-24 15:31 UTC, benesch reviewed
Looking really good!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-:-LNBC7hYBRIAaZF_9kzk:b-b00xdb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LMrU0Dw9cBzOeQm6TdY:-LNBAkU3DHWzYqkWtDu_:b-8ipqwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc768a3f8741a7d945bfe85af98fe3bcafdc8537/docs/RFCS/20180919_cascading_zone_configs.md#L91)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Didn't Spencer's caching PR just land? You're thinking of caching the fully resolved zone config, so its probably worth calling out that the worst case chain of inheritance won't be a performance concern.
</blockquote></details>

I believe Ridwan's plan, to start, is to cache fully resolved database and table zone configs, but partial index/partition zone configs. So there's still a bit of a perf hit for subzones.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNB3eVy62QeUCOyHOkt:-LNB3eVy62QeUCOyHOku:bwgmryv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L22)):*
> ```Markdown
> zone config by default and so also has a replication factor of `3`. Now the
> user updates the replication factor of the database to `5` but this change
> does not apply to the table as the change doesn't cascade down.
> ```

I think you're missing a step here. The user needs to install a zone config for the table that sets some field other than num_replicas. If there's no zone config for t, then the update to the default num_replicas will propagate.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNB5ABcC2jK-OcVtz8v:-LNB5ABcC2jK-OcVtz8w:b-oe3kts) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L81)):*
> ```Markdown
> 
> Unless explicitly set, the fields in the zone config for each zone/subzone would inherit
> the value from its parent recursively. The `.default` fields are always explicitly set.
> ```

It's worth being aware that there are actually two defaults. The first is installed into `system.zones` when the cluster is bootstrapped—i.e., the moment the cluster comes into existence. The second is in-memory in the binary itself. If the default entry in `system.zones` is deleted, then the in-memory default is used instead. Ending up in this state is difficult—you have to manually run a `DELETE FROM system.zones`—but it's been seen in the wild. The new cascading should continue to do something sensible if the default in `system.zones` is missing or incomplete.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNBBpEcCGHpEX74qCKk:b-xw15uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
> ```Markdown
> This change is acceptable (maybe shouldn't be?) as the inherited replication factor is 5.
> However, now it must become illegal for the replication factor of the database to be set to
> less than 5 (As that change would propagate to the table making its zone config invalid)
> ```

I think this is one of the biggest questions in this RFC. Do we want to validate a parent zone against all of its children, or do we want to live with the fact that it's possible to install an invalid zone config? I'm leaning towards the latter, but I'm curious what other folks think.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBFvY9V1LgvKKOm9S:-LNBBFvY9V1LgvKKOm9T:b-jizyv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L145)):*
> ```Markdown
> ## Additional Considerations
> 
> If a table is a `SubzonePlaceholder`, all of it's fields must be unset except for `NumReplicas`
> ```

nit: "its"
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBByKp25WmS0i-MJ4y:-LNBByKp25WmS0i-MJ4z:b-pcv9nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L158)):*
> ```Markdown
> What is the performance penalty of making the `ZoneConfig` fields nullable?
> The fields become pointers, but how much does the extra heap allocations affect performance?
> This needs to be measured.
> ```

Now that we have caching, I doubt it'll be noticeable.


<!-- Sent from Reviewable.io -->

2018-09-25 18:32 UTC, a-robinson requested changes
Nice writeup, @ridwanmsharif!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-:-LNH-FeW7exIdqUmc4Jq:b-x8jr7s)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNB3eVy62QeUCOyHOkt:-LNGsNwZAXeZr_T0Itlz:b4hd517) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L22)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you're missing a step here. The user needs to install a zone config for the table that sets some field other than num_replicas. If there's no zone config for t, then the update to the default num_replicas will propagate.
</blockquote></details>

Right, the copying of zone config from parent to child happens when the child's zone config is modified, not when the child itself (i.e. the table) is created.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNGxLrpABMIbXxZuHrD:b-o93vbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think this is one of the biggest questions in this RFC. Do we want to validate a parent zone against all of its children, or do we want to live with the fact that it's possible to install an invalid zone config? I'm leaning towards the latter, but I'm curious what other folks think.
</blockquote></details>

I disagree, I don't think we should live with that fact. Zone config changes are infrequent and important enough that we should have guard rails of some sort to prevent potentially catastrophic mistakes. Validating zone config changes against all children sounds pretty annoying to implement, but I think would be worth it.

Or alternatively, as @ridwanmsharif suggests for this case it'd be possible to prevent such broken configs by not allowing per-replica constraints without also explicitly setting the number of replicas in the same zone. If it's possible to avoid all such mistakes in that way, using localized requirements, I think that would be acceptable to most users. And as far as I can tell, the only real dependencies between different fields in the config are (1) this and (2) `RangeMinBytes` must be less than `RangeMaxBytes`. Forcing users to set both of those in tandem seems more annoying than for `NumReplicas` and per-replica constraints, but it seems better than the brokenness that accidentally having `RangeMinBytes >= `RangeMaxBytes` could cause.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNGz8BP8pi9ddqj7X94:b-n9749g) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
> ```Markdown
> # Drawbacks
> 
> # Unresolved Questions
> ```

I think this RFC is also missing a story for how the user can unset a field in a zone such that it starts being inherited from its parent again.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBByKp25WmS0i-MJ4y:-LNGyz4BEqvz1SvZD-Og:b-k29rex) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L158)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Now that we have caching, I doubt it'll be noticeable.
</blockquote></details>

Yeah, with caching in place I'd be pretty curious about this as well. Zone configs are almost never changed in real clusters. Although being more explicit about it with booleans indicating which fields were set by the user has a nice clarity to it that could prevent future coding mistakes.


<!-- Sent from Reviewable.io -->

2018-09-26 17:22 UTC, ridwanmsharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LMrU0Dw9cBzOeQm6TdY:-LNLo5UoC8Nix_ya5aV-:b-v0cmdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc768a3f8741a7d945bfe85af98fe3bcafdc8537/docs/RFCS/20180919_cascading_zone_configs.md#L91)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I believe Ridwan's plan, to start, is to cache fully resolved database and table zone configs, but partial index/partition zone configs. So there's still a bit of a perf hit for subzones.
</blockquote></details>

Yes, currently there's still going to be a lookup for `subzone`s inside a cached table zone. We could also cache the `subzone`s as mentioned later in the RFC.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNB3eVy62QeUCOyHOkt:-LNLnpF6DFmAbKY_F1q0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L22)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Right, the copying of zone config from parent to child happens when the child's zone config is modified, not when the child itself (i.e. the table) is created.
</blockquote></details>

Done.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNLorh644YTzY_Sb1yr:b-q8j3gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I disagree, I don't think we should live with that fact. Zone config changes are infrequent and important enough that we should have guard rails of some sort to prevent potentially catastrophic mistakes. Validating zone config changes against all children sounds pretty annoying to implement, but I think would be worth it.

Or alternatively, as @ridwanmsharif suggests for this case it'd be possible to prevent such broken configs by not allowing per-replica constraints without also explicitly setting the number of replicas in the same zone. If it's possible to avoid all such mistakes in that way, using localized requirements, I think that would be acceptable to most users. And as far as I can tell, the only real dependencies between different fields in the config are (1) this and (2) `RangeMinBytes` must be less than `RangeMaxBytes`. Forcing users to set both of those in tandem seems more annoying than for `NumReplicas` and per-replica constraints, but it seems better than the brokenness that accidentally having `RangeMinBytes >= `RangeMaxBytes` could cause.
</blockquote></details>

I don't think for something as infrequent as zone config changes, having invalid ones being installed is the best approach either. Validation is something we should do if we're not too worried about the time penalty validating every child recursively would result in. The _hacky_ solution of requiring `NumReplicas` when a `constraint` is set and similarly for `RangeMinBytes` and `RangeMaxBytes`, is one I'm fine with for now, that is if the validating children option is one we're not going to try.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNLqhsNEx5HcQMaLosA:barxgr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I think this RFC is also missing a story for how the user can unset a field in a zone such that it starts being inherited from its parent again.
</blockquote></details>

Done. What do think the sytax on the users end for unsetting a value should look like @a-robinson?


<!-- Sent from Reviewable.io -->

2018-09-27 17:14 UTC, a-robinson requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNQyBUk5dZNULyrR1Bw:b-42rr51) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
If you want to try implementing the validation of children, I won't stop you :) It's strictly better behavior from a user's perspective assuming its error messages are understandable. Just be aware it'll take significantly more time and effort to get right.

> The hacky solution of requiring `NumReplicas` when a `constraint` is set

To clarify, they'd only have to go hand-in-hand if the constraint is what we've been calling a ["per-replica" constraint](https://www.cockroachlabs.com/docs/v2.0/configure-replication-zones.html#per-replica-constraints-to-specific-datacenters-new-in-v2-0), meaning that relies on the number of replicas in the zone's ranges. If the constraint doesn't specify different predicates for different numbers of replicas (e.g. if I just set the constraint to `[-continent=europe]`) then we wouldn't have to require `NumReplicas` to also be explicitly set.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNQzUsq9u_2RZDCZmKe:bghsagi) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done. What do think the sytax on the users end for unsetting a value should look like @a-robinson?
</blockquote></details>

@benesch likely has better ideas than me here.

It may require new syntax. in SQL, I think we'd be able to interpret someone running something like `ALTER ... CONFIGURE ZONE USING  range_min_bytes=NULL;` as unsetting `range_min_bytes`, but we couldn't do the same in the CLI `cockroach zone set` command because AFAIK we can't easily differentiate between null and just not set when parsing yaml. A `cockroach zone unset` command would be a reasonable substitute.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNQxiYG-30oPntTKOor:-LNQxiYG-30oPntTKOos:bh14o1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bba995dbbc1f1bf52d5643e854da5139743e5c8b/docs/RFCS/20180919_cascading_zone_configs.md#L5)):*
> ```Markdown
> - Start Date: 2018-09-19
> - Authors: Ridwan Sharif
> - RFC PR: [#30611] - Prototype PR
> ```

This is usually meant to point to the PR in which the RFC was discussed, i.e. this one (#30426), in case anyone wants to look up the discussion that happened around the design decisions.


<!-- Sent from Reviewable.io -->

2018-09-27 17:20 UTC, a-robinson requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNR1dmq4I4Nbu2NiIrF:b-ewn3nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

@benesch likely has better ideas than me here.

It may require new syntax. in SQL, I think we'd be able to interpret someone running something like `ALTER ... CONFIGURE ZONE USING  range_min_bytes=NULL;` as unsetting `range_min_bytes`, but we couldn't do the same in the CLI `cockroach zone set` command because AFAIK we can't easily differentiate between null and just not set when parsing yaml. A `cockroach zone unset` command would be a reasonable substitute.
</blockquote></details>

Actually, I'm full of shit. Our yaml parser (gopkg.in/yaml.v2) does distinguish unset from null, by overwriting existing data if null is specified or leaving it alone if the field isn't specified. So we could potentially rely on null values to wipe fields, as long as we add some logic to handle that in our parsing code.


<!-- Sent from Reviewable.io -->

2018-09-27 17:24 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNR2W4D7k8Hk3nC9rsF:bfynyia) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Actually, I'm full of shit. Our yaml parser (gopkg.in/yaml.v2) does distinguish unset from null, by overwriting existing data if null is specified or leaving it alone if the field isn't specified. So we could potentially rely on null values to wipe fields, as long as we add some logic to handle that in our parsing code.
</blockquote></details>

I am ok with using yaml nulls for this purpose, but I'd like to point out that SQL has another idiomatic way to do this, already exemplified in other ALTER statements (e.g. to remove constraints on columns): DROP

ALTER ... CONFIGURE ZONE DROP range_min_bytes


<!-- Sent from Reviewable.io -->

2018-10-01 14:13 UTC, benesch reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNR6h0R-T-fxcf0NGa_:bmwx4df) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
> If you want to try implementing the validation of children, I won't stop you :) It's strictly better behavior from a user's perspective assuming its error messages are understandable. Just be aware it'll take significantly more time and effort to get right.

If you have 1k tables, that's potentially tens of thousands of zone configs. That's going to make changing the default zone config quite painful. I know we don't have many clusters of that scale today, but I think it'd be a shame to introduce that bottleneck. @bdarnell do you have thoughts?
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNR6U8T9a0ODEvXoQFk:b-393s8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am ok with using yaml nulls for this purpose, but I'd like to point out that SQL has another idiomatic way to do this, already exemplified in other ALTER statements (e.g. to remove constraints on columns): DROP

ALTER ... CONFIGURE ZONE DROP range_min_bytes


</blockquote></details>

Yeah, the `cockroach zone` command is deprecated in v2.1 so I'm hopeful we can remove it entirely in v2.2. Then we don't need to worry about YAML at all. I like your suggested SQL a lot, Raphael.


<!-- Sent from Reviewable.io -->

2018-10-01 14:28 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNk-fwI8iYPL9sN-MpY:bh27j5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

> If you want to try implementing the validation of children, I won't stop you :) It's strictly better behavior from a user's perspective assuming its error messages are understandable. Just be aware it'll take significantly more time and effort to get right.

If you have 1k tables, that's potentially tens of thousands of zone configs. That's going to make changing the default zone config quite painful. I know we don't have many clusters of that scale today, but I think it'd be a shame to introduce that bottleneck. @bdarnell do you have thoughts?
</blockquote></details>

It doesn't bother me too much if changing the default zone config has costs proportional to the number of zone configs in the system, although it would be best if that could be avoided. I agree that the best thing to do here is to treat the number of replicas and the constraints as a unit. (This is how zone configs originally worked: there wasn't an independent num_replicas setting, you would ask for three replicas by setting something like `constraints: [[], [], []]`. We added the `num_replicas` setting because it's much easier for the user to understand, although maybe we should decouple the user-facing config format from the underlying representation). 


<!-- Sent from Reviewable.io -->

2018-10-01 21:27 UTC, ridwanmsharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNlW6Yw14eRGutsrxrx:b-jc6q29) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It doesn't bother me too much if changing the default zone config has costs proportional to the number of zone configs in the system, although it would be best if that could be avoided. I agree that the best thing to do here is to treat the number of replicas and the constraints as a unit. (This is how zone configs originally worked: there wasn't an independent num_replicas setting, you would ask for three replicas by setting something like `constraints: [[], [], []]`. We added the `num_replicas` setting because it's much easier for the user to understand, although maybe we should decouple the user-facing config format from the underlying representation). 
</blockquote></details>

We're in agreement then. Treating constraints and replication factor as a unit, and range min and max bytes as another, is an acceptable way to deal with this problem.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 5 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNQxiYG-30oPntTKOor:-LNlW2m7Dg_aEL4SVH3e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bba995dbbc1f1bf52d5643e854da5139743e5c8b/docs/RFCS/20180919_cascading_zone_configs.md#L5)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

This is usually meant to point to the PR in which the RFC was discussed, i.e. this one (#30426), in case anyone wants to look up the discussion that happened around the design decisions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-02 15:59 UTC, a-robinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-:-LNpVPsb58dib6LuY7i9:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNH-2gR78GIfghTiZeg:-LNpV9dX9XfcSw3fg2wq:bnbobhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L155)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, the `cockroach zone` command is deprecated in v2.1 so I'm hopeful we can remove it entirely in v2.2. Then we don't need to worry about YAML at all. I like your suggested SQL a lot, Raphael.
</blockquote></details>

SGTM. The SQL command still has a version that accepts YAML, but that version doesn't have to support unsetting a field.


<!-- Sent from Reviewable.io -->

2018-10-03 10:47 UTC, knz approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30426)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNB5ABcC2jK-OcVtz8v:-LNtX2_WECeVkGMD0Kse:b31qvp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L81)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's worth being aware that there are actually two defaults. The first is installed into `system.zones` when the cluster is bootstrapped—i.e., the moment the cluster comes into existence. The second is in-memory in the binary itself. If the default entry in `system.zones` is deleted, then the in-memory default is used instead. Ending up in this state is difficult—you have to manually run a `DELETE FROM system.zones`—but it's been seen in the wild. The new cascading should continue to do something sensible if the default in `system.zones` is missing or incomplete.
</blockquote></details>

I concur, this needs to be addressed. it's not even "difficult": it happens in tests! I had changed this inadvertently (to ignore the root case) and CI was not happy.
___
*[docs/RFCS/20180919_cascading_zone_configs.md, line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30426#-LNBBpEcCGHpEX74qCKj:-LNtXQdX9mrUtgV7rMZc:bukqmdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/78dde6342de049a1be2609056f4786c905f825c1/docs/RFCS/20180919_cascading_zone_configs.md#L132)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

We're in agreement then. Treating constraints and replication factor as a unit, and range min and max bytes as another, is an acceptable way to deal with this problem.
</blockquote></details>

Maybe add a note in the RFC with a summary of the discussion and the outcome.


<!-- Sent from Reviewable.io -->

2018-10-04 04:15 UTC, ridwanmsharif commented
bors r+

2018-10-04 04:31 UTC, merged