sql: Use TableCollection cache for by-ID descriptor resolution
cockroachdb/cockroach pull request #30468
Opened 2018-09-20 16:13 UTC by itsbilal

This PR updates the optimizer catalog's ResolveDataSourceByID code
path to use the planner's TableCollection descriptor cache instead
of always doing kv reads. It also updates the resolver interface
to have an explicit tableID -> table descriptor resolver method.

Release note: None

2018-09-20 16:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30468)
<!-- Reviewable:end -->

2018-09-24 15:03 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/resolver.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNB4Xz-8g_bTGZH4qrA:-LNB4Xz068-cP_EnM4dc:biufmry) ([raw file](https://github.com/cockroachdb/cockroach/blob/19948ecb10c3b1ffcbd22b03ac098afe62c57dc3/pkg/sql/resolver.go#L262)):*
> ```Go
> 	ctx context.Context, id sqlbase.ID,
> ) (sqlbase.TableLookup, error) {
> 	return p.lookupFKTable(ctx, id)
> ```

we should rename lookupFKTable to LookupTableID and propagate that change to the users


<!-- Sent from Reviewable.io -->

2018-09-24 15:17 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/resolver.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNB4Xz-8g_bTGZH4qrA:-LNB8v2J9DXaSVE5K4q7:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/19948ecb10c3b1ffcbd22b03ac098afe62c57dc3/pkg/sql/resolver.go#L262)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

we should rename lookupFKTable to LookupTableID and propagate that change to the users
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2018-09-24 16:50 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/planner.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNBTlUT1-oasJy23-yD:-LNBTlUT1-oasJy23-yE:b-im3xho) ([raw file](https://github.com/cockroachdb/cockroach/blob/131710ca0a4831ce3fa3fc17f11d6bdb0cabf226/pkg/sql/planner.go#L393)):*
> ```Go
> }
> 
> func (p *planner) LookupTableID(
> ```

you'll need a comment explaining what this method does
___
*[pkg/sql/resolver.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNB4Xz-8g_bTGZH4qrA:-LNBU--F5qblnuouaoKJ:b3eenu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/19948ecb10c3b1ffcbd22b03ac098afe62c57dc3/pkg/sql/resolver.go#L262)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. 
</blockquote></details>

I also mean't not needing LookupTableByID() 


<!-- Sent from Reviewable.io -->

2018-09-24 16:52 UTC, BramGruneir requested changes
LGTM overall, just the nits.

> Reviewed 2 of 3 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-:-LNBUmoM62GcULc6p0xF:bk17p9n)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNBUaX8BrfdnIW2jCG7:-LNBUaX9DVz1EPPVa_f1:b6w7p9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/131710ca0a4831ce3fa3fc17f11d6bdb0cabf226/pkg/ccl/importccl/import_stmt.go#L369)):*
> ```Go
> 	ctx context.Context, id sqlbase.ID,
> ) (sqlbase.TableLookup, error) {
> 	return sqlbase.TableLookup{}, errSchemaResolver
> ```

Is this always supposed to be empty?
___
*[pkg/sql/planner.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNBTlUT1-oasJy23-yD:-LNBURjC5Fg4hGtzidPt:bnfm61v) ([raw file](https://github.com/cockroachdb/cockroach/blob/131710ca0a4831ce3fa3fc17f11d6bdb0cabf226/pkg/sql/planner.go#L393)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you'll need a comment explaining what this method does
</blockquote></details>

And should be named LookTableByID?


<!-- Sent from Reviewable.io -->

2018-09-24 17:09 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/importccl/import_stmt.go, line 369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNBUaX8BrfdnIW2jCG7:-LNBXuNX-eb9xL1zx2g2:b-ws9lm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/131710ca0a4831ce3fa3fc17f11d6bdb0cabf226/pkg/ccl/importccl/import_stmt.go#L369)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is this always supposed to be empty?
</blockquote></details>

In the case of errors, we keep it empty. This is your typical not-implemented error for this implementation of `sql.Resolver`.
___
*[pkg/sql/planner.go, line 393 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNBTlUT1-oasJy23-yD:-LNBY-VC0NzUe0WbHhgI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/131710ca0a4831ce3fa3fc17f11d6bdb0cabf226/pkg/sql/planner.go#L393)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

And should be named LookTableByID?
</blockquote></details>

Done.
___
*[pkg/sql/resolver.go, line 262 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30468#-LNB4Xz-8g_bTGZH4qrA:-LNBY0L39jX2wAQhHoBh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/19948ecb10c3b1ffcbd22b03ac098afe62c57dc3/pkg/sql/resolver.go#L262)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I also mean't not needing LookupTableByID() 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-24 17:15 UTC, vivekmenezes approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30468)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-09-24 17:35 UTC, itsbilal commented
bors r+

2018-09-24 18:07 UTC, itsbilal commented
bors r+

2018-09-24 18:49 UTC, merged