changefeedccl: more avro tests
cockroachdb/cockroach pull request #30484
Opened 2018-09-20 22:39 UTC by danhhz

Switched confluent_schema_registry from being a query parameter on the
sink uri to being a WITH option, it's much more natural this way.

Switched TestAvroEncoder to use the binary format by mocking out the
schema registry. Ripped out the avro-json format since it wasn't
returning or registering the schema in any way, which is an avro no-no.

Expanded TestAvroSchema to roundtrip the codec through json, which will
help us later check that a column can be recreated exactly from the avro
schema.

Also added the beginnings of an avro schema evolution/resolution test.
The first case checks adding a nullable SQL column.

Still not quite ready for external testing, so again no release note.

For #28637

Release note: None

2018-09-20 22:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30484)
<!-- Reviewable:end -->

2018-09-21 21:18 UTC, mrtracy requested changes
LGTM with one nit;  seems like it will work, although i'm starting to get a bit lost in the overall construction here; lots of layers and subtleties, hard to be sure that everything is testing the right thing on code review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30484#-:-LMxzMdf8V4cXnsuQjom:b-2jfza5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 571 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30484#-LMxbLCl2vxYK6KV9ShV:-LMxbLCl2vxYK6KV9ShW:b-ddxabe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f004cd59acc4ff93a4c5d7f717b4c3bc7839f110/pkg/ccl/changefeedccl/helpers_test.go#L571)):*
> ```Go
> 			}
> 			actual = append(actual, fmt.Sprintf(`%s: %s->%s`, topic, key, value))
> 		} else if resolved != nil {
> ```

This last else clause doesn't appear to do anything.


<!-- Sent from Reviewable.io -->

2018-09-22 05:25 UTC, mrtracy approved these changes

2018-09-24 18:56 UTC, danhhz reviewed
Yeah, I don't love how convoluted this all is and it's only going to get worse. Happy to step back and discuss how I got here over hangouts and see if there's some better way to do things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30484#-:-LNBvU7o88FL93_iKrmR:bnev6ne)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 571 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30484#-LMxbLCl2vxYK6KV9ShV:-LNBvSpCCkllBt_LZ-2h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f004cd59acc4ff93a4c5d7f717b4c3bc7839f110/pkg/ccl/changefeedccl/helpers_test.go#L571)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

This last else clause doesn't appear to do anything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-24 20:35 UTC, danhhz commented
bors r=mrtracy

2018-09-24 20:59 UTC, merged