opt: add UnifyComparisonTypes rule
cockroachdb/cockroach pull request #30504
Opened 2018-09-21 15:20 UTC by justinj

A comparison of the form

  column of time TIMESTAMP <comparison> constant DATE

should be able to generate index constraints if we have an index on the
timestamp column. However, prior to this commit, we did not.

This commit allows such comparisons to generate spans by casting the
constant if the following two conditions hold:

* The conversion between the two types is monotonic
  (a < b => f(a) < f(b)). This condition guarantees that such index
  constraints are valid for the original comparison. An example of a
  conversion for which this condition would not hold is INT -> STRING
  conversion, or virtually any collated string comparison.
* the constant can successfully round-trip. This guarantees that we do
  not lose any precision in the conversion between the two. For instance,
  we would need logic dependent on the nature of the conversion to know
  whether we need to convert `x > 3.3` to `x > 3` or `x > 4`.

This means that this commit can create spans in the case of a comparison
like `x > 3.0::FLOAT`, but not `x > 3.1::FLOAT`, which might be
unintuitive in some cases.

I feel like there are probably some edge cases to this code I'm not considering,
help coming up with problematic test cases would be appreciated!

Release note: None

2018-09-21 16:11 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMwjxLMDpkri6AgKOEM:-LMwjxLN5WuhcQvE1MWS:b-npv86v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/memo/testdata/logprops/constraints#L209)):*
> ```
> 
> opt
> SELECT * FROM kuv WHERE u > 1::INT
> ```

Beef up the comment above to make it clear that we only ignore *some* mixed-type comparisons, since this test is no longer doing what it was described to do.
___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 716 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMwmFLu8xwDIiL8Qmyd:-LMwmFLu8xwDIiL8Qmye:bl77v58) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/norm/testdata/rules/scalar#L716)):*
> ```
> 
> # --------------------------------------------------
> # UnifyComparisonTypes
> ```

Other tests:
- Positive/negative zero (floats, maybe decimal?)
- NaN/infinity
- Other comparison ops: IS, IS NOT (with and without nulls)
- Time zones
- Differently typed NULL values (NULL:::float, etc)
- Expressions other than simple variables on non-constant side
- Interesting expression that causes types to change when normalized, e.g.: `d - '1w'::INTERVAL > '2018-07-01'::DATE`. In that example, the left side is typed as timestamp initially, and then flips to date after normalization. This tests multiple rules, but is closely related to this rule, so seems a reasonable test.

Also, I'd sub-divide this test into sections, one for each data type family. We'll probably add more types, and we want to set the pattern for organization.
___
*[pkg/sql/opt/xform/testdata/external/tpch, line 723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMwtSXB4pP6GuxtZmHh:-LMwtSXB4pP6GuxtZmHi:b-p9qt1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/xform/testdata/external/tpch#L723)):*
> ```
>       │    ├── key: (1)
>       │    ├── fd: (1)-->(5,6)
>       │    ├── select
> ```

Rebecca's PR should fix this problem, in which `index-join` is not chosen due to anomalies in selectivity calculation.


<!-- Sent from Reviewable.io -->

2018-09-21 20:18 UTC, rytaft requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMxkKIJB1NPmRmrYxIk:-LMxkKIJB1NPmRmrYxIl:bglecjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/norm/rules/scalar.opt#L147)):*
> ```
> [UnifyComparisonTypes, Normalize]
> (Comparison
>     $left:^(Const)
> ```

Is there any benefit to matching this rule for all cases of `^(Const)`? Can we generate constraints on anything other than `(Variable)` or `(Tuple)` (Maybe this is a question for @RaduBerinde)?


<!-- Sent from Reviewable.io -->

2018-09-24 19:54 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMwjxLMDpkri6AgKOEM:-LNAuKrf9ggA_sLV_rKD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/memo/testdata/logprops/constraints#L209)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Beef up the comment above to make it clear that we only ignore *some* mixed-type comparisons, since this test is no longer doing what it was described to do.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMxkKIJB1NPmRmrYxIk:-LNAueUX3C4g4o2G_i4U:b84h46a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/norm/rules/scalar.opt#L147)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there any benefit to matching this rule for all cases of `^(Const)`? Can we generate constraints on anything other than `(Variable)` or `(Tuple)` (Maybe this is a question for @RaduBerinde)?
</blockquote></details>

This code doesn't currently handle the case where we're comparing against a tuple anyway, so that's a good point - I'll just limit this to `Variable` for now.
___
*[pkg/sql/opt/norm/testdata/rules/scalar, line 716 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LMwmFLu8xwDIiL8Qmyd:-LNBvzpo4cxUzBn6GW88:b-qgg7xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbca74139228e8a0a2b644a754609b9664cbc62e/pkg/sql/opt/norm/testdata/rules/scalar#L716)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Other tests:
- Positive/negative zero (floats, maybe decimal?)
- NaN/infinity
- Other comparison ops: IS, IS NOT (with and without nulls)
- Time zones
- Differently typed NULL values (NULL:::float, etc)
- Expressions other than simple variables on non-constant side
- Interesting expression that causes types to change when normalized, e.g.: `d - '1w'::INTERVAL > '2018-07-01'::DATE`. In that example, the left side is typed as timestamp initially, and then flips to date after normalization. This tests multiple rules, but is closely related to this rule, so seems a reasonable test.

Also, I'd sub-divide this test into sections, one for each data type family. We'll probably add more types, and we want to set the pattern for organization.
</blockquote></details>

Done - the example you gave actually exposed a small bug in `CanConstructBinary`, which I added a fix for.


<!-- Sent from Reviewable.io -->

2018-09-24 20:03 UTC, rytaft approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNC945U-SIXfi7m9JKa:-LNC945U-SIXfi7m9JKb:bdh6fju) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a55e485699e2f3c194fde1e03587483ed032a08/pkg/sql/opt/memo/testdata/logprops/constraints#L193)):*
> ```
>            └── const: 7 [type=int]
> 
> # Verify that we some ignore mixed-type comparisons.
> ```

some ignore -> ignore some


<!-- Sent from Reviewable.io -->

2018-09-24 20:48 UTC, andy-kimball approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNCJvHs6eOYyxcN6AWd:-LNCJvHs6eOYyxcN6AWe:bk1tdgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1213)):*
> ```Go
> // is not required.
> // TODO(justin): fill this out with the complete set of such conversions.
> func monotonicConversion(from, to coltypes.T) bool {
> ```

Should be `isMonotonicConversion`. Methods should generally start with a verb if they have behavior. This is not required fro methods that represent properties (like `OuterCols`), which this isn't.


<!-- Sent from Reviewable.io -->

2018-09-24 20:48 UTC, andy-kimball reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, nice work

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-:-LNCKkJJ16-pTF4z_EHo:b-qyf0xd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-25 14:29 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1203 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG4InZ0BgsiZXQ_hDZ:-LNG4InZ0BgsiZXQ_hD_:btnwhww) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1203)):*
> ```Go
> // monotonicConversion returns true if conversion of a value from FROM to
> // TO is monotonic.
> // That is, if a and b are values of type from, then
> ```

[nit] FROM
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG4rsN5ktjhid69bck:-LNG4rsN5ktjhid69bcl:b-924en0) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1209)):*
> ```Go
> // Note that the stronger property,
> //
> //   a < b implies a::TO < b::TO
> ```

It's not clear when reading these properties why we don't care about the second property (or why it's stronger) - can you add some examples, and also explain in what context we would care about monotonicity?

By the way, I don't think it's strictly stronger because the first property implies that `a=b  <=> a::TO=b::TO` which is not necessarily implied by the second one.

It might be clearer to say that we require:
 1) `a = b implies a::TO = b::TO`, and
 2) `a < b implies a::TO <= b::TO` (and explain that we don't need the stronger `a::TO < b::TO` here).
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG74Me3Ljl0hSfL49G:-LNG74Me3Ljl0hSfL49H:bt1h8te) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1234)):*
> ```Go
> 
> // UnifyComparison attempts to convert right to the type of left, if such a
> // conversion would be non-lossy and monotonic.
> ```

non-lossy can mean something stronger, for example `1.00:::decimal -> 1::int) -> 1:::decimal` would pass the check but it's not exactly non-lossy.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG6ykeDa3L69tqlr76:-LNG6ykeDa3L69tqlr77:bnoctdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1258)):*
> ```Go
> 	}
> 
> 	rightDatum := c.ExtractConstValue(right).(tree.Datum)
> ```

add a comment explaining that we're checking the roundtrip


<!-- Sent from Reviewable.io -->

2018-09-25 17:41 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/constraints, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNC945U-SIXfi7m9JKa:-LNGC4LHDDPUcpIISh7d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a55e485699e2f3c194fde1e03587483ed032a08/pkg/sql/opt/memo/testdata/logprops/constraints#L193)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

some ignore -> ignore some
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG4rsN5ktjhid69bck:-LNGC5m92g-AM-ySi2ZK:b-s3rnj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1209)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's not clear when reading these properties why we don't care about the second property (or why it's stronger) - can you add some examples, and also explain in what context we would care about monotonicity?

By the way, I don't think it's strictly stronger because the first property implies that `a=b  <=> a::TO=b::TO` which is not necessarily implied by the second one.

It might be clearer to say that we require:
 1) `a = b implies a::TO = b::TO`, and
 2) `a < b implies a::TO <= b::TO` (and explain that we don't need the stronger `a::TO < b::TO` here).
</blockquote></details>

Oh you're definitely right, it's not stronger in general.

I think that framing is much clearer - changed and added examples of where each property can be violated.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNCJvHs6eOYyxcN6AWd:-LNGjuML4gyv3dXOexMx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1213)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Should be `isMonotonicConversion`. Methods should generally start with a verb if they have behavior. This is not required fro methods that represent properties (like `OuterCols`), which this isn't.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG74Me3Ljl0hSfL49G:-LNGk5yf6q4V1zNLKQbo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1234)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

non-lossy can mean something stronger, for example `1.00:::decimal -> 1::int) -> 1:::decimal` would pass the check but it's not exactly non-lossy.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30504#-LNG6ykeDa3L69tqlr76:-LNGkpXS85yMuouefRcq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75be8d29d78640e3e2d7244c172a2aaa1e2181ea/pkg/sql/opt/norm/custom_funcs.go#L1258)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

add a comment explaining that we're checking the roundtrip
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-25 18:23 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-25 20:34 UTC, justinj commented
TFTRs!

bors r+

2018-09-25 20:47 UTC, merged

2018-09-25 22:03 UTC, RaduBerinde reviewed
> Reviewed 1 of 6 files at r1, 4 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30504)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->