pgwire: make conn hold most fields by value, not reference
cockroachdb/cockroach pull request #30508
Opened 2018-09-21 16:37 UTC by nvanbenschoten

This allows their lifetimes to be more obviously scoped together, reduces the number of pointers we have lying around for each SQL connection, and enables future optimization where we can put entire `pgwire.conn` objects in a pool.

2018-09-21 16:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30508)
<!-- Reviewable:end -->

2018-09-24 17:17 UTC, andreimatei requested changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-:-LNB_aXhBQEwSjIfHPlJ:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/conn_io.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-LNB_S60-R_0WiaeaCg5:-LNB_S614l-tmAWHJXY6:bmqmsvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e121a56ef9bbceed5a608233bab88511890a9233/pkg/sql/conn_io.go#L361)):*
> ```Go
> 
> // Init initializes a StmtBuf.
> func (buf *StmtBuf) Init() {
> ```

pls give a hint about why this exists in addition to `NewStmtBuf`
___
*[pkg/sql/pgwire/write_buffer.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-LNB__MJ0WVVjWDDDHky:-LNB__MJ0WVVjWDDDHkz:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/733e4e0e0ca544dc205b710e3e1ef4b97e1a3269/pkg/sql/pgwire/write_buffer.go#L60)):*
> ```Go
> }
> 
> func (b *writeBuffer) init(bytecount *metric.Counter) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2018-09-24 17:18 UTC, andreimatei approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-:-LNB_c6N9F5oHbx4rmRT:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-09-25 15:38 UTC, nvb reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-:-LNGN4KB-G2pk8fat5wZ:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/conn_io.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-LNB_S60-R_0WiaeaCg5:-LNGMfNM1-c8VgeiXLpF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e121a56ef9bbceed5a608233bab88511890a9233/pkg/sql/conn_io.go#L361)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls give a hint about why this exists in addition to `NewStmtBuf`
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/write_buffer.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30508#-LNB__MJ0WVVjWDDDHky:-LNGN3le3JAEkdT5fuNx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/733e4e0e0ca544dc205b710e3e1ef4b97e1a3269/pkg/sql/pgwire/write_buffer.go#L60)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-25 16:00 UTC, merged