engine: pool rocksDBBatch and RocksDBBatchBuilder allocations
cockroachdb/cockroach pull request #30523
Opened 2018-09-21 22:31 UTC by nvanbenschoten

This addresses the first three items from #30512.

I'm not seeing any big throughput improvements when running `kv0`
on my laptop (maybe ~1%, hard to tell), but I can see that this worked.
Total allocated space due to the three items in the issue dropped from
8.95% (1137.04 MB over a 1m run) to 0.32% (37.45 MB over a 1m run).

### Before

<img width="1195" alt="screen shot 2018-09-21 at 6 05 42 pm" src="https://user-images.githubusercontent.com/5438456/45908677-b6578580-bdcb-11e8-9135-52f450656578.png">

### After

<img width="1180" alt="screen shot 2018-09-21 at 6 05 30 pm" src="https://user-images.githubusercontent.com/5438456/45908679-b9eb0c80-bdcb-11e8-91f6-38cb46fd9c9d.png">

Release note (performance improvement): Pool allocations of rocksDBBatch
and RocksDBBatchBuilder objects.

2018-09-21 22:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30523)
<!-- Reviewable:end -->

2018-09-22 07:08 UTC, nvanbenschoten commented
If people like this then I'll probably follow it up with a similar change to pool `rocksDBReadOnly` objects. They're only responsible for 0.65% of allocated space in this TPC-C run, but their lifetimes are so clean that I think it makes sense to do.

2018-09-22 13:22 UTC, petermattis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30523)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/batch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0QIONBIToVNhblTtR:-LN0QIONBIToVNhblTtS:baej7gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/batch.go#L105)):*
> ```Go
> func (b *RocksDBBatchBuilder) reset() {
> 	if b.repr != nil {
> 		b.repr = b.repr[:headerSize]
> ```

If an unusually large batch was written, this could cause the memory to be held on to until the pool is cleaned. Do we want to worry about that?
___
*[pkg/storage/engine/rocksdb.go, line 1944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0Qa3VCgPp_Xgswb-F:-LN0Qa3VCgPp_Xgswb-G:b-uhxw4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/rocksdb.go#L1944)):*
> ```Go
> 		cpy := make([]byte, len(repr))
> 		copy(cpy, repr)
> 		return cpy
> ```

Did you audit all the calls to `Repr()`? I'm worried this could be a pessimization because my expectation was that `Repr()` didn't allocate and now it does. For example, `kvBatchSnapshotStrategy.Send` seems to call `Batch.Repr()` in a loop.


<!-- Sent from Reviewable.io -->

2018-09-24 19:25 UTC, a-robinson reviewed
Nothing to add beyond @petermattis's comments

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-:-LNC1mEX0QrUa2UTvIXO:b-wulxif)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-12 22:42 UTC, nvb reviewed
Sorry about sitting on this for so long. It wasn't going to make it into 2.1 so I put it on the backburner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-:-LOeP60C0VJgupUGAQ0I:b-7ygbwv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/batch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0QIONBIToVNhblTtR:-LNllM4X-boV4TTYHETe:b-ub2b1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/batch.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If an unusually large batch was written, this could cause the memory to be held on to until the pool is cleaned. Do we want to worry about that?
</blockquote></details>

Heh, @jordanlewis and I had a discussion about this before we began auditing allocations. The conclusion we came to was that the pool will flush all objects on each GC, so there's a low chance that an oversized object will live indefinitely.

Still, I've had the concern before and it's generally a good idea to play it safe, so I'm happy to add in some protection here. How does a 1MB retention limit sound?
___
*[pkg/storage/engine/rocksdb.go, line 1944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0Qa3VCgPp_Xgswb-F:-LOePHQfEMxwX7U4cJMV:bx5cujo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/rocksdb.go#L1944)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you audit all the calls to `Repr()`? I'm worried this could be a pessimization because my expectation was that `Repr()` didn't allocate and now it does. For example, `kvBatchSnapshotStrategy.Send` seems to call `Batch.Repr()` in a loop.
</blockquote></details>

That's a great point. Done.

Splitting out a separate `Len` method is a win on its own because we still were allocating in `Repr` when flushing mutations. This means that `kvBatchSnapshotStrategy.Send` was almost certainly allocating on each `len(b.Repr())` call already.


<!-- Sent from Reviewable.io -->

2018-10-15 13:53 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Yeah, this isn't appropriate for a backport.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-:-LOs-5xUB9_0EI9Y893m:b-3cwxnk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/batch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0QIONBIToVNhblTtR:-LOrzesCBB08sd3OnWGL:bs6fhtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/batch.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Heh, @jordanlewis and I had a discussion about this before we began auditing allocations. The conclusion we came to was that the pool will flush all objects on each GC, so there's a low chance that an oversized object will live indefinitely.

Still, I've had the concern before and it's generally a good idea to play it safe, so I'm happy to add in some protection here. How does a 1MB retention limit sound?
</blockquote></details>

`1MB` sounds good. Note that GC runs several times a second on small heaps, but can slow down to a run every few seconds on large heaps. 


<!-- Sent from Reviewable.io -->

2018-10-28 00:44 UTC, nvb reviewed
TFTRs.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-:-LPs4PjoCAh4YbbeE_Q6:b-tspvp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/engine/batch.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30523#-LN0QIONBIToVNhblTtR:-LPs4H3O1b7kU838kIqW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ca9f64c73322de7cd00f691d2658665bf035dd7/pkg/storage/engine/batch.go#L105)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`1MB` sounds good. Note that GC runs several times a second on small heaps, but can slow down to a run every few seconds on large heaps. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-28 00:59 UTC, merged