sql: drop index using ClearRange RPC
cockroachdb/cockroach pull request #30566
Opened 2018-09-24 15:48 UTC by eriktrinh

This change drops non-interleaved indexes using ClearRange. The
timestamp for when the drop of the non-interleaved index is initialized
is attached to mutation. During the running of the schema manager state
machine mutations with the attached timestamp are moved to a separate
list, and uses the timestamp and index's configured GC TTL value to
determine when a schema manager should execute and call
`ClearRange`. The index zone config is deleted when the data is removed
from `ClearRange`.

When the async schema changer deletes the index data using `ClearRange`,
two things occur: the job is marked as succeeded and the index zone
config is removed.

The job can immediately be marked as succeeded because currently a
separate job is created for each index that is dropped.

Fixes #20696

2018-09-24 15:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30566)
<!-- Reviewable:end -->

2018-09-26 16:53 UTC, vivekmenezes requested changes
This is a great start for a PR! Thanks for putting it together. I have a few comments for you to consider.

I wish there was a way to break up this change. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNLmeMbEAzmRwYjoHpF:b3p7e1o)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLfh1JEJU842Zcc-9s:-LNLfh1JEJU842Zcc-9t:b-q4hqeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/backfill.go#L210)):*
> ```Go
> 			return err
> 		}
> 	}
> ```

I forget why we need this code?
___
*[pkg/sql/backfill.go, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLg0Y342z0ld1L2dzB:-LNLg0Y342z0ld1L2dzC:b-bfvwdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/backfill.go#L296)):*
> ```Go
> 				resume, err = td.deleteIndex(
> 					ctx, &desc, resumeAt, chunkSize, noAutoCommit, false /* traceKV */, true, /* rangeDelete */
> 				)
> ```

why is this always true?
___
*[pkg/sql/schema_changer.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLhiR84Wj0gcw_Xxor:-LNLhiR84Wj0gcw_Xxos:b4qxg0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L361)):*
> ```Go
> 				return err
> 			}
> 		}
> ```

There are other mutations that are not GGCMutations. Those also have their jobs marked as succeeded. You want to move this logic to where that happens.
___
*[pkg/sql/schema_changer.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLm1On07S-0ZzUOdTe:-LNLm1On07S-0ZzUOdTf:b4cq4qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L531)):*
> ```Go
> 	table *sqlbase.TableDescriptor,
> ) error {
> 	if inSession || len(table.GCMutations) == 0 || len(sc.dropIndexTimes) == 0 {
> ```

also if len(table.Mutations) > 0 because we don't want to run any GC works while there are other mutations waiting.
___
*[pkg/sql/schema_changer.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLk3Wu7GqfWaxSM25G:-LNLk3Wu7GqfWaxSM25H:bnywu9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L607)):*
> ```Go
> 			if err := removeIndexZoneConfigs(ctx, txn, sc.execCfg, table.ID, dropped); err != nil {
> 				return err
> 			}
> ```

I suppose you can remove the zone config within truncateIndexes?
___
*[pkg/sql/schema_changer.go, line 967 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLia0MELsTcSbNCTW4:-LNLia0MELsTcSbNCTW5:bqlmmty) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L967)):*
> ```Go
> 	jobSucceeded := true
> 	return sc.leaseMgr.Publish(ctx, sc.tableID, func(desc *sqlbase.TableDescriptor) error {
> 		i := 0
> ```

reset jobSucceeded = true here because this function can be called more than once
you might as well also reset isRollback to false here too.
___
*[pkg/sql/schema_changer.go, line 1676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLmYoaEZZrmtgTT6mO:-LNLmYoaEZZrmtgTT6mP:b-j7085l) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L1676)):*
> ```Go
> 								indexExecAfter := timeutil.Unix(0, minDeadline)
> 								if schemaChanger.execAfter.IsZero() || schemaChanger.execAfter.After(indexExecAfter) {
> 									schemaChanger.execAfter = indexExecAfter
> ```

this can be reset below which is okay.
___
*[pkg/sql/sqlbase/structured.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLe2zmBa_jYK5yErh1:-LNLe2zmBa_jYK5yErh2:b-xccebw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/sqlbase/structured.proto#L545)):*
> ```protobuf
>   // The time which the mutation was initiated. This is used to indicate if a mutation
>   // should wait for the GC and complete asynchronously.
>   optional int64 modification_time = 8 [(gogoproto.nullable) = false];
> ```

I don't think we need this because the transitions through the state machine are rather fast and we can can use the time when the mutation is ready to be put in the GC queue as the drop time for the mutation.


<!-- Sent from Reviewable.io -->

2018-09-26 18:10 UTC, eriktrinh reviewed
Thank you for the review. This is a fairly large change and would be hard to break up, unfortunately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNM3h0q0jEk0X0cDlU7:b-dpbg92)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLfh1JEJU842Zcc-9s:-LNLr3NvA61g4N5rUl1L:birl6l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/backfill.go#L210)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I forget why we need this code?
</blockquote></details>

If the index is part of a table with index subzones and configs it requires a CCL binary to modify the zone config of the table (also, see `TestDropIndexWithZoneConfigOSS` in `drop_test.go`. This check is normally done in `removeIndexZoneConfigs` and returns an error preventing the index from being dropped, and is done here again for non-interleaved indexes.
___
*[pkg/sql/backfill.go, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLg0Y342z0ld1L2dzB:-LNLsF005t03Syksvjsy:b-27cih0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/backfill.go#L296)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

why is this always true?
</blockquote></details>

Because any non-interleaved indexes in this codepath has already waited the GC period and should be dropped using clearrange. It is only false when the drop index happens in the same transaction as the table creation (and will use the old index deletion for non-interleaved indexes).
___
*[pkg/sql/schema_changer.go, line 361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLhiR84Wj0gcw_Xxor:-LNLohUu0_-1glJS1IsV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L361)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

There are other mutations that are not GGCMutations. Those also have their jobs marked as succeeded. You want to move this logic to where that happens.
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLm1On07S-0ZzUOdTe:-LNLp1PaAOkqvzEAKtf6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L531)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

also if len(table.Mutations) > 0 because we don't want to run any GC works while there are other mutations waiting.
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLk3Wu7GqfWaxSM25G:-LNLq5z51v-pQkwSfX2V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L607)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I suppose you can remove the zone config within truncateIndexes?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 967 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLia0MELsTcSbNCTW4:-LNLqsk01PkoqMPrU-NF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L967)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

reset jobSucceeded = true here because this function can be called more than once
you might as well also reset isRollback to false here too.
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1676 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLmYoaEZZrmtgTT6mO:-LNLtvo57ZY4lEbb0v19:bfojdpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/schema_changer.go#L1676)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

this can be reset below which is okay.
</blockquote></details>

I moved it to be set below so that if the index GC deadline is before the drop table deadline it is not reset.
___
*[pkg/sql/sqlbase/structured.proto, line 545 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLe2zmBa_jYK5yErh1:-LNLul9O9LxOe_jPOvEN:biw8y1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/sqlbase/structured.proto#L545)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I don't think we need this because the transitions through the state machine are rather fast and we can can use the time when the mutation is ready to be put in the GC queue as the drop time for the mutation.
</blockquote></details>

Right. Done.


<!-- Sent from Reviewable.io -->

2018-09-27 16:13 UTC, vivekmenezes requested changes
Thanks for making the changes.

I think we can split this into three PRs.

1. A change that creates a SetTableGCImmediately() function that is used by all *existing* tests
2. A change that moves *all* non interleaved index data deletions to the asynchronous path.  What would happen if 
we also did it for the interleaved index? Would it break something to have interleaved index data for an index that doesn't exist? 
3. A change that changes the index data deletion under some circumstances to use ClearRange()

Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNQkHp1-574LiMu0VNm:bwk5ce8)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNLfh1JEJU842Zcc-9s:-LNQfd-M6kzJ9WQ59nsq:b-okpv0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd957c43bd4f6a7d31596162cbe17d5844ac8167/pkg/sql/backfill.go#L210)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

If the index is part of a table with index subzones and configs it requires a CCL binary to modify the zone config of the table (also, see `TestDropIndexWithZoneConfigOSS` in `drop_test.go`. This check is normally done in `removeIndexZoneConfigs` and returns an error preventing the index from being dropped, and is done here again for non-interleaved indexes.
</blockquote></details>

Hmmm, I'm not convinced this needs to be done here. Why here as opposed to in the DROP INDEX transaction?
___
*[pkg/sql/backfill.go, line 297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQg2T79ujiRwDhk_l9:-LNQg2T8EmlvHGL7b2PN:bmrhezk) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/backfill.go#L297)):*
> ```Go
> 		}
> 		if err := sc.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 			return removeIndexZoneConfigs(ctx, txn, sc.execCfg, sc.tableID, dropped)
> ```

was that CCL error returned by this?
___
*[pkg/sql/drop_table.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNMcXYvDvg_S2LEOVK7:-LNMcXYvDvg_S2LEOVK8:b7dmnh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_table.go#L390)):*
> ```Go
> 			return errors.Wrapf(err, "failed to mark job %d as as successful", gcm.JobID)
> 		}
> 	}
> ```

I'd suggest populating a map[JobID]stuct{} in the two above loops with jobs that need to be marked as successful and then looping over the map to mark the jobs.
___
*[pkg/sql/drop_test.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNMdqPkEmrVDWGsYfoK:-LNMdqPkEmrVDWGsYfoL:b-7kmav9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L431)):*
> ```Go
> 	params.Knobs = base.TestingKnobs{
> 		SQLSchemaChanger: &sql.SchemaChangerTestingKnobs{
> 			AsyncExecQuickly:  true,
> ```

Do you really need this?
___
*[pkg/sql/drop_test.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZ4IWD5pTG4tBj_H8:-LNQZ4IX3GBXyb1gLbUZ:b-kn2wd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L506)):*
> ```Go
> 		t.Fatalf("table descriptor still contains index after index is dropped")
> 	}
> 	tests.CheckKeyCount(t, kvDB, indexSpan, numRows)
> ```

Add this comment:

// index data hasn't been deleted.
___
*[pkg/sql/drop_test.go, line 530 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZFtx3Ld5x0o7ZILA:-LNQZFtx3Ld5x0o7ZILB:b-w1sdi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L530)):*
> ```Go
> 		t.Fatal(err)
> 	}
> ```

I'd suggest refactoring out  the above code into a separate PR and using it whereever we set the ttl to 0 in other tests, and then calling that function here. 
___
*[pkg/sql/drop_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZz4n5oWaYh8o5rWv:-LNQZz4n5oWaYh8o5rWw:b-llzsej) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L549)):*
> ```Go
> 	tests.CheckKeyCount(t, kvDB, tableDesc.TableSpan(), 2*numRows)
> }
> ```

excellent test! So it looks like the test below takes care of everything in this test, so we can safely delete it. 

Perhaps we can rename TestDropIndexNameReuse to just TestDropIndex
___
*[pkg/sql/schema_changer.go, line 976 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQdvfk15FKkXEzHM_u:-LNQdvfk15FKkXEzHM_v:btogp82) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/schema_changer.go#L976)):*
> ```Go
> 				indexDesc != nil &&
> 				!indexDesc.IsInterleaved() &&
> 				allowClearRange {
> ```

I think we need to have a function called 

canUseClearRangeFrorDropIndex()

and use that everywhere we check for isInterleaved() and the cluster settings. 
___
*[pkg/sql/schema_changer.go, line 987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQd7tc9JvevZrnV1m8:-LNQd7tc9JvevZrnV1m9:bp64tq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/schema_changer.go#L987)):*
> ```Go
> 					})
> 			} else {
> 				desc.MakeMutationComplete(mutation)
> ```

We always want to make the mutation complete independent of whether the mutation is moved to the gc mutations list or not


<!-- Sent from Reviewable.io -->

2018-09-27 16:14 UTC, vivekmenezes reviewed
I also want to say that given that you have worked for only a month on the project this is an incredible PR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNQndVm1ohaOWbOfuct:buzhl8r)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-09-27 22:31 UTC, eriktrinh reviewed
Repurposed this PR to include only the changes to move data deleted of non-interleaved indexes to the async code path. 

Moving interleaved indexes to also use the asynchronous path would not break things, but the problem is that the data would stay twice as long as it should (wait for GC TTL + tombstone cleanup). `ClearRange` also isn't feasible for interleaved indexes yet because the kv structure is different (see: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/index_encoding.go#L58 and https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160624_sql_interleaved_tables.md)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNS7_9k8JDt-N2BZT6E:b20t16u)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQg2T79ujiRwDhk_l9:-LNQrZ7o8Q4dg2SR-kdi:bd12u90) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/backfill.go#L297)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

was that CCL error returned by this?
</blockquote></details>

yes, in the synchronous path for interleaved indexes it will error here and the mutations would not complete. It makes sense to move it to the DROP INDEX transaction but it will be checked a second time when the zone configs are removed either way.
___
*[pkg/sql/drop_table.go, line 390 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNMcXYvDvg_S2LEOVK7:-LNQttMHBZAAhD-P36F2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_table.go#L390)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'd suggest populating a map[JobID]stuct{} in the two above loops with jobs that need to be marked as successful and then looping over the map to mark the jobs.
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 431 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNMdqPkEmrVDWGsYfoK:-LNQu6eDAwvL1sLIOuNB:b-ab7knj) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L431)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do you really need this?
</blockquote></details>

Nope, removed
___
*[pkg/sql/drop_test.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZ4IWD5pTG4tBj_H8:-LNQuXZCE4I_oFGvWBUI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L506)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Add this comment:

// index data hasn't been deleted.
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 530 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZFtx3Ld5x0o7ZILA:-LNRjrdrAjxONVXuzlbp:bmwfbvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L530)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I'd suggest refactoring out  the above code into a separate PR and using it whereever we set the ttl to 0 in other tests, and then calling that function here. 
</blockquote></details>

Done. See pr #30741
___
*[pkg/sql/drop_test.go, line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQZz4n5oWaYh8o5rWv:-LNQun4g2VL4KDNslHlT:b8e66fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/drop_test.go#L549)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

excellent test! So it looks like the test below takes care of everything in this test, so we can safely delete it. 

Perhaps we can rename TestDropIndexNameReuse to just TestDropIndex
</blockquote></details>

Thanks! I've removed the other DropIndex tests and renamed this one.
___
*[pkg/sql/schema_changer.go, line 976 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQdvfk15FKkXEzHM_u:-LNRF8PRDfcZtt4y3wIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/schema_changer.go#L976)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think we need to have a function called 

canUseClearRangeFrorDropIndex()

and use that everywhere we check for isInterleaved() and the cluster settings. 

</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 987 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNQd7tc9JvevZrnV1m8:-LNR6js76J9oXPuAoQDH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27ffbcbefaff5247ca1a76cfb68220be12fc8863/pkg/sql/schema_changer.go#L987)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We always want to make the mutation complete independent of whether the mutation is moved to the gc mutations list or not
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-09-28 01:42 UTC, vivekmenezes reviewed
I've not looked at your latest updates but what I was suggesting is move all index data deletion to the async path but set DropTime to a value only if ClearRange is going to be used. On the async path the DropTime can be used to delay the deletion of data for the use of ClearRange. is this doable? You certainly need a test to check that running SQL operations over the index data doesn't do anything funky. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNSp8Bk9OLhJ0K0bOGq:b-kaqtoj)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-03 14:55 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_test.go, line 507 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuISmn8xm5UKjwGbIK:-LNuISmn8xm5UKjwGbIL:by0dfmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/drop_test.go#L507)):*
> ```Go
> 	tests.CheckKeyCount(t, kvDB, newIdxSpan, numRows)
> 	tests.CheckKeyCount(t, kvDB, indexSpan, 0)
> 	tests.CheckKeyCount(t, kvDB, tableDesc.TableSpan(), 3*numRows)
> ```

great test!
___
*[pkg/sql/drop_test.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuIhFU0IVyIEzUJQR0:-LNuIhFU0IVyIEzUJQR1:bgecpcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/drop_test.go#L616)):*
> ```Go
> 	}
> 
> 	tests.CheckKeyCount(t, kvDB, tableSpan, 2*numRows)
> ```

Looks like both the changes you made to this test are not needed. 
___
*[pkg/sql/schema_changer.go, line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuKGJ60NfQaWghSG-0:-LNuKGJ60NfQaWghSG-1:b-tz1k0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L575)):*
> ```Go
> 		if timeRemaining < 0 {
> 			return nil
> 		}
> ```

It will be worth following up this PR with another one that abstracts this out into a function and uses it for the DROP TABLE and DROP INDEX use cases.  No need to do it here.
___
*[pkg/sql/schema_changer.go, line 594 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuKusBEGhH7PnG5hXu:-LNuKusBEGhH7PnG5hXv:brz26ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L594)):*
> ```Go
> 			for i := 0; i < len(tbl.GCMutations); i++ {
> 				otherMut := tbl.GCMutations[i]
> 				if otherMut.IndexID == mutation.IndexID {
> ```

Nit: combine the above two lines into one to limit scope of otherMut
___
*[pkg/sql/schema_changer.go, line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuL7gr5a4in6mqW4re:-LNuL7gr5a4in6mqW4rf:b-qxgrn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L602)):*
> ```Go
> 
> 			if !found {
> 				return errors.Errorf("could not find expected GC'd mutation")
> ```

I think you want to return errDidntUpdateDescriptor here just like you did above. In fact you can remove the one done above.
___
*[pkg/sql/schema_changer.go, line 1590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuOeO_BFRdEcVcZpWS:-LNuOeO_BFRdEcVcZpWT:b-k0f0l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1590)):*
> ```Go
> 						}
> 						if len(sc.dropIndexTimes) > 0 {
> 							earliestIndexExec := timeutil.Unix(0, 0)
> ```

You do not need to initialize this using Unix(0,0) . Just use a `var` declaration
___
*[pkg/sql/schema_changer.go, line 1689 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuPO0q1PxF5fHC_lgZ:-LNuPO0q1PxF5fHC_lg_:bxytih9) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1689)):*
> ```Go
> 								if minDeadline == 0 || deadline < minDeadline {
> 									minDeadline = deadline
> 									schemaChanger.dropIndexTimes = append([]droppedIndex{dropped}, schemaChanger.dropIndexTimes...)
> ```

is there a reason you need to prepend the dropped versus append it like you do below?
___
*[pkg/sql/schema_changer.go, line 1749 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuPsyM4m2_1xFwJfqB:-LNuPsyM4m2_1xFwJfqC:be1l6g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1749)):*
> ```Go
> 								// to be GC-ed.
> 								delete(s.schemaChangers, table.ID)
> 							}
> ```

The schema changer should only be on one list. If there is a non GC mutation needing processing it should stay on the non GC list.

There are three cases here
1. table contains non gc mutations -> schema change list
2. table contains only gc mutations -> gc list
3. table contains a mix of both -> schema change list.
___
*[pkg/sql/schema_changer_test.go, line 3502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuNfUnBsk8yq-NbArD:-LNuNfUnBsk8yq-NbArE:by33fke) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer_test.go#L3502)):*
> ```Go
> 
> 	// Verify that the index foo over v is consistent, and that column x has
> 	// been backfilled properly.
> ```

You've made a number of changes to the tests above that look fine but it's totall y worth running 
`make stress PKG=sql TESTS=TestFooBar` for 5 minutes on each of the tests you have changed.


<!-- Sent from Reviewable.io -->

2018-10-03 17:35 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_test.go, line 507 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuISmn8xm5UKjwGbIK:-LNuteWI9UTJdZJCc_Ai:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/drop_test.go#L507)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

great test!
</blockquote></details>

Thanks!
___
*[pkg/sql/drop_test.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuIhFU0IVyIEzUJQR0:-LNuc6Ct6vHQ6LziI_rN:b-23b050) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/drop_test.go#L616)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Looks like both the changes you made to this test are not needed. 
</blockquote></details>

Woops, reverted
___
*[pkg/sql/schema_changer.go, line 575 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuKGJ60NfQaWghSG-0:-LNuufOhB_a3KFgAqNBh:b1e1icw) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L575)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

It will be worth following up this PR with another one that abstracts this out into a function and uses it for the DROP TABLE and DROP INDEX use cases.  No need to do it here.
</blockquote></details>

Might be worth it to just keep track of the deadline for the DROP TABLE case
___
*[pkg/sql/schema_changer.go, line 594 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuKusBEGhH7PnG5hXu:-LNuaYOIAm2lB9-BZROE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L594)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Nit: combine the above two lines into one to limit scope of otherMut
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuL7gr5a4in6mqW4re:-LNuafzQB8oI5EV5Yzax:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L602)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think you want to return errDidntUpdateDescriptor here just like you did above. In fact you can remove the one done above.
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuOeO_BFRdEcVcZpWS:-LNuap7L2H9yI9kKvvRk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1590)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

You do not need to initialize this using Unix(0,0) . Just use a `var` declaration
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer.go, line 1689 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuPO0q1PxF5fHC_lgZ:-LNuarVODvcmRVhb7WHz:bcdovun) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1689)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

is there a reason you need to prepend the dropped versus append it like you do below?
</blockquote></details>

Right now the list is maintained such that the head of the list is the dropped index with the earliest GC deadline so that in `maybeGCMutations` we avoid searching for such index by querying for the zone configs when checking if the deadline has passed. I've changed this so that the schema manager keeps track of the deadlines as well as the droptimes so we do not need to query for the zone config again.
___
*[pkg/sql/schema_changer.go, line 1749 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuPsyM4m2_1xFwJfqB:-LNucGVA7eu3SdoDN_6j:bi41xgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1749)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

The schema changer should only be on one list. If there is a non GC mutation needing processing it should stay on the non GC list.

There are three cases here
1. table contains non gc mutations -> schema change list
2. table contains only gc mutations -> gc list
3. table contains a mix of both -> schema change list.



</blockquote></details>

Done, although I think if the table is being dropped we can just put it into the schema change list


<!-- Sent from Reviewable.io -->

2018-10-04 15:54 UTC, vivekmenezes approved these changes
Can you copy the new commit message into the PR description. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-:-LNzlfyg5-X-3uDc0EKj:b-sm1kyx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer.go, line 1749 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuPsyM4m2_1xFwJfqB:-LNzlXHm9QpZm3tw259y:b4xsexg) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer.go#L1749)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Done, although I think if the table is being dropped we can just put it into the schema change list
</blockquote></details>

That sounds right
___
*[pkg/sql/schema_changer_test.go, line 3502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuNfUnBsk8yq-NbArD:-LNzm8pJCqCbwhobmQtM:b-b07yl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer_test.go#L3502)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

You've made a number of changes to the tests above that look fine but it's totall y worth running 
`make stress PKG=sql TESTS=TestFooBar` for 5 minutes on each of the tests you have changed.
</blockquote></details>

Please do the above before merging


<!-- Sent from Reviewable.io -->

2018-10-05 21:33 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 3502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuNfUnBsk8yq-NbArD:-LO58K3O2gFzucvmdxdX:bq6bgwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer_test.go#L3502)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Please do the above before merging
</blockquote></details>

Done. Please take another look at the changes made in `schema_changer_test.go`.


<!-- Sent from Reviewable.io -->

2018-10-08 14:56 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/schema_changer_test.go, line 3502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LNuNfUnBsk8yq-NbArD:-LOJ9o8V8_QgxLUpTYMt:b-wzvord) ([raw file](https://github.com/cockroachdb/cockroach/blob/63211532914d7d1c3f19220c68575856d34ce504/pkg/sql/schema_changer_test.go#L3502)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Done. Please take another look at the changes made in `schema_changer_test.go`.
</blockquote></details>

So I do see a number of instances where you're enabling early GC by setting the zone config and enabling quick asynchronous execution of schema changes. Why do you need to do that? In particular, can you just embrace the fact that index data will not be deleted?

I can see situations where the table is still being written to and in those circumstances you will not be able to count the keys correctly. Let's restrict the forced deletion to only those cases.


<!-- Sent from Reviewable.io -->

2018-10-09 16:38 UTC, vivekmenezes approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1753 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOORrDU7OUBziBJnL3k:-LOORrDU7OUBziBJnL3l:b-ms4l8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/crdb_internal.go#L1753)):*
> ```Go
> 						if err == sqlbase.ErrIndexGCMutationsList {
> 							continue
> 						}
> ```

let's add a logictest for this 
___
*[pkg/sql/schema_changer_test.go, line 1466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOO_dA17LW8qHmNrK2r:-LOO_dA17LW8qHmNrK2s:b-9f2soh) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L1466)):*
> ```Go
> 	params, _ := tests.CreateTestServerParams()
> 	const chunkSize = 200
> 	var enableAsyncSchemaChanges uint32 = 1
> ```

I forget why you had to enable the async schema changer and then disable it?
___
*[pkg/sql/schema_changer_test.go, line 1560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOOaacR5nP5VvTm4g9P:-LOOaacR5nP5VvTm4g9Q:b-l97pfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L1560)):*
> ```Go
> 	if e := 1; len(tableDesc.GCMutations) != e {
> 		t.Fatalf("the table has %d instead of %d GC mutations", len(tableDesc.GCMutations), e)
> 	}
> ```

probably worth checking the values within the GCMutation
___
*[pkg/sql/schema_changer_test.go, line 2124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOOb9zIBi0lZicyGADM:-LOOb9zIBi0lZicyGADN:buw7u48) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L2124)):*
> ```Go
> 	// and completes successfully. The drop column part of the change errors
> 	// during backfilling the second chunk but cannot rollback the drop index.
> 	const expectedAttempts = 2
> ```

Add a comment here that the index truncation is no longer run through a backfill . Perhaps we should rename this expectedColumnBackfillAttempts


<!-- Sent from Reviewable.io -->

2018-10-09 18:37 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30566)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal.go, line 1753 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOORrDU7OUBziBJnL3k:-LOP5GvV6jL9vOB4Fhho:b-ppl01y) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/crdb_internal.go#L1753)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

let's add a logictest for this 
</blockquote></details>

The logictests shouldn't be able to marshal/unmarshal protos which would be required for a test like this. Instead, I've added a check in `partitionccl/drop_test.go` to ensure that the zone config is ignored the `crdb_internal.zones` and doesn't error.
___
*[pkg/sql/schema_changer_test.go, line 1466 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOO_dA17LW8qHmNrK2r:-LOOqPkp2ebqGoEXnVkP:b-deq5f9) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L1466)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I forget why you had to enable the async schema changer and then disable it?
</blockquote></details>

We enable it to allow the async schema changer to attempt to truncate the index in the rollback, where an error will occur . It is then disabled to preventing the scheduled retry from occurring so we can perform assertions on the table state. It is then re-enabled to allow the rollback to complete.
___
*[pkg/sql/schema_changer_test.go, line 1560 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOOaacR5nP5VvTm4g9P:-LOOmsC25qorT4UAzhaw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L1560)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

probably worth checking the values within the GCMutation
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 2124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30566#-LOOb9zIBi0lZicyGADM:-LOOnP0AE9-HKNsWxJ6i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98a13289c21efb3ff55bb56dfbdae988a99bac05/pkg/sql/schema_changer_test.go#L2124)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Add a comment here that the index truncation is no longer run through a backfill . Perhaps we should rename this expectedColumnBackfillAttempts
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-09 18:48 UTC, eriktrinh commented
bors r+

2018-10-09 19:08 UTC, eriktrinh commented
bors r-

2018-10-09 19:09 UTC, eriktrinh commented
bors r+

2018-10-09 19:26 UTC, merged