server: add a configuration to enable GC of system.rangelog
cockroachdb/cockroach pull request #30913
Opened 2018-10-03 10:38 UTC by mvijaykarthik

system.rangelog table currently grows unboundedly. The rate of
growth is slow (as long as there is no replica rebalancing
thrashing), but it can still become a problem in long running
clusters.

This commit adds cluster settings to specify interval and TTL
for rows in system.rangelog.
By default, GC of system.rangelog is disabled.

Fixes #21260

Release note: Add configuration to enable GC of system.rangelog

2018-10-03 10:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30913)
<!-- Reviewable:end -->

2018-10-03 17:01 UTC, benesch reviewed
This is awesome! @tschottdorf, are you the right person to review?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LNurlF1ATBqBSNG3B3V:b-74ot4q)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LNurto15I9s_VoiJkgr:-LNurto15I9s_VoiJkgs:b-oxg2ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad41304b5b512f9169081f407af32fac1774ec3/pkg/server/server.go#L137)):*
> ```Go
> 		"if non zero, range log entries older than this duration are deleted periodically "+
> 			"based on storage.rangelog.gc_interval",
> 		0,
> ```

I think we could probably default this to something like 30d. @bdarnell do you have thoughts?


<!-- Sent from Reviewable.io -->

2018-10-03 17:05 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LNurto15I9s_VoiJkgr:-LNusVX742HO9RpoEK8c:b7f4to9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad41304b5b512f9169081f407af32fac1774ec3/pkg/server/server.go#L137)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think we could probably default this to something like 30d. @bdarnell do you have thoughts?
</blockquote></details>

Yeah, I think this should be on by default. 30d seems reasonable (or maybe the threshold should be based on the size of the log, to cover cases when the log blows up suddenly due to rebalancer thrashing?)


<!-- Sent from Reviewable.io -->

2018-10-03 17:16 UTC, BramGruneir reviewed
This will be running on every server and there's no need for that.  Can we run this only on a specific node?  Say check for which node is the leaseholder for the rangelog and only try the delete there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LNuv8VU72YXdTfePARm:b-9q2qmb)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-03 19:15 UTC, petermattis reviewed
Glad this is getting done. I'll echo @bramgruneir's comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LNvLdI6DXjKP0NSy37B:b-aq6eez)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LNvKzYC85yLx34gWuno:-LNvKzYC85yLx34gWunp:bk7f7ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad41304b5b512f9169081f407af32fac1774ec3/pkg/server/server.go#L89)):*
> ```Go
> const (
> 	// defaultRangeLogGCInterval is the default interval to run gc on rangelog.
> 	defaultRangeLogGCInteval = 30 * time.Minute
> ```

`s/Inteval/Interval/g` (you've got it spelled right in the comment!)


<!-- Sent from Reviewable.io -->

2018-10-04 08:39 UTC, mvijaykarthik reviewed
Updated it to run on lease holder of range 1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LNyDpYXBrswhF1qXp5i:b-8wde6r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LNvKzYC85yLx34gWuno:-LNvbh385ha5uIP9kndY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad41304b5b512f9169081f407af32fac1774ec3/pkg/server/server.go#L89)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/Inteval/Interval/g` (you've got it spelled right in the comment!)
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LNurto15I9s_VoiJkgr:-LNvbmCQ-xk-22zccW5k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad41304b5b512f9169081f407af32fac1774ec3/pkg/server/server.go#L137)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, I think this should be on by default. 30d seems reasonable (or maybe the threshold should be based on the size of the log, to cover cases when the log blows up suddenly due to rebalancer thrashing?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-08 14:35 UTC, tbg requested changes
I gave this a coarse review. This already looks pretty good! A little bit of work is left to do to make sure this doesn't cause problems. Thanks so far @mvijaykarthik!

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LOJ5QigDRrl4N_nczO7:b-cahzo6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIrqOnANgcWauNa73E:-LOIrqOo2UKIlbsJi4Y6:bn2myjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L41)):*
> ```Go
> 
> 	"github.com/cockroachdb/cmux"
> ```

Remove this newline.
___
*[pkg/server/server.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ1vdSEPCot1thCAPk:-LOJ1vdSEPCot1thCAPl:bgn3z6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L131)):*
> ```Go
> 
> 	// RangeLogTTL is the TTL for rows in system.rangelog. If non zero, range log
> 	// entries are periodically garbage collectd. The period is given by
> ```

collected
___
*[pkg/server/server.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIrzD25mbrlYclWd13:-LOIrzD25mbrlYclWd14:bsms4rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L144)):*
> ```Go
> 	RangeLogGCInterval = settings.RegisterDurationSetting(
> 		"server.rangelog.gc_interval",
> 		"interval for running gc on rangelog. If storage.rangelog.ttl is non zero, "+
> ```

Shouldn't this simply be a function of `server.rangelog.ttl` (i.e. not a cluster var)? I think it should be computed as `min(10*time.Minute, RangeLogTTL)`. We don't want to want 30 days to make an attempt or deployments which see restarts every <30 days will never GC the range log. We also can't just blindly run at startup because leaseholdership is often not known then (on top of generating silly errors that might end up in the logs).
___
*[pkg/server/server.go, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIsyGdDoaCwqVlq-xt:-LOIsyGdDoaCwqVlq-xu:b-eb97o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1071)):*
> ```Go
> // It returns the node currently responsible for performing GC, the number of
> // rows affected and error (if any).
> func (s *Server) gcRangeLog(
> ```

please extract all of this new code into a new file `server_rangelog_gc.go`.
___
*[pkg/server/server.go, line 1074 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ3GvbAw1zuR8d_YR3:-LOJ3GvbAw1zuR8d_YR4:b-7rfzzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1074)):*
> ```Go
> 	ctx context.Context, cutoffTimestamp time.Time,
> ) (roachpb.NodeID, int, error) {
> 	const selectLeaseHolderStmt = `SELECT lease_holder from crdb_internal.ranges where range_id=1`
> ```

Careful, last I checked this was really expensive -- it sends an RPC to all nodes, collects information about all ranges, queries all leaseholders in a loop, and then throws it all away just to give you your boolean -- @changangela, I think you worked on this recently in https://github.com/cockroachdb/cockroach/pull/30846. What I say above is still mostly true, except for the loop to get the leaseholder, right? That would be *way* too expensive.

I think you can use

```go
repl, err := s.node.stores.GetReplicaForRangeID(roachpb.RangeID(1))
repl.IsFirstRange() && repl.OwnsValidLease(s.clock.Now())
```

for a *much* cheaper check.
___
*[pkg/server/server.go, line 1075 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ1z3jCLgUsKOeVN3x:-LOJ1z3jCLgUsKOeVN3y:bp42w60) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1075)):*
> ```Go
> ) (roachpb.NodeID, int, error) {
> 	const selectLeaseHolderStmt = `SELECT lease_holder from crdb_internal.ranges where range_id=1`
> 	const deleteStmt = `DELETE FROM system.rangelog WHERE timestamp <= $1 LIMIT 1000`
> ```

This is a queue-like workload and as such we should give it both a lower and upper bound so that the query reads

```sql
DELETE FROM system.rangelog WHERE timestamp <= $1 AND timestamp >= $2 LIMIT 1000
```

and in each iteration update the $2 with the last returned result (and you return the final $2 from the method so that it can be passed in again for the next run).

When the loop runs for the first time, I think it's OK if it uses a $2 of zero (hard to avoid).

Also make sure that you exercise the case in which you insert north of 1000 entries to be GC'ed, if you haven't already.
___
*[pkg/server/server.go, line 1081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ4qFt2XO7m8YNQ1Gk:-LOJ4qFt2XO7m8YNQ1Gl:buv7atz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1081)):*
> ```
> Rangelog
> ```

RangeLog (for both knobs).
___
*[pkg/server/server.go, line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIw0ax1bw8UTBzGXye:-LOIw0ax1bw8UTBzGXyf:blqq10a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1136)):*
> ```Go
> func (s *Server) startRangeLogGC(ctx context.Context) {
> 	s.stopper.RunWorker(ctx, func(ctx context.Context) {
> 		intervalChangeCh := make(chan time.Duration)
> ```

(This is a comment on this whole method)

Unfortunately it's really difficult to write a bug-free and robust implementation of a timer loop that's sensitive to cluster settings in the "optimal" way. Could you structure this exactly like #25227 which had a much much simpler loop (and also went through a couple of iterations in review)? You can start a server that overrides the default to a low value.

Here you have the problem that the cluster setting has an "on" default (30d), so naively it won't work. Instead, you can just override the default for the GC duration to something low by passing a suitable `*cluster.Settings` into TestServerArgs. Just look for a test that passes a non-nil `*cluster.Settings` into a `TestServerArgs` for inspiration. You can set the value with `myClusterVar.Set(&st.SV, 3*time.Millisecond)`.
___
*[pkg/storage/log_test.go, line 401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ0YfF1RvQkezO8ieg:-LOJ0YfF1RvQkezO8ieh:b-k9v5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L401)):*
> ```Go
> }
> 
> func TestLogGC(t *testing.T) {
> ```

I'd prefer if this lived close to the code that you're testing, in `pkg/server`. Any reason to not do that?
___
*[pkg/storage/log_test.go, line 518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ4t2ZCVE6xc-vsd_v:-LOJ4t2ZCVE6xc-vsd_w:b-rdjadk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L518)):*
> ```Go
> 	a.Equal(2000, rangeLogRowCount())
> 
> 	// GC everything
> ```

Stylistic nit: add `.` to every sentence.


<!-- Sent from Reviewable.io -->

2018-10-08 15:00 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 1074 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ3GvbAw1zuR8d_YR3:-LOJAwun9KqyqRiAf0B6:b-r35t61) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1074)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Careful, last I checked this was really expensive -- it sends an RPC to all nodes, collects information about all ranges, queries all leaseholders in a loop, and then throws it all away just to give you your boolean -- @changangela, I think you worked on this recently in https://github.com/cockroachdb/cockroach/pull/30846. What I say above is still mostly true, except for the loop to get the leaseholder, right? That would be *way* too expensive.

I think you can use

```go
repl, err := s.node.stores.GetReplicaForRangeID(roachpb.RangeID(1))
repl.IsFirstRange() && repl.OwnsValidLease(s.clock.Now())
```

for a *much* cheaper check.
</blockquote></details>

Since the `ranges` virtual table is now just a view over `ranges_no_leases`, the optimizer should be able to apply the filter first and then do the RPC request for only the one leaseholder.


<!-- Sent from Reviewable.io -->

2018-10-08 15:03 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 1074 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ3GvbAw1zuR8d_YR3:-LOJBrpj0aO7RbPMBj7h:b-wyfwpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1074)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Since the `ranges` virtual table is now just a view over `ranges_no_leases`, the optimizer should be able to apply the filter first and then do the RPC request for only the one leaseholder.
</blockquote></details>

Oh, but yeah unfortunately it still populates the entirety of the `ranges_no_leases` virtual table.


<!-- Sent from Reviewable.io -->

2018-10-08 19:14 UTC, mvijaykarthik reviewed
I have also added gc for system.eventlog as it was a very minor change to also include this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LOK2AXyCQqotgXYJ3id:b12om47)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIrqOnANgcWauNa73E:-LOJ6i8LAmPI3Zq8H0AO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L41)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Remove this newline.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ1vdSEPCot1thCAPk:-LOJ6ine2ayxIgPSfdHs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L131)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

collected
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIrzD25mbrlYclWd13:-LOJBQyXCo2HzLubIYtI:b-74xdug) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Shouldn't this simply be a function of `server.rangelog.ttl` (i.e. not a cluster var)? I think it should be computed as `min(10*time.Minute, RangeLogTTL)`. We don't want to want 30 days to make an attempt or deployments which see restarts every <30 days will never GC the range log. We also can't just blindly run at startup because leaseholdership is often not known then (on top of generating silly errors that might end up in the logs).
</blockquote></details>

I have kept this as 10m. If people accidentally set a low TTL, the gc loop may hamper system performance. Mentioned this in the documentation of this setting.
___
*[pkg/server/server.go, line 1071 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIsyGdDoaCwqVlq-xt:-LOJATnRDRMuIUJyPtG3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1071)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

please extract all of this new code into a new file `server_rangelog_gc.go`.
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1074 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ3GvbAw1zuR8d_YR3:-LOJDfO8BZiD3w6sgQv4:bg0ccnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1074)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Oh, but yeah unfortunately it still populates the entirety of the `ranges_no_leases` virtual table.
</blockquote></details>

Done. But it's not in the same transaction though. It shouldn't matter correctness wise, and should be fine performance wise as long as the lease doesn't bounce around.
___
*[pkg/server/server.go, line 1075 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ1z3jCLgUsKOeVN3x:-LOJyJeK6S8NX2NTIWHU:b-ubi8s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1075)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is a queue-like workload and as such we should give it both a lower and upper bound so that the query reads

```sql
DELETE FROM system.rangelog WHERE timestamp <= $1 AND timestamp >= $2 LIMIT 1000
```

and in each iteration update the $2 with the last returned result (and you return the final $2 from the method so that it can be passed in again for the next run).

When the loop runs for the first time, I think it's OK if it uses a $2 of zero (hard to avoid).

Also make sure that you exercise the case in which you insert north of 1000 entries to be GC'ed, if you haven't already.
</blockquote></details>

Done. A test case is present with 2000 rows.
___
*[pkg/server/server.go, line 1081 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ4qFt2XO7m8YNQ1Gk:-LOJ88OCCH7ZZluDUagr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1081)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> ```
> Rangelog
> ```

RangeLog (for both knobs).
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIw0ax1bw8UTBzGXye:-LOJAk9G5a--ZLpArVr7:b-5ypjrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L1136)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

(This is a comment on this whole method)

Unfortunately it's really difficult to write a bug-free and robust implementation of a timer loop that's sensitive to cluster settings in the "optimal" way. Could you structure this exactly like #25227 which had a much much simpler loop (and also went through a couple of iterations in review)? You can start a server that overrides the default to a low value.

Here you have the problem that the cluster setting has an "on" default (30d), so naively it won't work. Instead, you can just override the default for the GC duration to something low by passing a suitable `*cluster.Settings` into TestServerArgs. Just look for a test that passes a non-nil `*cluster.Settings` into a `TestServerArgs` for inspiration. You can set the value with `myClusterVar.Set(&st.SV, 3*time.Millisecond)`.
</blockquote></details>

Done. Changed to ticker. Tweaking this interval ideally shouldn't be required.
___
*[pkg/storage/log_test.go, line 401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ0YfF1RvQkezO8ieg:-LOJBA7BA-XIQ3KbUm5z:b-9bui9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L401)):*
I'm using the below to insert test rangelog events.
> ```
> store.LogReplicaChangeTest(
> ```
It not usable from server package. That's why I added it here
___
*[pkg/storage/log_test.go, line 518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ4t2ZCVE6xc-vsd_v:-LOK5GDE5NdoNhAWrV2y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L518)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Stylistic nit: add `.` to every sentence.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-10 10:32 UTC, tbg requested changes
Looks pretty good already. Some more comments but getting close!

> Reviewed 6 of 6 files at r3.
> Dismissed @petermattis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LOSWlpN16fkqdwgRTFu:b-1n9z8v)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOIrzD25mbrlYclWd13:-LOSSiK93eRSZ_aTKxOc:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/server/server.go#L144)):*
<details><summary><i>Previously, mvijaykarthik wrote…</i></summary><blockquote>

I have kept this as 10m. If people accidentally set a low TTL, the gc loop may hamper system performance. Mentioned this in the documentation of this setting.
</blockquote></details>

SGTM.
___
*[pkg/server/server_systemlog_gc.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOST7yG2d1y3TSY4ypR:-LOST7yG2d1y3TSY4ypS:b-syonu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L45)):*
> ```Go
> 	repl, err := s.node.stores.GetReplicaForRangeID(roachpb.RangeID(1))
> 	if err != nil {
> 		return 0, err
> ```

You want to handle the case in which there isn't a replica for r1 more gracefully to avoid spurious errors.
___
*[pkg/server/server_systemlog_gc.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSTcDt1_ApXPqXNC-Z:-LOSTcDuExE6dGj6DG3L:bdvl45y) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L48)):*
> ```Go
> 	}
> 
> 	if repl.IsFirstRange() && repl.OwnsValidLease(s.clock.Now()) {
> ```

I'd make that an early return, so you can de-dent all the code below. Same comment as above.
___
*[pkg/server/server_systemlog_gc.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSTgyU3OeKi1Dy2vRI:-LOSTgyU3OeKi1Dy2vRJ:b-7yvjgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L56)):*
> ```Go
> 		// A timestamp lower-bound is used in the delete query to avoid hitting
> 		// tombstones.
> 		// This lower bound is periodically updated after every successful delete
> ```

Sorry if that wasn't clear, but I was also expecting you to return this bound from this method. A large enough range tombstone minefield will cause a noticeable CPU spike and affect unrelated requests' p99. Ideally at some point range tombstones are less of a problem, but they are one today. The only case in which we'll eat the tombstones is when the server first starts and runs this loop.
___
*[pkg/server/server_systemlog_gc.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSUAZT1py895Y5_Wop:-LOSUAZT1py895Y5_Woq:byrhaas) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L118)):*
> ```Go
> 
> 	s.stopper.RunWorker(ctx, func(ctx context.Context) {
> 		period := 10 * time.Minute
> ```

make this a const somewhere so that you can also pretty-print it into the description of the cluster setting (where you refer to the 10min interval).
___
*[pkg/server/server_systemlog_gc.go, line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSUPHFBBZIievR5VlE:-LOSUPHFBBZIievR5VlF:b8hlo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L120)):*
> ```Go
> 		period := 10 * time.Minute
> 		if storeKnobs, ok := s.cfg.TestingKnobs.Store.(*storage.StoreTestingKnobs); ok && storeKnobs.SystemLogsGCPeriod != 0 {
> 			period = storeKnobs.SystemLogsGCPeriod
> ```

Ah, I see. That's why you were able to hard-code the 10min interval. Works for me.
___
*[pkg/server/server_systemlog_gc.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSUcWc-bB-yDC3pFv8:-LOSUcWc-bB-yDC3pFv9:bbspv58) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L144)):*
> ```Go
> 
> 						if rowsAffected > 0 {
> 							log.Infof(ctx, "garbage collected %d rows from %s", rowsAffected, table)
> ```

Make this `V(1)`. In a sufficiently busy cluster this will log every 10min, and that's not useful.
___
*[pkg/storage/log_test.go, line 401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ0YfF1RvQkezO8ieg:-LOSVZMJE-paFiJ5r54k:byj9j3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L401)):*
<details><summary><i>Previously, mvijaykarthik wrote…</i></summary><blockquote>

I'm using the below to insert test rangelog events.
> ```
> store.LogReplicaChangeTest(
> ```
It not usable from server package. That's why I added it here
</blockquote></details>

I'd prefer if you took what you needed from `func (s *Store) insertRangeLogEvent(` to insert dummy events. 
___
*[pkg/storage/log_test.go, line 578 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSVsu69kgdWxr9obk8:-LOSVsu69kgdWxr9obk9:b-gqnuep) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/storage/log_test.go#L578)):*
> ```Go
> 			)
> 
> 			tc.setting.Override(&s.ClusterSettings().SV, time.Nanosecond)
> ```

Please don't use `Override` after the server has been started, this is flaky since your custom value can be overridden by a Gossip update. Use `SET CLUSTER SETTING` instead. (I gave you bad advice here, sorry about that).


<!-- Sent from Reviewable.io -->

2018-10-10 13:50 UTC, mvijaykarthik reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/server/server_systemlog_gc.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOST7yG2d1y3TSY4ypR:-LOShRm08c98Uf9J1F02:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L45)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You want to handle the case in which there isn't a replica for r1 more gracefully to avoid spurious errors.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 48 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSTcDt1_ApXPqXNC-Z:-LOShSAGE1Z7ag6k_HdW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L48)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'd make that an early return, so you can de-dent all the code below. Same comment as above.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSTgyU3OeKi1Dy2vRI:-LOSi96TAL-HqElzAYgF:b-38vzz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L56)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Sorry if that wasn't clear, but I was also expecting you to return this bound from this method. A large enough range tombstone minefield will cause a noticeable CPU spike and affect unrelated requests' p99. Ideally at some point range tombstones are less of a problem, but they are one today. The only case in which we'll eat the tombstones is when the server first starts and runs this loop.
</blockquote></details>

Done. I think it will also hit tombstones if the lease holder for range 1 changes.
___
*[pkg/server/server_systemlog_gc.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSUAZT1py895Y5_Wop:-LOTEQbu1WW8naBVRgIA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L118)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

make this a const somewhere so that you can also pretty-print it into the description of the cluster setting (where you refer to the 10min interval).
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSUcWc-bB-yDC3pFv8:-LOSgFIO8GCA-wnZUBON:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/server/server_systemlog_gc.go#L144)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Make this `V(1)`. In a sufficiently busy cluster this will log every 10min, and that's not useful.
</blockquote></details>

Done.
___
*[pkg/storage/log_test.go, line 401 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOJ0YfF1RvQkezO8ieg:-LOSg5HD3BTuhKVq4nPj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2acfad2b82d5bef6a6c9c2daae072bac4956284c/pkg/storage/log_test.go#L401)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'd prefer if you took what you needed from `func (s *Store) insertRangeLogEvent(` to insert dummy events. 
</blockquote></details>

Done.
___
*[pkg/storage/log_test.go, line 578 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOSVsu69kgdWxr9obk8:-LOSkZtH1rxJ1GdpFs9D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/759bb3957040e7f2cbcb78e40aa04108d1a7deba/pkg/storage/log_test.go#L578)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Please don't use `Override` after the server has been started, this is flaky since your custom value can be overridden by a Gossip update. Use `SET CLUSTER SETTING` instead. (I gave you bad advice here, sorry about that).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-10 21:14 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> after my comments (none of which are substantial) are addressed. Thanks @mvijaykarthik and good work!

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LOUpA3RDSn0k0E048dS:bk0268g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/server.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhZt98FuSoU4O0Lzq:-LOUhZtADwwLYInd4i8K:bwexpiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server.go#L41)):*
> ```Go
> 
> 	"github.com/cockroachdb/cmux"
> ```

stray newline.
___
*[pkg/server/server_systemlog_gc.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhmo549f2j6zsKc8G:-LOUhmo549f2j6zsKc8H:b-2hz6gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L44)):*
> ```Go
> 		"server.rangelog.ttl",
> 		fmt.Sprintf(
> 			"if non zero, range log entries older than this duration are deleted periodically (%v period).",
> ```

`are deleted every %s`
___
*[pkg/server/server_systemlog_gc.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhp7l8LeD7mMmFp1C:-LOUhp7mC0K9NKcoac9e:b-2hz6gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L55)):*
> ```Go
> 		"server.eventlog.ttl",
> 		fmt.Sprintf(
> 			"if non zero, event log entries older than this duration are deleted periodically (%v period).",
> ```

`are deleted every %s`
___
*[pkg/server/server_systemlog_gc.go, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUiKZs58FqB_tikkTM:-LOUiKZs58FqB_tikkTN:byplpm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L68)):*
> ```Go
> // performs gc.
> // The system log table is expected to have a "timestamp" column.
> // It returns the highest timestamp gcd, number of rows affected and error
> ```

If it didn't GC anything, it should return `timestampUpperBound`, so I would just say that it returns a lower bound to be used in the next iteration.

Note that there's also a race here: if the ttl is very low, it's possible that events could be inserted at timestamps below the cutoff and so they would be missed.

I think that's OK. Perhaps worth a comment to suggest not setting the TTL lower than, say, a day.
___
*[pkg/server/server_systemlog_gc.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUon0g6QoRxKNZF-6x:-LOUon0g6QoRxKNZF-6y:bk6x4qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L71)):*
> ```Go
> // (if any).
> func (s *Server) gcSystemLog(
> 	ctx context.Context, table string, timestampLowerBound, timestampUpperBound time.Time,
> ```

just for paranoia, let's make sure that if `timestampLowerBound >= timestampUpperBound`, this method works. I think it does (won't remove anything and might regress the cutoff, but that's ok) but please also take a look.
___
*[pkg/server/server_systemlog_gc.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhurO8OE8gULD4k99:-LOUhurPA1ht-nVpVkVU:baodsa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L77)):*
> ```Go
> 	if err != nil {
> 		if log.V(1) {
> 			log.Warning(ctx, "unable to get descriptor for range 1")
> ```

Don't want to log the error? Also this would be Infof. In a large cluster most nodes won't have a replica of r1 and will see RangeNotFoundError here.
___
*[pkg/server/server_systemlog_gc.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUi02b44o-yhGrcjpS:-LOUi02b44o-yhGrcjpT:b-y9tk88) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L79)):*
> ```Go
> 			log.Warning(ctx, "unable to get descriptor for range 1")
> 		}
> 		return time.Time{}, 0, nil
> ```

You want to return the old timestamp bound to the caller.
___
*[pkg/server/server_systemlog_gc.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUie0Y7a8geeZliTkF:-LOUie0Y7a8geeZliTkG:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L86)):*
> ```Go
> 			log.Warningf(ctx, "not running gc on system.%v as node is not lease holder of range 1", table)
> 		}
> 		return time.Time{}, 0, nil
> ```

ditto
___
*[pkg/server/server_systemlog_gc.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUnCnG02Vk2dF37fmv:-LOUnCnG02Vk2dF37fmw:bguo4e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L149)):*
> is the timestamp below which events are gc'ed.
___
*[pkg/server/server_systemlog_gc_test.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUnpc70q2LJqMRW4w2:-LOUnpc8-3iFjdNWA76S:b-4gdagt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc_test.go#L80)):*
> ```Go
> 					txn.OrigTimestamp().GoTime(),
> 					testRangeID,
> 					1, // storeID.
> ```

optional nit: no dot here (inline comment). Go style guide :man_shrugging: 
___
*[pkg/server/server_systemlog_gc_test.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUnwgn7Sda1cdK8aH0:-LOUnwgn7Sda1cdK8aH1:b-vhf24p) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc_test.go#L104)):*
> ```Go
> 
> 	// GC up to maxTs1.
> 	tm, rowsGCd, err := ts.GCSystemLog(ctx, table, timeutil.Unix(0, 0), maxTs1)
> ```

nit: maxTS1, maxTS2, ... (Golang style guide wants abbreviations capitalized, like `HTTP` not `Http`).


<!-- Sent from Reviewable.io -->

2018-10-11 06:57 UTC, mvijaykarthik reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/server/server.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhZt98FuSoU4O0Lzq:-LOWESFw0v7jxvf8NcxH:b-rujqek) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server.go#L41)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

stray newline.
</blockquote></details>

Ah sorry. My editor auto-formats imports and it keeps adding this newline every time I edit this file.
___
*[pkg/server/server_systemlog_gc.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhmo549f2j6zsKc8G:-LOWEjKPCXNDxr11YNpn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L44)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`are deleted every %s`
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhp7l8LeD7mMmFp1C:-LOWEjyxE3lAQpamY8Xc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L55)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`are deleted every %s`
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 68 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUiKZs58FqB_tikkTM:-LOWFWrR-P9dWaVrbYUt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L68)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

If it didn't GC anything, it should return `timestampUpperBound`, so I would just say that it returns a lower bound to be used in the next iteration.

Note that there's also a race here: if the ttl is very low, it's possible that events could be inserted at timestamps below the cutoff and so they would be missed.

I think that's OK. Perhaps worth a comment to suggest not setting the TTL lower than, say, a day.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUon0g6QoRxKNZF-6x:-LOWFY__6FskcegkFmkp:bhaobmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L71)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

just for paranoia, let's make sure that if `timestampLowerBound >= timestampUpperBound`, this method works. I think it does (won't remove anything and might regress the cutoff, but that's ok) but please also take a look.
</blockquote></details>

I added a test case for equality case. I'll also add one for `>` case.
___
*[pkg/server/server_systemlog_gc.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUhurO8OE8gULD4k99:-LOWFqSj5uA_GV34ZKzN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L77)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Don't want to log the error? Also this would be Infof. In a large cluster most nodes won't have a replica of r1 and will see RangeNotFoundError here.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUi02b44o-yhGrcjpS:-LOWFr0J-GvBoIkcNOiB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L79)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You want to return the old timestamp bound to the caller.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUie0Y7a8geeZliTkF:-LOWFry7DBc1JhzvJ_Oa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L86)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUnCnG02Vk2dF37fmv:-LOWG5ixB7JEicaAI7cB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc.go#L149)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> is the timestamp below which events are gc'ed.
</blockquote></details>

Done.
___
*[pkg/server/server_systemlog_gc_test.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-LOUnpc70q2LJqMRW4w2:-LOWGcBy5Onp-wYPZQfZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c19c036a03b441830016064090d4e81fa86389e/pkg/server/server_systemlog_gc_test.go#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

optional nit: no dot here (inline comment). Go style guide :man_shrugging: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-11 08:32 UTC, tbg approved these changes
Thanks @mvijaykarthik! I had a few edits that were so minor that I went ahead patched them into your branch, I hope that's ok.

bors r+

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30913#-:-LOXFGttAJiEFnoV5vZR:bdowpe6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-10-11 10:29 UTC, tschottdorf commented
Flaked on #31246

2018-10-11 10:30 UTC, tschottdorf commented
Just triggered the merge for the PR that fixes that, so:

bors r+

2018-10-11 10:59 UTC, merged