distsqlrun: optimize merge joiner memory account usage
cockroachdb/cockroach pull request #30924
Opened 2018-10-03 15:30 UTC by changangela

Instead of closing the memory account for every single row, we can "resize" it to a size of 0.

Benchmark for this change:
```
name                           old time/op    new time/op    delta
MergeJoiner/InputSize=0-8        3.89µs ± 0%    3.87µs ± 0%   -0.34%  (p=0.000 n=9+9)
MergeJoiner/InputSize=4-8        8.15µs ± 1%    8.32µs ± 3%   +2.05%  (p=0.000 n=10+9)
MergeJoiner/InputSize=16-8       16.5µs ± 0%    15.2µs ± 1%   -7.76%  (p=0.000 n=10+10)
MergeJoiner/InputSize=256-8       193µs ± 1%     169µs ± 4%  -12.52%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8     3.03ms ± 1%    2.56ms ± 1%  -15.34%  (p=0.000 n=10+8)
MergeJoiner/InputSize=65536-8    50.3ms ±12%    45.8ms ± 9%   -9.10%  (p=0.000 n=9+10)

name                           old alloc/op   new alloc/op   delta
MergeJoiner/InputSize=0-8        6.65kB ± 0%    6.65kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=4-8        9.72kB ± 0%    9.72kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=16-8       9.72kB ± 0%    9.72kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=256-8      32.8kB ± 0%    32.8kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=4096-8      401kB ± 0%     401kB ± 0%     ~     (all equal)
MergeJoiner/InputSize=65536-8    6.30MB ± 0%    6.30MB ± 0%     ~     (p=0.260 n=10+9)

name                           old allocs/op  new allocs/op  delta
MergeJoiner/InputSize=0-8          15.0 ± 0%      15.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=4-8          17.0 ± 0%      17.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=16-8         17.0 ± 0%      17.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=256-8        47.0 ± 0%      47.0 ± 0%     ~     (all equal)
MergeJoiner/InputSize=4096-8        527 ± 0%       527 ± 0%     ~     (all equal)
MergeJoiner/InputSize=65536-8     8.21k ± 0%     8.21k ± 0%     ~     (all equal)

name                           old speed      new speed      delta
MergeJoiner/InputSize=4-8      7.86MB/s ± 0%  7.70MB/s ± 3%   -2.09%  (p=0.000 n=9+9)
MergeJoiner/InputSize=16-8     15.5MB/s ± 0%  16.8MB/s ± 1%   +8.41%  (p=0.000 n=10+10)
MergeJoiner/InputSize=256-8    21.2MB/s ± 1%  24.2MB/s ± 4%  +14.38%  (p=0.000 n=10+10)
MergeJoiner/InputSize=4096-8   21.6MB/s ± 1%  25.6MB/s ± 1%  +18.13%  (p=0.000 n=10+8)
MergeJoiner/InputSize=65536-8  20.9MB/s ±11%  23.0MB/s ±10%  +10.00%  (p=0.000 n=9+10)
```

2018-10-03 15:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30924)
<!-- Reviewable:end -->

2018-10-03 15:33 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNuYPKcANvrjB57A2T_:-LNuYPKcANvrjB57A2Ta:b-apu5ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed0ed03366a6caa40e9d848929f5380ff6dce4e/pkg/sql/distsqlrun/stream_group_accumulator.go#L120)):*
> ```Go
> 			ret := s.curGroup[:n:n]
> 			s.curGroup = s.curGroup[:0]
> 			s.memAcc.ResizeTo(evalCtx.Context, int64(0))
> ```

Instead of resizing the `memAcc` to 0, we can achieve significant improvement in speed if we if we reserve a minimum size for the MergeJoiner. ie. we grow the account to `merge_joiner_min_size` at the start, and then `s.memAcc.ResizeTo(evalCtx.Context, int64(merge_joiner_min_size))` here. Thoughts?


<!-- Sent from Reviewable.io -->

2018-10-03 15:37 UTC, jordanlewis commented
> Instead resizing the to a 0, we can achieve significant improvement in speed if we if we reserve a minimum size for the MergeJoiner. ie. we grow the account to merge_joiner_min_size at the start, and then s.memAcc.ResizeTo(evalCtx.Context, int64(merge_joiner_min_size)) here. Thoughts?

That does seem good, but why is that such an improvement?

2018-10-03 17:36 UTC, changangela reviewed
Since the `MergeJoiner` is constantly re-requesting for blocks of memory, a lot of the overhead can be reduced if we "allocate" some memory right at the beginning of the merge join and hold onto it until the end. I've updated the code to have the `streamGroupAccumulator` allocate a single block of memory right at the start of the process, and updated the benchmark above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LNuzG5n1eZRLckP5uj7:b-sf57mj)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-04 17:03 UTC, solongordon requested changes
The general approach makes sense to me. Some questions about implementation details.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LO-11TI7LMYXAaVEKOZ:bqxh7ry)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNuYPKcANvrjB57A2T_:-LO--lip5Fx1-DvkvVUA:beilkix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed0ed03366a6caa40e9d848929f5380ff6dce4e/pkg/sql/distsqlrun/stream_group_accumulator.go#L120)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Instead resizing the to a 0, we can achieve significant improvement in speed if we if we reserve a minimum size for the MergeJoiner. ie. we grow the account to `merge_joiner_min_size` at the start, and then `s.memAcc.ResizeTo(evalCtx.Context, int64(merge_joiner_min_size))` here. Thoughts?
</blockquote></details>

Could this same thing be achieved at the `BytesMonitor` level by reserving `minAllocated` up front?
___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO-0Qsy6Fdc4ql4u5zB:-LO-0Qsy6Fdc4ql4u5zC:boqkv32) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/sql/distsqlrun/stream_group_accumulator.go#L63)):*
> ```Go
> func (s *streamGroupAccumulator) start(ctx context.Context) {
> 	s.src.Start(ctx)
> 	s.memAcc.AllocateMinimum(ctx, 1)
> ```

Could you explain the choice of `1` here? I'm wondering if this should be related to row size. Otherwise if you have rows larger than `poolAllocationSize`, your optimization will never kick in.
___
*[pkg/util/mon/bytes_usage.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzBqQBL0SccH_Vv7Y:-LNzzBqRAR4Z8qdAvT1n:bd0fmip) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L452)):*
> ```Go
> 	// decreases as used increases (and vice-versa).
> 	reserved     int64
> 	minAllocated int64
> ```

Could use a comment here.
___
*[pkg/util/mon/bytes_usage.go, line 481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO-0NDm-cfjYEqwNJNo:-LO-0NDm-cfjYEqwNJNp:b-y9ylmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L481)):*
> ```Go
> }
> 
> // AllocateMinimum allocates a minimum allocated size (reserved + used) for the
> ```

`SetMinAllocated` might be clearer.
___
*[pkg/util/mon/bytes_usage.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzMZe6k1NB2wsp4KL:-LNzzMZe6k1NB2wsp4KM:b-icpsvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L484)):*
> ```Go
> // account. The account would not be able to Shrink() unless it has surpassed
> // this minimum allocated value.
> func (b *BoundAccount) AllocateMinimum(ctx context.Context, blocks int64) {
> ```

I wonder if `blocks` is the best interface here. It's hard to know what the right blocks value is without knowing what the pool allocation size is. Maybe better to just specify it in bytes?
___
*[pkg/util/mon/bytes_usage.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzmQ4-1GS_woYHS0b:-LNzzmQ4-1GS_woYHS0c:bch7i9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L486)):*
> ```Go
> func (b *BoundAccount) AllocateMinimum(ctx context.Context, blocks int64) {
> 	if blocks >= 0 {
> 		b.minAllocated = blocks * DefaultPoolAllocationSize
> ```

Should this be `b.mon.poolAllocationSize`?
___
*[pkg/util/mon/bytes_usage.go, line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO--QppCHebde0hqIEJ:-LO--QppCHebde0hqIEK:b-hn8m41) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L501)):*
> ```Go
> 	b.used = 0
> 	b.reserved = 0
> 	b.minAllocated = 0
> ```

I'm not sure if it makes sense to zero this out in `Clear` since it's more of a configuration setting than a state variable. I guess it depends on how `Clear` is generally used.


<!-- Sent from Reviewable.io -->

2018-10-04 18:16 UTC, changangela reviewed
Thanks @solongordon for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LO-Cn9p1yLzwRq0waUt:b-8l86lx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNuYPKcANvrjB57A2T_:-LO-DcGs-9BwquSO4eiK:b-e9xehx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed0ed03366a6caa40e9d848929f5380ff6dce4e/pkg/sql/distsqlrun/stream_group_accumulator.go#L120)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Could this same thing be achieved at the `BytesMonitor` level by reserving `minAllocated` up front?
</blockquote></details>

Hmm, the reason I thought it was best to put it into the `BoundAccount` instead of `(*BytesMonitor).releaseBytes`  was because function calling is quite expensive in this part of the code (ie. one level deeper function call decreases the benchmark speed by ~5%), and so it might take little longer before the `Shrink` decides to stop shrinking. Is this what you had in mind?
___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO-0Qsy6Fdc4ql4u5zB:-LO-CZ5H12ZK6Qz60nTt:bhlq365) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/sql/distsqlrun/stream_group_accumulator.go#L63)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Could you explain the choice of `1` here? I'm wondering if this should be related to row size. Otherwise if you have rows larger than `poolAllocationSize`, your optimization will never kick in.
</blockquote></details>

Yeah, I was actually just investigating that because using `1` optimized the joiner significantly. It turns out that in `Shrink()`, we were doing a (vacuously true) check on:
```
	if b.reserved >= b.mon.poolAllocationSize {
		b.mon.releaseBytes(ctx, b.reserved-b.mon.poolAllocationSize)
		b.reserved = b.mon.poolAllocationSize
	}
```
And, a very significant amount of overhead was due to the `>=`. If we change it to `>` then the block size of `1` becomes irrelevant. I think it makes sense for `minAllocated` to be related to row size in for the merge joiner though, will work on that.
___
*[pkg/util/mon/bytes_usage.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzBqQBL0SccH_Vv7Y:-LO-FoYXBmCTSPo85fhI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L452)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Could use a comment here.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO-0NDm-cfjYEqwNJNo:-LO-FOH7CL2vmIc08Piu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L481)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

`SetMinAllocated` might be clearer.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzMZe6k1NB2wsp4KL:-LO-FyWvC9xuwiPyzy3g:bu7e7sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L484)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I wonder if `blocks` is the best interface here. It's hard to know what the right blocks value is without knowing what the pool allocation size is. Maybe better to just specify it in bytes?
</blockquote></details>

I think it might be important to enforce that the `minAllocated` is some multiple of  `poolAllocationSize` because of the way `Shrink()` is related to `poolAllocationSize`. For example, if the client chooses `20479` (poolAllocationSize * 2 - 1) bytes, then this is logically equivalent to using `10240` (poolAllocationSize) which might be confusing. What do you think?
___
*[pkg/util/mon/bytes_usage.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzmQ4-1GS_woYHS0b:-LO-GxmQ8tHXEwq0twke:b5cd8x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L486)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Should this be `b.mon.poolAllocationSize`?
</blockquote></details>

Done. I'm not too sure what the difference is :P
___
*[pkg/util/mon/bytes_usage.go, line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO--QppCHebde0hqIEJ:-LO-HNN0AiBwvWO7kzL7:b4mjo68) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L501)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I'm not sure if it makes sense to zero this out in `Clear` since it's more of a configuration setting than a state variable. I guess it depends on how `Clear` is generally used.
</blockquote></details>

Done. Yeah that makes sense.


<!-- Sent from Reviewable.io -->

2018-10-04 18:48 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNuYPKcANvrjB57A2T_:-LO-Lhys7IW2NbisRdr1:b-m9sh7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed0ed03366a6caa40e9d848929f5380ff6dce4e/pkg/sql/distsqlrun/stream_group_accumulator.go#L120)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Hmm, the reason I thought it was best to put it into the `BoundAccount` instead of `(*BytesMonitor).releaseBytes`  was because function calling is quite expensive in this part of the code (ie. one level deeper function call decreases the benchmark speed by ~5%), and so it might take little longer before the `Shrink` decides to stop shrinking. Is this what you had in mind?
</blockquote></details>

Sorry, I meant to say `BoundAccount` not `BytesMonitor`. I was just thinking that for your suggestion above, you could implement that in `BoundAccount` rather than the `MergeJoiner` itself and keep things simpler. Though perhaps you are trying to avoid the function calls to `Grow`?
___
*[pkg/util/mon/bytes_usage.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzMZe6k1NB2wsp4KL:-LO-NnSi0-zhvyP9JLh4:b-nebvgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L484)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

I think it might be important to enforce that the `minAllocated` is some multiple of  `poolAllocationSize` because of the way `Shrink()` is related to `poolAllocationSize`. For example, if the client chooses `20479` (poolAllocationSize * 2 - 1) bytes, then this is logically equivalent to using `10240` (poolAllocationSize) which might be confusing. What do you think?
</blockquote></details>

Yeah, I see your point, though of the two I think it's more confusing to specify blocks without knowing what the block size is. And the concept of blocks is an implementation detail of the monitor so it feels weird to expose it. I'm not sure there's much harm in reserving more than specified, since that's already the case in calls to `Grow`.
___
*[pkg/util/mon/bytes_usage.go, line 486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzmQ4-1GS_woYHS0b:-LO-NS2mDpllMi7XGi1x:b5wagka) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L486)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Done. I'm not too sure what the difference is :P
</blockquote></details>

Looks like the default value can be overridden via the `increment` parameter in `MakeMonitor`.


<!-- Sent from Reviewable.io -->

2018-10-04 19:27 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNuYPKcANvrjB57A2T_:-LO-Y0XN-2O04y1C2NCJ:bh5c3y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed0ed03366a6caa40e9d848929f5380ff6dce4e/pkg/sql/distsqlrun/stream_group_accumulator.go#L120)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Sorry, I meant to say `BoundAccount` not `BytesMonitor`. I was just thinking that for your suggestion above, you could implement that in `BoundAccount` rather than the `MergeJoiner` itself and keep things simpler. Though perhaps you are trying to avoid the function calls to `Grow`?
</blockquote></details>

Oops, didn't realize the original comment referred to what was already implemented. Disregard.


<!-- Sent from Reviewable.io -->

2018-10-08 14:54 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO-0Qsy6Fdc4ql4u5zB:-LOJ9t98E5zfUb-8TlHn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/sql/distsqlrun/stream_group_accumulator.go#L63)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Yeah, I was actually just investigating that because using `1` optimized the joiner significantly. It turns out that in `Shrink()`, we were doing a (vacuously true) check on:
```
	if b.reserved >= b.mon.poolAllocationSize {
		b.mon.releaseBytes(ctx, b.reserved-b.mon.poolAllocationSize)
		b.reserved = b.mon.poolAllocationSize
	}
```
And, a very significant amount of overhead was due to the `>=`. If we change it to `>` then the block size of `1` becomes irrelevant. I think it makes sense for `minAllocated` to be related to row size in for the merge joiner though, will work on that.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 484 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LNzzMZe6k1NB2wsp4KL:-LO-Qsj-1GE4TgnGcmPJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L484)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yeah, I see your point, though of the two I think it's more confusing to specify blocks without knowing what the block size is. And the concept of blocks is an implementation detail of the monitor so it feels weird to expose it. I'm not sure there's much harm in reserving more than specified, since that's already the case in calls to `Grow`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-08 17:18 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/mon/bytes_usage.go, line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LO--QppCHebde0hqIEJ:-LOJfj_42jWDnisyttb_:bnv32jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5392a330124ceb58c108f07c28f40e8e48563a01/pkg/util/mon/bytes_usage.go#L501)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Done. Yeah that makes sense.
</blockquote></details>

Since we're now reserving the minAllocated memory right on call to `SetMinAllocated`, I think it makes sense to reset `minAllocated` when `used + reserved = 0`


<!-- Sent from Reviewable.io -->

2018-10-08 17:46 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOJjffZEm83yqCegLKH:-LOJjffZEm83yqCegLKI:bpefzcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2dec241b76f8368ba7b43ba23e6bd3c5ae7412/pkg/sql/distsqlrun/stream_group_accumulator.go#L126)):*
> ```Go
> 			s.curGroup = s.curGroup[:0]
> 
> 			if totalSize > s.memAcc.Allocated() {
> ```

Hm, I'm worried this approach is too greedy now. If I understand this right, you now have a BoundAccount which only ever reserves more bytes without releasing any until it is closed. That means if there are many small groups with one large one, we'll reserve the large group size until the merge join is complete.

Maybe there is a middle ground, like setting minAllocated to the size of one row?


<!-- Sent from Reviewable.io -->

2018-10-08 19:12 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOJjffZEm83yqCegLKH:-LOK35900y6WoWzvn0EG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac2dec241b76f8368ba7b43ba23e6bd3c5ae7412/pkg/sql/distsqlrun/stream_group_accumulator.go#L126)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Hm, I'm worried this approach is too greedy now. If I understand this right, you now have a BoundAccount which only ever reserves more bytes without releasing any until it is closed. That means if there are many small groups with one large one, we'll reserve the large group size until the merge join is complete.

Maybe there is a middle ground, like setting minAllocated to the size of one row?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-08 21:08 UTC, changangela reviewed
Fixed `SetMinAllocated` to release bytes if the new `minAllocated` shrinks below the current used. Also added some tests for the `bytes_usage` functions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LOKVIwX6HyCphfS4oDL:b-ygijf4)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-09 15:04 UTC, solongordon requested changes
Nice, a few last comments but this is looking good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LOOLHG20W9-oZbMyAN5:b-w6mice)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOOCh15EMBKhHCJALIT:-LOOCh15EMBKhHCJALIU:b2herc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab777d4387378bd31d5f6775ab18a3f2427234e/pkg/sql/distsqlrun/stream_group_accumulator.go#L59)):*
> ```Go
> 		ordering:        ordering,
> 		memAcc:          memMonitor.MakeBoundAccount(),
> 		minAllocatedSet: false,
> ```

Nit: This line isn't really necessary since `false` is the zero value for bools. No harm having it though.
___
*[pkg/util/mon/bytes_usage.go, line 491 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOOEJCf6_htfIA3bWTG:-LOOEJCf6_htfIA3bWTH:bv0kxq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab777d4387378bd31d5f6775ab18a3f2427234e/pkg/util/mon/bytes_usage.go#L491)):*
> ```Go
> 	if size >= 0 {
> 		b.minAllocated = b.mon.roundSize(size)
> 	}
> ```

You probably want to set `minAllocated = 0` if `size == 0`, right?
___
*[pkg/util/mon/bytes_usage.go, line 508 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOOKyzyEnkk5mGDVuTS:-LOOKyzyEnkk5mGDVuTT:b8fj2zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab777d4387378bd31d5f6775ab18a3f2427234e/pkg/util/mon/bytes_usage.go#L508)):*
> ```Go
> 		b.mon.releaseBytes(ctx, released)
> 		b.reserved -= released
> 	}
> ```

The logic above looks good to me after some staring, though it would be nice to add some basic unit tests to cover the different cases here, explicitly checking that the `b.reserved` value is as expected after `SetMinAllocated` is called.


<!-- Sent from Reviewable.io -->

2018-10-09 18:07 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/util/mon/bytes_usage.go, line 491 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOOEJCf6_htfIA3bWTG:-LOOweZf3JsHVPx-AodS:b-xbsk5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab777d4387378bd31d5f6775ab18a3f2427234e/pkg/util/mon/bytes_usage.go#L491)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

You probably want to set `minAllocated = 0` if `size == 0`, right?
</blockquote></details>

Yeah, `mon.roundSize` should take care of that properly. 
___
*[pkg/util/mon/bytes_usage.go, line 508 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOOKyzyEnkk5mGDVuTS:-LOOwwFE5H3nNxRMO8M6:b-th94lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ab777d4387378bd31d5f6775ab18a3f2427234e/pkg/util/mon/bytes_usage.go#L508)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

The logic above looks good to me after some staring, though it would be nice to add some basic unit tests to cover the different cases here, explicitly checking that the `b.reserved` value is as expected after `SetMinAllocated` is called.
</blockquote></details>

I've added some tests to cover the different logic paths in `bytes_usage_test`.


<!-- Sent from Reviewable.io -->

2018-10-09 18:59 UTC, changangela reviewed
Updated the benchmark results in the comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LOPBWi5C9Z5FdGwfJf4:bsi6l2u)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-09 19:43 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LOPLiAq4QBT72XzafCs:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-10-09 19:47 UTC, changangela commented
bors r+

2018-10-09 20:00 UTC, merged

2018-10-09 21:03 UTC, knz commented
will look tomorrow

2018-10-10 11:04 UTC, knz reviewed
Friends, there are several things here that needs some additional work before I can even start to evaluate it for a backport.

I appreciate this is still early steps for Angela so please assume kindness in my words, I promise we'll take this easy and make it an opportunity to learn. Cheers!

The changes I am strongly suggesting (let me be honest, it's "requesting" at this point) can be brought in a separate PR. Ping me when that's created, I'll continue the discussion there. 

> Reviewed 2 of 5 files at r2, 1 of 4 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-:-LOS_lmt0y-lcNUD5HAR:bdfsk7l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/util/mon/bytes_usage.go, line 453 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOSa63N2fW92Lcj1-Sw:-LOSa63N2fW92Lcj1-Sx:b-2dj7k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L453)):*
> ```Go
> 	reserved int64
> 	// minAllocated is a minimum allocated bytes size that the account reach
> 	// before being able to release bytes.
> ```

This comment is: 

1) unclear about what this is trying to achieve (I don't understand the sentence)

2) is not in the right place: the comment above (for BoundAccount) and the comment above that (at the start of the file) must thoroughly document the "big picture" and the protocol to use these data structures. This PR is making a rather major change in the protocol, and it is therefore absolutely required to update the module doc to reflect this change. The extended commentS will need exampleS to 

   a) justify this change
   b) show how to use the new interface

3) the commentS you are going to use must describe more-or-less axiomatically the mathematical relationship between reserved, used, minAllocated, the size requested to the monitor so far. I don't see this relationship stated/specified anywhere, so I can't evaluate whether your code preserves the required invariants.

4) in general - this single one liner here is increasing the size of a pretty common data structure by 25%. I'd like to see alloc benchmarks beyond the single-use test you've added, for example a couple of the standard SQL benchmarks, to properly confirmed this addition is amortized throughout CockroachDB.
___
*[pkg/util/mon/bytes_usage.go, line 475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOSapwB5Co5Hj4Ag-mC:-LOSapwB5Co5Hj4Ag-mD:bqxw5ig) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L475)):*
> ```Go
> 
> // Allocated returns the total number of bytes which this account is using or
> // reserving
> ```

period missing.
___
*[pkg/util/mon/bytes_usage.go, line 486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOSavdq5JMaCaRid6Lp:-LOSavdq5JMaCaRid6Lq:bcrrttw) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L486)):*
> ```Go
> 
> // SetMinAllocated allocates a minimum Allocated size (reserved + used) for the
> // account. The account would not be able to Shrink() unless it has surpassed
> ```

"The account would not be able to ..."

1) what happens if one tries?

2) why is this restriction put in place? (see my comment above)
___
*[pkg/util/mon/bytes_usage.go, line 490 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOSb1fA2xtu09A2Ya5g:-LOSb1fA2xtu09A2Ya5h:b-avzyqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L490)):*
> ```Go
> func (b *BoundAccount) SetMinAllocated(ctx context.Context, size int64) error {
> 	if size < 0 {
> 		panic(fmt.Sprintf("%s: cannot set bound account min allocated to a negative value",
> ```

Don't use `panic` in functions that return `error`. Instead use `pgerror.NewErrorf(pgerror.CodeInternalError, "programming error: ...")`
___
*[pkg/util/mon/bytes_usage.go, line 493 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOSbJzv6ENLYircLwAJ:-LOSbJzv6ENLYircLwAK:bdiuufx) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L493)):*
> ```Go
> 			b.mon.name))
> 	}
> 	b.minAllocated = b.mon.roundSize(size)
> ```

You may have noticed that every function larger than ~10 LOCs in this file has comments in the body of the function to explain what is going on.

Aside (not specific to this code, but to give you insight into the culture): the purpose of exhaustive comments (and exhaustive commit messages, and PR descriptions) is not to just be nice and polite. The purpose is to establish a baseline about your own expectations (as a human) about what you (as a human) *intend* your code to do. Then the reviewer can *compare* your stated intent with the actual realization, and properly recognize any divergences as bugs.

The problem we're trying to avoid this way is when the code appears correct on its face but is not actually what you intended. Unless you tell us what you intend these bugs would survive review.

So yeah before I can review all this work I need a lot more explanation (in writing! in the code, commit message and PR description) about:
- what you're intending to do here, why you're intending it
- what you are doing and how you expect it to work
- how life is going to be different for users of this module from now on
___
*[pkg/util/mon/bytes_usage.go, line 661 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30924#-LOScFcW6yvf8SJ3Wbs4:-LOScFcW6yvf8SJ3Wbs5:b-u386as) ([raw file](https://github.com/cockroachdb/cockroach/blob/279c2d83f21e91c43dae1708b05eef3bb5704362/pkg/util/mon/bytes_usage.go#L661)):*
> ```Go
> // reserveBytes().
> func (mm *BytesMonitor) releaseBytes(ctx context.Context, sz int64) {
> 	if sz == 0 {
> ```

Please justify this conditional. When this code was designed, the sz = 0 case was sufficiently uncommon.

When you add a conditional on a hot path, you're making every call of that method pay the price of this conditional, even when the condition is rarely taken. The benefit when the condition is true must be so large that it properly outweighs/amortizes the cost paid on every other call. Is that the case here?


<!-- Sent from Reviewable.io -->

2018-10-10 13:52 UTC, changangela commented
Thanks @knz for the review! I am working on the changes and will create another PR.