sql: remove protobuf output from `show zone configurations`
cockroachdb/cockroach pull request #30985
Opened 2018-10-04 21:07 UTC by ridwanmsharif

This shouldn't be in the output for the 2.1 release,
the tests that use this to verify zone configs now
can use the `crdb_internal.zones` table.

Also as suggested by @knz we could change the name 
of the column from `cli_specifier` to `zone_name` but still
have an alias to the old name for backwards compat with the cli.
I haven't seen that done anywhere though, how can I do 
that exactly?

Release note: None

2018-10-04 21:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30985)
<!-- Reviewable:end -->

2018-10-04 21:34 UTC, benesch reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_zone_config.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LO0-44_5pgN-LMnClKP:-LO0-44aExhzBr_pAyB5:bohnzgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc55ace644154b983ca25161b9e73e296870174a/pkg/sql/show_zone_config.go#L54)):*
> ```Go
> // These must match crdb_internal.zones.
> var showZoneConfigNodeColumns = sqlbase.ResultColumns{
> 	{Name: "zone_id", Typ: types.Int},
> ```

Did we decide to keep the ID col?


<!-- Sent from Reviewable.io -->

2018-10-04 21:42 UTC, benesch commented
> I haven't seen that done anywhere though, how can I do
that exactly?

I'm not sure. Hopefully @knz knows. I think you might just have to output the cols twice: once for each name.

2018-10-05 17:06 UTC, knz reviewed
1) for the output of `delegateQuery` try using `planMutableColumns()` on the result and modify the name / hidden attribute in-place.

2) for having both `cli_specifier` and `zone_name` contain the same data in `show all zone configs` you need to do something clever between `generateZoneConfigIntrospectionValues`, `showZoneConfigNode` and the code for `crdb_internal.zones`. I think you can figure it out.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-:-LO4ApOaCJNY2ApbHSnx:bfmxklt)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_zone_config.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LO4Acz42zWxVQy4BNO2:-LO4Acz50TOuXdG0pVCl:b-jd7eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee458a486985a708e7d7a223b7631e7c54293669/pkg/sql/show_zone_config.go#L43)):*
> ```Go
> 	if n.ZoneSpecifier == (tree.ZoneSpecifier{}) {
> 		return p.delegateQuery(ctx, "SHOW ZONE CONFIGURATIONS",
> 			`SELECT cli_specifier, config_sql
> ```

try this `select cli_specifier as zone_name, cli_specifier, `...

(but you still have to figure out the right way to hide a column for results of `delegateQuery`).


<!-- Sent from Reviewable.io -->

2018-10-08 01:24 UTC, ridwanmsharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_zone_config.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LO0-44_5pgN-LMnClKP:-LOGFxoC7EtW69Y_EAxV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc55ace644154b983ca25161b9e73e296870174a/pkg/sql/show_zone_config.go#L54)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Did we decide to keep the ID col?
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LO4Acz42zWxVQy4BNO2:-LOGFzj58Rv3rkcaTfRE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee458a486985a708e7d7a223b7631e7c54293669/pkg/sql/show_zone_config.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

try this `select cli_specifier as zone_name, cli_specifier, `...

(but you still have to figure out the right way to hide a column for results of `delegateQuery`).
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGFBo69Pz5hrbN6-w-:-LOGFBo69Pz5hrbN6-w0:bwmk9wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/sql/show_zone_config.go#L49)):*
> ```Go
> 			return planRenderNode, err
> 		}
> 		planRenderNode.(*renderNode).columns[1].Hidden = true
> ```

We were wondering if this ad-hoc way of updating the `hidden` attribute of the column is an acceptable way of proceeding @knz ? It gives us the desired behavior and doesn't break backwards compatibility with the cli.


<!-- Sent from Reviewable.io -->

2018-10-08 02:13 UTC, benesch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> assuming @knz is happy with the column-hiding approach. Thanks again for doing this last-minute work!

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-:-LOGRsIoEjvYV26IBKgs:bx2ilko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/partitionccl/partition_test.go, line 1306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGRmKb1ILZODpdlCf6:-LOGRmKb1ILZODpdlCf7:bxuehc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/ccl/partitionccl/partition_test.go#L1306)):*
> ```Go
> 					newPartitionNames[name] = struct{}{}
> 				}
> 				rows := sqlDB.QueryStr(t, "SELECT zone_name FROM [SHOW ALL ZONE CONFIGURATIONS] WHERE cli_specifier IS NOT NULL")
> ```

This is just to avoid relying on a hidden column, right? That is, the query still works correctly as it was written before, right?


<!-- Sent from Reviewable.io -->

2018-10-08 03:35 UTC, ridwanmsharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/partitionccl/partition_test.go, line 1306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGRmKb1ILZODpdlCf6:-LOGjJFq0bdGB23efafK:b-g1h21f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/ccl/partitionccl/partition_test.go#L1306)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is just to avoid relying on a hidden column, right? That is, the query still works correctly as it was written before, right?
</blockquote></details>

That's correct. I also just changed it back to be completely clear that it works the old way. No reason yet that we should change all the tests right now. We can do that once we drop support for the old way.


<!-- Sent from Reviewable.io -->

2018-10-08 03:49 UTC, benesch reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/partitionccl/partition_test.go, line 1306 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGRmKb1ILZODpdlCf6:-LOGmldv2mg1q-9ZGSlt:b-vqxh0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/ccl/partitionccl/partition_test.go#L1306)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

That's correct. I also just changed it back to be completely clear that it works the old way. No reason yet that we should change all the tests right now. We can do that once we drop support for the old way.
</blockquote></details>

Ack. I'm perfectly happy for you to upgrade any of these tests as you see fit, now or later. Just wanted to be sure you weren't doing so out of necessity.


<!-- Sent from Reviewable.io -->

2018-10-08 03:50 UTC, benesch reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-10-08 09:12 UTC, knz requested changes
Thanks for this work.

Only a few minor details and this will be good to go.

Also a release note should be populated for this change.

> Reviewed 7 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-:-LOHwb2G43sxOYWH24HX:bef4k08)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/crdb_internal.go, line 1684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwSrJ35bez5B7F34u:-LOHwSrJ35bez5B7F34v:beh3ep4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/crdb_internal.go#L1684)):*
> ```Go
>   zone_id          INT NOT NULL,
>   zone_name        STRING,
>   cli_specifier    STRING,
> ```

add a comment on cli_specifier to indicate it is deprecated in favor of zone_name.
___
*[pkg/sql/show_zone_config.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGFBo69Pz5hrbN6-w-:-LOHw4bu8sM5TNsQaAOw:b-i5oly2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/sql/show_zone_config.go#L49)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

We were wondering if this ad-hoc way of updating the `hidden` attribute of the column is an acceptable way of proceeding @knz ? It gives us the desired behavior and doesn't break backwards compatibility with the cli.
</blockquote></details>

use `planMutableColumns()`, as I indicated before.
___
*[pkg/sql/show_zone_config.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwXR-8a4bCkmHb5lZ:-LOHwXR-8a4bCkmHb5l_:b-1smknf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/show_zone_config.go#L43)):*
> ```Go
> 	if n.ZoneSpecifier == (tree.ZoneSpecifier{}) {
> 		planRenderNode, err := p.delegateQuery(ctx, "SHOW ZONE CONFIGURATIONS",
> 			`SELECT cli_specifier as zone_name, cli_specifier, config_sql
> ```

"AS" in capitals.
___
*[pkg/sql/show_zone_config.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwCOb5iPTnf_FQIE8:-LOHwCOb5iPTnf_FQIE9:b-755eqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/show_zone_config.go#L130)):*
> ```Go
> ) error {
> 	// Populate the ID column.
> 	values[0] = zoneID
> ```

replace the indices into `values` by a suitable enum defined alongside `showZoneConfigNodeColumns` above.


<!-- Sent from Reviewable.io -->

2018-10-08 14:59 UTC, ridwanmsharif reviewed
@knz made the changes you requested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-:-LOJAieACQXkmLTz8EVF:bghz038)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/crdb_internal.go, line 1684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwSrJ35bez5B7F34u:-LOJAaEc5-vNfyy2SKtM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/crdb_internal.go#L1684)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

add a comment on cli_specifier to indicate it is deprecated in favor of zone_name.
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOGFBo69Pz5hrbN6-w-:-LOJAc3ID6rZQZvRaE_T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f03db0ec49cf122da694adcc1f77ed368417fd5/pkg/sql/show_zone_config.go#L49)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

use `planMutableColumns()`, as I indicated before.
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwXR-8a4bCkmHb5lZ:-LOJAbBV4mxTybdCR8HB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/show_zone_config.go#L43)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"AS" in capitals.
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwCOb5iPTnf_FQIE8:-LOJAdOM6iivz4i-jub1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/show_zone_config.go#L130)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

replace the indices into `values` by a suitable enum defined alongside `showZoneConfigNodeColumns` above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-08 16:28 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with nits

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-:-LOJV_MS5asba5c0oV8m:bfmeux1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/crdb_internal.go, line 1684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwSrJ35bez5B7F34u:-LOJV3ci6F9GwUH9BGSc:b-wrlqk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/crdb_internal.go#L1684)):*
<details><summary><i>Previously, ridwanmsharif (Ridwan Sharif) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: you can add the comment as a SQL comment on the right of the column (like the one on config_sql below)
___
*[pkg/sql/show_zone_config.go, line 51 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVEms0cuwX5-DXY1z:-LOJVEms0cuwX5-DXY2-:bjr4czv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L51)):*
> ```Go
> 
> 		// Using planMutableColumns to hide the cli_specifier column,
> 		// that needs to be supported for backwards copatibility with
> ```

*compatibility
___
*[pkg/sql/show_zone_config.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVFdwBRpVbnQrxgft:-LOJVFdx6upw-RYsd--E:b-z07aj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L54)):*
> ```Go
> 		// the CLI.
> 		columns := planMutableColumns(planRenderNode)
> 		columns[1].Hidden = true
> ```

Use the new enum to index the thing.
___
*[pkg/sql/show_zone_config.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVI-49xP30X2WN32H:-LOJVI-49xP30X2WN32I:b-ppdjo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L75)):*
> ```Go
> // These must match showZoneConfigColumns.
> const (
> 	zoneIDCol         int = 0
> ```

nit/tip: it's idiomatic Go to write

```go
zoneIDCol int = iota
zoneNameCol
cliSpecifier
...
```


<!-- Sent from Reviewable.io -->

2018-10-08 17:06 UTC, ridwanmsharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30985)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/crdb_internal.go, line 1684 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOHwSrJ35bez5B7F34u:-LOJdF_k4WZnqb34ndOo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb5a36ba79f50b65a7d956b78e18944db962b694/pkg/sql/crdb_internal.go#L1684)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: you can add the comment as a SQL comment on the right of the column (like the one on config_sql below)
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 51 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVEms0cuwX5-DXY1z:-LOJdHSfAbp-qP2K8baO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

*compatibility
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVFdwBRpVbnQrxgft:-LOJdISO6O0bdy0JoMRk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L54)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Use the new enum to index the thing.
</blockquote></details>

Done.
___
*[pkg/sql/show_zone_config.go, line 75 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/30985#-LOJVI-49xP30X2WN32H:-LOJdJOo9myxjrODSmvA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a631be0a18409c76fc5f905052538767186c66fe/pkg/sql/show_zone_config.go#L75)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit/tip: it's idiomatic Go to write

```go
zoneIDCol int = iota
zoneNameCol
cliSpecifier
...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-08 17:07 UTC, ridwanmsharif commented
bors r+

2018-10-08 17:32 UTC, merged