storage: don't serve requests on RHS after a merge commits
cockroachdb/cockroach pull request #30986
Opened 2018-10-04 21:14 UTC by benesch

Previously, it was possible for the leaseholder of the right-hand side
of a merge to erroneously serve requests after the merge committed. This
would occur when the RHS's watcher goroutine noticed that a merge
committed before the LHS on that store applied the merge commit trigger.
In this case, the watcher goroutine would unblock traffic, but that
traffic would be served normally because the RHS would not be marked as
destroyed. In effect, the watcher goroutine was assuming that the RHS
would always be marked as destroyed before it discovered that the merge
had committed, but there is no such guarantee.

The fix is to teach the watcher goroutine to mark the replica as
destroyed if the merge has committed before unblocking traffic.

With the fix in place, TestStoreRangeMergeRHSLeaseExpiration is no
longer flaky. For good measure, add a new test,
TestStoreRangeMergeWatcher, which more reliably reproduces the
consistency violation.

Fix #30349.

Release note: None

2018-10-05 13:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/30986)
<!-- Reviewable:end -->

2018-10-05 14:08 UTC, tbg requested changes
Looks good to me, just some comments to make sure we're getting things right.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-:-LO3YOZ7C2FWNoDVDFeL:b-u2fufg)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO3XgQP-DDijctpNaVI:-LO3XgQP-DDijctpNaVJ:bar8cq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c709ca46879db4b0e499e8f5bbc042184fda6089/pkg/storage/replica.go#L2932)):*
> ```Go
> 			// definitely committed.
> 			mergeCommitted = true
> 		case roachpb.ABORTED:
> ```

Wow, lots of code here. I agree that it's all needed, but having these two paths is awkward (also makes me wonder whether it's really all tested), perhaps we can just always hit meta? I know there's a scaling concern here, but it might be one of those that remain forever theoretical. Also (and we have to test that stuff), is there some case where the meta range you're pinging here is the range itself and it just deadlocks?
___
*[pkg/storage/replica.go, line 2995 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO3Yg8r3D8LOXglxxn2:-LO3Yg8r3D8LOXglxxn3:b-i5t6dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c709ca46879db4b0e499e8f5bbc042184fda6089/pkg/storage/replica.go#L2995)):*
> ```Go
> 		// error. If the merge aborted, the requests will be handled normally.
> 		r.mu.mergeComplete = nil
> 		close(mergeCompleteCh)
> ```

Everyone blocked on this checks the destroyStatus after this point, right?


<!-- Sent from Reviewable.io -->

2018-10-05 15:50 UTC, benesch reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO3XgQP-DDijctpNaVI:-LO3rPqA8nCQECN-ooCI:b-d3c2rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c709ca46879db4b0e499e8f5bbc042184fda6089/pkg/storage/replica.go#L2932)):*
Coverage is actually quite good. I made it just a little bit better by injecting failures into the push txn and get requests. Here's the coverage report:

https://rawgit.com/benesch/48af9b89aa4f588cc4ead5e92c7f7585/raw/0c3a33ba7500a5d55b9add6546e315dfbd044753/coverage.html#file27

I'm going to add a test case shortly to hit one last branch that isn't covered.

> perhaps we can just always hit meta? I know there's a scaling concern here, but it might be one of those that remain forever theoretical.

That introduces its own complexities, though. Ideally, we'd just do a consistent read from meta2. That would both wait for the merge txn to complete, by waiting for its intent to get resolved, and tell you how that intent was resolved! But I tried that, and you can end up deadlocking on yourself. See https://github.com/cockroachdb/cockroach/blob/69ce79fe832e5a26b577b50b4310909e070bb482/pkg/storage/client_merge_test.go#L995-L1032.

So, ok, you can poll meta2 with at the READ_UNCOMMITTED iso level instead. But how do you know when to stop polling? You can't just wait for the intent to disappear, because the intent might never disappear if the coordinator dies immediately after laying down the meta2 intent. The txn record will get GC'd without knowledge of the meta2 intent, and nothing will ever come looking for it. So you'd need to do some sort of intent resolution yourself. And I think that's at least as complex, if not more complex, than this solution.

> Also (and we have to test that stuff), is there some case where the meta range you're pinging here is the range itself and it just deadlocks?

Yep. The plan is to just disallow meta2 merges. I know we're getting down to the wire, but this is in my queue. https://github.com/cockroachdb/cockroach/issues/28886
___
*[pkg/storage/replica.go, line 2995 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO3Yg8r3D8LOXglxxn2:-LO3rPFQ6bFCvrzLs-eG:bb77uci) ([raw file](https://github.com/cockroachdb/cockroach/blob/c709ca46879db4b0e499e8f5bbc042184fda6089/pkg/storage/replica.go#L2995)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Everyone blocked on this checks the destroyStatus after this point, right?
</blockquote></details>

Yep!


<!-- Sent from Reviewable.io -->

2018-10-05 15:55 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-:-LO3w6VV7vbKWA_xiB_x:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 2932 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO3XgQP-DDijctpNaVI:-LO3voNb4DTvnWvL8RwI:b6rgr0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c709ca46879db4b0e499e8f5bbc042184fda6089/pkg/storage/replica.go#L2932)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Coverage is actually quite good. I made it just a little bit better by injecting failures into the push txn and get requests. Here's the coverage report:

https://rawgit.com/benesch/48af9b89aa4f588cc4ead5e92c7f7585/raw/0c3a33ba7500a5d55b9add6546e315dfbd044753/coverage.html#file27

I'm going to add a test case shortly to hit one last branch that isn't covered.

> perhaps we can just always hit meta? I know there's a scaling concern here, but it might be one of those that remain forever theoretical.

That introduces its own complexities, though. Ideally, we'd just do a consistent read from meta2. That would both wait for the merge txn to complete, by waiting for its intent to get resolved, and tell you how that intent was resolved! But I tried that, and you can end up deadlocking on yourself. See https://github.com/cockroachdb/cockroach/blob/69ce79fe832e5a26b577b50b4310909e070bb482/pkg/storage/client_merge_test.go#L995-L1032.

So, ok, you can poll meta2 with at the READ_UNCOMMITTED iso level instead. But how do you know when to stop polling? You can't just wait for the intent to disappear, because the intent might never disappear if the coordinator dies immediately after laying down the meta2 intent. The txn record will get GC'd without knowledge of the meta2 intent, and nothing will ever come looking for it. So you'd need to do some sort of intent resolution yourself. And I think that's at least as complex, if not more complex, than this solution.

> Also (and we have to test that stuff), is there some case where the meta range you're pinging here is the range itself and it just deadlocks?

Yep. The plan is to just disallow meta2 merges. I know we're getting down to the wire, but this is in my queue. https://github.com/cockroachdb/cockroach/issues/28886
</blockquote></details>

Thanks for the additional color, that looks good. Carry on. Disallowing m2 merges sounds fine for 2.1. Doubt we'll need them for quite some time to come (though I hope we can iron them out while you're still in this area).


<!-- Sent from Reviewable.io -->

2018-10-05 16:28 UTC, tschottdorf commented
Oh - one more request - can you stress the crap out of the new/altered test before you merge?

2018-10-05 20:57 UTC, benesch reviewed
I added a new test case for the one branch I hadn't covered... and it caught a segfault. Whoops. The test is rather involved—would you mind taking a quick look? 

Stress is looking good after a few minutes. I'll let it run for 30+ before I merge. (I'll also wait for your re-review, of course.)

> Dismissed @tschottdorf from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-:-LO5-xem6-HkpoV9Rluc:b3ht33j)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 2210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO5-bHyBk_HvaSDRNGD:-LO5-bHyBk_HvaSDRNGE:b-x97vd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/06255e58d6de5d3c68447779ed2ee6a695085448/pkg/storage/client_merge_test.go#L2210)):*
> ```Go
> 	if atomic.LoadInt64(&sawMeta2Req) != 1 {
> 		t.Fatalf("test did not generate expected meta2 get request/response")
> 	}
> ```

This test is long and involved, but it caught a segfault, so I think it's worth keeping.
___
*[pkg/storage/replica.go, line 2966 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO5-d3S9HLUDFURKHfl:-LO5-d3S9HLUDFURKHfm:b-rekf37) ([raw file](https://github.com/cockroachdb/cockroach/blob/827907d357936239bef5491fb91668542771960a/pkg/storage/replica.go#L2966)):*
> ```Go
> 				break
> 			}
> 			if getRes.Value.RawBytes == nil {
> ```

When a Get request does not find a value, `getRes.Value` is nil. Not `getRes.Value.RawBytes`, as the comment on `roachpb.GetResponse` would have you believe. I've fixed the comment.


<!-- Sent from Reviewable.io -->

2018-10-06 09:10 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> very happy about this test coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-:-LO7d821790HcSf5xTSx:b-jjm3is)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 2080 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO7byZU3510qH_I6sJn:-LO7byZVD5M8rJs4kjbZ:b-81eq6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/06255e58d6de5d3c68447779ed2ee6a695085448/pkg/storage/client_merge_test.go#L2080)):*
> ```Go
> // merge occurs.
> //
> // This test is a more complicated version of TestSToreRangeMergeWatcher that
> ```

STore


<!-- Sent from Reviewable.io -->

2018-10-08 04:16 UTC, benesch reviewed
TFTR!

bors r=tschottdorf

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-:-LOGsuG31tdt0wOTFkBT:b5yfumx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 2080 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LO7byZU3510qH_I6sJn:-LOGsYE3BgWy6UsP-SV_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06255e58d6de5d3c68447779ed2ee6a695085448/pkg/storage/client_merge_test.go#L2080)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

STore
</blockquote></details>

Done.
___
*[pkg/storage/client_merge_test.go, line 2100 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30986#-LOGscEk0YfcVjUmdCQU:-LOGscEk0YfcVjUmdCQV:b-hsvxf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/04345777caf7658b974a43e71ee3cfee4aedd492/pkg/storage/client_merge_test.go#L2100)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	t.Skip("flawed test: deadlocks if merge transaction retries")
> ```

Naturally, this test is great at timing out under race. Equally naturally, our PR stresser doesn't catch it because its timeout is 25m and the PR stresser only runs stress for 5m. Sigh. I don't have time to fix it right now but I really want to get this into the next v2.1 release, so I'm just going to merge with the test skipped. 


<!-- Sent from Reviewable.io -->

2018-10-08 04:41 UTC, merged