workload/ycsb: add support for uniform load distribution
cockroachdb/cockroach pull request #31155
Opened 2018-10-09 19:22 UTC by m-schneider

Previously we could only run YCSB with a zipfian distribution, now we'll
be able to use a default uniform distribution.

Closes #30996

Release note: None

2018-10-10 05:11 UTC, nvb requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LORNKCMBZ2A5G5Pfnd3:bw4z117) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
> ```Go
> 	mu       syncutil.Mutex
> 	r        *rand.Rand
> 	sequence uint64
> ```

I'm a little confused about this sequence number. Should we be setting it initially? Are we going to repeatedly call `IncrementIMax()` until its where we want it? Does it need to be dynamic or can we just set it once?
___
*[pkg/workload/ycsb/uniform_generator.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORMIFjEyj2H7PY5W8L:-LORMIFjEyj2H7PY5W8M:b-yljy2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L48)):*
> ```Go
> }
> 
> // IncrementIMax increments, iMax, and recompute the internal values that depend
> ```

Don't need the commas in here.
___
*[pkg/workload/ycsb/ycsb.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLQbE3Mr2Vs36NcZr:-LORLQbE3Mr2Vs36NcZs:b-wczsv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L242)):*
> ```Go
> 	if strings.ToLower(g.distribution) == "zipfian" {
> 		randGen, err = NewZipfGenerator(
> 			zipfRng, zipfIMin, defaultIMax, defaultTheta, false) /* verbose */
> ```

Looks like the inline comment got messed up.
___
*[pkg/workload/ycsb/ycsb.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLN-T9xlQaT-Jyk5V:-LORLN-T9xlQaT-Jyk5W:bcnzn41) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L245)):*
> ```Go
> 	} else {
> 		randGen, err = NewUniformGenerator(zipfRng, zipfIMin)
> 	}
> ```

Let's throw an error if a different distribution is given.
___
*[pkg/workload/ycsb/ycsb.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLU0Q0rqu5bLoWYvL:-LORLU0Q0rqu5bLoWYvM:btbvvvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L268)):*
> ```Go
> }
> 
> type RandGenerator interface {
> ```

No need to export this.


<!-- Sent from Reviewable.io -->

2018-10-10 18:13 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LOTd1sABw3sEOPb2IBt:b-ugmblh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little confused about this sequence number. Should we be setting it initially? Are we going to repeatedly call `IncrementIMax()` until its where we want it? Does it need to be dynamic or can we just set it once?
</blockquote></details>

So this is technically more for when we get proper inserts working with both distributions. I'm using sequence as a row count.  I didn't want to touch the zipfian stuff as much as possible so I kept the function names.
___
*[pkg/workload/ycsb/uniform_generator.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORMIFjEyj2H7PY5W8L:-LOU8RHI0M2Jh2LNZgti:b-fsmmf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Don't need the commas in here.
</blockquote></details>

Changed the comment
___
*[pkg/workload/ycsb/ycsb.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLQbE3Mr2Vs36NcZr:-LOU8Uig8pIP09r1CPXW:b-q4e7c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L242)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like the inline comment got messed up.
</blockquote></details>

Hmm you're right the ) is on the wrong side.
___
*[pkg/workload/ycsb/ycsb.go, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLN-T9xlQaT-Jyk5V:-LOU9Dr28iSCK70tLJFz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L245)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's throw an error if a different distribution is given.
</blockquote></details>

Done.
___
*[pkg/workload/ycsb/ycsb.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORLU0Q0rqu5bLoWYvL:-LOU9MAfDpFLT78Zt-w7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/ycsb.go#L268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No need to export this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-10 18:19 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LOUBhFX8z9TjIJZlI6d:b-ba1pa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

So this is technically more for when we get proper inserts working with both distributions. I'm using sequence as a row count.  I didn't want to touch the zipfian stuff as much as possible so I kept the function names.
</blockquote></details>

But unlike the zipfian distribution, we don't give it an initial value, so how does this work when we're not inserting?


<!-- Sent from Reviewable.io -->

2018-10-10 18:32 UTC, m-schneider commented
___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LOUEpZ_EQWWhANoJMvT:b-g147kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

But unlike the zipfian distribution, we don't give it an initial value, so how does this work when we're not inserting?
</blockquote></details>

I'm passing it the initial number or rows. To support inserts the zipfian will need a similar mechanism.


<!-- Sent from Reviewable.io -->

2018-10-10 18:32 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOUD8J2C0q5xTmda4Le:-LOUD8J2C0q5xTmda4Lf:b-zcgn3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a6223a5e93d2b01c19469b90c13a5c026319af/pkg/workload/ycsb/uniform_generator.go#L12)):*
> ```Go
> type UniformGenerator struct {
> 	// The underlying RNG
> 	uniformGenMu UniformGeneratorMU
> ```

Could you use an anonymous struct here? i.e.
```
type UniformGenerator struct {
    minValue uint64
    mu struct {
        syncutil.Mutex
        r *rand.Rand
        ...
    }
}
```


<!-- Sent from Reviewable.io -->

2018-10-10 19:14 UTC, m-schneider commented
___
*[pkg/workload/ycsb/uniform_generator.go, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOUD8J2C0q5xTmda4Le:-LOUO_4h7fj3AJbyats3:bseuw2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/64a6223a5e93d2b01c19469b90c13a5c026319af/pkg/workload/ycsb/uniform_generator.go#L12)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you use an anonymous struct here? i.e.
```
type UniformGenerator struct {
    minValue uint64
    mu struct {
        syncutil.Mutex
        r *rand.Rand
        ...
    }
}
```
</blockquote></details>

Much cleaner.


<!-- Sent from Reviewable.io -->

2018-10-10 19:14 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LOUOXiKCNwd_TW77UQl:bv7emv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I'm passing it the initial number or rows. To support inserts the zipfian will need a similar mechanism.
</blockquote></details>

As the minimum value? Doesn't that mean that reads will never read existing data?


<!-- Sent from Reviewable.io -->

2018-10-10 19:42 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/uniform_generator.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LORNKCMBZ2A5G5Pfnd2:-LOUUqLP3sMvIbqolo7l:b8ef8u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ee91d9c631a32ab380f5f3f252a811bd39d416/pkg/workload/ycsb/uniform_generator.go#L20)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

As the minimum value? Doesn't that mean that reads will never read existing data?
</blockquote></details>

You're absolutely right! The min value is more as a lower bound for the random number generated for reads, however because the current zipfian generator isn't quite correct, it mods the result by the number of rows.


<!-- Sent from Reviewable.io -->

2018-10-11 18:09 UTC, m-schneider commented
___
*[pkg/workload/ycsb/ycsb.go, line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOZJGyD8yN1tDmCwFc8:-LOZJGyEDVM69iYBgAe_:bv0dtia) ([raw file](https://github.com/cockroachdb/cockroach/blob/7083ab2fddd95034c3607079c4e72e990e053c6a/pkg/workload/ycsb/ycsb.go#L355)):*
> ```Go
> 	// this should work. (Basically repeatedly drawing from the distribution until
> 	// a sufficiently low value is chosen, but with some complications.)
> 	rownum := yw.hashKey(yw.randGen.Uint64()) % uint64(yw.config.initialRows)
> ```

Tested the uniform distribution via roachtest, the only strange thing is this hashKey method. It's not in the original YCSB code. Do you know what this is?


<!-- Sent from Reviewable.io -->

2018-10-12 17:43 UTC, nvb reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/ycsb.go, line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOZJGyD8yN1tDmCwFc8:-LOdLzhs-LqBGGclZ3Nu:b-b72n56) ([raw file](https://github.com/cockroachdb/cockroach/blob/7083ab2fddd95034c3607079c4e72e990e053c6a/pkg/workload/ycsb/ycsb.go#L355)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Tested the uniform distribution via roachtest, the only strange thing is this hashKey method. It's not in the original YCSB code. Do you know what this is?
</blockquote></details>

No, I'm not sure about it. It's strange because it looks like we actually hash the random number twice - once here and once in `buildKeyName`. Can we just remove this entirely?


<!-- Sent from Reviewable.io -->

2018-10-15 14:32 UTC, m-schneider commented
___
*[pkg/workload/ycsb/ycsb.go, line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOZJGyD8yN1tDmCwFc8:-LOs7n7iB0qSRZyh0Odw:b-6nh4do) ([raw file](https://github.com/cockroachdb/cockroach/blob/7083ab2fddd95034c3607079c4e72e990e053c6a/pkg/workload/ycsb/ycsb.go#L355)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No, I'm not sure about it. It's strange because it looks like we actually hash the random number twice - once here and once in `buildKeyName`. Can we just remove this entirely?
</blockquote></details>

I'd be nervous moving it out because we could break the Zipfian distribution accidentally. Maybe I could pass the function to the distributions and have uniform ignore it and zipfian use it? When I ran uniform on 5 rows with it, it gave 0 and 4 as the only two choices.


<!-- Sent from Reviewable.io -->

2018-10-15 15:57 UTC, nvb reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31155)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/ycsb/ycsb.go, line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOZJGyD8yN1tDmCwFc8:-LOsR9P2Au6Kzu8rC5lh:b-9h9ypy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7083ab2fddd95034c3607079c4e72e990e053c6a/pkg/workload/ycsb/ycsb.go#L355)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I'd be nervous moving it out because we could break the Zipfian distribution accidentally. Maybe I could pass the function to the distributions and have uniform ignore it and zipfian use it? When I ran uniform on 5 rows with it, it gave 0 and 4 as the only two choices.
</blockquote></details>

Hashing twice is nonsensical though. I guess we can leave this for now and ask @arjunravinarayan when he's back. I'd just leave a TODO for now.


<!-- Sent from Reviewable.io -->

2018-10-15 18:19 UTC, m-schneider commented
___
*[pkg/workload/ycsb/ycsb.go, line 355 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31155#-LOZJGyD8yN1tDmCwFc8:-LOsx8p0DJN3Tf2H29RM:b-jlblw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7083ab2fddd95034c3607079c4e72e990e053c6a/pkg/workload/ycsb/ycsb.go#L355)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Hashing twice is nonsensical though. I guess we can leave this for now and ask @arjunravinarayan when he's back. I'd just leave a TODO for now.
</blockquote></details>

Yep agreed, added the TODO.


<!-- Sent from Reviewable.io -->

2018-10-15 18:48 UTC, nvb approved these changes

2018-10-15 20:43 UTC, m-schneider commented
bors r+

2018-10-15 20:57 UTC, merged