opt: Change Memo data structures
cockroachdb/cockroach pull request #31173
Opened 2018-10-10 01:13 UTC by andy-kimball

Change how the Memo stores groups and expressions. Currently, both
are stored in Go slices which are resized as new groups and expressions
are added to the memo. Expressions store GroupIDs and PrivateIDs, which
are indexes into slices holding memo groups and expression-specific  data.

While this design has worked OK, it has several downsides:

  1. There is very little type safety, since all expressions are stored
     in identical 16 byte structs so they can be packed into slices.
     This can also make debugging tedious, as the debugger does not
     know how to decode the expressions.

  2. Expressions can have only 3 fields, since we pack them into 16
     bytes. For many operators this is fine, but it requires awkward
     workarounds for operators than need >3 fields.

  3. Many nodes have "private" data fields that require the allocation
     of a separate object to store. This cancels what would otherwise
     be an advantage of the current design, since it ends up allocating
     about the same number of objects as the new design for this and
     other reasons. It also requires tedious calls to InternPrivate
     and LookupPrivate methods in order to map to and from slice
     indexes.

  4. When the optimizer decides on a lowest cost expression tree, it
     must store that information "off to the side" in BestExpr
     structures so that ExprView knows which of the trees in the forest
     to traverse. This triggers additional allocations.

  5. Traversal of the tree requires an auxiliary ExprView data structure
     that holds onto context necessary for the traversal (i.e. the Memo).
     This makes the current design harder to understand and use.

  6. All expressions allocate and store logical properties. While this is
     necessary for relational expressions, it is not required for most
     scalar operators.

  7. The memo expression storage format is not compatible with nodes used
     in other parts of Cockroach, like AST and planNodes. This makes mixing
     and matching nodes difficult, and requires "wrapper" nodes to map
     between different representations.

The new memo expression representation solves these problems using a more
natural Go-friendly design. Each expression is a differently-typed Go
struct that implements the Expr interface:
```
  type Expr interface {
    Op() Operator
    ChildCount() int
    Child(nth int) Expr
    Private() interface{}
    String() string
  }
```
This is similar to how AST nodes and planNodes work. Optgen generates a
struct definition for each operator, as well as implementations for the
Expr interface methods. Private values are stored inline in the structs,
replacing the need for an additional allocation. Expressions can be
constructed using a very natural factory interface with no explicit
interning required.

Where it gets more interesting is for relational expressions, which are
part of memo groups that can contain multiple logically equivalent
expressions. The new representation links together expressions in the
same group using "next" pointers. In addition, the first expression in
the memo is allocated with extra inline storage to store relational and
physical properties. This avoids separate allocation for the properties
like the current representation requires. For a simple expression tree
with 1 expression per group, the tree requires just 1 object per memo
group.

Here are numbers for the old vs. new representations:
```
name                               old time/op  new time/op  delta
Phases/kv-read/ExecBuild           15.5µs ± 3%  10.7µs ± 3%  -31.03%  (p=0.008 n=5+5)
Phases/kv-read-no-prep/ExecBuild   38.1µs ± 3%  33.4µs ± 2%  -12.14%  (p=0.008 n=5+5)
Phases/kv-read-const/ExecBuild      682ns ± 2%   622ns ± 2%   -8.71%  (p=0.008 n=5+5)
Phases/tpcc-new-order/ExecBuild    53.2µs ± 5%  35.4µs ± 3%  -33.41%  (p=0.008 n=5+5)
Phases/tpcc-delivery/ExecBuild     38.9µs ± 3%  23.8µs ± 5%  -38.72%  (p=0.008 n=5+5)
Phases/tpcc-stock-level/ExecBuild   167µs ± 2%   114µs ± 3%  -31.34%  (p=0.008 n=5+5)
Exec/kv-read/ExecPlan               197µs ± 2%   193µs ± 2%     ~     (p=0.056 n=5+5)
Exec/kv-read/ExecOpt                186µs ± 4%   189µs ± 3%     ~     (p=0.421 n=5+5)
Exec/kv-read-no-prep/ExecPlan       318µs ± 3%   315µs ± 2%     ~     (p=0.548 n=5+5)
Exec/kv-read-no-prep/ExecOpt        340µs ± 8%   327µs ± 1%   -4.00%  (p=0.016 n=5+5)
Exec/kv-read-const/ExecPlan         194µs ± 3%   192µs ± 2%     ~     (p=0.421 n=5+5)
Exec/kv-read-const/ExecOpt          161µs ± 3%   161µs ± 4%     ~     (p=1.000 n=5+5)
Exec/tpcc-new-order/ExecPlan        301µs ± 8%   268µs ± 2%  -10.81%  (p=0.008 n=5+5)
Exec/tpcc-new-order/ExecOpt         269µs ± 1%   261µs ± 3%   -3.09%  (p=0.032 n=5+5)
Exec/tpcc-delivery/ExecPlan         243µs ± 2%   253µs ± 9%     ~     (p=0.690 n=5+5)
Exec/tpcc-delivery/ExecOpt          242µs ± 1%   245µs ± 6%     ~     (p=0.690 n=5+5)
Exec/tpcc-stock-level/ExecPlan      545µs ± 2%   525µs ± 2%   -3.53%  (p=0.008 n=5+5)
Exec/tpcc-stock-level/ExecOpt       532µs ± 3%   501µs ± 3%   -5.79%  (p=0.008 n=5+5)
```

2018-10-10 01:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31173)
<!-- Reviewable:end -->

2018-10-11 14:52 UTC, justinj reviewed
I looked through `optbuilder` and `execbuilder` changes, mostly seems pretty mechanical as far as those two packages go. I'll look through more of the rest of the changes later.

> Reviewed 8 of 92 files at r2, 9 of 23 files at r5, 6 of 21 files at r8, 7 of 197 files at r9, 11 of 22 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LOYaxQI8nG2C2YDzf0Z:b-28ojb4)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 398 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOTX_DE8ERyyNts1cZR:-LOTX_DE8ERyyNts1cZS:be5vlh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/exec/execbuilder/relational_builder.go#L398)):*
> ```Go
> }
> 
> func (b *Builder) buildHashJoin(join memo.RelExpr) (execPlan, error) {
> ```

Did you consider making interfaces for these more specific subclasses of expressions, like this and GroupBys? Any reason you opted not to?
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 486 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOTvZcw7J8syfMiTarB:-LOTvZcw7J8syfMiTarC:b-v1dgyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/exec/execbuilder/testdata/explain#L486)):*
> ```
> ·       row 1, expr 2  (6)[int]           ·                                        ·
> 
> # TODO(rytaft): range operator needed to detect contradiction
> ```

is this test change a result of not having rebased yet?
___
*[pkg/sql/opt/optbuilder/scalar.go, line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOURkqZ-4II-8aqldPx:-LOURkqZ-4II-8aqldPy:bybuuz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/optbuilder/scalar.go#L110)):*
> ```Go
> 			els[i] = b.buildScalar(texpr, inScope, nil, nil, colRefs)
> 		}
> 		out = b.factory.ConstructArray(els, arrayType)
> ```

Did the fancy list storage not end up being a win in the long run? Or difficult to implement in this new representation?
___
*[pkg/sql/opt/optbuilder/scalar.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOUUgXF9Z38ymX2ri0_:-LOUUgXF9Z38ymX2ri0a:b32e7o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/optbuilder/scalar.go#L160)):*
> ```Go
> 				b.factory.ConstructScalarGroupBy(
> 					s.node,
> 					memo.AggregationsExpr{{
> ```

Why is this not `Construct`ed? Even if it's just a list underneath is that not an implementation detail?
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 894 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOY_FuH5Ra9aJY65fpb:-LOY_FuH5Ra9aJY65fpc:b-pixouu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9858934f2e50787a5984d308a63189cf0392f7f2/pkg/sql/opt/optbuilder/testdata/aggregate#L894)):*
> ```
>  │         ├── scan kv
>  │         │    └── columns: kv.k:5(int!null) kv.v:6(int) kv.w:7(int) kv.s:8(string)
>  │         └── filters
> ```

nit (doesn't need to be part of this PR): it would probably be helpful if an empty `filters` was more obviously a constant `True`, this makes sense if you know that `filters` is basically `and`, but someone not familiar with opt inspecting these tests might be confused.
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 2800 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOY_k_69OqyHrtMml6Y:-LOY_k_69OqyHrtMml6Z:b-vrkejj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9858934f2e50787a5984d308a63189cf0392f7f2/pkg/sql/opt/optbuilder/testdata/aggregate#L2800)):*
> ```
> SELECT 123 r FROM kv ORDER BY max(v)
> ----
> project
> ```

why did this plan change? is this a rebasing thing?


<!-- Sent from Reviewable.io -->

2018-10-12 15:12 UTC, RaduBerinde commented
Hi Andy,

I put an initial set of comments for the `memo` part here, as a diff (comments usually refer to the line below): https://gist.github.com/RaduBerinde/a3d238f44495b1822bc88fb77f6b1880

Feel free to comment in that gist, I think that's easier than interleaving all discussions in this PR.

2018-10-15 15:03 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 398 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOTX_DE8ERyyNts1cZR:-LOs9Fm0AyUNW-VUh584:bffy580) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/exec/execbuilder/relational_builder.go#L398)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Did you consider making interfaces for these more specific subclasses of expressions, like this and GroupBys? Any reason you opted not to?
</blockquote></details>

Each interface requires a more casting back and forth, and more complications when generating code. I'd only do it if I had additional methods that were useful to add (like `DataType` for `ScalarExpr` or `NextExpr` for `RelExpr`). Too much polymorphism can be more trouble than its worth, and I decided to draw the line here as a compromise.
___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 486 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOTvZcw7J8syfMiTarB:-LOsA7YM2LBDMJl5NExV:b-udvq99) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/exec/execbuilder/testdata/explain#L486)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is this test change a result of not having rebased yet?
</blockquote></details>

Yes, should be gone now.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOURkqZ-4II-8aqldPx:-LOsAF5M1OezX99_H9ns:btk9jlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/optbuilder/scalar.go#L110)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Did the fancy list storage not end up being a win in the long run? Or difficult to implement in this new representation?
</blockquote></details>

I ran into a bunch of issues when considering what to intern. I ended up deciding it's best to not intern the list types *or* the list item types.

1. Lists are now represented as typed slices, which would be painful to intern, since we'd need a different list storage implementation for each list item type (`FiltersItem`, `ProjectionsItem`, etc).
2. I don't know how to intern slices in the same way as we were interning lists before. Before, we had a level of indirection in the form of a `ListID`. Now, we just have a regular Go slice. We wouldn't be able to store slices in one larger slice, because we have no way of updating underlying pointers when the larger slice is resized.
3. If we attempted to intern list expressions (`FiltersExpr`, `ProjectionsExpr`, etc.) rather than slices of items, then we'd trigger additional allocations, since we'd have to allocate slice headers on the heap (i.e. `*FiltersExpr`).
4. We can't intern list item expressions (`FiltersItem`, `ProjectionsItem`), because they are inlined into their parent slice.
5. We have many rules that rewrite lists, and today it's expensive to have to re-intern the entire list just in order to remove or replace a list item. I felt like we should just exclude list and list item types entirely from interning.
___
*[pkg/sql/opt/optbuilder/scalar.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOUUgXF9Z38ymX2ri0_:-LOsDX8M0iGjCCIQbMnv:b-bxuko8) ([raw file](https://github.com/cockroachdb/cockroach/blob/368f25ed40e5530167fe774a2d7705af4f12c174/pkg/sql/opt/optbuilder/scalar.go#L160)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Why is this not `Construct`ed? Even if it's just a list underneath is that not an implementation detail?
</blockquote></details>

I don't intern list or list item nodes; see above for explanation. Any `Construct` method would look different from all other `Construct` methods, because I want to avoid extra allocations:
```
ConstructAggregationsExpr(in memo.AggregationsExpr) memo.AggregationsExpr
```
Notice that these are not pointers to expressions, as with every other `Construct` method. Using pointers here would likely force the slice header onto the heap, as well as imply an expectation that the expressions would be interned. And if I don't use pointers, what would the `Construct` method do? Just be a dummy pass through? That possibility seemed strange to me.
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 894 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOY_FuH5Ra9aJY65fpb:-LOsEnWp5IzU1FdWhzHx:bjsgw8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9858934f2e50787a5984d308a63189cf0392f7f2/pkg/sql/opt/optbuilder/testdata/aggregate#L894)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit (doesn't need to be part of this PR): it would probably be helpful if an empty `filters` was more obviously a constant `True`, this makes sense if you know that `filters` is basically `and`, but someone not familiar with opt inspecting these tests might be confused.
</blockquote></details>

Yeah, I went back and forth on this. I could make it `true`, though it might lead to other confusion, since people might then think there's actually a `true` expression when there isn't. @radu, @rebecca, any opinion on this?
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 2800 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOY_k_69OqyHrtMml6Y:-LOsEq1o1CbDwiDz07oJ:b-2snq59) ([raw file](https://github.com/cockroachdb/cockroach/blob/9858934f2e50787a5984d308a63189cf0392f7f2/pkg/sql/opt/optbuilder/testdata/aggregate#L2800)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

why did this plan change? is this a rebasing thing?
</blockquote></details>

Yes, should be "no change" now that I've rebased.


<!-- Sent from Reviewable.io -->

2018-10-15 15:42 UTC, RaduBerinde commented
xform part LGTM, some minor comments: https://gist.github.com/RaduBerinde/1324028c377f85dbd051fcd797062f92

2018-10-15 16:54 UTC, RaduBerinde commented
___
*[pkg/sql/opt/optbuilder/testdata/aggregate, line 894 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOY_FuH5Ra9aJY65fpb:-LOsdDNY2s_I3QAme6L-:bk9uz74) ([raw file](https://github.com/cockroachdb/cockroach/blob/9858934f2e50787a5984d308a63189cf0392f7f2/pkg/sql/opt/optbuilder/testdata/aggregate#L894)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, I went back and forth on this. I could make it `true`, though it might lead to other confusion, since people might then think there's actually a `true` expression when there isn't. @radu, @rebecca, any opinion on this?
</blockquote></details>

I would make it show up as `no-filters` (or `filters (none)` or `filters (true)`)


<!-- Sent from Reviewable.io -->

2018-10-15 20:04 UTC, rytaft requested changes
Nice work! I've reviewed the Optgen change (r11), now looking at the norm change (r13).

> Reviewed 8 of 197 files at r9, 18 of 18 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LOtJO9h5uLkfkELC-pY:b-6i6phd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 99 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOs91-64f-rTGn9a63D:-LOs91-7CB6j5zZOBLfi:bw7fhzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L99)):*
> ```Go
> //   }
> //
> func (g *exprsGen) genGroupExpr(define *lang.DefineExpr) {
> ```

[nit] for consistency, maybe this should be `genGroupStruct`?
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 186 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOs9msv6MV6PGXiFFkO:-LOs9msv6MV6PGXiFFkP:b-xjiyuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L186)):*
> ```Go
> 	for _, field := range define.Fields {
> 		// If field's name is "_", then use Go embedding syntax.
> 		fieldName := g.md.fieldName(field)
> ```

you only need `fieldName` if `isEmbeddedField` is false
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 480 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsGlsp9BelQJfVrAao:-LOsGlsp9BelQJfVrAap:bmhmj6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L480)):*
> ```Go
> 
> 	// Generate the Op method.
> 	fmt.Fprintf(g.w, "func (e *%s) Op() opt.Operator {\n", opTyp.name)
> ```

Is there a benefit to having pointer receivers for slice types?
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 491 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsH5Za7R5rUoUIweWr:-LOsH5Za7R5rUoUIweWs:byhl4mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L491)):*
> ```Go
> 	// Generate the Child method.
> 	fmt.Fprintf(g.w, "func (e *%s) Child(nth int) opt.Expr {\n", opTyp.name)
> 	if opTyp.listItemType.isGenerated {
> ```

Why does `isGenerated` mean that it's a pointer type?
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 250 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsb6Lu4FJ6BJ8B4NNf:-LOsb6Lv5LbGX5wAhgjM:b-856gnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L250)):*
> ```Go
> 		} else {
> 			g.w.writeIndent("before := list[i]\n")
> 			g.w.writeIndent("after := replace(before).(opt.ScalarExpr)\n")
> ```

[nit] this line is redundant and can be moved out of the if block
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 358 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsuWPD-YWGJ0kD6GSQ:-LOsuWPECj0AjgBEYzgD:b-rboeov) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L358)):*
> ```Go
> 		if itemType.isGenerated {
> 			firstFieldName := g.md.fieldName(itemDefine.Fields[0])
> 			g.w.writeIndent("dst[i].%s = f.assignPlaceholders(src[i].%s).(opt.ScalarExpr)\n",
> ```

Why are we only assigning placeholders to the first field?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 220 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtFdat9Ah62aVK7fm7:-LOtFdat9Ah62aVK7fm8:bx2ekya) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L220)):*
> ```Go
> 		// Remove package prefix from types in the same package.
> 		if strings.HasPrefix(typ.fullName, pkg+".") {
> 			typ.name = typ.fullName[len(pkg)+1:]
> ```

what about pointers? don't you need an extra char in that case?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 248 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGAaDCwa7r2M91MLU:-LOtGAaDCwa7r2M91MLV:b-ooclrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L248)):*
> ```Go
> // fieldName maps the Optgen field name to the corresponding Go field name. In
> // particular, fields named "_" are mapped to the name of a Go embedded field,
> // which is equal to the field's type name.
> ```

does the type name include the package name?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 269 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGUwS3oADs5yudluO:-LOtGUwS3oADs5yudluP:b-sicby3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L269)):*
> ```Go
> // a private field and will not be returned.
> func (m *metadata) childFields(define *lang.DefineExpr) lang.DefineFieldsExpr {
> 	// Skip until non-node field is found.
> ```

non-expr?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 293 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGfYu9JIZOq52l_mI:-LOtGfYv-wU0apIMJnxV:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L293)):*
> ```Go
> // the operator, then privateField returns nil.
> func (m *metadata) privateField(define *lang.DefineExpr) *lang.DefineFieldExpr {
> 	// Skip until non-node field is found.
> ```

ditto
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 329 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtIx5336rTQEFybA0z:-LOtIx5336rTQEFybA1-:by14xn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L329)):*
> ```Go
> // Since SetPrivate values are passed by reference, they must be dereferenced
> // before copying them to a target field.
> func (m *metadata) fieldStorePrefix(field *lang.DefineFieldExpr) string {
> ```

Seems like you could have more helper functions like this to encapsulate some of the complexity elsewhere due to the `isPointer`, `isGenerated` and `passByVal` fields
___
*[pkg/sql/opt/optgen/cmd/optgen/ops_gen.go, line 21 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsddUl0jcXi5ewT-Je:-LOsddUm0EK0mYRREAXQ:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/ops_gen.go#L21)):*
> ```Go
> 	"fmt"
> 	"io"
> ```

[nit] extra line
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 57 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsfNx593WP4yxpmhlo:-LOsfNx6AAxcN-fmkR13:b7qw2d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L57)):*
> ```Go
> // like this instead:
> //
> //     _select := _innerJoin.(*SelectExpr)
> ```

Maybe you mean `_innerJoin.Left.(*SelectExpr)`?
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 184 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsgYFm7Dqa_l9a11iZ:-LOsgYFm7Dqa_l9a11i_:b-lyzfsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L184)):*
> ```Go
> //
> // In that example, the context starts out as "elems", which is the name of the
> // top-level Tuple oeprator fields that's being list matched. Then, the context
> ```

oeprator -> operator
fields -> field
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 187 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsgnwVAWnt6DJIWb3T:-LOsgnwWErLIp84B64YQ:b-a22wiq) ([raw file](https://github.com/cockroachdb/cockroa [...]

2018-10-15 23:58 UTC, andy-kimball commented
> I would make it show up as `no-filters` (or `filters (none)` or `filters (true)`)

Good idea, I like `filters (true)`.

2018-10-16 01:50 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 99 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOs91-64f-rTGn9a63D:-LOuAwHf3Fl1KAg4lOa9:b-4pr8wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L99)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] for consistency, maybe this should be `genGroupStruct`?
</blockquote></details>

I changed it to `genExprGroupDef` to be symmetric with `genExprDef`, since it's also generating methods.
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 186 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOs9msv6MV6PGXiFFkO:-LOuB7si2nGiQ3dJbmOX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L186)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

you only need `fieldName` if `isEmbeddedField` is false
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 480 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsGlsp9BelQJfVrAao:-LOuB8qbBEgSSChgR3DQ:b-wiy0cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L480)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there a benefit to having pointer receivers for slice types?
</blockquote></details>

They need to be that way. For example, the `Child` method of a `Select` operator needs to return `&e.Filters`, which is a pointer to a slice, rather than the slice itself. If we were to return the slice itself, it would force a heap allocation.
___
*[pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go, line 491 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsH5Za7R5rUoUIweWr:-LOuCzIMAwwj56P4BGJ8:b9pzdpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/exprs_gen.go#L491)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why does `isGenerated` mean that it's a pointer type?
</blockquote></details>

It's the other way around; if it's generated then it's a type like `FiltersItem` that's inlined in the slice, and so to get an `opt.Expr` we need to take the address of the slice entry.

However, that's not too clear, so I changed it to check `isPointer` instead (i.e. when list item type is `opt.ScalarExpr`).
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 250 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsb6Lu4FJ6BJ8B4NNf:-LOuDxKl7mzwBaeWMyJ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L250)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] this line is redundant and can be moved out of the if block
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/factory_gen.go, line 358 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsuWPD-YWGJ0kD6GSQ:-LOuE7dp2CPQaO8lFU0P:bu0moa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/factory_gen.go#L358)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why are we only assigning placeholders to the first field?
</blockquote></details>

I added a comment:
```
// All list item types generated by Optgen can have at most one input
// field (always the first field). Any other fields must be privates.
// And placeholders only need to be assigned for input fields.
```
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 220 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtFdat9Ah62aVK7fm7:-LOuEiexCMPO_MB4kZd9:bje8wzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L220)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what about pointers? don't you need an extra char in that case?
</blockquote></details>

None of the pointer types are in the packages into which we generate files. If that changes, it's easy enough to extend this code. I just don't like to handle cases that are impossible to test.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 248 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGAaDCwa7r2M91MLU:-LOuFISpDpVzv8oZgvlm:b-1bsxg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L248)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

does the type name include the package name?
</blockquote></details>

Optgen syntax does not allow that, since it only allows alphanumeric type names. I added more commentary on this.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 269 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGUwS3oADs5yudluO:-LOuGcfI91L_cF98IRFK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L269)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

non-expr?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 293 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGfYu9JIZOq52l_mI:-LOuGd4a4WZ3AyTeL33o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L293)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 329 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtIx5336rTQEFybA0z:-LOuGfeO7w55tDMS9TcU:bvxilcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L329)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like you could have more helper functions like this to encapsulate some of the complexity elsewhere due to the `isPointer`, `isGenerated` and `passByVal` fields
</blockquote></details>

I originally tried this, but it turns out that every case is unique, and so I was just calling them once. It felt even more confusing to have all these methods that looked almost the same, but were each different. I couldn't even figure out good names for them.
___
*[pkg/sql/opt/optgen/cmd/optgen/ops_gen.go, line 21 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsddUl0jcXi5ewT-Je:-LOuHMY0EI-hhvbfUsdL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/ops_gen.go#L21)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 57 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOsfNx593WP4yxpmhlo:-LOuHRVC5Zjp_mKCNCo_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/rule_gen.go#L57)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe you mean `_innerJoin.Left.(*SelectExpr)`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/cmd/optgen/rule_gen.go, line 184 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-L [...]

2018-10-16 13:49 UTC, rytaft requested changes
> Reviewed 18 of 18 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 220 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtFdat9Ah62aVK7fm7:-LOx3vMG0WJofIn-tX3X:b-nblz1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L220)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

None of the pointer types are in the packages into which we generate files. If that changes, it's easy enough to extend this code. I just don't like to handle cases that are impossible to test.
</blockquote></details>

Makes sense - maybe just add a comment so that's clear?
___
*[pkg/sql/opt/optgen/cmd/optgen/metadata.go, line 248 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOtGAaDCwa7r2M91MLU:-LOx4E_I2mRydCCwBgBo:b-wsixt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/metadata.go#L248)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Optgen syntax does not allow that, since it only allows alphanumeric type names. I added more commentary on this.
</blockquote></details>

This helps. Just a nit -- I think it would be better to change `=>` to say "gets compiled into" so it doesn't look so much like an optgen rule.
___
*[pkg/sql/opt/optgen/cmd/optgen/testdata/exprs, line 176 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOt-pKOEuT_5LVUxM1c:-LOx5pWt1Bd5iLoBdQHf:b39erxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/testdata/exprs#L176)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It's good that you thought about that. I added this comment to `Optimizer.setLowestCostTree` by way of explanation:
```
// Note that a memo group can have multiple lowest cost expressions, each for a
// different set of physical properties. During optimization, these are retained
// in the groupState map. However, only one of those lowest cost expressions
// will be used in the final tree; the others are simply discarded. This is
// because there is never a case where a relational expression is referenced
// multiple times in the final tree, but with different physical properties
// required by each of those references.
```
My entire rewrite is based on that statement being true. It turns out that we never reference a relational expression more than once, since that would mean reusing `ColumnID`s, which we can't do for other reasons. The only other case I could think of would be a relational expression with no columns (like `ScanExpr` with all cols pruned). But none of those expressions would ever provide any physical properties, so even if they were reused, an enforcer would be providing the properties (and those are always created as separate expressions).
</blockquote></details>

Got it - thanks for the explanation!
___
*[pkg/sql/opt/optgen/cmd/optgen/testdata/factory, line 221 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOt7CxK-wGH5HBpxvh8:-LOx6PkjAiBml4UQY6EC:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1bd5802cb3a0689a6dd29eddbd2f514aeb20be6/pkg/sql/opt/optgen/cmd/optgen/testdata/factory#L221)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`assignPlaceholders` does double-duty. It makes a copy of the memo at the same time it's assigning placeholders. Here's the comment on `Factory.AssignPlaceholders`:
```
// AssignPlaceholders is used just before execution of a prepared Memo. It makes
// a copy of the given memo, but with any placeholder values replaced by their
// assigned values. This can trigger additional normalization rules that can
// substantially rewrite the tree. Once all placeholders are assigned, the
// exploration phase can begin.
```
That said, it might be safe to reuse scalar subexpressions that have no placeholders *and* do not have subqueries. I'll have to think about that more. I'd do that in a follow-on PR, though, since it'd be a perf item, not a correctness issue.
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2018-10-16 22:01 UTC, rytaft requested changes
Still reviewing, but figured I'd post the comments I have so far.

> Reviewed 5 of 42 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LOytIswBhLCm5-ESIR3:bg7uwwh)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 390 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxDK1n8sWHUbgApZoq:-LOxDK1oCXFfXsdVJmr4:b-lc5f9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L390)):*
> ```Go
> }
> 
> // IsContradiction returns true if any of the given filter item contains a
> ```

any of the given -> the given
___
*[pkg/sql/opt/norm/custom_funcs.go, line 485 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxEkfe85mtAiuQtcsx:-LOxEkfe85mtAiuQtcsy:b-lpabmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L485)):*
> ```Go
> 	filters memo.FiltersExpr, cols opt.ColSet,
> ) memo.FiltersExpr {
> 	newFilters := make(memo.FiltersExpr, 0, len(filters)-1)
> ```

Is it true that we only call this function if there is at least one unbound condition? If so, add a comment to explain why the capacity is `len(filters)-1`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 501 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxF5kX1B0sqENeKq3P:-LOxF5kYDQu6RrRbTs66:b-gn9epo) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L501)):*
> ```Go
> 	filters memo.FiltersExpr, cols opt.ColSet,
> ) memo.FiltersExpr {
> 	newFilters := make(memo.FiltersExpr, 0, len(filters)-1)
> ```

Same here - the function should only be called if there is at least one bound condition.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 543 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxIbQI7nSt14ksB9W1:-LOxIU51CWRmL4BEAnYW:bwvfsn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L543)):*
> ```Go
> 	for i := range inner {
> 		item := &inner[i]
> 		if passthrough.Contains(int(item.Col)) {
> ```

It would be good to add a comment that the outer synthesized columns do not contain references to item since `CanMergeProjectsions` should have returned true.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 596 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxJvzrAMHN1iBXK4da:-LOxJvzrAMHN1iBXK4db:bf8tkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L596)):*
> ```Go
> }
> 
> // MakeEmptyColSet returns a column set with columns in it.
> ```

with columns -> with no columns
___
*[pkg/sql/opt/norm/custom_funcs.go, line 618 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOysnG7DE0LIQOsJOYv:-LOysnG8-FSWhol_h7Mi:b-ehbkpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L618)):*
> ```Go
> func (c *CustomFuncs) SimplifyFilters(filters memo.FiltersExpr) memo.FiltersExpr {
> 	// This code assumes that the NormalizeNestedAnds rule has already run and
> 	// ensured a left deep And tree. If not (maybe because it's a testing
> ```

Out of curiosity, why did you decide to change `And` and `Or` back to being binary operators?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 621 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxNCbH-_V_nAcNY67X:-LOxNCbH-_V_nAcNY67Y:b-cwtm7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L621)):*
> ```Go
> 	// scenario), then this rule may rematch, but it should still make forward
> 	// progress).
> 	cnt := 0
> ```

It would help to explicitly say that this first nested for-loop is just used to count the number of conjuncts in a flattened list. I had to stare at it for a bit to figure that out.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 646 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxNsRW-ttIdUkqOSVX:-LOxNsRX4TOEqhfxVn5-:b-82lb5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L646)):*
> ```Go
> // find nested And operators. It adds any conjuncts (ignoring True operators) to
> // the given FiltersExpr and returns true. If it finds a False or Null operator,
> // it returns propagates a false return value all the up the call stack, and
> ```

returns propagates -> propagates
___
*[pkg/sql/opt/norm/custom_funcs.go, line 810 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxQ3rxCvn8s_pf5vVa:-LOxQ3rxCvn8s_pf5vVb:blhabi) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L810)):*
> ```Go
> //   A OR (A AND B)                     =>  A
> //   (A AND B) OR (A AND C)             =>  A
> //   (A AND B AND C) OR (A AND D OR E)  =>  A
> ```

Is this correct? Not sure this works unless it's `(A AND D AND E)`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 826 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxRUUw4LZPPDz_ISwB:-LOxRUUx4fdgiAX9-mO3:b-e3wtt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L826)):*
> ```Go
> 			left = and.Left
> 		} else {
> 			if !c.isConjunct(left, right) {
> ```

[nit] to make these two cases parallel, why don't you check `if c.IsConjunct(left, right)` and swap the two return statements
___
*[pkg/sql/opt/norm/custom_funcs.go, line 863 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxSCvMBVqZ62wgftZc:-LOxSCvMBVqZ62wgftZd:b-ll9vmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L863)):*
> ```Go
> //
> // These transformations are useful for finding a conjunct that can be pushed
> // down in the query tree. For example, if the redundant subclause A is
> ```

subclause -> conjunct
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1045 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxX7EdAVxkmfqpuWsh:-LOxX7EdAVxkmfqpuWsi:b-v95s58) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1045)):*
> ```Go
> 
> // EqualsOpName returns true if the two operators are the same.
> func (c *CustomFuncs) EqualsOpName(left, right opt.Operator) bool {
> ```

[nit] This name is a bit confusing since it sounds like it should return the name of the `EqualsOp` operator. Why not just call it `SameAs` or something like like that?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1079 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxY47F-O7BiZ-NiWlI:-LOxY47F-O7BiZ-NiWlJ:bzet7ds) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1079)):*
> ```Go
> // ----------------------------------------------------------------------
> 
> // EqualsNumber returns true if the given private numeric value (decimal, float,
> ```

[nit] can remove the word "private"
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1225 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxYsFQ78HvBhLpqbLs:-LOxYsFQ78HvBhLpqbLt:b-1hjb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1225)):*
> ```Go
> 
> // UnifyComparison attempts to convert a constant expression to the type of the
> // variables expression, if that conversion can round-trip and is monotonic.
> ```

variables -> variable
___
*[pkg/sql/opt/norm/decorrelate.go, line 130 at r20](https://reviewable [...]

2018-10-17 00:10 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 390 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxDK1n8sWHUbgApZoq:-LOz-Uoe0bIWYpP0D0L2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L390)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

any of the given -> the given
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 485 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxEkfe85mtAiuQtcsx:-LOz-lryE1FSbrb5esWc:b-mb9z1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L485)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is it true that we only call this function if there is at least one unbound condition? If so, add a comment to explain why the capacity is `len(filters)-1`.
</blockquote></details>

Actually, there may be  zero unbound conditions. I'll get rid of the `-1`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 501 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxF5kX1B0sqENeKq3P:-LOz-z749LANk__aOKfl:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L501)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Same here - the function should only be called if there is at least one bound condition.
</blockquote></details>

Same as above.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 543 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxIbQI7nSt14ksB9W1:-LOz0Uoj6bUbJ1Gl7UQC:b-35b93r) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L543)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would be good to add a comment that the outer synthesized columns do not contain references to item since `CanMergeProjectsions` should have returned true.
</blockquote></details>

I added an extra comment to the method header to that effect.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 596 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxJvzrAMHN1iBXK4da:-LOz0dEm-veWEx2CvXDA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L596)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

with columns -> with no columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 618 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOysnG7DE0LIQOsJOYv:-LOz0eB2ESNL4jDm2O09:bu2jzuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L618)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Out of curiosity, why did you decide to change `And` and `Or` back to being binary operators?
</blockquote></details>

1. It saves us slice allocations in the common case of `WHERE` conjuncts, which just get rolled up into a `Filters` list anyway.
2. It mirrors the AST expression. I hope to unify the two representations in the future.
3. Most of the use cases for having a list are now handled by the `Filters` operator. There were only a couple `And` use cases left, and I changed those accordingly. The redundant subclause rules aren't quite as elegant now, but I think they're still pretty good.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 621 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxNCbH-_V_nAcNY67X:-LOz3TyoBdEXCyqZA0rJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L621)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would help to explicitly say that this first nested for-loop is just used to count the number of conjuncts in a flattened list. I had to stare at it for a bit to figure that out.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 646 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxNsRW-ttIdUkqOSVX:-LOz3X_R2emW1lnq65OE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L646)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

returns propagates -> propagates
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 810 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxQ3rxCvn8s_pf5vVa:-LOz3p0gC7iR_mob67W8:b-mtay22) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L810)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this correct? Not sure this works unless it's `(A AND D AND E)`.
</blockquote></details>

I added parentheses to fix precedence.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 826 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxRUUw4LZPPDz_ISwB:-LOz4PPW48azZTHbyHLk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L826)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] to make these two cases parallel, why don't you check `if c.IsConjunct(left, right)` and swap the two return statements
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 863 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxSCvMBVqZ62wgftZc:-LOz5Wes6145ljt0W1UZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L863)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

subclause -> conjunct
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1045 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxX7EdAVxkmfqpuWsh:-LOz5yT_-L38nzf87feW:bwjhujd) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1045)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] This name is a bit confusing since it sounds like it should return the name of the `EqualsOp` operator. Why not just call it `SameAs` or something like like that?
</blockquote></details>

I changed to `OpsAreSame`.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1079 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxY47F-O7BiZ-NiWlI:-LOz62rf9BOvvZr0YFXs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1079)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] can remove the word "private"
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 1225 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxYsFQ78HvBhLpqbLs:-LOz668KAvuS1zOyzpu9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L1225)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

variables -> variable
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/decorrelate.go, line 130 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOxm2HZ0tzZfbfaq4i-:-LOz6r6gAsGaJzZqRexN:b-s34lhv) ([raw file](https://github.com/cockroach [...]

2018-10-17 19:46 UTC, rytaft requested changes
Almost there... still a bit more to review

> Reviewed 1 of 112 files at r23, 30 of 42 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LP2YxGFAiBhr4sOS9E0:bkvqa5h)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/custom_funcs.go, line 618 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LOysnG7DE0LIQOsJOYv:-LP1bQnF1YcS-txTJ2bg:b-xe5y6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d7e17313142bd8f37cf510e9109a501e7f911e/pkg/sql/opt/norm/custom_funcs.go#L618)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

1. It saves us slice allocations in the common case of `WHERE` conjuncts, which just get rolled up into a `Filters` list anyway.
2. It mirrors the AST expression. I hope to unify the two representations in the future.
3. Most of the use cases for having a list are now handled by the `Filters` operator. There were only a couple `And` use cases left, and I changed those accordingly. The redundant subclause rules aren't quite as elegant now, but I think they're still pretty good.
</blockquote></details>

Makes sense - thanks!
___
*[pkg/sql/opt/norm/inline.go, line 22 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1eFDt9ryahPhTx-wx:-LP1eFDt9ryahPhTx-wy:bag8wen) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L22)):*
> ```Go
> )
> 
> // HasDuplicateRefs returns true if the target projections expression reference
> ```

expression -> expressions
___
*[pkg/sql/opt/norm/inline.go, line 23 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1eUliAnj-RZLtrGw5:-LP1eUljEPJXQ_3ISXst:b99sk2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L23)):*
> ```Go
> 
> // HasDuplicateRefs returns true if the target projections expression reference
> // any outer column more than one time, or if it has a subquery. For example:
> ```

why did you remove the word "correlated"? I think uncorrelated subqueries are ok...
___
*[pkg/sql/opt/norm/inline.go, line 46 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1fPsG5bEYOPZ3siTn:-LP1fPsH7jwGuDysZkEG:b-3s2dkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L46)):*
> ```Go
> 		// already contains a reference to that column, then there is a duplicate.
> 		// findDupRefs returns true if the subtree contains at least one duplicate.
> 		var findDupRefs func(nd opt.Expr) bool
> ```

[nit] what is `nd`? This variable name is kind of cryptic
___
*[pkg/sql/opt/norm/inline.go, line 127 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2-yRR8_Gv6_CuHdyD:-LP2-yRR8_Gv6_CuHdyE:bd4xlpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L127)):*
> ```Go
> }
> 
> // InlineProjectProject searches the input expression (with must be a Project
> ```

with -> which
___
*[pkg/sql/opt/norm/inline.go, line 130 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP20c3c64t9iIgx5AKj:-LP20c3d7mkQdgJOhwc-:b-abyjdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L130)):*
> ```Go
> // operator) for any variable references to columns from the given projections
> // expression. Each variable is replaced by the corresponding inlined projection
> // expression.
> ```

Isn't this backwards? It seems like it's searching `projections` for any variable references from `input`'s projections.
___
*[pkg/sql/opt/norm/inline.go, line 162 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP21UHmDj7S-LJ3S7T3:-LP21UHmDj7S-LJ3S7T4:b5q0u7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L162)):*
> ```Go
> // Recursively walk the tree looking for references to projection expressions
> // that need to be replaced.
> func (c *CustomFuncs) inlineProjections(nd opt.Expr, projections memo.ProjectionsExpr) opt.Expr {
> ```

[nit] another case of `nd`. I guess this is like "node"? Could use a better name. Maybe just `e`, which I've seen you use elsewhere.
___
*[pkg/sql/opt/norm/join.go, line 130 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP22PZA7CubgV33gtUt:-LP22PZA7CubgV33gtUu:b1ueoho) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L130)):*
> ```Go
> 	filters memo.FiltersExpr, src *memo.FiltersItem, dst memo.RelExpr,
> ) bool {
> 	// Fast path if condition is already bound by input.
> ```

Why did you change this comment from `src`/`dst` to `condition`/`input`?
___
*[pkg/sql/opt/norm/join.go, line 301 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP24b0O4AF7zLIDWuKf:-LP24b0O4AF7zLIDWuKg:bv6bbw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L301)):*
> ```Go
> 		}
> 
> 		// Normalize leftCol to come from leftCols.
> ```

This comment doesn't really make sense anymore
___
*[pkg/sql/opt/norm/join.go, line 560 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP25Ld97tE9t6FTNq9s:-LP25Ld97tE9t6FTNq9t:bbnngci) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L560)):*
> ```Go
> //   - a and b are not "bare" variables;
> //   - a and b contain no correlated subqueries;
> //   - neither a or b are constants.
> ```

Update comment -- `a` and `b` have been replaced by `scalar`
___
*[pkg/sql/opt/norm/project_builder.go, line 29 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2IIio8JbbHGVO-Iuo:-LP2IIip51qM3w8fUgZd:b-yb167i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/project_builder.go#L29)):*
> ```Go
> //   e1 := pb.add(some expression)
> //   e2 := pb.add(some other expression)
> //   augmentedInput := pb.buildProject(input)
> ```

Missing passthrough columns
___
*[pkg/sql/opt/norm/rules/bool.opt, line 42 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2NcJnBIiRA6IEoaSx:-LP2NcJo39YdURKu-3hK:b-ol0b8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L42)):*
> ```
> $right
> 
> # SimplifyTrueAnd simplifies the And operator by discarding a True condition on
> ```

SimplifyTrueAnd -> SimplifyAndTrue
___
*[pkg/sql/opt/norm/rules/bool.opt, line 148 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2PHqr1D2A6yr4Po1v:-LP2PHqs-T6-DKwcRGBL:b4zt1fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L148)):*
> ```
> (And (Not $left) (Not $right))
> 
> # ExtractRedundantConjunct matches an OR expression in which the same conjunct
> ```

Nice rewriting of this rule
___
*[pkg/sql/opt/norm/rules/bool.opt, line 157 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2OW4R8dDbRdBdymAh:-LP2OW4R8dDbRdBdymAi:b-ll9vmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L157)):*
> ```
> #
> # This transformation is useful for finding a conjunct that can be pushed down
> # in the query tree. For example, if the redundant subclause A is fully bound by
> ```

subclause -> conjunct
___
*[pkg/sql/opt/norm/rules/bool.opt, line 160 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2Ol1XDXvqfEJp76gX:-LP2Ol1XDXvqfEJp76gY:b-ll9vmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a49 [...]

2018-10-17 21:25 UTC, rytaft approved these changes
norm and optgen commits <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 3 of 92 files at r2, 2 of 197 files at r9, 3 of 195 files at r16, 12 of 42 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LP2uOix64mJ9iJzfJpA:b-5tjx6b)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/testdata/rules/bool, line 224 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2m0cpBFwR3cnoEDJn:-LP2m0cpBFwR3cnoEDJo:b-se7w1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/testdata/rules/bool#L224)):*
> ```
> 
> opt
> SELECT k=1 OR true AND f=3.5 AS r FROM a
> ```

I don't think this is testing the right rules -- AND has precedence here


<!-- Sent from Reviewable.io -->

2018-10-18 03:30 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/inline.go, line 22 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1eFDt9ryahPhTx-wx:-LP3ZbvWBpm9no7FAznG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L22)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

expression -> expressions
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/inline.go, line 23 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1eUliAnj-RZLtrGw5:-LP3_os249jBaIiSlGsm:b-a19ivd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L23)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did you remove the word "correlated"? I think uncorrelated subqueries are ok...
</blockquote></details>

For a little while during the rewrite it was all subqueries. I switched it back, but didn't switch the comment back.
___
*[pkg/sql/opt/norm/inline.go, line 46 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP1fPsG5bEYOPZ3siTn:-LP3a0JW2Ua3eNRfND1v:bzbnw7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L46)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] what is `nd`? This variable name is kind of cryptic
</blockquote></details>

It was short for `Node`. I didn't catch all the places when I renamed `Node` to `Expr`. Fixed.
___
*[pkg/sql/opt/norm/inline.go, line 127 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2-yRR8_Gv6_CuHdyD:-LP3a9ay9QQZL6bCMOD7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L127)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

with -> which
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/inline.go, line 130 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP20c3c64t9iIgx5AKj:-LP3ajVN2VRnoh0DN_BC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Isn't this backwards? It seems like it's searching `projections` for any variable references from `input`'s projections.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/inline.go, line 162 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP21UHmDj7S-LJ3S7T3:-LP3alWP39ZMY-wD7q8_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/inline.go#L162)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] another case of `nd`. I guess this is like "node"? Could use a better name. Maybe just `e`, which I've seen you use elsewhere.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 130 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP22PZA7CubgV33gtUt:-LP3azJy1lCdmi5oyV3k:b741ba5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L130)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you change this comment from `src`/`dst` to `condition`/`input`?
</blockquote></details>

Was from an earlier iteration where that made sense, missed changing comment back.
___
*[pkg/sql/opt/norm/join.go, line 301 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP24b0O4AF7zLIDWuKf:-LP3bAl0C9Av9G6-moBD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L301)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This comment doesn't really make sense anymore
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 560 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP25Ld97tE9t6FTNq9s:-LP3blxEEnlCpmxmm9vV:bj1cwjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/join.go#L560)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment -- `a` and `b` have been replaced by `scalar`
</blockquote></details>

I switched it back to use `a` and `b` - at one point in my iterations it made sense to use `scalar` instead.
___
*[pkg/sql/opt/norm/project_builder.go, line 29 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2IIio8JbbHGVO-Iuo:-LP3cKAF6Ht52pxGAZz6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/project_builder.go#L29)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Missing passthrough columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/bool.opt, line 42 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2NcJnBIiRA6IEoaSx:-LP3cSD3CzoP8wLOmVnq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L42)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

SimplifyTrueAnd -> SimplifyAndTrue
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/bool.opt, line 157 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2OW4R8dDbRdBdymAh:-LP3c_QmCfIC3JKdc812:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L157)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

subclause -> conjunct
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/bool.opt, line 160 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2Ol1XDXvqfEJp76gX:-LP3c_wi52V5Xe3p3puW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/bool.opt#L160)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

subclause -> conjunct
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 64 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2PduA0EL6-sWIPLOE:-LP3cpIM48nRPWGDc_P6:bl5l2lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/02209c9f5cb6ed8b966ee42d92f758b4aeaf36d5/pkg/sql/opt/norm/rules/decorrelate.opt#L64)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How did you eliminate the need for cycle detection?
</blockquote></details>

I added `HasOuterCols` checks in the `PushFilterIntoJoin` rules. So we no longer push down in cases where it might trigger a cycle. This did result in at least one case where we can't decorrelate where we could before. I think it's still the right way to go, since these are edge cases that don't justify the complexity of cycle detection.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 693 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2RNzcB7zQlhzwZaV2:-LP3dxP1-fjyd0-4xazu:br1tm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e06a13d4c3504306b299442ee57b2a490aa102eb/pkg/sql/opt/norm/rules/decorrelate.opt#L693)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you need to split these into two different rules?
</blockquote></details>

Because we can no longer match on List operators like `Filters`, so we have to match on their parent operator. The new design does not intern or match list operators for various reasons (I listed them in another comment made by Justin). It's a downsid [...]

2018-10-18 13:25 UTC, rytaft approved these changes
> Reviewed 7 of 7 files at r26.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 64 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP2PduA0EL6-sWIPLOE:-LP6Kaov7c9zKaOFMEgm:b-490o4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/02209c9f5cb6ed8b966ee42d92f758b4aeaf36d5/pkg/sql/opt/norm/rules/decorrelate.opt#L64)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I added `HasOuterCols` checks in the `PushFilterIntoJoin` rules. So we no longer push down in cases where it might trigger a cycle. This did result in at least one case where we can't decorrelate where we could before. I think it's still the right way to go, since these are edge cases that don't justify the complexity of cycle detection.
</blockquote></details>

Cool makes sense
___
*[pkg/sql/opt/norm/rules/join.opt, line 436 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP6IoMJ9BgSAed_cGI2:-LP6IoMK5gmZn1xRlJQL:be7p3um) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1760365ddbe6d0705b1786eda50d73b06673a9/pkg/sql/opt/norm/rules/join.opt#L436)):*
> ```
>         ...
>         $item:(FiltersItem
>             $eq:(Eq
> ```

don't need to bind $eq anymore


<!-- Sent from Reviewable.io -->

2018-10-18 14:26 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/rules/join.opt, line 436 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-LP6IoMJ9BgSAed_cGI2:-LP6ZQun9yJyLnisSvVe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c1760365ddbe6d0705b1786eda50d73b06673a9/pkg/sql/opt/norm/rules/join.opt#L436)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

don't need to bind $eq anymore
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-18 14:32 UTC, rytaft approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-18 18:07 UTC, RaduBerinde commented
The updates to memo and xform LGTM.

One small thing (feel free to take it or leave it) -  in the interner it would be cleaner if `Next` would only do the "read-only" stuff, and `Add` would do all the modifications; something along the lines of: https://gist.github.com/RaduBerinde/e10a1b2b5393b9e09b0494c714a964f7

2018-10-18 22:33 UTC, andy-kimball reviewed
Yes, that's a better approach. I made the change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31173#-:-LP8D2dlECQHKFpBxViO:b-rtby5t)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-18 23:30 UTC, andy-kimball commented
bors r+

2018-10-18 23:43 UTC, andy-kimball commented
Thanks to all for the time-consuming reviews of such a large PR.

2018-10-18 23:48 UTC, merged