roachtest, workload: large re-write of interleaved-partition test and workload
cockroachdb/cockroach pull request #31311
Opened 2018-10-12 16:20 UTC by BramGruneir

The interleaved partition workload and test were not performing the correct
operations and there was a good amount of leftover cruft from experiments that
were run. This commit fixes most of those problems.

A non-exhaustive selection of the updates:

- All inserts occurred in the east so everything was stored with the
leaseholders being locked to the east dc.  These should be split evenly between
east and west and now are again.
- Both the retrieve and update operations did not run against actual session
ids.  So all of their operations where essentially noops.
- The workloads are now run from different machines to not interfere with
cockroach.
- I greatly reduced the number of options being passed into the test. There was
no need for most of them.
- Removed the non-partitioned index on sessions.created.
- Updated the session ids to show both the node in which they were added as
well as the worker number. This proves we have a nice spread, as expected.

There's still some more to do here, such as put the full retrieve and update
operations inside a transaction.  And try to reduce contention by adding in a
partitioned index for deletes.

All of this work was prompted by #28921, which shows that we had collisions.
Now that the workload is running correctly, if this happens again, we will have
more insight into what's going on.

Release note: None

2018-10-12 16:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31311)
<!-- Reviewable:end -->

2018-10-22 14:18 UTC, m-schneider commented on pkg/cmd/roachtest/interleavedpartitioned.go
> +		cockroachWest := c.Range(1, 3)
test

2018-10-22 15:13 UTC, m-schneider requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31311)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LOd41JK9vUSwCeUcaat-r1-42:-LPRJ2SS5X6Y2zoPLEbk:b6bmuo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L42)):*
> ```Go
> 		config config,
> 	) {
> 		cockroachWest := c.Range(1, 3)
> ```

Out of curiosity how did you get this working?
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKZI94m5v6y5AM30K:-LPRKZI94m5v6y5AM30L:b-6kt4yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L76)):*
> ```Go
> 		histograms := " --histograms logs/stats.json"
> 
> 		createCmd := func(locality string, cockroachNodes nodeListOption) string {
> ```

Why are you removing various parameters? Are they not needed?
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKJv6A7Ua4cw2RUUV:-LPRKJv6A7Ua4cw2RUUW:bzfv05e) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L122)):*
> ```Go
> 		}
> 
> 		runLocality("west", workloadWest, createCmd("west", cockroachWest))
> ```

Is this so you can use east,west etc.. instead of the actual GCE region name?
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKRdE0r3TSWwMke7H:-LPRKRdE0r3TSWwMke7I:b1m64dn) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L139)):*
> ```Go
> 					westName:        `us-west1-b`,
> 					centralName:     `us-central1-a`,
> 					initSessions:    1000,
> ```

Why the change in sessions?


<!-- Sent from Reviewable.io -->

2018-10-22 16:42 UTC, BramGruneir reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31311)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LOd41JK9vUSwCeUcaat-r1-42:-LPRcq2X5HRIG3b9J6IY:b-mg3tpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L42)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Out of curiosity how did you get this working?
</blockquote></details>

It was broken because I had updated `merge` but it's an interface and only in one place.  Once I reverted the change it was working again.  I still think it should take more than one group, but futzing with it just got frustrating.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKZI94m5v6y5AM30K:-LPRbzpZ7C0nA7j81svd:bqsz49w) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L76)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Why are you removing various parameters? Are they not needed?
</blockquote></details>

This was just way too configurable.  If you need to alter the workload to run some very specific scenario, you can still do that manually.  But from every run that I've ever done with this style of workload, they were not needed.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKJv6A7Ua4cw2RUUV:-LPRdBq51iG8RqS7Svvl:bwlrgta) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L122)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Is this so you can use east,west etc.. instead of the actual GCE region name?
</blockquote></details>

The workload is different based on the locality.  I guess we could use actual locality, but it just seems cleaner to specify which workload here.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKRdE0r3TSWwMke7H:-LPRcKY7AKJKnSHCr5f4:b-z54ioy) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L139)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Why the change in sessions?
</blockquote></details>

The 10000 was ignored and replaced with 0 before (see `cmdInit`).  10,000 seemed a little large, so I just set it to 1000 which should be good enough.


<!-- Sent from Reviewable.io -->

2018-10-22 17:12 UTC, m-schneider approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-:-LPRkuOk0adyoWJWven_:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LOd41JK9vUSwCeUcaat-r1-42:-LPRksEW4jCNBFuEoEeb:bxa6kq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L42)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

It was broken because I had updated `merge` but it's an interface and only in one place.  Once I reverted the change it was working again.  I still think it should take more than one group, but futzing with it just got frustrating.
</blockquote></details>

Oh ok.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKZI94m5v6y5AM30K:-LPRkgE8ES8s0FxKPfAm:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L76)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This was just way too configurable.  If you need to alter the workload to run some very specific scenario, you can still do that manually.  But from every run that I've ever done with this style of workload, they were not needed.
</blockquote></details>

Ok!
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKJv6A7Ua4cw2RUUV:-LPRkieJ67afINdFtdFs:b-mmez5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L122)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

The workload is different based on the locality.  I guess we could use actual locality, but it just seems cleaner to specify which workload here.
</blockquote></details>

Yes, you're right it's very clean.
___
*[pkg/cmd/roachtest/interleavedpartitioned.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-LPRKRdE0r3TSWwMke7H:-LPRknub491Gs1oE232y:btojbfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/03497ae55a8c24686f9703db7144cd0a81ba48b6/pkg/cmd/roachtest/interleavedpartitioned.go#L139)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

The 10000 was ignored and replaced with 0 before (see `cmdInit`).  10,000 seemed a little large, so I just set it to 1000 which should be good enough.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2018-10-22 19:07 UTC, BramGruneir reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31311#-:-LPSA4yz3vRccGOEKqgS:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-22 19:39 UTC, BramGruneir commented
bors r+

2018-10-23 21:46 UTC, BramGruneir commented
bors r+

2018-10-24 13:51 UTC, BramGruneir commented
bors r+

Unrelated test flake seems to match #30951.

2018-10-24 14:13 UTC, merged