sql: use ClearRange for index truncation
cockroachdb/cockroach pull request #31326
Opened 2018-10-12 19:41 UTC by eriktrinh

This change makes the deletion of index data use the ClearRange batch
request. DROP INDEX schema changes in the same transaction as the one
which created the table still uses the slower DelRange because
ClearRange cannot be run inside a transaction and will remove write
intents of the index keys which have not been resolved in the
transaction.

The GC threshold is also forwarded for the cleared range to prevent
reads and writes of index data.

Fixes #20696.

Release note (performance improvement): Deletion of index data is faster.

2018-10-12 19:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31326)
<!-- Reviewable:end -->

2018-10-12 20:43 UTC, vivekmenezes requested changes
Nicely done!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-:-LOe0JIn9N4oNTifcFn8:b-ao1qb6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease_test.go, line 1025 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOe-fzGBzRVfk_5xVId:-LOe-fzGBzRVfk_5xVIe:bge5q91) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0a5ed19556e360d5c41c4880b7fc38c5751981/pkg/sql/lease_test.go#L1025)):*
> ```Go
> 		t.Fatal(err)
> 	}
> ```

I think it's valuable to count the size of the index and assert that the above INSERT added a value to the index even though it was dropped. 
___
*[pkg/sql/tablewriter_delete.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOdykdh4x3WFoOWdRqm:-LOdykdh4x3WFoOWdRqn:b-8jj8a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0a5ed19556e360d5c41c4880b7fc38c5751981/pkg/sql/tablewriter_delete.go#L261)):*
> ```Go
> 	autoCommit autoCommitOpt,
> 	traceKV bool,
> 	allowClearRange bool,
> ```

We should create a new function clearIndex() and use that instead of passing in a bool. In clearRange() you can assert that !idx.IsInterleaved


<!-- Sent from Reviewable.io -->

2018-10-15 13:39 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease_test.go, line 1025 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOe-fzGBzRVfk_5xVId:-LOrwn_j6T-1yZHINhQD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0a5ed19556e360d5c41c4880b7fc38c5751981/pkg/sql/lease_test.go#L1025)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think it's valuable to count the size of the index and assert that the above INSERT added a value to the index even though it was dropped. 
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter_delete.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOdykdh4x3WFoOWdRqm:-LOrwpJz3I6MvCj0UsaQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea0a5ed19556e360d5c41c4880b7fc38c5751981/pkg/sql/tablewriter_delete.go#L261)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We should create a new function clearIndex() and use that instead of passing in a bool. In clearRange() you can assert that !idx.IsInterleaved
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-15 17:30 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_delete.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOsjqxuEg8zdH3QMxf3:-LOsjqxuEg8zdH3QMxf4:bndkq8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/sql/tablewriter_delete.go#L306)):*
> ```Go
> ) (roachpb.Span, error) {
> 	if idx.IsInterleaved() {
> 		if log.V(2) {
> ```

you can return an error here. There should be no reason why IsInterleaved() is true
___
*[pkg/storage/batcheval/cmd_clear_range.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOslYLu2j1wrk5CuTpK:-LOslYLu2j1wrk5CuTpL:b-g0bgn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/storage/batcheval/cmd_clear_range.go#L95)):*
> ```Go
> 	if err := stateLoader.SetGCThreshold(ctx, batch, cArgs.Stats, &gcThreshold); err != nil {
> 		return result.Result{}, err
> 	}
> ```

We should have a test in storage that tests this. I'm adding @benesch as a reviewer


<!-- Sent from Reviewable.io -->

2018-10-15 17:31 UTC, vivekmenezes commented
looks like this has a broken test in Import

2018-10-15 17:43 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_delete.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOsjqxuEg8zdH3QMxf3:-LOsn-H-5tt-8HEg9wKv:bd7h7m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/sql/tablewriter_delete.go#L306)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you can return an error here. There should be no reason why IsInterleaved() is true
</blockquote></details>

It can be true because `truncateIndexes` (which calls `clearIndex`) is still called in the synchronous code path for interleaved indexes. In fact it will also call this for non-interleaved indexes in the synchronous code path if the cluster version does not allow for ClearRange (on a related note, do we need to add a new cluster version flag for truncating indexes?).

We should check `canClearRangeForDrop` once again in `truncateIndexes` and call this if it can, and `deleteIndex` otherwise.


<!-- Sent from Reviewable.io -->

2018-10-15 17:55 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_delete.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOsjqxuEg8zdH3QMxf3:-LOsqxQJ1yzWv1r5skka:b-aea79i) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/sql/tablewriter_delete.go#L306)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

It can be true because `truncateIndexes` (which calls `clearIndex`) is still called in the synchronous code path for interleaved indexes. In fact it will also call this for non-interleaved indexes in the synchronous code path if the cluster version does not allow for ClearRange (on a related note, do we need to add a new cluster version flag for truncating indexes?).

We should check `canClearRangeForDrop` once again in `truncateIndexes` and call this if it can, and `deleteIndex` otherwise.
</blockquote></details>

Let's maintain two separate code paths for the deleteIndex and clearIndex and return an error from clearIndex if it shouldn't have been called. Thanks!


<!-- Sent from Reviewable.io -->

2018-10-15 19:59 UTC, eriktrinh reviewed
> looks like this has a broken test in Import

looks like there is a race, still taking a look        

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-:-LOtIw4C6VOM1hY1XLHA:b51z1xx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/tablewriter_delete.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOsjqxuEg8zdH3QMxf3:-LOt8nCc7uPVRppD6cAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/sql/tablewriter_delete.go#L306)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Let's maintain two separate code paths for the deleteIndex and clearIndex and return an error from clearIndex if it shouldn't have been called. Thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-15 20:41 UTC, benesch reviewed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_clear_range.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOslYLu2j1wrk5CuTpK:-LOtJWF81AJWy2v65JmS:bx4vjwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/storage/batcheval/cmd_clear_range.go#L95)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

We should have a test in storage that tests this. I'm adding @benesch as a reviewer
</blockquote></details>

I think the implications of this are problematic. Say the index is located on the same range as the primary key, which is the case for any table whose primary + index data is less than 64MB. Dropping that index would forward the GC threshold on that entire range to now, meaning that AOST queries on the primary key data will be impossible!

In fact, even if you assume that the index is on a separate range, I'm not sure this is sufficient? Don't AOST queries see the old version of the descriptor? So they'll try to use the index and explode because the index's range won't serve reads at that time.

Anyway, @tschottdorf is the expert here. I might be off base.


<!-- Sent from Reviewable.io -->

2018-10-15 20:47 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_clear_range.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOslYLu2j1wrk5CuTpK:-LOtTW9C0mYlt1itmQ4T:bnx6saw) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/storage/batcheval/cmd_clear_range.go#L95)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think the implications of this are problematic. Say the index is located on the same range as the primary key, which is the case for any table whose primary + index data is less than 64MB. Dropping that index would forward the GC threshold on that entire range to now, meaning that AOST queries on the primary key data will be impossible!

In fact, even if you assume that the index is on a separate range, I'm not sure this is sufficient? Don't AOST queries see the old version of the descriptor? So they'll try to use the index and explode because the index's range won't serve reads at that time.

Anyway, @tschottdorf is the expert here. I might be off base.
</blockquote></details>

Yeah, we wouldn't want to wipe the AOST window here. I'm probably lacking context here, but why do we need to do this? I was assuming the schema change machinery would delete this data only once it's not being accessed any more.


<!-- Sent from Reviewable.io -->

2018-10-15 20:49 UTC, benesch reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batcheval/cmd_clear_range.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LOslYLu2j1wrk5CuTpK:-LOtUAb726hzzxr1E-qE:byj7hvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79310e606efb7e6f5b5070713a0b2c2f014541ce/pkg/storage/batcheval/cmd_clear_range.go#L95)):*
I think you actually answered that question a year ago. :)

> One complication is that all index operations are serialized through the surrounding table descriptor, so that the naive approach of waiting for the TTL is not great (as it holds up unrelated schema changes).

#20696


<!-- Sent from Reviewable.io -->

2018-10-17 23:23 UTC, eriktrinh reviewed
PTAL, updated the pr to move ahead with this despite the `ClearRange` limitation. The failing test from before was probably the race between the split queue and forwarding the GC threshold.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-:-LP3JcKvCnw9NsA1PqsG:b-x8bzjo)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-19 02:11 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP92WW12HqaSAJjVouG:-LP92WW12HqaSAJjVouH:b-i3mgrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/backfill.go#L233)):*
> ```Go
> 			if err := sc.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 				if fn := sc.execCfg.DistSQLRunTestingKnobs.RunBeforeBackfillChunk; fn != nil {
> 					if err := fn(resume); err != nil {
> ```

Can you check for the clearIndex case that this is only always called with an empty ResumeSpan in the test. This is to ensure that we are indeed calling the new code path.
___
*[pkg/sql/lease_test.go, line 1047 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP93VCT0-CjzHtt8MkQ:-LP93VCT0-CjzHtt8MkR:b1ek3om) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/lease_test.go#L1047)):*
> ```Go
> 		t.Fatal(err)
> 	}
> ```

You've set the zone config ttl to 0 above so how do you know that the above two commands are not going to fail infrequently and result in a test flake?


I think you should move the GC section to the bottom of this test and show that the above SELECT and UPDATE work  with the index because they are using the old descriptor. But that is okay because the data is consistent.
___
*[pkg/sql/tablewriter_delete.go, line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP91SUTCIV4stC_cDf6:-LP91SUTCIV4stC_cDf7:bhxxtc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/tablewriter_delete.go#L303)):*
> ```Go
> 	resume roachpb.Span,
> 	limit int64,
> 	autoCommit autoCommitOpt,
> ```

resume, limit and autocommit need not be pass in


<!-- Sent from Reviewable.io -->

2018-10-19 13:09 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 233 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP92WW12HqaSAJjVouG:-LP9MayN1aZUr44r0ZU_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/backfill.go#L233)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you check for the clearIndex case that this is only always called with an empty ResumeSpan in the test. This is to ensure that we are indeed calling the new code path.
</blockquote></details>

Done.
___
*[pkg/sql/lease_test.go, line 1047 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP93VCT0-CjzHtt8MkQ:-LP9ShCv3BsE8B5R1fRa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/lease_test.go#L1047)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

You've set the zone config ttl to 0 above so how do you know that the above two commands are not going to fail infrequently and result in a test flake?


I think you should move the GC section to the bottom of this test and show that the above SELECT and UPDATE work  with the index because they are using the old descriptor. But that is okay because the data is consistent.
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter_delete.go, line 303 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LP91SUTCIV4stC_cDf6:-LP9HSDa70zFMdF5YE2M:br434np) ([raw file](https://github.com/cockroachdb/cockroach/blob/549a20a581f17da94ef759b2a21b4c03fa56859d/pkg/sql/tablewriter_delete.go#L303)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

resume, limit and autocommit need not be pass in
</blockquote></details>

Done. Removed traceKV as it was always false.


<!-- Sent from Reviewable.io -->

2018-10-19 15:09 UTC, vivekmenezes approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 269 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBqQGR52OMDBjNIPPh:-LPBqQGR52OMDBjNIPPi:b-aw26h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/backfill.go#L269)):*
> ```Go
> 				} else {
> 					err = td.clearIndex(ctx, &desc)
> 					resume = roachpb.Span{}
> ```

done = true
return td.clearindex(ctx, &desc)
___
*[pkg/sql/backfill.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBqmxi7rIzQD7RnxWX:-LPBqmxi7rIzQD7RnxWY:bnby583) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/backfill.go#L272)):*
> ```Go
> 				}
> 				done = resume.Key == nil
> 				return err
> ```

move this to the if clause above
___
*[pkg/sql/lease_test.go, line 1053 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBrFeYBpwdsAFwx1iJ:-LPBrFeYBpwdsAFwx1iK:behymvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/lease_test.go#L1053)):*
> ```Go
> 	// TODO(erik, vivek): Transactions using old descriptors should fail and
> 	// rollback when the index keys have been removed by ClearRange
> 	// and the consistency issue is resolved.
> ```

Can you add a reference to the issue number


<!-- Sent from Reviewable.io -->

2018-10-19 15:35 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31326)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 269 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBqQGR52OMDBjNIPPh:-LPBxmWd7p98Oc8Un4q1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/backfill.go#L269)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

done = true
return td.clearindex(ctx, &desc)
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBqmxi7rIzQD7RnxWX:-LPBxnKR59NM8TYKlxb-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/backfill.go#L272)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

move this to the if clause above
</blockquote></details>

Done.
___
*[pkg/sql/lease_test.go, line 1053 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31326#-LPBrFeYBpwdsAFwx1iJ:-LPBxqpH5sAtojdkIyqd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8d4b5db19b82e09edf47dc20ab60b4c8440ad3/pkg/sql/lease_test.go#L1053)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you add a reference to the issue number
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-19 15:35 UTC, eriktrinh commented
bors r+

2018-10-19 15:38 UTC, eriktrinh commented
bors r+

2018-10-19 16:17 UTC, eriktrinh commented
bors r+

2018-10-19 16:39 UTC, merged