storage: lazily load storage.Replica objects
cockroachdb/cockroach pull request #31663
Opened 2018-10-20 01:32 UTC by spencerkimball

More than several tens of thousands of `Replica` objects can take
substantial time at server startup to initialize. This change introduces
a `ReplicaShim` object which contains a pointer to the `Replica` which is
non-nil if resident. Otherwise, a set of other values including a ref to
the appropriate zone config, `MVCCStats` and a handful of other properties
necessary to accurately compute stats even when a replica is not-resident.

Release note (performance improvement): faster startup whena node contains
many replicas.

2018-10-20 01:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31663)
<!-- Reviewable:end -->

2018-10-20 01:36 UTC, spencerkimball commented
The performance at startup is markedly better. With 700,000 ranges:

Before: 189.3s, 638MiB RSS
After: 45.8s, 5GiB RSS

If we can do something more efficient with loading the MVCC stats, I think we can substantially reduce the time further.

2018-10-20 03:36 UTC, benesch commented
> The performance at startup is markedly better. With 700,000 ranges:
>
> Before: 189.3s, 5GiB RSS
> After: 45.8s, 638MiB RSS
> 
> If we can do something more efficient with loading the MVCC stats, I think we can substantially reduce the time further.

Can we parallelize loading the replicas? Is there some blocker there that I'm not seeing?

2018-10-20 11:18 UTC, spencerkimball commented
I tried to parallelize by NumProc (or whatever the runtime variable is) and it didn't seem to have much of an impact. That was a while ago though and I didn't pursue it, so I think the experiment should be retried. If there were any way to read all of the MVCCStats in a linear fashion and then match them to the range descriptors post-hoc in one pass, it would be much faster. One problem is that the MVCCStats have been combined into an aggregate state and there's an inline migration which chooses which way to load them. Again, I haven't started down that path in earnest so this is just what I vaguely recall from a few months ago when I was first experimenting with this. I think though that there room for improvement and this is already a big improvement.

The push here is to allow the replicas to be made non-resident again after being resident so we can keep memory used fot replicas at a relatively small size.

2018-10-22 09:44 UTC, tschottdorf commented
> I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.

Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/

I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

2018-10-22 10:04 UTC, tschottdorf commented
> I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.

Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/

I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

2018-10-22 10:04 UTC, tschottdorf commented
> I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.

Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/

I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

2018-10-22 10:08 UTC, tschottdorf commented
> I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.

Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/

I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

2018-10-22 11:04 UTC, tschottdorf commented
> I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.

Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/

I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

2018-10-22 12:29 UTC, spencerkimball commented
The third commit further optimizes to 14.9s by parallelizing the two scans.

2018-10-22 12:49 UTC, spencerkimball commented
> > I made a second commit which for some reason is not showing up here even though it definitely pushed to this branch.
> 
> Github outage, see https://blog.github.com/2018-10-21-october21-incident-report/
> 
> I wasn't able to glean this from the commit message (perhaps augment it a bit), but when are making replicas non-resident (i.e. when do you kick them out of memory). Is it when they quiesce or is there some more active approach too that limits the number of replicas that can be active simultaneously? I'm asking because in #31125 we see that ~500k is definitely too many replicas to have in memory, unquiesced. We also see in #31580 that even with quiescence being an option, a hiccup on node liveness can lock the system in a state in which all replicas are unquiesced so that running with lots of replicas can be a fragile state. (PS there are probably still somewhat low hanging performance fruit there that maybe make 500k ranges actually "manageable").

@tschottdorf Nothing in this commit kicks replicas out of memory. That's another PR, which must ref count active replicas in order to safely make them non-resident. The way it works is to only kick a replica out when its qps is zero. Correctly dealing with stats otherwise would be difficult or impossible. I'll need to look at the cited issues more closely to determine what, if anything, this work can do to prevent the badness you reference when many replicas aren't quiescable.

2018-10-22 20:41 UTC, nvb requested changes
> Reviewed 14 of 18 files at r1, 3 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_status_test.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPRvybbAtHHBs27XX35:-LPRvybbAtHHBs27XX36:b-oyvgiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/client_status_test.go#L82)):*
> ```Go
> 		// Subset of ranges including first.
> 		{"a", "c", 1, 3},
> 		// middle subset of ranges.
> ```

nit: `s/m/M/`
___
*[pkg/storage/replica.go, line 4866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPRwbTv7Pq1LnVB-hAJ:-LPRwbTv7Pq1LnVB-hAK:b-z5l37s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica.go#L4866)):*
> ```Go
> 			continue
> 		}
> 		// In common operation, we only quiesce when all followers are
> ```

I think this is skewing with https://github.com/cockroachdb/cockroach/pull/31112.
___
*[pkg/storage/replica_shim.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS-j3ZBb_UJwJCWevI:-LPS-j3ZBb_UJwJCWevJ:br1d9s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L30)):*
> ```Go
> )
> 
> // ReplicaShim holds either a RangeDescriptor or an initialized
> ```

How does this interact with `ReplicaPlaceholder` objects? How does it interact with uninitialized replicas? Is there a way we can merge all of these concepts, or at least make sure their relationship to one-another is easy to understand?
___
*[pkg/storage/replica_shim.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS0YrH-S0ir6_QgsZN:-LPS0YrH-S0ir6_QgsZO:b-supp5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L37)):*
> ```Go
> 	replica *Replica // non-nil if resident
> 
> 	// Fields below not valid if replica is non-nil.
> ```

I think it's worth pulling this into a separate struct so that we can easily zero it out when we pull a replica into memory.
___
*[pkg/storage/replica_shim.go, line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS21SQ4bzC9GQzvMCa:-LPS21SQ4bzC9GQzvMCb:bd4hckw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L199)):*
> ```Go
> 		Leaseholder:     holder,
> 		LeaseType:       roachpb.LeaseEpoch,
> 		Quiescent:       true,
> ```

`// non-resident replicas are always quiescent`
___
*[pkg/storage/replica_shim.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS1y19-KJ52CyUp1xu:-LPS1y19-KJ52CyUp1xv:b-gl3ov0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L217)):*
> ```Go
> }
> 
> func (rs *ReplicaShim) startKey() roachpb.RKey {
> ```

mention `rangeKeyItem` here.
___
*[pkg/storage/store.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS5Idy5PmU19ivnyw_:-LPS5Idy5PmU19ivnywa:bj77ygf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L367)):*
> ```Go
> 		} else {
> 			var err error
> 			repl, err = rs.store.GetReplica(shim.RangeID())
> ```

Shouldn't we avoid this lookup for resident replicas?
___
*[pkg/storage/store.go, line 2036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS78s51sJ4BNu21ZEo:-LPS78s51sJ4BNu21ZEp:b-7ig0bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2036)):*
> ```Go
> 		}
> 		rep.SetZoneConfig(shim.zone)
> 		shim.replica = rep
> ```

This seems like it should be a method on `ReplicaShim`, along with clearing the other fields.
___
*[pkg/storage/store.go, line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS9_61B8SewJ4N00nF:-LPS9_61B8SewJ4N00nG:b-u814cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2044)):*
> ```Go
> }
> 
> // mustGetReplica fetches a replica by Range ID. Any error
> ```

I would expect a method called "mustXXX" to always fatal if it failed. This has a strange contract where it only fatals for some errors.
___
*[pkg/storage/store.go, line 1319 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPSUsCdAA3CKOOz7O-f:-LPSUsCdAA3CKOOz7O-g:b-87r43l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba32284de6261a427f338c8f6e8c68ed08cf43dc/pkg/storage/store.go#L1319)):*
> ```Go
> 	// creating replica shims.
> 	statsMap := map[roachpb.RangeID]enginepb.MVCCStats{}
> 	if _, err = engine.MVCCIterate(ctx, s.engine,
> ```

A few nits here that should help speed things up:
1. `MVCCIterate` is more heavy-weight than you need. You can avoid a lot of memory copying by using an `engine.Iterator` directly and decoding keys and protos straight from unsafe buffers
2. Pull the protos out of the loop to avoid allocations there


<!-- Sent from Reviewable.io -->

2018-10-24 18:00 UTC, spencerkimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 4866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPRwbTv7Pq1LnVB-hAJ:-LPagKW98Ui41bk2mhgQ:b-3wtw0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica.go#L4866)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this is skewing with https://github.com/cockroachdb/cockroach/pull/31112.
</blockquote></details>

Yikes, thanks for pointing that out. This was a bad rebase outcome.
___
*[pkg/storage/replica_shim.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS-j3ZBb_UJwJCWevI:-LPagSCF7jKPztRdZs_A:b-1fea6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this interact with `ReplicaPlaceholder` objects? How does it interact with uninitialized replicas? Is there a way we can merge all of these concepts, or at least make sure their relationship to one-another is easy to understand?
</blockquote></details>

It works with `ReplicaPlaceholder` objects in exactly the same way that `Replica` objects did – they both exist together in the `replicaShims` map. Uninitialized replicas also are embedded in `ReplicaShims`. There's a 1:1 correspondence between how `Replica`s were used / referenced by a `Store` and how `ReplicaShim`s are now used / referenced. In other words, `ReplicaShim` has replaced `Replica` in all of the `Store`'s top-level data structures.
___
*[pkg/storage/replica_shim.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS0YrH-S0ir6_QgsZN:-LPaucyK1EbEHbfYsX6O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think it's worth pulling this into a separate struct so that we can easily zero it out when we pull a replica into memory.
</blockquote></details>

Done.
___
*[pkg/storage/replica_shim.go, line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS21SQ4bzC9GQzvMCa:-LPaul1v63zlOSeABY3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L199)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`// non-resident replicas are always quiescent`
</blockquote></details>

Done.
___
*[pkg/storage/replica_shim.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS1y19-KJ52CyUp1xu:-LPautrm3lXFBGTF2T8m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L217)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

mention `rangeKeyItem` here.
</blockquote></details>

Done.
___
*[pkg/storage/store.go, line 367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS5Idy5PmU19ivnyw_:-LPav67d-lMuoJzTV7ht:b-1jja7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L367)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't we avoid this lookup for resident replicas?
</blockquote></details>

Easier to just call GetReplica than to have another if/else block here. It's cheap if the replica is already resident.
___
*[pkg/storage/store.go, line 2036 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS78s51sJ4BNu21ZEo:-LPb0SnxCmBw-1yeydxC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2036)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems like it should be a method on `ReplicaShim`, along with clearing the other fields.
</blockquote></details>

Done.
___
*[pkg/storage/store.go, line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS9_61B8SewJ4N00nF:-LPbDOTo7KTB5I8qL6UT:bxjoh3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2044)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would expect a method called "mustXXX" to always fatal if it failed. This has a strange contract where it only fatals for some errors.
</blockquote></details>

The problem here is the weirdness of the `GetReplica` contract, which returns an error if the replica isn't found, where the majority of callers actually just want to ignore that error and continue. Since `RangeNotFoundError` isn't considered a fatal error for most callers who want the `mustGetReplica` semantics, I've changed things around a bit here to just return a `*Replica`, which might be nil if not found. Don't know if this addresses your concern, but the point of this method is to avoid checking the error for `RangeNotFoundError` across 10 call sites.
___
*[pkg/storage/store.go, line 1319 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPSUsCdAA3CKOOz7O-f:-LPayDbA7-H6VrF7_woQ:b-zb7bkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba32284de6261a427f338c8f6e8c68ed08cf43dc/pkg/storage/store.go#L1319)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A few nits here that should help speed things up:
1. `MVCCIterate` is more heavy-weight than you need. You can avoid a lot of memory copying by using an `engine.Iterator` directly and decoding keys and protos straight from unsafe buffers
2. Pull the protos out of the loop to avoid allocations there
</blockquote></details>

I'm going to punt on the changes to the iteration, but I've made the suggested changes around avoiding allocations and it seemed to have a slight positive impact.


<!-- Sent from Reviewable.io -->

2018-10-26 05:17 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r5, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-:-LPincs6EEsYPIAVjeEN:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_shim.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS-j3ZBb_UJwJCWevI:-LPijrhh5JkmB4vbjyBK:b-d13a2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L30)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

It works with `ReplicaPlaceholder` objects in exactly the same way that `Replica` objects did – they both exist together in the `replicaShims` map. Uninitialized replicas also are embedded in `ReplicaShims`. There's a 1:1 correspondence between how `Replica`s were used / referenced by a `Store` and how `ReplicaShim`s are now used / referenced. In other words, `ReplicaShim` has replaced `Replica` in all of the `Store`'s top-level data structures.
</blockquote></details>

So to visualize this, we now have the following states that a Replica can be in:
```
                                    replicasByKey
                                       (oneof)
                                      /      \
                                    /          \
                                  /              \
                       ReplicaShim                ReplicaPlaceholder
                          (oneof)
                         /      \
                       /          \
                     /              \
                 Replica        nonResidentReplica
                 (oneof)
                /      \
              /          \
            /              \
Replica.initialized  !Replica.initialized
```

I'm worried about this ever-growing complexity because it makes the code harder to reason about. Can any of these states be collapsed into the same level or even better, combined? For instance, is there a reason to keep the non-initialized Replica state if we also have a non-resident Replica state? It doesn't need to hold up this PR, but I think it would benefit us to think about this.

@benesch you've worked with this code most closely over the past few months. I'm curious if you have any suggestions here or strong feelings about what should and shouldn't be done. 
___
*[pkg/storage/store.go, line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS9_61B8SewJ4N00nF:-LPijShL9lvWvVCoTKJZ:b6px6d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2044)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

The problem here is the weirdness of the `GetReplica` contract, which returns an error if the replica isn't found, where the majority of callers actually just want to ignore that error and continue. Since `RangeNotFoundError` isn't considered a fatal error for most callers who want the `mustGetReplica` semantics, I've changed things around a bit here to just return a `*Replica`, which might be nil if not found. Don't know if this addresses your concern, but the point of this method is to avoid checking the error for `RangeNotFoundError` across 10 call sites.
</blockquote></details>

Yeah, that's better.


<!-- Sent from Reviewable.io -->

2018-10-26 09:10 UTC, tschottdorf commented
I haven't given this a close review, but from the looks of it it's the type of change that could introduce a number of issues. @benesch could you work with @spencerkimball to vet this before it merges (once it's in there's no way to "turn it off")? I'm thinking a roachtest run and a nightly stress run. For the roachtest run, unfortunately things are already pretty busted right now but I hope that #31914 can improve the situation.

2018-10-26 13:09 UTC, petermattis requested changes
The speedup here is impressive, though I echo @tschottdorf's concern that this could be destabilizing. Let's hold off on merging this until we've got the roachtest stability issues under control. I think that is close, though it is hard to put a precise time bound on what that stability will be achieved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-:-LPkUP0L5tqagtjTOhnO:bo9mpbk)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-26 18:03 UTC, spencerkimball reviewed
The speedup here is now down to `9.7s` after reducing allocations and getting rid of migrations which have already run, but were running nevertheless anew at every startup.

I'll work with Nikhil to do roachtest and nightly stress runs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-:-LPkhHji6XexWon7yx4H:b-yvp1go)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_shim.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS-j3ZBb_UJwJCWevI:-LPlQkxiCefTLjGBOduO:b4fvh10) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/replica_shim.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

So to visualize this, we now have the following states that a Replica can be in:
```
                                    replicasByKey
                                       (oneof)
                                      /      \
                                    /          \
                                  /              \
                       ReplicaShim                ReplicaPlaceholder
                          (oneof)
                         /      \
                       /          \
                     /              \
                 Replica        nonResidentReplica
                 (oneof)
                /      \
              /          \
            /              \
Replica.initialized  !Replica.initialized
```

I'm worried about this ever-growing complexity because it makes the code harder to reason about. Can any of these states be collapsed into the same level or even better, combined? For instance, is there a reason to keep the non-initialized Replica state if we also have a non-resident Replica state? It doesn't need to hold up this PR, but I think it would benefit us to think about this.

@benesch you've worked with this code most closely over the past few months. I'm curious if you have any suggestions here or strong feelings about what should and shouldn't be done. 
</blockquote></details>

Yes this graph is correct, except uninitialized replicas are not stored in `replicasByKey`; they're in the `replicaShims` map. The uninitialized replica map actually just provides a boolean for any given replica for whether the replica has been added yet to `replicasByKey` after being initialized. The reason is that once the replica's range descriptor has been set, we lose the context of whether the replica was previously uninitialized and hasn't yet been added to `replicasBykey`.
___
*[pkg/storage/store.go, line 2044 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-LPS9_61B8SewJ4N00nF:-LPlUVeGAi5bpSmL06BD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dbc1b98104e25ceca97b8d56649daa2c02b241f/pkg/storage/store.go#L2044)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, that's better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-29 17:17 UTC, spencerkimball commented
@tschottdorf @petermattis: both nightly stress and roachtest seem to be fine with this change. I'm relying on @benesch to interpret the non-culpability around pre-existing roachtest issues: https://teamcity.cockroachdb.com/viewLog.html?buildId=988969&tab=queuedBuildOverviewTab

2018-11-14 18:59 UTC, bdarnell reviewed
Tobi and I are concerned about the potential stability impact of this change, especially since we're still handling the fallout from 2.1 changes like the contention queue and async writes. Since we're not currently planning to push for higher scalability in this dimension for 2.2, I'd rather put this PR on hold even if that means rewriting it when we're ready to tackle the issue. When that day comes, I'd like to see a larger refactoring that unifies replica shims with initialized and uninitialized replicas and replica placeholders instead of bolting a new not-quite-replica type on top of the multiple existing ones. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31663#-:-LRIZcyq9g3Q1IOvLZdz:bf5opm9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2020-03-10 16:33 UTC, bobvawter commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=31663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=31663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=31663) it.</sub>

2026-06-08 16:20 UTC, closed without merging