roachtest: port docker-based cdc tests to roachtest
cockroachdb/cockroach pull request #31707
Opened 2018-10-22 20:23 UTC by danhhz

The docker ones occasionally flaked on teamcity. The acceptance test
momentum right now is definitely with roachtests, so move to them so we
get all the hottest bug fixes.

This also helps set up end-to-end avro testing, which was going to be
hard with the docker based tests because some port nonsense. (The full
gory details are in a huge comment in the file this commit deletes.)

Also makes the cdc roachtests work with --local.

Also make the bank workload's update fire more often. Previously it only
did anything if the account had enough balance to cover the transfer.
This models the real world, but in the test (where the invariant is just
that the accounts sum to 0) it was just making extra work.

Closes #30740
Closes #27292

Release note: None

2018-10-22 21:10 UTC, danhhz commented
The teamcity failure made me realize that we don't currently have a way to run this on every PR because of the enterprise license requirement. It was using the TestingEnableEnterprise hook before but that doesn't work with a binary. And there are security concerns with doing it via env vars in an every-pr build. Maybe just running it in the nightlies is sufficient. Thoughts @mrtracy?

2018-10-23 07:20 UTC, mrtracy requested changes
As for the inability to run these on every PR; is there anything being captured by the bank test (and existing roachtests) that isn't being effectively captured by unit tests, other than kafka interaction?  And, is there any way for us to get any effective kafka sink tests as unit tests?

This roachtest still provides value, I think hooking the validator up to kafka is a good innovation here.  However, we need to make sure we're not being too skimpy in our checkin tests.

2018-10-23 07:20 UTC, mrtracy commented on pkg/cmd/roachtest/cdc.go
> +func runCDCErrors(ctx context.Context, t *test, c *cluster) {
This doesn't need to be a roachtest at all; none of these cases even contact kafka!

2018-10-23 07:20 UTC, mrtracy commented on pkg/cmd/roachtest/cdc.go
> +		l, err := c.l.ChildLogger(`changefeed`)
Apparently we should use `t.l.ChildLogger`, instead of `c.`.  Don't know why, was just informed of that in my last PR though.

2018-10-23 07:20 UTC, mrtracy commented on pkg/cmd/roachtest/cdc.go
> +		err := c.RunE(ctx, workloadNode, `./workload run bank {pgurl:0}`)
How does this know when to stop?  To me this looks like it will run forever.

2018-10-23 14:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31707)
<!-- Reviewable:end -->

2018-10-23 15:16 UTC, danhhz reviewed
Kafka interaction is the only thing unique about these tests at this point. The only way I could think to do that with unit tests is the thing I'm deleting. It was super fragile, hard to extend, and took weeks to get set up, I've really become convinced it wasn't the way to go. (Seriously, go read the huge comment block in the file I deleted in this commit.)

Now that I think about it, we may be able to bring these back on merge-to-master tests, but I'd like to leave that for a a followup.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-:-LPWUAomDAD_DsMu2pQu:bo6zv4x)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cdc.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-LPWN2QU4_YRxzZszCEH-r1-200:-LPWN50t2jl-XO7dyF12:bx27rdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f35c0c4375a8e8ff6688a2fbd5ea6991e2bb72/pkg/cmd/roachtest/cdc.go#L200)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

How does this know when to stop?  To me this looks like it will run forever.
</blockquote></details>

it's cancelled using the context when the below goroutine exits: `defer workloadCancel()`
___
*[pkg/cmd/roachtest/cdc.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-LPWN2QU4_YRxzZszCEH-r1-208:-LPWNEteB9BrKxU4yEQx:b-7lihc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f35c0c4375a8e8ff6688a2fbd5ea6991e2bb72/pkg/cmd/roachtest/cdc.go#L208)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Apparently we should use `t.l.ChildLogger`, instead of `c.`.  Don't know why, was just informed of that in my last PR though.
</blockquote></details>

Oh, must be part of andrei's refactor. Done
___
*[pkg/cmd/roachtest/cdc.go, line 275 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-LPWN2QU4_YRxzZszCEH-r1-275:-LPWT-Ia54cqYdLyeXVj:bts85zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/85f35c0c4375a8e8ff6688a2fbd5ea6991e2bb72/pkg/cmd/roachtest/cdc.go#L275)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

This doesn't need to be a roachtest at all; none of these cases even contact kafka!
</blockquote></details>

Heh, thanks for pushing me on my laziness. It was connecting to the sink before doing these checks, but that's silly. Done

Took this opportunity to clean up TestChangefeedErrors which was identical between sinkless and enterprise, so it was needlessly running twice.


<!-- Sent from Reviewable.io -->

2018-10-23 16:10 UTC, benesch commented
> Now that I think about it, we may be able to bring these back on merge-to-master tests, but I'd like to leave that for a a followup.

I'd recommend against doing that, actually. If you fail the merge-to-master build you'll prevent binaries from getting built. (And if you somehow soft fail it, no one will ever notice that it failed.)

Maybe I'm misunderstanding what you meant, though. I think a TeamCity build that separately listened for pushes to master could be workable.

2018-10-23 16:16 UTC, danhhz commented
Yeah, I'm not sold on this, so happy to give up on it if it doesn't make sense. Just to be clear we're talking about the same thing, my strawman is the test wouldn't be run while iterating on a PR, but would be run by bors and prevent the merge if we somehow broke it. Also a concern here is having something fail only when bors-ing, which is going to be even more frustrating than usual if it flakes.

2018-10-23 23:34 UTC, mrtracy commented
This is LGTM, questions about nightly tests aside.

2018-10-23 23:34 UTC, mrtracy approved these changes

2018-10-24 14:50 UTC, danhhz commented
@benesch came up with a great idea about how to use a Vault plugin to solve the every-pr enterprise license problem for good. In the meantime, it's not ideal, but I'm comfortable with only running these tests in the nightly build.

TFTR!

bors r=mrtracy

2018-10-24 15:22 UTC, merged

2018-10-24 18:17 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31707)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cdc.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-LPbHbWH0p9LaJCfNH69:-LPbHbWICT3cVOJtsn9f:b-jwy7i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fecc2288bf895bdd9b6c86877cfdb28b1b25567/pkg/cmd/roachtest/cdc.go#L360)):*
> ```Go
> 		Nodes:      nodes(4),
> 		Stable:     true, // DO NOT COPY to new tests
> 		SubTests: []testSpec{{
> ```

Any reason for a test with a single subtest (as opposed to just a test)? I don't think this arrangement currently carries any semantics; does it?
Asking cause I'm generally trying to get rid of subtests.


<!-- Sent from Reviewable.io -->

2018-10-24 18:18 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31707)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/cdc.go, line 364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31707#-LPbIA9LAM8wdy_dcM3s:-LPbIA9LAM8wdy_dcM3t:b8n9j9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fecc2288bf895bdd9b6c86877cfdb28b1b25567/pkg/cmd/roachtest/cdc.go#L364)):*
> ```Go
> 			Stable: true, // DO NOT COPY to new tests
> 			Run: func(ctx context.Context, t *test, c *cluster) {
> 				c.Wipe(ctx)
> ```

also, is there a point to this `wipe()`?


<!-- Sent from Reviewable.io -->

2018-10-24 18:19 UTC, danhhz commented
There will be more tests here in the future, but I'm fine making this not a subtest