exec: columnarized N:1 inner hash joiner
cockroachdb/cockroach pull request #31703
Opened 2018-10-22 18:22 UTC by changangela

Fixes #31375.

This operator performs a N-1 vectorized int64 inner hash join where the left input source's equality column must be unique.

For now, the equality columns must be `int64` values because none of the other types have hash/rehash functions implemented.

Benchmark results:
```
BenchmarkHashJoiner/rows=2048-8         	   10000	    169744 ns/op	 772.17 MB/s
BenchmarkHashJoiner/rows=4096-8         	    5000	    274218 ns/op	 955.97 MB/s
BenchmarkHashJoiner/rows=16384-8        	    2000	    897532 ns/op	1168.29 MB/s
BenchmarkHashJoiner/rows=262144-8       	     100	  13079283 ns/op	1282.73 MB/s
BenchmarkHashJoiner/rows=4194304-8      	       5	 200591222 ns/op	1338.22 MB/s
BenchmarkHashJoiner/rows=67108864-8     	       1	6687757443 ns/op	 642.21 MB/s
PASS
ok  	github.com/cockroachdb/cockroach/pkg/sql/exec	16.227s
```

2018-10-22 22:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31703)
<!-- Reviewable:end -->

2018-10-22 23:32 UTC, jordanlewis reviewed
Haven't fully reviewed yet, but here's what I've got so far.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LPT6l_P83-JLU2m8Sq4:b-3z5l16)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT1jA3E-196hyUG26Z:-LPT1jA3E-196hyUG26_:bre1rg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/colvec.go#L171)):*
> ```Go
> 
> func (m *memColumn) Append(vec ColVec, colType types.T, toLength uint64, fromLength uint16) {
> 	switch colType {
> ```

You should use `execgen` to generate this function.
___
*[pkg/sql/exec/colvec.go, line 198 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT1sMCD-_cxpoEiHv-:-LPT1sMCD-_cxpoEiHv0:bi546rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/colvec.go#L198)):*
> ```Go
> 	// todo (changangela): handle the case when nSel > ColBatchSize
> 	switch colType {
> 	case types.Bool:
> ```

Should template this function with `execgen`.
___
*[pkg/sql/exec/hashjoiner.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPSxp_7A1H2XhLDOLsn:-LPSxp_7A1H2XhLDOLso:b-hr37vr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40d45db20196ad26f95a381a53b0609304809e2/pkg/sql/exec/hashjoiner.go#L32)):*
> ```Go
> 	// phase. Output columns are stored and a hash map is constructed from the
> 	// equality columns.
> 	// todo(changangela): dynamically determine which side to store (which side is
> ```

Probably we should not do this - we should expect that we're configured to have the small side known at runtime.
___
*[pkg/sql/exec/hashjoiner.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT0sP78C-bpMkP2ftE:-LPT0sP78C-bpMkP2ftF:b6yjv9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40d45db20196ad26f95a381a53b0609304809e2/pkg/sql/exec/hashjoiner.go#L48)):*
> ```Go
> 	// first stores the id of the first key that resides in each bucket. This id
> 	// is used to determine the corresponding equality column key as well as
> 	// output column values.
> ```

does `id` here mean index into the keys and values ColVecs? Be explicit about that - it'll help readers.
___
*[pkg/sql/exec/hashjoiner.go, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT-zwPDsV_220st8Cz:-LPT-zwQ8fbMsAigikmD:bngzrso) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40d45db20196ad26f95a381a53b0609304809e2/pkg/sql/exec/hashjoiner.go#L196)):*
> ```Go
> 
> 	// prepare the output batch by allocating with the correct column types
> 	hj.outFlow = NewMemBatch(outColTypes...)
> ```

nit: we should s/outFlow/batch/ now that we're using the cockroach names.
___
*[pkg/sql/exec/hashjoiner.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT2A0a0HQwxSRSUPxz:-LPT2A0a0HQwxSRSUPy-:byraxa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L45)):*
> ```Go
> type hashJoinerSpec struct {
> 
> 	// leftEqCol and rightEqCol specify the indices of the joint constraint left
> ```

s/joint/join/
___
*[pkg/sql/exec/hashjoiner.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT2HpjCbmNiUP5obFu:-LPT2HpjCbmNiUP5obFv:bg16apv) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L67)):*
> ```Go
> // behavior is undefined. An inner join is performed and there is no guarantee
> // on the ordering of the output columns.
> type hashJoinerInt64Op struct {
> ```

When this gets templated with `execgen`, we should name it more accurately. It should be called something like `hashJoinEqInnerDistinctInt64Op` or something... we'll probably need to invent a better name taxonomy. But the name needs to have the specifics - it's an inner, equality hash join that requires distinct values on the left, against int64s.
___
*[pkg/sql/exec/hashjoiner.go, line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT3PpH2Ze0-opBpO7f:-LPT3PpH2Ze0-opBpO7g:bm6i7ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L296)):*
> ```Go
> 		eqCol := batch.ColVec(eqColId)
> 
> 		// groupID stores the id that maps to the joining rows of the build table.
> ```

Be more explicit about what the "keys and values" of this slice mean, exactly.
___
*[pkg/sql/exec/hashjoiner.go, line 352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT4QK738tQf_bwxS8Z:-LPT4QK738tQf_bwxS8_:b-vutp13) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L352)):*
> ```Go
> // toCheck. If the bucket has reached the end, the key is rejected. The toCheck
> // list is reconstructed to only hold the indices of the eqCol keys that have
> // not been found.
> ```

What is the return value of this?
___
*[pkg/sql/exec/hashjoiner.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT64J5ChM4tiaKYEec:-LPT64J5ChM4tiaKYEed:b-3tb8wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L367)):*
> ```Go
> 			if id := groupID[toCheck[i]]; id != 0 {
> 				// the index of a key is the id offset by 1
> 				if keys[id-1] != col[toCheck[i]] {
> ```

So is the opposite of this condition a match? Put a comment that explains this.
___
*[pkg/sql/exec/hashjoiner.go, line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT3kc7Bs9XNsYzz1JL:-LPT3kc7Bs9XNsYzz1JM:b-d3oede) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L388)):*
> ```Go
> }
> 
> // collectResults prepares the outFlow with the joined output columns where the
> ```

nit: s/outFlow/batch/
___
*[pkg/sql/exec/hashjoiner.go, line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT6g2uAR5lQ8JEYQsl:-LPT6g2uAR5lQ8JEYQsm:bgzyc5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L393)):*
> ```Go
> 	groupID []uint64, batch ColBatch, batchSize uint16, outCols []int, outColTypes []types.T,
> ) {
> 	buildID := make([]uint64, batchSize)
> ```

These allocations will be very expensive. You should put these slices in the prober and reuse them.


<!-- Sent from Reviewable.io -->

2018-10-23 19:35 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT1jA3E-196hyUG26Z:-LPXLUJK370qxWWNW9hD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/colvec.go#L171)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should use `execgen` to generate this function.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colvec.go, line 198 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT1sMCD-_cxpoEiHv-:-LPXLUk_A3_p5siy4G9A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/colvec.go#L198)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should template this function with `execgen`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPSxp_7A1H2XhLDOLsn:-LPXLVot2416K5tPWrUu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40d45db20196ad26f95a381a53b0609304809e2/pkg/sql/exec/hashjoiner.go#L32)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Probably we should not do this - we should expect that we're configured to have the small side known at runtime.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT0sP78C-bpMkP2ftE:-LPXLwYn8kQYYbG7u5p9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40d45db20196ad26f95a381a53b0609304809e2/pkg/sql/exec/hashjoiner.go#L48)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

does `id` here mean index into the keys and values ColVecs? Be explicit about that - it'll help readers.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT2A0a0HQwxSRSUPxz:-LPXLdvn-CyqMnyrkmtw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L45)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

s/joint/join/
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT2HpjCbmNiUP5obFu:-LPXLtEVEgb3aNz4TPe9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L67)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

When this gets templated with `execgen`, we should name it more accurately. It should be called something like `hashJoinEqInnerDistinctInt64Op` or something... we'll probably need to invent a better name taxonomy. But the name needs to have the specifics - it's an inner, equality hash join that requires distinct values on the left, against int64s.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT3PpH2Ze0-opBpO7f:-LPXN7xS6f5sNE3YQtSU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L296)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Be more explicit about what the "keys and values" of this slice mean, exactly.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 352 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT4QK738tQf_bwxS8Z:-LPXNKqJ4RDxdbP_AG-_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L352)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What is the return value of this?
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT64J5ChM4tiaKYEec:-LPXOJmfBwZIxOrAXTfO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L367)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

So is the opposite of this condition a match? Put a comment that explains this.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 393 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LPT6g2uAR5lQ8JEYQsl:-LPXPsex8JpfD0oLeR67:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86fbdc7a32949d3e62857781a30b5e5a27e2f97d/pkg/sql/exec/hashjoiner.go#L393)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These allocations will be very expensive. You should put these slices in the prober and reuse them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-29 15:01 UTC, jordanlewis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/hashjoiner.go, line 79 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Hhwt3nbT3HTsu5Gy:-LQ-HhwuCiZk0irF2Vid:b-r8uhby) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L79)):*
> ```Go
> 	// ht, if not nil, holds the hashTable that is populated during the build
> 	// phase and used during the probe phase.
> 	ht *hashTable
> ```

When would these fields be nil? Seems odd to say "if not nil" in each comment if they will always be populated.
___
*[pkg/sql/exec/hashjoiner.go, line 259 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-ItaI3Gw7WENmGsSf:-LQ-ItaI3Gw7WENmGsSg:b7ugj92) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L259)):*
> ```Go
> func (ht *hashTable) finalizeHash(buckets []uint64, nKeys uint64) {
> 	// todo(changangela): modulo a power of 2 could be made significantly faster
> 	// (20% speed improvement in benchmarks) if we use bitwise operators instead.
> ```

Seems like you finished this TODO.
___
*[pkg/sql/exec/hashjoiner.go, line 265 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Io4n6lMXZVaBDWZh:-LQ-Io4n6lMXZVaBDWZi:b-2gl2hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L265)):*
> ```Go
> 		// theoretically, this could be optimized into the following (because
> 		// bucketSize is a power of 2):
> 		buckets[i] = buckets[i] & (ht.bucketSize - 1)
> ```

Update this comment since that's actually what the code does now :)

This is a cool idea.
___
*[pkg/sql/exec/hashjoiner.go, line 395 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Ja3H6YkJJLLgkN52:-LQ-Ja3H6YkJJLLgkN53:b-yh9r5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L395)):*
> ```Go
> 		sel := batch.Selection()
> 
> 		prober.lookupInitial(batchSize, sel)
> ```

Whenever a function has hidden side effects, it's good to write a comment explaining what the intent of the function is, and what it sets up below.
___
*[pkg/sql/exec/hashjoiner.go, line 414 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Jmio3buVQ3u1miwe:-LQ-Jmio3buVQ3u1miwf:bt80k71) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L414)):*
> ```Go
> 		if prober.batch.Length() > 0 {
> 			// todo (changangela): add buffering to return batches of equal length on
> 			// each call to Next()
> ```

I think it might be a decent idea to add a separate operator for this common task. That way, this code won't have to get too bloated doing this - and many other operators will need to do this as well.

Do you want to take this on? You could do it in a separate PR. 
___
*[pkg/sql/exec/hashjoiner_test.go, line 272 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KCCc-3DDX9oIbCfA:-LQ-KCCc-3DDX9oIbCfB:b1lkq8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner_test.go#L272)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 		})
> ```

Do you have any test cases where there are hash collisions, or where there are no matches for an input?
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 37 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Kb192UcVHAzxTiIm:-LQ-Kb1A5A5O-TtuZF6L:b-screoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L37)):*
> ```Go
> ) {
> 	{{range .}}
> 	if colType == types.{{.ExecType}} {
> ```

Change to switch/case.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 49 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KZpe6KDfTWrHkYEP:-LQ-KZpe6KDfTWrHkYEQ:b-idymc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L49)):*
> ```Go
> ) {
> 	{{range .}}
> 	if colType == types.{{.ExecType}} {
> ```

You should change this to be a switch/case. It will be much faster.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 54 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KWNIDxAngxMMi5RJ:-LQ-KWNIDxAngxMMi5RK:bgu02q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L54)):*
> ```Go
> 
> 		// todo(changangela): using this approach causes large benchmarks to be
> 		// exponentially slow. why?
> ```

Hmm, what do you mean?
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 76 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KcNFAkGZJ9OnQlAI:-LQ-KcNFAkGZJ9OnQlAJ:bjpgju9) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L76)):*
> ```Go
> 	// todo (changangela): handle the case when nSel > ColBatchSize
> 	{{range .}}
> 	if colType == types.{{.ExecType}} {
> ```

Change to switch/case
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 90 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KdNt1LuqOuJpTVx4:-LQ-KdNt1LuqOuJpTVx5:b-sqkd7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L90)):*
> ```Go
> func (m *memColumn) CopyWithSelInt16(vec ColVec, sel []uint16, nSel uint16, colType types.T) {
> 	{{range .}}
> 	if colType == types.{{.ExecType}} {
> ```

Ditto, switch/case
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 46 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KsAbCQOKcBcnojwk:-LQ-KsAbCQOKcBcnojwl:btrrjjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L46)):*
> ```Go
> 		  	for i := uint64(0); i < nKeys; i++ {
> 					{{if .IsBool}}
> 						if keys[sel[i]] {
> ```

Hmm, I wonder if there's a cleaner way to do all of this. Perhaps you need to define functions elsewhere that do these type-specific hashes, and then pull them in in the template, rather than defining them inline...


<!-- Sent from Reviewable.io -->

2018-10-29 17:28 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/hashjoiner.go, line 79 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Hhwt3nbT3HTsu5Gy:-LQ-RUajE5KhMLmScuQS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L79)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

When would these fields be nil? Seems odd to say "if not nil" in each comment if they will always be populated.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 259 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-ItaI3Gw7WENmGsSf:-LQ-XGLKAsovXvgGu1xq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L259)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Seems like you finished this TODO.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 265 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Io4n6lMXZVaBDWZh:-LQ-XH9G3Gwu34u4FNOM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Update this comment since that's actually what the code does now :)

This is a cool idea.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 395 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Ja3H6YkJJLLgkN52:-LQ-Y2p96H3mOe7tMRF6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L395)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Whenever a function has hidden side effects, it's good to write a comment explaining what the intent of the function is, and what it sets up below.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 414 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Jmio3buVQ3u1miwe:-LQ-Y5Sq9Vc9v0LWsDZw:b4hvtc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner.go#L414)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it might be a decent idea to add a separate operator for this common task. That way, this code won't have to get too bloated doing this - and many other operators will need to do this as well.

Do you want to take this on? You could do it in a separate PR. 
</blockquote></details>

Yeah I can take this on. We can also experiment with how it affects performance to put use this separate operator.
___
*[pkg/sql/exec/hashjoiner_test.go, line 272 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KCCc-3DDX9oIbCfA:-LQ-YJhX2X0tChnYnMPB:b-zbkqzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/hashjoiner_test.go#L272)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do you have any test cases where there are hash collisions, or where there are no matches for an input?
</blockquote></details>

There are a few cases that test single/multiple column values that hash to the same bucket.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 37 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-Kb192UcVHAzxTiIm:-LQ-YUmqBzguWN4cKgwQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L37)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Change to switch/case.
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 49 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KZpe6KDfTWrHkYEP:-LQ-fqkK9-XRLer4GKhd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L49)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should change this to be a switch/case. It will be much faster.
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 54 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KWNIDxAngxMMi5RJ:-LQ-p-gY3YrFkmQml4aN:b-bz3wo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L54)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, what do you mean?
</blockquote></details>

`make` becomes very slow when the size is large. I've changed this to always append a newly initialized array of `batchSize` instead. 
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 76 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KcNFAkGZJ9OnQlAI:-LQ-pnV2-9PObPrPDJzG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L76)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Change to switch/case
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 90 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KdNt1LuqOuJpTVx4:-LQ-pnwSDUzidRp37Ooq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L90)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ditto, switch/case
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go, line 46 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ-KsAbCQOKcBcnojwk:-LQ-prE02-0OSXTBUDLw:buxqqdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/854696fcc1b4f17d4c14e1fa324ec67c6ed5f065/pkg/sql/exec/execgen/cmd/execgen/hashjoiner_gen.go#L46)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, I wonder if there's a cleaner way to do all of this. Perhaps you need to define functions elsewhere that do these type-specific hashes, and then pull them in in the template, rather than defining them inline...
</blockquote></details>

Instead of the `IsBool` and `IsBytes` flags, I'm just using the `ExecType` now. It's not too much cleaner but I don't think we can get around that `if - else if - else` statement. Defining the function to do just the type specific hashes would put the type switching inside the for loop rather than outside.


<!-- Sent from Reviewable.io -->

2018-10-30 19:11 UTC, changangela commented
It looks like the current `distsql/hash_joiner` outputs a row of left output columns followed by right output columns:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/joinerbase.go#L83

The `numMergedEqualityColumns` looks to be deprecated.

@jordanlewis can you confirm?

In the case that the right table is our build table there are two options:
1. The planner can reverse the input table ordering, but it will also need to know how to manually unmerge+reorder the output columns somehow.
2. The planner can pass a flag to the `hashJoiner` indicating which side to build, and the `hashJoiner` will output the correct ordering (this is actually pretty simple to do).

2018-10-30 19:54 UTC, jordanlewis commented
Take a look at the comment above `HashJoinerSpec` - that defines the internal schema of the HashJoiner.

2018-10-31 01:41 UTC, jordanlewis approved these changes
The new explanation blurbs are great. Nice work - just a few last comments. This <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

(Please remember to squash all the commits together before you merge!)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LQ6eoFcDtxwiFTJQ3iZ:b-vwixdx)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 52 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6dhnu9aaIzEVQkFwo:-LQ6dhnv7FWdyxU9Iyti:b-fliied) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/colvec.go#L52)):*
> ```Go
> 	Col() interface{}
> 
> 	// Append requires a ColVec of the same type and appends it's column vector
> ```

nit: s/it's/its/

I would reword these a little bit. Instead of saying appends/copies "into itself", I would say something like:

`Append appends fromLength elements of the the given ColVec to this ColVec, assuming that both ColVecs are of type colType`.

I also don't understand the `toLength` argument. I don't think you need it, but I could be mistaken.
___
*[pkg/sql/exec/colvec.go, line 62 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6eRLO5vfJxC5B9NlR:-LQ6eRLO5vfJxC5B9NlS:bgyajjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/colvec.go#L62)):*
> ```Go
> 	// CopyWithSelInt64 copies into itself another column vector, filtered by the given
> 	// selection vector.
> 	CopyWithSelInt64(vec ColVec, sel []uint64, nSel uint16, colType types.T)
> ```

For these ones, I'd say "Copy... copies vec into this ColVec, replacing the contents of this ColVec.
___
*[pkg/sql/exec/hashjoiner.go, line 21 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6h5dG3DnkvdNmYf1D:-LQ6h5dH3uJQd7hiMxmf:bgplfzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L21)):*
> ```Go
> )
> 
> // todo(changangela): support rehashing instead of large fixed bucket size
> ```

This seems like a pretty important next step.

Speaking of next steps, once this merges, could you please write down a checklist of work remaining into the issue? It would be good to get a sense for what remains in the path of making this implementation ready for production.

Things that come to my mind are null handling, memory accounting and disk spilling, but I'm sure you can think of more.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 39 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6kRuJ1D_sWOBiEBAT:-LQ6kRuJ1D_sWOBiEBAU:blv35q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L39)):*
> ```Go
> 		{{range .}}
> 		case types.{{.ExecType}}:
> 			m.col = append(m.{{.ExecType}}()[:toLength], vec.{{.ExecType}}()[:fromLength]...)
> ```

Yeah I'm not really sure the point of `toLength` - seems like you should be able to just avoid that slice - though maybe you had a reason to add it?


<!-- Sent from Reviewable.io -->

2018-10-31 02:26 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/hashjoiner.go, line 21 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6h5dG3DnkvdNmYf1D:-LQ6nc0JBmwyCyauuagR:b-cp10jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L21)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems like a pretty important next step.

Speaking of next steps, once this merges, could you please write down a checklist of work remaining into the issue? It would be good to get a sense for what remains in the path of making this implementation ready for production.

Things that come to my mind are null handling, memory accounting and disk spilling, but I'm sure you can think of more.
</blockquote></details>

Hmm, does this limitation invalidate some of the larger benchmarks you have? Surely the hash table fills up for benchmarks that have more than 2*16 rows?

Seems like we'll want to address this sooner rather than later. I guess we'll need to keep track of the number of entries and resize 
___
*[pkg/sql/exec/hashjoiner.go, line 278 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6pSXV5PxRq3857QPY:-LQ6pSXV5PxRq3857QPZ:b-dp803x) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L278)):*
> ```Go
> // the resulting hash value based on an element of the key of a specified type.
> // The current array hashing heuristic is based off of Java's
> // Arrays.hashCode(int[]) and only supports int64 elements.
> ```

This needs rewording (it no longer just supports int64s).
___
*[pkg/sql/exec/hashjoiner.go, line 297 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6pwpk4d3k0ZkO6_RE:-LQ6pwpk4d3k0ZkO6_RF:b-b7wcym) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L297)):*
> ```Go
> 	for i := uint64(0); i < nKeys; i++ {
> 		// since bucketSize is a power of 2, modulo bucketSize could be optimized
> 		// into a bitwise operation which improves benchmark performance by 20%.
> ```

I would still include the "simple implementation" in a comment to make sure it's obvious what's going on, in addition to what you already have here.

e.g.:

// In effect, the following code is equivalent to (but faster than):
// buckets[i] = buckets[i] % ht.bucketSize 
___
*[pkg/sql/exec/hashjoiner_test.go, line 295 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6o2ZD54fdGPOy2-yZ:-LQ6o2ZE1_sRsU_T3mU8:bqsn7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner_test.go#L295)):*
> ```Go
> 	batch.SetLength(ColBatchSize)
> 
> 	for _, nBatches := range []int{1 << 1, 1 << 2, 1 << 4, 1 << 8, 1 << 12, 1 << 16} {
> ```

I would consider reducing the number of batch sizes here (especially if they overflow the hash table).


<!-- Sent from Reviewable.io -->

2018-10-31 02:30 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 52 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6dhnu9aaIzEVQkFwo:-LQ6xCt2BrcikeWxNs7l:bypie1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/colvec.go#L52)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: s/it's/its/

I would reword these a little bit. Instead of saying appends/copies "into itself", I would say something like:

`Append appends fromLength elements of the the given ColVec to this ColVec, assuming that both ColVecs are of type colType`.

I also don't understand the `toLength` argument. I don't think you need it, but I could be mistaken.
</blockquote></details>

Nevermind, I see why - of course, no ColVecs have proper lengths associated with them.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 39 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6kRuJ1D_sWOBiEBAT:-LQ6x5Wk0EVY8UiSG_Wj:bypie1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L39)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah I'm not really sure the point of `toLength` - seems like you should be able to just avoid that slice - though maybe you had a reason to add it?
</blockquote></details>

Nevermind, I see why - of course, no ColVecs have proper lengths associated with them.


<!-- Sent from Reviewable.io -->

2018-10-31 03:11 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/hashjoiner.go, line 266 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ75FO15OdpSvnG6B6V:-LQ75FO15OdpSvnG6B6W:b6t81n8) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L266)):*
> ```Go
> 
> 		for i, colIdx := range outCols {
> 			ht.values[i].Append(batch.ColVec(colIdx), ht.valueColTypes[i], ht.size, batchSize)
> ```

Aren't we doing duplicate work here if eqCols and outCols overlap? Seems like there should be a single loop over the union of eqCols + outCols, instead of a loop over each of them, otherwise we'll do extra.


<!-- Sent from Reviewable.io -->

2018-10-31 14:50 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 62 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6eRLO5vfJxC5B9NlR:-LQ9SX6Z1wT-_wGj4yRA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/colvec.go#L62)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

For these ones, I'd say "Copy... copies vec into this ColVec, replacing the contents of this ColVec.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 21 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6h5dG3DnkvdNmYf1D:-LQ9SbwZ6WBKAkLjMaG-:brs8y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L21)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, does this limitation invalidate some of the larger benchmarks you have? Surely the hash table fills up for benchmarks that have more than 2*16 rows?

Seems like we'll want to address this sooner rather than later. I guess we'll need to keep track of the number of entries and resize 
</blockquote></details>

Yeah, you see definitely see performance suffering a little bit with the largest benchmark case because of this high load factor (we had `1024` buckets each with `1 << 16` elements in its chain`. But even in these cases, the `build` time still outweighs the `probe` time. It looks like for this task, chaining can be handled pretty  efficiently by the prober. I will create a follow up issue for this.
___
*[pkg/sql/exec/hashjoiner.go, line 266 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ75FO15OdpSvnG6B6V:-LQ9UOKM91lWSsuxH1-a:bbbpwia) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L266)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Aren't we doing duplicate work here if eqCols and outCols overlap? Seems like there should be a single loop over the union of eqCols + outCols, instead of a loop over each of them, otherwise we'll do extra.
</blockquote></details>

Oh yeah good point, I'm working on fixing this.
___
*[pkg/sql/exec/hashjoiner.go, line 278 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6pSXV5PxRq3857QPY:-LQ9VVS83a_01BqOc_BR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L278)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This needs rewording (it no longer just supports int64s).
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 297 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6pwpk4d3k0ZkO6_RE:-LQ9UJge-5fFAt1miezi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner.go#L297)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would still include the "simple implementation" in a comment to make sure it's obvious what's going on, in addition to what you already have here.

e.g.:

// In effect, the following code is equivalent to (but faster than):
// buckets[i] = buckets[i] % ht.bucketSize 
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner_test.go, line 295 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQ6o2ZD54fdGPOy2-yZ:-LQ9Tj4ED8vD0nWPM1x-:bq0cnfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/012885923c741ad4f614476e41d77d086be2b370/pkg/sql/exec/hashjoiner_test.go#L295)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would consider reducing the number of batch sizes here (especially if they overflow the hash table).
</blockquote></details>

The `1 << 16` takes a hit in performance and exhibits some other weird/special behavior that the other sizes don't have which I thought my be interesting to look at.


<!-- Sent from Reviewable.io -->

2018-10-31 18:57 UTC, changangela reviewed
Thanks @jordanlewis for the review! Just added some final things:
- address equal and output column overlap to save space during build phase.
- added a flag to support building the right table instead of the left table.
- reshaped output column to follow the distsql hash join output schema - added some dummy columns in output batch.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LQATdI92b11_YYkNiRF:b-digqo9)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-31 18:59 UTC, changangela reviewed
New benchmark results:
```
BenchmarkHashJoiner/rows=2048-8         	   10000	    183396 ns/op	 714.69 MB/s
BenchmarkHashJoiner/rows=4096-8         	    5000	    286295 ns/op	 915.64 MB/s
BenchmarkHashJoiner/rows=16384-8        	    2000	    849839 ns/op	1233.85 MB/s
BenchmarkHashJoiner/rows=262144-8       	     100	  11797009 ns/op	1422.16 MB/s
BenchmarkHashJoiner/rows=4194304-8      	      10	 178025754 ns/op	1507.85 MB/s
BenchmarkHashJoiner/rows=67108864-8     	       1	5977620561 ns/op	 718.51 MB/s
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LQAUMTFCh69OAOkwfb5:bvgfkik)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-01 16:11 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> mod the `AllTypes` thing.

Also, please extend your commit message with a more detailed explanation of what you're adding. It doesn't have to be fully thorough, but just explain something like "This commit adds a new exec.Operator, fooOperator, that does xyz. It supports inner joins on arbitrary numbers of equality columns, on xyz types, but only for 1:n joins where xyz." Look at some other commit messages in the repo for inspiration. We also have a doc on this (https://github.com/cockroachdb/cockroach/wiki/Git-Commit-Messages) to check out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LQF1Ap03faRpqxuqJfI:b-7rcq1)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/types/types.go, line 175 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQF0wTdDP38-BszOFD7:-LQF0wTdDP38-BszOFD8:b3qvvhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf608519dccfedaac7786e8cd838a4c8b3d6c692/pkg/sql/exec/types/types.go#L175)):*
> ```Go
> 
> // Types is a list of all the different supported column types.
> var Types = []T{
> ```

`AllTypes` has this information now and it's produced programmatically so it won't rot. You should delete this and use `AllTypes` in your code.


<!-- Sent from Reviewable.io -->

2018-11-01 17:40 UTC, changangela reviewed
TFTRs! Rebased with master and added support for Decimal/Date types into the hash joiner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-:-LQFLuBq3QzWKc3XgBf2:b-5ekuk5)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-01 17:40 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31703)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/types/types.go, line 175 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/31703#-LQF0wTdDP38-BszOFD7:-LQFM6zY6-hPXx9V5fEd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf608519dccfedaac7786e8cd838a4c8b3d6c692/pkg/sql/exec/types/types.go#L175)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

`AllTypes` has this information now and it's produced programmatically so it won't rot. You should delete this and use `AllTypes` in your code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-01 17:51 UTC, changangela commented
bors r+

2018-11-01 19:18 UTC, changangela commented
bors r+

2018-11-01 19:39 UTC, changangela commented
bors r+

2018-11-01 19:54 UTC, merged