[wip]cli: add I/O benchmarking to cockroach
cockroachdb/cockroach pull request #31897
Opened 2018-10-25 21:07 UTC by m-schneider

This PR adds a framework and a first test to write 128mb blocks to
cockroach.

See #31833

Release note: None

2018-10-25 21:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31897)
<!-- Reviewable:end -->

2018-10-26 01:37 UTC, petermattis requested changes
The interface here is awkward and unintuitive: `cockroach systembench hdd --write128`. What does 128 stand for? The term `hdd` usually refers to spinning disk, while most likely we'll be writing to a solid state drive. The term `ssd` isn't appropriate either.

I thought the plan for #31883 was to test sequential writes by writing ~32KB blocks and then calling fsync/fdatasync every 512KB of data. This would mimic how RocksDB outputs sstables. The current structure of this code overwrites the same 128MB file over and over without every calling fsync which likely makes this a benchmark of memory copy performance. 

 I think something that looked like `cockroach systembench seqwrite --write-size=32KiB --sync-size=512KiB` would be better. A slight tweak to these parameters would allow simulating the performance of the small writes that we see to the RocksDB WAL. In the future we can get fancy and allow the write size to fall into a range with `--write-size=16KiB-32KiB`. 

Nit: `sysbench` rolls off the fingers easier than `systembench`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LPhyY_W-DnT0D74O9sA:bxcy7lm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/hdd_bench.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LPi-wfv9vy4rXa6Byua:-LPi-wfv9vy4rXa6Byub:b-prghgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a53dc458c550e557ca9ec26ea2a1cb43d7e325/pkg/cli/systembench/hdd_bench.go#L118)):*
> ```Go
> 	// We're creating a temp file like this instead of using ioutil.TempFile
> 	// to open in append mode.
> 	tempName := strconv.Itoa(rand.Int()) + ".txt"
> ```

Any reason for the `.txt` suffix? It looks like you're writing random data to the file. 


<!-- Sent from Reviewable.io -->

2018-10-29 14:55 UTC, m-schneider commented
I think we do need some sort of reference to IO for the test name because once we add cpu and network benchmarks it could get confusing if we do something with a similar name for one of the other categories of tests.

There are 5 tests in https://github.com/cockroachdb/cockroach/issues/31833 and appending 128MB chunks is the most straightforward one there. This code opens the file in O_APPEND mode so it appends the 128MB, I tested by looking at the temp file and seeing it grow. The plan was to merge the general framework for the tests and then send out separate PRs for the rest of the tests in the list. You're right that the 128 should be a parameter with a default of 128. How does ioblockwrite sound? 

I agree that sysbench rolls off the tongue and fingers must better but I didn't want users to think that we implemented the actual sysbench.





<!-- Sent from Reviewable.io -->

2018-10-29 16:46 UTC, petermattis commented
> How does ioblockwrite sound?

I'd prefer something that made it clear that this is a sequential write. I don't mind putting the size or purpose of the writes in the name. Something like `seq-sstable-write`, `seq-wal-write`. Having written that, I have a minor preference for `seq-large-write` and `seq-small-write`. Note that we **never** write 128MB at a time (I'm emphasizing this because you mentioned 128MB again). We write 128MB sstables, but the sstables are generated by performing small-ish (~32KB) writes and calling fdatasync every ~512KB of data written.

> The plan was to merge the general framework for the tests and then send out separate PRs for the rest of the tests in the list. 

That's fine to me. I'm just commenting on the highest level of structure so far.

2018-10-29 18:58 UTC, m-schneider reviewed
I added flags for block size and and a sync interval.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LQ08PFO8FaMrb6LL68t:b-d5d76z)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/systembench/hdd_bench.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LPi-wfv9vy4rXa6Byua:-LQ0B8pMA0vf2PcSev0H:bm0ya40) ([raw file](https://github.com/cockroachdb/cockroach/blob/31a53dc458c550e557ca9ec26ea2a1cb43d7e325/pkg/cli/systembench/hdd_bench.go#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Any reason for the `.txt` suffix? It looks like you're writing random data to the file. 
</blockquote></details>

Nope, got rid of it.


<!-- Sent from Reviewable.io -->

2018-10-29 19:18 UTC, nvb requested changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQ0FfiaACHT4RjM5Qhk:b2bqllg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
> ```Go
> 	WriteSize = FlagInfo{
> 		Name:        "write-size",
> 		Description: `Size of blocks to write to storage device.`,
> ```

All other flags have descriptions with newlines. Let's do that here.
___
*[pkg/cli/cliflags/flags.go, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FXdV6ImrAoPI40QX:-LQ0FXdV6ImrAoPI40QY:b6esqoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L832)):*
> ```Go
> 	BenchDuration = FlagInfo{
> 		Name:        "duration",
> 		Description: `The amount of time to run workers.`,
> ```

Drop the `The` to stay consistent.
___
*[pkg/cli/systembench.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FRssAXyoMi-Ls7j7:-LQ0FRssAXyoMi-Ls7j8:b-tg8c5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench.go#L27)):*
> ```Go
> 	Short: "Runs hdd benchmark.",
> 	Long: `
> Runs sequential IO write benchmark.
> ```

"Runs the"
___
*[pkg/cli/systembench/io_bench.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0F-loBbZs57OH0LTg:-LQ0F-loBbZs57OH0LTh:bfc0mcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L38)):*
> ```Go
> 	SyncInterval int64
> 
> 	SeqWriteTest bool
> ```

Let's make this an enum so we're ready for more tests.
___
*[pkg/cli/systembench/io_bench.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0ESJr-STtpANFDE8f:-LQ0ESJr-STtpANFDE8g:b-tfminh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L56)):*
> ```Go
> // the temp file.
> type workerSeqWrite struct {
> 	latency
> ```

Does this need to be embedded?
___
*[pkg/cli/systembench/io_bench.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0DWAf5UN07I0qs0Xd:-LQ0DWAf5UN07I0qs0Xe:baiq9jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L65)):*
> ```Go
> // newWorkerSeqWrite creates a worker that writes writeSize sized
> // sequential blocks with fsync every syncInterval bytes to a file.
> func newWorkerSeqWrite(ctx context.Context, file *os.File,
> ```

This format looks off. Have you taken a look at `crlfmt`?
___
*[pkg/cli/systembench/io_bench.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0DgFq4kQYThSRWy44:-LQ0DgFq4kQYThSRWy45:b-fsoj1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L70)):*
> ```Go
> 	_, err := rand.Read(data)
> 	if err != nil {
> 		log.Error(ctx, "Failed to fill byte array with random bytes %s", err)
> ```

`log.Fatalf` unless we're going to return here.
___
*[pkg/cli/systembench/io_bench.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Dl4d4dzFaLTGrJoB:-LQ0Dl4d4dzFaLTGrJoC:bx8dqib) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L73)):*
> ```Go
> 	}
> 
> 	w := &workerSeqWrite{data: data,
> ```

Format looks off as well.
___
*[pkg/cli/systembench/io_bench.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0E751Ci250iEMWaA1:-LQ0E751Ci250iEMWaA2:bf3ihff) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L86)):*
> ```Go
> 	defer wg.Done()
> 	for {
> 		written := int64(0)
> ```

How does this work? Are we ever syncing? We're initializing `written` to 0 at the beginning of the loop and then only writing once per iteration.
___
*[pkg/cli/systembench/io_bench.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EjoO9vROs-CKoq7E:-LQ0EjoO9vROs-CKoq7F:bl8y4l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L90)):*
> ```Go
> 		if _, err := w.tempFile.Write(w.data); err != nil {
> 			w.tempFile.Close()
> 			log.Fatal(ctx, err)
> ```

We should probably run the workers in an `errgroup` and properly return errors.
___
*[pkg/cli/systembench/io_bench.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Eu_sD9YTQAWbY2JE:-LQ0Eu_sD9YTQAWbY2JF:bsnoqqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L117)):*
> ```Go
> 
> // Run runs I/O benchmarks specified by hddOpts.
> func Run(iOOpts IOOptions) error {
> ```

`s/iOOpts/ioOpts/`
___
*[pkg/cli/systembench/io_bench.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EY3C5y_qBHThtyLf:-LQ0EY3C5y_qBHThtyLg:bpa6kb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L120)):*
> ```Go
> 	ctx := context.Background()
> 
> 	// Check if the directory exists.
> ```

Think it makes sense to create the directory if it doesn't already exist?
___
*[pkg/cli/systembench/io_bench.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Ehqz6rL_H5ZVb5_G:-LQ0Ehqz6rL_H5ZVb5_H:b-9bsi0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L135)):*
> ```Go
> 		os.O_RDWR|os.O_APPEND|os.O_CREATE, 0660)
> 	if err != nil {
> 		log.Fatal(ctx, err)
> ```

Why not return the error?
___
*[pkg/cli/systembench/io_bench.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FDY1DkBO_4RBRTpC:-LQ0FDY2AZRZGgRfEPK9:bobgqm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L149)):*
> ```Go
> 	for i := range workers {
> 		wg.Add(1)
> 		workers[i] = workerCreator(ctx, tmpfile, &iOOpts)
> ```

nit: just launch the goroutine here.


<!-- Sent from Reviewable.io -->

2018-10-29 21:04 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQ0HoNT8bI-8BFBsQOw:bb6wvjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

All other flags have descriptions with newlines. Let's do that here.
</blockquote></details>

Some of the ones above don't, do we have some sort of style guideline?
___
*[pkg/cli/cliflags/flags.go, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FXdV6ImrAoPI40QX:-LQ0I1IW9b1Eo2NcL_JV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L832)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Drop the `The` to stay consistent.
</blockquote></details>

Done.
___
*[pkg/cli/systembench.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FRssAXyoMi-Ls7j7:-LQ0HnmWA345kJzDJ_Cs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench.go#L27)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"Runs the"
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0F-loBbZs57OH0LTg:-LQ0Jy7x54HL0-1_ziHJ:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L38)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's make this an enum so we're ready for more tests.
</blockquote></details>

Done. 
___
*[pkg/cli/systembench/io_bench.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0ESJr-STtpANFDE8f:-LQ0I9Rb9epAntSNXXso:bosik40) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be embedded?
</blockquote></details>

No, is there any reason not to have it embedded?
___
*[pkg/cli/systembench/io_bench.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0DWAf5UN07I0qs0Xd:-LQ0LoVB3pUkZSZRDrl-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This format looks off. Have you taken a look at `crlfmt`?
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0DgFq4kQYThSRWy44:-LQ0K7NM8pHdogyYb4VF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`log.Fatalf` unless we're going to return here.
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Dl4d4dzFaLTGrJoB:-LQ0Lox8B_RSpFTOHrIY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Format looks off as well.
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0E751Ci250iEMWaA1:-LQ0M04q39QfdfDlIzx0:b-5bbhzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L86)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this work? Are we ever syncing? We're initializing `written` to 0 at the beginning of the loop and then only writing once per iteration.
</blockquote></details>

Moved written.
___
*[pkg/cli/systembench/io_bench.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EjoO9vROs-CKoq7E:-LQ0_6Le02pcS-ZFws8G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should probably run the workers in an `errgroup` and properly return errors.
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Eu_sD9YTQAWbY2JE:-LQ0MSMlEa0l37f46iP7:bv33rdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L117)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/iOOpts/ioOpts/`
</blockquote></details>

Yes that looks better.
___
*[pkg/cli/systembench/io_bench.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EY3C5y_qBHThtyLf:-LQ0M4wq6o9PmDgbQpy0:b7clahu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L120)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Think it makes sense to create the directory if it doesn't already exist?
</blockquote></details>

I looked at other tests that don't, so I followed them. I can create if you think we should.
___
*[pkg/cli/systembench/io_bench.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0Ehqz6rL_H5ZVb5_G:-LQ0MzAO9T8QGaWjCrX_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why not return the error?
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FDY1DkBO_4RBRTpC:-LQ0N2mB-gOqYHqIEBZ_:bqmq4nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: just launch the goroutine here.
</blockquote></details>

I split the worker creation from the run for tests that have a more involved setup. We don't want to count that as part of the run.


<!-- Sent from Reviewable.io -->

2018-10-29 22:39 UTC, nvb requested changes
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQ0wycL3McNv9IAZ6ey:bw9wtay) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Some of the ones above don't, do we have some sort of style guideline?
</blockquote></details>

Yes - https://github.com/cockroachdb/cockroach/blob/master/docs/style.md. This wouldn't be in the guide though.
___
*[pkg/cli/systembench/io_bench.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0ESJr-STtpANFDE8f:-LQ0xBnJBsS3KevgAgn6:b-fmeuci) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L56)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

No, is there any reason not to have it embedded?
</blockquote></details>

Yes, if you embed a field in a struct then it's methods and fields are addressable on outer struct. That can lead to confusion and bugs, especially with people relying on code completion. For instance, what does `workerSeqWrite.mu` mean? Does it lock the entire worker? In general, only embed types if you're ok with their entire interface leaking into the embedding struct.
___
*[pkg/cli/systembench/io_bench.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EY3C5y_qBHThtyLf:-LQ0yEeX58qWtUq2f146:bh1xrza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L120)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I looked at other tests that don't, so I followed them. I can create if you think we should.
</blockquote></details>

I guess we can leave this as is and change it if we find the behavior to be annoying.
___
*[pkg/cli/systembench/io_bench.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0yazX27iBr90p9enZ:-LQ0yazX27iBr90p9en_:b-615vmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L192)):*
> ```Go
> 
> 	go func() {
> 		if err := g.Wait(); err != nil {
> ```

What is going to cause the workers to return? Do we need to cancel their contexts?


<!-- Sent from Reviewable.io -->

2018-10-30 00:43 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/context.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KYDgBDYh7ZAt3_Ct:-LQ1KYDgBDYh7ZAt3_Cu:b-lk6jc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L140)):*
> ```Go
> 	systemBenchCtx.concurrency = 1
> 	systemBenchCtx.duration = 60 * time.Second
> 	systemBenchCtx.tempDir = "/tmp/"
> ```

The directory we perform the writes in needs to be a prominent part of the command. Is a flag sufficient? Writing data to `/tmp` is not going to give accurate results as `/tmp` is usually not the disk containing the CockroachDB store.
___
*[pkg/cli/context.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KSHZ-8xOXWT1BKjU:-LQ1KSHZ-8xOXWT1BKjV:b-4uuqad) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L141)):*
> ```Go
> 	systemBenchCtx.duration = 60 * time.Second
> 	systemBenchCtx.tempDir = "/tmp/"
> 	systemBenchCtx.writeSize = 32000
> ```

Let the compiler do the work for you: `s/32000/32 << 10/g`
___
*[pkg/cli/context.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KVNJ8kFxBiD2Mqab:-LQ1KVNJ8kFxBiD2Mqac:b-ll5nov) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L142)):*
> ```Go
> 	systemBenchCtx.tempDir = "/tmp/"
> 	systemBenchCtx.writeSize = 32000
> 	systemBenchCtx.syncInterval = 512000
> ```

`s/512000/512 << 10/g`
___
*[pkg/cli/systembench.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OV47Aj4f4_VJqGYl:-LQ1OV47Aj4f4_VJqGYm:b-bdaicu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench.go#L25)):*
> ```Go
> var seqWriteBench = &cobra.Command{
> 	Use:   "seqwrite",
> 	Short: "Runs hdd benchmark.",
> ```

`Runs the sequential disk write benchmark`
___
*[pkg/cli/systembench.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OZ0S2q6h4YEXyQ4L:-LQ1OZ0S2q6h4YEXyQ4M:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench.go#L27)):*
> ```Go
> 	Short: "Runs hdd benchmark.",
> 	Long: `
> Runs the sequential IO write benchmark.
> ```

Ditto.
___
*[pkg/cli/systembench/io_bench.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OqgRCFyN_j39gmBm:-LQ1OqgRCFyN_j39gmBn:bw6if91) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L45)):*
> ```Go
> 
> // IOBenchMarkType represents an I/O benchmark.
> type IOBenchMarkType int
> ```

`s/BenchMark/Benchmark/g` (benchmark is one word, not two).
___
*[pkg/cli/systembench/io_bench.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1PSF0EQ7Fn-WNRGgm:-LQ1PSF13i35-J89ycpt:byym399) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L156)):*
> ```Go
> 	// We're creating a temp file like this instead of using ioutil.TempFile
> 	// to open in append mode.
> 	tempName := strconv.Itoa(rand.Int())
> ```

https://golang.org/pkg/io/ioutil/#TempFile is the idiomatic way to generate a unique filename.
___
*[pkg/cli/systembench/io_bench.go, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Pg1xBE37D5EbTeY2:-LQ1Pg1xBE37D5EbTeY3:b-5a5xjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L158)):*
> ```Go
> 	tempName := strconv.Itoa(rand.Int())
> 	tmpfile, err := os.OpenFile(filepath.Join(ioOpts.Dir, tempName),
> 		os.O_RDWR|os.O_APPEND|os.O_CREATE, 0660)
> ```

RocksDB never concurrently writes to the same file. It does concurrently write to different files. I'm pointing this out because `seqwrite --concurrency=2` will be testing a setup that CockroachDB never uses. Even for the WAL, RocksDB never concurrently writes to the files, but relies on a mutex to provide exclusive writes.
___
*[pkg/cli/systembench/io_bench.go, line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Q8E776DjOEcu59NP:-LQ1Q8E776DjOEcu59NQ:b-vo5j4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L278)):*
> ```Go
> 				time.Duration(cumulative.ValueAtQuantile(100)).Seconds()*1000,
> 			)
> 			break loop
> ```

Or you could `return nil` here and not utilize the named-break.


<!-- Sent from Reviewable.io -->

2018-10-30 15:15 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cli/context.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KYDgBDYh7ZAt3_Ct:-LQ4SYES9e09VI7nsxhR:b-840jq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L140)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The directory we perform the writes in needs to be a prominent part of the command. Is a flag sufficient? Writing data to `/tmp` is not going to give accurate results as `/tmp` is usually not the disk containing the CockroachDB store.
</blockquote></details>

Maybe we should keep the flag but set the default to the store directory? 
___
*[pkg/cli/context.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KSHZ-8xOXWT1BKjU:-LQ4THJlAf2Plgau7LM6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L141)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let the compiler do the work for you: `s/32000/32 << 10/g`
</blockquote></details>

Done.
___
*[pkg/cli/context.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KVNJ8kFxBiD2Mqab:-LQ4THYSALhznEd5kZTT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L142)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/512000/512 << 10/g`
</blockquote></details>

Done.
___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQ4X1s31j2CHVu6WsgQ:b-3pp07v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes - https://github.com/cockroachdb/cockroach/blob/master/docs/style.md. This wouldn't be in the guide though.
</blockquote></details>

Thanks! Is there a reason not to fix the other ones without a newline in the file?
___
*[pkg/cli/systembench.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OV47Aj4f4_VJqGYl:-LQ4TU7l2pJai9YBqrRY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench.go#L25)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`Runs the sequential disk write benchmark`
</blockquote></details>

Done.
___
*[pkg/cli/systembench.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OZ0S2q6h4YEXyQ4L:-LQ4TTqv-FkefaKq4s8a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench.go#L27)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0ESJr-STtpANFDE8f:-LQ4U7Vv8iS5wqfrDukW:bkq973u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L56)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, if you embed a field in a struct then it's methods and fields are addressable on outer struct. That can lead to confusion and bugs, especially with people relying on code completion. For instance, what does `workerSeqWrite.mu` mean? Does it lock the entire worker? In general, only embed types if you're ok with their entire interface leaking into the embedding struct.
</blockquote></details>

Ok, got it.
___
*[pkg/cli/systembench/io_bench.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0EY3C5y_qBHThtyLf:-LQ4XfZg2C9itJJxshHj:bt8khcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/systembench/io_bench.go#L120)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I guess we can leave this as is and change it if we find the behavior to be annoying.
</blockquote></details>

I think this test is usually going to be run in a specific place that should exist. But yes we can always change it.
___
*[pkg/cli/systembench/io_bench.go, line 45 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1OqgRCFyN_j39gmBm:-LQ4ToAN2HzChxd22nrU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L45)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/BenchMark/Benchmark/g` (benchmark is one word, not two).
</blockquote></details>

Done.
___
*[pkg/cli/systembench/io_bench.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1PSF0EQ7Fn-WNRGgm:-LQ4UBhaCnqP7dhanv2a:b-f8ehz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L156)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

https://golang.org/pkg/io/ioutil/#TempFile is the idiomatic way to generate a unique filename.
</blockquote></details>

That's why I commented above, it doesn't open the file in append mode by default and we need that for our tests if we have concurrent writers.
___
*[pkg/cli/systembench/io_bench.go, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Pg1xBE37D5EbTeY2:-LQ4VMLq8ITCCynoekFQ:bc9fw2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L158)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

RocksDB never concurrently writes to the same file. It does concurrently write to different files. I'm pointing this out because `seqwrite --concurrency=2` will be testing a setup that CockroachDB never uses. Even for the WAL, RocksDB never concurrently writes to the files, but relies on a mutex to provide exclusive writes.
</blockquote></details>

Ok I see, should we get rid of the concurrency flag for this altogether?  Or will we want more general benchmarks in the future? If so I can use the builtin TempFile function.
___
*[pkg/cli/systembench/io_bench.go, line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0yazX27iBr90p9enZ:-LQ4Xa0C9A36b_AEQZ_F:b-i9oblw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L192)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What is going to cause the workers to return? Do we need to cancel their contexts?
</blockquote></details>

I added a context cancel function.
___
*[pkg/cli/systembench/io_bench.go, line 278 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Q8E776DjOEcu59NP:-LQ4WqkQ4IVuRdvjv2Rb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L278)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Or you could `return nil` here and not utilize the named-break.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-31 01:09 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo small comments below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LQ6eiFrEx3dsrD2rw_y:b-oer34b)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/context.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KYDgBDYh7ZAt3_Ct:-LQ6cjE73cx6DrQ1FC-c:b-k80fji) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L140)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Maybe we should keep the flag but set the default to the store directory? 
</blockquote></details>

The default store directory is `cockroach-data`. Feels a bit strange to use that, though I don't have good words for why. Another option is to use `.`. 
___
*[pkg/cli/systembench/io_bench.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1PSF0EQ7Fn-WNRGgm:-LQ6dXoW1A0VvZBWlb7Z:blh789d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L156)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

That's why I commented above, it doesn't open the file in append mode by default and we need that for our tests if we have concurrent writers.
</blockquote></details>

Heh, I missed that comment. It's more lines, but my recommendation would be to close and reopen the file. You can get the name of the temp file using `File.Name()`. The reason for using `TempFile()` is that it avoids overwriting a file that already exists. 
___
*[pkg/cli/systembench/io_bench.go, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Pg1xBE37D5EbTeY2:-LQ6dkWX8yDsQhOrDUBH:b95enws) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L158)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Ok I see, should we get rid of the concurrency flag for this altogether?  Or will we want more general benchmarks in the future? If so I can use the builtin TempFile function.
</blockquote></details>

The concurrency flag isn't interesting for `seqwrite`, but for the WAL write simulation it is interesting, you just won't be concurrently writing to the file. See `synctest`. 
___
*[pkg/cli/systembench/io_bench.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ6e4Gr4UWetEHC3xfv:-LQ6e4Gr4UWetEHC3xfw:b-mnhgnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d494c1e9286d295d5250c96be9d9e3f79c1a40/pkg/cli/systembench/io_bench.go#L54)):*
> ```Go
> 
> // IOOptions holds parameters for the test.
> type IOOptions struct {
> ```

`s/IOOptions/DiskOptions/g` and `s/IOBenchmarkType/DiskBenchmarkType/g`. I'm suggesting this because I bet you're going to run into difficulty cramming network and cpu benchmark options into a single struct. Rather I think you'll want to have a `NetOptions` struct and a `CPUOptions` struct (or perhaps even additional structs for each benchmark type). 

Similarly, I think you should `s/io_bench.go/disk_bench.go`.


<!-- Sent from Reviewable.io -->

2018-10-31 01:11 UTC, petermattis reviewed
Before merging you should sanity check that the output from this matches performance seen by `sysbench`.

Also, rather than continually appending to files, I'm wondering if you should rotate through the file so that you don't just fill up disk. Something along the lines of rotating the file every gigabyte.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LQ6epPbD-4XF838G5ZH:bxjlc3v)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-31 16:58 UTC, nvb requested changes
Yeah, before merging we should look at the result of a few runs. Perhaps you could run on you laptop, a gce machine with and without an SSD, and an aws machine with and without an SSD. If we can interpret the results and make sense of them then we'll have a baseline for this tool going forward.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LQA2abn33HV2H3F9mL_:b-s5ginz)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQA2AzS17EZZE8CbrII:b-7hc10t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Thanks! Is there a reason not to fix the other ones without a newline in the file?
</blockquote></details>

I'm not sure, how do these show up in the cli help text? (don't let this slow down the PR though!)
___
*[pkg/cli/systembench/io_bench.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ6e4Gr4UWetEHC3xfv:-LQA2P8E1_UBHoKrYsqX:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d494c1e9286d295d5250c96be9d9e3f79c1a40/pkg/cli/systembench/io_bench.go#L54)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/IOOptions/DiskOptions/g` and `s/IOBenchmarkType/DiskBenchmarkType/g`. I'm suggesting this because I bet you're going to run into difficulty cramming network and cpu benchmark options into a single struct. Rather I think you'll want to have a `NetOptions` struct and a `CPUOptions` struct (or perhaps even additional structs for each benchmark type). 

Similarly, I think you should `s/io_bench.go/disk_bench.go`.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2018-10-31 19:17 UTC, m-schneider reviewed
@petermattis I added logic to recreate the temp file every 1GB.

@nvanbenschoten I just ran a couple of tests on GCE which show the difference between mounting with and without nobarrier, I've started a spreadsheet here: https://docs.google.com/spreadsheets/d/1O4boSEG-f4ZstcXQLRG9IbxvDNtykz3EU0ZCt1QfTgw/edit?usp=sharing and I'll keep adding different configurations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-:-LQAVQWAACNVKzawL0zC:b-jsc5sd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/context.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1KYDgBDYh7ZAt3_Ct:-LQA7QGL9tabrxO9FEGn:b-9ubesg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/context.go#L140)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The default store directory is `cockroach-data`. Feels a bit strange to use that, though I don't have good words for why. Another option is to use `.`. 
</blockquote></details>

I understand what you mean which is why I didn't use that to begin with, it doesn't seem like a place for temp files. `.` works.
___
*[pkg/cli/cliflags/flags.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ0FfiaACHT4RjM5Qhj:-LQAA5xtDLZ9k_gpxMoY:bccgiyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3014bf4f115404865e10408d8feab205bd6dedda/pkg/cli/cliflags/flags.go#L817)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure, how do these show up in the cli help text? (don't let this slow down the PR though!)
</blockquote></details>

It actually looks the same, I tested on a different command.
___
*[pkg/cli/systembench/io_bench.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1PSF0EQ7Fn-WNRGgm:-LQACusv3HdewInObacT:b-3282rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L156)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, I missed that comment. It's more lines, but my recommendation would be to close and reopen the file. You can get the name of the temp file using `File.Name()`. The reason for using `TempFile()` is that it avoids overwriting a file that already exists. 
</blockquote></details>

I added a function.
___
*[pkg/cli/systembench/io_bench.go, line 158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ1Pg1xBE37D5EbTeY2:-LQAAM2M5O3l0MP7N13p:bz4hsko) ([raw file](https://github.com/cockroachdb/cockroach/blob/d10f6e7392d95ca7ea91168e11fe8edfa5431daa/pkg/cli/systembench/io_bench.go#L158)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The concurrency flag isn't interesting for `seqwrite`, but for the WAL write simulation it is interesting, you just won't be concurrently writing to the file. See `synctest`. 
</blockquote></details>

I'll get rid of it for this command.
___
*[pkg/cli/systembench/io_bench.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQ6e4Gr4UWetEHC3xfv:-LQA7P6k93muidT0lBfz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d494c1e9286d295d5250c96be9d9e3f79c1a40/pkg/cli/systembench/io_bench.go#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-01 01:08 UTC, petermattis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/systembench/disk_bench.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBmgi45SIKeOoakmQo:-LQBmgi45SIKeOoakmQp:b-bxzqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L60)):*
> ```Go
> 	SyncInterval int64
> 
> 	IOBenchMark DiskBenchmarkType
> ```

`s/IO/Disk/g`/
`s/BenchMark/Benchmark/g`
___
*[pkg/cli/systembench/disk_bench.go, line 114 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBnYsDEaAM_s7pSQ8W:-LQBnYsDEaAM_s7pSQ8X:bow8cay) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L114)):*
> ```Go
> 
> 	writeSize := int64(len(w.data))
> 	defer os.Remove(tempfile.Name()) // clean up
> ```

You could write this as:

```
defer func() {
  os.Remove(tempFile.Name())
}()
```

And then it would remove the current active temp file and not the one active at the time the defer is created. This would allow you to remove the `defer` in the loop below, though see my comment below for another suggestion.
___
*[pkg/cli/systembench/disk_bench.go, line 142 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBnufqDQ0s31rvB370:-LQBnufqDQ0s31rvB371:b-ymouim) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L142)):*
> ```Go
> 				return err
> 			}
> 			tempfile, err = newTempFile(w.tempFileDir)
> ```

You could reuse the same temp file name here, rather than generating a new one. That would remove the need to create another `defer`. 


<!-- Sent from Reviewable.io -->

2018-11-13 18:12 UTC, m-schneider commented
bors r+





<!-- Sent from Reviewable.io -->

2018-11-13 18:17 UTC, m-schneider commented
bors r-





<!-- Sent from Reviewable.io -->

2018-11-13 18:42 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/systembench/disk_bench.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBmgi45SIKeOoakmQo:-LRDNIqO2u2KYAUXdkOV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/IO/Disk/g`/
`s/BenchMark/Benchmark/g`
</blockquote></details>

Done.
___
*[pkg/cli/systembench/disk_bench.go, line 114 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBnYsDEaAM_s7pSQ8W:-LRDNKCu7PvtvZOaOyJv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L114)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could write this as:

```
defer func() {
  os.Remove(tempFile.Name())
}()
```

And then it would remove the current active temp file and not the one active at the time the defer is created. This would allow you to remove the `defer` in the loop below, though see my comment below for another suggestion.
</blockquote></details>

Done.
___
*[pkg/cli/systembench/disk_bench.go, line 142 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBnufqDQ0s31rvB370:-LRDNKiQ382nGCxcPRpt:b-7femrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L142)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You could reuse the same temp file name here, rather than generating a new one. That would remove the need to create another `defer`. 
</blockquote></details>

Switched it to truncate the temp file.


<!-- Sent from Reviewable.io -->

2018-11-13 19:18 UTC, petermattis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/systembench/disk_bench.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBmgi45SIKeOoakmQo:-LRDVRlA3LPz81-HFiWp:b9pc1gi) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L60)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Two problems remain: `Benchmark` is one word, not two words. You've used inconsistent capitalization on the same line: `BenchMark` vs `Benchmark`. The latter (`Benchmark`) is the correct capitalization.


<!-- Sent from Reviewable.io -->

2018-11-13 19:28 UTC, nvb requested changes
> Reviewed 3 of 5 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/cli_test.go, line 1814 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LRDXIcL8NVs9xjatIy7:-LRDXIcMECCwgvn_PFwh:bou2otk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1492356a408cae1cdd6beede8ad781a5ea6e128e/pkg/cli/cli_test.go#L1814)):*
> ```Go
>   dump        dump sql tables
> 
>   systembench Run systembench
> ```

How are these sorted? I'd expect `systembench` to be right below `workload`.
___
*[pkg/cli/systembench/disk_bench.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBmgi45SIKeOoakmQo:-LRDX_-55RUdUT-AfXUl:b-lbqr4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Two problems remain: `Benchmark` is one word, not two words. You've used inconsistent capitalization on the same line: `BenchMark` vs `Benchmark`. The latter (`Benchmark`) is the correct capitalization.
</blockquote></details>

I'd actually just call this field `Type`.
___
*[pkg/cli/systembench/disk_bench.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LRDXlIY0eIgi_3mDDiS:-LRDXlIY0eIgi_3mDDiT:b-xodfg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1492356a408cae1cdd6beede8ad781a5ea6e128e/pkg/cli/systembench/disk_bench.go#L139)):*
> ```
> 		// 1 << 30 is a gigabyte
> 		if writtenInFile >= 1<<30 {
> ```

`if writtenInFile >= 1<<30 /* 30 GB */ {`

or better yet, pull this into a constant.


<!-- Sent from Reviewable.io -->

2018-11-13 20:22 UTC, m-schneider reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31897)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cli/cli_test.go, line 1814 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LRDXIcL8NVs9xjatIy7:-LRDjCyC0tpBr15tJ3yv:b1z6ev3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1492356a408cae1cdd6beede8ad781a5ea6e128e/pkg/cli/cli_test.go#L1814)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How are these sorted? I'd expect `systembench` to be right below `workload`.
</blockquote></details>

They didn't seem to be sorted in any specific way, but I moved systembench under workload.
___
*[pkg/cli/systembench/disk_bench.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LQBmgi45SIKeOoakmQo:-LRDgVfBEstQ7HOxQwFO:b-i6k1l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/57a87a4b0499096b381f5ac397d60b43546d5f60/pkg/cli/systembench/disk_bench.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd actually just call this field `Type`.
</blockquote></details>

I like Type. 
___
*[pkg/cli/systembench/disk_bench.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/31897#-LRDXlIY0eIgi_3mDDiS:-LRDgmDiCRY0vp5umbLJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1492356a408cae1cdd6beede8ad781a5ea6e128e/pkg/cli/systembench/disk_bench.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> 		// 1 << 30 is a gigabyte
> 		if writtenInFile >= 1<<30 {
> ```

`if writtenInFile >= 1<<30 /* 30 GB */ {`

or better yet, pull this into a constant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-14 15:53 UTC, m-schneider commented
bors r+





<!-- Sent from Reviewable.io -->

2018-11-14 17:25 UTC, merged