exec: generate projection and selection ops
cockroachdb/cockroach pull request #31892
Opened 2018-10-25 18:59 UTC by solongordon

An initial collection of projection and selection operations is now
auto-generated via execgen.

Int64 benchmarks:
```
BenchmarkProjPlusInt64Int64ConstOp-4   	 3000000	       554 ns/op	14767.10 MB/s
BenchmarkProjPlusInt64Int64Op-4        	 3000000	       581 ns/op	28188.13 MB/s
BenchmarkSelLTInt64Int64ConstOp-4      	 2000000	       666 ns/op	12290.12 MB/s
BenchmarkSelLTInt64Int64Op-4           	 2000000	       857 ns/op	19115.31 MB/s
```

Release note: None

2018-10-25 18:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31892)
<!-- Reviewable:end -->

2018-10-25 21:50 UTC, jordanlewis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/operators.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPhAquYEmTIS4XoQCrm:-LPhAquYEmTIS4XoQCrn:b248twy) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/operators.go#L21)):*
> ```Go
> )
> 
> type op int
> ```

nit: I would name this file something besides operators, which namespace-collides with exec.Operator. Maybe `overloads.go` or `bin_operators.go`?
___
*[pkg/sql/exec/execgen/cmd/execgen/operators.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPhBGpq1s-M0W5nX7uP:-LPhBGpq1s-M0W5nX7uQ:bec8bl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/operators.go#L25)):*
> ```Go
> const (
> 	invalidOp op = iota
> 	plusOp
> ```

We should consider using some of the pre-existing operator types for this instead of making another enum that will need to be converted back and forth.

These currently live in `sql/sem/tree/expr.go`. I'm not sure what the downside of using those directly is, but undoubtedly there are some.

There are also `opt` equivalents that live in `sql/opt/operator.og.go`, with conversion maps in `sql/opt/operator.go`.
___
*[pkg/sql/exec/execgen/cmd/execgen/operators.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh9TDy-zIzLxwUOf0D:-LPh9TDzA2l-k5KjDPgZ:b34ifvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/operators.go#L76)):*
> ```Go
> }
> 
> // TODO: Autogenerate this collection.
> ```

+1, seems like you should get this out of the way sooner rather than later. We'll want to be adding new types very soon.
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh91zz6KmhEmuezYzA:-LPh91zz6KmhEmuezYzB:bflnbvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L52)):*
> ```Go
> 		}
> 	} else {
> 		for i := uint16(0); i < n; i++ {
> ```

Bounds check elimination would improve performance of this further. It's possible by slicing projCol and col to :n, and then ranging over them instead of using an explicit for loop.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh175g-gZRJAP5lTBO:-LPh175g-gZRJAP5lTBP:b-bq326f) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L30)):*
> ```Go
> {{range .}}
> {{range .}}
> {{if eq .RetTyp.String "Bool"}}
> ```

Took me a while to understand this - it's selecting out the predicates. It might be clearer to pass in a list of just the predicates to the templater. Or, at least add a comment. (Also apologies if this was my code - I don't understand it anymore :)
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh4g8z5bP91L09gXas:-LPh4g8z5bP91L09gXat:bc4w80d) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L96)):*
> ```Go
> 		var idx uint16
> 		if sel := batch.Selection(); sel != nil {
> 			for s := uint16(0); s < n; s++ {
> ```

don't need the uint16 here. I think you could as well do `sel=sel[:n]; for _, i := range sel`, right? I think you might have better performance with that because of fewer bounds checks.
___
*[pkg/sql/exec/types/types.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh2dBs9_w7sU-EMHLq:-LPh2dBtBfupfQtgv03f:b-tc2ngc) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/types/types.go#L107)):*
> ```Go
> 
> // GoTypeName returns the stringified Go type for an exec type.
> func (t T) GoTypeName() string {
> ```

I wonder, is this one of those things you wanted to avoid? You mentioned it was annoying to have to go around adding new items to switch statements all over the place in current code.

Would this be better as a method on types.T? 


<!-- Sent from Reviewable.io -->

2018-10-28 20:00 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPwFYZO1YCAxuXL22Vd:-LPwFYZO1YCAxuXL22Ve:b-l89oej) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L59)):*
> ```Go
> }
> 
> func (p {{template "opConstName" .}}) Init() {}
> ```

All of these Init methods will need to Init their parents now. That's changed since you rebased, sorry about that.
___
*[pkg/sql/exec/types/types.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh2dBs9_w7sU-EMHLq:-LPwFf329KGGSdA3o9oQ:b-6qpvhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/types/types.go#L107)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I wonder, is this one of those things you wanted to avoid? You mentioned it was annoying to have to go around adding new items to switch statements all over the place in current code.

Would this be better as a method on types.T? 
</blockquote></details>

Wait, it already is a method. I got confused - types.T is a single type, not n different types. Nevermind.


<!-- Sent from Reviewable.io -->

2018-10-29 16:02 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-Yrh5AKnptUe7NQcD:-LQ-Yrh5AKnptUe7NQcE:b-7o94vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L48)):*
> ```Go
> 	if batch.Selection() != nil {
> 		for s := uint16(0); s < n; s++ {
> 			i := batch.Selection()[s]
> ```

Might be good to extract this since `batch.Selection` does an if statement on every call
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-Z-7ZDdwauHaUfJNF:-LQ-Z-7ZDdwauHaUfJNG:buo9nmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L79)):*
> ```Go
> 	if batch.Selection() != nil {
> 		for s := uint16(0); s < n; s++ {
> 			i := batch.Selection()[s]
> ```

Same here


<!-- Sent from Reviewable.io -->

2018-10-29 16:50 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-Yrh5AKnptUe7NQcD:-LQ-ZErQDIr3c7loMhrd:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be good to extract this since `batch.Selection` does an if statement on every call
</blockquote></details>

Yes, done.
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh91zz6KmhEmuezYzA:-LQ-Z1_uEFWZIJeQsRWl:bxfsh2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L52)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Bounds check elimination would improve performance of this further. It's possible by slicing projCol and col to :n, and then ranging over them instead of using an explicit for loop.
</blockquote></details>

Done... ish. Is there really a way to range over both of them? Or is the best we can do to slice and range over one?
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPwFYZO1YCAxuXL22Vd:-LQ-ZA6l3jn1GwZWTjL5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

All of these Init methods will need to Init their parents now. That's changed since you rebased, sorry about that.
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-Z-7ZDdwauHaUfJNF:-LQ-ZGZF9GRiIDSX3pQw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh175g-gZRJAP5lTBO:-LQ-ZKgg8E3MmBOAQFb2:b-ild7ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L30)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Took me a while to understand this - it's selecting out the predicates. It might be clearer to pass in a list of just the predicates to the templater. Or, at least add a comment. (Also apologies if this was my code - I don't understand it anymore :)
</blockquote></details>

Haha, it was yours. Should be clear now.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh4g8z5bP91L09gXas:-LQ-PNVr1ifwYoov7KZb:bjkeytr) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L96)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

don't need the uint16 here. I think you could as well do `sel=sel[:n]; for _, i := range sel`, right? I think you might have better performance with that because of fewer bounds checks.
</blockquote></details>

Yup, this shows a ~20% improvement in my benchmark. Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/operators.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPhBGpq1s-M0W5nX7uP:-LQ-gjVUE_mSxpPlNWxh:b-dcxjz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/operators.go#L25)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We should consider using some of the pre-existing operator types for this instead of making another enum that will need to be converted back and forth.

These currently live in `sql/sem/tree/expr.go`. I'm not sure what the downside of using those directly is, but undoubtedly there are some.

There are also `opt` equivalents that live in `sql/opt/operator.og.go`, with conversion maps in `sql/opt/operator.go`.
</blockquote></details>

Done, using the expr types for now.
___
*[pkg/sql/exec/execgen/cmd/execgen/operators.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh9TDy-zIzLxwUOf0D:-LQ-gnAq29puhSj-EOKW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/operators.go#L76)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

+1, seems like you should get this out of the way sooner rather than later. We'll want to be adding new types very soon.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-29 17:24 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-qc1e8ogDzx-Hqcgo:-LQ-qc1e8ogDzx-Hqcgp:bmjf496) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e7abc0c620a33ac778874afde5e0fc4592e26f/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L44)):*
> ```Go
> 	col := batch.ColVec(p.colIdx).{{.LTyp}}()[:ColBatchSize]
> 	n := batch.Length()
> 	if sel := batch.Selection(); sel != nil {
> ```

Oops, seems like I missed a slice here. Fixing.
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LQ-qeSr1JGttHllLUmI:-LQ-qeSr1JGttHllLUmJ:bmjf496) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e7abc0c620a33ac778874afde5e0fc4592e26f/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L76)):*
> ```Go
> 	col2 := batch.ColVec(p.col2Idx).{{.RTyp}}()[:ColBatchSize]
> 	n := batch.Length()
> 	if sel := batch.Selection(); sel != nil {
> ```

Oops, seems like I missed a slice here. Fixing.


<!-- Sent from Reviewable.io -->

2018-10-29 18:40 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 3 of 7 files at r1, 1 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-:-LQ0746PAwiEAMJXKXZV:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31892#-LPh91zz6KmhEmuezYzA:-LQ05qeJ-t3eXQjYDWYu:br1m5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/399f769f69635e4ed312726283693b0d1e2b5897/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L52)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Done... ish. Is there really a way to range over both of them? Or is the best we can do to slice and range over one?
</blockquote></details>

There's a way you can get BCE on both of them, but it probably requires some experimentation. But trying to perfect this right now is probably not important. This seems good to me.


<!-- Sent from Reviewable.io -->

2018-10-29 18:50 UTC, solongordon commented
bors r+

2018-10-29 19:10 UTC, merged