libroach: don't re-compare every key with end key
cockroachdb/cockroach pull request #31909
Opened 2018-10-26 04:02 UTC by jordanlewis

Previously, during scan, every key was always compared with the end key
to see if we could finish. However, RocksDB is already configured to do
this exact thing every time we have an end key, so we're doubling the
work that needs to get done there for no reason.

Seems to have a decent effect.

    name                                                  old time/op    new time/op    delta
    MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8    3.54ms ± 1%    3.43ms ± 1%  -3.14%  (p=0.000 n=10+10)

    name                                                  old speed      new speed      delta
    MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8  22.6MB/s ± 1%  23.3MB/s ± 1%  +3.25%  (p=0.000 n=10+10)

    name                                                  old alloc/op   new alloc/op   delta
    MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8    1.04MB ± 0%    1.04MB ± 0%    ~     (p=1.000 n=10+10)

    name                                                  old allocs/op  new allocs/op  delta
    MVCCScan_RocksDB/rows=10000/versions=1/valueSize=8-8      3.00 ± 0%      3.00 ± 0%    ~     (all equal)

Release note: None

2018-10-26 04:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31909)
<!-- Reviewable:end -->

2018-10-26 13:21 UTC, petermattis requested changes
> Previously, during scan, every key was always compared with the end key
to see if we could finish. However, RocksDB is already configured to do
this exact thing every time we have an end key, so we're doubling the
work that needs to get done there for no reason.

Where are we configuring RocksDB to use the `MVCCScan` end key? I don't see a call to `SetUpperBound` near the `MVCCScan` code paths. Perhaps I'm just missing it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31909#-:-LPkW_LGEved8gyPDSs6:bcarzc2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[c-deps/libroach/mvcc.h, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31909#-LPkWS0iB5ZA70Lk6jbv:-LPkWS0iB5ZA70Lk6jbw:b-484rux) ([raw file](https://github.com/cockroachdb/cockroach/blob/59093075573fdb0421e0350f6c9b9370a716ff78/c-deps/libroach/mvcc.h#L130)):*
> ```objc
>         return results_;
>       }
>       for (; cur_key_.compare(end_key_) >= 0;) {
> ```

There is also this comparison against `end_key_`. And there is a comparison in `nextKey()`. 


<!-- Sent from Reviewable.io -->

2018-10-26 13:29 UTC, petermattis commented
> My understanding was that it's set in mvcc.go:mvccScanInternal, when we set UpperBound to endKey in the passed-in IterOptions.

I missed that. Thanks for the pointer. What happens if `mvccScanInternal` is called with non-nil iterator?

2018-10-26 13:31 UTC, jordanlewis commented
We never do that in the normal scan path, so I didn't think about it. Looks like it's used by `MVCCIterateUsingIter`, which seems to be always configured with a single end key that doesn't change between calls.

2018-10-26 13:35 UTC, petermattis commented
It would make me feel better about this change if `libroach/mvcc.cc:MVCCScan` called `SetUpperBound` on the iterator. I believe the call should be incredibly cheap.

2018-10-26 14:53 UTC, jordanlewis commented
What am I doing wrong?

I tried:

```
diff --git a/c-deps/libroach/mvcc.cc b/c-deps/libroach/mvcc.cc
index 3be15504f3..3bb0649d70 100644
--- a/c-deps/libroach/mvcc.cc
+++ b/c-deps/libroach/mvcc.cc
@@ -295,9 +295,11 @@ DBScanResults MVCCScan(DBIterator* iter, DBSlice start, DBSlice end, DBTimestamp
                        bool tombstones) {
   ScopedStats scoped_iter(iter);
   if (reverse) {
+    iter->SetUpperBound(ToDBKey(ToSlice(start)));
     mvccReverseScanner scanner(iter, end, start, timestamp, max_keys, txn, consistent, tombstones);
     return scanner.scan();
   } else {
+    iter->SetUpperBound(ToDBKey(ToSlice(end)));
     mvccForwardScanner scanner(iter, start, end, timestamp, max_keys, txn, consistent, tombstones);
     return scanner.scan();
   }
```

but it breaks all the tests, which can't be right since we should be doing the same thing at a higher level. Is the problem that I need to add the input's MVCC timestamp to the start/end key? Doesn't seem like it, because the Go equivalent just sets the upper bound to a `roachpb.Key` which doesn't have MVCC timestamp data yet.

2018-10-26 14:59 UTC, petermattis commented
> What am I doing wrong?

Try narrowing down to whether it is the forward or reverse scan change that is causing the problem. Or perhaps both are.

2018-10-31 20:31 UTC, benesch commented
```
diff --git a/c-deps/libroach/mvcc.cc b/c-deps/libroach/mvcc.cc
index 3be15504f3..3bb0649d70 100644
--- a/c-deps/libroach/mvcc.cc
+++ b/c-deps/libroach/mvcc.cc
@@ -295,9 +295,11 @@ DBScanResults MVCCScan(DBIterator* iter, DBSlice start, DBSlice end, DBTimestamp
                        bool tombstones) {
   ScopedStats scoped_iter(iter);
   if (reverse) {
+    iter->SetUpperBound(ToDBKey(ToSlice(start)));
     mvccReverseScanner scanner(iter, end, start, timestamp, max_keys, txn, consistent, tombstones);
     return scanner.scan();
   } else {
+    iter->SetUpperBound(ToDBKey(ToSlice(end)));
     mvccForwardScanner scanner(iter, start, end, timestamp, max_keys, txn, consistent, tombstones);
     return scanner.scan();
   }
```
The upper bound is independent of iteration direction. What you really need for the reverse case is to set the lower bound to start.

2018-10-31 20:36 UTC, jordanlewis commented
It's broken even with just a forward scan. I haven't gotten around to figuring this out yet, but I will at some point.

2018-10-31 22:20 UTC, benesch reviewed
I'm trying to get some cleanup in to make this easier.

> It would make me feel better about this change if libroach/mvcc.cc:MVCCScan called SetUpperBound on the iterator. I believe the call should be incredibly cheap.

I thought about this and the idea of mutating internal iterator state when you call MVCCIterateUsingIter makes me very anxious. That's a recipe for a subtle bug.  I think the answer here is that MVCCIterateUsingIter is the wrong API. (After all, it only has one caller.) What we want instead, I think, are two functions, MVCCScan and MVCCIterate, both of which take a ScanOptions struct that lets you configure them any which way. But they always manage the iterators for you, and that way we can rely on the iterators always having a tight lower and upper bound, and remove both the lower and upper bound checks from the C++ mvccScanner.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31909#-:-LQBB7FQ5X6dNa-eVEFz:b-nag8nb)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-27 01:32 UTC, jordanlewis commented
Woohoo, thanks!

2018-11-27 01:32 UTC, closed without merging