sql: check uncommitted tables for created tables in same txn
cockroachdb/cockroach pull request #31986
Opened 2018-10-29 21:34 UTC by eriktrinh

Add a new field to MutableTableDescriptor which describes the table
schema as seen by the cluster outside of the current transaction. This
change also removes createdTables set in the table collection, and
checks if a table has been created in the same transaction if the
outside view of the table is nil.

Release note: None

2018-10-29 21:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/31986)
<!-- Reviewable:end -->

2018-10-30 01:45 UTC, vivekmenezes requested changes
Happy to see this change! Great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-:-LQ1dSIE251Y2wBv1Oow:b-tcuwlj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/table.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1cgol9xnvdYZQ8XdM:-LQ1_onz6x-RxA1PQgo3:b-sw4quk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ccbbcac7a32483d27b159b9d4a1000470cee1a5/pkg/sql/table.go#L157)):*
> ```Go
> 	// table is marked dropped.
> 	uncommittedTables   map[sqlbase.ID]*sqlbase.MutableTableDescriptor
> 	uncommittedTableIDs []sqlbase.ID
> ```

I see that you're adding two data structures here for performance reasons, but the table name based lookup which is the more common lookup is not really taking advantage of the map . Its actually running a map lookup as you traverse the list. I'd keep this as a single list for now until we've got a specific performance improvement you want to make. In which case you can make a separate change along with a benchmark.
___
*[pkg/sql/truncate.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1aSeiEjVxfIde5E_c:-LQ1aSeiEjVxfIde5E_d:bwh6pzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6691aad3d491ffb558f78cd84054d4b767133d7/pkg/sql/truncate.go#L277)):*
> ```Go
> 	}
> 
> 	p.Tables().addCreatedTable(newID)
> ```

you need to delete the definition of this function too.
___
*[pkg/sql/sqlbase/structured.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1ajET5bFP2cPruB4z:-LQ1ajET5bFP2cPruB5-:b-7wxzda) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ccbbcac7a32483d27b159b9d4a1000470cee1a5/pkg/sql/sqlbase/structured.go#L111)):*
> ```Go
> 	TableDescriptor
> 
> 	ClusterVer *TableDescriptor
> ```

It would be okay to store the descriptor and have ID == 0 represent the zero value


<!-- Sent from Reviewable.io -->

2018-10-30 15:09 UTC, eriktrinh reviewed
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-:-LQ4WKjN8XiHQpSUaCs_:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/table.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1cgol9xnvdYZQ8XdM:-LQ4Sh9c4IAycjqGE_qN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ccbbcac7a32483d27b159b9d4a1000470cee1a5/pkg/sql/table.go#L157)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I see that you're adding two data structures here for performance reasons, but the table name based lookup which is the more common lookup is not really taking advantage of the map . Its actually running a map lookup as you traverse the list. I'd keep this as a single list for now until we've got a specific performance improvement you want to make. In which case you can make a separate change along with a benchmark.
</blockquote></details>

Done.
___
*[pkg/sql/truncate.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1aSeiEjVxfIde5E_c:-LQ4SjVnDbZX4y3L6GJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6691aad3d491ffb558f78cd84054d4b767133d7/pkg/sql/truncate.go#L277)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you need to delete the definition of this function too.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ1ajET5bFP2cPruB4z:-LQ4SoD65svKoLce8pHe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ccbbcac7a32483d27b159b9d4a1000470cee1a5/pkg/sql/sqlbase/structured.go#L111)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

It would be okay to store the descriptor and have ID == 0 represent the zero value
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-30 15:39 UTC, vivekmenezes requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31986)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 812 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4ZPc_4MtpFCmDdpsh:-LQ4ZPcaCG2uxMvZ_5ce:byfe0qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/create_table.go#L812)):*
> ```Go
> // given TableDescriptor and cluster version of the table.
> func NewMutableTableDescriptor(
> 	tbl sqlbase.TableDescriptor, clusterVer sqlbase.TableDescriptor,
> ```

s/clusterVer/clusterVersion
___
*[pkg/sql/resolver.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4YdhcEpz0lmJHz_Nk:-LQ4Ydhd10rqY5Lm4pMZ:b-81tle9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/resolver.go#L160)):*
> ```Go
> 			return mutDesc, nil
> 		}
> 		tbl := descI.(*TableDescriptor)
> ```

tbl := *descI.(*TableDescriptor)
return NewMutableTableDescriptor(tbl, tbl), nil
___
*[pkg/sql/table.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4cCJ5DM6AjWalDp34:-LQ4cCJ5DM6AjWalDp35:b8wzyre) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/table.go#L471)):*
> ```Go
> func (tc *TableCollection) isCreatedTable(id sqlbase.ID) bool {
> 	mut := tc.getUncommittedTableByID(id)
> 	return mut != nil && mut.ClusterVer.ID == sqlbase.InvalidID
> ```

You can delete this function. See my other comment on this.
___
*[pkg/sql/table.go, line 795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4ZlIU6XrCcPhPpnTc:-LQ4ZlIU6XrCcPhPpnTd:bjdq6xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/table.go#L795)):*
> ```Go
> 
> 	// Table is created in current transaction.
> 	if tableDesc.ClusterVer.ID == sqlbase.InvalidID {
> ```

I think you could create a method on MutableTableDescriptor called isNewTable() that runs this check and use it here and the other place in this file where isCreatedTable() is called.  You can change the backfill.go code to 

`
table := tc.getUncommittedTableByID(k)
if !table.isNewTable() {
return errors.Errorf(
				"table %s not created in the same transaction as id = %s", tableDesc.Name, table.Name)
}
` 
___
*[pkg/sql/sqlbase/structured.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4Z3nbBPqWc2xlJQnT:-LQ4Z3nbBPqWc2xlJQnU:blmt6sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/sqlbase/structured.go#L111)):*
> ```Go
> 	TableDescriptor
> 
> 	ClusterVer TableDescriptor
> ```

// ClusterVersion represents the version of the table descriptor read from the store.
ClusterVersion TableDescriptor


<!-- Sent from Reviewable.io -->

2018-10-30 17:33 UTC, eriktrinh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31986)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 812 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4ZPc_4MtpFCmDdpsh:-LQ4zjhLDZDZTwU4WSZT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/create_table.go#L812)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

s/clusterVer/clusterVersion
</blockquote></details>

Done.
___
*[pkg/sql/resolver.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4YdhcEpz0lmJHz_Nk:-LQ5-xCPCN3uBOvrVCv-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/resolver.go#L160)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

tbl := *descI.(*TableDescriptor)
return NewMutableTableDescriptor(tbl, tbl), nil
</blockquote></details>

Done.
___
*[pkg/sql/table.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4cCJ5DM6AjWalDp34:-LQ4xfa65syMm_RQkiRo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/table.go#L471)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

You can delete this function. See my other comment on this.
</blockquote></details>

Done.
___
*[pkg/sql/table.go, line 795 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4ZlIU6XrCcPhPpnTc:-LQ4zhdn7uItj9pkY4u6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/table.go#L795)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I think you could create a method on MutableTableDescriptor called isNewTable() that runs this check and use it here and the other place in this file where isCreatedTable() is called.  You can change the backfill.go code to 

`
table := tc.getUncommittedTableByID(k)
if !table.isNewTable() {
return errors.Errorf(
				"table %s not created in the same transaction as id = %s", tableDesc.Name, table.Name)
}
` 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-LQ4Z3nbBPqWc2xlJQnT:-LQ4zi_b8h8GSkEy5hIN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9e8175d28251ffd5048ddc874f64677aa14349/pkg/sql/sqlbase/structured.go#L111)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

// ClusterVersion represents the version of the table descriptor read from the store.
ClusterVersion TableDescriptor
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-30 23:08 UTC, vivekmenezes approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31986#-:-LQ6E6zaCU9elyZjhZhy:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-10-31 15:09 UTC, eriktrinh commented
bors r+

2018-10-31 15:37 UTC, merged