sql: add request for MutableTableDescriptor in descriptor API
cockroachdb/cockroach pull request #32152
Opened 2018-11-05 16:02 UTC by vivekmenezes

This change sets up users of the descriptor resolution API to
clearly request a MutableTableDescriptor using a flag. It allows
the implementation for reading a TableDescriptor to be split away
from the one reading a MutableTableDescriptor. MutableTableDescriptor
is now created where it's needed.

The avoidCache flag now only affects the implementation of reading
a TableDescriptor, and can be used where transactions need to read
a const TableDescriptor from the store.

Release note: None

2018-11-05 16:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32152)
<!-- Reviewable:end -->

2018-11-12 15:59 UTC, eriktrinh requested changes
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32152)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7YQEh56VPm0MNO07Q:-LR7YQEi1BECYQED2rZC:b-5a66yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/create_table.go#L812)):*
> ```Go
> // given TableDescriptor with the cluster version being the zero table. This
> // is for a table that is created in the transaction.
> func NewMutableCreateTableDescriptor(tbl sqlbase.TableDescriptor) *sqlbase.MutableTableDescriptor {
> ```

Maybe `NewMutableCreatedTableDescriptor`?
___
*[pkg/sql/data_source.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7Y_ev1oAm1lP8i5Nt:-LR7Y_ev1oAm1lP8i5Nu:btx330m) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/data_source.go#L205)):*
> ```Go
> 		avoidCached: p.avoidCachedDescriptors,
> 	},
> 		false, /*requireMutable*/
> ```

Could use the field name for the requireMutable ObjectLookupFlags initialization here.
___
*[pkg/sql/descriptor.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7ZTmQCHMuQTx2GCkJ:-LR7ZTmQCHMuQTx2GCkK:b-21jxiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/descriptor.go#L126)):*
> ```Go
> 	b.CPut(descKey, descDesc, nil)
> 
> 	mutDesc, isTable := descriptor.(*sqlbase.MutableTableDescriptor)
> ```

Nice cleanup
___
*[pkg/sql/physical_schema_accessors.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7ZcvU-4PYJ9OVxeEL:-LR7ZcvU-4PYJ9OVxeEM:b-1mwdo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/physical_schema_accessors.go#L206)):*
> ```Go
> 			return nil, db, err
> 		}
> 		return table, db, err
> ```

should be able to just `return a.tc.getMutableTableDescriptor(flags.ctx, name, flags)` here and the nil interface should return correctly. Same for below.
___
*[pkg/sql/planner.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7_WQVDg0qteEBo-3J:-LR7_WQVDg0qteEBo-3K:b-sl6mqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/planner.go#L121)):*
> ```Go
> 	// modified by the schema change. (reading a table in CREATE VIEW)
> 	// 2. Disable the use of the table cache in tests.
> 	//
> ```

extra empty line here, and does the previous comment about the txn isolation level not apply anymore?
___
*[pkg/sql/table.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7d6in-WE0JqbYaNeV:-LR7d6in-WE0JqbYaNeW:bk8ty84) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/table.go#L309)):*
> ```Go
> 			return nil, db, err
> 		}
> 		return obj.(*sqlbase.TableDescriptor), db, err
> ```

obj.TableDesc()


<!-- Sent from Reviewable.io -->

2018-11-14 15:45 UTC, vivekmenezes reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-:-LRHtaA159h_GnQIJgYy:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/create_table.go, line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7YQEh56VPm0MNO07Q:-LRHlekk54vlLExELN4E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/create_table.go#L812)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Maybe `NewMutableCreatedTableDescriptor`?
</blockquote></details>

Done.
___
*[pkg/sql/data_source.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7Y_ev1oAm1lP8i5Nt:-LRHlqGnB4N6MXJiX1zT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/data_source.go#L205)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

Could use the field name for the requireMutable ObjectLookupFlags initialization here.
</blockquote></details>

Done.
___
*[pkg/sql/physical_schema_accessors.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7ZcvU-4PYJ9OVxeEL:-LRHluvQB-ksb3Og4rjY:b481aqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/physical_schema_accessors.go#L206)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

should be able to just `return a.tc.getMutableTableDescriptor(flags.ctx, name, flags)` here and the nil interface should return correctly. Same for below.
</blockquote></details>

Unfortunately golang suffers from this problem https://golang.org/doc/faq#nil_error
___
*[pkg/sql/planner.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7_WQVDg0qteEBo-3J:-LRHmETGDuWHVBrgCauU:bqtuzq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/planner.go#L121)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

extra empty line here, and does the previous comment about the txn isolation level not apply anymore?
</blockquote></details>

No. We only support SERIALIZABLE isolation level now.
___
*[pkg/sql/table.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-LR7d6in-WE0JqbYaNeV:-LRHmloj830nx8RvM2U0:b39kbce) ([raw file](https://github.com/cockroachdb/cockroach/blob/886b887116e07f0bc2ef7409aaba5eadcb3f67eb/pkg/sql/table.go#L309)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

obj.TableDesc()
</blockquote></details>

well, that's implemented by the interface. This will crash if it's not of the right type which is what we want.


<!-- Sent from Reviewable.io -->

2018-11-14 16:11 UTC, eriktrinh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32152#-:-LRHzVTT9Qn7KI1GjOdJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-14 16:17 UTC, vivekmenezes commented
bors r+

2018-11-14 17:12 UTC, merged