opt: implement Provided orderings
cockroachdb/cockroach pull request #32221
Opened 2018-11-12 18:24 UTC by RaduBerinde

This change implements logic to determine specific Provided orderings
that can be used to configure distsql correctly. See #31882 and the
description in `ordering/doc.go`.

In a follow-up change we will modify the execbuilder to use
`ProvidedOrdering` and re-enable the group-by optimization where we
set all grouping columns as optionals in the required ordering.

Informs #31882.

Release note: None

2018-11-13 21:48 UTC, RaduBerinde commented
Updated - I rebased on top of #32283 and created a `physical.Required` struct - ignore all but the last commit.

2018-11-13 23:08 UTC, rytaft requested changes
Very impressive work! 

I think the overall explanations of required v. provided props are really helpful, but I was a bit confused at the per-operator level in a lot of cases. It seems like each operator is slightly different, and it's currently kind of hard to understand exactly how or why. I added comments in a few places where I was confused, but I think more per-operator comments would be helpful in general.

> Reviewed 30 of 49 files at r1, 72 of 72 files at r2, 8 of 8 files at r3, 1 of 1 files at r4, 50 of 50 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LREJeYh8HeSrOtXXSac:bovzra2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr_format.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDdJgj3Lr922iot2p6:-LRDdJgj3Lr922iot2p7:b-b8bqix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/memo/expr_format.go#L306)):*
> ```Go
> 	if !physical.Ordering.Any() {
> 		provided := e.ProvidedOrdering()
> 		// XXX do not merge
> ```

Is this a stale comment?
___
*[pkg/sql/opt/optbuilder/testdata/limit, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDp1MPA1WYU7UoKvni:-LRDp1MPA1WYU7UoKvnj:b-2yqm9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/optbuilder/testdata/limit#L64)):*
> ```
>  ├── columns: k:1(int!null)
>  ├── internal-ordering: +1
>  ├── ordering: +1 [provided: ]
> ```

Why is there no provided ordering? Shouldn't it be `+1`?
___
*[pkg/sql/opt/ordering/doc.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDqwJc1dWB68kNkVNp:-LRDqwJc1dWB68kNkVNq:b-sr9xmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/doc.go#L23)):*
> ```Go
> operator-specific APIs in some cases.
> 
> Required orderings
> ```

Nice explanation!
___
*[pkg/sql/opt/ordering/doc.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDqFZYEM2BqBqn6YNT:-LRDqFZYEM2BqBqn6YNU:b-7vm400) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/doc.go#L40)):*
> ```Go
> 
> In a single-node serial execution model, the Required ordering would be
> sufficient to configure execution. But in a distributed setting even if an
> ```

[nit] add a comma after distributed setting
___
*[pkg/sql/opt/ordering/lookup_join.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDs7pqBTpFbIlrhJGa:-LRDs7pqBTpFbIlrhJGb:b-13a3jv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/lookup_join.go#L66)):*
> ```Go
> 	}
> 
> 	// The lookup join implicitly constraints equality on the lookup columns.
> ```

[nit] constraints equality -> adds equality constraints
___
*[pkg/sql/opt/ordering/lookup_join_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDt8_PElGtn-XGh-ZX:-LRDt8_PElGtn-XGh-ZY:b-y9h8lk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/lookup_join_test.go#L60)):*
> ```Go
> 	}{
> 		{ // case 1
> 			keyCols:  opt.ColList{5, 6},
> ```

Can you add some comments here? It's not obvious to me why `provided` is correct for these test cases.
___
*[pkg/sql/opt/ordering/ordering.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDuYol7nV_mP_QnsGV:-LRDuYol7nV_mP_QnsGW:b-5b7xla) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering.go#L201)):*
> ```Go
> 	var result opt.Ordering
> 	// closure is the set of columns that are functionally determined by the
> 	// columns in provided[:provIdx].
> ```

what is `provIdx`?
___
*[pkg/sql/opt/ordering/ordering.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDxFEX27JtQrp25LJ3:-LRDxFEX27JtQrp25LJ4:b-d05la5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering.go#L303)):*
> ```Go
> 	}
> 
> 	// The provided ordering must intersect with the required ordering, after FDs
> ```

[nit] intersect with -> intersect
___
*[pkg/sql/opt/ordering/ordering_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDy2rh-NWK8iKpdHXg:-LRDy2rh-NWK8iKpdHXh:bpexkbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering_test.go#L50)):*
> ```Go
> 			prov: "-6,+4,-5,+7",
> 			fds:  constFD,
> 			exp:  "-6,+4,-5",
> ```

Why is it ok to keep `-6`? Does this mean a sort will be necessary?
___
*[pkg/sql/opt/ordering/ordering_test.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDzImy1Qemg8UBaDwD:-LRDzImy1Qemg8UBaDwE:b-617uir) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering_test.go#L151)):*
> ```Go
> }
> 
> type dummyRelExpr struct {
> ```

It seems like this is something that will be useful to other tests as well (I will use something like this in the props test infrastructure). Maybe it's worth adding it as an exported struct in testutils? Not essential, but might save some time later...
___
*[pkg/sql/opt/ordering/row_number.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRE1eGo02JjDIXtbHHg:-LRE1eGo02JjDIXtbHHh:baej8yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/row_number.go#L42)):*
> ```Go
> // ordering is +a,+b, then any of these orderings can be provided:
> //
> //   +ord
> ```

I'm confused by this comment... how can it provide `+ord` or `+a +ord` if the required input ordering is `+a +b`?
___
*[pkg/sql/opt/ordering/row_number.go, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREFwcW583bXNMvilyI:-LREFwcW583bXNMvilyJ:bf0ugt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/row_number.go#L84)):*
> ```Go
> 	provided = append(
> 		provided[:len(provided):len(provided)], // force reallocation
> 		opt.MakeOrderingColumn(r.ColID, false /* descending */),
> ```

Why don't you just truncate at prefix+1? Then you wouldn't need to add this extra column, right?
___
*[pkg/sql/opt/ordering/scan_test.go, line 113 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREHiR98cPe8U-5Ei41:-LREHiR98cPe8U-5Ei42:b-iq0gtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/scan_test.go#L113)):*
> ```Go
> 			},
> 		},
> 		{ // group 3: scan with limit (forces forward scan)>
> ```

extra `>`
___
*[pkg/sql/opt/ordering/select.go, line 67 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREI1Zd2rJR-OTq7dGt:-LREI1Zd2rJR-OTq7dGu:bruwmpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/select.go#L67)):*
> ```Go
> 	rel := s.Relational()
> 	// We don't need to remap columns, but we want to remove columns that are now
> 	// unnecessary (e.g. because the Select constraints them to be constant).
> ```

[nit] constraints -> constrains
___
*[pkg/sql/opt/props/physical/provided.go, line 53 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREIThZ6ac8WWPM3xFR:-LREIThZ6ac8WWPM3xFS:b-62vzwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/props/physical/provided.go#L53)):*
> ```Go
> }
> 
> // Equals returns true if the two sets of provided properties are identical.
> ```

Update comment


<!-- Sent from Reviewable.io -->

2018-11-14 00:42 UTC, andy-kimball reviewed
I added several comments as well. +1 to Rebecca's request for more comments on the per-op ordering implementations, which can be dense and tricky.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LREe_X_9pHd46KSHcib:b-jq82w5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/testdata/limit, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDp1MPA1WYU7UoKvni:-LREWktK5QGqqf2d2lde:bxlksmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/optbuilder/testdata/limit#L64)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is there no provided ordering? Shouldn't it be `+1`?
</blockquote></details>

The order of the query results doesn't matter - distsql doesn't need to provide any ordering. It does beg the question, though, how come there's a required ordering on the `Limit` operator? It seems like there should only be an internal ordering.
___
*[pkg/sql/opt/optbuilder/testdata/orderby, line 1076 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDB50h7RTRvODnTu8T:-LRDB50h7RTRvODnTu8U:bfk4ezi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/optbuilder/testdata/orderby#L1076)):*
> ```
> project
>  ├── columns: a:1(int!null)  [hidden: b:2(int) c:3(int)]
>  ├── ordering: +1,+2,+3 [provided: +1]
> ```

So `provided` here is `+1` b/c we simplify the provided ordering, but not the required ordering when using `build`?
___
*[pkg/sql/opt/ordering/doc.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRERJu_E9Ktk6XSqU-k:-LRERJuaEEkgZMz5QiL2:b-soj80l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/doc.go#L31)):*
> ```Go
> 
> An operator can provide a Required ordering if it can guarantee its results
> respect at an ordering in the OrderingChoice set, perhaps by requiring specific
> ```

Did you mean `respect at least one ordering`?
___
*[pkg/sql/opt/ordering/group_by.go, line 66 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREXVt277OUB0YPg57P:-LREXVt277OUB0YPg57Q:bksygpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/group_by.go#L66)):*
> ```Go
> 	groupBy := expr.(*memo.GroupByExpr)
> 	provided := groupBy.Input.ProvidedPhysical().Ordering
> 	// Retain the longest prefix of grouping columns in the input ordering.
> ```

NIT: blank lines before comments, unless they're at the start of a block. Without the space, it feels like reading a book that has no paragraphs.
___
*[pkg/sql/opt/ordering/ordering.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREcxIgDkht0ALD9UPh:-LREcxIgDkht0ALD9UPi:b-fi1pnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L191)):*
> ```Go
> 
> // remapProvided remaps columns in a provided ordering (according to the given
> // FDs) so that it only refers to columns in the given set. It also removes any
> ```

I'd clarify, "in the given outCols set."
___
*[pkg/sql/opt/ordering/ordering.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREcCPY33JsQOBtuimq:-LREcCPY33JsQOBtuimr:bp3gwvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L197)):*
> ```Go
> func remapProvided(provided opt.Ordering, fds *props.FuncDepSet, outCols opt.ColSet) opt.Ordering {
> 	if len(provided) == 0 {
> 		return nil
> ```

Isn't it better to return `provided` here, for possible case where an empty ordering is passed in? We might cause crashes in calling code if we map empty to nil.
___
*[pkg/sql/opt/ordering/ordering.go, line 201 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREcPSgEqDOcxkNfPd6:-LREcPSgEqDOcxkNfPd7:b-r8mek6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L201)):*
> ```Go
> 	// result is nil until we determine that we need to make a copy.
> 	var result opt.Ordering
> 	// closure is the set of columns that are functionally determined by the
> ```

NIT: blank line before comment.
___
*[pkg/sql/opt/ordering/ordering.go, line 221 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREdBmL5A4Rh6I7MLwI:-LREdBmL5A4Rh6I7MLwJ:b-j8ccj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L221)):*
> ```Go
> 			equivCols := fds.ComputeEquivClosure(util.MakeFastIntSet(int(col)))
> 			remappedCol, ok := equivCols.Intersection(outCols).Next(0)
> 			if !ok {
> ```

Can you add comment explaining why there must always be an equivalent column? Maybe add to documentation for method, since it seems like requirement that caller must guarantee?


<!-- Sent from Reviewable.io -->

2018-11-14 01:14 UTC, RaduBerinde reviewed
Thank you for the thorough reviews, I know it's a big change. I'll work on adding more comments. For now I addressed your notes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LREOnX21s857B5glBdI:bssopgq)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/expr_format.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDdJgj3Lr922iot2p6:-LREZQ2-AQ3RnFXIRXMb:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/memo/expr_format.go#L306)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this a stale comment?
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/optbuilder/testdata/limit, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDp1MPA1WYU7UoKvni:-LREOsD4-RE8GnItwtA-:b7wip8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/optbuilder/testdata/limit#L64)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The order of the query results doesn't matter - distsql doesn't need to provide any ordering. It does beg the question, though, how come there's a required ordering on the `Limit` operator? It seems like there should only be an internal ordering.
</blockquote></details>

It's one row so it's all the same. The required ordering would normally be empty too, but this is `build` so we don't simplify it.  I changed things to hide the ordering if the "hide misc props" flag is set (which is the case for optbuilder tests).
___
*[pkg/sql/opt/optbuilder/testdata/orderby, line 1076 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDB50h7RTRvODnTu8T:-LREhZCu8s87HJvjd0Gf:byr4flj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/optbuilder/testdata/orderby#L1076)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

So `provided` here is `+1` b/c we simplify the provided ordering, but not the required ordering when using `build`?
</blockquote></details>

Right.
___
*[pkg/sql/opt/ordering/doc.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDqFZYEM2BqBqn6YNT:-LREZYUtDgVH8gWXIZAI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/doc.go#L40)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] add a comma after distributed setting
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/doc.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRERJu_E9Ktk6XSqU-k:-LREhoug3nzTQuRih1xT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/doc.go#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you mean `respect at least one ordering`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/lookup_join.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDs7pqBTpFbIlrhJGa:-LREZtixERxYx8YpCu-e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/lookup_join.go#L66)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] constraints equality -> adds equality constraints
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/lookup_join_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDt8_PElGtn-XGh-ZX:-LREa2rkC7lz2tOc9-tI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/lookup_join_test.go#L60)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add some comments here? It's not obvious to me why `provided` is correct for these test cases.
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/ordering.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDuYol7nV_mP_QnsGV:-LREa9yU5NKU4yP8YmXE:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering.go#L201)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what is `provIdx`?
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/ordering/ordering.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDxFEX27JtQrp25LJ3:-LREaFDy6g3cBxei5XtY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering.go#L303)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] intersect with -> intersect
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/ordering.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREcxIgDkht0ALD9UPh:-LREi5lzA7cbU2n5MI29:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L191)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'd clarify, "in the given outCols set."
</blockquote></details>

Done.
___
*[pkg/sql/opt/ordering/ordering.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREcCPY33JsQOBtuimq:-LREi8blA0C12zXjcYOW:b-spbdgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L197)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Isn't it better to return `provided` here, for possible case where an empty ordering is passed in? We might cause crashes in calling code if we map empty to nil.
</blockquote></details>

`nil` is a valid empty slice and the function doesn't make any promises about the returned slice.
___
*[pkg/sql/opt/ordering/ordering.go, line 221 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LREdBmL5A4Rh6I7MLwI:-LREil5p42y3-yjoHmz3:b-8zb5z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d837a18b7b26425f84e26ce7e6718f96328223d3/pkg/sql/opt/ordering/ordering.go#L221)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you add comment explaining why there must always be an equivalent column? Maybe add to documentation for method, since it seems like requirement that caller must guarantee?
</blockquote></details>

Added to the method comment.
___
*[pkg/sql/opt/ordering/ordering_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDy2rh-NWK8iKpdHXg:-LREaSx92YuulRIKrz50:bhnar3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering_test.go#L50)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is it ok to keep `-6`? Does this mean a sort will be necessary?
</blockquote></details>

Hm, good catch, this was incorrect. It didn't blow up because `trimProvided` doesn't thoroughly check that the provided ordering "makes sense" (`checkProvided` does that).
___
*[pkg/sql/opt/ordering/ordering_test.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDzImy1Qemg8UBaDwD:-LREfO5c6EqQGI9xks_i:be59og7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/ordering_test.go#L151)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It seems like this is something that will be useful to other tests as well (I will use something like this in the props test infrastructure). Maybe it's wort [...]

2018-11-14 03:12 UTC, RaduBerinde commented
Added some more comments and made some minor cleanups.

2018-11-14 15:57 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> The comments are very helpful - thanks!

> Reviewed 18 of 30 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LRHvsbrAIsv12t9oQQ-:bkh365t)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/ordering/lookup_join_test.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRDt8_PElGtn-XGh-ZX:-LRHs9Ms-CHkquVB-ZrE:b-jbif44) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/lookup_join_test.go#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Very helpful - thanks!
___
*[pkg/sql/opt/ordering/lookup_join_test.go, line 72 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRHriX85oZS-Gn-CJVJ:-LRHriX85oZS-Gn-CJVK:bjd1t3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/aebca7ed520491fa3830d82195b6f58065f8a75c/pkg/sql/opt/ordering/lookup_join_test.go#L72)):*
> ```Go
> 			provided: "+5,+6",
> 		},
> 		{ // case 2: the lookup join produces all columns. The provided orderin
> ```

orderin -> ordering
___
*[pkg/sql/opt/ordering/row_number.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRE1eGo02JjDIXtbHHg:-LRHttT470x3nXf9EghV:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcd77dae8b6e6ffd65f7ef91e69022632525b6d8/pkg/sql/opt/ordering/row_number.go#L42)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I reworded it a bit, it should be more clear now.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2018-11-14 16:01 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/ordering/lookup_join_test.go, line 72 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-LRHriX85oZS-Gn-CJVJ:-LRHx6ZkEKjqDPgishQh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aebca7ed520491fa3830d82195b6f58065f8a75c/pkg/sql/opt/ordering/lookup_join_test.go#L72)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

orderin -> ordering
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-14 16:10 UTC, rytaft reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-14 21:49 UTC, RaduBerinde commented
Instea of #32320, I disabled the assertions for now. Not sure if we want to merge this now or I'll keep working on it when I get back.

2018-11-14 21:56 UTC, rytaft reviewed
Fine with me to merge, but maybe Andy has a different opinion

> Reviewed 1 of 2 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LRJDBRj47MDz9Cvjhre:b3vrg85)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-14 22:16 UTC, andy-kimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, I'm fine with it going in now or later. You can work on fixing the perf issue when you get back and re-enable the assert, based on our offline discussion of how we might fix the perf.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LRJHm2384EHRZgFn-_o:b-gpz1tn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-14 22:17 UTC, andy-kimball reviewed
But I don't think the assert + perf issue needs to block this, since this is an improvement of the status quo, even if there's a possible edge case where it has an issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32221#-:-LRJI32p5PykMjKOSMNQ:bynkiqo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-15 00:19 UTC, RaduBerinde commented
Thanks for the reviews. I put the asserts back in now that the fix for the constraints issue is in.

2018-11-15 00:47 UTC, merged