opt: Add optimizer support for new Insert operator
cockroachdb/cockroach pull request #32423
Opened 2018-11-16 18:42 UTC by andy-kimball

Add Insert operator to the optimizer.  The implementation is side-by-side
with the existing heuristic planner version. The main differences are that it
supports correlated subqueries, integrates with the CBO, and compiles
default and computed properties differently. Rather than keeping these
properties separate, the new Insert operator wraps the input expression
with Project operators that synthesize the default and computed
expressions.

2018-11-16 18:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32423)
<!-- Reviewable:end -->

2018-11-16 18:46 UTC, knz commented
niiice :tada:

2018-11-16 20:21 UTC, justinj reviewed
Looked at a bunch of this, need to let a bunch of it sit and will come back for another look later.

> Reviewed 22 of 22 files at r1, 3 of 3 files at r2, 7 of 7 files at r3, 3 of 3 files at r4, 31 of 31 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-:-LRTAjWE9NZ-hQl_zk4j:bwqdlza)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 1990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSqnVH9LjTSegC9Gc9:-LRSqnVH9LjTSegC9GcA:bzghtb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/logictest/testdata/logic_test/builtin_function#L1990)):*
> ```
> UTF8  NULL
> 
> # TODO(SQL execution team): Restore this to original form by removing FROM
> ```

nit: I believe the intention of the names is generally like, "who is the person you can ask about this", which I guess in this case would either be you or Jordan.
___
*[pkg/sql/opt/memo/testdata/logprops/join, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSrzcx4ofFxt3I2Oux:-LRSrzcx4ofFxt3I2Ouy:b-ng1jai) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/memo/testdata/logprops/join#L91)):*
> ```
>  │    │    ├── fd: ()-->(5,6)
>  │    │    ├── prune: (6)
>  │    │    ├── max1-row
> ```

nit/unrelated: I wonder if `Max1Row` should error if its input is provably >1 row? Perhaps that case is limited enough that it's not worth it.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSst2p8UBGQHu0TB0B:-LRSst2p8UBGQHu0TB0C:b-igbk1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/norm/custom_funcs.go#L556)):*
> ```Go
> // Project operator can be merged with the columns of a Values operator to form
> // a single combined Values operator. This is only possible when there is a
> // single Values row and when the projections are not dependent on columns from
> ```

Why must there be a single `Values` row? I think having an explanation of why these restrictions exist would be helpful.
___
*[pkg/sql/opt/norm/rules/project.opt, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSs_FK-Ps4quSuEY-i:-LRSs_FLDluRxvDjvCYC:b-ey6zhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/norm/rules/project.opt#L38)):*
> ```
> [MergeProjectWithValues, Normalize]
> (Project
>     $input:(Values)
> ```

Could this be something like `(Values [ * ])` and then `CanMergeProjectWithValues` doesn't have to check there's a single row?
___
*[pkg/sql/opt/optbuilder/insert.go, line 495 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT240z189d6ikPzDFa:-LRT240z189d6ikPzDFb:bnegix9) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L495)):*
> ```Go
> 	// explicitly specified:
> 	//
> 	//   INSERT INTO <table> (...) VALUES (...))
> ```

nit: extra `)`
___
*[pkg/sql/opt/optbuilder/insert.go, line 552 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT2qcZ7fciedfG7O9o:-LRT2qcZ7fciedfG7O9p:b46xuy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L552)):*
> ```Go
> 	ib.addSynthesizedCols(func(tabCol opt.Column) bool { return !tabCol.IsComputed() })
> 
> 	// Add any missing computed columns.
> ```

I think a comment might be helpful to clarify that this ordering is enforced because computed columns can depend on default columns (but not the other way around).
___
*[pkg/sql/opt/optbuilder/insert.go, line 593 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT3hw9C0b35sMCd4Sj:-LRT3hw9C0b35sMCd4Sk:bguv989) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L593)):*
> ```Go
> 		expr := ib.parseDefaultOrComputedExpr(tabColID)
> 		texpr := ib.outScope.resolveType(expr, tabCol.DatumType())
> 		scopeCol := ib.b.addColumn(projectionsScope, "" /* label */, texpr)
> ```

is there any reason not to set the label to `tabCol.ColName()`?
___
*[pkg/sql/opt/optbuilder/insert.go, line 672 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT4L_5B4l9h8Jskiee:-LRT4L_5B4l9h8Jskief:bynyxwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L672)):*
> ```Go
> 		more, less := "expressions", "target columns"
> 		if actual < expected {
> 			more, less = less, more
> ```

I like this, haha


<!-- Sent from Reviewable.io -->

2018-11-17 01:04 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/testdata/logprops/join, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSrzcx4ofFxt3I2Oux:-LRTrGNe1I3TWUF9qpkt:b56wchq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/memo/testdata/logprops/join#L91)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit/unrelated: I wonder if `Max1Row` should error if its input is provably >1 row? Perhaps that case is limited enough that it's not worth it.
</blockquote></details>

Yeah, maybe something we add in future, but not terribly important.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSst2p8UBGQHu0TB0B:-LRTs1ju8Rg18BP6k63U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/norm/custom_funcs.go#L556)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Why must there be a single `Values` row? I think having an explanation of why these restrictions exist would be helpful.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/project.opt, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRSs_FK-Ps4quSuEY-i:-LRU6Rhk64EmD0f-8HYP:b-r3e4kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a01a013049b2cdc3eda9c7bf8e0d981fd4e88869/pkg/sql/opt/norm/rules/project.opt#L38)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Could this be something like `(Values [ * ])` and then `CanMergeProjectWithValues` doesn't have to check there's a single row?
</blockquote></details>

Yes, it's a good idea. Though it does require a couple changes to Optgen, due to an unreferenced variable in this case.
___
*[pkg/sql/opt/optbuilder/insert.go, line 552 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT2qcZ7fciedfG7O9o:-LRU6xr-DQ1bGTxzYXKd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L552)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think a comment might be helpful to clarify that this ordering is enforced because computed columns can depend on default columns (but not the other way around).
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 593 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT3hw9C0b35sMCd4Sj:-LRU7JBL3Ir3mh6ynG_g:bdrolkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L593)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

is there any reason not to set the label to `tabCol.ColName()`?
</blockquote></details>

Well, I went back and forth a bit. The trouble is that if I set the columns in the input expression to the names of the target table columns, then it creates duplicate labels in the metadata. This in turn causes the formatter to fully qualify the names, which looks messy. I suppose I could come up with some other naming like `a_default` for the default value of an `a` column, or something.
___
*[pkg/sql/opt/optbuilder/insert.go, line 672 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRT4L_5B4l9h8Jskiee:-LRU8rFx6CSkV6Vhlcxz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/790a07362258d6f0ee85a52ee7f8857b7c0fb034/pkg/sql/opt/optbuilder/insert.go#L672)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I like this, haha
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-21 20:24 UTC, rytaft requested changes
I think I've reviewed about half of this.... great stuff!  Taking a break and will come back later and review the rest.

> Reviewed 17 of 22 files at r1, 49 of 49 files at r7, 3 of 3 files at r8, 7 of 7 files at r9, 3 of 3 files at r10, 30 of 33 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-:-LRrvuDS7cILdpm7z3xY:b-zi609z)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 584 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmyHUl81Ptj4Dc761f:-LRmyHUl81Ptj4Dc761g:bxk3z8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/exec/execbuilder/testdata/explain#L584)):*
> ```
>  └── values  ·              ·                                           (x int[])  ·
> ·            size           1 column, 1 row                             ·          ·
> ·            row 0, expr 0  (ARRAY[(1)[int],(2)[int],(3)[int]])[int[]]  ·          ·
> ```

This seems like a worse plan -- any idea why?
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1754 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRr_JYqA9mxR6Pm5gsj:-LRr_JYr1avGOC6RLn-C:btiw9h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/memo/statistics_builder.go#L1754)):*
> ```Go
> 	colSet opt.ColSet, ins *InsertExpr,
> ) *props.ColumnStatistic {
> 	return sb.colStat(colSet, ins.Input)
> ```

This isn't updating the cache for Insert -- maybe use `copyColStatFromChild`?
___
*[pkg/sql/opt/norm/custom_funcs.go, line 555 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmsFbY1unH2hafENsk:-LRmsFbY1unH2hafENsl:b-450154) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/norm/custom_funcs.go#L555)):*
> ```Go
> // MergeProjectWithValues merges a Project operator with its input Values
> // operator. This is only possible in certain circumstances, which must first be
> // validated by calling CanMergeProjectWithValues (see its header comment).
> ```

CanMergeProjectWithValues -> AreProjectionsCorrelated
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3487 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmzIz--_UH7A6rJoGP:-LRmzIz--_UH7A6rJoGQ:b-hsdar9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/norm/testdata/rules/decorrelate#L3487)):*
> ```
> project
>  ├── columns: i:2(int) y:7(int)
>  └── inner-join-apply
> ```

how come we could decorrelate this before but not anymore? 
___
*[pkg/sql/opt/optbuilder/insert.go, line 323 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrhA3r0djYof1e-_wf:-LRrhA3s0CJ_nvos92qf:byez8h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L323)):*
> ```Go
> 			if indexCol.Column.IsDefault() || indexCol.Column.IsComputed() {
> 				// The column has a default value.
> 				allNull = false
> ```

What if the default value is NULL?
___
*[pkg/sql/opt/optbuilder/insert.go, line 464 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrmDz847GUvs7Gd-dK:-LRrmDz94U5cOeuBciPn:b789syx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L464)):*
> ```Go
> 				val = ib.parseDefaultOrComputedExpr(ib.targetColList[itup])
> 			}
> 			newTuple = append(newTuple, val)
> ```

do you want to check if `newTuple != nil`?
___
*[pkg/sql/opt/optbuilder/insert.go, line 560 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrq3t7E8l_GUdc3afn:-LRrq3t7E8l_GUdc3afo:b6o8ljy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L560)):*
> ```Go
> // scans the list of table columns, looking for any that do not yet have values
> // provided by the input expression. New columns are synthesized for any missing
> // columns.
> ```

Can you add a sentence explaining what the `addCol` function does?
___
*[pkg/sql/opt/optbuilder/insert.go, line 572 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrvZLQDJ3iwItNQ00d:-LRrvZLQDJ3iwItNQ00e:bbtw1g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L572)):*
> ```Go
> 
> 		// Get column metadata, including any mutation columns.
> 		var tabCol opt.Column
> ```

Don't you already have a helper function for this? `tableColumnByOrdinal`?
___
*[pkg/sql/opt/optbuilder/insert.go, line 706 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruir76jX2WCFnG2mm:-LRruir8DiKtushOua8a:b-8ez0kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L706)):*
> ```Go
> 		exprStr = tabCol.DefaultExprStr()
> 	case tabCol.IsNullable():
> 		return tree.DNull
> ```

do you want to also cache this in `parsedExprs`?
___
*[pkg/sql/opt/optbuilder/insert.go, line 745 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruysxD7blUUpjO0Ev:-LRruysyD6sPnJPfli-i:b-v91kc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L745)):*
> ```Go
> 		n = ate.Expr
> 		// It's okay to ignore the As columns here, as they're not permitted in
> 		// DML aliases where this function is used.
> ```

should there be an error if they are used?
___
*[pkg/sql/opt/optbuilder/select.go, line 21 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqiR8w-uWamMpB5B3g:-LRqiR8w-uWamMpB5B3h:bdm4nxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14e451b6bd0ef65cf14187339b742770e004563/pkg/sql/opt/optbuilder/select.go#L21)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/sql/privilege"
> ```

[nit] extra space
___
*[pkg/sql/opt/optbuilder/util.go, line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqj2lK8_xy41eYTlpU:-LRqj2lK8_xy41eYTlpV:b-muqpe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14e451b6bd0ef65cf14187339b742770e004563/pkg/sql/opt/optbuilder/util.go#L423)):*
> ```Go
> // metadata, so that the privileges can be re-checked on reuse of the memo.
> func (b *Builder) checkPrivilege(ds opt.DataSource, priv privilege.Kind) {
> 	if !b.skipSelectPrivilegeChecks {
> ```

What if the privilege is UPDATE? Don't we still want to check?
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 267 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqpGNr9vFo01YhjQox:-LRqpGNr9vFo01YhjQoy:b-1aw7sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/testdata/insert#L267)):*
> ```
> INSERT INTO abcde WITH a AS (SELECT 1) VALUES (1, DEFAULT, 2)
> ----
> error (42601): DEFAULT can only appear in a VALUES list within INSERT or on the right side of a SET
> ```

This error message is a bit confusing... but I assume this is the same message we were using before?
___
*[pkg/sql/opt/testutils/testcat/test_catalog.go, line 508 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqwNkp9yGK_DWZmMTc:-LRqwNkp9yGK_DWZmMTd:bjrr58a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/testutils/testcat/test_catalog.go#L508)):*
> ```Go
> 
> // IsDefault is part of the opt.Column interface.
> func (tc *Column) IsDefault() bool {
> ```

[nit] maybe HasDefault would be a better name?


<!-- Sent from Reviewable.io -->

2018-11-22 03:06 UTC, rytaft requested changes
Done with the rest of the review -- only one additional (minor) comment. Impressive work!

> Reviewed 3 of 33 files at r11, 3 of 3 files at r12, 11 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-:-LRtN0KVAVuZv0zPXLgp:b6chwwn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/project.go, line 134 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRs3rUfDnG17gTCyTg9:-LRs3rUfDnG17gTCyTgA:b-iuogmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/project.go#L134)):*
> ```Go
> 						outScope.cols = make([]scopeColumn, 0, len(selects)+len(exprs)-1)
> 					}
> 					for i, e := range exprs {
> ```

now this is shadowing the outer `i`. Can you give it a new name? 


<!-- Sent from Reviewable.io -->

2018-11-23 01:43 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 584 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmyHUl81Ptj4Dc761f:-LRyBhD110dTN3L2euUU:b-xomu4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/exec/execbuilder/testdata/explain#L584)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This seems like a worse plan -- any idea why?
</blockquote></details>

The difference is that the `InlineProjectInProject` rule fired before, and now it doesn't, because we don't have an `InlineProjectInValues` rule. This seems like an edge case, so I don't think it's a priority to add such a rule.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1754 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRr_JYqA9mxR6Pm5gsj:-LRxex_m0inKnuPiWwWc:b6ycf40) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/memo/statistics_builder.go#L1754)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This isn't updating the cache for Insert -- maybe use `copyColStatFromChild`?
</blockquote></details>

But why cache it twice, both in the Insert cache and in the input node cache? Seems better to pass through calls, which will end up using the input node cache. I'd thought about just inlining this in `colStat`, but decided to put it here for consistency with other methods. Perhaps Go inlines it.
___
*[pkg/sql/opt/norm/custom_funcs.go, line 555 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmsFbY1unH2hafENsk:-LRxfiW16G1KUsCfG93T:b-dwiyr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/norm/custom_funcs.go#L555)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

CanMergeProjectWithValues -> AreProjectionsCorrelated
</blockquote></details>

Fixed the comment.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 3487 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRmzIz--_UH7A6rJoGP:-LRxfoEv4i4JPo33c3Rw:b-xxkczu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9d7583c9e5c87352101030cfb03a812bc7d501/pkg/sql/opt/norm/testdata/rules/decorrelate#L3487)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

how come we could decorrelate this before but not anymore? 
</blockquote></details>

Because of the new `MergeProjectWithValues` rule. To decorrelate this, we'd need a new rule that mapped `(InnerJoin <input> (Values)) => (Project <input> (Values))` when `Values` has cardinality one. Since this is quite an edge case, I don't think it's too important. But I'll keep in mind.
___
*[pkg/sql/opt/optbuilder/insert.go, line 323 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrhA3r0djYof1e-_wf:-LRxEnmv506IsxRXW-vf:b3t4pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L323)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if the default value is NULL?
</blockquote></details>

I'm matching the semantics of the existing code (in `makeBaseFKHelper`), and that code doesn't care whether a default value is NULL, or if a computed column evaluates to NULL.  I changed the name from `allNull` to `allMissing` to describe the current behavior better. This code really exists just to give a better error at compile-time; if the default or computed value turns out to be NULL at runtime, it should be correctly rejected (unless all values are NULL, of course).
___
*[pkg/sql/opt/optbuilder/insert.go, line 464 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrmDz847GUvs7Gd-dK:-LRxTrN4EToCfvbunl8V:b-f06h8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L464)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

do you want to check if `newTuple != nil`?
</blockquote></details>

Yes, good catch.
___
*[pkg/sql/opt/optbuilder/insert.go, line 560 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrq3t7E8l_GUdc3afn:-LRxUKba56YxvMp4eIsS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L560)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a sentence explaining what the `addCol` function does?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 572 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRrvZLQDJ3iwItNQ00d:-LRxUZ4N07MBFNLKJgRe:b-b1lpge) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L572)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Don't you already have a helper function for this? `tableColumnByOrdinal`?
</blockquote></details>

Yes, written at different times. Fixed to use the helper function.
___
*[pkg/sql/opt/optbuilder/insert.go, line 706 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruir76jX2WCFnG2mm:-LRxUhI37sLnOGfOxi-T:bm3h11r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L706)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

do you want to also cache this in `parsedExprs`?
</blockquote></details>

I had considered it, but decided not to, b/c it adds a bit more complexity for very little benefit.
___
*[pkg/sql/opt/optbuilder/insert.go, line 745 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruysxD7blUUpjO0Ev:-LRxWGww3E0GLBwOO7-l:btzdqne) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L745)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should there be an error if they are used?
</blockquote></details>

I just cut and pasted this method from `data_source.go`. I don't know what this comment means, so I removed it.
___
*[pkg/sql/opt/optbuilder/project.go, line 134 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRs3rUfDnG17gTCyTg9:-LRxWYTJ3CV5HxVS651X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/project.go#L134)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

now this is shadowing the outer `i`. Can you give it a new name? 
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/util.go, line 423 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqj2lK8_xy41eYTlpU:-LRxWpqICtQDSXmEbzKg:b-2jmcqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14e451b6bd0ef65cf14187339b742770e004563/pkg/sql/opt/optbuilder/util.go#L423)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if the privilege is UPDATE? Don't we still want to check?
</blockquote></details>

Hmm, I guess the existing planner code does check in case where an INSERT is embedded in a view. I fixed this and added a regression case. Good catch.
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 267 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRqpGNr9vFo01YhjQox:-LRxamW3DhS3X1c1-wWn:bu4ngvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/testdata/insert#L267)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This error message is a bit confusing... but I assume this is the same message we were using  [...]

2018-11-23 18:07 UTC, andy-kimball reviewed
I simplified the `InsertPrivate` structure by getting rid of the need for `TableCols`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-:-LS0k1ZwDHnAmcgaXcQC:b-edsfcy)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-24 14:29 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 60 files at r14, 3 of 3 files at r15, 3 of 7 files at r16, 1 of 3 files at r17, 36 of 36 files at r18, 3 of 3 files at r19, 11 of 11 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-:-LS56gWG1MFZzCny6fDH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/insert.go, line 745 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruysxD7blUUpjO0Ev:-LS53r339uaCsbhb2GP2:b-3qa6lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L745)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I just cut and pasted this method from `data_source.go`. I don't know what this comment means, so I removed it.
</blockquote></details>

Looks like you removed it in `data_source.go` but not here. I think it's referring to the fact that the `tree.AliasClause` may also have columns (e.g., `SELECT * FROM t AS a(b, c)`), but those column aliases aren't allowed in DML statements. I think it's actually a helpful comment, but maybe just needs a bit more info.
___
*[pkg/sql/opt/optbuilder/scope.go, line 580 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LS56Ehu7lOA7cL8q3RD:-LS56Ehu7lOA7cL8q3RE:bsyjuhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/optbuilder/scope.go#L580)):*
> ```Go
> 			col := &s.cols[i]
> 			// TODO(rytaft): Do not return a match if this column is being
> 			// backfilled, or the column expression being resolved is not from
> ```

Do you need to make any modifications here to ensure that mutation columns are not returned? If not, maybe you can update the TODO?


<!-- Sent from Reviewable.io -->

2018-11-28 16:04 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/ordering/insert.go, line 43 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LSQ2VRN8mY59A43XFGh:-LSQ2VRN8mY59A43XFGi:b-lexxli) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/ordering/insert.go#L43)):*
> ```Go
> 	// The child's provided ordering satisfies both <required> and the Insert
> 	// internal ordering; it may need to be trimmed.
> 	childProvided := expr.(*memo.InsertExpr).Input.ProvidedPhysical().Ordering
> ```

IIUC Insert doesn't output all input columns - only those in `InputCols` (and which are not mutation columns). In principle, we could need to remap columns here; this should look like `projectBuildProvided` 


<!-- Sent from Reviewable.io -->

2018-11-28 16:13 UTC, RaduBerinde commented
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 191 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LSQ4OeG9UyZiED_LV9I:-LSQ4OeG9UyZiED_LV9J:b-dy2je0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L191)):*
> ```Go
> 
> 	// Handle operators which can write data.
> 	if ep.root == nil {
> ```

A little fragile to define "can write" as "anything not handled yet" (e.g. if some of functioncalled above has a bug and returns a `nil` root, we would get a very confusing error).

We could add a `Mutation` tag and use that.  We can then move the check up (`if opt.IsMutation(e) && b.evalCtx.TxnReadOnly { return err }`) and move `case InsertExpr` in the switch above.


<!-- Sent from Reviewable.io -->

2018-11-29 00:23 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 191 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LSQ4OeG9UyZiED_LV9I:-LSRiF1y14HiZPPWO3dp:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/exec/execbuilder/relational_builder.go#L191)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A little fragile to define "can write" as "anything not handled yet" (e.g. if some of functioncalled above has a bug and returns a `nil` root, we would get a very confusing error).

We could add a `Mutation` tag and use that.  We can then move the check up (`if opt.IsMutation(e) && b.evalCtx.TxnReadOnly { return err }`) and move `case InsertExpr` in the switch above.
</blockquote></details>

Good idea. Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 745 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LRruysxD7blUUpjO0Ev:-LSRj15L0KkN1PMzzWnf:byujdft) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dba693946f736ece43633058b9d17121f1107a3/pkg/sql/opt/optbuilder/insert.go#L745)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks like you removed it in `data_source.go` but not here. I think it's referring to the fact that the `tree.AliasClause` may also have columns (e.g., `SELECT * FROM t AS a(b, c)`), but those column aliases aren't allowed in DML statements. I think it's actually a helpful comment, but maybe just needs a bit more info.
</blockquote></details>

I see. No, there doesn't need to be an error here because the SQL grammar does not allow the syntax. So the parser would error if you try to use them, and it never gets here. I added a bit to the comment to clarify that.
___
*[pkg/sql/opt/optbuilder/scope.go, line 580 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LS56Ehu7lOA7cL8q3RD:-LSRk0We1QlUqAsFyw1j:bv9a7xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/optbuilder/scope.go#L580)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you need to make any modifications here to ensure that mutation columns are not returned? If not, maybe you can update the TODO?
</blockquote></details>

I removed the TODO. At least so far, the scopes never make mutation columns accessible to the query to begin with. Mutation columns are treated as if they were computed columns, and added only after expressions have been analyzed. I removed the TODO.
___
*[pkg/sql/opt/ordering/insert.go, line 43 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LSQ2VRN8mY59A43XFGh:-LSRkyXu3ifbxjpGMxRp:b-6l8jmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/ordering/insert.go#L43)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

IIUC Insert doesn't output all input columns - only those in `InputCols` (and which are not mutation columns). In principle, we could need to remap columns here; this should look like `projectBuildProvided` 
</blockquote></details>

It's not possible to use mutation columns in ordering expressions (or any other expression for that matter, besides possibly another computed mutation expression). Doesn't that mean we can just ignore remapping? I added a check in `check_expr.go` to ensure we never use mutation columns as output or ordering columns.


<!-- Sent from Reviewable.io -->

2018-11-29 02:01 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32423)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/ordering/insert.go, line 43 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/32423#-LSQ2VRN8mY59A43XFGh:-LSSBh247I8qep4DIddv:b-qy14dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e03446a2915268fc25f5110e2f19bb9c65efd4f/pkg/sql/opt/ordering/insert.go#L43)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

It's not possible to use mutation columns in ordering expressions (or any other expression for that matter, besides possibly another computed mutation expression). Doesn't that mean we can just ignore remapping? I added a check in `check_expr.go` to ensure we never use mutation columns as output or ordering columns.
</blockquote></details>

After our discussion, I added a call to `remapProvided`. I also added a test in `xform/testcases/physprops/ordering`.


<!-- Sent from Reviewable.io -->

2018-11-29 04:15 UTC, andy-kimball commented
bors r+

2018-11-29 04:38 UTC, merged