ui: render errors in Loading component
cockroachdb/cockroach pull request #32464
Opened 2018-11-19 14:38 UTC by celiala

Previously, data fetching errors were not being consistently surfaced to
the user. This commit updates all existing uses of the Loading component
to surface these errors:

 - Some parent components were rendering data from multiple sources,
   potentially having multiple errors to show the user. This commit also
   extends the Loading component to handle multiple errors.
 - The Certificates page had custom loading logic. This commit replaces
   logic with Loading component.

Also in this commit is some minor cleanup (copy, layout).

Release note (admin ui change): This commit wires up data errors to all
existing uses of the Loading component. Previously, data errors weren't
consistently surfaced.

2018-11-19 14:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32464)
<!-- Reviewable:end -->

2018-11-19 17:33 UTC, couchand requested changes
This is great, thanks for taking on this task!  I left a handful of minor nits & questions, let me know if anything is unclear.  Thanks!

> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-:-LRh0w8p4pXqqc_4XKGm:b758w4c)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgtn6Z7pvj3mWuqqzH:-LRgtn6Z7pvj3mWuqqzI:b-dllfyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx#L37)):*
> ```XML
> import { TreeNode, TreePath } from "./tree";
> import "./index.styl";
> import {selectLivenessRequestStatus, selectNodeRequestStatus} from "oss/src/redux/nodes";
> ```

you should only need to prefix an import with `oss` if it's CCL code importing the OSS version of precisely the same file (for fallback purposes).  otherwise, starting import paths with `src` should always pick up the right file.

I know that Pete's editor sometimes automatically adds it, perhaps you have the same editor config...
___
*[pkg/ui/src/views/reports/containers/range/allocator.tsx, line 67 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgv5IVBkBYOd6ylEPj:-LRgv5IVBkBYOd6ylEPk:b-2injg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/reports/containers/range/allocator.tsx#L67)):*
> ```XML
>     // case, but making major changes to the CachedDataReducer or util.api seems
>     // fraught at this point.  We should revisit this soon.
>     if (allocator.lastError && allocator.lastError.message === "Forbidden") {
> ```

It's hard to know if the other code that does just `if (allocator)` and `loading={!allocator}` is being excessively defensive or not, but it makes me nervous to move this dereference before one of those checks without some kind of validation.

It seems like, since the type is just `CachedDataReducerState`, it should be initialized by Redux on app startup and we shouldn't ever get here with it being falsey.  If that logic is sound, we can probably remove the (apparently) excessively defensive checks in the rest of the code.  On the other hand, if there's a flaw in that logic, we should add one of those checks here.
___
*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 87 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgwLGVEP3N4Z37C1Rg:-LRgwLGVEP3N4Z37C1Rh:bl6pvuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/reports/containers/settings/index.tsx#L87)):*
> ```XML
>         </Helmet>
>         <h1>Cluster Settings</h1>
>         <h2></h2> {/* TODO(vilterp): why is this here? just for spacing? */}
> ```

looks like it's always been there.  https://github.com/cockroachdb/cockroach/commit/0bf60a6dadf1d692ff6ac3368a4602215a4f5988#diff-7fb3b6a2810f0f9be12ec4c2e3f4dff4R81

seems safe to delete unless it throws off the page layout significantly, and even then there's probably a clearer way to achieve the goal.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgwsxaAn_PFOrRAHx7:-LRgwsxaAn_PFOrRAHx8:b-bmle1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/index.tsx#L40)):*
> ```XML
>     } else {
>       // Remove null values from Error[].
>       const validErrors = _.filter(errors, (e) => { return !!e; });
> ```

It doesn't seem like lodash is really helping here.

also the closure can be much terser: `e => !!e`
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 80 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgxdLp1sdsTpT5b36p:-LRgxdLp1sdsTpT5b36q:br4ugp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/index.tsx#L80)):*
> ```XML
>       );
>     }
>     return (
> ```

There doesn't seem to be a lot of value special casing a single error now.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgyFjN0dEvBsNCuetF:-LRgyFjN0dEvBsNCuetG:b-b59dms) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L40)):*
> ```XML
> 
> describe("<Loading>", () => {
>   describe("renders correctly for various states.", () => {
> ```

In test results the nested `describe` titles are just concatenated with the `it` titles.  There's an opportunity to hack them to make each one just a word or phrase so that they read as sentences when all put together.

I also like to use outer describes structurally to setup each part of the scenario.  For instance, I'd recommend organizing these tests something like:

```
describe "<Loading>"
  describe "when error is null"
    describe "when loading=false"
      it "renders content."
    describe "when loading=true"
      it "renders loading spinner."
  describe "when error is a single error"
    describe "when loading=false"
      it "renders error."
    describe "when loading=true"
      it "renders error anyway"
  describe "when error is a list of errors"
    describe "when no errors are null"
      ...
    describe "when some errors are null"
      ...
    describe "when all errors are null"
      ...
```

Personally I prefer something like that to come conjunctions and conditionals in a given test title.

Just to clarify, these tests do cover the necessary logic, so I'm happy with them as-is, just thought I'd take the opportunity to share some thoughts here.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 166 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRh0VIFCyJmhjGJ4oBb:-LRh0VIFCyJmhjGJ4oBc:bix8kpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L166)):*
> ```XML
>     // Single errors are rendered inside a <pre></pre>;
>     // Multiple errors are listed in <ul><li> list.
>     const expectedSelector = props.errorCount === 1 ? "pre" : "li";
> ```

The markup wraps `pre`s in `li`s, so could we just always look for the `pre`s?  Does `ReactWrapper#find` do deep searching?

I ask because I really don't like conditionals in a test if we can avoid it.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 170 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRh035XEuLPuR6WKOEy:-LRh035XEuLPuR6WKOEz:b76d740) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L170)):*
> ```XML
>       wrapper.find("div." + ERROR_CLASS_NAME).find(expectedSelector),
>       props.errorCount,
>       "number of errors was not " + props.errorCount,
> ```

I really like the message attached to the above assertion, because it translates from what (the length is wrong) to why (element should/should not be visible).  This one just rehashes what the default "expected/actual" would already say, so it doesn't really add anything.


<!-- Sent from Reviewable.io -->

2018-11-21 18:35 UTC, celiala reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32464)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgtn6Z7pvj3mWuqqzH:-LRqjtxj-xn7k_SGEQ9v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx#L37)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

you should only need to prefix an import with `oss` if it's CCL code importing the OSS version of precisely the same file (for fallback purposes).  otherwise, starting import paths with `src` should always pick up the right file.

I know that Pete's editor sometimes automatically adds it, perhaps you have the same editor config...
</blockquote></details>

Done.
___
*[pkg/ui/src/views/reports/containers/range/allocator.tsx, line 67 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgv5IVBkBYOd6ylEPj:-LRrH_L05LgWFbjZDaD5:b-bohi99) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/reports/containers/range/allocator.tsx#L67)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It's hard to know if the other code that does just `if (allocator)` and `loading={!allocator}` is being excessively defensive or not, but it makes me nervous to move this dereference before one of those checks without some kind of validation.

It seems like, since the type is just `CachedDataReducerState`, it should be initialized by Redux on app startup and we shouldn't ever get here with it being falsey.  If that logic is sound, we can probably remove the (apparently) excessively defensive checks in the rest of the code.  On the other hand, if there's a flaw in that logic, we should add one of those checks here.
</blockquote></details>

Done.

It looks like allocator is derived from `KeyedCachedDataReducerState[range_id_key]`, which could potentially be `undefined`, so I'll add an extra `if (allocator && ..` check here.
___
*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 87 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgwLGVEP3N4Z37C1Rg:-LRrKCxV3-2kzpzxCKig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/reports/containers/settings/index.tsx#L87)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

looks like it's always been there.  https://github.com/cockroachdb/cockroach/commit/0bf60a6dadf1d692ff6ac3368a4602215a4f5988#diff-7fb3b6a2810f0f9be12ec4c2e3f4dff4R81

seems safe to delete unless it throws off the page layout significantly, and even then there's probably a clearer way to achieve the goal.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgwsxaAn_PFOrRAHx7:-LRrLWVM18lrAOXD9Frr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/index.tsx#L40)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It doesn't seem like lodash is really helping here.

also the closure can be much terser: `e => !!e`
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/index.tsx, line 80 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgxdLp1sdsTpT5b36p:-LRrL_CT-GZ0aWVzq7EU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/index.tsx#L80)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

There doesn't seem to be a lot of value special casing a single error now.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 40 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRgyFjN0dEvBsNCuetF:-LRrQPg77ho6niG_Q7Mg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L40)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

In test results the nested `describe` titles are just concatenated with the `it` titles.  There's an opportunity to hack them to make each one just a word or phrase so that they read as sentences when all put together.

I also like to use outer describes structurally to setup each part of the scenario.  For instance, I'd recommend organizing these tests something like:

```
describe "<Loading>"
  describe "when error is null"
    describe "when loading=false"
      it "renders content."
    describe "when loading=true"
      it "renders loading spinner."
  describe "when error is a single error"
    describe "when loading=false"
      it "renders error."
    describe "when loading=true"
      it "renders error anyway"
  describe "when error is a list of errors"
    describe "when no errors are null"
      ...
    describe "when some errors are null"
      ...
    describe "when all errors are null"
      ...
```

Personally I prefer something like that to come conjunctions and conditionals in a given test title.

Just to clarify, these tests do cover the necessary logic, so I'm happy with them as-is, just thought I'd take the opportunity to share some thoughts here.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 166 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRh0VIFCyJmhjGJ4oBb:-LRrM53w5zeqKpJEkCHE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L166)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

The markup wraps `pre`s in `li`s, so could we just always look for the `pre`s?  Does `ReactWrapper#find` do deep searching?

I ask because I really don't like conditionals in a test if we can avoid it.
</blockquote></details>

Done.
___
*[pkg/ui/src/views/shared/components/loading/loading.spec.tsx, line 170 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRh035XEuLPuR6WKOEy:-LRrR2GbDtMfkuebX8hd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/120c0b321b0fc8a2d846a3d7b71dc53fd528d3ad/pkg/ui/src/views/shared/components/loading/loading.spec.tsx#L170)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I really like the message attached to the above assertion, because it translates from what (the length is wrong) to why (element should/should not be visible).  This one just rehashes what the default "expected/actual" would already say, so it doesn't really add anything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-21 18:36 UTC, celiala commented
Thanks for the feedback (incorporated). PTAL, thanks! :)

2018-11-21 19:46 UTC, couchand approved these changes
Awesome, good work.

> Reviewed 1 of 21 files at r8, 11 of 11 files at r9, 1 of 1 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-:-LRrnqWLByg8Gj9U8Ahe:bgmawj0)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRrnF0BCmL6LU94-i8t:-LRrnF0BCmL6LU94-i8u:b-5qkbqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c70565a8bff36d19e996295d2bea7554347794e8/pkg/ui/src/views/reports/containers/settings/index.tsx#L82)):*
> ```XML
>   render() {
>     return (
>       <div className="section">
> ```

It seems like having just the one `className="section"` up here is cleaner... is there a reason you moved it below?


<!-- Sent from Reviewable.io -->

2018-11-21 21:33 UTC, celiala reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32464)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/reports/containers/settings/index.tsx, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32464#-LRrnF0BCmL6LU94-i8t:-LRsAj_aBSfvWzc-xXyy:b-uy0fx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c70565a8bff36d19e996295d2bea7554347794e8/pkg/ui/src/views/reports/containers/settings/index.tsx#L82)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It seems like having just the one `className="section"` up here is cleaner... is there a reason you moved it below?
</blockquote></details>

Oops, was tinkering around and forgot to clean up; will revert back to one `className="section"` and add a .styl sheet to add padding to just the `<p>` note.


<!-- Sent from Reviewable.io -->

2018-11-21 21:39 UTC, celiala commented
bors r=couchand
TFTR!

2018-11-21 21:53 UTC, vilterp commented
w00t!

2018-11-21 21:56 UTC, merged