opt: Add expression and xform rule for secondary index zigzag joins
cockroachdb/cockroach pull request #32512
Opened 2018-11-20 21:24 UTC by itsbilal

This change adds an optimizer expression, coster, statistics/logical
property builder as well as a simple xform rule to generate zigzag joins
in the case where we have select filters with const values on prefixes
of two separate secondary indexes.

Things to improve (either in this PR or in future ones): 
- [ ] Xform rules to catch more zigzaggable instances
- [x] More accurate statistics calculations (currently, zigzag joins wrapped with lookup joins can't compete with index-join selects due to the much higher row count)
- [ ] Better index selection algorithm instead of a quadratic iteration
- [ ] Refactor and split up `GenerateZigzagJoins` in `custom_funcs`  (probably best to do it alongside the above task)

Release note: None

2018-11-20 21:38 UTC, itsbilal commented
Speedup with this change and this [zigzag-oriented benchmark](https://github.com/itsbilal/cockroach/blob/00ce4edf15a049292df08ab708bb54122d782066/pkg/bench/bench_test.go#L1130):

```
name                             old time/op  new time/op  delta
ZigzagJoin/Cockroach-4           12.0ms ±14%  10.3ms ±20%     ~     (p=0.056 n=5+5)
ZigzagJoin/CockroachOpt-4        11.1ms ±10%   0.7ms ±29%  -94.16%  (p=0.008 n=5+5)
ZigzagJoin/MultinodeCockroach-4  11.7ms ±15%   0.7ms ±34%  -94.20%  (p=0.008 n=5+5)
```

2018-11-20 22:36 UTC, justinj reviewed
just did a first pass, my high-level comment is that I would find it helpful if there was a canonical location that described when and how it's possible to plan a zigzag join (because it definitely seems nontrivial), so I can try to build up the intuition a little more easily as I read the code.

> Reviewed 10 of 10 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LRnFkKI2qoJ51BAmfhE:b-lsq3md)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 934 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn-wQu0J5lDOc2KtM2:-LRn-wQu0J5lDOc2KtM3:b-z8pjvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/relational_builder.go#L934)):*
> ```Go
> 	// Build the fixed value scalars. These are represented as one value node
> 	// per side of the join, containing one row/tuple with fixed values for
> 	// a prefix of that index' columns.
> ```

nit: index's
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0eQPCJqOnf-XUyjr:-LRn0eQPCJqOnf-XUyjs:bzg4hor) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L508)):*
> ```
> render            ·         ·                      (a)              ·
>  │                render 0  a                      ·                ·
>  └── zigzag-join  ·         ·                      (b, a, b, c, a)  ·
> ```

This seems slightly sketchy - should this be outputting columns multiple times?
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 792 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0E9u2BJMDOWxZ9NI:-LRn0E9u2BJMDOWxZ9NJ:boizfoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L792)):*
> ```
> ----
> ts3  1
> ts   1
> ```

doesn't really matter but I don't think this needed to change? actually I don't think we even usually have execution tests in the execbuilder at all, maybe you should just delete this test/move it to a logic test?
___
*[pkg/sql/opt/exec/execbuilder/testdata/stats, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0pZIAXapxWwMX6Ul:-LRn0pZIAXapxWwMX6Um:b-2c8gaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/stats#L26)):*
> ```
>  │                render 0  u                      ·                                           ·
>  │                render 1  v                      ·                                           ·
>  └── zigzag-join  ·         ·                      (u, rowid[hidden], v, v, rowid[hidden], u)  ·
> ```

same here, perhaps we can remove the duplicated columns here?
___
*[pkg/sql/opt/memo/expr_format.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn10vq4YTcoC128fbN:-LRn10vq4YTcoC128fbO:bh8e1b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/expr_format.go#L162)):*
> ```Go
> 
> 	case *ZigzagJoinExpr:
> 		fmt.Fprintf(f.Buffer, "%v (zigzag", t.JoinType)
> ```

can a zigzag even service a regular join? will this `JoinType` ever be different than `inner`?
___
*[pkg/sql/opt/memo/expr_format.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn1MFKExer4Sqv7CsH:-LRn1MFKExer4Sqv7CsI:b-sf0hhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/expr_format.go#L616)):*
> ```Go
> 		leftTab := f.Memo.metadata.Table(t.LeftTable)
> 		rightTab := f.Memo.metadata.Table(t.RightTable)
> 		if t.LeftIndex == opt.PrimaryIndex {
> ```

slightly more succinct/idiomatic:
```
fmt.Fprintf(f.Buffer, " %s", leftTab.Name().TableName)
if t.LeftIndex != opt.PrimaryIndex {
    fmt.Fprintf(f.Buffer, "@%s", leftTab.Index(t.LeftIndex).IdxName())
}
```
___
*[pkg/sql/opt/memo/extract.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn1gu0DmzPE8Cz8WrX:-LRn1gu0DmzPE8Cz8WrY:b-hm38qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L235)):*
> ```Go
> }
> 
> // ExtractFixedColumns returns columns in filter expression that have been
> ```

nit: `in the filters expression`
___
*[pkg/sql/opt/memo/extract.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn223m5UP-XZJ6vFb3:-LRn223m5UP-XZJ6vFb4:ba0jd8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L241)):*
> ```Go
> ) (fixedCols opt.ColSet) {
> 	for i := range on {
> 		if on[i].Op() != opt.FiltersItemOp {
> ```

when is this the case? for like, `true`, or something?
___
*[pkg/sql/opt/memo/extract.go, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2GlHCBGP3vBMAlPs:-LRn2GlHCBGP3vBMAlPt:bjpjj9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L255)):*
> ```Go
> // getConstrainedCols returns constrained prefixes in the set of constraints
> // passed in.
> func getConstrainedCols(
> ```

nit: the way this is named it sounds to me like it's any columns with a constraint (for instance, I would say `x` is constrained in `x < 10 and x > 3`). Consider renaming to `getConstCols` or something.
___
*[pkg/sql/opt/memo/extract.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2byFBVRoyyafg0EF:-LRn2byFBVRoyyafg0EG:b-yh69nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L265)):*
> ```Go
> }
> 
> // ExtractValueFromFilter iterates through filter expr and builds a map of constant
> ```

nit: "through the filters expr", but I think this comment can just describe the result, rather than what's done to get it:
"ExtractValueFromFilter returns a map of constant columns to their values"
or something.
___
*[pkg/sql/opt/memo/extract.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2i1X6wBxhqW-4sCV:-LRn2i1X6wBxhqW-4sCW:b-ioehu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L269)):*
> ```Go
> func ExtractValuesFromFilter(
> 	on FiltersExpr, cols opt.ColSet,
> ) map[int]tree.Datum {
> ```

nit: I think this should be `map[opt.ColumnID]tree.Datum`.
___
*[pkg/sql/opt/memo/extract.go, line 287 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn35Kw4w0pbNyjRY3D:-LRn35Kw4w0pbNyjRY3E:b-kdra5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L287)):*
> ```Go
> // extractFixedEquality extracts a column that's being equated to a constant
> // value if possible.
> func extractFixedEquality(
> ```

I think one line this? (lint will probably complain)
___
*[pkg/sql/opt/memo/extract.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn45-z-9CkNy5c2c9N:-LRn45-z-9CkNy5c2c9O:b-wgl339) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L290)):*
> ```Go
> 	condition opt.ScalarExpr,
> ) (bool, int, tree.Datum) {
> 	if eq, ok := condition.(*EqExpr); ok {
> ```

I think you should be able to consult the scalar props to determine constant columns (see the `Constraints` property on props.Scalar, I think it has an existing method for this).
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn [...]

2018-11-22 16:55 UTC, rytaft requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 501 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRwIxLf72f-s3lD4tCG:-LRwIxLgEjLU_XL7NZYJ:b-esm7cd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1e907a34021230a7b420aaef8a1584fb5b347b/pkg/sql/opt/exec/execbuilder/testdata/select_index#L501)):*
> ```
> ·                 table     t@b_desc               ·                ·
> ·                 table     t@bc                   ·                ·
> ·                 pred      (@3 = 5) AND (@4 = 1)  ·                ·
> ```

It seems like this is a worse plan than before. Check the coster to make sure we still prefer index scans when we can build a tight constraint.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn4c4W1ERGc1bb2U8L:-LRwKidWE0zUSRZUneRP:bnpukfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/logical_props_builder.go#L446)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

The more I think about zigzag I'm not sure I'm convinced that it's similar enough to other join types to be lumped in with them? Can you service arbitrary joins with a zigzag? I don't think so, right? I think it could possibly make more sense to just make it its own thing (either way I think the code in `buildJoinProps` could just be inlined here, since it's unique to this join type (right?).
</blockquote></details>

Seems more like an `IndexJoin`, no?
___
*[pkg/sql/opt/xform/rules/join.opt, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRwK0Rt3H-umNeWH2jf:-LRwK0Ru6Zw9GaDCxOA5:bixxpem) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1e907a34021230a7b420aaef8a1584fb5b347b/pkg/sql/opt/xform/rules/join.opt#L61)):*
> ```
> [GenerateZigzagJoins, Explore]
> (Select
>     (Scan $scan:*)
> ```

Should probably check if `IsCanonicalScan` (see `GenerateLookupJoins` above)


<!-- Sent from Reviewable.io -->

2018-11-23 21:35 UTC, itsbilal reviewed
There's a pretty large high-level comment about zigzag joins in `pkg/sql/distsqlrun/zigzagjoiner.go` that talks about when they can be planned, how the internal schema looks, and everything. I've also added a much smaller comment in `pkg/sql/zigzag_join.go` about it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LRrWQaZ6sUaVUZZWz5o:bl03vkj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 934 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn-wQu0J5lDOc2KtM2:-LS0WGnbEfTMzVBkZx8W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/relational_builder.go#L934)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: index's
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0eQPCJqOnf-XUyjr:-LRraaty21ZJO6lYnNi7:bvjmsvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L508)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This seems slightly sketchy - should this be outputting columns multiple times?
</blockquote></details>

This is basically a design choice - it makes the `ResultColumn` logic easier in `opt_exec_factory` since we don't need to keep track of columns we've output already. Instead we can just keep appending every index scans' column descriptors one after the other everywhere. That way it'll also be easy to extend a lot of the planning logic to 2+ way zigzag joins.

If having repeated columns with a projection on top is bad for performance or makes less sense, I'm open to adding code to the exec factory to explicitly watch for and remove the duplication (or I could add a TODO to do that).
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 792 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0E9u2BJMDOWxZ9NI:-LRraXv50_LDcdAqaFmO:b-tx5928) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L792)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

doesn't really matter but I don't think this needed to change? actually I don't think we even usually have execution tests in the execbuilder at all, maybe you should just delete this test/move it to a logic test?
</blockquote></details>

Done. Reverted this change.
___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 501 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRwIxLf72f-s3lD4tCG:-LS1T34O6NO2p_Ycfj_B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb1e907a34021230a7b420aaef8a1584fb5b347b/pkg/sql/opt/exec/execbuilder/testdata/select_index#L501)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It seems like this is a worse plan than before. Check the coster to make sure we still prefer index scans when we can build a tight constraint.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/stats, line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0pZIAXapxWwMX6Ul:-LRrd_BUAPDS8qBzGSfe:b-tv7gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/stats#L26)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

same here, perhaps we can remove the duplicated columns here?
</blockquote></details>

See comment earlier
___
*[pkg/sql/opt/memo/expr_format.go, line 162 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn10vq4YTcoC128fbN:-LRreCrN4bQ4qNWVLLsO:bw9pt3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/expr_format.go#L162)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

can a zigzag even service a regular join? will this `JoinType` ever be different than `inner`?
</blockquote></details>

The underlying joiner supports left joins, so it makes sense to propagate it through the planNode and everything. Even if we don't currently plan any non-inner zigzags.
___
*[pkg/sql/opt/memo/expr_format.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn1MFKExer4Sqv7CsH:-LRri3oBBIZp04BQGyFp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/expr_format.go#L616)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

slightly more succinct/idiomatic:
```
fmt.Fprintf(f.Buffer, " %s", leftTab.Name().TableName)
if t.LeftIndex != opt.PrimaryIndex {
    fmt.Fprintf(f.Buffer, "@%s", leftTab.Index(t.LeftIndex).IdxName())
}
```
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn1gu0DmzPE8Cz8WrX:-LRrjeqp76GaPFOKiHa1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L235)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: `in the filters expression`
</blockquote></details>

Done
___
*[pkg/sql/opt/memo/extract.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn223m5UP-XZJ6vFb3:-LRrjfh95DYv8pGLeEmm:be6or2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L241)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

when is this the case? for like, `true`, or something?
</blockquote></details>

Just a sanity check in general, but yes - the most common case would be when we just put a `True` here as a default.
___
*[pkg/sql/opt/memo/extract.go, line 255 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2GlHCBGP3vBMAlPs:-LRrk80p2wWyvViFgp5y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L255)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: the way this is named it sounds to me like it's any columns with a constraint (for instance, I would say `x` is constrained in `x < 10 and x > 3`). Consider renaming to `getConstCols` or something.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2byFBVRoyyafg0EF:-LRrkOXtDRE5YEfKYtP6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L265)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: "through the filters expr", but I think this comment can just describe the result, rather than what's done to get it:
"ExtractValueFromFilter returns a map of constant columns to their values"
or something.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn2i1X6wBxhqW-4sCV:-LRrkV4UBZf-0uWCs56X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/extract.go#L269)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: I think this should be `map[opt.ColumnID]tree.Datum`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 287 at r3](https:/ [...]

2018-11-24 23:02 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 446 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn4c4W1ERGc1bb2U8L:-LS6wZon9hb7lLCHLjW3:b-kif0dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/memo/logical_props_builder.go#L446)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Good point - this would also help with the stats / cardinality issues that we're seeing, if we have a completely dedicated code path for zigzag joins when it comes to logical props and stats. I'll make that set of changes by the end of the week, since it might be pretty substantial. 
</blockquote></details>

So this is what I ended up doing, after playing around with a couple solutions:

- Added `joinPropsBuilder` support for zigzag joins (it looks for `leftProps` and `rightProps` in the expr - similar to lookup joins)
- Use said props builder for building logical props - and since the builder has support for zigzags now, the rest of the code just does the right thing here
- In statsbuilder, I still use the join `colStat` function for zigzag joins, while using a zigzag-specific initial statistics building function (`buildZigzag`). That function is more similar to index joins. A lot of the colStat code would have looked a lot like that of the join one anyway (except with all the outer-join cases taken out for simplicity), and `colStatFromJoin{Left,Right}` already know to do the right thing with zigzags so the amount of special casing required was pretty small.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1009 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRnEdpg0Tay0B9CWXQt:-LS6w9xA2Kv3jXjUKUec:be2bj6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/xform/custom_funcs.go#L1009)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. The lookup join had the advantage of filters getting embedded right into the join, but I worked around it by wrapping an IndexJoin in a select. Which is better for stats anyway.
</blockquote></details>

Ended up reverting to `LookupJoinExpr` - since index joins do not support arbitrary non-index-scan inputs. It made more sense to use the general case instead of adding more special-case logic to `IndexJoinExpr`.


<!-- Sent from Reviewable.io -->

2018-11-26 16:38 UTC, rytaft requested changes
> Reviewed 9 of 10 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0eQPCJqOnf-XUyjr:-LSFhdNXA9jvRU5NdwhR:bxz5y7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L508)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This is basically a design choice - it makes the `ResultColumn` logic easier in `opt_exec_factory` since we don't need to keep track of columns we've output already. Instead we can just keep appending every index scans' column descriptors one after the other everywhere. That way it'll also be easy to extend a lot of the planning logic to 2+ way zigzag joins.

If having repeated columns with a projection on top is bad for performance or makes less sense, I'm open to adding code to the exec factory to explicitly watch for and remove the duplication (or I could add a TODO to do that).
</blockquote></details>

+1 to getting rid of duplicate output columns. You can store the already-added columns in a `ColSet`, and check for duplicates using `if colSet.Contains(col)`. We use this pattern in several other places in the code. 
___
*[pkg/sql/opt/memo/statistics_builder.go, line 306 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFlYTqDF0cKSOGm9rj:-LSFlYTqDF0cKSOGm9rk:b6g9wl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L306)):*
> ```Go
> 		opt.SemiJoinOp, opt.AntiJoinOp, opt.InnerJoinApplyOp, opt.LeftJoinApplyOp,
> 		opt.RightJoinApplyOp, opt.FullJoinApplyOp, opt.SemiJoinApplyOp, opt.AntiJoinApplyOp,
> 		opt.LookupJoinOp, opt.ZigzagJoinOp:
> ```

I'm still a bit surprised that the regular join logic works for zig zag join... to me it seems more similar to an index join. But I'll be more convinced if you add some tests -- you need to add tests for both logical properties and stats.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSFjg_98I_WWerBRf_X:b-z2izuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
> ```Go
> 	// row counts. An example of such a case would be a zigzag on secondary
> 	// indexes of the same table.
> 	s.RowCount = max(leftStats.RowCount, rightStats.RowCount)
> ```

When would the left and right sides ever have different row counts? Aren't these indexes from the same table?


<!-- Sent from Reviewable.io -->

2018-11-27 19:53 UTC, itsbilal reviewed
I've rebased on master (now that the dependent PR is merged). Reviewing this should be easier now - PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LSLiny60_7vKsNK-1V8:b-5wrxgl)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 508 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LRn0eQPCJqOnf-XUyjr:-LSLhp8d3BCjEdBWWQb5:b4c2ie9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d1653c480bce6c7280aec66522f4bd2fe67dd2/pkg/sql/opt/exec/execbuilder/testdata/select_index#L508)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

+1 to getting rid of duplicate output columns. You can store the already-added columns in a `ColSet`, and check for duplicates using `if colSet.Contains(col)`. We use this pattern in several other places in the code. 
</blockquote></details>

Done. Zigzags effectively have an implicit project built into them now (similar to lookup joins)..
___
*[pkg/sql/opt/memo/statistics_builder.go, line 306 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFlYTqDF0cKSOGm9rj:-LSLhqxf-amhQVCxFHoD:b48amdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L306)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'm still a bit surprised that the regular join logic works for zig zag join... to me it seems more similar to an index join. But I'll be more convinced if you add some tests -- you need to add tests for both logical properties and stats.
</blockquote></details>

I added some tests for stats. I'm not sure how I'd go around testing logical props - don't those show up as output in every test case where we test opt expressions?

Also, zigzags working with the usual join logic isn't too surprising when you notice the implementation is pretty similar to that of lookup joins (with side-specific logical properties nested inside the expr). Once we're able to get some sense of `left` and `right` props, which is pretty straightforward, the rest does the right thing.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSLi3p_DK49ZXgMnfrj:b-3h7u4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

When would the left and right sides ever have different row counts? Aren't these indexes from the same table?
</blockquote></details>

It shouldn't - just added the max as a sanity check. Any other ideas?


<!-- Sent from Reviewable.io -->

2018-11-27 21:03 UTC, rytaft requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 306 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFlYTqDF0cKSOGm9rj:-LSLwtwfCeIuZRlOWElU:b-gas0dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L306)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I added some tests for stats. I'm not sure how I'd go around testing logical props - don't those show up as output in every test case where we test opt expressions?

Also, zigzags working with the usual join logic isn't too surprising when you notice the implementation is pretty similar to that of lookup joins (with side-specific logical properties nested inside the expr). Once we're able to get some sense of `left` and `right` props, which is pretty straightforward, the rest does the right thing.
</blockquote></details>

Now that I think about it, are you sure this code is actually being called? Logical props and stats are only calculated for normalized expressions, so if `ZigZagJoin` is always an alternate expression then it shouldn't need logical props or stats code. For example, `MergeJoin` does not have code for logical properties or stats. 

But if it is called, you can test the logical props by adding some test cases inside `memo/testdata/logprops`. You're right that the props show up in many other places, but it's a good idea to add targeted tests for the range of possible logical properties (see the other tests in that directory for examples).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSLuzNJBlkAKLPNptuv:b-h5mhws) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It shouldn't - just added the max as a sanity check. Any other ideas?
</blockquote></details>

I would just use `leftStats.RowCount`, and add a comment saying that they should be the same. If you think you need a sanity check, you could add a panic if the two are not equal (unless you can think of a legitimate reason why they would be different).


<!-- Sent from Reviewable.io -->

2018-11-27 21:11 UTC, rytaft commented
___
*[pkg/sql/opt/memo/statistics_builder.go, line 306 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFlYTqDF0cKSOGm9rj:-LSM-Q388nhpE-6jzaTT:bd7yvcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L306)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Now that I think about it, are you sure this code is actually being called? Logical props and stats are only calculated for normalized expressions, so if `ZigZagJoin` is always an alternate expression then it shouldn't need logical props or stats code. For example, `MergeJoin` does not have code for logical properties or stats. 

But if it is called, you can test the logical props by adding some test cases inside `memo/testdata/logprops`. You're right that the props show up in many other places, but it's a good idea to add targeted tests for the range of possible logical properties (see the other tests in that directory for examples).
</blockquote></details>

Sorry ignore that -- I see that it should be getting called since there is a ConstructZigZagJoin call inside GenerateZigZagJoins. But beware that it *won't* be called if the ZigZag is not the normalized expression in its group (e.g. if it's not wrapped in a lookup join).


<!-- Sent from Reviewable.io -->

2018-11-27 21:14 UTC, rytaft commented
___
*[pkg/sql/opt/memo/testdata/stats/select, line 819 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSM0BWE8XPL46bB25-B:-LSM0BWE8XPL46bB25-C:bq2rx3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/823a6365d5c271ef12ed14d48de35cd0121ee6c5/pkg/sql/opt/memo/testdata/stats/select#L819)):*
> ```
> WHERE
>     l_shipdate = DATE '1995-09-01'
>     AND l_commitdate = DATE '1995-08-01';
> ```

I don't think this test is actually exercising your stats code. I think it's probably using the stats that were calculated for the normalized SELECT expression (which is probably why the stats are exactly the same as the norm case below...)


<!-- Sent from Reviewable.io -->

2018-11-27 21:59 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 306 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFlYTqDF0cKSOGm9rj:-LSMA7ad4vxK-ZTcokrx:b-8un1p9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L306)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Sorry ignore that -- I see that it should be getting called since there is a ConstructZigZagJoin call inside GenerateZigZagJoins. But beware that it *won't* be called if the ZigZag is not the normalized expression in its group (e.g. if it's not wrapped in a lookup join).
</blockquote></details>

Yep - it's called in the case of zigzag joins being nested inside lookup joins. I took a look at the logprops folder and it looks like it mostly only concerns itself with normalized expressions (having almost no `opt` test cases).

We do implicitly test zigzag logprops whenever we do an `opt` with a nested zigzag join as the output, and when we're `RaceEnabled`, we also ensure that non-nested zigzag joins have the same logprops as selects/scans in the same group. In fact, those tests caught some `OutputCols` inconsistencies that I just fixed.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSM9oo91-1_KzTD1sMx:b-diza42) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I would just use `leftStats.RowCount`, and add a comment saying that they should be the same. If you think you need a sanity check, you could add a panic if the two are not equal (unless you can think of a legitimate reason why they would be different).
</blockquote></details>

Done. Don't think a sanity check is necessary, actually. 
___
*[pkg/sql/opt/memo/testdata/stats/select, line 819 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSM0BWE8XPL46bB25-B:-LSM9tjs7VtjLElb-sdo:b-nwvmdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/823a6365d5c271ef12ed14d48de35cd0121ee6c5/pkg/sql/opt/memo/testdata/stats/select#L819)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think this test is actually exercising your stats code. I think it's probably using the stats that were calculated for the normalized SELECT expression (which is probably why the stats are exactly the same as the norm case below...)
</blockquote></details>

It is - I was able to find a bug in `colStatJoin` this way. Though I don't think the single-column `colstat=11 colstat=12` directives are triggering colstat generation, but the `11,12` case definitely is.


<!-- Sent from Reviewable.io -->

2018-11-27 22:06 UTC, rytaft commented
___
*[pkg/sql/opt/memo/testdata/stats/select, line 819 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSM0BWE8XPL46bB25-B:-LSMBX5H2taQnfUOzXfb:b-5b31xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/823a6365d5c271ef12ed14d48de35cd0121ee6c5/pkg/sql/opt/memo/testdata/stats/select#L819)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It is - I was able to find a bug in `colStatJoin` this way. Though I don't think the single-column `colstat=11 colstat=12` directives are triggering colstat generation, but the `11,12` case definitely is.
</blockquote></details>

Ok, I guess those `colstat` directives are applied after optimization - makes sense. But I doubt this is testing the code in `buildZigzagJoin`. And it sounds like it's not testing the single-column stats. I'd suggest adding another test where the zigzag is wrapped in a lookup join so you test all the different code paths.


<!-- Sent from Reviewable.io -->

2018-11-27 22:10 UTC, rytaft commented
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSMCk4Y-ugSTlJ9w1os:b-igqhie) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Don't think a sanity check is necessary, actually. 
</blockquote></details>

I would make the comment more explicit (e.g., "the left and right indexes are from the same table, so the row count should be the same")


<!-- Sent from Reviewable.io -->

2018-11-28 16:34 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/statistics_builder.go, line 1245 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSFjg_98I_WWerBRf_W:-LSQ8np3BhhOCDE-mQAi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ff14498d821b1d3667531cfd3b4a4c872655389/pkg/sql/opt/memo/statistics_builder.go#L1245)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I would make the comment more explicit (e.g., "the left and right indexes are from the same table, so the row count should be the same")
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/select, line 819 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSM0BWE8XPL46bB25-B:-LSQ8p96CxLMZDCO1Fqr:b-3zxpe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/823a6365d5c271ef12ed14d48de35cd0121ee6c5/pkg/sql/opt/memo/testdata/stats/select#L819)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok, I guess those `colstat` directives are applied after optimization - makes sense. But I doubt this is testing the code in `buildZigzagJoin`. And it sounds like it's not testing the single-column stats. I'd suggest adding another test where the zigzag is wrapped in a lookup join so you test all the different code paths.
</blockquote></details>

Done. We were already implicitly testing `buildZigzagJoin` whenever we tested the selection of a zigzag-nested-inside-lookup join in the xform tests by the optimizer. But now we also have a more explicit test.


<!-- Sent from Reviewable.io -->

2018-12-03 16:21 UTC, RaduBerinde reviewed
This has been a ton of work, great job! I have some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LSorPSMCg9_HLtbaJmc:bw2lqbw)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 236 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSopaJ19-iJqrRvzuBR:-LSopaJ19-iJqrRvzuBS:btg3sp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/extract.go#L236)):*
> ```Go
> // ExtractFixedColumns returns columns in the filters expression that have been
> // constrained to fixed values.
> func ExtractFixedColumns(
> ```

[nit] We call these `Const` columns in existing cases, I'd stick to that name
___
*[pkg/sql/opt/ops/relational.opt, line 312 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSonNJM48imdk2epZ7y:-LSonNJM48imdk2epZ7z:b-j08wj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L312)):*
> ```
> define ZigzagJoinPrivate {
> 	# JoinType is InnerJoin or LeftJoin.
> 	JoinType Operator
> ```

What a left join means here (if indeed it's possible) needs to be documented, since we don't have an explicit "left" input..  If it's a join that outputs all the rows from the left index, then it's not really a zig-zag, it's a regular lookup join.

I would remove this field unless/until we have a use case.
___
*[pkg/sql/opt/ops/relational.opt, line 330 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSooMFu1WHpQhzKHtn3:-LSooMFu1WHpQhzKHtn4:b-kz4k52) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L330)):*
> ```
> 	RightEqCols ColList
> 
> 	# FixedVals, LeftFixedCols and RightFixedCols reference fixed values.
> ```

What are "fixed" values?
___
*[pkg/sql/opt/ops/relational.opt, line 339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSonD-IB_h4OLq7p8aR:-LSonD-IB_h4OLq7p8aS:b-jcsf3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L339)):*
> ```
> 	Cols ColSet
> 
> 	leftProps RelProps
> ```

Hm, I don't think we have other cases with unexported fields, do these need to be private? I think they need a comment either way
___
*[pkg/sql/opt/xform/custom_funcs.go, line 851 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSopufz6TFAdi0j7zdO:-LSopufz6TFAdi0j7zdP:byp2m1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/xform/custom_funcs.go#L851)):*
> ```Go
> 	// Efficiently finding pairs (or, in the future when zigzagjoiner supports
> 	// n-way zigzag joins, sets) of indexes that make the most efficient zigzag
> 	// join is an instance of this NP-hard problem:
> ```

[nit] Finding pairs can't be an NP-hard problem since there are only N^2 possible pairs. I'd rephrase to make it clearer that the n-way problem is NP-hard.


<!-- Sent from Reviewable.io -->

2018-12-03 18:37 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 240 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSoh3Zh6WiZm5INqYeF:-LSoh3Zi198ta532Ivss:b57qb62) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/extract.go#L240)):*
> ```Go
> ) (fixedCols opt.ColSet) {
> 	for i := range on {
> 		if on[i].Op() != opt.FiltersItemOp {
> ```

The items of a `FiltersExpr` are already strongly-typed as `FiltersItem`, so there's no need to test `Op` as well.
___
*[pkg/sql/opt/memo/extract.go, line 257 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSohzgEAK7KcNJIeTe7:-LSohzgEAK7KcNJIeTe8:b-tf7xia) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/extract.go#L257)):*
> ```Go
> 	vals := make(map[opt.ColumnID]tree.Datum)
> 	for i := range on {
> 		if on[i].Op() != opt.FiltersItemOp {
> ```

Same here; this check is unnecessary.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 396 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSojoLt-ZXEoCG87aSv:-LSojoLt-ZXEoCG87aSw:b9o30rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/logical_props_builder.go#L396)):*
> ```Go
> 	// ----------
> 	if !b.disableStats {
> 		// Zigzag joins have their own stats builder case.
> ```

I think it'd be a bit better API-wise to put this check into the beginning of `buildJoin`. I'd expect a method called `buildJoin` to be able to build statistics for any kind of join.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1390 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSoipAI3eCGxns9HsU4:-LSoipAI3eCGxns9HsU5:bes5etm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/logical_props_builder.go#L1390)):*
> ```Go
> 		h.filterIsTrue = false
> 		h.filterIsFalse = h.filters.IsFalse()
> 	case *ZigzagJoinExpr:
> ```

NIT: add blank line before `case`
___
*[pkg/sql/opt/memo/statistics_builder.go, line 225 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSol7Lk5UyxPYP7-91U:-LSol7Lk5UyxPYP7-91V:b-67da2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/statistics_builder.go#L225)):*
> ```Go
> 	}
> 
> 	if lookupJoin != nil || zigzagJoin != nil || opt.IsJoinOp(e) {
> ```

Not loving where this logic has ended up, but this PR is not at fault, and doesn't seem right time to tackle it.
___
*[pkg/sql/opt/xform/testdata/rules/join, line 1271 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSoo9U75-KbOx_6gZQb:-LSoo9U75-KbOx_6gZQc:b-bvkgnx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/xform/testdata/rules/join#L1271)):*
> ```
>       └── c > n [type=bool, outer=(2,6), constraints=(/2: (/NULL - ]; /6: (/NULL - ])]
> 
> # --------------------------
> ```

These tests look insufficient to me. For example, what about:

1. Multi-column indexes
2. More than 2 indexes available
3. Indexes with types other than INT
4. Indexes with additional columns beyond the "fixed" prefix
5. More than 2 equality predicates that create ambiguous situations, where there's choice between indexes

etc.


<!-- Sent from Reviewable.io -->

2018-12-03 19:18 UTC, rytaft requested changes
> Reviewed 3 of 17 files at r10, 17 of 17 files at r12, 7 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 279 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpH8Y30MVZptMkCggn:-LSpH8Y30MVZptMkCggo:b-z651s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/extract.go#L279)):*
> ```Go
> 			}
> 		}
> 		if rightVar, ok := eq.Right.(*VariableExpr); ok {
> ```

I think you only need to check the left side -- the variable should always be on the left due to the `CommuteVar` rule.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1399 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpJOUH-Y66xlZyKjuS:-LSpJOUH-Y66xlZyKjuT:b7prt4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/logical_props_builder.go#L1399)):*
> ```Go
> 		h.filterNotNullCols = b.rejectNullCols(h.filters)
> 
> 		// Apply the zigzag join equalities
> ```

[nit] end comment with a period.
___
*[pkg/sql/opt/ops/relational.opt, line 315 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpLGGg1IgdkaRXH4qn:-LSpLGGh0eKNghdsb39r:b-c610um) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L315)):*
> ```
> 
> 	# LeftTable and RightTable identifies the left and right tables for this
> 	# join.
> ```

Will these ever be different tables? If not, it seems excessive to pass the same table twice.
___
*[pkg/sql/opt/ops/relational.opt, line 336 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpLiuY4d1a4shlStBw:-LSpLiuZ6SJcDhAvs58x:b1asw10) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L336)):*
> ```
> 
> 	# Cols is the set of columns produced by the zigzag join. This set can
> 	# contain columns from any of the side indexes.
> ```

what are the "side indexes"?
___
*[pkg/sql/opt/xform/coster.go, line 329 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpM-dB50R6Eal47CX1:-LSpM-dB50R6Eal47CX2:b8n9tll) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/xform/coster.go#L329)):*
> ```Go
> 	scanCost += c.rowScanCost(join.RightTable, join.RightIndex, 0)
> 
> 	cost := memo.Cost(rowCount) * (cpuCostFactor + 2*seqIOCostFactor + scanCost)
> ```

I think this needs a comment -- why are you multiplying `seqIOCostFactor` by 2, but not `cpuCostFactor`?
___
*[pkg/sql/opt/xform/custom_funcs.go, line 780 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpNS636rom_DTkArNT:-LSpNS636rom_DTkArNU:b-loqop5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/xform/custom_funcs.go#L780)):*
> ```Go
> 	leftEqCols opt.ColList,
> 	rightEqCols opt.ColList,
> ) (opt.ColList, opt.ColList) {
> ```

[nit] I would label these return values for clarity. e.g.:
```
) (leftEqPrefix, rightEqPrefix opt.ColList) {
	leftEqPrefix = make(opt.ColList, 0, len(leftEqCols))
	rightEqPrefix = make(opt.ColList, 0, len(rightEqCols))
```


<!-- Sent from Reviewable.io -->

2018-12-04 19:00 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/extract.go, line 236 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSopaJ19-iJqrRvzuBR:-LStvV3KAs4JBgsoVl60:b-blktdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/extract.go#L236)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We call these `Const` columns in existing cases, I'd stick to that name
</blockquote></details>

Done. I went with `Fixed` since that's what the giant comment in `pkg/sql/distsqlrun/zigzagjoiner.go` (something we're treating as an authoritative source on how zigzag joins work) refers to them as. But `Const` makes more sense at least in `extract.go`.
___
*[pkg/sql/opt/memo/extract.go, line 279 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpH8Y30MVZptMkCggn:-LSu8iBLELJScLPu0WKj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/extract.go#L279)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you only need to check the left side -- the variable should always be on the left due to the `CommuteVar` rule.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 240 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSoh3Zh6WiZm5INqYeF:-LStwc-fCoMPwQByjs5T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/extract.go#L240)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The items of a `FiltersExpr` are already strongly-typed as `FiltersItem`, so there's no need to test `Op` as well.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/extract.go, line 257 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSohzgEAK7KcNJIeTe7:-LStwgMiDYMwdwWnJEDJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/extract.go#L257)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Same here; this check is unnecessary.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1399 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpJOUH-Y66xlZyKjuS:-LSu9Ykq5DVNUGE9_l6x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/memo/logical_props_builder.go#L1399)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] end comment with a period.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 396 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSojoLt-ZXEoCG87aSv:-LSu9NJr725Z0An4i8MQ:b5wf5tn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/logical_props_builder.go#L396)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be a bit better API-wise to put this check into the beginning of `buildJoin`. I'd expect a method called `buildJoin` to be able to build statistics for any kind of join.
</blockquote></details>

Done. That makes sense.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1390 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSoipAI3eCGxns9HsU4:-LSu9VT-5QHO8AzMl7RU:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4abd6d2e4056d6aef9d7f5a41b3dd14925248cd2/pkg/sql/opt/memo/logical_props_builder.go#L1390)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: add blank line before `case`
</blockquote></details>

Done. 
___
*[pkg/sql/opt/ops/relational.opt, line 312 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSonNJM48imdk2epZ7y:-LSu9oHIDJJtl51vZUVz:b-74bepi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L312)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What a left join means here (if indeed it's possible) needs to be documented, since we don't have an explicit "left" input..  If it's a join that outputs all the rows from the left index, then it's not really a zig-zag, it's a regular lookup join.

I would remove this field unless/until we have a use case.
</blockquote></details>

Done. Removed it.
___
*[pkg/sql/opt/ops/relational.opt, line 315 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpLGGg1IgdkaRXH4qn:-LSuACef85SmmXs2-kuL:b-b0tpzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L315)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Will these ever be different tables? If not, it seems excessive to pass the same table twice.
</blockquote></details>

All of the underlying implementation supports multiple tables, even though the xform rule will not plan them yet. The processor spec asks for a slice of table descriptors. I kept support for multiple tables in case we decide to support it.
___
*[pkg/sql/opt/ops/relational.opt, line 330 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSooMFu1WHpQhzKHtn3:-LSuAioc0hOrTkybkG0l:b-te9x13) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L330)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What are "fixed" values?
</blockquote></details>

Constant values to constrain the columns referenced in the `{Left,Right}FixedCols` lists. Making it more explicit in the comment.
___
*[pkg/sql/opt/ops/relational.opt, line 336 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpLiuY4d1a4shlStBw:-LSuCY5B6EGBUXHagCJd:bpe960f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L336)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what are the "side indexes"?
</blockquote></details>

Rewording it to `either side's index`. We refer to each side of a zigzag join as a side, and the associated index is the side index.
___
*[pkg/sql/opt/ops/relational.opt, line 339 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSonD-IB_h4OLq7p8aR:-LSuCqxdDUQnFEF0G76x:b-shn9hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/ops/relational.opt#L339)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, I don't think we have other cases with unexported fields, do these need to be private? I think they need a comment either way
</blockquote></details>

Added a comment. We have a similar setup in `LookupJoinPrivate` with an unexported RelProps.
___
*[pkg/sql/opt/xform/coster.go, line 329 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpM-dB50R6Eal47CX1:-LSts8ar0HadJYkXZ53D:bjua9fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3234d3f8cae0509ba344fd3a6b821a635ad229f1/pkg/sql/opt/xform/coster.go#L329)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this needs a comment -- why are you multiplying `seqIOCostFactor` by 2, but not `cpuCostFactor`?
</blockquote></details>

Done. Left a comment, and doubled cpuCostFactor as well.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 780 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSpNS636rom_DTkArNT:-LStvSRh39tWdTWQ4buc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/b [...]

2018-12-04 19:38 UTC, rytaft approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> nicely done!

> Reviewed 22 of 22 files at r14, 7 of 7 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LSuf4eDCcN6xvyEoge6:b-vdj6eg)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-04 23:09 UTC, rytaft approved these changes
New changes for the session flag LGTM

> Reviewed 11 of 11 files at r16, 8 of 8 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-:-LSvTojB-nugXfobNi5P:by04lo6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-12-05 15:49 UTC, justinj reviewed
> Reviewed 1 of 19 files at r7, 3 of 10 files at r8, 1 of 5 files at r9, 4 of 22 files at r14, 2 of 11 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/testutils/opt_tester.go, line 135 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSz15QV41WIhRUD9hpg:-LSz15QV41WIhRUD9hph:b-5kpvz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/332d5c847986eda57bf607b5147634db2b7b3cf9/pkg/sql/opt/testutils/opt_tester.go#L135)):*
> ```Go
> 	// Enable zigzag joins for all opt tests. Execbuilder tests exercise
> 	// cases where this flag is false.
> 	ot.evalCtx.SessionData.ZigzagJoinEnabled = true
> ```

I'm mildly :-1: on having the behaviour here being by default globally different from prod, one alternative we discussed was having an argument like

```
opt flags=(zigzag, ...)
...
```

But I'm just posting this so the option is documented, what you've done <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> in the interest of getting this in soon!


<!-- Sent from Reviewable.io -->

2018-12-05 16:08 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32512)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/testutils/opt_tester.go, line 135 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/32512#-LSz15QV41WIhRUD9hpg:-LSz6IsN7Orm3E8nP6Qx:bc2wcad) ([raw file](https://github.com/cockroachdb/cockroach/blob/332d5c847986eda57bf607b5147634db2b7b3cf9/pkg/sql/opt/testutils/opt_tester.go#L135)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I'm mildly :-1: on having the behaviour here being by default globally different from prod, one alternative we discussed was having an argument like

```
opt flags=(zigzag, ...)
...
```

But I'm just posting this so the option is documented, what you've done :lgtm: in the interest of getting this in soon!
</blockquote></details>

Good point. I'd also agree in principle - though the advantage of turning this flag on for all opt tests is that it lets us preemptively test for cases where we unintentionally plan bad zigzag joins. The hope is that this flag will soon default to on anyway and then we can remove this.


<!-- Sent from Reviewable.io -->

2018-12-05 16:09 UTC, itsbilal commented
bors r+

2018-12-05 16:45 UTC, merged