raftentry: rewrite storage.raftEntryCache with dense, per-replica state
cockroachdb/cockroach pull request #32618
Opened 2018-11-26 22:21 UTC by ajwerner

_### Problem

This blocking profile is filtered to show all Mutex contention (ignoring other
forms like channels and Cond vars). We can see that blocking in the
`raftEntryCache` is responsible for **99%** of all Mutex contention. This seems
absurd, but it adds up given that the cache is responsible for **3%** of CPU
utilization on a node and requires mutual exclusion across an entire `Store`.

We've also seen in changes like #29596 how expensive these cache accesses have
become, especially as the cache grows because most entry accesses take `log(n)`
time, where `n` is the number of `raftpb.Entry`s in the cache across all Ranges
on a Store.

_### Rewrite

This PR rewrites the `raftEntryCache` as a new `storage/raftentries.Cache` type.
It picks up from https://github.com/cockroachdb/cockroach/pull/30152.
The rewrite diverges from the original implementation in two important ways,
both of which exploit and optimize for the unique access patterns that this
cache is subject to.

_#### Per Replica Cache State

The first change is to move from a single global data tree with per-entry LRU
state to per-range caches which evict entire ranges.  This makes maintaining the
LRU linked-list significantly cheaper because we only need to update it once per
Replica access instead of once per entry access. It also means that the
linked-list will be significantly smaller, resulting in far fewer memory
allocations and a reduced GC footprint.

The per-replica state also enables dramatically reducing the amount of work done while
holding the cache mutex. Because individual ranges are never accessed
concurrently, by optimistically computing space requirements, we can allow
operations to on different ranges to proceed at the same time.

In order to maintain a cap on the total amount of data which can be stored in
cache, the size of cache additions are computed before looking at the cache and
then space is freed such that the entire write will be able to fit in the cache.
This downside of this approach is that it can lead to overly aggressive evictions
in cases where large amounts of data which are already present in the cache are
added again. This edge case is not particularly concerning as it implies that
the cache is poorly sized for the workload.

_#### LLRB -> Ring Buffers

The second change is that the rewrite trades in the balanced binary tree
structure for a per-replica ring buffer structure. This structure is preferable
because it improves the time complexity of entry access. It's also more memory
efficient and allocation friendly because it takes advantage of builtin Go
slices and their compile-time specialization. Finally, it should be more GC
friendly because it cuts down on the number of pointers in use.

It turns out that Raft entries are densely ordered with discrete indices.
This means that given a low and a high index, we can simply iterate through the
range efficiently, without the need for an ordered data-structure. This property
was also exploited in 6e4e57f. The problem with a dense data structure it that
it makes dealing with disjoint ranges cumbersome and wasteful without further
specialization. Rather than shouldering the complexity of supporting caching
disjoint ranges, this implementation chooses to ignore writes which do not
overlap with existing cached entries.

It may be worth evaluating a different policy where lower index
entries are removed rather than higher index entries. Data from KV5 workloads
do not show that any entries are dropped due to this policy. When a node is
catching up, it's possible that old logs not be cached.

_### Performance

```
name                 old time/op    new time/op    delta
EntryCache-8           2.32ms ±10%    0.12ms ± 3%   -94.93%  (p=0.008 n=5+5)
EntryCacheClearTo-8     277µs ±11%       0µs ± 3%   -99.96%  (p=0.008 n=5+5)

name                 old alloc/op   new alloc/op   delta
EntryCache-8            113kB ± 0%     189kB ± 0%   +67.38%  (p=0.016 n=4+5)
EntryCacheClearTo-8    8.31kB ± 0%    0.00kB       -100.00%  (p=0.008 n=5+5)

name                 old allocs/op  new allocs/op  delta
EntryCache-8            2.02k ± 0%     0.00k ± 0%   -99.80%  (p=0.008 n=5+5)
EntryCacheClearTo-8      14.0 ± 0%       0.0       -100.00%  (p=0.008 n=5+5)
```

```
name       old ops/s   new ops/s   delta
KV5        17.1k ± 1%  17.7k ± 2%  +3.06%  (p=0.008 n=5+5)
```

Release note (performance improvement): Rewrite Raft entry cache to optimize for access patterns, reduce lock contention, and reduce memory footprint.

2018-11-26 22:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32618)
<!-- Reviewable:end -->

2018-11-26 22:39 UTC, nvb requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSH8cupBJ7zaACwi-JK:-LSH8cupBJ7zaACwi-JL:b-b2jyx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2659d6e4349d6307331f6800e5a056a7c90dbdc/pkg/storage/raftentry/cache.go#L183)):*
> ```Go
> 
> func (c *Cache) recordUpdate(p *partition, bytesAdded, bytesGuessed, entriesAdded int) {
> 	c.mu.Lock()
> ```

Planning on giving this a more thorough review tomorrow morning, but I have one question already. Do you think it's possible to avoid this second lock? You have a nice optimization to guess at the impact that a set of entries will have on the size of the cache during the initial lock. This allows us to guarantee that we never need to evict in this mutual exclusion zone. I'd hope this would allow us to avoid this second lock entirely! 

Could we push some of this logic into the partition and perform the rest (e.g. `c.bytes += delta`) using atomic operations? The gauges are already thread-safe, so then the only other thing to worry about is deleting empty partitions. This seems like a rare enough case to justify the lock. Maybe we never do this unless the replica is being removed from the Store?


<!-- Sent from Reviewable.io -->

2018-11-26 23:38 UTC, nvanbenschoten commented
Also, what was the command you used to run `kv5`, and what kind of cluster did you run it on? I'm curious whether you performed any splits and what your load concurrency was.

2018-11-27 01:52 UTC, ajwerner reviewed
Here's the command:
`./workload run kv '{pgurl:1-3}' --init --splits=4096 --duration 60s --read-percent=5 --concurrency=4096`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSHr7gB3xc0GEpfv5cw:b4w3umb)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-11-27 01:56 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSH8cupBJ7zaACwi-JK:-LSHrbTp0U53zIQPNTEg:b-4pkkhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2659d6e4349d6307331f6800e5a056a7c90dbdc/pkg/storage/raftentry/cache.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Planning on giving this a more thorough review tomorrow morning, but I have one question already. Do you think it's possible to avoid this second lock? You have a nice optimization to guess at the impact that a set of entries will have on the size of the cache during the initial lock. This allows us to guarantee that we never need to evict in this mutual exclusion zone. I'd hope this would allow us to avoid this second lock entirely! 

Could we push some of this logic into the partition and perform the rest (e.g. `c.bytes += delta`) using atomic operations? The gauges are already thread-safe, so then the only other thing to worry about is deleting empty partitions. This seems like a rare enough case to justify the lock. Maybe we never do this unless the replica is being removed from the Store?
</blockquote></details>

Seems like it'll take a little bit of thought to make sure the bookkeeping stays correct in the case of evictions but doesn't seem crazy. Let me see what I can come up with. Making the partition deletion explicit seems pretty reasonable and ultimately probably a better solution. In the interim I think we can avoid grabbing the lock in cases where the size doesn't go to zero. Let me take another pass and then we'll see where we are. 


<!-- Sent from Reviewable.io -->

2018-11-27 16:48 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSH8cupBJ7zaACwi-JK:-LSL2Nmg5XeKTFC_MAQn:bukwmhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2659d6e4349d6307331f6800e5a056a7c90dbdc/pkg/storage/raftentry/cache.go#L183)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Seems like it'll take a little bit of thought to make sure the bookkeeping stays correct in the case of evictions but doesn't seem crazy. Let me see what I can come up with. Making the partition deletion explicit seems pretty reasonable and ultimately probably a better solution. In the interim I think we can avoid grabbing the lock in cases where the size doesn't go to zero. Let me take another pass and then we'll see where we are. 
</blockquote></details>

Got rid of the second locking. For now we just defer to the LRU to remove empty partitions. I could see giving empty partitions some size in the accounting so that we don't leak memory growing huge list of empty partitions but it seems like it would take a pretty pathological workload where we never actually fill the cache to get to that place.

![Master](https://files.reviewableusercontent.io/images/reviewable/1839234/LvrK8RY3gvitJz0uKfkhZr3G/Screenshot%20from%202018-11-27%2011-39-26.png)
![New cache with single locking](https://files.reviewableusercontent.io/images/reviewable/1839234/8oyACpekW56OErNpdzJPnXkb/Screenshot%20from%202018-11-27%2011-39-32.png)


<!-- Sent from Reviewable.io -->

2018-11-27 19:03 UTC, nvb reviewed
I did a first pass looking at the `ringBuffer` implementation. Mostly just nits, I like the structure. 

We can get rid of `pkg/storage/entry_cache.go` and `pkg/storage/entry_cache_test.go`, right?

> Reviewed 5 of 11 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSLNhif5vfaSPmcxOl6:bthm1u3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/ring_buffer.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLUYxxBb9_xos8JrBt:-LSLUYxy4boblzCqh5X9:bna90g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L23)):*
> ```Go
> 
> // ringBuf is a ring buffer of raft entries.
> type ringBuf struct {
> ```

It's probably worth adding a few small unit tests for this type to make sure the resizing is working as expected.
___
*[pkg/storage/raftentry/ring_buffer.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLSAk4312WTtY8MBR7:-LSLSAk4312WTtY8MBR8:b-rq23iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L41)):*
> ```Go
> 	before, after, ok := computeExtension(b, ents[0].Index, ents[len(ents)-1].Index)
> 	if !ok {
> 		return
> ```

So if there's a gap then we don't add anything? I was expecting that we'd replace what was already there, but maybe that's not right. What's the trade-off here?
___
*[pkg/storage/raftentry/ring_buffer.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLVwxT0CSm11DpbaP8:-LSLVwxT0CSm11DpbaP9:bivhxr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L45)):*
> ```Go
> 	extend(b, before, after)
> 	it := first(b)
> 	if before == 0 && after != b.len {
> ```

Drop a comment like `// Ignore unchanged prefix.` here. Took me some time to figure out what it was doing.
___
*[pkg/storage/raftentry/ring_buffer.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLWRTF-f7gbdFGdyjC:-LSLWRTF-f7gbdFGdyjD:b-qauhoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L66)):*
> ```Go
> 	}
> 	it, ok := first(b), true
> 	firstIndex := int(it.index(b))
> ```

Super nit: I'd leave `firstIndex` as a `uint64` and cast after the subtraction to keep it clear that this is an operation in the Raft log index domain and not in the buffer index domain.
___
*[pkg/storage/raftentry/ring_buffer.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLXizI9kzL_1vss8sV:-LSLXizI9kzL_1vss8sW:b-394d87) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L94)):*
> ```Go
> 
> func (b *ringBuf) scan(
> 	ents []raftpb.Entry, id roachpb.RangeID, lo, hi, maxBytes uint64,
> ```

Why do you need `id`?
___
*[pkg/storage/raftentry/ring_buffer.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLU4DmDt1JfCVi37mp:-LSLU4DmDt1JfCVi37mq:b2sgpdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L119)):*
> ```Go
> 
> // realloc copies the data from the current slice into new buf leaving
> // before buf untouched
> ```

This comment looks like it was written when the function had different params.
___
*[pkg/storage/raftentry/ring_buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLU9o12y9wxU-fES0k:-LSLU9o12y9wxU-fES0l:b-sfkk2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L121)):*
> ```Go
> // before buf untouched
> func realloc(b *ringBuf, before, newSize int) {
> 	newBuf := make([]raftpb.Entry, newSize)
> ```

I think you're working on this now, but we probably want a minimum len here. Maybe 16?
___
*[pkg/storage/raftentry/ring_buffer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLTOAcB9nz_iGodakQ:-LSLTOAcB9nz_iGodakR:bcf3yin) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L152)):*
> ```Go
> }
> 
> func computeExtension(b *ringBuf, lo, hi uint64) (before, after int, ok bool) {
> ```

It was pretty unclear to me that `before` and `after` weren't indexes, but were the number of elements that need to be prepended/appended. Add a comment to make that clear.
___
*[pkg/storage/raftentry/ring_buffer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLRc6D9eryzfkkdQNq:-LSLRc6D9eryzfkkdQNr:b-s2pow4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L157)):*
> ```Go
> 	}
> 	first, last := first(b).index(b), last(b).index(b)
> 	if lo > (last+1) || hi < (first-1) {
> ```

This is the case where you have a gap, right? Drop a small comment here.
___
*[pkg/storage/raftentry/ring_buffer.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLOKXh8W74kmpS7Qx2:-LSLOKXh8W74kmpS7Qx3:b7rexs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L169)):*
> ```Go
> }
> 
> // iterator is an index into a ringBuf
> ```

missing period at the end.

Actually, missing on a lot of these comments. Our style guide adheres to https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.
___
*[pkg/storage/raftentry/ring_buffer.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLPmyf3zi3PvQfdqF_:-LSLPmyf3zi3PvQfdqFa:bljctvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L170)):*
> ```Go
> 
> // iterator is an index into a ringBuf
> type iterator int
> ```

Cool idea! It might be more natural to have the type be `struct { b *ringBuf, idx int }` though, so that the methods don't also need to take the same `*ringBuf`. You'll still be able to chain methods as long as you never use a pointer receiver.

If you do make this change, double check that it doesn't cause anything to escape.
___
*[pkg/storage/raftentry/ring_buffer.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLPIeo8-BHPbFHcNlL:-LSLPIeo8-BHPbFHcNlM:bktnj5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L180)):*
> ```Go
> }
> 
> func first(b *ringBuf) iterator {
> ```

Is first inclusive or exclusive? How about last? Let's add a comment making that clear.

If it's exclusive then is it safe to call on an empty buffer?
___
*[pkg/storage/raftentry/ring_buffer.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLOxxtEs_2nbmilXGI:-LSLOxxtEs_2nbmilXGJ:b-xhmxio) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L184)):*
> ```Go
> }
> 
> // unsafe to call on empty buffer
> ```

Feel free to make this panic in this case. We'll be switching to go1.11 soon enough, which permits functions with panics to still be inlined.
___
*[pkg/storage/raftentry/ring_buffer.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLQt-337L9WcerUuUR:-LSLQt-337L9WcerUuUS:bjhnjj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L190)):*
> ```Go
> 
> // unsafe to call on empty buffer
> func (it iterator) next(b *ringBuf) (_ iterator, ok bool) {
> ```

The usual API for iterators is a `next` method and a ` [...]

2018-11-27 19:41 UTC, ajwerner reviewed
Dealt with most of your comments as well as the lint failures. I didn't change the policy or the iterator structure yet. I also have yet to add the specific ringBuf unit tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSLdXzE0sFqebjkw9mL:b-dcop9r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/ring_buffer.go, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLUYxxBb9_xos8JrBt:-LSLcyil1zcP4O3yAnvW:b-prfs8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L23)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's probably worth adding a few small unit tests for this type to make sure the resizing is working as expected.
</blockquote></details>

I made sure to hit all of the edge cases of ringBuf resizing through the public API but will add a more focused set of tests.
___
*[pkg/storage/raftentry/ring_buffer.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLSAk4312WTtY8MBR7:-LSLZQLlCAjHgAY-JHx3:bq63ggt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

So if there's a gap then we don't add anything? I was expecting that we'd replace what was already there, but maybe that's not right. What's the trade-off here?
</blockquote></details>

I commented in the commit that it might be worthwhile to overwrite rather than ignore non-overlapping entries that are after the currently cached range. While testing I added a metric for how many entries we drop before and after due to this condition and without the trimming optimization under kv5, we never dropped any due to this condition. I imagine there are probably some cases where we could pull entries into the cache to cache up another node and then miss new traffic which seems bad. It feels wrong however to overwrite the cached entries with lower index entries. I'm happy to change the policy, this just seemed like the simplest first step.
___
*[pkg/storage/raftentry/ring_buffer.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLVwxT0CSm11DpbaP8:-LSL_7zEApwYgY2_3BAr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Drop a comment like `// Ignore unchanged prefix.` here. Took me some time to figure out what it was doing.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLWRTF-f7gbdFGdyjC:-LSL_xtX3MIOTdQk8dtT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Super nit: I'd leave `firstIndex` as a `uint64` and cast after the subtraction to keep it clear that this is an operation in the Raft log index domain and not in the buffer index domain.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLXizI9kzL_1vss8sV:-LSL_zD61_e20fpXYMZu:b-896gyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do you need `id`?
</blockquote></details>

Don't
___
*[pkg/storage/raftentry/ring_buffer.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLU4DmDt1JfCVi37mp:-LSLa3wC2uBY_QSzh_fu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment looks like it was written when the function had different params.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLU9o12y9wxU-fES0k:-LSLa4X5BhLlTMuXI1B7:b33vmhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think you're working on this now, but we probably want a minimum len here. Maybe 16?
</blockquote></details>

This is already done in reallocSize
___
*[pkg/storage/raftentry/ring_buffer.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLOKXh8W74kmpS7Qx2:-LSLblBA5Lul9RQ0EX15:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L169)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

missing period at the end.

Actually, missing on a lot of these comments. Our style guide adheres to https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLPmyf3zi3PvQfdqF_:-LSLblnm094oUpeCQOhp:b4wbmw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Cool idea! It might be more natural to have the type be `struct { b *ringBuf, idx int }` though, so that the methods don't also need to take the same `*ringBuf`. You'll still be able to chain methods as long as you never use a pointer receiver.

If you do make this change, double check that it doesn't cause anything to escape.
</blockquote></details>

I don't feel strongly here. I can make the change if you want. 
___
*[pkg/storage/raftentry/ring_buffer.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLPIeo8-BHPbFHcNlL:-LSLaMbB-13VBPE_ie9i:biqy7ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L180)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is first inclusive or exclusive? How about last? Let's add a comment making that clear.

If it's exclusive then is it safe to call on an empty buffer?
</blockquote></details>

Added a comment. It is inclusive. It's always safe to call but will create an invalid iterator if b.len is 0.
___
*[pkg/storage/raftentry/ring_buffer.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLOxxtEs_2nbmilXGI:-LSLaaG01N-ctbyS2IFY:b-ocbf0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L184)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Feel free to make this panic in this case. We'll be switching to go1.11 soon enough, which permits functions with panics to still be inlined.
</blockquote></details>

It already will panic with a division by zero


<!-- Sent from Reviewable.io -->

2018-11-27 19:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/ring_buffer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLTOAcB9nz_iGodakQ:-LSLgoT6AK_Y_Dh_bFUL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It was pretty unclear to me that `before` and `after` weren't indexes, but were the number of elements that need to be prepended/appended. Add a comment to make that clear.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLRc6D9eryzfkkdQNq:-LSLgovH7YE9PBDVC_Ey:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is the case where you have a gap, right? Drop a small comment here.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLQt-337L9WcerUuUR:-LSLgwRfA6V7c9drccmi:b-ivhnsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L190)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The usual API for iterators is a `next` method and a `valid` method. This would be possible if `iterator` was more than just an index. You might consider this as an alternative to the "unsafe to call on empty buffer" comments and the return value here.
</blockquote></details>

We can revisit on the next pass if you still want the change.


<!-- Sent from Reviewable.io -->

2018-11-28 00:20 UTC, nvb reviewed
This is looking really good!

> Reviewed 1 of 11 files at r1, 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSMftusBt93azQ0sc74:b-i2sit7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMO-TH6rQMWPDttujH:-LSMO-TH6rQMWPDttujI:bbxg8jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/replica.go#L67)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	"github.com/cockroachdb/cockroach/pkg/util/uuid"
> 	"github.com/google/btree"
> ```

What happened here?
___
*[pkg/storage/raftentry/cache.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMaX3w9zquHQrAgKYx:-LSMaX3w9zquHQrAgKYy:bakkmsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L46)):*
> must be acquired while holding Cache.mu

If we do this then we're back to a single global lock for the entire `Cache` whenever we have contention on this mutex. I'm not convinced we need this condition if we still only allow a single concurrent writer per Replica.
___
*[pkg/storage/raftentry/cache.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYray-sc42tvlCPEr:-LSMYray-sc42tvlCPEs:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L53)):*
> ```Go
> 
> // rangeCache represents the interface that the partition uses.
> // It is never explicitly used but a new implementation to replace ringBuf must
> ```

:thumbsup: 
___
*[pkg/storage/raftentry/cache.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMa7xi9C7ryEMIYlO3:-LSMa7xi9C7ryEMIYlO4:b-800bgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L96)):*
> ```Go
> 	c.evictLocked(bytesGuessed)
> 	// get p again in case we just evicted everything
> 	p := c.getPartLocked(id, true /* create */, false /* recordUse */)
> ```

We can wrap this in a `if len(c.parts) == 0 {` condition, right? Should be faster and easier to understand.
___
*[pkg/storage/raftentry/cache.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMbY3F-nKiq7zVNVGY:-LSMbY3F-nKiq7zVNVGZ:b9avrg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L141)):*
> ```Go
> 		c.metrics.Hits.Inc(1)
> 	}
> 	return
> ```

We almost never like naked returns in the codebase. There were a few cases in the ring buffer that were passable, but this one seems worse because we're setting the values in a nested scope. I'd strongly lean towards avoiding them, especially in a package's external facing API.
___
*[pkg/storage/raftentry/cache.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSM_symCUY_HqB8BlBq:-LSM_symCUY_HqB8BlBr:beq58wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L175)):*
> ```Go
> func (c *Cache) getPartLocked(id roachpb.RangeID, create, recordUse bool) *partition {
> 	part := c.parts[id]
> 	if create {
> ```

`if create && part == nil {`
___
*[pkg/storage/raftentry/cache.go, line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSM_kZA6zf1nwuYiWvn:-LSM_kZBCUUz7h2we7nn:b-l2kkf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L177)):*
> ```Go
> 	if create {
> 		if part == nil {
> 			newPart := &partition{id: id}
> ```

`part = &partition{id: id}`?
___
*[pkg/storage/raftentry/cache.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMcLLz8lFpgEEtFa0Y:-LSMcLLz8lFpgEEtFa0Z:b-re8cc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L207)):*
> ```Go
> 	p *partition, orig cacheSize, bytesAdded, bytesGuessed, entriesAdded int32,
> ) {
> 	// the only way that the stats here could change is if we were evicted so
> ```

`s/the/The/`
___
*[pkg/storage/raftentry/cache.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdaS_75XXRZh-gzBC:-LSMdaS_75XXRZh-gzBD:b-ezp5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L212)):*
> ```Go
> 	delta := bytesAdded - bytesGuessed
> 	new := orig.add(delta, entriesAdded)
> 	if p.setSize(orig, new) {
> ```

nit: `notEvicted := p.setSize(orig, new)` so this is explicit. Might even be worth asserting that the parition is evicted if this check fails to guard against concurrent updates.

As is, will this work with concurrent updates?
___
*[pkg/storage/raftentry/cache.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdjSNASC2mMChglri:-LSMdjSNASC2mMChglrj:bq7qjzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L231)):*
> ```Go
> 
> func (p *partition) evict() (bytes, entries int32) {
> 	const evicted = 0
> ```

What happens if `orig` is `0` for an update attempt and then the partition gets evicted? Do we need an out-of-band value here to indicate that the partition is evicted? `1` would work because a partition can't be 1 byte with 0 entries.
___
*[pkg/storage/raftentry/cache.go, line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMZRDm9RSum8oKxJZD:-LSMZRDm9RSum8oKxJZE:bjpf0yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L247)):*
> ```Go
> }
> 
> // analyzeEntries calculates the size in bytes of ents as well and ensures that
> ```

`s/as well//`
___
*[pkg/storage/raftentry/cache_test.go, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYHCW0CagC2sXkXDv:-LSMYHCW0CagC2sXkXDw:bbkn79j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache_test.go#L260)):*
> ```Go
> }
> 
> func BenchmarkEntryCache(b *testing.B) {
> ```

Why the increase in allocation size in this benchmark? Resizing of the ring buffer?
___
*[pkg/storage/raftentry/ring_buffer.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLSAk4312WTtY8MBR7:-LSMQonzAj9ZQ-Nyl2QV:bvhqxga) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I commented in the commit that it might be worthwhile to overwrite rather than ignore non-overlapping entries that are after the currently cached range. While testing I added a metric for how many entries we drop before and after due to this condition and without the trimming optimization under kv5, we never dropped any due to this condition. I imagine there are probably some cases where we could pull entries into the cache to cache up another node and then miss new traffic which seems bad. It feels wrong however to overwrite the cached entries with lower index entries. I'm happy to change the policy, this just seemed like the simplest first step.
</blockquote></details>

I think I'd prefer the possibility of thrashing vs. the possibility of the cache getting stuck and never retaining anything. Those are the two failure modes that fall out of this decision, right?
___
*[pkg/storage/raftentry/ring_buffer.go, line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLTOAcB9nz_iGodakQ:-LSMOQIQ3o0JNP5bZf5r:bdu5b1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676 [...]

2018-11-28 16:12 UTC, petermattis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSQ1_i67W2l6EC9Neco:-LSQ1_i67W2l6EC9Necp:bjagxlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L40)):*
> ```Go
> 
> 	mu    syncutil.Mutex
> 	lru   list.List
> ```

In the past, we've inlined the implementation of the circularly linked list for these performance sensitive data structures. Doing so avoids an allocation for `list.Element`. See `util/cache.Entry` for an example of doing so.
___
*[pkg/storage/raftentry/cache.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMaX3w9zquHQrAgKYx:-LSQ3Pga1CdB3A3AwCEs:b3eq3j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> must be acquired while holding Cache.mu

If we do this then we're back to a single global lock for the entire `Cache` whenever we have contention on this mutex. I'm not convinced we need this condition if we still only allow a single concurrent writer per Replica.
</blockquote></details>

I agree with @nvanbenschoten regarding locking. Something else to take a look at is the [`commitQueue`](https://github.com/petermattis/pebble/blob/master/commit.go#L25 ) in pebble which is a lock-free single-producer multiple-consumer queue. I don't quite see how that could be adapted to `ringBuf` as resizing the slice in a lock-free manner seems difficult. Pointing it out in case one of you sees a possibility. 


<!-- Sent from Reviewable.io -->

2018-11-28 17:59 UTC, ajwerner reviewed
Addressed most of the feedback and expanded the testing. Just two minor things left to do:

1) inlining the linked list for the LRU
2) giving empty partitions some space in the cache bookkeeping to avoid piling up empty partitions

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSQT6Cy98mvXZHgfyDd:b-lgsy5g)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMO-TH6rQMWPDttujH:-LSNC4zZ4bshvn3KeY_g:b-d1347v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/replica.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

Sorry was mucking around with goimports, must have killed a space and then had them sorted. What's our usual style?

```
import (
   <stdlib>

   <3rdparty>
   
   <first party>
)
```
?
___
*[pkg/storage/raftentry/cache.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSQ1_i67W2l6EC9Neco:-LSQSvC03Jf7Kh5NAbzu:by78yya) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L40)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In the past, we've inlined the implementation of the circularly linked list for these performance sensitive data structures. Doing so avoids an allocation for `list.Element`. See `util/cache.Entry` for an example of doing so.
</blockquote></details>

Can do. 
___
*[pkg/storage/raftentry/cache.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMaX3w9zquHQrAgKYx:-LSNCSEq0Qb7kftP3pK1:b-kkxsm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> must be acquired while holding Cache.mu

If we do this then we're back to a single global lock for the entire `Cache` whenever we have contention on this mutex. I'm not convinced we need this condition if we still only allow a single concurrent writer per Replica.
</blockquote></details>

Yes, fair point. It seems we still need some locking on the partition because it seems that reads and writes occur concurrently. Addressed by moving the locking of the partition out from the cache lock and adding a comment that concurrent writes are not allowed
___
*[pkg/storage/raftentry/cache.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYray-sc42tvlCPEr:-LSNCmDy4IxnHbIP-vn-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMa7xi9C7ryEMIYlO3:-LSNCyrS6Zo205lJUERI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can wrap this in a `if len(c.parts) == 0 {` condition, right? Should be faster and easier to understand.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMbY3F-nKiq7zVNVGY:-LSNDoOI8HPc-09MocXG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L141)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We almost never like naked returns in the codebase. There were a few cases in the ring buffer that were passable, but this one seems worse because we're setting the values in a nested scope. I'd strongly lean towards avoiding them, especially in a package's external facing API.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSM_symCUY_HqB8BlBq:-LSNE2wR25Rfc5d1zI00:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L175)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`if create && part == nil {`
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSM_kZA6zf1nwuYiWvn:-LSNE2VKBMpqSu7lUycU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`part = &partition{id: id}`?
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMcLLz8lFpgEEtFa0Y:-LSNE5QeCNxd6ZDhADGH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L207)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/the/The/`
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdaS_75XXRZh-gzBC:-LSNE9Yj4ZsDztnZ4iyJ:b-5pg0z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `notEvicted := p.setSize(orig, new)` so this is explicit. Might even be worth asserting that the parition is evicted if this check fails to guard against concurrent updates.

As is, will this work with concurrent updates?
</blockquote></details>

I did the nit. Can you help me understand the concern about concurrent updates. Also renamed the variables to not shadow the `new` keyword.
___
*[pkg/storage/raftentry/cache.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdjSNASC2mMChglri:-LSNEi3f6y9VAl4gFJt2:b23jct5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What happens if `orig` is `0` for an update attempt and then the partition gets evicted? Do we need an out-of-band value here to indicate that the partition is evicted? `1` would work because a partition can't be 1 byte with 0 entries.
</blockquote></details>

I think this case is dealt with already because we add the "guessedBytes" to orig for an add under Cache.mu and evict here is always called under Cache.mu. If orig here is 0, then either no other goroutine is accessing this replica or if a goroutine is currently clearing the replica, it has already atomically taken its space (in recordUpdate) and will update the Cache bookkeeping when it gets the lock.  It is impossible for a routine to enter recordUpdate with positive numbers to add with an orig value of 0. This does however highlight a bug in evictLocked whereby we may have evicted all of the partitions and still exceed the cache because the goroutine which will soon free the cache bytes needs the lock to do so. I fixed this by bailing out of the cache loop once all partitions have been evicted [...]

2018-11-28 19:15 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMO-TH6rQMWPDttujH:-LSQjjbd-WX7pzRoHV0f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/replica.go#L67)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Sorry was mucking around with goimports, must have killed a space and then had them sorted. What's our usual style?

```
import (
   <stdlib>

   <3rdparty>
   
   <first party>
)
```
?

</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSQ1_i67W2l6EC9Neco:-LSQjqRz1WP3m8AE50rl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L40)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can do. 
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 46 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMaX3w9zquHQrAgKYx:-LSQTWVx6li-MyfgeERb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, fair point. It seems we still need some locking on the partition because it seems that reads and writes occur concurrently. Addressed by moving the locking of the partition out from the cache lock and adding a comment that concurrent writes are not allowed
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/ring_buffer.go, line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLPmyf3zi3PvQfdqF_:-LSQTZIzCw9sGZpqGrPu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If not then I'm fine with leaving it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-28 19:54 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/ring_buffer.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLSAk4312WTtY8MBR7:-LSQskZM5OlPGwJRwISE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes, that sounds right to me. I changed to logic to detect adds after the current range and clear the cache. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-29 01:50 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once the final batch of comments is resolved. Really nice job on this! I suspect we could actually find workloads where the effect of this is even more dramatic.

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSS8YSk8yiLRBwppMRC:bbc0yok)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 212 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdaS_75XXRZh-gzBC:-LSS-pM1DSbU3sYcZh-c:b-gmkqym) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L212)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did the nit. Can you help me understand the concern about concurrent updates. Also renamed the variables to not shadow the `new` keyword.
</blockquote></details>

The concern with concurrent updates is that the CAS operation might fail even if the partition wasn't evicted, simply because the second update already modified the partition before grabbing the partition lock. We don't allow concurrent updates though, so this is a non-issue.
___
*[pkg/storage/raftentry/cache.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdjSNASC2mMChglri:-LSS0Mh06ciA57S9jj2y:b-a6wvbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this case is dealt with already because we add the "guessedBytes" to orig for an add under Cache.mu and evict here is always called under Cache.mu. If orig here is 0, then either no other goroutine is accessing this replica or if a goroutine is currently clearing the replica, it has already atomically taken its space (in recordUpdate) and will update the Cache bookkeeping when it gets the lock.  It is impossible for a routine to enter recordUpdate with positive numbers to add with an orig value of 0. This does however highlight a bug in evictLocked whereby we may have evicted all of the partitions and still exceed the cache because the goroutine which will soon free the cache bytes needs the lock to do so. I fixed this by bailing out of the cache loop once all partitions have been evicted. 

In summary, it seems like the check for `cs != evicted`, while probably fine, is causing confusion and so I've removed it.
</blockquote></details>

Ah, I see. Yeah, this is now easier to understand.

Might be worth adding somewhere that this is all easy to reason about because once we move to the `evicted` state, we can never have a transition away from that state.
___
*[pkg/storage/raftentry/cache.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzI-1DK9_769cD5tj:-LSRzI-1DK9_769cD5tk:b-1dgtoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L52)):*
> ```Go
> //
> // Cache is designed to be a shared store-wide object which incurs low
> // contention for operations on different ranges. This is achieved through the
> ```

Might want to end this sentence with "while maintaining a global memory policy".
___
*[pkg/storage/raftentry/cache.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzCJv-g2pISAibCZF:-LSRzCJv-g2pISAibCZG:bc477e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L53)):*
> ```Go
> // Cache is designed to be a shared store-wide object which incurs low
> // contention for operations on different ranges. This is achieved through the
> // use ofa two-level locking scheme. Cache.mu is acquired to access any data in
> ```

"of a"
___
*[pkg/storage/raftentry/cache.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzj7J7YaufgbQan0z:-LSRzj7J7YaufgbQan1-:btutr4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L66)):*
> ```
> date
> ```
state?
___
*[pkg/storage/raftentry/cache.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzyHlAKmbVJA03zwO:-LSRzyHlAKmbVJA03zwP:bj629sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L74)):*
> ```
> mediated the
> ```

mediated through the
___
*[pkg/storage/raftentry/cache_test.go, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYHCW0CagC2sXkXDv:-LSS3NSU1tw8Ig4rOR5J:b-kfsjn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache_test.go#L260)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

honestly this is straight copied from your diff and from the previous incarnation of the test 

https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/entry_cache_test.go#L146
https://github.com/cockroachdb/cockroach/blob/6c212b70f4fa9e8919ecfe8b971422cbf81a2364/pkg/storage/raftentry/cache_test.go#L178

so you tell me?
</blockquote></details>

You're right that that attempt also had a similar effect. That adds weight to the suspicion that this is a result of overestimation in partition sizing (i.e. vector resizing in this change and map resizing in the previous one).

Might be worth dropping this benchmark into a memory profile just to verify that everything lines up and matches expectations, but don't let that hold up the change.
___
*[pkg/storage/raftentry/cache_test.go, line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS364X68itgDJ3LYwi:-LSS364X68itgDJ3LYwj:bisskrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache_test.go#L307)):*
> ```
> c.Metrics().Bytes.Value()
> ```

Can we compute what this should be by peeking at the number of partitions left in the cache? That will allow us to test the byte count handling as well.
___
*[pkg/storage/raftentry/ring_buffer.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSLSAk4312WTtY8MBR7:-LSS4xhc2SB3SrRoK7fZ:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac676ca63a1b213436c4417a8bee3f85fd0758f8/pkg/storage/raftentry/ring_buffer.go#L41)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
___
*[pkg/storage/raftentry/ring_buffer.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS7vZe2-3Vszl9nD5A:-LSS7vZe2-3Vszl9nD5B:bl1afmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/ring_buffer.go#L135)):*
> ```Go
> // reallocLen returns a new length which is greater than neededSize and is
> // a power-of-two multiple of minBufSize.
> func reallocLen(curSize, neededSize int) (newLen int) {
> ```

This seems overly complex. Do we even need `curSize`? Will something like this do?
```
func reallocLen(need int) int {
	if need <= minBufSize {
		return minBufSize
	}
	f := bits.UintSize - bits.LeadingZeros(uint(need))
	return 1 << uint(f)
}
```


<!-- Sent from Reviewable.io -->

2018-11-29 03:50 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 231 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMdjSNASC2mMChglri:-LSSRHEWCVe6IFkd6Sde:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache.go#L231)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ah, I see. Yeah, this is now easier to understand.

Might be worth adding somewhere that this is all easy to reason about because once we move to the `evicted` state, we can never have a transition away from that state.
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzI-1DK9_769cD5tj:-LSSVT71EEktr3lBc7MN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L52)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Might want to end this sentence with "while maintaining a global memory policy".
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzCJv-g2pISAibCZF:-LSSVTZs3CKcWQFMSFN4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"of a"
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzj7J7YaufgbQan0z:-LSSVZsm4ghHR2cfXj7d:bfftd2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> date
> ```
state?
</blockquote></details>

cache state, fixed
___
*[pkg/storage/raftentry/cache.go, line 74 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzyHlAKmbVJA03zwO:-LSSWBmG7Tk0Mhqe--fG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> mediated the
> ```

mediated through the
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache_test.go, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYHCW0CagC2sXkXDv:-LSSYT6OAY9a37eYbHSz:bdiutoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache_test.go#L260)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You're right that that attempt also had a similar effect. That adds weight to the suspicion that this is a result of overestimation in partition sizing (i.e. vector resizing in this change and map resizing in the previous one).

Might be worth dropping this benchmark into a memory profile just to verify that everything lines up and matches expectations, but don't let that hold up the change.
</blockquote></details>

honestly looking at the cache size in the ClearTo benchmark reveals a problem which is that the cache size was smaller than required to store the data so the entries were being ignored completely. I've updated the micro benchmarks. 
___
*[pkg/storage/raftentry/cache_test.go, line 307 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS364X68itgDJ3LYwi:-LSSXFnPALLNMUSDhfuA:b-sfidww) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache_test.go#L307)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> c.Metrics().Bytes.Value()
> ```

Can we compute what this should be by peeking at the number of partitions left in the cache? That will allow us to test the byte count handling as well.
</blockquote></details>

sure, done
___
*[pkg/storage/raftentry/ring_buffer.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS7vZe2-3Vszl9nD5A:-LSSYkQGA1RtB16E3lyh:bseuw2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/ring_buffer.go#L135)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This seems overly complex. Do we even need `curSize`? Will something like this do?
```
func reallocLen(need int) int {
	if need <= minBufSize {
		return minBufSize
	}
	f := bits.UintSize - bits.LeadingZeros(uint(need))
	return 1 << uint(f)
}
```
</blockquote></details>

Much cleaner!


<!-- Sent from Reviewable.io -->

2018-11-29 04:47 UTC, ajwerner reviewed
I've updated the commit message with new stats. For KV90 on n1-standard-32's I find a pretty big win:

```
    $ ./workload run kv '{pgurl:1-3}' --init --splits=512 --duration 180s --read-percent=90 --concurrency=512
```
```
    name       old ops/s  new ops/s  delta
    KV90       100k ± 0%  108k ± 1%  +8.05%  (p=0.004 n=6+5)
    KV90       100k ± 0%  107k ± 2%  +6.81%  (p=0.002 n=6+6)
    kV90       101k ± 1%  107k ± 0%  +6.25%  (p=0.010 n=6+4)
```

Also update the micro benchmarks after resolving that ClearTo bug and cleaned up some comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSShIX81w0wn3xcKF3S:b-vloupz)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/ring_buffer.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS7vZe2-3Vszl9nD5A:-LSSmhrmD--vot1UDv36:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/ring_buffer.go#L135)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Much cleaner!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-29 06:09 UTC, nvb requested changes
Still <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LST2lYY5Gwb5frcy6QL:b-2pygyf)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSRzCJv-g2pISAibCZF:-LST2xHCDhE51O2lpHsb:bryygr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/cache.go#L53)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now it's "o fa"
___
*[pkg/storage/raftentry/cache.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LST32UO7RgMT5XGGaIN:-LST32UO7RgMT5XGGaIO:b-7d2wmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd01c869d69bf84ce1dbb1a0fb8a6ddc6bba76/pkg/storage/raftentry/cache.go#L58)):*
> add to the  cache

Double space recently added here between "the" and "cache".
___
*[pkg/storage/raftentry/cache_test.go, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYHCW0CagC2sXkXDv:-LST3Fa60nrTPZ6gUGpg:b-nkuorz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache_test.go#L260)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

honestly looking at the cache size in the ClearTo benchmark reveals a problem which is that the cache size was smaller than required to store the data so the entries were being ignored completely. I've updated the micro benchmarks. 
</blockquote></details>

Well that explains it. Glad you tracked it down.
___
*[pkg/storage/raftentry/ring_buffer.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSS7vZe2-3Vszl9nD5A:-LST3MCC1VB8G7wpmTsz:b-s7fet4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d291b6e6251ef6fe9f39508c3e9b2e3e5099728f/pkg/storage/raftentry/ring_buffer.go#L135)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Out of curiosity, I took a look to see whether this `bits` function was implemented with a single instruction. It's not, but in checking I realized that the snippet is a bit redundant. The definition of `LeadingZeros` is:

```
func LeadingZeros(x uint) int { return UintSize - Len(x) }
```

So we can make this:

```
func reallocLen(need int) int {
	if need <= minBufSize {
		return minBufSize
	}
	return 1 << uint(bits.Len(uint(need)))
}
```


<!-- Sent from Reviewable.io -->

2018-11-29 06:09 UTC, nvb approved these changes

2018-11-29 13:44 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raftentry/cache.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LST32UO7RgMT5XGGaIN:-LSUguai-WqoKlgiU9q1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13cd01c869d69bf84ce1dbb1a0fb8a6ddc6bba76/pkg/storage/raftentry/cache.go#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> add to the  cache

Double space recently added here between "the" and "cache".
</blockquote></details>

Done.
___
*[pkg/storage/raftentry/cache_test.go, line 260 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSMYHCW0CagC2sXkXDv:-LSUgyOp7z_hzBmAoj4x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d307dd777e939b88f78c2e2c82b2977c23c75a/pkg/storage/raftentry/cache_test.go#L260)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Well that explains it. Glad you tracked it down.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-11-29 15:57 UTC, ajwerner commented
bors r+

2018-11-29 16:15 UTC, merged

2018-11-30 12:04 UTC, tbg reviewed
Very nice!

> Dismissed @nvanbenschoten from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-:-LSZVRPJ2vCR3AEqN0MN:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/raftentry/cache.go, line 288 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32618#-LSZUBwC3q6NF_LGeEsg:-LSZUBwC3q6NF_LGeEsh:b-qbptpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5ca4dc06d94695d2e2de7fe0221ff8e751e71a/pkg/storage/raftentry/cache.go#L288)):*
> ```Go
> 	const evicted = 0
> 	// a partition size is never equal to evicted while a partition exists and
> 	// Cache.mu is not held because a partition caries the byte size of its struct
> ```

carries


<!-- Sent from Reviewable.io -->

2018-11-30 12:05 UTC, tbg reviewed
> Reviewed 5 of 11 files at r1, 1 of 5 files at r2, 2 of 7 files at r3, 2 of 5 files at r4, 1 of 3 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32618)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->