[wip] cli: absorb github.com/knz/go-libedit
cockroachdb/cockroach pull request #32623
Opened 2018-11-27 05:33 UTC by benesch

There is more work to do here to appease the linter, but wanted to get this proof-of-concept out. @knz what copyright header would you like me to put on the files in cli/editline? 

---

Absorb our line-editing library, github.com/knz/go-libedit. The C
library, libedit, is extracted into a c-deps submodule, where its build
can be properly orchestrated by our Makefile to use the upstream
autotools build system. The Go code is extracted into pkg/cli/editline,
where it can more easily be modified to meet our needs.

Fix #31843.

Release note: None

2018-11-27 05:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32623)
<!-- Reviewable:end -->

2018-11-27 05:41 UTC, knz commented
1) You're defining a fork since the implementation is (slightly) different.

2) I'm sorry but you can't just add copyright headers using the APL license terms and call it a day.  the proper course of action is:

- for the sources that are specific to go-libedit:
  - add a header that mentions the proper license terms (go-libedit's BSD terms; you can take inspiration from the c libedit files)
  - mention the original copyright at the top of the license terms
  - add the cockroachdb copyright on top of those specific files you're modifying
  - change the linter to accept all that

- for the sources imported from libedit:
  - leave the headers that are there as-is

- mention these licenses in the top level `licenses/` directory

2018-11-27 15:35 UTC, benesch commented
Ok, I think this is ready to go. @knz I added your copyright header to all of the files that originated from github.com/knz/go-libedit. I'm not seeing why the NetBSD copyright would be relevant to any of them; they're all your original work, save for a function or two that I contributed.

The copyright on libedit itself, of course, very much belongs to NetBSD and Christos Zoulas. We don't need to worry about that, though, since it's isolated in its own Git submodule with appropriate license files and headers.

2018-11-27 15:38 UTC, knz requested changes
You can't just add "portions of this file are with a different license"

This is not how licenses work.

The original code was released with a specific license. That license grants you right that you would otherwise not have since you are not copyright holder.

The license grants you the following rights:
- make copies and redistribution of the files
- make changes to the file, holding the copyright and license info intact
- claim copyright to portions of the files

Here is a right that the license **does not** grant you:
- issue a new license for the files

Licenses do not apply for  a "portion" of the file. Licenses apply on entire files.

Also, you may not issue a license for code for which you are not the sole copyright owner, without agreement from every other copyright holder.


If you want to have a mixed-license source tree you must be very careful to:

- separate code with different copyright holders into **different files**, with clear copyright attributions
- license the files that *you* have **sole** copyright over using a a separate license, if you wish to do so
- identify clearly (usually, by using separate directories) which files are released with which license.

2018-11-27 15:40 UTC, knz commented
So in terms of changes:

- if you wish to edit files from go-libedit, you can do so and add the cockroach name, but not change the licensing terms (and not "portions of this file with separate license" - that doesn not work)

- if you insist on using APL for your changes, make these changes on different files and use `#include` / `#ifdef` to make them work the way you want

2018-11-27 15:49 UTC, benesch commented
We do the "portions of this file" thing elsewhere, so if that is indeed wrong there is a lot to clean up: https://github.com/cockroachdb/cockroach/blob/e2deae4961ad007f8f26b4e08b04c11fddf06348/pkg/internal/rsg/yacc/lex.go#L1-L22

> Here is a right that the license does not grant you:
>
> issue a new license for the files

Why not? The derivative work is subject to the terms of both licenses: your original BSD license as well as the Apache license. 

> Licenses do not apply for a "portion" of the file. Licenses apply on entire files.

Source? I think this is just a convention.

I don't have a problem with releasing my changes in this directory under the terms of your BSD license, but I think doing so requires @bdarnell's permission.

2018-11-27 15:52 UTC, knz commented
This discussion is above my paygrade but all my experience until now has been that open source software avoid separate licensing terms for separate portions of files. 

This is because it makes tracking attribution and licensing of individual lines/words inside the file properly impossible.

I do indeed think that we have a serious problem on our hands if that has been done in other places. I'd like to see some serious precedent outside of CockroachDB before I different an different.

2018-11-27 22:45 UTC, knz commented
this was discussed with @bdarnell. please issue first a PR against go-libedit to re-license with APL; we'll merge that, then you can pick it up from there.

2018-12-07 20:16 UTC, knz commented
@benesch while we iterate on the first commit can you put the 2nd commit in a separate PR so we can merge that and solve the linking error in the next release. thanks

2018-12-09 14:48 UTC, knz commented
@benesch fyi I am rebasing your branch on top of the new `master` to bring it down to 1 commit.

2018-12-09 14:57 UTC, knz commented
As I am iterating on this I notice that this patch links against the embedded libedit unconditionally.

This does not seem desirable as NetBSD's version, at least, and FreeBSD's (soon) are adequate already.

2018-12-09 15:14 UTC, knz commented
@benesch is it possible to rebase the code at https://github.com/cockroachdb/libedit on top of the newest netbsd code instead of the severely outdated code from May? This would also automagically integrate your patch from upstream.

2018-12-09 15:49 UTC, knz commented
On a different note I also see that the signal handling on Darwin/macOS has been fixed/cleaned up in go 1.11, so the ugly hack in libedit is not any more needed -- as a matter of fact, it may even have become incorrect.

I am enclined to remove it, but that would bump our dependency to go 1.11.

2018-12-09 15:57 UTC, knz commented
Here is my preliminary plan:

1. in go-libedit require the user to run `make` at least once before they can use it in go programs
2. the makefile will:
   1. test the go version and activate the use of the `unix/sigtramp` sub-module based on the detected version 
   2. when using the embedded libedit, recursively configure and build that so there's an archive around
   3. generate cgo cppflags/ldflags according to parameters
3. either apply nikhil's patch to the libedit embeddded in go-libedit, or change go-libedit to use cockroachdb/libedit
4. rebase this PR to use the updated go-libedit
5. adjust the makefile accordingly

For the 2nd step I will need a macOS machine to test the result, so this pushes the resolution one more week forward (when I get home). However in the meantime  #32959 and backport will have made the life of users simpler.

2019-06-19 01:32 UTC, jordanlewis commented
@knz is this dead? :( Do you remember the last status of the bugfix that @benesch pushed into bsd land? When can we get that bugfix inside of CockroachDB?

2019-06-19 03:38 UTC, benesch commented
👋 hey Jordan! So the status is kind of complicated.

Libedit has two upstreams: NetBSD and FreeBSD. The two BSDs occasionally incorporate one another's patches, but it seems to only happen when someone involved with the projects notices or cares, not on any regular schedule. FreeBSD hasn't incorporated the fix from NetBSD yet, so FreeBSD users are stuck with a broken libedit.

NetBSD is arguably the more authoritative upstream, because the autotools port maintained by Jess Thrysoee (https://thrysoee.dk/editline/) is based upon it. Jess has cut two releases with the patch, so the patched version will slowly make its way through the Linux ecosystem. It might also eventually make it into macOS, though it's not clear to me that anyone at Apple is incorporating upstream libedit fixes into Darwin's libedit these days.

Anyway, all that to say that it'll be years before the patch actually makes it across all the platforms we care about.

So, if we want the patch in CockroachDB, we need go-libedit to unconditionally build a patched libedit on all platforms—right now it tries to use the system libedit where possible (i.e., everywhere but Linux) to avoid building and linking a standalone libedit unnecessarily. It's easy enough to do this if we absorb the go-libedit entirely, which is the approach this PR took, because we can simply hardcode the rule "build libedit and statically link it."  The downside, of course, is that we essentially end up with a fork of Raphael's library, and will struggle to maintain parity between the two.

Raphael's counterproposal was to introduce configurability into the go-libedit build process, so that CockroachDB could ask for a patched libedit to be built, without breaking `go build` inside go-libedit for other folks. That's a decent bit more work and testing though, a plan for which Raphael laid out in his last comment. I don't think that there have been any roadblocks with this approach; just no one's had the time to push this approach across the finish line.

FWIW, the former approach (the one in this PR) is essentially ready to merge—the few conflicts here are trivial—but I'm sympathetic to Raphael's concerns about future maintainability.

2019-06-19 04:19 UTC, benesch commented
> On a different note I also see that the signal handling on Darwin/macOS has been fixed/cleaned up in go 1.11, so the ugly hack in go-libedit is not any more needed -- as a matter of fact, it may even have become incorrect.

I've submitted a PR for this! https://github.com/knz/go-libedit/pull/16

2019-06-19 05:03 UTC, benesch commented
I nerdsniped myself into composing a patch for Raphael's approach. This is mostly ready:

```diff
diff --git a/.gitmodules b/.gitmodules
index 3e7d61ad19..dc4ffeb3b3 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -26,3 +26,6 @@
 [submodule "c-deps/krb5"]
 	path = c-deps/krb5
 	url = https://github.com/cockroachdb/krb5.git
+[submodule "c-deps/libedit"]
+	path = c-deps/libedit
+	url = https://github.com/cockroachdb/libedit.git
diff --git a/Makefile b/Makefile
index 09aecd0b7b..e940dd6283 100644
--- a/Makefile
+++ b/Makefile
@@ -410,6 +410,7 @@ JEMALLOC_SRC_DIR := $(C_DEPS_DIR)/jemalloc
 PROTOBUF_SRC_DIR := $(C_DEPS_DIR)/protobuf
 ROCKSDB_SRC_DIR  := $(C_DEPS_DIR)/rocksdb
 SNAPPY_SRC_DIR   := $(C_DEPS_DIR)/snappy
+LIBEDIT_SRC_DIR  := $(C_DEPS_DIR)/libedit
 LIBROACH_SRC_DIR := $(C_DEPS_DIR)/libroach
 KRB5_SRC_DIR     := $(C_DEPS_DIR)/krb5
 
@@ -436,6 +437,7 @@ JEMALLOC_DIR := $(BUILD_DIR)/jemalloc$(if $(use-msan),_msan)
 PROTOBUF_DIR := $(BUILD_DIR)/protobuf$(if $(use-msan),_msan)
 ROCKSDB_DIR  := $(BUILD_DIR)/rocksdb$(if $(use-msan),_msan)$(if $(use-stdmalloc),_stdmalloc)$(if $(USE_ROCKSDB_ASSERTIONS),_assert)
 SNAPPY_DIR   := $(BUILD_DIR)/snappy$(if $(use-msan),_msan)
+LIBEDIT_DIR  := $(BUILD_DIR)/libedit$(if $(use-msan),_msan)
 LIBROACH_DIR := $(BUILD_DIR)/libroach$(if $(use-msan),_msan)
 KRB5_DIR     := $(BUILD_DIR)/krb5$(if $(use-msan),_msan)
 # Can't share with protobuf because protoc is always built for the host.
@@ -446,12 +448,13 @@ LIBJEMALLOC := $(JEMALLOC_DIR)/lib/libjemalloc.a
 LIBPROTOBUF := $(PROTOBUF_DIR)/libprotobuf.a
 LIBROCKSDB  := $(ROCKSDB_DIR)/librocksdb.a
 LIBSNAPPY   := $(SNAPPY_DIR)/libsnappy.a
+LIBEDIT     := $(LIBEDIT_DIR)/src/.libs/libedit.a
 LIBROACH    := $(LIBROACH_DIR)/libroach.a
 LIBROACHCCL := $(LIBROACH_DIR)/libroachccl.a
 LIBKRB5     := $(KRB5_DIR)/lib/libgssapi_krb5.a
 PROTOC 		 := $(PROTOC_DIR)/protoc
 
-C_LIBS_COMMON = $(if $(use-stdmalloc),,$(LIBJEMALLOC)) $(LIBPROTOBUF) $(LIBSNAPPY) $(LIBROCKSDB)
+C_LIBS_COMMON = $(if $(use-stdmalloc),,$(LIBJEMALLOC)) $(LIBPROTOBUF) $(LIBSNAPPY) $(LIBEDIT) $(LIBROCKSDB)
 C_LIBS_OSS = $(C_LIBS_COMMON) $(LIBROACH)
 C_LIBS_CCL = $(C_LIBS_COMMON) $(LIBCRYPTOPP) $(LIBROACHCCL)
 
@@ -484,9 +487,16 @@ native-tag := $(subst -,_,$(TARGET_TRIPLE))$(if $(use-stdmalloc),_stdmalloc)$(if
 # constraint `{native-tag}` and are built the first time a Make-driven build
 # encounters a given native tag. These tags are unset when building with the Go
 # toolchain directly, so these files are only compiled when building with Make.
-CGO_PKGS := cli server/status storage/engine ccl/storageccl/engineccl ccl/gssapiccl
-CGO_UNSUFFIXED_FLAGS_FILES := $(addprefix ./pkg/,$(addsuffix /zcgo_flags.go,$(CGO_PKGS)))
-CGO_SUFFIXED_FLAGS_FILES   := $(addprefix ./pkg/,$(addsuffix /zcgo_flags_$(native-tag).go,$(CGO_PKGS)))
+CGO_PKGS := \
+	pkg/cli \
+	pkg/server/status \
+	pkg/storage/engine \
+	pkg/ccl/storageccl/engineccl \
+	pkg/ccl/gssapiccl \
+	vendor/github.com/knz/go-libedit/unix
+vendor/github.com/knz/go-libedit/unix-package := libedit_unix
+CGO_UNSUFFIXED_FLAGS_FILES := $(addprefix ./,$(addsuffix /zcgo_flags.go,$(CGO_PKGS)))
+CGO_SUFFIXED_FLAGS_FILES   := $(addprefix ./,$(addsuffix /zcgo_flags_$(native-tag).go,$(CGO_PKGS)))
 CGO_FLAGS_FILES := $(CGO_UNSUFFIXED_FLAGS_FILES) $(CGO_SUFFIXED_FLAGS_FILES)
 
 $(CGO_UNSUFFIXED_FLAGS_FILES): build/defs.mk.sig
@@ -496,10 +506,10 @@ $(CGO_FLAGS_FILES): Makefile
 	@echo >> $@
 	@echo '// +build $(if $(findstring $(native-tag),$@),$(native-tag),!make)' >> $@
 	@echo >> $@
-	@echo 'package $(notdir $(@D))' >> $@
+	@echo 'package $(if $($(@D)-package),$($(@D)-package),$(notdir $(@D)))' >> $@
 	@echo >> $@
 	@echo '// #cgo CPPFLAGS: $(addprefix -I,$(JEMALLOC_DIR)/include $(KRB_CPPFLAGS))' >> $@
-	@echo '// #cgo LDFLAGS: $(addprefix -L,$(CRYPTOPP_DIR) $(PROTOBUF_DIR) $(JEMALLOC_DIR)/lib $(SNAPPY_DIR) $(ROCKSDB_DIR) $(LIBROACH_DIR) $(KRB_DIR))' >> $@
+	@echo '// #cgo LDFLAGS: $(addprefix -L,$(CRYPTOPP_DIR) $(PROTOBUF_DIR) $(JEMALLOC_DIR)/lib $(SNAPPY_DIR) $(LIBEDIT_DIR)/src/.libs $(ROCKSDB_DIR) $(LIBROACH_DIR) $(KRB_DIR))' >> $@
 	@echo 'import "C"' >> $@
 
 # BUILD ARTIFACT CACHING
@@ -602,6 +612,18 @@ $(SNAPPY_DIR)/Makefile: $(C_DEPS_DIR)/snappy-rebuild | bin/.submodules-initializ
 	cd $(SNAPPY_DIR) && cmake $(xcmake-flags) $(SNAPPY_SRC_DIR) \
 	  -DCMAKE_BUILD_TYPE=Release
 
+$(LIBEDIT_SRC_DIR)/configure.ac: | bin/.submodules-initialized
+
+$(LIBEDIT_SRC_DIR)/configure: $(LIBEDIT_SRC_DIR)/configure.ac
+	cd $(LIBEDIT_SRC_DIR) && autoconf
+
+$(LIBEDIT_DIR)/Makefile: $(C_DEPS_DIR)/libedit-rebuild $(LIBEDIT_SRC_DIR)/configure
+	rm -rf $(LIBEDIT_DIR)
+	mkdir -p $(LIBEDIT_DIR)
+	@# NOTE: If you change the configure flags below, bump the version in
+	@# $(C_DEPS_DIR)/libedit-rebuild. See above for rationale.
+	cd $(LIBEDIT_DIR) && $(LIBEDIT_SRC_DIR)/configure $(xconfigure-flags) --disable-examples --disable-shared
+
 # TODO(benesch): make it possible to build libroach without CCL code. Because
 # libroach and libroachccl are defined in the same CMake project, CMake requires
 # that the CCL code be present even if only the OSS target will be built.
@@ -660,6 +682,9 @@ $(LIBPROTOBUF): $(PROTOBUF_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD
 $(LIBSNAPPY): $(SNAPPY_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD
 	@uptodate $@ $(SNAPPY_SRC_DIR) || $(MAKE) --no-print-directory -C $(SNAPPY_DIR) snappy
 
+$(LIBEDIT): $(LIBEDIT_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD
+	@uptodate $@ $(LIBEDIT_SRC_DIR) || $(MAKE) --no-print-directory -C $(LIBEDIT_DIR)/src
+
 $(LIBROCKSDB): $(ROCKSDB_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD
 	@uptodate $@ $(ROCKSDB_SRC_DIR) || $(MAKE) --no-print-directory -C $(ROCKSDB_DIR) rocksdb
 
@@ -678,6 +703,7 @@ $(LIBKRB5): $(KRB5_DIR)/Makefile bin/uptodate .ALWAYS_REBUILD
 .PHONY: protoc libcryptopp libjemalloc libprotobuf libsnappy librocksdb libroach libroachccl libkrb5
 protoc:      $(PROTOC)
 libcryptopp: $(LIBCRYPTOPP)
+libedit:     $(LIBEDIT)
 libjemalloc: $(LIBJEMALLOC)
 libprotobuf: $(LIBPROTOBUF)
 libsnappy:   $(LIBSNAPPY)
diff --git a/build/variables.mk b/build/variables.mk
index 560fa4328a..ff3f01b880 100644
--- a/build/variables.mk
+++ b/build/variables.mk
@@ -83,6 +83,9 @@ define VALID_VARS
   LC_ALL
   LDFLAGS
   LIBCRYPTOPP
+  LIBEDIT
+  LIBEDIT_DIR
+  LIBEDIT_SRC_DIR
   LIBJEMALLOC
   LIBPROTOBUF
   LIBROACH
diff --git a/c-deps/libedit b/c-deps/libedit
new file mode 160000
index 0000000000..56d1ad6fbc
--- /dev/null
+++ b/c-deps/libedit
@@ -0,0 +1 @@
+Subproject commit 56d1ad6fbc22bba53d03491d0e2a88f66ca75466
diff --git a/c-deps/libedit-rebuild b/c-deps/libedit-rebuild
new file mode 100644
index 0000000000..a8a50e2029
--- /dev/null
+++ b/c-deps/libedit-rebuild
@@ -0,0 +1,4 @@
+Bump the version below when changing libedit configure flags. Search for "BUILD
+ARTIFACT CACHING" in build/common.mk for rationale.
+
+1
```

I just need to make a few tiny tweaks to go-libedit, which I'll try to get to soon.

2019-06-20 03:00 UTC, jordanlewis commented
Whoa - I was *not* expecting you to do all this work! You are truly the man. What is the tiny tweak or two you need to make to `go-libedit`? I wouldn't want that info to get lost to the sands of time if you don't get to it (and I certainly don't expect you to!).

2019-06-20 03:57 UTC, kenliu commented
thanks @benesch !

2019-06-21 04:30 UTC, benesch commented
> Whoa - I was not expecting you to do all this work! You are truly the man.

The idea of closing out my last outstanding CockroachDB PR is quite motivating :D.

> What is the tiny tweak or two you need to make to go-libedit? I wouldn't want that info to get lost to the sands of time if you don't get to it (and I certainly don't expect you to!).

Not to worry! I submitted the PR here: https://github.com/knz/go-libedit/pull/17.

Steps to get this merged:

  1. [ ] Land knz/go-libedit#16.
  2. [ ] Land knz/go-libedit#17.
  3. [ ] Bump the knz/go-libedit dependency in Cockroach.
  4. [ ] Merge https://github.com/benesch/libedit/tree/crl-release-20190324-3.1 into the CockroachDB fork.
  5. [ ] Review/land this PR.

This PR is currently written as if (1)-(4) have happened; I'm expecting CI to fail until they're complete. I'll need @knz's help to get (1) and (2) done. Then ideally someone with commit rights would take care of (3), since bumping deps is a real pain without push access to vendored. I've already asked @jordanlewis (via Slack) to take care of (4). And that should cover it!

2019-06-21 06:39 UTC, knz commented
points 1-3 are ready (pending review+merge of  #38345)

I don't understand point 4 - I see that a branch called `crl-release-20190324-3.1` was created on github.com/cockroachdb/libedit, but did you not want this in `master`?

2019-06-21 06:44 UTC, knz approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @benesch, and @jordanlewis)

___
*[Makefile, line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32623#-LhslNOn2YDtxxfR1Wjg:-LhslNOoC-yUWBoilosI:b-258cyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a25accc49f83771004b51766c3017118e30bb03/Makefile#L522)):*
> ```Makefile
> 	@echo >> $@
> 	@echo '// #cgo CPPFLAGS: -DGO_LIBEDIT_NO_BUILD' >> $@
> 	@echo '// #cgo LDFLAGS: -ledit -lncurses' >> $@
> ```

Do I understand right that the cgo cflags/ldflags are combined across multiple go files in the same dir? If so, this looks good.


<!-- Sent from Reviewable.io -->

2019-06-21 20:00 UTC, benesch commented
> I don't understand point 4 - I see that a branch called crl-release-20190324-3.1 was created on github.com/cockroachdb/libedit, but did you not want this in master?

We handle C dependency repositories a bit different than we handle the vendored repository. In vendored we just need to keep Git from GCing any of the commits that have been referred to by cockroachdb/cockroach, which we accomplish by putting every commit on master. We don't care about the particular history at all, since `dep ensure`, well, ensures that we're getting exactly the copy of our dependencies that we've asked for.

For the C dependencies, we're maintaining complicated patch sets on top of upstream. The RocksDB fork is the best example of this: https://github.com/cockroachdb/rocksdb/branches. Creating a fresh branch for every new release is the sanest approach I've found for maintaining these patchsets. If you just merge upstream into master periodically, it's easy to lose track of particular patches (e.g. by resolving conflicts in the wrong direction).

2019-06-21 20:19 UTC, knz commented
ok thanks for the explanation!

2019-06-21 20:30 UTC, benesch commented
Whew, ok, thanks for all the help, @knz! I've just rebased this. Will merge on green.

2019-06-21 20:35 UTC, knz commented
well thanks to _you_ kind sir

2019-06-21 21:33 UTC, benesch commented
It's green! 💚 

bors r=knz

2019-06-21 21:59 UTC, merged

2019-06-24 17:19 UTC, bobvawter commented
This patch appears to break the nightly Windows build

```
[01:57:30]2019/06/24 01:57:30 [] [mkrelease windows GOFLAGS= SUFFIX=.windows-6.2-amd64.exe TAGS= BUILDCHANNEL=official-binary]
[01:57:30]+ CGO_ENABLED=1
[01:57:30]+ make BUILDTYPE=release XGOOS=windows XGOARCH=amd64 XCMAKE_SYSTEM_NAME=Windows TARGET_TRIPLE=x86_64-w64-mingw32 LDFLAGS=-static SUFFIX=-windows-6.2-amd64 GOFLAGS= SUFFIX=.windows-6.2-amd64.exe TAGS= BUILDCHANNEL=official-binary
[01:57:32]configure: error: libncurses, libcurses, or libtermcap is required!
[01:57:33]make: *** [/go/native/x86_64-w64-mingw32/libedit/Makefile] Error 1
[01:57:33]make: *** Waiting for unfinished jobs....
[01:57:58]2019/06/24 01:57:58 [mkrelease windows GOFLAGS= SUFFIX=.windows-6.2-amd64.exe TAGS= BUILDCHANNEL=official-binary]: exit status 1
```

2019-06-24 17:25 UTC, benesch commented
Oh, hm, I guess we shouldn't bother trying to build lib edit for Windows because it certainly won't work there.

2019-06-24 18:12 UTC, benesch commented
I'll have a patch for this shortly.

2019-06-24 20:42 UTC, danhhz commented
Awesome! Feel free to cc me on the review. I'm about to cut a 19.2 alpha and this has Publish Bleeding Edge blocked

2019-06-24 21:45 UTC, danhhz commented
Argh, sorry, but I had to revert this to get an alpha release started 😬. We didn't have any recent green Publish Bleeding Edge builds. https://github.com/cockroachdb/cockroach/pull/38383. Should be easy to unrevert with the windows fix, tho

2019-06-24 22:47 UTC, benesch commented
Ah, shoot, too bad. The patch is prepared, but the holdup is waiting for
Docker to verify that the thing actually builds on Windows. Will circle
back later tonight.

On Mon, Jun 24, 2019 at 5:46 PM Daniel Harrison <notifications@github.com>
wrote:

> Argh, sorry, but I had to revert this to get an alpha release started 😬.
> We didn't have any recent green Publish Bleeding Edge builds. #38383
> <https://github.com/cockroachdb/cockroach/pull/38383>. Should be easy to
> unrevert with the windows fix, tho
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/32623?email_source=notifications&email_token=AAGXSICTBJGM3PEYOXURY63P4E6CLA5CNFSM4GGTBVS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYOKL2Y#issuecomment-505193963>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAGXSIG7XV3OVDW2TBQS6JDP4E6CLANCNFSM4GGTBVSQ>
> .
>