storage: partially deflake TestSystemZoneConfigs
cockroachdb/cockroach pull request #32642
Opened 2018-11-27 16:42 UTC by ridwanmsharif

I doubt this fixes #32511 completely, but this does address the
splits @andreimatei saw with the same test. With the scan interval
being so low, there are about 20 scans, each of which with ~ 20
replicas per scan, and they hit ~ 10 queues. If the queues do a meta
lookup or any other system lookup, it is possible that the QPS threshold
for splits is exceeded. To fix this, we turn off LBS in such tests

Release note: None

2018-11-27 16:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32642)
<!-- Reviewable:end -->

2018-11-27 17:30 UTC, benesch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-:-LSLDI7o0xtubvAnHnTP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ccl/partitionccl/partition_test.go, line 1112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLAlcC89J-tM1wXoTj:-LSLAlcD8-KxSa_t60ss:b8w8pc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/ccl/partitionccl/partition_test.go#L1112)):*
> ```Go
> 				Store: &storage.StoreTestingKnobs{
> 					// Disable LBS because when the scan is happening at the rate its happening
> 					// below, its possible that one of the system ranges trigger a split.
> ```

nit: s/its/it's/ (both cases)
___
*[pkg/storage/client_replica_test.go, line 1606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLDDtnEV-de5gnZy4k:-LSLDDtnEV-de5gnZy4l:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/storage/client_replica_test.go#L1606)):*
> ```Go
> 				Store: &storage.StoreTestingKnobs{
> 					// Disable LBS because when the scan is happening at the rate its happening
> 					// below, its possible that one of the system ranges trigger a split.
> ```

nit: ditto
___
*[pkg/storage/node_liveness_test.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLDFOk-PJTB43dxVnq:-LSLDFOlC4RQ-rl_9qPd:b-iipjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/storage/node_liveness_test.go#L789)):*
> ```Go
> 				DisableReplicaRebalancing: true,
> 				// Disable LBS because when the scan is happening at the rate its happening
> 				// below, its possible that one of the system ranges trigger a split.
> ```

nit: ditto
___
*[pkg/testutils/testcluster/testcluster.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLB0Ei2JR3L_ZqyVMe:-LSLB0Ei2JR3L_ZqyVMf:bp4lc7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/testutils/testcluster/testcluster.go#L277)):*
> ```Go
> 				if !strings.Contains(err.Error(), "unknown cluster setting") {
> 					t.Fatal(err)
> 				}
> ```

Is this necessary? Unit tests should always run with the latest cluster version. I guess there are a few cluster version tests that manipulate the cluster version, but those just won't set DisableLoadBasedSplitting.


<!-- Sent from Reviewable.io -->

2018-11-27 17:54 UTC, ridwanmsharif reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-:-LSLIiqYAVQwbAjhycBE:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-27 17:56 UTC, a-robinson requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/testutils/testcluster/testcluster.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLIbu-8aTpcGic9ucX:-LSLIbu-8aTpcGic9ucY:b-i74k6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/testutils/testcluster/testcluster.go#L270)):*
> ```Go
> 	if serverArgs.Knobs.Store != nil {
> 		storeKnobs := serverArgs.Knobs.Store.(*storage.StoreTestingKnobs)
> 		if storeKnobs.DisableLoadBasedSplitting && len(tc.Servers) == 0 {
> ```

`StoreTestingKnobs` are typically implemented in the store, not in the `TestCluster`. I'd suggest either implementing the disabling in the Stores themselves (such that they still take effect even if a full `TestCluster` isn't being used) if possible, or else add the option to `TestClusterArgs` instead of `StoreTestingKnobs`.

Also, I'd optionally consider automatically disabling load-based splitting (at the store level) if `ScanInterval` is less than some threshold. That'd help us avoid accidentally adding more tests that set `ScanInterval` without disabling splitting.


<!-- Sent from Reviewable.io -->

2018-11-27 17:57 UTC, a-robinson reviewed
Also, did you confirm that this helps at all?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-:-LSLJFF43_GJUe6vLMMY:bq7o6eq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-27 18:51 UTC, ridwanmsharif reviewed
Running stress tests on this before the change, at one point showed that splits were occurring. After this change, I confirmed that was no longer the case. I still see a test failure (like in the issue, but that does seem unrelated to LBS).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-:-LSLTrGQB-OM_owzn1g7:bhzrajy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 7027 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLV6ea6eGNgFUtwhpp:-LSLV6ea6eGNgFUtwhpq:b-har5i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/703dbee234f7ed699c7d64ed2b390463f28396a4/pkg/storage/replica.go#L7027)):*
> ```Go
> 	return SplitByLoadEnabled.Get(&r.store.cfg.Settings.SV) &&
> 		r.store.ClusterSettings().Version.IsMinSupported(cluster.VersionLoadSplits) &&
> 		!r.store.TestingKnobs().DisableLoadBasedSplitting
> ```

@a-robinson is this more like what you had in mind to disable LBS in tests?
___
*[pkg/testutils/testcluster/testcluster.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSLIbu-8aTpcGic9ucX:-LSLUDzn9VBZgQHc-Gjg:b-j6hekc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f109d30c1c74bf7ff60dfa66f3580a110bc0413f/pkg/testutils/testcluster/testcluster.go#L270)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

`StoreTestingKnobs` are typically implemented in the store, not in the `TestCluster`. I'd suggest either implementing the disabling in the Stores themselves (such that they still take effect even if a full `TestCluster` isn't being used) if possible, or else add the option to `TestClusterArgs` instead of `StoreTestingKnobs`.

Also, I'd optionally consider automatically disabling load-based splitting (at the store level) if `ScanInterval` is less than some threshold. That'd help us avoid accidentally adding more tests that set `ScanInterval` without disabling splitting.
</blockquote></details>

Thats a good note. I now disable LBS if the `ScanInterval` is low. I still kept the `StoreTestingKnob` so its easier in the future to use it to disable LBS using it.


<!-- Sent from Reviewable.io -->

2018-11-27 18:52 UTC, a-robinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-:-LSLVwnA-n1k8kOpijxb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2018-11-27 19:45 UTC, ridwanmsharif commented
bors r+

2018-11-27 20:16 UTC, merged

2018-11-28 17:33 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32642)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/storage/testing_knobs.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32642#-LSQNG-b2wEH3m9e1jdT:-LSQNG-b2wEH3m9e1jdU:b-i9u31c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8b00ed9070dacbd5e3dc3bb1d13807cbcd7a8c3/pkg/storage/testing_knobs.go#L112)):*
> ```Go
> 	DisableReplicaRebalancing bool
> 	// DisableLoadBasedSplitting turns off LBS so no splits happen because of load.
> 	DisableLoadBasedSplitting bool
> ```

could the test using this just use `ReplicationMode: base.ReplicationManual` instead?
Separately, how does this new know interact with `ReplicationManual`? Is it implied by that?


<!-- Sent from Reviewable.io -->

2018-11-28 17:57 UTC, ridwanmsharif commented
Yes looks like using that replication mode would stop the split queue (that LBS uses for splits) and so it'd imply that LBS would also be disabled. This testing knob tho lets us control LBS specifically, without turning off the split queue completely (doesn't really matter for this test though).