exec: added the hashed aggregator operator
cockroachdb/cockroach pull request #32685
Opened 2018-11-28 19:50 UTC by changangela

This PR adds on top of #32393 (non-distinct hash joiner) and #32277 (average aggregate function).

The `hashedAggregator` is an operator that performs an aggregation based on specified grouping columns. This operator performs a blocking hash table build at the beginning and then the grouped buckets are then passed as input to an orderedAggregator. The output row ordering of this aggregator is arbitrary.

Benchmark results:
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/exec
BenchmarkHashAggregator/rows=2048-8         	    5000	    253410 ns/op	 258.62 MB/s
BenchmarkHashAggregator/rows=4096-8         	    3000	    430055 ns/op	 304.78 MB/s
BenchmarkHashAggregator/rows=16384-8        	    1000	   1493246 ns/op	 351.11 MB/s
BenchmarkHashAggregator/rows=262144-8       	      50	  29557663 ns/op	 283.80 MB/s
BenchmarkHashAggregator/rows=4194304-8      	       2	 819780630 ns/op	 163.72 MB/s
BenchmarkHashAggregator/rows=67108864-8     	       1	20412171368 ns/op	 105.21 MB/s
PASS
ok  	github.com/cockroachdb/cockroach/pkg/sql/exec	30.353s
```

2018-11-28 19:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32685)
<!-- Reviewable:end -->

2018-12-06 17:51 UTC, jordanlewis commented
Going to start reviewing this now. @asubiotto could you also take a look at this?

2018-12-10 09:54 UTC, asubiotto commented
Yup! @changangela, could you rebase this? I think there are a couple of commits on your branch that are part of master.

2018-12-10 15:46 UTC, changangela commented
Yup, should be good now.

2018-12-14 09:32 UTC, asubiotto requested changes
Nice work!

Not sure if I missed it but the `exec: fix ColBatchSize to type uint16` commit needs a commit message with a clear motivation. I think you might also be able to squash the commit of removing redundant hashed aggregator work into the first commit. It might also be good to extract the hash joiner changes in the first commit into a separate, earlier commit but that's up to you.

> Reviewed 6 of 6 files at r1, 10 of 10 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-:-LTg0yPC5c70sq22d_V7:b-hll98s)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcV-RJ6s1bskyppUsM:-LTcV-RJ6s1bskyppUsN:b-cpubdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L272)):*
> ```Go
> 
> // hashedAggregator is an operator that performs an aggregation based on
> // specified grouping columns. This operator performs a blocking hash table
> ```

What do you mean by blocking?
___
*[pkg/sql/exec/aggregator.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcUtI60v9TMUCWkX75:-LTcUtI60v9TMUCWkX76:bpg62w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L276)):*
> ```Go
> // to an orderedAggregator. The output row ordering of this aggregator is
> // arbitrary.
> type hashedAggregator struct {
> ```

nit: I would call this `hashAggregator`
___
*[pkg/sql/exec/aggregator.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcoF6U-NrNQr8aoyj8:-LTcoF6U-NrNQr8aoyj9:b-7mnv0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L277)):*
> ```Go
> // arbitrary.
> type hashedAggregator struct {
> 	spec *aggregatorSpec
> ```

Not sure this needs to be a pointer.
___
*[pkg/sql/exec/aggregator.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTck_XI1VlAMyIqgNON:-LTck_XI1VlAMyIqgNOO:b-xvzh7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L279)):*
> ```Go
> 	spec *aggregatorSpec
> 
> 	isBuilding bool
> ```

Since the aggregator first builds and then aggregates, I would rename this to `isAggregating` or something equivalent which stores the inverse of `isBuilding`. In this way you don't have to worry about setting the correct initial state and can only set it when transitioning to the second stage or resetting the aggregator.
___
*[pkg/sql/exec/aggregator.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcmWN0Dy9s-QvRpXpD:-LTcmWN0Dy9s-QvRpXpE:b2m84lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L290)):*
> ```Go
> 
> func NewHashedAggregator(
> 	input Operator, aggFns []int, groupCols []uint32, aggCols [][]uint32, colTypes []types.T,
> ```

re: aggFns I think you can use `distsqlb` directly (e.g.https://github.com/cockroachdb/cockroach/pull/32969/commits/3543fc26a77e08920155e26e96997263ad953202)
___
*[pkg/sql/exec/aggregator.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTccL22DTrHB93d7UDJ:-LTccL22DTrHB93d7UDK:bn5vg78) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L293)):*
> ```Go
> ) (Operator, error) {
> 	// Determine the groupTyps and aggTyps from the colTypes.
> 	groupTyps := make([]types.T, len(groupCols))
> ```

Great idea. Do you think you could extract this into a helper function that e.g. `NewOrderedAggregator` also uses?
___
*[pkg/sql/exec/aggregator.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnS7z9WAoKZCjEzr3:-LTcnS7z9WAoKZCjEzr4:b3f44c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L309)):*
> ```Go
> 	nCols := uint32(len(colTypes))
> 	keepCol := make([]bool, nCols)
> 	compressed := make([]uint32, nCols)
> ```

Please add a comment to compressed
___
*[pkg/sql/exec/aggregator.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnlgGBoRpBSTfjuZi:-LTcnlgGBoRpBSTfjuZj:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L371)):*
> ```Go
> 		aggTyps,
> 	)
> ```

nit: extra line
___
*[pkg/sql/exec/aggregator.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnxB-5EqJFlbJTKaW:-LTcnxB-5EqJFlbJTKaX:b-oipi5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L418)):*
> ```Go
> var _ Operator = &hashedAggregator{}
> 
> type aggregatorSpec struct {
> ```

This is something I've been meaning to bring up @jordanlewis. We use specs in distsql mostly to serialize them into protos but it has the additional benefit of grouping together arguments to avoid a long list of parameters to operator/processor creation. I don't think these columnar exec specs need to be made into protos as they are a subset of `distsqlb` protos. I'm all for keeping these specs as lightweight as possible. @changangela, do you think you could also use this `aggregatorSpec` as a parameter to `NewHashedAggregator` (and maybe also `NewOrderedAggregator`?)
___
*[pkg/sql/exec/aggregator.go, line 376 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTg22zO0ZzT8UmP7Fgc:-LTg22zO0ZzT8UmP7Fgd:b5zc95j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9be01f54a4c6ac62df2947c6c72cbad98237a24/pkg/sql/exec/aggregator.go#L376)):*
> ```Go
> 		aggCols:        mappedAggCols,
> 		aggTyps:        aggTyps,
> 		groupCol:       distinctCol,
> ```

Another strategy to do this is to extract the rest of `NewOrderedAggregator` into its own package-private function so you could call that from here as well as `NewOrderedAggregator`. This would protect cases in which some new functionality when instantiating an ordered aggregator is added but not picked up in the `hashedAggregator`.
___
*[pkg/sql/exec/aggregator.go, line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTg1sKE32varM8cviso:-LTg1sKE32varM8cvisp:b-6s04mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9be01f54a4c6ac62df2947c6c72cbad98237a24/pkg/sql/exec/aggregator.go#L503)):*
> ```Go
> 	nSelected = uint16(batchEnd - op.batchStart)
> 
> 	copy(op.distinctCol, op.distinct[op.batchStart:batchEnd])
> ```

Does this need to be a copy?
___
*[pkg/sql/exec/aggregator_test.go, line 422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTfz-iyCbcARrSG2V4G:-LTfz-iyCbcARrSG2V4H:b5vzd0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator_test.go#L422)):*
> ```Go
> 	floats := []float64{1.3, 1.6, 0.5, 1.2, 3.4}
> 	decs := make([]apd.Decimal, len(floats))
> 	for i, f := range floats {
> ```

Can you extract and reuse the logic from the decimal conversion code at the top of this file?
___
*[pkg/sql/exec/aggregator_test.go, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTfyi5i3dPa7SHpAn6z:-LTfyi5i3dPa7SHpAn7-:b-hdj844) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator_test.go#L440)):*
> ```Go
> 	}{
> 		{
> 			// Test carry between output batches.
> ```

Consider adding a `name` field to your test cases and running each test case in a subtest. In this way, when any test fails, you know exactly which one and what it's trying to test. Actually, I wonder if you could reuse the `aggregatorTestCase` struct.
___
*[pkg/sql/exec/aggregator_test.go, line 564 at r1 [...]

2018-12-17 20:51 UTC, changangela reviewed
TFTRs! I've pulled the `exec: fix ColBatchSize to type uint16` out of this PR for now since rebasing got too messy.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-:-LTxQ4Dr2k9_YRuC7_1K:bofs1d6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcV-RJ6s1bskyppUsM:-LTwuNog7cCtbXgMbzzV:bpxkq5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L272)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What do you mean by blocking?
</blockquote></details>

Done. Reworded this comment.
___
*[pkg/sql/exec/aggregator.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcUtI60v9TMUCWkX75:-LTwuQIf0mntd94rPnEu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L276)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I would call this `hashAggregator`
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcoF6U-NrNQr8aoyj8:-LTwv87gDXHdiakvhlWy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L277)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure this needs to be a pointer.
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTck_XI1VlAMyIqgNON:-LTwvYsK-Nf8o-SZJChS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L279)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since the aggregator first builds and then aggregates, I would rename this to `isAggregating` or something equivalent which stores the inverse of `isBuilding`. In this way you don't have to worry about setting the correct initial state and can only set it when transitioning to the second stage or resetting the aggregator.
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcmWN0Dy9s-QvRpXpD:-LTxQQEY4qi1DSUMwvK2:b-m7t04l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L290)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

re: aggFns I think you can use `distsqlb` directly (e.g.https://github.com/cockroachdb/cockroach/pull/32969/commits/3543fc26a77e08920155e26e96997263ad953202)
</blockquote></details>

I've tried to cherry-pick that commit into this branch since there are a few dependencies needed to use `distsqlb` directly, but this didn't turn out to be as cleaned as I hoped since a lot of the aggregator stuff has been refactored. I think maybe it would be easier to make the change from `int` to `distsqlb` in the `exec: use distsqlpb.Aggregator_Spec_Func directly` commit instead?
___
*[pkg/sql/exec/aggregator.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTccL22DTrHB93d7UDJ:-LTxaBo1189dcx-xvrcz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L293)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Great idea. Do you think you could extract this into a helper function that e.g. `NewOrderedAggregator` also uses?
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnS7z9WAoKZCjEzr3:-LTxb1WGAgyrTjWOqcjN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L309)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Please add a comment to compressed
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnlgGBoRpBSTfjuZi:-LTxb29g8vJOdG3u6jGh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L371)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: extra line
</blockquote></details>

Done.
___
*[pkg/sql/exec/aggregator.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnxB-5EqJFlbJTKaW:-LTxcRNB2sGq-duHRL3a:bh97npj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L418)):*
> This is something I've been meaning to bring up @jordanlewis. We use specs in distsql mostly to serialize them into protos but it has the additional benefit of grouping together arguments to avoid a long list of parameters to operator/processor creation. I don't think these columnar exec specs need to be made into protos as they are a subset of distsqlb protos. I'm all for keeping these specs as lightweight as possible. @changangela, do you think you could also use this aggregatorSpec as a parameter to NewHashedAggregator (and maybe also NewOrderedAggregator?)
<details><summary><i alt="summary">Quoted 400 lines of code…</i></summary>

>               
>             
>             
>           
>         
>         
>           
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 asubiotto (Alfonso Subiotto Marqués) is:
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                    Blocking: opposed to resolving the discussion while waiting on somebody else.
>                 
>                 
>                 
>                 
>                    Dismiss from
>                   this discussion
>                   •
>                   unresolved discussions.
>                 
>                 
>                 
>                 
>               
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 jordanlewis (Jordan Lewis) is:
>                 
>                 
>                 
>                 
>                    Mentioned: recently @-mentioned in a comment but neutral on resolving.
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>               
>             
>             
>               
>                 
>                 
>               
>               
>               
>                 
>                   
>                     
>                       
>                         This is advanced stuff, you don't need it to get started.
>                       
>                       You are:
>                       
>                       
>                       
>                     
>                     
>                        Uninvolved: not yet involved in this discussion.
>                     
>                     
>                        Following: following new comments bu [...]

2018-12-17 22:02 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32685)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/aggregator.go, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-LTcnxB-5EqJFlbJTKaW:-LTyBFQ_EXoQ8zf7WDru:b-l33d51) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6da5c3a12e3faea682b0a9ebbe9be6fbc004595/pkg/sql/exec/aggregator.go#L418)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

> This is something I've been meaning to bring up @jordanlewis. We use specs in distsql mostly to serialize them into protos but it has the additional benefit of grouping together arguments to avoid a long list of parameters to operator/processor creation. I don't think these columnar exec specs need to be made into protos as they are a subset of distsqlb protos. I'm all for keeping these specs as lightweight as possible. @changangela, do you think you could also use this aggregatorSpec as a parameter to NewHashedAggregator (and maybe also NewOrderedAggregator?)
>               
>             
>             
>           
>         
>         
>           
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 asubiotto (Alfonso Subiotto Marqués) is:
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                    Blocking: opposed to resolving the discussion while waiting on somebody else.
>                 
>                 
>                 
>                 
>                    Dismiss from
>                   this discussion
>                   •
>                   unresolved discussions.
>                 
>                 
>                 
>                 
>               
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 jordanlewis (Jordan Lewis) is:
>                 
>                 
>                 
>                 
>                    Mentioned: recently @-mentioned in a comment but neutral on resolving.
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>               
>             
>             
>               
>                 
>                 
>               
>               
>               
>                 
>                   
>                     
>                       
>                         This is advanced stuff, you don't need it to get started.
>                       
>                       You are:
>                       
>                       
>                       
>                     
>                     
>                        Uninvolved: not yet involved in this discussion.
>                     
>                     
>                        Following: following new comments but neutral on resolving.
>                     
>                     
>                        Mentioned: recently @-mentioned in a comment but neutral on resolving.
>                     
>                     
>                        Dismissed: was engaged but dismissed by
>                       .
>                     
>                     
>                        Discussing: contributing to the discussion but neutral on resolving.
>                       
>                     
>                     
>                        Informing: resolving the discussion but keeping it active for everyone.
>                       
>                         This will resolve the discussion.
>                       
>                     
>                     
>                        Satisfied: in favor of resolving and ending the discussion.
>                       
>                     
>                     
>                        Blocking: opposed to resolving the discussion while waiting on somebody else.
>                     
>                     
>                        Working: holding the discussion unresolved while working on something related.
>                     
>                     
>                   
>                   
>                     
>                       Your global discussion settings:
>                       
>                     
>                     
>                       
>                       
>                         Trust but ver­ify: when you are Dis­cussing on a dis­cus­sion and it gets re­solved with­out fur­ther com­ment, bring it to your at­ten­tion.
>                       
>                     
>                   
>                 
>                 
>               
>             
>           
>           
>             
>               
>                 
>               
>               
>               
>                 
>                 
>                 done
>               
>             
>           
>           
>         
>       
>     
>     
>   
> 
> 
>   
>   
>   
>     
>       type aggregatorSpec struct {
>     
>     
>   
> 
> 
>   
>     
>       input    Operator
>     
>     
>   
>   
>   
>     
>       input    Operator
>     
>     
>   
> 
> 
>   
>     
>       colTypes []types.T
>     
>     
>   
>   
>   
>     
>       colTypes []types.T
>     
>     
>   
> 
> 
>   
>     
>        
>     
>     
>   
>   
>   
>     
>        
>     
>     
>   
> 
> 
>   
>     
>     
>     
>       
>         
>           
>           
>           EXPAND
>         
>         
>           
>           
>           EXPAND
>         
>       
>       
>         
>           
>           Collapsed:
>         
>         
>           79 lines
>           with
>           no changes
>         
>         
>           
>             
>               Expand everything:
>               this file
>               
>                 •
>                 all files
>               
>             
>             
>               
>               Collapse whitespace changes
>             
>             
>               Applies to all future diffs in this review and sets your default for new reviews.
>             
>             
>           
>         
>       
>     
>     
>   
>   
>   
>     
>       func (op *hashedAggregatorBatchOp) Next() ColBatch {   ⋯ expand 47 lines
>     
>   
>   
>   
>     
>       func (op *hashedAggregatorBatchOp) Next() ColBatch {   ⋯ expand 47 lines
>     
>   
> 
> 
> 
> 
>   
>     
>       }
>     
>     
>   
>   
>   
>     
>       }
>     
>     
>   
> 
> 
>   
>     
>       nSelected = uint16(batchEnd - op.batchStart)
>     
>     
>   
>   
>   
>     
>       nSelected = uint16(batchEnd - op.batchStart)
>     
>     
>   
> 
> 
>   
>     
>        
>     
>     
>   
>   
>   
>     
>        
>     
>     
>   
> 
> 
>   
>     
>       copy(op.distinctCol, op.distinct[op.batchStart:batchEnd])
>     
>     
>   
>     
>       r3⊥
>     
>     
>       
>         
>          In progress
>         
>         
>         
>           after publishing
>         
>       
>       
>       
>         —
>         
>           
>             
>           
>           
>             Show
>             1
>             
>             comment
>           
>         
>         
>           
>             
>               Show all in:
>               
>                 this file
>                 •
>               
>               
>                 all files
>               
>             
>           
>         
>       
>       
>         
>           line 503 
>         
>         
>       
>     
>     
>       
>         
>           
 [...]

2018-12-20 11:42 UTC, asubiotto commented
Will take a look at this today. Could you rebase and resolve the conflicts?

2018-12-20 18:48 UTC, changangela reviewed
Thanks, rebased! There were a lot of conflicts so I decided to just rebase on top of #33206. This way we don't have to do another major rebase again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32685#-:-LUBwO4kDQ8HNSPIWi1A:b9lhb5f)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-03-01 15:22 UTC, asubiotto commented
Superseded by #34770

2019-03-01 15:22 UTC, closed without merging