exec: added null handling to inner hash join
cockroachdb/cockroach pull request #32836
Opened 2018-12-04 21:37 UTC by changangela

The null handling is particularly slow right now because the `ColVec` helper functions like `Append` and `CopyWithSel` basically perform an inefficient loop around each bit of the `nulls` bitmap. I didn't want to change the `Nulls` interface too much since this PR builds on top of #32809. I'm guessing a lot of the slow down can be eliminated by optimizing these helper functions.

This PR also builds off the non-distinct hash joiner (#32393).

```
BenchmarkHashJoiner/distinct=true/rows=2048-8         	    5000	    339357 ns/op	 386.24 MB/s
BenchmarkHashJoiner/distinct=true/rows=4096-8         	    2000	    565344 ns/op	 463.69 MB/s
BenchmarkHashJoiner/distinct=true/rows=16384-8        	    1000	   1804217 ns/op	 581.18 MB/s
BenchmarkHashJoiner/distinct=true/rows=262144-8       	      50	  28003113 ns/op	 599.12 MB/s
BenchmarkHashJoiner/distinct=true/rows=4194304-8      	       3	 385702946 ns/op	 695.96 MB/s
BenchmarkHashJoiner/distinct=true/rows=67108864-8     	       1	9463122409 ns/op	 453.86 MB/s
BenchmarkHashJoiner/distinct=false/rows=2048-8        	    3000	    344335 ns/op	 380.65 MB/s
BenchmarkHashJoiner/distinct=false/rows=4096-8        	    2000	    600059 ns/op	 436.86 MB/s
BenchmarkHashJoiner/distinct=false/rows=16384-8       	    1000	   2013463 ns/op	 520.78 MB/s
BenchmarkHashJoiner/distinct=false/rows=262144-8      	      50	  34850256 ns/op	 481.41 MB/s
BenchmarkHashJoiner/distinct=false/rows=4194304-8     	       2	 852387298 ns/op	 314.92 MB/s
BenchmarkHashJoiner/distinct=false/rows=67108864-8    	       1	18771088932 ns/op	 228.81 MB/s
```

2018-12-04 21:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32836)
<!-- Reviewable:end -->

2018-12-06 17:24 UTC, jordanlewis commented
Can you rebase this? I think a lot more prerequisites have been merged now, and it looks like you accidentally picked up some other random commits.

2018-12-06 17:44 UTC, changangela reviewed
> Can you rebase this? I think a lot more prerequisites have been merged now, and it looks like you accidentally picked up some other random commits.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-:-LT3betfDQ218zCFKXrN:bc9mp51)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-11 16:40 UTC, changangela commented
PTAL - the hash joiner is now able to use shortcuts when there is no null values present in either the build table or the probe batch.

2018-12-18 11:26 UTC, asubiotto requested changes
Do you think you could extract all non-hashjoiner null-related stuff into its own commit earlier commit?  It'll be easier to review this PR that way. I skipped over the first three commits given that they seem to be from another PR but prerequisite changes. Since those are about adding null handling, maybe the general null stuff belongs in those commits?

I also think r7 (selection vector templating) belongs in its own PR, it'll be easier to digest the changes there. It also seems that r9 is removing this functionality in favor of different functionality? Those two should probably be squashed into one and moved into a different PR. I'll have to take a closer look at these changes.

@jordanlewis, could you take a look at the `overloads.go` and null changes?

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 7 of 7 files at r6, 4 of 4 files at r7, 2 of 2 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-:-LU-wrY-0m_R64_Yw_6M:b-iktcs5)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tA6X05qcbqvWPtT6:-LU-tA6X05qcbqvWPtT7:b-e1syac) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L94)):*
> ```Go
> 
> 	NullAt64(i uint64) bool
> 	SetNull64(i uint64)
> ```

Why do these need to be added?
___
*[pkg/sql/exec/colvec.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tcH0Ei1t4nXaHINq:-LU-tcH0Ei1t4nXaHINr:b48izj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L114)):*
> ```Go
> 	var nulls []int64
> 	if n > 0 {
> 		nulls = make([]int64, (n-1)>>6+1)
> ```

I think this belongs more in `r3: exec: null handling` than this commit. cc @jordanlewis
___
*[pkg/sql/exec/colvec.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-uWlz5LR_T-hW1jyj:-LU-uWlz5LR_T-hW1jyk:bxofxov) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L163)):*
> ```Go
> func (m *memColumn) UnsetNulls() {
> 	for i := range m.nulls {
> 		m.nulls[i] = 0
> ```

Why can this not be a copy anymore?
___
*[pkg/sql/exec/colvec.go, line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-szJv8aM5dGRthj9Y:-LU-szJwC8XQoWYajOJy:b-5c2ydc) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L169)):*
> ```Go
> func (m *memColumn) NullAt64(i uint64) bool {
> 	intIdx := i >> 6
> 	//if intIdx >= uint64(len(m.nulls)) {
> ```

Leftover
___
*[pkg/sql/exec/hashjoiner.go, line 314 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-qV583TvKwuuIPJ-x:-LU-qV583TvKwuuIPJ-y:b-uok405) ([raw file](https://github.com/cockroachdb/cockroach/blob/5692abfa2231a9e8de4e83613f5f9a71c7d74620/pkg/sql/exec/hashjoiner.go#L314)):*
> ```Go
> 	nKeep := uint32(0)
> 
> 	keepTypes := make([]types.T, 0)
> ```

In cases like these, when you know the maximum size of the slice (i.e. `nCols`) but not its resulting size you can do `keepTypes := make([]types.T, 0, nCols)` which will initialize `keepTypes` to have that capacity as its underlying storage so you know that `append`ing will never grow the slice. Same thing goes for `cols`.
___
*[pkg/sql/exec/hashjoiner_test.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU0-Lqd1QxxrQFzjN2G:-LU0-Lqd1QxxrQFzjN2H:buxar46) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d0b6be3bfa8e8de8afa9fd6a9b8e007cf6484f9/pkg/sql/exec/hashjoiner_test.go#L58)):*
> ```Go
> 	}{
> 		{
> 			leftTypes:  []types.T{types.Int64},
> ```

Do these tests belong in this commit? My understanding is that you're not changing `hashJoiner` behavior here. Maybe they should be in r5?
___
*[pkg/sql/exec/hashjoiner_test.go, line 657 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU01hy0-n5oxpkjkCwC:-LU01hy0-n5oxpkjkCwD:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ddda4ca30658e1c0b3841beb54f5030e3dd3cb/pkg/sql/exec/hashjoiner_test.go#L657)):*
> ```Go
> 	for _, hasNulls := range []bool{false, true} {
> 		b.Run(fmt.Sprintf("nulls=%v", hasNulls), func(b *testing.B) {
> ```

nit: extra space
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU00u80DLI02zq89uzl:-LU00u80DLI02zq89uzm:b-gcn9lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d0b6be3bfa8e8de8afa9fd6a9b8e007cf6484f9/pkg/sql/exec/hashjoiner_tmpl.go#L78)):*
> ```Go
> 		_SEL_CLAUSE_BEGIN()
> 		for i := uint64(0); i < nKeys; i++ {
> 			v := keys[_WRAP_SEL("i")]
> ```

I'm a bit unclear as to why we need `_WRAP_SEL` here. Could you make the for loop part of `SEL_CLAUSE_BEGIN` and iterate over the elements of `sel` as `i` and just use `i` here?
___
*[pkg/sql/exec/utils_test.go, line 273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-vwc-8UxDG6GznKgz:-LU-vwc-8UxDG6GznKh-:bkvt8pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/utils_test.go#L273)):*
> ```Go
> 	for i := 0; i < len(actual); i++ {
> 		if expected[i] == nil || actual[i] == nil {
> 			if expected[i] != nil || actual[i] != nil {
> ```

Is there any way to avoid having two branches here and in the case above?
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-ySM23XFPFsjrc6fQ:-LU-ySM23XFPFsjrc6fR:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f23f5c54cabe10e3fb93191d2781eae5144b5/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L102)):*
> ```Go
> 	vec ColVec, sel []uint64, nSel uint16, colType types.T,
> ) {
> ```

nit: extra space
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-y4Jf2GlBVUDUhaKv:-LU-y4Jf2GlBVUDUhaKw:b-novywz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f23f5c54cabe10e3fb93191d2781eae5144b5/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L117)):*
> ```Go
> 					m.SetNull(i)
> 				} else {
> 					toCol[i] = fromCol[sel[i]]
> ```

It might be more efficient to do a first pass ignoring nulls and then a second one to set the nulls. Might be worth adding a benchmark but I would maybe do that in a separate PR.
___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 132 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-wjeb-HK7kEy2wuiG:-LU-wjeb-HK7kEy2wuiH:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f23f5c54cabe10e3fb93191d2781eae5144b5/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L132)):*
> ```Go
> 
> func (m *memColumn) CopyWithSelInt16(vec ColVec, sel []uint16, nSel uint16, colType types.T) {
> 	
> ```

nit: extra space
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 262 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-ylfA03K7QwCQGwGF:-LU-ylfA03K7QwCQGwGG:b-fkb3is) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0f23f5c54cabe10e3fb93191d2781eae5144b5/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L262)):*
> ```Go
> 	return func(op overload, target, v, _ string) string {
> 		return fmt.Sprintf(`
> 			if %[2]s {
> ```

This might be more efficient if you did:
```
x := 0
if %[2]s {
    x = 1
}
%[1]s = x
```
Because the compiler optimizes out the if statement (similar to sum and avg). This should be easy to check with your benchmarks.
___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 366 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU01xZ6Bmj9ZHMOHitu:-LU01xZ6Bmj9ZHMOHitv:byjkvvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ddda4ca30658e1c0b3841beb [...]

2018-12-18 16:58 UTC, changangela reviewed
> Do you think you could extract all non-hashjoiner null-related stuff into its own commit earlier commit?  It'll be easier to review this PR that way. I skipped over the first three commits given that they seem to be from another PR but prerequisite changes. Since those are about adding null handling, maybe the general null stuff belongs in those commits?

TFTR!

Yep, I've extracted out all the template hash joiner stuff into its own PR (#33237). Now this PR only has the propagating null handling stuff.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-:-LU19kCX5W0q8gLimxXx:bvmz0py)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tA6X05qcbqvWPtT6:-LU1A1wY11zGpIwRNE0F:b-st7t6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L94)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do these need to be added?
</blockquote></details>

Since the hash joiner operates on a ColVec with size much greater than ColBatchSize, its indices could exceed uint16. This is pretty redundant though... any alternate ideas are welcome
___
*[pkg/sql/exec/colvec.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tcH0Ei1t4nXaHINq:-LU1BUhw2YsNqZRnf-Ff:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L114)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this belongs more in `r3: exec: null handling` than this commit. cc @jordanlewis
</blockquote></details>

Done.
___
*[pkg/sql/exec/colvec.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-uWlz5LR_T-hW1jyj:-LU1BYcp02FKswDEfIcN:b-4nh1je) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why can this not be a copy anymore?
</blockquote></details>

Since the `nulls` array was made to be variable size, I wasn't sure how to effectively do the copy in a similar manner,
___
*[pkg/sql/exec/colvec.go, line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-szJv8aM5dGRthj9Y:-LU1Bx983ELDBJ2qvew0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L169)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Leftover
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner.go, line 314 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-qV583TvKwuuIPJ-x:-LU1CLw24pC6KWT4HmeN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5692abfa2231a9e8de4e83613f5f9a71c7d74620/pkg/sql/exec/hashjoiner.go#L314)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In cases like these, when you know the maximum size of the slice (i.e. `nCols`) but not its resulting size you can do `keepTypes := make([]types.T, 0, nCols)` which will initialize `keepTypes` to have that capacity as its underlying storage so you know that `append`ing will never grow the slice. Same thing goes for `cols`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner_test.go, line 58 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU0-Lqd1QxxrQFzjN2G:-LU1CYJ3CVPXH5HaVWK5:b-uwovjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d0b6be3bfa8e8de8afa9fd6a9b8e007cf6484f9/pkg/sql/exec/hashjoiner_test.go#L58)):*
> Do these tests belong in this commit? My understanding is that you're not changing hashJoiner behavior here. Maybe they should be in r5?
<details><summary><i alt="summary">Quoted 1077 lines of code…</i></summary>

>               
>             
>             
>           
>         
>         
>           
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 asubiotto (Alfonso Subiotto Marqués) is:
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                    Blocking: opposed to resolving the discussion while waiting on somebody else.
>                 
>                 
>                 
>                 
>                    Dismiss from
>                   this discussion
>                   •
>                   unresolved discussions.
>                 
>                 
>                 
>                 
>               
>             
>             
>               
>                 
>                 
>               
>               
>               
>                 
>                   
>                     
>                       
>                         This is advanced stuff, you don't need it to get started.
>                       
>                       You are:
>                       
>                       
>                       
>                     
>                     
>                        Uninvolved: not yet involved in this discussion.
>                     
>                     
>                        Following: following new comments but neutral on resolving.
>                     
>                     
>                        Mentioned: recently @-mentioned in a comment but neutral on resolving.
>                     
>                     
>                        Dismissed: was engaged but dismissed by
>                       .
>                     
>                     
>                        Discussing: contributing to the discussion but neutral on resolving.
>                       
>                     
>                     
>                        Informing: resolving the discussion but keeping it active for everyone.
>                       
>                         This will resolve the discussion.
>                       
>                     
>                     
>                        Satisfied: in favor of resolving and ending the discussion.
>                       
>                     
>                     
>                        Blocking: opposed to resolving the discussion while waiting on somebody else.
>                     
>                     
>                        Working: holding the discussion unresolved while working on something related.
>                     
>                     
>                   
>                   
>                     
>                       Your global discussion settings:
>                       
>                     
>                     
>                       
>                       
>                         Trust but ver­ify: when you are Dis­cussing on a dis­cus­sion and it gets re­solved with­out fur­ther com­ment, bring it to your at­ten­tion.
>                       
>                     
>                   
>                 
>                 
>               
>             
>           
>           
>             
>               
>                 
>               
>               
>               
>                 
>                 
>                 done
>               
>             
>           
>           
>         
>       
>     
>     
>   
> 
> 
>   
>   
>   
>     
>        
>     
>     
>   
> 
> 
>   
>     
>       rightTypes: []types.T{types.Int64},
>     
>     
>   
>   
>   
>     
>        
>     
>     
>   
> 
> 
>   
>     
>        
>     
>     
>   
>   
>   
>     
>        
>     
>     
>   
> 
> 
>   
>      [...]

2018-12-19 09:27 UTC, asubiotto reviewed
> Reviewed 1 of 6 files at r11, 5 of 7 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tA6X05qcbqvWPtT6:-LU4biQPBb6PU8nC7jgG:b-j4iq1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L94)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Since the hash joiner operates on a ColVec with size much greater than ColBatchSize, its indices could exceed uint16. This is pretty redundant though... any alternate ideas are welcome
</blockquote></details>

Maybe you could just have the `Null` variants take in a `uint64`? But that would mean you need to cast the current uses. Try it out, and if it becomes tedious, you could leave these in but at least have the original Null methods cast to uint64 and call out to the uint64 methods. It's unfortunate that we've limited ourselves with uint16s here.
___
*[pkg/sql/exec/colvec.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-uWlz5LR_T-hW1jyj:-LU4b9EqESU-hWFmu7LE:b-ehdjbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L163)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Since the `nulls` array was made to be variable size, I wasn't sure how to effectively do the copy in a similar manner,
</blockquote></details>

I believe copy returns the number of elements copied, which you could keep track of in a loop where you do a `ColBatchSize` copy every iteration, using the number of elements copied as an index into the destination slice up to the condition where you've copied as many times as `m.nulls` is large.
___
*[pkg/sql/exec/hashjoiner_test.go, line 609 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU4kU8lAzvC8ZpzQFEO:-LU4kU8lAzvC8ZpzQFEP:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b5e9a9df2d83c56ba0d119e5a9b44570388fb12/pkg/sql/exec/hashjoiner_test.go#L609)):*
> ```Go
> 	for _, hasNulls := range []bool{false, true} {
> 		b.Run(fmt.Sprintf("nulls=%v", hasNulls), func(b *testing.B) {
> ```

nit: extra space
___
*[pkg/sql/exec/utils_test.go, line 273 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-vwc-8UxDG6GznKgz:-LU4m6J68fM_80AQh3df:bwxqe2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/utils_test.go#L273)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Hmm I'm not too sure how to get around this since the outer branch matches the bottom else. Any ideas?
</blockquote></details>

I'm not too sure what you mean. I was wondering if you could e.g. use `DeepEqual` even if the values were nil.


<!-- Sent from Reviewable.io -->

2018-12-19 09:31 UTC, asubiotto commented
BTW, I pulled, rebased this onto master, fixed conflicts and force-pushed to remove the null handling commit and pick the one up from master, so you might have to do a `git reset --hard` before making any changes.

2018-12-19 16:41 UTC, changangela reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-tA6X05qcbqvWPtT6:-LU6KrIy89imcqFGhiCn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L94)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe you could just have the `Null` variants take in a `uint64`? But that would mean you need to cast the current uses. Try it out, and if it becomes tedious, you could leave these in but at least have the original Null methods cast to uint64 and call out to the uint64 methods. It's unfortunate that we've limited ourselves with uint16s here.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colvec.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU-uWlz5LR_T-hW1jyj:-LU6KjNs-sAiZD-KAFFz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/582417dc7ea41d9986cd5a616fecec974fe124f8/pkg/sql/exec/colvec.go#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I believe copy returns the number of elements copied, which you could keep track of in a loop where you do a `ColBatchSize` copy every iteration, using the number of elements copied as an index into the destination slice up to the condition where you've copied as many times as `m.nulls` is large.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-19 16:59 UTC, asubiotto approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 171 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU6Op40E23UJJlH1mU2:-LU6Op40E23UJJlH1mU3:bokp31s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0482617a718eb9a38a5b22c138c89f796de3477a/pkg/sql/exec/colvec.go#L171)):*
> ```Go
> 	for startIdx < len(m.nulls) {
> 		copy(m.nulls[startIdx:], zeroedNulls[:])
> 		startIdx += len(zeroedNulls)
> ```

Since `copy` returns the number of elements copied I think you can do:
```
startIdx += copy(m.nulls[startIdx:], zeroedNulls[:])
```


<!-- Sent from Reviewable.io -->

2018-12-19 17:04 UTC, changangela reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-:-LU6QES03JgNezI1jUdF:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 171 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/32836#-LU6Op40E23UJJlH1mU2:-LU6QDbt-Acz4uG5mZO1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0482617a718eb9a38a5b22c138c89f796de3477a/pkg/sql/exec/colvec.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since `copy` returns the number of elements copied I think you can do:
```
startIdx += copy(m.nulls[startIdx:], zeroedNulls[:])
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-19 17:41 UTC, merged