storage: replace CommandQueue with spanlatch.Manager
cockroachdb/cockroach pull request #32865
Opened 2018-12-05 20:11 UTC by nvanbenschoten

This commit replaces the CommandQueue with the spanlatch.Manager, which was introduced in #31997. See that PR for an introduction to how the structure differs from the CommandQueue and how it improves performance on microbenchmarks.

This is mostly a mechanical change. One important detail is that it removes the CommandQueue debug change. We found that the page was buggy (or straight up broken) and it wasn't actively used by members of Core when debugging problems. In its place, the commit revives the "slow requests" metric for latching, which hasn't been hooked up in over a year.

### Benchamrks

#### Standard Benchmarks

These benchmarks are standard benchmarks that we commonly run. They were run with varying node sizes, cluster sizes, and pre-split counts.

```
name                              old ops/sec  new ops/sec  delta
kv0/cores=4/nodes=1/splits=0       1.99k ± 2%   2.06k ± 1%   +3.22%  (p=0.008 n=5+5)
kv0/cores=4/nodes=1/splits=100     2.25k ± 1%   2.38k ± 1%   +6.01%  (p=0.008 n=5+5)
kv0/cores=4/nodes=3/splits=0       1.60k ± 0%   1.69k ± 2%   +5.53%  (p=0.008 n=5+5)
kv0/cores=4/nodes=3/splits=100     3.52k ± 6%   3.65k ± 9%     ~     (p=0.421 n=5+5)
kv0/cores=16/nodes=1/splits=0      19.9k ± 1%   21.8k ± 1%   +9.34%  (p=0.008 n=5+5)
kv0/cores=16/nodes=1/splits=100    24.4k ± 1%   26.1k ± 1%   +7.17%  (p=0.008 n=5+5)
kv0/cores=16/nodes=3/splits=0      14.9k ± 1%   16.1k ± 1%   +8.03%  (p=0.008 n=5+5)
kv0/cores=16/nodes=3/splits=100    20.6k ± 1%   22.8k ± 1%  +10.79%  (p=0.008 n=5+5)
kv0/cores=36/nodes=1/splits=0      31.2k ± 2%   35.3k ± 1%  +13.28%  (p=0.008 n=5+5)
kv0/cores=36/nodes=1/splits=100    45.7k ± 1%   51.1k ± 1%  +11.80%  (p=0.008 n=5+5)
kv0/cores=36/nodes=3/splits=0      23.7k ± 2%   27.1k ± 2%  +14.39%  (p=0.008 n=5+5)
kv0/cores=36/nodes=3/splits=100    34.9k ± 2%   45.1k ± 1%  +29.44%  (p=0.008 n=5+5)
kv95/cores=4/nodes=1/splits=0      12.7k ± 2%   12.9k ± 2%   +1.39%  (p=0.151 n=5+5)
kv95/cores=4/nodes=1/splits=100    12.8k ± 2%   13.1k ± 2%   +2.10%  (p=0.032 n=5+5)
kv95/cores=4/nodes=3/splits=0      10.6k ± 1%   10.8k ± 1%   +1.58%  (p=0.056 n=5+5)
kv95/cores=4/nodes=3/splits=100    12.3k ± 7%   12.6k ± 8%   +2.61%  (p=0.095 n=5+5)
kv95/cores=16/nodes=1/splits=0     50.9k ± 1%   52.2k ± 1%   +2.37%  (p=0.008 n=5+5)
kv95/cores=16/nodes=1/splits=100   52.2k ± 1%   53.0k ± 1%   +1.49%  (p=0.008 n=5+5)
kv95/cores=16/nodes=3/splits=0     46.2k ± 1%   46.8k ± 1%   +1.32%  (p=0.032 n=5+5)
kv95/cores=16/nodes=3/splits=100   51.0k ± 1%   53.2k ± 1%   +4.25%  (p=0.008 n=5+5)
kv95/cores=36/nodes=1/splits=0     79.8k ± 2%  101.6k ± 1%  +27.31%  (p=0.008 n=5+5)
kv95/cores=36/nodes=1/splits=100    104k ± 1%    107k ± 1%   +2.60%  (p=0.008 n=5+5)
kv95/cores=36/nodes=3/splits=0     85.8k ± 1%   91.8k ± 1%   +7.08%  (p=0.008 n=5+5)
kv95/cores=36/nodes=3/splits=100    106k ± 1%    112k ± 1%   +5.51%  (p=0.008 n=5+5)

name                              old p50(ms)  new p50(ms)  delta
kv0/cores=4/nodes=1/splits=0        3.52 ± 5%    3.40 ± 0%   -3.41%  (p=0.016 n=5+4)
kv0/cores=4/nodes=1/splits=100      3.30 ± 0%    3.00 ± 0%   -9.09%  (p=0.008 n=5+5)
kv0/cores=4/nodes=3/splits=0        4.70 ± 0%    4.14 ± 9%  -11.91%  (p=0.008 n=5+5)
kv0/cores=4/nodes=3/splits=100      1.50 ± 0%    1.48 ± 8%     ~     (p=0.968 n=4+5)
kv0/cores=16/nodes=1/splits=0       1.40 ± 0%    1.40 ± 0%     ~     (all equal)
kv0/cores=16/nodes=1/splits=100     1.20 ± 0%    1.20 ± 0%     ~     (all equal)
kv0/cores=16/nodes=3/splits=0       2.00 ± 0%    1.90 ± 0%   -5.00%  (p=0.000 n=5+4)
kv0/cores=16/nodes=3/splits=100     1.40 ± 0%    1.40 ± 0%     ~     (all equal)
kv0/cores=36/nodes=1/splits=0       1.76 ± 3%    1.60 ± 0%   -9.09%  (p=0.008 n=5+5)
kv0/cores=36/nodes=1/splits=100     1.40 ± 0%    1.30 ± 0%   -7.14%  (p=0.008 n=5+5)
kv0/cores=36/nodes=3/splits=0       2.56 ± 2%    2.40 ± 0%   -6.25%  (p=0.000 n=5+4)
kv0/cores=36/nodes=3/splits=100     1.70 ± 0%    1.40 ± 0%  -17.65%  (p=0.008 n=5+5)
kv95/cores=4/nodes=1/splits=0       0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=4/nodes=1/splits=100     0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=4/nodes=3/splits=0       0.60 ± 0%    0.60 ± 0%     ~     (all equal)
kv95/cores=4/nodes=3/splits=100     0.60 ± 0%    0.60 ± 0%     ~     (all equal)
kv95/cores=16/nodes=1/splits=0      0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=16/nodes=1/splits=100    0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=16/nodes=3/splits=0      0.70 ± 0%    0.64 ± 9%   -8.57%  (p=0.167 n=5+5)
kv95/cores=16/nodes=3/splits=100    0.60 ± 0%    0.60 ± 0%     ~     (all equal)
kv95/cores=36/nodes=1/splits=0      0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=36/nodes=1/splits=100    0.50 ± 0%    0.50 ± 0%     ~     (all equal)
kv95/cores=36/nodes=3/splits=0      0.66 ± 9%    0.60 ± 0%   -9.09%  (p=0.167 n=5+5)
kv95/cores=36/nodes=3/splits=100    0.60 ± 0%    0.60 ± 0%     ~     (all equal)

name                              old p99(ms)  new p99(ms)  delta
kv0/cores=4/nodes=1/splits=0        11.0 ± 0%    10.5 ± 0%   -4.55%  (p=0.000 n=5+4)
kv0/cores=4/nodes=1/splits=100      7.90 ± 0%    7.60 ± 0%   -3.80%  (p=0.000 n=5+4)
kv0/cores=4/nodes=3/splits=0        15.7 ± 0%    15.2 ± 0%   -3.18%  (p=0.008 n=5+5)
kv0/cores=4/nodes=3/splits=100      8.90 ± 0%    8.12 ± 3%   -8.76%  (p=0.016 n=4+5)
kv0/cores=16/nodes=1/splits=0       3.46 ± 2%    3.00 ± 0%  -13.29%  (p=0.000 n=5+4)
kv0/cores=16/nodes=1/splits=100     4.50 ± 0%    3.36 ± 2%  -25.33%  (p=0.008 n=5+5)
kv0/cores=16/nodes=3/splits=0       4.50 ± 0%    3.90 ± 0%  -13.33%  (p=0.008 n=5+5)
kv0/cores=16/nodes=3/splits=100     5.80 ± 0%    4.10 ± 0%  -29.31%  (p=0.029 n=4+4)
kv0/cores=36/nodes=1/splits=0       6.80 ± 0%    5.20 ± 0%  -23.53%  (p=0.008 n=5+5)
kv0/cores=36/nodes=1/splits=100     5.80 ± 0%    4.32 ± 4%  -25.52%  (p=0.008 n=5+5)
kv0/cores=36/nodes=3/splits=0       7.72 ± 2%    6.30 ± 0%  -18.39%  (p=0.000 n=5+4)
kv0/cores=36/nodes=3/splits=100     7.98 ± 2%    5.20 ± 0%  -34.84%  (p=0.000 n=5+4)
kv95/cores=4/nodes=1/splits=0       5.38 ± 3%    5.20 ± 0%   -3.35%  (p=0.167 n=5+5)
kv95/cores=4/nodes=1/splits=100     5.00 ± 0%    5.00 ± 0%     ~     (all equal)
kv95/cores=4/nodes=3/splits=0       5.68 ± 3%    5.50 ± 0%   -3.17%  (p=0.095 n=5+4)
kv95/cores=4/nodes=3/splits=100     3.60 ±31%    2.93 ± 3%  -18.75%  (p=0.016 n=5+4)
kv95/cores=16/nodes=1/splits=0      4.10 ± 0%    4.10 ± 0%     ~     (all equal)
kv95/cores=16/nodes=1/splits=100    4.50 ± 0%    4.10 ± 0%   -8.89%  (p=0.000 n=5+4)
kv95/cores=16/nodes=3/splits=0      2.60 ± 0%    2.60 ± 0%     ~     (all equal)
kv95/cores=16/nodes=3/splits=100    2.50 ± 0%    1.90 ± 5%  -24.00%  (p=0.008 n=5+5)
kv95/cores=36/nodes=1/splits=0      6.60 ± 0%    6.00 ± 0%   -9.09%  (p=0.029 n=4+4)
kv95/cores=36/nodes=1/splits=100    5.50 ± 0%    5.12 ± 2%   -6.91%  (p=0.008 n=5+5)
kv95/cores=36/nodes=3/splits=0      4.18 ± 2%    4.02 ± 3%   -3.71%  (p=0.000 n=4+5)
kv95/cores=36/nodes=3/splits=100    3.80 ± 0%    2.80 ± 0%  -26.32%  (p=0.008 n=5+5)
```

#### Large-machine Benchmarks

These benchmarks are standard benchmarks run on a single-node cluster with 72 vCPUs.

```
name                              old ops/sec  new ops/sec  delta
kv0/cores=72/nodes=1/splits=0      31.0k ± 4%   36.4k ± 1%  +17.57%  (p=0.008 n=5+5)
kv0/cores=72/nodes=1/splits=100    44.0k ± 0%   49.0k ± 1%  +11.41%  (p=0.008 n=5+5)
kv95/cores=72/nodes=1/splits=0     52.7k ±18%   72.6k ±26%  +37.70%  (p=0.016 n=5+5)
kv95/cores=72/nodes=1/splits=100   66.8k ±17%   68.5k ± 5%     ~     (p=0.286 n=5+4)

name                              old p50(ms)  new p50(ms)  delta
kv0/cores=72/nodes=1/splits=0       2.30 ±13%    2.52 ± 5%     ~     (p=0.214 n=5+5)
kv0/cores=72/nodes=1/splits=100     3.00 ± 0%    2.90 ± 0%   -3.33%  (p=0.008 n=5+5)
kv95/cores=72/nodes=1/splits=0      0.46 ±13%    0.50 ± 0%     ~     (p=0.444 n=5+5)
kv95/cores=72/nodes=1/splits=100    0.44 ±14%    0.50 ± 0%  +13.64%  (p=0.167 n=5+5)

name                          [...]

2018-12-05 20:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/32865)
<!-- Reviewable:end -->

2018-12-06 17:55 UTC, ajwerner requested changes
LGTM! excited to see the numbers

> Reviewed 31 of 31 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-:-LT3e7eP0BIbY492wXcc:bv6qn7r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3cNIy3W_-YsiJXF5W:-LT3cNIz4-E1TbIQulYc:b20cczi) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/replica.go#L2400)):*
> ```Go
> 		}
> 
> 		if beforeLatch != (time.Time{}) {
> ```

! https://golang.org/pkg/time/#Time.IsZero ?


<!-- Sent from Reviewable.io -->

2018-12-06 17:55 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-:-LT3eETQ4dGGM2ZGXTiP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-06 18:40 UTC, vilterp approved these changes
LGTM on command queue page removal.

2018-12-06 18:40 UTC, vilterp commented on pkg/storage/metrics.go
>  	metaSlowCommandQueueRequests = metric.Metadata{
nit: change this variable name

2018-12-06 18:55 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I appreciate you going the extra mile in removing all references to command queue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-:-LT3rxsB7kalmvYpvZYN:b-paf4zd)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/server/status/health_check.go, line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3hgOA7KaVzqM2oYlw:-LT3hgOA7KaVzqM2oYlx:bc4kmp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/server/status/health_check.go#L53)):*
> ```Go
> 	"ranges.underreplicated":      gaugeZero,
> 	"requests.backpressure.split": gaugeZero,
> 	"requests.slow.latch":         gaugeZero,
> ```

That makes so much more sense.
___
*[pkg/storage/replica.go, line 2347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3hyue9h5lwdMC2NgG:-LT3hyue9h5lwdMC2NgH:bvjzva9) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/replica.go#L2347)):*
> ```Go
> 
> 	// With clockless reads, everything is treated as a write.
> 	clockless := r.store.Clock().MaxOffset() == timeutil.ClocklessMaxOffset
> ```

I thought we removed support for clockless mode. @tbg?
___
*[pkg/storage/replica_test.go, line 3405 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3iCQmAccqVPRhrGng:-LT3iCQmAccqVPRhrGnh:bt1bew) ([raw file](https://github.com/cockroachdb/cockroach/blob/60fa2606d93064baa6cba82cdf45d1300ba5ed8d/pkg/storage/replica_test.go#L3405)):*
> ```Go
> // TestReplicaCommandQueuePrereqDebugSummary tests the debug summary logged
> // about a request's prerequisites when entering the command queue.
> func TestReplicaCommandQueuePrereqDebugSummary(t *testing.T) {
> ```

I assume all of these tests are being moved elsewhere.


<!-- Sent from Reviewable.io -->

2018-12-07 09:23 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-:-LT6ykHf1ygWTnKTr_F8:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 2347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3hyue9h5lwdMC2NgG:-LT6xtsVD0-yRaXg0013:bi3xuh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/replica.go#L2347)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I thought we removed support for clockless mode. @tbg?
</blockquote></details>

Might still be in the code, but you definitely don't have to add code that maintains it. Needs to be ripped out.


<!-- Sent from Reviewable.io -->

2018-12-08 00:48 UTC, nvb reviewed
Thanks for all the reviews!

> I appreciate you going the extra mile in removing all references to command queue.

Not really the extra mile, I just never want to hear that name again.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-:-LTAH6MLEwNFn2ZDvLVs:bn0qry2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[pkg/storage/metrics.go, line 875 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LSzzs68ESoaPH31rZ0J-r3-875:-LTAFI1z24L-fjZd37TA:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/metrics.go#L875)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

nit: change this variable name
</blockquote></details>

Good catch, done.
___
*[pkg/storage/replica.go, line 2347 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3hyue9h5lwdMC2NgG:-LTAFQfG1lBo_8Dp_u7b:bv2c8ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/replica.go#L2347)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Might still be in the code, but you definitely don't have to add code that maintains it. Needs to be ripped out.
</blockquote></details>

Done.

Is there a discussion on why we removed clockless mode? Was it related to leases and their expiration?
___
*[pkg/storage/replica.go, line 2400 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3cNIy3W_-YsiJXF5W:-LTAG32nD5R841ZH5Ue0:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/81626620f3b7f902a7665fba2149113bc1fa7887/pkg/storage/replica.go#L2400)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

! https://golang.org/pkg/time/#Time.IsZero ?
</blockquote></details>

Nice, done.
___
*[pkg/storage/replica_test.go, line 3405 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32865#-LT3iCQmAccqVPRhrGng:-LTAG4b98XwGe551p1ip:b-1fmutv) ([raw file](https://github.com/cockroachdb/cockroach/blob/60fa2606d93064baa6cba82cdf45d1300ba5ed8d/pkg/storage/replica_test.go#L3405)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I assume all of these tests are being moved elsewhere.
</blockquote></details>

All of the tests that we still need were either already moved to the `storage/spanlatch` package or are renamed in this commit. This is deleting a few tests around command cancellation while waiting in the CommandQueue because the equivalent action is significantly simpler now that we no longer build explicit dependency trees. b81216e added a few new tests in `storage/spanlatch` that test exactly that.


<!-- Sent from Reviewable.io -->

2018-12-08 01:10 UTC, merged