roachtest: add support for testSpec.Manual
cockroachdb/cockroach pull request #33139
Opened 2018-12-13 19:05 UTC by petermattis

A manual test only matches when a filter is supplied. This makes
`roachtest run` have different behavior than `roachtest run .`. This will
be used by weekly tests to prevent them from being run nightly.

Release note: None

2018-12-13 19:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/33139)
<!-- Reviewable:end -->

2018-12-13 19:08 UTC, petermattis commented
Now that I've written this, I think it is too subtle. I'd prefer to have something on `testSpec` that is more explicit, such as a `testSpec.Tag`.

2018-12-13 19:11 UTC, andreimatei requested changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-:-LTcyeZdEmNevjzVq785:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/test.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTcy0LQCfEDFlXiS5Ja:-LTcy0LRDV187_xnEPhZ:bvl4qt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/63446ffb605bc9586b91364179762b7484546aca/pkg/cmd/roachtest/test.go#L49)):*
> ```Go
> )
> 
> type testFilter struct {
> ```

comment on the struct pls


<!-- Sent from Reviewable.io -->

2018-12-13 19:11 UTC, andreimatei approved these changes

2018-12-13 19:57 UTC, petermattis commented
Added a 3rd commit which implements `testSpec.Tag`. I like the ergonomics of this better. I'll squash the 2nd and 3rd commit before merging.

2018-12-13 20:27 UTC, andreimatei requested changes
So with r3, if I run `roachtest run WeeklyTest`, does my test run or not?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-:-LTdDKEPB2m5UbPBTa7b:bqc6p6h)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/main.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTdD1jx4sdsNLfD16QL:-LTdD1jyEF0OMtOi6k5s:bftaych) ([raw file](https://github.com/cockroachdb/cockroach/blob/f194865330901d4881e2b1ff6f04010230413bf8/pkg/cmd/roachtest/main.go#L88)):*
> ```Go
> Use --bench to list benchmarks instead of tests.
> 
> The --tag flag can be used as alternative means of filtering the tests, but
> ```

how does --tag and names compose? Can one use both?


<!-- Sent from Reviewable.io -->

2018-12-13 20:31 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/main.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTdD1jx4sdsNLfD16QL:-LTdFsyaD62hSdI8tSat:bsfwtki) ([raw file](https://github.com/cockroachdb/cockroach/blob/f194865330901d4881e2b1ff6f04010230413bf8/pkg/cmd/roachtest/main.go#L88)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how does --tag and names compose? Can one use both?
</blockquote></details>

That --tag filter and name filters are intersected. For example, `roachtest list --tag !acceptance acceptance` will return 0 results.


<!-- Sent from Reviewable.io -->

2018-12-13 20:38 UTC, andreimatei commented
So this means that the answer to the other question (So with r3, if I run roachtest run WeeklyTest, does my test run or not?) is that the test doesn't run? If so, I don't like it r3 - you're making a magic tag "weekly".

I think the sane thing is the manual tag with clear semantics about what that does to regexp expansion (so `roachtest run` and `roachtest run .` are the same), plus an `--ignore-manual` flag.

Feel free to merge if you disagree, but please document the intersection of the flags better if you do.

2018-12-13 20:47 UTC, petermattis commented
> So this means that the answer to the other question (So with r3, if I run roachtest run WeeklyTest, does my test run or not?) is that the test doesn't run? If so, I don't like it r3 - you're making a magic tag "weekly".

If "WeeklyTest" has the "weekly" tag, then `roachtest run WeeklyTest` will not run the test because that is equivalent to `roachtest run --tag !weekly WeeklyTest`. (The default for the `--tag` flag is `!weekly`). 

An `--include-manual` flag is a bit odd, because what makes the test "manual".

2018-12-13 20:52 UTC, andreimatei commented
> An --include-manual flag is a bit odd, because what makes the test "manual".

Not sure how to parse this sentence. The bool field in `r2` is what makes the test "manual"...
And perhaps s/manual/noGlob everywhere.

2018-12-13 20:56 UTC, andreimatei commented
This reminded me of something. In my previous information retrieval team, there was a concept of "cross-matching" - you had queries that retrieved documents (actually, documents that retrieved queries), but elements in your index could also run their own little matching criteria - so the documents would select the queries and the selected queries could reject to be retrieved.
The noGlob is such a cross-match algorithm.

2018-12-13 21:00 UTC, petermattis commented
Yet with `--include-manual`, the query itself becomes more complex. Or perhaps that is a `--no-glob` or `--no-regexp`. Even, so the ergonomics seem awkward. In order to run the weekly tests I have to do `roachtest run --no-regexp my-weekly-test-name`? Seems preferable to have a group of tests tagged "weekly" and then do `roachtest run --tag weekly`.

2018-12-14 14:01 UTC, petermattis commented
@andreimatei I've reworked this again. `roachtest run WeeklyTest` will now show `WeeklyTest` as skipped if the tag filter doesn't match. Assuming `WeeklyTest` has the tag `weekly`, in order to run it you would do `roachtest run tag:weekly WeeklyTest`.

2018-12-17 23:39 UTC, andreimatei approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-:-LTyXOh2A1WlUg1IGGER:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyX3hn871NCmupGR6_:-LTyX3hn871NCmupGR6a:b-u3wrn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a640dc0a1e947228ef99aac77df2b261e3db756/pkg/cmd/roachtest/acceptance.go#L55)):*
> ```Go
> 		},
> 	}
> 	tags := []string{"default", "acceptance"}
> ```

If you name the tag "acceptance", it's hard to know when to apply this tag (or easy, but wrong IMHO :)).
How about a "quick" tag. And separately, a pseudo-tag of some sort for filtering tests that can run locally. And those two would be used by TC on every PR.
___
*[pkg/cmd/roachtest/test.go, line 415 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyWTsMAT8XPgGI-1UT:-LTyWTsMAT8XPgGI-1UU:b1pg4v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/960e7b67d3eec3b7906727446e8526451446fcce/pkg/cmd/roachtest/test.go#L415)):*
> ```Go
> 	// Find the top-level tests to run.
> 	tests := r.ListTopLevel(filter)
> 	if len(tests) == 0 {
> ```

I think we should exit with a non-zero code here.
Also, if a filter is set, it'd be cool for the message to say something about it.


<!-- Sent from Reviewable.io -->

2018-12-18 00:45 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyX3hn871NCmupGR6_:-LTyjgRd0tbAgWxqIpe6:bkmucsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a640dc0a1e947228ef99aac77df2b261e3db756/pkg/cmd/roachtest/acceptance.go#L55)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If you name the tag "acceptance", it's hard to know when to apply this tag (or easy, but wrong IMHO :)).
How about a "quick" tag. And separately, a pseudo-tag of some sort for filtering tests that can run locally. And those two would be used by TC on every PR.
</blockquote></details>

Ok, renamed `acceptance` to `quick`. Not sure how to implement the `local` pseudo tag? Did you have thoughts about that?
___
*[pkg/cmd/roachtest/test.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTcy0LQCfEDFlXiS5Ja:-LTyjuroDLEUNcl3n9J6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63446ffb605bc9586b91364179762b7484546aca/pkg/cmd/roachtest/test.go#L49)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment on the struct pls
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/test.go, line 415 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyWTsMAT8XPgGI-1UT:-LTyjvrX46je0Ru7hLLE:bx4nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/960e7b67d3eec3b7906727446e8526451446fcce/pkg/cmd/roachtest/test.go#L415)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we should exit with a non-zero code here.
Also, if a filter is set, it'd be cool for the message to say something about it.
</blockquote></details>

Done and done.


<!-- Sent from Reviewable.io -->

2018-12-18 01:39 UTC, petermattis commented
bors r=andreimatei

2018-12-18 01:59 UTC, merged

2018-12-18 03:32 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyX3hn871NCmupGR6_:-LTzMNrFBXtPGgtGbwOh:b-w8mb2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a640dc0a1e947228ef99aac77df2b261e3db756/pkg/cmd/roachtest/acceptance.go#L55)):*
> Not sure how to implement the local pseudo tag? Did you have thoughts about that?

Well, the burden must fall on either the tag consumer or on the tag provider to handle this magic tag. I'd put it on the provider - make a `testSpec.Tags()` method that conditionally appends `local` to the list of flags returned.


<!-- Sent from Reviewable.io -->

2018-12-18 14:11 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33139)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/acceptance.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33139#-LTyX3hn871NCmupGR6_:-LU0dbhP7CnMv6AZonVX:bxtg36k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a640dc0a1e947228ef99aac77df2b261e3db756/pkg/cmd/roachtest/acceptance.go#L55)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Not sure how to implement the local pseudo tag? Did you have thoughts about that?

Well, the burden must fall on either the tag consumer or on the tag provider to handle this magic tag. I'd put it on the provider - make a `testSpec.Tags()` method that conditionally appends `local` to the list of flags returned.
</blockquote></details>

What is the condition to decide when to append `local`? A `testSpec` currently doesn't know if a test can operate locally. We could certainly add that, though it seems very similar to adding a `local` tag itself. Most tests work fine locally.


<!-- Sent from Reviewable.io -->