roachtest: create new kv/contention/nodes=4 test
cockroachdb/cockroach pull request #33290
Opened 2018-12-19 23:35 UTC by nvanbenschoten

Closes #32814.

This commit adds a roachtest that stresses the kinds of scenarios that we saw bring down adriatic in #32582. It runs `kv` with a cycle length of 512, a concurrency of 128, and a batch size of 4. The test runs this on a 4 node cluster. It then verifies that QPS stayed above a certain threshold for the entire duration of the test.

2018-12-19 23:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/33290)
<!-- Reviewable:end -->

2018-12-20 09:14 UTC, tbg requested changes
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33290)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/kv.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33290#-LU9tHGR6woy6uZvECOS:-LU9tHGS5w7_XhPr8CHl:bljycya) ([raw file](https://github.com/cockroachdb/cockroach/blob/41ac4ddd0ba9a1f9e87c12334af18ccf47576cc6/pkg/cmd/roachtest/kv.go#L117)):*
> ```Go
> 				// threshold.
> 				const minQPS = 10
> 				verifyTxnPerSecond(ctx, c, t, c.Node(1), start, end, minQPS, 0.05)
> ```

Could you comment on the 0.05?


<!-- Sent from Reviewable.io -->

2018-12-20 09:14 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33290#-:-LU9tL5g8xRjGxf_bb0E:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-20 15:00 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33290#-:-LUAo_cqAEvsT85J7Lhj:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-02-08 20:02 UTC, nvanbenschoten commented
bors r+

2019-02-08 20:33 UTC, merged