sql/opt: avoid swallowing TransactionAbortedErrors
cockroachdb/cockroach pull request #33312
Opened 2018-12-21 00:14 UTC by benesch

An optimizer code path could, in rare cases, fail to propagate a
transaction aborted error. This proved disastrous as, due to a footgun
in our transaction API (#22615), swallowing a transaction aborted error
results in proceeding with a brand new transaction that has no knowledge
of the earlier operations performed on the original transaction.

This presented as a rare and confusing bug in splits, as the split
transaction uses an internal executor. The internal executor would
occasionally silently return a new transaction that only had half of the
necessary operations performed on it, and committing that partial
transaction would result in a "range does not match splits" error.

Fixes #32784.

Release note: None

/cc @tbg

2018-12-21 00:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/33312)
<!-- Reviewable:end -->

2018-12-21 01:11 UTC, RaduBerinde reviewed
Wow, what a subtle issue.. Awesome find, that couldn't have been easy to figure out!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-:-LUDICHW4a3qxOEVCmXR:b-fka81k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan.go, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDGpN67gdYJu11b41f:-LUDGpN67gdYJu11b41g:b9jm7h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/plan.go#L442)):*
> ```Go
> 		// If the prepared memo has been invalidated by schema or other changes,
> 		// re-prepare it.
> 		if ok, err := stmt.Prepared.Memo.IsStale(ctx, p.EvalContext(), &catalog); err != nil {
> ```

`s/ok/isStale` (same below)
___
*[pkg/sql/plan.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDH8Xo-_Gh9quXhcsj:-LUDH8Xo-_Gh9quXhcsk:bvd55uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/plan.go#L444)):*
> ```Go
> 		if ok, err := stmt.Prepared.Memo.IsStale(ctx, p.EvalContext(), &catalog); err != nil {
> 			return 0, err
> 		} else if !ok {
> ```

inverse check, should be `if isStale`
___
*[pkg/sql/opt/memo/memo.go, line 249 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDHF0s48M3Af4395A4:-LUDHF0s48M3Af4395A5:bt9rd2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/opt/memo/memo.go#L249)):*
> ```Go
> //   5. Data source privileges: current user may no longer have access to one or
> //      more data sources.
> //
> ```

I would add a comment about the error, that it can be associated with the transaction and has to be propagated (or something to that effect). Same for CheckDependencies
___
*[pkg/sql/opt/memo/memo.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDGmOxEpwaIy1gysrj:-LUDGmOxEpwaIy1gysrk:bof0c2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/opt/memo/memo.go#L271)):*
> ```Go
> 	// has changed, or if the current user no longer has sufficient privilege to
> 	// access the data source.
> 	return m.Metadata().CheckDependencies(ctx, catalog)
> ```

this should return the inverse of what CheckDeps returns. Or you can invert the function and rename to `CheckStaleness`


<!-- Sent from Reviewable.io -->

2018-12-21 09:40 UTC, tbg reviewed
:sweat: thanks for finding this before we had to find it in the wild. #22615 seems well worth doing.
I'll defer to @raduberinde on the final LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-:-LUF7MND593TEssLU-vH:biapqgs)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-28 14:14 UTC, tbg commented
I think this would also fix https://github.com/cockroachdb/cockroach/issues/33375.

2019-01-01 17:33 UTC, andy-kimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, nice find. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-:-LV9T7Dg8JH8cgF-OzpW:bddva5l)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-01-01 18:57 UTC, benesch commented
> Also, will this need to be back-ported to 2.1?

We'll definitely want to consider backporting. On the one hand there's no evidence that this bug can manifest without merges turned on, but on the other hand there is a good chance that there is some way to trigger it with merges turned off that I haven't thought of.

@andy-kimball @RaduBerinde I could actually use your advice on how to fix this test failure. This is the failure in question:

```
EXECUTE change_view
expected "pq: relation \"otherview\" does not exist", but found "pq: relation \"otherdb.public.otherview\" does not exist"
```

The logictest renames `otherview` to `otherview2`, then executes a prepared statement that references the view by its old name. Previously, `IsStale` would return `true` so that the query would be replanned in light of the new name of the view, and the replanning would fail with `relation "otherview" does not exist`, using the non-qualified name "otherview" because that's how the name is specified in the `change_view` prepared query.

Unfortunately, now `IsStale` returns the `relation does not exist` error directly. The optimizer always uses fully-qualified names in its memo, and the error message thus uses the fully-qualified name: `relation "otherdb.public.otherview" does not exist`.

I can't just change the test to expect the fully-qualified name because then it fails in the reverse direction, i.e., when the optimizer is turned off. The only thing I've come up with is teaching IsStale to return `true, nil` if it detects an undefined relation error, so that query continues to planning where it can fail with the proper undefined relation error. This seems kind of gross. Do either of you have a better suggestion?

2019-01-01 18:58 UTC, benesch commented
I suppose we could also declare that we don't care about whether the error message uses the fully-qualified name or not, and adjust the logictest accordingly.

2019-01-01 21:43 UTC, rytaft commented
The logic tests allow you to specify two possible error messages since it's just a regex. We've done this in other places: https://github.com/cockroachdb/cockroach/blob/a8afcabd753eff930f2f1fef5e79718439fbf65a/pkg/sql/logictest/testdata/logic_test/insert#L642





<!-- Sent from Reviewable.io -->

2019-01-02 15:06 UTC, benesch commented
Oh, fantastic! Done. PTAL.

2019-01-02 18:15 UTC, andreimatei requested changes
> I can't just change the test to expect the fully-qualified name because then it fails in the reverse direction, i.e., when the optimizer is turned off. 


Have you tried to unify the error between the two paths?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-:-LVElXhyEqpPyBMQddJ2:b-1soltu)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/internal_test.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVES2f6DIIqF-aEkjRQ:-LVES2f6DIIqF-aEkjRR:b-h22vp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L305)):*
> ```Go
> // Note that a fix to our transaction API to eliminate this class of errors is
> // proposed in #22615.
> func TestInternalExecutorTxnAbortNotSwallowed(t *testing.T) {
> ```

Let's talk about this test. The bug this patch is fixing is in the optimizer, not in the internal executor. The test's comment claims otherwise. I don't think this test is warranted... Is it? At the very least please add more words.

If you keep it, consider using `TxnAborter` instead of what you're doing.
___
*[pkg/sql/internal_test.go, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVEkxlP3SfWFJC3Y7Rl:-LVEkxlP3SfWFJC3Y7Rm:bcfxv93) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L317)):*
> ```Go
> 				if r.GetHeartbeatTxn() != nil && br.Responses[i].GetHeartbeatTxn().Txn.Status == roachpb.ABORTED {
> 					go func() {
> 						heartbeatSawAbortedTxn <- ba.Txn.ID
> ```

please comment on why the distinction between a heartbeat finding out that a txn was aborted versus the commit finding out about the abort is important.
___
*[pkg/sql/internal_test.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVElDUC847ue7fGnnxe:-LVElDUC847ue7fGnnxf:b-gpwwqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L380)):*
> ```Go
> 		t.Fatalf("expected query execution on aborted txn to fail, but got %+v", err)
> 	}
> }
> ```

don't forget to rollback the txn :) That's the contract.


<!-- Sent from Reviewable.io -->

2019-01-03 04:51 UTC, benesch reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/plan.go, line 444 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDH8Xo-_Gh9quXhcsj:-LUEFcFr1_x1jBVsJcJn:b-m43f9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/plan.go#L444)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

inverse check, should be `if isStale`
</blockquote></details>

:man_facepalming: thanks, done.
___
*[pkg/sql/opt/memo/memo.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LUDGmOxEpwaIy1gysrj:-LUEFoDvBEBzu6lDzfkF:b-onultl) ([raw file](https://github.com/cockroachdb/cockroach/blob/164956526e47e5aa8e90d8a652226ef85b3607dc/pkg/sql/opt/memo/memo.go#L271)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this should return the inverse of what CheckDeps returns. Or you can invert the function and rename to `CheckStaleness`
</blockquote></details>

Wow, I was really asleep at the wheel here. Thanks. Fixed.
___
*[pkg/sql/internal_test.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVES2f6DIIqF-aEkjRQ:-LVH1m1x0xecGwHF7YYc:b-uukb08) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L305)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Let's talk about this test. The bug this patch is fixing is in the optimizer, not in the internal executor. The test's comment claims otherwise. I don't think this test is warranted... Is it? At the very least please add more words.

If you keep it, consider using `TxnAborter` instead of what you're doing.
</blockquote></details>

Ok, I'll just remove it. Preserved here just in case: https://gist.github.com/benesch/53203264cf72eb6a1efe9137a306a26f
___
*[pkg/sql/internal_test.go, line 317 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVEkxlP3SfWFJC3Y7Rl:-LVH24og3QrfS_Houejs:baezvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L317)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment on why the distinction between a heartbeat finding out that a txn was aborted versus the commit finding out about the abort is important.
</blockquote></details>

Done. (Test removed.)
___
*[pkg/sql/internal_test.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-LVElDUC847ue7fGnnxe:-LVH25fiDdH_lFSRVABW:baezvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1884eb2725a97764139b3dfe7c86a72687f34df/pkg/sql/internal_test.go#L380)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't forget to rollback the txn :) That's the contract.
</blockquote></details>

Done. (Test removed.)


<!-- Sent from Reviewable.io -->

2019-01-03 16:35 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33312#-:-LVJZVc5C-ROrvmi_Q4h:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)



<!-- Sent from Reviewable.io -->

2019-01-03 16:44 UTC, benesch commented
TFTRs!

bors r+

2019-01-03 17:07 UTC, merged