storage: allow HeartbeatTxn and EndTxn requests to create txn records
cockroachdb/cockroach pull request #33396
Opened 2018-12-28 19:38 UTC by nvanbenschoten

Based on #33257.
Informs #25437.
Informs #32971.

This is the first part of addressing #32971. Part two will update concurrent txns to not immediately abort missing txn records and part three will update the txn client to stop sending BeginTxn records.

The change closely resembles what was laid out in the corresponding RFC sections. `HeartbeatTxn` and `EndTxn` are both updated to permit the creation of transaction records when they finds that one is missing.

To prevent replays from causing issues, they *both* check the write timestamp cache when creating a transaction record. This is one area where the change diverges from the RFC. Instead of having `EndTxn` always check the write timestamp cache, it only does so if it is creating a txn record from scratch. To make this safe, `HeartbeatTxn` also checks the write timestamp cache if it is creating a txn record from scratch. This prevents a long-running transaction from increasingly running the risk of being aborted by a lease transfer as its `EndTxn` continues to be delayed. Instead, a lease transfer will only abort a transaction if it comes before the transaction record creation, which should be within a second of the transaction starting.

The change pulls out a new `CanCreateTxnRecord` method, which has the potential of being useful for detecting eagerly GCed transaction records and solving the major problem from the RFC without an extra QueryIntent. This is what Andrei was pushing for before. More details are included in TODOs within the PR.

### Migration Safety

Most of the changes to the transaction state machine are straightforward to validate. Transaction records can still never be created without checking for replays and only an EndTxn from the client's sync path can GC an ABORTED txn record. This means that it is still impossible for a transaction to move between the two finalized statuses (at some point it would be worth it to draw this state machine).

The one tricky part is ensuring that the changes in this PR are safe when run in mixed-version clusters. The two areas of concern are:
1. lease transfers between a new and an old cluster on a range that
should/does contain a transaction record.
2. an old txn client that is not expecting HeartbeatTxn and EndTxn requests to create txn records if they are found to be missing.
3. an old txn client may not expect a HeartbeatTxn to hit the write timestamp cache if run concurrently with an EndTxn.

The first concern is protected by the write timestamp cache. Regardless of which replica creates that transaction record from a BeginTxn req or a HeartbeatTxn req (on the new replica), it will first need to check the timestamp cache. This prevents against any kind of replay that could create a transaction record that the old replica is not prepared to handle.

We can break the second concern into two parts. First, an old txn client will never send an EndTxn without having sent a successful BeginTxn, so the new behavior there is not an issue. Second, an old txn client may send a HeartbeatTxn concurrently with a BeginTxn. If the heartbeat wins, it will create a txn record on a new replica. If the BeginTxn evaluates on a new replica, it will be a no-op. If it evaluates on an old replica, it will result in a retryable error.

The third concern is specific to the implementation of the heartbeat loop itself. If a HeartbeatTxn loses a race with an EndTxn, it may get an aborted error after checking the timestamp cache. This is  desirable from the replica-side, but we'd need to ensure that the client will handle it correctly. This PR adds some protection (see `sendingEndTxn`) to the txn client to prevent this case from causing weirdness on the client, but I don't think this could actually cause issues even without this protection.
The reason is that the txn client might mark itself as aborted due to the heartbeat, but this will be overwritten when the EndTxn returns and the sql client will still hear back from the successful EndTxn. This must have actually always been an issue because it was always possible for a committed txn record to be GCed and then written as aborted later, at which point a concurrent heartbeat could have observed it.

I'd like Andrei to sign off on this last hazard, as he's thought about this kind of thing more than anybody.

2018-12-28 19:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/33396)
<!-- Reviewable:end -->

2019-01-02 14:56 UTC, tbg reviewed
Looks good! Thanks for breaking this into manageable chunks. As far as I'm concerned adding additional commits (as opposed to massaging the existing ones with feedback) is fine.

I think that for doc purposes, an overview over when the write timestamp cache is supposed to be populated would be useful. I just went back to the RFC and didn't find it there, neither. I think what happens right now on `master` is that EndTransaction updates the write timestamp cache and `BeginTransaction` checks it. (I think) You're going to make it such that "whoever creates the transaction record for the client has to check it (which excludes pushes)".

> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, 5 of 5 files at r3, 2 of 2 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVDo3Jm4Aez70yUviNg:bc42r85)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/txn_interceptor_heartbeat.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDppBf2N44eIpNUxNF:-LVDppBf2N44eIpNUxNG:bfg2fwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/txn_interceptor_heartbeat.go#L267)):*
> ```Go
> 
> 	if haveEndTxn {
> 		h.mu.sendingEndTxn = false
> ```

Isn't this still racy? The EndTxn might return (and we're setting status to COMMITTED), and then an inflight heartbeat returns and we flip to ABORTED?
The reason for resetting here in the first place is that there could've been a transaction retry error, right?
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDqrKu4c_rMfLajVk6:-LVDqrKu4c_rMfLajVk7:bm8uthp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/kv/txn_interceptor_heartbeat.go#L497)):*
> ```Go
> // The asyncAbortCallbackLocked callback is also called.
> func (h *txnHeartbeat) abortTxnAsyncLocked(ctx context.Context) {
> 	// Stop the heartbeat loop if it is still running.
> ```

What's up with this change?
___
*[pkg/roachpb/data.proto, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDkdIVCdACH42lbQXC:-LVDkdIVCdACH42lbQXD:bck3ore) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L380)):*
> ```protobuf
>   // See comments on Transaction proto.
> 	storage.engine.enginepb.TxnMeta meta = 1  [(gogoproto.nullable) = false, (gogoproto.embed) = true];
> 	TransactionStatus status             = 4;
> ```

I think we use spaces instead of tabs in proto files. Or so it seems from the diff.
___
*[pkg/roachpb/data_test.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDl0p6AcU7oFvKFD_9:-LVDl0p6AcU7oFvKFD_A:b3in6zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data_test.go#L566)):*
> ```Go
> 	// strips out fields but is lossless for the desired fields.
> 	txn := nonZeroTxn
> 	txnRecord := txn.AsRecord()
> ```

`assert.NoError(t, zerofields.NoZeroField(&txnRecord)` to keep test from rotting
___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVDmcvN7hpM57pagDRS:b-43g97w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
> ```Go
> 	VersionImportFormats
> 	VersionSecondaryLookupJoins
> 	VersionClientSideWritingFlag // unused
> ```

Always nice to see the final payoff of such a migration.
___
*[pkg/storage/replica_test.go, line 3683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDyY13D17xFPYeWn-W:-LVDyY13D17xFPYeWn-X:bnmvlcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3683)):*
> ```Go
> 	for i, test := range testCases {
> 		// Establish existing txn state by writing directly to range engine.
> 		existTxn := txn.Clone()
> ```

Make this `.AsRecord()`.
___
*[pkg/storage/replica_test.go, line 3799 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDymiP2cMWCRqhKLl6:-LVDymiP2cMWCRqhKLl7:b-2ll8qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3799)):*
> ```Go
> // TestRaftReplayProtectionInTxn verifies that transactional batches
> // enjoy protection from "Raft retries".
> func TestRaftRetryProtectionInTxn(t *testing.T) {
> ```

Hmm, I think the explanation here has rotted. We're protected from "Raft retries" thanks to the lease applied index. I think what we're testing here are RPC-level retries (i.e. DistSender delivers a batch twice).
___
*[pkg/storage/replica_test.go, line 3801 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDyg5OBu4gPG_qgLiU:-LVDyg5OBu4gPG_qgLiV:b-uu4tn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3801)):*
> ```Go
> func TestRaftRetryProtectionInTxn(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	defer setTxnAutoGC(true)()
> ```

This line can go, it was introduced when the default was `false`.
___
*[pkg/storage/replica_test.go, line 3831 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzKeD9Ok_CzaZi22Y:-LVDzKeD9Ok_CzaZi22Z:biisx54) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3831)):*
> ```Go
> 	// transaction, which fails the 1PC path and forces the txn to execute
> 	// normally at which point the WriteTooOld gets indirectly turned into a
> 	// TransactionAbortedError.
> ```

Isn't something fishy here? If this is indeed a real-world RPC retry and the first RPC is the one that gets lost (i.e. the client receives the response from the second one), it'll receive TxnAbortedError even though the first one might've committed the Txn. Is it that DistSender would turn that TxnAbortedError into an ambiguous one?
___
*[pkg/storage/replica_test.go, line 3892 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzac77JbwzX-A2zvF:-LVDzac77JbwzX-A2zvG:b-5fv4ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3892)):*
> ```Go
> }
> 
> // TestRaftRetryCantCommitIntents tests that transactional Raft retries cannot
> ```

Ditto about what we're testing.
___
*[pkg/storage/replica_test.go, line 3901 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzkEq8qsI--w6WPdj:-LVDzkEq8qsI--w6WPdk:b-5u40z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3901)):*
> ```Go
> // the reproposal not execute if the original proposal had already been
> // applied.
> // - in case of Raft *retries*, in most cases we know that the original proposal
> ```

Ah, this is what a Raft retry is. I think @andreimatei is just about to remove this in https://github.com/cockroachdb/cockroach/pull/33381.
___
*[pkg/storage/replica_tscache.go, line 76 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVE-pRdEkSsR-bn2g7x:-LVE-pRdEkSsR-bn2g7y:b-sflujc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_tscache.go#L76)):*
> ```Go
> 				// throughout the transaction.
> 				// TODO(nvanbenschoten): This assumption wouldn't be needed
> 				// if we compared against for the OrigTimestamp. See
> ```

s/for//
___
*[pkg/storage/replica_tscache.go, line 214 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVE0553CnS6KW9k0cUM:-LVE0553CnS6KW9k0cUN:b-eju9c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_tscache.go# [...]

2019-01-02 16:37 UTC, bdarnell reviewed
> Reviewed 2 of 2 files at r1, 12 of 12 files at r2, 5 of 5 files at r3, 2 of 2 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/data.proto, line 371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVEKeT_DwP2M5q1WH1T:-LVEKeT_DwP2M5q1WH1U:b74qaap) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L371)):*
> ```protobuf
> // be persisted in a transaction record. It also serves as a specification
> // for the fields that must be present in a transaction record.
> message TransactionRecord {
> ```

Comment that any changes to this type must be reflected in the AsRecord/AsTransaction methods.
___
*[pkg/storage/replica_tscache.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVEOd7K5nzSeGuTm50m:-LVEOd7K5nzSeGuTm50n:b-wonisk) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_tscache.go#L220)):*
> ```Go
> 	// Use the transaction key to look for an entry in the write timestamp cache.
> 	key := keys.TransactionKey(txn.Key, txn.ID)
> 	return r.store.tsCache.GetMaxWrite(key, nil /* end */)
> ```

This feels like a slight abuse of the tscache txnID payload - normally it's used to *allow* txns to operate on keys they've already written, instead of for a txn to block itself out. I think it works here because we don't use txn records in normal MVCC operations, and I don't have a better idea right now, but it seems like something that might come back to bite us.

Specifically, at least in the read half of the tscache, the txn id gets cleared if two txns attempt to read the same key, so they both perceive the read as being done by a different transaction instead of themselves. If a similar situation happened here it would be interpreted as a low water mark instead of an interaction between two txns. 
___
*[pkg/storage/batcheval/eval_context.go, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVEN75pB4lAhTMnkkvH:-LVEN75pB4lAhTMnkkvI:b-isjybw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/batcheval/eval_context.go#L84)):*
> ```Go
> 	GetSplitQPS() float64
> 
> 	// GetTxnTombstoneFromTimestampCache returns the tombstone timestamp for the
> ```

What is the "tombstone timestamp for the transaction"? I don't think that's a term we use/define anywhere else. 
___
*[pkg/storage/batcheval/eval_context.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVENG5fDw1pMJsZePdD:-LVENG5fDw1pMJsZePdE:bav46zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/batcheval/eval_context.go#L88)):*
> ```Go
> 	// is not empty then the tombstone was explicitly set by an EndTxn req. If
> 	// it is empty then the tombstone is an implicit artifact of the timestamp
> 	// cache's low-water mark. Either way, transactions should not write records
> ```

s/records/txn records/

Which of the txn record's several timestamps matters here?


<!-- Sent from Reviewable.io -->

2019-01-02 21:25 UTC, andreimatei requested changes
Good stuff!

What do you think about including information in the responses to requests that can now create txn record (heartbeat and EndTxn) about whether a record was created? I think it might prove useful for testing and tracing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVFOxPX4Tj7-hqsuLL0:bi12et2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/integration_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFO46M4GCV4WldbCpX:-LVFO46M4GCV4WldbCpY:bs3ygv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/integration_test.go#L71)):*
> ```Go
> func TestDelayedBeginRetryable(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip(`WIP: @andrei what should we do here? Now that the timestamp
> ```

we discussed - the test should prolly be deleted once there's no more BeginTxn.
In the meantime, skip it, or investigate why it's flaky with the updated error.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 105 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFONEm-aVShFCliV0g:-LVFONEm-aVShFCliV0h:bdykmca) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/txn_interceptor_heartbeat.go#L105)):*
> ```
> The field is not needed for client-perceived correctness,
> ```

Say that the flipping should not be observed by clients since they're not supposed to be using the txn concurrently with an EndTxn
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDqrKu4c_rMfLajVk6:-LVFPNFPAZzbfS5EoZ_H:bwr5yqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/kv/txn_interceptor_heartbeat.go#L497)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What's up with this change?
</blockquote></details>

indeed, what's up?
___
*[pkg/roachpb/data.proto, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVErtKK2yCVtZlTOrSj:-LVErtKK2yCVtZlTOrSk:b-w0zf9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L258)):*
> ```protobuf
>   // A free-text identifier for debug purposes.
>   string name = 2;
>   reserved 3;
> ```

nit: i'd put this either at the top or at the bottom
___
*[pkg/roachpb/data_test.go, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVExDmJDs32rjwpgN7j:-LVExDmJDs32rjwpgN7k:b-tonoqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data_test.go#L562)):*
> ```Go
> }
> 
> func TestTransactionRecordRoundtrips(t *testing.T) {
> ```

please spell out that this test is about Transaction->TransactionRecord->Transaction, and please give a reminder about how TransactionRecord has a subset of fields and how wire compatibility is required because somebody unmarshalls TR as T.
___
*[pkg/roachpb/errors.proto, line 209 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFPklC5q5Al9F26NFL:-LVFPklC5q5Al9F26NFM:bgf4mkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/roachpb/errors.proto#L209)):*
> ```protobuf
>   // A possible replay caused by duplicate begin txn or out-of-order
>   // txn sequence number.
>   // TODO(nvanbenschoten): This is no longer in use. Remove.
> ```

remove in 2.4, right?
___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVEzdFhB_bxckLp-AvQ:b-k97tei) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Always nice to see the final payoff of such a migration.
</blockquote></details>

thanks for the cleanup, indeed.
But why not delete this constant? That's the ultimate victory.
___
*[pkg/storage/replica_tscache.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFDcfr-fONz-MHNqMX:-LVFDcfr-fONz-MHNqMY:b-j06att) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_tscache.go#L215)):*
> ```Go
> // cache's low-water mark. Either way, transactions should not write records
> // at or below this timestamp.
> func (r *Replica) GetTxnTombstoneFromTimestampCache(
> ```

I don't like this interface very much. I'll read this method and its comment in two weeks and I won't understand very much. One problem is that we return a txn id but the caller doesn't actually use the value. Another is that I don't like that the caller is in charge of dealing with `TxnSpanGCThreshold` separately from dealing with this method. It seems that that check could be encapsulated.

How about `GetTxnRecordHistory()` (or `GetTxnRecordCreationObjection()` or `IsTxnRecordRejected()`) returning an `enum {
None,   - caller go ahead and create the txn rec
Finalized, - replay
Ambiguous, - ts cache was bumped, somebody might have aborted us
TooOld - all the history might have been GC-ed. Why are you even bothering me for this old txn?
}`
Or as you've suggested, return a `TransactionAbortedReason` directly.

Also as we discussed, returning a timestamp from this method, and further propagating it through the `TransactionAbortedError` seems unnecessary, if not plainly bad, so getting rid of that part is good by itself.
___
*[pkg/storage/batcheval/cmd_begin_transaction.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVExe0t8QYNFkyc7Gt1:-LVExe0t8QYNFkyc7Gt2:b-9ztidg) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/storage/batcheval/cmd_begin_transaction.go#L139)):*
> ```Go
> 	// Write the txn record.
> 	txnRecord := reply.Txn.AsRecord()
> 	return result.Result{}, engine.MVCCPutProto(ctx, batch, cArgs.Stats, key, hlc.Timestamp{}, nil, &txnRecord)
> ```

long line :)
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 180 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFROXg77iJR4OS0HiA:-LVFROXg77iJR4OS0HiB:b-aq8iki) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/batcheval/cmd_end_transaction.go#L180)):*
> ```Go
> 		return result.Result{}, err
> 	} else if !ok {
> 		// No existing transaction record was found - create one.
> ```

mind giving some hints about how the record is "created" exactly? I don't see a call to the `batch` to write it. Same in `HeartbeatTxn`
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 185 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFRhDB88BiIveu8JNE:-LVFRhDB88BiIveu8JNF:bcmevbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/batcheval/cmd_end_transaction.go#L185)):*
> ```Go
> 
> 		// Verify that it is safe to create the transaction record.
> 		if args.Commit {
> ```

so what about rollbacks? They don't need replay protection, I guess? Consider adding a comment saying something.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 349 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFQwhp1HkUNwS5VkwO:-LVFQwhp1HkUNwS5VkwP:b347rgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/batcheval/cmd_end_transaction.go#L349)):*
> ```Go
> 	// WriteTooOldError). However, the replayed intent cannot be resolved by a
> 	// subsequent replay of this EndTransaction call because the txn timestamp
> 	// will be too old. Replays which include a BeginTransaction never succeed
> ```

I think this comment can be updated around `BeginTransaction`
___
*[pkg/storage/b [...]

2019-01-02 22:19 UTC, nvb reviewed
TFTRs!

I've gotten through the comments about #33257 so far and updated that PR accordingly.

> What do you think about including information in the responses to requests that can now create txn record (heartbeat and EndTxn) about whether a record was created? I think it might prove useful for testing and tracing.

It sounds like a decent idea, but I'll defer until we would find it useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVFbtH-12RHiHM2DVj_:b9ugo1y)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/data.proto, line 258 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVErtKK2yCVtZlTOrSj:-LVFapMd8maL-xgWSF1D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L258)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: i'd put this either at the top or at the bottom
</blockquote></details>

Done.
___
*[pkg/roachpb/data.proto, line 371 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVEKeT_DwP2M5q1WH1T:-LVFbLdW6GBlK3LFTOIa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L371)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment that any changes to this type must be reflected in the AsRecord/AsTransaction methods.
</blockquote></details>

Done.
___
*[pkg/roachpb/data.proto, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDkdIVCdACH42lbQXC:-LVFVqkiC4V4xRTw9wsS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data.proto#L380)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think we use spaces instead of tabs in proto files. Or so it seems from the diff.
</blockquote></details>

Done.
___
*[pkg/roachpb/data_test.go, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVExDmJDs32rjwpgN7j:-LVFXQZW8xfOo-_GVMlA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data_test.go#L562)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please spell out that this test is about Transaction->TransactionRecord->Transaction, and please give a reminder about how TransactionRecord has a subset of fields and how wire compatibility is required because somebody unmarshalls TR as T.
</blockquote></details>

Done.
___
*[pkg/roachpb/data_test.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDl0p6AcU7oFvKFD_9:-LVFWGO15hvENpl1uptB:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/roachpb/data_test.go#L566)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`assert.NoError(t, zerofields.NoZeroField(&txnRecord)` to keep test from rotting
</blockquote></details>

Nice, done.
___
*[pkg/storage/batcheval/cmd_push_txn.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDlf1X5AQTnJv3yWTm:-LVFXqn64kuWwcrgOThU:b-crqimh) ([raw file](https://github.com/cockroachdb/cockroach/blob/acd81211421d90ccc1c03204ab73df2418a4e6f0/pkg/storage/batcheval/cmd_push_txn.go#L109)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

+1 on unmarshalling as TR here
</blockquote></details>

I did this at first and went back and forth on it, but decided that unmarshalling into `TxnRecord`s everywhere added unnecessary noise without much benefit. We'd be converting these to `*Transaction` objects almost immediately. Pushing the type safety into `api.proto` messages would make this more of a win, but at the cost of a dramatic proliferation of the type, which has its own downsides (i.e. we now have *another* variant of Transaction floating around).

My current thinking about this type is to view it as an optional "mask" on the fields in `Transaction` when writing transaction records (with the associated perf improvement). Readers of transaction records can use the type as documentation about the few fields that will be set in the unmarshaled `Transaction`. (I added as much to the type's comment)


<!-- Sent from Reviewable.io -->

2019-01-03 17:17 UTC, nvb reviewed
The rest of this is ready for another look! The biggest change I made was refining the interface added to `batcheval.EvalContext`. I think @andreimatei will like this better.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVJhigp59bV4D2raKgQ:bifl5f2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/integration_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFO46M4GCV4WldbCpX:-LVFeMM_4-AlHwhUvASd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/integration_test.go#L71)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we discussed - the test should prolly be deleted once there's no more BeginTxn.
In the meantime, skip it, or investigate why it's flaky with the updated error.
</blockquote></details>

Done.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 105 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFONEm-aVShFCliV0g:-LVFeY_UEAQzifQ8MPUo:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/txn_interceptor_heartbeat.go#L105)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> The field is not needed for client-perceived correctness,
> ```

Say that the flipping should not be observed by clients since they're not supposed to be using the txn concurrently with an EndTxn
</blockquote></details>

Removed.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDppBf2N44eIpNUxNF:-LVFeZSm5k9l5ksAAwYC:b-ib1j1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/kv/txn_interceptor_heartbeat.go#L267)):*
Yeah, you're right, this is still racy. I removed it and added a TODO instead since this is nothing new. 

> The reason for resetting here in the first place is that there could've been a transaction retry error, right?

Yes. We could conditionally reset it, but I'd like this to be thought out more carefully before doing anything, and I don't want to do that in this change.
___
*[pkg/kv/txn_interceptor_heartbeat.go, line 497 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDqrKu4c_rMfLajVk6:-LVFfw4v0dHMG48oNOFm:b-ppjexc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b0ea90eac2d94aba4d96537dbcc175707ebd259/pkg/kv/txn_interceptor_heartbeat.go#L497)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

indeed, what's up?
</blockquote></details>

Drive by clean up of redundant code. This calls `asyncAbortCallbackLocked` immediately below, which calls `TxnCoordSender.cleanupTxnLocked`, which calls `txnHeartbeat.closeLocked`.
___
*[pkg/roachpb/errors.proto, line 209 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVFPklC5q5Al9F26NFL:-LVFj6sY0WX825bngLhj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/roachpb/errors.proto#L209)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

remove in 2.4, right?
</blockquote></details>

Done.
___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVFo7GG99F7ZK4KqLis:b17bxul) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
> But why not delete this constant? That's the ultimate victory.

The instructions for removing a version say not to because we only want to remove versions in-order. That idea looks to date back to https://github.com/cockroachdb/cockroach/pull/26967#issuecomment-400387963. I don't remember the reason for this though. @bdarnell do you?
___
*[pkg/storage/replica_test.go, line 3683 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDyY13D17xFPYeWn-W:-LVFsHE5CWGtqGbX84_E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3683)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Make this `.AsRecord()`.
</blockquote></details>

Done.
___
*[pkg/storage/replica_test.go, line 3799 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDymiP2cMWCRqhKLl6:-LVJep9NEr8qfrdwv2h1:b-ozc3ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3799)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, I think the explanation here has rotted. We're protected from "Raft retries" thanks to the lease applied index. I think what we're testing here are RPC-level retries (i.e. DistSender delivers a batch twice).
</blockquote></details>

Yeah, I suspect that this has been broken ever since command evaluation was pushed into `propose`. Fixed.
___
*[pkg/storage/replica_test.go, line 3801 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDyg5OBu4gPG_qgLiU:-LVFsaRM2WIs8IPOAoaa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3801)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This line can go, it was introduced when the default was `false`.
</blockquote></details>

Done.
___
*[pkg/storage/replica_test.go, line 3831 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzKeD9Ok_CzaZi22Y:-LVJg9V12SAsvgI3dOJn:b-srevak) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3831)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't something fishy here? If this is indeed a real-world RPC retry and the first RPC is the one that gets lost (i.e. the client receives the response from the second one), it'll receive TxnAbortedError even though the first one might've committed the Txn. Is it that DistSender would turn that TxnAbortedError into an ambiguous one?
</blockquote></details>

Are we working in a model where the RPC could be duplicated and then a response could be returned from the second one without the client knowing or being the cause of the duplication? I don't see how we could avoid issues from cases like that without full idempotency everywhere, so I suspect that that's not actually the case and that a duplicate request requires some buy-in from DistSender, which is where we turn RPC errors into ambiguous commit errors.
___
*[pkg/storage/replica_test.go, line 3892 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzac77JbwzX-A2zvF:-LVJh6h234N5Zf1ah4qL:bm8lvrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3892)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ditto about what we're testing.
</blockquote></details>

So this should stay then, right?
___
*[pkg/storage/replica_test.go, line 3901 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDzkEq8qsI--w6WPdj:-LVJhXKG8LeA5khHvVvZ:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae84f125c473c58a5b5631c523dfa07aac5b03c/pkg/storage/replica_test.go#L3901)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ah, this is what a Raft retry is. I think @andreimatei is just about to remove this in https://github.com/cockroachdb/cockroach/pull/33381.
</blockquote></details>

Ack.
___
*[pkg/storage/replica_tscache.go, line 76 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVE-pRdEkSsR-bn2 [...]

2019-01-03 17:22 UTC, nvanbenschoten commented
The fourth commit is also new. It stops explicitly using the timestamp from `TransactionAbortedError`s as the minimum timestamp for new transactions. @andreimatei and I decided this was unnecessary because the coordinator's clock should already be forwarded by the timestamp from the corresponding `BatchResponse`. This permitted a simplification to the `EvalContext` interface.

2019-01-04 22:56 UTC, bdarnell reviewed
> Reviewed 1 of 22 files at r6, 1 of 2 files at r7, 2 of 2 files at r9, 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVQ260k5Qin3BhLOd6-:bxh36kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> But why not delete this constant? That's the ultimate victory.

The instructions for removing a version say not to because we only want to remove versions in-order. That idea looks to date back to https://github.com/cockroachdb/cockroach/pull/26967#issuecomment-400387963. I don't remember the reason for this though. @bdarnell do you?
</blockquote></details>

I think it's just because we were using `iota` and didn't want to fix up the sequence to preserve the old values. At the time of that comment we were confused about whether the old values needed to be preserved; later in the thread we realized that they're never persisted or written over the network so this doesn't matter.


<!-- Sent from Reviewable.io -->

2019-01-07 17:58 UTC, nvanbenschoten commented
I think there's one issue here which is that `OrigTimestamp` can be moved forward between transaction epochs. This could allow a transaction that has incremented its timestamp and moved to a new epoch to recreate an aborted transaction record. We'll need to compare against `EpochZeroTimestamp` instead in `CanCreateTxnRecord`.

2019-01-07 18:30 UTC, andreimatei approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVd_8fw8SteGQH8ZZtf:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/errors.proto, line 209 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdT-Xr44IIHveeewlk:-LVdT-Xr44IIHveeewll:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/roachpb/errors.proto#L209)):*
> ```protobuf
>   // A possible replay caused by duplicate begin txn or out-of-order
>   // txn sequence number.
>   // TODO(nvanbenschoten): This is no longer in use. Remove in 2.4.
> ```

:+1: 
___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVdD0Kh-fc4i2L5rlT1:bkof8zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think it's just because we were using `iota` and didn't want to fix up the sequence to preserve the old values. At the time of that comment we were confused about whether the old values needed to be preserved; later in the thread we realized that they're never persisted or written over the network so this doesn't matter.
</blockquote></details>

so it sounds like we should just delete it, right?
___
*[pkg/storage/replica_eval_context_span.go, line 155 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdRZAh4p_XUJJU3HiM:-LVdRZAh4p_XUJJU3HiN:bdlcx7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/replica_eval_context_span.go#L155)):*
> ```Go
> // record was rejected. If the method ever determines that a transaction record
> // must be rejected, it will continue to reject that transaction going forwards.
> func (rec SpanSetReplicaEvalContext) CanCreateTxnRecord(
> ```

can we centralize the comment for this method in one place (i.e. on the EvalContext interface) and link to that from here and from the `replica` implementation?
___
*[pkg/storage/replica_tscache.go, line 216 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdYxbP3Ijc7aR1VKeb:-LVdYxbP3Ijc7aR1VKec:b-xlbskf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/replica_tscache.go#L216)):*
> ```
> 	// finalized. If there is one, then we return a retriable into an ambiguous
> 	// one higher up. Otherwise, if the client is still waiting for a result,
> ```

I think some words are missing here?
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 356 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdZjbPCJztyCkSLRO_:-LVdZjbPCJztyCkSLROa:b-klb4ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/batcheval/cmd_end_transaction.go#L356)):*
> ```
> 	// retry error. If the replay didn't attempt to create a txn record, any
> 	// push will immediately succeed as a missing txn record on push where
> 	// CanCreateTxnRecord returns false sets the transaction to aborted. In both
> ```

s/sets the transaction to aborted/succeeds


<!-- Sent from Reviewable.io -->

2019-01-07 22:06 UTC, nvb reviewed
TFTRs!

> I think there's one issue here which is that OrigTimestamp can be moved forward between transaction epochs. This could allow a transaction that has incremented its timestamp and moved to a new epoch to recreate an aborted transaction record. We'll need to compare against EpochZeroTimestamp instead in CanCreateTxnRecord.

I addressed this by using `txn.EpochZeroTimestamp`, which gives the desired semantics. I also added a comprehensive test with 45 separate scenarios that would have caught this issue and makes me feel more confident that the state machine correctly implements the one drawn out in https://github.com/cockroachdb/cockroach/pull/33523#issuecomment-451973368. @andreimatei you might be interested in taking a quick look at `TestCreateTxnRecord`. If not, I'll go ahead and merge this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-:-LVeHb7M1pGvQKr0oos_:b9lugeb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/settings/cluster/cockroach_versions.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVDmcvN7hpM57pagDRR:-LVdeb-n9lwxI9Q-qlt7:b-q1wklo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a36679c0426c0ecb1394ee314fa272d0e0bb7b4e/pkg/settings/cluster/cockroach_versions.go#L63)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so it sounds like we should just delete it, right?
</blockquote></details>

I'll go through and do that in one sweep.
___
*[pkg/storage/replica_eval_context_span.go, line 155 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdRZAh4p_XUJJU3HiM:-LVddbpcAfeOvZlSZUUQ:b-520gpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/replica_eval_context_span.go#L155)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we centralize the comment for this method in one place (i.e. on the EvalContext interface) and link to that from here and from the `replica` implementation?
</blockquote></details>

Sounds good. I'll do that in #33523 though, since this is being reworked there anyway.
___
*[pkg/storage/replica_tscache.go, line 216 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdYxbP3Ijc7aR1VKeb:-LVdeI6w7DFHManiAb4X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/replica_tscache.go#L216)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> 	// finalized. If there is one, then we return a retriable into an ambiguous
> 	// one higher up. Otherwise, if the client is still waiting for a result,
> ```

I think some words are missing here?
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/cmd_end_transaction.go, line 356 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/33396#-LVdZjbPCJztyCkSLRO_:-LVdeWWF9Vy4-Whjm_w1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3567e99fb3082a167ef9bdd1e7167b8f04abb831/pkg/storage/batcheval/cmd_end_transaction.go#L356)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> 	// retry error. If the replay didn't attempt to create a txn record, any
> 	// push will immediately succeed as a missing txn record on push where
> 	// CanCreateTxnRecord returns false sets the transaction to aborted. In both
> ```

s/sets the transaction to aborted/succeeds

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-01-07 23:13 UTC, merged