sql: add auto-spilling disk backed hash row container
cockroachdb/cockroach pull request #34092
Opened 2019-01-17 16:41 UTC by yuzefovich

We have two implementations of hashRowContainer (an in-memory and
a disk backed), but we don't have a container that would combine
those two. Previously, the logic of spilling to disk was a part
of hashJoiner; now, we extract that logic into a wrapper that starts
out by using the in-memory container and automatically spills to disk
when necessary.

Addresses: #32226.

Release note: None

2019-01-17 16:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/34092)
<!-- Reviewable:end -->

2019-01-17 16:44 UTC, yuzefovich commented
cc @georgeutsin if you're curious.

2019-01-22 15:22 UTC, asubiotto requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34092)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsqlrun/hash_row_container.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq2zAU22L4lSItT9Ta:-LWq2zAU22L4lSItT9Tb:b-4qu68a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L674)):*
> ```Go
> 	// to an embedded struct because of how defer works:
> 	// 	rc.init(...)
> 	//	defer rc.Close(ctx)
> ```

nit: uneven indentation
___
*[pkg/sql/distsqlrun/hash_row_container.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq2LkR03a13jvJizN3:-LWq2LkR03a13jvJizN4:b781ak5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L675)):*
> ```Go
> 	// 	rc.init(...)
> 	//	defer rc.Close(ctx)
> 	// Close will call hashRowContainer.Close(ctx) even after spilling to disk.
> ```

`s/hashRowContainer/hashMemRowContainer`
___
*[pkg/sql/distsqlrun/hash_row_container.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq3T_vEBreKUZzm7uN:-LWq3T_vEBreKUZzm7uO:bee3pqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L747)):*
> ```Go
> 	}
> 	if h.mrc == nil {
> 		mrc := memRowContainer{}
> ```

nit: you can assign `&memRowContainer{}` directly do `h.mrc`
___
*[pkg/sql/distsqlrun/hash_row_container_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq8PBJ1B_dyTlw0xh6:-LWq8PBJ1B_dyTlw0xh7:b-4uhs5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container_test.go#L130)):*
> ```Go
> 		}
> 		func() {
> 			i := rc.NewUnmarkedIterator(ctx)
> ```

I would maybe also add a test that creates a bucket iterator to verify that matches are preserved across spills.


<!-- Sent from Reviewable.io -->

2019-01-22 21:52 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34092)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/hash_row_container.go, line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq2zAU22L4lSItT9Ta:-LWqlgAg0mgLIEgJFTzR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L674)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: uneven indentation
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/hash_row_container.go, line 675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq2LkR03a13jvJizN3:-LWqlqnn-JW0f1ljjyRD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L675)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/hashRowContainer/hashMemRowContainer`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/hash_row_container.go, line 747 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq3T_vEBreKUZzm7uN:-LWqm-a620n5hYDUAQ37:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container.go#L747)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: you can assign `&memRowContainer{}` directly do `h.mrc`
</blockquote></details>

Thanks!
___
*[pkg/sql/distsqlrun/hash_row_container_test.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWq8PBJ1B_dyTlw0xh6:-LWrWtPz-cKwLzN0kP30:b-8tt3bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c272825454035b64f94d0ca96b0a205bca190eb6/pkg/sql/distsqlrun/hash_row_container_test.go#L130)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would maybe also add a test that creates a bucket iterator to verify that matches are preserved across spills.
</blockquote></details>

Good idea, thanks. Done.


<!-- Sent from Reviewable.io -->

2019-01-24 10:53 UTC, asubiotto approved these changes
Good stuff, thanks for doing this.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-:-LWzUapXBG-RVVIOJoRd:bhbsbc3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/hash_row_container.go, line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWzTDiS7LsNL2IgAwC9:-LWzTDiTArWOq_Qb_HQ1:b-1km8m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbd93305499e7d86bab14a6ca6aee0d21c53293/pkg/sql/distsqlrun/hash_row_container.go#L847)):*
> ```Go
> 	if h.shouldMark && h.hmrc.marked != nil {
> 		// We need to preserve marks.
> 		for i := 0; i < h.hmrc.Len(); i++ {
> ```

It feels weird to have two different ways to iterate over this row container depending on whether we're marking or not, but I guess that's fine. The only thing I would point out is that the final iterator is popping rows from the row container as it's done reading them as opposed to this loop not doing so. Up to you what you want to do, but if we're spilling due to memory being high, it might be good to `PopFirst`.
___
*[pkg/sql/distsqlrun/hashjoiner.go, line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWzUUIC2RJBsZgjR6CD:-LWzUUIC2RJBsZgjR6CE:b-7x3vqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbd93305499e7d86bab14a6ca6aee0d21c53293/pkg/sql/distsqlrun/hashjoiner.go#L596)):*
> ```Go
> 	if h.InternalClose() {
> 		// We need to close only memRowContainer of the probe side because the
> 		// stored side container will be closed by closing of h.storedRows.
> ```

`s/by closing of h.storedRows/by closing h.storedRows`


<!-- Sent from Reviewable.io -->

2019-01-24 17:52 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34092)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/hash_row_container.go, line 847 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWzTDiS7LsNL2IgAwC9:-LX-xbZxA07qFCMUWtpx:b1w38ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbd93305499e7d86bab14a6ca6aee0d21c53293/pkg/sql/distsqlrun/hash_row_container.go#L847)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels weird to have two different ways to iterate over this row container depending on whether we're marking or not, but I guess that's fine. The only thing I would point out is that the final iterator is popping rows from the row container as it's done reading them as opposed to this loop not doing so. Up to you what you want to do, but if we're spilling due to memory being high, it might be good to `PopFirst`.
</blockquote></details>

Great point. My thinking at first was that iterator does not guarantee a particular order in which the rows are outputted which is necessary to match with the marks, but upon looking into the code I realize that the iterator will output the rows in the order of increasing row indices, so I combined everything into a single way of iteration.
___
*[pkg/sql/distsqlrun/hashjoiner.go, line 596 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-LWzUUIC2RJBsZgjR6CD:-LX-yfPgDmEDmFIrbNVJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fbd93305499e7d86bab14a6ca6aee0d21c53293/pkg/sql/distsqlrun/hashjoiner.go#L596)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/by closing of h.storedRows/by closing h.storedRows`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-01-24 19:51 UTC, yuzefovich reviewed
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34092#-:-LX0PiBj6LvCarHpx3PY:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-01-24 20:15 UTC, merged