opt: add JoinLimit session variable
cockroachdb/cockroach pull request #34375
Opened 2019-01-29 20:01 UTC by justinj

This commit introduces the JoinLimit session variable, which enables a
transformation-based search of potential join orderings when a query
contains no more than a specified number of joins. I think we could
theoretically safely set this value to a default of 4 or 5 today, and I
suspect without too much trouble we can speed it up enough to bump it up
to 6 or 7.

This is sort of a crude heuristic: we count the number of joins
*globally*, even though those might not all be part of the same join
expression.

I briefly tried to compute the size of the biggest join tree via a
logical property, but that wasn't great, since we'd want it to be a Rule
property, and the Shared properties don't have those. In the end I
decided this was probably simplest (we just walk the tree after build).

This method does have some perf impact:

Before:
```
BenchmarkPhases/kv-read/Explore-8         	  100000	     12449 ns/op
BenchmarkPhases/kv-read-no-prep/Explore-8 	   30000	     40384 ns/op
BenchmarkPhases/kv-read-const/Explore-8   	10000000	       120 ns/op
BenchmarkPhases/tpcc-new-order/Explore-8  	   30000	     41891 ns/op
BenchmarkPhases/tpcc-delivery/Explore-8   	   50000	     26807 ns/op
BenchmarkPhases/tpcc-stock-level/Explore-8     	   10000	    134082 ns/op
```

After:
```
BenchmarkPhases/kv-read/Explore-8         	  100000	     12216 ns/op
BenchmarkPhases/kv-read-no-prep/Explore-8 	   30000	     41637 ns/op
BenchmarkPhases/kv-read-const/Explore-8   	10000000	       123 ns/op
BenchmarkPhases/tpcc-new-order/Explore-8  	   30000	     42511 ns/op
BenchmarkPhases/tpcc-delivery/Explore-8   	   50000	     27790 ns/op
BenchmarkPhases/tpcc-stock-level/Explore-8         10000	    137069 ns/op
```

Alternatively we could increment the counter in the memo during
the build phase, which might reduce the perf impact.

Next steps also include adding reordering rules for outer joins.

Planning time for chain queries:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/409075/51936630-a2094200-23d6-11e9-847c-5b12ab976fff.png">

Release note (sql change): replaced experimental_reorder_joins session
variable with experimental_join_limit, which will reorder joins in
queries with fewer than the specified number of joins.

2019-01-29 20:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/34375)
<!-- Reviewable:end -->

2019-01-30 16:12 UTC, RaduBerinde reviewed
We now store a copy of `ReorderJoins` flag in the `Memo`. We will need to store this new flag as well, otherwise we may use cached plans that don't match the current value (when we enable the cache that is).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-:-LXUWP-J53xbvljCpSwK:b-o5n24e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)



<!-- Sent from Reviewable.io -->

2019-01-30 18:11 UTC, rytaft requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/vars.go, line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUvEjd82-jbpXKgxPX:-LXUvEjd82-jbpXKgxPY:b-k7eu8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/vars.go#L345)):*
> ```Go
> 
> 	// CockroachDB extension.
> 	`experimental_join_limit`: {
> ```

I'd name this `experimental_reorder_joins_limit` or something like that -- right now it almost sounds like you limit the total number of joins allowed per query.
___
*[pkg/sql/opt/memo/memo.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUw5M84im0lazgzzxL:-LXUw5M84im0lazgzzxM:bjm3lbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/opt/memo/memo.go#L199)):*
> ```Go
> // from the given expression.
> // TODO(justin): make this bail early if it goes over the limit: if
> // the join limit is 0, we shouldn't traverse the whole tree.
> ```

Seems like bailing early might help reduce the regression you identified in the commit message, no?
___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUwq1u38-lvxC7np0B:-LXUwq1u38-lvxC7np0C:b-smgodm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/opt/xform/testdata/rules/join_order#L264)):*
> ```
>  └── G13: (const 1)
> 
> memo join-limit=4
> ```

Do you have any tests where you have more joins than the provided join-limit? E.g., this query with join-limit=3.


<!-- Sent from Reviewable.io -->

2019-02-04 15:18 UTC, justinj reviewed
Oops! Just realized I never published my comments here, PTAL since I'd like to get this in (off by default) for the upcoming alpha, if possible!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-:-LXt3nLjEWPlinQypCo1:bwoao53)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/vars.go, line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUvEjd82-jbpXKgxPX:-LXVZrWvByqiVd6NeEIh:bohqzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/vars.go#L345)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'd name this `experimental_reorder_joins_limit` or something like that -- right now it almost sounds like you limit the total number of joins allowed per query.
</blockquote></details>

Agreed, done.
___
*[pkg/sql/opt/memo/memo.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUw5M84im0lazgzzxL:-LXVZOIG7SXCemDSzT65:b6z9o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/opt/memo/memo.go#L199)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like bailing early might help reduce the regression you identified in the commit message, no?
</blockquote></details>

Got rid of this.
___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXUwq1u38-lvxC7np0B:-LXVZdRxEkDZqGc_ltDH:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b59eaef1ddb174c7049d0b84be28cb4475e331e/pkg/sql/opt/xform/testdata/rules/join_order#L264)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you have any tests where you have more joins than the provided join-limit? E.g., this query with join-limit=3.
</blockquote></details>

Good call, done.


<!-- Sent from Reviewable.io -->

2019-02-04 15:55 UTC, rytaft approved these changes
Has the perf impact improved? If so, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-:-LXtCjnR7-uR1jxWcP7h:b-voswtn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXtBj7dCKVYZSfz7it1:-LXtBj7e1jhmLnEhNjrA:b53qnwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f3bee631a7dbfb07b9da165ad0b25eca4cf69a/pkg/sql/opt/xform/testdata/rules/join_order#L219)):*
> ```
>  └── filters (true)
> 
> opt join-limit=3 format=show-all
> ```

Maybe add an `expect-not=AssociateJoin` here? Or does it still fire for the `cy, dz, abc` joins?
If so, you could keep this test but also add another test with `join-limit=2` or something like that... 


<!-- Sent from Reviewable.io -->

2019-02-04 15:57 UTC, rytaft commented
___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXtDScODK-ScBZfeJiC:-LXtDScODK-ScBZfeJiD:bklvqcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f3bee631a7dbfb07b9da165ad0b25eca4cf69a/pkg/sql/opt/xform/testdata/rules/join_order#L183)):*
> ```
> 
> opt join-limit=4
> SELECT * FROM bx, cy, dz, abc WHERE a = 1
> ```

just realized that this produces the same plan as the one below. Maybe you can inject some stats so they produce different plans?


<!-- Sent from Reviewable.io -->

2019-02-04 17:35 UTC, justinj reviewed
Yeah the perf impact only seems to be around 300ns in most cases now. Thanks for the review!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-:-LXtLgSE77-0QLiX9CPd:br0sd94)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXtDScODK-ScBZfeJiC:-LXtJmGiCqCYLTL-lVxh:bmqxcen) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f3bee631a7dbfb07b9da165ad0b25eca4cf69a/pkg/sql/opt/xform/testdata/rules/join_order#L183)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

just realized that this produces the same plan as the one below. Maybe you can inject some stats so they produce different plans?
</blockquote></details>

Oh good call—I changed the order of them so it can't find the good plan anymore.
___
*[pkg/sql/opt/xform/testdata/rules/join_order, line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-LXtBj7dCKVYZSfz7it1:-LXtJpSy6Ei3Zy5kgm5H:ba2o0ye) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f3bee631a7dbfb07b9da165ad0b25eca4cf69a/pkg/sql/opt/xform/testdata/rules/join_order#L219)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe add an `expect-not=AssociateJoin` here? Or does it still fire for the `cy, dz, abc` joins?
If so, you could keep this test but also add another test with `join-limit=2` or something like that... 
</blockquote></details>

It does still fire for the subtree, it shouldn't fire for two though, added.


<!-- Sent from Reviewable.io -->

2019-02-04 18:27 UTC, rytaft approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)



<!-- Sent from Reviewable.io -->

2019-02-04 19:38 UTC, andy-kimball approved these changes
Looks good. I'm glad you got the property stuff working.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34375#-:-LXu0AxSCJsT9RWBtgen:bsen1wp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)



<!-- Sent from Reviewable.io -->

2019-02-04 21:45 UTC, justinj commented
I think this got stuck, trying again

bors r+

2019-02-04 22:16 UTC, merged