sql: bust incorrect usages of evalCtx.Ctx()
cockroachdb/cockroach pull request #34936
Opened 2019-02-15 00:09 UTC by jordanlewis

Fixes #34935.

Previously, a bunch of callsites were incorrectly using evalCtx.Ctx()
instead of a more appropriate context. This was admittedly confusing,
and this commit does nothing to improve the confusion, though it does
fix the incorrect context usages.

Processors must never use evalCtx.Ctx() once they've been started - they
must always use the context embedded into their processor base.

Release note (bug fix): fix a crash that could occur when using logspy
tracing in some circumstances.

2019-02-15 00:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/34936)
<!-- Reviewable:end -->

2019-02-19 23:26 UTC, jordanlewis commented
PTAL

2019-02-20 16:31 UTC, asubiotto approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34936#-:-LZAjow_-uWPP4shXd04:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)



<!-- Sent from Reviewable.io -->

2019-02-20 16:32 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/distsqlrun/stream_group_accumulator.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34936#-LZAj3B95hd0T1NlQYbt:-LZAj3B95hd0T1NlQYbu:b7t6eth) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94a65b9530b6867cf0a1ae79562f8991727c3e/pkg/sql/distsqlrun/stream_group_accumulator.go#L29)):*
> ```Go
> // by equality according to the ordering columns.
> type streamGroupAccumulator struct {
> 	// ctx is the captured context, created at Start time. It should be used for
> ```

why capture these two guys in this accumulator as opposed to passing them both to `nextGroup()`? I guess the capturing of the `evalCtx` I don't care much, but I'd avoid the capturing of the `ctx`.

Also, here and in `streamMerger`, it looks like this `evalCtx` is only needed for some comparisons. Maybe there's an opportunity to extract a much smaller subset of the `evalCtx` for that - a minuscule `datumComparisonCtx`. If possible, that's probably be an improvement.
___
*[pkg/sql/distsqlrun/stream_merger.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34936#-LZAjI_G9Tuk5kqbtZOU:-LZAjI_G9Tuk5kqbtZOV:b-9houup) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b94a65b9530b6867cf0a1ae79562f8991727c3e/pkg/sql/distsqlrun/stream_merger.go#L32)):*
> ```Go
> // stream.
> type streamMerger struct {
> 	evalCtx    *tree.EvalContext
> ```

similar - why capture this as opposed to passing it like it was?
Also, since 


<!-- Sent from Reviewable.io -->

2019-02-20 23:40 UTC, jordanlewis commented
Fixed the capturing of the context.Context, fixing the EvalContext is definitely out of scope of this.

2019-02-20 23:51 UTC, andreimatei approved these changes
LGTM

> fixing the EvalContext is definitely out of scope of this.

well but the capturing of the `EvalCtx` in the `streamMerger/streamAgg` is new in this patch, isn't it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34936#-:-LZCJLfKAa8xBfaZexwS:bgjox85)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-02-21 18:09 UTC, jordanlewis commented
bors r+

2019-02-21 18:09 UTC, jordanlewis commented
Fixed your comment - TFTR!

2019-02-21 18:39 UTC, merged