workload: add indexes workload
cockroachdb/cockroach pull request #35077
Opened 2019-02-19 22:23 UTC by nvanbenschoten

Closes #34912.

This adds a new workload called `indexes`. Unlike `kv`, the workload is
specifically designed to stress secondary indexes. Its schema looks
like:

```
CREATE TABLE indexes (
    key     UUID  NOT NULL PRIMARY KEY,
    col0    INT   NOT NULL,
    col1    INT   NOT NULL,
    col2    INT   NOT NULL,
    col3    INT   NOT NULL,
    col4    INT   NOT NULL,
    col5    INT   NOT NULL,
    col6    INT   NOT NULL,
    col7    INT   NOT NULL,
    col8    INT   NOT NULL,
    col9    INT   NOT NULL,
    payload BYTES NOT NULL
)
```

and it includes knobs to specify how many of the "col" columns should be
indexed and whether they should be indexed using a UNIQUE specifier. The
workload also includes a knob to specify the size of the `payload`
column.

Release note: None

2019-02-19 22:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35077)
<!-- Reviewable:end -->

2019-02-20 16:00 UTC, ajwerner requested changes
This is a fine start. I can imagine we'll extend this by adding control for the distribution of writes. 

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-:-LZAc1gH8EBq5kP7qL7m:bgosnik)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/workload/indexes/indexes.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAbBK4DVsBXv4LA8vu:-LZAbBK4DVsBXv4LA8vv:bcxofsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> 
> package bank
> ```

`package indexes`?
___
*[pkg/workload/indexes/indexes.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAcOfH1NOQqIA4wszE:-LZAcOfH1NOQqIA4wszF:b-zbn5ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L69)):*
> ```Go
> 	New: func() workload.Generator {
> 		g := &indexes{}
> 		g.flags.FlagSet = pflag.NewFlagSet(`indexes`, pflag.ContinueOnError)
> ```

should we add an `init` flag to be parallel to kv?  
___
*[pkg/workload/indexes/indexes.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAbieO-K3QHZO1VKdb:-LZAbieP1brS8hOyBJ1L:b-noqfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L73)):*
> ```Go
> 		g.flags.IntVar(&g.idxs, `secondary-indexes`, 1, `Number of indexes to add to the table.`)
> 		g.flags.BoolVar(&g.unique, `unique-indexes`, false, `Use UNIQUE secondary indexes.`)
> 		g.flags.IntVar(&g.payload, `payload`, 64, `Size of the payload only present in the primary key.`)
> ```

`only present in the primary index`? I found this documentation sort of confusing. 


<!-- Sent from Reviewable.io -->

2019-02-20 16:40 UTC, danhhz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/workload/indexes/indexes.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAlVC_-FBvseheYXiY:-LZAlVCa4n9MBdXcZmk0:b1wl75n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L103)):*
> ```Go
> 			}
> 			for i := 0; i < w.idxs; i++ {
> 				ddl := fmt.Sprintf(`CREATE%s INDEX idx%d ON indexes (col%d)`, unique, i, i)
> ```

unless you're specifically interested in testing schema changes, it's usually better to put these in the table schema. then if you're dealing with fixtures, you get them during the IMPORT


<!-- Sent from Reviewable.io -->

2019-02-25 18:15 UTC, nvb reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35077)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/indexes/indexes.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAbBK4DVsBXv4LA8vu:-LZ_lD8zDIWDICF0z8cZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L15)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`package indexes`?
</blockquote></details>

Done.
___
*[pkg/workload/indexes/indexes.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAcOfH1NOQqIA4wszE:-LZ_lOji1GssApZktAss:b-re9ztf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L69)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we add an `init` flag to be parallel to kv?  
</blockquote></details>

The `init` flag is part of workload. See `pkg/workload/cli/run.go`.
___
*[pkg/workload/indexes/indexes.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAbieO-K3QHZO1VKdb:-LZ_leJF0xmCmCVFTh1K:bj4fq1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L73)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`only present in the primary index`? I found this documentation sort of confusing. 
</blockquote></details>

How's that?
___
*[pkg/workload/indexes/indexes.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-LZAlVC_-FBvseheYXiY:-LZ_rYjO6HtMZ_CW2Mpv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a90e28785b6dee10d9d5f0cecaf1b5ba10acaca/pkg/workload/indexes/indexes.go#L103)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

unless you're specifically interested in testing schema changes, it's usually better to put these in the table schema. then if you're dealing with fixtures, you get them during the IMPORT
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-02-25 20:15 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35077#-:-LZaI02K0EMkw0XWAWfb:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-02-25 20:45 UTC, nvanbenschoten commented
bors r+

2019-02-25 22:14 UTC, merged