exec: implement sort chunks operator
cockroachdb/cockroach pull request #35082
Opened 2019-02-20 02:17 UTC by yuzefovich

Implements sort chunks operator in vectorized engine to be used when
the tuples are already ordered on a prefix of ordering columns. The
"meat" of implementation is a new chunker operator which produces
chunks of tuples (delimited by a zero-length batch) which are then
inputted into a general sorter. The sorter is reset for every chunk.

Please disregard the first commit for now.

Also, some of ColVec's method have been copied from George's PR.

Release note: None

2019-02-20 02:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35082)
<!-- Reviewable:end -->

2019-02-20 02:21 UTC, yuzefovich commented
At the moment, running the benchmark shows that general sorter is more efficient than sort chunks when average chunk size is relatively small, and they become about the same at around 32 tuples per chunk on avg. There should be some performance improvements to be made, but I don't see them at the moment.

Here are the results of the benchmark:
```
BenchmarkSortChunks/CHUNKS/rows=4096/cols=2/matchLen=1/avgChunkSize=4-12         	    3000	    367382 ns/op	 178.39 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=2/matchLen=1/avgChunkSize=4-12            	   10000	    211712 ns/op	 309.55 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=2/matchLen=1/avgChunkSize=32-12        	   10000	    134198 ns/op	 488.35 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=2/matchLen=1/avgChunkSize=32-12           	   10000	    215705 ns/op	 303.82 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=2/matchLen=1/avgChunkSize=256-12       	   10000	    195484 ns/op	 335.25 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=2/matchLen=1/avgChunkSize=256-12          	    5000	    254989 ns/op	 257.01 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=1/avgChunkSize=4-12         	    2000	    885725 ns/op	 147.98 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=1/avgChunkSize=4-12            	    3000	    429610 ns/op	 305.09 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=1/avgChunkSize=32-12        	    5000	    369259 ns/op	 354.96 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=1/avgChunkSize=32-12           	    3000	    441204 ns/op	 297.08 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=1/avgChunkSize=256-12       	    5000	    384495 ns/op	 340.89 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=1/avgChunkSize=256-12          	    3000	    466733 ns/op	 280.83 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=2/avgChunkSize=4-12         	    1000	   1284477 ns/op	 102.04 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=2/avgChunkSize=4-12            	    3000	    379238 ns/op	 345.62 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=2/avgChunkSize=32-12        	    3000	    355769 ns/op	 368.42 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=2/avgChunkSize=32-12           	    5000	    382958 ns/op	 342.26 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=2/avgChunkSize=256-12       	    5000	    313552 ns/op	 418.02 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=2/avgChunkSize=256-12          	    5000	    402069 ns/op	 325.99 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=3/avgChunkSize=4-12         	    1000	   1375976 ns/op	  95.26 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=3/avgChunkSize=4-12            	    5000	    384106 ns/op	 341.24 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=3/avgChunkSize=32-12        	    5000	    345421 ns/op	 379.45 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=3/avgChunkSize=32-12           	    5000	    300658 ns/op	 435.95 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=3/avgChunkSize=256-12       	   10000	    204918 ns/op	 639.63 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=3/avgChunkSize=256-12          	    5000	    296898 ns/op	 441.47 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=2/matchLen=1/avgChunkSize=4-12        	     200	   6158005 ns/op	 170.28 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=2/matchLen=1/avgChunkSize=4-12           	     500	   3437333 ns/op	 305.06 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=2/matchLen=1/avgChunkSize=32-12       	    1000	   1936189 ns/op	 541.57 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=2/matchLen=1/avgChunkSize=32-12          	     500	   3282176 ns/op	 319.48 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=2/matchLen=1/avgChunkSize=256-12      	    1000	   1854351 ns/op	 565.47 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=2/matchLen=1/avgChunkSize=256-12         	     500	   3600148 ns/op	 291.26 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=1/avgChunkSize=4-12        	     100	  14805080 ns/op	 141.65 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=1/avgChunkSize=4-12           	     200	   6128562 ns/op	 342.19 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=1/avgChunkSize=32-12       	     300	   6025250 ns/op	 348.06 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=1/avgChunkSize=32-12          	     200	   6356965 ns/op	 329.90 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=1/avgChunkSize=256-12      	     300	   4783125 ns/op	 438.45 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=1/avgChunkSize=256-12         	     200	   6796123 ns/op	 308.58 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=2/avgChunkSize=4-12        	     100	  21026125 ns/op	  99.74 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=2/avgChunkSize=4-12           	     200	   5952529 ns/op	 352.31 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=2/avgChunkSize=32-12       	     200	   6068083 ns/op	 345.60 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=2/avgChunkSize=32-12          	     300	   5464716 ns/op	 383.76 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=2/avgChunkSize=256-12      	     300	   3911763 ns/op	 536.11 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=2/avgChunkSize=256-12         	     200	   6152161 ns/op	 340.88 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=3/avgChunkSize=4-12        	     100	  20421626 ns/op	 102.69 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=3/avgChunkSize=4-12           	     300	   5619728 ns/op	 373.18 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=3/avgChunkSize=32-12       	     300	   4867495 ns/op	 430.85 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=3/avgChunkSize=32-12          	     300	   4469045 ns/op	 469.26 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=3/avgChunkSize=256-12      	    1000	   2226770 ns/op	 941.79 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=3/avgChunkSize=256-12         	     300	   4693298 ns/op	 446.84 MB/s
```

2019-02-20 02:26 UTC, yuzefovich commented
Oh, and BTW, this PR fixes a typo in general sorter benchmark. That typo made the benchmark overestimate the actual throughput.

With typo:
```
BenchmarkSort/rows=2048/cols=1-12               100000         20167 ns/op     812.39 MB/s
BenchmarkSort/rows=2048/cols=2-12                50000         38103 ns/op     859.98 MB/s
BenchmarkSort/rows=2048/cols=4-12                20000         70954 ns/op     923.63 MB/s
BenchmarkSort/rows=16384/cols=1-12               10000        145783 ns/op     899.09 MB/s
BenchmarkSort/rows=16384/cols=2-12                5000        319510 ns/op     820.46 MB/s
BenchmarkSort/rows=16384/cols=4-12                2000        647004 ns/op     810.33 MB/s
BenchmarkSort/rows=262144/cols=1-12                500       2453909 ns/op     854.62 MB/s
BenchmarkSort/rows=262144/cols=2-12                300       4993101 ns/op     840.02 MB/s
BenchmarkSort/rows=262144/cols=4-12                100      10132106 ns/op     827.92 MB/s
```
Without typo:
```
BenchmarkSort/rows=2048/cols=1-12                10000        110513 ns/op     148.25 MB/s
BenchmarkSort/rows=2048/cols=2-12                10000        153907 ns/op     212.91 MB/s
BenchmarkSort/rows=2048/cols=4-12                10000        222148 ns/op     295.01 MB/s
BenchmarkSort/rows=16384/cols=1-12                2000        923159 ns/op     141.98 MB/s
BenchmarkSort/rows=16384/cols=2-12                1000       1265358 ns/op     207.17 MB/s
BenchmarkSort/rows=16384/cols=4-12                1000       1905475 ns/op     275.15 MB/s
BenchmarkSort/rows=262144/cols=1-12                100      12337140 ns/op     169.99 MB/s
BenchmarkSort/rows=262144/cols=2-12                100      19630624 ns/op     213.66 MB/s
BenchmarkSort/rows=262144/cols=4-12                 50      35416060 ns/op     236.86 MB/s
```

2019-02-21 18:21 UTC, georgeutsin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/sort.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyeaB5eEeUzJkRuoa:-LZFyeaB5eEeUzJkRuob:bb9j4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L340)):*
> ```Go
> 	// emitting states.
> 	chunkerReading chunkerState = iota
> 	// chunkerEmittingFromBuffer is the state of chunker operator in which it
> ```

[nit].. state of the chunker...
___
*[pkg/sql/exec/sort.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyzdA1V8fp9UaVN1q:-LZFyzdA1V8fp9UaVN1r:bvtaez3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L341)):*
> ```Go
> 	chunkerReading chunkerState = iota
> 	// chunkerEmittingFromBuffer is the state of chunker operator in which it
> 	// emits tuples that have been buffered. All those tuples belong to the same
> ```

[nit] All the tuples...
___
*[pkg/sql/exec/sort.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFz5-R3zMGJSnawWNx:-LZFz5-R3zMGJSnawWNy:buyfog4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L343)):*
> ```Go
> 	// emits tuples that have been buffered. All those tuples belong to the same
> 	// chunk. After all tuples are emitted, the buffer is cleared, a zero-length
> 	// batch is emitted to indicate the end of the chunk, and chunker is moved
> ```

[nit] and the state is moved to chunkerEmittingFromBatch
___
*[pkg/sql/exec/sort.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyuk80RV6RFBDZkQJ:-LZFyuk80RV6RFBDZkQK:bb9j4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L346)):*
> ```Go
> 	// to chunkerEmittingFromBatch state.
> 	chunkerEmittingFromBuffer
> 	// chunkerEmittingFromBatch is the state of chunker operator in which it
> ```

[nit].. state of the chunker...
___
*[pkg/sql/exec/sort.go, line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZGDTpJ7zNcQCEpP7d3:-LZGDTpJ7zNcQCEpP7d4:b-2slxg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L355)):*
> ```Go
> // chunker is an operator that produces chunks from its input when the tuples
> // are already ordered on the first matchLen columns. To indicate the end of a
> // chunk chunker emits a single zero-length batch. To indicate that the input
> ```

[nit] chunk, the chunker
___
*[pkg/sql/exec/sort.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZGEBkREnSZ7iskGTg2:-LZGEBkREnSZ7iskGTg3:b-p54yyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L443)):*
> ```Go
> 		s.bufferedValues = make([]ColVec, len(s.inputTypes))
> 		for i := 0; i < len(s.inputTypes); i++ {
> 			s.bufferedValues[i] = newMemColumn(s.inputTypes[i], 0)
> ```

What has pprof shown with regards to the bufferedValues memory allocations? My hunch is that we can amortize some allocation by setting a non 0 value here


<!-- Sent from Reviewable.io -->

2019-02-21 22:23 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/sort.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyeaB5eEeUzJkRuoa:-LZH4HSZ1Hi1DP7l5A8o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L340)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

[nit].. state of the chunker...
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyzdA1V8fp9UaVN1q:-LZH4Ju_68BkM8Ip7y1G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L341)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

[nit] All the tuples...
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFz5-R3zMGJSnawWNx:-LZH4dNI5E8sX6btc9OU:bq6bmxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L343)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

[nit] and the state is moved to chunkerEmittingFromBatch
</blockquote></details>

Thanks, slightly rephrased the comment.
___
*[pkg/sql/exec/sort.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZFyuk80RV6RFBDZkQJ:-LZH5HPCAftIK4er6Cdz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L346)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

[nit].. state of the chunker...
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZGDTpJ7zNcQCEpP7d3:-LZH5Hq76QxNraJmOL-6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L355)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

[nit] chunk, the chunker
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZGEBkREnSZ7iskGTg2:-LZH6ssI8LgrNMAm5Cm6:b6pedzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L443)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

What has pprof shown with regards to the bufferedValues memory allocations? My hunch is that we can amortize some allocation by setting a non 0 value here
</blockquote></details>

This doesn't seem to be a problem (I don't see it on the profile): I tried setting 512 instead of 0 (max avg size of a chunk in the benchmark is 256), and I see no performance difference. I think that on a workload with constantly growing chunk sizes it might show up, but on the benchmark it doesn't because we'll allocate only once (or maybe twice) since the chunk sizes are about equal. But I agree, we might want to allocate for say 32 tuples right away. Curious what other people think?


<!-- Sent from Reviewable.io -->

2019-02-22 01:01 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colvec_tmpl.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa-d335JJ93VJIKiD:-LZHa-d44d-jN7RA0b-r:bz2hbrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/colvec_tmpl.go#L263)):*
> ```Go
> 		for i := uint16(0); i < batchSize; i++ {
> 			if vec.NullAt(srcStartIdx + i) {
> 				m.SetNull64(destStartIdx + uint64(i))
> ```

I know this is messed up everywhere, but just realized that this is pretty silly - it's a bitmap, we can just bitwise OR the two null bitmaps.
___
*[pkg/sql/exec/deselector.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa9j298hlu91gdx7l:-LZHa9j298hlu91gdx7m:bq73tkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/deselector.go#L19)):*
> ```Go
> import "github.com/cockroachdb/cockroach/pkg/sql/exec/types"
> 
> // TODO(yuzefovich): does this operator deserve a unit test?
> ```

I would say it deserves at least a very basic sanity check. I also would like to see a benchmark - I've always been curious how much it costs to remove the selection vector as many operators are simpler to understand without having to think about the selection vector. If it's cheap, we could just deselect unconditionally before certain operators.
___
*[pkg/sql/exec/deselector.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHaTJz-l44Nsxa-0q-:-LZHaTJz-l44Nsxa-0q0:bw3wway) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/deselector.go#L58)):*
> ```Go
> 		toCol := p.output.ColVec(i)
> 		fromCol := batch.ColVec(i)
> 		toCol.CopyWithSelInt16(fromCol, sel, batch.Length(), t)
> ```

What's the advantage of doing this as opposed to the `coalesce` operator, which I think also combines batches that are smaller than `ColBatchSize`? In general, it's better to give operators longer chunks of stuff to work on, since it makes the tight loops be able to do more before having to go back up and do type switches on columns again.
___
*[pkg/sql/exec/sort.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZGEBkREnSZ7iskGTg2:-LZHcq3u2Ku2ArKcAQhI:bkitruz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38df6cbc6a0895e274cd326af13f0a603971ca5/pkg/sql/exec/sort.go#L443)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This doesn't seem to be a problem (I don't see it on the profile): I tried setting 512 instead of 0 (max avg size of a chunk in the benchmark is 256), and I see no performance difference. I think that on a workload with constantly growing chunk sizes it might show up, but on the benchmark it doesn't because we'll allocate only once (or maybe twice) since the chunk sizes are about equal. But I agree, we might want to allocate for say 32 tuples right away. Curious what other people think?
</blockquote></details>

I don't think it matters much to be honest, since this is just happening during init. Any performance hit we take from having to resize will go away as long as there are at least a couple of batches. I think it's okay to do either.
___
*[pkg/sql/exec/sort.go, line 277 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHbgnkEHxhDK140KgY:-LZHbgnl-g2LS2fzajMD:bg1q78i) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L277)):*
> ```Go
> // the columns in the input operator. The input tuples must be sorted on first
> // matchLen columns.
> func NewSortChunks(
> ```

I would recommend moving this to a different file.
___
*[pkg/sql/exec/sort.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHgh_I8H0BN_gHcKLc:-LZHgh_I8H0BN_gHcKLd:b-iw7frg) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L289)):*
> ```Go
> 		sorter, err = NewSorter(chunker, inputTypes, orderingCols[matchLen:])
> 	} else {
> 		sorter = &noopOperator{input: chunker}
> ```

Do you need to include an extra noopOperator here?
___
*[pkg/sql/exec/sort.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHblES3T34_yyzEk3g:-LZHblES3T34_yyzEk3h:bmmn12t) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L296)):*
> ```Go
> 	// TODO(yuzefovich): current implementation of sort chunks will be returning
> 	// batches of sizes equal to sizes of the corresponding chunks. Should we use
> 	// a coalescer operator around it?
> ```

Yes, I think we should, for the reason I mentioned in another comment. It's inefficient to give operators tiny batches.

In some cases, it's more efficient to do the coalescing on demand, as the operator is running, since it involves less copies. You might want to think about doing that rather than simply slapping a coalesce operator on top.
___
*[pkg/sql/exec/sort.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHc7I846RalxM0enxh:-LZHc7I846RalxM0enxi:burd4la) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L319)):*
> ```Go
> 			}
> 			// We're not yet done - need to process another chunk.
> 			if resetter, ok := c.sorter.(resetter); ok {
> ```

I think I introduced this interface as well in the hash-agg PR, but at least in that PR it was for a very different purpose - resetting for benchmarks. And the implicit contract was that every resettable operator would call reset on its input...

What's the purpose of this reset call here exactly? I think we should think a bit about which operators need such things, and whether there's 2 kinds of reset that we really desire.
___
*[pkg/sql/exec/sort.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHdZgKC7Ux7HC5thVB:-LZHdZgLAcuw2iA8ynHF:ba0ipcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L475)):*
> ```Go
> 			// TODO(yuzefovich): is this the best way to reinitialize s.partitionCol
> 			// to false?
> 			copy(s.partitionCol, s.initPartitionCol)
> ```

I think this is fine, yeah.
___
*[pkg/sql/exec/sort.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHfsyxAKY5TL4D5YyW:-LZHfsyxAKY5TL4D5YyX:bj0xgog) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L544)):*
> ```Go
> 				s.output.ColVec(i).Copy(s.bufferedValues[i], s.emittedFromBuffer, newEmitted, s.inputTypes[i])
> 			}
> 			s.emittedFromBuffer = newEmitted
> ```

It seems to me that this would be a good opportunity to not immediately return `s.output` to do the coalescing within the operator without incurring the overhead of passing everything to the coalescer, which will take 2x the copies in the end (1x into output buffer for a chunk, then another 1x for each output buffer into the coalescer's internal buffer). Seems like you should copy these colvecs into the "current batch" until there's no room, and flush at that point, saving the remainder into a buffer for next time.

Oh, but taking a step back, I see that this is required because this is exactly the thing that passes data into the sorter which permits the sorter to act like a global sorter...

Perhaps the thing that's holding the performance back here is that we're not simply hooking into the sorter's internal processes for managing the partitions. Then again, maybe those things aren't particularly good either. It just strikes me that it's possible that the sorter is more efficient at passing a part [...]

2019-02-22 01:11 UTC, jordanlewis reviewed
Nice work overall, and good tests. Also, thanks for spotting that mistake in the sorter benchmark. Though I think the fix was not quite right - I think the more correct fix makes the performance curve make a little more sense. 

My main feedback is about how the sort chunks plugs into the sorter. I think it would be more efficient to hook into the sorter in a way that requires fewer copies overall. Instead of having one copy for every chunk, it would be slightly be better to keep small chunks next to each other in an output batch, and then tell the sorter to act how it does today when sorting the rest of a multi-column sort - in a single type switch, it does a subsort on each of the partitions. Then again, I'm not totally positive that it would make things faster.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-LZHiWSD-uGTRnGYinIS:b-xb44f5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/sort_test.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHj_1C2iU7zWDukF1x:-LZHj_1C2iU7zWDukF1y:bmehbvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort_test.go#L207)):*
> ```Go
> 					col := batch.ColVec(i).Int64()
> 					for j := 0; j < ColBatchSize; j++ {
> 						col[j] = rng.Int63() % int64((j*1024)+1)
> ```

I think the second `j` here should be an `i` as well. The purpose of this mod was to give the values a small range, so that partitioning could be tested. Keeping it at j doesn't make any sense as far as I can tell.
___
*[pkg/sql/exec/sort_test.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHjXzS4WXux9Fb4Jye:-LZHjXzS4WXux9Fb4Jyf:bnfjqj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort_test.go#L231)):*
> ```Go
> }
> 
> func TestChunker(t *testing.T) {
> ```

Put this in a separate file too.


<!-- Sent from Reviewable.io -->

2019-02-25 22:38 UTC, asubiotto requested changes
Left a couple of small comments but as we talked offline theoretically a sorter currently sorts one column at a time and sort chunks seems like the only thing it could do differently is choose when to pause the spool step (as close to ColBatchSize as possible) and "skip" over columns as it can assume that a prefix has already been sorted, so it seems like it doesn't need to be a new op. I think this is what Jordan is saying as well. Will wait for your update on this PR and give it another look then.

> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-LZami_q9TniC2BNmnz-:b-z95gmq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/operator.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZaar0FC6BV8JYKzjUT:-LZaar0G5CMjUyHRo7II:b9i7qsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/operator.go#L47)):*
> ```Go
> }
> 
> func (n *noopOperator) reset() {}
> ```

If you end up doing this this should call `reset` on its input.
___
*[pkg/sql/exec/sort.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZabSE7-maBSTGIrqFb:-LZabSE7-maBSTGIrqFc:bq5j0q0) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L200)):*
> ```Go
> 		p.order = make([]uint64, nTuples)
> 		p.workingSpace = make([]uint64, nTuples)
> 	} else if uint64(cap(p.order)) < nTuples {
> ```

This could be
```
if p.order == nil || uint64(cap(p.order)) < nTuples {
    make...
}
```
___
*[pkg/sql/exec/sort.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZabf1T51WULs8qrlGm:-LZabf1T51WULs8qrlGn:b-brvniu) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L267)):*
> ```Go
> }
> 
> func (p *sortOp) reset() {
> ```

This should reset its input operator as well I think
___
*[pkg/sql/exec/sort.go, line 475 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHdZgKC7Ux7HC5thVB:-LZagrlv8poIRW_t56AP:bx0p5bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L475)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this is fine, yeah.
</blockquote></details>

We also have a `zeroBoolVec` you can reuse for this purpose.


<!-- Sent from Reviewable.io -->

2019-02-27 02:02 UTC, yuzefovich reviewed
Thanks for the feedback! Indeed, my initial approach was flawed (although it seemed very understandable, at least to me), but with the updated approach of plugging into the general sorter directly we get significant performance improvement, regardless of the average chunk size:
```
BenchmarkSortChunks/CHUNKS/rows=4096/cols=2/matchLen=1/avgChunkSize=8-12         	   20000	     69082 ns/op	 948.67 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=2/matchLen=1/avgChunkSize=8-12            	   10000	    204058 ns/op	 321.16 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=2/matchLen=1/avgChunkSize=128-12       	   20000	     81068 ns/op	 808.40 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=2/matchLen=1/avgChunkSize=128-12          	    5000	    252258 ns/op	 259.80 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=1/avgChunkSize=8-12         	   10000	    197829 ns/op	 662.55 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=1/avgChunkSize=8-12            	    3000	    460703 ns/op	 284.50 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=1/avgChunkSize=128-12       	   10000	    317556 ns/op	 412.75 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=1/avgChunkSize=128-12          	    3000	    523740 ns/op	 250.26 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=2/avgChunkSize=8-12         	   10000	    156823 ns/op	 835.80 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=2/avgChunkSize=8-12            	    5000	    384891 ns/op	 340.54 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=2/avgChunkSize=128-12       	   10000	    169408 ns/op	 773.71 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=2/avgChunkSize=128-12          	    3000	    404988 ns/op	 323.64 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=3/avgChunkSize=8-12         	   10000	    121904 ns/op	1075.21 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=3/avgChunkSize=8-12            	    5000	    363983 ns/op	 360.10 MB/s
BenchmarkSortChunks/CHUNKS/rows=4096/cols=4/matchLen=3/avgChunkSize=128-12       	   10000	    109190 ns/op	1200.39 MB/s
BenchmarkSortChunks/ALL/rows=4096/cols=4/matchLen=3/avgChunkSize=128-12          	    5000	    323842 ns/op	 404.74 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=2/matchLen=1/avgChunkSize=8-12        	    2000	    666526 ns/op	1573.19 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=2/matchLen=1/avgChunkSize=8-12           	     500	   3601791 ns/op	 291.13 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=2/matchLen=1/avgChunkSize=128-12      	    2000	    918969 ns/op	1141.04 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=2/matchLen=1/avgChunkSize=128-12         	     300	   4321204 ns/op	 242.66 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=1/avgChunkSize=8-12        	     500	   2545744 ns/op	 823.79 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=1/avgChunkSize=8-12           	     200	   7028614 ns/op	 298.37 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=1/avgChunkSize=128-12      	     300	   3745373 ns/op	 559.93 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=1/avgChunkSize=128-12         	     200	   8625811 ns/op	 243.13 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=2/avgChunkSize=8-12        	    1000	   2000503 ns/op	1048.31 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=2/avgChunkSize=8-12           	     200	   6517729 ns/op	 321.76 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=2/avgChunkSize=128-12      	    1000	   2076858 ns/op	1009.77 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=2/avgChunkSize=128-12         	     300	   5940460 ns/op	 353.03 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=3/avgChunkSize=8-12        	    1000	   1196730 ns/op	1752.40 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=3/avgChunkSize=8-12           	     300	   5142366 ns/op	 407.82 MB/s
BenchmarkSortChunks/CHUNKS/rows=65536/cols=4/matchLen=3/avgChunkSize=128-12      	    2000	   1058806 ns/op	1980.68 MB/s
BenchmarkSortChunks/ALL/rows=65536/cols=4/matchLen=3/avgChunkSize=128-12         	     300	   4392910 ns/op	 477.39 MB/s
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-LZgcmKx6JpNSF5hVhtI:b-62xrgu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/colvec_tmpl.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa-d335JJ93VJIKiD:-LZ_ZtxI8J5QC1XxV57U:bwnqegs) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/colvec_tmpl.go#L263)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I know this is messed up everywhere, but just realized that this is pretty silly - it's a bitmap, we can just bitwise OR the two null bitmaps.
</blockquote></details>

We don't seem to have direct access to `nulls` slice of `vec` unless we do type conversion. I think what you're suggesting is something like `m.nulls[i] |= vec.nulls[i]`, right?
___
*[pkg/sql/exec/deselector.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa9j298hlu91gdx7l:-LZ_XBY-8Km3oTLzuoKk:bhnj103) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/deselector.go#L19)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would say it deserves at least a very basic sanity check. I also would like to see a benchmark - I've always been curious how much it costs to remove the selection vector as many operators are simpler to understand without having to think about the selection vector. If it's cheap, we could just deselect unconditionally before certain operators.
</blockquote></details>

Done.

The benchmarks show that this "deselection" is pretty cheap (unless I messed the benchmark up):
```
BenchmarkDeselector/rows=2048/after_selection=1834-12         	  300000	      3834 ns/op	3826.81 MB/s
BenchmarkDeselector/rows=4096/after_selection=3668-12         	  300000	      4945 ns/op	5932.96 MB/s
BenchmarkDeselector/rows=16384/after_selection=14672-12       	  200000	     11409 ns/op	10287.95 MB/s
BenchmarkDeselector/rows=262144/after_selection=234752-12     	   10000	    151497 ns/op	12396.36 MB/s
```
___
*[pkg/sql/exec/deselector.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHaTJz-l44Nsxa-0q-:-LZ__LVY0nhxBW1NgWrn:bsz672d) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/deselector.go#L58)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What's the advantage of doing this as opposed to the `coalesce` operator, which I think also combines batches that are smaller than `ColBatchSize`? In general, it's better to give operators longer chunks of stuff to work on, since it makes the tight loops be able to do more before having to go back up and do type switches on columns again.
</blockquote></details>

The advantage was that was easier to reason about when there are tuples only from the single chunk in a batch (at least it was straightforward for me to hook it up to the general sorter this way right away).
___
*[pkg/sql/exec/operator.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZaar0FC6BV8JYKzjUT:-LZgbdYDEyoS_1YK7195:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/operator.go#L47)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you end up doing this this should call `reset` on its input.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZabSE7-maBSTGIrqFb:-LZauWlm8X65vMCfm3Pr:b23hvue) ([raw f [...]

2019-02-27 15:29 UTC, yuzefovich commented
I extracted deselector operator into a separate PR, and this one builds on top of #35207 and #35235, so please review those first.

2019-03-01 15:39 UTC, yuzefovich commented
I've rebased on top of the merged PRs, so this one is ready for another look.

2019-03-01 17:02 UTC, jordanlewis approved these changes
Nice work! I like the spooler abstraction you used here. It's pretty clean. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-LZuC583ETCp67I-6O17:btrmlbb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/operator.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZtuvnX8hK6Hpoi5f4m:-LZtuvnX8hK6Hpoi5f4n:b2qq860) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/operator.go#L33)):*
> ```Go
> }
> 
> type resetter interface {
> ```

This wants a comment. What does it mean to implement resetter? What is the contract? I think it wants to be something like "resetter is a testing interface that operators can implement if they can be reset during tests."

But the thing is as soon as you assume an operator can be reset for testing, you're also sort of expecting that all of its parents will also be reset, or else you get a weird situation where the benchmark isn't really testing what you thought it was anymore (this happened to me at one point).
___
*[pkg/sql/exec/sort_chunks.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu13XbAJdxwpEz0Noy:-LZu13XbAJdxwpEz0Noz:b-miiaha) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L34)):*
> ```Go
> 		// input is already ordered on all orderingCols, so there is nothing more
> 		// to sort.
> 		return &noopOperator{input: input}, nil
> ```

Can't you just `return input` here? Did I already ask you this and you explained why not?
___
*[pkg/sql/exec/sort_chunks.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu1rvW0Q34dg41LIUC:-LZu1rvW0Q34dg41LIUD:b-6b04dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L68)):*
> ```Go
> 			// explicitly reset the chunker because it will be reset by the sorter
> 			// as the sorter's input.
> 			if resetter, ok := c.sorter.(resetter); ok {
> ```

Hmm... I think this is a recipe for trouble. Now there are 2 competing expectations in my head of what `resetter` does - it looks like here you only want to be resetting the sorter itself, but in other contexts we want reset to reset the entire chain of operators.

I'm not sure what to do here exactly, but I do think we need to be careful. Perhaps we need to take a step back and think about what contracts we want on these operators. We now have `Init` and `reset`. Perhaps we should make `Init` invoke `reset` and also `Init` of its input, and have `reset` only modify itself. 
___
*[pkg/sql/exec/sort_chunks.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuA69k1ljbm8iK-4C8:-LZuA69k1ljbm8iK-4C9:b-od7x89) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L163)):*
> ```Go
> 	// bufferedValues is a buffer to store tuples when a chunk is bigger than
> 	// ColBatchSize or when the chunk is the last in the last read batch (we
> 	// don't know yet where the end of such chunk is).
> ```

nit: maybe it would be better to call this bufferedColumns, just so that later when you iterate over it it's clear that you're looking at whole columns not just values. But I'm not sure if `bufferedColumns` is that clear either.

Naming these "leftover values" comes up a lot. It would be nice if we had a clear name for these. Or even a nice abstraction to help operators implement this part, which can be tricky.
___
*[pkg/sql/exec/sort_chunks.go, line 225 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu86ML4nm_qXdMPO7N:-LZu86ML4nm_qXdMPO7O:b-div6vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L225)):*
> ```Go
> 			}
> 
> 			copy(s.partitionCol, zeroBoolVec)
> ```

I would add a general high level comment for this phase, something like:

"First, run the partitioners on our pre-sorted columns to determine the boundaries of the chunks to sort further."
___
*[pkg/sql/exec/sort_chunks.go, line 286 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu9_wl0Yp_kkjYLSla:-LZu9_wm3Z1dIsImYP3X:b2ph63n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L286)):*
> ```Go
> 			return readFromBuffer
> 		case chunkerEmittingFromBatch:
> 			if s.chunksProcessedIdx+1 < len(s.chunks) {
> ```

Comment here - what is this condition exactly?
___
*[pkg/sql/exec/sort_chunks.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu9pd_EKVVzqBh7zgi:-LZu9pd_EKVVzqBh7zgj:b-bssvap) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L291)):*
> ```Go
> 				return readFromBatch
> 			}
> 			if s.chunksProcessedIdx == len(s.chunks)-1 {
> ```

This also seems similar to the last condition... can you simplify the ifs a little bit? Seems like it should be a tri-conditional.
___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuBp206sj1dVINpuHQ:-LZuBp206sj1dVINpuHR:b40k9v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/tuples_differ_tmpl.go#L65)):*
> ```Go
> // */}}
> 
> func tuplesDiffer(t types.T) (func(ColVec, int, ColVec, int, *bool), error) {
> ```

I'd comment this even though it's redundant with below.

Also, there's no point here in having a _TYPE function, is there? Nobody's calling those things directly. I'dj ust inline the body of tuplesDiffer_TYPE into the case statement in this function.
___
*[pkg/sql/exec/colvec_tmpl.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa-d335JJ93VJIKiD:-LZu6y2552gMve3geLNr:brewksu) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/colvec_tmpl.go#L263)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We don't seem to have direct access to `nulls` slice of `vec` unless we do type conversion. I think what you're suggesting is something like `m.nulls[i] |= vec.nulls[i]`, right?
</blockquote></details>

Yeah exactly. Can fix this later though.


<!-- Sent from Reviewable.io -->

2019-03-01 17:57 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/operator.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZtuvnX8hK6Hpoi5f4m:-LZuOSDIEH_6o130uRXP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/operator.go#L33)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This wants a comment. What does it mean to implement resetter? What is the contract? I think it wants to be something like "resetter is a testing interface that operators can implement if they can be reset during tests."

But the thing is as soon as you assume an operator can be reset for testing, you're also sort of expecting that all of its parents will also be reset, or else you get a weird situation where the benchmark isn't really testing what you thought it was anymore (this happened to me at one point).
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort_chunks.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu13XbAJdxwpEz0Noy:-LZuDwjTB0TWUBtuCk73:b-lbou39) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L34)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can't you just `return input` here? Did I already ask you this and you explained why not?
</blockquote></details>

Yes, you're right. Before was a slightly different situation I believe, but the code has been refactored and the noop is no longer needed.
___
*[pkg/sql/exec/sort_chunks.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu1rvW0Q34dg41LIUC:-LZuNs-f5TiCStAVD7Zm:b-9ju5o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L68)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... I think this is a recipe for trouble. Now there are 2 competing expectations in my head of what `resetter` does - it looks like here you only want to be resetting the sorter itself, but in other contexts we want reset to reset the entire chain of operators.

I'm not sure what to do here exactly, but I do think we need to be careful. Perhaps we need to take a step back and think about what contracts we want on these operators. We now have `Init` and `reset`. Perhaps we should make `Init` invoke `reset` and also `Init` of its input, and have `reset` only modify itself. 
</blockquote></details>

Synced it up offline, my usage of `reset` on the `chunker` was inappropriate which was confusing to everyone (myself including).
___
*[pkg/sql/exec/sort_chunks.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuA69k1ljbm8iK-4C8:-LZuJbnX5nhpuI7DOka4:b-a5zs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L163)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: maybe it would be better to call this bufferedColumns, just so that later when you iterate over it it's clear that you're looking at whole columns not just values. But I'm not sure if `bufferedColumns` is that clear either.

Naming these "leftover values" comes up a lot. It would be nice if we had a clear name for these. Or even a nice abstraction to help operators implement this part, which can be tricky.
</blockquote></details>

Done, I think `bufferedColumns` is clearer. Not sure what the abstraction would be though.
___
*[pkg/sql/exec/sort_chunks.go, line 225 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu86ML4nm_qXdMPO7N:-LZuEfpE6bq1r6cMVfjR:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L225)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would add a general high level comment for this phase, something like:

"First, run the partitioners on our pre-sorted columns to determine the boundaries of the chunks to sort further."
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec/sort_chunks.go, line 286 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu9_wl0Yp_kkjYLSla:-LZuFQfPEkYi6FGnYdvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L286)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comment here - what is this condition exactly?
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort_chunks.go, line 291 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZu9pd_EKVVzqBh7zgi:-LZuFsA87tNAwRmLFp53:bohqzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/sort_chunks.go#L291)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This also seems similar to the last condition... can you simplify the ifs a little bit? Seems like it should be a tri-conditional.
</blockquote></details>

Agreed, done.
___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuBp206sj1dVINpuHQ:-LZuHU7E8jgmivebyO1o:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d28287772ab5f18cdda2e2fa4cf60c9e507f68aa/pkg/sql/exec/tuples_differ_tmpl.go#L65)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'd comment this even though it's redundant with below.

Also, there's no point here in having a _TYPE function, is there? Nobody's calling those things directly. I'dj ust inline the body of tuplesDiffer_TYPE into the case statement in this function.
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuJ2Eq2l9sbHePsfcc:-LZuJ2Eq2l9sbHePsfcd:b1g8jr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a141b9338aebb53a4355da8063de633d1a3c9e53/pkg/sql/exec/tuples_differ_tmpl.go#L41)):*
> ```Go
> var _ bytes.Buffer
> 
> // TODO(yuzefovich): make build complains about this import for some reason.
> ```

Do we need this `apd.Decimal` import? `make` was complaining about it.
___
*[pkg/sql/exec/colvec_tmpl.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZHa-d335JJ93VJIKiD:-LZuIKnK4zDofUvWkvEi:bex4giu) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/colvec_tmpl.go#L263)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah exactly. Can fix this later though.
</blockquote></details>

Added TODOs.


<!-- Sent from Reviewable.io -->

2019-03-01 23:56 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-LZvfsef2QkE3w2axX70:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuJ2Eq2l9sbHePsfcc:-LZvfd3ZC3zPA17gKjHi:bu99bnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a141b9338aebb53a4355da8063de633d1a3c9e53/pkg/sql/exec/tuples_differ_tmpl.go#L41)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we need this `apd.Decimal` import? `make` was complaining about it.
</blockquote></details>

If it compiles fine without it, it's not necessary. I'm surprised it works with that though, doesn't the ASSIGN_NE expansion for decimal need the `apd` import?


<!-- Sent from Reviewable.io -->

2019-03-04 15:29 UTC, yuzefovich commented
@asubiotto @georgeutsin PTAL when you get a chance.

2019-03-04 17:15 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 12 files at r5, 1 of 4 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-:-L_8gzMO6Em9pnbKYpyN:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/sort.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZabSE7-maBSTGIrqFb:-L_8cnS06FDfXPW3RRZ0:bvauqxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L200)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done. I wasn't sure whether it is safe to take `cap` of `nil` slice.
</blockquote></details>

It is, but also note that if `p.order` is `nil`, only the first part of the if statement is evaluated.
___
*[pkg/sql/exec/sort.go, line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8d42Z6b5m696SIRJb:-L_8d42Z6b5m696SIRJc:bgz85ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort.go#L278)):*
> ```Go
> }
> 
> func (p *sortOp) sort() {
> ```

nit: Maybe add a comment that the tuples must have been `spooled` before calling `sort`?
___
*[pkg/sql/exec/sort_chunks.go, line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8ent5-E8mwbyKDQlI:-L_8ent5-E8mwbyKDQlJ:b-1k3iiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L61)):*
> ```Go
> 		batch := c.sorter.Next()
> 		if batch.Length() == 0 {
> 			if c.input.readFrom == inputDone {
> ```

I think this should be abstracted behind a `done()` or something, `readFrom` doesn't seem like it should be anything but internal to the chunker.
___
*[pkg/sql/exec/sort_chunks.go, line 73 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8f1xK6a6QVyRP6Pxa:-L_8f1xK6a6QVyRP6Pxb:b-bo5orb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L73)):*
> ```Go
> 				r.reset()
> 			} else {
> 				panic(fmt.Sprintf("sorter doesn't implement resetter interface"))
> ```

I think this is the first time we use `reset` outside of benchmarks. I think rather than panicking, you should consider creating an interface composed of `Operator` and `resetter` (`resettableOperator`?) and have `c.sorter` be of that type.
___
*[pkg/sql/exec/sort_chunks.go, line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8fOIP2Jk7C080-liA:-L_8fOIP2Jk7C080-liB:b-jsly27) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L109)):*
> ```Go
> 
> // readFrom indicates where the spooler needs to read tuples from for emitting.
> type readFrom int
> ```

nit: Maybe rename this to `chunkerReadingState`?
___
*[pkg/sql/exec/sort_chunks_test.go, line 167 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8gdDR0HZ7OY573b8S:-L_8gdDR0HZ7OY573b8T:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks_test.go#L167)):*
> ```Go
> }
> 
> func TestSortChunksRandomized(t *testing.T) {
> ```

Nice!
___
*[pkg/sql/exec/sort_chunks_test.go, line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8gIae7DBrVmIDLY-_:-L_8gIae7DBrVmIDLY-a:b-9l9csh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks_test.go#L177)):*
> ```Go
> 				ordCols[i].ColIdx = uint32(i)
> 				ordCols[i].Direction = distsqlpb.Ordering_Column_Direction(rng.Int() % 2)
> 				typs[i] = types.Int64
> ```

Would it make sense to randomize types as well?


<!-- Sent from Reviewable.io -->

2019-03-04 18:15 UTC, georgeutsin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/sort_chunks.go, line 334 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8tllD8GNJ4e_LBXdI:-L_8tllD8GNJ4e_LBXdJ:bqac2l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L334)):*
> ```Go
> // buffered tuples.
> func (s *chunker) buffer(start uint16, end uint16) {
> 	if start == 0 {
> ```

Why is this broken out into Append and AppendSlice? Both perform a slicing on the source array, so why not just use AppendSlice regardless of the value of start?
___
*[pkg/sql/exec/sort_chunks_test.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8uLcX1OHvV0nJ7Cz5:-L_8uLcX1OHvV0nJ7Cz6:b-strakk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks_test.go#L38)):*
> ```Go
> 		matchLen int
> 	}{
> 		{
> ```

nit: I did this for my pr, but I added a "description" field to each tuple, so that 
a) we can output exactly which test failed, which makes it easier to cross reference it with this array
b) provides documentation about the kind of test the tuples represent


<!-- Sent from Reviewable.io -->

2019-03-04 18:56 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/sort.go, line 200 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZabSE7-maBSTGIrqFb:-L_8sDg46s2Ve1NIqTNx:b-v50nz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/079f95fcdc925314339ec6f0f81b02c232cbd349/pkg/sql/exec/sort.go#L200)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It is, but also note that if `p.order` is `nil`, only the first part of the if statement is evaluated.
</blockquote></details>

Thanks. Yeah, I was wondering about that as well (I know that in Java the `if` conditions are evaluated only if necessary but wasn't sure about Go).
___
*[pkg/sql/exec/sort.go, line 278 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8d42Z6b5m696SIRJb:-L_8ss-w8RbbVAWvo9Up:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort.go#L278)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: Maybe add a comment that the tuples must have been `spooled` before calling `sort`?
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort_chunks.go, line 61 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8ent5-E8mwbyKDQlI:-L_8u3f3-8f-BVc0OHDi:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this should be abstracted behind a `done()` or something, `readFrom` doesn't seem like it should be anything but internal to the chunker.
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec/sort_chunks.go, line 73 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8f1xK6a6QVyRP6Pxa:-L_92OtF1N-Z9QVoMQgP:b5ol1vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L73)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this is the first time we use `reset` outside of benchmarks. I think rather than panicking, you should consider creating an interface composed of `Operator` and `resetter` (`resettableOperator`?) and have `c.sorter` be of that type.
</blockquote></details>

I like this idea, done.
___
*[pkg/sql/exec/sort_chunks.go, line 109 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8fOIP2Jk7C080-liA:-L_8tzmV7tHPOEDu06Kb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L109)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: Maybe rename this to `chunkerReadingState`?
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort_chunks.go, line 334 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8tllD8GNJ4e_LBXdI:-L_8vvKhByOBsYdSnC5r:bupn85d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks.go#L334)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

Why is this broken out into Append and AppendSlice? Both perform a slicing on the source array, so why not just use AppendSlice regardless of the value of start?
</blockquote></details>

Good point, done. I think initially I implemented the code that used only `start == 0` case, so I kept it after I extended the code. Nice catch.
___
*[pkg/sql/exec/sort_chunks_test.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8uLcX1OHvV0nJ7Cz5:-L_90Yrc5dlP_yB5UPOa:bpjyiev) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks_test.go#L38)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

nit: I did this for my pr, but I added a "description" field to each tuple, so that 
a) we can output exactly which test failed, which makes it easier to cross reference it with this array
b) provides documentation about the kind of test the tuples represent
</blockquote></details>

I like that idea. Done.
___
*[pkg/sql/exec/sort_chunks_test.go, line 177 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_8gIae7DBrVmIDLY-_:-L_8uUoW6jVZSh2u4FSq:bod6pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bddb17e77514a736e3a8c2a344e80bb76f9dc9dc/pkg/sql/exec/sort_chunks_test.go#L177)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Would it make sense to randomize types as well?
</blockquote></details>

Yeah, I think we should do that for both general sort and sort chunks. I left TODOs for that.
___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuJ2Eq2l9sbHePsfcc:-L_8riRf9rRuE8pTnsnU:bcx7c9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a141b9338aebb53a4355da8063de633d1a3c9e53/pkg/sql/exec/tuples_differ_tmpl.go#L41)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If it compiles fine without it, it's not necessary. I'm surprised it works with that though, doesn't the ASSIGN_NE expansion for decimal need the `apd` import?
</blockquote></details>

Yeah, I 'm not sure how this works. If I remove `apd` import, `make build` succeeds, but if I keep it, it fails (`pkg/sql/exec/tuples_differ.eg.go:18:2: imported and not used: "github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd"`), so I'll just remove it.


<!-- Sent from Reviewable.io -->

2019-03-04 19:03 UTC, georgeutsin approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_94P64DLBF5Nwht5SF:-L_94P64DLBF5Nwht5SG:b-2zonaq) (no related file):*
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> great work!

---


<!-- Sent from Reviewable.io -->

2019-03-04 19:32 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35082)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-L_94P64DLBF5Nwht5SF:-L_9BJm-20f2Hg0oVW4K:b-uaobgy) (no related file):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

:lgtm: great work!
</blockquote></details>

Thanks all for the reviews!

bors r+

---
___
*[pkg/sql/exec/tuples_differ_tmpl.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/35082#-LZuJ2Eq2l9sbHePsfcc:-L_9Awuc5kDp2neUbjvn:b8dyuww) ([raw file](https://github.com/cockroachdb/cockroach/blob/a141b9338aebb53a4355da8063de633d1a3c9e53/pkg/sql/exec/tuples_differ_tmpl.go#L41)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, I 'm not sure how this works. If I remove `apd` import, `make build` succeeds, but if I keep it, it fails (`pkg/sql/exec/tuples_differ.eg.go:18:2: imported and not used: "github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd"`), so I'll just remove it.
</blockquote></details>

Ok, I looked into this a little more. I believe the reason that `apd` package is not needed is that this template operates on `types.Decimal` and doesn't explicitly operate on `apd.Decimal`. The relevant generated part is:
```
	case types.Decimal:
		aCol := aColVec.Decimal()
		bCol := bColVec.Decimal()
		var unique bool
		unique = tree.CompareDecimals(&aCol[aTupleIdx], &bCol[bTupleIdx]) != 0
		*differ = *differ || unique
		return nil
```
and that `tree.CompareDecimals` does the comparison on `apd.Decimal`s.


<!-- Sent from Reviewable.io -->

2019-03-04 19:58 UTC, merged