opt: fix computation of apply join outer columns
cockroachdb/cockroach pull request #35171
Opened 2019-02-23 17:51 UTC by justinj

Previously, we would incorrectly compute the outer columns of an
apply-join, because we would not consider that some of the right input's
outer columns actually came from higher up in the tree, not from the
left input.

By fixing this, a new problem was uncovered that required fixing. The
following series of events led to an infinite loop of norm rules
applying:
* An outer join requests null rejection on some set of columns,
* that request travels up through an apply join,
* it eventually reaches a GroupBy that can provide null rejection via
  RejectNullsGroupBy,
* RejectNullsGroupBy creates a new filter and pushes it down,
* this new filter is unable to make it past the apply join that the
  request traveled through,
* RejectNullsGroupBy triggers again, since the null rejection request
  persists.

The fix was to stop null rejection requests if the join propagating
them already had a filter that could reject nulls. This implies that
null rejection was provided, but couldn't be pushed down, and the
request should stop here.

Unfortunately, we can't (easily) fix this by allowing filters to travel
through apply joins (via PushFilterIntoJoinRight), since that then
cycles with TryDecorrelateSelect (which is effectively the inverse of
that).

This also prevents decorrelation of an existing test case, which
requires further investigation.

Release note: None

2019-02-23 17:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35171)
<!-- Reviewable:end -->

2019-02-25 17:08 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ__8qF53Q1zaG7484X:-LZ__8qF53Q1zaG7484Y:bk7fjww) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/memo/logical_props_builder.go#L410)):*
> ```Go
> 		// right input.
> 		rightOuterCols := join.Child(1).(RelExpr).Relational().OuterCols
> 		boundOuterCols := rightOuterCols.Intersection(join.Child(0).(RelExpr).Relational().OutputCols)
> ```

We already did `DifferenceWith(inputCols)` above which includes all the left child OutputCols.. So maybe we can remove this entire block?
___
*[pkg/sql/opt/norm/testdata/rules/reject_nulls, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ_c6nGAq3_yulfeugH:-LZ_c6nGAq3_yulfeugI:btng4v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/norm/testdata/rules/reject_nulls#L620)):*
> ```
> # them.
> exprnorm
> (Root
> ```

[nit] I don't think you need the `Root` part as long as you don't execbuild it.


<!-- Sent from Reviewable.io -->

2019-02-25 18:21 UTC, rytaft requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @justinj)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ_sU410RSEPWyqI_93:-LZ_sU410RSEPWyqI_94:bdjzhbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/testutils/opttester/opt_tester.go#L591)):*
> ```Go
> 		}
> 		ot.seenRules.Add(int(ruleName))
> 		return true
> ```

This seems like it's doing full exploration -- not just normalization (I think you want to do what OptNorm is doing above).


<!-- Sent from Reviewable.io -->

2019-02-25 19:43 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35171)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ__8qF53Q1zaG7484X:-LZa938g6ut91NWI9hcx:b-cog35p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/memo/logical_props_builder.go#L410)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We already did `DifferenceWith(inputCols)` above which includes all the left child OutputCols.. So maybe we can remove this entire block?
</blockquote></details>

Oh, you're totally right! Deleted it.
___
*[pkg/sql/opt/norm/testdata/rules/reject_nulls, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ_c6nGAq3_yulfeugH:-LZa9Dwm1LniL6BMRXVY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/norm/testdata/rules/reject_nulls#L620)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I don't think you need the `Root` part as long as you don't execbuild it.
</blockquote></details>

Done.
___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ_sU410RSEPWyqI_93:-LZa9EhZBoJuVLIClyMV:b6hvjdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/testutils/opttester/opt_tester.go#L591)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This seems like it's doing full exploration -- not just normalization (I think you want to do what OptNorm is doing above).
</blockquote></details>

It's not actually, `exprgen.Build` doesn't run exploration over the built expression. Added a comment explaining.


<!-- Sent from Reviewable.io -->

2019-02-25 20:08 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-:-LZaGNBc-oCWV_j0BvH3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/opt/testutils/opttester/opt_tester.go, line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-LZ_sU410RSEPWyqI_93:-LZaGBU0AI75eA5qSVGH:b-l2keul) ([raw file](https://github.com/cockroachdb/cockroach/blob/bafd909cefb43a654e2ca2bedf8466e102471106/pkg/sql/opt/testutils/opttester/opt_tester.go#L591)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It's not actually, `exprgen.Build` doesn't run exploration over the built expression. Added a comment explaining.
</blockquote></details>

Cool - thanks!


<!-- Sent from Reviewable.io -->

2019-02-26 14:04 UTC, andy-kimball approved these changes
Seems we need to bring back cycle detection. I removed it thinking the Rule props were a good enough tool to prevent cycles, but this is the second known case where that unable to decorrelate due to not having the cycle detection.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35171#-:-LZe5WaTDLXtGmsoXF3a:b-6tg7dl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2019-02-26 16:52 UTC, justinj commented
bors r+

2019-02-26 17:41 UTC, merged