exec: extract spooling phase of sorter into a separate operator
cockroachdb/cockroach pull request #35207
Opened 2019-02-26 16:45 UTC by yuzefovich

Extracting spooling phase into a separate operator will allow us
to efficiently reuse sorting logic for sort chunks operator. The
benchmarks show no significant changes due to additional function
calls instead of accessing variables directly.

Before (with benchmark bug fixed):
```
BenchmarkSort/rows=2048/cols=1-12         	  100000	     18616 ns/op	 880.06 MB/s
BenchmarkSort/rows=2048/cols=2-12         	   10000	    122138 ns/op	 268.29 MB/s
BenchmarkSort/rows=2048/cols=4-12         	   10000	    210499 ns/op	 311.34 MB/s
BenchmarkSort/rows=16384/cols=1-12        	   10000	    147420 ns/op	 889.10 MB/s
BenchmarkSort/rows=16384/cols=2-12        	    2000	   1008754 ns/op	 259.87 MB/s
BenchmarkSort/rows=16384/cols=4-12        	    1000	   1693625 ns/op	 309.57 MB/s
BenchmarkSort/rows=262144/cols=1-12       	     500	   2361441 ns/op	 888.08 MB/s
BenchmarkSort/rows=262144/cols=2-12       	     100	  13967882 ns/op	 300.28 MB/s
BenchmarkSort/rows=262144/cols=4-12       	      50	  30452824 ns/op	 275.46 MB/s
```
After (with benchmark bug fixed):
```
BenchmarkSort/rows=2048/cols=1-12         	  100000	     18557 ns/op	 882.87 MB/s
BenchmarkSort/rows=2048/cols=2-12         	   10000	    123117 ns/op	 266.15 MB/s
BenchmarkSort/rows=2048/cols=4-12         	   10000	    211704 ns/op	 309.56 MB/s
BenchmarkSort/rows=16384/cols=1-12        	   10000	    149049 ns/op	 879.38 MB/s
BenchmarkSort/rows=16384/cols=2-12        	    2000	   1014123 ns/op	 258.49 MB/s
BenchmarkSort/rows=16384/cols=4-12        	    1000	   1670286 ns/op	 313.89 MB/s
BenchmarkSort/rows=262144/cols=1-12       	     500	   2379547 ns/op	 881.32 MB/s
BenchmarkSort/rows=262144/cols=2-12       	     100	  14311793 ns/op	 293.07 MB/s
BenchmarkSort/rows=262144/cols=4-12       	      50	  29759557 ns/op	 281.88 MB/s
```
And here is the benchmark of allSpooler:
```
BenchmarkAllSpooler/rows=2048/cols=1-12         	  200000	      6366 ns/op	2573.52 MB/s
BenchmarkAllSpooler/rows=2048/cols=2-12         	  100000	     12125 ns/op	2702.37 MB/s
BenchmarkAllSpooler/rows=2048/cols=4-12         	  100000	     23711 ns/op	2763.85 MB/s
BenchmarkAllSpooler/rows=16384/cols=1-12        	   20000	     71757 ns/op	1826.61 MB/s
BenchmarkAllSpooler/rows=16384/cols=2-12        	   10000	    149136 ns/op	1757.74 MB/s
BenchmarkAllSpooler/rows=16384/cols=4-12        	    5000	    319455 ns/op	1641.19 MB/s
BenchmarkAllSpooler/rows=262144/cols=1-12       	    1000	   1407761 ns/op	1489.71 MB/s
BenchmarkAllSpooler/rows=262144/cols=2-12       	     500	   2794163 ns/op	1501.09 MB/s
BenchmarkAllSpooler/rows=262144/cols=4-12       	     300	   5278886 ns/op	1589.09 MB/s
```

Release note: None

2019-02-26 16:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35207)
<!-- Reviewable:end -->

2019-02-26 21:51 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/sort.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZfm-LU-_1uTlWtLeDp:-LZfm-LU-_1uTlWtLeDq:bnsb5o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b684a29e17116bae9f799d4a36721ee59b3f2a/pkg/sql/exec/sort.go#L71)):*
> ```Go
> // spooler is an operator that spools the data from its input.
> type spooler interface {
> 	Operator
> ```

I'm not sure whether this `spooler` guy should be an `Operator`. It needs to have `Init` method, but the concept of `Next` is not applicable (at least the way I see it). Maybe I should do something like:
```
type Initializer interface {
  Init ()
}

type Operator interface {
  Initializer
  Next()
}
```
and make `spooler` to be an `Initializer`. Thoughts?


<!-- Sent from Reviewable.io -->

2019-02-27 15:36 UTC, asubiotto requested changes
BTW, you can run `BENCHES=BenchmarkHashJoiner PKG=./pkg/sql/exec ./scripts/bench master <newbranch>` to automatically compare a new branch to an older branch (note that you have to commit your changes, otherwise the build on master will pick them up).

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-:-LZjV2cKCcva-glB7LCu:b-odjchf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/operator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZjX1j2EJ767fxc74SN:-LZjX1j2EJ767fxc74SO:bfqkftw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/operator.go#L42)):*
> ```Go
> 
> func (n *noopOperator) Init() {
> 	n.input.Init()
> ```

Looks like this `noopOperator` took its job description too literally
___
*[pkg/sql/exec/sort.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZfm-LU-_1uTlWtLeDp:-LZjWmcdADCDfBFh7cfM:bmssxiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b684a29e17116bae9f799d4a36721ee59b3f2a/pkg/sql/exec/sort.go#L71)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm not sure whether this `spooler` guy should be an `Operator`. It needs to have `Init` method, but the concept of `Next` is not applicable (at least the way I see it). Maybe I should do something like:
```
type Initializer interface {
  Init ()
}

type Operator interface {
  Initializer
  Next()
}
```
and make `spooler` to be an `Initializer`. Thoughts?
</blockquote></details>

Is there ever a requirement that a spooler be considered only an `Initializer`? If not you could just make `Init`/`init`? be part of the `spooler` interface and leave the operator interface alone.
___
*[pkg/sql/exec/sort.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZj_htK9-QBOtJWanXS:-LZj_htK9-QBOtJWanXT:b-vsp8vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/sort.go#L146)):*
> ```Go
> }
> 
> func (p *allSpooler) getValues(i int) ColVec {
> ```

Actually thinking about this more being implemented as an `Operator`, isn't this just `n := Next(); n.ColVec(i)`? Just that this spooler's `Next` will only return one batch and then a zero length batch for any other calls?
___
*[pkg/sql/exec/sort_test.go, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZj_HYr0AOKdRk1njug:-LZj_HYr0AOKdRk1njuh:blatbfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/sort_test.go#L241)):*
> ```Go
> 				receivedTuple := make(tuple, len(tc.typ))
> 				for j := 0; j < len(tc.typ); j++ {
> 					receivedTuple[j] = allSpooler.getValues(j).Col().([]int64)[i]
> ```

`getValues(j).Int64()`? Is there a need to copy? Unless I'm missing something, why not get the whole `ColVec` and compare column by column?


<!-- Sent from Reviewable.io -->

2019-02-27 15:58 UTC, yuzefovich reviewed
Good to know, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-:-LZjfI-V17L_LnAQBKik:bgzdldr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/operator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZjX1j2EJ767fxc74SN:-LZjbEEo9fnFNBsSIKsG:b4zutyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/operator.go#L42)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Looks like this `noopOperator` took its job description too literally
</blockquote></details>

Indeed :)
___
*[pkg/sql/exec/sort.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZfm-LU-_1uTlWtLeDp:-LZjbLyLAdW0Yo_iVTnt:b47il8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b684a29e17116bae9f799d4a36721ee59b3f2a/pkg/sql/exec/sort.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there ever a requirement that a spooler be considered only an `Initializer`? If not you could just make `Init`/`init`? be part of the `spooler` interface and leave the operator interface alone.
</blockquote></details>

I agree, it is not necessary.
___
*[pkg/sql/exec/sort.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZj_htK9-QBOtJWanXS:-LZjcJgmBJVCAMShmJh7:b7lam79) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/sort.go#L146)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Actually thinking about this more being implemented as an `Operator`, isn't this just `n := Next(); n.ColVec(i)`? Just that this spooler's `Next` will only return one batch and then a zero length batch for any other calls?
</blockquote></details>

`spooler` might return more tuples than `ColBatchSize`, so it cannot return batches as usual (unless we adjust the concept of "batch"). For example, this `allSpooler` will be returning all tuples that came from input (be it 1, 10, or 100k tuples). `chunker` (which will implement `spooler` interface) can also return pretty large number of tuples at once if they all belong to the same chunk. I started out by making this "spooler" an `Operator`, but it didn't really make sense to me. Also, at least in `chunker` case, this interface allows for more direct plugging into the general sorter - i.e. no copying necessary - which gives good performance gains.
___
*[pkg/sql/exec/sort_test.go, line 241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZj_HYr0AOKdRk1njug:-LZjf31PAn-Yocs2Cm-z:buhq0tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/sort_test.go#L241)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`getValues(j).Int64()`? Is there a need to copy? Unless I'm missing something, why not get the whole `ColVec` and compare column by column?
</blockquote></details>

Good point, done. There was no particular reason (only that I wrote tuple by tuple comparison earlier, and the concept stuck in my mind).


<!-- Sent from Reviewable.io -->

2019-02-28 18:19 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-:-LZpKKLKDfnQL69-v3C2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-02-28 21:23 UTC, jordanlewis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @yuzefovich)

___
*[pkg/sql/exec/operator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZjX1j2EJ767fxc74SN:-LZpx8zc4e6qs43q5jKE:b-fbzavr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/operator.go#L42)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Indeed :)
</blockquote></details>

Whoops! Nice find. While you're here, can you improve the comment on `Init`? Someting like:

```
If an operator has an input operator, it's responsible for calling Init on that input operator as well.
```
___
*[pkg/sql/exec/sort.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpxyvm6jyl6zJdMBFZ:-LZpxyvm6jyl6zJdMBF_:bk6hkbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L87)):*
> ```Go
> 
> // allSpooler is the spooler that spools all tuples from the input. It is used
> // by general sorter over the whole input.
> ```

nit: the general sorter
___
*[pkg/sql/exec/sort.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpy0n0BBD_wDeCfLU-:-LZpy0n0BBD_wDeCfLU0:b-8h98jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L91)):*
> ```Go
> 	input Operator
> 
> 	// inputTypes contains the types of all of the columns from input.
> ```

nit: the input
___
*[pkg/sql/exec/sort.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpz9i44X1maeBVR9b4:-LZpz9i44X1maeBVR9b5:b-tb9neg) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L109)):*
> ```Go
> }
> 
> func (p *allSpooler) init() {
> ```

This method doesn't reset `p.spooled`, so I'm suspicious the benchmark is kind of a no op except for the first round... is that right?


<!-- Sent from Reviewable.io -->

2019-02-28 21:33 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/operator.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZjX1j2EJ767fxc74SN:-LZpzu9s0WhkbV0jGUdm:bxvec61) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ccf3f784dc5585455be89f1fafe244949ddbec2/pkg/sql/exec/operator.go#L42)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Whoops! Nice find. While you're here, can you improve the comment on `Init`? Someting like:

```
If an operator has an input operator, it's responsible for calling Init on that input operator as well.
```
</blockquote></details>

Of course, done.
___
*[pkg/sql/exec/sort.go, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpxyvm6jyl6zJdMBFZ:-LZq--mw6PsDUDXISXHx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L87)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: the general sorter
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpy0n0BBD_wDeCfLU-:-LZq-2hpDW8AYX0sc-Ow:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L91)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: the input
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpz9i44X1maeBVR9b4:-LZq-BPq7zWJ_z94qHPV:bewo7l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L109)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This method doesn't reset `p.spooled`, so I'm suspicious the benchmark is kind of a no op except for the first round... is that right?
</blockquote></details>

But we're creating a new `allSpooler` on every iteration of the `for` loop. (Also, `spool` would have panicked if that was the case).


<!-- Sent from Reviewable.io -->

2019-03-01 01:27 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-:-LZqr9ZBAKcwozyRsARg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @yuzefovich)

___
*[pkg/sql/exec/sort.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35207#-LZpz9i44X1maeBVR9b4:-LZqr7Jh-lN0gFn8ud60:bu3zqf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/55223617763f0a4d93dff0f5c304139e37bf8444/pkg/sql/exec/sort.go#L109)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

But we're creating a new `allSpooler` on every iteration of the `for` loop. (Also, `spool` would have panicked if that was the case).
</blockquote></details>

My mistake, I see now.


<!-- Sent from Reviewable.io -->

2019-03-01 02:09 UTC, yuzefovich commented
Thanks for the reviews!

bors r+

2019-03-01 02:40 UTC, merged