exec: add deselector operator
cockroachdb/cockroach pull request #35235
Opened 2019-02-27 15:09 UTC by yuzefovich

Adds deselector operator that takes in batches and reorders and
omits tuples depending on the selection vector. If a batch comes in
with no selection vector, it is a noop. This operator is pretty cheap
and makes reasoning about other operators (e.g. in sort chunks) a lot
easier, and it could be useful in other places as well.

Benchmarks (with randomly ordered selection vector that omits about 10% of the rows):
```
BenchmarkDeselector/rows=2048/after_selection=1838-12         	  300000	      3854 ns/op	3815.02 MB/s
BenchmarkDeselector/rows=4096/after_selection=3676-12         	  300000	      4877 ns/op	6029.00 MB/s
BenchmarkDeselector/rows=16384/after_selection=14704-12       	  200000	     11310 ns/op	10400.54 MB/s
BenchmarkDeselector/rows=262144/after_selection=235264-12     	   10000	    143440 ns/op	13121.21 MB/s
```

Release note: None

2019-02-27 15:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35235)
<!-- Reviewable:end -->

2019-02-27 15:48 UTC, asubiotto requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/deselector_test.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjbqQgBq5MEbzcXj_7:-LZjbqQh-1vjSvJqVbY_:b-vxtcoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L54)):*
> ```Go
> 			sel:      []uint16{0, 1, 2},
> 			expected: tuples{{0}, {1}, {2}},
> 		},
> ```

Also add a test with no selection vector.
___
*[pkg/sql/exec/deselector_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcdtsEigjsTdEkLfQ:-LZjcdttAi8V3T76nwQS:b-aph8zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L95)):*
> ```Go
> 			b.ResetTimer()
> 			for i := 0; i < b.N; i++ {
> 				input := newRepeatableBatchSource(batch)
> ```

This should be used above the `ResetTimer`, right?
___
*[pkg/sql/exec/deselector_test.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcHO88s4n-A3JcIxV:-LZjcHO88s4n-A3JcIxW:b-l13qx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L98)):*
> ```Go
> 
> 				op := NewDeselectorOp(input, inputTypes)
> 				op.Init()
> ```

This is where a `resettable` interface is useful so you don't take into account the allocation of a whole `memBatch` in the benchmark. I guess you could also just reuse this operator without having to do anything to reset.
___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZjd68D-UwKmJXuZ-1p:bxkahzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
> ```Go
> func (s *repeatableBatchSource) Next() ColBatch {
> 	// TODO(yuzefovich): any reason for removing the selection vector here?
> 	//s.internalBatch.SetSelection(false)
> ```

I'm not sure cc @jordanlewis


<!-- Sent from Reviewable.io -->

2019-02-27 17:58 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/deselector_test.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjbqQgBq5MEbzcXj_7:-LZk32SI2A-0TBzcV-2J:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Also add a test with no selection vector.
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec/deselector_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcdtsEigjsTdEkLfQ:-LZk3U1f7TWdm4Ds-4sy:boi7vp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L95)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This should be used above the `ResetTimer`, right?
</blockquote></details>

I've copied the general approach from `BenchmarkSort`, and I guess we're keeping the generation of the data above `ResetTimer`, but creating input sources is negligible, so it is done within the `for ... b.N` loop (and reset timer should be outside of it). I adjusted it according to your comments, and now the benchmarks are:
```
BenchmarkDeselector/rows=2048/after_selection=1832-12         	 1000000	      1087 ns/op	13479.01 MB/s
BenchmarkDeselector/rows=4096/after_selection=3664-12         	 1000000	      2174 ns/op	13476.79 MB/s
BenchmarkDeselector/rows=16384/after_selection=14656-12       	  200000	      8759 ns/op	13384.91 MB/s
BenchmarkDeselector/rows=262144/after_selection=234496-12     	   10000	    140090 ns/op	13391.12 MB/s
```
___
*[pkg/sql/exec/deselector_test.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcHO88s4n-A3JcIxV:-LZk5WXw13Gbzj0yTy4f:bucy3dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L98)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is where a `resettable` interface is useful so you don't take into account the allocation of a whole `memBatch` in the benchmark. I guess you could also just reuse this operator without having to do anything to reset.
</blockquote></details>

Yeah, for this particular operator we don't need to reset since it doesn't keep any state.


<!-- Sent from Reviewable.io -->

2019-02-27 23:07 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-:-LZlBhLzDIJeEnLWg4ng:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-02-28 14:24 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @georgeutsin)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZoUGwf0aBxT5v1YKdc:b-5krmn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure cc @jordanlewis
</blockquote></details>

@jordanlewis are you ok with removing this part? I'm not sure what was the logic behind removing the selection vector there.


<!-- Sent from Reviewable.io -->

2019-02-28 14:31 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @georgeutsin)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZoVwaC8JlPQVD4PloE:b-kphxxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@jordanlewis are you ok with removing this part? I'm not sure what was the logic behind removing the selection vector there.
</blockquote></details>

Oh, you should keep this... if anybody downstream sets the selection vector on this batch (like a filter operator), the batch will keep its selection vector.

Maybe it's kind of a wart in the ColBatch design, but for now it's required for any operator that emits its own batch.


<!-- Sent from Reviewable.io -->

2019-02-28 14:32 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @georgeutsin)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZoWBWk9U-iHBF6xaoh:b-z68p4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh, you should keep this... if anybody downstream sets the selection vector on this batch (like a filter operator), the batch will keep its selection vector.

Maybe it's kind of a wart in the ColBatch design, but for now it's required for any operator that emits its own batch.
</blockquote></details>

I'm surprised this didn't fail any of the filter tests.


<!-- Sent from Reviewable.io -->

2019-02-28 14:49 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @georgeutsin)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZoYg6a38sErTEuFhmd:b-x63d84) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm surprised this didn't fail any of the filter tests.
</blockquote></details>

Wait, I'm not sure I follow: so you're saying to keep `s.internal.SetSelection(false)` untouched, right? But that prohibits me from setting a specified selection vector to test the `deselector` operator. Also, what do you mean by "the batch will keep its selection vector"? Can't we update the selection vector when a different operator emits it?


<!-- Sent from Reviewable.io -->

2019-02-28 14:51 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @georgeutsin)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZo_HurDpLI0saBVc8-:bwuk4hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Wait, I'm not sure I follow: so you're saying to keep `s.internal.SetSelection(false)` untouched, right? But that prohibits me from setting a specified selection vector to test the `deselector` operator. Also, what do you mean by "the batch will keep its selection vector"? Can't we update the selection vector when a different operator emits it?
</blockquote></details>

I can't seem to find a place that would use a `repeatableBatchSource` and later set a selection vector on the batch, so I'm a little confused by your responses.


<!-- Sent from Reviewable.io -->

2019-02-28 15:18 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZofWhB2ENrQGvWEGGT:byl7332) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I can't seem to find a place that would use a `repeatableBatchSource` and later set a selection vector on the batch, so I'm a little confused by your responses.
</blockquote></details>

The problem is just that if you had a test that used a repeatableBatchSource and a downstream operator that always set a selection vector, then after the first iteration of the operator, it would be getting a ColBatch with a selection vector from upstream set to whatever the downstream operator had last set it to.

Probably you want to extend `repeatableBatchSource` with an option to use a selection vector or not. Selection vectors are mutable, so if you want a particular one from your upstream batch source,  you have to make sure to reset it to that particular one on each iteration.


<!-- Sent from Reviewable.io -->

2019-02-28 16:16 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/utils_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjd68D-UwKmJXuZ-1o:-LZosdqk8rAJelJbbDqa:b-qmvw15) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/utils_test.go#L478)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The problem is just that if you had a test that used a repeatableBatchSource and a downstream operator that always set a selection vector, then after the first iteration of the operator, it would be getting a ColBatch with a selection vector from upstream set to whatever the downstream operator had last set it to.

Probably you want to extend `repeatableBatchSource` with an option to use a selection vector or not. Selection vectors are mutable, so if you want a particular one from your upstream batch source,  you have to make sure to reset it to that particular one on each iteration.
</blockquote></details>

Got it, thanks for the explanation. As you suggested, I extended `repeatableBatchSource` (or maybe I actually made it keep its promise of returning exactly the same batch forever).


<!-- Sent from Reviewable.io -->

2019-02-28 17:54 UTC, asubiotto approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/deselector_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcdtsEigjsTdEkLfQ:-LZpELILBPcy08NsNKu1:b-bld6l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L95)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I've copied the general approach from `BenchmarkSort`, and I guess we're keeping the generation of the data above `ResetTimer`, but creating input sources is negligible, so it is done within the `for ... b.N` loop (and reset timer should be outside of it). I adjusted it according to your comments, and now the benchmarks are:
```
BenchmarkDeselector/rows=2048/after_selection=1832-12         	 1000000	      1087 ns/op	13479.01 MB/s
BenchmarkDeselector/rows=4096/after_selection=3664-12         	 1000000	      2174 ns/op	13476.79 MB/s
BenchmarkDeselector/rows=16384/after_selection=14656-12       	  200000	      8759 ns/op	13384.91 MB/s
BenchmarkDeselector/rows=262144/after_selection=234496-12     	   10000	    140090 ns/op	13391.12 MB/s
```
</blockquote></details>

Aren't these the original benchmark numbers?


<!-- Sent from Reviewable.io -->

2019-02-28 21:16 UTC, yuzefovich reviewed
I also measured the performance of the combination of `deselector` and `coalescer`, and the benchmarks are:
```
BenchmarkDeselectorCoalescer/rows=2048/after_selection=1836-12         	 1000000	      2338 ns/op	6280.77 MB/s
BenchmarkDeselectorCoalescer/rows=4096/after_selection=3672-12         	  300000	      4080 ns/op	7198.61 MB/s
BenchmarkDeselectorCoalescer/rows=16384/after_selection=14688-12       	  100000	     16870 ns/op	6965.10 MB/s
BenchmarkDeselectorCoalescer/rows=262144/after_selection=235008-12     	    5000	    267331 ns/op	7032.72 MB/s
BenchmarkDeselectorCoalescer/rows=2048/after_selection=210-12          	 2000000	       707 ns/op	2376.08 MB/s
BenchmarkDeselectorCoalescer/rows=4096/after_selection=420-12          	 1000000	      1317 ns/op	2549.41 MB/s
BenchmarkDeselectorCoalescer/rows=16384/after_selection=1680-12        	  200000	      6495 ns/op	2069.20 MB/s
BenchmarkDeselectorCoalescer/rows=262144/after_selection=26880-12      	   20000	     87678 ns/op	2452.59 MB/s
```
So I believe whenever we're implementing a new `Operator`, we should implement it thinking that incoming batches have no selection vectors, run the benchmarks of the new operator, and if the throughput numbers are less than say 1GB/s, we should just put a deselector-coalescer pair on top of the input and not implement the non-nil selection vector case. Some operators, however, seem to be performing a lot better when they are optimized for batches with selection vectors (for example, sum aggregator performance decreased by 4-6x when I put the deselector-coalescer pair in front of it).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-:-LZpvwSFAveNssIGCUuU:b-moz6d2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @jordanlewis)

___
*[pkg/sql/exec/deselector_test.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35235#-LZjcdtsEigjsTdEkLfQ:-LZpv7u99I1yu3adwdGA:bnkwxzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/35af29383657eb74ce0f7b1d8e1c19860bdb742d/pkg/sql/exec/deselector_test.go#L95)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Aren't these the original benchmark numbers?
</blockquote></details>

No, those were the new benchmarks after adjustments. I made some more adjustments, and now benchmarks (with two probabilities of omitting rows of 0.1 and 0.9) are:
```
BenchmarkDeselector/rows=2048/after_selection=1832-12         	 1000000	      1262 ns/op	11606.69 MB/s
BenchmarkDeselector/rows=4096/after_selection=3664-12         	 1000000	      2461 ns/op	11906.96 MB/s
BenchmarkDeselector/rows=16384/after_selection=14656-12       	  200000	      9559 ns/op	12264.71 MB/s
BenchmarkDeselector/rows=262144/after_selection=234496-12     	   10000	    155676 ns/op	12050.41 MB/s
BenchmarkDeselector/rows=2048/after_selection=226-12          	 5000000	       287 ns/op	6297.21 MB/s
BenchmarkDeselector/rows=4096/after_selection=452-12          	 3000000	       525 ns/op	6875.31 MB/s
BenchmarkDeselector/rows=16384/after_selection=1808-12        	 1000000	      1949 ns/op	7420.07 MB/s
BenchmarkDeselector/rows=262144/after_selection=28928-12      	   50000	     30724 ns/op	7532.34 MB/s
```


<!-- Sent from Reviewable.io -->

2019-02-28 22:33 UTC, yuzefovich commented
Thanks for the reviews!

bors r+

2019-02-28 23:56 UTC, merged