server: introduce a new bootstrapping RPC service
cockroachdb/cockroach pull request #35367
Opened 2019-03-04 22:01 UTC by andreimatei

This patch introduces an RPC service comprised of two methods:
GetClusterInfo - returns the cluster id and version
AllocateNodeIDs - allocates node is and stores ids

The interface is not used at the moment, and I'm not yet sure how it's
going to be used exactly, but I'd like to get it in 19.1 so that 19.2
can use it.
The idea is that I'm pretty unhappy with the current way nodes join an
existing cluster. I'm unhappy that they conservatively start with a
stale cluster version only to find out the real version later, and I'm
unhappy that we have a nodeIDContainer and a clusterIDContainer
everywhwere, helping the node join process where the node needs to "join
the cluster" to some degree before it can allocate its own ids. The idea
of this interface is for a node to delegate this work to one that's
already in the cluster, in the hope that this will support untangle the
join process.

Release note: None

2019-03-04 22:01 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35367)
<!-- Reviewable:end -->

2019-03-05 03:10 UTC, bdarnell requested changes
I don't think we should be adding incompletely-designed network-accessible endpoints in the last month before release. We haven't cut a release branch yet but the switchover from alphas to betas is the feature freeze, so this is too late. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35367#-:-L_AosIt6CiJMaHAbycO:bucy3tf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @tbg)

___
*[pkg/server/init.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35367#-L_AnzKnBEa1RX6erLal:-L_AnzKnBEa1RX6erLam:b867186) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52f4f2eb8d968a2892ece8a3da69a0925cc1efb/pkg/server/init.go#L131)):*
> ```Go
> 
> // AllocateNodeIDs implements the serverpb.InitServer interface.
> func (s *initServer) AllocateNodeIDs(
> ```

What's the authentication story here?
___
*[pkg/server/serverpb/init.proto, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35367#-L_AoNfB4v3nDFVRAl5G:-L_AoNfB4v3nDFVRAl5H:b4uuu4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a52f4f2eb8d968a2892ece8a3da69a0925cc1efb/pkg/server/serverpb/init.proto#L54)):*
> ```protobuf
> service Init {
>   // Bootstrap an uninitialized cluster.
>   rpc Bootstrap(BootstrapRequest) returns (BootstrapResponse) {}
> ```

I think these should be separate from the service that handles bootstrapping. We want them to be available at all times, while bootstrap is only available before the first init. (we don't currently completely deactivate the initServer, but we'd like to - the TODO for that even has your name on it). In fact, their availability is disjoint - Bootstrap is only available before we know our cluster ID and the others are only available after. 


<!-- Sent from Reviewable.io -->

2019-03-06 11:42 UTC, tbg commented
Agreed with Ben, I also like this line of work but let's pick it up again
after the release is out the door.

On Tue, Mar 5, 2019 at 4:10 AM Ben Darnell <notifications@github.com> wrote:

> *@bdarnell* requested changes on this pull request.
>
> I don't think we should be adding incompletely-designed network-accessible
> endpoints in the last month before release. We haven't cut a release branch
> yet but the switchover from alphas to betas is the feature freeze, so this
> is too late.
>
> *Reviewable
> <https://reviewable.io/reviews/cockroachdb/cockroach/35367#-:-L_AosIt6CiJMaHAbycO:bucy3tf>*
> status: [image: :shipit:] complete! 0 of 0 LGTMs obtained (waiting on
> @andreimatei <https://github.com/andreimatei>, @bdarnell
> <https://github.com/bdarnell>, and @tbg <https://github.com/tbg>)
>
> ------------------------------
>
> *pkg/server/init.go, line 131 at r1
> <https://reviewable.io/reviews/cockroachdb/cockroach/35367#-L_AnzKnBEa1RX6erLal:-L_AnzKnBEa1RX6erLam:b867186>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/a52f4f2eb8d968a2892ece8a3da69a0925cc1efb/pkg/server/init.go#L131>):*
>
> // AllocateNodeIDs implements the serverpb.InitServer interface.func (s *initServer) AllocateNodeIDs(
>
> What's the authentication story here?
> ------------------------------
>
> *pkg/server/serverpb/init.proto, line 54 at r1
> <https://reviewable.io/reviews/cockroachdb/cockroach/35367#-L_AoNfB4v3nDFVRAl5G:-L_AoNfB4v3nDFVRAl5H:b4uuu4n>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/a52f4f2eb8d968a2892ece8a3da69a0925cc1efb/pkg/server/serverpb/init.proto#L54>):*
>
> service Init {
>   // Bootstrap an uninitialized cluster.
>   rpc Bootstrap(BootstrapRequest) returns (BootstrapResponse) {}
>
> I think these should be separate from the service that handles
> bootstrapping. We want them to be available at all times, while bootstrap
> is only available before the first init. (we don't currently completely
> deactivate the initServer, but we'd like to - the TODO for that even has
> your name on it). In fact, their availability is disjoint - Bootstrap is
> only available before we know our cluster ID and the others are only
> available after.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/35367#pullrequestreview-210474807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE135P7pAp5AQpstbmSH7lXGs6ftU-TYks5vTeAfgaJpZM4bdTA7>
> .
>

2019-03-16 20:06 UTC, andreimatei reviewed
ok, the nays have it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35367#-:-La76BAXCE5xDVXgwnm4:b-pqexak)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)



<!-- Sent from Reviewable.io -->

2019-03-16 20:06 UTC, closed without merging