sql: produce telemetry for usage of relational operators
cockroachdb/cockroach pull request #35679
Opened 2019-03-13 11:54 UTC by knz

This adds telemetry for use of opt nodes at the end of
optimizations (in the exec build phase).

The telemetry counters have the form `sql.plan.opt.node.xxxxx`.

Release note (sql change): CockroachDB will now report uses of the
various relational logical plan operators in telemetry, when telemetry
is enabled, to help guide future optimization efforts.

2019-03-13 11:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35679)
<!-- Reviewable:end -->

2019-03-13 11:55 UTC, knz commented
Requested by @awoods187, @jordanlewis sent it my way.

2019-03-13 13:40 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @knz)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-L_rEa9SAT3qU8JFdBVF:-L_rEa9SAT3qU8JFdBVG:bh3jp9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33370c9d944016006f38f4a15a1921bfaf6c9f0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L155)):*
> ```Go
> 
> 	// Collect usage telemetry for all relational nodes.
> 	telemetry.Inc(opt.OpTelemetryCounters[e.Op()])
> ```

This looks like it results in a bunch of atomic writes on every plan.. Can you run the `sql/opt/bench` benchmarks? (though I'm more worried of a loaded system with many cores which wouldn't be covered by the benchmarks)

Perhaps we should only record operators of interest, for most of them I don't think we care. We can add a `Telemetry` tag to the relevant operators. I can help come up with a list (though I'm not sure what the intention is for this data, maybe you or @awoods187 can explain?)

Also, this should be disabled if this is performed as part of an apply join, otherwise we'd be counting how many left rows that apply join query had.
___
*[pkg/sql/opt/optgen/cmd/optgen/telemetry_gen.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-L_rEE-E4JDnjodcZ_pe:-L_rEE-F7o32CAwegjbH:b-raimdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33370c9d944016006f38f4a15a1921bfaf6c9f0/pkg/sql/opt/optgen/cmd/optgen/telemetry_gen.go#L38)):*
> ```Go
> 	g.sorted = sortDefines(compiled.Defines)
> 
> 	fmt.Fprintf(g.w, "package opt\n\n")
> ```

Can you add a testdata file in `cmd/optgen/testdata`? It's useful to see an example of what the code looks like.


<!-- Sent from Reviewable.io -->

2019-03-13 14:08 UTC, knz commented
Your questions are reasonable but I do not have the answers.

- I don't know the operators of interest, although perhaps I can just focus on joins for now.
- I don't know anything about apply joins (@jordanlewis please advise)
- I don't know how to produce the `testdata` for optgen (nor how to test it)

2019-03-13 14:20 UTC, RaduBerinde commented
Looking at https://github.com/cockroachlabs/registration/issues/198 and https://github.com/cockroachlabs/registration/issues/199 we probably care about the join and group by variations and maybe sort.

For the third point look at `cmd/optgen/testdata/ops`. You can probably copy that example verbatim and change the directive to `optgen telemetry test.opt` and run the test with `TESTFLAGS=-rewrite` to populate the output. Btw you can also consider folding this new code into "ops" (i.e. `operator.og.go`) instead of a separate file.

2019-03-20 12:50 UTC, RaduBerinde commented
@knz if you want I can help with adding a `Telemetry` tag so we only have counters for a specific set of operators.

2019-03-20 13:04 UTC, knz commented
> @knz if you want I can help with adding a Telemetry tag so we only have counters for a specific set of operators.

Yes thanks.

2019-03-20 15:06 UTC, RaduBerinde commented
@knz I pushed two commits. One replaces the optgen change with a telemetry tag and a bit of code. The other disables telemetry inside the apply re-planning. Let me know what you think.

2019-03-26 19:25 UTC, RaduBerinde commented
@justinj @rytaft can one of you take a look over this before I merge it?

2019-03-26 19:54 UTC, justinj commented on pkg/sql/opt/exec/execbuilder/builder.go
> +	b.disableTelemetry = true
This doesn't appear to be consulted?

2019-03-26 20:42 UTC, rytaft commented
taking a look now





<!-- Sent from Reviewable.io -->

2019-03-26 20:57 UTC, rytaft requested changes
I have the same question as @justinj below... otherwise looks good

> Reviewed 7 of 7 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-:-LavmHQZAPPGTaJKL60n:b-v0ltt8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, and @knz)

___
*[pkg/sql/opt/telemetry.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-Lavl-ZN6ex-JDvsCbmd:-Lavl-ZN6ex-JDvsCbme:btnj08c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d7afd1da4cd4feca737afb02c2ba5022470ee6/pkg/sql/opt/telemetry.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

[nit] 2019
___
*[pkg/sql/sqltelemetry/opt.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-Lavkqmn-b21-63bEGa-:-Lavkqmo78qDqpjeDk6W:b-rjdo3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b33370c9d944016006f38f4a15a1921bfaf6c9f0/pkg/sql/sqltelemetry/opt.go#L24)):*
> ```Go
> 
> // OptNodeCounter should be incremented every time a node of the given
> // type is encountered at the end of the query optimization (i.e.  it
> ```

[nit] extra space after i.e.


<!-- Sent from Reviewable.io -->

2019-03-27 13:54 UTC, RaduBerinde approved these changes
TFTRs! Updated (and squashed + rebased).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-:-LazQVF79_PIeA0rd-i7:b-aajjk3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, and @knz)

___
*[pkg/sql/opt/exec/execbuilder/builder.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-LaQcoL5OcgYztFynPdW-r3-56:-LazQOfzCe1uwW60QhAm:bnozg5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aee019dd9ff8e70ff9d89b83b3ccc81729d5e49/pkg/sql/opt/exec/execbuilder/builder.go#L56)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This doesn't appear to be consulted?
</blockquote></details>

Oops, fixed and added a test.


<!-- Sent from Reviewable.io -->

2019-03-27 14:16 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/builder.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-LaQcoL5OcgYztFynPdW-r3-56:-LazVS540e0kYtM592x6:bms7l8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aee019dd9ff8e70ff9d89b83b3ccc81729d5e49/pkg/sql/opt/exec/execbuilder/builder.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oops, fixed and added a test.
</blockquote></details>

Doesn't look like you pushed...


<!-- Sent from Reviewable.io -->

2019-03-27 14:23 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, @knz, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/builder.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-LaQcoL5OcgYztFynPdW-r3-56:-LazX4P30FY-tLnEiovp:b-6xgsjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3aee019dd9ff8e70ff9d89b83b3ccc81729d5e49/pkg/sql/opt/exec/execbuilder/builder.go#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Doesn't look like you pushed...
</blockquote></details>

Oops, forgot this wasn't in my fork. Should be up now.


<!-- Sent from Reviewable.io -->

2019-03-27 14:28 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35679#-:-LazYDeI3Bc3jG5QlozN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @jordanlewis, @justinj, and @knz)



<!-- Sent from Reviewable.io -->

2019-03-27 18:24 UTC, RaduBerinde commented
Had to revert the test, the counters are global so we can't rely on the counter values if there are tests running in parallel.

2019-03-28 15:35 UTC, RaduBerinde commented
bors r+

2019-03-28 19:55 UTC, RaduBerinde commented
bors r-

2019-03-28 20:47 UTC, RaduBerinde commented
Fixed a minor issue in the test, it was accidentally picking up some other counter because of the lax condition. And because counters are global :/

bors r+

2019-03-29 13:55 UTC, RaduBerinde commented
bors r+

2019-03-29 14:21 UTC, merged