[poc,dnm] storage: delay application of preemptive snapshots
cockroachdb/cockroach pull request #35786
Opened 2019-03-15 12:20 UTC by tbg

Preemptive snapshots are sent to a Store (by another Store) as part of
the process of adding a new Replica to a Range. The sequence of events
is:

1. send a preemptive snapshot (replicaID=0) to the target
1. target creates a Replica from the preemptive snapshot (replicaID=0)
1. allocate new replicaID and add the target officially under that
replicaID
1. success (replicaID=nonzero)

They are problematic for a variety of reasons:

1. they introduce a Replica state, namely that of Replicas that have
   data but don't have a replicaID. Such replicas can't serve traffic
   and can't even have an initialized Raft group, so they're barely
   Replicas at all. Every bit of code in Replica needs to know about
   that.
2. the above state is implemented in an ad-hoc fashion and adds
   significantly to the complexity of the Store/Replica codebase.
3. Preemptive snapshots are subject to accidental garbage collection.
   There's currently no mechanism to decide whether a preemptive
   snapshot is simply waiting to be upgraded or whether it's abandoned.
   Accidental deletion causes another snapshot (this time Raft) to be
   sent.
4. Adding to 1., there are transitions between regular Replicas and
   preemptive snapshots that add additional complexity. For example,
   a regular snapshot can apply on top of a preemptive snapshot and
   vice versa. We try to prevent some of them but there are technical
   problems.
5. Preemptive snapshots have a range descriptor that doesn't include
   the Replica created from them. This is another gotcha that code
   needs to be aware of. (we cannot fix this in the first iteration,
   but it will be fixed when [learner replicas] are standard)

Our answer to all but the last of these problems is that we want to
remove the concept of preemptive snapshots altogether and instead rely
on [learner replicas]. This is a Raft concept denoting essentially a
member of a replication group without a vote. By replacing the
preemptive snapshot with the addition of a learner replica (before
upgrading to a full voting member), preemptive snapshots are replaced by
full replicas with a flag set.

However, as often the case, the interesting question becomes that
of the migration, or, the possibility of running a mixed version
cluster in which one node knows about these changes and another
doesn't. The basic requirement that falls out of this is that we
have to be able to send preemptive snapshots to followers even
using the new code, and we have to be able to receive preemptive
snapshots using the new code (though that code will go cold once
the cluster setting upgrade has happened).

Fortunately, sending and receiving preemptive snapshots is not what
makes them terrible. In fact, the code that creates and receives
preemptive snapshots is 100% shared with that for Raft snapshots.  The
complexity surrounding preemptive snapshots come from what happens when
they are used to create a Replica object too early, but this is an
implementation detail not visible across RPC boundaries.

This suggests investigating how we can receive preemptive snapshots
without actually using any of the internal code that handles them, so
that this code can be removed in 19.2. The basic idea is that we will
write the preemptive snapshot to a temporary location on disk (instead
of creating a Replica from it, and apply it as a Raft snapshot the
moment we observe a local Replica for the matching RangeID created as a
full member of the Raft group (i.e. with nonzero replicaID). This is
sketched out in this PR without dwelling on the details, however some
known problems that would need to be fixed are spelled out below.

Problems to address:

- stash in streaming fashion: to smooth out IO usage. The POC buffers
all into memory and then writes to disk in one fell swoop. Shortly
thereafter, we suck back into memory and shove into RocksDB in one go.
We can smooth out everything except the RocksDB part ([SST snapshots]
will address that).
- GC of obsolete stashed snapshots: time-based or size-based should
both work relatively well.
- fix/test the throttling (previously, snapshot application was
throttled due to inbound network bandwidth throttling, now it's
decoupled from that). At the very least, need to run testing for this.
- locking around creation of snapshot stashes and their reading. This
is hacky right now. Do snap stashes need to be disambiguated?
- locking when feeding the snap as a Raft snapshot. Needs some light
  refactoring for a version of s.processRaftSnapshotRequest with less
  recursion.

See the companion POC [learner replicas] which doesn't bother about the
migration but explores actually using learner replicas. When learner
replicas are standard, 5. above is also mostly addressed: the replica
will always be contained in its range descriptor, even though it may be
as a learner.

[learner replicas]: XXX
[SST snapshots]: https://github.com/cockroachdb/cockroach/pull/25134

Release note: None

2019-03-15 12:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/35786)
<!-- Reviewable:end -->

2019-04-08 19:33 UTC, tbg commented
I pulled on this thread a little more. Unfortunately, just delaying preemptive snapshots isn't enough for what I wanted to accomplish.

The basic motivation for getting rid of preemptive snapshots is to get rid of replicas without a replicaID, but preemptive snapshots are only one source of them. We also notably have a replica without a replicaID if a replica is fully added (after a delayed preemptive snap) and catching up on the log, but hasn't received the entry that adjusts the range descriptor to include the replica itself. In-memory, there will be a replicaID taken from incoming raft messages, but it won't survive a restart and so on restart the data looks like a preemptive snapshot again. We also use zero replicaIDs in a few other places, notably splits.

When we acquire a split lock (i.e. the raftMu of the RHS) we pass a replicaID of zero to `getOrCreateReplica`. We can't use the "real" replicaID there because that replicaID will only be valid *if* the split commits, but we're just evaluating it and don't want to leave a replica behind. (See https://github.com/cockroachdb/cockroach/issues/21146 for similar problems). I think the way it should work is that the split lock is either a) the raftMu of a preexisting replica (i.e. some other replica of the RHS has already been created, and has sent us a message) in which case the replicaID is known or b) we introduce a placeholder that temporarily drops incoming messages for the rhs' rangeID. Maybe there's a better option, but I'm not going to be able to come up with it tonight.

2019-04-09 10:29 UTC, tbg commented
I think I found a buglet in Raft that was exposed by my latest (now pushed) version of these changes, and thankfully caught in `TestAdminAPINonTableStats` (thanks, @celiala!).

Basically, when Raft applies a config change that adds a new peer, it doesn't seem to be reaching out to that peer proactively. It takes waiting for the next round of heartbeats (or next proposal) to do the job. With delayed snapshots, this doesn't just delay the catch-up of the newly added replica, but instead delays the *creation* of the replica in the first place, and that's what the test caught because it wasn't waiting for long enough. In the logs, I see this play out as follows:

> I190409 10:23:58.397987 298 storage/store_snapshot.go:875  [n1,replicate,s1,r8/1:/Table/1{2-3}] sending preemptive snapshot d0e7b8fd at applied index 28
I190409 10:23:58.398156 298 storage/store_snapshot.go:918  [n1,replicate,s1,r8/1:/Table/1{2-3}] streamed snapshot to (n2,s2):?: kv pairs: 50, log entries: 0, rate-limit: 8.0 MiB/sec, 0.00s
I190409 10:23:58.398409 298 storage/replica_command.go:796  [n1,replicate,s1,r8/1:/Table/1{2-3}] change replicas (ADD_REPLICA (n2,s2):2): read existing descriptor r8:/Table/1{2-3} [(n1,s1):1, next=2, gen=0]
I190409 10:23:58.399773 298 storage/replica_raft.go:396  [n1,s1,r8/1:/Table/1{2-3}] proposing ADD_REPLICA((n2,s2):2): updated=[(n1,s1):1 (n2,s2):2] next=3

(replicate queue goes off to do other things, and comes back):

> I190409 10:23:58.483197 23 storage/store_snapshot.go:875  [n1,replicate,s1,r8/1:/Table/1{2-3}] sending preemptive snapshot 85ffb5ef at applied index 30
I190409 10:23:58.483303 23 storage/store_snapshot.go:918  [n1,replicate,s1,r8/1:/Table/1{2-3}] streamed snapshot to (n3,s3):?: kv pairs: 52, log entries: 0, rate-limit: 8.0 MiB/sec, 0.00s
I190409 10:23:58.483561 23 storage/replica_command.go:796  [n1,replicate,s1,r8/1:/Table/1{2-3}] change replicas (ADD_REPLICA (n3,s3):3): read existing descriptor r8:/Table/1{2-3} [(n1,s1):1, (n2,s2):2, next=3, gen=0]
I190409 10:23:58.484000 723 storage/replica_raftstorage.go:828  [n2,s2,r8/2:{-}] applying delayed preemptive snapshot at index 28 (id=d0e7b8fd, encoded size=4557, 1 rocksdb batches, 0 log entries)
I190409 10:23:58.484203 723 storage/replica_raftstorage.go:834  [n2,s2,r8/2:/Table/1{2-3}] applied delayed preemptive snapshot in 0ms [clear=0ms batch=0ms entries=0ms commit=0ms]
I190409 10:23:58.484983 23 storage/replica_raft.go:396  [n1,s1,r8/1:/Table/1{2-3}] proposing ADD_REPLICA((n3,s3):3): updated=[(n1,s1):1 (n2,s2):2 (n3,s3):3] next=4

What's happening here is that we add first a replica on n2, then later one on n3. But in the sequence of events for n2, we never see the delayed preemptive snapshot actually apply (which it would if the leader contacted the follower after the conf change). It takes another replica change to give the raft group work to do so that it'll actually contact the follower proactively.

The test relies on `TestCluster`'s  `WaitForFullReplication` which in turn uses the underreplicated ranges gauge to decide whether everything is good. When the delayed snapshot is, well, delayed more than it should be, all the replicas that are there agree that the replicas are fully replicated (the replica that is missing would be the only one who could tell another tale, and it's not there yet). So the test fails now. Previously, we put preemptive snapshots into place which presumably would always be there to fail the check until everything was fully replicated.

Adding the line

```go
r.maybeSendAppend(id, true /* sendIfEmpty */)
```

in this code fixes it:

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/raft.go#L1433

Before I go upstream, I'd like to hear from @bdarnell if I missed anything.

2019-04-10 17:19 UTC, bdarnell requested changes
> (and this allocation has to be done in the replica change
transaction, which hasn't started yet)

I think it would be possible to pre-allocate replica IDs. One CPut to the range descriptor to bump the next replica ID before the main transaction restarts, and then we could use that ID for the preemptive snapshots. I'm not 100% sure that's safe if there are multiple concurrent proposed schema changes, but that would be one way to get rid of replica ID zero without moving away from preemptive snapshots entirely. 

> Before I go upstream, I'd like to hear from @bdarnell if I missed anything.

Yeah, adding a maybeSendAppend there looks like a good idea.


This change seems like a step in the wrong direction - it moves us away from streaming snapshot application and increases memory pressure. What exactly is the problem being solved here? I understand the problems with preemptive snapshots, and we're planning to fix them by moving to learner replicas. What good does this intermediate state do for us and how long will it be in effect?

> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-:-Lc7Ag9m4Oh_z1-Q5yEh:bimqmph)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/storage/replica_raft.go, line 2134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-Lc7ECAc3_9zf83Qz4XI:-Lc7ECAc3_9zf83Qz4XJ:b-xn5fpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8fc30a4213f5a1cf79fd6f1b64fe2412498e840/pkg/storage/replica_raft.go#L2134)):*
> ```Go
> 	// up a replica of `[a,b)'` by that time, the snapshot will be discarded by
> 	// Raft. If it has a replica of `[a,b)` (i.e. before the merge), the snapshot
> 	// again must be refused, for
> ```

Complete this sentence.
___
*[pkg/storage/store_snapshot.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-Lc7FEPZ4SQwsW0xvv-u:-Lc7FEPZ4SQwsW0xvv-v:bxl6j76) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8fc30a4213f5a1cf79fd6f1b64fe2412498e840/pkg/storage/store_snapshot.go#L97)):*
> ```Go
> 	}
> 
> 	maxSize := 128 * (1 << 20) // 128MB
> ```

Shoudn't this be a function of the zone config's range max size? 
___
*[pkg/storage/txnwait/txnqueue.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-Lc7DVMW8yF99tQdlzWu:-Lc7DVMW8yF99tQdlzWv:b54wzpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8fc30a4213f5a1cf79fd6f1b64fe2412498e840/pkg/storage/txnwait/txnqueue.go#L646)):*
> ```Go
> 	q.mu.Lock()
> 	// If the txn wait queue is not enabled or if the request is not
> 	// contained within the replica, do nothing. The request can fallp
> ```

Undo this


<!-- Sent from Reviewable.io -->

2019-04-11 10:26 UTC, tbg reviewed
> One CPut to the range descriptor to bump the next replica ID before the main transaction restarts, and then we could use that ID for the preemptive snapshots.

This isn't as easy as it sounds, we need to emit a commit trigger so that the in-memory copy of the range descriptor gets updated (we wouldn't want to let them diverge). Assuming we did that, we'll still be in an awkward spot. The preemptive snapshot will be instantiated with that replicaID, and now what? It's not in the descriptor, so its outgoing messages will be dropped. Similarly nobody can talk to it, but it does get to have a raft group now. I think this road ultimately doesn't lead to any good place, especially since we have our answer - learners - already.

> This change seems like a step in the wrong direction - it moves us away from streaming snapshot application and increases memory pressure. What exactly is the problem being solved here?

The problem solved here (not fully solved, but getting there) is that we want to get rid of the `Replica` state in which the replicaID is zero. The "feature" allowing that are learners (which we'll hopefully introduce in the 19.2 cycle as well) which leaves compatibility to be dealt with. We can "sit out" preemptive snapshots for a whole additional cycle but cleaning up the replica states is, in my opinion, the best tech debt reduction we can work on because it comes up with anything else in the store/replica area that we're discussing (pulling out the replication package, etc). That leads to wanting to receive preemptive snapshots without dealing with them throughout the codebase "very soon", so that we can get as close to removing replicaID zero as we can in this cycle (I'm hoping all the way). Applying delayed preemptive snapshots is a big step towards that.

This means that we wouldn't expect to actually use delayed preemptive snapshots outside of mixed version clusters (and baking it on master until we have learner replicas, which gives us confidence that they actually work). We're intentionally not focusing on scalability right now, so in this cycle we won't see larger snapshots than we have previously. In the next cycle, all things working out as expected, we can complete the transition into SST snapshots but either way the preemptive snapshot path will be dead because thanks to learners all snapshots will (look like) Raft snapshots and will apply with a replicaID immediately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-:-LcArqlF70BE3SnMbHSG:b-y8mftd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, @nvanbenschoten, and @tbg)

___
*[pkg/storage/store_snapshot.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35786#-Lc7FEPZ4SQwsW0xvv-u:-LcAuTNL1NdZxEjSx3TL:b9lxsdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8fc30a4213f5a1cf79fd6f1b64fe2412498e840/pkg/storage/store_snapshot.go#L97)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Shoudn't this be a function of the zone config's range max size? 
</blockquote></details>

Yes and no. We only allow one incoming snapshot at any given point in time (granted, that could change in the cycle, though I don't anticipate it), so morally speaking the storage will only ever contain a single snapshot (with the exception of abandoned preemptive snaps, which stick around for ~20s). The exception are empty snapshots (or very small ones) for which we have special rules, and for which this storage even budgets based on size.

A single snapshot arriving will always be accepted into the storage, regardless of its size, evicting prior additions if necessary.

So even if you ran with 512mb ranges, things should just work unless many snapshots are sent in parallel. But we could make the max size a function of the maximum range size seen in the zone configs and add some padding to avoid early eviction of a single large snapshots by a subsequent very small snapshot.


<!-- Sent from Reviewable.io -->

2020-01-13 12:16 UTC, closed without merging