distsqlrun: fix data race on evalCtx.iVarContainerStack
cockroachdb/cockroach pull request #36140
Opened 2019-03-25 23:56 UTC by yuzefovich

Previously, it was possible to run into a data race on the slice
evalCtx.iVarContainerStack because we were simply using a copy by
dereference to create a new eval context. However, this is not
sufficient since the slices still point to the same underlying
memory, so now we make a deeper copy of the slice.

Fixes: #35500. 

Release note: None

2019-03-25 23:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36140)
<!-- Reviewable:end -->

2019-03-25 23:58 UTC, yuzefovich commented
I agree with Alfonso's conclusion here https://github.com/cockroachdb/cockroach/issues/35500#issuecomment-472070040, so I implemented the last option he mentioned. Running the test locally before the fix I hit the data race like in 2 minutes and with the fix I didn't hit the data race in 20 minutes, so I'm assuming that the solution works.

2019-03-27 19:28 UTC, asubiotto requested changes
Thanks for getting this done.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-Lb-Wq2W84fwA_j5SKQi:b-4v1l1t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsqlrun/flow.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb-aFXIBq8LYifZ51oU:-Lb-aFXIBq8LYifZ51oV:b-bosz3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/814a23e3afddc45de86e3dd7e6372ac14779531d/pkg/sql/distsqlrun/flow.go#L127)):*
> ```Go
> // var context.
> func (ctx *FlowCtx) NewEvalCtx() *tree.EvalContext {
> 	evalCtx := *ctx.EvalCtx
> ```

I think it might make sense to make `Copy` a method on the `EvalCtx` and either have `FlowCtx.NewEvalCtx` use that or use it directly. I'm wondering if we can add a small test that ensures that the copy doesn't result in races if used concurrently?


<!-- Sent from Reviewable.io -->

2019-03-27 21:21 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/flow.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb-aFXIBq8LYifZ51oU:-Lb00BD_3uDSbA90CTgF:braasjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/814a23e3afddc45de86e3dd7e6372ac14779531d/pkg/sql/distsqlrun/flow.go#L127)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it might make sense to make `Copy` a method on the `EvalCtx` and either have `FlowCtx.NewEvalCtx` use that or use it directly. I'm wondering if we can add a small test that ensures that the copy doesn't result in races if used concurrently?
</blockquote></details>

I agree about `Copy`, done.

However, I haven't succeeded in making a small test that would trigger a data race without this fix. I've tried this:
```
func TestNewEvalContext(t *testing.T) {
	defer leaktest.AfterTest(t)()
	st := cluster.MakeTestingClusterSettings()
	evalCtx := tree.MakeTestingEvalContext(st)
	defer evalCtx.Stop(context.Background())
	flowCtx := distsqlrun.FlowCtx{
		Settings: st,
		EvalCtx:  &evalCtx,
	}

	const numRuns = 100000000
	const numGoRoutines = 10

	evalCtxs := make([]*tree.EvalContext, numGoRoutines)
	for i := range evalCtxs {
		evalCtxs[i] = flowCtx.NewEvalCtx()
		defer evalCtxs[i].Stop(context.Background())
	}

	var wg sync.WaitGroup
	wg.Add(numGoRoutines)
	for i := 0; i < numGoRoutines; i++ {
		go func(evalCtx *tree.EvalContext) {
			ivc := sqlbase.CheckHelper{}
			for r := 0; r < numRuns; r++ {
				evalCtx.PushIVarContainer(&ivc)
				evalCtx.PopIVarContainer()
			}
			wg.Done()
		}(evalCtxs[i])
	}
	wg.Wait()
}
```
Do you happen to see why it is not triggering the race?


<!-- Sent from Reviewable.io -->

2019-03-28 16:15 UTC, yuzefovich reviewed
Finally, the test triggers a data race on the first run without this fix. Apparently, non-nil and non-full slice was required as you guys suggested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-Lb43noo5ZNCIZTdThMw:b22oo2b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-Lb44GBP-FKdaNPAEeXc:b-808etc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
> ```Go
> 		SessionData:        &sessiondata.SessionData{},
> 		Settings:           st,
> 		iVarContainerStack: make([]IndexedVarContainer, 0, 8),
> ```

Not sure whether I should add a note here for the reason why we're making a slice.


<!-- Sent from Reviewable.io -->

2019-03-28 16:19 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-Lb4507CBUic7iwKEihx:b-vuewzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Not sure whether I should add a note here for the reason why we're making a slice.
</blockquote></details>

Another idea is to not create a slice here, but in the test push 3 items into the slice - the slice capacity is expected to be at least 4 - and then create "child" eval contexts. This seems hacky though.


<!-- Sent from Reviewable.io -->

2019-04-01 13:40 UTC, asubiotto approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/flow_test.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbO6_VV6uwzItFQLvCn:-LbO6_VV6uwzItFQLvCo:bk95x8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/distsqlrun/flow_test.go#L110)):*
> ```Go
> 		go func(evalCtx *tree.EvalContext) {
> 			for r := 0; r < numRuns; r++ {
> 				evalCtx.PushIVarContainer(&ivc)
> ```

I wonder if there's a way to test that all fields in the `EvalCtx` after copying are protected from data races.
___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-LbO6qxiDW2DyaP4SArH:bjolzrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Another idea is to not create a slice here, but in the test push 3 items into the slice - the slice capacity is expected to be at least 4 - and then create "child" eval contexts. This seems hacky though.
</blockquote></details>

Could you also `make` it in your test after calling `MakeTestingEvalContextWithMon`? Seems fishy for your test to rely on some behavior of a utility function.


<!-- Sent from Reviewable.io -->

2019-04-01 15:28 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/flow_test.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbO6_VV6uwzItFQLvCn:-LbORymo3LqNiHel62Ct:b-qb90ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/distsqlrun/flow_test.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if there's a way to test that all fields in the `EvalCtx` after copying are protected from data races.
</blockquote></details>

I was also thinking about this, but I don't know how to check this. I'm open to any ideas, but it seems to me that we'd have to manually and explicitly test each accessible field.

For example, there is `CollationEnv` field within `EvalContext` which contains `cache  map[string]collationEnvironmentCacheEntry`, and I think this could be another susceptible to a data race object.
___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-LbOT1OR3V1bL2B43Fnw:bifvwnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you also `make` it in your test after calling `MakeTestingEvalContextWithMon`? Seems fishy for your test to rely on some behavior of a utility function.
</blockquote></details>

`iVarContainerStack` is private, so we don't have access to it from `distsqlrun` package.

I made a slight modification to expose the instantiation. I think this is the cleanest way.


<!-- Sent from Reviewable.io -->

2019-04-01 15:59 UTC, asubiotto reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/flow_test.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbO6_VV6uwzItFQLvCn:-LbObxpA9IVgY5pnJyjh:b42t98q) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/distsqlrun/flow_test.go#L110)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I was also thinking about this, but I don't know how to check this. I'm open to any ideas, but it seems to me that we'd have to manually and explicitly test each accessible field.

For example, there is `CollationEnv` field within `EvalContext` which contains `cache  map[string]collationEnvironmentCacheEntry`, and I think this could be another susceptible to a data race object.
</blockquote></details>

definitely cc @jordanlewis in case he has a better idea as to how to test the safety of eval ctx copies.
___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-LbObY4F6Hql4KJKLbzX:basc0dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`iVarContainerStack` is private, so we don't have access to it from `distsqlrun` package.

I made a slight modification to expose the instantiation. I think this is the cleanest way.
</blockquote></details>

Got it. I don't think that `InitIVarContainerStack` is a good idea if it's just used for testing purposes. Maybe add the test to a new file `eval_test.go` in this package so you can set the private variable? I would just test `evalCtx.Copy` instead of `NewEvalCtx`


<!-- Sent from Reviewable.io -->

2019-04-01 16:53 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/sem/tree/eval.go, line 2610 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-Lb44GBP-FKdaNPAEeXb:-LbOoVovDhHuhCCGO_uF:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/80d25498ef2a1cf71c32095a90da8ce551ebaec9/pkg/sql/sem/tree/eval.go#L2610)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Got it. I don't think that `InitIVarContainerStack` is a good idea if it's just used for testing purposes. Maybe add the test to a new file `eval_test.go` in this package so you can set the private variable? I would just test `evalCtx.Copy` instead of `NewEvalCtx`
</blockquote></details>

Good point, done.


<!-- Sent from Reviewable.io -->

2019-04-01 18:10 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/sem/tree/eval.go, line 2623 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP3jz_5k_yuk8ZhLG1:-LbP3jz_5k_yuk8ZhLG2:b-pi0a98) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval.go#L2623)):*
> ```Go
> func (ctx *EvalContext) Copy() *EvalContext {
> 	ctxCopy := *ctx
> 	// Copying EvalCtx by value is not sufficient for correct copying of
> ```

comment is unnecessary - you've said that we're making a deep-copy
___
*[pkg/sql/sem/tree/eval.go, line 2626 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP3Rmt0mNqKqC-Jzhe:-LbP3Rmt0mNqKqC-Jzhf:b-1i0cr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval.go#L2626)):*
> ```Go
> 	// iVarContainerStack slice, so we're making a deep copy of that slice
> 	// manually. This is necessary to prevent data races in some cases (see issue
> 	// #35500).
> ```

nit: link to issue is unnecessary click-bait
___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbP43le5GyFfFMBMz7A:b-9zwz0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
> ```Go
> // TestEvalContextCopy verifies that EvalContext.Copy() produces copies of
> // EvalContext that are not susceptible to data races.
> func TestEvalContextCopy(t *testing.T) {
> ```

this test seems bizarre to me. A simple test would be just to assert that the copy gets a new iVarContainerStacks slice.
You've tried to make the test more "general" by asserting behavior of mutations, but have you succeeded? You're still just testing a single member.


<!-- Sent from Reviewable.io -->

2019-04-01 22:04 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/sem/tree/eval.go, line 2623 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP3jz_5k_yuk8ZhLG1:-LbP7_JPCum0WQMK11CL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval.go#L2623)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment is unnecessary - you've said that we're making a deep-copy
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval.go, line 2626 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP3Rmt0mNqKqC-Jzhe:-LbP7an3AtOE0ZeTprDD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval.go#L2626)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: link to issue is unnecessary click-bait
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbPuZiJ93wSybWnH8IB:b-yuqn0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this test seems bizarre to me. A simple test would be just to assert that the copy gets a new iVarContainerStacks slice.
You've tried to make the test more "general" by asserting behavior of mutations, but have you succeeded? You're still just testing a single member.
</blockquote></details>

My goal was to have a small repro of the issue that caught the bug. I agree that it is a somewhat weird test that checks one thing in particular.

I tried rewriting the test as you suggested just to assert that different `iVarContainerStack`s are created with something like:
```fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack)```
but for some reason even without the deep copy, the pointers are different. What am I missing?


<!-- Sent from Reviewable.io -->

2019-04-01 22:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbPve0S3IsWjur6wE7b:b-5ser7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

My goal was to have a small repro of the issue that caught the bug. I agree that it is a somewhat weird test that checks one thing in particular.

I tried rewriting the test as you suggested just to assert that different `iVarContainerStack`s are created with something like:
```fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack)```
but for some reason even without the deep copy, the pointers are different. What am I missing?
</blockquote></details>

Sorry, I meant to say:
```
fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", evalCtxs[1].iVarContainerStack)
```
And the pointers are the same in both cases.

I also tried
```
fmt.Sprintf("%p", &evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", &evalCtxs[1].iVarContainerStack)
```
in which cases, the pointers are different in both cases.

(By both cases I mean with and without the deep copy.)


<!-- Sent from Reviewable.io -->

2019-04-01 22:55 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbPyHKqBNffC3mgvVp1:b-pbxp8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
> fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", evalCtxs[1].iVarContainerStack)

You had me staring for a while.
My first reaction was to complain that you're printing a slice with the "%p" verb in your test and comparing the strings instead of directly comparing pointers. But then I said OK, it should still work. Except it doesn't for empty slices.
When a slice has capacity, the "%p" appears to print the address of the first element in the slice. If the slice does not have capacity, it prints what appears to be garbage.
The philosophical way to look at it: slices with no capacity are always equals; they cannot be used in your test to determine if you've made deep copies or not.
Your `Copy()` function returns slices with no capacity when the input slice is empty.
If you change the code to
```
	ctxCopy.iVarContainerStack = make([]IndexedVarContainer, len(ctx.iVarContainerStack), cap(ctx.iVarContainerStack))
```
it'll work.

Or better yet, have the tests actually put something in that slice.
And compare pointers directly (`%cpy.iVarCrap[0]`), no sprintf crap.


<!-- Sent from Reviewable.io -->

2019-04-01 22:57 UTC, andreimatei requested changes
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbQ6LOE9Ix5MBXMT_JE:bl0welj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
> fmt.Sprintf("%p", &evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", &evalCtxs[1].iVarContainerStack)

Btw, this one is clear, right? Shallow copies make copies of the slice header, like they make copies of all the fields in `evalCtx`.
You're essentially testing
```
type t struct {
  x int
}

var a t
b := a
&a.x != &b.x
```


<!-- Sent from Reviewable.io -->

2019-04-01 23:22 UTC, andreimatei reviewed
The more I look around this `evalCtx` copying business, the more scared I am. For example, one can't call `Stop()` on a copy. I feel like that `Stop()` method should disappear, and responsibility for closing the monitors used through the `evalCtx` should be maintained by whomever is supplying those monitors.
Even without copying, that `Stop()` method doesn't make sense to me. If someone hands a monitor with some memory already allocated to a `evalCtx`, then... should `Stop()` be called or not? cc @justinj who introduced the `Stop()` - what's the thinking?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-LbQ9Ysu9GY2HpsVvZog:b-g5nqrd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @jordanlewis, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-04-01 23:36 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/sem/tree/eval_internal_test.go, line 130 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbP43le5GyFfFMBMz79:-LbQCs3X0tdSiSYbWWCN:b-t82reo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c69bf559987f094b8d3135c5552e8e62d4add2b2/pkg/sql/sem/tree/eval_internal_test.go#L130)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> fmt.Sprintf("%p", &evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", &evalCtxs[1].iVarContainerStack)

Btw, this one is clear, right? Shallow copies make copies of the slice header, like they make copies of all the fields in `evalCtx`.
You're essentially testing
```
type t struct {
  x int
}

var a t
b := a
&a.x != &b.x
```

</blockquote></details>

Thanks for the detailed responses!

I tried to compare the pointers directly with `evalCtxs[0].iVarContainerStack == evalCtxs[1].iVarContainerStack`, but it doesn't work since comparison of `[]IndexedVarContainer` is not defined, so I switched to `Sprintf`s to get the addresses under the slices. What am I missing here?

In the test, I'm explicitly instantiating an `iVarContainerStack` myself, so my attempt to test the assertion as you suggested earlier was something like:
```
func TestEvalContextCopy(t *testing.T) {
	defer leaktest.AfterTest(t)()
	st := cluster.MakeTestingClusterSettings()
	evalCtx := MakeTestingEvalContext(st)
	defer evalCtx.Stop(context.Background())

	// Note: the test relies on "parent" EvalContext having non-nil and non-full
	// iVarContainerStack.
	evalCtx.iVarContainerStack = make([]IndexedVarContainer, 0, 8)

	var ivc IndexedVarContainer
	evalCtx.PushIVarContainer(ivc)

	evalCtxs := make([]*EvalContext, 2)
	for i := range evalCtxs {
		evalCtxs[i] = evalCtx.Copy()
		defer evalCtxs[i].Stop(context.Background())
	}

	if fmt.Sprintf("%p", evalCtxs[0].iVarContainerStack) == fmt.Sprintf("%p", evalCtxs[1].iVarContainerStack) {
		t.Fatal("iVarContainerStack are the same")
	}
}
```
but that doesn't trigger the panic without the fix (I tried both with and without putting `ivc` onto the stack).


<!-- Sent from Reviewable.io -->

2019-04-01 23:42 UTC, andreimatei commented
> I tried to compare the pointers directly with evalCtxs[0].iVarContainerStack == evalCtxs[1].iVarContainerStack, but it doesn't work since comparison of []IndexedVarContainer is not defined, so I switched to Sprintfs to get the addresses under the slices. What am I missing here?

What you want is non-empty slices and `&evalCtxs[0].iVarContainerStack[0] != &evalCtxs[1].iVarContainerStack[0]`.

```
func Test() {
	ctx := EvalContext{iVarStack: make([]..., 1)}
	cpy := ctx.Copy()
	if &ctx.iVarStack[0] == &cpy.iVarStack[0] {
		t.Fatal("shallow bro")
	}
}
```

2019-04-01 23:51 UTC, yuzefovich commented
Thanks @andreimatei, it worked!

2019-04-02 23:38 UTC, yuzefovich reviewed
I found a few places where `extendedEvalContext` (which contains `EvalContext`) was being copied by value, so I added a deep `copy` method. I think it is safer this way, but please let me know if you disagree. (I will squash the commits if there are no objections to this change.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-LbVPBwYDcD6wVcCQwNx:b-cudkwo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-04-03 18:36 UTC, andreimatei submitted a review, later dismissed
This is getting out of hand in my opinion. We need an analysis about when this evalCtx is modified. Without reading something on that, I can't know when a copy is needed and when it isn't. The fact that it's "safer"  comes with significant pollution and confusion, so I hope it can be avoided. (and again, perhaps it'd be a good idea to make this ctx immutable, and isolate the mutable parts somewhere else with a clearer lifetime).
Anyway, I don't need to review this, but I'm definitely concerned. Let's get someone to write a good contract. Maybe @jordanlewis .

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-LbZTHp46x4dKDqrLrI9:b-3p1t55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/apply_join.go, line 310 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbZSUW8CW8hzKoiDDEr:-LbZSUW8CW8hzKoiDDEs:b-118e6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8902fdf3d7afc5cb24579823ed04085cfb3806/pkg/sql/apply_join.go#L310)):*
> ```Go
> 		params.ctx,
> 		params.p,
> 		func() *extendedEvalContext {
> ```

you don't need the anonymous function, do you?
simply passing `params.extendedEvalCtx.copy` should do.
___
*[pkg/sql/sem/tree/eval_internal_test.go, line 131 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbZT0VU2vSeGWGo8W3o:-LbZT0VU2vSeGWGo8W3p:byzprjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8902fdf3d7afc5cb24579823ed04085cfb3806/pkg/sql/sem/tree/eval_internal_test.go#L131)):*
> ```Go
> func TestEvalContextCopy(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	st := cluster.MakeTestingClusterSettings()
> ```

do you really need to use the `MakeTestingEvalCtx` ctor and this `st` and the `Stop` call?
Can't you just do `ctx := evalCtx{iVar = make...}`?


<!-- Sent from Reviewable.io -->

2019-04-03 20:12 UTC, yuzefovich reviewed
@andreimatei Thanks for the comments!

I agree that this eval context business is getting worse and making the context immutable is probably the right way to do it; however, that would be a significantly larger undertaking, and right before the release might not be the best time for it. I think that we should proceed with this change and backport it on the release branch since it does fix a bug. @jordanlewis thoughts?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-LbZoCCuC14u2iWMkOeh:bs5ynll)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)

___
*[pkg/sql/apply_join.go, line 310 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbZSUW8CW8hzKoiDDEr:-LbZo8g6-eYAuHfSkRTI:b-9vhyeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8902fdf3d7afc5cb24579823ed04085cfb3806/pkg/sql/apply_join.go#L310)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you don't need the anonymous function, do you?
simply passing `params.extendedEvalCtx.copy` should do.

</blockquote></details>

Indeed, fixed.
___
*[pkg/sql/sem/tree/eval_internal_test.go, line 131 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-LbZT0VU2vSeGWGo8W3o:-LbZnzwv0tFBUlaCOVMI:ba8mxvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f8902fdf3d7afc5cb24579823ed04085cfb3806/pkg/sql/sem/tree/eval_internal_test.go#L131)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do you really need to use the `MakeTestingEvalCtx` ctor and this `st` and the `Stop` call?
Can't you just do `ctx := evalCtx{iVar = make...}`?
</blockquote></details>

You're right, thanks, it is unnecessary. This was an artifact of how I set up the test before.


<!-- Sent from Reviewable.io -->

2019-04-08 13:32 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> agreed with your assessment - let's merge this and backport it. A better fix can come later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36140#-:-Lbx8YQOCHQMmz7W75S-:bg0ym9u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @asubiotto, and @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-04-08 14:33 UTC, yuzefovich commented
Thanks for the reviews everyone!

bors r+

2019-04-08 15:11 UTC, merged