roachtest: streamline debug collection
cockroachdb/cockroach pull request #36562
Opened 2019-04-05 08:18 UTC by tbg

Inspired by [1].

The case in which a test hit an error and the case in which a test
times out were handled differently and I had little confidence that
it was working as intended.

This simplifies by not running the test in the main goroutine, but
reserving the main goroutine for defering the debug and cleanup
actions while the test itself is now running in a child goroutine.

I tested this running `tpcc/nodes=3/w=headroom` locally (where it
runs with one warehouse and only for a minute) in the passing case
and in the case in which it fails with an artificially low timeout.

[1]: https://github.com/cockroachdb/cockroach/issues/36094#issuecomment-480189693

Release note: None

2019-04-05 08:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36562)
<!-- Reviewable:end -->

2019-04-05 08:20 UTC, tbg commented on pkg/cmd/roachtest/test.go
> +				c.Destroy(ctx)
PS I'm unclear why there's this random `c.Destroy` call that only fires on a timeout. Perhaps someone can educate me. I thought destroying would be left to a higher power. Perhaps we can just stop in all cases and don't need to track the bool?

2019-04-05 13:26 UTC, petermattis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/cmd/roachtest/test.go, line 1190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36562#-Lbg_4xAylN8X4GYmNqg-r1-1190:-LbheE3cDthQti4buyMK:b-r7pjrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d0b4b6db12257d6b3ff7cede0b5e5201ae9763/pkg/cmd/roachtest/test.go#L1190)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

PS I'm unclear why there's this random `c.Destroy` call that only fires on a timeout. Perhaps someone can educate me. I thought destroying would be left to a higher power. Perhaps we can just stop in all cases and don't need to track the bool?
</blockquote></details>

As I've mentioned to @andreimatei before, this code has evolved into the current mess and deserves to be rewritten, but there is a high probability of fallout from any changes. 
___
*[pkg/cmd/roachtest/test.go, line 1230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36562#-LbhecldDDZgG5BvOPgP:-LbhecldDDZgG5BvOPgQ:b-rprwsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0d0b4b6db12257d6b3ff7cede0b5e5201ae9763/pkg/cmd/roachtest/test.go#L1230)):*
> ```Go
> 		t.mu.Unlock()
> 
> 		// Run the test itself in a goroutine. The main goroutine is in charge
> ```

Does this muck with the `test.runner` stacktrace magic? See `test.decorate`. Also, `test.runnerID` is supposed to be the ID of the goroutine running the test. See `test.Status`, and `test.Progress`. I suspect switching to running the test in a goroutine is going to have a bunch of fallout. 


<!-- Sent from Reviewable.io -->

2019-04-19 17:14 UTC, andreimatei reviewed
Let's not change the existing code any more. I'm trying to get my rewrite merged asap.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36562#-:-Lcq_bc_5aHrw5P5mzNT:b-kfgrtf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)



<!-- Sent from Reviewable.io -->

2020-01-13 12:17 UTC, closed without merging