roachprod: accept multipl GCE projects for different commands
cockroachdb/cockroach pull request #36581
Opened 2019-04-05 20:11 UTC by andreimatei

List, sync, destroy, gc and extend now support working across multiple
gce projects. This was motivated by wanting the gc cron job to gc
multiple projects.
create only works with one GCE project.

The implementation works by having different commands register the
--gce-project flag as either a string or a StringSlice. The flags
populate either a opts.project or an opts.projects field, and then we
have accessors that determine what field to look at.

Release note: None

2019-04-05 20:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36581)
<!-- Reviewable:end -->

2019-04-05 20:11 UTC, andreimatei commented
First commit is #36580

2019-04-05 20:47 UTC, ajwerner requested changes
> Reviewed 7 of 7 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @bobvawter)

___
*[pkg/cmd/roachprod/main.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbjEAQ4-W7WTEqFBCpK:-LbjEAQ4-W7WTEqFBCpL:b4f7xl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/287224926fb3ba2648c19b2b15edcf34d88d63aa/pkg/cmd/roachprod/main.go#L761)):*
> ```Go
> 	}
> 	if !vm.Providers[aws.ProviderName].Active() {
> 		refreshDNS = true
> ```

should this be `false`?


<!-- Sent from Reviewable.io -->

2019-04-05 20:59 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> when you fix the other PR. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-:-LbjI7WaD8XzRGhNLb44:b-n9ysp6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @bobvawter)



<!-- Sent from Reviewable.io -->

2019-04-05 20:59 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @bobvawter)

___
*[pkg/cmd/roachprod/main.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbjEAQ4-W7WTEqFBCpK:-LbjHZHCDgTwzpMXMRcH:b3uz6sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/287224926fb3ba2648c19b2b15edcf34d88d63aa/pkg/cmd/roachprod/main.go#L761)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should this be `false`?
</blockquote></details>

yes. But what should `(!vm.Providers[aws.ProviderName].Active() => !refreshDNS) && vm.Providers[aws.ProviderName].Active()` be?


<!-- Sent from Reviewable.io -->

2019-04-05 21:10 UTC, ajwerner commented
> But what should `(!vm.Providers[aws.ProviderName].Active() => !refreshDNS) && vm.Providers[aws.ProviderName].Active()` be?

True, my friend, true

2019-04-08 12:20 UTC, bobvawter requested changes
> Reviewed 2 of 7 files at r1, 5 of 5 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/cmd/roachprod/main.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbjEAQ4-W7WTEqFBCpK:-LbwspEPDX5V8_NDVoqX:bak4ddo) ([raw file](https://github.com/cockroachdb/cockroach/blob/287224926fb3ba2648c19b2b15edcf34d88d63aa/pkg/cmd/roachprod/main.go#L761)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yes. But what should `(!vm.Providers[aws.ProviderName].Active() => !refreshDNS) && vm.Providers[aws.ProviderName].Active()` be?
</blockquote></details>

Should this be generalized to loop over all registered providers and do a type-switch for GCE, then keep `if !p.Active() { refresh = false}` in case another provider is added in the future?
___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbwrsCn9OuZ-7ZJZqI0:-LbwrsCn9OuZ-7ZJZqI1:bvw9f1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36fe6d0b256e86b0aeb611bf96a2e9272b317dc/pkg/cmd/roachprod/vm/gce/gcloud.go#L177)):*
> ```Go
> 	// For other commands, the flag populates the project field.
> 	// Accessed through GetProject() or GetProjects().
> 	project        string
> ```

Why keep this solo `project` field at all?  If there's a `GetProject()` accessor, it can just return `projects[0]` or panic.


<!-- Sent from Reviewable.io -->

2019-04-08 14:44 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @bobvawter)

___
*[pkg/cmd/roachprod/main.go, line 761 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbjEAQ4-W7WTEqFBCpK:-LbxNaDR09jsQFHD4gFP:b-wm1vm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/287224926fb3ba2648c19b2b15edcf34d88d63aa/pkg/cmd/roachprod/main.go#L761)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Should this be generalized to loop over all registered providers and do a type-switch for GCE, then keep `if !p.Active() { refresh = false}` in case another provider is added in the future?
</blockquote></details>

meh. The `local` provider doesn't affect the DNS stuff, for example.
The abstractions around here are pretty bankrupt. I'd just leave it.
___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbwrsCn9OuZ-7ZJZqI0:-LbxO79R9rHokYmOexPH:by0szr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36fe6d0b256e86b0aeb611bf96a2e9272b317dc/pkg/cmd/roachprod/vm/gce/gcloud.go#L177)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why keep this solo `project` field at all?  If there's a `GetProject()` accessor, it can just return `projects[0]` or panic.
</blockquote></details>

Because of the way the cobra flags work. For the ones that accept string, as opposed to []string (so, the flags for the commands that only accepts a single project), they write into this project field.
I tried doing something better but gave up because of how we register the same flag for multiple commands, and each of these flags has a default value which the library writes into the variable you give it, etc. If you have an exact proposal (or better yet want to amend this patch), I'm all for it.


<!-- Sent from Reviewable.io -->

2019-04-08 15:19 UTC, bobvawter requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbwrsCn9OuZ-7ZJZqI0:-LbxTkKuE2NRMZazcHHl:b-rvmrkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36fe6d0b256e86b0aeb611bf96a2e9272b317dc/pkg/cmd/roachprod/vm/gce/gcloud.go#L177)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Because of the way the cobra flags work. For the ones that accept string, as opposed to []string (so, the flags for the commands that only accepts a single project), they write into this project field.
I tried doing something better but gave up because of how we register the same flag for multiple commands, and each of these flags has a default value which the library writes into the variable you give it, etc. If you have an exact proposal (or better yet want to amend this patch), I'm all for it.
</blockquote></details>

When `ConfigureXFlags()` is called in single-project mode, it can initialize `projects` to be a single-element slice and then configure a string flags using the address of the 0-th element.

```
o.projects = make([]string, 1)
flags.StringVar(&o.projects[0], .....)
```


<!-- Sent from Reviewable.io -->

2019-04-08 18:15 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @bobvawter)

___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-LbwrsCn9OuZ-7ZJZqI0:-Lby8fOI7kjsqgzilThO:bu8hd5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e36fe6d0b256e86b0aeb611bf96a2e9272b317dc/pkg/cmd/roachprod/vm/gce/gcloud.go#L177)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

When `ConfigureXFlags()` is called in single-project mode, it can initialize `projects` to be a single-element slice and then configure a string flags using the address of the 0-th element.

```
o.projects = make([]string, 1)
flags.StringVar(&o.projects[0], .....)
```
</blockquote></details>

that's not entirely satisfactory because the `o.projects` keeps being overwritten by the (multiple copies of) the flag that accepts the comma-separated list, and so now you have to reason about how the different defaults between the slice flags and the string flag interact.

Instead, I've done away with StringVar and StringSliceVar and implemented my own flag var. PTAL.


<!-- Sent from Reviewable.io -->

2019-04-09 11:54 UTC, bobvawter approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-:-Lc0wfqp68G-SkEbMS46:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @andreimatei)

___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 184 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-Lc0wGVE-Ljy22h9Tz8W:-Lc0wGVFAVvwoe_zYEka:bj6rc67) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fc32ee1c6ad8ae20aea5c0fcf9cb2301ca303a/pkg/cmd/roachprod/vm/gce/gcloud.go#L184)):*
> ```Go
> }
> 
> // projectsVal is the implementation for the --gce-proects flag. It populates
> ```

proJects


<!-- Sent from Reviewable.io -->

2019-04-19 21:46 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @bobvawter)

___
*[pkg/cmd/roachprod/vm/gce/gcloud.go, line 184 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-Lc0wGVE-Ljy22h9Tz8W:-LcrZEwA6PT7ZzEP2tVJ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8fc32ee1c6ad8ae20aea5c0fcf9cb2301ca303a/pkg/cmd/roachprod/vm/gce/gcloud.go#L184)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

proJects
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-04-19 21:55 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36581#-:-Lcra9mH5bj_uiBO7ean:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @bobvawter)



<!-- Sent from Reviewable.io -->

2019-04-19 22:33 UTC, merged