exec: add vectorized merge joiner logic and comparison tests
cockroachdb/cockroach pull request #36627
Opened 2019-04-08 18:46 UTC by georgeutsin

Added tests that compare the row by row merge joiner to the
vectorized one on randomized input data. This mainly tests the
column orderings to make sure that different permutations of
columns are handled properly.

Also added some basic logic tests that can be extended in the
future.

Release note: None

2019-04-08 18:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36627)
<!-- Reviewable:end -->

2019-04-08 20:38 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lbyecs5785PkXW_pKrH:-Lbyecs5785PkXW_pKrI:b-6kasci) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L133)):*
> ```Go
> 		// if there are columns not in the ordering, the results are not fully
> 		// deterministic.
> 		lOrderingCols := generateColumnOrdering(rng, nCols, nCols, false)
> ```

Why don't you want to randomize direction as well? `Compare` below should work in either case.


<!-- Sent from Reviewable.io -->

2019-04-08 20:40 UTC, georgeutsin reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lbyecs5785PkXW_pKrH:-LbyfbfaD_RaW4wrbdZy:btw6qqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L133)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why don't you want to randomize direction as well? `Compare` below should work in either case.
</blockquote></details>

Because of: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/mergejoiner.go#L67


<!-- Sent from Reviewable.io -->

2019-04-08 20:53 UTC, yuzefovich approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-:-LbyiZSS1NFqR3NcwMIC:be8rotp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lbyecs5785PkXW_pKrH:-LbyhkILArf2RcT9zlse:b-b1s4xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L133)):*
<details><summary><i>Previously, georgeutsin (George Utsin) wrote…</i></summary><blockquote>

Because of: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/mergejoiner.go#L67
</blockquote></details>

Ok, makes sense. Disregard my comment.


<!-- Sent from Reviewable.io -->

2019-04-10 13:00 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36627)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @georgeutsin and @jordanlewis)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6H2iaEAN-02crhvFB:-Lc6H2iaEAN-02crhvFC:b-xssg9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L51)):*
> ```Go
> 		// if there are columns not in the ordering, the results are not fully
> 		// deterministic.
> 		orderingCols := generateColumnOrdering(rng, nCols, nCols, true)
> ```

Add inline comments to the bool args
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6IRF0EymiCHBDOrt5:-Lc6IRF0EymiCHBDOrt6:b-gwtxjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L116)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	var da sqlbase.DatumAlloc
> 	st := cluster.MakeTestingClusterSettings()
> ```

Do you use `st` below?
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6I5hiA2TubtHX6Hb8:-Lc6I5hiA2TubtHX6Hb9:bs9b6ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L119)):*
> ```Go
> 	evalCtx := tree.MakeTestingEvalContext(st)
> 	defer evalCtx.Stop(context.Background())
> 	rng := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
> ```

Use `rng, _ := randutil.NewPseudoRand()`. It's a nice utility that prints out the seed on failure so that you can reproduce random failures.
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6HDLo7RhBeVsF4mne:-Lc6HDLo7RhBeVsF4mnf:b-xh6wdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L133)):*
> ```Go
> 		// if there are columns not in the ordering, the results are not fully
> 		// deterministic.
> 		lOrderingCols := generateColumnOrdering(rng, nCols, nCols, false)
> ```

Not sure why the comments were lost, but it seems the reason you're not randomizing the direction is that you need the same direction in the right ordering columns. Could you generate the random column ordering for the left and right columns and then overwrite the right column ordering direction to pass that check? 
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6IgOT5dIbmRFYX3zX:-Lc6IgOT5dIbmRFYX3zY:b-a65c3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L163)):*
> ```Go
> 			Core:  distsqlpb.ProcessorCoreUnion{MergeJoiner: mjSpec},
> 		}
> 		if err := verifyColOperator(false, [][]sqlbase.ColumnType{inputTypes, inputTypes}, []sqlbase.EncDatumRows{lRows, rRows}, append(inputTypes, inputTypes...), pspec); err != nil {
> ```

Comment the `false` here as well.
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6Jtgu5kbcxt7pxHLW:-Lc6Jtgu5kbcxt7pxHLX:b-47o76n) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/logictest/testdata/logic_test/exec_merge_join#L6)):*
> ```
> 
> statement ok
> CREATE TABLE  t1 (k INT PRIMARY KEY, v INT)
> ```

Would probably be good to make one of these tables have a non-unique index (e.g. `CREATE TABLE t1 (k INT, v INT, INDEX k_idx (k))`) to increase test coverage a slight bit by including multiple rows for a group.

nit: seems like there's an extra space between `TABLE` and `t1`?


<!-- Sent from Reviewable.io -->

2019-04-10 16:34 UTC, georgeutsin reviewed
I will be addressing most the review comments regarding column orderings in the next PR as I refactor the merge joiner

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-:-Lc75I_55iVjtFFjuTCC:bv1v8gt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6H2iaEAN-02crhvFB:-Lc6Z7E_4U16cjPjTPoz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L51)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add inline comments to the bool args
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6IRF0EymiCHBDOrt5:-Lc6Z7oo9d7p7U97i5kN:b-fv5uaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L116)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do you use `st` below?
</blockquote></details>

In he evalCtx yes
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6I5hiA2TubtHX6Hb8:-Lc6ZJ6c5ghNpwmDLJBB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L119)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Use `rng, _ := randutil.NewPseudoRand()`. It's a nice utility that prints out the seed on failure so that you can reproduce random failures.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6HDLo7RhBeVsF4mne:-Lc6aNag0Rl3N-Ztxt9g:bbcpmaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L133)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure why the comments were lost, but it seems the reason you're not randomizing the direction is that you need the same direction in the right ordering columns. Could you generate the random column ordering for the left and right columns and then overwrite the right column ordering direction to pass that check? 
</blockquote></details>

Done.
Refactored the whole process.
___
*[pkg/sql/distsqlrun/columnar_operators_test.go, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6IgOT5dIbmRFYX3zX:-Lc6nw164re-YqyA3_qE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/distsqlrun/columnar_operators_test.go#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Comment the `false` here as well.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/exec_merge_join, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36627#-Lc6Jtgu5kbcxt7pxHLW:-Lc6olc95QGpdyMNNSeQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da0ecfc7d7b49909df08426574b305ce641371da/pkg/sql/logictest/testdata/logic_test/exec_merge_join#L6)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Would probably be good to make one of these tables have a non-unique index (e.g. `CREATE TABLE t1 (k INT, v INT, INDEX k_idx (k))`) to increase test coverage a slight bit by including multiple rows for a group.

nit: seems like there's an extra space between `TABLE` and `t1`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-10 16:35 UTC, georgeutsin commented
bors r+

2019-04-10 17:01 UTC, merged