exec: support NOT LIKE
cockroachdb/cockroach pull request #36781
Opened 2019-04-11 21:14 UTC by solongordon

In order to support NOT LIKE operators, I added an "invert" option to
our selection ops. This indicates that the comparison results should be
inverted from true to false and vice versa. This is supported by all
selection operators now but only used by the LIKE ones as of yet.

Refers #34498

Release note: None

2019-04-11 21:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36781)
<!-- Reviewable:end -->

2019-04-11 21:36 UTC, jordanlewis requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/like_ops.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDGi9C-9QJ-ZcvVi65:-LcDGi9C-9QJ-ZcvVi66:b-7y7yzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L40)):*
> ```Go
> 		if invert {
> 			// Matches nothing.
> 			return NewVoidOp(input), nil
> ```

Chatted with @justinj briefly about whether this kind of decision should be left to the optimizer, and he both said yes and also pointed out that the `noop` case isn't actually right because of nulls. 

So I guess the second branch should really be replaced by a not-null matcher, which seems like a pretty good operator to add in general.
___
*[pkg/sql/exec/operator.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDIopKEIRtqADjoNSr:-LcDIopKEIRtqADjoNSs:b-qw3c2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/operator.go#L78)):*
> ```Go
> var _ Operator = &voidOperator{}
> 
> // NewVoidOp creates a new operator which just returns an empty batch.
> ```

Can you call this `ZeroOp` to match the `zeroNode` in the HP?
___
*[pkg/sql/exec/operator.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDIktx36-scS2u0Ok3:-LcDIktx36-scS2u0Ok4:b-1gw9un) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/operator.go#L88)):*
> ```Go
> 
> func (s *voidOperator) Next() coldata.Batch {
> 	// TODO(solon): Can we avoid calling Next on the input at all?
> ```

I think so, yes.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDJCkX0uBITj4w0n-Q:-LcDJCkY7JyGZOsc0K_h:b-wyp5xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L66)):*
> ```Go
> 				var cmp bool
> 				{{(.Assign "cmp" "coldata[i]" "p.constArg")}}
> 				cmp = cmp != p.invert
> ```

How badly does this affect the other selection benchmarks? Just pointing out that this is unnecessary - we only need `invert` for the `LIKE` case, right, since everything else has reversed variants already.

I would prefer to see template-time inverted like cases for all of the ones that require it, so that the other operators don't have this unnecessary comparison. I think it should be possible to accomplish this by just modifying the gen loop for the like operators.


<!-- Sent from Reviewable.io -->

2019-04-11 22:00 UTC, yuzefovich reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/exec/like_ops.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDOY-t2taTTCjrm3Px:-LcDOY-t2taTTCjrm3Py:b-dybzk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L27)):*
> ```Go
> // pattern.
> func GetLikeOperator(
> 	ctx *tree.EvalContext, input Operator, colIdx int, pattern string, invert bool,
> ```

Maybe "negate" or "negative" is a better name? "Invert" to me implies switching "left Op right" to "right Op left" whereas we're switching it to "not(left Op right)".


<!-- Sent from Reviewable.io -->

2019-04-12 01:29 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/like_ops.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDOY-t2taTTCjrm3Px:-LcE9AL-7-L5CBUcroTl:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L27)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Maybe "negate" or "negative" is a better name? "Invert" to me implies switching "left Op right" to "right Op left" whereas we're switching it to "not(left Op right)".
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/exec/like_ops.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDGi9C-9QJ-ZcvVi65:-LcE9FeG6ono8VevGKxk:b5qzpyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L40)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Chatted with @justinj briefly about whether this kind of decision should be left to the optimizer, and he both said yes and also pointed out that the `noop` case isn't actually right because of nulls. 

So I guess the second branch should really be replaced by a not-null matcher, which seems like a pretty good operator to add in general.
</blockquote></details>

:man_facepalming: Good point about nulls.
___
*[pkg/sql/exec/operator.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDIktx36-scS2u0Ok3:-LcE8jLT7pU3UZI_uaFI:bl2usiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/operator.go#L88)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think so, yes.
</blockquote></details>

I couldn't puzzle out how to do this (at least with the existing interfaces) since presumably it needs to preserve the "shape" of the input batch.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDJCkX0uBITj4w0n-Q:-LcE8CZx5RD9QH1_cfiy:b-tnejdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L66)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

How badly does this affect the other selection benchmarks? Just pointing out that this is unnecessary - we only need `invert` for the `LIKE` case, right, since everything else has reversed variants already.

I would prefer to see template-time inverted like cases for all of the ones that require it, so that the other operators don't have this unnecessary comparison. I think it should be possible to accomplish this by just modifying the gen loop for the like operators.
</blockquote></details>

I'll double-check but I didn't see any difference when I ran the benchmarks. Intuitively a single bit comparison seems like it should be very cheap but I won't trust my intuition over the benchmarks.


<!-- Sent from Reviewable.io -->

2019-04-12 01:31 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDJCkX0uBITj4w0n-Q:-LcE9awh3tqvbrayi_Uo:bul0xcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L66)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'll double-check but I didn't see any difference when I ran the benchmarks. Intuitively a single bit comparison seems like it should be very cheap but I won't trust my intuition over the benchmarks.
</blockquote></details>

But also I take your point that it's more straightforward to just add more overloads, as long as we don't need to handle a more general NOT case.


<!-- Sent from Reviewable.io -->

2019-04-16 16:10 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @justinj, and @yuzefovich)

___
*[pkg/sql/exec/like_ops.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDOY-t2taTTCjrm3Px:-LcauD5JENUNJyu6jSjW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L27)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.
___
*[pkg/sql/exec/like_ops.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDGi9C-9QJ-ZcvVi65:-Lcat5l5AGa-6sIo-ozP:bhrjq1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/like_ops.go#L40)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

:man_facepalming: Good point about nulls.
</blockquote></details>

I'll fix the null handling in a separate PR.
___
*[pkg/sql/exec/operator.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDIopKEIRtqADjoNSr:-Lcat8KmEtZv_N-VxZ5I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/operator.go#L78)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you call this `ZeroOp` to match the `zeroNode` in the HP?
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDJCkX0uBITj4w0n-Q:-Lcat9wt0NmwW289RU09:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L66)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

But also I take your point that it's more straightforward to just add more overloads, as long as we don't need to handle a more general NOT case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-16 16:10 UTC, solongordon commented
Ready for a second look, thanks!

2019-04-16 16:13 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-:-LcavEgSD7ul7Ahj2D0l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/exec/operator.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDIktx36-scS2u0Ok3:-LcauoR6EhVtJf7_uul0:bmxievk) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/operator.go#L88)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I couldn't puzzle out how to do this (at least with the existing interfaces) since presumably it needs to preserve the "shape" of the input batch.
</blockquote></details>

Oh, I see. You'd have to add that argument to `NewZeroOp` like many of the other operators do. But this seems fine.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-LcDJCkX0uBITj4w0n-Q:-LcauwYsBlZY4Qi19_oN:b-mrdovj) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a660f55dd62ffc517c11f3928725b9d4bb4c0/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L66)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Agreed that in other cases this is cheap enough that we shouldn't bother trying to micro-optimize it. Here, it's the principle of the thing - we have the opportunity to do a perfect job planning the precise operator, so we should do it. I think sticking to our guns on that will pay dividends. Thanks for doing it!


<!-- Sent from Reviewable.io -->

2019-04-16 17:31 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36781#-:-LcbC2Zq1E7aH1JI90By:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-04-16 17:45 UTC, solongordon commented
bors r+

2019-04-16 18:04 UTC, merged