opt: support some basic window functions
cockroachdb/cockroach pull request #36843
Opened 2019-04-15 16:09 UTC by justinj

Window functions are operators which allow computations that take into
consideration other rows in the same result set.

More concretely, a window function is a relational operator that takes
in a result set and appends a single new column whose value depends on
the other rows within the result set, and that row's relative position
in it.

Depending on the exact window function being computed, the
value of the new column could be the position of the row in the output
(`row_number`), or a cumulative sum, or something else.

Window functions are always computed relative to a given partition (if
empty, there is just one single partition containing every row) defined
by the set of rows which have the same value for some set of columns.

This commit introduces support for a very limited subset of window
functions.

Supported are window functions:
* that are not aggregates, and
* have no arguments, and
* have no ordering or partitioning specified (thus, ordering is always
  ambiguous and the partition is always the entire input set).

What it does do is lay out the groundwork for how window functions are
optbuilt, represented, and execbuilt.

Since stats and some logical props are best-effort, those have been left
mostly unimplemented for the time being.

One major difference from how these window functions are execbuilt vs.
how they were planned in the HP is that we output a single planNode for
each window function being computed. In a future commit I think it will
be beneficial to collapse the tower of window functions down into a
single planNode, but for now this approach is simpler.

Release note: None

2019-04-15 16:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36843)
<!-- Reviewable:end -->

2019-04-15 17:55 UTC, RaduBerinde reviewed
Very cool that you already have something working end-to-end!

A high-level note (not necessarily for this PR): execution uses one windower processor for each unique `PARTITION BY` clause. I would expect our operator to be like that too (instead of one function at a time). Coalescing at exec-build time might be non-trivial if operators need to be reordered, plus it will be hard to cost the operators correctly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcX1Rx45GyR7ulbugle:b-q2n751)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX-bb47X91iGW4G4fU:-LcX-bb47X91iGW4G4fV:b5nv3mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt_exec_factory.go#L812)):*
> ```Go
> }
> 
> func (ef *execFactory) ConstructWindow(root exec.Node, wi exec.WindowInfo) (exec.Node, error) {
> ```

[nit] add `// ConstructWindow is part of the exec.Factory interface`
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX7ujR1nNLgWn9RG5S:-LcX7ujR1nNLgWn9RG5T:b-jbf1ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1353)):*
> ```Go
> 		overload.FixedReturnType(),
> 		// TODO(justin): does this need to be set to anything for a window function?
> 		&tree.FunctionProperties{},
> ```

Can't you get this with `GetBuiltinProperties`?
___
*[pkg/sql/opt/memo/expr.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX742g0Oh1VylUX_dU:-LcX742g0Oh1VylUX_dV:bokxr23) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/memo/expr.go#L121)):*
> ```Go
> var NullSingleton = &NullExpr{Typ: types.Unknown}
> 
> // TODO(justin): perhaps these should be auto-generated.
> ```

Where are these used?
___
*[pkg/sql/opt/memo/typing.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5Za0B9Rp_SErbJy1:-LcX5Za0B9Rp_SErbJy2:b4qfjqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/memo/typing.go#L144)):*
> ```Go
> 		return name, overload
> 	}
> 	return FindAggregateOverload(e)
> ```

[nit] add a comment here saying that all aggregate functions can be used as window functions
___
*[pkg/sql/opt/ops/relational.opt, line 836 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5fz05_RxbEii_aUa:-LcX5fz05_RxbEii_aUb:b-x3udqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/relational.opt#L836)):*
> ```
> }
> 
> # Window represents a window function.  Window functions are operators which
> ```

[nit] double space
___
*[pkg/sql/opt/optbuilder/groupby.go, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX63VcDUWSfqbcGSWz:-LcX63VcDUWSfqbcGSX-:brhc7il) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/groupby.go#L250)):*
> ```Go
> 	for i, agg := range aggInfos {
> 		if agg.WindowDef != nil {
> 			argCols = argCols[len(agg.args):]
> ```

[nit] a short comment here or for the function (saying that we ignore window fns) would be useful


<!-- Sent from Reviewable.io -->

2019-04-15 18:32 UTC, rytaft requested changes
This is awesome!

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcXGNBq6EnaiqTW_-hn:b-glzdop)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @yuzefovich)

___
*[pkg/sql/opt/operator.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX3EjM6kyth4cbCSoy:-LcX3EjM6kyth4cbCSoz:b6aan7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/operator.go#L200)):*
> ```Go
> }
> 
> // WindowOpReverseMap maps from an optimizer operator type to the name of an
> ```

[nit] an -> a
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5JTgDWhhM3LdWUww:-LcX5JTgDWhhM3LdWUwx:b5r5ggn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/exec/execbuilder/testdata/window#L38)):*
> ```
> ·                    spans  ALL
> 
> statement ok
> ```

why did you delete this stuff?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5xgwAZ6xfEvQJK4L:-LcX5xgwAZ6xfEvQJK4M:b-1bpiat) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/memo/logical_props_builder.go#L933)):*
> ```Go
> 	// Output columns are all passed through with the addition of one extra
> 	// column.
> 	rel.OutputCols = inputProps.OutputCols.Union(util.MakeFastIntSet(int(window.ColID)))
> ```

[nit] seems like it might be slightly better to avoid constructing a single-item fast int set like this:
```
rel.OutputCols = inputProps.OutputCols.Copy()
rel.OutputCols.Add(int(window.ColID))
```
___
*[pkg/sql/opt/ops/relational.opt, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX8yPZ2ZZHpsYBam9o:-LcX8yPZ2ZZHpsYBam9p:b6h2wqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/relational.opt#L850)):*
> ```
> define Window {
>     Input  RelExpr
>     Render ScalarExpr
> ```

[nit] I know Render matches the terminology used in the HP, but we haven't used this term at all in the optimizer. Maybe call it Projection or something else?
___
*[pkg/sql/opt/ops/scalar.opt, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX9EDoDSQ0prDJGf8n:-LcX9EDp3wjIU_Hrdv8j:bbhd2dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/scalar.opt#L898)):*
> ```
> }
> 
> # The name RowNumber is already taken by the relational operator.
> ```

Should we rename that other operator to Ordinality? (Not a big deal, but it would match the syntax...)
___
*[pkg/sql/opt/optbuilder/groupby.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXASvk5EpOR353mDo6:-LcXASvk5EpOR353mDo7:bbma2r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/groupby.go#L406)):*
> ```Go
> 
> 	// Make sure the GROUP BY columns have no special functions.
> 	b.semaCtx.Properties.Require("GROUP BY", tree.RejectSpecial|tree.RejectWindowApplications)
> ```

reject special already includes window functions
___
*[pkg/sql/opt/optbuilder/scope.go, line 957 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXB5JN4r7yihHeJcmL:-LcXB5JN4r7yihHeJcmM:b64wsh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/optbuilder/scope.go#L957)):*
> ```Go
> 
> 	s.builder.semaCtx.Properties.Require(s.context,
> 		tree.RejectNestedAggregates|tree.RejectWindowApplications)
> ```

how come you don't need to reject window functions here?
___
*[pkg/sql/opt/optbuilder/scope.go, line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXDXeE9PoUQfSdQDRH:-LcXDXeE9PoUQfSdQDRI:bh9pbi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/scope.go#L1016)):*
> ```Go
> 	}
> 
> 	private := memo.FunctionPrivate{
> ```

why not move this down closer to where it's needed?
___
*[pkg/sql/opt/optbuilder/scope.go, line 1022 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXFizv0jf_EbbQL8Wf:-LcXFizv0jf_EbbQL8Wg:b-p77fk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/scope.go#L1022)):*
> ```Go
> 	}
> 
> 	expr := f.Walk(s)
> ```

Do you need to add rejection of aggregates and window functions before this call?
___
*[pkg/sql/opt/optbuilder/select.go, line 663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXG2oXAc6QRARQc-mV:-LcXG2oXAc6QRARQc-mW:b24ey7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/select.go#L663)):*
> ```Go
> 	}
> 
> 	for i := range fromScope.windows {
> ```

Are there any weird scoping rules with window functions in subqueries like there are with aggregates?
___
*[pkg/sql/opt/optbuilder/select.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXELzF9OYknsCp-VVH:-LcXELzF9OYknsCp-VVI:bz7qmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/optbuilder/select.go#L795)):*
> ```Go
> }
> 
> // windowInfo stores information about a window function call.
> ```

I'd put this stuff in a separate file called `window.go`


<!-- Sent from Reviewable.io -->

2019-04-15 18:58 UTC, yuzefovich reviewed
Very excited about this!

Radu's point is worth noting, so possibly I should've not encouraged you to go with a function at a time approach. I still think it'd be easier for the vectorized engine to convert a single planned window function into a single columnar operator, but (at least at the moment) we're converting from specs of the processors, so we'll see only `windower`'s spec. Therefore, the internals of planning and optimizing will be hidden from the vectorized engine.

Another thing that always bothered me about `windowNode` is it does both computations of all window functions and rendering the results. I wonder if it'll be possible with your work to break it out into two separate nodes.

> Reviewed 4 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcXJq3DCrnJgG9WxOYq:b-gqhhd8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/operator.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXEAzUAh3ysBX1Wir7:-LcXEAzUAh3ysBX1Wir8:bqp7lan) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/operator.go#L200)):*
> ```Go
> }
> 
> // WindowOpReverseMap maps from an optimizer operator type to the name of an
> ```

[nit]: of "a" or possibly "the"
___
*[pkg/sql/opt/exec/factory.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXEX280gH9KU3d9GiM:-LcXEX292XUYfazqUpf6:b1bf89p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/factory.go#L469)):*
> ```Go
> 	Expr *tree.FuncExpr
> 
> 	// Idx is the index that the window function should put its output in (all
> ```

`ArgIdxStart` of a window function holder indicates the first argument-column to the function. We overload it as well to use as "output idx" like you're describing. If a function doesn't take any arguments, then `ArgIdxStart` is only understood as the second "meaning,", so the comment is correct at the moment but may not be going forward. Just FYI.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXFcpLC2bG18HrBgk9:-LcXFcpLC2bG18HrBgkA:bwm0tef) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1359)):*
> ```Go
> 	resultCols := make(sqlbase.ResultColumns, w.Relational().OutputCols.Len())
> 
> 	// All the passthrough cols will keep their ordinal index.
> ```

Actually, the ordinal indices might change (if there are window functions that take in number of arguments other than 1). For example, in the following query
`SELECT a, rank () OVER (), b FROM t`, due to `rank` taking no arguments, all columns after it will be "shifted" by one, meaning that `windower` receives the schema as `a -> 0, b -> 1` with `rank.ArgIdxStart = 1`, and it'll insert a new column for rank, and the output schema will be `a -> 0, rank -> 1, b -> 2`. In case of two or more arguments to a window function, the first column-argument is replaced by the result of computation whereas the second and the third are omitted from output entirely (i.e. those are "consumed"). Again, just FYI.


<!-- Sent from Reviewable.io -->

2019-04-15 20:20 UTC, RaduBerinde commented
>  I still think it'd be easier for the vectorized engine to convert a single planned window function into a single columnar operator

Even so, if there are multiple functions per `PARTITION BY`, we don't want to repartition for each one. So it would still be useful if we grouped them. Perhaps there will be an operator for reorganizing the data according to a `PARTITION BY` and another operator for calculating a window function on that output?

2019-04-15 20:43 UTC, andy-kimball reviewed
Great to see this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcXjNdR8Y6M1YgjM3CB:b-699yfe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 850 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX8yPZ2ZZHpsYBam9o:-LcXiRdQ79mFWcPF04m9:blibe4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/relational.opt#L850)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I know Render matches the terminology used in the HP, but we haven't used this term at all in the optimizer. Maybe call it Projection or something else?
</blockquote></details>

Is this going to work like `GroupBy` does today, where the `Render` can only be an instance of one of the window function exprs defined in `scalar.opt`? If so, then shouldn't we call this `Function`? Or, if we want to be able to easily compute multiple functions over the same partition, we'd call it `Functions`, and it would work just like `Aggregations` work today, with separate scalar slice operator.
___
*[pkg/sql/opt/ops/scalar.opt, line 894 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXincr9lIobK-HwfgH:-LcXincr9lIobK-HwfgI:br1yjfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/scalar.opt#L894)):*
> ```
> }
> 
> [Scalar, Window]
> ```

Can you add short descriptions to each of these to remind caller what they do, so they don't have to jump to docs?
___
*[pkg/sql/opt/ops/scalar.opt, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX9EDoDSQ0prDJGf8n:-LcXijFACYkdigwIbtZm:buofnod) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/ops/scalar.opt#L898)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should we rename that other operator to Ordinality? (Not a big deal, but it would match the syntax...)
</blockquote></details>

I like this idea, to reduce confusion.


<!-- Sent from Reviewable.io -->

2019-04-15 21:02 UTC, yuzefovich commented
> Even so, if there are multiple functions per `PARTITION BY`, we don't want to repartition for each one. So it would still be useful if we grouped them. Perhaps there will be an operator for reorganizing the data according to a `PARTITION BY` and another operator for calculating a window function on that output?
Yes, we definitely don't want to repartition the data. We will - similarly to existing DistSQL infrastructure - leverage columnar hash router to distribute the data and then will compute the window functions over it.

2019-04-16 15:27 UTC, justinj reviewed
I still tend to feel like one opt operator per function is the better approach.

First, if the current execution implementation works best when like-partitions are grouped, that's an optimization concern and we can arrange to have those together without too much trouble (I think this is not too difficult to do during normalization via a rule prop) and then collapse them during execbuild (even if pushing down things like `SELECT`s or `LIMIT`s would split up same-partitioned window functions, that still seems like a desirable optimization to do because it would reduce the amount of data that the higher-up window functions would have to process). 

But that's an artifact of the current implementation, and like Yahor said, the calculus here changes significantly when not only do we support vectorized window functions, but something else that I think we should support even sooner, which is (row-based) streaming window functions.

Today, we only support partitioning via hash, but [the paper we've talked about a bunch](http://vldb.org/pvldb/vol5/p1244_yucao_vldb2012.pdf) describes a way to structure the tree such that the window function operators *themselves* don't need to handle the sorting *or* partitioning. This is particularly compelling because it lets us decouple the partitioning+sorting strategy from the windowing operator itself and lets more information live in the structure of the opt tree rather than in fat operators, which I think is just generally good (consider that today, window functions can't really make use of indexes at all because they don't know when their input is sorted).

Once we have streaming execution, consider this (extremely contrived) example where having the window functions be separate is required to find the best plan:

Consider three window functions, `A`, `B`, `C`:
`A` has partition `{x, y}` and ordering `(a)`,
`B` has partition `{x}` and ordering `(y, b)`, and
`C` has partition `{x, y}` and ordering `(c)`.
Where we have an index on `(x, y, c)` and want to output the ordering
`(x, y, a)`.

The plan that requires the fewest sorts here is:
```
   Output (x, y, a)
           ^
           |
       Perform A
           ^
           |
  Sort to (x, y, a)
           ^
           |
       Perform B
           ^
           |
  Sort to (x, y, b)
           ^
           |
       Perform C
           ^
           |
     Scan (x, y, c)
```

But if `A` and `C` must be adjacent, then this plan is not legal.

I agree costing is an issue here but I'm not sure I foresee any window exploration rules at least until streaming is supported in the first place.

I could be convinced otherwise, but given the fact that there could be, in the future, a variety of ways of executing window functions, I think this implementation is the most flexible and orthogonal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcXfUD11xUOui2P4OE3:b-8nv9x4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX-bb47X91iGW4G4fU:-LcY09lf02sPQPb7rIwU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt_exec_factory.go#L812)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add `// ConstructWindow is part of the exec.Factory interface`
</blockquote></details>

Done.
___
*[pkg/sql/opt/operator.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX3EjM6kyth4cbCSoy:-LcY0DeG-gvfyWGB6Ve6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/operator.go#L200)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] an -> a
</blockquote></details>

Done.
___
*[pkg/sql/opt/operator.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXEAzUAh3ysBX1Wir7:-LcY0DxI2AhTQGyoBDIE:b-x5vo3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/operator.go#L200)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: of "a" or possibly "the"
</blockquote></details>

Done (both of you!).
___
*[pkg/sql/opt/exec/factory.go, line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXEX280gH9KU3d9GiM:-LcY0XUc09whEU0d9kFI:b-hzjyyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/factory.go#L469)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

`ArgIdxStart` of a window function holder indicates the first argument-column to the function. We overload it as well to use as "output idx" like you're describing. If a function doesn't take any arguments, then `ArgIdxStart` is only understood as the second "meaning,", so the comment is correct at the moment but may not be going forward. Just FYI.
</blockquote></details>

Thanks for the heads up—I think I will reckon with making sure these comments make sense for that when it comes time to actually make that change.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX7ujR1nNLgWn9RG5S:-LcY1FYGEVAcS3vfhwWv:b-oz8tyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1353)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can't you get this with `GetBuiltinProperties`?
</blockquote></details>

Good call!
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcXFcpLC2bG18HrBgk9:-LcY2bwJ4pow6uxIh_Fq:b-sj1cpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b2bae30020e1ce96f4406f3ab027cfb40bf812b/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1359)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually, the ordinal indices might change (if there are window functions that take in number of arguments other than 1). For example, in the following query
`SELECT a, rank () OVER (), b FROM t`, due to `rank` taking no arguments, all columns after it will be "shifted" by one, meaning that `windower` receives the schema as `a -> 0, b -> 1` with `rank.ArgIdxStart = 1`, and it'll insert a new column for rank, and the output schema will be `a -> 0, rank -> 1, b -> 2`. In case of two or more arguments to a window function, the first column-argument is replaced by the result of computation whereas the second and the third are omitted from output entirely (i.e. those are "consumed"). Again, just FYI.
</blockquote></details>

The way the optimizer handles column references actually makes this not really a problem right now, since its not concerned with the relative ordering of them until the very final step here where we go from opt representation->planNode. It might be a problem when we have arguments, but for now the ordering of the columns isn't an issue.
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5JTgDWhhM3LdWUww:-LcY3CqS00kaXP9iznUN:bixgjgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/exec/execbuilder/testdata/window#L38)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why did you delete this stuff?
</blockquote></details>

It seems concerned with execution, rather than the construction of the planNodes. I actually thought that this was probably copied over from the logic test but that appears to not be the case? 
___
*[pkg/sql/opt/memo/expr.go, line 121 at r1](https://reviewable.io/reviews/co [...]

2019-04-16 15:46 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 49 of 49 files at r2, 26 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcaorGqD6guFtF3xFPm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-Lcam2HvD4Jjcp2ykzxw:-Lcam2HvD4Jjcp2ykzxx:b-wgoj9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27815c4fde1bcc081f20500a1330feb1f8627f4/pkg/sql/opt/exec/execbuilder/relational_builder.go#L207)):*
> ```Go
> 
> 	case *memo.OrdinalityExpr:
> 		ep, err = b.buildRowNumber(t)
> ```

I think you should change this function to be `buildOrdinality` now
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5JTgDWhhM3LdWUww:-LcanYP1DQQI81o1nDzy:b-1h2by6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/exec/execbuilder/testdata/window#L38)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It seems concerned with execution, rather than the construction of the planNodes. I actually thought that this was probably copied over from the logic test but that appears to not be the case? 
</blockquote></details>

Ok! It might be in the planner_test, in which case I feel like we should try to keep them in sync....

Otherwise feel free to delete.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcamN8613F8gBhCMjbW:-LcamN8613F8gBhCMjbX:b-mfx42f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27815c4fde1bcc081f20500a1330feb1f8627f4/pkg/sql/opt/memo/statistics_builder.go#L1720)):*
> ```Go
> }
> 
> func (sb *statisticsBuilder) colStatRowNumber(
> ```

I'd change the names of these functions to `buildOrdinality` and `colStatOrdinality`


<!-- Sent from Reviewable.io -->

2019-04-16 15:54 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Cool, thanks for explaining. There are more details to the design that you thought of and which don't transpire from this initial change, so I defer to you.

> First, if the current execution implementation works best when like-partitions are grouped, that's an optimization concern and we can arrange to have those together without too much trouble (I think this is not too difficult to do during normalization via a rule prop)

Not sure how that would work, given that two functions that should be grouped could be arbitrarily far away from each other (depth-wise in the tree). But maybe it's enough if it works in a few common cases. Or maybe it's enough to group them in optbuilder and construct them in the right order.

> The plan that requires the fewest sorts here is:

I would only group functions that have the same partitioning and ordering requirement, so the groups above would stay separate. I think you can't minimize sorts without grouping these (whether they are explicitly grouped in an operator, or implicitly grouped in that they form a chain the tree).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-LcanW7K34qjf4vguUod:b-rf1zpd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, @RaduBerinde, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-04-16 16:55 UTC, justinj reviewed
>Not sure how that would work, given that two functions that should be grouped could be arbitrarily far away from each other (depth-wise in the tree). But maybe it's enough if it works in a few common cases. Or maybe it's enough to group them in optbuilder and construct them in the right order.

My thought here was that it would be like interesting orders, where each window function would transmit upwards via a rule prop the set of partitions that exist in the current tower and then individual window nodes could use that information to locally rearrange themselves. That might be overcomplicated though, like you said we could probably rearrange them in the optbuilder to similar effect (the exception being if two towers that are not connected during optbuild join together as a result of normalization, but not sure how common that is).

>I would only group functions that have the same partitioning and ordering requirement, so the groups above would stay separate. I think you can't minimize sorts without grouping these (whether they are explicitly grouped in an operator, or implicitly grouped in that they form a chain the tree).

Ah, I hadn't understood that you only meant to group partition+ordering and not just partition. I could certainly be convinced that's the right way to do it, it appears the existing code only groups on partition:
```
root@127.0.0.1:56533/defaultdb> explain (distsql) select rank() over (partition by k), rank() over (partition by v), rank() over (partition by k order by v) from kv;
  automatic |                                                                                                                                                                                                                      url
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    true    | https://cockroachdb.github.io/distsqlplan/decode.html#eJyckc1q6zAQhff3KcSsEq5KYrkrrZzQLkzBDqqhhOKFag3B1JGMJPeH4HcvtqBNCjZtd54Zf-d8oBNoozCTR3TAHyGCkkJrTYXOGTuswg-pegO-plDrtvPDuqRQGYvAT-Br3yBwKORTgwKlQrtaAwWFXtbNGNva-ijte_L8AhTuW6kdJ1dQ9hRM578SnZcHBB719OetD7VW5hXtKrqs3G1EkRZpnpHtnpNkuIpNdrdYfn6QRS5ubgXZ7knC_i8nddifdNiszvW5Tt75wZAmjCbxpEb8Gw2BrjXa4YXEVPK6LymgOmB4b2c6W-HOmmqsCWM-cuNCofPhGoUh1eE0CJ7D0SzM5mE2C8ff4LL_9xEAAP__xTzj5w==
(1 row)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-Lcaw83fDqkQ1tHDJOqb:bsvaok0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-Lcam2HvD4Jjcp2ykzxw:-Lcb1RxaDjy3as6T2goL:b-kl8g4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27815c4fde1bcc081f20500a1330feb1f8627f4/pkg/sql/opt/exec/execbuilder/relational_builder.go#L207)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you should change this function to be `buildOrdinality` now
</blockquote></details>

good catch!
___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5JTgDWhhM3LdWUww:-Lcb2-fYBcSsmBmZ-KW8:bmxvyl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/exec/execbuilder/testdata/window#L38)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ok! It might be in the planner_test, in which case I feel like we should try to keep them in sync....

Otherwise feel free to delete.
</blockquote></details>

I deleted it from the planner test and moved it into the logic test, since it involves execution.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcamN8613F8gBhCMjbW:-Lcb2xum2mTR5iOmqpj1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27815c4fde1bcc081f20500a1330feb1f8627f4/pkg/sql/opt/memo/statistics_builder.go#L1720)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I'd change the names of these functions to `buildOrdinality` and `colStatOrdinality`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-16 17:05 UTC, RaduBerinde reviewed
Yeah, I was thinking from the perspective of the current execution operator which AFAIK never cares about input ordering. But it sounds like you want to introduce a streaming kind of operator, so in that context it wouldn't make much sense to group together functions that require different orderings. Anyway, we can discuss more in person.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-:-Lcb4Shv793GWRtwTnip:bl7tfs6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @RaduBerinde, @rytaft, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-04-16 17:10 UTC, rytaft approved these changes
> Reviewed 28 of 28 files at r4, 28 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36843)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/window, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36843#-LcX5JTgDWhhM3LdWUww:-Lcb64qGASSymEyUIXkb:b-sb2x68) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c0b58566e052ce6c92c93a804a049aa14d313f0/pkg/sql/opt/exec/execbuilder/testdata/window#L38)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I deleted it from the planner test and moved it into the logic test, since it involves execution.
</blockquote></details>

Ok! As long as it still passes... I think we've kept most of these tracing outputs in the planner/execbuilder tests since the output depends on the plan as well as execution


<!-- Sent from Reviewable.io -->

2019-04-16 17:55 UTC, yuzefovich commented
> Ah, I hadn't understood that you only meant to group partition+ordering and not just partition. I could certainly be convinced that's the right way to do it, it appears the existing code only groups on partition:

I'm not sure what exact meaning of "grouping" is here, but the current execution code in regards to partitions and orderings is as follows:
1. for every PARTITION BY among all window functions we have a stage of `windower`s
2. for all window functions with the same partition, we "rearrange" the functions according to ORDER BY clauses so that we sort the data only once for each ordering (i.e. for a query with `rank() OVER (ORDER BY a), rank() OVER (ORDER BY b), rank() OVER (ORDER BY a)` we will sort the data by `a`, compute the first and the third functions, resort the data by `b`, and compute the second function). This, however, doesn't take into account any information about indexes/already ordered data.

2019-04-17 15:43 UTC, justinj commented
TFTRs!

bors r+

2019-04-17 16:03 UTC, merged