opt: support arguments to window functions
cockroachdb/cockroach pull request #36941
Opened 2019-04-18 21:53 UTC by justinj

A fair bit of complexity here, the main idea is that when building
window functions with arguments we create a projection that introduces
the arguments for the window function to consume.

When execbuilding, we then rearrange the columns to simplify knowing
where columns are going to end up, since in execution, window functions
always put their results in the place they took their arguments from.

I think this commit might be a bit undertested, since a lot of the logic
tests are still blocked on running under the optimizer due to PARTITION
and ORDER BY support, so it's possible that adding those will uncover
some bugs here due to unlocking a lot more of the logic tests.

Release note: None

2019-04-18 21:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36941)
<!-- Reviewable:end -->

2019-04-18 22:50 UTC, yuzefovich reviewed
Keep 'em coming!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-:-Lcmd4Eg9YaaDvr8Sap0:b-9jkxvr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmU4-o94RQbFFtDOLE:-LcmU4-pEw0LAeihiQ9U:boijza5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1365)):*
> ```Go
> 	for i, n := 0, w.Function.ChildCount(); i < n; i++ {
> 		col := w.Function.Child(i).(*memo.VariableExpr).Col
> 		args[i] = b.indexedVar(&ctx, b.mem.Metadata(), col)
> ```

Does this "automagically" handle all the cases (i.e. constant arguments, column names, random expressions, etc.)?
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1392 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmUQCXCpQ7AO9TQC_I:-LcmUQCXCpQ7AO9TQC_J:btco5tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1392)):*
> ```Go
> 
> 	// Because of the way we arranged the input columns, we will be outputting
> 	// the window column at the end.
> ```

I think in the vectorized engine we will also be appending new columns for the outputs of window functions, so I like this choice.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmUulU6Qdc2sZuChp9:-LcmUulU6Qdc2sZuChpA:b-vtadbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/memo/logical_props_builder.go#L946)):*
> ```Go
> 	// Outer columns were derived by BuildSharedProps; remove any that are bound
> 	// by input columns.
> 	rel.OuterCols.DifferenceWith(inputProps.OutputCols)
> ```

To confirm my understanding: this removes all the columns that were the arguments to the window function, right?
___
*[pkg/sql/opt/ops/relational.opt, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmW7Fb4E-basDo9GOG:-LcmW7Fb4E-basDo9GOH:b-5fnhtm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/relational.opt#L864)):*
> ```
> 
>     # Passthrough is the set of columns the window function passes through
>     # unchanged. Since the only columns pruned by a Window operator are the
> ```

[nit]: the second sentence of the comment seems unfinished to me.
___
*[pkg/sql/opt/ops/scalar.opt, line 961 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmWXOHDktA5c59dnpn:-LcmWXOHDktA5c59dnpo:b-gv5ewa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/scalar.opt#L961)):*
> ```
> }
> 
> # FirstValue returns Value evaluated at the first row in the row's partition.
> ```

Just FYI: to be more precise, "at the first row in the row's frame."
___
*[pkg/sql/opt/optbuilder/select.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmXTzSAnbgbaFzrW46:-LcmXTzSAnbgbaFzrW47:b-aswq76) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L699)):*
> ```Go
> 	// relation. Build a projection that produces those values to go underneath
> 	// the window functions.
> 	// TODO(justin): this is unfortunate in common cases where the arguments are
> ```

Hm, good point. I'll work on this tomorrow.
___
*[pkg/sql/opt/optbuilder/select.go, line 703 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmXsQl0ZBMxFxo5U0T:-LcmXsQl0ZBMxFxo5U0U:b-rowqd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L703)):*
> ```Go
> 	// would be good if the windower supported being specified with constant
> 	// values.
> 	// TODO(justin): it's possible we could reuse some projections here, if a
> ```

Another good point. I think it is worth refactoring `windowFuncHolder` to include additional `OutputIdx` so that each window function knows where to put its output. This way we'll remove overloading of the meaning of `ArgIdxStart`, and we'll be able to reuse some of the projections. Since some window functions might take up to 3 arguments, I think of introducing `Args []uint32` or similar. Also, I'll look into it tomorrow.


<!-- Sent from Reviewable.io -->

2019-04-19 15:10 UTC, rytaft requested changes
Nice!

> Reviewed 17 of 17 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-:-Lcq8Z-h1HJ1GF363y2s:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/ops/scalar.opt, line 947 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcpyPHg58zzBubxB1Fu:-LcpyPHg58zzBubxB1Fv:b-2w3w10) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/scalar.opt#L947)):*
> ```
>     Value  ScalarExpr
>     Offset ScalarExpr
>     Def    ScalarExpr
> ```

[nit] I'd call this `Default` for clarity
___
*[pkg/sql/opt/optbuilder/select.go, line 694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq-17t6F2Bvcict9oI:-Lcq-17t6F2Bvcict9oJ:bvojlvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L694)):*
> ```Go
> 
> // buildWindow adds any window functions on top of the expression.
> func (b *Builder) buildWindow(outScope *scope, inScope *scope) {
> ```

This function and the one below should be moved to `window.go`
___
*[pkg/sql/opt/optbuilder/select.go, line 707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq0Sqo2k47KqS_mTw3:-Lcq0Sqo2k47KqS_mTw4:b-tdiqxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L707)):*
> ```Go
> 	// TODO(justin): would it be better to just introduce a projection beneath
> 	// every window operator and then let norm rules push them all down and merge
> 	// them at the bottom, rather than building up one projection here?
> ```

I kind of like that you are building them all together, because it will allow you to remove redundant projections (based on my suggestion below). But if it simplifies the logic a lot to separate them, then go for it
___
*[pkg/sql/opt/optbuilder/select.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq1ZYsCwo7fWu13Cuq:-Lcq1ZYsCwo7fWu13Cur:b-k2w7xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L714)):*
> ```Go
> 		w.args = make(memo.ScalarListExpr, len(argExprs))
> 		for j, a := range argExprs {
> 			colID := b.factory.Metadata().AddColumn(
> ```

I think you should use `synthesizeColumn` here, so you add it to the scope. Then you can also check if a column already exists in the scope and avoid synthesizing a new one using `outScope.findExistingCol(a)`
___
*[pkg/sql/opt/optbuilder/select.go, line 727 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq4a7g2d0veT_qSOdo:-Lcq4a7g2d0veT_qSOdp:b-kh832b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L727)):*
> ```Go
> 	}
> 
> 	if len(projections) > 0 {
> ```

Better to use `constructProjectForScope` here, I think
___
*[pkg/sql/opt/optbuilder/select.go, line 779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq6VZkCfhglnf6fhEH:-Lcq6VZl6Hn4THnb-oJF:b-65hjf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L779)):*
> ```Go
> 		}
> 		if len(argExprs) < 3 {
> 			n, err := tree.ReType(tree.DNull, argExprs[0].ResolvedType())
> ```

[super nit] I think of `n` as usually representing a number. Maybe call this variable `null`? 
___
*[pkg/sql/opt/optbuilder/testdata/window, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq6xAz2zJ3wCGtH4WD:-Lcq6xB-DRjwWpRSCPE4:b6sffiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/testdata/window#L211)):*
> ```
> SELECT lag(1, 2, 3) OVER (), lead(1, 2, 3) FROM kv
> ----
> error (42809): window function lead() requires an OVER clause
> ```

did you mean for this to be an error?


<!-- Sent from Reviewable.io -->

2019-04-19 19:02 UTC, RaduBerinde approved these changes
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-:-LcqyccaEic_CFVjn0T7:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/sql/opt/ops/scalar.opt, line 941 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqvLA859rtSIduzXVO:-LcqvLA859rtSIduzXVP:b-80iir5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L941)):*
> ```
> # Lag returns Value evaluated at the row Offset rows before this one. If no
> # such row exists, returns Def.
> # Offset and Def are optional. We include three operators because we don't
> ```

They're optional in SQL syntax, but that's not directly relevant here. I'd just say that typical values for Offset and Def are 1 and NULL respectively.
___
*[pkg/sql/opt/ops/scalar.opt, line 946 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqvqN06MwjjaJM14B8:-LcqvqN06MwjjaJM14B9:bdv9elr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L946)):*
> ```
> define Lag {
>     Value  ScalarExpr
>     Offset ScalarExpr
> ```

Do offset and def need to be `ScalarExpr`s or can they just be `ConstExpr`? (not sure what SQL allows)
___
*[pkg/sql/opt/ops/scalar.opt, line 963 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcqws-B4QukwDNa_z-S:-Lcqws-B4QukwDNa_z-T:b-mi0qkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L963)):*
> ```
> # FirstValue returns Value evaluated at the first row in the row's partition.
> [Scalar, Window]
> define FirstValue {
> ```

There is semantic overlap between this and `FirstAgg`, I wonder if they should be the same?
___
*[pkg/sql/opt/ops/scalar.opt, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcqw2XhBX-19rVsS6tw:-Lcqw2XhBX-19rVsS6tx:bjzbnrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L973)):*
> ```
> }
> 
> # NthValue returns Value evaluated at the nth row in the row's partition.
> ```

Mention what happens if the partition has fewer rows than that (I assume returns NULL?)
___
*[pkg/sql/opt/optbuilder/groupby.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqwROJ45T0b2wRl4C6:-LcqwROJ45T0b2wRl4C7:b-admbwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/optbuilder/groupby.go#L532)):*
> ```Go
> 	case "nth_value":
> 		return b.factory.ConstructNthValue(args[0], args[1])
> 	case "string_agg":
> ```

should we add the `Window` tag to `StringAgg`? (and all the aggregates that can be window functions, which I guess is all of them with possible exceptions `AnyNotNullAgg` and `FirstAgg`)


<!-- Sent from Reviewable.io -->

2019-04-22 17:55 UTC, justinj reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 1365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmU4-o94RQbFFtDOLE:-Lcq9lVt29ALrxEYDbdJ:bv4g8tt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/exec/execbuilder/relational_builder.go#L1365)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Does this "automagically" handle all the cases (i.e. constant arguments, column names, random expressions, etc.)?
</blockquote></details>

Yup, because we constructed them all as references to the projection we introduced below.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmUulU6Qdc2sZuChp9:-Lcq9qq03iSKQOfhSrPf:b-lubquw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/memo/logical_props_builder.go#L946)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

To confirm my understanding: this removes all the columns that were the arguments to the window function, right?
</blockquote></details>

The `OuterCols` are the columns referenced by the operator that it doesn't have values for. If you're familiar with the concept of "free variables" it's basically that. This just says that if the window function references any columns, those can be satisfied by the columns coming in from the input.
___
*[pkg/sql/opt/ops/relational.opt, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmW7Fb4E-basDo9GOG:-LcqAARMCpWOTzTEU7Vp:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/relational.opt#L864)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the second sentence of the comment seems unfinished to me.
</blockquote></details>

Fixed.
___
*[pkg/sql/opt/ops/scalar.opt, line 947 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcpyPHg58zzBubxB1Fu:-LcqABaFDuqugmJXQhl0:b-23ne4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/scalar.opt#L947)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'd call this `Default` for clarity
</blockquote></details>

Unfortunately since `default` is a Go keyword this makes the resulting code not compile. Added a comment that it's actually meant to evoke "Default"
___
*[pkg/sql/opt/ops/scalar.opt, line 961 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcmWXOHDktA5c59dnpn:-LcqASd1BsLa7WsJOoeB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/ops/scalar.opt#L961)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Just FYI: to be more precise, "at the first row in the row's frame."
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/scalar.opt, line 941 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqvLA859rtSIduzXVO:-Ld4UIrr-Ah98NeVrsYJ:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L941)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

They're optional in SQL syntax, but that's not directly relevant here. I'd just say that typical values for Offset and Def are 1 and NULL respectively.
</blockquote></details>

Good point, fixed.
___
*[pkg/sql/opt/ops/scalar.opt, line 946 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqvqN06MwjjaJM14B8:-Ld4UQf85vYfjadew8qQ:bljhw9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L946)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do offset and def need to be `ScalarExpr`s or can they just be `ConstExpr`? (not sure what SQL allows)
</blockquote></details>

They can be arbitrary values, though as this is set up now these will always be `VariableExpr`s (like aggregations).
___
*[pkg/sql/opt/ops/scalar.opt, line 963 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcqws-B4QukwDNa_z-S:-Ld4UseB4t3ah9vYkBeu:b2hctgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L963)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There is semantic overlap between this and `FirstAgg`, I wonder if they should be the same?
</blockquote></details>

Hm, yeah I guess they are the same! It seems like we can't execbuild `FirstValue` at the moment though. Going to leave this as a TODO for the time being.
___
*[pkg/sql/opt/ops/scalar.opt, line 973 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcqw2XhBX-19rVsS6tw:-Ld4VvU5C-oMc6scsYLf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/ops/scalar.opt#L973)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Mention what happens if the partition has fewer rows than that (I assume returns NULL?)
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/groupby.go, line 532 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-LcqwROJ45T0b2wRl4C6:-Ld4Vz-H3h-X3VoBQqp6:bvi4d8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/optbuilder/groupby.go#L532)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

should we add the `Window` tag to `StringAgg`? (and all the aggregates that can be window functions, which I guess is all of them with possible exceptions `AnyNotNullAgg` and `FirstAgg`)
</blockquote></details>

At least right now I don't see a huge benefit to adding that, and saying that window functions can be anything with the `Window` tag or the `Aggregate` tag (there's no reason `AnyNotNullAgg` or `FirstAgg` *couldn't* be used as a window function if they had user-level names).
___
*[pkg/sql/opt/optbuilder/select.go, line 694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq-17t6F2Bvcict9oI:-LcqAUFm7TgkWgNHhG_9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L694)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This function and the one below should be moved to `window.go`
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/select.go, line 707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq0Sqo2k47KqS_mTw3:-Ld4FDY6DhRaSly_S-66:brnup66) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L707)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I kind of like that you are building them all together, because it will allow you to remove redundant projections (based on my suggestion below). But if it simplifies the logic a lot to separate them, then go for it
</blockquote></details>

That's a good point, I'll stick with building them together.z
___
*[pkg/sql/opt/optbuilder/select.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq1ZYsCwo7fWu13Cuq:-LcqAiKj70LJFdgDfMY2:b3nvhtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L714)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you should use `synthesizeColumn` here, [...]

2019-04-22 20:24 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-:-Ld5i0t199G1ii57SJZE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Ld5bqGW08hBE49NKrGZ:-Ld5bqGX73Q9KO1pGQ0U:b-pyfrpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/optbuilder/scope.go#L1041)):*
> ```Go
> 			Overload:   f.ResolvedOverload(),
> 		},
> 		col: s.builder.synthesizeColumn(s, def.Name, f.ResolvedType(), f, nil),
> ```

Why did you get rid of this?
___
*[pkg/sql/opt/optbuilder/select.go, line 714 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Lcq1ZYsCwo7fWu13Cuq:-Ld5cBBf958K2sjGrWMH:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae6509b9a8ac80b5b9dfda625c13c67ef7e1b48c/pkg/sql/opt/optbuilder/select.go#L714)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

We can't exploit this at the moment, due to the semantics of `windowNode` (boiling down to not being able to use input columns as arguments and also pass them through), though Yahor's work in #36943 will enable that in the future. Now that I'm thinking about it, I guess that's more of an execbuilder concern and we could maybe finagle things to output the same opt column twice at that point, but I think it might just be simpler to wait for Yahor's change to go in and then make the change as you're suggesting here.
</blockquote></details>

Ok!


<!-- Sent from Reviewable.io -->

2019-04-23 15:00 UTC, justinj reviewed
TFTRs! I think it will be simpler if I just wait for #36943 to go in, so I'm going to wait for that and rebase.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-:-Ld9hE534Lf8tM64qAbb:b-ovorp0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Ld5bqGW08hBE49NKrGZ:-Ld9azN8D1Mhjn66_l-w:b10op22) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/optbuilder/scope.go#L1041)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you get rid of this?
</blockquote></details>

It was adding the scopeColumn directly to the scope here, which wasn't what we wanted (we need the intermediate scope without window functions to add the window function arguments onto). I experimented for a while with adding a `windowScope` to `scope` so that we could use `synthesizeColumn` but it just made things more complicated, this ended up being the simplest solution I could come up with.


<!-- Sent from Reviewable.io -->

2019-04-23 17:06 UTC, rytaft approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36941)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/opt/optbuilder/scope.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36941#-Ld5bqGW08hBE49NKrGZ:-LdA9BtL2-FuFcpB14KT:b-uk9w9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe4426bbfd63b0ed6811b7ccf16cc0941b212ced/pkg/sql/opt/optbuilder/scope.go#L1041)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It was adding the scopeColumn directly to the scope here, which wasn't what we wanted (we need the intermediate scope without window functions to add the window function arguments onto). I experimented for a while with adding a `windowScope` to `scope` so that we could use `synthesizeColumn` but it just made things more complicated, this ended up being the simplest solution I could come up with.
</blockquote></details>

:thumbsup: Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2019-04-23 21:00 UTC, justinj commented
Changed my mind, sorry @yuzefovich I'd like to get this in sooner rather than later :) I'll loop back around for the other changes, let me know if you need help adapting the opt code for your changes.

bors r+

2019-04-23 22:15 UTC, merged