exec: add cancellation check to operators
cockroachdb/cockroach pull request #36967
Opened 2019-04-19 21:57 UTC by yuzefovich

We introduce a CancelChecker operator that wraps all other operators
and performs a cancellation check on every batch. Also, sorter and
hash joiner do additional checks themselves since they can spend
a lot of time in certain phases of execution.

Release note: None

2019-04-19 21:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36967)
<!-- Reviewable:end -->

2019-04-20 14:37 UTC, jordanlewis reviewed
Looks nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-LcvAUsIBUcdVMy7_GpF:b-vob8e8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Lcv9coHEBy3oLEdZHGs:-Lcv9coHEBy3oLEdZHGt:bchf1m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd3335923a4c64c37e037b99c9862a845266fd29/pkg/sql/distsqlrun/column_exec_setup.go#L450)):*
> ```Go
> 		op = exec.NewLimitOp(op, post.Limit)
> 	}
> 	return exec.NewCancelChecker(op), nil
> ```

I wonder if there's any significant advantage to doing this once per batch per operator as opposed to  just once per *input* batch. Like, you could install a single cancel checker at the top of the pipeline, below the table reader.

In this case, I think the effects would be nearly identical as long as there aren't any long-running operators. But we're already adding fixes to all of the long running operators individually...
___
*[pkg/sql/exec/sort.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Lcv9GOq4sqJTv2WmHRn:-Lcv9GOq4sqJTv2WmHRo:bu6f07f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd3335923a4c64c37e037b99c9862a845266fd29/pkg/sql/exec/sort.go#L364)):*
> ```Go
> 		// Since we can spend a lot of time doing sorting here, it's worth to check
> 		// for cancellation explicitly.
> 		// TODO(yuzefovich): is this granular enough?
> ```

I kind of doubt it - it misses the common case of a large global sort on a single column. That might take a long time and should be interruptable.


<!-- Sent from Reviewable.io -->

2019-04-22 17:26 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Lcv9coHEBy3oLEdZHGs:-Ld4rfjm56D46Da3plrS:b-95p3it) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd3335923a4c64c37e037b99c9862a845266fd29/pkg/sql/distsqlrun/column_exec_setup.go#L450)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I wonder if there's any significant advantage to doing this once per batch per operator as opposed to  just once per *input* batch. Like, you could install a single cancel checker at the top of the pipeline, below the table reader.

In this case, I think the effects would be nearly identical as long as there aren't any long-running operators. But we're already adding fixes to all of the long running operators individually...
</blockquote></details>

Good point, done. I also think this should be sufficient with individual operators doing the checks as well.
___
*[pkg/sql/exec/sort.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Lcv9GOq4sqJTv2WmHRn:-Ld5452U7ew1qXLsmO2l:brlzun5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd3335923a4c64c37e037b99c9862a845266fd29/pkg/sql/exec/sort.go#L364)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I kind of doubt it - it misses the common case of a large global sort on a single column. That might take a long time and should be interruptable.
</blockquote></details>

Agreed. I basically copied the approach from existing sorter now.


<!-- Sent from Reviewable.io -->

2019-04-22 17:41 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld56U9c1xi000mRsnjc:-Ld56U9c1xi000mRsnjd:b-6ykjx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/hashjoiner_tmpl.go#L272)):*
> ```Go
> 	nKeys uint64,
> 	sel []uint16,
> 	cancelChecker CancelChecker,
> ```

Would it make more sense to put the cancelChecker in the `hashTable` struct itself? Not sure, I guess the downside of that is that it has to know the context ahead of time, which is something that we try to avoid.
___
*[pkg/sql/exec/quicksort_tmpl.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld561QcA_ixMCaK_7c2:-Ld561QcA_ixMCaK_7c3:bf1r1op) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/quicksort_tmpl.go#L197)):*
> ```Go
> 		}
> 		maxDepth--
> 		cancelChecker.check()
> ```

Do we also need one below, in the other if? This looks like only happens for small slices. I don't know how this implementation works very well.

Also could you show results of sort benchmarks?


<!-- Sent from Reviewable.io -->

2019-04-22 17:54 UTC, asubiotto requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/cancel_checker.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58EW_5hP2riEqJcTA:-Ld58EW_5hP2riEqJcTB:b-k0kpu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L25)):*
> ```Go
> )
> 
> // CancelChecker is an Operator that checks whether a query cancellation has
> ```

`s/a query/query`
___
*[pkg/sql/exec/cancel_checker.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58SCH9_0xA1a3f4SM:-Ld58SCI7APbUmBN7ZOc:bz9omj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L46)):*
> ```Go
> 
> // Init is part of Operator interface.
> func (c *CancelChecker) Init() {
> ```

I believe you can elide this definition (the embedded `Init` will be called by default)
___
*[pkg/sql/exec/cancel_checker.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58ehXDkTt0Ow5s38h:-Ld58ehXDkTt0Ow5s38i:b-75crzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L61)):*
> ```Go
> const cancelCheckInterval = 1024
> 
> // check panics with query canceled error if the associated query has been
> ```

`s/with query/with a query`
___
*[pkg/sql/exec/cancel_checker.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58plx2UpYYsbJnt9_:-Ld58plx2UpYYsbJnt9a:b-t05xfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L70)):*
> ```Go
> 	// Increment. This may rollover when the 32-bit capacity is reached, but
> 	// that's all right.
> 	atomic.AddUint32(&c.callsSinceLastCheck, 1)
> ```

TODO: come back to this
___
*[pkg/sql/exec/cancel_checker_test.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld599vA7HTH8jJ7sLWE:-Ld599vBEirA27GIilxM:b-k7tp22) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker_test.go#L33)):*
> ```Go
> 	op := NewCancelChecker(NewNoop(newRepeatableBatchSource(batch)))
> 	cancel()
> 	if err := CatchVectorizedRuntimeError(func() {
> ```

You might be able to use the `require` package here again (using `require.Panics`)
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld56U9c1xi000mRsnjc:-Ld59tViBkkuHORZaI0O:bs659ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/hashjoiner_tmpl.go#L272)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Would it make more sense to put the cancelChecker in the `hashTable` struct itself? Not sure, I guess the downside of that is that it has to know the context ahead of time, which is something that we try to avoid.
</blockquote></details>

One solution would be to put the `cancelChecker` in the `hashTable` struct but remove the context field from the `cancelChecker` struct and make that an argument to `check` instead. This way the `hashTable` could take a `context.Context` that it then passes to its `cancelChecker.check` which makes for more idiomatic go and doesn't require a context field.


<!-- Sent from Reviewable.io -->

2019-04-22 21:01 UTC, yuzefovich reviewed
Benchmark of the general sorter:
```
name                        old time/op    new time/op    delta
Sort/rows=2048/cols=1-12      20.1µs ±10%    17.7µs ±12%    -11.94%  (p=0.002 n=10+10)
Sort/rows=2048/cols=2-12       128µs ± 6%     145µs ± 8%    +13.12%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12       222µs ± 3%     300µs ±11%    +34.79%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12      164µs ±11%     160µs ± 9%       ~     (p=0.393 n=10+10)
Sort/rows=16384/cols=2-12     1.09ms ± 6%    1.11ms ± 3%       ~     (p=0.218 n=10+10)
Sort/rows=16384/cols=4-12     1.84ms ± 8%    2.00ms ± 7%     +8.65%  (p=0.000 n=10+9)
Sort/rows=262144/cols=1-12    2.68ms ± 9%    2.37ms ± 3%    -11.41%  (p=0.000 n=10+9)
Sort/rows=262144/cols=2-12    15.3ms ± 7%    15.3ms ± 2%       ~     (p=0.829 n=10+8)
Sort/rows=262144/cols=4-12    33.1ms ± 6%    32.3ms ± 1%       ~     (p=0.515 n=10+8)

name                        old speed      new speed      delta
Sort/rows=2048/cols=1-12     820MB/s ±10%   929MB/s ±11%    +13.31%  (p=0.002 n=10+10)
Sort/rows=2048/cols=2-12     256MB/s ± 6%   226MB/s ± 8%    -11.57%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12     295MB/s ± 3%   219MB/s ±10%    -25.61%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12    799MB/s ±10%   819MB/s ± 8%       ~     (p=0.393 n=10+10)
Sort/rows=16384/cols=2-12    240MB/s ± 5%   236MB/s ± 3%       ~     (p=0.218 n=10+10)
Sort/rows=16384/cols=4-12    285MB/s ± 8%   262MB/s ± 6%     -8.00%  (p=0.000 n=10+9)
Sort/rows=262144/cols=1-12   785MB/s ± 9%   884MB/s ± 3%    +12.62%  (p=0.000 n=10+9)
Sort/rows=262144/cols=2-12   274MB/s ± 7%   275MB/s ± 2%       ~     (p=0.829 n=10+8)
Sort/rows=262144/cols=4-12   254MB/s ± 6%   259MB/s ± 1%       ~     (p=0.515 n=10+8)

name                        old alloc/op   new alloc/op   delta
Sort/rows=2048/cols=1-12      73.2kB ± 0%    73.3kB ± 0%     +0.09%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12       113kB ± 0%     121kB ± 0%     +7.01%  (p=0.000 n=10+9)
Sort/rows=2048/cols=4-12       206kB ± 0%     267kB ± 0%    +29.87%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12      885kB ± 0%     885kB ± 0%     +0.01%  (p=0.000 n=10+10)
Sort/rows=16384/cols=2-12     1.52MB ± 0%    1.56MB ± 0%     +2.36%  (p=0.000 n=9+10)
Sort/rows=16384/cols=4-12     2.78MB ± 0%    2.94MB ± 0%     +5.84%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-12    16.0MB ± 0%    16.0MB ± 0%     +0.00%  (p=0.000 n=8+10)
Sort/rows=262144/cols=2-12    28.0MB ± 0%    28.0MB ± 0%     +0.13%  (p=0.000 n=8+10)
Sort/rows=262144/cols=4-12    51.5MB ± 0%    51.7MB ± 0%     +0.31%  (p=0.000 n=10+10)

name                        old allocs/op  new allocs/op  delta
Sort/rows=2048/cols=1-12        27.0 ± 0%      29.0 ± 0%     +7.41%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12        45.0 ± 0%     293.3 ± 3%   +551.85%  (p=0.000 n=10+9)
Sort/rows=2048/cols=4-12        81.0 ± 0%    1999.4 ± 1%  +2368.40%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12       65.0 ± 0%      67.0 ± 0%     +3.08%  (p=0.000 n=10+10)
Sort/rows=16384/cols=2-12        121 ± 0%      1243 ± 3%   +927.44%  (p=0.000 n=10+10)
Sort/rows=16384/cols=4-12        233 ± 0%      5304 ± 1%  +2176.22%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-12       564 ± 0%       566 ± 0%     +0.35%  (p=0.000 n=10+10)
Sort/rows=262144/cols=2-12     1.12k ± 0%     2.22k ± 1%    +98.67%  (p=0.000 n=10+10)
Sort/rows=262144/cols=4-12     2.23k ± 0%     7.28k ± 1%   +226.50%  (p=0.000 n=10+10)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-Ld5m5JFCmp7BU6sfjh5:b718odb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec/cancel_checker.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58EW_5hP2riEqJcTA:-Ld5cVyoCZfwgT3PZdLn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L25)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/a query/query`
</blockquote></details>

Done.
___
*[pkg/sql/exec/cancel_checker.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58SCH9_0xA1a3f4SM:-Ld5c__xAM8YFkZ0Hqr0:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L46)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I believe you can elide this definition (the embedded `Init` will be called by default)
</blockquote></details>

Thanks, done.
___
*[pkg/sql/exec/cancel_checker.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58ehXDkTt0Ow5s38h:-Ld5cgOK29pm9zYZQ8su:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/with query/with a query`
</blockquote></details>

Done.
___
*[pkg/sql/exec/cancel_checker.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58plx2UpYYsbJnt9_:-Ld5ly-OE7n8cv9QyKxE:bd4f9pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

TODO: come back to this
</blockquote></details>

Did you mean for me to leave a TODO like this? Or was it for your own attention?
___
*[pkg/sql/exec/cancel_checker_test.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld599vA7HTH8jJ7sLWE:-Ld5cKqXEUgB7pdVjYu4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker_test.go#L33)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You might be able to use the `require` package here again (using `require.Panics`)
</blockquote></details>

Done.
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld56U9c1xi000mRsnjc:-Ld5lsoa5h5pGvwHGv8V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/hashjoiner_tmpl.go#L272)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

One solution would be to put the `cancelChecker` in the `hashTable` struct but remove the context field from the `cancelChecker` struct and make that an argument to `check` instead. This way the `hashTable` could take a `context.Context` that it then passes to its `cancelChecker.check` which makes for more idiomatic go and doesn't require a context field.
</blockquote></details>

Done.
___
*[pkg/sql/exec/quicksort_tmpl.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld561QcA_ixMCaK_7c2:-Ld59qs9C0ubfgzyGoGu:b-vtkvb6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/quicksort_tmpl.go#L197)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Do we also need one below, in the other if? This looks like only happens for small slices. I don't know how this implementation works very well.

Also could you show results of sort benchmarks?
</blockquote></details>

I also wondered about that. `sqlbase/sort.go` doesn't check it in case `12 > b-a > 1`, I'm assuming, because that case should be extremely quick.


<!-- Sent from Reviewable.io -->

2019-04-22 21:15 UTC, yuzefovich reviewed
I decided to try having to pass `CancelChecker` by pointer, and the results are surprising to me (note that this is the comparison of current master against cancellation branch and not the comparison between cancellation with values and with pointers):
```
name                        old time/op    new time/op    delta
Sort/rows=2048/cols=1-12      20.8µs ±13%    17.7µs ± 8%  -14.70%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12       139µs ±14%     128µs ± 5%   -7.81%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12       227µs ± 2%     214µs ± 2%   -6.00%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12      161µs ± 6%     149µs ± 2%   -7.43%  (p=0.000 n=10+9)
Sort/rows=16384/cols=2-12     1.08ms ± 7%    1.02ms ± 3%   -5.39%  (p=0.000 n=10+9)
Sort/rows=16384/cols=4-12     1.75ms ± 1%    1.70ms ± 2%   -2.71%  (p=0.000 n=8+10)
Sort/rows=262144/cols=1-12    2.41ms ± 9%    2.32ms ± 5%     ~     (p=0.065 n=10+9)
Sort/rows=262144/cols=2-12    16.1ms ± 7%    14.5ms ± 2%  -10.31%  (p=0.000 n=10+8)
Sort/rows=262144/cols=4-12    36.6ms ±14%    29.7ms ± 1%  -18.75%  (p=0.000 n=10+8)

name                        old speed      new speed      delta
Sort/rows=2048/cols=1-12     793MB/s ±12%   927MB/s ± 7%  +16.88%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12     236MB/s ±12%   255MB/s ± 4%   +8.19%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12     288MB/s ± 2%   307MB/s ± 2%   +6.37%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12    816MB/s ± 6%   881MB/s ± 2%   +7.93%  (p=0.000 n=10+9)
Sort/rows=16384/cols=2-12    243MB/s ± 6%   256MB/s ± 3%   +5.65%  (p=0.000 n=10+9)
Sort/rows=16384/cols=4-12    300MB/s ± 1%   308MB/s ± 2%   +2.79%  (p=0.000 n=8+10)
Sort/rows=262144/cols=1-12   872MB/s ± 8%   901MB/s ± 3%     ~     (p=0.122 n=10+8)
Sort/rows=262144/cols=2-12   258MB/s ± 7%   290MB/s ± 2%  +12.25%  (p=0.000 n=9+8)
Sort/rows=262144/cols=4-12   231MB/s ±15%   282MB/s ± 1%  +22.25%  (p=0.000 n=10+8)

name                        old alloc/op   new alloc/op   delta
Sort/rows=2048/cols=1-12      73.2kB ± 0%    73.3kB ± 0%   +0.04%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12       113kB ± 0%     113kB ± 0%   +0.03%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12       206kB ± 0%     206kB ± 0%   +0.02%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12      885kB ± 0%     885kB ± 0%   +0.00%  (p=0.000 n=10+10)
Sort/rows=16384/cols=2-12     1.52MB ± 0%    1.52MB ± 0%   +0.00%  (p=0.000 n=10+10)
Sort/rows=16384/cols=4-12     2.78MB ± 0%    2.78MB ± 0%   +0.00%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-12    16.0MB ± 0%    16.0MB ± 0%   +0.00%  (p=0.000 n=10+10)
Sort/rows=262144/cols=2-12    28.0MB ± 0%    28.0MB ± 0%   +0.00%  (p=0.000 n=9+8)
Sort/rows=262144/cols=4-12    51.5MB ± 0%    51.5MB ± 0%   +0.00%  (p=0.000 n=8+10)

name                        old allocs/op  new allocs/op  delta
Sort/rows=2048/cols=1-12        27.0 ± 0%      28.0 ± 0%   +3.70%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-12        45.0 ± 0%      46.0 ± 0%   +2.22%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-12        81.0 ± 0%      82.0 ± 0%   +1.23%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-12       65.0 ± 0%      66.0 ± 0%   +1.54%  (p=0.000 n=10+10)
Sort/rows=16384/cols=2-12        121 ± 0%       122 ± 0%   +0.83%  (p=0.000 n=10+10)
Sort/rows=16384/cols=4-12        233 ± 0%       234 ± 0%   +0.43%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-12       564 ± 0%       565 ± 0%   +0.18%  (p=0.000 n=10+10)
Sort/rows=262144/cols=2-12     1.12k ± 0%     1.12k ± 0%   +0.09%  (p=0.000 n=10+10)
Sort/rows=262144/cols=4-12     2.23k ± 0%     2.23k ± 0%   +0.04%  (p=0.000 n=10+10)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-Ld5tCep4uKfTfr3D7Tw:b-q6u9oj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-04-22 21:40 UTC, yuzefovich reviewed
Reduced hash joiner benchmark:
```
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=2048-12        299µs ± 5%     350µs ± 7%  +16.85%  (p=0.000 n=10+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=262144-12     25.7ms ± 2%    32.4ms ± 6%  +26.28%  (p=0.000 n=10+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=4194304-12     397ms ± 6%     488ms ± 3%  +22.97%  (p=0.000 n=10+9)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=2048-12         375µs ± 7%     408µs ± 2%   +8.66%  (p=0.000 n=10+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=262144-12      34.2ms ± 2%    39.7ms ± 2%  +16.15%  (p=0.000 n=10+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=4194304-12      540ms ± 6%     625ms ± 4%  +15.56%  (p=0.000 n=10+9)

name                                                                  old speed      new speed      delta
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=2048-12      438MB/s ± 5%   375MB/s ± 6%  -14.40%  (p=0.000 n=10+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=262144-12    654MB/s ± 2%   519MB/s ± 6%  -20.71%  (p=0.000 n=10+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=4194304-12   677MB/s ± 6%   550MB/s ± 3%  -18.72%  (p=0.000 n=10+9)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=2048-12       350MB/s ± 7%   321MB/s ± 2%   -8.06%  (p=0.000 n=10+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=262144-12     491MB/s ± 2%   422MB/s ± 2%  -13.92%  (p=0.000 n=10+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=4194304-12    497MB/s ± 6%   430MB/s ± 4%  -13.50%  (p=0.000 n=10+9)

name                                                                  old alloc/op   new alloc/op   delta
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=2048-12        805kB ± 0%     805kB ± 0%     ~     (p=0.126 n=8+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=262144-12     46.4MB ± 0%    46.4MB ± 0%     ~     (p=0.262 n=10+10)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=4194304-12     699MB ± 0%     699MB ± 0%     ~     (p=1.000 n=8+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=2048-12         805kB ± 0%     805kB ± 0%     ~     (p=0.211 n=10+10)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=262144-12      46.4MB ± 0%    46.4MB ± 0%     ~     (p=0.229 n=10+9)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=4194304-12      699MB ± 0%     699MB ± 0%     ~     (p=0.952 n=10+9)

name                                                                  old allocs/op  new allocs/op  delta
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=2048-12        8.29k ± 0%     8.29k ± 0%     ~     (all equal)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=262144-12      1.05M ± 0%     1.05M ± 0%     ~     (all equal)
HashJoiner/nulls=false/fullOuter=false/distinct=true/rows=4194304-12     16.8M ± 0%     16.8M ± 0%     ~     (all equal)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=2048-12         8.29k ± 0%     8.29k ± 0%     ~     (all equal)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=262144-12       1.05M ± 0%     1.05M ± 0%     ~     (all equal)
HashJoiner/nulls=true/fullOuter=false/distinct=true/rows=4194304-12      16.8M ± 0%     16.8M ± 0%     ~     (all equal)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-Ld5zSm109AlPCe0FEtE:b-hvxtj4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @jordanlewis, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-04-22 23:53 UTC, jordanlewis approved these changes
So you are suggesting that somehow passing the cancel checker by pointer makes the general sorter just faster? That seems suspicious... why do you think that is? Must be something more going on here.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> though

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-Ld6SgjE6gesMir6Gt4e:bre4ekp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-04-23 00:21 UTC, asubiotto requested changes
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, @solongordon, and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6Ysnq-lfKC2nQQ-1d:-Ld6Ysnq-lfKC2nQQ-1e:b-qv31qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/distsqlrun/column_exec_setup.go#L119)):*
> ```Go
> 		}
> 		op, err = newColBatchScan(flowCtx, core.TableReader, post)
> 		op = exec.NewCancelChecker(op)
> ```

Maybe add a comment as to why it's only necessary to wrap the `colBatchScan`.
___
*[pkg/sql/exec/cancel_checker.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58plx2UpYYsbJnt9_:-Ld6YA518fOSJvJv4HKU:botwsyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L70)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Did you mean for me to leave a TODO like this? Or was it for your own attention?
</blockquote></details>

Oops. This was for my own attention. What I was going to ask is why do we need an atomic here?
___
*[pkg/sql/exec/cancel_checker.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6Y-hC7g04QdBaHb58:-Ld6Y-hC7g04QdBaHb59:b-db0pss) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/exec/cancel_checker.go#L54)):*
> ```Go
> 
> // check panics with a query canceled error if the associated query has been
> // canceled. The check is performed on every 1024th call. This should be used
> ```

`s/1024/cancelCheckInterval`
___
*[pkg/sql/exec/quicksort_tmpl.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6YWXc8CORXg_VcVod:-Ld6YWXc8CORXg_VcVoe:b-6js0ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/exec/quicksort_tmpl.go#L61)):*
> ```Go
> }
> 
> func (p *sort_TYPE_DIROp) heapSort(a, b int, ctx context.Context, cancelChecker *CancelChecker) {
> ```

Should we embed this `cancelChecker` in the sort struct as we do with the hash table? I suppose this is what the benchmark discussion was about. It seems suspicious to me as well.


<!-- Sent from Reviewable.io -->

2019-04-23 01:02 UTC, yuzefovich commented
@jordanlewis you were right about probably my Mac being noisy. The results of running the benchmark on gce worker:
```
name                        old time/op    new time/op    delta
Sort/rows=2048/cols=1-24      45.6µs ± 2%    47.2µs ± 3%  +3.33%  (p=0.000 n=10+9)
Sort/rows=2048/cols=2-24       236µs ± 2%     239µs ± 2%  +1.31%  (p=0.029 n=10+10)
Sort/rows=2048/cols=4-24       412µs ± 1%     419µs ± 2%  +1.57%  (p=0.000 n=9+8)
Sort/rows=16384/cols=1-24      438µs ± 1%     469µs ± 8%  +7.16%  (p=0.013 n=9+10)
Sort/rows=16384/cols=2-24     2.00ms ± 2%    1.99ms ± 2%    ~     (p=0.515 n=8+10)
Sort/rows=16384/cols=4-24     3.38ms ± 2%    3.47ms ± 1%  +2.70%  (p=0.000 n=10+9)
Sort/rows=262144/cols=1-24    6.53ms ± 1%    6.51ms ± 1%    ~     (p=0.684 n=10+10)
Sort/rows=262144/cols=2-24    28.1ms ± 2%    28.3ms ± 3%    ~     (p=0.356 n=10+9)
Sort/rows=262144/cols=4-24    63.8ms ± 3%    62.7ms ± 3%    ~     (p=0.089 n=10+10)

name                        old speed      new speed      delta
Sort/rows=2048/cols=1-24     359MB/s ± 2%   348MB/s ± 3%  -3.23%  (p=0.000 n=10+9)
Sort/rows=2048/cols=2-24     139MB/s ± 2%   137MB/s ± 2%  -1.29%  (p=0.025 n=10+10)
Sort/rows=2048/cols=4-24     159MB/s ± 1%   155MB/s ± 6%  -2.31%  (p=0.000 n=9+9)
Sort/rows=16384/cols=1-24    299MB/s ± 1%   281MB/s ± 8%  -6.25%  (p=0.013 n=9+10)
Sort/rows=16384/cols=2-24    131MB/s ± 2%   132MB/s ± 2%    ~     (p=0.515 n=8+10)
Sort/rows=16384/cols=4-24    155MB/s ± 2%   151MB/s ± 1%  -2.64%  (p=0.000 n=10+9)
Sort/rows=262144/cols=1-24   321MB/s ± 1%   322MB/s ± 1%    ~     (p=0.684 n=10+10)
Sort/rows=262144/cols=2-24   149MB/s ± 2%   148MB/s ± 4%    ~     (p=0.368 n=10+9)
Sort/rows=262144/cols=4-24   131MB/s ± 3%   134MB/s ± 3%    ~     (p=0.089 n=10+10)

name                        old alloc/op   new alloc/op   delta
Sort/rows=2048/cols=1-24      73.2kB ± 0%    73.3kB ± 0%  +0.04%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-24       113kB ± 0%     113kB ± 0%  +0.03%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-24       206kB ± 0%     206kB ± 0%  +0.02%  (p=0.000 n=10+8)
Sort/rows=16384/cols=1-24      885kB ± 0%     885kB ± 0%  +0.00%  (p=0.000 n=9+10)
Sort/rows=16384/cols=2-24     1.52MB ± 0%    1.52MB ± 0%  +0.00%  (p=0.000 n=10+10)
Sort/rows=16384/cols=4-24     2.78MB ± 0%    2.78MB ± 0%  +0.00%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-24    16.0MB ± 0%    16.0MB ± 0%  +0.00%  (p=0.000 n=9+10)
Sort/rows=262144/cols=2-24    28.0MB ± 0%    28.0MB ± 0%  +0.00%  (p=0.000 n=10+10)
Sort/rows=262144/cols=4-24    51.5MB ± 0%    51.5MB ± 0%  +0.00%  (p=0.000 n=10+10)

name                        old allocs/op  new allocs/op  delta
Sort/rows=2048/cols=1-24        27.0 ± 0%      28.0 ± 0%  +3.70%  (p=0.000 n=10+10)
Sort/rows=2048/cols=2-24        45.0 ± 0%      46.0 ± 0%  +2.22%  (p=0.000 n=10+10)
Sort/rows=2048/cols=4-24        81.0 ± 0%      82.0 ± 0%  +1.23%  (p=0.000 n=10+10)
Sort/rows=16384/cols=1-24       65.0 ± 0%      66.0 ± 0%  +1.54%  (p=0.000 n=10+10)
Sort/rows=16384/cols=2-24        121 ± 0%       122 ± 0%  +0.83%  (p=0.000 n=10+10)
Sort/rows=16384/cols=4-24        233 ± 0%       234 ± 0%  +0.43%  (p=0.000 n=10+10)
Sort/rows=262144/cols=1-24       564 ± 0%       565 ± 0%  +0.18%  (p=0.000 n=10+10)
Sort/rows=262144/cols=2-24     1.12k ± 0%     1.12k ± 0%  +0.09%  (p=0.000 n=10+10)
Sort/rows=262144/cols=4-24     2.23k ± 0%     2.23k ± 0%  +0.04%  (p=0.000 n=10+10)
```

2019-04-23 02:31 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @georgeutsin, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6Ysnq-lfKC2nQQ-1d:-Ld6upUw8ekcP9c3BwnG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/distsqlrun/column_exec_setup.go#L119)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe add a comment as to why it's only necessary to wrap the `colBatchScan`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/cancel_checker.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld58plx2UpYYsbJnt9_:-Ld6vMx55AU0idhBcjUf:biuulue) ([raw file](https://github.com/cockroachdb/cockroach/blob/a71b9e9da1446c65810f681fcf2598cdba55b5e8/pkg/sql/exec/cancel_checker.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oops. This was for my own attention. What I was going to ask is why do we need an atomic here?
</blockquote></details>

I guess I just copy/pasted it. I don't see a reason for it at the moment, so I removed it. Maybe in the future we will want to parallelize sort or something like that? We can always add it back later if needed.
___
*[pkg/sql/exec/cancel_checker.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6Y-hC7g04QdBaHb58:-Ld6v9W28wMVlEKu4Ayt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/exec/cancel_checker.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/1024/cancelCheckInterval`
</blockquote></details>

Done.
___
*[pkg/sql/exec/quicksort_tmpl.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-Ld6YWXc8CORXg_VcVod:-Ld70Qa66j4CSvJKB6eX:b-9sixdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84bd6b9f94d9aab7761b509d19cf38b577a23cd/pkg/sql/exec/quicksort_tmpl.go#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we embed this `cancelChecker` in the sort struct as we do with the hash table? I suppose this is what the benchmark discussion was about. It seems suspicious to me as well.
</blockquote></details>

Yeah, the benchmarks on my Mac were off.

I embedded `cancelChecker` into sorter structs as well. I also run the benchmark to check whether there is any significant difference, and there doesn't appear to be any (ran on gce worker):
```
name                        old time/op   new time/op   delta
Sort/rows=2048/cols=1-24     38.1µs ±14%   36.7µs ± 2%    ~     (p=0.905 n=10+9)
Sort/rows=2048/cols=2-24      203µs ± 1%    203µs ± 1%    ~     (p=0.353 n=10+10)
Sort/rows=2048/cols=4-24      367µs ± 1%    369µs ± 1%    ~     (p=0.156 n=10+9)
Sort/rows=16384/cols=1-24     308µs ± 2%    312µs ± 1%  +1.49%  (p=0.015 n=10+10)
Sort/rows=16384/cols=2-24    1.63ms ± 2%   1.64ms ± 1%  +1.06%  (p=0.027 n=8+9)
Sort/rows=16384/cols=4-24    3.13ms ± 4%   3.10ms ± 2%    ~     (p=0.481 n=10+10)
Sort/rows=262144/cols=1-24   4.32ms ± 1%   4.54ms ±12%  +5.13%  (p=0.003 n=10+10)
Sort/rows=262144/cols=2-24   22.7ms ± 2%   22.7ms ± 1%    ~     (p=0.853 n=10+10)
Sort/rows=262144/cols=4-24   59.1ms ± 1%   59.3ms ± 2%    ~     (p=0.579 n=10+10)

name                        old speed     new speed     delta
Sort/rows=2048/cols=1-24    433MB/s ±13%  446MB/s ± 2%    ~     (p=0.905 n=10+9)
Sort/rows=2048/cols=2-24    161MB/s ± 1%  162MB/s ± 1%    ~     (p=0.353 n=10+10)
Sort/rows=2048/cols=4-24    178MB/s ± 1%  178MB/s ± 1%    ~     (p=0.163 n=10+9)
Sort/rows=16384/cols=1-24   426MB/s ± 2%  420MB/s ± 1%  -1.47%  (p=0.015 n=10+10)
Sort/rows=16384/cols=2-24   161MB/s ± 2%  160MB/s ± 1%  -1.05%  (p=0.026 n=8+9)
Sort/rows=16384/cols=4-24   168MB/s ± 4%  169MB/s ± 2%    ~     (p=0.481 n=10+10)
Sort/rows=262144/cols=1-24  485MB/s ± 1%  463MB/s ±11%  -4.55%  (p=0.003 n=10+10)
Sort/rows=262144/cols=2-24  185MB/s ± 2%  185MB/s ± 1%    ~     (p=0.838 n=10+10)
Sort/rows=262144/cols=4-24  142MB/s ± 1%  142MB/s ± 2%    ~     (p=0.565 n=10+10)
```


<!-- Sent from Reviewable.io -->

2019-04-23 15:08 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once alfonso's satisfied too

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-Ld9jV-K6oQZLmx7kbQ7:b-vcy6co)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-04-23 17:30 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> minus the ordering of the `ctx` arg.

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-LdAEjx8A8RbwOclaMQa:b-p058p3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto, @georgeutsin, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/quicksort_tmpl.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-LdAEWZi7hntbZdGNbLA:-LdAEWZi7hntbZdGNbLB:bb15wzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d9aee172fbea492832c490d8a5ad967f5665db2/pkg/sql/exec/quicksort_tmpl.go#L192)):*
> ```Go
> }
> 
> func (p *sort_TYPE_DIROp) quickSort(a, b, maxDepth int, ctx context.Context) {
> ```

nit: `ctx` is usually the first argument to a method.


<!-- Sent from Reviewable.io -->

2019-04-23 17:55 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @georgeutsin, and @solongordon)

___
*[pkg/sql/exec/quicksort_tmpl.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-LdAEWZi7hntbZdGNbLA:-LdAKLlMBl4gI_Cs7EEK:bgpx6p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d9aee172fbea492832c490d8a5ad967f5665db2/pkg/sql/exec/quicksort_tmpl.go#L192)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `ctx` is usually the first argument to a method.
</blockquote></details>

Done. I was debating whether it should be the first or the last in this case.


<!-- Sent from Reviewable.io -->

2019-04-23 19:44 UTC, yuzefovich reviewed
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36967#-:-LdAibrV841YziI19iXv:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @georgeutsin, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-04-23 20:38 UTC, merged