roachtest: add schemachange/bulkingest test
cockroachdb/cockroach pull request #36999
Opened 2019-04-22 19:28 UTC by lucy-zhang

Add a test to index the random `payload` column for the `bulkingest` workload,
to test the index backfiller for an index on randomly ordered values relative
to the primary key.

Release note: None

2019-04-22 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/36999)
<!-- Reviewable:end -->

2019-04-23 14:57 UTC, vivekmenezes requested changes
Thanks for putting this together. I think I'd prefer this test be in the schemachange.go file to keep with convention. Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-:-Ld9glUDAnbrzZUfxK-A:b-9vygi9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/cmd/roachtest/bulkingest.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9dtbo4ZoGKqRpM_JC:-Ld9dtbo4ZoGKqRpM_JD:b4t0dtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L36)):*
> ```Go
> 
> func runSchemaChangeBulkIngest(ctx context.Context, t *test, c *cluster) {
> 	aNum := 100000000
> ```

 Can you add a comment here discussing these parameters?
___
*[pkg/cmd/roachtest/bulkingest.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9epvN92SXeMNY1g8p:-Ld9epvN92SXeMNY1g8q:befqko5) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L81)):*
> ```Go
> 			pauseDuration = time.Second * 10
> 		}
> 		time.Sleep(pauseDuration)
> ```

what's this pause for? What about if you running locally? perhaps we should put all the parameters at the top and set them based on a size control param. That way someone can easily run this test with larger/smaller inputs based on the value of the size control param
___
*[pkg/cmd/roachtest/bulkingest.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9geqk3rozazll60id:-Ld9geqk3rozazll60ie:b-hs6qoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L88)):*
> ```Go
> 		}
> 		c.l.Printf("CREATE INDEX took %v\n", timeutil.Since(before))
> 		return nil
> ```

This test needs a timeout somewhere.


<!-- Sent from Reviewable.io -->

2019-04-24 20:24 UTC, thoszhang reviewed
Moved to schemachange.go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-:-LdG-UCN1uQYU4DJvTXx:b-ms7k78)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

___
*[pkg/cmd/roachtest/bulkingest.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9dtbo4ZoGKqRpM_JC:-LdFzqRfC8elz7EcY4gq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L36)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

 Can you add a comment here discussing these parameters?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/bulkingest.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9epvN92SXeMNY1g8p:-LdFzrAtCQyT5zu0u3u5:b51f1va) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L81)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

what's this pause for? What about if you running locally? perhaps we should put all the parameters at the top and set them based on a size control param. That way someone can easily run this test with larger/smaller inputs based on the value of the size control param
</blockquote></details>

It's just so that we wait a few minutes while the loadgen runs before building the index. I updated it so that it only sleeps for a non-local cluster and added a comment.

I moved all the interesting parameters to the function arguments (not including the sleep interval) to match the other tests, which I think is sufficient - it's hard to have a more general size control parameter since the number of nodes and the number of rows are independent of each other and have different effects on behavior.
___
*[pkg/cmd/roachtest/bulkingest.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36999#-Ld9geqk3rozazll60id:-LdG-Hsw9Q7m9h6yuvB9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87b422089a3f8465748c8c4629b826ca439ef2b2/pkg/cmd/roachtest/bulkingest.go#L88)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

This test needs a timeout somewhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-29 17:33 UTC, vivekmenezes approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36999)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)



<!-- Sent from Reviewable.io -->

2019-04-29 17:36 UTC, lucy-zhang commented
bors r+

2019-04-29 18:29 UTC, merged