server/heapprofiler: don't conside "goIdle" memory
cockroachdb/cockroach pull request #37412
Opened 2019-05-08 22:38 UTC by andreimatei

Base decisions about whether to take a heap profile or not on
RSS - goIdle, not RSS alone. goIdle is memory allocated from the OS
that's not actually in use. I've seen it be up to several gigs.
The rationale behind the patch is that we want profiles when the heap is
large more than when the RSS is large. I'm looking at a case where we
took a heap profile when the heap was 4.5 gigs with 2 gigs idle and then
never took one again because of how the heuristic works. And then we
OOMed when the heap was larger and the idle space was lower, but the RSS
was about the same. With this patch, we would have taken a profile at a
more interesting time.

Release note: None

2019-05-08 22:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/37412)
<!-- Reviewable:end -->

2019-05-09 10:04 UTC, tbg requested changes
This sounds reasonable, but I'd like to suck you into a little cleanup before this lands (I wrote most of the code in the comment below to make this easier to swallow - hope it works :smile:)

The RSS size and to Go stats are taken separately because apparently at some point we had problems with the duration of the call to retrieve the Go stats: https://github.com/cockroachdb/cockroach/blob/4850713b64e397ea2c1343e480365f111c8265b8/pkg/server/server.go#L1916-L1920

The result is kind of crappy. We get the RSS in one loop, and the Go stats in the other, so they could be, at worst, 10s out of sync (or more if these stalls still happen).

What I think we should do is the following:

1. unify the stats collection, i.e. move https://github.com/cockroachdb/cockroach/blob/034df0b3262452aae4fe57a735e1dfb12db26d82/pkg/server/status/runtime.go#L409 into `SampleEnvironment` and store both that and the Go stats in a `type MemStats struct { gosigar.ProcMem runtime.MemStats }` that has convenience functions to get "good numbers" out of it. Note that it makes sense to call gosigar last (i.e. after getting go mem stats), so that it's taken very soon after the Go stats computation returns.
2. try to sync up these loops somewhat. I'm thinking the following

```go
	// As of go1.12, runtime.ReadMemStats() "stops the world" and requires
	// waiting for any current GC run to finish. With a large heap, a single GC
	// run may take longer than the default sampling period (10s). The code below
	// is resilient to this sort of thing and will continue to run roughly at the
	// defined frequency, using the last stats that were in fact collected.
	s.stopper.RunWorker(ctx, func(ctx context.Context) {
		timer := timeutil.NewTimer()
		defer timer.Stop()
		timer.Reset(frequency)

		var memStats atomic.Value // *base.MemStats
		var collecting int32      // atomic, 1 when stats call is ongoing
		memStats.Store(&base.MemStats{})
		for {
			select {
			case <-timer.C:
				timer.Read = true
				timer.Reset(frequency)

				statsCollected := make(chan struct{})
				if atomic.CompareAndSwapInt64(&collecting, 0, 1) {
					if err := s.stopper.RunAsyncTask(ctx, "go-mem-stats", func(ctx context.Context) {
						curStats := s.runtime.SampleMemStats(ctx)
						memStats.Store(&curStats)
						close(statsCollected)
						atomic.StoreInt32(&collecting, 0)
					}); err != nil {
						close(statsCollected)
					}
				} else {
					close(statsCollected)
				}

				select {
				case <-time.After(time.Second):
					// Maybe log a warning, but continue to use the old stats in
					// this iteration.
				case <-statsCollected:
					// Common case, we have updated stats now.
				}

				curStats := memStats.Load().(*base.MemStats)
				s.runtime.SampleEnvironment(ctx, curStats)

				if goroutineDumper != nil {
					goroutineDumper.MaybeDump(ctx, s.ClusterSettings(), s.runtime.Goroutines.Value())
				}
				if heapProfiler != nil {
					heapProfiler.MaybeTakeProfile(ctx, s.ClusterSettings(), curStats)
				}
			case <-s.stopper.ShouldStop():
				return
			}
		}
	})
```

When we have that, we can think about what the meaningful thing for the heap profiler to look at is. I believe RSS is always somewhat inflated (at least on linux) due to the use of MADVISE. Also, the heap profiler never tells us anything about allocs on the non-Go side, so it doesn't make a whole lot of sense to use it for the heap profiler in the first place; the only thing that really matters is some combination of GoAllocated and GoIdle (but note that jemalloc can dump heap also, an extension which might make sense in the future but not if we switch to pebble).

`HeapIdle` has this comment:

```
// HeapIdle minus HeapReleased estimates the amount of memory

	// that could be returned to the OS, but is being retained by

	// the runtime so it can grow the heap without requesting more

	// memory from the OS. If this difference is significantly

	// larger than the heap size, it indicates there was a recent

	// transient spike in live heap size.

	HeapIdle uint64
```

I agree that it's better to limit to the non-idle Go memory as a trigger. Lots of idle memory tells us that something interesting happened frequently, but we missed it, but maybe we did actually catch it earlier.

1. remove `fractionSystemMemoryHeuristic`: we've established that we can't really reason about what a good threshold here is because we always expect sizeable chunks of memory on the C++ side
2. introduce a high watermark heuristic: dump every time we see a new max for non-idle go heap size (or perhaps every time we see more than 1.3x the previous max, or something like that). Heap dumps are fairly cheap because they just write out info that is collected during GC.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LeQuaoC29Y0bLKF45rw:beqxie4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/base/mem_stats.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LeQpnBm2Ky0_FhvGbr0:-LeQpnBm2Ky0_FhvGbr1:b977a4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0777ccaa32b78a68c5fc553867a40c9f43f39c5e/pkg/base/mem_stats.go#L17)):*
> ```Go
> package base
> 
> // MemStats represents information from the Go allocator.
> ```

This seems like sort of a random struct that's kind of useful, but not really useful, and also not aptly named. See the suggestion on the main thread.


<!-- Sent from Reviewable.io -->

2019-05-16 22:53 UTC, andreimatei commented
Please see now.

2019-05-17 14:22 UTC, tbg reviewed
> Reviewed 5 of 5 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, and @Nishant9)

___
*[pkg/base/mem_stats.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf55hmJDQEam8z3vDoN:-Lf55hmJDQEam8z3vDoO:b32val) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/base/mem_stats.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

19
___
*[pkg/server/server.go, line 1952 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59AbKCrJsTFF8meQb:-Lf59AbL58K-I1NPgFNQ:bit526k) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/server.go#L1952)):*
I'd clarify this to say

> With a large heap and under extreme conditions, a single GC run may take longer than the default sampling period of 10s. Under normal operations and with more recent versions of Go, this hasn't been observed to be a problem.
___
*[pkg/server/heapprofiler/heapprofiler.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58VZ59AJ_mmleXRuK:-Lf58VZ59AJ_mmleXRuL:bwytmo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler.go#L94)):*
> ```Go
> }
> 
> // fractionSystemMemoryHeuristic is true if latest (RSS - goIdle) is more than
> ```

Thinking about this more, it still strikes me as silly that we're comparing apples (RSS) to oranges (goIdle) here. How about we always take a profile if GoActualHeapBytes() is larger than the max seen thus far? We don't have to worry about the min profile interval since we've resolved that taking a heap profile is cheap and because the profiler is already triggered periodically at a low enough frequency (though if you feel that we should retain some protection here, that's fine by me too but I would lower it to 10s).
___
*[pkg/server/heapprofiler/heapprofiler_test.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59rn7Bw0aSXxJzyCG:-Lf59rn7Bw0aSXxJzyCH:b-ubjh7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler_test.go#L52)):*
> ```Go
> 		assert.Nil(t, err)
> 		if len(expectedScores) <= numProfiles {
> 			t.Fatalf("unexected profile: %d", numProfiles)
> ```

unexpected
___
*[pkg/server/status/runtime.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58O7IAp7pWmNzIw5U:-Lf58O7J0srQUPuqEko2:b15v54d) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L502)):*
> ```Go
> 		humanize.IBytes(mem.Resident), numGoroutine,
> 		humanize.IBytes(ms.GoAllocated), humanize.IBytes(ms.GoIdle), humanize.IBytes(ms.GoTotal),
> 		staleMsg,
> ```

Nice touch.
___
*[pkg/server/status/runtime.go, line 550 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59UnHEN-1uVPy05VA:-Lf59UnHEN-1uVPy05VB:bz3uh6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L550)):*
> ```Go
> 	goAllocated := ms.Alloc
> 	goTotal := ms.Sys - ms.HeapReleased
> 	rsr.GoAllocBytes.Update(int64(goAllocated))
> ```

Move this to `SampleEnvironment`, then remove this method completely (we just call `runtime.ReadMemStats` at the caller).
___
*[pkg/server/status/runtime.go, line 556 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf566lQ-bkEszSJFIbt:-Lf566lRC52GdVSCIwNZ:b-sg4bxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L556)):*
> ```Go
> 	return base.GoMemStats{
> 		GoAllocated: goAllocated,
> 		GoIdle:      ms.HeapIdle - ms.HeapReleased,
> ```

Please just use `runtime.MemStats` here (and use it in `base.MemStats`) and do all the math later with an accessor. That way it'll be much easier to navigate later.


<!-- Sent from Reviewable.io -->

2019-05-17 16:05 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/server/heapprofiler/heapprofiler.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58VZ59AJ_mmleXRuK:-Lf5WSer-siknhbXjdn5:byc3vye) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler.go#L94)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Thinking about this more, it still strikes me as silly that we're comparing apples (RSS) to oranges (goIdle) here. How about we always take a profile if GoActualHeapBytes() is larger than the max seen thus far? We don't have to worry about the min profile interval since we've resolved that taking a heap profile is cheap and because the profiler is already triggered periodically at a low enough frequency (though if you feel that we should retain some protection here, that's fine by me too but I would lower it to 10s).
</blockquote></details>

well I thought it's silly to take profiles when the memory usage is "low", regardless of whether we've reached a high-water mark or not. And we don't really know what the target for all the go memory is, since so much memory is taken by CGo. So I want something that says "if there's plenty of free memory on the system, don't take a profile".
And also I don't know about _only_ taking profiles on high-water marks... I think while memory is "high" it's better to take more profiles periodically.

So, I dunno... It'd still go with what I have here. And hopefully we'll switch to Pebble and then we can talk about just Go memory.


<!-- Sent from Reviewable.io -->

2019-05-20 13:04 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, and @Nishant9)

___
*[pkg/server/heapprofiler/heapprofiler.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58VZ59AJ_mmleXRuK:-LfKKRYb6Q_M9TF7KSFv:b1afqn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler.go#L94)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well I thought it's silly to take profiles when the memory usage is "low", regardless of whether we've reached a high-water mark or not. And we don't really know what the target for all the go memory is, since so much memory is taken by CGo. So I want something that says "if there's plenty of free memory on the system, don't take a profile".
And also I don't know about _only_ taking profiles on high-water marks... I think while memory is "high" it's better to take more profiles periodically.

So, I dunno... It'd still go with what I have here. And hopefully we'll switch to Pebble and then we can talk about just Go memory.
</blockquote></details>

You're right that the first couple of profiles won't be *useful*, but it's not silly because it eliminates needing to know what a "reasonable" threshold for Go memory usage is, which is what has been the real silliness in this code thus far. Trying to fix that is nontrivial and we don't have much to win by even trying. Even when there's no C++ involved I'd prefer the robustness of the simple approach (proposed above). I'll also add that I originally asked for these complications to be introduced, which I regret now. It would've saved us a number of eng hours to just take a heap profile whenever a new high watermark is reached.

I can take this change over if you'd rather spend your time somewhere else.


<!-- Sent from Reviewable.io -->

2019-05-20 21:58 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/server/heapprofiler/heapprofiler.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58VZ59AJ_mmleXRuK:-LfMEptqEvByzzi519n7:byu37nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler.go#L94)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You're right that the first couple of profiles won't be *useful*, but it's not silly because it eliminates needing to know what a "reasonable" threshold for Go memory usage is, which is what has been the real silliness in this code thus far. Trying to fix that is nontrivial and we don't have much to win by even trying. Even when there's no C++ involved I'd prefer the robustness of the simple approach (proposed above). I'll also add that I originally asked for these complications to be introduced, which I regret now. It would've saved us a number of eng hours to just take a heap profile whenever a new high watermark is reached.

I can take this change over if you'd rather spend your time somewhere else.
</blockquote></details>

ok, no more RSS. Highwater-mark + periodic reset.


<!-- Sent from Reviewable.io -->

2019-05-21 14:00 UTC, tbg reviewed
Did you see the other comments I had before your last push regarding to `GoMemStats`? I feel rather strongly that they're worth addressing. I just spent 15 minutes trying to figure out what numbers we actually use now, which I wouldn't have had to do with my suggestion addressed. (I also didn't manage to convince myself, so let's address the comment and then  I'll try again).

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LfPf5cW5qaXy1Euhy7_:bp4pj90)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/base/mem_stats.go, line 21 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPbWQu4Gvhqj6WqF2x:-LfPbWQu4Gvhqj6WqF2y:b-p5o9lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/base/mem_stats.go#L21)):*
> ```Go
> // GoMemStats represents information from the Go allocator.
> // All units are bytes.
> type GoMemStats struct {
> ```

I hate to bring this up again, but I find it hard to justify this over just embedding a `runtime.MemStats` in `base.MemStats`. What's the thinking there? Things have names that don't match `runtime.MemStats` too which adds extra friction. I really think this just ought to be `runtime.MemStats` so that I can just navigate to the explanation from the stdlib instead of trusting that the numbers get propagated to the right fields and that the names match my expectations.

Since you're also holding on to `Collected` you'll probably want

```go
type GoMemStats struct {
  runtime.MemStats
  Collected time.Time
}
```

with an accessor `NotIdle()` which boils down to whatever the final formula for it is (I tried piecing it together from this PR, but it's really not that straightforward and I also wasn't super confident that the result was the right thing, but let's discuss that when it's written down in one place here).
___
*[pkg/server/server.go, line 1952 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59AbKCrJsTFF8meQb:-LfPc1xaCm31g7bdfqb1:bb726fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/server.go#L1952)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'd clarify this to say

> With a large heap and under extreme conditions, a single GC run may take longer than the default sampling period of 10s. Under normal operations and with more recent versions of Go, this hasn't been observed to be a problem.
</blockquote></details>

Ping
___
*[pkg/server/server.go, line 1947 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPcARBEVi3K7WQTGK1:-LfPcARBEVi3K7WQTGK2:bbpsy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/server.go#L1947)):*
> ```Go
> 				statsCollected := make(chan struct{})
> 				if atomic.CompareAndSwapInt32(&collectingMemStats, 0, 1) {
> 					if err := s.stopper.RunTask(ctx, "mem-stats-sample", func(ctx context.Context) {
> ```

`RunAsyncTask` or the whole dance is useless :-)
___
*[pkg/server/heapprofiler/heapprofiler.go, line 47 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPcQKWBJHBXOn8SWOu:-LfPcQKWBJHBXOn8SWOv:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/heapprofiler/heapprofiler.go#L47)):*
> ```Go
> )
> 
> type stats struct {
> ```

?
___
*[pkg/server/heapprofiler/heapprofiler.go, line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPclWo0GjuEveDclgm:-LfPclWo0GjuEveDclgn:b-j9ofv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/heapprofiler/heapprofiler.go#L101)):*
> ```Go
> 	}
> 
> 	curMemUse := memStats.Go.GoTotal - memStats.Go.GoIdle
> ```

Put this in a method on `memStats.Go`, for example `memStats.Go.HeapNotIdle()`. You
___
*[pkg/server/status/runtime.go, line 550 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59UnHEN-1uVPy05VA:-LfPeYMA5uBP93olYw5R:bb726fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L550)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Move this to `SampleEnvironment`, then remove this method completely (we just call `runtime.ReadMemStats` at the caller).
</blockquote></details>

Ping


<!-- Sent from Reviewable.io -->

2019-05-21 20:36 UTC, andreimatei reviewed
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LfR61wADPWN5-HQtHAD:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/base/mem_stats.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf55hmJDQEam8z3vDoN:-LfPyeX00jPCtOqobc6S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/base/mem_stats.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

19
</blockquote></details>

Done.
___
*[pkg/base/mem_stats.go, line 21 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPbWQu4Gvhqj6WqF2x:-LfR2HhZByZqWfb1hdtX:bm938yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/base/mem_stats.go#L21)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I hate to bring this up again, but I find it hard to justify this over just embedding a `runtime.MemStats` in `base.MemStats`. What's the thinking there? Things have names that don't match `runtime.MemStats` too which adds extra friction. I really think this just ought to be `runtime.MemStats` so that I can just navigate to the explanation from the stdlib instead of trusting that the numbers get propagated to the right fields and that the names match my expectations.

Since you're also holding on to `Collected` you'll probably want

```go
type GoMemStats struct {
  runtime.MemStats
  Collected time.Time
}
```

with an accessor `NotIdle()` which boils down to whatever the final formula for it is (I tried piecing it together from this PR, but it's really not that straightforward and I also wasn't super confident that the result was the right thing, but let's discuss that when it's written down in one place here).
</blockquote></details>

ok, see now
___
*[pkg/server/server.go, line 1952 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59AbKCrJsTFF8meQb:-LfR2fyw4Hbh0XmpF3ev:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/server.go#L1952)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ping
</blockquote></details>

done
___
*[pkg/server/server.go, line 1947 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPcARBEVi3K7WQTGK1:-LfR2QL241xUCCVQyc6r:b-pb9bue) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/server.go#L1947)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`RunAsyncTask` or the whole dance is useless :-)
</blockquote></details>

indeed
___
*[pkg/server/heapprofiler/heapprofiler.go, line 47 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPcQKWBJHBXOn8SWOu:-LfR2jwJ4dZZwW65cl8t:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/heapprofiler/heapprofiler.go#L47)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

?
</blockquote></details>

removed
___
*[pkg/server/heapprofiler/heapprofiler.go, line 101 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfPclWo0GjuEveDclgm:-LfR31iK8idNGEopCGI6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9093c63a002538a98b7af87d3f5b6f3c075fcc61/pkg/server/heapprofiler/heapprofiler.go#L101)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Put this in a method on `memStats.Go`, for example `memStats.Go.HeapNotIdle()`. You
</blockquote></details>

Done.
___
*[pkg/server/heapprofiler/heapprofiler_test.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59rn7Bw0aSXxJzyCG:-LfR2smx8Pe0cq8VW_cK:b2ni76j) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/heapprofiler/heapprofiler_test.go#L52)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

unexpected
</blockquote></details>

n/a
___
*[pkg/server/status/runtime.go, line 502 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf58O7IAp7pWmNzIw5U:-LfR2tlf52YBHDr5k50w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L502)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Nice touch.
</blockquote></details>

Done.
___
*[pkg/server/status/runtime.go, line 550 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf59UnHEN-1uVPy05VA:-LfR4RWL5z2_paOzC9eT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L550)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ping
</blockquote></details>

done
___
*[pkg/server/status/runtime.go, line 556 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-Lf566lQ-bkEszSJFIbt:-LfR385lANwteLOROfHl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/841a2ffe0f3ca8b40de17bb50aaf85ce6fdd16a1/pkg/server/status/runtime.go#L556)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Please just use `runtime.MemStats` here (and use it in `base.MemStats`) and do all the math later with an accessor. That way it'll be much easier to navigate later.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-22 10:14 UTC, tbg reviewed
Thanks for sticking it out! Please add release note about the removed cluster setting. One more substantial comment that's easy to address, one nit, and then we're good to go :pray: 

> Reviewed 2 of 7 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LfU-MWbCXeGe0OLzppC:b-xqciw6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/base/mem_stats.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU-T-vEC_1M1TyeB-R:-LfU-T-vEC_1M1TyeB-S:bxxe9wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/base/mem_stats.go#L25)):*
> ```Go
> // All units are bytes.
> type GoMemStats struct {
> 	// MemStats is a pointer because it's a large struct. We want GoMemStats to be
> ```

This isn't anywhere close to any hot path and never will be, so this looks like premature optimization. Even if we cared, wouldn't you just embed the value anyway and deal in `*GoMemStats` elsewhere? You can `runtime.ReadMemStats(&goMemStats.MemStats)`.
___
*[pkg/base/mem_stats.go, line 43 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfTxp3v5qC2qmXQpnMH:-LfTxp3v5qC2qmXQpnMI:b-vvrt82) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/base/mem_stats.go#L43)):*
> ```Go
> // is counted as "in use" by this method.
> func (ms *GoMemStats) GoInUse() uint64 {
> 	// NOTE(andrei): It may seem weird that we're only subtracting HeapReleased
> ```

I think we're quite likely to shoot ourselves in the foot here in some way. `HeapReleased` is a counter (i.e. only ever goes up, or am I reading that wrong?) but `Sys` isn't. And even if they're actually comparable quantities, I don't think we can win anything here by trying to account for "as much Go memory as we can" here because the profile will show only the heap, and because the heuristic isn't properly exercised at scale (i.e. there's no test that puts a cluster under heap pressure at scale and verifies that we get sensible profile scores over extended periods of time and I don't think we're planning to write one). Let's use `HeapAlloc` which is certifiably the thing we care about (and it shouldn't include `HeapIdle` which was the original motivation for this PR):

```go
        // HeapAlloc is bytes of allocated heap objects.
        //
        // "Allocated" heap objects include all reachable objects, as
        // well as unreachable objects that the garbage collector has
        // not yet freed. Specifically, HeapAlloc increases as heap
        // objects are allocated and decreases as the heap is swept
        // and unreachable objects are freed. Sweeping occurs
        // incrementally between GC cycles, so these two processes
        // occur simultaneously, and as a result HeapAlloc tends to
        // change smoothly (in contrast with the sawtooth that is
        // typical of stop-the-world garbage collectors).
        HeapAlloc uint64
```

There's a chance that we'll sometimes see crashes in which the heap remains bounded but some other Go memory (stacks when goroutine leaking perhaps?) explodes, but these are rarer and I expect them to show other signs that we can interpret. Either way, a heap profile in that case wouldn't show us much except that the heap wasn't huge. This information is better conveyed by logging the heap size in the runtime stats, which we do already: https://github.com/cockroachdb/cockroach/blob/034df0b3262452aae4fe57a735e1dfb12db26d82/pkg/server/status/runtime.go#L552
___
*[pkg/server/server.go, line 1968 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfTzoWt2qjZ665wRVwJ:-LfTzoWu3XNsNWSjOWmu:b8by24x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/server.go#L1968)):*
> ```Go
> 					// Good; we managed to read the Go memory stats quickly enough.
> 				case <-time.After(time.Second):
> 					log.Infof(ctx, "get-mem-stats hasn't finished in one second; "+
> ```

Now that I'm looking at this, is this logging necessary? The runtime stats will print `(stale)`, right? Your call.
___
*[pkg/server/heapprofiler/heapprofiler.go, line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU0QWoC6d0sYQ0WIF7:-LfU0QWoC6d0sYQ0WIF8:bqv1e9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/heapprofiler/heapprofiler.go#L56)):*
> ```Go
> //
> // MaybeTakeProfile() is supposed to be called periodically. A profile is taken
> // every time the current Go memory usage is the high-water mark. The recorded
> ```

s/memory/heap/ (in accordance with my comment about HeapAlloc)
___
*[pkg/server/status/runtime.go, line 389 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU0w3Y2_0VEdEWrpV8:-LfU0w3Y2_0VEdEWrpV9:b-rlqc8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/status/runtime.go#L389)):*
> ```Go
> // to keep runtime statistics current.
> //
> // SampleEnvironment takes GoMemStats as input because that it collected
> ```

s/it/is/


<!-- Sent from Reviewable.io -->

2019-05-22 18:11 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/base/mem_stats.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU-T-vEC_1M1TyeB-R:-LfVH15Y4SiI8Q3MMrzk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/base/mem_stats.go#L25)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This isn't anywhere close to any hot path and never will be, so this looks like premature optimization. Even if we cared, wouldn't you just embed the value anyway and deal in `*GoMemStats` elsewhere? You can `runtime.ReadMemStats(&goMemStats.MemStats)`.
</blockquote></details>

Done.
___
*[pkg/base/mem_stats.go, line 43 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfTxp3v5qC2qmXQpnMH:-LfVHN5F40k3-gKwLN02:b-hcgn3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/base/mem_stats.go#L43)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think we're quite likely to shoot ourselves in the foot here in some way. `HeapReleased` is a counter (i.e. only ever goes up, or am I reading that wrong?) but `Sys` isn't. And even if they're actually comparable quantities, I don't think we can win anything here by trying to account for "as much Go memory as we can" here because the profile will show only the heap, and because the heuristic isn't properly exercised at scale (i.e. there's no test that puts a cluster under heap pressure at scale and verifies that we get sensible profile scores over extended periods of time and I don't think we're planning to write one). Let's use `HeapAlloc` which is certifiably the thing we care about (and it shouldn't include `HeapIdle` which was the original motivation for this PR):

```go
        // HeapAlloc is bytes of allocated heap objects.
        //
        // "Allocated" heap objects include all reachable objects, as
        // well as unreachable objects that the garbage collector has
        // not yet freed. Specifically, HeapAlloc increases as heap
        // objects are allocated and decreases as the heap is swept
        // and unreachable objects are freed. Sweeping occurs
        // incrementally between GC cycles, so these two processes
        // occur simultaneously, and as a result HeapAlloc tends to
        // change smoothly (in contrast with the sawtooth that is
        // typical of stop-the-world garbage collectors).
        HeapAlloc uint64
```

There's a chance that we'll sometimes see crashes in which the heap remains bounded but some other Go memory (stacks when goroutine leaking perhaps?) explodes, but these are rarer and I expect them to show other signs that we can interpret. Either way, a heap profile in that case wouldn't show us much except that the heap wasn't huge. This information is better conveyed by logging the heap size in the runtime stats, which we do already: https://github.com/cockroachdb/cockroach/blob/034df0b3262452aae4fe57a735e1dfb12db26d82/pkg/server/status/runtime.go#L552
</blockquote></details>

`Sys` is also a counter. That's spelled out in `HeapSys` for example, which is one of its constituents, that says `as well as virtual	address space for which the physical memory has been	returned to the OS after it became unused`.

The reason why I had written what I wrote was because I thought that the stacks are actually reflected somehow in the profile - I kinda remember seeing something about allocating stacks, but maybe I'm thinking of CPU profiles not memory profiles. In any case, I went with `HeapAlloc`.
___
*[pkg/server/server.go, line 1968 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfTzoWt2qjZ665wRVwJ:-LfVZHJa2aJQrssbK59v:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/server.go#L1968)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Now that I'm looking at this, is this logging necessary? The runtime stats will print `(stale)`, right? Your call.
</blockquote></details>

removed
___
*[pkg/server/heapprofiler/heapprofiler.go, line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU0QWoC6d0sYQ0WIF7:-LfVbB_l2cdtOqZxZiW0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/heapprofiler/heapprofiler.go#L56)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/memory/heap/ (in accordance with my comment about HeapAlloc)
</blockquote></details>

Done.
___
*[pkg/server/status/runtime.go, line 389 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfU0w3Y2_0VEdEWrpV8:-LfVbLuC4NGCLwo-pOEc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d13fee87aa976be6fa0c977c0c2171b154bd8ada/pkg/server/status/runtime.go#L389)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/it/is/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-23 04:05 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> CI complains, I think it's because various tests now create errant profiles and we check for stray files at the end. Probably have to avoid writing profiles if the profiler is set up with an empty dir.

> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LfXrH1N2wM_XX_9dsq0:b-22g5xm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @lucy-zhang, and @Nishant9)

___
*[pkg/server/heapprofiler/heapprofiler.go, line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfXqjL44J3n7cqyQR5v:-LfXqjL44J3n7cqyQR5w:b7tn9qw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6355b48f2556206b467c8eaf669f6107d9eba180/pkg/server/heapprofiler/heapprofiler.go#L56)):*
> Go heap allocated bytes exceeds the previous
___
*[pkg/server/heapprofiler/heapprofiler_test.go, line 38 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfXr0XkCgbji6z2RG_T:-LfXr0XkCgbji6z2RG_U:b-iz3zu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6355b48f2556206b467c8eaf669f6107d9eba180/pkg/server/heapprofiler/heapprofiler_test.go#L38)):*
> ```Go
> 		{0, 30, true},    // we always take the first profile
> 		{10, 40, true},   // new high-water mark
> 		{20, 30, false},  // below high-water mark; no profile
> ```

Add a few here to test GC? Or is there a dedicated test elsewhere?


<!-- Sent from Reviewable.io -->

2019-05-28 20:58 UTC, andreimatei reviewed
indeed. Now the profiler is disabled in unit tests. Curious if I need to disable in... any other tests. We'll see.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-Lg-E4DZ5F_66gkRbRkz:bwbwvt7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)

___
*[pkg/server/heapprofiler/heapprofiler.go, line 56 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfXqjL44J3n7cqyQR5v:-Lg-8Nei1uyG48oZ3oQa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6355b48f2556206b467c8eaf669f6107d9eba180/pkg/server/heapprofiler/heapprofiler.go#L56)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> Go heap allocated bytes exceeds the previous
</blockquote></details>

Done.
___
*[pkg/server/heapprofiler/heapprofiler_test.go, line 38 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-LfXr0XkCgbji6z2RG_T:-Lg-8aAtCF0LcEf9S8nH:b-yijsrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6355b48f2556206b467c8eaf669f6107d9eba180/pkg/server/heapprofiler/heapprofiler_test.go#L38)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Add a few here to test GC? Or is there a dedicated test elsewhere?
</blockquote></details>

well testing GC would need some more mocking. The profiler used in this test is configured to not actually write any files.
I'll leave it...


<!-- Sent from Reviewable.io -->

2019-05-29 11:04 UTC, tbg approved these changes
> Reviewed 6 of 6 files at r9, 8 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @Nishant9)



<!-- Sent from Reviewable.io -->

2019-05-30 20:41 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-Lg9TOoTB2_aHe6XmSyf:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)



<!-- Sent from Reviewable.io -->

2019-05-31 02:55 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LgAo5HF1poyRhcCSRzo:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)



<!-- Sent from Reviewable.io -->

2019-05-31 09:57 UTC, tbg commented
bors pls
bors r+

2019-05-31 17:51 UTC, andreimatei reviewed
borsy boy
bors r+ 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LgE07MsEt_4VtEDm_TP:b-air4z7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)



<!-- Sent from Reviewable.io -->

2019-06-03 17:22 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37412#-:-LgTMLocA9Stt1G6D-V2:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @Nishant9, and @tbg)



<!-- Sent from Reviewable.io -->

2019-06-03 17:55 UTC, merged