exec: implement top K sorter
cockroachdb/cockroach pull request #38009
Opened 2019-06-04 17:34 UTC by solongordon

I added a new sorter implementation for top K sorting. This can be used
when there is a limit on the sort and no post-process filters. The
implementation uses a heap to track the top K rows as data is streamed
in. Unfortunately it's slower than our existing sort implementation
unless K is significantly smaller than the input size. However, this
isn't really an apples-to-apples comparison because the top K
implementation handles nulls and the vanilla sorter does not.

Fixes #33589

Release note: None

2019-06-04 17:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38009)
<!-- Reviewable:end -->

2019-06-04 17:36 UTC, solongordon commented
This could use some more unit tests since right now it only has a randomized test. (In particular null handling isn't tested.) But otherwise it's ready for review.

2019-06-04 19:27 UTC, yuzefovich requested changes
Nice work! A few comments from me. Also, it might be interesting to see how the benchmarks look with a variable value of K.

Does the null handling comes "for free" due to usage of `vecComparator`s?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-:-LgYwzNx2CpYOFgR8nTY:b-5k3v0e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgY_I2k6O0piVvvDwnZ:-LgY_I2k6O0piVvvDwn_:b-5nehk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/distsqlrun/column_exec_setup.go#L387)):*
> ```Go
> 		if matchLen > 0 {
> 			op, err = exec.NewSortChunks(input, inputTypes, orderingCols, int(matchLen))
> 		} else if post.Limit != 0 && post.Filter.Empty() && post.Limit+post.Offset < math.MaxUint16 {
> ```

A comment explaining the choice of using the second and third parts of the conditional would be helpful. My guess is that filters can be supported? If so, a TODO would be nice.
___
*[pkg/sql/exec/sort_test.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYwVLY0BFkEaek-2ax:-LgYwVLZ1s0WbLr-gpNo:bm9qisl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sort_test.go#L173)):*
> ```Go
> 						var sorter Operator
> 						if topK {
> 							sorter = &topKSorter{
> ```

[nit]: could use `NewTopKSorter` here.
___
*[pkg/sql/exec/sort_test.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYwdf8DJkB_TrxalKe:-LgYwdf8DJkB_TrxalKf:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sort_test.go#L303)):*
> ```Go
> 						var resultBatches int
> 						if topK {
> 							sorter = &topKSorter{
> ```

ditto
___
*[pkg/sql/exec/sorttopk.go, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYa66D4wIdJR2O4spO:-LgYa66D4wIdJR2O4spP:bt1migw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L3)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> //
> // Licensed under the Apache License, Version 2.0 (the "License");
> ```

[nit]: probably it's worth putting BSL here already.
___
*[pkg/sql/exec/sorttopk.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYtZhFA2rDVF-qFuAR:-LgYtZhFA2rDVF-qFuAS:b-tjpdma) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L87)):*
> ```Go
> 		o.comparators[i] = GetVecComparator(typ, 2)
> 	}
> 	o.updateComparators(topKVecIdx, o.topK)
> ```

[nit]: I'm not sure, but this seems unnecessary to me since comparators are updated in `spool`.
___
*[pkg/sql/exec/sorttopk.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYscqIDOTGOyEhmfqJ:-LgYscqIDOTGOyEhmfqK:b1lxcqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L108)):*
> ```Go
> //
> // After all the input has been read, we pop everything off the heap to
> // determine the final output ordering. This is used in emit to output the rows
> ```

[super nit]: I was a little confused by "emit" here, maybe `o.emit()` or `emit()` to make it explicit that it's a function name.
___
*[pkg/sql/exec/sorttopk.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYu4W_Bdd9l2r0p5uM:-LgYu4W_Bdd9l2r0p5uN:btcbayn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L157)):*
> ```Go
> 			idx := i
> 			if inputBatch.Selection() != nil {
> 				idx = inputBatch.Selection()[i]
> ```

[nit]: we can save a function call here if we put `sel := inputBatch.Selection()` before the for loop.
___
*[pkg/sql/exec/sorttopk.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYvBvvDM4WpVzzRf3-:-LgYvBvvDM4WpVzzRf30:bd0fgv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L190)):*
> ```Go
> 	if toEmit == 0 {
> 		// We're done.
> 		return coldata.NewMemBatchWithSize(o.inputTypes, 0)
> ```

We can reuse the output batch here as well (the comment below).
___
*[pkg/sql/exec/sorttopk.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYsG0SBvxaVylpB5Ic:-LgYsG0SBvxaVylpB5Id:b-mf7451) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L195)):*
> ```Go
> 		toEmit = coldata.BatchSize
> 	}
> 	output := coldata.NewMemBatchWithSize(o.inputTypes, int(toEmit))
> ```

I think we can reuse the underlying batch here, and it should speed things up, at least a little.
___
*[pkg/sql/exec/sorttopk.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYbroS9QVDa6tzRG5I:-LgYbroS9QVDa6tzRG5J:bunlb2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L205)):*
> ```Go
> }
> 
> func (o *topKSorter) compareRow(vecIdx1, vecIdx2 int, rowIdx1, rowIdx2 uint16) int {
> ```

This row comparison is probably where the slowness is coming from. I remember when I was thinking about top k sort a few months ago, I came up with a complicated algorithm that wasn't doing row-to-row comparison and was processing one column at a time, and I thought it was pretty hard to get right (also, in some edge cases the logic I had in mind could keep all the input tuples even when K was significantly smaller than the input size). This way is definitely simpler though, and if it gives performance benefits against general sorter, that's great.
___
*[pkg/sql/exec/sorttopk.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYb_VQ3UCyM2w4kSUV:-LgYb_VQ3UCyM2w4kSUW:bbwlqp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L214)):*
> ```Go
> 				return res
> 			case distsqlpb.Ordering_Column_DESC:
> 				return res * -1
> ```

[super nit]: maybe `-res`.
___
*[pkg/sql/exec/sorttopk.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYb3qQ5UOURDok9gDL:-LgYb3qQ5UOURDok9gDM:b-ysxfbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L225)):*
> ```Go
> func (o *topKSorter) updateComparators(vecIdx int, batch coldata.Batch) {
> 	for i := range o.orderingCols {
> 		o.comparators[i].setVec(vecIdx, batch.ColVecs()[o.orderingCols[i].ColIdx])
> ```

[super nit]: I'd use `batch.ColVec(o.orderingCols[i].ColIdx)`


<!-- Sent from Reviewable.io -->

2019-06-05 14:35 UTC, solongordon reviewed
Thanks for the review! I think you could use some nit recalibration. In my opinion your [nit]s should be regular comments and your [super nits] should be [nit]s. :)

Yeah, null handling should come from the use of `vecComparators` and the `Vec` methods for appending/copying. Still need to validate that though.

I'll see if I can get some variable K benchmarks in there without causing a combinatorial explosion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-:-Lgc0q9U8Itep9nqZRcW:b-watpss)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgY_I2k6O0piVvvDwnZ:-Lgbs1yf31G7Xc2o-W19:b2qvg7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/distsqlrun/column_exec_setup.go#L387)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

A comment explaining the choice of using the second and third parts of the conditional would be helpful. My guess is that filters can be supported? If so, a TODO would be nice.
</blockquote></details>

Done. If there is a filter we can't use top K sort because we don't know how many rows we'll need to output.
___
*[pkg/sql/exec/sort_test.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYwVLY0BFkEaek-2ax:-LgbudlJ4OVVswdN53nk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sort_test.go#L173)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: could use `NewTopKSorter` here.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sort_test.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYwdf8DJkB_TrxalKe:-LgbueDgE1a6kFMt8Rq1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sort_test.go#L303)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYa66D4wIdJR2O4spO:-Lgbuf5O6DZBdWjN8SKR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L3)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: probably it's worth putting BSL here already.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYtZhFA2rDVF-qFuAR:-LgburWs-YMBhIx8SNq-:b-3ti32x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L87)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'm not sure, but this seems unnecessary to me since comparators are updated in `spool`.
</blockquote></details>

Good catch, I don't know what this was doing here. Done.
___
*[pkg/sql/exec/sorttopk.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYscqIDOTGOyEhmfqJ:-LgbuxUSATB9eZf9Q07Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L108)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: I was a little confused by "emit" here, maybe `o.emit()` or `emit()` to make it explicit that it's a function name.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYu4W_Bdd9l2r0p5uM:-Lgbv970CIvXoKabp-AP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L157)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: we can save a function call here if we put `sel := inputBatch.Selection()` before the for loop.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYvBvvDM4WpVzzRf3-:-LgbwIME3vAuqMTedBKn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L190)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We can reuse the output batch here as well (the comment below).
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYsG0SBvxaVylpB5Ic:-LgbwImT0tnPWDpllApW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L195)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we can reuse the underlying batch here, and it should speed things up, at least a little.
</blockquote></details>

Done.
___
*[pkg/sql/exec/sorttopk.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYbroS9QVDa6tzRG5I:-LgbwNrx3sGEtMdz42Cc:b-gx9y8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L205)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This row comparison is probably where the slowness is coming from. I remember when I was thinking about top k sort a few months ago, I came up with a complicated algorithm that wasn't doing row-to-row comparison and was processing one column at a time, and I thought it was pretty hard to get right (also, in some edge cases the logic I had in mind could keep all the input tuples even when K was significantly smaller than the input size). This way is definitely simpler though, and if it gives performance benefits against general sorter, that's great.
</blockquote></details>

Yeah, this is certainly where most of the CPU goes. Interested to hear about your algorithm! 
___
*[pkg/sql/exec/sorttopk.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYb_VQ3UCyM2w4kSUV:-Lgc02zF4zYqwA9eEA8F:b-pyz1he) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L214)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: maybe `-res`.
</blockquote></details>

Done. TIL
___
*[pkg/sql/exec/sorttopk.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYb3qQ5UOURDok9gDL:-Lgc0cLr9-c9F8J0uDm1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L225)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: I'd use `batch.ColVec(o.orderingCols[i].ColIdx)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-05 15:30 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (as long as Yahor is satisfied).

Is the heap Fix operation expensive? If it is, we could use the same approach we did for sort and make an integer-specific version that doesn't need to do any interface lookups. But I expect the worst part is probably the comparison, like Yahor said, and not the heap Fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-:-LgcFeYh-oHXTSUe3-tO:b-xnrh4d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/sorttopk.go, line 115 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgcEShX7NCKiu6OJN2x:-LgcEShY0WjNHR5_FmqG:bcskk8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a995386dff932dbcb25e4b3ba7c2c8c276ef1139/pkg/sql/exec/sorttopk.go#L115)):*
> ```Go
> 	spooledRows := uint16(0)
> 	remainingRows := o.k
> 	for remainingRows > 0 && inputBatch.Length() > 0 {
> ```

This loop is a nice and useful algorithm: "copy `n` rows from the input efficiently, regardless of batch sizes". I think you could consider moving it into a function for reuse. I'm somewhat surprised we don't already have this loop sitting around somewhere.


<!-- Sent from Reviewable.io -->

2019-06-05 15:52 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> as well.

Curiosity about different values of K comes from thinking that we might want to tweak when we're using top k sort versus general since the benchmarks show that in certain cases the general sort wins. I don't think it's important to do it right now though.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-:-LgcKLGL1hXgdWnBqOy7:beqmo07)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgY_I2k6O0piVvvDwnZ:-LgcHrd07VsiNWt2x_nN:b-p87v0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/distsqlrun/column_exec_setup.go#L387)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Done. If there is a filter we can't use top K sort because we don't know how many rows we'll need to output.
</blockquote></details>

That makes sense, thanks.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgcHwvX3MF0YOPQ64Ng:-LgcHwvX3MF0YOPQ64Nh:b-fdwoeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a995386dff932dbcb25e4b3ba7c2c8c276ef1139/pkg/sql/distsqlrun/column_exec_setup.go#L395)):*
> ```Go
> 			op = exec.NewTopKSorter(input, inputTypes, orderingCols, k)
> 		} else {
> 			// No optimations possible. Default to the standard sort operator.
> ```

"optimizations."
___
*[pkg/sql/exec/sorttopk.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYvBvvDM4WpVzzRf3-:-LgcIh_F6FfbRxRaD08T:b-lsv0o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L190)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed this one (we can do `o.output.SetLength(0)` and then return `o.output`).
___
*[pkg/sql/exec/sorttopk.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38009#-LgYbroS9QVDa6tzRG5I:-LgcJW5L8N7Bsr-XD4za:bozbcyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a2a4b35ca2a7e7afadc93775e5e05b1243139c5/pkg/sql/exec/sorttopk.go#L205)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yeah, this is certainly where most of the CPU goes. Interested to hear about your algorithm! 
</blockquote></details>

The main idea of that algorithm was to read the input one column at a time maintaining a heap of at least K "candidate" tuples at all times. "At least" because if some tuples are equal on one column, we don't know which one to keep before we take a look at the next columns, so we keep all of them, and once we look at the following columns, we discard some. It probably doesn't make sense, so we should do some whiteboarding.


<!-- Sent from Reviewable.io -->

2019-06-06 20:08 UTC, solongordon commented
bors r+

2019-06-06 20:45 UTC, merged