[WIP] sql: add UNSPLIT ALL
cockroachdb/cockroach pull request #38023
Opened 2019-06-04 23:10 UTC by jeffrey-xiao

WIP

This PR adds `ALTER TABLE .. UNSPLIT ALL` which can be used for unsplitting all ranges in DROP, TRUNCATE, and IMPORT.

Just wanted to get some feedback on this current approach. It is a bit hacky so please let me know if there are better approaches. cc @jordanlewis

2019-06-04 23:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38023)
<!-- Reviewable:end -->

2019-06-05 13:58 UTC, ajwerner requested changes
All in all could be uglier. I'm curious to see how SQL folks feel about this approach. 

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-Lgbvk6xDyAbrNDJTgeA:b1ifr05)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/sql/planner.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgbuOfe1bv3Ps9BmVvF:-LgbuOff2AS0I1nFfxn-:b-hm0lm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc314380da60c467b0e17bf33a37b4534d3a3215/pkg/sql/planner.go#L1)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> ```

rebase?
___
*[pkg/sql/unsplit.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgbudoxDA9mF6cmxvnz:-LgbudoxDA9mF6cmxvo-:bpcubl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc314380da60c467b0e17bf33a37b4534d3a3215/pkg/sql/unsplit.go#L71)):*
> ```Go
> 			 WHERE table_name='%s'
> 			   AND index_name='%s'
> 				 AND manual_split_time IS NOT NULL
> ```

nit: weird spacing. Also, can't you use placeholders and pass the args to Query as opposed to the Sprintf?

```
ranges, err := p.ExtendedEvalContext().InternalExecutor.Query(ctx, 
`SELECT
    start_key
FROM
    crdb_internal.ranges
WHERE
    table_name = $1 AND index_name = $2;`, 
 p.txn, statement, n.TableOrIndex.Table.String(), n.TableOrIndex.Index)
```


<!-- Sent from Reviewable.io -->

2019-06-05 14:25 UTC, jeffrey-xiao reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/planner.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgbuOfe1bv3Ps9BmVvF:-Lgc0wFe7SEuWg_wrxg5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc314380da60c467b0e17bf33a37b4534d3a3215/pkg/sql/planner.go#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

rebase?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-05 19:58 UTC, jordanlewis reviewed
The approach doesn't seem particularly hacky. What were you concerned about?

I left some comments about comments. Overall, I think you need some more of them, but overall this LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-LgdCyfR7hp6GnzbSDuX:b-8wa76b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)

___
*[pkg/sql/unsplit.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcYqJ-9JcnCiZBloGM:-LgcYqJ-9JcnCiZBloGN:bxhxoky) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L34)):*
> ```Go
> 	index     *sqlbase.IndexDescriptor
> 	rows      planNode
> 	raw       bool
> ```

This `raw` boolean needs a comment, please. A future code reader probably won't be able to understand what it means without reading and understanding all of the usages of it otherwise!
___
*[pkg/sql/unsplit.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcZ3_K6nptgeHnqqYm:-LgcZ3_K6nptgeHnqqYn:b3bines) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L47)):*
> ```Go
> 	ret := &unsplitNode{
> 		tableDesc: tableDesc.TableDesc(),
> 		index:     index,
> ```

You could put `raw:  n.All` in this declaration if you wanted.

So does `raw` just mean `all`? What do you think about renaming it to `unsplitAll` instead?
___
*[pkg/sql/unsplit.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcZf-K7zaUn286JYrn:-LgcZf-K7zaUn286JYro:b2nobhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L151)):*
> ```Go
> 	var err error
> 	if n.raw {
> 		rowKey = []byte(*row[0].(*tree.DBytes))
> ```

What's going on here exactly? I guess the idea is that depending on what mode we're in, the row container stores a slightly different thing? You should comment this, please!

Oh, I see now what `raw` is about - it's describing that the values inside the row container are "raw" split points. Comments!


<!-- Sent from Reviewable.io -->

2019-06-05 20:40 UTC, jeffrey-xiao reviewed
>The approach doesn't seem particularly hacky. What were you concerned about?

The main concern was the use of the `raw` flag, but I don't think it's that bad.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-LgdMPcm6LtFl2aarMxb:b57fhn5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/unsplit.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcYqJ-9JcnCiZBloGM:-LgdMFtU8brFcjxKNr6o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L34)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This `raw` boolean needs a comment, please. A future code reader probably won't be able to understand what it means without reading and understanding all of the usages of it otherwise!
</blockquote></details>

Done.
___
*[pkg/sql/unsplit.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcZ3_K6nptgeHnqqYm:-LgdMHEtBVRGTh8LkoG8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L47)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You could put `raw:  n.All` in this declaration if you wanted.

So does `raw` just mean `all`? What do you think about renaming it to `unsplitAll` instead?
</blockquote></details>

Done.
___
*[pkg/sql/unsplit.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgcZf-K7zaUn286JYrn:-LgdMIj1DYcjOF-yjYPv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed2953985caf3fec9e7f8cf8d5f80ee3491b9ad1/pkg/sql/unsplit.go#L151)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What's going on here exactly? I guess the idea is that depending on what mode we're in, the row container stores a slightly different thing? You should comment this, please!

Oh, I see now what `raw` is about - it's describing that the values inside the row container are "raw" split points. Comments!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-05 21:30 UTC, ajwerner reviewed
> The approach doesn't seem particularly hacky. What were you concerned about?

I think @nvanbenschoten and I were unsure of whether it was a good idea to do the lookup on crdb

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-LgdUIeV4xq0e2UTKH0c:b-dfmxxn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, @jordanlewis, and @nvanbenschoten)

___
*[pkg/sql/unsplit.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LgdXsxg4HBQg1FNooz2:-LgdXsxg4HBQg1FNooz3:b-btxc67) ([raw file](https://github.com/cockroachdb/cockroach/blob/b202c2549d67a0189889e24924a7d5acc2bd195b/pkg/sql/unsplit.go#L73)):*
> ```Go
> 				start_key
> 			FROM
> 				crdb_internal.ranges
> ```

Use `crdb_internal.ranges_no_leases`, it's cheaper than `ranges`


<!-- Sent from Reviewable.io -->

2019-06-05 21:31 UTC, ajwerner reviewed
I meant to finish that sentence when I realized we were using `ranges` instead of `ranges_no_leases` :man_facepalming: .

But yeah, we were unsure of how kosher the lookup inside the planNode constructor was.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-LgdYD-i6kMWt1cYvSUW:b-ree6yy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jeffrey-xiao, @jordanlewis, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-06-05 21:38 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> mod the ranges_no_leases comment.

> Reviewed 3 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-:-Lgd_6MQ-jT5ES8oKnij:b-g325ff)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jeffrey-xiao, @jordanlewis, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-06-07 14:39 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38023)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jeffrey-xiao, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-06-07 15:39 UTC, jeffrey-xiao commented
bors r+

2019-06-07 16:17 UTC, merged

2019-06-30 02:51 UTC, RaduBerinde commented
___
*[pkg/sql/unsplit.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38023#-LiaH0IJCmWqBDcag1XA:-LiaH0IJCmWqBDcag1XB:b-s321ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/56eb106a36f83b2e335d131a93c06a499b1412de/pkg/sql/unsplit.go#L76)):*
> ```Go
> 				crdb_internal.ranges_no_leases
> 			WHERE
> 				table_name=$1::string AND index_name=$2::string AND split_enforced_until IS NOT NULL
> ```

I just noticed this code. We can have multiple tables with the same name (in different databases) and this will touch them all. For example:

```
root@127.129.42.91:44047/defaultdb> alter table t unsplit all;
            key           |      pretty        
+-------------------------+-------------------+
  \274\211\211            | /Table/52/1/1      
  \274\211\212            | /Table/52/1/2      
  \277\211\022foo\000\001 | /Table/55/1/"foo"  
  \277\211\022lol\000\001 | /Table/55/1/"lol"  
```


<!-- Sent from Reviewable.io -->

2019-07-01 01:53 UTC, RaduBerinde commented
Ah, never mind, that was already fixed in #38338.