[WIP] Loose index scan table reader
cockroachdb/cockroach pull request #38216
Opened 2019-06-17 17:11 UTC by rohany

First pass at implementing a loose index scan table reader. Please leave comments about the structure and I/O behavior.

This is intended to be used as a replacement for a table reader processor in certain situations. 

Consider the following schema and query -- 

```
CREATE TABLE t (a int, b int, c string, PRIMARY KEY(a, b));
SELECT DISTINCT(a) FROM t;
```

This table reader could be used to implement this query more efficiently than a full table scan, as it will seek through distinct increasing values of a, rather than scanning the entire table. This strategy can be more efficient than a full scan if there many more values of b than there are of a.

If there are x columns requested from the reader, it seeks through distinct values of the x length prefix of the primary key.

2019-06-17 17:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38216)
<!-- Reviewable:end -->

2019-06-17 19:42 UTC, solongordon requested changes
Great start! I left some thoughts. Looking forward to seeing some benchmarks comparing this to the vanilla tablereader. Also I think taking on reverse scans could be a good next step after this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-:-LhaxINM1tte0ptlD7LE:b-nsnqw7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhaw2V59IWJADe5iItw:-Lhaw2V59IWJADe5iItx:baaoeoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlpb/processors_sql.proto#L125)):*
> ```protobuf
> // IndexSkipTableReaderSpec
> // TODO: this might not need to be different from just the
> // normal table reader spec
> ```

Let's keep it separate even if it's very similar. Better for backward compatibility if they do diverge.
___
*[pkg/sql/distsqlpb/processors_sql.proto, line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhawFhIBTTibiLjGXpc:-LhawFhIBTTibiLjGXpd:b-s2t9zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlpb/processors_sql.proto#L126)):*
> ```protobuf
> // TODO: this might not need to be different from just the
> // normal table reader spec
> message IndexSkipTableReaderSpec {
> ```

Could you remove any unused fields below to avoid confusion down the line?
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhawRWABWLAswKVtBpc:-LhawRWBAY2g50sm9EGc:byk7nzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L27)):*
> ```Go
> )
> 
> type indexSkipTableReader struct {
> ```

Needs a description
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 33 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhawkC877MpNcCO3Z-l:-LhawkC877MpNcCO3Z-m:b-gxdbj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L33)):*
> ```Go
> 
> 	// maintains which span we are currently
> 	// getting rows from
> ```

Nit: We usually wrap comments at 80 chars
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhasStaEu8AzAVx4vdn:-LhasStaEu8AzAVx4vdo:b-h9ubj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L82)):*
> ```Go
> 	t := istrPool.Get().(*indexSkipTableReader)
> 
> 	t.currentSpan = 0
> ```

Nit: I would put this in `Release` rather than here since it's 0 by default, and that's where you're resetting everything else.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhasZIv2E3jK0ag4YWk:-LhasZIv2E3jK0ag4YWl:b-4dr5z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L85)):*
> ```Go
> 
> 	// hardcode right now to just get size 1 batches
> 	t.limitHint = limitHint(1, post)
> ```

Better to just remove this attribute entirely I'd say.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhatmLv50H4ViB-Rpcm:-LhatmLv50H4ViB-Rpcn:beped11) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L163)):*
> ```Go
> 			return nil, t.DrainHelper()
> 		}
> 		if !t.spans[t.currentSpan].Valid() {
> ```

Seems bad to silently ignore an invalid span. Better to throw an error if something is weird. I wonder if this check is necessary though. Does the tablereader do it?
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 170 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhatwBS0-kDIesG6toq:-LhatwBS0-kDIesG6tor:b-v6olzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L170)):*
> ```Go
> 		// do a scan
> 		err := t.fetcher.StartScan(
> 			t.Ctx, t.flowCtx.txn, []roachpb.Span{t.spans[t.currentSpan]},
> ```

A bit nicer: `t.spans[t.currentSpan:t.currentSpan + 1]`
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 190 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhapdyH3VA7ilbQuoaP:-LhapdyH3VA7ilbQuoaQ:bsdq1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L190)):*
> ```Go
> 			continue
> 		}
> 		if err != nil {
> ```

You should do the error check before the `row == nil` check, since row will probably be nil if an error is returned.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhaq2-P-E7me85Hg_3i:-Lhaq2-P-E7me85Hg_3j:b-ykbpvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L200)):*
> ```Go
> 		// 0xff present as a value in the table (0xff encodes a type of null)
> 		for i := 0; i < (t.indexLen - t.keyPrefixLen + 1); i++ {
> 			key = append(key, 0xff)
> ```

Nit: Might be nice to avoid repeated `append` calls here so we don't need to resize `key` more than once.
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 32 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhauMTh5LB9iTREw5xV:-LhauMTh5LB9iTREw5xW:b53fdmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L32)):*
> ```Go
> func TestIndexSkipTableReader(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Log("Beginning test run\n")
> ```

Don't need this
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhavRF78BHm55oXeIY7:-Lhauag8CsiMrKc4_DnH:b-15y823) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L84)):*
> ```Go
> 			},
> 			expected: "[[4] [5] [6]]",
> 		},
> ```

Would be nice to think about more exotic test cases.
- More than one output column?
- Secondary index?
- Null columns to test the `0xff` business?
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 89 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhavAeBC7w8BjmftaB4:-LhavAeBC7w8BjmftaB5:b-wkam01) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L89)):*
> ```Go
> 	for _, c := range testCases {
> 		t.Run("", func(t *testing.T) {
> 			testutils.RunTrueAndFalse(t, "row-source", func(t *testing.T, rowSource bool) {
> ```

Like I mentioned on Slack, I think you can just get rid of the `rowSource == false` case and keep things simple.


<!-- Sent from Reviewable.io -->

2019-06-18 15:37 UTC, rohany commented
@solongordon I added new tests and addressed your change requests

2019-06-18 19:47 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 148 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg2aQN5kfEMsLQUONN:-Lhg2aQN5kfEMsLQUONO:b-gtu1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b095c5b2497e9b307bd7113d6a22a22ee4728fa2/pkg/sql/distsqlpb/processors_sql.proto#L148)):*
> ```protobuf
>   // // If non-zero, this is a guarantee for the upper bound of rows a TableReader
>   // // will read. If 0, the number of results is unbounded.
>   // optional uint64 max_results = 8 [(gogoproto.nullable) = false];
> ```

I think you can just remove this. It's not relevant because we only fetch one row at a time regardless.
___
*[pkg/sql/distsqlpb/processors_sql.proto, line 150 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg2ui89hmKFSq1-CFG:-Lhg2ui89hmKFSq1-CFH:b-9k3mwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b095c5b2497e9b307bd7113d6a22a22ee4728fa2/pkg/sql/distsqlpb/processors_sql.proto#L150)):*
> ```protobuf
>   // optional uint64 max_results = 8 [(gogoproto.nullable) = false];
> 
>   optional uint64 max_timestamp_age_nanos = 5 [(gogoproto.nullable) = false];
> ```

Looks like this is only used for table stats so probably not needed here. Let's just remove it and we can add it back later if it turns out to be useful.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhasZIv2E3jK0ag4YWk:-Lhg3Wgl33LbMJmybSd1:bjns025) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L85)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Better to just remove this attribute entirely I'd say.
</blockquote></details>

I still think we always want the limit to be 1, right?
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 267 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg6tHi6i4bZJTSWfEO:-Lhg6tHi6i4bZJTSWfEP:b-9ikrcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8e60620710e49eb76b35973fc9e2e114018c76/pkg/sql/distsqlrun/index_skip_table_reader.go#L267)):*
> ```Go
> 			}
> 			trailingMeta = append(trailingMeta, distsqlpb.ProducerMetadata{Ranges: t.misplannedRanges})
> 		}
> ```

Didn't you already do the `misplannedRanges` check in `Next`? It seems like all you should do here is append `t.misplannedRanges` to the trailing metadata.


<!-- Sent from Reviewable.io -->

2019-06-18 20:01 UTC, rohany commented
Fixed code according to @solongordon's comments.

2019-06-21 20:12 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 123 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhqteur5rE6s8o8Fjzw:-Lhqteur5rE6s8o8Fjzx:b-sesasx) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlpb/processors_sql.proto#L123)):*
> ```protobuf
> }
> 
> // IndexSkipTableReaderSpec is the specification for table reader that
> ```

nit: should this be *a* table reader?
___
*[pkg/sql/distsqlpb/processors_sql.proto, line 127 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhqtiG-0NAdPpPIfUW1:-LhqtiG-0NAdPpPIfUW2:bauyqp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlpb/processors_sql.proto#L127)):*
> ```protobuf
> // this reader will return distinct rows from the table while using the index
> // to skip unnecessary rows. This reader is used for different optimizations
> // when operating on a prefix of a compound key
> ```

nit: I think you want a period here, or maybe you wanted to say more in this comment?
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 26 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhv_Mgj3wo2cTy5ghEy:-Lhv_Mgj3wo2cTy5ghEz:bd7um52) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L26)):*
> ```Go
> )
> 
> // indexSkipTableReader is another start of a computation flow; it performs
> ```

I see this was copied from tableReader. I would try to improve this comment a little bit - I think the one on tableReader isn't very good either :)

How about something like:

indexSkipTableReader is a DistSQL processor that retrieves distinct rows from a table, ...

I would also include the fact that indexSkipTableReader takes no inputs. That's what is meant by "start of a computation flow", but it's clearer. And finally, get rid of the thing about "runs a filter and passes rows to an output rowReciever" - that's a stale comment. We no longer Push rows anywhere - instead, we expose a Next (iterator model) interface.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 35 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhv_qIQ1KBrN93iKusZ:-Lhv_qIQ1KBrN93iKus_:bshsu5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L35)):*
> ```Go
> 	spans roachpb.Spans
> 
> 	// maintains which span we are currently getting rows from
> ```

nit: field and function comments are best prefixed with their name. (The Go linter enforces this for public fields and types). Also, add periods. So, this would be `currentSpan maintains which spans we are currently getting rows from.` Don't take these nits the wrong way! You couldn't have known these things easily.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 38 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaEaV4okgYW1DIY7o:-LhvaEaV4okgYW1DIY7p:b-1qf6no) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L38)):*
> ```Go
> 	currentSpan int
> 
> 	// how much of the primary key prefix we are doing the distinct over
> ```

nit: same as above. prefix and period, please!
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 196 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaskUC_l6BZ1--tbn:-LhvaskUC_l6BZ1--tbo:bbg6j5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L196)):*
> ```Go
> 		// 0xff present as a value in the table (0xff encodes a type of null)
> 		for i := 0; i < (t.indexLen - t.keyPrefixLen + 1); i++ {
> 			key = append(key, 0xff)
> ```

Hmm. i'm nervous that this will not work properly in the presence of interleaved tables. Do we guard against this possibility elsewhere?

Here's an example.

```
create table a (a int primary key);
create table b (a int, b int, primary key(a,b)) interleave in parent a(a);
insert into b values(50,0);

select distinct a from b
```

In this case, won't we get a key that's basically like /table/a/1/50, and construct a key that's "larger than any value with the same prefix" by doing `/table/a/1/50/ff`?

But, since we have an interleaved table, the full key for that row in b will be `/table/a/1/50/b/1/0`, roughly. Does this `ff` algorithm still work in that case? And why do we need to append one `ff` per column? Don't shorter strings sort after longer strings, so wouldn't just a single `ff` do? I think I need some more justification here to understand what's going on.


<!-- Sent from Reviewable.io -->

2019-06-21 20:56 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solon)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 123 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhqteur5rE6s8o8Fjzw:-LhvnT808a_7a4haKyI2:b-40jx38) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlpb/processors_sql.proto#L123)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: should this be *a* table reader?
</blockquote></details>

It seems like it should be considered a table reader? It’s I/O behavior seems similar to that of the table reader, though I’m not familiar with the rest of the architecture to see if there’s a better fit
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 196 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaskUC_l6BZ1--tbn:-LhvnvL76V7d4ikoSYyA:b-kfv04h) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L196)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm. i'm nervous that this will not work properly in the presence of interleaved tables. Do we guard against this possibility elsewhere?

Here's an example.

```
create table a (a int primary key);
create table b (a int, b int, primary key(a,b)) interleave in parent a(a);
insert into b values(50,0);

select distinct a from b
```

In this case, won't we get a key that's basically like /table/a/1/50, and construct a key that's "larger than any value with the same prefix" by doing `/table/a/1/50/ff`?

But, since we have an interleaved table, the full key for that row in b will be `/table/a/1/50/b/1/0`, roughly. Does this `ff` algorithm still work in that case? And why do we need to append one `ff` per column? Don't shorter strings sort after longer strings, so wouldn't just a single `ff` do? I think I need some more justification here to understand what's going on.
</blockquote></details>

Yeah I’m unsure about interleaved tables, I’ll have to also learn more about them before I can be sure about anything. I think as a first step @solongordon and I were thinking to not support interleaved tables. The alternative here is to actually decode the row into a datum and manipulate the datums we want to get the next key. We moved to this method to avoid having to do that.

We need multiple ff in the case that there nulls in the key, because ff is used to encode a null. We add one more just in case the last part of the key is null as well to ensure that the resulting key is larger than everything.


<!-- Sent from Reviewable.io -->

2019-06-21 20:57 UTC, rohany commented
Thanks for the review jordan! I’ll fix those nits when I get the chance.

2019-06-21 20:59 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solon)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 123 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhqteur5rE6s8o8Fjzw:-LhvpPI3BO-ImXoWLQKK:b-ga8hoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlpb/processors_sql.proto#L123)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

It seems like it should be considered a table reader? It’s I/O behavior seems similar to that of the table reader, though I’m not familiar with the rest of the architecture to see if there’s a better fit
</blockquote></details>

Haha I just meant adding the word "a" in front of "table reader", just a grammar thing!
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 196 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaskUC_l6BZ1--tbn:-LhvpUsD7MUNDOcTJ9Pn:b-haxny9) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L196)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah I’m unsure about interleaved tables, I’ll have to also learn more about them before I can be sure about anything. I think as a first step @solon and I were thinking to not support interleaved tables. The alternative here is to actually decode the row into a datum and manipulate the datums we want to get the next key. We moved to this method to avoid having to do that.

We need multiple ff in the case that there nulls in the key, because ff is used to encode a null. We add one more just in case the last part of the key is null as well to ensure that the resulting key is larger than everything.
</blockquote></details>

I'm into the idea of not supporting them for now!


<!-- Sent from Reviewable.io -->

2019-06-21 21:07 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solon)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 123 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhqteur5rE6s8o8Fjzw:-Lhvr4651-NxLw6-f4ML:b44twb) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlpb/processors_sql.proto#L123)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Haha I just meant adding the word "a" in front of "table reader", just a grammar thing!
</blockquote></details>

🤔
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 196 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaskUC_l6BZ1--tbn:-LhvrCSQDpYthA1hb2c6:bx0s4u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L196)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm into the idea of not supporting them for now!
</blockquote></details>

Alright, I’ll add that information into the comments while fixing the nits.


<!-- Sent from Reviewable.io -->

2019-06-21 22:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=38216) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=38216) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rohany<br/>:x: Rohan Yadav<br/><hr/>**Rohan Yadav** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cockroachdb/cockroach?pullRequest=38216) it.</sub>

2019-06-21 22:33 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @solon, and @solongordon)

___
*[pkg/sql/distsqlpb/processors_sql.proto, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhaw2V59IWJADe5iItw:-Lhw5hRL9_ge8oE-YmtW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlpb/processors_sql.proto#L125)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Let's keep it separate even if it's very similar. Better for backward compatibility if they do diverge.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlpb/processors_sql.proto, line 148 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg2aQN5kfEMsLQUONN:-Lhw65KS9KZ-dbg0TscR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b095c5b2497e9b307bd7113d6a22a22ee4728fa2/pkg/sql/distsqlpb/processors_sql.proto#L148)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think you can just remove this. It's not relevant because we only fetch one row at a time regardless.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlpb/processors_sql.proto, line 150 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg2ui89hmKFSq1-CFG:-Lhw66czCRkqSpqEGPYc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b095c5b2497e9b307bd7113d6a22a22ee4728fa2/pkg/sql/distsqlpb/processors_sql.proto#L150)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Looks like this is only used for table stats so probably not needed here. Let's just remove it and we can add it back later if it turns out to be useful.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhasZIv2E3jK0ag4YWk:-Lhw68cXBfz51Axd4i2Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader.go#L85)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I still think we always want the limit to be 1, right?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 267 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg6tHi6i4bZJTSWfEO:-Lhw68pdCu9MocchaISs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8e60620710e49eb76b35973fc9e2e114018c76/pkg/sql/distsqlrun/index_skip_table_reader.go#L267)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Didn't you already do the `misplannedRanges` check in `Next`? It seems like all you should do here is append `t.misplannedRanges` to the trailing metadata.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 26 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhv_Mgj3wo2cTy5ghEy:-Lhw8FndE-9nRaQUrdgX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L26)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I see this was copied from tableReader. I would try to improve this comment a little bit - I think the one on tableReader isn't very good either :)

How about something like:

indexSkipTableReader is a DistSQL processor that retrieves distinct rows from a table, ...

I would also include the fact that indexSkipTableReader takes no inputs. That's what is meant by "start of a computation flow", but it's clearer. And finally, get rid of the thing about "runs a filter and passes rows to an output rowReciever" - that's a stale comment. We no longer Push rows anywhere - instead, we expose a Next (iterator model) interface.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 196 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhvaskUC_l6BZ1--tbn:-Lhw9bA97g-UV5iOaV0a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/928eba95865bed4336ecdbb5f4876d5f7a0d0978/pkg/sql/distsqlrun/index_skip_table_reader.go#L196)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Alright, I’ll add that information into the comments while fixing the nits.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 32 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhauMTh5LB9iTREw5xV:-Lhw6Rjz4mOLVzzLIy2d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L32)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Don't need this
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LhavRF78BHm55oXeIY7:-Lhw6STz9L2y4Av0sPE4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/857bfbbf2ad33e7a729018537de947b6705c424b/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L84)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Would be nice to think about more exotic test cases.
- More than one output column?
- Secondary index?
- Null columns to test the `0xff` business?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-21 22:36 UTC, rohany commented
alright, fixed all nits that jordan brought up.

2019-06-24 14:59 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solon)

___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 33 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Li8zHJE2MmsZ8tRwHvc:-Li8zHJE2MmsZ8tRwHvd:b-cjp6c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3507fdf12161573850fd5fcc9b0b0f96061db34/pkg/sql/distsqlrun/index_skip_table_reader.go#L33)):*
> ```Go
> // of the prefix instead of doing a full table scan.
> // As of now, the indexSkipTableReader does not support use with
> // interleaved tables.
> ```

Just to be safe, could you add an explicit check which throws an error if the table is interleaved? You should be able to figure that out from the table descriptor.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 43 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Li8yKZp-fqSw6HcczER:-Li8yKZp-fqSw6HcczES:baukbek) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3507fdf12161573850fd5fcc9b0b0f96061db34/pkg/sql/distsqlrun/index_skip_table_reader.go#L43)):*
> ```Go
> 
>   // keyPrefixLen holds the length of the prefix of the index
>   // that we are performing a distinct over.
> ```

Formatting weirdness. You have some spaces sneaking in for some reason.
___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 46 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Li8yOwC9iIKs3J88k5V:-Li8yOwC9iIKs3J88k5W:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3507fdf12161573850fd5fcc9b0b0f96061db34/pkg/sql/distsqlrun/index_skip_table_reader.go#L46)):*
> ```Go
> 	keyPrefixLen int
>   // indexLen holds the number of columns in the index that
>   // is being considered.
> ```

Ditto.
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 47 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg8gjD5yzqbvbuY4Zf:-Lhg8gjD5yzqbvbuY4Zg:biuhzef) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8e60620710e49eb76b35973fc9e2e114018c76/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L47)):*
> ```Go
> 	// | rowId/10  | rowId%10  |
> 
> 	xFnt1 := func(row int) tree.Datum {
> ```

Nit: Does "Fnt" stand for "function"? I'm used to seeing "fn".


<!-- Sent from Reviewable.io -->

2019-06-24 18:31 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, @solon, and @solongordon)

___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 47 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg8gjD5yzqbvbuY4Zf:-Li9kEaP01WVTOh4UMn8:b5n68lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8e60620710e49eb76b35973fc9e2e114018c76/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L47)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Does "Fnt" stand for "function"? I'm used to seeing "fn".
</blockquote></details>

the Fn stands for function, the t1 is means that this function is used as the x column in t1. I can change these names if it is unclear


<!-- Sent from Reviewable.io -->

2019-06-25 16:01 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once the interleaved check is fixed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-:-LiEMcna3i26TVHmNjop:b-cyg24r)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solon)

___
*[pkg/sql/distsqlrun/index_skip_table_reader.go, line 82 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-LiEMCpz3ZzeJreoW5nO:-LiEMCpz3ZzeJreoW5nP:b322xf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/916722d032959c61227ad6737429281dbc8d3fbc/pkg/sql/distsqlrun/index_skip_table_reader.go#L82)):*
> ```Go
> 	// error our if there is an index that is interleaved
> 	for _, index := range spec.Table.Indexes {
> 		if len(index.Interleave.Ancestors) > 0 {
> ```

I think this is not quite right. You're checking if this table is interleaved into another table, but we want to check if there are other tables interleaved into this table. See here for an example: https://github.com/cockroachdb/cockroach/blob/c9ad321f83e92b66b1c19462698c85827f2717da/pkg/sql/delete.go#L365-L371
___
*[pkg/sql/distsqlrun/index_skip_table_reader_test.go, line 47 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38216#-Lhg8gjD5yzqbvbuY4Zf:-LiEKS_h5FBFlPOXhhuj:btwluio) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8e60620710e49eb76b35973fc9e2e114018c76/pkg/sql/distsqlrun/index_skip_table_reader_test.go#L47)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

the Fn stands for function, the t1 is means that this function is used as the x column in t1. I can change these names if it is unclear
</blockquote></details>

Ah got it, that's fine


<!-- Sent from Reviewable.io -->

2019-06-25 17:56 UTC, rohany commented
bors r+

2019-06-25 18:16 UTC, merged