opt: early prototype for FK checks
cockroachdb/cockroach pull request #38277
Opened 2019-06-18 20:13 UTC by RaduBerinde

This is an early prototype for planning FK checks. The idea is that
the input of a mutation is wrapped into a `ForeignKeys` operator which
conceptually passes through the input unchanged; the FK check queries
hang off this operator.

The prototype comes with the following caveats:
 - only enabled in optbuilder tests
 - only INSERTs are supported
 - the FK check queries "alias" the same expression used as the
   mutation input. This is illegal in general but should be ok in
   practice when the input is a constant VALUES. The intention here
   is that `ForeignKeys` will act like the upcoming `With` operator
   and the FK checks will use a reference to that saved buffer.

Release note: None

2019-06-18 20:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38277)
<!-- Reviewable:end -->

2019-06-19 00:47 UTC, andy-kimball reviewed
Looks like an interesting start on this. How come we wouldn't add the `FKChecks` operator directly on the mutation operators? Semantically, these are evaluated *after* the mutation, correct?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-LhhBHmH-1LXBS3-MOSD:b-wg5wlm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @rytaft)



<!-- Sent from Reviewable.io -->

2019-06-19 02:38 UTC, RaduBerinde commented
Correct. It's a good question, I'll try doing that.

2019-06-19 15:07 UTC, rytaft requested changes
Nice work! I'll take another look after you try Andy's suggestion.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-LhkGXJz7glf4PbqIgLD:bbgf9z5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/builder.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-Lhk5e6EEJLbIHYMBUX5:-Lhk5e6EEJLbIHYMBUX6:b-wg7s7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/builder.go#L56)):*
> ```Go
> 
> 	// -- Control knobs: these fields can be set before calling Build to control
> 	//                   various aspects of the building process.
> ```

[nit] make the formatting of this comment consistent with the results section below
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-Lhk94oI5vXelNmwsm4z:-Lhk94oI5vXelNmwsm5-:bv4ixvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L763)):*
> ```Go
> 		}
> 		refOrdinals := make([]int, numCols)
> 		for i := range refOrdinals {
> ```

[nit] you're shadowing the outer `i`
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkAFbtEd8vvO7dMF-4:b6nozhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
> ```Go
> 		// prototyping purposes (should work ok with constant inputs). Note that
> 		// the column IDs in the FK check query aren't exposed by the ForeignKeys
> 		// operator so using the same column IDs shouldn't cause issues.
> ```

I don't really understand this comment. How are you reusing the expression? And what would the reference to a buffer look like?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkCLoaCxX4mByCzZEM:-LhkCLoaCxX4mByCzZEN:b-60y20i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L855)):*
> ```Go
> 				var condition opt.ScalarExpr
> 				for i, ok := originCols.Next(0); ok; i, ok = originCols.Next(i + 1) {
> 					is := mb.b.factory.ConstructIs(
> ```

shouldn't this be IsNot?
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkENEUBVuyd-nMbsoI:-LhkENEUBVuyd-nMbsoJ:bh3sd6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L145)):*
> ```
> # single column).
> exec-ddl
> CREATE TABLE child2 (c INT PRIMARY KEY, p INT REFERENCES parent(p) MATCH FULL)
> ```

[nit] maybe call this child_nullable2? Or child_nullable_full?
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkEkcY7qXfPfEqBJec:-LhkEkcY7qXfPfEqBJed:b7vvpnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L185)):*
> ```
>                      │    │                   └── null [type=unknown]
>                      │    └── filters
>                      │         └── is-not [type=bool]
> ```

seems like you're not respecting MATCH FULL since this is `is-not`, but you're building `is`
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkFYixBZ_uE2ZvnpfW:-LhkFYixBZ_uE2ZvnpfX:b1hfeu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L437)):*
> ```
>                      │    │                   └── null [type=unknown]
>                      │    └── filters
>                      │         ├── is-not [type=bool]
> ```

I think this should be wrapped in an OR
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkFhvt1sCC1L8n3Ec7:-LhkFhvt1sCC1L8n3Ec8:b-fmmsld) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L459)):*
> ```
>                                └── variable: t.public.multi_col_parent.r [type=int]
> 
> # Only p and q are nullable; no filter necessary.
> ```

you mean no filter necessary on r?


<!-- Sent from Reviewable.io -->

2019-06-19 15:33 UTC, RaduBerinde reviewed
Updated with Andy's suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-LhkKU422WJ2M4lTS50r:b-ua0a0o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkKdra0gNfmmJBQEFP:b-q4q103) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't really understand this comment. How are you reusing the expression? And what would the reference to a buffer look like?
</blockquote></details>

`mb.outScope.expr` will be used both as the input of the mutation, and as part of the FK check query. It means that query will be built twice and executed separately, which is bad if the result is non-deterministic. I believe this also violates some assumptions we make throughout the optimizer.

A reference would be an operator which corresponds to scanning a buffer where the input rows are saved. It will probably be the same operator for `WITH`.
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkEkcY7qXfPfEqBJec:-LhkMi47EwMnH-_bR9vy:ba7bbkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L185)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

seems like you're not respecting MATCH FULL since this is `is-not`, but you're building `is`
</blockquote></details>

good catch.. I think there's some functionality missing in the testcat, will fix.


<!-- Sent from Reviewable.io -->

2019-06-19 15:42 UTC, rytaft reviewed
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkONB-EFgHpq9cEVQr:bqs25td) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`mb.outScope.expr` will be used both as the input of the mutation, and as part of the FK check query. It means that query will be built twice and executed separately, which is bad if the result is non-deterministic. I believe this also violates some assumptions we make throughout the optimizer.

A reference would be an operator which corresponds to scanning a buffer where the input rows are saved. It will probably be the same operator for `WITH`.
</blockquote></details>

Thanks for the explanation! Is this still relevant now that you've included the checks as part of the mutation operation?


<!-- Sent from Reviewable.io -->

2019-06-19 15:53 UTC, RaduBerinde commented
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkR9v04Ml-ak3FHqvw:b3lwge8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Thanks for the explanation! Is this still relevant now that you've included the checks as part of the mutation operation?
</blockquote></details>

Yeah, same thing


<!-- Sent from Reviewable.io -->

2019-06-19 16:04 UTC, rytaft commented
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkSICM4lmB4Ynj4Wvp:bwtwbu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, same thing
</blockquote></details>

Instead of adding the checks as a separate query, is there any reason they couldn't be part of the same query? (This may not actually make any sense, just trying to understand...)


<!-- Sent from Reviewable.io -->

2019-06-19 16:18 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/builder.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-Lhk5e6EEJLbIHYMBUX5:-LhkUKu17DWZCw2OGNLi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/builder.go#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] make the formatting of this comment consistent with the results section below
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-Lhk94oI5vXelNmwsm4z:-LhkVCPZEeg41cUxYXh8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L763)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] you're shadowing the outer `i`
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkVEUJEHQn5-oQRXxJ:b-fybigy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Instead of adding the checks as a separate query, is there any reason they couldn't be part of the same query? (This may not actually make any sense, just trying to understand...)
</blockquote></details>

The checks need to run after the main query (one day maybe even later, at the end of txn).

But this is a bit perpendicular to this issue - even if there was a single query, we can't have two different parts of that query "point to" the same relational expression.

It would be akin to having `WITH a AS (..) UNION (some query with a), (some query with a)` and trying to build the query for `a` and simply use that group directly in the rest of the query. It's not correct because the query for `a` would get executed twice (with potentially different results), and it also violates some assumptions in the optimizer (for one, the way we store physical properties assumes the same group can't be part of the expression multiple times). The right thing to do is to store the results of the query for `a` and use that buffer for the multiple references.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkCLoaCxX4mByCzZEM:-LhkTsGR-SEq4i9P0twb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L855)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't this be IsNot?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkENEUBVuyd-nMbsoI:-LhkSjqf0vseYib1By3_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L145)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe call this child_nullable2? Or child_nullable_full?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 437 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkFYixBZ_uE2ZvnpfW:-LhkTtdXCE_2xl23YEan:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L437)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this should be wrapped in an OR
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/fk-checks-insert, line 459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkFhvt1sCC1L8n3Ec7:-LhkTvcgBlYnfV1s5uXC:b-d7909n) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/testdata/fk-checks-insert#L459)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

you mean no filter necessary on r?
</blockquote></details>

No, the `(p,q,r) = (null, null, null)` case is not possible so we don't need to filter it out (and that's the only case that can be ignored under FULL). Or said differently, `r is not null` is always true which makes the entire disjunction always true.


<!-- Sent from Reviewable.io -->

2019-06-19 16:49 UTC, rytaft commented
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkcuB3AFPX595n7eVn:b-g3breu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The checks need to run after the main query (one day maybe even later, at the end of txn).

But this is a bit perpendicular to this issue - even if there was a single query, we can't have two different parts of that query "point to" the same relational expression.

It would be akin to having `WITH a AS (..) UNION (some query with a), (some query with a)` and trying to build the query for `a` and simply use that group directly in the rest of the query. It's not correct because the query for `a` would get executed twice (with potentially different results), and it also violates some assumptions in the optimizer (for one, the way we store physical properties assumes the same group can't be part of the expression multiple times). The right thing to do is to store the results of the query for `a` and use that buffer for the multiple references.
</blockquote></details>

I see, but isn't it possible for the mutation operator to pass through its input (e.g. for RETURNING)? I'm thinking we could use that output as the input to the FK checks query.


<!-- Sent from Reviewable.io -->

2019-06-19 16:51 UTC, rytaft reviewed
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2019-06-19 16:54 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-Lhkdn8Z843SQvk8JIc2:blsv654) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I see, but isn't it possible for the mutation operator to pass through its input (e.g. for RETURNING)? I'm thinking we could use that output as the input to the FK checks query.
</blockquote></details>

That output could also be used by the outer query (with RETURNING). Also, there are multiple check queries (one for each FK reference). Which reminds me, I should add some tests with multiple references.


<!-- Sent from Reviewable.io -->

2019-06-19 16:56 UTC, andy-kimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkdRQ36NTd0ZUGfEpN:b-tcjz2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

That output could also be used by the outer query (with RETURNING). Also, there are multiple check queries (one for each FK reference). Which reminds me, I should add some tests with multiple references.
</blockquote></details>

I also thought about using RETURNING columns. But my hope is that we can (eventually) change SQL execution to run the FK checks in parallel with the input query, when possible. Imagine we had 3 FK checks for a given mutation operator with constant input. I see no reason we couldn't have 3 goroutines that run in the background making those checks in parallel. If we instead wrapped the mutation operator with 3 FK check operators in series, we'd need to wait to do each check until the previous check completed. Given that FK check latency is a big complaint from the SE team in POC's, I think we want a design that is able to minimize latency (even if we don't implement it in this release).


<!-- Sent from Reviewable.io -->

2019-06-19 17:00 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 807 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhkAFbtEd8vvO7dMF-3:-LhkfRgdEF5d2fulBpy7:b-xe5y6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d00c8b6bc8c0d77eb0026d3be6003865d1d2efb/pkg/sql/opt/optbuilder/mutation_builder.go#L807)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I also thought about using RETURNING columns. But my hope is that we can (eventually) change SQL execution to run the FK checks in parallel with the input query, when possible. Imagine we had 3 FK checks for a given mutation operator with constant input. I see no reason we couldn't have 3 goroutines that run in the background making those checks in parallel. If we instead wrapped the mutation operator with 3 FK check operators in series, we'd need to wait to do each check until the previous check completed. Given that FK check latency is a big complaint from the SE team in POC's, I think we want a design that is able to minimize latency (even if we don't implement it in this release).
</blockquote></details>

Makes sense - thanks!


<!-- Sent from Reviewable.io -->

2019-06-19 18:59 UTC, RaduBerinde commented
Added a test with multiple references. Also made the `testcat` output include `MATCH FULL` when appropriate and added some tests there.

2019-06-20 14:20 UTC, rytaft reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-LhpFYKs8hN2Hjqpa4g0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @justinj, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2019-06-20 19:43 UTC, RaduBerinde commented
@justinj - please take a look too. I am hoping to enlist your help in this area at some point (maybe next milestone).

2019-06-20 21:30 UTC, justinj reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, sorry for delay!

> Reviewed 11 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-Lhqn3wFBzQxE8QvV-BF:bqoqzfh)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/ops/statement.opt, line 189 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhqedzK2IqWGenVHmdv:-LhqedzK2IqWGenVHmdw:bwy9yg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/18cac3bfed04b232222f2eb5654c78b6aa5e18ca/pkg/sql/opt/ops/statement.opt#L189)):*
> ```
> 
> # FKChecksItem is a foreign key check query, to be run after the main query.
> # If the query returns any results, that will generate an execution error.
> ```

nit: this reads a little odd to me, maybe "An execution error will be generated if the query returns any results"?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 843 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-Lhqlj8iC2aK1RSfczOC:-Lhqlj8iC2aK1RSfczOD:b-fnadru) ([raw file](https://github.com/cockroachdb/cockroach/blob/18cac3bfed04b232222f2eb5654c78b6aa5e18ca/pkg/sql/opt/optbuilder/mutation_builder.go#L843)):*
> ```Go
> 					filters = append(filters, memo.FiltersItem{
> 						Condition: mb.b.factory.ConstructIsNot(
> 							mb.b.factory.ConstructVariable(opt.ColumnID(i)),
> ```

nit: unnecessary cast now?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 862 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhqlzRu57_onOoPHrJ-:-LhqlzRu57_onOoPHrJ0:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/18cac3bfed04b232222f2eb5654c78b6aa5e18ca/pkg/sql/opt/optbuilder/mutation_builder.go#L862)):*
> ```Go
> 				for i, ok := originCols.Next(0); ok; i, ok = originCols.Next(i + 1) {
> 					is := mb.b.factory.ConstructIsNot(
> 						mb.b.factory.ConstructVariable(opt.ColumnID(i)),
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-06-20 21:53 UTC, RaduBerinde reviewed
Thanks!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-:-Lhqpoky-UKzF6TLK7zy:b-hay2ia)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/opt/ops/statement.opt, line 189 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhqedzK2IqWGenVHmdv:-LhqpbGC6P8qHaCHycos:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18cac3bfed04b232222f2eb5654c78b6aa5e18ca/pkg/sql/opt/ops/statement.opt#L189)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: this reads a little odd to me, maybe "An execution error will be generated if the query returns any results"?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 862 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38277#-LhqlzRu57_onOoPHrJ-:-Lhqpo-F9f3oqv3OH8oj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18cac3bfed04b232222f2eb5654c78b6aa5e18ca/pkg/sql/opt/optbuilder/mutation_builder.go#L862)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-20 22:15 UTC, RaduBerinde commented
bors r+

2019-06-20 23:09 UTC, merged