[WIP] tighter spans for column families in lookup joins
cockroachdb/cockroach pull request #38301
Opened 2019-06-19 20:24 UTC by rohany

First pass at implementing family specific spans for lookup joins, beginning work on #38280 

theres probably some incorrect assumptions made in here, so let me know what to improve.

I added another test to the joinreader_test that forces a split into two different families for the point lookups, but I'm unsure how to verify that it does this other than by looking at logs.

2019-06-19 20:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38301)
<!-- Reviewable:end -->

2019-06-19 20:26 UTC, rohany commented
if this works, i believe a very similar strategy can be used to do the same optimization in the index joiner.

2019-06-25 17:53 UTC, solongordon requested changes
Testing is an interesting question. When I did this work for tablereader I added tests which looked at the spans in the explain plans, but that won't work here.

Right now the best thing I can think of would be to add a logic test where you use the SHOW TRACE FOR SESSION feature to see what scans are happening.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LiEkLws2NvIjJ6o81Ca:b-t9x1m9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/indexjoiner.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEj4N-EwkOruuqt-k6:-LiEj4N-EwkOruuqt-k7:b-tql0jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/indexjoiner.go#L55)):*
> ```Go
> 	spans roachpb.Spans
> 
> 	// Hold onto what families we need to query from if our
> ```

Nit: The Go convention is to prefix comments with the name of the thing they're describing, so `neededFamilies is...`. That way if you grep the code for `neededFamilies` you can see both the definition and the description.
___
*[pkg/sql/distsqlrun/indexjoiner.go, line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEgW_T8T2nUfg6dAdm:-LiEgW_T8T2nUfg6dAdn:bcmd6zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/indexjoiner.go#L226)):*
> ```Go
> 	// looking up a full primary key
> 	if len(ij.neededFamilies) > 0 &&
> 		len(ij.desc.Families) > 1 &&
> ```

I think this condition is redundant. It's implied by the other two.
___
*[pkg/sql/distsqlrun/joinreader.go, line 293 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEdRLZ4KT4baIwmys2:-LiEdRLZ4KT4baIwmys3:be4aey) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L293)):*
> ```Go
> 
> // TODO: maybe want to move this into the joinerbase?
> func (jr *joinReader) canSplitSpanIntoSeparateFamilies(span roachpb.Span) (bool, roachpb.Spans) {
> ```

Usually the convention in Go is to return the bool "ok" value second, not first. But actually I'm thinking it would be simpler here to do away with it altogether. If the span can't be split, you could still return `roachpb.Spans` but only containing the input span. Then just call the function `maybeSplitSpanIntoFamilies` or whatever.
___
*[pkg/sql/distsqlrun/joinreader.go, line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEOPnH17gs2hJSj7MU:-LiEOPnI8Komr2mpdx6q:b8syvxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L296)):*
> ```Go
> 	// check the following:
> 	// - we have more than one needed family
> 	// - we are looking at the primary index
> ```

I think this is too restrictive. We can also split if we have a unique secondary index.
___
*[pkg/sql/distsqlrun/joinreader.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEckOU5kiSyIJzR9SN:-LiEckOV3hxsg1TYcMwU:b-k0kkrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L302)):*
> ```Go
> 	// up on is equal to the number of columns in the primary index, then
> 	// we are guaranteed to be looking at a single row, so we don't need to
> 	// be checking if span.Key.Equals(span.EndKey)
> ```

This sounds plausible *except* I suspect it doesn't hold true for interleaved tables. I would recommend revisiting this after you've done some reading on the interleaved encoding stuff. You also might want to take a look at `MakeSpanFromEncDatums`, which is what the lookup joiner uses to make a span for a single key lookup.
___
*[pkg/sql/distsqlrun/joinreader.go, line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEjak_2AWTqgxvqWqz:-LiEjak_2AWTqgxvqWr-:baw6gdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L305)):*
> ```Go
> 	if len(jr.neededFamilies) > 0 &&
> 		jr.index.ID == jr.desc.PrimaryIndex.ID &&
> 		len(jr.desc.Families) > 1 &&
> ```

Redundant condition
___
*[pkg/sql/sqlbase/index_encoding.go, line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEf1it9kTSwFSDKJAq:-LiEf1it9kTSwFSDKJAr:bi1ghey) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/sqlbase/index_encoding.go#L272)):*
> ```Go
> // into separate spans that request particular families from neededFamilies
> // instead of requesting all the families. It is up to the client to verify
> // whether the requested span represents a single row lookup, and when
> ```

Can you make it clearer that this is only appropriate for point lookups?
___
*[pkg/sql/sqlbase/index_encoding.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEHXSE-gL9bt2yYn8F:-LiEHXSE-gL9bt2yYn8G:b4kpd4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/sqlbase/index_encoding.go#L283)):*
> ```Go
> 		tempSpan.EndKey = tempSpan.Key.PrefixEnd()
> 		if i > 0 && familyID == neededFamilies[i-1]+1 {
> 			// the family ID is the same, so collapse these spans
> ```

I think the previous comment was more accurate:
```
// This column family is adjacent to the previous one. We can merge
// the two spans into one.
```


<!-- Sent from Reviewable.io -->

2019-06-25 17:56 UTC, solongordon reviewed
This is the general kind of test I'm thinking of:
https://github.com/cockroachdb/cockroach/blob/27fe883b6205471e4b8a2f6c97fad12d2cee2cd2/pkg/sql/logictest/testdata/planner_test/update#L277-L294

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LiEm-y67oWMsfXQx5C2:behn73f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)



<!-- Sent from Reviewable.io -->

2019-06-25 19:51 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/distsqlrun/indexjoiner.go, line 226 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEgW_T8T2nUfg6dAdm:-LiF6goy6UCOdISN8GSt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/indexjoiner.go#L226)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think this condition is redundant. It's implied by the other two.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/joinreader.go, line 293 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEdRLZ4KT4baIwmys2:-LiF3ozWDSibPx-f-RJ3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L293)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Usually the convention in Go is to return the bool "ok" value second, not first. But actually I'm thinking it would be simpler here to do away with it altogether. If the span can't be split, you could still return `roachpb.Spans` but only containing the input span. Then just call the function `maybeSplitSpanIntoFamilies` or whatever.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/joinreader.go, line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEOPnH17gs2hJSj7MU:-LiF3_HE1arE-jcztvMK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L296)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think this is too restrictive. We can also split if we have a unique secondary index.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/joinreader.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEckOU5kiSyIJzR9SN:-LiF5HNT5Byk6pM-wsx2:biavmwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L302)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This sounds plausible *except* I suspect it doesn't hold true for interleaved tables. I would recommend revisiting this after you've done some reading on the interleaved encoding stuff. You also might want to take a look at `MakeSpanFromEncDatums`, which is what the lookup joiner uses to make a span for a single key lookup.
</blockquote></details>

I believe this should work even for interleaved tables -- MakeSpanFromEncDatums generates all the ancestors of the interleaving that are needed, and then child interleaved tables keys must have the '#' separator instead of a family id, so there isn't a way that we get back a span that contains child interleaved rows.
___
*[pkg/sql/distsqlrun/joinreader.go, line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEjak_2AWTqgxvqWqz:-LiF6iNgCQaO8ZcqkiUn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L305)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Redundant condition
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEf1it9kTSwFSDKJAq:-LiF2eiO9mAGHlSR7u5V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/sqlbase/index_encoding.go#L272)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Can you make it clearer that this is only appropriate for point lookups?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEHXSE-gL9bt2yYn8F:-LiF2xlmERHxnjXxHydt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/sqlbase/index_encoding.go#L283)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think the previous comment was more accurate:
```
// This column family is adjacent to the previous one. We can merge
// the two spans into one.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-25 21:24 UTC, rohany commented
I added an example logic test, take a look at let me know if its what you had in mind @solongordon

2019-06-26 14:39 UTC, solongordon requested changes
Great to see that test! Could we get one for index joins too?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LiJCyhQ16hQDtf4zz3u:b-t5qn5e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/joinreader.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEckOU5kiSyIJzR9SN:-LiJApdz7kwTGBe3sqC3:bhkhpxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L302)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I believe this should work even for interleaved tables -- MakeSpanFromEncDatums generates all the ancestors of the interleaving that are needed, and then child interleaved tables keys must have the '#' separator instead of a family id, so there isn't a way that we get back a span that contains child interleaved rows.
</blockquote></details>

That sounds plausible... let's test it!
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1081 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJBUBR5-IoHjgaegYJ:-LiJBUBR5-IoHjgaegYK:bfjjxw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1081)):*
> ```
> query error aggregate functions are not allowed in ON
> SELECT * FROM foo JOIN bar ON max(foo.c) < 2
> ```

Let's put this in the `lookup_join` test file. Then you shouldn't need to turn the optimizer on explicitly because it only uses configurations where the optimizer is already enabled.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1087 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJBiQYCrYYIlTHVbWe:-LiJBiQYCrYYIlTHVbWf:bre2obi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1087)):*
> ```
> 
> statement ok
> CREATE TABLE familySplit1 (x INT, PRIMARY KEY (x)); INSERT INTO familySplit1 VALUES (1);
> ```

Nit: Could you make the INSERTs separate statements? Helps readability.
Another nit: Usually table names are in `snake_case`.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1093 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJCMip7aQG0nuLNdWy:-LiJCMip7aQG0nuLNdWz:bnk21of) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1093)):*
> ```
> 
> statement ok
> SET optimizer = on; SET tracing = on; SELECT familySplit2.x, familySplit2.z FROM familySplit1 INNER LOOKUP JOIN familySplit2 ON (familySplit1.x = familySplit2.x); SET tracing = off; set optimizer = off; 
> ```

Nit: Extra parens around the ON condition.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1096 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJCQiqEFEtooYiZrGK:-LiJCQiqEFEtooYiZrGL:b-dai8a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1096)):*
> ```
> 
> query T
> select message from [SHOW TRACE FOR SESSION] where message in ('Scan /Table/81/1/1/{0-1}, /Table/81/1/1/2/{1-2}');
> ```

I would recommend changing the WHERE condition to `WHERE message LIKE 'Scan%'`. That way we can make sure there aren't any unnecessary scans happening.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1098 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJCFKi6sNjqL61eiUu:-LiJCFKi6sNjqL61eiUv:b-bqose0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1098)):*
> ```
> select message from [SHOW TRACE FOR SESSION] where message in ('Scan /Table/81/1/1/{0-1}, /Table/81/1/1/2/{1-2}');
> ----
> Scan /Table/81/1/1/{0-1}, /Table/81/1/1/2/{1-2}
> ```

Nice! Yes this is exactly what we want to see.


<!-- Sent from Reviewable.io -->

2019-06-26 18:56 UTC, rohany reviewed
Yup, added a test using interleaved tables as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LiK8N1MAB0f7xT3uG_D:bps663g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/distsqlrun/joinreader.go, line 302 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEckOU5kiSyIJzR9SN:-LiK8R2P3ClAcelFy1z3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L302)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

That sounds plausible... let's test it!
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1081 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJBUBR5-IoHjgaegYJ:-LiK0f9bC19GTJAYpFWY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1081)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Let's put this in the `lookup_join` test file. Then you shouldn't need to turn the optimizer on explicitly because it only uses configurations where the optimizer is already enabled.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1096 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJCQiqEFEtooYiZrGK:-LiK0e6ACfsVg2BF4I7K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1096)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I would recommend changing the WHERE condition to `WHERE message LIKE 'Scan%'`. That way we can make sure there aren't any unnecessary scans happening.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/join, line 1098 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiJCFKi6sNjqL61eiUu:-LiJpoHB8Ko6UvsRJkv6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b313460ee697eed6fc903b76bdeafd134c2defb7/pkg/sql/logictest/testdata/logic_test/join#L1098)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nice! Yes this is exactly what we want to see.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-03 15:06 UTC, solongordon requested changes
I added some picky comments about your logic tests. Otherwise this is good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LisMfDYCe-OmlJeRiCw:b-ozpdqf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 510 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisJ28kAw5ADZJVVr2V:-LisJ28kAw5ADZJVVr2W:b9gg57u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L510)):*
> ```
> 1     1  2  2  NULL  2
> 1     1  2  2  1     1
> ```

Nit: Extra blank line
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 517 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisJDVN7vh1iQyuX4xj:-LisJDVN7vh1iQyuX4xk:b-h0rki3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L517)):*
> ```
> 
> statement ok
> CREATE TABLE family_split_1 (x INT, PRIMARY KEY (x));
> ```

Nit: You don't need semicolons at the end of statements in logic tests.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 529 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisJWxy33LuFXe2Sh3k:-LisJWxy33LuFXe2Sh3l:b-owpy7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L529)):*
> ```
> 
> statement ok
> SET tracing = on; SELECT family_split_2.x, family_split_2.z FROM family_split_1 INNER LOOKUP JOIN family_split_2 ON family_split_1.x = family_split_2.x; SET tracing = off;
> ```

Minor: While we're running this query we might as well assert that the output is as expected. Like
```
query II
SET tracing = on; SELECT y,w FROM family_index_join WHERE y = 2
----
2 4

query T
SET tracing = off; SELECT message FROM [SHOW TRACE FOR SESSION] WHERE message LIKE 'Scan /Table/71/%, /Table/71/%';
----
Scan /Table/71/1/1/1/{1-2}, /Table/71/1/1/3/{1-2}
```
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 532 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisKGC0EAqNsrCoVIiC:-LisKGC0EAqNsrCoVIiD:b-p5b3qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L532)):*
> ```
> 
> query T
> SELECT message FROM [SHOW TRACE FOR SESSION] WHERE message LIKE 'Scan /Table/70/%, /Table/70/%'
> ```

I still think we should make the `LIKE` a bit more general: `WHERE message LIKE 'Scan /Table/70/%`. Just in case there are extra scans you're not catching.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 535 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisKQ1g3xd6tBqsvCzN:-LisKQ1g3xd6tBqsvCzO:b9gg57u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L535)):*
> ```
> ----
> Scan /Table/70/1/1/{0-1}, /Table/70/1/1/2/{1-2}
> ```

Nit: Extra blank line
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 544 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisKlU41jw_AEnD-DlX:-LisKlU41jw_AEnD-DlY:bugeg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L544)):*
> ```
> 
> statement ok
> SET tracing = on; SELECT y,w FROM family_index_join WHERE y = 2; SET tracing = off;
> ```

Same thing about asserting the output.

Also, just to be safe we might want to force it to use the y index so that the index join will definitely happen: `SELECT y, w FROM family_index_join@family_index_join_y_idx WHERE y = 2`.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 547 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisLJf53i5VjqwA9pp_:-LisLJf53i5VjqwA9ppa:b-xzydkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L547)):*
> ```
> 
> query T
> SELECT message FROM [SHOW TRACE FOR SESSION] WHERE message LIKE 'Scan /Table/71/%, /Table/71/%';
> ```

Ditto about the more general `LIKE`.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisLbmyAQYNhOQz3qGn:-LisLbmyAQYNhOQz3qGo:b2mpsnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L551)):*
> ```
> Scan /Table/71/1/1/1/{1-2}, /Table/71/1/1/3/{1-2}
> 
> # test tight spans with interleaved tables
> ```

Proper grammar for comments please
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 568 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisMVHv7RjePBS2fmOV:-LisMVHv7RjePBS2fmOW:buzeyps) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L568)):*
> ```
> 
> query II
> select family_interleave_1.x, family_interleave_1.z from family_interleave_2 INNER LOOKUP JOIN family_interleave_1 ON family_interleave_1.x = family_interleave_2.x;
> ```

Nit: upper case SELECT and FROM would be nice.
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 576 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LisMb013BbzVM5wzmi0:-LisMb013BbzVM5wzmi1:b-xzydkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9df059a06d035c88172fb4b525eaa428fdb14b6/pkg/sql/logictest/testdata/logic_test/lookup_join#L576)):*
> ```
> 
> query T
> SELECT message FROM [SHOW TRACE FOR SESSION] WHERE message LIKE 'Scan /Table/72/%, /Table/72/%';
> ```

Ditto about the more general `LIKE`.


<!-- Sent from Reviewable.io -->

2019-07-08 20:50 UTC, rohany commented
RFAL

2019-07-09 02:08 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-:-LjJUBnV4Q4kKKMXXkRf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-07-09 14:58 UTC, rohany commented
bors r+

2019-07-09 16:06 UTC, merged

2019-07-16 15:27 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/distsqlrun/joinreader.go, line 296 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38301#-LiEOPnH17gs2hJSj7MU:-LjvNdsg8OK2XZJIHZ6T:b5gh9b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d986d76b63b92a2d288e45631cc265f8a9a7b0bc/pkg/sql/distsqlrun/joinreader.go#L296)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, I think I was wrong here. This optimization only applies to the primary index, because there's no such thing as column families on a secondary index.


<!-- Sent from Reviewable.io -->