pgtest: teach ErrorResponse about response codes
cockroachdb/cockroach pull request #38365
Opened 2019-06-22 04:04 UTC by mjibson

Make error response codes match for existing tests. These aren't
exhaustive, and maybe we can do more in the future, but this is a
good start.

Release note (sql change): Make some pgwire error codes for binary
parameter decoding better match Postgres.

2019-06-22 04:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38365)
<!-- Reviewable:end -->

2019-06-22 07:33 UTC, knz requested changes
Thanks Matt for starting on this path. In general I think that aligning the error codes with pg is going to be a good investment.

As a special case though, I'd like to request that you treat the internal code (XX000) specially: for this, the test should accept a difference, and let CockroachDB produce a more specific code than postgres. 

The reason is that we treat XX000 specially throughout the code base. Between other things, it causes noisy logging and a Sentry report. We have validated before that this special casing is a good thing, and I strongly recommend we don't revisit this difference just for the sake of pg alignment.

Also arguably the code is very vague and does not tell much about what the error is about. In the particular case of the json code, for example, `NewProtocolViolationErrorf()` would be a better choice than either the syntax or internal error code.

2019-07-01 20:46 UTC, mjibson commented
Agreed. I've added the ability to map error types to do this. RFAL.

2019-07-02 04:20 UTC, mjibson commented
Rebased on top of #38586, but only the last commit is relevant.

2019-07-02 10:22 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but you'll want andrei to also check the portal tests.
Thanks!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38365#-:-LimCAlIE66jxzVnJOoO:b-cdqqsn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-07-02 20:02 UTC, mjibson commented
bors r+

2019-07-02 20:21 UTC, merged