exec: add BatchAllocator skeleton
cockroachdb/cockroach pull request #38394
Opened 2019-06-25 13:46 UTC by solongordon

I created a new BatchAllocator type, which is responsible for doling out
batches to operators within a fixed budget. The budgeting logic doesn't
exist yet, but this commit adds the new type and plumbs it through
operators which use a variable amount of memory. Next step is to
actually measure the memory required when NewBatch or Append is called
and track that against a budget.

Fixes #38056

Release note: None

2019-06-25 13:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38394)
<!-- Reviewable:end -->

2019-06-25 15:36 UTC, yuzefovich approved these changes
Left a few comments, but it <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 19 of 19 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-:-LiEGb-n8fb4XRVSoTf7:b-ty4n6p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @solongordon)

___
*[pkg/sql/exec/mergejoiner.go, line 203 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiEEOiACjZomrzX7yVD:-LiEEOiACjZomrzX7yVE:b-2j2es9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e50cf5d5ec218732772d30ce3a88a769b1930c0/pkg/sql/exec/mergejoiner.go#L203)):*
> ```Go
> 
> // NewMergeJoinOp returns a new merge join operator with the given spec.
> func NewMergeJoinOp(
> ```

I think you missed a few cases of `NewMemBatchWithSize` in the merge joiner (within `mergeJoinOp.initWithBatchSize`). (Also, some appends, but I guess we can deal with it later.)
___
*[pkg/sql/exec/sort.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiEFojU7zIYNiceQhQq:-LiEFojV1_-M1tZdNQpY:b-hllix5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e50cf5d5ec218732772d30ce3a88a769b1930c0/pkg/sql/exec/sort.go#L27)):*
> ```Go
> func NewSorter(
> 	input Operator,
> 	allocator coldata.BatchAllocator,
> ```

[nit]: in some cases you put `allocator` as the first argument, in others `input` as first. It'd be nice to be consistent, even if there are two inputs like in the cases of the joiners (I don't have a preference for one of those though).
___
*[pkg/sql/exec/coldata/batch.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiEFDP15boHbu7zDctx:-LiEFDP15boHbu7zDcty:b-8kzd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e50cf5d5ec218732772d30ce3a88a769b1930c0/pkg/sql/exec/coldata/batch.go#L177)):*
> ```Go
> // size.
> func (*BatchAllocator) NewMemBatchWithSize(types []types.T, size int) (batch Batch, ok bool) {
> 	return NewMemBatchWithSize(types, size), true
> ```

Maybe it makes sense do `s/NewMemBatchWithSize/newMemBatchWithSize` so that the build will tell you in which spots it is used? Then you'll substitute all of those with `BatchAllocator.NewMemBatchWithSize`. This trick could work for `Append` as well.
___
*[pkg/sql/exec/coldata/batch.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiEGSvh6lPZ6eEb4sYH:-LiEGSvh6lPZ6eEb4sYI:bl2iajd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca13c4f2ebdf68c40a5a65ec8502d782b1bfab10/pkg/sql/exec/coldata/batch.go#L167)):*
> ```Go
> //
> // TODO(solon): Add memory budget logic.
> type BatchAllocator struct{}
> ```

The goal is that `BatchAllocator` will handle `Copy` and nulls eventually as well, right?


<!-- Sent from Reviewable.io -->

2019-07-01 03:51 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38394)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @solongordon)

___
*[pkg/sql/exec/hashjoiner.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LifdFSqBH14Q7DVd7FU:-LifdFSqBH14Q7DVd7FV:baobrq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca13c4f2ebdf68c40a5a65ec8502d782b1bfab10/pkg/sql/exec/hashjoiner.go#L490)):*
> ```Go
> 			},
> 		); !ok {
> 			panic("hashTable exceeded allocator budget")
> ```

I think all of these probably want to be panics on errors with a pgerror code, or else the panic catcher in `pkg/sql/exec/error.go` will think it's an "unexpected error" and wrap it further. We probably want to make this just propagate an error returned by `Append`, so that we don't have to duplicate that pgerror code in every callsite to append/ne.
___
*[pkg/sql/exec/coldata/batch.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-Lifdaih-wGlsOpsAqvR:-Lifdaih-wGlsOpsAqvS:bqwvk42) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca13c4f2ebdf68c40a5a65ec8502d782b1bfab10/pkg/sql/exec/coldata/batch.go#L176)):*
> ```Go
> // NewMemBatchWithSize allocates a new in-memory Batch with the given column
> // size.
> func (*BatchAllocator) NewMemBatchWithSize(types []types.T, size int) (batch Batch, ok bool) {
> ```

I think while we're changing this interface, I'd recommend that we probably replace the `ok bool` with an `err error`, so that this function can eventually return an error that has a suitable error, similar to our current system (requested x, but only y in budget, or some other such readable message).


<!-- Sent from Reviewable.io -->

2019-07-01 16:27 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38394)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/sort.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiEFojU7zIYNiceQhQq:-LiiEZb01EQ2DmlvFHwC:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e50cf5d5ec218732772d30ce3a88a769b1930c0/pkg/sql/exec/sort.go#L27)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: in some cases you put `allocator` as the first argument, in others `input` as first. It'd be nice to be consistent, even if there are two inputs like in the cases of the joiners (I don't have a preference for one of those though).
</blockquote></details>

+1
___
*[pkg/sql/exec/coldata/batch.go, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-LiiLboo5YGPImeLRv3L:-LiiLboo5YGPImeLRv3M:b-rv5xw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca13c4f2ebdf68c40a5a65ec8502d782b1bfab10/pkg/sql/exec/coldata/batch.go#L167)):*
> ```Go
> //
> // TODO(solon): Add memory budget logic.
> type BatchAllocator struct{}
> ```

I would move this to a new file.
___
*[pkg/sql/exec/coldata/batch.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38394#-Lifdaih-wGlsOpsAqvR:-LiiLnww8RlRJTsI-0MF:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca13c4f2ebdf68c40a5a65ec8502d782b1bfab10/pkg/sql/exec/coldata/batch.go#L176)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think while we're changing this interface, I'd recommend that we probably replace the `ok bool` with an `err error`, so that this function can eventually return an error that has a suitable error, similar to our current system (requested x, but only y in budget, or some other such readable message).
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2019-11-13 23:24 UTC, yuzefovich commented
This PR has been taken over by #42232, so feel free to close it :)

2019-11-14 14:10 UTC, asubiotto commented
Superseded by #42232, thanks for your work on this @solongordon!

2019-11-14 14:10 UTC, closed without merging