exec: consolidate all Copy{...} methods into one
cockroachdb/cockroach pull request #38419
Opened 2019-06-25 20:17 UTC by asubiotto

This makes the code easier to work with.

name                old time/op    new time/op    delta
Copy/CopySimple-8      158ns ± 0%     115ns ± 1%   -27.05%  (p=0.000 n=8+9)
Copy/CopyWithSel-8     790ns ± 0%     668ns ± 2%   -15.47%  (p=0.000 n=8+10)

name                old speed      new speed      delta
Copy/CopySimple-8   51.6GB/s ± 0%  70.6GB/s ± 1%   +36.83%  (p=0.000 n=8+9)
Copy/CopyWithSel-8  10.4GB/s ± 0%  12.3GB/s ± 2%   +18.28%  (p=0.000 n=8+10)

name                old alloc/op   new alloc/op   delta
Copy/CopySimple-8       128B ± 0%        0B       -100.00%  (p=0.000 n=10+10)
Copy/CopyWithSel-8     0.00B          0.00B           ~     (all equal)

Release note: None

2019-06-25 20:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38419)
<!-- Reviewable:end -->

2019-06-26 14:22 UTC, solongordon requested changes
Looks good in general! A few minor things.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-:-LiJ9VXb7BGYQoRe-Rpy:bspf72x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @solongordon)

___
*[pkg/sql/exec/coldata/vec.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ1BRU32zJs0fpDTX2:-LiJ1BRU32zJs0fpDTX3:b-y0vy3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec.go#L122)):*
> ```Go
> 	// Copy uses CopyArgs to copy elements of a source Vec into this Vec. It is
> 	// logically equivalent to:
> 	// copy(destVec[:args.DestIdx], args.Src[args.SrcStartIdx:args.SrcEndIdx])
> ```

Did you mean `destVec[args.DestIdx:]`?
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ6xkr61SgdoWq-uyd:-LiJ6xkr61SgdoWq-uye:b-nkpypd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L71)):*
> ```Go
> 	if args.DestIdx != 0 && m.HasNulls() {
> 		panic("copying to non-zero dest index with nulls is not implemented yet (would overwrite nulls)")
> 	}
> ```

It might also be nice to fail fast if the args are set incorrectly, for instance both `Sel` and `Sel64` set or `Nils` set without `Sel64`.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ7TZ82lD52koWfBhL:-LiJ7TZ82lD52koWfBhM:b-g7dohw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L83)):*
> ```Go
> 		fromCol := args.Src._TemplateType()
> 		toCol := m._TemplateType()
> 		if args.Sel64 != nil {
> ```

Nit: I think this would be a bit more readable if you returned immediately at the end of each case. Would reduce indentation a bit and make it clear there isn't shared logic below.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ8Cbt0hT5u3rFU_P-:-LiJ8Cbt0hT5u3rFU_P0:biv3j1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L111)):*
> ```Go
> 					nulls := args.Src.Nulls()
> 					toColSliced := toCol[args.DestIdx:]
> 					for i, selIdx := range sel[args.SrcStartIdx:args.SrcEndIdx] {
> ```

I think you can use `Nulls.ExtendWithSel` here.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ5AIz1bn5leKIUJ8W:-LiJ5AIz1bn5leKIUJ8X:buycj4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L151)):*
> ```Go
> 				if args.DestIdx == 0 && args.SrcStartIdx == 0 {
> 					// We can copy this bitmap indiscriminately.
> 					copy(m.nulls.nulls, args.Src.Nulls().NullBitmap())
> ```

I guess this goes hand-in-hand with your TODO but we should only be copying nulls up until `SrcEndIdx`, right?
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ5ba13Wejn6YskPFf:-LiJ5ba13Wejn6YskPFg:bec69et) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L154)):*
> ```Go
> 				} else {
> 					srcNulls := args.Src.Nulls()
> 					for curDestIdx, curSrcIdx := args.DestIdx, args.SrcStartIdx; curSrcIdx < args.SrcEndIdx; curDestIdx, curSrcIdx = curDestIdx+1, curSrcIdx+1 {
> ```

I think you could use `Nulls.Extend` here.


<!-- Sent from Reviewable.io -->

2019-06-26 15:28 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38419)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/exec/coldata/vec.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ1BRU32zJs0fpDTX2:-LiJFbJ89afzTTcNIqkG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec.go#L122)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Did you mean `destVec[args.DestIdx:]`?
</blockquote></details>

Done.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ6xkr61SgdoWq-uyd:-LiJFqat6oJCPKeLnSmG:b-zirpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L71)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It might also be nice to fail fast if the args are set incorrectly, for instance both `Sel` and `Sel64` set or `Nils` set without `Sel64`.
</blockquote></details>

Done. Added check for `Nils` but I think it's fine to just ignore `Sel` when `Sel64` is set
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ7TZ82lD52koWfBhL:-LiJGYkW6aZQ2LI-6pOk:b-ns2p5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L83)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: I think this would be a bit more readable if you returned immediately at the end of each case. Would reduce indentation a bit and make it clear there isn't shared logic below.
</blockquote></details>

Done. LMK.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ8Cbt0hT5u3rFU_P-:-LiJI-5N7Q1jDq8JDM06:b618ema) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L111)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think you can use `Nulls.ExtendWithSel` here.
</blockquote></details>

You're right, but I that would result in two loops instead of one and would only remove the if check so I'm not sure whether it would be an improvement. The other danger is that `Extend` uses `append` so might truncate nulls past the end of where we're copying. This only happens in the case that our null slice does not have enough capacity, which is an assumption of `Copy`, so that should be fine.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ5AIz1bn5leKIUJ8W:-LiJMPwd-hjIdPQcJUBr:b-vydou1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L151)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I guess this goes hand-in-hand with your TODO but we should only be copying nulls up until `SrcEndIdx`, right?
</blockquote></details>

Yes, or some modded version of that. Not doing that here due to the `UnsetNulls` above already losing null information. It feels weird to keep this code broken but I'd rather tackle the problems in this code iteratively.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ5ba13Wejn6YskPFf:-LiJN67MBH0OhZQnaZQN:b-5p1ewe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L154)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think you could use `Nulls.Extend` here.
</blockquote></details>

Good point. I changed it to `Nulls.Extend` but it takes `uint16` args and don't want to cause issues by casting `uint64`s to `uint16`s. Left a TODO.


<!-- Sent from Reviewable.io -->

2019-06-26 15:37 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-:-LiJQsVSD6k2WUZxbYYn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ6xkr61SgdoWq-uyd:-LiJPOxY8HCoeehp_YzQ:b-6dk873) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done. Added check for `Nils` but I think it's fine to just ignore `Sel` when `Sel64` is set
</blockquote></details>

I still think something weird has happened if both `Sel` and `Sel64` are set but no big deal.
___
*[pkg/sql/exec/coldata/vec_tmpl.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38419#-LiJ8Cbt0hT5u3rFU_P-:-LiJQIWf0If-iRhtHj8u:b-rl194a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a6e7d9cab0b3b8d98384a51dbbb7ec50cfb9a7/pkg/sql/exec/coldata/vec_tmpl.go#L111)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You're right, but I that would result in two loops instead of one and would only remove the if check so I'm not sure whether it would be an improvement. The other danger is that `Extend` uses `append` so might truncate nulls past the end of where we're copying. This only happens in the case that our null slice does not have enough capacity, which is an assumption of `Copy`, so that should be fine.
</blockquote></details>

Oh yeah, I missed that you're either setting the null bit or copying a value, so `Extend` doesn't work so well here. Never mind.


<!-- Sent from Reviewable.io -->

2019-06-26 16:00 UTC, asubiotto commented
bors r=solongordon

2019-06-26 16:39 UTC, asubiotto commented
That's weird... no failed tests but bors failed?

bors r=solongordon

2019-06-26 17:35 UTC, asubiotto commented
bors r=solongordon

2019-06-26 17:55 UTC, merged