exec: handle nulls in ordered distinct
cockroachdb/cockroach pull request #38464
Opened 2019-06-26 20:31 UTC by solongordon

The ordered distinct operator previously did not take nulls into
account. I added logic to handle this, which basically amounts to an
extra step to iterate through any null values at the beginning of the
input.

Fixes #36881

Release note: None

2019-06-26 20:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38464)
<!-- Reviewable:end -->

2019-06-26 21:10 UTC, rafiss requested changes
looks nice! only relatively minor comments.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-:-LiKbfH_-N35HNyuwQ6k:b-71olqp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/distinct_test.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKbAWhDZoSDIei6eQD:-LiKbAWhDZoSDIei6eQE:bbxke0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_test.go#L105)):*
> ```Go
> 	lastB := int64(0)
> 	for i := 0; i < coldata.BatchSize; i++ {
> 		// 1/4 chance of changing each distinct coldata.
> ```

perhaps the benchmark should be adjusted so there is also some chance that some values are null.

the pattern i went with in https://github.com/cockroachdb/cockroach/pull/38422 was to benchmark with two values of `nullProbability` (0 and 0.3). the performance characteristics do differ, but i am not certain if that justifies running the benchmark a second time. what do you think?
___
*[pkg/sql/exec/distinct_tmpl.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKXGhEBBoR96oQyfr1:-LiKXGhEBBoR96oQyfr2:b-ddk4a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L184)):*
> ```Go
> 	vec := batch.ColVec(p.sortedDistinctCol)
> 	var nulls *coldata.Nulls
> 	if vec.HasNulls() {
> ```

this if-block may not be necessary; you should be able to do `nulls := vec.Nulls()` at the beginning of the `if !p.foundFirstNonNullRow` block.

i think this suggestion is mostly just a matter of style, but IMO it makes it a little easier to read since `nulls` is only used inside the if-block below
___
*[pkg/sql/exec/distinct_tmpl.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKYc4z6lAM4-HAL-2a:-LiKYc4z6lAM4-HAL-2b:b-6t9h53) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L197)):*
> ```Go
> 			outputCol[0] = true
> 		}
> 		p.foundFirstRow = true
> ```

you might be able to avoid entering the `if !p.foundFirstNonNullRow` block later if you set `p.foundFirstNonNullRow = !vec.HasNulls()` right here
___
*[pkg/sql/exec/distinct_tmpl.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKZb2U1m6I2qmDbUUM:-LiKZb2U1m6I2qmDbUUN:bbjwyz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L209)):*
> ```Go
> 		if sel != nil {
> 			for _, i := range sel[:n] {
> 				if nulls == nil || !nulls.NullAt(i) {
> ```

the `nulls == nil` check can be removed if we set `p.foundFirstNonNullRow` eagerly as per my previous comment. (same for line 220)

i'm not sure if that makes the code too not-obvious, but maybe it would be fine to remove as long as there's a comment explaining why we don't have to check
___
*[pkg/sql/exec/distinct_tmpl.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKVpFUD56IYubd6eNa:-LiKVpFUD56IYubd6eNb:b1idy9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L219)):*
> `for startIdx < n`

i think you can eliminate a bounds check here by doing `for range col[:n]` instead
___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKalC5BqIs6f4O_LJc:bvbse96) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
> ```Go
> 					break
> 				}
> 				startIdx++
> ```

this is probably besides the point, but i wonder if it would be useful to have a function like `Nulls.AllNulls()` -- if that is true then we can avoid the loop entirely and skip right to the end of the batch.


<!-- Sent from Reviewable.io -->

2019-06-26 21:14 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKcl4l7o9JD05TRIWP:b-o0xvqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is probably besides the point, but i wonder if it would be useful to have a function like `Nulls.AllNulls()` -- if that is true then we can avoid the loop entirely and skip right to the end of the batch.
</blockquote></details>

to be more clear, what i meant to say is that such a function is beyond the scope of this PR, but i'm curious to hear your thoughts about it


<!-- Sent from Reviewable.io -->

2019-06-26 21:45 UTC, solongordon reviewed
Thanks for the review! Fixes coming tomorrow.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-:-LiKjY0g4uhNCrNDGBiM:b5by7ee)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/distinct_test.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKbAWhDZoSDIei6eQD:-LiKd_7N2-HQFMvooyWv:bqanq2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_test.go#L105)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

perhaps the benchmark should be adjusted so there is also some chance that some values are null.

the pattern i went with in https://github.com/cockroachdb/cockroach/pull/38422 was to benchmark with two values of `nullProbability` (0 and 0.3). the performance characteristics do differ, but i am not certain if that justifies running the benchmark a second time. what do you think?
</blockquote></details>

Yeah, I should add nulls here. It's not exactly a probability because there can only be nulls at the beginning, but I can add some percentage of nulls.
___
*[pkg/sql/exec/distinct_tmpl.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKXGhEBBoR96oQyfr1:-LiKeJEH0CYWS8TEOuWc:b-qxg95y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L184)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this if-block may not be necessary; you should be able to do `nulls := vec.Nulls()` at the beginning of the `if !p.foundFirstNonNullRow` block.

i think this suggestion is mostly just a matter of style, but IMO it makes it a little easier to read since `nulls` is only used inside the if-block below
</blockquote></details>

I think this is not quite equivalent. It's possible for a vector to have a null bitmap with no null bits set. In that case, `vec.HasNulls()` would be non-nil but `vec.HasNulls()` would be false, so we could still skip null checks.

But... it should be a minuscule performance difference since we'll discover a non-null value immediately, so probably better to go for readability like you suggest.
___
*[pkg/sql/exec/distinct_tmpl.go, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKYc4z6lAM4-HAL-2a:-LiKfdAM32mK50iLX29c:bwmmdf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L197)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

you might be able to avoid entering the `if !p.foundFirstNonNullRow` block later if you set `p.foundFirstNonNullRow = !vec.HasNulls()` right here
</blockquote></details>

Yeah, I went back and forth on this. It lets you skip the next block, but you also have to duplicate the logic for setting `lastVal`, `outputCol[i]`, and `startIdx`. I'll see how much of a difference it makes in the benchmark.
___
*[pkg/sql/exec/distinct_tmpl.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKVpFUD56IYubd6eNa:-LiKhEQn-UQkby0u26SH:b-jargaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L219)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> `for startIdx < n`

i think you can eliminate a bounds check here by doing `for range col[:n]` instead
</blockquote></details>

Yup I might as well. I didn't worry too much about this because the bounds check happens exactly once, not once per row.
___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKhr6v04A3SPERq-SG:bameont) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

to be more clear, what i meant to say is that such a function is beyond the scope of this PR, but i'm curious to hear your thoughts about it
</blockquote></details>

Good idea. Though my guess is it would actually be slower on average because it's hard for the existing nulls implementation to know if it has all nulls without examining the null bitmap. So you would end up doing extra work whenever `AllNulls()` is false, which seems like the typical case.


<!-- Sent from Reviewable.io -->

2019-06-26 21:51 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKl-iUB5UAQb2-62Fv:b-hsym92) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Good idea. Though my guess is it would actually be slower on average because it's hard for the existing nulls implementation to know if it has all nulls without examining the null bitmap. So you would end up doing extra work whenever `AllNulls()` is false, which seems like the typical case.
</blockquote></details>

I wonder if we should add 2 more bits to the `Nulls` implementation, one for all nulls and one for no nulls. Would that help anything?


<!-- Sent from Reviewable.io -->

2019-06-26 21:55 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKlc-N6oTueAGbAwOR:btzscak) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I wonder if we should add 2 more bits to the `Nulls` implementation, one for all nulls and one for no nulls. Would that help anything?
</blockquote></details>

I think to do it correctly you need to keep a running count of how many nulls there are, and every time you set a bit to null (or not-null) you have to first check the existing state so you know whether the count should change. Maybe this is worth the overhead though.


<!-- Sent from Reviewable.io -->

2019-06-26 21:58 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/distinct_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKn0620dl_grBoOite:-LiKn0620dl_grBoOitf:b-rxfejr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_test.go#L34)):*
> ```Go
> 			colTypes:     []types.T{types.Float64, types.Int64, types.Bytes},
> 			numCols:      4,
> 			tuples: tuples{
> ```

maybe add an all-null case?
___
*[pkg/sql/exec/distinct_tmpl.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKXGhEBBoR96oQyfr1:-LiKmijC5wOUWps-9G4n:b99pgi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L184)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think this is not quite equivalent. It's possible for a vector to have a null bitmap with no null bits set. In that case, `vec.HasNulls()` would be non-nil but `vec.HasNulls()` would be false, so we could still skip null checks.

But... it should be a minuscule performance difference since we'll discover a non-null value immediately, so probably better to go for readability like you suggest.
</blockquote></details>

i didn't consider that. however, i think that if you take the line 197 suggestion, then that extra performance hit won't happen
___
*[pkg/sql/exec/distinct_tmpl.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKVpFUD56IYubd6eNa:-LiKmXSi5cxszKj9STDd:b-mfjr3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L219)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Yup I might as well. I didn't worry too much about this because the bounds check happens exactly once, not once per row.
</blockquote></details>

shouldn't the bounds check happen once per each null row?
___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKm1IJ46lGToBRBHfD:bc5nge5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think to do it correctly you need to keep a running count of how many nulls there are, and every time you set a bit to null (or not-null) you have to first check the existing state so you know whether the count should change. Maybe this is worth the overhead though.
</blockquote></details>

the `Nulls` struct already has a `hasNulls bool` field, so we could add an `allNulls bool` if we wanted i suppose. it still seems kind of annoying though since we would have to add logic to check if we need to flip `allNulls` in every call to `SetNull(i)`


<!-- Sent from Reviewable.io -->

2019-06-26 22:17 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKn9Yj4eeNvMcv56Kl:-LiKn9Yj4eeNvMcv56Km:b663mw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L204)):*
> ```Go
> 	lastVal := p.lastVal
> 	if !p.foundFirstNonNullRow {
> 		// Nulls sort first, so advance startIdx until we find the first non-null
> ```

I'm afraid to say that I don't think this is true, for 2 reasons.

1. descending indexes. for example:
```
root@127.0.0.1:55040/defaultdb> create table a (a int, index (a desc));
root@127.0.0.1:55040/defaultdb> insert into a values(1), (null);
root@127.0.0.1:55040/defaultdb> select distinct a from a@a_a_idx;
   a
+------+
     1
  NULL
```
2. I believe we use this operator in cases where the input is only partitioned, and not sorted. I think the merge joiner and window function partitioner both do this, but it would be worth double checking.
___
*[pkg/sql/exec/distinct_tmpl.go, line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKalC5BqIs6f4O_LJb:-LiKmVcBAN0LJCArlzzJ:bgm0l5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L227)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think to do it correctly you need to keep a running count of how many nulls there are, and every time you set a bit to null (or not-null) you have to first check the existing state so you know whether the count should change. Maybe this is worth the overhead though.
</blockquote></details>

Oh yeah, good point. I'm not sure about that. Seems like a good amount of work, too, unless there was a compare-and-swap-y way of doing it.


<!-- Sent from Reviewable.io -->

2019-06-27 02:56 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKn9Yj4eeNvMcv56Kl:-LiLp6fB1FVyeC4qfn6g:b-r5vpt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L204)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm afraid to say that I don't think this is true, for 2 reasons.

1. descending indexes. for example:
```
root@127.0.0.1:55040/defaultdb> create table a (a int, index (a desc));
root@127.0.0.1:55040/defaultdb> insert into a values(1), (null);
root@127.0.0.1:55040/defaultdb> select distinct a from a@a_a_idx;
   a
+------+
     1
  NULL
```
2. I believe we use this operator in cases where the input is only partitioned, and not sorted. I think the merge joiner and window function partitioner both do this, but it would be worth double checking.
</blockquote></details>

😐

Thanks. For some reason I had it in my head that nulls sort first in both directions but obviously you're right. Also was not aware of #2. I'll adjust to handle nulls in any position.


<!-- Sent from Reviewable.io -->

2019-06-27 03:44 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38464)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/distinct_tmpl.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38464#-LiKn9Yj4eeNvMcv56Kl:-LiM0pTQAFznHaJnYbQe:b-e40kj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5890872d5f10085e354239d15db7ab54b5a030b4/pkg/sql/exec/distinct_tmpl.go#L204)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

😐

Thanks. For some reason I had it in my head that nulls sort first in both directions but obviously you're right. Also was not aware of #2. I'll adjust to handle nulls in any position.
</blockquote></details>

Yes, Jordan is correct about #2 on both merge joiner and window partitioner.


<!-- Sent from Reviewable.io -->

2019-06-27 21:13 UTC, solongordon commented
Closing this in favor of a new PR since the new implementation is sufficiently different.

2019-06-27 21:13 UTC, closed without merging