storage: batch command application
cockroachdb/cockroach pull request #38568
Opened 2019-06-28 22:54 UTC by ajwerner

This commit batches raft command application where possible. The basic
approach is to notice that many commands only "trivially" update the
replica state machine. Trivial commands can be processed in a single
batch by acting on a copy of the replica state. Non-trivial commands
share the same logic but always commit alone as they for one reason or
another rely on having a view of the replica or storage engine as of a
specific log index.

This commit also sneaks in another optimization which batching enables.
Each command mutates a portion of replica state called the applied state
which tracks a combination of the log index which has been applied and the
MVCC stats of the range as of that application. Before this change each
entry would update this applied state and each of those writes will end up
in the WAL, mem-table, and L0 just the be compacted away in L1. Now that
commands are being applied to the storage engine in a single batch it is easy
to only update the applied state for the last entry in the batch.

For sequential writes this patch shows a considerable performance win. The below
benchmark was run on a 3-node c5d.4xlarge (16 vCPU) cluster with concurrency 64.

```
name            old ops/s   new ops/s   delta
KV0-throughput  20.2k ± 1%  25.2k ± 1%  +24.94%  (p=0.029 n=4+4)

name            old ms/s    new ms/s    delta
KV0-P50          4.45 ± 8%   3.70 ± 5%  -16.85%  (p=0.029 n=4+4)
KV0-Avg          3.10 ± 0%   2.50 ± 0%  -19.35%  (p=0.029 n=4+4)
```

Due to the re-organization of logic in the change, the Replica.mu does not need
to be acquired as many times during the application of a batch. In the common
case it is now acquired exactly twice in the process of applying a batch whereas
before it was acquired more than twice per entry. This should hopefully improve
performance on large machines which experience mutex contention for a single
range.

This effect is likely visible in the below benchmark running KV95 on the same
nodes but with a small number of splits (2) and load-based splitting disabled:

```
name             old ops/s   new ops/s   delta
KV95-throughput  76.8k ±10%  86.3k ± 1%  +12.41%  (p=0.029 n=4+4)

name             old ms/s    new ms/s    delta
KV95-P50          5.25 ±10%   4.50 ± 0%  -14.29%  (p=0.029 n=4+4)
KV95-Avg          1.12 ±16%   1.00 ± 0%     ~     (p=0.429 n=4+4)
```

Fixes #37426.

Release note (performance improvement): Batch raft entry application and
elide writes to applied state for the batch.

2019-06-28 22:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38568)
<!-- Reviewable:end -->

2019-07-01 20:52 UTC, ajwerner commented
In the initial version of this revision I had been accidentally stepping the raft machine for each entry (instead of just conf changes). This was remedied early on but I hadn't re-run the benchmarks. They have now been updated to show a solid 48% throughput win on KV0/seq=true.

I'm sure there's more commentary to add to this PR and I'm sure I've made some things stale but on the whole it's a pretty exciting win.

2019-07-03 02:14 UTC, nvb reviewed
Very cool!

> Before this change each entry would update this applied state and each of those writes will end up
in the WAL, mem-table, and L0 just the be compacted away in L1

My understanding was that they would be collapsed when compacting from the mem-table to L0, not from L0 to L1. Am I confused?

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LipJXqo5hLS40fPzybG:bh9fruk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/application_state_buf.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipanVr44AhyMon5XDc:-LipanVr44AhyMon5XDd:bb5ned2) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/application_state_buf.go#L21)):*
> ```Go
> // applicationStateBufNode.
> // TODO(ajwerner): justify this number.
> const applicationStateBufSize = 8
> ```

s/applicationStateBufSize/applicationStateBufChunkSize/
___
*[pkg/storage/replica_application.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDKaX0QvnRQqISWgN:-LiiDKaX0QvnRQqISWgO:b-z1kw7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L37)):*
> ```Go
> )
> 
> // applicationState stores the state required to apply an entry to a
> ```

s/an entry/a single entry/
___
*[pkg/storage/replica_application.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiCwWz62esDlYdWlEi:-LiiCwWz62esDlYdWlEj:b-jkyls3) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L39)):*
> ```Go
> // applicationState stores the state required to apply an entry to a
> // replica. The state is accumulated in stages which occur in
> // Replica.handleCommittedEntriesRaftMuLocked. From a high level, a command is
> ```

Enumerating the steps here would be helpful. Or maybe add a bit of pseudo code like we have in #37426.
___
*[pkg/storage/replica_application.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipQJCqBUGiJekbxmgo:-LipQJCqBUGiJekbxmgp:b-9rnrxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L46)):*
> ```Go
> // Then the batch is committed, the side-effects are applied and the local
> // result is processed.
> type applicationState struct {
> ```

nit: something about the name `applicationState` seems particularly overloaded to me in the world of computer science. I know you're using "application" to mean Raft entry application, but it still jumps out at me after reviewing this entire PR. It also doesn't do a good job conveying that this is per-entry state and nothing more. Did you consider any other names? Maybe:
- `entryApplication`
- `entryApplicationState`
- `entAppliedState`
- `entAppState`
___
*[pkg/storage/replica_application.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDRex66LbX4uS9kWv:-LiiDRex66LbX4uS9kWw:b2niczw) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L50)):*
> ```Go
> 	// proposal's context if this entry was proposed locally.
> 	ctx context.Context
> 	// e is th Entry being applied.
> ```

the
___
*[pkg/storage/replica_application.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipRwQj-yBzTP5BeHdo:-LipRwQj-yBzTP5BeHdp:bux5mqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L54)):*
> ```Go
> 
> 	// The below fields are decoded from e.
> ```

Remove this line so that it's clear that you're just referring to this group of four fields.

I do like that you added this comment and grouped the fields like this though. It would be helpful to a reader of this code if all of the groups of fields were commented as well. For instance, the next group would be `// The below fields are populated on the proposing Replica only and come from the Replica's proposal map.`
___
*[pkg/storage/replica_application.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDXV8-De0XiyiW6AB:-LiiDXV8-De0XiyiW6AC:baw0cv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L60)):*
> ```Go
> 	ccCtx   ConfChangeContext // only populated for conf changes
> 
> 	proposedLocally bool
> ```

Consider making this a method to reduce the footprint of the `applicationStateBuf`.
___
*[pkg/storage/replica_application.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDkv13uRaiEo5p_bA:-LiiDkv23zOPg-Shmpqy:b-lyvbvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L67)):*
> ```Go
> 
> 	leaseIndex uint64
> 	lResult    *result.LocalResult
> ```

nit: s/lResult/localResult/
___
*[pkg/storage/replica_application.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipTORp3z3w-CXL2GOU:-LipTORp3z3w-CXL2GOV:bu4j6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L81)):*
> ```Go
> // At the time of writing it is possible that the current conditions are too
> // strict but they are certainly sufficient.
> func isTrivial(usingStateAppliedKey bool, r *storagepb.ReplicatedEvalResult) bool {
> ```

nit: move the `*storagepb.ReplicatedEvalResult` up because that's the more important argument.
___
*[pkg/storage/replica_application.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipTZZP8fy5itaxj_gW:-LipTZZP8fy5itaxj_gX:bnqzek) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L94)):*
> ```Go
> 				r.State.Lease == nil &&
> 				r.State.Desc == nil &&
> 				(usingStateAppliedKey || !r.State.UsingAppliedStateKey)))
> ```

I would have expected this to be `(!usingStateAppliedKey || r.State.UsingAppliedStateKey)`. That's the condition where we upgrade to using the applied state key, right?

Also, it would almost certainly be ok to consider all commands during the applied state key upgrade non-trivial if that simplifies the code. I think that would allow us to get rid of the `usingStateAppliedKey` arg.
___
*[pkg/storage/replica_application.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiFQDp9-RF3mTV5YPQ:-LiiFQDp9-RF3mTV5YPR:b-kc8f5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L102)):*
> ```Go
> }
> 
> // decode decodes s.e into the other fields of s.
> ```

It seems like this could be merged with `initialize` to simplify the usage of `applicationState`.
___
*[pkg/storage/replica_application.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Liibigp40lN0NSJJHl2:-Liibigp40lN0NSJJHl3:b-m8koa) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L149)):*
> ```Go
> // commands. Committed raft commands are applied to the batch in a multi-stage
> // process whereby individual commands are decoded, prepared for application
> // relative to the current view of replicaState.
> ```

This sentence seemed to end abruptly.
___
*[pkg/storage/replica_application.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipSz2f8Ycsupw5_1w2:-LipSz2f8Ycsupw5_1w3:b-2kbeyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L154)):*
> ```Go
> 	stats [...]

2019-07-04 16:27 UTC, ajwerner reviewed
TFTR! Sorry for the mess

> My understanding was that they would be collapsed when compacting from the mem-table to L0, not from L0 to L1. Am I confused?

You are correct, I was incorrect. Wishful thinking. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LipnP8LCVahaphiICWJ:bbsb5xn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/application_state_buf.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipanVr44AhyMon5XDc:-LitCKMQ5NAZMutqROKg:brlg7m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/application_state_buf.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/applicationStateBufSize/applicationStateBufChunkSize/
</blockquote></details>

Went with `entryApplicationStateBufNodeSize`
___
*[pkg/storage/replica_application.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDKaX0QvnRQqISWgN:-LitCPdw1k4gSCqlWKd3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/an entry/a single entry/
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiCwWz62esDlYdWlEi:-Lit9k_LB3p1dv4AblIe:b-yf94xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Enumerating the steps here would be helpful. Or maybe add a bit of pseudo code like we have in #37426.
</blockquote></details>

I added the pseudocode to handleCommittedEntriesRaftMuLocked, 
___
*[pkg/storage/replica_application.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipQJCqBUGiJekbxmgo:-LipoubO9PRDhO67hPZC:b-qwtdeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L46)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: something about the name `applicationState` seems particularly overloaded to me in the world of computer science. I know you're using "application" to mean Raft entry application, but it still jumps out at me after reviewing this entire PR. It also doesn't do a good job conveying that this is per-entry state and nothing more. Did you consider any other names? Maybe:
- `entryApplication`
- `entryApplicationState`
- `entAppliedState`
- `entAppState`
</blockquote></details>

It was all `entryApplication...` and then I did a big `s/entryApplication/application/g` though I clearly even typed some layer and missed `(put|get)EntryApplicationBatch`. I wasn't happy with either of them but I'm happy to go back. 
___
*[pkg/storage/replica_application.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipRwQj-yBzTP5BeHdo:-LisNwl32ubCQ-TAm19b:b6ptfo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Remove this line so that it's clear that you're just referring to this group of four fields.

I do like that you added this comment and grouped the fields like this though. It would be helpful to a reader of this code if all of the groups of fields were commented as well. For instance, the next group would be `// The below fields are populated on the proposing Replica only and come from the Replica's proposal map.`
</blockquote></details>

Added more structure and comments here generally.
___
*[pkg/storage/replica_application.go, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDXV8-De0XiyiW6AB:-LisO-gY7srFSI3hD48I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L60)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider making this a method to reduce the footprint of the `applicationStateBuf`.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiDkv13uRaiEo5p_bA:-LisQCJo3MwW05TaW7Zv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: s/lResult/localResult/
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipTORp3z3w-CXL2GOU:-LitCIqfEpkY3589k22k:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L81)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move the `*storagepb.ReplicatedEvalResult` up because that's the more important argument.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipTZZP8fy5itaxj_gW:-LisQEWn8BByDKzElG1s:b9l0w4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L94)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would have expected this to be `(!usingStateAppliedKey || r.State.UsingAppliedStateKey)`. That's the condition where we upgrade to using the applied state key, right?

Also, it would almost certainly be ok to consider all commands during the applied state key upgrade non-trivial if that simplifies the code. I think that would allow us to get rid of the `usingStateAppliedKey` arg.
</blockquote></details>

I added a comment. This logic does consider the upgrade to be non-trivial. It just considers not upgrading to be trivial. 
___
*[pkg/storage/replica_application.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LiiFQDp9-RF3mTV5YPQ:-LisQndL46zXSqDM9U53:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L102)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems like this could be merged with `initialize` to simplify the usage of `applicationState`.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Liibigp40lN0NSJJHl2:-Lit8tskBkoVJUQpoz7b:buvj6o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This sentence seemed to end abruptly.
</blockquote></details>

It does indeed. Fixed.
___
*[pkg/storage/replica_application.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipSz2f8Ycsupw5_1w2:-LisSADH2nd137I4KgxT:be17bc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote> [...]

2019-07-08 18:14 UTC, nvb reviewed
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/entry_application_state_buf.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHmWCb3r1rsKK_EgQT:-LjHmWCb3r1rsKK_EgQU:b-kkk6kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/entry_application_state_buf.go#L90)):*
> ```Go
> }
> 
> // entryApplicationStateRingBuf is a ring-buffer of entryApplicationState.
> ```

The ring-buffer structure here isn't necessary anymore. Should we keep it at the cost of added complexity? I think we can get rid of the entire `entryApplicationStateRingBuf` type if we want.
___
*[pkg/storage/replica_application.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipSz2f8Ycsupw5_1w2:-LjHZ50w0CBZn_mUo0QI:b-sxrw91) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L154)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why not? Their side-effect should coalesce nicely and is handled to just take latest one. I was mostly motivated by this comment:

```
		// Raft log truncation is too frequent to justify a replica state
		// assertion.
```
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/replica_proposal.go#L593-L594

We did discuss this offline and I'm open to making this change but will at least defer it to the next revision.
</blockquote></details>

We discussed this offline. The conclusion was that unlike all of the other side-effects, this one modifies the write batch directly so it doesn't fit into the trivial/non-trivial split. I wonder whether that's worth changing to simplify this code structure. If not, we should add a comment explaining why this is different than all of the other non-trivial side effects.
___
*[pkg/storage/replica_application.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipZ6eY4PJ6ecLxKgsC:-LjHlTK_4tBQA0DepalI:b7owsmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L356)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I did, there is code downstream of this which assumes that rResult hasn't been modified. I could re-work it but for now this seems easier. If after the next pass we think it's worth the change I can do it. Namely in finishRaftCommand there are some assertions and then also when looking to decide whether we aborted the config change. 
</blockquote></details>

Yeah I'd like to come back to this, but it can wait until everything else settles down.
___
*[pkg/storage/replica_application.go, line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipKMWg-NVlvByIK9zz:-LjHcM5G0n5eUjiF2zc_:bdu5b1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L485)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Much better, thanks.
___
*[pkg/storage/replica_application.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipZQqv0ozhftKDZGn0:-LjHbht6AuH8U2-QYcui:bks4i8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1047)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`prepareLocalResultis` missing a space
___
*[pkg/storage/replica_application.go, line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lip_aM_DETJbikTvSok:-LjHc-_Y4X3XeTEeNtmz:bbqvykj) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1173)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is old logic where this returned straight up to the loop in handleRaftReady. I've now hauled the check up. 
</blockquote></details>

Looks like we're still returning this though.
___
*[pkg/storage/replica_application.go, line 1235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lipa1p5BY2p3mEwmxTo:-LjHhISA7UQiU2Yr1-23:b-2hiaef) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1235)):*
>I did try just sharing a single batch.Distinct() after implementing the ApplyBatchRepr method on the distinctBatch because it seemed easier to try it than to read the code to figure out if anybody does any reads below here. It showed a win but failed a server test, I figured I could go explore that later.

That might be because some non-trivial entries need to read from the current batch. It seems worthwhile to explore this at some point.
___
*[pkg/storage/replica_application.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHI2m-C_GsxvPGKPii:-LjHI2m-C_GsxvPGKPij:b3m8tmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L53)):*
> ```Go
> // The pseudocode looks like:
> //
> //   while entries:
> ```

Thanks for this, it's great!
___
*[pkg/storage/replica_application.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHIgWt7BhtpIMEVW0r:-LjHIgWt7BhtpIMEVW0s:b-paco9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L80)):*
> ```Go
> 	ctx context.Context,
> 	committedEntries []raftpb.Entry,
> 	stats *handleRaftReadyStats,
> ```

I just noticed that this stats object only contains information about entry application at the moment. How do you feel about lifting it into here entirely? That prevents us from adding non-application related stats, so maybe that's not ideal. If not, how do you feel about creating a `handleCommittedEntriesStats` object and returning it from here?
___
*[pkg/storage/replica_application.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHeorH4deoTzZUiNwE:-LjHeorH4deoTzZUiNwF:b-2whh78) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L310)):*
> ```Go
> 		// values) here. If the key range we are ingesting into isn't empty,
> 		// we're not using AddSSTable but a plain WriteBatch.
> 		if s.rResult().AddSSTable != nil {
> ```

Do you mind verifying that each of these pre-apply effects still work correctly now that we allow trivial entries to proceed a non-trivial entry? I think the only change we'll need to make is to adjust `preDestroyRaftMuLocked` to use the current batch instead of `tmpBatch`, but it would be nice to verify all of them.
___
*[pkg/storage/replica_application.go, line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHhzCeEuVVucXmP6ji:-LjHhzCf9tsM_fuQCEzx:bgbardk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L718)):*
> ```Go
> // not modify rResult in order to give the TestingPostApplyFilter testing knob
> // an opportunity to inspect the command's ReplicatedEvalResult.
> func applyTrivialReplicatedEvalResult(
> ```

Should this be `stageTrivialReplicatedEvalResult` because it's not modifying the real replicated state?
___
*[pkg/storage/replica_application.go, line 741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHiaDd-3u6bV9CcUuN:-LjHiaDd-3u6bV9CcUuO:b-larryp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L741)):*
> ```
> Up [...]

2019-07-08 19:20 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/replica_application.go, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipVn9s5sW2EAkI-5k9:-LjI0mAP2qH6VdaNDs2e:b26ldah) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L537)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I just inlined the closure as it wasn't providing a lot of additional clarity. 
</blockquote></details>

s/retreive/retrieve/


<!-- Sent from Reviewable.io -->

2019-07-08 19:45 UTC, ajwerner reviewed
Thanks for the review. This is getting there. The biggest outstanding thing is the `preDestroyRaftMuLocked` comment. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjI608w5ZlpJaCUYdHF:bxazero)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/entry_application_state_buf.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHmWCb3r1rsKK_EgQT:-LjHpnVN4XgehAfeqXco:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/entry_application_state_buf.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The ring-buffer structure here isn't necessary anymore. Should we keep it at the cost of added complexity? I think we can get rid of the entire `entryApplicationStateRingBuf` type if we want.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipSz2f8Ycsupw5_1w2:-LjHzFp93rHvVGTCnQQw:b21x5vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We discussed this offline. The conclusion was that unlike all of the other side-effects, this one modifies the write batch directly so it doesn't fit into the trivial/non-trivial split. I wonder whether that's worth changing to simplify this code structure. If not, we should add a comment explaining why this is different than all of the other non-trivial side effects.
</blockquote></details>

Another point is that truncated state side-effects don't have a trigger that needs to view the replica's in-memory state. The fact that the command touches ReplicaState doesn't make it non-trivial per se. All commands update the MVCCStats and lease applied index. 

Anyway, added more commentary and a TODO
___
*[pkg/storage/replica_application.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipZ6eY4PJ6ecLxKgsC:-LjI00Hu--H2eXIP9Lkb:b-ml3wwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L356)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah I'd like to come back to this, but it can wait until everything else settles down.
</blockquote></details>

Okay, I've cleaned this up a tad more. 
___
*[pkg/storage/replica_application.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipZQqv0ozhftKDZGn0:-LjHtlJ029rw64TW9dg2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1047)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`prepareLocalResultis` missing a space
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 1173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lip_aM_DETJbikTvSok:-LjHtt14A3vf6hq5Onft:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1173)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we're still returning this though.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 1235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lipa1p5BY2p3mEwmxTo:-LjHu36UATnAECmO-91B:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L1235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

>I did try just sharing a single batch.Distinct() after implementing the ApplyBatchRepr method on the distinctBatch because it seemed easier to try it than to read the code to figure out if anybody does any reads below here. It showed a win but failed a server test, I figured I could go explore that later.

That might be because some non-trivial entries need to read from the current batch. It seems worthwhile to explore this at some point.
</blockquote></details>

Ack.
___
*[pkg/storage/replica_application.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHIgWt7BhtpIMEVW0r:-LjHxfMv0PetvgA48ZZ0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L80)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I just noticed that this stats object only contains information about entry application at the moment. How do you feel about lifting it into here entirely? That prevents us from adding non-application related stats, so maybe that's not ideal. If not, how do you feel about creating a `handleCommittedEntriesStats` object and returning it from here?
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjI3SFY7LTsP1cdKFNO:-LjI3SFY7LTsP1cdKFNP:bqmdf6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L288)):*
> ```Go
> 		}
> 
> 		// Update the node clock with the serviced request. This maintains
> ```

This can get coalesced per batch right? I've added a TODO
___
*[pkg/storage/replica_application.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHeorH4deoTzZUiNwE:-LjI1QxBAkdVeDtdzgUS:bbsu92p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L310)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind verifying that each of these pre-apply effects still work correctly now that we allow trivial entries to proceed a non-trivial entry? I think the only change we'll need to make is to adjust `preDestroyRaftMuLocked` to use the current batch instead of `tmpBatch`, but it would be nice to verify all of them.
</blockquote></details>

This is actually tricky for the preDestroyRaftMuLocked case. The old logic applies the current entry's writeBatch to the tmpBatch. When this is called we haven't yet written the current entry's writeBatch to the batch. In order to give an equivalent view we'd need to create another tmpBatch and write the current batch's repr into it and then write this writeBatch's repr into it. That sounds rather expensive. We may want to rework this entirely. 

As for split's use of tmpBatch, I think it's safe and added a comment. 

The other checks I believe are safe because they only access fields on the replica updated by non-trivial commands.
___
*[pkg/storage/replica_application.go, line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHhzCeEuVVucXmP6ji:-LjHqWGp6Lyd2XVa7Y-I:bdo7wlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L718)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be `stageTrivialReplicatedEvalResult` because it's not modifying the real replicated state?
</blockquote></details>

Done. Also fixed some grammar.
___
*[pkg/storage/replica_application.go, line 741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHiaDd-3u6bV9CcUuN:-LjHqxZ5Bsyo0J49C1_U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc683 [...]

2019-07-08 19:50 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application.go, line 537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LipVn9s5sW2EAkI-5k9:-LjI7ede2vgSYn40QMwl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/006f72e7eb005887c96f4c54d9868d5a7622698c/pkg/storage/replica_application.go#L537)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/retreive/retrieve/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-08 21:25 UTC, nvb reviewed
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/entry_application_state_buf.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjIOSiC7u9Ol3MIyMa5:-LjIOSiDDGzi7onyLklF:byng249) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cf2b4ce26eababb5e2687831687098628ceb2f/pkg/storage/entry_application_state_buf.go#L34)):*
> ```Go
> }
> 
> // entryApplicationStateRingBuf is a ring-buffer of entryApplicationState.
> ```

This comment is wrong.
___
*[pkg/storage/replica_application.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjI3SFY7LTsP1cdKFNO:-LjIOo_Q4H0-sgPZq_r_:bq9o4ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L288)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This can get coalesced per batch right? I've added a TODO
</blockquote></details>

Yes, although I think it needs to happen before we ack requests, so the early acknowledgment change will need to be careful about this.
___
*[pkg/storage/replica_application.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHeorH4deoTzZUiNwE:-LjITN9aEXxvEA5r1hfk:b-x37k47) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L310)):*
> We may want to rework this entirely.

What did you have in mind? I wonder if we could clear the batch completely.
___
*[pkg/storage/replica_application.go, line 826 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHjJjk2Natd8fSTLla:-LjISNos9TvW9UcZmVG5:b-ka8u1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L826)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not sure I totally follow what you mean w/ regards to marking each entry's RaftLogDelta as 0. I believe that logic remains the same. This last call here is about making sure that the change in the raft log size due to sideloaded commands is properly reflected. One source of confusion was the name `truncationDelta` which is actually the bytes removed by truncating the sideloaded entries. I've renamed the variable for clarity.

Do you have more concerns?
</blockquote></details>

Oh, I see. Ok that makes sense.
___
*[pkg/storage/replica_application.go, line 1250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHKsT9Cnky41b-EHpT:-LjIPhI-6Hn2d8qZqXqF:b4of8tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L1250)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not for this change, but we could clean some of this `(errExp, expl)` stuff up with an error wrapper type and the new `errors.As` style.

https://github.com/cockroachdb/errors#providing-pii-free-details discusses a `errors.WithSafeDetails` function, which might be exactly what we want.

I'd leave a TODO.
___
*[pkg/storage/replica_application.go, line 1363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjH_XsCBXszV3P_wQjt:-LjISbU9C0SxhMvl5haS:b-5diox) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L1363)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Updated somewhat though I'm not sure I see how the`A result is fundamentally considered "trivial" if it does ...` sentence is off? 
</blockquote></details>

It looks good now.


<!-- Sent from Reviewable.io -->

2019-07-08 21:58 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/entry_application_state_buf.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjIOSiC7u9Ol3MIyMa5:-LjIZXfUEgyPFOFtW0kf:b-revvgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/27cf2b4ce26eababb5e2687831687098628ceb2f/pkg/storage/entry_application_state_buf.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment is wrong.
</blockquote></details>

Fixed. Also just inlined all the Node methods into the buf itself. I don't think they added much now that the data structure is so much simpler. 
___
*[pkg/storage/replica_application.go, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjI3SFY7LTsP1cdKFNO:-LjIUJ5z2Gl8HBF4kgrD:b-rxqfai) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L288)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, although I think it needs to happen before we ack requests, so the early acknowledgment change will need to be careful about this.
</blockquote></details>

Sure, it can be done immediately after decoding a batch. 
___
*[pkg/storage/replica_application.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHeorH4deoTzZUiNwE:-LjIV5JMDDLGXL0yLGIN:bqxc6of) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L310)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> We may want to rework this entirely.

What did you have in mind? I wonder if we could clear the batch completely.
</blockquote></details>

This code seems to only read from the batch to determine if it's going to delete enough keys to warrant a range deletion tombstone (https://sourcegraph.com/github.com/cockroachdb/cockroach/-/blob/pkg/storage/replica_raftstorage.go#L665). I was going to suggest we make this heuristic more explicit at this level and see if we can find some other indication, perhaps combining the existing heuristic with an MVCCStats delta. 

On second thought it seems like it's probably okay to base the heuristic on the state of the range prior to this write batch (your initial suggestion) and add more comments. It's not clear to me how important it is to also observe the writes of this batch to the range. Thoughts?
___
*[pkg/storage/replica_application.go, line 1250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHKsT9Cnky41b-EHpT:-LjIY7Y_8dxgGoy7Mukk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L1250)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not for this change, but we could clean some of this `(errExp, expl)` stuff up with an error wrapper type and the new `errors.As` style.

https://github.com/cockroachdb/errors#providing-pii-free-details discusses a `errors.WithSafeDetails` function, which might be exactly what we want.

I'd leave a TODO.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-08 22:34 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_application.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjHeorH4deoTzZUiNwE:-LjIhxud61d9TtfpNhjD:bir42x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b65d72c5dd9d139c2bddc68344c9676389039097/pkg/storage/replica_application.go#L310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This code seems to only read from the batch to determine if it's going to delete enough keys to warrant a range deletion tombstone (https://sourcegraph.com/github.com/cockroachdb/cockroach/-/blob/pkg/storage/replica_raftstorage.go#L665). I was going to suggest we make this heuristic more explicit at this level and see if we can find some other indication, perhaps combining the existing heuristic with an MVCCStats delta. 

On second thought it seems like it's probably okay to base the heuristic on the state of the range prior to this write batch (your initial suggestion) and add more comments. It's not clear to me how important it is to also observe the writes of this batch to the range. Thoughts?
</blockquote></details>

Discussed offline. These state updates need to be atomic with the batch but they don't need to necessarily be part of the writeBatch that comes with the command. I moved the application of the entry's writeBatch up to precede these preapply calls. It all seems to work and avoids the inefficiency of the tmpBatch. 


<!-- Sent from Reviewable.io -->

2019-07-09 14:46 UTC, nvb approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjMBgnN5FBes0zO9Ql3:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-07-09 15:46 UTC, tbg commented
Just chatted with @nvanbenschoten and I'll also give this a full review. Won't get to it until tomorrow though.

2019-07-09 15:57 UTC, ajwerner commented
> Just chatted with @nvanbenschoten and I'll also give this a full review. Won't get to it until tomorrow though.

No rush and thanks!

2019-07-10 14:03 UTC, tbg requested changes
Phew, that was a chunk to get through but here I am.

The way you're structuring the batching is very well thought out and there's lots of good commentary that I'm sure wasn't there before. That is to say, even if this hadn't moved the needle on perf at all, it would have been worth it.

There's some code movement in this PR and perhaps reviewing would've been easier had you factored that out into a separate commit, but I know that this sort of thing constitutes a herculean feat in itself after a certain point, and not having the movement split out forced me to review more of the existing code in detail (again), which is good.

Still, obviously the change is quite complex and it's hard for me to come away from the PR feeling comfortable that everything is chipper. My most salient suggestion among all of the comments is that of being more conservative w.r.t what to batch: right now it's "stop batch when you see something nontrivial", I'd prefer moving to a "nontrivial gets their own batch" model. I think I also found a place (AddSSTable) in which the former is incorrect, but even if that were the case, we just shouldn't be batching anything that doesn't move the perf needle so that a) we get easier semantics and b) the mistakes we will certainly make in the future will be less likely to actually manifest in incorrect behavior, though I'd also like to see some testing for b) that strikes when we add side effects without updating the black/whitelists/the test.

A fair share of the comments I left in this PR don't need to be addressed in the PR itself, so whatever you feel like leaving out or punting (including to someone else), that's fine by me.

> Reviewed 1 of 7 files at r2, 1 of 6 files at r3, 1 of 2 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjR8uo92u2zvG8iuuzz:b4bto0z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/entry_application_state_buf.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQ_ZIu4a9EPU_Wnn-7:-LjQ_ZIu4a9EPU_Wnn-8:b-w46es7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L43)):*
> first
___
*[pkg/storage/entry_application_state_buf.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQfrWI08-nlMHeBBLB:-LjQfrWI08-nlMHeBBLC:bfifn9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L71)):*
> ```Go
> 		entryApplicationStateBufNodeSyncPool.Put(oldHead)
> 	}
> 	*buf.head = entryApplicationStateBufNode{}
> ```

I'm surprised that you keep one node around and manually remove it in `destroy()`, that feels icky. If there's a reason add a comment, otherwise simplify.
___
*[pkg/storage/entry_application_state_buf.go, line 85 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQgRl0DEsZOTdqG5_C:-LjQgRl0DEsZOTdqG5_D:bkuj66k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L85)):*
> ```Go
> 	*buf = entryApplicationStateBuf{}
> }
> ```

Add brief comments on all the things from here on down, and in particular on the return value of `init`.
___
*[pkg/storage/entry_application_state_buf.go, line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQh12P1OmSLHM7T2yu:-LjQh12P1OmSLHM7T2yv:bf85ioe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L91)):*
> ```Go
> 
> type entryApplicationStateBufIterator struct {
> 	idx    int32
> ```

Comment on idx and offset. Isn't `offset` just `idx % entryApplicationStateBufNodeSize`? If so consider simplifying, it'll be easier to understand with just one counter.
___
*[pkg/storage/replica_application.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQj5TnA5-03Hew4s08:-LjQj5TnA5-03Hew4s09:b2utcxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L38)):*
> ```Go
> 
> type handleCommittedEntriesStats struct {
> 	processed int
> ```

Is this commands or batches? We should be able to tell from these stats whether there's a frequent command that is breaking up these batches (i.e. isn't `isTrivial()`). The caller already knows how many commands there were (`len(committedEntries)` so we don't necessarily need that), but the number of batches is probably interesting, along with the number of nontrivial commands (which is mostly known from the number of batches, but not completely). At a high level it's worth keeping both because we want to be able to see batches/sec as well as whether there's a significant source of "batch breaker" commands.
___
*[pkg/storage/replica_application.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQixlv3obGCV1oN-xe:-LjQixlv3obGCV1oN-xf:bhkm7oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L71)):*
> stages:
___
*[pkg/storage/replica_application.go, line 77 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjiOmBAY6qh8fhwAM:-LjQjiOmBAY6qh8fhwAN:b8hwlzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L77)):*
> ```Go
> // reading the current replica state from underneath the Replica.mu and
> // determining whether any of the commands were proposed locally. Next each
> // command is written to the engine.Batch and have the "trivial" component of
> ```

s/have/has/
___
*[pkg/storage/replica_application.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjm4G1FRbliqcQ0U5:-LjQjm4G1FRbliqcQ0U6:b-u3bvib) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L78)):*
> ```Go
> // determining whether any of the commands were proposed locally. Next each
> // command is written to the engine.Batch and have the "trivial" component of
> // their ReplicatedEvalResult applied to the batch's view of the ReplicaState.
> ```

s/their/its/
___
*[pkg/storage/replica_application.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjszF3gslVWlLTUAW:-LjQjszF3gslVWlLTUAX:b-djjw0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L79)):*
> , its side effects on the Replica's state is applied, and the clients acked with the respective results.
___
*[pkg/storage/replica_application.go, line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjzjm4jWnUv6PKTDq:-LjQjzjm4jWnUv6PKTDr:b-aswcgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L80)):*
> ```Go
> // their ReplicatedEvalResult applied to the batch's view of the ReplicaState.
> // Finally the batch is written to the storage engine and its side effects on
> // the Replica's state are applied.
> ```

Good job on the comment!
___
*[pkg/storage/replica_application.go, line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQlApK1skmG02V7c_r:-LjQlApK1skmG02V7c_s:b-zg4ksh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L80)):*
> ```Go
> // their ReplicatedEvalResult applied to the batch's view of the ReplicaState.
> // Finally the batch is written to the storage engine and its side effects on
> // the Replica's state are applied.
> ```

Mention that errors from this method are fatal. (They still are, right)
___
*[pkg/storage/replica_application.go [...]

2019-07-10 14:03 UTC, tbg reviewed
Oh, and I meant to say: great work! Delighted with how this is all shaping up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjRBXEY9b0WC4unsCm7:b-uk8432)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2019-07-10 14:22 UTC, ajwerner commented
> Still, obviously the change is quite complex and it's hard for me to come away from the PR feeling comfortable that everything is chipper. My most salient suggestion among all of the comments is that of being more conservative w.r.t what to batch: right now it's "stop batch when you see something nontrivial", I'd prefer moving to a "nontrivial gets their own batch" model. I think I also found a place (AddSSTable) in which the former is incorrect, but even if that were the case, we just shouldn't be batching anything that doesn't move the perf needle so that a) we get easier semantics and b) the mistakes we will certainly make in the future will be less likely to actually manifest in incorrect behavior, though I'd also like to see some testing for b) that strikes when we add side effects without updating the black/whitelists/the test.

:) should have stopped and let you have a say before I went on polishing this. The initial version of this PR did exactly this, the buffer had a mechanism to store an extra entry as a sort of "lookahead".

From Nathan:
>I'm wondering if this is overly restrictive. My intuition would be that we could probably get away with having non-trivial commands be part of a batch as long as they are the last command in the batch. This construction would dramatically simplify the code structure here because it would turn the pushing and unpushing process into a simple process of: 1. batch as much as possible, 2: flush after each non-trivial command is added to the batch, 3. flush again at the end. It would also allow us to think of each batch as having n "trivial side effects" and one "complex side effect", which is easy to understand and to structure in the code. 

I'm happy to go back to the previous approach but let's reach consensus before I make the change.

2019-07-10 14:38 UTC, tbg commented
Heh, oops, sorry about that. @nvanbenschoten what do you think? I never saw the version of the code I suggested, you have, so see what you think about the safety argument. The `AddSSTable` thing would've probably slipped in had I not spent some time thinking about it, and maybe it would've never mattered in practice, but it just seems scary since we'll be using it more and more on "liver" data as time goes by.

2019-07-10 15:17 UTC, nvanbenschoten commented
The `AddSSTable` example you brought up does seem bad - nice catch. I don't think it would ever cause any issues in practice because above-Raft latches would protect us from ever mixing any entries that aren't allowed to commute, but it's concerning that entries would have the potential to no longer be atomic.

I think I'm ok with moving back to the "non-trivial entries must live alone" style, but I hope we don't regress to the lookahead mechanism we had before, along with the highly-specialized `entryApplicationStateBuf` interface to accommodate it. The goal with that approach was to avoid decoding entries multiple times, which is a nice property. What made it a little clunky is that we were trying to emplace into the `entryApplicationStateBuf` while decoding and could only determine whether the newly decoded entry was trivial after this. We'd then try to ignore the last entry in the buffer until coming back around the loop the next time.

I think we can do better by turning decoding into a two-stage process. We could first decode into a temporary `entryApplicationState` that's not part of the `entryApplicationStateBuf`. We then check whether this is trivial. If it is, we push it into the buffer and continue decoding. If not, we process the buffer as is, without the new entry. We then begin the loop by checking whether this entry is empty and pushing it into the buffer if not.

Getting the current style to work also allowed us to get rid of the `tmpBatch`s used in split and merge pre-apply hooks. I hope we can keep that change.

2019-07-10 15:37 UTC, ajwerner commented
> Getting the current style to work also allowed us to get rid of the tmpBatchs used in split and merge pre-apply hooks. I hope we can keep that change.

I think that this change is orthogonal. It raises a question about why the tmpBatch is there in the first place if we could avoid it by just applying the write batch first. 

> I think I'm ok with moving back to the "non-trivial entries must live alone" style, but I hope we don't regress to the lookahead mechanism we had before

Reasonable, let me see what I can do.

2019-07-10 22:55 UTC, ajwerner reviewed
Thanks for the review! I suspect there's at least one more round left to deal with my renaming choices and the triviality of log truncation. Maybe also some cleanup on `decodeBuf` and `decodedRaftEntry`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjT3WGe7coWEqwmSNHs:bxu7a10)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/entry_application_state_buf.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQ_ZIu4a9EPU_Wnn-7:-LjSJP-_1qnyv2SoClIS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L43)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> first
</blockquote></details>

Done.
___
*[pkg/storage/entry_application_state_buf.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQfrWI08-nlMHeBBLB:-LjSJWUk4djsJjZxP81Z:b-mr031e) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L71)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm surprised that you keep one node around and manually remove it in `destroy()`, that feels icky. If there's a reason add a comment, otherwise simplify.
</blockquote></details>

Done. This was a vestige from when the buf had a lookahead feature.
___
*[pkg/storage/entry_application_state_buf.go, line 85 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQgRl0DEsZOTdqG5_C:-LjSNMBB3bV1wKtXQ5xu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L85)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Add brief comments on all the things from here on down, and in particular on the return value of `init`.
</blockquote></details>

Done.
___
*[pkg/storage/entry_application_state_buf.go, line 91 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQh12P1OmSLHM7T2yu:-LjSJdMJ-tmoAEpIqWOt:b-aojbfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/entry_application_state_buf.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Comment on idx and offset. Isn't `offset` just `idx % entryApplicationStateBufNodeSize`? If so consider simplifying, it'll be easier to understand with just one counter.
</blockquote></details>

Done. A lot of this code got simpler over time, the nodes used to be ring buffers.
___
*[pkg/storage/replica_application.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQj5TnA5-03Hew4s08:-LjT-2VT0DEql75C_LKn:b-x985an) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L38)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is this commands or batches? We should be able to tell from these stats whether there's a frequent command that is breaking up these batches (i.e. isn't `isTrivial()`). The caller already knows how many commands there were (`len(committedEntries)` so we don't necessarily need that), but the number of batches is probably interesting, along with the number of nontrivial commands (which is mostly known from the number of batches, but not completely). At a high level it's worth keeping both because we want to be able to see batches/sec as well as whether there's a significant source of "batch breaker" commands.
</blockquote></details>

Added more fields. 
___
*[pkg/storage/replica_application.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQixlv3obGCV1oN-xe:-LjSRmlTCWfRGp-8GWLS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L71)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> stages:
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 77 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjiOmBAY6qh8fhwAM:-LjSRnBb0Xtb55ql2pTw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L77)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/have/has/
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjm4G1FRbliqcQ0U5:-LjT-4sl6LP5qQgzs0lz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L78)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/their/its/
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjszF3gslVWlLTUAW:-LjT-LMd7Sem1Y-Rwsqq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L79)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> , its side effects on the Replica's state is applied, and the clients acked with the respective results.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQjzjm4jWnUv6PKTDq:-LjSR_uFCq2SSknjY2eH:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L80)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Good job on the comment!
</blockquote></details>

Thanks!
___
*[pkg/storage/replica_application.go, line 80 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQlApK1skmG02V7c_r:-LjT-emWDFVzCaAoo8gR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L80)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mention that errors from this method are fatal. (They still are, right)
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 85 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQk2BnEqPJQ2yHom8Z:-LjSRv8x6vFeFaB4oowP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L85)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

At this point it's neither clear to me why this receives a refreshReason but even less why it returns a new one. Can you say something about this in a comment? There's probably a canonical situation in which this is necessary and it'll be helpful to prime readers for it.

I'm seeing below that this is only relevant when we see an empty entry, so how do you feel about just returning a `bool` or even just adding a `numEmptyEntries` field in the `stats`, so that the refresh reason mangling can live at the caller. I feel that this would remove an unnecessary distraction from this method.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQmfg3BvRIJNBPGgp8:-LjSSH0p4nQ6YWj8-Tmv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L125)):*
<details><summary><i>Previously, tbg (Tobias Griege [...]

2019-07-10 23:16 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/replica_application.go, line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjQj5TnA5-03Hew4s08:-LjT9kRsDWI2AcY8BTVu:bzs23v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Added more fields. 
</blockquote></details>

Though I didn't do anything with them. Probably I should add more metrics. Added a TODO. 
___
*[pkg/storage/replica_application.go, line 633 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjT7wZhBHhF7Z-7_DrJ:-LjT7wZhBHhF7Z-7_DrK:b-bdai0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7716922db4edb03379f7a16ca0326c1f63bf11b7/pkg/storage/replica_application.go#L633)):*
> ```Go
> 			cmd.replicatedResult().State.TruncatedState = nil
> 			cmd.replicatedResult().RaftLogDelta = 0
> 			// TODO(ajwerner): consider moving this code.
> ```

@tbg I'm curious to hear how you feel about this here. It's the only place we really reach down and muck with the `Replica`. If we hoisted this and then passed the `raftMu.stateLoader` this wouldn't even need to be a method on `Replica`.


<!-- Sent from Reviewable.io -->

2019-07-11 08:27 UTC, tbg approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 5 of 10 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjV7vCDCb4QZRYsASuu:b-uwkowd)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/storage/cmd_app_batch.go, line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV-ifK5DBsm2kcCN6q:-LjV-ifK5DBsm2kcCN6r:b-9zegwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L83)):*
> toProcess
___
*[pkg/storage/cmd_app_batch.go, line 89 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV0C4A8jtSKLIbn3Mz:-LjV0C4A8jtSKLIbn3N-:b-51coqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L89)):*
> In that case, the returned decodedCmdRequiresFlush is true to indicate ...
___
*[pkg/storage/cmd_app_batch.go, line 105 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV0NldDrtQpzxCTsvR:-LjV0Nle88A4DkFT6TBl:bnjctg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L105)):*
> ```Go
> 	for len(toProcess) > 0 {
> 		e := &toProcess[0]
> 		// If we haven't already decoded this entry then we decode it into the
> ```

Why "If we haven't already"? We're always decoding into the scratch space here.
___
*[pkg/storage/cmd_app_ctx.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUwfhk3QAbjG64anqa:-LjUwEPLAbdMxVmC61KZ:b-nfx0a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_ctx.go#L70)):*
> ```Go
> 	idKey   storagebase.CmdIDKey
> 	raftCmd storagepb.RaftCommand
> 	cc      raftpb.ConfChange // only populated for conf changes
> ```

nit: cc and ccCtx aren't trivial structs, might be worth having them be pointers since they're barely ever populated. It probably isn't worth it.
___
*[pkg/storage/cmd_app_ctx_buf.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUwxMp417OJLEGG0CK:-LjUwxMp417OJLEGG0CL:byp1ktf) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_ctx_buf.go#L38)):*
> ```Go
> }
> 
> var entryApplicationStateBufNodeSyncPool = sync.Pool{
> ```

Rename
___
*[pkg/storage/replica_application.go, line 722 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjR1UYq3zT_XpoZo5Dr:-LjV3t2ZBNtGZUSdt8yA:b-qi7ebo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L722)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Only truncated state. Nathan and I also discussed making truncated state commands non-trivial and I'm still happy to do it. If we want to do it I'll do it on the next pass. 
</blockquote></details>

Raft truncation is pretty frequent, I'd worry that that'll backfire somehow. Mild preference to keep it trivial then. Maybe we'll manage to restructure the log truncation so that it's less invasive, too (i.e. not synced through a Raft command in the first place).
___
*[pkg/storage/replica_application.go, line 633 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjT7wZhBHhF7Z-7_DrJ:-LjV3SsBEgabVOcJt_ly:bu171oy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7716922db4edb03379f7a16ca0326c1f63bf11b7/pkg/storage/replica_application.go#L633)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

@tbg I'm curious to hear how you feel about this here. It's the only place we really reach down and muck with the `Replica`. If we hoisted this and then passed the `raftMu.stateLoader` this wouldn't even need to be a method on `Replica`.
</blockquote></details>

I like that, but more as a follow-up than eagerly - this PR should land and it's becoming quite difficult to trace the correctness of these smaller changes through the diffs.
___
*[pkg/storage/replica_application.go, line 98 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUzpfv34UySEh8p7-I:-LjUzpfv34UySEh8p7-J:b-avzruc) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L98)):*
> ```Go
> ) (stats handleCommittedEntriesStats, errExpl string, err error) {
> 	var (
> 		decodeBuf        decodedRaftEntry
> ```

This escapes, right?
___
*[pkg/storage/replica_application.go, line 104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV13Mr34P2KeQRXRjr:-LjV13Mr34P2KeQRXRjs:blbp7fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L104)):*
> // The batch is always empty at the beginning of this loop. In each iteration, we either process a chunk of trivial entries or an individual nontrivial entry. The `haveDecodedEntry` branch always corresponds to a non-trivial entry, while the `else` branch processes either a single nontrivial entry or any number of nontrivial entries.

This might get a little more streamlined as far as the explanation goes if instead of handling a nontrivial command that is encountered first in the `else` branch eagerly, you defer it via `haveDecodedEntry`. Then you could say

> The haveDecodedEntry branch corresponds to a nontrivial entry, while the else branch populates b with any number (possibly zero) of trivial entries.

I think that's worth doing, but I'll defer to your judgment.
___
*[pkg/storage/replica_application.go, line 141 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV-VFZAKTvGANFjyp_:-LjV-VFZAKTvGANFjypa:bkt2isj) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L141)):*
> retrieve
___
*[pkg/storage/replica_application.go, line 181 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV2jy53goH_DQSPq1G:-LjV2jy53goH_DQSPq1H:bstgsvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L181)):*
> ```Go
> // proposal's content is wiped and we apply an empty log entry instead. If an
> // error occurs and the command was proposed locally, it will be communicated to
> // a waiting proposer. The two typical cases errors occur are lease mismatch (in
> ```

Grammar off
___
*[pkg/storage/replica_application.go, line 575 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV38oP96WboSEK-WfL:-LjV38oP96WboSEK-WfM:b-lfc165) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L575)):*
> ```Go
> 	//
> 	// TODO(ajwerner): explore the costs and benefits of this use of Distinct().
> 	// This call requires flushing the batch's writes but
> ```

the suspense!
___
*[pkg/storage/replica_application.go, line 637 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV71qJ3GiMAE-ISLzn:-LjV71qJ3GiMAE-ISLzo:b-ft29d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L637)):*
> ```Go
> 		cmd.replicatedResult().State.TruncatedState != nil
> 	if haveTruncatedState {
> 		apply, err := handleTruncatedStateBelowRaft(ctx, replicaState.TruncatedState,
> ```

Hmm, now I'm not sure this batches correctly. `handleTruncatedStateBelowRaft` loads from the engine, which now fails to reflect any prior truncations in the same batch. This is all probably fine since we're throwing away all but the last truncation (and don't do anything with the information in the ones we throw away prior to tossing [...]

2019-07-11 22:13 UTC, ajwerner reviewed
TFTR! @tbg can you give the change for the truncated state a glance before I bors this. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-LjWl54198Nl9g8O-NQd:b-tx1uuu)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/cmd_app_batch.go, line 83 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV-ifK5DBsm2kcCN6q:-LjWPveV4vsLS14_jZaq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L83)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> toProcess
</blockquote></details>

Done.
___
*[pkg/storage/cmd_app_batch.go, line 89 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV0C4A8jtSKLIbn3Mz:-LjWQigUDMcyiCUFODIF:bs4i3k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L89)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> In that case, the returned decodedCmdRequiresFlush is true to indicate ...
</blockquote></details>

Cleaned up the logic as suggested.
___
*[pkg/storage/cmd_app_batch.go, line 105 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV0NldDrtQpzxCTsvR:-LjWQoPG3jy7FYo-Sv_B:bze417e) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_batch.go#L105)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why "If we haven't already"? We're always decoding into the scratch space here.
</blockquote></details>

Stale.
___
*[pkg/storage/cmd_app_ctx.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUwfhk3QAbjG64anqa:-LjWRDKiEaqG_mQjCxmB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_ctx.go#L70)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: cc and ccCtx aren't trivial structs, might be worth having them be pointers since they're barely ever populated. It probably isn't worth it.
</blockquote></details>

Done.
___
*[pkg/storage/cmd_app_ctx_buf.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUwxMp417OJLEGG0CK:-LjWb4b_13Dsb_GAq065:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_ctx_buf.go#L38)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 722 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjR1UYq3zT_XpoZo5Dr:-LjWjq2m6ZcqIPH3IaVL:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L722)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Raft truncation is pretty frequent, I'd worry that that'll backfire somehow. Mild preference to keep it trivial then. Maybe we'll manage to restructure the log truncation so that it's less invasive, too (i.e. not synced through a Raft command in the first place).
</blockquote></details>

Ack.
___
*[pkg/storage/replica_application.go, line 98 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUzpfv34UySEh8p7-I:-LjWb6d61J-XlJIFlrqb:bnptj54) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L98)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This escapes, right?
</blockquote></details>

Indeed it did. Moved to the appCtxBatch struct. 
___
*[pkg/storage/replica_application.go, line 104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV13Mr34P2KeQRXRjr:-LjWbWS6DRyEnF1QL3EM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L104)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> // The batch is always empty at the beginning of this loop. In each iteration, we either process a chunk of trivial entries or an individual nontrivial entry. The `haveDecodedEntry` branch always corresponds to a non-trivial entry, while the `else` branch processes either a single nontrivial entry or any number of nontrivial entries.

This might get a little more streamlined as far as the explanation goes if instead of handling a nontrivial command that is encountered first in the `else` branch eagerly, you defer it via `haveDecodedEntry`. Then you could say

> The haveDecodedEntry branch corresponds to a nontrivial entry, while the else branch populates b with any number (possibly zero) of trivial entries.

I think that's worth doing, but I'll defer to your judgment.
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 141 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV-VFZAKTvGANFjyp_:-LjWdIda52hZuAaNEUrz:bss1dwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L141)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> retrieve
</blockquote></details>

I have a serious problem with these diphthong vowel orderings.
___
*[pkg/storage/replica_application.go, line 181 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV2jy53goH_DQSPq1G:-LjWekeOADjA2XQJ7F_E:b-h7p0o7) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L181)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Grammar off
</blockquote></details>

I'm not totally sure about the grammar qualms. I tried to tighten up the grammar but most of my changes in this area but my changes were mostly just speculation.
___
*[pkg/storage/replica_application.go, line 575 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV38oP96WboSEK-WfL:-LjWiM7E-2hxpYZJ9YHD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L575)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

the suspense!
</blockquote></details>

Done.
___
*[pkg/storage/replica_application.go, line 637 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV71qJ3GiMAE-ISLzn:-LjWj-4x-SWqiVlN2q-J:b4bmni6) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L637)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, now I'm not sure this batches correctly. `handleTruncatedStateBelowRaft` loads from the engine, which now fails to reflect any prior truncations in the same batch. This is all probably fine since we're throwing away all but the last truncation (and don't do anything with the information in the ones we throw away prior to tossing them). Add some commentary.
</blockquote></details>

If we don't use the Distinct() batch it will be safe, right? I changed it to use the batch rather than the `Distinct()` writer. I'd like your approval before I merge I merge this. 
___
*[pkg/storage/replica_application_result.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV5a5N-WYlVTHT6kvY:-LjWjuT76elVj47Jpgrw:b9zm5go) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application_result.go#L92)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><bloc [...]

2019-07-12 07:45 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
bors it like it's hot

> Reviewed 7 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-:-Lj_8CE69LfBgyeTA_J-:b-t9gr73)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/cmd_app_batch.go, line 90 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lj_4QJ75nQuedlrPmAx:-Lj_4QJ75nQuedlrPmAy:b-oz5lrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eff726b040672219cae92c4e7bdf10de6b9575/pkg/storage/cmd_app_batch.go#L90)):*
> ```Go
> // commands must always be in their own batch. If a non-trivial command is
> // encountered the batch is returned immediately without adding the newly
> // decoded command to the batch of removing it from remaining.
> ```

s/of/or/
___
*[pkg/storage/cmd_app_ctx_buf.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjUwxMp417OJLEGG0CK:-Lj_523Q3B5EOOgFf8Pn:bb726fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/cmd_app_ctx_buf.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ping
___
*[pkg/storage/replica_application.go, line 917 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjR7O_5DXkwS4igEztL:-Lj_8DKCCBfLz53bEpfe:b-qv9mx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4c6d91e72f4869c4f4571af93ca64790c504cfe/pkg/storage/replica_application.go#L917)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Wish I could tell you.
___
*[pkg/storage/replica_application.go, line 181 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV2jy53goH_DQSPq1G:-Lj_5ns--IfqiEP8xp-m:b-aire9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L181)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not totally sure about the grammar qualms. I tried to tighten up the grammar but most of my changes in this area but my changes were mostly just speculation.
</blockquote></details>

Yeah the missing "in which" threw me off, my brain doesn't think that that's valid (regardless of whether it is), thanks for fixing.
___
*[pkg/storage/replica_application.go, line 637 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-LjV71qJ3GiMAE-ISLzn:-Lj_6jeP2gCJ_qODMnO3:b-q7abxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/da52af6aafe0f76c1378e0ebb4724cee228663ef/pkg/storage/replica_application.go#L637)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If we don't use the Distinct() batch it will be safe, right? I changed it to use the batch rather than the `Distinct()` writer. I'd like your approval before I merge I merge this. 
</blockquote></details>

Yes, that checks out.
Can you rename `distinctEng` in `handleTruncatedStateBelowRaft` to just `batch`?

I don't know if there's a penalty for using the batch after having used `Distinct()`, but we probably do that already anyway. And for truncations, the right thing in the long run is to avoid having them triggered by Raft commands, so this particular use we're hoping to remove at some point.

Also, lol at the [semantics of `Distinct()`](https://github.com/cockroachdb/cockroach/blob/70472c47051ffff62e589236a2107c5433daf8bf/pkg/storage/engine/engine.go#L373-L384). I remember now that I wasted time on this in the past.
___
*[pkg/storage/replica_application.go, line 111 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/38568#-Lj_5HV98Mxe9aBdPUNT:-Lj_5HV98Mxe9aBdPUNU:bo64evb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7eff726b040672219cae92c4e7bdf10de6b9575/pkg/storage/replica_application.go#L111)):*
> into


<!-- Sent from Reviewable.io -->

2019-07-12 13:59 UTC, ajwerner commented
TFTR!

bors r=nvanbenschoten,tbg

2019-07-12 14:22 UTC, merged