Sum aggregator null handling
cockroachdb/cockroach pull request #38665
Opened 2019-07-03 19:18 UTC by rafiss

#37738
depends on #38522

```
    BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12         4997417 ns/op     104.91 MB/s
    BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12          5322976 ns/op      98.50 MB/s
    BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12       32984783 ns/op     15.89 MB/s
    BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12        30298825 ns/op     17.30 MB/s
    BenchmarkAggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12      151927 ns/op     3450.92 MB/s
    BenchmarkAggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12       224303 ns/op     2337.41 MB/s
    BenchmarkAggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12    28843918 ns/op     18.18 MB/s
    BenchmarkAggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12     25312401 ns/op     20.71 MB/s
```

2019-07-03 19:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38665)
<!-- Reviewable:end -->

2019-07-03 19:18 UTC, rafiss commented
```
name                                                                                old time/op     new time/op     delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12             6.18ms ± 5%     6.32ms ± 5%      ~     (p=0.075 n=10+10)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12              6.19ms ± 1%     6.52ms ± 6%    +5.35%  (p=0.000 n=9+10)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12             4.76ms ± 1%     5.53ms ±30%   +16.21%  (p=0.000 n=10+10)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12              4.96ms ± 1%     5.40ms ±22%    +8.74%  (p=0.000 n=8+9)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12           4.29ms ± 1%     4.20ms ± 2%    -1.98%  (p=0.000 n=10+9)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12            4.48ms ± 0%     4.71ms ± 4%    +5.06%  (p=0.000 n=7+9)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12          4.92ms ± 6%     4.99ms ±10%      ~     (p=0.720 n=9+10)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12           18.8ms ±72%      5.4ms ±17%   -71.15%  (p=0.028 n=10+9)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12           61.8ms ± 4%     11.3ms ± 2%   -81.72%  (p=0.000 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12            12.3ms ±18%     11.7ms ±12%    -5.55%  (p=0.040 n=9+9)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12           11.9ms ±11%     11.5ms ± 9%      ~     (p=0.211 n=10+9)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12            11.3ms ± 2%     10.9ms ± 3%    -3.29%  (p=0.007 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12         31.6ms ± 2%     31.5ms ± 4%      ~     (p=0.447 n=9+10)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12          31.6ms ± 2%     30.2ms ±16%      ~     (p=0.156 n=9+10)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12        34.8ms ± 8%     35.1ms ± 7%      ~     (p=0.436 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12         35.5ms ± 6%     36.3ms ±12%      ~     (p=0.481 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12           189µs ±14%      212µs ±13%   +11.67%  (p=0.004 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12            192µs ± 3%      278µs ± 3%   +45.01%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12           183µs ± 7%      179µs ± 6%      ~     (p=0.143 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12            178µs ± 5%      258µs ± 9%   +44.88%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12         169µs ± 4%      158µs ± 3%    -6.09%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12          170µs ± 6%      227µs ± 2%   +33.29%  (p=0.000 n=9+10)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12        170µs ±15%      156µs ± 1%    -8.53%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12         169µs ± 8%      233µs ± 3%   +38.20%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12        4.90ms ± 3%     4.88ms ± 2%      ~     (p=0.971 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12         4.80ms ± 1%     4.54ms ± 2%    -5.43%  (p=0.000 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12        5.65ms ± 0%     5.86ms ± 2%    +3.64%  (p=0.000 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12         5.66ms ± 1%     5.29ms ± 1%    -6.53%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12      26.7ms ± 3%     27.0ms ± 2%      ~     (p=0.053 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12       26.8ms ± 1%     24.6ms ± 2%    -8.27%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12     28.5ms ± 5%     28.8ms ± 4%      ~     (p=0.436 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12      28.3ms ± 4%     25.6ms ± 1%    -9.48%  (p=0.000 n=10+8)

name                                                                                old speed       new speed       delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12           84.9MB/s ± 5%   83.0MB/s ± 5%      ~     (p=0.075 n=10+10)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12            84.7MB/s ± 1%   80.5MB/s ± 6%    -4.98%  (p=0.000 n=9+10)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12            110MB/s ± 1%     96MB/s ±24%   -12.55%  (p=0.000 n=10+10)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12             106MB/s ± 1%     95MB/s ±22%    -9.62%  (p=0.000 n=8+10)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12          122MB/s ± 1%    125MB/s ± 2%    +2.03%  (p=0.000 n=10+9)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12           117MB/s ± 0%    111MB/s ± 4%    -4.76%  (p=0.000 n=7+9)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12         107MB/s ± 6%    105MB/s ± 9%      ~     (p=0.720 n=9+10)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12        49.6MB/s ±102%   95.0MB/s ±18%   +91.50%  (p=0.035 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12         8.48MB/s ± 4%  46.38MB/s ± 2%  +446.86%  (p=0.000 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12          42.7MB/s ±15%   44.5MB/s ±12%      ~     (p=0.113 n=9+10)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12         44.3MB/s ±10%   44.9MB/s ±16%      ~     (p=0.424 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12          46.5MB/s ± 2%   48.1MB/s ± 3%    +3.44%  (p=0.007 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12       16.6MB/s ± 2%   16.6MB/s ± 4%      ~     (p=0.459 n=9+10)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12        16.5MB/s ± 3%   17.5MB/s ±14%      ~     (p=0.138 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12      15.1MB/s ± 7%   14.9MB/s ± 7%      ~     (p=0.447 n=10+10)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12       14.8MB/s ± 6%   14.5MB/s ±11%      ~     (p=0.424 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12        2.78GB/s ±13%   2.49GB/s ±12%   -10.46%  (p=0.004 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12         2.73GB/s ± 3%   1.88GB/s ± 3%   -31.04%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12        2.84GB/s ± 4%   2.93GB/s ± 6%    +3.39%  (p=0.043 n=9+10)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12         2.95GB/s ± 4%   2.04GB/s ± 8%   -30.91%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12      3.11GB/s ± 4%   3.31GB/s ± 3%    +6.50%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12       3.08GB/s ± 5%   2.31GB/s ± 2%   -25.02%  (p=0.000 n=9+10)
Aggregato [...]

2019-07-08 19:50 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjI7jXS4Lxl1W_PkLR1:-LjI7jXS4Lxl1W_PkLR2:b-xiha99) ([raw file](https://github.com/cockroachdb/cockroach/blob/f49b4f961fd04b8648629bceed9895d91343e5e0/pkg/sql/exec/sum_agg_tmpl.go#L194)):*
> ```Go
> 		a.scratch.foundNonNullForCurrentGroup = false
> 	}
> 	if !nulls.NullAt(uint16(i)) {
> ```

ditto suggestion in your other PR, I think you could DRY this a tiny bit.


<!-- Sent from Reviewable.io -->

2019-07-10 18:18 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjI7jXS4Lxl1W_PkLR1:-LjS5vYX3QL7G-Ge2jDI:b-urmj54) ([raw file](https://github.com/cockroachdb/cockroach/blob/f49b4f961fd04b8648629bceed9895d91343e5e0/pkg/sql/exec/sum_agg_tmpl.go#L194)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto suggestion in your other PR, I think you could DRY this a tiny bit.
</blockquote></details>

done, made the null check templated


<!-- Sent from Reviewable.io -->

2019-07-10 18:19 UTC, rafiss commented
ready for the next review :)

2019-07-10 18:57 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjS8Bjq0h5Dbydrw3Ya:-LjS8Bjs8plUHZP1efXf:b-7mkxgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L183)):*
> ```Go
> 	// {{ end }}
> 	if !isNull {
> 		_ASSIGN_ADD("a.scratch.vec[a.scratch.curIdx]", "a.scratch.vec[a.scratch.curIdx]", "col[i]")
> ```

This is only semi-related to your PR, but I think there is a pretty easy optimization available here. Rather than repeatedly reading and writing `a.scratch.vec[a.scratch.curIdx]`, you could keep a running sum variable and only write to the vec when a new group starts. That should be decently faster because you don't need to index into the slice over and over. The same strategy could be applied to other aggregations too, like min/max.


<!-- Sent from Reviewable.io -->

2019-07-10 19:02 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSFhzk2tThwwnk-d0Q:-LjSFhzk2tThwwnk-d0R:b8t39bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L167)):*
> ```Go
> 		if !a.scratch.foundNonNullForCurrentGroup && a.scratch.curIdx >= 0 {
> 			a.scratch.nulls.SetNull(uint16(a.scratch.curIdx))
> 		}
> ```

Is there an edge case here where this won't get run for the final group?
___
*[pkg/sql/exec/sum_agg_tmpl.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSF-BgDUgCwTMF9DOC:-LjSF-BgDUgCwTMF9DOD:bsvxzdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L171)):*
> ```Go
> 
> 		// We only need to reset this flag if there are nulls. If there are no
> 		// nulls, this will be updated unconditionally below.
> ```

Nit: This should probably be a template comment. It's kind of confusing to include it in the generated code.


<!-- Sent from Reviewable.io -->

2019-07-10 19:14 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSFhzk2tThwwnk-d0Q:-LjSIjQxE5OKr5GoMdNw:b2uyq3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L167)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is there an edge case here where this won't get run for the final group?
</blockquote></details>

Oops, you already handled this. Never mind.


<!-- Sent from Reviewable.io -->

2019-07-10 19:18 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>! One comment nit and one optimization suggestion you're welcome to save for later.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-:-LjSJMTQ5AK5F6ow2c8z:bm1b3b0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)



<!-- Sent from Reviewable.io -->

2019-07-10 19:18 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSFhzk2tThwwnk-d0Q:-LjSGKEG8aIfPI1ou5IR:bkf60ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L167)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is there an edge case here where this won't get run for the final group?
</blockquote></details>

this doesn't get run for the final group; that is handled on line 115. i'm definitely open to suggestions on avoiding that duplication.
___
*[pkg/sql/exec/sum_agg_tmpl.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSF-BgDUgCwTMF9DOC:-LjSGT0v7xoAIYi6BER6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L171)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: This should probably be a template comment. It's kind of confusing to include it in the generated code.
</blockquote></details>

done
___
*[pkg/sql/exec/sum_agg_tmpl.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjS8Bjq0h5Dbydrw3Ya:-LjSGX4y2Dd0Uxgshr00:bc23f28) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L183)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This is only semi-related to your PR, but I think there is a pretty easy optimization available here. Rather than repeatedly reading and writing `a.scratch.vec[a.scratch.curIdx]`, you could keep a running sum variable and only write to the vec when a new group starts. That should be decently faster because you don't need to index into the slice over and over. The same strategy could be applied to other aggregations too, like min/max.
</blockquote></details>

that's a good idea! trying it out


<!-- Sent from Reviewable.io -->

2019-07-10 19:37 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjS8Bjq0h5Dbydrw3Ya:-LjSNUv57FxW1DqSohQd:bool5rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L183)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that's a good idea! trying it out
</blockquote></details>

it looks like about a 300 MB/s speedup, thanks! i'll make sure the other aggregators work this way too. (except it doesn't apply to any_not_null since we were only indexing once per group already)


<!-- Sent from Reviewable.io -->

2019-07-10 19:44 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjS8Bjq0h5Dbydrw3Ya:-LjSPaIN0pxuudVdHZIq:beuyiaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a849883d5ab3f5ae2a0c95ade05547b87bd3125/pkg/sql/exec/sum_agg_tmpl.go#L183)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like about a 300 MB/s speedup, thanks! i'll make sure the other aggregators work this way too. (except it doesn't apply to any_not_null since we were only indexing once per group already)
</blockquote></details>

Good stuff!


<!-- Sent from Reviewable.io -->

2019-07-10 19:58 UTC, rafiss commented
Here are some new bench stats, with Solon's suggestion to avoid indexing each time.

```
name                                                                                old time/op    new time/op    delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12          179µs ± 2%     227µs ± 1%    +26.42%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12           179µs ± 1%     414µs ± 2%   +131.27%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12          169µs ± 2%     181µs ± 3%     +6.82%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12           169µs ± 3%     275µs ± 1%    +62.33%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12        159µs ± 1%     151µs ± 3%     -5.14%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12         160µs ± 1%     221µs ± 7%    +38.31%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12       160µs ± 1%     144µs ± 3%    -10.04%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12        160µs ± 1%     217µs ± 3%    +35.62%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12       4.78ms ± 1%   27.91ms ± 1%   +483.26%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12        4.79ms ± 1%   25.63ms ± 4%   +435.38%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12       5.64ms ± 2%   30.09ms ± 5%   +433.73%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12        5.58ms ± 2%   26.01ms ± 0%   +365.71%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12     26.2ms ± 1%    28.9ms ± 0%    +10.13%  (p=0.016 n=5+4)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12      26.2ms ± 1%    26.3ms ± 1%       ~     (p=0.310 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12    27.6ms ± 3%    28.8ms ± 0%     +4.09%  (p=0.016 n=4+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12     30.0ms ± 9%    26.2ms ± 1%    -12.64%  (p=0.008 n=5+5)

name                                                                                old speed      new speed      delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12       2.92GB/s ± 2%  2.31GB/s ± 1%    -20.90%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12        2.93GB/s ± 1%  1.27GB/s ± 2%    -56.75%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12       3.10GB/s ± 2%  2.90GB/s ± 3%     -6.34%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12        3.10GB/s ± 3%  1.91GB/s ± 1%    -38.41%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12     3.29GB/s ± 1%  3.47GB/s ± 3%     +5.44%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12      3.28GB/s ± 1%  2.38GB/s ± 7%    -27.47%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12    3.28GB/s ± 1%  3.64GB/s ± 2%    +11.19%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12     3.27GB/s ± 1%  2.41GB/s ± 3%    -26.24%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12      110MB/s ± 1%    19MB/s ± 1%    -82.86%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12       110MB/s ± 1%    20MB/s ± 4%    -81.31%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12     93.0MB/s ± 2%  17.5MB/s ± 5%    -81.24%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12      93.9MB/s ± 2%  20.2MB/s ± 1%    -78.53%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12   20.0MB/s ± 1%  18.0MB/s ± 3%     -9.80%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12    20.0MB/s ± 1%  19.9MB/s ± 1%       ~     (p=0.246 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12  19.0MB/s ± 3%  18.2MB/s ± 0%     -3.94%  (p=0.016 n=4+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12   17.5MB/s ± 9%  20.0MB/s ± 1%    +13.97%  (p=0.008 n=5+5)

name                                                                                old alloc/op   new alloc/op   delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12         51.5kB ± 0%    51.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12          51.5kB ± 0%    51.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12         50.5kB ± 0%    50.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12          50.5kB ± 0%    50.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12       49.5kB ± 0%    49.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12        49.5kB ± 0%    49.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12      49.5kB ± 0%    49.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12       49.5kB ± 0%    49.5kB ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12        576kB ± 0%   17751kB ± 0%  +2983.02%  (p=0.016 n=4+5)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12         576kB ± 0%   15855kB ± 0%  +2653.74%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12       1.89MB ± 0%   18.37MB ± 0%   +874.40%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12        1.89MB ± 0%   16.49MB ± 0%   +774.78%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12     16.4MB ± 0%    18.7MB ± 0%    +14.06%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12      16.4MB ± 0%    16.8MB ± 0%     +2.43%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12    17.7MB ± 0%    18.7MB ± 0%     +5.66%  (p=0.008 n=5+5)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12     17.7MB ± 0%    16.8MB ± 0%     -5.01%  (p=0.008 n=5+5)

name                                                                                old allocs/op  new allocs/op  delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12            711 ± 0%       711 ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12             711 ± 0%       711 ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12            679 ± 0%       679 ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12             679 ± 0%       679 ± 0%       ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12          648 ± 0%       648 ± 0%       ~     (all equal)
Aggrega [...]

2019-07-10 20:36 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSaRtY9_C0v_AQM-J8:-LjSaRtY9_C0v_AQM-J9:b-peykfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L177)):*
> ```Go
> 				a.scratch.nulls.SetNull(uint16(a.scratch.curIdx))
> 			}
> 			a.scratch.vec[a.scratch.curIdx] = a.scratch.curAgg
> ```

I think you also need to reset `curAgg` somewhere in here.


<!-- Sent from Reviewable.io -->

2019-07-10 20:44 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjScN0s618CS25AvjbD:-LjScN0s618CS25AvjbE:b-cjn5p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L104)):*
> ```Go
> 	if a.scratch.curIdx != -1 {
> 		a.scratch.curIdx = idx
> 		a.scratch.curAgg = a.scratch.vec[idx]
> ```

Is this right? I forget what exactly the contract of `SetOutputIndex` is but I don't see why `curAgg` should be affected.


<!-- Sent from Reviewable.io -->

2019-07-10 22:03 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 104 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjScN0s618CS25AvjbD:-LjSkSxEAOx3xXBCYS-A:b-sjtwcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L104)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is this right? I forget what exactly the contract of `SetOutputIndex` is but I don't see why `curAgg` should be affected.
</blockquote></details>

yeah... it's not needed. thanks for that catch. my initial thinking was that since the index was changing, we could be computing for a different group now, but that is not the case.
___
*[pkg/sql/exec/sum_agg_tmpl.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSaRtY9_C0v_AQM-J8:-LjSspiX7w12dq7bVy2B:b-ssgz5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L177)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think you also need to reset `curAgg` somewhere in here.
</blockquote></details>

thanks! i _think_ this bug also explained why the bench for Decimal with small groupSize ended up in disaster. the aggregate wasn't getting reset, so the total was getting to be really big, and Decimals are much slower at adding larger numbers.

i can't make of `zero_TYPEColumn`in this part of the template, so take a look at what i'm doing instead and let me know if it seems ok...


<!-- Sent from Reviewable.io -->

2019-07-10 22:41 UTC, rafiss commented
Fixing the bug that Solon pointed out leads to acceptable benchmark stats

```
name                                                                                old time/op    new time/op    delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12          180µs ± 5%     229µs ± 1%   +27.16%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12           179µs ± 2%     429µs ± 2%  +139.18%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12          172µs ± 6%     177µs ± 1%    +2.91%  (p=0.008 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12           172µs ± 6%     271µs ± 1%   +56.89%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12        160µs ± 3%     141µs ± 1%   -12.12%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12         163µs ± 4%     206µs ± 1%   +27.01%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12       160µs ± 3%     142µs ± 1%   -11.21%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12        161µs ± 1%     209µs ± 2%   +29.71%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12       5.71ms ± 3%    5.78ms ± 2%    +1.12%  (p=0.029 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12        5.67ms ± 2%    5.44ms ± 2%    -4.01%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12       5.87ms ± 2%    5.89ms ± 1%      ~     (p=0.218 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12        6.15ms ± 4%    5.40ms ± 2%   -12.09%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12     3.93ms ± 2%    3.70ms ± 1%    -5.66%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12      3.79ms ± 1%    3.55ms ± 6%    -6.37%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12    3.70ms ± 1%    3.66ms ± 2%      ~     (p=0.113 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12     3.71ms ± 2%    3.36ms ± 2%    -9.53%  (p=0.000 n=10+9)

name                                                                                old speed      new speed      delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12       2.91GB/s ± 4%  2.29GB/s ± 1%   -21.39%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12        2.93GB/s ± 2%  1.22GB/s ± 2%   -58.19%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12       3.06GB/s ± 5%  2.97GB/s ± 1%    -2.91%  (p=0.008 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12        3.04GB/s ± 5%  1.94GB/s ± 1%   -36.32%  (p=0.000 n=10+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12     3.27GB/s ± 3%  3.72GB/s ± 1%   +13.77%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12      3.23GB/s ± 3%  2.54GB/s ± 1%   -21.29%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12    3.27GB/s ± 3%  3.68GB/s ± 1%   +12.60%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12     3.26GB/s ± 1%  2.51GB/s ± 2%   -22.90%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12     91.8MB/s ± 2%  90.7MB/s ± 2%    -1.12%  (p=0.029 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12      92.5MB/s ± 2%  96.4MB/s ± 2%    +4.17%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12     89.4MB/s ± 2%  88.9MB/s ± 1%      ~     (p=0.218 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12      85.3MB/s ± 4%  97.0MB/s ± 2%   +13.72%  (p=0.000 n=9+9)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12    134MB/s ± 2%   142MB/s ± 1%    +5.98%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12     138MB/s ± 1%   148MB/s ± 5%    +6.89%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12   142MB/s ± 1%   143MB/s ± 2%      ~     (p=0.113 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12    141MB/s ± 2%   156MB/s ± 2%   +10.54%  (p=0.000 n=10+9)

name                                                                                old alloc/op   new alloc/op   delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12         51.5kB ± 0%    51.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12          51.5kB ± 0%    51.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12         50.5kB ± 0%    50.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12          50.5kB ± 0%    50.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12       49.5kB ± 0%    49.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=true/numInputBatches=64-12        49.5kB ± 0%    49.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-12      49.5kB ± 0%    49.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-12       49.5kB ± 0%    49.5kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-12        575kB ± 0%     575kB ± 0%      ~     (p=0.197 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-12         575kB ± 0%     523kB ± 0%    -9.17%  (p=0.000 n=8+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-12       1.88MB ± 0%    1.88MB ± 0%      ~     (p=0.905 n=9+10)
Aggregator/SUM/ordered/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-12        1.88MB ± 0%    1.58MB ± 0%   -16.03%  (p=0.000 n=10+10)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-12     56.6kB ± 0%    56.6kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-12      56.6kB ± 0%    56.6kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-12    53.1kB ± 0%    53.1kB ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-12     53.1kB ± 0%    53.1kB ± 0%      ~     (all equal)

name                                                                                old allocs/op  new allocs/op  delta
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=false/numInputBatches=64-12            711 ± 0%       711 ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=1/hasNulls=true/numInputBatches=64-12             711 ± 0%       711 ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=false/numInputBatches=64-12            679 ± 0%       679 ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=2/hasNulls=true/numInputBatches=64-12             679 ± 0%       679 ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize=512/hasNulls=false/numInputBatches=64-12          648 ± 0%       648 ± 0%      ~     (all equal)
Aggregator/SUM/ordered/Int64/groupSize [...]

2019-07-11 02:05 UTC, solongordon approved these changes
Cool, glad we have an explanation for those weird benchmark numbers. (Also explains why allocations went through the roof.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-:-LjTld_S9oPIC1Zn6ksE:bi4astn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSaRtY9_C0v_AQM-J8:-LjTkrQQ0CMr2jGdaVY6:b8lb4if) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L177)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

thanks! i _think_ this bug also explained why the bench for Decimal with small groupSize ended up in disaster. the aggregate wasn't getting reset, so the total was getting to be really big, and Decimals are much slower at adding larger numbers.

i can't make of `zero_TYPEColumn`in this part of the template, so take a look at what i'm doing instead and let me know if it seems ok...
</blockquote></details>

Seems like it should work though it's kind of confusing. I would either add an explanatory comment or create a new pattern to be replaced by `{{.Global.LTyp}}`.
___
*[pkg/testutils/lint/lint_test.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjTkiW3CFHYWnmbhCAU:-LjTkiW3CFHYWnmbhCAV:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbf076e6f0719b3596676673b82ea9dfceacf7e/pkg/testutils/lint/lint_test.go#L114)):*
> ```Go
> 
> 		cmd, stderr, filter, err := dirCmd(crdb.Dir,
> 			"git", "grep", "-nE", fmt.Sprintf(`[^_a-zA-Z](%s)\(`, strings.Join(names, "|")),
> ```

Why did this change?


<!-- Sent from Reviewable.io -->

2019-07-11 14:06 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/exec/sum_agg_tmpl.go, line 177 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjSaRtY9_C0v_AQM-J8:-LjWLp711cWkKcjPXg96:b-8t5j0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/028efbcc7b2c37fdc6ab94517db3b033ea0aef50/pkg/sql/exec/sum_agg_tmpl.go#L177)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Seems like it should work though it's kind of confusing. I would either add an explanatory comment or create a new pattern to be replaced by `{{.Global.LTyp}}`.
</blockquote></details>

i'll go with a comment
___
*[pkg/testutils/lint/lint_test.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjTkiW3CFHYWnmbhCAU:-LjWL-icAwVo0BkjMnWU:b-3hu7bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbf076e6f0719b3596676673b82ea9dfceacf7e/pkg/testutils/lint/lint_test.go#L114)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

i mentioned it in the commit message -- there was a bug in the linter that disallowed function names that ended in "_SUM" (or any other SQL builtin). It was supposed to only disallow functions named "SUM"


<!-- Sent from Reviewable.io -->

2019-07-11 14:14 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38665)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/testutils/lint/lint_test.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38665#-LjTkiW3CFHYWnmbhCAU:-LjWNbJl9fOCuRD5pS8Q:b-vo0hen) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbf076e6f0719b3596676673b82ea9dfceacf7e/pkg/testutils/lint/lint_test.go#L114)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i mentioned it in the commit message -- there was a bug in the linter that disallowed function names that ended in "_SUM" (or any other SQL builtin). It was supposed to only disallow functions named "SUM"
</blockquote></details>

Got it, thanks


<!-- Sent from Reviewable.io -->

2019-07-11 14:49 UTC, rafiss commented
thanks for all the reviews!
bors r+

2019-07-11 15:14 UTC, merged