exec: Add memory estimation and monitoring for streaming operators.
cockroachdb/cockroach pull request #38796
Opened 2019-07-10 18:59 UTC by rohany

We want to error out early of our vectorized execution if there is not enough memory available to run the query, especially if we can tell upfront that this is the case. Some streaming operators always use a static amount of memory, so we can monitor this memory during construction of the vectorized plan. Due to difficulties with traversing the vectorized flow once is it constructed, we monitor memory during construction of each operator, and have streaming operators estimate how much memory they will use during construction. This PR adds memory estimation to the following operators:

* CountOp
* Aggregate operators
* TopK sorter
* Columnarizer
* Coalescer
* OrderedSynchronizer
* Projection operators

Release note: None

2019-07-10 19:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38796)
<!-- Reviewable:end -->

2019-07-10 19:00 UTC, rohany commented
This is pretty big PR. Reviews + discussion are very much appreciated. Let me know if I missed any operators!

2019-07-15 18:35 UTC, asubiotto reviewed
I like the general approach, although I'm wondering if it would be cleaner to either 1) just return the number of bytes that an operator will use or 2) Have the operators you care about implement an interface that will return the number of bytes used given some types and in either case increment the account in `newColOperator` after creating an operator and then again after creating any post processing operators. I like the second approach better and it'll be nice to not have to care about the `mon` package, modify tests that don't care about memory, or modify constructors. We'll have to do something similar for buffering operators and since they will return the same amount of memory regardless of the types.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-:-LjqjgeA4UYUBHBXxCc4:bpu0idj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljqibs59wDvTzGuEiVo:-Ljqibs59wDvTzGuEiVp:b-x38l9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/distsqlrun/column_exec_setup.go#L554)):*
> ```Go
> func planSelectionOperators(
> 	ctx context.Context,
> 	tctx *tree.EvalContext,
> ```

nit: `s/tctx/evalCtx`
___
*[pkg/sql/distsqlrun/columnar_utils_test.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljqm8bS8IIzxf428WQJ:-Ljqm8bS8IIzxf428WQK:b-4s44m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/distsqlrun/columnar_utils_test.go#L76)):*
> ```Go
> 	columnarizers := make([]exec.Operator, len(inputs))
> 	for i, input := range inputsColOp {
> 		c, err := newColumnarizer(ctx, flowCtx, int32(i)+1, input, nil)
> ```

nit: add block comments to `nil` arguments
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjqmEMY6xMSWDOpg2Wr:-LjqmEMY6xMSWDOpg2Ws:b2niaru) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L72)):*
> ```Go
> 	}{
> 		{
> 			desc: "Test construct sorttopk",
> ```

nit: use camel case and no spaces, there's also no need to be overly descriptive (e.g. `TopK` is enough in this case, on failure this will be printed as `TestVectorizeSpaceError/TopK` which is informative enough). It's also nice to use short names to minimize typing mistakes for when you need to rerun a subset of tests
___
*[pkg/sql/exec/mem_estimation.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjqtfHl9StEf92_JRnd:-LjqtfHl9StEf92_JRne:b-rzffnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/exec/mem_estimation.go#L32)):*
> ```Go
> 			// much space each byte array takes up. Use some default value as a
> 			// heuristic right now.
> 			acc += 100
> ```

I would put a big warning at the top that this function only really works for fixed-width types and maybe mention that there will be a transition to specifying batch sizes in terms of bytes, which will remove the need for any estimation.
___
*[pkg/sql/exec/mem_estimation.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljqtj8J3LkSvUo6xfGh:-Ljqtj8J3LkSvUo6xfGi:bfy5cdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/exec/mem_estimation.go#L36)):*
> ```Go
> 			acc++
> 		case types.Int16:
> 			acc += 2
> ```

nit: You could improve readability by extracting constants and using them here:
```
const (
	sizeOfInt8    = int(unsafe.Sizeof(int8(0)))
	sizeOfInt16   = int(unsafe.Sizeof(int16(0)))
	sizeOfInt32   = int(unsafe.Sizeof(int32(0)))
	sizeOfInt64   = int(unsafe.Sizeof(int64(0)))
	sizeOfFloat32 = int(unsafe.Sizeof(float32(0)))
	sizeOfFloat64 = int(unsafe.Sizeof(float64(0)))
)
```


<!-- Sent from Reviewable.io -->

2019-07-15 21:06 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec/mem_estimation.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjqtfHl9StEf92_JRnd:-LjrB9Vn3LYMroe5L6Dk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/exec/mem_estimation.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would put a big warning at the top that this function only really works for fixed-width types and maybe mention that there will be a transition to specifying batch sizes in terms of bytes, which will remove the need for any estimation.
</blockquote></details>

Done.
___
*[pkg/sql/exec/mem_estimation.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljqtj8J3LkSvUo6xfGh:-LjrB9sp9SGoemQ1oPST:b-jfi83l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ee86130b7e0ba2dc1cd534f84b908ef86519202/pkg/sql/exec/mem_estimation.go#L36)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: You could improve readability by extracting constants and using them here:
```
const (
	sizeOfInt8    = int(unsafe.Sizeof(int8(0)))
	sizeOfInt16   = int(unsafe.Sizeof(int16(0)))
	sizeOfInt32   = int(unsafe.Sizeof(int32(0)))
	sizeOfInt64   = int(unsafe.Sizeof(int64(0)))
	sizeOfFloat32 = int(unsafe.Sizeof(float32(0)))
	sizeOfFloat64 = int(unsafe.Sizeof(float64(0)))
)
```
</blockquote></details>

Ok, I wasn't sure if it was ok to use the unsafe package or not.


<!-- Sent from Reviewable.io -->

2019-07-15 21:07 UTC, rohany commented
RFAL -- followed alfonso's suggestion, and the code seems cleaner than before.

2019-07-16 15:26 UTC, asubiotto requested changes
Nice, I think it does look cleaner although this is making me think that fully integrating #38394 into the allocation flow will probably be beneficial for streaming operators as well to both verify that memory declared is not too far off from actual memory requested (this would be great for logic tests)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-:-LjvLNDBChhT3bae4O2P:b-bz6syg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljv3BWN1mE2_eLjEiOo:-Ljv3BWN1mE2_eLjEiOp:b-a8i8ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L102)):*
> ```Go
> 	spec *distsqlpb.ProcessorSpec,
> 	inputs []exec.Operator,
> ) (exec.Operator, []types.T, int, error) {
> ```

Seems like we might as well make these named return variables at this point
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 479 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljv4v6A5b1NWXEPc_TT:-Ljv4v6B6Xyvp3L6WT23:bw14615) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L479)):*
> ```Go
> 	// After constructing the base operator, calculate the memory usage
> 	// of the operator.
> 	if sMemOp, ok := op.(exec.StaticMemoryOperator); ok {
> ```

When we talked about this, did we mention that we sometimes created multiple operators in the above switch? Skimming it, I see it in the windower case, which is not something we care about right now but want to be sure we're not missing a case in the static operator creation.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljv5SR5B9e-48PJVqIh:-Ljv5SR6C36TMqlLIzQ8:b6qro4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L495)):*
> ```Go
> 	if !post.Filter.Empty() {
> 		var helper exprHelper
> 		var memUsed int
> ```

nit: `s/memUsed/selectionMem` or something similar. Also, another way to declare variables on multiple lines is:
```
var (
    helper exprHelper
    memUsed int
)
```
Up to you
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 919 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvCepG7q_57rEOzXj3:-LjvCepG7q_57rEOzXj4:bbodibd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L919)):*
> ```Go
> 				return nil, nil, memUsed, err
> 			}
> 			inbox, err := colrpc.NewInbox(conv.FromColumnTypes(input.ColumnTypes))
> ```

I think we need to account for the static memory used by the `inbox` here as well, otherwise we won't be counting remote data.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1064 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvB8c-1pSnfprlUMuX:-LjvB8c-1pSnfprlUMuY:b-exfpuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L1064)):*
> ```Go
> 			}
> 			if err = acc.Grow(ctx, int64(memUsed)); err != nil {
> 				return errors.Wrapf(err, "Not enough memory to setup vectorized plan.")
> ```

nit: error message aren't capitalized or have punctuation by convention (https://github.com/golang/go/wiki/CodeReviewComments#error-strings)
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvJxLOBDfWffPXTJbx:-LjvJxLOBDfWffPXTJby:b7hb1c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L28)):*
> ```Go
> )
> 
> func TestVectorizeSpaceError(t *testing.T) {
> ```

I wonder if there's a way to do some black box testing of this addition (maybe not now). This will probably be easier with the addition of @solongordon's BatchAllocator but if we had some way to globally track the batches actually allocated, we could probably add a testing knob to logic tests similar to metadata verification that would then verify that memory usage reported to the monitor is around what was requested from the BatchAllocator.
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvEYAM4jnE6byxGBNk:-LjvEYAM4jnE6byxGBNl:be9b7u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L108)):*
> ```Go
> 		},
> 		{
> 			desc: "aggergation",
> ```

`s/aggergation/aggregation`
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvG5HC4RZTyq7bwEt5:-LjvG5HD19BaWBT6d6A6:bqia4nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L127)):*
> ```Go
> 						ctx, "Unlimited Monitor", mon.MemoryResource, nil, nil, math.MaxInt64, st)
> 				} else {
> 					memMon = mon.MakeMonitorWithLimit(
> ```

It's a bit subtle, but hard-limit monitors like this one are only used in processors that fall back to disk. To mirror the monitor that is used in `setupVectorized` you have to do something like:
```
memMon := mon.MakeMonitor(...)
if succ {
    memMon.Start(..., mon.MakeStandaloneBudget(math.MaxInt64))
} else {
    memMon.Start(..., mon.MakeStandaloneBudget(1))
}
defer memMon.Stop()
```
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvEvWCDxm2VPiJIo37:-LjvEvWCDxm2VPiJIo38:b-79gg5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L134)):*
> ```Go
> 				err = acc.Grow(ctx, int64(memUsed))
> 				if succ && err != nil {
> 					t.Fatal("Expected success, found: ", err)
> ```

nit: I think this will print double spaces


<!-- Sent from Reviewable.io -->

2019-07-16 16:54 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljv3BWN1mE2_eLjEiOo:-LjvbwrK-5ARus7QQYeU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Seems like we might as well make these named return variables at this point
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 479 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Ljv4v6A5b1NWXEPc_TT:-LjvPYKb0lmtW-mSgz-T:b-3ilazd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L479)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

When we talked about this, did we mention that we sometimes created multiple operators in the above switch? Skimming it, I see it in the windower case, which is not something we care about right now but want to be sure we're not missing a case in the static operator creation.
</blockquote></details>

I went through the cases and made sure to increment the memory usage when we layer operators, or a StaticMemoryOperator gets layered over.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 919 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvCepG7q_57rEOzXj3:-Ljve_4E3ILkAfRgBKvk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/column_exec_setup.go#L919)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we need to account for the static memory used by the `inbox` here as well, otherwise we won't be counting remote data.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvEYAM4jnE6byxGBNk:-Ljve7w59demzeECCwPx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L108)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/aggergation/aggregation`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/flow_vectorize_space_test.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-LjvG5HC4RZTyq7bwEt5:-Ljve7Ui5HXSFAU2mpth:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c12409020547cf2651e736b7eab3259acd49ff0/pkg/sql/distsqlrun/flow_vectorize_space_test.go#L127)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's a bit subtle, but hard-limit monitors like this one are only used in processors that fall back to disk. To mirror the monitor that is used in `setupVectorized` you have to do something like:
```
memMon := mon.MakeMonitor(...)
if succ {
    memMon.Start(..., mon.MakeStandaloneBudget(math.MaxInt64))
} else {
    memMon.Start(..., mon.MakeStandaloneBudget(1))
}
defer memMon.Stop()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-17 15:01 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-:-Lk-RyuP0EQ8BRk8qwoD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1108 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38796#-Lk-Ri5g2EExL8sxAA4k:-Lk-Ri5g2EExL8sxAA4l:bt5fepo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f1d295c3df6e066144df1fd5a1445b77b1e8ddf/pkg/sql/distsqlrun/column_exec_setup.go#L1108)):*
> ```Go
> 		op, outputTypes, memUsage, err := newColOperator(ctx, &f.FlowCtx, pspec, inputs)
> 		if err != nil {
> 			return errors.Wrapf(err, "Unable to vectorize execution plan.")
> ```

nit: same thing here and below about the error messages


<!-- Sent from Reviewable.io -->

2019-07-17 16:50 UTC, rohany commented
bors r=asubiotto

2019-07-17 17:19 UTC, merged

2019-07-17 19:17 UTC, asubiotto commented
Something I just realized: I think we might need to close the vectorized bound account on setup error as well, otherwise we'll never clear the memory when we fail to set up a vectorized flow in some cases. Failures on remote nodes won't ever call `Cleanup` on an error, the only case I can think of that might be fine is when falling back to distsql on gateway nodes, since we use the same flow struct, but that still means that we'll have extra accounted for memory during the execution of that flow.

2019-07-17 19:44 UTC, asubiotto commented
I'm touching this code now so will fix.

2019-07-17 21:10 UTC, rohany commented
That makes sense -- good catch.