exec: minor cleanup of merge joiner
cockroachdb/cockroach pull request #38856
Opened 2019-07-12 21:55 UTC by yuzefovich

First commit puts all template variables in caps so that it is easier to distinguish them.

Second commit templates out building from null groups in merge joiner. Null groups cannot occur either on the left, on the right, or on both sides (depending on the join type), so now we're templating out a check that would happen on every tuple.

Third commit removes redundant join type field in merge join base struct.

2019-07-12 21:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38856)
<!-- Reviewable:end -->

2019-07-12 21:56 UTC, yuzefovich commented
I also run the benchmarks for all of the join types:
```
BenchmarkMergeJoiner/INNER/rows=1024-12         	   50000	     31934 ns/op	2052.22 MB/s
BenchmarkMergeJoiner/INNER/rows=4096-12         	   10000	    112055 ns/op	2339.41 MB/s
BenchmarkMergeJoiner/INNER/rows=16384-12        	    3000	    413377 ns/op	2536.61 MB/s
BenchmarkMergeJoiner/INNER/rows=1048576-12      	      50	  28552394 ns/op	2350.38 MB/s
BenchmarkMergeJoiner/INNER/oneSideRepeat-rows=1024-12         	   50000	     32350 ns/op	2025.81 MB/s
BenchmarkMergeJoiner/INNER/oneSideRepeat-rows=4096-12         	   10000	    114211 ns/op	2295.25 MB/s
BenchmarkMergeJoiner/INNER/oneSideRepeat-rows=16384-12        	    3000	    420962 ns/op	2490.90 MB/s
BenchmarkMergeJoiner/INNER/oneSideRepeat-rows=1048576-12      	      50	  29466267 ns/op	2277.48 MB/s
BenchmarkMergeJoiner/INNER/bothSidesRepeat-rows=1024-12       	   50000	     32427 ns/op	2021.01 MB/s
BenchmarkMergeJoiner/INNER/bothSidesRepeat-rows=4096-12       	   10000	    132466 ns/op	1978.95 MB/s
BenchmarkMergeJoiner/INNER/bothSidesRepeat-rows=16384-12      	    2000	    757038 ns/op	1385.10 MB/s
BenchmarkMergeJoiner/INNER/bothSidesRepeat-rows=32768-12      	    1000	   2197048 ns/op	 954.53 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/rows=1024-12                  	   50000	     37650 ns/op	1740.65 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/rows=4096-12                  	   10000	    133856 ns/op	1958.40 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/rows=16384-12                 	    3000	    478468 ns/op	2191.53 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/rows=1048576-12               	      50	  30452843 ns/op	2203.70 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/oneSideRepeat-rows=1024-12    	   50000	     36325 ns/op	1804.12 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/oneSideRepeat-rows=4096-12    	   10000	    126001 ns/op	2080.49 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/oneSideRepeat-rows=16384-12   	    3000	    450628 ns/op	2326.92 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/oneSideRepeat-rows=1048576-12 	      50	  29538627 ns/op	2271.90 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/bothSidesRepeat-rows=1024-12  	   50000	     35319 ns/op	1855.53 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/bothSidesRepeat-rows=4096-12  	   10000	    123800 ns/op	2117.47 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/bothSidesRepeat-rows=16384-12 	    2000	    740949 ns/op	1415.18 MB/s
BenchmarkMergeJoiner/LEFT_OUTER/bothSidesRepeat-rows=32768-12 	    1000	   2136348 ns/op	 981.65 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/rows=1024-12                 	   50000	     38992 ns/op	1680.75 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/rows=4096-12                 	   10000	    136561 ns/op	1919.60 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/rows=16384-12                	    3000	    481571 ns/op	2177.41 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/rows=1048576-12              	      50	  30794713 ns/op	2179.23 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/oneSideRepeat-rows=1024-12   	   50000	     36740 ns/op	1783.76 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/oneSideRepeat-rows=4096-12   	   10000	    128933 ns/op	2033.17 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/oneSideRepeat-rows=16384-12  	    3000	    465381 ns/op	2253.16 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/oneSideRepeat-rows=1048576-12         	      50	  31021596 ns/op	2163.29 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/bothSidesRepeat-rows=1024-12          	   50000	     35751 ns/op	1833.12 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/bothSidesRepeat-rows=4096-12          	   10000	    128185 ns/op	2045.03 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/bothSidesRepeat-rows=16384-12         	    2000	    790992 ns/op	1325.65 MB/s
BenchmarkMergeJoiner/RIGHT_OUTER/bothSidesRepeat-rows=32768-12         	     500	   2314237 ns/op	 906.20 MB/s
BenchmarkMergeJoiner/FULL_OUTER/rows=1024-12                           	   50000	     37815 ns/op	1733.04 MB/s
BenchmarkMergeJoiner/FULL_OUTER/rows=4096-12                           	   10000	    133511 ns/op	1963.46 MB/s
BenchmarkMergeJoiner/FULL_OUTER/rows=16384-12                          	    3000	    470793 ns/op	2227.25 MB/s
BenchmarkMergeJoiner/FULL_OUTER/rows=1048576-12                        	      50	  30221691 ns/op	2220.55 MB/s
BenchmarkMergeJoiner/FULL_OUTER/oneSideRepeat-rows=1024-12             	   50000	     36192 ns/op	1810.74 MB/s
BenchmarkMergeJoiner/FULL_OUTER/oneSideRepeat-rows=4096-12             	   10000	    124928 ns/op	2098.35 MB/s
BenchmarkMergeJoiner/FULL_OUTER/oneSideRepeat-rows=16384-12            	    3000	    448907 ns/op	2335.84 MB/s
BenchmarkMergeJoiner/FULL_OUTER/oneSideRepeat-rows=1048576-12          	      50	  29549945 ns/op	2271.03 MB/s
BenchmarkMergeJoiner/FULL_OUTER/bothSidesRepeat-rows=1024-12           	   50000	     34483 ns/op	1900.51 MB/s
BenchmarkMergeJoiner/FULL_OUTER/bothSidesRepeat-rows=4096-12           	   10000	    127425 ns/op	2057.23 MB/s
BenchmarkMergeJoiner/FULL_OUTER/bothSidesRepeat-rows=16384-12          	    2000	    724216 ns/op	1447.88 MB/s
BenchmarkMergeJoiner/FULL_OUTER/bothSidesRepeat-rows=32768-12          	    1000	   2093167 ns/op	1001.90 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/rows=1024-12                            	  100000	     21607 ns/op	3033.02 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/rows=4096-12                            	   20000	     68839 ns/op	3808.03 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/rows=16384-12                           	    5000	    249367 ns/op	4204.94 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/rows=1048576-12                         	     100	  15707100 ns/op	4272.52 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/oneSideRepeat-rows=1024-12              	  100000	     19986 ns/op	3278.97 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/oneSideRepeat-rows=4096-12              	   20000	     65554 ns/op	3998.85 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/oneSideRepeat-rows=16384-12             	    5000	    240686 ns/op	4356.60 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/oneSideRepeat-rows=1048576-12           	     100	  15891279 ns/op	4223.00 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/bothSidesRepeat-rows=1024-12            	  100000	     19296 ns/op	3396.21 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/bothSidesRepeat-rows=4096-12            	   50000	     37000 ns/op	7084.97 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/bothSidesRepeat-rows=16384-12           	   10000	    107634 ns/op	9742.02 MB/s
BenchmarkMergeJoiner/LEFT_SEMI/bothSidesRepeat-rows=32768-12           	   10000	    217243 ns/op	9653.48 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/rows=1024-12                            	  100000	     23084 ns/op	2838.99 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/rows=4096-12                            	   20000	     74771 ns/op	3505.92 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/rows=16384-12                           	    5000	    271433 ns/op	3863.10 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/rows=1048576-12                         	     100	  16615596 ns/op	4038.91 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/oneSideRepeat-rows=1024-12              	  100000	     21929 ns/op	2988.55 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/oneSideRepeat-rows=4096-12              	   20000	     71695 ns/op	3656.34 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/oneSideRepeat-rows=16384-12             	    5000	    261798 ns/op	4005.28 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/oneSideRepeat-rows=1048576-12           	     100	  17008788 ns/op	3945.54 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/bothSidesRepeat-rows=1024-12            	  100000	     21309 ns/op	3075.46 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/bothSidesRepeat-rows=4096-12            	   50000	     25264 ns/op	10375.97 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/bothSidesRepeat-rows=16384-12           	   30000	     54364 ns/op	19288.01 MB/s
BenchmarkMergeJoiner/LEFT_ANTI/bothSidesRepeat-rows=32768-12           	   20000	     93173 ns/op	22507.96 MB/s
PASS
ok  	github.com/cockroachdb/cockroach/pkg/sql/exec	341.998s
```

2019-07-22 15:09 UTC, jordanlewis requested changes
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38856)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner.go, line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPDXzf6PGdpuUnY8Lx:-LkPDXzgBCjkPYSushAL:b-vy2eu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7362fa958cd7a8a0260dce0b217bf2dfb8165d/pkg/sql/exec/mergejoiner.go#L247)):*
> ```Go
> 
> func newMergeJoinBase(
> 	joinType sqlbase.JoinType,
> ```

This is excellent. It validates our templating work to know that we don't need to know the join type at runtime.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 628 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPCsN_Bq1m-DycDApP:-LkPCsN_Bq1m-DycDApQ:bdm0tq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea233aec9e43351f316331d38776020ad4737ef2/pkg/sql/exec/mergejoiner_tmpl.go#L628)):*
> ```Go
> 				// Null groups on the left can only occur with RIGHT OUTER and FULL
> 				// OUTER joins for both of which IsRightOuter is true. For other joins,
> 				// we're omitting this check.
> ```

Nice idea.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPDKSY5y5k65Ec8MFk:-LkPDKSY5y5k65Ec8MFl:bqo7oai) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea233aec9e43351f316331d38776020ad4737ef2/pkg/sql/exec/mergejoiner_tmpl.go#L634)):*
> ```Go
> 					outStartIdx += toAppend
> 				} else {
> 					// {{ end }}
> ```

nit: you can have the {{end}} come before the second `{`, and then omit the `}` below, since in Go you can have a block that looks like:
```
{
  some code that goes here
}
```
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 778 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPDSEm7uksfV-w9yff:-LkPDSEm7uksfV-w9yfg:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea233aec9e43351f316331d38776020ad4737ef2/pkg/sql/exec/mergejoiner_tmpl.go#L778)):*
> ```Go
> 					out.Nulls().SetNullRange(uint64(outStartIdx), uint64(outStartIdx+toAppend))
> 				} else {
> 					// {{ end }}
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-07-22 15:09 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (oops, I did not mean to "request changes".)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-:-LkPDejz9Fv0giZnlvW2:b-l4y236)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-07-22 18:29 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38856)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 634 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPDKSY5y5k65Ec8MFk:-LkPwKYU2ugOcGirXuLW:b-ol9l4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea233aec9e43351f316331d38776020ad4737ef2/pkg/sql/exec/mergejoiner_tmpl.go#L634)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: you can have the {{end}} come before the second `{`, and then omit the `}` below, since in Go you can have a block that looks like:
```
{
  some code that goes here
}
```
</blockquote></details>

Nice! Done.
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 778 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38856#-LkPDSEm7uksfV-w9yff:-LkPwMrEDr0vgLY9ruws:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea233aec9e43351f316331d38776020ad4737ef2/pkg/sql/exec/mergejoiner_tmpl.go#L778)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-22 18:55 UTC, yuzefovich commented
TFTR!

bors r+

2019-07-22 20:06 UTC, yuzefovich commented
bors r+

2019-07-22 20:37 UTC, merged