exec: switch Bytes representation from [][]byte to []byte + offsets
cockroachdb/cockroach pull request #38876
Opened 2019-07-15 17:33 UTC by asubiotto

This gives us much faster serialization and the ability to account for memory used in O(1). Look at the individual commits for details.

Closes #37704

2019-07-15 17:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/38876)
<!-- Reviewable:end -->

2019-07-15 17:35 UTC, asubiotto commented
I still want to audit the `Set` patterns as a very obvious one: `NewMemBatch`, setting all elements, then resetting all elements in that batch in the next `Next` call  will lead to very high memory usage (due to constantly appending given that the bytes will be set out of order). We might need to add a `Reset()` method.

2019-07-15 18:57 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/coldata/bytes.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqiPRgCP6B4vdLBG4b:-LjqiPRgCP6B4vdLBG4c:b-bfbpag) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L33)):*
> ```
> new
> ```
Do we have anything in our guidelines about reusing the name of a built-in function? In this case it seems extremely unlikely to cause any issue since it's a one-line function, but just wondering.
___
*[pkg/sql/exec/coldata/bytes.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqioeB-kZM5RlcaVXN:-LjqioeB-kZM5RlcaVXO:bt6aqss) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L48)):*
> ```Go
> }
> 
> // CopySlice copies srcStartIdx inclusive and srcEndIdx inclusive []byte values
> ```

isn't it exclusive to srcEndIdx? same for AppendSlice
___
*[pkg/sql/exec/coldata/bytes.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqkE1I4-j-5BB5DiwK:-LjqkE1I4-j-5BB5DiwL:b-i787k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L70)):*
> ```Go
> }
> 
> var zeroBytesColumn = make([][]byte, BatchSize)
> ```

i guess it doesn't make sense to export and reuse the one in pkg/sql/exec/zerocolumns.eg.go ... seems like it wouldn't be worth the effort but just floating the idea
___
*[pkg/sql/exec/coldata/bytes.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqt9mQ61JzhqeITN8T:-Ljqt9mQ61JzhqeITN8U:bh94mng) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L98)):*
> ```Go
> // kept around.
> func (b *Bytes) CopySlice(src *Bytes, destIdx, srcStartIdx, srcEndIdx int) {
> 	if destIdx > b.Len() {
> ```

would it be useful to also check negative indices here? and that srcEndIdx >= srcStartIdx? (same for AppendSlice)
___
*[pkg/sql/exec/coldata/bytes.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqyIgMDHvHFHe1kl4z:-LjqyIgMDHvHFHe1kl5-:b-dbfis4) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L146)):*
> ```Go
> 		v := src.data[src.offsets[j] : src.offsets[j]+src.lengths[j]]
> 		b.offsets[i] = int32(len(b.data))
> 		b.lengths[i] = int32(len(v))
> ```

will this be ok if `b` and `src` refer to the same `Bytes`? it seems like yes to me, but maybe a test case for that is worth adding
___
*[pkg/sql/exec/coldata/bytes.go, line 186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqwh80761juUMLJ7aj:-Ljqwh80761juUMLJ7ak:buvrs4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L186)):*
> ```Go
> 
> 	if !b.outOfOrder && !src.outOfOrder {
> 		destEnd := b.offsets[destIdx-1] + b.lengths[destIdx-1]
> ```

nit: maybe a name like destDataEnd would be more clear, so that it's more apparent that it indexes into `data`, as opposed to destIdx, which indexes into `offsets` and `lengths`.
___
*[pkg/sql/exec/coldata/bytes.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqx8Ae4h_774SuT6Ek:-Ljqx8Af3CYrLprF9Wlo:b-ajh6d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L202)):*
> ```Go
> 
> 	if src.outOfOrder {
> 		b.outOfOrder = src.outOfOrder
> ```

could the if be replaced by `b.outOfOrder = b.outOfOrder || src.outOfOrder` ?
___
*[pkg/sql/exec/coldata/bytes_test.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqzC0g3vDpvMKCDt6F:-LjqzC0g3vDpvMKCDt6G:b-l00mm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes_test.go#L59)):*
> ```
>  b2 [][]byte, b2source [][]byte
> ```

nit: the type can be declared once
___
*[pkg/sql/exec/execgen/cmd/execgen/data_manipulation_gen.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqleq3CXP7MOY4Hdpe:-Ljqleq3CXP7MOY4Hdpf:b5v6l54) ([raw file](https://github.com/cockroachdb/cockroach/blob/418f67991f090f2b5d0ef05fdaa7e4d290e1c394/pkg/sql/exec/execgen/cmd/execgen/data_manipulation_gen.go#L83)):*
> ```Go
> 		placeHolderArgs := make([]string, dmri.numArgs)
> 		templResultArgs := make([]string, dmri.numArgs)
> 		for i := 0; i < dmri.numArgs; i++ {
> ```

this seems a bit similar to `makeFunctionRegex`, could that get reused somehow?


<!-- Sent from Reviewable.io -->

2019-07-16 17:33 UTC, danhhz commented
Have you looked into the allocation increase in ArrowToBatch?

2019-07-16 18:26 UTC, asubiotto commented
@danhhz not yet but it's on my list after the `Reset` stuff. Most likely it's just the allocation of `lengths`, I refactored to reuse a passed in *Bytes but forgot to change that part.

2019-07-16 22:22 UTC, yuzefovich reviewed
I took a quick look at some commits, a couple of nits from me.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 10 of 42 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LjwsAO120scSJN6E-Ja:b-19gky9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/coldata/bytes.go, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjtKcsB4OaahDE2aFux:-LjtKcsB4OaahDE2aFuy:b-oa0n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L6)):*
> ```Go
> // in the file licenses/BSL.txt and at www.mariadb.com/bsl11.
> //
> // Change Date: 2022-10-01
> ```

[nit]: the header has been updated.
___
*[pkg/sql/exec/execgen/placeholders.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjtMAKiB3iQKQndLK9r:-LjtMAKiB3iQKQndLK9s:bmby28c) ([raw file](https://github.com/cockroachdb/cockroach/blob/418f67991f090f2b5d0ef05fdaa7e4d290e1c394/pkg/sql/exec/execgen/placeholders.go#L15)):*
> ```Go
> const nonTemplatePanic = "do not call from non-template code"
> 
> func GET(target, i interface{}) interface{} {
> ```

[nit]: I think we tend to use underscores (i.e. "_GET", "_COPY_SLICE") to highlight template-internal stuff, not sure if it applies here though.


<!-- Sent from Reviewable.io -->

2019-07-17 18:31 UTC, asubiotto reviewed
OK fixed the allocations (and updated the commit message) and responded to comments. I still need to do the `Reset` thing which I think will end up being part of a batch contract and go hand in hand with resetting the selection vector when returning internal batches, but this is RFAL otherwise. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-Lk0BZWm7iDI6QEOPH4W:bjxauc6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/sql/exec/coldata/bytes.go, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjtKcsB4OaahDE2aFux:-Lk0BUdy78kx5ghvvJCb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L6)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the header has been updated.
</blockquote></details>

Done.
___
*[pkg/sql/exec/coldata/bytes.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqiPRgCP6B4vdLBG4b:-Ljr0tW5D95ze9tCKF2x:bymqbdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> ```
> new
> ```
Do we have anything in our guidelines about reusing the name of a built-in function? In this case it seems extremely unlikely to cause any issue since it's a one-line function, but just wondering.
</blockquote></details>

Not sure there are guidelines, but definitely not something we want to do. Changed this.
___
*[pkg/sql/exec/coldata/bytes.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqioeB-kZM5RlcaVXN:-Lk-G6au0LGmE6ria6gN:bb71nyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L48)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

isn't it exclusive to srcEndIdx? same for AppendSlice
</blockquote></details>

Oops
___
*[pkg/sql/exec/coldata/bytes.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqkE1I4-j-5BB5DiwK:-Lk-DWYWD8sIf2XaBZ74:b58ddcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c280741c80bd62ce86e01ab4c84ef33f73fa84a/pkg/sql/exec/coldata/bytes.go#L70)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i guess it doesn't make sense to export and reuse the one in pkg/sql/exec/zerocolumns.eg.go ... seems like it wouldn't be worth the effort but just floating the idea
</blockquote></details>

Yeah, I don't think so. That would also introduce an import dependency so if we were to do that we'd probably want to have these zeros in `coldata` at which point you wonder if it's worth it.
___
*[pkg/sql/exec/coldata/bytes.go, line 98 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqt9mQ61JzhqeITN8T:-Lk0AyPN3aD7VQjVBnz_:b-k5rtp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L98)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be useful to also check negative indices here? and that srcEndIdx >= srcStartIdx? (same for AppendSlice)
</blockquote></details>

Why not. Done.
___
*[pkg/sql/exec/coldata/bytes.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqyIgMDHvHFHe1kl4z:-Lk-FbvB3M2mKPQXSU7r:bgrpu39) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

will this be ok if `b` and `src` refer to the same `Bytes`? it seems like yes to me, but maybe a test case for that is worth adding
</blockquote></details>

Definitely, turned up a bug which made me change the contract of `Slice` PTAL.
___
*[pkg/sql/exec/coldata/bytes.go, line 186 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqwh80761juUMLJ7aj:-Lk-EFUiDptWl9_qgi3U:b-lt9xtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L186)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: maybe a name like destDataEnd would be more clear, so that it's more apparent that it indexes into `data`, as opposed to destIdx, which indexes into `offsets` and `lengths`.
</blockquote></details>

Done. Renamed to `destDataIdx`
___
*[pkg/sql/exec/coldata/bytes.go, line 202 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqx8Ae4h_774SuT6Ek:-Lk-Dgzw4nIjrmJRc3bO:bmfg1ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes.go#L202)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could the if be replaced by `b.outOfOrder = b.outOfOrder || src.outOfOrder` ?
</blockquote></details>

Yes, good call.
___
*[pkg/sql/exec/coldata/bytes_test.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjqzC0g3vDpvMKCDt6F:-Lk-DKfCD2YBTLp6TMKi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/75dea04c9d57f63fff63db5c7afb4833b2293ff3/pkg/sql/exec/coldata/bytes_test.go#L59)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> ```
>  b2 [][]byte, b2source [][]byte
> ```

nit: the type can be declared once
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/placeholders.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjtMAKiB3iQKQndLK9r:-Lk-C7bK6DSAj4UDh5NC:b-9h6wnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/418f67991f090f2b5d0ef05fdaa7e4d290e1c394/pkg/sql/exec/execgen/placeholders.go#L15)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I think we tend to use underscores (i.e. "_GET", "_COPY_SLICE") to highlight template-internal stuff, not sure if it applies here though.
</blockquote></details>

You're right, but adding underscores would make these private functions. Since usage looks like `execgen.GET`, I think it's clear that these should be used as template variables.
___
*[pkg/sql/exec/execgen/cmd/execgen/data_manipulation_gen.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Ljqleq3CXP7MOY4Hdpe:-Lk-BgWp0_9AaoAtTJE2:b-go5816) ([raw file](https://github.com/cockroachdb/cockroach/blob/418f67991f090f2b5d0ef05fdaa7e4d290e1c394/pkg/sql/exec/execgen/cmd/execgen/data_manipulation_gen.go#L83)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this seems a bit similar to `makeFunctionRegex`, could that get reused somehow?
</blockquote></details>

Good call, missed that function. However, I need to loop to construct the `replaceWith` string so might as well create the regex there than add a second loop.


<!-- Sent from Reviewable.io -->

2019-07-18 19:51 UTC, asubiotto commented
Added the `Reset` method PTAL. This PR is a pain to rebase, so please ignore the file conflicts, I will resolve them when the PR is ready to merge.

2019-07-19 15:09 UTC, jordanlewis reviewed
Really great work Alfonso. This is headed in an excellent direction.

I've reviewed most of this but want to take another pass. I'm also concerned that the complex manipulation methods on the type might be undertested. Would you run a coverage build to see if we're hitting all of the paths?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-Lk9loLr8ZO3ObScvDQv:bodcat0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 97 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9f_DQC-slwZ8rxjb7:-Lk9f_DQC-slwZ8rxjb8:b96s2po) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/any_not_null_agg_tmpl.go#L97)):*
> ```Go
> 	if a.curIdx != -1 {
> 		a.curIdx = idx
> 		vecLen := execgen.LEN(a.vec)
> ```

Oh man, this is such a great idea for how to make this stuff look reasonable. Really into it - nice!
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9jnQA-KsoI5Z-IwWu:-Lk9jnQA-KsoI5Z-IwWv:b-gq0t6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/hashjoiner_tmpl.go#L75)):*
> ```Go
> 	// {{define "checkColMain"}}
> 	buildVal := execgen.GET(buildKeys, int(keyID-1))
> 	selIdx := _SEL_IND
> ```

How come you have to do this second assignment?
___
*[pkg/sql/exec/sort_tmpl.go, line 155 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9kWZB9pBYUhp2YBi-:-Lk9kWZB9pBYUhp2YBi0:be6x62h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/sort_tmpl.go#L155)):*
> ```Go
> 	arg1 := execgen.GET(s.sortCol, i)
> 	arg2 := execgen.GET(s.sortCol, j)
> 	_ASSIGN_LT("lt", "arg1", "arg2")
> ```

I think we should consdering changing this to be `execgen.ASSIGN_LT` eventually. This would start to make some sense out of the madness.
___
*[pkg/sql/exec/coldata/bytes.go, line 259 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9lFLkD-_RB-fiTmVu:-Lk9lFLkD-_RB-fiTmVv:b-28buod) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/coldata/bytes.go#L259)):*
> ```Go
> func (b Bytes) Zero() {
> 	b.data = b.data[:0]
> 	for n := 0; n < len(b.offsets); n += copy(b.offsets[n:], zeroInt32Slice) {
> ```

I think if you benchmarked this you *might* find that a simple for loop was the same speed, but I'm not completely sure.
___
*[pkg/sql/exec/execgen/placeholders.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LjtMAKiB3iQKQndLK9r:-Lk9l_qT3J_yXjokTh0X:b11rj3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/418f67991f090f2b5d0ef05fdaa7e4d290e1c394/pkg/sql/exec/execgen/placeholders.go#L15)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You're right, but adding underscores would make these private functions. Since usage looks like `execgen.GET`, I think it's clear that these should be used as template variables.
</blockquote></details>

Yeah, I agree with ALfonso. I really like this convention. No need for leading undescore if there's an unambiguous package prefix.
___
*[pkg/sql/exec/types/types.go, line 115 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9f9zS6N8FleZw9twR:-Lk9f9zS6N8FleZw9twS:biw1nto) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/types/types.go#L115)):*
> ```Go
> 
> // GoTypeSliceName returns how a slice of the receiver type is represented.
> func (t T) GoTypeSliceName() string {
> ```

I like this. Should we switch `types.T` to a interface and have a default and non default implementation? That would allow us to remove these conditionals and have `types.Bytes` implement each of these things differently. And these would all be execgen time things so no worries about performance.


<!-- Sent from Reviewable.io -->

2019-07-29 15:23 UTC, asubiotto reviewed
Is there a specific path you're worried about? I'm doing randomized testing against a `[][]byte` "reference" for all methods listed at the top of `bytes_test`. Unsure how to get real coverage as one run won't mirror what we'd get out of `make stress`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LkyFQqd1yWP9wOREXPQ:b3csn85)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/sql/exec/any_not_null_agg_tmpl.go, line 97 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9f_DQC-slwZ8rxjb7:-LkyGz0q0QNum9KKuq6J:b4gnk75) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/any_not_null_agg_tmpl.go#L97)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh man, this is such a great idea for how to make this stuff look reasonable. Really into it - nice!
</blockquote></details>

Glad you like it!
___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9jnQA-KsoI5Z-IwWu:-LkyH-FUE_qjnfQUvjUU:b-wtfqqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/hashjoiner_tmpl.go#L75)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

How come you have to do this second assignment?
</blockquote></details>

`_SEL_IND` won't get replaced otherwise, but I'm not quite sure why not.
___
*[pkg/sql/exec/coldata/bytes.go, line 259 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9lFLkD-_RB-fiTmVu:-LkyHA_62_1qCDb0PGwF:b9i6abz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/coldata/bytes.go#L259)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think if you benchmarked this you *might* find that a simple for loop was the same speed, but I'm not completely sure.
</blockquote></details>

Hmm, how come? I remember benchmarking when we reset slices to zero in the aggregator and the `copy` was much faster.
___
*[pkg/sql/exec/types/types.go, line 115 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9f9zS6N8FleZw9twR:-LkyIWy37TCg_1rmQ1Yn:b7nqmia) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/types/types.go#L115)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I like this. Should we switch `types.T` to a interface and have a default and non default implementation? That would allow us to remove these conditionals and have `types.Bytes` implement each of these things differently. And these would all be execgen time things so no worries about performance.
</blockquote></details>

Yeah, I think that would be nice but at the same time I'm hoping that we'd just have all this be part of the templating infrastructure after we switch the map direction (i.e. instead of mapping from overloads to types, map from types to overloads with redefined implementations for types that need it). I don't think I want to touch that in this PR unless you think it's necessary.


<!-- Sent from Reviewable.io -->

2019-07-29 15:24 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9jnQA-KsoI5Z-IwWu:-LkyK0QU1cIfz6ZI3HDs:b836mcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/hashjoiner_tmpl.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`_SEL_IND` won't get replaced otherwise, but I'm not quite sure why not.
</blockquote></details>

Oh, it's not that it won't get replaced, but we'll have a double bracket expression inside another double pracket expression, which is disallowed (i.e. {{ . Get {{ .SelInd }}}})


<!-- Sent from Reviewable.io -->

2019-07-29 15:43 UTC, jordanlewis reviewed
Can you up the number of runs in the randomized test case to a high number and then run coverage and see what you get? 

Also if this is a pain to keep rebasing, you could break out the manual refactor stuff to add the new get/set assign templates into a separate PR that could merge without a lot more back and forth. And same with the implementation of the bytes type.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LkyNjYZ6Mpt-oUKKJV3:b48z4t6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/sql/exec/hashjoiner_tmpl.go, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9jnQA-KsoI5Z-IwWu:-LkyNswd31VQsfV-u4Oa:b-7fmpv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/hashjoiner_tmpl.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oh, it's not that it won't get replaced, but we'll have a double bracket expression inside another double pracket expression, which is disallowed (i.e. {{ . Get {{ .SelInd }}}})
</blockquote></details>

Ah, ok cool
___
*[pkg/sql/exec/coldata/bytes.go, line 259 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9lFLkD-_RB-fiTmVu:-LkyNxER7dPXvgZp2pjW:b-1323hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/coldata/bytes.go#L259)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, how come? I remember benchmarking when we reset slices to zero in the aggregator and the `copy` was much faster.
</blockquote></details>

Oh yeah, I forgot about that :P nevermind
___
*[pkg/sql/exec/types/types.go, line 115 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lk9f9zS6N8FleZw9twR:-LkyO-9tDnYiRcrbF6uJ:b-j9usi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fc0f0830019243a0acc4dd29a38165df87c61d5/pkg/sql/exec/types/types.go#L115)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yeah, I think that would be nice but at the same time I'm hoping that we'd just have all this be part of the templating infrastructure after we switch the map direction (i.e. instead of mapping from overloads to types, map from types to overloads with redefined implementations for types that need it). I don't think I want to touch that in this PR unless you think it's necessary.
</blockquote></details>

Agreed not in this PR.


<!-- Sent from Reviewable.io -->

2019-07-29 15:57 UTC, asubiotto commented
That's a good idea, I'll rebase and do that. The coverage when commenting out the arrow batch converter stuff (which is tested in `TestArrowBatchConverter`) is at `82%` without `Reset` and `Zero` (`72.5%` with), I'll look at some ways to use these in testing and double checking what isn't covered.

2019-08-19 15:34 UTC, asubiotto commented
Added a deterministic test that bumps up coverage to `93%` which I'm happy with. Since we've now removed physical swaps in sorting, I explicitly disallow doing this and will remove `execgen.SWAP` in the future. The goal is to reduce complexity and unexpected performance hits incurred by out of order swaps.

I also wrote another flat bytes implementation that doesn't support out of order `Set`s but the execution engine currently relies on this in case of writing based on an out of order selection vector (e.g. builtin functions) so putting that on the back burner until we figure out what we want to do there. PTAL, I think this should be ready to merge.

2019-08-19 15:37 UTC, asubiotto commented
https://github.com/asubiotto/cockroach/tree/flatdata-noswap is the branch for the alternative implementation

2019-08-19 17:53 UTC, yuzefovich reviewed
Very nice work! I left a few comments.

> Reviewed 1 of 57 files at r11, 2 of 3 files at r12, 12 of 12 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-Lmf-P-5CSq-Xq2S59b1:bbb1za7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 21 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmf-myp0KTx23bA6CA4:-Lmf-myp0KTx23bA6CA5:b-he17z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L21)):*
> ```Go
> type Bytes struct {
> 	// data is the slice of all bytes
> 	data []byte
> ```

[nit]: missing period (in the line above).
___
*[pkg/col/coldata/bytes.go, line 26 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmf-jj-Ck8zLAh5_uZX:-Lmf-jj-Ck8zLAh5_uZY:b-1en1uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L26)):*
> ```Go
> 	// outOfOrder. If the offsets are in order, fast paths can be used in various
> 	// situations,
> 	offsets []int32
> ```

[nit]: `s/,/./` (in the line above).
___
*[pkg/col/coldata/bytes.go, line 88 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmeppnc8X1Ch3Wf-ENi:-Lmeppnc8X1Ch3Wf-ENj:blbpci8) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L88)):*
> ```Go
> 	b.offsets = b.offsets[start:end]
> 	b.lengths = b.lengths[start:end]
> 	b.maxSetIndex = end - start - 1
> ```

I think we might need to update `outOfOrder` as well.
___
*[pkg/col/coldata/bytes.go, line 121 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmer4z_-iLH9jD3a0-4:-Lmer4z_-iLH9jD3a0-5:b-48i0wa) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L121)):*
> ```Go
> 			b.data = make([]byte, len(src.data))
> 		}
> 		b.data = b.data[:cap(b.data)]
> ```

Why are we slicing up to `cap(b.data)`?
___
*[pkg/col/coldata/bytes.go, line 296 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmeujja7hq42JJzOMSs:-Lmeujja7hq42JJzOMSt:b27k18y) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L296)):*
> ```Go
> 	if cap(b.lengths) < len(offsets)-1 {
> 		b.lengths = b.lengths[:cap(b.lengths)]
> 		b.lengths = append(b.lengths, make([]int32, len(offsets)-1)...)
> ```

It seems like we will over-allocate when `cap(b.lengths) > 0`, is this intended?
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 1262 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmezI02Ckd83p4b8ue3:-LmezI030XjZdAFaB-M6:b-19y3y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/sql/exec/mergejoiner_tmpl.go#L1262)):*
> ```Go
> 
> 			if o.outputReady || o.builderState.outCount == o.outputBatchSize {
> 				o.output.SetSelection(false)
> ```

[nit]: this line can now be removed.
___
*[pkg/col/coldata/bytes_test.go, line 209 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmewpUNEyXUvknr3rb8:-LmewpUO-1LhCwkSlFSY:b-hkkvxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes_test.go#L209)):*
> ```Go
> 	referenceSource := reference
> 	selfReferencingSources := true
> 	if rng.Float64() < 0 {
> ```

This will always be `false`, right? I think you meant maybe `0.5` probability?


<!-- Sent from Reviewable.io -->

2019-08-19 19:58 UTC, asubiotto commented
After talking to @jordanlewis it seems like the case of an out of order selection vector is not something that we will encounter because we were only testing that due to the sorter. Removing out of order selection vector generation in testing code makes the branch that disallows out of order swaps pass. I will therefore go forward with that implementation and update this PR since it will be simpler and more performant.

Thanks for the review @yuzefovich, I haven't addressed your comments in the latest revision yet but will.

2019-08-20 14:58 UTC, asubiotto reviewed
OK this new version is now RFAL! @yuzefovich addressed your comments that still applied and fixed the last couple of tests failing due to a missing `Reset`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LmjXCW7AnCderIYbbsw:b4383f0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 88 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmeppnc8X1Ch3Wf-ENi:-LmjIs0OEWr3kJ0Tkk2N:bg9fugs) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L88)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we might need to update `outOfOrder` as well.
</blockquote></details>

Removed `outOfOrder`
___
*[pkg/col/coldata/bytes.go, line 121 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmer4z_-iLH9jD3a0-4:-LmjItzi0ybapWBlyvMl:bd8j7ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L121)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why are we slicing up to `cap(b.data)`?
</blockquote></details>

So that we can maximally increase the length of b.data since `copy` only looks at the length. Admittedly directly appending is probably simpler. Removed this in the latest version
___
*[pkg/col/coldata/bytes.go, line 296 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmeujja7hq42JJzOMSs:-LmjJAKx1SnTVfd9H5oi:b-qheqtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes.go#L296)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It seems like we will over-allocate when `cap(b.lengths) > 0`, is this intended?
</blockquote></details>

No, good catch!
___
*[pkg/sql/exec/mergejoiner_tmpl.go, line 1262 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmezI02Ckd83p4b8ue3:-LmjU9tPEwAc3ZxkmTDV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/sql/exec/mergejoiner_tmpl.go#L1262)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: this line can now be removed.
</blockquote></details>

Done.
___
*[pkg/col/coldata/bytes_test.go, line 209 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmewpUNEyXUvknr3rb8:-LmjT_RJ7V3WN66FKzAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61712e8338856900a3dd4bfb066c8f0d2a8a9fa8/pkg/col/coldata/bytes_test.go#L209)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This will always be `false`, right? I think you meant maybe `0.5` probability?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-20 15:48 UTC, asubiotto commented
`TestLogic/{fakedist,local}/inner-join` seems like a timeout in vectorized execution unrelated to this PR. Will try to reproduce and open an issue.

2019-08-20 20:17 UTC, asubiotto commented
Actually, seems like the timeout is related to this PR because a materializer is calling `Get` with an invalid index which causes a panic and somehow ends up blocking on `Wait` running `TABLE [SHOW ZONE CONFIGURATIONS] WITH ORDINALITY`:
```
goroutine 4663 [select]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait(0xc001390b40)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:601 +0x106
panic(0x6b82880, 0x9561d00)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/exec/execerror.CatchVectorizedRuntimeError.func1(0xc004ec8290)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/execerror/error.go:82 +0x720
panic(0x6b82880, 0x9561d00)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/col/coldata.Bytes.Get(...)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:51
github.com/cockroachdb/cockroach/pkg/sql/exec.PhysicalTypeColElemToDatum(0x77b2e80, 0xc001fa77c0, 0x77b0007, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/vec_elem_to_datum.go:54 +0x107c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*materializer).next(0xc0022e8300, 0x402e89f, 0x8, 0xc0011f0a00, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/materializer.go:171 +0x234
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*materializer).nextAdapter(...)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/materializer.go:135
github.com/cockroachdb/cockroach/pkg/sql/exec/execerror.CatchVectorizedRuntimeError(0xc004ec82a0, 0x0, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/execerror/error.go:91 +0x55
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*materializer).Next(0xc0022e8300, 0xc00117dd40, 0x3, 0x3, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/materializer.go:179 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x774e1a0, 0xc001fa7d80, 0x77653a0, 0xc0022e8300, 0x77303a0, 0xc002a02840)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0022e8300, 0x774e1a0, 0xc001fa7d80)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc001390b40, 0x774e260, 0xc0013bce40, 0x7071f50, 0x0, 0x0)
    /Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:584 +0x1ec
```

2019-08-21 15:31 UTC, asubiotto commented
OK, this should be ready for a look @jordanlewis! Hopefully the build is green now. Filed an issue for a hang caused by the panic: https://github.com/cockroachdb/cockroach/issues/39779 and fixed the panic. I changed `ArrowBatchConverterRandom` to exercise this. It was a bug caused when converting batches that had fewer elements than their capacity to arrow format leading to `Get` to try to access `b.data` with negative, invalid, slice bounds).

2019-08-21 15:46 UTC, yuzefovich reviewed
Wow, amazing performance numbers!

I left a couple of comments, but I haven't reviewed the full PR and will do so shortly.

Since you mentioned that #39779 is fixed in this PR, I think that the PR description should be adjusted to close that issue.

> Reviewed 1 of 31 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LmopBE60h-tfVRCWDA2:b-ttwit1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 21 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmophXcBHu9x-y2NfbZ:-LmophXcBHu9x-y2Nfb_:bt5uki5) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L21)):*
> ```Go
> type Bytes struct {
> 	// data is the slice of all bytes
> 	data []byte
> ```

[nit]: missing period (in the line above).
___
*[pkg/col/coldata/bytes.go, line 26 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmoprVA1mE6rwPFSn-c:-LmoprVA1mE6rwPFSn-d:b-9qqkle) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L26)):*
> ```Go
> 	// outOfOrder. If the offsets are in order, fast paths can be used in various
> 	// situations,
> 	offsets []int32
> ```

[nit]: the comment needs to be updated.
___
*[pkg/col/coldata/bytes.go, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmoq9UX1m8ilTCWB4JV:-Lmoq9UX1m8ilTCWB4JW:b6j9tms) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L32)):*
> ```Go
> 	// maxSetIndex specifies the last index set by the user of this struct. This
> 	// enables us to set outOfOrder if an element is set prior to maxSetIndex.
> 	maxSetIndex int
> ```

Do we still need it?


<!-- Sent from Reviewable.io -->

2019-08-21 16:10 UTC, asubiotto reviewed
TFTR! #39779 is not fixed in this PR, just the panic that led to it (we could still encounter it if some other thing panics).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LmovXlH0PmsDaCo13hV:b-6rfbf3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 21 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmophXcBHu9x-y2NfbZ:-Lmow0B31u7vkfegZoXL:bw49b45) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L21)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing period (in the line above).
</blockquote></details>

Done. Sorry I missed this the first time!
___
*[pkg/col/coldata/bytes.go, line 26 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmoprVA1mE6rwPFSn-c:-Lmow2HjAmdZAfFJeeIa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L26)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment needs to be updated.
</blockquote></details>

Done.
___
*[pkg/col/coldata/bytes.go, line 32 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmoq9UX1m8ilTCWB4JV:-Lmow2yB6pA4iWmrtc1g:b9bx4ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/728399ffe17b19f65323814393eacb2ae8ce6dc4/pkg/col/coldata/bytes.go#L32)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we still need it?
</blockquote></details>

Yes. Updated the comment. It disallows unordered sets.


<!-- Sent from Reviewable.io -->

2019-08-21 20:59 UTC, yuzefovich approved these changes
Oh, I misunderstood your comment (I didn't look at the code to check whether it was actually fixed), never mind then.

Very nice work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 31 files at r14, 8 of 11 files at r15, 12 of 16 files at r16, 5 of 5 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-Lmp21L15srW5_8JjHOm:brtqpoq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 91 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp3P3dB4fhFni4zT31:-Lmp3P3dB4fhFni4zT32:bujh8qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L91)):*
> ```Go
> 		return b
> 	}
> 	if start == end {
> ```

What will happen if `start > end`?
___
*[pkg/col/coldata/bytes.go, line 112 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp4ubX-Uwvt0n9xbBb:-Lmp4ubX-Uwvt0n9xbBc:bfkvgap) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L112)):*
> ```Go
> // from src into the receiver starting at destIdx. Similar to the copy builtin,
> // min(dest.Len(), src.Len()) values will be copied. Note that due to the
> // possibility of unordered offsets, data that is overwritten might still be
> ```

[nit]: the comment needs an adjustment.
___
*[pkg/col/coldata/bytes.go, line 145 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp5qXYAXVsMjvwtFXe:-Lmp5qXYAXVsMjvwtFXf:b-kavsqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L145)):*
> ```Go
> 		// copy those elements into leftoverDestBytes to append after all elements
> 		// have been copied.
> 		leftoverDestBytesToCopy := b.data[b.offsets[destIdx+toCopy]:]
> ```

[nit]: I think this behavior should be called out in the comment to the method (I'm actually a little confused why we have this behavior). Also, I think we can reduce the amount of copying to only copy `len(b.offsets)-destIdx-toCopy` of `[]byte` slices.
___
*[pkg/sql/exec/random_testutils.go, line 115 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmpyQnL8CrbE2TU7CLk:-LmpyQnL8CrbE2TU7CLl:b2bbetd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/sql/exec/random_testutils.go#L115)):*
> ```Go
> // random elements equal to length (capcity if length is 0). The values will be
> // null with a probability of nullProbability.
> func RandomBatch(
> ```

[nit]: `s/capcity/capacity/` (above).


<!-- Sent from Reviewable.io -->

2019-08-22 00:03 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 91 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp3P3dB4fhFni4zT31:-LmqY146DD8n5yjDMWzb:blzynqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L91)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What will happen if `start > end`?
</blockquote></details>

An out of bounds panic.
___
*[pkg/col/coldata/bytes.go, line 112 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp4ubX-Uwvt0n9xbBb:-LmqZWpW3jXoEMg9v1Hj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L112)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment needs an adjustment.
</blockquote></details>

Done.
___
*[pkg/col/coldata/bytes.go, line 145 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp5qXYAXVsMjvwtFXe:-LmqayerDsVbcGO6DLVz:b-dcl9ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L145)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I think this behavior should be called out in the comment to the method (I'm actually a little confused why we have this behavior). Also, I think we can reduce the amount of copying to only copy `len(b.offsets)-destIdx-toCopy` of `[]byte` slices.
</blockquote></details>

Added a comment to the method, let me know if it's useful. I don't think I understand your second point, could you elaborate? We will only copy `len(b.offsets)-destIdx-toCopy` elements (that's the `b.offsets[destIdx+toCopy]`, but each of those can have a variable number of `[]byte`s.
___
*[pkg/sql/exec/random_testutils.go, line 115 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmpyQnL8CrbE2TU7CLk:-LmqcaYM5D1ItkIEbELm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/sql/exec/random_testutils.go#L115)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/capcity/capacity/` (above).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-22 00:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 145 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmp5qXYAXVsMjvwtFXe:-LmqeYObD2yQC0FR11eO:b-8walu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6374398b514bc94d00b211adb392f4ec05b9db03/pkg/col/coldata/bytes.go#L145)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Added a comment to the method, let me know if it's useful. I don't think I understand your second point, could you elaborate? We will only copy `len(b.offsets)-destIdx-toCopy` elements (that's the `b.offsets[destIdx+toCopy]`, but each of those can have a variable number of `[]byte`s.
</blockquote></details>

Oh, I see, thanks for the explanation (I think the comment is very helpful). My second point then doesn't make sense since I misread the code, please disregard it.


<!-- Sent from Reviewable.io -->

2019-08-22 00:29 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-:-LmqiftR4RUuUXon_OcS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 25 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqefIv5gqaxBvLWpWE:-LmqefIv5gqaxBvLWpWF:b-1d0tla) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L25)):*
> ```Go
> 	offsets []int32
> 	// lengths[i] contains the length of the []byte value beginning at offsets[i].
> 	lengths []int32
> ```

Now that we don't have out of order sets, I believe it should be unnecessary to keep both lengths and offsets. But, you could always fix this later.
___
*[pkg/col/coldata/bytes.go, line 39 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmqf-PqBj1qK8jMkoPv:-Lmqf-PqBj1qK8jMkoPw:bdtgpqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L39)):*
> ```Go
> 		// Given that the []byte slices are of variable length, we multiply the
> 		// number of elements by some constant factor.
> 		data:    make([]byte, 0, n*64),
> ```

Just a note that this would be a good thing to eventually make tunable. that would be an easy way to make cheap-ish fixed length strings without having to invent a new datatype.
___
*[pkg/col/coldata/bytes.go, line 46 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqfgOpDhoPzyGCbXGg:-LmqfgOpDhoPzyGCbXGh:b6fauaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L46)):*
> ```Go
> 
> // Get returns the ith []byte in Bytes. Note that the returned byte slice is
> // unsafe for reuse if a Set at the same index happens.
> ```

Shouldn't this say if a Set at the same index or earlier happens? Wouldn't a set at index 0 potentially overwrite any subsequent values?
___
*[pkg/col/coldata/bytes.go, line 296 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqhGoJ2tv4jwYWbj1S:-LmqhGoJ2tv4jwYWbj1T:b-hfcj00) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L296)):*
> ```Go
> // PrimitiveRepr is a temprorary migration tool.
> // TODO(asubiotto): Remove this.
> func (b Bytes) PrimitiveRepr() [][]byte {
> ```

Can this go away now or not yet?
___
*[pkg/col/coltypes/types.go, line 156 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqiU93DLAhEUMWgR5q:-LmqiU93DLAhEUMWgR5r:b-5i2ynt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coltypes/types.go#L156)):*
> ```Go
> 
> // Get is a function that should only be used in templates.
> func (t T) Get(safe bool, target, i string) string {
> ```

What about the idea of having `safe` be a string that's either `safe` or `unsafe` so that the raw calls to this thing don't have a naked boolean?
___
*[pkg/col/coldata/bytes_test.go, line 234 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqhWmBAEB2pYCD3RQU:-LmqhWmBAEB2pYCD3RQV:b-w8969a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes_test.go#L234)):*
> ```Go
> 	methods := make([]bytesMethod, 0, numCalls)
> 	for i := 0; i < numCalls; i++ {
> 		methods = append(methods, bytesMethods[rng.Intn(len(bytesMethods))])
> ```

This is such a cool idea!


<!-- Sent from Reviewable.io -->

2019-08-22 15:14 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38876)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @rafiss, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 25 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqefIv5gqaxBvLWpWE:-Lmtn7wAEi_QsMCFiYLd:b-v1dgdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L25)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Now that we don't have out of order sets, I believe it should be unnecessary to keep both lengths and offsets. But, you could always fix this later.
</blockquote></details>

Totally! I prefer to fix this later just to get the PR in ASAP so added a TODO.
___
*[pkg/col/coldata/bytes.go, line 39 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-Lmqf-PqBj1qK8jMkoPv:-LmtnsBB-E5cwrKr2jls:bp1fhqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L39)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Just a note that this would be a good thing to eventually make tunable. that would be an easy way to make cheap-ish fixed length strings without having to invent a new datatype.
</blockquote></details>

+1 added a TODO
___
*[pkg/col/coldata/bytes.go, line 46 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqfgOpDhoPzyGCbXGg:-Lmto91b1Zb2qyePsf3q:brvz22s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L46)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Shouldn't this say if a Set at the same index or earlier happens? Wouldn't a set at index 0 potentially overwrite any subsequent values?
</blockquote></details>

Yes. Reworded to be "any write operation".
___
*[pkg/col/coldata/bytes.go, line 296 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqhGoJ2tv4jwYWbj1S:-Lmtp5l5AwrwXPzLIOSd:bm7omi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes.go#L296)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can this go away now or not yet?
</blockquote></details>

Yes, it crept back in in this latest commit.
___
*[pkg/col/coltypes/types.go, line 156 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqiU93DLAhEUMWgR5q:-LmtqBnh8rT_0w2k90Ii:bkoke9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coltypes/types.go#L156)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about the idea of having `safe` be a string that's either `safe` or `unsafe` so that the raw calls to this thing don't have a naked boolean?
</blockquote></details>

I like it. Done.
___
*[pkg/col/coldata/bytes_test.go, line 234 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/38876#-LmqhWmBAEB2pYCD3RQU:-Lmtp9r8ESPcpO-2D-aS:b4gnk75) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dddced45fa8027396e232a20b40a24ec0579480/pkg/col/coldata/bytes_test.go#L234)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is such a cool idea!
</blockquote></details>

Glad you like it!


<!-- Sent from Reviewable.io -->

2019-08-22 15:31 UTC, asubiotto commented
bors r=yuzefovich,jordanlewis

2019-08-22 15:56 UTC, asubiotto commented
```
[15:37:07]Prepare environment
[15:37:07][Prepare environment]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[15:37:07][Prepare environment]                                  Dload  Upload   Total   Spent    Left  Speed
[15:37:07][Prepare environment] 
[15:37:07][Prepare environment]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[15:37:07][Prepare environment]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[15:37:07][Prepare environment] curl: (22) The requested URL returned error: 503 Service Unavailable: Back-end server is at capacity
[15:37:07][Prepare environment] Process exited with code 22
```
bors r=yuzefovich,jordanlewis

2019-08-22 15:58 UTC, asubiotto commented
I guess this is what backpressure looks like

2019-08-22 16:21 UTC, asubiotto commented
Was the registration server, which should be back to healthy now.

bors r=yuzefovich,jordanlewis

2019-08-22 16:44 UTC, asubiotto commented
Latest failure is #39816 and unrelated

bors r=yuzefovich,jordanlewis

2019-08-22 17:15 UTC, merged

2019-08-22 17:17 UTC, jordanlewis commented
Woohoo!