sql: Update show create to show table and partition zone configs.
cockroachdb/cockroach pull request #39102
Opened 2019-07-25 18:58 UTC by rohany

Release note: None

2019-07-25 18:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39102)
<!-- Reviewable:end -->

2019-07-25 18:59 UTC, rohany commented
Example output.

Whole table in one zone:
```
root@:26257/defaultdb> alter table table_in_region configure zone using constraints='[+region=us-east1]';
CONFIGURE ZONE 1

Time: 5.1ms
root@:26257/defaultdb> show create table_in_region;
    table_name    |                  create_statement
+-----------------+-----------------------------------------------------+
  table_in_region | CREATE TABLE table_in_region (
                  |     x INT8 NULL,
                  |     FAMILY "primary" (x, rowid)
                  |     /* table zone constraints: [+region=us-east1]*/
                  | )
(1 row)

Time: 7.643ms
```
Partitioned table
```
root@:26257/defaultdb> show create table table_partitioned;
     table_name     |                               create_statement
+-------------------+------------------------------------------------------------------------------+
  table_partitioned | CREATE TABLE table_partitioned (
                    |     x INT8 NOT NULL,
                    |     CONSTRAINT "primary" PRIMARY KEY (x ASC),
                    |     FAMILY "primary" (x)
                    | ) PARTITION BY LIST (x) (
                    |     PARTITION p1 VALUES IN ((1)) /* zone constraints: [+region=us-east1]*/,
                    |     PARTITION p2 VALUES IN ((2)) /* zone constraints: [+region=us-east2]*/,
                    |     PARTITION p3 VALUES IN ((3)) /* zone constraints: [+region=us-east3]*/
                    | )
(1 row)

Time: 8.053ms

root@:26257/defaultdb>
```

2019-07-26 19:46 UTC, awoods187 commented
I like this!

2019-07-29 15:18 UTC, solongordon requested changes
Hm, I find the inline comments kind of hacky and confusing. I don't think it's obvious to the user that if they reran the `CREATE TABLE` statement as shown, those constraints would not be applied.

What if we just included the relevant `ALTER` statements? So it might look something like this:
```
root@localhost:26257/defaultdb> SHOW CREATE TABLE orders;
  table_name |                                                 create_statement
+------------+-------------------------------------------------------------------------------------------------------------------+
  orders     | CREATE TABLE orders (
             |     region STRING NOT NULL,
             |     id UUID NOT NULL DEFAULT gen_random_uuid(),
             |     total DECIMAL NOT NULL,
             |     created_at TIMESTAMP NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (region ASC, id ASC),
             |     UNIQUE INDEX orders_by_created_at (region ASC, created_at ASC, id ASC) STORING (total),
             |     FAMILY "primary" (region, id, total, created_at),
             |     CONSTRAINT check_region CHECK (region IN ('us-east1':::STRING, 'us-west1':::STRING, 'europe-west2':::STRING))
             | ) PARTITION BY LIST (region) (
             |     PARTITION us_east1 VALUES IN (('us-east1')),
             |     PARTITION us_west1 VALUES IN (('us-west1')),
             |     PARTITION europe_west2 VALUES IN (('europe-west2'))
             | );
             | ALTER PARTITION us_east1 OF TABLE orders CONFIGURE ZONE USING
             |     constraints='[+region=us-east1]';
             | ALTER PARTITION us_west1 OF TABLE orders CONFIGURE ZONE USING
             |     constraints='[+region=us-west1]';
             | ALTER PARTITION europe_west2 OF TABLE orders CONFIGURE ZONE USING
             |     constraints='[+region=europe-west2]'
(1 row)
```
It seems like the `ALTER PARTITION` sql is already readily available in `crdb_internal.zones`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-:-LkyG9sA8fX6LPrlKOyV:b-wckhsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Lky7oJ4A92vRY3XC_pj:-Lky7oJ597uCCcoreLBR:bv99h5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b0af8e9c06e71e5b29f9a7c3004dd800b22c9c/pkg/sql/crdb_internal.go#L1132)):*
> ```Go
> 		// tables have not been created, or are unaccessible (perhaps during
> 		// certain tests (TestDumpAsOf in pkg/cli/dump_test.go)). So if something
> 		// goes wrong querying this table, proceed without any constraint data.
> ```

Probably worth at least logging a warning in this case.
___
*[pkg/sql/crdb_internal.go, line 1135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LkyBW35B_PDd_K5K1d9:-LkyBW35B_PDd_K5K1dA:b-k4mtrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b0af8e9c06e71e5b29f9a7c3004dd800b22c9c/pkg/sql/crdb_internal.go#L1135)):*
> ```Go
> 		zoneConstraintRows, _ := p.ExtendedEvalContext().ExecCfg.InternalExecutor.Query(
> 			ctx, "zone-constraints-for-show-create-table", p.txn,
> 			`SELECT zone_name, config_yaml from crdb_internal.zones`)
> ```

Rather than querying yaml from `crdb_internal.zones`, I wonder if it would be get the serialized zone config proto directly from `system.zones`.
___
*[pkg/sql/crdb_internal.go, line 1139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Lky85iiBgodjMHy0oWy:-Lky85iiBgodjMHy0oWz:b-bfnvi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8b0af8e9c06e71e5b29f9a7c3004dd800b22c9c/pkg/sql/crdb_internal.go#L1139)):*
> ```Go
> 		// Perform this encode -> decode to guarantee we easily get
> 		// readable constraint output.
> 		for _, row := range zoneConstraintRows {
> ```

I would wrap this whole block in `if err != nil { ... }`. I don't think it's good to make assumptions about the value of `zoneConstraintRows` when an error is returned.


<!-- Sent from Reviewable.io -->

2019-07-29 19:43 UTC, rohany commented
its a decent refactor of the code to add the alter sql statements in as well, so we should get andy's opinion on the addition first. I addressed the other comments that solon had though.

2019-08-05 16:41 UTC, rohany commented
After taking another look at this, it was much easier than I thought to add in solon's suggestion. RFAL.

```
root@:26257/defaultdb> show create table_partitioned;
     table_name     |                                      create_statement
+-------------------+---------------------------------------------------------------------------------------------+
  table_partitioned | CREATE TABLE table_partitioned (
                    |     x INT8 NOT NULL,
                    |     CONSTRAINT "primary" PRIMARY KEY (x ASC),
                    |     FAMILY "primary" (x)
                    | ) PARTITION BY LIST (x) (
                    |     PARTITION p1 VALUES IN ((1)) /* zone constraints: [+region=us-east1] */,
                    |     PARTITION p2 VALUES IN ((2)) /* zone constraints: [+region=us-east2] */,
                    |     PARTITION p3 VALUES IN ((3)) /* zone constraints: [+region=us-east3] */
                    | );
                    | ALTER PARTITION p2 OF INDEX defaultdb.public.table_partitioned@primary CONFIGURE ZONE USING
                    |     constraints = '[+region=us-east2]';
                    | ALTER PARTITION p3 OF INDEX defaultdb.public.table_partitioned@primary CONFIGURE ZONE USING
                    |     constraints = '[+region=us-east3]';
                    | ALTER PARTITION p1 OF INDEX defaultdb.public.table_partitioned@primary CONFIGURE ZONE USING
                    |     constraints = '[+region=us-east1]'
(1 row)
```

2019-08-06 13:44 UTC, awoods187 commented
My original concern was that adding it via `Alter Table` might be confusing to users, but, the more I think on it, the more I think this is a superior approach. Users want to be able read what their table is and doing that via SQL is better than SQL + comments. In addition, it does make it easier to copy the table output for use elsewhere. Good work!

2019-08-06 14:47 UTC, solongordon reviewed
@awoods187 Do you have an opinion on whether to also keep the zone constraint comments in the `CREATE TABLE` statement? I think my personal preference would be to ditch them.

@rohany Do you think we could order the `ALTER PARTITION` statements in a predictable way? It's kind of off-putting to see the `p1, p2, p3` order in the create table statement and then `p2, p3, p1` in the alter statements.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-:-LlbNV8c8d9dgVlT8bRc:b-pmgceo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-08-06 14:58 UTC, rohany commented
I updated the PR after I made this comment to sort the partitions by zone_name, so it will be ordered by table_name, partition_name now.

2019-08-06 17:07 UTC, rohany commented
i also agree -- if we are showing the alter statements anyway, then there doesn't really seem like a need to have these inline comments.

2019-08-06 17:15 UTC, awoods187 commented
Well the idea was to have one place that showed everything--if the zone config comments are gone then you don't actually know if the zone configs have been applied. I still kinda like them for that purpose--similarly to how we listed them for `SHOW PARTITIONS`

2019-08-06 18:26 UTC, solongordon commented
If it's better to see it all in one place that's ok with me, though I'm not sure I understand the "you don't actually know if the zone configs have been applied" part. The comments and the `ALTER` statements are showing the same information as far as I understand.

2019-08-06 18:38 UTC, awoods187 commented
oh i think i misunderstood--we do have the zone configs in the bottom so we don't also need the comments in the top.

2019-08-06 20:22 UTC, rohany commented
alright, i removed the extra output. RFAL.

2019-08-07 12:25 UTC, awoods187 commented
lgtm

2019-08-07 17:17 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlgzxSn1iS5hecAxIKe:-LlgzxSn1iS5hecAxIKf:b8dbutx) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1128)):*
> ```Go
> 		typeSequence := tree.NewDString("sequence")
> 
> 		zoneConfigStmtsMap := make(map[string]string)
> ```

Rather than using the zone name as the key in this map, I think it would be better to use the database and table name, which you can now get by doing `SELECT database_name, table_name, config_sql FROM crdb_internal.zones`.
___
*[pkg/sql/crdb_internal.go, line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llgy6lGA39S3ESg_Dhc:-Llgy6lGA39S3ESg_Dhd:b-r4savw) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1136)):*
> ```Go
> 		zoneConstraintRows, err := p.ExtendedEvalContext().ExecCfg.InternalExecutor.Query(
> 			ctx, "zone-constraints-for-show-create-table", p.txn,
> 			`SELECT zone_name, config_yaml, config_sql FROM crdb_internal.zones ORDER BY zone_name`)
> ```

Do you still need `config_yaml`?
___
*[pkg/sql/crdb_internal.go, line 1144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh-cVWBsxhYigTuzV9:-Llh-cVWBsxhYigTuzVA:b-kzat6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1144)):*
> ```Go
> 			for _, row := range zoneConstraintRows {
> 				var zoneConfig config.ZoneConfig
> 				if row[0] == tree.DNull || row[1] == tree.DNull || row[2] == tree.DNull {
> ```

Better to add `WHERE ... IS NOT NULL` conditions to your original query.
___
*[pkg/sql/crdb_internal.go, line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlgyTMtD7R4jHnOv065:-LlgyTMtD7R4jHnOv066:blhr0y1) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1152)):*
> ```Go
> 					return err
> 				}
> 				id := string(tree.MustBeDString(row[0]))
> ```

A little confusing to call this `id` when it is the zone name.
___
*[pkg/sql/crdb_internal.go, line 1182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh0UBdAZbxFPBHbz2k:-Llh0UBdAZbxFPBHbz2l:b4okklv) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1182)):*
> ```Go
> 					descType = typeTable
> 					tn := (*tree.Name)(&table.Name)
> 					createNofk, err = ShowCreateTable(ctx, tn, contextName, table, lCtx, true /* ignoreFKs */, zoneConfigStmtsMap)
> ```

It shouldn't be necessary to pass `zoneConfigStmtsMap` to `ShowCreateTable` anymore. You can just add the statements below.

Furthermore, I think we want to be careful about how these statements are stored in `crdb_internal.create_statements`. Note that this table has separate columns for `create_statement`, `create_nofks`, `alter_statements`, and `validate_statements`. As it stands I think you're just adding the zone config statements to both `create_statement` and `create_nofks`, which could break expectations about those columns. For instance the DUMP command appears to depend on `create_nofks` for dumping the schema.

After some cursory code grepping, I *think* what we want is to only add the zone config statements to the `create_statement` column, but it would be great if you could validate that.
___
*[pkg/sql/show_create.go, line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh-x22DmUhDtm_EgT4:-Llh-x22DmUhDtm_EgT5:b-fjuy10) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/show_create.go#L321)):*
> ```Go
> func ShowCreatePartitioning(
> 	a *sqlbase.DatumAlloc,
> 	dbPrefix string,
> ```

This is unused now, right?


<!-- Sent from Reviewable.io -->

2019-08-07 17:24 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @rohany)

___
*[pkg/sql/crdb_internal.go, line 1182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh0UBdAZbxFPBHbz2k:-Llh5vgm1FsS3cWT6J-g:b-u0jwfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1182)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It shouldn't be necessary to pass `zoneConfigStmtsMap` to `ShowCreateTable` anymore. You can just add the statements below.

Furthermore, I think we want to be careful about how these statements are stored in `crdb_internal.create_statements`. Note that this table has separate columns for `create_statement`, `create_nofks`, `alter_statements`, and `validate_statements`. As it stands I think you're just adding the zone config statements to both `create_statement` and `create_nofks`, which could break expectations about those columns. For instance the DUMP command appears to depend on `create_nofks` for dumping the schema.

After some cursory code grepping, I *think* what we want is to only add the zone config statements to the `create_statement` column, but it would be great if you could validate that.
</blockquote></details>

Or it might be even better to add a new column for the zone config statements, and have the `SHOW CREATE TABLE` implementation concatenate the two.


<!-- Sent from Reviewable.io -->

2019-08-07 19:43 UTC, rohany commented
RFAL

2019-08-07 19:45 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187 and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlgzxSn1iS5hecAxIKe:-LlhQTXT6OFFVLc3fzw3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1128)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Rather than using the zone name as the key in this map, I think it would be better to use the database and table name, which you can now get by doing `SELECT database_name, table_name, config_sql FROM crdb_internal.zones`.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llgy6lGA39S3ESg_Dhc:-LlhQMGM0liBcig9fKli:b-d390pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1136)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Do you still need `config_yaml`?
</blockquote></details>

yeah, we want to only output constraints if there are zone constraints on the table -- this is the easiest way to get that information.
___
*[pkg/sql/crdb_internal.go, line 1144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh-cVWBsxhYigTuzV9:-LlhQLzi73U6Uq5J-CI7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1144)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Better to add `WHERE ... IS NOT NULL` conditions to your original query.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlgyTMtD7R4jHnOv065:-LlhQLVP6owsJKxHVKu0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1152)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

A little confusing to call this `id` when it is the zone name.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 1182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh0UBdAZbxFPBHbz2k:-Llh_6175WDEW6U7QHA3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1182)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Or it might be even better to add a new column for the zone config statements, and have the `SHOW CREATE TABLE` implementation concatenate the two.
</blockquote></details>

Done.
___
*[pkg/sql/show_create.go, line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llh-x22DmUhDtm_EgT4:-Llhb0KSAbxOZVAoUGHK:biz53mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/show_create.go#L321)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This is unused now, right?
</blockquote></details>

no, it is used to display partition values


<!-- Sent from Reviewable.io -->

2019-08-07 20:29 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llgy6lGA39S3ESg_Dhc:-LlhgCB2AxIp47dnfy-v:b3ul6t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/868badffa33ba763b0076c7a166fe1f2f5c700c3/pkg/sql/crdb_internal.go#L1136)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

yeah, we want to only output constraints if there are zone constraints on the table -- this is the easiest way to get that information.
</blockquote></details>

Oh, I see. @awoods187 is this correct? Should we only show the `ALTER ... CONFIGURE ZONE ...` statements if there are `constraints`, or is it also worth showing if there are other zone configurations like `num_replicas`, `lease_preferences`, etc.?
___
*[pkg/sql/crdb_internal.go, line 1115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhfBZlCnUczQ_sjf7R:-LlhfBZlCnUczQ_sjf7S:bay86hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/crdb_internal.go#L1115)):*
> ```Go
>   alter_statements    					STRING[] NOT NULL,
>   validate_statements 					STRING[] NOT NULL,
> 	zone_configuration_statements STRING[] NOT NULL
> ```

Weird whitespace
___
*[pkg/sql/crdb_internal.go, line 1141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhgAc947BjtKQiBZod:-LlhgAc947BjtKQiBZoe:bwhecvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/crdb_internal.go#L1141)):*
> ```Go
> 				AND config_sql IS NOT NULL
> 			ORDER BY
> 				(database_name, table_name, index_name, partition_name)
> ```

Nit: unnecessary parens
___
*[pkg/sql/crdb_internal.go, line 1209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhkXMS4yQH2z8Ec163:-LlhkXMS4yQH2z8Ec164:b8b3q1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/crdb_internal.go#L1209)):*
> ```Go
> 				// certain tests (TestDumpAsOf in pkg/cli/dump_test.go)). So if something
> 				// goes wrong querying this table, proceed without any constraint data.
> 				zoneConstraintRows, err := p.ExtendedEvalContext().ExecCfg.InternalExecutor.Query(
> ```

Hmm. I'm slightly worried about querying `crdb_internal.zones` once for every single table. It seems like this could be slow if a user has a lot of tables in their database. I also wonder whether this causes us to "rebuild" `crdb_internal.zones` over and over again.

Would it be easy enough to use a map like you were before?
___
*[pkg/sql/delegate/show_table.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llhi7Nf-yt52pR5Q4pk:-Llhi7Nf-yt52pR5Q4pl:bkx0hoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L30)):*
> ```Go
> 					zone_configuration_statements
> 				),
> 				concat(';', chr(10))
> ```

I think `e';\n'` works just as well and is less mysterious. :wink:
___
*[pkg/sql/delegate/show_table.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhiyJxEDju1bYuIulv:-LlhiyJxEDju1bYuIulw:b-86g1vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L36)):*
> ```Go
> 			%[4]s.crdb_internal.create_statements
> 		WHERE
> 			(database_name IS NULL OR database_name = %[1]s)
> ```

Nit: Not your code but more unnecessary parens
___
*[pkg/sql/delegate/show_table.go, line 38 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llhj2Rh6FI0to-z-vYs:-Llhj2Rh6FI0to-z-vYt:b-2nzs83) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L38)):*
> ```Go
> 			(database_name IS NULL OR database_name = %[1]s)
> 			AND schema_name = %[5]s
> 			AND descriptor_name = %[2]s;
> ```

Nit: Don't need the semicolon at the end


<!-- Sent from Reviewable.io -->

2019-08-07 20:48 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhkXMS4yQH2z8Ec163:-LlhpWjy0VCOJrnATRgX:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/crdb_internal.go#L1209)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Hmm. I'm slightly worried about querying `crdb_internal.zones` once for every single table. It seems like this could be slow if a user has a lot of tables in their database. I also wonder whether this causes us to "rebuild" `crdb_internal.zones` over and over again.

Would it be easy enough to use a map like you were before?
</blockquote></details>

done.
___
*[pkg/sql/delegate/show_table.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llhi7Nf-yt52pR5Q4pk:-LlhmJEu-zXzlu_383O4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L30)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think `e';\n'` works just as well and is less mysterious. :wink:
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_table.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhiyJxEDju1bYuIulv:-LlhpYkb1sS2y-Yj3x20:b67bcfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L36)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Not your code but more unnecessary parens
</blockquote></details>

it wasn't unnecessary -- it doesn't work without it


<!-- Sent from Reviewable.io -->

2019-08-07 20:50 UTC, rohany commented
RFAL -- sorry for this taking so many iterations

2019-08-07 21:15 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/delegate/show_table.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llhi7Nf-yt52pR5Q4pk:-LlhvzbI5TMvDcX3Z-C-:b-vbp453) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L30)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You don't need the `concat` now.
___
*[pkg/sql/delegate/show_table.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-LlhiyJxEDju1bYuIulv:-Llhvhr_6DyLm04Ul_Sh:bjfm4k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e49ddb47544596683aba6fa0c56cf9f2453eb5c/pkg/sql/delegate/show_table.go#L36)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

it wasn't unnecessary -- it doesn't work without it
</blockquote></details>

Oh I missed the conditions below. Carry on...


<!-- Sent from Reviewable.io -->

2019-08-08 02:16 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, though let's double-check with Andy about whether this should be limited to constraints.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-:-Llj-X7TBAeg0JmPt8x2:b6518oy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-08-08 02:17 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39102)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39102#-Llj-sbnA9XshHdJEC42:-Llj-sbnA9XshHdJEC43:bxlm3b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b011b569d34c4279f60a7f2554fb9d51acc2a9ef/pkg/sql/crdb_internal.go#L1115)):*
> ```Go
>   alter_statements    					STRING[] NOT NULL,
>   validate_statements 					STRING[] NOT NULL,
>   zone_configuration_statements STRING[] NOT NULL
> ```

Whitespace still looks weird here


<!-- Sent from Reviewable.io -->

2019-08-09 00:14 UTC, awoods187 commented
Linking this to the main issue https://github.com/cockroachdb/cockroach/issues/39076

Also, there should be a release note on this work.

2019-08-11 14:28 UTC, rohany commented
Alright, if there are no more comments I'm going to fix these build errors and merge this.

2019-08-11 17:24 UTC, rohany commented
bors r+

2019-08-12 16:27 UTC, rohany commented
bors r+

2019-08-12 17:12 UTC, merged