exec: cancel the flow context when materializer is done
cockroachdb/cockroach pull request #39100
Opened 2019-07-25 17:59 UTC by yuzefovich

Previously, flow shutting down has been a little fragile since
some goroutines would remain blocked when the materializer finishes
its execution. Now we will cancel the shared flow context, and if
all infrastructure listens to it, the infra will be shut down
appropriately.

Fixes: #39029.
Fixes: #39092.

Release note: None

2019-07-25 17:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39100)
<!-- Reviewable:end -->

2019-07-25 18:46 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/exec/unorderedsynchronizer.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeQ76-6_3cSGk74lbA:-LkeQ7602ql2o2bbN9bm:b-wwezx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/unorderedsynchronizer.go#L157)):*
> ```Go
> 					}
> 					return
> 				case <-s.origCtx.Done():
> ```

This is confusing to me. Since `ctx` is derived from `origCtx`, won't it be canceled when `origCtx` is? Not clear to me why this `case` is necessary.
___
*[pkg/sql/exec/colrpc/inbox.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeRpvdEgY8c42utv-Z:-LkeRpvdEgY8c42utv-_:bljpv3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/colrpc/inbox.go#L281)):*
> ```Go
> 
> // DrainMeta is part of the MetadataGenerator interface. DrainMeta may be
> // called concurrently with Next.
> ```

Do we care if `Next` buffers more metadata after `DrainMeta` has already been called?


<!-- Sent from Reviewable.io -->

2019-07-25 19:04 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/exec/unorderedsynchronizer.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeQ76-6_3cSGk74lbA:-LkeVDPU6gKkjNXlqFUA:beg66ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/unorderedsynchronizer.go#L157)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This is confusing to me. Since `ctx` is derived from `origCtx`, won't it be canceled when `origCtx` is? Not clear to me why this `case` is necessary.
</blockquote></details>

To be honest, I'm not sure about this stuff myself. I think you're right:
```
// WithCancel returns a copy of parent with a new Done channel. The returned
// context's Done channel is closed when the returned cancel function is called
// or when the parent context's Done channel is closed, whichever happens first.
```
___
*[pkg/sql/exec/colrpc/inbox.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeRpvdEgY8c42utv-Z:-LkeVhbZ5q8ItmCkjn3a:br7892r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/colrpc/inbox.go#L281)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Do we care if `Next` buffers more metadata after `DrainMeta` has already been called?
</blockquote></details>

My understanding is that if `DrainMeta` has been called, it means that `materializer` is wrapping everything up and will be shutting down the flow shortly, so any metadata received after `DrainMeta` is dropped on the floor. I think it is an expected behavior because we don't want to hold the shut down until we're sure there is no more metadata coming if `Consumer` has already been satisfied.


<!-- Sent from Reviewable.io -->

2019-07-25 19:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @solongordon)

___
*[pkg/sql/distsqlrun/materializer.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeYL5Y7IURaUi2y4I-:-LkeYL5Y7IURaUi2y4I0:biowdyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ffb2ed7b7e9106cbed919323ca6011ed0d8be94/pkg/sql/distsqlrun/materializer.go#L105)):*
> ```Go
> func (m *materializer) Start(ctx context.Context) context.Context {
> 	m.input.Init()
> 	m.origCtx = ctx
> ```

I'm not sure if it's necessary. Here is a snippet from `ProcessorBase.InternalClose`:
```
		// Reset the context so that any incidental uses after this point do not
		// access the finished span.
		pb.Ctx = pb.origCtx
```
___
*[pkg/sql/exec/unorderedsynchronizer.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeQ76-6_3cSGk74lbA:-LkeXlBa0igbSFipwYrd:bo4xpok) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/unorderedsynchronizer.go#L157)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

To be honest, I'm not sure about this stuff myself. I think you're right:
```
// WithCancel returns a copy of parent with a new Done channel. The returned
// context's Done channel is closed when the returned cancel function is called
// or when the parent context's Done channel is closed, whichever happens first.
```
</blockquote></details>

I removed it and confirmed that the tests still pass. Thanks for the catch!


<!-- Sent from Reviewable.io -->

2019-07-25 19:28 UTC, solongordon approved these changes
Well done figuring this out!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Lke_wToEMkC2BceBauJ:b-5mg3ll)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/colrpc/inbox.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeRpvdEgY8c42utv-Z:-LkeaKzC-uiI7RXVsaSX:b40xl06) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/colrpc/inbox.go#L281)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

My understanding is that if `DrainMeta` has been called, it means that `materializer` is wrapping everything up and will be shutting down the flow shortly, so any metadata received after `DrainMeta` is dropped on the floor. I think it is an expected behavior because we don't want to hold the shut down until we're sure there is no more metadata coming if `Consumer` has already been satisfied.
</blockquote></details>

That sounds plausible. It would be great to get @asubiotto's thoughts on this but I'm fine with merging and then revisiting when he has time.


<!-- Sent from Reviewable.io -->

2019-07-25 20:03 UTC, yuzefovich commented
I added our concerns as TODOs, and I think we should go ahead and merge this and continue on iterating.

2019-07-25 20:06 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeYL5Y7IURaUi2y4I-:-LkejMyE0uElyLiN5h2C:b-vh3s96) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ffb2ed7b7e9106cbed919323ca6011ed0d8be94/pkg/sql/distsqlrun/materializer.go#L105)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm not sure if it's necessary. Here is a snippet from `ProcessorBase.InternalClose`:
```
		// Reset the context so that any incidental uses after this point do not
		// access the finished span.
		pb.Ctx = pb.origCtx
```
</blockquote></details>

Yeah, this is necessary, I think.
___
*[pkg/sql/exec/colrpc/outbox.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkejWAi5Lq5LYbhfld-:-LkejWAi5Lq5LYbhfld0:b-9ulmcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c780232d7389ce7b465bfcfa22651a8f8dbd5b/pkg/sql/exec/colrpc/outbox.go#L199)):*
> ```Go
> 		// iteration? Will it be more performant if we define this function with
> 		// the Outbox as a receiver (as well as in other usages of
> 		// CatchVectorizedRuntimeError)?
> ```

Yes and yes.


<!-- Sent from Reviewable.io -->

2019-07-25 20:29 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/distsqlrun/materializer.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeYL5Y7IURaUi2y4I-:-LkekH176kKBXGbiFviB:b-4gbub9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0ffb2ed7b7e9106cbed919323ca6011ed0d8be94/pkg/sql/distsqlrun/materializer.go#L105)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, this is necessary, I think.
</blockquote></details>

Ok, thanks, let's keep it then to be safe.
___
*[pkg/sql/exec/colrpc/outbox.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkejWAi5Lq5LYbhfld-:-Lkeodia9cRlCRGTDRaG:bpeo18z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4c780232d7389ce7b465bfcfa22651a8f8dbd5b/pkg/sql/exec/colrpc/outbox.go#L199)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yes and yes.
</blockquote></details>

Thanks. I updated all non-test places where `CatchVectorizedRuntimeError` is used.


<!-- Sent from Reviewable.io -->

2019-07-25 20:35 UTC, asubiotto reviewed
Haven't taken a thorough look but I think the `Inbox.done` / `Inbox.initialized` should be protected by the mutex as well. Would it be possible to add some tests to ensure correct behavior? I'm thinking like a black box test where you run a simple flow in a goroutine then Drain and cancel concurrently.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Lkepimb3ZYSOXKKUvYh:btcolmc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)



<!-- Sent from Reviewable.io -->

2019-07-25 20:37 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/unorderedsynchronizer.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeqJWe8jLrQR21nD8B:-LkeqJWf2HqTnYQ7u9E6:b-ne4fg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/unorderedsynchronizer.go#L96)):*
> ```Go
> 		input.Init()
> 		s.nextBatch[i] = func() {
> 			s.batch = input.Next(s.ctx)
> ```

I think this is a classic Go gotcha - `input` is getting captured but overwritten on each iteration of the loop. You can fix by passing `input` as an argument to the anonymous function.


<!-- Sent from Reviewable.io -->

2019-07-25 21:04 UTC, asubiotto requested changes
Thanks a lot for doing this! Took a quick look but I would recommend writing a test to verify the integrated behavior works. The flow I think would be interesting would have a hashRouter where all outputs go to an unordered synchronizer, with one or two inboxes as an extra two inputs to this syncrhonizer and a materializer reading from all that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LkewVFW8YoyGmtozFRV:bikzsk5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/exec/routers.go, line 256 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LketfT5-rvBsfQRQk6h:-LketfT5-rvBsfQRQk6i:b-iag5ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/routers.go#L256)):*
> ```Go
> 	hashCols []int
> 	// ctx is the context to use when processing next batch from the input.
> 	ctx context.Context
> ```

I'm not sure I understand the need to have a context field, I think we generally avoid putting contexts in structs.
___
*[pkg/sql/exec/colrpc/inbox.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeRpvdEgY8c42utv-Z:-LkevNH45TfP1ici-QaZ:bka5b80) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/colrpc/inbox.go#L281)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

That sounds plausible. It would be great to get @asubiotto's thoughts on this but I'm fine with merging and then revisiting when he has time.
</blockquote></details>

`DrainMeta` keeps on reading from the stream until io.EOF returns. I think it would be fine for `Inbox` to add to the metadata concurrently but we probably just want to avoid `Next` reading from the stream at all once `DrainMeta` begins (I guess the best we can do is at most once). We could probably do this by setting `i.done` under lock but only closing `errCh` once we finish with the stream in `DrainMeta`
___
*[pkg/sql/exec/colrpc/inbox.go, line 266 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkesg2X-CL1lv14z_2T:-Lkesg2X-CL1lv14z_2U:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/inbox.go#L266)):*
> ```Go
> 			// TODO(yuzefovich): it seems to me that TODO above can be removed
> 			// because only vectorized Outboxes can be connected to these Inboxes,
> 			// and Outboxes do not use NumEmptyRows field.
> ```

SGTM
___
*[pkg/sql/exec/colrpc/outbox.go, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkew4pt4NkRY1nqB4ng:-Lkew4pt4NkRY1nqB4nh:b-hbom3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L46)):*
> ```Go
> 	batch coldata.Batch
> 	// ctx is the context to be used to get the next batch from the input.
> 	ctx context.Context
> ```

same re: context in struct
___
*[pkg/sql/exec/colrpc/outbox.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkew8OZ0w-B4Xye7Id0:-Lkew8OZ0w-B4Xye7Id1:bakkidr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L278)):*
> ```Go
> 			case msg.DrainRequest != nil:
> 				o.moveToDraining(ctx)
> 				// TODO(yuzefovich): why are we not exiting this goroutine here?
> ```

Because we need to keep on `Recv` ing until we get io.EOF (I think this is mentioned somewhere else in the file) from the stream. The main goroutine will `CloseSend` so that this happens eventually.
___
*[pkg/sql/exec/colrpc/outbox.go, line 280 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkewH1O21ZyII46HTWw:-LkewH1O21ZyII46HTWx:b-dgjan6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L280)):*
> ```Go
> 				// TODO(yuzefovich): why are we not exiting this goroutine here?
> 				// TODO(yuzefovich): should we check msg.SetupFlowRequest and panic if
> 				// it's non-nil?
> ```

:man_shrugging: I think we should probably redefine the proto to not get a SetupFlowRequest when working with this stream but doesn't seem worth it.


<!-- Sent from Reviewable.io -->

2019-07-26 05:45 UTC, yuzefovich reviewed
Okay, I added a test as Alfonso suggested. I'm way over my head here to be honest, so please let me know what you guys think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Lkgnm8g7WEMzr8IPf-N:bny0voo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec/routers.go, line 256 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LketfT5-rvBsfQRQk6h:-LkeyLpq7cvJGjC2sBG-:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/routers.go#L256)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I understand the need to have a context field, I think we generally avoid putting contexts in structs.
</blockquote></details>

Refactored.
___
*[pkg/sql/exec/unorderedsynchronizer.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeqJWe8jLrQR21nD8B:-LkerxEf9n_bpYb85Rb8:b-flvxtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/unorderedsynchronizer.go#L96)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this is a classic Go gotcha - `input` is getting captured but overwritten on each iteration of the loop. You can fix by passing `input` as an argument to the anonymous function.
</blockquote></details>

Oops, fixed. I have already made this mistake in the past :/
___
*[pkg/sql/exec/colrpc/inbox.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkeRpvdEgY8c42utv-Z:-Lkf4-MU73z4uG-JYvyR:bgbjioa) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bedfd707aa968386c47b1256f87dc07ee0a26eb/pkg/sql/exec/colrpc/inbox.go#L281)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`DrainMeta` keeps on reading from the stream until io.EOF returns. I think it would be fine for `Inbox` to add to the metadata concurrently but we probably just want to avoid `Next` reading from the stream at all once `DrainMeta` begins (I guess the best we can do is at most once). We could probably do this by setting `i.done` under lock but only closing `errCh` once we finish with the stream in `DrainMeta`
</blockquote></details>

Ok, I put my best understanding of the situation into the code. PTAL.
___
*[pkg/sql/exec/colrpc/inbox.go, line 266 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkesg2X-CL1lv14z_2T:-LkextPd934ioB_7mK-a:b-sg81zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/inbox.go#L266)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

Thanks, removed.
___
*[pkg/sql/exec/colrpc/outbox.go, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkew4pt4NkRY1nqB4ng:-LkeyJUi2FTdGJnkZjkR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L46)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

same re: context in struct
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/outbox.go, line 278 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lkew8OZ0w-B4Xye7Id0:-Lkeyi17ABfw27aWV8u5:b-abswid) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L278)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Because we need to keep on `Recv` ing until we get io.EOF (I think this is mentioned somewhere else in the file) from the stream. The main goroutine will `CloseSend` so that this happens eventually.
</blockquote></details>

Yeah, there is a comment about it below:
```
			// The receiver goroutine will read from the stream until io.EOF is
			// returned.
```
I guess it's a part of the contract?
___
*[pkg/sql/exec/colrpc/outbox.go, line 280 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkewH1O21ZyII46HTWw:-Lkeyq0G9D5h25kbO8gv:b8uqcav) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ad0da63b5892d555e9d73a7a54e8d6306f0e706/pkg/sql/exec/colrpc/outbox.go#L280)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:man_shrugging: I think we should probably redefine the proto to not get a SetupFlowRequest when working with this stream but doesn't seem worth it.
</blockquote></details>

Yeah, makes sense.


<!-- Sent from Reviewable.io -->

2019-07-29 14:52 UTC, asubiotto requested changes
Great work, I think we're getting there. Thanks for picking this up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LkyCwLaE0pRjFaNzYG8:b-4smcjq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 172 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyCWjDA6Ctx1X0GbON:-LkyCWjDA6Ctx1X0GbOO:bdyar9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/materializer.go#L172)):*
> ```Go
> }
> 
> func (m *materializer) ConsumerClosed() {
> ```

I think we also want to cancel the flow on `ConsumerDone`. This is the scenario that the limit op goes through: get enough batches then return `ConsumerDone`. In this case, the materializer should drain the metadata and then cancel the flow. I wonder why the test is passing?
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky2DqeC56OSjd8NHNw:-Lky2DqeC56OSjd8NHNx:b95n1pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L44)):*
> ```Go
> }
> 
> func (d *mockDialer) Dial(context.Context, roachpb.NodeID) (*grpc.ClientConn, error) {
> ```

One other option is to reuse the mock rpc layer in `colrpc_test`, but I think you're probably correct in going one layer above, as we want to mirror grpc behavior as closely as possible.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky2C2T5-rspFGqZcAK:-Lky2C2T5-rspFGqZcAL:b-8o237f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L56)):*
> ```Go
> // batches from the materializer and then closes it which should trigger
> // closure of everything else.
> func TestVectorizedFlowShutdown(t *testing.T) {
> ```

Great stuff!
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky1Y93-9yzshruPN0Y:-Lky1Y94DggtpbeVu-_c:b-wuczjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L71)):*
> ```Go
> 		consumerDone,
> 		consumerClosed,
> 		drainMeta,
> ```

Is drainMeta not the same scenario as `consumerDone`?
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky3D6I0vbKRl3JxK-C:-Lky3D6I0vbKRl3JxK-D:b-o354ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L114)):*
> ```Go
> 				synchronizerInputs = append(synchronizerInputs, exec.Operator(inboxes[i]))
> 			}
> 			synchronizer := exec.NewUnorderedSynchronizer(synchronizerInputs, typs, &sync.WaitGroup{})
> ```

Consider commenting the waitgroup that isn't kept around
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky5QRFC_ImAyMA4hRy:-Lky5QRFC_ImAyMA4hRz:b-axkvua) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L118)):*
> ```Go
> 			metadataSources = append(metadataSources, hashRouter)
> 			for _, inbox := range inboxes {
> 				metadataSources = append(metadataSources, inbox)
> ```

I think it would also be good to have some dummy metadata that we assert is received at the end.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky5pJo3aYhJBS8jMHr:-Lky5pJo3aYhJBS8jMHs:bnethsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L137)):*
> ```Go
> 			)
> 			require.NoError(t, err)
> 			d := &mockDialer{addr: addr}
> ```

Might as well call this `dialer`.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky6e8g8tHxv15hWk1E:-Lky6e8g8tHxv15hWk1F:bw4e47n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L154)):*
> ```Go
> 				handleStreamErrCh[i] = make(chan error, 1)
> 				doneFn := func(donec chan<- error) func() {
> 					return func() { close(donec) }
> ```

I think you can just close Donec directly (no need to pass it in to the function), since the `serverStreamNotification`'s scope is limited to inside on iteration of the for loop.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 159 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky6sJF5VphwVXU-Kp3:-Lky6sJF5VphwVXU-Kp4:b-6uz76i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L159)):*
> ```Go
> 				go func(id int, stream distsqlpb.DistSQL_FlowStreamServer, doneFn func()) {
> 					handleStreamErrCh[id] <- inboxes[id].RunWithStream(stream.Context(), stream)
> 					if doneFn != nil {
> ```

This check is probably not necessary
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky1n8H3tMZn037vHh9:-Lky1n8H3tMZn037vHhA:b-1e7vqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L191)):*
> ```Go
> 				// that it would either be nil or context canceled, but TeamCity ran
> 				// into "rpc error: code = Internal desc = grpc: failed to unmarshal
> 				// the received message proto: illegal wireType 7".
> ```

I think we definitely want to do so, I'm not sure what's causing this error, probably something to look into.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky7JImDGHoHn4atcBC:-Lky7JIn84iAmL4g6c9q:bplz47x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L193)):*
> ```Go
> 				// the received message proto: illegal wireType 7".
> 			}
> 			wg.Wait()
> ```

This is a really cool test, thanks for adding it! I think we could go an extra level and maybe randomly add a scenario that instead of the materializer being directly connected to the unordered synchronizer, we would have an outbox->inbox->materializer, essentially simulating a remote hop. This would test how we handle `Consumer{Done,Closed}` over the network.
___
*[pkg/sql/exec/routers.go, line 256 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky83XJErpHeu-o1LjA:-Lky83XJErpHeu-o1LjB:b-xllaqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/routers.go#L256)):*
> ```Go
> 	hashCols []int
> 	// done indicates whether the input is done.
> 	done bool
> ```

Why are we adding this to the `hashRouter`? I don't see the usage of `done` changing scope.
___
*[pkg/sql/exec/colrpc/inbox.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyB5VX-YYybtboOZoq:-LkyB5VX-YYybtboOZor:b1xvomo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/colrpc/inbox.go#L54)):*
> ```Go
> 	// initialized prevents double initialization. Should not be used by the
> 	// RunWithStream goroutine.
> 	initialized bool
> ```

I think `initialized` should also be protected by the mutex now. Consider `Next` and `DrainMeta` racin [...]

2019-07-29 14:57 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky5QRFC_ImAyMA4hRy:-LkyDwdODswv1-87jhRw:b-y2oxg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it would also be good to have some dummy metadata that we assert is received at the end.
</blockquote></details>

To be clear: In `ConsumerClosed` we don't care about any metadata but in `ConsumerDone` we care that **all** metadata is received.


<!-- Sent from Reviewable.io -->

2019-07-29 22:10 UTC, yuzefovich reviewed
Thanks for the review! I agree, I think we're almost there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LkziakqCpljXf__E7xy:bm3f4ix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 172 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyCWjDA6Ctx1X0GbON:-LkyQpxn7QfKZB7KZDcB:b6bj8vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/materializer.go#L172)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we also want to cancel the flow on `ConsumerDone`. This is the scenario that the limit op goes through: get enough batches then return `ConsumerDone`. In this case, the materializer should drain the metadata and then cancel the flow. I wonder why the test is passing?
</blockquote></details>

So actually that's exactly what's happening here - `ProcessorBase` implements `ConsumerDone` as:
```
// ConsumerDone is part of the RowSource interface.
func (pb *ProcessorBase) ConsumerDone() {
	pb.MoveToDraining(nil /* err */)
}
```
so `materializer` moves to `draining` state, and after all metadata has been drained, `m.InternalClose` is called which cancels the flow. I added the explicit implementation of `ConsumerDone` with a comment to remove the confusion.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky2DqeC56OSjd8NHNw:-LkyPARC0RZ0E4WmSwX7:bm41y66) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L44)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

One other option is to reuse the mock rpc layer in `colrpc_test`, but I think you're probably correct in going one layer above, as we want to mirror grpc behavior as closely as possible.
</blockquote></details>

Yeah, another consideration was that we don't want to expose `Outbox.runWithStream` as public method, so I thought that going one layer above made sense.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky1Y93-9yzshruPN0Y:-LkyRjBA2pk9Q1ZIb0bW:b-c3n2o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is drainMeta not the same scenario as `consumerDone`?
</blockquote></details>

Yes, thanks. Removed.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 114 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky3D6I0vbKRl3JxK-C:-LkyRp9x4z1SFKDF7U_l:b-r2e0vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L114)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Consider commenting the waitgroup that isn't kept around
</blockquote></details>

Actually, I think we want to use the same `wg` here as everywhere else to make sure that all goroutines are closed. Thanks for the catch!
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky5QRFC_ImAyMA4hRy:-LkyYFFdCIu7txx5w7gv:b-pavw0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

To be clear: In `ConsumerClosed` we don't care about any metadata but in `ConsumerDone` we care that **all** metadata is received.
</blockquote></details>

Great idea, added.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky5pJo3aYhJBS8jMHr:-Lkycqhl-j3398COJU7A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L137)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might as well call this `dialer`.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky6e8g8tHxv15hWk1E:-Lkyd5Jz09XuIRDQUFME:bcq4d07) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L154)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you can just close Donec directly (no need to pass it in to the function), since the `serverStreamNotification`'s scope is limited to inside on iteration of the for loop.
</blockquote></details>

I think you're right, done.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 159 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky6sJF5VphwVXU-Kp3:-LkydIvKCiQKuixJ148o:b-asz0fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L159)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This check is probably not necessary
</blockquote></details>

Yeah, thanks, removed. This was a leftover from previous iterations.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky1n8H3tMZn037vHh9:-LkziPV_7X6eApHNdZMw:b-id86gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L191)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we definitely want to do so, I'm not sure what's causing this error, probably something to look into.
</blockquote></details>

I think this problem has been caused by not protecting access to `i.stream`. I have moved it under the protection of the mutex and haven't seen it again.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky7JImDGHoHn4atcBC:-LkyocBKDP0cojwLPPjp:b-2ymw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L193)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is a really cool test, thanks for adding it! I think we could go an extra level and maybe randomly add a scenario that instead of the materializer being directly connected to the unordered synchronizer, we would have an outbox->inbox->materializer, essentially simulating a remote hop. This would test how we handle `Consumer{Done,Closed}` over the network.
</blockquote></details>

Good idea, added.
___
*[pkg/sql/exec/routers.go, line 256 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky83XJErpHeu-o1LjA:-Lkypvzr7vzCX7YhfRmi:b-2j9awo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/routers.go#L256)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why are we adding this to the `hashRouter`? I don't see the usage of `done` changing scope.
</blockquote></details>

Oops, I forgot t [...]

2019-07-29 22:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Lky1n8H3tMZn037vHh9:-LkzmbwKCBu9lE2HsuiE:bg8r83r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L191)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this problem has been caused by not protecting access to `i.stream`. I have moved it under the protection of the mutex and haven't seen it again.
</blockquote></details>

Lol, my last sentence is funny if you read it literally (as if I "haven't seen [`i.stream`] again"). I meant I haven't seen those rpc layer errors again (at least so far).


<!-- Sent from Reviewable.io -->

2019-07-29 23:05 UTC, yuzefovich commented
Only linters failed (which are now fixed), so it should be green now, yay!

Paraphrasing one blonde pal, "Let's make this PR green again!"

2019-07-30 04:07 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 223 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01wer2vZxDpqV6Tvw:-Ll01wer2vZxDpqV6Tvx:bjobaj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L223)):*
> ```Go
> func (i *Inbox) Next(ctx context.Context) coldata.Batch {
> 	i.mu.Lock()
> 	if i.mu.done {
> ```

Hmm... is this going to be racy? What if we continue past this check and them somebody calls `closeLocked`? Are we contractually obligated to give up at that point?

In general do we really need to do all of this fine grained locking? I don't understand who we're locking for - It seems like we're just synchronizing 2 threads, right? Inbox.Next goroutine and the DrainMeta goroutine? If that's the case, then I feel like we might as well just make the entire Next method synchronized - DrainMeta is already doing that too.
___
*[pkg/sql/exec/colrpc/inbox.go, line 234 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01RKG0TDukvVkinbY:-Ll01RKG0TDukvVkinbZ:bo26bj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L234)):*
> ```Go
> 		// during normal termination.
> 		if err := recover(); err != nil {
> 			i.mu.Lock()
> ```

Isn't this buggy (or at least re-entrant in a confusing way) if we panic while the lock is already locked? Like in the example of a panic during `maybeInitLocked` for some reason.

Also, what about the idea of introducing an`i.close(ctx)` variant that doesn't need the mutex to be locked? That might clean up the code.
___
*[pkg/sql/exec/colrpc/inbox.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01GHS2rrIoPfOyk-v:-Ll01GHS2rrIoPfOyk-w:buvyeq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L261)):*
> ```Go
> 			return i.zeroBatch
> 		}
> 		i.mu.Unlock()
> ```

Seems like Unlock and Lock are called in succession - delete them?


<!-- Sent from Reviewable.io -->

2019-07-30 04:19 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 223 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01wer2vZxDpqV6Tvw:-Ll04WGnC7wS9bXRwO5R:b-bm6dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L223)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... is this going to be racy? What if we continue past this check and them somebody calls `closeLocked`? Are we contractually obligated to give up at that point?

In general do we really need to do all of this fine grained locking? I don't understand who we're locking for - It seems like we're just synchronizing 2 threads, right? Inbox.Next goroutine and the DrainMeta goroutine? If that's the case, then I feel like we might as well just make the entire Next method synchronized - DrainMeta is already doing that too.
</blockquote></details>

I agree - I just kept on adding more and more locking, and now we're at the point when it makes just to acquire the lock for the full duration of the method.
___
*[pkg/sql/exec/colrpc/inbox.go, line 234 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01RKG0TDukvVkinbY:-Ll04qlE4sGJADEPl42G:b-qb3uev) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L234)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Isn't this buggy (or at least re-entrant in a confusing way) if we panic while the lock is already locked? Like in the example of a panic during `maybeInitLocked` for some reason.

Also, what about the idea of introducing an`i.close(ctx)` variant that doesn't need the mutex to be locked? That might clean up the code.
</blockquote></details>

We had such a variant of `i.close(ctx)` at some point but still needed to acquire a lock before checking `i.mu.done`. Now that we're locking the full `Next` method, I think the concern is resolved.
___
*[pkg/sql/exec/colrpc/inbox.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll01GHS2rrIoPfOyk-v:-Ll057Sf0f2i2esel6JD:b-y3z0v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bbc1ace9cbaa92a0d75ccf81c2bb63b274004b3/pkg/sql/exec/colrpc/inbox.go#L261)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Seems like Unlock and Lock are called in succession - delete them?
</blockquote></details>

Yeah, I missed it.


<!-- Sent from Reviewable.io -->

2019-07-30 12:58 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll1tfW28n89P47n-nQP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/outbox.go, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyBUH34KJIkw08gpgK:-Ll1tlN34ZqO0qmS43ZN:bwdrn9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/colrpc/outbox.go#L120)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I might be missing something, but `conn` is created here, within this `Run` method below, by dialing a node, and `conn` is not exposed to anyone else, so we need to explicitly close it for the tests.

I've just noticed that in some cases `conn` was not closed - for example, when sending a header in `Outbox` failed. Here is an example of leaked goroutines:
```
I190729 21:51:16.640228 46 sql/exec/colrpc/outbox.go:173  [streamID=0] Outbox calling cancelFn after Send (batches) EOF
W190729 21:51:16.648893 86 sql/exec/colrpc/outbox.go:151  [streamID=1] Outbox Send header error, distributed query will fail: EOF
--- FAIL: TestVectorizedFlowShutdown (5.05s)
    --- PASS: TestVectorizedFlowShutdown/shutdownScenario=ConsumerDone (0.01s)
    --- PASS: TestVectorizedFlowShutdown/shutdownScenario=ConsumerClosed (0.02s)
    leaktest.go:120: Leaked goroutine: goroutine 127 [select]:
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream.func5(0xc000778600, 0xc0005b8200, 0x747b660, 0xc0001e01b0)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:324 +0xd7
        created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newClientStream
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:323 +0xa26
        
        Leaked goroutine: goroutine 87 [select]:
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ccResolverWrapper).watcher(0xc0001e0150)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:109 +0x13f
        created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ccResolverWrapper).start
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/resolver_conn_wrapper.go:95 +0x3f
        
        Leaked goroutine: goroutine 88 [select]:
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000e0240)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x110
        created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.newCCBalancerWrapper
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x13e
        
        Leaked goroutine: goroutine 89 [select]:
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).createTransport(0xc00061db80, 0x2, 0x0, 0xbf47f876793d6dcd, 0x1429bed95, 0x90229a0, 0xbf47f87ade37bba8, 0x558786f70, 0x90229a0, 0xc000332040, ...)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1361 +0xc86
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc00061db80, 0x7446aa0, 0xc000528130)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1251 +0x41b
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc00061db80)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:1436 +0x3e0
        github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc00061db80)
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:960 +0x1d9
        created by github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*addrConn).connect
        	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/clientconn.go:951 +0xe1
```
I'm not sure how to clean this up properly without explicitly closing the connection. Why don't we need to do the same in other cases?
</blockquote></details>

I think it's fine to need to explicitly close it for tests? how is it supposed to get closed in  ordinary operation?


<!-- Sent from Reviewable.io -->

2019-07-30 12:59 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/outbox.go, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyBUH34KJIkw08gpgK:-Ll1wo7H0N-r163u-xW0:beym771) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/colrpc/outbox.go#L120)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think it's fine to need to explicitly close it for tests? how is it supposed to get closed in  ordinary operation?
</blockquote></details>

Well the thing is that the outbox doesn't own the connection (i.e. it doesn't actually *create* anything, just requests access to it), so shouldn't be the one closing it. The dialer returns a connection it keeps around for any component that needs it to communicate with another node (e.g. for raft or gossip). The only time it's created and should be closed is in the test. I'm saying that in the test since you already define an interface through which you return a conn, you can set some variable on your test dialer to the conn returned and then defer close that.


<!-- Sent from Reviewable.io -->

2019-07-30 13:04 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/exec/colrpc/outbox.go, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyBUH34KJIkw08gpgK:-Ll1y9Nx6Edvg0ZVWYrX:b-o8y5v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/colrpc/outbox.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Well the thing is that the outbox doesn't own the connection (i.e. it doesn't actually *create* anything, just requests access to it), so shouldn't be the one closing it. The dialer returns a connection it keeps around for any component that needs it to communicate with another node (e.g. for raft or gossip). The only time it's created and should be closed is in the test. I'm saying that in the test since you already define an interface through which you return a conn, you can set some variable on your test dialer to the conn returned and then defer close that.
</blockquote></details>

So it would be something like
```
type mockDialer struct {
	addr net.Addr
        conn *grpc.ClientConn
}

func (d *mockDialer) Dial(context.Context, roachpb.NodeID) (*grpc.ClientConn, error) {
        var err error
        if d.conn != nil {
            d.conn.Close()
        }
	d.conn, err = grpc.Dial(d.addr.String(), grpc.WithInsecure())
        return d.con, err
}

// Close must be called after the test.
func (d *mockDialer) Close() {
        d.conn.Close()
}
```
To keep this behavior in testing code.


<!-- Sent from Reviewable.io -->

2019-07-30 13:23 UTC, asubiotto requested changes
> Reviewed 2 of 6 files at r1, 2 of 10 files at r5, 5 of 10 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 172 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyCWjDA6Ctx1X0GbON:-Ll1zLmf1wJzDxg8O_Gl:b556ppv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/distsqlrun/materializer.go#L172)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

So actually that's exactly what's happening here - `ProcessorBase` implements `ConsumerDone` as:
```
// ConsumerDone is part of the RowSource interface.
func (pb *ProcessorBase) ConsumerDone() {
	pb.MoveToDraining(nil /* err */)
}
```
so `materializer` moves to `draining` state, and after all metadata has been drained, `m.InternalClose` is called which cancels the flow. I added the explicit implementation of `ConsumerDone` with a comment to remove the confusion.
</blockquote></details>

Awesome, thanks.
___
*[pkg/sql/distsqlrun/materializer.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1zE4iEQeyDZvl4AQ_:-Ll1zE4iEQeyDZvl4AQa:b-ob5701) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/materializer.go#L92)):*
> ```Go
> 					trailingMeta = append(trailingMeta, src.DrainMeta(ctx)...)
> 				}
> 				m.InternalClose()
> ```

Does this have any unintended side effects (i.e. will `InternalClose` be called twice, and is that bad?)? If so we should probably just `m.cancelFlow()`.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-QK-11_TaLYXif60:-Ll2-QK-11_TaLYXif61:bu1p25y) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
> ```Go
> 				// We either should get no error or a context cancelation error.
> 				if err != nil {
> 					require.True(t, strings.Contains(err.Error(), "context canceled"))
> ```

Note: I think what we usually do here is : `require.True(t, testutils.IsError(err, "context canceled"), err)`
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 223 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-sro4Dlg8BxwbvzJ:-Ll2-sro4Dlg8BxwbvzK:bx8rxez) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L223)):*
> ```Go
> // ConsumerDone shutdown scenario, it checks that the metadata from Outbox is
> // correctly propagated to materializer.
> func TestVectorizedOutboxInboxShutdown(t *testing.T) {
> ```

Since both tests seem very similar, I wonder if we should just make this part of the previous test. i.e. between these two lines:
```
			synchronizer := exec.NewUnorderedSynchronizer(synchronizerInputs, typs, &wg)
			materializer, err := newMaterializer(
```
Add an outbox and then an inbox with a 50% chance.
___
*[pkg/sql/exec/testutils.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1znx72muutpITg4bA:-Ll1znx72muutpITg4bB:b-w8zmy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/testutils.go#L123)):*
> ```Go
> // DrainMeta call will always produce exactly one non-nil metadata object with
> // Err field containing the id.
> type VectorizedDummyMetadataSource struct {
> ```

I think you could probably reuse `CallbackMetadataSource`
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll21amwACJbyxn0gQh0:b-yl516b) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
> ```Go
> // cause Next goroutine to finish.
> func (i *Inbox) DrainMeta(ctx context.Context) []distsqlpb.ProducerMetadata {
> 	i.mu.Lock()
> ```

I like just locking once, but there's a slight problem. Consider the case in which `Next` holds the `mu` and is indefinitely blocked reading from the stream. `DrainMeta` will just block trying to acquire that mutex. Probably what we want to do is send the drain signal before acquiring the mutex in `DrainMeta` and then proceeding. It's safe to use a stream between separate goroutines to `Send` and `Recv` (but you can't `Recv` on the same stream in two different goroutines)


<!-- Sent from Reviewable.io -->

2019-07-30 17:06 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 92 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1zE4iEQeyDZvl4AQ_:-Ll2OTGP3_DQVxAR6ro3:b-kxg0t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/materializer.go#L92)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this have any unintended side effects (i.e. will `InternalClose` be called twice, and is that bad?)? If so we should probably just `m.cancelFlow()`.
</blockquote></details>

No, `InternalClose` will be called only once.  Here is a snippet from `ProcessorBase.moveToTrailingMeta`:
```
	if pb.trailingMetaCallback != nil {
		pb.trailingMeta = append(pb.trailingMeta, pb.trailingMetaCallback(pb.Ctx)...)
	} else {
		pb.InternalClose()
	}
```
and here is a part of the comment about `trailingMetaCallback`:
```
	// trailingMetaCallback, if set, will be called by moveToTrailingMeta(). The
	// callback is expected to close all inputs, do other cleanup on the processor
	// (including calling InternalClose())
```
so I think this is safe. I refactored `materializer.InternalClose` slightly so that `cancelFlow` happens exactly once when the materializer is closed.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-QK-11_TaLYXif60:-Ll2Q6aN3iRrPN_D4mFV:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Note: I think what we usually do here is : `require.True(t, testutils.IsError(err, "context canceled"), err)`
</blockquote></details>

Thanks, done.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 223 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-sro4Dlg8BxwbvzJ:-Ll2RBnUDek2aL754Ri0:b-blxg2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L223)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since both tests seem very similar, I wonder if we should just make this part of the previous test. i.e. between these two lines:
```
			synchronizer := exec.NewUnorderedSynchronizer(synchronizerInputs, typs, &wg)
			materializer, err := newMaterializer(
```
Add an outbox and then an inbox with a 50% chance.
</blockquote></details>

And connect this new chain through an unordered synchronizer to the materializer? We already have 3 of these. Or connecting to a new materializer? Well, then I think we should keep it as a separate test then. In a sense, we will have a full flow shutdown test and a single remote connection shutdown test; the latter can be useful to triage the former.
___
*[pkg/sql/exec/testutils.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1znx72muutpITg4bA:-Ll2TZSr7cvN-lZgcskx:bkhd8qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/testutils.go#L123)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you could probably reuse `CallbackMetadataSource`
</blockquote></details>

I think I could use it only for `Outbox`es but not `hashRouterOutput`s because the latter are created by `HashRouter` itself and it doesn't allow specifying metadata sources for its outputs.
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll2pZpX-k30XEklfO7Z:bs65z9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I like just locking once, but there's a slight problem. Consider the case in which `Next` holds the `mu` and is indefinitely blocked reading from the stream. `DrainMeta` will just block trying to acquire that mutex. Probably what we want to do is send the drain signal before acquiring the mutex in `DrainMeta` and then proceeding. It's safe to use a stream between separate goroutines to `Send` and `Recv` (but you can't `Recv` on the same stream in two different goroutines)
</blockquote></details>

Good point, added the needed logic.
___
*[pkg/sql/exec/colrpc/outbox.go, line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LkyBUH34KJIkw08gpgK:-Ll2VOgyDHEzoaAC_YyI:buftc3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5734e10734f4aac7af42fa81fa0bd3a27bd8a16d/pkg/sql/exec/colrpc/outbox.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So it would be something like
```
type mockDialer struct {
	addr net.Addr
        conn *grpc.ClientConn
}

func (d *mockDialer) Dial(context.Context, roachpb.NodeID) (*grpc.ClientConn, error) {
        var err error
        if d.conn != nil {
            d.conn.Close()
        }
	d.conn, err = grpc.Dial(d.addr.String(), grpc.WithInsecure())
        return d.con, err
}

// Close must be called after the test.
func (d *mockDialer) Close() {
        d.conn.Close()
}
```
To keep this behavior in testing code.
</blockquote></details>

Thanks! Done. I didn't look carefully at the code.


<!-- Sent from Reviewable.io -->

2019-07-30 17:17 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll2scLr31VUpQl8EPiF:b-lxmkni) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Good point, added the needed logic.
</blockquote></details>

But I still think that what I added with an atomic swap is insufficient. I'm not sure how to guarantee that `i.mu.stream` has been initialized without holding the mutex.


<!-- Sent from Reviewable.io -->

2019-07-30 19:56 UTC, asubiotto requested changes
> Reviewed 3 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 223 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-sro4Dlg8BxwbvzJ:-Ll3O86H8yq9YK2WCFh0:b-w2fqp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L223)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

And connect this new chain through an unordered synchronizer to the materializer? We already have 3 of these. Or connecting to a new materializer? Well, then I think we should keep it as a separate test then. In a sense, we will have a full flow shutdown test and a single remote connection shutdown test; the latter can be useful to triage the former.
</blockquote></details>

The former, i.e. `unordered sync -> outbox -> inbox -> materializer`. I think it also increases the coverage more than having two separate tests because it tests how outboxes shut down their input flow.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 128 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3QBt4-UPsD_VuI8yu:-Ll3QBt5-uea0IoMf7zH:b-yz8vn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L128)):*
> ```Go
> 			inboxes := make([]*colrpc.Inbox, numInboxes)
> 			for _, o := range hashRouterOutputs {
> 				ms := exec.NewVectorizedDummyMetadataSource(o, metadataSourceID)
> ```

As mentioned below, these don't generate metadata. The only component that does is the `hashRouter`, you can simulate some metadata by appending to `hashRouter.bufferedMetadata` directly (i.e. no need to create `VectorizedDummyMetadataSource`.)
___
*[pkg/sql/exec/testutils.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1znx72muutpITg4bA:-Ll3PUtz5CwkMhTB-Mfz:bxvo8l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/testutils.go#L123)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think I could use it only for `Outbox`es but not `hashRouterOutput`s because the latter are created by `HashRouter` itself and it doesn't allow specifying metadata sources for its outputs.
</blockquote></details>

Hmm, `hashRouterOutput`s don't ever generate metadata so we shouldn't be creating any metadata source that corresponds to them. I'm realizing that the metadata test might be slightly wrong: commented on that.
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll3Qupv6zMd3Q7Ps4IB:b-z42b0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

But I still think that what I added with an atomic swap is insufficient. I'm not sure how to guarantee that `i.mu.stream` has been initialized without holding the mutex.
</blockquote></details>

Another thing you could do is just release the mutex before `Recv`ing and reacquiring right after, this might also remove the need to send a drain signal first. The only annoying bit is that `Recv` might panic (unlikely) which we'll probably have to handle in the `recover()`.
___
*[pkg/sql/exec/colrpc/inbox.go, line 321 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3Qzol0JGDW0sAm7Ra:-Ll3Qzol0JGDW0sAm7Rb:bo5zku7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/exec/colrpc/inbox.go#L321)):*
> ```Go
> 			log.Warningf(ctx, "Inbox unable to send drain signal to Outbox: %+v", err)
> 			// TODO(yuzefovich): do we want to grab i.mu.bufferedMeta here without
> 			// holding i.mu since we know that the reader is blocked anyway?
> ```

Sometimes there're some cases where if your goroutine is scheduled on another proc as another goroutine that has updated a value, you might not see the latest updated value (it's in cache). Doing a mutex lock is essentially like a *flush*. I remember reading this a long time ago so don't have anywhere to point you but can try dig it up if you want.


<!-- Sent from Reviewable.io -->

2019-07-31 01:09 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 223 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll2-sro4Dlg8BxwbvzJ:-Ll3bjSo2L3giJkejVyF:b-2fuwub) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L223)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The former, i.e. `unordered sync -> outbox -> inbox -> materializer`. I think it also increases the coverage more than having two separate tests because it tests how outboxes shut down their input flow.
</blockquote></details>

Oh, I see. I misunderstood your idea at first. I like it, done.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 128 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3QBt4-UPsD_VuI8yu:-Ll4QEOMCPcd7LUqZgBJ:b8h287d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

As mentioned below, these don't generate metadata. The only component that does is the `hashRouter`, you can simulate some metadata by appending to `hashRouter.bufferedMetadata` directly (i.e. no need to create `VectorizedDummyMetadataSource`.)
</blockquote></details>

Yeah, I thought I would add some extra. Removed. However, there are no public methods on Hash Router to easily inject into `bufferedMetadata`. Do you think it's worth it plumbing it through?
___
*[pkg/sql/exec/testutils.go, line 123 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll1znx72muutpITg4bA:-Ll4UCQf0po6ZjtSuo0u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/testutils.go#L123)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, `hashRouterOutput`s don't ever generate metadata so we shouldn't be creating any metadata source that corresponds to them. I'm realizing that the metadata test might be slightly wrong: commented on that.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll4Yi2ABeGrA89YPxs_:b-5zest3) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Another thing you could do is just release the mutex before `Recv`ing and reacquiring right after, this might also remove the need to send a drain signal first. The only annoying bit is that `Recv` might panic (unlikely) which we'll probably have to handle in the `recover()`.
</blockquote></details>

Done. I still have a couple of concerns, left comments in the code.
___
*[pkg/sql/exec/colrpc/inbox.go, line 321 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3Qzol0JGDW0sAm7Ra:-Ll4UMj_3pM7d_8BKXXJ:bophy7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/exec/colrpc/inbox.go#L321)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sometimes there're some cases where if your goroutine is scheduled on another proc as another goroutine that has updated a value, you might not see the latest updated value (it's in cache). Doing a mutex lock is essentially like a *flush*. I remember reading this a long time ago so don't have anywhere to point you but can try dig it up if you want.
</blockquote></details>

I guess we'll just return `nil` in this case.


<!-- Sent from Reviewable.io -->

2019-07-31 03:38 UTC, yuzefovich reviewed
Now the new test no longer passes :cry: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll55m384Jlrgc5Tz8oY:b-li10mp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-07-31 03:48 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll57JCN6flUuQq1nmxr:b-s3lsow) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done. I still have a couple of concerns, left comments in the code.
</blockquote></details>

I'm seeing different failures:
- `rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: illegal wireType 6`
- `rpc error: code = ResourceExhausted desc = grpc: received message larger than max (2504067728 vs. 2147483647)`
- `fatal error: sync: unlock of unlocked mutex` (`github.com/cockroachdb/cockroach/pkg/sql/distsqlpb.(*distSQLFlowStreamServer).Recv` is in the stack trace for this one)

So I'm guessing that access to `i.mu.stream` must be synchronized after all (I've seen similar failures before, when we were not holding the mutex when calling `stream.Recv`)?


<!-- Sent from Reviewable.io -->

2019-07-31 15:06 UTC, asubiotto requested changes
Based on my experience with #39137, I think that canceling a flow after draining in the current state is not 100% correct given that we might cancel a query subtree that hasn't been drained yet. However, we're going to change it so that components only drain their input operator subtree, in which case the cancellation works. Not something to do in this PR, but just an FYI.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll7Y5QEAFtAJGd97cWE:b-3wk1m3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7LzvC-jkjsQO38-yx:-Ll7LzvC-jkjsQO38-yy:be8pijb) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
> ```Go
> 				// Closed}; however, some asynchronous components will actually be
> 				// canceled only when Flow.ctxCancel is called. I feel like we should
> 				// propagate Flow.ctxCancel into the materializer.
> ```

That's kind of surprising. The context that an inbox listens for cancellation on is the context passed in `Next`, which is the context the materializer should be using when passing it to its input operator tree. ~Am I missing something?~ Ah, I think I get it, it works for the inbox, but not for the outbox. This is expected but uncovers a scenario we hadn't thought of. The context passed into an outbox at creation is not the one that is canceled, but the outbox should also have a way to cancel its input flow just like the materializer does when it finishes draining. Consider the case in which an outbox is on a separate node as the materializer. The outbox will never be created with a context associated with the materializer.
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll7P1GlEsZuI3v7gP6g:bi2eo54) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm seeing different failures:
- `rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: illegal wireType 6`
- `rpc error: code = ResourceExhausted desc = grpc: received message larger than max (2504067728 vs. 2147483647)`
- `fatal error: sync: unlock of unlocked mutex` (`github.com/cockroachdb/cockroach/pkg/sql/distsqlpb.(*distSQLFlowStreamServer).Recv` is in the stack trace for this one)

So I'm guessing that access to `i.mu.stream` must be synchronized after all (I've seen similar failures before, when we were not holding the mutex when calling `stream.Recv`)?

</blockquote></details>

Hmm, I think it's because we're still calling `Recv` from two different goroutines, which is illegal. I think it might be time to take a step back and rethink what we're trying to solve. We want draining to work here regardless of whether or not we have a goroutine in `Next`. We essentially need to do two things: 1) Is the stream safe to use? If yes, then 2) Make sure nobody else is receiving. Unfortunately there is no way to cancel a receive on a stream so we need to do this by sending the message. However, we can't unconditionally send a message because we don't know the state of the stream (is it initialized?). I think what this leaves us with is having two separate mutexes, one for the state (the current i.mu) and another one for the stream, to make sure we wait until the `Next` goroutine has finished `Recving`. The other option is to let `Next` do all the work of `Recv`ing metadata but I'm not sure that will work if there is no goroutine in `Next`. There might be a better solution, maybe we can come up with something.
___
*[pkg/sql/exec/colrpc/inbox.go, line 174 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7OUy45dw2VsoISwyn:-Ll7OUy51z8qNVKG3CL3:b17s5xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/exec/colrpc/inbox.go#L174)):*
> ```Go
> }
> 
> func (i *Inbox) close() {
> ```

It feels wrong to have two close variants and seems like it could lead to confusion. I think we should just have a local variable in `Next` that indicates whether or not we were in `Recv` and lock or not accordingly.


<!-- Sent from Reviewable.io -->

2019-07-31 15:06 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox.go, line 277 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7ZNou8IvMOwbXHWCx:-Ll7ZNou8IvMOwbXHWCy:b-u4msev) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/exec/colrpc/inbox.go#L277)):*
> ```Go
> 		// I think it is possible that DrainMeta goroutine was called while Next
> 		// goroutine was blocked on Recv, so now Next goroutine should just exit
> 		// right away.
> ```

I don't think so, otherwise we could drop metadata.


<!-- Sent from Reviewable.io -->

2019-07-31 16:21 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7LzvC-jkjsQO38-yx:-Ll7nU_u7e0RzbzW_dS0:b-38uga7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That's kind of surprising. The context that an inbox listens for cancellation on is the context passed in `Next`, which is the context the materializer should be using when passing it to its input operator tree. ~Am I missing something?~ Ah, I think I get it, it works for the inbox, but not for the outbox. This is expected but uncovers a scenario we hadn't thought of. The context passed into an outbox at creation is not the one that is canceled, but the outbox should also have a way to cancel its input flow just like the materializer does when it finishes draining. Consider the case in which an outbox is on a separate node as the materializer. The outbox will never be created with a context associated with the materializer.
</blockquote></details>

Yeah. Similar situation is with hash routers: they are started with a different context than the one that materializer will cancel. I'm not sure what to do about it though.
___
*[pkg/sql/exec/colrpc/inbox.go, line 298 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll21amwACJbyxn0gQh-:-Ll7kxcx6-8C60Wr5ABI:b-s2ukwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/27be3f1160043ba54fce87bf4913ee0b0ff1d2c9/pkg/sql/exec/colrpc/inbox.go#L298)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, I think it's because we're still calling `Recv` from two different goroutines, which is illegal. I think it might be time to take a step back and rethink what we're trying to solve. We want draining to work here regardless of whether or not we have a goroutine in `Next`. We essentially need to do two things: 1) Is the stream safe to use? If yes, then 2) Make sure nobody else is receiving. Unfortunately there is no way to cancel a receive on a stream so we need to do this by sending the message. However, we can't unconditionally send a message because we don't know the state of the stream (is it initialized?). I think what this leaves us with is having two separate mutexes, one for the state (the current i.mu) and another one for the stream, to make sure we wait until the `Next` goroutine has finished `Recving`. The other option is to let `Next` do all the work of `Recv`ing metadata but I'm not sure that will work if there is no goroutine in `Next`. There might be a better solution, maybe we can come up with something.
</blockquote></details>

I see, thanks for the explanation, this makes sense.
___
*[pkg/sql/exec/colrpc/inbox.go, line 174 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7OUy45dw2VsoISwyn:-Ll7nr7321xY-XDPVv-G:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/exec/colrpc/inbox.go#L174)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels wrong to have two close variants and seems like it could lead to confusion. I think we should just have a local variable in `Next` that indicates whether or not we were in `Recv` and lock or not accordingly.
</blockquote></details>

Removed.
___
*[pkg/sql/exec/colrpc/inbox.go, line 277 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7ZNou8IvMOwbXHWCx:-Ll7nssUEODr7xVxmG3z:b2nhll9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/exec/colrpc/inbox.go#L277)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think so, otherwise we could drop metadata.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2019-07-31 16:25 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/exec/colrpc/inbox.go, line 162 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7ptu90s6xDRxh6cgU:-Ll7ptu90s6xDRxh6cgV:bi68t14) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L162)):*
> ```Go
> // point ownership is transferred to RunWithStream. This should only be called
> // from the reader goroutine when it needs a stream.
> // NOTE: i.streamMu *must* be held when calling this function.
> ```

This is actually unnecessary - holding `i.stateMu` is sufficient here (and we always hold it in `maybeInitLocked`), but it seems weird to require that a different mutex is held. Thoughts?


<!-- Sent from Reviewable.io -->

2019-07-31 16:41 UTC, asubiotto requested changes
Thanks for bearing with this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll7ti_12DAnW20Kp_d8:bk7tudg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 128 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3QBt4-UPsD_VuI8yu:-Ll7u-bVDFW-7yNFlfaB:bwh3wm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L128)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, I thought I would add some extra. Removed. However, there are no public methods on Hash Router to easily inject into `bufferedMetadata`. Do you think it's worth it plumbing it through?
</blockquote></details>

I don't htink so.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7LzvC-jkjsQO38-yx:-Ll7rpHQ2wr4qGNI8inq:bmnb8he) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah. Similar situation is with hash routers: they are started with a different context than the one that materializer will cancel. I'm not sure what to do about it though.
</blockquote></details>

True, well I think we just have the `outbox` and `hashRouter` derive a `context.WithCancel` from the passed in context and then cancel it at the end of `DrainMeta` in `hashRouter` and `sendMetadata` in the outbox (i.e. once they've finished draining their inputs).
___
*[pkg/sql/exec/colrpc/inbox.go, line 70 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7tQhL6Pq-tHGFoJ91:-Ll7tQhL6Pq-tHGFoJ92:bamnc4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L70)):*
> ```Go
> 	errCh chan error
> 
> 	// We want draining the Inbox to work regardless of whether or not we have a
> ```

This is written in the context of `DrainMeta` so makes less sense here. Do you think there's a way to generalize the explanation?
___
*[pkg/sql/exec/colrpc/inbox.go, line 162 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7ptu90s6xDRxh6cgU:-Ll7sNUlBtM8nismVcri:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L162)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This is actually unnecessary - holding `i.stateMu` is sufficient here (and we always hold it in `maybeInitLocked`), but it seems weird to require that a different mutex is held. Thoughts?
</blockquote></details>

Agreed.
___
*[pkg/sql/exec/colrpc/inbox.go, line 335 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7t9Y_CHYjiGwn10Az:-Ll7t9Y_CHYjiGwn10B-:b-j7qv70) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L335)):*
> ```Go
> 	if i.stateMu.initialized {
> 		log.VEvent(ctx, 2, "Inbox sending drain signal to Outbox")
> 		// It is safe to Send without holding the mutex.
> ```

Maybe elaborate: "because it is legal to call `Send` and `Recv` from different goroutines"
___
*[pkg/sql/exec/colrpc/inbox.go, line 347 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7snAJ19sbk0Ya89-e:-Ll7snAJ19sbk0Ya89-f:bbu5w9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L347)):*
> ```Go
> 	// the lock when this one is executed.
> 	defer func() {
> 		// Catch any panics that occur and close the errCh in order to not leak the
> ```

I don't think we need to defer this recover function. If we panic `defer i.closeLocked()` will execute anyway.


<!-- Sent from Reviewable.io -->

2019-07-31 18:36 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 128 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll3QBt4-UPsD_VuI8yu:-Ll7wGiT82cHgUr9e1dl:b2nhll9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81e40cb7edcd956bb01f58184bc9e9ad8a8d96a/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't htink so.
</blockquote></details>

Ok.
___
*[pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7LzvC-jkjsQO38-yx:-Ll86aVVBmCvT48Iz8lO:b-8bvb41) ([raw file](https://github.com/cockroachdb/cockroach/blob/00ee2ef0eee3a396ca4dacbffb3b2a5ba9447d69/pkg/sql/distsqlrun/vectorized_flow_shutdown_test.go#L210)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

True, well I think we just have the `outbox` and `hashRouter` derive a `context.WithCancel` from the passed in context and then cancel it at the end of `DrainMeta` in `hashRouter` and `sendMetadata` in the outbox (i.e. once they've finished draining their inputs).
</blockquote></details>

Done (although I'm a little unsure about `Outbox` case - about different contexts).
___
*[pkg/sql/exec/colrpc/inbox.go, line 70 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7tQhL6Pq-tHGFoJ91:-Ll8IDdR40oUAYCvW55V:bedjoo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is written in the context of `DrainMeta` so makes less sense here. Do you think there's a way to generalize the explanation?
</blockquote></details>

I'm having trouble generalizing this problem. I feel like it is innate to `DrainMeta`'s context, so I moved the comment.
___
*[pkg/sql/exec/colrpc/inbox.go, line 162 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7ptu90s6xDRxh6cgU:-Ll7vxrA5AYTlWv_GaDK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L162)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 335 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7t9Y_CHYjiGwn10Az:-Ll7w3YJA2vm-ONITMUI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L335)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe elaborate: "because it is legal to call `Send` and `Recv` from different goroutines"
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox.go, line 347 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll7snAJ19sbk0Ya89-e:-Ll7w9LZ5tQnAjrldd_d:buxa7q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/inbox.go#L347)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we need to defer this recover function. If we panic `defer i.closeLocked()` will execute anyway.
</blockquote></details>

Thanks, I wasn't sure about that.


<!-- Sent from Reviewable.io -->

2019-07-31 23:07 UTC, yuzefovich reviewed
I think I made the changes the way we discussed with Alfonso, but hash router doesn't get closed :/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll9HFER8hjqqMbc2WPI:bkxqcj4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-07-31 23:17 UTC, yuzefovich reviewed
Here are the logs (not sure if this is helpful).
`ConsumerDone`:
```
I190731 23:09:56.840476 27 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 0 is running
I190731 23:09:56.840521 27 sql/exec/colrpc/outbox.go:120  [streamID=0] Outbox Dialing 3
I190731 23:09:56.843048 27 sql/exec/colrpc/outbox.go:142  [streamID=0] Outbox sending header
I190731 23:09:56.844670 27 sql/exec/colrpc/outbox.go:155  [streamID=0] Outbox starting normal operation
I190731 23:09:56.846181 74 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 1 is running
I190731 23:09:56.846208 74 sql/exec/colrpc/outbox.go:120  [streamID=1] Outbox Dialing 3
I190731 23:09:56.846486 73 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 0 is running
I190731 23:09:56.849849 74 sql/exec/colrpc/outbox.go:142  [streamID=1] Outbox sending header
I190731 23:09:56.849953 74 sql/exec/colrpc/outbox.go:155  [streamID=1] Outbox starting normal operation
I190731 23:09:56.851292 163 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 2 is running
I190731 23:09:56.853855 163 sql/exec/colrpc/outbox.go:120  [streamID=2] Outbox Dialing 3
I190731 23:09:56.854588 162 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 1 is running
I190731 23:09:56.863310 163 sql/exec/colrpc/outbox.go:142  [streamID=2] Outbox sending header
I190731 23:09:56.863772 163 sql/exec/colrpc/outbox.go:155  [streamID=2] Outbox starting normal operation
I190731 23:09:56.864700 181 sql/distsqlrun/vectorized_flow_shutdown_test.go:259  HashRouter is running
I190731 23:09:56.865038 180 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 2 is running
I190731 23:09:56.865576 98 sql/exec/colrpc/outbox.go:280  [streamID=0] Outbox received drain request
I190731 23:09:56.867698 98 sql/exec/colrpc/outbox.go:175  [streamID=0] Outbox moved to draining
I190731 23:09:56.868550 27 sql/exec/colrpc/outbox.go:288  [streamID=0] Outbox terminated gracefully %!s(bool=true) with err <nil>
I190731 23:09:56.870687 73 sql/distsqlrun/vectorized_flow_shutdown_test.go:214  Inbox 0 is done
I190731 23:09:56.871143 146 sql/exec/colrpc/outbox.go:280  [streamID=1] Outbox received drain request
I190731 23:09:56.871156 146 sql/exec/colrpc/outbox.go:175  [streamID=1] Outbox moved to draining
I190731 23:09:56.871938 27 sql/distsqlrun/vectorized_flow_shutdown_test.go:200  Outbox 0 is done
I190731 23:09:56.871972 74 sql/exec/colrpc/outbox.go:288  [streamID=1] Outbox terminated gracefully %!s(bool=true) with err <nil>
I190731 23:09:56.875071 162 sql/distsqlrun/vectorized_flow_shutdown_test.go:214  Inbox 1 is done
I190731 23:09:56.875116 163 sql/exec/colrpc/outbox.go:288  [streamID=2] Outbox terminated gracefully %!s(bool=true) with err <nil>
I190731 23:09:56.875168 163 sql/exec/colrpc/outbox.go:175  [streamID=2] Outbox moved to draining
I190731 23:09:56.875472 31 sql/exec/colrpc/outbox.go:280  [streamID=2] Outbox received drain request
I190731 23:09:56.875473 74 sql/distsqlrun/vectorized_flow_shutdown_test.go:200  Outbox 1 is done
I190731 23:09:56.876057 180 sql/distsqlrun/vectorized_flow_shutdown_test.go:214  Inbox 2 is done
I190731 23:09:56.876286 163 sql/distsqlrun/vectorized_flow_shutdown_test.go:200  Outbox 2 is done
panic: test timed out after 10s
```
`ConsumerClosed`:
```
I190731 23:15:51.574518 26 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 0 is running
I190731 23:15:51.574560 26 sql/exec/colrpc/outbox.go:120  [streamID=0] Outbox Dialing 3
I190731 23:15:51.575648 26 sql/exec/colrpc/outbox.go:142  [streamID=0] Outbox sending header
I190731 23:15:51.575721 26 sql/exec/colrpc/outbox.go:155  [streamID=0] Outbox starting normal operation
I190731 23:15:51.576131 45 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 1 is running
I190731 23:15:51.576182 44 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 0 is running
I190731 23:15:51.576219 45 sql/exec/colrpc/outbox.go:120  [streamID=1] Outbox Dialing 3
I190731 23:15:51.576762 45 sql/exec/colrpc/outbox.go:142  [streamID=1] Outbox sending header
I190731 23:15:51.576782 45 sql/exec/colrpc/outbox.go:155  [streamID=1] Outbox starting normal operation
I190731 23:15:51.577011 69 sql/distsqlrun/vectorized_flow_shutdown_test.go:259  HashRouter is running
I190731 23:15:51.577032 68 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 1 is running
panic: test timed out after 10s
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll9ICmr81cZqVs9wrK2:bp1objk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-08-01 00:30 UTC, asubiotto requested changes
Hmm I'm not sure. Looking at the consumer closed case, which is simpler, it doesn't seem like the outboxes are returning from `sendBatches`. Maybe add a log message to make sure we're returning from `RunWithStream` in the inboxes and at the other extreme, that the materializer is calling the cancel function. I'll take another look tomorrow.

> Reviewed 7 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll9WZKS1b0m6Gb6Dd7m:b-7pbolv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/flow.go, line 535 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll9POUgCJtgNHHcGelj:-Ll9POUhBDQrvjJl2NB_:b-h10b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb550b1d009b6669b3c2f735e19b36c5fe6f1ed/pkg/sql/distsqlrun/flow.go#L535)):*
> ```Go
> 	)
> 
> 	if f.ctxCancel == nil {
> ```

I think we can probably get rid of this since a flow must be `setup` before `started` right?


<!-- Sent from Reviewable.io -->

2019-08-01 02:19 UTC, yuzefovich reviewed
I ran into an interesting situation where `Inbox`es exited before `materializer.ConsumerClosed` was called:
```
=== RUN   TestVectorizedFlowShutdown/shutdownScenario=ConsumerClosed#01
I190801 02:09:39.820256 63 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 0 is running
I190801 02:09:39.820272 63 sql/exec/colrpc/outbox.go:120  [streamID=0] Outbox Dialing 3
I190801 02:09:39.822021 63 sql/exec/colrpc/outbox.go:142  [streamID=0] Outbox sending header
I190801 02:09:39.822038 63 sql/exec/colrpc/outbox.go:155  [streamID=0] Outbox starting normal operation
I190801 02:09:39.823212 108 sql/distsqlrun/vectorized_flow_shutdown_test.go:197  Outbox 1 is running
I190801 02:09:39.823226 107 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 0 is running
I190801 02:09:39.823227 108 sql/exec/colrpc/outbox.go:120  [streamID=1] Outbox Dialing 3
I190801 02:09:39.823238 107 sql/exec/colrpc/inbox.go:186  Inbox handling stream
I190801 02:09:39.825531 108 sql/exec/colrpc/outbox.go:142  [streamID=1] Outbox sending header
I190801 02:09:39.825690 108 sql/exec/colrpc/outbox.go:155  [streamID=1] Outbox starting normal operation
I190801 02:09:39.835930 79 sql/distsqlrun/vectorized_flow_shutdown_test.go:261  HashRouter is running
I190801 02:09:39.836024 107 sql/exec/colrpc/inbox.go:196  Inbox reader arrived
I190801 02:09:39.835955 78 sql/distsqlrun/vectorized_flow_shutdown_test.go:210  Inbox 1 is running
I190801 02:09:39.836043 78 sql/exec/colrpc/inbox.go:186  Inbox handling stream
I190801 02:09:39.836159 78 sql/exec/colrpc/inbox.go:196  Inbox reader arrived
I190801 02:09:48.829608 107 sql/exec/colrpc/inbox.go:213  Inbox exited stream handler
I190801 02:09:48.829662 107 sql/distsqlrun/vectorized_flow_shutdown_test.go:214  Inbox 0 is done
I190801 02:09:48.829847 78 sql/exec/colrpc/inbox.go:210  Inbox exited stream handler
I190801 02:09:48.829881 78 sql/distsqlrun/vectorized_flow_shutdown_test.go:214  Inbox 1 is done
materializer is canceling the flow
I190801 02:09:48.830476 63 sql/exec/colrpc/outbox.go:166  [streamID=0] Outbox calling cancelFn after Send (batches) EOF
I190801 02:09:48.830495 108 sql/exec/colrpc/outbox.go:166  [streamID=1] Outbox calling cancelFn after Send (batches) EOF
I190801 02:09:48.830513 108 sql/exec/colrpc/outbox.go:288  [streamID=1] Outbox terminated gracefully %!s(bool=false) with err <nil>
I190801 02:09:48.830515 79 sql/distsqlrun/vectorized_flow_shutdown_test.go:264  HashRouter is done
I190801 02:09:48.830501 63 sql/exec/colrpc/outbox.go:288  [streamID=0] Outbox terminated gracefully %!s(bool=false) with err <nil>
E190801 02:09:48.830607 125 sql/exec/colrpc/outbox.go:272  [streamID=1] Outbox Recv connection error: rpc error: code = Canceled desc = grpc: the client connection is closing
I190801 02:09:48.830657 108 sql/distsqlrun/vectorized_flow_shutdown_test.go:200  Outbox 1 is done
E190801 02:09:48.830628 43 sql/exec/colrpc/outbox.go:272  [streamID=0] Outbox Recv connection error: rpc error: code = Canceled desc = grpc: the client connection is closing
I190801 02:09:48.830692 63 sql/distsqlrun/vectorized_flow_shutdown_test.go:200  Outbox 0 is done
```
Not sure how it was possible, but this represented itself as not being able to read 10 non-nil rows from the materializer:
```
    --- FAIL: TestVectorizedFlowShutdown/shutdownScenario=ConsumerClosed#01 (9.22s)
        require.go:919: 
            	Error Trace:	vectorized_flow_shutdown_test.go:271
            	Error:      	Expected value not to be nil.
            	Test:       	TestVectorizedFlowShutdown/shutdownScenario=ConsumerClosed#01
```
I feel like I probably have been staring at this PR for too long so that I'm not seeing something more or less obvious.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-Ll9xnmB953OlyKyW19O:b7c2y2v)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/flow.go, line 535 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-Ll9POUgCJtgNHHcGelj:-Ll9oIvI-NHuH0ziiodH:bh4drcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cb550b1d009b6669b3c2f735e19b36c5fe6f1ed/pkg/sql/distsqlrun/flow.go#L535)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we can probably get rid of this since a flow must be `setup` before `started` right?
</blockquote></details>

I wasn't sure about that (I searched for usages of `startInternal` and thought that on the remote nodes it could be called without calling `setup`), but I think you're right. Removed.


<!-- Sent from Reviewable.io -->

2019-08-01 14:08 UTC, asubiotto approved these changes
Seems like you figured it out last night. I'm stressing it and the test seems to run fine. What was it?

This now <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> minus nits and leftover log/print mesages (also the `consumerDone` test case needs to be enabled again).

> Reviewed 2 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LlCSyxS5kWDLmLdMc3F:bcpp4g1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 56 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlCTFqRCv0aGo546dIg:-LlCTFqRCv0aGo546dIh:b-csyc20) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d35292a6ea34a310ed142d07d4f985968a6d6b4/pkg/sql/distsqlrun/materializer.go#L56)):*
> ```Go
> 	outputMetadata *distsqlpb.ProducerMetadata
> 
> 	// ctxCancel will cancel the context that is passed to input (which will pass
> ```

nit: `s/to input/to the input`, `s/of tree/of the tree`
___
*[pkg/sql/distsqlrun/materializer.go, line 64 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlCTYSV2qpwwG5E6giR:-LlCTYSV2qpwwG5E6giS:beygzen) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d35292a6ea34a310ed142d07d4f985968a6d6b4/pkg/sql/distsqlrun/materializer.go#L64)):*
> ```Go
> const materializerProcName = "materializer"
> 
> // cancelFlow is the context cancellation function that cancels the context of
> ```

nit: begin this comment with `newMaterializer` and maybe add a brief description of the other arguments as well?


<!-- Sent from Reviewable.io -->

2019-08-01 14:22 UTC, yuzefovich reviewed
I had some issues with the test setup which I fixed, but it still fails reliably for me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LlCYlHt6T02ylUk9MV-:bkd669n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/materializer.go, line 56 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlCTFqRCv0aGo546dIg:-LlCYdiA6-TKWX6IY9n7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d35292a6ea34a310ed142d07d4f985968a6d6b4/pkg/sql/distsqlrun/materializer.go#L56)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/to input/to the input`, `s/of tree/of the tree`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/materializer.go, line 64 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlCTYSV2qpwwG5E6giR:-LlCYeMn-ka7Ait7qpuS:blknm4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d35292a6ea34a310ed142d07d4f985968a6d6b4/pkg/sql/distsqlrun/materializer.go#L64)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: begin this comment with `newMaterializer` and maybe add a brief description of the other arguments as well?
</blockquote></details>

Done (some arguments I think are obvious, so I didn't mention those).


<!-- Sent from Reviewable.io -->

2019-08-01 14:28 UTC, asubiotto commented
Oh, I think I see why it's different. You were running with `TESTTIMEOUT=10s`, right? I'm stressing it and see:
```
1047 runs so far, 0 failures, over 1m5s
1061 runs so far, 0 failures, over 1m10s
1061 runs so far, 0 failures, over 1m15s
1061 runs so far, 0 failures, over 1m20s
1061 runs so far, 0 failures, over 1m25s
1091 runs so far, 0 failures, over 1m30s
```
So it seems like sometimes it stalls but gets unblocked. Will run with that timeout.

2019-08-01 23:34 UTC, yuzefovich reviewed
Okay, the test now reliably passes under the stress. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LlEX0HE1XJUWzN7Tkkh:bzfaekn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-08-02 00:47 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlEmlN51gl3MMLGibNo:b-l6cwkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
> ```Go
> 	// of the infrastructure on the remote nodes, we need to drain the outboxes
> 	// on those remote nodes.
> 	m.trailingMetaCallback(m.Ctx)
> ```

Unfortunately, without explicitly draining here, the remote infrastructure is still left hanging.


<!-- Sent from Reviewable.io -->

2019-08-02 01:33 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlEtahoAPGmSVd2bIKn:b-qhq8dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Unfortunately, without explicitly draining here, the remote infrastructure is still left hanging.
</blockquote></details>

That's unexpected, right? Materializer flow context cancellation should close inbox streams which will cause outboxes to receive an EOF and cancel their flow context.
___
*[pkg/sql/exec/colrpc/inbox.go, line 82 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEwBpzBSqAt9W4eAEy:-LlEwBpzBSqAt9W4eAEz:bycvgc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/exec/colrpc/inbox.go#L82)):*
> ```Go
> 		done bool
> 		// nextRunning indicates whether Next goroutine is running at the moment.
> 		nextRunning bool
> ```

It's a pity to have so many state variables but at this time I don't know how to improve this (maybe having a single enum variable?). I think it's fine to merge it like this as long as the tests pass but hopefully we'll come up with a simpler way.
___
*[pkg/sql/exec/colrpc/outbox.go, line 280 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvJ7o7RrOk7ncJiBD:-LlEvJ7pEoOh6mryoGQd:b-m54hlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/outbox.go#L280)):*
> ```Go
> 				log.VEventf(ctx, 2, "Outbox received handshake: %v", msg.Handshake)
> 			case msg.DrainRequest != nil:
> 				log.VEvent(ctx, 2, "Outbox received drain request")
> ```

nit: we sould probably leave this log message in.
___
*[pkg/sql/exec/colrpc/outbox.go, line 48 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEuShM1jjKXvxD0Ac5:-LlEuShM1jjKXvxD0Ac6:b-6uzp1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/exec/colrpc/outbox.go#L48)):*
> ```Go
> // be used concurrently. Exactly one OutboxRegistry must be associated with
> // each node of the cluster.
> type OutboxRegistry struct {
> ```

I feel like having an outbox registry is overkill. All we really need is a uint32 atomically incremented in the `vectorizedFlowCreator` right before we call the `startableFn` and then an atomic decrement after the outbox exits from `Run` with a `cancelFn` when it drops to 0. I guess that the test won't pass unless you do the same thing manually there but I think that's fine. I believe that we also want to disable this behavior as soon as we have a materializer in the flow, since it might still be draining some stuff through inboxes.
___
*[pkg/sql/logictest/logic.go, line 428 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvQ2_1pMYujXBPXei:-LlEvQ2_1pMYujXBPXej:bdvuq30) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/logictest/logic.go#L428)):*
> ```Go
> 	{name: "fakedist", numNodes: 3, useFakeSpanResolver: true, overrideDistSQLMode: "on", overrideOptimizerMode: "off"},
> 	{name: "fakedist-opt", numNodes: 3, useFakeSpanResolver: true, overrideDistSQLMode: "on", overrideOptimizerMode: "on", overrideAutoStats: "false"},
> 	// TODO(yuzefovich): enable fakedist-vec config.
> ```

Heads up that you've got these
___
*[pkg/sql/logictest/testdata/logic_test/overflow, line 3 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvRg_CGy1RL9NDl2r:-LlEvRgaEbGj1KUuH26-:bdvut09) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/logictest/testdata/logic_test/overflow#L3)):*
> ```
> # LogicTest: local-vec local-opt fakedist fakedist-opt fakedist-metadata
> 
> # TODO(yuzefovich): add fakedist-vec config.
> ```

Heads up that you've got this.


<!-- Sent from Reviewable.io -->

2019-08-02 03:16 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlFFiXf7Ysk7CFtwynT:bizur2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That's unexpected, right? Materializer flow context cancellation should close inbox streams which will cause outboxes to receive an EOF and cancel their flow context.
</blockquote></details>

The closure of inbox streams does not happen, probably because `streamCtx` is a separate from the flow context.

Another problem was that `cancelFlow` function was canceling a different context from the one `Inbox` when it was initialized (i.e. which it stored as `readerCtx`). I worked around it by using exactly the same "flow context" for the materializer as well as all inboxes on the local to materializer node. This way, inboxes wake up because `readerCtx` is canceled. But this still seems quite fragile as well.

I also added another commit that uses this `f.ctx` everywhere. Please let me know what you think. I have a feeling that at some point, someone already did this, but then there was a reason for why it is a bad decision, so `Flow.ctx` was removed.
___
*[pkg/sql/exec/colrpc/inbox.go, line 82 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEwBpzBSqAt9W4eAEy:-LlFGAuPB3CYfQJSlq1P:bu8urdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/exec/colrpc/inbox.go#L82)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's a pity to have so many state variables but at this time I don't know how to improve this (maybe having a single enum variable?). I think it's fine to merge it like this as long as the tests pass but hopefully we'll come up with a simpler way.
</blockquote></details>

Yeah, I don't like it either, but I agree that we can deal with it later.
___
*[pkg/sql/exec/colrpc/outbox.go, line 280 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvJ7o7RrOk7ncJiBD:-LlF60mA07eZtpuzJRcV:b-33ikzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/edeec4ee000722c64074b8010d8d254823f0a044/pkg/sql/exec/colrpc/outbox.go#L280)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: we sould probably leave this log message in.
</blockquote></details>

It wasn't here before this PR, and also there is a log message in `o.moveToDraining`, so it was kind of a redundant.
___
*[pkg/sql/exec/colrpc/outbox.go, line 48 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEuShM1jjKXvxD0Ac5:-LlF5oIIAnPUiLnJPsZX:b-iru65r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/exec/colrpc/outbox.go#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I feel like having an outbox registry is overkill. All we really need is a uint32 atomically incremented in the `vectorizedFlowCreator` right before we call the `startableFn` and then an atomic decrement after the outbox exits from `Run` with a `cancelFn` when it drops to 0. I guess that the test won't pass unless you do the same thing manually there but I think that's fine. I believe that we also want to disable this behavior as soon as we have a materializer in the flow, since it might still be draining some stuff through inboxes.
</blockquote></details>

Okay, I think you're right. Done.
___
*[pkg/sql/logictest/logic.go, line 428 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvQ2_1pMYujXBPXei:-LlF6AgHE3piqjHvnhFq:b-iw7tyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/logictest/logic.go#L428)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Heads up that you've got these
</blockquote></details>

Yeah, I wasn't sure what was causing the failures. I thought maybe a recent change in the way we run logic tests was causing many tests to run with this new config.

Restored (let's see what happens with the build).
___
*[pkg/sql/logictest/testdata/logic_test/overflow, line 3 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEvRg_CGy1RL9NDl2r:-LlFGT_97Exz_2Lhgyeg:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/logictest/testdata/logic_test/overflow#L3)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Heads up that you've got this.
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2019-08-02 04:48 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlFdhkfDl-KlXNGHyyB:b-y77qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The closure of inbox streams does not happen, probably because `streamCtx` is a separate from the flow context.

Another problem was that `cancelFlow` function was canceling a different context from the one `Inbox` when it was initialized (i.e. which it stored as `readerCtx`). I worked around it by using exactly the same "flow context" for the materializer as well as all inboxes on the local to materializer node. This way, inboxes wake up because `readerCtx` is canceled. But this still seems quite fragile as well.

I also added another commit that uses this `f.ctx` everywhere. Please let me know what you think. I have a feeling that at some point, someone already did this, but then there was a reason for why it is a bad decision, so `Flow.ctx` was removed.
</blockquote></details>

Ok, I refactored this part a little bit. Now we're using a different context that is passed into inboxes and other operators, and upon exit from materializer, we cancel both the flow context and this new context. This all seems so fragile :/


<!-- Sent from Reviewable.io -->

2019-08-02 13:24 UTC, asubiotto requested changes
> Reviewed 2 of 10 files at r13, 6 of 8 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1027 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHQipAEEak5shJhT-0:-LlHQipB4X9KNsc7sit9:b3b9kot) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/distsqlrun/column_exec_setup.go#L1027)):*
> ```Go
> 	}
> 	run := func(ctx context.Context, cancelFn context.CancelFunc) {
> 		atomic.AddInt32(&s.numOutboxes, 1)
> ```

I would maybe increment this above `run :=`
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1030 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHTwEX3E7VbMMUwkU7:-LlHTwEY-FvR4qhCpXyv:b245p6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/distsqlrun/column_exec_setup.go#L1030)):*
> ```Go
> 		outbox.Run(ctx, s.nodeDialer, stream.TargetNodeID, s.flowID, stream.StreamID, cancelFn)
> 		atomic.AddInt32(&s.numOutboxes, -1)
> 		if !s.materializerAdded && atomic.LoadInt32(&s.numOutboxes) == 0 && cancelFn != nil {
> ```

Maybe add a comment about what's going on here.
___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlHQrA812dU78c_6LkT:b-of6mnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Ok, I refactored this part a little bit. Now we're using a different context that is passed into inboxes and other operators, and upon exit from materializer, we cancel both the flow context and this new context. This all seems so fragile :/
</blockquote></details>

`streamCtx` should never be associated with the flow context, that's just the GRPC stream's context. If that gets cancelled, it just means that the remote outbox cancelled the context. The context that should be getting canceled is the `readerCtx`. I think the real issue here is that `cancelFlow` does not cancel the context used by the materializer in `Next` (i.e. the one passed in to `Start`). That should be part of the materializer contract if you're passing in a `cancelFlow` fn and I think it is respected during normal execution (i.e. flows `Run`ing a materializer use the context with the `cancelFn`). I think it's more likely that something is slightly wrong with the test. I'm not sure I see anything related to `f.ctx` but in general it's a bad idea to embed contexts because you get into situations similar to this, where you don't know which context is the right one to use. In this case I think it's pretty clear, we're probably not passing in the correct `cancelFlow` for the context used in `Start`.
___
*[pkg/sql/exec/colrpc/inbox.go, line 243 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHUN9h5SG50HFFmpbw:-LlHUN9h5SG50HFFmpbx:bfwllzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/exec/colrpc/inbox.go#L243)):*
> ```Go
> 	defer i.stateMu.nextExited.Signal()
> 	i.stateMu.nextRunning = true
> 	defer func() {
> ```

Instead of having three defers, it would probably be clearer to have a single one to make it clear which order these are executed in.


<!-- Sent from Reviewable.io -->

2019-08-02 14:38 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1027 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHQipAEEak5shJhT-0:-LlHjG8lEY2kMXmhP_Vb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/distsqlrun/column_exec_setup.go#L1027)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would maybe increment this above `run :=`
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1030 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHTwEX3E7VbMMUwkU7:-LlHkHXZ1w4KbvK982_n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/distsqlrun/column_exec_setup.go#L1030)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe add a comment about what's going on here.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/materializer.go, line 204 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlEmlN51gl3MMLGibNn:-LlHkIUg9w__lhonD-j5:b-5bhhpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4010388ed97181f3a5e1d26339d6fb81dca668f7/pkg/sql/distsqlrun/materializer.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`streamCtx` should never be associated with the flow context, that's just the GRPC stream's context. If that gets cancelled, it just means that the remote outbox cancelled the context. The context that should be getting canceled is the `readerCtx`. I think the real issue here is that `cancelFlow` does not cancel the context used by the materializer in `Next` (i.e. the one passed in to `Start`). That should be part of the materializer contract if you're passing in a `cancelFlow` fn and I think it is respected during normal execution (i.e. flows `Run`ing a materializer use the context with the `cancelFn`). I think it's more likely that something is slightly wrong with the test. I'm not sure I see anything related to `f.ctx` but in general it's a bad idea to embed contexts because you get into situations similar to this, where you don't know which context is the right one to use. In this case I think it's pretty clear, we're probably not passing in the correct `cancelFlow` for the context used in `Start`.
</blockquote></details>

I agree that, in some cases, context that is canceled by `cancelFlow` is unrelated to the one passed in into `materializer.Start`. Left a TODO to figure it out later.
___
*[pkg/sql/exec/colrpc/inbox.go, line 243 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-LlHUN9h5SG50HFFmpbw:-LlHhzzT0TIkALejdqN8:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b00c6cb145fb564eee2055a894482c9b676587c1/pkg/sql/exec/colrpc/inbox.go#L243)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of having three defers, it would probably be clearer to have a single one to make it clear which order these are executed in.
</blockquote></details>

I agree, done.


<!-- Sent from Reviewable.io -->

2019-08-02 14:42 UTC, asubiotto reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Thanks for your hard work on this

> Reviewed 1 of 8 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LlHlpH30LJjsXvJZGz0:b-5ap8h9)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-08-02 15:10 UTC, yuzefovich reviewed
Thanks for all the reviews and discussions! This PR has been definitely the hardest for me to land (15 revisions lol).

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39100#-:-LlHsJgzBsS7coQteW87:b-g2bp74)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2019-08-02 15:35 UTC, merged