sql: warn when creating non-partitioned index
cockroachdb/cockroach pull request #39154
Opened 2019-07-29 20:44 UTC by solongordon

In most cases, secondary indexes created on a partitioned table should
also be partitioned. To protect users from this gotcha, we now return an
error in this case if sql_safe_updates is on.

This isn't an ideal solution to the problem. It only really protects
users who are using the interactive CLI, and if a user really does want
an unpartitioned index it will force them to turn off sql_safe_updates,
at least temporarily. However, I didn't have much luck finding another
way to deliver a warning which users were likely to see.

Fixes #38475

Release note: None

2019-07-29 20:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39154)
<!-- Reviewable:end -->

2019-07-29 20:44 UTC, solongordon commented
Open to other ideas about how to deliver this warning if people have them!

2019-07-29 20:50 UTC, rohany requested changes
Is there a way to make a unit/logic test for this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-:-LkzUud81v5NLeF7sboj:b-asiglc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/create_index.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzTtUd-t93nvouNE3D:-LkzTtUd-t93nvouNE3E:but346o) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_index.go#L95)):*
> ```Go
> 	// which is undesirable in most cases.
> 	if params.SessionData().SafeUpdates && n.n.PartitionBy == nil &&
> 		n.tableDesc.PrimaryIndex.Partitioning.NumColumns > 0 {
> ```

do you need to check all indexes, not just the primary index?
___
*[pkg/sql/create_table.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzUnpr1eOFzHjUWabZ:-LkzUnpr1eOFzHjUWab_:b-sdop8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_table.go#L142)):*
> ```Go
> 	if params.SessionData().SafeUpdates && n.n.PartitionBy != nil {
> 		for _, def := range n.n.Defs {
> 			if d, ok := def.(*tree.IndexTableDef); ok {
> ```

I think you also want to check here if the primary key isn't partitioned, but a secondary index is partitioned.


<!-- Sent from Reviewable.io -->

2019-07-29 21:01 UTC, solongordon reviewed
Yup, added a few logic tests. (I was trying to slip them in before anyone reviewed but you were too fast.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-:-LkzXAoE8bzhigazo79G:b-nfqcna)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/create_index.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzTtUd-t93nvouNE3D:-LkzW4Lu0EqTPKPS4b0-:bosl96u) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_index.go#L95)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

do you need to check all indexes, not just the primary index?
</blockquote></details>

My understanding is that checking the primary index tells you whether the "table" is partitioned, so I think it's enough? I don't think we need to error if the user is adding an unpartitioned index to a table where the primary index isn't partitioned but some other index is.
___
*[pkg/sql/create_table.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzUnpr1eOFzHjUWabZ:-LkzWgVS4URjtk_qi5MS:b-i6eybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_table.go#L142)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think you also want to check here if the primary key isn't partitioned, but a secondary index is partitioned.
</blockquote></details>

Interesting, yeah that seems unlikely but I suppose it would be weird enough to warn about.


<!-- Sent from Reviewable.io -->

2019-07-29 21:07 UTC, rohany approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-:-LkzYmdSBZeL9FSG09gk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @solongordon)

___
*[pkg/sql/create_index.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzTtUd-t93nvouNE3D:-LkzYeSH0DEFeDwxbOWS:b-k8twrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_index.go#L95)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

My understanding is that checking the primary index tells you whether the "table" is partitioned, so I think it's enough? I don't think we need to error if the user is adding an unpartitioned index to a table where the primary index isn't partitioned but some other index is.
</blockquote></details>

yeah that makes sense 
___
*[pkg/sql/create_table.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39154#-LkzUnpr1eOFzHjUWabZ:-LkzYhZb92ltPipsIqAz:b-mvz73p) ([raw file](https://github.com/cockroachdb/cockroach/blob/20307564b1dc5216f5aa2a1024c03b677f773eef/pkg/sql/create_table.go#L142)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Interesting, yeah that seems unlikely but I suppose it would be weird enough to warn about.
</blockquote></details>

yup, since we are warning anyway, might as well.


<!-- Sent from Reviewable.io -->

2019-08-06 14:36 UTC, solongordon commented
bors r+

2019-08-06 15:00 UTC, merged