libroach: Allow KVs with the same ts and value to shadow in AddSSTable
cockroachdb/cockroach pull request #39201
Opened 2019-07-31 21:48 UTC by adityamaru27

This is a slight modification to the `disallowShadowing` option in
AddSSTable. It allows an ingested KV with the same ts
(walltime and logical), and same value as an existing KV to
overwrite that existing KV.

The motivation behind this is to support the behavior of an
IMPORT job on resume. A resumed IMPORT job must re-import KVs
not in the checkpointed set. Some of these KVs could have
already been ingested into the table (but not checkpointed), and
thus prior to this change the `disallowShadowing` logic would
see a collision and error out. Since the entirety of an IMPORT
(including reattempts) occurs at the same ts, we can let such
"collisions" silently slip by ensuring the ts and the value of the
KV is identical to what has already been ingested.

In order to keep the behavior uniform, duplicate KVs in the same
SST will also be skipped, instead of throwing a uniqueness error.
This logic will be added in the sorting phase of the IMPORT in
PR #39152, once this is merged.

Release note: None

2019-07-31 21:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39201)
<!-- Reviewable:end -->

2019-08-02 19:03 UTC, dt approved these changes

2019-08-02 22:32 UTC, nvb requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27)

___
*[c-deps/libroach/db.cc, line 590 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-LlJRi1mAbh560PFtZsJ:-LlJRi1mAbh560PFtZsK:b6oomvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2dd23968251b94c4ddeaad7b42a4b95f13ed93/c-deps/libroach/db.cc#L590)):*
> ```cpp
>     // If the ingested KV has an identical timestamp and value as the existing
>     // data then we do not consider it to be a collision.
>     bool has_equal_timestamp = existing_ts.wall_time == sst_ts.wall_time && existing_ts.logical == sst_ts.logical;
> ```

`existing_ts == sst_ts` doesn't work? Don't we overload the equality operator?
___
*[c-deps/libroach/db.cc, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-LlJS4P15a-JXX8q9Jka:-LlJS4P15a-JXX8q9Jkb:b-m7dcy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2dd23968251b94c4ddeaad7b42a4b95f13ed93/c-deps/libroach/db.cc#L592)):*
> ```cpp
>     bool has_equal_timestamp = existing_ts.wall_time == sst_ts.wall_time && existing_ts.logical == sst_ts.logical;
>     bool has_equal_value = kComparator.Compare(existingIter->rep->value(), sstIter->rep->value()) == 0;
>     if (has_equal_timestamp && has_equal_value) {
> ```

Shouldn't this be in the `compare == 0` block? What if two different keys are at the same timestamp and have the same value?
___
*[c-deps/libroach/db.cc, line 594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-LlJSG9TAOmrM5U65rYa:-LlJSG9TAOmrM5U65rYb:b-jm4ayl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2dd23968251b94c4ddeaad7b42a4b95f13ed93/c-deps/libroach/db.cc#L594)):*
> ```cpp
>     if (has_equal_timestamp && has_equal_value) {
>       state.valid = true;
>       return state;
> ```

Why are we returning after the first key/value/timestamp match? Don't we still want to check every key in the two iterators for a collision?


<!-- Sent from Reviewable.io -->

2019-08-03 01:41 UTC, adityamaru27 commented
Reviewable is being weird, I can't seem to publish that I have resolved the comments.

2019-08-05 18:16 UTC, nvb reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39201)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27 and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_add_sstable_test.go, line 738 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-LlXzYtqBnvcqlXhhv_k:-LlXzYtqBnvcqlXhhv_l:b8glfjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b80512492af570fd4f6f212f3d164972776a722d/pkg/storage/batcheval/cmd_add_sstable_test.go#L738)):*
> ```Go
> 
> 	// Test ingesting a key with different timestamp but same value. This should
> 	// trigger a collision error.
> ```

Do we have a test for the same timestamp but a different value?
___
*[pkg/storage/batcheval/cmd_add_sstable_test.go, line 772 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-LlXzADH9ZiydWkwLg0K:-LlXzADH9ZiydWkwLg0L:b-ksdm7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b80512492af570fd4f6f212f3d164972776a722d/pkg/storage/batcheval/cmd_add_sstable_test.go#L772)):*
> ```Go
> 			{"y", 5, "yyy"}, // key has the same timestamp and value as the one present in the existing data - not a collision.
> 			{"z", 3, "zzz"}, // shadow key
> ```

stray line


<!-- Sent from Reviewable.io -->

2019-08-05 23:34 UTC, nvb approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39201#-:-LlZ7fa80zzNc-85gp7a:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-08-06 02:19 UTC, adityamaru27 commented
TFTR!
bors r+

2019-08-06 02:45 UTC, merged