distsql: return cancellable context from flow setup
cockroachdb/cockroach pull request #39331
Opened 2019-08-05 18:03 UTC by asubiotto

Flow.setup would derive a cancellable context from the parent context
passed in and store the cancellation function to be passed in to
outboxes/a materializer. However, callers would use the parent context
to run the flow, rendering cancellation ineffective. This commit returns
the cancellable context from Flow.setup and expects that context to be
used to run the flow.

Release note: None

Fixes #39299

2019-08-05 18:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39331)
<!-- Reviewable:end -->

2019-08-05 18:26 UTC, yuzefovich requested changes
Thanks for figuring this out! I remember I had concerns about moving the context derivation from `Start` but brushed them off. I think I agree with Jordan that option 2) you mentioned in Slack is the way to go because option 1) seems more fragile to me. I don't think it'll be too much work to go that way, right?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39331#-:-LlY-PNV6tRCG3SVS0Gm:b-5ewfsm)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-08-05 19:49 UTC, asubiotto commented
Yeah, I agree, this also allowed me to remove `ctxCancel`. I ran into a (hard to reproduce) stress failure in `TestVectorizedFlowShutdown` where not all the metadata is drained in the consumer done case because a context cancellation closes an inbox stream. I'm unsure whether this is because of my branch or not, I've been running a 5 minute stress and haven't run into it again. Will stress master on the gceworker.

2019-08-05 20:33 UTC, asubiotto commented
Very hard to tell. I've run stress with half an hour without a reproduction. I'm willing to bet that there's an edge case on master, I think we should merge this independently.

2019-08-05 23:30 UTC, yuzefovich approved these changes
Thanks! Hm, the build is broken, but the change <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39331#-:-LlZ6SkJ82mIzC-U_4r0:b-wtskra)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsqlrun/flow.go, line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39331#-LlZ5yGP1FVpjUNRx475:-LlZ5yGP1FVpjUNRx476:bk3i6i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85d8a86c0e4aa407bc0ed6c1dea040abb05d948/pkg/sql/distsqlrun/flow.go#L454)):*
> ```Go
> }
> 
> // setup sets up a flow according to spec. A cancellable context is derived from
> ```

[nit]: now this comment needs an adjustment.


<!-- Sent from Reviewable.io -->

2019-08-06 15:51 UTC, asubiotto commented
Looks like a logictest timeout due to cancellation. Investigating

2019-08-06 18:11 UTC, asubiotto commented
Hmm, it's out good old friend `EXISTS`. I'm not sure whether I should figure it out or code defensively and keep `ctxCancel` in the materializer.

2019-08-06 18:27 UTC, asubiotto reviewed
Keeping `ctxCancel` in this PR as a safeguard. Will create an issue to investigate the subquery.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39331#-:-LlcAfZz7jmzEcHhfZ3p:bl5r3ai)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/distsqlrun/flow.go, line 454 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39331#-LlZ5yGP1FVpjUNRx475:-LlcAN3y7cvtlAiwf9wJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d85d8a86c0e4aa407bc0ed6c1dea040abb05d948/pkg/sql/distsqlrun/flow.go#L454)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: now this comment needs an adjustment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-06 19:36 UTC, asubiotto commented
bors r=yuzefovich

2019-08-06 20:07 UTC, merged