sql/sem/tree: fix DatumTypeSize for ints and floats
cockroachdb/cockroach pull request #39337
Opened 2019-08-05 20:59 UTC by rafiss

Previously, these types would always report a size of 8 bytes. Now, we
use the internal Width, which will be correct for the various types
of ints and floats, i.e., int2, int4, int8, float4, and float8.

Release note: None

2019-08-05 20:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39337)
<!-- Reviewable:end -->

2019-08-05 21:05 UTC, rohany requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 3596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39337#-LlYaNZJ9xj4FVpZ2E2d:-LlYaNZJ9xj4FVpZ2E2e:b1d0b84) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb34a413c2f8f0004cab6cb6abf36e3231828e/pkg/sql/sem/tree/datum.go#L3596)):*
> ```Go
> 		return sz, variable
> 	case types.IntFamily, types.FloatFamily:
> 		return uintptr(t.Width()), false
> ```

should this be width() / 8? I think the widths are in terms of bits.


<!-- Sent from Reviewable.io -->

2019-08-05 21:05 UTC, jordanlewis reviewed
I believe some logic tests will fail here and need updating.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39337#-:-LlYaVql5A-RNz30DHpY:b2b2bku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 3596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39337#-LlYaH13EHAYQKo_TXNF:-LlYaH13EHAYQKo_TXNG:byq4w42) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb34a413c2f8f0004cab6cb6abf36e3231828e/pkg/sql/sem/tree/datum.go#L3596)):*
> ```Go
> 		return sz, variable
> 	case types.IntFamily, types.FloatFamily:
> 		return uintptr(t.Width()), false
> ```

I think this probably needs to be divided by 8, since this is supposed to be a size in bytes, but I believe Width() returns a size in bits.


<!-- Sent from Reviewable.io -->

2019-08-08 15:26 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39337)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 3596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39337#-LlYaH13EHAYQKo_TXNF:-LllpX5U0WFXexHF2Mkl:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecdb34a413c2f8f0004cab6cb6abf36e3231828e/pkg/sql/sem/tree/datum.go#L3596)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this probably needs to be divided by 8, since this is supposed to be a size in bytes, but I believe Width() returns a size in bits.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-08-08 21:23 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> mod last test failure

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39337#-:-Lln6IBR64MnL3cQO29n:bk2xiu1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)



<!-- Sent from Reviewable.io -->

2019-08-12 16:55 UTC, rafiss commented
bors r+

2019-08-12 18:04 UTC, merged