sql: record total transaction time
cockroachdb/cockroach pull request #39429
Opened 2019-08-07 22:27 UTC by yuzefovich

This commit adds the collection of a few things about the transactions
(namely, total transaction time, whether it was committed, and whether
it was implicit). This information is stored in an internal table.

Fixes: #39056.

Release note: None

2019-08-07 22:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39429)
<!-- Reviewable:end -->

2019-08-07 22:29 UTC, yuzefovich commented
This doesn't work as is. I thought if I did these recordings right before `eventTxnStart` and `eventTxnFinish` were issued, I'd catch all the cases. Apparently, it is more tricky than this. I would appreciate some pointers.

2019-08-08 20:21 UTC, mjibson commented on pkg/sql/conn_executor_exec.go
> +	ex.planner.statsCollector.PhaseTimes()[transactionEnd] = timeutil.Now()
save the result of `.PhaseTimes()` in a var if it's used multiple times

2019-08-08 20:21 UTC, mjibson commented on pkg/sql/crdb_internal.go
> +var crdbInternalTxnStatsTable = virtualSchemaTable{
How long are these stats kept for? Looks unbounded.

2019-08-12 20:44 UTC, yuzefovich reviewed
This now works, so it is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-Lm6Ys-C4uxxqsovzHwq:b-paj1k7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @jordanlewis, and @mjibson)

___
*[pkg/sql/app_stats.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT0-r1-51:-Lm5rNJ2EC6WFyW18W6r:b2wongs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/app_stats.go#L51)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

does this need to be a pointer?
</blockquote></details>

Probably not. I refactored this code a bit.
___
*[pkg/sql/app_stats.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT0-r1-221:-Lm5qw-N34cbYTLv0yv8:btd51a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/app_stats.go#L221)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Panic'ing is definitely the correct thing here, since it should never happen and indicates something went very wrong.
</blockquote></details>

I agree.
___
*[pkg/sql/app_stats.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT0-r1-225:-Lm5qelz-fJqvgOx_2wy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/app_stats.go#L225)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

```
a.txns[txnID] = &txnStats{
TotalTime: totalTime,
...
}
```

</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 1305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT1-r1-1305:-Lm5qz3l4nQqJRAhxqcv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/conn_executor_exec.go#L1305)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

save the result of `.PhaseTimes()` in a var if it's used multiple times
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor_exec.go, line 1280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lm6ZCXy9v2-yWnIzaec:-Lm6ZCXy9v2-yWnIzaed:b-x67ntr) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1280)):*
> ```Go
> }
> 
> func (ex *connExecutor) recordTransactionStart() {
> ```

One question that Nathan brought up is who should be responsible for populating transaction statistics. Maybe the receiver of these two new methods should be `txnState`? And maybe `sqlStatsCollector` shouldn't be the one collecting stats about transactions? Thoughts?
___
*[pkg/sql/crdb_internal.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT2-r1-699:-Lm5rD8R18fL0wSRdcrA:b-mouldn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/crdb_internal.go#L699)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

How long are these stats kept for? Looks unbounded.
</blockquote></details>

I think it is unbounded right now, and I'm not sure whether we want to have a TTL for these. I followed the example of statement statistics.


<!-- Sent from Reviewable.io -->

2019-08-13 06:08 UTC, madelynnblue reviewed
The sql state machine stuff LGTM. I'm not familiar with the transaction stuff though, so I would recommend making sure someone else with experience there gives a review too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-Lm8_a9o6t9iedQh_jHy:big0cob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lm6ZCXy9v2-yWnIzaec:-Lm8Z-jw2D5yb_ldAhkU:b-2mh5op) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1280)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

One question that Nathan brought up is who should be responsible for populating transaction statistics. Maybe the receiver of these two new methods should be `txnState`? And maybe `sqlStatsCollector` shouldn't be the one collecting stats about transactions? Thoughts?
</blockquote></details>

I don't know much about transactions or stats, so I don't have an informed opinion about this. Whichever feels good is probably ok.


<!-- Sent from Reviewable.io -->

2019-08-13 13:08 UTC, ajwerner reviewed
Do you want to add a test that runs a transaction and something sane ends up in the virtual table?

I'm a bit concerned about the lack of logic to clear the data.

Also might want @andreimatei to have a look at the state machine stuff. 

> Reviewed 5 of 10 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LmA4_4T44wn22WX_ogs:b-6qutpc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @mjibson, and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmA17VA1HROUwILsa9p:-LmA17VBExzB7oVBbU2h:b-n9c7s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1012)):*
> ```Go
> 			rwMode = tree.ReadOnly
> 		}
> 		// TODO(yuzefovich): do we want to record the fact that we are restarting
> ```

This is a good question. I feel like preserving the previous start time might make more sense here. 
___
*[pkg/sql/crdb_internal.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT2-r1-699:-LmA2v8t0wp10242KQrA:bstz0k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/crdb_internal.go#L699)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think it is unbounded right now, and I'm not sure whether we want to have a TTL for these. I followed the example of statement statistics.
</blockquote></details>

I thought statement statistics are updated every `diagnostics.reporting.interval`. 

https://github.com/cockroachdb/cockroach/blob/f11604f0278d47629c2e82406d201f50283ee848/pkg/server/updates.go#L285
___
*[pkg/sql/crdb_internal.go, line 698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmA2cLYB-EdZnapAeGb:-LmA2cLYB-EdZnapAeGc:b-3jlru6) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/crdb_internal.go#L698)):*
> ```Go
> }
> 
> // TODO(tbg): prefix with node_.
> ```

It seems like this is prefixed with `node_`


<!-- Sent from Reviewable.io -->

2019-08-15 14:22 UTC, yuzefovich reviewed
Thanks for the suggestions! I added a sanity-check logic test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LmKdvJwESpds4bioemy:b-xqb2b5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmA17VA1HROUwILsa9p:-LmKXduK5XAp-fSkRcoY:brkno94) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1012)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is a good question. I feel like preserving the previous start time might make more sense here. 
</blockquote></details>

I agree, done.
___
*[pkg/sql/crdb_internal.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LliBOuCqeAJBgFhJxT2-r1-699:-LmKYJuMDNumDF1Za7k-:bwbhfs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f8f9c96a7ed6605484c8c8bee3a5e46b6dac733/pkg/sql/crdb_internal.go#L699)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I thought statement statistics are updated every `diagnostics.reporting.interval`. 

https://github.com/cockroachdb/cockroach/blob/f11604f0278d47629c2e82406d201f50283ee848/pkg/server/updates.go#L285
</blockquote></details>

Andrew is correct. The statistics are cleared either when diagnostics are reported (every hour by default) or, if that for some reason fails, after `diagnostics.forced_stat_reset.interval`(two hours by default).
___
*[pkg/sql/crdb_internal.go, line 698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmA2cLYB-EdZnapAeGb:-LmKYEel61DZNGpKzLKG:b-9vhyeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/crdb_internal.go#L698)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It seems like this is prefixed with `node_`
</blockquote></details>

Indeed, fixed.


<!-- Sent from Reviewable.io -->

2019-08-17 13:45 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LmUodzTBpJAMeHaq6WW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @mjibson, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-08-17 15:55 UTC, andreimatei commented
I'll look at this on Monday. Sorry for the delay

On Sat, Aug 17, 2019, 9:45 AM ajwerner <notifications@github.com> wrote:

> *@ajwerner* approved this pull request.
>
> [image: :lgtm:]
> <https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67>
>
> Reviewed 8 of 8 files at r3.
> *Reviewable
> <https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LmUodzTBpJAMeHaq6WW:bnfp4nl>*
> status: [image: :shipit:] complete! 1 of 0 LGTMs obtained (waiting on
> @andreimatei <https://github.com/andreimatei>, @jordanlewis
> <https://github.com/jordanlewis>, @mjibson <https://github.com/mjibson>,
> and @yuzefovich <https://github.com/yuzefovich>)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/39429?email_source=notifications&email_token=AAC4C4MGK6N2GJUAKQJZXDTQE76JHA5CNFSM4IKEYHG2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCB3Q3DA#pullrequestreview-276237708>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAC4C4L3ZQHELV643FCRDTLQE76JHANCNFSM4IKEYHGQ>
> .
>

2019-08-19 18:00 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @mjibson)

___
*[pkg/sql/conn_executor_exec.go, line 1280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lm6ZCXy9v2-yWnIzaec:-Lmf1-gL2Xt2yoqNKucv:bqtuis) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1280)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I don't know much about transactions or stats, so I don't have an informed opinion about this. Whichever feels good is probably ok.
</blockquote></details>

@andreimatei I'm curious about your opinion on this.


<!-- Sent from Reviewable.io -->

2019-08-19 19:49 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/conn_executor_exec.go, line 1280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lm6ZCXy9v2-yWnIzaec:-LmfLwQ66bTOfJPe6qky:b-ppfqfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1280)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@andreimatei I'm curious about your opinion on this.
</blockquote></details>

For the particular case of transaction start, I don't understand what the dance between the `connExecutor` and the `txnState` gives you. Starting a transaction is ~ a noop (it's just state management crap). Just have the executor record whatever it needs and leave the `txnState` out.
Not so for transaction ending. There, in case the txn wasn't "auto-committed", it's the `txnState` that actually performs the commit and obviously we want to count that time (if you ask @nvanbenschoten, that's the only time a txn takes :P).

Generally speaking, I think we'd be well advised to intermingle the `connExecutor` and the txn state machine as little as possible. And I think that the state machine should also stay as simple as possible, so we should try to keep the collection of statistics out of it.
I don't much like the callbacks you're passing around. Have you tried using the `txnEvents` (part of the information returned by the state machine to the connEx) and have them drive the `connEx` to update the txn finish statistics? That's why they were introduced - to let the `connEx` do things on transaction start/finish that don't quite belong in the state machine.
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/sql/txn_state.go#L356
___
*[pkg/sql/conn_fsm.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfHyBv1GeQjySrgBWO:-LmfHyBv1GeQjySrgBWP:b2p3aej) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb7e61ea8cadbab5cacee1508bbc5927cb8c20d0/pkg/sql/conn_fsm.go#L168)):*
> ```Go
> 
> func makeEventTxnFinishPayload(
> 	commit bool, recordTransactionStatistics func(commit bool),
> ```

pls no `bool` args in such prominent APIs. Make it an enum.
https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#try-to-avoid-bool-parameters


<!-- Sent from Reviewable.io -->

2019-08-19 20:57 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_exec.go, line 1280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lm6ZCXy9v2-yWnIzaec:-LmfeHUW4XjBKwMuGVLw:b-h08599) ([raw file](https://github.com/cockroachdb/cockroach/blob/220f534e7d36e1403dc43f186e5e195017cd6df8/pkg/sql/conn_executor_exec.go#L1280)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

For the particular case of transaction start, I don't understand what the dance between the `connExecutor` and the `txnState` gives you. Starting a transaction is ~ a noop (it's just state management crap). Just have the executor record whatever it needs and leave the `txnState` out.
Not so for transaction ending. There, in case the txn wasn't "auto-committed", it's the `txnState` that actually performs the commit and obviously we want to count that time (if you ask @nvanbenschoten, that's the only time a txn takes :P).

Generally speaking, I think we'd be well advised to intermingle the `connExecutor` and the txn state machine as little as possible. And I think that the state machine should also stay as simple as possible, so we should try to keep the collection of statistics out of it.
I don't much like the callbacks you're passing around. Have you tried using the `txnEvents` (part of the information returned by the state machine to the connEx) and have them drive the `connEx` to update the txn finish statistics? That's why they were introduced - to let the `connEx` do things on transaction start/finish that don't quite belong in the state machine.
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/sql/txn_state.go#L356

</blockquote></details>

I refactored the code to use `txnEvent`s, and I think that I finally like the code. Please let me know what you think.
___
*[pkg/sql/conn_fsm.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfHyBv1GeQjySrgBWO:-Lmfe0io13F9eqyo-S_q:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb7e61ea8cadbab5cacee1508bbc5927cb8c20d0/pkg/sql/conn_fsm.go#L168)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls no `bool` args in such prominent APIs. Make it an enum.
https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#try-to-avoid-bool-parameters
</blockquote></details>

Refactored.


<!-- Sent from Reviewable.io -->

2019-08-19 21:58 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, @mjibson, @nvanbenschoten, and @yuzefovich)

___
*[pkg/roachpb/app_stats.proto, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsP5w-4AuAJg3L51j:-LmfsP5w-4AuAJg3L51k:b-gnclqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L141)):*
> ```protobuf
> }
> 
> message TransactionStatistics {
> ```

nit: these are not really "statistics". More like `TxnInfo`.
___
*[pkg/roachpb/app_stats.proto, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsGOR1BqgfUTWdc0L:-LmfsGOR1BqgfUTWdc0M:bp62lsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L142)):*
> ```protobuf
> 
> message TransactionStatistics {
>   optional double total_time = 1 [(gogoproto.nullable) = false];
> ```

pls include the unit in the field name
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfrlM_2n7QggZkmmzm:-LmfrlM_2n7QggZkmmzn:b-iis1cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
> ```Go
> 	syncutil.Mutex
> 	stmts map[stmtKey]*stmtStats
> 	txns  map[string]roachpb.TransactionStatistics
> ```

why not UUID as the map key?

At the very least, pls comment what the key is.
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfs2AN3Y7zcWte7BQ0:-Lmfs2AN3Y7zcWte7BQ1:b83iokm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
> ```Go
> 	syncutil.Mutex
> 	stmts map[stmtKey]*stmtStats
> 	txns  map[string]roachpb.TransactionStatistics
> ```

Are we going to keep... all the txns around? For an hour?
Isn't that... bad? Shouldn't we be computing some statistics (store the distribution of execution times)?
___
*[pkg/sql/app_stats.go, line 255 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfsna20ZlhKbXg-6-d:-Lmfsna20ZlhKbXg-6-e:b-ppxdnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L255)):*
> ```Go
> 		return a
> 	}
> 	a := &appStats{st: s.st, stmts: make(map[stmtKey]*stmtStats), txns: make(map[string]roachpb.TransactionStatistics)}
> ```

long line son
___
*[pkg/sql/crdb_internal.go, line 698 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfrGAlCPSCl1kGzY-a:-LmfrGAlCPSCl1kGzY-b:b-e52cor) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/crdb_internal.go#L698)):*
> ```Go
> 
> var crdbInternalTxnStatsTable = virtualSchemaTable{
> 	comment: `transaction statistics (RAM; local node only)`,
> ```

I don't know what the RAM part means
___
*[pkg/sql/crdb_internal.go, line 704 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfr8_qER6SsqRIAMeN:-Lmfr8_rEWEAsCOxbNt8:bk27fzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/crdb_internal.go#L704)):*
> ```Go
>   application_name    STRING NOT NULL,
>   txn_id              STRING NOT NULL,
>   total_time          FLOAT NOT NULL,
> ```

pls put the unit in the name


<!-- Sent from Reviewable.io -->

2019-08-19 23:11 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)

___
*[pkg/roachpb/app_stats.proto, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsP5w-4AuAJg3L51j:-LmfzVpPCc-enDRslU-t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L141)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: these are not really "statistics". More like `TxnInfo`.
</blockquote></details>

Done.
___
*[pkg/roachpb/app_stats.proto, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsGOR1BqgfUTWdc0L:-LmfzWZ665c84VHdvZBW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L142)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls include the unit in the field name
</blockquote></details>

Done.
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfrlM_2n7QggZkmmzm:-Lmg02wo66B_-iJwPiSH:bdmbex0) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why not UUID as the map key?

At the very least, pls comment what the key is.
</blockquote></details>

It was a remnant of the past. Refactored.
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfs2AN3Y7zcWte7BQ0:-Lmg06oF2akXSBMjD5U6:b-fe4jgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Are we going to keep... all the txns around? For an hour?
Isn't that... bad? Shouldn't we be computing some statistics (store the distribution of execution times)?


</blockquote></details>

We do collect even more information about statements, so I thought it was ok to do the same for transactions.

However, I didn't quite understand how to display that information. I've just added two dashboards for 90th and 99th percentiles of total transaction times and disabled collection of per-transaction information by default. Although we're not using that internal table at the moment, I think we should still keep it since in the future we intend to add "transactions" page to the UI, and the internal table will probably be useful then.
___
*[pkg/sql/app_stats.go, line 255 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfsna20ZlhKbXg-6-d:-Lmg0wWQ0ApLqI9BGgYB:busawlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L255)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line son
</blockquote></details>

Fixed :)
___
*[pkg/sql/crdb_internal.go, line 698 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfrGAlCPSCl1kGzY-a:-Lmg1ow499cXXPRYMjDR:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/crdb_internal.go#L698)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't know what the RAM part means
</blockquote></details>

Updated.
___
*[pkg/sql/crdb_internal.go, line 704 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfr8_qER6SsqRIAMeN:-Lmg1py2557RcUpsOVeW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/crdb_internal.go#L704)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls put the unit in the name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-20 15:35 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, @nvanbenschoten, and @yuzefovich)

___
*[pkg/roachpb/app_stats.proto, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsGOR1BqgfUTWdc0L:-Lmjcj5l2CNBwpU0QA3N:b-x6mhwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L142)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: `total_time_sec`
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfs2AN3Y7zcWte7BQ0:-LmjdCg1-h4rqdmqLwOW:b-rh6jzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
> We do collect even more information about statements, so I thought it was ok to do the same for transactions.

I'm not saying you're lying, but I don't believe you. I believe we collect *statistics* per statement fingerprint - not per statement. Huge difference. For example, these fingerprints ignore constants and placeholder values.
No?

And I think that's the right mindset. Extract txn fingerprints through some clustering algorithm (or screw it and just have one bucket per application name).
Storing any per-txn or per-stmt doesn't seem like it can work to me. A node is supposed to do up to tens of thousands of these per second.


<!-- Sent from Reviewable.io -->

2019-08-20 20:37 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)

___
*[pkg/roachpb/app_stats.proto, line 142 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmfsGOR1BqgfUTWdc0L:-Lmk0HL-ESkj_JEgGsRz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/roachpb/app_stats.proto#L142)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: `total_time_sec`
</blockquote></details>

Done.
___
*[pkg/sql/app_stats.go, line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmfs2AN3Y7zcWte7BQ0:-Lmkgui67bvAuGaP9okl:bnkugcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed2ea89b06d62d32887e13823e9e4e9705d839f/pkg/sql/app_stats.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> We do collect even more information about statements, so I thought it was ok to do the same for transactions.

I'm not saying you're lying, but I don't believe you. I believe we collect *statistics* per statement fingerprint - not per statement. Huge difference. For example, these fingerprints ignore constants and placeholder values.
No?

And I think that's the right mindset. Extract txn fingerprints through some clustering algorithm (or screw it and just have one bucket per application name).
Storing any per-txn or per-stmt doesn't seem like it can work to me. A node is supposed to do up to tens of thousands of these per second.

</blockquote></details>

Yes, you're right, I missed that crucial point, thanks for pointing it out. I've refactored the code to use a single bucket per application name, I think this should be good for now, and I turned the collection of these transactions stats back "on" by default.

Extracting transaction fingerprints is on the roadmap (not for 19.2 though), and it seems like it would be quite time-consuming, so I'd rather not do it now.
___
*[pkg/sql/conn_executor_exec.go, line 1010 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmkizvr132xa3W6k-hC:-Lmkizvr132xa3W6k-hD:b-i00e80) ([raw file](https://github.com/cockroachdb/cockroach/blob/9da3944445a72aedf803a3a4ed6642a8e224b37c/pkg/sql/conn_executor_exec.go#L1010)):*
> ```Go
> 			rwMode = tree.ReadOnly
> 		}
> 		// TODO(yuzefovich): as far as I understand, `txnStart` txnEvent will not
> ```

@andreimatei, is this assumption correct?


<!-- Sent from Reviewable.io -->

2019-08-20 20:38 UTC, yuzefovich commented
Adding @vilterp as a reviewer to take a look at the UI changes.

2019-08-20 21:27 UTC, vilterp approved these changes
Could you add a screenshot of the new TS dashboards? Makes it easier for everyone looking at this PR to see what's being added without having to pull it down and run it.

Looks good though.

2019-08-20 22:13 UTC, yuzefovich commented
Oh yeah, sorry, I was meaning to do that but forgot.
<img width="1003" alt="Screen Shot 2019-08-20 at 3 12 11 PM" src="https://user-images.githubusercontent.com/5135385/63388353-04b73080-c35d-11e9-8c4f-719acbd5872d.png">

2019-08-21 15:27 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/app_stats.go, line 63 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmoeSJz7f2FDnV4QsXt:-LmoeSJz7f2FDnV4QsXu:b-nqr52w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/app_stats.go#L63)):*
> ```Go
> // transactionStats hold per-application transaction statistics.
> type transactionStats struct {
> 	syncutil.Mutex
> ```

nit: as soon as you put a mutex in a struct, I think it's better to follow the usual pattern of making an anonymous struct `mu` that embeds the mutex, and then adding methods to modify the protected fields instead of accessing them directly from outside the struct.
Unless there's a lot of similar structs around that have sneaked in :)
___
*[pkg/sql/conn_executor.go, line 941 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmofrJ49f5pE9m-MiF1:-LmofrJ49f5pE9m-MiF2:b-jod418) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor.go#L941)):*
> ```Go
> 	draining bool
> 
> 	// txnInfo contains information about the current (or last) transaction. It
> ```

I think this belongs in `extraTxnState`.
And I'd suggest replacing it with a closure returned by `ex.recordTransactionStart()`  which closure would bind the information about whether the txn is implicit or not.
And then `resetExtraTxnState()` would call that closure - and you'd plumb the commit/abort status to it.
___
*[pkg/sql/conn_executor_exec.go, line 1010 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmkizvr132xa3W6k-hC:-LmoiTSY2fdF03ne1MxU:b-8y42pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9da3944445a72aedf803a3a4ed6642a8e224b37c/pkg/sql/conn_executor_exec.go#L1010)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@andreimatei, is this assumption correct?
</blockquote></details>

I think that's right. The relevant code is here - notice the "no event"
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/sql/conn_fsm.go#L447

Please take the opportunity to document this on the `txnStart` event.
___
*[pkg/sql/conn_executor_exec.go, line 1292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmojpmF1eW2oE-DfiCq:-LmojpmF1eW2oE-DfiCr:blo5f5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor_exec.go#L1292)):*
> ```Go
> 	totalTransactionTime := transactionEnd.Sub(transactionStart)
> 	ex.metrics.EngineMetrics.SQLTxnLatency.RecordValue(totalTransactionTime.Nanoseconds())
> 	ex.planner.statsCollector.RecordTransaction(
> ```

I think calling a transaction-related method through (something hanging from) the planner is where a line needs to be drawn. The planner should have nothing to do with transaction scopes. We should strive for a stateless planner; this is moving in the wrong direction. We should also strive for a planner used exclusively for... planning.

The stats collector already has things in it that the planner should have nothing to do with - `phaseTimes` related to session events.

I know you haven't created the mess (hopefully neither have I :) ), but I'm gonna kindly ask you to try to move the statsCollector away from the planner. Let it hang from the executor directly. I've looked superficially and it looks to me like it's mostly the executor using the stats collector, so hopefully it isn't hard. It's also used by an internal table - it would be more appropriate for that guy to access it (or a narrower interface implemented by it) though the `ExtendedEvalContext`.
And then maybe the interface describing the `statsCollector` could go away. In fact, I'm already unsure why that interface exists.

Makes sense?
___
*[pkg/sql/crdb_internal.go, line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmom6Z14bphepb_ztmo:-Lmom6Z14bphepb_ztmp:b1kaq8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/crdb_internal.go#L686)):*
> ```Go
> 
> var crdbInternalTxnStatsTable = virtualSchemaTable{
> 	comment: `per-application transaction statistics (in-memory, not durable; local node only)`,
> ```

maybe make it more clear that this table is wiped periodically
___
*[pkg/sql/crdb_internal.go, line 692 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmomHXRAxE_VJwDW6fQ:-LmomHXS4nqUyMJpt9bn:bi1cbis) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/crdb_internal.go#L692)):*
> ```Go
>   application_name   STRING NOT NULL,
>   txn_count          INT NOT NULL,
>   agg_total_time_sec FLOAT NOT NULL,
> ```

I think the average time would be more useful. What possible use could one have for the "total time" other then to compute the average?
___
*[pkg/sql/planner.go, line 623 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmojaSM5AUy-OTefY1G:-LmojaSM5AUy-OTefY1H:bzdeddr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/planner.go#L623)):*
> ```Go
> 
> 	// RecordTransaction records information about a transaction.
> 	RecordTransaction(totalTimeSec float64, committed bool, implicit bool)
> ```

particularly for a method on an interface, please no bool args


<!-- Sent from Reviewable.io -->

2019-08-21 23:03 UTC, yuzefovich reviewed
I've just pushed a second commit addressing Andrei's comments to see whether teamcity will complain, and I will squash the two commits before merging.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LmqPZDs0fGD3kQZRF7s:bjussos)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)

___
*[pkg/sql/app_stats.go, line 63 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmoeSJz7f2FDnV4QsXt:-LmqJstQBwNK1jkIix58:bw47ngs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/app_stats.go#L63)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: as soon as you put a mutex in a struct, I think it's better to follow the usual pattern of making an anonymous struct `mu` that embeds the mutex, and then adding methods to modify the protected fields instead of accessing them directly from outside the struct.
Unless there's a lot of similar structs around that have sneaked in :)
</blockquote></details>

I've been following the pattern of `stmtStats`, so yeah, there are a few similar structs, but I refactored the code as you're suggesting to not introduce yet another one :)
___
*[pkg/sql/conn_executor.go, line 941 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmofrJ49f5pE9m-MiF1:-LmqOx8W6dw_lTwFwuwP:betxz8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor.go#L941)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this belongs in `extraTxnState`.
And I'd suggest replacing it with a closure returned by `ex.recordTransactionStart()`  which closure would bind the information about whether the txn is implicit or not.
And then `resetExtraTxnState()` would call that closure - and you'd plumb the commit/abort status to it.

</blockquote></details>

Done. I don't understand though why would we be using a closure here instead of a simple boolean within `extraTxnState`?
___
*[pkg/sql/conn_executor.go, line 751 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmqPrTO3czaINf9Pp5r:-LmqPrTO3czaINf9Pp5s:b-t4ryj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56e86a86f72d9762736b8ee4ccc4d31816232b1/pkg/sql/conn_executor.go#L751)):*
> ```Go
> 	}
> 
> 	// TODO(yuzefovich): I'm not sure about which kind of txnEvent to pass in.
> ```

I think `noEvent` here is the right choice, but I'm not sure.
___
*[pkg/sql/conn_executor_exec.go, line 1010 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmkizvr132xa3W6k-hC:-Lmq0ZcGBnjgDjjetNmR:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9da3944445a72aedf803a3a4ed6642a8e224b37c/pkg/sql/conn_executor_exec.go#L1010)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think that's right. The relevant code is here - notice the "no event"
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/sql/conn_fsm.go#L447

Please take the opportunity to document this on the `txnStart` event.
</blockquote></details>

Thanks, done.
___
*[pkg/sql/conn_executor_exec.go, line 1292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmojpmF1eW2oE-DfiCq:-LmqGVgeB2_9SdZzYUr9:b-83b474) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor_exec.go#L1292)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think calling a transaction-related method through (something hanging from) the planner is where a line needs to be drawn. The planner should have nothing to do with transaction scopes. We should strive for a stateless planner; this is moving in the wrong direction. We should also strive for a planner used exclusively for... planning.

The stats collector already has things in it that the planner should have nothing to do with - `phaseTimes` related to session events.

I know you haven't created the mess (hopefully neither have I :) ), but I'm gonna kindly ask you to try to move the statsCollector away from the planner. Let it hang from the executor directly. I've looked superficially and it looks to me like it's mostly the executor using the stats collector, so hopefully it isn't hard. It's also used by an internal table - it would be more appropriate for that guy to access it (or a narrower interface implemented by it) though the `ExtendedEvalContext`.
And then maybe the interface describing the `statsCollector` could go away. In fact, I'm already unsure why that interface exists.

Makes sense?
</blockquote></details>

Yeah, I share your feeling on this one. I refactored the code by moving the stats collector into the executor and adding a pointer to it into the extended eval context. I don't like the latter part too much, but I don't see an easy way around it since that `populate` function doesn't have a lot of flexibility and is specified dozens of times. I think it is now better than it used to be (?).
___
*[pkg/sql/crdb_internal.go, line 686 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmom6Z14bphepb_ztmo:-LmqFyXD5-6D_clgMUUS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/crdb_internal.go#L686)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe make it more clear that this table is wiped periodically
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 692 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmomHXRAxE_VJwDW6fQ:-LmqGLS69wf5Uv4VE37_:b4px8kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/crdb_internal.go#L692)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the average time would be more useful. What possible use could one have for the "total time" other then to compute the average?
</blockquote></details>

Indeed (I was also thinking about this but forgot to change it).
___
*[pkg/sql/planner.go, line 623 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmojaSM5AUy-OTefY1G:-LmqOngBAqFe0scga2Do:bfelba4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/planner.go#L623)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

particularly for a method on an interface, please no bool args
</blockquote></details>

It is not a method of an interface, and I refactored the new code to not have bool args.


<!-- Sent from Reviewable.io -->

2019-08-22 14:56 UTC, andreimatei submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, @nvanbenschoten, and @yuzefovich)

___
*[pkg/sql/app_stats.go, line 233 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtmRqx-H0rGi5Whkok:-LmtmRqy15UfiW2glRqI:b-hklo51) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L233)):*
> ```Go
> 
> func (s *transactionStats) recordTransaction(
> 	totalTimeSec float64, ev txnEvent, isImplicit func() bool,
> ```

you're taking a function returning a `bool`? Why not... a bool? Or a `*bool` if you want to allow nils (but we should get to the bottom of that).
Let me know if you need help.
___
*[pkg/sql/app_stats.go, line 244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtnG4_E_RM514FJKam:-LmtnG4_E_RM514FJKan:behfcyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L244)):*
> ```Go
> 	// TODO(yuzefovich): I don't understand it, but sometimes isImplicit is null
> 	// here which means that either txnCommit or txnAborted events were emitted,
> 	// but txnStart wasn't (?).
> ```

I think it's worth getting to the bottom of this. printf your way to figuring out how that happens.
I was perhaps not very principled when I've introduced these txn events, so perhaps I've missed some cases.
___
*[pkg/sql/app_stats.go, line 251 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtmsn133lJt1WhvYMP:-Lmtmsn133lJt1WhvYMQ:bpucow4) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L251)):*
> ```Go
> 
> func (a *appStats) recordTransaction(totalTimeSec float64, ev txnEvent, isImplicit func() bool) {
> 	if a == nil || !txnStatsEnable.Get(&a.st.SV) {
> ```

sup with the `a == nil` check? Do we really need to allow calling such a method on a nil receiver? At the very least add a comment to lower people's eye brows.
___
*[pkg/sql/app_stats.go, line 257 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtihf-6b5I7Jb2RrTK:-Lmtihf-6b5I7Jb2RrTL:brq48jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L257)):*
> ```Go
> }
> 
> // sqlStats carries per-application statistics for all applications on each
> ```

nit: this comment is bad; there's noting "each node" about this struct
___
*[pkg/sql/conn_executor.go, line 941 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmofrJ49f5pE9m-MiF1:-LmtnnUI72Yfw2qVFbdY:bcfgs98) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor.go#L941)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done. I don't understand though why would we be using a closure here instead of a simple boolean within `extraTxnState`?
</blockquote></details>

I didn't mean a closure that returns whether the txn is implicit or not :)
I meant a closure that calls `recordTransaction()` and *binds* the information about  whether the txn is implicit.
Like
```
return func() {
   recordTxn(..., implicit)
}
```
___
*[pkg/sql/conn_executor.go, line 751 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmqPrTO3czaINf9Pp5r:-LmtkJf93-UTEH1efozE:bnsjgxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56e86a86f72d9762736b8ee4ccc4d31816232b1/pkg/sql/conn_executor.go#L751)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think `noEvent` here is the right choice, but I'm not sure.
</blockquote></details>

everything in this `close()` seems a bit hacky; it doesn't matter much what happens around here as long as we properly clean up stuff that needs cleaning up - in particular, as long as long as we rollback the (kv) txn (if any) and we close its span.

I think what you did is fine. An alternative that would perhaps be a bit nicer is to gate the beginning of this method on checking whether we're inside a txn (` ex.machine.CurState().(stateNoTxn)` or such). And if we're inside a txn, sending an `txnAborted` event to `resetExtra..` would be appropriate.
___
*[pkg/sql/crdb_internal.go, line 694 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtltRl8blEEV_P36Jc:-LmtltRl8blEEV_P36Jd:b-rqyao9) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/crdb_internal.go#L694)):*
> ```Go
>   application_name   STRING NOT NULL,
>   txn_count          INT NOT NULL,
>   avg_total_time_sec FLOAT NOT NULL,
> ```

what's the "total"? I think you want `avg_time_sec`.
___
*[pkg/sql/crdb_internal.go, line 709 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtoc7w8xAlkbbHIX0Z:-Lmtoc7w8xAlkbbHIX0_:b-kgivvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/crdb_internal.go#L709)):*
> ```Go
> 		}
> 
> 		leaseMgr := p.LeaseMgr()
> ```

unless there's already a million other people doing the same, let's find a better . way to get the node id than going through `p.LeaseMgr`.
Put the `nodeIDContainer` in the `ExtendedEvalCtx` too if it's not there already.


<!-- Sent from Reviewable.io -->

2019-08-22 19:00 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)

___
*[pkg/sql/app_stats.go, line 233 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtmRqx-H0rGi5Whkok:-LmudaBm0z4nGsDiyiEC:b-h9788d) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L233)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you're taking a function returning a `bool`? Why not... a bool? Or a `*bool` if you want to allow nils (but we should get to the bottom of that).
Let me know if you need help.
</blockquote></details>

This was misunderstanding on my part, fixed.
___
*[pkg/sql/app_stats.go, line 244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtnG4_E_RM514FJKam:-Lmudk8X09bW0kjLjZux:b-qz1efe) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L244)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it's worth getting to the bottom of this. printf your way to figuring out how that happens.
I was perhaps not very principled when I've introduced these txn events, so perhaps I've missed some cases.
</blockquote></details>

I think I figured out the thing when isImplicit function is nil in some cases. The reason is that we have a "limited" conn executor bound to BoundTxnStateTransitions which is used by the InternalExecutor when running inside a higher-level transaction. In there, when the "inner txn" gets an error, the txnEvent is set to txnAborted, but that "inner txn" is never explicitly started. I think in such a case we do not want to record the fact that "inner txn" is finished since it should be higher-level txn's responsibility.
___
*[pkg/sql/app_stats.go, line 251 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtmsn133lJt1WhvYMP:-LmueKRH956U5RYJBLXM:b-s4ycp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L251)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sup with the `a == nil` check? Do we really need to allow calling such a method on a nil receiver? At the very least add a comment to lower people's eye brows.
</blockquote></details>

I copied this over from statement stats, but I agree with your thinking here. Removed the nil check (I believe it was never nil anyway, and if it was, then something is broken).
___
*[pkg/sql/app_stats.go, line 257 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtihf-6b5I7Jb2RrTK:-LmuaRMA9VbYkLyjQhYB:b3op6x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/app_stats.go#L257)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: this comment is bad; there's noting "each node" about this struct
</blockquote></details>

Removed. I think it was implying that these statistics are not aggregated between different nodes and only contain the information about the local node, for each node, so using different nodes as gateways - in theory - should return different statistics.
___
*[pkg/sql/conn_executor.go, line 941 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmofrJ49f5pE9m-MiF1:-Lmud8ut1VvtMtAif35s:b-hexfgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3a66e10b9b710831d9214c49581de05fd240767/pkg/sql/conn_executor.go#L941)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I didn't mean a closure that returns whether the txn is implicit or not :)
I meant a closure that calls `recordTransaction()` and *binds* the information about  whether the txn is implicit.
Like
```
return func() {
   recordTxn(..., implicit)
}
```
</blockquote></details>

Oh, yeah, I misunderstood you :) Fixed.
___
*[pkg/sql/conn_executor.go, line 751 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmqPrTO3czaINf9Pp5r:-LmufG-L7GL5N2J4ltB4:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56e86a86f72d9762736b8ee4ccc4d31816232b1/pkg/sql/conn_executor.go#L751)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

everything in this `close()` seems a bit hacky; it doesn't matter much what happens around here as long as we properly clean up stuff that needs cleaning up - in particular, as long as long as we rollback the (kv) txn (if any) and we close its span.

I think what you did is fine. An alternative that would perhaps be a bit nicer is to gate the beginning of this method on checking whether we're inside a txn (` ex.machine.CurState().(stateNoTxn)` or such). And if we're inside a txn, sending an `txnAborted` event to `resetExtra..` would be appropriate.
</blockquote></details>

Thanks, done.
___
*[pkg/sql/crdb_internal.go, line 694 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-LmtltRl8blEEV_P36Jc:-LmudNPs5Vs7mmqI5UVT:b4nqqmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/crdb_internal.go#L694)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the "total"? I think you want `avg_time_sec`.
</blockquote></details>

I agree. It is a remnant of how the issue I'm trying to close with this PR called it as "total transaction time." Fixed.
___
*[pkg/sql/crdb_internal.go, line 709 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-Lmtoc7w8xAlkbbHIX0Z:-Lmug6q084qeo-WTPNgU:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/35b404ebf70b103bc562e8a088fd68c669f71263/pkg/sql/crdb_internal.go#L709)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

unless there's already a million other people doing the same, let's find a better . way to get the node id than going through `p.LeaseMgr`.
Put the `nodeIDContainer` in the `ExtendedEvalCtx` too if it's not there already.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2019-08-27 15:13 UTC, andreimatei reviewed
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39429#-:-LnIcsUgB6Ds3-BG4jhe:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @jordanlewis, @mjibson, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2019-08-27 18:11 UTC, merged