sql: Fix bug with negative parsing validation for zone constraints
cockroachdb/cockroach pull request #39824
Opened 2019-08-22 18:35 UTC by rohany

Fixes #39801.

This PR fixes the parsing issues brought up in #39801, and refactors the test cases for zone validation to specifically test this behavior. Previously this behavior was tested, but falsely passed due to a logic error.

Release note: None

2019-08-22 18:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/39824)
<!-- Reviewable:end -->

2019-08-27 15:28 UTC, solongordon reviewed
Logic looks good to me. A couple points of confusion that could be cleaned up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-:-LnIg8B37j7Bmez3F0FZ:b-t2mxv6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIdx-j-OgMHuM3owU5:-LnIdx-j-OgMHuM3owU6:b-pad04o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config.go#L611)):*
> ```Go
> 		// logic below fails to validate negative constraints if a node
> 		// in the cluster has the constraint being prohibited, and
> 		// falsely validates prohibited constraints in certain cases as well.
> ```

This comment is confusing to me. Based on the comment on the function definition it seems like we don't want to validate negative constraints anyway, right?
```
// Note that this really only catches typos in required constraints -- we don't
// want to reject prohibited constraints whose attributes/localities don't
// match any of the current nodes because it's a reasonable use case to add
// prohibited constraints for a new set of nodes before adding the new nodes to
// the cluster. If you had to first add one of the nodes before creating the
// constraints, data could be replicated there that shouldn't be.
```
So it seems like your comment isn't really necessary.
___
*[pkg/sql/set_zone_config_test.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIfU57201UokPFUAVI:-LnIfU57201UokPFUAVJ:bbm0392) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config_test.go#L136)):*
> ```Go
> 		cfg       string
> 		expectErr int
> 		nodes     nodeGetter
> ```

Nit: To me the way this is set up is confusing, with all these functions floating around. It would be clearer if the test case just had the store definitions. Then the test body could do the work of converting that to a `nodeGetter`.


<!-- Sent from Reviewable.io -->

2019-08-27 16:08 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIdx-j-OgMHuM3owU5:-LnIorvo7iuSuDwaKFuf:b-4y8zkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config.go#L611)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This comment is confusing to me. Based on the comment on the function definition it seems like we don't want to validate negative constraints anyway, right?
```
// Note that this really only catches typos in required constraints -- we don't
// want to reject prohibited constraints whose attributes/localities don't
// match any of the current nodes because it's a reasonable use case to add
// prohibited constraints for a new set of nodes before adding the new nodes to
// the cluster. If you had to first add one of the nodes before creating the
// constraints, data could be replicated there that shouldn't be.
```
So it seems like your comment isn't really necessary.
</blockquote></details>

I think my wording isn't clear enough then. When I say "fail to validate" i mean incorrectly declares negative constraints in certain cases as invalid.
___
*[pkg/sql/set_zone_config_test.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIfU57201UokPFUAVI:-LnIp2iI5YiFsM39Ve_d:bip3clw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config_test.go#L136)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: To me the way this is set up is confusing, with all these functions floating around. It would be clearer if the test case just had the store definitions. Then the test body could do the work of converting that to a `nodeGetter`.
</blockquote></details>

I think it is a bit clearer to do this, as the zone configuration function also expects a "nodeGetter" function. I don't see the difference in readability between passing the closures (getters around the structs) around vs passing the structs as variables directly.


<!-- Sent from Reviewable.io -->

2019-08-29 13:39 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIdx-j-OgMHuM3owU5:-LnS_fwMDrB7TAnWAHwr:b-alg0cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config.go#L611)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think my wording isn't clear enough then. When I say "fail to validate" i mean incorrectly declares negative constraints in certain cases as invalid.
</blockquote></details>

I think what confuses me is that your comment says we want to ignore validation on negative constraints because the logic can't handle it. But from the pre-existing comment, it sounds like we want to ignore validation on negative constraints anyway for business reasons. Is that right?
___
*[pkg/sql/set_zone_config_test.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIfU57201UokPFUAVI:-LnSaS2_A7vhox2watVa:b-co8my6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config_test.go#L136)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think it is a bit clearer to do this, as the zone configuration function also expects a "nodeGetter" function. I don't see the difference in readability between passing the closures (getters around the structs) around vs passing the structs as variables directly.
</blockquote></details>

OK, I don't feel strongly about it.


<!-- Sent from Reviewable.io -->

2019-08-29 17:02 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIdx-j-OgMHuM3owU5:-LnTIOr32dkxgWjzF3bu:box1smm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config.go#L611)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think what confuses me is that your comment says we want to ignore validation on negative constraints because the logic can't handle it. But from the pre-existing comment, it sounds like we want to ignore validation on negative constraints anyway for business reasons. Is that right?
</blockquote></details>

Yeah, it's a bit weird. The comment at the top of the function says we want to ignore it, but the comment/code at the validation step *still* performs some sort of validation on negative constraints. And it so happens that the validation it performs on negative constraints is incorrect.

To make it a bit clearer what is going on, look at config.StoreMatchesConstraint and config.StoreHasConstraint. If the constraint is a negative constraint, and the store actually has the constraint, then StoreMatchesConstraint *returns false*. However, if the constraint is negative and the store doesn't match the constraint, then StoreMatchesConstraint returns true. Based on it erroneously returning true here, this bug wasn't seen in a majority of cases (multi node clusters -- the loop here loops over all nodes, so when a negative constraint was checked against a node in the cluster *that didn't have the constraint*, the validation would be successful).


<!-- Sent from Reviewable.io -->

2019-08-29 20:48 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 611 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39824#-LnIdx-j-OgMHuM3owU5:-LnU6z9G9lnYYKrlj-RW:bciahp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9857b20fb917fbf0eb45ae2fd45388040da9e3e1/pkg/sql/set_zone_config.go#L611)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Yeah, it's a bit weird. The comment at the top of the function says we want to ignore it, but the comment/code at the validation step *still* performs some sort of validation on negative constraints. And it so happens that the validation it performs on negative constraints is incorrect.

To make it a bit clearer what is going on, look at config.StoreMatchesConstraint and config.StoreHasConstraint. If the constraint is a negative constraint, and the store actually has the constraint, then StoreMatchesConstraint *returns false*. However, if the constraint is negative and the store doesn't match the constraint, then StoreMatchesConstraint returns true. Based on it erroneously returning true here, this bug wasn't seen in a majority of cases (multi node clusters -- the loop here loops over all nodes, so when a negative constraint was checked against a node in the cluster *that didn't have the constraint*, the validation would be successful).
</blockquote></details>

Yeah that makes sense, but still, we don't even want to validate negative constraints, so I don't care if the logic handles them or not. My personal preference would be to just change this comment to `// We skip validation for negative constraints. See the function-level comment.`, but I'll leave it up to you to choose what you think is clearest.


<!-- Sent from Reviewable.io -->

2019-08-29 21:02 UTC, rohany commented
bors r=solongordon

2019-08-29 21:03 UTC, rohany commented
bors r=solongordon

2019-08-29 21:57 UTC, rohany commented
bors retry

2019-08-29 22:44 UTC, rohany commented
bors r+

2019-08-29 23:16 UTC, rohany commented
alright @solongordon got any idea whats going on here? bors is just not happy :(

2019-08-29 23:50 UTC, rohany commented
bors r=solongordon

2019-08-30 00:26 UTC, merged