exec: add inbox shutdown race test
cockroachdb/cockroach pull request #40193
Opened 2019-08-24 10:09 UTC by asubiotto

Release note: None

Closes #39775

This test was added to test the inbox behavior in a concurrent environment with the intention of accompanying a small refactor of the inbox state machine. The latter is still in progress and I think this test is probably useful to have independently. It also increases my confidence in the Inbox implementation. Since I'm out for a week or so I'll just put this up and work on the refactor if we still want it before the release (although it might be cutting it close).

2019-08-24 10:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40193)
<!-- Reviewable:end -->

2019-08-26 16:24 UTC, yuzefovich requested changes
Great work, I think it's a very thorough test! I'm only concerned about the condition of when we're sending batches in `RunWithStream`.

[super nit]: usually, the order of things in the commit message is as "comment", Closes: ..., Release note...

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-:-LnDiSB03WMn4e1rQL_e:bmmq6j4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec/colrpc/inbox_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDeZz26DO1j5P1Np-q:-LnDeZz26DO1j5P1Np-r:b6x7o3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L24)):*
> ```Go
> 	"time"
> 
> 	"github.com/cockroachdb/cockroach/pkg/col/colserde"
> ```

[nit]: it seems like the packages are out of order with unnecessary blank lines in-between.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDjMFQ7MioyLTR3UKw:-LnDjMFQ7MioyLTR3UKx:bguo3uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L191)):*
> ```Go
> //  - DrainMeta called concurrently with Next with an active stream.
> //  - A forceful cancellation of Next but no call to DrainMeta.
> func TestInboxShutdown(t *testing.T) {
> ```

(in the comment above):
[nit]: different indentation between scenarios.
[nit]: probably `s/Next before/Next and before/`.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDjSb9Ahxf01WRI4lc:-LnDjSb9Ahxf01WRI4ld:bz1iolj) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L251)):*
> ```Go
> 										// stream code during normal operation. This timeout simulates a
> 										// stream not arriving in time.s
> 										inbox.Timeout(errors.New("artificial timeout"))
> ```

[nit]: `s/time.s/time./` (in the line above).
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDh7sL7Bsm99gKwh5J:-LnDh7sL7Bsm99gKwh5K:be1xjnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L293)):*
> ```Go
> 										msg := &distsqlpb.ProducerMessage{Data: distsqlpb.ProducerData{RawBytes: buffer.Bytes()}}
> 										batchesToSend := rng.Intn(65536)
> 										for i := 0; !infiniteBatches && i == batchesToSend; i++ {
> ```

I don't understand the condition here. It seems to me that if `batchesToSend != 0` (which happens in 65535 out of 65536 cases), the `for` loop will never be executed.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDhTG9Ctqt4k2pdhCF:-LnDhTG9Ctqt4k2pdhCG:b-p29xr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L308)):*
> ```Go
> 									// Use context.Background() because it's separate from the
> 									// inbox context.
> 									handleErr := <-handleStream(context.Background(), inbox, rpcLayer.server, func() { close(rpcLayer.server.csChan) })
> ```

[nit]: it might be better to declare a variable like `handleStreamCtx := context.Background()` up top (and have a comment about it there) and use it here.


<!-- Sent from Reviewable.io -->

2019-09-05 08:43 UTC, asubiotto reviewed
TFTR. I kept this PR without a commit message and aimed to just provide an explanation of why I was opening this PR in the PR message. The `Closes: ` I think is also better to but in the PR message since it avoids pinging the issue every time you rebase and push.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-:-Lo-WjTC4IalDHN7MoBb:b-4gflgo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDeZz26DO1j5P1Np-q:-Lo-YfUY-E2tLFNEnk5s:bfctt07) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it seems like the packages are out of order with unnecessary blank lines in-between.
</blockquote></details>

Done. No idea why go imports didn't fix this :/
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDjMFQ7MioyLTR3UKw:-Lo-YxUPAx2voAtOoTEC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L191)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

(in the comment above):
[nit]: different indentation between scenarios.
[nit]: probably `s/Next before/Next and before/`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDjSb9Ahxf01WRI4lc:-Lo-Z0n72g3_lcBaLXew:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L251)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/time.s/time./` (in the line above).
</blockquote></details>

Done.
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDh7sL7Bsm99gKwh5J:-Lo-ZQp30X-uYgUvFoIv:bqdrwp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L293)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't understand the condition here. It seems to me that if `batchesToSend != 0` (which happens in 65535 out of 65536 cases), the `for` loop will never be executed.
</blockquote></details>

Oops, changed the condition
___
*[pkg/sql/exec/colrpc/inbox_test.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDhTG9Ctqt4k2pdhCF:-Lo-_dJEEEJjZQM8CQnt:bp7xlpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L308)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it might be better to declare a variable like `handleStreamCtx := context.Background()` up top (and have a comment about it there) and use it here.
</blockquote></details>

I don't know, why do you think it's better?


<!-- Sent from Reviewable.io -->

2019-09-05 16:00 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Yeah, when I said "commit message" I meant "the PR message".

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-:-Lo18EZB4KfsHB2x_-7g:b-f1ppe6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec/colrpc/inbox_test.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40193#-LnDhTG9Ctqt4k2pdhCF:-Lo17d0lBjA6l9XKScCV:bud8n2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/009105066e3f0bb8d6d3ab96b3b9a30167f34813/pkg/sql/exec/colrpc/inbox_test.go#L308)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't know, why do you think it's better?
</blockquote></details>

I guess I was looking for "symmetry" with `inboxCtx`, and it seemed to me that it'd be more appropriate for the comment to be where `inboxCtx` is derived, but I don't have a strong opinion about this, so feel free to disregard this comment.


<!-- Sent from Reviewable.io -->

2019-09-09 09:32 UTC, asubiotto commented
bors r=yuzefovich

2019-09-09 10:59 UTC, asubiotto commented
bors r=yuzefovich

2019-09-09 11:32 UTC, merged