exec: a small amount of DRY for proj/sel ops
cockroachdb/cockroach pull request #40358
Opened 2019-08-30 00:11 UTC by jordanlewis

The struct definitions had a lot of overlap - this adds some base
structs to clean things up a little bit.

Release note: None

2019-08-30 00:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40358)
<!-- Reviewable:end -->

2019-08-30 00:22 UTC, jordanlewis commented
First commit is from a different PR.

2019-08-30 15:48 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/exec/projection_ops_test.go, line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYBHZu0Cxt43X7qJBn:-LnYBHZvDltpnXrchgid:b-oq8jtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/projection_ops_test.go#L245)):*
> ```Go
> 			case coltypes.Int64:
> 				return &projPlusInt64Int64Op{
> 					projOpBase: projOpBase{
> ```

i think all the `projOpBase`s in this function could be extracted to one variable
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYBjBQARzeeurpnTC0:-LnYBjBQARzeeurpnTC1:b-8z98ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L41)):*
> ```Go
> // constant, except for the constant itself.
> type projConstOpBase struct {
> 	OneInputNode
> ```

nit: different indentation happening here
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 256 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYBz29ClAQNWXwhYdj:-LnYBz29ClAQNWXwhYdk:bhx1txd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L256)):*
> ```Go
> 				{{if .IsBinOp}}
> 				case tree.{{.Name}}:
> 					return &{{if $left}}{{template "opLConstName" .}}{{else}}{{template "opRConstName" .}}{{end}}{projConstOpBase: projConstOpBase, constArg: c.({{if $left}}{{.LGoType}}{{else}}{{.RGoType}}{{end}})}, nil
> ```

nit: might be more readable if it were still multi line
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYC5WLAeAY0az8KRlv:-LnYC5WLAeAY0az8KRlw:b-9szxcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L267)):*
> ```Go
> 				{{if .IsCmpOp}}
> 				case tree.{{.Name}}:
> 					return &{{if $left}}{{template "opLConstName" .}}{{else}}{{template "opRConstName" .}}{{end}}{projConstOpBase: projConstOpBase, constArg: c.({{if $left}}{{.LGoType}}{{else}}{{.RGoType}}{{end}})}, nil
> ```

same, maybe should be multi line
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYCPj8CRjZSbMij9WT:-LnYCPj8CRjZSbMij9WU:b8zpyyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L40)):*
> ```Go
> // selConstOpBase contains all of the fields for binary selections with a
> // constant, except for the constant itself.
> type selConstOpBase struct {
> ```

not too sure of this suggestion, but maybe these base structs could be defined in some other non-`_gen.go` file so they are easier to find? up to you


<!-- Sent from Reviewable.io -->

2019-09-05 12:22 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/exec/projection_ops_test.go, line 245 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYBHZu0Cxt43X7qJBn:-Lo0Mtu_26pynv-1u6l4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/projection_ops_test.go#L245)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think all the `projOpBase`s in this function could be extracted to one variable
</blockquote></details>

Done.
___
*[pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYC5WLAeAY0az8KRlv:-Lo0MumQ-mMSAacS0rm5:b33bjto) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/projection_ops_gen.go#L267)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

same, maybe should be multi line
</blockquote></details>

Done. And I discovered a very helpful trick! Appending or prepending `-` to any template suppress the whitespace after or before it, respectively.
___
*[pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40358#-LnYCPj8CRjZSbMij9WT:-Lo0N2BE8dtI9_uOTz-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6195a78db1a9272a8f56b6d2262bb36b148ae5c/pkg/sql/exec/execgen/cmd/execgen/selection_ops_gen.go#L40)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not too sure of this suggestion, but maybe these base structs could be defined in some other non-`_gen.go` file so they are easier to find? up to you
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-05 20:25 UTC, rafiss approved these changes
> Reviewed 1 of 6 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2019-09-05 20:29 UTC, jordanlewis commented
bors r+

2019-09-05 21:17 UTC, merged