sql: Remove unnecessary constraints check in show create
cockroachdb/cockroach pull request #40417
Opened 2019-09-03 15:13 UTC by rohany

The show create table function would not display a zone configuration
if the constraints list was empty. However, this isn't a valid check
because the constraints list could be empty but other fields set.

Release note: None

2019-09-03 15:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40417)
<!-- Reviewable:end -->

2019-09-03 23:24 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40417)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40417#-LntR4VT29RxyWerWBgQ:-LntR4VT29RxyWerWBgR:b84dvmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d76ccfdec0a6a6069cbccc89ef2fb5e907ac26/pkg/sql/crdb_internal.go#L1221)):*
> ```Go
> 				if zoneConfig.RangeMinBytes != nil || zoneConfig.RangeMaxBytes != nil ||
> 					zoneConfig.NumReplicas != nil || len(zoneConfig.Constraints) != 0 ||
> 					len(zoneConfig.LeasePreferences) != 0 {
> ```

This looks brittle. If anyone adds a new field to `ZoneConfig` and doesn't update this logic it'll be broken. Would it work to just compare to an empty `config.ZoneConfig{}` instead?


<!-- Sent from Reviewable.io -->

2019-09-04 00:57 UTC, rohany commented
I just tried, and it doesn't seem like we can. The arrays inside of the zoneConfig can't be compared, so an error is thrown at compile time. A better solution might be to define an equality function on zone configs, and then drop a comment to update that? Or define a function isEmptyZoneConfig and then update that when the zoneConfig struct changes.

2019-09-04 03:34 UTC, solongordon commented
If I'm not mistaken, `ZoneConfig` should be a protobuf-generated struct which already comes with an `Equal` method built in.

2019-09-04 15:26 UTC, rohany commented
Oh sweet -- i didnt know proto did that for us. Let me change that.

2019-09-04 17:08 UTC, rohany commented
Alright, that looks like it worked. PTAL

2019-09-05 16:47 UTC, solongordon approved these changes
Lovely

2019-09-05 16:49 UTC, rohany commented
bors r+

2019-09-05 17:34 UTC, merged