cmd/smithtest: add sqlsmith auto tester and github filer
cockroachdb/cockroach pull request #40453
Opened 2019-09-04 02:34 UTC by mjibson

smithtest is a CLI program for automating sqlsmith testing. It does
normal sqlsmith but via cockroach demo, so found panics don't also take
down the test itself. Found errors are de-duplicated using existing
github issues. The reducer is used to minimize test repros. A new tab
is opened to github with most of the issue data filled in.

The CLI is taught about COCKROACH_FORCE_INTERACTIVE, a new environment
variable that forces the interactive flag to be on. The interactive
demo shell outputs its address on startup. This makes it possible for
smithtest to start cockroach demo nodes and scrape their listen address so
it can then connect and execute statements. Without the interactive flag,
no address is output, and thus it's not possible to get the listening
address of the demo node.

Release note: None

2019-09-04 02:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40453)
<!-- Reviewable:end -->

2019-09-04 06:00 UTC, mjibson commented
@knz can you review the CLI interactive change?

2019-09-04 11:04 UTC, knz reviewed
Yeah so I reviewed this and I strongly recommend against this approach.

1. the interactive boolean does imply a few other things besides just  printing the intro text, and you probably don't want those things to occur
2. printing the connection URL on the message shown to *all users of demo* will erroneously suggest that cockroach demo starts a "server" that they can connect to from other tools, or even suggest that  they *must* use an external tool to use it. I find this coutner-productive to the kind of UX we want to advertise for `cockroach demo`, and it may increase our support burden in unexpected ways.

Instead, please consider issuing the following SQL query via the command's stdin instead: `select value from crdb_internal.node_runtime_info where component='DB' and field='URL';` which will give you that URL too.

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-:-LnvvfqK3WiyzdIByi5V:b6od4yx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-09-04 11:07 UTC, knz commented
In fact I'd go a step further and argue that hijacking `cockroach demo`, a tool that's inherently designed for human consumption and where we have 0% guarantee of UX stability, for the purpose of automated testing which does require some form of API stability, is not a good way to go.

I'd instead recommend building an executable program that sets up a cockroachdb test server like any unit test and prints the connection URL on its stderr, and have that custom executable driven by your sqlsmith command. They would live next to each other in the same package and this way you don't create a mandate for every contributor to `cockroach demo` to keep your testing tool in mind.

2019-09-05 18:43 UTC, rafiss requested changes
i reviewed the internals of the new command, bu i defer to knz about `COCKROACH_FORCE_INTERACTIVE`

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-:-Lo1j6162nNAEr012u_B:b-tzpcbk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1i1Rn3_QpU383R_ia:-Lo1i1Rn3_QpU383R_ib:bbfcfxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L68)):*
> ```Go
> 	rand.Seed(timeutil.Now().UnixNano())
> 
> 	// Prepopulate seen issues from GitHub.
> ```

nit: populating seen issues could be extracted to a separate function
___
*[pkg/cmd/smithtest/main.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1dixX52ZmrDOKoxff:-Lo1dixY9qWN5MhWPvBj:b-5q35re) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L71)):*
> ```Go
> 	var opts github.SearchOptions
> 	for {
> 		results, _, err := setup.github.Search.Issues(ctx, "is:issue is:open label:C-bug label:O-sqlsmith", &opts)
> ```

i haven't used this `github` client library, so i might be missing something. how is this search being restricted to only the cockroachdb repo?
___
*[pkg/cmd/smithtest/main.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1i7-GCKnRLrKYGdvb:-Lo1i7-GCKnRLrKYGdvc:bjww8kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L98)):*
> ```Go
> 
> // Setup contains initialization and configuration for running smithers.
> type Setup struct {
> ```

nit: the name `Setup` doesn't really seem descriptive to me, but i also just may not know the naming conventions for stuff like this in go. perhaps a name like `WorkerSetup` or even `WorkerPool`? also, does the type need to be exported?
___
*[pkg/cmd/smithtest/main.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1hy5D6NWO4tsY96K5:-Lo1hy5D6NWO4tsY96K6:bbyiru2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L228)):*
> ```Go
> 	// it takes for a single reduction run.
> 	lock syncutil.RWMutex
> 	seen = map[string]bool{}
> ```

nit: it could be helpful to declare these earlier in the file, since i notice they are used earlier. and perhaps add a comment to `seen`
___
*[pkg/cmd/smithtest/main.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1izwX4pveGGoMO6wi:-Lo1izwX4pveGGoMO6wj:b-yembod) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L289)):*
> ```Go
> 		RawQuery: query.Encode(),
> 	}
> 	const max = 8000
> ```

just curious: do most issue bodies with stacktraces fit into this limit?


<!-- Sent from Reviewable.io -->

2019-09-10 08:55 UTC, knz commented
question from https://github.com/cockroachdb/cockroach/pull/40594#issuecomment-529581092

> Maybe my PR could solve its problem in a different way that doesn't involve changing anything on the interactive side?

What about you use the same technique used in `Example_sql` in `cli_test.go`: `RunWithCapture` and execute `cockroach sql -e` in this way.

2019-09-12 17:59 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1dixX52ZmrDOKoxff:-LoJUPCC8NyM5t5TNdBb:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L71)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i haven't used this `github` client library, so i might be missing something. how is this search being restricted to only the cockroachdb repo?
</blockquote></details>

Fixed.
___
*[pkg/cmd/smithtest/main.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1i7-GCKnRLrKYGdvb:-LoJUYtI9Ufk9bZkTtNJ:blt380a) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L98)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the name `Setup` doesn't really seem descriptive to me, but i also just may not know the naming conventions for stuff like this in go. perhaps a name like `WorkerSetup` or even `WorkerPool`? also, does the type need to be exported?
</blockquote></details>

Renamed. I just wanted it uppercase to indicate its importance. Doesn't matter for commands.
___
*[pkg/cmd/smithtest/main.go, line 289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-Lo1izwX4pveGGoMO6wi:-LoJV2J9BKelfP5u7IqN:b-l4cknr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9d8f4de6ac9ea5b79cea6be5ae3910bd32bb5a/pkg/cmd/smithtest/main.go#L289)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious: do most issue bodies with stacktraces fit into this limit?
</blockquote></details>

Yes. I only found a few that don't, mostly caused by large queries that weren't very reduceable.


<!-- Sent from Reviewable.io -->

2019-09-21 05:03 UTC, mjibson commented
Updated to use a pty package and `cockroach start-single-node` instead of the env var. Note: we do indeed need the pty because the stuff isn't printed to stdout otherwise.

2019-09-21 05:04 UTC, mjibson commented
PTAL

2019-09-22 08:12 UTC, knz reviewed
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-LpN0kX96_7JlK3Lu_SX:-LpN0kX96_7JlK3Lu_SY:b-jsn486) ([raw file](https://github.com/cockroachdb/cockroach/blob/218a22a1a1b1f18918fd3bbc51359fbd57545af5/pkg/cmd/smithtest/main.go#L156)):*
> ```Go
> 		"--port", "0",
> 		"--http-port", "0",
> 		"--insecure",
> ```

Add `--logtostderr` to this and remove the `pty` thing altogether. The log will go to stderr and you can pick the details up from there.

Bonus is that this way you'll also get stack traces and crash reports for fatal errors, not just panics (you'd only get panics otherwise).


<!-- Sent from Reviewable.io -->

2019-09-23 16:57 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-LpN0kX96_7JlK3Lu_SX:-LpU2Vva7cHY71hPx-R-:boyexbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/218a22a1a1b1f18918fd3bbc51359fbd57545af5/pkg/cmd/smithtest/main.go#L156)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add `--logtostderr` to this and remove the `pty` thing altogether. The log will go to stderr and you can pick the details up from there.

Bonus is that this way you'll also get stack traces and crash reports for fatal errors, not just panics (you'd only get panics otherwise).
</blockquote></details>

Done. Thanks.


<!-- Sent from Reviewable.io -->

2019-09-23 18:11 UTC, knz approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with perhaps a nit. 

But otherwise thanks!

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-:-LpUJZYOA2uOa42zxws2:b-38b6ml)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-LpUJPCc1KsqnxLOePlE:-LpUJPCc1KsqnxLOePlF:b-o97yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7f2aab0fa0c6e792ad133f89b6a47f1f568f45/pkg/cmd/smithtest/main.go#L141)):*
> ```Go
> 
> // run is a single sqlsmith worker. It starts a new sqlsmither and cockroach
> // demo instance. If an error is found it reduces and submits the issue. If
> ```

comment needs adjustment. "and in-memory single-node cluster"
___
*[pkg/cmd/smithtest/main.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-LpUJKSr-7eMD6rMYc9c:-LpUJKSs1tme5az-0Xa0:b-f5rn5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7f2aab0fa0c6e792ad133f89b6a47f1f568f45/pkg/cmd/smithtest/main.go#L147)):*
> ```Go
> // nil, since they are expected. Something unexpected would be like the
> // initialization SQL was unable to run.
> func (s WorkerSetup) run(ctx context.Context, rnd *rand.Rand) error {
> ```

My preference would be to split this large functions into small(er) sub-functions. Your call.


<!-- Sent from Reviewable.io -->

2019-09-24 19:48 UTC, madelynnblue reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40453)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz, @mjibson, @rafiss, and @solongordon)

___
*[pkg/cmd/smithtest/main.go, line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40453#-LpUJPCc1KsqnxLOePlE:-LpZoGBN9ZL8wQhD-TEY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a7f2aab0fa0c6e792ad133f89b6a47f1f568f45/pkg/cmd/smithtest/main.go#L141)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

comment needs adjustment. "and in-memory single-node cluster"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-25 20:26 UTC, mjibson commented
bors r+

2019-09-25 20:45 UTC, merged