sql: Fixing show partitions to work on not current database
cockroachdb/cockroach pull request #40450
Opened 2019-09-04 01:34 UTC by rohany

show partitions did not work correctly when the database the object
was within was not the current database. This PR updates show partitions
to fix this and adds regression tests.

Fixes #40448.

Release note: None

2019-09-04 01:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40450)
<!-- Reviewable:end -->

2019-09-04 04:01 UTC, solongordon approved these changes
Thanks for the quick fix! Have you tested this out with database/table names that have spaces in them? I'm not entirely convinced that will work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-:-LnuNMHN79m_XYAgdnUx:b-lom1km)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/delegate/show_partitions.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-LnuN36Z-VV3NVzwaIo8:-LnuN2Go9k9u6vGroWcZ:b-f2kb4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/58aa6eeee09b189c4f409b92c41a58901826ed50/pkg/sql/delegate/show_partitions.go#L61)):*
> ```Go
> 			tables.name = %[1]s AND tables.database_name = %[2]s;
> 		`
> 		return parse(fmt.Sprintf(showTablePartitionsQuery, lex.EscapeSQLString(resName.Table()), lex.EscapeSQLString(resName.Catalog()), resName.Catalog()))
> ```

Nit: Long line.


<!-- Sent from Reviewable.io -->

2019-09-04 04:18 UTC, rohany commented
Table and database names can have spaces in them ?? :( I think i know a fix for that though, I'll give it a shot tomorrow.

2019-09-04 04:27 UTC, solongordon commented
Sorry to be the bearer of bad news. `CREATE DATABASE "oh no";`

On Tue, Sep 3, 2019 at 9:19 PM Rohan Yadav <notifications@github.com> wrote:

> Table and database names can have spaces in them ?? :( I think i know a
> fix for that though, I'll give it a shot tomorrow.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/40450?email_source=notifications&email_token=AAFF2TSADLJVMLWZUP6BJ4TQH4ZM3A5CNFSM4ITMLMA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD52JA6A#issuecomment-527732856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAFF2TWWB2DOVIMYTUUA5VDQH4ZM3ANCNFSM4ITMLMAQ>
> .
>

2019-09-04 05:25 UTC, mjibson commented
`create database """";` is also valid to create a database that's named just double quote.

2019-09-04 15:14 UTC, rohany commented
this """" database is ruining my morning.

2019-09-04 17:30 UTC, mjibson commented
We have functions to deal with all of this. If you are having trouble, it should only be in the form of locating the functions. You should not be writing any new logic to handle this stuff.

2019-09-04 17:47 UTC, rohany commented
re matt -- yes, it just took a while to find the right functions and massage things to the right types. More time was spent trying to debug logic tests.

Please take another look, I had to make a decent amount of changes now. I noticed that the show ranges command faces a similar issue, so I fixed that here, except the logic tests don't work -- for some reason the crdb_internal.ranges table of the new database I'm creating is not getting populated correctly, which doesn't make any sense to me.

2019-09-05 15:26 UTC, rohany commented
I realized the problem with testing. I'll update the PR soon with a fix.

2019-09-05 15:53 UTC, rohany commented
RFAL

2019-09-05 16:38 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40450)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/delegate/show_partitions.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1FRcY5m1SJ0bFVu22:-Lo1FRcY5m1SJ0bFVu23:bsdnuhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_partitions.go#L64)):*
> ```Go
> 			lex.EscapeSQLString(resName.Table()),
> 			lex.EscapeSQLString(resName.Catalog()),
> 			resName.CatalogName.String()))
> ```

Nit: It's not incorrect but I believe the `.String()` call is redundant here (and in several other spots below.) `Sprintf` will automatically call `.String()` when converting arguments to strings.
___
*[pkg/sql/delegate/show_partitions.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1FufE3WeUX723Zjmj:-Lo1FufE3WeUX723Zjmk:bk2eu4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_partitions.go#L92)):*
> ```Go
> 			tables.name, partitions.name;
> 		`
> 		// Note (tree.Name).String() != string(name)
> ```

I see what you mean here but it might be clearer to just say `Note: n.Database.String() != string(n.Database)`.
___
*[pkg/sql/delegate/show_ranges.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1Gzx_4Tt6zxCxazZ2:-Lo1Gzx_4Tt6zxCxazZ3:b-ksa668) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_ranges.go#L80)):*
> ```Go
> FROM %[3]s.crdb_internal.ranges AS r
> LEFT JOIN %[3]s.crdb_internal.gossip_nodes n ON
> r.lease_holder = n.node_id
> ```

Why the additional join?  Did this sneak in from another PR?


<!-- Sent from Reviewable.io -->

2019-09-05 16:40 UTC, solongordon requested changes

2019-09-05 16:40 UTC, solongordon commented on pkg/sql/logictest/testdata/logic_test/ranges
> +# Due to aynschronous splitting of ranges, we cannot gaurantee the output of the show ranges from database command.
Please fix misspellings (aynschronous, gaurantee) and limit comment line length to 80 chars when possible.

2019-09-05 16:40 UTC, solongordon commented on pkg/sql/logictest/testdata/logic_test/ranges
> +# The test below just ensure that the translation occurs correctly.
ensures

2019-09-05 16:40 UTC, solongordon commented on pkg/sql/logictest/testdata/logic_test/ranges
> +# The test below just ensure that the translation occurs correctly.
Also not obvious what "the translation" means.

2019-09-05 16:48 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40450)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/delegate/show_partitions.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1FRcY5m1SJ0bFVu22:-Lo1J3E1AhsCEHeswCXx:bfyas1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_partitions.go#L64)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: It's not incorrect but I believe the `.String()` call is redundant here (and in several other spots below.) `Sprintf` will automatically call `.String()` when converting arguments to strings.
</blockquote></details>

I think its clearer to make the String call here due to subtlety of needing to call it vs just using .Catalog()
___
*[pkg/sql/delegate/show_partitions.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1FufE3WeUX723Zjmj:-Lo1JOvjBXFgOxt5m4l2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_partitions.go#L92)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I see what you mean here but it might be clearer to just say `Note: n.Database.String() != string(n.Database)`.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_ranges.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40450#-Lo1Gzx_4Tt6zxCxazZ2:-Lo1JPVM2Ecdk1-Y0X5H:b-r4aaas) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a4529f0f2b2b61a7fd0f589c798d3b56786a490/pkg/sql/delegate/show_ranges.go#L80)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why the additional join?  Did this sneak in from another PR?
</blockquote></details>

woah -- this somehow got in here from a really old rebase. Good catch...


<!-- Sent from Reviewable.io -->

2019-09-10 14:50 UTC, solongordon approved these changes

2019-09-10 14:58 UTC, rohany commented
bors r+

2019-09-10 15:06 UTC, rohany commented
bors r-

2019-09-10 15:08 UTC, rohany commented
bors r+

my rebase picked up some changes to vendor unnecesarily

2019-09-10 16:03 UTC, merged