[WIP]sql: Display inherited constraints in show partitions
cockroachdb/cockroach pull request #40493
Opened 2019-09-04 22:26 UTC by rohany

There a couple things going on here, so I want to get some feedback before adding tests and committing too much to this implementation.

The current implementation of SHOW PARTITIONS joins against the crdb_internal.zones table to get the zone config information. However, the internal zones table is intended to not contain inherited zone information. Additionally, because partitions that don't have zone configuration data are not present in the system.zones table, its hard to follow the dependency chain from the partition's zone config. 

Therefore, I decided to add zone config inheritance information into the crdb_internal.partitions table, and follow the inheritance chain manually and display the full inherited zone configuration there.

Fixes #40349.

Release note: None

2019-09-04 22:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40493)
<!-- Reviewable:end -->

2019-09-04 22:31 UTC, rohany commented
There are some problems with this that I'm noticing however, such as follows. Consider the example @andreimatei brought up in #40377 with the following table and zone constraints applied
```
create table t(country string, x int, primary key (country, x)) 
partition by list (country) 
(
  partition us values in ('us') partition by range (x) 
    (
      partition low values from (0) to (100)
    )
);

alter table t configure zone using constraints='[+region=us-east1]';
alter partition us of table t configure zone using constraints='[+az=b]';
```

If i understand zone inheritance correctly, partition low *should* have constraints +region=us-east1, because that is the first constraint above it in the inheritance chain of partition -> index -> table -> database -> default. That is what the output of show partitions now will display : 
```
root@127.0.0.1:62780/movr> show partitions from table t;
  database_name | table_name | partition_name | parent_partition | column_names | index_name | partition_value |       zone_config       |               full_zone_config
+---------------+------------+----------------+------------------+--------------+------------+-----------------+-------------------------+-----------------------------------------------+
  movr          | t          | us             | NULL             | country      | t@primary  | ('us')          | constraints = '[+az=b]' | range_min_bytes = 16777216 (INHERITED),
                |            |                |                  |              |            |                 |                         | range_max_bytes = 67108864 (INHERITED),
                |            |                |                  |              |            |                 |                         | gc.ttlseconds = 90000 (INHERITED),
                |            |                |                  |              |            |                 |                         | num_replicas = 1 (INHERITED),
                |            |                |                  |              |            |                 |                         | constraints = [+az=b],
                |            |                |                  |              |            |                 |                         | lease_preferences = [] (INHERITED)
  movr          | t          | low            | us               | x            | t@primary  | (0) TO (100)    | NULL                    | range_min_bytes = 16777216 (INHERITED),
                |            |                |                  |              |            |                 |                         | range_max_bytes = 67108864 (INHERITED),
                |            |                |                  |              |            |                 |                         | gc.ttlseconds = 90000 (INHERITED),
                |            |                |                  |              |            |                 |                         | num_replicas = 1 (INHERITED),
                |            |                |                  |              |            |                 |                         | constraints = [+region=us-east1] (INHERITED),
                |            |                |                  |              |            |                 |                         | lease_preferences = [] (INHERITED)
(2 rows)
```

However, from what I can gather about zone config key resolution the zone config for keys in low will start with something like /Table/Index/1/us/ and thus resolve to have constraint +az=b. This _makes sense_, but I don't think follows the rules that we currently have laid out for zone configuration inheritance. 

Please let me know if I am on the right track with this stuff, and loop in people who know more about this.

2019-09-09 15:44 UTC, rohany commented
This is ready for a look now, I redid the implementation in a much better way. However, I still can't reproduce the example that andrei has created -- the configuration of the subpartition never "switches". Instead it always inherits from the table/indexes configuration, not the parent partitions.

2019-09-11 21:38 UTC, andreimatei reviewed
Let me propose something else. Instead of adding the `zone_config` column to `crdb_internal.partitions`, add a reference to the `crdb_internal.zones` table (`<zone_id/subzone_id>`). `subzone_id` is brand new.
`crdb_internal.zones` doesn't deal with inheritance, but I think we should expand it to do it - besides its `config_yaml` column, add also an `config_full_yaml` one that inherits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-:-LoXF-7J0a6casm3WLTX:b-yplpav)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @awoods187, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoX9IDU6-y6ClHG6rZ9:-LoX9IDU6-y6ClHG6rZA:bw6jsv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2513)):*
> ```Go
> }
> 
> func addPartitioningRows(
> ```

pls comment this function and its arguments. What can be nil? The implementation is recursive, so this is quite important
___
*[pkg/sql/crdb_internal.go, line 2513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoX9ktyD0r5WYaxrX0K:-LoX9ktyD0r5WYaxrX0L:b-tvw7kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2513)):*
> ```Go
> }
> 
> func addPartitioningRows(
> ```

nit: if this function has been introduced recently, I think a better name would be `visitPartitions`. This function does not add anything to anything; it calls a callback.
Also, I'd extract the conversion to different types of datums into that callback
___
*[pkg/sql/crdb_internal.go, line 2537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXAHCN1vWDWfMq6nQO:-LoXAHCN1vWDWfMq6nQP:bmfv8t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2537)):*
> ```Go
> 	colNames := tree.NewDString(buf.String())
> 
> 	var a sqlbase.DatumAlloc
> ```

pls a better name than `a` :)
___
*[pkg/sql/crdb_internal.go, line 2546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXBKBJBlj6aMhgYw32:-LoXBKBJBlj6aMhgYw33:bvbgkao) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2546)):*
> ```Go
> 	}
> 
> 	for _, l := range partitioning.List {
> ```

please comment around here that what this does is produce the `partition_value` column
___
*[pkg/sql/crdb_internal.go, line 2561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoX8JpK8UzksVWUyRCt:-LoX8JpK8UzksVWUyRCu:b1c95h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2561)):*
> ```Go
> 		}
> 		name := tree.NewDString(l.Name)
> 		_, zone, subzone, err := GetZoneConfigInTxn(ctx, p.txn, uint32(table.ID), index, l.Name, false)
> ```

pls comment the `false` inline
https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#inline-comments-for-arguments-to-function-calls

Or do everybody one better and, in a different commit, change `GetZoneConfigInTxn()` to take an enum instead of a naked bool so that callers are naturally readable.
___
*[pkg/sql/crdb_internal.go, line 2572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXC3Ch-aehOI7oJHtq:-LoXC3Ch-aehOI7oJHtr:bafpgxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2572)):*
> ```Go
> 			Partition: tree.Name(l.Name),
> 		}
> 		// TODO (rohany): is it correct to take zone if the subzone is nil?
> ```

I think so
___
*[pkg/sql/crdb_internal.go, line 2588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXB2D69F4RqxIiy4R3:-LoXB2D69F4RqxIiy4R4:bfmcon6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2588)):*
> ```Go
> 			numColumns,
> 			colNames,
> 			tree.NewDString(buf.String()),
> ```

pls comment (or assign it to a variable before)
___
*[pkg/sql/crdb_internal.go, line 2589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXB11S6zJxT9kkOvG4:-LoXB11S6zJxT9kkOvG5:b-iz4ctr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2589)):*
> ```Go
> 			colNames,
> 			tree.NewDString(buf.String()),
> 			tree.DNull,
> ```

pls comment


<!-- Sent from Reviewable.io -->

2019-09-11 23:44 UTC, rohany reviewed
I thought about changing crdb_internal.zones instead, but this becomes a problem when a partition doesn't have a zone config, because then it doesn't show up in crdb_internal.zones. This makes it not really clear what to do when trying to figure out the inheritance information relating to a partition. It seemed more straightforward to instead do this on crdb_internal.partitions because there we know all of the partitions and can then look into the zones table for information. Let's figure this out before fixing the code related comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-:-LoXgb0J8v9NuM_hdxqK:b5rvkf9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-09-11 23:58 UTC, andreimatei commented
> This makes it not really clear what to do

It seems clear enough to me: we link the zoneless partition to the lowest ancestor that does have a zone. And that's the end of it when talking about the partitions table. 
Then, in the context of the zones table, we deal with inheritance by exposing both the raw zone config for each zone (as it's implemented now) and the "completed" one (after applying inheritance) in a new column.

2019-09-12 00:01 UTC, andreimatei commented
Btw, longer term, I'm convinced that the model generally needs to evolve away from a partition "having" a zone to a partition "being linked to a zone" (i.e. away from a 1-1 relationship between zones and partitions and to a many-one relationship). So the linking that I'm suggesting we do now I think will naturally evolve into that.

2019-09-12 00:04 UTC, rohany commented
That makes sense, but I still don't think it's that easy to implement that. At least right now, the show commands are just translated into joins (in this case joining partitions and zones). At this point we can't just follow the chain of inheritance up, because we are at the sql level, not go anymore. We could change the show partitions implementation to instead be a plan node and get executed, but I think that would be too large of a change (I haven't done something like that before so I'm unsure of the scope of that).

2019-09-12 00:30 UTC, andreimatei commented
I'm proposing we "walk the chain" in the generator for the `crdb_internal.partitions` table, not in the implementation of `show partitions`. Btw, there's code that I just wrote for that; maybe it helps:
https://github.com/andreimatei/cockroach/blob/91bb5880bc26a1447ed8a2ed6d6ddd900a863048/pkg/storage/reports/reporter.go#L289

2019-09-12 00:43 UTC, rohany commented
Ok, I think I understand your proposed solution now, sorry it took so long. To reiterate:

1. Add a link from crdb_internal.partitions to crdb_internal.zones which represents the zone config that this partition is applying to. Here we pick the correct zone config based on the inheritance chain. There should be an easy way to generate a span when given a partition right?
2. The crdb_internal.zones table should display the inherited zone constraints for each zone in a separate column.
3. Show partitions should just grab the appropriate zone info columns (applied + inherited) for the id's that they link to.

I like this solution, and it should be more useful going forward than what I have. Thanks for the feedback andrei!

2019-09-12 03:39 UTC, rohany commented
PTAL, i reimplemented it in the different way, and I think the code is better now.

2019-09-13 15:55 UTC, andreimatei requested changes
pls put more info in the release note to help the docs folk understand what needs to be documented. Speak about the new columns.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-:-LoaPGi40qQb-EAWUEGr:b-ftt2s1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @awoods187, @rohany, and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning, line 863 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaOoD86drBS6Hsod5u:-LoaOoD86drBS6Hsod5v:b-m3m5ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/ccl/logictestccl/testdata/logic_test/partitioning#L863)):*
> ```
> RESET sql_safe_updates
> 
> <<<<<<< HEAD
> ```

hide your porn
___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaN8Mx1RAuJooZBy3L:-LoaN8Mx1RAuJooZBy3M:beq9x8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
> ```Go
>                            -- possible (e.g. the object was deleted).
>   config_protobuf  BYTES NOT NULL,
> 	inherited_config_yaml STRING NOT NULL,
> ```

alignment
___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaNE8oBGGREhGavuk-:-LoaNE8oBGGREhGavuk0:b-tkq14o) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
> ```Go
>                            -- possible (e.g. the object was deleted).
>   config_protobuf  BYTES NOT NULL,
> 	inherited_config_yaml STRING NOT NULL,
> ```

s/inherited/full

Better yet, I think we should rename the existing columns `raw_config` and call the new ones `config`. This is technically a breaking change, but people are gonna start getting what they were expecting in the column named `config`.
Also, I think we should get rid of the `[inherited_]config_sql` columns and turn `zoneConfigToSQL()` into a builtin function that takes the yaml.

Let's get more eyes on these schema changes - cc @bdarnell @knz 
___
*[pkg/sql/crdb_internal.go, line 2161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofE4cl1HD551jCH08f:-LofE4cm13ssHEWghP1o:b-k8r643) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2161)):*
> ```Go
> 			// Inherit full information about this zone.
> 			fullZone := configProto
> 			// if fullZone is a SubzonePlaceholder, remove its SubzonePlaceholder marker so that
> ```

nit:s/if/If
___
*[pkg/sql/crdb_internal.go, line 2164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofEVMvEo-2v1RBdydu:-LofEVMvEo-2v1RBdydv:b2wqbrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2164)):*
> ```Go
> 			// we get the correct inheritance information.
> 			if fullZone.IsSubzonePlaceholder() {
> 				fullZone.NumReplicas = nil
> ```

How come we have to do this crap? Can we improve `completeZoneConfig` so that we don't have to do it?
___
*[pkg/sql/crdb_internal.go, line 2170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofJv2Y4XRgIWk0ZPOu:-LofJv2Y4XRgIWk0ZPOv:b-g55r69) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2170)):*
> ```Go
> 			}
> 
> 			if !configProto.IsSubzonePlaceholder() {
> ```

I say we get rid of this "subzone placeholder" concept (in general, but in particular for the purposes of this table). I don't understand why this concept exists, in general; there's nothing special about a "subzone placeholder" zone as opposed to any other zone. I think it had to exist in the dark times before cascading zone configs, but now classifying zones as "normal" and "placeholders" I believe is a useless distinction. I say let's just add rows to the `crdb_internal.zones` table for these placeholders.
___
*[pkg/sql/crdb_internal.go, line 2644 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofGEpbEh3HaPaKxzJb:-LofGEpbEh3HaPaKxzJc:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2644)):*
> ```Go
> 
> 		// Figure out which zone and subzone this partition should correspond to.
> 		zoneID, zone, subzone, err := GetZoneConfigInTxn(ctx, p.txn, uint32(table.ID), index, l.Name, false /* getInheritedDefault */)
> ```

long line
___
*[pkg/sql/crdb_internal.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofGKOU3uuBbeCVdAmB:-LofGKOU3uuBbeCVdAmC:b-h4fjyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2648)):*
> ```Go
> 			return err
> 		}
> 		subzoneID := 0
> ```

there's now a `SubzoneID` type in the `storage/reports` package, and a utility function to deal with the `+1` index to id conversion. Move those to `base` and use them.
___
*[pkg/sql/crdb_internal.go, line 2700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofGkaT-dC2sc59hpeW:-LofGkaT-dC2sc59hpeX:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2700)):*
> ```Go
> 
> 		// Figure out which zone and subzone this partition should correspond to.
> 		zoneID, zone, subzone, err := GetZoneConfigInTxn(ctx, p.txn, uint32(table.ID), index, r.Name, false /* getInheritedDefault */)
> ```

long line
___
*[pkg/sql/crdb_internal.go, line 2749 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofHZ4QDNXGQlJTYLxC:-LofHZ4QDNXGQlJTYLxD:b23cpsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2749)):*
> ```Go
> 	list_value  STRING,
> 	range_value STRING,
> 	zone_id INT,
> ```

please comment what these column reference - the `crdb_internal.zones` table
Better yet, have you checked if it's feasible to add a FK spec to this virtual table descriptor? Don't know if it's doable; you'll probably have to add an index to the `zones'` descriptor. But I think it's worth a shot to level up these tables.


<!-- Sent from Reviewable.io -->

2019-09-17 19:44 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaNE8oBGGREhGavuk-:-Lp-izdk1rIB_8UXK21_:b-6czx39) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/inherited/full

Better yet, I think we should rename the existing columns `raw_config` and call the new ones `config`. This is technically a breaking change, but people are gonna start getting what they were expecting in the column named `config`.
Also, I think we should get rid of the `[inherited_]config_sql` columns and turn `zoneConfigToSQL()` into a builtin function that takes the yaml.

Let's get more eyes on these schema changes - cc @bdarnell @knz 
</blockquote></details>

I'm not close to this area, but I think this table should be a more-or-less direct reflection of what's in the `ALTER... CONFIGURE ZONE` statements: only the raw local configs. Merging in the inherited configs should be the job of higher-level functionality like `SHOW ZONE CONFIGURATION` (which I think should show the final configuration after all inheritance and other processing).

I thing I agree in principle with a conversion function instead of having both sql and yaml columns, but I'm not sure I'd remove them now that they're already there. 


<!-- Sent from Reviewable.io -->

2019-09-17 20:20 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaNE8oBGGREhGavuk-:-Lp-sDHN8LTEYu2r9pnt:b-mu4r18) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm not close to this area, but I think this table should be a more-or-less direct reflection of what's in the `ALTER... CONFIGURE ZONE` statements: only the raw local configs. Merging in the inherited configs should be the job of higher-level functionality like `SHOW ZONE CONFIGURATION` (which I think should show the final configuration after all inheritance and other processing).

I thing I agree in principle with a conversion function instead of having both sql and yaml columns, but I'm not sure I'd remove them now that they're already there. 
</blockquote></details>

Ben, keep in mind that `crdb_internal.zones` is already a "higher-level" thing than `system.zones`, which gives you raw data. That one is a too raw (it gives you protos, and it doesn't expand subzones). But we'll hopefully change it.
Does this change your mind?


<!-- Sent from Reviewable.io -->

2019-09-17 20:25 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaNE8oBGGREhGavuk-:-Lp-tWZH9GKEQEnuk4Sd:b-hl3220) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Ben, keep in mind that `crdb_internal.zones` is already a "higher-level" thing than `system.zones`, which gives you raw data. That one is a too raw (it gives you protos, and it doesn't expand subzones). But we'll hopefully change it.
Does this change your mind?
</blockquote></details>

Maybe? I don't have strong opinions here because I don't know how this table is used. 


<!-- Sent from Reviewable.io -->

2019-09-24 19:48 UTC, rohany commented
friendly ping

2019-09-24 20:37 UTC, andreimatei approved these changes
LGTM

Please respond to review comments when you address them (e.g. "Done"). Otherwise I don't get any emails.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-:-LpZzUKD0ATA-Bc8XUTO:b-s6kq8t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2667 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LpZxkdW0eg1kwCSUWxj:-LpZxkdW0eg1kwCSUWxk:brgyxs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0745e5d0cb621ac7bd6c3a0c3b84d37cd52be6e/pkg/sql/crdb_internal.go#L2667)):*
> ```Go
> 			numColumns,
> 			colNames,
> 			tree.NewDString(buf.String()), /* holds the partition value */
> ```

nit: just put the column name here. As per the style guide, if you want to put more info (which is unnecessary in all the cases here), do it like `/* arg_name - more explanations */`.
The style guide talks specifically about argument names, but the extension column names for the variadic `addRow()` function is natural.
___
*[pkg/sql/show_zone_config.go, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LpZyzZQ2pNx7X2RAx_j:-LpZyzZQ2pNx7X2RAx_k:b-rnnldu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0745e5d0cb621ac7bd6c3a0c3b84d37cd52be6e/pkg/sql/show_zone_config.go#L40)):*
> ```Go
> 	{Name: "raw_config_yaml", Typ: types.String, Hidden: true},
> 	{Name: "raw_config_sql", Typ: types.String},
> 	{Name: "config_protobuf", Typ: types.Bytes, Hidden: true},
> ```

what about `config_protobuf`? If it stayed the raw one, call it `raw_config_protobuf`.


<!-- Sent from Reviewable.io -->

2019-09-24 20:50 UTC, rohany commented
Thanks for the very detailed reviews! I'll update the tests now and then merge this. Sorry, I thought that clicking "request review" again would send you an email.

2019-09-26 20:26 UTC, rohany commented
@andreimatei do you mind giving this another quick look before I merge? I had to make a couple more changes to get things to pass/avoid changing other tests too much.

2019-09-30 15:00 UTC, andreimatei approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-:-Lq1g07x436ie8gp7HMF:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 2167 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-Lq1fKS_9qYbSFQSXk9B:-Lq1fKSaDx8LorxCZhwa:buircv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7a8fe6c7ab7b40d624d2336d05fe7abcfe6f3a7/pkg/sql/crdb_internal.go#L2167)):*
> ```Go
> 
> 			// Write down information about the zone in the table.
> 			// TODO (rohany): We would like to just display information about these
> ```

many tests depend on these zone rows not existing for placeholder zones? Is it more than logic tests? (cause logic test golden files can be rewritten by running with `-rewrite`


<!-- Sent from Reviewable.io -->

2019-09-30 15:11 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @awoods187, @knz, @rohany, and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/partitioning, line 863 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaOoD86drBS6Hsod5u:-LouRYkA-KC733dq4IUJ:b32vhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/ccl/logictestccl/testdata/logic_test/partitioning#L863)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

hide your porn
</blockquote></details>

:(
___
*[pkg/sql/crdb_internal.go, line 2513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoX9IDU6-y6ClHG6rZ9:-LouRcHh77GXDZ-0dKCw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2513)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment this function and its arguments. What can be nil? The implementation is recursive, so this is quite important
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2537 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXAHCN1vWDWfMq6nQO:-LouRg-L3B3B3RZ7kDz_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2537)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls a better name than `a` :)
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXBKBJBlj6aMhgYw32:-LouRgmS48Cp_feijqWT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2546)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please comment around here that what this does is produce the `partition_value` column
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoX8JpK8UzksVWUyRCt:-LouRhQQ23vxTXavk0fC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2561)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment the `false` inline
https://github.com/cockroachdb/cockroach/blob/master/docs/style.md#inline-comments-for-arguments-to-function-calls

Or do everybody one better and, in a different commit, change `GetZoneConfigInTxn()` to take an enum instead of a naked bool so that callers are naturally readable.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXC3Ch-aehOI7oJHtq:-LouRiHl1UqBcrVGUXK6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2572)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think so
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXB2D69F4RqxIiy4R3:-LouT_0xEdvhgs1Ys0pz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2588)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment (or assign it to a variable before)
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2589 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoXB11S6zJxT9kkOvG4:-LouTl8-4btXpciQGJdA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c796e7970e85e47f40ab36c8833c6539840a4455/pkg/sql/crdb_internal.go#L2589)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaN8Mx1RAuJooZBy3L:-LouR_5R-Mjg6BTtLibg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

alignment
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LoaNE8oBGGREhGavuk-:-LouZIwWEZtvyZgZN7CN:bomm14u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2106)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/inherited/full

Better yet, I think we should rename the existing columns `raw_config` and call the new ones `config`. This is technically a breaking change, but people are gonna start getting what they were expecting in the column named `config`.
Also, I think we should get rid of the `[inherited_]config_sql` columns and turn `zoneConfigToSQL()` into a builtin function that takes the yaml.

Let's get more eyes on these schema changes - cc @bdarnell @knz 
</blockquote></details>

I hesitate on moving zoneConfigToSQL into a builtin function, as then we won't have access to the internal representation of the tree.ZoneSpecifier to correctly format/choose the version of the alter * command, and instead would have to let users choose the correct version instead.
___
*[pkg/sql/crdb_internal.go, line 2164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofEVMvEo-2v1RBdydu:-LouXbgpD1gVe2Hj-g9S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2164)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

How come we have to do this crap? Can we improve `completeZoneConfig` so that we don't have to do it?
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofJv2Y4XRgIWk0ZPOu:-LouX-xc5DmZcWMySszK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2170)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I say we get rid of this "subzone placeholder" concept (in general, but in particular for the purposes of this table). I don't understand why this concept exists, in general; there's nothing special about a "subzone placeholder" zone as opposed to any other zone. I think it had to exist in the dark times before cascading zone configs, but now classifying zones as "normal" and "placeholders" I believe is a useless distinction. I say let's just add rows to the `crdb_internal.zones` table for these placeholders.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2644 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofGEpbEh3HaPaKxzJb:-LouRhx93DDpZvDV0Eoi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2644)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 2648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40493#-LofGKOU3uuBbeCVdAmB:-LouSF-PEd2kpFkepU0t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd663109dec9467f0a22490cd763282eb96f90b2/pkg/sql/crdb_internal.go#L2648)):*
<details><sum [...]

2019-09-30 15:23 UTC, rohany commented
bors r=andreimatei

2019-09-30 16:02 UTC, merged