sql: Add telemetry for some partitioning UX improvements
cockroachdb/cockroach pull request #40839
Opened 2019-09-17 17:24 UTC by rohany

Add telemetry for the following operations:
* show partitions
* show ranges
* show locality
* show create table (intending to capture usage of new partitioning info)

Work towards https://github.com/cockroachlabs/registration/issues/228

Release justification: Low risk improvement to monitoring.

Release note: None

2019-09-17 17:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/40839)
<!-- Reviewable:end -->

2019-09-17 17:36 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40839)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @solongordon)

___
*[pkg/sql/sqltelemetry/show.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-Lp-HV3O8RF0oXWgwudF:-Lp-HV3O8RF0oXWgwudG:bc4k3yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62bfc45a13b417e09f1c5653e456c43cf90a7c4/pkg/sql/sqltelemetry/show.go#L19)):*
> ```Go
> )
> 
> var showTelemetryCounters map[string]telemetry.Counter
> ```

this might be a little safer with an enum type as the key (with a `String()` method) instead of a string key. that way if it's used in different contexts it's harder to mess up the key name
___
*[pkg/sql/sqltelemetry/show.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-Lp-GvC28waAsbIMamOo:-Lp-GvC28waAsbIMamOp:b-4dm4zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62bfc45a13b417e09f1c5653e456c43cf90a7c4/pkg/sql/sqltelemetry/show.go#L29)):*
> ```Go
> 		telemetry.Inc(counter)
> 	} else {
> 		showTelemetryCounters[showType] = telemetry.GetCounterOnce(fmt.Sprintf("sql.show.%s", showType))
> ```

I think theoretically there is a race condition here, since two threads could be calling IncrementShowCounter for the same string, and both could end up in this branch. `GetCounterOnce` will panic if the counter exists

I think it would be safest to do all the `GetCounterOnce` calls in the `init` function. for example, take a look at pkg/sql/opt/telemetry.go

That would also be easier to do if there were an enum type and the `init` function just iterates over the enum values.


<!-- Sent from Reviewable.io -->

2019-09-17 17:51 UTC, rohany reviewed
Good catches @rafiss. I wanted to have this so that you could just add different telemetry counters without having to touch show.go, but it seems better to explicitly have to add an enum to opt in. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-:-Lp-LJlZANungQ7nYQ2o:b-kpq5b9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/sqltelemetry/show.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-Lp-HV3O8RF0oXWgwudF:-Lp-LIvI-O_6Gfno49cF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62bfc45a13b417e09f1c5653e456c43cf90a7c4/pkg/sql/sqltelemetry/show.go#L19)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this might be a little safer with an enum type as the key (with a `String()` method) instead of a string key. that way if it's used in different contexts it's harder to mess up the key name
</blockquote></details>

Done.
___
*[pkg/sql/sqltelemetry/show.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-Lp-GvC28waAsbIMamOo:-Lp-LJG4A5znAbyGjLPF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b62bfc45a13b417e09f1c5653e456c43cf90a7c4/pkg/sql/sqltelemetry/show.go#L29)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

I think theoretically there is a race condition here, since two threads could be calling IncrementShowCounter for the same string, and both could end up in this branch. `GetCounterOnce` will panic if the counter exists

I think it would be safest to do all the `GetCounterOnce` calls in the `init` function. for example, take a look at pkg/sql/opt/telemetry.go

That would also be easier to do if there were an enum type and the `init` function just iterates over the enum values.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-18 14:54 UTC, rafiss approved these changes
looks great!

> Reviewed 3 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40839#-:-Lp3rTAQ4_SbdiL3KjH4:b6lqmcl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)



<!-- Sent from Reviewable.io -->

2019-09-18 15:11 UTC, rohany commented
bors r+

2019-09-18 15:47 UTC, merged