sql: fix bug with needed column families and nulls
cockroachdb/cockroach pull request #41136
Opened 2019-09-26 19:55 UTC by solongordon

When doing point lookups, we have logic to only scan column families
which are needed for the requested columns. However, this logic had a
bug concerning NULL values. Column families other than the one with ID 0
do not store a row if all their columns are NULL. This means that if you
only scan those families, you can't distinguish between the absence of a
row and all NULL values. Since we didn't account for this, some queries
which should have returned an all NULL row were instead returning no
row. See the referenced issue for specific examples.

I added new logic to determine whether it is necessary to scan column
family 0. It must be scanned if any of the following is true:
- It includes one of the needed columns which is not in the primary key.
- It includes one of the needed columns which uses composite encoding.
- All the columns in the other needed families are nullable.

Fixes #41007

Release note: None

2019-09-26 19:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41136)
<!-- Reviewable:end -->

2019-09-26 20:04 UTC, solongordon commented
This needs more tests to cover the weird cases, but I could use some initial feedback on whether this is reasonable for 19.2. There is a simpler, almost one-line fix which is to always include column family 0 in the needed columns no matter what. That would work fine, but it ignores some cases where we can safely omit that column family.

2019-09-26 20:21 UTC, solongordon commented
@rohany put in a vote for doing the one-liner fix for 19.2 and saving the more sophisticated version for 20.1. Unless @jordanlewis feels different I'll go with that.

2019-09-26 20:29 UTC, solongordon commented
cc @nvanbenschoten since I believe he relies on this optimization for benchmarks like YCSB and TPCC. How bad is it for those benchmarks if we always scan column family 0?

2019-09-26 20:38 UTC, nvanbenschoten commented
> How bad is it for those benchmarks if we always scan column family 0?

I'm pretty confident that they were already scanning column family 0. I've certainly seen `UPDATE` statements in YCSB turned into a trace with `2 Scan`, followed by `1 Put, 1 EndTxn`. Is it possible that we were already handling this properly in some cases?

2019-09-26 20:54 UTC, solongordon commented
If we were already handling it properly I think it would be because the primary key column was included in the list of "needed" columns passed to `NeededColumnFamilyIDs(...)`. (This PR has an optimization for omitting column family 0 if its needed columns can be decoded from the key, but that's new.)

2019-09-26 20:57 UTC, solongordon commented
But that's good news if we're unlikely to tank our benchmarks by doing the simple fix for 19.2.

2019-09-30 18:43 UTC, solongordon commented
OK, I opened a new PR (#41212) for the simpler fix. I'll save this one for after we create the release-19.2 branch.

2019-11-14 19:16 UTC, rohany requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/sqlbase/index_encoding.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41136#-LtfK1IR7YSf27Wy7lU_:-LtfK1IR7YSf27Wy7lUa:bjwusqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee4c0416589ebac92ad3f36632b9ca42559dd4/pkg/sql/sqlbase/index_encoding.go#L251)):*
> ```Go
> 	var family0 *ColumnFamilyDescriptor
> 
> 	// Iterate over the non-zero column families to find which ones contain needed
> ```

I'd suggest changing this to something like "columns families with id != 0" instead of non-zero. Non-zero seems to say something about the size of the family.
___
*[pkg/sql/sqlbase/index_encoding.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41136#-LtfKyeb2AoDvij0jbqG:-LtfKyecErGOgc8DpTzW:b-8w7sgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee4c0416589ebac92ad3f36632b9ca42559dd4/pkg/sql/sqlbase/index_encoding.go#L295)):*
> ```Go
> 	// contains needed columns which are either not in the primary index or
> 	// composite values. (Non-composite primary index columns can be decoded from
> 	// the key.)
> ```

don't you also need to add a check if any of the columns from neededCols are in the first family here?


<!-- Sent from Reviewable.io -->

2020-02-04 19:31 UTC, closed without merging