sql: Fix settings zone config bug with zone placeholders
cockroachdb/cockroach pull request #41261
Opened 2019-10-02 15:56 UTC by rohany

This PR fixes a bug where zone configurations applied on a table after
setting a zone configuration on a index would seemingly be ignored
unless the num_replicas field was also set on the table.

In the future, it seems like we should remove the notion of subzone
placeholders rather than using fixes like this.

Fixes #38074.

Release justification: Fixes a bug in zone configurations

Release note: None

2019-10-02 15:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41261)
<!-- Reviewable:end -->

2019-10-02 15:56 UTC, rohany commented
I'll update this PR with a test shortly.

2019-10-02 17:34 UTC, solongordon requested changes
The fix makes sense to me after puzzling over it a bit. Couple minor requests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-:-LqCXDii1xqQuxu4PgNp:bs4wvhg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rohany, and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 790 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCVLBR3oO05RIItLbo:-LqCVLBR3oO05RIItLbp:bmzdwkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/ccl/logictestccl/testdata/logic_test/zone#L790)):*
> ```
> ALTER TABLE t38074 CONFIGURE ZONE USING gc.ttlseconds = 70000
> 
> # Ensure that the zone configurations for the table are not ignore due to being placeholders.
> ```

nit: s/ignore/ignored/

Also maybe a bit clearer to say "Ensure that the table-level zone configuration is no longer a placeholder."
___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCV9w20RqhnXJSNDWy:-LqCV9w20RqhnXJSNDWz:b7c9cdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/ccl/logictestccl/testdata/logic_test/zone#L792)):*
> ```
> # Ensure that the zone configurations for the table are not ignore due to being placeholders.
> query TT
> SELECT table_name, index_name FROM crdb_internal.zones WHERE table_name='t38074'
> ```

Would it be worth verifying the zone config contents as well?
___
*[pkg/sql/set_zone_config.go, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCWjbF6Xw0_kJhPzQx:-LqCWjbF6Xw0_kJhPzQy:b1ck2t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/sql/set_zone_config.go#L496)):*
> ```Go
> 				completeZone = &newZone
> 				partialZone = &finalZone
> 				// If we are writing to a zone that is not a subzone, we need to make sure that the zone
> ```

Maybe clearer: "Since we are writing to a zone that is not a subzone...". Your comment confused me a bit because it sounded like we're still not sure if this is a subzone or not.
___
*[pkg/sql/set_zone_config.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCUfCi4H1QzQEXZ5Y1:-LqCUfCi4H1QzQEXZ5Y2:b-i5v5ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/sql/set_zone_config.go#L499)):*
> ```Go
> 				// config is not considered a placeholder anymore. If the settings applied to this zone
> 				// don't touch the NumReplicas field, set it to nil so that the zone isn't considered a
> 				// placeholder anymore.
> ```

Nit: Please wrap comments at 80 chars when possible.


<!-- Sent from Reviewable.io -->

2019-10-02 21:27 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41261)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 792 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCV9w20RqhnXJSNDWy:-LqDMdbh3n9RtLAMK2ED:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/ccl/logictestccl/testdata/logic_test/zone#L792)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Would it be worth verifying the zone config contents as well?
</blockquote></details>

Done.
___
*[pkg/sql/set_zone_config.go, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCWjbF6Xw0_kJhPzQx:-LqDLQ4D6BBQuWFsAay-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/sql/set_zone_config.go#L496)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe clearer: "Since we are writing to a zone that is not a subzone...". Your comment confused me a bit because it sounded like we're still not sure if this is a subzone or not.
</blockquote></details>

Done.
___
*[pkg/sql/set_zone_config.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-LqCUfCi4H1QzQEXZ5Y1:-LqDLbu08JN9wUlMXC7O:b4zj676) ([raw file](https://github.com/cockroachdb/cockroach/blob/99ad178079ca6cedb2bc35f7715b5bce0a675779/pkg/sql/set_zone_config.go#L499)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: Please wrap comments at 80 chars when possible.
</blockquote></details>

seems like my editor was misconfigured


<!-- Sent from Reviewable.io -->

2019-10-02 21:42 UTC, solongordon approved these changes
Would you please add a release note describing the bug fix? Otherwise this is good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-:-LqDQ1hXCYqYPXiiW6yz:b-5vpzxt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)



<!-- Sent from Reviewable.io -->

2019-10-02 22:08 UTC, andreimatei reviewed
i'm gonna sit this one out unless you need my review in particular

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41261#-:-LqDW-Bm2EEJAADOJqYa:bwrk042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)



<!-- Sent from Reviewable.io -->

2019-10-03 14:53 UTC, rohany commented
bors r=solongordon

2019-10-03 15:15 UTC, merged