sql/sem/builtins: Add bit_and and bit_or.
cockroachdb/cockroach pull request #41334
Opened 2019-10-04 17:33 UTC by elliotcourant

Adds support for the PostgreSQL functions bit_and and bit_or.

This also adds some helper functions for aggregation tests to make sure
that null values are handled. No tests outside of the scope of bit_and
and bit_or were modified yet though.

Resolves: #41273

2019-10-04 17:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41334)
<!-- Reviewable:end -->

2019-10-04 18:10 UTC, rafiss submitted a review, later dismissed
thank you very much for your contribution!

please add lines like the following to your commit message and PR description:

> Release justification: Low risk change that increases Postgres compatibility.
> Release note (sql change): Support bit_and and bit_or aggregate functions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqMxGph15pKzO55uOsg:b-y78qov)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant and @rohany)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMx8r00p4UioPyq3jO:-LqMx8r00p4UioPyq3jP:bag22qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L450)):*
> ```Go
> const sizeOfIntXorAggregate = int64(unsafe.Sizeof(intXorAggregate{}))
> const sizeOfJSONAggregate = int64(unsafe.Sizeof(jsonAggregate{}))
> const sizeOfIntBitAggregate = int64(unsafe.Sizeof(bitAndIntAggregate{}))
> ```

Although they are the same size, and it's unlikely that would change, I feel it would be safer to have a separate const for each bitwise int aggregate.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMwRKM01FN8gIgow40:-LqMwRKM01FN8gIgow41:brkhaq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L214)):*
> ```Go
> // returned. Use this to ensure proper partial null
> // handling of aggregations.
> func makeTestWillNullDatum(count int, maker func(count int) []tree.Datum) []tree.Datum {
> ```

Should this be `makeTestWithNullDatum`? (and same in the comment)


<!-- Sent from Reviewable.io -->

2019-10-04 18:18 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rohany)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMx8r00p4UioPyq3jO:-LqMzeg8AtDkJFpcektg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L450)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Although they are the same size, and it's unlikely that would change, I feel it would be safer to have a separate const for each bitwise int aggregate.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMwRKM01FN8gIgow40:-LqMzff9EEML0brvusJ3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L214)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Should this be `makeTestWithNullDatum`? (and same in the comment)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-04 18:39 UTC, yuzefovich requested changes
Thanks a lot for taking on this issue!

I left several comments, and I also think that a few tests are missing that would catch the problem I described below (or prove me wrong). I'd add a couple of test case into `pkg/sql/logictest/testdata/logic_test/aggregate`. This is a file of "logic tests" for aggregate builtins (there is a comment about such tests in `pkg/sql/logictest/logic.go`). Please let us know if you have any questions about the format of the logic tests.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqN2J-386bmqAOgXb9q:b-ya02xj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, and @rohany)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMvqCY20-ar0WZ5p-r:-LqMvqCY20-ar0WZ5p-s:b-aw7gvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L132)):*
> ```Go
> 	"bit_and": makeBuiltin(aggProps(),
> 		makeAggOverload([]*types.T{types.Int}, types.Int, newBitAndIntAggregate,
> 			"Calculates the bitwise AND of all non-null input values, or null if none"),
> ```

[nit]: missing period.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMvrp67vyQx7sZNELg:-LqMvrp67vyQx7sZNELh:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L137)):*
> ```Go
> 	"bit_or": makeBuiltin(aggProps(),
> 		makeAggOverload([]*types.T{types.Int}, types.Int, newBitOrIntAggregate,
> 			"Calculates the bitwise OR of all non-null input values, or null if none"),
> ```

ditto
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 728 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN-eUkAAk7Ug0lwYz5:-LqMwmin5H-Tg_CiTblo:b2fpljr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L728)):*
> ```Go
> }
> 
> type bitAndIntAggregate struct {
> ```

[super nit]: naming of other aggregates seem to follow a pattern as "argument type _ aggregate name _ word `Aggregate`", so `intBitAndAggregate` seems to align better. The same goes to `bit_or`.

Also, personally, I'd omit the `int` part entirely since there are no other types for which `bit_and` operates on, but it's up to you.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqMzK1d3BwC1UTRj4z8:bsdkhwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
> ```Go
> 	}
> 	a.sawNonNull = true
> 	a.result = a.result & int64(*datum.(*tree.DInt))
> ```

I think this might not be correct: when the first non-null datum is added, then `a.result` should be all zeroes, and AND'ing it with a datum will also produce all zeroes, and the same cycle will repeat for all consequent datums. I believe we need to check whether we saw non-null already, if we haven't, then we would assign datum to the result, and if we have, then we would actually AND.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 785 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN-0xG9YVyIbpySMeB:-LqN-0xG9YVyIbpySMeC:b2sxvdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L785)):*
> ```Go
> 	}
> 	a.sawNonNull = true
> 	a.result = a.result | int64(*datum.(*tree.DInt))
> ```

I think the same comment should be applied here from above: although this code does seem to behave correctly (as long as `a.result` is all zeroes when first non-null datum is added), I think it'd be beneficial to explicitly check for the first non-null.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN2Ays9XxpI4f0c5R6:-LqN2Ays9XxpI4f0c5R7:brucdt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ff409bd7b2877c2a5644f0f4152ffd334f66d25/pkg/sql/sem/builtins/aggregate_builtins.go#L768)):*
> ```Go
> func (a *bitAndIntAggregate) Size() int64 {
> 	// This aggregation is the same size as the OR aggregate.
> 	return sizeOfIntAndBitAggregate
> ```

[nit]: the comment above is unnecessary now.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN2EFZ8AdmsO8m8yvc:-LqN2EFZ8AdmsO8m8yvd:b-n1eqsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ff409bd7b2877c2a5644f0f4152ffd334f66d25/pkg/sql/sem/builtins/aggregate_builtins.go#L810)):*
> ```Go
> func (a *bitOrIntAggregate) Size() int64 {
> 	// This aggregation is the same size as the AND aggregate.
> 	return sizeOfIntOrBitAggregate
> ```

ditto for the comment.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN0YoG1umqqktDpnC2:-LqN0YoG1umqqktDpnC3:b-6fihmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L191)):*
> ```Go
> // makeNullTestDatum will create an array of only DNull
> // values to make sure the aggregation handles only nulls
> func makeNullTestDatum(count int) []tree.Datum {
> ```

[nit]: missing period above.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN1Wx5ALkK_s6MhAvm:-LqN1Wx6AAM02--Dhx2v:b5ns33v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L217)):*
> ```Go
> 	rng, _ := randutil.NewPseudoRand()
> 
> 	values := append(maker(count-1), nil)
> ```

I think this code is a little more complicated than necessary - I'd just generate an array with exactly`count` datums and then would override one of them with `DNull`. Also, a nit: you could use `rng.Intn(count)` to generate the index.


<!-- Sent from Reviewable.io -->

2019-10-04 18:57 UTC, elliotcourant reviewed
I will add those tonight.

Also I'll make the changes suggested in all of the other comments here as well. 

Thank you very much!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqN3DBi46b6oeYC8Tg5:b-21f8qo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqN6x_Y8kDrf4A3b8p2:b-4f2uxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this might not be correct: when the first non-null datum is added, then `a.result` should be all zeroes, and AND'ing it with a datum will also produce all zeroes, and the same cycle will repeat for all consequent datums. I believe we need to check whether we saw non-null already, if we haven't, then we would assign datum to the result, and if we have, then we would actually AND.
</blockquote></details>

I think you are correct, I can make that adjustment for this aggregate.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN1Wx5ALkK_s6MhAvm:-LqN7KkR4s4yRvRL_lLU:bfivohm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L217)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this code is a little more complicated than necessary - I'd just generate an array with exactly`count` datums and then would override one of them with `DNull`. Also, a nit: you could use `rng.Intn(count)` to generate the index.
</blockquote></details>

That is much simpler and easier to read.


<!-- Sent from Reviewable.io -->

2019-10-04 21:06 UTC, elliotcourant reviewed
It looks like BitAnd and BitOr is already defined for non aggregate function syntax here: `pkg/sql/opt/ops/scalar.opt:492`
Given that, what should the naming convention be for the aggregate functions? `AggBitAnd` and `AggBitOr` maybe?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqNYGwg5bCf0MEkLWJg:bi7uc2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMvqCY20-ar0WZ5p-r:-LqNBtV752AtL9zOUDlY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L132)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing period.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMvrp67vyQx7sZNELg:-LqNBtw_EFv4f4UrHF5w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L137)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-04 21:17 UTC, yuzefovich reviewed
How about `bitAndAggregate` and `bitOrAggregate`?

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqNbefYAcHkmEAubMip:b-8f6zg8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-10-04 23:31 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 728 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN-eUkAAk7Ug0lwYz5:-LqO5NPW42dnmY7-aLag:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L728)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: naming of other aggregates seem to follow a pattern as "argument type _ aggregate name _ word `Aggregate`", so `intBitAndAggregate` seems to align better. The same goes to `bit_or`.

Also, personally, I'd omit the `int` part entirely since there are no other types for which `bit_and` operates on, but it's up to you.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqO5qX39mKlf2IWWozm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

I think you are correct, I can make that adjustment for this aggregate.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 785 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN-0xG9YVyIbpySMeB:-LqO4mpH7wPT9zQBsrBF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L785)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think the same comment should be applied here from above: although this code does seem to behave correctly (as long as `a.result` is all zeroes when first non-null datum is added), I think it'd be beneficial to explicitly check for the first non-null.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN2Ays9XxpI4f0c5R6:-LqO5rLjBNo8nY5I_NMT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ff409bd7b2877c2a5644f0f4152ffd334f66d25/pkg/sql/sem/builtins/aggregate_builtins.go#L768)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment above is unnecessary now.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 810 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN2EFZ8AdmsO8m8yvc:-LqO5sk54WZWXtJuqwW4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ff409bd7b2877c2a5644f0f4152ffd334f66d25/pkg/sql/sem/builtins/aggregate_builtins.go#L810)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto for the comment.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN0YoG1umqqktDpnC2:-LqO5vqC51mT8wSfEfs9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L191)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing period above.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqN1Wx5ALkK_s6MhAvm:-LqO5x2W8bvcpjYUSkOF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins_test.go#L217)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

That is much simpler and easier to read.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-04 23:51 UTC, elliotcourant commented
I didn't mean to have it remove sql-opt-prs from the reviewers. I'm not sure how I could add that back.

2019-10-04 23:55 UTC, yuzefovich reviewed
No worries, I added it back.

The PR is looking great! I left a few other comments. Also consider squashing the commits into a single one.

> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqOBLOKC_sJ5H7twVtw:bjvvo3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 430 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqO7yNB8wtpTb6TxqhM:-LqO7yNC1GliDPh3CZBN:bcioimi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a857de7405e9064295788c96961fe7700791920/pkg/sql/execinfrapb/processors_sql.proto#L430)):*
> ```protobuf
>     JSONB_AGG = 20;
>     STRING_AGG = 21;
> ```

[nit]: I'd remove this extra line.
___
*[pkg/sql/opt/operator.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqO8OFSBVV_5wz56zL-:-LqO8OFSBVV_5wz56zL0:buhjhcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a857de7405e9064295788c96961fe7700791920/pkg/sql/opt/operator.go#L176)):*
> ```Go
> 	ArrayAggOp:        "array_agg",
> 	AvgOp:             "avg",
> 	BitAndAggregateOp: "bit_and",
> ```

[nit]: although I suggested `BitAndAggregate` as the name, the code around here in the optimizer seems to be using a different convention, so your suggestion of `BitAndAgg` and `BitOrAgg` would fit better.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMx8r00p4UioPyq3jO:-LqOAF2K0pMFSL2WrryQ:b4sb8zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L450)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[nit]: I'd rename the constants to match the aggregate names (i.e. `s/sizeOfIntAndBitAggregate/sizeOfBitAndAggregate/` and the same for OR).
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqO9FU-6oIcPxK9R5FI:b-rfonlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this code can be simplified a bit. How about something like this
```
if datum == tree.DNull {
  return nil
}
if !a.sawNonNull {
  // This is the first non-null datum, so we simply assign it to the result.
  a.result = int64(*datum.(*tree.DInt))
  a.sawNonNull = true
  return nil
}
// This is not the first non-null datum, so we actually AND it with the
// aggregate so far.
a.result = a.result & int64(*datum.(*tree.DInt))
return nil
```
This way we can eliminate an extra `a.sawValue`.


<!-- Sent from Reviewable.io -->

2019-10-05 00:10 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqOExUKDNkpcYQJkiaJ:but4e1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this code can be simplified a bit. How about something like this
```
if datum == tree.DNull {
  return nil
}
if !a.sawNonNull {
  // This is the first non-null datum, so we simply assign it to the result.
  a.result = int64(*datum.(*tree.DInt))
  a.sawNonNull = true
  return nil
}
// This is not the first non-null datum, so we actually AND it with the
// aggregate so far.
a.result = a.result & int64(*datum.(*tree.DInt))
return nil
```
This way we can eliminate an extra `a.sawValue`.
</blockquote></details>

Additionally, we usually use tree.AsDInt, or tree.MustBeDInt rather than directly doing the interface switch here, in order to have more consistent error messages.


<!-- Sent from Reviewable.io -->

2019-10-05 00:19 UTC, elliotcourant reviewed
:+1: I will squash all my commits with this next push. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LqOH5aZ1Q6iyMYcQgZq:bwzr4df)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors_sql.proto, line 430 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqO7yNB8wtpTb6TxqhM:-LqOEIvp2AVBRaeTVVgH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a857de7405e9064295788c96961fe7700791920/pkg/sql/execinfrapb/processors_sql.proto#L430)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd remove this extra line.
</blockquote></details>

Done.
___
*[pkg/sql/opt/operator.go, line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqO8OFSBVV_5wz56zL-:-LqOFoZX2CkDu-s3ICGx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a857de7405e9064295788c96961fe7700791920/pkg/sql/opt/operator.go#L176)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: although I suggested `BitAndAggregate` as the name, the code around here in the optimizer seems to be using a different convention, so your suggestion of `BitAndAgg` and `BitOrAgg` would fit better.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqOGYDXE3am8re8sMe8:bdnf43y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Additionally, we usually use tree.AsDInt, or tree.MustBeDInt rather than directly doing the interface switch here, in order to have more consistent error messages.
</blockquote></details>

I like that way of doing it, it makes it easier to read. And I've changed it to use `tree.MustBeDInt`.

As another option, right now the `result` variable is stored as an int64, but I think it would make more sense to store it as a DInt and then I wouldn't need to cast it to int64 when doing operations.

And when returning the result it would be easier as well. What are your thoughts?


<!-- Sent from Reviewable.io -->

2019-10-05 01:28 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMx8r00p4UioPyq3jO:-LqOWtwO7shOf14MvqMC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L450)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd rename the constants to match the aggregate names (i.e. `s/sizeOfIntAndBitAggregate/sizeOfBitAndAggregate/` and the same for OR).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-07 16:42 UTC, yuzefovich reviewed
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-Lqb38_i-CospbxscqK6:b94ez8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

I like that way of doing it, it makes it easier to read. And I've changed it to use `tree.MustBeDInt`.

As another option, right now the `result` variable is stored as an int64, but I think it would make more sense to store it as a DInt and then I wouldn't need to cast it to int64 when doing operations.

And when returning the result it would be easier as well. What are your thoughts?
</blockquote></details>

It seems like other aggregates use `int64` and alike internally, so I'd lean towards doing the same.

I wonder if there is any performance difference between the two (if you're up to checking it out, you could write a benchmark in `aggregate_builtins_test`, and then run it with `int64` and `DInt`. We actually have a tool that helps with comparing such changes - it's in `scripts/bench`. The way you run it is you have your `old` branch, then you check out `new` branch and make the changes that you want to compare against the "old" ones, and then run something like `BENCHES=BenchmarkBitAndAggregate PKG=./pkg/sql/sem/builtins ./scripts/bench old new`. The tool will run the specified benchmark 10 times (by default) on each of the branches and will spit out the comparison so that it is very easy to see what impact the changes had.). 

Also, I still think that `sawValue` is unnecessary - what does it offer that `sawNonNull` doesn't already provide?


<!-- Sent from Reviewable.io -->

2019-10-09 00:19 UTC, elliotcourant commented
Sorry for the slow follow up on this. I'll play around with benchmarks a bit but I don't think it will lead to any difference that would be anything more than negligible. But I'll check it out for curiosity!

And yes you are correct with the sawValue and sawNull, those don't need to be separate. I'll make my changes tomorrow afternoon! Thank you!

2019-10-11 19:12 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwE2VAEdY3ouwDI15_:-LqwE2VB27_h7Gm_6_aW:b-pjls44) (no related file):*
I believe this is done now? If anyone has anymore feedback I'd be more than happy to make any more adjustments!

---
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqwDmkDExW8DevuEFLZ:b8orn5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It seems like other aggregates use `int64` and alike internally, so I'd lean towards doing the same.

I wonder if there is any performance difference between the two (if you're up to checking it out, you could write a benchmark in `aggregate_builtins_test`, and then run it with `int64` and `DInt`. We actually have a tool that helps with comparing such changes - it's in `scripts/bench`. The way you run it is you have your `old` branch, then you check out `new` branch and make the changes that you want to compare against the "old" ones, and then run something like `BENCHES=BenchmarkBitAndAggregate PKG=./pkg/sql/sem/builtins ./scripts/bench old new`. The tool will run the specified benchmark 10 times (by default) on each of the branches and will spit out the comparison so that it is very easy to see what impact the changes had.). 

Also, I still think that `sawValue` is unnecessary - what does it offer that `sawNonNull` doesn't already provide?
</blockquote></details>

I've refactored this, must not have been thinking. I've also reverted it back to the int64 type as well.


<!-- Sent from Reviewable.io -->

2019-10-11 19:30 UTC, yuzefovich reviewed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwE2VAEdY3ouwDI15_:-LqwI3qP90QP3Q1HSfX4:b694c3i) (no related file):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

I believe this is done now? If anyone has anymore feedback I'd be more than happy to make any more adjustments!
</blockquote></details>

One last nit from me and it's ready to go in :)

---
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqMzK1d3BwC1UTRj4z7:-LqwGmlT3gQMLcOr0SXV:b9ldnc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1ec626fdc2da193c110398ad9ea0ce5f38fcd69/pkg/sql/sem/builtins/aggregate_builtins.go#L743)):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

I've refactored this, must not have been thinking. I've also reverted it back to the int64 type as well.
</blockquote></details>

Cool, thanks.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 747 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwH__uBSJFmABWz9Wd:-LqwH__uBSJFmABWz9We:biodmsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbc4773c85cb64086ec45e024d1caaf56a6a324c/pkg/sql/sem/builtins/aggregate_builtins.go#L747)):*
> ```Go
> 	// store the provided value for the
> 	// aggregation.
> 	if !a.sawNonNull {
> ```

[nit]: I'd remove the comment from above and put it inside this `if`. Also, I'd simplify the comment a bit, maybe to something like `This is the first non-null datum, so we simply store the provided value for the aggregation.`.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 799 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwI24p5YpKGZlerWzY:-LqwI24p5YpKGZlerWzZ:bjvmrku) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbc4773c85cb64086ec45e024d1caaf56a6a324c/pkg/sql/sem/builtins/aggregate_builtins.go#L799)):*
> ```Go
> 	// aggregation.
> 	if !a.sawNonNull {
> 		a.result = int64(tree.MustBeDInt(datum))
> ```

ditto for the comment


<!-- Sent from Reviewable.io -->

2019-10-15 18:44 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwE2VAEdY3ouwDI15_:-LrFj6mp7V9eb-uI_5nZ:b2m3ov7) (no related file):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

One last nit from me and it's ready to go in :)
</blockquote></details>

Updated those comments as suggested! :+1: 

---
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 747 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwH__uBSJFmABWz9Wd:-LrFigcT8ZE29CdxaPva:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbc4773c85cb64086ec45e024d1caaf56a6a324c/pkg/sql/sem/builtins/aggregate_builtins.go#L747)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd remove the comment from above and put it inside this `if`. Also, I'd simplify the comment a bit, maybe to something like `This is the first non-null datum, so we simply store the provided value for the aggregation.`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 799 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwI24p5YpKGZlerWzY:-LrFifmF3rl9LaDZV4K8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cbc4773c85cb64086ec45e024d1caaf56a6a324c/pkg/sql/sem/builtins/aggregate_builtins.go#L799)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto for the comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-15 19:48 UTC, yuzefovich approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwE2VAEdY3ouwDI15_:-LrFwoPS3UXK73szCEUc:bom92ta) (no related file):*
<details><summary><i>Previously, elliotcourant (Elliot Courant) wrote…</i></summary><blockquote>

Updated those comments as suggested! :+1: 
</blockquote></details>

Thanks a lot! It now <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

We do need to fix a couple of issues to appease the build:
- there is an issue with identation:
```
=== PAUSE TestLint/TestGofmtSimplify
        lint_test.go:1027: 
            /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go
            diff -u /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go.orig /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go
            --- /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go.orig	2019-10-15 19:06:21.669836133 +0000
            +++ /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go	2019-10-15 19:06:21.669836133 +0000
            @@ -173,8 +173,8 @@
             var AggregateOpReverseMap = map[Operator]string{
             	ArrayAggOp:        "array_agg",
             	AvgOp:             "avg",
            -	BitAndAggOp:         "bit_and",
            -	BitOrAggOp:          "bit_or",
            +	BitAndAggOp:       "bit_and",
            +	BitOrAggOp:        "bit_or",
             	BoolAndOp:         "bool_and",
             	BoolOrOp:          "bool_or",
             	ConcatAggOp:       "concat_agg",
```
- there is an issue with generated comments (maybe `make buildshort` is needed to regenerate the comments or you need to rebase on top of the current master)
```
Conflicting files
docs/generated/sql/aggregates.md
```
- `Release justification` is no longer needed, so please remove it from the commit's message and PR description.

Also, note that we have some flakiness right now with the build system, so we might need to wait a day or two for those issues to be resolved before merging this.

---


<!-- Sent from Reviewable.io -->

2019-10-15 21:38 UTC, elliotcourant reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss, @rohany, and @yuzefovich)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LqwE2VAEdY3ouwDI15_:-LrGLb-wEYsWc3tnyYmh:b-4b1kul) (no related file):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Thanks a lot! It now :lgtm:

We do need to fix a couple of issues to appease the build:
- there is an issue with identation:
```
=== PAUSE TestLint/TestGofmtSimplify
        lint_test.go:1027: 
            /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go
            diff -u /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go.orig /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go
            --- /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go.orig	2019-10-15 19:06:21.669836133 +0000
            +++ /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/operator.go	2019-10-15 19:06:21.669836133 +0000
            @@ -173,8 +173,8 @@
             var AggregateOpReverseMap = map[Operator]string{
             	ArrayAggOp:        "array_agg",
             	AvgOp:             "avg",
            -	BitAndAggOp:         "bit_and",
            -	BitOrAggOp:          "bit_or",
            +	BitAndAggOp:       "bit_and",
            +	BitOrAggOp:        "bit_or",
             	BoolAndOp:         "bool_and",
             	BoolOrOp:          "bool_or",
             	ConcatAggOp:       "concat_agg",
```
- there is an issue with generated comments (maybe `make buildshort` is needed to regenerate the comments or you need to rebase on top of the current master)
```
Conflicting files
docs/generated/sql/aggregates.md
```
- `Release justification` is no longer needed, so please remove it from the commit's message and PR description.

Also, note that we have some flakiness right now with the build system, so we might need to wait a day or two for those issues to be resolved before merging this.
</blockquote></details>

Fixed the indentation and rebased onto master so the merge conflict should now be resolved, also updated the commit message!

---


<!-- Sent from Reviewable.io -->

2019-10-15 21:44 UTC, yuzefovich reviewed
There is one more thing (sorry for not spotting it earlier).

> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LrGNIGh4yFTThDnmpjJ:b-kbe7tt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @elliotcourant, @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 81 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LrGMuy05LMdG7Dg0q6m:-LrGMuy05LMdG7Dg0q6n:biqtjto) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ffdaaf82eae695cecd49b874198a903ef3c1db6/pkg/sql/sem/builtins/aggregate_builtins_test.go#L81)):*
> ```Go
> }
> 
> func TestBitAndIntResultDeepCopy(t *testing.T) {
> ```

These two tests are missing a leaktest:
```
[21:41:44][Ensure generated code is up-to-date] --- a/pkg/sql/sem/builtins/aggregate_builtins_test.go
[21:41:44][Ensure generated code is up-to-date] +++ b/pkg/sql/sem/builtins/aggregate_builtins_test.go
[21:41:44][Ensure generated code is up-to-date] @@ -79,6 +79,7 @@ func TestAvgDecimalResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  }
[21:41:44][Ensure generated code is up-to-date]  
[21:41:44][Ensure generated code is up-to-date]  func TestBitAndIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date] +	defer leaktest.AfterTest(t)()
[21:41:44][Ensure generated code is up-to-date]  	t.Run("all null", func(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  		testAggregateResultDeepCopy(t, newBitAndAggregate, makeNullTestDatum(10))
[21:41:44][Ensure generated code is up-to-date]  	})
[21:41:44][Ensure generated code is up-to-date] @@ -91,6 +92,7 @@ func TestBitAndIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  }
[21:41:44][Ensure generated code is up-to-date]  
[21:41:44][Ensure generated code is up-to-date]  func TestBitOrIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date] +	defer leaktest.AfterTest(t)()
[21:41:44][Ensure generated code is up-to-date]  	t.Run("all null", func(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  		testAggregateResultDeepCopy(t, newBitOrAggregate, makeNullTestDatum(10))
[21:41:44][Ensure generated code is up-to-date]  	})
```
Basically you need to add `defer leaktest.AfterTest(t)()` as the first line of `TestBitAndIntResultDeepCopy` and `TestBitOrIntResultDeepCopy`.


<!-- Sent from Reviewable.io -->

2019-10-15 22:01 UTC, elliotcourant reviewed
No worries at all, just pushed those changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-:-LrGR7CVAK_KKWlUpQZ9:b-7c3erw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/sql/sem/builtins/aggregate_builtins_test.go, line 81 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41334#-LrGMuy05LMdG7Dg0q6m:-LrGR69_3hSla0t69d8P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ffdaaf82eae695cecd49b874198a903ef3c1db6/pkg/sql/sem/builtins/aggregate_builtins_test.go#L81)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

These two tests are missing a leaktest:
```
[21:41:44][Ensure generated code is up-to-date] --- a/pkg/sql/sem/builtins/aggregate_builtins_test.go
[21:41:44][Ensure generated code is up-to-date] +++ b/pkg/sql/sem/builtins/aggregate_builtins_test.go
[21:41:44][Ensure generated code is up-to-date] @@ -79,6 +79,7 @@ func TestAvgDecimalResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  }
[21:41:44][Ensure generated code is up-to-date]  
[21:41:44][Ensure generated code is up-to-date]  func TestBitAndIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date] +	defer leaktest.AfterTest(t)()
[21:41:44][Ensure generated code is up-to-date]  	t.Run("all null", func(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  		testAggregateResultDeepCopy(t, newBitAndAggregate, makeNullTestDatum(10))
[21:41:44][Ensure generated code is up-to-date]  	})
[21:41:44][Ensure generated code is up-to-date] @@ -91,6 +92,7 @@ func TestBitAndIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  }
[21:41:44][Ensure generated code is up-to-date]  
[21:41:44][Ensure generated code is up-to-date]  func TestBitOrIntResultDeepCopy(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date] +	defer leaktest.AfterTest(t)()
[21:41:44][Ensure generated code is up-to-date]  	t.Run("all null", func(t *testing.T) {
[21:41:44][Ensure generated code is up-to-date]  		testAggregateResultDeepCopy(t, newBitOrAggregate, makeNullTestDatum(10))
[21:41:44][Ensure generated code is up-to-date]  	})
```
Basically you need to add `defer leaktest.AfterTest(t)()` as the first line of `TestBitAndIntResultDeepCopy` and `TestBitOrIntResultDeepCopy`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-16 02:04 UTC, yuzefovich commented
Thanks a lot for your contribution, @elliotcourant!

bors r+

2019-10-16 02:41 UTC, yuzefovich commented
Seems like a flake.

bors r+

2019-10-16 03:07 UTC, merged