roachtest: Fix partitioning roachtest failure
cockroachdb/cockroach pull request #41402
Opened 2019-10-07 19:56 UTC by rohany

Fixes a roachtest failure caused by a recent change that performed more
zone config validation on partitions and indexes.

Fixes #41321.

Release justification: Fixes a failing roachtest.

Release note: None

2019-10-07 19:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41402)
<!-- Reviewable:end -->

2019-10-07 19:56 UTC, rohany commented
Should the constraints on this test be empty or equal to the leaseholder preferences? I'm not sure.

2019-10-07 20:09 UTC, andreimatei reviewed
> Should the constraints on this test be empty or equal to the leaseholder preferences?

I don't know what the test does. If diversification is enough to guarantee that a replica is placed in the localities indicated by the lease preference, then I think that's what we want (i.e. empty constraints". That's how it was before, right?

I'm not a good reviewer for this. Find whomever wrote the test and ask about the intention. Since this is a workload, the difference between a geo-replicated partition and a non-geo-replicated one might be crucial. I assume it was non-geo-replicated before, and I assume that was on purpose.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41402#-:-Lqboo-m-LE8mnlp7UWd:b-9h43i0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)



<!-- Sent from Reviewable.io -->

2019-10-07 20:12 UTC, andreimatei commented
I meant it was geo-replicated before.

2019-10-07 21:47 UTC, rohany commented
Ok! I've asked @BramGruneir to take a look at this instead.

2019-10-09 18:12 UTC, BramGruneir requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41402)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @rohany)

___
*[pkg/workload/interleavedpartitioned/interleavedpartitioned.go, line 764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41402#-Lqlh8ys7eRmhjNR1ibZ:-Lqlh8ys7eRmhjNR1ib_:b-xvgjhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d601b36589fc76adb636ac7a14abaafca75601d/pkg/workload/interleavedpartitioned/interleavedpartitioned.go#L764)):*
> ```Go
> 					"ALTER PARTITION east OF TABLE sessions CONFIGURE ZONE USING"+
> 						" lease_preferences = '[[+zone=%[1]s]]', "+
> 						"constraints = '[+zone=%[1]s]'",
> ```

Both of these are incorrect.  It should be set to 
`'{"+zone=%s": 1}'`  (I think)

This needs to have replicas in all three regions, and only set the lease preferences.   So the closest analog would be to set a preference to have one replica in that zone.

Frankly, the requirement to have a constraint in order to set a lease preference is still odd to me.


<!-- Sent from Reviewable.io -->

2019-10-09 18:30 UTC, rohany commented
It is odd, but I think its necessary to avoid having inherited constraints conflict with the lease preferences. Let me update this, that logic makes sense.

2019-10-09 18:36 UTC, BramGruneir commented
A lease preference is never a strong condition.  as long as we have a report to show that it isn't being applied I think is a better solution than requiring these constraint gymnastics.





<!-- Sent from Reviewable.io -->

2019-10-10 15:08 UTC, BramGruneir approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41402#-:-LqqC_FF95MugOKL0bQa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)



<!-- Sent from Reviewable.io -->

2019-10-10 15:44 UTC, merged