sql/parser: support string values in EXTRACT arguments
cockroachdb/cockroach pull request #41429
Opened 2019-10-08 11:47 UTC by rogaps

This adds support to use string values in EXTRACT arguments
(e.g. `EXTRACT ('month' FROM now())`).

Fixes #41408.

Release note: None

2019-10-08 11:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41429)
<!-- Reviewable:end -->

2019-10-08 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=41429) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=41429) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cockroachdb/cockroach?pullRequest=41429) it.</sub>

2019-10-08 13:55 UTC, rohany requested changes
This looks good! A small increase in testing and this should be ready to merge. Thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41429#-:-LqfdhcS0cV79MUJruTV:b-jqfz67)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rogaps and @rohany)

___
*[pkg/sql/sem/tree/testdata/eval/extract, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41429#-LqfdTfpDJHrjhvFr01W:-LqfdTfqAK1gSubCTdcL:bil3w8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad7754f90391d26e20fc1f4e533bd62cd086fe9d/pkg/sql/sem/tree/testdata/eval/extract#L9)):*
> ```
> 
> eval
> extract('year' from '2010-09-28'::date)
> ```

Please add a test where a string constant that isn't correct is rejected, and a case using a string with capital letters.


<!-- Sent from Reviewable.io -->

2019-10-08 16:03 UTC, rogaps commented
Thanks for the review. I just updated the tests, and added rejected strings tests and string with capital characters tests to logic tests.

2019-10-08 16:21 UTC, rohany reviewed
This looks good to me! Please add a release note and then this is good to go.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41429#-:-LqgACe4D98hwTN_MFM8:b-k2rso7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rogaps)



<!-- Sent from Reviewable.io -->

2019-10-08 17:06 UTC, rogaps commented
Release note is added in commit message.

2019-10-08 19:42 UTC, rohany commented
Thanks for your contribution! This LGTM.

bors r=rohany

2019-10-08 21:13 UTC, rohany commented
Hi, it looks like your branch is failing tests on merge. Can you try and rebase and take a look at the test output (it's under bors).

2019-10-08 23:42 UTC, rohany commented
bors r-

2019-10-09 01:48 UTC, rogaps commented
Done rebasing and tests have been fixed.

2019-10-09 02:19 UTC, rohany commented
bors r=rohany

2019-10-09 03:05 UTC, merged

2019-10-09 03:09 UTC, rohany commented
Thanks for your contribution! We are going to backport this into the 19.2 release as well.

2019-10-09 03:30 UTC, rohany commented
I spoke to soon -- we might not backport it to 19.2. I'll write on here the final decision.