sql: Bugfixes around zone config setting and COPY FROM PARENT
cockroachdb/cockroach pull request #41506
Opened 2019-10-10 18:17 UTC by rohany

This PR fixes two bugs related to setting zone configurations.

* COPY FROM PARENT was ignored when using it on partitions and indexes
* COPY FROM PARENT was ignored when using it on a zone that had an
existing value for the field that was being changed with COPY FROM
PARENT.

This change should be backported onto 19.2.

Release note (bug fix): Fix multiple bugs relating to zone
configurations and copy from parent:
* COPY FROM PARENT was ignored when using it on partitions and indexes
* COPY FROM PARENT was ignored when using it on a zone that had an
existing value for the field that was being changed with COPY FROM
PARENT.

2019-10-10 18:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41506)
<!-- Reviewable:end -->

2019-10-10 18:17 UTC, rohany commented
Let me know if there are some other cases that should be tested, or that I missed

2019-10-14 21:06 UTC, solongordon requested changes
Good catch on the issue. This mostly looks good except for a bug I noticed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41506#-:-LrB4tcuE57iVVKjmg4e:b-6vdsq1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41506#-LrB3RLS3LRfV_zeoJC6:-LrB3RLS3LRfV_zeoJC7:b-w07xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c729e5eaf19df5bb2f5e28ee00134ce8971359/pkg/sql/set_zone_config.go#L214)):*
> ```Go
> 		}
> 		return kv.Value, nil
> 	}
> ```

Nit: It would be nice to move this function closer to where it's being used.
___
*[pkg/sql/set_zone_config.go, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41506#-LrB1vO91V3wauTSzk1y:-LrB1vOA2dvwVzSHrdTZ:b-3tac2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/62c729e5eaf19df5bb2f5e28ee00134ce8971359/pkg/sql/set_zone_config.go#L408)):*
> ```Go
> 			// Copy all of the requested parent fields into partial zone, which will
> 			// be used later if we are editing a zone.
> 			partialZone.CopyFromZone(zoneInheritedFields, copyFromParentList)
> ```

I think there's a bug here. If you're doing COPY FROM PARENT on a subzone, the parent zone will end up getting changed too.

Example:
```
create table t (x int, index idx (x));
alter table t configure zone using gc.ttlseconds = 700;
alter index t@idx configure zone using num_replicas = copy from parent;
```
Now the zone config for `TABLE t` incorrectly has `num_replicas` set.


<!-- Sent from Reviewable.io -->

2019-10-14 21:18 UTC, rohany commented
PTAL, addressed both comments.

2019-10-15 13:37 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41506)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/set_zone_config.go, line 408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41506#-LrEcU7O6ZS6pgiqO36M:-LrEcU7P2JuRXJS_M_up:bp3t3t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1c6626bd2096cc2e112d82aa82a81b4116d5926/pkg/sql/set_zone_config.go#L408)):*
> ```Go
> 			// Only modify partialZone if are operating on a zone, not a subZone. This
> 			// occurs when we are not operating on an index.
> 			if index == nil {
> ```

Now there is a new bug where if you do COPY FROM PARENT on an index, it won't inherit a value from the parent table.


<!-- Sent from Reviewable.io -->

2019-10-15 14:32 UTC, rohany commented
Third times a charm. PTAL

2019-10-15 14:47 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41506#-:-LrEsrMu5_kzP115x8SK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)



<!-- Sent from Reviewable.io -->

2019-10-15 19:41 UTC, rohany commented
bors r+

2019-10-15 20:09 UTC, merged

2019-10-16 15:02 UTC, tbg commented
Should this be backported?

2019-10-16 15:42 UTC, rohany commented
Yes, there’s an open issue to back port this and a few other zone config fixes. I’ll get to it today or tomorrow!