storage: prevent even replica count if cannot progress to odd count
cockroachdb/cockroach pull request #41623
Opened 2019-10-15 22:30 UTC by darinpp

This is a bug, introduced with the addition of learner replicas. The fix
restores the same behavior as 19.1

Fixes #41328

Release note: None

2019-10-15 22:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41623)
<!-- Reviewable:end -->

2019-10-16 07:35 UTC, tbg approved these changes
I took a look at https://github.com/cockroachdb/cockroach/blob/d7efc7d209c98fe9d5837f193085914dfa4522a2/pkg/storage/replicate_queue_test.go#L159-L163 to see whether it could be turned into a regression test. Unfortunately I'm not sure this is straightforward since we have no good way to simulate a node being down - we have to actually take it down, and then wait out TimeUntilStoreDead, and we're likely to run into trouble the way things are set up today if we turn that number down too much (since making this smaller than the liveness duration will make all nodes look dead most of the time). If you're interested, we can introduce a testing knob that can hardcode certain nodes down to unlock this kind of testing. If not, still LGTM assuming you manually verified that this patch does fix the problem.

2019-10-16 14:45 UTC, danhhz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @darinpp)

___
*[pkg/storage/replicate_queue.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-LrK0LLY3br2M97GhaJS:-LrK0LLY3br2M97GhaJT:b-ls1upy) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/pkg/storage/replicate_queue.go#L349)):*
> ```Go
> 		// only include live replicas, since dead replicas should soon be removed
> 		existingReplicas := liveVoterReplicas
> 		return rq.addOrReplace(ctx, repl, existingReplicas, -1 /* removeIdx */, dryRun)
> ```

This isn't the old behavior either. Previously, the call to `AllocateTarget` inside `add` was using liveReplicas (which is where this came from). Does this matter? Dunno. If we're making the safest possible change should we plumb them both down and do exactly what we were doing before? Probably

Also I think it's worth a TODO to revisit this, because the old behavior doesn't seem great either, just less wrong.


<!-- Sent from Reviewable.io -->

2019-10-16 21:33 UTC, darinpp commented
> I took a look at
> 
> https://github.com/cockroachdb/cockroach/blob/d7efc7d209c98fe9d5837f193085914dfa4522a2/pkg/storage/replicate_queue_test.go#L159-L163
> 
> to see whether it could be turned into a regression test. Unfortunately I'm not sure this is straightforward since we have no good way to simulate a node being down - we have to actually take it down, and then wait out TimeUntilStoreDead, and we're likely to run into trouble the way things are set up today if we turn that number down too much (since making this smaller than the liveness duration will make all nodes look dead most of the time). If you're interested, we can introduce a testing knob that can hardcode certain nodes down to unlock this kind of testing. If not, still LGTM assuming you manually verified that this patch does fix the problem.

I did test manually. I also looked to add a regression test but it isn't trivial and I don't want to delay this too much. We still need to resolve the 19.1 issue and that be opportunity to add that test.

2019-10-16 21:34 UTC, darinpp commented
bors r+

2019-10-16 21:39 UTC, danhhz requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41623)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

___
*[pkg/storage/replicate_queue.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-LrK0LLY3br2M97GhaJS:-LrLVeSd5Qj0RV_8InIR:b-u6qzsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/pkg/storage/replicate_queue.go#L349)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This isn't the old behavior either. Previously, the call to `AllocateTarget` inside `add` was using liveReplicas (which is where this came from). Does this matter? Dunno. If we're making the safest possible change should we plumb them both down and do exactly what we were doing before? Probably

Also I think it's worth a TODO to revisit this, because the old behavior doesn't seem great either, just less wrong.
</blockquote></details>

Sorry, did you see this comment? I don't think this is ready to bors until it's resolved


<!-- Sent from Reviewable.io -->

2019-10-16 21:47 UTC, darinpp commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41623)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @darinpp)
> 
> _[pkg/storage/replicate_queue.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-LrK0LLY3br2M97GhaJS:-LrK0LLY3br2M97GhaJT:b-ls1upy) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/pkg/storage/replicate_queue.go#L349)):_
> 
> > ```go
> > 		// only include live replicas, since dead replicas should soon be removed
> > 		existingReplicas := liveVoterReplicas
> > 		return rq.addOrReplace(ctx, repl, existingReplicas, -1 /* removeIdx */, dryRun)
> > ```
> 
> This isn't the old behavior either. Previously, the call to `AllocateTarget` inside `add` was using liveReplicas (which is where this came from). Does this matter? Dunno. If we're making the safest possible change should we plumb them both down and do exactly what we were doing before? Probably
> 
> Also I think it's worth a TODO to revisit this, because the old behavior doesn't seem great either, just less wrong.

The `AllocateTarget` only considers live stores. The replica list is being passed so you can filter out stores that already have replicas. So it doesn't matter if you will check each live store if it has one of the live or all range replicas.

2019-10-16 21:56 UTC, danhhz reviewed
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-:-LrLZSfz9CJmvCFAlqWD:b-ydi9aw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

___
*[pkg/storage/replicate_queue.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-LrK0LLY3br2M97GhaJS:-LrLZTXm6ZC9virYSfIv:bg6hmqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/53e1686b19e95a4c9b79884e348720b05b434244/pkg/storage/replicate_queue.go#L349)):*
<details><summary><i>Previously, darinpp wrote…</i></summary><blockquote>

The `AllocateTarget` only considers live stores. The replica list is being passed so you can filter out stores that already have replicas. So it doesn't matter if you will check each live store if it has one of the live or all range replicas.  
</blockquote></details>

I talked to darin offline and he's going to pass both allVoters and liveVoters into addOrReplica to make this as low risk as possible for 19.2. We'll revisit in 20.1


<!-- Sent from Reviewable.io -->

2019-10-16 23:23 UTC, darinpp commented
@danhhz take another look to see if this is what you had in mind.

2019-10-17 14:54 UTC, danhhz approved these changes
LGTM, thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41623#-:-LrPCaucBDrAGf2Eplpw:b2c0zcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)



<!-- Sent from Reviewable.io -->

2019-10-17 16:04 UTC, darinpp commented
bors r+

2019-10-17 16:32 UTC, merged