sql: Add ability to create no-op temp tables with correct FK semantics
cockroachdb/cockroach pull request #41703
Opened 2019-10-17 19:33 UTC by arulajmani

Skeletal work that temp tables can be built on further. This PR includes
support for:
- start accepting the temp syntax for tables, views, and sequences
- ensure no FK cross constraint can be established between persistent
and temp tables
- save the sessionID in the extendedEvalContext (for later work)
- gate the feature behind "enable_temp_tables"

Release note: None

2019-10-17 19:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41703)
<!-- Reviewable:end -->

2019-10-17 20:12 UTC, solongordon requested changes
> Reviewed 21 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/create_sequence.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQG6-z66oZx9_LzB4E:-LrQG6-z66oZx9_LzB4F:bkubtry) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_sequence.go#L55)):*
> ```Go
> 	if n.n.PersistenceStatus == tree.Temporary {
> 		return unimplemented.NewWithIssuef(5807,
> 			"Can not create temporary sequences at this time")
> ```

Nit: How about just "temporary sequences are unsupported"?
___
*[pkg/sql/create_table.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGALIElyli09rBVE8:-LrQGALIElyli09rBVE9:b-scj03v) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_table.go#L38)):*
> ```Go
> 
> var enableTempTablesError = pgerror.New(pgcode.Syntax,
> 	"enable_temp_tables is an experimental feature which must be explicitly turned on")
> ```

I'd suggest just returning an unimplemented exception for now. People who don't know to enable the setting probably shouldn't be using temp tables yet anyway. :)
___
*[pkg/sql/create_view.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGFIpBfEeTImOn601:-LrQGFIpBfEeTImOn602:brlcyz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_view.go#L27)):*
> ```Go
> 	viewName tree.Name
> 	// viewQuery contains the view definition, with all table names fully
> 	// qualified.
> ```

Misplaced comment
___
*[pkg/sql/create_view.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGNQYD8wYxaDGprFB:-LrQGNQYD8wYxaDGprFC:b3ipi1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_view.go#L45)):*
> ```Go
> 	// TODO(arul): Allow temporary views once temp tables work for regular tables.
> 	if n.persistenceStatus == tree.Temporary {
> 		return unimplemented.NewWithIssuef(5807,
> ```

This line is unreachable.
___
*[pkg/sql/vars.go, line 817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGRvU1zFK2fwoag0W:-LrQGRvV2VrAdQBh-5bD:b-ge3uq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/vars.go#L817)):*
> ```Go
> 	// TODO(arul): Update this comment when temp tables work is done.
> 	// Still under development
> 	`enable_temp_tables`: {
> ```

Make this `experimental_enable_temp_tables`. By convention we always prefix experimental options with `experimental_`. (See https://www.cockroachlabs.com/docs/dev/experimental-features.html for some other examples.)
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGiLj3eXMwYA9y05W:-LrQGiLj3eXMwYA9y05X:bne7qyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2663)):*
> ```
> statement ok
> DROP TABLE person, pet
> ```

Nit: extra blank line
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQH0Jd4iFIfAVHeH49:-LrQH0Jd4iFIfAVHeH4A:b-sy5iba) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2664)):*
> ```
> DROP TABLE person, pet
> ```

Maybe nice to test that you can't create a temp table before enabling them.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGZLJBhsa63tgWJAR:-LrQGZLJBhsa63tgWJAS:bl0ydkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2678)):*
> ```
> 
> statement ok
> DROP TABLE a_temp, b_temp
> ```

Just to keep things simple I'd avoid dropping tables and just create a new one.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGkP8ELgIsmynL1OS:-LrQGkP8ELgIsmynL1OT:b-2ux5ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2685)):*
> ```
> 
> statement ok
> SET enable_temp_tables = true
> ```

Why do you disable and then re-enable temp tables?
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGwYYDgXWFjv3KBTp:-LrQGwYYDgXWFjv3KBTq:bxm9hdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2694)):*
> ```
> 
> statement ok
> DROP TABLE a_persistent
> ```

Ditto about not dropping tables.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGo_416tGeuowBPNM:-LrQGo_416tGeuowBPNN:b2gqorh) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2697)):*
> ```
> 
> statement ok
> SET enable_temp_tables = false
> ```

I wouldn't worry about resetting this.
___
*[pkg/sql/opt/metadata.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQHxaoCqc0RGm-qyZC:-LrQHxaoCqc0RGm-qyZD:b-tz63sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/opt/metadata.go#L33)):*
> ```Go
> type SchemaID int32
> 
> type PersistenceStatus bool
> ```

My editor tells me this is unused—is that right?
___
*[pkg/sql/sem/tree/create.go, line 903 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQIvwC6_N6z09jKrwO:-LrQIvwC6_N6z09jKrwP:b-1ov0t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sem/tree/create.go#L903)):*
> ```Go
> }
> 
> // PersistenceStatus represents the persistence type of a table.
> ```

PersistenceStatus is a confusing name to me, mainly the "status" part. That makes it sound like it's subject to change. Maybe just PersistenceType would be clearer?
___
*[pkg/sql/sem/tree/create.go, line 908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQJCzb-y6SqX38McuR:-LrQJCzb-y6SqX38McuS:b-dgqpcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sem/tree/create.go#L908)):*
> ```Go
> const (
> 	Persistent PersistenceStatus = iota
> 	Temporary
> ```

Why did you choose to use an enum here but an `isTempTable` boolean on the table descriptor? Are we anticipating more values in the future? I don't necessarily think the enum is a bad idea but the discrepancy is confusing to me.
___
*[pkg/sql/sessiondata/session_data.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQKZkaBFZnYBmcMqyh:-LrQKZkaBFZnYBmcMqyi:b-bzpfm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sessiondata/session_data.go#L97)):*
> ```Go
> 	// SaveTablesPrefix is empty, no tables are created.
> 	SaveTablesPrefix string
> 	// TempTablesEnabled indicates whether temporary tables can be used or not.
> ```

More specifically whether they can be created or not.
___
*[pkg/sql/sqlbase/structured.proto, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQJQsT7o2lfKrCbSNu:-LrQJQsT7o2lfKrCbSNv:ba3q4by) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sqlbase/structured.proto#L837)):*
> ```protobuf
>   repeated ForeignKeyConstraint inbound_fks = 37 [(gogoproto.nullable) = false, (gogoproto.customname) = "InboundFK [...]

2019-10-17 20:59 UTC, rohany requested changes
Some small comments from a preliminary look at this

> Reviewed 15 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-LrQWCqf2M5BHwCQA7HF:b-tdrn6r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/create_table.go, line 866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQDX3S7PGM2YzCT_Nj:-LrQDX3TE2uKfHJOImV1:b-ul0qe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_table.go#L866)):*
> ```Go
> 	creationTime hlc.Timestamp,
> 	privileges *sqlbase.PrivilegeDescriptor,
> 	isTempTable bool,
> ```

[nit] maybe instead `isTemporary`?
___
*[pkg/sql/parser/sql.y, line 4912 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQDud54Ua8Swl8SLYX:-LrQDud54Ua8Swl8SLYY:b-lm0tod) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/parser/sql.y#L4912)):*
> ```Yacc
>     $$.val = &tree.CreateSequence {
>       Name: name,
>       PersistenceStatus: $2.persistenceStatus(),
> ```

rather than adding all the extra plumbing in the sequence and view code, you could return the unimplemented error here


<!-- Sent from Reviewable.io -->

2019-10-18 20:15 UTC, arulajmani reviewed
TFTR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-LrVVhQm4l5OzQ4_sg1D:bz5m8k4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rohany, and @solongordon)

___
*[pkg/sql/create_table.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGALIElyli09rBVE8:-LrQQKEzD7wAxk6ZQK4d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_table.go#L38)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'd suggest just returning an unimplemented exception for now. People who don't know to enable the setting probably shouldn't be using temp tables yet anyway. :)
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGFIpBfEeTImOn601:-LrQQjGV2B0hp8VLz4Hl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_view.go#L27)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Misplaced comment
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGNQYD8wYxaDGprFB:-LrQRSuh2fu5btMVc9iR:b-8x1or7) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_view.go#L45)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This line is unreachable.
</blockquote></details>

My bad, I was supposed to check if temp tables were enabled above. Acc to your previous comment, Im removing this block and simply returning the unimplemented error. 
___
*[pkg/sql/vars.go, line 817 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGRvU1zFK2fwoag0W:-LrQS3iH9-vMKlx2dbBB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/vars.go#L817)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Make this `experimental_enable_temp_tables`. By convention we always prefix experimental options with `experimental_`. (See https://www.cockroachlabs.com/docs/dev/experimental-features.html for some other examples.)
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQH0Jd4iFIfAVHeH49:-LrVJQhO7wwR_HETgNdJ:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2664)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe nice to test that you can't create a temp table before enabling them.
</blockquote></details>

Added.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2678 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGZLJBhsa63tgWJAR:-LrVK9jiB4KWmch6VO85:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2678)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Just to keep things simple I'd avoid dropping tables and just create a new one.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2685 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGkP8ELgIsmynL1OS:-LrQS6g462rkSXC9u0IQ:bmn3yhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2685)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why do you disable and then re-enable temp tables?
</blockquote></details>

I was thinking of this as two separate tests -- one for temp table fk referencing persistent, and another for the other direction. To keep them "logically separate", I was doing the dropping + enable/re-enable. 

On second thought, it makes more sense to just add a comment on top explaining the tests rather than what I was doing earlier. Changing to that. :) 
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2694 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGwYYDgXWFjv3KBTp:-LrVLP_N-pHiUscpNho2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2694)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ditto about not dropping tables.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2697 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGo_416tGeuowBPNM:-LrVJEeYEZxJxJxHs4t7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/logictest/testdata/logic_test/fk#L2697)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I wouldn't worry about resetting this.
</blockquote></details>

Done.
___
*[pkg/sql/opt/metadata.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQHxaoCqc0RGm-qyZC:-LrQTVf-3qtPYfreaINM:b-aciyar) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/opt/metadata.go#L33)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

My editor tells me this is unused—is that right?
</blockquote></details>

It is! remnant of when I was trying to figure out some code gen stuff in opt. Removing it :) 
___
*[pkg/sql/parser/sql.y, line 4912 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQDud54Ua8Swl8SLYX:-LrVLkcA7u1ydXoqHGED:bn2yssv) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/parser/sql.y#L4912)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

rather than adding all the extra plumbing in the sequence and view code, you could return the unimplemented error here
</blockquote></details>

Makes sense, I could've just added an if statement here. Considering we need to do the plumbing at some point soon, and it would be added effort to remove it, do you have any major concerns just keeping it this way? 
___
*[pkg/sql/sem/tree/create.go, line 903 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQIvwC6_N6z09jKrwO:-LrQTiOLAut2Q5UVaui2:ba7m5ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sem/tree/create.go#L903)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

PersistenceStatus is a confusing name to me, mainly the "status" part. That makes it sound like it's subject to change. Maybe just PersistenceType would be clearer?
</blockquote></details>

Changing this to a bool `Temporary` to match the table descriptor boolean (in reference to your comment below) 
___
*[pkg/sql/sem/tree/create.go, line 908 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQJCzb-y6SqX38McuR:-LrUUw3c1LabdsZjvpoT:b7sj2oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/sem/tree/create.go#L908)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why did you choose to use an enum here but an `isTempTable` boolean on the table descriptor? Are we anticipating more values in the future? I don't necessarily think the enum is a bad idea but the discrepancy is confusing to me.
</blockquote></details>

From our discussion offline, I looked into transaction scoped temp tables. The syntax to create them is `CREATE TEMP TABLE a(a int) ON COMMIT DROP`. The `ON [...]

2019-10-21 14:45 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rohany, and @solongordon)

___
*[pkg/sql/create_sequence.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrilTf040ySIN9aBE0O:-LrilTf040ySIN9aBE0P:bw8nkb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/create_sequence.go#L52)):*
> ```Go
> 	if n.n.Temporary {
> 		return unimplemented.NewWithIssuef(5807,
> 			"Temporary sequences are unsupported")
> ```

Nit: By convention I believe we do not capitalize the first letter in our error messages.
___
*[pkg/sql/create_table.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGALIElyli09rBVE8:-Lrijtkg95TDSCpT92Xa:b4bp9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_table.go#L38)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Isn't this unused now?
___
*[pkg/sql/create_table.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrilVeL6SDXdHXzssGN:-LrilVeL6SDXdHXzssGO:bw8nkb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/create_table.go#L72)):*
> ```Go
> 		if !params.SessionData().TempTablesEnabled {
> 			return unimplemented.NewWithIssuef(5807,
> 				"Temporary tables are unsupported")
> ```

Nit: By convention I believe we do not capitalize the first letter in our error messages.
___
*[pkg/sql/create_view.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrikBQm8w19YteKz2Nv:-LrikBQm8w19YteKz2Nw:bw8nkb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/create_view.go#L43)):*
> ```Go
> 	if n.temporary {
> 		return unimplemented.NewWithIssuef(5807,
> 			"Temporary views are unsupported")
> ```

Nit: By convention I believe we do not capitalize the first letter in our error messages.
___
*[pkg/sql/logictest/logic_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrilbL837sX-cU0P99m:-LrilbL837sX-cU0P99n:b-7qcd9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/logictest/logic_test.go#L32)):*
> ```Go
> func TestLogic(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	// RunLogicTest(t, "testdata/logic_test/[^.]*")
> ```

Oh boy you'd really better uncomment this. :)
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2690 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrikZ8m8ixzGOJrmayc:-LrikZ8n52WiayVCSXYJ:britnph) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/logictest/testdata/logic_test/fk#L2690)):*
> ```
> 
> statement ok
> DROP TABLE a_temp, b_temp, c_persistent
> ```

Still not necessary to drop these tables. Unless you're testing something by dropping them?
___
*[pkg/sql/sem/tree/create.go, line 942 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrikyoRCsBrtKkNzEHv:-LrikyoRCsBrtKkNzEHw:b-wckxyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/sem/tree/create.go#L942)):*
> ```Go
> 	ctx.WriteString("CREATE ")
> 	if node.Temporary {
> 		ctx.WriteString("TEMP ")
> ```

Nit: I would prefer TEMPORARY here.
___
*[pkg/sql/sem/tree/create.go, line 1048 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-Lril0EJ7EdzO90WmH_U:-Lril0EJ7EdzO90WmH_V:b-frj83b) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/sem/tree/create.go#L1048)):*
> ```Go
> 
> 	if node.Temporary {
> 		ctx.WriteString("TEMP ")
> ```

Ditto about "TEMPORARY".
___
*[pkg/sql/sem/tree/create.go, line 1212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-Lril1hkAi0RneYAnt1_:-Lril1hkAi0RneYAnt1a:b-frj83b) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/sem/tree/create.go#L1212)):*
> ```Go
> 
> 	if node.Temporary {
> 		ctx.WriteString("TEMP ")
> ```

Ditto about "TEMPORARY".


<!-- Sent from Reviewable.io -->

2019-10-21 15:27 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rohany, and @solongordon)

___
*[pkg/sql/create_table.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrQGALIElyli09rBVE8:-LrisXOR0uvxBc2pmtBB:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b24a0e8a48a25afd996fa7caa2815841008ac1/pkg/sql/create_table.go#L38)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Isn't this unused now?
</blockquote></details>

Removed.
___
*[pkg/sql/logictest/logic_test.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrilbL837sX-cU0P99m:-Lrisq-r1FvfkOVfgGZz:b-jqyr6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/logictest/logic_test.go#L32)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Oh boy you'd really better uncomment this. :)
</blockquote></details>

Oops this crept in from my testing ... 
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 2690 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrikZ8m8ixzGOJrmayc:-LritFDyDnjdZFdxcSQR:bsuse73) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/logictest/testdata/logic_test/fk#L2690)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Still not necessary to drop these tables. Unless you're testing something by dropping them?
</blockquote></details>

Not testing anything, I had this because other logic tests Ive seen seem to perform cleanup of tables/sequences that they create. Removing it. :) 
___
*[pkg/sql/sem/tree/create.go, line 1048 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-Lril0EJ7EdzO90WmH_U:-LrivXWz4R_BB8jCqwvH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/sem/tree/create.go#L1048)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ditto about "TEMPORARY".
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 1212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-Lril1hkAi0RneYAnt1_:-LrivXwR7hw9aoUuaM0T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23316bb96aaeecc722d741188e22052f602abff5/pkg/sql/sem/tree/create.go#L1212)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ditto about "TEMPORARY".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-21 15:31 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-LriwJsU4Y9z4LPZ1iF6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-10-21 18:26 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @rohany, and @solongordon)

___
*[pkg/sql/parser/sql.y, line 4180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrjZRzp6hFLsyKVtaFr:-LrjZRzqAoIDA-U04fF0:bqtb73q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac21af7e0184fa56c799f368b7945af4e128c0f8/pkg/sql/parser/sql.y#L4180)):*
> ```Yacc
> // %Category: DDL
> // %Text:
> // CREATE TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<interleave>]
> ```

Please update this too.


<!-- Sent from Reviewable.io -->

2019-10-21 19:26 UTC, arulajmani reviewed
Open question on the GLOBAL TEMP/LOCAL TEMP syntax -- PG accepts both these options, but essentially treats GLOBAL/LOCAL keywords as no-ops. So, they're all equivalent to a plain TEMP qualifier.

The GLOBAL/LOCAL no-ops are only accepted by PG in CREATE TABLE -- not VIEW/SEQUENCE. Currently, the way this PR is implemented, we can have GLOBAL TEMP/LOCAL TEMP for sequences and views as well. Just like CREATE TABLE, these are considered no-ops. Is this behavior acceptable? Or should the no-ops only be allowed for CREATE TABLE to match PG. I personally don't think there is a need to make a distinction. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-LrjlBjc64PNxhFZdJJZ:biz6xgx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @knz, @rohany, and @solongordon)

___
*[pkg/sql/parser/sql.y, line 4180 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-LrjZRzp6hFLsyKVtaFr:-LrjlA_74xobRTQo76_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac21af7e0184fa56c799f368b7945af4e128c0f8/pkg/sql/parser/sql.y#L4180)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please update this too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-21 19:44 UTC, solongordon reviewed
My opinion is let's match Postgres if it's easy. But if you have to do something convoluted to make it work, the extra no-op keywords don't seem like a big deal to me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-LrjpdTy75_8GbFUnv94:b-e7p1co)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @knz, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-10-21 21:14 UTC, arulajmani reviewed
Done, it should match PG now. Merging 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41703#-:-Lrk9rorAPiyaPfXfUDy:b-rbahu0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @knz, @rohany, and @solongordon)



<!-- Sent from Reviewable.io -->

2019-10-21 21:15 UTC, arulajmani commented
bors r+

2019-10-21 21:48 UTC, merged