changefeedccl: fix bug which leaves a dangling table lease after job restart
cockroachdb/cockroach pull request #41785
Opened 2019-10-21 20:10 UTC by aayushshah15

Fixes #41780

Currently, any call to `acquireNodeLease()` in `lease.go` goes through
a `singleflight.Group`. The group uses the `context.Context` of its first
caller. The method `AcquireFreshestFromStore()` calls `acquireNodeLease()`.

Now, in `poller.go` and `table_history.go` we repeatedly call
`leaseManager.AcquireFreshestFromStore()` in order to make sure the table
descriptor is up to date with respect to a certain timestamp.
Additionally, we also call `leaseManager.AcquireFreshestFromStore()`
periodically inside `leaseManager.RefreshLeases()`.

Now consider the case where there is a job cancellation around the same
time as a `RefreshLeases` call. Since the single flight group simply uses
the `context` of its first caller, it's possible that it's using the
changefeed job's context that's passed down into this call from the `poller`.
Due to the job cancellation and because the single flight group is using
the changefeed job's context, the `purgeOldVersions` call
(called by `RefreshLeases`) also gets cancelled; this leaves a dangling table
lease that doesn't get purged at the end of the call.

We can fix this problem by having `acquireNodeLease` create a new context
inside of its single flight closure to make sure that this closure doesn't
get cancelled, after copying the tags from the context it's handed.

Release note (bug fix): Other callers to `acquireNodeLease` will not get
erroneously cancelled just because the context of the first caller was
cancelled.

2019-10-21 20:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41785)
<!-- Reviewable:end -->

2019-10-21 20:25 UTC, danhhz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @danhhz)

___
*[pkg/sql/lease.go, line 990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzIbeCTT6sienxXkA:-LrjzIbeCTT6sienxXkB:bm6lt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L990)):*
> ```Go
> 		// happened.
> 		b := logtags.FromContext(ctx)
> 		newCtx := logtags.WithTags(context.Background(), b)
> ```

we probably do want some sort of safety net timeout here, but beats me what a good value should be


<!-- Sent from Reviewable.io -->

2019-10-21 20:29 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @danhhz)

___
*[pkg/sql/lease.go, line 990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzIbeCTT6sienxXkA:-LrjzlCH2MwO7qKIr1P8:b-mfvtql) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L990)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

we probably do want some sort of safety net timeout here, but beats me what a good value should be
</blockquote></details>

https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/stop#Stopper.WithCancelOnQuiesce seems like a sane choice. 
___
*[pkg/sql/lease.go, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzCXX1_cQO4u5hnC8:-LrjzCXX1_cQO4u5hnC9:b-66mvap) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L1020)):*
> ```Go
> 	case result := <-resultChan:
> 		if result.Err != nil {
> 			return false, result.Err
> ```

It's weird to me that you're going to return `false` here for the `didAcquire` unconditionally if you got a result on the channel but you may return true or false if the context was cancelled. It honestly also seems bad that the releaseLease call happens where it does too. I'm not really clear on why it doesn't live in the singleflight, except that we don't want to expose the latency of the release to other callers which joined the singleflight? It too is going to do database operations. 

Furthermore we are now exposed to a race condition. There's no synchronization on that `toRelease` object so it's not safe to look at it now that we might get signalled by the context cancellation. 

I think the `releaseLease` logic should get a reworking here. 


<!-- Sent from Reviewable.io -->

2019-10-21 20:31 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @danhhz)

___
*[pkg/sql/lease.go, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzCXX1_cQO4u5hnC8:-Lrk-s_nESnRYtuia3Gj:b4aee9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L1020)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's weird to me that you're going to return `false` here for the `didAcquire` unconditionally if you got a result on the channel but you may return true or false if the context was cancelled. It honestly also seems bad that the releaseLease call happens where it does too. I'm not really clear on why it doesn't live in the singleflight, except that we don't want to expose the latency of the release to other callers which joined the singleflight? It too is going to do database operations. 

Furthermore we are now exposed to a race condition. There's no synchronization on that `toRelease` object so it's not safe to look at it now that we might get signalled by the context cancellation. 

I think the `releaseLease` logic should get a reworking here. 
</blockquote></details>

Actually it launches an async task if we're not already shutting down. I think it's definitely worth lifting the `releaseLease` logic into the singleflight. 


<!-- Sent from Reviewable.io -->

2019-10-21 23:42 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/lease.go, line 990 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzIbeCTT6sienxXkA:-Lrkgkpz-G_t8n4ED0Jx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L990)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

https://godoc.org/github.com/cockroachdb/cockroach/pkg/util/stop#Stopper.WithCancelOnQuiesce seems like a sane choice. 
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 1020 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrjzCXX1_cQO4u5hnC8:-LrkgcGx0LWl1oehql-J:bguxul4) ([raw file](https://github.com/cockroachdb/cockroach/blob/66ac97b3988752732403b17920507e5e5cd56247/pkg/sql/lease.go#L1020)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Actually it launches an async task if we're not already shutting down. I think it's definitely worth lifting the `releaseLease` logic into the singleflight. 
</blockquote></details>

Done, let me know if I misunderstood you or if this doesn't seem reasonable.


<!-- Sent from Reviewable.io -->

2019-10-21 23:51 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

just the nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-:-Lrkim9M69WJ4onmbcHp:b37ocnb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/sql/lease.go, line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41785#-LrkiFUV62n6sTO_qThJ:-LrkiFUV62n6sTO_qThK:b-jcpp41) ([raw file](https://github.com/cockroachdb/cockroach/blob/cda4132a25f7d6105f3ae34bb4d837bc0fa3cd81/pkg/sql/lease.go#L990)):*
> ```Go
> 		// happened.
> 		b := logtags.FromContext(ctx)
> 		stopper := m.stopper
> ```

nit: why assign this a variable?

I think I'd just write all of this as:
```
ctx, cancel := m.stopper.WithCancelOnQuiesce(
    logtags.WithTags(context.Background(), logtags.FromContest(ctx))
```


<!-- Sent from Reviewable.io -->

2019-10-23 21:43 UTC, aayushshah15 commented
TFTRs! Merging this now.

2019-10-23 21:44 UTC, merged