support custom bases log function #41837
cockroachdb/cockroach pull request #41848
Opened 2019-10-23 07:31 UTC by u5surf

Fixes: #41837 

Added overload function to return logarithm to be customed base `log b (x)`.

2019-10-23 07:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41848)
<!-- Reviewable:end -->

2019-10-23 07:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=41848) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cockroachdb/cockroach?pullRequest=41848) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cockroachdb/cockroach?pullRequest=41848) it.</sub>

2019-10-23 15:49 UTC, jordanlewis commented
Hi @u5surf, thanks for the contribution. Your code doesn't compile yet, and you didn't add any tests yet - we'll need both of those to get this to merge. Feel free to ask questions on this PR and we'll try to help!

2019-10-28 20:56 UTC, yuzefovich reviewed
@u5surf thanks for taking this on! This is looking good, but you could make it even better! :)

Currently, when taking a logarithm of zero or a negative float, we will return `-Inf` or `NaN`, respectively, but Postgres returns an error (we do return an error when operating on decimals). So it'd be nice if we were returning an error as well. You can take a look `decimalLogFn` for an example of such behavior.

Also, here is the ideal interaction (which you could incorporate in tests as part of your PR):
```
yuzefovich=# select log(0.0);
ERROR:  cannot take logarithm of zero
CONTEXT:  SQL function "log" statement 1
yuzefovich=# select log(-10.0);
ERROR:  cannot take logarithm of a negative number
CONTEXT:  SQL function "log" statement 1
yuzefovich=# select log(2.0, 0.0);
ERROR:  cannot take logarithm of zero
yuzefovich=# select log(2.0, -10.0);
ERROR:  cannot take logarithm of a negative number
```

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41848#-:-LsJ7ifTB20vIm1zgBJ1:b-alo3rx)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-01-20 17:18 UTC, otan requested changes
Sorry for the delay in review. I think there needs to be a change though.

2020-01-20 17:25 UTC, otan commented on pkg/sql/sem/builtins/builtins.go
> +				return nil, errLogOfNegNumber
Ooops, I got this wrong, never mind! Don't have a complex type yet :D!

2020-01-20 17:25 UTC, otan commented on pkg/sql/sem/builtins/builtins.go
>  		decimalLogFn(tree.DecimalCtx.Log10, "Calculates the base 10 log of `val`."),
We do need to add one for the decimal type too though, don't we?
Can you add a test for SELECT log(2.0, 4.5::double)

2020-01-20 21:37 UTC, knz commented
The reviewers are invited to ensure there is a release note in there before it merges.

(Tip: if it was mem I would take over the PR with a final force-push to do the final polishes after the external contributors finds themselves happy with their performance. It would be unfair to ask them to learn our nits if they are not regular contributors already.)

2020-01-24 16:23 UTC, otan commented
i've fixed the compile error and added decimal. if this passes, i will merge this with master for you :)

2020-01-24 16:55 UTC, otan approved these changes

2020-01-24 16:56 UTC, otan commented
bors r+

2020-01-24 17:34 UTC, merged

2020-01-27 02:08 UTC, u5surf commented
@otan Sorry for slow response, Thank you for following up!