storage/engine: add pebbleReadOnly
cockroachdb/cockroach pull request #41859
Opened 2019-10-23 15:16 UTC by petermattis

Reimplement `Pebble.ReadOnly` with a specific `pebbleReadOnly`
implementation. This removes a lot of `if p.readOnly` checks from
`Pebble`, and also allows for `pebbleReadOnly.NewIterator` to use a
reusable iterator. This brings the behavior in line with
`rocksDBReadOnly`.

Added `pebbleIterator.{reusable,inuse,setOptions}`. Replaced
`pebbleBatchIterator` with a `pebbleIterator` marked as reusable.

Release note: None

2019-10-23 15:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41859)
<!-- Reviewable:end -->

2019-10-23 15:41 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/batch_test.go, line 1015 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LrtGg_R4dDaF3tguaTA:-LrtGg_SA3isf7hYvkxo:b-tblxj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/af02589148b8afa1e72c742ea6b8549ef79c7529/pkg/storage/engine/batch_test.go#L1015)):*
> ```Go
> 					// With Pebble, writes to the distinct batch are readable by the
> 					// distinct batch. This semantic difference is due to not buffering
> 					// writes in a builder.
> ```

I don't think this difference between Pebble and RocksDB distinct batches will matter, but we all should be aware of it.
___
*[pkg/storage/engine/batch_test.go, line 1203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LrtGmr96JCt4KG9bCWC:-LrtGmr96JCt4KG9bCWD:b7ctho4) ([raw file](https://github.com/cockroachdb/cockroach/blob/af02589148b8afa1e72c742ea6b8549ef79c7529/pkg/storage/engine/batch_test.go#L1203)):*
> ```Go
> 			switch engineImpl.name {
> 			case "pebble":
> 				// Reverse iteration in batches works on Pebble.
> ```

A less important difference between Pebble and RocksDB. We don't support reverse iteration on RocksDB batches due to implementation limitations with iteration on `rocksdb::WriteBatchWithIndex`. No such limitation with Pebble, but this isn't something CRDB uses.


<!-- Sent from Reviewable.io -->

2019-10-23 20:51 UTC, itsbilal requested changes
Looks good overall, just some questions / concerns.

> Reviewed 2 of 5 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-:-LruNn3xEGRR9aF17q5D:b-xxnnkg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_batch.go, line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruNX-S9WQQtFw0-_7s:-LruNX-S9WQQtFw0-_7t:b27lx1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_batch.go#L114)):*
> ```Go
> 		}
> 	} else if !p.batch.Indexed() {
> 		r = p.db
> ```

Is this just to mimic RocksDB behaviour, or do we actually do reads on distinct batches and expect them to fall through to the underlying db?
___
*[pkg/storage/engine/pebble_batch.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruJxgHAy_pdR5O4tAr:-LruJxgHAy_pdR5O4tAs:b-u5bvig) ([raw file](https://github.com/cockroachdb/cockroach/blob/483063bb68cb76f6b9ae98abf6604d15e8431511/pkg/storage/engine/pebble_batch.go#L146)):*
> ```Go
> 	// Use the cached iterator.
> 	//
> 	// TODO(itsbilal): Investigate if it's equally or more efficient to just call
> ```

Are we confident enough in ditching this TODO? Both performance-wise and correctness wise?

For eg. I just uncovered a minor issue in this area: I noticed that we sometimes end up running into the "iterator already in use" case where we expect a batch to be able to spawn two iterators at once. As a particular example, `resolveLocalIntents` in batchEval spins up one non-prefix iterator on a batch (the associated `Close` is in a defer), then calls `SetAbortSpan` which requests a prefix iterator on the same batch. This is fine in the RocksDB batch case since we cache a prefix and a non-prefix iterator. We could either mimic that setup here and cache two iterators, or just do no caching if the performance impact of that is negligible or none.
___
*[pkg/storage/engine/pebble_iterator.go, line 519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruM8krAt4bFrRxR8pa:-LruM8krAt4bFrRxR8pb:bqppkqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_iterator.go#L519)):*
> ```Go
> 	p.reusable = false
> 	p.inuse = false
> 	p.Close()
> ```

Calling `Close()` here with `reusable = false` is pretty unsafe, since it will put the iterator back in the `pebbleIterPool`, while the batch it is in will end up in `pebbleBatchPool`, resulting in cases where two threads could concurrently be using the same `pebbleIterator`. I actually made the same mistake a couple weeks ago, which is probably a testament to how managing reusable iterators can be confusing and why it's a good idea to consider ditching them altogether.

For now, you can probably just copy the relevant parts of `Close` (i.e. `*p = pebbleIterator{...}`) here and that's good enough.


<!-- Sent from Reviewable.io -->

2019-10-23 21:33 UTC, petermattis reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-:-LruWVlXDkyO5fsdWjOs:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_batch.go, line 114 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruNX-S9WQQtFw0-_7s:-LruW5ft-kgEepfN5koc:b-ulq115) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_batch.go#L114)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Is this just to mimic RocksDB behaviour, or do we actually do reads on distinct batches and expect them to fall through to the underlying db?
</blockquote></details>

We definitely use this for iteration. The change here was made to mimic the RocksDB behavior for tests in `batch_test.go`. I don't think we actually use this in any production code.
___
*[pkg/storage/engine/pebble_batch.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruJxgHAy_pdR5O4tAr:-LruVQBEADv09bVKFADP:bfegg6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/483063bb68cb76f6b9ae98abf6604d15e8431511/pkg/storage/engine/pebble_batch.go#L146)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Are we confident enough in ditching this TODO? Both performance-wise and correctness wise?

For eg. I just uncovered a minor issue in this area: I noticed that we sometimes end up running into the "iterator already in use" case where we expect a batch to be able to spawn two iterators at once. As a particular example, `resolveLocalIntents` in batchEval spins up one non-prefix iterator on a batch (the associated `Close` is in a defer), then calls `SetAbortSpan` which requests a prefix iterator on the same batch. This is fine in the RocksDB batch case since we cache a prefix and a non-prefix iterator. We could either mimic that setup here and cache two iterators, or just do no caching if the performance impact of that is negligible or none.
</blockquote></details>

Yeah, I'm confident of this performance-wise. Correctness is actually part of the motivation here. Creation of an iterator grabs an implicit snapshot. I'd prefer to mimic the behavior of RocksDB that we're getting by caching the iterator rather than having subtly different semantics.

Can you elaborate on the `resolveLocalIntents` problem? I haven't seen any test failures due to this. And the change here doesn't actually change the `iterator already in use` checking. 
___
*[pkg/storage/engine/pebble_iterator.go, line 519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruM8krAt4bFrRxR8pa:-LruVpXH4Bb-5d_YkwRQ:b-pgmw89) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_iterator.go#L519)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Calling `Close()` here with `reusable = false` is pretty unsafe, since it will put the iterator back in the `pebbleIterPool`, while the batch it is in will end up in `pebbleBatchPool`, resulting in cases where two threads could concurrently be using the same `pebbleIterator`. I actually made the same mistake a couple weeks ago, which is probably a testament to how managing reusable iterators can be confusing and why it's a good idea to consider ditching them altogether.

For now, you can probably just copy the relevant parts of `Close` (i.e. `*p = pebbleIterator{...}`) here and that's good enough.
</blockquote></details>

Good catch. I've reorganized the code so that `Close()` now calls `destroy()` instead. PTAL.


<!-- Sent from Reviewable.io -->

2019-10-23 21:50 UTC, itsbilal approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-:-LruaIlg6qUjtWzhHlae:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

___
*[pkg/storage/engine/pebble_batch.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruJxgHAy_pdR5O4tAr:-LruYJLr6jp8ZCfJJ4RR:b-rn66hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/483063bb68cb76f6b9ae98abf6604d15e8431511/pkg/storage/engine/pebble_batch.go#L146)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yeah, I'm confident of this performance-wise. Correctness is actually part of the motivation here. Creation of an iterator grabs an implicit snapshot. I'd prefer to mimic the behavior of RocksDB that we're getting by caching the iterator rather than having subtly different semantics.

Can you elaborate on the `resolveLocalIntents` problem? I haven't seen any test failures due to this. And the change here doesn't actually change the `iterator already in use` checking. 
</blockquote></details>

That makes sense, then - let's keep it this way and remove the TODO.

The issue I mentioned would fall under the umbrella of that TODO, but I could address it in a separate PR since it's unrelated to this change. It's not very well tested, but pops up every once in a while on a long running cluster

 Just skim through `resolveLocalIntents` in `batcheval/cmd_end_transaction.go`, and you'll notice that there's an open batch iterator for the lifetime of that function. There's one case inside it where it could also call `SetAbortSpan`, which does an MVCCGetProto, which does an MVCCGet, which creates a short-lived prefix iterator on the batch.

In the RocksDB case that's fine since the two are cached independently and we don't end up reusing the same iterator, but in our current implementatino we only cache one iterator, and flip prefix to true as necessary. I guess if preserving semantics is our priority, we probably should just cache two iterators and call it a day.
___
*[pkg/storage/engine/pebble_iterator.go, line 519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruM8krAt4bFrRxR8pa:-LruZaIuDvXaY7PABFV-:bheiuwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_iterator.go#L519)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Good catch. I've reorganized the code so that `Close()` now calls `destroy()` instead. PTAL.
</blockquote></details>

LGTM. There's a subtlety currently where calling `destroy` then `Close` could still leak a reusable iterator into the iterator pool, but looking at the places where we call `destroy` directly, I can't imagine any cases where it would happen. Plus `destroy` is unexported, so this seems safe.


<!-- Sent from Reviewable.io -->

2019-10-23 23:24 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

___
*[pkg/storage/engine/pebble_batch.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruJxgHAy_pdR5O4tAr:-Lrud28NCqES0bBxIn8g:b-j2frgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/483063bb68cb76f6b9ae98abf6604d15e8431511/pkg/storage/engine/pebble_batch.go#L146)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

That makes sense, then - let's keep it this way and remove the TODO.

The issue I mentioned would fall under the umbrella of that TODO, but I could address it in a separate PR since it's unrelated to this change. It's not very well tested, but pops up every once in a while on a long running cluster

 Just skim through `resolveLocalIntents` in `batcheval/cmd_end_transaction.go`, and you'll notice that there's an open batch iterator for the lifetime of that function. There's one case inside it where it could also call `SetAbortSpan`, which does an MVCCGetProto, which does an MVCCGet, which creates a short-lived prefix iterator on the batch.

In the RocksDB case that's fine since the two are cached independently and we don't end up reusing the same iterator, but in our current implementatino we only cache one iterator, and flip prefix to true as necessary. I guess if preserving semantics is our priority, we probably should just cache two iterators and call it a day.
</blockquote></details>

Hmm. Interesting. It might be worth separating the cached `prefix` and `normal` iterators like we do for RocksDB. I'll leave this to a follow-on PR.
___
*[pkg/storage/engine/pebble_iterator.go, line 519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LruM8krAt4bFrRxR8pa:-LrudE6B4b0ld-k8H1WE:bxez469) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d17a2668f73fc31f708d514f2684d4396cff052/pkg/storage/engine/pebble_iterator.go#L519)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

LGTM. There's a subtlety currently where calling `destroy` then `Close` could still leak a reusable iterator into the iterator pool, but looking at the places where we call `destroy` directly, I can't imagine any cases where it would happen. Plus `destroy` is unexported, so this seems safe.
</blockquote></details>

True. I've add a small mitigation which is to maintain the state of `p.reusable`. If `Close()` is subsequently called on a reusable iterator, we'll fall into the `if p.reusable` block.


<!-- Sent from Reviewable.io -->

2019-10-24 00:27 UTC, merged

2019-10-24 13:10 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 578 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LrxsKeq7mjdTMFSkxbE:-LrxsKeq7mjdTMFSkxbF:bs0eeir) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b01e7600d7b3f3b2c725234dd71f77586d61132/pkg/storage/engine/pebble.go#L578)):*
> ```Go
> 	}
> 
> 	if opts.MinTimestampHint != (hlc.Timestamp{}) {
> ```

is hlc.Timestamp{} the zero timestamp? Is it possible for the above to be false but the MaxTimestampHint to be provided?


<!-- Sent from Reviewable.io -->

2019-10-24 13:26 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41859)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 578 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41859#-LrxsKeq7mjdTMFSkxbE:-LrxtYW-8LkpUZ55maTQ:bvajev6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b01e7600d7b3f3b2c725234dd71f77586d61132/pkg/storage/engine/pebble.go#L578)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is hlc.Timestamp{} the zero timestamp? Is it possible for the above to be false but the MaxTimestampHint to be provided?
</blockquote></details>

Yes, `hlc.Timestamp{}` is the zero timestamp. That's a Go-ism.

The logic here is copied from the `RocksDB`. I'm not sure why only `MinTimestampHint` is checked. That seems fragile, but we always set both timestamps whenever time-bound iteration is requested.


<!-- Sent from Reviewable.io -->