WIP: testutils: Implement a light weight dependency injection mechanism.
cockroachdb/cockroach pull request #41933
Opened 2019-10-25 19:22 UTC by miretskiy

testvalue package provides a way for the production code to enable
the tests to do, essentially, a light weight dependency injection.
This package makes it possible to expose certain aspects of the
internal implemenation (such as return value of a call) to the tests,
and enables those tests to modify those internal attributes without
forcing to use heavy dependenchy injection mechanisms.

Server code:
  ....
  res, err := doSomething()
  testvalue.Adjust("inject_server_error", &err)
  ...

Test code:
  Enable()
  testvalue.Set("inject_server_error", error.New("bad error"))

This library will ensure that the adjusted values have correct types and are assignable
to the value in the first place.  The assignment through interface pointer is supported,
so the test could for example, inject a "mock" implementation should they wish to do so.

The values can also be set via a callback:
  testvalue.SetCallback("inject_server_error", func() interface{} { return myError })

The SetCallback() approach enables the tests to have more interesting use cases,
such as synchronizatgion between the test and the code under the test with minimal fuss.

Release note: None

2019-10-25 19:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41933)
<!-- Reviewable:end -->

2019-10-27 13:48 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41933)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @spaskob)

___
*[pkg/testutils/testvalue/testvalue.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCPvYD0Szyfh8h63Ol:-LsCPvYD0Szyfh8h63Om:b-tw9c1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue.go#L23)):*
> ```
> var enabled int32
> ```
maybe the 3 vars can go in common struct?

registry will be nil and you need to call Reset()
___
*[pkg/testutils/testvalue/testvalue.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCQuX08OVPhwvWWf3k:-LsCQuX08OVPhwvWWf3l:becczlo) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue.go#L104)):*
> ```Go
> 	// any reasons.  However, we try to provide a bit more interesting error messages to simplify debugging.
> 
> 	// Value must be a pointer type so that we can assign to it.
> ```

move the definition of val just above its first use
___
*[pkg/testutils/testvalue/testvalue.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCRGRB9zA5vPfZW62s:-LsCRGRB9zA5vPfZW62t:b3axvlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue.go#L106)):*
> ```Go
> 	// Value must be a pointer type so that we can assign to it.
> 	if val.Kind() != reflect.Ptr {
> 		panic(fmt.Sprintf("Cannot adjust non-ptr values for key '%s'", key))
> ```

usually Go people don't like using panic but insist on returning error instead. 
___
*[pkg/testutils/testvalue/testvalue.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCRR1i0CKjM2wQIVwT:-LsCRR1jD4vXaeEXJILd:bd9oai2) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue.go#L109)):*
> ```Go
> 	}
> 
> 	// Ensure we can assign override to *value.
> ```

haven't checked this code since I don't understand Go reflection
___
*[pkg/testutils/testvalue/testvalue_test.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCT3Uq7tjJcMYSvUIm:-LsCT3Ur0qRWTxXkVcCz:b-wmpssg) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue_test.go#L393)):*
> ```Go
> 
> 	Set("st", &stoppable{})
> 	Adjust("st", &st)
> ```

in your test Set and Adjust are called next to each other, it may be more instructive to the reader to the reader to have Adjust live in a separate function that you later set in the test.


<!-- Sent from Reviewable.io -->

2019-10-27 15:57 UTC, petermattis reviewed
Have you taken a look at `base/testing_knobs.go`? See `store/testing_knobs.go` for a concrete implementation. We've used the testing knobs approach to control both server configuration, and to provide hooks which are invoked by the internal implementation when certain events occur. I'm not sure what distinguishes light-weight from heavy-weight in this context, but there seems to be overlap in functionality here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-:-LsCv6sK9qrMb7Xef_7U:b-6932z4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)



<!-- Sent from Reviewable.io -->

2019-10-28 12:34 UTC, tbg commented
I'd like to gently push back on singletons. We run multi-node clusters in lots of tests and each instance should have its own set of testing hooks. I'd greatly prefer if you just used testing knobs. There are certainly shortcomings there but let's improve on them instead of building something new.

2019-10-28 14:48 UTC, miretskiy reviewed
Thanks for all your replies.  This pr is a work in progress; more to help me learn about Go (as a flex friday), but also see whether I could try to do some things that I have had some  success with in the past.

I'm curious though, why do you think that "each instance should have its own set of testing hooks" vs a unified mechanism?

I have seen test knobs, and I did find them to be rather cumbersome to use.  Probably because I'm rather new here... Of course, that might not be a reason enough not to use them.

Re light/heavy weight... one of the things that I dislike about dependency injection is that it has, kind of a "viral" type nature: you have to inject dependency into the public API, and you have to propagate those injections downstream.  Often enough, it's very hard to inject an artificial low level error, without propagating this kinda of injection from the very top of the call chain.  Which, of course, we can see happening with the test knobs (e.g. storage/testing_knobs include fields which are themselves testing knobs for some lower level systems).

In contrast, w/ test value, you do not need to pollute public api's with test knobs that have nothing todo with the API itself.  In that sense, I think test value is not "viral", and that's one of the reasons I really liked working with a similar package (at google).   Perhaps these concerns are less applicable to Go than they were in c++.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-:-LsHW0f_2y3KIlA-wDKm:bobsmcx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @spaskob)

___
*[pkg/testutils/testvalue/testvalue.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41933#-LsCRGRB9zA5vPfZW62s:-LsCfq6g29oThTayCLn1:b-11xuot) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bcb556be277978d54b1a66a6a6afa8045deefe/pkg/testutils/testvalue/testvalue.go#L106)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

usually Go people don't like using panic but insist on returning error instead. 
</blockquote></details>

I understand this.  However, I think in this case panic is not only justified, it's probably correct.
If we had something like c++ templates, then the compilation would fail if the types were incorrect, etc.
Alas, we're not c++, but, one could argue that calling Set() with incorrect types should be treated like a syntax
error.  The closes to that is panic.  


<!-- Sent from Reviewable.io -->

2019-11-05 03:46 UTC, dt commented
I think I prefer typed, component-specific TestingKnobs for if/when we need production code check/assert/etc values for tests: I like types and compiler-checked knobs and usage a lot more than strings and interface{}, and I also echo concerns about singletons. While we usually try to find other options first if we can (like a real, user-facing setting or inspection of trace data or whatever), for cases where those don't work, the FooKnobs pattern is already pretty established in many existing places in the codebase.

2019-11-05 14:03 UTC, closed without merging

2019-11-05 19:45 UTC, spaskob commented
For the purpose of my own engineering understanding of Cockroach, can somebody please explain here, preferably with a concrete example what exactly is wrong with singletons in this case?

2019-11-05 21:08 UTC, tbg commented
1. Test fails without resetting singleton: spray effects into the rest of
the test suite.
2. Test uses multi-cluster, but wants to set the hook only on one node.
Doesn't work with singletons.

Then there are additional concerns about this PR because nothing is typed,
so it's hard to mess up and maintain (little help from IDE tooling).

On Tue, Nov 5, 2019 at 8:45 PM Spas Bojanov <notifications@github.com>
wrote:

> For the purpose of my own engineering understanding of Cockroach, can
> somebody please explain here, preferably with a concrete example what
> exactly is wrong with singletons in this case?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ABGXPZH3UGMQG6KBDNIRG3TQSHEN3A5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDECPCQ#issuecomment-549988234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGXPZD2MIAG2BJA7GYRF4LQSHEN3ANCNFSM4JFHTD7Q>
> .
>

2019-11-05 21:17 UTC, miretskiy commented
Re 1. Test fails without resetting singleton: spray effects into the rest of
the test suite.

One could argue that there are numerous examples of singletons in the test
code base already, they simply are called by a different name:
$ git grep "()()"
Pretty much all of those are examples of a "singleton" like change to a
setting that, if you forget to defer reset, will spray out
into other tests.

So, yes, to use testvalue, you need to reset it -- just like you need to
reset in the cases above.

Re 2: clearly a deficiency right now -- I have, in all honesty, not given
it much thought to it.  The testvalue would still be useful, even without
addressing the multi cluster setup, though, it could probably be changed so
that the test values (somehow) are per node instance (so, perhaps, instead
of calling testvalue.Adjust(), youd' call cfg.TestKnobs.Adjust(...) (and
thus, you'd get easy of setting test values, and having them per node).


On Tue, Nov 5, 2019 at 4:08 PM Tobias Grieger <notifications@github.com>
wrote:

> 1. Test fails without resetting singleton: spray effects into the rest of
> the test suite.
> 2. Test uses multi-cluster, but wants to set the hook only on one node.
> Doesn't work with singletons.
>
> Then there are additional concerns about this PR because nothing is typed,
> so it's hard to mess up and maintain (little help from IDE tooling).
>
> On Tue, Nov 5, 2019 at 8:45 PM Spas Bojanov <notifications@github.com>
> wrote:
>
> > For the purpose of my own engineering understanding of Cockroach, can
> > somebody please explain here, preferably with a concrete example what
> > exactly is wrong with singletons in this case?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ABGXPZH3UGMQG6KBDNIRG3TQSHEN3A5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDECPCQ#issuecomment-549988234
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ABGXPZD2MIAG2BJA7GYRF4LQSHEN3ANCNFSM4JFHTD7Q
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ANA4FVF4TTLBRLLG4IYROPTQSHOF3A5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEKKYA#issuecomment-550020448>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVCXZD2L5OOMZLELSPTQSHOF3ANCNFSM4JFHTD7Q>
> .
>

2019-11-05 21:27 UTC, spaskob commented
Re 1: I agree with Yevgeniy, there are a bunch of tests that write to system.{jobs,tables, etc} or change the job registry and they suffer from the same problem.

2019-11-05 21:32 UTC, tbg commented
Right, but the fact that there are singletons doesn't mean there should be
more singletons. There should always be less singletons.

2019-11-05 21:34 UTC, miretskiy commented
So, taking those ()() singletons and replacing it with one that can do all
of that functionality should be preferable?

On Tue, Nov 5, 2019 at 4:33 PM Tobias Grieger <notifications@github.com>
wrote:

> Right, but the fact that there are singletons doesn't mean there should be
> more singletons. There should always be less singletons.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ANA4FVE6PWTLJFIGW7RTBRTQSHRBPA5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEMZAA#issuecomment-550030464>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVEIR4EQJNRD2R345Y3QSHRBPANCNFSM4JFHTD7Q>
> .
>

2019-11-05 21:35 UTC, miretskiy commented
I'm just saying that if a singleton will be brought in as a significant
issue affecting this PR, then we should be open to discussing
other wide-uses of singletons and why those are not considered to be
problematic.

On Tue, Nov 5, 2019 at 4:33 PM Yevgeniy Miretskiy <
yevgeniy@cockroachlabs.com> wrote:

> So, taking those ()() singletons and replacing it with one that can do all
> of that functionality should be preferable?
>
> On Tue, Nov 5, 2019 at 4:33 PM Tobias Grieger <notifications@github.com>
> wrote:
>
>> Right, but the fact that there are singletons doesn't mean there should be
>> more singletons. There should always be less singletons.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ANA4FVE6PWTLJFIGW7RTBRTQSHRBPA5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEMZAA#issuecomment-550030464>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANA4FVEIR4EQJNRD2R345Y3QSHRBPANCNFSM4JFHTD7Q>
>> .
>>
>

2019-11-05 21:52 UTC, tbg commented
> So, taking those ()() singletons and replacing it with one that can do all
of that functionality should be preferable?

No, I don't think this is necessarily true. We should invest in reducing the number of singletons, not building machinery that incentivizes new singletons.

> I'm just saying that if a singleton will be brought in as a significant
issue affecting this PR, then we should be open to discussing
other wide-uses of singletons and why those are not considered to be
problematic.

I consider all uses of singletons to be problematic. For some of them, the return on investment for removing them is not high enough right now, so they remain.

Ultimately, problems can be solved in many different ways, including the one you are advocating for. Much time can be spent arguing about which one is "best" and at the end, sometimes it comes down to personal preferences or a status quo. The status quo that has emerged here at CRL (after a fair amount of experimentation over the years) is that we try our best to avoid singletons and that we use testing knobs as the standard tool for injecting behavior during tests. It gets the job done, avoids the common pitfalls around dependency injection, and it's what we're familiar with. There'd have to be compelling reasons to do something else, which I personally am not seeing here.

2019-11-05 22:21 UTC, miretskiy commented
Your argument about the status quo is reasonable to me.

I do think that the existing status quo (vis-a-vis testing knobs) does have
some deficiencies.
From a quick glance, it seems that test knobs suffer from the following:
  * Many testing knobs are added and used form exactly 1 test.  Even so, we
have to add a testing know to some high level structure (e.g. server knobs).
     We are changing (effectively) some public API  in order to carry a
setting that's used from exactly 1 test.
  * Those testing knob structs become a kitchen sync of things.
  * It's not clear (or maybe even arbitrary) where a particular knob
belongs.
     If I want to change something in bulk import, do I added to "dist sql"
knob? server knob?  Stand along knob somewhere?
  * The use of test knobs is extremely cumbersome: example:
ca.flowCtx.TestingKnobs().Changefeed.(*TestingKnobs);
     That's a lot of hoops to jump through.  Not to mention, injection the
testing knob into (cluster/server) config is also an exercise in typing
agility.
     Seems to me that's a lot of work to set one testing option that's used
in 1 test.
     I do understand that Go is a verbose language, but the verbosity for
the sake of verbosity (as opposed to clarity) is certainly not what Go
should be about.
  * Lack of consistency: each testing knob is a bit different.

I did this work in progress/proof of concept precisely because I found it
to be incredibly unwieldy,  and cumbersome to inject a low level scheduling
channel.

Does this status quo work?  Yes, it does -- and I'm sure i'll be able to
get things done with or without testvalue; most likely by adding yet
another singleton or testing knob.

But I also want to make sure that we don't take "status quo" as a gospel
that should never be questioned or challenged.



On Tue, Nov 5, 2019 at 4:53 PM Tobias Grieger <notifications@github.com>
wrote:

> So, taking those ()() singletons and replacing it with one that can do all
> of that functionality should be preferable?
>
> No, I don't think this is necessarily true. We should invest in reducing
> the number of singletons, not building machinery that incentivizes new
> singletons.
>
> I'm just saying that if a singleton will be brought in as a significant
> issue affecting this PR, then we should be open to discussing
> other wide-uses of singletons and why those are not considered to be
> problematic.
>
> I consider all uses of singletons to be problematic. For some of them, the
> return on investment for removing them is not high enough right now, so
> they remain.
>
> Ultimately, problems can be solved in many different ways, including the
> one you are advocating for. Much time can be spent arguing about which one
> is "best" and at the end, sometimes it comes down to personal preferences
> or a status quo. The status quo that has emerged here at CRL (after a fair
> amount of experimentation over the years) is that we try our best to avoid
> singletons and that we use testing knobs as the standard tool for injecting
> behavior during tests. It gets the job done, avoids the common pitfalls
> around dependency injection, and it's what we're familiar with. There'd
> have to be compelling reasons to do something else, which I personally am
> not seeing here.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/41933?email_source=notifications&email_token=ANA4FVB65MTWX6GBSUL4MJLQSHTM7A5CNFSM4JFHTD72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDEOZRQ#issuecomment-550038726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVAHTJHR572FUGJK2KLQSHTM7ANCNFSM4JFHTD7Q>
> .
>