storage: Support nodelocal file access using NodeID
cockroachdb/cockroach pull request #41990
Opened 2019-10-29 15:08 UTC by g3orgia

In order to support importing from a specific node's local file
system, `ExternalStorage` needs an access to the blob service.
This PR plumbs through the `blobClient` to `ExternalStorage` and
uses that to access nodelocal files.

Many of the changes are related to tests that depended on nodelocal
and now need mock blob clients to run. The majority of code changes
are in `external_storage.go`.

Release notes (enterprise change):
When specifying a nodelocal file URI (ex. within `IMPORT`,`BACKUP`),
you can now specify which node's local file system you would like to
use. This is done by specifying that node's ID:
`nodelocal://<nodeID>/path/file.csv`

2019-10-29 15:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/41990)
<!-- Reviewable:end -->

2019-10-29 17:59 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @g3orgia, and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNeXLe7jn7aXOCJnI7:-LsNeXLfD9EQlMxIzH9Q:baegtu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L309)):*
> ```Go
> 	cfg        roachpb.ExternalStorage_LocalFilePath // contains un-prefixed filepath -- DO NOT use for I/O ops.
> 	base       string                                // relative filepath prefixed with externalIODir, for I/O ops on this node.
> 	blobClient blobs.BlobClient                      // inter-node file sharing service
> ```

One thing I was feeling when looking at the implementation of the blobs.BlobClient is that it's sort of a bummer that we create a new gRPC client connection for every RPC. I was worried to complicate that diff then but I wonder if what we really want here is a factory that takes a node ID and gives you back a client whose interface doesn't know about blob ID. It's not a big change and I think will clean up this code and make it more efficient when used to make a large number of RPCs. 
___
*[pkg/storage/cloud/external_storage.go, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNdBuB7jxBqo0Dok5m:-LsNdBuB7jxBqo0Dok5n:b-yc9xmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L321)):*
> ```Go
> 
> func makeNodeLocalURIWithNodeID(nodeID roachpb.NodeID, path string) string {
> 	return fmt.Sprintf("nodelocal://%d%s", nodeID, path)
> ```

isn't there supposed to be a slash here between the `%d` and the `%s`?
___
*[pkg/storage/cloud/external_storage_test.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNeF2S-HEVYmWPVCTT:-LsNeF2S-HEVYmWPVCTU:b41xgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage_test.go#L106)):*
> ```Go
> 		sampleBytes := "hello world"
> 
> 		// TODO(georgiah): is this a bug?
> ```

say more?


<!-- Sent from Reviewable.io -->

2019-10-30 15:19 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNeXLe7jn7aXOCJnI7:-LsSCKRg44r3ixEUAvAU:bsg9d6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L309)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One thing I was feeling when looking at the implementation of the blobs.BlobClient is that it's sort of a bummer that we create a new gRPC client connection for every RPC. I was worried to complicate that diff then but I wonder if what we really want here is a factory that takes a node ID and gives you back a client whose interface doesn't know about blob ID. It's not a big change and I think will clean up this code and make it more efficient when used to make a large number of RPCs. 
</blockquote></details>

Hmmm I'm unsure if I'm understanding the scope of these changes correctly. To do this, wouldn't we need to change the existing interface of the blob client? The instead of creating the grpc client connection within each call, we could have a client cache in the factory and pass that to every blob client created.
___
*[pkg/storage/cloud/external_storage.go, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNdBuB7jxBqo0Dok5m:-LsS2Ujv0vmr0R9PY_Ut:bci30gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L321)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

isn't there supposed to be a slash here between the `%d` and the `%s`?
</blockquote></details>

This takes in paths from blobClient.List() which already has a slash. I can add a trim, then add the slash to make this function more usable in other situations.
___
*[pkg/storage/cloud/external_storage_test.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNeF2S-HEVYmWPVCTT:-LsS2Ji73giK-vVP57v3:b4bkpxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage_test.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

say more?
</blockquote></details>

It was indeed a bug which it has since been fixed. Will remove this comment.


<!-- Sent from Reviewable.io -->

2019-10-30 15:25 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @g3orgia, and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNeXLe7jn7aXOCJnI7:-LsSG-fC1D5Je2aM_PPV:bh0ss1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L309)):*
>To do this, wouldn't we need to change the existing interface of the blob client? 

Sure, but nobody currently uses that interface and it will make the interface align with its one client's use case and seems like it will generally be an improvement. 

>The instead of creating the grpc client connection within each call, we could have a client cache in the factory and pass that to every blob client created.

Yes this could be a nice follow-on optimization but might require reference counting. 


<!-- Sent from Reviewable.io -->

2019-10-30 20:54 UTC, ajwerner requested changes
This seems much cleaner, thanks for making the change! 

> Reviewed 3 of 12 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-:-LsTRWWt27hQnQNPzFJb:b-4e9l40)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @g3orgia, and @lucy-zhang)

___
*[pkg/blobs/client.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTODu63bBR0MLcblQx:-LsTODu7DsUzQ4aW668D:bzf0raw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/blobs/client.go#L118)):*
> ```Go
> }
> 
> func (c *remoteClient) GetNodeID() roachpb.NodeID {
> ```

Do we need this anymore?
___
*[pkg/blobs/client.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTOL3H3DK2k1G4MIyq:-LsTOL3H3DK2k1G4MIyr:bprwvlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/blobs/client.go#L159)):*
> ```Go
> }
> 
> // BlobClientFactory creates a blob client based on the nodeID we are dialing.
> ```

How about moving the context up to here rather than taking it in NewBlobClientFactory? 
___
*[pkg/storage/cloud/external_storage.go, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsNdBuB7jxBqo0Dok5m:-LsTPmBLEgRjVnjYjmT_:bkkoitj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1e17483436ebe753d940b69e9d360f35f662aa9/pkg/storage/cloud/external_storage.go#L321)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

This takes in paths from blobClient.List() which already has a slash. I can add a trim, then add the slash to make this function more usable in other situations.
</blockquote></details>

Oh it was okay then I just wanted to make sure that it was an invariant that you'd always have a leading slash. I think I slightly prefer the explicitness of this and it's pretty much free so :thumbsup:
___
*[pkg/storage/cloud/external_storage.go, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTRLFi85WmlZZW1rop:-LsTRLFi85WmlZZW1roq:bb7qubv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/storage/cloud/external_storage.go#L374)):*
> ```Go
> 
> 	for _, fileName := range matches {
> 		fileList = append(fileList, makeNodeLocalURIWithNodeID(l.cfg.NodeID, fileName))
> ```

What about the case where `l.cfg.NodeID` is 0? I don't think this is going to do what we want, is it?


<!-- Sent from Reviewable.io -->

2019-10-30 22:03 UTC, g3orgia reviewed
Yeah, this is definitely much cleaner :) Seems like there's a few bugs (CI previously didn't run) with existing tests, fixing them right now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-:-LsTftfaCuWYoW3NlOtI:be4bl9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @lucy-zhang)

___
*[pkg/blobs/client.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTOL3H3DK2k1G4MIyq:-LsTfj6zCC5A4v3AkYfO:b-qeqdxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/blobs/client.go#L159)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How about moving the context up to here rather than taking it in NewBlobClientFactory? 
</blockquote></details>

Hmm as in make the Factory an object rather than a function?
___
*[pkg/storage/cloud/external_storage.go, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTRLFi85WmlZZW1rop:-LsTfDJt6maxXK7U4uKV:b-cvm31h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/storage/cloud/external_storage.go#L374)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What about the case where `l.cfg.NodeID` is 0? I don't think this is going to do what we want, is it?
</blockquote></details>

Ah yes, good catch. Will check for that case in that function `makeNodeLocalURIWithNodeID`.


<!-- Sent from Reviewable.io -->

2019-10-30 22:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @g3orgia, and @lucy-zhang)

___
*[pkg/blobs/client.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsTOL3H3DK2k1G4MIyq:-LsTplEs0lGdExx0swLr:b9z67rf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9ec9d559d5c303d695ccb543a414700de61f35f/pkg/blobs/client.go#L159)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

Hmm as in make the Factory an object rather than a function?
</blockquote></details>

As in:

```
type BlobClientFactory func(ctx context.Context, dialing roachpb.NodeID) (BlobClient, error)
```
and
```
func NewBlobClientFactory(
	localNodeID roachpb.NodeID, dialer *nodedialer.Dialer, externalIODir string,
) BlobClientFactory {
```


<!-- Sent from Reviewable.io -->

2019-10-31 21:20 UTC, ajwerner reviewed
> Reviewed 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @g3orgia, and @lucy-zhang)

___
*[pkg/blobs/local_storage.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsYfHfk-ufPPduGhDG4:-LsYfHfl4cEk2nvYd_QZ:b-z3zf9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e3293377a95bb308498fca78306abf6c750d4a1/pkg/blobs/local_storage.go#L99)):*
> ```Go
> 	var fileList []string
> 	for _, file := range matches {
> 		fileList = append(fileList, strings.TrimPrefix(file, l.externalIODir+"/"))
> ```

This is rather unfortunate because you're going to allocate a new string on every iteration through this loop. 

How about:

`strings.TrimPrefix(strings.TrimPrefix(file, l.externalIODir), "/")`


<!-- Sent from Reviewable.io -->

2019-11-01 17:49 UTC, thoszhang reviewed
Refactoring looks good, just a few minor comments.

> Reviewed 1 of 12 files at r1, 3 of 10 files at r2, 12 of 13 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-:-Lsc4UmuE19OhCXSfEal:byce6vq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @g3orgia)

___
*[pkg/blobs/testutils.go, line 20 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsbzao2AVnFHr1Vvs2b:-Lsbzao35TjyY2IBFCFW:b-4ombbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/blobs/testutils.go#L20)):*
> ```Go
> 
> // TestBlobServiceClient can be used as a mock BlobClient
> // in tests that use nodelocal storage
> ```

nit: add a period (same for comment below)
___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-Lsc3uZx9uVqfWArWiGd:bzbe37d) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
> ```Go
> }
> 
> func joinWithoutClean(path string, file string) string {
> ```

What is this for?


<!-- Sent from Reviewable.io -->

2019-11-01 18:09 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-Lsc8QW4-mLLvIduQ2Vv:b-qu06da) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

`filepath.Join()` also cleans the path. However, `Join("/../../blob", "file")` would turn into `/blob/file`, but we actually want to keep `/../../` since it is now simplified within the blob service.


<!-- Sent from Reviewable.io -->

2019-11-01 18:28 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-:-LscCNWG8-5g9lIrwSFS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscA1F8AWm2DvQIPclC:bu6nicy) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

`filepath.Join()` also cleans the path. However, `Join("/../../blob", "file")` would turn into `/blob/file`, but we actually want to keep `/../../` since it is now simplified within the blob service.
</blockquote></details>

My understanding is that the only place where the behavior of this function as it differs from `filepath.Join` are cases which would return an error. 

`filepath.Join` is indeed going to turn `/../../` into `/` because it's an absolute path. I suppose in this case we'd like to retain that prefix so in the implementation of the blob server it becomes`<external io dir>/../../` which will lead to an error in the server. One approach might instead be to do `filepath.Join(strings.TrimLeft(path, "/"), file)` which will make the path relative and will retain any leading `/../`. That ends up being pretty similar to this in complexity so I think I'm okay with it but a comment explaining why this exists would be helpful. 
___
*[pkg/storage/cloud/external_storage.go, line 1 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LscC9P1Bd8pCaV54UiP:-LscC9P211GlOA0_JU_G:b-6vkx9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/08ae4a4786969d4b3b0c6748d63874e96d9b2cfd/pkg/storage/cloud/external_storage.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

I feel like now that I know this file exists I really want to break it up into different files for the different implementations (not an action item for you, just a remark).


<!-- Sent from Reviewable.io -->

2019-11-01 18:44 UTC, thoszhang approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @g3orgia)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscE89-5jC8ZqREvHIJ:bzbhhjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My understanding is that the only place where the behavior of this function as it differs from `filepath.Join` are cases which would return an error. 

`filepath.Join` is indeed going to turn `/../../` into `/` because it's an absolute path. I suppose in this case we'd like to retain that prefix so in the implementation of the blob server it becomes`<external io dir>/../../` which will lead to an error in the server. One approach might instead be to do `filepath.Join(strings.TrimLeft(path, "/"), file)` which will make the path relative and will retain any leading `/../`. That ends up being pretty similar to this in complexity so I think I'm okay with it but a comment explaining why this exists would be helpful. 
</blockquote></details>

I guess you could have a path like `/../<external-io-dir>` or something, in which case we don't expect an error (I think). Anyway, I agree that a comment would be good.


<!-- Sent from Reviewable.io -->

2019-11-01 18:46 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscDyKbATGbXOBunKmz:b9wmt0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

I guess you could have a path like `/../<external-io-dir>` or something, in which case we don't expect an error (I think). Anyway, I agree that a comment would be good.
</blockquote></details>

nit: I think everything in here (that is delegating to blobClient as opposed hitting disk directly after this change) needs to use `path.{Join,Trim, ...}` instead of `filepath` -- the former always uses the standard, host-independent separator, whereas the latter is host-specific, so as long as a path still has the potential to be put in a network request, it should only use `path.Join` on it.

I'm still not _quiet_ clear why the wrapping doing an extra pass of cleaning is _wrong_ though? like, sure, it collapses `/foo/../` to `/`, but that still ends up the same path on the remote side after collapsing. and if they started their path relative (`../`), that won't be collapsed here at all (and will trigger an error when it _is_ collapsed when joined with the prefix since it'll stop matching the prefix). Can ou give an example of where doing the cleaning here results in reading the wrong path?


<!-- Sent from Reviewable.io -->

2019-11-01 18:56 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscInVUDKBiBfKBtLJz:bnjem16) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: I think everything in here (that is delegating to blobClient as opposed hitting disk directly after this change) needs to use `path.{Join,Trim, ...}` instead of `filepath` -- the former always uses the standard, host-independent separator, whereas the latter is host-specific, so as long as a path still has the potential to be put in a network request, it should only use `path.Join` on it.

I'm still not _quiet_ clear why the wrapping doing an extra pass of cleaning is _wrong_ though? like, sure, it collapses `/foo/../` to `/`, but that still ends up the same path on the remote side after collapsing. and if they started their path relative (`../`), that won't be collapsed here at all (and will trigger an error when it _is_ collapsed when joined with the prefix since it'll stop matching the prefix). Can ou give an example of where doing the cleaning here results in reading the wrong path?
</blockquote></details>

The example georgia provided I think is valid. Imagine the path is not relative but rather is absolute, say `/foo/../../` and the file is `bar`. `filepath.Join` will turn it into `/bar` which will then turn into `<externalIODir>/bar` which might be a valid file. It seems like the correct thing for it to turn into is into `<externalIODir>/../bar` which will be an error. I think the trick is that we want to make sure `path` here is not absolute.

I _think_ `filepath.Join("./", path, file)` will do what we want. 


<!-- Sent from Reviewable.io -->

2019-11-01 18:58 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscKAxI98BuYujZkBwL:bmctn8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The example georgia provided I think is valid. Imagine the path is not relative but rather is absolute, say `/foo/../../` and the file is `bar`. `filepath.Join` will turn it into `/bar` which will then turn into `<externalIODir>/bar` which might be a valid file. It seems like the correct thing for it to turn into is into `<externalIODir>/../bar` which will be an error. I think the trick is that we want to make sure `path` here is not absolute.

I _think_ `filepath.Join("./", path, file)` will do what we want. 
</blockquote></details>

Or rather `filepath.Join(".", path, file)`


<!-- Sent from Reviewable.io -->

2019-11-01 19:23 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscLjRpA5xWB0yYrmkz:b1wtfiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Or rather `filepath.Join(".", path, file)`
</blockquote></details>

This was discovered in [this failing test](https://github.com/cockroachdb/cockroach/blob/c669035fb744bc1710f1c333e1d0a82ac642e86a/pkg/ccl/backupccl/backup_test.go#L2862). It backs up to `nodelocal:///../../blah` and expects an external directory error, but could not find this error because the backup went to `<externalIODir>/blah`.

Seems like @ajwerner 's suggestion, `path.Join(".", path, file)` works, since it's a clean way to make this path relative. Going to change to that, making sure we use `path` instead of `filepath`.


<!-- Sent from Reviewable.io -->

2019-11-01 20:30 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/storage/cloud/external_storage.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-Lsc3uZx9uVqfWArWiGc:-LscKMbw3knYdr02Rsli:bq0ncok) ([raw file](https://github.com/cockroachdb/cockroach/blob/73772830da0746f2fedca576cee803b460f146ab/pkg/storage/cloud/external_storage.go#L361)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

This was discovered in [this failing test](https://github.com/cockroachdb/cockroach/blob/c669035fb744bc1710f1c333e1d0a82ac642e86a/pkg/ccl/backupccl/backup_test.go#L2862). It backs up to `nodelocal:///../../blah` and expects an external directory error, but could not find this error because the backup went to `<externalIODir>/blah`.

Seems like @ajwerner 's suggestion, `path.Join(".", path, file)` works, since it's a clean way to make this path relative. Going to change to that, making sure we use `path` instead of `filepath`.
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2019-11-04 16:15 UTC, ajwerner reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @g3orgia and @lucy-zhang)

___
*[pkg/testutils/lint/lint_test.go, line 1194 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsrBr3o7hI3fuYHQL9E:-LsrBr3pA1KLQzK9YtVK:b5ys57j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecf6e3c21d5dc721df3db36218cfd7b6c5a09f4/pkg/testutils/lint/lint_test.go#L1194)):*
> ```Go
> 			stream.GrepNot(`cockroach/pkg/server/debug/pprofui: path$`),
> 			stream.GrepNot(`cockroach/pkg/util/caller: path$`),
> 			stream.GrepNot(`cockroach/pkg/storage/cloud: path$`),
> ```

What's going on here?


<!-- Sent from Reviewable.io -->

2019-11-04 16:25 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/testutils/lint/lint_test.go, line 1194 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41990#-LsrBr3o7hI3fuYHQL9E:-LsrCC2y40O0r2J_NPIb:b-yjnuwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fecf6e3c21d5dc721df3db36218cfd7b6c5a09f4/pkg/testutils/lint/lint_test.go#L1194)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What's going on here?
</blockquote></details>

This lint test checks that we import `path/filepath` instead of `path` because that's what we should be using in most cases. This test used ignoring that check for `storageccl` where the`storage/cloud` package was recently moved from. As David mentioned, we should be using `path` here, so we need to ignore this package from the `path` check.


<!-- Sent from Reviewable.io -->

2019-11-04 16:51 UTC, g3orgia commented
bors r=ajwerner,lucy-zhang

2019-11-04 18:28 UTC, g3orgia commented
bors r=ajwerner,lucy-zhang

2019-11-04 21:19 UTC, g3orgia commented
bors r+

2019-11-04 22:03 UTC, merged