sql: Add column family support for secondary indexes
cockroachdb/cockroach pull request #42073
Opened 2019-10-31 18:52 UTC by rohany

In order to proceed with primary key changes work, primary
indexes need to be made less "special", which involves allowing
secondary indexes to support as many of the same features as
primary indexes as possible. This PR adds support for column
families to be respected by secondary indexes.

Secondary indexes respect the family definitions applied
to tables, and break secondary index k/v pairs into mulitple
depending on the family and stored column configurations.

This PR adds and details an extension of the primary index
column family encoding for secondary indexes, and implements it.

This encoding was implemented by updating how secondary indexes are
encoded and decoded in `EncodeSecondaryIndex` and the fetchers.

The way that the column families have been encoded means that this
will work on indexes that haven't been encoded with column families,
and will make interpreting a primary key's encoded column families easy.

Release note (sql change): Allow secondary indexes to respect column family
definitions upon they table they are on.

2019-10-31 18:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42073)
<!-- Reviewable:end -->

2019-11-07 04:59 UTC, jordanlewis requested changes
Great work so far! Really excited about the PR.

My main comment is that this needs way more tests. Encoding is very subtle (as I'm sure you have found out already :). The only way to make sure that we've gotten it correct is to write tests.

Does @mjibson's column family randomizer tool help here? Or maybe it's already doing its magic?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-:-Lt3DQ0e8b0jmJ4uXC-K:bvjtez2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @RaduBerinde, @rohany, and @solongordon)

___
*[docs/tech-notes/encoding.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zGs372yEndLHq5Ep:-Lt2zGs372yEndLHq5Eq:bg1278x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L286)):*
> ```Markdown
> for each indexed column, the data therein are non-null and equal.
> 
> Secondary indexes have been extended to include support for column families.
> ```

Be more clear about when this change is happening. Imagine someone reading this doc in its entirety without knowledge of this migration.
___
*[docs/tech-notes/encoding.md, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zSqV1WimkhY0lVWP:-Lt2zSqV1WimkhY0lVWQ:bj9qew2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L321)):*
> ```Markdown
> ### Value encoding
> 
> If the value corresponds to column family 0:
> ```

This is still for secondary indexes right? Leave that in.
___
*[docs/tech-notes/encoding.md, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zb6M3tRntuVZOhgJ:-Lt2zb6M3tRntuVZOhgK:b7ux72e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L323)):*
> ```Markdown
> If the value corresponds to column family 0:
> 
> The KV value will have value type bytes, and consists of
> ```

nit: grammar - tense doesn't agree (will have vs consists of)
___
*[docs/tech-notes/encoding.md, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zsDM2zSFmHma_Qxk:-Lt2zsDM2zSFmHma_Qxl:btv9ik6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L339)):*
> ```Markdown
> KV key and the KV value. (Ditto for stored column data in the old format.)
> 
> Else the KV Value will have value type `TUPLE` and consists of all stored
> ```

Be more explicit about this else - this is a text document not a program. Say "For indexes with more than 1 column family, the non-0th column families KV values will..."
___
*[docs/tech-notes/encoding.md, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3-FSi-nzRtaAcU0-K:-Lt3-FSi-nzRtaAcU0-L:b-wmhzz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L342)):*
> ```Markdown
> columns in that family in the `TUPLE` encoded format.
> 
> ### Backwards Compatibility
> ```

For what? Be more explicit here so it's clear to future readers.
___
*[pkg/sql/colencoding/key_encoding.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3-YuS8FSl5Zt_tFk3:-Lt3-YuS8FSl5Zt_tFk4:bjaccny) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colencoding/key_encoding.go#L238)):*
> ```Go
> // TODO(jordan): each type could be optimized here.
> // TODO(jordan): should use this approach in the normal row fetcher.
> // TODO(rohany): what is the approach in the normal row fetcher?
> ```

I think the normal row fetcher doesn't try to skip table key values at all if they're not necessary. It just decodes everything. Look at `DecodeKeyVals`.
___
*[pkg/sql/colexec/cfetcher.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt34tAgEhLNJzVasWyb:-Lt34tAgEhLNJzVasWyc:b-5c7hps) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L374)):*
> ```Go
> 			// Primary indexes only contain ascendingly-encoded
> 			// values. If this ever changes, we'll probably have to
> 			// figure out the directions here too.
> ```

Hmm... do we have to worry about this? Can you test your new code with descending index columns too? Same comment for fetcher.go.
___
*[pkg/sql/colexec/cfetcher.go, line 661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt30Ih0EJOwSfB9taew:-Lt30Ih16mGR_zOKeEbe:baxan96) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L661)):*
> ```Go
> 			// is that the extra columns are not always there, and are used to unique-ify
> 			// the index key, rather than provide the primary key column values.
> 			if rf.table.isSecondaryIndex && rf.table.index.Unique && len(rf.table.desc.Families) != 1 {
> ```

We should only do this logic if the secondary index has nullable columns. Also, if this condition gets much more complex, you shouldn't recheck it for every single key. It's statically known, so you can figure it out at the start of the run of the fetcher and cache it as a single boolean.
___
*[pkg/sql/colexec/cfetcher.go, line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt31hkNEZSTDKYkCQ-K:-Lt31hkNEZSTDKYkCQ-L:b-ayssq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L664)):*
> ```Go
> 				// TODO (rohany): we don't want to have to look at each indexed value twice (once
> 				//  while decoding and once here). A possible optimization is to pass whether a
> 				//  null was encountered while decoding and use that information here instead.
> ```

Yeah, this is going to make scans signinficantly slower I'm pretty sure. I think this optimization is very worthwhile. The fetchers are very performance sensitive and it's worth checking the impact here.
___
*[pkg/sql/sqlbase/index_encoding.go, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3CHS30-TkN34yMRbW:-Lt3CHS30-TkN34yMRbX:bi7gwsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L813)):*
> ```Go
> 		}
> 
> 		// TODO (rohany): do I need to skip this logic for an inverted index?
> ```

Good question... do you? Inverted indexes I don't think should have column families at all. And you definitely won't be able to make them primary later - they're fundamentally different beasts (a single database row can have more than one corresponding entries in a single inverted index).
___
*[pkg/sql/sqlbase/index_encoding.go, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3ChDzClGj0LzsCaHo:-Lt3ChDzClGj0LzsCaHp:b-yuzd53) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L820)):*
> ```Go
> 			// Copy the key, as we will modify it and move it into the resulting IndexEntry.
> 			entryKey := make([]byte, len(key))
> 			copy(entryKey, key)
> ```

This isn't necessary on the first iteration (which is the most common case). Can we avoid?
___
*[pkg/sql/sqlbase/index_encoding.go, line 825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3D6F4-fN_0e3Q-5G9:-Lt3D6F4-fN_0e3Q-5GA:b4ktk72) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L825)):*
> ```Go
> 			// TODO (rohany): make this faster by computing this up front with
> 			//  fastIntSets? I wonder if there was a way to reuse this computed
> 			//  information across calls to EncodeSecondaryIndex.
> ```

You should definitely precompute this. Otherwise it's like a duplicate N^2 loo [...]

2019-11-08 00:13 UTC, rohany reviewed
Yeah, matts column family randomizer is running already -- it caught a bunch of bugs already!

I updated the PR with alot of the TODO optimizations implemented, and added a bunch of more detailed k/v trace tests that helped find some more bugs. 

Working on this more opened some more TODO's, so PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-:-Lt5UFbNAqSqfo9S5A1A:b-9xcr8u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @RaduBerinde, and @solongordon)

___
*[docs/tech-notes/encoding.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zGs372yEndLHq5Ep:-Lt6e7dm6oZi3ayjRPb6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L286)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Be more clear about when this change is happening. Imagine someone reading this doc in its entirety without knowledge of this migration.
</blockquote></details>

Done.
___
*[docs/tech-notes/encoding.md, line 321 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zSqV1WimkhY0lVWP:-Lt6eeTZ2kK9yKWaKV48:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L321)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is still for secondary indexes right? Leave that in.
</blockquote></details>

Done.
___
*[docs/tech-notes/encoding.md, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt2zsDM2zSFmHma_Qxk:-Lt6f20DE8COdOVtpnX7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L339)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Be more explicit about this else - this is a text document not a program. Say "For indexes with more than 1 column family, the non-0th column families KV values will..."
</blockquote></details>

Done.
___
*[docs/tech-notes/encoding.md, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3-FSi-nzRtaAcU0-K:-Lt6fUHu7A9owSksMQNj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/docs/tech-notes/encoding.md#L342)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

For what? Be more explicit here so it's clear to future readers.
</blockquote></details>

Done.
___
*[pkg/sql/colencoding/key_encoding.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3-YuS8FSl5Zt_tFk3:-Lt5UNDe18aT_gO30X7G:br3zv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colencoding/key_encoding.go#L238)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think the normal row fetcher doesn't try to skip table key values at all if they're not necessary. It just decodes everything. Look at `DecodeKeyVals`.
</blockquote></details>

oh ok -- i think i read this originally as "should use the approach in the normal row fetcher" and was confused why we didn't want to skip columns
___
*[pkg/sql/colexec/cfetcher.go, line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt34tAgEhLNJzVasWyb:-Lt5UeyN5SoNSZGTQtqU:b-pb74zp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L374)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... do we have to worry about this? Can you test your new code with descending index columns too? Same comment for fetcher.go.
</blockquote></details>

I don't think we have to worry about this for this PR -- will have to double check this once the primary key compatibility changes in the fetcher go through. Either way, we can ensure that the new candidate primary key has ascending columns as well (as a first step).
___
*[pkg/sql/colexec/cfetcher.go, line 661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt30Ih0EJOwSfB9taew:-Lt6Z_tf9nj4_i5OPxL1:b-c8ted7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L661)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We should only do this logic if the secondary index has nullable columns. Also, if this condition gets much more complex, you shouldn't recheck it for every single key. It's statically known, so you can figure it out at the start of the run of the fetcher and cache it as a single boolean.
</blockquote></details>

I added the optimization below, so the check here can remain simple -- these current booleans and whether or not a null was actually decoded.
___
*[pkg/sql/colexec/cfetcher.go, line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt31hkNEZSTDKYkCQ-K:-Lt6Z_eQ3A2AYlXxtqkG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/colexec/cfetcher.go#L664)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah, this is going to make scans signinficantly slower I'm pretty sure. I think this optimization is very worthwhile. The fetchers are very performance sensitive and it's worth checking the impact here.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3CHS30-TkN34yMRbW:-Lt6Nbfi7pFcQg1a1drY:bqyvhtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L813)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Good question... do you? Inverted indexes I don't think should have column families at all. And you definitely won't be able to make them primary later - they're fundamentally different beasts (a single database row can have more than one corresponding entries in a single inverted index).
</blockquote></details>

Makes sense -- i'll move back to the existing logic for the inverted indexes just to be safe.
___
*[pkg/sql/sqlbase/index_encoding.go, line 820 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3ChDzClGj0LzsCaHo:-Lt5YCWPD2j9gRsfxfHT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L820)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This isn't necessary on the first iteration (which is the most common case). Can we avoid?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 825 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lt3D6F4-fN_0e3Q-5G9:-Lt6NVHOCERdr1FF30C2:bnfteft) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1114bd9cbca8e9fd9adeb94c5b3cd84184d2f56/pkg/sql/sqlbase/index_encoding.go#L825)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You should definitely precompute this. Otherwise it's like a duplicate N^2 loop on every key we're encoding.  Also, it's pointless in the common case of 1 column family. Should we just have a special case for that vs more than 1?
</blockquote></details>

Done -- I have to look into how to precompute this information across calls to EncodeSecondaryIndex. That might have to be the work of a future PR.


<!-- Sent from Reviewable.io -->

2019-11-14 18:04 UTC, rohany commented
Friendly ping

2019-11-14 18:11 UTC, danhhz commented
Dunno if you're waiting on me, but I'm going to remove myself as one of the reviewers. Happy to hash out high level tradeoffs around column families but my knowledge of the details has rotted too much to be of any use.

2019-11-14 18:13 UTC, rohany commented
> Dunno if you're waiting on me, but I'm going to remove myself as one of the reviewers. Happy to hash out high level tradeoffs around column families but my knowledge of the details has rotted too much to be of any use.

Oh my bad -- i thought you were still familiar with this area. Thanks for your help earlier with going through the high level details!

2019-11-15 14:09 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, @rohany, and @solongordon)

___
*[docs/tech-notes/encoding.md, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LtjO2fX4XPzW5A-XT0A:-LtjO2fX4XPzW5A-XT0B:b-29wg7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/308a389bbe51d26a31bfa12762b62a73139ee958/docs/tech-notes/encoding.md#L347)):*
> ```Markdown
> 
> Because the key and value encodings for column family 0 have not changed,
> we can read indexes encoded without column family support without any changes.
> ```

How does this work exactly? If I have an index that has the old encoding on-disk and I want to read a specific family (being able to do that is kind of the point of families), I won't scan family 0. I would need to know that I can't scan specific families with this index.


<!-- Sent from Reviewable.io -->

2019-11-15 16:27 UTC, rohany commented
> How does this work exactly? If I have an index that has the old encoding on-disk and I want to read a specific family (being able to do that is kind of the point of families), I won't scan family 0. I would need to know that I can't scan specific families with this index.

Thats a good point -- there are definitely cases like this where we wont want to use the encoding with families, so a versioning mark on the index descriptor is needed. I think the core of what I was trying to get at is that there doesn't need to be any special casing done for reading old encodings at the fetcher level, because the old encoding is compatible with the new one.

2019-11-15 16:57 UTC, RaduBerinde commented
Yeah, that makes sense - a mark on the descriptor that tells us that the index has all rows encoded using the current families.

2019-11-15 17:01 UTC, rohany commented
Having a mark on the descriptor will also allow me to not have to plumb a cluster.settings object all the way down to encode key, which is something i left as a todo :)

2019-11-20 23:23 UTC, jordanlewis reviewed
So I think this is good, and I'm happy that @mjibson's column family randomizer exists as I think it has high potential to flush bugs out of this code.

I am nervous about cross version testing though. We need to figure out a way to test data that's half 19.2 and half 20.1 - tables that have indexes with the old format and some new format? 

Also what about just indexes that have some new data and some old? Or wait, is that not possible?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-:-LuA6HZu857KnpCO1Wbz:bfov88o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, @rohany, and @solongordon)

___
*[docs/tech-notes/encoding.md, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LtjO2fX4XPzW5A-XT0A:-Lu3jPrcDWKQdA93cErF:bbzion3) ([raw file](https://github.com/cockroachdb/cockroach/blob/308a389bbe51d26a31bfa12762b62a73139ee958/docs/tech-notes/encoding.md#L347)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How does this work exactly? If I have an index that has the old encoding on-disk and I want to read a specific family (being able to do that is kind of the point of families), I won't scan family 0. I would need to know that I can't scan specific families with this index.
</blockquote></details>

Does this need an update now that you have the version bit?
___
*[pkg/sql/create_table.go, line 1046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9w7yg2NLtib6sT04s:-Lu9w7yh8uSMxXh4s8ak:b9pfqvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/create_table.go#L1046)):*
> ```Go
> 		version.IsActive(cluster.VersionSecondaryIndexColumnFamilies) {
> 		indexEncodingVersion = sqlbase.SecondaryIndexFamilyFormatVersion
> 	}
> ```

Are these the only two spots where we make index descriptors from scratch?
___
*[pkg/sql/row/helper.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9wqgFA2CNiE5qKXXy:-Lu9wqgFA2CNiE5qKXXz:b-itrvla) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/helper.go#L73)):*
> ```Go
> }
> 
> // encodePrimaryIndex encodes the primary index keys.
> ```

nit: Isn't this key singular? 
___
*[pkg/sql/row/updater.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9z61YDXTVuSQMfc91:-Lu9z61YDXTVuSQMfc92:b-2xvddg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L142)):*
> ```Go
> 		// TODO (rohany): I'm unsure what this means from the comment about
> 		//  it above -- when are you ever going to update something but not
> 		//  the secondary indexes?
> ```

If you update part of a primary key that isn't touched by any secondary indexes, you won't need to update them. e.g.:

```
create table a (a int, b int, primary key c int);
create index on a(a);
update a set b=3 where c=5;
```

In this case, there's no need to edit the index entries for the secondary index.
___
*[pkg/sql/row/updater.go, line 356 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA-C0O8DpdjpDO-Hyz:-LuA-C0O8DpdjpDO-Hz-:b-yp5ygy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L356)):*
> ```Go
> 	// TODO (rohany): clean up some unused fields in the updater helper if this change looks good.
> 	oldIndexEntries := make([][]sqlbase.IndexEntry, len(ru.Helper.Indexes))
> 	newIndexEntries := make([][]sqlbase.IndexEntry, len(ru.Helper.Indexes))
> ```

This feels pretty sad to me - I think that adding more allocations like this is something we'd really rather avoid. I'd be okay merging as is if you promise to reduce right afterwards, but I do think this will materially affect performance - update is a hot path!
___
*[pkg/sql/row/updater.go, line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA5wOS2mCw_-7fwG9O:-LuA5wOS2mCw_-7fwG9P:bn2j36i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L387)):*
> ```Go
> 				//  * The only difference between column family 0 vs other families encodings is
> 				//    just the family key ending of the key, so if index[0] is different, the other
> 				//    index entries will be different as well.
> ```

Yes that seems legit to me.
___
*[pkg/sql/row/updater.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA63M_-Hv8i-oQinE_:-LuA63M_-Hv8i-oQinEa:bgdu722) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L449)):*
> ```Go
> 				var expValue *roachpb.Value
> 				if !bytes.Equal(oldEntry.Key, newEntry.Key) {
> 					// TODO (rohany): this check is duplicated here and above, is there a reason?
> ```

Where is above?


<!-- Sent from Reviewable.io -->

2019-11-20 23:32 UTC, rohany reviewed
Yeah, we should test it. However, i don't imagine it being a problem -- neither of those should result in errors. We only create indexes with the column family encode on clusters that are fully 20.1 (by the check in create index / create table), and all existing indexes will have the version bit == to the non family encoding.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-:-LuA94-O7o9p_ipyy7cL:b-mtu4nh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @solongordon)

___
*[docs/tech-notes/encoding.md, line 347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LtjO2fX4XPzW5A-XT0A:-LuA89mD6CPmORGvg88Q:b-gs2ifs) ([raw file](https://github.com/cockroachdb/cockroach/blob/308a389bbe51d26a31bfa12762b62a73139ee958/docs/tech-notes/encoding.md#L347)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this need an update now that you have the version bit?
</blockquote></details>

yep, will do.
___
*[pkg/sql/create_table.go, line 1046 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9w7yg2NLtib6sT04s:-LuA8Cwn6nNjzG8MrA4C:b-run0y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/create_table.go#L1046)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Are these the only two spots where we make index descriptors from scratch?
</blockquote></details>

I believe so -- if I missed a place then the index will default to the version without column families, so it's still safe. I'll look more before the next update.
___
*[pkg/sql/row/helper.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9wqgFA2CNiE5qKXXy:-LuA8OY605gIewNxWtIr:bb7sa0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/helper.go#L73)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: Isn't this key singular? 
</blockquote></details>

yes.
___
*[pkg/sql/row/updater.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9z61YDXTVuSQMfc91:-LuA8aBz2WnR-ZQfJ1E4:bp7vbga) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L142)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If you update part of a primary key that isn't touched by any secondary indexes, you won't need to update them. e.g.:

```
create table a (a int, b int, primary key c int);
create index on a(a);
update a set b=3 where c=5;
```

In this case, there's no need to edit the index entries for the secondary index.
</blockquote></details>

sounds good.
___
*[pkg/sql/row/updater.go, line 356 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA-C0O8DpdjpDO-Hyz:-LuA8bad0GHMrbUJhRNy:bds2o2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L356)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This feels pretty sad to me - I think that adding more allocations like this is something we'd really rather avoid. I'd be okay merging as is if you promise to reduce right afterwards, but I do think this will materially affect performance - update is a hot path!
</blockquote></details>

Ok, i can look to see if I can move these allocations into creation. At this pass I was working towards correctness.
___
*[pkg/sql/row/updater.go, line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA5wOS2mCw_-7fwG9O:-LuA8hcjE4sLcJy4wlji:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L387)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yes that seems legit to me.
</blockquote></details>

nice
___
*[pkg/sql/row/updater.go, line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA63M_-Hv8i-oQinE_:-LuA92Lw-oIOcP95cQyz:bic74mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L449)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Where is above?
</blockquote></details>

line 388 in this file.


<!-- Sent from Reviewable.io -->

2019-11-21 00:32 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @solongordon)

___
*[pkg/sql/row/updater.go, line 142 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-Lu9z61YDXTVuSQMfc91:-LuAGTch86Z7tInFmYYg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L142)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

sounds good.
</blockquote></details>

Done.
___
*[pkg/sql/row/updater.go, line 356 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA-C0O8DpdjpDO-Hyz:-LuAJ-fy6mfdwdx-9UMm:b-ghtyd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L356)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Ok, i can look to see if I can move these allocations into creation. At this pass I was working towards correctness.
</blockquote></details>

Updated. There are some other performance improvements that I can make an issue for an implement after.
___
*[pkg/sql/row/updater.go, line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuA5wOS2mCw_-7fwG9O:-LuAGUtd5Z6Rm7m6Pcv9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee5c5af98fbf29ec8dbc239ff2aebe710d2ed8a/pkg/sql/row/updater.go#L387)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

nice
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-11-21 00:33 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @solongordon)

___
*[pkg/sql/sqlbase/system.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuAN4fD81Adb4MtZ0Zd:-LuAN4fD81Adb4MtZ0Ze:bsr370t) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a8cb5ca56dfbe4d829d50e5c6ac07751ef84ec/pkg/sql/sqlbase/system.go#L324)):*
> ```Go
> 			ColumnDirections: []IndexDescriptor_Direction{IndexDescriptor_ASC, IndexDescriptor_ASC},
> 			ColumnIDs:        []ColumnID{1, 2},
> 			Version:          SecondaryIndexFamilyFormatVersion,
> ```

Am I supposed to change this stuff?? Will it have an impact on tables in earlier versions?


<!-- Sent from Reviewable.io -->

2019-11-21 14:59 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, @RaduBerinde, and @solongordon)

___
*[pkg/sql/sqlbase/system.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuAN4fD81Adb4MtZ0Zd:-LuDTMwh8kw3uwdehxgB:b-8o4qi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a8cb5ca56dfbe4d829d50e5c6ac07751ef84ec/pkg/sql/sqlbase/system.go#L324)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Am I supposed to change this stuff?? Will it have an impact on tables in earlier versions?
</blockquote></details>

Hmm... this is a great question. It will not have impact on tables in earlier versions. I am not sure if this is a valid change. @dt would you weigh in?


<!-- Sent from Reviewable.io -->

2019-12-02 05:28 UTC, jordanlewis reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> besides the unknown about the thing @dt is tagged on.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-:-Lv44Asm3aiWOaERp6Th:b-gyndwu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @solongordon)

___
*[pkg/sql/sqlbase/system.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuAN4fD81Adb4MtZ0Zd:-Lv445eXETTEMUOgojiY:bbdt7eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a8cb5ca56dfbe4d829d50e5c6ac07751ef84ec/pkg/sql/sqlbase/system.go#L324)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm... this is a great question. It will not have impact on tables in earlier versions. I am not sure if this is a valid change. @dt would you weigh in?
</blockquote></details>

Ping @dt 


<!-- Sent from Reviewable.io -->

2019-12-03 15:00 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/sqlbase/system.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuAN4fD81Adb4MtZ0Zd:-LvBFSdCD1YVIR-0VW8R:b-336yh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a8cb5ca56dfbe4d829d50e5c6ac07751ef84ec/pkg/sql/sqlbase/system.go#L324)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ping @dt 
</blockquote></details>

Uhh. I'm pretty out of the loop on descriptors and bootstrapping but I'm pretty sure this will only affect what is written on initial cluster creation and then what is used in a handful of unit tests. I don't know if you _need_ to change this since you need a migration for existing descriptors anyway but I don't think it hurts anything either.


<!-- Sent from Reviewable.io -->

2019-12-03 15:12 UTC, rohany commented
I had to change these to stop a bunch of unittests from failing -- do you know how/who to ask so we can confirm this only affects initial cluster creation?

2019-12-04 18:34 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42073)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/sqlbase/system.go, line 324 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42073#-LuAN4fD81Adb4MtZ0Zd:-LvHAAIG8b7X1iACPj8F:bvhhrrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/26a8cb5ca56dfbe4d829d50e5c6ac07751ef84ec/pkg/sql/sqlbase/system.go#L324)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Uhh. I'm pretty out of the loop on descriptors and bootstrapping but I'm pretty sure this will only affect what is written on initial cluster creation and then what is used in a handful of unit tests. I don't know if you _need_ to change this since you need a migration for existing descriptors anyway but I don't think it hurts anything either.
</blockquote></details>

to clarify, changing this would be expected to make the unit test that the descriptor matches the result of `CREATE TABLE` pass, but my point above was that this only affects _new_ clusters -- on existing clusters, these tables already exist, so depending on _what_ tests are failing, that could be an indication that it is actually important that existing descriptors get migrated too?


<!-- Sent from Reviewable.io -->

2019-12-04 18:37 UTC, rohany commented
Only the tests that were checking that executing the corresponding `create table` statement on these special tables created the corresponding hardcoded table descriptors were failing

2019-12-04 18:42 UTC, rohany commented
I'm looking at some earlier commits that bump versions on table descriptors / index descriptors and they change these without including migrations.

2019-12-04 20:10 UTC, rohany commented
I don't think we'd want a migration for this in the first place -- the existing indexes are encoded with the old format, and we wouldn't want to bump them up to the new format (without rewriting all of their data). Only when a new cluster is created should the new version be used.

2019-12-04 20:34 UTC, rohany commented
I'm going to go ahead and try merging this!

bors r=jordanlewis

2019-12-04 21:09 UTC, merged