blobs: Stream large files between nodes
cockroachdb/cockroach pull request #42071
Opened 2019-10-31 18:35 UTC by g3orgia

Currently, the blob service reads and write large files across
different nodes by sending the entire file across the wire. This
cannot support larger files.

This PR adds support for streaming files across to another node
by implementing an `io.ReadCloser` which uses gRPC's streaming
API underneath.

Release note: None

2019-10-31 18:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42071)
<!-- Reviewable:end -->

2019-10-31 21:47 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @g3orgia)

___
*[pkg/blobs/client_test.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlpSlCNKU1shnHuOH:-LsYlpSlCNKU1shnHuOI:b-bjjkcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/client_test.go#L170)):*
> ```Go
> 		t.Run(tc.name, func(t *testing.T) {
> 			ctx := context.TODO()
> 			reader, _ := blobClient.ReadFile(ctx, tc.nodeID, tc.filename)
> ```

How come you're ignoring this error now?
___
*[pkg/blobs/blobspb/blobs.proto, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlXsg2XOXYBSgfPPb:-LsYlXsg2XOXYBSgfPPc:b-un0mxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/blobspb/blobs.proto#L85)):*
> ```protobuf
> // files that are stored on a node's local file system.
> service Blob {
>   rpc GetBlob(GetRequest) returns (GetResponse) {}
> ```

You can drop these now right?
___
*[pkg/blobs/streaming/stream.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlSydCAjxiu5XBIo4:-LsYlSydCAjxiu5XBIo5:b53l1fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

I'm not sure this warrants its own package. 
___
*[pkg/blobs/streaming/stream.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlCcV6ii4KJxfMBjh:-LsYlCcV6ii4KJxfMBji:b-wkjtxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L102)):*
> ```Go
> 	}
> 
> 	// Fill remaining space with 0, this should only happen if we reach EOF.
> ```

This doesn't seem right to me. I think you are supposed to return io.EOF and the number of bytes you actually wrote to the buffer. 


<!-- Sent from Reviewable.io -->

2019-11-01 18:35 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/blobs/client_test.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlpSlCNKU1shnHuOH:-LscCdCu5Ao1TaCUhXKv:bb6mubt) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/client_test.go#L170)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How come you're ignoring this error now?
</blockquote></details>

Because the errors we are interested in are now within the `io.ReadCloser`, as we're reading the file. Will add a check to directly fail the test if an error occurs here.
___
*[pkg/blobs/blobspb/blobs.proto, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlXsg2XOXYBSgfPPb:-LscCwbl6qfdI9mt6R9w:bdsz2at) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/blobspb/blobs.proto#L85)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You can drop these now right?
</blockquote></details>

Right, meant to ask, do we directly remove functions no longer in use, or just comment them out? What about the implementation itself?
___
*[pkg/blobs/streaming/stream.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlSydCAjxiu5XBIo4:-LscDBXn06cLLsw6vY6I:boyok3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not sure this warrants its own package. 
</blockquote></details>

Okay, will put it directly in blobs, and rename some of the functions.
___
*[pkg/blobs/streaming/stream.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlCcV6ii4KJxfMBjh:-LscDKwm6YdsELfD2TGB:b-1wv4ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L102)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This doesn't seem right to me. I think you are supposed to return io.EOF and the number of bytes you actually wrote to the buffer. 
</blockquote></details>

I thought this was part of `Read()`'s responsability. After re-reading `io.Reader`'s interface comments, seems like that's not the case. Will remove this.


<!-- Sent from Reviewable.io -->

2019-11-01 18:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @g3orgia)

___
*[pkg/blobs/blobspb/blobs.proto, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlXsg2XOXYBSgfPPb:-LscG7QIC1iVDypLmFy9:bivqigg) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/blobspb/blobs.proto#L85)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

Right, meant to ask, do we directly remove functions no longer in use, or just comment them out? What about the implementation itself?
</blockquote></details>

You could remove it from the proto and remove the impl. I might leave it for now so we can do some benchmarking and come and clean it up later. Just add a TODO?
___
*[pkg/blobs/streaming/stream.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LscGENd0Wr7P-kmfOhr:-LscGENeCtxsxxGPHmR7:bqzt5nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L19)):*
> ```Go
> )
> 
> const chunkSize = 4 * 1024
> ```

I'd love to see some benchmarks about throughput of streaming at different chunk sizes vs buffering the whole thing in ram vs the local impl.

Just a microbenchmark test a la https://golang.org/pkg/testing/#hdr-Benchmarks for each of these configurations in the blobs package would be very cool.
___
*[pkg/blobs/streaming/stream.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlCcV6ii4KJxfMBjh:-LscH33L2JdEUgK_Zg9Y:bi2yei8) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L102)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

I thought this was part of `Read()`'s responsability. After re-reading `io.Reader`'s interface comments, seems like that's not the case. Will remove this.
</blockquote></details>

I'm a bit alarmed that this behavior didn't produce test failures. It seems to me like the only way this can possibly not produce test failures is if the read buffers are always aligned with the file sizes or the test is busted. Maybe make sure you can make a test fail with this before getting rid of it. 


<!-- Sent from Reviewable.io -->

2019-11-01 18:54 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/blobs/streaming/stream.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LscGENd0Wr7P-kmfOhr:-LscJJKB-CG41N1GQGwB:buoyb35) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L19)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd love to see some benchmarks about throughput of streaming at different chunk sizes vs buffering the whole thing in ram vs the local impl.

Just a microbenchmark test a la https://golang.org/pkg/testing/#hdr-Benchmarks for each of these configurations in the blobs package would be very cool.
</blockquote></details>

Sounds good, will add some benchmarking tests.
___
*[pkg/blobs/streaming/stream.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlCcV6ii4KJxfMBjh:-LscIlQB4nbEnk2SDOYA:b963yll) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L102)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm a bit alarmed that this behavior didn't produce test failures. It seems to me like the only way this can possibly not produce test failures is if the read buffers are always aligned with the file sizes or the test is busted. Maybe make sure you can make a test fail with this before getting rid of it. 
</blockquote></details>

Hmm this doesn't change `offset`, it should only fill the space after offset with zeros, then return the original number of bytes we wrote. 


<!-- Sent from Reviewable.io -->

2019-11-01 19:11 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/blobs/streaming/stream.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LsYlCcV6ii4KJxfMBjh:-LscNE9LELiKy7P2R6-f:b5c245p) ([raw file](https://github.com/cockroachdb/cockroach/blob/afac7ec8967a2546395f463ccaf3a8181a5eb3e4/pkg/blobs/streaming/stream.go#L102)):*
<details><summary><i>Previously, g3orgia (Georgia Hong) wrote…</i></summary><blockquote>

Hmm this doesn't change `offset`, it should only fill the space after offset with zeros, then return the original number of bytes we wrote. 
</blockquote></details>

Whoops missed that. Carry on. 


<!-- Sent from Reviewable.io -->

2019-11-05 19:51 UTC, g3orgia reviewed
I ran the benchmark tests that we talked about and the results can be found [here](https://docs.google.com/spreadsheets/d/1YBN9aFLjYiKLNgQPRiEK_bbEUB49twt5M3d9_A4qP38/edit?usp=sharing).
Here's the [code](https://github.com/g3orgia/cockroach/blob/streaming-benchmark/pkg/blobs/bench_test.go) that was used.
In these tests, `ReadFile` and `WriteFile` were both benchmarked for difference file sizes for the following cases:
- Without streaming
- With different streaming chunk sizes (8K, 32K, 64K, 128K, 256K)

Follow results [link](https://docs.google.com/spreadsheets/d/1YBN9aFLjYiKLNgQPRiEK_bbEUB49twt5M3d9_A4qP38/edit?usp=sharing) for graphs. Some conclusions gathered:
- For files 1 MB or smaller, streaming did not make a significant difference
- For files 1 MB < size < 64 MB, as chunk size went up, so did throughput
- For files >64 MB, thoughput peaks or flattens out at chunk size = 128K

Based on these results, I've changed the chunk size to 128K and removed the no streaming implementation.
Lemme know if that seems reasonable @ajwerner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-:-Lsx6XltA9s3H_zFX1so:bl4kq6n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2019-11-05 21:08 UTC, ajwerner commented
There's a lot of variance in the numbers. It might be interesting to run it `go test ./pkg/blobs --bench . --benchtime 10x --count 5 --benchmem 2>&1 | tee out` and save the results and cat them to `benchstat` (which you can install with `go get golang.org/x/perf/cmd/benchstat`). I'd also add an even larger chunk sizes just to be sure, maybe also 512 and 1M.

2019-11-06 19:48 UTC, g3orgia commented
I've run the benchmarking with `count=5` and added the results to the [spreadsheet](https://docs.google.com/spreadsheets/d/1YBN9aFLjYiKLNgQPRiEK_bbEUB49twt5M3d9_A4qP38/edit?usp=sharing). Seems like `ReadFile` does not actually flatten out nearly as much as the first run, and instead keeps getting more efficient as chunk sizes go up. `WriteFile` does still seem to be more efficient at `chunksize=128K`. @ajwerner In this case, does it seem reasonable to keep the chunk size at 128K?

2019-11-06 20:30 UTC, ajwerner reviewed
nice this is close.

> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-:-Lt1PG0i-mt2tgJIS1IH:b-dkyck8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @g3orgia)

___
*[pkg/blobs/client.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1LRHR45tJmLFPf632:-Lt1LRHR45tJmLFPf633:b-nftt7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/client.go#L78)):*
> ```Go
> 		return
> 	}
> 	err = streamContent(stream, content)
> ```

this feels awkward to defer something with no logic after it. 
___
*[pkg/blobs/client_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1G_VL8xdlcug4HucK:-Lt1G_VL8xdlcug4HucL:bmuvm2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/client_test.go#L255)):*
> ```Go
> 			err = blobClient.WriteFile(ctx, tc.filename, bytes.NewReader(byteContent))
> 			if err != nil {
> 				if tc.err != "" && testutils.IsError(err, tc.err) {
> ```

nit: I think just `testutils.IsError` will work for the `nil, nil` case too so this can be:

```
if !testutils.IsError(err, tc.err) {
   t.Fatalf("unexpected error: got %v, expected %v", err, tc.err)
}
```
___
*[pkg/blobs/service.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1H2L15VLK1OGSjdvs:-Lt1H2L15VLK1OGSjdvt:b-4z17yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/service.go#L65)):*
> ```Go
> 		return errors.New("could not fetch metadata")
> 	}
> 	filename := md.Get("filename")
> ```

Can you make sure to test that
1) this slice isn't empty (it'd be a bug but it is still possible)
2) the first element is a non-empty string (this is even more possible and would end up failing if the external io dir exists but I could see it being super problematic if the external io dir didn't exist). 
___
*[pkg/blobs/stream.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1Lsx-5HlUYMzvwPp0:-Lt1Lsx-5HlUYMzvwPp1:b-njo5df) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L19)):*
> ```Go
> )
> 
> var chunkSize = 128 * 1 << 10
> ```

Now that you've run the numbers, add some commentary to justify it. 
___
*[pkg/blobs/stream.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1HjyB5u7W_XaV5FKg:-Lt1HjyB5u7W_XaV5FKh:bq8himq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L30)):*
> ```Go
> }
> 
> // nopSendAndClose creates a GetStreamClient that has a nop SendAndClose function
> ```

This all needs some explanation about why it's used. My sense is that we should still close the stream when we call `Close` even though the call is different. Maybe call this `getStreamReceiver` and have `SendAndClose` actually just call `Close`?
___
*[pkg/blobs/stream.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1IXEV1oBaaF9ppT0x:-Lt1IXEV1oBaaF9ppT0y:b-bag01y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L43)):*
> ```Go
> func newGetStreamReader(client blobspb.Blob_GetStreamClient) io.ReadCloser {
> 	return &blobStreamReader{
> 		lastPayload: nil,
> ```

no need to initialize zero values. this is just
```
return &blobStreamReader{
    stream:  &nopSendAndClose{client},
}
```
___
*[pkg/blobs/stream.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1Icrx9qwyod3NMxrp:-Lt1Icrx9qwyod3NMxrq:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L53)):*
> ```Go
> // to read chunks of data.
> func newPutStreamReader(client blobspb.Blob_PutStreamServer) io.ReadCloser {
> 	return &blobStreamReader{
> ```

same as above
___
*[pkg/blobs/stream.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1Kk8mAVrrqIEoL6AQ:-Lt1Kk8mAVrrqIEoL6AR:b-3n3rka) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L119)):*
> ```Go
> // streamContent splits the content into chunks, of size `chunkSize`,
> // and streams those chunks to sender.
> func streamContent(sender streamSender, content io.Reader) error {
> ```

Please comment that this call does not close the stream. 
___
*[pkg/blobs/stream.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1NPrX8v3uIvEYDfIQ:-Lt1NPrX8v3uIvEYDfIR:b-bdvejy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L121)):*
> ```Go
> func streamContent(sender streamSender, content io.Reader) error {
> 	for {
> 		payload := make([]byte, chunkSize)
> ```

It turns out we can reuse these messages after each call to send returns so there's a big efficiency win to be had here. Note that this fact is not well documented in grpc.

```
payload := make([]byte, chunkSize)
var chunk blobspb.StreamChunk
...
for {
    n, err := content.Read(payload)
    if n > 0 {
        chunk.Payload = payload[:n]
        err = sender.Send(&chunk)
    }
    ...
}
```


<!-- Sent from Reviewable.io -->

2019-11-06 21:59 UTC, g3orgia reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/blobs/client.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1LRHR45tJmLFPf632:-Lt1TCq_-OipMfgSdyCo:b2o8d7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/client.go#L78)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this feels awkward to defer something with no logic after it. 
</blockquote></details>

Oh right, I was trying to figure out how to return the error from `CloseAndRecv()`, but this is supposed to go before `streamContent(stream, content)`. Changed this.
___
*[pkg/blobs/client_test.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1G_VL8xdlcug4HucK:-Lt1UYCVB-Xq7l2K9DkA:b-3mgfzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/client_test.go#L255)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I think just `testutils.IsError` will work for the `nil, nil` case too so this can be:

```
if !testutils.IsError(err, tc.err) {
   t.Fatalf("unexpected error: got %v, expected %v", err, tc.err)
}
```
</blockquote></details>

Oh yes, it does handle that case, that's much cleaner thanks!
___
*[pkg/blobs/stream.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1HjyB5u7W_XaV5FKg:-Lt1aEjeBT5riT6aMxja:b-k5mbqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L30)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This all needs some explanation about why it's used. My sense is that we should still close the stream when we call `Close` even though the call is different. Maybe call this `getStreamReceiver` and have `SendAndClose` actually just call `Close`?
</blockquote></details>

As discussed offline, will add a comment explaining why this is needed.
___
*[pkg/blobs/stream.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-Lt1NPrX8v3uIvEYDfIQ:-Lt1XxHV0XMJ0L7VRx_0:b-a86kwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab94b18fd2214c4aa2cffff4d85d2da4222737b2/pkg/blobs/stream.go#L121)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It turns out we can reuse these messages after each call to send returns so there's a big efficiency win to be had here. Note that this fact is not well documented in grpc.

```
payload := make([]byte, chunkSize)
var chunk blobspb.StreamChunk
...
for {
    n, err := content.Read(payload)
    if n > 0 {
        chunk.Payload = payload[:n]
        err = sender.Send(&chunk)
    }
    ...
}
```
</blockquote></details>

This is good to know, thanks! Changed it.


<!-- Sent from Reviewable.io -->

2019-11-11 15:43 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-:-LtQ7TcXAE59yKcJYsbZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @g3orgia)

___
*[pkg/blobs/stream.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42071#-LtQ70p3CdouIKOwBnI3:-LtQ70p3CdouIKOwBnI4:b-gv2iy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6880f76875fdd25ec4cda26c92afe056f5d5005f/pkg/blobs/stream.go#L19)):*
> ```Go
> )
> 
> /*
> ```

nit: I don't stumble upon `/*...*/` multi-line comments often. We generally still prefix every line with `//`


<!-- Sent from Reviewable.io -->

2019-11-11 17:41 UTC, g3orgia commented
bors r+

2019-11-11 17:48 UTC, g3orgia commented
bors r+

2019-11-11 18:35 UTC, g3orgia commented
bors r+

2019-11-11 19:13 UTC, merged