roachpb: clarify why DeleteRanges update the timestamp cache
cockroachdb/cockroach pull request #42382
Opened 2019-11-11 22:24 UTC by andreimatei

Fix the explanation of why DeleteRange updates the write timestamp cache.
The comment used to talk about "phantom deletes", but I think that was
wrong. Instead, I now talk about "lost deletes".
In the literature, phantoms refer to transactional scans that return
different results when repeated within the same transaction. CRDB
doesn't allow any sort of phantoms because of MVCC - as long as a txn is
tied to a timestamp (i.e. a database snapshot), and we don't allow a
read's history to be changed, then scans are repeatable by definition.
Updating the write timestamp cache (or, in general, _a_ timestamp cache)
has to do with wanting to avoid anomalies akin to the "lost update" one,
where transactions trample each other's writes.

Release note: None

2019-11-11 22:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42382)
<!-- Reviewable:end -->

2019-11-11 22:26 UTC, bdarnell approved these changes
Does this mean you've convinced yourself that these deletes of empty space matter and must not be lost?

2019-11-11 23:07 UTC, andreimatei commented
> Does this mean you've convinced yourself that these deletes of empty space matter and must not be lost?

Not particularly... But I've convinced myself that reasoning about which serializability anomalies are "ok" (according to snapshot isolation) and which aren't is a fool's errand (or at least requires more galaxy brain than I have).
By losing deletes of empty space, you can get anomalies that feel a bit different than write skew... I guess... I think it comes down to what you think is admissible for the following:

```sql
table t(key string, val int);

txn 1: delete from t where key >= 'a' and key <= 'z'; <insert some random keys>; insert into _sum1 select sum(val) from t;
txn 2: delete from t where key >= 'a' and key <= 'z'; <insert some random keys>; insert into _sum2 select sum(val) from t;
```

Would you expect (under snapshot isolation) for at least one of the sums to be correct at any given time? You might, on the account that the write sets are supposed to always intersect...

2019-11-12 12:48 UTC, tbg requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42382)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @spencerkimball)

___
*[pkg/roachpb/api.go, line 1049 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42382#-LtUa7YI5O_Con9WPmkx:-LtUa7YI5O_Con9WPmky:b-iq7vjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e82ce45efbb8ed1b63e7e546ba6c3b8e20cf4dc/pkg/roachpb/api.go#L1049)):*
> ```Go
> 	// the lost delete anomaly. Note that, even without it, delete of keys that
> 	// exist would not be lost (since the DeleteRange leaves intents on those
> 	// keys), but deletes of "empty space" would.
> ```

How about this:

DeleteRange only leaves intents on the keys it deletes, but semantically it wants to guarantee that the whole key range is empty at the timestamp at which it ultimately commits. Without some sort of timestamp cace protection, we could have the following history involving txn1 and txn2:

- txn1 runs DeleteRange([a,c)) at ts=100, so it lays down an intent on a (the only kv pair it sees).
- txn2 runs Put(b) at ts=50
- txn2 runs Put(d) at ts=50
- txn2 commits
- txn1 runs Get(d) at ts=100

txn1 must serialize after txn2 because it reads txn2's write at d, but in that order on `[a,c)` we should end up with an empty keyspace since the DeleteRange ought to shadow the Put(b). But it does not.

I don't understand why DeleteRange updates the *write* timestamp cache though. It seems equivalent to say that DeleteRange logically first scans the range, then issues point deletes. The scan would update the read timestamp cache, which should have the same effect. I might be missing some way in which the timestamp cache is queried that makes a difference.

Furthermore, DeleteRange needs to pick up refresh spans, as the flags below indicate it does. If not, we can get the following:

- txn1 runs DeleteRange[a,c) at ts=100, puts intent on `a`, populates tscache with 100
- txn2 runs Put(b) at ts=101
- txn1 gets pushed elsewhere, it refreshes to 102 (note that we assume that it does not refresh `[a,c)`, which would fail)
- txn2 writes Put(d) at ts=101
- txn2 commits
- txn1 reads d
- txn1 commits

Again, txn2 needs to serialize before txn1, but again [a,c) is not empty after both have applied.

Consider adding both of these examples into the comment, and consider also adding a nod to this method in the `DeleteRangeRequest` comment. With both in place, it seems clear that when a DeleteRange commits at some timestamp T, the keyspace will actually be empty (at T).


<!-- Sent from Reviewable.io -->

2019-11-12 15:42 UTC, bdarnell commented
> Would you expect (under snapshot isolation) for at least one of the sums to be correct at any given time? You might, on the account that the write sets are supposed to always intersect...

Yeah, this seems like a violation of snapshot isolation to me.

> I might be missing some way in which the timestamp cache is queried that makes a difference.

Andrei and I think it mattered for snapshot isolation, but in serializable there's no difference.

2019-11-12 17:00 UTC, tbg commented
> Andrei and I think it mattered for snapshot isolation, but in serializable there's no difference.

What's the "it" here? DeleteRange definitely needs to update *a* timestamp cache, and I just wonder why it didn't always just update the read timestamp cache. I think the answer is just "it could have".

> Yeah, this seems like a violation of snapshot isolation to me.

How so? It's not even clear to me how to characterize the allowed anomalies under SNAPSHOT. Is this "just" write skew?

2019-11-12 18:10 UTC, bdarnell commented
> What's the "it" here? DeleteRange definitely needs to update a timestamp cache, and I just wonder why it didn't always just update the read timestamp cache.

"It" refers to the use of the write timestamp cache instead of the read one.

> How so? It's not even clear to me how to characterize the allowed anomalies under SNAPSHOT. Is this "just" write skew?

My (informal) model is that write skew is characterized by overlapping read sets but disjoint write sets. Here we have overlapping write sets so I think it's something different from write skew. But I haven't gone back to Adya to see exactly how things are formally defined.

2019-11-12 22:08 UTC, andreimatei reviewed
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42382#-:-LtWdhl33PM7nem2s3N2:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spencerkimball and @tbg)

___
*[pkg/roachpb/api.go, line 1049 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42382#-LtUa7YI5O_Con9WPmkx:-LtWcaTABvzTyZBRMQq-:blmyvmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e82ce45efbb8ed1b63e7e546ba6c3b8e20cf4dc/pkg/roachpb/api.go#L1049)):*
I've added some nods to the timestamp cache and refreshes in a comment on the DeleteRange proto.

I've massaged my comment a bit to refer to snapshot isolation in relation to the _write_ timestamp cache.
Beyond that, I've only stated that the DeleteRange doesn't want anybody writing below it. Why that is I think it's obvious enough, so I haven't done much with your comment...

> I don't understand why DeleteRange updates the write timestamp cache though

Beyond the discussion at the top, I'll say that I'll get rid of the write timestamp cache and then it'll all become moot.


<!-- Sent from Reviewable.io -->

2019-11-12 22:33 UTC, merged

2019-11-13 10:50 UTC, tbg commented on pkg/roachpb/api.go
> +	// it forces subsequent writes to get a write-too-old error and avoids the
Ah, that's what I was missing.