release-19.2: IMPORT CSV experimental_save_rejected support
cockroachdb/cockroach pull request #42391
Opened 2019-11-12 02:29 UTC by spaskob

Backport:
  * 1/1 commits from "importccl: enabling saving of bad csv rows to a side file" (#41430)
  * 1/1 commits from "importccl: move parsing of the input files in a separate function" (#41864)
  * 1/1 commits from "importccl: refactor out all business logic from the processor" (#41909)
  * 1/1 commits from "importccl: remove unnecessary interface function" (#41972)
  * 1/1 commits from "importccl: add experimental_save_rejected option to CSV IMPORT " (#42112)

Please see individual PRs for details.

/cc @cockroachdb/release

2019-11-12 02:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42391)
<!-- Reviewable:end -->

2019-11-12 15:43 UTC, bdarnell requested changes
We shouldn't be introducing new features (especially experimental ones) in patch releases.

2019-11-12 16:12 UTC, dt commented
This change was intended to move the `experimental_save_rejected` functionality that was added to the the `DELIMITED` format in 19.2 to also apply to the `CSV` format, as the customer for whom it was introduced is now using CSV instead. I think we _do_ want to backport this for them, since added to 19.2 at their request, but as discussed offline, we'll wait to do so in 19.2.2, in case any serious bugs are discovered in 19.2.0 in the coming weeks that require a quick release of a pure-bug-fix 19.2.1. 


In the meantime, @spaskob and I are going to look though this again to see if there are any ways to minimize the backport diff further / more tightly confine it to just the applicable CSV code (i.e. if there is any way to not include the `runImport` refactor / leave the no-op inputFinished calls for now, etc).

2020-03-31 14:37 UTC, dt commented
I think we ended up not wanting to add this in a patch release after all, and with 20.1 coming out in the coming weeks, i think we can close this.

2020-03-31 14:50 UTC, closed without merging