jobs: allow jobs to be created and started separately
cockroachdb/cockroach pull request #42521
Opened 2019-11-15 23:48 UTC by ajwerner

Prior to this commit, if a creator of a job wanted to get the results it would
have to create and start it at the same time by calling jobs.Registry.StartJob.
That method would take a jobs.Record, create a new *jobs.Job and start it
immediately, sending results on a passed channel and returning an error
channel.

This is awkward because sometimes callers might want to do other work on the
same transaction which is creating the job. Furthermore those callers might
not want to start the job until after the creating transaction commits.

This refactor provides a mechanism for callers to create and store a job
in a transaction and then start it after that transaction commits.

Here's an example:

```
j := registry.NewJob(record)
if err := db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
    if err := j.WithTxn(txn).Created(ctx); err != nil {
        return err
    }
    ...
}); err != nil {
    ...
}
resultsCh := make(chan tree.Datums)
errCh, err := j.Start(ctx, resultsCh)
...
```

Release note: None

2019-11-15 23:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42521)
<!-- Reviewable:end -->

2019-11-15 23:49 UTC, ajwerner commented
I typed this in my protected timestamp PR, figured I'd pull it out.

2019-11-16 04:03 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @spaskob)

___
*[pkg/jobs/jobs.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmKsaf04c_kvgC2_xb:-LtmKsaf04c_kvgC2_xc:bb9zkyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L493)):*
> ```Go
> 	}
> 
> 	j.mu.Lock()
> ```

Was there a race condition here previously?
___
*[pkg/jobs/registry.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmNHS6E79GCkHlQbcp:-LtmNHS6E79GCkHlQbcq:b-y82082) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/registry.go#L223)):*
> ```Go
> 	// DEFAULT unique_rowid(), to avoid a race condition where the job exists
> 	// in the jobs table but is not yet present in our registry, which would
> 	// allow another node to adopt it.
> ```

This comment block belongs above r.makeJobID() statement


<!-- Sent from Reviewable.io -->

2019-11-17 11:15 UTC, spaskob reviewed
I added some comments, not sure if you see them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-Ltt3pbHDIdpIj83SBXG:b-kvjlax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)



<!-- Sent from Reviewable.io -->

2019-11-17 11:50 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[pkg/jobs/jobs.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LttA7n_B39B00vZ4XzX:-LttA5SU5x-xBJ9xuyW7:b-dulml6) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L105)):*
> ```Go
> // Start starts a previously unstarted job. The job may already have been
> // created but must not have ever been started.
> func (j *Job) Start(ctx context.Context, resultsCh chan<- tree.Datums) (<-chan error, error) {
> ```

Would it make more sense for this function to be called on a registry by passing the job as param, since the registry is responsible for the lifecycle management of jobs? Also the code of startJob is also in registry, so this makes it easier for the reader of the code.


<!-- Sent from Reviewable.io -->

2019-11-17 13:40 UTC, ajwerner reviewed
I see them. Other than the moving of the method does the high level approach make sense?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-Ltt_nKs1wFI5Zu5oIHf:bdyng3l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/jobs/jobs.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LttA7n_B39B00vZ4XzX:-LttZWzZAPZKdtHFheCM:b-7pko8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L105)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Would it make more sense for this function to be called on a registry by passing the job as param, since the registry is responsible for the lifecycle management of jobs? Also the code of startJob is also in registry, so this makes it easier for the reader of the code.
</blockquote></details>

It very much makes sense. I just wasn't clear on what to call it given we have `StartJob`. Maybe I'll move the existing one to `CreateAndStartJob`?
___
*[pkg/jobs/jobs.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmKsaf04c_kvgC2_xb:-LttZ9tR6emLjtQNb4LG:bqk6wss) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L493)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Was there a race condition here previously?
</blockquote></details>

Look at all the accessors. The mutex and comments imply that things are safe for concurrency and yet we don't use it all here. Imagine somebody calls `Job.Progress()` and `Job.Update()` concurrently. 

Either way, this should be in a different PR. I'll remove it. 
___
*[pkg/jobs/registry.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmNHS6E79GCkHlQbcp:-LttZ65nDkpgf5vQOUWr:b-7iq8w5) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/registry.go#L223)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

This comment block belongs above r.makeJobID() statement
</blockquote></details>

true.


<!-- Sent from Reviewable.io -->

2019-11-17 14:13 UTC, ajwerner reviewed
This didn't totally work because when we were creating jobs (using `Created()`) outside of `StartJob()` and we weren't giving the job a lease (see `Job.insert()` which opens them up to being started by other nodes. Should be fixed now. 

See how this makes you feel. I don't have super strong feelings, I just knew you were messing around in this area and felt like I should share this at the very least for the sake of discussion of the approach. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-Ltte9dY4JuEmUILqrlH:buujkit)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)



<!-- Sent from Reviewable.io -->

2019-11-18 00:03 UTC, spaskob approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @spaskob)

___
*[pkg/jobs/jobs.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LttA7n_B39B00vZ4XzX:-LtvmXFD2C-b46snSFqZ:bexs0hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L105)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It very much makes sense. I just wasn't clear on what to call it given we have `StartJob`. Maybe I'll move the existing one to `CreateAndStartJob`?
</blockquote></details>

thanks, that's long name but precise
___
*[pkg/jobs/jobs.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmKsaf04c_kvgC2_xb:-Ltvmh4l12hwC485-C5o:b89wdux) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L493)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Look at all the accessors. The mutex and comments imply that things are safe for concurrency and yet we don't use it all here. Imagine somebody calls `Job.Progress()` and `Job.Update()` concurrently. 

Either way, this should be in a different PR. I'll remove it. 
</blockquote></details>

Thanks, the reason I am asking is there's a lot of flakiness in the jobs/bulkio tests and I wonder if some of it was caused by this race. Some of the tests are disabled so it's hard to tell if they would improve. Furthermore some are flaky only on TC. Not related to this PR, but what's you advice on how to periodically retry the ones that are paused and maybe enable them?
___
*[pkg/jobs/registry.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-Ltvo0-K5B-D_lW54c1F:-Ltvo0-K5B-D_lW54c1G:b7wpnhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee70dcdda3b5fcb705ff656e8c3dc53fbd71b27e/pkg/jobs/registry.go#L220)):*
> ```Go
> 	}
> 
> 	if j.ID() == nil {
> ```

What are you thoughts on moving this block in CreateAndStartJob? Creating the ID in StartJob make cause some subtle bugs down the road, probably it's better to fail fast if the ID is nil here.


<!-- Sent from Reviewable.io -->

2019-11-18 00:04 UTC, spaskob reviewed
Thank you, this has been very useful! It looks good, I added one more comment that I don't feel strongly about.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-LtvofFz98586TVYiLRR:btmucm7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @spaskob)



<!-- Sent from Reviewable.io -->

2019-11-19 02:49 UTC, spaskob reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-Lu0Z9XZ64BZt2RPzcz3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @spaskob)



<!-- Sent from Reviewable.io -->

2019-11-19 03:05 UTC, ajwerner reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-:-Lu0bfgs0WfQKRYSHbKb:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt and @spaskob)

___
*[pkg/jobs/jobs.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LttA7n_B39B00vZ4XzX:-Lu0Z_AH5fBnXS40zIXv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L105)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

thanks, that's long name but precise
</blockquote></details>

Done.
___
*[pkg/jobs/jobs.go, line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmKsaf04c_kvgC2_xb:-Lu0ZaqCCDhMy8fVF1lp:bcpv5g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/jobs.go#L493)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Thanks, the reason I am asking is there's a lot of flakiness in the jobs/bulkio tests and I wonder if some of it was caused by this race. Some of the tests are disabled so it's hard to tell if they would improve. Furthermore some are flaky only on TC. Not related to this PR, but what's you advice on how to periodically retry the ones that are paused and maybe enable them?
</blockquote></details>

I don't think so. At least I don't know where `insert` would be called in parallel with anything else.
___
*[pkg/jobs/registry.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-LtmNHS6E79GCkHlQbcp:-Lu0_wpB7JmRJNkFikqy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/947d6aa804b34da8dab84308abe8a9a1a93ce138/pkg/jobs/registry.go#L223)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

true.
</blockquote></details>

Done.
___
*[pkg/jobs/registry.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-Ltvo0-K5B-D_lW54c1F:-Lu0Zn9E7YOEpKZ76xEB:b-mch2et) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee70dcdda3b5fcb705ff656e8c3dc53fbd71b27e/pkg/jobs/registry.go#L220)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

What are you thoughts on moving this block in CreateAndStartJob? Creating the ID in StartJob make cause some subtle bugs down the road, probably it's better to fail fast if the ID is nil here.
</blockquote></details>

Hmm yeah I could see doing that. I didn't want to write the job record until after I had verified that we could create the resumer. This way the semantics are that you could call `NewJob()` and then `StartJob()`. I really don't have strong feelings.

I moved it around to construct the resumer above common shared logic and it felt worse because then I needed to ensure that we did have an ID. 


<!-- Sent from Reviewable.io -->

2019-11-19 03:27 UTC, spaskob approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42521)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @spaskob)

___
*[pkg/jobs/registry.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42521#-Ltvo0-K5B-D_lW54c1F:-Lu0gmVk3aVbUkbrqPF4:b32w49) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee70dcdda3b5fcb705ff656e8c3dc53fbd71b27e/pkg/jobs/registry.go#L220)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Hmm yeah I could see doing that. I didn't want to write the job record until after I had verified that we could create the resumer. This way the semantics are that you could call `NewJob()` and then `StartJob()`. I really don't have strong feelings.

I moved it around to construct the resumer above common shared logic and it felt worse because then I needed to ensure that we did have an ID. 
</blockquote></details>

SG


<!-- Sent from Reviewable.io -->

2019-11-19 14:49 UTC, ajwerner commented
I'm pretty sure the build flakes are unrelated but I'd like it to build before I bors it.

2019-11-19 15:49 UTC, ajwerner commented
bors r=spaskob

I'm merging this for now. We can roll it back when we provide a better mechanism.

2019-11-19 16:32 UTC, merged