Temp tables session deletion
cockroachdb/cockroach pull request #42742
Opened 2019-11-25 18:27 UTC by arulajmani

Previously, temporary tables and the temporary schema created by a
session were not cleaned up when the session ended. As these objects
are session scoped, this needs to change.

This PR:

-  Addresses the cleanup of temporary objects when the session
exits gracefully.

- Adds a SchemaID field  to table descriptors. If this field is not
set, it is assumed to be 29, which is the schemaID of `public` schema.

Release note (sql change): When a session that has created temporary tables
exits gracefully, the tables and temporary schema are deleted
automatically.

2019-11-25 18:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42742)
<!-- Reviewable:end -->

2019-12-02 21:01 UTC, solongordon requested changes
Left some thoughts. The `conn_executor`-level stuff is fairly unfamiliar to me so we might want to pull someone else in to take a look at that.

> Reviewed 95 of 95 files at r1, 5 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-Lv7P9ft8Q2RFxZSjd2h:b-g91357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/jobs/jobspb/jobs.proto, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv6IUm5D6q7NgWF6w8o:-Lv6IUm6ANherQuDkOGP:b-hzx22m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/jobs/jobspb/jobs.proto#L307)):*
> ```protobuf
>   CREATE_STATS = 6 [(gogoproto.enumvalue_customname) = "TypeCreateStats"];
>   AUTO_CREATE_STATS = 7 [(gogoproto.enumvalue_customname) = "TypeAutoCreateStats"];
>   DELETE_TEMP_TABLES = 8 [(gogoproto.enumvalue_customname) = "TypeDeleteTempTables"];
> ```

Unrelated (as you already mentioned)
___
*[pkg/sql/conn_executor.go, line 747 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv719VpBFFyq_EQiM82:-Lv719VqEMVaQXZsGium:b-1as97d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/conn_executor.go#L747)):*
> ```Go
> 			return err
> 		}
> 		return nil
> ```

Nit: Just `return cleanupSessionTempObjects(ctx, &ex.planner, ex.sessionID)`
___
*[pkg/sql/conn_executor.go, line 1202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7HYV5Eapzw9M9W_FI:-Lv7HYV5Eapzw9M9W_FJ:bf55ja8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/conn_executor.go#L1202)):*
> ```Go
> 
> 	ex.sessionID = ex.generateID()
> 	sessionID := ex.sessionID
> ```

Why reassign this?
___
*[pkg/sql/temporary_schema.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7I49y-0U8zp9SK-hm:-Lv7I49y-0U8zp9SK-hn:bufucq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L50)):*
> ```Go
> }
> 
> func TemporarySchemaName(sessionID ClusterWideID) string {
> ```

Does this need to be exported?
___
*[pkg/sql/temporary_schema.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7JBrN7uVzePhjK1LN:-Lv7JBrN7uVzePhjK1LO:bd1xvrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L56)):*
> ```Go
> func cleanupSessionTempObjects(ctx context.Context, p *planner, sessionID ClusterWideID) error {
> 	tempSchemaName := TemporarySchemaName(sessionID)
> 	if p.sessionDataMutator != nil && p.sessionDataMutator.data.SearchPath.GetTemporarySchemaName() != tempSchemaName {
> ```

This is a roundabout way of checking if any temp schemas were created, right? Maybe nicer to make an explicit method on SearchPath for this.
___
*[pkg/sql/temporary_schema.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7M4D_4jAz_31ZMo2e:-Lv7M4D_4jAz_31ZMo2f:b7o99po) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L63)):*
> ```Go
> 		return err
> 	}
> 	for _, id := range dbIDs {
> ```

Did you take a look at the DROP DATABASE implementation to see if any code can be shared with that?
___
*[pkg/sql/temporary_schema.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7LrUF-ZhGUge5bSeC:-Lv7LrUF-ZhGUge5bSeD:b-tu8iln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L74)):*
> ```Go
> 				return err
> 			}
> 			_, err = p.dropTableImpl(ctx, tbDesc)
> ```

Does this also work for views and sequences?
___
*[pkg/sql/sqlbase/structured.proto, line 508 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MP00EwDy-9T26GiO:-Lv7MP00EwDy-9T26GiP:bt36u47) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L508)):*
> ```protobuf
>       (gogoproto.customname) = "ParentID", (gogoproto.casttype) = "ID"];
>   // ID of the parentSchema. Before this field being introduced goes hand in hand
>   // with CRDB supporting additional physical schemas (other than public). If
> ```

This sentence doesn't make sense to me.
___
*[pkg/sql/sqlbase/structured.proto, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MVVG3ulDxnbQwnS6:-Lv7MVVG3ulDxnbQwnS7:bco4sog) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L512)):*
> ```protobuf
>   // table was scoped under the public physical schema, so this field has the
>   // implied value of 29 (when unset).
>   optional uint32 parent__schema_id = 40 [(gogoproto.nullable) = false,
> ```

Extra underscore?
___
*[pkg/sql/sqlbase/structured.proto, line 692 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MwmP6ZKfkNQziOhg:-Lv7MwmP6ZKfkNQziOhh:bhxfzqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L692)):*
> ```protobuf
>       (gogoproto.customname) = "ParentID", (gogoproto.casttype) = "ID"];
>     // The schemaID of the schema the table belongs to before the rename/drop.
>     // Required to reclaim the old table name back.
> ```

Not clear to me what the last sentence means.


<!-- Sent from Reviewable.io -->

2019-12-03 12:07 UTC, knz commented
You may want to ask Andrei for the conn executor change.

Also let me know if you want me to give another look too.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

2019-12-03 17:56 UTC, arulajmani reviewed
TFTR. I talked to Andrei offline last week and discussed/showed him my approach around the `conn_executor` stuff. I'll add him as a reviewer here. 

@knz feel free to have a look over this stuff! :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LvBjymu9vJ9K-WL3YH-:b-zdh5oq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/jobs/jobspb/jobs.proto, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv6IUm5D6q7NgWF6w8o:-LvBXY2TAP8cFODYJLhU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/jobs/jobspb/jobs.proto#L307)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unrelated (as you already mentioned)
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 1202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7HYV5Eapzw9M9W_FI:-LvBXqwLDoc_Vg3A0AC9:bui2xh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/conn_executor.go#L1202)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why reassign this?
</blockquote></details>

Leftover from some debugging around this area. Removed. 
___
*[pkg/sql/temporary_schema.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7I49y-0U8zp9SK-hm:-LvBYRxp5EgpKa3OMDCe:b-t5w8h1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L50)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Does this need to be exported?
</blockquote></details>

Nup, leftover from a previous approach. 
___
*[pkg/sql/temporary_schema.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7JBrN7uVzePhjK1LN:-LvBZpme4it1Xuf8bNuI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L56)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This is a roundabout way of checking if any temp schemas were created, right? Maybe nicer to make an explicit method on SearchPath for this.
</blockquote></details>

Done.
___
*[pkg/sql/temporary_schema.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7M4D_4jAz_31ZMo2e:-LvBdfIJ8MNT6bh2SqER:b6tgdrl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L63)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Did you take a look at the DROP DATABASE implementation to see if any code can be shared with that?
</blockquote></details>

Refactored the actual dropping of the descriptor to reuse some code. 

Ideally, this code, and the database code, should go through a dropSchema/dropSchemaImpl pattern code path. I can work on that after Im done the schema cache stuff in a PR. I've left a TODO here. 

drop database is a bit trickier, because it happens in two steps. My first impression is that it will require implementing the bulk of `DROP SCHEMA`. 
___
*[pkg/sql/temporary_schema.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7LrUF-ZhGUge5bSeC:-LvBcjHF9N5LgoDh-K78:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/temporary_schema.go#L74)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Does this also work for views and sequences?
</blockquote></details>

Fixed. 
___
*[pkg/sql/sqlbase/structured.proto, line 508 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MP00EwDy-9T26GiO:-LvBbugW-p8jh4XzB52v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L508)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This sentence doesn't make sense to me.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MVVG3ulDxnbQwnS6:-LvBbuQm8MqiXyBigeUK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L512)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Extra underscore?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 692 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lv7MwmP6ZKfkNQziOhg:-LvBcRpD50wNZjjY2lp0:b-v6qq34) ([raw file](https://github.com/cockroachdb/cockroach/blob/f676fc10bd0835c812f0dd38694b63d849129f94/pkg/sql/sqlbase/structured.proto#L692)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Not clear to me what the last sentence means.
</blockquote></details>

Changed to be more explicit. Basically, drops/renames involve reclaiming names in the drain name process. To identify which name to reclaim, we need the parentSchemaID. 


<!-- Sent from Reviewable.io -->

2019-12-03 18:17 UTC, arulajmani commented
@andreimatei I got to all the changes you suggested in the `conn_executor` part of this PR based on our discussion last week. Could you have another look?

2019-12-03 19:22 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4kLUD-z9oJR-OSq8:-LvC4kLUD-z9oJR-OSq9:b-jhb6xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
> ```Go
> }
> 
> func (ex *connExecutor) maybeCleanupTempObjects() {
> ```

this method deserves a comment
___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4md61QzZcoTWHyYQ:-LvC4md61QzZcoTWHyYR:b4tjg3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
> ```Go
> }
> 
> func (ex *connExecutor) maybeCleanupTempObjects() {
> ```

nit: I don't like the `maybe` prefix (but I also don't really know what this function does). Is the maybe referring to the possibility of there being no temp objects? If so, I'd drop it. If it's referring to something else, spell it out in the name.
___
*[pkg/sql/conn_executor.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC-x32ASNlenp_qwAd:-LvC-x32ASNlenp_qwAe:bm0wn7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L744)):*
> ```Go
> 
> func (ex *connExecutor) maybeCleanupTempObjects() {
> 	// Has to happen in a new context, because the context associated with  the
> ```

double space
___
*[pkg/sql/conn_executor.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC2wSQ-GcpM1qmS8n7:-LvC2wSQ-GcpM1qmS8n8:b3f0k6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L744)):*
> ```Go
> 
> func (ex *connExecutor) maybeCleanupTempObjects() {
> 	// Has to happen in a new context, because the context associated with  the
> ```

This sentence is missing a subject and also it's unclear. What does connection closing have to do with this? 
Simply say "Don't inherit context cancelation. This cleanup happens after the connection is closed.". And see below.
___
*[pkg/sql/conn_executor.go, line 746 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC29Wg4U5FNx2ogKcf:-LvC29WhCF21U4hQ8Euf:bd2elc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L746)):*
> ```Go
> 	// Has to happen in a new context, because the context associated with  the
> 	// session is cancelled when the connection is closed.
> 	ctx := context.Background()
> ```

take in a context and do `logtags.WithTags(context.Background(), logtags.FromContext(ctx)`to get the log tags (`[n1,...]`)
And do all this in the caller and pass in the proper context. The comments about connection closing will actually make sense.
___
*[pkg/sql/conn_executor.go, line 748 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0X4k4y5fz1gI8Yxh:-LvC0X4k4y5fz1gI8Yxi:b-94e8ob) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L748)):*
> ```Go
> 	ctx := context.Background()
> 	err := ex.planner.ExtendedEvalContext().DB.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 		ex.resetPlanner(ctx, &ex.planner, txn, ex.server.cfg.Clock.PhysicalTime() /* stmtTS */, 0)
> ```

pls comment inline on the 0 constant as per the style guide (' /* numAnnotations */').
Same below.
___
*[pkg/sql/conn_executor.go, line 749 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvCCQAa60Vvw5aeTTrW:-LvCCQAa60Vvw5aeTTrX:b-ui4a42) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L749)):*
> ```Go
> 	err := ex.planner.ExtendedEvalContext().DB.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 		ex.resetPlanner(ctx, &ex.planner, txn, ex.server.cfg.Clock.PhysicalTime() /* stmtTS */, 0)
> 		return cleanupSessionTempObjects(ctx, &ex.planner, ex.sessionID)
> ```

how about having this guy return `ex.planner.extendedEvalCtx.SchemaChangers` ?
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC47BiAeh9bfxzLBi0:-LvC47BiAeh9bfxzLBi1:b-ao9hcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Error(ctx, err)
> ```

`cleanupSessionTempObjects()` doesn't seem to do much error wrapping. Make sure there's a good error message that talks about dropping temp tables, one way or another.
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC5ywo3N8HfwzJkUyl:-LvC5ywo3N8HfwzJkUym:b8uj04d) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Error(ctx, err)
> ```

remember the error, return it later, and swallow it in the caller. (There's doesn't appear to be a reason why this method can't return an error, and if it can, it should.)
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC7nxUCVd9Ly8qGQ9f:-LvC7nxUCVd9Ly8qGQ9g:b-hx0p2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Error(ctx, err)
> ```

is there a point in continuing after an error? If so, please put some comments to this effect for the return values of `cleanupSessionTempObjects()` - and hint that schema changes are queued up.
___
*[pkg/sql/conn_executor.go, line 754 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvCCZYLEimAvB7rH1rG:-LvCCZYLEimAvB7rH1rH:bgqkizb) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L754)):*
> ```Go
> 		log.Error(ctx, err)
> 	}
> 	err = ex.planner.ExtendedEvalContext().DB.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> ```

can you give a nod about why this needs to be a different txn than the above?
___
*[pkg/sql/conn_executor.go, line 756 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC9ndM8FRoRkveM59l:-LvC9ndM8FRoRkveM59m:bf7g5ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L756)):*
> ```Go
> 	err = ex.planner.ExtendedEvalContext().DB.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 		ieFactory := func(ctx context.Context, sd *sessiondata.SessionData) sqlutil.InternalExecutor {
> 			ex.resetPlanner(ctx, &ex.planner, txn, ex.server.cfg.Clock.PhysicalTime() /* stmtTS */, 0)
> ```

Is this `resetPlanner` call necessary? It scares me because it suggests that the `sbie` below uses `ex.planner`, but that kind of sharing seems against the spirit of passing a factory to `execSchemaChanges()` - which might use the factory multiple times, concurrently?
___
*[pkg/sql/conn_executor.go, line 766 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0q2H-XW3ZdwS94t0:-LvC0q2H-XW3ZdwS94t1:b-bp8def) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L766)):*
> ```Go
> 			return ie
> 		}
> 		err = ex.planner.extendedEvalCtx.SchemaChangers.execSchemaChanges(ctx, ex.server.cfg, &ex.sessionTracing, ieFactory)
> ```

line over 100 chars
___
*[pkg/sql/conn_executor.go, line 767 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0to3D6VuJ_pqnmFA:-LvC0to3D6VuJ_pqnmFB:bdcwrmi) ([raw file](https://github.com/cockroachdb/cockroach [...]

2019-12-04 22:43 UTC, knz reviewed
I'm replying to the question addressed to me below.
I'm willing to also review the PR but not before the other one is merged and this one rebased on top. It's a bit too unwieldy to review otherwise.

> Reviewed 1 of 95 files at r1, 1 of 34 files at r3, 22 of 23 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LvI48JL5CSL9uaJRooo:b-4h77oj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @solongordon)

___
*[pkg/sql/drop_table.go, line 609 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6yrcDpUGhEKsfOd8:-LvI3Iy73JA3O2h3dWNb:b-j2xr3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/drop_table.go#L609)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you put more words in this TODO? (or ask Rafa). I don't know what this is telling me, and I can't judge if it's appropriate in the new location. Perhaps take the opportunity to do whatever this wants.
</blockquote></details>

Have you copy-copied this comment from `drop_database.go`? The comment pertains to the object names accumulated in the `tbNameStrings` slice. I don't see you using `tbNameStrings` here so I don't think the comment is relevant/warranted.


<!-- Sent from Reviewable.io -->

2019-12-04 23:20 UTC, arulajmani reviewed
@knz that should be merged soon, will comment here when this branch is rebased and more "review friendly" 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LvICES8-0xtMVxjuGMt:b-7gj6oy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4kLUD-z9oJR-OSq8:-LvHwoS9-hE061ot_JPJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this method deserves a comment
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4md61QzZcoTWHyYQ:-LvHJcQo0REXKYVT4aep:b-skkm7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I don't like the `maybe` prefix (but I also don't really know what this function does). Is the maybe referring to the possibility of there being no temp objects? If so, I'd drop it. If it's referring to something else, spell it out in the name.
</blockquote></details>

Yup, it refers to the possibility of there being no temp objects. Dropping the `maybe`.
___
*[pkg/sql/conn_executor.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC-x32ASNlenp_qwAd:-LvHNZHKE-kkYIAmBRau:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L744)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 744 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC2wSQ-GcpM1qmS8n7:-LvHNZbc7bva7wAOqmCU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L744)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This sentence is missing a subject and also it's unclear. What does connection closing have to do with this? 
Simply say "Don't inherit context cancelation. This cleanup happens after the connection is closed.". And see below.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 746 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC29Wg4U5FNx2ogKcf:-LvHYViS4nJOqvah8raS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L746)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

take in a context and do `logtags.WithTags(context.Background(), logtags.FromContext(ctx)`to get the log tags (`[n1,...]`)
And do all this in the caller and pass in the proper context. The comments about connection closing will actually make sense.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 748 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0X4k4y5fz1gI8Yxh:-LvHYjfH2VmzMZKKwwM3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L748)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment inline on the 0 constant as per the style guide (' /* numAnnotations */').
Same below.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 749 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvCCQAa60Vvw5aeTTrW:-LvHq94Z7fEP0HKPJydR:b-2itqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L749)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about having this guy return `ex.planner.extendedEvalCtx.SchemaChangers` ?
</blockquote></details>

Makes sense, done. 
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC47BiAeh9bfxzLBi0:-LvHrFcB6beS1UeKKh45:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`cleanupSessionTempObjects()` doesn't seem to do much error wrapping. Make sure there's a good error message that talks about dropping temp tables, one way or another.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC5ywo3N8HfwzJkUyl:-LvHrEuC-4VLF1lW6xY-:b-4uvt36) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

remember the error, return it later, and swallow it in the caller. (There's doesn't appear to be a reason why this method can't return an error, and if it can, it should.)
</blockquote></details>

I've implemented this for now, but I'm finding this remembering error and swallowing in the caller sort of ugly.

What if there is an error in both `cleanupSessionTempObjects` and the partial schema changes that have been queued up? Currently, I'm sticking with logging the second error and returning the first. Not sure thats the best option here. 
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC7nxUCVd9Ly8qGQ9f:-LvI4hAj5yyC5WM1dOvf:b-mlh480) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is there a point in continuing after an error? If so, please put some comments to this effect for the return values of `cleanupSessionTempObjects()` - and hint that schema changes are queued up.
</blockquote></details>

Yup, there could be schema changes for some tables queued up. Added a comment in `cleanupSessionTempObjects`. 
___
*[pkg/sql/conn_executor.go, line 754 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvCCZYLEimAvB7rH1rG:-LvHry8sAK-_RXFU7cdL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L754)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you give a nod about why this needs to be a different txn than the above?
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 756 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC9ndM8FRoRkveM59l:-LvHrotkEJzokNPvrF7E:bhaxde2) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L756)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is this `resetPlanner` call necessary? It scares me because it suggests that the `sbie` below uses `ex.planner`, but that kind of sharing seems against the spirit of passing a factory to `execSchemaChanges()` - which might use the factory multiple times, concurrently?
</blockquote></details>

No it isn't. Removed. 
___
*[pkg/sql/conn_executor.go, line 766 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0q2H-XW3ZdwS94t0:-LvHroeg9CQ5Y-hThd9b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L766)):*
<details><s [...]

2019-12-05 17:09 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4kLUD-z9oJR-OSq8:-LvLs6whC0RpLl4FMU65:b-cgtknz) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

can you qualify "objects" a bit pls? Tables and what else?
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC5ywo3N8HfwzJkUyl:-LvLsTdiD6okQ8TIPfBV:b3wuydy) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I've implemented this for now, but I'm finding this remembering error and swallowing in the caller sort of ugly.

What if there is an error in both `cleanupSessionTempObjects` and the partial schema changes that have been queued up? Currently, I'm sticking with logging the second error and returning the first. Not sure thats the best option here. 
</blockquote></details>

use `errors.CombineErrors()`
___
*[pkg/sql/conn_executor.go, line 767 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0to3D6VuJ_pqnmFA:-LvLte4y5p282poWaPGA:bbyp0y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L767)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look done :)
___
*[pkg/sql/conn_executor.go, line 773 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6AP-DZYYdzd5saHp:-LvLtipW-2wqhOloWcx9:b-cebaig) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L773)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you almost never want to both log an error and return it. Just return it.
___
*[pkg/sql/conn_executor.go, line 755 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLuTLA0usV0OIDRNht:-LvLuTLA0usV0OIDRNhu:b-d0hhjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/conn_executor.go#L755)):*
> ```Go
> 		return err
> 	})
> 	// schema changes run after the transaction that queued them has committed, so
> ```

nit: s/schema/Schema
___
*[pkg/sql/conn_executor.go, line 757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLwDy58phUDcTbP37i:-LvLwDy58phUDcTbP37j:b-vfnfam) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/conn_executor.go#L757)):*
> ```Go
> 	// schema changes run after the transaction that queued them has committed, so
> 	// they must be run in a new transaction.
> 	err := ex.planner.ExtendedEvalContext().DB.Txn(ctx,
> ```

`return errors.CombineErrors(cleanupError, ex.planner....)`
___
*[pkg/sql/conn_executor.go, line 794 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLtvgx8g3jLsomoLoO:-LvLtvgx8g3jLsomoLoP:b-amzpq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/conn_executor.go#L794)):*
> ```Go
> 	err := ex.cleanupTempObjects(cleanupCtx)
> 	if err != nil {
> 		log.Errorf(ctx, "error deleting temporary objects %v", err)
> ```

s/%v/%s (because you know that err is not nil)
And put a colon after "objects" pls.
___
*[pkg/sql/temporary_schema.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC7LBD53uG3NCtnR1i:-LvLxq9K18cxHQrL5Nvl:bn6bgcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/temporary_schema.go#L77)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

For now, but not when support for temporary views is turned on. 
</blockquote></details>

Well, at that point, the assertion will fail. The assertion serves as insurance that we won't forget to change this.
Also, it will serve as clarifying what the return value of of `dropDesc` is, and as a implicit comment about why we're ignoring it.
___
*[pkg/sql/temporary_schema.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC7VscAGFvMQr224L-:-LvLyB_B20CQg0Mz0rV-:brkh30l) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/temporary_schema.go#L81)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should be done before I leave. 
</blockquote></details>

It's not very clear to me from this comment what "this" and "there" mean. Please improve it or... just remove it :).
If you intend to do it, then the TODO is not necessary. If you don't do it, then your name on it is wrong (ticking clock and all).
___
*[pkg/sql/temporary_schema.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLycfL9dkxTm-0Ch7F:-LvLycfL9dkxTm-0Ch7G:b-23grh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/temporary_schema.go#L88)):*
> ```Go
> 		// there, so that the cache entry is removed as well.
> 		//
> 		// Finally, also remove the temporary schema from the namespace table
> ```

 nit: period at the end of the sentence pls


<!-- Sent from Reviewable.io -->

2019-12-08 21:47 UTC, arulajmani reviewed
Switched to a new approach to use an internal planner, instead of the session planner, as discussed with @andreimatei offline. I also rebased off master after the namespace PR landed, so this should be easier to review now :) 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LvbSPrxB6OYTXX5sQJ7:b-4659ld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 743 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC4kLUD-z9oJR-OSq8:-LvSLtlG7_cG6FNn8929:b-7zfnvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L743)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you qualify "objects" a bit pls? Tables and what else?
</blockquote></details>

I don't need this function anymore, but objects was referring to tables, views, and sequences here. Added a nod to this in `temporary_schema.go`.
___
*[pkg/sql/conn_executor.go, line 752 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC5ywo3N8HfwzJkUyl:-LvSL2KLC8oTAMRTZTqU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

use `errors.CombineErrors()`
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 767 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC0to3D6VuJ_pqnmFA:-LvSL5tz45Nwhc6pJ4ne:b-aslgwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L767)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Doesn't look done :)
</blockquote></details>

I don't think it applied without `errors.CombineErrors`. Should be good now though :) 
___
*[pkg/sql/conn_executor.go, line 773 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6AP-DZYYdzd5saHp:-LvM8MAd-lf6-0rm8Gho:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/conn_executor.go#L773)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you almost never want to both log an error and return it. Just return it.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 757 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLwDy58phUDcTbP37i:-LvSL0EOALPcl8Iv5qIy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/conn_executor.go#L757)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`return errors.CombineErrors(cleanupError, ex.planner....)`
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 794 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLtvgx8g3jLsomoLoO:-LvSLeIxENZ0vvv9Do_d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/conn_executor.go#L794)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/%v/%s (because you know that err is not nil)
And put a colon after "objects" pls.
</blockquote></details>

Done.
___
*[pkg/sql/temporary_schema.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC7VscAGFvMQr224L-:-LvSI5VnEkI_rH84VCsD:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/temporary_schema.go#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

It's not very clear to me from this comment what "this" and "there" mean. Please improve it or... just remove it :).
If you intend to do it, then the TODO is not necessary. If you don't do it, then your name on it is wrong (ticking clock and all).
</blockquote></details>

Removed.
___
*[pkg/sql/temporary_schema.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvLycfL9dkxTm-0Ch7F:-LvSITaY-044arj9_2xO:b-a8uaa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/82d349bca42a9b2a14ff688c8c70ebcd07ed9de0/pkg/sql/temporary_schema.go#L88)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

 nit: period at the end of the sentence pls
</blockquote></details>

Removed the comment completely.


<!-- Sent from Reviewable.io -->

2019-12-09 17:00 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 748 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfaIWU27qv2B8PlgW2:-LvfaIWVBw3Yx-m5_X55:bbn21qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/conn_executor.go#L748)):*
> ```Go
> 
> 	if ex.planner.HasCreatedTemporarySchema(ex.sessionID) {
> 		// Don't inherit context cancellation. This cleanup happens after the
> ```

the part about happening after something is closed doesn't make sense any more now that you're in `close()`. Also removing the cancelation seems good for the contexts passed to all callees in this method. Let's take the opportunity to move it to `closeWrapper()` and just say "// Closing is not cancelable."


<!-- Sent from Reviewable.io -->

2019-12-09 20:53 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/drop_table.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6VSSE4sg5smy5Urh:-LvgPXmQ3JjUuHe2GHX9:b-qo0zav) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/drop_table.go#L605)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually let's name it `dropObject`. Putting `desc` in the name makes it sound like it's a low level function that just deletes a descriptor, whereas this is anything but.
___
*[pkg/sql/drop_table.go, line 615 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfxsRn4OlVJVz4Uy-C:-LvfxsRn4OlVJVz4Uy-D:b-j43qtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/drop_table.go#L615)):*
> ```Go
> }
> 
> // Drops a descriptor based its type. Returns the names of any additional views
> ```

"dropDesc drops". Even though the linter does enforce this for non-exported methods, we keep the convention.
___
*[pkg/sql/planner.go, line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg1aip9kiPQLr3I3ka:-Lvg1aip9kiPQLr3I3kb:bbbt3d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L354)):*
> ```Go
> }
> 
> func (p *planner) HasCreatedTemporarySchema(sessionID ClusterWideID) bool {
> ```

Get rid of this method. The caller has access to the session data. It doesn't need to go through the planner.
___
*[pkg/sql/planner.go, line 360 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg0NZn2EJfYe1bigBw:-Lvg0NZn2EJfYe1bigBx:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L360)):*
> ```Go
> 	// can be called by session bound internal executors, this nil check is
> 	// required.
> 	return p.sessionDataMutator != nil && p.sessionDataMutator.data.SearchPath.HasCreatedTemporarySchema(tempSchemaName)
> ```

long line
___
*[pkg/sql/sequence.go, line 462 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg-lOs5rQimARrhWf4:-Lvg-lOs5rQimARrhWf5:b-o6n98e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/sequence.go#L462)):*
> ```Go
> // When a table/column is dropped that owns sequences, the sequences must be dropped
> // as well.
> func dropSequencesOwnedByCol(ctx context.Context, col *sqlbase.ColumnDescriptor, p *planner) error {
> ```

this seems to not need a planner, just a txn
___
*[pkg/sql/sequence.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg-MVFEtHtuRVXdQzK:-Lvg-MVGEJiDH4DDTN8a:b-5eerrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/sequence.go#L482)):*
> ```Go
> func removeSequenceDependencies(
> 	ctx context.Context,
> 	p *planner,
> ```

nit: put the planner last. The other args are more interesting.
And in fact it looks like just the txn is needed, not a planner.
___
*[pkg/sql/temporary_schema.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfyiR42Ns5R_TdLtuE:-LvfyiR42Ns5R_TdLtuF:b-709ulo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L59)):*
> ```Go
> }
> 
> // Removes all temporary objects (tables, sequences, views) created by the
> ```

"cleanupSession... removes"
___
*[pkg/sql/temporary_schema.go, line 71 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgNr4eAA86axgmQVSD:-LvgNr4eAA86axgmQVSE:byrl5p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L71)):*
> ```Go
> 		)
> 		defer cleanup()
> 		// The temporary schema needs to be set on the new internal planner, as
> ```

nit:s/new internal planner/planner
___
*[pkg/sql/temporary_schema.go, line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgNzDRDtdDpZtpS6VI:-LvgNzDRDtdDpZtpS6VJ:b-g36fy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L75)):*
> ```Go
> 		// only be accessed by the session that created them.
> 		p.SetTemporarySchemaName(tempSchemaName)
> 		dbIDs, err := GetAllDatabaseDescriptorIDs(ctx, p.txn)
> ```

please describe around how we're gonna do everything, since it's not obvious.
```
We're going to read all the database descriptor ids, then for each database we're going
to list the tables in the temporary schema. We're going to then drop the one by one, and then run the schema changes produced by the dropping.
```
___
*[pkg/sql/temporary_schema.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgN4Hz1IeD_AR-DxWi:-LvgN4Hz1IeD_AR-DxWj:b-4qs3gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L81)):*
> ```Go
> 		for _, id := range dbIDs {
> 			dbDesc, err := MustGetDatabaseDescByID(ctx, p.txn, id)
> 			if err != nil {
> ```

Since we're making such a big deal about continuing after errors below, why don't we continue accumulating temp tables after errors here or when we handle one table at a time below? We should continue the other databases / tables, shouldn't we?
Or alternatively don't run the schema changes after errors at all. As it stands, we do it half way if I read correctly.

If you do want to tolerate errors as much as possible, consider making another function that returns ids of temp tables, and also an error if the collection might be incomplete.
___
*[pkg/sql/temporary_schema.go, line 84 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvfz2czAK7fQdCJlGhq:-Lvfz2czAK7fQdCJlGhr:b-68erpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L84)):*
> ```Go
> 				return err
> 			}
> 			tbNames, err := GetObjectNames(ctx, p.txn, p, dbDesc, tempSchemaName, true /* explicitPrefix*/)
> ```

over 100 chars?
___
*[pkg/sql/temporary_schema.go, line 84 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgQLM_5iuKfEqE0jPP:-LvgQLM_5iuKfEqE0jPQ:b-u6l83i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L84)):*
> ```Go
> 				return err
> 			}
> 			tbNames, err := GetObjectNames(ctx, p.txn, p, dbDesc, tempSchemaName, true /* explicitPrefix*/)
> ```

Isn't there a way to get ids instead of names?
Alternatively, since it seems that we're doing a bunch of work to get what we want anyway, can't we simply run `DROP TABLE` statements and not any custom code?
___
*[pkg/sql/temporary_schema.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgObsd-35JVlIBRlex:-LvgObsd-35JVlIBRley:b71xxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L87)):*
> ```Go
> 			for i := range tbNames {
> 				tbDesc, err := p.ResolveMutableTableDescriptor(
> 					ctx, &tbNames[i], true /* required */, ResolveAnyDescType,
> ```

Don't we want `ResolveRequireTableDesc` here? If we're expecting all of these to be tables, my vote is to be strict about it, not tolerant. If nothing else, for documentation purposes.
___
*[pkg/sql/temporary_schema.go, line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgM0vKC3UO0-IrRhPO:-LvgM0vKC3UO0-IrRhPP:b-w7b68j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L90)):*
> ```Go
> 				)
> 				if err != n [...]

2019-12-11 04:16 UTC, arulajmani reviewed
Switched to executing a `DROP TABLE` statement instead of running custom code to drop descriptors and then run schema changes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-Lvn8lY31EIAnGwxNusu:b4ufltd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 748 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfaIWU27qv2B8PlgW2:-Lvk_M8J-wvpAfua1pOu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/conn_executor.go#L748)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the part about happening after something is closed doesn't make sense any more now that you're in `close()`. Also removing the cancelation seems good for the contexts passed to all callees in this method. Let's take the opportunity to move it to `closeWrapper()` and just say "// Closing is not cancelable."
</blockquote></details>

Done.
___
*[pkg/sql/drop_table.go, line 615 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfxsRn4OlVJVz4Uy-C:-Lvk__R29G-MbQYP9tiZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/drop_table.go#L615)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"dropDesc drops". Even though the linter does enforce this for non-exported methods, we keep the convention.
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg1aip9kiPQLr3I3ka:-Lvn2kfGCw-eTLD8hAqI:b3vg8jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L354)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Get rid of this method. The caller has access to the session data. It doesn't need to go through the planner.
</blockquote></details>

I've changed the method (and the name) slightly, but I think this should be a method call instead of constructing the temp schema name and comparing against the temp schema set on the SearchPath (in the conn_executor). 

I thought of putting this method on SessionData, instead of the planner,  but that doesn't work because sessionID is in the sql package and that causes a dependency cycle when included in the sessiondata package. The next best alternative imo is to have this method on the planner instead. 
___
*[pkg/sql/planner.go, line 360 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg0NZn2EJfYe1bigBw:-LvkcMdY9sL4cfiCYBdp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L360)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/sequence.go, line 462 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg-lOs5rQimARrhWf4:-LvkeNkH1NGUb_TLcj2P:b-pqlwwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this seems to not need a planner, just a txn
</blockquote></details>

It accesses the table collection/calls `dropSequenceImpl` which is a method on the planner. 
___
*[pkg/sql/sequence.go, line 482 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg-MVFEtHtuRVXdQzK:-LvkfQUW0GHcLy7y1VQ_:b-46dlv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/sequence.go#L482)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: put the planner last. The other args are more interesting.
And in fact it looks like just the txn is needed, not a planner.
</blockquote></details>

Put the planner last. 
This accesses some methods on the planner as well (`WriteSchemaChange`, `Table()` etc.). 
___
*[pkg/sql/temporary_schema.go, line 59 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvfyiR42Ns5R_TdLtuE:-Lvkfs3TB_oGRVmqFm-d:b30xsd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L59)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"cleanupSession... removes"
</blockquote></details>

Comment was outdated. Fixed that. 
___
*[pkg/sql/temporary_schema.go, line 75 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgNzDRDtdDpZtpS6VI:-LvlxXuxD4VFbVS_jksT:bi1cucw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please describe around how we're gonna do everything, since it's not obvious.
```
We're going to read all the database descriptor ids, then for each database we're going
to list the tables in the temporary schema. We're going to then drop the one by one, and then run the schema changes produced by the dropping.
```
</blockquote></details>

Added a comment, though the new approach is slightly easier to understand than what was there before. Let me know if the comment isn't required anymore.
___
*[pkg/sql/temporary_schema.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgN4Hz1IeD_AR-DxWi:-LvmxpgP2q8kyKVb_nm6:byrxam0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Since we're making such a big deal about continuing after errors below, why don't we continue accumulating temp tables after errors here or when we handle one table at a time below? We should continue the other databases / tables, shouldn't we?
Or alternatively don't run the schema changes after errors at all. As it stands, we do it half way if I read correctly.

If you do want to tolerate errors as much as possible, consider making another function that returns ids of temp tables, and also an error if the collection might be incomplete.

</blockquote></details>

comment no longer applicable as we don't queue/run schema changes manually anymore. 
___
*[pkg/sql/temporary_schema.go, line 84 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvfz2czAK7fQdCJlGhq:-LvkY3Ma9E6Vcxkkl37J:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L84)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

over 100 chars?
</blockquote></details>

Fixed. 
___
*[pkg/sql/temporary_schema.go, line 84 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgQLM_5iuKfEqE0jPP:-Lvn64Ua59LsYpXFnbWx:b7ovpv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L84)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Isn't there a way to get ids instead of names?
Alternatively, since it seems that we're doing a bunch of work to get what we want anyway, can't we simply run `DROP TABLE` statements and not any custom code?
</blockquote></details>

Currently there isn't a way to get all table descriptor IDs under a particular (database, schema). We have functions to get all database IDs, or the ID given a single table name.  

Switched the approach to use a `DROP TABLE` statement, as we discussed offline. 
___
*[pkg/sql/temporary_schema.go, line 87 at r6](https://reviewable.io/reviews/cockr [...]

2019-12-13 17:37 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 752 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-6wEy8280Hnmisb9e:-Lw-6wEy8280Hnmisb9f:b-6w8485) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/conn_executor.go#L752)):*
> ```Go
> 		err := cleanupSessionTempObjects(ctx, ex.server, ex.sessionID)
> 		if err != nil {
> 			log.Errorf(ctx, "error deleting temporary objects: %s", err)
> ```

please leave a comment here with a hint about the async retry process
___
*[pkg/sql/planner.go, line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg1aip9kiPQLr3I3ka:-Lw-7qv02xrZgSAqtN1L:b9dqfuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L354)):*
>  but I think this should be a method call instead of constructing the temp schema name and comparing against the temp schema set on the SearchPath (in the conn_executor).

Why? Make it a method on the `connExecutor` if you insist. The planner doesn't have much to do with a session.

> I thought of putting ...

Move `ClusterWideID`, or whatever type you need, to `sqlbase` if it helps you
___
*[pkg/sql/planner.go, line 358 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-BioZ3TEIY1c6y2bZ:-Lw-BioZ3TEIY1c6y2b_:ba8rp98) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/planner.go#L358)):*
> ```Go
> func (p *planner) HasSessionCreatedTemporarySchema(sessionID ClusterWideID) bool {
> 	tempSchemaName := temporarySchemaName(sessionID)
> 	return p.SessionData().SearchPath.GetTemporarySchemaName() == tempSchemaName
> ```

Can you find a good place to explain what's going on here? Why is the temporary schema name not a constant? Why is there a function called `temporarySchemaName` that returns something that's not the same as `GetTemporarySchemaName()`?
I don't know what I'm talking about, but it seems to me that this name should just be a well known constant.
___
*[pkg/sql/planner.go, line 399 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-9i4X5FJ3rqDemkbW:-Lw-9i4X5FJ3rqDemkbX:b-tstj07) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/planner.go#L399)):*
> ```Go
> }
> 
> func (p *planner) SetTemporarySchemaName(scName string) {
> ```

Does this method need to be on the planner/exist? I think all callers have access to the `sessionDataMutator`. If it doesn't need to exist, I'd rather untangle the planner from performing mutations to the session state as much as possible.
___
*[pkg/sql/sequence.go, line 462 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg-lOs5rQimARrhWf4:-Lw-CqusBCXgVN9MMhTL:b32wtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It accesses the table collection/calls `dropSequenceImpl` which is a method on the planner. 
</blockquote></details>

ok
___
*[pkg/sql/sequence.go, line 460 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-Cj9pCqPisVpKTkzs:-Lw-Cj9pCqPisVpKTkzt:b-dhm6xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L460)):*
> ```Go
> }
> 
> // When a table/column is dropped that owns sequences, the sequences must be dropped
> ```

this comment should start with the function name and say what the function does, not abstractly what must happen. After explaining what it does, you can give a hint about when it's called, or even when it must be called.

```
dropSequencesOwnedByCol drops all the sequences from col.OwnsSequenceIDs. Called when the respective column (or the whole table) is being dropped.
```
___
*[pkg/sql/sequence.go, line 462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-D_sB6wIF9ybBo_K_:-Lw-D_sB6wIF9ybBo_Ka:b-nshwsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L462)):*
> ```Go
> // When a table/column is dropped that owns sequences, the sequences must be dropped
> // as well.
> func dropSequencesOwnedByCol(ctx context.Context, col *sqlbase.ColumnDescriptor, p *planner) error {
> ```

One of the callers of this unnecessarily gates the call on `if len(col.OwnsSequenceIds) > 0`. The other caller doesn't. Get rid of the gating.
___
*[pkg/sql/sequence.go, line 462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-Ed3w9JDj4Bg-85Ox:-Lw-Ed3w9JDj4Bg-85Oy:b4gda72) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L462)):*
> ```Go
> // When a table/column is dropped that owns sequences, the sequences must be dropped
> // as well.
> func dropSequencesOwnedByCol(ctx context.Context, col *sqlbase.ColumnDescriptor, p *planner) error {
> ```

This function doesn't really need to take a `col`, just a list of sequence ids -> `dropSequences()`. Being in `sequence.go`, tying it to column is not great. If you move it to another place that has to do with columns more, the objection might go away.
___
*[pkg/sql/temporary_schema.go, line 93 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvgPxtS9UtBWB6W9MnE:-Lw-KMvVAs4B9-MrbIOV:be899e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/temporary_schema.go#L93)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

As we discussed offline, truncate doesn't actually do the deletion. It simply drops the old table (without draining the names), and creates a new table descriptor and updates the namespace table with the new ID. 
</blockquote></details>

mind leaving a TODO(andrei) or a NOTE saying that we might want to accelerate the deletion of this data
___
*[pkg/sql/temporary_schema.go, line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-FSV6CE5XPDkG3ofD:-Lw-FSV6CE5XPDkG3ofE:bot8ft2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L52)):*
> ```Go
> 
> func temporarySchemaName(sessionID ClusterWideID) string {
> 	return fmt.Sprintf("pg_temp_%v%v", sessionID.Hi, sessionID.Lo)
> ```

s/%v/%d/g

And please explain what this is and how it relates to the other `GetTemporarySchemaName()`.
___
*[pkg/sql/temporary_schema.go, line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-GWxz0wGeEmHsYkNf:-Lw-GWxz0wGeEmHsYkNg:b-d9wnj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L65)):*
> ```Go
> 		)
> 		defer cleanup()
> 		// The temporary schema needs to be set on the planner, as the planner is
> ```

I don't understand what this comment is telling me. If you explain it more to me, perhaps I'll be able to suggest a better one.
___
*[pkg/sql/temporary_schema.go, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-FqGi2LuVPOxCNhX_:-Lw-FqGi2LuVPOxCNhXa:b-2lb81g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L66)):*
> ```Go
> 		defer cleanup()
> 		// The temporary schema needs to be set on the planner, as the planner is
> 		// responsible for ensuring temporary table descriptors can  only be
> ```

double space after "can"
___
*[pkg/sql/temporary_schema.go, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-FvLvAusTH2x-vvxK:-Lw-FvLvAusTH2x-vvxL:b-8qj9le) ([raw file](https://githu [...]

2019-12-13 23:40 UTC, arulajmani reviewed
Switched to not using an `internalPlanner` and added a session variable `HasCreatedTempTable`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-Lw0cRey7QkKPJO6YHdV:b65p3cm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 752 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-6wEy8280Hnmisb9e:-Lw0W8m64UR49RLqNWIO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please leave a comment here with a hint about the async retry process
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 354 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lvg1aip9kiPQLr3I3ka:-Lw-i3hk3Dd4w4A9tZRy:bwewwun) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dcfdb7552a754b4c79be3bdd638f9ea5805e155/pkg/sql/planner.go#L354)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

>  but I think this should be a method call instead of constructing the temp schema name and comparing against the temp schema set on the SearchPath (in the conn_executor).

Why? Make it a method on the `connExecutor` if you insist. The planner doesn't have much to do with a session.

> I thought of putting ...

Move `ClusterWideID`, or whatever type you need, to `sqlbase` if it helps you
</blockquote></details>

As discussed offline, I added a new session variable `HasCreatedTemporarySchema`, and I perform that check here now.
___
*[pkg/sql/planner.go, line 358 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-BioZ3TEIY1c6y2bZ:-Lw0WBWi9Z8iGOxL0Zgz:b-ugil9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/planner.go#L358)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Can you find a good place to explain what's going on here? Why is the temporary schema name not a constant? Why is there a function called `temporarySchemaName` that returns something that's not the same as `GetTemporarySchemaName()`?
I don't know what I'm talking about, but it seems to me that this name should just be a well known constant.
</blockquote></details>

As discussed offline, I've added a session variable `HasCreatedTemporarySchema`, instead of relying on the temporary schema being set on the SearchPath.
___
*[pkg/sql/planner.go, line 399 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-9i4X5FJ3rqDemkbW:-Lw-uiPKAgndgr9q0AfP:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/planner.go#L399)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does this method need to be on the planner/exist? I think all callers have access to the `sessionDataMutator`. If it doesn't need to exist, I'd rather untangle the planner from performing mutations to the session state as much as possible.
</blockquote></details>

Removed.
___
*[pkg/sql/sequence.go, line 460 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-Cj9pCqPisVpKTkzs:-Lw-voPiBNE1B8g_oRSi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L460)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment should start with the function name and say what the function does, not abstractly what must happen. After explaining what it does, you can give a hint about when it's called, or even when it must be called.

```
dropSequencesOwnedByCol drops all the sequences from col.OwnsSequenceIDs. Called when the respective column (or the whole table) is being dropped.
```
</blockquote></details>

Done.
___
*[pkg/sql/sequence.go, line 462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-D_sB6wIF9ybBo_K_:-Lw-vSyS84NFfFwdYZqG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

One of the callers of this unnecessarily gates the call on `if len(col.OwnsSequenceIds) > 0`. The other caller doesn't. Get rid of the gating.
</blockquote></details>

Done.
___
*[pkg/sql/sequence.go, line 462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-Ed3w9JDj4Bg-85Ox:-Lw0X9mk52b14EpV05oC:b7gn6x5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This function doesn't really need to take a `col`, just a list of sequence ids -> `dropSequences()`. Being in `sequence.go`, tying it to column is not great. If you move it to another place that has to do with columns more, the objection might go away.
</blockquote></details>

Sure, but we miss the opportunity to implicitly document why these sequenceIDs are being dropped if we just drop a list of ids without any context. 

Seems like a lot of functions in this file take a column descriptor to work on a col/sequence relationship. I couldn't find a place that has to do with columns more, but if you'd like me to move this someplace specific, I can do that. 
___
*[pkg/sql/temporary_schema.go, line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-FSV6CE5XPDkG3ofD:-Lw-y5JH5cpZkdr6iBa9:b-qv9f2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L52)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/%v/%d/g

And please explain what this is and how it relates to the other `GetTemporarySchemaName()`.
</blockquote></details>

Done. Added a comment describing the purpose of this function so it is a bit less confusing.
___
*[pkg/sql/temporary_schema.go, line 65 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-GWxz0wGeEmHsYkNf:-Lw0TSYo376SatKD86TH:b-f7ehwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L65)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't understand what this comment is telling me. If you explain it more to me, perhaps I'll be able to suggest a better one.
</blockquote></details>

No need for this comment, as we aren't constructing an internal planner anymore.
___
*[pkg/sql/temporary_schema.go, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-FqGi2LuVPOxCNhX_:-Lw0TR8-4cvZ1Ts7_Vxu:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L66)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

double space after "can"
</blockquote></details>

ditto
___
*[pkg/sql/temporary_schema.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-JWzr5oZziCjGqUOk:-Lw-zk-B1h68nHx3YTNP:bp0lb2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/temporary_schema.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Can we go fully the SQL route and not read any descriptors, etc? Can we get the names of the tables that we want to delete from `system.namespace` or from `crdb_internal.tables`?
Cause if we can, I think it'd be a lot more readable.
</blockquote></details>

Then we won't be able to distinguish if the object is a view/sequence [...]

2019-12-16 16:55 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/conn_executor.go, line 752 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-6wEy8280Hnmisb9e:-LwEa_Ht-QIMtK9rNh5s:b-zgkv2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/conn_executor.go#L752)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant a comment that hints to who/when will retry. Like "// The such and such manager will retry periodically."
___
*[pkg/sql/create_table.go, line 1033 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEROz-4FYZCUn3SYN3:-LwEROz-4FYZCUn3SYN4:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/create_table.go#L1033)):*
> ```Go
> 	columnDefaultExprs := make([]tree.TypedExpr, len(n.Defs))
> 
> 	desc := InitTableDescriptor(id, parentID, parentSchemaID, n.Table.Table(), creationTime, privileges, temporary)
> ```

long line
___
*[pkg/sql/create_view.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwERfNpBcra0QX2_pOS:-LwERfNpBcra0QX2_pOT:b-8s8s4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/create_view.go#L160)):*
> ```Go
> 	semaCtx *tree.SemaContext,
> ) (sqlbase.MutableTableDescriptor, error) {
> 	desc := InitTableDescriptor(id, parentID, keys.PublicSchemaID, viewName, creationTime, privileges, false /* temporary */)
> ```

long line (the fact that it was already long is no excuse :) )
___
*[pkg/sql/drop_table.go, line 609 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6yrcDpUGhEKsfOd8:-LwEaLWxCuwIQd-Pp41L:b-i0htb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/drop_table.go#L609)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I have, but I've also changed `drop_database.go` to use this codepath, and concatenate the return value of this function to `tbNameStrings`. Should I delete this comment completely/move it back to `drop_database.go`?
</blockquote></details>

Rafa what's the right thing to do here?
___
*[pkg/sql/opt_catalog.go, line 112 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwETFQNC-B8JmnngsRn:-LwETFQNC-B8JmnngsRo:b6w4rb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/opt_catalog.go#L112)):*
> ```Go
> 		os.name.Schema(),
> 		true,  /* explicitPrefix */
> 		false, /* required */
> ```

required used to be implicitly `true`. Did you mean to change it?
___
*[pkg/sql/resolver.go, line 70 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwETbuD6Kor1Kvk587e:-LwETbuD6Kor1Kvk587f:b-l8yiys) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/resolver.go#L70)):*
> ```Go
> 	scName string,
> 	explicitPrefix bool,
> 	required bool,
> ```

The new argument needs a comment (and add one for `explicitPrefix` too if you can).
Consider changing this `bool` to an enum, such that the values are self-documenting. Bool args are discouraged by the style guide. 

Feel free to ignore, but better yet, would it be appropriate for this to take `DatabaseListFlags`? Perhaps a flavor of that with the caching flags stripped out if caching is not a reasonable concern for the callers.
___
*[pkg/sql/sequence.go, line 462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-Lw-Ed3w9JDj4Bg-85Ox:-LwEbh625tEBl7pNYi7z:b32wtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Sure, but we miss the opportunity to implicitly document why these sequenceIDs are being dropped if we just drop a list of ids without any context. 

Seems like a lot of functions in this file take a column descriptor to work on a col/sequence relationship. I couldn't find a place that has to do with columns more, but if you'd like me to move this someplace specific, I can do that. 
</blockquote></details>

ok
___
*[pkg/sql/temporary_schema.go, line 72 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwESBZlDz_ldxwSyXOI:-LwESBZlDz_ldxwSyXOJ:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L72)):*
> ```Go
> 	a := UncachedPhysicalAccessor{}
> 	return a.GetObjectNames(
> 		ctx, txn, dbDesc, tempSchemaName, tree.DatabaseListFlags{CommonLookupFlags: tree.CommonLookupFlags{Required: false}},
> ```

long line
___
*[pkg/sql/temporary_schema.go, line 76 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEcURI04DNARJWTkLr:-LwEcURI04DNARJWTkLs:belys6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L76)):*
> ```Go
> }
> 
> // cleanupSessionTempObjects removes all temporary objects (tables, sequences,
> ```

this function looks better, thanks
___
*[pkg/sql/temporary_schema.go, line 120 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEc_7p1H7YOaAbN5SV:-LwEc_7p1H7YOaAbN5SW:bfp8b09) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L120)):*
> ```Go
> 				}
> 			}
> 			// Even if no objects were found under the temporary schema, it may still
> ```

nit: s/it/the schema itself
___
*[pkg/sql/vars.go, line 832 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEc4fw1sZ_GN8ip980:-LwEc4fw1sZ_GN8ip981:b40e7p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/vars.go#L832)):*
> ```Go
> 	},
> 
> 	`has_created_temporary_schema`: {
> ```

let's move this state to the `connEx` as discussed
___
*[pkg/sql/sessiondata/search_path.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEVnD981Oa941FQj7U:-LwEVnD981Oa941FQj7V:bpudu39) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sessiondata/search_path.go#L28)):*
> ```Go
> // schema if/when CRDB supports them. In PG, schema names starting with `pg_`
> // are "reserved", so this can never clash with an actual physical schema.
> const DefaultTemporarySchemaName = "pg_no_temp_schema"
> ```

I thought this was going away?


<!-- Sent from Reviewable.io -->

2019-12-16 20:39 UTC, knz reviewed
Looks generally good, although I'd like a last look after Andrei's remaining comments have been addressed.

> Reviewed 1 of 23 files at r4, 7 of 55 files at r6, 8 of 15 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LwFQrsa3tqnE2VSiPhs:b-w0p2rk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @solongordon)

___
*[pkg/sql/drop_database.go, line 144 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFPokx8inJ4TxNLy8X:-LwFPoky4YrOlipFTm4u:bpg9s42) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/drop_database.go#L144)):*
> ```Go
> 
> 	for _, toDel := range n.td {
> 		cascadedViews, err := p.dropObject(ctx, toDel.desc, tree.DropCascade)
> ```

rename `cascadedViews` to `cascadedObjects`
___
*[pkg/sql/drop_table.go, line 609 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LvC6yrcDpUGhEKsfOd8:-LwFPz1eCHibBFMCaMOo:b-qa473u) ([raw file](https://github.com/cockroachdb/cockroach/blob/052ae7b3cf942de63e4b8e1f622003fef9a3259d/pkg/sql/drop_table.go#L609)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Rafa what's the right thing to do here?
</blockquote></details>

With the new code structure, the comment is now relevant. Nothing else to change here.
___
*[pkg/sql/opt_catalog.go, line 112 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwETFQNC-B8JmnngsRn:-LwFQCHU5pwHp5MTiYrN:b-wc7xq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/opt_catalog.go#L112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

required used to be implicitly `true`. Did you mean to change it?
</blockquote></details>

same question, this sounds like this should be required here
___
*[pkg/sql/sequence.go, line 462 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQRYK6fNwTtTnuOFf:-LwFQRYK6fNwTtTnuOFg:b-ptbjgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/sequence.go#L462)):*
> ```Go
> // dropSequencesOwnedByCol drops all the sequences from col.OwnsSequenceIDs.
> // Called when the respective column (or the whole table) is being dropped.
> func dropSequencesOwnedByCol(ctx context.Context, col *sqlbase.ColumnDescriptor, p *planner) error {
> ```

Make this a method on  `planner` instead of passing the planner as argument.
___
*[pkg/sql/sequence.go, line 484 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQWccBtHUCFwD9TYs:-LwFQWcd1Zr38p6mHlWX:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/sequence.go#L484)):*
> ```Go
> 	tableDesc *sqlbase.MutableTableDescriptor,
> 	col *sqlbase.ColumnDescriptor,
> 	p *planner,
> ```

ditto
___
*[pkg/sql/temporary_schema.go, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQelc4d_KMtGGPnDV:-LwFQelc4d_KMtGGPnDW:bnljhyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L115)):*
> ```Go
> 				// nil transaction ensures that the internal executor runs the schema
> 				// change, which drains names and deletes the data.
> 				_, err = ie.Exec(ctx, "delete-temp_tables", nil /* txn */, query.String())
> ```

`delete-temp-tables`


<!-- Sent from Reviewable.io -->

2019-12-17 00:38 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @solongordon)

___
*[pkg/sql/create_table.go, line 1033 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEROz-4FYZCUn3SYN3:-LwFhKV0BYTTxOX5pUb3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/create_table.go#L1033)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwERfNpBcra0QX2_pOS:-LwFh_DX1CAfJt2h6BSc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/create_view.go#L160)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line (the fact that it was already long is no excuse :) )
</blockquote></details>

Done.
___
*[pkg/sql/drop_database.go, line 144 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFPokx8inJ4TxNLy8X:-LwFhie_2PuwWbIGSHFC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/drop_database.go#L144)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

rename `cascadedViews` to `cascadedObjects`
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 112 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwETFQNC-B8JmnngsRn:-LwFhqJh-eH6XwYpHrD4:b-u94gma) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/opt_catalog.go#L112)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

same question, this sounds like this should be required here
</blockquote></details>

My bad. Fixed. 
___
*[pkg/sql/resolver.go, line 70 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwETbuD6Kor1Kvk587e:-LwG-j2l7qwOwcHvLoFB:byauc4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/resolver.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The new argument needs a comment (and add one for `explicitPrefix` too if you can).
Consider changing this `bool` to an enum, such that the values are self-documenting. Bool args are discouraged by the style guide. 

Feel free to ignore, but better yet, would it be appropriate for this to take `DatabaseListFlags`? Perhaps a flavor of that with the caching flags stripped out if caching is not a reasonable concern for the callers.
</blockquote></details>

Changed back, added a comment for `explicitPrefix`.
___
*[pkg/sql/sequence.go, line 462 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQRYK6fNwTtTnuOFf:-LwFjrDU3SNsAt2vdnMZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/sequence.go#L462)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Make this a method on  `planner` instead of passing the planner as argument.
</blockquote></details>

Done.
___
*[pkg/sql/sequence.go, line 484 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQWccBtHUCFwD9TYs:-LwFkBmBBZsN5-2Xeexd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/sequence.go#L484)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/temporary_schema.go, line 72 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwESBZlDz_ldxwSyXOI:-LwFkLFZ69YMbDijFodN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L72)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/temporary_schema.go, line 76 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEcURI04DNARJWTkLr:-LwFkLq5BoszvC_91CaI:b-j1we20) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L76)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this function looks better, thanks
</blockquote></details>

:raised_hands: 
___
*[pkg/sql/temporary_schema.go, line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwFQelc4d_KMtGGPnDV:-LwFkYEM0o4TkzQ-GlvX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/temporary_schema.go#L115)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`delete-temp-tables`
</blockquote></details>

Done.
___
*[pkg/sql/vars.go, line 832 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEc4fw1sZ_GN8ip980:-LwFngp05X0VSv4k5Z7z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37ad7bb1dec23c394e0e88f14316d5d3416c682a/pkg/sql/vars.go#L832)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's move this state to the `connEx` as discussed
</blockquote></details>

Done.
___
*[pkg/sql/sessiondata/search_path.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwEVnD981Oa941FQj7U:-LwFwAVfEHawrbkbH8LR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f95d2cce87c8bc212ad4abcaaf106451a0b9c7ae/pkg/sql/sessiondata/search_path.go#L28)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I thought this was going away?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-17 11:58 UTC, knz approved these changes
You'll need to update the expected output in the show_trace test with the new parent schema ID.

LGTM beyond that. Thank you!

> Reviewed 22 of 22 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LwIhVyr2pfNHAsFGOAy:bt48ddv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)



<!-- Sent from Reviewable.io -->

2019-12-17 19:25 UTC, andreimatei approved these changes
LGTM

Not for this PR, but there's 6 remaining `TODO(arul)` in the codebase. Please update them to different names.

> Reviewed 1 of 23 files at r4, 1 of 22 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LwJm6FrDXzR_nfwzqUF:bn4f50o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @solongordon)

___
*[pkg/ccl/importccl/load.go, line 169 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwJmNRI9BQRwJc0ccM9:-LwJmNRI9BQRwJc0ccMA:b-3t9yb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/ccl/importccl/load.go#L169)):*
> ```Go
> 			// At this point the CREATE statements in the loaded SQL do not
> 			// use the SERIAL type so we need not process SERIAL types here.
> 			desc, err := sql.MakeTableDesc(ctx, txn, nil /* vt */, st, s, dbDesc.ID, keys.PublicSchemaID, 0, /* table ID */
> ```

long line
Please put a visual cue in your editor.
___
*[pkg/sql/conn_executor.go, line 988 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwJnCrJCfpdQKvbmnEw:-LwJnCrJCfpdQKvbmnEx:b90wto2) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/conn_executor.go#L988)):*
> ```Go
> 	executorType executorType
> 
> 	// hasCreatedTemporarySchema is set to true if the executor has created a
> ```

nit: s/set to true/set
___
*[pkg/sql/create_sequence.go, line 147 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwJnJzU9UetyiYpucsu:-LwJnJzU9UetyiYpucsv:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_sequence.go#L147)):*
> ```Go
> 	params *runParams,
> ) (sqlbase.MutableTableDescriptor, error) {
> 	desc := InitTableDescriptor(id, parentID, keys.PublicSchemaID, sequenceName, creationTime, privileges, false /* temporary */)
> ```

long line
___
*[pkg/sql/create_table.go, line 1021 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwK6spU2GEHTmH8kunu:-LwK6spV1F5aU4TxM0bF:b-r91gsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_table.go#L1021)):*
> ```Go
> 	st *cluster.Settings,
> 	n *tree.CreateTable,
> 	parentID, parentSchemaID, id sqlbase.ID,
> ```

parentID and parentSchemaID need comments now. Should `parentID` be renamed to `parentDatabaseID`?
___
*[pkg/sql/drop_table.go, line 375 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwKEePn9v8TsD5LlrIQ:-LwKEePn9v8TsD5LlrIR:bfeocir) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/drop_table.go#L375)):*
> ```Go
> 	if drainName {
> 		parentSchemaID := tableDesc.GetParentSchemaID()
> 		if parentSchemaID == sqlbase.InvalidID {
> ```

Don't use the getter if there's no particular reason; proto fields are generally accessed directly. As written, that auto-generated getter should not even exist - except someone had the bright idea to use the `gogoproto.goproto_getters` option on this particular proto so that the generated struct implements some interface. They needed like 2 getters and we got 100.

More importantly, I don't like it that two callers need to do this `if parentSchemaID == sqlbase.InvalidID {` business. This should all be centralized. One way or another, the getter should do it (and then having a getter would actually make sense). Unfortunately the getter name `GetParentSchemaID()` is taken.

Some options:
1. Make the field nullable and give it a `default = 29` (since this file is proto2 you can have defaults). Then the getter does the right thing. But setting the field is a bit more annoying cause one way or another you have to create pointers from the values you want to set it to (see `proto.Int()`).
2. Implement another getter (say, `GetParentSchemaIDOrDefault()`) and comment everywhere that that one should be used. If you're filling hot, there's precedent to adding a linter to disallow the default getter (see descriptor_marshall.go)
3. Get rid of the `gogoproto.goproto_getters`. Copy all the getters that are already generated and used from structured.pb.go to structured.go, so they stay around. And then`GetParentSchemaID()` is under our control.
___
*[pkg/sql/exec_util.go, line 1756 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwKIQGE-yvpQCmIIUIP:-LwKIQGE-yvpQCmIIUIQ:b-btn4st) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/exec_util.go#L1756)):*
> ```Go
> 	// setHasCreatedTemporarySchema is called when the temporary schema is set
> 	// on the search path.
> 	setHasCreatedTemporarySchema func(val bool)
> ```

Name this according to when it's called, not what it does. Think of this as an event listener; the caller doesn't care what it does. In the case of `setCurTxnReadOnly` above, the name sounds like it describes what it does, but it actually describes when its called (on a `set` statement).
```
// onTempSchemaCreation is called when the temporary schema is created (for the first time? there can be multiple temp schemas, right?)
onTempSchemaCreation
```
___
*[pkg/sql/exec_util.go, line 1796 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwKJQ4lDzbswbuCvDUB:-LwKJQ4lDzbswbuCvDUC:b1jjhya) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/exec_util.go#L1796)):*
> ```Go
> 
> func (m *sessionDataMutator) SetTemporarySchemaName(scName string) {
> 	m.setHasCreatedTemporarySchema(true)
> ```

if you rename `m.setHasCreatedTemporarySchema`, extract this out of this method. And at that point the method can go away if you want.


<!-- Sent from Reviewable.io -->

2019-12-18 01:06 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @solongordon)

___
*[pkg/ccl/importccl/load.go, line 169 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwJmNRI9BQRwJc0ccM9:-LwKjxZxCMRsStd52Its:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/ccl/importccl/load.go#L169)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
Please put a visual cue in your editor.
</blockquote></details>

Done.
___
*[pkg/sql/create_sequence.go, line 147 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwJnJzU9UetyiYpucsu:-LwKkFXW8QaxOm1QUw8p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_sequence.go#L147)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1021 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwK6spU2GEHTmH8kunu:-LwKkHVF5b9d8r6kjnx5:b-awb7km) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_table.go#L1021)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

parentID and parentSchemaID need comments now. Should `parentID` be renamed to `parentDatabaseID`?
</blockquote></details>

Added the comments. 

Could do that, if we make rename the field on the table descriptor. Would require accounting for all descriptors created before 20.1 though, and the change will have to be made in a lot more places. I'd say that should be considered as a separate PR?
___
*[pkg/sql/drop_table.go, line 375 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwKEePn9v8TsD5LlrIQ:-LwLN3G6CW8VVlDqWcM1:b7lx3wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/drop_table.go#L375)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Don't use the getter if there's no particular reason; proto fields are generally accessed directly. As written, that auto-generated getter should not even exist - except someone had the bright idea to use the `gogoproto.goproto_getters` option on this particular proto so that the generated struct implements some interface. They needed like 2 getters and we got 100.

More importantly, I don't like it that two callers need to do this `if parentSchemaID == sqlbase.InvalidID {` business. This should all be centralized. One way or another, the getter should do it (and then having a getter would actually make sense). Unfortunately the getter name `GetParentSchemaID()` is taken.

Some options:
1. Make the field nullable and give it a `default = 29` (since this file is proto2 you can have defaults). Then the getter does the right thing. But setting the field is a bit more annoying cause one way or another you have to create pointers from the values you want to set it to (see `proto.Int()`).
2. Implement another getter (say, `GetParentSchemaIDOrDefault()`) and comment everywhere that that one should be used. If you're filling hot, there's precedent to adding a linter to disallow the default getter (see descriptor_marshall.go)
3. Get rid of the `gogoproto.goproto_getters`. Copy all the getters that are already generated and used from structured.pb.go to structured.go, so they stay around. And then`GetParentSchemaID()` is under our control.


</blockquote></details>

Discussed offline, changed the field to `UnexposedParentSchemaID` and added a getter `GetParentSchemaID()` in `structured.go`
___
*[pkg/sql/exec_util.go, line 1756 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwKIQGE-yvpQCmIIUIP:-LwKmf_9AEHtAjQ6ezDW:b-ble3uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/exec_util.go#L1756)):*
> there can be multiple temp schemas, right?

Just one per session (executor). Done. 


<!-- Sent from Reviewable.io -->

2019-12-18 08:42 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/create_table.go, line 1021 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwK6spU2GEHTmH8kunu:-LwNA-I5AEE2cTKBmPQ-:b-tmmip) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_table.go#L1021)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Added the comments. 

Could do that, if we make rename the field on the table descriptor. Would require accounting for all descriptors created before 20.1 though, and the change will have to be made in a lot more places. I'd say that should be considered as a separate PR?
</blockquote></details>

(FYI Renaming the field does not affect existing descriptors. No comment further about when to do it though.)


<!-- Sent from Reviewable.io -->

2019-12-18 15:14 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/create_table.go, line 1021 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwK6spU2GEHTmH8kunu:-LwOZ4os1u6-WzbPhz5c:b7ko39v) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_table.go#L1021)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

(FYI Renaming the field does not affect existing descriptors. No comment further about when to do it though.)
</blockquote></details>

I had missed that this goes directly into the descriptor. I'd leave it alone then, and consider renaming it in a different commit. And then I'd drop the "parent" prefix from both the database and the schema fields.
For now just please make sure that the descriptor has a comment telling me that one of them is a database id.


<!-- Sent from Reviewable.io -->

2019-12-18 15:59 UTC, arulajmani reviewed
Fixed a failing test, should be good to merge now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-:-LwOj1QcBXAi4sQtGX4C:bz8l1ek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, @knz, and @solongordon)

___
*[pkg/sql/create_table.go, line 1021 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42742#-LwK6spU2GEHTmH8kunu:-LwOhi6u9D26k8oNcB1c:bd4ay2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/53b297d0e8e94f1ccf0032bfb947784df3a998aa/pkg/sql/create_table.go#L1021)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I had missed that this goes directly into the descriptor. I'd leave it alone then, and consider renaming it in a different commit. And then I'd drop the "parent" prefix from both the database and the schema fields.
For now just please make sure that the descriptor has a comment telling me that one of them is a database id.
</blockquote></details>

I think the descriptor already has a comment saying the parentID refers to the parent database. 

I'd be in favor of renaming it in a different commit too. 


<!-- Sent from Reviewable.io -->

2019-12-18 15:59 UTC, arulajmani commented
bors r+

2019-12-18 16:41 UTC, merged