sql/rowexec: select only required rows for interleaved_reader_joiner
cockroachdb/cockroach pull request #42798
Opened 2019-11-26 19:32 UTC by otan

Refs: #42609

interleaved_reader_joiner seems to have an out of date comment that it
needed to select every column when doing a join. This comment seems two
years old and outdated; furthermore, it causes a bug when trying to
select every column but trips up because it does not have permission to
do so. I imagine the planner will now be smart and do this for us
instead, so we can be more selective about the rows being picked.

Release note (bug fix): Fix a bug where selecting cols by forcing an
INTERLEAVING index would error instead of returning the correct results.

2019-11-26 19:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42798)
<!-- Reviewable:end -->

2019-11-26 19:35 UTC, rohany commented
I think this is the right way of doing this, lets see if the tests pass.

2019-11-26 22:28 UTC, rohany requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, and @rohany)

___
*[pkg/sql/rowexec/interleaved_reader_joiner.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42798#-Ludp1hz8MBlwwqJQ-Jw:-Ludp1hz8MBlwwqJQ-Jx:b-npdcix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d1e8e3cc9e318a33a563b9f581f1e406689bb2/pkg/sql/rowexec/interleaved_reader_joiner.go#L414)):*
> ```Go
> 		}
> 
> 		if table.Post.Projection {
> ```

can you use the ProcOutputHelper.NeededColumns() here? It seems to duplicate this logic -- `irj.Out.NeededColumns()`


<!-- Sent from Reviewable.io -->

2019-11-26 22:57 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42798)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/rowexec/interleaved_reader_joiner.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42798#-Ludp1hz8MBlwwqJQ-Jw:-LudvhjxChfXyYxR90d4:b84gcis) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d1e8e3cc9e318a33a563b9f581f1e406689bb2/pkg/sql/rowexec/interleaved_reader_joiner.go#L414)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

can you use the ProcOutputHelper.NeededColumns() here? It seems to duplicate this logic -- `irj.Out.NeededColumns()`
</blockquote></details>

Yep. Didn't know that existed *sigh*.


<!-- Sent from Reviewable.io -->

2019-11-27 03:28 UTC, rohany commented
LGTM -- lets just check with jordan if he remembers the original reasoning for those comments.

2019-12-02 21:28 UTC, jordanlewis reviewed
This <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

The comment (I believe) was referring to the fact that the output of the fetcher needs to contain *indexes* for all of the columns in the table, because that's just part of the join contract. This is still true. But the comment was incorrectly using that fact as justification for marking all columns as *required*, which is a separate concept.

To illustrate (in case this is helpful) with a simpler case, let's say we had a table `t (a int, b int, c int)`, and we had the query `SELECT a from t WHERE c=3`. In this case, I believe the associated TableReader should output all of the columns, `a b c`, but only actually includes values for the needed columns, which are `a` and `c`.

So the associated output row from the table reader, if there was a row `1 2 3`, would basically look like `1 nil 3` - the `b` value would just not get filled in by the fetcher.

This situation is definitely not ideal - I think it would be cleaner if the readers just didn't have slots for things that aren't needed - but that's just how the contracts work at the moment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42798#-:-Lv7UskX078BlBUrgaSB:blkvvhe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)



<!-- Sent from Reviewable.io -->

2019-12-02 22:50 UTC, rohany commented
:lgtm:

2019-12-02 22:54 UTC, rohany approved these changes

2019-12-02 23:03 UTC, otan commented
bors r+

2019-12-02 23:26 UTC, merged