coldata: expose a modifier for batchSize variable
cockroachdb/cockroach pull request #42845
Opened 2019-11-27 21:41 UTC by yuzefovich

This commit exposes a setter for batchSize private variable to be
modified in tests and runs all tests in sql/colexec with 3 different
batch sizes.

Release note: None

2019-11-27 21:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42845)
<!-- Reviewable:end -->

2019-11-27 21:42 UTC, yuzefovich commented
Not requesting a review for now since I want to see what the fallout is first. We probably will want to limit the config to two batch sizes - the default (1024) and a random (I think it must be greater than 1).

2019-12-20 02:17 UTC, yuzefovich commented
This didn't discover any new bugs, but #42816 would have been caught by this change when `batchSize` is set to 3.

Also, I'm not sure whether we want to randomize the second batch size or just pick 3 (smallest I've tried).

2020-01-13 14:37 UTC, asubiotto requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42845)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUIdJM-q0R5atoMXmP:-LyUIdJM-q0R5atoMXmQ:bp4huqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L63)):*
> ```Go
> const (
> 	// MinBatchSize is the minimum acceptable size of batches.
> 	MinBatchSize = 3
> ```

What happens if we make this 1?
___
*[pkg/col/coldata/batch.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUJHQoAsIDl8G-vyCS:-LyUJHQoAsIDl8G-vyCT:b5lb16l) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L65)):*
> ```Go
> 	MinBatchSize = 3
> 	// MaxBatchSize is the maximum acceptable size of batches.
> 	MaxBatchSize = 1024
> ```

Do we want to try having a max batch size > 1024?
___
*[pkg/col/coldata/batch.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUKAdR29maCSPiAvEt:-LyUKAdS0VqYLhSdN0En:bnpxufl) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L78)):*
> ```Go
> // SetBatchSizeForTests modifies batchSize variable. It should only be used in
> // tests.
> func SetBatchSizeForTests(newBatchSize uint16) {
> ```

I wonder if there's a way to only make this method available during tests. Does putting it in a `_test.go` file work?
___
*[pkg/sql/colexec/main_test.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUIyKmAg5c9yALWFmG:-LyUIyKn8fKFZEZUEeqX:b-20hjle) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/sql/colexec/main_test.go#L57)):*
> ```Go
> 			fmt.Printf("coldata.BatchSize() is set to %d\n", batchSize)
> 			coldata.SetBatchSizeForTests(batchSize)
> 			if code := m.Run(); code != 0 {
> ```

Do we want to run these tests twice? How does the runtime increase? I think we should just run them with a random batch size that we print out in the same way that the random seed is printed out using `randutil`.
___
*[pkg/sql/colexec/routers_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUJss26HEEhsRXyIvf:-LyUJss26HEEhsRXyIvg:bg0xab6) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/sql/colexec/routers_test.go#L477)):*
> ```Go
> 
> 	if _, ok := expectedNumVals[batchSize]; !ok {
> 		// We do not have a precomputed expectedNumVals for this batch size, so we
> ```

But then we have a very low probability of actually running this test. We might want to override the batch size here by getting the batch size, calling `SetBatchSize` ourselves with a constant value, then resetting it with a defer.


<!-- Sent from Reviewable.io -->

2020-01-13 23:10 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42845)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUIdJM-q0R5atoMXmP:-LyW-gg67TKqEKTy9SZe:bwbw8as) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L63)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What happens if we make this 1?
</blockquote></details>

There are multiple unit tests that have baked-in assumption of a "big" batch size, those would need to be changed. Also, I feel like some operators might have that assumption, and they might get stuck in an infinite loop or something (or maybe not). I'm not sure how much of a change that would be, but I think we will benefit from getting this PR in with 3 as the minimum and then during stabilization period possibly pushing it all the way down to 1.
___
*[pkg/col/coldata/batch.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUJHQoAsIDl8G-vyCS:-LyW6TNZ-soT0xmMKYuI:b-x3gtzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L65)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to try having a max batch size > 1024?
</blockquote></details>

I tried with 2048, 4096, and 8192, and the tests passed (I needed to do a minor tweak to one aggregator random test because there was uint16 overflow). I do feel that unless we decide to use bigger batch sizes in production, there is not much benefit from testing with larger sizes - most of our unit tests have very little data, so if we increase the batch size, the likelihood of uncovering a bug doesn't seem to increase (nor to decrease). Running randomized unit tests might get slightly better coverage at the expense of longer runtime. I think that pushing the minimum as low as possible is beneficial, not sure about the maximum though.
___
*[pkg/col/coldata/batch.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUKAdR29maCSPiAvEt:-LyVymvo9GtYHRHivYBF:b-3k1bww) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/col/coldata/batch.go#L78)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if there's a way to only make this method available during tests. Does putting it in a `_test.go` file work?
</blockquote></details>

Unfortunately, that doesn't work. If we move the setter method in `_test` file, it is only visible within `coldata` package (not even `coldata_test`); if we move it to `coldata_test` package, then it is visible only that package.
___
*[pkg/sql/colexec/main_test.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUIyKmAg5c9yALWFmG:-LyW7Kzp0Dk9k93zLs_q:b-f954xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/sql/colexec/main_test.go#L57)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to run these tests twice? How does the runtime increase? I think we should just run them with a random batch size that we print out in the same way that the random seed is printed out using `randutil`.
</blockquote></details>

The runtime increases more or less linearly (there are randomized unit tests which depend on the batch size, so with the smaller sizes, those run faster). The whole test suite of `colexec` package takes 10 seconds or so on my laptop, I think we could run it with the default batch size and a random one, but I'm not sure whether that would give us any benefits. Switched to only random batch size.
___
*[pkg/sql/colexec/routers_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-LyUJss26HEEhsRXyIvf:-LyW9cmKDvW1_YRMRUim:bd6y8qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/88202476d0b358fadc3a626e73b0ed9d335dffce/pkg/sql/colexec/routers_test.go#L477)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But then we have a very low probability of actually running this test. We might want to override the batch size here by getting the batch size, calling `SetBatchSize` ourselves with a constant value, then resetting it with a defer.
</blockquote></details>

True, I was imagining this being useful if we always run the tests with the default config. Changed.


<!-- Sent from Reviewable.io -->

2020-01-14 15:26 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42845#-:-LyZeU_20kMf7sOTNJzg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-01-14 20:19 UTC, yuzefovich commented
TFTR!

bors r+

2020-01-14 20:54 UTC, andreimatei commented
if you know anything about the failure, say on https://github.com/cockroachdb/cockroach/issues/43949

2020-01-14 21:19 UTC, yuzefovich commented
An unrelated flake.

bors r+

2020-01-14 22:23 UTC, merged