sql: native support for creating hash sharded indexes
cockroachdb/cockroach pull request #42922
Opened 2019-12-03 20:39 UTC by aayushshah15

This PR accompanies the hash sharded indexes RFC (TODO).

Currently, in CockroachDB, write workloads that are sequential on a
particular key will cause a hotspot on a single range if there's any
sort of index with the said key as a prefix.

This PR alleviates this problem by allowing users to _shard_ their
indexes into a specific number of buckets by creating a computed shard
column under the hood and prefixing the index with this shard column in
order to distribute sequential traffic uniformly over the index's ranges.

Fixes #39340

TODOs:
1) Gate the creation of hash sharded indexes to 20.1

Release note (sql change): Improve user experience for creating hash
                           sharded indexes.

2019-12-03 20:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/42922)
<!-- Reviewable:end -->

2019-12-03 21:28 UTC, rohany requested changes
I took a cursory look at this after reading the RFC

> Reviewed 6 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LvCePFc-auKcTlV6tky:bhz2ad7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCabKg4845A75rNx0-:-LvCabKg4845A75rNx00:b-jt2gkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38c575abaa806042d580ba821b938607ce3c023/pkg/sql/create_index.go#L142)):*
> ```Go
> }
> 
> func createAndAddShardColToTable(
> ```

I'm not 100% sure about computed columns, but I'm pretty sure they will need a backfill if they are stored on disk -- you'll have to add the column as a mutation rather than adding it directly to the table when this isn't in a create table statement.
___
*[pkg/sql/create_table.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCboVL3xZIHLn91Lp2:-LvCboVL3xZIHLn91Lp3:b-78zafj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38c575abaa806042d580ba821b938607ce3c023/pkg/sql/create_table.go#L1124)):*
> ```Go
> 			idxColumns := d.Columns
> 			if d.Sharded != nil {
> 				var colNames []string
> ```

This code feels like its been duplicated many times -- is there a way to unify this?


<!-- Sent from Reviewable.io -->

2019-12-04 18:52 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvHF1-d0DZ85cI7hO9d:-LvHEd5W7lfIA3Ql3V2X:bnjloiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L65)):*
> ```
>                         FAMILY "primary" (a, a_shard__internal, rowid)
> )
> ```

We should write tests around `CREATE INDEX`. Also it'd be good to exercises cases of dropping and re-adding sharded indexes. Also probably worthwhile to add some rows to the table. 

There are some logic tests which look at plans. They may be useful here. 
___
*[pkg/sql/parser/sql.y, line 4814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvHFIk19gviCTU5AXlS:-LvHFIk19gviCTU5AXlT:b-5jxdc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/parser/sql.y#L4814)):*
> ```Yacc
> 
> opt_hash_sharded:
>   USING HASH WITH BUCKET_COUNT '=' a_expr
> ```

I made this comment on the other PR. How do you feel about using the opt_with_clause here instead of makign `BUCKET_COUNT` a token in the grammar?


<!-- Sent from Reviewable.io -->

2019-12-04 18:54 UTC, aayushshah15 commented
___
*[pkg/sql/parser/sql.y, line 4814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvHFIk19gviCTU5AXlS:-LvHFok_9V3XTcbKUw-D:blg81lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/parser/sql.y#L4814)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I made this comment on the other PR. How do you feel about using the opt_with_clause here instead of makign `BUCKET_COUNT` a token in the grammar?
</blockquote></details>

Yup sounds good, on it.


<!-- Sent from Reviewable.io -->

2019-12-10 04:14 UTC, yuzefovich reviewed
Nice work!

I'm not too familiar with this part of the codebase, but I left some nits and questions.

> Reviewed 12 of 19 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LvhzLUn1yPxr07lD_aK:b-7ls2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @jordanlewis, @rohany, and @solongordon)

___
*[pkg/sql/create_index.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhtTW-Bxf69RNeslio:-LvhtTW-Bxf69RNeslip:b-mbtcpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L105)):*
> ```Go
> 		// check constraint here, but doing it above this function would lead to a bunch
> 		// of code duplication.
> 		ckDef, err := makeShardCheckConstraintDef(tableDesc, int(buckets), shardCol)
> ```

The error here is unchecked.

Why you don't like creating a check constraint here?
___
*[pkg/sql/create_index.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhs1Bu92BzUoq3dIhE:-Lvhs1BvAoopW4G0TtVH:b-8ojbn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L145)):*
> ```Go
> 	shardBuckets int, desc *sqlbase.MutableTableDescriptor, colNames []string, shouldAssignID bool,
> ) (*sqlbase.ColumnDescriptor, error) {
> 	shardCol, err := makeShardColumnDesc(colNames, shardBuckets, false)
> ```

[nit]: please add an inline comment what argument `false` is here for.
___
*[pkg/sql/create_index.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhsKXQDeF3ZVUkpqv5:-LvhsKXQDeF3ZVUkpqv6:brk44wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L149)):*
> ```Go
> 		return nil, err
> 	}
> 	if !hasColumn(*desc, shardCol.Name) {
> ```

This check seems slightly suspicious to me - the function is named "create and add" shard column, so I'd expect for shard column to always be added. It probably deserves a callout in the comment for the method.
___
*[pkg/sql/create_index.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhu9Xx6v2xD91Nxf60:-Lvhu9Xx6v2xD91Nxf61:b-ii36in) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L169)):*
> ```Go
> 	// index is created in a 'CREATE TABLE` statement but I can't be 100% sure. Does this
> 	// seem like a valid thing to do?
> 	if shouldAssignID {
> ```

Why wouldn't we want to assign an ID on every creation? Is this what your comment is about as well?
___
*[pkg/sql/create_table.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCboVL3xZIHLn91Lp2:-LvhuhM10rD2wCbamZoN:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38c575abaa806042d580ba821b938607ce3c023/pkg/sql/create_table.go#L1124)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This code feels like its been duplicated many times -- is there a way to unify this?
</blockquote></details>

+1
___
*[pkg/sql/sem/tree/create.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhwsKg1vtLROvKucJh:-LvhwsKg1vtLROvKucJi:b-k0iziq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe31961f053aadbde0cbf2fdadfbdcd7c8d459a/pkg/sql/sem/tree/create.go#L566)):*
> ```Go
> 	if node.Name != "" {
> 		ctx.FormatNode(&node.Name)
> 		ctx.WriteByte(' ')
> ```

We don't need this space?
___
*[pkg/sql/sqlbase/structured.go, line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhxQWrDV9Lb70ek8f7:-LvhxQWrDV9Lb70ek8f8:b-4k1ki7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.go#L499)):*
> ```Go
> 	if !ok {
> 		return 0, pgerror.New(pgcode.InvalidParameterValue,
> 			`BUCKET_COUNT must be a strictly positive integer value.`)
> ```

[nit]: the error message could be extracted into a variable.
___
*[pkg/sql/sqlbase/structured.go, line 587 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhxnun5ErfuVY1Cnff:-Lvhxnun5ErfuVY1Cnfg:b5k7n9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.go#L587)):*
> ```Go
> // IsSharded returns whether the index is hash sharded or not.
> func (desc *IndexDescriptor) IsSharded() bool {
> 	return !reflect.DeepEqual(desc.Sharded, ShardedDescriptor{})
> ```

This reflection check seems suspicious - I think usually we do interface conversion in such a scenario, is it not possible in this case?
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LvhyxHN458b_1ARpmcl:b-b6mrlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
> ```protobuf
> 
>   // Sharded, if it's not the zero value, describes how this index is sharded.
>   optional ShardedDescriptor sharded = 18 [(gogoproto.nullable) = false]; 
> ```

I think this field could be nullable, and then `IsSharded` check would compare this field against `nil`, no?


<!-- Sent from Reviewable.io -->

2019-12-10 20:18 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCabKg4845A75rNx0-:-Lvi85FA3Oukfj-HE4ER:b-39ytfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38c575abaa806042d580ba821b938607ce3c023/pkg/sql/create_index.go#L142)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm not 100% sure about computed columns, but I'm pretty sure they will need a backfill if they are stored on disk -- you'll have to add the column as a mutation rather than adding it directly to the table when this isn't in a create table statement.
</blockquote></details>

Thanks for pointing this out, fixed.
___
*[pkg/sql/create_index.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhtTW-Bxf69RNeslio:-Lvi9ncdA14hqqDT5ab7:bedos9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L105)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The error here is unchecked.

Why you don't like creating a check constraint here?
</blockquote></details>

I didn't like the idea of creating the shard column, its check constraint, etc inside of a method named `MakeIndexDescriptor` since that name makes it seem like it should only be doing that one thing. Fixed now.
___
*[pkg/sql/create_index.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhs1Bu92BzUoq3dIhE:-Lvi84WeEMkMW_F7FPZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L145)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: please add an inline comment what argument `false` is here for.
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhsKXQDeF3ZVUkpqv5:-Lvi95q583oxTIV60NAR:ba3lcjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L149)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This check seems slightly suspicious to me - the function is named "create and add" shard column, so I'd expect for shard column to always be added. It probably deserves a callout in the comment for the method.
</blockquote></details>

Made it more explicit. 
___
*[pkg/sql/create_index.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhu9Xx6v2xD91Nxf60:-LviAbJ73VRSBlvU_Kgv:beaxwq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/create_index.go#L169)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why wouldn't we want to assign an ID on every creation? Is this what your comment is about as well?
</blockquote></details>

I changed this to instead do a separate pass through all the indexes in the table (see `AssignFamiliesToShardColumns`) and if they're hash sharded, assign the shard column to the column family of the first column in the set of index columns. imo, it seems cleaner this way. Let me know if any of this doesn't make sense. 
___
*[pkg/sql/create_table.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCboVL3xZIHLn91Lp2:-LviFZTlBMc1FZZ3jmuT:bw8jbjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38c575abaa806042d580ba821b938607ce3c023/pkg/sql/create_table.go#L1124)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

+1
</blockquote></details>

I wanted to stay consistent to the pattern followed in the rest of that method, but in retrospect this seems misguided. Fixed now.
___
*[pkg/sql/sqlbase/structured.go, line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhxQWrDV9Lb70ek8f7:-LviC9He0_kbhE_bIJ49:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.go#L499)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the error message could be extracted into a variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-16 23:48 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvHF1-d0DZ85cI7hO9d:-LwG5nhP3bFG0jbqLzLr:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We should write tests around `CREATE INDEX`. Also it'd be good to exercises cases of dropping and re-adding sharded indexes. Also probably worthwhile to add some rows to the table. 

There are some logic tests which look at plans. They may be useful here. 
</blockquote></details>

Done. 
___
*[pkg/sql/sqlbase/structured.go, line 587 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lvhxnun5ErfuVY1Cnff:-LwG603u0aVwnZ_V_8lM:b-732la2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.go#L587)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This reflection check seems suspicious - I think usually we do interface conversion in such a scenario, is it not possible in this case?
</blockquote></details>

Changed that field to a pointer, see comment below.
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LwG64YJDGuN2mliyJVF:b-nbsls5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this field could be nullable, and then `IsSharded` check would compare this field against `nil`, no?
</blockquote></details>

Done. I'm curious, is there a good reason we force `nullable = false` for all the other fields?


<!-- Sent from Reviewable.io -->

2019-12-16 23:49 UTC, aayushshah15 reviewed
I still have to gate sharded index creation behind 20.1, but otherwise this is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LwG6HcF3sfSUMPzp95D:b-p66fan)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-12-17 01:07 UTC, rohany requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGH4Hj2PA_1fWZtSTM:-LwGH4HkBlwncT38MpGz:bfbdpwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_index.go#L84)):*
> ```Go
> 	}
> 
> 	if n.Sharded != nil {
> ```

Small nit, but I feel like this code would be cleaner if it was possible to move it into a separate function.
___
*[pkg/sql/create_table.go, line 992 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGHsI0BiEoe3F1FdIT:-LwGHsI0BiEoe3F1FdIU:b-re8a4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_table.go#L992)):*
> ```Go
> }
> 
> func hasColumn(desc sqlbase.MutableTableDescriptor, colName string) bool {
> ```

There is already a `findColumnByName` function you could use
___
*[pkg/sql/drop_index.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJ9CfAQKRfzii72yI:-LwGJ9CfAQKRfzii72yJ:brlywnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/drop_index.go#L131)):*
> ```Go
> 				for i := range tableDesc.Columns {
> 					if tableDesc.Columns[i].ID == shardColDesc.ID {
> 						tableDesc.Columns = append(tableDesc.Columns[:i:i], tableDesc.Columns[i+1:]...)
> ```

this allocates basically everytime you delete one of the elements -- probably better to do something like
```
tmp := tableDesc.Columns[:0]
// do the loop
if keep element {
  tmp = append(tmp, elem)
}
tableDesc.Columns = tmp
```
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwGJSch35Hgp4IpBGeh:b-o5m2jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
> ```
> SHOW CREATE TABLE sharded_primary
> ----
> sharded_primary  CREATE TABLE sharded_primary (
> ```

Do we want users to be able to "inspect" this sharded table and see whats actually happening, or no?
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwGJtj40bhF0cDDYijm:b-b156qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
> ```
>                    a INT8 NULL,
>                    INDEX sharded_secondary_a_shard_10_internal_a_idx (a ASC) USING HASH WITH BUCKET_COUNT=10,
>                    INDEX sharded_secondary_a_shard_4_internal_a_idx (a ASC) USING HASH WITH BUCKET_COUNT=4,
> ```

I might have missed this, but are there any issues with name conflicts if you made another sharded index on a with the same bucket counts here?
___
*[pkg/sql/parser/sql.y, line 5128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKMmxAMfyIotxRHau:-LwGKMmxAMfyIotxRHav:btv6zew) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/parser/sql.y#L5128)):*
> ```Yacc
> // 
> // Hash sharded clause: 
> //    USING HASH WITH BUCKET_COUNT = <shard_buckets>
> ```

just a thought, have we ruled out the syntax of
```
USING HASH WITH a_expr BUCKETS
```
___
*[pkg/sql/parser/sql.y, line 5132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKCYR-viJbeijDF_Q:-LwGKCYR-viJbeijDF_R:b-ag7ugz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/parser/sql.y#L5132)):*
> ```Yacc
> // %SeeAlso: CREATE TABLE, SHOW INDEXES, SHOW CREATE,
> // WEBDOCS/create-index.html
> // TODO DURING REVIEW: how do I clarify above that the hash sharded clause only applies to non-inverted indexes?
> ```

You'd want that to just show up in the docs -- i think we just do pure syntax here.
___
*[pkg/sql/sem/tree/create.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKYDb5lUIXLWqY6WY:-LwGKYDb5lUIXLWqY6WZ:b-irwesl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sem/tree/create.go#L217)):*
> ```Go
> 	}
> 	PrimaryKey struct {
> 		PrimaryKey   bool
> ```

rename this to IsPrimaryKey or something -- seeing this used in other places in the code was confusing
___
*[pkg/sql/sqlbase/structured.go, line 745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGLb9F765-QmFUkopP:-LwGLb9F765-QmFUkopQ:b-530kue) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L745)):*
> ```Go
> func (desc *MutableTableDescriptor) AssignFamiliesToShardColumns() error {
> 	getColumnFamilyForShard := func(shardCol string, idxColumns []string) (string, error) {
> 		for _, f := range desc.GetFamilies() {
> ```

just looping over the Families slice would be fine. also, we usually loop over the indices and index into the list for these larger structs to avoid copies
___
*[pkg/sql/sqlbase/structured.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGMNY93U7NhaXteyeI:-LwGMNY93U7NhaXteyeJ:bvdpjh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L765)):*
> ```Go
> 				return err
> 			}
> 			desc.RemoveColumnFromFamily(shardColDesc.ID)
> ```

Why do you remove the column from a family and then add it back?
___
*[pkg/sql/sqlbase/structured.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGMUtP9Qz7F7j9eaS5:-LwGMUtP9Qz7F7j9eaS6:bacybhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L775)):*
> ```Go
> 
> // PrintColumnNamesAndIDs prints list of column names and ids to stdout.
> func (desc *TableDescriptor) PrintColumnNamesAndIDs() {
> ```

should these be removed before merging?
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LwGNJUu7LxDs4_gzAd_:b-ksi8o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done. I'm curious, is there a good reason we force `nullable = false` for all the other fields?
</blockquote></details>

we do nullable = false to avoid a pointer (an allocation). I think you can make it not nullable and use the generated IsSet method.
___
*[pkg/sql/sqlbase/structured.proto, line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGNCwSBniUbLaD8uvF:-LwGNCwSBniUbLaD8uvG:b-4iz3q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.proto#L227)):*
> ```protobuf
>   // ColumnNames lists the names of the columns used to compute the shard column's
>   // values.
>   repeated string column_names = 3;
> ```

would it make sense to just hold onto column ID's here? I'm not sure why we need the names.
___
*[pkg/sql/sqlbase/table.go, line 225 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGNtr71j71kWiaUEOx:-LwGNtr71j71kWiaUEOy:blbh2cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/table.go#L225)):*
> ```Go
> // AddShardToIndexDesc populates the given index descriptor with details pertaining to how
> // it's sharded.
> func AddShardToIndexDesc(
> ```

This method basically doesn't do anythin [...]

2019-12-17 01:08 UTC, rohany reviewed
Theres alot of descriptor manipulation going on here -- since show create isn't a good way to introspect what the descriptor actually looks like at the end of the process, i think there should be some tests that look at raw table descriptors after the creation process and ensure things are as you expect.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LwGOHD_ECaOOwkp5UlT:b-d061o3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2019-12-17 16:02 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwJYSIUBR41BKpwePsx:b-1q7xn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Do we want users to be able to "inspect" this sharded table and see whats actually happening, or no?
</blockquote></details>

No, we'd decided that we wanted it to be transparent to the user.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwJZJBdBDMR9lomy6uV:b8urmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I might have missed this, but are there any issues with name conflicts if you made another sharded index on a with the same bucket counts here?
</blockquote></details>

This isn't a problem since postgres (and CRDB) allows creation of multiple identical indices. I'll add this to the logictests to make it clear. With regards to the hidden computed shard column, we reuse the same shard column if there is already an index on the same set of columns with the same bucket_count.
___
*[pkg/sql/parser/sql.y, line 5128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKMmxAMfyIotxRHau:-LwJZnZe9_QzdHWK9nC3:b-qteub8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/parser/sql.y#L5128)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

just a thought, have we ruled out the syntax of
```
USING HASH WITH a_expr BUCKETS
```
</blockquote></details>

We didn't consider it since we wanted to borrow from the SQL Server syntax. Additionally, the current approach allows us to add more options to this feature in the future.
___
*[pkg/sql/sqlbase/table.go, line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGO38EAeUbq3NZSawS:-LwJ_QKy5vC71S6K4SlG:btlmdup) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/table.go#L237)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

this will cause name conflicts if someone applies the duplicate index pattern on sharded indexes right?
</blockquote></details>

This is intentional since we want to avoid re-creating multiple shard columns that are always equivalent. See comment above and the `startExec` method in drop_index (we only drop the hidden shard column once we're sure there aren't any other sharded indexes referring to it).


<!-- Sent from Reviewable.io -->

2019-12-17 17:02 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwJnUN80wCTbpQIa667:b-444gvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

No, we'd decided that we wanted it to be transparent to the user.
</blockquote></details>

this is opaque though right -- users don't know (or just can't see) what using hash actually does under the hood
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwJndOz3N1qyOLSGxdD:b-tpbmnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This isn't a problem since postgres (and CRDB) allows creation of multiple identical indices. I'll add this to the logictests to make it clear. With regards to the hidden computed shard column, we reuse the same shard column if there is already an index on the same set of columns with the same bucket_count.
</blockquote></details>

i meant that its allowed, but you might run into name conflicts when you auto generate these names if you aren't careful
___
*[pkg/sql/parser/sql.y, line 5128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKMmxAMfyIotxRHau:-LwJnk1W881JtC_IduyB:b-pqov82) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/parser/sql.y#L5128)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

We didn't consider it since we wanted to borrow from the SQL Server syntax. Additionally, the current approach allows us to add more options to this feature in the future.
</blockquote></details>

makes sense
___
*[pkg/sql/sqlbase/table.go, line 237 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGO38EAeUbq3NZSawS:-LwJnqRQEyNcOyZ0nzrG:bd2bs5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/table.go#L237)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This is intentional since we want to avoid re-creating multiple shard columns that are always equivalent. See comment above and the `startExec` method in drop_index (we only drop the hidden shard column once we're sure there aren't any other sharded indexes referring to it).
</blockquote></details>

yup makes sense.


<!-- Sent from Reviewable.io -->

2019-12-17 17:09 UTC, aayushshah15 commented
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwJpAKy0NnnYOtBagSR:b-wfyo3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i meant that its allowed, but you might run into name conflicts when you auto generate these names if you aren't careful
</blockquote></details>

I think I misunderstood; could you clarify what the original concern was? I simply meant that sharded index names (for identical indexes) aren't going to conflict for the same reason *normal* index names don't. 


<!-- Sent from Reviewable.io -->

2019-12-17 17:32 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwJug2j-phuZuoLYycW:b-c1ib4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I think I misunderstood; could you clarify what the original concern was? I simply meant that sharded index names (for identical indexes) aren't going to conflict for the same reason *normal* index names don't. 
</blockquote></details>

My concern is if the following works:
```
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT = 4;
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT = 4
```
they would get the same generated name and collide right?


<!-- Sent from Reviewable.io -->

2019-12-18 20:03 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGH4Hj2PA_1fWZtSTM:-LwPI5FW4nD5pkyxPKj2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_index.go#L84)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Small nit, but I feel like this code would be cleaner if it was possible to move it into a separate function.
</blockquote></details>

Done.
___
*[pkg/sql/drop_index.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJ9CfAQKRfzii72yI:-LwPZvcDEWlBbuABE3-o:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/drop_index.go#L131)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

this allocates basically everytime you delete one of the elements -- probably better to do something like
```
tmp := tableDesc.Columns[:0]
// do the loop
if keep element {
  tmp = append(tmp, elem)
}
tableDesc.Columns = tmp
```
</blockquote></details>

done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwPI9Jo1DgtorKCEfj2:bwoi3kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

this is opaque though right -- users don't know (or just can't see) what using hash actually does under the hood
</blockquote></details>

Yeah this sort of thing has confusing interpretations, see: https://ell.stackexchange.com/questions/17693/what-is-the-correct-interpretation-of-transparent. 

I simply meant that we decided to keep the under-the-hood sharding logic hidden from the user, as discussed here: https://github.com/cockroachdb/cockroach/pull/42924/files#diff-8778ea5fd9afd71f6a0a0818d734f6a3R383.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwPJfgU-qXuaJOJIvYa:bslxzms) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

My concern is if the following works:
```
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT = 4;
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT = 4
```
they would get the same generated name and collide right?
</blockquote></details>

I should've included this in the logictests, added now. But essentially, we simply append an integer to a newly generated index name if one already exists with that name. 

Example of expected behavior: 
```

query TT
SHOW CREATE TABLE sharded_secondary
----
sharded_secondary  CREATE TABLE sharded_secondary (
                   a INT8 NULL,
                   FAMILY "primary" (a, rowid)
)

# Ensure that multiple (> 2) identical indexes can be created.
statement ok
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

statement ok 
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

statement ok
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

query TT
SHOW CREATE TABLE sharded_secondary
----
sharded_secondary  CREATE TABLE sharded_secondary (
                    a INT8 NULL,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx1 (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx2 (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    FAMILY "primary" (a, rowid, a_shard_10_internal)
)

```
___
*[pkg/sql/sem/tree/create.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKYDb5lUIXLWqY6WY:-LwJjmBr9bERfdbEeJdv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sem/tree/create.go#L217)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

rename this to IsPrimaryKey or something -- seeing this used in other places in the code was confusing
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 745 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGLb9F765-QmFUkopP:-LwP_9WX6pae_Xog_fy0:b-9c9o2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L745)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

just looping over the Families slice would be fine. also, we usually loop over the indices and index into the list for these larger structs to avoid copies
</blockquote></details>

Removed this block. See comment below.
___
*[pkg/sql/sqlbase/structured.go, line 765 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGMNY93U7NhaXteyeI:-LwPKY2E3UOTIHcntXv5:bhh58ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L765)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Why do you remove the column from a family and then add it back?
</blockquote></details>

Andrew and I discussed this offline, and I have changed the way this is done. The reason I first removed the shard column from its family was to avoid having it in the family twice (in case the family of the first column in the index set is also the "primary" family, which the `AllocateIDs` method default-assigns the shard column into). 

A lot of the complexity here stems from the fact that (1) we need the shard column to have an ID in order for `MakeCheckConstraint` to construct a valid check constraint and (2) the shard column must be assigned to its "correct" column family before `AllocateIDs()` is called, since otherwise it gets gnarly to "move" the shard column from its default column family to its expected one. 

I believe the current approach is slightly easier to reason about. The decision tree is as follows: 1) If the shard column is not new, that means it already has a family and its corresponding check constraint, so we can elide all logic pertaining to column families and check constraints in this case. 2) If we created a new shard column as a result of the current SQL statement being executed, we first force it into its correct column family, then call `AllocateIDs` and then finally create its check constraint. 
___
*[pkg/sql/sqlbase/structured.go, line 775 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGMUtP9Qz7F7j9eaS5:-LwPKVYQ7GWthc4yqgnh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.go#L775)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

should these be removed before merging?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LwP_GcU8EOAYro_BEMc:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

we do nulla [...]

2019-12-18 23:15 UTC, rohany requested changes
some more small comments, but its looking alot better. Someone else from sql should also take a look before the LGTM, because it is alot of code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LwQHi9L0rfzU3ciLuTB:b-63mvu6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/settings/cluster/cockroach_versions.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQF_WgBUSx7JWZeYrf:-LwQF_WgBUSx7JWZeYrg:b-n33vp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/settings/cluster/cockroach_versions.go#L354)):*
> ```Go
> 		Version: roachpb.Version{Major: 19, Minor: 2, Unstable: 6},
> 	},
> 	{
> ```

This should have a comment with the PR and an explanation of whats going on
___
*[pkg/sql/create_index.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQFq7ECNTSZ2q8ASpe:-LwQFq7ECNTSZ2q8ASpf:blum1dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L137)):*
> ```Go
> 
> 	if n.Sharded != nil {
> 		colNames := make([]string, 0, len(n.Columns))
> ```

you could also add all of this stuff into the function, and just call it setupShard or something. your call though, i don't mind either way
___
*[pkg/sql/create_index.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQG3_DE6C3jiNcDLcO:-LwQG3_DE6C3jiNcDLcP:b-a84no1) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L213)):*
> ```Go
> 	}
> 
> 	if n.n.Sharded != nil &&
> ```

i'd just move this check into MakeIndexDescMaybeCreateShard
___
*[pkg/sql/create_table.go, line 992 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGHsI0BiEoe3F1FdIT:-LwQGA9n1QFx1l2-M7yn:b-qcrb2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_table.go#L992)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

There is already a `findColumnByName` function you could use
</blockquote></details>

i accidentally marked this as done
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGU3m5tHUrv8Ak1s-:-LwQGU3m5tHUrv8Ak1s0:b-3q0bv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
> ```Go
> 	col.Type = *types.Int4
> 	computeExprBuilder := strings.Builder{}
> 	// TODO(aayush): Write a universal hash function that can take a set of
> ```

drop all the `TODO (aayush)` and move it to andrew werner possibly
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwQGmgj28AM-nn2z-hI:bhp1oeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yeah this sort of thing has confusing interpretations, see: https://ell.stackexchange.com/questions/17693/what-is-the-correct-interpretation-of-transparent. 

I simply meant that we decided to keep the under-the-hood sharding logic hidden from the user, as discussed here: https://github.com/cockroachdb/cockroach/pull/42924/files#diff-8778ea5fd9afd71f6a0a0818d734f6a3R383.
</blockquote></details>

sounds good then
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJtj40bhF0cDDYijl:-LwQGxHZ35YBQD-V4U7D:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L117)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I should've included this in the logictests, added now. But essentially, we simply append an integer to a newly generated index name if one already exists with that name. 

Example of expected behavior: 
```

query TT
SHOW CREATE TABLE sharded_secondary
----
sharded_secondary  CREATE TABLE sharded_secondary (
                   a INT8 NULL,
                   FAMILY "primary" (a, rowid)
)

# Ensure that multiple (> 2) identical indexes can be created.
statement ok
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

statement ok 
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

statement ok
CREATE INDEX ON sharded_secondary (a) USING HASH WITH BUCKET_COUNT=10

query TT
SHOW CREATE TABLE sharded_secondary
----
sharded_secondary  CREATE TABLE sharded_secondary (
                    a INT8 NULL,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx1 (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    INDEX sharded_secondary_a_shard_10_internal_a_idx2 (a ASC) USING HASH WITH BUCKET_COUNT=10,
                    FAMILY "primary" (a, rowid, a_shard_10_internal)
)

```
</blockquote></details>

nice
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGoOiETAQH3iy1lEN:-LwQGoOiETAQH3iy1lEO:b5o5yb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L11)):*
> ```
>                  a INT8 NOT NULL,
>                  CONSTRAINT "primary" PRIMARY KEY (a ASC) USING HASH WITH BUCKET_COUNT=10,
>                  FAMILY "primary" (a_shard_10_internal, a)
> ```

if it is hidden, then shouldn't you not show the family of the hidden column?
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LwQHchyEedduTLTFP6A:bdo2ukj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Ack.
</blockquote></details>

its still not nullable
___
*[pkg/sql/sqlbase/structured.proto, line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGNCwSBniUbLaD8uvF:-LwQHR1s-8hYeWa2gkyZ:bhmeifj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/sqlbase/structured.proto#L227)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Some points at which we create these `ShardedDescriptor` objects, we do not have access to the column IDs since they haven't been assigned yet. See `startExec` in `create_table.go` and its call to `MakeColumnDefDescs()` (where we construct these descriptors). What is the rationale for storing column IDs here instead of the names? 
</blockquote></details>

ok makes sense -- if there wasn't a reason then it just keeps the descriptors smaller


<!-- Sent from Reviewable.io -->

2019-12-18 23:15 UTC, ajwerner requested changes
I definitely need to give this more passes. Here's a brief first pass. 

> Reviewed 1 of 12 files at r3, 4 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LwQHfEE5FlLE9FVlFQ9:b-1il4i3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGH4Hj2PA_1fWZtSTM:-LwQAS4p7OdQvhnqg9p8:b8imzqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_index.go#L84)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I could see another function still. 
___
*[pkg/sql/create_index.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQAGJr0vFc43hRs7bT:-LwQAGJr0vFc43hRs7bU:b-7i0en4) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L49)):*
> ```Go
> }
> 
> func setupFamilyAndConstraintForShard(
> ```

nit: comment to explain what this does to what and when it's called. 
___
*[pkg/sql/create_table.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQC6ZV2Y8mlsjRB2QU:-LwQC6ZW0epjzfRNx_mI:b-fyx4jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L37)):*
> ```Go
> )
> 
> var invalidClusterForShardedIndex = errors.Errorf("hash sharded indexes can only be created on a cluster that has fully migrated to version 20.1")
> ```

Is there a pg error code/ pgerror we want to use here? `pgerror.Newf(pgcode.FeatureNotSupported, ...)`?
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LwQCchE8L_kvvOYDvmC:b-u8spo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
> ```Go
> 	col.Type = *types.Int4
> 	computeExprBuilder := strings.Builder{}
> 	// TODO(aayush): Write a universal hash function that can take a set of
> ```

I don't understand this comment. You already have one. You could `fnv32(c) + ...` 

I don't have super strong feelings. I think I'd slightly prefer using the function itself without the cast for data types we know we don't need to cast. Like check the types and call fnv(32) without the cast if we know we support it and then cast it to string if we don't. 

My biggest concern is that formatting timestamps to strings isn't super cheap and I suspect timestamps are going to be the primary use case here. 
___
*[pkg/sql/create_table.go, line 1519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQDBOmCdDf7nKOV2D6:-LwQDBOmCdDf7nKOV2D7:bnywv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1519)):*
> ```Go
> 	parsed, err := parser.ParseExpr(computeExprBuilder.String())
> 	if err != nil {
> 		return nil, err
> ```

This seems like an assertion failure. Can you wrap it in one: https://godoc.org/github.com/cockroachdb/errors#NewAssertionErrorWithWrappedErrf

I'm worried a little bit about quoting here. Can we try some nasty cases with columns that have spaces and weirdness in some logic tests? 
___
*[pkg/sql/create_table.go, line 1527 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQEEva12wPP9Za3Okg:-LwQEEvb86wJEyEj7cf7:b-a8r6b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1527)):*
> ```Go
> }
> 
> func generateMaybeDuplicateNameForCheckConstraint(
> ```

comment this and its counterpart
___
*[pkg/sql/drop_index.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQEyuX9Eq-BW2Ieceb:-LwQEyuX9Eq-BW2Iecec:bgz99fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/drop_index.go#L79)):*
> ```Go
> 		}
> 
> 		idxDesc, _, err := tableDesc.FindIndexByName(string(index.idxName))
> ```

Even this isn't going to save you. The returned idxDesc is a pointer into the slice. Once you modify the slice below it will point to the wrong thing. You're going to need to deep copy this if you're keeping it around. Make the decsision about the deep copy before you drop it and 
___
*[pkg/sql/drop_index.go, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQFEyt5Wf23AtlpUXs:-LwQFEyt5Wf23AtlpUXt:bbdna2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/drop_index.go#L93)):*
> ```Go
> 		// Drop the shard column if no other sharded index refers to it.
> 		if idxDesc.IsSharded() {
> 			shardColDesc, dropped, err := tableDesc.FindColumnByName(tree.Name(idxDesc.Sharded.Name))
> ```

pull all of this business out into a helper
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGJSch35Hgp4IpBGeg:-LwQFamG160Pknopvq0O:b8mn5bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L8)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yeah this sort of thing has confusing interpretations, see: https://ell.stackexchange.com/questions/17693/what-is-the-correct-interpretation-of-transparent. 

I simply meant that we decided to keep the under-the-hood sharding logic hidden from the user, as discussed here: https://github.com/cockroachdb/cockroach/pull/42924/files#diff-8778ea5fd9afd71f6a0a0818d734f6a3R383.
</blockquote></details>

I'm +1 on not exposing the hashing logic to the user for now. We may eventually decide we want to but it's easier to give than to take. 
___
*[pkg/sql/parser/sql.y, line 4814 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvHFIk19gviCTU5AXlS:-LwQFpW-6st_iBw8Q3yI:buc1833) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/parser/sql.y#L4814)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yup sounds good, on it.
</blockquote></details>

Discussed offline. 
___
*[pkg/sql/sem/tree/backup.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQG7tJ-wS8n8KpC_F-:-LwQG7tJ-wS8n8KpC_F0:b-maq2td) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sem/tree/backup.go#L81)):*
> ```Go
> }
> 
> // Format implements the NodeFormatter interface.
> ```

Is this fallout from the experiment to move to a KVOption? 
___
*[pkg/sql/sqlbase/structured.go, line 507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQ9B5N7M75vCAwZ1hT:-LwQ9B5N7M75vCAwZ1hU:b-dhry36) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sqlbase/structured.go#L507)):*
> ```Go
> }
> 
> // EvalShardBucketCount evaluates and checks the integer argument to a `USING HASH WITH
> ```

This belongs in `tree` not here. Also can this just be a method on the Shared 
___
*[pkg/sql/sqlbase/structured.go, line 1941 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGahL3oghgoKYqbCF:-LwQGahL3oghgoKYqbCG:bmhck3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sqlbase/structured.go#L1941)):*
> ```Go
> }
> 
> func (desc *TableDescriptor) validateShardedIndex(index *IndexDescriptor) error {
> ```

should there be more validation here? 
___
*[pkg/sql/sqlbase/structured.proto, line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGNCwSBniUbLaD8uvF:-LwQHnts22W7iNQYSo0l:b-uzzi [...]

2019-12-20 02:17 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGH4Hj2PA_1fWZtSTM:-LwW2ESN8anoC9rqmILi:b-c8cfku) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_index.go#L84)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I could see another function still. 
</blockquote></details>

Done. Let me know if you see an even cleaner way.
___
*[pkg/sql/create_index.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQFq7ECNTSZ2q8ASpe:-LwW2MI5-8AihIPYmQ3g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L137)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

you could also add all of this stuff into the function, and just call it setupShard or something. your call though, i don't mind either way
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1527 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQEEva12wPP9Za3Okg:-LwW2ZEd-tkF8ISnyZ9z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1527)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

comment this and its counterpart
</blockquote></details>

Done.
___
*[pkg/sql/drop_index.go, line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQEyuX9Eq-BW2Ieceb:-LwVps4D5kPv7t5y5oXT:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/drop_index.go#L79)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Even this isn't going to save you. The returned idxDesc is a pointer into the slice. Once you modify the slice below it will point to the wrong thing. You're going to need to deep copy this if you're keeping it around. Make the decsision about the deep copy before you drop it and 
</blockquote></details>

done.
___
*[pkg/sql/drop_index.go, line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQFEyt5Wf23AtlpUXs:-LwVpwOQ7AltQvy6_Dsd:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/drop_index.go#L93)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

pull all of this business out into a helper
</blockquote></details>

done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGoOiETAQH3iy1lEN:-LwQJICL8w3ktj6lyE0x:b-m3utjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L11)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

if it is hidden, then shouldn't you not show the family of the hidden column?
</blockquote></details>

We do show the family of hidden columns (I believe it is the only "visible" aspect about them), we do it for `rowid` for example.
___
*[pkg/sql/parser/sql.y, line 5132 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGKCYR-viJbeijDF_Q:-LwVr3WI8mKv3EiE2Fk5:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/parser/sql.y#L5132)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

You'd want that to just show up in the docs -- i think we just do pure syntax here.
</blockquote></details>

Ack.
___
*[pkg/sql/sem/tree/backup.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQG7tJ-wS8n8KpC_F-:-LwVr14_0hD48fEWzLgd:b-o2oku4) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sem/tree/backup.go#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this fallout from the experiment to move to a KVOption? 
</blockquote></details>

yes, removed.
___
*[pkg/sql/sem/tree/create.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhwsKg1vtLROvKucJh:-LwQKHFo08tEr82Rqj1I:b-fcf8b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe31961f053aadbde0cbf2fdadfbdcd7c8d459a/pkg/sql/sem/tree/create.go#L566)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We don't need this space?
</blockquote></details>

Is this comment rotten now? I'm confused.
___
*[pkg/sql/sqlbase/structured.go, line 507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQ9B5N7M75vCAwZ1hT:-LwVsAit5UjS5VqsMNSe:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sqlbase/structured.go#L507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This belongs in `tree` not here. Also can this just be a method on the Shared 
</blockquote></details>

done.
___
*[pkg/sql/sqlbase/structured.go, line 1941 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGahL3oghgoKYqbCF:-LwW3FH4ABhtGgHVtSYL:b5fbm62) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/sqlbase/structured.go#L1941)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should there be more validation here? 
</blockquote></details>

Renamed the method to be more specific.


<!-- Sent from Reviewable.io -->

2019-12-20 14:41 UTC, ajwerner requested changes
Here's the next pass

> Reviewed 1 of 11 files at r4, 4 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LwYkKOP9oHOXJVfq83P:baxdeq8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQG3_DE6C3jiNcDLcO:-LwYaz_X5FBo6qG-0Lpo:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L213)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i'd just move this check into MakeIndexDescMaybeCreateShard
</blockquote></details>

+1
___
*[pkg/sql/create_index.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwY_eSv2vDVVfCowkv0:-LwY_eSwEv4sdri1j9js:bsrg2ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L141)):*
> ```Go
> 	if n.Sharded != nil {
> 		if n.PartitionBy != nil {
> 			return nil, pgerror.New(pgcode.InvalidSQLStatementName, "sharded indexes don't support partitioning")
> ```

I'm not sure this code makes sense here. Maybe more of a `FeatureNotSupported`. This combined with the inability to provide prefix columns is likely the roughest edge of this project. I'll create an issue to fix it. 
___
*[pkg/sql/create_index.go, line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYaPBK2ShjXLh39ohV:-LwYaPBK2ShjXLh39ohW:b-y81og5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L165)):*
> ```Go
> 	tableDesc *sqlbase.MutableTableDescriptor,
> 	indexDesc *sqlbase.IndexDescriptor,
> ) (*sqlbase.ColumnDescriptor, bool, error) {
> ```

nit: name the return value for the bool 
___
*[pkg/sql/create_index.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYaifzCvy6Dv4IV9Xm:-LwYaifzCvy6Dv4IV9Xn:bikqul3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L193)):*
> ```Go
> 
> // maybeCreateAndAddShardCol adds a new hidden computed shard column (or its mutation)
> // to `desc`, if one doesn't already exist for the given index column set.
> ```

nit `given index column set and number of shard buckets`
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LwYerwD3kLIjBVyZtXl:b-3bww8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't understand this comment. You already have one. You could `fnv32(c) + ...` 

I don't have super strong feelings. I think I'd slightly prefer using the function itself without the cast for data types we know we don't need to cast. Like check the types and call fnv(32) without the cast if we know we support it and then cast it to string if we don't. 

My biggest concern is that formatting timestamps to strings isn't super cheap and I suspect timestamps are going to be the primary use case here. 
</blockquote></details>

I'd prefer we sum the hashes of the string casts rather than passing all of them to the hash function. 
___
*[pkg/sql/create_table.go, line 1043 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYbH_Y2e9rGcfzET9Y:-LwYbH_Y2e9rGcfzET9Z:b-azuyrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1043)):*
> ```Go
> 
> 	desc := InitTableDescriptor(id, parentID, n.Table.Table(), creationTime, privileges, temporary)
> 	generatedNames := map[string]struct{}{}
> ```

This change seems stale. 
___
*[pkg/sql/create_table.go, line 1143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYcCTK-UfScCFN592z:-LwYcCTK-UfScCFN593-:bgg7foy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1143)):*
> ```Go
> 
> 	var primaryIndexColumnSet map[string]struct{}
> 	setupShardedIndex := func(idx *sqlbase.IndexDescriptor, d *tree.IndexTableDef, idxColumns *tree.IndexElemList) error {
> ```

I'm not really clear on why you choose not to interact with `d.Columns` directly and instead take a pointer to it. I surmise that the reasoning had something to do with a desire to not modify the `IndexTableDef` directly, which is reasonable, but let's add a comment. Furthermore, given that your goal is to preserve `d` in its original form, why pass in `idxColumn`? How about instead you just return a `tree.IndexElemList` with the error?
___
*[pkg/sql/drop_index.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYfhgb4AEesITE2z0g:-LwYfhgb4AEesITE2z0h:b-wucxi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L79)):*
> ```Go
> 		}
> 
> 		tmpDesc, _, err := tableDesc.FindIndexByName(string(index.idxName))
> ```

Isn't it also the case that you only need to store this value if the index is sharded?

Also this badly needs commentary to explain why you're doing it. Furthermore I think you should just call it idxDesc and then set it to nil if it's not a sharded index and copy it to a newly allocated pointer if it is. 
___
*[pkg/sql/drop_index.go, line 166 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgUEG7K9sx6yIhV7t:-LwYgUEG7K9sx6yIhV7u:bfz1gaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L166)):*
> ```Go
> 	}
> 	shardColDesc, dropped, err := tableDesc.FindColumnByName(tree.Name(idxDesc.Sharded.Name))
> 	shouldDropShardColumn := true
> ```

nit: move this to just above the loop
___
*[pkg/sql/drop_index.go, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgG1S6AEzrWQ31fHt:-LwYgG1S6AEzrWQ31fHu:b-l7sfyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L182)):*
> ```Go
> 		}
> 	}
> 	if shouldDropShardColumn {
> ```

nit:

```
if !shouldDropShardColumn {
    return nil
}
return n.dropShardColumnAndConstraint(params, tableDesc, shardColDesc)
```
___
*[pkg/sql/sem/tree/create.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhwsKg1vtLROvKucJh:-LwYgfya76MmlsWESbAE:b-kjfjew) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe31961f053aadbde0cbf2fdadfbdcd7c8d459a/pkg/sql/sem/tree/create.go#L566)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Is this comment rotten now? I'm confused.
</blockquote></details>

I feel like we did need this space. 
___
*[pkg/sql/sem/tree/pretty.go, line 1431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgsYSBAVTw1B3Psuq:-LwYgsYSBAVTw1B3Psur:b-a9odgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sem/tree/pretty.go#L1431)):*
> ```Go
> 	//
> 	parts := []pretty.Doc{
> 		pretty.Keyword("USING HASH WITH BUCKET_COUNT="),
> ```

nit: I feel like often these are written in SQL as `BUCKET_COUNT = 8` with spaces. You haven't been doing that but it seems slightly more natural to me. 
___
*[pkg/sql/sem/tree/pretty.go, line 1759 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYh4i97NkvmPWkE0ZI:-LwYh4i97NkvmPWkE0ZJ:b-n7p1gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sem/tree/pretty.go#L1759)):*
> ```Go
> 
> 	if node.PrimaryKey.Sharded {
> 		clauses = append(clauses, pretty.Keyword("USING HASH WITH BUCKET_COUNT="))
> ```

same nit about the spaces. 
__ [...]

2019-12-20 14:43 UTC, rohany commented
Small thought I had -- have you double checked that this extra column appears in the 'extraColumnsIDs' of secondary indexes? This is important so you can reconstruct the primary key from a secondary index k/v

2019-12-26 00:34 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/settings/cluster/cockroach_versions.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQF_WgBUSx7JWZeYrf:-Lwz-1ec9Qg1FQUpA4Fw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/settings/cluster/cockroach_versions.go#L354)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This should have a comment with the PR and an explanation of whats going on
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQG3_DE6C3jiNcDLcO:-Lwz07xn7hVCOyFHXe4d:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L213)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

+1
</blockquote></details>

done.
___
*[pkg/sql/create_index.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwY_eSv2vDVVfCowkv0:-Lwz-LqR3iqbVtefqm7V:b-8eizj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not sure this code makes sense here. Maybe more of a `FeatureNotSupported`. This combined with the inability to provide prefix columns is likely the roughest edge of this project. I'll create an issue to fix it. 
</blockquote></details>

Changed it to `FeatureNotSupported` for now.
___
*[pkg/sql/create_index.go, line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYaPBK2ShjXLh39ohV:-Lwz-hSg8hT5Fup65aNo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L165)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: name the return value for the bool 
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYaifzCvy6Dv4IV9Xm:-Lwz-rvI79e3W_05shAM:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L193)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit `given index column set and number of shard buckets`
</blockquote></details>

done.
___
*[pkg/sql/create_table.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQC6ZV2Y8mlsjRB2QU:-Lwz0ORJC2hyqqbBmQq4:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is there a pg error code/ pgerror we want to use here? `pgerror.Newf(pgcode.FeatureNotSupported, ...)`?
</blockquote></details>

done.
___
*[pkg/sql/create_table.go, line 1043 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYbH_Y2e9rGcfzET9Y:-Lwz1ZqB10s3SkO5bS8o:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1043)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This change seems stale. 
</blockquote></details>

Fixed.
___
*[pkg/sql/drop_index.go, line 166 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgUEG7K9sx6yIhV7t:-Lwz44z052S5UCaa3iv3:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L166)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: move this to just above the loop
</blockquote></details>

done.
___
*[pkg/sql/drop_index.go, line 182 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgG1S6AEzrWQ31fHt:-Lwz4LdB0gBRXINpfFg1:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L182)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit:

```
if !shouldDropShardColumn {
    return nil
}
return n.dropShardColumnAndConstraint(params, tableDesc, shardColDesc)
```
</blockquote></details>

done.
___
*[pkg/sql/sem/tree/create.go, line 566 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhwsKg1vtLROvKucJh:-Lwz54Oi1GNIlntOkaSc:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe31961f053aadbde0cbf2fdadfbdcd7c8d459a/pkg/sql/sem/tree/create.go#L566)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like we did need this space. 
</blockquote></details>

done.
___
*[pkg/sql/sem/tree/pretty.go, line 1431 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYgsYSBAVTw1B3Psuq:-LwzbkM42OVyC6EzB0SP:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sem/tree/pretty.go#L1431)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: I feel like often these are written in SQL as `BUCKET_COUNT = 8` with spaces. You haven't been doing that but it seems slightly more natural to me. 
</blockquote></details>

done.
___
*[pkg/sql/sem/tree/pretty.go, line 1759 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYh4i97NkvmPWkE0ZI:-LwzbllF1iVAHxMbpdhH:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sem/tree/pretty.go#L1759)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

same nit about the spaces. 
</blockquote></details>

done.
___
*[pkg/sql/sqlbase/structured.go, line 561 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYh8Ja9u4lyyj62v3N:-LwzbmwO3lqxWhqW0a3c:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sqlbase/structured.go#L561)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

same nit about the spaces
</blockquote></details>

done.
___
*[pkg/sql/sqlbase/structured.go, line 1924 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYhLWIA13v5B5I7laF:-Lwz6EpO7QhoaaFDBnIO:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sqlbase/structured.go#L1924)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

s/ensureShardedIndexNoComputed/ensureShardedIndexNotComputed/
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2019-12-26 15:41 UTC, rohany commented
Is this ready for another review?

2019-12-26 21:44 UTC, aayushshah15 commented
nope, I was going to get back to it this weekend, will notify here!

2020-01-04 14:27 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQAGJr0vFc43hRs7bT:-LxQ_fEU0IvAtYeEDJUH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_index.go#L49)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: comment to explain what this does to what and when it's called. 
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 992 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwGHsI0BiEoe3F1FdIT:-LxQbA-f71ViSFoZD_Ex:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7954d4c6b7acb76af0444f532808bba2304c494d/pkg/sql/create_table.go#L992)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i accidentally marked this as done
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LxQEX6X5cSvYj2OlqQd:bmx6c1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd prefer we sum the hashes of the string casts rather than passing all of them to the hash function. 
</blockquote></details>

w.r.t your first comment: I didn't remove that comment initially because of Ben's RFC comment that talked about how certain hash functions are faster on modern hardware. I was wondering if it'd be feasible to have a builtin that uses the fastest hash functions we could use for a given instruction set. Not sure if it's worth looking into. We discussed the casting aspect offline & decided to stick with the current implementation.

w.r.t second comment: Done. I don't remember if we discussed this as well, but I'm just curious as to why you like this better.
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQGU3m5tHUrv8Ak1s-:-LxkmeBk82mj7xjR7I6T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

drop all the `TODO (aayush)` and move it to andrew werner possibly
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQDBOmCdDf7nKOV2D6:-LxkKRyYDXHMdHBPfkZK:bar4lhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1519)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This seems like an assertion failure. Can you wrap it in one: https://godoc.org/github.com/cockroachdb/errors#NewAssertionErrorWithWrappedErrf

I'm worried a little bit about quoting here. Can we try some nasty cases with columns that have spaces and weirdness in some logic tests? 
</blockquote></details>

Made it an assertion failure. I'm a little confused about the second part of your comment, are you talking about testing `STRING` type columns that contain weird strings in them?
___
*[pkg/sql/create_table.go, line 1143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYcCTK-UfScCFN592z:-LxQ7ErP6l5utUldxrZD:b-kxg3d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1143)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not really clear on why you choose not to interact with `d.Columns` directly and instead take a pointer to it. I surmise that the reasoning had something to do with a desire to not modify the `IndexTableDef` directly, which is reasonable, but let's add a comment. Furthermore, given that your goal is to preserve `d` in its original form, why pass in `idxColumn`? How about instead you just return a `tree.IndexElemList` with the error?
</blockquote></details>

Now that you mention it, I don't really see why we shouldn't just modify `d.Columns`; it seems cleaner. I believe this approach was just a vestige of one of my early implementations. These `IndexTableDefs` aren't being touched after this loop but, in any case, it seems safer to have `d.Columns` contain the shard column if it was added. Fixed. 
___
*[pkg/sql/drop_index.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYfhgb4AEesITE2z0g:-LxkjfPy45R4bhYj5VCj:bbwi3xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/drop_index.go#L79)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Isn't it also the case that you only need to store this value if the index is sharded?

Also this badly needs commentary to explain why you're doing it. Furthermore I think you should just call it idxDesc and then set it to nil if it's not a sharded index and copy it to a newly allocated pointer if it is. 
</blockquote></details>

I realized that we didn't need to keep the index descriptor around anymore (because we only iterate through non-drop indexes in the `maybeDropShardColumn` method below, so we're not going to see this descriptor again), only the name of the shard column. Cleaner now. 
___
*[pkg/sql/sqlbase/structured.proto, line 418 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvhyxHN458b_1ARpmck:-LxQOuwo96jEPWr_jIvO:b346v8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b7a23f240ea603091c84ac807684ddd81135af4/pkg/sql/sqlbase/structured.proto#L418)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

its still not nullable
</blockquote></details>

My bad I didn't realize you wanted it changed back. Added a flag to the proto since there doesn't seem to be a generated `IsSet` method. 
___
*[pkg/sql/sqlbase/table.go, line 192 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYhhnx0EP4Mf2Yp9h7:-LxQZjubD4LC9W7iMJ6m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/sqlbase/table.go#L192)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

something smells here. This got way more complicated with no commentary. I find the below version easier to read:

```
if !d.PrimaryKey.Sharded {
   idx = &IndexDescriptor{
	Unique:           true,
	ColumnNames:      []string{string(d.Name)},
	ColumnDirections: []IndexDescriptor_Direction{IndexDescriptor_ASC},
    }
} else {
    buckets, err := tree.EvalShardBucketCount(d.PrimaryKey.ShardBuckets)
    if err != nil {
        return nil, nil, nil, err
    }
    shardColName := GetShardColumnName(colNames, buckets)
    idx = &IndexDescriptor{
        Unique:           true,
        ColumnNames:      []string{shardColName, d.Name},
        ColumnDirections: []IndexDescriptor_Direction{IndexDescriptor_ASC, IndexDescriptor_ASC}
        Sharded: &ShardedDescriptor{
            Name: shardColName,
            ShardBuckets: buckets,
            ColumnNames: []string{d.Name},
        },
    }
}

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-04 14:38 UTC, aayushshah15 reviewed
I'll try my best to add unit tests that verify table descriptor states tonight. I believe this is ready for a look otherwise.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lxkx69c2yFBTRRPpWu5:bv6fn4g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-01-04 14:46 UTC, aayushshah15 commented
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-Lxl-Log5M9YGqrQf8PT:bpj1le0) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

w.r.t your first comment: I didn't remove that comment initially because of Ben's RFC comment that talked about how certain hash functions are faster on modern hardware. I was wondering if it'd be feasible to have a builtin that uses the fastest hash functions we could use for a given instruction set. Not sure if it's worth looking into. We discussed the casting aspect offline & decided to stick with the current implementation.

w.r.t second comment: Done. I don't remember if we discussed this as well, but I'm just curious as to why you like this better.
</blockquote></details>

One thing to note here is that if we wave our hands and say "`fnv32` produces a uniform distribution of values when its domain is sequential", our result isn't a uniform distribution anymore since the sum of multiple uniform distributions is an Irwin-Hall distribution. https://en.wikipedia.org/wiki/Irwin%E2%80%93Hall_distribution. 


<!-- Sent from Reviewable.io -->

2020-01-04 16:40 UTC, RaduBerinde commented
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LxlPf7w1wBwVNB57XYB:bp2bz4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

One thing to note here is that if we wave our hands and say "`fnv32` produces a uniform distribution of values when its domain is sequential", our result isn't a uniform distribution anymore since the sum of multiple uniform distributions is an Irwin-Hall distribution. https://en.wikipedia.org/wiki/Irwin%E2%80%93Hall_distribution. 
</blockquote></details>

Sum is also bad because it's commutative, eg (1,2) always hashes the same with (2,1). I would probably fnv32 the concatenation of the hashes for the columns.


<!-- Sent from Reviewable.io -->

2020-01-04 17:14 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @RaduBerinde, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LxlXtNm3gcc_AGBw0Bg:b2nhoia) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sum is also bad because it's commutative, eg (1,2) always hashes the same with (2,1). I would probably fnv32 the concatenation of the hashes for the columns.
</blockquote></details>

TIL


<!-- Sent from Reviewable.io -->

2020-01-04 17:26 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @RaduBerinde, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-LxlYERR7MsE0G32LnXa:bs7l7dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

TIL
</blockquote></details>

About the Irwin-Hall distribution, though I don’t think that exactly applies. The fact that we’re taking the sum over mod of a smaller range I think changes the argument substantially. I think even if you take mod over the range of the uniform random values it will lead to a distribution that is not like the Irwin-Hall at all. Irwin-hall seems to apply when you say take the sum of numbers pulled from N trials of a process that’s uniform over [0, 1). I feel pretty confident that the output of our distribution is not going to appear to behave like a normal distribution. 

It’d be a fun curiosity to see if we can show that it’s not a uniform distribution, at least with uncorrelated inputs. 

Also the commutativity argument makes sense as being problematic, at least in contrived cases where say all columns are permutations of the same set of values. 


<!-- Sent from Reviewable.io -->

2020-01-04 18:41 UTC, RaduBerinde commented
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-Lxlr1bC02rBoT2lLktU:bugbs17) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

About the Irwin-Hall distribution, though I don’t think that exactly applies. The fact that we’re taking the sum over mod of a smaller range I think changes the argument substantially. I think even if you take node over the range of the uniform random values it will lead to a distribution that is not like the Irwin-Hall at all. Irwin-hall seems to apply when you say take the sum of numbers pulled from N trials of a process that’s uniform over [0, 1). I feel pretty confident that the output of our distribution is not going to appear to behave like a normal distribution. 

It’d be a fun curiosity to see if we can show that it’s not a uniform distribution, at least with uncorrelated inputs. 

Also the commutativity argument makes sense as being problematic, at least in contrived cases where say all columns are permutations of the same set of values. 
</blockquote></details>

I would XOR rather than sum but it has the same commutativity problem.


<!-- Sent from Reviewable.io -->

2020-01-04 18:48 UTC, RaduBerinde commented
___
*[pkg/sql/create_table.go, line 1507 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQCchE8L_kvvOYDvmB:-Lxls85Q1onkFSySwoms:b-gcfmac) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would XOR rather than sum but it has the same commutativity problem.
</blockquote></details>

I think you're right though that the sum would be uniformly distributed. If we sun k values between 0 and M-1 modulo M, for each result value there are M^(K-1) combinations of inpit values that sum to that.


<!-- Sent from Reviewable.io -->

2020-01-06 16:46 UTC, rohany reviewed
a couple nits

> Reviewed 2 of 14 files at r6, 1 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lxvjw22EqsRUFXbD6L5:b-owkuoa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1507 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvhniK07aSDckFdzgz:-LxvhniK07aSDckFdzh-:b-pkcvic) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/create_table.go#L1507)):*
> ```Go
> // based on all the `colNames`.
> func makeShardColumnDesc(
> 	colNames []string, buckets int, primaryKey bool,
> ```

It doesn't seem like this primaryKey argument is used anymore?
___
*[pkg/sql/drop_index.go, line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxviahQ7n2_rYrzSBoB:-LxviahQ7n2_rYrzSBoC:becb498) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L108)):*
> ```Go
> // dropShardColumnAndConstraint drops the given shard column and its associated check
> // constraint.
> func (n *dropIndexNode) dropShardColumnAndConstraint(
> ```

why does this function not use maybeDropShardColumn?
___
*[pkg/sql/drop_index.go, line 160 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxviZJR5Edg2Hyq7i4y:-LxviZJR5Edg2Hyq7i4z:bpw2m08) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L160)):*
> ```Go
> }
> 
> // maybeDropShardColumn drops the shard column that `idxDesc` is based on, if there aren't
> ```

i think this comment is out of date
___
*[pkg/sql/drop_index.go, line 218 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lxvir-a2AY6YqKcLJ13:-Lxvir-bE23oYy6og9ds:b-h6dpba) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L218)):*
> ```Go
> 	jobDesc string,
> ) error {
> 	fmt.Printf(`drop index triggered`)
> ```

remove these prints
___
*[pkg/sql/drop_index.go, line 231 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvisTrBMIuqdQuHxKJ:-LxvisTrBMIuqdQuHxKK:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L231)):*
> ```Go
> 	}
> 	if dropped {
> 		fmt.Printf(`somehow already dropped`)
> ```

ditto
___
*[pkg/sql/sqlbase/structured.proto, line 655 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvjR365krS6eyyGOSr:-LxvjR365krS6eyyGOSs:b24sfjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/sqlbase/structured.proto#L655)):*
> ```protobuf
>     // Whether the check constraint should show up in the result of a `SHOW CREATE
>     // TABLE..` statement.
>     optional bool hidden = 7 [(gogoproto.nullable) = false];
> ```

[nit] I'd rename this to visible perhaps? Your call though.
___
*[pkg/sql/sqlbase/table.go, line 231 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvjoB74B8letRZusZp:-LxvjoB74B8letRZusZq:bpvoz3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/sqlbase/table.go#L231)):*
> ```Go
> 	sort.Strings(colNames)
> 	return strings.Join(
> 		append(append([]string{`crdb_internal`}, colNames...), fmt.Sprintf(`shard_%v`, buckets)), `_`,
> ```

[nit] I'd put another _ after the `crdb_internal`


<!-- Sent from Reviewable.io -->

2020-01-10 18:15 UTC, rohany commented
Whats the status on this? Should one of me or @ajwerner take this over? I'd like to see it get in.

2020-01-13 14:02 UTC, aayushshah15 reviewed
Addressed the latest set of comments. If this is time sensitive, feel free to take over. My schedule's been a little been a little tight since school began. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-LyTvnTg3N2-J_xg0igF:b-svp7gh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1507 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvhniK07aSDckFdzgz:-LyUAToKDOZIaoafqVkE:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/create_table.go#L1507)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

It doesn't seem like this primaryKey argument is used anymore?
</blockquote></details>

Removed
___
*[pkg/sql/drop_index.go, line 108 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxviahQ7n2_rYrzSBoB:-LyUAkTE3GqIkyKUdpzu:b-cm7eyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L108)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

why does this function not use maybeDropShardColumn?
</blockquote></details>

`maybeDropShardColumn` uses this function to delete the column and its constraint after it ensures that there aren't any other indexes referring to that shard column.
___
*[pkg/sql/drop_index.go, line 160 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxviZJR5Edg2Hyq7i4y:-LyUB3P71r4xVOal99q4:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L160)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i think this comment is out of date
</blockquote></details>

Fixed.
___
*[pkg/sql/drop_index.go, line 218 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lxvir-a2AY6YqKcLJ13:-LyU1RwcEPt06NP8D7A5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L218)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

remove these prints
</blockquote></details>

Done
___
*[pkg/sql/drop_index.go, line 231 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvisTrBMIuqdQuHxKJ:-LyU1Sc_ABXjXiOXnBWq:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/drop_index.go#L231)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[pkg/sql/sqlbase/structured.proto, line 655 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvjR365krS6eyyGOSr:-LyU95Ld2EC-DYT1r9ud:b-9tzb73) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/sqlbase/structured.proto#L655)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit] I'd rename this to visible perhaps? Your call though.
</blockquote></details>

`hidden` seems better to me since it's consistent with what we do in `ColumnDescriptor`. 
___
*[pkg/sql/sqlbase/table.go, line 231 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LxvjoB74B8letRZusZp:-LyUAS2a6pmzyREOR1xn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/843b4849c8da3ce970c5e1c14beddcd633f6756b/pkg/sql/sqlbase/table.go#L231)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit] I'd put another _ after the `crdb_internal`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-01-13 14:16 UTC, ajwerner commented
> If this is time sensitive, feel free to take over. My schedule's been a little been a little tight since school began.

It’s not super time sensitive at this point in the release cycle. That being said, if at any point in the next few weeks you feel at all overwhelmed by this work or that you don’t think you’ll get through it just let us know and we’ll coordinate getting it over the finish line. Thanks for staying engaged with this!

2020-01-13 14:20 UTC, aayushshah15 commented
Sounds good @ajwerner 





<!-- Sent from Reviewable.io -->

2020-01-13 19:07 UTC, rohany reviewed
I think this is looking pretty good now. There's still some duplication that I'd like to get rid of, but it seems the way that create table is set up makes it hard to do that. 

Before merging, this should be behind a feature flag -- look at `pkg/sql/vars.go`. 
Also, as part of this PR or a future PR, we should add this to SQLSmith. I don't think it would be hard. Look at `pkg/internal/sqlsmith/alter.go:makeCreateIndex`. With some probability we could make the created index have a sharded component.

2020-01-20 07:19 UTC, aayushshah15 reviewed
Added some unit tests for version gating and for verifying state of the table descriptor after creation of a sharded index.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lz-kYmrCwDd4cARGUmm:b1muhng)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCUL9W-Ocbzt4993qD-r8-110:-Lz0oMMUB00FrNZiwsSp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa21f1fc97f4c598a22e7750232341b92f0da7b0/pkg/sql/create_index.go#L110)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

After reading this again, I think this should still be called MakeIndexDescriptor -- it does alot of other stuff not related to shards, which are just a part of the CreateIndexNode passed in.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-21 17:18 UTC, rohany commented on pkg/sql/tests/hash_sharded_test.go
> +func TestHashShardedIndexVersionGating(t *testing.T) {
I'm not sure we need this test case -- I have a PR landing soon (https://github.com/cockroachdb/cockroach/pull/43332) that adds a mixed 19.2-20.1 cluster setting to the logic tests, so we could just add a test that ensures you can't create a hash sharded index in that state.

2020-01-21 17:18 UTC, rohany commented
overall, this LGTM. @ajwerner want to take another look?

2020-01-21 18:42 UTC, ajwerner reviewed
Yeah, I'm going to rebase this branch and then take another pass. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lz8PJg_Asc1EAg1kCug:b3qua1h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-01-21 21:53 UTC, ajwerner requested changes
This is getting very close. Some nits. I have a sinking feeling that the code in the sql package could be a touch tighter and better commented. I think there's some  lingering bugs related to quoting in the computed column both for the constraint and the column name. 

Another question I have is whether we want to gate this entire feature on a cluster setting. @rohany how do you feel about a bool cluster setting to gate this thing until we get a bit more testing?

Again, do let us know if you don't think you're going to be able to work on this. 

> Reviewed 1 of 5 files at r8, 21 of 21 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lz91zIa5lNanSXnh0eg:b-x9ko5r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwY_eSv2vDVVfCowkv0:-Lz94zZQ6CGjaYgkO-HV:b8bgzke) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L141)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Changed it to `FeatureNotSupported` for now.
</blockquote></details>

Leaving this open as an action item for me. 
___
*[pkg/sql/create_index.go, line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCUL9W-Ocbzt4993qD-r8-110:-Lz8vEoD7nVO3tKXa59_:brcfy7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa21f1fc97f4c598a22e7750232341b92f0da7b0/pkg/sql/create_index.go#L110)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think I'd like this comment to note that the tableDesc will be modified
___
*[pkg/sql/create_index.go, line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8ulpwC3Lnp8eupNHH:-Lz8ulpwC3Lnp8eupNHI:b-qiote0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L63)):*
> ```Go
> 	family := sqlbase.GetColumnFamilyForShard(tableDesc, idxColumns)
> 	if family == "" {
> 		return errors.Errorf("could not find column family for the first column in the index column set")
> ```

Does this need to be a more specific type of error? Is this an assertion failure?
___
*[pkg/sql/create_index.go, line 217 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz93sE17xm12Ynf4aAv:-Lz93sE17xm12Ynf4aAw:bdf721d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L217)):*
> ```Go
> 		return nil, false, err
> 	}
> 	_, dropped, err := desc.FindColumnByName(tree.Name(shardCol.Name))
> ```

this logic made me a little uneasy for a few reasons. It both was playing fast and loose with assumptions about the returned error and it was assuming that shardCol and the existing shard are the same. My sense is either we should return an error if the made shard column is not exactly the same as the found shard column or it should return the old one. I'm not sure which I prefer. For now I had it return the existing shardCol but I also added a TODO that I wouldn't mind addressing in this review.
___
*[pkg/sql/create_index.go, line 226 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8vucZ9dW4m6sqDbYE:-Lz8vucZ9dW4m6sqDbYF:b92de2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L226)):*
> ```Go
> 			desc.AddColumnMutation(shardCol, sqlbase.DescriptorMutation_ADD)
> 		}
> 		return shardCol, true, nil
> ```

nit: set `created` to true here and then have just one `return shardCol, created, nil`

edit: I did it
___
*[pkg/sql/create_table.go, line 1519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQDBOmCdDf7nKOV2D6:-Lz8z-QR9_NE-mpoLQlY:b83251l) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1519)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Made it an assertion failure. I'm a little confused about the second part of your comment, are you talking about testing `STRING` type columns that contain weird strings in them?
</blockquote></details>

no, not about the contents of the columns but rather the names of the columns. Imagine the following:

```
root@127.46.118.87:45895/movr> CREATE TABLE foo ("I have spaces in a column name" int);
CREATE TABLE

Time: 3.114845ms

root@127.46.118.87:45895/movr> SELECT "I have spaces in a column name" FROM foo;
  I have spaces in a column name
----------------------------------
(0 rows)

Time: 2.720141ms
```
___
*[pkg/sql/create_table.go, line 1143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYcCTK-UfScCFN592z:-Lz8xqzq5XqdJ77TOLK6:b-j6trpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1143)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Now that you mention it, I don't really see why we shouldn't just modify `d.Columns`; it seems cleaner. I believe this approach was just a vestige of one of my early implementations. These `IndexTableDefs` aren't being touched after this loop but, in any case, it seems safer to have `d.Columns` contain the shard column if it was added. Fixed. 
</blockquote></details>

this closure feels pretty similar to `setupShardedIndexMaybeCreateShard`. There are some differences but the duplication of the core of it is a little frustrating. Can we pull the meat of it into a shared function? Furthermore, this closure is really just closing over ctx and st. I'm not sure that warrants the closure. 
___
*[pkg/sql/create_table.go, line 1147 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8wcBK5nfqXXAaMpAo:-Lz8wcBK5nfqXXAaMpAp:bc8e0xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_table.go#L1147)):*
> ```Go
> 				}
> 			}
> 			if d.PrimaryKey.Sharded {
> ```

Does this need to check for partitioning like we did in `MakeIndexDesc`?
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz90NoaAkE1dAeOqrZC:-Lz90NoaAkE1dAeOqrZD:bu2m98t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L1)):*
> ```
> # Tests for creating a hash sharded primary key
> ```

Testing with weird quoting on column names seems important. 
___
*[pkg/sql/sqlbase/table.go, line 231 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz91aquEIu1Oy2VRpBs:-Lz91aquEIu1Oy2VRpBt:blunfan) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/sqlbase/table.go#L231)):*
> ```Go
> 	sort.Strings(colNames)
> 	return strings.Join(
> 		append(append([]string{`crdb_internal_`}, colNames...), fmt.Sprintf(`shard_%v`, buckets)), `_`,
> ```

The `crdb_internal__` prefix feels unnecessary.  Can we change `crdb_internal_` here to `crdb_internal`?
___
*[pkg/sql/tests/hash_sharded_test.go, line 160 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz-j9Hnci4qTYauif12-r9-160:-Lz91mqN9nN_bLl04iHQ:b9x78uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/05177433197d629fbd649527d4ba1b604a22acd0/pkg/sql/tests/hash_sharded_test.go#L160)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I'm not sure we need this test case -- I have a PR landing soon (https://github.com/cockroachdb/cockroach/pull/43332) that adds a mixed 19.2-20.1 cluster setting to the logic tests, so we could just add a test that ensures you [...]

2020-01-21 22:02 UTC, rohany reviewed
re the cluster setting yeap, thats what I had in mind (prefixed with `experimental`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-Lz96kSjDAzWacjCWNnZ:b-tyr1wb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/sqlbase/table.go, line 231 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz91aquEIu1Oy2VRpBs:-Lz978ffEgoP5FmKTZMT:b-4yw1t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/sqlbase/table.go#L231)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The `crdb_internal__` prefix feels unnecessary.  Can we change `crdb_internal_` here to `crdb_internal`?
</blockquote></details>

I was the one who requested the extra `_`, but i don't mind either way.


<!-- Sent from Reviewable.io -->

2020-01-23 03:04 UTC, aayushshah15 commented
___
*[pkg/sql/create_index.go, line 217 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz93sE17xm12Ynf4aAv:-LzFGJFc5X4DIhz8AWTY:b-ftx4z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L217)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this logic made me a little uneasy for a few reasons. It both was playing fast and loose with assumptions about the returned error and it was assuming that shardCol and the existing shard are the same. My sense is either we should return an error if the made shard column is not exactly the same as the found shard column or it should return the old one. I'm not sure which I prefer. For now I had it return the existing shardCol but I also added a TODO that I wouldn't mind addressing in this review.
</blockquote></details>

If we stick with the current version of the `ComputeExpr` (where we're summing the hashes of individual columns), the commutative nature of the expression makes it such that the `Name` of a shard column uniquely identifies it. If we end up switching back to the old `ComputeExpr` (where we do `fnv(columnSet..)`)  then we end up in a situation where `existingShardCol` could differ from the new `shardCol`. Is this your concern? `existingShardCol` would also differ from `shardCol` if we end up changing the way we compute the shard columns down the line in a subsequent release.


<!-- Sent from Reviewable.io -->

2020-01-23 20:21 UTC, rohany commented
Before this merges, can you also add a check in `alter_table.go` that disallows primary key changes from tables that have a hash shared primary key?

2020-01-23 22:33 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_index.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwY_eSv2vDVVfCowkv0:-LzF7NJXBG0O12lA-KRP:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_index.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Leaving this open as an action item for me. 
</blockquote></details>

:+1: 
___
*[pkg/sql/create_index.go, line 110 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LvCUL9W-Ocbzt4993qD-r8-110:-LzF7M1T8rE2Ghrt4l43:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa21f1fc97f4c598a22e7750232341b92f0da7b0/pkg/sql/create_index.go#L110)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think I'd like this comment to note that the tableDesc will be modified
</blockquote></details>

Done.
___
*[pkg/sql/create_index.go, line 63 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8ulpwC3Lnp8eupNHH:-LzF6hzf73CfAk12MgXh:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L63)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this need to be a more specific type of error? Is this an assertion failure?
</blockquote></details>

Fixed.
___
*[pkg/sql/create_index.go, line 226 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8vucZ9dW4m6sqDbYE:-LzFInBz6zyjLtvqL0lY:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L226)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: set `created` to true here and then have just one `return shardCol, created, nil`

edit: I did it
</blockquote></details>

:+1: 
___
*[pkg/sql/create_table.go, line 1519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQDBOmCdDf7nKOV2D6:-Lz9BucK7S5zw9RBPN2q:b-x1g5tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1519)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

no, not about the contents of the columns but rather the names of the columns. Imagine the following:

```
root@127.46.118.87:45895/movr> CREATE TABLE foo ("I have spaces in a column name" int);
CREATE TABLE

Time: 3.114845ms

root@127.46.118.87:45895/movr> SELECT "I have spaces in a column name" FROM foo;
  I have spaces in a column name
----------------------------------
(0 rows)

Time: 2.720141ms
```
</blockquote></details>

wow TIL.
___
*[pkg/sql/create_table.go, line 1143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYcCTK-UfScCFN592z:-LzJ9ptsC5r-9ESURjrj:b-qk1o4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1143)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this closure feels pretty similar to `setupShardedIndexMaybeCreateShard`. There are some differences but the duplication of the core of it is a little frustrating. Can we pull the meat of it into a shared function? Furthermore, this closure is really just closing over ctx and st. I'm not sure that warrants the closure. 
</blockquote></details>

Thanks, I lifted the common stuff into a shared function and it's definitely much cleaner now. There is still some duplication (in case the sharded primary key is a `ColumnTableDef`) but the way `MakeTableDesc` is currently structured makes it a bit hard to improve. Let me know if you'd like something done differently.
___
*[pkg/sql/create_table.go, line 1147 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz8wcBK5nfqXXAaMpAo:-LzJAkVz2sqB70T16e-B:b-mu7tks) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_table.go#L1147)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Does this need to check for partitioning like we did in `MakeIndexDesc`?
</blockquote></details>

Yes, sorry for the oversight.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz90NoaAkE1dAeOqrZC:-LzJTfAvD523i1zXwbsX:b-bvrfys) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Testing with weird quoting on column names seems important. 
</blockquote></details>

I added some logic tests around this, however they are currently failing for reasons I haven't looked into yet. I'll try to understand what's happening and get them deflaked soon.
___
*[pkg/sql/sqlbase/table.go, line 231 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz91aquEIu1Oy2VRpBs:-LzFPQpO-e81sGYpbD-D:bp3aow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/sqlbase/table.go#L231)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I was the one who requested the extra `_`, but i don't mind either way.
</blockquote></details>

Reverted.
___
*[pkg/sql/tests/hash_sharded_test.go, line 160 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz-j9Hnci4qTYauif12-r9-160:-LzFN0Ai9F0EOSESIr1v:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/05177433197d629fbd649527d4ba1b604a22acd0/pkg/sql/tests/hash_sharded_test.go#L160)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:raised_hands: - version tests as unit tests end up rotting as we move on to the next version. I prefer the above PR plus perhaps a version upgrade acceptance test. 
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2020-02-03 13:11 UTC, aayushshah15 reviewed
> Before this merges, can you also add a check in alter_table.go that disallows primary key changes from tables that have a hash shared primary key?
 
Done.

This is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-M-A5jvF-G6B7nUSoNcI:b-8wo8a1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 1 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz90NoaAkE1dAeOqrZC:-M-A5ra75V0FFbSAwhaJ:bvl4ltj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L1)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I added some logic tests around this, however they are currently failing for reasons I haven't looked into yet. I'll try to understand what's happening and get them deflaked soon.
</blockquote></details>

The tests were flaky because the logictest package adds random column family definitions if a `CREATE TABLE` statement doesn't contain any. See: https://github.com/cockroachdb/cockroach/pull/41013 for details. Fixed now.


<!-- Sent from Reviewable.io -->

2020-02-03 19:52 UTC, ajwerner reviewed
nit: get rid of the indentation on the release note. 

I think we can spruce up the release note in general. 

This is super close. Thanks for all your hard work! I'd love to get this merged this week. Again let us know if you anticipate having any trouble working on this. 

> Reviewed 1 of 11 files at r5, 27 of 27 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-M-BaLH88qywG8gTBzpO:b-xf98ij)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/settings/cluster/cockroach_versions.go, line 409 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BX8ssC7MwaAEDF9jH:-M-BX8stElK0ZspXv5ZR:b-80yd1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/settings/cluster/cockroach_versions.go#L409)):*
> ```Go
> 		// ranges with said shard column.
> 		Key:     VersionHashShardedIndexes,
> 		Version: roachpb.Version{Major: 19, Minor: 2, Unstable: 11},
> ```

This needs an update
___
*[pkg/settings/cluster/versionkey_string.go, line 0 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BXDLp1U7ItpJJpraf:-M-BXDLp1U7ItpJJprag:b-pm085k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/settings/cluster/versionkey_string.go#L0)):*
This needs to be regenerated after the fix. 
___
*[pkg/sql/create_index.go, line 217 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz93sE17xm12Ynf4aAv:-M-BXkBSE673wmh63HJB:bn1b0xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/create_index.go#L217)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

If we stick with the current version of the `ComputeExpr` (where we're summing the hashes of individual columns), the commutative nature of the expression makes it such that the `Name` of a shard column uniquely identifies it. If we end up switching back to the old `ComputeExpr` (where we do `fnv(columnSet..)`)  then we end up in a situation where `existingShardCol` could differ from the new `shardCol`. Is this your concern? `existingShardCol` would also differ from `shardCol` if we end up changing the way we compute the shard columns down the line in a subsequent release.
</blockquote></details>

I mostly just didn't like the idea that this code was going to make assumptions about the only reason `FindColumnByName` might return an error. 

In most cases I agree with you that it's fine if the column used a different expression than maybe we might now create. I just want to call out the possibility to a reader. 
___
*[pkg/sql/create_table.go, line 1519 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwQDBOmCdDf7nKOV2D6:-M-BYmkfE2zy78GfqOqy:bwx5xyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a17f2b5a5551227f2df27c14b5f173d725c8bf/pkg/sql/create_table.go#L1519)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

wow TIL.
</blockquote></details>

I still worry there are cases where this doesn't work. What does this expression actually look like for these weird cases? Try a case with a capital letter in the middle of the word. Maybe we store the string with the `"`s in the colNames, I don't know, but given I had the question can you find out and call out in an `NB` at the point of formatting above?
___
*[pkg/sql/create_table.go, line 1143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-LwYcCTK-UfScCFN592z:-M-BabZY14KQtI7cm7Fo:b-pm83x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8f2a738187eddfec06a043c0300037d63e090d7/pkg/sql/create_table.go#L1143)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Thanks, I lifted the common stuff into a shared function and it's definitely much cleaner now. There is still some duplication (in case the sharded primary key is a `ColumnTableDef`) but the way `MakeTableDesc` is currently structured makes it a bit hard to improve. Let me know if you'd like something done differently.
</blockquote></details>

lgtm, thanks. 
___
*[pkg/sql/create_table.go, line 1286 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BYY4gB_b_1kKn7fua:-M-BYY4gB_b_1kKn7fub:bah3ciu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/create_table.go#L1286)):*
> ```Go
> 		}
> 		if newColumn {
> 			buckets, _ := tree.EvalShardBucketCount(d.Sharded.ShardBuckets)
> ```

Why are you ignoring this error? If it's due to some assumption that this has already passed, please add a comment. 
___
*[pkg/sql/drop_index.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BYxM57nyVidyR5601:-M-BYxM57nyVidyR5602:b-l9495n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/drop_index.go#L336)):*
> ```Go
> 		}
> 		// The index being deleted could be used as the origin index for this foreign key.
> 		if idx.IsValidOriginIndex(fk.OriginColumnIDs) {
> ```

why not `&&` and lose a layer of indentation?
___
*[pkg/sql/drop_index.go, line 362 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BZ5DE73TeQlKqDztU:-M-BZ5DE73TeQlKqDztV:b-xkchcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/drop_index.go#L362)):*
> ```Go
> 			// If we haven't found a replacement candidate for this foreign key, then
> 			// we need a cascade to delete this index.
> 			if !indexHasReplacementCandidate(canReplace) {
> ```

nit: please use `&&` on the conditions rather than the nested `if`. 
___
*[pkg/sql/vars.go, line 871 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BZOXh7jM7DM7N0Xhf:-M-BZOXh7jM7DM7N0Xhg:b-8lo1sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/vars.go#L871)):*
> ```Go
> 	},
> 
> 	// CockroachDB extension.
> ```

@rohany does it make sense to have this as a session variable or a cluster setting? I was thinking cluster setting. 
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 463 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BZkVS6kK5NcfeEF5v:-M-BZkVS6kK5NcfeEF5w:by6fkfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L463)):*
> ```
>                 INDEX foo ("'quotes' in the column's name" ASC) USING HASH WITH BUCKET_COUNT = 4,
>                 FAMILY "primary" ("I am a column with spaces", "'quotes' in the column's name", "crdb_internal_I am a column with spaces_shard_12", "crdb_internal_'quotes' in the column's name_shard_4")
> )
> ```

nit: newline
___
*[pkg/sql/sqlbase/table.go, line 231 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-Lz91aquEIu1Oy2VRpBs:-M-BZvhX-E9pawG2fRee:brs41zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1850a13f899ba089a168a75efc0999741e6c0d/pkg/sql/sqlbase/table.go#L231)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Reverted.
</blockquote></details>

Whoops. Sorry for the back and forth. I prefer it this way. 


<!-- Sent from Reviewable.io -->

2020-02-03 19:56 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/vars.go, line 871 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BZOXh7jM7DM7N0Xhf:-M-BbnTZCfAL1_XwFb8_:b-5vqto7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/vars.go#L871)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

@rohany does it make sense to have this as a session variable or a cluster setting? I was thinking cluster setting. 
</blockquote></details>

I think it's best to add it as both right now, with the session variable having default value equal to the cluster setting. Thats what we've been doing elsewhere for similar things.


<!-- Sent from Reviewable.io -->

2020-02-10 15:16 UTC, ajwerner reviewed
Alright I'm going to take a stab at updating this to get it merged. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-M-jeyaX1j4Vrbys4MdH:btgro49)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-10 22:37 UTC, ajwerner reviewed
@rohany is this missing anything?

> Reviewed 1 of 20 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-M-lEzW82wmLOq1PDgbV:bmkqvqr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-10 23:01 UTC, rohany commented
I think its all good

2020-02-11 01:49 UTC, ajwerner reviewed
Alright, I reworked the expression creation to build expressions using the AST instead of building a string and then parsing it. This was done out of an abundance of fear of an eventual sql injection attack and also to assuage any fears of quoting mistakes.

Once it builds I think I'm going to bors it. I played with it manually, it works and it's cool!

Thanks again @aayushshah15 for all of your hard work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-:-M-lvREyCeTj9lPCoTh_:b-eemsus)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-11 04:19 UTC, aayushshah15 commented
thanks for all your help @rohany and @ajwerner, glad to see it go in.

2020-02-11 14:32 UTC, ajwerner commented
bors r=rohany,aayushshah

2020-02-11 15:12 UTC, merged

2020-02-27 21:43 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1205 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M17aQl49xbFdUQkXoXj:-M17aQl5BvGPKZiZA6z6:b-a4ebfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a14a3bd8d1954fc20e6805bb996450cc7d30157/pkg/sql/create_table.go#L1205)):*
> ```Go
> 			}
> 			if d.PrimaryKey.Sharded {
> 				if !cluster.Version.IsActive(ctx, st, cluster.VersionHashShardedIndexes) {
> ```

`st` can be nil here. `cluster.Version` can also be uninitialized (see comment above the `if st != nil` block above).

I'm not familiar enough with this area to figure what should be done here if `st == nil` or if `active cluster version == cluster.ClusterVersion{}`. Any ideas? @rohany perhaps? Ran into this when rebasing https://github.com/cockroachdb/cockroach/pull/45455, so blocked.


<!-- Sent from Reviewable.io -->

2020-02-27 21:46 UTC, rohany commented
I think using `ActiveVersionOrEmpty` and allowing the hash sharded index to be created if the resulting version `!= cluster.ClusterVersion{}` makes sense.

2020-02-27 22:22 UTC, ajwerner reviewed
> Reviewed 10 of 20 files at r12, 14 of 14 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1286 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BYY4gB_b_1kKn7fua:-M-oPyGs6CW1HK7-nH0E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/create_table.go#L1286)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why are you ignoring this error? If it's due to some assumption that this has already passed, please add a comment. 
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1205 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M17aQl49xbFdUQkXoXj:-M17jBRvEDLJH24hf24B:b6xwyq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a14a3bd8d1954fc20e6805bb996450cc7d30157/pkg/sql/create_table.go#L1205)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`st` can be nil here. `cluster.Version` can also be uninitialized (see comment above the `if st != nil` block above).

I'm not familiar enough with this area to figure what should be done here if `st == nil` or if `active cluster version == cluster.ClusterVersion{}`. Any ideas? @rohany perhaps? Ran into this when rebasing https://github.com/cockroachdb/cockroach/pull/45455, so blocked.
</blockquote></details>

in what cases can `st == nil` be true here? If it's testing, can we fix those cases by plumbing cluster settings in?

When is active cluster version `ClusterVersion{}`? Shouldn't we default that value to the minimum cluster version for this release?
___
*[pkg/sql/drop_index.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BYxM57nyVidyR5601:-M-oQFF-0Y2MeR0q1CIM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/drop_index.go#L336)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why not `&&` and lose a layer of indentation?
</blockquote></details>

Done.
___
*[pkg/sql/drop_index.go, line 362 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M-BZ5DE73TeQlKqDztU:-M-oQRIr-DYWso0O28oc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1cb936e8d342d095a3ba4f05c37a9157262eb4/pkg/sql/drop_index.go#L362)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: please use `&&` on the conditions rather than the nested `if`. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-27 22:27 UTC, rohany commented
I take it back -- I can't seem to find whatever was passing a nil settings into here.

2020-02-27 22:41 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1205 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M17aQl49xbFdUQkXoXj:-M17ngH24_neDrS8ZX7A:b-ypn253) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a14a3bd8d1954fc20e6805bb996450cc7d30157/pkg/sql/create_table.go#L1205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

in what cases can `st == nil` be true here? If it's testing, can we fix those cases by plumbing cluster settings in?

When is active cluster version `ClusterVersion{}`? Shouldn't we default that value to the minimum cluster version for this release?
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/6595c628953b492aacad42517852441e47138e48/pkg/settings/cluster/settings.go#L286

It's `ClusterVersion{}` when the version is uninitialized. 


<!-- Sent from Reviewable.io -->

2020-02-27 22:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1205 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M17aQl49xbFdUQkXoXj:-M17oXhcD-N6v18G4qL2:b-nk3k0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a14a3bd8d1954fc20e6805bb996450cc7d30157/pkg/sql/create_table.go#L1205)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/6595c628953b492aacad42517852441e47138e48/pkg/settings/cluster/settings.go#L286

It's `ClusterVersion{}` when the version is uninitialized. 
</blockquote></details>

I'm fine with disallowing in the case that the version is empty though given the node startup flow I think this should still only happen in testing and is worthy of a comment. Let's not introduce the nil check on the setting if we can avoid it. 


<!-- Sent from Reviewable.io -->

2020-02-27 22:48 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42922)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @jordanlewis, @rohany, @solongordon, and @yuzefovich)

___
*[pkg/sql/create_table.go, line 1205 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/42922#-M17aQl49xbFdUQkXoXj:-M17pQ6_2LhMSB85hGBA:b-rntu85) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a14a3bd8d1954fc20e6805bb996450cc7d30157/pkg/sql/create_table.go#L1205)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm fine with disallowing in the case that the version is empty though given the node startup flow I think this should still only happen in testing and is worthy of a comment. Let's not introduce the nil check on the setting if we can avoid it. 
</blockquote></details>

Done (https://github.com/cockroachdb/cockroach/pull/45455#issuecomment-592216581). I'll leave the nil check cleanup to Rohan, I think it affects more places than just here anyway.


<!-- Sent from Reviewable.io -->