roachtest: do not use TIMETZ type for sqlsmith test on 19.2
cockroachdb/cockroach pull request #43080
Opened 2019-12-10 17:55 UTC by yuzefovich

We do not support TIMETZ type on 19.2 branch, so we want to regenerate
the setup if it happened to contain this type. This will stop "syntax
error" messages to be filed as errors.

Release note: None

2019-12-10 17:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43080)
<!-- Reviewable:end -->

2019-12-11 05:00 UTC, mjibson commented on pkg/cmd/roachtest/sqlsmith.go
> +					continue
This continue will only retrigger the check loop, not the setupFunc loop.

2019-12-11 05:20 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43080#-Lvkws28iQjQ9Qp_Kucx-r1-103:-LvnOeB0BSwEQA1J2ivJ:bm5oqht) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae63ce5c5e9e41ddcaceaebbee547125023ece3/pkg/cmd/roachtest/sqlsmith.go#L103)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

```
for prefix, typs := range unsupportedTypesByVersion {
  if strings.HasPrefix(version, prefix) {
    unsupportedTypes = types
    break
  }
}
```

feels like it makes more sense
</blockquote></details>

I agree, thanks.
___
*[pkg/cmd/roachtest/sqlsmith.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43080#-Lvkws28iQjQ9Qp_Kucx-r1-114:-LvnOgVF1pqupt1PKNp5:b-qg882e) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae63ce5c5e9e41ddcaceaebbee547125023ece3/pkg/cmd/roachtest/sqlsmith.go#L114)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This continue will only retrigger the check loop, not the setupFunc loop.
</blockquote></details>

You're right, fixed.


<!-- Sent from Reviewable.io -->

2019-12-11 16:00 UTC, madelynnblue requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @yuzefovich)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43080#-Lvkws28iQjQ9Qp_Kucx-r1-114:-LvpfkDvBVnTQWEV4mfB:b-gek3gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae63ce5c5e9e41ddcaceaebbee547125023ece3/pkg/cmd/roachtest/sqlsmith.go#L114)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

You're right, fixed.
</blockquote></details>

I also just realized that this function needs to have a retry fail count. This is because some setups (like the seed setup) have a hard coded time type and will thus always fail this function. No amount of randomness will change that.

I sort of think that we should just do this type failure test one time and skip the current setup if it fails the first time, instead of trying in a loop.


<!-- Sent from Reviewable.io -->

2019-12-11 16:37 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43080#-Lvkws28iQjQ9Qp_Kucx-r1-114:-Lvpof3c-f1m_iXf2YLd:b-83lzry) ([raw file](https://github.com/cockroachdb/cockroach/blob/cae63ce5c5e9e41ddcaceaebbee547125023ece3/pkg/cmd/roachtest/sqlsmith.go#L114)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I also just realized that this function needs to have a retry fail count. This is because some setups (like the seed setup) have a hard coded time type and will thus always fail this function. No amount of randomness will change that.

I sort of think that we should just do this type failure test one time and skip the current setup if it fails the first time, instead of trying in a loop.
</blockquote></details>

Oh, you're right, I didn't think about that. Done.


<!-- Sent from Reviewable.io -->

2019-12-12 01:37 UTC, madelynnblue approved these changes

2019-12-12 03:04 UTC, yuzefovich commented
TFTR!

bors r+

2019-12-12 03:37 UTC, merged