sql: use the correct context when recording an error for sentry
cockroachdb/cockroach pull request #43301
Opened 2019-12-18 19:07 UTC by yuzefovich

Previously, context.Background() was used to record an internal error.
That context is missing the registered tags (e.g. 'statement' tag) which
results in an incomplete sentry report. Now this is fixed.

Release note: None

2019-12-18 19:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43301)
<!-- Reviewable:end -->

2019-12-18 19:10 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwPP4zD8MuKpc-aOgY6:bbr1598) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
> ```Go
> 			res.CloseWithErr(pe.errorCause())
> 		} else {
> 			ex.recordError(ctx, resErr)
> ```

The duplicate report happens because of these two lines - both `ex.recordError` and `res.Close` create a report, I'm not sure which one should not be happening. Should we modify `res.Close` to take an argument whether the report has already been created?


<!-- Sent from Reviewable.io -->

2019-12-18 19:10 UTC, knz approved these changes
Fantastic find. This must have been painful to troubleshoot. You're a hero.

2019-12-18 19:13 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwPQ6HWAOztN-bR_y2n:b-zfxy9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The duplicate report happens because of these two lines - both `ex.recordError` and `res.Close` create a report, I'm not sure which one should not be happening. Should we modify `res.Close` to take an argument whether the report has already been created?
</blockquote></details>

Unsure what the best approach is.
My recollection is the following:
- we can't make res.Close the only place responsible because if the resultwriter is not pgwire, the error would get lost
- we can't make this code here the only place responsible, because we need to catch the error on other termination paths (e.g. a panic)

Maybe what you suggest is not too bad. It's possible that the number of people who can propose an informed opinion on this has been reduced to just 1 (you) over the last year.


<!-- Sent from Reviewable.io -->

2019-12-18 19:26 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwPTBZK3S81QG6IbrdZ:bpck9tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Unsure what the best approach is.
My recollection is the following:
- we can't make res.Close the only place responsible because if the resultwriter is not pgwire, the error would get lost
- we can't make this code here the only place responsible, because we need to catch the error on other termination paths (e.g. a panic)

Maybe what you suggest is not too bad. It's possible that the number of people who can propose an informed opinion on this has been reduced to just 1 (you) over the last year.
</blockquote></details>

I'm under the same impression as your recollection of things, so I pushed a second commit to add that argument. PTAL.


<!-- Sent from Reviewable.io -->

2019-12-18 19:28 UTC, andreimatei reviewed
For the first commit, where is the sentry reporting happening?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-:-LwPTjdO4ct92gh6HNi2:bd68h8s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)



<!-- Sent from Reviewable.io -->

2019-12-18 19:30 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPUBEb5WWnoydmUGwg:-LwPUBEb5WWnoydmUGwh:b-16nj8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d83c7c290c20ecb1de95e1ab67e6738b4a2d73fa/pkg/sql/conn_executor.go#L1434)):*
> ```Go
> 			// We have just reported the error, so we tell res.Close not to report
> 			// the error to avoid the duplicate error report.
> 			res.Close(ctx, stateToTxnStatusIndicator(ex.machine.CurState()), false /* shouldReportError */)
> ```

@andreimatei this is where the reporting happens and where the context was needed.


<!-- Sent from Reviewable.io -->

2019-12-18 19:34 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPUBEb5WWnoydmUGwg:-LwPV8ss0N63AXZJL1d7:b9r3284) ([raw file](https://github.com/cockroachdb/cockroach/blob/d83c7c290c20ecb1de95e1ab67e6738b4a2d73fa/pkg/sql/conn_executor.go#L1434)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

@andreimatei this is where the reporting happens and where the context was needed.
</blockquote></details>

pls point me to the code that calls into sentry


<!-- Sent from Reviewable.io -->

2019-12-18 19:35 UTC, knz commented
In `pgwire/conn.go`:

```

func writeErr(
  ctx context.Context, sv *settings.Values, err error, msgBuilder *writeBuffer, w io.Writer,
) error {
  // Record telemetry for the error.
  sqltelemetry.RecordError(ctx, err, sv)
```

2019-12-18 19:35 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPUBEb5WWnoydmUGwg:-LwPVWtGAWqurN656Ph2:bflnjxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d83c7c290c20ecb1de95e1ab67e6738b4a2d73fa/pkg/sql/conn_executor.go#L1434)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls point me to the code that calls into sentry
</blockquote></details>

`pkg/sql/pgwire/conn.go:1190`


<!-- Sent from Reviewable.io -->

2019-12-18 21:00 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwPkba_3aKfp5zEQFZp:b-a1hcir) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm under the same impression as your recollection of things, so I pushed a second commit to add that argument. PTAL.
</blockquote></details>

I think we need a clear contract about who reports what. Given that pgwire is in the reporting game, I think the `connExecutor` should get out of it; I don't see what benefit we get from sql ever doing it. Perhaps for internal executors... but we don't do it consistently. I'd rather do it in the `bufferedCommandResult` if we care about internal executor. Or, rather, forget about them.
I also think that the way in which pgwire gets that statement from the context is fairly ridiculous. It's obviously extremely fragile, and we care about that statement enough. Getting random dynamic tags from the context to put them in the report is fine, but the statement is not dynamic. Moreover, pgwire actually has the statement. It doesn't need to get it in an insane way from sql. The constructor of the `CommandResult` has it, for example. So let's just hang it from the `CommandResult`.

So, I'd keep the first commit but change the way in which the statement is retrieved for the report, and I'd do something else for the 2nd commit.
___
*[pkg/sql/conn_io.go, line 671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPeP64EkVwxtdlOpUS:-LwPeP654uWwblAZ8AoL:bi6drya) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L671)):*
> ```Go
> 	// an error (if present). This should be set to true only if the caller will
> 	// take care of creating the report on their own.
> 	Close(ctx context.Context, tsi TransactionStatusIndicator, shouldReportError bool)
> ```

No bool arguments to high-profile APIs like this! In fact, no bool args ever (discouraged by the style guide too.
Make it an enum if we don't find a better idea.

Also what's the "should"? Should every function Foo be called shouldFoo? :)
Just `reportError`.
___
*[pkg/sql/conn_io.go, line 671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPei85BFTQwxBAz9-z:-LwPei85BFTQwxBAz90-:bcq3qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L671)):*
> ```Go
> 	// an error (if present). This should be set to true only if the caller will
> 	// take care of creating the report on their own.
> 	Close(ctx context.Context, tsi TransactionStatusIndicator, shouldReportError bool)
> ```

The only caller that sets the new argument doesn't need it - the result in question is created just above and has no error. So the arg is not needed.
___
*[pkg/sql/conn_io.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPjTQI7O022sLMEnaX:-LwPjTQI7O022sLMEnaY:b36gbyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L681)):*
> ```Go
> 	// command in the same batch as the one being closed. The contract is that the
> 	// next result created corresponds to the first command in the next batch.
> 	CloseWithErr(context.Context, error)
> ```

It looks to me like we can get rid of this `CloseWithErr()`. It's only called in one place, which can call `SetError() + Close()`. Getting rid of it would simplify the reasoning about this PR. Perhaps in a preamble commit.
___
*[pkg/sql/pgwire/conn.go, line 1174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPgBtsEv2p3DAEErnh:-LwPgBtsEv2p3DAEErni:b-8ivy26) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/pgwire/conn.go#L1174)):*
> ```Go
> }
> 
> func (c *conn) bufferErr(ctx context.Context, err error, shouldReportError bool) {
> ```

no bools

And I don't think the arg is needed. If the code is simplified, I think this will always be false.
___
*[pkg/sql/pgwire/conn.go, line 1188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPi7b7DEMZTccMZMPW:-LwPi7b7DEMZTccMZMPX:b-714yof) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/pgwire/conn.go#L1188)):*
> ```Go
> }
> 
> func writeErr(
> ```

split this into `writeErr()` and `writeAndReportErr()`. 


<!-- Sent from Reviewable.io -->

2019-12-18 21:13 UTC, knz commented
> t. Perhaps for internal executors... 

yes!

> but we don't do it consistently. I'd rather do it in the bufferedCommandResult if we care about internal executor. 

Maybe that's a good idea.

> Or, rather, forget about them.

Surely not :)

2019-12-18 21:46 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_io.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPjTQI7O022sLMEnaX:-LwPyMtb8df4vxFD9AhI:b-mqzul7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L681)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

It looks to me like we can get rid of this `CloseWithErr()`. It's only called in one place, which can call `SetError() + Close()`. Getting rid of it would simplify the reasoning about this PR. Perhaps in a preamble commit.
</blockquote></details>

You're right. Added such commit (I wanna see that nothing breaks, so I've just pushed it.)


<!-- Sent from Reviewable.io -->

2019-12-19 15:54 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwTqebh0rAegXLH159t:b-ben5cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we need a clear contract about who reports what. Given that pgwire is in the reporting game, I think the `connExecutor` should get out of it; I don't see what benefit we get from sql ever doing it. Perhaps for internal executors... but we don't do it consistently. I'd rather do it in the `bufferedCommandResult` if we care about internal executor. Or, rather, forget about them.
I also think that the way in which pgwire gets that statement from the context is fairly ridiculous. It's obviously extremely fragile, and we care about that statement enough. Getting random dynamic tags from the context to put them in the report is fine, but the statement is not dynamic. Moreover, pgwire actually has the statement. It doesn't need to get it in an insane way from sql. The constructor of the `CommandResult` has it, for example. So let's just hang it from the `CommandResult`.

So, I'd keep the first commit but change the way in which the statement is retrieved for the report, and I'd do something else for the 2nd commit.
</blockquote></details>

I'm leaning more towards keeping the reporting of statement execution errors in sql, and not removing it from pgwire. So as soon as a CommandResult is created, the responsibility of reporting its error falls to the ConnExecutor.


<!-- Sent from Reviewable.io -->

2019-12-19 15:55 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwTrlPu5YEvdMIq7tnY:b-burh0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm leaning more towards keeping the reporting of statement execution errors in sql, and not removing it from pgwire. So as soon as a CommandResult is created, the responsibility of reporting its error falls to the ConnExecutor.
</blockquote></details>

I meant "and removing it from pgwire"


<!-- Sent from Reviewable.io -->

2019-12-19 16:27 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwTyrpT-cMJmWwZbpKf:b88n2u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I meant "and removing it from pgwire"
</blockquote></details>

I support making SQL generally more responsible for reporting.

Meanwhile we still need a mechanism in pgwire to record errors happening within pgwire.


<!-- Sent from Reviewable.io -->

2019-12-19 18:20 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwUNrhtBnb3jACoLLGi:bc9zs1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I support making SQL generally more responsible for reporting.

Meanwhile we still need a mechanism in pgwire to record errors happening within pgwire.
</blockquote></details>

yeah, for everything not using `newCommandResult` (i.e. for all the non-statement commands), pgwire would remain responsible


<!-- Sent from Reviewable.io -->

2019-12-19 22:13 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LwVBk5K5pHJoyvcHZkJ:b48svfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah, for everything not using `newCommandResult` (i.e. for all the non-statement commands), pgwire would remain responsible
</blockquote></details>

Pardon my ignorance, but I don't fully understand where the line between non-statement and statement commands lies. This seems like a bigger undertaking than I had in mind.

However, I looked into changing the way that statement is propagated, and although it is true that `commandResult` can store `tree.Statement`, `SendReport` is being called by other things (I got to `util/log logDepth()` function) and for those it'll be a lot of plumbing to pass in the statement outside of the context. I decided to not proceed with that change.

I appreciate the thoughtful comments that you guys provided though.
___
*[pkg/sql/conn_io.go, line 671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPeP64EkVwxtdlOpUS:-LwVAwpb3VQOjv87ShVA:b7virjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L671)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

No bool arguments to high-profile APIs like this! In fact, no bool args ever (discouraged by the style guide too.
Make it an enum if we don't find a better idea.

Also what's the "should"? Should every function Foo be called shouldFoo? :)
Just `reportError`.



</blockquote></details>

Introduced an enum.
___
*[pkg/sql/conn_io.go, line 671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPei85BFTQwxBAz9-z:-LwVBEooBJjuf8rDsyNA:bh7r5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/conn_io.go#L671)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The only caller that sets the new argument doesn't need it - the result in question is created just above and has no error. So the arg is not needed.
</blockquote></details>

Hm, I don't think it's correct (if there was no error, we would not be seeing duplicated reports).
___
*[pkg/sql/pgwire/conn.go, line 1174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPgBtsEv2p3DAEErnh:-LwVCzMt15-GJL32gaf7:bwfas9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/pgwire/conn.go#L1174)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no bools

And I don't think the arg is needed. If the code is simplified, I think this will always be false.
</blockquote></details>

No bools, but I believe the argument is needed.
___
*[pkg/sql/pgwire/conn.go, line 1188 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPi7b7DEMZTccMZMPW:-LwVBhlnA28asRIxVoIn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c337581834cbd45d397ae4ed232180ea62f8572/pkg/sql/pgwire/conn.go#L1188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

split this into `writeErr()` and `writeAndReportErr()`. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-27 22:48 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-Lx8NYJk3c8o_Sh714Vd:b1kip69) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
> SendReport is being called by other things 

I think it's fine for randos to take whatever they find in the context. In particular, `log.Fatal()` calls shouldn't happen, so I don't care too much about them.
But errors reported for the execution of SQL statements are not random, and also they're supposed to happen (or maybe not? We report on `code == pgcode.Internal || errors.HasAssertionFailure(err)` and I forgot when the `Internal` code happens).

Anyway, the thing I care more about is the contract about who reports what. Passing an extra arg to `res.Close()` I really don't like, and I don't think it's necessary. The `CommandResult` interface I care about.

What was the code doing before this PR? Isn't it nonsense?
It has two errors to deal with: `resErr` and `pe`. If there's no `resErr`, then it was passing `pe` to `res.CloseWithError()`, and the result was in charge of reporting the one and only error. Cool.
If there was a `resErr`, then it was recording the `resErr` (which was already part of the result and hence reported by the result), and it was ignoring `pe`. Does that make any sense? Perhaps what it wanted to do is record `pe`, not `resErr`. As written (before and after your PR), if you simply remove `ex.recordError(ctx, resErr)`, don't all the problems go away while reporting exactly what we already report?

Unless I'm missing something, I'd just get rid of that call and move on.
___
*[pkg/sql/conn_executor.go, line 1379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-Lx8Pd7B1BGPyXbVnldr:-Lx8Pd7CB4R4QpWrWqxu:b-dcrvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_executor.go#L1379)):*
> ```Go
> 				// If we're about to close the connection, close res in order to flush
> 				// now, as we won't have an opportunity to do it later.
> 				res.Close(ctx, stateToTxnStatusIndicator(ex.machine.CurState()), sqltelemetry.ErrorNotRecorded)
> ```

long line


<!-- Sent from Reviewable.io -->

2019-12-28 12:06 UTC, knz reviewed
> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBLvm54U9ggrcyS3mh:-LxBLvm64VguL7KHilsd:b-enmjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_executor.go#L1436)):*
> ```Go
> 		}
> 		errStatus := sqltelemetry.ErrorNotRecorded
> 		if resErr == nil && ok {
> ```

Can you add a few comments to explain why `errStatus` is needed and what are the various combination of causes/circumstances covered by the various branches of this conditional.

IMHO This code is very complex and it is important to help the future maintainer.
___
*[pkg/sql/conn_io.go, line 669 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBMgPG-sXcJOut1Duc:-LxBMgPG-sXcJOut1Dud:b-jxqos3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_io.go#L669)):*
> ```Go
> 	// state that needs to be closed even when the whole connection is about to be
> 	// terminated.
> 	Close(context.Context, TransactionStatusIndicator, sqltelemetry.RecordErrorStatus)
> ```

ditto my comment above about explaining the status more and the various cases that it covers (with examples).
___
*[pkg/sql/pgwire/conn.go, line 1177 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBNkPz0HanN81Msqis:-LxBNkPz0HanN81Msqit:b-unwhih) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/pgwire/conn.go#L1177)):*
> ```Go
> 		if err := writeAndReportErr(ctx, c.sv,
> 			err, &c.msgBuilder, &c.writerState.buf); err != nil {
> 			panic(fmt.Sprintf("unexpected err from buffer: %s", err))
> ```

So I went and investigated this case further. I believe a `panic` here is not warranted. 
tldr:
1) make `bufferErr` return `error` and propagate the error from here
2) change the remaining call points in `command_result.go` (in `Close`) to log then discard the error.

The reason is that it's actually legitimate for an error to occur here. The client could have disconnected and dropped its connection just before the error packet is sent. In fact it's even likely, for example if a user interrupts a long-running query after they quit the client that issued it. We don't want to panic in those cases.
___
*[pkg/sql/sqltelemetry/report.go, line 25 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBN7ctCzNLovWHwrMx:-LxBN7ctCzNLovWHwrMy:b-hfhhyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/sqltelemetry/report.go#L25)):*
> ```Go
> 
> // RecordErrorStatus indicates whether the error has already been recorded.
> type RecordErrorStatus int
> ```

```go
type foo bool

const a foo = true
const b foo = false
```

1) smaller footprint in memory
2) you don't need a `default` in the `switch`.


<!-- Sent from Reviewable.io -->

2019-12-31 04:22 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LxP6zRy7_FwPjKYRr32:bz8r6ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> SendReport is being called by other things 

I think it's fine for randos to take whatever they find in the context. In particular, `log.Fatal()` calls shouldn't happen, so I don't care too much about them.
But errors reported for the execution of SQL statements are not random, and also they're supposed to happen (or maybe not? We report on `code == pgcode.Internal || errors.HasAssertionFailure(err)` and I forgot when the `Internal` code happens).

Anyway, the thing I care more about is the contract about who reports what. Passing an extra arg to `res.Close()` I really don't like, and I don't think it's necessary. The `CommandResult` interface I care about.

What was the code doing before this PR? Isn't it nonsense?
It has two errors to deal with: `resErr` and `pe`. If there's no `resErr`, then it was passing `pe` to `res.CloseWithError()`, and the result was in charge of reporting the one and only error. Cool.
If there was a `resErr`, then it was recording the `resErr` (which was already part of the result and hence reported by the result), and it was ignoring `pe`. Does that make any sense? Perhaps what it wanted to do is record `pe`, not `resErr`. As written (before and after your PR), if you simply remove `ex.recordError(ctx, resErr)`, don't all the problems go away while reporting exactly what we already report?

Unless I'm missing something, I'd just get rid of that call and move on.

</blockquote></details>

I think you're right that the code was not doing what it intended, so I switched to "recording" `pe` and reporting `resErr` through `pgwire`, and I also agree that simply removing `ex.recordError(ctx, resErr)` would have solved the double reporting problem. Sorry for not seeing it before and making all this fuzz.

Yet, I'm leaning towards actually recording `pe`. Do you guys know whether `pe.errorCause()` and `res.Err()` are usually different? Do we want to report both?
___
*[pkg/sql/conn_executor.go, line 1379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-Lx8Pd7B1BGPyXbVnldr:-LxP6vQcCZDmS7ohtKrI:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_executor.go#L1379)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

long line
</blockquote></details>

Removed.
___
*[pkg/sql/conn_executor.go, line 1436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBLvm54U9ggrcyS3mh:-LxP6xLl-RLCc6B7pVJ0:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_executor.go#L1436)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you add a few comments to explain why `errStatus` is needed and what are the various combination of causes/circumstances covered by the various branches of this conditional.

IMHO This code is very complex and it is important to help the future maintainer.
</blockquote></details>

Removed.
___
*[pkg/sql/conn_io.go, line 669 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBMgPG-sXcJOut1Duc:-LxP7xsqAEWZHobPwS6A:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/conn_io.go#L669)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto my comment above about explaining the status more and the various cases that it covers (with examples).
</blockquote></details>

Removed.
___
*[pkg/sql/pgwire/conn.go, line 1177 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBNkPz0HanN81Msqis:-LxPAbpk-MgwnTxQE2oJ:b-pbuxou) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/pgwire/conn.go#L1177)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So I went and investigated this case further. I believe a `panic` here is not warranted. 
tldr:
1) make `bufferErr` return `error` and propagate the error from here
2) change the remaining call points in `command_result.go` (in `Close`) to log then discard the error.

The reason is that it's actually legitimate for an error to occur here. The client could have disconnected and dropped its connection just before the error packet is sent. In fact it's even likely, for example if a user interrupts a long-running query after they quit the client that issued it. We don't want to panic in those cases.
</blockquote></details>

Makes sense, added another commit.
___
*[pkg/sql/sqltelemetry/report.go, line 25 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxBN7ctCzNLovWHwrMx:-LxP6dac7fbwEKOEscDX:b-re73qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b260998508ff01bccf109f342763f5017dd72c0/pkg/sql/sqltelemetry/report.go#L25)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```go
type foo bool

const a foo = true
const b foo = false
```

1) smaller footprint in memory
2) you don't need a `default` in the `switch`.
</blockquote></details>

Code was removed, but thanks for the suggestion.


<!-- Sent from Reviewable.io -->

2019-12-31 11:45 UTC, knz approved these changes
LGTM with nits

> Reviewed 1 of 3 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-:-LxQlfCr5d1kwNhBLwyF:b3nilp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LxQjQON1rpRECc7hcwo:b-ptf6ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think you're right that the code was not doing what it intended, so I switched to "recording" `pe` and reporting `resErr` through `pgwire`, and I also agree that simply removing `ex.recordError(ctx, resErr)` would have solved the double reporting problem. Sorry for not seeing it before and making all this fuzz.

Yet, I'm leaning towards actually recording `pe`. Do you guys know whether `pe.errorCause()` and `res.Err()` are usually different? Do we want to report both?
</blockquote></details>

I would cut this gordian knot by using `errors.CombineErrors`  to report whichever is set if only one is set, or both if both are set.
___
*[pkg/sql/pgwire/command_result.go, line 103 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQjrCC0prh35Sg57hv:-LxQjrCC0prh35Sg57hw:be2svo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/command_result.go#L103)):*
> ```Go
> 			ctx, r.conn.sv, r.err, &r.conn.msgBuilder, &r.conn.writerState.buf,
> 		); err != nil {
> 			log.VErrEvent(ctx, 2 /* level */, err.Error())
> ```

1) I think you can be a bit clearer about what is going on:
```go
log.VErrEventf(ctx, 2 /* level */, `error in writeErr(): %v`, err)
```

2) do you want to hide these errors by default? I was thinking about `log.Warningf` instead of a trace-only thing.

3) (optionally) you can place this logging in a helper function, which you can call in other places where `writeErr` is called. I provide a few (non-exhaustive) examples below. If you prefer to leave this out of scope, you can file an issue with my name on it and I'll pick it up later.
___
*[pkg/sql/pgwire/conn.go, line 349 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQklff1uoxGSAbYfmy:-LxQklfgCsC3IhrSxNlW:b-y6y8sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L349)):*
> ```Go
> 			// This messages are only acceptable during the auth phase, handled above.
> 			err = pgwirebase.NewProtocolViolationErrorf("unexpected authentication data")
> 			_ /* err */ = writeErr(
> ```

you can emit the error here with the helper too
___
*[pkg/sql/pgwire/conn.go, line 460 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQkSRL2PsgrLFK_QmM:-LxQkSRL2PsgrLFK_QmN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L460)):*
> ```Go
> 		_ /* err */ = writeErr(ctx, &sqlServer.GetExecutorConfig().Settings.SV,
> 			newAdminShutdownErr(ErrDrainingExistingConn), &c.msgBuilder, &c.writerState.buf)
> 		_ /* n */, _ /* err */ = c.writerState.buf.WriteTo(c.conn)
> ```

ditto
___
*[pkg/sql/pgwire/conn.go, line 542 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQl5b38ZN8Sw4PaJ5h:-LxQl5b38ZN8Sw4PaJ5i:b-dkxzio) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L542)):*
> ```Go
> 					// Add a prefix. This also adds a stack trace.
> 					retErr = errors.Wrap(retErr, "caught fatal error")
> 					_ = writeErr(
> ```

here it's different, I believe the error should not be ignored (neither the one below).
This would be `retErr = errors.CombineErrors(retErr, err)`
___
*[pkg/sql/pgwire/conn.go, line 609 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQlEDJAXIpqHoL5Ail:-LxQlEDKBWSDJPyhsH5-:b-j355ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L609)):*
> ```Go
> 		ctx, c.sessionArgs, &c.stmtBuf, c, c.metrics.SQLMemMetrics)
> 	if err != nil {
> 		_ /* err */ = writeErr(
> ```

ditto `errors.CombineErrors`
___
*[pkg/sql/pgwire/conn.go, line 1491 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQlJPl44-qsYuS4Vss:-LxQlJPl44-qsYuS4Vst:b-8a09yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L1491)):*
> ```Go
> ) error {
> 	sendError := func(err error) error {
> 		_ /* err */ = writeErr(ctx, &execCfg.Settings.SV, err, &c.msgBuilder, c.conn)
> ```

Probably `errors.CombineErrors` here too.


<!-- Sent from Reviewable.io -->

2020-01-02 16:15 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-Lxb0nw62-I54VL2colu:b6hxwrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
> Yet, I'm leaning towards actually recording pe

You mean, you're leaning towards *not* recording `pe`?

> Do you guys know whether pe.errorCause() and res.Err() are usually different? Do we want to report both?

They're different in some corner cases. For example on query cancelation, `resErr` is more sanitized than `pe`. On schema change failure, you have a `resErr` but not a `pe` (because schema changes run when the transaction commits, and the events and their payloads are about transaction updates).
So I think we should not record `pe`.


<!-- Sent from Reviewable.io -->

2020-01-02 18:20 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LwPP4zD8MuKpc-aOgY5:-LxbO6FU25WmlGpHbkB6:bkphvy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9624c32315638bdce357ce0e6182587098b8950/pkg/sql/conn_executor.go#L1431)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> Yet, I'm leaning towards actually recording pe

You mean, you're leaning towards *not* recording `pe`?

> Do you guys know whether pe.errorCause() and res.Err() are usually different? Do we want to report both?

They're different in some corner cases. For example on query cancelation, `resErr` is more sanitized than `pe`. On schema change failure, you have a `resErr` but not a `pe` (because schema changes run when the transaction commits, and the events and their payloads are about transaction updates).
So I think we should not record `pe`.
</blockquote></details>

I did mean "recording `pe`", but your examples of the differences suggest that recording `resErr` should be sufficient, so I removed the newly added reporting of `pe` as you're suggesting.
___
*[pkg/sql/pgwire/command_result.go, line 103 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQjrCC0prh35Sg57hv:-LxbPAmaBt5WpgPOkH_4:bsatl4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/command_result.go#L103)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) I think you can be a bit clearer about what is going on:
```go
log.VErrEventf(ctx, 2 /* level */, `error in writeErr(): %v`, err)
```

2) do you want to hide these errors by default? I was thinking about `log.Warningf` instead of a trace-only thing.

3) (optionally) you can place this logging in a helper function, which you can call in other places where `writeErr` is called. I provide a few (non-exhaustive) examples below. If you prefer to leave this out of scope, you can file an issue with my name on it and I'll pick it up later.

</blockquote></details>

Nice suggestions, thanks, done.
___
*[pkg/sql/pgwire/conn.go, line 349 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQklff1uoxGSAbYfmy:-LxbSppX4_5svcLcyzCq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L349)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can emit the error here with the helper too
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 460 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQkSRL2PsgrLFK_QmM:-LxbSoKb3DejERtS17nV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L460)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 542 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQl5b38ZN8Sw4PaJ5h:-LxbQZMh2VrTMGD-SYeN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L542)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here it's different, I believe the error should not be ignored (neither the one below).
This would be `retErr = errors.CombineErrors(retErr, err)`

</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 609 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQlEDJAXIpqHoL5Ail:-LxbQxK9-iVlXKIZg50m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L609)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto `errors.CombineErrors`
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/conn.go, line 1491 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxQlJPl44-qsYuS4Vss:-LxbRAyO2T_2gBKen3V4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaec2d030366070e602a94df8dcbe440bfeadfb7/pkg/sql/pgwire/conn.go#L1491)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Probably `errors.CombineErrors` here too.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/server.go, line 499 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxbU0np5mVo76tcqEvJ:-LxbU0np5mVo76tcqEvK:bblwypw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab47e59fac0ac47a0dff785bedcb18dd777a5569/pkg/sql/pgwire/server.go#L499)):*
> ```Go
> 	sendErr := func(err error) error {
> 		msgBuilder := newWriteBuffer(s.metrics.BytesOutCount)
> 		writeErrWithLogging(ctx, &s.execCfg.Settings.SV, err, msgBuilder, conn)
> ```

I don't have a feeling for whether this should be logged or combined with the error to return. Thoughts?


<!-- Sent from Reviewable.io -->

2020-01-02 20:28 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/pgwire/conn.go, line 1187 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-Lxbvxk_Bm8-vVab2nnv:-Lxbvxk_Bm8-vVab2nnw:bvbbn7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab47e59fac0ac47a0dff785bedcb18dd777a5569/pkg/sql/pgwire/conn.go#L1187)):*
> ```Go
> // writeErrWithLogging is the same as writeErr with the addition of logging the
> // error returned by writeErr.
> func writeErrWithLogging(
> ```

I don't know about this logging... We don't log for other communication errors (or do all communication errors end up in a call to this? I don't think so). And for good reason - client connections dropping are not a noteworthy event - at least not noteworthy for our log files.
___
*[pkg/sql/pgwire/conn.go, line 1193 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxbvpBG9Hq08TsXXnoN:-LxbvpBG9Hq08TsXXnoO:b-5il9i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab47e59fac0ac47a0dff785bedcb18dd777a5569/pkg/sql/pgwire/conn.go#L1193)):*
> ```Go
> 		ctx, sv, err, msgBuilder, w,
> 	); err != nil {
> 		log.Warningf(ctx, `error in writeErr(): %v`, err)
> ```

nit: s/%v/%s since you know err is not nil. We use `%v` to tolerate nils.
___
*[pkg/sql/pgwire/server.go, line 499 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxbU0np5mVo76tcqEvJ:-Lxbu60HC4B480K7kF9u:buwp8gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab47e59fac0ac47a0dff785bedcb18dd777a5569/pkg/sql/pgwire/server.go#L499)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't have a feeling for whether this should be logged or combined with the error to return. Thoughts?
</blockquote></details>

I wouldn't combine it. Per the comment of `ServeConn()`: An error is returned if the initial handshake of the connection fails.
Failing to send the handshake error to the client is not interesting; combining the error would only blur the reason why the handshake failed.

More importantly, `ServeConn` doesn't generally return communication errors to the caller. Given that, returning a communication error from the handshake part of the protocol in particular doesn't make much sense.

You can argue that `ServeConn()` shouldn't return any errors. The reason why it does return handshake errors, I guess, is because we want to log those in particular since they might be important to yell about - they might show some client misconfiguration, bad certs, etc. There's probably a better way to achieve said logging.


<!-- Sent from Reviewable.io -->

2020-01-03 00:47 UTC, knz reviewed
I'll review more later, just replying on a nit here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-:-LxcrqIk527Ls0P0-7JN:b-n3uiwl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/pgwire/conn.go, line 1193 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LxbvpBG9Hq08TsXXnoN:-LxcrlhABkMS_Ktjy9o0:bavf9da) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab47e59fac0ac47a0dff785bedcb18dd777a5569/pkg/sql/pgwire/conn.go#L1193)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: s/%v/%s since you know err is not nil. We use `%v` to tolerate nils.
</blockquote></details>

this nit is more a FYI. The code is fine as-is. We use `%v` throughout for errors.


<!-- Sent from Reviewable.io -->

2020-01-21 16:52 UTC, yuzefovich commented
Guys, what do you think about not merging the last commit about auditing error handling and leaving a TODO to do that? The original intention of this PR was simply removing duplicated reports of errors to Sentry.

2020-01-21 16:54 UTC, knz commented
I'm in favor. You can split the commit in a separate PR.
I'll let Andrei weigh in, his opinion on this is more informed than mine.

2020-01-21 17:11 UTC, yuzefovich commented
Removed the last commit and will open a separate PR to continue discussion in there.

2020-01-23 17:06 UTC, andreimatei reviewed
I really wanted to and agonized for an hour, but I just can't sign off on the first commit. I know you haven't written this code, so you can take Rafa's LGTM and run with it, but I can't put mine. Having something as important as including the statement in the Sentry reports depend on what context `res.Close()` is called with does not make sense. It's magic for no reason and fragile for no reason. The caller to `res.Close()` might as well put structured information in the error for the purposes of the report - for example by using the `errors.With<foo>(err)` patterns.
Also notice that currently because of the context stuff the reports don't make a distinction between errors encountered by execution of a statement or portal vs errors encountered by a prepare. If we make this caller construct some structured info, it'd be trivial to make that distinction.

On `log.Fatal()`, on the other hand, I think the magic is justified to get as much info as possible. On panics, I similarly believe the magic is justified, except that it looks to me like on the [one panic handler that matters](https://github.com/cockroachdb/cockroach/blob/9f8359c73846dedd30fa7a2330cf99d788102c21/pkg/sql/conn_executor.go#L736), the magic will actually not work because the context there is not the one with the statement in it. So again I think some structured solution needs to be find. For example recovering panics earlier, somewhere in `conn_executor_exec.go`, and panicing again with an error that has the statement in it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-:-LzIFxN21LG0mI-ObpiT:b-49x0x6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1438 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LzIBW2a5wET2U5gh50A:-LzIBW2b0FS-F1Um05gk:bb1bx89) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f3143789feecfcb620ec15f8f3d14370f2dce2/pkg/sql/conn_executor.go#L1438)):*
> ```Go
> 			res.SetError(pe.errorCause())
> 		} else {
> 			ex.recordError(ctx, resErr)
> ```

now that this call goes away, there's no reason for `recordError` to stay a method on the executor. Please get rid of it.
___
*[pkg/sql/conn_executor.go, line 1435 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LzIA5HL0i1ae_xQciKY:-LzIA5HL0i1ae_xQciKZ:b93sjto) ([raw file](https://github.com/cockroachdb/cockroach/blob/f922b7307cd142aab9d2868f143ab8877b3466ec/pkg/sql/conn_executor.go#L1435)):*
> ```Go
> 			ex.sessionEventf(ctx, "execution error: %s", pe.errorCause())
> 			if resErr == nil {
> 				// We use the payload error to set on the result only if 'res' doesn't
> ```

This comment is confusing. The first sentence is unnecessary since it just states the code without adding any useful commentary. The 2nd sentence talks about reporting, but no reader will know what you're talking about - the reporting is hidden 20 levels deep. I don't think this code needs any comment besides that comment a few lines up that claims that `res.Err()` might not be set in case of error events; we'd be doing this `SetError()` regardless of any reporting concerns.


<!-- Sent from Reviewable.io -->

2020-01-23 17:56 UTC, yuzefovich reviewed
I appreciate the thoughtful comments that you left, and I extracted them into a separate issue (#44308). I believe that this PR strictly improves the situation, so it is beneficial to merge it. At the moment, I don't have the bandwidth to look into this further, so I'll go ahead and merge it as is.

Thanks for the comments!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-:-LzIRzdABuRm0zhMfNb-:ba82rl8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @yuzefovich)

___
*[pkg/sql/conn_executor.go, line 1438 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LzIBW2a5wET2U5gh50A:-LzIQGUGDZbVfFSJJUTD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/46f3143789feecfcb620ec15f8f3d14370f2dce2/pkg/sql/conn_executor.go#L1438)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

now that this call goes away, there's no reason for `recordError` to stay a method on the executor. Please get rid of it.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 1435 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/43301#-LzIA5HL0i1ae_xQciKY:-LzIQPbYEY-hfvqsMDYk:btfxb5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f922b7307cd142aab9d2868f143ab8877b3466ec/pkg/sql/conn_executor.go#L1435)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment is confusing. The first sentence is unnecessary since it just states the code without adding any useful commentary. The 2nd sentence talks about reporting, but no reader will know what you're talking about - the reporting is hidden 20 levels deep. I don't think this code needs any comment besides that comment a few lines up that claims that `res.Err()` might not be set in case of error events; we'd be doing this `SetError()` regardless of any reporting concerns.
</blockquote></details>

Ok, removed.


<!-- Sent from Reviewable.io -->

2020-01-23 18:52 UTC, merged