demo: round robin movr workload onto all nodes
cockroachdb/cockroach pull request #43474
Opened 2019-12-23 00:39 UTC by rohany

Fixes #42591.

This PR allows the `cockroach demo --with-load` to round-robin
queries to all the nodes in the demo cluster.

Release note (cli change): allows for `cockroach demo --with-load` to
round robin queries to all nodes in the demo cluster.

2019-12-23 00:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43474)
<!-- Reviewable:end -->

2020-01-09 17:30 UTC, otan requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyALB5I00AFhJfzKlLP:bnsgl3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
> ```Go
> 	ql := workload.QueryLoad{SQLDatabase: sqlDatabase}
> 	for range urls {
> 		db, err := gosql.Open(`cockroach`, urlStrs)
> ```

a little confused here: doesn't this round robin inside a round robin? as in - we are looping over every URL to open a sql connection to every other URL?
or should I be reading this differently?


<!-- Sent from Reviewable.io -->

2020-01-09 17:31 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyALvnI6DrvuU81st5d:b-88fwno) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

a little confused here: doesn't this round robin inside a round robin? as in - we are looping over every URL to open a sql connection to every other URL?
or should I be reading this differently?
</blockquote></details>

I thought so as well, but take a look at workload/driver.go -- it seems like the cockroach driver only round robins the _calls_ to open, rather than operations.


<!-- Sent from Reviewable.io -->

2020-01-09 18:15 UTC, otan commented
___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAT1Nn5tk1mf6ptO7g:b-i8n8jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I thought so as well, but take a look at workload/driver.go -- it seems like the cockroach driver only round robins the _calls_ to open, rather than operations.
</blockquote></details>

Not sure I quite get you here. To clarify first - is the intention of the PR to make it such that each worker has its own workload, or that each query alternates between different nodes? It seems like we want the latter, this code looks like it will do the former.

Nonetheless - if we are shooting for the former, it seems theoretically that if we did

```
for url := range urls {
   db, err := gosql.Open(`cockroach`, url)
}
```

should achieve the same thing, as the code in `workload/driver.go` round robins between the list of URLs passed in to `Open`.


<!-- Sent from Reviewable.io -->

2020-01-09 18:21 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAX0bWEC1m780t1zDz:b-fgwqh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Not sure I quite get you here. To clarify first - is the intention of the PR to make it such that each worker has its own workload, or that each query alternates between different nodes? It seems like we want the latter, this code looks like it will do the former.

Nonetheless - if we are shooting for the former, it seems theoretically that if we did

```
for url := range urls {
   db, err := gosql.Open(`cockroach`, url)
}
```

should achieve the same thing, as the code in `workload/driver.go` round robins between the list of URLs passed in to `Open`.

</blockquote></details>

The goal is to make sure that each demo node gets some queries from the workload. I couldn't get the driver to alternate queries among different nodes without making a separate workload function for each node. I'm not sure the driver does that (at least I couldn't get it to).


<!-- Sent from Reviewable.io -->

2020-01-09 18:24 UTC, otan commented
___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAXZaq5TSiCpYJW-fv:b-oztbn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
I thinkthe PR description is a bit misleading if we're doing it this way though, hehe.

> I couldn't get the driver to alternate queries among different nodes without making a separate workload function for each node.

Maybe you have a universal workload function, and for each query it generates you could make it use a different db connection each time? You'd have to mock a `db` object in `movrWorker` to round robin the execution between different engines or something.

If we're doing it this way though, I am still unsure why the below doesn't work for achieving the same thing

```
for url := range urls {
   db, err := gosql.Open(`cockroach`, url)
}
```


<!-- Sent from Reviewable.io -->

2020-01-09 18:25 UTC, otan commented
___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAYOC1C068zdhTrdrQ:b-9jffcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I thinkthe PR description is a bit misleading if we're doing it this way though, hehe.

> I couldn't get the driver to alternate queries among different nodes without making a separate workload function for each node.

Maybe you have a universal workload function, and for each query it generates you could make it use a different db connection each time? You'd have to mock a `db` object in `movrWorker` to round robin the execution between different engines or something.

If we're doing it this way though, I am still unsure why the below doesn't work for achieving the same thing

```
for url := range urls {
   db, err := gosql.Open(`cockroach`, url)
}
```

</blockquote></details>

Also, if we're doing it this way, do the work simulation queries conflict with each other?


<!-- Sent from Reviewable.io -->

2020-01-09 18:41 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAae4pCbPoO8nvt4cW:b-tvvyrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Also, if we're doing it this way, do the work simulation queries conflict with each other?
</blockquote></details>

I don't believe the queries conflict with each other

Yeah, that works as well (i had that originally, its probably clearer if that way is used)

That is what I was thinking, but I didn't want to reimplement that round robin logic -- it must be available somewhere in the repository! (well it is, but it's tied to a testing package for some reason...)


<!-- Sent from Reviewable.io -->

2020-01-09 19:01 UTC, otan commented
___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyAfieW-Sm3vXvYGS5B:bhbljdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
> (well it is, but it's tied to a testing package for some reason...)

maybe we can perform some surgery :D


<!-- Sent from Reviewable.io -->

2020-01-09 21:11 UTC, rohany commented
PTAL

2020-01-09 22:06 UTC, otan approved these changes
lgtm - is there something that exercises this in `pkg/cli/interactive_tests`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-:-LyB9iJe6AD2vistAO7p:bykgm0a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/workload/round_robin.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyB9gK38CFTYanS8wRo:-LyB9gK38CFTYanS8wRp:bf6lpvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfb358c4524c2dd13b94f05919ae3b889a528c/pkg/workload/round_robin.go#L28)):*
> ```Go
> // NewRoundRobinDB creates a RoundRobinDB using the databases from a list
> // of comma separated database connection url's.
> func NewRoundRobinDB(urlStr string) (*RoundRobinDB, error) {
> ```

nit: maybe just pass in a list of URIs to avoid the join / split
___
*[pkg/workload/round_robin.go, line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyBKvnp4Vssd1R3yobJ:-LyBKvnp4Vssd1R3yobK:b-jd1vvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfb358c4524c2dd13b94f05919ae3b889a528c/pkg/workload/round_robin.go#L32)):*
> ```Go
> 	r := &RoundRobinDB{current: 0, handles: make([]*gosql.DB, 0, len(urls))}
> 	for _, url := range urls {
> 		db, err := gosql.Open(`cockroach`, url)
> ```

should probably have a constant for the `cockroach` but /shrug not important for this PR


<!-- Sent from Reviewable.io -->

2020-01-09 22:10 UTC, rohany reviewed
Theres something that tests that the workload is actually running (i.e. no errors in the workload functions), but I don't know how to test that all nodes are getting queries. I've just been looking at the admin UI to verify instead.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-:-LyBLli6AZsEpHRsfBi4:b-o34l6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/workload/round_robin.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyB9gK38CFTYanS8wRo:-LyBLZrVD50MVULvIkrg:btzmser) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfb358c4524c2dd13b94f05919ae3b889a528c/pkg/workload/round_robin.go#L28)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: maybe just pass in a list of URIs to avoid the join / split
</blockquote></details>

i think? the convention for these things is to have comma separated lists, but i don't know enough to say.


<!-- Sent from Reviewable.io -->

2020-01-09 22:51 UTC, otan commented
___
*[pkg/workload/round_robin.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyB9gK38CFTYanS8wRo:-LyBVHSv2Yb00N1-UKuT:b91qhf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfb358c4524c2dd13b94f05919ae3b889a528c/pkg/workload/round_robin.go#L28)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

i think? the convention for these things is to have comma separated lists, but i don't know enough to say.
</blockquote></details>

`urlStrs := strings.Join(urls, ` `)`

makes it seem like otherwise haha, no worries, up to you.


<!-- Sent from Reviewable.io -->

2020-01-10 03:43 UTC, rohany reviewed
Do you mind taking another quick look before I merge it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-:-LyCYA3e-oAKXpgp9COF:b2fcr8m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/workload/round_robin.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyB9gK38CFTYanS8wRo:-LyCXfvUAHRxzGc5HAEr:b1pf6q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfb358c4524c2dd13b94f05919ae3b889a528c/pkg/workload/round_robin.go#L28)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

`urlStrs := strings.Join(urls, ` `)`

makes it seem like otherwise haha, no worries, up to you.
</blockquote></details>

ack i had it backwards...


<!-- Sent from Reviewable.io -->

2020-01-13 15:41 UTC, knz reviewed
Haven't looked in detail but Rohan and Oliver for this and in the future I would be grateful if you could file any `demo`-related PRs into the CLI project in addition to whatever else you had in mind as well. Thanks!

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-:-LyUZAnp3y-c06yOSuhi:bjfoge8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/workload/movr/workload.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-LyALB5I00AFhJfzKlLO:-LyUZ89r6RK2Mld5rpT8:b-cpcf2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a3b4b49042e946b92b97ca5f56c982c7798a7c7/pkg/workload/movr/workload.go#L313)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> (well it is, but it's tied to a testing package for some reason...)

maybe we can perform some surgery :D
</blockquote></details>

:+1: on code reuse and surgery


<!-- Sent from Reviewable.io -->

2020-01-13 16:09 UTC, otan approved these changes
Will do!
Everything looks good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43474#-:-LyUeXXr1-gFC0Ry1MNg:b-prevag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)



<!-- Sent from Reviewable.io -->

2020-01-13 16:55 UTC, rohany commented
Will do rafael!

bors r=otan

2020-01-13 17:25 UTC, merged

2020-01-13 18:35 UTC, andreimatei commented
Friendly note to please make release notes be full sentences. There's some examples in the commit message template.