colexec: make disk spiller catch only "its own" OOM errors
cockroachdb/cockroach pull request #43652
Opened 2019-12-30 20:55 UTC by yuzefovich

Previously, disk spiller would always catch an OOM error without paying
attention at which operator actually hit its memory limit. Now this is
(more or less) fixed by checking that the appropriate memory monitor
emitted the error.

Release note: None

2019-12-30 20:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43652)
<!-- Reviewable:end -->

2020-01-13 19:11 UTC, asubiotto requested changes
Good catch.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-:-LyVJHhA0NZAM6fnSaHa:b6zrrkh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/disk_spiller.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-LyVJEpjEj8lu_o9Cdoj:-LyVJEpjEj8lu_o9Cdok:b-v673l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02d56a1f7a11bc5e4dabc915b56c2678e7785da/pkg/sql/colexec/disk_spiller.go#L148)):*
> ```Go
> 	); err != nil {
> 		if sqlbase.IsOutOfMemoryError(err) &&
> 			// TODO(yuzefovich): is there a better way to distinguish where the error
> ```

Unfortunately nothing comes to mind. I think this is fine for now.
___
*[pkg/sql/colexec/execplan.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-LyVI4S486QYAWT59dYs:-LyVI4S486QYAWT59dYt:b1gg1eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02d56a1f7a11bc5e4dabc915b56c2678e7785da/pkg/sql/colexec/execplan.go#L773)):*
> ```Go
> 			} else {
> 				// No optimizations possible. Default to the standard sort operator.
> 				var sorterMemMonitorName = "sort-all-limited-" + uuid.FastMakeV4().String()
> ```

Can we make use the processor ID instead of an UUID?


<!-- Sent from Reviewable.io -->

2020-01-13 22:10 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43652)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/disk_spiller.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-LyVJEpjEj8lu_o9Cdoj:-LyVwoysEU13AysKBekZ:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02d56a1f7a11bc5e4dabc915b56c2678e7785da/pkg/sql/colexec/disk_spiller.go#L148)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Unfortunately nothing comes to mind. I think this is fine for now.
</blockquote></details>

Ack.
___
*[pkg/sql/colexec/execplan.go, line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-LyVI4S486QYAWT59dYs:-LyVxBWKEzuh1RfkH01k:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d02d56a1f7a11bc5e4dabc915b56c2678e7785da/pkg/sql/colexec/execplan.go#L773)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we make use the processor ID instead of an UUID?
</blockquote></details>

Good point, done.


<!-- Sent from Reviewable.io -->

2020-01-14 15:30 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43652#-:-LyZfGINE576YBcq__rE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-01-14 15:32 UTC, yuzefovich commented
TFTR!

bors r+

2020-01-14 16:00 UTC, merged