sql: pg_catalog.pg_am needs to be populated
cockroachdb/cockroach pull request #43715
Opened 2020-01-03 15:00 UTC by jasobrown

This patch adds inverted index to the access methods listed
in pg_am.

Additionally, this patch sets pg_class.relam to zero for sequences and views,
which is more consistent with postgres.

Fixes #27766

Release note (sql change): more accurate pg_catalog access method information.

2020-01-03 15:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43715)
<!-- Reviewable:end -->

2020-01-03 15:02 UTC, jasobrown commented
@BramGruneir PTAL

I wasn't quite sure if the existing access method name, 'prefix', was completely accurate (compared to something like MySQL's prefix index). `forward`, as in forward index, didn't seem quite right either. Is `prefix` still the best name here?

2020-01-03 23:28 UTC, BramGruneir commented
@jasobrown, this is great.  I'm on vacation until Monday, so if nobody else gets to it by then, I'll take a look.

2020-01-08 11:57 UTC, jasobrown reviewed
sorry, i think I clicked the LGTM button inadvertently.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-Ly4-PkbCafFygUxpVGL:bsvcqyp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir)



<!-- Sent from Reviewable.io -->

2020-01-08 22:00 UTC, knz commented
cc @rafiss @apantel

2020-01-13 21:42 UTC, rafiss requested changes
Thanks for the PR! just had some minor comments, though @bramgruneir 's review is still welcome!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-LyVqq98-7MNKKGzV1bQ:bwb8tkt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir and @jasobrown)

___
*[pkg/sql/pg_catalog.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyVqcs14R33P2EUh89m:-LyVqcs14R33P2EUh89n:b-z89gcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdaa2961334789068cab29945a09f52b960c2f8/pkg/sql/pg_catalog.go#L308)):*
> ```Go
> 		var err error
> 		// add row for forward indexes
> 		if err = addRow(
> ```

I think normally our convention would be to have `if err := addRow(...); err != nil {`, and skip the `err` declaration above
___
*[pkg/sql/pg_catalog.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyVqR-O1UJM-hhXqY17:-LyVqR-O1UJM-hhXqY18:bsgjpdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdaa2961334789068cab29945a09f52b960c2f8/pkg/sql/pg_catalog.go#L677)):*
> ```Go
> 		return forEachTableDesc(ctx, p, dbContext, virtualMany,
> 			func(db *sqlbase.DatabaseDescriptor, scName string, table *sqlbase.TableDescriptor) error {
> 				// The only difference between tables, views and sequences is the relkind column.
> ```

should this comment be adjusted now?


<!-- Sent from Reviewable.io -->

2020-01-13 21:46 UTC, BramGruneir approved these changes
This is looking good.  I went through all the expected values of pg_am (both 9.5 and 9.6) and they all look good.

As far as naming, prefix still seems fine to me.  

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  with the fixes @rafiss suggested. 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-LyVr8oPEUV48Y_E_3Ez:bts7wp8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jasobrown)



<!-- Sent from Reviewable.io -->

2020-01-14 10:22 UTC, jasobrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BramGruneir and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyVqcs14R33P2EUh89m:-LyYZZP20D_r3jPsqhsc:b-bjumx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdaa2961334789068cab29945a09f52b960c2f8/pkg/sql/pg_catalog.go#L308)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

I think normally our convention would be to have `if err := addRow(...); err != nil {`, and skip the `err` declaration above
</blockquote></details>

lol - i'm a golang newbie, so that pattern isn't ingrained yet. Fixed.
___
*[pkg/sql/pg_catalog.go, line 677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyVqR-O1UJM-hhXqY17:-LyYZXt93Je4O4mofB5F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdaa2961334789068cab29945a09f52b960c2f8/pkg/sql/pg_catalog.go#L677)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this comment be adjusted now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-14 11:40 UTC, knz reviewed
I'm all for this change but I am not too fond of including all the pg 9.5 _and_ 9.6 columns in `pg_am` side by side.

Although it is true that crdb still advertises as pg 9.5 in its early connection version string, we really have more and more features from 9.6+ (incl 10+ and 11+) and I don't think we should ride the 9.5 train for much longer.

FYI as per https://www.postgresql.org/docs/9.6/release-9-6.html v9.6 is where all the extra columns have been dropped. Maybe we should do the same.

Nevertheless, if we keep them, then at least the information included therein should be correct. See below.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-LyYph2O4L3SjcnGcR7z:b-upb8j2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jasobrown and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYouDk01MXq7PNA7Ao:-LyYouDk01MXq7PNA7Ap:b-aepa3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L62)):*
> ```Go
> )
> 
> var forwardIndexOid *tree.DOid
> ```

So this is 100% fine here but if you're keen to learn some more go idioms the following also works:

```go
var forwardIndexOid = func() *tree.DOid {
   h := makeOidHasher()
   h.writeStr(indexTypeForwardIndex)
   return h.getOid()
}()
```

The advantage of this is that it works "earlier than `init`" as well as earlier as any other variable that depends on this for initialization -- so there is no point where the variable can be used un-initialized.
___
*[pkg/sql/pg_catalog.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYqWuoAnFZOsnWLKrC:-LyYqWuoAnFZOsnWLKrD:b3t5x2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L351)):*
> ```Go
> 			zeroVal,                               // amstrategies - < v9.6
> 			zeroVal,                               // amsupport - < v9.6
> 			tree.DBoolTrue,                        // amcanorder - < v9.6
> ```

Are you sure about this one? I don't think we can order using inverted indexes.
___
*[pkg/sql/pg_catalog.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYq_KkA294V099t0OX:-LyYq_KkA294V099t0OY:b66tfa6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L353)):*
> ```Go
> 			tree.DBoolTrue,                        // amcanorder - < v9.6
> 			tree.DBoolFalse,                       // amcanorderbyop - < v9.6
> 			tree.DBoolTrue,                        // amcanbackward - < v9.6
> ```

Neither this.


<!-- Sent from Reviewable.io -->

2020-01-15 13:27 UTC, jasobrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @BramGruneir, @knz, and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 62 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYouDk01MXq7PNA7Ao:-LydMkEWDN2gp1tzwntu:b7ebc6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L62)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So this is 100% fine here but if you're keen to learn some more go idioms the following also works:

```go
var forwardIndexOid = func() *tree.DOid {
   h := makeOidHasher()
   h.writeStr(indexTypeForwardIndex)
   return h.getOid()
}()
```

The advantage of this is that it works "earlier than `init`" as well as earlier as any other variable that depends on this for initialization -- so there is no point where the variable can be used un-initialized.
</blockquote></details>

I had followed the style of the original implementation, but initializing the variables even before any `init` functions makes sense. Since there are two variables being initialized here (`forwardIndexOid` and `invertedIndexOid`), I opted to put the initializer code into a separate function rather than an inline lambda (like your sample) as I would need that code twice.
___
*[pkg/sql/pg_catalog.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYqWuoAnFZOsnWLKrC:-LydMYCFDInRWMe36Ve1:b-acotng) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L351)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Are you sure about this one? I don't think we can order using inverted indexes.
</blockquote></details>

You are correct. Fixed.
___
*[pkg/sql/pg_catalog.go, line 353 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-LyYq_KkA294V099t0OX:-LydMgLQ7bV2X_D6PDu7:b-9kgjve) ([raw file](https://github.com/cockroachdb/cockroach/blob/c46a633593b29886bc8cdd2d4ee5570073bc479c/pkg/sql/pg_catalog.go#L353)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Neither this.
</blockquote></details>

You are correct again. Fixed.


<!-- Sent from Reviewable.io -->

2020-01-28 02:37 UTC, jasobrown commented
@knz / @rafiss RFAL. Sorry this dropped for a while, but picking it up now to get it completed.

2020-01-28 09:17 UTC, knz approved these changes
No comment from me. @rafiss this is all yours.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-LzfRFE67IshXVA7iHrK:bf94bjo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2020-01-28 18:07 UTC, rafiss approved these changes
thanks for the change! lgtm

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43715#-:-LzhKWrKBT-ZYMAIjja4:bm59997)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2020-01-28 18:08 UTC, rafiss commented
bors r=rafiss

2020-01-28 19:13 UTC, merged

2020-12-08 04:12 UTC, SWDevAngel commented
@jasobrown Hi Jason. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)