roachprod: Make multiple set [provider]-zones always geo-distribute nodes
cockroachdb/cockroach pull request #43748
Opened 2020-01-06 18:58 UTC by jlinder

Before: if multiple zones were set for a provider and --geo wasn't set, all hosts
would be started in just one zone in one region.

Why change? Because if multiple zones are set, the intention is that they be
used.

Now:

1) when multiple zones are set in the CLI command, then --geo is assumed.
2) if no zones are set in the CLI command, then the value of --geo is followed.

Issue #38542.

Release note: None

2020-01-06 18:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43748)
<!-- Reviewable:end -->

2020-01-06 19:53 UTC, bobvawter commented
Looks like these changes conflict with some other flag-handling changes that just landed.

2020-01-06 21:44 UTC, jlinder commented
Ha. Such luck!

I've done the update. It's RFAL.

2020-01-06 22:15 UTC, ajwerner reviewed
If I read this change correctly it's going to massively change the behavior of roachprod for users which don't specify zones. Most users never specify any zones. There is an inbuilt assumption (perhaps bad) that if you don't specify geo you're going to get a cluster in us-east2 and if you do it's going to span us-west, us-east and eu-west (for AWS and equivalent for GCP). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43748#-:-Lxwv3i-AcGJDcLqnOVL:b-br63gz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @kenliu)



<!-- Sent from Reviewable.io -->

2020-01-06 23:25 UTC, jlinder commented
This PR doesn't change how --geo is applied when no zones are specified on the command line. It seems the PR and commit descriptions need to be more extensive in describing the new behavior.

Here are the combinations for how it works:

- if geo and zones are not set, then all nodes get placed in the same zone in one region
- if geo is set but zones aren't set, then the nodes are geo-distributed across us-west, us-east and eu-west
- if zones are set, then the nodes are distributed across the provided zones

I'll make the description updates.

Your question does bring up for me though that it would be good to communicate the change before I merge.

Also, are there any automated tasks that would need to be updated based on the new implementation? Or anything I should check?

2020-01-06 23:27 UTC, ajwerner reviewed
Check for uses of `create` in https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachtest

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43748#-:-LxxAbcqE-0Tx8Kwtwgl:b-d8her5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @kenliu)



<!-- Sent from Reviewable.io -->

2020-01-06 23:28 UTC, ajwerner reviewed
Seems like it should be alright. I think the thing I missed was that you're defaulting the zones to `[]string{}`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43748#-:-LxxB0vf15ZiEGPRZ2Io:bp4t9mh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @kenliu)



<!-- Sent from Reviewable.io -->

2020-01-07 14:53 UTC, bobvawter requested changes
Some nits:
  * The default value of `nil` is idiomatic for providing an empty slice value.  `cap(nil)==len(nil) == 0`
  * You can have the commit automatically close the issue when merged if you use `Fixes: #12345`.  There are also a number of synonyms: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
  * It would be nice to add a table to the roachprod readme showing the interplay of the various geo vs. zones options and where a user can expect nodes to be provisioned.

Changes to tools are usually announced with a note to the `eng@` mailing list and the `#engineering` channel.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43748#-:-Ly-Spo55DVZtQzVQdvh:btouk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kenliu)



<!-- Sent from Reviewable.io -->

2020-01-07 20:51 UTC, jlinder commented
This is RFAL.

I've updated to use `nil` instead of `[]string{}`, added `Fixes: ` to the PR description and commit message, updated the PR description and commit msg to fully explain the new use expectations, added some sections to the README for geo + zone flag expectations, and checked roachtest for how it uses `roachprod create` (it's always setting geo when specifying zones).

2020-01-07 20:54 UTC, bobvawter approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43748#-:-Ly0mSm1-OJhd57VMDTN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kenliu)



<!-- Sent from Reviewable.io -->

2020-01-07 20:57 UTC, jlinder commented
bors r+

2020-01-07 21:25 UTC, merged