ui: Upgrade React version and react-dependent libraries
cockroachdb/cockroach pull request #43846
Opened 2020-01-09 14:06 UTC by Koorosh

- Has to merged after: https://github.com/cockroachdb/cockroach/pull/43685
- Depends on https://github.com/cockroachdb/yarn-vendored/pull/13

With current changes, react is upgraded to latest version (16.12.0) and
following libraries are upgraded as well: react-redux, redux, redux-saga.
These upgrades of major versions has required to do some code adjustments
to properly migrate to newest versions.
- redux. Provide valid type arguments for Dispatch type.
- redux-saga. Changed import and usage of 'delay' function.
- react-redux. `connect` function failed to correctly resolve returned type
for `mapDispatchToProps` argument. As result it is provided as a function
instead of object argument. This hack allows implicitly resolve types.
- `CachedDataReducer` class is extended with one more optional type argument
to specify the list of allowed `actionNamespace` literals instead of `string`.
It was necessary to have strictly defined CachedDataReducer interface.
- `normalizeConnectedComponent` function is used to do simple mapping from
react's ExoticComponent to valid react component. This resolves issue of
providing ConnectedComponents (which are ExoticComponent's, not regular react
components) to Route component which has strict type validation of component types.

2020-01-09 14:07 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43846)
<!-- Reviewable:end -->

2020-01-09 14:09 UTC, Koorosh commented on pkg/ui/ccl/src/views/shared/containers/licenseSwap/index.tsx
> +  class LicenseSwap extends React.Component<TProps & OwnProps & any> {
Following hack with **&any** type is required to make changes related to types only and do not rewrite component logic.

2020-01-27 21:00 UTC, dhartunian requested changes
Thanks for this huge undertaking @Koorosh! My only major concern is whether the restructuring the `mapDispatchToProps` is necessary. See my comments for the approach I looked at.

2020-01-28 12:59 UTC, Koorosh commented on pkg/ui/src/views/cluster/containers/events/index.tsx
> +  () => ({
Agree. Removed unnecessary function wrappers across all project

2020-01-28 13:01 UTC, Koorosh commented on pkg/ui/src/redux/cachedDataReducer.ts
> +    return (dispatch: Dispatch<Action, TResponseMessage>, getState: () => S) => {
Awesome, it makes code much cleaner! Thanks!

2020-01-29 18:44 UTC, dhartunian approved these changes
👍 LGTM. Thanks for the updates!

2020-01-29 18:44 UTC, dhartunian commented
bors r+

2020-01-29 19:17 UTC, merged