colexec: reject aggregates with different input and output types
cockroachdb/cockroach pull request #43985
Opened 2020-01-14 23:47 UTC by yuzefovich

For MIN and MAX aggregate functions, `execinfrapb.GetAggregateInfo`
returns `INT` (i.e. `INT8`) as the return type for all integer types.
However, columnar operators will output the same physical type as their
input. This would lead to a panic of type mismatch, and it has been
fixed by rejecting such queries to run via the vectorized engine.
I believe only MIN and MAX on integer types were affected.

Fixes: #43936.

Release note (bug fix): Previously, an internal error could occur when
a query with an aggregate function MIN or MAX was executed via the
vectorized engine when the input column was either INT2 or INT4 type.
Now this is fixed.

2020-01-14 23:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/43985)
<!-- Reviewable:end -->

2020-01-15 15:45 UTC, asubiotto requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregator.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-LydrNUs4MfybEr65qFX:-LydrNUs4MfybEr65qFY:b61lun) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0a2dc6f180c84155f890c0a4901547adb52b03/pkg/sql/colexec/aggregator.go#L451)):*
> ```Go
> 	var inputType *types.T
> 	if len(inputTypes) > 0 {
> 		inputType = &inputTypes[0]
> ```

What of the other `inputTypes`? If this is only ever one type, I would keep the signature the same and pass it in to `GetAggregateInfo` that way.
___
*[pkg/sql/colexec/aggregator.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-Lydrj402LK7gDIswCgj:-Lydrj402LK7gDIswCgk:b-9h62ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0a2dc6f180c84155f890c0a4901547adb52b03/pkg/sql/colexec/aggregator.go#L481)):*
> ```Go
> 		return false, err
> 	}
> 	if typeconv.FromColumnType(retType) != outputTypes[0] {
> ```

Add a small comment about what this check is.


<!-- Sent from Reviewable.io -->

2020-01-15 18:30 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43985)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregator.go, line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-LydrNUs4MfybEr65qFX:-LyeRvkZAyFuPcsaNBtk:b-v0kinu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0a2dc6f180c84155f890c0a4901547adb52b03/pkg/sql/colexec/aggregator.go#L451)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What of the other `inputTypes`? If this is only ever one type, I would keep the signature the same and pass it in to `GetAggregateInfo` that way.
</blockquote></details>

Currently we only support aggregates with at most one argument, so other input types are ignored.

But I agree with your point that it seems weird taking in multiple input types and then using only one. Changed to "use" all of them (as it was the case before my refactor a month ago)
___
*[pkg/sql/colexec/aggregator.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-Lydrj402LK7gDIswCgj:-LyeT5OP2u7hV68yDL35:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0a2dc6f180c84155f890c0a4901547adb52b03/pkg/sql/colexec/aggregator.go#L481)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a small comment about what this check is.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-15 21:44 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-:-Lyf9Sgd2xmugMMMT1HN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregator.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-Lyf9GNACsihEkrr8wLZ:-Lyf9GNB23iUurWbHfKa:b-tsvc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8de9fde76aa354c0d55d9aa7c2c14b1e327c27/pkg/sql/colexec/aggregator.go#L448)):*
> ```Go
> 	aggFn execinfrapb.AggregatorSpec_Func, inputTypes []types.T,
> ) (bool, error) {
> 	aggType, err := typeconv.FromColumnTypes(inputTypes)
> ```

nit: `s/aggType/aggTypes/`


<!-- Sent from Reviewable.io -->

2020-01-15 21:55 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-:-LyfBzYt3EAbvn-QWMTL:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregator.go, line 448 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43985#-Lyf9GNACsihEkrr8wLZ:-LyfBxzJ9bPWXQMhHuGv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8de9fde76aa354c0d55d9aa7c2c14b1e327c27/pkg/sql/colexec/aggregator.go#L448)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/aggType/aggTypes/`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-15 23:27 UTC, yuzefovich commented
bors r+

2020-01-16 01:10 UTC, merged