colexec: add short-circuiting logic into projecting operators
cockroachdb/cockroach pull request #44126
Opened 2020-01-18 22:51 UTC by yuzefovich

Previously, all projecting operators (those that append columns) were
not allowed to short-circuit (i.e. to exit from Next() method) when they
receive a zero-length batch. The problem is that the planning code
assigns each operator an "output index" for the columns and operators
would only append a column if the width of the batch they receive equals
to their assigned output index. In case some projecting operator
short-circuits and doesn't append a column, the downstream operator
would also not append its output column which would lead to an internal
error.

The problem is solved by allowing operators to append as many "unknown"
zero-length columns until the batch becomes of the desired width and
then appending their output column. Now all projecting operators track
the status of whether the column was appended. In a case, when
a projecting operator that previously short-circuited wants to add
a column, but the width of the batch is higher than the operator's
output index (meaning that an "unknown" column was added in that place),
that "unknown" zero-length column is replaced with the full-sized column
of the desired type. All this logic is placed into the Allocator. This
behavior allows us to have short-circuiting logic in-place but also
reduces the amount of allocated memory (if a projecting operator
actually never outputs anything).

Additionally, coldata.ZeroBatch is now implemented by a special wrapper
around coldata.MemBatch that prohibits modifications of the zero batch.
This was prompted by a bug with merge joiner in which we relied on the
width of the zero batch to decide whether to unwrap a vector.

Release note: None

2020-01-18 22:51 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44126)
<!-- Reviewable:end -->

2020-01-18 22:51 UTC, yuzefovich commented
First 4 commits are in separate PRs.

2020-01-18 22:53 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lyur11U-BnT3LdiKn1e:-Lyur11V4pcrJ5soKnCh:bln12ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12ec00f02d9875caf7774f55d2ebc49c4ed76f9/pkg/sql/colexec/and_or_projection_tmpl.go#L112)):*
> ```Go
> func (o *_OP_LOWERProjOp) Next(ctx context.Context) coldata.Batch {
> 	batch := o.input.Next(ctx)
> 	origLen := batch.Length()
> ```

I wonder whether it'd be cleaner to compare the batch against `coldata.ZeroBatch` directly, instead of checking the length. I think it should now work.


<!-- Sent from Reviewable.io -->

2020-01-21 15:18 UTC, asubiotto requested changes
> Reviewed 4 of 19 files at r5, 16 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7_RO6CTAFo3RJ7pKX:-Lz7_RO7DDKzfquelAfA:bu87g75) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/col/coldata/batch.go#L45)):*
> ```Go
> 	// ReplaceCol replaces the current Vec at the provided index with the
> 	// provided Vec.
> 	ReplaceCol(Vec, int)
> ```

Does this need to be part of the interface? I would rather have it as a helper (if needed) that does: `Batch.ColVec(i).SetCol(Vec)`
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lyur11U-BnT3LdiKn1e:-Lz7bEyq0oHZ66t7ss61:b68vizf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12ec00f02d9875caf7774f55d2ebc49c4ed76f9/pkg/sql/colexec/and_or_projection_tmpl.go#L112)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I wonder whether it'd be cleaner to compare the batch against `coldata.ZeroBatch` directly, instead of checking the length. I think it should now work.
</blockquote></details>

I don't think so. I think `ZeroBatch` should just be considered a helper to signal the end of output. Operators shouldn't be constrained to only using `ZeroBatch` for this. A zero-length batch seems like a more useful general termination condition to check.
___
*[pkg/sql/colexec/colbatch_scan.go, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7c0kt0oQRjcJbLNDb:-Lz7c0kt0oQRjcJbLNDc:bzfbto5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7d75908f7aefb81637a2d0540d94d0efc27775/pkg/sql/colexec/colbatch_scan.go#L72)):*
> ```Go
> 		execerror.VectorizedInternalPanic(err)
> 	}
> 	bat.SetSelection(false)
> ```

Any reason this was removed?
___
*[pkg/sql/colexec/ordinality.go, line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7dzYX7Ms5-D-EEdYq:-Lz7dzYX7Ms5-D-EEdYr:bjddkbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/sql/colexec/ordinality.go#L58)):*
> ```Go
> 	}
> 	if c.ordinalityCol == ordinalityColIndexUnknown {
> 		c.ordinalityCol = bat.Width()
> ```

I find it a bit hard to reason about the fact that this will be the correct `ordinalityCol`. Could you add some commend to `MaybeAddColumn` on how to reason about the correctness of it in all cases?


<!-- Sent from Reviewable.io -->

2020-01-21 20:10 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7_RO6CTAFo3RJ7pKX:-Lz8gtHt3RKwwYedRuEQ:b-ni5zl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/col/coldata/batch.go#L45)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this need to be part of the interface? I would rather have it as a helper (if needed) that does: `Batch.ColVec(i).SetCol(Vec)`
</blockquote></details>

Added a helper.
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 112 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lyur11U-BnT3LdiKn1e:-Lz8gxTBBWhgQD4VFAJE:bigpj1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e12ec00f02d9875caf7774f55d2ebc49c4ed76f9/pkg/sql/colexec/and_or_projection_tmpl.go#L112)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think so. I think `ZeroBatch` should just be considered a helper to signal the end of output. Operators shouldn't be constrained to only using `ZeroBatch` for this. A zero-length batch seems like a more useful general termination condition to check.
</blockquote></details>

Ok, sounds good.
___
*[pkg/sql/colexec/colbatch_scan.go, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7c0kt0oQRjcJbLNDb:-Lz8h1xI13I3L0CaNnQG:bldvci0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7d75908f7aefb81637a2d0540d94d0efc27775/pkg/sql/colexec/colbatch_scan.go#L72)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Any reason this was removed?
</blockquote></details>

Because `cfetcher` can return `coldata.ZeroBatch` and we do not allow the modification of it.

This call wasn't necessary in the first place since `cfetcher` doesn't use selection vectors. Added a sanity check for that.
___
*[pkg/sql/colexec/ordinality.go, line 58 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7dzYX7Ms5-D-EEdYq:-Lz8hrvW8YL9vft1F-9E:byvv1vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/sql/colexec/ordinality.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I find it a bit hard to reason about the fact that this will be the correct `ordinalityCol`. Could you add some commend to `MaybeAddColumn` on how to reason about the correctness of it in all cases?
</blockquote></details>

As discussed in person, currently I think there is a bug here. This PR actually happens to fix it. I'll look into whether we can refactor `ordinalityOp` to know the output index during the planning stage and open a separate PR to address that.


<!-- Sent from Reviewable.io -->

2020-01-21 20:38 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-:-Lz8p-w47me5ArKS0DpE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-01-21 21:47 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7_RO6CTAFo3RJ7pKX:-Lz93IHO2MhA_g2umULu:bj0frva) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/col/coldata/batch.go#L45)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Added a helper.
</blockquote></details>

Actually `SetCol` and `SetNulls` is not sufficient - we also might need to change the type of the column, so we would need to introduce something like `SetType` into `coldata.Vec` interface. At this point I'd say that `ReplaceCol` should be introduced into `coldata.Batch` interface. Thoughts?


<!-- Sent from Reviewable.io -->

2020-01-21 21:48 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7_RO6CTAFo3RJ7pKX:-Lz93vQn-cZ6oWVcjuqP:bigpj1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/col/coldata/batch.go#L45)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually `SetCol` and `SetNulls` is not sufficient - we also might need to change the type of the column, so we would need to introduce something like `SetType` into `coldata.Vec` interface. At this point I'd say that `ReplaceCol` should be introduced into `coldata.Batch` interface. Thoughts?
</blockquote></details>

Ok, sounds good.


<!-- Sent from Reviewable.io -->

2020-01-21 22:28 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-:-Lz9Czdf2ttUj6Ns3XyG:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 45 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44126#-Lz7_RO6CTAFo3RJ7pKX:-Lz9Cx0M4e2T00-7f8yl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e56f6b4b037a74e4df1bab79354e38fa433f6d95/pkg/col/coldata/batch.go#L45)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Ok, sounds good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-21 23:15 UTC, merged