sql: optimize NeededColumnFamilyIDs
cockroachdb/cockroach pull request #44239
Opened 2020-01-22 22:58 UTC by solongordon

I made the logic for determining which column families need to be
scanned more clever in two ways:

- Previously we were always including column family 0 as a sentinel,
  since other column families have no KV entry if all their columns are
  null. This is not necessary if any of the column families being
  scanned have a NOT NULL column.
- If a needed column is indexed and not composite, it can be decoded
  from the key, so we don't need to take it into account when
  determining the needed column families.

Release note: None

2020-01-22 22:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44239)
<!-- Reviewable:end -->

2020-01-22 22:58 UTC, solongordon commented
This needs tests but is ready for an initial look if you're interested.

2020-01-23 00:05 UTC, nvb reviewed
Very nice! Thanks for putting this together so fast.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-:-LzEhvPm1aM5qXgCGpch:bentite)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/sqlbase/index_encoding.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEet8VDdhbrnsRn_8p:-LzEet8W2723m_INl6jr:b-9d4ob1) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L243)):*
> ```Go
> 
> // NeededColumnFamilyIDs returns the minimal set of column families required to
> // retrieve neededCols for the specified table and index.
> ```

Make a note that the returned column families are in sorted order.
___
*[pkg/sql/sqlbase/index_encoding.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEfDqO6GVVWkNHvqC_:-LzEfDqO6GVVWkNHvqCa:b-2qgaay) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L266)):*
> ```Go
> 	// Iterate over the column families to find which ones contain needed
> 	// columns. We also keep track of whether all of the needed family columns are
> 	// nullable, since this means we need column family 0 as a sentinel.
> ```

"as a sentinel, regardless of whether any of the columns in it are needed"
___
*[pkg/sql/sqlbase/index_encoding.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgC0B6ieZ_4BnfPHu:-LzEgC0B6ieZ_4BnfPHv:b-gmasmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L292)):*
> ```Go
> 		if needed {
> 			neededFamilyIDs = append(neededFamilyIDs, family.ID)
> 			if !nullable || family.ID == 0 {
> ```

nit: I'd set `nullable == false` in the `if family.ID == 0 {` branch. You'll need to move up the two bool declarations.
___
*[pkg/sql/sqlbase/index_encoding.go, line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgfKCBo5PIp5V6Q1f:-LzEgfKCBo5PIp5V6Q1g:b6pq99c) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L301)):*
> ```Go
> 	}
> 
> 	// If all the needed families are nullable, we need family 0 as a sentinel.
> ```

Add a note that we'll never enter this branch if family 0 is already in `neededFamilyIDs`.
___
*[pkg/sql/sqlbase/index_encoding.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgpYx7F0gKcG--CSX:-LzEgpYx7F0gKcG--CSY:b-80fjux) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L303)):*
> ```Go
> 	// If all the needed families are nullable, we need family 0 as a sentinel.
> 	if allFamiliesNullable {
> 		return append([]FamilyID{0}, neededFamilyIDs...)
> ```

Let's avoid the extra allocation, since this one is easy to avoid:
```go
if allFamiliesNullable {
	// Prepend family 0.
	neededFamilyIDs = append(neededFamilyIDs, 0)
	copy(neededFamilyIDs[1:], neededFamilyIDs)
	neededFamilyIDs[0] = family0.ID
}
```


<!-- Sent from Reviewable.io -->

2020-01-23 05:45 UTC, rohany requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/sqlbase/index_encoding.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzFuwOmElXXuTAIp9Qu:-LzFuwOn2eNNmNsXtbpu:bujkv65) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L279)):*
> ```Go
> 		for _, columnID := range family.ColumnIDs {
> 			columnOrdinal := colIdxMap[columnID]
> 			// We need this column family if it includes a needed column, unless that
> ```

This is a bit awkward, due to where we place the composite columns in primary vs secondary indexes (sorry):

If an index is the primary index, or is a secondary index _encoded like a primary index_ (i.e. using the primary index encoding), then the composite value is included in the family that the column is in.

If an index is using the secondary index encoding, then composite values are always included in family 0.


<!-- Sent from Reviewable.io -->

2020-01-23 15:32 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/sqlbase/index_encoding.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEet8VDdhbrnsRn_8p:-LzHrZQP1wxmZbXjsoF_:b-vb5a2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note that the returned column families are in sorted order.
</blockquote></details>

Does that mean it's guaranteed that `table.Families` is in sorted order? I don't see any reason it shouldn't be, but I was trying to avoid that assumption just in case.
___
*[pkg/sql/sqlbase/index_encoding.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEfDqO6GVVWkNHvqC_:-LzHtA4i0ZbdK4DIFWiX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L266)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"as a sentinel, regardless of whether any of the columns in it are needed"
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzFuwOmElXXuTAIp9Qu:-LzHsKkh1ZKsAi3T0UKf:b-yuxrxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L279)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This is a bit awkward, due to where we place the composite columns in primary vs secondary indexes (sorry):

If an index is the primary index, or is a secondary index _encoded like a primary index_ (i.e. using the primary index encoding), then the composite value is included in the family that the column is in.

If an index is using the secondary index encoding, then composite values are always included in family 0.
</blockquote></details>

Thank you, I suspected I didn't get this quite right. (As usual I couldn't find this in `encoding.md` but now I see that it's there.)
___
*[pkg/sql/sqlbase/index_encoding.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgC0B6ieZ_4BnfPHu:-LzHt1yU441dcU1P5x0l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L292)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I'd set `nullable == false` in the `if family.ID == 0 {` branch. You'll need to move up the two bool declarations.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgfKCBo5PIp5V6Q1f:-LzHtmtT-cjvh9nNhpOs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L301)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a note that we'll never enter this branch if family 0 is already in `neededFamilyIDs`.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEgpYx7F0gKcG--CSX:-LzHtw0CEGGjc591lXaF:b-x3zn47) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L303)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's avoid the extra allocation, since this one is easy to avoid:
```go
if allFamiliesNullable {
	// Prepend family 0.
	neededFamilyIDs = append(neededFamilyIDs, 0)
	copy(neededFamilyIDs[1:], neededFamilyIDs)
	neededFamilyIDs[0] = family0.ID
}
```
</blockquote></details>

:thumbsup: Done.


<!-- Sent from Reviewable.io -->

2020-01-23 15:33 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/sqlbase/index_encoding.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzFuwOmElXXuTAIp9Qu:-LzI1IhcDss1r1pBiO_S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L279)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Thank you, I suspected I didn't get this quite right. (As usual I couldn't find this in `encoding.md` but now I see that it's there.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-23 15:52 UTC, rohany requested changes
This logic is p tricky, so lets get some tests on it

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-:-LzI5Pnu2XNZyUMkhbBj:b-ee8vzk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @rohany, and @solongordon)

___
*[pkg/sql/sqlbase/index_encoding.go, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI3pXp3mXeE8qRzpg5:-LzI3pXp3mXeE8qRzpg6:b-ann3am) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L284)):*
> ```Go
> 			// Set column family 0 aside in case we need it as a sentinel.
> 			family0 = family
> 			if index.EncodingType == SecondaryIndexEncoding && compositeNeeded {
> ```

You actually need to check if the index is not the primary index here and that the encoding type is SecondaryIndexEncoding. That field is only populated on secondary indexes (is there a way to make this more clear? I'm worried this will lead to some bugs in the future)
___
*[pkg/sql/sqlbase/index_encoding.go, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI4NNf5Y4Onq0FepHt:-LzI4NNf5Y4Onq0FepHu:bz833nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L291)):*
> ```Go
> 		}
> 		for _, columnID := range family.ColumnIDs {
> 			if needed && !nullable {
> ```

could we move this outside of the loop?
___
*[pkg/sql/sqlbase/index_encoding.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI4dgQ4mtqhhh189KV:-LzI4dgQ4mtqhhh189KW:b6mbv7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L300)):*
> ```Go
> 			// composite.
> 			if neededCols.Contains(columnOrdinal) &&
> 				(!indexedIDs.Contains(int(columnID)) || compositeIDs.Contains(int(columnID))) {
> ```

don't we need to only check the composite here if the index is a primary index? Otherwise we might erroneously generate spans for secondary indexes with composite columns (even though we already included family 0)


<!-- Sent from Reviewable.io -->

2020-01-28 21:32 UTC, solongordon reviewed
Still iterating on getting existing logic tests to pass, then will add more of my own. I'll comment when this is ready for another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-:-Lzi3P6I1suLk4PjdVS4:bec0z1s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/sqlbase/index_encoding.go, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI3pXp3mXeE8qRzpg5:-LzI6T8KA6aCZCtp7kFa:bz4z2cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L284)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

You actually need to check if the index is not the primary index here and that the encoding type is SecondaryIndexEncoding. That field is only populated on secondary indexes (is there a way to make this more clear? I'm worried this will lead to some bugs in the future)
</blockquote></details>

Ooh that is tricky. I made a bad assumption that `PrimaryIndexEncoding` was the zero value.
___
*[pkg/sql/sqlbase/index_encoding.go, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI4NNf5Y4Onq0FepHt:-LzcdIEO1cCyzMT_aRkY:ba34mqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L291)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

could we move this outside of the loop?
</blockquote></details>

We could, but it allows exiting the loop early in some cases.
___
*[pkg/sql/sqlbase/index_encoding.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI4dgQ4mtqhhh189KV:-LzcdR_W6WLXtD2svzTA:byvyago) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L300)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

don't we need to only check the composite here if the index is a primary index? Otherwise we might erroneously generate spans for secondary indexes with composite columns (even though we already included family 0)
</blockquote></details>

Yes. Done.


<!-- Sent from Reviewable.io -->

2020-02-04 17:49 UTC, solongordon commented
Getting closer to making existing tests pass. I was previously not handling mutation columns, which got caught by `TestOperationsWithColumnAndIndexMutation`. And some logic tests now need hard-coded column family definitions, mainly so that EXPLAIN output is predictable.

2020-02-05 23:11 UTC, solongordon commented
This should be ready for another look. This function has turned into a bit of a monster and I'd welcome suggestions for making it more efficient. I've mostly been focusing on correctness.

2020-02-05 23:12 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/sqlbase/index_encoding.go, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzI3pXp3mXeE8qRzpg5:-M-Mc1af9XW2U9tszQrA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/367426e9d1b2a5a8e30ffa6798682740d12791fa/pkg/sql/sqlbase/index_encoding.go#L284)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ooh that is tricky. I made a bad assumption that `PrimaryIndexEncoding` was the zero value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-05 23:30 UTC, rohany commented on pkg/sql/sqlbase/index_encoding.go
> +	columns := table.ColumnsWithMutations(true)
The `SpanBuilder` could cache these structures on creation of the object and pass them through to here.

2020-02-05 23:30 UTC, rohany commented on pkg/sql/sqlbase/index_encoding.go
> +			neededCols.Remove(columnOrdinal)
are you allowedto remove stuff while iterating over the object?

2020-02-05 23:30 UTC, rohany commented on pkg/sql/sqlbase/index_encoding.go
> +		if compositesInFamily0 && compositeCols.Contains(columnOrdinal) ||
can you add a comment here about this case?

2020-02-06 03:41 UTC, nvb reviewed
> Reviewed 1 of 1 files at r2, 11 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @rohany, and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/family, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-NXDSM00aTvmyS2thh:-M-NXDSM00aTvmyS2thi:bgnqvfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/logictest/testdata/logic_test/family#L337)):*
> ```
> 
> query TT
> SELECT field, description FROM [EXPLAIN SELECT c FROM t1 WHERE a = 10] WHERE field IN ('table', 'spans')
> ```

Does `SELECT d from t1 WHERE a = 10` result in two distinct scans instead of a single scan over two families? If so, could you add that case as well?
___
*[pkg/sql/sqlbase/index_encoding.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzEet8VDdhbrnsRn_8p:-LzIGiUS5kl8f4cQS-Tb:b-pt1i6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/40cc4744eae355b849d9156a37a269d94843ecaa/pkg/sql/sqlbase/index_encoding.go#L243)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Does that mean it's guaranteed that `table.Families` is in sorted order? I don't see any reason it shouldn't be, but I was trying to avoid that assumption just in case.
</blockquote></details>

That's a good question. I'm not sure, but we seem to rely on this assumption in callers of this function, at least in order to merge spans. We shouldn't say it if it's not true, but I suspect you're right about `table.Families`, so maybe we're missing documentation on that slice as well.
___
*[pkg/sql/sqlbase/structured.go, line 3230 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-NZfKu01RRew1_zmxX:-M-NZfKu01RRew1_zmxY:bf9gb7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/structured.go#L3230)):*
> ```Go
> // mutation columns.
> func (desc *TableDescriptor) ColumnsWithMutations(mutations bool) []*ColumnDescriptor {
> 	nCols := len(desc.Columns)
> ```

If we're willing to switch the return type to `[]ColumnDesciptor` then we can avoid allocating a new slice in what I expect is the overwhelmingly common case where `!mutations || len(desc.Mutations) == 0` with something like:
```go
nCols := len(desc.Columns)
columns := desc.Columns[:nCols:nCols]
if mutations {
    for i := range desc.Mutations {
        if col := desc.Mutations[i].GetColumn(); col != nil {
            columns = append(columns, col)
        }
    }
}
return columns
```


<!-- Sent from Reviewable.io -->

2020-02-06 17:14 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/family, line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-NXDSM00aTvmyS2thh:-M-QPgtFAF4ZrJVKnFsJ:b69hoj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/logictest/testdata/logic_test/family#L337)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does `SELECT d from t1 WHERE a = 10` result in two distinct scans instead of a single scan over two families? If so, could you add that case as well?
</blockquote></details>

That particular query only needs to scan column family 0, but I know what you mean. Added a test case.
___
*[pkg/sql/sqlbase/index_encoding.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzETaQbAKsF8g9-D5nG-r3-252:-M-QMu0K6go_MBK2uZH1:b-x5evlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/index_encoding.go#L252)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

The `SpanBuilder` could cache these structures on creation of the object and pass them through to here.
</blockquote></details>

Good idea. I'm going to save this for a follow-up PR if that's ok with you.
___
*[pkg/sql/sqlbase/index_encoding.go, line 288 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzETaQbAKsF8g9-D5nG-r3-288:-M-Q-UEW25XrrKc2xs3T:bpx91g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/index_encoding.go#L288)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

are you allowedto remove stuff while iterating over the object?
</blockquote></details>

Good point. It seems like yes but I agree it's dangerous to rely on that since `ForEach` doesn't make it explicit. Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzETaQbAKsF8g9-D5nG-r3-290:-M-Q-DpY3BGcLosCexIE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/index_encoding.go#L290)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

can you add a comment here about this case?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 3230 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-NZfKu01RRew1_zmxX:-M-QPubl845IE9zS3gEv:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/structured.go#L3230)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're willing to switch the return type to `[]ColumnDesciptor` then we can avoid allocating a new slice in what I expect is the overwhelmingly common case where `!mutations || len(desc.Mutations) == 0` with something like:
```go
nCols := len(desc.Columns)
columns := desc.Columns[:nCols:nCols]
if mutations {
    for i := range desc.Mutations {
        if col := desc.Mutations[i].GetColumn(); col != nil {
            columns = append(columns, col)
        }
    }
}
return columns
```
</blockquote></details>

Good point, done.


<!-- Sent from Reviewable.io -->

2020-02-06 18:07 UTC, rohany approved these changes
LGTM aside from nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-:-M-Qfs8l38HMUkNKLvgK:b-td3wvi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @solongordon)

___
*[pkg/sql/sqlbase/index_encoding.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-LzETaQbAKsF8g9-D5nG-r3-252:-M-QfVui0CnwJ_vfeXds:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c17dcd0245b1690577c8de74522929fc24a4e459/pkg/sql/sqlbase/index_encoding.go#L252)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Good idea. I'm going to save this for a follow-up PR if that's ok with you.
</blockquote></details>

Sounds good
___
*[pkg/sql/sqlbase/index_encoding.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-Qfa1U5rdVposbT9nu:-M-Qfa1U5rdVposbT9nv:b-mkap4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3bd5db61ab2a39c925a6d09493c0cefa4403c18/pkg/sql/sqlbase/index_encoding.go#L274)):*
> ```Go
> 	// columns which are not indexed.)
> 	var family0 *ColumnFamilyDescriptor
> 	hasSecondaryEncoding := index.ID != table.PrimaryIndex.ID &&
> ```

nit -- maybe we could move this into a function on the index descriptor? I've had to do this in some places as well, it would be a good idea to centralize it.


<!-- Sent from Reviewable.io -->

2020-02-06 19:48 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44239)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rohany)

___
*[pkg/sql/sqlbase/index_encoding.go, line 274 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44239#-M-Qfa1U5rdVposbT9nu:-M-R1qJQ8i1NXdlhC3gW:b-aqimct) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3bd5db61ab2a39c925a6d09493c0cefa4403c18/pkg/sql/sqlbase/index_encoding.go#L274)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

nit -- maybe we could move this into a function on the index descriptor? I've had to do this in some places as well, it would be a good idea to centralize it.
</blockquote></details>

Ah, yeah I had the same thought. Done.


<!-- Sent from Reviewable.io -->

2020-02-11 20:51 UTC, solongordon commented
bors r+

2020-02-11 21:41 UTC, merged