sql: Role management, CREATEROLE privilege
cockroachdb/cockroach pull request #44232
Opened 2020-01-22 22:22 UTC by RichardJCai

Added role management via CREATEROLE privilege

Release note:
Modified CREATE ROLE to add "CREATEROLE" option. Added ALTER ROLE command.
Added CREATEROLE privilege - managed by choosing options when CREATING and ALTERING role.
Example: CREATE ROLE "role" WITH CREATEROLE"

Only users with CREATEROLE privilege are able to CREATE and ALTER roles and users. Granting roles remains unchanged.

2020-01-22 22:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44232)
<!-- Reviewable:end -->

2020-01-27 15:32 UTC, solongordon requested changes
Nice start! I took a first pass and left some thoughts.

One thing we'll need to think carefully about is how to handle clusters which are upgrading from v19.2. We'll at least need a migration which adds the new `hasCreateRole` column. But we also need to make sure the new node isn't trying to use the new column before the migration runs.

Also, once you have this working, we should evaluate whether a boolean column for each role-level permission is actually what we want or if we'd prefer to have a single column which will hold all future permissions as well.

> Reviewed 26 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-Lzbai3e57VSjnkWKCOg:b-vuaidp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/.DS_Store, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbFUsAE9fKkai3B2wh:-LzbFUsAE9fKkai3B2wi:b-z8tdym) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/.DS_Store#L0)):*
You should add `.DS_Store` and similar files to your global `.gitignore` in your home directory. Here's the one I use: https://gist.github.com/octocat/9257657
___
*[pkg/sql/alter_role.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbTJ3-E0u9xOGDYvjy:-LzbTJ3-E0u9xOGDYvjz:bly2md8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L38)):*
> ```Go
> 	// Note that for Postgres, only superuser can ALTER another superuser
> 	// CockroachDB does not support superuser privilege right now
> 	// However we make it so the admin role cannot be edited (done in startExec)
> ```

Nit: Please add periods after sentences in comments.
___
*[pkg/sql/alter_role.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbTQ-32zmZvyTfttd0:-LzbTQ-32zmZvyTfttd1:b2w2808) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L64)):*
> ```Go
> 
> // alterRoleRun is the run-time state of
> // alterRoleRun	 for local execution.
> ```

Nit: Weird line break and extra spaces.
___
*[pkg/sql/alter_role.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbVAQB1NXIQoNUKZRB:-LzbVAQB1NXIQoNUKZRC:btquz6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L78)):*
> ```Go
> 	}
> 	if name == "admin" {
> 		return errors.New("cannot edit admin role")
> ```

Do you think there would be an appropriate `pgcode` to return here?
___
*[pkg/sql/alter_role.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbUSQn2GXO3uljPFLu:-LzbUSQn2GXO3uljPFLv:b-ddg6x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L96)):*
> ```Go
> 		`UPDATE system.users SET "hasCreateRole" = $2 WHERE username = $1`,
> 		normalizedUsername,
> 		rolePrivilegeBits&roleprivilege.CREATEROLE.Mask() != 0,
> ```

I'm not sure this is quite right, especially if we add more role-level permissions. For instance imagine we also add support for `CREATEDB`/`NOCREATEDB`. If someone runs `ALTER ROLE foo WITH CREATEDB` on a role which already has `CREATEROLE`, it doesn't mean we should revoke `CREATEROLE`.
___
*[pkg/sql/alter_role.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbV4-A5DNyOLTH24eG:-LzbV4-A5DNyOLTH24eH:b5rdwx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L105)):*
> ```Go
> 			"user %s does not exist", name)
> 	}
> 	return err
> ```

While this is technically correct it would be clearer to say `return nil`.
___
*[pkg/sql/authorization.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbWi8L8U_dTJQCt57w:-LzbWi8L8U_dTJQCt57x:b-c41b26) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L288)):*
> ```Go
> func (p *planner) HasCreateRolePrivilege(ctx context.Context) error {
> 	user := p.SessionData().User
> ```

Probably want to return true immediately if the user is `root` or `node`, just like in `HasAdminRole`.
___
*[pkg/sql/authorization.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbWNqpCQjW55zMwYp0:-LzbWNqpCQjW55zMwYp1:b13vcsd) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L289)):*
> ```Go
> 	user := p.SessionData().User
> 
> 	// Expand role memberships
> ```

Nit: Add a period please.
___
*[pkg/sql/authorization.go, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbXEHJ9f9iEFQ990cT:-LzbXEHJ9f9iEFQ990cU:bicq4ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L296)):*
> ```Go
> 
> 	// Iterate over the roles that 'user' is a member of.
> 	// Check for hasCreateRole permission
> ```

Nit: Add a period please. Also, you don't need a line break between sentences.
___
*[pkg/sql/authorization.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbY74y8lLNrEG0Q8R_:-LzbY74y8lLNrEG0Q8Ra:brsvjiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L298)):*
> ```Go
> 	// Check for hasCreateRole permission
> 	hasCreateRole := false
> 	for role := range memberOf {
> ```

Rather than looping and running many queries, I think we should be able to accomplish this in a single query. Could you try writing a query which joins `system.role_members` and `system.users` to check if any of the roles a user belongs to has `hasCreateRole`?
___
*[pkg/sql/authorization.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbXLzrAX1BhFq5DTN8:-LzbXLzrAX1BhFq5DTN9:bsl8ej1) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L308)):*
> ```Go
> 
> 		if len(hasCreateRoleRows) != 0 {
> 			hasCreateRole = true
> ```

Why not return true immediately?
___
*[pkg/sql/create_user.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_41c-qwDt_5SMeNY:-Lzb_41c-qwDt_5SMeNZ:b7ghqg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/create_user.go#L31)):*
> ```Go
> 	ifNotExists   bool
> 	isRole        bool
> 	hasCreateRole bool
> ```

In `CreateRole` and `AlterRole` you have `rolePrivileges roleprivilege.List` here, which I think is nicer.
___
*[pkg/sql/user.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_WuR0mCiTy7nzOAp:-Lzb_WuR0mCiTy7nzOAq:bmv7m2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/user.go#L101)):*
> ```Go
> 	err = runFn(func(ctx context.Context) error {
> 		const getHashedPassword = `SELECT "hashedPassword" FROM system.users ` +
> 			`WHERE username=$1 AND "isRole" = false AND "hasCreateRole" = false`
> ```

Wait, why did this change?
___
*[pkg/sql/logictest/logic.go, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_eCC3D7v6Yq4twue:-Lzb_eCC3D7v6Yq4twuf:byk66ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c85e8fa76616efbb5d13b11adaf451c6160b41/pkg/sql/logictest/logic.go#L547)):*
> ```Go
> 		"local",
> 		"local-vec-off",
> 		"local-vec",
> ```

Assuming you didn't mean to check in this change.
___
*[pkg/sql/parser/sql.y, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbQsMqCsfa1zHomqLq:-LzbQsMqCsfa1zHomqLr:b-7aiyu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L34)):*
> ```Yacc
>     "github.com/ [...]

2020-01-27 15:34 UTC, solongordon reviewed
Also, when you have a moment please read over our commit message guidelines here: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-LzbcawW86jxbic3n81n:b-9lngew)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)



<!-- Sent from Reviewable.io -->

2020-01-28 16:57 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/.DS_Store, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbFUsAE9fKkai3B2wh:-Lzh3CrG3Klx97RzqR3a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/.DS_Store#L)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

You should add `.DS_Store` and similar files to your global `.gitignore` in your home directory. Here's the one I use: https://gist.github.com/octocat/9257657
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbVAQB1NXIQoNUKZRB:-Lzh3GeqDUR49mQCaiQO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L78)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Do you think there would be an appropriate `pgcode` to return here?
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbUSQn2GXO3uljPFLu:-Lzh3HyZ6rUUkIHEXQEj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L96)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm not sure this is quite right, especially if we add more role-level permissions. For instance imagine we also add support for `CREATEDB`/`NOCREATEDB`. If someone runs `ALTER ROLE foo WITH CREATEDB` on a role which already has `CREATEROLE`, it doesn't mean we should revoke `CREATEROLE`.
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbV4-A5DNyOLTH24eG:-Lzh3IeK0kvCEoyH9O15:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/alter_role.go#L105)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

While this is technically correct it would be clearer to say `return nil`.
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbWi8L8U_dTJQCt57w:-Lzh3Jyd3QsPoWTRk3eI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L288)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Probably want to return true immediately if the user is `root` or `node`, just like in `HasAdminRole`.
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbY74y8lLNrEG0Q8R_:-Lzh3MDm7BhogGesqfB0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L298)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Rather than looping and running many queries, I think we should be able to accomplish this in a single query. Could you try writing a query which joins `system.role_members` and `system.users` to check if any of the roles a user belongs to has `hasCreateRole`?
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbXLzrAX1BhFq5DTN8:-Lzh3MfcDLtn5Jw4qjny:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/authorization.go#L308)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why not return true immediately?
</blockquote></details>

Done.
___
*[pkg/sql/create_user.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_41c-qwDt_5SMeNY:-Lzh3OIiC9mETx7eC0_n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/create_user.go#L31)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

In `CreateRole` and `AlterRole` you have `rolePrivileges roleprivilege.List` here, which I think is nicer.
</blockquote></details>

Done.
___
*[pkg/sql/user.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_WuR0mCiTy7nzOAp:-Lzh3QEk4WRPT_KmASyJ:b4nrq8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/user.go#L101)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Wait, why did this change?
</blockquote></details>

I think I changed it because I was getting the fakeSpanResolver error again. 
Although the logic here does make since since this is specifically looking up a user.
___
*[pkg/sql/logictest/logic.go, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_eCC3D7v6Yq4twue:-Lzh3epZ8bjgLsc_zP3e:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c85e8fa76616efbb5d13b11adaf451c6160b41/pkg/sql/logictest/logic.go#L547)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Assuming you didn't mean to check in this change.
</blockquote></details>

Yep.
___
*[pkg/sql/parser/sql.y, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbQsMqCsfa1zHomqLq:-Lzh3hz112KwfWOBCwG-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L34)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

It's a good habit to update `parse_test.go` whenever you add new syntax to `sql.y`.
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 5123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbPTjR54vzFLAmGfa_:-Lzh3j0w0fR84x6tOFOe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L5123)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Looks like the WITH is optional in Postgres so we might as well mimic that.
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 5176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbL-JNDD8SnkikYno_:-Lzh3js05zBYfmg-q9hs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L5176)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Why not just `$$.val = tree.NameList{tree.Name($1)}`?
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 5188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbKx3vCLLm9F1uerm-:-Lzh3kTbD9IOOwJfosl-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L5188)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Looks like some tabs snuck in here.

Also could you do something simpler here, like what `privilege_list` does?
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 10044 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-LzbFwMTDkd4ZDVo-qbN:-Lzh3lq74zG_x-DFIRJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/parser/sql.y#L10044)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

The comment block above says "NEVER ADD KEYWORDS HERE". So let's not. Is there a reason you wanted to make `CREATEROLE` a reserved keyword but `NOCREATEROLE` unreserved?
</blockquote></details [...]

2020-02-03 19:56 UTC, solongordon requested changes
> Reviewed 25 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/authorization.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BS5pr4AWBEy3yD4Kv:-M-BS5pr4AWBEy3yD4Kw:bs9touj) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L305)):*
> ```Go
> 
> 	// Create list of roles for sql WHERE IN clause.
> 	memberOf, err := p.MemberOfWithAdminOption(ctx, normalizedName)
> ```

Missing an error check here?
___
*[pkg/sql/authorization.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BQcddDgz_pvs0k5GW:-M-BQcddDgz_pvs0k5GX:b-6f0xhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L312)):*
> ```Go
> 	}
> 
> 	sqlRoleList := fmt.Sprintf("(%s)", strings.Join(roles, ","))
> ```

I think instead of constructing your own IN via string processing, you can make an array and pass it via `WHERE hasCreateRole = ANY($1)`, which is probably preferable. See an example here: https://github.com/cockroachdb/cockroach/blob/4ec5929a08687b82b05ef80231fddd0d53421973/pkg/jobs/registry.go#L478
___
*[pkg/sql/create_user.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_41c-qwDt_5SMeNY:-M-BSIo-7VitYgGAYyXC:bhdfcsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/create_user.go#L31)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Any reason this field is exported (starts with a capital) while the other ones aren't?
___
*[pkg/sql/create_user.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSXVG834y9azPjSj3:-M-BSXVG834y9azPjSj4:b-tc40ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/create_user.go#L38)):*
> ```Go
> }
> 
> var userTableName = tree.NewTableName("system", "users").String()
> ```

Did you really need to add `.String()` here? If it's just being used for `%s` replacements, `.String()` should get called automatically.
___
*[pkg/sql/create_user.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSgM7-ewAVcSev7-7:-M-BSgM7-ewAVcSev7-8:b6hv5k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/create_user.go#L45)):*
> ```Go
> //          as well, but disallow password authentication for these users.
> func (p *planner) CreateUser(ctx context.Context, n *tree.CreateUser) (planNode, error) {
> 	return p.CreateUserNode(ctx, n.Name, n.Password, n.IfNotExists, false /* isRole */, "CREATE USER", nil)
> ```

Nit: Avoid lines over 100 chars.
___
*[pkg/sql/create_user.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BRjEQ-4Ksh1ynt4zV:-M-BRjEQ-4Ksh1ynt4zW:b3cbaey) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c85e8fa76616efbb5d13b11adaf451c6160b41/pkg/sql/create_user.go#L133)):*
> ```Go
> 		opName,
> 		params.p.txn,
> 		"insert into system.users values ($1, $2, $3)",
> ```

This worries me. It looks like this query is going to fail on v19.2 nodes after your migration gets run, because it will be trying to insert three values into a four column table. Could you check if that's the case?
___
*[pkg/sql/user.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_WuR0mCiTy7nzOAp:-M-BbvtA3slHsa37WABq:b-sx5eif) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/user.go#L101)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think I changed it because I was getting the fakeSpanResolver error again. 
Although the logic here does make since since this is specifically looking up a user.
</blockquote></details>

Probably doesn't hurt anything, but let's not change it if we don't have to. I'll merge my PR for fixing the fakeSpanResolver issue momentarily.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSv31EO94c49BHRWj:-M-BSv31EO94c49BHRWk:b-kcpav) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/logictest/testdata/logic_test/fk#L621)):*
> ```
> FKScan /Table/88/3/100/"one"{-/#}
> FKScan /Table/89/3/100/"one"{-/#}
> FKScan /Table/90/2/100/"one"{-/PrefixEnd}
> ```

I'm surprised these table IDs changed since nothing else in the file did. :thinking: 
___
*[pkg/sql/parser/parse_test.go, line 2040 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BT7R0AVwHtvjPcGcC:-M-BT7R0AVwHtvjPcGcD:b20c87b) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/parse_test.go#L2040)):*
> ```Go
> 			`ALTER ROLE 'foo' CREATEROLE`},
> 		{`ALTER ROLE foo NOCREATEROLE`,
> 			`ALTER ROLE 'foo' NOCREATEROLE`},
> ```

Nit: I don't think it's necessary to test these all with both `CREATEROLE` and `NOCREATEROLE`. You can pick one or the other.
___
*[pkg/sql/parser/sql.y, line 5192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BXp9wD-0NA9gZD7YJ:-M-BXp9wD-0NA9gZD7YK:bsz9z7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/sql.y#L5192)):*
> ```Yacc
> 		}
> 	 	$$.val = rolePrivList
> 	}
> ```

Mixture of tabs and spaces here.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYwqrE76H2-Hd_eUF:-M-BYwqrE76H2-Hd_eUG:bgiqqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L1)):*
> ```Go
> // Copyright 2015 The Cockroach Authors.
> ```

Old copyright. :)
___
*[pkg/sql/roleprivilege/role_privilege.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYzRv0xTiraHJtdaz:-M-BYzRv0xTiraHJtdb-:b7o1hsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package roleprivilege
> ```

I need to think more about this but I wonder if we can make this package's interface clearer. A few things I'm thinking about:
- I'm not convinced the BitField stuff is buying us much here, and it's not ideal that callers need to be aware of it rather than it just being an implementation detail.
- I would try not to export anything which isn't needed outside the package, like `MapToSQLColumn` for instance.
- I wonder if we can pull more of the functionality for setting and getting these privileges into this package for better encapsulation.

I'll think more about this but I would encourage you to think about what functionality callers actually need when it comes to role privileges. Then try and design a clear and compact interface which serves those needs, and hide everything else.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-Ba-Rx55rjN27j5394:-M-Ba-Ry8XVDbpWxxzOG:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L42)):*
> ```Go
> 
> // ByValue is just an array of role privilege kinds sorted by value.
> var ByValue = [...]Kind{
> ```

Unused
___
*[pkg/sql/roleprivilege/role_privilege.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-Ba30wCoqQjVBB6BSK:-M-Ba30wCoqQjVBB6BSL:bksc84f) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/ro [...]

2020-02-03 22:43 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/authorization.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BS5pr4AWBEy3yD4Kv:-M-BuyblAsd28jD7jXdc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L305)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Missing an error check here?
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BQcddDgz_pvs0k5GW:-M-C3-J1DDfHYNf-51nN:b-427qf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L312)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think instead of constructing your own IN via string processing, you can make an array and pass it via `WHERE hasCreateRole = ANY($1)`, which is probably preferable. See an example here: https://github.com/cockroachdb/cockroach/blob/4ec5929a08687b82b05ef80231fddd0d53421973/pkg/jobs/registry.go#L478
</blockquote></details>


For this, the array has to be a DArray - the underlying Array inside DArray is of type Datums, to do this we would have to convert the String into Datum type and create this DArray (DArray has it's own String format which allows this query to work). A regular slice can't be passed in to this query.

Would this be preferable to doing my own String construction here.
___
*[pkg/sql/create_user.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_41c-qwDt_5SMeNY:-M-BvrkiAgsQ59GPdoY9:bspem3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/create_user.go#L31)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Any reason this field is exported (starts with a capital) while the other ones aren't?
</blockquote></details>

Nope, fixed.
___
*[pkg/sql/create_user.go, line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSXVG834y9azPjSj3:-M-BwCYnB8-nhJrJlQNN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/create_user.go#L38)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Did you really need to add `.String()` here? If it's just being used for `%s` replacements, `.String()` should get called automatically.
</blockquote></details>

Done.
___
*[pkg/sql/create_user.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BRjEQ-4Ksh1ynt4zV:-M-BwIqG4JkC1W5G7mzL:bbd1138) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c85e8fa76616efbb5d13b11adaf451c6160b41/pkg/sql/create_user.go#L133)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This worries me. It looks like this query is going to fail on v19.2 nodes after your migration gets run, because it will be trying to insert three values into a four column table. Could you check if that's the case?
</blockquote></details>

I checked - I don't think there's an issue inserting three values into a four column table, as long as the order is correct. The 4th value will just be NULL - which should be okay
___
*[pkg/sql/user.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-Lzb_WuR0mCiTy7nzOAp:-M-C3URQ1t32zB-xR8Il:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbe6540f7d2aeb801bf5c5e66f03b12fa6f06c/pkg/sql/user.go#L101)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Probably doesn't hurt anything, but let's not change it if we don't have to. I'll merge my PR for fixing the fakeSpanResolver issue momentarily.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSv31EO94c49BHRWj:-M-BwZfQ1JwfEYAc-TH8:b20hhht) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/logictest/testdata/logic_test/fk#L621)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm surprised these table IDs changed since nothing else in the file did. :thinking: 
</blockquote></details>

Yeah I'm not sure, I ran the test with the rewrite flag
___
*[pkg/sql/parser/parse_test.go, line 2040 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BT7R0AVwHtvjPcGcC:-M-BwccpDcfkcodE7JK3:btn5jp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/parse_test.go#L2040)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: I don't think it's necessary to test these all with both `CREATEROLE` and `NOCREATEROLE`. You can pick one or the other.
</blockquote></details>

Gotcha
___
*[pkg/sql/parser/sql.y, line 5192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BXp9wD-0NA9gZD7YJ:-M-BwnOyA6tyap9Vwsst:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/sql.y#L5192)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Mixture of tabs and spaces here.
</blockquote></details>

Done.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYwqrE76H2-Hd_eUF:-M-BwqGi7atsZdEb4YB7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L1)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Old copyright. :)
</blockquote></details>

Done.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYzRv0xTiraHJtdaz:-M-BwtMZ0rs1gul-eN-l:blnqm2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L11)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I need to think more about this but I wonder if we can make this package's interface clearer. A few things I'm thinking about:
- I'm not convinced the BitField stuff is buying us much here, and it's not ideal that callers need to be aware of it rather than it just being an implementation detail.
- I would try not to export anything which isn't needed outside the package, like `MapToSQLColumn` for instance.
- I wonder if we can pull more of the functionality for setting and getting these privileges into this package for better encapsulation.

I'll think more about this but I would encourage you to think about what functionality callers actually need when it comes to role privileges. Then try and design a clear and compact interface which serves those needs, and hide everything else.
</blockquote></details>

Yeah - for user expiration where I'm merging the behaviour of users/roles, I changed this to actually be a part of tree and renamed RolePrivilege to RoleOption - one reason for moving it to tree is because it made sense for the "Value" field of Role Option/Privilege to be an Expr, importing Expr into this package would cause a circular dependency.

I'm not sure if this is the best solution however, let me know if you have any ideas.

https://github.com/RichardJCai/cockroach/blob/user_account_expiration/pkg/sql/sem/tree/role_option.go
___
*[pkg/sql/roleprivilege/role_privilege.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-Ba-Rx55rjN27j5394:-M-ByFpa5pLOr6J8rgMj:b-896fix) ([raw file](https://githu [...]

2020-02-04 18:12 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/roleprivilege/role_privilege.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYzRv0xTiraHJtdaz:-M-GOewm1FQMMNboGG99:bd5wl0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L11)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah - for user expiration where I'm merging the behaviour of users/roles, I changed this to actually be a part of tree and renamed RolePrivilege to RoleOption - one reason for moving it to tree is because it made sense for the "Value" field of Role Option/Privilege to be an Expr, importing Expr into this package would cause a circular dependency.

I'm not sure if this is the best solution however, let me know if you have any ideas.

https://github.com/RichardJCai/cockroach/blob/user_account_expiration/pkg/sql/sem/tree/role_option.go
</blockquote></details>

Left BitField internally to support checking for redundant and conflicting privileges easier - not exporting it.


<!-- Sent from Reviewable.io -->

2020-02-10 15:05 UTC, solongordon requested changes
Few things left to fix up but looking good!

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-M-jcQYv1m-03weER05K:b-hwcsew)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @solongordon)

___
*[pkg/sql/authorization.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BQcddDgz_pvs0k5GW:-M-jZzaz46UVjFcU28S5:bbwmkve) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L312)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>


For this, the array has to be a DArray - the underlying Array inside DArray is of type Datums, to do this we would have to convert the String into Datum type and create this DArray (DArray has it's own String format which allows this query to work). A regular slice can't be passed in to this query.

Would this be preferable to doing my own String construction here.
</blockquote></details>

I'd still say this is preferable. `DString` and `DArray` are pretty thin wrappers.
___
*[pkg/sql/create_user.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BRjEQ-4Ksh1ynt4zV:-M-j_9MO1OTaqzly7s4z:b-tq2y0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/14c85e8fa76616efbb5d13b11adaf451c6160b41/pkg/sql/create_user.go#L133)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I checked - I don't think there's an issue inserting three values into a four column table, as long as the order is correct. The 4th value will just be NULL - which should be okay
</blockquote></details>

Great, I forgot (or maybe never knew) about this behavior.
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BSv31EO94c49BHRWj:-M-j_N7Y6_TgBxqKb-iD:bf39sxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/logictest/testdata/logic_test/fk#L621)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yeah I'm not sure, I ran the test with the rewrite flag
</blockquote></details>

Seems fixed now.
___
*[pkg/sql/parser/sql.y, line 5192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BXp9wD-0NA9gZD7YJ:-M-j_UxEAAXuJJKj9oNi:bo9hazv) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/sql.y#L5192)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still a problem.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-jbwmJ6QkTYiQypJv7:-M-jbwmJ6QkTYiQypJv8:b-83b0hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L176)):*
> ```Go
> 
> 	if (rolePrivilegeBits&CREATEROLE.Mask() != 0) &&
> 		(rolePrivilegeBits&NOCREATEROLE.Mask() != 0) {
> ```

Nit: Unnecessary parens
___
*[pkg/sql/roleprivilege/role_privilege.go, line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-ja6673VeIYckuxPvr:-M-ja6686DvAZy1-_yUM:b679wpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/567193636e100b132b93a9bc0b1a3e608afc134a/pkg/sql/roleprivilege/role_privilege.go#L118)):*
> ```Go
> 	sb.WriteString("SET ")
> 	for i, privilege := range pl {
> 		if i == 0 {
> ```

Minor: Seems like you can reduce some duplication here. Something like
```
if i > 0 {
    sb.WriteString(" , ")
}
sb.WriteString(fmt.Sprintf(`"%s" = %t`, toSQLColumn[privilege], toBool[privilege]))
```
___
*[pkg/sql/roleprivilege/role_privilege.go, line 120 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-j_hKpBlqY8W_Wx1vS:-M-j_hKpBlqY8W_Wx1vT:b-ifkjfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/567193636e100b132b93a9bc0b1a3e608afc134a/pkg/sql/roleprivilege/role_privilege.go#L120)):*
> ```Go
> 		if i == 0 {
> 			sb.WriteString(fmt.Sprintf(
> 				"\"%s\" = %t ",
> ```

Nit: You can use backticks to avoid escaping the quotes.


<!-- Sent from Reviewable.io -->

2020-02-10 18:20 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/authorization.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BQcddDgz_pvs0k5GW:-M-kJ1m1BsR5_L6kIsLB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/authorization.go#L312)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'd still say this is preferable. `DString` and `DArray` are pretty thin wrappers.
</blockquote></details>

Done.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BYzRv0xTiraHJtdaz:-M-kExC90CYQgh15dg4q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/roleprivilege/role_privilege.go#L11)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Left BitField internally to support checking for redundant and conflicting privileges easier - not exporting it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-10 18:25 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/parser/sql.y, line 5192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-BXp9wD-0NA9gZD7YJ:-M-kL8TI4y0FTeT6a1t2:bqj9fj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/31c5e3362b08a39782fdc62378ddd481580453f9/pkg/sql/parser/sql.y#L5192)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Still a problem.
</blockquote></details>

Done now - how do you check tabs vs spaces using reviewable?


<!-- Sent from Reviewable.io -->

2020-02-10 21:07 UTC, solongordon requested changes
> Reviewed 1 of 28 files at r2, 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sqlmigrations/migrations.go, line 902 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-kv56m27NUbE2lg8gx:-M-kv56m27NUbE2lg8gy:b5xzbk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9388fdbcb286fe7fd4bedf10361c1042f6e5571e/pkg/sqlmigrations/migrations.go#L902)):*
> ```Go
> func addHasCreateRoleToSystemUsers(ctx context.Context, r runner) error {
> 	const addHasCreateRoleColumn = `
>           ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "hasCreateRole" bool DEFAULT false
> ```

Sorry I just noticed this is still missing the `NOT NULL` declaration so it will differ from the bootstrapped version of the table.


<!-- Sent from Reviewable.io -->

2020-02-10 21:17 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 902 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-kv56m27NUbE2lg8gx:-M-kxVTA9WREbXp2iYXi:b9r97ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/9388fdbcb286fe7fd4bedf10361c1042f6e5571e/pkg/sqlmigrations/migrations.go#L902)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Sorry I just noticed this is still missing the `NOT NULL` declaration so it will differ from the bootstrapped version of the table.
</blockquote></details>

Oops, I thought the DEFAULT was enough, will update.


<!-- Sent from Reviewable.io -->

2020-02-10 21:27 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sqlmigrations/migrations.go, line 902 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-kv56m27NUbE2lg8gx:-M-l-0iSDbJYxZ9JjwZI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9388fdbcb286fe7fd4bedf10361c1042f6e5571e/pkg/sqlmigrations/migrations.go#L902)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Oops, I thought the DEFAULT was enough, will update.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-12 15:30 UTC, solongordon commented
@dt weighed in on the schema for role options and feels that it would be less risky to go with a separate `role_options` table with a row per option. (The second approach from https://github.com/cockroachdb/cockroach/issues/44486.) Let's go ahead and make that change before merging this.

By the way, when you create the new table descriptor, you can put all the columns in the same family. Older system tables only use a separate column family for every column for historical reasons.

2020-02-13 16:22 UTC, solongordon requested changes
Cool, thanks for making this change. I appreciate it's slightly more awkward than just upserting a single row into `system.users` but I think it's worth it to avoid more migrations down the line. I left a suggestion about how you might make the mutation code more straightforward.

> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-M-zJYGGCH71KPHVjNgx:b-np2jd9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/alter_role.go, line 90 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zKxne0loWRJI-QcwP:-M-zKxne0loWRJI-QcwQ:b-jbasw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/alter_role.go#L90)):*
> ```Go
> 		params.p.txn,
> 		sqlbase.InternalExecutorSessionDataOverride{User: security.RootUser},
> 		fmt.Sprintf("SELECT * FROM %s WHERE username = $1", userTableName),
> ```

You can make this `SELECT 1` instead of `SELECT *`.
___
*[pkg/sql/alter_role.go, line 94 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zL5gd3q6w6SwSfcVy:-M-zL5gd3q6w6SwSfcVz:b-6jzuoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/alter_role.go#L94)):*
> ```Go
> 	)
> 	if err != nil {
> 		return err
> ```

Can we make sure this is a nice "role %s does not exist" error?
___
*[pkg/sql/authorization.go, line 322 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zLls6BuAr0cUw6ccY:-M-zLls6BuAr0cUw6ccZ:b-270aht) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/authorization.go#L322)):*
> ```Go
> 		sqlbase.InternalExecutorSessionDataOverride{User: security.RootUser},
> 		fmt.Sprintf(
> 			`SELECT * from %s WHERE option = '%s' AND username = ANY($1)`,
> ```

I missed this before but this can be `SELECT 1` as well. You could also add a `LIMIT 1` at the end.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zEEIxE1SelVysmXly:-M-zEEIxE1SelVysmXlz:bu0iqup) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/roleprivilege/role_privilege.go#L59)):*
> ```Go
> 	CREATEROLE:   true,
> 	NOCREATEROLE: false,
> }
> ```

Unused now
___
*[pkg/sql/roleprivilege/role_privilege.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zEa-Q93RiFl8m2VXd:-M-zEa-Q93RiFl8m2VXe:b-tu59ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/roleprivilege/role_privilege.go#L116)):*
> ```Go
> 
> // GetInsertStmtRows returns the rows to insert for the given role options.
> func (pl List) GetInsertStmtRows() (rows string, numRows int, err error) {
> ```

I think it would be more straightforward if you just had a function which mapped `Kind` to the appropriate SQL statement, like
```
CREATEROLE -> `UPSERT INTO system.role_options (username, option) VALUES ($1, "CREATEROLE")`
NOCREATEROLE -> `DELETE FROM system.role_options WHERE username = $1 AND option = "CREATEROLE"`
```
Then when you're executing an ALTER ROLE statement, you just need to retrieve the appropriate statements and run them in one transaction. No need to delete all the existing rows first like you're doing now. And it gets rid of the confusing "positive option" stuff.

Note this also will extend nicely to handle `password` even though it still lives in `system.users`.
___
*[pkg/sql/sqlbase/system.go, line 72 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zHH3qDwdEUGuXGyRH:-M-zHH3qDwdEUGuXGyRI:b9omh1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/sqlbase/system.go#L72)):*
> ```Go
>   username         STRING PRIMARY KEY,
>   "hashedPassword" BYTES,
>   "isRole"         BOOL NOT NULL DEFAULT false,
> ```

Shouldn't make a difference but let's not add the comma here.
___
*[pkg/sqlmigrations/migrations.go, line 293 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zJ0dODixFmOJGJPWM:-M-zJ0dODixFmOJGJPWN:b-62lfc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sqlmigrations/migrations.go#L293)):*
> ```Go
> 	{
> 		// Introduced in v20.1.,
> 		name:             "create system.role_options table.",
> ```

Nit: The other migration names don't have a period at the end so let's match that
___
*[pkg/sqlmigrations/migrations.go, line 301 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zIuv2-CL3wFTvePGf:-M-zIuv2-CL3wFTvePGg:b-s35nyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sqlmigrations/migrations.go#L301)):*
> ```Go
> 		name:   "insert (admin, CREATEROLE) column into system.role_options.",
> 		workFn: addCreateRoleToAdmin,
> 	},
> ```

Minor: You could just combine these two into a single migration.
___
*[pkg/sqlmigrations/migrations.go, line 879 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zILtX9O_B9_qXoHLX:-M-zILtX9O_B9_qXoHLY:b-7c7ozo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sqlmigrations/migrations.go#L879)):*
> ```Go
> }
> 
> func addAdminRole(ctx context.Context, r runner) error {
> ```

Nit: This function got moved unnecessarily.
___
*[pkg/sqlmigrations/migrations.go, line 908 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zIUrU7AHVazAiivMn:-M-zIUrU7AHVazAiivMo:bxru4kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sqlmigrations/migrations.go#L908)):*
> ```Go
> 	// We intentionally override any existing entry.
> 	const upsertAdminStmt = `
>           INSERT INTO system.role_options (username, option, value) VALUES ($1, 'CREATEROLE', NULL)
> ```

Make this an UPSERT since migrations must be idempotent.


<!-- Sent from Reviewable.io -->

2020-02-14 19:02 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/alter_role.go, line 90 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zKxne0loWRJI-QcwP:-M0-PEix-pezNUWfXrpg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/alter_role.go#L90)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

You can make this `SELECT 1` instead of `SELECT *`.
</blockquote></details>

Done.
___
*[pkg/sql/alter_role.go, line 94 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zL5gd3q6w6SwSfcVy:-M0-QMw4AghRy_YBbSiJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/alter_role.go#L94)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Can we make sure this is a nice "role %s does not exist" error?
</blockquote></details>

Done.
___
*[pkg/sql/authorization.go, line 322 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zLls6BuAr0cUw6ccY:-M0-QTsHDNd78WIJLdZD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/authorization.go#L322)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I missed this before but this can be `SELECT 1` as well. You could also add a `LIMIT 1` at the end.
</blockquote></details>

Done.
___
*[pkg/sql/roleprivilege/role_privilege.go, line 59 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zEEIxE1SelVysmXly:-M0-QXPbCinInSUHBVib:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/roleprivilege/role_privilege.go#L59)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused now
</blockquote></details>

Removed
___
*[pkg/sql/roleprivilege/role_privilege.go, line 116 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zEa-Q93RiFl8m2VXd:-M0-QZGv679CMyflcmd6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/roleprivilege/role_privilege.go#L116)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think it would be more straightforward if you just had a function which mapped `Kind` to the appropriate SQL statement, like
```
CREATEROLE -> `UPSERT INTO system.role_options (username, option) VALUES ($1, "CREATEROLE")`
NOCREATEROLE -> `DELETE FROM system.role_options WHERE username = $1 AND option = "CREATEROLE"`
```
Then when you're executing an ALTER ROLE statement, you just need to retrieve the appropriate statements and run them in one transaction. No need to delete all the existing rows first like you're doing now. And it gets rid of the confusing "positive option" stuff.

Note this also will extend nicely to handle `password` even though it still lives in `system.users`.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/system.go, line 72 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zHH3qDwdEUGuXGyRH:-M0-Q_d5DSplXR0Tkh9T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sql/sqlbase/system.go#L72)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Shouldn't make a difference but let's not add the comma here.
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 908 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-M-zIUrU7AHVazAiivMn:-M0-Qe9B8JkTnSmGk4Ud:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b3c7e3faf96237bf42bd5b0a5df38d8c21802f1/pkg/sqlmigrations/migrations.go#L908)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Make this an UPSERT since migrations must be idempotent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-14 19:44 UTC, RichardJCai reviewed
Note* Please ignore R8 when reviewing -- accidentally pushed wrong branch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-M04DkV00uN0kUSdK5qi:bof7jss)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)



<!-- Sent from Reviewable.io -->

2020-02-19 15:02 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you figure out the failing test. Thanks for sticking it out through several revisions!

> Reviewed 7 of 21 files at r8, 26 of 27 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44232#-:-M0Sy3XjCEh84YKrP2gr:b-a0q4v1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)



<!-- Sent from Reviewable.io -->

2020-02-24 19:10 UTC, RichardJCai commented
bors r+

2020-02-24 20:02 UTC, merged

2020-02-26 20:23 UTC, knz commented
(nit: the release note doesn't have the right format. Hopefully it'll get picked up in the next beta release, but @RichardJCai please track the next beta announcement and check that the explanation is in there. If needed, ping Jesse to initiate the doc update.)

2020-02-26 21:15 UTC, RichardJCai commented
@knz 

Yep will do.

2020-02-26 21:16 UTC, knz commented
alternatively you can do something like #45201 :)