sql,ui: enable non-admin users to see their own jobs
cockroachdb/cockroach pull request #44345
Opened 2020-01-24 16:40 UTC by knz

Informs #44335.

Release note (ui change): Non-admin users can now use the "Jobs
detail" page and see their own jobs.

Release note (sql change): Non-admin users can now query `SHOW JOBS`
and `crdb_internal.jobs` and see their own jobs.

2020-01-24 16:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44345)
<!-- Reviewable:end -->

2020-01-24 16:41 UTC, knz commented
(Will add the missing tests once CI tells me what I need to change.)

2020-01-24 21:10 UTC, spaskob requested changes
I don't feel to qualified to review on my own, please contact @dt  as well

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-:-LzONs_V9E2iSK_lgJw_:bybxn95)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzOMpGKDoj6HH11FZkU:-LzOMpGLErqjFNg3jkDV:b-q1jszo) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L463)):*
> ```Go
> 
> 		// Beware: we're querying system.jobs as root; we need to be careful to filter
> 		// out results that the current user is not able to see.
> ```

@dt how does this interplay with you work on cloud keys
___
*[pkg/sql/crdb_internal.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzON-pjAGgRmrMr6Fce:-LzON-pjAGgRmrMr6Fcf:brq4b7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L486)):*
> ```Go
> 			// We filter out masked rows before we allocate all the
> 			// datums. Needless allocate when not necessary.
> 			if !(isAdmin || (payload != nil && payload.Username == currentUser)) {
> ```

I find it hard to read and reason that is correct; are you sure it's not ... && ...
I feel like this may need a test as well.


<!-- Sent from Reviewable.io -->

2020-01-24 22:17 UTC, dt approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzOMpGKDoj6HH11FZkU:-LzOa7j24QDX912hYeU3:b-g91n2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L463)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

@dt how does this interplay with you work on cloud keys
</blockquote></details>

If the user was an admin, they could already read secrets/keys directly from system.jobs, and it if is their own job, then it is their own keys anyway (account-sharing notwithstanding). Overall I don't think this significantly changes anything w.r.t. secrets stored in job payloads. 

Additionally, we only show them the `payload.Description` which typically hides they secrets, but I'd rather not include that here -- the hiding is only superficial since the secrets are still in and need to be in the job itself, so pretending they're gone clouds some people's thread model, but that's a separate issue.
___
*[pkg/sql/crdb_internal.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzON-pjAGgRmrMr6Fce:-LzObIfeAj8Z_tO-IF0I:b7e7xkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L486)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I find it hard to read and reason that is correct; are you sure it's not ... && ...
I feel like this may need a test as well.
</blockquote></details>

even just binding an intermediate bool and moving the extra inversion could help IMO:
 `if canSeeJob := isAdmin || (paylod!=nil && payload.Username == currentUser); !canSeeJob { continue }`


<!-- Sent from Reviewable.io -->

2020-01-25 11:43 UTC, knz reviewed
Added the missing test cases. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-:-LzRVrCQ8r1yrFzbK53B:bo24bz8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/sql/crdb_internal.go, line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzOMpGKDoj6HH11FZkU:-LzRVpg-BO82o4b95V91:b-gsh0ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L463)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

If the user was an admin, they could already read secrets/keys directly from system.jobs, and it if is their own job, then it is their own keys anyway (account-sharing notwithstanding). Overall I don't think this significantly changes anything w.r.t. secrets stored in job payloads. 

Additionally, we only show them the `payload.Description` which typically hides they secrets, but I'd rather not include that here -- the hiding is only superficial since the secrets are still in and need to be in the job itself, so pretending they're gone clouds some people's thread model, but that's a separate issue.
</blockquote></details>

Thanks for checking
___
*[pkg/sql/crdb_internal.go, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzON-pjAGgRmrMr6Fce:-LzRVqn3E2HdG5ELDdKk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/995bfdc43276d5c94be9d0332dfbc7e15fd7d982/pkg/sql/crdb_internal.go#L486)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

even just binding an intermediate bool and moving the extra inversion could help IMO:
 `if canSeeJob := isAdmin || (paylod!=nil && payload.Username == currentUser); !canSeeJob { continue }`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-27 12:11 UTC, spaskob approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @spaskob)

___
*[pkg/sql/crdb_internal.go, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzauIYkCEHEOwThCLbu:-LzauIYkCEHEOwThCLbv:bd6h24h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f85bea70aa70b143ed9904097f2cfabc3298e20/pkg/sql/crdb_internal.go#L488)):*
> ```Go
> 			sameUser := payload != nil && payload.Username == currentUser
> 			canAccess := isAdmin || sameUser
> 			if !canAccess {
> ```

nit: if canAccess := isAdmin || sameUser; !canAccess {


<!-- Sent from Reviewable.io -->

2020-01-27 13:15 UTC, knz reviewed
TFYR!

bors r=dt,spaskob

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-:-Lzb7zAE2O94VkOH66K_:b-gc3izl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/sql/crdb_internal.go, line 488 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44345#-LzauIYkCEHEOwThCLbu:-Lzb7y5r7dZXCTBQ_GVn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f85bea70aa70b143ed9904097f2cfabc3298e20/pkg/sql/crdb_internal.go#L488)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

nit: if canAccess := isAdmin || sameUser; !canAccess {
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-27 14:01 UTC, merged