storageccl: helpers for encrypting and decrypting blobs
cockroachdb/cockroach pull request #44474
Opened 2020-01-29 05:45 UTC by dt

These helpers handle encrypting and decrypting files, for use in BACKUP/RESTORE.

The following helpers are intended for use in creating and reading encrypted
BACKUPs that support being created and restored using a simple passphrase.
Encryption is done using ASE-GCM with a key derived from the provided
passphrase. There are helpers here for two types of files:
 a) unique-IV-prefixed files that are encrypted/decrypted with a known key
    using EncryptFile and DecryptFile.
 b) unique-salt-and-IV prefixed files that can be encrypted/decrypted with
    just a passphrase by (re-)deriving the key from the salt, using various
    combinations of GenerateKey, EncryptSaltedFile, DecryptSaltedFile and
    DecryptSaltedFileUsingKey.

The former are relatively cheap to read and write on most modern hardware
thanks to native support for AES, but require that you manage the key used.
The advantages of the later type of files is that, with only a passphrase, you
can pick a salt, derive a key and then create a file that can also be read
with just that passphrase: you can open the file, read the salt to re-derive the
key and then decrypt the file. However, the key derivation step there is
(necessarily!) very expensive - using per-file salts and derived keys for
each individual file in a BACKUP could, assuming we used a nice and secure
expensive derivation function, add considerable cost to running such a job.
By offering helpers for both flavors however, a caller can generate a salt
and key once and use it for the salt-prefixed scheme on a chosen metadata or
manifest file, then just use that key for writing all accompanying files using
the cheaper IV-ony headers that rely on the common key.

A following change will actually integrate this into BACKUP/RESTORE.

Release note: none.

2020-01-29 05:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44474)
<!-- Reviewable:end -->

2020-01-29 05:47 UTC, dt commented
This is split out of #44177 to make it easier (in particular for those outside bulk-io) to review the actual crypto in isolation, and then #44177 will just be calling it on the right files with the right keys, putting those keys in the job, etc.

2020-01-29 15:44 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlkbdPAfSU62PHRlcY:-LzlkbdPAfSU62PHRlcZ:b-vgpjvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L55)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> // encryptionPreamble is a constant string prepended to all ciphertexts allowing
> // for some basic sanity checks and hopefully more friendly user-facing errors
> // when an unencrypted file is incorrectly treated as encrypted or vice-versa.
> // The former case is easier to catch -- Decrypt can simply check and should
> // *always* find the preamble if its argument was encrypted. The inverse is a
> // bit harder -- an unencrypted file could start with any byte string, but if
> // a caller a) finds an input file to be un-parsable and b) suspects it might be
> // encrypted, then it can use AppearsEncrypted to check if the file has such a
> // preamble indicating that that is likely the case.
> ```
</details>


Few questions here:
Does it make sense to have information about the type of encryption, etc be exposed as a protocol buffer?  We probably already have backup manifest (BackupDescriptor?) proto.

I'm not a huge fan of storing "encrypt" as a pre-amble.  I think proto would also make sense for the type information (salt size, etc). The easiest thing would be to serialize/deserialize proto itself; but even if we don't want to do that (perhaps unmarshalling errors are not that great), I think we could perhaps store something like:
<version><IV><maybe salt><hmac>

Appending hmac sidesteps the "un-parsable" issue you mention above, and makes it just a bit less obvious (and just a bit more secure to e.g. bit flips detection) as to the type of data included in the file.  Hmac, of course, is computed w/ user supplied key, so if it matches the <version><IV><salt> byte string ,then we know the file is encrypted.
___
*[pkg/ccl/storageccl/encryption.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzltTLu8w30qzsq1yzN:-LzltTLu8w30qzsq1yzO:b-5zhnhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L74)):*
> ```
> func EncryptFile(plaintext, key []byte) ([]byte, error) {
> ```

I am concerned that this API seems to imply that our encrypt/decrypt functions must operate on the entire files loaded in memory.  Is that the case, and if so, is it reasonable to assume that we will never have huge backup files?

Should the API have been as exposed as io.ReaderCloser/WriteCloser instead?
___
*[pkg/ccl/storageccl/encryption.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzliCFt-JCRcE3jTFE7:-LzliCFt-JCRcE3jTFE8:b-133ma5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L82)):*
> ```Go
> 	// Pick a unique IV for this file.
> 	iv := make([]byte, gcm.NonceSize())
> 	if _, err := rand.Read(iv); err != nil {
> ```

I wish go didn't put crypto/rand into "rand" package;  perhaps import crypto/rand as "crypto_rand" to make it obvious that this random data is cryptographically sound?  Or, perhaps update the comment above to make it clear that we're picking cryptographically sound random bytes?
___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-Lzlxpib3tGq3WuP-Nr0:brafyx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
> ```
> // DecryptSaltedFileUsingKey decrypt the same files as DecryptSaltedFile – those
> // created by EncryptSaltedFile with a salt in their header prefix – but can be
> // used when the key has already been derived, to avoid re-derivation.
> ```
Could these 2 use cases be combined? Perhaps pass key, salt as *[]byte?
If non-nil, use them as "expected" salt, otherwise, read & init them?
___
*[pkg/ccl/storageccl/encryption_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlhLYn8vExlUM0q3h2:-LzlhLYn8vExlUM0q3h3:b-ehkfhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption_test.go#L48)):*
> ```
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> ```
Perhaps use some of the helpers, s.a.
assert.NoError(t, err)
assert.Equal(t, plaintext, decrypted)


<!-- Sent from Reviewable.io -->

2020-01-29 15:45 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlkbdPAfSU62PHRlcY:-Lzlybci4EkbvjRFBhT5:b-7xp45f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L55)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> // encryptionPreamble is a constant string prepended to all ciphertexts allowing
> // for some basic sanity checks and hopefully more friendly user-facing errors
> // when an unencrypted file is incorrectly treated as encrypted or vice-versa.
> // The former case is easier to catch -- Decrypt can simply check and should
> // *always* find the preamble if its argument was encrypted. The inverse is a
> // bit harder -- an unencrypted file could start with any byte string, but if
> // a caller a) finds an input file to be un-parsable and b) suspects it might be
> // encrypted, then it can use AppearsEncrypted to check if the file has such a
> // preamble indicating that that is likely the case.
> ```

Few questions here:
Does it make sense to have information about the type of encryption, etc be exposed as a protocol buffer?  We probably already have backup manifest (BackupDescriptor?) proto.

I'm not a huge fan of storing "encrypt" as a pre-amble.  I think proto would also make sense for the type information (salt size, etc). The easiest thing would be to serialize/deserialize proto itself; but even if we don't want to do that (perhaps unmarshalling errors are not that great), I think we could perhaps store something like:
<version><IV><maybe salt><hmac>

Appending hmac sidesteps the "un-parsable" issue you mention above, and makes it just a bit less obvious (and just a bit more secure to e.g. bit flips detection) as to the type of data included in the file.  Hmac, of course, is computed w/ user supplied key, so if it matches the <version><IV><salt> byte string ,then we know the file is encrypted.
</blockquote></details>

Formatting snafu:

I was suggesting to store
Type, IV, Optional Salt, HMAC


<!-- Sent from Reviewable.io -->

2020-01-29 15:56 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlkbdPAfSU62PHRlcY:-LzlydLgDwjcVb0UOujM:b-f4c3ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L55)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Formatting snafu:

I was suggesting to store
Type, IV, Optional Salt, HMAC

</blockquote></details>

We're already using AES-GCM for _authenticated_ encryption, meaning it already has an embedded HMAC that is checked as part of seal/open -- we don't want to roll our own (since that is where mistakes around not checking it, checking it incorrectly, etc can creep in).

the preamble it just only there so we can tell if a user sends us a backup file that it was encrypted or not, and so we can try to yield slightly better errors if users mix up their encrypted and unencrypted backups.
___
*[pkg/ccl/storageccl/encryption.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzliCFt-JCRcE3jTFE7:-LzlzjekEHQcsvtKP8Hj:b-gwr0py) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L82)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I wish go didn't put crypto/rand into "rand" package;  perhaps import crypto/rand as "crypto_rand" to make it obvious that this random data is cryptographically sound?  Or, perhaps update the comment above to make it clear that we're picking cryptographically sound random bytes?
</blockquote></details>

i like the import alias, will do.
___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-LzlzmmH9vu80Sar_3OD:bgd2hf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> // DecryptSaltedFileUsingKey decrypt the same files as DecryptSaltedFile – those
> // created by EncryptSaltedFile with a salt in their header prefix – but can be
> // used when the key has already been derived, to avoid re-derivation.
> ```
Could these 2 use cases be combined? Perhaps pass key, salt as *[]byte?
If non-nil, use them as "expected" salt, otherwise, read & init them?


</blockquote></details>

you mean one method that takes all three of `passphrase []byte`, `key []byte` and `salt []byte` and expects either the first or second and third to be non-nil?

I donno, there's a 17,842x difference in performance between those for ~1KB manifest files -- I'd prefer the caller be explicit about which one they're using -- one-time, expensive one vs repeated-access-one.


<!-- Sent from Reviewable.io -->

2020-01-29 16:17 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlkbdPAfSU62PHRlcY:-Lzm4ELp-uz7dV7H9Zb_:brkb6ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L55)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

We're already using AES-GCM for _authenticated_ encryption, meaning it already has an embedded HMAC that is checked as part of seal/open -- we don't want to roll our own (since that is where mistakes around not checking it, checking it incorrectly, etc can creep in).

the preamble it just only there so we can tell if a user sends us a backup file that it was encrypted or not, and so we can try to yield slightly better errors if users mix up their encrypted and unencrypted backups.

</blockquote></details>

I realize that... But the afaik, the authenticate encryption applies only to the plaintext part; we are not encrypting or authenticating the IV.


<!-- Sent from Reviewable.io -->

2020-01-29 16:21 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-Lzm5NpsCqdRoerDjbwj:b4vgmva) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
> ```
> DecryptSaltedFile
> ```
Just trying to see if we can use just one DecryptSaltedFile method instead of 2 flavors.
Does it make sense to simply split the two methods?
One to extract key/salt based on passphrase plus this method?


<!-- Sent from Reviewable.io -->

2020-01-29 16:38 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzltTLu8w30qzsq1yzN:-Lzm5vx95Cdnwq-PfjSp:b4fb5w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L74)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> func EncryptFile(plaintext, key []byte) ([]byte, error) {
> ```

I am concerned that this API seems to imply that our encrypt/decrypt functions must operate on the entire files loaded in memory.  Is that the case, and if so, is it reasonable to assume that we will never have huge backup files?

Should the API have been as exposed as io.ReaderCloser/WriteCloser instead?
</blockquote></details>

Heh, we went over this for like a week. The API here actually follows the API from Go's AEAD interface: https://golang.org/pkg/crypto/cipher/#AEAD

Streaming is tricky with authentication or a trailing HMAC: we don't want to emit any unauthenticated bytes to the stream -- where they may be acted on -- until we've verified the HMAC for them. We could, in theory, do something with chunked input and individually verified blocks if needed, either chunking our file before using GCM, or using our own AES-CTR with intermittent HMACs or whatever, but none of that is currently worth the complexity since we _already hold the whole file in memory_ and we don't have immediate plans to change that: disk IO is a precious resource and we control the size of used for chunking those files and are already planning to just aim for a size we're okay with holding in memory. If we did switch to something streaming, it would additionally need to support Seeking which adds to the complexity a bit, so over all, given that this fits with our current usage anyway, we decided to stop messing with streaming. We can always change that later -- if we go to bigger files, we can switch to a chunked input and identify it with a different version tag.
___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-Lzm8AHS0zZ7vZGs0AjX:b-vlh2h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> DecryptSaltedFile
> ```
Just trying to see if we can use just one DecryptSaltedFile method instead of 2 flavors.
Does it make sense to simply split the two methods?
One to extract key/salt based on passphrase plus this method?
</blockquote></details>

Yeah, I initially had a separate salt-extract-key-derivation helper but removed it since it re-ran a bunch of the sanity/validation code. Maybe if we're only doing it once per backup we don't care though (particularly compared to the KDF in the middle of it which takes 20000x longer than a couple slice length checks). I'll play with it and see if it cleans things up.


<!-- Sent from Reviewable.io -->

2020-01-29 16:44 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption_test.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlhLYn8vExlUM0q3h2:-LzmARv74UXsDjdcB5Bp:b-5w0qs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption_test.go#L48)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> ```
Perhaps use some of the helpers, s.a.
assert.NoError(t, err)
assert.Equal(t, plaintext, decrypted)

</blockquote></details>

Ah, yeah, that really tidied this up. Note:`require` actually stops the test (t.Fatal), `assert` just records a failure (t.Error) which I find often isn't what you want (continuing rarely makes sense). Also, one thing to be aware of is both sometimes cause allocs so be careful using them in benchmarks to ensure they don't change your results.


<!-- Sent from Reviewable.io -->

2020-01-29 17:06 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzltTLu8w30qzsq1yzN:-LzmFNtKDDYTmth5kIpI:bv3q3c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L74)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Heh, we went over this for like a week. The API here actually follows the API from Go's AEAD interface: https://golang.org/pkg/crypto/cipher/#AEAD

Streaming is tricky with authentication or a trailing HMAC: we don't want to emit any unauthenticated bytes to the stream -- where they may be acted on -- until we've verified the HMAC for them. We could, in theory, do something with chunked input and individually verified blocks if needed, either chunking our file before using GCM, or using our own AES-CTR with intermittent HMACs or whatever, but none of that is currently worth the complexity since we _already hold the whole file in memory_ and we don't have immediate plans to change that: disk IO is a precious resource and we control the size of used for chunking those files and are already planning to just aim for a size we're okay with holding in memory. If we did switch to something streaming, it would additionally need to support Seeking which adds to the complexity a bit, so over all, given that this fits with our current usage anyway, we decided to stop messing with streaming. We can always change that later -- if we go to bigger files, we can switch to a chunked input and identify it with a different version tag.
</blockquote></details>

Okay -- I just wanted to make sure that we do keep files in memory and we're fine with that..
With chunked wringing, reading, you would pretty much have to generate new cipher.Block w/ new IV every X number of bytes, and of course X would also need to be stored in the encrypted file header.

BTW, going w/ proto message might make it easier to extend in the future...  Is that a concern?
if we change encrypting encoding/decoding between versions, we would presumably still want to be able to read old format?


<!-- Sent from Reviewable.io -->

2020-01-29 19:29 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzltTLu8w30qzsq1yzN:-LzmGWZM4mCd5SdItf9s:ba73uwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L74)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Okay -- I just wanted to make sure that we do keep files in memory and we're fine with that..
With chunked wringing, reading, you would pretty much have to generate new cipher.Block w/ new IV every X number of bytes, and of course X would also need to be stored in the encrypted file header.

BTW, going w/ proto message might make it easier to extend in the future...  Is that a concern?
if we change encrypting encoding/decoding between versions, we would presumably still want to be able to read old format?
</blockquote></details>

I'm open to switching to proto later, especially if we decide to support configurable KDFs or KDF params like iterations, choice of ciphers, etc. Even if/when we do so though, i think i'd still stick a version byte in front to identify that that is what we're doing in that file in case we ever change it, which means we can just as easily do this if/when we need it. For now, the standard IV-then-ciphertext pattern seems fine and keeps things simple.


<!-- Sent from Reviewable.io -->

2020-01-29 20:08 UTC, aaron-crl commented
I'd be in favor of versioning this now unless it's a heavy lift. It keeps the future logic lighter and reduces some of the subsequent attack surface.

2020-01-29 22:39 UTC, pbardea reviewed
minor point: If we don't go in the direction of separating out a validation method, it may still be useful to document the expected structure of an encrypted file so it's easier for future readability (debugging, etc...)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-:-LznRt-k2F0QNTiUg8JZ:buhudji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmDS1y9bVHTJAaHvI8:-LzmDS1y9bVHTJAaHvI9:b-nyup0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L24)):*
> ```Go
> // The following helpers are intended for use in creating and reading encrypted
> // BACKUPs that support being created and restored using a simple passphrase.
> // Encryption is done using ASE-GCM with a key derived from the provided
> ```

nit: AES rather than ASE
___
*[pkg/ccl/storageccl/encryption.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmDX5U7BaqyLIrKWi_:-LzmDX5U7BaqyLIrKWia:b-1p1gc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L58)):*
> ```Go
> 
> const encryptionSaltSize = 16
> const encryptionVersionAESGCMWithSalt = 1
> ```

Would it be beneficial/easier to read if this were an enum?
___
*[pkg/ccl/storageccl/encryption.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmnDTN1DS5VVL2eLmy:-LzmnDTOExskrUEv401j:bbayj6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L208)):*
> ```Go
> 	if version != encryptionVersionAESGCMWithSalt {
> 		return nil, nil, nil, errors.Errorf("unexpected encryption scheme/config version %d", version)
> ```

nit: extra newline here
___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-Lzmp9Vw8POHhQ1o-Iqf:b-nimcvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, I initially had a separate salt-extract-key-derivation helper but removed it since it re-ran a bunch of the sanity/validation code. Maybe if we're only doing it once per backup we don't care though (particularly compared to the KDF in the middle of it which takes 20000x longer than a couple slice length checks). I'll play with it and see if it cleans things up.
</blockquote></details>

I had similar thoughts when doing my first pass. My 2c: I think having a separate validation method for each type of file may be useful if only to serve as a source to document the expected structure of an encrypted file.


<!-- Sent from Reviewable.io -->

2020-01-29 22:46 UTC, dt commented
@aaron-crl it _is_ versioned, unless I'm not understanding what you mean?

2020-01-29 23:00 UTC, miretskiy reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)



<!-- Sent from Reviewable.io -->

2020-01-29 23:01 UTC, miretskiy approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @miretskiy)



<!-- Sent from Reviewable.io -->

2020-01-29 23:39 UTC, pbardea approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, and @miretskiy)



<!-- Sent from Reviewable.io -->

2020-01-30 02:24 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmDS1y9bVHTJAaHvI8:-LzoCkf7DBgbyGoM7A5s:bdiogf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L24)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: AES rather than ASE
</blockquote></details>

Nice catch
___
*[pkg/ccl/storageccl/encryption.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmDX5U7BaqyLIrKWi_:-LzoCqLJ7D-U6vOA60aP:b-jpc9mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L58)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Would it be beneficial/easier to read if this were an enum?
</blockquote></details>

Huh, like just give it a type alias? I intentionally _don't_ want to use `iota` since the value _is_ persisted and I would not want moving the code around or deleting some other lineto change its value (iota-enums are just generally bad for persisted things). I could give it an alias though if you think that'd be nice to have.
___
*[pkg/ccl/storageccl/encryption.go, line 237 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-Lzlxpib3tGq3WuP-Nr-:-LzoD2iR1k_QCSqgg836:b-2qozah) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L237)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I had similar thoughts when doing my first pass. My 2c: I think having a separate validation method for each type of file may be useful if only to serve as a source to document the expected structure of an encrypted file.
</blockquote></details>

Done (both suggestions): separate public API method for just extracting salt and deriving key from passphrase, so that there is then only one flavor of this decrypt function (that you can call after the salt extract/key derivation one if you want), and then pulled the header reading/salt-extraction into a common internal helper that is shared by both of those functions. I like both cleanups!


<!-- Sent from Reviewable.io -->

2020-01-30 02:27 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzmDX5U7BaqyLIrKWi_:-LzoGC7z2EYAYv9ZfBbQ:b-jg270y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L58)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Huh, like just give it a type alias? I intentionally _don't_ want to use `iota` since the value _is_ persisted and I would not want moving the code around or deleting some other lineto change its value (iota-enums are just generally bad for persisted things). I could give it an alias though if you think that'd be nice to have.
</blockquote></details>

actually, giving it a type alias just makes us have to cast them and forth back to use them in a []byte, so I think I prefer just leaving them as untyped consts for now. Plus, since we're not passing them anywhere, we never actually mention their type, so the alias wouldn't even get us type checking or anything.


<!-- Sent from Reviewable.io -->

2020-01-30 02:40 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzlkbdPAfSU62PHRlcY:-LzoILO5A_rROTJ0YFSd:b-rzt1ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L55)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I realize that... But the afaik, the authenticate encryption applies only to the plaintext part; we are not encrypting or authenticating the IV.
</blockquote></details>

We chatted a bit offline today -- if we stared with IV and then an HMAC of the IV, we could be _really confident_ that we were looking at an encrypted file since the odds of that happing in any given plaintext would be small. That said, we don't _need_ to be absolutely certain - this was more intended to be _human_ readable when looking at files -- and we don't need an HMAC on the IV for anything else and we already have one thanks to GCM on the rest, so I'm inclined to leave this as is.


<!-- Sent from Reviewable.io -->

2020-01-30 12:30 UTC, miretskiy approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @miretskiy, and @pbardea)



<!-- Sent from Reviewable.io -->

2020-01-30 19:09 UTC, aaron-crl commented
> @aaron-crl it _is_ versioned, unless I'm not understanding what you mean?

My misunderstanding. Apologies.

2020-02-01 19:02 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44474)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @miretskiy, and @pbardea)

___
*[pkg/ccl/storageccl/encryption.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44474#-LzltTLu8w30qzsq1yzN:-LzzADvQ2JoDXCgNJmht:b54ktno) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f5bdce207ef81515408b6b9dd5064c0c88b158b/pkg/ccl/storageccl/encryption.go#L74)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm open to switching to proto later, especially if we decide to support configurable KDFs or KDF params like iterations, choice of ciphers, etc. Even if/when we do so though, i think i'd still stick a version byte in front to identify that that is what we're doing in that file in case we ever change it, which means we can just as easily do this if/when we need it. For now, the standard IV-then-ciphertext pattern seems fine and keeps things simple.
</blockquote></details>

I played with prefixing a proto but it was kinda ugly: we'd need to marshal it separately, manually encode the length, etc. 

I went ahead and just removed the salt-prefixed helpers entirely and made keeping track of encryption options -- like salt chosen, KDF/params/etc all the responsibility of the caller (and backup will use a proto for that, stored along side the encrypted files in a separate encryption-options file). I had a slight preference for being able to open and read a manifest by itself, by including the salt in its header, but overall it doesn't really matter if we need to fetch and open one more file in a big bulk job.


<!-- Sent from Reviewable.io -->

2020-02-04 00:08 UTC, dt commented
I'm going to go ahead and merge this on the above approvals since the only changes since then are pretty much just deletions, and if discussion on #44177 does end up prompting a change in direction, we can always revise it.

bors r+

2020-02-04 00:36 UTC, merged