storage/concurrency: define concurrency control interfaces
cockroachdb/cockroach pull request #44787
Opened 2020-02-06 01:12 UTC by nvanbenschoten

Informs #41720.

The commit creates a new concurrency package that provides a concurrency manager structure that encapsulates the details of concurrency control and contention handling for serializable key-value transactions. Interested readers should start at `concurrency_control.go` and move out from there.

The new package has a few primary objectives:

1. centralize the handling of request synchronization and transaction contention handling in a single location, allowing for the topic to be documented, understood, and tested in isolation.
2. rework contention handling to react to intent state transitions directly. This simplifies the transaction queueing story, reduces the frequency of transaction push RPCs, and allows waiters to proceed immediately after intent resolution.
3. create a framework that naturally permits "update" locking, which is required for kv-level SELECT FOR UPDATE support (#6583).
4. provide stronger guarantees around fairness when transactions conflict, to reduce tail latencies under contended sceneries.
5. create a structure that can extend to address the long-term goals of a fully centralized lock-table laid out in #41720.

This commit pulls over a lot of already reviewed code from #43775. The big differences are that it updates the lockTable interface to match the one introduced in #43740 and it addresses the remaining TODOs to document the rest of the concurrency control mechanisms in CockroachDB. At this point, a reader of this file should get a good idea of how KV transactions interact in CRDB... now we just need to make the system actually work this way.

2020-02-06 01:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44787)
<!-- Reviewable:end -->

2020-02-06 20:22 UTC, sumeerbhola requested changes
> Reviewed 11 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/storage/concurrency/concurrency_control.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QxrT96VgfxqnZnc5Y:-M-QxrT96VgfxqnZnc5Z:b-knhsg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L63)):*
> ```Go
> // that a request that is part of a transaction which has already acquired a
> // lock does not need to wait on that lock during sequencing, and can therefore
> // ignore any queue that has formed on the lock.
> ```

nit: Perhaps add: For other exceptions, see the later comment for lockTable.
___
*[pkg/storage/concurrency/concurrency_control.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QyRFm4Vokj2wI1e4t:-M-QyRFnCW8d9GXRTctH:bb2cdq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L84)):*
> ```Go
> //  |             | [ lockTable ]                                     |  |  |
> //  |             | [    key1   ]    -------------+-----------------+ |  ^  |
> //  |             | [    key2   ]  /  lock:       | lockWaitQueue:  |--<------<---+
> ```

s/lock:/lockState:/
___
*[pkg/storage/concurrency/concurrency_control.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QzVUp7gp6WhTjrBoE:-M-QzVUp7gp6WhTjrBoF:b-kjbow0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L163)):*
> ```Go
> 	// sequencing attempts. If provided, the guard should not be holding latches
> 	// already. This typically means that the guard was acquired through a call
> 	// to a contentionHandler method.
> ```

I didn't quite understand the last sentence.
___
*[pkg/storage/concurrency/concurrency_control.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R28pBALs3MWFb5-vd:-M-R28pBALs3MWFb5-ve:b-r0yu5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L171)):*
> ```Go
> 	// directly, in which case it will return a Response for the request. If it
> 	// does so, it will not return a request guard.
> 	SequenceReq(context.Context, *Guard, Request) (*Guard, Response, *Error)
> ```

A go question: `requestSequencer` is an unexported interface so does it matter whether this method is named `SequenceReq` or `sequenceReq`?
___
*[pkg/storage/concurrency/concurrency_control.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R-G--D-hpMtJ7BBx9:-M-R-G--D-hpMtJ7BBxA:b-k7wtw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L187)):*
> ```Go
> 	// from its lock table. After doing so, it enqueues the request that hit the
> 	// error in the lock's wait-queue (but does not wait) and releases the
> 	// guard's latches. It returns an updated guard reflecting this change.
> ```

The latching situation is a bit unclear in these interfaces since it happens as a side-effect of method calls. It sounds like both the methods in `contentionHandler` are called after `SequenceReq()`, which has acquired latches and both of these release them.
Also, there are many interfaces: is it possible to have a rough usage comment that explains how to use them together.
___
*[pkg/storage/concurrency/concurrency_control.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R05sw4iwjWyPb3xsx:-M-R05sw4iwjWyPb3xsy:bmsxuzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L204)):*
> ```Go
> 	// OnLockAcquired informs the concurrency manager that a transaction has
> 	// acquired a new lock or updated an existing lock that it already held.
> 	OnLockAcquired(context.Context, roachpb.Intent)
> ```

should this be `OnLockUpdate()` for consistency with `lockTable`?
___
*[pkg/storage/concurrency/concurrency_control.go, line 325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R0mqF9UN-kzg7gyHX:-M-R0mqF9UN-kzg7gyHY:bb2cdq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L325)):*
> ```Go
> //  | [ lockTable ]                                     |
> //  | [    key1   ]    -------------+-----------------+ |
> //  | [    key2   ]  /  lock:       | lockWaitQueue:  | |
> ```

s/lock:/lockState:/
___
*[pkg/storage/concurrency/concurrency_control.go, line 332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R2jnf2h9fOh3QeueG:-M-R2jnf2h9fOh3QeueH:b-gnrb6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L332)):*
> ```Go
> //  +---------------------------------------------------+
> //
> // The database is read and written using "requests". Transactions are composed
> ```

Are there any substantive changes to the long comments related to lockTable -- i.e., should I reread?
___
*[pkg/storage/concurrency/concurrency_control.go, line 423 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R5uMB3bCcPMEbXH2F:-M-R5uMC8ysLPxXjKsOA:bpsz6ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L423)):*
> ```Go
> 	// For replicated locks, this must be called after the corresponding write
> 	// intent has been applied to the replicated state machine.
> 	AcquireLock(*enginepb.TxnMeta, roachpb.Key, lock.Strength, lock.Durability) error
> ```

can you add a code comment that `*TxnMeta` must be the same as the one used in `Request` 
___
*[pkg/storage/concurrency/concurrency_control.go, line 502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R33e-49Bzr3asCnJ9:-M-R33e-49Bzr3asCnJA:be9mdi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L502)):*
> ```Go
> // lockTableGuardState represents the current state of a request as it waits on
> // conflicting locks in the lockTable.
> type lockTableGuardState interface {
> ```

the actual state is hidden since it is irrelevant to the user of this package?
___
*[pkg/storage/concurrency/lock_table.go, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R4sIS2uVg8WVQ4Yb3:-M-R4sIS2uVg8WVQ4Yb4:b4siqn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/662ab2865270d15abe5fa2c5b85b578e70ffba16/pkg/storage/concurrency/lock_table.go#L209)):*
> ```Go
> // thread.
> //
> // Recommended usage:
> ```

this usage comment has been omitted when copying -- I assume that is because it has outlived its usefulness since there will soon be code that roughly mirrors it?
___
*[pkg/storage/concurrency/lock_table.go, line 291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R4I192WSM7rY0-DZb:-M-R4I1A1_WKZEbR3W2B:btm3aqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/lock_table.go#L291)):*
> ```Go
> 	g.table.findNextLockAfter(g, false /* notify */)
> 	g.mu.Lock() // Unlock deferred
> 	return &g.mu.state
> ```

We can't return a pointer to `state` since it can be modified after this method returns.
I suspect this need to use a pointer was motivated by using a pointer receiver for the marker `guardState()` method -- is that correct?
___
*[pkg/storage/concurrency/lock_table.go, line 812 at r3](ht [...]

2020-02-07 00:10 UTC, nvb reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @sumeerbhola, and @tbg)

___
*[pkg/storage/concurrency/concurrency_control.go, line 63 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QxrT96VgfxqnZnc5Y:-M-RnBoE7oDxh6n33NSY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: Perhaps add: For other exceptions, see the later comment for lockTable.
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QyRFm4Vokj2wI1e4t:-M-RnGJDATVtOTwM424o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L84)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/lock:/lockState:/
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-QzVUp7gp6WhTjrBoE:-M-RnjOZ8RiyXLBdEVUC:bgk7mm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L163)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't quite understand the last sentence.
</blockquote></details>

Improved.
___
*[pkg/storage/concurrency/concurrency_control.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R28pBALs3MWFb5-vd:-M-RnlyH2TV1oxTrGKuA:b2dxkxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

A go question: `requestSequencer` is an unexported interface so does it matter whether this method is named `SequenceReq` or `sequenceReq`?
</blockquote></details>

`requestSequencer ` is embedded in `Manager` though, so in this case, it does matter.

For purely unexported interfaces, the only difference is that exporting the methods allows objects from other packages to satisfy the interface. We see this with `txnWaitQueue`, which is implemented by `txnwait.Queue`.
___
*[pkg/storage/concurrency/concurrency_control.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R-G--D-hpMtJ7BBx9:-M-RoO-i8uXnLGwYeiVE:bulvlqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L187)):*
> The latching situation is a bit unclear in these interfaces since it happens as a side-effect of method calls. It sounds like both the methods in contentionHandler are called after SequenceReq(), which has acquired latches and both of these release them.

Yes, that's all true. I added to their comments and updated the diagram above.

> Also, there are many interfaces: is it possible to have a rough usage comment that explains how to use them together.

These are all exposed as part of the same `concurrency.Manager` interface. Other packages will only interact with that. I just split up these sub-interfaces to tease apart the different roles that the `concurrency.Manager` plays.
___
*[pkg/storage/concurrency/concurrency_control.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R05sw4iwjWyPb3xsx:-M-RuC2EAqXoT_3QfQT-:b-52r88b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L204)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be `OnLockUpdate()` for consistency with `lockTable`?
</blockquote></details>

Yes! Good catch.
___
*[pkg/storage/concurrency/concurrency_control.go, line 325 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R0mqF9UN-kzg7gyHX:-M-Ru4VK3wv9iqKgEjyD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L325)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/lock:/lockState:/
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R2jnf2h9fOh3QeueG:-M-RuSLr-M9cwbibH6X4:bvl817h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L332)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are there any substantive changes to the long comments related to lockTable -- i.e., should I reread?
</blockquote></details>

No, this is mostly a clean copy with just a few edits to make it fit into the rest of this structure.
___
*[pkg/storage/concurrency/concurrency_control.go, line 423 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R5uMB3bCcPMEbXH2F:-M-RuoGE0xGZeRLnjihA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L423)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a code comment that `*TxnMeta` must be the same as the one used in `Request` 
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 502 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R33e-49Bzr3asCnJ9:-M-Ruww75fPPQ7PQUPfn:b-vwqcls) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L502)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the actual state is hidden since it is irrelevant to the user of this package?
</blockquote></details>

Yes, the state is hidden to anyone other than a `lockTableWaiter` impl. No one else should need to know about it, but it's useful to include here opaquely for the sake of understanding how it fits in with the rest of the package.
___
*[pkg/storage/concurrency/lock_table.go, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R4sIS2uVg8WVQ4Yb3:-M-RvQlj4OeLYyM5RGh1:b-gokzc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/662ab2865270d15abe5fa2c5b85b578e70ffba16/pkg/storage/concurrency/lock_table.go#L209)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this usage comment has been omitted when copying -- I assume that is because it has outlived its usefulness since there will soon be code that roughly mirrors it?
</blockquote></details>

Yeah, we could have kept it, but the next step here is to implement the `lockTableWaiter` which will mirror this code closely, so I didn't think we need to keep it going forward.
___
*[pkg/storage/concurrency/lock_table.go, line 291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R4I192WSM7rY0-DZb:-M-Rvpyi2YJwGCwG8BFr:b-s5f40q) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/lock_table.go#L291)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We can't return a pointer to `state` since it can be modified after this method returns.
I suspect this need to use a pointer was motivated by using a pointer receiver for the marker `guardState()` method -- is that correct?
</blockquote></details>

Good point, I guess I'll revert this `lockTableGuardState` part for now. It wasn't really getting us all that much.
___
*[p [...]

2020-02-08 03:36 UTC, sumeerbhola approved these changes
seems like the changes outside the concurrency package are cosmetic -- if not, someone else would need to review those.
Rest <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

How do you want to sequence merging this and #44791

> Reviewed 1 of 13 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-:-M-XqvFC5wdV5H0eVJ3h:bfbqzq1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/storage/concurrency/concurrency_control.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R05sw4iwjWyPb3xsx:-M-XpWzC-OArGUF7TaR5:b2c40or) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L204)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes! Good catch.
</blockquote></details>

the comment is updated but the method is still `OnLockReleased()`


<!-- Sent from Reviewable.io -->

2020-02-08 19:08 UTC, nvb reviewed
Thanks for the review!

> How do you want to sequence merging this and #44791

Let's get that in first.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-:-M-a9w1d2oXN4ZQZIlz6:b-4mmfuw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @sumeerbhola, and @tbg)

___
*[pkg/storage/concurrency/concurrency_control.go, line 204 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R05sw4iwjWyPb3xsx:-M-a9tZK8CQJ0t59TH2Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L204)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the comment is updated but the method is still `OnLockReleased()`
</blockquote></details>

Done.
___
*[pkg/storage/spanset/spanset.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-aA7zV8pILSjk5vqPq:-M-aA7zV8pILSjk5vqPr:b-tup8s8) ([raw file](https://github.com/cockroachdb/cockroach/blob/78533e0179213476bba8af10b6ecc681dc46aaa4/pkg/storage/spanset/spanset.go#L140)):*
> ```Go
> 		for ss := SpanScope(0); ss < NumSpanScope; ss++ {
> 			s.spans[sa][ss], _ /* distinct */ = mergeSpans(s.spans[sa][ss])
> 			// TODO(nvanbenschoten): dedup across accesses.
> ```

@sumeerbhola I was thinking about this more and I wonder if we can avoid this. If we iterate over span accesses in decreasing strength order (read-write, then read-only) then we know that if a weaker strength access conflicts with a lock and that lock also overlap with a stronger strength access, then the request must already be waiting on the lock. So can't we easily detect this in the lockTable using the `lockTableGuardImpl.mu.locks` set to avoid waiting on the same lock twice?

It would be nice not to place extra obscure constraints on the spanset provided to the lockTable/latchManager if we don't need to.


<!-- Sent from Reviewable.io -->

2020-02-09 23:22 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/storage/spanset/spanset.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-aA7zV8pILSjk5vqPq:-M-gEiTw9eY0Omyjc3NZ:b-to3906) ([raw file](https://github.com/cockroachdb/cockroach/blob/78533e0179213476bba8af10b6ecc681dc46aaa4/pkg/storage/spanset/spanset.go#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@sumeerbhola I was thinking about this more and I wonder if we can avoid this. If we iterate over span accesses in decreasing strength order (read-write, then read-only) then we know that if a weaker strength access conflicts with a lock and that lock also overlap with a stronger strength access, then the request must already be waiting on the lock. So can't we easily detect this in the lockTable using the `lockTableGuardImpl.mu.locks` set to avoid waiting on the same lock twice?

It would be nice not to place extra obscure constraints on the spanset provided to the lockTable/latchManager if we don't need to.
</blockquote></details>

Yes, we can use `lockTableGuardImpl.mu.locks` to remove this need. A `lockState` is in that map when (a) request has a reservation or it is in the queued writers (active or inactive), (b) request is in waiting readers, which only happens when actively waiting at this lock. So if a read access finds the `lockState` in the map when doing the scan it must be also doing a write.


<!-- Sent from Reviewable.io -->

2020-02-10 13:44 UTC, tbg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but do consider this a non-expert review.

> Reviewed 10 of 13 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-:-M-jKxa57qDJx9EQMfpz:bcskh9d)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/concurrency/concurrency_control.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R28pBALs3MWFb5-vd:-M-jAO3aDy7eQfkCfAzg:b-dwkb8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`requestSequencer ` is embedded in `Manager` though, so in this case, it does matter.

For purely unexported interfaces, the only difference is that exporting the methods allows objects from other packages to satisfy the interface. We see this with `txnWaitQueue`, which is implemented by `txnwait.Queue`.
</blockquote></details>

Not sure if we care, but look at the opaque godoc the current code causes:

```
type Manager interface {
    // contains filtered or unexported methods
}
```

if you embedded exported interfaces, it would render better. As is, all of the method comments are hidden.
___
*[pkg/storage/concurrency/concurrency_control.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R-G--D-hpMtJ7BBx9:-M-jB-vy5BC8VAyQ0gru:b-c74l9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> The latching situation is a bit unclear in these interfaces since it happens as a side-effect of method calls. It sounds like both the methods in contentionHandler are called after SequenceReq(), which has acquired latches and both of these release them.

Yes, that's all true. I added to their comments and updated the diagram above.

> Also, there are many interfaces: is it possible to have a rough usage comment that explains how to use them together.

These are all exposed as part of the same `concurrency.Manager` interface. Other packages will only interact with that. I just split up these sub-interfaces to tease apart the different roles that the `concurrency.Manager` plays.
</blockquote></details>

The new guard won't hold any latches, right? So the caller will use it to call into `SequenceReq`? Does this preserve fairness (e.g. by putting the txn at the head of the wait queues for all latches it held)?
___
*[pkg/storage/concurrency/concurrency_control.go, line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-j9dis8ZC4XnMVIuF2:-M-j9ditBwN8mOgW1L82:b-7r3t2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L118)):*
> ```Go
> // interface and inner-workings.
> //
> // At a high-level, a request enter the concurrency manager and immediately
> ```

a request -> requests
___
*[pkg/storage/concurrency/concurrency_control.go, line 199 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jBbZa5Hea02QbL8GE:-M-jBbZa5Hea02QbL8GF:b-s0cxg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L199)):*
> ```Go
> 	// HandleTransactionPushError consumes a TransactionPushError by informing
> 	// the concurrency manager about a transaction record that could not be
> 	// pushed during request evaluation (while holding latches). After doing so,
> ```

Is the command running into this necessarily a PushTxn? If not, what's an example that calls into this? Having trouble rationalizing what this is for. (I'm paging this all back in, so I might be too good of an approximation to someone who just walked into this package for the first time)
___
*[pkg/storage/concurrency/concurrency_control.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jC9ZA36u6jO0jqETw:-M-jC9ZBA0sgObx-BgoP:b9liq68) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L215)):*
> ```Go
> 	// OnLockUpdated informs the concurrency manager that a transaction has
> 	// updated or released a lock or range of locks that it previously held.
> 	OnLockUpdated(context.Context, roachpb.Intent)
> ```

The comment on OnLockAcquired also states that it's called when "a txn has ... updated an existing lock it already held". How is this different? Also the word "previously" means "already" here, right (like in the comment above)? Not that it "used to hold this lock but no longer".
___
*[pkg/storage/concurrency/concurrency_control.go, line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jCUF-5bi_pyoFWdzy:-M-jCUF-5bi_pyoFWdzz:bv1074i) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L222)):*
> ```Go
> type transactionManager interface {
> 	// OnTransactionUpdated informs the concurrency manager that a transaction's
> 	// status was updated by a successful transaction state transition.
> ```

what's a "successful transaction state transition"? Or rather, what constitutes an "unsuccessful" one? Maybe just removed everything after "updated".
___
*[pkg/storage/concurrency/concurrency_control.go, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jE0ar2wvXDG9eG5nb:-M-jDt3l69pnks2CnjWk:b-m8dw63) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L386)):*
> ```Go
> 	//
> 	// The first call to ScanAndEnqueue for a given request uses a nil
> 	// lockTableGuard and the subsequent calls reuse the previously returned
> ```

Why are there subsequent calls? Just when running into intents?
___
*[pkg/storage/concurrency/concurrency_control.go, line 428 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jEhfF2jGVRBY4zZyb:-M-jEhfF2jGVRBY4zZyc:b-ys1lgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L428)):*
> ```Go
> 	// lock's timestamp and strength, if necessary.
> 	//
> 	// For replicated locks, this must be called after the corresponding write
> ```

In steady state operation, we thus expect calls to `AddDiscoveredLock` to be rare, correct?
___
*[pkg/storage/concurrency/concurrency_control.go, line 501 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jHo19DWG_Hj3wF5EI:-M-jHo1A08ypnqc1q6D2:by3oxlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L501)):*
> ```Go
> 	// not retrieved, since it is not necessary for the waiter to see every
> 	// state transition.
> 	NewStateChan() <-chan struct{}
> ```

Why `New`?

Have you considered `StateChan() (<-chan struct{}, bool)` which subsumes ShouldWait (returning a nil chan if the bool is false)?
___
*[pkg/storage/concurrency/concurrency_control.go, line 551 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jIZ2WEf12G39wgQQz:-M-jIZ2WEf12G39wgQR-:b-5gc06k) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L551)):*
> ```Go
> // txnWaitQueue holds a collection of wait-queues for transaction records.
> // Conflicting transactions, known as "pushers", sit in a q [...]

2020-02-10 22:27 UTC, nvb reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44787)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @sumeerbhola, and @tbg)

___
*[pkg/storage/concurrency/concurrency_control.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R28pBALs3MWFb5-vd:-M-l0ydL4DnS_3vs38os:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L171)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not sure if we care, but look at the opaque godoc the current code causes:

```
type Manager interface {
    // contains filtered or unexported methods
}
```

if you embedded exported interfaces, it would render better. As is, all of the method comments are hidden.
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 187 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-R-G--D-hpMtJ7BBx9:-M-l11lG1p3LllcHOFjr:b-d0gwg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9adea73ef5cc8a17b656846e78fff5c385e00e3/pkg/storage/concurrency/concurrency_control.go#L187)):*
> The new guard won't hold any latches, right? So the caller will use it to call into SequenceReq?

Yes, exactly.

> Does this preserve fairness (e.g. by putting the txn at the head of the wait queues for all latches it held)?

The new guard will still hold its place in lock wait-queues and will preserve its lockTable seqnum, which preserves fairness.
___
*[pkg/storage/concurrency/concurrency_control.go, line 118 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-j9dis8ZC4XnMVIuF2:-M-l0djA5hSivSP0SaHK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L118)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

a request -> requests
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 199 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jBbZa5Hea02QbL8GE:-M-l1HqvEABe8cMg-efQ:bln1dyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L199)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is the command running into this necessarily a PushTxn? If not, what's an example that calls into this? Having trouble rationalizing what this is for. (I'm paging this all back in, so I might be too good of an approximation to someone who just walked into this package for the first time)
</blockquote></details>

Done. Added examples usages of these two methods as well.
___
*[pkg/storage/concurrency/concurrency_control.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jC9ZA36u6jO0jqETw:-M-l4v3f6Z48O59Ut3Xv:b7sgs1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L215)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The comment on OnLockAcquired also states that it's called when "a txn has ... updated an existing lock it already held". How is this different? Also the word "previously" means "already" here, right (like in the comment above)? Not that it "used to hold this lock but no longer".
</blockquote></details>

Changed the word "updated" to "re-acquired". The difference here is that the first method is used during writes and the second method is used during intent resolution.
___
*[pkg/storage/concurrency/concurrency_control.go, line 222 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jCUF-5bi_pyoFWdzy:-M-l5AR--Wc44SCr3wZG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L222)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

what's a "successful transaction state transition"? Or rather, what constitutes an "unsuccessful" one? Maybe just removed everything after "updated".
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jE0ar2wvXDG9eG5nb:-M-l5DszDHZkuntOvQFV:b3e16n0) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L386)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why are there subsequent calls? Just when running into intents?
</blockquote></details>

No, this also gets called after waiting in lock wait-queues. A request is only safe to proceed when it performs an entire scan through the lockTable and only finds conflicting lockStates which are released and which it is already at the head of the queue for.
___
*[pkg/storage/concurrency/concurrency_control.go, line 428 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jEhfF2jGVRBY4zZyb:-M-l5YwT6PUCVziek3o9:b-yxdo45) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L428)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

In steady state operation, we thus expect calls to `AddDiscoveredLock` to be rare, correct?
</blockquote></details>

Yes, as long as we decide to put all replicated locks into the lockTable immediately even while they're still stored outside of it. 
___
*[pkg/storage/concurrency/concurrency_control.go, line 501 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jHo19DWG_Hj3wF5EI:-M-l5mMp06y87bgGlIv1:brbihmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L501)):*
This is meant to be read as "new state" chan, not new "state chan".

> Have you considered StateChan() (<-chan struct{}, bool) which subsumes ShouldWait (returning a nil chan if the bool is false)?

That's not a bad idea, although it doesn't really fit with #44885.
___
*[pkg/storage/concurrency/concurrency_control.go, line 551 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jIZ2WEf12G39wgQQz:-M-l66Gz7TAo4Kaqqc-W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L551)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

an extant
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 584 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jIzQJ3xIJ2aLbUekN:-M-l69PN5VE_z_wAA-xI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L584)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

must
</blockquote></details>

Done.
___
*[pkg/storage/concurrency/concurrency_control.go, line 713 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44787#-M-jJwqK2mzWT1NMHDK1:-M-l69pnEnBlGrDIJky3:bk15i09) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a799a1a3ebe9da5d35aa7407fe4d949f9215da/pkg/storage/concurrency/concurrency_control.go#L713)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

any reason you're spelling out the struct initializers?
</blockquote></details>

I was getting "unused field" errors without this. This should all be gone soon.
___
*[pkg/storage/concurrency/lock_table.go, line 183 at r5](https://reviewable.io/r [...]

2020-02-10 22:59 UTC, nvanbenschoten commented
bors r+

2020-02-10 23:40 UTC, merged