sql: add support for temporary sequences
cockroachdb/cockroach pull request #44806
Opened 2020-02-06 13:18 UTC by otan

Resolves https://github.com/cockroachdb/cockroach/issues/44642.

This PR adds support for creating temporary sequences:
* Modified create_sequence.go to re-use the same logic for checking
whether the schema exists.
* Modified other callers (implicit sequence creators) to create
temporary sequences if required.
* Modified schema cleanup to take care of sequences, adding on the
necessary dirty work to clean up any permanent tables requiring access
to the temporary schema.

Release note (sql change): If temporary table creation is enabled, users
now have the ability to create temporary sequences as well.

2020-02-06 13:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44806)
<!-- Reviewable:end -->

2020-02-10 16:32 UTC, solongordon requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/temporary_schema.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-js1G8EPIrqzRbACk_:-M-js1G92WtHaOY79Z85:bkyjrk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema.go#L218)):*
> ```Go
> 						return err
> 					}
> 					dependentColIDs := make(map[sqlbase.ColumnID]struct{}, len(d.ColumnIDs))
> ```

You can use `util.FastIntSet` for such cases to avoid unnecessary allocations.
___
*[pkg/sql/temporary_schema.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-jt80e6LqrCA8mOEbm:-M-jt80e6LqrCA8mOEbn:bnymv7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema.go#L229)):*
> ```Go
> 								txn,
> 								fmt.Sprintf(
> 									"ALTER TABLE %s.%s.%s ALTER COLUMN %s DROP DEFAULT",
> ```

We need to be careful here to handle "interesting" names: those with capital letters, spaces, double quotes, etc. Perhaps this is broken for tables and views too. I don't remember the appropriate incantation for this offhand but let me know if you have trouble finding it.
___
*[pkg/sql/temporary_schema_test.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-jwBwj5BQbnSH99ft8:-M-jwBwj5BQbnSH99ft9:b-p2cr0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema_test.go#L47)):*
> ```Go
> CREATE TEMP SEQUENCE a_sequence;
> CREATE TEMP VIEW a_view AS SELECT a FROM a;
> CREATE TABLE perm_table (a int DEFAULT nextval('a_sequence'), b int);
> ```

Can we test the end state of this table after the temp sequence is cleaned up, i.e. that the DEFAULT value is appropriately removed?


<!-- Sent from Reviewable.io -->

2020-02-10 16:51 UTC, otan commented
___
*[pkg/sql/temporary_schema.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-js1G8EPIrqzRbACk_:-M-k-h5r522B2JdtPZgf:bb3ym8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema.go#L218)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

You can use `util.FastIntSet` for such cases to avoid unnecessary allocations.
</blockquote></details>

did it ; seems like we can totally use this way though since we already know the size. doesn't make a huge difference :P 


<!-- Sent from Reviewable.io -->

2020-02-10 16:56 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/temporary_schema.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-js1G8EPIrqzRbACk_:-M-k0VJ93G45gkZW9aGb:bb7vm1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema.go#L218)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

did it ; seems like we can totally use this way though since we already know the size. doesn't make a huge difference :P 
</blockquote></details>

Yeah definitely not a big difference, though I believe it'll be one allocation for the `map` vs. zero for the `FastIntSet` (as long as the column IDs are < 64).


<!-- Sent from Reviewable.io -->

2020-02-10 18:39 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/temporary_schema.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-jt80e6LqrCA8mOEbm:-M-kOYcY0LvbWtqHmaMp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema.go#L229)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

We need to be careful here to handle "interesting" names: those with capital letters, spaces, double quotes, etc. Perhaps this is broken for tables and views too. I don't remember the appropriate incantation for this offhand but let me know if you have trouble finding it.
</blockquote></details>

Done.
___
*[pkg/sql/temporary_schema_test.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-jwBwj5BQbnSH99ft8:-M-kI1bw9XJXqYdckMw2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c2e7e47ed06625163a96a7046785c49b781ac4c/pkg/sql/temporary_schema_test.go#L47)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Can we test the end state of this table after the temp sequence is cleaned up, i.e. that the DEFAULT value is appropriately removed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-10 19:06 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44806)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @solongordon)

___
*[pkg/sql/temporary_schema.go, line 271 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44806#-M-kTdfQ3erYUQ5Na_mI:-M-kTdfQ3erYUQ5Na_mJ:b-x29ksr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5cc92b6f5b6041b950ddc9d435abc8110feef7d/pkg/sql/temporary_schema.go#L271)):*
> ```Go
> 						tbName.SchemaName.String(),
> 						tree.NameString(tbName.Table()),
> 					),
> ```

Minor: It looks like maybe you could just use `tbName.FQString()` here. (And perhaps in the other spot too, though you would need to make a `TableName` struct first.)


<!-- Sent from Reviewable.io -->

2020-02-10 20:30 UTC, otan commented
bors r=solongordon

2020-02-10 22:19 UTC, merged