roachtest: fix django and sqlalchemy instability
cockroachdb/cockroach pull request #44940
Opened 2020-02-10 21:58 UTC by rafiss

The Django tests require more memory because of lots of load under
schema changes.

The sqlalchemy tests had a setup/installation issue that is resolved by
using a newer Python version

Release note: None

2020-02-10 21:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44940)
<!-- Reviewable:end -->

2020-02-11 18:33 UTC, apantel requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44940)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

___
*[pkg/cmd/roachtest/sqlalchemy.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44940#-M-pWX2b9K8zZmlOndNH:-M-pWX2b9K8zZmlOndNI:bwclt5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/93eaf8f01c8b3db377e25d85e40305d6049d309a/pkg/cmd/roachtest/sqlalchemy.go#L68)):*
> ```Go
> 
> 		if err := repeatRunE(
> 			ctx, c, node, "update apt-get", `sudo apt-get -qq update`,
> ```

Do you need this twice?


<!-- Sent from Reviewable.io -->

2020-02-11 18:35 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44940)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel)

___
*[pkg/cmd/roachtest/sqlalchemy.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44940#-M-pWX2b9K8zZmlOndNH:-M-pX27q-IWXyA4aD1RB:b-uniyj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/93eaf8f01c8b3db377e25d85e40305d6049d309a/pkg/cmd/roachtest/sqlalchemy.go#L68)):*
<details><summary><i>Previously, apantel (Adam Pantel) wrote…</i></summary><blockquote>

Do you need this twice?
</blockquote></details>

no, thanks for catching that


<!-- Sent from Reviewable.io -->

2020-02-11 20:31 UTC, apantel approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44940#-:-M-pwjad2gxpRk6L3Kk6:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel)



<!-- Sent from Reviewable.io -->

2020-02-11 21:56 UTC, rafiss commented
bors r+

2020-02-11 22:49 UTC, merged