colexec: implement online aggregation for hash aggregator
cockroachdb/cockroach pull request #44966
Opened 2020-02-11 16:09 UTC by Azhng

This PR change the implementation of hash aggregator to online aggregation.

Since the online aggregation implementation no longer uses `orderedAggregator`,
the order of the output is no longer guaranteed. Therefore the aggregator tests
are updated to use `unorderedVerifier` for hash aggregator.

Closes #41678

2020-02-11 16:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44966)
<!-- Reviewable:end -->

2020-02-11 21:35 UTC, asubiotto requested changes
Took a first pass. Great job getting this out so quickly!

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-qAMX-Eqhypyz9WkIx:b-lctw8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/hash_aggregator.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pRHZS378AwAawoWPh:-M-pRHZS378AwAawoWPi:b-wqf8bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L25)):*
> ```Go
> 
> const (
> 	hashAggregatorBatchBufferLimit        = uint16(1)
> ```

nit: a name like `hashAggregatorDefaultNumBufferedBatches` seems clearer to me. Also, I don't think you need to do the cast to a `uint16`.
___
*[pkg/sql/colexec/hash_aggregator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pQD-L20ZE8LYtFeaW:-M-pQD-L20ZE8LYtFeaX:bk7wz9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L26)):*
> ```Go
> const (
> 	hashAggregatorBatchBufferLimit        = uint16(1)
> 	hashAggregatorMaximumBatchBufferLimit = uint16(63) // 2^16 / BatchSize() - 1
> ```

I think this constant should be the number of tuples, not the number of batches and should just be `math.MaxUint16`. The problem with using the number of batches is that `BatchSize` is variable, so that could change. The input batch could also have a selection vector, so you would only need to buffer 1 tuple, even though the batch has n tuples.
___
*[pkg/sql/colexec/hash_aggregator.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pRkXc6BVNKq7lZvYy:-M-pRkXc6BVNKq7lZvYz:b-x9i68r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L28)):*
> ```Go
> 	hashAggregatorMaximumBatchBufferLimit = uint16(63) // 2^16 / BatchSize() - 1
> 
> 	hashAggregatorBuffering = iota
> ```

We usually would put these constants below `hashAggregatorState` and specify the type, i.e.:
```
hashAggregatorBuffering hashAggregatorState = iota
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pS3bAE-OkZ1LLEPhm:-M-pS3bAE-OkZ1LLEPhn:bs1lghf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L45)):*
> ```Go
> 	aggFuncMap hashAggFuncMap
> 
> 	// type of each column
> ```

nit: Throughout the file, comments should be capitalized and end with a period. Field comments also usually start with the field name, e.g.: "valTypes contains the types for each input column"
___
*[pkg/sql/colexec/hash_aggregator.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pcFyI6dMN5qzu0eOh:-M-pcFyI6dMN5qzu0eOi:b1fwxce) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L59)):*
> ```Go
> 	buffer            coldata.Batch
> 
> 	pendingOutput  bool
> ```

tip if you want it: sometimes we group fields that are used in a certain state together just to organize it better, e.g.:
```
outputState struct {
    pendingOutput bool
    resumeHashCode uint64
    ....
}
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pSTkU-QQ1JTURgC4P:-M-pSTkU-QQ1JTURgC4Q:bi086pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L75)):*
> ```Go
> }
> 
> // HashAggregator is an operator that performs aggregation based on
> ```

This will probably give you a lint error since function comments need to start with the name of the function. Also, this comment describes the operator, not the constructor, so I think it would be better placed above the `hashAggregator` struct.
___
*[pkg/sql/colexec/hash_aggregator.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pSzp0BqBy-h75Q1TZ:-M-pSzp0BqBy-h75Q1T_:bbx49to) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L110)):*
> ```Go
> 	}
> 
> 	for _, col := range groupCols {
> ```

TODO(asubiotto)
___
*[pkg/sql/colexec/hash_aggregator.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pUhDy-Ajt38rY_sB8:-M-pUhDy-Ajt38rY_sB9:b-k6od1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L146)):*
> ```Go
> 
> 	bufferLimit := hashAggregatorBatchBufferLimit
> 	if bufferLimit > hashAggregatorMaximumBatchBufferLimit {
> ```

Similar to above, I think we want to specify these limits in number of tuples, not number of batches since the number of input batches doesn't correspond 1:1 to the number of tuples buffered. The default would be `coldata.BatchSize()` with a maximum of `math.Uint16`. Also, this limit should be specified using some sort of testing knob so that we can see how performance changes with this knob. This could probably be a private variable on the struct that is set in benchmarks/tests after casting the returned operator.
___
*[pkg/sql/colexec/hash_aggregator.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pXN-l2NnvZOjC61W1:-M-pXN-l2NnvZOjC61W2:bmbevxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L150)):*
> ```Go
> 	}
> 
> 	batchBufferTupleLimit := bufferLimit * coldata.BatchSize()
> ```

I think this currently could lead to overflow if `coldata.BatchSize()` > 1024, right?
___
*[pkg/sql/colexec/hash_aggregator.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pWwybDeoZOAdTCi59:-M-pWwyc2waLTwDNBg8h:bbvi9r5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L188)):*
> ```Go
> 		case hashAggregatorBuffering:
> 			if op.needToResetBuffer {
> 				op.buffer = op.allocator.NewMemBatchWithSize(op.valTypes, int(op.batchBufferTupleLimit))
> ```

Hmm, why do we need to allocate a new batch? I don't think this buffer is returned downstream, so we can probably just call `ResetInternalBatch` here. Also, in which cases do we not need to reset the buffer?
___
*[pkg/sql/colexec/hash_aggregator.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-paf_I-q7vkyFQYev2:-M-paf_I-q7vkyFQYev3:btd6o6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L192)):*
> ```Go
> 
> 			// Buffering up input batches.
> 			bufferedBatchCount := op.bufferBatch(ctx)
> ```

Do we need to return the number of buffered batches? Maybe a boolean that indicates that no data was buffered and the input was finished is more specific.
___
*[pkg/sql/colexec/hash_aggregator.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-p_Fpl8s5aJy6xzdWi:-M-p_Fpl8s5aJy6xzdWj:b-dglso5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L199)):*
> ```Go
> 			}
> 
> 			sels := op.buildSelectionForHashCode(ctx)
> ```

I wonder if it would be good to extract this logic into a separate `hashAggregatorAggregatingState` to not combine buffering and aggregating into one state.
___
*[pkg/sql/colexec/hash_aggregator.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-puk7m0I5BFFTS5_9b:-M-puk7m0I5BFFTS5_9c:bexpo33) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L314)):*
> ```Go
> 	for selIdx, hashCode := range hashBuff [...]

2020-02-12 21:30 UTC, yuzefovich reviewed
I left some comments while I couldn't fall asleep last night but didn't go through the whole PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-vIUpD8JRjx87UoeA1:bcyxwbg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/hash_aggregator.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pRkXc6BVNKq7lZvYy:-M-szDfR11O83qmJfgXC:bt9vxn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We usually would put these constants below `hashAggregatorState` and specify the type, i.e.:
```
hashAggregatorBuffering hashAggregatorState = iota
```
</blockquote></details>

Also, for the "states" of the operator a short description might be beneficial.
___
*[pkg/sql/colexec/hash_aggregator.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-szzF36JNXyt00ZD5m:-M-szzF36JNXyt00ZD5n:b-std4fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L78)):*
> ```Go
> // specified grouping columns.
> // This operator performs aggregation in online fashion. It buffers the
> // input up to a certain threshold. Then each group in input is hash to
> ```

I'd like to see a comment explaining what "certain threshold" is. Is it what is now `hashAggregatorMaximumBatchBufferLimit`? If so, I'd mention it explicitly.

What is "group" in this context? I feel like we first will hash the tuples according to the grouping columns and only then we will have "groups" (with possible hash collisions).
___
*[pkg/sql/colexec/hash_aggregator.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-t-gYXCQDpIPQAtFjN:-M-t-gYXCQDpIPQAtFjO:b-nho7ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L80)):*
> ```Go
> // input up to a certain threshold. Then each group in input is hash to
> // a bucket and the operator lazily creates aggregation functions for
> // each group. After all input is exhausted, the operator begin to write
> ```

nit: `s/begin/begins/g`.
___
*[pkg/sql/colexec/hash_aggregator.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pWwybDeoZOAdTCi59:-M-t10yGDZoYRlvUQk5f:bxgjg9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L188)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, why do we need to allocate a new batch? I don't think this buffer is returned downstream, so we can probably just call `ResetInternalBatch` here. Also, in which cases do we not need to reset the buffer?
</blockquote></details>

Yeah, we definitely don't want to create a new batch here. Reusing the old buffer should give a nice speedup.
___
*[pkg/sql/colexec/hash_aggregator.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-t35KHDZIU2QTjY_0V:-M-t35KHDZIU2QTjY_0W:b-hqkjqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L214)):*
> ```Go
> 						for fnIdx, fn := range aggFunc.fns {
> 							fn.SetOutputIndex(int(curOutputIdx))
> 							fn.Compute(coldata.ZeroBatch, op.aggCols[fnIdx])
> ```

I think the fact that we're passing in a zero batch in order to "flush" the current aggregation state deserves a comment.
___
*[pkg/sql/colexec/hash_aggregator.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-t1oeZ8ogIysS5FfNr:-M-t1oeZ8ogIysS5FfNs:bamxgwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L305)):*
> ```Go
> 			op.buffer.ColVec(int(colIdx)),
> 			uint64(nKeys),
> 			nil,
> ```

nit: this is `sel` argument, right? It's beneficial to add a comment like `/* sel */` (I use a rule of thumb - if Goland highlights the argument name, then I should put it into an inline comment).
___
*[pkg/sql/colexec/hash_aggregator.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-puk7m0I5BFFTS5_9b:-M-t2WG6DQGupCANkYZ0:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L314)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if we can find a way to not reallocate a selection vector for each new group. This could be a performance hit. Maybe if we kept `sels` around as a scratch object on the hash aggregator and reset it here (i.e. `for each hashCode: sels[hashCode] = sels[hashCode][:0]`) we could append and allocate a new selection vector if non-existent. We could probably do something more clever too but probably not necessary.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2020-02-13 00:25 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pQD-L20ZE8LYtFeaW:-M-thjffEvCIVnOKULFU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L26)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this constant should be the number of tuples, not the number of batches and should just be `math.MaxUint16`. The problem with using the number of batches is that `BatchSize` is variable, so that could change. The input batch could also have a selection vector, so you would only need to buffer 1 tuple, even though the batch has n tuples.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pRkXc6BVNKq7lZvYy:-M-thpY47GW9rUuoD0UH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L28)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We usually would put these constants below `hashAggregatorState` and specify the type, i.e.:
```
hashAggregatorBuffering hashAggregatorState = iota
```
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pcFyI6dMN5qzu0eOh:-M-uWsli-BqUl6Hi1DNj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L59)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

tip if you want it: sometimes we group fields that are used in a certain state together just to organize it better, e.g.:
```
outputState struct {
    pendingOutput bool
    resumeHashCode uint64
    ....
}
```
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pSTkU-QQ1JTURgC4P:-M-tjBdS1Zz2VhZodwM8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L75)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This will probably give you a lint error since function comments need to start with the name of the function. Also, this comment describes the operator, not the constructor, so I think it would be better placed above the `hashAggregator` struct.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-szzF36JNXyt00ZD5m:-M-vnKoy5MUK1uFiGm5Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L78)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd like to see a comment explaining what "certain threshold" is. Is it what is now `hashAggregatorMaximumBatchBufferLimit`? If so, I'd mention it explicitly.

What is "group" in this context? I feel like we first will hash the tuples according to the grouping columns and only then we will have "groups" (with possible hash collisions).
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pSzp0BqBy-h75Q1TZ:-M-vvCkv9w39Y8hGL9Vn:b-5bznom) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

TODO(asubiotto)
</blockquote></details>

Is there any issue here that needs to be addressed ? 
___
*[pkg/sql/colexec/hash_aggregator.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pUhDy-Ajt38rY_sB8:-M-vnYWa8bE09icuQXW4:b-d91l8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L146)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Similar to above, I think we want to specify these limits in number of tuples, not number of batches since the number of input batches doesn't correspond 1:1 to the number of tuples buffered. The default would be `coldata.BatchSize()` with a maximum of `math.Uint16`. Also, this limit should be specified using some sort of testing knob so that we can see how performance changes with this knob. This could probably be a private variable on the struct that is set in benchmarks/tests after casting the returned operator.
</blockquote></details>

Done.

Actually I think the maximum value should be `math.MaxUint16 - coldata.BatchSize()`, because by the time we detect we have exceed our tuple limit, number of tuples in the buffer has already exceed the limit and some tuples in the buffer will already be outside of the range of uint16.
___
*[pkg/sql/colexec/hash_aggregator.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pXN-l2NnvZOjC61W1:-M-vpGxPA0aM1lju3eLK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L150)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this currently could lead to overflow if `coldata.BatchSize()` > 1024, right?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pWwybDeoZOAdTCi59:-M-toRh44j-7c_i86DuE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L188)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, why do we need to allocate a new batch? I don't think this buffer is returned downstream, so we can probably just call `ResetInternalBatch` here. Also, in which cases do we not need to reset the buffer?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-paf_I-q7vkyFQYev2:-M-tjFcR3UYbcq1ve2-O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L192)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we need to return the number of buffered batches? Maybe a boolean that indicates that no data was buffered and the input was finished is more specific.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-p_Fpl8s5aJy6xzdWi:-M-toTtB3U_eg8aWKeds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L199)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if it would be good to extract this logic into a separate `hashAggregatorAggregatingState` to not combine buffering and aggregating into one state.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-t35KHDZIU2QTjY_0V:-M-vlkN61ZeHSPxD3J38:b-896fix) ([raw file](https://githu [...]

2020-02-13 00:31 UTC, Azhng reviewed
New update has few major changes. 

1) inverted loop order in `match()`.
2) `match()` and `onlineAgg` no longer allocate new slices for `matched` and `remaining` selection vectors. It reuses previously allocated slices as well as the selection vector of the `scratch` batch.
3) split the `buffering` state into `buffering` and `aggregating` states
4) each aggregation group no longer store a slice of `Vec` as its key. Instead, it stores a `keyIdx` which points to the `keyMapping` batch stored inside the aggregator. This eliminates the needs to calling `.Window()` on each `Vec`. 

1) + 4) boosted the performance by another 20% ~ 40% compared to the previous draft. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-vvxiv4HuS3xoQyQGf:b-ummf6d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-13 00:36 UTC, Azhng reviewed
Another note:

An observation I had is for `TestAggregatorRandom`, when the batch size is greater than 1500, it takes a very long time for `unorderedVerifier` to finish comparing the result. Maybe instead of reducing number of input batches, we should somehow limit the batch size in the `TestAggregatorRandom` ? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-vy1nvEGXKsZRGco4C:bvmpaf0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-13 00:44 UTC, Azhng reviewed
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-w-J0_8_PkNNBE1qKN:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-13 16:25 UTC, asubiotto requested changes
This is starting to look good! By the way, remember that you can provide a comparison with the aggregator version on master using:
`COCKROACH_RANDOMIZE_BATCH_SIZE=false BENCHES=BenchmarkAggregator/<hash subtest> ./scripts/bench master <your branch>`
I, for one, would be interested in the diff. You might also consider adding more lightweight types to `BenchmarkAggregator` (i.e. non-decimal types) to get a better idea of the hash aggregator's code performance (i.e. we don't sink a lot of time in performing operations)

> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M-zLxGs8aCRdIdsM5GK:b-ia2t5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z4cxjBJE-hSY28wWq:-M-z4cxk0EW3E6t3cZWf:b-s8qgpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/aggregator_test.go#L72)):*
> ```Go
> // This is a wrapper around NewHashAggregator so its signature is compatible
> // with orderedAggregator.
> func newHashAggregatorForTest(
> ```

nit: since it's only used once, I would probably just declare it directly below:
```
new: func(allocator etc....) (..) {
    return NewHashAggregator()
},
new: NewOrderedAggregator,
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pSzp0BqBy-h75Q1TZ:-M-z6_UaETyG_Eq2woRm:b-w29niq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L110)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Is there any issue here that needs to be addressed ? 
</blockquote></details>

No, was just adding a personal note to come back to this and forgot to remove it.
___
*[pkg/sql/colexec/hash_aggregator.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pvYsw3661KFLrY0b_:-M-zClDWBEtGsgLRKt7s:b-7xppm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L335)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Updated the `match()` so the code looks quite different now. 
My idea was to have `remaining` overwritten every time we loop through an `aggFunc` so that eventually if there's any elements in the `remaining` left, it means we need to create more aggregation function.
</blockquote></details>

OK, that makes more sense now.
___
*[pkg/sql/colexec/hash_aggregator.go, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-pwK_0EMr-3B8yMmV1:-M-zGbAd8fPFfXkOmi0a:bd9r7ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7ea332a5f0b75df5d50f4bb13ec693797e91ee/pkg/sql/colexec/hash_aggregator.go#L421)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.

Updated the `match` function to directly reuse previously allocated slices without allocating any new ones. 

// Was a huge pain to debug though
</blockquote></details>

Thanks! Looks great
___
*[pkg/sql/colexec/hash_aggregator.go, line 113 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z5x4z9ZS_W55up-ZW:-M-z5x4z9ZS_W55up-ZX:bwq91w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L113)):*
> ```Go
> 	// bufferedBatch because in the worst case where all keys in the grouping
> 	// columns are distinct, we need to store every single key in the input.
> 	keyMappig struct {
> ```

nit: `s/keyMappig/keyMapping`
___
*[pkg/sql/colexec/hash_aggregator.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z6pCl1PCGkfT1JNiG:-M-z6pCl1PCGkfT1JNiH:bb8scvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L240)):*
> ```Go
> 	op.input.Init()
> 
> 	op.output.Batch = op.allocator.NewMemBatch(op.outputTypes)
> ```

nit: @yuzefovich wasn't there something about not wanting to allocate in `Init` to avoid OOM errors?
___
*[pkg/sql/colexec/hash_aggregator.go, line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z7OxECPUNJgHzDI5D:-M-z7OxECPUNJgHzDI5E:b-uiqd8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L336)):*
> ```Go
> }
> 
> func (op *hashAggregator) bufferBatch(ctx context.Context) (done bool) {
> ```

Please add a comment explaining the return value and how a caller should interpret it. Also, I don't think this needs to be a named return parameter. Usually these are used when the code is easier to understand when the variable is pre-defined and you would write `var done bool` at the start of your method anyway.
___
*[pkg/sql/colexec/hash_aggregator.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z9vDH-JpXI0I6PjIe:-M-z9vDH-JpXI0I6PjIf:b2d5rvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L365)):*
> ```Go
> }
> 
> // Build selection vector for each hash code.
> ```

nitty nit: the comment should be `buildSelectionForHashCode builds a selection vector etc...`. However, I don't think you need a comment here since the name of the method is pretty clear.
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z9oK38hboBNsxznQa:-M-z9oK38hboBNsxznQb:byf5x2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L366)):*
> ```Go
> 
> // Build selection vector for each hash code.
> func (op *hashAggregator) buildSelectionForHashCode(ctx context.Context) {
> ```

`s/ForHashCode/ForEachHashCode` might be clearer.
___
*[pkg/sql/colexec/hash_aggregator.go, line 368 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zA5VC9xx60xWd2dBB:-M-zA5VC9xx60xWd2dBC:b3ufain) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L368)):*
> ```Go
> func (op *hashAggregator) buildSelectionForHashCode(ctx context.Context) {
> 	nKeys := op.scratch.Length()
> 	initHash(op.hashBuffer, uint64(nKeys), 1)
> ```

I think you should slice hashBuffer: `op.hashBuffer = op.hashBuffer[:nKeys]` at the start of this function to only get `nKeys`
___
*[pkg/sql/colexec/hash_aggregator.go, line 383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zAP6bAG36RF4iqbR9:-M-zAP6bAG36RF4iqbRA:b-vamvwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L383)):*
> ```Go
> 
> 	// Resets the selection vectors to reuse the memory allocated.
> 	for hashCode := range op.scratch.sels {
> ```

I think `range` ing over `op.scratch.sels` will loop over *all* the groups you've seen so far, right? I think this should be in the if statement below when you loop over the `hashBuffer`, i.e. only the codes you care about:
```
if _, ok := op.scratch. <...>; !ok {
   make()
} else {
   <reset> sel
}
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 387 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zAsMg6hkMz1VddizU:-M-zAsMg6hkMz1VddizV:b-nd7pb9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L387)):*
> ```Go
> 	}
> 
> 	for selIdx, hashCode := range hashBuffer {
> ```

Might be worth mentioning in the comment that it's ok to use `selIdx` as an index into `hashBuffer` because there is never a selection vector over [...]

2020-02-13 22:31 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 336 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z7OxECPUNJgHzDI5D:-M-zn54X-fGvbR0Hjx_i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L336)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Please add a comment explaining the return value and how a caller should interpret it. Also, I don't think this needs to be a named return parameter. Usually these are used when the code is easier to understand when the variable is pre-defined and you would write `var done bool` at the start of your method anyway.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z9vDH-JpXI0I6PjIe:-M-zQ-fjDgxrizmC0ZAf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L365)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nitty nit: the comment should be `buildSelectionForHashCode builds a selection vector etc...`. However, I don't think you need a comment here since the name of the method is pretty clear.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 366 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z9oK38hboBNsxznQa:-M-zQ-RZD2MyWxZmF_b5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L366)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/ForHashCode/ForEachHashCode` might be clearer.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 368 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zA5VC9xx60xWd2dBB:-M0-Nm8z7NOIYV8dcheT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L368)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you should slice hashBuffer: `op.hashBuffer = op.hashBuffer[:nKeys]` at the start of this function to only get `nKeys`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zAP6bAG36RF4iqbR9:-M0-eoyeAniCzm81XNPK:bs6or26) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L383)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think `range` ing over `op.scratch.sels` will loop over *all* the groups you've seen so far, right? I think this should be in the if statement below when you loop over the `hashBuffer`, i.e. only the codes you care about:
```
if _, ok := op.scratch. <...>; !ok {
   make()
} else {
   <reset> sel
}
```
</blockquote></details>

This causes performance hit when group size is large. See reply on line 400 for details. 
___
*[pkg/sql/colexec/hash_aggregator.go, line 387 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zAsMg6hkMz1VddizU:-M0-bK6u5wnMatABVVpM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L387)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be worth mentioning in the comment that it's ok to use `selIdx` as an index into `hashBuffer` because there is never a selection vector over `op.scratch`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 400 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zC6Sh9L72Nxjiu8Gp:-M0-UfjnBWiMGBkTQtcz:b-woh4tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L400)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Here you're `range`ing over every group in op.scratch.sels as well, i.e. looping over every group ever seen which is probably very inefficient (especially for the `groupSize=1` case). I would recommend keeping a scratch slice of `hashCodes` for processing that is reset and built in `buildSelectionForHashCode` that you then use here to access the selection vectors you actually want.
</blockquote></details>

Ran the benchmark on the version that only ranges over the hash codes the aggregator has seen in the current batch.
It turns out that it only causes the performance boost when the group size is small, but hurts the performance when the group size is large, I think this is because when the batch size is big, the `op.scratch.sels` is small, which is faster to iterate over when were are resetting `op.scratch.sels` inside `buildSelectionForEachHashCode` 

I'm hesitating on whether or not to add this change and the one on line 383. 

I only ran the benchmark on `AVG` aggregation. 

Benchmark looping over sels
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       	       5	 321515764 ns/op	   1.63 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        	       5	 317512178 ns/op	   1.65 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       	      10	 160907044 ns/op	   3.26 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        	      10	 160778892 ns/op	   3.26 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8     	     200	   6930876 ns/op	  75.65 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      	     200	   7148321 ns/op	  73.34 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    	     200	   6469877 ns/op	  81.04 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     	     200	   6520431 ns/op	  80.41 MB/s
```

Benchmark looping over new hash codes appeared in current batch
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       	       5	 236405214 ns/op	   2.22 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        	       5	 224763271 ns/op	   2.33 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       	      10	 113184056 ns/op	   4.63 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        	      10	 114047224 ns/op	   4.60 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8
     200	   9264131 ns/op	  56.59 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      	     200	   9331043 ns/op	  56.19 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    	     200	   8573078 ns/op	  61.16 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     	     200	   9388814 ns/op	  55.84 MB/s
```
___
*[pkg/sql/colexec/hash_aggregator.go, line 414 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zEJtF90BzYKvHHXDF:-M0-LSUq0QSPizJmiOlO:b-896fix) ([raw file](https://github.com/coc [...]

2020-02-14 00:37 UTC, Azhng reviewed
Updated to sort the tuples before comparing them in the `unorderedVerifier`, significant performance boost :smiley:  . Test runtime dropped from ~70s (with 10 batches) to ~5s (with 64 batches). 
Caught a new bug that when there are a lot of groups (groupSize=2 numInputBatches=64), `keyIdx` in the `hashAggFuncs` overflows and cannot address all the `keyMapping` since it's uint16. Changed it to uint64. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M006SnG27IzCycv4udK:bc5tqzr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-14 18:21 UTC, Azhng reviewed
Been having CI failures on `TestMergeJoiner`, but couldn't reproduce on my local machine. Any thoughts ? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M03vbbxE76KenkIQ_t7:brf7bcd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-14 21:43 UTC, Azhng reviewed
Turns out that using `unorderedVerifier` in the HashJoin test modify the order in expected test cases in the MergeJoin tests cause the `orderedVerifier` to fail. 
Fixed 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M04dlm_2DlQ5XehoW5r:b-bg8yla)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-18 13:33 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 400 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zC6Sh9L72Nxjiu8Gp:-M0NUxbe9WSXM549r9AH:b6yy1uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L400)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ran the benchmark on the version that only ranges over the hash codes the aggregator has seen in the current batch.
It turns out that it only causes the performance boost when the group size is small, but hurts the performance when the group size is large, I think this is because when the batch size is big, the `op.scratch.sels` is small, which is faster to iterate over when were are resetting `op.scratch.sels` inside `buildSelectionForEachHashCode` 

I'm hesitating on whether or not to add this change and the one on line 383. 

I only ran the benchmark on `AVG` aggregation. 

Benchmark looping over sels
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       	       5	 321515764 ns/op	   1.63 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        	       5	 317512178 ns/op	   1.65 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       	      10	 160907044 ns/op	   3.26 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        	      10	 160778892 ns/op	   3.26 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8     	     200	   6930876 ns/op	  75.65 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      	     200	   7148321 ns/op	  73.34 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    	     200	   6469877 ns/op	  81.04 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     	     200	   6520431 ns/op	  80.41 MB/s
```

Benchmark looping over new hash codes appeared in current batch
```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       	       5	 236405214 ns/op	   2.22 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        	       5	 224763271 ns/op	   2.33 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       	      10	 113184056 ns/op	   4.63 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        	      10	 114047224 ns/op	   4.60 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8
     200	   9264131 ns/op	  56.59 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      	     200	   9331043 ns/op	  56.19 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    	     200	   8573078 ns/op	  61.16 MB/s
BenchmarkAggregator/AVG/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     	     200	   9388814 ns/op	  55.84 MB/s
```
</blockquote></details>

Here is also the benchmark for `SUM` operation we can compare the metrics for the INT64 

```
name                                                                            old time/op    new time/op     delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-8         7.40ms ± 0%   229.67ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-8          7.29ms ± 0%   229.20ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-8         5.28ms ± 0%   108.39ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-8          5.26ms ± 0%   108.23ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-8       4.17ms ± 0%     2.90ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-8        4.99ms ± 0%     3.22ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-8      4.62ms ± 0%     2.65ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-8       5.62ms ± 0%     2.97ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       18.4ms ± 0%    238.9ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        17.4ms ± 0%    241.5ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       17.1ms ± 0%    114.0ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        20.2ms ± 0%    115.4ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8     13.7ms ± 0%      6.8ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      11.3ms ± 0%      6.7ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    12.0ms ± 0%      6.4ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     11.7ms ± 0%      6.4ms ± 0%   ~     (p=1.000 n=1+1)

name                                                                            old speed      new speed       delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-8       70.8MB/s ± 0%    2.3MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-8        71.9MB/s ± 0%    2.3MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-8       99.3MB/s ± 0%    4.8MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-8         100MB/s ± 0%      5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-8      126MB/s ± 0%    181MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-8       105MB/s ± 0%    163MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-8     113MB/s ± 0%    198MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-8     93.3MB/s ± 0%  176.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8     28.5MB/s ± 0%    2.2MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8      30.1MB/s ± 0%    2.2MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8     30.7MB/s ± 0%    4.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8      25.9MB/s ± 0%    4.5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8   38.2MB/s ± 0%   77.4MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8    46.6MB/s ± 0%   78.5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8  43.6MB/s ± 0%   81.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal [...]

2020-02-18 13:34 UTC, Azhng reviewed
RFAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0NVY3ZDGD1ruT4ZNQK:b-828fno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 400 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zC6Sh9L72Nxjiu8Gp:-M0NVMQR-6cJbT57iANb:bdayom8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L400)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Here is also the benchmark for `SUM` operation we can compare the metrics for the INT64 

```
name                                                                            old time/op    new time/op     delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-8         7.40ms ± 0%   229.67ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-8          7.29ms ± 0%   229.20ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-8         5.28ms ± 0%   108.39ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-8          5.26ms ± 0%   108.23ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-8       4.17ms ± 0%     2.90ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-8        4.99ms ± 0%     3.22ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-8      4.62ms ± 0%     2.65ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-8       5.62ms ± 0%     2.97ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8       18.4ms ± 0%    238.9ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8        17.4ms ± 0%    241.5ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8       17.1ms ± 0%    114.0ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8        20.2ms ± 0%    115.4ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8     13.7ms ± 0%      6.8ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8      11.3ms ± 0%      6.7ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8    12.0ms ± 0%      6.4ms ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8     11.7ms ± 0%      6.4ms ± 0%   ~     (p=1.000 n=1+1)

name                                                                            old speed      new speed       delta
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64-8       70.8MB/s ± 0%    2.3MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64-8        71.9MB/s ± 0%    2.3MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64-8       99.3MB/s ± 0%    4.8MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64-8         100MB/s ± 0%      5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64-8      126MB/s ± 0%    181MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64-8       105MB/s ± 0%    163MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64-8     113MB/s ± 0%    198MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64-8     93.3MB/s ± 0%  176.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64-8     28.5MB/s ± 0%    2.2MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64-8      30.1MB/s ± 0%    2.2MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64-8     30.7MB/s ± 0%    4.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64-8      25.9MB/s ± 0%    4.5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64-8   38.2MB/s ± 0%   77.4MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64-8    46.6MB/s ± 0%   78.5MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64-8  43.6MB/s ± 0%   81.6MB/s ± 0%   ~     (p=1.000 n=1+1)
Aggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64-8   44.7MB/s ± 0%   82.1MB/s ± 0%   ~     (p=1.000 n=1+1)
```
</blockquote></details>

^^^ This is the benchmark comparison between the current branch and the master branch. I think I posted it in the wrong place. 


<!-- Sent from Reviewable.io -->

2020-02-18 15:14 UTC, asubiotto requested changes
> Reviewed 1 of 7 files at r4, 7 of 7 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 535 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nqav35QC6gTn8kXEr:-M0Nqav4BEFaPfqgDD_i:bwedu24) ([raw file](https://github.com/cockroachdb/cockroach/blob/d989ea008eed5d650020e39432a9656d26c66ba9/pkg/sql/colexec/aggregator_test.go#L535)):*
> ```Go
> }
> 
> func TestAggregatorRandom(t *testing.T) {
> ```

I'm not sure I remember why we had to change the test like this. Could you remind me?
___
*[pkg/sql/colexec/aggregator_test.go, line 571 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NqiVnEXdV76p37V89:-M0NqiVnEXdV76p37V8A:b-7u7zev) ([raw file](https://github.com/cockroachdb/cockroach/blob/d989ea008eed5d650020e39432a9656d26c66ba9/pkg/sql/colexec/aggregator_test.go#L571)):*
> ```Go
> 										if expNulls[curGroup] {
> 											expectedTuples = append(expectedTuples, tuple{
> 												expRowCounts[curGroup], expCounts[curGroup], nil, nil, nil, nil,
> ```

I'm confused as to why we're expecting `NULL`s here
___
*[pkg/sql/colexec/hash_aggregator.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z6pCl1PCGkfT1JNiG:-M0Nglva3r3xBXgAsFOu:b-1llcg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L240)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: @yuzefovich wasn't there something about not wanting to allocate in `Init` to avoid OOM errors?
</blockquote></details>

@azhng I think you want to allocate these batches in the constructor rather than `Init` to error out early with a memory error if not enough memory.
___
*[pkg/sql/colexec/hash_aggregator.go, line 383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zAP6bAG36RF4iqbR9:-M0NjF0-4i9ZLAH7Xene:b-xgaa2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L383)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This causes performance hit when group size is large. See reply on line 400 for details. 
</blockquote></details>

Cool! Thanks for trying it out.
___
*[pkg/sql/colexec/hash_aggregator.go, line 400 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zC6Sh9L72Nxjiu8Gp:-M0NjY1h46_b4wyrOdPw:b-ralii) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L400)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

^^^ This is the benchmark comparison between the current branch and the master branch. I think I posted it in the wrong place. 
</blockquote></details>

Cool! Looks like there's a huge performance hit for small groups but a 2x performance gain for large groups, which is the expected case. This is looking good.
___
*[pkg/sql/colexec/hash_aggregator.go, line 136 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nfnh93Zw457JTQuWm:-M0Nfnh93Zw457JTQuWn:b-tlihb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L136)):*
> ```Go
> 
> 	testingKnobs struct {
> 		numOfHashBucket uint64
> ```

nit: `s/numOfHashBucket/numOfHashBuckets`. Also, could you add a comment about this and what it tests if set?
___
*[pkg/sql/colexec/hash_aggregator.go, line 407 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NjTYI9g5xastDQ6nB:-M0NjTYI9g5xastDQ6nC:bn0sa4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L407)):*
> ```Go
> }
> 
> // onlineAgg probes aggFuncMap using the built sels map and
> ```

nit: is this comment wrapped at 80 chars?
___
*[pkg/sql/colexec/hash_aggregator.go, line 426 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NjsVTC4gDofNzS7jN:-M0NjsVTC4gDofNzS7jO:b-2bzis3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L426)):*
> ```Go
> 			for _, aggFunc := range aggFuncs {
> 				// We write the selection vector of matched tuples directly into
> 				// 'matched' and selection vector of unmatched tuples into 'remaining'.
> ```

nit: is the reference to `matched` still relevant here?
___
*[pkg/sql/colexec/hash_aggregator.go, line 516 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NkvJ8CNT3ubs1ZY8E:-M0NkvJ8CNT3ubs1ZY8F:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L516)):*
> ```Go
> // aggregating group.
> type hashAggFuncs struct {
> ```

nit: extra line
___
*[pkg/sql/colexec/hash_aggregator.go, line 517 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NkzUz7UFVl20XV1je:-M0NkzUz7UFVl20XV1jf:bnpsapw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L517)):*
> ```Go
> type hashAggFuncs struct {
> 
> 	// keyIdx is the index of key of the current aggregating group, which is
> ```

nit: `s/index of key of the/index of the key for the`
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 74 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nnqjc-kGqlSJwt6FY:-M0Nnqjc-kGqlSJwt6FZ:b-orv7xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator_tmpl.go#L74)):*
> ```Go
> 	for selIdx, rowIdx := range sel {
> 		// {{if .LhsHasNulls}}
> 		// {{if .RhsHasNulls}}
> ```

What happens if lhs has nulls, i.e. the value is null but the right hand side doesn't? Don't we know that those won't be equal?
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 101 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NlZqcAPa3srCMRZ4i:-M0NlZqcAPa3srCMRZ4j:bchmu06) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator_tmpl.go#L101)):*
> ```Go
> var _ interface{} = execgen.UNSAFEGET
> 
> // match takes a selection vector and compare it against the values of the key
> ```

nit: `s/compare/compares`
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 103 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nlid_5Ngzwg4DuIQ2:-M0Nlid_5Ngzwg4DuIQ3:bx923vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator_tmpl.go#L103)):*
> ```Go
> // match takes a selection vector and compare it against the values of the key
> // of its aggregation function. It returns a selection vector representing the
> // unmatched tuples and a boolean to indicate whether or not if there is any
> ```

nit: `s/whether or not if there is/whether or not there are`.

Also, I think it might make more sense for the return values to be `bool, []uint16` instead of `[]uint16, bool` since the `[]uint16` is a side effect, but that's just personal preference so up to you.
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nm2RxEm4UzkAJJFmA:-M0Nm2RxEm4UzkAJJFmB:bhm2ije) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator_tmpl.go#L104)):*
> ```Go
> // of its aggregation function. It returns a selection vector representing the
> // unmatched tuples and a boolean to indicate whether or not if there is any
> // matching tuples. It dir [...]

2020-02-19 03:50 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0QZ-Z28hANTBMUeFzv:b-u5nrut) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
> ```Go
> 				result.Op, err = NewHashAggregator(
> 					NewAllocator(ctx, hashAggregatorMemAccount), inputs[0], typs, aggFns,
> 					aggSpec.GroupCols, aggCols, execinfrapb.IsScalarAggregate(aggSpec),
> ```

Does the new hash aggregator handle a case of an empty input when the aggregator is in scalar context?
___
*[pkg/sql/colexec/hash_aggregator.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z6pCl1PCGkfT1JNiG:-M0QVWSr-pDxI7K5oLcN:b-bp0ji3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L240)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

@azhng I think you want to allocate these batches in the constructor rather than `Init` to error out early with a memory error if not enough memory.
</blockquote></details>

After thinking a little bit more about this, I think in this case (since we don't have an "external hash aggregator") we should keep these allocations either in `Init` or doing lazy allocations in `Next`. The reason is that `SupportsVectorized` check will be creating all the operators, and moving the allocations from `Init` into the constructor will make that check more expensive.

In order to tell the planning code upfront about these allocations we could implement `InternalMemoryOperator` interface. I think it could wait though, it's something we could look into during the stabilization period (we haven't been very careful with this).
___
*[pkg/sql/colexec/hash_aggregator.go, line 457 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zKst47rQgraXJcgD7:-M0QWrkOEzZi6gSRNwEx:br3obdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L457)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think it's done.

Yeah, this is unfortunate, but I guess we have to come up with a linter rule to enforce this. It seems very subtle though :/
___
*[pkg/sql/colexec/hash_aggregator.go, line 117 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QUzHSD0bk7AoKpx4C:-M0QUzHSD0bk7AoKpx4D:blvbxu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator.go#L117)):*
> ```Go
> 
> 		// nextAvailableIdx is the next available slot inside the key mapping buffer.
> 		nextAvailableIdx uint64
> ```

Looks to me that `nextAvailableIdx` stores the length of the `bufferedBatch`, but the latter already has that field. I think you could reuse that.

Also, we're ok that we could hit a memory limit when appending to this buffered batch and we don't have a fallback mechanism, right?
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 47 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QXQ68CjidvUf1sOTA:-M0QXQ68CjidvUf1sOTB:b-cvlk54) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator_tmpl.go#L47)):*
> ```Go
> var _ int = math.MaxInt16
> 
> // _ASSIGN_CMP is the template function for assigning the result of comparing
> ```

nit: `s/CMP/NE/g`.
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 99 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QXXpr0RRaejWx5jV8:-M0QXXpr0RRaejWx5jV9:b-a75t3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator_tmpl.go#L99)):*
> ```Go
> 
> // Use execgen package to remove unused import warning.
> var _ interface{} = execgen.UNSAFEGET
> ```

nit: let's remove this and instead wrap import of `execgen` with template comments `//{/*` and `//*/}}`.
___
*[pkg/sql/colexec/utils_test.go, line 106 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QY4y81sCq-JlYpvuH:-M0QY4y81sCq-JlYpvuI:bx4zxp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/utils_test.go#L106)):*
> ```Go
> 
> 		switch typ := lhsVal.Type().Name(); typ {
> 		case "int", "int16", "int64":
> ```

What about `int32`?
___
*[pkg/sql/colexec/execgen/cmd/execgen/hash_aggregator_gen.go, line 35 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QYGiK3DllKe_ZkEv3:-M0QYGiL3eVu0XEH51q5:b-f49b7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/execgen/cmd/execgen/hash_aggregator_gen.go#L35)):*
> ```Go
> 
> 	assignCmpRe := makeFunctionRegex("_ASSIGN_NE", 3)
> 	s = assignCmpRe.ReplaceAllString(s, "{{.Assign $1 $2 $3}}")
> ```

nit: let's put arguments into quotes `"` and then remove quotes from the template file.


<!-- Sent from Reviewable.io -->

2020-02-19 14:30 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 535 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nqav35QC6gTn8kXEr:-M0P1ZMRBF-hB-N9N7IO:bapnew1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d989ea008eed5d650020e39432a9656d26c66ba9/pkg/sql/colexec/aggregator_test.go#L535)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I remember why we had to change the test like this. Could you remind me?
</blockquote></details>

It was because `TestAggregatorRandom` hand wrote the checking logic between actual and expected tuples (instead of using `verifier`s). It also effectively implemented `orderedVerifier` with its original implementation. This change is to make `TestAggregatorRandom` to use `orderedVerifier` for `orderedAggregator` and `unorderedVerifier` for `hashAggregator`. 
___
*[pkg/sql/colexec/aggregator_test.go, line 571 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NqiVnEXdV76p37V89:-M0P3CxmCqoKbMdSaGlP:bmynshe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d989ea008eed5d650020e39432a9656d26c66ba9/pkg/sql/colexec/aggregator_test.go#L571)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm confused as to why we're expecting `NULL`s here
</blockquote></details>

`expNulls` for the current group was set later in the if/else block in line 595 (that was part of the original testing code). Since we changed to use `Verifier`, we need to store all the expected values in `tuples{}`. Here we are just simulating the aggregation result of a group where all its values are `NULL`. 
___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0Sj5pz49GLMJM4Ru5I:b-m1rju1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Does the new hash aggregator handle a case of an empty input when the aggregator is in scalar context?
</blockquote></details>

I think @asubiotto pointed out that in that case only ordered aggregator will be created. So there is no need to handle empty input in a scalar context. 
___
*[pkg/sql/colexec/hash_aggregator.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z6pCl1PCGkfT1JNiG:-M0Sn7eJ7U5H_MmcZu5I:b8gulno) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L240)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

After thinking a little bit more about this, I think in this case (since we don't have an "external hash aggregator") we should keep these allocations either in `Init` or doing lazy allocations in `Next`. The reason is that `SupportsVectorized` check will be creating all the operators, and moving the allocations from `Init` into the constructor will make that check more expensive.

In order to tell the planning code upfront about these allocations we could implement `InternalMemoryOperator` interface. I think it could wait though, it's something we could look into during the stabilization period (we haven't been very careful with this).
</blockquote></details>

I'm a bit confused for the `InternalMemoryOperator` interface, 
  is it supposed to report the current memory usage of an operator 
   or 
  is it supposed to report the estimated memory usage of an operator
___
*[pkg/sql/colexec/hash_aggregator.go, line 457 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zKst47rQgraXJcgD7:-M0SoTXiC2xN2zm8KreT:bz6iecq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L457)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think it's done.

Yeah, this is unfortunate, but I guess we have to come up with a linter rule to enforce this. It seems very subtle though :/
</blockquote></details>

I wrap the `PerformOperation` around the outer for loop, did I miss something here? 
___
*[pkg/sql/colexec/hash_aggregator.go, line 407 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NjTYI9g5xastDQ6nB:-M0P8DK1AZljDe2PVh4o:bx3i0rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L407)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: is this comment wrapped at 80 chars?
</blockquote></details>

ah good catch, I thought I have fixed all of them. 
___
*[pkg/sql/colexec/hash_aggregator.go, line 426 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NjsVTC4gDofNzS7jN:-M0P8U0A30HDZJyqFbq2:b-8fn6fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator.go#L426)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: is the reference to `matched` still relevant here?
</blockquote></details>

Removed reference to `matched` 
___
*[pkg/sql/colexec/hash_aggregator.go, line 117 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QUzHSD0bk7AoKpx4C:-M0Sjm-5-AVU4YEvHqB5:b-ch6gix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Looks to me that `nextAvailableIdx` stores the length of the `bufferedBatch`, but the latter already has that field. I think you could reuse that.

Also, we're ok that we could hit a memory limit when appending to this buffered batch and we don't have a fallback mechanism, right?
</blockquote></details>

Updated to reuse `bufferedBatch.length` 

The memory usage of `bufferedBatch` is proportional to the number of the groups that we are performing aggregation on. The memory issue could happen when group size is too small and there are a lot of inputs, but I think this was the case that we chose not to handle. 
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 74 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Nnqjc-kGqlSJwt6FY:-M0SpRed6IkdRHtZlWAP:bvcfe86) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/hash_aggregator_tmpl.go#L74)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What happens if lhs has nulls, i.e. the value is null but the right hand side doesn't? Don't we know that those won't be equal?
</blockquote></details>

Added short circuit logic to handle that case. 
___
*[pkg/sql/colexec/utils_test.go, line 128 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0NpT4NBLhPHJ1ruXfM:-M0PAU3CDS5bRVFipLer:beevk5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ea39f0f265a61f6ff141bd45f70b3ca86021e20/pkg/sql/colexec/utils_test.go#L128)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would call out in a comment that `sort` returns a sorted copy of tuples. And just to check: do we want to do this, or can we do an in place sort?
</blockquote></details>

Done.

Returning a copy of the tuples is necessary, doing in place sort can change the order of some of the `expected` test cases, which can cause test failures if the tests is using `orderedVerifier`. 
___
*[pkg/sql/colexec/utils_test.go, line 106 at r9](https://reviewable.io/reviews/cockroachdb/cockro [...]

2020-02-19 18:52 UTC, asubiotto reviewed
Did you end up running benchmarks to find the best setting for `batchTupleLimit`? I think it would be great to do so if not.

> Reviewed 7 of 7 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0Tkp7MEfMEs5Qwih2H:b-pbldbj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0Tl6ztCvd_XqyFmmDm:bhbds9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think @asubiotto pointed out that in that case only ordered aggregator will be created. So there is no need to handle empty input in a scalar context. 
</blockquote></details>

That's what I assumed (a hash aggregation with no groups doesn't make sense, we'd just use the ordered aggregator in that case), but I might be wrong
___
*[pkg/sql/colexec/hash_aggregator.go, line 117 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QUzHSD0bk7AoKpx4C:-M0TlQiN7zkZdRbHu9QO:b-bmm7sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator.go#L117)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Updated to reuse `bufferedBatch.length` 

The memory usage of `bufferedBatch` is proportional to the number of the groups that we are performing aggregation on. The memory issue could happen when group size is too small and there are a lot of inputs, but I think this was the case that we chose not to handle. 
</blockquote></details>

Correct, we're ok with that. The row execution engine also returns a memory error in this case (look at `buckets` and `bucketsAcc`).
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Tm9lo1pl8ZPfbtG8r:-M0Tm9lo1pl8ZPfbtG8s:bjrk3km) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7c5a585ae209adfa7e3b8494824c355759b9a4/pkg/sql/colexec/hash_aggregator_tmpl.go#L75)):*
> ```Go
> 
> 	for selIdx, rowIdx := range sel {
> 		// {{if .LhsMayHasNulls}}
> ```

nit: `s/MayHas/MaybeHas`


<!-- Sent from Reviewable.io -->

2020-02-19 19:28 UTC, Azhng reviewed
Run the benchmark for `batchTupleLimit` = 1024/2048/4096/8192 and here is the result: 

Looks like the larger the `batchTupleLimit` value the better the result.

Should I also commit the code that runs benchmark with different `batchTupleLimit` ? 

```
pkg: github.com/cockroachdb/cockroach/pkg/sql/colexec
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8         	       5	 247667048 ns/op	   2.12 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8          	       5	 257736108 ns/op	   2.03 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8         	      10	 115920451 ns/op	   4.52 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8          	      10	 115112203 ns/op	   4.55 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8       	     500	   3183859 ns/op	 164.67 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8        	     500	   3731188 ns/op	 140.51 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8      	     500	   2658012 ns/op	 197.25 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8       	     500	   3208227 ns/op	 163.42 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8       	       5	 230785502 ns/op	   2.27 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8        	       5	 233540269 ns/op	   2.24 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8       	      10	 113586520 ns/op	   4.62 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8        	      10	 111584048 ns/op	   4.70 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8     	     200	   6937800 ns/op	  75.57 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8      	     200	   6822927 ns/op	  76.84 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=1024-8    	     200	   6651557 ns/op	  78.82 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=1024-8     	     200	   6599989 ns/op	  79.44 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8         	      10	 163804103 ns/op	   3.20 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8          	      10	 170591922 ns/op	   3.07 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8         	      20	  74451722 ns/op	   7.04 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8          	      20	  76448363 ns/op	   6.86 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8       	     500	   2737696 ns/op	 191.51 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8        	     500	   3103818 ns/op	 168.92 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8      	     500	   2554722 ns/op	 205.22 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8       	     500	   2922596 ns/op	 179.39 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8       	      10	 174239686 ns/op	   3.01 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8        	      10	 176310890 ns/op	   2.97 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8       	      20	  82894100 ns/op	   6.32 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8        	      20	  88001697 ns/op	   5.96 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8     	     200	   6631382 ns/op	  79.06 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8      	     200	   7522288 ns/op	  69.70 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=2048-8    	     200	   6909513 ns/op	  75.88 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=2048-8     	     200	   6713422 ns/op	  78.10 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8         	      10	 151366971 ns/op	   3.46 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8          	      10	 171415408 ns/op	   3.06 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8         	      20	  71617556 ns/op	   7.32 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8          	      20	  71994313 ns/op	   7.28 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8       	     500	   2883482 ns/op	 181.82 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8        	     500	   3242344 ns/op	 161.70 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8      	     500	   2723424 ns/op	 192.51 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8       	     500	   3036088 ns/op	 172.69 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8       	      10	 156359823 ns/op	   3.35 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8        	      10	 160931562 ns/op	   3.26 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8       	      20	  73077303 ns/op	   7.17 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=2/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8        	      20	  73845776 ns/op	   7.10 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8     	     200	   6783396 ns/op	  77.29 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=512/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8      	     200	   6618486 ns/op	  79.22 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=false/numInputBatches=64/numOfBatchedTuples=4096-8    	     200	   6539063 ns/op	  80.18 MB/s
BenchmarkAggregator/SUM/hash/Decimal/groupSize=1024/hasNulls=true/numInputBatches=64/numOfBatchedTuples=4096-8     	     200	   6329726 ns/op	  82.83 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=false/numInputBatches=64/numOfBatchedTuples=8192-8         	      10	 117691773 ns/op	   4.45 MB/s
BenchmarkAggregator/SUM/hash/Int64/groupSize=1/hasNulls=true/numInputBatches=64/numOfBatchedTuples [...]

2020-02-20 15:36 UTC, Azhng reviewed
Actually spent a bit more time testing out more data, it looks like the performance peaks when the number of batched tuples is `16 * coldata.BatchSize()`. 


![Number of Tuple buffered vs. Hash Aggregator Throughput.png](Uploading...)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0YARz2CZFeeYPMllsP:bd3wr21)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-20 15:46 UTC, Azhng reviewed
Looks like uploading the image to reviewable failed. Here's the link to the spreadsheet that contains all the data for benchmark. 
https://docs.google.com/spreadsheets/d/1r17CD73sCT960TpkOgiPFNT6mXsXVMW7ShB-avJi-iI/edit?usp=sharing

Picked limit be `2 * coldata.BatchSize()` since there's no very significant performance improvement as the limit increase and we can reduce memory usage this way. 

PTAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0YGZQQDhbgyaiuLqn4:b-bw5145)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-20 16:25 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but I would wait until @yuzefovich gets one last look

> Reviewed 5 of 5 files at r13, 1 of 1 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0YPi2v43MY_5TZ_spt:b-39423j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-02-20 20:25 UTC, yuzefovich reviewed
I left a bunch of nits, but I have only one concern before the PR looks good to me - about no groups case: we should somehow make that hash aggregator is never planned in such scenario.

Very nice work nonetheless!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0ZFzE5210h5PgQJOoT:by2pt0y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 907 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z0tF07ts1Mro32DnC:-M0Z0tF15zESG0q5M4B1:b-tfx0qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/aggregator_test.go#L907)):*
> ```Go
> 	}
> 
> 	for _, numOfHashBucket := range []uint64{0 /* no limit */, 1, uint64(coldata.BatchSize())} {
> ```

nit: `s/numOfHashBucket/numOfHashBuckets/g`.
___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0Z1-pC-OfA1O1_6jBk:bw5pddl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That's what I assumed (a hash aggregation with no groups doesn't make sense, we'd just use the ordered aggregator in that case), but I might be wrong
</blockquote></details>

Hm, I think we could end up in a situation where the hash aggregator is planned with no groups - if we have empty table, but the stats for that table say that the table is not empty and in fact contains something. I'd be curious to see what would happen in such scenario. You can take a look at `tpch_vec` logic test for an example on how to inject stats.
___
*[pkg/sql/colexec/hash_aggregator.go, line 240 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-z6pCl1PCGkfT1JNiG:-M0SuxP_5GWp2JxFPLzC:bu0hsag) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L240)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I'm a bit confused for the `InternalMemoryOperator` interface, 
  is it supposed to report the current memory usage of an operator 
   or 
  is it supposed to report the estimated memory usage of an operator
</blockquote></details>

I agree that this is a confusing interface. Probably you should ignore what I said about it. (The idea behind it is to register some memory allocations - which are not `coldata`-related - with a memory account. For example, in `caseOp` uses two "internal" slice of `uint16` to do it's job, so the operator would report that usage via this interface. This isn't applicable to this case though, but it'd be nice if we could report estimated memory usage upfront, during planning when we're creating the operators.)
___
*[pkg/sql/colexec/hash_aggregator.go, line 457 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M-zKst47rQgraXJcgD7:-M0ZBVTq00D8muVoHpZ4:b-6sm6ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/f80b6c80ab49e18b9246068c0cf387189d0acc8c/pkg/sql/colexec/hash_aggregator.go#L457)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I wrap the `PerformOperation` around the outer for loop, did I miss something here? 
</blockquote></details>

My comment about something being "unfortunate" was about the missing linter rule, to enforce that we don't forget to wrap things with `PerformOperation`. You're good though.
___
*[pkg/sql/colexec/hash_aggregator.go, line 28 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z1j2jAgZmrCTeHy-4:-M0Z1j2jAgZmrCTeHy-5:b-gajv6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L28)):*
> ```Go
> 
> const (
> 	// hashAggregatorBuffering represents the state the hashAggregator is
> ```

nit: to me it reads as if something is missing. Maybe "the state  *in which* the hashAggregator..."

ditto for other states.
___
*[pkg/sql/colexec/hash_aggregator.go, line 73 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z2XJ_1CXtV0zHWWUX:-M0Z2XJ_1CXtV0zHWWUY:b-redj0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L73)):*
> ```Go
> 	aggFuncMap hashAggFuncMap
> 
> 	// valTypes stores the corresponding types of the val columns.
> ```

nit: what is "val columns" here? I think we should spell it out for both `valTypes` and `valCols` that we only store "group" cols and "agg" cols, and "vals" is those two combined.
___
*[pkg/sql/colexec/hash_aggregator.go, line 81 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z3DVl3mQwgi80McwK:-M0Z3DVl3mQwgi80McwL:bey6feh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L81)):*
> ```Go
> 
> 	// batchTupleLimit limits the number of tuples the aggregator will buffer
> 	// before starts to perform aggregation. The maximum value of this field
> ```

nit: before "it" starts.
___
*[pkg/sql/colexec/hash_aggregator.go, line 91 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z3JS5DkPp6f4Jqeu8:-M0Z3JS5DkPp6f4Jqeu9:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L91)):*
> ```Go
> 		coldata.Batch
> 
> 		// sels stores the intermediate selection vector for each hash code
> ```

nit: missing period.
___
*[pkg/sql/colexec/hash_aggregator.go, line 96 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z3OVoCvqMlaNgn_2o:-M0Z3OVoCvqMlaNgn_2p:b-gu5ets) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L96)):*
> ```Go
> 		// group is a boolean vector where "true" represent the beginning of a group
> 		// in the column. It is shared among all aggregation functions. Since
> 		// hashAggregator manually manage mapping between input groups and their
> ```

nit: `s/manage/manages/g.`
___
*[pkg/sql/colexec/hash_aggregator.go, line 99 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z3UK22ZI3eARw5Fcp:-M0Z3UK22ZI3eARw5Fcq:b-c4hbec) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L99)):*
> ```Go
> 		// corresponding aggregation functions, group is set to all false to prevent
> 		// premature materialization of aggregation result in the aggregation
> 		// function. However, aggregation function expect at least one group in its
> ```

nit: `s/expect/expects/g`.
___
*[pkg/sql/colexec/hash_aggregator.go, line 118 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z3lUhA7Kj8Hmb2QhA:-M0Z3lUhA7Kj8Hmb2QhB:b-vglpe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L118)):*
> ```Go
> 		coldata.Batch
> 
> 		// pendingOutput indicates if there are more data need to be returned.
> ```

nit: "if there is more data that needs to be returned" or something like this.
___
*[pkg/sql/colexec/hash_aggregator.go, line 131 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z4-OG0mTyAiXOopXT:-M0Z4-OG0mTyAiXOopXU:biwver5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L131)):*
> ```Go
> 
> 	testingKnobs struct {
> 		// numOfHashBuckets is the maximum hash buckets each tuple will be hash to.
> ```

nit: something like "numOfHashBuckets is the number of hash buckets that each tuple will be assigned to".
___
*[pkg/sql/colexec/hash_aggregator.go, line 13 [...]

2020-02-24 17:23 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0sBNIw5iulj_BQAZ_T:b-cmlfv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I think we could end up in a situation where the hash aggregator is planned with no groups - if we have empty table, but the stats for that table say that the table is not empty and in fact contains something. I'd be curious to see what would happen in such scenario. You can take a look at `tpch_vec` logic test for an example on how to inject stats.
</blockquote></details>

Tried to inject stats into the table to see if `hashAggregator` will be planed in that case:

```
create table bools (a int, b bool);

alter table bools inject statistics '[
{
"columns": ["a", "b"],
"row_count": 5,
"distinct_count": 2,
"created_at": "2018-01-01 1:00:00.00000+00:00"
}]';

show statistics for table bools;
  statistics_name | column_names |          created          | row_count | distinct_count | null_count | histogram_id
------------------+--------------+---------------------------+-----------+----------------+------------+---------------
  NULL            | {a,b}        | 2020-02-25 01:00:00+00:00 |         5 |              2 |          0 |         NULL


explain (vec) select bool_and(b) from bools;
                text
-------------------------------------
  │
  └ Node 1
    └ *colexec.orderedAggregator
      └ *colexec.oneShotOp
        └ *colexec.distinctChainOps
          └ *colexec.colBatchScan
```

Looks like `orderedAggregator` is still planned in this case. 

Also glancing through the code in `execplan.go` it looks like `hashAggregator` is planned if and only if there is at least one grouping columns in the query and the set of grouping columns must be subset of ordered columns of that table. 

Therefore, since:
1. We only handle empty scalar case when there is no `group by` clause
2. Without having `group by` clause in the query, planner will always pick ordered aggregator 

I don't think hash aggregator need to handle empty scalar case.

This is my intuition, though I could have missed something. 
___
*[pkg/sql/colexec/hash_aggregator.go, line 117 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QUzHSD0bk7AoKpx4C:-M0rv8g1E-aaqWYjiZRQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70195babe2f6b80ef8d48190ce4df78ad5d944aa/pkg/sql/colexec/hash_aggregator.go#L117)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Correct, we're ok with that. The row execution engine also returns a memory error in this case (look at `buckets` and `bucketsAcc`).
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 244 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0Z8iMwAhfpRxQMYcr1:-M0ryeAJ6v43784zA7Q1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L244)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why do we have the additional `coldata.BatchSize()` of tuples? Because we might buffer more than `op.batchTupleLimit` kind of by "mistake"? If so, I think it deserves a short comment.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 454 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZCCft1CfsfYUa_7vz:-M0s05jpEWzoni1qNLqL:bar65pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L454)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we might be able to improve things here: `Append`ing a single tuple is slow, and instead we could use a different strategy - we would need to somehow force the col vecs of `keyMapping` to make sure that there is enough capacity and then we could use `execgen.SET` to set the values (i.e. to copy them). This doesn't belong in this PR, but you should leave a TODO. I feel like it would give a noticeable boost in the case of many distinct groups.
</blockquote></details>

Good point, though I think it's difficult to know beforehand how much memory to allocate for `keyMapping` buffer since it's correlated to number of group in all the input tuples. 

I think maybe we can try to allocate `op.batchTupleSize`, initially and when we run out of the space in the buffer, we can then use `Append()` to grow the buffer capacity. 

I will test it out later to see how much performance boost this will bring. 
___
*[pkg/sql/colexec/hash_aggregator.go, line 455 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZCoqv2j_UfYvJ-RTO:-M0s30GyDjj4gb6s-SKZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L455)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Another thing that can be improved is "unwrapping" `op.scratch` into its "ColVecs" so that we don't need to call the method on an interface. This probably won't be that big of a win, and I have an issue open about this, so it's up to you if you wanna do that in this PR.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 472 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZDLXR-QmbPZsTwkvZ:-M0s3_AT3qCTaSrdFyqc:bjv8f5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L472)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we could omit matching the zeroth "remaining" tuple as well. This probably will require some refactor (we would need to modify "match" method). Please leave a TODO.
</blockquote></details>

Just to clarify, does it mean to add additional parameter to tell `match()` to omit matching the 0th tuple in `remaining`?
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 30 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZE7JD15egWsKww_GL:-M0rujZi8hChJDDnsVHk:b-icuhl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator_tmpl.go#L30)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: unnecessary line.
</blockquote></details>

Goland auto format keep adding in this blank line here everytime I save. Had to manually edit this in vim. Is there any option to disable that?
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 71 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZEWng81SiEpsL6wqA:-M0rpODrC1-M1MUwIzxZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator_tmpl.go#L71)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I wonder whether we can remove this "with .Global" thingy in this file, and instead in the `hash_aggregator_gen.go` file call `{{.Global.Assign...`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-24 18:30 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r16, 1 of 1 files at r17, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-:-M0sSnQG0HYbNZyTjEfx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 606 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0sM9gf2shhe1OESqdh:-M0sM9gf2shhe1OESqdi:b-7rrdgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada2f586110aeb9bf2fc1ffcb970f9a801108ecb/pkg/sql/colexec/aggregator_test.go#L606)):*
> ```Go
> 								groups[i] = int64(curGroup)
> 							}
> 							// add result for last group.
> ```

nit: `s/add/Add/g`.
___
*[pkg/sql/colexec/aggregator_test.go, line 640 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0sMa1_CNmfJpmAld3P:-M0sMa1_CNmfJpmAld3Q:bapqpwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada2f586110aeb9bf2fc1ffcb970f9a801108ecb/pkg/sql/colexec/aggregator_test.go#L640)):*
> ```Go
> 							testOutput := newOpTestOutput(a, expectedTuples)
> 							if strings.Contains(agg.name, "hash") {
> 								err = testOutput.VerifyAnyOrder()
> ```

Now that we have `expectedTuples` populated, can we use `runTests` test harness instead of manually calling `testOutput.Verify`? Sorry if this was discussed before.
___
*[pkg/sql/colexec/execplan.go, line 440 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0QZ-Z28hANTBMUeFzu:-M0sSVp8BXqvDwjsqjBk:b-aml8dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469f81f863cb9a70f287ef4272da7c854ccdc2d/pkg/sql/colexec/execplan.go#L440)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Tried to inject stats into the table to see if `hashAggregator` will be planed in that case:

```
create table bools (a int, b bool);

alter table bools inject statistics '[
{
"columns": ["a", "b"],
"row_count": 5,
"distinct_count": 2,
"created_at": "2018-01-01 1:00:00.00000+00:00"
}]';

show statistics for table bools;
  statistics_name | column_names |          created          | row_count | distinct_count | null_count | histogram_id
------------------+--------------+---------------------------+-----------+----------------+------------+---------------
  NULL            | {a,b}        | 2020-02-25 01:00:00+00:00 |         5 |              2 |          0 |         NULL


explain (vec) select bool_and(b) from bools;
                text
-------------------------------------
  │
  └ Node 1
    └ *colexec.orderedAggregator
      └ *colexec.oneShotOp
        └ *colexec.distinctChainOps
          └ *colexec.colBatchScan
```

Looks like `orderedAggregator` is still planned in this case. 

Also glancing through the code in `execplan.go` it looks like `hashAggregator` is planned if and only if there is at least one grouping columns in the query and the set of grouping columns must be subset of ordered columns of that table. 

Therefore, since:
1. We only handle empty scalar case when there is no `group by` clause
2. Without having `group by` clause in the query, planner will always pick ordered aggregator 

I don't think hash aggregator need to handle empty scalar case.

This is my intuition, though I could have missed something. 
</blockquote></details>

Ok, thanks for checking.
___
*[pkg/sql/colexec/hash_aggregator.go, line 454 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZCCft1CfsfYUa_7vz:-M0sNA5QEj3WYnncr2Fg:b-zgj5v6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L454)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Good point, though I think it's difficult to know beforehand how much memory to allocate for `keyMapping` buffer since it's correlated to number of group in all the input tuples. 

I think maybe we can try to allocate `op.batchTupleSize`, initially and when we run out of the space in the buffer, we can then use `Append()` to grow the buffer capacity. 

I will test it out later to see how much performance boost this will bring. 
</blockquote></details>

Maybe we could rely on behavior of Go's `append` method - when a slice reaches its capacity, the new capacity will be doubled. So there might be no need to explicitly force allocation of big slices in this code, we could check the capacity of vector (for all types except for `coltypes.Bytes`), and if that capacity is greater than `aggFunc.keyIdx`, then we use `execgen.SET`, otherwise we use `Vec.Append`.

nit: use `TODO(azhng)` and also there is no need to indent the consequent lines in the todo.
___
*[pkg/sql/colexec/hash_aggregator.go, line 472 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZDLXR-QmbPZsTwkvZ:-M0sQdau2YBiPHaoWvFF:b-bdro8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L472)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Just to clarify, does it mean to add additional parameter to tell `match()` to omit matching the 0th tuple in `remaining`?
</blockquote></details>

Yeah, adding an additional parameter sounds good. The idea is that we can just include `aggFunc.keyIdx` into `matched` right away, without having to check whether it is different from itself.
___
*[pkg/sql/colexec/hash_aggregator_tmpl.go, line 30 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZE7JD15egWsKww_GL:-M0sLhG91FT3V8WReTO6:b-sejaji) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator_tmpl.go#L30)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Goland auto format keep adding in this blank line here everytime I save. Had to manually edit this in vim. Is there any option to disable that?
</blockquote></details>

Do you have a file watcher set up in Goland? Here is Tobi's instruction: https://cockroachlabs.slack.com/archives/C4VM697PC/p1545384791000100?thread_ts=1540908498.001700&cid=C4VM697PC (pinned in Goland slack channel).


<!-- Sent from Reviewable.io -->

2020-02-24 18:50 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 454 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZCCft1CfsfYUa_7vz:-M0sU2PF9WD2K4RTh3uS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L454)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Maybe we could rely on behavior of Go's `append` method - when a slice reaches its capacity, the new capacity will be doubled. So there might be no need to explicitly force allocation of big slices in this code, we could check the capacity of vector (for all types except for `coltypes.Bytes`), and if that capacity is greater than `aggFunc.keyIdx`, then we use `execgen.SET`, otherwise we use `Vec.Append`.

nit: use `TODO(azhng)` and also there is no need to indent the consequent lines in the todo.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/hash_aggregator.go, line 472 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0ZDLXR-QmbPZsTwkvZ:-M0sUyW90sLBOPYB-kfZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c6e86e176fe7f2bf2f9320284317d005c8077da/pkg/sql/colexec/hash_aggregator.go#L472)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, adding an additional parameter sounds good. The idea is that we can just include `aggFunc.keyIdx` into `matched` right away, without having to check whether it is different from itself.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-24 19:35 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 640 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0sMa1_CNmfJpmAld3P:-M0sesNK8theUoGkP5RP:b9e4q7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada2f586110aeb9bf2fc1ffcb970f9a801108ecb/pkg/sql/colexec/aggregator_test.go#L640)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Now that we have `expectedTuples` populated, can we use `runTests` test harness instead of manually calling `testOutput.Verify`? Sorry if this was discussed before.
</blockquote></details>

I was just testing out using `runTests` test harness instead of manually using `testOutput.Verify`, and looks like the tests was slow down by a lot (~17s without `runTests` VS ~300s with `runTests` ) because `runTests` add additional tests with different input sizes as well as null injection tests. The test cases that has `batchSize=1` runs extremely slow. 

I'm wondering if those automatically injected tests are necessary since the original `TestAggregatorRandom` didn't have those either. 


<!-- Sent from Reviewable.io -->

2020-02-24 20:08 UTC, yuzefovich reviewed
> Reviewed 3 of 5 files at r19, 1 of 1 files at r20, 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 640 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0sMa1_CNmfJpmAld3P:-M0snSzB3LQDNc5maEJf:bzdje5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada2f586110aeb9bf2fc1ffcb970f9a801108ecb/pkg/sql/colexec/aggregator_test.go#L640)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I was just testing out using `runTests` test harness instead of manually using `testOutput.Verify`, and looks like the tests was slow down by a lot (~17s without `runTests` VS ~300s with `runTests` ) because `runTests` add additional tests with different input sizes as well as null injection tests. The test cases that has `batchSize=1` runs extremely slow. 

I'm wondering if those automatically injected tests are necessary since the original `TestAggregatorRandom` didn't have those either. 
</blockquote></details>

I guess it's ok without it.


<!-- Sent from Reviewable.io -->

2020-02-24 20:09 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44966)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/aggregator_test.go, line 640 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/44966#-M0sMa1_CNmfJpmAld3P:-M0soDLZAV36OUF-2Etj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada2f586110aeb9bf2fc1ffcb970f9a801108ecb/pkg/sql/colexec/aggregator_test.go#L640)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I guess it's ok without it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-24 20:10 UTC, Azhng commented
TFTR! 

bors r+

2020-02-24 20:15 UTC, asubiotto commented
I think now that we randomize batch sizes, it's probably not worth it as much to run these tests with different batch sizes, which would probably decrease the runtime noticeably. Given the runtime though, I'd probably avoid adding runTests here.

2020-02-24 21:13 UTC, merged