server: separate sql statement stats from telemetry refresh interval
cockroachdb/cockroach pull request #44977
Opened 2020-02-11 18:42 UTC by rohany

This PR aims to solve the current problem that SQL statements
are refreshed when the telemetry update is sent, having side
effects on consumers of statement statistics, as well as making
it difficult to change the interval at which sql statements
statistics are refreshed.

I originally considered an approach where on SQL statement
stat reset the collected SQL stats would be merged into
a separate stat pool to be reported to telemetry, but this
does not work if the telemetry is collected faster than
the SQL stats are refreshed.

It seems that the only way to fully separate statement
statistics and telemtry reported statement statistics
is to just store both statisitics in separate pools
that can be reset independently of each other. This
PR implements this approach by updating the conn_executor
and server to maintain statement statistics and statement
statistics to report in separate pools.

Release note: None

2020-02-11 18:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/44977)
<!-- Reviewable:end -->

2020-02-11 18:43 UTC, rohany commented
cc @piyush-singh, not sure if you have an issue tracking this work.

I'm not sure what the best way to test this is, so I'm looking for suggestions.

@knz I'm adding you as a reviewer since we talked about this on slack, but pass it off to someone else if you aren't the right person.

2020-02-12 21:38 UTC, knz requested changes
Double storage inside SQL upon every statement exewcution is doubleplus ungood.

A possible proposal:  make a copy of the collected stats in the telemetry collector instead. This way the copy is only performed periodically (amortized cost). Then, whenever telemetry picks up the next round of stats, _substract_ the values observed "now" from those observed "the last time" before reporting.

Also meanwhile this PR does not provide a mechanism to flush the accumulated stats for the UI. There's no way we're going to merge a PR that causes unbounded memory growth.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44977#-:-M-vJyFG8t_vUVT6vhHo:b84f0a5)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-02-12 21:57 UTC, rohany commented
> Double storage inside SQL upon every statement exewcution is doubleplus ungood.

I don't feel great about it either

> Also meanwhile this PR does not provide a mechanism to flush the accumulated stats for the UI. There's no way we're going to merge a PR that causes unbounded memory growth.

There is already a thread that runs at an interval to clear the SQL stats. Then the telemetry thread would run to clear the reportedStats, so we wouldn't have unbounded growth.

> A possible proposal: make a copy of the collected stats in the telemetry collector instead. This way the copy is only performed periodically (amortized cost). Then, whenever telemetry picks up the next round of stats, substract the values observed "now" from those observed "the last time" before reporting.

This is what I wanted to do initially, but couldn't quite push it through. I maintained a second copy of the stats for telemetry, and whenever the sql stats were flushed I aggregated them into the telemetry copy (in order not to lose data). When the telemetry server gets refreshed quicker than the sql stats, we might run into a case where we have to do this subtraction of the stats from each other (it seems like i can identify when this needs to be done). Subtracting out the means stored seems doable, but idk if it's possible to do for the online variance calculation.

2020-02-12 21:59 UTC, knz commented
What about limiting the deletion to the maximum of the two configured time periods?

2020-02-12 22:09 UTC, rohany commented
> What about limiting the deletion to the maximum of the two configured time periods?

I think that would make sense. As I understand it, the main goal of this work is to allow users to shorten the time that sql stats are refreshed at so that more granular statement statistics can be displayed on the UI.

2020-02-12 22:20 UTC, knz commented
you mean reduce the frequency, not the period (less frequent refreshes)?

2020-02-12 22:31 UTC, rohany commented
No, i think they want to increase the refresh rate. The goal would be something like in the UI, set the stats interval to 10 seconds, then be able to see the performance of recent individual queries.

2020-02-12 22:34 UTC, knz commented
woah ok sorry I had misunderstood. What about the following:

- make each iteration of the SQL loop archive the current app stats into a queue of recently flushed stats
- make each iteration of the update loop take all the current archived stats and report that (perhaps with a combination/sum step)

2020-02-12 22:43 UTC, rohany commented
That makes sense. This problem is a lot simpler if we don't _have_ to report sql stat data every time the telemetry update loop fires -- it can just send data when there is actually dumped data to send. Thanks for the pointers Raphael, I'll open a new PR with a better approach.

2020-02-12 22:54 UTC, closed without merging