jobs: trigger job adoption on registry Run()
cockroachdb/cockroach pull request #45184
Opened 2020-02-18 21:36 UTC by pbardea

To quickly trigger the adoption of a job, make the job registry listen
to a channel which will be triggered when a job is run.

Release note: None

2020-02-18 21:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45184)
<!-- Reviewable:end -->

2020-02-18 21:58 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>


A test wouldn't hurt but I'm cool with this merging as-is. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-:-M0PIiY51kCd06p_yAHX:b-5zu3di)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)



<!-- Sent from Reviewable.io -->

2020-02-19 03:14 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang, @pbardea, and @spaskob)

___
*[pkg/jobs/registry.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0QQT_u4N6inPQ5x4_1:-M0QQT_vD3L5ilwGMLmM:b3in3w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L265)):*
> ```Go
> 		return nil
> 	}
> 	select {
> ```

new proposal:

```
const maxAdoptionTriggers = 5
for i := 0; i < len(jobs) && i < maxAdoptionTriggers; i++ {
    select {
    case r.adoptionCh <- struct{}{}:
    case <-ctx.Done():
        return ctx.Err()
    }
}
```

This should work for all cases we care about in testing and most cases in general.
___
*[pkg/jobs/registry.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0QQoWp8K-0tBAPCYon:-M0QQoWp8K-0tBAPCYoo:b-hh2ziz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L414)):*
> ```Go
> 	stopper.RunWorker(context.Background(), func(ctx context.Context) {
> 		for {
> 			select {
> ```

doesn't this also need a

```
case <-ctx.Done():
    return ctx.Err()
```


<!-- Sent from Reviewable.io -->

2020-02-19 12:21 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/jobs/registry.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0SO91A6ky1NL7K-VPQ:-M0SO91A6ky1NL7K-VPR:b-l5is5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L271)):*
> ```
> 
> ```
Why not just stick it here:

```
    select {
    case r.adoptionCh <- struct{}{}:
    case <-ctx.Done():
        return ctx.Err()
    }
```


<!-- Sent from Reviewable.io -->

2020-02-19 13:14 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang, @pbardea, and @spaskob)

___
*[pkg/jobs/registry.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0SO91A6ky1NL7K-VPQ:-M0S_KQxDFvyI1PVSD2b:b-ddnr6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L271)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

> ```
> 
> ```
Why not just stick it here:

```
    select {
    case r.adoptionCh <- struct{}{}:
    case <-ctx.Done():
        return ctx.Err()
    }
```
</blockquote></details>

Works for me. I had a slight concern about triggering the loop too many times but I've decided I'm no longer worried about that. 


<!-- Sent from Reviewable.io -->

2020-02-19 13:56 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @spaskob)

___
*[pkg/jobs/registry.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0QQT_u4N6inPQ5x4_1:-M0SistL6bLaa--sCUG8:b-ea82oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L265)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

new proposal:

```
const maxAdoptionTriggers = 5
for i := 0; i < len(jobs) && i < maxAdoptionTriggers; i++ {
    select {
    case r.adoptionCh <- struct{}{}:
    case <-ctx.Done():
        return ctx.Err()
    }
}
```

This should work for all cases we care about in testing and most cases in general.
</blockquote></details>

Done. Put it in the jobs loop below.
___
*[pkg/jobs/registry.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-M0SO91A6ky1NL7K-VPQ:-M0SivrCApEYc3oPhL-u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd0a3e4e513ff7792d4bac650c7709ce3bf98586/pkg/jobs/registry.go#L271)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Works for me. I had a slight concern about triggering the loop too many times but I've decided I'm no longer worried about that. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-19 18:52 UTC, spaskob approved these changes
lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45184#-:-M0Tmkh80Ae-URWwZfhE:bb7k0qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @spaskob)



<!-- Sent from Reviewable.io -->

2020-02-19 19:23 UTC, pbardea commented
TFTRs!
bors r+

2020-02-20 16:25 UTC, pbardea commented
bors r+

2020-02-20 16:38 UTC, pbardea commented
bors r+

2020-02-20 18:58 UTC, pbardea commented
bors r+

2020-02-20 21:25 UTC, merged