colexec: add recursive partitioning to external hash joiner
cockroachdb/cockroach pull request #45301
Opened 2020-02-22 05:25 UTC by yuzefovich

**colexec: add recursive partitioning to external hash joiner**

This commit adds the support for recursive partitioning to external hash
joiner. The goal is that if a partition is too big to join at once (when
the right side partition exceeds the memory limit), we need to
repartition that partition according to a different hash function. We
will always try to join as many partitions as possible (and emit the
corresponding output), and then if there are any partitions that are too
big, we will repartition them, one at a time. Once that single big
partition is repartitioned, we will try joining subpartitions. If at
some point we see that there is no decrease in size (if the decrease
is less than 0.05), we will bail on such query. It is likely that in
such case we have tuples that are not distinct on equality columns, and
we need to fallback to a combination of sort + merge join (currently not
supported).

The given memory limit is divided into two parts: one half for disk
queues (i.e. partitions), and another half for the in-memory hash
joiner. The number of buckets to divide a partition into is
semi-dynamically computed to be in the range [2, 16] (i.e. we will be
using from 4 to 32 disk queues). The memory usage of the in-memory hash
joiner is approximated by the size of the right side partition.

Fixes: #44727.

Release note: None

**colexec: fix verifySelAndNullsReset test**

Previously, we would run verifySelAndNullsReset test on all of the
units. However, this test relies on the fact that the output of the
operator in question is the same which is not always the case - it is
such only if we expect the order of tuples (and batches) remain the
same. This is now fixed by checking whether the verifierType is
orderedVerifier, and only if so, we will run this test.

Additionally, this numbers all hash joiner unit tests for ease of
debugging.

Release note: None

2020-02-22 05:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45301)
<!-- Reviewable:end -->

2020-02-24 14:12 UTC, asubiotto requested changes
Great to see this done so quickly.

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-:-M0mluNF8aR861aiBZaU:b-c27r26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mh6gw1etRbK5i-g6s:-M0mh6gx72_Xoqh2N8OH:b-pt4gx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/execplan.go#L555)):*
> ```Go
> 						memoryLimit := execinfra.GetWorkMemLimit(flowCtx.Cfg)
> 						monitorNamePrefix := "external-hash-joiner"
> 						allocator := NewAllocator(
> ```

Could you remind me why this is a limited account?
___
*[pkg/sql/colexec/execplan.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mhCXH9nByhw1zNoO_:-M0mhCXH9nByhw1zNoOa:b-rm0flx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/execplan.go#L567)):*
> ```Go
> 								ctx, flowCtx, monitorNamePrefix+"-disk-queues",
> 							))
> 						if flowCtx.Cfg.TestingKnobs.ForceDiskSpill && flowCtx.Cfg.TestingKnobs.MemoryLimitBytes == 0 {
> ```

Why not do this in tests explicitly?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M0ml8l145P62jUHShvW:b-cn06dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
> ```Go
> 	// partition index and join the corresponding partitions from both sides. We
> 	// will only join the partitions if the right side partition fits into memory
> 	// (because in-memory hash joiner will fully buffer the right side). If there
> ```

I need to wrap my head around left side usage, let's talk offline.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miAM0Bkiur5-DfPDS:-M0miAM0Bkiur5-DfPDT:boegdnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L70)):*
> ```Go
> 
> const (
> 	externalHJMaxNumBuckets                              = 16
> ```

I wonder if it's better to have a constant maximum or determine that based on the file descriptor semaphore count (not merged yet). This does not need to be changed in this PR.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miFR7AoHlSeSn0Okb:-M0miFR7AoHlSeSn0Okc:b71mg4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L71)):*
> ```Go
> const (
> 	externalHJMaxNumBuckets                              = 16
> 	externalHJRecursivePartitioningSizeDecreaseThreshold = 0.05
> ```

You've explained it above, but might make sense to add a comment here as well.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miJzsB2Qo0WcETApX:-M0miJzsB2Qo0WcETApY:b-6nvi2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L105)):*
> ```Go
> // this algorithm. The partition will be divided into sub-partitions by a new
> // hash function, spilled to disk, and so on.
> // TODO(yuzefovich): actually implement recursive partitioning.
> ```

Remove todo?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mj8gwCP6I1Iv7ysJ-:-M0mj8gwCP6I1Iv7ysJ0:bco8by4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L190)):*
> ```Go
> 			// We divide by 2 because we might need a queue on both sides for each
> 			// bucket.
> 			numBuckets = numDiskQueuesThatFit / 2
> ```

maybe `s/numBuckets/numBucketsPerSide`
___
*[pkg/sql/colexec/external_hash_joiner.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mkJk5EuB1GOIeY4ki:-M0mkJk5EuB1GOIeY4kj:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L330)):*
> ```Go
> 			// to increase the seed value of the tuple distributor.
> 			hj.tupleDistributor.initHashValue++
> 			// We also need to update how many buckets we're using when
> ```

Why?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mkoBpDbKd7RrHhfkF:-M0mkoBpDbKd7RrHhfkG:b-ele14e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L373)):*
> ```Go
> 							sizeDecrease := 1.0 - float64(after)/float64(before)
> 							if sizeDecrease < externalHJRecursivePartitioningSizeDecreaseThreshold {
> 								// TODO(yuzefovich): support this case by falling back to
> ```

Could we pre-emptively add a test that checks for this error? It'll be useful for when we add sortmerge.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mleiqBp6EOSDQeIY5:-M0mleiqBp6EOSDQeIY6:b-r3b84k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L401)):*
> ```Go
> 					hj.state = externalHJJoining
> 					delete(hj.partitionsToJoin, partitionIdx)
> 					return hj.Next(ctx)
> ```

Shouldn't this transition to `externalHJJoining`? Couldn't this have led to bugs where you only emit one batch and never re-join those partitions since you deleted it from `partitionsToJoin`?


<!-- Sent from Reviewable.io -->

2020-02-24 17:17 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execplan.go, line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mh6gw1etRbK5i-g6s:-M0s-SOwCjzn_WxW601Y:b-84y8ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/execplan.go#L555)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you remind me why this is a limited account?
</blockquote></details>

Previously, we were not doing any memory accounting in the external hash joiner explicitly and were leaving that up to the allocator (used by the internal in-memory hash joiner), but now that we track the size of the partitions on the right side we can use the unlimited account. Changed.
___
*[pkg/sql/colexec/execplan.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mhCXH9nByhw1zNoO_:-M0s1k6-AH9o1A4-4EJk:bcyvfqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/execplan.go#L567)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not do this in tests explicitly?
</blockquote></details>

Because we needed a reasonable memory limit when instantiating a limited allocator above, but now that's changed, so we can do this in tests.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M0sApgt1p4arK_4Rlwb:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I need to wrap my head around left side usage, let's talk offline.
</blockquote></details>

SGTM.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miAM0Bkiur5-DfPDS:-M0s3dUh23DeTU5A3Bzm:b8nwjcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if it's better to have a constant maximum or determine that based on the file descriptor semaphore count (not merged yet). This does not need to be changed in this PR.
</blockquote></details>

I think we want to have both restrictions.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miFR7AoHlSeSn0Okb:-M0s5mjNBkqyRhweRUAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L71)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You've explained it above, but might make sense to add a comment here as well.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miJzsB2Qo0WcETApX:-M0s2WA86lJh5Q9MOcH2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L105)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Remove todo?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mj8gwCP6I1Iv7ysJ-:-M0s2wU50mxIpBjqkq_m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L190)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

maybe `s/numBuckets/numBucketsPerSide`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mkJk5EuB1GOIeY4ki:-M0s6gUL0OnjpJ4nP-hF:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L330)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Added a comment.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 373 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mkoBpDbKd7RrHhfkF:-M0sAVGu-mxcgcJkEfqu:b1s21md) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L373)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we pre-emptively add a test that checks for this error? It'll be useful for when we add sortmerge.
</blockquote></details>

Done (this actually found a bug that I was not setting `partitionInfo.rightParentMemSize` correctly - it remained unset).
___
*[pkg/sql/colexec/external_hash_joiner.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mleiqBp6EOSDQeIY5:-M0s3Lwf9DlDX-KwL7WP:b-f1y2lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L401)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't this transition to `externalHJJoining`? Couldn't this have led to bugs where you only emit one batch and never re-join those partitions since you deleted it from `partitionsToJoin`?
</blockquote></details>

We do transition to `externalHJJoining` state a couple of lines above.


<!-- Sent from Reviewable.io -->

2020-02-24 19:35 UTC, asubiotto requested changes
> Reviewed 3 of 6 files at r1, 5 of 5 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M0sSMzJ4TiOegqtOuk1:bw1ugru) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

SGTM.
</blockquote></details>

I guess one question I have, how are we guaranteed that the left side partition fits into memory?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miAM0Bkiur5-DfPDS:-M0sSgCjDklkWrAn6fgo:b-jv0mxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L70)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we want to have both restrictions.
</blockquote></details>

I'm not 100% certain about this. With a maximum of 16 per side and the current reserved fraction, we'll be able to in the best case, join against 512 MiB of data (on the right side) before repartitioning (and I believe that repartitioning is probably pretty expensive). I'm not sure it'll ever be good to limit the maximum number of partitions using some constant if we can avoid repartitioning through more partitions. We're going to have to run some benchmarks once #45318 is in to figure out 1) the right reserved fraction and 2) whether we want to limit the number of partitions (maybe in the joiner we don't but the sorter we do, to not have too many partitions open at once). I guess my point is that it's an open ended question and my opinion specifically in the joiner, is that a hard constant might not be what we want.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0mleiqBp6EOSDQeIY5:-M0se_d1CyGkEykeibgu:bb71nyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L401)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We do transition to `externalHJJoining` state a couple of lines above.
</blockquote></details>

Oops
___
*[pkg/sql/colexec/external_hash_joiner.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sQgKz35Q9hYs2t9n-:-M0sQgKz35Q9hYs2t9n0:bmyjl9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L40)):*
> ```Go
> 	// reduces the size of the partitions in question - if we see that the newly
> 	// created largest partition is about the same in size as the "parent"
> 	// partition (the difference is less than
> ```

nit: `s/difference/percentage difference`
___
*[pkg/sql/colexec/external_hash_joiner.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sW_UDB7IvdQsxsP78:-M0sW_UDB7IvdQsxsP79:b-z6p86c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L188)):*
> ```Go
> 	leftInput, rightInput Operator,
> 	memoryLimit int64,
> 	memUsagePerDiskQueue int,
> ```

nit: I think it would be best to just pass in a full `DiskQueueCfg` since this is done in the external sorter as well. We'll also need it to create the partitioned disk queues.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M0sZT9GDDN50BEgT4K8:b-tek5qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
> ```Go
> 				// cache of new disk queues we're about to create, so we also need to
> 				// update how many buckets we're using when repartitioning.
> 				diskQueuesUsedMem := 2 * len(hj.partitionsToJoin) * hj.memState.memUsagePerDiskQueue
> ```

At this stage, when using partitioned disk queues, we only need two partitions open: the left and right side we're reading from, so we can just `numBuckets -= 2`. This will be the stage at which we'll close the disk queues for writing. I think I'll add an option to that in my PR to also release any cache memory (and reallocate it on the first read).
___
*[pkg/sql/colexec/external_hash_joiner.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sdo1_DGFU0njos1ni:-M0sdo1_DGFU0njos1nj:b-8sx100) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L365)):*
> ```Go
> 			for parentPartitionIdx, parentPartitionInfo := range hj.partitionsToJoin {
> 				for {
> 					leftBatch := hj.recursiveScratch.leftBatch
> ```

might be nicer to write this as:
```
for _, side := range []{leftSide, rightSide} {
   batch := leftBatch
   if side == rightSide {
        batch = rightBatch
   }
   ....
}
```
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sPwGMEyY1keGo3-ta:-M0sPwGMEyY1keGo3-tb:bn9kg46) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L53)):*
> ```Go
> 		flowCtx.Cfg.TestingKnobs.ForceDiskSpill = spillForced
> 		if spillForced {
> 			// We want to make recursive partitioning more likely, so we will "limit"
> ```

How many repartitions will happen in this case? Would it be possible to determine this dynamically with a target number of repartitions (probably will have to do this per `tc`)? I've noticed that the external sort test took a long time because of excessive repartitioning, so we should make sure that it isn't the case here.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sf2l22bPi3-07vVXW:-M0sf2l22bPi3-07vVXX:b-of2nd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L84)):*
> ```Go
> }
> 
> func TestExternalHashJoinerFallbackToSortMergeJoin(t *testing.T) {
> ```

Add a quick comment describing this test.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sevf9EG4JXdosalYW:-M0sevf9EG4JXdosalYX:bgymwji) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L100)):*
> ```Go
> 	leftSource := newFiniteBatchSource(batch, nBatches)
> 	rightSource := newFiniteBatchSource(batch, nBatches)
> 	flowCtx.Cfg.TestingKnobs.ForceDiskSpill = true
> ```

nit: can you set these in the `Cfg` above directly?
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sfQxCDAqteaRYCs2r:-M0sfQxCDAqteaRYCs2s:bspi7xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L180)):*
> ```Go
> 					flowCtx.Cfg.TestingKnobs.ForceDiskSpill = spillForced
> 					if spillForced {
> 						flowCtx.Cfg.TestingKnobs.MemoryLimitBytes = 100 * mon.DefaultPoolAllocationSize
> ```

I would probably leave repartitioning out of the benchmark for now. If we do wan to include it, we should probably have a target number of repartitions and then determine the memory limit (i.e. partition size) from that.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/co [...]

2020-02-24 21:53 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M0sqGLR5oJ8pVNNEm57:ba8zaa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I guess one question I have, how are we guaranteed that the left side partition fits into memory?
</blockquote></details>

Is the question still relevant?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0miAM0Bkiur5-DfPDS:-M0sqzNi7w7mgYPpeYIz:bw63w0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L70)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not 100% certain about this. With a maximum of 16 per side and the current reserved fraction, we'll be able to in the best case, join against 512 MiB of data (on the right side) before repartitioning (and I believe that repartitioning is probably pretty expensive). I'm not sure it'll ever be good to limit the maximum number of partitions using some constant if we can avoid repartitioning through more partitions. We're going to have to run some benchmarks once #45318 is in to figure out 1) the right reserved fraction and 2) whether we want to limit the number of partitions (maybe in the joiner we don't but the sorter we do, to not have too many partitions open at once). I guess my point is that it's an open ended question and my opinion specifically in the joiner, is that a hard constant might not be what we want.
</blockquote></details>

Fair point.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sQgKz35Q9hYs2t9n-:-M0spZle4fZDBJj1OeYc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L40)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/difference/percentage difference`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sW_UDB7IvdQsxsP78:-M0srXUn4fBZj-XZC6Yl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L188)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think it would be best to just pass in a full `DiskQueueCfg` since this is done in the external sorter as well. We'll also need it to create the partitioned disk queues.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M0ssKvzB8vm__ZYaqcw:b-ak0zif) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

At this stage, when using partitioned disk queues, we only need two partitions open: the left and right side we're reading from, so we can just `numBuckets -= 2`. This will be the stage at which we'll close the disk queues for writing. I think I'll add an option to that in my PR to also release any cache memory (and reallocate it on the first read).
</blockquote></details>

I think we might have slightly different mental models here: `hj.numBuckets` doesn't limit number of total partitions, it specifies how many "children" partitions the big "parent" partition is divided into. For example, we fully consume the inputs, and we have 16 partitions on each side, all of them are too big to join, so we will repartition 0th from each side into another 16 partitions. At this point we will have 31 partition on each side.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sdo1_DGFU0njos1ni:-M0suTTk4mtH25Jo1Czq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L365)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

might be nicer to write this as:
```
for _, side := range []{leftSide, rightSide} {
   batch := leftBatch
   if side == rightSide {
        batch = rightBatch
   }
   ....
}
```
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sPwGMEyY1keGo3-ta:-M0suf_U2FAT-79cskOd:bgly20d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L53)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How many repartitions will happen in this case? Would it be possible to determine this dynamically with a target number of repartitions (probably will have to do this per `tc`)? I've noticed that the external sort test took a long time because of excessive repartitioning, so we should make sure that it isn't the case here.
</blockquote></details>

Probably repartitioning actually won't be happening at all in this test because test cases here are written explicitly and contain very small amount of data.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sf2l22bPi3-07vVXW:-M0t4wYn2-v9wPfNbr1D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L84)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a quick comment describing this test.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sevf9EG4JXdosalYW:-M0t5AIF7d0RwGI7AzgE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: can you set these in the `Cfg` above directly?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sfQxCDAqteaRYCs2r:-M0t5JZV8tMpUi0AtL2X:btfxb5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner_test.go#L180)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would probably leave repartitioning out of the benchmark for now. If we do wan to include it, we should probably have a target number of repartitions and then determine the memory limit (i.e. partition size) from that.
</blockquote></details>

Ok, removed.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sfku67O9VHFAAHgo0:-M0t5mcv2cgJ2lS2O8PB:b9tto4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/distsql/columnar_op [...]

2020-02-25 14:57 UTC, asubiotto requested changes
> Reviewed 9 of 9 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M0wjvGvA8ngsgRQFbIo:b2nhky0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is the question still relevant?
</blockquote></details>

No.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M0wmCuGAj0Ma3THSCY0:brv8i64) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we might have slightly different mental models here: `hj.numBuckets` doesn't limit number of total partitions, it specifies how many "children" partitions the big "parent" partition is divided into. For example, we fully consume the inputs, and we have 16 partitions on each side, all of them are too big to join, so we will repartition 0th from each side into another 16 partitions. At this point we will have 31 partition on each side.
</blockquote></details>

Right, I guess I'm thinking about numBuckets as total, but it's per side. What I mean is that `numBuckets` is determined so that the cache memory never exceeds a certain amount. My point is that we have determined we can use 16 partitions at the top level (per side = 32 partitions total). When we repartition, say we choose to repartition partition 1 and 2 (using 1-indexed). At this stage, we can close the other 30 partitions' cache, but since we need to read from 1 and 2, we still need to say that their cache is used, so `numBuckets` should be 15 to create 30 children. This is only at the top level of repartition.

What I'm trying to say is that we shouldn't calculate any memory usage here and should just reduce `numBuckets` by 1 for the children.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wo12u7DauO2qjv6ut:-M0wo12u7DauO2qjv6uu:b-jm2d3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L163)):*
> ```Go
> 
> 	testingKnobs struct {
> 		numForcedRepartitions int
> ```

I think we should add a comment to explicitly describe what behavior enabling this will result in.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0woENo76SLhij6rXU4:-M0woENo76SLhij6rXU5:b-uuucun) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L358)):*
> ```Go
> 			hj.tupleDistributor.initHashValue++
> 			hj.numBuckets = externalHJMaxNumBucketsPerSide
> 			if hj.cfg.BufferSizeBytes > 0 {
> ```

Could we track the number of repartitions and maybe add some verbose logging for observability? We'll probably want to add this to EXPLAIN ANALYZE later on.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wmaAI1JO3-7ZM6ifF:-M0wmaAI1JO3-7ZM6ifG:b4w8whw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L375)):*
> ```Go
> 			}
> 			hj.tupleDistributor.resetNumOutputs(hj.numBuckets)
> 			for parentPartitionIdx, parentPartitionInfo := range hj.partitionsToJoin {
> ```

I wonder if we should choose which partitions to recursively partition. If we've hashed properly I guess it doesn't matter though, since the partitions should be equal in size. But maybe add a TODO?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 397 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wnice0NHYwLoO4QUW:-M0wnice0NHYwLoO4QUX:bqhsia4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L397)):*
> ```Go
> 				if !hj.testingKnobs.repartitionForced {
> 					// If the repartition was forced, then it is possible that there is
> 					// no reduction in size, and we don't want to error out in such case.
> ```

Is a test failing because of this?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wpbd9E36zukHyoQ7k:-M0wpbd9E36zukHyoQ7l:b-fo1wd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L420)):*
> ```Go
> 				hj.partitionIdxOffset += hj.numBuckets
> 				hj.state = externalHJJoinNewPartition
> 				return hj.Next(ctx)
> ```

Does this state change guarantee that we'll join all the new partitions? Since map iteration is not stable I'm not sure it will but we probably want to attempt to join all of these with a decreased size, otherwise we could end up blowing up the number of partitions by repartitioning another top-level partition.

Also, why call `hj.Next` instead of `continue`? Might be better to `continue` to not add another level to the stack trace and it's consistent with other transitions.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wqKZZABxkFXaWoAQj:-M0wqKZZABxkFXaWoAQk:b-52ub5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L440)):*
> ```Go
> 					hj.state = externalHJJoining
> 					delete(hj.partitionsToJoin, partitionIdx)
> 					return hj.Next(ctx)
> ```

here as well re `s/hj.Next/continue`
___
*[pkg/sql/distsql/columnar_operators_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sfku67O9VHFAAHgo0:-M0wjRySDDh5oRApPbfL:b-icjj0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/distsql/columnar_operators_test.go#L550)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually, again, the repartition wouldn't have happened at all because we generate just 10 rows in this test.

Added a testing knob to force repartition (it's slightly unfortunate that this knob is very specific to external hash joiner).
</blockquote></details>

We could just call it `numForcedRepartitions` and observe it in the sorter too (maybe not in this PR)


<!-- Sent from Reviewable.io -->

2020-02-26 03:05 UTC, yuzefovich commented
I'll wait for #45318 to go in, and then will address comments here.

2020-02-26 20:40 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0ml8l145P62jUHShvV:-M12CpYE9IQ7MbvW8bOk:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0d259bfcb6e16b1b81b9feb64bd43b54767c01/pkg/sql/colexec/external_hash_joiner.go#L52)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

No.
</blockquote></details>

Ack.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M129UpL8rtS390rnD9y:b-vmmqxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Right, I guess I'm thinking about numBuckets as total, but it's per side. What I mean is that `numBuckets` is determined so that the cache memory never exceeds a certain amount. My point is that we have determined we can use 16 partitions at the top level (per side = 32 partitions total). When we repartition, say we choose to repartition partition 1 and 2 (using 1-indexed). At this stage, we can close the other 30 partitions' cache, but since we need to read from 1 and 2, we still need to say that their cache is used, so `numBuckets` should be 15 to create 30 children. This is only at the top level of repartition.

What I'm trying to say is that we shouldn't calculate any memory usage here and should just reduce `numBuckets` by 1 for the children.
</blockquote></details>

Well, I was writing the code when I didn't have a way to release the FDs, so I had to add this recomputation. Now that the ability to close FDs is about to be merged, it is not needed indeed.

Actually, thinking about it more, we don't even need to subtract 1:
- in `externalHJInitialPartitioning` we are actively using `hj.numBuckets * 2` FDs, and we correctly limit `hj.numBuckets` by the available memory for the caches
- in `externalHJRecursivePartitioning` state we now repartition one side at a time, so we're actively using `1 + hj.numBuckets`. We actually could make `hj.numBuckets := 2*hj.numBuckets - 1`. I'll leave it as TODO to see whether it'd be helpful.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wo12u7DauO2qjv6ut:-M127U7mCcRWcA2zLYKs:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we should add a comment to explicitly describe what behavior enabling this will result in.
</blockquote></details>

Good point, done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 358 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0woENo76SLhij6rXU4:-M128o1t49CACAdARo36:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L358)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we track the number of repartitions and maybe add some verbose logging for observability? We'll probably want to add this to EXPLAIN ANALYZE later on.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wmaAI1JO3-7ZM6ifF:-M128w3bCrazfpvAWGHC:bdkeo9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L375)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if we should choose which partitions to recursively partition. If we've hashed properly I guess it doesn't matter though, since the partitions should be equal in size. But maybe add a TODO?
</blockquote></details>

I think it doesn't actually matter. Our criteria for when to repartition (right side partition is too big to fit in memory) doesn't care about the order in which we apply the criteria. Or is there something I'm missing from the file descriptor perspective?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 397 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wnice0NHYwLoO4QUW:-M129Juf3dBk_3nVoswY:b-bemltj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L397)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is a test failing because of this?
</blockquote></details>

It's failing because of the missing fallback to sort + merge join. Added clarifying comment to the knob.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wpbd9E36zukHyoQ7k:-M120h_wBdIriB1KtlvA:bq4mcsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L420)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this state change guarantee that we'll join all the new partitions? Since map iteration is not stable I'm not sure it will but we probably want to attempt to join all of these with a decreased size, otherwise we could end up blowing up the number of partitions by repartitioning another top-level partition.

Also, why call `hj.Next` instead of `continue`? Might be better to `continue` to not add another level to the stack trace and it's consistent with other transitions.
</blockquote></details>

Yes, it guarantees that. We will be joining partitions until the map is empty, but the order in which we join partitions is arbitrary. At this point we have created `hj.numBuckets` (possibly empty) new partitions and we have checked that there was reasonable reduction in size, so we will try to join them all, one at a time.

The call is to `hj.Next` instead of `continue` because of the fact that we're in an inner loop, but want to continue to the outer. Added labels for that.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 440 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wqKZZABxkFXaWoAQj:-M121WVc7VuawPgwut4G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L440)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

here as well re `s/hj.Next/continue`
</blockquote></details>

Done.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 550 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sfku67O9VHFAAHgo0:-M121_0-3sKHz26SK7Wk:byw7pig) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/distsql/columnar_operators_test.go#L550)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We could just call it `numForcedRepartitions` and observe it in the sorter too (maybe not in this PR)
</blockquote></details>

In sorter it would be called something like `numForcedMerges` (at least in my mind). Anyway, renamed everywhere and added clarifying comments.


<!-- Sent from Reviewable.io -->

2020-02-27 18:45 UTC, yuzefovich commented
Rebased, RFAL.

2020-02-27 20:17 UTC, asubiotto requested changes
> Reviewed 2 of 9 files at r6, 13 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M17BYjy06eK_EL39z4X:bawtwve) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Well, I was writing the code when I didn't have a way to release the FDs, so I had to add this recomputation. Now that the ability to close FDs is about to be merged, it is not needed indeed.

Actually, thinking about it more, we don't even need to subtract 1:
- in `externalHJInitialPartitioning` we are actively using `hj.numBuckets * 2` FDs, and we correctly limit `hj.numBuckets` by the available memory for the caches
- in `externalHJRecursivePartitioning` state we now repartition one side at a time, so we're actively using `1 + hj.numBuckets`. We actually could make `hj.numBuckets := 2*hj.numBuckets - 1`. I'll leave it as TODO to see whether it'd be helpful.
</blockquote></details>

:+1: good observation
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wpbd9E36zukHyoQ7k:-M17Br2K7wXuj3kva5QN:blbj5ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L420)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yes, it guarantees that. We will be joining partitions until the map is empty, but the order in which we join partitions is arbitrary. At this point we have created `hj.numBuckets` (possibly empty) new partitions and we have checked that there was reasonable reduction in size, so we will try to join them all, one at a time.

The call is to `hj.Next` instead of `continue` because of the fact that we're in an inner loop, but want to continue to the outer. Added labels for that.
</blockquote></details>

Oh, I see. It's because we never repartition if we have pending partitions to join.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 228 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M179wSI3zbx3psAzds5:-M179wSI3zbx3psAzds6:b-vs7r1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L228)):*
> ```Go
> 	// of partitions that will be used by the external hash joiner. Below we
> 	// check whether we have enough RAM to support the caches of this number of
> 	// partitions.
> ```

maybe add a TODO that this maximum is arbitrary, needs tuning.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 366 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17CWnS8BDrIPWSCf1P:-M17CWnS8BDrIPWSCf1Q:b-44s1dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L366)):*
> ```Go
> 				// Both inputs have been partitioned and spilled, so we transition to
> 				// "joining" phase. Close all the open write file descriptors.
> 				if err := hj.leftPartitioner.CloseAllOpenWriteFileDescriptors(); err != nil {
> ```

Just a note that this will also clear the cache once the new PR is in. This means we will reallocate a cache whenever reading from the partitions. What I think we might want to do is not close the partitions here. Instead, we move on to joining, which will switch all of these reserved file descriptors to read in the best case (no repartitioning) and reuse the cache. Only if we need to repartition should we `CloseAllOpenWriteFileDescriptors` of both sides. It might also be more efficient to `Dequeue` from the partitions you'll read from before doing that to exempt them from releasing their FDs to the semaphore.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 415 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17Em0m43xiU4j78PcD:-M17Em0m43xiU4j78PcE:b-67gvuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L415)):*
> ```Go
> 					}
> 					// We're done reading from this partition.
> 					if err := partitioner.CloseAllOpenReadFileDescriptors(); err != nil {
> ```

The file descriptor is automatically released when a zero batch is Dequeued. I think it'll be best to call `CloseInactiveReadPartitions` after this loop (to take care of both partitions in one call). This will actually reclaim disk space.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17DtG59Q8-sjaxXxrz:-M17DtG59Q8-sjaxXxs-:b-2bkp08) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L420)):*
> ```Go
> 				}
> 				// We're done writing to the newly created partitions.
> 				if err := hj.leftPartitioner.CloseAllOpenWriteFileDescriptors(); err != nil {
> ```

I don't think we should do this here. I think the invariant should be: we're entering `externalHJRecursivePartitioning`, at that stage we have at most `numBuckets*2` file descriptors open. At the top of the state transition, close all open write file descriptors, which should reduce the open descriptors to 0. Now we open the two read partitions for 2 file descriptors and whatever number of write partitions we want. This'll allow us to remove the call to `CloseAllOpen...` in the first state as well.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 500 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17FUFt1kg47Z6j04sm:-M17FUFt1kg47Z6j04sn:b-z0otnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L500)):*
> ```Go
> 		case externalHJJoining:
> 			b := hj.inMemHashJoiner.Next(ctx)
> 			if b.Length() == 0 {
> ```

In this case, two partitions that we're joining have been automatically closed, but we want to reclaim the disk space, so you should call `CloseInactiveReadPartitions`.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 506 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17G2yb3b10JANqu3p3:-M17G2yb3b10JANqu3p4:b-ee6jiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L506)):*
> ```Go
> 			return b
> 		case externalHJFinished:
> 			return coldata.ZeroBatch
> ```

I think we need to `Close` the `PartitionedDiskQueue` in this case to remove any leftover files (which should be 0), but still good to do. Maybe add an implementation of the `io.Closer` interface and call that here in preparation for adding the slice of `io.Closer`s to the flow. Actually, the fact that there is no `io.Closer` here should mean that we're failing some tests like `verifySelAndNullResets` which don't fully drain the operator.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 266 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17GaDX7uKhW9n58I-V:-M17GaDX7uKhW9n58I-W:b-5fq6wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner_test.go#L266)):*
> ```Go
> 		// TODO(asubiotto): Assert a maximum number of open file descriptors when
> 		//  we have recursive partitioning.
> 		FDSemaphore: NewTestingSemaphore(256),
> ```

I think in this case we want to add a semaphore argument to `createDiskBackedHashJoiner` similar to `createDiskBackedExternalSorter` with a semaphore with a specific limit. We need to add a way to override the number of partitions in the hash joiner similar to ho [...]

2020-02-27 23:26 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 351 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0sZT9GDDN50BEgT4K7:-M17gYLX0jYMiXypMBxc:brirziu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e428febcdf594e24f90c185974b1e8712d538b4e/pkg/sql/colexec/external_hash_joiner.go#L351)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:+1: good observation
</blockquote></details>

Implemented the TODO.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M0wpbd9E36zukHyoQ7k:-M17_s14EzT9TnzBfPfe:b-ne685n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e45c1b1dce8beb13ea0bb1e28780090fe3996546/pkg/sql/colexec/external_hash_joiner.go#L420)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oh, I see. It's because we never repartition if we have pending partitions to join.
</blockquote></details>

Yep, exactly.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 228 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M179wSI3zbx3psAzds5:-M17ZrNUB9I4_EK0fswj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L228)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

maybe add a TODO that this maximum is arbitrary, needs tuning.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 366 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17CWnS8BDrIPWSCf1P:-M17_i_H-Ejvp_S4jDZx:b-xxo8dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L366)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Just a note that this will also clear the cache once the new PR is in. This means we will reallocate a cache whenever reading from the partitions. What I think we might want to do is not close the partitions here. Instead, we move on to joining, which will switch all of these reserved file descriptors to read in the best case (no repartitioning) and reuse the cache. Only if we need to repartition should we `CloseAllOpenWriteFileDescriptors` of both sides. It might also be more efficient to `Dequeue` from the partitions you'll read from before doing that to exempt them from releasing their FDs to the semaphore.
</blockquote></details>

I think this would belong in a separate PR. Added this as TODO as well.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 415 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17Em0m43xiU4j78PcD:-M17aOO68rXBEQTX7Dr-:bnnu3zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L415)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The file descriptor is automatically released when a zero batch is Dequeued. I think it'll be best to call `CloseInactiveReadPartitions` after this loop (to take care of both partitions in one call). This will actually reclaim disk space.
</blockquote></details>

Switched the call. But we do need to do this inside of the loop because we have two separate partitioned queues. (We could have a single partitioned queue, but that would require some work to introduce mapping from `partitionIdx` in that single queue to "logical" partition index which is needed to join the partitions that have the same logical indices. I don't know whether it'd be useful though.)
___
*[pkg/sql/colexec/external_hash_joiner.go, line 420 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17DtG59Q8-sjaxXxrz:-M17cb5T526TnDNMAOhW:b-38kt8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L420)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we should do this here. I think the invariant should be: we're entering `externalHJRecursivePartitioning`, at that stage we have at most `numBuckets*2` file descriptors open. At the top of the state transition, close all open write file descriptors, which should reduce the open descriptors to 0. Now we open the two read partitions for 2 file descriptors and whatever number of write partitions we want. This'll allow us to remove the call to `CloseAllOpen...` in the first state as well.
</blockquote></details>

Similarly, I'd argue this change belongs in a separate PR. Copied the comment as TODO.

Currently the mechanics are different:
- in "initial" state we use `hj.numBuckets * 2` write descriptors which we close before transitioning to "join new partition" state
- in that state we pick a partition index to join and transition to "joining" state
- in that state we will close read partitions before transitioning back to "join new partition" state
- if we end up in "recursive partitioning" state, we come in with no FDs held, then we pick a partition index and repartition it using `hj.numBuckets` write FDs (while holding one read FD); once the repartition is done, we close all of them.

When another PR merges, we can update this to what you're describing.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 500 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17FUFt1kg47Z6j04sm:-M17bg_bCP5TDoj4vjuM:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L500)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In this case, two partitions that we're joining have been automatically closed, but we want to reclaim the disk space, so you should call `CloseInactiveReadPartitions`.
</blockquote></details>

Good point, done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 506 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17G2yb3b10JANqu3p3:-M17bFgm-AsSGIpiENSQ:b-d94qbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L506)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we need to `Close` the `PartitionedDiskQueue` in this case to remove any leftover files (which should be 0), but still good to do. Maybe add an implementation of the `io.Closer` interface and call that here in preparation for adding the slice of `io.Closer`s to the flow. Actually, the fact that there is no `io.Closer` here should mean that we're failing some tests like `verifySelAndNullResets` which don't fully drain the operator.
</blockquote></details>

The closure did happen in `externalHJJoinNewPartition` state when there are no partitions to join, right before we transition to "finished" state.

`verifySelAndNullResets` is skipped for hash joiner because it doesn't make sense (the test relies on the order in the output being the same between runs which is not the case for hash joiner).

But `allNullsInjection` suffers from the same issue, so I added `Close` method.
Update: this seems still to be insufficient, I think we should skip this `allNullsInjection` subtests for now and merge the PR as is.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 266 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17GaDX7uKhW9n58I-V:-M17vFZ69Gd3KAXVu6xZ:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60 [...]

2020-02-28 03:23 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 506 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M17G2yb3b10JANqu3p3:-M18oB8o-NNtZ-PM1Xt2:b-myyazd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fdc119054957dd5608cb1890a60c1ffa6827bca/pkg/sql/colexec/external_hash_joiner.go#L506)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The closure did happen in `externalHJJoinNewPartition` state when there are no partitions to join, right before we transition to "finished" state.

`verifySelAndNullResets` is skipped for hash joiner because it doesn't make sense (the test relies on the order in the output being the same between runs which is not the case for hash joiner).

But `allNullsInjection` suffers from the same issue, so I added `Close` method.
Update: this seems still to be insufficient, I think we should skip this `allNullsInjection` subtests for now and merge the PR as is.
</blockquote></details>

Added `Close` method to `simpleProjectOp` (which is planned on top of the joiner when not all columns needs to be in the output) and vast majority of unit test cases now run no problem. The only exception are cases with non-empty `ON expr` - those are skipped for now. I think it is acceptable.


<!-- Sent from Reviewable.io -->

2020-02-28 20:01 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-:-M1CNoxdA3CpKQ2gJfKm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 257 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M1CMyqeDi5vibutQCmX:-M1CMyqeDi5vibutQCmY:boxemjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42c376b47d25113f3ae3d85dd9d2a707ba539a/pkg/sql/colexec/external_hash_joiner_test.go#L257)):*
> ```Go
> 								ctx, flowCtx, spec, []Operator{leftSource, rightSource},
> 								func() {}, queueCfg, 0, /* numForcedRepartitions */
> 								NewTestingSemaphore(256), // using the default FD limit
> ```

urgh, I should have probably extracted this `256` number into a constant. could you do it?
___
*[pkg/sql/colexec/sort_chunks.go, line 83 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M1CNPVr1lPkyWTiaTZ_:-M1CNPVs9H6fMhi2XTP_:b-ir7fjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42c376b47d25113f3ae3d85dd9d2a707ba539a/pkg/sql/colexec/sort_chunks.go#L83)):*
> ```Go
> 	// TODO(yuzefovich): switch to calling this method on allocator. This will
> 	// require plumbing unlimited allocator to work correctly in tests with
> 	// memory limit of 1.
> ```

I'm not sure we want to do that, right? A `ForceDiskSpill` should be interpreted by the external sorter to pass in a limited allocator to this operator so that it falls back immediately. I think the problem is that we're allocating in `Init`, maybe we want to do that in `Next`? mm, I don't know, maybe we should talk about this.


<!-- Sent from Reviewable.io -->

2020-02-28 21:33 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 257 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M1CMyqeDi5vibutQCmX:-M1ChkQq3Z_04LoKzfge:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42c376b47d25113f3ae3d85dd9d2a707ba539a/pkg/sql/colexec/external_hash_joiner_test.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

urgh, I should have probably extracted this `256` number into a constant. could you do it?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/sort_chunks.go, line 83 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-M1CNPVr1lPkyWTiaTZ_:-M1CegjD8yz57xmZlHhK:b-78phri) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42c376b47d25113f3ae3d85dd9d2a707ba539a/pkg/sql/colexec/sort_chunks.go#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure we want to do that, right? A `ForceDiskSpill` should be interpreted by the external sorter to pass in a limited allocator to this operator so that it falls back immediately. I think the problem is that we're allocating in `Init`, maybe we want to do that in `Next`? mm, I don't know, maybe we should talk about this.
</blockquote></details>

The issue is that this `windowedBatch` needs to be instantiated even if the in-memory operator uses a limit of `1` because it is used in the process of falling back to disk-backed operator. This batch doesn't have columns, but it does need some space for the selection vector. I imagine there are two ways to address it:
1. add a separate "unlimited" allocator that will be used only once to instantiated this windowed batch
2. introduce an allocator into `ExportBuffered()` method as parameter (as we had at some point).


<!-- Sent from Reviewable.io -->

2020-02-28 21:43 UTC, asubiotto commented
Option 2 might be good. This would be the external sorter's unlimited allocator?

2020-02-28 21:55 UTC, yuzefovich reviewed
Yes, that would be the external operator's unlimited account.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-:-M1CmtMS3TvBTEAgQ0f2:bp1olax)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-02-28 23:36 UTC, yuzefovich reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45301#-:-M1D90Z7C5IpEN9fZXMI:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-02-29 02:09 UTC, yuzefovich commented
bors r-

Needs a rebase.

2020-02-29 02:30 UTC, yuzefovich commented
bors r+

2020-02-29 03:58 UTC, merged