jobs: allow jobs to create SessionBoundInternalExecutors
cockroachdb/cockroach pull request #45526
Opened 2020-02-28 05:33 UTC by lucy-zhang

This PR adds a `SessionBoundInternalExecutorFactory` to the job
registry, and exposes the ability to create session bound internal
executors in jobs via a method `MakeSessionBoundInternalExecutor()` on
`Job`. This is needed for the (forthcoming) temp table cleanup job.

This diff is a subset of #45185 (at time of writing) and only contains the internal executor factory changes. I'm pulling out the changes since they're useful for schema changes as well.

Release note: None

2020-02-28 05:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45526)
<!-- Reviewable:end -->

2020-02-28 15:16 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang, @otan, and @spaskob)

___
*[pkg/jobs/jobs.go, line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45526#-M1BMHHs1CRnrc1etSp0:-M1BMHHt9KNqTaqeeD_p:bnbh7k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/38c2603409fc4152297352972d0783245c0107c3/pkg/jobs/jobs.go#L567)):*
> ```Go
> }
> 
> func (j *Job) MakeSessionBoundInternalExecutor(
> ```

Can you add a comment on describing how this executor will be used, why the job needs to request it from the registry, what the is the life cycle of the executor.


<!-- Sent from Reviewable.io -->

2020-02-29 01:34 UTC, otan commented
usage of this LGTM!

2020-03-03 03:34 UTC, lucy-zhang commented
I'm going to fold this into #44391 instead, since it looks like #45185 will likely end up taking a different approach, so this change will only make sense in the context of the schema change job.

I'm not satisfied with the approach in this PR, and I still think the ideal setup is to have a single InternalExecutor for the entire schema change job, where the table descriptors that override the contents of the TableCollection are specified in a per-query option. But I haven't found a good solution for that, and I don't want to block progress on #44391 (or require too many changes to the internals of the schema changer), so I'm going with the approach in this PR for now.

2020-03-03 03:34 UTC, closed without merging