colcontainer, colexec: add RewindableQueue interface
cockroachdb/cockroach pull request #45620
Opened 2020-03-03 03:41 UTC by yuzefovich

This commit introduces RewindableQueue interface which is a Queue that
can be read from multiple times from the start. It is now implemented by
diskQueue with an introduction of a special "rewindable" read mode in
which fully-read files are not removed upon closure. Which type of disk
queue is created is decided based on the read mode argument from the
disk queue config.

spillingQueue has been extended to support "rewinding" behavior as well:
when the disk queue config has "rewindable" read mode, then in-memory
batches are not discarded while dequeueing, instead, a separate
dequeueState is being kept.

The caveat of using spillingQueue in "rewinding" mode is that those
batches that are kept in memory are returned directly, so if any
modifications to the returned batches occur, then they will be corrupted
on the next "rewind". I think this is acceptable though.

Addresses: #44555.

Release note: None

2020-03-03 03:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45620)
<!-- Reviewable:end -->

2020-03-03 15:43 UTC, asubiotto requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzwM2EDvZ0mUAhynW:-M1VzwM3Emu4FPPtvzG1:b7xrfj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L160)):*
> ```Go
> 	typs  []coltypes.T
> 	cfg   DiskQueueCfg
> 	files []*file
> ```

Do we need to make this a pointer? In `Rewind` we can just do `files[i].curOffsetIdx = 0`
___
*[pkg/sql/colcontainer/diskqueue.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1W-RD6C1gl-ctxd0xc:-M1W-RD76AAyNOZRN4bb:b-kkqxsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L216)):*
> ```Go
> // RewindableQueue is a Queue that can be read from multiple times. Note that
> // in order for this Queue to return the same data after rewinding, all
> // Enqueueing *must* occur before any Dequeueing.
> ```

We should enforce this and return an error, as in the reuse cache mode
___
*[pkg/sql/colcontainer/diskqueue.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzEIJ8UHw2Deapjhl:-M1VzEIK1uqv1qEgPxzG:b-ghdm9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L279)):*
> ```Go
> 	CacheMode DiskQueueCacheMode
> 	// ReadMode defines the way a DiskQueue manages the files. Refer to the
> 	// comment of diskQueueReadModes for more information.
> ```

nit: `/disk/Disk`?
___
*[pkg/sql/colcontainer/diskqueue.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzWiU7oVo6qQtj8Xr:-M1VzWiU7oVo6qQtj8Xs:bv8va4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L350)):*
> ```Go
> 		cfg.OnNewDiskQueueCb()
> 	}
> 	if cfg.ReadMode == DiskQueueReadModeRewindable &&
> ```

Do we want to add this as a config option? If we have separate interfaces for the rewindable disk queue vs not, it makes more sense to me to have this option exposed as a different constructor, i.e.:
```
NewRewindableDiskQueue() RewindableQueue
NewDiskQueue() Queue
```
___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1VzLHzBCyUx_9UFYE8:bb76mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
> ```Go
> 	if cfg.ReadMode == DiskQueueReadModeRewindable &&
> 		cfg.CacheMode == DiskQueueCacheModeClearAndReuseCache {
> 		return nil, errors.Errorf("rewindable read mode is incompatible with clear-and-reuse cache mode")
> ```

Why?
___
*[pkg/sql/colexec/spilling_queue.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1W34Vf-rMeAtg38Zpw:-M1W34Vf-rMeAtg38Zpx:b-xu72q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colexec/spilling_queue.go#L58)):*
> ```Go
> 	rewindable      bool
> 	rewindableState struct {
> 		numItemsDequeuedFromMemory int
> ```

You might be able to just keep track of `numItemsDequeued`


<!-- Sent from Reviewable.io -->

2020-03-03 21:33 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colcontainer/diskqueue.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzwM2EDvZ0mUAhynW:-M1Wa1DmEzxJ65UQrlIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L160)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we need to make this a pointer? In `Rewind` we can just do `files[i].curOffsetIdx = 0`
</blockquote></details>

Done.
___
*[pkg/sql/colcontainer/diskqueue.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1W-RD6C1gl-ctxd0xc:-M1WcQg9AE-zCzUoZ9OK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L216)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We should enforce this and return an error, as in the reuse cache mode
</blockquote></details>

Done.
___
*[pkg/sql/colcontainer/diskqueue.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzEIJ8UHw2Deapjhl:-M1Wchtx31OkqJznHEi6:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L279)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `/disk/Disk`?
</blockquote></details>

Removed.
___
*[pkg/sql/colcontainer/diskqueue.go, line 350 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzWiU7oVo6qQtj8Xr:-M1Wbw1o2pO9kr2ih5v3:b80k70f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L350)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to add this as a config option? If we have separate interfaces for the rewindable disk queue vs not, it makes more sense to me to have this option exposed as a different constructor, i.e.:
```
NewRewindableDiskQueue() RewindableQueue
NewDiskQueue() Queue
```
</blockquote></details>

Done. This was also my initial thought, but then I changed it for ease of tests I guess.
___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1Wc8En3nZV9klLOOwW:ba0w14l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Deleted, but is it possible that some batches will be held in the cache and if we clear it, after `Rewind()`, they will get lost?
___
*[pkg/sql/colexec/spilling_queue.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1W34Vf-rMeAtg38Zpw:-M1X-ycu47lASVqCi0lg:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colexec/spilling_queue.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You might be able to just keep track of `numItemsDequeued`
</blockquote></details>

Good point, done.


<!-- Sent from Reviewable.io -->

2020-03-04 16:00 UTC, asubiotto reviewed
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1aF_g61T5oUCl6UP45:b-6wtaf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Deleted, but is it possible that some batches will be held in the cache and if we clear it, after `Rewind()`, they will get lost?
</blockquote></details>

The cache is only cleared when enqueueing a zero batch. If we Rewind when Dequeuing, unread batches will get lost, but that's the case for any `CacheMode` but I think that's ok when rewinding (they'll still be reread from disk).
___
*[pkg/sql/colcontainer/diskqueue_test.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1aGBLE7sQV2NRAT6WA:-M1aGBLE7sQV2NRAT6WB:b-vtl0bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab3405b76a53659b56313c6b645ab1ab10203dd/pkg/sql/colcontainer/diskqueue_test.go#L45)):*
> ```Go
> 
> 	rng, _ := randutil.NewPseudoRand()
> 	for _, rewindable := range []bool{false, true} {
> ```

How's the runtime on this test now? We could disable `AlwaysCompress` if the queue is rewindable, don't think it adds testing coverage but it would be good to understand why it's slow if it still is.
___
*[pkg/sql/colexec/spilling_queue.go, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1aGUZp5SzXXV27oS3s:-M1aGUZp5SzXXV27oS3t:b-f291lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab3405b76a53659b56313c6b645ab1ab10203dd/pkg/sql/colexec/spilling_queue.go#L202)):*
> ```Go
> }
> 
> func (q *spillingQueue) maybeSpillToDisk(ctx context.Context) (err error) {
> ```

I don't think this needs a named return variable


<!-- Sent from Reviewable.io -->

2020-03-04 16:49 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1aRIYH2uTUxtqSj_e5:bgde3hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The cache is only cleared when enqueueing a zero batch. If we Rewind when Dequeuing, unread batches will get lost, but that's the case for any `CacheMode` but I think that's ok when rewinding (they'll still be reread from disk).
</blockquote></details>

Could you spell out the sequence of what gets released when? I mean something like
- we enqueue several batches, all of them are held in the cache (is it write or read cache?)
- then we enqueue zero-length batch (what happens to the cache?)
- we dequeue batches (where they are served from?)
- etc.
___
*[pkg/sql/colcontainer/diskqueue_test.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1aGBLE7sQV2NRAT6WA:-M1aQLEd3Lw5ZT7-hzZO:b-83odhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab3405b76a53659b56313c6b645ab1ab10203dd/pkg/sql/colcontainer/diskqueue_test.go#L45)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How's the runtime on this test now? We could disable `AlwaysCompress` if the queue is rewindable, don't think it adds testing coverage but it would be good to understand why it's slow if it still is.
</blockquote></details>

I believe the slowness was caused due to unlucky set of circumstances - `coldata.BatchSize()` was set to almost 4000, and then we generated almost 2000 of batches, and under stress this was extremely slow.

Right now the runtime seems ok (and `alwaysCompress` doesn't seem to have much of an effect).
___
*[pkg/sql/colexec/spilling_queue.go, line 202 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1aGUZp5SzXXV27oS3s:-M1aQxBU4_JVw0OKDk9l:bmf0dip) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ab3405b76a53659b56313c6b645ab1ab10203dd/pkg/sql/colexec/spilling_queue.go#L202)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think this needs a named return variable
</blockquote></details>

I wanted to omit one code line by avoiding a `var err error` declaration, changed.


<!-- Sent from Reviewable.io -->

2020-03-04 20:45 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-:-M1bHp8s89vcwUEbW7t_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1bH9q_-Nk5qUYLLf1q:b3cfian) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Could you spell out the sequence of what gets released when? I mean something like
- we enqueue several batches, all of them are held in the cache (is it write or read cache?)
- then we enqueue zero-length batch (what happens to the cache?)
- we dequeue batches (where they are served from?)
- etc.
</blockquote></details>

In the `ClearAndReuseCacheMode`:
- We enqueue several batches, they are held in the write cache.
- Once the zero batch is enqueued, whatever batches that are still in the cache get flushed to disk. The write cache is cleared/GCed.
- When we start to dequeue batches, we automatically reallocate the cache on the read side (in `maybeInitDeserializer`) and use that as the read cache to serve batches from.
- When `Rewind`ing, we don't clear the cache, but it doesn't matter. That memory will be reused to deserialize the first couple of batches from the first file on `Dequeue` and the batches will be there.


<!-- Sent from Reviewable.io -->

2020-03-04 20:46 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-:-M1bI-JSCyh_rdj15Xlo:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colcontainer/diskqueue.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45620#-M1VzLHzBCyUx_9UFYE7:-M1bI1TsBuwdUiyciHW8:bv3rmoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0727f5eb9791da18567aefbdd064a96c3d42fd/pkg/sql/colcontainer/diskqueue.go#L352)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In the `ClearAndReuseCacheMode`:
- We enqueue several batches, they are held in the write cache.
- Once the zero batch is enqueued, whatever batches that are still in the cache get flushed to disk. The write cache is cleared/GCed.
- When we start to dequeue batches, we automatically reallocate the cache on the read side (in `maybeInitDeserializer`) and use that as the read cache to serve batches from.
- When `Rewind`ing, we don't clear the cache, but it doesn't matter. That memory will be reused to deserialize the first couple of batches from the first file on `Dequeue` and the batches will be there.
</blockquote></details>

This makes sense, thanks!


<!-- Sent from Reviewable.io -->

2020-03-04 21:38 UTC, merged