ui: Filter out internal statements for default All filter
cockroachdb/cockroach pull request #45646
Opened 2020-03-03 14:56 UTC by koorosh

Release note (admin ui change): ALL filter doesn't include
internal statements (on Statements page)

2020-03-03 14:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45646)
<!-- Reviewable:end -->

2020-03-17 22:01 UTC, dhartunian requested changes
Nice focused change, just want to take an opportunity to refactor a bit before we merge.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-:-M2eSN1W9n-EYk4mkhWW:b-ozorjd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)

___
*[pkg/ui/src/views/statements/statements.spec.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eR2ZhD55PNm8EPNPg:-M2eR2ZhD55PNm8EPNPh:b56zuc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statements.spec.tsx#L53)):*
> ```XML
>   });
> 
>   it("returns the statements without Internal for default ALL filter", () => {
> ```

Thanks for the test!
___
*[pkg/ui/src/views/statements/statements.spec.tsx, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eR5-T5L-uTd1-b6ih:-M2eR5-T5L-uTd1-b6ii:b-jqjccu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statements.spec.tsx#L445)):*
> ```XML
>             nanos: 0,
>           },
>           internal_app_name_prefix: "$ internal",
> ```

Extract this into a string constant
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eRuCg0k33E4iKObfQ:-M2eRuCg0k33E4iKObfR:b-3gbuue) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statementsPage.tsx#L283)):*
> ```XML
>     } else {
>       statements = statements.filter(
>         (statement: ExecutionStatistics) => !statement.app.startsWith(state.data.internal_app_name_prefix),
> ```

Can we extract the filter here and the one above into named lambdas?  That would help make them more readable and the lines would be shorter.


<!-- Sent from Reviewable.io -->

2020-03-17 22:03 UTC, dhartunian reviewed
Forgot to mention that we'll need Release Justification for this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-:-M2eWM763dreKYYj0Bm7:b-uuwxzv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh)



<!-- Sent from Reviewable.io -->

2020-03-18 11:18 UTC, koorosh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[pkg/ui/src/views/statements/statements.spec.tsx, line 445 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eR5-T5L-uTd1-b6ih:-M2hLvcF4CJ3JhWk5qXY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statements.spec.tsx#L445)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Extract this into a string constant
</blockquote></details>

Done
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eRuCg0k33E4iKObfQ:-M2hM2Ej5QqJ4Rj0qjDS:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statementsPage.tsx#L283)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we extract the filter here and the one above into named lambdas?  That would help make them more readable and the lines would be shorter.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-03-18 11:22 UTC, koorosh reviewed
@dhartunian , added release justification

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-:-M2hN9X-CYWk4lvL5Z47:b-1nrrxe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ui/src/views/statements/statements.spec.tsx, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eR2ZhD55PNm8EPNPg:-M2hMxyO81uzKcnkRX2H:b-vo27v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statements.spec.tsx#L53)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Thanks for the test!
</blockquote></details>

🙌🏼


<!-- Sent from Reviewable.io -->

2020-03-18 20:08 UTC, dhartunian requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eRuCg0k33E4iKObfQ:-M2jFZT1-hTd1jvzDDyH:bppletm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statementsPage.tsx#L283)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Done
</blockquote></details>

One more ask (sorry), but now that you have named funtions, you can just pass them to `filter` without creating a new lambda! Then the line is shorter and simpler.


<!-- Sent from Reviewable.io -->

2020-03-18 22:19 UTC, koorosh commented
> > Reviewed 1 of 2 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)
> 
> _[pkg/ui/src/views/statements/statementsPage.tsx, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-M2eRuCg0k33E4iKObfQ:-M2jFZT1-hTd1jvzDDyH:bppletm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb8a168ebf6fc8fe2a2288e548cf8911dbe2bab/pkg/ui/src/views/statements/statementsPage.tsx#L283)):_
> 
> Previously, koorosh (Andrii Vorobiov) wrote…
> One more ask (sorry), but now that you have named funtions, you can just pass them to `filter` without creating a new lambda! Then the line is shorter and simpler.

@dhartunian , I thought about this, and it is kind of trade of for me because then I need `isNotInternal` instead of `isInternal` function to pass it in`filter` directly (without one more lambda function). 
Function names with negative prefixes isn't the best practice I would say. Do you think it makes sense?

2020-03-20 18:34 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45646#-:-M2tD2tKEDnv5bT62wjO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)



<!-- Sent from Reviewable.io -->

2020-03-20 18:34 UTC, dhartunian commented
bors r+

2020-03-24 22:13 UTC, dhartunian commented
bors r+

2020-03-24 23:40 UTC, merged