colexec: add fallback from external hash join to sort + merge join
cockroachdb/cockroach pull request #45825
Opened 2020-03-07 00:26 UTC by yuzefovich

This commit finishes the implementation of the external hash joiner by
adding the fallback to (disk-backed) sort + merge join strategy for the
case when recursive partitioning doesn't reduce the size of the
partition enough to fit in the memory. The idea is very simple: we
accumulate the indices of the partitions that are too big to join using
in-memory hash joiner, and once there are no more indices that the
in-memory hash joiner can join, we transition to different state in
which we will join the partitions with the accumulated indices one at
a time with a chain of disk-backed sort followed by disk-backed merge
join.

Fixes: #45594.

Release note: None

2020-03-07 00:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45825)
<!-- Reviewable:end -->

2020-03-09 18:48 UTC, yuzefovich commented
I think this is RFAL.

2020-03-09 19:57 UTC, asubiotto requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mgDGEN0KrOuzKi1B:-M2-mgDGEN0KrOuzKi1C:b4na0mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L274)):*
> ```Go
> 	}
> 	leftOrdering := makeOrderingCols(spec.left.eqCols)
> 	leftPartitionSorter, err := createReusableDiskBackedSorter(
> ```

I think we might want to do this lazily instead.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-nMXmBAqdMczX_I2Q:-M2-nMXmBAqdMczX_I2R:bfo3w9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L281)):*
> ```Go
> 	}
> 	rightOrdering := makeOrderingCols(spec.right.eqCols)
> 	rightPartitionSorter, err := createReusableDiskBackedSorter(
> ```

This and the merge joiner might also try to `Acquire` file descriptors. How are we guaranteed that we never exceed the maximum number of file descriptors?
___
*[pkg/sql/colexec/external_hash_joiner.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mp_MEzyWIAa8pVHj:-M2-mp_MEzyWIAa8pVHk:b-lbut5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L288)):*
> ```Go
> 	}
> 	diskBackedSortMerge, err := newMergeJoinOp(
> 		// TODO(yuzefovich): maybe different cache mode for disk queues.
> ```

What do you mean?
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-pZd48z39y184w0Z6:-M2-pZd5EWQX88ZmS748:b-jiws42) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L34)):*
> ```Go
> 
> // externalHJTestMaxNumberPartitions specifies the minimum number of partitions
> // that be the limit for the external hash joiner. External hash joiner needs
> ```

nit: that be the limit
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-px5uCUP3X64BoPzC:-M2-px5uCUP3X64BoPzD:b1rlwir) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L37)):*
> ```Go
> // at least two partitions per side (i.e. we need at least 4), but during the
> // fallback to sort + merge join we will be using 6 (external sorter on each
> // side will use 2 to read its own partitions and 1 more to write out).
> ```

Also 1 to read from the partition, right? But that'll be the same as the 1 to write out.
___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M2-qwc98rgJFPP8xiFe:b-k5ckea) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
> ```Go
> 		case externalSorterFinished:
> 			if s.usageMode == externalOperatorUsageModeDefault {
> 				if err := s.Close(); err != nil {
> ```

Why do we avoid closing this? The other option would be to close and create a new partitioned disk queue when resetting.


<!-- Sent from Reviewable.io -->

2020-03-09 20:27 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mgDGEN0KrOuzKi1B:-M2-vCo4BF0qH6ijOOEJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L274)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we might want to do this lazily instead.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-nMXmBAqdMczX_I2Q:-M2-xz8b6miYhLiELHWb:bgap8yi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L281)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This and the merge joiner might also try to `Acquire` file descriptors. How are we guaranteed that we never exceed the maximum number of file descriptors?
</blockquote></details>

There is no guarantee because it requires #45982. And I'd argue that this guarantee should not be a part of this fallback PR.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mp_MEzyWIAa8pVHj:-M2-vM1IAeyuhfNdFYWT:b-91thnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L288)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

The merge joiner itself will be using `spillingQueue` plus the external sorts (which are inputs to merge joiner) will be using partitioned disk queues. This TODO is to figure out whether two kinds of queues should use different cache modes (I don't know whether that matters much). Thoughts?
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-pZd48z39y184w0Z6:-M2-w-Bu1o4vig1NQrdU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L34)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: that be the limit
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-px5uCUP3X64BoPzC:-M2-w-vI8MXjJ8jYLbNm:byvaydg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L37)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Also 1 to read from the partition, right? But that'll be the same as the 1 to write out.
</blockquote></details>

That single FD to read should be released before the merge. So in the comment I'm describing the maximum number of FDs that should be held at once.
___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M2-wEBa8bPvAumQaUlQ:b-l1k3fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do we avoid closing this? The other option would be to close and create a new partitioned disk queue when resetting.
</blockquote></details>

We avoid closing so that we didn't have to recreate the disk queues. Do see an issue with that?


<!-- Sent from Reviewable.io -->

2020-03-09 20:59 UTC, asubiotto requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-nMXmBAqdMczX_I2Q:-M202TaG6lRQiy_W3qVz:bsxpsdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L281)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

There is no guarantee because it requires #45982. And I'd argue that this guarantee should not be a part of this fallback PR.
</blockquote></details>

I don't think #45892 helps here though, but #45892 does need to be sure that even when we're doing this fallback, we never exceed `maxNumberActivePartitions` I guess what we need is some way to pass in to the sorter that it should not use more than n partitions (which I think we already have, but as a testing knob) and say that we'll have `2+n/2` resources requested maximum where 2 are the read partitions, `n/2` is the maximum number of partitions in the sorter. I guess the merge joiner does use 2 for the spilling queue (although it probably doesn't need to) so it's probably more like `4+n/2`. We can find n such that the thing is less than `maxNumberActivePartitions, and that should be sufficient. I guess we can do it in another PR, but I don't think it should be too onerous to do it in this one.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mp_MEzyWIAa8pVHj:-M20434v0hicxq50oYwi:b-j26fs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L288)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The merge joiner itself will be using `spillingQueue` plus the external sorts (which are inputs to merge joiner) will be using partitioned disk queues. This TODO is to figure out whether two kinds of queues should use different cache modes (I don't know whether that matters much). Thoughts?
</blockquote></details>

We definitely want the sort to use its default `ReuseCache` mode but I think it will already do so. In the merge joiner case I think we probably want the `ReuseCache` mode as well, although this applies to normal operation as well. This can be done in another PR.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-px5uCUP3X64BoPzC:-M204Znv8UWPwfJ4n7XY:b-awrfg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L37)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

That single FD to read should be released before the merge. So in the comment I'm describing the maximum number of FDs that should be held at once.
</blockquote></details>

Ack, could you make it a bit more clear?
___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M204j0G-GM5s9WMTH0T:bf3jwnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We avoid closing so that we didn't have to recreate the disk queues. Do see an issue with that?
</blockquote></details>

We'll have a bunch of leftover data because we don't remove the files. We do remove the files in the mergjoiner though when calling `spillingQueue.reset`


<!-- Sent from Reviewable.io -->

2020-03-09 23:27 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_hash_joiner.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-nMXmBAqdMczX_I2Q:-M20abZT2wyl_opMuKTf:b-yk4v63) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L281)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think #45892 helps here though, but #45892 does need to be sure that even when we're doing this fallback, we never exceed `maxNumberActivePartitions` I guess what we need is some way to pass in to the sorter that it should not use more than n partitions (which I think we already have, but as a testing knob) and say that we'll have `2+n/2` resources requested maximum where 2 are the read partitions, `n/2` is the maximum number of partitions in the sorter. I guess the merge joiner does use 2 for the spilling queue (although it probably doesn't need to) so it's probably more like `4+n/2`. We can find n such that the thing is less than `maxNumberActivePartitions, and that should be sufficient. I guess we can do it in another PR, but I don't think it should be too onerous to do it in this one.
</blockquote></details>

Good point. It's a small change, so I added to this PR.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-mp_MEzyWIAa8pVHj:-M20V0NBCO99YoPZSe6d:bn5p7ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner.go#L288)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We definitely want the sort to use its default `ReuseCache` mode but I think it will already do so. In the merge joiner case I think we probably want the `ReuseCache` mode as well, although this applies to normal operation as well. This can be done in another PR.
</blockquote></details>

Yeah, sorter already is using `ReuseCache`, modified the disk queue config for merge joiner as well.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M20WnFjCiV3pUi9MwdZ:-M20WnFjCiV3pUi9Mwd_:b-s4q28k) ([raw file](https://github.com/cockroachdb/cockroach/blob/22800329bfc83d797d7996acdd6158f1f9a0dfbb/pkg/sql/colexec/external_hash_joiner.go#L272)):*
> ```Go
> 		maxNumberActivePartitions = 4
> 	}
> 	diskBackedSortMergeCreator := func() resettableOperator {
> ```

Making the instantiation lazy breaks the assumption that all memory monitoring infra is created during planning (and gets added to `NewColOperatorResult`), so I reverted this change. Other changes made creation of partitioned queues in external sort lazy, so I think this should be ok.
___
*[pkg/sql/colexec/external_hash_joiner_test.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-px5uCUP3X64BoPzC:-M20ReWV4_Cif5CiOB2z:b8q98t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_hash_joiner_test.go#L37)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Ack, could you make it a bit more clear?
</blockquote></details>

Extended the comment. It's pretty hard to describe this limitation in words.
___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M20Ug8-BnElA3VtFkgO:b-vewld2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We'll have a bunch of leftover data because we don't remove the files. We do remove the files in the mergjoiner though when calling `spillingQueue.reset`
</blockquote></details>

Ok, I see. Removed this "reusable" behavior.


<!-- Sent from Reviewable.io -->

2020-03-10 03:18 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M21RkDq1i1k66dzrd1N:brm73r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Ok, I see. Removed this "reusable" behavior.
</blockquote></details>

After the removal, the tests are failing (not all file descriptors are closed), and I can't seem to track the problem down. Does anything stands out to you?


<!-- Sent from Reviewable.io -->

2020-03-10 13:47 UTC, asubiotto requested changes
I'm not sure I understand the WIP commit. Is it to address the flow teardown? If so, I'm not sure we want to do it this way. The operators should be added to a slice of closers as we're constructing the flow. If not, we should go down a more principled route and mirror what we did for `DrainMeta` and add an `OperatorCloser` interface that we'll accumulate and give to components that want to be aware of closing. This avoids having to implement closing propagation logic properly everywhere, which is something that's probably error-prone. If not necessary for this PR, I think we should definitely do it in another one.

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-:-M23fol48oELSZ3Se4yW:brdabw0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M23exDF4Xewl81knAcb:b8uoi8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

After the removal, the tests are failing (not all file descriptors are closed), and I can't seem to track the problem down. Does anything stands out to you?
</blockquote></details>

Are there cases where we could be resetting without closing?
___
*[pkg/sql/colexec/external_sort_test.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M23fKPgAu0al3exZjGD:-M23fKPgAu0al3exZjGE:b-q1vjin) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc28e140e5d59338f28fb58260da1f5fbf0eb7/pkg/sql/colexec/external_sort_test.go#L152)):*
> ```Go
> 		memMonitors []*mon.BytesMonitor
> 	)
> 	const maxNumberPartitions = 3
> ```

Curious: why the increase?
___
*[pkg/sql/colexec/mergejoiner.go, line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M23fTJ5DfuKK5fZEgba:-M23fTJ5DfuKK5fZEgbb:b-18qb80) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc28e140e5d59338f28fb58260da1f5fbf0eb7/pkg/sql/colexec/mergejoiner.go#L331)):*
> ```Go
> 	}
> 
> 	diskQueueCfg.CacheMode = colcontainer.DiskQueueCacheModeReuseCache
> ```

I think we also want to call `diskQueueCfg.SetDefaultNumBytes...`


<!-- Sent from Reviewable.io -->

2020-03-10 17:01 UTC, yuzefovich reviewed
No, the WIP commit it was me trying to figure out where the file descriptors are being leaked, I removed the commit. The build should be green now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-:-M24Mai1533XY8aXLbWD:b-cbi320)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/external_sort.go, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M2-qwc98rgJFPP8xiFd:-M24MjXo91NG1ws0REtz:ba7m89x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0504c8d0ac70cd80ec6285768034cb727ea416f/pkg/sql/colexec/external_sort.go#L284)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are there cases where we could be resetting without closing?
</blockquote></details>

Yep, that was the case - for certain join types merge joiner can not fully drain one of the inputs (for example, in LEFT OUTER the right input might not be drained, so `externalSorter.Close` would not be called), so we need to `Close` the external sorter explicitly while resetting.
___
*[pkg/sql/colexec/external_sort_test.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M23fKPgAu0al3exZjGD:-M24N0wkDxbvrERtlnd3:b-lqm15m) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc28e140e5d59338f28fb58260da1f5fbf0eb7/pkg/sql/colexec/external_sort_test.go#L152)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Curious: why the increase?
</blockquote></details>

I realized that we were incorrectly adhering to the limit - previously, we would accumulate `n` partitions and then merging it and spill into a new one which resulted in using `n+1` file descriptors while the limit should be `n`. Now we will be accumulating up to `n-1` partitions, merging and spilling them.
___
*[pkg/sql/colexec/mergejoiner.go, line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M23fTJ5DfuKK5fZEgba:-M24NRzN1hzEJQZtFwCw:bt1pm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc28e140e5d59338f28fb58260da1f5fbf0eb7/pkg/sql/colexec/mergejoiner.go#L331)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we also want to call `diskQueueCfg.SetDefaultNumBytes...`
</blockquote></details>

Good point. Done.

We might want to change the interaction here: add `Get` and `Set` methods for the cache mode with `Set` method internally setting the buffer size bytes, and unexport `CacheMode` field entirely, so that in the future we are not in a position where we could set the cache mode without setting the buffer size bytes.


<!-- Sent from Reviewable.io -->

2020-03-10 17:16 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> this probably needs a release justification now

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-:-M24RLBxDDfBHYdpgBb5:bi0ohpf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/mergejoiner.go, line 331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/45825#-M23fTJ5DfuKK5fZEgba:-M24RQTl5pEccWUhTDN4:b-7ez96f) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc28e140e5d59338f28fb58260da1f5fbf0eb7/pkg/sql/colexec/mergejoiner.go#L331)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Good point. Done.

We might want to change the interaction here: add `Get` and `Set` methods for the cache mode with `Set` method internally setting the buffer size bytes, and unexport `CacheMode` field entirely, so that in the future we are not in a position where we could set the cache mode without setting the buffer size bytes.
</blockquote></details>

Good suggestion, although there might be cases we want to leave the buffer size bytes unchanged? We can do this in another PR.


<!-- Sent from Reviewable.io -->

2020-03-10 17:46 UTC, yuzefovich commented
TFTR!

bors r+

2020-03-10 18:14 UTC, merged