backupccl: adopt protected timestamps for BACKUP
cockroachdb/cockroach pull request #45859
Opened 2020-03-08 23:15 UTC by pbardea

This change ensures that the timestamp at which a BACKUP starts is not
GC'd during the lifetime of the backup. It does this by leveraging the
protected timestamp package.

Release note (enterprise change): BACKUPs will no longer fail if the GC window for
a table is exceeded while backing the table up.

2020-03-08 23:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/45859)
<!-- Reviewable:end -->

2020-03-08 23:16 UTC, pbardea commented
This PR just applies the same changes as #44739.

2020-03-08 23:47 UTC, ajwerner requested changes
LGTM mod the comment. Thanks!

> Reviewed 1 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-:-M1wXn388jAOjWtKabN1:bcllspn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @pbardea)

___
*[testplan, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-M1wUfEj4s_W4NwldbZZ:-M1wUfEkB5TlC6vvuqoS:b44u1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e59c9294d37e4d836cf4122cde6f73cef4fab7b/testplan#L1)):*
> ```
> x while !test_passes {
> ```

🧐
___
*[pkg/ccl/backupccl/backup_job.go, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-M1wV16L7SiFRnozDW8B:-M1wV16L7SiFRnozDW8C:bivlbeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e59c9294d37e4d836cf4122cde6f73cef4fab7b/pkg/ccl/backupccl/backup_job.go#L462)):*
> ```Go
> 	b.makeExternalStorage = p.ExecCfg().DistSQLSrv.ExternalStorage
> 
> 	ptsID := details.ProtectedTimestampRecord
> ```

Something i realize now is this needs to check for errnotexists and then return early because we might crash after removing it. 


<!-- Sent from Reviewable.io -->

2020-03-09 00:27 UTC, pbardea reviewed
Thanks for taking a look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-:-M1wgBhHAqYbRdI3s89q:bubxju8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

___
*[testplan, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-M1wUfEj4s_W4NwldbZZ:-M1wfT1A7_aV9V4u6Prb:b-tmuyzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e59c9294d37e4d836cf4122cde6f73cef4fab7b/testplan#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

🧐
</blockquote></details>

:see_no_evil: 
___
*[pkg/ccl/backupccl/backup_job.go, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45859#-M1wV16L7SiFRnozDW8B:-M1wgA9E810i3vRlTRCB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e59c9294d37e4d836cf4122cde6f73cef4fab7b/pkg/ccl/backupccl/backup_job.go#L462)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Something i realize now is this needs to check for errnotexists and then return early because we might crash after removing it. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-09 18:56 UTC, merged