roachtest: adjust tpchvec
cockroachdb/cockroach pull request #46105
Opened 2020-03-14 02:03 UTC by yuzefovich

Release justification: non-production code changes.

This commit adjusts tpchvec test in the following ways:
- it disables the verbose logging of `bytes_usage` (this was enabled to
get something to dig into in case a fatal OOM error that occurred once
would occur again, but it didn't)
- it introduces two "run configurations" into the test:
1. keeps the previous behavior with minor tweaks (removes the
randomization of `workmem` and enabled verbose logging for
`vectorized_flow` file so that we see whether a disk spill occurs). This
configuration is meant to be used to check the correctness of the
vectorized engine and compare the queries' runtimes against row-by-row
engine.
2. adds a new configuration in which only the vectorized engine runs all
queries once, but the workmem is randomized in [100KiB, 1000KiB) range.
This configuration is meant to stress disk spilling of the vectorized
engine. There is no verbose logging and no comparison of the runtimes
(since the row-by-row engine is not used in this config).

Release note: None

2020-03-14 02:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46105)
<!-- Reviewable:end -->

2020-03-16 10:43 UTC, asubiotto requested changes
I think we should switch around verbose logging in the correctness case but not in the performance case. We shouldn't log verbosely if we're measuring the performance of the engine.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-:-M2Xtmaj8rgAl2q1Sccn:bblamvq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-M2XvoliDybEX_Z8MvCi:-M2XvoliDybEX_Z8MvCj:b-p6t11l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8533b6de510be07dc0186ff5428f4516800518d1/pkg/cmd/roachtest/tpchvec.go#L520)):*
> ```Go
> 				// We are interested in the performance comparison between
> 				// vectorized and row-by-row engines, so we will set workmem
> 				// limit to a random value in range [1MiB, 64MiB].
> ```

Do we want to compare performance with a limit of `1MiB`? I'm thinking that we shouldn't care to much about this case and maybe run it with at least `32MiB`.


<!-- Sent from Reviewable.io -->

2020-03-16 15:52 UTC, yuzefovich reviewed
I agree now, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-:-M2Z12GP9tmPtMbrBP7P:b-3fdpf2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-M2XvoliDybEX_Z8MvCi:-M2Z0ZTIAGmbIxnoAopc:b1bsf40) ([raw file](https://github.com/cockroachdb/cockroach/blob/8533b6de510be07dc0186ff5428f4516800518d1/pkg/cmd/roachtest/tpchvec.go#L520)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to compare performance with a limit of `1MiB`? I'm thinking that we shouldn't care to much about this case and maybe run it with at least `32MiB`.
</blockquote></details>

This was my initial idea, then I thought why would we give up the randomization, but now I'm back in the same camp as you are - we have one config that is about the performance (plus correctness) which we should run with the default limit, and we have another configs that stresses the correctness (here we can randomize the limit).


<!-- Sent from Reviewable.io -->

2020-03-16 15:59 UTC, asubiotto reviewed
Is it possible to run only one config but not the other one from `./bin/roachtest run`? If not, I think that that would be amazing to have.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-:-M2Z3OdrCAwTnCC4cj-l:b4cgv0b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-03-16 16:00 UTC, yuzefovich commented
I don't think so, and it is beyond the scope of this PR (I believe `roachtest` infrastructure would need to be refactored cause it doesn't take arguments).

2020-03-16 16:36 UTC, asubiotto reviewed
I think it would be a nice addition though. I don't mean arguments to roachtest, I guess i'm more talking about a different test name, so extracting the configuration of stressing disk spilling one level above and registering a new test at the bottom of this file that will run `runTPCHVec` with one arg or another e.g.:
```
	r.Add(testSpec{
		Name:       "tpchvec",
		Owner:      OwnerSQLExec,
		Cluster:    makeClusterSpec(nodeCount),
		MinVersion: "v19.2.0",
		Run:        runTPCHVec,
---- NEW ---
                StressDiskSpilling: true,
	})
	r.Add(testSpec{
		Name:       "tpchvec/perf",
		Owner:      OwnerSQLExec,
		Cluster:    makeClusterSpec(nodeCount),
		MinVersion: "v19.2.0",
		Run:        runTPCHVec,
	}

```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-:-M2ZBRfkBspHO5T24G1v:b-3awduf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-03-16 16:54 UTC, yuzefovich commented
Oh, I see, nice idea, done.

2020-03-16 17:03 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46105#-:-M2ZI7LwCquWEfRG1u77:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-03-16 17:04 UTC, yuzefovich commented
TFTR!

bors r+

2020-03-16 18:38 UTC, merged