ui: Timescale test
cockroachdb/cockroach pull request #46259
Opened 2020-03-18 16:04 UTC by elkmaster

replaced `Timescale` class component to functional, added tests for timescale

Release note (ui): none

2020-03-18 16:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46259)
<!-- Reviewable:end -->

2020-06-11 09:25 UTC, koorosh requested changes
Got an error on project build:
```
ERROR: cockroachdb/cockroach/pkg/ui/src/views/cluster/components/controls/controls.spec.tsx:41:4 - file should end with a newline
```
Please take a look at this error.

2020-06-11 09:26 UTC, koorosh commented on pkg/ui/src/views/cluster/components/controls/controls.spec.tsx
> +// Copyright 2018 The Cockroach Authors.
Please, update year. 2018 -> 2020

2020-06-12 08:27 UTC, koorosh reviewed
@elkmaster , I have a concern about `TimeFrameControls` component and props it exposes.
- `disabledArrows` prop makes you iterate three times over the same array to check if buttons have to be disabled.
-  Would it be more clear to name props as `onButtonClick` instead of `onArrowClick`
- it is only three buttons in the component and I suppose it can be more meaningful to change  `disabledArrows` prop to three props like: `isBackButtonDisabled`, `isForwardButtonDisabled`, and `isNowButtonDisabled` props.

2020-06-18 13:43 UTC, elkmaster commented on pkg/ui/src/views/cluster/containers/timescale/index.tsx
> +  const arrowClick = (direction: ArrowDirection) => {
Arrow direction is not used as dropdown icon direction. Not great naming due to the fact as on previous designs it was arrows. But I would do not refactor that part in terms of this pr as this is about tests only. Let's revisit it in terms of integrating DS component here.

2020-06-19 10:39 UTC, elkmaster commented on pkg/ui/src/views/cluster/containers/timescale/index.tsx
> +        : moment.utc(currentWindow.start).format(dateFormat),
good catch, added utc for L79-80

2020-06-19 10:42 UTC, elkmaster commented
> @elkmaster , I have a concern about `TimeFrameControls` component and props it exposes.
> 
> * `disabledArrows` prop makes you iterate three times over the same array to check if buttons have to be disabled.
> * Would it be more clear to name props as `onButtonClick` instead of `onArrowClick`
> * it is only three buttons in the component and I suppose it can be more meaningful to change  `disabledArrows` prop to three props like: `isBackButtonDisabled`, `isForwardButtonDisabled`, and `isNowButtonDisabled` props.

I agree but would like to revisit this in terms of other ticket. This pr is about test coverage only.

2020-06-19 10:46 UTC, koorosh requested changes
Tests look good to me, but code still needs to be cleaned up. Please take a look at my comments.

2020-06-19 10:46 UTC, koorosh commented on pkg/ui/src/views/cluster/containers/timescale/timescale.spec.tsx
> +// import { assert } from "chai";
Remove commented imports

2020-06-19 10:46 UTC, koorosh commented on pkg/ui/src/views/cluster/containers/timescale/timescale.spec.tsx
> +const dateFormat = "MMM DD,";
Would it be better to reuse `dateFormat` and `timeFormat` by exporting them and importing them in tests? Will reduce code duplication.

2020-06-19 10:46 UTC, koorosh commented on pkg/ui/src/views/cluster/containers/timescale/timescale.spec.tsx
> +    console.log(wrapper.find(".trigger .Select-value-label"));
Remove `console.log`

2020-06-19 10:46 UTC, koorosh commented on pkg/ui/src/views/cluster/containers/timescale/timescale.spec.tsx
> +import { expect, assert } from "chai";
What is a reason to use `expect` for assertions? By default `assert` is used across the entire project.

2020-06-19 12:54 UTC, elkmaster commented on pkg/ui/src/views/cluster/components/controls/controls.spec.tsx
> +    spy = sinon.spy();
that was original intent, but it is not worked well, so I switched to class based tests. Removed leftovers

2020-06-29 13:58 UTC, koorosh approved these changes
LGTM

2020-07-01 14:38 UTC, dhartunian approved these changes

2020-07-02 08:35 UTC, elkmaster commented
bors r+

2020-07-02 14:08 UTC, elkmaster commented
bors r+

2020-07-06 16:25 UTC, dhartunian commented
bors r+

2020-07-22 14:24 UTC, elkmaster commented
bors r+

2020-07-22 15:23 UTC, merged