changefeedccl,jobs: add behavior on PauseRequest, protect CHANGEFEED data
cockroachdb/cockroach pull request #46345
Opened 2020-03-20 03:28 UTC by ajwerner

This PR comes in several commits. 

1) Unexport a number of internal state transitions from the `*jobs.Job` struct. 
2) Remove some debugging Printlns
3) Add an extension to `jobs.Resumer` to control behavior when a pause is requested
4) Use that extension to install a protected timestamp record when pausing a CHANGEFEED.

Release justification: bug fixes and low-risk updates to new functionality

2020-03-20 03:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46345)
<!-- Reviewable:end -->

2020-03-20 14:49 UTC, danhhz commented
I haven't reviewed this, but I'm worried about how counter intuitive it is. Changefeeds were designed from day 1 to impact live traffic as little as possible. With this change, a paused changefeed will cause old revisions to stick around for an unbounded amount of time, no? If so, that would potentially increase latencies and definitely will increase disk usage. This would be very surprising to me as a user.

I think we should consider putting this behind a WITH option or something to keep the default behavior we had before, but allow users to opt-in to this if they know what they're doing.

Also, even if we think this behavior change is exactly the right one as-is, calling it low-risk is quite a stretch.

2020-03-20 16:15 UTC, ajwerner commented
Making this behavior opt in should de-risk it both in terms of user expectation and in terms of likelihood to cause problems. Will update.

2020-03-23 18:21 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/helpers_test.go, line 63 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36lkJt-z-9WsnYW6g7:-M36lkJt-z-9WsnYW6g8:b-sny916) ([raw file](https://github.com/cockroachdb/cockroach/blob/776edfb32a25492b641eb77a913145c356677cec/pkg/jobs/helpers_test.go#L63)):*
> ```Go
> 
> func (d FakeResumer) OnPauseRequest(
> 	ctx context.Context, phs interface{}, txn *kv.Txn, details *jobspb.Progress,
> ```

use onPauseRequestFunc 
___
*[pkg/jobs/jobs_test.go, line 1021 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36j3hC0TGc-gu5VWZf:-M36j3hC0TGc-gu5VWZg:bs1csvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc3f9d9c3a271444d25ef637762316fefc92cc3a/pkg/jobs/jobs_test.go#L1021)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		if err := registry.Resume(ctx, nil, *job.ID()); err != nil {
> ```

this is here on purpose to test Resume is idempotent
___
*[pkg/jobs/jobs_test.go, line 1971 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36rvhE8D26lQYk0dpj:-M36rvhE8D26lQYk0dpk:bh4r35f) ([raw file](https://github.com/cockroachdb/cockroach/blob/776edfb32a25492b641eb77a913145c356677cec/pkg/jobs/jobs_test.go#L1971)):*
> ```Go
> // TestOnPauseRequest tests that job Resumers which implement PauseRequester
> // work correctly.
> func TestOnPauseRequest(t *testing.T) {
> ```

`type registryTestSuite struct` used in in this test file above has similar test setup logic and is used for all tests concerning the registry lifecycle, which this test belongs to as well logically. Can you look into refactoring this test to use it as well and fit it in `func TestRegistryLifecycle(t *testing.T)`.


<!-- Sent from Reviewable.io -->

2020-03-24 19:53 UTC, ajwerner reviewed
I've gone and gated the functionality behind a new changefeed option. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-:-M3D5LJQ0GZUAof9yDPs:b-bwexj9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/jobs/helpers_test.go, line 63 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36lkJt-z-9WsnYW6g7:-M37xukl74yKLtzf0JA5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/776edfb32a25492b641eb77a913145c356677cec/pkg/jobs/helpers_test.go#L63)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

use onPauseRequestFunc 
</blockquote></details>

Done.
___
*[pkg/jobs/jobs_test.go, line 1021 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36j3hC0TGc-gu5VWZf:-M37xxgp5EcGFCRKi3Jn:b-zbj234) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc3f9d9c3a271444d25ef637762316fefc92cc3a/pkg/jobs/jobs_test.go#L1021)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

this is here on purpose to test Resume is idempotent
</blockquote></details>

Noted, added back with a comment.
___
*[pkg/jobs/jobs_test.go, line 1971 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M36rvhE8D26lQYk0dpj:-M3D5K62C5cZpuLDELIb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/776edfb32a25492b641eb77a913145c356677cec/pkg/jobs/jobs_test.go#L1971)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

`type registryTestSuite struct` used in in this test file above has similar test setup logic and is used for all tests concerning the registry lifecycle, which this test belongs to as well logically. Can you look into refactoring this test to use it as well and fit it in `func TestRegistryLifecycle(t *testing.T)`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-25 23:01 UTC, spaskob approved these changes
> Reviewed 2 of 4 files at r4, 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/jobs_test.go, line 786 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M3IuxsQ-Tl_6YUWWxLZ:-M3IuxsQ-Tl_6YUWWxL_:bottiwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b47dfb6a0ea767daff7876e541782f3749f562e/pkg/jobs/jobs_test.go#L786)):*
> ```Go
> 		require.NoError(t, <-pauseErrCh)
> 		rts.check(t, jobs.StatusPaused)
> 		_ = *job.ID()
> ```

what are you trying to accomplish here?
___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts_test.go, line 62 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M3IvNv5CLT2L_Zr0MMb:-M3IvNv69oHb-v2hUJu1:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b47dfb6a0ea767daff7876e541782f3749f562e/pkg/jobs/jobsprotectedts/jobs_protected_ts_test.go#L62)):*
> ```Go
> 				Tables: []jobspb.SchemaChangeGCDetails_DroppedID{
> 					{
> 						ID:       42,
> ```

:)


<!-- Sent from Reviewable.io -->

2020-03-26 16:53 UTC, ajwerner reviewed
@danhhz this is now gated behind a new option with a perhaps overly verbose name. Feel free to give it a look. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-:-M3MkfHKAu5QJNT8CxNL:blnx6kg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/jobs_test.go, line 786 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46345#-M3IuxsQ-Tl_6YUWWxLZ:-M3Ix6RL6GczAvEyqzHo:b-x17vie) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b47dfb6a0ea767daff7876e541782f3749f562e/pkg/jobs/jobs_test.go#L786)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

what are you trying to accomplish here?
</blockquote></details>

whoops, thought I removed those. I was debugging something. removed. 


<!-- Sent from Reviewable.io -->

2020-03-27 20:44 UTC, ajwerner commented
bors r=spaskob

2020-03-27 22:23 UTC, merged