ui: Clean up recently-added css
cockroachdb/cockroach pull request #46492
Opened 2020-03-24 15:33 UTC by elkmaster

Moved all the new CSS that got added to shame.styl to components
Added Antd Pagination, Picker, Divider, Checkbox, Tabs components
refactored code
removed unused styles

Resolves: #46314

Release note (ui): none

2020-03-24 15:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46492)
<!-- Reviewable:end -->

2020-03-25 15:17 UTC, dhartunian requested changes
@elkmaster my apologies, I think I need to clarify the issue text: I wanted the *recent* changes moved out of `shame.styl`, not to eliminate it entirely.

Specifically, I was hoping the newer CSS we added starting from line 140 could be extracted out into more specific CSS files. Can we do this without creating new components?

I also can't merge this as-is because it moves around too many things before release. I know we want to do the component refactor but now is a difficult time to push on this. Since we're in the middle of acceptance testing already, it will be tough to verify that we don't have visual regressions.

> Reviewed 1 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46492#-:-M3HBVPE6rE594Ls-1Bt:bqonbwf)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-03-25 15:29 UTC, elkmaster commented
@dhartunian, hmm. to be honest I really don't see any need to have this shame.styl anymore. this approach have place long time ago in "before-css-modules" times. If this is to big change for now, let's just wait with merge before stab period is over. Is it makes sense for you?

2020-03-25 22:33 UTC, dhartunian commented
@elkmaster sound great! We can wait on this.

2020-06-02 14:03 UTC, closed without merging