colexec: fix interaction between projectingBatch and ArrowBatchConverter
cockroachdb/cockroach pull request #46543
Opened 2020-03-25 01:04 UTC by yuzefovich

Release justification: bug fixes and low-risk updates to new
functionality.

With our recent work, `simpleProjectOp` relies on creating a separate
`projectingBatch` for each "new" batch it sees (where "new" is tracked
by the pointer address). This works ok, but the interaction with
ArrowBatchConverter has been messed up - the converter `Reset`s the
batch which truncates its type schema. As a result, we end up in
a situation where `projectingBatch` that wraps the batch created in the
converter thinks that there are more columns than `MemBatch.b` actually
contains after the truncation which can lead to an internal error. This
problem is now fixed by introducing another variation of `Reset` method
(`ResetNoTruncation`) that doesn't truncate the schema. Only
ArrowBatchConverter is using this method.

Fixes: #46533.

Release note: None (this is a follow-up fix to a PR that has been merged
three weeks ago with a release note)

2020-03-25 01:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46543)
<!-- Reviewable:end -->

2020-03-25 10:02 UTC, asubiotto requested changes
Why does the batch passed in to the `ArrowBatchConverter` have a different schema than what the converter expects? Is this valid behavior?

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-:-M3G7DWy7v9txgJy8SC_:bul07ag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/batch.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-M3G7I4y0zjaRSHuzSwo:-M3G7I4y0zjaRSHuzSwp:b-4jefvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74cbfb23f6038d249db0ce5c94c59e6ae98fca9/pkg/col/coldata/batch.go#L61)):*
> ```Go
> 	// the batch will be reused (meaning this method does *not* truncate the
> 	// type schema).
> 	ResetNoTruncation(types []coltypes.T, length int)
> ```

Could we make this a package-level function instead if it's only used in one place?
___
*[pkg/sql/colexec/execplan.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-M3G7pC8AF3YTsSsTFDn:-M3G7pC9BPxqjZwqZYkf:b7m0mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74cbfb23f6038d249db0ce5c94c59e6ae98fca9/pkg/sql/colexec/execplan.go#L1047)):*
> ```Go
> 					// We want to project out temporary columns (which have indices in the
> 					// range [wf.OutputColIdx, wf.OutputColIdx+tempColOffset)).
> 					projection := make([]uint32, 0, wf.OutputColIdx+1)
> ```

Why is this change in this PR?


<!-- Sent from Reviewable.io -->

2020-03-25 18:37 UTC, yuzefovich reviewed
As discussed offline, probably `projectingBatch` abuses the semantics by storing the batch (that it doesn't own) without copying the vectors. However, at this point it is too late to change that, plus the performance implications of copying the data on every `simpleProjectOp` (which we assume to be very cheap) cannot be brushed aside.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-:-M3HrJyoDs6YYfZFaokv:b-1psytx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/batch.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-M3G7I4y0zjaRSHuzSwo:-M3HxBX26FPG9oB6THMa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74cbfb23f6038d249db0ce5c94c59e6ae98fca9/pkg/col/coldata/batch.go#L61)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we make this a package-level function instead if it's only used in one place?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-M3G7pC8AF3YTsSsTFDn:-M3HycRa4aeGpGVeqSbf:b-smv4yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d74cbfb23f6038d249db0ce5c94c59e6ae98fca9/pkg/sql/colexec/execplan.go#L1047)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this change in this PR?
</blockquote></details>

Just because I noticed it while debugging. It's not important though, removed.


<!-- Sent from Reviewable.io -->

2020-03-26 09:58 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46543#-:-M3LGlEd1dwj2c69i9mj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-03-26 15:41 UTC, yuzefovich commented
TFTR!

bors r+

2020-03-26 18:57 UTC, yuzefovich commented
bors r+

2020-03-26 19:51 UTC, merged