encoding: fix decimal decoding not reset properly
cockroachdb/cockroach pull request #46589
Opened 2020-03-25 21:30 UTC by Azhng

Previously, we did not properly reset apd.Decimal when we call
DecodeIntoNonsortingDecimal(). This results in incorrect decoded
results.

Closes #46523

Release justification: bug fix
Release note: None

2020-03-25 21:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46589)
<!-- Reviewable:end -->

2020-03-25 21:37 UTC, yuzefovich reviewed
Nice find!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-:-M3Ic6NGEvTVXIgNC-z-:bdkgtm2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/util/encoding/decimal_test.go, line 475 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3IbmkK374u1RuJmTX4:-M3IbmkK374u1RuJmTX5:b-jlehg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L475)):*
> ```Go
> }
> 
> func TestDecodeMultipleDecimalsIntoNonsortingDecimals(t *testing.T) {
> ```

nit: `s/IntoNonsortingDecimals/IntoNonsortingDecimal/g`.
___
*[pkg/util/encoding/decimal_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3Ib_o6Eyo-NUf10O2x:-M3Ib_o6Eyo-NUf10O2y:b-xhhdkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L477)):*
> ```Go
> func TestDecodeMultipleDecimalsIntoNonsortingDecimals(t *testing.T) {
> 	tcs := []struct {
> 		Value []string
> ```

super nit: seems unusual to have an exported field in an anonymous struct, so `s/Value/value/g`.
___
*[pkg/util/encoding/decimal_test.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3Ibw4221B4swmykWRE:-M3Ibw4221B4swmykWRF:bjouv93) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L480)):*
> ```Go
> 	}{
> 		{
> 			[]string{"1.0", "5.0", "7.0"},
> ```

Would be nice to see some NaNs and infinities in the test if possible.
___
*[pkg/util/encoding/decimal_test.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3IbN_TAP9gyma2hUjb:-M3IbN_TAP9gyma2hUjc:bbpmahb) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L503)):*
> ```Go
> 			}
> 			if actual.Cmp(expected) != 0 {
> 				t.Errorf("unexpected mismatch for %v. got %v", expected, &actual)
> ```

nit: `s/./,/g`.


<!-- Sent from Reviewable.io -->

2020-03-25 21:50 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/util/encoding/decimal_test.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3Ib_o6Eyo-NUf10O2x:-M3IdVI-0BZjfZc23lLq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L477)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: seems unusual to have an exported field in an anonymous struct, so `s/Value/value/g`.
</blockquote></details>

Done.
___
*[pkg/util/encoding/decimal_test.go, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3Ibw4221B4swmykWRE:-M3IfEZZCqbbg3UevMF2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c2862b45bc5b75aa87f255f5b36627a2b905d6/pkg/util/encoding/decimal_test.go#L480)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Would be nice to see some NaNs and infinities in the test if possible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-26 03:07 UTC, yuzefovich approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-:-M3JnnAv0vV_Bfm2fR5j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-03-26 09:54 UTC, asubiotto requested changes
Nice find! The issue we've observed is that the sign is not reset properly right? I'd be interested in seeing how this change affects performance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-:-M3LFiHS-3V6gaQ85TbE:bqigos9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/util/encoding/decimal.go, line 627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3LFPFL53f7HYgjGrKd:-M3LFPFL53f7HYgjGrKe:b-1c4en1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9076326e10e049de0dcf1194a0b6f361ccc6d7/pkg/util/encoding/decimal.go#L627)):*
> ```Go
> // on the passed-in *apd.Decimal instead of producing a new one.
> func DecodeIntoNonsortingDecimal(dec *apd.Decimal, buf []byte, tmp []byte) error {
> 	*dec = apd.Decimal{}
> ```

I think there might be an associated benchmark, could you run it and post the results here?


<!-- Sent from Reviewable.io -->

2020-03-26 15:32 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/util/encoding/decimal.go, line 627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-M3LFPFL53f7HYgjGrKd:-M3MTBXUC54FYN1DQGpo:bwk6u5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a9076326e10e049de0dcf1194a0b6f361ccc6d7/pkg/util/encoding/decimal.go#L627)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think there might be an associated benchmark, could you run it and post the results here?
</blockquote></details>

Looks like there is not much performance impact with this change 

```
name                        old time/op    new time/op    delta
EncodeDecimalSmall-24          352ns ± 0%     353ns ± 0%  +0.50%  (p=0.001 n=10+9)
DecodeDecimalSmall-24          512ns ± 1%     512ns ± 0%    ~     (p=0.765 n=10+8)
EncodeDecimalMedium-24         334ns ± 1%     335ns ± 0%  +0.39%  (p=0.020 n=10+10)
DecodeDecimalMedium-24         499ns ± 1%     501ns ± 1%  +0.30%  (p=0.018 n=10+10)
EncodeDecimalLarge-24          352ns ± 0%     353ns ± 0%    ~     (p=0.447 n=10+10)
DecodeDecimalLarge-24          514ns ± 0%     513ns ± 0%    ~     (p=0.627 n=10+10)
PeekLengthDecimal-24          53.8ns ± 1%    53.8ns ± 1%    ~     (p=0.958 n=10+10)
NonsortingEncodeDecimal-24    92.7ns ± 1%    88.5ns ± 1%  -4.59%  (p=0.000 n=10+10)
NonsortingDecodeDecimal-24    92.8ns ± 1%    92.9ns ± 1%    ~     (p=0.399 n=10+10)
EncodeDecimalValue-24         80.8ns ± 1%    77.6ns ± 0%  -3.90%  (p=0.000 n=9+10)
DecodeDecimalValue-24          105ns ±11%     101ns ± 0%    ~     (p=0.549 n=10+8)

name                        old alloc/op   new alloc/op   delta
EncodeDecimalSmall-24          29.0B ± 0%     29.0B ± 0%    ~     (all equal)
DecodeDecimalSmall-24          40.0B ± 0%     40.0B ± 0%    ~     (all equal)
EncodeDecimalMedium-24         29.0B ± 0%     29.0B ± 0%    ~     (all equal)
DecodeDecimalMedium-24         40.0B ± 0%     40.0B ± 0%    ~     (all equal)
EncodeDecimalLarge-24          29.0B ± 0%     29.0B ± 0%    ~     (all equal)
DecodeDecimalLarge-24          40.0B ± 0%     40.0B ± 0%    ~     (all equal)
PeekLengthDecimal-24           0.00B          0.00B         ~     (all equal)
NonsortingEncodeDecimal-24     0.00B          0.00B         ~     (all equal)
NonsortingDecodeDecimal-24     8.00B ± 0%     8.00B ± 0%    ~     (all equal)
EncodeDecimalValue-24          0.00B          0.00B         ~     (all equal)
DecodeDecimalValue-24          8.00B ± 0%     8.00B ± 0%    ~     (all equal)

name                        old allocs/op  new allocs/op  delta
EncodeDecimalSmall-24           2.00 ± 0%      2.00 ± 0%    ~     (all equal)
DecodeDecimalSmall-24           2.00 ± 0%      2.00 ± 0%    ~     (all equal)
EncodeDecimalMedium-24          2.00 ± 0%      2.00 ± 0%    ~     (all equal)
DecodeDecimalMedium-24          2.00 ± 0%      2.00 ± 0%    ~     (all equal)
EncodeDecimalLarge-24           2.00 ± 0%      2.00 ± 0%    ~     (all equal)
DecodeDecimalLarge-24           2.00 ± 0%      2.00 ± 0%    ~     (all equal)
PeekLengthDecimal-24            0.00           0.00         ~     (all equal)
NonsortingEncodeDecimal-24      0.00           0.00         ~     (all equal)
NonsortingDecodeDecimal-24      1.00 ± 0%      1.00 ± 0%    ~     (all equal)
EncodeDecimalValue-24           0.00           0.00         ~     (all equal)
DecodeDecimalValue-24           1.00 ± 0%      1.00 ± 0%    ~     (all equal)
```


<!-- Sent from Reviewable.io -->

2020-03-26 16:15 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46589#-:-M3Mc0OqDSMDCnuo5XPJ:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-03-26 16:15 UTC, Azhng commented
TFTR!

bors r+

2020-03-26 18:27 UTC, merged