storage/metamorphic: Set MaxKeys, TargetBytes, handle Open-time errors
cockroachdb/cockroach pull request #46814
Opened 2020-03-31 21:30 UTC by itsbilal

Sets the TargetBytes and MaxKeys options in MVCCScan to some resonable
non-zero defaults. Also sets the engine handle to nil if there's an
Open-time error, so we don't double-panic when the defer CloseAll
runs.

Release note: None.

2020-03-31 21:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/46814)
<!-- Reviewable:end -->

2020-03-31 23:04 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[pkg/storage/metamorphic/operations.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3mp-WCBy3fUbqeMkrj:-M3mp-WCBy3fUbqeMkrk:bdjsyh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d0eea5f69d19997467124e0f6148774034a2ef/pkg/storage/metamorphic/operations.go#L365)):*
> ```Go
> 		Txn:          txn,
> 		MaxKeys:      16,
> 		TargetBytes:  1 << 20,
> ```

I think these should be randomized in some fashion. I believe that implies adding fields to `mvccScanOp`. 
___
*[pkg/storage/metamorphic/operations.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3mpFQnBuqBdtH2sANR:-M3mpFQnBuqBdtH2sANS:bivzaqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d0eea5f69d19997467124e0f6148774034a2ef/pkg/storage/metamorphic/operations.go#L370)):*
> ```Go
> 		return fmt.Sprintf("error: %s", err)
> 	}
> 	return fmt.Sprintf("kvs = %v, intents = %v", result.KVs, result.Intents)
> ```

We should include `result.ResumeSpan` in the returned value. Perhaps also `result.NumKeys` and `result.NumBytes`. Any discrepancies between the RocksDB and Pebble MVCC implementations would be surprising.


<!-- Sent from Reviewable.io -->

2020-04-01 13:36 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[pkg/storage/metamorphic/operations.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3mp-WCBy3fUbqeMkrj:-M3px-o0CQu3glZFF8yQ:baqum51) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d0eea5f69d19997467124e0f6148774034a2ef/pkg/storage/metamorphic/operations.go#L365)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think these should be randomized in some fashion. I believe that implies adding fields to `mvccScanOp`. 
</blockquote></details>

Done. Added a float operand manager to generalize generation of values within ranges. 
___
*[pkg/storage/metamorphic/operations.go, line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3mpFQnBuqBdtH2sANR:-M3px4Vx4GJacx_JE8Y-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8d0eea5f69d19997467124e0f6148774034a2ef/pkg/storage/metamorphic/operations.go#L370)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

We should include `result.ResumeSpan` in the returned value. Perhaps also `result.NumKeys` and `result.NumBytes`. Any discrepancies between the RocksDB and Pebble MVCC implementations would be surprising.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-01 14:06 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/storage/metamorphic/operations.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q2NJ-4G7qrcp9776V:-M3q2NJ-4G7qrcp9776W:b-sesjyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L125)):*
> ```Go
> 		txn = txnID(args[2])
> 	}
> 	maxKeys := int64(m.floatGenerator.parse(args[3]) * 32)
> ```

I think when we specify `maxKeys`, we generally set a higher value than this. But perhaps this is a good value for the metamorphic test because it has less data.

I don't have a strong objection to using a float generator here, but I would have used an `intGenerator` since the parameters you're generating are both integers. Curious why you went with `floatGenerator`. Is it because the generator doesn't provides a means of specifying the range for the integers?
___
*[pkg/storage/metamorphic/operations.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q1mB85UjQSQaH4xtq:-M3q1mB85UjQSQaH4xtr:b3nfbr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L126)):*
> ```Go
> 	}
> 	maxKeys := int64(m.floatGenerator.parse(args[3]) * 32)
> 	targetBytes := int64(1 << int(m.floatGenerator.parse(args[4]) * 20))
> ```

I think this means that `targetBytes` will be in the range `[1,512k]`. Is the value 0 interesting? Rather than the powers-of-2, I think it would be useful to make any value in the range `[0,512k)` possible: `int64(m.floatGenerator.parse(args[4]))*(1 << 20)`.

What is the effect of setting both `maxKeys` and `targetBytes`? Is it useful to flip a coin to choose between:
1. Setting `maxKeys`
2. Setting `targetBytes`
3. Setting both fields


<!-- Sent from Reviewable.io -->

2020-04-01 14:56 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[pkg/storage/metamorphic/operations.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q2NJ-4G7qrcp9776V:-M3qC2Pr4GxNgszXn05p:b9et6iw) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L125)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think when we specify `maxKeys`, we generally set a higher value than this. But perhaps this is a good value for the metamorphic test because it has less data.

I don't have a strong objection to using a float generator here, but I would have used an `intGenerator` since the parameters you're generating are both integers. Curious why you went with `floatGenerator`. Is it because the generator doesn't provides a means of specifying the range for the integers?
</blockquote></details>

Yeah, we usually use higher values, but I wanted a higher likelihood of us actually hitting the maxKeys in this case. That's why I went with `[0,32)`.


And that's correct, the current abstraction doesn't allow for specifying arguments to the operand managers. Doing a `floatManager` is the easiest way in the current structure, although it has a slight negative impact on readability of the output files.
___
*[pkg/storage/metamorphic/operations.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q1mB85UjQSQaH4xtq:-M3qDfZI7FllJ3zOq8Sf:br999sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L126)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this means that `targetBytes` will be in the range `[1,512k]`. Is the value 0 interesting? Rather than the powers-of-2, I think it would be useful to make any value in the range `[0,512k)` possible: `int64(m.floatGenerator.parse(args[4]))*(1 << 20)`.

What is the effect of setting both `maxKeys` and `targetBytes`? Is it useful to flip a coin to choose between:
1. Setting `maxKeys`
2. Setting `targetBytes`
3. Setting both fields
</blockquote></details>

I think we should always be setting both fields. In many cases we won't hit either limit anyway (due to intents encountered, not enough data, etc) - so the higher likelihood that we can have of hitting any one of them, the more cases we're able to test.


<!-- Sent from Reviewable.io -->

2020-04-01 14:57 UTC, itsbilal commented
___
*[pkg/storage/metamorphic/operations.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q1mB85UjQSQaH4xtq:-M3qEhPYAQ0hnpgbZZBQ:bxjw5gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L126)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think we should always be setting both fields. In many cases we won't hit either limit anyway (due to intents encountered, not enough data, etc) - so the higher likelihood that we can have of hitting any one of them, the more cases we're able to test.
</blockquote></details>

Made the `1 << 20 * float` change. 


<!-- Sent from Reviewable.io -->

2020-04-01 15:06 UTC, petermattis requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-:-M3qGl5lE1z-SI13izbh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/storage/metamorphic/operations.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q2NJ-4G7qrcp9776V:-M3qGiQYBe0kJwCbVfOY:b4o4t18) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L125)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah, we usually use higher values, but I wanted a higher likelihood of us actually hitting the maxKeys in this case. That's why I went with `[0,32)`.


And that's correct, the current abstraction doesn't allow for specifying arguments to the operand managers. Doing a `floatManager` is the easiest way in the current structure, although it has a slight negative impact on readability of the output files.
</blockquote></details>

Ack. Ok.
___
*[pkg/storage/metamorphic/operations.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46814#-M3q1mB85UjQSQaH4xtq:-M3qFTxq7UVRen2lYt65:bn39f55) ([raw file](https://github.com/cockroachdb/cockroach/blob/670c977fda366c1443df0d190f5715835731374c/pkg/storage/metamorphic/operations.go#L126)):*
> I think we should always be setting both fields. In many cases we won't hit either limit anyway (due to intents encountered, not enough data, etc) - so the higher likelihood that we can have of hitting any one of them, the more cases we're able to test.

Agreed that in many cases we won't be hitting either limit. The purpose of only setting one of the fields it to ensure that we can randomly stumble upon scenarios where setting only one of the fields triggers bad behavior. I suspect a more proximate reason for always setting both fields is that only setting one is a bit irritating with the current infrastructure. This points to a bit of inflexibility in the high-level design: trying to generate the arguments for an operation independently. I don't think it is worth trying to fix at this time.


<!-- Sent from Reviewable.io -->

2020-04-01 15:42 UTC, itsbilal commented
Thanks for the review!

bors r+

2020-04-01 16:31 UTC, merged