sql: add support for CREATE OR REPLACE VIEW
cockroachdb/cockroach pull request #47051
Opened 2020-04-05 03:32 UTC by rohany

Fixes #24897.

This PR adds support for the CREATE OR REPLACE VIEW
command by allowing the create view statement to optionally
overwrite an existing descriptor, rather than always write
a new descriptor k/v entry.

Release note (sql change): This PR adds support for the
CREATE OR REPLACE VIEW command.

2020-04-05 03:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/47051)
<!-- Reviewable:end -->

2020-04-05 04:39 UTC, RaduBerinde reviewed
Cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-:-M47cafy-mMrsn0qWU1J:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @rohany)

___
*[pkg/sql/create_view.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47Q8VC7OwEYMzlyC0S:-M47Q8VC7OwEYMzlyC0T:b-7tmz2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L79)):*
> ```Go
> 	tKey, schemaID, err := getTableCreateParams(params, n.dbDesc.ID, isTemporary, viewName)
> 	if err != nil {
> 		if sqlbase.IsRelationAlreadyExistsError(err) {
> ```

[nit] we can invert this check and `return err` so the other logic isn't so nested
___
*[pkg/sql/create_view.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47Ptqm66fwSaAEHiOt:-M47Ptqm66fwSaAEHiOu:bu86vb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L82)):*
> ```Go
> 			if n.ifNotExists {
> 				return nil
> 			} else if n.replace {
> ```

[nit] no need for `else` after `return`. Actually this could all be a big switch with four branches, all of which end in `return`
___
*[pkg/sql/create_view.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47aYdjBKLz7cLwHzCw:-M47aYdjBKLz7cLwHzCx:b7eopyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L112)):*
> ```Go
> 
> 	var id sqlbase.ID
> 	if replacingDesc != nil {
> ```

[nit] this could be coalesced with the `if` below, it has the same branches
___
*[pkg/sql/create_view.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47bYXw6E2uDHNr3jYB:-M47bYXw6E2uDHNr3jYC:b-vqb7ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L139)):*
> ```Go
> 		oldDesc := &replacingDesc.ClusterVersion
> 
> 		// Compare replacingDesc against its ClusterVersion to verify if
> ```

[nit] This block is a good candidate for moving into a helper function to make this function easier to read through
___
*[pkg/sql/create_view.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47bH_S1-QpjisGP3L1:-M47bH_S1-QpjisGP3L2:bkudjfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L169)):*
> ```Go
> 		}
> 
> 		// Remove this view from all tables that depend on it.
> ```

this comment seems wrong, this is about tables that the existing view depends on no?
___
*[pkg/sql/create_view.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47bxi14bAffsanRXIo:-M47bxi14bAffsanRXIp:bdaxkk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L181)):*
> ```Go
> 			}
> 
> 			// Remove the back reference.
> ```

Is some of this code not the same with drop view code? (wondering if we can share anything)


<!-- Sent from Reviewable.io -->

2020-04-05 18:40 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/create_view.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47Ptqm66fwSaAEHiOt:-M4Acvqk16ISCjOcREBK:buimgm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L82)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] no need for `else` after `return`. Actually this could all be a big switch with four branches, all of which end in `return`
</blockquote></details>

oh thats clean -- i didn't realize you could switch on nothing.
___
*[pkg/sql/create_view.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47aYdjBKLz7cLwHzCw:-M4Aa_9Y-GlQCI1QhCkf:b-hj17oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L112)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this could be coalesced with the `if` below, it has the same branches
</blockquote></details>

it was actually unneeded.
___
*[pkg/sql/create_view.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47bH_S1-QpjisGP3L1:-M4Abulw1XR2QGNNL3nF:b-2uztsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L169)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this comment seems wrong, this is about tables that the existing view depends on no?
</blockquote></details>

Yup, this was backwards.
___
*[pkg/sql/create_view.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M47bxi14bAffsanRXIo:-M4AcXLABILgQlK6u1y-:b6xiudy) ([raw file](https://github.com/cockroachdb/cockroach/blob/02c77fd47175da3fc1c1435986c647b1e5bafb52/pkg/sql/create_view.go#L181)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is some of this code not the same with drop view code? (wondering if we can share anything)
</blockquote></details>

good call, was able to remove some duplication.


<!-- Sent from Reviewable.io -->

2020-04-06 11:59 UTC, knz reviewed
> Reviewed 7 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, @RaduBerinde, and @rohany)

___
*[pkg/sql/create_view.go, line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4ELnQH4P_VSSaPWFQU:-M4ELnQIE_ZNhigrPSRv:b-rmq6cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/574437d710ca32c736c78f09459a557f2cedd515/pkg/sql/create_view.go#L322)):*
> ```Go
> 	for i := range oldColumns {
> 		oldCol, newCol := &oldColumns[i], &newColumns[i]
> 		if oldCol.Name != newCol.Name {
> ```

I think you need to compare the visibility as well (hidden vs non-hidden). Otherwise the result of `*`-expansion can change.


<!-- Sent from Reviewable.io -->

2020-04-06 14:23 UTC, rohany commented
Is it possible for views to have hidden columns? It doesn't seem like it.

2020-04-06 17:02 UTC, knz commented
> Is it possible for views to have hidden columns? It doesn't seem like it.

If it becomes possible _tomorrow_, you don't want this code to start failing silently.

2020-04-06 17:11 UTC, rohany commented
valid point, updated.

2020-04-06 18:43 UTC, RaduBerinde commented
Since we are reusing the descriptor ID, is it guaranteed that the `Version` in the descriptor will change? That is necessary for plan caching to handle the change correctly (via [this](https://github.com/cockroachdb/cockroach/blob/f79144de22e54753982277c04504c8648188003e/pkg/sql/opt_catalog.go#L439
) code).

In any case, please add a test (in `logic_test/prepare`) where we have a view, we prepare a query using that view, we update the view, then execute the prepared query and verify that the results are consistent with the new view definition.

2020-04-06 19:18 UTC, rohany commented
> Since we are reusing the descriptor ID, is it guaranteed that the Version in the descriptor will change? That is necessary for plan caching to handle the change correctly (via this code).

Yeah, the version will be bumped. Added a test to verify this!

2020-04-06 19:48 UTC, RaduBerinde commented
Test looks great, thanks!

2020-04-10 01:40 UTC, rohany commented
Pinging for an "official" review action please!

2020-04-10 02:09 UTC, jordanlewis approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @lucy-zhang, @RaduBerinde, and @rohany)

___
*[pkg/sql/create_view.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq8vL7rF1AM7U8JK1:-M4Wq8vM0741xo9I14cN:b9yb2sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L91)):*
> ```Go
> 				return err
> 			}
> 			desc, err := params.p.Tables().getMutableTableVersionByID(params.ctx, id, params.p.txn)
> ```

Are there permissions we need to consider here? You shouldn't be allowed to edit a view you don't have write on, or something like that.
___
*[pkg/sql/create_view.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WmRdpAa16RiuUXZ2C:-M4WmRdq4xaQEZKXmywv:byb88g1) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L96)):*
> ```Go
> 			}
> 			if !desc.IsView() {
> 				return pgerror.Newf(pgcode.WrongObjectType, `"%s" is not a view`, viewName)
> ```

nit: You can use %q instead of "%s".
___
*[pkg/sql/create_view.go, line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WnCTQBHd7N9AxhIYz:-M4WnCTQBHd7N9AxhIZ-:bwg3zp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L115)):*
> ```Go
> 	var newDesc *sqlbase.MutableTableDescriptor
> 
> 	if replacingDesc != nil {
> ```

I would make this big block a function to make things a little cleaner, and add a comment. "replacingDesc != nil" doesn't really explain what's going on. 
___
*[pkg/sql/create_view.go, line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpsE_4f8SaTP8h8mz:-M4WpsE_4f8SaTP8h8n-:b-4tnwkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L147)):*
> ```Go
> 
> 			// Remove the back reference.
> 			desc.DependedOnBy = removeMatchingReferences(desc.DependedOnBy, replacingDesc.ID)
> ```

Doesn't this pointlessly drop and re-add the depend relationships if the view is edited but its dependencies not changed? This is the sort of thing that we're trying to cut down on with DDL performance improvements. They add up.
___
*[pkg/sql/create_view.go, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpMc30pn4VFC0hgKS:-M4WpMc30pn4VFC0hgKT:b-k117i) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L149)):*
> ```Go
> 			desc.DependedOnBy = removeMatchingReferences(desc.DependedOnBy, replacingDesc.ID)
> 			if err := params.p.writeSchemaChange(
> 				params.ctx, desc, sqlbase.InvalidMutationID, "updating view reference",
> ```

While you're here, can you make this job have a better name (and the one down below)? Just include the name of the view that is causing the update.
___
*[pkg/sql/create_view.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpShf1w7WqmNfaQtV:-M4WpShgAzGEOLnyayUI:b-3le7mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L222)):*
> ```Go
> 		// TODO (lucy): Have more consistent/informative names for dependent jobs.
> 		if err := params.p.writeSchemaChange(
> 			params.ctx, backRefMutable, sqlbase.InvalidMutationID, "updating view reference",
> ```

This one should also be updated.
___
*[pkg/sql/create_view.go, line 292 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq0JIDagHXmTmtQIi:-M4Wq0JIDagHXmTmtQIj:b-yewmlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L292)):*
> ```Go
> }
> 
> func addResultColumns(
> ```

Add a comment on this.
___
*[pkg/sql/create_view.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpbMI9KONA2n6Cb7x:-M4WpbMI9KONA2n6Cb7y:bxft8kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L339)):*
> ```Go
> 			)
> 		}
> 		if newCol.Hidden != oldCol.Hidden {
> ```

What about changing nullability? Or is that not an attribute for view columns?


<!-- Sent from Reviewable.io -->

2020-04-10 02:09 UTC, jordanlewis commented
Oops, I didn't mean to mark this as approved yet.

2020-04-10 02:10 UTC, jordanlewis requested changes
unapproved! sorry, haha

2020-04-10 02:56 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/create_view.go, line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4ELnQH4P_VSSaPWFQU:-M4Wv8g9EQZIhLyj2x1m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/574437d710ca32c736c78f09459a557f2cedd515/pkg/sql/create_view.go#L322)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you need to compare the visibility as well (hidden vs non-hidden). Otherwise the result of `*`-expansion can change.
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq8vL7rF1AM7U8JK1:-M4WsE4sDkg0jM8V2TUo:b6078yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L91)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Are there permissions we need to consider here? You shouldn't be allowed to edit a view you don't have write on, or something like that.
</blockquote></details>

Good catch, added.
___
*[pkg/sql/create_view.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WmRdpAa16RiuUXZ2C:-M4WsK6YD3l7aky2gAzO:b2nid0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L96)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: You can use %q instead of "%s".
</blockquote></details>

til
___
*[pkg/sql/create_view.go, line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WnCTQBHd7N9AxhIYz:-M4WuigM7FU990pg5XRo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L115)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would make this big block a function to make things a little cleaner, and add a comment. "replacingDesc != nil" doesn't really explain what's going on. 
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 147 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpsE_4f8SaTP8h8mz:-M4X-jKU7KXb_mK-iWlf:b-yttgoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L147)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Doesn't this pointlessly drop and re-add the depend relationships if the view is edited but its dependencies not changed? This is the sort of thing that we're trying to cut down on with DDL performance improvements. They add up.
</blockquote></details>

I thought this was going to be too tricky when first doing it but it turned out to be not bad. I've updated this to only do this write on tables that the new view doesn't reference anymore.
___
*[pkg/sql/create_view.go, line 149 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpMc30pn4VFC0hgKS:-M4WvKEJ0pwYA16TFrkD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L149)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

While you're here, can you make this job have a better name (and the one down below)? Just include the name of the view that is causing the update.
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpShf1w7WqmNfaQtV:-M4WvJNb1F6d-E6xIJoY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L222)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This one should also be updated.
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 292 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq0JIDagHXmTmtQIi:-M4Wv99QA2ADCXzXv9Fl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L292)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add a comment on this.
</blockquote></details>

Done.
___
*[pkg/sql/create_view.go, line 339 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4WpbMI9KONA2n6Cb7x:-M4X-dBc2JMF4ZaQhBzP:baoa1rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L339)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about changing nullability? Or is that not an attribute for view columns?
</blockquote></details>

Not sure, but theres no harm in adding a check for future proofing.


<!-- Sent from Reviewable.io -->

2020-04-10 13:12 UTC, knz commented
(I won't be reviewing this further)

2020-04-11 03:07 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> mod the permissions test!

Just thinking about other random edge cases... will anything go wrong if other views depended on the old view? I think no, because the view will keep its id and all of the columns it used to have, and select * isn't allowed in views.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-:-M4bAogg41Cxq5xs2THe:b-33o0oo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, @lucy-zhang, @RaduBerinde, and @rohany)

___
*[pkg/sql/create_view.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq8vL7rF1AM7U8JK1:-M4bAQro6oCVxi_8dkIM:bbdrzwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L91)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Good catch, added.
</blockquote></details>

Did you add a test?


<!-- Sent from Reviewable.io -->

2020-04-11 03:23 UTC, rohany reviewed
> Just thinking about other random edge cases... will anything go wrong if other views depended on the old view? I think no, because the view will keep its id and all of the columns it used to have, and select * isn't allowed in views.

Yeah, i think it will be ok. The checks we do (same column prefix) ensures that nothing goes wrong with the new view.

TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-:-M4bFaap72aGORE2LR3A:bgte7fk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @knz, @lucy-zhang, and @RaduBerinde)

___
*[pkg/sql/create_view.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47051#-M4Wq8vL7rF1AM7U8JK1:-M4bFYHG6Sri_z_q-Dwx:bbymfmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/180dc7750c97abf32209cce39194e828b410b23e/pkg/sql/create_view.go#L91)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Did you add a test?
</blockquote></details>

Gah sorry, added.


<!-- Sent from Reviewable.io -->

2020-04-11 15:12 UTC, rohany commented
bors r+

2020-04-11 16:48 UTC, merged