colexec: resolve miscellaneous TODOs and do some cleanups
cockroachdb/cockroach pull request #47309
Opened 2020-04-09 23:51 UTC by yuzefovich

**colexec: unify spacing in templates**

This commit removes the space after `{{` and before `}}` in templating
directives which unifies the code base (and brings it inline with the
godoc's examples use).

Release note: None

**colexec: minor refactor of merge joiner**

This commit does the following refactor of the merge joiner:
1. it bumps the "output batch size" for `count(*)` queries (when we
don't need to populate the output other than the number of tuples) to
max int. Previously this was limited due to `uint16` length of the
batch.
2. in the probe phase, when comparing tuples from both inputs to see
whether they match each other, previously we were using the combination
of `==` and `<` to make the decision which input to advance; now we will
be using `.Compare` equivalents. This allows us to simplify the template
generator a bit.
3. it removes extra spaces in the template directives.

Point number 2 shows some improvement (5% or so) in the benchmarks when
operating on ints, but it would matter more on Bytes and other
non-native types.

Release note: None

**colexec: miscellaneous cleanups**

This commit does the following:
1. plumbs the processor ID of the processor that we're wrapping into the
vectorized flow. This processor ID will be used for the materializer
/ columnarizer pair. I don't think it matters much, but why not.
2. resolves a minor TODO in the external sorter benchmark.
3. removes limitation of `2<<16-1` on K in the top K sorter (previously
limited by `uint16` batch length.
4. removes calling `Next` on the input of `zeroOperator` (which always
returns a zero batch). I believe previously it was needed so that
projecting operators had a chance to append their output columns to the
batch which is no longer the case.

Release note: None

2020-04-09 23:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/47309)
<!-- Reviewable:end -->

2020-04-21 22:25 UTC, yuzefovich commented
Friendly ping.

2020-04-25 23:53 UTC, yuzefovich commented
Friendly ping - this is a prerequisite to removing `coltypes.T` system.

2020-04-27 15:08 UTC, asubiotto requested changes
Wow, sorry I took so long to review this. The subject made it seem like the PR was not urgent.

> Reviewed 24 of 24 files at r1, 4 of 4 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-:-M5w7gpK9VXtRMPEUiDd:b5ca8qm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w8XCgCNnGdbbY5tAj:-M5w8XCh0j-a-L_Y4RF8:b-yygxfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad7703c1398458d92d74954854580cce4047e8bc/pkg/sql/colexec/mergejoiner_tmpl.go#L79)):*
> ```Go
> 
> // _ASSIGN_CMP is the template equality function for assigning the first input
> // to the result of comparison of the second input to the third input which
> ```

nit: `s/comparison of/comparing`
___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w8rETDLDk9iO6-cx7:-M5w8rETDLDk9iO6-cx8:b68ukst) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad7703c1398458d92d74954854580cce4047e8bc/pkg/sql/colexec/mergejoiner_tmpl.go#L249)):*
> ```Go
> 				} else { // mismatch
> 					// Switch the direction of increment if we're sorted descendingly.
> 					incrementLeft := cmp < 0 == (o.left.directions[eqColIdx] == execinfrapb.Ordering_Column_ASC)
> ```

nit: this `==` is awkward, can you use a `&&` instead?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 546 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w9eqB3LDLLh1GSUPB:-M5w9eqCDC1mxWbpGwjB:b-a2ro69) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a365d55110bb9562846368e33793cdefe9c9e4/pkg/sql/distsql/columnar_operators_test.go#L546)):*
> ```Go
> 									// will allow us to plan a zero operator which always returns a zero
> 									// batch. In such case, the spilling might not occur and that's ok.
> 									forcedDiskSpillMightNotOccur: !filter.Empty() || !onExpr.Empty(),
> ```

Do we need to add this field? Could we just set `forceDiskSpill` to the result of `spillForced && <your addition>`? 


<!-- Sent from Reviewable.io -->

2020-04-27 16:09 UTC, yuzefovich reviewed
No worries. The second commit modifies the mergejoiner code generation which is helpful in my WIP on removal of `coltypes.T`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-:-M5wODYn9E_LuKVLs1sS:b-gvcdq7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w8XCgCNnGdbbY5tAj:-M5wEZWZ9AD62l45mHsJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad7703c1398458d92d74954854580cce4047e8bc/pkg/sql/colexec/mergejoiner_tmpl.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/comparison of/comparing`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/mergejoiner_tmpl.go, line 249 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w8rETDLDk9iO6-cx7:-M5wLcBgBD26pqOlQssN:b-30tyj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad7703c1398458d92d74954854580cce4047e8bc/pkg/sql/colexec/mergejoiner_tmpl.go#L249)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: this `==` is awkward, can you use a `&&` instead?
</blockquote></details>

I added a clarifying comment.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 546 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-M5w9eqB3LDLLh1GSUPB:-M5wMKZ_0K88k83nc_1Q:bcww9cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/08a365d55110bb9562846368e33793cdefe9c9e4/pkg/sql/distsql/columnar_operators_test.go#L546)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we need to add this field? Could we just set `forceDiskSpill` to the result of `spillForced && <your addition>`? 
</blockquote></details>

I think two knobs have different semantics (with this PR in):
- `forceDiskSpill` means setting up memory limits so that disk spilling is very likely to occur.
- `forcedDiskSpillMightNotOccur` means not failing if the disk spilling didn't occur when we attempted to force it.

If we remove the latter knob and modifying the former, I think we would be losing some test coverage - namely, when we have non-empty `filter` or `onExpr` that are not "always false" we would be spilling to disk if `forceDiskSpill == true`, but we will not error out if the spilling doesn't occur (which it actually should).


<!-- Sent from Reviewable.io -->

2020-04-28 08:55 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 14 of 14 files at r4, 4 of 4 files at r5, 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47309#-:-M5zzrx6DM17v5kRK6oO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-04-28 17:05 UTC, yuzefovich commented
TFTR!

bors r+

2020-04-28 22:08 UTC, yuzefovich commented
bors r+

2020-04-28 23:14 UTC, merged