ui: application_name with forward slash breaks stmts page
cockroachdb/cockroach pull request #47423
Opened 2020-04-13 14:21 UTC by elkmaster

Replaced `application_name` if have any slashes for fix redirecting to `Statement Details` page.

Added test for encoding and decoding urlSlash

Resolves: #46592

Release note (ui): fix statements page crash on db names with /

2020-04-13 14:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/47423)
<!-- Reviewable:end -->

2020-04-14 14:56 UTC, dhartunian commented
@elkmaster This change appears too narrowly scoped, can we just urlencode the entire app name? What about a name with two slashes?

2020-04-30 14:19 UTC, elkmaster commented
@dhartunian, updated util to handle multi slash. Main problem only on routes level. We also have there `databaseNameAttr`, `statementAttr`, `nodeIDAttr`, `tableNameAttr`. Maybe we can proceed with this pr as hotfix, and than create ticket that will cover all cases?

2020-05-26 19:23 UTC, dhartunian commented
@elkmaster what I had in mind was using the browser API's `encodeURIComponent` function. Is there a reason it's not appropriate here?

2020-05-26 19:23 UTC, dhartunian requested changes
@elkmaster what I had in mind was using the browser API's encodeURIComponent function. Is there a reason it's not appropriate here?

2020-05-27 14:09 UTC, elkmaster commented
@dhartunian, no.

2020-06-10 18:41 UTC, dhartunian approved these changes

2020-06-12 17:08 UTC, dhartunian commented
bors r+

2020-06-12 18:56 UTC, merged