sql: fix renaming of columns involved in hash sharded indexes
cockroachdb/cockroach pull request #47431
Opened 2020-04-13 17:02 UTC by ajwerner

Prior to this commit, renames in hash sharded indexes were busted in a few
different ways.

1) The column references were using `UnresolvedName` when it should have been
   using `*tree.ColumnItem`. This was going on both in the check constaint and
   in the computed expr.

2) The `ShardedDescriptor` was not being updated to refer to the new name.

Another rough edge in all of this is that we're in deep trouble if we can't
tie the shard column back to the index[es] which are responsible for its
existence. Today this relationship is annoyingly tenuous. In an ideal world
we'd populate the ColumnDescriptor with information to mark it as a sharded
column and, ideally, the sharded descriptor. Furthermore, it's something of a
bummer that we have multiple of the same `ShardedDescriptor`s which each imply
a column but are denormalized into the `IndexDescriptor`.

Given we are where we are however, we really want to keep the name of the
shard column in sync with its source columns. This commit makes sure that
happens when member columns are renamed, the shard column is accordingly
renamed. The commit also disallows the renaming of a shard column as that
would upset the careful name synchronization.

It's worth noting that this is a little bit weird as other auto-generated
names don't change when the members change. For example an index created
with a name in the `CREATE TABLE` statement of a `FAMILY` clause.

Release note (bug fix): In earlier betas, columns which were members of
hash sharded indexes could not be renamed. Indexes created in prior
releases will need to be dropped and recreated to resolve this limitation.

2020-04-13 17:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/47431)
<!-- Reviewable:end -->

2020-04-14 16:09 UTC, rohany requested changes

2020-04-14 16:09 UTC, rohany commented on pkg/sql/alter_table.go
> +			descChanged, err := params.p.renameColumn(params.ctx, n.tableDesc, &t.Column, &t.NewName, false)
[nit]: comment the constant argument

2020-04-14 16:09 UTC, rohany commented on pkg/sql/create_table.go
> +							Expr: &tree.ColumnItem{ColumnName: tree.Name(colName)},
What changes when you make this a columnItem vs an unresolved name?

2020-04-14 16:09 UTC, rohany commented on pkg/sql/logictest/testdata/logic_test/hash_sharded_index
> +ALTER TABLE rename_column RENAME c2 TO c3;
Do you need to insert/select from this table to ensure that everything works, or is just doing the rename enough?

2020-04-14 16:09 UTC, rohany commented on pkg/sql/rename_column.go
> +	descChanged, err := params.p.renameColumn(params.ctx, tableDesc, &n.n.Name, &n.n.NewName, false)
^ missing arg comment

2020-04-14 16:09 UTC, rohany commented on pkg/sql/rename_column.go
> +// renameColumn will rename the
unfinished comment

2020-04-14 16:09 UTC, rohany commented on pkg/sql/sqlbase/structured.go
> +				return fmt.Errorf("index %q refers to non-existent shard column %q",
should this be a pgerror?

2020-04-14 18:32 UTC, ajwerner reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/alter_table.go, line 732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDG-r1-732:-M4tkk2b8rL4JaXHgnID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/alter_table.go#L732)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

[nit]: comment the constant argument
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 2012 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDH-r1-2012:-M4tkkn78Bx91m8d02A3:b-r5zwts) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/create_table.go#L2012)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

What changes when you make this a columnItem vs an unresolved name?
</blockquote></details>

Nothing, just seems more correct. 
___
*[pkg/sql/rename_column.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNg-r1-63:-M4tozjJ1JjWqAPjRegH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/rename_column.go#L63)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

^ missing arg comment
</blockquote></details>

Done.
___
*[pkg/sql/rename_column.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNg-r1-80:-M4tp9R76Ij2A9O0WVUo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/rename_column.go#L80)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

unfinished comment
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tpA2l7dzwZa8VCZCN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Do you need to insert/select from this table to ensure that everything works, or is just doing the rename enough?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNh-r1-2036:-M4tq99W2bjXG4WS5Aqp:bnxfk2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/sqlbase/structured.go#L2036)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

should this be a pgerror?
</blockquote></details>

heh I typed it that way at first. The testing infra in structured_test.go got in my way. I could move it back. I've sort of changed my mindset  that we should keep these errors as non-specific errors but do validation before we ever hit any of them. Ideally we'd get to the point where any failure under validation here is an assertion failure. At least I'm going with that until I get proven wrong. See my comment here:

https://github.com/cockroachdb/cockroach/issues/47430#issuecomment-613023139


<!-- Sent from Reviewable.io -->

2020-04-14 18:36 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tyGvV70BX41mCdzlA:b-s24yhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry my other comment here didn't publish -- i think you should also do a show create statement test to check that the shard column got renamed appropriately
___
*[pkg/sql/sqlbase/structured.go, line 2036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZlpSm60qJLesNh-r1-2036:-M4tyScmC2Ao68WGdreY:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/sqlbase/structured.go#L2036)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

heh I typed it that way at first. The testing infra in structured_test.go got in my way. I could move it back. I've sort of changed my mindset  that we should keep these errors as non-specific errors but do validation before we ever hit any of them. Ideally we'd get to the point where any failure under validation here is an assertion failure. At least I'm going with that until I get proven wrong. See my comment here:

https://github.com/cockroachdb/cockroach/issues/47430#issuecomment-613023139
</blockquote></details>

Makes sense!


<!-- Sent from Reviewable.io -->

2020-04-14 18:37 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4tyecz9wGtmgSZP2zB:b4eh23m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Sorry my other comment here didn't publish -- i think you should also do a show create statement test to check that the shard column got renamed appropriately
</blockquote></details>

Ha I had several and then realized they were getting mucked up because of the column family randomization and deleted them. I'll add them back with explicit column families. 


<!-- Sent from Reviewable.io -->

2020-04-14 18:57 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 500 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-M4oUWZkujb8FUBPboDI-r1-500:-M4u2R2I512EmFl_Jh9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a64fa4e63c7f29cb3d371ae2c66a6ff64e4b71be/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L500)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Ha I had several and then realized they were getting mucked up because of the column family randomization and deleted them. I'll add them back with explicit column families. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-14 19:00 UTC, rohany approved these changes

2020-04-14 19:56 UTC, ajwerner reviewed
bors r=rohany

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-:-M4uFswG0tRM8ZKAxlaG:bxeqqbd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)



<!-- Sent from Reviewable.io -->

2020-04-14 19:56 UTC, ajwerner reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47431#-:-M4uFwZE5fvRgy_6Tntn:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rohany)



<!-- Sent from Reviewable.io -->

2020-04-14 21:22 UTC, merged