sql: start index drop job for primary key changes immediately
cockroachdb/cockroach pull request #47624
Opened 2020-04-17 20:06 UTC by lucy-zhang

Release note (performance improvement): The cleanup job which runs after
a primary key change to remove old indexes, which blocks other schema
changes from running, now starts immediately after the primary key swap
is complete instead of being subject to a waiting period before being
run.

2020-04-17 20:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/47624)
<!-- Reviewable:end -->

2020-04-17 20:28 UTC, rohany commented
I think the alter column set data type implementation will want something similar to this too

2020-04-18 03:22 UTC, lucy-zhang commented
FWIW, on my laptop, `TestMultiplePrimaryKeyChanges` takes about 1m to run on master _without_ `setTestJobsAdoptInterval`, and 30s to run after this change. (It takes about 1s to run with `setTestJobsAdoptInterval`.) The remaining delay is due to retries from schema change jobs not being first in line.

2020-04-18 19:25 UTC, rohany requested changes

2020-04-18 19:25 UTC, rohany commented on pkg/sql/schema_changer_test.go
> +	testutils.SucceedsSoon(t, func() error {
Was the PrimaryKeyChangeWithOperations flaky now (the old indexes got cleaned up too fast?)

2020-04-18 19:25 UTC, rohany commented on pkg/sql/schema_changer_test.go
> +func TestPrimaryKeyDropIndexNotCancelable(t *testing.T) {
Does the job finish now in the logic test so we have to move it here?

2020-04-18 19:25 UTC, rohany commented on pkg/sql/schema_changer.go
> +		pkChangeIndexDropJob = nil
Can we change this to a slice like "childJobs" or something so that it is easy to add new jobs to start immediately?

2020-04-18 19:26 UTC, rohany commented
Thanks for getting to this lucy!

2020-04-21 14:41 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Seems sane to me. I'll let @rohany sign off. 

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-:-M5SArq751Em9wVRK1_q:b-7aw4rs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/schema_changer.go, line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-M58jwLcrNidFQQ5Bhks-r1-786:-M5SAHnd5UNDZJ6BaQnD:b73s17e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96d9d7da594587cf7b49a47c352fd745da350b/pkg/sql/schema_changer.go#L786)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Can we change this to a slice like "childJobs" or something so that it is easy to add new jobs to start immediately?
</blockquote></details>

Seems like a reasonable idea to me


<!-- Sent from Reviewable.io -->

2020-04-21 17:59 UTC, thoszhang reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47624)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany)

___
*[pkg/sql/schema_changer.go, line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-M58jwLcrNidFQQ5Bhks-r1-786:-M5Ssya2-myDKQYFdkSv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96d9d7da594587cf7b49a47c352fd745da350b/pkg/sql/schema_changer.go#L786)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Seems like a reasonable idea to me
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-M5AHgLM6XGrMGTQTdfW-r1-411:-M5Ied6X07_4xklo0siC:b-n2jhi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96d9d7da594587cf7b49a47c352fd745da350b/pkg/sql/schema_changer_test.go#L411)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Was the PrimaryKeyChangeWithOperations flaky now (the old indexes got cleaned up too fast?)
</blockquote></details>

Yeah, but the problem wasn't the indexes being GC'ed too quickly per se, since the test previously had the default GC TTL set for the table. Without setting the GC TTL to a low value, I kept getting a value that was lower than 2 times the number of rows in the table but that didn't decrease over time. I think what's going on is that some writes to the table are now happening after the index starts being dropped, so the dropped non-public index doesn't necessarily have the expected KV count. Does that seem plausible to you?
___
*[pkg/sql/schema_changer_test.go, line 3006 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-M5AHgLM6XGrMGTQTdfW-r1-3006:-M5IebY8ASloDfE4TfsZ:bs7q45j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96d9d7da594587cf7b49a47c352fd745da350b/pkg/sql/schema_changer_test.go#L3006)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Does the job finish now in the logic test so we have to move it here?
</blockquote></details>

Yeah, that's why.


<!-- Sent from Reviewable.io -->

2020-04-21 18:29 UTC, rohany approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47624)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @lucy-zhang)

___
*[pkg/sql/schema_changer_test.go, line 411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47624#-M5AHgLM6XGrMGTQTdfW-r1-411:-M5SzqVU9T4q02rt-nKp:buk13hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc96d9d7da594587cf7b49a47c352fd745da350b/pkg/sql/schema_changer_test.go#L411)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, but the problem wasn't the indexes being GC'ed too quickly per se, since the test previously had the default GC TTL set for the table. Without setting the GC TTL to a low value, I kept getting a value that was lower than 2 times the number of rows in the table but that didn't decrease over time. I think what's going on is that some writes to the table are now happening after the index starts being dropped, so the dropped non-public index doesn't necessarily have the expected KV count. Does that seem plausible to you?
</blockquote></details>

Yes, i think that makes sense. The test originally had a multiple of 2 (one multiple for the new primary key and one for the old key). Changing the multiple to 1 and having the gc trigger immediately seems correct.


<!-- Sent from Reviewable.io -->

2020-04-21 18:31 UTC, lucy-zhang commented
TFTRs

bors r+

2020-04-21 18:34 UTC, lucy-zhang commented
(hopefully the infra flake is gone)

2020-04-22 02:48 UTC, lucy-zhang commented
bors r+

2020-04-22 03:36 UTC, merged

2020-04-22 03:43 UTC, rohany commented
I'm wondering, is this something that is backportable to a point release of 20.1?

2020-04-22 03:46 UTC, lucy-zhang commented
Yeah, I opened a backport PR #47818 (though I figured it wasn't worth getting reviews until we actually start merging to the release branch for 20.1.1, which I believe we're not doing right now).