kvserver: don't track closed timestamp for epoch-based leases
cockroachdb/cockroach pull request #48521
Opened 2020-05-07 02:48 UTC by ajwerner

Epoch-based leases are a requirement for the closed-timestamp
subsystem. Closed timestamp records only make sense in the context
of node-liveness epochs. Expiration-based leases have a maxClosed()
value equal to their lease start time. This genearlly means that
until the oldest expiration-based lease on a node changes, the
closed timestamp lag on that node will grow.

Release note (bug fix): Fixed bug which falsly indicated that
`kv.closed_timestamp.max_behind_nanos` was almost always growing.

2020-05-07 02:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/48521)
<!-- Reviewable:end -->

2020-05-07 15:27 UTC, ajwerner commented
needs a test -- @andreimatei can you let me know if the extra return arg offends and you'd prefer I just check on the lease in metrics code?

2020-05-08 14:58 UTC, andreimatei reviewed
Well, that return value seems a bit hard to explain. What would you say about returning an error from `maxClosed()` for expiration-based ranges? Or otherwise calling the returned bool `ok` and return it pared with a zero timestamp.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-:-M6omHEG-mON4IX5ynMr:bru3erw)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-05-11 15:43 UTC, ajwerner reviewed
> Well, that return value seems a bit hard to explain. What would you say about returning an error from maxClosed() for expiration-based ranges? Or otherwise calling the returned bool ok and return it pared with a zero timestamp.

Done.

I added a test, PTAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-:-M73On-GBKssj_jETSla:b-qrgtfv)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-05-11 18:37 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/client_metrics_test.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M74-VFf3z0zhee5GYKK:-M74-VFf3z0zhee5GYKL:b-t05fnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/client_metrics_test.go#L344)):*
> ```Go
> // TestStoreMaxBehindNanosOnlyTracksEpochBasedLeases ensures that the metric
> // ClosedTimestampMaxBehindNanos does not follow the start time of expiration
> // based leases.
> ```

spell out that expiration-based ranges don't publish closed timestamps
___
*[pkg/kv/kvserver/client_metrics_test.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M740nPy7Y4LmW_Zq_j8:-M740nPy7Y4LmW_Zq_j9:b730uau) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/client_metrics_test.go#L387)):*
> ```Go
> 			require.NoError(t, s.ComputeMetrics(ctx, 0))
> 			maxBehind := time.Duration(s.Metrics().ClosedTimestampMaxBehindNanos.Value())
> 			const behindMultiple = 5 // ensure the max behind value is much larger
> ```

isn't it the other way - we're ensuring that `maxBehind` is much smaller than behind
___
*[pkg/kv/kvserver/helpers_test.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73zzn_5Y2BUlqgPI8q:-M73zzn_5Y2BUlqgPI8r:be358be) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/helpers_test.go#L279)):*
> ```Go
> 
> // MaxClosed returns the maximum closed timestamp known to the Replica.
> func (r *Replica) MaxClosed(ctx context.Context) hlc.Timestamp {
> ```

I'd add the extra return value here too. Without looking at how this method is used, it seems to me that, for the public version, it's even more important to make callers aware of the funkiness.
___
*[pkg/kv/kvserver/replica_follower_read.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73yOW70CoG21MGmgpS:-M73yOW70CoG21MGmgpT:btoxwlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/replica_follower_read.go#L110)):*
> ```Go
> // The ok return value indicates that the replica uses an epoch-based lease.
> // The timestamp returned from this method are valid as a maxClosed timestamp
> // for expiration based leases, however, those timestamps do not move with the
> ```

can you spell out that, for expiration-based ranges, the timestamp is the lease start time?
I'd still prefer we returned 0 for them, which would keep everybody away for using this method for such ranges (and then we wouldn't need to explain much)
___
*[pkg/kv/kvserver/store_split.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73zHts3MuzG4YMhwp5:-M73zHts3MuzG4YMhwp6:b-xfbzv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/store_split.go#L154)):*
> ```Go
> 	if initialMaxClosed, ok := r.maxClosed(ctx); ok {
> 		rightRepl.mu.Lock()
> 		rightRepl.mu.initialMaxClosed = initialMaxClosed
> ```

Why don't we mechanically copy `initialMaxClosed` any more?
By not doing it, it means that the closed ts for the rhs will regress after a split?
My preference would be to copy it mechanically, but at the same time keep `initialMaxClosed` to 0 for expiration-based ranges.


<!-- Sent from Reviewable.io -->

2020-05-11 19:02 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/client_metrics_test.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M74-VFf3z0zhee5GYKK:-M744MGWAAI1WF_IWvTO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/client_metrics_test.go#L344)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

spell out that expiration-based ranges don't publish closed timestamps
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_metrics_test.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M740nPy7Y4LmW_Zq_j8:-M744OKq0nrMO7gLmVO6:b-alkrlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/client_metrics_test.go#L387)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

isn't it the other way - we're ensuring that `maxBehind` is much smaller than behind
</blockquote></details>

right right, I meant to say `behind value`, improved the variable naming and commentary.
___
*[pkg/kv/kvserver/helpers_test.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73zzn_5Y2BUlqgPI8q:-M744kVb-3HhC7Zfabcq:b-1j4a86) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/helpers_test.go#L279)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd add the extra return value here too. Without looking at how this method is used, it seems to me that, for the public version, it's even more important to make callers aware of the funkiness.
</blockquote></details>

It's only public to tests (note `helpers_test.go`) but sure, done.
___
*[pkg/kv/kvserver/replica_follower_read.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73yOW70CoG21MGmgpS:-M745CfL9kI6oGqfHl2C:br2f38f) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/replica_follower_read.go#L110)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you spell out that, for expiration-based ranges, the timestamp is the lease start time?
I'd still prefer we returned 0 for them, which would keep everybody away for using this method for such ranges (and then we wouldn't need to explain much)
</blockquote></details>

Okay, done.
___
*[pkg/kv/kvserver/store_split.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-M73zHts3MuzG4YMhwp5:-M745X9w3yMjqoj2mA0V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf4c70b89310ceb98bd929f45529c69c0d163e32/pkg/kv/kvserver/store_split.go#L154)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Why don't we mechanically copy `initialMaxClosed` any more?
By not doing it, it means that the closed ts for the rhs will regress after a split?
My preference would be to copy it mechanically, but at the same time keep `initialMaxClosed` to 0 for expiration-based ranges.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-11 19:13 UTC, andreimatei reviewed
danke 

LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48521#-:-M74922k6Dv4c58HuvhV:buph5vy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)



<!-- Sent from Reviewable.io -->

2020-05-11 19:56 UTC, ajwerner commented
bors r=andreimatei

2020-05-11 21:14 UTC, merged