sql: unify "will distribute" check
cockroachdb/cockroach pull request #48851
Opened 2020-05-14 03:56 UTC by yuzefovich

This commit makes everyone who cares about whether a plan will be
distributed use the same `willDistributePlan` function. It also removes
the receiver from the utility methods `checkSupportForNode` and
`checkExpr` that verify whether DistSQL engine supports certain things
as a preliminary step to making the distribution decision in
execbuilder. Additionally, it updates a few comments.

Release note: None

2020-05-14 03:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/48851)
<!-- Reviewable:end -->

2020-05-14 14:17 UTC, asubiotto requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48851#-M7IWyzT6JdABhYR0RD7:-M7IWyzT6JdABhYR0RD8:bjbxkyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b2f299b13158206c5d3e444ece0c42c4938418/pkg/sql/exec_util.go#L837)):*
> ```Go
> 	plan planNode,
> ) bool {
> 	if _, noMultiTenancy := nodeID.OptionalNodeID(); noMultiTenancy {
> ```

I think this check should be `!noMultitenancy` since this returns true if the node ID is exposed (i.e. in a single-tenant environment).  We should probably rename the boolean to `singleTenant` (or something else to avoid the double negative) so `!singleTenant` makes more sense.


<!-- Sent from Reviewable.io -->

2020-05-14 17:31 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/exec_util.go, line 837 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48851#-M7IWyzT6JdABhYR0RD7:-M7Iu0ZZ0-odMVUY8LFQ:bt7gas0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9b2f299b13158206c5d3e444ece0c42c4938418/pkg/sql/exec_util.go#L837)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this check should be `!noMultitenancy` since this returns true if the node ID is exposed (i.e. in a single-tenant environment).  We should probably rename the boolean to `singleTenant` (or something else to avoid the double negative) so `!singleTenant` makes more sense.
</blockquote></details>

Yeah, this was a mistake during the refactor, fixed.


<!-- Sent from Reviewable.io -->

2020-05-14 17:34 UTC, yuzefovich commented
Unfortunately, we have a special case behavior for EXPLAIN variants, so this PR doesn't "truly" unify the check, but I think it's still useful to merge it.

2020-05-18 15:09 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48851#-:-M7cK8P2AYW06QUg9Jqq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)



<!-- Sent from Reviewable.io -->

2020-05-18 15:29 UTC, yuzefovich commented
TFTR!

bors r+

2020-05-18 16:22 UTC, merged