sql/pgwire: Make it possible to send out-of-band noticies immediately.
cockroachdb/cockroach pull request #49190
Opened 2020-05-18 13:40 UTC by miretskiy

Improves out-of-band notice sending mechanism to make it possible
to send and flush notices before command completes.

Some commands, such as IMPORT run for very long time.  This change
makes it possible to notify user about important events.
For example, IMPORT statement will display a warning if the user
attempts to import files that are too large.  Importing very large
files often leads to poor user experience (and slow imports).
The notification message tells the user about that and suggests
for ways to improve performance.

Release notes (enhancement): IMPORT statement now warns the user
if we attempt to import very large files.  Improrting large files
often results in suboptimal performand and poor user experience,
where for long periods of time the user has no idea if the job is
making progress.  We now show a warning message if we import
large files, and recommend good mitigation strategies.

2020-05-18 13:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49190)
<!-- Reviewable:end -->

2020-05-18 14:05 UTC, pbardea reviewed
This is really cool! I'm excited about what this could do - in particular your idea about linking to an IMPORT perf docs/best practices page once we have one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M7c5L_l7aG9GBUiRfCE:blhmibm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1MOk2NfS3CTyXwqd:-M7c1MOk2NfS3CTyXwqe:bbm85sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L696)):*
> ```Go
> 
> 		if err := warnIfImportFileTooLarge(
> 			ctx, files, p.ExecCfg().DistSQLSrv.ExternalStorageFromURI, 6); err != nil {
> ```

Looks like the file size here was for testing - but we'll probably want to pull it out into a `const`.
___
*[pkg/ccl/importccl/import_stmt.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1UpG0EajSebdtxHD:-M7c1UpG0EajSebdtxHE:b-6yt47e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L789)):*
> ```Go
> 		}
> 		if sz > maxSize {
> 			return pgerror.New(pgcode.Warning, "Yo files 2 large, man!")
> ```

We'll probably also want to re-work the wording here :)
___
*[pkg/sql/notice.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c2FJT9XmsUUqduCBR:-M7c2FJT9XmsUUqduCBS:b-co01nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L39)):*
> ```Go
> // SendClientNotice implements the tree.ClientNoticeSender interface.
> func (p *planner) SendClientNotice(ctx context.Context, err error) {
> 	p.sendClientNoticeInternal(ctx, false, err)
> ```

nit: I think adding: `p.sendClientNoticeInternal(ctx, false /* flush */, err)` would be helpful here. (Same for the other call to `sendClientNoticeInternal`.)
___
*[pkg/sql/notice.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1s6e3F1dD0_2pLsQ:-M7c1s6f7UenvNWCFrCC:bpbivcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L67)):*
> ```Go
> 	if flush {
> 		if err := p.noticeSender.SendNotice(ctx, err); err != nil {
> 			log.Errorf(ctx, "error sending notice: %v", err)
> ```

nit: I think using the `%+v` directive provides [a bit more info which may be useful for debugging](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#details-for-troubleshooting). This also applies to the logs in `warnIfImportFileTooLarge`.


<!-- Sent from Reviewable.io -->

2020-05-18 15:42 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1MOk2NfS3CTyXwqd:-M7cRmHq3Y19nWQ65n0D:bjt9vcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L696)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Looks like the file size here was for testing - but we'll probably want to pull it out into a `const`.
</blockquote></details>

Yup.. Just testing
___
*[pkg/ccl/importccl/import_stmt.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1UpG0EajSebdtxHD:-M7cRdak5ehAGGtIBmAy:b4d9jq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L789)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

We'll probably also want to re-work the wording here :)
</blockquote></details>

Ya thank? ;) This was just a POC.


<!-- Sent from Reviewable.io -->

2020-05-20 09:57 UTC, knz commented
As discussed elsewhere: there's a reason why notices and errors are delayed until statement completion. You need to investigate that reason, then explain in the commit message what the reason was, and what you did about it.

"It appears to work" is likely due to incomplete testing in this area of the code.

My guess, as your code stands now, is that if a statement that sends an early notice is retried internally by the SQL executor, the notice will be sent twice (actually, as many times as there are retries). At the very least you'll need to disable the retry mechanism as soon as an early notice has been sent.

There may be other problems due to the missing synchronization between (early) client messages and the incoming statement buffer.

Maybe @andreimatei could refresh our collective memory of why the client response is delayed, and recommend directions to investigate to determine the minimum bookkeeping required to make your code correct.

2020-05-20 14:20 UTC, miretskiy commented
Thanks @knz -- I do plan on investigating this further this coming friday.

2020-05-20 15:10 UTC, andreimatei requested changes
Flushing the connection closes the door to automatic retries. Whether that's OK in this case, I don't know.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M7mc54X8YKtvOIsYU6T:bob724d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mWTmf3c9ZO0RH6zT4:-M7mWTmf3c9ZO0RH6zT5:bf5eexo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L765)):*
> ```Go
> }
> 
> func warnIfImportFileTooLarge(
> ```

This seems like a very weird interface to me. This function returns an error in case a notice is needed, but swallows all other errors. At the very least the name seems wrong (the function doesn't take any action) and it needs a comment. But I think it'd be a lot better if the `SendClientNoticeImmediately()` call was moved in this function, and no error was returned.

It also seems weird to me that the `SendClientNotice*()` functions take generic errors instead of something more specific, but I guess that's not on you.
___
*[pkg/ccl/importccl/import_stmt.go, line 774 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mbROV9noEKyTPyAeb:-M7mbROV9noEKyTPyAec:bl9jka3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L774)):*
> ```Go
> 		store, err := fileFactory(ctx, files[i])
> 		if err != nil {
> 			log.Errorf(ctx, "error opening external file: %v", err)
> ```

Do we really want to swallow these errors? The files we're dealing with here I assume will be used for the import - so won't the import fail anyway? If so, let's just return them and stop the import early. Or is the rest of the import more resilient somehow?

If we leave the log statements, I think it'd be good for them to have a hint that it's an import logging the message, and also that the error is fairly benign (since we swallow it). And so then the `Errorf()` level doesn't seem appropriate, I guess.
___
*[pkg/ccl/importccl/import_stmt.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7maGfz8L5dDUftLcof:-M7maGfz8L5dDUftLcog:b-rmdx94) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L778)):*
> ```Go
> 		}
> 
> 		sz, err := store.Size(ctx, "")
> ```

s/""/"" /* baseName */

I think it'd help if you renamed `store` above to `file`, since, as far as I understand, calling the factory with the path to a file actually gives you something like a file, not something like a store. Otherwise this call to `Size()` here lets the reader wonder whose size is being checked. FWIW I find the `ExternalStorageFromURIFactory` interface weird in this respect.
___
*[pkg/sql/conn_io.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mX_w74z7QJHhoyrfg:-M7mX_w74z7QJHhoyrfh:b-874wos) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/conn_io.go#L884)):*
> ```Go
> // AppendNotice is part of the RestrictedCommandResult interface.
> func (r *bufferedCommandResult) AppendNotice(noticeErr error) {
> 	panic("unimplemented")
> ```

why panic (here and below)? Just make them no-ops; there's no interface for getting notices out of a `bufferedCommandResult`, so dropping them on the floor seems just fine.
___
*[pkg/sql/notice.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mZIsb81ZHmVi8WE4n:-M7mZIsb81ZHmVi8WE4o:b-vb0u4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L47)):*
> ```Go
> }
> 
> func (p *planner) sendClientNoticeInternal(ctx context.Context, flush bool, err error) {
> ```

Please turn this bool into an enum so you don't have to comment all the callsites. The style guide encourages this too. It can be a bool one like 
```
type flushOpt bool
const (
flush flushOpt = true
dontFlush = false
)
```
___
*[pkg/sql/notice.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mZxLL9M6LslQG02u3:-M7mZxLL9M6LslQG02u4:b2mhmng) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L67)):*
> ```Go
> 	if flush {
> 		if err := p.noticeSender.SendNotice(ctx, err); err != nil {
> 			log.Errorf(ctx, "error sending notice: %v", err)
> ```

I don't think you want to swallow this error, do you? Errors from this `SendNotice()` I think mean that the client connection dropped. Let's propagate this error up to stop the query.
___
*[pkg/sql/pgwire/command_result.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mYXqb6iHHZPs087rp:-M7mYXqb6iHHZPs087rq:bgto67u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/pgwire/command_result.go#L207)):*
> ```Go
> // AppendNotice is part of the CommandResult interface.
> func (r *commandResult) AppendNotice(noticeErr error) {
> 	r.flushBeforeCloseFuncs = append(
> ```

Do you know why this guy defers the buffering to `Close()` time? Why not buffer immediately? That would seem more natural to me - give the client the notice in-stream, as it was generated.

I know it's not your code, but do me a favor and please find out. I'm thinking we can change some things around if this turns out to be unnecessary. And if not, let's document.
___
*[pkg/sql/pgwire/command_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7m_R2e3aCpL_lJjc4p:-M7m_R2e3aCpL_lJjc4q:b-r1bm3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/pgwire/command_result.go#L220)):*
> ```Go
> 		return err
> 	}
> 	return r.conn.Flush(r.pos)
> ```

Instead of this, I think it'd be better to offer a `Flush()` method on the `CommandResult` interface, and let the caller call that explicitly. Flushing has serious implications - no more auto-retries - so it should be as explicit as possible. It deserves an explicit comment on the `CommandResult` interface.
So this `SendNotice()` would become `BufferNotice()`, which I hope can be the same as the current `AppendNotice()` if we get rid of the deferment in `AppendNotice()`.


<!-- Sent from Reviewable.io -->

2020-05-20 17:55 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @miretskiy, and @pbardea)

___
*[pkg/sql/pgwire/command_result.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mYXqb6iHHZPs087rp:-M7nDNaPECwcNTf0vE8b:bo9wb2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/pgwire/command_result.go#L207)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Do you know why this guy defers the buffering to `Close()` time? Why not buffer immediately? That would seem more natural to me - give the client the notice in-stream, as it was generated.

I know it's not your code, but do me a favor and please find out. I'm thinking we can change some things around if this turns out to be unnecessary. And if not, let's document.
</blockquote></details>

@otan maybe you're the guy to ask ^


<!-- Sent from Reviewable.io -->

2020-05-20 18:27 UTC, otan commented
___
*[pkg/sql/pgwire/command_result.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mYXqb6iHHZPs087rp:-M7nKQ4_DV9KCrn55dtf:b-rym8se) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/pgwire/command_result.go#L207)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

@otan maybe you're the guy to ask ^
</blockquote></details>

I did this because I thought we wanted these not to appear if there were errors internally. Looking back, I don't think there's too strong a reason for it otherwise and the suggestion below would be sane.


<!-- Sent from Reviewable.io -->

2020-05-20 18:32 UTC, knz commented
Note that there is a cursor update in the pgwire result Close() method, and I believe it's not safe to send result packets before that cursor call. @andreimatei can you explain what this call precisely means?
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

2020-05-20 18:59 UTC, andreimatei commented
> Note that there is a cursor update in the pgwire result Close() method, and I believe it's not safe to send result packets before that cursor call. @andreimatei can you explain what this call precisely means?

Which call are we talking about? And which cursor update? I'm looking at [`commandResult.Close()`](https://github.com/cockroachdb/cockroach/blob/f4368088b8b709887cbf625820b83c1362aae717/pkg/sql/pgwire/command_result.go#L95`) and not seeing it.
Generally, results can be sent to the client before the command result is closed - it happens when the buffer we put in front of the `net.Conn` overflows.

What I've discussed with @miretskiy is implementing an option to send notices completely out of band from any results by bypassing the buffer and writing them straight to the connection. This would mean that, at least theoretically, the client can get them in the middle of results from previous statements, and also that a notice will be sent multiple times if the respective transaction is auto-retried, but on the flip side sending them will no longer have implications for disabling auto-retries.

2020-05-21 11:31 UTC, knz commented
I was considering this code from `(*commandResult) Close()`:

```go
        r.conn.writerState.fi.registerCmd(r.pos)
        if r.err != nil {
                r.conn.bufferErr(ctx, r.err)
                return
        }

        for _, f := range r.flushBeforeCloseFuncs {
                if err := f(ctx); err != nil {
                        panic(fmt.Sprintf("unexpected err when closing: %s", err))
                }
        }
```

Can you remind us what `writerState.fi.registerCmd` does? What is the impact of sending error/results to the client before that `registerCmd` call?

> implementing an option to send notices completely out of band from any results by bypassing the buffer and writing them straight to the connection. This would mean that, at least theoretically, the client can get them in the middle of results from previous statements, and also that a notice will be sent multiple times if the respective transaction is auto-retried

That seems completely unacceptable wrt UX to me.

2020-05-21 11:32 UTC, knz commented
My opinion from before is this: if a notice is sent early, then that should block auto-retry.

- for statements which we have a strong incentive to auto-retry, we should keep the current queueing behavior

- for certain statements (like bulk i/o) which never auto-retry anyway (IIRC), it doesn't matter as much and then we can send the notice early **and also disable auto-retry**

The idea is to never enter the incorrect zone of "auto-retry enabled AND results already sent to the client" which is going to bring misery and sadness.

2020-05-21 15:47 UTC, andreimatei reviewed
> Can you remind us what writerState.fi.registerCmd does? What is the impact of sending error/results to the client before that registerCmd call?

It maintains `cmdStarts`, which is a mapping from a pgwire command to the offset in `buf` where the results for the respective command begins. Generally, if results for the respective command had already been produced, then an offset is already registered and calling `registerCmd()` again at `Close()` time is a no-op (e.g. `AddRow()` calls `registerCmd()` too).
I'm not entirely sure why I've built it this way instead of always registering the offset in a single place - when the `commandResult` is constructed. I think maybe I didn't want to impose the rule that `commandResults` need to be created in order, one after closing the previous one. This was written in the time of parallel statements when things were more complex, I think. The implementation is optimized for the case where there's a single non-closed `commandResult` at  a time - see `allocCommandResult()`.

Anyway, buffering results for a command before calling `registerCmd()` results in those results not being discarded from the buffer when we rewind in order to do an automatic retry - so they'll be delivered to the client even if the statement is retried, potentially with a duplicate is the statement does the same thing a second time around. 

> for certain statements (like bulk i/o) which never auto-retry anyway (IIRC), it doesn't matter as much and then we can send the notice early and also disable auto-retry

At first I though the same and I suggested making the statement in charge of doing an explicit `Flush()` if it wants anything to be delivered to the client eagerly (e.g. a notice that it just buffered prior to flushing). But then it appeared that an `IMPORT` actually might need retries because it does some table-creation business (and in particular it does that *after* generating the notice).
So then I thought that forcing a flush would be a pity and so screw these notifications - let's just deliver them twice in the case of an auto-retried IMPORT. And potentially also out of order, although realistically it's hard to believe that would happen cause who'd batch together some statements before an `IMPORT`. I don't see these notices the same as more regular results for a statement; I see them as needed less coherence. I think everybody except our command client ignores them completely, and even our client seems to defer showing them somewhat.

If anything, as an alternative to preventing retries, I'd look into building some magic at the connection level to avoid sending the same notice twice for a statement (or perhaps even across statements). Or even doing this de-duplication in our client. But I for one honestly wouldn't bother.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M7rnikS7SDXIk2BOswe:b37j7wa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, @miretskiy, and @pbardea)



<!-- Sent from Reviewable.io -->

2020-05-21 16:08 UTC, knz commented
>  I think everybody except our command client ignores them completely, and even our client seems to defer showing them somewhat.

This shows that you're not the average SQL user :joy: 

In DBeaver (or maybe it was IntelliJ), a notice causes a modal pop-up dialog to show on the user's screen, which they have to manually click away. If we let those things come again, and again, and again due to some contention-driven retry, we'll have pitchforks at our doors.

2020-05-21 16:26 UTC, andreimatei commented
> In DBeaver (or maybe it was IntelliJ), a notice causes a modal pop-up dialog to show on the user's screen, which they have to manually click away. If we let those things come again, and again, and again due to some contention-driven retry, we'll have pitchforks at our doors.

Are you sure about this? From what I Google, [DBeaver](https://dba.stackexchange.com/questions/218175/how-do-you-view-postgresql-messages-such-as-raise-notice-in-dbeaver) lists them in some "Server output" console, and [Intellij](https://youtrack.jetbrains.com/issue/DBE-133?_ga=2.250607238.1650326677.1590077553-1273521924.1572462748) seems to not display them at all.
I find it hard to believe that somebody would use a modal dialog for these because I now see that Postgres has a `RAISE {INFO,NOTICE,ERROR}` statements that scripts can use to log stuff. Perhaps the modal you've seen is for specific severity levels?

Btw, @miretskiy I see that the default value we put in the notice's severity field is "error". Make sure you override that.

2020-05-21 16:30 UTC, otan commented
> Btw, @miretskiy I see that the default value we put in the notice's severity field is "error". Make sure you override that.

Should be done by https://github.com/cockroachdb/cockroach/blob/35d12cae4d5926a4a6fd9a865e74c775f2304ef7/pkg/sql/notice.go#L43

2020-05-23 19:31 UTC, miretskiy reviewed
I have made some changes where I basically tried to send those notifications in an unbuffered way
(as I discussed with @andreimatei ).

@knz  I have tested this w/ dbeaver and goland.  These warnings show up in a console.
They do not show up as modal dialogs anywhere.  Even IF there is a product out there that shows
these as modal dialogs, I don't think we should be designing around poorly written UIs.

I think sending notices immediately is more useful, and it simplifies API quite as well.

If there is a concern about spamming clients with excessive warnings, perhaps we can put in an artificial
limit (say, 3 or 5) on those notices and simply throw them away (or just log them).

What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M82-RoA7KK1lIVFR7yA:bgati6r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 765 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mWTmf3c9ZO0RH6zT4:-M7x313o7_BJymXtMX0T:b-t4xbb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L765)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This seems like a very weird interface to me. This function returns an error in case a notice is needed, but swallows all other errors. At the very least the name seems wrong (the function doesn't take any action) and it needs a comment. But I think it'd be a lot better if the `SendClientNoticeImmediately()` call was moved in this function, and no error was returned.

It also seems weird to me that the `SendClientNotice*()` functions take generic errors instead of something more specific, but I guess that's not on you.
</blockquote></details>

Changed... This was just a hack
___
*[pkg/ccl/importccl/import_stmt.go, line 774 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mbROV9noEKyTPyAeb:-M7x342A2cS9prqNQeKy:b-onw42) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L774)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Do we really want to swallow these errors? The files we're dealing with here I assume will be used for the import - so won't the import fail anyway? If so, let's just return them and stop the import early. Or is the rest of the import more resilient somehow?

If we leave the log statements, I think it'd be good for them to have a hint that it's an import logging the message, and also that the error is fairly benign (since we swallow it). And so then the `Errorf()` level doesn't seem appropriate, I guess.
</blockquote></details>

I mean, it was a best effort warning funciton.... But, if I can't open the file, i won't be able to import it anyway.  So, propagating an error anyway
___
*[pkg/ccl/importccl/import_stmt.go, line 778 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7maGfz8L5dDUftLcof:-M7x4udt8_yZiW9SV9XF:b-qncky) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L778)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/""/"" /* baseName */

I think it'd help if you renamed `store` above to `file`, since, as far as I understand, calling the factory with the path to a file actually gives you something like a file, not something like a store. Otherwise this call to `Size()` here lets the reader wonder whose size is being checked. FWIW I find the `ExternalStorageFromURIFactory` interface weird in this respect.
</blockquote></details>

I agree it is rather weird -- I think it's historical.
___
*[pkg/ccl/importccl/import_stmt.go, line 789 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1UpG0EajSebdtxHD:-M82-CnN6Ri-Q5La0Azw:b-4a2kzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L789)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ya thank? ;) This was just a POC.
</blockquote></details>

This is fixed
___
*[pkg/sql/conn_io.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mX_w74z7QJHhoyrfg:-M7x57H2EnvfescqqkSU:b-vber0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/conn_io.go#L884)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why panic (here and below)? Just make them no-ops; there's no interface for getting notices out of a `bufferedCommandResult`, so dropping them on the floor seems just fine.
</blockquote></details>

just following what was there before, i suppose.  I changed it
___
*[pkg/sql/notice.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c2FJT9XmsUUqduCBR:-M82-HNuCnxRPW9N_gPD:byubvuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L39)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: I think adding: `p.sendClientNoticeInternal(ctx, false /* flush */, err)` would be helpful here. (Same for the other call to `sendClientNoticeInternal`.)
</blockquote></details>

No longer applicable
___
*[pkg/sql/notice.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mZIsb81ZHmVi8WE4n:-M7xZPba12cZLerohSOl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L47)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please turn this bool into an enum so you don't have to comment all the callsites. The style guide encourages this too. It can be a bool one like 
```
type flushOpt bool
const (
flush flushOpt = true
dontFlush = false
)
```
</blockquote></details>

Done.
___
*[pkg/sql/notice.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7mZxLL9M6LslQG02u3:-M7xZYfGBIbf5fC68I3C:b-tyja65) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L67)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think you want to swallow this error, do you? Errors from this `SendNotice()` I think mean that the client connection dropped. Let's propagate this error up to stop the query.
</blockquote></details>

none of the methods in this api return errors.
___
*[pkg/sql/notice.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1s6e3F1dD0_2pLsQ:-M82-IgW-36v3xk2nZ7U:byubvuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/notice.go#L67)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: I think using the `%+v` directive provides [a bit more info which may be useful for debugging](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#details-for-troubleshooting). This also applies to the logs in `warnIfImportFileTooLarge`.
</blockquote></details>

No longer applicable
___
*[pkg/sql/pgwire/command_result.go, line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7m_R2e3aCpL_lJjc4p:-M82-Nz-B8oOyXI6ONa_:byubvuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/sql/pgwire/command_result.go#L220)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Instead of this, I think it'd be better to offer a `Flush()` method on the `CommandResult` interface, and let the caller cal [...]

2020-05-23 19:31 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M7c1MOk2NfS3CTyXwqd:-M8208ia5a61eLoofumD:b-ril1fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cbce7beb0c37383931ddaf14c043e7d64a50ff9/pkg/ccl/importccl/import_stmt.go#L696)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Yup.. Just testing
</blockquote></details>

do we want to warn at lower than 512MB?


<!-- Sent from Reviewable.io -->

2020-05-23 20:44 UTC, knz commented
I like this summary of your opinion so far:

> I think sending notices immediately is more useful, and it simplifies API 
quite as well.

On my side, I will remain on record with the dissenting opinion.

So we have:

- making notices non-transactional (your proposal):
  - **pros:** "simpler to implement" (is that really true?), "more useful" (this would need some more evidence, but I'll go with it)
  - **cons:** notices not transactional, will cause noise in case of auto-retries server side, loses the 1-1 mapping between statements executed server-side and what the client receives

- keeping notices transactional like errors (my position so far):
  - **pros:** simpler to *understand* and to explain (no exception to the existing models), simpler to predict what's going on
  - **cons:** introduces a distinction between "early notices", which disable server-side auto-retries, and "late notices" which behave as currently

There are some design points already mentioned in the discussion, and some more not yet listed:

- limit the number of repetitions of the same notice
- delay the sending of the first notice for a few seconds, to give a chance for the stmt to be auto-retried if there's a txn conflict


Finally, I'd like to point out that none of the participants in this discussion are nominally responsible for the SQL interface and compatibility  with 3rd party clients. I am surprised that the discussion so far has not involved the AppDev or SQL features team. I'd really like to have @jordanlewis chime in or delegate the evaluation of this proposal to one of the other TLs in the SQL teams.

2020-05-25 21:41 UTC, miretskiy reviewed
Just to be clear: I wanted to try out things suggested by @andreimatei  -- and, in my opinion, those things are simpler
to understand: there is no queueing of function closures.

I'm not trying to make any sweeping statements about the protocol, etc.  I wanted to try out notice facility for the problem I wanted to address. 

 I have however spent some time looking at the existing use cases of the notice api.  I disagree with the statement that  transaction approach is "pros: simpler to understand and to explain (no exception to the existing models), simpler to predict what's going on".
I think it's the exact opposite.  It's not easy to understand: consider when you call SendNotice(), nothing is sent when called.  So, at the very least, this should be called BufferNoticeUntilClose.  Secondly, I question the usefulness of buffering notices as a whole. Let's look at e.g. primary key change notice (I looked at all other use cases of SendNotice -- all are same as alter key):

```
p.SendClientNotice(
		ctx,
		pgnotice.Newf(
			"primary key changes are finalized asynchronously; "+
				"further schema changes on this table may be restricted until the job completes"),
	)
```
It appears that this notice is useful because it tells the operator that other schema changes are restricted.  However, the *only* reason why this notice is useful is because of the implementation detail of primary key change -- in particular, that operation does not block, and returns as soon as the job to do the schema change is created.

So, we have an API that is only useful for short running operations, and for operations that execute as background
jobs.  Even though, it's called, rather generically, "SendNotice", the caller must know a priory that the statement will execute "quickly" -- otherwise that notice will likely arrive too late to be of too much use.

I also do not think that the api that disables retries if the notice is sent early is great either.  I think we either need to figure out how to make notices useful in all use cases, or make it abundantly clear  via method names, etc that this API has a limited use and is not applicable to all situations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M87k4-y626Gdcen6he8:b-o68590)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @pbardea)



<!-- Sent from Reviewable.io -->

2020-05-26 15:51 UTC, andreimatei reviewed
What I was thinking is that we'd have both options for notifications - buffered and unbuffered. If the existing users are happy with the buffering, no reason to change them in my opinion.
I very much like the removing the "deferred buffering" behavior though - the queuing of closers. Since @otan doesn't seem to want to defend it, I'm happy it's going away - but I think it should be replaced by immediate buffering. And please move that to a separate commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-:-M8Gf-xj4aG-hTb-fhhb:b-9n67fh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt.go, line 698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8GboujERQMKeC0JndR:-M8GboujERQMKeC0JndS:b-gezvfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/ccl/importccl/import_stmt.go#L698)):*
> ```Go
> 
> 		const warnSize = 512 << 20
> 		haveLargeFiles, err := checkImportLargeFiles(ctx, files, p.ExecCfg().DistSQLSrv.ExternalStorageFromURI, warnSize)
> ```

line over 100 cols
___
*[pkg/ccl/importccl/import_stmt.go, line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8GbwDK7u0OkbkhkXc8:-M8GbwDK7u0OkbkhkXc9:blali72) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/ccl/importccl/import_stmt.go#L705)):*
> ```Go
> 		if haveLargeFiles {
> 			warning := fmt.Sprintf(`
> It appears you are trying to import a large (>%s) file.
> ```

can we print the actual size? I think it'd be much more useful than the threshold.
___
*[pkg/ccl/importccl/import_stmt.go, line 714 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8Gc57i0ddL1m7SIPU7:-M8Gc57i0ddL1m7SIPU8:b-na1d07) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/ccl/importccl/import_stmt.go#L714)):*
> ```Go
> Importing large %s files can also be made faster by creating target SQL table(s)
> by hand, and executing "IMPORT INTO ..." statement instead.
> `, importStmt.FileFormat)
> ```

nit: we're printing the file format here and the text makes it sound like it's important, but it looks to me like the format doesn't actually matter; the advice seems to be good regardless of the format. So consider removing it.
___
*[pkg/ccl/importccl/import_stmt.go, line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8GcN7YC8gtf1uHE0nR:-M8GcN7YC8gtf1uHE0nS:bzhe5gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/ccl/importccl/import_stmt.go#L718)):*
> ```Go
> 
> 			if err := p.ExtendedEvalContext().ClientNoticeSender.SendClientNotice(
> 				ctx, pgnotice.NewWithSeverityf("NOTICE", warning)); err != nil {
> ```

nit: I think formatting as 
```
	if err := p.ExtendedEvalContext().ClientNoticeSender.SendClientNotice(
			ctx, pgnotice.NewWithSeverityf("NOTICE", warning),
           ); err != nil {
```
is much more common in our code (and for good reason IMO).
___
*[pkg/sql/conn_io.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8GddT334LHFIA3RZCn:-M8GddT334LHFIA3RZCo:b3wah8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/sql/conn_io.go#L688)):*
> ```Go
> 	AppendParamStatusUpdate(string, string)
> 
> 	// SendNotice sends notification message to the client.
> ```

sends *a* notification message

If this stays, please comment about how notices are not buffered and thus not discarded by rewinds, as it is in contrast to everything else.
An alternative is to replace this with a `Conn()` method that returns an interface modeling the connection, and put the `SendNotice()` method on that interface. I think I'd favor that such that all communication methods on the `CommandResult` stay buffered.
___
*[pkg/sql/pgwire/conn.go, line 612 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49190#-M8GdwkF7GQ5QhytdqnH:-M8GdwkF7GQ5QhytdqnI:b7j7luw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1f650f24a6c38bec1f2227b8d9b4728f2fc22c8/pkg/sql/pgwire/conn.go#L612)):*
> ```Go
> func (c *conn) sendNotice(ctx context.Context, noticeErr error) error {
> 	c.msgBuilder.initMsg(pgwirebase.ServerMsgNoticeResponse)
> 	return writeErrFields(ctx, c.sv, noticeErr, &c.msgBuilder, c.conn)
> ```

pls highlight again in a comment that `c.conn` is used here instead, instead of the buffer


<!-- Sent from Reviewable.io -->

2021-04-22 16:07 UTC, closed without merging