kv/concurrency: avoid redundant txn pushes and batch intent resolution
cockroachdb/cockroach pull request #49218
Opened 2020-05-18 21:05 UTC by nvanbenschoten

Fixes #48790.
Informs #36876.
Closes #31664.

This commit adds a per-Range LRU cache of transactions that are known to be aborted or committed. We use this cache in the lockTableWaiter for two purposes:
1. when we see a lock held by a known-finalized txn, we neither wait out the `kv.lock_table.coordinator_liveness_push_delay` (10 ms) nor push the transactions record (RPC to leaseholder of pushee's txn record range).
2. we use the existence of a transaction in the cache as an indication that it may have abandoned multiple intents, perhaps due to a failure of the transaction coordinator node, so we begin deferring intent resolution to enable batching.

Together, these two changes make us much more effective as cleaning up after failed transactions that have abandoned a large number of intents. The following example demonstrates this:
```sql
--- BEFORE

CREATE TABLE keys (k BIGINT NOT NULL PRIMARY KEY);
BEGIN; INSERT INTO keys SELECT generate_series(1, 10000); ROLLBACK;
SELECT * FROM keys;

  k
-----
(0 rows)

Time: 2m50.801304266s

CREATE TABLE keys2 (k BIGINT NOT NULL PRIMARY KEY);
BEGIN; INSERT INTO keys2 SELECT generate_series(1, 10000); ROLLBACK;
INSERT INTO keys2 SELECT generate_series(1, 10000);

INSERT 10000

Time: 3m26.874571045s

--- AFTER

CREATE TABLE keys (k BIGINT NOT NULL PRIMARY KEY);
BEGIN; INSERT INTO keys SELECT generate_series(1, 10000); ROLLBACK;
SELECT * FROM keys;

  k
-----
(0 rows)

Time: 5.138220753s

CREATE TABLE keys2 (k BIGINT NOT NULL PRIMARY KEY);
BEGIN; INSERT INTO keys2 SELECT generate_series(1, 10000); ROLLBACK;
INSERT INTO keys2 SELECT generate_series(1, 10000);

INSERT 10000

Time: 48.763541138s
```

Notice that we are still not as fast at cleaning up intents on the insertion path as we are at doing so on the retrieval path. This is because we only batch the resolution of intents observed by a single request at a time. For the scanning case, a single ScanRequest notices all 10,000 intents and cleans them all up together. For the insertion case, each of the 10,000 PutRequests notices a single intent, and each intent is cleaned up individually. So this case is only benefited by the first part of this change (no liveness delay or txn record push) and not the second part of this change (intent resolution batching).

For this reason, we still haven't solved all of #36876. To completely address that, we'll need to defer propagation of `WriteIntentError` during batch evaluation, as we do for `WriteTooOldError`s. Or we can wait out the future LockTable changes - once we remove all cases where an intent is not "discovered", the changes here will effectively address #36876.

This was a partial regression in v20.1, so we'll want to backport this to that release branch. This change is on the larger side, but I feel ok about it because the mechanics aren't too tricky. I'll wait a week before backporting just to see if anything falls out.

Release note (bug fix): Abandoned intents due to failed transaction coordinators are now cleaned up much faster. This resolves a regression in v20.1.0 compared to prior releases.

@irfansharif I'm adding you as a reviewer because there's not really anyone else on KV that knows this code, so we should change that.

2020-05-18 21:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49218)
<!-- Reviewable:end -->

2020-05-19 16:04 UTC, sumeerbhola requested changes
Generally looks good. I haven't yet looked carefully at the tests.

> Reviewed 3 of 10 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-:-M7hew-cEBX7qpRvLjDr:bw9zuqv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hPGlm2vnaWyAgnqZe:-M7hPGlm2vnaWyAgnqZf:b-bcalr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/concurrency_control.go#L636)):*
> ```Go
> 	WaitOnLock(context.Context, Request, *roachpb.Intent) *Error
> 
> 	// ClearCaches wipes all caches maintained by the lockTableWaiter.
> ```

Is this also for the situation where the lockTable is disabled? Could you add a code comment?
And is this just to recover memory -- a stale cache of committed/aborted transactions is presumably harmless for correctness?
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hd-xV3OGaSCD56Y2G:-M7hd-xV3OGaSCD56Y2H:bdpfg2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L136)):*
> ```Go
> 	// batching of intent resolution while cleaning up after abandoned txns.
> 	var deferredResolution []roachpb.LockUpdate
> 	defer w.resolveDeferredIntents(ctx, &err, &deferredResolution)
> ```

If there are N cache hits we would build up N intents in this slice and then a miss would cause this request to wait without doing the resolution. Should the deferred batch be flushed based on a timer? Perhaps worth a code comment.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hQMm_0I8K2eH8dW60:-M7hQMm_0I8K2eH8dW61:bmr613n) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L162)):*
> ```Go
> 				// had a cache of aborted transaction IDs that allowed us to notice
> 				// and quickly resolve abandoned intents then we might be able to
> 				// get rid of this state.
> ```

We now have a cache. But don't we still need the short timer to quickly add the aborted txn to the cache? If so, probably should reword this comment.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7ha7Xy685JLFMDQzfc:-M7ha7Xy685JLFMDQzfd:b-j2khv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L196)):*
> ```Go
> 				// This allows us to accumulate a group of intents to resolve
> 				// and send them together as a batch.
> 				if livenessPush {
> ```

I think it is worth commenting again here that if the lock is held there will be at least one waiter (the distinguished waiter) that will have `livenessPush=true`, so will do this work that will benefit all waiters.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hbm8FD-Zy6P4voNo9:-M7hbm8FD-Zy6P4voNoA:b252wn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L207)):*
> ```Go
> 						// the future (before we observe the corresponding MVCC state).
> 						// This is safe because we already handle cases where locks
> 						// exist only in the MVCC keyspace and not in the lockTable.
> ```

This is justifying why this is correct for replicated locks. How about adding something like:
For unreplicated locks, the `lockTable` is the source of truth, and removing the locks held by an already committed/aborted transaction does not affect correctness. 
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hdkxs6P43US_naNAc:-M7hdkxtBIQgpEeI2atI:bi0k9ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L592)):*
> ```Go
> type finalizedTxnCache struct {
> 	mu   syncutil.Mutex
> 	txns [8]*roachpb.Transaction // [MRU, ..., LRU]
> ```

How big wrt memory footprint are these `Transaction` objects? I am trying to understand the reason for the choice of 8.


<!-- Sent from Reviewable.io -->

2020-05-20 19:07 UTC, irfansharif reviewed
LGTM as someone looking at this for the first time.

> Reviewed 9 of 10 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-:-M7nRFTz64I5wMLediiP:b-9a0zwc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7n-ieJ05AxLgyJWnx1:-M7n-ieJ05AxLgyJWnx2:bnhyxfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/concurrency_manager.go#L344)):*
> ```Go
> 	} else {
> 		// Disable all queues - the concurrency manager will no longer be
> 		// informed about all state transitions to locks and transactions.
> ```

Comment here could be updated to say we're also clearing out the cache, and why (also, unclear to me why we need this).
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7nFLh96kcsqegI1N-O:-M7nFLh96kcsqegI1N-P:b9wop2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L96)):*
> ```Go
> 	// For now, we don't do this because we don't share any state between
> 	// separate concurrency.Manager instances.
> 	knownTxns finalizedTxnCache
> ```

[nit] I think `knownTxns` is a bit vague, but I don't have a better suggestion. Perhaps just `finalizedTxnCache`? The type itself is a generic txn LRU cache, and the comment block above the type definition is better suited here, I think.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7nRoFq03e8pJCyuz5y:-M7nRoFq03e8pJCyuz5z:b-e2ohu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L119)):*
> ```Go
> 	ResolveIntent(context.Context, roachpb.LockUpdate, intentresolver.ResolveOptions) *Error
> 
> 	// ResolveIntent synchronously resolves the provided batch of intents.
> ```

s/ResolveIntent/ResolveIntents


<!-- Sent from Reviewable.io -->

2020-05-23 05:42 UTC, nvb reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-:-M8-0jsN3AVuuLPOPHKL:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hPGlm2vnaWyAgnqZe:-M7yg8py1BlahksEskeb:b-jeyk15) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/concurrency_control.go#L636)):*
> Is this also for the situation where the lockTable is disabled? Could you add a code comment?

Done.

> And is this just to recover memory -- a stale cache of committed/aborted transactions is presumably harmless for correctness?

Yes, that's correct. A stale cache entry is harmless, it just consumes memory and can also interact with tests.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7n-ieJ05AxLgyJWnx1:-M7ygwDOAmXkMFZK3NPj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/concurrency_manager.go#L344)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Comment here could be updated to say we're also clearing out the cache, and why (also, unclear to me why we need this).
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7nFLh96kcsqegI1N-O:-M7yh7cX5IiN7K57lQ8Q:b-4k0685) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L96)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] I think `knownTxns` is a bit vague, but I don't have a better suggestion. Perhaps just `finalizedTxnCache`? The type itself is a generic txn LRU cache, and the comment block above the type definition is better suited here, I think.
</blockquote></details>

Good point! Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7nRoFq03e8pJCyuz5y:-M7yhbuiDrk-FWQILY7O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53dec58c0abd125990ec812ac6ba9c3c49cfa02e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L119)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/ResolveIntent/ResolveIntents
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hd-xV3OGaSCD56Y2G:-M7zzPzk6JX4rGKpUf-e:b-2hqfua) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L136)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If there are N cache hits we would build up N intents in this slice and then a miss would cause this request to wait without doing the resolution. Should the deferred batch be flushed based on a timer? Perhaps worth a code comment.
</blockquote></details>

I added a comment. I don't think there's a strong need to flush deferred intent resolution on a timer. There is a subtle interaction here in cases where the request that deferred the intent resolution does not acquire a reservation on the key, but flushing wouldn't address this anyway.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hQMm_0I8K2eH8dW60:-M7yiE6--dfMf88g62so:bqhxjy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L162)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We now have a cache. But don't we still need the short timer to quickly add the aborted txn to the cache? If so, probably should reword this comment.
</blockquote></details>

Done. I just removed it because I don't think the cache is effective enough at avoiding redundant pushes to warrant risking multiple 100ms delays. Right now, it's not even shared between ranges. Even if it was, there's no way to share it between nodes. We really don't want to slow down the initial push if we have scenarios where this delay can compound.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7ha7Xy685JLFMDQzfc:-M7yjK9wBVom69fZ08ir:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L196)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it is worth commenting again here that if the lock is held there will be at least one waiter (the distinguished waiter) that will have `livenessPush=true`, so will do this work that will benefit all waiters.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hbm8FD-Zy6P4voNo9:-M7ykcrV7ffH-pj777u9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L207)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is justifying why this is correct for replicated locks. How about adding something like:
For unreplicated locks, the `lockTable` is the source of truth, and removing the locks held by an already committed/aborted transaction does not affect correctness. 
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_waiter.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M7hdkxs6P43US_naNAc:-M7yf1s57eMfAKHyIcGi:bmhl110) ([raw file](https://github.com/cockroachdb/cockroach/blob/639ecb8c81944976ab97b598268dd394173e47bb/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L592)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How big wrt memory footprint are these `Transaction` objects? I am trying to understand the reason for the choice of 8.
</blockquote></details>

They are 288 bytes large, so 8 puts us just over 2KB per leaseholder range. Even on large nodes, we tend to top out at about 10k leaseholders per node, so that puts the maximum size of this cache across an entire process at ~20MB, which seems fine for now. There's a TODO to move this to a per-store cache, which would allow us to increase its size significantly and remove the num_leaseholder factor from the size.


<!-- Sent from Reviewable.io -->

2020-05-26 13:30 UTC, irfansharif approved these changes
> Reviewed 10 of 10 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2020-05-26 14:26 UTC, nvanbenschoten commented
bors r+

2020-05-26 15:12 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 10 files at r1, 2 of 10 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-:-M8GXiUu2uUe7ZGuVN16:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @irfansharif, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M8GWIdp6z9seJM5Iwg3:-M8GWIdqBF6rEQ1tcOLo:b-gw78me) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d39d204b698942919675a290c6978b1fcb35214/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents#L69)):*
> ```
> [3] sequence req1: pushing timestamp of txn 00000002 above 0.000000010,1
> [3] sequence req1: blocked on select in concurrency_test.(*cluster).PushTransaction
> ```

Could you add another debug-lock-table here and add a comment that since txn1 is the distinguished waiter for "a" it will try to push and that is the first intent resolution of "a" below (due to the abort of txn2), and then the cache kicks in to cause a batch resolution of the others.


<!-- Sent from Reviewable.io -->

2020-05-26 15:40 UTC, nvanbenschoten commented
bors r-

2020-05-26 18:52 UTC, nvb reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-:-M8HK1n11VfZEfQXRAeg:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @irfansharif and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49218#-M8GWIdp6z9seJM5Iwg3:-M8HK12aDOniMfo7IRYC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d39d204b698942919675a290c6978b1fcb35214/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add another debug-lock-table here and add a comment that since txn1 is the distinguished waiter for "a" it will try to push and that is the first intent resolution of "a" below (due to the abort of txn2), and then the cache kicks in to cause a batch resolution of the others.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-26 19:36 UTC, merged