WIP sql: distsql spec creation in execbuilder plumbing
cockroachdb/cockroach pull request #49348
Opened 2020-05-20 23:43 UTC by yuzefovich

**sql: add stub exec.factory implementation for execbuilder-driven distsql spec**

This commit adds a stub implementation of `exec.Factory` interface that
will be creating DistSQL processor specs directly from `opt.Tree`,
sidestepping intermediate `planNode` phase.

It also introduces a new private setting
"sql.distsql.experimental_planning.enabled" that determines whether the
new factory is used, set to `false` by default.

Release note: None

**sql: remove two private settings**

This commit removes two private settings that could disable planning of
multiple join readers (i.e would disable distribution) and disable
planning merge joiners (i.e. would simply prohibit the use of merge
joiners).

Release note: None

To be continued.

2020-05-20 23:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49348)
<!-- Reviewable:end -->

2020-05-28 13:00 UTC, asubiotto requested changes
Great to see this!

The last commit seems to claim something that I don't think is happening yet ("we will use the execbuilder-driven DistSQL spec creationg only for SELECT statements"). 

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8QElta709pf7KZjleX:bsbudu9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[docs/generated/settings/settings.html, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QFDDM5k58SbaxG2sX:-M8QFDDM5k58SbaxG2sY:b-sstsow) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/docs/generated/settings/settings.html#L48)):*
> ```HTML
> <tr><td><code>sql.defaults.results_buffer.size</code></td><td>byte size</td><td><code>16 KiB</code></td><td>default size of the buffer that accumulates results for a statement or a batch of statements before they are sent to the client. This can be overridden on an individual connection with the 'results_buffer_size' parameter. Note that auto-retries generally only happen while no results have been delivered to the client, so reducing this size can increase the number of retriable errors a client receives. On the other hand, increasing the buffer size can increase the delay until the client receives the first result row. Updating the setting only affects new connections. Setting to 0 disables any buffering.</td></tr>
> <tr><td><code>sql.defaults.serial_normalization</code></td><td>enumeration</td><td><code>rowid</code></td><td>default handling of SERIAL in table definitions [rowid = 0, virtual_sequence = 1, sql_sequence = 2]</td></tr>
> <tr><td><code>sql.distsql.experimental_planning.enabled</code></td><td>boolean</td><td><code>false</code></td><td>set to true to enable experimental DistSQL planning driven by the optimizer.</td></tr>
> ```

Why is only this cluster setting removed from the file? I also feel like this commit should probably be its own PR.
___
*[pkg/sql/distsql_running.go, line 900 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QHNmY8sbwANlN6CIF:-M8QHNmY8sbwANlN6CIG:b-9nqzkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/distsql_running.go#L900)):*
> ```Go
> 	} else {
> 		var err error
> 		subqueryPhysPlan, err = dsp.createPhysPlanForPlanNode(subqueryPlanCtx, subqueryPlan.plan.planNode)
> ```

Instead of having this `if else` in a lot of these places, could you create a wrapper over `createPhysPlanForPlanNode` that either unwraps the plan as a planNode, or returns the physical plan?
___
*[pkg/sql/exec_util.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QCl8U-EeFhocVYYDs:-M8QCl8V5R19x19g0esY:b-e6ymv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/exec_util.go#L257)):*
> ```Go
> // execbuilder-driven DistSQL spec creation that sidesteps intermediate
> // planNode transition when going from opt.Tree to DistSQL processor specs.
> var execBuilderDrivenDistSQLSpecCreationClusterMode = settings.RegisterBoolSetting(
> ```

This feels unnecessarily long. How about `execBuilderBuildDistSQLSpecsDirectly`?
___
*[pkg/sql/exec_util.go, line 919 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QJSOU8nqQyT8dloXq:-M8QJSOU8nqQyT8dloXr:blzc9wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/exec_util.go#L919)):*
> ```Go
> 	var rec distRecommendation
> 	if plan.physPlan != nil {
> 		rec = plan.recommendation
> ```

Where is this recommendation coming from?
___
*[pkg/sql/execbuilder_distsql_spec_factory.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QDcp5-E5NZyuTjnEr:-M8QDcp5-E5NZyuTjnEs:b-3t0um2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/execbuilder_distsql_spec_factory.go#L24)):*
> ```Go
> )
> 
> type execBuilderDistSQLSpecFactory struct {
> ```

Not sure if it makes sense to have exec builder in this name and the filename. How about `distSQLSpecExecFactory` and `s/execbuilder/opt` in the filename?
___
*[pkg/sql/execbuilder_distsql_spec_factory.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QEPcHED4EUa79jWfA:-M8QEPcHED4EUa79jWfB:b3wx13d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/execbuilder_distsql_spec_factory.go#L32)):*
> ```Go
> func makeExecBuilderDistSQLFactory(allowAutoCommit bool) execBuilderDistSQLSpecFactory {
> 	return execBuilderDistSQLSpecFactory{
> 		allowAutoCommit: allowAutoCommit,
> ```

Why add this if it's not used?
___
*[pkg/sql/explain_distsql.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QJohdEdHbnj80qgm6:-M8QJohdEdHbnj80qgm7:b-mmksi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/explain_distsql.go#L154)):*
> ```Go
> 	var physPlan PhysicalPlan
> 	if n.plan.main.physPlan != nil {
> 		physPlan = *n.plan.main.physPlan
> ```

What happens if we have subqueries in this case?
___
*[pkg/sql/plan.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QG-Dz1IiSGEKPkPVP:-M8QG-Dz1IiSGEKPkPVQ:b-6a42sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan.go#L323)):*
> ```Go
> // use either planNode or DistSQL spec representation, but eventually will be
> // replaced by the latter representation directly.
> type planMaybePhysical struct {
> ```

What made you choose to do this instead of creating a new `planNode` that is a wrapper over a `*PhysicalPlan`? I think it would probably require less code changes. The distsql planning code could then check for that and unwrap the physical plan.
___
*[pkg/sql/plan_opt.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QEy6p8BQgKpb9M4rt:-M8QEy6p8BQgKpb9M4ru:bxmv1dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/plan_opt.go#L182)):*
> ```Go
> 		execFactory = &factory
> 	} else {
> 		factory := makeExecFactory(p)
> ```

I wonder why we don't just `s/make/new` and return a pointer directly
___
*[pkg/sql/plan_opt.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QKay7ElLZSYys2g6t:-M8QKay7ElLZSYys2g6u:b-c9bwry) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan_opt.go#L184)):*
> ```Go
> 	// TODO(yuzefovich): update this once we support more than just creating
> 	// table reader specs in execbuilder.
> 	isSelectStmt := strings.HasPrefix(strings.ToLower(p.stmt.SQL), "select")
> ```

I think it would be better to look at `p.stmt.AST` 
___
*[pkg/sql/plan_opt.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QKsiK8wRV0cIUs64W:-M8QKsiK8wRV0cIUs64X:b-u3lk2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan_opt.go#L185)):*
> ```Go
> 	// table reader specs in execbuilder.
> 	isSelectStmt := strings.HasPrefix(strings.ToLower(p.stmt.SQL), "select")
> 	if execBuilderDrivenDistSQLSpecCreationClusterMode.Get(&p.execCfg.Settings.SV) && isSelectStmt {
> ```

Do we want to add a mode for this cluster setting similar to `vectorize_always` that uses this factory regardless of support?
___
*[pkg/sql/schema_changer.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QLYriCIDhLuKLCJbF:-M8QLYriCIDhLuKLCJbG:b-wizz46) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/schema_changer.go#L240)):*
> ```Go
> 
> 		// TODO(yuzefovich): update this once we support more than just
> 		// creating table reader  [...]

2020-05-28 22:35 UTC, yuzefovich reviewed
It was happening (in `plan_opt.go`), but I moved the claim in the first commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8SQ2Cp02OJpi42l3gl:beke3c3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[docs/generated/settings/settings.html, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QFDDM5k58SbaxG2sX:-M8RgYNPA9L0cidqEGbv:bgf6kww) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/docs/generated/settings/settings.html#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is only this cluster setting removed from the file? I also feel like this commit should probably be its own PR.
</blockquote></details>

I didn't regenerate the settings on the first commit on its own, fixed.

Extracted the second commit into a separate PR. 
___
*[pkg/sql/distsql_running.go, line 900 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QHNmY8sbwANlN6CIF:-M8SPmPY-jajgiSylYQ_:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/distsql_running.go#L900)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of having this `if else` in a lot of these places, could you create a wrapper over `createPhysPlanForPlanNode` that either unwraps the plan as a planNode, or returns the physical plan?
</blockquote></details>

Good point, done.
___
*[pkg/sql/exec_util.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QCl8U-EeFhocVYYDs:-M8RmiC6AZRoSxm9cGTn:bim548h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/exec_util.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This feels unnecessarily long. How about `execBuilderBuildDistSQLSpecsDirectly`?
</blockquote></details>

Renamed it to be inline with the actual setting name.
___
*[pkg/sql/exec_util.go, line 919 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QJSOU8nqQyT8dloXq:-M8RiCmW4yC7xSyGUiTZ:b-qu4it9) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/exec_util.go#L919)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Where is this recommendation coming from?
</blockquote></details>

Currently, `checkSupportForNode` and `createPlanForNode` return the distribution recommendation and the physical plan respectively, but I envision that the new distsql exec factory will populate both at the same time - it will make the recommendation while constructing distsql specs. This is still TBD.
___
*[pkg/sql/explain_distsql.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QJohdEdHbnj80qgm6:-M8SE1hN2yMsNeqsBw-f:b-v627zy) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/explain_distsql.go#L154)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What happens if we have subqueries in this case?
</blockquote></details>

The error should occur earlier, in the execbuilder. Left a TODO as a reminder.
___
*[pkg/sql/plan.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QG-Dz1IiSGEKPkPVP:-M8SKWbS03abPvRTo5Ut:b-33h1i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan.go#L323)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What made you choose to do this instead of creating a new `planNode` that is a wrapper over a `*PhysicalPlan`? I think it would probably require less code changes. The distsql planning code could then check for that and unwrap the physical plan.
</blockquote></details>

To me such an approach breaks an assumption that a `planNode` represents a single node in the tree because this new wrapper plan node would contain the whole physical plan at once, i.e. it would be a "meta" node.

I guess we could change the perspective a little and, instead, introduce a "plan-node-that-might-be-distsql-processor-spec" which would be the distsql spec for a single plan node and not the whole tree, but I don't know whether it'll be better.

This is one of those things that I learn by doing, and we're still laying out the plumbing before doing some meaningful work. From my point of view, it should be ok to merge something that moves us forward in the prototyping of this experimental planning (and doesn't break the normal flow), and we can iterate on the representation later.
___
*[pkg/sql/plan_opt.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QEy6p8BQgKpb9M4rt:-M8Rkb4_61kXxJfGV9aH:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/plan_opt.go#L182)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder why we don't just `s/make/new` and return a pointer directly
</blockquote></details>

Good point, done.
___
*[pkg/sql/plan_opt.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QKay7ElLZSYys2g6t:-M8S41zo6wLv-HNnhu1H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan_opt.go#L184)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it would be better to look at `p.stmt.AST` 
</blockquote></details>

Done.
___
*[pkg/sql/plan_opt.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QKsiK8wRV0cIUs64W:-M8Rmx85Dk8QCTllXI-Y:b9j79i) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan_opt.go#L185)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to add a mode for this cluster setting similar to `vectorize_always` that uses this factory regardless of support?
</blockquote></details>

I also thought about this, but the difficulty is if you set your cluster setting to `always` or whatever, you won't be able to change that easily. I tried catching `SET` statements and use the old factory for that, but internally we use `INSERT` into a system table (I guess) and maybe other statements, so it seemed pretty hard.

That is why (at least for now) I decided to not implement the fallback from the new factory to the old one if the former doesn't support the statement, but apply the heuristic to see whether the statement is a `SELECT`.
___
*[pkg/sql/schema_changer.go, line 240 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QLYriCIDhLuKLCJbF:-M8S9eyb6wEqruMTkaH3:bmamigh) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/schema_changer.go#L240)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this TODO needs to be reworded (and any similar ones) because "once we support more" is not clear. Does doing this require support for all specs? If so, we should probably link the issue.
</blockquote></details>

Removed this particular TODO and updated others.
___
*[pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QE9JZ0OS7PZtwB1_x:-M8S5rCrAy6l9BgXLEMN:b-1utt34) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning#L1)):*
<details><summary><i>Previousl [...]

2020-05-28 22:44 UTC, RaduBerinde commented
CC @rytaft

2020-05-28 23:34 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/execbuilder_distsql_spec_factory.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QDcp5-E5NZyuTjnEr:-M8ScRSE-emrPWu25VuR:b-arsxwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/execbuilder_distsql_spec_factory.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Renamed the struct and the file.

My initial thinking for the filename was that eventually the file should live in `execbuilder` package, so I used it as a prefix, but I'm not sure why I didn't create the file in that package right away, moved. Possibly we will need to move the file back, but we can do so later.
</blockquote></details>

I moved the file back into `pkg/sql` because currently `opt_exec_factory` is quite strongly coupled with that package, and I'm worried that moving the necessary pieces into a shared "base" package will be a little too much (for the moment).


<!-- Sent from Reviewable.io -->

2020-05-29 20:47 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QCl8U-EeFhocVYYDs:-M8XA1Q4ChAf_0htGTZR:b-5318q3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/exec_util.go#L257)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Renamed it to be inline with the actual setting name.
</blockquote></details>

I'm still debating on what the naming should be: currently I have "experimental distsql planning", and that implies not only the spec creation but also actual distsql physical planning, probably it's acceptable, but then the scope of the project increases. I don't think we'll get to the "physical planning" part in the near term, but it might make sense to keep this naming as an aspirational goal.
___
*[pkg/sql/plan_opt.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QKsiK8wRV0cIUs64W:-M8XAokX8ig4SdzJ3OKb:bp0npp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan_opt.go#L185)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I also thought about this, but the difficulty is if you set your cluster setting to `always` of whatever, you won't be able to change that easily. I tried catching `SET` statements and use the old factory for that, but internally we use `INSERT` into a system table (I guess) and maybe other statements, so it seemed pretty hard.

That is why (at least for now) I decided to not implement the fallback from the new factory to the old one if the former doesn't support the statement, but apply the heuristic to see whether the statement is a `SELECT`.
</blockquote></details>

I've actually just added this `always` mode and changed the setting to be more like what we have with `vectorize` after I did more prototyping.


<!-- Sent from Reviewable.io -->

2020-06-01 11:48 UTC, asubiotto requested changes
> Reviewed 20 of 20 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jekLD6IhhASLrcGFl:-M8jekLD6IhhASLrcGFm:b-5rdqan) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/distsql_physical_planner.go#L2295)):*
> ```Go
> ) (physPlan PhysicalPlan, err error) {
> 	if plan.physPlan != nil {
> 		return *plan.physPlan, nil
> ```

Could we change `createPhysPlan` to return a pointer?
___
*[pkg/sql/exec_util.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QCl8U-EeFhocVYYDs:-M8jaOX-2Bjo5zhrWfBo:b-xot695) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/exec_util.go#L257)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm still debating on what the naming should be: currently I have "experimental distsql planning", and that implies not only the spec creation but also actual distsql physical planning, probably it's acceptable, but then the scope of the project increases. I don't think we'll get to the "physical planning" part in the near term, but it might make sense to keep this naming as an aspirational goal.
</blockquote></details>

That's fine. What parts of physical planning are you referring to that we won't get to?
___
*[pkg/sql/exec_util.go, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jaLthErZO0sfjouiL:-M8jaLthErZO0sfjouiM:b7ze0j0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/exec_util.go#L259)):*
> ```Go
> var execBuilderDrivenDistSQLSpecCreationClusterMode = settings.RegisterBoolSetting(
> 	"sql.defaults.experimental_distsql_planning.enabled",
> 	"if set to true, enables experimental DistSQL spec creation driven by the execbuilder",
> ```

This is useful help text, should we keep it in?
___
*[pkg/sql/exec_util.go, line 933 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jf9JH11B4K_SM6vBJ:-M8jf9JH11B4K_SM6vBK:bp0u3t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/exec_util.go#L933)):*
> ```Go
> 	} else {
> 		var err error
> 		rec, err = checkSupportForPlanNode(plan.planNode)
> ```

is it worth it to change `checkSupport` to take in a `planMaybePhysical` similar to `createPlan`? 
___
*[pkg/sql/explain_distsql.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jfkbl6xtC5I2Xp2FX:-M8jfkbm9k1JrS8XRS7M:bmhn3gs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/explain_distsql.go#L79)):*
> ```Go
> 	plan planMaybePhysical,
> ) bool {
> 	if plan.physPlan == nil {
> ```

I think it would be nice to abstract this check behind a method (e.g. `isPhysicalPlan`)
___
*[pkg/sql/explain_plan.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jgjyNCtZXPUNyCEv0:-M8jgjyNCtZXPUNyCEv1:bxzm305) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/explain_plan.go#L299)):*
> ```Go
> 	if plan.main.physPlan != nil {
> 		return errors.AssertionFailedf(
> 			"EXPLAIN of a query with opt-driven DistSQL planning is not supported",
> ```

nit: `s/opt-driven/experimental` to be consistent, otherwise we should rename `experimental` everywhere else to `opt-driven experimental`. Maybe that'd be better since it's more specific.
___
*[pkg/sql/plan.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QG-Dz1IiSGEKPkPVP:-M8jhJ-nAm70owC8ZSqS:bxxx4gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan.go#L323)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

To me such an approach breaks an assumption that a `planNode` represents a single node in the tree because this new wrapper plan node would contain the whole physical plan at once, i.e. it would be a "meta" node.

I guess we could change the perspective a little and, instead, introduce a "plan-node-that-might-be-distsql-processor-spec" which would be the distsql spec for a single plan node and not the whole tree, but I don't know whether it'll be better.

This is one of those things that I learn by doing, and we're still laying out the plumbing before doing some meaningful work. From my point of view, it should be ok to merge something that moves us forward in the prototyping of this experimental planning (and doesn't break the normal flow), and we can iterate on the representation later.
</blockquote></details>

That makes sense.
___
*[pkg/sql/execbuilder_distsql_spec_factory.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QDcp5-E5NZyuTjnEr:-M8j_ozs82OwFn5djVAg:bobo70c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/execbuilder_distsql_spec_factory.go#L24)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I moved the file back into `pkg/sql` because currently `opt_exec_factory` is quite strongly coupled with that package, and I'm worried that moving the necessary pieces into a shared "base" package will be a little too much (for the moment).
</blockquote></details>

Yeah, I think having it in the `sql` package is the right move. Not sure it'll ever belong in `execbuilder`  TBH given the physical planning dependencies.


<!-- Sent from Reviewable.io -->

2020-06-01 21:58 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/distsql_physical_planner.go, line 2295 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jekLD6IhhASLrcGFl:-M8lsbnrCi99Iv6VapY3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/distsql_physical_planner.go#L2295)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we change `createPhysPlan` to return a pointer?
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QCl8U-EeFhocVYYDs:-M8lmoAW5CeoIQ53BNUQ:bjomvd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/exec_util.go#L257)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That's fine. What parts of physical planning are you referring to that we won't get to?
</blockquote></details>

I meant making more "optimal" decisions in terms of distribution of work rather than simply transitioning the logic (and the heuristics) we already have in `distsql_physical_planner`.
___
*[pkg/sql/exec_util.go, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jaLthErZO0sfjouiL:-M8lnQnW4fhFfgBu3UHD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/exec_util.go#L259)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is useful help text, should we keep it in?
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 933 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jf9JH11B4K_SM6vBJ:-M8lnUMp2cWsjgFKc4DI:bl6ssdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/exec_util.go#L933)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

is it worth it to change `checkSupport` to take in a `planMaybePhysical` similar to `createPlan`? 
</blockquote></details>

I'm still debating about this - I think ideally we should be able to call `ConstructPlan` that will return `planMaybePhysical` with the distribution recommendation set, so we would be "checking support" while constructing at the same time, so I'm inclined to keep this as `checkSupportForPlanNode` as legacy code and attempt to move away from it.
___
*[pkg/sql/explain_distsql.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jfkbl6xtC5I2Xp2FX:-M8loTTwBeks_E8juDGN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/explain_distsql.go#L79)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it would be nice to abstract this check behind a method (e.g. `isPhysicalPlan`)
</blockquote></details>

Done.
___
*[pkg/sql/explain_plan.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8jgjyNCtZXPUNyCEv0:-M8lpHPZBwJp2pQVIqhH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c1f9915a63b558e21216ab99082c985341fc328/pkg/sql/explain_plan.go#L299)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/opt-driven/experimental` to be consistent, otherwise we should rename `experimental` everywhere else to `opt-driven experimental`. Maybe that'd be better since it's more specific.
</blockquote></details>

Done.
___
*[pkg/sql/plan.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QG-Dz1IiSGEKPkPVP:-M8lq4gu5gALcPbqQ7Hm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ba4b383da24d9bf94eda1b32210b57854e282f/pkg/sql/plan.go#L323)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

That makes sense.
</blockquote></details>

Done.
___
*[pkg/sql/execbuilder_distsql_spec_factory.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8QDcp5-E5NZyuTjnEr:-M8lmbgfAcHWtFmWAURv:bo1z2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae2154711d3c2e09e19a39830045e5012a33fc4a/pkg/sql/execbuilder_distsql_spec_factory.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yeah, I think having it in the `sql` package is the right move. Not sure it'll ever belong in `execbuilder`  TBH given the physical planning dependencies.
</blockquote></details>

I think eventually we should be able to pull that into `execbuilder` once the optimizer is aware of the nodes' physical placement.


<!-- Sent from Reviewable.io -->

2020-06-02 10:20 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 16 of 16 files at r6, 14 of 14 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8oXtLj6ldND3y_6-Ek:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-06-02 12:38 UTC, rytaft reviewed
Sorry for the delay. Just taking a quick look at this now. I've looked at the first commit, checking the others now.

Some nits in the commit/PR message:
- There's no such thing as `opt.Tree`. 
- I don't understand this sentence: "Currently the fallback doesn't occur with `always` only for SELECT statements (so that we could run other statements types, like SET)." 
- "logical -> "logical"
- all processor spec -> all processor specs

> Reviewed 3 of 20 files at r4, 16 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8oxyOz6-EpWkXJOIVd:bmzawzr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 260 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-5cS-2gODKRGBbXm:-M8p-5cS-2gODKRGBbXn:b-cktv9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/exec_util.go#L260)):*
> ```Go
> // experimentalDistSQLPlanningClusterMode can be used to enable
> // optimizer-driven DistSQL planning that sidesteps intermediate planNode
> // transition when going from opt.Tree to DistSQL processor specs.
> ```

[nit] `opt.Tree` does not exist
___
*[pkg/sql/exec_util.go, line 267 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-TUC0Hd5QlXcHHzG:-M8p-TUDDxz-lvJauUSy:b-aib6oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/exec_util.go#L267)):*
> ```Go
> 	map[int64]string{
> 		int64(sessiondata.ExperimentalDistSQLPlanningOff): "off",
> 		int64(sessiondata.ExperimentalDistSQLPlanningOn):  "on",
> ```

Seems weird to have a different set of allowed values for the cluster setting than the session setting. Why not include "always" here?
___
*[pkg/sql/opt_exec_factory.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-et97eHzXDEz6VMM:-M8p-et97eHzXDEz6VMN:b-3l9h3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43d665a8de336f3856dd361b2c0035bbc48cdc4/pkg/sql/opt_exec_factory.go#L46)):*
> ```Go
> var _ exec.Factory = &execFactory{}
> 
> func makeExecFactory(p *planner) execFactory {
> ```

why did you change this?
___
*[pkg/sql/plan_opt.go, line 193 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p019l5MfPpeauJYeQ:-M8p019l5MfPpeauJYeR:b-bczhji) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/plan_opt.go#L193)):*
> ```Go
> 				// We use a simple heuristic to check whether the statement is
> 				// a SELECT, and the reasoning behind it is that we want to be
> 				// able to run certain statement types (e.g. SET) regardless of
> ```

This logic is a bit confusing. Why not just check if the statement is `SET`?


<!-- Sent from Reviewable.io -->

2020-06-02 12:50 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 14 of 14 files at r7, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8p3wR53IpUtrDuaN3m:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-06-02 14:31 UTC, yuzefovich reviewed
Addressed the nits in the commit messages.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-:-M8pRRFaE0uVsfbnEM2v:b-a0ve1u)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @rytaft)

___
*[pkg/sql/exec_util.go, line 260 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-5cS-2gODKRGBbXm:-M8pQHo65gTsThH-4ZDH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/exec_util.go#L260)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] `opt.Tree` does not exist
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 267 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-TUC0Hd5QlXcHHzG:-M8pN5AV38a5XF2CPimH:b-5ja8fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/exec_util.go#L267)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems weird to have a different set of allowed values for the cluster setting than the session setting. Why not include "always" here?
</blockquote></details>

I'm worried about the case of not supporting SET statements which would not allow to change the cluster setting from `always` easily once it is set. We had a similar issue with `vectorize` cluster setting, and if I remember correctly I had to do some manual system table manipulation to reset the cluster setting once it was set to `experimental_always`.
___
*[pkg/sql/opt_exec_factory.go, line 46 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p-et97eHzXDEz6VMM:-M8pP7UFCm3K8rq3okiH:b-sdr6fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43d665a8de336f3856dd361b2c0035bbc48cdc4/pkg/sql/opt_exec_factory.go#L46)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why did you change this?
</blockquote></details>

I think there is a convention that if the method returns a value, then `make` is used, but if it returns a pointer, then `new` is used. We've changed the signature to return a pointer, so I made the corresponding change to the method name. If the question is why change it to return a pointer - Alfonso asked why not, and I didn't have an explanation. In fact, in two places where this method is called we already where taking the pointer from the return value when using it.
___
*[pkg/sql/plan_opt.go, line 193 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49348#-M8p019l5MfPpeauJYeQ:-M8pPxPPCHzp5-Ouh1Z0:b-q45jn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f0777400bd9e3f23b841a38dab3f9c8d42bcff9/pkg/sql/plan_opt.go#L193)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This logic is a bit confusing. Why not just check if the statement is `SET`?
</blockquote></details>

That was my first attempt, but execution of `SET` statement behind the scenes involves an `INSERT` into a system table (and possibly other statement types), and at least for now the goal is supporting `kv` workload, so restricting to `SELECT` in particular seems reasonable.


<!-- Sent from Reviewable.io -->

2020-06-02 17:22 UTC, yuzefovich commented
TFTRs!

bors r+

2020-06-02 18:34 UTC, merged