roachtest: fix typo in tpchvec/perf
cockroachdb/cockroach pull request #49554
Opened 2020-05-26 16:00 UTC by yuzefovich

TPCH queries have semicolon at the end, so when trying to do `SELECT url
FROM [EXPLAIN ANALYZE %s];` with query replacing the `%s`, we would have
a semicolon within square brackets which would produce a syntax error.
Fix this by reading both `automatic` boolean and `url` string and
outputting the latter.

Release note: None

2020-05-26 16:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49554)
<!-- Reviewable:end -->

2020-05-26 16:33 UTC, asubiotto requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49554)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49554#-M8Gp1b42-zcMX0r5If0:-M8Gp1b42-zcMX0r5If1:bug6hrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/08536fdd0f291cfe86ae7501217cab673ad0f29f/pkg/cmd/roachtest/tpchvec.go#L270)):*
> ```Go
> 				for i := 0; i < tpchPerfTestNumRunsPerQuery; i++ {
> 					rows, err := conn.Query(fmt.Sprintf(
> 						"EXPLAIN ANALYZE %s;", tpch.QueriesByNumber[queryNum],
> ```

Does a double semi-colon matter? I would try this out by modifying it to always run EXPLAIN ANALYZE and running the roachtest locally to make sure it works so we avoid any other problems of this type.


<!-- Sent from Reviewable.io -->

2020-05-26 16:36 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49554)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49554#-M8Gp1b42-zcMX0r5If0:-M8Gpgpk0QN4OhiGW6qL:b1r8upr) ([raw file](https://github.com/cockroachdb/cockroach/blob/08536fdd0f291cfe86ae7501217cab673ad0f29f/pkg/cmd/roachtest/tpchvec.go#L270)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does a double semi-colon matter? I would try this out by modifying it to always run EXPLAIN ANALYZE and running the roachtest locally to make sure it works so we avoid any other problems of this type.
</blockquote></details>

I tried it out in the cli, and an extra semicolon didn't matter, but I'll run the roachtest to confirm that.


<!-- Sent from Reviewable.io -->

2020-05-26 19:48 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49554)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 270 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49554#-M8Gp1b42-zcMX0r5If0:-M8HWTbL72wzGdqoR45D:b-uctwfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/08536fdd0f291cfe86ae7501217cab673ad0f29f/pkg/cmd/roachtest/tpchvec.go#L270)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I tried it out in the cli, and an extra semicolon didn't matter, but I'll run the roachtest to confirm that.
</blockquote></details>

The manual run actually showed that there was a problem with closing of `rows` - initially I had `defer rows.Close()` which would leave `conn` in "unfinished" state because I do not call `rows.Next()` until it returns `false` - i.e. until exhaustion. I modified the code a bit, and then everything worked as expected.


<!-- Sent from Reviewable.io -->

2020-05-27 09:50 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49554#-:-M8KXdH85w2mguGZYq5f:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-05-28 00:35 UTC, yuzefovich commented
TFTR!

bors r+

2020-05-28 03:27 UTC, merged