ui: Error message for non-table data on Databases page
cockroachdb/cockroach pull request #49592
Opened 2020-05-27 13:20 UTC by koorosh

Partially resolves: #48152

Previously, error messages received on request for
non-table data on Databases page is not handled and not
displayed for users.

Now, default error message is shown in response to errors.

Release note (admin ui change): Show default error message
about restricted permissions for non-admin users on
Databases page.

Test cases to validate correct behavior:
- Databases page loads table info for a user with `admin` role
- Databases page shows the default error message with `insufficient rights` message for non-admin user.
- The loading indicator is displayed while response is not received.

2020-05-27 13:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49592)
<!-- Reviewable:end -->

2020-05-27 13:23 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.tsx
> +  renderTable = () => {
It is necessary to preserve the reference to `this` when passing function in props to `Loading` component.

2020-05-31 02:56 UTC, celiala commented
Hmm, I wonder if we should also hide the "Non-Table Cluster Data" header, since I'm not sure how valuable it it for the user to see that, given that they aren't seeing any data for "Table cluster data". 

But, I'll defer to whatever @piyush-singh and @dhartunian think. Fyi, this PR results in:
<img width="400" src="https://user-images.githubusercontent.com/3051672/83343366-58c94b00-a2c7-11ea-897c-1dcd786361e9.png">

But IMO I think it should be without the line and "Non-Table" header, i.e.:

<img width="400" src="https://user-images.githubusercontent.com/3051672/83343358-3e8f6d00-a2c7-11ea-9fc2-d63398ca2451.png">

2020-05-31 02:58 UTC, celiala requested changes
The code itself LGTM, modulo a few nits (noted inline)...

However, I have a request for the PR itself (this is for all PRs):

* For any UI-facing change, could you include screenshots of the change that you're making, so that it's easy to visually see what area this changes? Ideally a before/after screenshot, if it makes sense. Thanks!

(but let's also hold on the above, to see if Piyush/DavidH think the design should change, of course)

2020-05-31 02:58 UTC, celiala commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +    it ("successfully loads data", () => {
nit: remove space after `it`
```
    it("successfully loads...
```

2020-05-31 02:58 UTC, celiala commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +    it ("shows error message when failed request", () => {
nit: same
```javascript
    it("shows error...
```

2020-05-31 02:58 UTC, celiala commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.tsx
> +            />
nit: remove spaces
```javascript
            <Loading
              loading={!this.props.nonTableStats}
              error={this.props.lastError}
              render={this.renderTable}
            />
```

2020-06-01 13:11 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.tsx
> +            />
Done

2020-06-01 13:11 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +    it ("shows error message when failed request", () => {
Done

2020-06-01 13:11 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +    it ("successfully loads data", () => {
Done

2020-06-01 13:11 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +import {cockroach} from "src/js/protos";
Done

2020-06-01 13:11 UTC, koorosh commented on pkg/ui/src/views/databases/containers/databases/nonTableSummary.spec.tsx
> +import {noop} from "lodash";
Done

2020-06-01 13:14 UTC, koorosh commented
@celiala thank you for the feedback! Updated code with respect to all requested changes.

2020-06-02 05:19 UTC, celiala commented
Updating thread, based on offline (Slack) discussion:

I previously asked (above) whether or not to hide the "Non-Table Cluster Data" header if the "insufficient privileges". This evolved into an investigation around users with various privilege permutations, which evolved into a larger question of what should we show for users with _some_ data privileges.

We landed on keeping this PR/messaging as-is, and create a separate issue (#49782) to account for access to some, but not all, data on Databases page.

2020-06-02 05:19 UTC, celiala approved these changes
LGTM, thanks!

2020-06-02 10:15 UTC, koorosh commented
bors r+

2020-06-02 10:59 UTC, merged