sql: clean up of scanNode and some other things
cockroachdb/cockroach pull request #49724
Opened 2020-05-29 23:41 UTC by yuzefovich

**sql: move setting of isLocal of PlanningCtx into the constructors**

Release note: None

**sql: remove separate scanVisilibity struct**

This commit removes `sql.scanVisibility` in favor of protobuf-generated
`execinfrapb.ScanVisibility`. It also introduces prettier aliases for
the two values into `execinfra` package that are now used throughout the
code.

Release note: None

**sql: clean up of scan node and a few other things**

This commit does the following cleanups of `scanNode`:
1. refactors `scanNode.initCols` method to be standalone (it will
probably be reused later by distsql spec exec factory).
2. removes `numBackfillColumns`, `specifiedIndexReverse`, and
`isSecondaryIndex` fields since they are no longer used.
3. refactors the code to remove `valNeededForCols` field which was
always consecutive numbers in range `[0, len(n.cols)-1]`.
4. refactors `getIndexIdx` method to not depend on `scanNode`.

Additionally, this commit removes `planDependencies` business
from `planTop` since optimizer now handles CREATE VIEW and handles
the plan dependencies on its own (and CREATE VIEW was the single
user of that struct in the plan top).

Also, it removes (which seems like) unnecessary call to `planColumns`
when creating distinct spec and an unused parameter from
`createTableReaders` method.

Addresses: #47474.

Release note: None

2020-05-29 23:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/49724)
<!-- Reviewable:end -->

2020-06-01 11:08 UTC, asubiotto requested changes
> Reviewed 15 of 15 files at r1, 15 of 15 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/apply_join.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jONpr5WvwLcZiDGon:-M8jONpr5WvwLcZiDGoo:b3b5f8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/569d277d1a350a24bec48793852c51654a961a40/pkg/sql/apply_join.go#L264)):*
> ```Go
> 	planCtx := params.p.extendedEvalCtx.ExecCfg.DistSQLPlanner.newLocalPlanningCtx(params.ctx, evalCtx)
> 	// Always plan local.
> 	planCtx.isLocal = true
> ```

I don't think `newLocalPlanningCtx` sets this field. Maybe it should?
___
*[pkg/sql/conn_executor_exec.go, line 866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jUtrq41fQpqkUxhKm:-M8jUtrq41fQpqkUxhKn:b-1obu0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a704e94e42f8f28dc1b83fc0bea5a7729ac444/pkg/sql/conn_executor_exec.go#L866)):*
> ```Go
> 	var planCtx *PlanningCtx
> 	if distribute {
> 		planCtx = ex.server.cfg.DistSQLPlanner.NewPlanningCtx(ctx, evalCtx, planner.txn, distribute)
> ```

`NewPlanningCtx` calls `newLocalPlanningCtx`. We should be able to remove this `if distribute` check here and everywhere and have `NewPlanningCtx` behave identically to the old behavior
___
*[pkg/sql/distsql_physical_planner.go, line 3253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jVZh37bMlY9rHTW8W:-M8jVZh40zxJDDfopcSn:b-t1s34z) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a704e94e42f8f28dc1b83fc0bea5a7729ac444/pkg/sql/distsql_physical_planner.go#L3253)):*
> ```Go
> 	ctx context.Context, evalCtx *extendedEvalContext, txn *kv.Txn, distribute bool,
> ) *PlanningCtx {
> 	planCtx := dsp.newLocalPlanningCtx(ctx, evalCtx)
> ```

How about `if !distribute { return`?
___
*[pkg/sql/distsql_running_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jVq517r8pSp8s07oG:-M8jVq517r8pSp8s07oH:bpdykh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a704e94e42f8f28dc1b83fc0bea5a7729ac444/pkg/sql/distsql_running_test.go#L158)):*
> ```Go
> 
> 		evalCtx := p.ExtendedEvalContext()
> 		// We need distribute = true so that we executing the plan involves marshaling
> ```

nit: so that we executing the plan
___
*[pkg/sql/opt_exec_factory.go, line 2098 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jWKAHAG91bimbhA8u:-M8jWKAHAG91bimbhA8v:btr2zix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca8e0a229619bbe0a6a86771741ff28da2e4ae97/pkg/sql/opt_exec_factory.go#L2098)):*
> ```Go
> // identified by their ordinal position in the table schema.
> func makeScanColumnsConfig(table cat.Table, cols exec.TableColumnOrdinalSet) scanColumnsConfig {
> 	// Set visibility=publicAndNotPublicColumns, since all columns in the "cols"
> ```

nit: update comment further?
___
*[pkg/sql/scan.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jYjvo6LaicDcTK1sr:-M8jYjvo6LaicDcTK1ss:b-dzz6sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca8e0a229619bbe0a6a86771741ff28da2e4ae97/pkg/sql/scan.go#L362)):*
> ```Go
> 
> 	// Register the dependency to the planner, if requested.
> 	if planDeps != nil {
> ```

cc @raduberinde 


<!-- Sent from Reviewable.io -->

2020-06-01 14:07 UTC, RaduBerinde commented
___
*[pkg/sql/scan.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jYjvo6LaicDcTK1sr:-M8kCOyq1KSLH6w-7R_B:bss75uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca8e0a229619bbe0a6a86771741ff28da2e4ae97/pkg/sql/scan.go#L362)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

cc @raduberinde 
</blockquote></details>

Yes, this is no longer needed.


<!-- Sent from Reviewable.io -->

2020-06-01 21:19 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/apply_join.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jONpr5WvwLcZiDGon:-M8lgsQ67fNgogxfA1Yf:br83d2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/569d277d1a350a24bec48793852c51654a961a40/pkg/sql/apply_join.go#L264)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think `newLocalPlanningCtx` sets this field. Maybe it should?
</blockquote></details>

It does set the field.
___
*[pkg/sql/conn_executor_exec.go, line 866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jUtrq41fQpqkUxhKm:-M8liAty6U1E3heDjEdr:b6p8fpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a704e94e42f8f28dc1b83fc0bea5a7729ac444/pkg/sql/conn_executor_exec.go#L866)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`NewPlanningCtx` calls `newLocalPlanningCtx`. We should be able to remove this `if distribute` check here and everywhere and have `NewPlanningCtx` behave identically to the old behavior
</blockquote></details>

Yeah, I didn't refactor code all the way, done.
___
*[pkg/sql/distsql_physical_planner.go, line 3253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jVZh37bMlY9rHTW8W:-M8lis7W9ltgbatEr9aa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/74a704e94e42f8f28dc1b83fc0bea5a7729ac444/pkg/sql/distsql_physical_planner.go#L3253)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How about `if !distribute { return`?
</blockquote></details>

Done.
___
*[pkg/sql/opt_exec_factory.go, line 2098 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jWKAHAG91bimbhA8u:-M8lkAa9DBxzMHo-d75_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca8e0a229619bbe0a6a86771741ff28da2e4ae97/pkg/sql/opt_exec_factory.go#L2098)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: update comment further?
</blockquote></details>

Done.
___
*[pkg/sql/scan.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-M8jYjvo6LaicDcTK1sr:-M8lkDXHE50i_AsFvA_A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca8e0a229619bbe0a6a86771741ff28da2e4ae97/pkg/sql/scan.go#L362)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yes, this is no longer needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-06-02 10:15 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 23 of 23 files at r4, 17 of 17 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49724#-:-M8oWr8M4gQikL293jQS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-06-02 14:09 UTC, yuzefovich commented
TFTR!

bors r+

2020-06-02 16:02 UTC, merged