backupccl: move Statistics field outside of BackupManifest (and store it separately)
cockroachdb/cockroach pull request #49838
Opened 2020-06-03 17:28 UTC by Anzoteh96

Histograms and tables become a significant overhead to backup manifest files, so a separate
storage of these information will keep the backup manifest files in a reasonable amount of size
(while retrieving those stats data only as necessary).

Fixes #48719 

Release note: None

2020-06-06 14:56 UTC, miretskiy requested changes
Can you drop parenthesis in the commit title?

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-:-M94tUFsE4jtA340yZ-O:bbkx557)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup.proto, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M997Hiw4aCQ7Dp9N8iD:-M997Hiw4aCQ7Dp9N8iE:b-245668) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L113)):*
> ```protobuf
>   repeated string locality_kvs = 20 [(gogoproto.customname) = "LocalityKVs"];
>   repeated sql.stats.TableStatisticProto statistics = 21;
>   repeated string statsFiles = 23;
> ```

Perhaps rename to statistics_filenames?
___
*[pkg/ccl/backupccl/backup.proto, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9594bhEWZUcNOrK7gR:-M9594bhEWZUcNOrK7gS:b-a52v5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L139)):*
> ```protobuf
> }
> 
> // StatsTables contains an array of sql.stats.TableStatisticProto object.
> ```

Can you describe what this message is for?
___
*[pkg/ccl/backupccl/backup_planning.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M959TXf6pOvjzHp6puW:-M959TXf6pOvjzHp6puX:biymk9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L380)):*
> ```Go
> 					return err
> 				}
> 				tableStatistics := make([]*stats.TableStatisticProto, 0)
> ```

you can just do `var tableStatistics []*stats.TableStatisticProto`
___
*[pkg/ccl/backupccl/backup_planning.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M959zZPECHWU1ROAAvR:-M959zZPECHWU1ROAAvS:b-hku7vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L389)):*
> ```Go
> 				statsTablesByID = append(statsTablesByID, &statsTable)
> 				fName := fmt.Sprintf("%s_%d", BackupStatistics, tableDesc.GetID())
> 				statsFiles = append(statsFiles, fName)
> ```

 Having 3 arrays is a bit unwieldy.

I don't think you need to have statsFiles array at all.
You can generate the name below, when you iterate to emit those stats.

I think statsTablesByID is misnamed right now -- it's just an array; but
if you change it to 
statsTablesByID := make(map[sqlbase.ID]*StatsTable
then, here you can simply do:

  statsTablesByID[tableDesc.GetID()] = &StatsTable{Statistics: tableStatistics}
___
*[pkg/ccl/backupccl/backup_planning.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M94tozO-w8BHc5T-N8s:-M94tozO-w8BHc5T-N8t:bdjpd1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L403)):*
> ```Go
> 			encryptionPassphrase = []byte(passphrase)
> 		} else {
> 			fmt.Println(ok)
> ```

erroneous debug stuff?
___
*[pkg/ccl/backupccl/backup_planning.go, line 682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95aAETDzHp0_KSUgJ1:-M95aAETDzHp0_KSUgJ2:b-n4qgag) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L682)):*
> ```Go
> 		// We delay the writing to here as the 'encryption' value has been changed just earlier on.
> 		for ind, statsTable := range statsTablesByID {
> 			err := writeTableStatistics(ctx, defaultStore, statsFiles[ind], encryption, statsTable)
> ```

I'm not sure it's okay to write these files at this stage. 

We seem to be creating those statistics files even before the job starts running.
Should't the resumer be the one that writes this data?

Also, how many files are we talking about here?


@pbardea ?
___
*[pkg/ccl/backupccl/backup_test.go, line 2887 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98tu2PCfyblzFDcJIJ:-M98tu2PCfyblzFDcJIK:b5eupzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2887)):*
> ```
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> ```
require.NoError(t, err)
___
*[pkg/ccl/backupccl/backup_test.go, line 2889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98u6UM5rEQBAvgHL0d:-M98u6UM5rEQBAvgHL0e:bqgtaxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2889)):*
> ```Go
> 	}
> 	for _, f := range files {
> 		fName := f.Name()
> ```

why have this alias? it's only 3 characters shorter.. Just use f.Name() perhaps?
___
*[pkg/ccl/backupccl/backup_test.go, line 2891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98u3Wx82Jf7a43xQxE:-M98u3Wx82Jf7a43xQxF:baurxw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2891)):*
> ```Go
> 		fName := f.Name()
> 		if partitionMatcher.MatchString(fName) {
> 			statsFile := subDir + "/" + fName
> ```

path.Join(...)
___
*[pkg/ccl/backupccl/backup_test.go, line 2895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98tyFA2wmwjTcqX2co:-M98tyFA2wmwjTcqX2cp:b-95lw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2895)):*
> ```
> 			if err != nil {
> 				t.Fatal(err)
> 			}
> ```
require.NoError(t, err)
___
*[pkg/ccl/backupccl/manifest_handling.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95Y1e2BCSUY4XMh4kI:-M95Y1e2BCSUY4XMh4kJ:b-xh7ib1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L55)):*
> ```Go
> 	// BackupStatistics is the file name used to store the table statistics
> 	// after moving the table stats out.
> 	BackupStatistics = "BACKUP-STATISTICS"
> ```

maybe rename to  BackupStatisticsFileName?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98uCNeEquVIBCHMwBG:-M98uCNeEquVIBCHMwBH:bbw5zez) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L243)):*
> ```Go
> 	filename string,
> 	encryption *roachpb.FileEncryptionOptions,
> ) (StatsTable, error) {
> ```

should you return *StatsTable instead?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M996aLE32ba-EY_q2br:-M996aLE32ba-EY_q2bs:bk3312e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L615)):*
> ```Go
> func loadSQLDescsFromBackupsAtTime(
> 	backupManifests []BackupManifest, asOf hlc.Timestamp,
> ) ([]sqlbase.Descriptor, BackupManifest, int) {
> ```

i'm not a fan of returning an int.. no idea what it actually means.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98uRiG7x4iwsWT9LYw:-M98uRiG7x4iwsWT9LYx:bhhprrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L618)):*
> ```Go
> 	lastBackupManifest := backupManifests[len(backupManifests)-1]
> 
> 	lastInd := len(backupManifests) - 1
> ```

rename to lastIndex?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 629 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98ucWTAg-mg31gvqI-:-M98ucWTAg-mg31gvqI0:b6gi6uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L629)):*
> ```Go
> 		}
> 		lastBackupManifest = b
> 		 [...]

2020-06-06 14:57 UTC, miretskiy requested changes
I think the PR description should be expanded.

2020-06-07 19:08 UTC, pbardea requested changes
Getting there with this first pass - I think there are things that can be cleaned up a bit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-:-M9F9wyl7B1fc67v16Fl:b-f3pybs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup.proto, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9F9dYKDsV0S7KkV3ie:-M9F9dYKDsV0S7KkV3if:b-z0nx3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L112)):*
> ```protobuf
>   repeated string partition_descriptor_filenames = 19;
>   repeated string locality_kvs = 20 [(gogoproto.customname) = "LocalityKVs"];
>   repeated sql.stats.TableStatisticProto statistics = 21;
> ```

Can you add a comment here saying that this field is used by backups created in 19.2 and 20.1 which store all of the table statistics in this field and that later versions now write the table statistics to a separate file indicated by the `table_statistic_files` field?
___
*[pkg/ccl/backupccl/backup.proto, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95KCPJ7BK0lQ47R-yL:-M95KCPJ7BK0lQ47R-yM:b5v57a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L113)):*
> ```protobuf
>   repeated string locality_kvs = 20 [(gogoproto.customname) = "LocalityKVs"];
>   repeated sql.stats.TableStatisticProto statistics = 21;
>   repeated string statsFiles = 23;
> ```

I think it would be useful to store this as a:
```
  map<uint32, string> table_statistic_files = 23 [
    (gogoproto.castkey) = "github.com/cockroachdb/cockroach/pkg/sql/sqlbase.ID"
  ];
```
so that in the future if we want to patitiono the file which stores the table stats into smaller files we have the flexibility of being backwards compatible.
___
*[pkg/ccl/backupccl/backup.proto, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9C8KE0EtVOBxXeLkvo:-M9C8KE0EtVOBxXeLkvp:bxvsx10) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L141)):*
> ```protobuf
> // StatsTables contains an array of sql.stats.TableStatisticProto object.
> message StatsTable {
>   repeated sql.stats.TableStatisticProto statistics = 2;
> ```

The ID here can just be `= 1`.
___
*[pkg/ccl/backupccl/backup_planning.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M959zZPECHWU1ROAAvR:-M9F8e3I9DsX7uBRaJ0k:bp2yf2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L389)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

 Having 3 arrays is a bit unwieldy.

I don't think you need to have statsFiles array at all.
You can generate the name below, when you iterate to emit those stats.

I think statsTablesByID is misnamed right now -- it's just an array; but
if you change it to 
statsTablesByID := make(map[sqlbase.ID]*StatsTable
then, here you can simply do:

  statsTablesByID[tableDesc.GetID()] = &StatsTable{Statistics: tableStatistics}

</blockquote></details>

Alternatively, I think it would also be fine to write all of the statistics to 1 file (`BACKUP-STATISTICS`), since this is basically what we do now, with a TODO to investigate more saying something like:
`TODO: It may be beneficial to write out the stats for each table in their own file, but it may be inefficient to write out many files if they are all tiny. We should investigate if this tradeoff is worthwhile.`

Also, separate from your changes, I think that the table stats should also be collected during the job - I don't see any reason to collect them via planning (this was the doing of my past self). I think we can move all of this to the backup_job, before we actually backup the data. If something goes wrong here I'd like to know before backing up a large amount of data, rather than after.
___
*[pkg/ccl/backupccl/backup_planning.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9F9Zl03YESr3UgcTXw:-M9F9Zl16nyYt64_7YhG:bvpcm1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L623)):*
> ```Go
> 			NodeID:             nodeID,
> 			ClusterID:          p.ExecCfg().ClusterID(),
> 			Statistics:         nil,
> ```

I think we can just remove this line.
___
*[pkg/ccl/backupccl/backup_planning.go, line 682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95aAETDzHp0_KSUgJ1:-M9C8elCDXrzS-lEs8Ac:b-h4qcee) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L682)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure it's okay to write these files at this stage. 

We seem to be creating those statistics files even before the job starts running.
Should't the resumer be the one that writes this data?

Also, how many files are we talking about here?


@pbardea ?
</blockquote></details>

Yep - we'd want to move the writing here to the job portion (in `backup_job.go`) rather than during backup planning. 

I also think that for now we can just write all of the stats to 1 file. This is safer in the short term to ensure we're not writing a crazy amount of files. See my comment above.
___
*[pkg/ccl/backupccl/backup_test.go, line 2866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9Eyogv1RfInGYIoi4C:-M9Eyogv1RfInGYIoi4D:b-d7ch0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2866)):*
> ```Go
> }
> 
> func TestStatsEncrypted(t *testing.T) {
> ```

It may be easier to just add a check that the `BACKUP-STATISTICS` file is encrypted by extending `TestBackupEncrypted` rather than adding an new test just for this? That way, checking that the backup is encrypted is all tested in 1 central place.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95Y1e2BCSUY4XMh4kI:-M9C8zgv-JvuiLZibhYX:bp7xb9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L55)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe rename to  BackupStatisticsFileName?
</blockquote></details>

+1 to the rename. I also think we can update the comment above it as "moving the table stats out" may not make sense to others after this change is merged. I think the comment should read something like:
```
// BackupStatisticsFileName is the file name used to store the serialized table statistics for the tables being backed up.
```
___
*[pkg/ccl/backupccl/manifest_handling.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9Ezcqu5Z-fNqY8LAuB:-M9Ezcqu5Z-fNqY8LAuC:bcs4db) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L324)):*
> ```Go
> 
> // writeTableStatistics writes a StatsTable object to one of the
> // stores in the backup.
> ```

This comment implies that each backup has multiple stores. Although this may be true for a locality-aware backup, I think the comment may be confusing in the future. If we're going to add a comment here, I think I would phrase this as something like: "writeTableStatistics writes a StatsTable object to a file with a given filename to the specified exportStore. It will be encrypted, depending on the provided encryption options provided."
___
*[pkg/ccl/backupccl/manifest_handling.go, line 615 at r1](https://reviewable.io/reviews/cockroac [...]

2020-06-07 20:56 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-M9FWqeGECYIxDAsvbEZ:bpgtfsj) (no related file):*
Partial changes (mostly the small nits) according to the comments. Still pending the structural changes like moving the collection of stats files from backup planning to backup job, getting rid of the `lastInd` (will implement what Paul suggests: returning the relevant URI), and moving the `encrypted stats file` into a subtest. 

---
___
*[pkg/ccl/backupccl/backup.proto, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9F9dYKDsV0S7KkV3ie:-M9FTtm-2tCb6Iv7yzRY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L112)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can you add a comment here saying that this field is used by backups created in 19.2 and 20.1 which store all of the table statistics in this field and that later versions now write the table statistics to a separate file indicated by the `table_statistic_files` field?
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup.proto, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M997Hiw4aCQ7Dp9N8iD:-M9FTvZfB0PX3GU5DgGl:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L113)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps rename to statistics_filenames?
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup.proto, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95KCPJ7BK0lQ47R-yL:-M9FTx8uCpMPpZLXp_i1:bfi3b4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L113)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think it would be useful to store this as a:
```
  map<uint32, string> table_statistic_files = 23 [
    (gogoproto.castkey) = "github.com/cockroachdb/cockroach/pkg/sql/sqlbase.ID"
  ];
```
so that in the future if we want to patitiono the file which stores the table stats into smaller files we have the flexibility of being backwards compatible.
</blockquote></details>

Done (however, we now only have one file, so this map only has one key-value pair for now). 
___
*[pkg/ccl/backupccl/backup.proto, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9594bhEWZUcNOrK7gR:-M9FU6nyCd73F90ajOH5:beq1612) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L139)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Can you describe what this message is for?
</blockquote></details>

Done (expanded the description a bit)
___
*[pkg/ccl/backupccl/backup.proto, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9C8KE0EtVOBxXeLkvo:-M9FUBLU6c2SK8DKC6M5:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L141)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

The ID here can just be `= 1`.
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_planning.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M94tozO-w8BHc5T-N8s:-M9FUMiG-6IT3UpAwmFS:b-e9hnm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L403)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

erroneous debug stuff?
</blockquote></details>

Done (removed)
___
*[pkg/ccl/backupccl/backup_planning.go, line 623 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9F9Zl03YESr3UgcTXw:-M9FUbEwC-cJtmA3XBut:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L623)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think we can just remove this line.
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 2887 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98tu2PCfyblzFDcJIJ:-M9FUg5E2pfMmcPVObJN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2887)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	if err != nil {
> 		t.Fatal(err)
> 	}
> ```
require.NoError(t, err)
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 2889 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98u6UM5rEQBAvgHL0d:-M9FVSWU2E9FvDdML1DU:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2889)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why have this alias? it's only 3 characters shorter.. Just use f.Name() perhaps?
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 2891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98u3Wx82Jf7a43xQxE:-M9FVTqDADbhcs46ici_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2891)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

path.Join(...)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_test.go, line 2895 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98tyFA2wmwjTcqX2co:-M9FVU_JATMVnUeaYoU2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2895)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 			if err != nil {
> 				t.Fatal(err)
> 			}
> ```
require.NoError(t, err)
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95Y1e2BCSUY4XMh4kI:-M9FV_z_7tEc5cglwjBA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L55)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

+1 to the rename. I also think we can update the comment above it as "moving the table stats out" may not make sense to others after this change is merged. I think the comment should read something like:
```
// BackupStatisticsFileName is the file name used to store the serialized table statistics for the tables being backed up.
```
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98uCNeEquVIBCHMwBG:-M9FVbpZAP2t7e2czAqH:b-1b1xza) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L243)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should you return *StatsTable instead?
</blockquote></details>

Looks like other functions (readBackupManifest / readBackupPartitionDescriptor) also return the object instead of the pointer so I'm just following for consistenc [...]

2020-06-08 17:26 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-M9Jwm6nA2rfv9xHYcn-:b-qou0gu) (no related file):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Partial changes (mostly the small nits) according to the comments. Still pending the structural changes like moving the collection of stats files from backup planning to backup job, getting rid of the `lastInd` (will implement what Paul suggests: returning the relevant URI), and moving the `encrypted stats file` into a subtest. 
</blockquote></details>

Update: got around the `lastInd` problem (although this might not be the intended solution), and moved `encrypted stats file` into a subtest. Pending: move the collection of stats files from backup planning to backup job, and clean up `remapRelevantStatistics`. 

---
___
*[pkg/ccl/backupccl/backup_planning.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M959TXf6pOvjzHp6puW:-M9JuyM13wnPf_PWVd1O:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L380)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you can just do `var tableStatistics []*stats.TableStatisticProto`
</blockquote></details>

Done
___
*[pkg/ccl/backupccl/backup_test.go, line 2866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9Eyogv1RfInGYIoi4C:-M9Jv6a8ChlQ8H8oX_bF:b519op3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_test.go#L2866)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It may be easier to just add a check that the `BACKUP-STATISTICS` file is encrypted by extending `TestBackupEncrypted` rather than adding an new test just for this? That way, checking that the backup is encrypted is all tested in 1 central place.
</blockquote></details>

Made that a subtest of `TestBackupEncrypted` by checking that the stats files of relevant directories are encrypted (those with encryption option being passed in). 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M996aLE32ba-EY_q2br:-M9JvRGx9erJtQRPjxJ-:bwz2rr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L615)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Ya, this method is really doing 2 things and I think it would benefit from being separated into 2 methods that each do a single thing. First, a method (something like `findBackupAtTimestamp`) finds the relevant backup given an AOST timestamp from the list of backupManifests. I think this should be it's own method and should return the relevant index. A second method (something like `loadSQLDescsFromBackup`) should take a single backup manifest and return the sql descriptors from the backup.
</blockquote></details>

I used a helper function `getBackupIndAtTime` to get rid of returning of an int at other places (admittedly, this helper function returns an int), but we don't need to return an int within other functions and instead, just call `getBackupIndAtTime` in the `restoreResumer.Resume` function when we need to get the relevant `URI`. 
___
*[pkg/ccl/backupccl/restore_job.go, line 764 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9974c13KyCOZ5OEgE3:-M9Jw7Y25nK_o6MdeG96:btigpx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/restore_job.go#L764)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think for now we can just return `details.URIs[lastBackupIndex]`, rather than the index of the last backup - since that's what we're after.

I think these methods that return a lot of things is kind of a code-smell that they're trying to do too much. Could you also add a todo along the lines of: `TODO: This method is now returning a lot of separate items and should be broken into one that finds the relevant backup manifest, and others which load descriptors from a given manifest.` I don't think this refactor should block this PR.

</blockquote></details>

Done (added the TODO). 


<!-- Sent from Reviewable.io -->

2020-06-09 01:13 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-M9LcevK1MMNKyxRmpwV:b-5vt7hl) (no related file):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Update: got around the `lastInd` problem (although this might not be the intended solution), and moved `encrypted stats file` into a subtest. Pending: move the collection of stats files from backup planning to backup job, and clean up `remapRelevantStatistics`. 
</blockquote></details>

Update: just moved the collection of stats files from backup planning to backup job, and cleaned up `remapRelevantStatistics`. Ready for another review! 

---
___
*[pkg/ccl/backupccl/backup_planning.go, line 682 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M95aAETDzHp0_KSUgJ1:-M9Lc7Ja0PWkNplyWxmi:b8v0gwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L682)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep - we'd want to move the writing here to the job portion (in `backup_job.go`) rather than during backup planning. 

I also think that for now we can just write all of the stats to 1 file. This is safer in the short term to ensure we're not writing a crazy amount of files. See my comment above.
</blockquote></details>

It's in the `backupResumer.Resume` now (instead of the `backupPlanHook` function). The only tricky part is that the `StatisticsFilenames` of a backup manifest is initialized at the `backupPlanHook` stage, because it might be tricky to do that in the `backupResumer.Resume`. 
___
*[pkg/ccl/backupccl/manifest_handling.go, line 618 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98uRiG7x4iwsWT9LYw:-M9Lbdli8pkEaHAA_dkH:b-ivk99k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L618)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think I would push this further to `lastBackupIndex` since it really is the index of the last backup before the given time.
</blockquote></details>

(It's now in a helper function :) )
___
*[pkg/ccl/backupccl/restore_job.go, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9CATXj04i7w4IQWceG:-M9LbmK7EeN7Jk8NQ5pO:b-jylrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/restore_job.go#L805)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think the function should just operate on the relevant statistics. Now that the table statitics are not always in the backup manifest, I think that there are a couple of things we can do here:
1. I think it would be nicer if we made a method which was responsible for getting the table statitics from a backup file. This method would be responsible for determining if the statistics were in the backup manfiest or in a seperate file.
2. `remapRelevantStatistics` would be a function that would just take table statistics and a table rewrite map, and would return the remapped statistics.

I think this would remove the weirdness of passing in an external store to a function that should only be responsible for remapping a protobuf. Additionally, it would help us avoid some of the code duplication below.
</blockquote></details>

I've split that into two functions: `getStatisticsFromBackup` and `remapRelevantStatistics` (the later simply takes a `BackupManifest` object and performs the remapping). 


<!-- Sent from Reviewable.io -->

2020-06-09 14:43 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup.proto, line 112 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9LeI8nA9w6evJMqEQ6:-M9LeI8nA9w6evJMqEQ7:b-jy1bhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup.proto#L112)):*
> ```protobuf
>   repeated string partition_descriptor_filenames = 19;
>   repeated string locality_kvs = 20 [(gogoproto.customname) = "LocalityKVs"];
>   // This field is used by backups in 10.2 and 20.1 where a backup manifest stores all the table
> ```

`s/10.2/19.2`
___
*[pkg/ccl/backupccl/backup_job.go, line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9OIqDh1OZLreoexvUQ:-M9OIqDh1OZLreoexvUR:b-xfugcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup_job.go#L566)):*
> ```Go
> 			// TODO: look into the tradeoffs of having all objects in the array to be in the same file,
> 			// vs having each object in a separate file, or somewhere in between.
> 			if len(statsFiles) == 0 {
> ```

My concern is that if we only write an entry for the first table that we'll see, if we later decide to separate the stats out to different files we'll still need to special case this logic to know that if there's only 1 key-value pair (even if it's one not for the table you're restoring). I think just having all of the tables present in this map, and all of them pointing to the same string would be best with respect for future proofing.

Also, considering that we're already storing the entire descriptor for each table, I don't think a few bytes to store an extra string for each of them will have a relatively small impact on the file size if that's a concern.
___
*[pkg/ccl/backupccl/backup_planning.go, line 373 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9OWzy91kQYxHjXJpvO:-M9OWzy91kQYxHjXJpvP:b-j0acja) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup_planning.go#L373)):*
> ```Go
> 				// TODO: look into the tradeoffs of having all objects in the array to be in the same file,
> 				// vs having each object in a separate file, or somewhere in between.
> 				if len(statsFiles) == 0 {
> ```

See my other comment about this.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 614 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9Lftti1VtTqgCDVAJm:-M9Lftti1VtTqgCDVAJn:b-w2lb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/manifest_handling.go#L614)):*
> ```Go
> }
> 
> func getBackupIndAtTime(backupManifests []BackupManifest, asOf hlc.Timestamp) int {
> ```

Can we call this `getBackupIndexAtTime`?
___
*[pkg/ccl/backupccl/restore_job.go, line 983 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9ORyyP1jv7gxHvq7-5:-M9ORyyP1jv7gxHvq7-6:bxh7vv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/restore_job.go#L983)):*
> ```
> lastInd 
> ```
Can we call this `lastBackupIndex`?


<!-- Sent from Reviewable.io -->

2020-06-09 17:30 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup.proto, line 112 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9LeI8nA9w6evJMqEQ6:-M9P4sh9B9jaKIbaWIds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup.proto#L112)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

`s/10.2/19.2`
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_job.go, line 566 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9OIqDh1OZLreoexvUQ:-M9P4wCV4AAfYI9I2GEw:bex7max) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup_job.go#L566)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

My concern is that if we only write an entry for the first table that we'll see, if we later decide to separate the stats out to different files we'll still need to special case this logic to know that if there's only 1 key-value pair (even if it's one not for the table you're restoring). I think just having all of the tables present in this map, and all of them pointing to the same string would be best with respect for future proofing.

Also, considering that we're already storing the entire descriptor for each table, I don't think a few bytes to store an extra string for each of them will have a relatively small impact on the file size if that's a concern.
</blockquote></details>

Done. (However, when recovering it during the `restore` stage, we'll need to identify only the list of the unique file names in the `StatisticsFilenames` field. 
___
*[pkg/ccl/backupccl/backup_planning.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M959zZPECHWU1ROAAvR:-M9P6hmu9m2nJbdcFA4C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup_planning.go#L389)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Alternatively, I think it would also be fine to write all of the statistics to 1 file (`BACKUP-STATISTICS`), since this is basically what we do now, with a TODO to investigate more saying something like:
`TODO: It may be beneficial to write out the stats for each table in their own file, but it may be inefficient to write out many files if they are all tiny. We should investigate if this tradeoff is worthwhile.`

Also, separate from your changes, I think that the table stats should also be collected during the job - I don't see any reason to collect them via planning (this was the doing of my past self). I think we can move all of this to the backup_job, before we actually backup the data. If something goes wrong here I'd like to know before backing up a large amount of data, rather than after.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_planning.go, line 373 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9OWzy91kQYxHjXJpvO:-M9P6cxN04Pwz_FM62WL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/backup_planning.go#L373)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

See my other comment about this.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 614 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9Lftti1VtTqgCDVAJm:-M9P6oDD4KoAOfh9D0QH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/manifest_handling.go#L614)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we call this `getBackupIndexAtTime`?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 983 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9ORyyP1jv7gxHvq7-5:-M9P6ris8U9tDM0jU0An:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30a80d167ec51cf79c8b48ca1e8c1e7decc4a44a/pkg/ccl/backupccl/restore_job.go#L983)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

> ```
> lastInd 
> ```
Can we call this `lastBackupIndex`?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-M9P6ydH-_LnjMF89tan:bnmodk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
> ```Go
> 	}
> 	tableStatistics := make([]*stats.TableStatisticProto, 0, len(backup.Statistics))
> 	uniqueFileNames := make(map[string]bool)
> ```

Note: this is the code that retrieves only the unique filenames in `backup.StatisticsFilenames`. 


<!-- Sent from Reviewable.io -->

2020-06-10 14:10 UTC, pbardea approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-M9TY_NQ8I5szxtaGN8J:bi079q6) (no related file):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Update: just moved the collection of stats files from backup planning to backup job, and cleaned up `remapRelevantStatistics`. Ready for another review! 
</blockquote></details>

Nice! This LGTM mod some small comments.

---
___
*[pkg/ccl/backupccl/backup.proto, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9594bhEWZUcNOrK7gR:-M9TX1nzAgyFd-eegey2:b-xx5rcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/backup.proto#L139)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Done (expanded the description a bit)
</blockquote></details>

nit: `s/moved out/stored separately from the backup manifest`
___
*[pkg/ccl/backupccl/manifest_handling.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M98uCNeEquVIBCHMwBG:-M9TXN0nBMVTDJLkEGr3:bxw1ps2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d98ea2ef07aa119c70c5e4e381a98d0b625ab88/pkg/ccl/backupccl/manifest_handling.go#L243)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Looks like other functions (readBackupManifest / readBackupPartitionDescriptor) also return the object instead of the pointer so I'm just following for consistency. 
</blockquote></details>

I'm not sure those methods have much of a good reason to return the entire struct rather than the pointer.
___
*[pkg/ccl/backupccl/restore_job.go, line 983 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9TXw_SA-Cxh8Xyfq3s:-M9TXw_SA-Cxh8Xyfq3t:bq5qo8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a981d5ed94707e3091763de54e3aa6bab97d206f/pkg/ccl/backupccl/restore_job.go#L983)):*
> ```Go
> 
> 	// The lastInd information is needed to know the index of latestBackUpManifest
> 	// in order to retrieve the corresponding URI.
> ```

I'm not sure we need this comment anymore, now the code is pretty clear on why we need the `lastBackupIndex` since we use it just a few lines after retrieving it.


<!-- Sent from Reviewable.io -->

2020-06-16 18:27 UTC, pbardea commented
I think this is looking pretty good - @miretskiy, did you want to take another quick pass?

2020-06-17 13:24 UTC, miretskiy commented
Thanks.  Taking a look now.

On Tue, Jun 16, 2020 at 2:28 PM Paul Bardea <notifications@github.com>
wrote:

> I think this is looking pretty good - @miretskiy
> <https://github.com/miretskiy>, did you want to take another quick pass?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/49838#issuecomment-644936795>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANA4FVEPAACTQZ2MWXRVWMDRW62TTANCNFSM4NR33O3Q>
> .
>

2020-06-17 14:21 UTC, miretskiy requested changes
> Reviewed 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96)

___
*[pkg/ccl/backupccl/backup_job.go, line 353 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1L4QcAlkpAdc6LVmT:-MA1L4QcAlkpAdc6LVmU:bak4dv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L353)):*
> ```Go
> 	for _, desc := range backupManifest.Descriptors {
> 		if tableDesc := desc.Table(hlc.Timestamp{}); tableDesc != nil {
> ```

drop extra \n?
___
*[pkg/ccl/backupccl/backup_job.go, line 359 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1b5XF09MRPbDnIqjF:-MA1b5XF09MRPbDnIqjG:b8v4aay) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L359)):*
> ```Go
> 				return RowCount{}, err
> 			}
> 			for i := range tableStatisticsAcc {
> ```

maybe use 2 variable version of the range loop?

for _, stat := range tableStatisticsAcc {
  tableStatistics = append(tableStatistics, &stat.TableStatisticProto)
}
___
*[pkg/ccl/backupccl/backup_job.go, line 490 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1d7KM9wyYQr4qOA9O:-MA1d7KM9wyYQr4qOA9P:bcx5eqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L490)):*
> ```Go
> 		p.ExecCfg().DistSQLSrv.ExternalStorage,
> 		details.Encryption,
> 		statsCache,
> ```

probably okay to leave for this version; but we are getting to 14 arguments to a function.
That's probably an indication that things needs to be refactored a bit.

I am noticing however, that we do pass in 4 fields from execfg to this function, plus the actual p... So, we can probably eliminate those explicit args.

@pbardea  wdyt?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 617 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1N95rA42wPJMdjYrs:-MA1N95rA42wPJMdjYrt:bo9vkab) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L617)):*
> ```Go
> 
> // TODO(anzoteh96): benchmark the performance of different search algorithms,
> // e.g.  linear search, binary search, reverse linear search.
> ```

personally, i'd drop this todo.  backupManifest list is small.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 619 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1P3QnCBzqoL3oPTTA:-MA1P3QnCBzqoL3oPTTB:b-t2vnix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L619)):*
> ```Go
> // e.g.  linear search, binary search, reverse linear search.
> func getBackupIndexAtTime(backupManifests []BackupManifest, asOf hlc.Timestamp) int {
> 	backupManifestIndex := len(backupManifests) - 1
> ```

It does appear that this function cannot be called with empty backup manifests.
Does it make sense to be defensive about this (panic, or return an error either here or at this functions call site)?
___
*[pkg/ccl/backupccl/manifest_handling.go, line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1NGsH32leIcCWnpNW:-MA1NGsH32leIcCWnpNX:b78kqaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L620)):*
> ```Go
> func getBackupIndexAtTime(backupManifests []BackupManifest, asOf hlc.Timestamp) int {
> 	backupManifestIndex := len(backupManifests) - 1
> 	if asOf.IsEmpty() {
> ```

Is this a common case?  If not, then perhaps don't even bother having this special case.

Also, are backup manifests sorted in timestamp order?  
if so, this method can be written as:

if index := sort.Search(len(backupManifest), func(i int) bool {return asOf.Less(backupManifests[i]}); index >=0 {
   return index
}
return len(backupManifest)-1
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA1_HWd7Z80crnW9T4u:b-wwizyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Note: this is the code that retrieves only the unique filenames in `backup.StatisticsFilenames`. 
</blockquote></details>

Is having non-unique statistics filenames expected? 
___
*[pkg/ccl/backupccl/restore_job.go, line 760 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1LsbNDslHBKreWcxy:-MA1LsbNDslHBKreWcxz:b-2o6x32) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L760)):*
> ```Go
> // skip_missing_foreign_keys was set, we should have aborted the RESTORE and
> // returned an error prior to this.
> // TODO(anzoteh96): this method returns two things: the sqlbase.Descriptor
> ```

doesn't this method return more than two things?
___
*[pkg/ccl/backupccl/restore_job.go, line 818 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1QkpD7K31rniMF0QU:-MA1QkpD7K31rniMF0QV:b73oye9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L818)):*
> ```Go
> ) []*stats.TableStatisticProto {
> 	if backup.Statistics != nil {
> 		return backup.Statistics
> ```

Do we expect this method to be called multiple times?  I don't see in the resumer anything that would initialize this field multiple times.  Am I missing something?
___
*[pkg/ccl/backupccl/restore_job.go, line 820 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1REQWEnobZrXVqwn4:-MA1REQWEnobZrXVqwn5:biu1ggs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L820)):*
> ```Go
> 		return backup.Statistics
> 	}
> 	tableStatistics := make([]*stats.TableStatisticProto, 0, len(backup.Statistics))
> ```

I'm confused.  We have a check above "if backup.Statistics != nil {return}".
So, here, we have backup.Statistics == nil, therefore len(backup.Statistics) is known to be 0.
Why then do this long hand initialization?  
___
*[pkg/ccl/backupccl/restore_job.go, line 825 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1RWg93q5IdrhICRZT:-MA1RWg93q5IdrhICRZU:b-rukq1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L825)):*
> ```Go
> 		uniqueFileNames[fname] = struct{}{}
> 	}
> 	for fname := range uniqueFileNames {
> ```

Combine those 2 loops.  There is no reason to iterate through file names twice.  Instead:

for fname := range bakcup.StatisticsFilenames {
  if _, exists := uniqueFileNames[fmane]; !exists {
     uniqueFileNames[fname] = struct{}{}
    ... rest of this loop body
  }
}
___
*[pkg/ccl/backupccl/restore_job.go, line 828 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1Zm1o6O-51KpdDsLp:-MA1Zm1o6O-51KpdDsLq:b8q6dne) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L828)):*
> ```Go
> 		myStatsTable, err := readTableStatistics(ctx, exportStore, fname, encryption)
> 		if err != nil {
> 			return tableStatistics
> ```

Why are we swallowing error here?  If this is a right thing to do, thenit needs an explanation why.
___
*[pkg/ccl/backupccl/restore_job.go, line 854 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1_iQbB-69LJ336kK0:-MA1_iQbB-69LJ336kK1:b3qgpsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L854)):*
<details><summary><i alt="summary">Quote [...]

2020-06-17 15:10 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @miretskiy)

___
*[pkg/ccl/backupccl/backup_job.go, line 490 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1d7KM9wyYQr4qOA9O:-MA1gwqqEgRTsqxtEKaw:b-udrmti) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L490)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

probably okay to leave for this version; but we are getting to 14 arguments to a function.
That's probably an indication that things needs to be refactored a bit.

I am noticing however, that we do pass in 4 fields from execfg to this function, plus the actual p... So, we can probably eliminate those explicit args.

@pbardea  wdyt?
</blockquote></details>

Yep - a lot of these methods have grown unwieldy. I think it's fine to leave this for this PR but we can clean this up quite a bit.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 617 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1N95rA42wPJMdjYrs:-MA1oEFk0kgChNiKHkYy:bon9e9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L617)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

personally, i'd drop this todo.  backupManifest list is small.
</blockquote></details>

Ya, we chatted about this and thought that it may be larger as we get to really aggressive schedules. I was also thinking separately that we could just use `sort.Search` like you suggested below. But like I said, I think that we can revisit that in a separate PR and leave the mechanical code-move here.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 619 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1P3QnCBzqoL3oPTTA:-MA1hESd6n9yXVB9GnzF:bwm5rra) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L619)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It does appear that this function cannot be called with empty backup manifests.
Does it make sense to be defensive about this (panic, or return an error either here or at this functions call site)?
</blockquote></details>

Ya, there is a check that the backup manifests is not empty when we load them - however I think it would be nice if we do check them defensively here.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 620 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1NGsH32leIcCWnpNW:-MA1hVIxBVPCmDpmWyBr:b-mr3zvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L620)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is this a common case?  If not, then perhaps don't even bother having this special case.

Also, are backup manifests sorted in timestamp order?  
if so, this method can be written as:

if index := sort.Search(len(backupManifest), func(i int) bool {return asOf.Less(backupManifests[i]}); index >=0 {
   return index
}
return len(backupManifest)-1
</blockquote></details>

Yep, this case is just a plain old restore which I think is the case the vast majority of the time. I think I'd prefer cleaning up the index search in a separate PR and just live the mechanical code move in this PR.
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA1jNXI-Lxmi3wV4_km:b-cv2cne) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is having non-unique statistics filenames expected? 
</blockquote></details>

Yep, non-unique files are expected to start. The initial version that I proposed has a map that relates all tables to the file where they can find their stats. This means that we'll currently have something like:
`{53 -> STATS_FILE, 54 -> STATS_FILE, 61 -> STATS_FILE}`. I don't think the repeated naming is a big deal compared to the gain that we get in backwards compatibility. If we decide to split up the stats into separate file (as we've had issues with stats getting large in the past), we can set up the stats like: `{53 -> STATS_FILE_1, 54 -> STATS_FILE_1, 61 -> STATS_FILE_2}`, and read only the files for the tables that we're interested in and it would be backwards compatible.

This might be a bit excessive, but I prefer to opt for methods that give us the most flexibility considering we'll need to support this backup format forever. Happy to hear your thoughts on this though!
___
*[pkg/ccl/backupccl/restore_job.go, line 760 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1LsbNDslHBKreWcxy:-MA1laiEAt3f3u7v5flY:b-vsdy8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L760)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

doesn't this method return more than two things?
</blockquote></details>

I think the comment can be rephrased to: `this method returns the backup manifests and the descriptors from the relevant manifest`. I was planning on doing a quick refactor soon after to address the `TODO`.
___
*[pkg/ccl/backupccl/restore_job.go, line 818 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1QkpD7K31rniMF0QU:-MA1idLr7H6XaSnGSWHk:b-ptn3m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L818)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do we expect this method to be called multiple times?  I don't see in the resumer anything that would initialize this field multiple times.  Am I missing something?
</blockquote></details>

This method is used to abstract away the fact that in old versions we stored the stats in `backup.Statistics` and in new versions it's stored in a separate file. 
___
*[pkg/ccl/backupccl/restore_job.go, line 820 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1REQWEnobZrXVqwn4:-MA1iOomCfb33wAVueU3:b-1yfgpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L820)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm confused.  We have a check above "if backup.Statistics != nil {return}".
So, here, we have backup.Statistics == nil, therefore len(backup.Statistics) is known to be 0.
Why then do this long hand initialization?  
</blockquote></details>

Good catch, this should probably be `len(backup.StatisticsFilenames)`.
___
*[pkg/ccl/backupccl/restore_job.go, line 828 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1Zm1o6O-51KpdDsLp:-MA1ktYv1iOeBGPlW0_Q:b-lpv74w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L828)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Why are we swallowing error here?  If this is a right thing to do, thenit needs an explanation why.
</blockquote></details>

Hmm - I think this can go either way. I think we should be more thoughtful about 
___
*[pkg/ccl/backupccl/restore_job.go, line 854 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1_iQbB-69LJ336kK0:-MA1mW3sB1YZQljCFXy4:b-uknjnm) ([raw file](https://gi [...]

2020-06-17 15:42 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA1ueXH8OjaHlbR_w_Z:bf9slgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep, non-unique files are expected to start. The initial version that I proposed has a map that relates all tables to the file where they can find their stats. This means that we'll currently have something like:
`{53 -> STATS_FILE, 54 -> STATS_FILE, 61 -> STATS_FILE}`. I don't think the repeated naming is a big deal compared to the gain that we get in backwards compatibility. If we decide to split up the stats into separate file (as we've had issues with stats getting large in the past), we can set up the stats like: `{53 -> STATS_FILE_1, 54 -> STATS_FILE_1, 61 -> STATS_FILE_2}`, and read only the files for the tables that we're interested in and it would be backwards compatible.

This might be a bit excessive, but I prefer to opt for methods that give us the most flexibility considering we'll need to support this backup format forever. Happy to hear your thoughts on this though!
</blockquote></details>

Well, my thinking is that if we don't have duplicate files right now, then we probably don't need to dedup right now. 

Adding deduping later is a backward compatible change (as in: all previous versions never had duplicates to begin with, so adding deduping step later is totally fine).

Unless of course, you almost immediately plan on sending another PR that will need this dedup logic -- but even in that case, i'd argue adding that later (along with the test for that)
___
*[pkg/ccl/backupccl/restore_job.go, line 818 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1QkpD7K31rniMF0QU:-MA1uoY3ApTbMSk10yPP:bhrilqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L818)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

This method is used to abstract away the fact that in old versions we stored the stats in `backup.Statistics` and in new versions it's stored in a separate file. 
</blockquote></details>

I missed that part entirely.  I wonder if we should rename "Statistics" member to "deprecated_statistics" in the proto?  

At the very least, this if statement needs a comment that this is dealing w/ pre 20.2 stats format.
___
*[pkg/ccl/backupccl/restore_job.go, line 828 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1Zm1o6O-51KpdDsLp:-MA1vqPg12iv2MykRM4o:bvebeiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L828)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Hmm - I think this can go either way. I think we should be more thoughtful about 
</blockquote></details>

It just looked strange to me.  In particular, this method returns an array of statistics.
Does the caller expect that this array has the same cardinality as the number of file names?

Note: i'm not saying that the caller should/should not expect it.  Just that this method signature almost implies that.  So, if we are going to return after the first encountered error, then at the very least this needs some good reason (and a comment).

Furthermore, if this is a best effort attempt to load statistics, then shouldn't we at least load what we can and simply continue to try to load next stats?
___
*[pkg/ccl/backupccl/restore_job.go, line 996 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1aV91Cyayw2j5hGNQ:-MA1wTDR-V89f83khsVB:b-rldjso) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L996)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Yep, `loadBackupSQLDescs` does that check .
</blockquote></details>

A comment would be helpful here, I think.


<!-- Sent from Reviewable.io -->

2020-06-17 16:59 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA29wBQERv6QC3FdrNl:b-wg3qu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Well, my thinking is that if we don't have duplicate files right now, then we probably don't need to dedup right now. 

Adding deduping later is a backward compatible change (as in: all previous versions never had duplicates to begin with, so adding deduping step later is totally fine).

Unless of course, you almost immediately plan on sending another PR that will need this dedup logic -- but even in that case, i'd argue adding that later (along with the test for that)
</blockquote></details>

I see. I was thinking that we do need some de-duping here since all of the tables point to the same file. But since they are all written to the same file now, we could also just read directly form the file.
___
*[pkg/ccl/backupccl/restore_job.go, line 818 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1QkpD7K31rniMF0QU:-MA29Wk0AFbA3lihNYzA:b-39jk4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L818)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I missed that part entirely.  I wonder if we should rename "Statistics" member to "deprecated_statistics" in the proto?  

At the very least, this if statement needs a comment that this is dealing w/ pre 20.2 stats format.
</blockquote></details>

I think adding both (field rename + comment here) would be a good idea here.
___
*[pkg/ccl/backupccl/restore_job.go, line 828 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1Zm1o6O-51KpdDsLp:-MA2BScZ5KAIvMTouRQX:b-kkepme) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L828)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It just looked strange to me.  In particular, this method returns an array of statistics.
Does the caller expect that this array has the same cardinality as the number of file names?

Note: i'm not saying that the caller should/should not expect it.  Just that this method signature almost implies that.  So, if we are going to return after the first encountered error, then at the very least this needs some good reason (and a comment).

Furthermore, if this is a best effort attempt to load statistics, then shouldn't we at least load what we can and simply continue to try to load next stats?

</blockquote></details>

Whoops. Unsure how my comment got cut short...

I agree that this looks strange. I think that we should be bubbling up this error to the caller and decide how it should be handled there. I think we should bubble up the error all the way through the restore. If we did want to swallow the error - in addition to a comment I think we should also log it.


<!-- Sent from Reviewable.io -->

2020-06-18 13:39 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/backup_job.go, line 353 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1L4QcAlkpAdc6LVmT:-MA6c9bL2yB5iiXI3AX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L353)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

drop extra \n?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_job.go, line 359 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1b5XF09MRPbDnIqjF:-MA6c8oQAJlxjnVcSs9X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/backup_job.go#L359)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe use 2 variable version of the range loop?

for _, stat := range tableStatisticsAcc {
  tableStatistics = append(tableStatistics, &stat.TableStatisticProto)
}
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/manifest_handling.go, line 619 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1P3QnCBzqoL3oPTTA:-MA6aGos8_MtYCiZHwCy:b2fahwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/manifest_handling.go#L619)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Ya, there is a check that the backup manifests is not empty when we load them - however I think it would be nice if we do check them defensively here.
</blockquote></details>

Added an error check there for the case where backup manifest is empty. 
___
*[pkg/ccl/backupccl/restore_job.go, line 983 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9TXw_SA-Cxh8Xyfq3s:-MA6aYSp2z6g8UFmY_eg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a981d5ed94707e3091763de54e3aa6bab97d206f/pkg/ccl/backupccl/restore_job.go#L983)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I'm not sure we need this comment anymore, now the code is pretty clear on why we need the `lastBackupIndex` since we use it just a few lines after retrieving it.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 760 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1LsbNDslHBKreWcxy:-MA6adCTC8GdlzQ9YzRF:b-88xc0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L760)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think the comment can be rephrased to: `this method returns the backup manifests and the descriptors from the relevant manifest`. I was planning on doing a quick refactor soon after to address the `TODO`.
</blockquote></details>

Just rephrased the comment. 
___
*[pkg/ccl/backupccl/restore_job.go, line 818 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1QkpD7K31rniMF0QU:-MA6b2cPDlkISgb5Fdia:bp29ir0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L818)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think adding both (field rename + comment here) would be a good idea here.
</blockquote></details>

Done. (Comments added and changed the field name to `deprecated_statistics`. 
___
*[pkg/ccl/backupccl/restore_job.go, line 820 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1REQWEnobZrXVqwn4:-MA6b8w-CxvzLQe3t6ei:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L820)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Good catch, this should probably be `len(backup.StatisticsFilenames)`.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 825 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1RWg93q5IdrhICRZT:-MA6bAQFBixKrNDhup37:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L825)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Combine those 2 loops.  There is no reason to iterate through file names twice.  Instead:

for fname := range bakcup.StatisticsFilenames {
  if _, exists := uniqueFileNames[fmane]; !exists {
     uniqueFileNames[fname] = struct{}{}
    ... rest of this loop body
  }
}
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 828 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1Zm1o6O-51KpdDsLp:-MA6bT3S1cN6Xqo0aI_N:bkr5ok1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L828)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Whoops. Unsure how my comment got cut short...

I agree that this looks strange. I think that we should be bubbling up this error to the caller and decide how it should be handled there. I think we should bubble up the error all the way through the restore. If we did want to swallow the error - in addition to a comment I think we should also log it.
</blockquote></details>

I made the function to return a `*stats.TableStatisticProto` array and error. 
___
*[pkg/ccl/backupccl/restore_job.go, line 996 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1aV91Cyayw2j5hGNQ:-MA6bhvF-8zc5ZzhIPjq:b-4ve9fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L996)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

A comment would be helpful here, I think.
</blockquote></details>

An empty backup manifest will have (-1, error) returned at `getBackupIndexAtTime`, hope this solves the problem. :) 
___
*[pkg/ccl/backupccl/restore_job.go, line 997 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1OORYC34BZEQBBVIt:-MA6b-lT5wDoQ9CO2KOg:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L997)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

this seems wrong: error check should happen before you call getBackupIndexAtTime.
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2020-06-18 13:51 UTC, miretskiy approved these changes
> Reviewed 6 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @miretskiy, and @pbardea)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-MA6gUEv7b_-9BoKEvkN:b-pp12nl) (no related file):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Nice! This LGTM mod some small comments.
</blockquote></details>

Looking much better.  I'm giving <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> ; just 2 more comments to resolve.  Thanks!

---
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA6g4YuCIYc_QaPJ-xe:b-scpuhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I see. I was thinking that we do need some de-duping here since all of the tables point to the same file. But since they are all written to the same file now, we could also just read directly form the file.
</blockquote></details>

@pbardea  So, did you want uniqueness check dropped or still kept?
___
*[pkg/ccl/backupccl/restore_job.go, line 854 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1_iQbB-69LJ336kK0:-MA6gG254jBJaVX0HPJ8:bgst9f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L854)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Haha, I believe this was my doing in the first place. I usually opt for early-return to avoid a lot of nesting, but considering the shortness of this method I think I would actually prefer your suggestion. I don't think that we need to change this in this PR though.
</blockquote></details>

@anzoteh96 I think you should change this loop (since you already changing it) anyway


<!-- Sent from Reviewable.io -->

2020-06-18 14:23 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 854 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA1_iQbB-69LJ336kK0:-MA6nosH9EJuH3zeNRki:bu9g4k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ce7ba0130268f3c172dc26727f652ffce3de6d/pkg/ccl/backupccl/restore_job.go#L854)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

@anzoteh96 I think you should change this loop (since you already changing it) anyway
</blockquote></details>

Done. Thanks for catching that!


<!-- Sent from Reviewable.io -->

2020-06-18 16:39 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96 and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9FWqeGECYIxDAsvbEY:-MA7I2yEEUmKWqR4GU_B:b-b9ejxe) (no related file):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Looking much better.  I'm giving :lgtm: ; just 2 more comments to resolve.  Thanks!
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with just 1 small formatting nit on the error message.

---
___
*[pkg/ccl/backupccl/manifest_handling.go, line 620 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA7HLqDAfEuRcVcw9h9:-MA7HLqDAfEuRcVcw9hA:b-mpd5wh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ff384fec37d37236e250e388a407a41f5f3464/pkg/ccl/backupccl/manifest_handling.go#L620)):*
> ```Go
> func getBackupIndexAtTime(backupManifests []BackupManifest, asOf hlc.Timestamp) (int, error) {
> 	if len(backupManifests) == 0 {
> 		return -1, errors.New("Expected a nonempty backup manifest list, got an empty list")
> ```

nit: we usually don't capitalize error messages
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA7GQp_6_SBe8IzIyps:b5lc8jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

@pbardea  So, did you want uniqueness check dropped or still kept?
</blockquote></details>

My vote would be to keep it.


<!-- Sent from Reviewable.io -->

2020-06-18 17:42 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49838)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 620 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-MA7HLqDAfEuRcVcw9h9:-MA7V0EU0admjdgttnJa:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5ff384fec37d37236e250e388a407a41f5f3464/pkg/ccl/backupccl/manifest_handling.go#L620)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: we usually don't capitalize error messages
</blockquote></details>

Done. 
___
*[pkg/ccl/backupccl/restore_job.go, line 813 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49838#-M9P6ydH-_LnjMF89tam:-MA7V8Ys7rgJJeGKo0dZ:bhyrjo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/524d751c9f8a25c532db941cea9fbb8a7da31320/pkg/ccl/backupccl/restore_job.go#L813)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

My vote would be to keep it.
</blockquote></details>

Contributing my two cents: I think we can leave the code as it is now, but we could add some comments along the lines of "For now, we have multiple TableDescriptors mapping to the same filename as we intend to have all TableStatisticsProto objects to be stored on the same file. However, we preserve the mapping structure on the grounds of backward compatibility, just in case we are going for other alternatives in the future". 


<!-- Sent from Reviewable.io -->

2020-06-25 18:33 UTC, Anzoteh96 commented
Leaving this code as it is now :) TFTR!

bors r+

2020-06-25 20:05 UTC, merged