importccl: enable import into tables with user defined types
cockroachdb/cockroach pull request #50002
Opened 2020-06-09 04:15 UTC by rohany

Fixes #49971.

This PR adds the necessary type metadata hydration to the import
statement and import workers in order to import into tables that contain
user defined types.

Release note: None

2020-06-09 04:16 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50002)
<!-- Reviewable:end -->

2020-06-09 16:39 UTC, miretskiy requested changes
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rohany)

___
*[pkg/ccl/importccl/import_processor.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9Ovxbv8J2yymdY4Nzq:-M9Ovxbv8J2yymdY4Nzr:b-yclnml) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_processor.go#L127)):*
> ```Go
> 				// Create a new transaction to hydrate the types in.
> 				if err := evalCtx.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 					evalCtx.Txn = txn
> ```


Could evalCtx already have a Txn set? What happens when we override it?


just not sure how this code supposed to work (nor, why for example HydrateTypeSlice does not
take txn argument explicitly, though, looking at that method, I don't see a reason why we shouldn't pass txn directly
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9OwaHWE9aYrelYHV7z:-M9OwaHWE9aYrelYHV8-:b-ib8ym0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1100)):*
> ```Go
> 		require.NoError(t, err)
> 		// Run the import statement.
> 		if test.into {
> ```

why not just add another loop 
for into := range {true,false}?
You could cut your test cases in 1/2


<!-- Sent from Reviewable.io -->

2020-06-09 17:00 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/importccl/import_processor.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9Ovxbv8J2yymdY4Nzq:-M9P0EiD4_jl8d1JI2uD:b-7xsr01) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_processor.go#L127)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>


Could evalCtx already have a Txn set? What happens when we override it?


just not sure how this code supposed to work (nor, why for example HydrateTypeSlice does not
take txn argument explicitly, though, looking at that method, I don't see a reason why we shouldn't pass txn directly

</blockquote></details>

I don't think it can in this case, but it's reasonable to check and reuse it if so. We use an `EvalContext` in that function because it will eventually be updated to look into the `LeaseManager` for leased TypeDescriptors, and fall back to the txn if a descriptor isn't leased.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9OwaHWE9aYrelYHV7z:-M9P0VOu4ALACH_EW5i8:b-sg9esu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1100)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why not just add another loop 
for into := range {true,false}?
You could cut your test cases in 1/2
</blockquote></details>

True -- i was originally thinking that something more would need to be done for the import into statements, but that doesn't seem to be the case. I'll update it.


<!-- Sent from Reviewable.io -->

2020-06-09 17:23 UTC, rohany commented on pkg/ccl/importccl/import_stmt_test.go
> +		// TODO (rohany): What's the best way to test out some AVRO imports?
Any suggestions here?

2020-06-09 17:24 UTC, rohany commented
I was looking at some backup stuff today, and I see that some of this descriptor ID rewriting logic is also used in import -- do you think that needs to be touched here?

2020-06-09 19:11 UTC, miretskiy requested changes
I honestly don't know.  @pbardea ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-:-M9PSWHu4c6vTETdfIWV:bc7419z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9OwaHWE9aYrelYHV7z:-M9PSiGu40HN570a7wLm:b-8otjij) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1100)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

True -- i was originally thinking that something more would need to be done for the import into statements, but that doesn't seem to be the case. I'll update it.
</blockquote></details>

Good question.  I think we almost certainly need to add an issue to add support for Avro.

We might have to update our avro parser (read_import_avro), but I'm not sure on that..
The change you're making is focused making changes to makeInputConverter -- the same code we use in avro. 

I think you can try doing few things:
  1. If you want to generate test data on the fly,like you do in your test, 
you might want to take a look at read_import_avro_test.  There is a generator code in there that
can generate and test avro data.  I suggest genOcfData which will probably be the easiest thing for you to use (you might want to move this test code to testutils_test.go)
  2. You can generate external (testdata) avro data.  testdata/avro directory has readme file
describing how to generate avro data.


<!-- Sent from Reviewable.io -->

2020-06-09 19:12 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1090 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9MHhDiHq83W5R-vwc1-r1-1090:-M9PUp756odJcJojvI9V:b3hpm96) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1090)):*
> Good question.  I think we almost certainly need to add an issue to add support for Avro.
> We might have to update our avro parser (read_import_avro), but I'm not sure on that..
> The change you're making is focused making changes to makeInputConverter -- the same code we use in avro.
> I think you can try doing few things:
> 
> If you want to generate test data on the fly,like you do in your test,
> you might want to take a look at read_import_avro_test.  There is a generator code in there that
> can generate and test avro data.  I suggest genOcfData which will probably be the easiest thing for you to use (you might want to move this test code to testutils_test.go)
> You can generate external (testdata) avro data.  testdata/avro directory has readme file
> describing how to generate avro data.


<!-- Sent from Reviewable.io -->

2020-06-09 20:34 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_processor.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9Ovxbv8J2yymdY4Nzq:-M9PmV8LAOLrDW8kPZ9G:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_processor.go#L127)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I don't think it can in this case, but it's reasonable to check and reuse it if so. We use an `EvalContext` in that function because it will eventually be updated to look into the `LeaseManager` for leased TypeDescriptors, and fall back to the txn if a descriptor isn't leased.
</blockquote></details>

Done
___
*[pkg/ccl/importccl/import_stmt_test.go, line 1100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9OwaHWE9aYrelYHV7z:-M9PmYPu8a7h6JoDqhBJ:b-50s58h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1100)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Good question.  I think we almost certainly need to add an issue to add support for Avro.

We might have to update our avro parser (read_import_avro), but I'm not sure on that..
The change you're making is focused making changes to makeInputConverter -- the same code we use in avro. 

I think you can try doing few things:
  1. If you want to generate test data on the fly,like you do in your test, 
you might want to take a look at read_import_avro_test.  There is a generator code in there that
can generate and test avro data.  I suggest genOcfData which will probably be the easiest thing for you to use (you might want to move this test code to testutils_test.go)
  2. You can generate external (testdata) avro data.  testdata/avro directory has readme file
describing how to generate avro data.

</blockquote></details>

Removed the extra tests. Thanks for the avro tip, I'll look into that now.


<!-- Sent from Reviewable.io -->

2020-06-09 20:38 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1040 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9PnM_XCFsgPmyCZj7a:-M9PnM_XCFsgPmyCZj7b:b1ztcj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2716a892df9abdefb7a37a2f7c82543c098ca/pkg/ccl/importccl/import_stmt_test.go#L1040)):*
> ```Go
> 		// Test CSV imports.
> 		{
> 			create:      "a greeting, b greeting",
> ```

TODO (me): Test import with some default column values that are enums as well.


<!-- Sent from Reviewable.io -->

2020-06-09 20:44 UTC, miretskiy reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)



<!-- Sent from Reviewable.io -->

2020-06-09 21:40 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1040 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9PnM_XCFsgPmyCZj7a:-M9Q0cGnEgLMAyVZ0EA1:b-t5hr5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0a2716a892df9abdefb7a37a2f7c82543c098ca/pkg/ccl/importccl/import_stmt_test.go#L1040)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

TODO (me): Test import with some default column values that are enums as well.
</blockquote></details>

Never mind, I don't think you can do this.


<!-- Sent from Reviewable.io -->

2020-06-09 21:42 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1090 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9MHhDiHq83W5R-vwc1-r1-1090:-M9Q183TC3UM0bGC8FRz:blbqnvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b784c8008f24798749ed42ceab809d6ab05859a3/pkg/ccl/importccl/import_stmt_test.go#L1090)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> Good question.  I think we almost certainly need to add an issue to add support for Avro.
> We might have to update our avro parser (read_import_avro), but I'm not sure on that..
> The change you're making is focused making changes to makeInputConverter -- the same code we use in avro.
> I think you can try doing few things:
> 
> If you want to generate test data on the fly,like you do in your test,
> you might want to take a look at read_import_avro_test.  There is a generator code in there that
> can generate and test avro data.  I suggest genOcfData which will probably be the easiest thing for you to use (you might want to move this test code to testutils_test.go)
> You can generate external (testdata) avro data.  testdata/avro directory has readme file
> describing how to generate avro data.

</blockquote></details>

Done, added some avro data to the test.


<!-- Sent from Reviewable.io -->

2020-06-09 22:01 UTC, miretskiy approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50002)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 1057 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50002#-M9Q56f16boqJN4mHo4E:-M9Q56f28e5o2OkJL3aV:b-db7gj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fed78b6d433aba1ee4787476c586e4b985ec77/pkg/ccl/importccl/import_stmt_test.go#L1057)):*
> ```Go
> 		require.NoError(t, err)
> 		// Create an AVRO writer from the schema.
> 		ocr, err := goavro.NewOCFWriter(goavro.OCFConfig{
> ```

s/ocr/ocf/?


<!-- Sent from Reviewable.io -->

2020-06-10 00:27 UTC, rohany commented
TFTR!

> I was looking at some backup stuff today, and I see that some of this descriptor ID rewriting logic is also used in import -- do you think that needs to be touched here?

I looked into this more, and I don't think that it is necessary. I'll take another pass while working on backup.

bors r+

2020-06-10 01:59 UTC, merged