opt: add rule to fold JSON field access into Values operator
cockroachdb/cockroach pull request #50131
Opened 2020-06-12 02:48 UTC by DrewKimball

Previously, the optimizer didn't fold JSON field access over an input
Values operator.

This patch adds a rule that constructs a new Values operator with columns
corresponding to each referenced field in the JSON expression. It replaces
the surrounding Project operator with a new one that references the new
columns and takes the new Values as input. Example:
```
SELECT cust->'id' AS id, cust->'name' AS name
FROM (VALUES
   ('{"id": 1, "name": 'Drew'}'::JSON),
   ('{"id": 2, "name": 'Radu'}'::JSON),
   ('{"id": 3, "name": 'Rebecca'}'::JSON)
) v(cust)
=>
SELECT id, name
FROM (VALUES
   (1::JSON, 'Drew'::JSON),
   (2::JSON, 'Radu'::JSON),
   (3::JSON, 'Rebecca'::JSON)
) v(id, name)
```
Release note: None

2020-06-12 02:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50131)
<!-- Reviewable:end -->

2020-06-12 02:55 UTC, DrewKimball commented
I benchmarked this query with different numbers of rows:

```
SELECT j->'a', j->'b', j->'c', j->'d', j->'e'
FROM (VALUES
	('{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}'::JSON),
         …
);
```
**1 Row:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    76.2µs ± 3%    76.4µs ± 3%   ~     (p=0.436 n=10+10)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    18.3kB ± 0%    18.3kB ± 0%   ~     (p=0.857 n=8+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd       150 ± 0%       150 ± 0%   ~     (all equal)
```
**10 Rows:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     126µs ± 1%     111µs ± 2%  -11.85%  (p=0.000 n=9+10)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    35.1kB ± 0%    32.8kB ± 0%   -6.61%  (p=0.000 n=8+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd       557 ± 0%       466 ± 0%  -16.34%  (p=0.000 n=8+8)
```
**100 Rows:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     458µs ± 3%     418µs ± 3%  -8.67%  (p=0.000 n=10+10)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     160kB ± 1%     166kB ± 0%  +3.49%  (p=0.000 n=9+9)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     3.81k ± 0%     3.62k ± 0%  -4.82%  (p=0.000 n=10+8)
```
**1,000 Rows:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    3.35ms ± 2%    3.26ms ± 2%  -2.74%  (p=0.000 n=10+9)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    1.39MB ± 0%    1.50MB ± 0%  +7.73%  (p=0.000 n=9+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     36.3k ± 0%     35.2k ± 0%  -2.98%  (p=0.000 n=9+8)
```
**10,000 Rows:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    34.8ms ± 3%    33.1ms ± 1%  -5.01%  (p=0.000 n=10+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd    13.7MB ± 0%    14.9MB ± 0%  +8.12%  (p=0.000 n=8+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd      361k ± 0%      351k ± 0%  -2.79%  (p=0.000 n=8+8)
```
**100,000 Rows:**
```
name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     398ms ± 3%     353ms ± 5%  -11.23%  (p=0.000 n=10+10)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     137MB ± 0%     148MB ± 0%   +8.14%  (p=0.000 n=9+8)

name                              old time/op    new time/op    delta
EndToEnd/json-fold-test/EndToEnd     3.61M ± 0%     3.51M ± 0%   -2.78%  (p=0.000 n=9+8)
```

2020-06-12 04:06 UTC, andy-kimball approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> This already incorporates my feedback. @raduberinde, @rytaft, I'm going to begin marking any of Drew's PR's that I looked at before he posted so that you both don't need to feel like you have to review as well (maybe just one of you on a given PR is sufficient in most cases). Unless you want to review, of course!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-:-M9ae3sF8MnRszf_iBui:b1sitsp)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-06-12 12:54 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> very nice!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-:-M9ca42A49QXPseR1ff8:bhnhlex)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/project_funcs.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9c_mli5wLbmSKcXdeC:-M9c_mli5wLbmSKcXdeD:by6nh62) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/project_funcs.go#L255)):*
> ```Go
> }
> 
> // CanUnnestJSONFromValues returns true if the Values operator has a single
> ```

Also add a note somewhere in this comment that this function should only be called if the values has at least one row and exactly one column.
___
*[pkg/sql/opt/norm/project_funcs.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cSg9RA3zMYZpyMr04:-M9cSg9RA3zMYZpyMr05:bcb8ckr) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/project_funcs.go#L261)):*
> ```Go
> //     within the JSON object can be referenced.
> //  2. All JSON keys referenced by the projections are present in the first row.
> //  3. All JSON keys present in the first row are present in all other rows.
> ```

Technically we only need the keys referenced by the projections, but after reading the code I agree this approach is cleaner/easier (and as you show in one of the test cases, the unused columns get pruned away anyway). Maybe just add a quick note summarizing this here...
___
*[pkg/sql/opt/norm/rules/project.opt, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cXerDEqjhbsOONDdm:-M9cXPdG-lVmZSlPZzob:b-rnr3ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L164)):*
> ```
> [FoldTupleAccessIntoValues, Normalize]
> (Project
>     $input:(Values [ * ... ]) &
> ```

Is this checking that there is at least one row? If so, maybe add that info to the comment above.
___
*[pkg/sql/opt/norm/rules/project.opt, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cXtFG-9iNotEU5w4C:-M9cXtFG-9iNotEU5w4D:blh7lk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L184)):*
> ```
> )
> 
> # FoldJSONAccessIntoValues replaces a Values that has a single column that
> ```

a single column and at least one row?
___
*[pkg/sql/opt/norm/rules/project.opt, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cYE-r5ihEja0SztRp:-M9cYE-r5ihEja0SztRq:b-rznrs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L192)):*
> ```
> #
> # FoldJSONAccessIntoValues has the side affect of pruning any keys that are not
> # present in the first Values row (since they are unreferenced).
> ```

You need to mention somewhere before this that the rule only fires if all references match keys contained in the first row.


<!-- Sent from Reviewable.io -->

2020-06-12 19:48 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/norm/project_funcs.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9c_mli5wLbmSKcXdeC:-M9e2pIK3T1lYj6Sqicd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/project_funcs.go#L255)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Also add a note somewhere in this comment that this function should only be called if the values has at least one row and exactly one column.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/project_funcs.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cSg9RA3zMYZpyMr04:-M9e3F77206ZYlFx_IoP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/project_funcs.go#L261)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Technically we only need the keys referenced by the projections, but after reading the code I agree this approach is cleaner/easier (and as you show in one of the test cases, the unused columns get pruned away anyway). Maybe just add a quick note summarizing this here...
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/project.opt, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cXerDEqjhbsOONDdm:-M9e1M8B1yqlq6tbX-pe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L164)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this checking that there is at least one row? If so, maybe add that info to the comment above.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/project.opt, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cXtFG-9iNotEU5w4C:-M9e1NE1D2_NUx88J5Qd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L184)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

a single column and at least one row?
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/project.opt, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9cYE-r5ihEja0SztRp:-M9e1sqsEbjaWnikhwLt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df051a3bd9049123fde5ea913fd4abb97fefe39d/pkg/sql/opt/norm/rules/project.opt#L192)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You need to mention somewhere before this that the rule only fires if all references match keys contained in the first row.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-06-13 14:52 UTC, rytaft approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/general_funcs.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i8Uj12HBBA6PLEIkh:-M9i8Uj12HBBA6PLEIki:b-ax4rau) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L176)):*
> ```Go
> }
> 
> // HasNoCols returns true if the input ColSet has zero output columns.
> ```

[nit] output columns -> columns
___
*[pkg/sql/opt/norm/general_funcs.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i8Yzg8iAlh58GAMki:-M9i8Yzh0iaiTtgLPYUg:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L181)):*
> ```Go
> }
> 
> // HasOneCol returns true if the input ColSet has exactly one output column.
> ```

ditto
___
*[pkg/sql/opt/norm/rules/project.opt, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i9H1f48wNad-RQ_xr:-M9i9H1f48wNad-RQ_xs:b-y5d9bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/rules/project.opt#L146)):*
> ```
> (PushColumnRemappingIntoValues $input $projections $passthrough)
> 
> # FoldTupleAccessIntoValues replaces a Values that has a single column of tuples
> ```

single column of tuples and at least one row?


<!-- Sent from Reviewable.io -->

2020-06-15 16:23 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/general_funcs.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9skspw38JKoApA8K7W:-M9skspxEB92pGukh7wV:b-o8o718) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L177)):*
> ```Go
> 
> // HasNoCols returns true if the input ColSet has zero output columns.
> func (c *CustomFuncs) HasNoCols(cols opt.ColSet) bool {
> ```

`HasNoCols` is a duplicate of `ColsAreEmpty` below on line 193. I think we should remove this function and use that one instead.
___
*[pkg/sql/opt/norm/general_funcs.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9slr7z8N5FcRjaIC5t:-M9slDc-3y-2jaZdVVnx:b-j85pcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L182)):*
> ```Go
> 
> // HasOneCol returns true if the input ColSet has exactly one output column.
> func (c *CustomFuncs) HasOneCol(cols opt.ColSet) bool {
> ```

[nit] The other functions operating on `ColSet` have names starting with "Cols". If we wanted to be consistent with that, we could name this something like `ColsLenOne` or `ColsIsLenOne`? But those might be less clear, although more consistent.


<!-- Sent from Reviewable.io -->

2020-06-15 19:34 UTC, DrewKimball reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/norm/general_funcs.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i8Uj12HBBA6PLEIkh:-M9tSL0l7tDBjZTqIGVJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] output columns -> columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/general_funcs.go, line 177 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9skspw38JKoApA8K7W:-M9tSNuHDvSOrbNaXPTt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L177)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`HasNoCols` is a duplicate of `ColsAreEmpty` below on line 193. I think we should remove this function and use that one instead.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/general_funcs.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i8Yzg8iAlh58GAMki:-M9tSOqh8g9f9Ned2TYg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L181)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/general_funcs.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9slr7z8N5FcRjaIC5t:-M9tSuBz8C1Xmxj7NW3S:b-oel8q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L182)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] The other functions operating on `ColSet` have names starting with "Cols". If we wanted to be consistent with that, we could name this something like `ColsLenOne` or `ColsIsLenOne`? But those might be less clear, although more consistent.
</blockquote></details>

How does ```ColsAreLenOne``` sound?
___
*[pkg/sql/opt/norm/rules/project.opt, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i9H1f48wNad-RQ_xr:-M9tS0LBBoMugArDUSqY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/rules/project.opt#L146)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

single column of tuples and at least one row?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-06-15 19:35 UTC, rytaft commented
___
*[pkg/sql/opt/norm/general_funcs.go, line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9i8Uj12HBBA6PLEIkh:-M9tTgLh-Oior4e0-91S:bo5wa54) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L176)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks like you didn't push the latest update....


<!-- Sent from Reviewable.io -->

2020-06-16 18:25 UTC, mgartner approved these changes
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50131)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @rytaft)

___
*[pkg/sql/opt/norm/general_funcs.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50131#-M9slr7z8N5FcRjaIC5t:-M9yM0UGC1PCpYLDAPH9:b-6gyjyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f222fe92f02e80ff883979aa590a161166bda91/pkg/sql/opt/norm/general_funcs.go#L182)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

How does ```ColsAreLenOne``` sound?
</blockquote></details>

:money_mouth_face: 


<!-- Sent from Reviewable.io -->

2020-06-17 01:01 UTC, DrewKimball commented
bors r+

2020-06-17 01:55 UTC, merged