sql: fix ALTER COLUMN TYPE USING EXPRESSION for same type conversion
cockroachdb/cockroach pull request #50130
Opened 2020-06-12 00:56 UTC by RichardJCai

Forgot to update the case where a no-op would happen if the column conversion was
to the same type. We should always be trying the General conversion if an expression
is provided.

Left the release note as none since bug is not out in prod.

Release note: None

2020-06-12 00:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50130)
<!-- Reviewable:end -->

2020-06-12 01:59 UTC, rohany requested changes
Isn't the bug something more like "fixed a bug where alter column type using expression would sometimes not perform a backfill with a `USING` expression. This could be caused when the type change was happening between two trivially convertible types, or two types that can't be casted in the standard way".

[nit] commit message should be prefixed with the package changed

2020-06-12 01:59 UTC, rohany commented on pkg/sql/alter_column_type.go
> +		if col.Type.Identical(typ) {
I don't think you need this, classify conversion performs this same check.

2020-06-13 02:39 UTC, rohany approved these changes

2020-06-13 03:47 UTC, RichardJCai commented
Thanks for the review!

2020-06-13 03:47 UTC, RichardJCai commented
bors r=rohany

2020-06-13 04:33 UTC, merged