colexec: adjust the distribution of randomized batch size
cockroachdb/cockroach pull request #50167
Opened 2020-06-12 22:45 UTC by yuzefovich

This commit adjusts the distribution of randomized batch size to favor
the small sizes yet keeps the possibility of larger sizes as well. Such
distribution is chosen due to the fact that most of our unit tests
don't have a lot of data, so in order to exercise the multi-batch
behavior we favor really small batch sizes. On the other hand, we also
want to occasionally exercise that we handle batch sizes larger than
default one correctly.

Release note: None

2020-06-12 22:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50167)
<!-- Reviewable:end -->

2020-06-15 14:47 UTC, asubiotto requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/main_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50167#-M9sRbeUE9CHer4RyYvq:-M9sRbeUE9CHer4RyYvr:b9ug4lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9bc752c46223c2dc69a1c0eef0fd4796f32668/pkg/sql/colexec/main_test.go#L100)):*
> ```Go
> 		// exercise that we handle batch sizes larger than default one
> 		// correctly.
> 		var sizesToChooseFrom = []int{
> ```

It might make sense to put this into `coldata` and reuse here since I think logic tests also attempt to do something similar re distribution and might benefit from just calling this when it's moved into `coldata`.


<!-- Sent from Reviewable.io -->

2020-06-15 14:58 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/main_test.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50167#-M9sRbeUE9CHer4RyYvq:-M9sTNIy3SXYAjTmbHdp:bo0ed2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9bc752c46223c2dc69a1c0eef0fd4796f32668/pkg/sql/colexec/main_test.go#L100)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might make sense to put this into `coldata` and reuse here since I think logic tests also attempt to do something similar re distribution and might benefit from just calling this when it's moved into `coldata`.
</blockquote></details>

I disagree with this for a couple of reasons:
1. currently the method is very easy to use, and the caller can decide on the distribution of random values that suits the caller's needs. If we force the distribution into the method itself, it won't be as flexible.
2. the distributions in `colexec/main_test.go` and `logic.go` are different - note that in `colexec` we have a `minBatchSize` prohibiting values of `1` and `2` be used, but in `logic.go` those are actually quite desirable. If we make an investment in auditing the unit tests in `colexec` to remove this limitation, then maybe we could unify the two calls.


<!-- Sent from Reviewable.io -->

2020-06-15 15:48 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50167#-:-M9sej_M993Gm2ONuAM8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-06-15 15:49 UTC, yuzefovich commented
TFTR!

bors r+

2020-06-15 17:26 UTC, merged