logictest: introduce new configs for experimental distsql planning
cockroachdb/cockroach pull request #50249
Opened 2020-06-15 23:33 UTC by yuzefovich

This commit adds three new configurations `local-exp-planning`,
`fakedist-exp-planning`, and `5node-exp-planning` which override
`experimental_distsql_planning` cluster setting to `on`. These configs
are not included in any of the "default" lists and are currently used
only in two files. I intend to add them to the corresponding
`distsql_...` files once the certain `Construct*` methods are supported.
And once the new factory is significantly implemented, it will probably
make sense to add the configs to the lists of defaults ones.

Release note: None

2020-06-15 23:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50249)
<!-- Reviewable:end -->

2020-06-16 14:29 UTC, asubiotto requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50249)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50249#-M9xWuYN71DS-YYIXz8l:-M9xWuYOEtyGiVcR3ZHF:b-17nejq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39f1067024ea639a904b2653b4aa63dabd41cd/pkg/sql/logictest/logic.go#L482)):*
> ```Go
> 	},
> 	{
> 		name:                                "local-exp-planning",
> ```

`exp` sounds like `expression to me. How about `spec` e.g. `local-spec-planning` instead?
___
*[pkg/sql/logictest/logic.go, line 586 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50249#-M9xX5s9AfG42ZSlGuXf:-M9xX5s9AfG42ZSlGuXg:b-bddinw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39f1067024ea639a904b2653b4aa63dabd41cd/pkg/sql/logictest/logic.go#L586)):*
> ```Go
> 	},
> 	{
> 		name:                                "5node-exp-planning",
> ```

What if we add this to the `5node-defaults` directive? Is it worth it?


<!-- Sent from Reviewable.io -->

2020-06-16 15:47 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50249)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/logic.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50249#-M9xWuYN71DS-YYIXz8l:-M9xmtN9CPhddYDRtvyF:b-d53l7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39f1067024ea639a904b2653b4aa63dabd41cd/pkg/sql/logictest/logic.go#L482)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`exp` sounds like `expression to me. How about `spec` e.g. `local-spec-planning` instead?
</blockquote></details>

I like this suggestion, done.
___
*[pkg/sql/logictest/logic.go, line 586 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50249#-M9xX5s9AfG42ZSlGuXf:-M9xnG4-AKeACIAg56RC:b-h7hxyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f39f1067024ea639a904b2653b4aa63dabd41cd/pkg/sql/logictest/logic.go#L586)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What if we add this to the `5node-defaults` directive? Is it worth it?
</blockquote></details>

Hm, at this point not many things are implemented in the new factory, so most of the work will be redundant. However, we use `5node-defaults` in about 10 files, so it shouldn't make the test time a lot worse, and it might be nice to have the new config in those files. Done.


<!-- Sent from Reviewable.io -->

2020-06-16 15:55 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50249#-:-M9xpraW3RTc5PXEAWek:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-06-16 20:19 UTC, yuzefovich commented
TFTR!

bors r+

2020-06-17 01:12 UTC, merged