opt: change GeoLookupJoin to InvertedLookupJoin
cockroachdb/cockroach pull request #50252
Opened 2020-06-16 02:17 UTC by rytaft

This commit converts the `GeoLookupJoin` operator in the optimizer into
a more general operator, `InvertedLookupJoin`. This new operator maps
directly to the `invertedJoiner` DistSQL processor. In the future, the
`InvertedLookupJoin` operator can also be used for lookup joins on inverted
JSON and array indexes in addition to geospatial indexes.

This commit also adds a new structure, `geoDatumToInvertedExpr`, which
implements the `DatumToInvertedExpr` interface for geospatial data types.
This will enable the optimized plan to be easily converted to a DistSQL
plan for execution by the `invertedJoiner`.

Release note: None

2020-06-16 02:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50252)
<!-- Reviewable:end -->

2020-06-16 17:08 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-M9y5OB5Bt0wUZF72ksX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/opt/ops/relational.opt, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y3vGo9EQFJIBuOzMM:-M9y3vGp7jv86bjP5iEN:b862ts1) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb134e905953c2132a956a0bdc64f2ca7ecf9/pkg/sql/opt/ops/relational.opt#L334)):*
> ```
>     # not actually included in the index, the GeoLookupJoin must be wrapped in
>     # an index join, which will contain the original geospatial function as one
>     # of its On conditions.)
> ```

This bit about requiring an IndexJoin applies to all inverted lookup joins, correct? Should we keep it?
___
*[pkg/sql/opt/xform/geo.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y0SHXDVrL8HMOaIBR:-M9y0SHY-PvJ0h9SjG9d:bj16aq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/96876125341b7a638c9548a85c46942d211452de/pkg/sql/opt/xform/geo.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package xform
> ```

Does it make sense to put these functions in a new package, `pkg/sql/opt/geo`? That's what I've done with some of the partial index logic in `pkg/sql/opt/partialidx`. I don't feel too strongly either way, but I'm thinking it would be nice to be consistent with these types of "helper" packages, so I can also move that partial index "helper" code into `xform`.
___
*[pkg/sql/opt/xform/geo.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y4PPtBLvCIzHUgrF1:-M9y4PPtBLvCIzHUgrF2:b-3nsgnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/xform/geo.go#L266)):*
> ```Go
> }
> 
> var _ invertedexpr.DatumToInvertedExpr = &geoDatumToInvertedExpr{}
> ```

I've seen this elsewhere, but I'm not sure what its purpose is. Is it like an assertion to ensure all correct interface methods of `DatumToInvertedExpr` have been defined for `geoDatumToInvertedExpr`?


<!-- Sent from Reviewable.io -->

2020-06-16 17:23 UTC, sumeerbhola requested changes
I haven't finished reading yet -- flushing some comments.

> Reviewed 2 of 2 files at r1, 20 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-M9y8q5E7RFOwQIlNRbE:b-vtb6jj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y5s3Y-8EI-GFqyJ4_:-M9y5s3Y-8EI-GFqyJ4a:b-1es69c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
> ```Go
> }
> 
> func (b *Builder) builInvertedLookupJoin(join *memo.InvertedLookupJoinExpr) (execPlan, error) {
> ```

if this is distributed across different partitions of the input, will this function be executed at each node that is evaluating the inverted join?

nit: the term `InvertedLookupJoin` predates the name of the InvertedJoiner processor. How about renaming in the optimizer code to InvertedJoin?
___
*[pkg/sql/opt/ops/relational.opt, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y3vGo9EQFJIBuOzMM:-M9y7Ypd9DxVyc6JjxWL:b-9dflq) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb134e905953c2132a956a0bdc64f2ca7ecf9/pkg/sql/opt/ops/relational.opt#L334)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This bit about requiring an IndexJoin applies to all inverted lookup joins, correct? Should we keep it?
</blockquote></details>

The wrapping is only needed if the filter cannot be precisely (is tightly the right term?) evaluated. For JSON and Array there are cases where it won't be needed. Unless of course we need more than the primary key columns later in the query.


<!-- Sent from Reviewable.io -->

2020-06-16 21:37 UTC, sumeerbhola requested changes
> Reviewed 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/custom_funcs.go, line 1745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9z1VquBSb7menDgBOO:-M9z1VqvCY__y8nSiPFI:b3hhxen) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/xform/custom_funcs.go#L1745)):*
> ```Go
> 		lookupJoin.Table = scanPrivate.Table
> 		lookupJoin.Index = iter.IndexOrdinal()
> 		lookupJoin.DatumToInvertedExpr = NewGeoDatumToInvertedExpr(relationship, iter.Index())
> ```

This seems restricted to a single relationship.

We should add a TODO to handle more complicated expressions e.g. ST_Intersects(x, y) AND ST_Covers(<some literal>, y) where y is the indexed value. 


<!-- Sent from Reviewable.io -->

2020-06-22 16:03 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARl8UA-6bHB9Aqsg_z:-MARl8UA-6bHB9Aqsga-:b-bqyw7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
> ```Go
> }
> 
> func (b *Builder) builInvertedLookupJoin(join *memo.InvertedLookupJoinExpr) (execPlan, error) {
> ```

s/buil/build/


<!-- Sent from Reviewable.io -->

2020-06-22 16:25 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARn_OK9Q6z5yVK90OS:-MARn_OK9Q6z5yVK90OT:b-48qrp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1373)):*
> ```Go
> 
> 	inputCols := join.Input.Relational().OutputCols
> 	lookupCols := join.Cols.Difference(inputCols)
> ```

(my question from the meeting today)
Using the example in the `InvertedJoinerSpec` comment: the table has columns `| c | d | e |` and the inverted index has columns `| e' | c |`, and the input columns are `| a | b |` where the inverted join uses column b from the input. I am assuming `inputCols` here is  the set `{a, b}`. Is `lookupCols` the set `{c, e}`?


<!-- Sent from Reviewable.io -->

2020-06-22 17:57 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt_exec_factory.go, line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAS8FRWAp9bSt8YpgQA:-MAS8FRWAp9bSt8YpgQB:bfbnrjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt_exec_factory.go#L702)):*
> ```Go
> 	var scanCols sqlbase.ResultColumns
> 	if joinType != sqlbase.LeftSemiJoin && joinType != sqlbase.LeftAntiJoin {
> 		scanCols = planColumns(tableScan)
> ```

@yuzefovich 

Using this PR I am trying to implement `ConstructInvertedLookupJoin` below.
The InvertedJoinerSpec follows the pattern of JoinReaderSpec in that the rows produced for INNER and LEFT_OUTER joins include all the right table columns, though only the columns in the index will be populated.
I am confused on how that relates to this `scanCols` construction -- digging into `scanNode.initDescDefaults` (which is called by `scanNode.initTable` which is called above) it seems to me that `scanNode.resultColumns` is only the columns in `colCfg`. Is my understanding correct? And if so, does that mean that `lookupJoinNode.columns` does not include all the columns in the table?

The question of which columns, and in which order, has tripped up the integration of `invertedFilterer` so I'd like to get this clarified for `invertedJoiner` while we are still discussing this PR. 


<!-- Sent from Reviewable.io -->

2020-06-22 18:21 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @rytaft, and @sumeerbhola)

___
*[pkg/sql/opt_exec_factory.go, line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAS8FRWAp9bSt8YpgQA:-MASEm4s6PJNI0UWunxM:b-96yepm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt_exec_factory.go#L702)):*
> it seems to me that `scanNode.resultColumns` is only the columns in `colCfg`. Is my understanding correct?

Yes, `scanNode` will output only columns that are marked as "wanted" in `colCfg` (which is the second argument in `makeScanColumnsConfig`).

> And if so, does that mean that `lookupJoinNode.columns` does not include all the columns in the table?

Yes, it will contain only all columns from the input and those that are present in `lookupCols` from the table against which the lookup is performed.


<!-- Sent from Reviewable.io -->

2020-06-22 18:29 UTC, rytaft reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MASG4Ad1VbVxoroj7QE:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y5s3Y-8EI-GFqyJ4_:-MARcM1j7cmTGRJukF2u:b-gt4fx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
> if this is distributed across different partitions of the input, will this function be executed at each node that is evaluating the inverted join?

No, the optimizer builds a local plan, and the DistSQL planner converts it to a distributed plan.

> nit: the term InvertedLookupJoin predates the name of the InvertedJoiner processor. How about renaming in the optimizer code to InvertedJoin?

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARl8UA-6bHB9Aqsg_z:-MASANf44cDz_9P_FrDp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/buil/build/
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARn_OK9Q6z5yVK90OS:-MASGfTF5SFpPk7GdP8N:bur0y2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1373)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(my question from the meeting today)
Using the example in the `InvertedJoinerSpec` comment: the table has columns `| c | d | e |` and the inverted index has columns `| e' | c |`, and the input columns are `| a | b |` where the inverted join uses column b from the input. I am assuming `inputCols` here is  the set `{a, b}`. Is `lookupCols` the set `{c, e}`?

</blockquote></details>

`lookupCols` will only contain `c`. Should we add a separate field for the inverted column, similar to what we were discussing for the inverted filterer?
___
*[pkg/sql/opt/ops/relational.opt, line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y3vGo9EQFJIBuOzMM:-MARciwbBbtxDrkQKiLM:bhw2i2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/96feb134e905953c2132a956a0bdc64f2ca7ecf9/pkg/sql/opt/ops/relational.opt#L334)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The wrapping is only needed if the filter cannot be precisely (is tightly the right term?) evaluated. For JSON and Array there are cases where it won't be needed. Unless of course we need more than the primary key columns later in the query.
</blockquote></details>

Yea, eventually we should be able to avoid wrapping in an index join in some cases.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 1745 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9z1VquBSb7menDgBOO:-MARcsOO2wwtSSn7ml3F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/xform/custom_funcs.go#L1745)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This seems restricted to a single relationship.

We should add a TODO to handle more complicated expressions e.g. ST_Intersects(x, y) AND ST_Covers(<some literal>, y) where y is the indexed value. 
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/geo.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y0SHXDVrL8HMOaIBR:-MAReqbJ5-vP37dMo6iK:b-p2mo75) ([raw file](https://github.com/cockroachdb/cockroach/blob/96876125341b7a638c9548a85c46942d211452de/pkg/sql/opt/xform/geo.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does it make sense to put these functions in a new package, `pkg/sql/opt/geo`? That's what I've done with some of the partial index logic in `pkg/sql/opt/partialidx`. I don't feel too strongly either way, but I'm thinking it would be nice to be consistent with these types of "helper" packages, so I can also move that partial index "helper" code into `xform`.
</blockquote></details>

Hmm I see your point, and I think it's good to keep functionality nicely contained in packages, but I think this case is different than `partialidx` since most of the functionality here is very tightly coupled with specific functions in `xform/custom_funcs.go`. The top level function here is `tryConstrainGeoIndex`, which only really makes sense in the context of `GenerateInvertedIndexScans`. 

The code in `partialidx` (current and planned) seems much more like a library that could in theory be called from multiple places and can be nicely unit tested. I can't think of many unit tests that would make much sense here outside of what we're already testing in the xform/rules tests. I also don't expect to add a significant amount to this file... this is pretty close to everything we'll need for geospatial transformation rules.

Anyway, I don't feel that strongly and I can definitely see the argument for creating a new package, so I'm willing to be convinced otherwise. But it also seems like a bit of a waste to create a new package for one file that we don't expect to grow much....
___
*[pkg/sql/opt/xform/geo.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y4PPtBLvCIzHUgrF1:-MARfe1p92M55cBzHCta:b-r61giy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/xform/geo.go#L266)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I've seen this elsewhere, but I'm not sure what its purpose is. Is it like an assertion to ensure all correct interface methods of `DatumToInvertedExpr` have been defined for `geoDatumToInvertedExpr`?
</blockquote></details>

Yea, exactly -- it's an assertion that `geoDatumToInvertedExpr` implements `DatumToInvertedExpr`


<!-- Sent from Reviewable.io -->

2020-06-22 20:42 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @sumeerbhola)

___
*[pkg/sql/opt/xform/geo.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y0SHXDVrL8HMOaIBR:-MASkvBr8TUQTVD6Gic4:brwqeu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/96876125341b7a638c9548a85c46942d211452de/pkg/sql/opt/xform/geo.go#L11)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Hmm I see your point, and I think it's good to keep functionality nicely contained in packages, but I think this case is different than `partialidx` since most of the functionality here is very tightly coupled with specific functions in `xform/custom_funcs.go`. The top level function here is `tryConstrainGeoIndex`, which only really makes sense in the context of `GenerateInvertedIndexScans`. 

The code in `partialidx` (current and planned) seems much more like a library that could in theory be called from multiple places and can be nicely unit tested. I can't think of many unit tests that would make much sense here outside of what we're already testing in the xform/rules tests. I also don't expect to add a significant amount to this file... this is pretty close to everything we'll need for geospatial transformation rules.

Anyway, I don't feel that strongly and I can definitely see the argument for creating a new package, so I'm willing to be convinced otherwise. But it also seems like a bit of a waste to create a new package for one file that we don't expect to grow much....
</blockquote></details>

Thanks for sharing your thoughts. I agree with you. Let's leave as-is.
___
*[pkg/sql/opt/xform/geo.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y4PPtBLvCIzHUgrF1:-MASl4igBbzg6kb1KIwa:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/xform/geo.go#L266)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea, exactly -- it's an assertion that `geoDatumToInvertedExpr` implements `DatumToInvertedExpr`
</blockquote></details>

Nice, thanks!


<!-- Sent from Reviewable.io -->

2020-06-22 20:52 UTC, sumeerbhola requested changes
> Reviewed 4 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAS8FRWAp9bSt8YpgQA:-MASiqewDrHYSnhDFbki:b-qlcjyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt_exec_factory.go#L702)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

> it seems to me that `scanNode.resultColumns` is only the columns in `colCfg`. Is my understanding correct?

Yes, `scanNode` will output only columns that are marked as "wanted" in `colCfg` (which is the second argument in `makeScanColumnsConfig`).

> And if so, does that mean that `lookupJoinNode.columns` does not include all the columns in the table?

Yes, it will contain only all columns from the input and those that are present in `lookupCols` from the table against which the lookup is performed.
</blockquote></details>

Isn't this inconsistent with the `JoinReaderSpec` comment (the implementation of `joinReader` seems consistent with the spec comment).
```
  // If populated (lookup join), the `joinReader` will perform a lookup join
  // and the "internal columns" will be the concatenation of the input stream
  // columns followed by the table columns (except for semi/anti join, which
  // don't output any table columns).
```
I must be missing something obvious to you all.

And the comment in the declaration of `scanNode.cols` suggests it is all the table columns.
```
// The table columns, possibly including ones currently in schema changes.
```
Is there something going on in `initColsForScan` using the `addUnwantedAsHidden` that I am overlooking -- I don't see it being set to true except in `scrub_physical.go` (which I don't understand the purpose of).
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y5s3Y-8EI-GFqyJ4_:-MASgpkg553l2S3SEx2D:b-s2mudz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
> No, the optimizer builds a local plan, and the DistSQL planner converts it to a distributed plan.

IIUC, that means we'll need to capture what is in `datumToInvertedExpr` in the `InvertedJoinerSpec.InvertedExpr`, so it can be serialized, and use the latter to construct an implementation of `DatumToInvertedExpr` when instantiating the `invertedJoiner`. Is that correct?
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARn_OK9Q6z5yVK90OS:-MASlmf8Du3OniztLPjk:blqvdq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1373)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

`lookupCols` will only contain `c`. Should we add a separate field for the inverted column, similar to what we were discussing for the inverted filterer?
</blockquote></details>

Ah, so it won't have the inverted column. Is the optimizer assuming that the output row will have `inputCols + lookupCols` populated (for INNER and LEFT_OUTER joins)? Or does it have some other state to track that? If it is the former, we should not change things here -- I can figure out the inverted column ID and ordinal (unlike the inverted filterer case) in the implementation of `exec.Factory` since I have access to the index and table specs.


<!-- Sent from Reviewable.io -->

2020-06-22 21:08 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1373 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MARn_OK9Q6z5yVK90OS:-MASqCb_019_Ttm_F5fC:b-w5bnmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1373)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Ah, so it won't have the inverted column. Is the optimizer assuming that the output row will have `inputCols + lookupCols` populated (for INNER and LEFT_OUTER joins)? Or does it have some other state to track that? If it is the former, we should not change things here -- I can figure out the inverted column ID and ordinal (unlike the inverted filterer case) in the implementation of `exec.Factory` since I have access to the index and table specs.
</blockquote></details>

I don't think there is any other state.... this is basically the same as what is happening above with `buildLookupJoin`.


<!-- Sent from Reviewable.io -->

2020-06-22 21:26 UTC, rytaft commented
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y5s3Y-8EI-GFqyJ4_:-MASsvcr4v9sX5pCQqvU:bxj9hze) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> No, the optimizer builds a local plan, and the DistSQL planner converts it to a distributed plan.

IIUC, that means we'll need to capture what is in `datumToInvertedExpr` in the `InvertedJoinerSpec.InvertedExpr`, so it can be serialized, and use the latter to construct an implementation of `DatumToInvertedExpr` when instantiating the `invertedJoiner`. Is that correct?
</blockquote></details>

Yes, I think you're right. This will require some rethinking.....


<!-- Sent from Reviewable.io -->

2020-06-23 13:00 UTC, sumeerbhola reviewed
For general handling of inverted expressions in the join, I was imagining something like:
- The optimizer would have an implementation of InvertedExpression, called TwoVariableFunction, which involved the lookup column on the left and the inverted column on the right.
- it would walk the opt.ScalarExpr, and construct SpanExpressions (for functions involving only the right side inverted column), TwoVariableFunctions, and NonInvertedColExpressions (for functions that do not involve the right side inverted column), and call invertedexpr.{And,Or}.
- If the result is a single NonInvertedColExpression we can't do an inverted join.
- Else the tree contains only SpanExpressions and TwoVariableFunctions. Walk this tree and if there is any subtree composed only of SpanExpressions that is unioned with a TwoVariableFunction, replace it with a NonInvertedColExpression. What we are doing is finding f(left, right) OR g(right) and replacing with true, since we can't evaluate these using the join. We do want to retain f(left, right) AND g(right) since g(right) can be used to narrow the result once we have the value for left.
- If the resulting tree reduces to a NonInvertedColExpressionwe we can't do an inverted join.
- When we can do an inverted join, we would now construct the OnExpr. Walk the opt.ScalarExpr and construct a partial copy where every function involving a left side column and a right side PK column is preserved and everything else replaced with true. If the resulting expression reduces to true, there is no OnExpr. Else the resulting expression is the OnExpr.
- Serialize the OnExpr and InvertedExpression trees in the same way that the original expression that was parsed into opt.ScalarExpr was serialized. These will be placed in the InvertedJoinerSpec. The left and right side columns in the inverted expression serialization are labeled `@1` and `@2` respectively.
- The optimizer implements a factory function that takes the serialized InvertedExpression and the IndexDescriptor and returns an implementation of DatumToInvertedExpr. This will be called on each node that constructs the invertedJoiner.

It would be nice if the simple thing we do now fits with the above in how the inverted expression is represented in the InvertedJoinerSpec.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAWEs6-5u7lR1LPoM8y:bb1fa8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 702 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAS8FRWAp9bSt8YpgQA:-MAVxNAD4OzpAaDPkQgX:b-zk4c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt_exec_factory.go#L702)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Isn't this inconsistent with the `JoinReaderSpec` comment (the implementation of `joinReader` seems consistent with the spec comment).
```
  // If populated (lookup join), the `joinReader` will perform a lookup join
  // and the "internal columns" will be the concatenation of the input stream
  // columns followed by the table columns (except for semi/anti join, which
  // don't output any table columns).
```
I must be missing something obvious to you all.

And the comment in the declaration of `scanNode.cols` suggests it is all the table columns.
```
// The table columns, possibly including ones currently in schema changes.
```
Is there something going on in `initColsForScan` using the `addUnwantedAsHidden` that I am overlooking -- I don't see it being set to true except in `scrub_physical.go` (which I don't understand the purpose of).
</blockquote></details>

(for the record)
we resolved this with a side discussion -- the "inconsistency" in the 2 places is deliberate and both places are accurately describing their behavior. The projection added by DistSQLPlanner.createPlanForLookupJoin fixes things.


<!-- Sent from Reviewable.io -->

2020-06-23 13:27 UTC, rytaft reviewed
This makes sense -- thanks for spelling it out. I'll work on getting something like this implemented here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAWLXVIEpY7lZot4fRQ:b-pg7eae)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @sumeerbhola, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-06-23 22:59 UTC, rytaft commented
I've pushed some pretty hacky code -- hopefully this will help unblock your testing, @sumeerbhola. I'll try to push something cleaner tomorrow.





<!-- Sent from Reviewable.io -->

2020-06-24 14:24 UTC, sumeerbhola requested changes
This is looking good. Some small comments.

> Reviewed 25 of 25 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAahipfDA-fsKg0uIgW:bbdfi4a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAaaOo29-b4tLdPwvXt:b-67dujz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
> ```Go
> func (e *distSQLSpecExecFactory) ConstructInvertedJoin(
> 	joinType sqlbase.JoinType,
> 	invertedExpr tree.TypedExpr,
> ```

I will eventually need to convert this into `execinfrapb.Expression` and I see a `physicalplan.MakeExpression` being used by `distsql_physical_planner.go`. Will this need any remapping using the `indexVarMap` parameter or is it already in the right order?
___
*[pkg/sql/opt/exec/factory.go, line 235 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAabExC-0SFEoz2Y4Ss:-MAabExC-0SFEoz2Y4St:b-rvv1gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/exec/factory.go#L235)):*
> ```Go
> 
> 	// ConstructInvertedJoin returns a node that performs an inverted join.
> 	// datumToInvertedExpr is used along with inputCol (a column from the input)
> ```

s/datumToInvertedExpr/invertedExpr/
___
*[pkg/sql/opt/exec/factory.go, line 237 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAabLtd8eCv7Xos-APb:-MAabLte6zD8TVNZqBOj:b-z7p4x3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/exec/factory.go#L237)):*
> ```Go
> 	// datumToInvertedExpr is used along with inputCol (a column from the input)
> 	// to find the keys to look up in the index; lookupCols are ordinals for the
> 	// table columns we are retrieving.
> ```

Can you add that lookupCols does not include the inverted column.
___
*[pkg/sql/opt/xform/geo.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAag8vKBKjGWE6bhBmU:-MAag8vKBKjGWE6bhBmV:bh3o2w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/xform/geo.go#L261)):*
> ```Go
> 	return getSpanExpr(ctx, d, relationship, index.GeoConfig())
> }
> ```

up to this point in this file is mostly code movement from `custom_funcs.go`, yes?
___
*[pkg/sql/opt/invertedexpr/expression.proto, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAadTJ87UcPs_K9PXXe:-MAadTJ87UcPs_K9PXXf:bdrs6wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/invertedexpr/expression.proto#L52)):*
> ```protobuf
> // TwoVariableExpressionProto is a proto representation of an InvertedExpression
> // consisting of an expression containing two variables and an optional
> // SpanExpression. It is intended for use in expression execution.
> ```

When the optional `span_expression` is present is it meant to be a conjunction with `expression`?

I am missing where this is used.


<!-- Sent from Reviewable.io -->

2020-06-24 14:58 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAao81oCCzIcBKzq-Ak:b-jgrg03) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I will eventually need to convert this into `execinfrapb.Expression` and I see a `physicalplan.MakeExpression` being used by `distsql_physical_planner.go`. Will this need any remapping using the `indexVarMap` parameter or is it already in the right order?
</blockquote></details>

It should be able to use the same mapping as the `onCond`, which should follow the same logic as the code in `ConstructLookupJoin`
___
*[pkg/sql/opt/xform/geo.go, line 261 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAag8vKBKjGWE6bhBmU:-MAapOHkBRe1mr0LOclM:bqj0b2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/xform/geo.go#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

up to this point in this file is mostly code movement from `custom_funcs.go`, yes?
</blockquote></details>

The first commit is the code movement, so if you look at the diffs after the first commit you should be able to see the changes.
___
*[pkg/sql/opt/invertedexpr/expression.proto, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAadTJ87UcPs_K9PXXe:-MAaoavQDv355T62WzOv:bauo5eo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/invertedexpr/expression.proto#L52)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

When the optional `span_expression` is present is it meant to be a conjunction with `expression`?

I am missing where this is used.
</blockquote></details>

Yes, this is a conjunction between the two fields. It seems to me that this is the only possible configuration, since otherwise we would have a NonInvertedColExpression -- is that right?

I haven't actually used it yet -- just wanted to get something working first and make sure this is on the right track.


<!-- Sent from Reviewable.io -->

2020-06-24 19:41 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAbmrJ94ZEqen6YEWdo:budootm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It should be able to use the same mapping as the `onCond`, which should follow the same logic as the code in `ConstructLookupJoin`
</blockquote></details>

@yuzefovich 
I first want to confirm my understanding of `onCond` which is now suspect:
The comment in `DistSQLPlanner.createPlanForLookupJoin` says
```
		// Note that (regardless of the join type or the OutputColumns projection)
		// the ON condition refers to the input columns with var indexes 0 to
		// numInputNodeCols-1 and to table columns with var indexes starting from
		// numInputNodeCols.
```
And the code that initializes `post.OutputColumns` and uses it seems consistent with that. That is, the index assignment is 0-based. But the comment in `JoinReaderSpec` says that the index assigment is 1-based
```
	// "ON" expression (in addition to the equality constraints captured by the
	// orderings). Assuming that the left stream has N columns and the right
	// stream has M columns, in this expression variables @1 to @N refer to
	// columns of the left stream and variables @N to @(N+M) refer to columns in
	// the right stream.
```
Which is correct?

And what is the difference between `numInputNodeCols` and `numLeftCols`? Or are they the same?

-----
Now coming back to this `invertedExpr`. This started with a `memo.FunctionExpr` which was a single geospatial function with 2 parameters which was converted to `tree.TypedExpr` using `b.buildScalar(&ctx, join.InvertedExpr)`. I saw somewhere that `TypedExpr` uses `IndexedVars`. How were the `IndexedVar.Idx` in this `TypedExpr` assigned? This affects how I would construct the `indexVarMap` parameter for `physicalplan.MakeExpression`.


<!-- Sent from Reviewable.io -->

2020-06-24 19:55 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAbrQXY16mW0cXFtLoH:budouvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
> Which is correct?

I think, in a sense, both are correct. For the purposes of serialization we use 1-based ordinal assignment, i.e. `@1 < @2` will compare zeroth and first columns, but everywhere else we use 0-based indices (if you're curious where this "+1" behavior happens, it's in the guts of `fmtCtx.FormatNode(expr)` call in `MakeExpression` - `pkg/sql/sem/tree/indexed_vars.go:98`).

> And what is the difference between numInputNodeCols and numLeftCols? Or are they the same?

I feel like they are the same, but I'm not certain because `plan.ResultColumns` and `planColumns(planNode)` might return different things. The former contains only the columns that are output by the whole physical plan (which might have projection on top of it, so certain columns could be projected out) whereas the latter - I think - returns the result columns before the projection is applied (i.e. what the "core" of the processor will output).


<!-- Sent from Reviewable.io -->

2020-06-24 20:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAbwQwm8VY7Zg9cczfY:b-xdp9il) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
> I saw somewhere that `TypedExpr` uses `IndexedVar`s. How were the `IndexedVar.Idx` in this `TypedExpr` assigned?

I'm not sure whether this was a question for me, but I think it happens in `execbuilder.Builder.indexedVar()` method (during `IndexedVarWithType`). But I don't think that you need to pay attention to this.

> This affects how I would construct the `indexVarMap` parameter for `physicalplan.MakeExpression`.

I think you could assume that first `0..numInputNodeCols-1` columns refer to the input plan, and `numInputNodeCols..numInputNodeCols+len(lookupTableCols)` to the lookup table. There might be some adjustment needed because of an extra column for the inverted column though.


<!-- Sent from Reviewable.io -->

2020-06-24 21:49 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAcFDcz9HMg--eFc-4i:bpjj2bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
> I think you could assume that first 0..numInputNodeCols-1 columns refer to the input plan, and numInputNodeCols..numInputNodeCols+len(lookupTableCols) to the lookup table. There might be some adjustment needed because of an extra column for the inverted column though.

I am assuming by `lookupTableCols` you mean `lookupCols` which is currently only the PK columns of the table (as per the discussion with @rytaft in `relational.go` below). That doesn't include the inverted column, which is one of the two variables in this inverted expression.
I think we are overcomplicating the situation -- we don't need the usual `IndexedVar.Idx` assignment since we don't need any generality here. Here we just need two indices 0 (for the input col) and 1 for the inverted col. And once we serialize it like that in `InvertedJoinerSpec.InvertedExpr` the execution side consumer of this serialization is also code that is being added in this PR. We are not beholden to some existing machinery that we need to conform to. @rytaft and @yuzefovich -- do you think we could simplify the conversion from `memo.FunctionExpr` to `execinfrapb.Expression` for this inverted expression case?


<!-- Sent from Reviewable.io -->

2020-06-24 21:59 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAcK6_CDe_8s4W-8N0K:b-dcm2od) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I think you could assume that first 0..numInputNodeCols-1 columns refer to the input plan, and numInputNodeCols..numInputNodeCols+len(lookupTableCols) to the lookup table. There might be some adjustment needed because of an extra column for the inverted column though.

I am assuming by `lookupTableCols` you mean `lookupCols` which is currently only the PK columns of the table (as per the discussion with @rytaft in `relational.go` below). That doesn't include the inverted column, which is one of the two variables in this inverted expression.
I think we are overcomplicating the situation -- we don't need the usual `IndexedVar.Idx` assignment since we don't need any generality here. Here we just need two indices 0 (for the input col) and 1 for the inverted col. And once we serialize it like that in `InvertedJoinerSpec.InvertedExpr` the execution side consumer of this serialization is also code that is being added in this PR. We are not beholden to some existing machinery that we need to conform to. @rytaft and @yuzefovich -- do you think we could simplify the conversion from `memo.FunctionExpr` to `execinfrapb.Expression` for this inverted expression case?

</blockquote></details>

I haven't reviewed this PR, but I see no problem in using a simple "binary" mapping as the one you're describing when serializing this expression. Just make sure to highlight in the comments that `InvertedJoinerSpec.InvertedExpr` is serialized/deserialized using a custom "protocol" (meaning that `@1` and `@2` ordinals in the expression mean different things than in all other places where `execinfrapb.Expression` is used).


<!-- Sent from Reviewable.io -->

2020-06-25 12:50 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAfVQ9i0gEitqdsLQrx:bdekpxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I haven't reviewed this PR, but I see no problem in using a simple "binary" mapping as the one you're describing when serializing this expression. Just make sure to highlight in the comments that `InvertedJoinerSpec.InvertedExpr` is serialized/deserialized using a custom "protocol" (meaning that `@1` and `@2` ordinals in the expression mean different things than in all other places where `execinfrapb.Expression` is used).
</blockquote></details>

Using a simpler mapping is also fine with me, but I don't really see how it would be cleaner than just using the same column mapping as the `onCond`. If you look at the code I added to `inverted_joiner.go` in this PR, re-using `onExprColTypes` for the `invertedExpr` makes things pretty clean (at least when converting from `execinfrapb.Expression` back to `tree.TypedExpr`).

I don't think the `invertedJoiner` needs to know anything about what's in `invertedExp` other than the code I already added, right?


<!-- Sent from Reviewable.io -->

2020-06-25 13:24 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAfaj2T0Ab64TbNiTKg:bsct0vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Using a simpler mapping is also fine with me, but I don't really see how it would be cleaner than just using the same column mapping as the `onCond`. If you look at the code I added to `inverted_joiner.go` in this PR, re-using `onExprColTypes` for the `invertedExpr` makes things pretty clean (at least when converting from `execinfrapb.Expression` back to `tree.TypedExpr`).

I don't think the `invertedJoiner` needs to know anything about what's in `invertedExp` other than the code I already added, right?
</blockquote></details>

I see the following in `inverted_joiner.go`
```
		var invertedExprHelper execinfra.ExprHelper
		if err := invertedExprHelper.Init(spec.InvertedExpr, onExprColTypes, ij.EvalCtx); err != nil {
			return nil, err
		}
		ij.datumToInvertedExpr, err = xform.NewDatumToInvertedExpr(invertedExprHelper.Expr, ij.index)
```
The `onExprColTypes` has the type of the original column that was indexed. So the call to `invertedExprHelper.Init` should work even with type checking. Currently `NewDatumToInvertedExpr` does not care about the indices since it only uses the `TypedExpr` for the function name.
```
	fn, ok := expr.(*tree.FuncExpr)
	...
	name := fn.Func.FunctionReference.String()
```
I am assuming that when we extend this to more than a single function, `xform.NewDatumToInvertedExpr` will also need to receive as parameters the `IndexedVar` for the left and right columns. Is that correct?

So this sounds ok.
Could you update the comment in `InvertedJoinerSpec.InvertedExpr` regarding the numbering of the columns?


<!-- Sent from Reviewable.io -->

2020-06-25 15:47 UTC, rytaft reviewed
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAg86sgEKRyc9S6NO3u:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAg1aYo0FHy83vJ2J4F:b2g8h53) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
> I am assuming that when we extend this to more than a single function, xform.NewDatumToInvertedExpr will also need to receive as parameters the IndexedVar for the left and right columns. Is that correct?

In theory yes, but in practice I think we may be able to make it work without the IndexedVars. When we build the plan in the optimizer we will have already checked that the parameters in the function correspond to a column from the input, the indexed column, or a constant, and that they are in the expected order (I have a TODO right now to commute the function if they don't match the order, but I can make sure that the functions stored in `InvertedExpr` have a consistent ordering).

It's possible that I'm missing something, but in that case we could definitely do as you suggest and add a parameter to `xform.NewDatumToInvertedExpr` for the indexed vars.

> Could you update the comment in InvertedJoinerSpec.InvertedExpr regarding the numbering of the columns?

Done.
___
*[pkg/sql/opt/exec/factory.go, line 235 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAabExC-0SFEoz2Y4Ss:-MAg7K5l0OWaSvKyB6-s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/exec/factory.go#L235)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/datumToInvertedExpr/invertedExpr/
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/factory.go, line 237 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAabLtd8eCv7Xos-APb:-MAg7WJcAzWqKTsb5mUL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/exec/factory.go#L237)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add that lookupCols does not include the inverted column.
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational.go, line 1364 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-M9y5s3Y-8EI-GFqyJ4_:-MAg7bIeBop9bBTh3gqG:bblz7l8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0aa06d40edbec92d22ea863ac9b317b27550a89/pkg/sql/opt/exec/execbuilder/relational.go#L1364)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yes, I think you're right. This will require some rethinking.....
</blockquote></details>

This has been reworked to use a `tree.TypedExpr`.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 3044 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAg8MjJCrJxfOAKG3sP:-MAg8MjJCrJxfOAKG3sQ:bb3c6va) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/xform/custom_funcs.go#L3044)):*
> ```Go
> // NewDatumToInvertedExpr returns a new DatumToInvertedExpr. Currently there
> // is only one possible implementation returned, geoDatumToInvertedExpr.
> func NewDatumToInvertedExpr(
> ```

I'm not sure if this is the best place for this. I would have liked to put it in the `invetedexpr` package, but that would cause an import cycle.
___
*[pkg/sql/opt/invertedexpr/expression.proto, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAadTJ87UcPs_K9PXXe:-MAg7p0HBoIHFmt53p5f:b-y4if3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/invertedexpr/expression.proto#L52)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yes, this is a conjunction between the two fields. It seems to me that this is the only possible configuration, since otherwise we would have a NonInvertedColExpression -- is that right?

I haven't actually used it yet -- just wanted to get something working first and make sure this is on the right track.
</blockquote></details>

Removed this for now. Once it's needed I'll add it back.


<!-- Sent from Reviewable.io -->

2020-06-25 16:19 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAgG_kt-39BuSuVoJ9f:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/distsql_spec_exec_factory.go, line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAaaOo29-b4tLdPwvXs:-MAgDAmq1sPou6TfV737:b-xyj08s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/distsql_spec_exec_factory.go#L402)):*
>  I can make sure that the functions stored in InvertedExpr have a consistent ordering

Sounds good.
___
*[pkg/sql/opt/xform/custom_funcs.go, line 3044 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAg8MjJCrJxfOAKG3sP:-MAgG1_EBJYbKRH-8MMq:b-9kdb26) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/xform/custom_funcs.go#L3044)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm not sure if this is the best place for this. I would have liked to put it in the `invetedexpr` package, but that would cause an import cycle.
</blockquote></details>

I don't have any better ideas.
___
*[pkg/sql/opt/invertedexpr/expression.proto, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAadTJ87UcPs_K9PXXe:-MAgFVu6D3WHbNO8hpGL:b-kixatt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/invertedexpr/expression.proto#L52)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Removed this for now. Once it's needed I'll add it back.
</blockquote></details>

Do you think this will ever be needed -- I thought `execinfrapb.Expression` was sufficient based on our discussion?
Since the code in this file is not being changed, do you want to undo the file renaming?


<!-- Sent from Reviewable.io -->

2020-06-25 17:00 UTC, rytaft reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-:-MAgPmhM0YUSsq-q96wL:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/opt/invertedexpr/expression.proto, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50252#-MAadTJ87UcPs_K9PXXe:-MAgOef17ZJzOvU3-Xul:b-6ifypi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8454e99e99b7eef030b0ab875a8f2ea9865b690/pkg/sql/opt/invertedexpr/expression.proto#L52)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do you think this will ever be needed -- I thought `execinfrapb.Expression` was sufficient based on our discussion?
Since the code in this file is not being changed, do you want to undo the file renaming?
</blockquote></details>

Yea, it might not be needed. Changed the name back.


<!-- Sent from Reviewable.io -->

2020-06-25 17:55 UTC, merged