kvserver: prevent follower reads during range merge critical state
cockroachdb/cockroach pull request #50265
Opened 2020-06-16 09:57 UTC by aayushshah15

Before this commit, during a merge, the RHS leaseholder’s store
could continue broadcasting (actionable) closed timestamp updates
even after it had been subsumed. This allowed the followers to be
able to serve follower reads past the subsumption time of RHS.
Additionally, after the merge, if the LHS had a lower closed timestamp
than the RHS, it could allow writes to the keyspan owned by RHS
at timestamps lower than the RHS’s max closed timestamp.

This commit fixes this bug by requiring that the followers catch up
to a LeaseAppliedIndex that belongs to the entry succeeding the
Subsume request.

Fixes #44878

Release note (bug fix): Fixes a bug that allowed follower reads
during the critical state of a merge transaction.

2020-06-16 09:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50265)
<!-- Reviewable:end -->

2020-06-16 10:02 UTC, aayushshah15 commented
I feel uneasy about having `store.cfg` exported, please let me know if I missed something cleaner. 

In a future commit, I will add a test that forces a lease transfer during the merge critical state.

2020-06-16 15:49 UTC, andreimatei requested changes
Were there supposed to be one commits or two in here? I see what with a message looking like the squash of two.

Nit: there's a lot diffs created by the exporting of that `Cfg` guy. Moving that change to a dedicated commit would make reviewing easier.


Nit: the release note is too technical; users don't understand this. Also the tense is wrong (as per https://wiki.crdb.io/wiki/spaces/CRDB/pages/186548364/Release+notes) - say "Fixed a bug".
> Release note (bug fix): Fixes a bug that allowed follower reads
> during the critical state of a merge transaction.

I'd say

> Fixed a rare bug causing transaction serializability violations when using follower reads.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-M9xP9BsA8a8EZxaWuQX:b-vvy8ld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xULwX3F2bPAW0Lmzu:-M9xULwX3F2bPAW0Lmzv:bc8zbx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/closed_timestamp_test.go#L710)):*
> ```Go
> // done.
> func setupClusterForClosedTSTestingWithCustomKnobs(
> 	ctx context.Context, t *testing.T, targetDuration time.Duration, knobs base.TestingKnobs,
> ```

might as well take a `TestClusterArgs`.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 801 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xTprz9p771r1gdUZf:-M9xTprz9p771r1gdUZg:b3vdnlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/closed_timestamp_test.go#L801)):*
> ```Go
> 	repls []*kvserver.Replica,
> ) {
> 	defaultTestingKnobs := base.TestingKnobs{
> ```

Consider keeping a single `setupClusterForClosedTSTesting()` function by extracting `defaultTestingKnobs` into a `aggressiveResolvedTSPushKnobs` that everybody passed in. That way it'll be easier for tests to compose these default knobs with other additional knobs.
___
*[pkg/kv/kvserver/replica.go, line 1330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xUvu57QxJu71TmKRa:-M9xUvu57QxJu71TmKRb:bu754r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1330)):*
> ```Go
> // neighbor is in its critical phase and, if so, arranges to block all requests
> // until the merge completes.
> func (r *Replica) maybeWatchForMerge(ctx context.Context, untrack closedts.ReleaseFunc) error {
> ```

pls comment the new param
___
*[pkg/kv/kvserver/replica.go, line 1361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xo35w1NVxGhWXzxfr:-M9xo35w1NVxGhWXzxfs:blw9q11) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1361)):*
> ```Go
> 		// Nothing more to do.
> 		r.mu.Unlock()
> 		return nil
> ```

don't we need to call `untrack()` with LAI+1 in this case?
___
*[pkg/kv/kvserver/replica.go, line 1370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xX2Zo9BTSFHn4OWLI:-M9xX2Zo9BTSFHn4OWLJ:bmyjlrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1370)):*
> ```Go
> 	// arrived and now, which is rare but entirely legal.
> 	r.unquiesceLocked()
> 	// We prevent replicas from being able to serve follower reads on timestamps
> ```

I think this comment needs to spell things out more: say that we block follower reads by publishing a MLAI that's never going to come in the happy case, and we do that because the closed timestamps that are published from now on will not be reflected in the LHS's tscache after the merge.
___
*[pkg/kv/kvserver/replica.go, line 1372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xWVNt94SJB8pGrQFp:-M9xWVNt94SJB8pGrQFq:b-yhvq7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1372)):*
> ```Go
> 	// We prevent replicas from being able to serve follower reads on timestamps
> 	// that fall between the subsumption time (FreezeStart) and the timestamp at
> 	// which the merge transaction commits or aborts (i.e. when a merge is in its
> ```

s/when a merge/the timestamp window representing the range's critical state


Also I don't see the syntagm "critical state" used elsewhere around here. Maybe say something more descriptive like "subsumed state".
___
*[pkg/kv/kvserver/replica.go, line 1382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xVn4N6FLd6zEOFOdK:-M9xVn4N6FLd6zEOFOdL:b-ek56it) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1382)):*
> ```Go
> 	// has been subsumed are lease requests, which do not bump the LAI.
> 	//
> 	// See https://github.com/cockroachdb/cockroach/issues/44878 for discussion.
> ```

nit: I personally consider most such issue links to be just click bait. The comments should usually be sufficient for explaining what's going on; when they're not sufficient because we failed to write them properly, there's git blame.
___
*[pkg/kv/kvserver/replica_read.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xgDR2Ch9hcqzIHZv1:-M9xgDR2Ch9hcqzIHZv2:b-omf9gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L127)):*
> ```Go
> 	log.Event(ctx, "executing read-only batch")
> 
> 	untrack := r.maybeTrackProposal(ctx, ba)
> ```

can this down, move next to `res.Local.ReleaseFunc = untrack` ?
___
*[pkg/kv/kvserver/replica_read.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xeOD3EamJ7d1S9pOZ:-M9xeOD3EamJ7d1S9pO_:b-hjepry) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eea0be192499fa7d29b5eca5ed14173982b25f0/pkg/kv/kvserver/replica_read.go#L130)):*
> ```Go
> 		}
> 		br, res, pErr = evaluateBatch(ctx, kvserverbase.CmdIDKey(""), rw, rec, nil, ba, true /* readOnly */)
> ```

spurious diff
___
*[pkg/kv/kvserver/replica_read.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xmJXi2atmD9-IUYJ2:-M9xmJXi2atmD9-IUYJ3:b-quohxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L150)):*
> ```Go
> 		return nil, res, pErr
> 	}
> 	res.Local.ReleaseFunc = untrack
> ```

Is this indirection really needed? Can't we simply `untrack` here?
I see that there are some early returns in `maybeWatchForMerge` that don't untrack  with LAI+1, but I can't tell which ones are expected. Plus one of them seems wrong to me.


If the indirection is necessary, can we at least bind all the arguments to the closure we put in `res.Local.ReleaseFunc`? They shouldn't change in between here and `maybeWatchForMerge`, should they?  The closure could take a single bool about whether we're watching for the merge or not (a false would translate to all zeros to `untrack()`).
___
*[pkg/kv/kvserver/replica_read.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xf8NW7qTxl5Iy8OVN:-M9xf8NW7qTxl5Iy8OVO:b-9t6hyu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L154)):*
> ```Go
> }
> 
> func (r *Replica) maybeTrackProposal(
> ```

This funky method has one caller. Inline it there and then I won't have to ask for a better name and comments.
___
*[pkg/kv/kvserver/replica_read.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xm8Ws7L9WuVrJ6v_N:-M9xm8Ws7L9WuVrJ6v_O:b-pgdvos) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L [...]

2020-06-16 17:34 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xo35w1NVxGhWXzxfr:-M9y5TJCCmM_GpZIYD0_:b-bkn690) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1361)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't we need to call `untrack()` with LAI+1 in this case?
</blockquote></details>

We only need to release this tracked proposal the first time we run `maybeWatchForMerge` (which should always be right after the subsume request evaluation unless there is a lease transfer). Any time we see that we've already started the `mergeComplete` channel, we should already have released this proposal then. This is what the comment below (in `maybeTrackProposal`) talks about, I'll make it clearer.
___
*[pkg/kv/kvserver/replica_read.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xgDR2Ch9hcqzIHZv1:-M9y8iTb7Jf_lE_BX82r:b-2yb2re) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L127)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can this down, move next to `res.Local.ReleaseFunc = untrack` ?
</blockquote></details>

Starting to track the proposal after evaluation of the subsume request seemed problematic for the given scenario:
t1: RHS leaseholder begins evaluating the subsume request (i.e. t1 is our `FreezeStart`)
t2: The leaseholder's store broadcasts a closed timestamp that is above t1
t3: Now we begin tracking the proposal, but it's too late because we've already emitted a closed timestamp above `FreezeStart`

Does that make sense? Let me know if I'm missing something.


<!-- Sent from Reviewable.io -->

2020-06-16 18:23 UTC, nvanbenschoten commented
> there's a lot diffs created by the exporting of that Cfg guy. Moving that change to a dedicated commit would make reviewing easier.

Big +1 on this. The main change here is small but subtle and difficult to prove the correctness of. It's a major burden for reviewers and future readers when such changes are mixed in with a refactor that touches 46 files.

> // NB: The above statement relies on the invariant that the LAI that
> // follows a Subsume request will be applied only after the merge aborts, as
> // the RHS replicas will get destroyed if the merge successfully commits. This
> // invariant is upheld because the only Raft proposals allowed after a range
> // has been subsumed are lease requests, which do not bump the LAI.

Are we sure about this? I mentioned in https://github.com/cockroachdb/cockroach/issues/44878#issuecomment-642824033 that I'm not convinced this invariant is currently upheld. It relies on latching and that there are Requests that perform Raft proposals that do not acquire any latches that conflict with the `SubsumeRequest` request, such as `ComputeChecksumRequest`s.

Given that this is so critical for correctness, I think it would be worth adding assertions around raft proposal logic to ensure that we uphold this invariant.

2020-06-16 18:26 UTC, aayushshah15 commented
Sounds good, feel free to hold off on reviewing until I reorg it into multiple commits. I'll also add assertions around the invariant.

2020-06-26 00:02 UTC, aayushshah15 reviewed
I reorganized a bunch of stuff and added a new test that forces a lease transfer on the RHS during the merge (& ensures that our closed timestamp guarantees are upheld). 

With regards to ComputeChecksumRequest: It turns out that the `ComputeChecksum` request does "acquire latches" even though it doesn't declare any keys. However, [`checkExecutionCanProceed` only cares about the latchGuard being non-nil](https://github.com/cockroachdb/cockroach/blob/c29c57ad62ea31704d2560714b9edc853b403a52/pkg/kv/kvserver/replica.go#L1107) on the leaseholder. It almost seems like an unintentional consequence. Should we be more explicit about this? Sorry for not investigating this properly earlier. I added an assertion that blows up if it sees a proposal that would bump the LAI while the range is subsumed, along with an accompanying test.

This is RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MAhgu4_8_yAH-grEIgd:b72860a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xULwX3F2bPAW0Lmzu:-MA2bQwP25p63DPswbJt:b260hja) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/closed_timestamp_test.go#L710)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

might as well take a `TestClusterArgs`.
</blockquote></details>

Done, let me know if I misunderstood you. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 801 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xTprz9p771r1gdUZf:-MA2bWnM6gH5yMS6kxFN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/closed_timestamp_test.go#L801)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Consider keeping a single `setupClusterForClosedTSTesting()` function by extracting `defaultTestingKnobs` into a `aggressiveResolvedTSPushKnobs` that everybody passed in. That way it'll be easier for tests to compose these default knobs with other additional knobs.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/replica.go, line 1330 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xUvu57QxJu71TmKRa:-MA3E63S-uWMzxHBi-wy:b-8j5tg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1330)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment the new param
</blockquote></details>

Removed the indirection.
___
*[pkg/kv/kvserver/replica.go, line 1370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xX2Zo9BTSFHn4OWLI:-MA3IIG0DOQNLCN0rYRM:b-5070ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1370)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this comment needs to spell things out more: say that we block follower reads by publishing a MLAI that's never going to come in the happy case, and we do that because the closed timestamps that are published from now on will not be reflected in the LHS's tscache after the merge.
</blockquote></details>

Done, let me know if you still find it lacking.
___
*[pkg/kv/kvserver/replica.go, line 1372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xWVNt94SJB8pGrQFp:-MA3HlRjAJyxydyOlRTO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1372)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/when a merge/the timestamp window representing the range's critical state


Also I don't see the syntagm "critical state" used elsewhere around here. Maybe say something more descriptive like "subsumed state".
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica.go, line 1382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xVn4N6FLd6zEOFOdK:-MA3Hmn85ELzhVdt56XI:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica.go#L1382)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I personally consider most such issue links to be just click bait. The comments should usually be sufficient for explaining what's going on; when they're not sufficient because we failed to write them properly, there's git blame.
</blockquote></details>

Removed.
___
*[pkg/kv/kvserver/replica_read.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xmJXi2atmD9-IUYJ2:-MA38OEl3ufIW-2qrtbr:b6ld7d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L150)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is this indirection really needed? Can't we simply `untrack` here?
I see that there are some early returns in `maybeWatchForMerge` that don't untrack  with LAI+1, but I can't tell which ones are expected. Plus one of them seems wrong to me.


If the indirection is necessary, can we at least bind all the arguments to the closure we put in `res.Local.ReleaseFunc`? They shouldn't change in between here and `maybeWatchForMerge`, should they?  The closure could take a single bool about whether we're watching for the merge or not (a false would translate to all zeros to `untrack()`).
</blockquote></details>

You're correct that the indirection isn't really necessary since we don't need to `untrack()` in the lease acquisition path (which is what the initial check in `maybeWatchForMerge` is for)
___
*[pkg/kv/kvserver/replica_read.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xf8NW7qTxl5Iy8OVN:-MA31ZRi9P8ueB2gXw38:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L154)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This funky method has one caller. Inline it there and then I won't have to ask for a better name and comments.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/replica_read.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xm8Ws7L9WuVrJ6v_N:-MA3Ia5q8njboUZZamY-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L160)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't quite understand the "for the first time" part. Consider axing it.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_read.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xkRbrD-0diqaZ_hL6:-MAheI6k3xzmuvao7CVR:b-wbjpn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L162)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think there's something missing here - the other return value from `Track` is a minimum timestamp for the (Subsume) request. I think we need to reject the `Subsume` request if its timestamp is above it. I think the comment above should spell out the important of Subsume's ts. 
</blockquote></details>

Not applicable as discussed offline.
___
*[pkg/kv/kvserver/batcheval/result/result.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xfpONBM3vs2FTHJIF:-MA3BBAv3rhReg7TD0qq:b-yliln) ([raw file](http [...]

2020-06-26 14:37 UTC, aayushshah15 commented
The test that forces a lease transfer during the merge is flakey under contention because it relies on the merge txn not retrying 😞. Trying to fix that..

2020-06-26 16:22 UTC, andreimatei approved these changes
LGTM

nit: I imagine I'm probably driving you crazy with this this stuff, but I think r4 and r5 should be squashed with r2. The testing really belongs with the commit fixing the issue. And the assertion is tiny, and also tied to the main thing this patch is doing. `TestStoreRangeMergeCheckConsistencyAfterSubsumption` is more random, that can be a separate commit indeed.

Btw, I also find it much better to rewrite all the commits every time I update a PR (like, rebase them all), so that reviewable shows the new commits as a contiguous block, instead of interspersing old commits and new commits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MAlL2PI-Ggs1uog2baP:b-ha263j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1534 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlQ6Dq8nqkdN5lKUoa:-MAlQ6Dq8nqkdN5lKUob:b-4id8vp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1534)):*
> ```Go
> // 2. Once a merge is aborted, pending (and future) requests will be allowed to
> // be proposed. This is meant as a sanity check for the assertion at the
> // end of Replica.propose().
> ```

pls put more words here describing this assertion
___
*[pkg/kv/kvserver/client_merge_test.go, line 1599 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlQJkXCmABWIrbFwDF:-MAlQJkXCmABWIrbFwDG:b-gt7p7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1599)):*
> ```Go
> 	case <-checkConsistencyResp:
> 		t.Fatalf("expected the consistency check to wait until the merge was complete")
> 	case <-time.After(1 * time.Second):
> ```

you probably want more than a second here and below; tests run on loaded machines, particularly under testrace.
Consider `testutils.SucceedsSoon()` - that's the go to for waiting a while
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 469 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlODpvD1u-BGKYfcMx:-MAlODpvD1u-BGKYfcMy:b-fib5xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/86f49d0ad6df94eb90d26b592c06bbed8c17b347/pkg/kv/kvserver/closed_timestamp_test.go#L469)):*
> ```Go
> 	t.Run("without lease transfer", func(t *testing.T) {
> 		ctx := context.Background()
> 		blockMergeTrigger := make(chan interface{}, 10) // headroom in case the merge txn retries
> ```

why `interface{}` and not `hlc.Timestamp` ?
___
*[pkg/kv/kvserver/replica_raft.go, line 337 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlMLgb5w26WBn1lmmU:-MAlMLgb5w26WBn1lmmV:bz65d50) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/replica_raft.go#L337)):*
> ```Go
> 	if maxLeaseIndex != 0 {
> 		r.mu.RLock()
> 		defer r.mu.RUnlock()
> ```

nit: I'd just put the RUnlock() below, without a defer. You want to hold this lock for as little as possible, and tie it with the `mergeInProgressRLocked()` call. Like, if there's more code added to this method, you don't want it running under the lock.
If the log.Fatal() is hit, the lock won't be release anyway.
___
*[pkg/kv/kvserver/replica_read.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-M9xgDR2Ch9hcqzIHZv1:-MAlJLfqBz9MzGeU68Ay:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1afc52bc258e7a6aa0fe5a2de54557d2752e7c6c/pkg/kv/kvserver/replica_read.go#L127)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Starting to track the proposal after evaluation of the subsume request seemed problematic for the given scenario:
t1: RHS leaseholder begins evaluating the subsume request (i.e. t1 is our `FreezeStart`)
t2: The leaseholder's store broadcasts a closed timestamp that is above t1
t3: Now we begin tracking the proposal, but it's too late because we've already emitted a closed timestamp above `FreezeStart`

Does that make sense? Let me know if I'm missing something.
</blockquote></details>

ack
___
*[pkg/kv/kvserver/replica_read.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlKYbo6fEDyvcKjd4h:-MAlKYbo6fEDyvcKjd4i:b-tl05tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/35d268266785ea3ff2d0d9d48479c0567287dd4d/pkg/kv/kvserver/replica_read.go#L126)):*
> ```Go
> 	log.Event(ctx, "executing read-only batch")
> 
> 	untrack := func(_ context.Context, _ ctpb.Epoch, _ roachpb.RangeID, _ ctpb.LAI) {}
> ```

I'd suggest simplifying this `untrack()` to only take a bool - whether or not the range has been subsumed, and closing over all the other arguments right here.


<!-- Sent from Reviewable.io -->

2020-06-27 18:33 UTC, nvb requested changes
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAqw6Mx5qfzD5q1prr-:-MAqw6My5QQtq2A4Pw_f:bmktz8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1530)):*
> ```Go
> 
> // TestStoreRangeMergeCheckConsistencyAfterSubsumption verifies the the following:
> // 1. While a range is subsumed, CheckConsistency requests wait until the merge
> ```

`s/CheckConsistency/ComputeChecksum/g` 
___
*[pkg/kv/kvserver/client_merge_test.go, line 1535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAquvzp4pNRdNMgpwZu:-MAquvzp4pNRdNMgpwZv:bkl54xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1535)):*
Unfortunately, I don't think this is testing the right thing. Or at least, it's not testing enough to disprove the absence of the race condition we're concerned with. I'm still not convinced we're in the clear here.

A `ComputeChecksum` request will `checkForPendingMergeRLocked` if the Subsume request has already completed and installed the `mergeComplete` channel by the time that it begins execution. However, that alone does not ensure that the `ComputeChecksum` request will perform this check _after the channel is installed_. You mentioned that
> the ComputeChecksum request does "acquire latches" even though it doesn't declare any keys

This is the problem here. If the `ComputeChecksum` is concurrent with the `Subsume`, we don't have any guarantee that the order of operations won't be:
1. ComputeChecksum acquires an empty set of latches
2. SubsumeRequest acquires its latches
3. ComputeChecksum `checkForPendingMergeRLocked` and finds nothing
4. SubsumeRequest installs `mergeComplete` channel with current LAI
5. `ComputeChecksum` evaluates and proposes with higher LAI, breaking our invariant

Latches are what we use to provide this kind of synchronization which enforces ordering between requests. So we should use them here to ensure that all requests serialize with `SubsumeRequests`. I think it would be fine to make `ComputeChecksum` acquire _some_ kind of small latch that ensures this property.

More generally, though, we need to ensure that this is true for all request types. I wonder how we can automate this verification. A unit test that loops over all registered `cmds` in `kvserver/batcheval` and ensures that they all acquire overlapping spans with a `SubsumeRequest` for the same range would be one approach. An issue I see with that is that we don't actually have access to all requests in `kvserver/batcheval` because some, like `ExportRequest`, are registered externally.

Maybe we could combine that with some kind of race-only (see `util.RaceEnabled`) assertion in the `Command.DeclareKeys` functions themselves? We could wrap each `Command.DeclareKeys` function with something like the following when declared to instrument each of them with such a check:
```
+++ b/pkg/kv/kvserver/batcheval/command.go
@@ -60,7 +60,7 @@ func RegisterReadWriteCommand(
        impl func(context.Context, storage.ReadWriter, CommandArgs, roachpb.Response) (result.Result, error),
 ) {
        register(method, Command{
-               DeclareKeys: declare,
+               DeclareKeys: maybeWrapDeclareKeysFunc(declare),
                EvalRW:      impl,
        })
 }
@@ -73,7 +73,7 @@ func RegisterReadOnlyCommand(
        impl func(context.Context, storage.Reader, CommandArgs, roachpb.Response) (result.Result, error),
 ) {
        register(method, Command{
-               DeclareKeys: declare,
+               DeclareKeys: maybeWrapDeclareKeysFunc(declare),
                EvalRO:      impl,
        })
 }
@@ -97,3 +97,34 @@ func LookupCommand(method roachpb.Method) (Command, bool) {
        cmd, ok := cmds[method]
        return cmd, ok
 }
+
+func assertSerializesWith(inner, other declareKeysFunc) declareKeysFunc {
+       return func(desc *roachpb.RangeDescriptor, h roachpb.Header, r roachpb.Request, latchSpans, lockSpans *spanset.SpanSet) {
+               inner(desc, h, r, latchSpans, lockSpans)
+
+               var otherLatchSpans, otherLockSpans spanset.SpanSet
+               other(desc, h, nil, otherLatchSpans, otherLockSpans)
+               if !latchSpans.Intersects(otherLatchSpans) { // TODO: implement this fn
+                       panic("...")
+               }
+       }
+}
+
+func assertSerializedWithSubsume(inner declareKeysFunc) declareKeysFunc {
+       return assertSerializesWith(
+               inner,
+               func(desc *roachpb.RangeDescriptor, h roachpb.Header, _ roachpb.Request, latchSpans, lockSpans *spanset.SpanSet) {
+                       r := &SubsumeRequest{RightDesc: desc}
+                       declareKeysSubsume(desc, header, r, latchSpans, lockSpans)
+               }
+       )
+}
+
+func maybeWrapDeclareKeysFunc(inner declareKeysFunc) declareKeysFunc {
+       if !util.RaceEnabled {
+               return inner
+       }
+       inner = assertSerializedWithSubsume(inner)
+       // ... could add other assertions in the future ...
+       return inner
+}
```

By the way, I bet you could get the assertion you added below (which expresses the invariant we want to guarantee surprisingly well) to fire if you removed the `mergeEndTxnReceived` channel and run this under stress. This `mergeEndTxnReceived` is actually serving as exactly the kind of synchronization that we want but don't currently have from latches.
___
*[pkg/kv/kvserver/replica_raft.go, line 337 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlMLgb5w26WBn1lmmU:-MAqx2Kp9ZQQBfw9SQOc:b-gar9fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/replica_raft.go#L337)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I'd just put the RUnlock() below, without a defer. You want to hold this lock for as little as possible, and tie it with the `mergeInProgressRLocked()` call. Like, if there's more code added to this method, you don't want it running under the lock.
If the log.Fatal() is hit, the lock won't be release anyway.
</blockquote></details>

Or create a `mergeInProgress` method on `Replica`. We already have a pair of `getMergeCompleteCh` and `getMergeCompleteChRLocked` methods.

While here, do you mind moving the `mergeInProgressRLocked` method down next to the other two?


<!-- Sent from Reviewable.io -->

2020-06-29 14:14 UTC, aayushshah15 commented
Would it be too invasive to have each type of request declare read-only access to a unique key associated with the type? This lets us clearly express "request level" conflicts like the one in question: since we want subsume requests to conflict with every other request, we can have it declare writes on all of these request keys.

2020-06-29 19:49 UTC, nvanbenschoten commented
> Would it be too invasive to have each type of request declare read-only access to a unique key associated with the type? This lets us clearly express "request level" conflicts like the one in question: since we want subsume requests to conflict with every other request, we can have it declare writes on all of these request keys.

Every latch acquired comes with a cost, so I don't think we should pessimize the vast majority of requests in order to synchronize with Subsume requests properly, especially because most already do synchronize with Subsume requests properly. I think our approach for synchronizing between meta-level requests has been to acquire a latch on `RangeDescriptorKey`. That might be a workable solution here. Or we can do something like we do in `RecomputeStatsRequest`.

I think the more important change here will be the testing. Once we have a good way to express and assert that everything else should synchronize with `SubsumeRequests`, we can figure out how to enforce that.

2020-07-01 15:26 UTC, aayushshah15 reviewed
It turns out that the merge txn retries were only a part of the problem, and they were masking a real oversight: when the lease for the RHS gets transferred while it is subsumed, the new leaseholder will emit an MLAI of `1` for this range in its next closed timestamp update (I had incorrectly assumed that it wouldn't include the RHS in its MLAI map since all traffic to the range has been blocked). The follower replicas can activate this LAI when they receive this closed timestamp update, leading to the violation in question. PTAL at the fix in `replica_closedts.go`. Aside from this, the merge txn retries seem to have gone away after I bumped the `PushTxnsAge` to a much longer duration, I `stressrace`ed it locally for ~15m, but we'll see if the CI gods are happy. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MB61rI3EBA-D1dGhvxd:b-kmfgen)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1530 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAqw6Mx5qfzD5q1prr-:-MB4v__R4y3bBTD_AWYd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1530)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/CheckConsistency/ComputeChecksum/g` 
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1534 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlQ6Dq8nqkdN5lKUoa:-MB6Xa-w-SpQ9g3PnZUd:bjzvzuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1534)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls put more words here describing this assertion
</blockquote></details>

Done. I like having one big comment block that acts as the single source of truth, so I keep pointing these smaller comments to that. Let me know if you'd prefer otherwise.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAquvzp4pNRdNMgpwZu:-MB4vPtvB2InU0uxhUXt:b-bae0ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1535)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Unfortunately, I don't think this is testing the right thing. Or at least, it's not testing enough to disprove the absence of the race condition we're concerned with. I'm still not convinced we're in the clear here.

A `ComputeChecksum` request will `checkForPendingMergeRLocked` if the Subsume request has already completed and installed the `mergeComplete` channel by the time that it begins execution. However, that alone does not ensure that the `ComputeChecksum` request will perform this check _after the channel is installed_. You mentioned that
> the ComputeChecksum request does "acquire latches" even though it doesn't declare any keys

This is the problem here. If the `ComputeChecksum` is concurrent with the `Subsume`, we don't have any guarantee that the order of operations won't be:
1. ComputeChecksum acquires an empty set of latches
2. SubsumeRequest acquires its latches
3. ComputeChecksum `checkForPendingMergeRLocked` and finds nothing
4. SubsumeRequest installs `mergeComplete` channel with current LAI
5. `ComputeChecksum` evaluates and proposes with higher LAI, breaking our invariant

Latches are what we use to provide this kind of synchronization which enforces ordering between requests. So we should use them here to ensure that all requests serialize with `SubsumeRequests`. I think it would be fine to make `ComputeChecksum` acquire _some_ kind of small latch that ensures this property.

More generally, though, we need to ensure that this is true for all request types. I wonder how we can automate this verification. A unit test that loops over all registered `cmds` in `kvserver/batcheval` and ensures that they all acquire overlapping spans with a `SubsumeRequest` for the same range would be one approach. An issue I see with that is that we don't actually have access to all requests in `kvserver/batcheval` because some, like `ExportRequest`, are registered externally.

Maybe we could combine that with some kind of race-only (see `util.RaceEnabled`) assertion in the `Command.DeclareKeys` functions themselves? We could wrap each `Command.DeclareKeys` function with something like the following when declared to instrument each of them with such a check:
```
+++ b/pkg/kv/kvserver/batcheval/command.go
@@ -60,7 +60,7 @@ func RegisterReadWriteCommand(
        impl func(context.Context, storage.ReadWriter, CommandArgs, roachpb.Response) (result.Result, error),
 ) {
        register(method, Command{
-               DeclareKeys: declare,
+               DeclareKeys: maybeWrapDeclareKeysFunc(declare),
                EvalRW:      impl,
        })
 }
@@ -73,7 +73,7 @@ func RegisterReadOnlyCommand(
        impl func(context.Context, storage.Reader, CommandArgs, roachpb.Response) (result.Result, error),
 ) {
        register(method, Command{
-               DeclareKeys: declare,
+               DeclareKeys: maybeWrapDeclareKeysFunc(declare),
                EvalRO:      impl,
        })
 }
@@ -97,3 +97,34 @@ func LookupCommand(method roachpb.Method) (Command, bool) {
        cmd, ok := cmds[method]
        return cmd, ok
 }
+
+func assertSerializesWith(inner, other declareKeysFunc) declareKeysFunc {
+       return func(desc *roachpb.RangeDescriptor, h roachpb.Header, r roachpb.Request, latchSpans, lockSpans *spanset.SpanSet) {
+               inner(desc, h, r, latchSpans, lockSpans)
+
+               var otherLatchSpans, otherLockSpans spanset.SpanSet
+               other(desc, h, nil, otherLatchSpans, otherLockSpans)
+               if !latchSpans.Intersects(otherLatchSpans) { // TODO: implement this fn
+                       panic("...")
+               }
+       }
+}
+
+func assertSerializedWithSubsume(inner declareKeysFunc) declareKeysFunc {
+       return assertSerializesWith(
+               inner,
+               func(desc *roachpb.RangeDescriptor, h roachpb.Header, _ roachpb.Request, latchSpans, lockSpans *spanset.SpanSet) {
+                       r := &SubsumeRequest{RightDesc: desc}
+                       declareKeysSubsume(desc, header, r, latchSpans, lockSpans)
+               }
+       )
+}
+
+func maybeWrapDeclareKeysFunc(inner declareKeysFunc) declareKeysFunc {
+       if !util.RaceEnabled {
+               return inner
+       }
+       inner = assertSerializedWithSubsume(inner)
+       // ... could add other assertions in the future ...
+       return inner
+}
```

By the way, I bet you could get the assertion you added below (which expresses the invariant we want to guarantee surprisingly well) to fire if you removed the `mergeEndTxnReceived` channel and run this under stress. This `mergeEndTxnReceived` is actually serving as exactly the kind of synchronization that we want but don't currently have from latches.
</blockquote></details>

Done, I chose to declare a read-only access over the range descriptor key for now. Would you still like me to add the unit test you mentioned? It seems redundant now that we're asserting this on race builds.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1599 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlQJkXCmABWIrbFwDF:-MB4vOhg5czhhggnmbCR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1599)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you probably want more than a second here and below; test [...]

2020-07-02 19:58 UTC, aayushshah15 commented
@andreimatei helped me look into why these merge txns were getting retried. We noticed that if the target closed timestamp duration was less than the time it takes for the AdminMerge logic to do all its `CPut`s, they can have their write timestamps bumped due to an intervening closed timestamp update: 
```
1153.112ms      0.225ms                event:kv/kvserver/store_send.go:169 [n2,s2] executing [txn: 8e0cd0db], ConditionalPut [/Local/Range/Table/53/1/2/RangeDescriptor,/Min)
  1153.686ms      0.574ms                event:kv/kvserver/replica_send.go:92 [n2,s2,r45/2:/{Table/53/1/2-Max}] read-write path
  1153.882ms      0.196ms                event:kv/kvserver/replica_send.go:668 [n2,s2,r45/2:/{Table/53/1/2-Max}] read has no clock uncertainty
  1154.177ms      0.296ms                event:kv/kvserver/concurrency/concurrency_manager.go:117 [n2,s2,r45/2:/{Table/53/1/2-Max}] sequencing request
  1154.307ms      0.130ms                event:kv/kvserver/concurrency/concurrency_manager.go:153 [n2,s2,r45/2:/{Table/53/1/2-Max}] acquiring latches
  1154.882ms      0.575ms                event:kv/kvserver/concurrency/concurrency_manager.go:165 [n2,s2,r45/2:/{Table/53/1/2-Max}] scanning lock table for conflicting locks
  1155.217ms      0.335ms                event:kv/kvserver/replica_tscache.go:313 [n2,s2,r45/2:/{Table/53/1/2-Max}] bumped write timestamp due to closed ts: 1593621353.387404000,1
  1155.473ms      0.257ms                event:kv/kvserver/replica_write.go:109 [n2,s2,r45/2:/{Table/53/1/2-Max}] applied timestamp cache
  1155.660ms      0.186ms                event:kv/kvserver/replica_write.go:320 [n2,s2,r45/2:/{Table/53/1/2-Max}] executing read-write batch
  1163.268ms      7.608ms                event:kv/kvserver/replica_raft.go:74 [n2,s2,r45/2:/{Table/53/1/2-Max}] evaluated request
  1276.978ms    113.710ms                    === operation:raft application node:2 range:45/2:/{Table/53/1/2-Max} sb:1 store:2 txnID:8e0cd0db-b954-42d1-b478-27b288c9f62c
  1293.799ms     16.821ms                    event:kv/kvserver/replica_application_state_machine.go:441 [n2,s2,r45/2:/{Table/53/1/2-Max}] applying command

```
Since we prevent merge txn refreshes, this causes the entire merge txn to abort & retry. This explains why the tests fail on a loaded CI machine (but not on my not-so-loaded macbook). There are two apparent solutions that don't really work:
1. Make the tests resilient to merge txn retries: this doesn't entirely solve the problem since these things can sometimes indefinitely keep retrying. 
2. Use a really long closed timestamp target duration: This should work in theory but the fact that the tests, at various points, need to poll (or wait) for appropriate closed timestamp updates, makes the tests really slow.

What I've done here is use a long closed timestamp duration until the merge txn is suspended at the commit trigger - at this point all the txn's intents have been laid down. Before the test starts polling for closed timestamps, we change the duration back to `testingTargetDuration` (300ms). This lets the rest of the test be reasonably fast.

2020-07-02 19:59 UTC, aayushshah15 commented
CI seems to be happy about this (the only failure is a flakey acceptance test `TestDockerCLI`)

2020-07-06 22:41 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAquvzp4pNRdNMgpwZu:-MBa791f28sURyKch-EW:b-q770rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1535)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done, I chose to declare a read-only access over the range descriptor key for now. Would you still like me to add the unit test you mentioned? It seems redundant now that we're asserting this on race builds.
</blockquote></details>

So Nathan did you also want this `TestStoreRangeMergeCheckConsistencyAfterSubsumption` to reorder the operations to match your race?
Or rather, I think we should just get rid of it in favor of the simpler test of the latches that y'all are discussing.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBa0RUgD345vOW6SfF0:-MBa0RUgD345vOW6SfF1:b-vgw076) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L51)):*
> ```Go
> )
> 
> var defaultClusterArgs = base.TestClusterArgs{
> ```

I'd name it `aggressiveResolvedTimestampClusterArgs`.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBa0avQ-haf9CBBTTmB:-MBa0avQ-haf9CBBTTmC:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L70)):*
> ```Go
> 
> 	ctx := context.Background()
> 	tc, db0, desc, repls := setupClusterForClosedTimestampTesting(ctx, t, testingTargetDuration, testingCloseFraction, defaultClusterArgs)
> ```

nit: long line
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 478 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaH9WW0f1g-BaxXbC-:-MBaH9WW0f1g-BaxXbC0:b-8teyff) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L478)):*
> ```Go
> 				Knobs: base.TestingKnobs{
> 					Store: &kvserver.StoreTestingKnobs{
> 						RangeFeedPushTxnsInterval: 5 * time.Second,
> ```

put some comments on these 2 guys pls
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 491 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCbdW2DpIPM4KSSPx:-MBaCbdW2DpIPM4KSSPy:bpvprsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L491)):*
> ```Go
> 		// causes the entire merge txn to retry.
> 		tc, db, leftDesc, rightDesc, err := initClusterWithSplitRanges(ctx, t, 3*time.Second, testingCloseFraction, clusterArgs)
> 		if err != nil {
> ```

nit: `require.NoError()`.

But I'm confused - why does `initClusterWithSplitRanges` both take a `t` and also return an error? 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 529 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaHFy179i-WiROE2Az:-MBaHFy179i-WiROE2B-:b-29gkan) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L529)):*
> ```Go
> 			return nil
> 		})
> 		testutils.SucceedsSoon(t, func() error {
> ```

I don't think `SucceedsSoon` does what you think it does - it doesn't enforce a timeout for reading from a channel.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 535 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaC8JU7cC9UcAL6vdJ:-MBaC8JU7cC9UcAL6vdK:b-1obh83) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L535)):*
> ```Go
> 		baReadRHSAfterSubsume := makeReadBatchRequestForDesc(rightDesc, freezeStartTimestamp.Next())
> 		rightReplFollowers := getFollowerReplicas(ctx, t, tc, rightDesc, leaseholder)
> 		testutils.SucceedsSoon(t, func() error {
> ```

what's going on here - you're calling `SucceedsSoon()` but never return an error from the closure. What's the point of the `SucceedsSoon`?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 537 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCIRc2_wamxBJhYrk:-MBaCIRc2_wamxBJhYrl:b-qxxsf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L537)):*
> ```Go
> 		testutils.SucceedsSoon(t, func() error {
> 			observedNLEs, err := countNotLeaseHolderErrors(baReadRHSAfterSubsume, rightReplFollowers)
> 			if err != nil {
> ```

`require.NoError()`
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 540 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCG0xBtgh_osJ4cKd:-MBaCG0xBtgh_osJ4cKe:b70mp00) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L540)):*
> ```Go
> 				t.Fatal(err)
> 			}
> 			if observedNLEs != expectedNLEs {
> ```

`require.Equal()`

also nit s/%v/%d
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaBht62h7o6O4rqHeN:-MBaBht62h7o6O4rqHeO:b-6eki3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
> ```Go
> 		finishMergeTxn := make(chan struct{})
> 		var leaseAcquisitionTrap atomic.Value
> 		//clusterArgs := defaultClusterArgs
> ```

leftover
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 702 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCSj44k8VXTiTQLZH:-MBaCSj44k8VXTiTQLZI:bl1l98y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L702)):*
> ```Go
> 		// incoming requests. However, its store will publish an initial MLAI update
> 		// for the RHS range that it just acquired a lease for.
> 		testutils.SucceedsSoon(t, func() error {
> ```

same as above - what's the point of this `SucceedsSoon`?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 709 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCNIM90rwMW9KZ96I:-MBaCNIM90rwMW9KZ96J:bl1l98y) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L709)):*
> ```Go
> 		rightReplFollowers := getFollowerReplicas(ctx, t, tc, rightDesc, rightLeaseholder)
> 		log.Infof(ctx, "sending read requests from followers at a timestamp after the start of the new lease")
> 		testutils.SucceedsSoon(t, func() error {
> ```

same as above - what's the point of this `SucceedsSoon`?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 718 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaDkmg6INIPnQ1HYF6:-MBaDkmg6INIPnQ1HYF7:b-mxq2v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L718)):*
> ```Go
> func suspendMergeTrigger(
> 	suspendMergeTrigger chan<- hlc.Timestamp, finishMergeTxn <-chan struct{},
> ) func(_ context.Context, ba roachpb.BatchRequest) *roachpb.Error {
> ```

What's going on here is unusual. I was gonna ask why does this return a function until I saw the `attempts`. If we want to keep it, turn the thing into a struct with a method, so that the state is more obvious.
But I'd also like to see some comments on this guy about what the semantics are - and maybe we can simplify it. What's up with the errors on retries? Is that still needed?

Also say something  [...]

2020-07-07 01:36 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 51 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBa0RUgD345vOW6SfF0:-MBaN9BY0ZaeMDQw8PcH:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L51)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd name it `aggressiveResolvedTimestampClusterArgs`.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 70 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBa0avQ-haf9CBBTTmB:-MBaXT-77Q04E6Q6GnXq:b-s3qozi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

Fixed here and elsewhere in the file.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 478 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaH9WW0f1g-BaxXbC-:-MBaYLLF1XjZYRbsmNV5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L478)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put some comments on these 2 guys pls
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 491 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCbdW2DpIPM4KSSPx:-MBaNDva9_jwwuj9nmJ-:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L491)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: `require.NoError()`.

But I'm confused - why does `initClusterWithSplitRanges` both take a `t` and also return an error? 
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 529 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaHFy179i-WiROE2Az:-MBaNGDx6mmu9TxMvWja:bepxrqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L529)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think `SucceedsSoon` does what you think it does - it doesn't enforce a timeout for reading from a channel.
</blockquote></details>

I was under the impression that `SucceedsSoon` will fail unless the supplied function successfully returns with a nil result within 45s. Didn't realize that it doesn't run the supplied function under a separate goroutine. Fixed now. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 535 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaC8JU7cC9UcAL6vdJ:-MBaNfkU7X9o5N59Mq5U:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L535)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's going on here - you're calling `SucceedsSoon()` but never return an error from the closure. What's the point of the `SucceedsSoon`?
</blockquote></details>

Fixed
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 537 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCIRc2_wamxBJhYrk:-MBaVqqhAZQNxCJZhrmo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L537)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`require.NoError()`
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 540 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCG0xBtgh_osJ4cKd:-MBaVtSN5rR-_2SIlv_T:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L540)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`require.Equal()`

also nit s/%v/%d
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaBht62h7o6O4rqHeN:-MBaW0owC0hoBv81EBTX:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

leftover
</blockquote></details>

Removed
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 702 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCSj44k8VXTiTQLZH:-MBaW3sb9gawl6-lP_5H:b-lx4fj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L702)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

same as above - what's the point of this `SucceedsSoon`?
</blockquote></details>

Fixed. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 709 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaCNIM90rwMW9KZ96I:-MBaWBtN7LGpTJAucnib:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L709)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

same as above - what's the point of this `SucceedsSoon`?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 718 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaDkmg6INIPnQ1HYF6:-MBaeCoVASHUDzFLUTxk:b-ueyqzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L718)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What's going on here is unusual. I was gonna ask why does this return a function until I saw the `attempts`. If we want to keep it, turn the thing into a struct with a method, so that the state is more obvious.
But I'd also like to see some comments on this guy about what the semantics are - and maybe we can simplify it. What's up with the errors on retries? Is that still needed?

Also say something about how this is used as a `RequestFilter`.
</blockquote></details>

 I'd like to keep it because otherwise, if the merge txn retries, these tests fail in very non-obvious ways. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 725 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaGAUF8Yut96KHs714:-MBaWJKoEU8HrO2FMbIz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L725)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: lowercase for error messages
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 731 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBaFSDO6gq_xOHIRymq:-MBaWK4F24AJseyKoVMR:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/closed_timestamp_test.go#L731)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: "now" is generally implicit :P
</blockquote></deta [...]

2020-07-08 17:45 UTC, andreimatei reviewed
I've got a probably dumb question: could/should we allow a subsume replica to process an `AdminTransferLeaseRequest`? The argument being that a new lease doesn't bump the LAI (of the old one), and that lease transfers obviously can happen anyway while the range is subsumed. Allowing a cooperative transfer would simplify the testing for... lease transfers.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MBjUvxV6Gs1G-ABWvHr:bknhtbc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @andreimatei)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 477 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjSyVd30R7rVmKLhVo:-MBjSyVd30R7rVmKLhVp:b-2ep2u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L477)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	t.Run("without lease transfer", func(t *testing.T) {
> ```

I think these tests are now quite good, but I'd like to explore what it'd take to merge the logic for the two subtests into a single table-driven test. Did you try?
What exactly is the difference between them? Is it just that the 2nd blocks the heartbeats and then does some dummy requests to cause a lease transfer? That can be modeled as an optional callback specified by a `testCase` struct to be run after the RHS is subsumed.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 523 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjR-xi7bseLrBp0gyL:-MBjR-xi7bseLrBp0gyM:b-8gt0qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L523)):*
> ```Go
> 			}
> 		}()
> 		// We now have the RHS in its subsumed state.
> ```

This comment should technically be on the next line, right? Change it to "wait until the RHS enters the subsumed state".
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjToOOE0vpzpOrLtfb:-MBjToOOE0vpzpOrLtfc:ba5mrr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
> ```Go
> 
> 	// This subtest ensures that follower reads are inactive on timestamps after
> 	// the subsumption time even in the presence of lease transfers on the
> ```

say something about the mechanism being tested here - that new leaseholders are supposed to notice the subsumed state when they apply the lease.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 646 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjT__g4-SHLiLpNHjs:-MBjT__g4-SHLiLpNHjt:b-arygwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L646)):*
> ```Go
> 		store := getTargetStoreOrFatal(t, tc, rightLeaseholder)
> 
> 		// We pause the node liveness heartbeats until a lease transfer occurs.
> ```

Say that we can't do a cooperative lease transfer (`AdminTransferLease()`) because the current leaseholder is subsumed, and so we'll wait for the expiration of the current lease.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 665 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjUA-S4t4yKXorJZYq:-MBjUA-S4t4yKXorJZYr:bpyqd1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L665)):*
> ```Go
> 		restartHeartbeats := store.NodeLiveness().DisableAllHeartbeatsForTest()
> 		log.Infof(ctx, "paused RHS rightLeaseholder's liveness heartbeats")
> 		time.Sleep(store.NodeLiveness().GetLivenessThreshold())
> ```

what is this sleep period going to be here? I don't see the test mucking with the liveness duration settings; should we make that really low?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 768 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjQdrOClFWTFjeIjOX:-MBjQdrPEx-uLylWNcBz:b3z638y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L768)):*
> ```Go
> }
> 
> func beginMergeTxn(tc serverutils.TestClusterInterface, leftDesc roachpb.RangeDescriptor) error {
> ```

what does the "begin" refer to? This function seems to do a merge.


<!-- Sent from Reviewable.io -->

2020-07-09 20:22 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 477 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjSyVd30R7rVmKLhVo:-MBpDjCyCVqP0gWrsevE:b-52jymv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L477)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think these tests are now quite good, but I'd like to explore what it'd take to merge the logic for the two subtests into a single table-driven test. Did you try?
What exactly is the difference between them? Is it just that the 2nd blocks the heartbeats and then does some dummy requests to cause a lease transfer? That can be modeled as an optional callback specified by a `testCase` struct to be run after the RHS is subsumed.
</blockquote></details>

Done, do you like the new structure?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 523 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjR-xi7bseLrBp0gyL:-MBltUfl4RHEh5kSfguZ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L523)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment should technically be on the next line, right? Change it to "wait until the RHS enters the subsumed state".
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjToOOE0vpzpOrLtfb:-MBltWbQ26sJO0I4rS5q:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say something about the mechanism being tested here - that new leaseholders are supposed to notice the subsumed state when they apply the lease.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 646 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjT__g4-SHLiLpNHjs:-MBoOOmjDvHYLxscbpHs:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L646)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Say that we can't do a cooperative lease transfer (`AdminTransferLease()`) because the current leaseholder is subsumed, and so we'll wait for the expiration of the current lease.
</blockquote></details>

Done
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 665 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjUA-S4t4yKXorJZYq:-MBoOUUm9NgfLb4vOoYr:b-zgc3lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L665)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what is this sleep period going to be here? I don't see the test mucking with the liveness duration settings; should we make that really low?
</blockquote></details>

See comment above `RaftElectionTimeoutTicks` on line 572. 
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 768 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjQdrOClFWTFjeIjOX:-MBoOh5C54Bfrwh_RaHM:b499q7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L768)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what does the "begin" refer to? This function seems to do a merge.
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2020-07-09 20:23 UTC, andreimatei reviewed
I caught up with Nathan on a huddle and we discussed a couple things around these parts.

In particular about these assertions that the latches for the different requests overlap. I think maybe the suggestion to have these latching assertions at runtime under race is not a big hit - because of complications with the RangeKeyMismatchErrors and possibly with the follower reads that you brought up, and just that it's kinda ugly cause it feels like it should be done with static checks. Let's do something more pedestrian, with a simple `kvserver` test that iterates through all the registered request types and creates each one by hand and verifies its intersection with a subsume. There are two request types that are registered in ccl packages, but screw them. If we want, there are ways to test them too but it's prolly not worth it.

A thing that we've noticed when looking at some code was in [checkExecutionCanProceed](https://github.com/cockroachdb/cockroach/blob/46adc70abba643b61ab11ff4cd48fff66779a5e6/pkg/kv/kvserver/replica.go#L1107) - this guy checks whether the `LeaseStatus` is nil. That argument is never nil. What that function really wants to check, Nathan was saying, is whether the request falls under the current lease or not. For example, a follower read should be exempt from the check. So, I think we should be checking whether that `status` is empty, or something like that. Maybe you can address that in a different PR - and I think maybe that would help with getting follower reads working on the leaseholder?

I mentioned to him my suggestion of allowing lease transfers to work while the range is subsumed and it seemed like a good idea. I think `AdminLeaseTransfer` would already be allowed by `checkExecutionCanProceed()` to go through, but the ensuing `LeaseTransfer` request I think would be blocked. But maybe we can whitelist it. I think that would make your test nicer, but don't worry about it if you're not interested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MBp9p1mEKm1t2F7H8iP:b-1itlju)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)



<!-- Sent from Reviewable.io -->

2020-07-13 11:43 UTC, aayushshah15 reviewed
I've added a TODO for allowing `TransferLease` requests through. From a cursory glance, it seems like the only new behavior it would allow is rebalancing related lease transfers while a range is subsumed. 

Added the unit test that iterates through all registered requests, as we discussed. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MBpNMc-Eny8b7umSgr7:bkxb2p9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAquvzp4pNRdNMgpwZu:-MC6ka-E7YE3ERhi_Fxx:byk4jvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/client_merge_test.go#L1535)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

So Nathan did you also want this `TestStoreRangeMergeCheckConsistencyAfterSubsumption` to reorder the operations to match your race?
Or rather, I think we should just get rid of it in favor of the simpler test of the latches that y'all are discussing.
</blockquote></details>

Done, see the review discussion comment above.
___
*[pkg/kv/kvserver/replica_test.go, line 926 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBa9Wc1DVrPbC_EQpdF:-MC6kES00reBpJ1szods:bdv89gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f23b67f71c6a67cbb60bb9d63160756589d0886/pkg/kv/kvserver/replica_test.go#L926)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Hmmm sending a request to a range with keys that don't match that range's (current) keys is normal - comes from stale client-side descriptor caches.
These requests need to get a `RangeKeyMismatchError`, not some other assertion failure or crash - even under race-test. Can we inhibit the new assertion for these mismatched requests? See `checkSpanInRangeRLocked()`. 
</blockquote></details>

Not applicable anymore.


<!-- Sent from Reviewable.io -->

2020-07-13 14:13 UTC, andreimatei approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MC7WZEq7Rzvavgqz-DC:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 477 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBjSyVd30R7rVmKLhVo:-MC7VJi0AtZJcsFb4wJq:b7rbuia) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ffa0ccffe36c676e7d6847dccfb5e7ef926154/pkg/kv/kvserver/closed_timestamp_test.go#L477)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done, do you like the new structure?
</blockquote></details>

yup, thanksTODO
___
*[pkg/kv/kvserver/batcheval/cmd_subsume_test.go, line 81 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MC7Vj_b0Dznrf-iWFPE:-MC7Vj_cDRviKylMi6GP:b-nn8q04) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba83db31146441944678a8c729ce046d1e90db31/pkg/kv/kvserver/batcheval/cmd_subsume_test.go#L81)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	ctx := context.Background()
> 	for method, command := range cmds {
> ```

nit: make every iteration of this loop a subtest. I'd also inline `ensureSerializesWithSubsume()` - it's annoying when a test is just a shell for no good reason. If you inline it, I think you can move everything above `declareKeysSubsume()` above the loop.


<!-- Sent from Reviewable.io -->

2020-07-13 14:26 UTC, aayushshah15 reviewed
Done. I'll wait a bit before merging in case Nathan wants to take another pass.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MC7ZQll18X7YUdkxoqd:bwf93rk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/cmd_subsume_test.go, line 81 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MC7Vj_b0Dznrf-iWFPE:-MC7ZNcY5SnxK-GxWoeJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba83db31146441944678a8c729ce046d1e90db31/pkg/kv/kvserver/batcheval/cmd_subsume_test.go#L81)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: make every iteration of this loop a subtest. I'd also inline `ensureSerializesWithSubsume()` - it's annoying when a test is just a shell for no good reason. If you inline it, I think you can move everything above `declareKeysSubsume()` above the loop.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-13 22:02 UTC, nvanbenschoten commented
Sorry for the delay on this. I'll take one more pass over this tomorrow morning, if that works for you. Thanks for all the work on this @aayushshah15!

2020-07-14 21:11 UTC, nvanbenschoten commented
Oh man, coming back to this I see that I had a whole slate of review comments from last week (many of which are now stale) that never got published. I blame this one on reviewable. Luckily, Andrei's recent reviews overlapped with some of them.

2020-07-14 21:42 UTC, nvb reviewed
> Reviewed 11 of 14 files at r6, 1 of 4 files at r8, 8 of 12 files at r9, 3 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @andreimatei)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAFzZM9YM1MeFt7WPU:-MBAFzZM9YM1MeFt7WPV:btafkcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
> ```Go
> 							}
> 							leaseAcquisitionCallback := val.(func(storeID roachpb.StoreID, rangeID roachpb.RangeID))
> 							if leaseAcquisitionCallback != nil {
> ```

Do we need this nil check?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 597 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGDLO6ackNfkixVD0:-MBAGDLO6ackNfkixVD1:bclwg9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L597)):*
> ```Go
> 		leaseAcquisitionTrap.Store(func(storeID roachpb.StoreID, rangeID roachpb.RangeID) {
> 			if rangeID == rightDesc.RangeID {
> 				once.Do(func() {
> ```

Can you avoid the sync.Once by instead `leaseAcquisitionTrap.Store(nil)` here?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 606 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGS-H-HBhhUZf9E9Y:-MBAGS-H-HBhhUZf9E9Z:b-5gfl9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L606)):*
> ```Go
> 		restartHeartbeats := store.NodeLiveness().DisableAllHeartbeatsForTest()
> 		log.Infof(ctx, "paused RHS leaseholder's liveness heartbeats")
> 		time.Sleep(store.NodeLiveness().GetLivenessThreshold())
> ```

Can we use a manual clock to avoid actually waiting this out?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 815 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAHjAx8zf8P9xFR0mQ:-MBAHjAx8zf8P9xFR0mR:b-xe04y0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L815)):*
> ```Go
> ) []*kvserver.Replica {
> 	repls := replsForRange(ctx, t, tc, rangeDesc)
> 	followers := make([]*kvserver.Replica, 0)
> ```

Not important here, but worth calling out for future reference:

There are a few different ways to build up a slice, each with their own performance characteristics. In order from slowest to fastest:
1. append to initially empty slice (what you have here). This requires intermediate resizing, which is expensive. The idiomatic way to do this is to declare the slice as `var followers []*kvserver.Replica` so that it doesn't even incur an allocation if left with a length of 0. Only use this approach is you don't know the final length (like here).
2. appending to initially empty slice with desired capacity (e.g. `followers := make([]*kvserver.Replica, 0, len(repls)`). Avoids resizing but still has to perform a bounds check and length update on each append. Generally only used if iterating over a map.
3. insert into properly sized slice (e.g. `followers := make([]*kvserver.Replica, len(repls)`). Fastest approach. No bounds checks, no updating length in slice header. Use whenever possible.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 659 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEA-CZ15Dnaqp0Wc3M:-MCEA-CZ15Dnaqp0Wc3N:b-e29qkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/closed_timestamp_test.go#L659)):*
> ```Go
> 	leaseAcquisitionTrap *atomic.Value,
> ) (newLeaseholder roachpb.ReplicationTarget, ts hlc.Timestamp, err error) {
> 	store := getTargetStoreOrFatal(t, tc, rightLeaseholder)
> ```

s/store/oldLeaseholderStore/
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 714 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEAu960O6V6kAzqTFO:-MCEAu960O6V6kAzqTFP:bx69jxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/closed_timestamp_test.go#L714)):*
> ```Go
> 	case <-time.After(30 * time.Second):
> 		err = errors.New("failed to receive lease acquisition request")
> 		return
> ```

`return ...`

The Go community is generally :thumbsdown: on naked returns – a.k.a the hundred dollar mistake.
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MBAK-2f4ESb43sWgjts:b-vngy77) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
> ```Go
> 		ctx := r.AnnotateCtx(context.Background())
> 		_, untrack := r.store.cfg.ClosedTimestamp.Tracker.Track(ctx)
> 		if r.mergeInProgress() {
> ```

Is there any benefit to publishing this MAIL instead of returning early if we notice that a merge is in progress? I think maybe the answer is that we need to do this on new leaseholders.

Do you mind writing the answer to this in the comment below?
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK7nf32HV7E2lp3tD:-MBAK7nf32HV7E2lp3tE:bgsfmz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
> ```Go
> 		ctx := r.AnnotateCtx(context.Background())
> 		_, untrack := r.store.cfg.ClosedTimestamp.Tracker.Track(ctx)
> 		if r.mergeInProgress() {
> ```

Can we assign `r.mergeInProgressRLocked()` to a bool while in the critical section above?
___
*[pkg/kv/kvserver/replica_raft.go, line 337 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MAlMLgb5w26WBn1lmmU:-MBAJpm_3J_AiYswnVvK:b-sp0bym) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f0b494f9e3bf25e13b1a28c01cbf8d1160410af/pkg/kv/kvserver/replica_raft.go#L337)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Did you mean, move it up next to the `getMergeComplete` methods? Let me know if I misunderstood you.
</blockquote></details>

Yep, looks good.
___
*[pkg/kv/kvserver/replica_raft.go, line 335 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAJoTV4W-Ekmrmk_hW:-MBAJoTV4W-Ekmrmk_hX:b-meni90) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_raft.go#L335)):*
> ```Go
> 		return 0, roachpb.NewError(err)
> 	}
> 	if maxLeaseIndex != 0 {
> ```

I'm realizing that this would be better located in `executeWriteBatch`, where we already have a check on `maxLeaseIndex != 0` right next to a call to `untrack`.
___
*[pkg/kv/kvserver/replica_raft.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEFmgE6VsOoyt1hyUO:-MCEFmgE6VsOoyt1hyUP:b-rwxr84) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/replica_raft.go#L336)):*
> ```Go
> 	}
> 	if maxLeaseIndex != 0 {
> 		if r.mergeInProgress() {
> ```

What about rollbacks of the merge transaction and its intents? Aren't those supposed to be allowed? I'm surprised there aren't any tests hitting that case.
___
*[pkg/kv/kvserver/replica_read.go, line 127 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEBrWj8p3m4V2taFPo:-MCEBrWj8p3m4V2taFPp:b-t3wz3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/replica_read.go#L127)):*
> ```Go
> 
> 	releaseSubsumeProp := func(_ bool) {}
> 	if ba.IsSingleSubsumeRequest() {
> ```

Why did we decide to add this logic here, which is a general routing function, instead of in the `Subsume` request evaluation itself? Because we' [...]

2020-07-14 23:56 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 606 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGS-H-HBhhUZf9E9Y:-MCEk0iICvNNruFJFw_t:b-7iyt8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L606)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use a manual clock to avoid actually waiting this out?
</blockquote></details>

I don't think so... You can't use a `ManualClock` with a `TestCluster` (can you!?!).

Btw, wow long is this sleep? If it's over a few secs, let's skip the test on `-short`.


<!-- Sent from Reviewable.io -->

2020-07-15 20:31 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 555 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAFzZM9YM1MeFt7WPU:-MCIiV5M373Weh2YZ_V3:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L555)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this nil check?
</blockquote></details>

removed.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 597 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGDLO6ackNfkixVD0:-MCIinE30zi6orFMyYU_:bpehju2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L597)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can you avoid the sync.Once by instead `leaseAcquisitionTrap.Store(nil)` here?
</blockquote></details>

Storing `nil` into an atomic.Value panics, TIL. I'm curious: why is using `sync.Once` undesirable?
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 606 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGS-H-HBhhUZf9E9Y:-MCJ6uUcBxc9KFcjzxVn:bprukh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L606)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think so... You can't use a `ManualClock` with a `TestCluster` (can you!?!).

Btw, wow long is this sleep? If it's over a few secs, let's skip the test on `-short`.
</blockquote></details>

Its ~3.6 seconds based on the `RaftElectionTimeoutTicks` used in the test.
+1 to andrei's question as I don't see any uses of TestCluster with a manual clock.
I'm also not sure how that would behave with the closed timestamp subsystem. For example if it meant that we need to manually forward the clock for each closed timestamp update then the test will end up just as complicated & will perhaps take a bunch more time to rewrite.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 815 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAHjAx8zf8P9xFR0mQ:-MCIipMu2LuH5NKDEeBe:b-8hv4eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L815)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not important here, but worth calling out for future reference:

There are a few different ways to build up a slice, each with their own performance characteristics. In order from slowest to fastest:
1. append to initially empty slice (what you have here). This requires intermediate resizing, which is expensive. The idiomatic way to do this is to declare the slice as `var followers []*kvserver.Replica` so that it doesn't even incur an allocation if left with a length of 0. Only use this approach is you don't know the final length (like here).
2. appending to initially empty slice with desired capacity (e.g. `followers := make([]*kvserver.Replica, 0, len(repls)`). Avoids resizing but still has to perform a bounds check and length update on each append. Generally only used if iterating over a map.
3. insert into properly sized slice (e.g. `followers := make([]*kvserver.Replica, len(repls)`). Fastest approach. No bounds checks, no updating length in slice header. Use whenever possible.
</blockquote></details>

Ack, we do know the final length here.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 659 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEA-CZ15Dnaqp0Wc3M:-MCIjGD-BZ8Wlz_atGSJ:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/closed_timestamp_test.go#L659)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/store/oldLeaseholderStore/
</blockquote></details>

done.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 714 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEAu960O6V6kAzqTFO:-MCIsYbe7eNQmffPzzIG:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/closed_timestamp_test.go#L714)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`return ...`

The Go community is generally :thumbsdown: on naked returns – a.k.a the hundred dollar mistake.
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK7nf32HV7E2lp3tD:-MCIss4s1rRl0aJLfLhK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we assign `r.mergeInProgressRLocked()` to a bool while in the critical section above?
</blockquote></details>

Done
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MCJ5lG83dItI97-zOkb:b-toqi2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there any benefit to publishing this MAIL instead of returning early if we notice that a merge is in progress? I think maybe the answer is that we need to do this on new leaseholders.

Do you mind writing the answer to this in the comment below?
</blockquote></details>

I'm actually not sure why we _need_ to do this on new leaseholders but I added a comment explaining why its undesirable based on my current understanding. 
___
*[pkg/kv/kvserver/replica_raft.go, line 335 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAJoTV4W-Ekmrmk_hW:-MCIxoTxAIvrpD8L8t5R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_raft.go#L335)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm realizing that this would be better located in `executeWriteBatch`, where we already have a check on `maxLeaseIndex != 0` right next to a call to `untrack`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_raft.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEFmgE6VsOoyt1hyUO:-MCIqZxu16GGie-UZic5:b-hticj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/replica_raft.go#L336)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What about rollbacks of the merge transaction and its intents? Aren't those supposed to be allowed? I'm surprised there aren't any tests hitting that case.
</blockquote></details>

Discussed offline: Before the merge-in-progress marker (`mergeComplete`) is removed, all the requests will block.  By the time a new request for a key on RHS is allowed to proceed, the merge-in-progress will have already been removed. At that point, it would be ok for this new request to resolve the aborted merge txn's intent on the RHS range descriptor.
___
*[pkg/kv/kvserver/replica_read.go, line 159 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEDUNR3yYhw9YZ3Wav:-MCJ0WEGDg-D18l-h40N: [...]

2020-07-16 19:07 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_read.go, line 127 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEBrWj8p3m4V2taFPo:-MCO0BOV3BPbjPK64jB4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/replica_read.go#L127)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why did we decide to add this logic here, which is a general routing function, instead of in the `Subsume` request evaluation itself? Because we'd need to expose the tracker on the `EvalContext`? If so, I think we should bite the bullet and expose that to batcheval. The more I think about it, the more I'm :thumbsdown: on this complex and extremely specific logic being in such a top-level function that has almost nothing to do with replica subsumption.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-17 20:53 UTC, nvb reviewed
> Reviewed 13 of 13 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @andreimatei)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 597 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGDLO6ackNfkixVD0:-MCTQz8O3xcbF0QOrr_5:b2sd5pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L597)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Storing `nil` into an atomic.Value panics, TIL. I'm curious: why is using `sync.Once` undesirable?
</blockquote></details>

No real reason. I guess this is fine.
___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 606 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGS-H-HBhhUZf9E9Y:-MCTRxh55TZ17LQCJjww:bylnhf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L606)):*
> RaftElectionTimeoutTicks

Can we configure this to be lower for this test? We do that in other tests to get them to run faster.
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MCTSRbw9H_OQ5Gs4wwP:bdq8pho) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I'm actually not sure why we _need_ to do this on new leaseholders but I added a comment explaining why its undesirable based on my current understanding. 
</blockquote></details>

What is the effect of it getting interpreted as the range being quiesced?
___
*[pkg/kv/kvserver/replica_raft.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCEFmgE6VsOoyt1hyUO:-MCTSaToCmHaDfL6i9rL:bbzhvbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/replica_raft.go#L336)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Discussed offline: Before the merge-in-progress marker (`mergeComplete`) is removed, all the requests will block.  By the time a new request for a key on RHS is allowed to proceed, the merge-in-progress will have already been removed. At that point, it would be ok for this new request to resolve the aborted merge txn's intent on the RHS range descriptor.
</blockquote></details>

That's a nice resolution. Glad you tracked that down.
___
*[pkg/kv/kvserver/replica_write.go, line 156 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSyp80dTQZKnTPVA_:-MCTSyp80dTQZKnTPVAa:bsuw84b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L156)):*
> ```
> executeReadOnlyBatchWithServerSideRefreshes
> ```

Mind finding all comments that reference this and fixing them now that the logic is not there?
___
*[pkg/kv/kvserver/replica_write.go, line 160 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSn_KCe9hx5lavoPa:-MCTSn_KCe9hx5lavoPb:b-af3h4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L160)):*
> ```Go
> 			log.Fatalf(ctx, "lease applied index bumped while the range was subsumed")
> 		}
> 		// In case no proposal was made or a lease was proposed, we don't need to
> ```

nit: why move this here? Isn't this the branch dealing with the case where a proposal _was_ made that was not  a lease?
___
*[pkg/kv/kvserver/batcheval/cmd_compute_checksum.go, line 39 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCECgIACQRRbU7ntwcV:-MCTToQi0UPl6WsRKO-N:b-b9xqgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/batcheval/cmd_compute_checksum.go#L39)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

If this invariant is violated, essentially, it'd be possible for actionable closed timestamps to regress (for a given key span). This means that two txns could potentially read different values for a given key for the same given timestamp. This would allow for an execution history that cannot be achieved if the two txns were serially executed one after another, right?
</blockquote></details>

Yes, that's all true, but that's still an effect of what's going wrong here, not the actual bug we're fixing. We wouldn't describe a fix to Pebble that avoids losing a write as a fix for a serializable violation, right? It wouldn't be incorrect, per se, but it just doesn't add any real information to the conversation without being properly qualified.

I would lean towards describing exactly what could happen in this case, "a closed timestamp violation due to writes on the post-merged range that violate a closed timestamp spuriously reported by the pre-merged range." If you want to say that this could in-turn allow for a serializability violation, that would be fine.

---

In fact, coming back to this comment after having moved the previous two paragraphs from a comment on another use of "serializability violation" in `replica_write.go` before remembering that we already had this discussion going, this one, in particular, seems even worse. The fix here is necessary to prevent a bug in the fix for the bug with closed timestamp. So we're an extra step away! So saying that "ComputeChecksum needs to be serialized with Subsume requests to prevent a serializability violation" is a little absurd sounding and makes the comment less useful then it could be.
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 138 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTWUt7-zMfSPpNIv5I:-MCTWUt846J7Dy42_D8D:bq8zfkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/batcheval/cmd_subsume.go#L138)):*
> ```Go
> 	reply.FreezeStart = cArgs.EvalCtx.Clock().Now()
> 
> 	// We prevent followers of the RHS from being able to serve follower reads on
> ```

Does this need to happen before `reply.FreezeStart = cArgs.EvalCtx.Clock().Now()`? We need to ensure that `FreezeStart` is greater than or equal to any closed timestamp broadcasted for `cArgs.EvalCtx.GetLeaseAppliedIndex()`, right?
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 153 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTXIhV0SpfOcReIgWT:-MCTXIhV0SpfOcReIgWU:b-yfd4m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3f81289799f480fc68dc9c8ae8aeea8048ac8d/pkg/kv/kvserver/batcheval/cmd_subsume.go#L153)):*
> ```Go
> 	//
> 	// Note that we are essentially lying to the closed timestamp tracker here in
> 	// order to achieve the effect of unactionable closed timestamp update until
> ```

"an unactionable"


<!-- Sent from Reviewable.io -->

2020-07-17 20:56 UTC, nvanbenschoten commented
By the way, I think it would be worth stressing `TestKVNemesisMultiNode` with and without this fix and with merges enabled (i.e. the following line commented out):
https://github.com/cockroachdb/cockroach/blob/053ec8b76042eadc35591f8d13e50842db721da9/pkg/kv/kvnemesis/kvnemesis_test.go#L71-L74

2020-07-20 16:38 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/closed_timestamp_test.go, line 606 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAGS-H-HBhhUZf9E9Y:-MCeQHdyDv6Q9gzJI2tK:b6x9ott) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/closed_timestamp_test.go#L606)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> RaftElectionTimeoutTicks

Can we configure this to be lower for this test? We do that in other tests to get them to run faster.
</blockquote></details>

Added a preceding commit that moves `RaftHeartbeatIntervalTicks` into `RaftConfig`, as it defaults to `5` and we disallow `RaftElectionTimeoutTicks` to be lower than it. Previously there was no way to change `RaftHeartbeatIntervalTicks` from a TestCluster. 

I could've reduced the tick duration instead but I see that we use a low `RaftHeartbeatIntervalTicks` in a bunch of tests that use `multiTextContext` already.
___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MCeN6bV1kocKZLhtQrs:bjjbrt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What is the effect of it getting interpreted as the range being quiesced?
</blockquote></details>

Discussed offline: We actually emit an MLAI update right after a lease transfer because if the range were to go on to quiesce right after the transfer, its followers won't be able to implicitly tick closed timestamp updates until they `Request` the new leaseholder for it. Emitting it here right after a lease transfer avoids that little bit of latency. 
___
*[pkg/kv/kvserver/replica_write.go, line 156 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSyp80dTQZKnTPVA_:-MCeO0DgE_PGA1gFBZ8I:bjddktk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L156)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> executeReadOnlyBatchWithServerSideRefreshes
> ```

Mind finding all comments that reference this and fixing them now that the logic is not there?
</blockquote></details>

Fixed, had missed this one because of the incorrect capitalization.
___
*[pkg/kv/kvserver/replica_write.go, line 160 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSn_KCe9hx5lavoPa:-MCeNw4h5dVZOVq9G4_8:bptm8n9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L160)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: why move this here? Isn't this the branch dealing with the case where a proposal _was_ made that was not  a lease?
</blockquote></details>

Didn't mean to move the comment block, fixed.
___
*[pkg/kv/kvserver/batcheval/cmd_compute_checksum.go, line 39 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCECgIACQRRbU7ntwcV:-MCePoGv-RPLuuX0986Y:bm3ps4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aefbb75ffbf3c9e7d35391e6d084152b242e826/pkg/kv/kvserver/batcheval/cmd_compute_checksum.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yes, that's all true, but that's still an effect of what's going wrong here, not the actual bug we're fixing. We wouldn't describe a fix to Pebble that avoids losing a write as a fix for a serializable violation, right? It wouldn't be incorrect, per se, but it just doesn't add any real information to the conversation without being properly qualified.

I would lean towards describing exactly what could happen in this case, "a closed timestamp violation due to writes on the post-merged range that violate a closed timestamp spuriously reported by the pre-merged range." If you want to say that this could in-turn allow for a serializability violation, that would be fine.

---

In fact, coming back to this comment after having moved the previous two paragraphs from a comment on another use of "serializability violation" in `replica_write.go` before remembering that we already had this discussion going, this one, in particular, seems even worse. The fix here is necessary to prevent a bug in the fix for the bug with closed timestamp. So we're an extra step away! So saying that "ComputeChecksum needs to be serialized with Subsume requests to prevent a serializability violation" is a little absurd sounding and makes the comment less useful then it could be.
</blockquote></details>

Makes sense :+1: fixed.
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 138 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTWUt7-zMfSPpNIv5I:-MCeQCnQ2VUZgl_8ZUI0:b-g5urpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/batcheval/cmd_subsume.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to happen before `reply.FreezeStart = cArgs.EvalCtx.Clock().Now()`? We need to ensure that `FreezeStart` is greater than or equal to any closed timestamp broadcasted for `cArgs.EvalCtx.GetLeaseAppliedIndex()`, right?
</blockquote></details>

Whoops, should've been more careful. Fixed now.
___
*[pkg/kv/kvserver/batcheval/cmd_subsume.go, line 153 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTXIhV0SpfOcReIgWT:-MCeQBSbAkq-NuWHckV7:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f3f81289799f480fc68dc9c8ae8aeea8048ac8d/pkg/kv/kvserver/batcheval/cmd_subsume.go#L153)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"an unactionable"
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-07-20 16:51 UTC, aayushshah15 commented
I stressed `master` and this commit with merges enabled in kvnemesis, and they both run for a while (usually 1-1.5 hours) and fail right after a merge due to the `Generation` of the pre-merge RHS and post-merge LHS being equal. In particular, this is the asssertion that fires when a Rangefeed gets a `RangeFeedRetryError_REASON_RANGE_MERGED` and calls `Evict` on the range's eviction token. https://github.com/cockroachdb/cockroach/blob/0e496133d63011fb105f9ffc938043fbe12b4382/pkg/kv/kvbase/range_cache.go#L122

I added a bunch of logging and will post here once I see what's going on. Have y'all seen this panic fire before?





<!-- Sent from Reviewable.io -->

2020-07-20 22:05 UTC, aayushshah15 commented
Turns out @andreimatei's current in-flight PR #51437 fixes exactly these sorts of issues (relating to the presence of "speculative" descriptors in the cache). I'll stress master & this commit a bit further with his fix patched in.

2020-07-29 15:30 UTC, aayushshah15 commented
In addition to what I just posted in #51294, I also ran into some clock sync related `Fatal`s while stressing kvnemesis.

- I saw a run failing with this on server start.
```
clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the offset)
```
- And a run failing with this: 
```
kvnemesis_test.go:67: error executing 'SET CLUSTER SETTING kv.rangefeed.enabled = true': pq: update-setting: remote wall time is too far ahead (970.559966ms) to be trustworthy
```
With this warning message in the traces:
```
 event:util/hlc/hlc.go:260 [n2,s2] backward time jump detected (-0.965141 seconds)
```

Here are the logs for these: 
[clock_out_of_sync_onboot.zip](https://github.com/cockroachdb/cockroach/files/4995753/clock_out_of_sync_onboot.zip)
[backward_clock_jump.zip](https://github.com/cockroachdb/cockroach/files/4995757/backward_clock_jump.zip)

The second one seems..really weird?

2020-07-29 15:35 UTC, aayushshah15 commented
FWIW at this point, I believe I’m not going to find anything in these stress runs that falls under this PR. The exact issue this PR fixes is simulated by the targeted unit test. It’s easy to sink a lot of time looking into these nemeses failures so we should probably let it find stuff in the nightly runs & track them separately anyway.

2020-08-01 22:23 UTC, nvb approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 23 files at r14, 21 of 21 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MDg6hmu0ND6ZqxP3t-2:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @andreimatei)

___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MDg696_BXBj-HIGh4uq:bfza3sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
> ```
> because it gets interpreted as the range getting quiesced
> ```

This doesn't quite capture the conclusion of that conversation. Mind updating it to be a little more clear?
___
*[pkg/kv/kvserver/replica_write.go, line 156 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSyp80dTQZKnTPVA_:-MDg6MWb5b1DIs_FxdXT:bo46yr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L156)):*
> ```
> Subsume() cmd_subsume.go
> ```
Is this missing an "in"?
___
*[pkg/kv/kvserver/batcheval/cmd_compute_checksum.go, line 39 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MDg6UsuDrfkDqsPtpWQ:-MDg6UsuDrfkDqsPtpWR:bky5mhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d648956e7b4c95129c1fecbdbde8eb290c5605f/pkg/kv/kvserver/batcheval/cmd_compute_checksum.go#L39)):*
> ```
> a rare a closed timestamp
> ```

Delete the second "a".


<!-- Sent from Reviewable.io -->

2020-08-04 01:47 UTC, aayushshah15 reviewed
Thank you for the extremely detailed reviews @nvanbenschoten and @andreimatei 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-:-MDr8buX2Susjq1PAU9n:b-y95d7u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_closedts.go, line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MBAK-2f4ESb43sWgjtr:-MDr5ygbB0KFLqf5FfeB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a798b8a762ba7448f14d348a12ac3fecff580559/pkg/kv/kvserver/replica_closedts.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> because it gets interpreted as the range getting quiesced
> ```

This doesn't quite capture the conclusion of that conversation. Mind updating it to be a little more clear?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_write.go, line 156 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MCTSyp80dTQZKnTPVA_:-MDr6E-w3gZgs9_7tlBu:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed3b0b09c67a89645d023a7d8ddd9c5ca03a5af8/pkg/kv/kvserver/replica_write.go#L156)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> Subsume() cmd_subsume.go
> ```
Is this missing an "in"?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/batcheval/cmd_compute_checksum.go, line 39 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/50265#-MDg6UsuDrfkDqsPtpWQ:-MDr6Nzb8z9ujcSfpnkr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d648956e7b4c95129c1fecbdbde8eb290c5605f/pkg/kv/kvserver/batcheval/cmd_compute_checksum.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> a rare a closed timestamp
> ```

Delete the second "a".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-04 01:49 UTC, aayushshah15 commented
bors r=nvanbenschoten,andreimatei

2020-08-04 06:16 UTC, merged