execinfra: adjust handling of trailing metadata
cockroachdb/cockroach pull request #50319
Opened 2020-06-17 00:34 UTC by yuzefovich

We have a special "read within uncertainty interval" error that needs to
be swallowed when the processor is in draining state. Previously, this
was checked only for metadata coming from the inputs being drained.
However, we also need to check the trailing metadata coming from
`trailingMetadataCallback` and possibly swallow it as well because that
metadata originates after the processor transitions into the draining
state.

However, there is one special piece of metadata that previously lived in
`trailingMeta` - the error that `MoveToDraining` method is called with.
That error is actually a "running" metadata, not "trailing", and this
commit separates it out.

The problem of not swallowing the error from trailing meta has been
recently exposed by the change to parallel unordered synchronizer:
previously, in the unit test when forced RWUI error occurred, it was
propagated via `colexecerror.InternalError` which was caught by the
materializer which then moved to draining (making the error that special
piece of metadata described above); however, with the change to the
synchronizer, the error is now propagated as trailing meta and should be
swallowed in some cases (when the materializer is the in draining state).

Fixes: 50299.

Release note: None

2020-06-17 00:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50319)
<!-- Reviewable:end -->

2020-06-17 14:03 UTC, asubiotto requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50319)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/execinfra/processorsbase.go, line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50319#-MA1UY4qBJK9E5jEp9qR:-MA1UY4qBJK9E5jEp9qS:b-sy4fsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc4e8a9ec869f47ca8ecba9427cd54bd13551d5/pkg/sql/execinfra/processorsbase.go#L615)):*
> ```Go
> func maybeSwallowErrorWhenDraining(
> 	meta *execinfrapb.ProducerMetadata,
> ) *execinfrapb.ProducerMetadata {
> ```

I don't think this needs to return a `meta`. A boolean and a rename to `shouldSwallow<...>` is probably best.
___
*[pkg/sql/execinfra/processorsbase.go, line 672 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50319#-MA1__fp66WnJJduv-mW:-MA1__fp66WnJJduv-mX:blfhaft) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dc4e8a9ec869f47ca8ecba9427cd54bd13551d5/pkg/sql/execinfra/processorsbase.go#L672)):*
> ```Go
> 		meta := &pb.trailingMeta[0]
> 		pb.trailingMeta = pb.trailingMeta[1:]
> 		if meta = maybeSwallowErrorWhenDraining(meta); meta != nil {
> ```

You probably need to update the `StateTrailingMeta` comment as well.


<!-- Sent from Reviewable.io -->

2020-06-17 14:47 UTC, andreimatei reviewed
> The problem of not swallowing the error from trailing meta has been
recently exposed by the change to parallel unordered synchronizer:
previously, in the unit test when forced RWUI error occurred, it was
propagated via colexecerror.InternalError which was caught by the
materializer which then moved to draining (making the error that special
piece of metadata described above); however, with the change to the
synchronizer, the error is now propagated as trailing meta and should be
swallowed in some cases (when the materializer is the in draining state).

Can you explain this to me more? It sounds like this error started being deferred some instead of being pushed to the synchronizer's output asap. Why is that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50319#-:-MA1jHf60fpOHlmUBUum:b9ui43d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-06-17 15:48 UTC, asubiotto commented
I was also curious about that ^ during the standup. I think what's happening here is that there's a race between reading from the `errCh` and `batchCh` and sometimes we're reading metadata from the `batchCh` first and propagating that metadata before returning an error. Not sure how to fix that at a first glance because we need to know to propagate the error with `InternalError` (I think) so can't just use `batchCh` and get rid of `errCh`.

2020-06-17 18:39 UTC, yuzefovich commented
> It sounds like this error started being deferred some instead of being pushed to the synchronizer's output asap.

Yes, this is my understanding as well, but I don't immediately see why it is the case. Maybe Alfonso's comment provides the explanation (about the race). Let's hold off on this PR for now, and I'll assign the issue to Alfonso to take a look at.

2020-06-18 13:19 UTC, asubiotto commented
The fix was simpler than that. The ParallelUnorderedSynchronizer needs to implement its own custom draining logic (since it handles non-row source inputs) and was not swallowing errors that occurred after a switch to draining.

Closing in favor of #50388

2020-06-18 13:19 UTC, closed without merging