docs/RFCS: first draft of a sqlliveness RFC
cockroachdb/cockroach pull request #50377
Opened 2020-06-18 00:44 UTC by ajwerner

There's been a lot of back-and-forth over what we're trying to build and why.
Hopefully an RFC can help us to consolidate on terminology, goals, and
implementation details.

Release note: None

2020-06-18 00:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50377)
<!-- Reviewable:end -->

2020-06-18 20:08 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7uRyQ6-0Nb25h5PI_:-MA7uRyQ6-0Nb25h5PIa:bmqqmqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L47)):*
> ```Markdown
> This use maps directly to the use of node liveness to drive epoch-based
> range leases. We would like to utilize SQL liveness to create leases
> which do not need to be independently heartbeated to remain active. This
> ```

It would be nice to mention the scalability concern up front (this is the blowup from one SQL instance holding leases on many tables). I didn't realize that that was the issue until much later in the doc. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7vH9P7W2H73_MmXSv:-MA7vH9P7W2H73_MmXSw:bu02lfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L55)):*
> ```Markdown
> protocol is madness.
> 
> 2) Discovery of SQL instances and their metadata.
> ```

We need to be careful with this - we specifically avoided use cases like this in node liveness because of the critical importance of the liveness range (so we keep its load to the minimum writes necessary). Most nodes don't even read from the node liveness range directly; one node reads and then the information propagates via gossip. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sJr_-vvKzX8eikhB:-MA7sJr_-vvKzX8eikhC:b-cvd2wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L64)):*
> ```Markdown
> ## Key Terms
> 
>  * `Instance` - An instance is a (unix) process running a SQL server. An instance is bound to a single SQL tenant. Instances have at various times been referred to as a SQL pod, or a SQL node. An instance will have an `InstanceID` which is gauranteed to be unique within the tenant cluster while the `Instance` exists. 
> ```

"Instance" is pretty generic; while we're introducing new terminology I'd prefer to use something more descriptive. At least call it a "SQL Instance". 
___
*[docs/RFCS/20200615_sql_liveness.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sr7M7GpbyDvEkify:-MA7sr7M7GpbyDvEkifz:bkykl8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L65)):*
> ```Markdown
> 
>  * `Instance` - An instance is a (unix) process running a SQL server. An instance is bound to a single SQL tenant. Instances have at various times been referred to as a SQL pod, or a SQL node. An instance will have an `InstanceID` which is gauranteed to be unique within the tenant cluster while the `Instance` exists. 
>  * `SQLInstanceID` - A 64-bit integer ID associated with an instance. It is guaranteed that each existing `Instance` will have a unique `SQLInstanceID`. It is, however, possible that an `SQLInstanceID` will be
> ```

Unless there's a really strong reason to use an int64, IDs should be bytes, not a numeric type (you're not going to do math with them). 
___
*[docs/RFCS/20200615_sql_liveness.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7u4tkB4S5VX-QHtfT:-MA7u4tkB4S5VX-QHtfU:b-c55zfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L68)):*
> ```Markdown
>  recycled and used by a different `Instance` which shares no state or
>  properties with a previous holder of that ID.
>  * `Epoch` - An epoch is a sequence number associated with the liveness
> ```

If a SQLInstanceID is reused, does its epoch restart from zero or continue from its previous value?
___
*[docs/RFCS/20200615_sql_liveness.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7ztRy3yGWrVBKVHdT:-MA7ztRy3yGWrVBKVHdU:b-u3q33y) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L70)):*
> ```Markdown
>  * `Epoch` - An epoch is a sequence number associated with the liveness
> of an `SQLInstanceID` in a tenant cluster.
>  * `Session` - A session is defined as a tuple of `(SQLInstanceID, Epoch)`.
> ```

What do we gain by using a tuple like this instead of a single opaque SessionID? Do we ever use the capability to link two sessions of the same instance? 
___
*[docs/RFCS/20200615_sql_liveness.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7y81vBCz-i6yisL7o:-MA7y81vBCz-i6yisL7p:b-k095yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L81)):*
> ```Markdown
> transactions which utilize the claimed resource or the transaction must
> commit before a known expiration timestamp for the session (perhaps by
> utilizing the `*kv.Txn`'s commit deadline functionality which has serious room for improvement).
> ```

It's perhaps worth noting that this commit deadline is *not* how range leases are implemented. It's how SQL descriptor leases are implemented, which came after the fact and were not part of the original design for node liveness. Range leases are ignorant of the expiration of epochs. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7zBqx8YxYzvr6cvZ2:-MA7zBqx8YxYzvr6cvZ3:b97ab3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L303)):*
> ```Markdown
> 
> Maybe that 5m is excessive as we anticipate running SQL
> pods on pre-emptible instances. Shortening it too much is costly here.
> ```

Another reason these leases are so long is that we can't (couldn't?) update the commit deadline for a transaction so we needed to allow plenty of buffer time. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7zQzHEUEw4NZ_dsus:-MA7zQzHEUEw4NZ_dsut:b4q4v5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L308)):*
> ```Markdown
> 
> One postgres feature that we've discussed building are
> `pg_advisory_locks`. Having a sql-level liveness construct
> ```

I haven't thought about this deeply but I've thought now that we have SELECT FOR UPDATE we should implement these advisory locks as SFU on a system locks table. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA80KsX5e6i21jXhcZH:-MA80KsX5e6i21jXhcZI:b38mgra) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L357)):*
> ```Markdown
> observability more difficult for little obvious gain. The epoch-based leases in
> KV have shown us that node epochs, given their monotonic nature, give state in
> the cluster a sense of time and place.
> ```

This seems less valuable to me in a world in which sql instances are themselves more ephemeral. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA81Kuh9lEaEuB8yGZd:-MA81Kuh9lEaEuB8yGZe:b-lumese) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L427)):*
> ```Markdown
>         * Big bummer here is that we're talking about sticking foreign key
>           relationships between system tables.
>         * Also seems r [...]

2020-06-19 02:55 UTC, ajwerner reviewed
Thanks for the read. An alternative layout might be something like:

```
CREATE TABLE system.sql_liveness (
    session_id         UUID PRIMARY KEY, -- or a STRING
    expiration         DECIMAL NOT NULL,
    sql_instance_id INT8 NOT NULL -- does this need to be here?
)

CREATE TABLE system.sql_instances (
    sql_instance_id INT8 PRIMARY KEY
    -- ... metadata
)
```

This is what @spaskob was originally thinking - or at least close to it. I pushed back only because I was worried about figuring out which container in our deployment actually is running some job. Perhaps that's overblown because we could just store both the session and sql_instance_id in the jobs table.

An even more extreme refinement might be to not include the `sql_instance_id` in the `system.sql_liveness` table at all. The real thing that I think @spaskob was thinking is just:

```
CREATE TABLE system.sql_lease_sessions (
     id               STRING PRIMARY KEY,
     expiration DECIMAL NOT NULL -- hlc
)
```

This would be just like `etcd` leases and would not be tightly coupled to instances in any way. Is that better?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MA9TjsN46ZRC2ZczP7G:bnhvahx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7vH9P7W2H73_MmXSv:-MA9Qh-aCB43OY33Pvsj:bhmjvjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We need to be careful with this - we specifically avoided use cases like this in node liveness because of the critical importance of the liveness range (so we keep its load to the minimum writes necessary). Most nodes don't even read from the node liveness range directly; one node reads and then the information propagates via gossip. 
</blockquote></details>

My thinking has been that the tightness here doesn't have to be as big. Also, I 
___
*[docs/RFCS/20200615_sql_liveness.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sJr_-vvKzX8eikhB:-MA9TRRZAsrGfXmjEalg:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L64)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

"Instance" is pretty generic; while we're introducing new terminology I'd prefer to use something more descriptive. At least call it a "SQL Instance". 
</blockquote></details>

:+1: 
___
*[docs/RFCS/20200615_sql_liveness.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sr7M7GpbyDvEkify:-MA9TOGk-FrPetZe4U_K:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L65)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Unless there's a really strong reason to use an int64, IDs should be bytes, not a numeric type (you're not going to do math with them). 
</blockquote></details>

Ack.
___
*[docs/RFCS/20200615_sql_liveness.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7u4tkB4S5VX-QHtfT:-MA9QtmU8ZG4N00G1Vpb:b-zczuse) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L68)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If a SQLInstanceID is reused, does its epoch restart from zero or continue from its previous value?
</blockquote></details>

I was thinking it continues. There's an open question about when rows ever get removed that I'll add. Perhaps that's the best reason to use independent session IDs.
___
*[docs/RFCS/20200615_sql_liveness.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7ztRy3yGWrVBKVHdT:-MA9Qxf858asW0tBHMef:b-2gwqns) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L70)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What do we gain by using a tuple like this instead of a single opaque SessionID? Do we ever use the capability to link two sessions of the same instance? 
</blockquote></details>

I suppose not. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7y81vBCz-i6yisL7o:-MA9T4fx5yRs1ZsVywb_:bfnm2jb) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L81)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's perhaps worth noting that this commit deadline is *not* how range leases are implemented. It's how SQL descriptor leases are implemented, which came after the fact and were not part of the original design for node liveness. Range leases are ignorant of the expiration of epochs. 
</blockquote></details>

:thumbsup: I'd like to incorporate the discussion going on at the bottom of the document higher up here. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7zBqx8YxYzvr6cvZ2:-MA9R3ZR57lbzt2c94SJ:b-pqtyt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L303)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Another reason these leases are so long is that we can't (couldn't?) update the commit deadline for a transaction so we needed to allow plenty of buffer time. 
</blockquote></details>

This is discussed in open questions. We should set the deadline right as we create `EndTransaction`s regardless of what happens here.
___
*[docs/RFCS/20200615_sql_liveness.md, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7zQzHEUEw4NZ_dsus:-MA9R8vjEcwwT9NPFLvo:b-9xn8v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L308)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I haven't thought about this deeply but I've thought now that we have SELECT FOR UPDATE we should implement these advisory locks as SFU on a system locks table. 
</blockquote></details>

I don't think it's that simple. `pg_advisory_lock` has some tricky semantics that outlive individual transactions and can be tied to SQL sessions. There was a pretty good exploration of this during the hackathon. In the hackathon, the pitch we ran with was to expose a special type of intent which can act as a lease. The difference between a lease intent and a regular intent is that when a lease intent is resolved due to expiration, it moves the timestamp cache to its expiration time. 

The only point I'm trying to make is that there are a number of ways to implement `pg_advisory_lock` and this isn't definitely the right one. The unreplicated locks in `SELECT FOR UPDATE` aren't an obvious fit but something using intents or some slight generalization might be. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA80KsX5e6i21jXhcZH:-MA9Ruqd2FyXFNfBe-3-:b-bcobyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L357)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This seems less valuable to me in a world in which sql instances are themselves more ephemeral. 
</blockquote></details>

F [...]

2020-06-22 17:07 UTC, bdarnell reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7vH9P7W2H73_MmXSv:-MARzCW30ZrNPSNPjUpw:b-7bk6bs) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My thinking has been that the tightness here doesn't have to be as big. Also, I 
</blockquote></details>

This comment is incomplete.
___
*[docs/RFCS/20200615_sql_liveness.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA80KsX5e6i21jXhcZH:-MARznSZ2RTwFn_vvZMy:b-s4zd5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L357)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Fair. I'm more than happy to rework the basic structure here. My concern with a UUID is that it's going to make it hard to map leases back to a sql pod. One compromise could be to put the ID which internally contains the `SQLInstanceID`? Another might be to store the SQLInstanceID in the session row in a different column. 
</blockquote></details>

I think a separate column for this makes more sense than encoding stuff in the ID. 


<!-- Sent from Reviewable.io -->

2020-06-22 17:44 UTC, ajwerner reviewed
@bdarnell in the above example we'd decouple the instance metadata from the liveness sessions. In that world I'd anticipate that instances write to the `system.sql_instances` prior to attempting to create the first session. I'd like to have a discussion about that decomposition and whether it's well received before I go through and adopt it in this RFC. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MAS77EqBi-SbAu8CgMc:b-4vsr1t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7vH9P7W2H73_MmXSv:-MAS6qnk7L_nvCxKfCMm:b-ebdjpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L55)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This comment is incomplete.
</blockquote></details>

True, I moved my discussion to the top level as I started to think more about this proposal. I don't feel a strong need to tightly couple these pieces of information. If I'm reading you correctly, you might like something closer to what I outlined in the top-level comment. Let's discuss there?


<!-- Sent from Reviewable.io -->

2020-06-22 21:17 UTC, bdarnell reviewed
I like the two-table version above. The instance ID isn't strictly necessary here but I think it will prove useful for observability/debugging. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MASspQg1rtRpJrzQ6sW:b1fea7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)



<!-- Sent from Reviewable.io -->

2020-06-23 13:15 UTC, ajwerner commented
@spaskob I have a sense that you'll find yourself in agreement with Ben. Do you have interest in converting the language of the proposal over to your original proposal which he has endorsed?

2020-06-23 15:08 UTC, spaskob requested changes
Sorry for the delay - I was OOO on Monday. Yes, it is true that originally I was in favor of session id-s. However Andrew quite convincingly won me over to the pod ID + epoch) approach and after having tried in a hacky implementation for jobs, I must say it seems quite natural at least for jobs. One of the big advantages is that it makes writing a query to get expired or currently claimed job rows quite easy and readable. So fa the only drawback I've read about the epoch approach is that invalidating an epoch will lock the row and it will not prevent the sql pod to obtain a new epoch. I think this should be quite fine for jobs since if another node has detected the partition it will attempt next to steal the jobs and there is not much merit resurrecting the original node at the same time.
I am going to finish today a WIP PR that illustrates how epoch based claims can be used for jobs, I think this PR can be a useful place to discuss more concretely open questions in this RFC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MAWfdiE9CNLbyYYw_Wf:bd7r7fh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWU0FSAkUoj3cOLEzj:-MAWU0FSAkUoj3cOLEzk:b-txp8m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L23)):*
> ```Markdown
> 
> The driving motivation for this work is the usage of node-liveness 
> epochs as the basis for the best-effort locks in the jobs registry.
> ```

Is this motivation strong enough for as a general solution as described in this RFC? One may argue that the requirements for jobs are quite soft - a long adoption cycle of 30s, small amount of nodes and relatively small number of running jobs, no sub-second requirements for job failover. For such a use case any naive approaches should just work. And one may argue that a naive but easy to program against and flexible approach may be preferable.

In this RFC we are trading higher complexity and less flexibility compared to a jobs specific solution for a promise that the framework will be more generally applicable. For this promise to be realistic we need to include in the motivation other compelling use cases IMO.

Additionally for jobs, our prior experience of #registries = # nodes may be misleading for the future. What is our expectation of the number of sql pods that will be registered?  What constraints should this system conform to in the new world fo multi-tenancy? Without analysis of how this system's requirements will evolve it's hard for me to justify a general solution vs a jobs specific one.
___
*[docs/RFCS/20200615_sql_liveness.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sr7M7GpbyDvEkify:-MAWVfXL4dUh9rsyHoT0:bp5mvi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Ack.
</blockquote></details>

Additionally BYTES column type allows for the option to write an encoded proto in the future.
___
*[docs/RFCS/20200615_sql_liveness.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7u4tkB4S5VX-QHtfT:-MAWVrTyBLrkJo99m88G:baq7egq) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was thinking it continues. There's an open question about when rows ever get removed that I'll add. Perhaps that's the best reason to use independent session IDs.
</blockquote></details>

My thinking is that it also continues. When a pod discovers that its epoch has been bumped it picks the current epoch if the deadline has not expired or bumps it and sets a new deadline that way all epochs < current one are considered invalid.
___
*[docs/RFCS/20200615_sql_liveness.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7ztRy3yGWrVBKVHdT:-MAWW9vCAeOFfRVYNG49:b-16k4gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L70)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I suppose not. 
</blockquote></details>

I think we might, also it makes it easier for a client to write queries for finding their current lease. An example from my current work in progress implementation using epochs:

```
	// Process jobs claimed as running or reverting.
	rows, err := r.ex.QueryEx(
		ctx, "select-running/reverting-jobs", nil,
		sqlbase.InternalExecutorSessionDataOverride{User: security.RootUser}, `
SELECT id FROM system.jobs
WHERE (status = $1 OR status = $2) AND (sqlinstance_id = $3 AND sqlinstance_epoch = $4)`,
		StatusRunning, StatusReverting, r.ID(), epoch,)
```
___
*[docs/RFCS/20200615_sql_liveness.md, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXCNX2n18HU4qfBHG:-MAWXCNX2n18HU4qfBHH:b-mcr4jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L127)):*
> ```Markdown
> }
> 
> type SessionIterator func(SessionInfo) (wantMore bool)
> ```

What is the benefit of iterators when the number of sessions is the number of SQL pods and I'd assume they are << O(1000)? A list interface will make it much easier for a developer to write and maintain code.
___
*[docs/RFCS/20200615_sql_liveness.md, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXaB-0V32kxXntWfJ:-MAWXaB-0V32kxXntWfK:brf1eqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L134)):*
> ```Markdown
> ```
> 
> Above find something of a straw-man interface to the `sqlliveness`
> ```

I think coming up with good interfaces is hard and especially so when we have only one use case to "test" them on. I feel strongly against defining a high level interface before we have another use case and I am willing to pay the price of future refactoring of jobs package when such interface has matured.


<!-- Sent from Reviewable.io -->

2020-06-23 17:52 UTC, ajwerner reviewed
> One of the big advantages is that it makes writing a query to get expired or currently claimed job rows quite easy and readable. 

I'd love to unpack this further. Perhaps in the context of another PR. I anticipate that we can make this query clean regardless of whether the lease is scoped to `(SQLInstanceID, Epoch)`  or `(SessionID, SQLInstanceID, Epoch)` where in the latter the opaque session ID is the actual claim and the other fields are metadata.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MAXGkec8oHEW1QHJtVQ:b-owtnsd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWU0FSAkUoj3cOLEzj:-MAXHG-y4tsEgVV0VYiJ:bzgfjna) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L23)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Is this motivation strong enough for as a general solution as described in this RFC? One may argue that the requirements for jobs are quite soft - a long adoption cycle of 30s, small amount of nodes and relatively small number of running jobs, no sub-second requirements for job failover. For such a use case any naive approaches should just work. And one may argue that a naive but easy to program against and flexible approach may be preferable.

In this RFC we are trading higher complexity and less flexibility compared to a jobs specific solution for a promise that the framework will be more generally applicable. For this promise to be realistic we need to include in the motivation other compelling use cases IMO.

Additionally for jobs, our prior experience of #registries = # nodes may be misleading for the future. What is our expectation of the number of sql pods that will be registered?  What constraints should this system conform to in the new world fo multi-tenancy? Without analysis of how this system's requirements will evolve it's hard for me to justify a general solution vs a jobs specific one.
</blockquote></details>

We should ancipate that there will be many more sql pods than KV nodes. Furthermore, those sql pods will be rate-limited at the KV layer. The way I see it, the less heartbeating we can do at the sql layer, the better. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7ztRy3yGWrVBKVHdT:-MAXHlKf6C4RoTbo_0Cy:b5z8wz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L70)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I think we might, also it makes it easier for a client to write queries for finding their current lease. An example from my current work in progress implementation using epochs:

```
	// Process jobs claimed as running or reverting.
	rows, err := r.ex.QueryEx(
		ctx, "select-running/reverting-jobs", nil,
		sqlbase.InternalExecutorSessionDataOverride{User: security.RootUser}, `
SELECT id FROM system.jobs
WHERE (status = $1 OR status = $2) AND (sqlinstance_id = $3 AND sqlinstance_epoch = $4)`,
		StatusRunning, StatusReverting, r.ID(), epoch,)
```
</blockquote></details>

There is nothing that precludes additionally including SQLInstanceID in the jobs table in addition to an opaque session ID. We could then do `(sqlinstance_id = $3 AND session = $4)` and it would all be the same. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXCNX2n18HU4qfBHG:-MAXI1oPCxQq_BQP4MQu:b37quja) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L127)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

What is the benefit of iterators when the number of sessions is the number of SQL pods and I'd assume they are << O(1000)? A list interface will make it much easier for a developer to write and maintain code.
</blockquote></details>

I generally prefer the iterator approach as it later lends itself to both pagination and predicates. It's easy to implement a slice approach on top of an iterator but not very valuable to do it the other way. Furthermore, doing an iterator approach allows the internal data structure to be implemented as, say, a BTree and not incur allocations upon invocation.

I'm not wedded here but don't buy the idea that the iterator approach is particularly difficult. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXaB-0V32kxXntWfJ:-MAXIUx952puMZWCfu9P:b-xdcd2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L134)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I think coming up with good interfaces is hard and especially so when we have only one use case to "test" them on. I feel strongly against defining a high level interface before we have another use case and I am willing to pay the price of future refactoring of jobs package when such interface has matured.
</blockquote></details>

This here is probably the strongest point of contention. In my mind, a clear abstraction is easier to evolve and evaluate than a leaky set of ad-hoc functionality. In fact, I find that often the hardest thing is to understand what the abstractions really are.

All that being said, i do think there's a trap in thinking that abstractions which exist are the right ones to exist that can lead to awkward code which bends itself backwards trying to make a bad abstraction work for a new use-case rather than changing the abstraction. 


<!-- Sent from Reviewable.io -->

2020-06-30 04:00 UTC, ajwerner reviewed
I've updated the RFC to utilize the unique session ID approach. See how y'all feel about it. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MB2NT-w1UiaESPr-eln:b5c4aaz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7uRyQ6-0Nb25h5PI_:-MB2LOUK-Pyv4zRjK7Vx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L47)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It would be nice to mention the scalability concern up front (this is the blowup from one SQL instance holding leases on many tables). I didn't realize that that was the issue until much later in the doc. 
</blockquote></details>

Done.
___
*[docs/RFCS/20200615_sql_liveness.md, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7zQzHEUEw4NZ_dsus:-MB2NOuH29yyAn_IA1pR:b-d8k6bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L308)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think it's that simple. `pg_advisory_lock` has some tricky semantics that outlive individual transactions and can be tied to SQL sessions. There was a pretty good exploration of this during the hackathon. In the hackathon, the pitch we ran with was to expose a special type of intent which can act as a lease. The difference between a lease intent and a regular intent is that when a lease intent is resolved due to expiration, it moves the timestamp cache to its expiration time. 

The only point I'm trying to make is that there are a number of ways to implement `pg_advisory_lock` and this isn't definitely the right one. The unreplicated locks in `SELECT FOR UPDATE` aren't an obvious fit but something using intents or some slight generalization might be. 
</blockquote></details>

I've removed this given I didn't have a coherent proposal.
___
*[docs/RFCS/20200615_sql_liveness.md, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA81_DGAipQhwUxfJIL:-MB2NMF14oCskeob4-PY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L432)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

And like range leases. You must observe the liveness record in order to request a new lease, and then it's the local lease record that is consulted for future operations. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-01 14:27 UTC, ajwerner reviewed
@andreimatei I added a rather speculative section on transaction record heartbeating. I also added a section on CHANGEFEED one-version leases like from the hack-a-thon as a future use case. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MB9kv0V65v_QSnlsOiK:brpnhz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7vH9P7W2H73_MmXSv:-MB9l4BV4uoXRKVYX2E0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

True, I moved my discussion to the top level as I started to think more about this proposal. I don't feel a strong need to tightly couple these pieces of information. If I'm reading you correctly, you might like something closer to what I outlined in the top-level comment. Let's discuss there?
</blockquote></details>

Done.
___
*[docs/RFCS/20200615_sql_liveness.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sJr_-vvKzX8eikhB:-MB9l5DnAZqPlkWHecl8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[docs/RFCS/20200615_sql_liveness.md, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7sr7M7GpbyDvEkify:-MB9l85D7W55P9Y8wwWi:b-kpms79) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L65)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Additionally BYTES column type allows for the option to write an encoded proto in the future.
</blockquote></details>

The `SQLInstanceID` is an existing concept. The `SessionID` has become an opaque bytes identifier. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7ztRy3yGWrVBKVHdT:-MB9lFx02kMVvsn4_kuv:ba4ylej) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L70)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

There is nothing that precludes additionally including SQLInstanceID in the jobs table in addition to an opaque session ID. We could then do `(sqlinstance_id = $3 AND session = $4)` and it would all be the same. 
</blockquote></details>

This is no longer relevant. Resolving. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXCNX2n18HU4qfBHG:-MB9lO100zohGfe-xpiy:b3oc2az) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L127)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I generally prefer the iterator approach as it later lends itself to both pagination and predicates. It's easy to implement a slice approach on top of an iterator but not very valuable to do it the other way. Furthermore, doing an iterator approach allows the internal data structure to be implemented as, say, a BTree and not incur allocations upon invocation.

I'm not wedded here but don't buy the idea that the iterator approach is particularly difficult. 
</blockquote></details>

I've removed the concept of iteration. Now there's only a predicate. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA80KsX5e6i21jXhcZH:-MB9lXQT0_Q5qGXwBdv9:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L357)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think a separate column for this makes more sense than encoding stuff in the ID. 
</blockquote></details>

Ack.
___
*[docs/RFCS/20200615_sql_liveness.md, line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA81Kuh9lEaEuB8yGZd:-MB9lZ0D-SsmvUmLewIQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L427)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Good point. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-02 08:26 UTC, spaskob approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWXaB-0V32kxXntWfJ:-MBDbS648YETR6ko2Jz2:b-f10uzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L134)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This here is probably the strongest point of contention. In my mind, a clear abstraction is easier to evolve and evaluate than a leaky set of ad-hoc functionality. In fact, I find that often the hardest thing is to understand what the abstractions really are.

All that being said, i do think there's a trap in thinking that abstractions which exist are the right ones to exist that can lead to awkward code which bends itself backwards trying to make a bad abstraction work for a new use-case rather than changing the abstraction. 
</blockquote></details>

Sounds good, I am preparing the jobs PR to use random session IDs instead of epoch based leases. Let's continue the discussion about the API there. Based on our discussions I don't anticipate any big changes.


<!-- Sent from Reviewable.io -->

2020-07-06 16:42 UTC, ajwerner reviewed
@bdarnell any chance I could get you to weigh in on the current state of this RFC? @spaskob is itching to get an implementation under way.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MB_-KMvC7F2tmFJJ1TQ:bnakil9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)



<!-- Sent from Reviewable.io -->

2020-07-06 20:07 UTC, bdarnell approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-:-MB_jJ_BCQS3LqUbueKr:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @bdarnell, and @spaskob)

___
*[docs/RFCS/20200615_sql_liveness.md, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MAWU0FSAkUoj3cOLEzj:-MB_gVsZ-bVSHjdUEz_x:bbcjcce) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We should ancipate that there will be many more sql pods than KV nodes. Furthermore, those sql pods will be rate-limited at the KV layer. The way I see it, the less heartbeating we can do at the sql layer, the better. 
</blockquote></details>

I agree that even if the job system is the first user of this scheme, it's the potential use for things like table leases that really justify it IMHO. 
___
*[docs/RFCS/20200615_sql_liveness.md, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50377#-MA7u4tkB4S5VX-QHtfT:-MB_hAg7E-sAlfzIV44O:b-dik826) ([raw file](https://github.com/cockroachdb/cockroach/blob/db5420f6f50fc23797dabac523cb984255e0d799/docs/RFCS/20200615_sql_liveness.md#L68)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

My thinking is that it also continues. When a pod discovers that its epoch has been bumped it picks the current epoch if the deadline has not expired or bumps it and sets a new deadline that way all epochs < current one are considered invalid.
</blockquote></details>

I think we can remove a lot of detail about the SQLInstanceID since it's a preexisting concept and we're no longer using it to construct session IDs here.


<!-- Sent from Reviewable.io -->

2020-07-06 21:25 UTC, ajwerner commented
TFTR!

bors r=bdarnell,spaskob

2020-07-06 22:34 UTC, merged