cloud: Add FileTableReadWriter to interface with user scoped blob tables
cockroachdb/cockroach pull request #50493
Opened 2020-06-22 18:08 UTC by adityamaru

This is a building block for supporting user scoped file upload and
download to and from a cluster, details of which are being discussed
in #47211.

FileTableReadWriter can be used to store, retrieve and delete blobs and
metadata of files, from user scoped tables. Access to these tables is
restricted to the root/admin user and the user responsible for
triggering table creation in the first place.

Under-the-hood FileTableReadWriter operates on user specific File and
Payload tables. The File table stores the metadata, while the Payload
table stores the contents of the file as chunks of a configurable size.

Release note: None

2020-06-22 18:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50493)
<!-- Reviewable:end -->

2020-06-22 22:32 UTC, miretskiy requested changes
Not sure I like the name 'filetablereaderwriter'... We are storing files inside sql tables...so, maybe package
could be: 
   * storage/cloud/db. (*i actully like this one -- short, easy to type, describes where the data lives)
   * storage/cloud/table
   * storage/cloud/sql

I don't know... just the filetablereaderwriter is a mouthful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-:-MASDyZ95Zkx3M88Tu79:b-y1avec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT7OyS8Mq70dgxz8qF:-MAT7OyS8Mq70dgxz8qG:b-ptbiuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L186)):*
> ```Go
> // -	Writes the filename metadata to File table.
> // - 	Write the filename chunks to the Payload table.
> //
> ```

This is a big function, which does too many things inline.
I would prefer you split table existence/creation checks as well as file existence checks into helpers.

Come to think of it, table creation/roles/revoke, etc should be moved into separate type altogether.
FileTableReaderWriter ought to concern itself with the reading and writing.

Creation of storage space for the file reader is a separate thing (think file vs file system)
___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT7QIBEeyWP87CBbhC:-MAT7QIBEeyWP87CBbhD:bn753zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L187)):*
> ```Go
> // - 	Write the filename chunks to the Payload table.
> //
> // All the above stages are performed within a txn to guarantee atomicity.
> ```

I assume this works (since some ddl statements cannot be mixed with regular sql statements under the same transaction)
___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT5-xXE4QrsMHIEeP-:-MAT5-xY9BtOgus5mVy5:b-qjx8c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L228)):*
> ```Go
> 
> 		// The Payload table is interleaved in the File table to prevent repetition
> 		// of filename for every chunk at the KV level.
> ```

isn't a bit complex? should we use e.g. file id as a unique int, and foreign key on that?
Just curious why you decided to go this route.


<!-- Sent from Reviewable.io -->

2020-06-23 16:16 UTC, miretskiy reviewed
For the record: @adityamaru  and I had some offline chats about how this API could be structured.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-:-MAWxh8t2m4JTg580Bgp:bpdz3h2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)



<!-- Sent from Reviewable.io -->

2020-06-24 03:03 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT7OyS8Mq70dgxz8qF:-MAXPMCo3HGLL2x6DDDz:b-78e9kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L186)):*
>           2 hours ago
>         miretskiyYevgeniy Miretskiy
As per our discussions offline I have split the existence check, privilege granting etc to helpers. Also introduced an isolated Writer and Reader for more fine-grained responsibilities.
Eventually, we can probably nuke `FileTableSystem` and move all of its methods to the custom `file_table_storage.go` implementation of ExternalStorage.
___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT7QIBEeyWP87CBbhC:-MAXPrOb80bi6Dy59Rkk:bieccjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L187)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I assume this works (since some ddl statements cannot be mixed with regular sql statements under the same transaction)
</blockquote></details>

Tests are passing so I think these sets of statements seem fine within a single txn.
___
*[pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAT5-xXE4QrsMHIEeP-:-MAXPvcw-gEmOI-QPsFZ:b-m7uuu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a626ec8a68a35358c39d2cab70790eba3771324/pkg/storage/cloud/filetablereadwriter/file_table_read_writer.go#L228)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

isn't a bit complex? should we use e.g. file id as a unique int, and foreign key on that?
Just curious why you decided to go this route.
</blockquote></details>

I thought this fit the description on when to use interleaved (https://www.cockroachlabs.com/docs/stable/interleave-in-parent.html#interleaved-hierarchy). I thought it would provide us some query gains as mentioned in the docs as we are not repeating the filename in the key for every row of the child table. I don't feel strongly either way, so open to suggestions.


<!-- Sent from Reviewable.io -->

2020-06-24 03:08 UTC, adityamaru commented
> Not sure I like the name 'filetablereaderwriter'... We are storing files inside sql tables...so, maybe package
> could be:
> 
> * storage/cloud/db. (*i actully like this one -- short, easy to type, describes where the data lives)
> * storage/cloud/table
> * storage/cloud/sql

RFAL! I have currently gone with `filetable` as the package name because I felt that just `table` or `db` was too wide, and did not capture the fact that this a storage which only stores files in sql tables. I am open to ideating some more on this 🙂

2020-06-24 15:37 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAacHz23QHv-0poLvJ2:-MAacHz23QHv-0poLvJ3:b-vdednw) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L49)):*
> ```Go
> 	username     string
> }
> ```

I think it would be useful, both for the code clarity (using constants is a good thing tm) as well as documentation purposes, if you pulled
table creation queries into constants here
(payloadTableSchema, fileTableSchema). 
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAabNxl2vbhYQUDoRen:-MAabNxl2vbhYQUDoReo:b-esm1bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L64)):*
> ```Go
> 
> 	// Byte offset of the last file chunk, plus the size of the last file chunk
> 	// will give us the size of the whole file.
> ```

If i'm not mistaken, filenames are unique (per user) and those uploads happen under single txn.  So, why not just store the file size in the filename record itself?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAadBlV5cWIbC_7g0Y7:-MAadBlV5cWIbC_7g0Y8:b8tewgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L84)):*
> ```Go
> 	var files []string
> 	fileTableName := fileTableNamePrefix + f.username
> 	listFilesQuery := fmt.Sprintf(`SELECT filename FROM %s ORDER BY upload_time`, fileTableName)
> ```

shouldn't we be ordering by file name?  that's usually the expected default behavior?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAadtmm7LcW6r63XlXs:-MAadtmm7LcW6r63XlXt:bbafbz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L102)):*
> ```Go
> // DeleteAllFiles drops the user scoped tables effectively deleting the blobs
> // and metadata of every file.
> func (f *FileToTableSystem) DeleteAllFiles(ctx context.Context) error {
> ```

Just thinking out loud.  DeleteAllFiles sounds a bit ominous.  Should this be called DeleteAllUserFiles()?

Or perhaps FileToTableSystem could be renamed to UserFileToTableSystem?

Thinking a bit more about this operation, the actual object "*f" is no longer useable after a call to this utility function.
(f.DeleteAllFiles() followed by f.ListAllFiles() seems logical, but you wouldn't get a 0 as the result of list all files).

Perhaps make this function standalone one altogether? And/Or Call it something like
DestroyUserFileSystem(f) to make it clear that f is no longer valid after the call (or at least you have to recreate stuff)?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAagADPBYKvp4sJnypm:-MAagADPBYKvp4sJnypn:b2s6t3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L123)):*
> ```Go
> 	}
> 
> 	if err = txn.CommitOrCleanup(ctx); err != nil {
> ```

I'm not sure that's okay.  We do return errors above, but shouldn't we rollback txn?

I suspect you should probably just use 	f.db.Txn() function:
the entire body of this function becomes:

return f.db.Txn(ctx, 
  func(ctx context.Context, txn *kv.Txn) error {
     .. your code here minus the call to CommitOrCleanup -- db.Txn does that for you if you didn't return an error
  })

You probably would need to do the same in other places in this file.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAahZPT8MMNcKq0yPV7:-MAahZPT8MMNcKq0yPV8:b-dsbq7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L160)):*
> ```Go
> }
> 
> type payloadWriter struct {
> ```

I realize this is unexported, but a short comment would be useful.
Something like:
// payloadWriter is responsible for writing file data (payload) into user payload
// table.  It implements io.Writer interface.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAaiI3WEC2hXIgOx2BA:-MAaiI3WEC2hXIgOx2BB:b-wkifnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L190)):*
> ```Go
> }
> 
> type chunkWriter struct {
> ```

ditto here.  It would be useful to have a short comment on the purpose of this writer.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAalT5zASel3xfbxHFr:-MAalT5zASel3xfbxHFs:b-owd490) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L203)):*
> ```Go
> 
> func newChunkWriter(
> 	ctx context.Context, filename, username, database string, ie *sql.InternalExecutor, txn *kv.Txn,
> ```

I would definitely specify chunk size as an argument to this method, and rename chunkSize constant to something
like defaultChunkSize.

This makes it possible to create interesting tests (like: chunk size == 1, or 2, or 3) -- and verify what you write is correct.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAakViEC5I_QMgZqjMj:-MAakViEC5I_QMgZqjMk:bkk3fgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L226)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 		send := make([]byte, chunkSize)
> 		n, err := buf.Read(send)
> 		if n > 0 {
> 			written, err := w.writer.Write(send[:n])
> 			if err != nil {
> 				return byteOffset, err
> 			}
> 			byteOffset += written
> ```
</details>

I am a bit confused as to why we need this.

If you do not need to have a branch below (if err == io.EOF, ...), then all this Write method would need to is to take
the user supplied data (p), append it to a buffer of "chunkSize" bytes to the internal buffer, and then send it onward to 
payload writer.

I think what I'm missing is: why not change the chunkWriter to embed the Writer implementation directly:
type chunkedWriter {
   *Writer.  // NOTE: *Writer instead of "writer *Writer"
   // rest of your fields
}

Then, I think you can remove this Write() method entirely.  When user calls 
c.Write(buf), the write method you call will be called on the buffered writer you created in
newChunkedWriter.

Also, I think most of the other state in chunk writer can also be removed (because it's available in the payload writer anyway)
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAaivZCEN6JCu1BkJvV:-MAaivZCEN6JCu1BkJvW:b-75x6uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L230)):*
> ```
> 			// If no rows were previously inserted then we insert a row with an empty
> 			// payload.
> 			if byteOffset == 0 {
> ```
If I understand correctly, this branch exists because w [...]

2020-06-25 02:27 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAacHz23QHv-0poLvJ2:-MAbKT_n5v76QJBWIqFJ:b-21w2pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L49)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it would be useful, both for the code clarity (using constants is a good thing tm) as well as documentation purposes, if you pulled
table creation queries into constants here
(payloadTableSchema, fileTableSchema). 
</blockquote></details>

good idea, done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAabNxl2vbhYQUDoRen:-MAbkQ1f9AREHt1nZ48A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L64)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

If i'm not mistaken, filenames are unique (per user) and those uploads happen under single txn.  So, why not just store the file size in the filename record itself?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAadBlV5cWIbC_7g0Y7:-MAbKg5M7mYQ7WorWUfn:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L84)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

shouldn't we be ordering by file name?  that's usually the expected default behavior?
</blockquote></details>

done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAadtmm7LcW6r63XlXs:-MAbkNIh1ac5JxSRIrtO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L102)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just thinking out loud.  DeleteAllFiles sounds a bit ominous.  Should this be called DeleteAllUserFiles()?

Or perhaps FileToTableSystem could be renamed to UserFileToTableSystem?

Thinking a bit more about this operation, the actual object "*f" is no longer useable after a call to this utility function.
(f.DeleteAllFiles() followed by f.ListAllFiles() seems logical, but you wouldn't get a 0 as the result of list all files).

Perhaps make this function standalone one altogether? And/Or Call it something like
DestroyUserFileSystem(f) to make it clear that f is no longer valid after the call (or at least you have to recreate stuff)?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAagADPBYKvp4sJnypm:-MAbrn2N5TnN1Y5HoJ78:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L123)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure that's okay.  We do return errors above, but shouldn't we rollback txn?

I suspect you should probably just use 	f.db.Txn() function:
the entire body of this function becomes:

return f.db.Txn(ctx, 
  func(ctx context.Context, txn *kv.Txn) error {
     .. your code here minus the call to CommitOrCleanup -- db.Txn does that for you if you didn't return an error
  })

You probably would need to do the same in other places in this file.

</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAahZPT8MMNcKq0yPV7:-MAbL-1UEuPaPR4mYlWK:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L160)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I realize this is unexported, but a short comment would be useful.
Something like:
// payloadWriter is responsible for writing file data (payload) into user payload
// table.  It implements io.Writer interface.
</blockquote></details>

done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 190 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAaiI3WEC2hXIgOx2BA:-MAd4kur-21BwAlPpHc8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L190)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

ditto here.  It would be useful to have a short comment on the purpose of this writer.
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAalT5zASel3xfbxHFr:-MAbjekE4X-SIDtvPuYM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L203)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would definitely specify chunk size as an argument to this method, and rename chunkSize constant to something
like defaultChunkSize.

This makes it possible to create interesting tests (like: chunk size == 1, or 2, or 3) -- and verify what you write is correct.
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAakViEC5I_QMgZqjMj:-MAd41tN9UPBWt7TgjF3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.go#L226)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 		send := make([]byte, chunkSize)
> 		n, err := buf.Read(send)
> 		if n > 0 {
> 			written, err := w.writer.Write(send[:n])
> 			if err != nil {
> 				return byteOffset, err
> 			}
> 			byteOffset += written
> ```
I am a bit confused as to why we need this.

If you do not need to have a branch below (if err == io.EOF, ...), then all this Write method would need to is to take
the user supplied data (p), append it to a buffer of "chunkSize" bytes to the internal buffer, and then send it onward to 
payload writer.

I think what I'm missing is: why not change the chunkWriter to embed the Writer implementation directly:
type chunkedWriter {
   *Writer.  // NOTE: *Writer instead of "writer *Writer"
   // rest of your fields
}

Then, I think you can remove this Write() method entirely.  When user calls 
c.Write(buf), the write method you call will be called on the buffered writer you created in
newChunkedWriter.

Also, I think most of the other state in chunk writer can also be removed (because it's available in the payload writer anyway)
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 230 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAaivZCEN6JCu1BkJvV:-MAbtREP0-nyHSQ39iix:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acef9b86618602c7e94a74f69988fe19c919b01e/pkg/storage/cloud/filetable/file_table_read_writer.g [...]

2020-06-25 14:29 UTC, miretskiy requested changes
This is looking good!  Few more questions and mostly nits.  

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-:-MAfsTXXDWPAhy6PACTN:bu1zrsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfX3wk0SN3Yb16nP63:-MAfX3wk0SN3Yb16nP64:b-tasdef) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L52)):*
> ```
> file_size INT
> ```
 do we need default 0? or perhaps "not null"

Ditto for username: "not null"?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfW9z-62hfKEETeS7A:-MAfW9z-62hfKEETeS7B:b-8s1fb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L58)):*
> ```Go
> // of filename for every chunk at the KV level.
> const payloadTableSchema = `CREATE TABLE %s (filename STRING, byte_offset INT, 
> payload BYTES, PRIMARY KEY(filename, byte_offset)) INTERLEAVE IN PARENT %s(filename)`
> ```

just a nit:
Maybe wrap long create statement?
`CREATE TABLE %s (
  filename STRRING
 ...
`
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfWgNR4kfMWv0pcya2:-MAfWgNR4kfMWv0pcya3:b-jyhhqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L138)):*
> ```
> The FileToTableSystem 
> ```

The FileToTableSystem object...
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfWpnz7-c4Ud7u7NNc:-MAfWpnz7-c4Ud7u7NNd:bgpxmko) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L143)):*
> ```Go
> 		func(ctx context.Context, txn *kv.Txn) error {
> 			payloadTableName := payloadTableNamePrefix + f.username
> 			dropPayloadTableQuery := fmt.Sprintf(`DROP TABLE %s`, payloadTableName)
> ```

I assume we don't need to drop payload table because of interleaving?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfXWTTBUTvaS57PDm-:-MAfXWTTBUTvaS57PDm0:b-pyfbdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L173)):*
> ```Go
> 	if err := f.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		fileTableName := fileTableNamePrefix + f.username
> 		deleteFileQuery := fmt.Sprintf(`DELETE FROM %s WHERE filename='%s'`, fileTableName, filename)
> ```

I assume we don't need to delete payload chunks because of interleaving?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZ0kp0_-3Q3ozJvtP:-MAfZ0kp0_-3Q3ozJvtQ:b-tm0e0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L217)):*
> ```Go
> 	insertChunkQuery := fmt.Sprintf(`INSERT INTO %s VALUES ($1, $2, $3)`, payloadTableName)
> 	_, err := p.ie.QueryEx(p.ctx, "insert-file-chunk", p.txn,
> 		sqlbase.InternalExecutorSessionDataOverride{User: p.username, Database: p.database},
> ```

This is just a nit -- feel free to ignore.

This "incantation" is repeated in many places (including in chunkWriter).
Perhaps, the chunkWriter can have a member
  execAs sqlbase.InternalExecutorSessionDataOverride

which can be initialized to the above
We can then also have execAs in this struct as well.

Benefit: shorter lines, one place where the override initialized, and 1 fewer member of this struct.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZavF1VEVhSlFWdnt:-MAfZavG7WsMJ_PPC90o:ba197f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L233)):*
> ```Go
> // on to the underlying payloadWriter to be written to the Payload table.
> // On Close() chunkWriter inserts a file metadata entry in the File table once
> // all the chunks have been written.
> ```

love it :)
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZu_28vCkEBFwF8F3:-MAfZu_28vCkEBFwF8F4:boccic1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L282)):*
> ```Go
> 	// Commit the txn after all the payload bytes have been written and the
> 	// metadata entry has been inserted.
> 	return w.pw.txn.CommitOrCleanup(w.pw.ctx)
> ```

Very nice. (and a nice comment)
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAf_CRi6ngVXt85NYMW:-MAf_CRi6ngVXt85NYMX:bzfz66i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L312)):*
> ```Go
> 	payloadTableName := payloadTableNamePrefix + username
> 	query := fmt.Sprintf(`SELECT payload FROM %s WHERE filename='%s'`, payloadTableName, filename)
> 	log.Info(ctx, "DATABASE "+database)
> ```

drop this log message?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 340 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAf_j5-8i1zgMrepvdf:-MAf_j5-8i1zgMrepvdg:b-a5kdia) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L340)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	var reader io.ReadCloser
> 	var err error
> 	if reader, err = newFileReader(ctx, filename, f.username, f.databaseName, f.ie); err != nil {
> 		return nil, err
> 	}
> 	return reader, nil
> ```
</details>

I think you can just do
var reader, err := ...
return reader, err
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 470 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfb-uQ3ypgPXljJNlz:-MAfb-uQ3ypgPXljJNm-:b-oehsmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L470)):*
> ```Go
> 		return nil, err
> 	}
> 	if !tablesExist {
> ```

I think we have some checks in the wrong places.

I think the "check if payload tables exist" should happen in the NewFileToTableSystem() method.
That is: we check if the table(s) exist, and create them if they don't.

This method should not check for the existence of these tables
(because you can't get *f w/out the check).  If they tables are dropped, etc, we will get
SQL errors.

Another thing: the check for the file existence should happen under the same transaction as will be used to write this file.  That is, create txn earlier, check for file existence, and then return writer.

Yet another thing to consider: you might not need this check at all.  
But you simply cannot begin the same file upload concurrently
(thanks,  transactions). The second upload will run into primary key violations.
You will get a nicer error message (e.g., file exists vs "ERROR: duplicate key value (name)=('foo') violates unique constraint "primary", but even that's a marginal improvement.

 Even if you manage to create 2 writers u [...]

2020-06-26 03:32 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfX3wk0SN3Yb16nP63:-MAg6U_eDcbI9_P0khy5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L52)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> file_size INT
> ```
 do we need default 0? or perhaps "not null"

Ditto for username: "not null"?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfW9z-62hfKEETeS7A:-MAgNkeC7cFavfAGT7nf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L58)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

just a nit:
Maybe wrap long create statement?
`CREATE TABLE %s (
  filename STRRING
 ...
`
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 138 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfWgNR4kfMWv0pcya2:-MAg6tal5d7hK2pd1PZs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L138)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> The FileToTableSystem 
> ```

The FileToTableSystem object...
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfWpnz7-c4Ud7u7NNc:-MAicuxWEWd0-LmWRHGh:bpi5xro) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L143)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I assume we don't need to drop payload table because of interleaving?
</blockquote></details>

Please refer to the response below. If we had the FK reference from the child to the parent, then we would have to DROP the child before we could DROP the parent. Even though we can't enforce the FK because of the reason given below, we will still need to drop both the tables individually. I do not think dropping the parent, gets rid of the child as well.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfXWTTBUTvaS57PDm-:-MAgJFu4DsW1u_slxtfW:b-lpwz83) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L173)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I assume we don't need to delete payload chunks because of interleaving?
</blockquote></details>

Ideally yes. From what I can tell if we imposed an explicit FK reference on the Payload table. So something like:

```
CREATE TABLE %s (filename STRING, 
byte_offset INT, 
payload BYTES, 
PRIMARY KEY(filename, byte_offset), FOREIGN KEY (filename) REFERENCES File(filename) ON DELETE CASCADE) 
INTERLEAVE IN PARENT %s(filename)
```

Then a deletion of a row in FileTable would cascade to the child. Unfortunately, because we insert to the Payload before we insert into File (the metadata), we would violate the FK reference.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZ0kp0_-3Q3ozJvtP:-MAib_qa0vn_RrQXsAqE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L217)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is just a nit -- feel free to ignore.

This "incantation" is repeated in many places (including in chunkWriter).
Perhaps, the chunkWriter can have a member
  execAs sqlbase.InternalExecutorSessionDataOverride

which can be initialized to the above
We can then also have execAs in this struct as well.

Benefit: shorter lines, one place where the override initialized, and 1 fewer member of this struct.
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 233 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZavF1VEVhSlFWdnt:-MAgKEFdDusGjdWnJijW:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L233)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

love it :)
</blockquote></details>

thanks!
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 282 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfZu_28vCkEBFwF8F3:-MAgKFfF6FRCoCXLXuc6:bsv417h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L282)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Very nice. (and a nice comment)
</blockquote></details>

thank you!
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAf_CRi6ngVXt85NYMW:-MAgKLi001QjYK09CaW9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L312)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

drop this log message?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 340 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAf_j5-8i1zgMrepvdf:-MAgKY0j9edCyTkiGf2C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L340)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	var reader io.ReadCloser
> 	var err error
> 	if reader, err = newFileReader(ctx, filename, f.username, f.databaseName, f.ie); err != nil {
> 		return nil, err
> 	}
> 	return reader, nil
> ```
I think you can just do
var reader, err := ...
return reader, err
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 470 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfb-uQ3ypgPXljJNlz:-MAgNHuJ6By4OFrgZhum:bb02wxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L470)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think we have some checks in the wrong places.

I think the "check if payload tables exist" should happen in the NewFileToTableSystem() method.
That is: we check if the table(s) exist, and create them if they don't.

This method should not check for the existence of these tables
(because you can't get *f w/out the check).  If they tables are dropped, etc, we will get
SQL errors.

Another thing: the check for the file existence should happen under the same transaction as will be used to write this file.  That is, create txn earlier, check for file existence, and then return writer.

Yet  [...]

2020-06-26 14:46 UTC, miretskiy requested changes
This is looking very good.  

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-:-MAl5-py6Up7c9LzwSYz:b-td6bhf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfXWTTBUTvaS57PDm-:-MAl0V8z0Wk9ZMALaeib:b-2hypon) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L173)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Ideally yes. From what I can tell if we imposed an explicit FK reference on the Payload table. So something like:

```
CREATE TABLE %s (filename STRING, 
byte_offset INT, 
payload BYTES, 
PRIMARY KEY(filename, byte_offset), FOREIGN KEY (filename) REFERENCES File(filename) ON DELETE CASCADE) 
INTERLEAVE IN PARENT %s(filename)
```

Then a deletion of a row in FileTable would cascade to the child. Unfortunately, because we insert to the Payload before we insert into File (the metadata), we would violate the FK reference.
</blockquote></details>

Hmm.. I do not see the deletion from the payload table... Am I missing something?
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 470 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfb-uQ3ypgPXljJNlz:-MAl28b060mXa90oAyUN:b-ysr7xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L470)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

moved the table existence check.
good point about concurrent/serial attempts to write a file with the same name failing with PK violation. Removed the file existence check. NewFileWriter() is down to a single line :smiley: 
</blockquote></details>

Just like we like it.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 245 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl0wyK2mtxk4q3yF7K:-MAl0wyK2mtxk4q3yF7L:b4og95b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L245)):*
> ```Go
> 	pw                      *payloadWriter
> 	execSessionDataOverride sqlbase.InternalExecutorSessionDataOverride
> 	chunkSize               int
> ```

do we need this member?  (buf.Cap() should be our chunkSize?)
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl1FkO9TZ_9qvTwp9G:-MAl1FkO9TZ_9qvTwp9H:b-i1fwb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L264)):*
> ```Go
> 	bytesBuffer := bytes.NewBuffer(buf)
> 	// On creation bytesBuffer.Len() returns chunkSize. We reset it to 0 to allow
> 	// for accurate accounting when buffering/writing in Write().
> ```

You can probably do away with this comment and a reset below by
initializing `buf := make([]byte, 0, chunkSize)`
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 310 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl1ZHEAAn-Lct9Evl4:-MAl1ZHEAAn-Lct9Evl5:bv7gi73) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L310)):*
I'm pretty sure it's wrong.  byteOffset keeps increasing all the time.
Write(1MB), Write(1MB), etc... 
(something tells me you should add a test that issues few writes, each one
> chunkSize)

You certainly don't want to be returning byteoffset.
You simply want to save the length of the buffer at the start of this function, and return that instead.
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfqYl7D0QWaTuENG7l:-MAl4XzX7cq5mgFxeJLm:b81hcwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L234)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

not sure what you mean here. I'm using our helper to test the existence of the user's DROP privilege.
</blockquote></details>

Ahh... I thought you had helper that checked if there are sufficient privs. my bad.

I think it would make sense to check (via show grants perhaps) that the grant given to the user when the fileTableSystem was created, no longer exist.
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl2gqn0WHl4vq39AhN:-MAl2gqn0WHl4vq39AhO:by3zr3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L56)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	err = writer.Close()
> 	if err != nil {
> 		return nil, err
> 	}
> ```
</details>


I think this is a bit of an (unfortunate) anti-pattern in go.
There are so many places where people write `defer w.Close()`, ignoring the errors.
Bad thing (tm), for sure, but we should not make it easy for our users to make this mistake.
(discussed options in person).
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl47YKAB9ciCcJlBny:-MAl47YL0K-VJ0Sew0tG:b-fwfsy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L75)):*
> ```Go
> 		payloadTableName, filename)).Scan(&count)
> 	require.NoError(t, err)
> 	return count == expectedNumChunks
> ```

maybe don't even return a bool, but `require.Equal(t, exepctedNumChunks, count)`


<!-- Sent from Reviewable.io -->

2020-06-26 16:17 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfXWTTBUTvaS57PDm-:-MAlCDTZ88Vsj580zNqk:byqjm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L173)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Hmm.. I do not see the deletion from the payload table... Am I missing something?
</blockquote></details>

huh, I see it below your comment. I delete from payload after I delete from File. Since there is no FK reference this is fine I believe.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 245 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl0wyK2mtxk4q3yF7K:-MAlE5VB6npMQXopxtbH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L245)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we need this member?  (buf.Cap() should be our chunkSize?)
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl1FkO9TZ_9qvTwp9G:-MAlE6AY4IRsn47SqwSp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L264)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

You can probably do away with this comment and a reset below by
initializing `buf := make([]byte, 0, chunkSize)`
</blockquote></details>

Done.
___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 310 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl1ZHEAAn-Lct9Evl4:-MAlF0iU95B93nrsIgbp:b-tqfjxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer.go#L310)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm pretty sure it's wrong.  byteOffset keeps increasing all the time.
Write(1MB), Write(1MB), etc... 
(something tells me you should add a test that issues few writes, each one
> chunkSize)

You certainly don't want to be returning byteoffset.
You simply want to save the length of the buffer at the start of this function, and return that instead.
</blockquote></details>

good catch added a test which reuses the same writer too.
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 234 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfqYl7D0QWaTuENG7l:-MAlP_uNDcBB5aRSE_Or:b-nnjxfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L234)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ahh... I thought you had helper that checked if there are sufficient privs. my bad.

I think it would make sense to check (via show grants perhaps) that the grant given to the user when the fileTableSystem was created, no longer exist.
</blockquote></details>

Done. Checking for grantees on the tables will return an error as the tables have been dropped. The grants were only given on the table so this should be sufficient?
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl2gqn0WHl4vq39AhN:-MAlCcenDWMiBdiRFpjh:b1ji4bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L56)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	err = writer.Close()
> 	if err != nil {
> 		return nil, err
> 	}
> ```

I think this is a bit of an (unfortunate) anti-pattern in go.
There are so many places where people write `defer w.Close()`, ignoring the errors.
Bad thing (tm), for sure, but we should not make it easy for our users to make this mistake.
(discussed options in person).
</blockquote></details>

As discussed offline, a stronger worded Close() comment has been added.
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAl47YKAB9ciCcJlBny:-MAlDbDf4SVFWD3xptHm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d20d793bafe3454339c83bebbf4e60fead5e8a2/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L75)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe don't even return a bool, but `require.Equal(t, exepctedNumChunks, count)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-06-26 16:51 UTC, miretskiy approved these changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50493)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/filetable/file_table_read_writer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAfXWTTBUTvaS57PDm-:-MAlX3hT5cETLH-D8oXk:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d14bf5d76bfb4f11fe8ecd7e0ad5603b346c731d/pkg/storage/cloud/filetable/file_table_read_writer.go#L173)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

huh, I see it below your comment. I delete from payload after I delete from File. Since there is no FK reference this is fine I believe.
</blockquote></details>

done
___
*[pkg/storage/cloud/filetable/file_table_read_writer_test.go, line 228 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50493#-MAlXScY3cd67yY8dKO9:-MAlXScY3cd67yY8dKOA:bcf2h3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79cdf720b6bdf7a8c605efc15ecaa14cecf37b6/pkg/storage/cloud/filetable/file_table_read_writer_test.go#L228)):*
> ```
> "reuse-writer-multiple-writes"
> ```
you're not actually reusing writer..
perhaps 'call-write-many-times'


<!-- Sent from Reviewable.io -->

2020-06-26 18:37 UTC, adityamaru commented
TFTR!

bors r=miretskiy

2020-06-26 19:20 UTC, merged