sql: ensure columns get dequalified for ALTER TABLE statements.
cockroachdb/cockroach pull request #50582
Opened 2020-06-23 22:12 UTC by RichardJCai

Notably alter table add column with a computed expr and alter column type using.

Moved the DequalifyColumnRefs call into ReplaceColumnVarsAndSanitizeExpr since
ReplaceColumnVarsAndSanitizeExpr is called to sanitize the expression in
all these cases.

Fixes #50069

Release note (bug fix): Previously performing ALTER TABLE ADD COLUMN with a computed
expression allowed you to provide a column in a different table or database if the column name
was the same. Similarly you could provide an expression referring to another table's
column when executing ALTER COLUMN TYPE USING EXPRESSION. This is no longer the case,
all columns must refer to the column in the table you're altering.

2020-06-23 22:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50582)
<!-- Reviewable:end -->

2020-06-24 00:38 UTC, mgartner requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

___
*[pkg/sql/create_table.go, line 1677 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYhRZ60id_Ruu3qB6m:-MAYhRZ77O4KJ-a4jDnr:b-2mjphe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/create_table.go#L1677)):*
> ```Go
> 		case *tree.ColumnTableDef:
> 			if d.IsComputed() {
> 				if err := computedColValidator.Validate(d, n.Table); err != nil {
> ```

The table name remains the same each time `Validate` is called within this context, so you could pass `n.Table` to the constructor, `NewComputedColumnValidator` instead.
___
*[pkg/sql/schemaexpr/column.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYiLun-P58v6RO1CiY:-MAYiLun-P58v6RO1CiZ:b-dznkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/schemaexpr/column.go#L290)):*
> ```Go
> // expression is valid, has the correct type and contains no variable
> // expressions. It returns the type-checked and constant-folded expression.
> func ReplaceColumnVarsAndSanitizeExpr(
> ```

The name of this function no longer makes a ton of sense. This function is now responsible for 1) dequalifying column references, 2) validating the result type of the expression, 3) validating that there are no impure functions if `allowImpure` is false. This function also seems to operate more on an expression-level, than a column-level.

What do you think about renaming this function, rewriting the doc to explain the 3 things above [I don't think the dummyColumn bit is necessary to document here, since the caller doesn't necessarily care _how_ it validates the type, just that it does], and moving to a new file like `schemaexpr/expr.go`? Ideally we add unit tests for this function as well, but we can always follow up that later, given this function is already not unit tested.
___
*[pkg/sql/schemaexpr/column.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYjDQS3htMJurVd0i7:-MAYjDQS3htMJurVd0i8:b-pnrj78) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/schemaexpr/column.go#L294)):*
> ```Go
> 	desc sqlbase.TableDescriptorInterface,
> 	expr tree.Expr,
> 	types *types.T,
> ```

Obviously not part of your PR, but`types` is confusing given the package with the same name and because this is a single type, not multiple. What do you think about renaming this to `typ`, a name I've seen used in a lot of other places for a `*types.T`.


<!-- Sent from Reviewable.io -->

2020-06-24 01:01 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RichardJCai)

___
*[pkg/sql/alter_column_type.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYp_PJ4ZHpCqTSrqKH:-MAYp_PJ4ZHpCqTSrqKI:b-vij77d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/alter_column_type.go#L61)):*
> ```Go
> 	params runParams,
> 	cmds tree.AlterTableCmds,
> 	tn tree.TableName,
> ```

Do we need to pass this by value?
___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAYphz5D-RgRdRrWKAa:b-tseqpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
> ```
> CREATE TABLE t50069_b (x INT);
> 
> statement error pq: no data source matches prefix: t50069b
> ```

This error doesn't seem right though: the data source t50069 does exist, we just can't access it in this context.
___
*[pkg/sql/schemaexpr/column.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYjDQS3htMJurVd0i7:-MAYpv234k9HV3l3vcwy:bhtb6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/schemaexpr/column.go#L294)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Obviously not part of your PR, but`types` is confusing given the package with the same name and because this is a single type, not multiple. What do you think about renaming this to `typ`, a name I've seen used in a lot of other places for a `*types.T`.
</blockquote></details>

yeah we want to avoid aliasing the package name


<!-- Sent from Reviewable.io -->

2020-06-24 16:43 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rohany)

___
*[pkg/sql/alter_column_type.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYp_PJ4ZHpCqTSrqKH:-MAasE3K3VXShptqSvFE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/alter_column_type.go#L61)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Do we need to pass this by value?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAant67Es66RqEpZ7HU:b-b78rck) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

This error doesn't seem right though: the data source t50069 does exist, we just can't access it in this context.
</blockquote></details>

I appended "in this context" I think that makes sense here.
___
*[pkg/sql/schemaexpr/column.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYiLun-P58v6RO1CiY:-MAaqPD-8BJfDA1LXbNH:b8eg5li) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/schemaexpr/column.go#L290)):*
> What do you think about renaming this function, rewriting the doc to explain the 3 things above [I don't think the dummyColumn bit is necessary to document here, since the caller doesn't necessarily care how it validates the type, just that it does], and moving to a new file like schemaexpr/expr.go? Ideally we add unit tests for this function as well, but we can always follow up that later, given this function is already not unit tested.

I created schemaexpr/expr.go and moved the function into it.
What do you think of just ValidateExpr?


<!-- Sent from Reviewable.io -->

2020-06-24 16:44 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rohany)

___
*[pkg/sql/schemaexpr/column.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYiLun-P58v6RO1CiY:-MAbCdDO1vevqwBgG6T6:bced33o) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/schemaexpr/column.go#L290)):*
> unit test
I went ahead and added unit tests by copying the one you made for partial indexes. I moved the dequalify columns logic for the partial index validator tests into the ValidateExpr test.


<!-- Sent from Reviewable.io -->

2020-06-24 17:22 UTC, mgartner requested changes
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAbHvK1E78j9fyRrMrE:bwv0h5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I appended "in this context" I think that makes sense here.
</blockquote></details>

I looked at the Postgres error to draw inspiration from, but it's worse:
```
ERROR:  42P01: missing FROM-clause entry for table "t50069b"
```
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAbK7ib2x5FJ_i2ZiTE:blf00xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
> ```
> t6  CREATE TABLE t6 (
>     a INT8 NULL,
>     INDEX t6_a_idx (a ASC) WHERE a > 0:::INT8,
> ```

@raduberinde Do we want type annotations to be added to partial index predicates, like this? The downside I see is that it clutters the expression a bit.

We currently add type annotations to `CHECK` constraints, so maybe consistency with that is a good thing.
___
*[pkg/sql/schemaexpr/expr.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbInfk6RBZNhpaOwKf:-MAbInfk6RBZNhpaOwKg:bqz2tcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L52)):*
> ```Go
> }
> 
> // ValidateExpr takes an expr de-qualifies the column names and validates that
> ```

What about DequalifyAndValidateExpr?

"DequalifyAndValidateEpr dequalifies the column names of the given expression and valiates that..."
___
*[pkg/sql/schemaexpr/expr.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbJBrt16-QLnWyezdP:-MAbJBrt16-QLnWyezdQ:b-kgb1x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L53)):*
> ```
> contains no variable expressions
> ```

Aren't variable expressions allowed?
___
*[pkg/sql/schemaexpr/partial_index_test.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbKiaf0gKBaHsqCdNJ:-MAbKiaf0gKBaHsqCdNK:b-umm1ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fadb7dd88addaea0d7677aabd3f45b71cf7fbb/pkg/sql/schemaexpr/partial_index_test.go#L83)):*
> ```Go
> 		{"bar.b = 0", true, "b = 0"},
> 		{"foo.bar.b = 0", true, "b = 0"},
> 		{"bar.a AND foo.bar.b = 0", true, "a AND (b = 0)"},
> ```

[nit] It doesn't hurt to leave these IMO. Even though it duplicates the test cases for `ValidateExpr`, my justification for leaving these is that if someone comes along and rewrites `Validate` so that it doesn't use `ValidateExpr`, they could end up breaking it with out breaking these tests.


<!-- Sent from Reviewable.io -->

2020-06-24 17:26 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, @RichardJCai, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAbLxIf0-UpTq_PqDaP:b6ltdil) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I looked at the Postgres error to draw inspiration from, but it's worse:
```
ERROR:  42P01: missing FROM-clause entry for table "t50069b"
```
</blockquote></details>

I don't know if we need to match the message exactly, but we should match the code at least.
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAbM1IjAMxkqDGPY0Y4:b6mqxmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

@raduberinde Do we want type annotations to be added to partial index predicates, like this? The downside I see is that it clutters the expression a bit.

We currently add type annotations to `CHECK` constraints, so maybe consistency with that is a good thing.
</blockquote></details>

We need the type annotations to be part of the serialized expression. However, it's not difficult to remove the annotations when displaying them in `SHOW CREATE`.
___
*[pkg/sql/schemaexpr/expr.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbInfk6RBZNhpaOwKf:-MAbMMea3g9JSaD1-AqD:b-dwklxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What about DequalifyAndValidateExpr?

"DequalifyAndValidateEpr dequalifies the column names of the given expression and valiates that..."
</blockquote></details>

`DequalifyAndValidateTableDescExpr`?


<!-- Sent from Reviewable.io -->

2020-06-24 17:47 UTC, mgartner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde, @RichardJCai, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAbP9mS2jjZ8Uer4HHz:bsdtovd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I don't know if we need to match the message exactly, but we should match the code at least.
</blockquote></details>

I ran into this with partial indexes too: https://github.com/cockroachdb/cockroach/blob/96db1b332ddd6e804285a2ed42bf8a2b7c18c1e3/pkg/sql/logictest/testdata/logic_test/partial_index#L28

I don't remember exactly why I left as a TODO, but I think we'd have to catch and rethrow the correct error or do some more serious plumbing work, becuase `SanitizeVarFreeExpr` errors with codes that I think are needed in other uses.
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAbPyESCHd5aHfDnOza:b-x0t7xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
> We need the type annotations to be part of the serialized expression.

Oh interesting, why is that?

> However, it's not difficult to remove the annotations when displaying them in SHOW CREATE.

We should probably stay consistent with `CHECK` constraints, but maybe we want to remove them from those expressions as well?
___
*[pkg/sql/schemaexpr/expr.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbInfk6RBZNhpaOwKf:-MAbQH2W-Jr8T4Pd32wI:b-vgt5dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L52)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

`DequalifyAndValidateTableDescExpr`?
</blockquote></details>

Hmm. `TableDesc` seems redundant in the context of the `schemaexpr` package, but I don't feel strongly. But now you've got me wondering whether `tabledescexpr` would have been a better package name...


<!-- Sent from Reviewable.io -->

2020-06-24 17:53 UTC, rohany reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde, @RichardJCai, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAbSRDh-isFjUbQ6Y2Z:bp6oehe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> We need the type annotations to be part of the serialized expression.

Oh interesting, why is that?

> However, it's not difficult to remove the annotations when displaying them in SHOW CREATE.

We should probably stay consistent with `CHECK` constraints, but maybe we want to remove them from those expressions as well?
</blockquote></details>

We need to annotate constants that whose types are ambiguous when formatted so that we ensure the same types are inferred again when processing the expression later. It's very important for user defined types at least that the annotation is present (less so for integers).


<!-- Sent from Reviewable.io -->

2020-06-24 21:47 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/alter_column_type, line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAYphz5D-RgRdRrWKA_:-MAcGYuo-zRDWNSbgUim:bg2kjop) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f08814784987b1d774ec79a76c384d0d0d98351/pkg/sql/logictest/testdata/logic_test/alter_column_type#L557)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I ran into this with partial indexes too: https://github.com/cockroachdb/cockroach/blob/96db1b332ddd6e804285a2ed42bf8a2b7c18c1e3/pkg/sql/logictest/testdata/logic_test/partial_index#L28

I don't remember exactly why I left as a TODO, but I think we'd have to catch and rethrow the correct error or do some more serious plumbing work, becuase `SanitizeVarFreeExpr` errors with codes that I think are needed in other uses.
</blockquote></details>

It does seem to return the right code for the alter table add computed column and alter column type
root@127.0.0.1:60093/movr> alter table t add column z int as (t2.x + 1) stored;
ERROR: no data source matches prefix: t2 in this context
SQLSTATE: 42P01
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAcGp9iCEFkgp1iPdP4:b-n7cz5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

We need to annotate constants that whose types are ambiguous when formatted so that we ensure the same types are inferred again when processing the expression later. It's very important for user defined types at least that the annotation is present (less so for integers).
</blockquote></details>

Should I remove the annotations from SHOW CREATE in this PR?
___
*[pkg/sql/schemaexpr/expr.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbInfk6RBZNhpaOwKf:-MAcHcp1BLctzcJjG761:b-k5ksi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm. `TableDesc` seems redundant in the context of the `schemaexpr` package, but I don't feel strongly. But now you've got me wondering whether `tabledescexpr` would have been a better package name...
</blockquote></details>

I'm leaning towards leaving the TableDesc out since it does seem somewhat redundant in the package and makes the function name a little long.
___
*[pkg/sql/schemaexpr/expr.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbJBrt16-QLnWyezdP:-MAcHMLF5u12IlpKRcKK:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/schemaexpr/expr.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

> ```
> contains no variable expressions
> ```

Aren't variable expressions allowed?
</blockquote></details>

Updated.
___
*[pkg/sql/schemaexpr/partial_index_test.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbKiaf0gKBaHsqCdNJ:-MAcHWdN62g5_TAcyNgl:b-iwda8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7fadb7dd88addaea0d7677aabd3f45b71cf7fbb/pkg/sql/schemaexpr/partial_index_test.go#L83)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] It doesn't hurt to leave these IMO. Even though it duplicates the test cases for `ValidateExpr`, my justification for leaving these is that if someone comes along and rewrites `Validate` so that it doesn't use `ValidateExpr`, they could end up breaking it with out breaking these tests.
</blockquote></details>

Added back


<!-- Sent from Reviewable.io -->

2020-06-25 16:36 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-:-MAgKWda19wPSwAbXXOH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50582#-MAbK7ib2x5FJ_i2ZiTD:-MAgKOjI4rqkEu-zrZP3:bk9j4et) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff69eb7fea6f29c3ce3d4620406072427bcd52c8/pkg/sql/logictest/testdata/logic_test/partial_index#L116)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Should I remove the annotations from SHOW CREATE in this PR?
</blockquote></details>

No don't worry about that for this PR. I'll make a note to ask around and see if we want to change that behavior.


<!-- Sent from Reviewable.io -->

2020-06-25 18:50 UTC, RichardJCai commented
Thanks for the reviews!

2020-06-25 18:50 UTC, RichardJCai commented
bors r=mgartner

2020-06-25 20:05 UTC, merged