colexec: add benchmark of hash aggregator against wrapped processor
cockroachdb/cockroach pull request #50737
Opened 2020-06-27 23:24 UTC by yuzefovich

The benchmark shows that it is actually faster to use the wrapped
aggregator processor with the group sizes up to 64 elements or so.

Release note: None

2020-06-27 23:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50737)
<!-- Reviewable:end -->

2020-06-27 23:28 UTC, yuzefovich commented
The result of running this new benchmark and comparing against a branch with the materializer change is [here](https://gist.github.com/yuzefovich/301bc59684d799daf9f654cd0933864a). The results show that it is beneficial to wrap the aggregator processor into the vectorized flow until we reach the group size of 64 or so. I thought it was an interesting observation, but it also explains why I was seeing slower query performance (in some cases) with added support for DISTINCT aggregation.

2020-06-30 09:39 UTC, asubiotto requested changes
The benchmarks reference a materializer change, am I missing something?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-:-MB3_U7n2r72mRSWuvTF:b-26es6j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-MB3_u471ftZG5RiRk2P:-MB3_u471ftZG5RiRk2Q:bj20420) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b917c2fe1c031a4fb694e3e98885add6ac34498/pkg/sql/colexec/colbuilder/execplan.go#L159)):*
> ```Go
> 
> 	case core.Aggregator != nil:
> 		if mustWrapCore != nil && mustWrapCore.Aggregator != nil {
> ```

Does it make sense to plumb this into `isSupported`? I would expect the caller to just check if `mustWrapCore` and not bother with an `isSupported` call if so.


<!-- Sent from Reviewable.io -->

2020-06-30 15:22 UTC, yuzefovich reviewed
"Materializer change" is #50725. I was curious to see what the impact that change has, so I cherry-picked and ran with scripts/bench. As we can see, in "wrapped" case the materializer change gives us 5-10% improvement. However, if you want to look at the absolute numbers of running the newly added benchmark, only look at the "old" column.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-:-MB4mIt246anLX5igjOB:bdpsrpx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-MB3_u471ftZG5RiRk2P:-MB4myxu86xkt1kHJvIc:bdrornd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b917c2fe1c031a4fb694e3e98885add6ac34498/pkg/sql/colexec/colbuilder/execplan.go#L159)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does it make sense to plumb this into `isSupported`? I would expect the caller to just check if `mustWrapCore` and not bother with an `isSupported` call if so.
</blockquote></details>

I want this `MustWrapCore` mechanism to be general in a sense that it would give us an ability to force wrapping of all kinds of cores (i.e. aggregators, sorters, joiners, etc). This desire forces us to use `execinfrapb.ProcessorCoreUnion` which can have any of the cores set to non-nil. And in order to check when `mustWrapCore != nil` that `spec` contains exactly the kind of the core that must be wrapped, we need to have a switch on `mustWrapCore` similar to what we have on `spec.Core`. Basically, we would need to have something like
```
switch {
  case spec.Core.Noop != nil && mustWrapCore.Noop != nil:
    return "must be wrapped"
  case spec.Core.Values != nil && mustWrapCore.Values != nil:
    return "must be wrapped"
  ...
}
```
Instead of having that, we can adjust `isSupported` check to do that as this PR does.


<!-- Sent from Reviewable.io -->

2020-07-01 13:54 UTC, asubiotto reviewed
What's the justification to merge this benchmark into master? I think it's a good datapoint but I'm not convinced yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-:-MB9bchS5oNJcp2oYB4o:bi8274n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-MB3_u471ftZG5RiRk2P:-MB9dxie-2HgUyZKbSBl:b-9ll5c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b917c2fe1c031a4fb694e3e98885add6ac34498/pkg/sql/colexec/colbuilder/execplan.go#L159)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I want this `MustWrapCore` mechanism to be general in a sense that it would give us an ability to force wrapping of all kinds of cores (i.e. aggregators, sorters, joiners, etc). This desire forces us to use `execinfrapb.ProcessorCoreUnion` which can have any of the cores set to non-nil. And in order to check when `mustWrapCore != nil` that `spec` contains exactly the kind of the core that must be wrapped, we need to have a switch on `mustWrapCore` similar to what we have on `spec.Core`. Basically, we would need to have something like
```
switch {
  case spec.Core.Noop != nil && mustWrapCore.Noop != nil:
    return "must be wrapped"
  case spec.Core.Values != nil && mustWrapCore.Values != nil:
    return "must be wrapped"
  ...
}
```
Instead of having that, we can adjust `isSupported` check to do that as this PR does.
</blockquote></details>

But isn't that switch pretty much what you're doing here? It just seems confusing to me. What about if you had a map of processor indices and if the processor index exists in that map, it must be wrapped.


<!-- Sent from Reviewable.io -->

2020-07-01 14:31 UTC, yuzefovich reviewed
I guess I thought we should measure relative performance of most interesting processor cores when those are wrapped against the equivalent vectorized operators, but I do agree that those benchmarks would be unactionable. Maybe in the future, once the optimizer knows about the vectorization, it will make sense to include an ability to force wrapping of a processor core into the vectorized flow depending on estimations of some parameters (e.g. for hash aggregator it's the group size), but it is pretty far-fetched at this point. I'll close this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-:-MB9lddF4xkgk6mWdvGf:b-7zfif0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50737#-MB3_u471ftZG5RiRk2P:-MB9lZbj8kZ3XBo4KZxd:b7vsu4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b917c2fe1c031a4fb694e3e98885add6ac34498/pkg/sql/colexec/colbuilder/execplan.go#L159)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But isn't that switch pretty much what you're doing here? It just seems confusing to me. What about if you had a map of processor indices and if the processor index exists in that map, it must be wrapped.
</blockquote></details>

Hm, fair point.


<!-- Sent from Reviewable.io -->

2020-07-01 14:31 UTC, closed without merging