sql: some changes around experimental distsql planning
cockroachdb/cockroach pull request #50903
Opened 2020-07-01 20:54 UTC by yuzefovich

**sql: change experimental_distsql_planning=always behavior**

Previously, `experimental_distsql_planning=always` setting would result
in an error for an unsupported query only when that query had a SELECT
statement tag. This might be confusing, and this commit changes the
behavior to return an error for all queries except for SET statements
(since we need to be able to change the setting from always).

Release note: None

**sql: introduce testing setting to disable partially distributed plans**

This commit adds a cluster setting
`sql.testing.partially_distributed_plans.enabled` that controls whether
the creation of partially distributed plans is allowed (such plans can
be produced by the new factory). By default it is set to `true` and
should be used only in tests when comparing the physical plans produced
by the old factory + distsql physical planner against the plans produced
by the new factory. I chose not to add a session variable because
I think we will want to use this knob on the whole testing cluster.
Also, I think that this knob will be removed when we are removing the
old factory, so there is no release note (at the moment, I think of this
setting as specifically a testing knob).

Release note: None

2020-07-01 20:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/50903)
<!-- Reviewable:end -->

2020-07-06 10:19 UTC, asubiotto requested changes
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/exec_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYZxTR0JgjT0-mfMUg:-MBYZxTR0JgjT0-mfMUh:b7aq6bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/exec_util.go#L272)):*
> ```Go
> // TODO(yuzefovich): remove this setting when deleting old sql.execFactory.
> var partiallyDistributedPlansEnabled = settings.RegisterBoolSetting(
> 	"sql.testing.partially_distributed_plans.enabled",
> ```

Since this should only affect the gateway, why wouldn't it be a session setting? Do you envision that multiple sessions would want to observe this?
___
*[pkg/sql/plan.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBY_ppZ2ye3RD9JHDCy:-MBY_ppZ2ye3RD9JHDCz:bxsojp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/plan.go#L359)):*
> ```Go
> 			return n.plan.main.physPlan.Distribution == physicalplan.PartiallyDistributedPlan
> 		}
> 	case *explainDistSQLNode:
> ```

You can probably merge this with the previous case:
```
case *explainPlanNode, *explainDistSQLNode:
```
And it might be nice to have this switch statement set a `distribution` variable which you then use at the end, rather than having multiple return statements.
___
*[pkg/sql/plan_opt.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYaO8n1Os6l-Y1hCgN:-MBYaO8n1Os6l-Y1hCgO:b-7gyhmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/plan_opt.go#L210)):*
> ```Go
> 		if err == nil {
> 			m := plan.(*planTop).main
> 			fallbackToOldFactory = m.isPartiallyDistributed() && !partiallyDistributedPlansEnabled.Get(&p.execCfg.Settings.SV)
> ```

I assumed that the effect of the cluster setting would be to again produce a plan with the new factory but not distributing. The current solution would decrease the test coverage by not testing these fallback cases. Maybe it doesn't matter much since these partial distribution cases are rare? What do you think?
___
*[pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYYgB1ARFqzoHXZtSg:-MBYYgB24l561kHrhWGN:b1f8jun) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f1f0563d814cbfad20650a3c121943387f880a/pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning#L1)):*
> ```
> # NOTE: all queries in this file should run with 'experimental_distsql_planning'
> ```

Should we run with an explicit config to avoid running the same test multiple times?


<!-- Sent from Reviewable.io -->

2020-07-06 17:34 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50903)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYZxTR0JgjT0-mfMUg:-MB_B5Jq5qe0QZnVTngj:bethj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/exec_util.go#L272)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since this should only affect the gateway, why wouldn't it be a session setting? Do you envision that multiple sessions would want to observe this?
</blockquote></details>

Made it a session variable. TBH I don't think it's important to make this distinction since this is a temporary testing knob, and initially I chose the cluster setting "route" because it adds less code (I guess), no good reason.
___
*[pkg/sql/plan.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBY_ppZ2ye3RD9JHDCy:-MB_21c26VqyYtbeEfgj:bkg4eiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/plan.go#L359)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

You can probably merge this with the previous case:
```
case *explainPlanNode, *explainDistSQLNode:
```
And it might be nice to have this switch statement set a `distribution` variable which you then use at the end, rather than having multiple return statements.
</blockquote></details>

I don't think I can merge the two cases because it's a type switch, so a single concrete type must be specified. If I merge them, then `n` is of `planNode` type and I cannot access `.plan` attribute.

Added the local variable.
___
*[pkg/sql/plan_opt.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYaO8n1Os6l-Y1hCgN:-MB_67bS3OIr9SyZETtw:bc5nu8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/plan_opt.go#L210)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I assumed that the effect of the cluster setting would be to again produce a plan with the new factory but not distributing. The current solution would decrease the test coverage by not testing these fallback cases. Maybe it doesn't matter much since these partial distribution cases are rare? What do you think?
</blockquote></details>

Hm, good point. It's not an invasive change, so implemented your suggestion.
___
*[pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYYgB1ARFqzoHXZtSg:-MB_1BS82GEnn_aldhaA:b6c90dg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1f1f0563d814cbfad20650a3c121943387f880a/pkg/sql/logictest/testdata/logic_test/experimental_distsql_planning#L1)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we run with an explicit config to avoid running the same test multiple times?
</blockquote></details>

Hm, I started typing out the configs that we should include here and got
```
# LogicTest: local local-vec-off fakedist fakedist-vec-off fakedist-disk 3node-tenant
```
so it's a half of all `defaultConfigs`. At this point given that this test file is not that long and not that long-running (e.g. in comparison to schema changes one), I think it's cleaner to just use the default configs.


<!-- Sent from Reviewable.io -->

2020-07-07 09:26 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-:-MBcaClH-69CnRnmhBo0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/exec_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYZxTR0JgjT0-mfMUg:-MBc_DcF827vfy7PnEO_:btm2260) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/exec_util.go#L272)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Made it a session variable. TBH I don't think it's important to make this distinction since this is a temporary testing knob, and initially I chose the cluster setting "route" because it adds less code (I guess), no good reason.
</blockquote></details>

Agreed. I think a session setting is better for this if we don't need a cluster setting because they seem more ephemeral (not persisted to `system.settings`)
___
*[pkg/sql/plan_opt.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBc_z4r54uLPdsSMZHV:-MBc_z4r54uLPdsSMZHW:b-9ppuw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/af4295e283d59b9b5690e669471d0d2d0f9c781e/pkg/sql/plan_opt.go#L213)):*
> ```Go
> 				// TODO(yuzefovich): remove this logic when deleting old
> 				// execFactory.
> 				bld = execbuilder.New(newDistSQLSpecExecFactory(p, true /* forceLocalPlanning */), execMemo, &opc.catalog, root, p.EvalContext())
> ```

What do you think of making this an enum instead of a bool? Not necessary but I think it looks nicer.


<!-- Sent from Reviewable.io -->

2020-07-07 18:22 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-:-MBeVnjUE7MFcKXEZ4bo:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/exec_util.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBYZxTR0JgjT0-mfMUg:-MBeFMP-09r74IWz5WlD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f0792fb638b457b265ad4b55d28fe981e520f37/pkg/sql/exec_util.go#L272)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Agreed. I think a session setting is better for this if we don't need a cluster setting because they seem more ephemeral (not persisted to `system.settings`)
</blockquote></details>

Done.
___
*[pkg/sql/plan_opt.go, line 213 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-MBc_z4r54uLPdsSMZHV:-MBeGgmV6Geu0S3Vzsx2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af4295e283d59b9b5690e669471d0d2d0f9c781e/pkg/sql/plan_opt.go#L213)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What do you think of making this an enum instead of a bool? Not necessary but I think it looks nicer.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-07 18:22 UTC, yuzefovich commented
Noticed a typo in the comment.

bors r-

2020-07-07 18:25 UTC, yuzefovich reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50903#-:-MBeWWHE6q4Wmbl3UB8P:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-07-07 20:58 UTC, merged