importccl: [WIP] add support for importing computed columns
cockroachdb/cockroach pull request #51321
Opened 2020-07-10 23:30 UTC by Anzoteh96

Previously, computed columns are not supported for IMPORT. This PR tries to address this problem by adding support for computed columns. This is accomplished by processing and evaluating the computed expressions at the row converter stage.

Release note (general change): computed columns are now supported in IMPORT.

2020-07-10 23:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51321)
<!-- Reviewable:end -->

2020-07-17 14:34 UTC, bobvawter commented
Would this add support for the `IMPORT MYSQLDUMP` to support converting its `VIRTUAL` column type into our `STORED`?

2020-07-17 14:46 UTC, Anzoteh96 commented
> Would this add support for the `IMPORT MYSQLDUMP` to support converting its `VIRTUAL` column type into our `STORED`?

I'm not really sure how `VIRTUAL` works in `MYSQLDUMP`. If it's the same as `STORED` in our CRDB database then it's potentially a yes. 

But that might also require some fixing in getting the targeted columns for the `MYSQLDUMP` case (which I will look into over the next few days). `PGDUMP`, for example, required the fix as in #51065 (and I suspect the same might be the same for MySQL).

2020-07-22 19:40 UTC, Anzoteh96 commented
@bobvawter I just had a chance to revisit this PR again, it seems like `Virtual column` is not supported by CRDB at all (also mentioned in issue #24455). According to [this doc](https://www.cockroachlabs.com/docs/stable/computed-columns.html), too, computed columns have to be `STORED`.

2020-07-23 15:17 UTC, bobvawter commented
The main use case that I'm seeing for (enterprise) customers who want to test-drive CRDB with their existing schemas.  I think that it's reasonable to convert `VIRTUAL` to `STORED` in the interest of reducing friction when folks are kicking the tires.

2020-07-29 15:28 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAFna8sitDlTpcDgG:-MDQAEGVCIgCN-Anxl9b:b-6catgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/ccl/importccl/import_stmt_test.go#L3314)):*
<details><summary><i alt="summary">Quoted 30 lines of code…</i></summary>

> ```
> 				},
> 				{
> 					"name": "b",
> 					"type": "int",
> 				},
> 			},
> 		}
> 		schemaStr, err := json.Marshal(schema)
> 		require.NoError(t, err)
> 		codec, err := goavro.NewCodec(string(schemaStr))
> 		require.NoError(t, err)
> 		// Create an AVRO writer from the schema.
> 		ocf, err := goavro.NewOCFWriter(goavro.OCFConfig{
> 			W:     &data,
> 			Codec: codec,
> 		})
> 		require.NoError(t, err)
> 		row1 := map[string]interface{}{
> 			"a": 1,
> 			"b": 2,
> 		}
> 		row2 := map[string]interface{}{
> 			"a": 3,
> 			"b": 4,
> 		}
> 		// Add the data rows to the writer.
> 		require.NoError(t, ocf.Append([]interface{}{row1, row2}))
> 		// Retrieve the AVRO encoded data.
> 		avroData = data.String()
> 	}
> ```
</details>

Have you see avroGen interface in read_import_avro_test?
___
*[pkg/sql/sqlbase/default_exprs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAqJc-R7p2eMWQSnW:-MDQAqJc-R7p2eMWQSnX:bnc5yzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/sql/sqlbase/default_exprs.go#L114)):*
> ```Go
> 
> // ProcessDefaultComputedColumns adds columns with DEFAULT or COMPUTED
> // to cols if not present, and returns those expressions.
> ```

i think it's not a great idea to add syntactic sugar utility functions like this (and the one above).
I think the code is much clearner if you simply call the underlying MakeDefaultExpr with apprpriate column filter yourself, at the call site.  Alternatively, you can just define these functions in the file you use them.  


<!-- Sent from Reviewable.io -->

2020-07-30 17:59 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAFna8sitDlTpcDgG:-MDVr8SC8O68RrChwyM1:buuig6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/ccl/importccl/import_stmt_test.go#L3314)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 				},
> 				{
> 					"name": "b",
> 					"type": "int",
> 				},
> 			},
> 		}
> 		schemaStr, err := json.Marshal(schema)
> 		require.NoError(t, err)
> 		codec, err := goavro.NewCodec(string(schemaStr))
> 		require.NoError(t, err)
> 		// Create an AVRO writer from the schema.
> 		ocf, err := goavro.NewOCFWriter(goavro.OCFConfig{
> 			W:     &data,
> 			Codec: codec,
> 		})
> 		require.NoError(t, err)
> 		row1 := map[string]interface{}{
> 			"a": 1,
> 			"b": 2,
> 		}
> 		row2 := map[string]interface{}{
> 			"a": 3,
> 			"b": 4,
> 		}
> 		// Add the data rows to the writer.
> 		require.NoError(t, ocf.Append([]interface{}{row1, row2}))
> 		// Retrieve the AVRO encoded data.
> 		avroData = data.String()
> 	}
> ```
Have you see avroGen interface in read_import_avro_test?
</blockquote></details>

I just looked into the `avroGen` interface: I could incorporate using the `testHelper` interface to get the schema up, but there are still more work to be done here in order to get the actual avroData that includes the row data. 
___
*[pkg/sql/row/row_converter.go, line 417 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDVrzfg2mOUREfnHAWP:-MDVrzfg2mOUREfnHAWQ:bkaiyz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/sql/row/row_converter.go#L417)):*
> ```Go
> 	cols []sqlbase.ColumnDescriptor, tableDesc *sqlbase.ImmutableTableDescriptor,
> ) []sqlbase.ColumnDescriptor {
> 	colIDSet := make(map[sqlbase.ColumnID]struct{}, len(cols))
> ```

Note: this is where `getRelevantColumns` is called which is basically `sqlbase.processColumnSet` except for the special case of Default + Computed columns. 
___
*[pkg/sql/sqlbase/default_exprs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAqJc-R7p2eMWQSnW:-MDVraXcCNvnR6Smg8Ih:bhelod1) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/sql/sqlbase/default_exprs.go#L114)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i think it's not a great idea to add syntactic sugar utility functions like this (and the one above).
I think the code is much clearner if you simply call the underlying MakeDefaultExpr with apprpriate column filter yourself, at the call site.  Alternatively, you can just define these functions in the file you use them.  
</blockquote></details>

Unfortunately `processColumnSet` is not exported by `sqlbase`. My getaround here would be to rewrite a `processColumnSet`-ish function in `row_converter.go` (known as `getRelevantColumns`) and then call `MakeDefaultExpr` from there. 


<!-- Sent from Reviewable.io -->

2020-07-30 18:03 UTC, miretskiy requested changes
> Reviewed 1 of 6 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAFna8sitDlTpcDgG:-MDVspd9DQcfkkeuUxYM:bjltfir) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/ccl/importccl/import_stmt_test.go#L3314)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I just looked into the `avroGen` interface: I could incorporate using the `testHelper` interface to get the schema up, but there are still more work to be done here in order to get the actual avroData that includes the row data. 
</blockquote></details>

Just bringing this up to your attention -- if you can use it, great; if not, ohh well.
___
*[pkg/sql/sqlbase/default_exprs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAqJc-R7p2eMWQSnW:-MDVt032-PQWrWE0UgwQ:b-e7obhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/sql/sqlbase/default_exprs.go#L114)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Unfortunately `processColumnSet` is not exported by `sqlbase`. My getaround here would be to rewrite a `processColumnSet`-ish function in `row_converter.go` (known as `getRelevantColumns`) and then call `MakeDefaultExpr` from there. 
</blockquote></details>

Is it possible to make it exported? Or perhaps just add exported version of that method with a todo to refactor callers of the unexported one?


<!-- Sent from Reviewable.io -->

2020-07-30 21:39 UTC, pbardea requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWX8IrA8rBmE9817s-:-MDWX8IrA8rBmE9817s0:b-fkz8qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/ccl/importccl/import_stmt_test.go#L3357)):*
> ```Go
> CREATE TABLE users (a INT, b INT, c INT AS (a + b) STORED);
> INSERT INTO users (a, b) VALUES (1, 2), (3, 4);
> `
> ```

Do we ever actually expect PGDUMP data to look like this? I would imagine any data exported from PGDUMP would have the value already populated in the computed column.
___
*[pkg/sql/row/row_converter.go, line 658 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWbIy92-aVXiAVompW:-MDWbIy92-aVXiAVompX:b-4m8p4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/sql/row/row_converter.go#L658)):*
> ```Go
> 		&txCtx,
> 		c.EvalCtx,
> 		&semaCtx, true)
> ```

Can you add an `/* addingCols */` comment on this param?
___
*[pkg/sql/row/row_converter.go, line 662 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWcienBWwl1LbiyvCE:-MDWcienBWwl1LbiyvCF:b-5wam7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/sql/row/row_converter.go#L662)):*
> ```Go
> 		return errors.Wrapf(err, "error evaluating computed expression for IMPORT INTO")
> 	}
> 	computedCols := make([]sqlbase.ColumnDescriptor, 0)
> ```

Is there a reason we need to change this? It seems like we'll be allocating an extra slice in cases where we don't have computed exrs.


<!-- Sent from Reviewable.io -->

2020-08-03 17:50 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAFna8sitDlTpcDgG:-MDpPFqNCA8aq3KpAuJs:b-rlxq18) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/ccl/importccl/import_stmt_test.go#L3314)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just bringing this up to your attention -- if you can use it, great; if not, ohh well.
</blockquote></details>

I'm using a different method now: use a helper function `createAvroData` to create the data for me. 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 3357 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWX8IrA8rBmE9817s-:-MDpPgrf7qce0evdHgK6:b-pk2mtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/ccl/importccl/import_stmt_test.go#L3357)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we ever actually expect PGDUMP data to look like this? I would imagine any data exported from PGDUMP would have the value already populated in the computed column.
</blockquote></details>

Hmm I'm not sure...let me look into it. 
___
*[pkg/sql/row/row_converter.go, line 658 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWbIy92-aVXiAVompW:-MDpQdkR-czK4noCwX7p:b-bfgzsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/sql/row/row_converter.go#L658)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can you add an `/* addingCols */` comment on this param?
</blockquote></details>

Done (interesting how Reviewable swallows this change but it's reflected here https://github.com/cockroachdb/cockroach/pull/51321/files )
___
*[pkg/sql/row/row_converter.go, line 662 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDWcienBWwl1LbiyvCE:-MDpPvXU3upUqzoyw5cm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/600ff74f7884de42c5122e1d1390155d4a494da4/pkg/sql/row/row_converter.go#L662)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Is there a reason we need to change this? It seems like we'll be allocating an extra slice in cases where we don't have computed exrs.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/default_exprs.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MDQAqJc-R7p2eMWQSnW:-MDpQ-CA6LHPp8KH2lr5:b-2bx6cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/71f87f9abd1f8f9498bdaec176be7e3f19a6a3a4/pkg/sql/sqlbase/default_exprs.go#L114)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Is it possible to make it exported? Or perhaps just add exported version of that method with a todo to refactor callers of the unexported one?
</blockquote></details>

I'm making it exported for now. 


<!-- Sent from Reviewable.io -->

2020-08-11 14:57 UTC, pbardea reviewed
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3413 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESfjXV9wspEgy5niri:-MESfjXV9wspEgy5nirj:b-hlsouq) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/ccl/importccl/import_stmt_test.go#L3413)):*
> ```Go
> 			format:          "PGDUMP",
> 			expectedResults: [][]string{{"1", "2", "3"}, {"3", "4", "7"}},
> 		},
> ```

Tests with both default and compute columns would also be interesting.
Also, reordering the target cols is also a good test case.
___
*[pkg/ccl/importccl/read_import_csv.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MEScjY1-uSSsdQCgDZT:-MEScjY1-uSSsdQCgDZU:b-1hsx4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/ccl/importccl/read_import_csv.go#L140)):*
> ```Go
> 			if col.IsComputed() {
> 				return nil,
> 					errors.Newf("%q is computed, which is not supported by IMPORT INTO CSV", col.Name)
> ```

Should this be a cannot write to computed column error? Are there plans for addressing the TODO here? I think that it's fairly important for that to be addressed before merging.
___
*[pkg/sql/row/row_converter.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESd-JI4yRGVodqc9_k:-MESd-JI4yRGVodqc9_l:bl3mi7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L125)):*
> ```Go
> 			// columns, all the columns which could possibly be referenced *are*
> 			// available.
> 			if !computedCols[i].IsComputed() {
> ```

Why do we need this? Shouldn't we not be marking non-computed columns as computed?
___
*[pkg/sql/row/row_converter.go, line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESu9h745Wiw4TcDVkN:-MESu9h83Jkl6GPLyaCy:b-5fpcok) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L389)):*
> ```Go
> 	colsForCompute := make([]sqlbase.ColumnDescriptor, len(c.tableDesc.Columns))
> 	for _, col := range c.tableDesc.Columns {
> 		colsForCompute[c.computedIVarContainer.Mapping[col.ID]] = col
> ```

How does the ordering of `colsForCompute` differ from `c.tableDesc.Columns`. This probably warrants a comment since it isn't immediately clear.
I'm also not sure that `colsForCompute` is the right name here since this looks like it's just a different ordering of all of the table columns?
___
*[pkg/sql/row/row_converter.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESwlgW7dw8xOP5dap6:-MESwlgW7dw8xOP5dap7:b7x1urt) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L407)):*
> ```Go
> 	var computedCols []sqlbase.ColumnDescriptor
> 	if len(computeExprs) > 0 {
> 		computedCols = colsForCompute
> ```

Is this what we want? I would expect `computedCols` to just be the columns that are computed.


<!-- Sent from Reviewable.io -->

2020-08-12 15:24 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3413 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESfjXV9wspEgy5niri:-MEYDq3GAVWsIZNazSfX:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/ccl/importccl/import_stmt_test.go#L3413)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Tests with both default and compute columns would also be interesting.
Also, reordering the target cols is also a good test case.
</blockquote></details>

Done. 
___
*[pkg/ccl/importccl/read_import_csv.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MEScjY1-uSSsdQCgDZT:-MEYDrH710u3nNhSmvFi:bsvrnzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/ccl/importccl/read_import_csv.go#L140)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Should this be a cannot write to computed column error? Are there plans for addressing the TODO here? I think that it's fairly important for that to be addressed before merging.
</blockquote></details>

It should really be error that checks that IMPORT CSV with targeted columns unspecified (in particular, happens in the case of `IMPORT TABLE`) should not support targeted columns. The TODO is there simply because we want to check this in the beginning of an IMPORT instead of every row (though I'm not too sure how would that work)
___
*[pkg/sql/row/row_converter.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESd-JI4yRGVodqc9_k:-MEYEUck457oomxjFmbs:b-omey1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L125)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Why do we need this? Shouldn't we not be marking non-computed columns as computed?
</blockquote></details>

So how it works is (see my comment below), if a row has no computed column, then this `computedCols` (or rather, as I renamed it, `computedColsLookup`) will be `nil`. Otherwise it will contain all the columns. 
___
*[pkg/sql/row/row_converter.go, line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESu9h745Wiw4TcDVkN:-MEYFCPP3usgL84P8-EG:brmxfmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L389)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

How does the ordering of `colsForCompute` differ from `c.tableDesc.Columns`. This probably warrants a comment since it isn't immediately clear.
I'm also not sure that `colsForCompute` is the right name here since this looks like it's just a different ordering of all of the table columns?
</blockquote></details>

`MakeComputedExprs` will return the computedExprs correspond to the order of `colsOrdered` (formerly `colsForCompute`), assuming that at least one of the columns is computed. Therefore we want the `colsOrdered` to follow the order that corresponds to `Datum`. 

As for the second part, would `colsOrdered` work? 
___
*[pkg/sql/row/row_converter.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESwlgW7dw8xOP5dap6:-MEYG5BG6AVAfwSis1ll:b-xr716c) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L407)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Is this what we want? I would expect `computedCols` to just be the columns that are computed.
</blockquote></details>

I'm thinking of passing `colsOrdered` into `GenerateInsertRow` which would ease the process of finding the corresponding Datum to be filled with computed expression. 


<!-- Sent from Reviewable.io -->

2020-08-12 17:43 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51321)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/importccl/read_import_csv.go, line 140 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MEScjY1-uSSsdQCgDZT:-MEYkqrq0A8Vre4DVLw8:b-2pl7eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/ccl/importccl/read_import_csv.go#L140)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

It should really be error that checks that IMPORT CSV with targeted columns unspecified (in particular, happens in the case of `IMPORT TABLE`) should not support targeted columns. The TODO is there simply because we want to check this in the beginning of an IMPORT instead of every row (though I'm not too sure how would that work)
</blockquote></details>

So I think this check could be moved as early to import planning stage: if the targeted columns are not specified, then computed expressions shouldn't be supported (with the exception of, perhaps, `AVRO` as the targeted columns are specified in the schemas). 
___
*[pkg/sql/row/row_converter.go, line 389 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MESu9h745Wiw4TcDVkN:-MEYkSLT5fnci7-FQnPj:bpz0bc7) ([raw file](https://github.com/cockroachdb/cockroach/blob/65ffd460edae6bf2b6338ecb26df9108c036af03/pkg/sql/row/row_converter.go#L389)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

`MakeComputedExprs` will return the computedExprs correspond to the order of `colsOrdered` (formerly `colsForCompute`), assuming that at least one of the columns is computed. Therefore we want the `colsOrdered` to follow the order that corresponds to `Datum`. 

As for the second part, would `colsOrdered` work? 
</blockquote></details>

Edit: I've moved that to row converter stage so that these computed expressions only have to be evaluated once for every import, not for every row. 
___
*[pkg/sql/row/row_converter.go, line 383 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51321#-MEYkdB81XfQycDLXp3L:-MEYkdB81XfQycDLXp3M:b-d4aep) ([raw file](https://github.com/cockroachdb/cockroach/blob/55636121c9ab681339df7b799a89035b3233c05f/pkg/sql/row/row_converter.go#L383)):*
> ```Go
> 		return nil, errors.Wrapf(err, "error evaluating computed expression for IMPORT INTO")
> 	}
> ```

The computed expression is now generated here. Notice that we still want the property of having the computed expressions to in the order aligning with the datums. 


<!-- Sent from Reviewable.io -->

2020-08-19 04:01 UTC, pbardea approved these changes
LGTM

2020-08-19 19:25 UTC, Anzoteh96 commented
TFTR!

bors r=pbardea

2020-08-19 19:49 UTC, merged