importccl: [WIP] support DEFAULT columns for current timestamp functions for IMPORT INTO
cockroachdb/cockroach pull request #51390
Opened 2020-07-13 19:54 UTC by Anzoteh96

like now(), localtimestamp, transaction_timestamp, current_date

This PR follows up from #50295 to add support for functions concerning current timestamps, which include now(), localtimestamp(), transaction_timestamp(), current_date(). This is achieved by injecting the walltime recorded at `importCtx` into evalCtx required for the evaluation of these functions.

Partially addresses #48253.

Release note (general change): current timestamp functions are now supported by IMPORT INTO.

2020-07-13 19:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51390)
<!-- Reviewable:end -->

2020-07-15 14:20 UTC, miretskiy requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHh-6c9qcv-gHbxaQ7:-MCHh-6c9qcv-gHbxaQ8:bjmvxdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2639)):*
> ```Go
> 				fmt.Sprintf(`IMPORT INTO t (a) CSV DATA ("%s")`, srv.URL))
> 		})
> 		t.Run("current-timestamp", func(t *testing.T) {
> ```

The way that you do this table driven test is a bit strange.

Usually you would have array of test cases, and you would t.Run() inside each of the subtests --
giving those subtests a descriptive name.

I would move this entire test cases into a separate TestImportDataTimeDefaultExpressions (or some such) -- this TestImportData is already huge enough (even if you have to copy few extra setup lines -- such as starting server, cluster, etc)

I would give each of your tests cases below a "name" (string), and then
for _, tc := range testCases {
   t.Run(tc.name, ...)
}
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHZMQd3JJA_nBleemg:-MCHZMQd3JJA_nBleemh:b-mhoxiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2642)):*
> ```Go
> 			// TODO(anzoteh96): need to figure out a way for timeofday() validation
> 			// because the format returned is different from the usually UTC format
> 			// and it's stored as string in the database.
> ```

I'm not sure I understand.  You can format & parse time, right?

```
timeOfDayFmt := ""Mon Jan _2 15:04:05.999999 2006 -0700""
parsedTimeOfDay, err := time.Parse(timeOfDayFmt, "Wed Jul 15 13:07:06.586762 2020 +0000");
```
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlZ8dCQR1NeqUm4Uc:-MCHlZ8dCQR1NeqUm4Ud:b-toqoaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2690)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 				if test.millisecond {
> 					sqlDB.Exec(t, fmt.Sprintf(`CREATE TABLE t(a INT, b %s DEFAULT %s(%d))`, test.colType, test.defaultExpr, 3))
> 				} else {
> 					sqlDB.Exec(t, fmt.Sprintf(`CREATE TABLE t(a INT, b %s DEFAULT %s)`, test.colType, test.defaultExpr))
> 				}
> ```
</details>

This looks a bit strange.  WHy not just change you defaultExpr in the test case:
you can have for example:
```
				{
					defaultExpr: "localtimestamp(3)",
					colType:     "TIMESTAMP",
				},
				{
					defaultExpr: "localtimestamp",
					colType:     "TIMESTAMP",
				},

```
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlnbzEacMsU88p9xR:-MCHlnbzEacMsU88p9xS:bg2z6jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2704)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 				timeStart := timeutil.Now()
> 				sqlDB.Exec(t, fmt.Sprintf(`IMPORT INTO t (a) CSV DATA ("%s")`, srv.URL))
> 				timeEnd := timeutil.Now()
> 				if test.colType == "DATE" {
> 					timeStart = timeStart.Truncate(24 * time.Hour)
> 					timeEnd = timeEnd.Truncate(24 * time.Hour)
> 				} else if test.millisecond {
> 					timeStart = timeStart.Truncate((time.Millisecond))
> 					timeEnd = timeEnd.Truncate((time.Millisecond))
> 				}
> 				var timeNow time.Time
> 				sqlDB.QueryRow(t, `SELECT b from t`).Scan(&timeNow)
> 				timeStr := sqlDB.QueryStr(t, `SELECT * from t`)
> 				assert.True(t, validTimestamp(timeStr, 1, timeStart, timeEnd, timeNow), test.defaultExpr, timeStart, timeStr, timeEnd)
> ```
</details>


I try to avoid relying on time in my tests.  Such tests tend to be (or become) flaky.
Consider what it is we are trying to test:
 
We want to ensure that every row we import is set to something other than NULL,
and that each row has exactly the same value.  You don't need to worry about testing
the type of the column for example -- that's ensured by the database itself.

So, how we could test the above?

You can query sqlDB.DB.QueryRow() directly and look at the returned Rows object -- ensure each row has identical value for column b.

Or, you can let the database itself do the work for you:

```
var numBadRows int
sqlDB.QueryRow(t, "SELECT count(*) FROM t WHERE  b !=(SELECT b FROM t WHERE a=1) OR b IS NULL").Scan(&numBadRows);
require.Equal(t, 0, numBadRows)
```
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlPSRAI7s1-RG1Aer:-MCHlPSSAfitYiHr1ajm:bna24de) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2705)):*
> ```Go
> 				timeStr := sqlDB.QueryStr(t, `SELECT * from t`)
> 				assert.True(t, validTimestamp(timeStr, 1, timeStart, timeEnd, timeNow), test.defaultExpr, timeStart, timeStr, timeEnd)
> 				sqlDB.Exec(t, `DROP TABLE t`)
> ```

you definitely want to move this to the beginning of your test with
```
defer sqlDB.Exec(...)
```
___
*[pkg/ccl/importccl/read_import_base.go, line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHcokR3gIN6EXY-Qp-:-MCHcokR3gIN6EXY-Qp0:b-l05juk) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/read_import_base.go#L492)):*
> ```Go
> 	nsec := importCtx.walltime % int64(time.Second)
> 	importCtx.evalCtx.TxnTimestamp = timeutil.Unix(sec, nsec)
> 	importCtx.evalCtx.StmtTimestamp = timeutil.Unix(sec, nsec)
> ```

i'm not sure this is the right place for this.

parallel importer is not used everywhere -- see read_import_pgdump.go for example.
Presumably, we'd want to support default expressions there as well.

I would introduce helper function here -- something like setEvalCtxTimestamps(...)
Or even 
```
func withEvalContextTimestamp(evalCtx *tree.EvalContext, wall int64) *tree.EvalContext {
  copy := evalCtx.Copy();
  copy.TxnTimestamp = ....
}
```

I would probably call this function inside makeDatumeConverter() function.
And other places (pgdump) can call this function directly as well.
___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCHXg9fA-54tNCr5Ce-:bvehff8) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
> ```Go
> 	"current_date()", "current_timestamp",
> 	"localtimestamp", "now()", "statement_timestamp()",
> 	"timeofday()", "transaction_timestamp()",
> ```

why do some of these have () and some dont?
Please rename to supportedDefaultExpressions.

Wouldn't you be better off if this were a map for a quick lookup inside isSupportedDefault?
supportedDefaultExpressions: map[string]struct{}{
   "current_date()": struct{},
   ...
}
___
*[pkg/sql/row/row_converter.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXwnjBvpKGHMUKdBX:-MCHXwnjBvpKGHMUKdBY:b-he6u33) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L33)):*
> ```Go
> }
> 
> func isSupportedDefault(ctx *tree.EvalContext, expr tree.TypedExpr, defaultStr string) bool {
> ```

can you rename to isSupportedDefaultExpression?


<!-- Sent from Reviewable.io -->

2020-07-15 19:22 UTC, Anzoteh96 reviewed
Addressed changes, pending a way to test the validity of the time returned without being flaky. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCIukzT6onaHE6YQukY:ba8v2sk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHh-6c9qcv-gHbxaQ7:-MCIu9vu2stiygI7DuYg:bra877y) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2639)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

The way that you do this table driven test is a bit strange.

Usually you would have array of test cases, and you would t.Run() inside each of the subtests --
giving those subtests a descriptive name.

I would move this entire test cases into a separate TestImportDataTimeDefaultExpressions (or some such) -- this TestImportData is already huge enough (even if you have to copy few extra setup lines -- such as starting server, cluster, etc)

I would give each of your tests cases below a "name" (string), and then
for _, tc := range testCases {
   t.Run(tc.name, ...)
}

</blockquote></details>

I have #51468 that deals with moving all the tests regarding default expressions outside `testImportCSV`. I'm looking at moving this part outside in that PR (or here, if that PR is merged first). 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHZMQd3JJA_nBleemg:-MCIu-80Bzadyq4wCEZC:b-723fsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2642)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure I understand.  You can format & parse time, right?

```
timeOfDayFmt := ""Mon Jan _2 15:04:05.999999 2006 -0700""
parsedTimeOfDay, err := time.Parse(timeOfDayFmt, "Wed Jul 15 13:07:06.586762 2020 +0000");
```



</blockquote></details>

Just added a way to test that. 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2690 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlZ8dCQR1NeqUm4Uc:-MCInOldDPJBiDJJXCNT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2690)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 				if test.millisecond {
> 					sqlDB.Exec(t, fmt.Sprintf(`CREATE TABLE t(a INT, b %s DEFAULT %s(%d))`, test.colType, test.defaultExpr, 3))
> 				} else {
> 					sqlDB.Exec(t, fmt.Sprintf(`CREATE TABLE t(a INT, b %s DEFAULT %s)`, test.colType, test.defaultExpr))
> 				}
> ```
This looks a bit strange.  WHy not just change you defaultExpr in the test case:
you can have for example:
```
				{
					defaultExpr: "localtimestamp(3)",
					colType:     "TIMESTAMP",
				},
				{
					defaultExpr: "localtimestamp",
					colType:     "TIMESTAMP",
				},

```
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlnbzEacMsU88p9xR:-MCInRsaE3jnE7F-HkBW:br1qai5) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2704)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 				timeStart := timeutil.Now()
> 				sqlDB.Exec(t, fmt.Sprintf(`IMPORT INTO t (a) CSV DATA ("%s")`, srv.URL))
> 				timeEnd := timeutil.Now()
> 				if test.colType == "DATE" {
> 					timeStart = timeStart.Truncate(24 * time.Hour)
> 					timeEnd = timeEnd.Truncate(24 * time.Hour)
> 				} else if test.millisecond {
> 					timeStart = timeStart.Truncate((time.Millisecond))
> 					timeEnd = timeEnd.Truncate((time.Millisecond))
> 				}
> 				var timeNow time.Time
> 				sqlDB.QueryRow(t, `SELECT b from t`).Scan(&timeNow)
> 				timeStr := sqlDB.QueryStr(t, `SELECT * from t`)
> 				assert.True(t, validTimestamp(timeStr, 1, timeStart, timeEnd, timeNow), test.defaultExpr, timeStart, timeStr, timeEnd)
> ```

I try to avoid relying on time in my tests.  Such tests tend to be (or become) flaky.
Consider what it is we are trying to test:
 
We want to ensure that every row we import is set to something other than NULL,
and that each row has exactly the same value.  You don't need to worry about testing
the type of the column for example -- that's ensured by the database itself.

So, how we could test the above?

You can query sqlDB.DB.QueryRow() directly and look at the returned Rows object -- ensure each row has identical value for column b.

Or, you can let the database itself do the work for you:

```
var numBadRows int
sqlDB.QueryRow(t, "SELECT count(*) FROM t WHERE  b !=(SELECT b FROM t WHERE a=1) OR b IS NULL").Scan(&numBadRows);
require.Equal(t, 0, numBadRows)
```


</blockquote></details>

I made the change you suggested for checking `badRows`, but I still think it's worth to verify that the time returned is legitimate because before as of the current state (before this PR change), the time recorded in the `evalCtx` is either something like `0001-01-01 00:00:00` or `1754-08-30 00:00:00` (which are the same for every row, and not NULL), but the time returned is simply wrong). 
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2705 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlPSRAI7s1-RG1Aer:-MCIo3if0O77qjEfEidz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2705)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

you definitely want to move this to the beginning of your test with
```
defer sqlDB.Exec(...)
```
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/read_import_base.go, line 492 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHcokR3gIN6EXY-Qp-:-MCIo6V4AwrbHyZlCgNR:bvgskf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/read_import_base.go#L492)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i'm not sure this is the right place for this.

parallel importer is not used everywhere -- see read_import_pgdump.go for example.
Presumably, we'd want to support default expressions there as well.

I would introduce helper function here -- something like setEvalCtxTimestamps(...)
Or even 
```
func withEvalContextTimestamp(evalCtx *tree.EvalContext, wall int64) *tree.EvalContext {
  copy := evalCtx.Copy();
  copy.TxnTimestamp = ....
}
```

I would probably call this function inside makeDatumeConverter() function.
And other places (pgdump) can call this function directly as well.
</blockquote></details>

Thanks for catching! Yes it turned out that this doesn't work for `PGDUMP` and `MySQL`, but neither would `makeDatumConverter` (as it's not being called). 

I've move these to `import_processor: makeInputCoverter` since all formats of import have to call that function. 
___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCIoeDA5yBTy_epXtMQ:b-8vlsju) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why do some of these have () and some dont?
Please rename to supportedDefaultExpressions.

Wouldn't you be better off if this were a map for a quick lookup inside isSupportedDefault?
supportedDefaultExpressions: map [...]

2020-07-15 22:57 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHh-6c9qcv-gHbxaQ7:-MCJ0GIm1hoCabA6B-8h:b-n7c5jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2639)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I have #51468 that deals with moving all the tests regarding default expressions outside `testImportCSV`. I'm looking at moving this part outside in that PR (or here, if that PR is merged first). 
</blockquote></details>

Just want to make sure this comment is not lost along the way.  This is new code you're adding.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlnbzEacMsU88p9xR:-MCJ1JY28Eq5funmO16l:b-7qycjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2704)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I made the change you suggested for checking `badRows`, but I still think it's worth to verify that the time returned is legitimate because before as of the current state (before this PR change), the time recorded in the `evalCtx` is either something like `0001-01-01 00:00:00` or `1754-08-30 00:00:00` (which are the same for every row, and not NULL), but the time returned is simply wrong). 
</blockquote></details>

Eh... Not sure about that.  There is complexity in the testing code.  If you worried about that particular case, then you can get the smallest allowed timestamp before you start import, like you do now:
minTs := timeutil.Now()
and just change query to add "OR b < $1" (plus add minTs as an argument to the query)
___
*[pkg/ccl/importccl/import_stmt_test.go, line 2673 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCJ2C6O-1NcTnabTbUc:-MCJ2C6PEUUa-NHmjUFE:b-wovbwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1bb79f8524bfab4b3f1b84ec8af8a6f73e7f057/pkg/ccl/importccl/import_stmt_test.go#L2673)):*
> ```Go
> 			for _, test := range testCases {
> 				t.Run(test.name, func(t *testing.T) {
> 					defer sqlDB.Exec(t, `DROP TABLE t`)
> ```

DROP IF EXIST, if you want to be defensive.
___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCJ2U1nE7S3u5paeuKO:bek2czl) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

The tricky part is that some of them may have arguments: like `localtimestamp()` vs `localtimestamp(d int)` (for precision), so I've changed that to Regex matching. 
</blockquote></details>

This makes me sad.

Particularly since we'll be matching 7 regexes for each row we are importing...  1B of them, for example.

I think there are 2 issues that must be addressed:

1. In the row converter itself, the fact that columns have default expressions, is known when converter is created.  Since the value of these expressions does not change for the duration of the import, we should "compute" the tree.Datum values for those columns, memoize them, and just lookup up correct value inside Row().  This can be done for everything except nextval() when it is supported. 

2. I really dislike these regexes. We should not be in the business of interpreting strings.  We have parser for that.  Also note, that if you say that current_timestamp() is supported default expression for import, is something like "current_timestamp()::int + current_timestamp()::int" supported?  Your regexes clearly cannot deal with this, but this type of expression should be fine for the import.

I've spent some time looking at what can be done about this.  Browsing through the code, I have traced and understood (more or less) where/how sql reports certain default expressions as valid or invalid during table creation.

Few observations we can make: first, the column DefaultExpr field has been already sanitized when the table was created.  In particular, sqlbase/table.go:190 calls SanitizeVarFreeExpr:
```
if d.HasDefaultExpr() {
		// Verify the default expression type is compatible with the column type
		// and does not contain invalid functions.
		var err error
		if typedExpr, err = SanitizeVarFreeExpr(
			ctx, d.DefaultExpr.Expr, resType, "DEFAULT", semaCtx, tree.VolatilityVolatile,
		); err != nil {
			return nil, nil, nil, err
		}
 ....
```

The SanitizeVarFreeExpr accepts slightly larger set of things that import supports.  But crucially, it does reject many things we also should be rejecting.

So, using that function as a blueprint, i've put together 

https://github.com/cockroachdb/cockroach/pull/51486/files

I basically use the fact that column DefaultExpr has already been sanitized; the only thing
I do in addition is to check that the expression does not contain volatile functions.

Crucially, the current_timestamp, etc function are not volatile.  They are stable functions, meaning that they return the same value for the duration of transaction.

Now, there are many more stable functions than your PR attempts to support.
However, I do think that, in general, we ought to be able to support any stable function that has not been rejected by SanitizeVarFreeExpr.

Crucially, SanitizeVarFreeExpr disallows many stable functions, such as aggregates, which I also disallow.

@pbardea @dt  -- please take a look at this as well.


<!-- Sent from Reviewable.io -->

2020-07-16 00:09 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @dt, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCJj_wg7ixc-SfqynOw:b-93e1zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This makes me sad.

Particularly since we'll be matching 7 regexes for each row we are importing...  1B of them, for example.

I think there are 2 issues that must be addressed:

1. In the row converter itself, the fact that columns have default expressions, is known when converter is created.  Since the value of these expressions does not change for the duration of the import, we should "compute" the tree.Datum values for those columns, memoize them, and just lookup up correct value inside Row().  This can be done for everything except nextval() when it is supported. 

2. I really dislike these regexes. We should not be in the business of interpreting strings.  We have parser for that.  Also note, that if you say that current_timestamp() is supported default expression for import, is something like "current_timestamp()::int + current_timestamp()::int" supported?  Your regexes clearly cannot deal with this, but this type of expression should be fine for the import.

I've spent some time looking at what can be done about this.  Browsing through the code, I have traced and understood (more or less) where/how sql reports certain default expressions as valid or invalid during table creation.

Few observations we can make: first, the column DefaultExpr field has been already sanitized when the table was created.  In particular, sqlbase/table.go:190 calls SanitizeVarFreeExpr:
```
if d.HasDefaultExpr() {
		// Verify the default expression type is compatible with the column type
		// and does not contain invalid functions.
		var err error
		if typedExpr, err = SanitizeVarFreeExpr(
			ctx, d.DefaultExpr.Expr, resType, "DEFAULT", semaCtx, tree.VolatilityVolatile,
		); err != nil {
			return nil, nil, nil, err
		}
 ....
```

The SanitizeVarFreeExpr accepts slightly larger set of things that import supports.  But crucially, it does reject many things we also should be rejecting.

So, using that function as a blueprint, i've put together 

https://github.com/cockroachdb/cockroach/pull/51486/files

I basically use the fact that column DefaultExpr has already been sanitized; the only thing
I do in addition is to check that the expression does not contain volatile functions.

Crucially, the current_timestamp, etc function are not volatile.  They are stable functions, meaning that they return the same value for the duration of transaction.

Now, there are many more stable functions than your PR attempts to support.
However, I do think that, in general, we ought to be able to support any stable function that has not been rejected by SanitizeVarFreeExpr.

Crucially, SanitizeVarFreeExpr disallows many stable functions, such as aggregates, which I also disallow.

@pbardea @dt  -- please take a look at this as well.


</blockquote></details>

Yeah, broadly agree with these points: I'd want to do as much as we possibly can once, at creation, not row-by-row. I'd also want to see SQL doing the function resolution, not some regex we maintain. 

I'll probably defer to @rohany or @knz on how to do that, but I imagine we could try walking the expr AST with a visitor that looks for tree.FuctionDefinition and, if it finds it, compares the `Name` field to the set for which IMPORT is going to supply overridden implementations. 

SanitizeFreeVar with max volatility Immutable looks close to what we want, but we'd want to pluck out the few stable or volatile functions where we have alternative, IMPORT-compatible implementations. 


<!-- Sent from Reviewable.io -->

2020-07-16 00:18 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @dt, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCJyuWK7tQofJgvEdKE:b-92fazl) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yeah, broadly agree with these points: I'd want to do as much as we possibly can once, at creation, not row-by-row. I'd also want to see SQL doing the function resolution, not some regex we maintain. 

I'll probably defer to @rohany or @knz on how to do that, but I imagine we could try walking the expr AST with a visitor that looks for tree.FuctionDefinition and, if it finds it, compares the `Name` field to the set for which IMPORT is going to supply overridden implementations. 

SanitizeFreeVar with max volatility Immutable looks close to what we want, but we'd want to pluck out the few stable or volatile functions where we have alternative, IMPORT-compatible implementations. 
</blockquote></details>

I did start writing a visitor; but then realized that sema ctx can reject anything I wanted to reject anyway.


<!-- Sent from Reviewable.io -->

2020-07-16 01:09 UTC, rohany commented
I took a quick look -- we _definitely_ do not want to be checking this function validity per row! Additionally, this regex approach doesn't work for expressions that contain more than just the builtin.

Writing a visitor and using that visitor during import schema validation to reject bad default expressions is the right way to do this. Additionally, I would take a look at the function volatilities in `pkg/sql/sem/tree/volatility.go` and see whether you can just restrict this check to a volatility rather than keeping some allow list of functions. These allow lists rot easily, and we are always adding new builtins. Additionally, does this PR disallow users from using builtins that aren't these selected time related builtins? If someone wants to use a builtin like `length()` why should we stop them?

2020-07-16 01:18 UTC, dt commented
I think in general we're only okay with VolatilityImmutable. Above that, there are a handful of _specific_ functions like `now` / `statement_timestamp`, `unique_rowid` and someday `nextval` and `gen_random_uuid` that we want to support, though to do so we'll need to swap out their implementations for IMPORT-specific ones (i.e. for random UUID we'll need to ensure deterministic seed based for a single IMPORT, so e.g. we pick a random number during job planning and then use that to see the rng on each resume. For unique_rowid, we use the IMPORT's write timestamp plus some number of microseconds per row. For nextval... it's complicated. So, essentially I think we want something like:

Constant expr? yes, eval to datum and done.
SantizeFreeVars with tree.VolatilityImmutable? yes? eval to datum and done.
Visitor walks AST, looks for the functions we overrided, replaces them with with our own tree.Overloads.

But for the ones that are actually volatile even with our IMPORT-speicifc overload, we'll still need to eval row-by-row, e.g. unique_rowid or gen_random_uuid.

2020-07-16 01:21 UTC, rohany commented
I think a custom walker that does the following would work:
* when it finds a function with a volatility too high, it looks into the set of registered import functions. 
* If available, it swaps it out for the import version, otherwise it errors

2020-07-16 01:47 UTC, miretskiy reviewed
@rohany how would we know which function we are looking at?  When walking expression, we just know it's a function; we don't know its name (or i'm missing something).  So, how would we check if we have registered import specific override?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCKIK4j4uLa5nIX7eRA:b-emrbc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)



<!-- Sent from Reviewable.io -->

2020-07-16 01:51 UTC, miretskiy reviewed
@rohany nvm... FuncExpr has Func...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCKJEdB0fyK5U0HeElm:b3oc04w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)



<!-- Sent from Reviewable.io -->

2020-07-16 02:06 UTC, pbardea reviewed
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlnbzEacMsU88p9xR:-MCKFfAYA-mwGXPku6XN:by6d1zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2704)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Eh... Not sure about that.  There is complexity in the testing code.  If you worried about that particular case, then you can get the smallest allowed timestamp before you start import, like you do now:
minTs := timeutil.Now()
and just change query to add "OR b < $1" (plus add minTs as an argument to the query)
</blockquote></details>

I like the idea of only checking for a minimum timestamp.
___
*[pkg/sql/row/row_converter.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHXg9fA-54tNCr5Cdz:-MCK8_WdDUEXT6XgN9aY:b-bizlu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/sql/row/row_converter.go#L30)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I did start writing a visitor; but then realized that sema ctx can reject anything I wanted to reject anyway.
</blockquote></details>

Thank you for your in-depth comment Yevginey.

I also generally agree here. First, we should move the evaluation of Immutable default expressions to run once (perhaps at row converter creation). Additionally, we should be validating the default expressions at creation as well, and avoid doing it in every iteration of the loop. Sorry for not catching that when reviewing the addition of the constant default expressions.

I don't think that we should implement all stable functions, since they can read current database state. I agree with @dt and think that we should explicitly allow a subset of non-immutable functions, but we should do this based on the name rather than a regex.
___
*[pkg/sql/row/row_converter.go, line 400 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCKGct_BrTjovydC_0t:-MCKGct_BrTjovydC_0u:b-e41mf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1bb79f8524bfab4b3f1b84ec8af8a6f73e7f057/pkg/sql/row/row_converter.go#L400)):*
> ```Go
> 		col := &c.cols[i]
> 		if _, ok := c.IsTargetCol[i]; !ok && !col.Hidden && col.DefaultExpr != nil {
> 			isSupported, err := isSupportedDefaultExpr(c.EvalCtx, c.defaultExprs[i])
> ```

As mentioned in the other comment, we'll want to move this to only run once. We'll also want to create a map between column IDs and the value that we should insert for Immutable default expressions.


<!-- Sent from Reviewable.io -->

2020-07-16 02:22 UTC, Anzoteh96 commented
Thanks for the insightful discussion above! I definitely agree that checking `regex` per row is very undesirable, will find a way to put together the methods suggested above. :) 

Regarding the set of functions we want to support, I've looked through the "Stable" functions (or have at least one "stable" overload, and no "volatile" overload) from the `sql/sem/builtins/builtins.go` and on broader term, this is the list of them:
1. `quote_literal` and `quote_nullable` for `anyelement` overload. 
2. the timestamp function as of this PR, along with some attention to timezone conversion and other time-related function like `age` and `timezone`. 
3. `array_to_string`, and some JSON-related functions like `json_build_object`
4. `current_user`, `current_database` `current_schema`
5. Other functions that (I suppose) aren't really intended to be used as default expressions like `enum` and `crdb_internal` functions. 

So it looks like it's reasonable to support the `Stable` functions in 1-4 above; would take a bit of time to verify that each of them would work, though.

2020-07-16 03:13 UTC, miretskiy reviewed
I pushed some changes to https://github.com/cockroachdb/cockroach/pull/51486/files
I think that's what we want to have -- list of allowed functions (the list needs to be updated, i only put in few functions there)

@rohany , please take a look.

Basically, the check for import safe functions is :
```

var importSafeFunctions = map[string]struct{}{
	"current_timestamp": {},
	"now":               {},
	"localtimestamp":    {},
}

type importSafeVisitor struct {
	ctx    *tree.EvalContext
	isSafe bool
}

func (v *importSafeVisitor) VisitPre(expr tree.Expr) (bool, tree.Expr) {
	return v.isSafe, expr
}

func (v *importSafeVisitor) VisitPost(expr tree.Expr) (newNode tree.Expr) {
	if fn, ok := expr.(*tree.FuncExpr); ok {
		_, v.isSafe = importSafeFunctions[fn.Func.String()]
	}
	return expr
}

func SanitizeExpressionForImport(
	ctx context.Context, evalCtx *tree.EvalContext, expr tree.Expr, targetType *types.T,
) (tree.Expr, error) {
	semaCtx := tree.MakeSemaContext()
	typedExpr, err := sqlbase.SanitizeVarFreeExpr(
		ctx, expr, targetType, "isImportSafe", &semaCtx, tree.VolatilityImmutable)
	if err == nil {
		return typedExpr, nil
	}

	v := &importSafeVisitor{ctx: evalCtx, isSafe: true}
	tree.WalkExprConst(v, expr)
	if !v.isSafe {
		return nil, errors.Newf("default expression %q not safe for import", tree.AsString(expr))
	}

	return expr, nil
}

var _ tree.Visitor = &importSafeVisitor{}
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCKaldH5yr4Z9N-bB3S:b-nrsj27)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)



<!-- Sent from Reviewable.io -->

2020-07-16 03:33 UTC, rohany commented
Left some comments on that PR

2020-07-16 12:08 UTC, miretskiy reviewed
Thanks, @rohany .  @anzoteh96 I think you should pick up general outline from the PR I created; incorporate test, and the visitor into this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCMWSqmAtRGLkSZeIBI:b-fnansx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)



<!-- Sent from Reviewable.io -->

2020-07-17 23:11 UTC, Anzoteh96 reviewed
After studying the visitor guideline by @miretskiy (those that I think is critical to this PR) here are the things I do:
1. I added `getImmutableDefault` to be called at the stage of `NewDatumRowConverter`: if the expression is immutable, we will evaluate right away and cache it at the `NewDatumRowConverter` stage so that if this default column is not targeted, we can just used this cached value for each row, right away. 

2. I did a basic visitor method that basically checks that all non-immutable function expressions contained in the expression must come from the allowed list of functions. Given that this PR is mainly for the time functions (which do not require overloading), I did not implement the overloading part at this stage, but will definitely get to that when I continue the work at, say, #50922 . 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCTyuRKDTC1HBRKeVXb:b-49iaai)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2704 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHlnbzEacMsU88p9xR:-MCTySPD5mumrPRMZ01k:b8g22i3) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2704)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I like the idea of only checking for a minimum timestamp.
</blockquote></details>

I added checking for _maximum_ allowed timestamp too, just to catch error like `2040-01-01` if that happens. 


<!-- Sent from Reviewable.io -->

2020-07-17 23:48 UTC, miretskiy requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8T6_-0gsUdho4FvT:-MCU8T6_-0gsUdho4FvU:buzc58k) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L42)):*
> ```Go
> type importDefaultExprVisitor struct {
> 	err error
> 	ctx *tree.EvalContext
> ```

unused?
___
*[pkg/sql/row/row_converter.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU60NwAjXfPFORdcr5:-MCU60Nx5J9amV0po38b:bo19hap) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L56)):*
> ```Go
> 	case *tree.FuncExpr:
> 		if fn.ResolvedOverload().Volatility > tree.VolatilityImmutable {
> 			fnName := fn.Func.String()
> ```

Please take a look at https://github.com/cockroachdb/cockroach/pull/51486/files
In particular, we don't need to us fn.Func.String().
Func is a resolved function.  
resolvedFnName := fn.Func.FunctionReference.(*tree.FunctionDefinition).Name
___
*[pkg/sql/row/row_converter.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU97cA0_ziZWt8S3hU:-MCU97cA0_ziZWt8S3hV:b-b24pm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L67)):*
> ```Go
> func getImmutableDefault(
> 	ctx context.Context, evalCtx *tree.EvalContext, expr tree.Expr, targetType *types.T,
> ) tree.Datum {
> ```

I don't understand why we need to have separate getImmutableDefault vs SanitizeExprsForImport.

At least, as of right now, the expressions you do support, even though they are not VolatilityImmutable, are actually safe to be cached at the NewDatumConverter stage.  
We turned time based functions into something that never changes.  Thus, this method is completely unnecessary.

Furthermore, when we support Stable/Volatilize expressions, we can return tree.Expr instead of tree.Datum to indicate that such expression should not be evaluated at New() stage, but instead when calling Row()
___
*[pkg/sql/row/row_converter.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8Hwe0N1wKiJO_IUl:-MCU8HwfEmS-fLD6inwu:b6702ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L84)):*
> ```Go
> ) (tree.Datum, error) {
> 	semaCtx := tree.MakeSemaContext()
> 	typedExpr, err := sqlbase.SanitizeVarFreeExpr(ctx, expr, targetType, "import_default", &semaCtx, tree.VolatilityImmutable)
> ```

wrap long lines please?
___
*[pkg/sql/row/row_converter.go, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8MiABpuw6s22xwEL:-MCU8MiABpuw6s22xwEM:b-ssww9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L104)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	if v.err != nil {
> 		return nil, unsafeExpressionError(v.err, "walking", expr.String())
> 	}
> 	datum, err := newExpr.(tree.TypedExpr).Eval(evalCtx)
> 	if err != nil {
> 		return nil, unsafeExpressionError(err, "eval", expr.String())
> 	}
> ```
</details>

please take a look at my PR.  This is not needed.  Please add comments on the importDefaultExprVisitor to indicate that it must be invoked on the typed expression.

I've made some changes to this method -- please incorporate them.
___
*[pkg/sql/row/row_converter.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCUA8PN7gFxC8XMq9X5:-MCUA8PN7gFxC8XMq9X6:b1ancb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L290)):*
> ```Go
> 	VisibleColTypes       []*types.T
> 	defaultExprs          []tree.TypedExpr
> 	defaultCache          []tree.Datum
> ```

we probably don't need defaultExprs now, do we?
___
*[pkg/sql/row/row_converter.go, line 467 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCUAL186x6txZROmEFu:-MCUAL186x6txZROmEFv:basraof) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L467)):*
> ```Go
> 				c.Datums[i] = c.defaultCache[i]
> 			} else {
> 				datum, err := SanitizeExprsForImport(ctx, c.EvalCtx, c.defaultExprs[i], c.defaultExprs[i].ResolvedType())
> ```

see comment above -- we probably don't need to evaluate anything now.


<!-- Sent from Reviewable.io -->

2020-07-20 15:43 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2684 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCgaFoEE3eZsBo8ghHA:-MCgaFoFACiEb-hZ0Tw5:bw1el3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/ccl/importccl/import_stmt_test.go#L2684)):*
> ```Go
> 					defaultExpr: "transaction_timestamp()",
> 					colType:     "TIMESTAMP",
> 				},
> ```

Test cases with some casting and nesting of builtins. Also test cases like testing that the override name is case insensitive and methods like `pg_catalog.now()`.  Also negative cases where we throw errors.
___
*[pkg/sql/row/row_converter.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCgYokw-brA_KkDM6WT:-MCgYokx4JC1B6E8GXUD:buqkhbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L92)):*
> ```Go
> 		return datum, nil
> 	}
> 	typedExpr, err = tree.TypeCheck(ctx, expr, &semaCtx, targetType)
> ```

In addition, the comments on Yevgeniy's branch are also useful and would be good to incorporate.


<!-- Sent from Reviewable.io -->

2020-07-20 15:53 UTC, Anzoteh96 reviewed
TL;DR the workflow of the default expression checking is:
-- If the default expression is safe and stays the same throughout the import, we evaluate right away at the `NewDatumRowConverter` stage and store the evaluated datum in `defaultCache`. 

-- If the default expression is safe but could change within the same import (e.g. `rowid` that we will support later on), we will return the sanitized expression at `defaultCache` which will be evaluated at `row()` stage. 

-- Otherwise the default expression is unsafe, but we don't know if the column is targeted or not so we don't want to throw an error right away at `NewDatumRowConverter`. Instead we cache the error in `defaultUnsafeErr` such that if this default expression is used in any row later (i.e., not targeted column), we will throw the error. 

(Also @pbardea left a review before I could finish commenting here, I will address them shortly but in the meantime anyone please feel free to critique this workflow). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCgst_J02tQtf3WPYWB:b-7c3pqe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8T6_-0gsUdho4FvT:-MCgrAzKCnCrDF5dSA4A:b-v6s1o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L42)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Removed. 
___
*[pkg/sql/row/row_converter.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU60NwAjXfPFORdcr5:-MCgrDCyBjbnRbs8r64H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L56)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Please take a look at https://github.com/cockroachdb/cockroach/pull/51486/files
In particular, we don't need to us fn.Func.String().
Func is a resolved function.  
resolvedFnName := fn.Func.FunctionReference.(*tree.FunctionDefinition).Name
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8Hwe0N1wKiJO_IUl:-MCgrGKuCQ2IMpMcsnfO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L84)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

wrap long lines please?
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8MiABpuw6s22xwEL:-MCgrWrn5XLFaSWBJ4s7:b51f0ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L104)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
> 	if v.err != nil {
> 		return nil, unsafeExpressionError(v.err, "walking", expr.String())
> 	}
> 	datum, err := newExpr.(tree.TypedExpr).Eval(evalCtx)
> 	if err != nil {
> 		return nil, unsafeExpressionError(err, "eval", expr.String())
> 	}
> ```
please take a look at my PR.  This is not needed.  Please add comments on the importDefaultExprVisitor to indicate that it must be invoked on the typed expression.

I've made some changes to this method -- please incorporate them.
</blockquote></details>

Hmm I'm not sure if I understand this comment -- it looks like your PR still has the last `Eval(evalCtx)` line there. I'm guessing that the intention is to move it to be evaluated at `NewDatumRowConverter` to (potentially) accommodate the fact that the evaluation of expression should be delayed to `Row()` stage for volatile expression. 

I've added the appropriate comments on the definition of `importDefaultExprVisitor`. 
___
*[pkg/sql/row/row_converter.go, line 290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCUA8PN7gFxC8XMq9X5:-MCgslFQ1kopL0o4pKi5:b-9kdo5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L290)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

we probably don't need defaultExprs now, do we?
</blockquote></details>

Yes it looks like `defaultCache` suffices. 


<!-- Sent from Reviewable.io -->

2020-07-20 18:25 UTC, miretskiy approved these changes
Thanks for doing this -- nice comments!

I'm giving you <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> , with few more comments.  Please make sure get one from @pbardea  as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MChSvnE-8Vnvep4MI1h:bmnmtsz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCU8MiABpuw6s22xwEL:-MChLXCz1cemnrejr9Wj:b-doe2ff) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L104)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Hmm I'm not sure if I understand this comment -- it looks like your PR still has the last `Eval(evalCtx)` line there. I'm guessing that the intention is to move it to be evaluated at `NewDatumRowConverter` to (potentially) accommodate the fact that the evaluation of expression should be delayed to `Row()` stage for volatile expression. 

I've added the appropriate comments on the definition of `importDefaultExprVisitor`. 
</blockquote></details>

I do have Eval -- as a demo. What I meant is that, *this* pr probably doesn't need to evaluate anything in the Row() function.  Though, I think you mentioned that we might still have to do it (pgdump format?) Anyway, we should make sure that those expressions evaluated only once.
___
*[pkg/sql/row/row_converter.go, line 270 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChSGnK-TLhtKWNQrCA:-MChLrFK3smfvQZVhnjW:bcy6hf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L270)):*
> ```Go
> 	VisibleColTypes       []*types.T
> 	defaultCache          []tree.TypedExpr
> 	defaultUnsafeErr      []error
> ```

We probably would need to rework this.  This array based approach is getting
a bit cumbersome.

If you want to get rid of defaultUnsafeErr array, what you can do is introduce a "typed expression" that evaluates to error.  Something like this:

```
type errExpr struct {
	tree.Datum
	err error
}

var _ tree.TypedExpr = &errExpr{}

func (e *errExpr) Eval(_ *tree.EvalContext) (tree.Datum, error) {
	return nil, e.err
}
```

Then, inside NewRowCOnverter you will get an error from sanitize exprs, and wrap that error in errExpr.  If you call eval on that, you'll get back your original error.

It's up to you if you want to do this, and remove defaultUnsafeErr member.  Perhaps chat w/ @pbardea  on the merits of this.
___
*[pkg/sql/row/row_converter.go, line 389 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChOdAV-GMfho9pJcgu:-MChOdAV-GMfho9pJcgv:bjt4xty) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L389)):*
> ```Go
> 					// call the user out at this stage: targeted columns may not have been
> 					// identified now (e.g. "IMPORT PGDUMP...") and we want to throw an error
> 					// only at the "Row" stage when the targeted columns have been identified.
> ```

Nice comment -- thanks.
___
*[pkg/sql/row/row_converter.go, line 395 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChM1023Wg0ltSfbCpL:-MChM1023Wg0ltSfbCpM:b-kz4rpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L395)):*
> ```Go
> 					// so it's okay for defaultCache to be evaluated here. However, when we add support for
> 					// unique_rowid, it changes for every row and therefore can no longer be evaluated right away.
> 					// We therefore need a flag to determine when we can evaluate here.
> ```

please wrap long comments (here an above)


<!-- Sent from Reviewable.io -->

2020-07-20 20:05 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2684 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCgaFoEE3eZsBo8ghHA:-MChk9Su2Dx7_1MUcTj3:b4k5vyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/ccl/importccl/import_stmt_test.go#L2684)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Test cases with some casting and nesting of builtins. Also test cases like testing that the override name is case insensitive and methods like `pg_catalog.now()`.  Also negative cases where we throw errors.
</blockquote></details>

Added most test cases in #51486 (in this current timestamp scope and a bunch of other unsupported ones), with an addition of a deep nesting with `random()` in an inner layer, and omission of `now() + 1 now()` as integer as this is harder to verify the correctness using `minTs < now < maxTs` test. 
___
*[pkg/sql/row/row_converter.go, line 270 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChSGnK-TLhtKWNQrCA:-MChl5AvC_D5gQTOGgB-:b59o0xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L270)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

We probably would need to rework this.  This array based approach is getting
a bit cumbersome.

If you want to get rid of defaultUnsafeErr array, what you can do is introduce a "typed expression" that evaluates to error.  Something like this:

```
type errExpr struct {
	tree.Datum
	err error
}

var _ tree.TypedExpr = &errExpr{}

func (e *errExpr) Eval(_ *tree.EvalContext) (tree.Datum, error) {
	return nil, e.err
}
```

Then, inside NewRowCOnverter you will get an error from sanitize exprs, and wrap that error in errExpr.  If you call eval on that, you'll get back your original error.

It's up to you if you want to do this, and remove defaultUnsafeErr member.  Perhaps chat w/ @pbardea  on the merits of this.
</blockquote></details>

I haven't done any change here now, but my take is that this "typed expression" would look clean and could potentially save space by having one fewer array to store: after all, one of `Cache` and `UnsafeErr` is gonna be nil. 

A drawback that I could think of is that it will be less intuitive for code readers when we evaluate this expression at the `Row()` stage as it might not be clear that the error returned is due to unsafe expression. But we could get this around by doing something like: 
```
switch expr := c.defaultCache[i].(type) {
case tree.Datum:
	c.Datums[i] = expr
case errExpr:
	return expr.err // Possibly include some error wrapping
default:
	datum, err := expr.Eval(c.EvalCtx)
	if err != nil {
		return errors.Wrapf(
			err, "error evaluating default expression %q", col.DefaultExprStr())
	}
	c.Datums[i] = datum
}
```


<!-- Sent from Reviewable.io -->

2020-07-20 20:43 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 270 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChSGnK-TLhtKWNQrCA:-MChxhY74mLzgr4D6kwK:b-abcwzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L270)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I haven't done any change here now, but my take is that this "typed expression" would look clean and could potentially save space by having one fewer array to store: after all, one of `Cache` and `UnsafeErr` is gonna be nil. 

A drawback that I could think of is that it will be less intuitive for code readers when we evaluate this expression at the `Row()` stage as it might not be clear that the error returned is due to unsafe expression. But we could get this around by doing something like: 
```
switch expr := c.defaultCache[i].(type) {
case tree.Datum:
	c.Datums[i] = expr
case errExpr:
	return expr.err // Possibly include some error wrapping
default:
	datum, err := expr.Eval(c.EvalCtx)
	if err != nil {
		return errors.Wrapf(
			err, "error evaluating default expression %q", col.DefaultExprStr())
	}
	c.Datums[i] = datum
}
```
</blockquote></details>

No... If you make it into errExpr -- you handle it just like your regular expression.
You evaluate it -- and you get back an error.


<!-- Sent from Reviewable.io -->

2020-07-20 21:35 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 270 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MChSGnK-TLhtKWNQrCA:-MCi8HACENvyO9cQKeH7:b-f5n0vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0abd2d267d629678bd00418ad35f81807e774126/pkg/sql/row/row_converter.go#L270)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

No... If you make it into errExpr -- you handle it just like your regular expression.
You evaluate it -- and you get back an error.
</blockquote></details>

Added a comment below, if that makes it clearer.
___
*[pkg/sql/row/row_converter.go, line 486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCi7tmxC9-htU5rUx_Q:-MCi7tmxC9-htU5rUx_R:b9ownjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L486)):*
> ```Go
> 		col := &c.cols[i]
> 		if _, ok := c.IsTargetCol[i]; !ok && !col.Hidden && col.DefaultExpr != nil {
> 			switch expr := c.defaultCache[i].(type) {
> ```

Calling `Eval` on a Datum just returns the datum. So here we can do:

```
datum, err := c.defaultCache[i].Eval(c.EvalCtx)
if err != nil {
	return errors.Wrapf(
		err, "error evaluating default expression %q", col.DefaultExprStr())
}
c.Datums[i] = datum

```


<!-- Sent from Reviewable.io -->

2020-07-20 22:39 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiNNln3gn_-wSvi3Uj:-MCiNNln3gn_-wSvi3Uk:bpmwkcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L93)):*
> ```Go
> 		ctx, expr, targetType, "import_default", &semaCtx, tree.VolatilityImmutable)
> 	if err == nil {
> 		return typedExpr.Eval(evalCtx)
> ```

should we just return typedExpr, as the comment says?
You're eval-ing at the call site anyway.


<!-- Sent from Reviewable.io -->

2020-07-20 22:43 UTC, pbardea approved these changes
This is looking much nicer!

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> mod the last few comments I left. I would like to see the `switch expr := c.defaultCache[i].(type) {` cleaned up since we're almost there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-:-MCiOEoICI78ZytWYYzT:b-d8z5vo)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Anzoteh96, @knz, @miretskiy, and @rohany)

___
*[pkg/sql/row/row_converter.go, line 26 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiN5E499cULCKI-FUa:-MCiN5E499cULCKI-FUb:b5hlemd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L26)):*
> ```Go
> )
> 
> var supportedImportFunctions = map[string]struct{}{
> ```

A brief note here about how `IMPORT` supports all default expressions with maximum volatility Immutable + a set of explicitly allowed other functions would be useful. It would also be good to mention that this is the case since IMPORT needs to generate the exact same values for ever row, even on retries.
___
*[pkg/sql/row/row_converter.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiMZ8BBQdhla7ZgsVi:-MCiMZ8BBQdhla7ZgsVj:b-qdl7ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L27)):*
> ```Go
> 
> var supportedImportFunctions = map[string]struct{}{
> 	"current_date":          {},
> ```

A brief comment here (above all the time methods) explaining that we support these methods since we set the statement and transaction timestamp of an import to be the write timestamp.
___
*[pkg/sql/row/row_converter.go, line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiLDfn3X0HThbnYSKJ:-MCiLDfn3X0HThbnYSKK:b-igxaxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L56)):*
> ```Go
> 
> // importDefaultExprVisitor must be invoked on a typed expression.
> type importDefaultExprVisitor struct {
> ```

Could we add a brief comment here explaining that this visitor walks the tree and ensures any expr that is more volatile than `volatility.Immutable` is one that import explicitly supports?
___
*[pkg/sql/row/row_converter.go, line 408 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiHZO8-sbzavykcAK6:-MCiHZOA5zy7eZ1Be76D:b-587ykv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L408)):*
> ```Go
> 					// This expression may not be safe for import but we don't want to
> 					// call the user out at this stage: targeted columns may not have
> 					// been identified now (e.g. "IMPORT PGDUMP...") and we want to
> ```

It should be noted that PGDUMP is not expected to produce an INSERT statement which does not contain all of the columns of the table. Caching the error should only be used in the case that we're importing output from `shp2pgsql`. In particular, it will create schemas with a `SERIAL` column type and the `INSERT` statements will not offer a value. Does this sound right, or are there other use cases that you had in mind? When looking at other formats, I'm hesitant to say that we support those formats since the semantics are not well defined.

I think this is find to keep for now, but we should be mindful when we actually expect this case to be reached.


<!-- Sent from Reviewable.io -->

2020-07-21 00:10 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51390)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Anzoteh96, @knz, @miretskiy, @pbardea, and @rohany)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCHh-6c9qcv-gHbxaQ7:-MCichUdDRhUj-yzvCJ4:brac33k) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b5a2006a04deebc17257fb018a27f4298dd100/pkg/ccl/importccl/import_stmt_test.go#L2639)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just want to make sure this comment is not lost along the way.  This is new code you're adding.
</blockquote></details>

As this is coming to a close, it looks like we'll leave it here as it is and fix this (along with the possible additional tests) in #51468. 
___
*[pkg/sql/row/row_converter.go, line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCgYokw-brA_KkDM6WT:-MCidBTV9WjpjjkkP8XT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d4bd435c818735bd47dec75d979d6e64067ad7/pkg/sql/row/row_converter.go#L92)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

In addition, the comments on Yevgeniy's branch are also useful and would be good to incorporate.
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 26 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiN5E499cULCKI-FUa:-MCid0ntCMiwHZ6r7pvX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L26)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

A brief note here about how `IMPORT` supports all default expressions with maximum volatility Immutable + a set of explicitly allowed other functions would be useful. It would also be good to mention that this is the case since IMPORT needs to generate the exact same values for ever row, even on retries.
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 27 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiMZ8BBQdhla7ZgsVi:-MCid2Q5370ZU7B329aO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L27)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

A brief comment here (above all the time methods) explaining that we support these methods since we set the statement and transaction timestamp of an import to be the write timestamp.
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiLDfn3X0HThbnYSKJ:-MCid6Sr0pwstoXyQxGs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L56)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Could we add a brief comment here explaining that this visitor walks the tree and ensures any expr that is more volatile than `volatility.Immutable` is one that import explicitly supports?
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiNNln3gn_-wSvi3Uj:-MCid99U4AI3_1xSgnou:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L93)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should we just return typedExpr, as the comment says?
You're eval-ing at the call site anyway.
</blockquote></details>

Done.
___
*[pkg/sql/row/row_converter.go, line 408 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCiHZO8-sbzavykcAK6:-MCieeUjCubIlPPKAFY9:b4jlll0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L408)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It should be noted that PGDUMP is not expected to produce an INSERT statement which does not contain all of the columns of the table. Caching the error should only be used in the case that we're importing output from `shp2pgsql`. In particular, it will create schemas with a `SERIAL` column type and the `INSERT` statements will not offer a value. Does this sound right, or are there other use cases that you had in mind? When looking at other formats, I'm hesitant to say that we support those formats since the semantics are not well defined.

I think this is find to keep for now, but we should be mindful when we actually expect this case to be reached.
</blockquote></details>

Yes I think this should support the case of `shp2pgsql` (though we'll need to perform overloading for sure, when we get there). 

One thing that could be tricky is a _default value change_ of column within the PGDUMP file itself (via `ALTER TABLE`), in which case the `defaultCache` will need to be updated accordingly. 
___
*[pkg/sql/row/row_converter.go, line 486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51390#-MCi7tmxC9-htU5rUx_Q:-MCif4hB35nx8c3rwJZR:b-81y6wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f9272c9f0a77e2078e3a0b1b7af2ef198a205f/pkg/sql/row/row_converter.go#L486)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Calling `Eval` on a Datum just returns the datum. So here we can do:

```
datum, err := c.defaultCache[i].Eval(c.EvalCtx)
if err != nil {
	return errors.Wrapf(
		err, "error evaluating default expression %q", col.DefaultExprStr())
}
c.Datums[i] = datum

```
</blockquote></details>

Done. I was initially concerned with this approach because we want to evaluate immutable expressions only once per import (instead of one per row), but later realized that an identity map wouldn't really hurt performance. 


<!-- Sent from Reviewable.io -->

2020-07-21 12:46 UTC, Anzoteh96 commented
Closing this to move on to supporting other default expressions. 

TFTR! bors=miretskiy,pbardea

2020-07-21 13:02 UTC, Anzoteh96 commented
Closing this one to move on to supporting other default expressions. TFTR! 

bors r+

2020-07-21 13:41 UTC, merged