importccl: cleanup test structure for supporting IMPORT default
cockroachdb/cockroach pull request #51468
Opened 2020-07-15 17:04 UTC by Anzoteh96

Previously, all the tests for supporting default expressions for IMPORT are inside the `TestImportIntoCSV` function. As default columns should also be supported in other formats, this PR moves these tests outside `TestImportIntoCSV` and instead have a standalone `TestImportDefault` function. In addition, having a standalone `TestImportDefault` should be justified given the scope of importing default expression (the different types of functions, along with the different file formats).

Release note: None

2020-07-16 02:04 UTC, pbardea requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @dt)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCKL-rX-LzYV1IeCbNT:-MCKL-rX-LzYV1IeCbNU:b6egwk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abc1d17401c7644d296e82c79e11e60b52a4a30/pkg/ccl/importccl/import_stmt_test.go#L2930)):*
> ```Go
> 
> 		}
> 		t.Run("is-target-with-null-data", func(t *testing.T) {
> ```

It seems to me that we could move all of these to the test-cases above by changing the evaluation expression in that test to include the nullif. That would clean these up quite a bit.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 3015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCKLRBWDqFwINgnW9qO:-MCKLRBWDqFwINgnW9qP:b-fa886z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abc1d17401c7644d296e82c79e11e60b52a4a30/pkg/ccl/importccl/import_stmt_test.go#L3015)):*
> ```Go
> 	})
> 
> 	t.Run("non-csv-formats", func(t *testing.T) {
> ```

Hmm, we currently only [document](https://www.cockroachlabs.com/docs/stable/import-into.html) supporting CSV and AVRO for IMPORT INTO. We should prioritize ensuring that this works for Avro files. But again, I think that we could fold this test into the test cases above.


<!-- Sent from Reviewable.io -->

2020-07-16 13:40 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2930 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCKL-rX-LzYV1IeCbNT:-MCMosAeARpcI75kZ1Jn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abc1d17401c7644d296e82c79e11e60b52a4a30/pkg/ccl/importccl/import_stmt_test.go#L2930)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It seems to me that we could move all of these to the test-cases above by changing the evaluation expression in that test to include the nullif. That would clean these up quite a bit.
</blockquote></details>

Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 3015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCKLRBWDqFwINgnW9qO:-MCMp2G25N0GdiXg8UAM:bdqfbxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abc1d17401c7644d296e82c79e11e60b52a4a30/pkg/ccl/importccl/import_stmt_test.go#L3015)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Hmm, we currently only [document](https://www.cockroachlabs.com/docs/stable/import-into.html) supporting CSV and AVRO for IMPORT INTO. We should prioritize ensuring that this works for Avro files. But again, I think that we could fold this test into the test cases above.
</blockquote></details>

I think this line (https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/import_stmt_test.go#L1089) did show that the `IMPORT INTO` from all four formats should be supported. 

As for the second half of the comment -- my intention / reasoning is to have each category handling different things (so the large chunk of the test cases above are for format, like NULL, target or not, etc), so this section is exclusively for non-csv formats (eventually we will have all three PGDUMP, AVRO, MySQL here). Let me think again...


<!-- Sent from Reviewable.io -->

2020-07-16 16:25 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3015 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCKLRBWDqFwINgnW9qO:-MCNRIKQ9yP58pPvbqgB:b1pttc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3abc1d17401c7644d296e82c79e11e60b52a4a30/pkg/ccl/importccl/import_stmt_test.go#L3015)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I think this line (https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/import_stmt_test.go#L1089) did show that the `IMPORT INTO` from all four formats should be supported. 

As for the second half of the comment -- my intention / reasoning is to have each category handling different things (so the large chunk of the test cases above are for format, like NULL, target or not, etc), so this section is exclusively for non-csv formats (eventually we will have all three PGDUMP, AVRO, MySQL here). Let me think again...
</blockquote></details>

Added everything to the map of the test cases. Will leave out AVRO and MySQL (and attend to them later) as that would involve a bit of fixing. 


<!-- Sent from Reviewable.io -->

2020-07-21 14:29 UTC, Anzoteh96 commented
Incorporated changes based on #51390, RFAR!

2020-07-21 15:12 UTC, pbardea approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51468)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Anzoteh96 and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 2984 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51468#-MCluzsu17P6ZgUpTHiT:-MCluzsu17P6ZgUpTHiU:b-kn3ls7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef64cdfea80617b4020ef79abb587c6c66ec8cb3/pkg/ccl/importccl/import_stmt_test.go#L2984)):*
> ```Go
> 		create          string
> 		targetCols      string
> 		expectedResults [][]string
> ```

A comment here saying that we expect one of `expectedResults` or `expectedError` to be set per test case would be useful. 

Also nit: I find it easier to parse of the "expected" properties were at the end of the struct so that we have 2 groups: the "inputs" to the tests and the expected "outputs".


<!-- Sent from Reviewable.io -->

2020-07-21 16:56 UTC, Anzoteh96 commented
Did the change as suggested. TFTR!

bors r=pbardea

2020-07-21 17:47 UTC, Anzoteh96 commented
bors r+

2020-07-22 00:39 UTC, Anzoteh96 commented
bors r+

2020-07-22 02:03 UTC, merged