rowflow: make routers propagate errors to all non-closed streams
cockroachdb/cockroach pull request #51518
Opened 2020-07-16 18:31 UTC by yuzefovich

This commit changes the way we propagate the errors in the hash router
so that the error metadata is sent on all non-closed streams.
Previously, we would be sending it over only the first non-closed stream
which could result in the processors on the same stage as that single
stream end to treat the absence of rows and errors as the input being
exhausted successfully, which is wrong because the input did encounter
an error.

I've confirmed that we don't have such a problem in the vectorized
engine because we use panic-catch mechanism of error propagation, and we
end up with the following sequence of events:
1. an operator encounters an error on any node (e.g. `colBatchScan`
encounters RWUI error on node 2). It is not an internal vectorized
error, so the operator will panic with `colexecerror.ExpectedError`.
2. the panic is caught by one of the catchers (it can be a parallel
unordered synchronizer goroutine, outbox goroutine, materializer)
3. that component will initiate the whole flow shutdown and will make
sure to send the error to the root materializer (which will then decide
whether it is ok to swallow that error).

Fixes: #51458.

Release note (bug fix): Previously, CockroachDB could return incorrect
results on query that encountered ReadWithinUncertaintyInterval error,
and this has been fixed.

2020-07-16 18:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51518)
<!-- Reviewable:end -->

2020-07-17 02:52 UTC, yuzefovich commented
I confirmed that this PR fixes https://github.com/cockroachlabs/support/issues/513, however, when forcing the vectorized execution (with `vectorize_row_count_threshold=0`) we occasionally get `ERROR: rpc error: code = Canceled desc = context canceled` instead of RWUI error. I think it probably has the same cause as the context cancellation issue that @asubiotto mentioned in #51375, and on a quick glance I didn't find the root cause of it.

I think we should still go ahead with this PR and backport the row-execution fix, and we can leave the vectorized context cancellation issue till later.

2020-07-22 20:22 UTC, yuzefovich commented
When this PR contains the commits from #51772, then I no longer see any issues on the customer's reproduction when vectorized engine is used. RFAL (only the last commit is in this PR).

2020-07-23 16:35 UTC, andreimatei commented
I'm sorry but I won't have time to look at this for a while. I'm happy to see it though!

2020-07-27 23:24 UTC, jordanlewis reviewed
Looks correct, but I have one request for clarity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-:-MDH_vau8qV1g0Q8HKDx:bnlugmp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowflow/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-MDH_eld591wEf2TCSNv:-MDH_eld591wEf2TCSNw:boutjz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eafafebc3be54ef99772c61f76431be3d6dd1a2/pkg/sql/rowflow/routers.go#L419)):*
> ```Go
> 	forwarded, holdingSema := false, false
> 
> 	for i := range rb.outputs {
> ```

I find this confusing. Can you have two cases at the top level, one for if there is an error (forward to all non closed streams) and one if there is not (forward to first non closed stream)?

It's hard to understand what's going on with the semaphore the way things are here, because of the fact that this loop is doing 2 different modes at once.


<!-- Sent from Reviewable.io -->

2020-07-28 00:14 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51518)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/rowflow/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-MDH_eld591wEf2TCSNv:-MDHl1trES7-qUaD9xw2:b-jmkyg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eafafebc3be54ef99772c61f76431be3d6dd1a2/pkg/sql/rowflow/routers.go#L419)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I find this confusing. Can you have two cases at the top level, one for if there is an error (forward to all non closed streams) and one if there is not (forward to first non closed stream)?

It's hard to understand what's going on with the semaphore the way things are here, because of the fact that this loop is doing 2 different modes at once.
</blockquote></details>

Done.

I'm a little unclear on the usage of `rb.semaphore` - in the error case, initially I thought it would be safer to acquire and release it for each non-closed stream, but now I think it should be ok to acquire and release it only once, outside of the loop. Thoughts?


<!-- Sent from Reviewable.io -->

2020-07-28 18:51 UTC, jordanlewis requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51518)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[pkg/sql/rowflow/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-MDH_eld591wEf2TCSNv:-MDLLe0C7epR0sC6X4qV:b-1f3658) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eafafebc3be54ef99772c61f76431be3d6dd1a2/pkg/sql/rowflow/routers.go#L419)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Done.

I'm a little unclear on the usage of `rb.semaphore` - in the error case, initially I thought it would be safer to acquire and release it for each non-closed stream, but now I think it should be ok to acquire and release it only once, outside of the loop. Thoughts?
</blockquote></details>

The semaphore is designed to make it so that if all of the outputs are blocked, we have to stop pushing to any of the outputs. I think your proposal makes sense, because it won't start its push loop until at least one is available, and then once it starts the push loop, if no other outputs are available, nobody else can enter the semaphore.


<!-- Sent from Reviewable.io -->

2020-07-28 18:51 UTC, jordanlewis approved these changes
Oops, I didn't mean to reject this. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-:-MDLkxjz9soU8O1OEF1g:b-2uh4ua)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-07-28 19:03 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-:-MDLnf6o-WQiZsv8Nqm3:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/rowflow/routers.go, line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51518#-MDH_eld591wEf2TCSNv:-MDLncfUDtQU5uKTyUHy:b-nozm7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eafafebc3be54ef99772c61f76431be3d6dd1a2/pkg/sql/rowflow/routers.go#L419)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

The semaphore is designed to make it so that if all of the outputs are blocked, we have to stop pushing to any of the outputs. I think your proposal makes sense, because it won't start its push loop until at least one is available, and then once it starts the push loop, if no other outputs are available, nobody else can enter the semaphore.
</blockquote></details>

Cool, thanks for checking.


<!-- Sent from Reviewable.io -->

2020-07-28 21:23 UTC, merged