cmd/internal: elide issue assignee based on authorship
cockroachdb/cockroach pull request #51660
Opened 2020-07-21 19:20 UTC by irfansharif

Touches https://github.com/cockroachdb/cockroach/issues/51653. This is a
bit controversial because it effectively also disconnects the roachtest
ownership from being used in the assignee field, but I want to try and
see what happens anyway.

Release note: None

2020-07-21 19:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51660)
<!-- Reviewable:end -->

2020-07-21 19:21 UTC, jordanlewis requested changes
Thumbs down on this because AFAIK it will also affect non-roachtest failures, and I don't think we've decided that those are bad yet as well.

Would you be able to only elide the issue assignment if you detect that it's `roachtest` itself failing?

2020-07-21 20:12 UTC, irfansharif reviewed
Wanna take another look? Should be just roachtests now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51660#-:-MCn-C7PBiffrcpa0Uo7:bwrar8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)



<!-- Sent from Reviewable.io -->

2020-07-22 16:28 UTC, irfansharif reviewed
Reviewing my own PR here but LGTM, let's get another pair of eyes on it given @tbg is out for a few days and get it in?

2020-07-22 16:28 UTC, irfansharif commented on pkg/cmd/roachtest/test_registry.go
> +		TriageColumnID: 8532151,
Nice jankiness. Maybe just add a comment next to each one naming the specific board/column.

2020-07-24 16:09 UTC, jordanlewis approved these changes
LGTM :trollface:

2020-07-24 16:10 UTC, irfansharif commented
bors r+

2020-07-24 20:00 UTC, irfansharif commented
bors r+

2020-07-24 20:56 UTC, merged