cloud: add statefulset config for EKS multi-region
cockroachdb/cockroach pull request #51775
Opened 2020-07-22 16:31 UTC by taroface

This StatefulSet config is meant for use with the EKS multi-region docs (WIP).

- Added an `initContainer` that determines the AZ of each pod.
- Added `namespace` field to fill in with a region-appropriate namespace.
- Modified `--join` and `--locality` in the start command for the user to customize with namespace/region names. I am unclear on whether the values here need to match the `namespace` defined for the cluster above.
- Added the memory/CPU requests & limits block that is in the single-region configs (but not the current multi-region config).

2020-07-22 16:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51775)
<!-- Reviewable:end -->

2020-08-03 23:22 UTC, taroface commented on cloud/kubernetes/multiregion/cockroachdb-statefulset-secure-eks.yaml
> +            # --join cockroachdb-0.cockroachdb.<cluster-namespace-1>,cockroachdb-1.cockroachdb.<cluster-namespace-1>,cockroachdb-2.cockroachdb.<cluster-namespace-1>,cockroachdb-0.cockroachdb.<cluster
Taking into account [this comment](https://github.com/cockroachdb/docs/issues/3395#issuecomment-667215351) on the --join flag, am I safe to remove one node (e.g. `cockroachdb-2`) from each region here?

2020-08-11 04:40 UTC, DuskEagle requested changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/51775#-MEQnFgwEXMO8uLMaXSM:-MEQnFgwEXMO8uLMaXSN:bpu5mtm) (no related file):*
The Kubernetes manifests look good to me, as long as there's other documentation to go along with it. It might be helpful to add a README about how to use these manifests. I realize there might be some text on the docs site, but if people find these manifests without going through the docs site, they might be confused on how to use them.

Relatedly, it might be nice to create a separate directory for the multiregion EKS manifests, to separate it from the existing manifests in this directory.

---
___
*[cloud/kubernetes/multiregion/cockroachdb-statefulset-secure-eks.yaml, line 253 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/51775#-MCrMPQpeDcRzA_1DvZm-r4-253:-MEQnOnL6pShdzSlP_MH:b-8a1eh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f273488cb7cde883b74263e5cbc5a531a26ba97/cloud/kubernetes/multiregion/cockroachdb-statefulset-secure-eks.yaml#L253)):*
<details><summary><i>Previously, taroface (Ryan Kuo) wrote…</i></summary><blockquote>

Taking into account [this comment](https://github.com/cockroachdb/docs/issues/3395#issuecomment-667215351) on the --join flag, am I safe to remove one node (e.g. `cockroachdb-2`) from each region here?
</blockquote></details>

You're definitely safe to, though I also think it's fine to leave it.


<!-- Sent from Reviewable.io -->

2020-08-14 03:00 UTC, taroface commented
@DuskEagle TFTR! I moved the files and added a README, also slightly updating the existing README in `multiregion`.

2020-08-19 21:19 UTC, DuskEagle approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle and @taroface)

___
*[cloud/kubernetes/multiregion/eks/README.md, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/51775#-MF7_aI79kpUo57VmOdu:-MF7_aI79kpUo57VmOdv:b-ziea2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/83407f9849d5d9e912b8f149a92350ca9e8d7ca1/cloud/kubernetes/multiregion/eks/README.md#L73)):*
> ```Markdown
> - `region2` and `region3` with the namespaces in which the CockroachDB pods will run in the other 2 regions.
> 
> - `ip1`, `ip2`, and `ip3` with the IP addresses of the EKS instances in the region.
> ```

This should be the IP addresses of the Network Load Balancerss in the other regions, not the EKS VMs.


<!-- Sent from Reviewable.io -->

2020-08-20 21:17 UTC, taroface commented
bors r+

2020-08-21 00:33 UTC, merged