sql: add SHOW TRANSACTIONS
cockroachdb/cockroach pull request #51902
Opened 2020-07-27 04:09 UTC by jordanlewis

Release note (sql change): add the SHOW TRANSACTIONS statement, similar
to SHOW SESSIONS and variants. It shows the currently active
transactions in the node or cluster, and some information about them.

2020-07-27 04:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/51902)
<!-- Reviewable:end -->

2020-08-03 20:02 UTC, awoods187 commented
Anything preventing a merge here?

2020-08-04 01:27 UTC, rohany commented on pkg/sql/delegate/show_transactions.go
> +	table := `crdb_internal.node_transactions`
Nit -- we preface this with "".crdb_internal... so that nothing goes wrong if we aren't connected to a database and try and execute this

2020-08-04 01:27 UTC, rohany commented on pkg/sql/parser/parse_test.go
> +		{`SHOW TRANSACTIONS`, `SHOW CLUSTER TRANSACTIONS`},
also add a test in `TestContextualHelp`

2020-08-13 21:06 UTC, rohany approved these changes
code lgtm

2020-08-13 22:00 UTC, jordanlewis commented
Sample output:

```
root@127.0.0.1:56739/defaultdb> show transactions;
  node_id |                  id                  | application_name | num_stmts | num_retries | num_auto_retries
----------+--------------------------------------+------------------+-----------+-------------+-------------------
        1 | 0d39f809-20f2-4baf-af64-dbbd2f0be0d1 | $ cockroach demo |         1 |           0 |                0
(1 row)
```

2020-08-14 16:16 UTC, solongordon requested changes
The fact that SHOW TRANSACTIONS only shows transactions for the current node seems confusing to me. I think a naive user would assume the output includes all transactions and might not realize that other nodes were getting filtered out. Should we consider making the default to show transactions from all nodes but still supporting `SHOW LOCAL TRANSACTIONS` for the local node?

> Reviewed 4 of 15 files at r4, 2 of 7 files at r5, 3 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-:-MEhj-BT1vFfBPduOecm:b-kwpqzb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/conn_executor_exec.go, line 213 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-MEhi33ODc_8ax6C-w10:-MEhi33ODc_8ax6C-w11:b-4cs1ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f41a90530b702809dc74b442fe8540cd25ec968/pkg/sql/conn_executor_exec.go#L213)):*
> ```Go
> 		}
> 	}()
> 	ex.state.mu.stmtCount++
> ```

Do you think this should get reset if the transaction is retried? Otherwise it can climb far beyond the number of statements the user submitted, which seems confusing.


<!-- Sent from Reviewable.io -->

2020-08-14 16:18 UTC, jordanlewis commented
I think `SHOW TRANSACTIONS` should show all of the cluster's transactions by default. It gets aliased to `SHOW CLUSTER TRANSACTIONS` like the other `SHOW FOOs` do, I think. Maybe I missed something?

2020-08-14 16:20 UTC, solongordon reviewed
Oh I misread something, cheerfully withdrawn!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-:-MEhlE513YV8ENCnTT9f:bdctxni)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)



<!-- Sent from Reviewable.io -->

2020-08-14 17:24 UTC, RaduBerinde reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I like it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-:-MEhz0T15wedFvbH6yzz:b779t6o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/delegate/show_transactions.go, line 31 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-MEhxyUv6TEI1_YGO6Cg:-MEhxyUv6TEI1_YGO6Ch:bk97iiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f41a90530b702809dc74b442fe8540cd25ec968/pkg/sql/delegate/show_transactions.go#L31)):*
> ```Go
> 
> func (d *delegator) delegateShowTransactions(n *tree.ShowTransactions) (tree.Statement, error) {
> 	const query = `SELECT node_id, id, application_name, num_stmts, num_retries, num_auto_retries FROM `
> ```

`id` is kind of obscure. Maybe it's more clear in the context of the internal table, but I'd make it `txn_id` her.
___
*[pkg/sql/parser/sql.y, line 4083 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-MEhygem99lFpg1qjiDR:-MEhygem99lFpg1qjiDS:b-c4yves) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f41a90530b702809dc74b442fe8540cd25ec968/pkg/sql/parser/sql.y#L4083)):*
> ```Yacc
> | show_trace_stmt           // EXTEND WITH HELP: SHOW TRACE
> | show_transaction_stmt     // EXTEND WITH HELP: SHOW TRANSACTION
> | show_transactions_stmt    // EXTEND WITH HELP: SHOW TRANSACTIONS
> ```

It's odd, if I try completion I get this:
```
root@127.0.0.1:40435/movr> show ??
Suggestion:
Command:     SHOW
Syntax:
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE SHOW TRANSACTION, SHOW USERS,
SHOW LAST QUERY STATISTICS, SHOW SCHEDULES
```
___
*[pkg/sql/parser/sql.y, line 4585 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-MEhzSICEQ2ngzU1hM3b:-MEhzSICEQ2ngzU1hM3c:b-bj4rol) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f41a90530b702809dc74b442fe8540cd25ec968/pkg/sql/parser/sql.y#L4585)):*
> ```Yacc
> // %Help: SHOW TRANSACTIONS - list open client transactions
> // %Category: Misc
> // %Text: SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
> ```

This should describe the variants. In particular it was not at all obvious what `ALL` does and that `CLUSTER` is the default (maybe it should be just `SHOW [ALL] [LOCAL] TRANSACTIONS`?)


<!-- Sent from Reviewable.io -->

2020-08-14 17:47 UTC, awoods187 commented
I'm very excited about this! I filed this issue for extending it even further https://github.com/cockroachdb/cockroach/issues/52826

2020-08-25 17:34 UTC, rohany commented
What's the status here @jordanlewis

2020-08-25 20:42 UTC, jordanlewis commented
I can't figure out why the bug Radu find is happening with tab completion...

2020-08-25 20:47 UTC, rohany commented
You need to update here in sql.y (around line 4100)

```
// %Help: SHOW
// %Category: Group	// %Category: Group
// %Text:	// %Text:
// SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,	// SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
// SHOW CREATE, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW	// SHOW CREATE, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
// PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,	// PARTITIONS, SHOW JOBS, SHOW QUERIES, SHOW RANGE, SHOW RANGES,
// SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,	// SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
// SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE SHOW TRANSACTION, SHOW USERS,	// SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE SHOW TRANSACTION, SHOW USERS,
// SHOW LAST QUERY STATISTICS, SHOW SCHEDULES	// SHOW LAST QUERY STATISTICS, SHOW SCHEDULES
show_stmt:	show_stmt:
```

2020-08-25 20:55 UTC, jordanlewis commented
Oh, duh. thx

2020-08-26 18:15 UTC, jordanlewis commented
@solongordon PTAL, I fixed the statement count reset thing

2020-08-27 15:04 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51902#-:-MFkRb8s7Cqy0ESoOB1p:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @solongordon)



<!-- Sent from Reviewable.io -->

2020-08-27 15:05 UTC, jordanlewis commented
bors r+

2020-08-27 17:25 UTC, merged