sql: fix connection shutdown with temp tables
cockroachdb/cockroach pull request #52148
Opened 2020-07-30 17:05 UTC by jordanlewis

Previously, shutting down a connection with an open transaction that had
active temp tables caused deadlocks or general brokenness. This was
because the table cleanup was done inside of the open transaction.

This commit moves the table cleanup to be after the user transaction is
shut down.

Fixes #52147

Release note (bug fix): prevent deadlocks on connection close with an
open user transaction and temp tables.

2020-07-30 17:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52148)
<!-- Reviewable:end -->

2020-07-31 03:02 UTC, otan commented
are we planning to backport this, good sir?

2020-07-31 03:03 UTC, otan reviewed
can we test this well in some way?

2020-07-31 18:09 UTC, jordanlewis commented
PTAL, added a test

2020-07-31 18:22 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> after you remove the debug print

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-:-MDa5z79-kyZGojCKi_X:bu1aey1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @otan)

___
*[pkg/sql/temporary_schema_test.go, line 251 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDa5tR97a6ENo5KB2ux:-MDa5tRB4izvHeHGypyp:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f4fbfdbed064eda7892d9a6d9075d0824f90fa6/pkg/sql/temporary_schema_test.go#L251)):*
> ```Go
> 	require.NoError(t, err)
> 	go func() {
> 		fmt.Println("Hi2")
> ```

remove


<!-- Sent from Reviewable.io -->

2020-07-31 18:26 UTC, otan approved these changes

2020-07-31 18:36 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/temporary_schema_test.go, line 223 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDa7OMFBMX7Mqcmg7Ub:-MDa7OMFBMX7Mqcmg7Uc:bosmu86) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5731d77870513f0f8c4ba5c6bc831fbd60e062/pkg/sql/temporary_schema_test.go#L223)):*
> ```Go
> 
> // Test that the temporary object cleaner doesn't break with a connection
> // that gets uncleanly shutdown. See issue #52147.
> ```

please put more words in this comment, and consider dropping the link clickbait.
___
*[pkg/sql/temporary_schema_test.go, line 224 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDa7gOe2csIrHpP7kQE:-MDa7gOe2csIrHpP7kQF:b-jqp3e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5731d77870513f0f8c4ba5c6bc831fbd60e062/pkg/sql/temporary_schema_test.go#L224)):*
> ```Go
> // Test that the temporary object cleaner doesn't break with a connection
> // that gets uncleanly shutdown. See issue #52147.
> func TestTemporaryObjectCleanerUncleanShutdown(t *testing.T) {
> ```

please describe in words what this test will do. Following interactions between 3 sessions is hard.

But better yet, let's find a way to write this test with a single connection. Using a 2nd connection to observe whether the first connection deadlocked itself is not getting to the core of the issue. To prove the point, in order to write the test this way, you have to do a `create table` on c2 because doing a simple read would make c2 not actually give you any info. This is not explained in the test and... good luck explaining it. And even so, the test is unconvincing. Just because c2's create succeeds doesn't prove much about c1's deadlock.

Let's find a way to assert the that `connExecutor.run()` returned - that's what proves the absence of a deadlock. Let's make this a lower-level `connExecutor` test, forgetting about connections.
___
*[pkg/sql/temporary_schema_test.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDa82q0EHbXIQjVznAL:-MDa82q0EHbXIQjVznAM:b-muhk2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5731d77870513f0f8c4ba5c6bc831fbd60e062/pkg/sql/temporary_schema_test.go#L259)):*
> ```Go
> 	c3, err := db.Conn(ctx)
> 
> 	// Cancel the first session once the second session has started its work.
> ```

how do you know that the 2nd session started its work at this point?
___
*[pkg/sql/temporary_schema_test.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDa8Nex3qFqCfUxR0AC:-MDa8Nex3qFqCfUxR0AD:b-t2jrkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5731d77870513f0f8c4ba5c6bc831fbd60e062/pkg/sql/temporary_schema_test.go#L260)):*
> ```Go
> 
> 	// Cancel the first session once the second session has started its work.
> 	_, err = c3.ExecContext(ctx,
> ```

why this and not `c3.Close()`?


<!-- Sent from Reviewable.io -->

2020-07-31 18:47 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52148)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/temporary_schema_test.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDaBq3M7ZbmYz2QwBW1:-MDaBq3M7ZbmYz2QwBW2:b-t8fpdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed5731d77870513f0f8c4ba5c6bc831fbd60e062/pkg/sql/temporary_schema_test.go#L254)):*
> ```Go
> 		// This should hang until c1 is closed, but not further.
> 		// See issue #52147 for a deadlock that this is testing.
> 		require.NoError(t, err)
> ```

can't do `NoError` on goroutine


<!-- Sent from Reviewable.io -->

2020-08-01 12:59 UTC, andreimatei reviewed
Pushed a commit with the test. See if you like it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-:-MDe5cAu6MTk7DSYDaU8:bm7md0s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/conn_executor.go, line 841 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDe3Vo-61N2n_sMH_HN:-MDe3Vo-61N2n_sMH_HO:bpyehfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdf6ba0f908f562822348300597b9f435f478d1/pkg/sql/conn_executor.go#L841)):*
> ```Go
> 		// We'll cleanup the SQL txn by creating a non-retriable (commit:true) event.
> 		// This event is guaranteed to be accepted in every state.
> 		ev := eventNonRetriableErr{IsCommit: fsm.True}
> ```

pls take the opportunity to name this `ev` differently than the `ev` above which straddles it (that one is used below in the `resetExtraTxnState`). Call that one `txnEvent`.
___
*[pkg/sql/conn_executor.go, line 851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDe3PZP2qIUNjCjlF5t:-MDe3PZP2qIUNjCjlF5u:b-hclroy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdf6ba0f908f562822348300597b9f435f478d1/pkg/sql/conn_executor.go#L851)):*
> ```Go
> 	}
> 
> 	if err := ex.resetExtraTxnState(ctx, ex.server.dbCache, ev); err != nil {
> ```

move this stanza up with the state transition too pls; they belong together


<!-- Sent from Reviewable.io -->

2020-08-03 03:45 UTC, jordanlewis reviewed
Thanks for the test, it looks great. I removed my attempt, and took your suggestions for the variable name changes and code movement in conn_executor.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-:-MDmPlZU9LVOeO9kBe8O:bypzish)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @jordanlewis)

___
*[pkg/sql/conn_executor.go, line 841 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDe3Vo-61N2n_sMH_HN:-MDmOtfp2xAEs5afgQA0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdf6ba0f908f562822348300597b9f435f478d1/pkg/sql/conn_executor.go#L841)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls take the opportunity to name this `ev` differently than the `ev` above which straddles it (that one is used below in the `resetExtraTxnState`). Call that one `txnEvent`.
</blockquote></details>

Done.
___
*[pkg/sql/conn_executor.go, line 851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52148#-MDe3PZP2qIUNjCjlF5t:-MDmOtI83iL4P0CHzKu3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bdf6ba0f908f562822348300597b9f435f478d1/pkg/sql/conn_executor.go#L851)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

move this stanza up with the state transition too pls; they belong together
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-03 04:46 UTC, jordanlewis commented
bors r-

2020-08-03 14:20 UTC, jordanlewis commented
bors r+

2020-08-03 22:04 UTC, jordanlewis commented
bors r+

2020-08-03 23:30 UTC, merged

2020-08-03 23:31 UTC, otan commented
backport? :P

On Mon, 3 Aug 2020, 4:30 pm craig[bot], <notifications@github.com> wrote:

> Merged #52148 <https://github.com/cockroachdb/cockroach/pull/52148> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/52148#event-3617931244>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA32FQ27M2R2UOQM5MODRGLR65CANANCNFSM4POGRODA>
> .
>