cli: improve interactive sql shell timings
cockroachdb/cockroach pull request #52233
Opened 2020-08-03 03:05 UTC by arulajmani

Previously, when a user executed multiple statements on a single line
in the CLI, we would send the string as-is to the server. This would
skew statement execution timings by attributing all of the server
execution time to the first statement.

This patch fixes this issue by parsing the supplied string on the
client side and sending invididual statements one at a time. This is
in line with Postgres behavior.

Additionally, this patch also changes the way we calculate the time
displayed by the CLI. Previously, we would show the time it took
between a client sending a request and recieving a result. This would
include the client-server latency as well. Now instead of showing the
total time, we switch to showing just the server execution time. This
is done by issuing the `SHOW LAST QUERY STATISTICS` query underneath
the hood.

Fixes #48180
Informs #49450

Release note (cli change): The way the CLI now shows the server
execution timing instead of the total time it took to recieve results.
This means factors such as rendering time and client server latency
are no longer accounted for in the timings that the CLI prints for a
query execution. Additionally, if multiple statements are supplied on
a single line, the timings displayed now are a more accurate
representation than before. Earlier the time displayed for the first
statement included the processing time for all the statements supplied
in that line. This is no longer the case as individual statement
timings now represent only their execution times. This brings us in line
with the postgres CLI.

2020-08-03 03:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52233)
<!-- Reviewable:end -->

2020-08-03 09:47 UTC, knz reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/cli/sql.go, line 1170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MDnhOPh9wutSnnKOKd-:-MDnhOPh9wutSnnKOKd0:bvtawbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0d5b29e437a785ca9617038734d0c4efeaa215/pkg/cli/sql.go#L1170)):*
> ```Go
> // concatLines.
> func (c *cliState) doRunStatements(nextState cliStateEnum) cliStateEnum {
> 	stmts, err := parser.Parse(c.concatLines)
> ```

Nah that won't do unfortunately.

While it is safe to *lex*  a SQL string into tokens, because the lexing rules only very rarely change, we can't make assumptions about the *grammar* in the CLI shell. Every two versions of the server will support different grammars, and a valid input for one version will not be valid for the CLI shell or vice-versa.

If you are really intent on *parsing*, then the SHOW SYNTAX statement is the way to go (i.e. do parsing server-side).
___
*[pkg/cli/sql_util.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MDnhkKO4lVrE-4x3wv3:-MDnhkKO4lVrE-4x3wv4:b6bccq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0d5b29e437a785ca9617038734d0c4efeaa215/pkg/cli/sql_util.go#L796)):*
> ```Go
> 			// TODO(arul): This 2 is kind of ugly and unfortunate.
> 			execLatencyRaw, hasVal := conn.getServerValueFromColumnIndex(
> 				"last query statistics", `SHOW LAST QUERY STATISTICS`, 2 /* exec_latency */)
> ```

You also need to make this code tolerant of the absence of support for this (new-ish) statement.
The way to do this is to detect the availability of the statement during connection set-up, e.g. in `checkServerMetadata()` and then have a condition here.


<!-- Sent from Reviewable.io -->

2020-08-05 21:20 UTC, arulajmani reviewed
Should be good for another look! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-ME-UdEOChS3Avz6-I9L:bpdm9uo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/sql.go, line 1170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MDnhOPh9wutSnnKOKd-:-MDziy3n-Aq8ZwXzRJxQ:b-xqof52) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0d5b29e437a785ca9617038734d0c4efeaa215/pkg/cli/sql.go#L1170)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Nah that won't do unfortunately.

While it is safe to *lex*  a SQL string into tokens, because the lexing rules only very rarely change, we can't make assumptions about the *grammar* in the CLI shell. Every two versions of the server will support different grammars, and a valid input for one version will not be valid for the CLI shell or vice-versa.

If you are really intent on *parsing*, then the SHOW SYNTAX statement is the way to go (i.e. do parsing server-side).
</blockquote></details>

Thats true, I forgot how much our grammar changes. I don't really need to parse anyway, so I've added a new `Scan` method and used that here. 

I decided against using the server side parse because checking syntax is a client side configurable setting, and I didn't want to couple timing calculation (old vs this implementation) with the check syntax setting. 
___
*[pkg/cli/sql_util.go, line 796 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MDnhkKO4lVrE-4x3wv3:-ME-K4FpDJQXHt_cVJc-:buhw4o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0d5b29e437a785ca9617038734d0c4efeaa215/pkg/cli/sql_util.go#L796)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You also need to make this code tolerant of the absence of support for this (new-ish) statement.
The way to do this is to detect the availability of the statement during connection set-up, e.g. in `checkServerMetadata()` and then have a condition here.
</blockquote></details>

Added `tryEnableServerExecutionTimings` inspired by how we check for `SHOW SYNTAX` support. Lmk what you think 


<!-- Sent from Reviewable.io -->

2020-08-06 09:02 UTC, knz reviewed
Thanks for the changes.

You'll need to tweak some tests (and add some minimal testing for your new feature)

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-ME2-MhQ7TwA2yAvfO0u:b-b2pkrt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/cli/sql.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1za7P4yNqjiUJbwcV:-ME1za7Q6IUOoW80RUZb:bbl3hy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1346)):*
> ```Go
> 		// Try to enable server execution timings for the CLI to display if
> 		// supported by the server.
> 		c.tryEnableServerExecutionTimings()
> ```

I recommend doing this check upon every re-connection. Consider the following scenario:

1. user starts sh ell
2. user stops node
3. user restarts node in different version (e.g an upgrade)
3. user continues using shell, shell reconnects

we want the shell to adjust to the new server's capabilities. Hence my suggestion to check these things in the connect method, like we already do for the version strings.
___
*[pkg/cli/sql.go, line 1551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1zq-i7tU2ikRVa_Yg:-ME1zq-i7tU2ikRVa_Yh:b-622qm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1551)):*
> ```Go
> func (c *cliState) tryEnableServerExecutionTimings() {
> 	if err := c.conn.Exec("SHOW LAST QUERY STATISTICS", nil); err != nil {
> 		fmt.Fprintf(stderr, "warning: cannot show server execution timings: %v\n", err)
> ```

1) you need to check that the result has a column named `exec_latency` in second position. That is the exact assumption made by the remainder of your code below.

2)  also set the thing to false if there's an error.
___
*[pkg/sql/parser/parse.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME2-6OVBLgwxuu1WH1V:-ME2-6OVBLgwxuu1WH1W:bsmunuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/sql/parser/parse.go#L228)):*
> ```Go
> }
> 
> // Scan takes a sql string and returns potential sql statements by performing
> ```

Given this description, the word "scan" is inappropriate.

Why not use a name that says what it does, eg `SplitAtSemicolons`


<!-- Sent from Reviewable.io -->

2020-08-10 02:37 UTC, arulajmani reviewed
TFTRs. Re: tests -- I'm having trouble getting `make acceptance TESTS=TestDockerCLI` to work locally, not quite sure whats going on. This is making the test tweaking/addition hard, I'll look into it again tomorrow. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MELDKp27ixeu5TyXkT9:b-lhphz5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @miretskiy)

___
*[pkg/cli/sql.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1za7P4yNqjiUJbwcV:-MEL3lrfClx2v86MJCCX:b-ovwjks) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1346)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I recommend doing this check upon every re-connection. Consider the following scenario:

1. user starts sh ell
2. user stops node
3. user restarts node in different version (e.g an upgrade)
3. user continues using shell, shell reconnects

we want the shell to adjust to the new server's capabilities. Hence my suggestion to check these things in the connect method, like we already do for the version strings.
</blockquote></details>

Makes sense. I guess this should've applied to `tryEnableCheckSyntax` as well, but I don't think it holds anymore because `SHOW SYNTAX` seems to be quite old, so all server versions should be able to recognize that observer statement. Unless I'm missing something, we can cleanup the `tryEnableCheckSyntax` stuff now, right?
___
*[pkg/cli/sql.go, line 1551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1zq-i7tU2ikRVa_Yg:-MEKzontBq9q7Qz68-2q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1551)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) you need to check that the result has a column named `exec_latency` in second position. That is the exact assumption made by the remainder of your code below.

2)  also set the thing to false if there's an error.
</blockquote></details>

Done.
___
*[pkg/sql/parser/parse.go, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME2-6OVBLgwxuu1WH1V:-MEKyRFoCW_WM-M6vsms:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/sql/parser/parse.go#L228)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Given this description, the word "scan" is inappropriate.

Why not use a name that says what it does, eg `SplitAtSemicolons`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-10 07:53 UTC, knz reviewed
>  I'm having trouble getting make acceptance TESTS=TestDockerCLI to work locally

This is what I use to run and troubleshoot these tests:
```shell
$ killall -9 cockroach cockroachshort; rm -rf logs; expect -d -f pkg/cli/interactive_tests/foo.tcl ./cockroach
```

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MEMLnA33akipmXZc5jW:bnnoxev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/cli/sql.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1za7P4yNqjiUJbwcV:-MEMLYRnDUQfe3GudS4u:b9u5ept) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1346)):*
> Unless I'm missing something, we can cleanup the tryEnableCheckSyntax stuff now, right?

yes that sounds right
___
*[pkg/cli/sql_util.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEMLckR-t9g5QV19Zw8:-MEMLckR-t9g5QV19Zw9:btbqvu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/cli/sql_util.go#L179)):*
> ```Go
> 	}
> 	defer func() { _ = rows.Close() }()
> 	if rows.Columns()[2] != "exec_latency" {
> ```

also check that `len(rows.Columns()) >= 2` to avoid surprises


<!-- Sent from Reviewable.io -->

2020-08-10 18:18 UTC, andreimatei requested changes
We like it when a client sends statements batched together without pgwire `Syncs` in between them because then the server can auto-retry all of them, not just the first one. That's a pretty useful thing; I wouldn't want to lose it. In particular, I use it a lot for testing so at the very lease give me a way to disable it. Better yet, have you considered keeping the batching and, instead of sending the statements one by one, adding the `show stats` thing in between every one of them while still batching? Like, transform the batch by interspersing these stats statements.

In any case, please add a flag to disable these new statements (a new `\set <foo>` flag), and include it in`--debug-sql-cli`. Any magic in the client is a pain in the ass when debugging.

I don't know if the patch does this already, but can we show both the execution time and the network time? The network time is useful to see in geo-distributed clusters.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MEOWYm-7bnHuure5VZ0:b-ww8f45)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/parser/parse.go, line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEOWCckDLtbj8OwAYYt:-MEOWCckDLtbj8OwAYYu:brwbyft) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/sql/parser/parse.go#L228)):*
> ```Go
> }
> 
> // SplitAtSemicolons takes a sql string and returns potential sql statements
> ```

Please spell out that this does lexing but not parsing (right?). That's important cause we don't want to do client-side parsing (with a potentially old grammar). 
Consider renaming to `ScanStatements` for coherency with other lexing around this package.
___
*[pkg/sql/parser/parse.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEOWEmv1apoFfraLwPq:-MEOWEmv1apoFfraLwPr:b-of0609) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/sql/parser/parse.go#L241)):*
> ```Go
> 		stmts = append(stmts, sql)
> 	}
> 	return
> ```

no naked returns pls


<!-- Sent from Reviewable.io -->

2020-08-14 18:43 UTC, arulajmani reviewed
I tried doing the interspersed statement approach, but I ran into some trouble with statements that return no rows. Seems like `lib/pq` doesn't return a result set if other statements in the batch return rows. This means that there if we intersperse a `CREATE TABLE` with `SHOW LAST QUERY STATISTICS`, instead of running the noRows hook for the create table, we end up printing the result of the `SHOW LAST QUERY STATISTICS`! It's easy to test this behavior on master, by doing a `BEGIN; CREATE TABLE t(a int); COMMIT;` -- only the COMMIT tag is printed! Not sure if there's a workaround, but I'd be open to implementing it as I like the interspersing approach. 

For now, I've added a `show_server_execution_times` flag to turn of the "new timings" as per @andreimatei's recommendation. When set to false, we continue doing the batching (and printing out the old timings). 

Lastly, I have an open question about Notices. Currently, we have a policy to print out notices once all the statements on a line have been printed. This doesn't fit that well in the new approach where we lex on the client side. (see the change to `test_notice.tcl` for an example of the change). Is this okay? Achieving the old behavior is still possible, but it does come with adding some complexity in the code by moving the responsibility of flushing notices, which makes me apprehensive. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MEiDg4I7H2wWqOB9ZRb:bgmzbji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/cli/sql.go, line 1346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-ME1za7P4yNqjiUJbwcV:-MEcNkFJ2wZarjKsbOLv:b-tvif7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/43b4b869ab984dfc3093f11f0c54d5ca4b34f183/pkg/cli/sql.go#L1346)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> Unless I'm missing something, we can cleanup the tryEnableCheckSyntax stuff now, right?

yes that sounds right
</blockquote></details>

Okay, I've removed it while Im in this part of the code then! 
___
*[pkg/cli/sql_util.go, line 179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEMLckR-t9g5QV19Zw8:-MEcLsCE7IhpuV5XkbkQ:b-3tblgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/cli/sql_util.go#L179)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

also check that `len(rows.Columns()) >= 2` to avoid surprises
</blockquote></details>

Ended up refactoring this stuff a little bit. Now I have a function responsible for getting and parsing last query statistics, which validates the columns as well. I like this more instead of having this `2` in two places. 
___
*[pkg/sql/parser/parse.go, line 228 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEOWCckDLtbj8OwAYYt:-MEcMfaZ3GCKlFHuxg4L:b-yo1c4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/sql/parser/parse.go#L228)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please spell out that this does lexing but not parsing (right?). That's important cause we don't want to do client-side parsing (with a potentially old grammar). 
Consider renaming to `ScanStatements` for coherency with other lexing around this package.
</blockquote></details>

Spelled out the intention to have this be called from the client and why we don't want to do any parsing on the client. 
___
*[pkg/sql/parser/parse.go, line 241 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MEOWEmv1apoFfraLwPq:-MEcN-B41YbnIBVy08LB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70522aa552bab624082196805d1d4ee07a5428f4/pkg/sql/parser/parse.go#L241)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

no naked returns pls
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-14 19:10 UTC, andreimatei commented
Since you mention notices, can't we just use notices to get the server timing (instead of a dedicated statement), and then we don't have to argue about the value of batching? Like a session variable used by the shell that causes a notice to be returned with each statement?

2020-08-14 19:25 UTC, andreimatei commented
Btw, changing the batching changes the semantics of error semantics, doesn't it? An error in a batch interrupts the execution of the following statements, whereas across batches it doesn't (assuming implicit txn). Maybe we don't handle this well (#44803), but hopefully we'll fix that.

2020-08-14 19:31 UTC, arulajmani commented
I think my change brings us more in line with the postgres CLI behavior. PG seems to do do similar client side lexing as my patch: 
```
postgres=# CREATE TABLE mytable(a INT);
CREATE TABLE
postgres=# INSERT INTO mytable VALUES(1); SELECT 1/0; INSERT INTO mytable VALUES(2);
INSERT 0 1
ERROR:  division by zero
INSERT 0 1
postgres=# SELECT * FROM mytable;
 a
---
 1
 2
(2 rows)
 
```

2020-08-14 22:22 UTC, arulajmani commented
Re: using notices to convey timings back to the client -- this seems a bit hacky to me. Right now, notices are printed out to stderr whereas the query results + timing etc. is printed out to stdout. The idea of going through all notices, figuring out if they pertain to timing, and parsing out timing from the notice error string doesn't seem the correct use of a notice. Additionally, postgres seems to do this client side lexing too, so I don't see a compelling case to not be in line with it. 

I do acknowledge your point that you find this batching stuff on the client useful. Maybe the solution here is to provide that as an option users can opt in to, and let the default behavior mimic postgres. To that end, I think it might make sense to rename the flag from `show_server_execution_times` to `batch_statements_on_same_line` (or something of that sort, which makes the intention clearer). How do you feel about this as a compromise to both solve your use-case and get us in line with PG behavior?

2020-08-14 22:50 UTC, andreimatei commented
> Re: using notices to convey timings back to the client -- this seems a bit hacky to me. Right now, notices are printed out to stderr whereas the query results + timing etc. is printed out to stdout. The idea of going through all notices, figuring out if they pertain to timing, and parsing out timing from the notice error string doesn't seem the correct use of a notice.

Using notices here seem like exactly the right use for them to me. It's extra information conveyed by the server to the client; it seems quite appropriate to me for the client to cherry-pick what it wants out of them and present them in whatever way it sees fit. Now that we have these notices, I wish we'd use them for reading the txn status too (which I think the shell also does after every batch).

> Additionally, postgres seems to do this client side lexing too, so I don't see a compelling case to not be in line with it.

When you say "postgres" you mean "psql", right? There's a difference between the two. I don't think being line with psql is a particular consideration; we made no efforts to support its flags for example.

The thing is that, ever since I found out of postgres' behavior for batches, I've really wanted that behavior from the command line. It'd save me a lot of `BEGIN...END` and it's always what I want on the command line. So I wouldn't want us to move further away from it. Respecting the batching also makes the interactive behavior of the shell similar to the `cockroach sql -e <batch>` behavior which makes sense to me (btw, you're not changing `-e` right?). 
Because you're breaking batches apart, but also because you're adding these new statements everywhere, this patch adds a bunch of latency. Particularly in geo-distributed settings this adds up, and particularly for a shell like this which is used frequently in a non-interactive way by piping a script into it (or did your changes not apply when stdin is not a tty somehow?).

I was gonna say that I don't need to care too much and if you have another reviewer that likes it then run with it, but I guess I do care about our shell experience, and I see doing something with notices to be better in every way. And then other clients could benefit from it too if they set that session var.

If you show me that I'm a minority here, I'll shut up.

2020-08-14 23:29 UTC, andreimatei commented
FWIW, `psql` has the option of escaping the `;` as `\;`, in which case it will not send the statement that it terminates by itself.

2020-08-17 13:13 UTC, awoods187 commented
|Because you're breaking batches apart, but also because you're adding these new statements everywhere, this patch adds a bunch of latency. Particularly in geo-distributed settings this adds up, and particularly for a shell like this which is used frequently in a non-interactive way by piping a script into it

This is my concern as well. The main point of this change is to give users more accurate time information on SQL statements and to break the concern into network and execution. We want to do this because users are concerned about latency/timing. Anything that would make that worse seems a non-starter for me. I also think Andrei's point about retries is a compelling one--we definitely don't want to make the retry behavior worse (and keeping batches from being retried together strikes me as worse).

2020-08-17 15:01 UTC, arulajmani commented
> (btw, you're not changing -e right?).
No, this change/splitting batching behaviour only applies to the interactive shell. 

>  Particularly in geo-distributed settings this adds up, and particularly for a shell like this which is used frequently in a non-interactive way by piping a script into it 

This doesn't apply because my change only affects interactive shells. 

>  Now that we have these notices, I wish we'd use them for reading the txn status too (which I think the shell also does after every batch).

Yup, we do this for getting both the current database and the transaction status after every batch. I was simply adding on to this pattern. We also do it every time a user enters a new line or they're inputting a multi-line statement. 

I'm not sure if the clarification about non-interactive shells makes this approach any better or not. I'll try and prototype the notice approach and see if it goes smoothly though.

2020-08-31 20:09 UTC, solongordon commented
@awoods187 @andreimatei What would you think about shipping this behind a flag which was off by default? That way it could still be used as a sales tool but wouldn't disrupt any existing use cases. The NOTICE approach sounds promising but there's no way we're doing it for 20.2.

2020-09-01 19:47 UTC, andreimatei reviewed
I wouldn't merge it; I don't think it's worth the code... If its for the sales engineers, you can just give them the binary. Or they can just type out `SHOW LAST QUERY STATISTICS` themselves.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MGAB_fSE_HMVX8YX9hx:b-j3bps4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)



<!-- Sent from Reviewable.io -->

2020-09-01 20:00 UTC, arulajmani commented
FWIW sales engineers cant just type `SHOW LAST QUERY STATISTICS` because of the statements the CLI issues underneath the hood, which is sort of unfortunate.

2020-09-01 22:25 UTC, andreimatei commented
If it helps, all those statements can be inhibited with various shell settings.

2020-09-02 12:37 UTC, knz commented
@arulajmani I reviewed your PR again today.
I would like to propose the following

- drop the lexing code and thus abandon the motivation to fix #48180 in this 20.2
- however, keep your PR in a somewhat simplified form.

Here's the proposal: keep the new code that issues `SHOW LAST QUERY STATISTICS` under the hood, then report these details for the last statement executed.

Regarding the issue #48180, here what we can do in 20.2:  if there is a semicolon inside the query, then display a warning to the user to inform them that the times are misleading. (i.e. inform them of the limitation of #48180 and let them decide to split the statement across multiple lines)

(I think you could even try disabling the timing report _entirely_ if there's a semicolon in the input. With an explanatory message. This way there's no wrong information for the user to work with.)

2020-09-03 02:23 UTC, arulajmani reviewed
@knz thanks for the suggestions, I implemented them more or less as you suggested, and I think this is in a place where the change is minimally invasive while still giving us the ability to show different buckets for query execution (network latency/server exec time), as was the original motivation behind the change. 


Re: multiple statements on one line -- these continue to behave the same functionally as they did before my change, albeit no timings are displayed for them anymore. 

I might need to revert some tests back, but Ill let CI find them for me. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MGGkPXMEsG0u7jNmB0o:b-9gy5fj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)



<!-- Sent from Reviewable.io -->

2020-09-03 12:14 UTC, knz requested changes
I like the new approach. Just a few nits and this will be good to go.

> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MGIsqcP7lh5mC4IAwNW:b-ykzk4j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @arulajmani)

___
*[pkg/cli/sql.go, line 366 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIqyMX3tr_O7EWp319:-MGIqyMX3tr_O7EWp31A:b-dge44l) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql.go#L366)):*
> ```Go
> 		display:                   func(_ *cliState) string { return strconv.FormatBool(sqlCtx.showTimes) },
> 	},
> 	`show_server_execution_times`: {
> ```

you can simplify this to `show_server_times` IMHO
___
*[pkg/cli/sql.go, line 1183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIr5492uAQC0_EoTMh:-MGIr5492uAQC0_EoTMi:btfznjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cef838c9e5bc50053cb09994a1e4f7ff2abc610e/pkg/cli/sql.go#L1183)):*
> ```Go
> 		if c.exitErr != nil {
> 			cliOutputError(stderr, c.exitErr, true /*showSeverity*/, false /*verbose*/)
> 			if c.errExit {
> ```

I think you need to preserve this code?
___
*[pkg/cli/sql_util.go, line 380 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIrI1n7H6ga3SuOVl2:-MGIrI1n7H6ga3SuOVl3:bgbgh0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql_util.go#L380)):*
> ```Go
> 		return 0, 0, err
> 	}
> 	defer func() { _ = rows.Close() }()
> ```

nit: if we're being pedantic, it's possible for the SQL client driver to detect a SQL error only when Close() is called.
so the idiom would be more like this:
```go
defer func() {
    closeErr := rows.Close()
    err = errors.CombineErrors(err, closeErr)
}()
```

(CombineError suitably returns `nil` if both arguments are `nil`)
___
*[pkg/cli/sql_util.go, line 891 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIrjV9EGoA8rX8HkzR:-MGIrjV9EGoA8rX8HkzS:b-65a9m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql_util.go#L891)):*
> ```Go
> 			fmt.Fprintln(w)
> 		} else {
> 			fmt.Fprintf(w, "Note: timings for multiple statements on a single line are not supported\n")
> ```

1) this `else` is incorrect. (Also the cause of the CI failures) You only want the warning to be printed if `sqlCtx.showTimes` is true

2) maybe worth printing to `stderr`, not `stdout` (ditto for the other Note above). not feeling strongly about this - you can see for yourself what the UX benefit is.

3) ditto, probably only worth printing the notes if `cliCtx.isInteractive` is true. I think there's no point in explaining if there's no eyes to look at this.
___
*[pkg/sql/parser/parse.go, line 239 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIs_w629oh9v-EEd_H:-MGIs_w629oh9v-EEd_I:b7jbv2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/sql/parser/parse.go#L239)):*
> ```Go
> }
> 
> // ScanStatements takes a sql string and returns potential sql statements
> ```

Given the new goal, I think you can simplify this function to just "HasMultipleStatements" returning bool, stopping the loop at the first semicolon.


<!-- Sent from Reviewable.io -->

2020-09-03 15:31 UTC, arulajmani reviewed
TFTR! Wanna give CI one more run on this still. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MGJ_xjvBTpCX88V_oaN:b8fkwuz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/cli/sql.go, line 366 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIqyMX3tr_O7EWp319:-MGJGqbE9ShA06QGuR39:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql.go#L366)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can simplify this to `show_server_times` IMHO
</blockquote></details>

Done.
___
*[pkg/cli/sql.go, line 1183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIr5492uAQC0_EoTMh:-MGJHcQw0XI1e4BoCkle:b-o3twnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cef838c9e5bc50053cb09994a1e4f7ff2abc610e/pkg/cli/sql.go#L1183)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you need to preserve this code?
</blockquote></details>

Didn't mean to delete, missed this when reverting back to the original state. Done. 
___
*[pkg/cli/sql_util.go, line 380 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIrI1n7H6ga3SuOVl2:-MGJIZeF0nvcd--WfZzR:bwn96re) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql_util.go#L380)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: if we're being pedantic, it's possible for the SQL client driver to detect a SQL error only when Close() is called.
so the idiom would be more like this:
```go
defer func() {
    closeErr := rows.Close()
    err = errors.CombineErrors(err, closeErr)
}()
```

(CombineError suitably returns `nil` if both arguments are `nil`)


</blockquote></details>

Makes sense, I'll change this in `runQueryAndFormatResults` while I'm here as well. 
___
*[pkg/cli/sql_util.go, line 891 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIrjV9EGoA8rX8HkzR:-MGJ_gs20CfJT9oaC8kG:b-itsfz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/cli/sql_util.go#L891)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) this `else` is incorrect. (Also the cause of the CI failures) You only want the warning to be printed if `sqlCtx.showTimes` is true

2) maybe worth printing to `stderr`, not `stdout` (ditto for the other Note above). not feeling strongly about this - you can see for yourself what the UX benefit is.

3) ditto, probably only worth printing the notes if `cliCtx.isInteractive` is true. I think there's no point in explaining if there's no eyes to look at this.
</blockquote></details>

Makes sense, switched this logic up a bit. I don't have any strong preferences about point 2 really, but I made the switch to `stderr`. 
___
*[pkg/sql/parser/parse.go, line 239 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGIs_w629oh9v-EEd_H:-MGJKlltAGbPIEYo_XnG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/531568571f5abc4da638e848116f2533409eb299/pkg/sql/parser/parse.go#L239)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Given the new goal, I think you can simplify this function to just "HasMultipleStatements" returning bool, stopping the loop at the first semicolon.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-03 15:41 UTC, knz approved these changes
LGTM modulo `stderr` see below

Also assuming CI is green :)

> Reviewed 2 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-:-MGJc8Sq2vYB5dSIuV10:b-ffw32t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @arulajmani, and @knz)

___
*[pkg/cli/sql_util.go, line 877 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52233#-MGJbrAN1yxAuKjxSXDk:-MGJbrAN1yxAuKjxSXDl:b-2xtykw) ([raw file](https://github.com/cockroachdb/cockroach/blob/41f96e5ef5f9cd1b9fbc0486cc0db5ed1155c6d2/pkg/cli/sql_util.go#L877)):*
> ```Go
> 				// No need to print if no one's watching.
> 				if sqlCtx.isInteractive {
> 					fmt.Fprintf(os.Stderr, "Note: timings for multiple statements on a single line are not supported.\n")
> ```

`stderr` not `os.Stderr`
ditto below

also, I'd argue it would be useful to add a reference to the github issue here (see `unimplemented.MakeURL()`)


<!-- Sent from Reviewable.io -->

2020-09-03 17:55 UTC, arulajmani commented
Thanks for all the reviews! 

bors r=knz

2020-09-03 18:34 UTC, merged