importccl: support random() and gen_random_uuid() as default expression
cockroachdb/cockroach pull request #52247
Opened 2020-08-03 15:30 UTC by Anzoteh96

This PR follows up from #50295 to support random() and gen_random_uuid() as default expression. 

Following the visitor and overriding patterns on previous PRs, the random() expression is supported by periodically re-seeding (say, every N rows) and making sure that when we resume (after a failed import), we return to the position where it's last re-seeded. The seed is determined by the row number, timestamp, and source ID.

Release note (general change): random() and gen_random_uuid() are supported
as default expressions for IMPORT.

2020-08-03 15:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52247)
<!-- Reviewable:end -->

2020-08-03 17:06 UTC, miretskiy requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @Anzoteh96)

___
*[pkg/ccl/importccl/read_import_base.go, line 625 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpFL2O6saG0AIaxlsp:-MDpFA7o38ZkZ7bfXQ5X:bf11695) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/ccl/importccl/read_import_base.go#L625)):*
> ```Go
> 			if batchIdx%resumeRowMultiple == 0 {
> 				row.ReseedForImport(conv.KvBatch.Source, rowIndex)
> 			}
> ```

I'm not sure this is the right place for this.

If i understand correctly, you need to
 a) have random() override
 b) have it produce deterministic results based on row number.

Remember: the override operates over evalCtx -- which is available
in every row converter. 

So, why can't we add a lazily initialized "rnd *rand.Random" member to the `cellInfoAnnotation` struct?

Since converter itself does not need to be thread safe, we can initialize `rnd` when Row() is called.

We can figure out the seed, and we can also figure out, how many times we need to call rnd.Random() to get to the right place.

```
func importRandom(evalCtx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
    annot := ...
    if annot.rnd == nil {
       annot.rnd = rand.New(rand.Source(your initial seed here))
      // catchup rnd to the row
     for i := annot.rowID % resumeRowMultiple; i > 0; i-- {
      _ = annot.rnd.Rand()
     } 
    }
	return tree.NewDFloat(tree.DFloat(rand.Float64())), nil
}

```

Something like that.
___
*[pkg/sql/row/expr_walker.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpDllx7HRUS2FvbFdX:-MDpDllx7HRUS2FvbFdY:b-j977ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/sql/row/expr_walker.go#L168)):*
> ```Go
> 	},
> 	"random": {
> 		visitorSideEffect: func(annot *tree.Annotations) {},
> ```

don't have to specify it if there is no side effect.
___
*[pkg/sql/row/row_converter.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpE2RhDCHmxGc-2rf8:-MDpE2RhDCHmxGc-2rf9:bx8li9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/sql/row/row_converter.go#L184)):*
> ```Go
> // ReseedForImport is a method to reset the state of the rand library whenever
> // being called.
> func ReseedForImport(sourceID int32, rowIndex int64) {
> ```

This looks wrong to me.  The behavior of the random depends on the number of calls to rand(); Plus, we are changing rand seed, and that rand is used by many different parts of the code.

Instead, you *should* use visitor side effect field in the walker to initialize
rand := rand.New(rand.NewSource(your seed value))


<!-- Sent from Reviewable.io -->

2020-08-03 17:16 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @Anzoteh96)

___
*[pkg/ccl/importccl/import_processor_test.go, line 411 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpIIsc7XQYFLS2-k1N:-MDpIIsc7XQYFLS2-k1O:behglx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/ccl/importccl/import_processor_test.go#L411)):*
> ```Go
> 					// batchSize rows (possibly out of order), starting from our initial resumePos
> 					for prog := range progCh {
> 						adjustedPos := adjustedResumePos(rp + int64(batchSize))
> ```

Looking at this now, I wonder if instead of adjusting the resume position we can seed `rand` and call `Random()` the correct number of times inside the random overload?

Ah - just as I'm typing this it looks like Yevgeniy has a suggestion on how to do exactly this.
___
*[pkg/ccl/importccl/import_stmt.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpHFHYDnfy-O9-V_27:-MDpHFHZEL6guqPZVsdS:b-lxqj6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/ccl/importccl/import_stmt.go#L93)):*
> ```Go
> // resumeRowMultiple is so that each resume row index must be a multiple of
> // resumeRowMultiple, and that every row is re-seeded at those places.
> const resumeRowMultiple = 20
> ```

I'd imagine that we'd want to tune this. Naively, 20 seems like we'd still be re-seeding quite frequently.
___
*[pkg/sql/row/expr_walker.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDpHjOa-LMEOM4qftRy:-MDpHjOa-LMEOM4qftRz:bfsz6lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/879c970ee95f1c7ad853017a929080a77dd87c5a/pkg/sql/row/expr_walker.go#L114)):*
> ```Go
> 
> func importRandom(evalCtx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 	return tree.NewDFloat(tree.DFloat(rand.Float64())), nil
> ```

Don't we need a `rand` specific to IMPORT? Otherwise other calls to random throughout the code will change it.


<!-- Sent from Reviewable.io -->

2020-08-03 22:09 UTC, Anzoteh96 reviewed
Here's the latest strategy: 
1. For each `random()` and `gen_random_uuid`, we have a field `Rand` source stored in it. 
2. When re-seeding is not needed, we will just use these sources to generate random numbers for us. 
3. Re-seeding is needed upon: 
(a) a Resume: in this case a `newRowConverter` is created, so this scenario is detected when the `Rand` source is `nil`. 
(b) when `rowIndex` is a multiple of `reseedRowMultiple` (I place 1000 here...feel free to suggest other magnitudes). 
4. At the first call of `random()` or `gen_random_uuid` after re-seeding, we use these sources to call `Int64` or `Float64` enough number of times before assigning the `random()` or `gen_random_uuid` values for us. 
(a) For the case when `rowIndex` is multiple of `reseedRowMultiple` this is basically a no-op. 
(b) for Resume (including the very first time a row is created), the number of times we have to call `Int64` or `Float64` is (`rowIndex % reseedRowMultiple` * number of occurrences of the `random()` or `gen_random_uuid` instances). 

That said, I'm looking for suggestion on any strategy to test the code: right now the tests I've added simply verify that the values are all different (in particular, we're certain they do not all produce 0.42 ;) )

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-:-MDqIySrAqi6xWc4aCRm:b-u1nq5k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqM6WnDlA2IQRh3XKv:-MDqM6WnDlA2IQRh3XKw:b-y00a4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/44469e4cf3615d39df9dbdb8193eb117e5a13e09/pkg/sql/row/expr_walker.go#L131)):*
> ```Go
> 	if c.randSource == nil {
> 		c.randSource = rand.New(rand.NewSource(c.randSeed))
> 		numOccurences := (int(c.rowID) % reseedRowMultiple) * c.randTotal
> ```

Note: this is how we know the number of times we need to call `Float64` (similar example for `gen_random_uuid`). 
___
*[pkg/sql/row/row_converter.go, line 27 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqLitZ2JWttQE76-uW:-MDqLitZ2JWttQE76-uX:b-w65tgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/44469e4cf3615d39df9dbdb8193eb117e5a13e09/pkg/sql/row/row_converter.go#L27)):*
> ```Go
> // ResumeRowMultiple is so that each resume row index must be a multiple of
> // ResumeRowMultiple, and that every row is re-seeded at those places.
> const reseedRowMultiple = 1000
> ```

Note: `reseedRowMultiple` declared here to replace `resumeRowMultiple`. 
___
*[pkg/sql/row/row_converter.go, line 369 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqLrzD5cZoiJ7R6WZv:-MDqLrzD5cZoiJ7R6WZw:b-f3ekmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/44469e4cf3615d39df9dbdb8193eb117e5a13e09/pkg/sql/row/row_converter.go#L369)):*
> ```Go
> 	annot := getCellInfoAnnotation(c.EvalCtx.Annotations)
> 	annot.Reset(sourceID, rowIndex)
> 	if annot.randSource == nil || rowIndex%reseedRowMultiple == 0 {
> ```

Note: `nil` will signify what happens after a `Resume`. 


<!-- Sent from Reviewable.io -->

2020-08-04 00:51 UTC, miretskiy requested changes
> Reviewed 1 of 7 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqwHLp5FI9HnfrEysR:-MDqwHLq6fzHfV7pczGA:bspktep) ([raw file](https://github.com/cockroachdb/cockroach/blob/78b5be4dff12bd304aec559e3ef0a36abba1e192/pkg/sql/row/expr_walker.go#L198)):*
> ```Go
> 	"random": {
> 		visitorSideEffect: func(annot *tree.Annotations) {
> 			getCellInfoAnnotation(annot).randTotal++
> ```

I'm not sure I like the name `randTotal`...
But more to the point, I don't understand why we need it.

Once you have seeded random number generator with the appropriate row number, 
and advanced random N times (until %X==0), why do we care how many random() expressions there are?  That number (the number of random() calls) does not change.  So, if you 
restart the import, you would still continue to generate the same sequence of random numbers.

Same thing the uuid as well.

Come to think of it, you probably can entirely get away with using just one instance
of random number generator. 


<!-- Sent from Reviewable.io -->

2020-08-04 13:24 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/row_converter.go, line 369 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqLrzD5cZoiJ7R6WZv:-MDtaLc-EHTGna_7FXEL:b-st09jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/44469e4cf3615d39df9dbdb8193eb117e5a13e09/pkg/sql/row/row_converter.go#L369)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

Note: `nil` will signify what happens after a `Resume`. 
</blockquote></details>

Personally, I think this entire check can be moved inside random() implementation
(one of the reasons why I don't like this check here is because i was not sure what it is that we are reseeding when randSource is null).

At any rate, I think you can use a bit of go encapsulation to build import specific random number generator.  Something along the following lines:

```
const reseedRandEveryN = 1000

type importRand struct {
  *rand.Rand
  pos int
}

func newImportRand(pos int) {
   rnd := rand.New(....)
   // initialize and seek
  return &importRand{rnd, pos}
}

func (r *importRand) advancePos() {
   r.pos++
   if r.pos % reseedRandEveryN == 0 {reseed}
}
func (r *importRand) Float64() float64 {
  res := r.Rand.Float64()
  r.advancePos()
}

// Similar for int64
```


<!-- Sent from Reviewable.io -->

2020-08-04 15:35 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqwHLp5FI9HnfrEysR:-MDu42oN7CEg6Fb3EiZt:bwjgr2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/78b5be4dff12bd304aec559e3ef0a36abba1e192/pkg/sql/row/expr_walker.go#L198)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure I like the name `randTotal`...
But more to the point, I don't understand why we need it.

Once you have seeded random number generator with the appropriate row number, 
and advanced random N times (until %X==0), why do we care how many random() expressions there are?  That number (the number of random() calls) does not change.  So, if you 
restart the import, you would still continue to generate the same sequence of random numbers.

Same thing the uuid as well.

Come to think of it, you probably can entirely get away with using just one instance
of random number generator. 
</blockquote></details>

I'm not sure I follow, I do think that we'd need to keep track of `randTotal`.

Let's assume that `reseedRowMultiple` is 20, and that each row has 2 calls to `random()` in their default expressions.

- ...
- IMPORT is about to insert row 20, and so it re-seeds.
- IMPORT then processes 3 more rows, calling `random()` 6 times.
- IMPORT checkpoints, remembering that it left off at row 23
- IMPORT fails

When resuming the IMPORT:
- The IMPORT resumes at row 23, notices that we're 3 off a `reseedRowMultiple`. To get back to the state where we left off, it seems like we'd need to advance `random()` 6 times (rather than 3).


<!-- Sent from Reviewable.io -->

2020-08-04 15:52 UTC, Anzoteh96 reviewed
Some note on the latest change: I followed the structure suggested by @miretskiy: to have a struct of `importRand` that contains the random generator and the position (which is, basically, determined by `rowID` and the number of instances of `random` or `gen_random_uuid` in a row). 

One modification here is that, rather than re-seeding per `reseedRandEveryN` rows, we'll re-seed for `reseedRandEveryN` calls (and I raise `reseedRandEveryN` to 10000 now: again this is open for discussion). Here's an example on how it works:

Suppose we have `reseedRandEveryN` = 10000 and we start (or resume) with rowID of 137562, and there are 3 `random()` instances in each row. Then given that 137562 * 3 = 412686 has remainder 2686 when divided by 10000, we will have 410000 as the seed for the our `random()` generator, and have it call `Float64` 2686 times. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-:-MDu8fWP80LhltfOS6aR:byr67uf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, and @miretskiy)

___
*[pkg/sql/row/expr_walker.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqwHLp5FI9HnfrEysR:-MDu7sWt9AfLacUILkf-:b2hvv58) ([raw file](https://github.com/cockroachdb/cockroach/blob/78b5be4dff12bd304aec559e3ef0a36abba1e192/pkg/sql/row/expr_walker.go#L198)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I'm not sure I follow, I do think that we'd need to keep track of `randTotal`.

Let's assume that `reseedRowMultiple` is 20, and that each row has 2 calls to `random()` in their default expressions.

- ...
- IMPORT is about to insert row 20, and so it re-seeds.
- IMPORT then processes 3 more rows, calling `random()` 6 times.
- IMPORT checkpoints, remembering that it left off at row 23
- IMPORT fails

When resuming the IMPORT:
- The IMPORT resumes at row 23, notices that we're 3 off a `reseedRowMultiple`. To get back to the state where we left off, it seems like we'd need to advance `random()` 6 times (rather than 3).

</blockquote></details>

I have been thinking whether we can get away with `randTotal` and I don't think there's a way (as per Paul's reasoning). I have renamed it as `randomInstancePerRow`, if that make things clearer. 
___
*[pkg/sql/row/row_converter.go, line 369 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqLrzD5cZoiJ7R6WZv:-MDu8XkH3qHRBLh2-2PW:b-pemtmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/44469e4cf3615d39df9dbdb8193eb117e5a13e09/pkg/sql/row/row_converter.go#L369)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Personally, I think this entire check can be moved inside random() implementation
(one of the reasons why I don't like this check here is because i was not sure what it is that we are reseeding when randSource is null).

At any rate, I think you can use a bit of go encapsulation to build import specific random number generator.  Something along the following lines:

```
const reseedRandEveryN = 1000

type importRand struct {
  *rand.Rand
  pos int
}

func newImportRand(pos int) {
   rnd := rand.New(....)
   // initialize and seek
  return &importRand{rnd, pos}
}

func (r *importRand) advancePos() {
   r.pos++
   if r.pos % reseedRandEveryN == 0 {reseed}
}
func (r *importRand) Float64() float64 {
  res := r.Rand.Float64()
  r.advancePos()
}

// Similar for int64
```

</blockquote></details>

The draft I have now follows this recipe. 


<!-- Sent from Reviewable.io -->

2020-08-04 17:11 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, and @miretskiy)

___
*[pkg/sql/row/expr_walker.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDqwHLp5FI9HnfrEysR:-MDuP2oC7ZRdg9Mq23IB:biomv9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/78b5be4dff12bd304aec559e3ef0a36abba1e192/pkg/sql/row/expr_walker.go#L198)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I have been thinking whether we can get away with `randTotal` and I don't think there's a way (as per Paul's reasoning). I have renamed it as `randomInstancePerRow`, if that make things clearer. 
</blockquote></details>

Ah.. yes, good points.  I stand corrected.
___
*[pkg/sql/row/expr_walker.go, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuPp2L-M2lG97-xsSc:-MDuPp2L-M2lG97-xsSd:b-725zk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L35)):*
> ```Go
> 	adjPos := (pos / reseedRandEveryN) * reseedRandEveryN
> 	rnd := rand.New(rand.NewSource(adjPos))
> 	for i := 0; i < int(pos%reseedRandEveryN); i++ {
> ```

Let's not mod every time?
`for i := int(pos%reseedRandEveryN); i > 0; i--`
___
*[pkg/sql/row/expr_walker.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuQ4-PCxQ5JbmNafW1:-MDuQ4-PCxQ5JbmNafW2:b-mdfu3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L50)):*
> ```Go
> 
> func (r *importRand) Float64() float64 {
> 	rand := r.Rand.Float64()
> ```

let's not use variable named same as our package? 
___
*[pkg/sql/row/expr_walker.go, line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuRajb4MRekErjW9a1:-MDuRajb4MRekErjW9a2:b-afrw7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L157)):*
> ```Go
> 	c := getCellInfoAnnotation(evalCtx.Annotations)
> 	if c.randSource == nil {
> 		c.randSource = newImportRand(c.rowID * int64(c.randInstancePerRow))
> ```

This makes sense to me.  I would love to see a good comment (about c.rowID * randInstancePerRow) -- this part is not obvious.  Or, perhaps (and even better),
add a helper function `getSeedForRand(rowId, numInstances, ...)` and add a nice
comment there (this way you won't have to repeat same comment below).

The second question I have is: should the seed be *also* offset by import time?
Right now, it always starts at 0 -- which is not entirely random.


<!-- Sent from Reviewable.io -->

2020-08-04 18:35 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, and @miretskiy)

___
*[pkg/sql/row/expr_walker.go, line 35 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuPp2L-M2lG97-xsSc:-MDuhaBq5E7l8G9wSUM6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L35)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's not mod every time?
`for i := int(pos%reseedRandEveryN); i > 0; i--`
</blockquote></details>

Done.
___
*[pkg/sql/row/expr_walker.go, line 50 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuQ4-PCxQ5JbmNafW1:-MDuhbc59OcXF5RYKWiO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L50)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's not use variable named same as our package? 
</blockquote></details>

Done.
___
*[pkg/sql/row/expr_walker.go, line 157 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDuRajb4MRekErjW9a1:-MDuhdRh0eDOzol14uo3:blpxds3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f54b48f5df7772d16eef6c380014fe6402bd2f5a/pkg/sql/row/expr_walker.go#L157)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This makes sense to me.  I would love to see a good comment (about c.rowID * randInstancePerRow) -- this part is not obvious.  Or, perhaps (and even better),
add a helper function `getSeedForRand(rowId, numInstances, ...)` and add a nice
comment there (this way you won't have to repeat same comment below).

The second question I have is: should the seed be *also* offset by import time?
Right now, it always starts at 0 -- which is not entirely random.
</blockquote></details>

Done for the first part (also added sourceID as a parameter to ensure that seeds don't collide for different processors. 

Ah, I always thought your second question is taken care of by the following line:
https://github.com/cockroachdb/cockroach/blob/6ff0528dccce688cd42e31756730b67bd51d7a54/pkg/ccl/importccl/read_import_base.go#L647
but only CSV and AVRO call these lines. Let me look into other types of formats now. 


<!-- Sent from Reviewable.io -->

2020-08-05 16:49 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3268 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDytCi59EC4uoQa8HzA:-MDytCi68ZgR8sEs8roH:b-6epx0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/ccl/importccl/import_stmt_test.go#L3268)):*
> ```Go
> 		}
> 	})
> 	t.Run("random-related", func(t *testing.T) {
> ```

Can we add test cases where there are multiple columns that have a default expression with `random()`. Also perhaps one that has both `random()` and `gen_random_uuid()`. Also some tests where those columns are targetted would be useful as well.

I don't remember if we have any tests that exercise IMPORT's resuming logic? If we do, it would be good to see if we could add a test case there to ensure that we can handle the resuming.
___
*[pkg/ccl/importccl/read_import_mysql_test.go, line 47 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzP7Le7GYSYoN1DJ59:-MDzP7Lh7vo8CqJP2Fbj:bxyz7cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/ccl/importccl/read_import_mysql_test.go#L47)):*
> ```Go
> 
> 	kvCh := make(chan row.KVBatch, 10)
> 	converter, err := newMysqldumpReader(ctx, kvCh, 0, tables, testEvalCtx)
> ```

Can you add a `/* timestamp */` comment by this argument. Also a comment about why it's ok to pass in 0 here would be useful.
___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-MDzPe9f9pes_gMzId09:b-qrnigt) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
> ```Go
> 	// Therefore, assuming that rowID increments by 1 for every row,
> 	// we will initialize the position as rowID * numInstances + sourceID << rowIDBits.
> 	rowIDWithMultiplier := int64(numInstances) * rowID
> ```

Looking at this again, don't we expect r.pos to be incremented a _maximum_ of numInstances based on how we're currently calculating `numInstances`


<!-- Sent from Reviewable.io -->

2020-08-05 18:16 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-MDzpHB6EOy1QN9ezffc:bsz6n7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Looking at this again, don't we expect r.pos to be incremented a _maximum_ of numInstances based on how we're currently calculating `numInstances`
</blockquote></details>

My head hurts thinking about this... But... Do we actually need this complexity?
What if we reseeded every time we flush row converter?
Couldn't we then simply set the seed to importTimestamp + rowID?
Regardless of how many instances we have? Would that be simpler ?


<!-- Sent from Reviewable.io -->

2020-08-05 18:56 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-MDzv78393Eq1EPfncBR:b-tg6vsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

My head hurts thinking about this... But... Do we actually need this complexity?
What if we reseeded every time we flush row converter?
Couldn't we then simply set the seed to importTimestamp + rowID?
Regardless of how many instances we have? Would that be simpler ?
</blockquote></details>

I don't think that will do the intended way because:
Say the rowIndex we left off was 26 and importTimeStamp is 10, and `reseedEveryN` is 15. then (26+10) mod 15 is 11 = 36 and this should mean that it will be the 6th call of the `rand` function with seed 30. 

If we instead reseed as we flush row converter, and we resume at 26, then we're starting with the 0-th call of the `rand` function with seed 36, instead. So these two numbers are different. 

The only way I could think of to get this work is by re-seeding every row (which might be expensive)

@pbardea looks like you're right: took me a (long) while to figure out but if some of the `random` expressions are targeted then `r.pos` will not increment as many times as `numInstances` (here, `numInstances` actually means `numInstancesPerRow`). Now that I'm typing this part it seems like re-seeding every row is the way to go if we really want to be safe hmm........


<!-- Sent from Reviewable.io -->

2020-08-05 19:55 UTC, miretskiy reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-ME-B2M1DMbb2HHhcxG9:b-td6mr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
<details><summary><i>Previously, Anzoteh96 (Anzo Teh) wrote…</i></summary><blockquote>

I don't think that will do the intended way because:
Say the rowIndex we left off was 26 and importTimeStamp is 10, and `reseedEveryN` is 15. then (26+10) mod 15 is 11 = 36 and this should mean that it will be the 6th call of the `rand` function with seed 30. 

If we instead reseed as we flush row converter, and we resume at 26, then we're starting with the 0-th call of the `rand` function with seed 36, instead. So these two numbers are different. 

The only way I could think of to get this work is by re-seeding every row (which might be expensive)

@pbardea looks like you're right: took me a (long) while to figure out but if some of the `random` expressions are targeted then `r.pos` will not increment as many times as `numInstances` (here, `numInstances` actually means `numInstancesPerRow`). Now that I'm typing this part it seems like re-seeding every row is the way to go if we really want to be safe hmm........
</blockquote></details>

No, you misunderstand.  There is no need to reseed. Always reseed when updating progress to whatever row number is + timestamp.  That's it. No reseeding every N.


<!-- Sent from Reviewable.io -->

2020-08-06 03:42 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-ME-6W3gCoQ5Db42eqAj:b-t6cp84) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

No, you misunderstand.  There is no need to reseed. Always reseed when updating progress to whatever row number is + timestamp.  That's it. No reseeding every N.
</blockquote></details>

Ah, yes we took this detour when coming up with the idea of reseeding every row where we wouldn't need to keep track of progress - but since that would be too slow we can just go back to reseeding on every flush. Refocusing, we can just reseed the RNG when saving progress and then the IMPORT should pick up where it left off by reseeding at the resume point. When we flush we should have access to the source, timestamp and row number.

Separately, I also don't think that we need to maintain 2 random generators.


<!-- Sent from Reviewable.io -->

2020-08-07 21:17 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3268 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDytCi59EC4uoQa8HzA:-ME9kvnTDkzSkqHx67Md:blfmb91) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/ccl/importccl/import_stmt_test.go#L3268)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we add test cases where there are multiple columns that have a default expression with `random()`. Also perhaps one that has both `random()` and `gen_random_uuid()`. Also some tests where those columns are targetted would be useful as well.

I don't remember if we have any tests that exercise IMPORT's resuming logic? If we do, it would be good to see if we could add a test case there to ensure that we can handle the resuming.
</blockquote></details>

Added the test cases for multiple `random()`, mixed `random()` and `gen_random_uuid()`, and also one with a `DEFAULT` column being targeted. 

We have one test at `TestCSVImportCanBeResumed` but judging by the code structure of `TestImportDefault` vs `TestCSVImportCanBeResumed` it will require some significant change for `TestCSVImportCanBeResumed` to be incorporated there. 
___
*[pkg/sql/row/expr_walker.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MDzPe9f9pes_gMzId08:-ME9dkun1GROjWBBkuc4:b-ivuyhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/494d142eaacd935a3b660c25ff8e1974a01a155f/pkg/sql/row/expr_walker.go#L65)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Ah, yes we took this detour when coming up with the idea of reseeding every row where we wouldn't need to keep track of progress - but since that would be too slow we can just go back to reseeding on every flush. Refocusing, we can just reseed the RNG when saving progress and then the IMPORT should pick up where it left off by reseeding at the resume point. When we flush we should have access to the source, timestamp and row number.

Separately, I also don't think that we need to maintain 2 random generators.
</blockquote></details>

So as it turns out (as discussed during the meeting), it will be tricky to re-seed when we save progress for the following reason: 

Suppose we successfully write the progress of row 1024 to the database, and the last seeding/re-seeding was at row 930. Presumably, the database will relay the signal of re-seeding back to the row converter. However, it could happen that by the time the row converter receives this message, it has already processed till row 1040 (i.e. 16 more rows) so the rows 1025-1040 are based on row 930. If a resume happens at this point, then rows 1025-1040 will be written with seed based on row 1024, which causes it to lose determinism. 

I've therefore decided to stick with the method of reseeding every N calls. To ensure that `advancePos` is being called the same number of times as `totalRandInstances`, though (regardless of whether a column is targeted), I call `eval` for each column with default expression (regardless of whether it's targeted). This is an ugly fix, and will require some optimization later on. 
___
*[pkg/sql/row/row_converter.go, line 374 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-ME9m3_J86KU9Cs-kA_e:-ME9m3_J86KU9Cs-kA_f:b-8kp124) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d93ccedccfae09f2288d527a335f545e868e691/pkg/sql/row/row_converter.go#L374)):*
> ```Go
> 			// TODO (anzoteh96): Optimize this part of code when there's no expression
> 			// involving random(), gen_random_uuid(), or anything like that.
> 			datum, err := c.defaultCache[i].Eval(c.EvalCtx)
> ```

Note: this is where expression is always evaluated, but only used (or an error returned upon unsafe import) when the column is non-targeted. 


<!-- Sent from Reviewable.io -->

2020-08-10 13:08 UTC, pbardea approved these changes
This LGTM! I expect that we've not added test cases non-CSV formats due to other issues we've identified around targeting a subset of columns in this format? Could we add a test case for at least Avro, or at least a TODO to add test cases for default expressions once the targeting issues are resolved.

> Reviewed 3 of 8 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-:-MENTjbJEbgIUblV_tmr:b-2vy9qk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MENTcV5DMPYCdjwRY3g:-MENTcV5DMPYCdjwRY3h:bf6ko0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d93ccedccfae09f2288d527a335f545e868e691/pkg/sql/row/expr_walker.go#L25)):*
> ```Go
> 
> // reseedRandEveryN is the number of calls before reseeding happens.
> const reseedRandEveryN = 10000
> ```

Can we change this to 1000 for now and add a TODO to tune it.


<!-- Sent from Reviewable.io -->

2020-08-10 19:11 UTC, Anzoteh96 reviewed
I've added a TODO comment for Avro (since we'll need to fix the targeted column issue). The test structure focuses on `IMPORT INTO` which is exclusive to CSV and AVRO (for now) so these are the only two file formats that make sense to be tested I think. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-:-MEOlePG8_9l8VZCADgY:bn3sr53)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/sql/row/expr_walker.go, line 25 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MENTcV5DMPYCdjwRY3g:-MEOmAPk4Ku8itbxF6E1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d93ccedccfae09f2288d527a335f545e868e691/pkg/sql/row/expr_walker.go#L25)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we change this to 1000 for now and add a TODO to tune it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-13 14:58 UTC, pbardea approved these changes
LGTM mod one testing comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-:-MEcK7mr4zy4C8_YOFvv:bu651jk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3373 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MEcK-cHBJY8GVk884kM:-MEcK-cHBJY8GVk884kN:b54fmyq) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa9bed1b5ac3da6454099104d1c8d4a071bf65f5/pkg/ccl/importccl/import_stmt_test.go#L3373)):*
> ```Go
> 				var numRows int
> 				sqlDB.QueryRow(t, `SELECT COUNT (*) FROM t`).Scan(&numRows)
> 				require.Equal(t, numDistinctRows, len(test.randomCols)*numRows)
> ```

Can we do 2 imports per test case and ensure that there is no overlap in the random columns between the tables?


<!-- Sent from Reviewable.io -->

2020-08-14 14:44 UTC, Anzoteh96 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52247)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @Anzoteh96, @miretskiy, and @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 3373 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/52247#-MEcK-cHBJY8GVk884kM:-MEhQMjY5hYNL_0iLyGO:b-3qtdch) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa9bed1b5ac3da6454099104d1c8d4a071bf65f5/pkg/ccl/importccl/import_stmt_test.go#L3373)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we do 2 imports per test case and ensure that there is no overlap in the random columns between the tables?
</blockquote></details>

Done. (We have 3 imports per test case, in fact). 


<!-- Sent from Reviewable.io -->

2020-08-17 16:53 UTC, pbardea approved these changes
This LGTM - I think we're good to merge.

2020-08-17 16:56 UTC, Anzoteh96 commented
Cool, thanks Paul. 

TFTR everyone! 
bors r=pbardea

2020-08-17 17:38 UTC, merged