server: stub out interface for transaction stats
cockroachdb/cockroach pull request #52251
Opened 2020-08-03 16:00 UTC by solongordon

To support adding transaction-level statistics to the webui, I modified
the existing StatementsResponse to include a new `transactions` field.
Transactions here are defined by the collection of statement
fingerprints within. To allow referencing statements, I added a
statement ID field, which is a hash of the statement fingerprint.

For the moment, transactions in the response are faked out by combining
together statement IDs at random. This is meant to unblock development
on the frontend while we work on populating the response with the real
transaction data.

Release note: None

2020-08-03 16:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52251)
<!-- Reviewable:end -->

2020-08-03 16:25 UTC, solongordon reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52251)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @dhartunian)

___
*[pkg/roachpb/app_stats.proto, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDp7KwGD9bC36l47dOb:-MDp7KwH70PqoqzWEb2i:b-73vrpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/roachpb/app_stats.proto#L152)):*
> ```protobuf
>   // Id is a hash of the query fingerprint which can be used to identify the
>   // statement, for instance in transaction statistics.
>   optional string id = 8 [(gogoproto.nullable) = false];
> ```

@dhartunian Is it easy enough to use this ID to create an `id -> statement` map on the frontend side? Or is it worth monkeying with the response format so that the statement statistics would already be in that format?


<!-- Sent from Reviewable.io -->

2020-08-04 15:33 UTC, arulajmani requested changes
Some minor nits, the only question I have is how this new proto interacts with `TxnStats`, which is used by `appStats` currently. Maybe we should collapse both these structures into 1? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-:-MDu5PAq9D59grVwK__S:b-85ibgn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dhartunian, and @solongordon)

___
*[pkg/roachpb/app_stats.proto, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDu4Yj9-KVSn0Wjek9a:-MDu4Yj9-KVSn0Wjek9b:b-hblrme) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/roachpb/app_stats.proto#L92)):*
> ```protobuf
> }
> 
> message TransactionStatistics {
> ```

Can/should we unify this with `TxnStats`? 
___
*[pkg/roachpb/app_stats.proto, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDtoiHo1iIc0J5dQTRQ:-MDtoiHo1iIc0J5dQTRR:b-xxknxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/roachpb/app_stats.proto#L98)):*
> ```protobuf
> 
>   // Count is the total number of times this transaction was executed
>   // since the begin of the reporting period.
> ```

nit: s/begin/beginning/
___
*[pkg/roachpb/app_stats.proto, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDtjLIUD-Pedll-gdgW:-MDtjLIV7kj0q3W4PnBn:b-cg15kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/roachpb/app_stats.proto#L109)):*
> ```protobuf
>   optional NumericStat num_rows = 4 [(gogoproto.nullable) = false];
> 
>   // ServiceLat is the time to service the transaction, from start of parse to
> ```

nit: it might be nice to re-word this comment as "time to service the transaction, from the time a transaction was received to end of execution".  

I'm not sure if there could be a delay between a query being received and parsing starting, but we calculate service latency using `TimeReceived`. 
___
*[pkg/server/statements.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDtqF2EAlYlF2WDKhFw:-MDtqF2EAlYlF2WDKhFx:b-nmcpqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/server/statements.go#L105)):*
> ```Go
> 		for _, stmt := range response.Statements[i : i+numStatements] {
> 			txnStats.StatementIds = append(txnStats.StatementIds, stmt.Key.KeyData.Id)
> 			txnStats.Count++
> ```

Can we stub this out to something random instead of the number of statements in the transaction? I got confused for a second by what `Count` was referring to until I saw the comment on the proto. 
___
*[pkg/server/serverpb/status.proto, line 805 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52251#-MDu4n4T6w0RJVNVbl0J:-MDu4n4T6w0RJVNVbl0K:bfxiyzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/60c772bb58a2b9249364a964d0282a6c6a404661/pkg/server/serverpb/status.proto#L805)):*
> ```protobuf
> }
> 
> message StatementsResponse {
> ```

Should we update this name? I don't like the idea of a `StatementResponse` encompassing both statement and transaction statistics. 


<!-- Sent from Reviewable.io -->

2020-08-24 13:52 UTC, solongordon commented
Incorporated into #52704

2020-08-24 13:52 UTC, closed without merging