monitoring: update with MSO rules
cockroachdb/cockroach pull request #52312
Opened 2020-08-04 00:19 UTC by taroface

Relates to https://github.com/cockroachdb/docs/issues/7718. See [comment](https://github.com/cockroachdb/docs/issues/7718#issuecomment-655613091).

- Added rules from https://github.com/cockroachlabs/managed-service/blob/master/conf/monitoring/rules/alerts.cockroach.yml
- A few rules in this file (`InstanceDown`, `LivenessMismatch`, `NoLeaseRanges`, `ZeroSQLQps`) are not in the MSO file. Should they be added to that config?
- The comment ` # This alert is intentionally loose (4 hours) to allow for rolling upgrades.` was updated to account for the changed value (original: 30 min) in this rule. However, the comment is not updated [in the MSO rule](https://github.com/cockroachlabs/managed-service/blob/master/conf/monitoring/rules/alerts.cockroach.yml#L54) so I'm not sure if 4 hours specifically makes sense for rolling upgrades or if there is some other reason the time was increased from 30 min.
- Note that the `InstanceRestart` timeframe has changed.
- @piyush-singh mentioned some backup failure alerts that should be added to these rules; I still need to track them down.

2020-08-04 00:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52312)
<!-- Reviewable:end -->

2020-08-19 18:52 UTC, taroface commented
@piyush-singh @dhartunian ping for review!

2020-08-20 17:28 UTC, piyush-singh requested changes
> A few rules in this file (InstanceDown, LivenessMismatch, NoLeaseRanges, ZeroSQLQps) are not in the MSO file. Should they be added to that config?

I'd argue that this actually means we should probably remove them from this public alerting file. I think the SRE team has pruned back alerts to only the meaningful ones they will actually care about. For example, ZeroQPS - for a small app with not too much traffic, this probably doesn't make sense as an alert since it would probably fire overnight every night when traffic drops. In general though, I think we shouldn't push changes to the MSO repo without asking SREs since I believe that is their production repository for alert definitions for Cockoach Cloud. 

> The comment # This alert is intentionally loose (4 hours) to allow for rolling upgrades. was updated to account for the changed value (original: 30 min) in this rule. However, the comment is not updated in the MSO rule so I'm not sure if 4 hours specifically makes sense for rolling upgrades or if there is some other reason the time was increased from 30 min.

I think we intentionally have set this to a high value to allow larger clusters to go through the rolling upgrade process with time in between each node being upgraded to allow the cluster to stabilize. 

> Note that the InstanceRestart timeframe has changed.

:+1: I can ask about why this change was made.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-:-MFB9AGf3_d6vnixR21y:b-4gu8px)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @piyush-singh, and @taroface)

___
*[monitoring/rules/alerts.rules.yml, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFB8eMR0AUo_uIFXRlC:-MFB8eMR0AUo_uIFXRlD:bzhkmtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L22)):*
> ```YAML
>   # Alert for any instance that is not ready for a while.
>   - alert: InstanceNotReady
>     expr: kube_statefulset_status_replicas_ready{statefulset="cockroachdb"} != kube_statefulset_status_replicas{statefulset="cockroachdb"}
> ```

This is Kubernetes specific. Should we include these in the default set of alerts? Perhaps we could include this commented out and note that it is relevant only if you are deployed via K8s? I also don't know enough about K8s to know if this would "just work". Are there additional configs we would need to set to get his to work correctly?
___
*[monitoring/rules/alerts.rules.yml, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBtxLC6qgRP94CaylB:-MFBtxLD40lfLxrdQY9z:bqv0eg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L25)):*
> ```YAML
>     for: 45m
>     labels:
>       priority: P4
> ```

These priority labels reflect our internal mapping of priorities for these alerts. It may be useful for us to suggest how to categorize the priority of these alert, but perhaps we can leave them commented out as suggestions? This may vary user to user. On the other hand, having this out of the box is kind of nice if you don't know the system and can't tell if something is a drop everything emergency vs something you should look at within the next 24 hrs.
___
*[monitoring/rules/alerts.rules.yml, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBmRRV-Hg2yeCVYqFx:-MFBmRRX4CT2L7aPcHpZ:b-ujhroa) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L41)):*
> ```YAML
>   # Alert on flapping instances (frequent restarts).
>   - alert: InstancesFlapping
>     # Aggregated. We commit to not updating so fast this is triggered except in emergency.
> ```

This seems like a comment that is more internal for the SRE team. Perhaps we can update this with guidance: "This alert assumes that rolling restarts or rolling upgrades leave at least 3 minutes between each node being updated or restarted." 
___
*[monitoring/rules/alerts.rules.yml, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBtZ4pB_WqbAaEyzak:-MFBtZ4r21EEPV_2BwN-:b95zikm) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L42)):*
> ```YAML
>   - alert: InstancesFlapping
>     # Aggregated. We commit to not updating so fast this is triggered except in emergency.
>     # Update automation sleeps 3m between pod updates!
> ```

We should remove this as it is specific to our K8s setup for CockroachCloud.


<!-- Sent from Reviewable.io -->

2020-08-27 18:20 UTC, taroface reviewed
OK, I removed the rules here that are not in the MSO file. Also added one that I missed previously!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-:-MFgebzP7-oe_nE1EKn_:b-jltrgi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @joshimhoff, and @piyush-singh)

___
*[monitoring/rules/alerts.rules.yml, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFB8eMR0AUo_uIFXRlC:-MFghAGD4q-BMOCwhoYQ:b-6h815d) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L22)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

This is Kubernetes specific. Should we include these in the default set of alerts? Perhaps we could include this commented out and note that it is relevant only if you are deployed via K8s? I also don't know enough about K8s to know if this would "just work". Are there additional configs we would need to set to get his to work correctly?
</blockquote></details>

My feeling is that this would work as long as they have a StatefulSet named `cockroachdb`, which is the default in our public configs (used in our docs). @joshimhoff can you comment here?
___
*[monitoring/rules/alerts.rules.yml, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBtxLC6qgRP94CaylB:-MFkhfZAEbzhj-hfSrRp:bc0di08) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L25)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

These priority labels reflect our internal mapping of priorities for these alerts. It may be useful for us to suggest how to categorize the priority of these alert, but perhaps we can leave them commented out as suggestions? This may vary user to user. On the other hand, having this out of the box is kind of nice if you don't know the system and can't tell if something is a drop everything emergency vs something you should look at within the next 24 hrs.
</blockquote></details>

P4 seems to be the only priority ranking here, so I'm just going to remove it for simplicity's sake.
___
*[monitoring/rules/alerts.rules.yml, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBmRRV-Hg2yeCVYqFx:-MFl8Equ2hgZ6WQ4aQPd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L41)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

This seems like a comment that is more internal for the SRE team. Perhaps we can update this with guidance: "This alert assumes that rolling restarts or rolling upgrades leave at least 3 minutes between each node being updated or restarted." 
</blockquote></details>

Done.
___
*[monitoring/rules/alerts.rules.yml, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52312#-MFBtZ4pB_WqbAaEyzak:-MFl8G0b29fZhajSimWH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/282f228768791b50fd1a27b074fcd56c379a9659/monitoring/rules/alerts.rules.yml#L42)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

We should remove this as it is specific to our K8s setup for CockroachCloud.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-01 17:17 UTC, piyush-singh approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52312)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @joshimhoff, and @piyush-singh)



<!-- Sent from Reviewable.io -->

2020-09-01 18:43 UTC, taroface commented
bors r+

2020-09-01 19:39 UTC, merged