coldata: minor tweak of flat bytes
cockroachdb/cockroach pull request #52369
Opened 2020-08-04 22:09 UTC by yuzefovich

This commit changes several things:
- removes some unnecessary operations in `Set` function
- fixes updating `maxSetIndex` field in `AppendSlice` in the case when
we're appending zero length value
- possibly utilizes better already allocated memory under `data` slice
in `AppendSlice`
- increases the size of global zero slice used in `Reset` method (this
should have some performance improvement).

Release note: None

2020-08-04 22:10 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52369)
<!-- Reviewable:end -->

2020-08-06 12:52 UTC, asubiotto reviewed
Please add tests for fixes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-:-ME2p1fD5Hw2VqefvvsO:bf44lzx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-08-06 15:31 UTC, yuzefovich commented
There was only one "fix" which turned out to not have any impact, so I removed it but kept the test that "fix" was trying to resolve. RFAL.

2020-08-07 15:53 UTC, asubiotto requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52369)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8bmmb1xemN9shNZ7x:-ME8bmmc4VEfSquelnbH:b-cvi2a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L310)):*
> ```Go
> 		// the index of the actual last element, so it is safe to update it
> 		// unconditionally.
> 		b.maxSetIndex = destIdx - 1
> ```

The commit message says `possibly utilizes better already allocated memory under data slice in AppendSlice`. How does this code translate to that result?
___
*[pkg/col/coldata/bytes.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8b03O5rsjM3LrmXxK:-ME8b03O5rsjM3LrmXxL:b5f4q0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L356)):*
> ```Go
> 	b.maybeBackfillOffsets(b.Len())
> 	b.data = append(b.data[:b.offsets[b.Len()]], v...)
> 	b.maxSetIndex = b.Len()
> ```

Is this correct? In the previous code setting `b.maxSetIndex` happened before the append.


<!-- Sent from Reviewable.io -->

2020-08-07 16:19 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52369)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/bytes.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8bmmb1xemN9shNZ7x:-ME8g22YCJhkZMQD9LFK:bride8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L310)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The commit message says `possibly utilizes better already allocated memory under data slice in AppendSlice`. How does this code translate to that result?
</blockquote></details>

It is not about the change in this `if` block, it's related to the change below.
___
*[pkg/col/coldata/bytes.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8g8XW0biPsDBIXk_Z:-ME8g8XW0biPsDBIXk__:b608zr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L355)):*
> ```Go
> 	}
> 	b.maybeBackfillOffsets(b.Len())
> 	b.data = append(b.data[:b.offsets[b.Len()]], v...)
> ```

Here, I think previously we could have "unclaimed" space in `b.data` if the last elements were unset.

Consider the following scenario:
- create a flat bytes vector with 2 elements; we now have `len(b.data) == 128`, `b.Len() == 2`, `b.offsets = [0, 0, 0]`
- set the first element to some value, let's say "zero";  `b.data[0:4] == "zero"`, `b.offsets = [0, 4, 0]`
- we then append value "two". Previously we would get `b.data[128:131] == "two"`, `b.offsets = [0, 4, 128, 131]` with a "no-man's land in-between", and now we will get `b.data[0:7] == "zerotwo"`, `b.offsets = [0, 4, 4, 7]`.
___
*[pkg/col/coldata/bytes.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8b03O5rsjM3LrmXxK:-ME8gRTG7iAudTXaauVh:b-wlne0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L356)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this correct? In the previous code setting `b.maxSetIndex` happened before the append.
</blockquote></details>

It doesn't really matter - note that this is Go native `append`, not `AppendSlice`, and the former doesn't know about `maxSetIndex`.


<!-- Sent from Reviewable.io -->

2020-08-10 16:21 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-:-MEOAFCV2ngTTuz8OGfe:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8g8XW0biPsDBIXk_Z:-MEO9V-EBaPrkCu7-6Yj:b-2awp9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L355)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Here, I think previously we could have "unclaimed" space in `b.data` if the last elements were unset.

Consider the following scenario:
- create a flat bytes vector with 2 elements; we now have `len(b.data) == 128`, `b.Len() == 2`, `b.offsets = [0, 0, 0]`
- set the first element to some value, let's say "zero";  `b.data[0:4] == "zero"`, `b.offsets = [0, 4, 0]`
- we then append value "two". Previously we would get `b.data[128:131] == "two"`, `b.offsets = [0, 4, 128, 131]` with a "no-man's land in-between", and now we will get `b.data[0:7] == "zerotwo"`, `b.offsets = [0, 4, 4, 7]`.
</blockquote></details>

I'm not sure I understand this example, where is `len(b.data)==128` coming from?
___
*[pkg/col/coldata/bytes.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8b03O5rsjM3LrmXxK:-MEO9evbEAnfXfxP5D0z:b-2pouh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L356)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

It doesn't really matter - note that this is Go native `append`, not `AppendSlice`, and the former doesn't know about `maxSetIndex`.
</blockquote></details>

Ah got it.


<!-- Sent from Reviewable.io -->

2020-08-10 16:22 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-:-MEOAWm67ZPE6OSCXKfW:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/bytes.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8g8XW0biPsDBIXk_Z:-MEOAOFtBCLcmyi3m-iw:b-h31qzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L355)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I understand this example, where is `len(b.data)==128` coming from?
</blockquote></details>

That's from "bytes allocation factor" - we preallocate 64 bytes for each element of the flat bytes vector.
___
*[pkg/col/coldata/bytes.go, line 356 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52369#-ME8b03O5rsjM3LrmXxK:-MEOAVolDRXd991ZtWUl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/db29aadc51cc5ce5692028c177bd363a045f8fc5/pkg/col/coldata/bytes.go#L356)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Ah got it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-10 16:50 UTC, merged