[wip,dnm] *: connect rpc
cockroachdb/cockroach pull request #52526
Opened 2020-08-08 00:20 UTC by irfansharif

Don't look, running CI.

2020-08-08 00:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52526)
<!-- Reviewable:end -->

2020-08-11 04:36 UTC, irfansharif commented
@tbg, this is not complete yet but should be ready for a sanity check now. The remaining TODOs (including testing) are relatively minor. I'm looking to add on top of this base commit, in this PR, changes to disallow mismatched version nodes from joining. In a separate PR I'll patch on the changes to disallow decomm'ed nodes from joining (which is a bit more involved, and follows the ideas discussed in the context of #48843).

2020-08-12 17:35 UTC, knz reviewed
I reviewed all this in detail except the changes to `server/init.go`. All that I reviewed looks good (with nits).

For `server/init.go` I'm still a bit :microscope: :dog: . Probably I can review this after we chat and you explain me what's going on in prose.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MEYjH0YE7lGzAIvJKdG:b-9vekiu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/cli/start.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYfxu3BjpibBVzYxmW:-MEYfxu3BjpibBVzYxmX:b-7k1rpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7a63106e5fb11574b470929dab2c145ca8fd34/pkg/cli/start.go#L673)):*
> ```Go
> 		if waitForInit {
> 			log.Shout(ctx, log.Severity_INFO,
> 				"initial startup completed.\n"+
> ```

Was there a reason to change this?
___
*[pkg/cmd/roachtest/decommission.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg08QByaPeZ2RSM6j:-MEYg08QByaPeZ2RSM6k:b-u5lr1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/cmd/roachtest/decommission.go#L323)):*
> ```Go
> 
> 	// XXX: Hack, to see node come into liveness table. We should do this as
> 	// part of the connect rpc.
> ```

reminder to remove this before the PR gets merged.
___
*[pkg/gossip/client.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg9NO666h6FQUvMDs:-MEYg9NO666h6FQUvMDt:b6my1fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/gossip/client.go#L278)):*
> ```Go
> 	// being done by an incoming client, either because an outgoing
> 	// matches an incoming or the client is connecting to itself.
> 	if nodeID := g.NodeID.Get(); nodeID != 0 && nodeID == c.peerID {
> ```

How do you plan to detect loopback connections when the nodes don't have an ID yet?
___
*[pkg/server/init.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhXr_5YO897QF7I6_:-MEYhXr_5YO897QF7I6a:b-cl7xi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L54)):*
> ```Go
> //
> // TODO(irfansharif): Remove this in 21.1.
> var ErrJoinRPCUnimplemented = fmt.Errorf("node does not implement join rpc")
> ```

"rpc" in capitals
___
*[pkg/server/init.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhhuc09_yPB4L8v6f:-MEYhhuc09_yPB4L8v6g:bk74hv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L107)):*
> ```Go
> 	// propagates the cluster ID to the rest of the nodes).
> 	//
> 	// TODO(irfansharif): This last sentence is not yet true. Update this list
> ```

Second sentence has has two verbs.
___
*[pkg/server/init.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYiipd-3IBtNdECiTV:-MEYiipd-3IBtNdECiTW:b5nxksh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L265)):*
> ```Go
> 			}
> 
> 			log.Infof(ctx, "**** cluster %s has been created", state.clusterID)
> ```

Here and below: drop the `****` - we don't do magic characters.
(if you need markers for your own debugging, add *additional* log lines with e.g. `log.Warningf(ctx, "XXX")` which you'll remove before merging the PR)
___
*[pkg/server/server.go, line 1021 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhOTi0NEjWXv-ItsJ:-MEYhOTi0NEjWXv-ItsK:bfvphot) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/server.go#L1021)):*
> ```Go
> // should represent the general startup operation.
> //
> // XXX: Write a summary. What are _all_ the components I care about?
> ```

if you need help we can chat

(reminder to remove the comment before the PR merges)
___
*[pkg/server/server.go, line 1301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhFiu8hBuUY3ox--e:-MEYhFiu8hBuUY3ox--f:b-lajafv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/server.go#L1301)):*
> ```Go
> 
> 	// We need gossip to get spun up before the init server (which internally
> 	// makes use of KV to allocate node IDs_. In an ideal world we'd be able to
> ```

stray `_`
___
*[pkg/server/server.go, line 1307 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhJcj693H6YKbuIor:-MEYhJcj693H6YKbuIos:b2paaxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/server.go#L1307)):*
> ```Go
> 	// example:
> 	//
> 	//   In a two node cluster where n1 is started+bootstrapped, when n2
> ```

`id` -> `ID` throughout the comment
___
*[pkg/server/server.go, line 1394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYgwCaCQ9yLqPfW0XQ:-MEYgwCaCQ9yLqPfW0XR:bkmxka2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/server.go#L1394)):*
> ```Go
> 		// prevent bugs during further refactors).
> 		if s.rpcContext.ClusterID.Get() == uuid.Nil {
> 			return errors.New("programming error: expected cluster id to be populated in rpc context")
> ```

`New("programming error: ...` -> `AssertionFailedf("...`
___
*[pkg/server/server.go, line 1413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYguPD3_XqNDtPBbw3:-MEYguPD3_XqNDtPBbw4:bdp9t41) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/server.go#L1413)):*
> ```Go
> 	// when a quorum of nodes has gone fully operational.
> 	_ = s.stopper.RunAsyncTask(ctx, "connect-gossip", func(ctx context.Context) {
> 		log.Infof(ctx, "connecting to gossip network to verify cluster id %q", state.clusterID)
> ```

`id` in uppercase.
___
*[pkg/server/serverpb/init.proto, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYgcoR4OZ84ZVCZTPS:-MEYgcoR4OZ84ZVCZTPT:b-75d4lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/serverpb/init.proto#L29)):*
> ```protobuf
>   // TODO(irfansharif): Use this field to provide the client's address so that
>   // the server is able to reach back to it, setting up bidirectional network
>   // links.
> ```

Add a comment that the field should be populated with the advertised address if different from the listen address..
___
*[pkg/server/serverpb/init.proto, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYgoIj-35f5KCGKFRJ:-MEYgoIj-35f5KCGKFRK:b-7w6j4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/serverpb/init.proto#L47)):*
> ```protobuf
> 
> service Init {
>   // Bootstrap an uninitialized cluster (inter-node links set up through the
> ```

I don't understand the phrasing of the comment. Can you perhaps use more words?


<!-- Sent from Reviewable.io -->

2020-08-13 16:21 UTC, tbg requested changes
This looks pretty good, though there is one major change that I suggested (in a few places, sorry about being a broken record): the join RPC should live on `*node`. It has no business being served by the early stages of startup since it requires a fully functional server.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MEcbuIcBWXSlBdCwsII:b-f9txco)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/server/init.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcQkHID0NxNy4u7nkk:-MEcQkHID0NxNy4u7nkl:b-fiqkkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L100)):*
> ```Go
> 
> 	// We hold onto a *kv.DB object to assign node IDs through the Join RPC.
> 	db *kv.DB
> ```

I'm not sure why this is here. The initServer should only be used in the early phase of startup (i.e. before we start the `*node` and, down the road, ideally before connecting gossip). In that early phase, we can't reliably use the `*kv.DB`. I expected the join RPC to live on `InternalServer` (i.e. `*node`) just like most other KV endpoints.
___
*[pkg/server/init.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcRKGT4PqmISToQ539:-MEcRKGT4PqmISToQ53A:b-wcvh8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L113)):*
> ```Go
> 	// it. We'll need to make sure that each server loops through its join list
> 	// at least once so that the "links" are setup. We don't want get
> 	// insta-bootstrapped and never set up those links.
> ```

If we have a connected graph, I don't think we need this? In a connected graph, for any node A and B, there is a path from A to B (i.e. A joins X joins .... joins Z joins B) for any A and B. The nodes that are directly adjacent to initialized nodes can join it and become themselves initialized. This means that in a finite number of iterations all nodes have joined.

It's more weakly connected graphs that are tricky. If n1 joins n2 joins n3 and we initialize n1, then naively nothing will happen. Even with your proposed fix (n1 tries to reach out to n2 at least once) we might be in trouble because what if n2 is not reachable when n1 tries that? It basically has to keep doing this forever and forever. Nodes can also swap addresses; an n2 that was earlier reached may now be a new node in need of incoming contact in order to be able to join. So to really fix this, we have to reach out to everyone ~periodically. Note that not even gossip does that! The above example with Gossip will "usually" work because n1 will establish outgoing Gossip connections, will reach n2, and since n2 has Gossip running n1 learns about n3, etc (though n2 would also directly Gossip to n3). However, this is just the example that works. Nodes don't generally connect to every other node; in a very large cluster n1 might be perfectly happy with its gossip connectivity and would never reach out to n2 or n3, which would perpetually stay isolated.
We have "gossip bootstrap persistence" to hack around our lack of clarity here - nodes remember and auto-load all of the recent addresses observed in the cluster. That too is only a best effort mechanism, as all of these addresses might have changed again by the time they are used.

I think when it comes down to it, at the time of writing, the real requirement that we have in order to have a converging network is in fact a connected graph. This is fine to work with if you have a load balancer, but it's awkward for manual deployments - we don't want to change all nodes' join flags whenever a new node joins. So our guidance has been to point everyone at a "few" common nodes to make it "highly likely" that convergence will happen (since everyone will connect to the same few nodes).

This all seems unsatisfying, but there's not enough pain to really do much about it, in practice the band aids we have work rather well: manual deployments are mostly static (and follow the "everyone joins n1-n3") pattern, so they work well.

I would be inclined to say that it is fine that, when a node is joining a cluster, it needs to directly be able to reach one node that has already joined (or will eventually) join the cluster. This is because this is intuitively easy to understand - a node that isn't pointed at the existing cluster can't quite be added to it.
___
*[pkg/server/init.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcVOsE1EkU-2uGPzWU:-MEcVOsE1EkU-2uGPzWV:bl0p28e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L205)):*
> ```Go
> // easy.
> //
> // TODO(tbg): give this a KV client and thus initialize at least one store in
> ```

Isn't this TODO mostly done now, mod the migration?
___
*[pkg/server/init.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcWWQLDYUfJiGFBCNG:-MEcWWQLDYUfJiGFBCNH:b-3gc5lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L268)):*
> ```Go
> 			log.Infof(ctx, "**** allocated node id %d for self", state.nodeID)
> 
> 			s.inspectState.clusterID = state.clusterID
> ```

data race? You're not holding the mutex and `Bootstrap` reads this for `NeedsInit`.
___
*[pkg/server/init.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcWrqcEZ74Tz_JxEkk:-MEcWrqcEZ74Tz_JxEkl:b9rd2wd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L290)):*
> ```Go
> 			s.inspectState.clusterID = state.clusterID
> 			// Ensure we're draining out join attempt.
> 			cancelJoin()
> ```

why do we have to cancel it? It just sent on the channel, so it should know it's done and shut down?
___
*[pkg/server/init.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcX2ao2jXqzcH4BOdi:-MEcX2ao2jXqzcH4BOdj:bto3rh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L308)):*
> ```Go
> 			// support). Commence startup; the Node will realize it's short a
> 			// NodeID and will request one.
> 			clusterID, err := gossip.GetClusterID()
> ```

Don't shadow the package name here.
___
*[pkg/server/init.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcXN3w8sUwE0zlWEmx:-MEcXN3w8sUwE0zlWEmy:bsrgzyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L328)):*
> error attempting to join: %v
___
*[pkg/server/init.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcXfc_0LSgsodDEmc_:-MEcXfcaDh0E1911Ke8F:b-4w92uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L382)):*
> ```Go
> // record here so as to no longer have to worry about the liveness record not
> // existing for a given node.
> func (s *initServer) Join(
> ```

As mentioned elsewhere, it seems that this lives in the wrong place. Join RPCs are served by full-fledged KV nodes, not by the initServer. The initServer should not do anything any more once it has handed out a NodeID. By extension, the initServer should not have a `*kv.DB`.
___
*[pkg/server/init.go, line 409 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcY4UE-Asl8yBlPCAB:-MEcY4UE-Asl8yBlPCAC:bund9e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L409)):*
> ```Go
> 
> func (s *initServer) startJoinLoop(ctx context.Context, stopper *stop.Stopper) error {
> 	dialOpts, err := s.rpcContext.GRPCDialOptions()
> ```

Can you try handing only what's needed from `rpcContext` instead of the whole thing? `rpc.Context` is large and we do make changes [...]

2020-08-20 05:30 UTC, irfansharif reviewed
I've addressed most of the comments here, mind taking another quick look @tbg? I'd normally only ask after it was a bit more polished but I'm a bit pressed for time this week, and am really hoping to land this pre-stability to make 21.1 code a bit easier. I might have to solicit another review before end of day. I'll have another commit I'm going to push to this PR after, building atop #53113, that tests all the behaviors we're interested in (including in mixed-version clusters).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MF9KIFZ6_JJfv0-15h6:bsqdc7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/cli/start.go, line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYfxu3BjpibBVzYxmW:-MEyYM1g2gvvDEaOwrJX:b-9rntu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b7a63106e5fb11574b470929dab2c145ca8fd34/pkg/cli/start.go#L673)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Was there a reason to change this?
</blockquote></details>

Only su[erficially; I've been starting at start up logs a fair amount while working on this and wanted this log to looks similar to other logging that happens during startup. Some of the other logging changes I made in this PR were motivated similarly by wanting to de-dup/simplify what we logged during start up.
___
*[pkg/cmd/roachtest/decommission.go, line 323 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg08QByaPeZ2RSM6j:-MExOW-y4ezATLj96Xx5:b-sv9bf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/cmd/roachtest/decommission.go#L323)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

reminder to remove this before the PR gets merged.
</blockquote></details>

Yup, I use these XXX tags as markers for myself when working on something. I somehow got my IDE to spit out a list of these on demand.
___
*[pkg/server/init.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhXr_5YO897QF7I6_:-MExOrWrEeGrixaOXUMv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L54)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"rpc" in capitals
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcQkHID0NxNy4u7nkk:-MExOtDO3vMacFq2SZYa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L100)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I'm not sure why this is here. The initServer should only be used in the early phase of startup (i.e. before we start the `*node` and, down the road, ideally before connecting gossip). In that early phase, we can't reliably use the `*kv.DB`. I expected the join RPC to live on `InternalServer` (i.e. `*node`) just like most other KV endpoints.
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYhhuc09_yPB4L8v6f:-MExV2aV6Tm2wRTcLHIF:bjw2wgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L107)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Second sentence has has two verbs.
</blockquote></details>

The comment was removed entirely, we're not going to do it anymore.
___
*[pkg/server/init.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcRKGT4PqmISToQ539:-MF9K-PaDq6Snp8Jl6LG:bqf3pff) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L113)):*
> I would be inclined to say that it is fine that, when a node is joining a cluster, it needs to directly be able to reach one node that has already joined (or will eventually) join the cluster. This is because this is intuitively easy to understand - a node that isn't pointed at the existing cluster can't quite be added to it.

I think I'm happy with this conclusion. It got pretty unwieldy trying to re-implement bidirectional gossip through RPCs.
___
*[pkg/server/init.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcVOsE1EkU-2uGPzWU:-MExXw4p-QqZ2BPoO0nO:b-24zpi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L205)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't this TODO mostly done now, mod the migration?
</blockquote></details>

I still need to seed the first store ID through the join RPC, but I've moved this TODO elsewhere.
___
*[pkg/server/init.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYiipd-3IBtNdECiTV:-MExbL4u7Oe-T3plgT11:bkmodnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L265)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here and below: drop the `****` - we don't do magic characters.
(if you need markers for your own debugging, add *additional* log lines with e.g. `log.Warningf(ctx, "XXX")` which you'll remove before merging the PR)
</blockquote></details>

Done. The "****" characters were there from before, and I figured they were to to call out bootstrap related logging (and that's the convention I followed). I've now removed the additions I made.
___
*[pkg/server/init.go, line 268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcWWQLDYUfJiGFBCNG:-MF1-DKtAwqlAyWU-nIN:bxweaep) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L268)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

data race? You're not holding the mutex and `Bootstrap` reads this for `NeedsInit`.
</blockquote></details>

Done (was leftover as a TODO I wanted to address in this PR).
___
*[pkg/server/init.go, line 290 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcWrqcEZ74Tz_JxEkk:-MF0petUDiPz1OAaDI5V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L290)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

why do we have to cancel it? It just sent on the channel, so it should know it's done and shut down?
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcX2ao2jXqzcH4BOdi:-MEycbKREiWdFZMMzXuR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L308)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Don't shadow the package name here.
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcXN3w8sUwE0zlWEmx:-MEycdW1657lB3Sa3OWy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L328)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> error attempting to join: %v
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 382 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcXfc_0LSgsodDEmc_:-MExehym1u3jjWxsxUKm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L382)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

As mentioned elsewhere, it se [...]

2020-08-20 11:29 UTC, tbg reviewed
Sure! This looks mostly good. I left lots of comments but the real work remaining here is to clarify the story of what comes next. Maybe I'm wrong, but it seemed like you were perhaps assuming that nodes would always call into `Join` when they start (but it's not how the code is written). Or perhaps they don't need to and the version protection is still fine (since, once we've reached our goal, versions can only changed when all nodes ack them)? There's a good chance I've since paged out a bit too much and you have to remind me of what the plan is, but either way it will be good to dump it in a TODO before we merge to avoid surprises along the way.
I'm very excited that on the "new master branch" we will be allowed to start gossip later, and that we will always have a NodeID (and StoreID, I hope you will get to that as well! Seems like a small step from this PR).

> Reviewed 7 of 14 files at r1, 7 of 7 files at r2, 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MFAbU1U41bLRsUdIyO7:bl81s9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/gossip/client.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg9NO666h6FQUvMDs:-MFAS2N70sK01RZ_L8-o:b-mhqwhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/gossip/client.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

How do you plan to detect loopback connections when the nodes don't have an ID yet?
</blockquote></details>

What made this change necessary, btw? Were you seeing nodes kill their gossip connections when they both didn't have a nodeID yet?

It's nice to know that, a cycle in from this PR, we won't ever use Gossip without NodeIDs any more.
___
*[pkg/roachpb/api.proto, line 2199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOZOj1S7FnO9fkZIu:-MFAOZOj1S7FnO9fkZIv:bqozg97) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2199)):*
> ```protobuf
> }
> 
> // JoinNodeRequest is used to specify to the server node what the client's
> ```

This isn't really what it's used for, no? It primarily requests a NodeID and StoreID.

In the end, we will have two RPCs- Join (which needs to be served by a live KV layer) and ... Connect/PreJoin (?) which checks against the node-local blocklist (decommissioned nodes).

I think that ultimately the startup sequence will be that nodes will always use `Connect` against another node very early and then use Join (if they don't have a NodeID yet). This would make it more attractive to run the version check in`Connect` (since it's earlier). In fact I don't think we *can* do it in `Join`, since that is only served on nodes that have KV running (so if you restart a fully down cluster, nodes would never be able to serve join each other).

I think we need to do this in `Connect` (with the caveat that a node will only *serve* connect after it itself has made it past its outgoing `Connect` call (to ensure the cluster won't bump the version without notifying the client)) and then we have to check it again during `Join` if we call it (as only that adds the new nodeID to the liveness table, making sure that version bumps won't happen in a racy way). In practice, I think that means that `Join` should also run whatever code backs `Connect` internally (meaning it needs to have the min_supported_version) field. So - this code is fine, but maybe, more accidentally than intentionally? Brain dump a comment here so we can merge this. No need to implement this fully in this PR, I am fine with TODOs, but we should know the definite path forward.
___
*[pkg/roachpb/api.proto, line 2210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOW7_EsoePwAIlySN:-MFAOW7_EsoePwAIlySO:b-dngltq) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2210)):*
> ```protobuf
> // node id was allocated to it.
> //
> // TODO(irfansharif): Think about the semantics for how store IDs get allocated.
> ```

+1 to exactly one
___
*[pkg/roachpb/api.proto, line 2214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOUs_7fM6ByPPQ73z:-MFAOUs_7fM6ByPPQ74-:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2214)):*
> ```protobuf
> // and entrust the node itself to allocate IDs for the remaining stores.
> //
> // TODO(irfansharif): We should use this RPC to tell us the right cluster
> ```

+1
___
*[pkg/rpc/context.go, line 511 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAQu2cC4kF6khw82kF:-MFAQu2cC4kF6khw82kG:bfzwp5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/rpc/context.go#L511)):*
> ```Go
> 	ctx context.Context, req *roachpb.JoinNodeRequest, _ ...grpc.CallOption,
> ) (*roachpb.JoinNodeResponse, error) {
> 	return a.InternalServer.Join(ctx, req)
> ```

We could refuse those - node should never join itself. I'm not sure it's worth breaking the pattern of this code though,  let's leave as is.
___
*[pkg/server/init.go, line 265 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYiipd-3IBtNdECiTV:-MFAXPlMAxPQgE8IQWqZ:b-f7jdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L265)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Done. The "****" characters were there from before, and I figured they were to to call out bootstrap related logging (and that's the convention I followed). I've now removed the additions I made.
</blockquote></details>

Might just remove the `*****` while you're here. Raphael is adding some linters.
___
*[pkg/server/init.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcZMwE-x1fHQ_N0JJX:-MFAMlB9AzUpUvaHHEGk:b-qi7mmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L472)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we _want_ to blindly retry for general errors? Only instance I know I'd want to retry is when the server node is not yet available; what are the other possible error conditions that merit retrying?
</blockquote></details>

I think we would blindly retry. The node is trying to join the cluster, it will need to reach a node at some point, so it should go around its join list and try (with backoff) until something works. This is similar to how Gossip will try forever to connect. It won't give up.
___
*[pkg/server/init.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFATh0D-8A5NPz2F-bV:-MFATh0D-8A5NPz2F-bW:b-y8lvv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L95)):*
> ```Go
> 	dialOpts []grpc.DialOption,
> 	inspectState *initDiskState,
> 	config initServerCfg,
> ```

why aren't the dial opts in the config?
___
*[pkg/server/init.go, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWAKSCh6KFL1_m3Fi:-MFAWAKSCh6KFL1_m3Fj:bjtkzr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L159)):*
> ```Go
> 
> // NeedsInitLocked returns true if (and only if) none if the engines are
> // initialized. In this case, server startup is blocked until either an
> ```

s/server startup/ServeAndWait/
___
*[pkg/server/init.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWDtD6w7DOxXHNMqG:-MFAWDtD6w7DOxXHNMqH:b-xuugpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init [...]

2020-08-20 11:54 UTC, knz reviewed
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)



<!-- Sent from Reviewable.io -->

2020-08-20 14:09 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/gossip/client.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg9NO666h6FQUvMDs:-MFB8Nxp8jnzC91DEYCN:bm15zgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/gossip/client.go#L278)):*
> Were you seeing nodes kill their gossip connections when they both didn't have a nodeID yet?

Yup. 

I'm not really sure how to respond to Raphael's question. In a cluster running 20.2 we won't have gossip started without NodeIDs. In mixed version settings where we're adding a 20.2 node to a 20.1 cluster, we could (we need to to maintain backwards compatibility). What exactly happens if we allow loopback connections for nodes without a node ID during that window of time? I don't think this code was designed to disallow that explicitly, I think it just happened because we didn't pay much mind to empty nodeIDs, but I could be wrong. I don't have enough understanding of gossip to think about what could break here with my patch.
___
*[pkg/roachpb/api.proto, line 2199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOZOj1S7FnO9fkZIu:-MFB1pwvArrLK8FEQ84X:b-7xi2vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2199)):*
[replying to this and the top level comment] The comment here is a bit dated, but yes, I was originally hoping we'd call something on every server start (and not just when not bootstrap), but realized soon after we're going to need a separate mechanism/RPC to disallow decomm'ed nodes from entering the cluster. _That_ RPC would be closely tied to the killfiles we'd distribute during decomm + persisting list of decomm'ed nodes in store local keys.

I see your point about preferring the version check to sit on this other `Connect` RPC, I think that makes sense. It's a similar gating mechanism we're using for decommissioned nodes.  I was originally thinking to place the connect RPC call right after the init server set up, because it's only that point after in the code today that we gain knowledge about our node ID, but that's not a good reason. That's also what had informed the placement of the version check in the Join RPC instead of Connect as well.

> Join, since that is only served on nodes that have KV running

Aside, I think I missed this detail. Mind point me to exactly where the code sits that sequences the serving of InternalServer RPCs after having "KV running". Related, where would this Connect/PreJoin RPC sit? I don't suppose it's *Node anymore, do we want a separate server for it entirely then?
___
*[pkg/server/node.go, line 1105 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFARSTh2ypQvNu28ZSc:-MFBAC5O20KzMTyuy8tF:bdf02ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/node.go#L1105)):*
> I thought Join would only be called when a new node joins for the first time 

That _is_ right. See other comment about needing a separate Connect RPC.


<!-- Sent from Reviewable.io -->

2020-08-20 15:18 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/gossip/client.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg9NO666h6FQUvMDs:-MFBRU5M5Z-RKOX4svUA:bno2py) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/gossip/client.go#L278)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

> Were you seeing nodes kill their gossip connections when they both didn't have a nodeID yet?

Yup. 

I'm not really sure how to respond to Raphael's question. In a cluster running 20.2 we won't have gossip started without NodeIDs. In mixed version settings where we're adding a 20.2 node to a 20.1 cluster, we could (we need to to maintain backwards compatibility). What exactly happens if we allow loopback connections for nodes without a node ID during that window of time? I don't think this code was designed to disallow that explicitly, I think it just happened because we didn't pay much mind to empty nodeIDs, but I could be wrong. I don't have enough understanding of gossip to think about what could break here with my patch.
</blockquote></details>

We talked 1:1 and the plan is for Irfan to check if he needs to make any changes here to get things working (and if so, understand why). Otherwise we'll leave this alone since NodeIDs will always be available in 21.1+
___
*[pkg/roachpb/api.proto, line 2199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOZOj1S7FnO9fkZIu:-MFBPJ0t4CTlNZFt4XzD:bf55byu) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2199)):*
We chatted about most of this 1:1. The version check is fine on the Join RPC (long-running migrations will include every "non-decommissioned" node in an upgrade, so once we have checked the version at join time, we'll receive all updates (or, if we're down, will block upgrades until decommissioned, in which case we can not connect to the cluster again in the future).

> Aside, I think I missed this detail. Mind point me to exactly where the code sits that sequences the serving of InternalServer RPCs after having "KV running". Related, where would this Connect/PreJoin RPC sit? I don't suppose it's *Node anymore, do we want a separate server for it entirely then?

I mean that the node only servers `Internal` (for the most part) when we hit this:

https://github.com/cockroachdb/cockroach/blob/30946b94e07b7108d02b3ae1e44fd4d35dda355f/pkg/server/server.go#L1480

In particular, while the `initServer` is blocking, the node does not serve `Join`.

The Connect/PreJoin RPC would be similar to the initServer, I think. It would be registered around

https://github.com/cockroachdb/cockroach/blob/30946b94e07b7108d02b3ae1e44fd4d35dda355f/pkg/server/server.go#L1157

(and we would already have passed the outbound Connect RPC at that point, this is necessary for correctness). It would sit on a small struct that only has the engines (which would be populated via some callback whenever we learn that a node is decommissioned, or we inject a db handle into it so that it can try to hit the liveness range, not sure, this is all tbd for me).


<!-- Sent from Reviewable.io -->

2020-08-24 08:44 UTC, irfansharif reviewed
Like mentioned below and discussed offline, we're going to need a separate RPC in addition to the one here that would check for the decomm'ed status of a node. That would happen after this Join RPC, because it's only after that point that the node is aware of its own Node ID. I've briefly outlined what that would look like, which was mostly already discussed in #48843. As for a possible "surprise along the way" that I don't have an answer for, is for the ever-growing list of decommissioned nodes that is being maintained on each store. Given that we're populating+broadcasting this list in best effort fashion (we are after all going to rely on the operator to guarantee that the target node is never coming back), perhaps it's also fine for us to age out the node ID list we maintain if it gets too large. Though I suspect that even maintaining a cap of 64 MB of decommissioned node IDs would only cause us problems long after we're gone (536,870,912 bits/64 = 8,388,608 decommissioned node IDs).

---

I've added a couple of tests (had to change some of our existing testing frameworks to make that easier), outlined follow up work, etc. I'm hoping to have this sitting in 20.2 just because it'll make 21.1 server start up code much simpler. PTAL.

> Reviewed 1 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MFUXqdf2umaIda4XVMO:b-6hhqyq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, @pbardea, and @tbg)

___
*[pkg/gossip/client.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEYg9NO666h6FQUvMDs:-MFCVHgfCXhjFV5Minqx:b-65pv9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/gossip/client.go#L278)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We talked 1:1 and the plan is for Irfan to check if he needs to make any changes here to get things working (and if so, understand why). Otherwise we'll leave this alone since NodeIDs will always be available in 21.1+
</blockquote></details>

Yea, I'm able to leave it alone. I wasn't before but now that I'm able to defer gossip start to after the join rpc, I don't need it anymore.
___
*[pkg/roachpb/api.proto, line 2199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOZOj1S7FnO9fkZIu:-MFURM6W3sG2joe0t5i-:bzg0who) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2199)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We chatted about most of this 1:1. The version check is fine on the Join RPC (long-running migrations will include every "non-decommissioned" node in an upgrade, so once we have checked the version at join time, we'll receive all updates (or, if we're down, will block upgrades until decommissioned, in which case we can not connect to the cluster again in the future).

> Aside, I think I missed this detail. Mind point me to exactly where the code sits that sequences the serving of InternalServer RPCs after having "KV running". Related, where would this Connect/PreJoin RPC sit? I don't suppose it's *Node anymore, do we want a separate server for it entirely then?

I mean that the node only servers `Internal` (for the most part) when we hit this:

https://github.com/cockroachdb/cockroach/blob/30946b94e07b7108d02b3ae1e44fd4d35dda355f/pkg/server/server.go#L1480

In particular, while the `initServer` is blocking, the node does not serve `Join`.

The Connect/PreJoin RPC would be similar to the initServer, I think. It would be registered around

https://github.com/cockroachdb/cockroach/blob/30946b94e07b7108d02b3ae1e44fd4d35dda355f/pkg/server/server.go#L1157

(and we would already have passed the outbound Connect RPC at that point, this is necessary for correctness). It would sit on a small struct that only has the engines (which would be populated via some callback whenever we learn that a node is decommissioned, or we inject a db handle into it so that it can try to hit the liveness range, not sure, this is all tbd for me).
</blockquote></details>

Done (Added the version check on the Join RPC.)
___
*[pkg/roachpb/api.proto, line 2210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOW7_EsoePwAIlySN:-MFUQr0E-UW2KOeR4Q2y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2210)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

+1 to exactly one
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 2214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAOUs_7fM6ByPPQ73z:-MFUQrMMDTISQb_-eKGa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/roachpb/api.proto#L2214)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 472 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MEcZMwE-x1fHQ_N0JJX:-MFCU6UTAnu8PMm84y68:b-k8ani0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7410cb1a2b867bcffbd06da555b68f76ad785ea1/pkg/server/init.go#L472)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think we would blindly retry. The node is trying to join the cluster, it will need to reach a node at some point, so it should go around its join list and try (with backoff) until something works. This is similar to how Gossip will try forever to connect. It won't give up.
</blockquote></details>

Added the blind retry. My real reason to suss out the connection error was to actually print out something less spammy during startup (also why I tried #51937).
___
*[pkg/server/init.go, line 95 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFATh0D-8A5NPz2F-bV:-MFC-1Ym4J_xDVKKpjzu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L95)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

why aren't the dial opts in the config?
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWAKSCh6KFL1_m3Fi:-MFC-7nK2kijanqMDmET:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L159)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/server startup/ServeAndWait/
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 167 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWDtD6w7DOxXHNMqG:-MFBVyIf08TlEvVgQDAJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L167)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/is ready to bootstrap/ is initialized, that is, has a NodeID and has permission to join the cluster.
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWNA4A089FNCyVy9B:-MFBW27K47mLSI5UfLMc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L170)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

add "outgoing"
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFAWPQK68XdA1R7co1Q:-MFUQsV_2RSbSOlyhYhC:b5uz7zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/22365db864b1402a7114c915806de414268cf0e3/pkg/server/init.go#L173)):*
<details><summary><i>Previously, tbg ( [...]

2020-08-25 11:37 UTC, tbg approved these changes
> Reviewed 69 of 69 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 2 of 2 files at r13, 4 of 4 files at r14, 24 of 24 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 2 of 2 files at r19.
> Dismissed @knz from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/cmd/roachtest/decommission.go, line 312 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZvK5vDs3FddWr_ra6:-MFZvK5vDs3FddWr_ra7:bxtnyyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/cmd/roachtest/decommission.go#L312)):*
> ```Go
> 	}
> 
> 	// This is a pretty gross hack to let the bootstrap info disseminate through
> ```

Can you explain what's actually happening here, or rather not happening quickly? 30s seems quite long but I see that you bumped this up from 10s so you likely had to. PS I'm also unsure what "bootstrap info" is.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 26 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_7p2_0LNINPOT_ETJ:-MF_7p2_0LNINPOT_ETK:b-d78iew) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L26)):*
> ```Go
> 	numNodes := 4
> 	r.Add(testSpec{
> 		Name:       "join-init/mixed",
> ```

Add a comment that this test is only relevant for 20.1/20.2 mixed clusters. We'll thus be able to remove (or selectively skip it) at some point.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 80 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8oIx6csoFhtq4JKd:-MF_8oIx6csoFhtq4JKe:bb6net1) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L80)):*
> ```Go
> 		checkNodeAndStoreIDs(node2, 2),
> 
> 		// If we upgrade too soon, we some times run into "last used with
> ```

Huh, really? `SHOW CLUSTER SETTING version` should only expose the version (on a given node) after it has been persisted to the disk. This is because of the gossip callback, which should run before exposing the version to the setting (and thus to SQL). Do you have an explanation for why this might be happening?
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 91 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8LIv4vuns6Lfw-3T:-MF_8LIw3YERBs6U8K00:bvqoduq) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L91)):*
> ```Go
> 		sleepStep(time.Minute),
> 
> 		// Roll node2 into the new version and check to see that it retains it's
> ```

it's --> its
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 163 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8Wy23CGTnQtRL_1d:-MF_8Wy23CGTnQtRL_1e:b-e03r1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L163)):*
> ```Go
> 				startArgs(fmt.Sprintf("-a=--join=%s", joinAddr)),
> 			)
> 			if err == nil {
> ```

when we use this, should check a particular error. You might as well adapt this code already to do so or we'll likely forget.
___
*[pkg/roachpb/api.proto, line 2220 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZvqcj7T-Mk_ilIO-q:-MFZvqcj7T-Mk_ilIO-r:b-kmr6wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/roachpb/api.proto#L2220)):*
> ```protobuf
>   int32 node_id = 2 [(gogoproto.customname) = "NodeID"];
>   int32 store_id = 3 [(gogoproto.customname) = "StoreID"];
>   roachpb.Version active_version = 4 [(gogoproto.customname) = "ActiveVersion"];
> ```

isn't the default name equal to your custom name here?
___
*[pkg/server/connectivity_test.go, line 120 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_71wUCIqBXXJ20sKg:-MF_71wUCIqBXXJ20sKh:bi0bmhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L120)):*
> ```Go
> 		// 0 <-> 1 <-- 2
> 		// 5 <-- 4 <-- 3 <-- 5
> 		{3, []int{1, 0, 1, 4, 5, 3}, []bool{false, false, false, true, true, true}},
> ```

So are these tests spending lots of time in the hard-coded 1s backoff? If so, that'd be further evidence to busy-loop through the first iteration when trying to join.
___
*[pkg/server/connectivity_test.go, line 121 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_6YiD2qLxzyNTzv9J:-MF_6YiD2qLxzyNTzv9K:b82actk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L121)):*
> ```Go
> 		// 5 <-- 4 <-- 3 <-- 5
> 		{3, []int{1, 0, 1, 4, 5, 3}, []bool{false, false, false, true, true, true}},
> 	}
> ```

Nice test :thumbsup: 
___
*[pkg/server/connectivity_test.go, line 124 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_53ZQ2DHXbKl9b3du:-MF_53ZQ2DHXbKl9b3dv:b-9p12hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L124)):*
> ```Go
> 
> 	getListener := func() net.Listener {
> 		listener, err := net.Listen("tcp", "127.0.0.1:0")
> ```

t.Helper() if you're feeling fancy
___
*[pkg/server/connectivity_test.go, line 179 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_6ORa16lPEVTMU8KA:-MF_6ORa16lPEVTMU8KB:bda16iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L179)):*
> ```Go
> 			go func() {
> 				// We need to start this in a separate thread because the
> 				// cluster is not initialized yet (it will be below), and is
> ```

this is
___
*[pkg/server/connectivity_test.go, line 313 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_7Pjq65DSgR3i6e2n:-MF_7Pjq65DSgR3i6e2o:b-174tnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5aa7aff49c6b13ee086532687c2665cf016e57d/pkg/server/connectivity_test.go#L313)):*
> ```Go
> 	knobs := base.TestingKnobs{
> 		Server: &server.TestingKnobs{
> 			BootstrapVersionOverride: oldVersion,
> ```

Something seems weird here, this is supposed to overwrite the bootstrap version, but you're using it for a node that is going to join the server. Can you rename the knob to reveal its true intent and add a comment on it?
___
*[pkg/server/connectivity_test.go, line 321 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_7iN0DjNEAUYXAEjW:-MF_7iN0DjNEAUYXAEjX:b-ykyjrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5aa7aff49c6b13ee086532687c2665cf016e57d/pkg/server/connectivity_test.go#L321)):*
> ```Go
> 	oldVersionServerArgs.JoinAddr = tc.Servers[0].ServingRPCAddr()
> 
> 	serv, err := tc.AddServer(oldVersionServerArgs)
> ```

:thumbsup: this came out nice.
___
*[pkg/server/init.go, line 135 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZupFhDemO1ZsVTk0L:-MFZupFiCLRNWHcLUcqh:b-f8beau) ([raw file](https://github.com/cockroachdb/cockroach/blob/7447361ab3290e4a8b673ba9880f1d830cb10dd7/pkg/server/init.go#L135)):*
> ```Go
> 	// TODO(tbg): remove this bool. The Node can find out another way whether
> 	// it just joined or restarted.
> 	joined bool
> ```

:thumbsup: nice cleanup.
___
*[pkg/server/init.go, line 51 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZwFxqDwc3fszSxLB2:-MFZwFxqDwc3fszSxLB3:b-ncaent) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/server/init.go#L51)):*
> ```Go
> 
> // ErrImproperBinaryVersion is returned when a CRDB node with a bi [...]

2020-08-28 06:57 UTC, irfansharif reviewed
TFTRs. I'm going to not check in my Test{Cluster,Server} changes as part of this PR given the blast radius of those changes. They've been a bit tricky to get quite right (that code hasn't changed all that much in years), so need added scrutiny. They're also well suited for code-stability, so I'll pick it back up then. I've stressed the tests I added here for hours, so am relatively confident in their correctness. The mixed version test still makes the cut.

Over the past few days all my debugging led to bugs I introduced in refactoring Test{Cluster,Server}, which is why I wanted to decouple it from this PR. The test I originally wrote up is sitting in https://github.com/irfansharif/cockroach/blob/3fd156b8e3883da082941a518613b2111d5b2dae/pkg/server/connectivity_test.go#L35-L39 for now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-:-MFnp_lb5e0dlKc7ZB3o:b-3xmt5j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cmd/roachtest/decommission.go, line 312 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZvK5vDs3FddWr_ra6:-MFlmSwx5HEl03FPud-i:b-y4uoob) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/cmd/roachtest/decommission.go#L312)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you explain what's actually happening here, or rather not happening quickly? 30s seems quite long but I see that you bumped this up from 10s so you likely had to. PS I'm also unsure what "bootstrap info" is.
</blockquote></details>

10s was all that I needed actually, but that was running locally. I was just being a bit overly generous here given I'm going to follow up by actually persisting the liveness record during start up. By bootstrap info I meant that node all nodes immediately learned the cluster ID (the join RPC is just a bit slower than gossip). I've clarified.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 26 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_7p2_0LNINPOT_ETJ:-MFlnRbXCH1i1TvA78jx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L26)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Add a comment that this test is only relevant for 20.1/20.2 mixed clusters. We'll thus be able to remove (or selectively skip it) at some point.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 80 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8oIx6csoFhtq4JKd:-MFlna5YCmbM2AuyOKpI:b-sid7wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L80)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Huh, really? `SHOW CLUSTER SETTING version` should only expose the version (on a given node) after it has been persisted to the disk. This is because of the gossip callback, which should run before exposing the version to the setting (and thus to SQL). Do you have an explanation for why this might be happening?
</blockquote></details>

Yea that's what I thought too, and was (am still) pretty confused by it. I haven't dug in too deeply to know what this is yet.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 91 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8LIv4vuns6Lfw-3T:-MFlo4wO-G7sydTKPArl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L91)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

it's --> its
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/mixed_version_join_init.go, line 163 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_8Wy23CGTnQtRL_1d:-MFlok3660PwgkzYk9VE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/478d526429ff0739469506e7d7e054f6c9b04b29/pkg/cmd/roachtest/mixed_version_join_init.go#L163)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

when we use this, should check a particular error. You might as well adapt this code already to do so or we'll likely forget.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 2220 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZvqcj7T-Mk_ilIO-q:-MFlozZI2Ys-6Bl8JNYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/roachpb/api.proto#L2220)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

isn't the default name equal to your custom name here?
</blockquote></details>

Done.
___
*[pkg/server/connectivity_test.go, line 120 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_71wUCIqBXXJ20sKg:-MFnpPCR74cde9J25nkW:b-vhxiur) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L120)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

So are these tests spending lots of time in the hard-coded 1s backoff? If so, that'd be further evidence to busy-loop through the first iteration when trying to join.
</blockquote></details>

Will follow up.
___
*[pkg/server/connectivity_test.go, line 121 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_6YiD2qLxzyNTzv9J:-MFlpK_DCf-x7iI0tawK:b2yjtjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L121)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Nice test :thumbsup: 
</blockquote></details>

thanks, ha, was a struggle.
___
*[pkg/server/connectivity_test.go, line 124 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_53ZQ2DHXbKl9b3du:-MFlpIw975qcq5iE8UEi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L124)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

t.Helper() if you're feeling fancy
</blockquote></details>

Done.
___
*[pkg/server/connectivity_test.go, line 179 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_6ORa16lPEVTMU8KA:-MFlpQYr0HqGy-fis-4m:bdhjun6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b773f5cc04ef82fc21641c25d8ca7b454fe0d5b/pkg/server/connectivity_test.go#L179)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

this is
</blockquote></details>

This was removed.
___
*[pkg/server/connectivity_test.go, line 313 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MF_7Pjq65DSgR3i6e2n:-MFlrQAH2i8a9RcZVTcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5aa7aff49c6b13ee086532687c2665cf016e57d/pkg/server/connectivity_test.go#L313)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Something seems weird here, this is supposed to overwrite the bootstrap version, but you're using it for a node that is going to join the server. Can you rename the knob to reveal its true intent and add a comment on it?
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 51 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/52526#-MFZwFxqDwc3fszSxLB2:-MFltJKAAuDBG1VqKZrF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/afed8d91fa08d8bfdbeda7685e39487bd03b3d7d/pkg/server/init.go#L51)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

or higher
</blockquote></details>

Done.
___
*[pkg/server/init.go, line 52 [...]

2020-08-28 07:21 UTC, irfansharif commented
bors r+

2020-08-28 08:24 UTC, irfansharif commented
bors r+

2020-08-28 09:02 UTC, irfansharif commented
bors r+

2020-08-28 09:37 UTC, merged