wip: sql: support alter type owner
cockroachdb/cockroach pull request #52656
Opened 2020-08-11 23:20 UTC by RichardJCai

Release note (sql change): Support ALTER TYPE <type> OWNER TO <owner>
The command changes the owner of a type.

To use the conditions, the following conditions must be met:
The user executing the command must be the explicit owner of the type.
(Not just have membership of the role who owns the type.)
The user executing the command must be a member of the new owner role.
The new owner role must have CREATE on the schema the type belongs to.

Only the latest commit is relevant, this depends on #51622
Fixes #48700

2020-08-11 23:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52656)
<!-- Reviewable:end -->

2020-08-18 21:29 UTC, otan commented
that's a shiny bot

2020-08-18 21:35 UTC, rohany commented
theres a whole company around it

2020-08-21 00:21 UTC, rohany requested changes

2020-08-21 00:21 UTC, rohany commented on pkg/sql/sem/tree/alter_type.go
> +// AlterTypeOwner represents an ALTER TYPE SET SCHEMA command.
comment isnt' right

2020-08-21 00:21 UTC, rohany commented on pkg/sql/alter_type.go
> +
don't add the .DS_STORE file below

2020-08-21 00:21 UTC, rohany commented on pkg/sql/parser/sql.y
> +    $$.val = &tree.AlterType{
is the help message updated?

2020-08-21 00:38 UTC, RichardJCai commented on pkg/sql/parser/sql.y
> +    $$.val = &tree.AlterType{
Yeah it was there before this.

2020-08-21 00:38 UTC, RichardJCai commented on pkg/sql/alter_type.go
> +
Oops

2020-08-21 00:38 UTC, RichardJCai commented on pkg/sql/sem/tree/alter_type.go
> +// AlterTypeOwner represents an ALTER TYPE SET SCHEMA command.
Done

2020-08-21 01:09 UTC, rohany approved these changes

2020-08-23 19:47 UTC, RichardJCai commented
@rohany can you bors this?

2020-08-23 19:54 UTC, rohany commented
bors r+

2020-08-23 21:32 UTC, merged