sql: implement idle_in_transaction_session_timeout
cockroachdb/cockroach pull request #52938
Opened 2020-08-17 20:27 UTC by RichardJCai

Release note (sql change): Implement IdleInTransactionSessionTimeout
variable to allow terminating sessions that are idle in a transaction
past the provides threshold.

Set the variable by using SET idle_in_transaction_session_timeout = 'time'.

Sessions that are idle in OPEN, ABORTED and DONE(COMMITWAIT) transaction states
will be terminated if the user idles longer than the threshold time.

Fixes #5924

2020-08-17 20:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/52938)
<!-- Reviewable:end -->

2020-08-20 18:39 UTC, solongordon requested changes
I just tested this out manually and something seems off. I set the timeout variable and then ran `BEGIN;` followed immediately by `SELECT 1`. Then no matter how long I wait it doesn't seem like the session is canceled. Could you take a look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-:-MFC99mu9tN9A-e5Qj01:b9ba410)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)



<!-- Sent from Reviewable.io -->

2020-08-20 19:20 UTC, solongordon reviewed
I take it back, I lost my session setting without realizing it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-:-MFCJ2jL6w7crpu6fMvn:bmt7z9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)



<!-- Sent from Reviewable.io -->

2020-08-20 19:39 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> My only real complaint is the same as last time, which is that the tests take ~30 seconds to run. Any chance you could slim that down a bit without introducing flakiness?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-:-MFCNM4rAxK6-gO1G-CQ:b-pai2ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @RichardJCai)

___
*[pkg/sql/conn_executor_exec.go, line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-MFCJe_14URwzzujed99:-MFCJe_29KeLDNORmX7p:b-smv9fy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bb0dc703673bb9406d435988294f8c2d4a60bd5/pkg/sql/conn_executor_exec.go#L153)):*
> ```Go
> 		case stateOpen:
> 			// Only start timeout if the statement is executed in an
> 			// implicit transaction.
> ```

s/implicit/explicit/
___
*[pkg/sql/run_control_test.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-MFCKlhz06mjW1T-Ui47:-MFCKlhz06mjW1T-Ui48:b-kzh9fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bb0dc703673bb9406d435988294f8c2d4a60bd5/pkg/sql/run_control_test.go#L514)):*
> ```Go
> 	time.Sleep(3 * time.Second)
> 	// The connection should still be alive.
> 	err = conn.PingContext(ctx)
> ```

Isn't this the same as what you test at the beginning of `TestIdleInTransactionSessionTimeout`?


<!-- Sent from Reviewable.io -->

2020-08-20 19:48 UTC, RichardJCai commented
> <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/41b3ec3419116e3b3f84507ad965646ce4ce1f0c/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67"> My only real complaint is the same as last time, which is that the tests take ~30 seconds to run. Any chance you could slim that down a bit without introducing flakiness?
> 
> >

I'm going to try to decrease the time, can increase it if it introduces flakiness on CI.

2020-08-20 19:49 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52938)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @solongordon)

___
*[pkg/sql/run_control_test.go, line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52938#-MFCKlhz06mjW1T-Ui47:-MFCPpgNA2LCZXSNz9GP:b-zej4yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bb0dc703673bb9406d435988294f8c2d4a60bd5/pkg/sql/run_control_test.go#L514)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Isn't this the same as what you test at the beginning of `TestIdleInTransactionSessionTimeout`?
</blockquote></details>

Yeah I think this is unnecessary


<!-- Sent from Reviewable.io -->

2020-08-20 22:21 UTC, RichardJCai commented
bors r+

2020-08-20 23:49 UTC, merged