sql: create and fill `crdb_internal.node_transaction_statistics` table
cockroachdb/cockroach pull request #53759
Opened 2020-09-01 16:17 UTC by arulajmani

Previously there was no way to query the transaction level metrics
collected by individual nodes. This patch adds this capability by
exposing a new internal table called
`crdb_internal.node_transaction_statistics` which is analagous to
`crdb_internal.node_statement_statistics` albeit for transactions.

Closes #53504

Release justification: low risk update to new functionality
Release note (sql change): A new crdb_internal table called
`node_transaction_statistics` is exposed as part of this change,
which allows users to query transaction metrics collected on a
particular node.

2020-09-01 16:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/53759)
<!-- Reviewable:end -->

2020-09-03 20:52 UTC, solongordon requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53759)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/crdb_internal.go, line 864 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVRgLCnEIc60gs3a9:-MGKVRgM-021leL2nWC3:b-7m8w3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L864)):*
> ```Go
> 
> var crdbInternalTransactionStatisticsTable = virtualSchemaTable{
> 	comment: `finer grain transaction statistics (in-memory, not durable; local node only). ` +
> ```

nit: "finer-grained"
___
*[pkg/sql/crdb_internal.go, line 867 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVHwsB2qxBu6UP3kq:-MGKVHwsB2qxBu6UP3kr:b-39eo0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L867)):*
> ```Go
> 		`This table is wiped periodically (by default, at least every two hours)`,
> 	schema: `
> CREATE  TABLE crdb_internal.node_transaction_statistics (
> ```

nit: two spaces after `CREATE`
___
*[pkg/sql/crdb_internal.go, line 868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVe-vCzMDwWvJF-Rh:-MGKVe-vCzMDwWvJF-Ri:bag0sgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L868)):*
> ```Go
> 	schema: `
> CREATE  TABLE crdb_internal.node_transaction_statistics (
>   node_id 					INT NOT NULL,
> ```

I wonder if we should also include the transaction hash here. It would be good to have some unique identifier per row. Otherwise it would be annoying to, say, write a query which returns all the statements for a particular transaction.

If so we should probably call it something other than `transaction_id` since that's already something different. Maybe `transaction_key` or just `key`?
___
*[pkg/sql/crdb_internal.go, line 878 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVbMr7j_Ub-FtF6W1:-MGKVbMr7j_Ub-FtF6W2:bw31p5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L878)):*
> ```Go
>   retry_lat_var 		FLOAT NOT NULL,
> 	commit_lat_avg 		FLOAT NOT NULL,
>   commit_lat_var 		FLOAT NOT NULL,
> ```

nit: doesn't quite line up
___
*[pkg/sql/crdb_internal.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKWfD3-Kt0khv0RF1T:-MGKWfD3-Kt0khv0RF1U:b-cg9hln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L884)):*
> ```Go
> `,
> 	populate: func(ctx context.Context, p *planner, _ *dbdesc.Immutable, addRow func(...tree.Datum) error) error {
> 		if err := p.RequireAdminRole(ctx, "access application statistics"); err != nil {
> ```

We should actually make this require the new VIEWACTIVITY role privilege, not admin. Would you mind making that change for the statement version of this table too while you're here?
___
*[pkg/sql/crdb_internal.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKhqBUDksmZDY-lTx-:-MGKhqBUDksmZDY-lTx0:b-7ad172) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L921)):*
> ```Go
> 			// Now retrieve the per-txn stats proper.
> 			for _, txnKey := range txnKeys {
> 				// The key should exist, so it's okay to pass nil for the statementIDs
> ```

What if the statistics happen to get cleared while this function is running? I think you should make sure to handle the case where the key doesn't exist.


<!-- Sent from Reviewable.io -->

2020-09-04 01:26 UTC, arulajmani reviewed
Addressed review comments, should be RFAL. Can't pinpoint why the `pg_catalog` test is failing because of this change. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-:-MGLi7sN5ohiNqpJM7GQ:b-z63hds)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/crdb_internal.go, line 868 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVe-vCzMDwWvJF-Rh:-MGLc-9v2UTXvVK0MFC4:bxf2pr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L868)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I wonder if we should also include the transaction hash here. It would be good to have some unique identifier per row. Otherwise it would be annoying to, say, write a query which returns all the statements for a particular transaction.

If so we should probably call it something other than `transaction_id` since that's already something different. Maybe `transaction_key` or just `key`?
</blockquote></details>

Added a `key` field. Didn't realize we had a `key` field for the statement version of this table. 
___
*[pkg/sql/crdb_internal.go, line 878 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKVbMr7j_Ub-FtF6W1:-MGLa6-g0Gnqm_jO-c68:b-k14cfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L878)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

nit: doesn't quite line up
</blockquote></details>

Tabs and spaces haha, Fixed now! 
___
*[pkg/sql/crdb_internal.go, line 884 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKWfD3-Kt0khv0RF1T:-MGLb6L64VB-7Y8wXZSY:bqmjwcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L884)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

We should actually make this require the new VIEWACTIVITY role privilege, not admin. Would you mind making that change for the statement version of this table too while you're here?
</blockquote></details>

Added!
___
*[pkg/sql/crdb_internal.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGKhqBUDksmZDY-lTx-:-MGLcZ7M81vdikoTbfbS:b-gj3s3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee2287c02c26e417680d73efea8ef0659d831651/pkg/sql/crdb_internal.go#L921)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

What if the statistics happen to get cleared while this function is running? I think you should make sure to handle the case where the key doesn't exist.
</blockquote></details>

Good catch! Handled. 


<!-- Sent from Reviewable.io -->

2020-09-04 20:13 UTC, arulajmani commented
Looks like the pg_catalog stuff changed because there is a new comment on the table I'm adding.

2020-09-04 20:20 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Is it weird that all those OIDs went *down* by 1? It would seem more expected for them to go up since you added something new but I don't really know how these things are generated.

> Reviewed 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-:-MGPlV-f-8yPrTmkzUal:b-a65rdc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)



<!-- Sent from Reviewable.io -->

2020-09-04 20:22 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53759)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGPm0aN0txj1USQ30_y:-MGPm0aN0txj1USQ30_z:b-olcwr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfd307f6017a2155669550afbc206fddb4e5cd1/pkg/sql/crdb_internal.go#L121)):*
> ```Go
> 		catconstants.CrdbInternalTxnStatsTableID:             crdbInternalTxnStatsTable,
> 		catconstants.CrdbInternalZonesTableID:                crdbInternalZonesTable,
> 		catconstants.CrdbInternalTransactionStatsTableID:     crdbInternalTransactionStatisticsTable,
> ```

nit: For future maintainability, it's better to maintain this dict ordered alphabetically.
___
*[pkg/sql/catalog/catconstants/constants.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53759#-MGPm8DD2SlMbWJNlkdy:-MGPm8DD2SlMbWJNlkdz:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfd307f6017a2155669550afbc206fddb4e5cd1/pkg/sql/catalog/catconstants/constants.go#L83)):*
> ```Go
> 	CrdbInternalTxnStatsTableID
> 	CrdbInternalZonesTableID
> 	CrdbInternalTransactionStatsTableID
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-09-06 23:50 UTC, arulajmani commented
addressed the nits and updated the zip tests. TFTRs! 

bors r=solongordon

2020-09-07 01:01 UTC, merged