sql: disallow role/user drops if they own a schema or a type
cockroachdb/cockroach pull request #54047
Opened 2020-09-08 18:03 UTC by arulajmani

Now that we have user defined schemas and types, they need to play well
with the concept of ownership as well. If a user/role owns a schema or a
type, the `DROP ROLE` command will fail with the appropriate message.

fixes #54015

Release justification: bug fix for new functionality.
Release note (sql change): If a user/role has ownership over a type or
a schema, it is no longer possible to drop them.

2020-09-08 18:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54047)
<!-- Reviewable:end -->

2020-09-10 14:39 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54047)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @solongordon)

___
*[pkg/sql/drop_role.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsOOcz9BhGblgTCYRj:-MGsOOcz9BhGblgTCYRk:b-nm72xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/drop_role.go#L162)):*
> ```Go
> 		}
> 		if _, ok := userNames[table.GetPrivileges().Owner]; ok {
> 			tn, err := getTableNameFromTableDescriptor(lCtx, table, "")
> ```

I can see why it makes sense to use fully qualified table names here. Should we do the same for schemas and types?
___
*[pkg/sql/drop_role.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsOR9QCxsu4Zcc9GeB:-MGsOR9QCxsu4Zcc9GeC:b-ed8e4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/drop_role.go#L188)):*
> ```Go
> 		// TODO(arul): What's the deal with the visibility check above for Tables?
> 		//  is that required for schema descs/types? GetState() seems to be only
> 		//  for table descriptors, so not sure here.
> ```

I think it's so we don't consider descriptors in the Dropped or Offline states. I would say we should apply the same check for schemas and types. It looks to me like they do both have `GetState()` methods.
___
*[pkg/sql/logictest/testdata/logic_test/owner, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsPxON4OVfxA7cY-X5:-MGsPxON4OVfxA7cY-X6:b8p7buu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/logictest/testdata/logic_test/owner#L228)):*
> ```
> user testuser
> 
> statement error pq: role testuser cannot be dropped because some objects depend on it.*\n.*owner of database d.*\n.*owner of table test.public.t.*\n.*owner of table d.public.t.*\n.*owner of schema s.*\n.*owner of type _?typ.*\n.*owner of type _?typ
> ```

Is something weird going on with stringifying user-defined type names? And why does the type show up twice?


<!-- Sent from Reviewable.io -->

2020-09-11 00:59 UTC, arulajmani reviewed
RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-:-MGuexgw1yoeNecVi3sE:by76qkj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/drop_role.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsOOcz9BhGblgTCYRj:-MGud0nMBrsGPiwCb5RE:bc1wab3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/drop_role.go#L162)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I can see why it makes sense to use fully qualified table names here. Should we do the same for schemas and types?
</blockquote></details>

Added the fully qualified name for types. Schema seems slightly complicated -- I think the right thing to do is add a `SchemaName` that aliases `ObjectNamePrefix` similar to the way `TableName` and `TypeName` alias `objName`, but I'm a bit hesitant to make this change just for an error message and without considering all the places we'd possibly want to format a "qualified schema name". 
___
*[pkg/sql/drop_role.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsOR9QCxsu4Zcc9GeB:-MGuKnyB5OousoZ2QlDY:b-jfqn1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/drop_role.go#L188)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I think it's so we don't consider descriptors in the Dropped or Offline states. I would say we should apply the same check for schemas and types. It looks to me like they do both have `GetState()` methods.
</blockquote></details>

Makes sense, I was sort of confused becuse the `GetState` method was just on the `TableDescriptor` interface and not on the `SchemaDescriptor` and `TypeDescriptor` interfaces, but turns out it's on the all the `descpb` descriptors and was therefore just hidden. Done. 
___
*[pkg/sql/logictest/testdata/logic_test/owner, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsPxON4OVfxA7cY-X5:-MGuBba88_PCJSrqKcNT:bbdntua) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/logictest/testdata/logic_test/owner#L228)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Is something weird going on with stringifying user-defined type names? And why does the type show up twice?
</blockquote></details>

There's two type descs created underneath the hood when we create a type. One is for the type and another is for an array of that type (it has an underscore at the beginning). The reason for having this `_?` business is that the order of descs read is different for different logic test configs, so can't deterministically hard code if the array type will be processed before the normal type.   


<!-- Sent from Reviewable.io -->

2020-09-15 19:50 UTC, arulajmani commented
Fixed some merge conflicts that had popped up. Should be good for a look @solongordon

2020-09-16 20:33 UTC, solongordon approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54047)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/drop_role.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsOOcz9BhGblgTCYRj:-MHNb4qMC4pAVBWK8pvO:bjqr9b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/drop_role.go#L162)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Added the fully qualified name for types. Schema seems slightly complicated -- I think the right thing to do is add a `SchemaName` that aliases `ObjectNamePrefix` similar to the way `TableName` and `TypeName` alias `objName`, but I'm a bit hesitant to make this change just for an error message and without considering all the places we'd possibly want to format a "qualified schema name". 
</blockquote></details>

OK, the inconsistency is a little weird but in the interest of minimizing code changes this seems reasonable. Would you mind adding a TODO to call out the difference here?
___
*[pkg/sql/logictest/testdata/logic_test/owner, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54047#-MGsPxON4OVfxA7cY-X5:-MHNSlvb2QY8hvQST-Ma:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4746fdbfe077704b67578802c2922da860fefcfd/pkg/sql/logictest/testdata/logic_test/owner#L228)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

There's two type descs created underneath the hood when we create a type. One is for the type and another is for an array of that type (it has an underscore at the beginning). The reason for having this `_?` business is that the order of descs read is different for different logic test configs, so can't deterministically hard code if the array type will be processed before the normal type.   
</blockquote></details>

Makes sense!


<!-- Sent from Reviewable.io -->

2020-09-17 16:02 UTC, arulajmani commented
TFTR! Added the todo, merging. 

bors r=solongordon

2020-09-17 16:55 UTC, merged