sql: ensure auto-retrying transactions respect the statement_timeout
cockroachdb/cockroach pull request #54370
Opened 2020-09-14 21:52 UTC by arulajmani

Backport:
  * 1/1 commits from "sql: ensure auto-retrying transactions respect the statement_timeout" (#53968)
  * 1/1 commits from "sql: increase statement_timeout in sequences logictest" (#54368)

Please see individual PRs for details.

/cc @cockroachdb/release

2020-09-14 21:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54370)
<!-- Reviewable:end -->

2020-09-15 16:06 UTC, rafiss requested changes

2020-09-15 16:06 UTC, rafiss commented on pkg/sql/run_control_test.go
> +	require.NoError(t, err)
looks like the `require` import was added in 39e7448ccddf92428716fbe56d257edaee02c874

i think you can just add the import here

2020-09-15 18:24 UTC, arulajmani commented
I might need to get https://github.com/cockroachdb/cockroach/issues/54372 in as well to deflake CI, so I'm putting the DNM label on this for now.

2020-09-16 17:19 UTC, arulajmani commented
This should be ready now that #54415  is in.

2020-09-16 20:40 UTC, solongordon approved these changes

2020-09-17 15:24 UTC, merged