sql: add memory accounting for sqlStats
cockroachdb/cockroach pull request #54521
Opened 2020-09-17 18:27 UTC by arulajmani

sqlStats track statement/transaction level statistics which can grow
unboundedly larged based on the users' query patterns. To mitigate
this, we currenlty clear the sqlStats and reportedStats at regular
intervals. This doesn't guarentee that we won't run into trouble with
excess mem usage though. This patch adds memory accounting to these
datastructures to deterministically ensure that we keep the amount of
memory usage in check. If stats collection ends up using more memory
than allowed, the sqlStats datastructure is reset pre-emptively.

Closes #53749

Release note (general change): users may find statistics are cleared
more often than dictated by cluster settings if stats collection is
taking up too much memory.

2020-09-17 18:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54521)
<!-- Reviewable:end -->

2020-09-30 15:10 UTC, otan commented on pkg/sql/app_stats.go
> +		log.Infof(ctx, "resetting sql stats because memory limit %d reached\n", size)
nit: no \n for Logf

2020-09-30 15:10 UTC, otan commented on pkg/sql/conn_executor.go
> +		// need another monitor that is a child of pool?
i think this is fine. is there a reason we should not?

2020-09-30 15:10 UTC, otan commented
(is this a release blocker?)

2020-11-12 17:14 UTC, solongordon requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54521)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @jordanlewis)

___
*[pkg/sql/app_stats.go, line 364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54521#-MLxR_O-3AUsh81IPVGg:-MLxR_O-3AUsh81IPVGh:bqyhve3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db4882366f730b8dc1de0784f91d4516f836fb3/pkg/sql/app_stats.go#L364)):*
> ```Go
> 		size += int(unsafe.Sizeof(k))
> 		size += int(unsafe.Sizeof(*v))
> 	}
> ```

I'm nervous about the overhead (and resulting contention) from calculating these sizes every time `appStats` is updated. Can we look into whether a more targeted approach is possible, like only updating the memory account when a new statement or transaction fingerprint is added? I'm not sure how difficult the plumbing would be for that but let's give it a shot.


<!-- Sent from Reviewable.io -->

2021-05-21 19:28 UTC, rafiss commented
replaced by https://github.com/cockroachdb/cockroach/pull/65172

2021-05-21 19:28 UTC, closed without merging