sql: randomize max mutation batch size in logic tests
cockroachdb/cockroach pull request #54591
Opened 2020-09-18 22:12 UTC by yuzefovich

Previously, all mutation operations (delete, insert, update, upsert)
used the same constant value 10000 which was stored separately. Such
a large number makes it difficult to test multi-batch logic in our logic
tests because they tend to not modify many rows, so usually we would
have a single KV batch. This testing gap turned out to be unfortunate
because it allowed a pretty severe bug to slip into a point release.

In order to close this gap and increase the testing coverage of the
mutations, this commit removes separate constants and introduces
a shared `MaxBatchSize` function (which uses an atomic) that all
mutations now use to determine when to start a new KV batch. The value
can be modified by a setter function as well as via a new private
cluster setting `sql.testing.mutations.max_batch_size`. The latter way
is now utilized by the logic tests.

Informs: #54456.

Release note: None

2020-09-18 22:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54591)
<!-- Reviewable:end -->

2020-09-18 22:12 UTC, yuzefovich commented
I need to check how much of an impact this has on the runtime of the whole logic test suite.

2020-09-19 01:54 UTC, yuzefovich commented
Ok, I've tried running `make testbaselogic` on gceworker, and with default 10k it takes about 500s and with 1 it took a little over 600s, so the slowdown is pretty much negligible.

2020-09-21 09:33 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHk-jJlDuSYjr23FyXx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-09-21 09:34 UTC, asubiotto reviewed
Did you test that this would've caught the `UPSERT` issue?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHk-m7b2laRNXiOEDDO:b-8zxczz)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-09-21 12:04 UTC, jordanlewis approved these changes
Thank you for taking a look at this so quickly!

2020-09-21 14:56 UTC, yuzefovich reviewed
Yeah, I did test it and the bug would have been caught.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHl9Z67C-l5Vye_7jXV:b-v5umjo)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/delete.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-MHl91jj7nTObOvjGotM:-MHl91jk4pT80J50xgs6:bsms3a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9850d68a76a158440d9dfbeddd673533aca20fe4/pkg/sql/delete.go#L122)):*
> ```Go
> 
> 		// Are we done yet with the current batch?
> 		if d.run.td.currentBatchSize >= mutations.MaxBatchSize() {
> ```

Do you guys think it's worth storing the result of `mutations.MaxBatchSize()` during init so that we avoid contention on this atomic? I remember I did benchmark doing similar change for `coldata.BatchSize` and didn't see a performance impact, but I'm wondering whether for mutations it might have a noticeable perf hit with a lot of concurrency. @asubiotto @jordanlewis 


<!-- Sent from Reviewable.io -->

2020-09-21 15:09 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/delete.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-MHl91jj7nTObOvjGotM:-MHlCSBb3YjbdEfZLwMS:b-czitre) ([raw file](https://github.com/cockroachdb/cockroach/blob/9850d68a76a158440d9dfbeddd673533aca20fe4/pkg/sql/delete.go#L122)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do you guys think it's worth storing the result of `mutations.MaxBatchSize()` during init so that we avoid contention on this atomic? I remember I did benchmark doing similar change for `coldata.BatchSize` and didn't see a performance impact, but I'm wondering whether for mutations it might have a noticeable perf hit with a lot of concurrency. @asubiotto @jordanlewis 
</blockquote></details>

I've updated the code, I think it should be safer (performance-wise).


<!-- Sent from Reviewable.io -->

2020-09-22 08:34 UTC, asubiotto approved these changes
Good idea, although I'm not sure it makes much of a difference (IO will probably be dominating factor here) but it's good hygiene. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHowZMJ8cdmqFwwSbcu:b-us3c3w)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-09-22 22:57 UTC, yuzefovich commented
This PR needs to be updated to remove some non-determinism in logic tests (I'm thinking about disabling the randomization for `execbuilder` tests), and I've been a bit busy with a customer issue. In the mean time I cherry-picked the commit on 20.1 branch and ran all logic tests with batch sizes of 1 and 2 and didn't encounter any problems, so I'm pretty confident that we've fixed the bugs with mutations at the SQL level.

2020-09-23 02:06 UTC, yuzefovich reviewed
I disabled the randomization in `execbuilder` tests and moved one file to that folder. I think that should cover all possibly non-deterministic cases, so I'd appreciate another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHshIaz8VicxoLDD3LF:b-umz4ch)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-09-23 08:41 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-MHu6YjC9bhn4Y5C_g9N:-MHu6YjC9bhn4Y5C_g9O:b-c6vdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/214efcac355aed52adf4fce132636aad6a00063b/pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats#L1)):*
> ```
> # Note that this filed was moved from the regular logic tests as a part of
> ```

nit: `s/filed/file`
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-MHu6kTSAbJvDmSXh_ly:-MHu6kTSAbJvDmSXh_lz:b6qxous) ([raw file](https://github.com/cockroachdb/cockroach/blob/214efcac355aed52adf4fce132636aad6a00063b/pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats#L13)):*
> ```
> # Disable automatic stats
> statement ok
> SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false
> ```

The problem with moving this file is that it doesn't run with `3node-tenant` anymore and I think this is very unfortunate and something we want to avoid if possible. Do we have any other stats tests in `logictest/testdata`? How come the `RESET CLUSTER SETTING` statement didn't work?


<!-- Sent from Reviewable.io -->

2020-09-23 14:45 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-MHu6kTSAbJvDmSXh_ly:-MHvPKb646FpUW6mKHxJ:by03ohe) ([raw file](https://github.com/cockroachdb/cockroach/blob/214efcac355aed52adf4fce132636aad6a00063b/pkg/sql/opt/exec/execbuilder/testdata/distsql_automatic_stats#L13)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The problem with moving this file is that it doesn't run with `3node-tenant` anymore and I think this is very unfortunate and something we want to avoid if possible. Do we have any other stats tests in `logictest/testdata`? How come the `RESET CLUSTER SETTING` statement didn't work?
</blockquote></details>

This was the only file in `logictest/testdata` the output of which seemed to change based on the mutations max batch size, so I'd guess there are no others.

The problem with `RESET CLUSTER SETTING` is that
- it changes the whole cluster setting (I believe we are executing multiple logic test files on the same configuration at once against the same test cluster, so by resetting it in this file, we will disable the randomization for all files that run later against that cluster)
- and we know that cluster setting change might propagate slowly (that's the issue with the vectorized batch size propagation that I handed over to you to look at).

Combining these two observations, I think moving a single file has the least negative impact.


<!-- Sent from Reviewable.io -->

2020-09-23 15:51 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but I'm still concerned about the loss of testing coverage. I agree that this is probably the best thing to do.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54591#-:-MHveKRX-SxBUXcnuc1N:b-ynsp5a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-09-23 16:58 UTC, yuzefovich commented
TFTRs!

bors r+

2020-09-23 18:36 UTC, merged