rowexec: optimize partially ordered distinct
cockroachdb/cockroach pull request #54724
Opened 2020-09-24 03:45 UTC by yuzefovich

This commit optimizes the partially ordered distinct by fixing a bug in
the implementation of the optimization's intention. When we have
partially ordered input stream, it is sufficient to only hash
non-ordered columns in order to distinguish between the rows. That has
also been the intention, but we actually hashed all distinct columns.
This is now fixed which gives a minor speedup.

Release note: None

2020-09-24 03:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54724)
<!-- Reviewable:end -->

2020-09-24 04:03 UTC, yuzefovich commented
```
name                                    old time/op    new time/op    delta
PartiallyOrderedDistinct/rows=16-24       8.80µs ± 2%    8.05µs ± 1%   -8.46%  (p=0.000 n=10+9)
PartiallyOrderedDistinct/rows=256-24       101µs ± 1%      90µs ± 1%  -10.62%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=4096-24     1.57ms ± 1%    1.38ms ± 0%  -11.72%  (p=0.000 n=9+9)
PartiallyOrderedDistinct/rows=65536-24    24.5ms ± 1%    21.8ms ± 1%  -11.28%  (p=0.000 n=9+9)

name                                    old speed      new speed      delta
PartiallyOrderedDistinct/rows=16-24     29.1MB/s ± 2%  31.8MB/s ± 1%   +9.23%  (p=0.000 n=10+9)
PartiallyOrderedDistinct/rows=256-24    40.7MB/s ± 1%  45.5MB/s ± 1%  +11.88%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=4096-24   41.9MB/s ± 1%  47.4MB/s ± 0%  +13.28%  (p=0.000 n=9+9)
PartiallyOrderedDistinct/rows=65536-24  42.7MB/s ± 1%  48.2MB/s ± 1%  +12.71%  (p=0.000 n=9+9)

name                                    old alloc/op   new alloc/op   delta
PartiallyOrderedDistinct/rows=16-24       6.70kB ± 0%    6.70kB ± 0%   +0.12%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=256-24      52.8kB ± 0%    52.8kB ± 0%   +0.02%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=4096-24      790kB ± 0%     790kB ± 0%   +0.00%  (p=0.000 n=9+10)
PartiallyOrderedDistinct/rows=65536-24    12.6MB ± 0%    12.6MB ± 0%     ~     (p=0.116 n=10+9)

name                                    old allocs/op  new allocs/op  delta
PartiallyOrderedDistinct/rows=16-24         42.0 ± 0%      43.0 ± 0%   +2.38%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=256-24         522 ± 0%       523 ± 0%   +0.19%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=4096-24      8.20k ± 0%     8.20k ± 0%   +0.01%  (p=0.000 n=10+10)
PartiallyOrderedDistinct/rows=65536-24      131k ± 0%      131k ± 0%   +0.00%  (p=0.000 n=10+10)
```

2020-10-01 15:08 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/distinct.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-MIZgo_xCLqithsXOLdf:-MIZgo_xCLqithsXOLdg:b-9ak6a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7e16bf73dcaa4627203a25958e8ca971bf72fe/pkg/sql/rowexec/distinct.go#L88)):*
> ```Go
> 
> 	for _, col := range spec.OrderedColumns {
> 		orderedCols.Add(int(col))
> ```

Why not keep these fast int sets and do something like `nonOrdered = distinctCols.DifferenceWith(orderedCols)`?


<!-- Sent from Reviewable.io -->

2020-10-01 15:20 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/distinct.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-MIZgo_xCLqithsXOLdf:-MIZiLY16mM6cmLsp4iY:bhe9rzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7e16bf73dcaa4627203a25958e8ca971bf72fe/pkg/sql/rowexec/distinct.go#L88)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not keep these fast int sets and do something like `nonOrdered = distinctCols.DifferenceWith(orderedCols)`?
</blockquote></details>

I don't think it's important in the grand scheme of things (performance-wise), in fact, it might be worse to keep on using `FastIntSet`s below because we'll be iterating over ordered and non-ordered columns a lot more in `matchLastGroupKey` and `encode`, and I think it is faster to iterate over slices.

We have `spec.OrderedCols` as `[]uint32`, so I think it makes sense to populate `nonOrderedCols` as `[]uint32`. Anecdotally, I remember I used `FastIntSet` somewhere and you suggested to just use slices instead, and I agree with that sentiment - this code is not on the hot-path, so we don't need to optimize the set subtraction, and the current approach seems as the most readable to me.


<!-- Sent from Reviewable.io -->

2020-10-01 15:25 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-:-MIZl2Tq04EfqoN3oPEQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/distinct.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-MIZgo_xCLqithsXOLdf:-MIZkeAGDoUrW0exb7KJ:b-810w0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7e16bf73dcaa4627203a25958e8ca971bf72fe/pkg/sql/rowexec/distinct.go#L88)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think it's important in the grand scheme of things (performance-wise), in fact, it might be worse to keep on using `FastIntSet`s below because we'll be iterating over ordered and non-ordered columns a lot more in `matchLastGroupKey` and `encode`, and I think it is faster to iterate over slices.

We have `spec.OrderedCols` as `[]uint32`, so I think it makes sense to populate `nonOrderedCols` as `[]uint32`. Anecdotally, I remember I used `FastIntSet` somewhere and you suggested to just use slices instead, and I agree with that sentiment - this code is not on the hot-path, so we don't need to optimize the set subtraction, and the current approach seems as the most readable to me.
</blockquote></details>

I was thinking about readability, not performance :shrug: up to you


<!-- Sent from Reviewable.io -->

2020-10-01 16:12 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-:-MIZvoyfEEfdBqIDrUHB:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/distinct.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54724#-MIZgo_xCLqithsXOLdf:-MIZvkv76RBVA2WsIoEo:bnntntm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f7e16bf73dcaa4627203a25958e8ca971bf72fe/pkg/sql/rowexec/distinct.go#L88)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I was thinking about readability, not performance :shrug: up to you
</blockquote></details>

I'll keep it then.


<!-- Sent from Reviewable.io -->

2020-10-01 16:51 UTC, merged