rowexec: account for some allocations due to hashing of datums
cockroachdb/cockroach pull request #54770
Opened 2020-09-24 22:57 UTC by yuzefovich

This commit adds memory accounting for the allocations of `tree.Datum`s
that might occur during `Fingerprint`ing (for example, when the encoded
datum uses a value encoding and we want to use the key ASC encoding). In
many cases, the newly allocated datums are only needed temporary, but we
know that GC takes its time with reclaiming the memory, so we choose to
go this route of possibly over-accounting in several places (in case of
the hash aggregator, windower, and sampler). This should improve the
stability of CockroachDB by preventing some crashes.

Release note: None

2020-09-24 22:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54770)
<!-- Reviewable:end -->

2020-09-25 02:38 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/rowenc/encoded_datum.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MI26xyw8hutItfBH2VN:-MI26xyw8hutItfBH2VO:b8d9ih9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c816121221b1455b982c963fd41b86c2d7c0efd/pkg/sql/rowenc/encoded_datum.go#L305)):*
> ```Go
> 	default:
> 		// For values that are key encodable, using the ascending key.
> 		// TODO (rohany): However, there should be a knob for the hasher that sees
> ```

Note that I prototyped this in #54722 and decided to abandon it since it wasn't as easy as I thought initially.


<!-- Sent from Reviewable.io -->

2020-09-29 14:59 UTC, asubiotto requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/rowexec/aggregator.go, line 960 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPLjG71RIWbmon--s_:-MIPLjG71RIWbmon--sa:b-ovv0fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/aggregator.go#L960)):*
> ```Go
> 	appendTo []byte, row rowenc.EncDatumRow,
> ) (encoding []byte, err error) {
> 	// We might allocate tree.Datums when hashing the row, so we'll
> ```

Is it `tree.Datums` allocation or `encoded` slice allocations we're worried about? It seems like we only decode if a JSON value. 
___
*[pkg/sql/rowexec/aggregator.go, line 968 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPLyle3fKb7W7VekjN:-MIPLyle3fKb7W7VekjO:b-uxfsrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/aggregator.go#L968)):*
> ```Go
> 	for _, colIdx := range ag.groupCols {
> 		newMemUsage -= row[colIdx].Size()
> 		appendTo, err = row[colIdx].Fingerprint(
> ```

We're not worried about `appendTo` because that just points to the `encoded` slice, right?
___
*[pkg/sql/rowexec/sampler.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMOTy8-Nt1Yrqhrne:-MIPMOTy8-Nt1Yrqhrnf:b-ti2afm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/sampler.go#L549)):*
> ```Go
> 	// likely take some time before GC reclaims that memory, so we choose the
> 	// over-accounting route to be safe.
> 	newMemUsage := uintptr(0)
> ```

Is the only memory usage here the fingerprinting or is the row stored somewhere?
___
*[pkg/sql/rowexec/windower.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMdO_0QVgkKPD2z60:-MIPMdO_0QVgkKPD2z61:b1olr88) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/windower.go#L689)):*
> ```Go
> 						"hash column %d, row with only %d columns", errors.Safe(col), errors.Safe(len(row)))
> 				}
> 				newMemUsage -= row[col].Size()
> ```

Since memory usage is important, maybe `Fingerprint` should require an account or something similar as a parameter?


<!-- Sent from Reviewable.io -->

2020-09-29 15:27 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/aggregator.go, line 960 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPLjG71RIWbmon--s_:-MIPNv-G5I0hD-zICb8P:bjjd9cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/aggregator.go#L960)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it `tree.Datums` allocation or `encoded` slice allocations we're worried about? It seems like we only decode if a JSON value. 
</blockquote></details>

It's `tree.Datum` allocation. We might have `encoded` with a different encoding than key ASC, so `Fingerprint` will do the following: `key DESC / value encoding -> tree.Datum -> key ASC encoding`. The datum is allocated only as an intermediate step, and in such scenario this happens for all types, it's just for JSON we use special value encoding as the last step.
___
*[pkg/sql/rowexec/aggregator.go, line 968 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPLyle3fKb7W7VekjN:-MIPOne--7kPV5D8CWbY:b-loa6o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/aggregator.go#L968)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We're not worried about `appendTo` because that just points to the `encoded` slice, right?
</blockquote></details>

We're not worried about `appendTo` here because it is accounted for elsewhere (in `accumulateRow` method). We reuse the same `[]byte scratch` for that, and then we're casting to `string` (which deep-copies) which we then account for with `stringarena.Arena`.
___
*[pkg/sql/rowexec/sampler.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMOTy8-Nt1Yrqhrne:-MIPP8Tn93SjQNYsZFju:b-p00w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/sampler.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is the only memory usage here the fingerprinting or is the row stored somewhere?
</blockquote></details>

The row itself is not stored anywhere: with auto stats we read all rows, perform some computations on them storing only the results of the computation, and then the rows are discarded. These sketches are responsible for estimating the number of distinct values in the columns (as well as few other easier things), and they store a subset of hashes of all elements (or something like that). The rows (as well as the datums) are actually discarded once the computation on it is performed; however, before of the slowness of GC, the rows can take up the memory for some time. This change adds accounting for a portion of the totally used memory. I thought about accounting for the whole rows, but then the stats jobs might never succeed on the big tables even when they wouldn't hit an OOM.

To be honest, I'm a bit on the fence about this change with stats. It seems like it could improve the stability by preventing an OOM, but the accounting here is incomplete and might produce false positives as well.
___
*[pkg/sql/rowexec/windower.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMdO_0QVgkKPD2z60:-MIPSICR23oX6qfOpnSe:bjcgijz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/windower.go#L689)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Since memory usage is important, maybe `Fingerprint` should require an account or something similar as a parameter?
</blockquote></details>

I thought about that too, but I'm hoping to backport this change to 20.2 (at least the hash aggregation adjustment), so I wanted to be it as least invasive as possible. There are 9 callers of `Fingerprint` right now, and in several of them we have `tree.Datum`s inside of `EncDatum`s for sure and for some of them - I think - we would like to avoid the memory accounting (e.g. the hash router). I guess an empty memory account could serve as a signal that memory accounting is not required, I'll add that.


<!-- Sent from Reviewable.io -->

2020-09-29 23:56 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/windower.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMdO_0QVgkKPD2z60:-MIRHq-Z8dZkaReNxJ5S:bfwr2xh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/windower.go#L689)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I thought about that too, but I'm hoping to backport this change to 20.2 (at least the hash aggregation adjustment), so I wanted to be it as least invasive as possible. There are 9 callers of `Fingerprint` right now, and in several of them we have `tree.Datum`s inside of `EncDatum`s for sure and for some of them - I think - we would like to avoid the memory accounting (e.g. the hash router). I guess an empty memory account could serve as a signal that memory accounting is not required, I'll add that.
</blockquote></details>

Implemented that change, RFAL.


<!-- Sent from Reviewable.io -->

2020-09-30 08:35 UTC, asubiotto requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rytaft, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6U7nE5P6HtwZ6Fg5:-MIT6U7nE5P6HtwZ6Fg6:b9gtipd) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/col/coldataext/datum_vec.go#L87)):*
> ```Go
> 	// We know that we have tree.Datum, so there will definitely be no need to
> 	// decode ed for fingerprinting, so we pass in nil memory account.
> 	b, err := ed.Fingerprint(context.Background(), d.ResolvedType(), da, nil /* appendTo */, nil /* acc */)
> ```

I think this calls for a `context.TODO` use since we'd probably like to plumb a context down here.
___
*[pkg/sql/rowenc/encoded_datum.go, line 298 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6dLB6gQ5IkBEIr_v:-MIT6dLB6gQ5IkBEIr_w:b-cizz62) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/sql/rowenc/encoded_datum.go#L298)):*
> ```Go
> // The caller is still responsible for accounting for the memory under the
> // returned byte slice.
> func (ed *EncDatum) Fingerprint(
> ```

I think a short unit test for this won't hurt.
___
*[pkg/sql/rowexec/sampler.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMOTy8-Nt1Yrqhrne:-MIT7Ht98Y8_LV8aNv-7:blqq0j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/sampler.go#L549)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The row itself is not stored anywhere: with auto stats we read all rows, perform some computations on them storing only the results of the computation, and then the rows are discarded. These sketches are responsible for estimating the number of distinct values in the columns (as well as few other easier things), and they store a subset of hashes of all elements (or something like that). The rows (as well as the datums) are actually discarded once the computation on it is performed; however, before of the slowness of GC, the rows can take up the memory for some time. This change adds accounting for a portion of the totally used memory. I thought about accounting for the whole rows, but then the stats jobs might never succeed on the big tables even when they wouldn't hit an OOM.

To be honest, I'm a bit on the fence about this change with stats. It seems like it could improve the stability by preventing an OOM, but the accounting here is incomplete and might produce false positives as well.
</blockquote></details>

I think this accounting is probably a good thing to do cc @rytaft 
___
*[pkg/sql/rowexec/windower.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMdO_0QVgkKPD2z60:-MIT5nRh5incllkzZoOc:b-fqc61o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/windower.go#L689)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Implemented that change, RFAL.
</blockquote></details>

Thanks. However, I don't think this makes the cut for 20.2 (at least not 20.2.0) because it's not a fix for a concrete release blocker.


<!-- Sent from Reviewable.io -->

2020-09-30 16:50 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @rytaft)

___
*[pkg/col/coldataext/datum_vec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6U7nE5P6HtwZ6Fg5:-MIUc_x9EZ1DQh9eRfPV:bzwe7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/col/coldataext/datum_vec.go#L87)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this calls for a `context.TODO` use since we'd probably like to plumb a context down here.
</blockquote></details>

Why would we plumb it down? It's only used when `acc` is non-nil, and we don't want the accounting in this case. I'll expand the comment on `Fingerprint`.
___
*[pkg/sql/rowenc/encoded_datum.go, line 298 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6dLB6gQ5IkBEIr_v:-MIUuJCj3329NtFcEEOK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/sql/rowenc/encoded_datum.go#L298)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think a short unit test for this won't hurt.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/windower.go, line 689 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMdO_0QVgkKPD2z60:-MIUuau3CZNO9H8CZL1t:b-f6zq0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/windower.go#L689)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Thanks. However, I don't think this makes the cut for 20.2 (at least not 20.2.0) because it's not a fix for a concrete release blocker.
</blockquote></details>

Ok, but I think it'd be beneficial to backport this (20.2.1 seems fine to me) since there are some scenarios when this accounting could prevent us from crashing.


<!-- Sent from Reviewable.io -->

2020-09-30 18:31 UTC, rytaft commented
___
*[pkg/sql/rowexec/sampler.go, line 549 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIPMOTy8-Nt1Yrqhrne:-MIV03a28x6fe0yEvhzF:b-6jogcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cfeb454a83b9a32ade91911027c9ebcc5c874c6/pkg/sql/rowexec/sampler.go#L549)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this accounting is probably a good thing to do cc @rytaft 
</blockquote></details>

I'd be surprised if there's much additional memory used here than what is already accounted for by the `SampleReservoir`, but this seems fine...


<!-- Sent from Reviewable.io -->

2020-10-01 14:48 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-:-MIZcfhv0ib8o-sPbcqi:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/col/coldataext/datum_vec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6U7nE5P6HtwZ6Fg5:-MIZcCzc7cp8B3iXrzOL:b-jzfyoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/col/coldataext/datum_vec.go#L87)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why would we plumb it down? It's only used when `acc` is non-nil, and we don't want the accounting in this case. I'll expand the comment on `Fingerprint`.
</blockquote></details>

Sorry, if we won't ever use a context here, then it's fine to use `context.Background`


<!-- Sent from Reviewable.io -->

2020-10-01 16:14 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-:-MIZwJQi6y51ZqvKJ74F:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldataext/datum_vec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54770#-MIT6U7nE5P6HtwZ6Fg5:-MIZwKjR5K2NhenDyvbG:b-mi0xy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/24a1791bc16bbf7a53c3cd8e20678d80b41ac247/pkg/col/coldataext/datum_vec.go#L87)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry, if we won't ever use a context here, then it's fine to use `context.Background`
</blockquote></details>

Let's keep it as `context.TODO` just in case.


<!-- Sent from Reviewable.io -->

2020-10-01 17:27 UTC, yuzefovich commented
bors r-

2020-10-01 17:29 UTC, yuzefovich commented
Fixed merge conflict.

bors r+

2020-10-01 18:44 UTC, merged