tree: correct sizes for geospatial datums
cockroachdb/cockroach pull request #54868
Opened 2020-09-28 15:38 UTC by otan

These were previously inaccurate, which may result in OOMs.

Release note: None

2020-09-28 15:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54868)
<!-- Reviewable:end -->

2020-09-28 20:21 UTC, sumeerbhola requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/sem/tree/datum.go, line 2833 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54868#-MILMrtQ1F0RVQ_PIyqm:-MILMrtRAq1b1iNE8piM:b-1de93) ([raw file](https://github.com/cockroachdb/cockroach/blob/429c9be3aa81a0cbc4c8edc0c36c394e77ca91a7/pkg/sql/sem/tree/datum.go#L2833)):*
> ```Go
> 		bboxSize = unsafe.Sizeof(*bbox)
> 	}
> 	return unsafe.Sizeof(*d) + bboxSize + uintptr(len(d.EWKB()))
> ```

how about a `SpatialObjectSize` function and use it in both places?


<!-- Sent from Reviewable.io -->

2020-09-28 20:29 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/sem/tree/datum.go, line 2833 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54868#-MILMrtQ1F0RVQ_PIyqm:-MILOu1ZEdU3Vd9-pirY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/429c9be3aa81a0cbc4c8edc0c36c394e77ca91a7/pkg/sql/sem/tree/datum.go#L2833)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about a `SpatialObjectSize` function and use it in both places?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 13:01 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54868#-:-MIOwywGBGsKEyXA3_QL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2020-09-29 14:50 UTC, otan commented
bors r=sumeerbhola

2020-09-29 14:50 UTC, otan commented
bors r=sumeerbhola

2020-09-29 16:00 UTC, merged