[WIP] cli: add import pgdump/mysqldump CLI command
cockroachdb/cockroach pull request #54896
Opened 2020-09-29 00:00 UTC by adityamaru

This change introduces a new CLI command to import
locally saved PGDUMP or MYSQLDUMP files into a running
cockroach cluster.

The underlying logic relies on user scoped userfile
storage to upload the local dump file to, and subsequently
import data from. Most of the heavy lifting was already
completed during the development of the userfile storage.

We can only support bundle formats that have the table
schemas to be imported, baked into the dump files. The newly
added CLI commands support the same options as IMPORT PGDUMP
and IMPORT MYSQLDUMP from the SQL shell do. These options
are to be passed in as CLI flags.

Following are the CLI examples:
`./cockroach import db <format> <source>`
`./cockroach import table <tablename> <format> <source>`

Release note (cli change): Adds an import CLI command which
allows users to upload and import local dump files into a
running cockroach cluster. We currently support PGDUMP and
MYSQLDUMP formats.

2020-09-29 00:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/54896)
<!-- Reviewable:end -->

2020-09-29 00:04 UTC, adityamaru commented
@knz I marked this as a WIP cause I'm running into a weird issue when trying to write tests for this CLI command. The `conn.ensureConn` method in `runImport` (https://github.com/cockroachdb/cockroach/pull/54896/files#diff-c5484a64be947c73503bb9e7ccbe71e1R71) is returning an EOF error when run through unit tests. When running against a local cockroach node all the commands work as expected. The EOF is apparently being throw because of a failed TCP handshake in the ensureConn method.

Spent a bunch of time trying to see what was different between this command and other existing ones but have not been able to spot anything yet, wondering if you see something amiss! I'll keep digging tomorrow.

2020-09-29 10:20 UTC, knz reviewed
> I'm running into a weird issue when trying to write tests for this CLI command.

I think you need to update `isSQLCommand` in `cli_test.go`.

The rest LGTM as far as the CLI code goes. I'll let your team comment on security and other UX aspects.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-:-MION1au98ZnxswTK88-:b-l79d1d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/cli/userfile.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MIOMRo24w7f24gIq_1E:-MIOMRo24w7f24gIq_1F:b-bssddz) ([raw file](https://github.com/cockroachdb/cockroach/blob/996002b1224f638d7faa2cb3d24e3ff50bf2e6e7/pkg/cli/userfile.go#L269)):*
> ```Go
> 	}
> 
> 	files, err := f.ListFiles(ctx, "")
> ```

`return f.ListFiles(...)`
___
*[pkg/cli/userfile.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MIOMXelAoBfF-lvmPun:-MIOMXelAoBfF-lvmPuo:bs89bva) ([raw file](https://github.com/cockroachdb/cockroach/blob/996002b1224f638d7faa2cb3d24e3ff50bf2e6e7/pkg/cli/userfile.go#L391)):*
> ```Go
> }
> 
> func uploadUserFile(
> ```

please add a comment to explain what the function does and the meaning of its return values.


<!-- Sent from Reviewable.io -->

2020-09-30 09:49 UTC, knz commented
>   I'm running into a weird issue when trying to write tests for this CLI command.

If you rebase it should be fixed now. (#54932)

2020-09-30 15:58 UTC, adityamaru commented
> > I'm running into a weird issue when trying to write tests for this CLI command.
> 
> If you rebase it should be fixed now. (#54932)

Thank you @knz!!

2020-10-14 13:10 UTC, adityamaru commented
@miretskiy this is RFAL now, thanks!

2020-10-21 16:45 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @knz)

___
*[pkg/cli/import.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB0utFBwyQ6aE2DS-W:-MKB0utFBwyQ6aE2DS-X:b-2bi6ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L34)):*
> ```Go
> 
> var importDumpTableCmd = &cobra.Command{
> 	Use:   "table <table> <format> <source>",
> ```

do we want to support multiple tables?
___
*[pkg/cli/import.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB1JTxCIU7K_oQ6zs2:-MKB1JTxCIU7K_oQ6zs3:bbp11tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L82)):*
> ```Go
> 	defer conn.Close()
> 	ctx := context.Background()
> 	return runImport(ctx, conn, importFormat, source, tableName, true /* isTableImport */)
> ```

maybe add a typedef instead?


<!-- Sent from Reviewable.io -->

2020-10-22 10:31 UTC, knz commented
btw how does this work with user-defined schemas?

2020-10-22 13:36 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @miretskiy)

___
*[pkg/cli/import.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB0utFBwyQ6aE2DS-W:-MKC5WpoAmC33b4uDZFw:btw1r5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L34)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we want to support multiple tables?
</blockquote></details>

importDumpFileCmd above is the flavour that supports the entire database. Or are you suggesting something in between a single table and the whole db? 
___
*[pkg/cli/import.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB1JTxCIU7K_oQ6zs2:-MKFWXWNDb7WULAKqOQk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L82)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

maybe add a typedef instead?
</blockquote></details>

Done.
___
*[pkg/cli/userfile.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MIOMRo24w7f24gIq_1E:-MKC9Qjo2-XYXxEUENfV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/996002b1224f638d7faa2cb3d24e3ff50bf2e6e7/pkg/cli/userfile.go#L269)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`return f.ListFiles(...)`
</blockquote></details>

Done.
___
*[pkg/cli/userfile.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MIOMXelAoBfF-lvmPun:-MKCAmiNAXEGOHjEMZtm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/996002b1224f638d7faa2cb3d24e3ff50bf2e6e7/pkg/cli/userfile.go#L391)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add a comment to explain what the function does and the meaning of its return values.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-22 13:40 UTC, adityamaru commented
> btw how does this work with user-defined schemas?

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/import_stmt.go#L784
We don't allow IMPORT to target user-defined schemas.

2020-10-22 13:51 UTC, knz commented
>  We don't allow IMPORT to target user-defined schemas.

Yes I understand, but can I import a table into a different schema than `public`?

Also what happens if I try to import a table into `pg_temp`? Does this work or do I get surprises?

2020-10-22 14:48 UTC, adityamaru commented
> > We don't allow IMPORT to target user-defined schemas.
> 
> Yes I understand, but can I import a table into a different schema than `public`?
> 
> Also what happens if I try to import a table into `pg_temp`? Does this work or do I get surprises?

I may be misunderstanding but the line I linked above only allows import to work on `public` schemas. So in my testing, supplying either a user-defined schema or a virtual schema throws an error `cannot import into a user-defined schema x` as expected. The commands I tested with are:
`./cockroach import table defaultdb.foo.simple pgdump pkg/ccl/importccl/testdata/pgdump/simple.sql --insecure`
`./cockroach import table defaultdb.pg_catalog.simple pgdump pkg/ccl/importccl/testdata/pgdump/simple.sql --insecure`

re: `pg_temp`, the way I understand it is that the import CLI command will create a new SQLConnection, and since the lifetime of pg_temp is tied to a session, our import CLI command can never see a `pg_temp` schema from another SQL connection. It currently returns an error `database does not exist: "defaultdb.pg_temp.simple"` which is as expected in my opinion.

2020-10-22 17:45 UTC, miretskiy approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @knz, and @miretskiy)

___
*[pkg/cli/import.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB0utFBwyQ6aE2DS-W:-MKGPSAr-feN3Udht2ky:b-ju7pwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L34)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

importDumpFileCmd above is the flavour that supports the entire database. Or are you suggesting something in between a single table and the whole db? 
</blockquote></details>

Right... Like import these 3 tables from the dump file.


<!-- Sent from Reviewable.io -->

2020-10-23 14:30 UTC, knz approved these changes
> Reviewed 4 of 6 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/cli/import_test.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKKrB5iCGDzEMkmPGBQ:-MKKrB5iCGDzEMkmPGBR:b-c4mv6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a737ecd654cb6722f90440f29bc4ca16aec4b42/pkg/cli/import_test.go#L31)):*
> ```Go
> ) string {
> 	knobs, unsetImportCLIKnobs := setImportCLITestingKnobs()
> 	defer unsetImportCLIKnobs()
> ```

Some explanatory comments around the pieces at the start of this function would help comprehension, thanks.


<!-- Sent from Reviewable.io -->

2020-10-26 14:03 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @miretskiy)

___
*[pkg/cli/import.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKB0utFBwyQ6aE2DS-W:-MK_ChQTCNadAnPKTzw3:b-y8vqif) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7c90c5b2002a6fbb3ba87d403192e0b410c1191/pkg/cli/import.go#L34)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Right... Like import these 3 tables from the dump file.
</blockquote></details>

I'll add it in a follow-up PR after bringing it up with Michael this week to get his product perspective. The change should be minimal.
___
*[pkg/cli/import_test.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/54896#-MKKrB5iCGDzEMkmPGBQ:-MK_D2LnBINLG-lJorVI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a737ecd654cb6722f90440f29bc4ca16aec4b42/pkg/cli/import_test.go#L31)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Some explanatory comments around the pieces at the start of this function would help comprehension, thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-26 15:34 UTC, adityamaru commented
TFTRs!

bors r=miretskiy,knz

2020-10-26 17:02 UTC, merged