ui: extend diagnostics column to allow activate and download reports
cockroachdb/cockroach pull request #55164
Opened 2020-10-02 10:45 UTC by koorosh

Previously, Statements table had a Diagnostics column which allowed
users to request diagnostics reports for the first time and then
displayed status for requested report only. As result it wasn't
possible to download already generated report or request new one
report from the statements table.

With current changes, Diagnostics column allows requesting new
reports every time when previous reports are generated.
Also, it provides a list with links to download previous reports.

The main change is to provide a list of available (or requested)
reports for every statement (instead of a single, most recent
report as it was before). Then extracted `StatementsPage` component
(from `admin-ui-components` package) handles all rendering logic
for this list of reports.

Minor changes:
- `WAITING FOR QUERY` status is renamed to `WAITING` for new design
- `getDiagnosticsStatus` utility function is reused to reduce code
duplication

Resolves: #50824
Depends on: https://github.com/cockroachdb/admin-ui-components/pull/31

Release note (admin ui change): Diagnostics column (on statements table)
has been changed and includes `Activate` button and dropdown list to
download completed reports. Also, diagnostics badge status is changed from
`WAITING FOR QUERY` to `WAITING`

![Screen Shot 2020-10-01 at 4 55 32 PM](https://user-images.githubusercontent.com/3106437/94915373-77c62c80-04b5-11eb-8fef-4b33db15613b.png)

2020-10-02 10:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55164)
<!-- Reviewable:end -->

2020-10-15 17:12 UTC, dhartunian approved these changes
@koorosh really appreciate the detail in the commit message. Nice work!

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55164#-:-MJhEYBRD5j97Ug-x8-L:b-2tceug)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-15 17:13 UTC, dhartunian requested changes
@koorosh I am expecting this PR to bump the `admin-ui-components` version, am I missing something?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55164#-:-MJhF43u0uOpVDFxmW1F:b-7jcokr)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-16 11:43 UTC, koorosh commented
> @koorosh I am expecting this PR to bump the `admin-ui-components` version, am I missing something?
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55164#-:-MJhF43u0uOpVDFxmW1F:b-7jcokr)_ status: :shipit: complete! 0 of 0 LGTMs obtained

@dhartunian , you're definitely right, already updated with bumped version. Thanks!

2020-10-19 20:22 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55164#-:-MK1Woxt8oBUXIRjiClw:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-20 11:53 UTC, koorosh commented
bors r+

2020-10-20 12:31 UTC, merged