sql: add jsonb_exists_any operator
cockroachdb/cockroach pull request #55172
Opened 2020-10-02 14:05 UTC by adzimzf

Currently, CRDB doesn't have jsonb_exists_any operator.

Fixes #54941.

Release note (sql change): Implement the builtin `add jsonb_exists_any(jsonb, text[])` operator

2020-10-02 14:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55172)
<!-- Reviewable:end -->

2020-10-02 16:43 UTC, yuzefovich reviewed
Thanks for working on this!

Apart from having a builtin function, there is `?|` operator which does exactly the same thing, and I think it'd be great if we added the support for that operator in this PR as well. That change will be slightly more involved, but following an example of already existing operator (e.g. `JSONFetchVal`) should give you an idea of how to do it. Please let us know whether you'd be interested in working on that and whether more detailed instructions are necessary.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-:-MIe9ckt4cd75q2k6FQ1:bd3k8i5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adzimzf)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 1153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe7Ypw9AwCkE5K2R30:-MIe7Ypw9AwCkE5K2R31:bc1m8o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/logictest/testdata/logic_test/json_builtins#L1153)):*
> ```
> query BBBB
> select
>        jsonb_exists_any('{"id":12,"name":"Micheal","address": {"postcode":12,"state":"California"}}'::jsonb, array['id']),
> ```

super nit: I think you meant `Michael` and not `Micheal`.
___
*[pkg/sql/sem/builtins/builtins.go, line 2998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8l5547pTUJCAepAe:-MIe8l5547pTUJCAepAf:b-4lgpms) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L2998)):*
> ```Go
> 				j := tree.MustBeDJSON(args[0])
> 
> 				if j.Type() == json.ArrayJSONType {
> ```

Can you add a logic test for this case?
___
*[pkg/sql/sem/builtins/builtins.go, line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8s6J7pg1mKd82le5:-MIe8s6J7pg1mKd82le6:b-gu8akp) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L3019)):*
> ```Go
> 				return tree.DBoolFalse, nil
> 			},
> 			Info:       "Determine weather any keys are exist in the JSON",
> ```

nit: some grammar errors, I'd say `Returns whether any of the strings in the text array exist as top-level keys or array elements` (based on Postgres docs).

Also, I wonder what "array elements" refers to, do you have an idea? Can you come up with a test query for this?


<!-- Sent from Reviewable.io -->

2020-10-02 17:34 UTC, otan requested changes
If it helps, I think the `?!` might be a separate issue/PR.
This current PR has a few improvements in functionality that we can make to make it compatible with Postgres.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-:-MIeNDlX1iAVa4SYj4TL:b-4dswqs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adzimzf and @yuzefovich)

___
*[pkg/sql/sem/builtins/builtins.go, line 2998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8l5547pTUJCAepAe:-MIeMYAG7LJV-IQiuIjk:b-rpd210) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L2998)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Can you add a logic test for this case?
</blockquote></details>

this case should return true if the jsonb is an array.

psql:
```

otan=# select jsonb_exists_any('["a"]', '{"a"}');
 jsonb_exists_any
------------------
 t
(1 row)
```

note the array can contains ints:

```
otan=# select jsonb_exists_any('["a", 10, 12]', '{"a"}'::text[]);
 jsonb_exists_any
------------------
 t
(1 row)
```
___
*[pkg/sql/sem/builtins/builtins.go, line 3004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIeMST-9i0tO_QcQ52S:-MIeMST-9i0tO_QcQ52T:bafojrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L3004)):*
> ```Go
> 				dArray := *tree.MustBeDArray(args[1])
> 				if dArray.Len() == 0 {
> 					return nil, pgerror.New(pgcode.IndeterminateDatatype,
> ```

this should work with an empty array for the any argument.

psql:
```
otan=# select jsonb_exists_any('["a"]', '{}');
 jsonb_exists_any
------------------
 f
(1 row)
```
___
*[pkg/sql/sem/builtins/builtins.go, line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8s6J7pg1mKd82le5:-MIeMinA1T2_CmPt-02s:bik3cat) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L3019)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: some grammar errors, I'd say `Returns whether any of the strings in the text array exist as top-level keys or array elements` (based on Postgres docs).

Also, I wonder what "array elements" refers to, do you have an idea? Can you come up with a test query for this?
</blockquote></details>

Please all terminate with a full stop.


<!-- Sent from Reviewable.io -->

2020-10-04 02:54 UTC, adzimzf reviewed
I'd be happy to work the operator `?!`,
should I add it to different PR or the same?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-:-MIlV-WU4r5erfoqOcXj:bmmdfzs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/json_builtins, line 1153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe7Ypw9AwCkE5K2R30:-MIlV_944d_RxKOjhll6:bytjdte) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/logictest/testdata/logic_test/json_builtins#L1153)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: I think you meant `Michael` and not `Micheal`.
</blockquote></details>

sorry for the typo
___
*[pkg/sql/sem/builtins/builtins.go, line 2998 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8l5547pTUJCAepAe:-MIlSAvz5HGmS5oKkduY:b45z71h) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L2998)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this case should return true if the jsonb is an array.

psql:
```

otan=# select jsonb_exists_any('["a"]', '{"a"}');
 jsonb_exists_any
------------------
 t
(1 row)
```

note the array can contains ints:

```
otan=# select jsonb_exists_any('["a", 10, 12]', '{"a"}'::text[]);
 jsonb_exists_any
------------------
 t
(1 row)
```
</blockquote></details>

noted, 
on it to add the logical test and update the code.
___
*[pkg/sql/sem/builtins/builtins.go, line 3004 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIeMST-9i0tO_QcQ52S:-MIlVnu1CDDMUOLzs4Dv:b-4zhqd1) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L3004)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this should work with an empty array for the any argument.

psql:
```
otan=# select jsonb_exists_any('["a"]', '{}');
 jsonb_exists_any
------------------
 f
(1 row)
```
</blockquote></details>

Sorry I didn't notice there will be a case like this.
Any hints on how to spot the argument are `'{}'` or `array[]` ?, because in Postgres when the argument is `array[]` it'll throw an error ` Cannot determine type of empty array`

here's the query
```sql
    select jsonb_exists_any('{"id":12,"name":"Micheal","address": {"postcode":12,"state":"California"}}'::jsonb, array[]);
```
___
*[pkg/sql/sem/builtins/builtins.go, line 3019 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-MIe8s6J7pg1mKd82le5:-MIlWw3R4epRzdOZNw4o:b-7m2y43) ([raw file](https://github.com/cockroachdb/cockroach/blob/252d6da1ad9847c141ceb526c11ab0a9b70a0e2c/pkg/sql/sem/builtins/builtins.go#L3019)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Please all terminate with a full stop.
</blockquote></details>

noted


<!-- Sent from Reviewable.io -->

2020-10-04 03:22 UTC, adzimzf reviewed
Hi @yuzefovich,
I try to run this query in CRDB,
```sql
select '{"id":12,"name":"Michael","address": {"postcode":12,"state":"California"}}'::jsonb ?| array['id'];
```
seems CRDB has had it
![image.png](https://files.reviewableusercontent.io/images/reviewable/17941719/3HDY0SZFrSkwIUkmIq8fngVT/image.png)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55172#-:-MIlby3f1GcLZnrw07iO:b-3bpqu4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-10-04 04:41 UTC, otan commented
If it already exists we should re-use the same code.
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/eval.go#L2408

2020-10-04 07:46 UTC, adzimzf commented
> If it already exists we should re-use the same code.
> https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/eval.go#L2408

noted, I'll reuse the existing code.
@otan regarding the empty array, I check the operator `?|` has a different result compared to Postgres.
![image](https://user-images.githubusercontent.com/17941719/95009998-3e75f400-0650-11eb-9223-2fdee8c14b1d.png)

picture 1 from Postgres and picture 2 from CRDB,
is it okay?

2020-10-04 14:50 UTC, otan commented
Difference in this case is ok

2020-10-05 02:50 UTC, adzimzf commented
> Difference in this case is ok

well and noted

2020-10-06 09:31 UTC, adzimzf commented on pkg/sql/sem/tree/eval.go
> +func JSONExistAny(_ *EvalContext, json DJSON, dArray *DArray) (*DBool, error) {
sure

2020-10-06 09:39 UTC, adzimzf commented on pkg/sql/sem/tree/eval.go
> +func JSONExistAny(_ *EvalContext, json DJSON, dArray *DArray) (*DBool, error) {
done

2020-10-06 14:31 UTC, otan approved these changes

2020-10-06 14:31 UTC, otan commented
thanks!

bors r+

2020-10-06 15:14 UTC, merged