sql - Add optional PRIVILEGES keyword in GRANT ALL and REVOKE ALL
cockroachdb/cockroach pull request #55304
Opened 2020-10-07 18:55 UTC by ajstorm

Postgres provides the ability to specify "PRIVILEGES" after GRANT ALL
and REVOKE ALL so that it's clear that the command relates to privilges.
Until now we haven't provided that ability.  This change brings our
grant/revoke syntax closer inline with Postgres.

Release note (sql change): Add the ability to optionally specify the
PRIVILEGES keyword when issuing the GRANT ALL or REVOKE ALL command.

Before, a statement like the following would fail with a syntax error,
(even though it's allowed in Postgres):

GRANT ALL PRIVILEGES ON DATABASE a TO user1

This commit allows for the above syntax in CRDB.

2020-10-07 18:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55304)
<!-- Reviewable:end -->

2020-10-08 21:14 UTC, solongordon requested changes
Changes LGTM. Would you also update the parser unit tests in `pkg/sql/parser/parse_test.go` to cover the new syntax? We try to update that whenever there is new syntax supported. In this case I think you would be updating `TestParse2` because the PRIVILEGES part will not be included when the SQL is regenerated from the syntax tree.

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55304#-:-MJ92a7_4Yabi3gbO972:be8hm0f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)



<!-- Sent from Reviewable.io -->

2020-10-08 22:28 UTC, ajstorm reviewed
Thanks for that tip.  I'd originally added a test to TestParse, but of course it was failing.  When I read the accompanying comment at the top of the testcase, I figured that there was no way to add parsing testcases which generated a different SQL from the syntax tree.  Now that I know about TestParse2, I added my testcases there and they're working now.

I also added a comment along with TestParse to point future noobs like me to TestParse2 if that's where their testcase belongs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55304#-:-MJ9Ja3rEmYfn-u53Jyk:b-1nupam)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-08 22:30 UTC, ajstorm commented
bors r=solongordon

2020-10-08 23:30 UTC, merged