roachtest: add DROP DATABASE CASCADE at end of schemachange/random-load
cockroachdb/cockroach pull request #55345
Opened 2020-10-08 17:40 UTC by lucy-zhang

This commit adds a step at the end of schemachange/random-load to drop
the workload's database. This helps validate the correctness of DROP
DATABASE CASCADE in the presence of complex schemas.

Release note: None

2020-10-08 17:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55345)
<!-- Reviewable:end -->

2020-10-09 10:07 UTC, spaskob requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @spaskob)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBL4bIByzn_5bdq8sY:-MJBL4bIByzn_5bdq8sZ:bpfakyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L36)):*
> ```Go
> 			concurrency := 20
> 			if local {
> 				maxOps = 100
> ```

What is the reason to reduce the number of ops? Usually 100 will be too little to be able to catch any regressions?
___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBoQLTEYHXbVpSVEZC:-MJBoQLTEYHXbVpSVEZD:b-vqbzb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L142)):*
> ```Go
> 
> 	t.Status("performing validation after workload")
> 	validate(db)
> ```

This check would be even nicer if added directly to the schemachange random workload. In fact we already randomly validate all descriptors via this operation: https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/schemachange/schemachange.go#L867

You should be able to append to the existing worker operations queue the final two validations plus a new operation for `DROP DATABASE CASCADE`. See https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/schemachange/schemachange.go#L226
___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBp-2hEI1e09oqEXYW:-MJBp-2hEI1e09oqEXYX:b-yt5mqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L144)):*
> ```Go
> 	validate(db)
> 	t.Status("dropping database")
> 	_, err := db.ExecContext(ctx, `USE defaultdb; DROP DATABASE schemachange CASCADE;`)
> ```

I would turn this into an operation in the the schemachange random workload


<!-- Sent from Reviewable.io -->

2020-10-09 13:51 UTC, lucy-zhang reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBL4bIByzn_5bdq8sY:-MJC_uW7E3RthFMu677V:b4642qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L36)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

What is the reason to reduce the number of ops? Usually 100 will be too little to be able to catch any regressions?
</blockquote></details>

This is just for running locally. The purpose of running locally is usually just to develop and test the roachtest itself, not to test the database.
___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBoQLTEYHXbVpSVEZC:-MJCaC590RVnZOpYif4O:b-69pbz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L142)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

This check would be even nicer if added directly to the schemachange random workload. In fact we already randomly validate all descriptors via this operation: https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/schemachange/schemachange.go#L867

You should be able to append to the existing worker operations queue the final two validations plus a new operation for `DROP DATABASE CASCADE`. See https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/schemachange/schemachange.go#L226


</blockquote></details>

We can't drop the database in the workload because all the tables and enums (and schemas) are being created in that single database, and this is hardcoded. Once the workload is capable of creating databases and doing introspection on them, we can revisit this. The extra validation is so we can isolate any problems to the DROP DATABASE CASCADE if we need to.
___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBp-2hEI1e09oqEXYW:-MJCaOCZ2BrOZII-h0Ir:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L144)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I would turn this into an operation in the the schemachange random workload
</blockquote></details>

See above.


<!-- Sent from Reviewable.io -->

2020-10-09 14:31 UTC, spaskob approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBL4bIByzn_5bdq8sY:-MJCk-ny5HE_bs04CtM1:b-y3wak0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L36)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This is just for running locally. The purpose of running locally is usually just to develop and test the roachtest itself, not to test the database.
</blockquote></details>

Still 100 is rather small, I would use at least 200.


<!-- Sent from Reviewable.io -->

2020-11-02 04:14 UTC, lucy-zhang reviewed
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-:-ML694SoCv0xONcV_3qx:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55345#-MJBL4bIByzn_5bdq8sY:-ML69LvR7IeukNU3uZV1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73c1ea4fa865f6b78e99f990f9f1107a38b37e4/pkg/cmd/roachtest/schemachange_random_load.go#L36)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Still 100 is rather small, I would use at least 200.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 04:47 UTC, merged