kv: set destroy status before destroying data on subsumed replicas
cockroachdb/cockroach pull request #55477
Opened 2020-10-13 05:18 UTC by nvanbenschoten

This PR cleans up some handling around replica destruction that scared me when working on #46329 and #55293. Specifically, there were cases during merges where the destroy status on a replica would not be set until after that replicas data was destroyed. This was true of merges applied through entry application, although in those cases, no user data was removed so it seems mostly harmless. More concerning is that is was true of merges applied through snapshot application. This was extra concerning because snapshot application can delete user data if a subsumed range is only partially covered (see `clearSubsumedReplicaDiskData`). So we were hypothetically risking user-visible correctness problems, especially now that we allow follower reads through on subsumed ranges as of #51594.

This PR patches up these issues and then adds a few extra assertions that enforce stricter preconditions for the functions at play during replica destruction. Specifically, we now assert that the destroy status is set to `destroyReasonRemoved` _before_ calling `preDestroyRaftMuLocked`. We also assert that if `RemoveOptions.DestroyData` is false when passed to `removeInitializedReplicaRaftMuLocked`, then the destroy status is also set.

This unification allows us to remove the `ignoreDestroyStatus` flag on `RemoveOptions`, whose meaning is now exactly the inverse of `DestroyData`. In hindsight, pushing on why this extra flag was needed and what new information it was conveying to the function could have potentially caught these issues a little earlier.

I think we'll want to backport this to v20.2, though probably in the first patch release because there is some risk here (especially without sufficient time to bake on master) and we aren't aware of seeing any correctness issues from the combination of the bug fixed here and #51594.

Release note (bug fix): A hypothesized bug that could allow a follower read to miss data on a range in the middle of being merged away into its left-hand neighbor was fixed. The bug seems exceedingly unlikely to have materialized in practice.

2020-10-13 05:18 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55477)
<!-- Reviewable:end -->

2020-10-13 12:12 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

:tada: new invariant!

> Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-:-MJWs0FO8IbNuBkHoQli:bgu6jmg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)



<!-- Sent from Reviewable.io -->

2020-10-13 18:33 UTC, aayushshah15 requested changes
> especially now that we allow follower reads through on subsumed ranges as of #51594.

Note that #51594 only allows historical (i.e. old enough to be outside the uncertainty window of the subsumption) reads on the subsumed leaseholder.

To clarify, were we trying to solve the following hazard with this PR (comment snippet lifted from `clearSubsumedReplicaDiskData`):
```
	// a       b       c       d
	// |---1---|-------2-------|  S1
	// |---1-------------------|  S2
	// |---1-----------|---3---|  S3
	//
	// Since the merge is the first operation to happen, a follower could be down
	// before it completes. It is reasonable for a snapshot for r1 from S3 to
	// subsume both r1 and r2 in S1.
```
1. S3 sends a snapshot for r1 to S1.
2. We clear out the disk data for r2 on S1, but haven't applied the snapshot yet
3. S1 serves incorrect follower-reads for r2 before snapshot is applied

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-:-MJXfauCCl_IooYC3e5d:bnkdsnp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/store_merge.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-MJYDz8Q2Ei7O9ZhWUBf:-MJYDz8Q2Ei7O9ZhWUBg:b-mtw66g) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e1eb651e9c389cf3b109a9842ded5cc81f5218/pkg/kv/kvserver/store_merge.go#L55)):*
> ```Go
> 	if err := s.removeInitializedReplicaRaftMuLocked(ctx, rightRepl, rightDesc.NextReplicaID, RemoveOptions{
> 		// The replica was destroyed when the merge applied by to the tombstones
> 		// added to the batch in runPreApplyTriggersAfterStagingWriteBatch.
> ```

garbled sentence?


<!-- Sent from Reviewable.io -->

2020-10-14 23:31 UTC, nvanbenschoten reviewed
> To clarify, were we trying to solve the following hazard with this PR (comment snippet lifted from clearSubsumedReplicaDiskData):

Yes, that's exactly the hazard we are trying to solve.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-:-MJdRsdrD5NCqUey_mU3:b-lddpkp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @ajwerner)

___
*[pkg/kv/kvserver/store_merge.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-MJYDz8Q2Ei7O9ZhWUBf:-MJdRbVr8dPKUDm_GdP7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62e1eb651e9c389cf3b109a9842ded5cc81f5218/pkg/kv/kvserver/store_merge.go#L55)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

garbled sentence?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-15 00:57 UTC, aayushshah15 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Thanks for clarifying. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55477#-:-MJdYm9h4IcPRXW5wfxD:botd3ld)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15 and @ajwerner)



<!-- Sent from Reviewable.io -->

2020-10-15 04:00 UTC, nvanbenschoten commented
TFTRs!

bors r+

2020-10-15 04:37 UTC, merged