auth: use HMAC to secure OIDC flow
cockroachdb/cockroach pull request #55556
Opened 2020-10-14 16:27 UTC by dhartunian

This change replaces existing server-side state validation
logic implemented for the OIDC flow with a stateless
HMAC-based state validation.

The HMAC-based method works as follows:

1. When the auth request is triggered, we generate 2
random byte arrays: a key and a message.
The key is stored in a browser cookie at the client.
The message is hashed into an HMAC using the key and
the message and hash pair are encoded into a protobuf
and sent along to the auth provider as the `state` param.

2. When the auth callback is triggered, we receive the HMAC
message and hash pair in the encoded protobuf as well
 as the key in the client's browser cookie. We can use the key
and message to reconstruct the expected hash and check it
against the one in the state protobuf we just decoded.

If the hash matches we proceed with authentication, if it does
not we immediately fail.

This change makes it possible to validate the state in the
query param against the browser cookie without any
server-side state or communication between CRDB nodes.

Since the OIDC feature is experimental, this change also
removes the state validation RPC calls and protos. A consequence
of this is that a cluster in the process of upgrading will experience
malfunction of the OIDC-based login flow the node that initiates
the auth flow and the one that handles the callback are running
different versions that use different state validation logic.

Release note (security): This change modifies the state validation
for the OIDC login flow and replaces it with a stateless hash
validation of the state parameter with the browser cookie using HMAC.

2020-10-14 16:27 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55556)
<!-- Reviewable:end -->

2020-10-15 18:58 UTC, aaron-crl reviewed
Looks good from a functional security standpoint though I'd prefer to be more explicit in the naming of secrets and tokens to avoid potential accidents.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-:-MJhbGUu8__6BQfVARjg:b-sl5rhv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @dhartunian)

___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJhamo6Bvf_wiHOJ7iH:-MJhamo6Bvf_wiHOJ7iI:b6py6ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L241)):*
> ```
> 		// First we check to see that the state matches the cookie, then make sure it matches one we
> 		// stored server-side. Since we stored the entire encoded proto in the cookie, we can compare
> 		// without deserialization.
> ```

Per our chat, this comment looks stale.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_MC4A92nMoNPsRHw:-MJh_MC4A92nMoNPsRHx:b3cf38y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L349)):*
> ```Go
> 		}
> 
> 		size := 16
> ```

Value here should at least match the has output size of 32 bytes.

Reference: https://tools.ietf.org/html/rfc7518#section-3.2
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_Y9I4Z32o23mqd4y:-MJh_Y9I4Z32o23mqd4z:b1etxji) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L357)):*
> ```Go
> 		}
> 
> 		message := make([]byte, size)
> ```

Naming this "message" here threw me. Since this serves more as a token, perhaps we should call it something that includes that?
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh__Ky9oy-TnDjomJY:-MJh__KzBACNclTcgWQI:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L368)):*
> ```Go
> 
> 		encodedStateProto, err := encodeOIDCState(serverpb.OIDCState{
> 			Message:    message,
> ```

Same as above.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_gOK85Bm6ZbodcDA:-MJh_gOK85Bm6ZbodcDB:b-tvpyw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L379)):*
> ```Go
> 		oidcStateCookie := http.Cookie{
> 			Name:     stateCookieName,
> 			Value:    base64.URLEncoding.EncodeToString(key),
> ```

The name here threw me as well, this is a session secret and we probably want to label it as such to avoid potentially mishandling it.


<!-- Sent from Reviewable.io -->

2020-10-19 17:44 UTC, bdarnell requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0rHmVBZWEi1cqS39m:-MK0rHmVBZWEi1cqS39n:bjwy0hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L264)):*
> ```Go
> 
> 		mac := hmac.New(sha256.New, key)
> 		expectedMessageMAC := mac.Sum(statePb.Message)
> ```

The go hmac/hash interface is awful and error-prone; this doesn't do what you think. See #30859. This suggests a need for additional test coverage.

We also have a linter that is supposed to catch this that doesn't seem to be firing here: see commit 4d0a803f7ecd
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0w_JeArpbe2lZGzsp:-MK0w_JeArpbe2lZGzsq:bjp9ol3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L365)):*
> ```Go
> 
> 		mac := hmac.New(sha256.New, key)
> 		messageMAC := mac.Sum(message)
> ```

Ditto. 
___
*[pkg/server/serverpb/authentication.proto, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0sxt81Vj7CmzWsL7c:-MK0sxt81Vj7CmzWsL7d:bx25731) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/server/serverpb/authentication.proto#L59)):*
> ```protobuf
> 	reserved 1;
> 	reserved 2;
> 	bytes message = 3;
> ```

These proto fields need comments.


<!-- Sent from Reviewable.io -->

2020-10-30 19:36 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @bdarnell)

___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJhamo6Bvf_wiHOJ7iH:-MKv-KHy9cT36nHf9TzN:brpmqc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L241)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

> ```
> 		// First we check to see that the state matches the cookie, then make sure it matches one we
> 		// stored server-side. Since we stored the entire encoded proto in the cookie, we can compare
> 		// without deserialization.
> ```

Per our chat, this comment looks stale.
</blockquote></details>

removed.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0rHmVBZWEi1cqS39m:-MKv-LwyAhUaq0pf1et2:b-fl6huh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L264)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The go hmac/hash interface is awful and error-prone; this doesn't do what you think. See #30859. This suggests a need for additional test coverage.

We also have a linter that is supposed to catch this that doesn't seem to be firing here: see commit 4d0a803f7ecd
</blockquote></details>

Thank you for pointing this out. I think I had a different error that the linter was catching first. Latest push fixes usage.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_MC4A92nMoNPsRHw:-MKv-Tj3D8_pI0q2grfE:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L349)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Value here should at least match the has output size of 32 bytes.

Reference: https://tools.ietf.org/html/rfc7518#section-3.2
</blockquote></details>

done.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_Y9I4Z32o23mqd4y:-MKv-Uj56Xlz8M1-asUf:b-p722gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L357)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Naming this "message" here threw me. Since this serves more as a token, perhaps we should call it something that includes that?
</blockquote></details>

I changed names in the latest push to use `key` and `token` where appropriate.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0w_JeArpbe2lZGzsp:-MKv-ZDUCGGOmxju3ltJ:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L365)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Ditto. 
</blockquote></details>

done.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 368 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh__Ky9oy-TnDjomJY:-MKv-_CP0_lJ_Fd1kxEb:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L368)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

done.
___
*[pkg/ccl/oidcccl/authentication_oidc.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MJh_gOK85Bm6ZbodcDA:-MKv-a4e86VIcO1Q0AGT:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/ccl/oidcccl/authentication_oidc.go#L379)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

The name here threw me as well, this is a session secret and we probably want to label it as such to avoid potentially mishandling it.
</blockquote></details>

done.
___
*[pkg/server/serverpb/authentication.proto, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-MK0sxt81Vj7CmzWsL7c:-MKv-bk49NG_yyjKpq9G:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dce15c63ff4b1bea328b520931b04fddef3afab/pkg/server/serverpb/authentication.proto#L59)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These proto fields need comments.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2020-11-02 16:55 UTC, bdarnell approved these changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @bdarnell)



<!-- Sent from Reviewable.io -->

2020-11-09 15:31 UTC, aaron-crl approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55556#-:-MLhcOgkBz5LDFX-TTQq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @bdarnell)



<!-- Sent from Reviewable.io -->

2020-11-09 23:27 UTC, dhartunian commented
bors r+

2020-11-10 00:01 UTC, merged