colexec, colflow: add network latency stat to streams
cockroachdb/cockroach pull request #55705
Opened 2020-10-19 19:24 UTC by cathymw

This commit adds the information about network latency from an outbox to inbox
on EXPLAIN ANALYZE diagrams. 
The network latencies are obtained from the `node.Activity` map from the `NodesStatusServer`.

Closes: #54555 
Close: #43859

The following screenshot shows that EXPLAIN ANALYZE now shows network latency on streams:
![image](https://user-images.githubusercontent.com/23270879/96500231-897d3300-121c-11eb-8e6d-befc87a0a61c.png)

Release note (sql change): EXPLAIN ANALYZE diagrams now contain "network
latency" information on streams.

2020-10-19 19:24 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55705)
<!-- Reviewable:end -->

2020-10-20 00:11 UTC, cathymw commented
#54769 was closed in favour of this PR, as most of the feedback no longer applied. 
The following comments are still applicable and were addressed as follows:
- The refactoring of the `VectorizedStatsCollector` into a base struct and specialized stats collectors, will be done in a separate PR. I've added a TODO for now.
- `tuples output` is hidden for inboxes
- `IO time` was renamed to `deserialization time` for inboxes. I got this value by subtracting the network latency from the total time. Since the network latency is just an approximate stat, so I'm not sure if it's okay/a good idea to base another stat on this value. Thoughts?

2020-10-20 15:24 UTC, yuzefovich reviewed
Very cool! I only have a few nits, but I'll defer to Alfonso for approval.

> `IO time` was renamed to `deserialization time` for inboxes. I got this value by subtracting the network latency from the total time. Since the network latency is just an approximate stat, so I'm not sure if it's okay/a good idea to base another stat on this value. Thoughts?

I think the math is not quite right - the total time includes the latency for every received batch, but we're subtracting it only once. Looks like we should use something like this `deserialization time = total time - # batches x latency`. I like the idea of having this stat even if it's not perfectly accurate.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MK5_TjUAqA2_6Kh_H1O:b-lysykp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/colexec/stats.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5YpIR6T604UTDpegm:-MK5YpIS1Aaqzz9X8W8B:b-5lyk6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/stats.go#L37)):*
> ```Go
> // VectorizedStatsCollector collects VectorizedStats on Operators.
> //
> // If two Operators are connected (i.e. one is an input to another), the
> ```

nit: just noticed that this comment is no longer true (not related to this PR), so feel free to remove this paragraph.
___
*[pkg/sql/colexec/stats.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5_9aC827SDXEZBPty:-MK5_9aC827SDXEZBPtz:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/stats.go#L41)):*
> ```Go
> // StopWatch.
> // TODO(cathymw): refactor this class into a base and specialized stats
> // collectors
> ```

nit: missing period.
___
*[pkg/sql/colexec/execpb/stats.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5ZL_oCX44_kNkfWHY:-MK5ZL_oCX44_kNkfWHZ:bqk2749) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/execpb/stats.go#L104)):*
> ```Go
> 			fmt.Sprintf("%s: %v", networkLatencyQueryPlanSuffix, time.Duration(vs.NetworkLatency).Round(time.Microsecond)))
> 	} else {
> 		stats = append(stats, fmt.Sprintf("%s: %d", tuplesOutputQueryPlanSuffix, vs.NumTuples),
> ```

super nit: I think it'd be nice to have this `Sprintf` on a new line for consistency with above.
___
*[pkg/sql/colexec/execpb/stats.proto, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5ZpEuA1px9SOW7nBu:-MK5ZpEuA1px9SOW7nBv:bj42pfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/execpb/stats.proto#L42)):*
> ```protobuf
>   // if network latency should be shown or not.
>   bool on_stream = 10;
>   // network_latency is the latency time between outbox and inbox. It is set
> ```

nit: it might be worth calling out what is the unit of time here (I think it is nanoseconds).


<!-- Sent from Reviewable.io -->

2020-10-20 15:57 UTC, cathymw reviewed
Thanks for the quick review! :) Fixed the nits and deserialization time calculation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MK5hk_YCXtqmGU4VOpx:b-7siy5a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5YpIR6T604UTDpegm:-MK5g1jO4l73yLvHslJI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/stats.go#L37)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: just noticed that this comment is no longer true (not related to this PR), so feel free to remove this paragraph.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5_9aC827SDXEZBPty:-MK5g2xpCTZfVEyWD-Pd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/stats.go#L41)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execpb/stats.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5ZL_oCX44_kNkfWHY:-MK5gJ9cERES4Q-gF9zi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/execpb/stats.go#L104)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: I think it'd be nice to have this `Sprintf` on a new line for consistency with above.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execpb/stats.proto, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK5ZpEuA1px9SOW7nBu:-MK5gXohEMEEQ9eDXXGv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a81be2d754b5b09d176a0f210a6c97766d5fca2a/pkg/sql/colexec/execpb/stats.proto#L42)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: it might be worth calling out what is the unit of time here (I think it is nanoseconds).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-21 12:15 UTC, asubiotto requested changes
Nice!

> IO time was renamed to deserialization time for inboxes. I got this value by subtracting the network latency from the total time. Since the network latency is just an approximate stat, so I'm not sure if it's okay/a good idea to base another stat on this value. Thoughts?

Didn't we already calculate deserialization time using the timer you added or is that something we only did in the last version? I think that's my preferred way to calculate it.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MK9xsiRDilHHtocQQMx:b-ukoh3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cathymw and @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK9zwOo9P96PpdIyJNu:-MK9zwOo9P96PpdIyJNv:brzc1xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.go#L43)):*
> ```Go
> 	if vs.IO {
> 		if vs.OnStream {
> 			timeSuffix = deserializationTimeTagSuffix
> ```

I would leave this if block alone and set the `timeSuffix` in the below check of `vs.OnStream` so you only have to check it once.
___
*[pkg/sql/colexec/execpb/stats.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA-sR7-sBdwpCz_PK5:-MKA-sR7-sBdwpCz_PK6:b17ulwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.go#L101)):*
> ```Go
> 	if vs.OnStream {
> 		stats = append(stats,
> 			fmt.Sprintf("%s: %v", timeSuffix, (vs.Time-time.Duration(vs.NetworkLatency*vs.NumBatches)).Round(time.Microsecond)),
> ```

I think this is a bit leaky because the stats object shouldn't know how to calculate deserialization time. Maybe there's a way to have the inbox return deserialization time through `vs.Time`? Also, doesn't having this specific case mean that we don't output the number of tuples output? Rather than having `vs.OnStream` be a specific case. How about:
```
stats = []string{batches output, tuples output, time /* in inbox, this will be deserialization time */}
if vs.OnStream {
    stats = append(stats, network latency)
}
```
___
*[pkg/sql/colexec/execpb/stats.proto, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0TlwDes50UWF1U8x:-MKA0Tlx1TUGucjX4UMI:b-7frr6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.proto#L41)):*
> ```protobuf
>   // on_stream indicates whether the stats are shown on a stream. This decides
>   // if network latency should be shown or not.
>   bool on_stream = 10;
> ```

If you're going to do a refactor for this, I would get it in before this PR (or an earlier commit as we discussed). It would be unfortunate to add a new field to a protobuf that we'd then have to deprecate.
___
*[pkg/sql/colflow/vectorized_flow.go, line 591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0lSE-qgDskCEG1By:-MKA0lSE-qgDskCEG1Bz:b-k2y0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L591)):*
> ```Go
> 
> 	var latency int64
> 	ss, err := flowCtx.Cfg.NodesStatusServer.OptionalNodesStatusServer(errorutil.FeatureNotAvailableToNonSystemTenantsIssue)
> ```

What happens in case this is not a system tenant? `latency` will be 0, does that mean that no stats will be displayed? It would be great to just remove it from the plan if we can't get it.
___
*[pkg/sql/colflow/vectorized_flow.go, line 593 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA33N-7Bv-ix4nnDQ6:-MKA33N-7Bv-ix4nnDQ7:b-22kyc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L593)):*
> ```Go
> 	ss, err := flowCtx.Cfg.NodesStatusServer.OptionalNodesStatusServer(errorutil.FeatureNotAvailableToNonSystemTenantsIssue)
> 	if err == nil {
> 		response, _ := ss.Nodes(ctx, &serverpb.NodesRequest{})
> ```

This performs the RPC every time we set up a remote output stream (many times per query). As we discussed, I think we need to cache this map in a level above the`vectorizedFlowCreator`. There might be a better place but we would:
- Create some sort of helper `latencyGetter struct { cache latencyMap; server StatusServer }` that the distsql server or planner creates with a pointer to the status server.
- This helper would have some way to get latency:
```
func (lg latencyGetter) getLatency(from, to NodeID) {
    if time.Since(lastUpdate) > someTime {
        // The cache seems old, update it.
        lg.cache = convertToMap(lg.server.Nodes())
        lastUpdate = time.Now()
    }
    return lg.cache[from][to]
}
```
And we'd use the latencyGetter here (maybe there's a better name). This is a lot cheaper, since we don't expect latencies to vary much.
___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKA0zDZ3aMHjj-gHcKz:b2p6zgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
> ```protobuf
> // and an Inbox.
> message NetworkStats {
>   optional int64 latency = 1 [(gogoproto.nullable) = false];
> ```

I think this message deserves a more extensive comment about how this latency is calculated and why we're using the latency on the origin node and then sending it over rather than using the latency on the inbox. In fact, can't we get the same information from the inbox (we have access to the whole cluster matrix, right?)


<!-- Sent from Reviewable.io -->

2020-10-21 14:54 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA-sR7-sBdwpCz_PK5:-MKAdhf31rFmBmWqlRvP:b-s9r0zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.go#L101)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this is a bit leaky because the stats object shouldn't know how to calculate deserialization time. Maybe there's a way to have the inbox return deserialization time through `vs.Time`? Also, doesn't having this specific case mean that we don't output the number of tuples output? Rather than having `vs.OnStream` be a specific case. How about:
```
stats = []string{batches output, tuples output, time /* in inbox, this will be deserialization time */}
if vs.OnStream {
    stats = append(stats, network latency)
}
```
</blockquote></details>

`tuples output` is removed from the stream because it is duplicated with `rowsRead`, see https://github.com/cockroachdb/cockroach/pull/54769#pullrequestreview-498980682


<!-- Sent from Reviewable.io -->

2020-10-27 00:28 UTC, cathymw reviewed
Added a second commit that refactors the VectorizedStatsCollector and VectorizedStats types. Also, added a LatencyGetter struct to hold a map of all the node latencies.

>Didn't we already calculate deserialization time using the timer you added or is that something we only did in the last version? I think that's my preferred way to calculate it.

Having the inbox collect its own deserialization time was proposed in the last version. While I was testing the second commit, I found that `deserialization time = total time - # batches x latency` sometimes displays negative time values for the deserialization time. Since this PR is already getting quite large, I left the time displayed as `ioTime` and added a TODO to have the inbox collect its own the deserialization time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MK_hZGc0MEJX3MPnPLc:b-s5zpa5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MK9zwOo9P96PpdIyJNu:-MK_ia2v44D2VxvjzgcJ:bwlrlfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.go#L43)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would leave this if block alone and set the `timeSuffix` in the below check of `vs.OnStream` so you only have to check it once.
</blockquote></details>

Done. vs.OnStream was removed completely in the refactor (2nd commit).
___
*[pkg/sql/colexec/execpb/stats.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA-sR7-sBdwpCz_PK5:-MK_iz976twINWdLSiTW:b-pw4lkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.go#L101)):*
>I think this is a bit leaky because the stats object shouldn't know how to calculate deserialization time. Maybe there's a way to have the inbox return deserialization time through vs.Time?

I've removed this calculation for now, since it was showing negative time values for some queries. For now, I added a TODO to have inbox collect its own deserialization time, since it's a little out of scope for this PR. 

>Also, doesn't having this specific case mean that we don't output the number of tuples output?

+1 on what Yahor commented. Also, with the refactor in the second commit, I added a separate implementation of the `SpanStats` interface called `VectorizedInboxStats` that displays the stats we want for Inbox.
___
*[pkg/sql/colexec/execpb/stats.proto, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0TlwDes50UWF1U8x:-MK_lZvwACZWKmJ9ipMZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colexec/execpb/stats.proto#L41)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you're going to do a refactor for this, I would get it in before this PR (or an earlier commit as we discussed). It would be unfortunate to add a new field to a protobuf that we'd then have to deprecate.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 591 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0lSE-qgDskCEG1By:-MK_lsiw639aCQs7dNAm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L591)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What happens in case this is not a system tenant? `latency` will be 0, does that mean that no stats will be displayed? It would be great to just remove it from the plan if we can't get it.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 593 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA33N-7Bv-ix4nnDQ6:-MKagi4M5O_ptlyakNvg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L593)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This performs the RPC every time we set up a remote output stream (many times per query). As we discussed, I think we need to cache this map in a level above the`vectorizedFlowCreator`. There might be a better place but we would:
- Create some sort of helper `latencyGetter struct { cache latencyMap; server StatusServer }` that the distsql server or planner creates with a pointer to the status server.
- This helper would have some way to get latency:
```
func (lg latencyGetter) getLatency(from, to NodeID) {
    if time.Since(lastUpdate) > someTime {
        // The cache seems old, update it.
        lg.cache = convertToMap(lg.server.Nodes())
        lastUpdate = time.Now()
    }
    return lg.cache[from][to]
}
```
And we'd use the latencyGetter here (maybe there's a better name). This is a lot cheaper, since we don't expect latencies to vary much.
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKar02T4G1EZkCO8nnl:b31gfmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this message deserves a more extensive comment about how this latency is calculated and why we're using the latency on the origin node and then sending it over rather than using the latency on the inbox. In fact, can't we get the same information from the inbox (we have access to the whole cluster matrix, right?)
</blockquote></details>

I updated the comment to be more extensive, but I'm not sure I understand the second part of your comment. The latency is retrieved at the outbox and sent to the inbox because retrieving the latency requires both the sending node ID and receiving node ID, but the inbox doesn't have access to which node ID data is coming from


<!-- Sent from Reviewable.io -->

2020-10-27 10:00 UTC, asubiotto requested changes
> While I was testing the second commit, I found that deserialization time = total time - # batches x latency sometimes displays negative time values for the deserialization time. Since this PR is already getting quite large, I left the time displayed as ioTime and added a TODO to have the inbox collect its own the deserialization time.

SGTM

Looking good, although I think you should reorder the commits (using `git rebase -i HEAD~2` and swapping the order of the commits) since the stats commit adds some code that is made unnecessary by the refactor commit .

> Reviewed 6 of 17 files at r1, 7 of 7 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MKdL4za2nhEyNK3qWPy:b-mb6kog)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/server/server_sql.go, line 67 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdP0i49f_XPDuYpkES:-MKdP0i49f_XPDuYpkET:bdxjjcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/server_sql.go#L67)):*
> ```Go
> 	"github.com/marusama/semaphore"
> 	"google.golang.org/grpc"
> 	"math"
> ```

I think these imports should stay where they were. Have you enabled `crlfmt` in goland? That should take care of it for you automatically on save.
___
*[pkg/server/serverpb/status.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPEbg0X4gnYf3joFy:-MKdPEbg0X4gnYf3joFz:b-3lzhtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L81)):*
> ```Go
> // the Inbox.
> func (lg *LatencyGetter) GetLatency(
> 	outboxNodeID roachpb.NodeID,
> ```

Instead of `outbox/inbox`, you should make this more general, with for example `originNodeID` and `targetNodeID`.
___
*[pkg/server/serverpb/status.go, line 83 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPANSDsady9VddpgY:-MKdPANSDsady9VddpgZ:ba8rjis) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L83)):*
> ```Go
> 	outboxNodeID roachpb.NodeID,
> 	inboxNodeID roachpb.NodeID,
> 	ctx context.Context,
> ```

nit: `context` is usually the first argument.
___
*[pkg/server/serverpb/status.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPWhA2ssO4-LnCsFg:-MKdPWhA2ssO4-LnCsFh:bwmcr6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L85)):*
> ```Go
> 	ctx context.Context,
> ) int64 {
> 	if time.Since(lg.lastUpdatedTime) > time.Second {
> ```

extract this `time.Second` into a constant and refer to it in the comment so it doesn't become stale if it is changed. Also, maybe we can make this 5*time.Second, not sure we get anything from pinging these nodes every second.
___
*[pkg/server/serverpb/status.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPPdH4D6rg6-rpQRa:-MKdPPdH4D6rg6-rpQRb:bxrh7l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L86)):*
> ```Go
> ) int64 {
> 	if time.Since(lg.lastUpdatedTime) > time.Second {
> 		// update latencies in latencyMap
> ```

nit: capitalize and period.
___
*[pkg/server/serverpb/status.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPxhT9f78XFvM-MVX:-MKdPxhT9f78XFvM-MVY:b-2y2afl) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L88)):*
> ```Go
> 		// update latencies in latencyMap
> 		ss, err := lg.NodesStatusServer.OptionalNodesStatusServer(errorutil.FeatureNotAvailableToNonSystemTenantsIssue)
> 		if err == nil {
> ```

Can you avoid excessive indentation by doing `if err != nil { do something? }` so that your `err == nil` is implicit and the block doesn't need to be indented. In general, it's nice to indent only the smallest blocks. For example, you can change your code to be:
```
if time.Since(lastUpdated) <= time.Second {
     return lg.latencyMap
}
// Implicit else, update with result from Nodes
lg.latencyMap.update()
if err != nil {
    return something
}
return updated lg.latencyMap
```
___
*[pkg/server/serverpb/status.go, line 106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPTAk3UJaLCgb_SIE:-MKdPTAk3UJaLCgb_SIF:b-6eki3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L106)):*
> ```Go
> 			}
> 		}
> 		fmt.Println(lg.latencyMap)
> ```

leftover
___
*[pkg/sql/distsql_running.go, line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdQlcv3Yp46r30YcfG:-MKdQlcv3Yp46r30YcfH:bytlxu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/distsql_running.go#L47)):*
> ```Go
> 	"github.com/cockroachdb/errors"
> 	opentracing "github.com/opentracing/opentracing-go"
> 	"math"
> ```

same thing re imports
___
*[pkg/sql/colexec/stats.go, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdT8m_AxQF_pxg36Gn:-MKdT8m_AxQF_pxg36Go:b-xptqr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L122)):*
> ```Go
> 	idTagKey string,
> 	inputWatch *timeutil.StopWatch,
> 	memMonitors []*mon.BytesMonitor,
> ```

All the nil monitors seem to indicate that it'd be nice to also have a memory/disk focused stat collector as well as one for IO operators (i.e. wherever we need to write `if vsc.IO`) but we can leave that for another PR.
___
*[pkg/sql/colexec/stats.go, line 201 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdRHvu6WZMRWfHKAbA:-MKdRHvu6WZMRWfHKAbB:blv6rws) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L201)):*
> ```Go
> }
> 
> func createSpan(
> ```

Could you make this a private method on the vectorized stats collector base since this needs a couple of inputs that are already fields of the struct?
___
*[pkg/sql/colflow/vectorized_flow.go, line 593 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA33N-7Bv-ix4nnDQ6:-MKdM7DMBxDM7YEd-3ME:b-og7vjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L593)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems like the new `LatencyGetter` is part of the refactor commit when it should be part of the stats commit.

Can you also add a comment about what happens if we can't get the node ID? 
___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKdMfTcA-hDfPtaD70w:bwl87av) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
> but the inbox doesn't have access to which node ID data is coming from

Got it, thanks. I had forgotten about this. BTW, I think the new comment is in the wrong commit. To undo this you can use `git restore` to undo the changes and stage them and then commit in the other commit. If it's too much work to separate the changes into their respective commits, I think I'm fine with squashing the two commits into one even though it's not ideal.


<!-- Sent from Reviewable.io -->

2020-10-27 14:55 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeW2xr1axghs2v-RAu:-MKeW2xr1axghs2v-RAv:b-uybg3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L65)):*
> ```Go
> }
> 
> // NetworkVectorizedStatsCollector collects InbocVectorizedStats on Inbox.
> ```

nit: `s/InbocVectorizedStats/VectorizedInboxStats/`.
___
*[pkg/sql/colexec/stats.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeWBkFBNmjK9ETz7fX:-MKeWBkFBNmjK9ETz7fY:briwutn) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L76)):*
> ```Go
> 
> // initVectorizedStatsCollectorBase initializes the common fields
> // of VectorizedStatsCollectorBase for all VectorizedStatsCollectors
> ```

nit: missing period.d
___
*[pkg/sql/colexec/stats.go, line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeWgevBXokBbqCXisz:-MKeWgevBXokBbqCXit-:b-spji2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L194)):*
> ```Go
> 
> // finalizeStats records the stats for the VectorizedStatsCollectorBase and
> // network latency. It also adjusts the time recorded to be the Inbox
> ```

How does the "adjustment" work? I don't think I see it. I guess it is a TODO item?
___
*[pkg/sql/colflow/vectorized_flow.go, line 376 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeY96oBwrSj76ZbPdV:-MKeY96oBwrSj76ZbPdW:b-apwln7) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colflow/vectorized_flow.go#L376)):*
> ```Go
> // colexec.NetworkVectorizedStatsCollector that wraps op.
> func (s *vectorizedFlowCreator) wrapWithNetworkVectorizedStatsCollector(
> 	op colexecbase.Operator,
> ```

nit: I think `op` and `networkReader` currently is always the same `colrpc.Inbox`, right? We could probably remove one of the arguments then.


<!-- Sent from Reviewable.io -->

2020-10-27 21:33 UTC, cathymw reviewed
Squashed commits because reordering the commits resulted in a bunch of merge conflicts and separating the changes was quite complicated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MKfxNVk1bMnDVhpM2aF:b-wfh2ao)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/server/server_sql.go, line 67 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdP0i49f_XPDuYpkES:-MKehvhFESElyglw4yL4:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/server_sql.go#L67)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think these imports should stay where they were. Have you enabled `crlfmt` in goland? That should take care of it for you automatically on save.
</blockquote></details>

Done. 
___
*[pkg/server/serverpb/status.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPEbg0X4gnYf3joFy:-MKei6QS037jzCOK8HE4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L81)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Instead of `outbox/inbox`, you should make this more general, with for example `originNodeID` and `targetNodeID`.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 83 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPANSDsady9VddpgY:-MKeiAMa9S66nVXZ8zFu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L83)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `context` is usually the first argument.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPWhA2ssO4-LnCsFg:-MKemIFw3ohx24uIZQ9O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L85)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

extract this `time.Second` into a constant and refer to it in the comment so it doesn't become stale if it is changed. Also, maybe we can make this 5*time.Second, not sure we get anything from pinging these nodes every second.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPPdH4D6rg6-rpQRa:-MKemL0g3UJ8uhc2b_aE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L86)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: capitalize and period.
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPxhT9f78XFvM-MVX:-MKev1nu7iYBTH5FyhJj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L88)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you avoid excessive indentation by doing `if err != nil { do something? }` so that your `err == nil` is implicit and the block doesn't need to be indented. In general, it's nice to indent only the smallest blocks. For example, you can change your code to be:
```
if time.Since(lastUpdated) <= time.Second {
     return lg.latencyMap
}
// Implicit else, update with result from Nodes
lg.latencyMap.update()
if err != nil {
    return something
}
return updated lg.latencyMap
```
</blockquote></details>

Done.
___
*[pkg/server/serverpb/status.go, line 106 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdPTAk3UJaLCgb_SIE:-MKemODxBXUQ5zwNDno-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/server/serverpb/status.go#L106)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

leftover
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdQlcv3Yp46r30YcfG:-MKevEbXAS9Z7xuLjWMf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/distsql_running.go#L47)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

same thing re imports
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats.go, line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeW2xr1axghs2v-RAu:-MKevNb26iylBwc-U1Rr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L65)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: `s/InbocVectorizedStats/VectorizedInboxStats/`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeWBkFBNmjK9ETz7fX:-MKevQzeCGQ4no9Yk84e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L76)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: missing period.d
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats.go, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdT8m_AxQF_pxg36Gn:-MKew-GF3sGQ4sgbDxaN:b-gv4d2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L122)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

All the nil monitors seem to indicate that it'd be nice to also have a memory/disk focused stat collector as well as one for IO operators (i.e. wherever we need to write `if vsc.IO`) but we can leave that for another PR.
</blockquote></details>

Done. Left a TODO.
___
*[pkg/sql/colexec/stats.go, line 194 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKeWgevBXokBbqCXisz:-MKewJAo9UcACYiqAsst:b-px23di) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L194)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

How does the "adjustment" work? I don't think I see it. I guess it is a TODO item?
</blockquote></details>

Done. Oops, I forgot to take out this comment when I removed deserialization time. Left a TODO in `execpb/stats.go` for inbox to collect its own deserialization time.
___
*[pkg/sql/colexec/stats.go, line 201 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKdRHvu6WZMRWfHKAbA:-MKex4qF4iEb1VFa8D2L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/264d4183b9ccf721fb377152e3d72272e666ea7e/pkg/sql/colexec/stats.go#L201)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you make this a private method on the vectorized stats collector base since this needs a couple of inputs that are already fields of the struct?
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 593 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA33N-7Bv-ix4nnDQ6:-MKfKOD2COPDQ_hxHpw3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/colflow/vectorized_flow.go#L593)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués [...]

2020-10-28 10:03 UTC, asubiotto requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/server/serverpb/status.go, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKicRIg7bqdjZ1lVdl_:-MKicRIg7bqdjZ1lVdla:b2k7pa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aca24131f4861d408dca0256eb33e8bc44eb7e8/pkg/server/serverpb/status.go#L84)):*
> ```Go
> 	ctx context.Context, originNodeID roachpb.NodeID, targetNodeID roachpb.NodeID,
> ) int64 {
> 	if time.Since(lg.lastUpdatedTime) > updateThreshold {
> ```

As mentioned in the other comment, I would flip this conditional to avoid indenting the block inside the if:
```
if time.Since(lg.lastUpdatedTime) < updateThreshold {
    return lg.latencyMap[originNodeID][targetNodeID]
}
<other code>
```
___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKidUmTENy6crhDPs4l:b3hrb05) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

Done. Commits were squashed because it would have been quite complicated to separate the changes
</blockquote></details>

I've been thinking about this and I wonder: maybe we should just change the `StreamEndpointSpec` protobuf that the inbox has access to to include the node ID it's receiving data from? We could avoid modifying the outbox to send this special message. I believe all it would take is changing `PopulateEndpoints` in `pkg/sql/physicalplan/physical_plan.go` to populate the new protobuf field with `p1.Node`, which is the node the outbox will be on.


<!-- Sent from Reviewable.io -->

2020-10-28 23:48 UTC, cathymw reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/server/serverpb/status.go, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKicRIg7bqdjZ1lVdl_:-MKjlwcd5XKW8MgWS7mP:b-gvcvae) ([raw file](https://github.com/cockroachdb/cockroach/blob/6aca24131f4861d408dca0256eb33e8bc44eb7e8/pkg/server/serverpb/status.go#L84)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

As mentioned in the other comment, I would flip this conditional to avoid indenting the block inside the if:
```
if time.Since(lg.lastUpdatedTime) < updateThreshold {
    return lg.latencyMap[originNodeID][targetNodeID]
}
<other code>
```
</blockquote></details>

Done. Oops, fixed it!
___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKlVnfh3zIJKytdfJBj:b-9nsrt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I've been thinking about this and I wonder: maybe we should just change the `StreamEndpointSpec` protobuf that the inbox has access to to include the node ID it's receiving data from? We could avoid modifying the outbox to send this special message. I believe all it would take is changing `PopulateEndpoints` in `pkg/sql/physicalplan/physical_plan.go` to populate the new protobuf field with `p1.Node`, which is the node the outbox will be on.
</blockquote></details>

Added some WIP changes as a second commit that I will squash/delete later. I tried to have the inbox access both the origin node id and target node id, like you suggested, and passing in the latency when an inbox is created. But, 
when I tested it in roachprod, the node ids seem to not get set properly (i.e. accessing the ids through `StreamEndpointSpec` always gives 0 as both values). I double-checked that in the `PopulateEndpoints` function they were getting set to non-zero values. Not really sure right now what/where the missing link is


<!-- Sent from Reviewable.io -->

2020-10-29 09:42 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKni5IB28eMklusHrsL:b-7j2qpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
> But, when I tested in it roachprod

What tests are you running? And where are you accessing the `StreamEndpointSpec`? When setting up the inputs?

Hmm, taking a quick look at the code it looks like this:
```
		endpoint := execinfrapb.StreamEndpointSpec{StreamID: execinfrapb.StreamID(sIdx)}
		if p1.Node == p2.Node {
			endpoint.Type = execinfrapb.StreamEndpointSpec_LOCAL
		} else {
			endpoint.Type = execinfrapb.StreamEndpointSpec_REMOTE
		}
		p2.Spec.Input[s.DestInput].Streams = append(p2.Spec.Input[s.DestInput].Streams, endpoint)
		if endpoint.Type == execinfrapb.StreamEndpointSpec_REMOTE {
			if !p.remotePlan {
				p.remotePlan = true
			}
			endpoint.TargetNodeID = p2.Node
		}
```
So what we're doing is appending to `p2` input spec **before** setting the `TargetNodeID`. I think what's most likely happening is that since the endpoint spec is a value, appending to the streams causes a copy when the node IDs are unset, which results in a node ID of zero even if they're set later on (because you're setting it on the original copy). I would just populate the node IDs before appending and see if that makes a difference.


<!-- Sent from Reviewable.io -->

2020-10-29 20:27 UTC, cathymw reviewed
Thanks for the reviews so far! Ready for another look! Following Alfonso's suggestion, I updated the commit so that the inbox now has access to the latency directly, rather than having the outbox access the latency and sending that information to the inbox.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MKq0rbH2KAfk9L-qOLa:bbnosfq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/execinfrapb/data.proto, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MKA0zDZ3aMHjj-gHcKy:-MKovN2q-c7F2GI-5352:b27cgf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aed4a8e0603fb7341d19cf60310e4d1917124641/pkg/sql/execinfrapb/data.proto#L246)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> But, when I tested in it roachprod

What tests are you running? And where are you accessing the `StreamEndpointSpec`? When setting up the inputs?

Hmm, taking a quick look at the code it looks like this:
```
		endpoint := execinfrapb.StreamEndpointSpec{StreamID: execinfrapb.StreamID(sIdx)}
		if p1.Node == p2.Node {
			endpoint.Type = execinfrapb.StreamEndpointSpec_LOCAL
		} else {
			endpoint.Type = execinfrapb.StreamEndpointSpec_REMOTE
		}
		p2.Spec.Input[s.DestInput].Streams = append(p2.Spec.Input[s.DestInput].Streams, endpoint)
		if endpoint.Type == execinfrapb.StreamEndpointSpec_REMOTE {
			if !p.remotePlan {
				p.remotePlan = true
			}
			endpoint.TargetNodeID = p2.Node
		}
```
So what we're doing is appending to `p2` input spec **before** setting the `TargetNodeID`. I think what's most likely happening is that since the endpoint spec is a value, appending to the streams causes a copy when the node IDs are unset, which results in a node ID of zero even if they're set later on (because you're setting it on the original copy). I would just populate the node IDs before appending and see if that makes a difference.
</blockquote></details>

OH, you are so right. Putting the append line after the node IDs are set fixed it. 


<!-- Sent from Reviewable.io -->

2020-11-02 10:39 UTC, asubiotto requested changes
Looking good, I think this is nearly read to merge.

> Reviewed 21 of 21 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-ML7XZ4VBwrQIXMtJ135:b-whkyog)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-ML7VrhN0wdET03d8Rk4:-ML7VrhN0wdET03d8Rk5:b-fi16nk) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c6a2b3c9a9021e1cef77afcb87baf06441c872/pkg/sql/colexec/stats.go#L41)):*
> ```Go
> type VectorizedStatsCollector interface {
> 	OutputStats(ctx context.Context, flowID string, deterministicStats bool)
> 	getElapsedTime() time.Duration
> ```

I think it would be cleaner to put this into a separate interface.
___
*[pkg/sql/colflow/vectorized_flow.go, line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-ML7WxvDCfdEZekdJfEu:-ML7WxvDCfdEZekdJfEv:bwjdntw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c6a2b3c9a9021e1cef77afcb87baf06441c872/pkg/sql/colflow/vectorized_flow.go#L447)):*
> ```Go
> 		toClose []colexecbase.Closer,
> 	) (*colrpc.Outbox, error)
> 	newInbox(ctx context.Context, allocator *colmem.Allocator, typs []*types.T, streamID execinfrapb.StreamID, latency int64) (*colrpc.Inbox, error)
> ```

It feels wrong to add `latency` to the constructor, given all the callsites that need to be changed to pass in a 0 latency because they're not interested. How about adding a method to the inbox that does something like:
```
func (i *Inbox) enableLatencyReport(latency int64) {
    i.latency = latency
}
```
Or something (maybe you can find a better name). This will avoid having to add a parameter to the constructor that is only used in a small number of cases.


<!-- Sent from Reviewable.io -->

2020-11-02 16:46 UTC, cathymw reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-ML7WxvDCfdEZekdJfEu:-ML8p7WUA-kdOD879mKq:b-vsjf50) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c6a2b3c9a9021e1cef77afcb87baf06441c872/pkg/sql/colflow/vectorized_flow.go#L447)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It feels wrong to add `latency` to the constructor, given all the callsites that need to be changed to pass in a 0 latency because they're not interested. How about adding a method to the inbox that does something like:
```
func (i *Inbox) enableLatencyReport(latency int64) {
    i.latency = latency
}
```
Or something (maybe you can find a better name). This will avoid having to add a parameter to the constructor that is only used in a small number of cases.
</blockquote></details>

I was actually thinking this morning that maybe it's a little overkill to set the latency in the inbox at all. Currently, the latency is set in the inbox, and then the inbox is passed as the `networkReader` into the `NetworkVectorizedStatsCollector` just so the stats collector can later get the latency from the inbox. I was thinking that since the vectorized flow has access to the latency, it can just directly set the latency stat when it creates the vectorized stats collector. What do you think?


<!-- Sent from Reviewable.io -->

2020-11-02 17:43 UTC, asubiotto commented
Sounds like a great idea.

2020-11-02 19:31 UTC, cathymw reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 41 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-ML7VrhN0wdET03d8Rk4:-ML9Qsf50xYyRYYaqa0c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c6a2b3c9a9021e1cef77afcb87baf06441c872/pkg/sql/colexec/stats.go#L41)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it would be cleaner to put this into a separate interface.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 447 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-ML7WxvDCfdEZekdJfEu:-ML9QxiL3jZ50Sv7SAYI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c6a2b3c9a9021e1cef77afcb87baf06441c872/pkg/sql/colflow/vectorized_flow.go#L447)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

I was actually thinking this morning that maybe it's a little overkill to set the latency in the inbox at all. Currently, the latency is set in the inbox, and then the inbox is passed as the `networkReader` into the `NetworkVectorizedStatsCollector` just so the stats collector can later get the latency from the inbox. I was thinking that since the vectorized flow has access to the latency, it can just directly set the latency stat when it creates the vectorized stats collector. What do you think?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-03 12:19 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 13 of 13 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-:-MLD211y92ARjiMDuIxE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MLD1dYV3pxWTCRJGh-C:-MLD1dYV3pxWTCRJGh-D:brk46nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6fddb9765472528b8a7de85d965fb3a628a6d68/pkg/sql/colexec/stats.go#L39)):*
> ```Go
> // ChildStatsCollector gives access to the stopwatches of a
> // VectorizedStatsCollector's childStatsCollectors.
> type ChildStatsCollector interface {
> ```

nit: can this be a private interface?


<!-- Sent from Reviewable.io -->

2020-11-03 16:49 UTC, cathymw reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55705)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/55705#-MLD1dYV3pxWTCRJGh-C:-MLE-U8i4VCUGZ_wuS0u:bxezuhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6fddb9765472528b8a7de85d965fb3a628a6d68/pkg/sql/colexec/stats.go#L39)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: can this be a private interface?
</blockquote></details>

I think this has to be public so that in can be used in `vectorized_flow.go` when the vectorized stats collectors are created.


<!-- Sent from Reviewable.io -->

2020-11-03 16:50 UTC, cathymw commented
TFTRs! 

bors r=asubiotto

2020-11-03 17:49 UTC, merged