roachprod: add availability zone and network disk type support to azure
cockroachdb/cockroach pull request #55775
Opened 2020-10-20 19:54 UTC by arulajmani

User facing change:
- New flag `--azure-availability-zone` lets the user supply which zone
a VM should be provisioned in.
- New flag `--azure-network-disk-type` lets the user choose which type
of network disk to use (ultra-disk, premium-ssd)

Previously, we didn't allow users to decide which availability zone a
VM was provisioned in. To achieve this, this patch adds support for
Network Security Groups. This was required as we had to update the
IP SKU from Basic (which is now deprecated) to Standard. By default,
this SKU blocks all inbound/outbound communication, which needed to be
overriden by creating network security rules that allow HTTPS/SSH/HTTP
connections. Network Security Groups are created under the resource
groups that manage VNets for a particular location the first time a
VNet is created.

Release note: None

2020-10-20 19:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55775)
<!-- Reviewable:end -->

2020-10-20 20:01 UTC, miretskiy requested changes

2020-10-20 20:01 UTC, miretskiy commented on pkg/cmd/roachprod/vm/azure/azure.go
> +	group, ok := p.mu.resourceGroups[name]
same question re concurrence.

2020-10-21 00:31 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miretskiy)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55775#-MK6Zy7eZ7drj-sHzGiN-r1-597:-MK7YT1K-qozj9LXt9hC:b-qaam04) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56eea0c8f5ece06908b7040c199d756a25c7c32/pkg/cmd/roachprod/vm/azure/azure.go#L597)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Should we keep default == premium-disk? Like it was before when not using SSD?
</blockquote></details>

That is still the default behaviour when the user says --local-ssd = false (see the changes in `flags.go`). This is triggered if the user provides a value for `--azure-network-disk-type` that isn't premium-disk or ultra-disk -- in which case it makes sense to return an error to the user instead of swallowing the erroneous value and creating a premium disk underneath the hood.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 679 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55775#-MK6Zy7eZ7drj-sHzGiN-r1-679:-MK7Z8b56IFJ0NFL4JdT:bjaqyzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56eea0c8f5ece06908b7040c199d756a25c7c32/pkg/cmd/roachprod/vm/azure/azure.go#L679)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Does this function get call from multiple threads? Looks like it is...
But then we release the lock, and proceed to create the group.. So, wouldn't we wind up creating multipole groups?
Should this be a `defer p.mu.Unlock()`?
</blockquote></details>

I'm honestly not sure about the flow of the code here and where/how this function can be called from multiple goroutines tbh. I just followed the pattern of the existing code in `getResourceGroup`, which didn't wrap the API calls to the client inside the mutex. Do you want me to switch it? 


<!-- Sent from Reviewable.io -->

2020-10-21 17:47 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55775)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @miretskiy)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55775#-MK6Zy7eZ7drj-sHzGiN-r1-597:-MKBGTo61LrF1pcuOQOT:bb7cwne) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56eea0c8f5ece06908b7040c199d756a25c7c32/pkg/cmd/roachprod/vm/azure/azure.go#L597)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

That is still the default behaviour when the user says --local-ssd = false (see the changes in `flags.go`). This is triggered if the user provides a value for `--azure-network-disk-type` that isn't premium-disk or ultra-disk -- in which case it makes sense to return an error to the user instead of swallowing the erroneous value and creating a premium disk underneath the hood.
</blockquote></details>

ack.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 679 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55775#-MK6Zy7eZ7drj-sHzGiN-r1-679:-MKBGWfPCHbl5ENhdWcW:bq0ncok) ([raw file](https://github.com/cockroachdb/cockroach/blob/d56eea0c8f5ece06908b7040c199d756a25c7c32/pkg/cmd/roachprod/vm/azure/azure.go#L679)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm honestly not sure about the flow of the code here and where/how this function can be called from multiple goroutines tbh. I just followed the pattern of the existing code in `getResourceGroup`, which didn't wrap the API calls to the client inside the mutex. Do you want me to switch it? 
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2020-10-21 18:00 UTC, arulajmani commented
TFTR!

bors r=miretskiy

2020-10-21 19:01 UTC, merged