logictest: add multiregion configuration
cockroachdb/cockroach pull request #55784
Opened 2020-10-20 21:08 UTC by otan

Add a logictest configuration that has three regions, with three
nodes in each AZ:
* test (azs test-az-1, test-az-2)
* test2

Release note: None

2020-10-20 21:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55784)
<!-- Reviewable:end -->

2020-10-20 21:09 UTC, otan commented
can't seem to add @cockroachdb/multiregion as reviewers, but here's a CC.

2020-10-21 17:19 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/logictest/logic.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55784#-MKB9XSZD0f0gbbfH-uu:-MKB9XSZD0f0gbbfH-uv:b-hvalns) ([raw file](https://github.com/cockroachdb/cockroach/blob/facba9ddb99a4c788e7b5800a68be13b2c975a57/pkg/sql/logictest/logic.go#L642)):*
> ```Go
> 	{
> 		name:              "multiregion",
> 		numNodes:          9,
> ```

Seems like it could be error prone to have the map below depend on this size.  Is there some way we can generate regions (and az's) below to match whatever number is up here?  I'm worried that someone will change this number, say to 15, and we'll have a bunch of nodes without localities set.
___
*[pkg/sql/logictest/logic.go, line 647 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55784#-MKB78se7bZ5d9Ec6m5I:-MKB78se7bZ5d9Ec6m5J:b-nqvfx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/facba9ddb99a4c788e7b5800a68be13b2c975a57/pkg/sql/logictest/logic.go#L647)):*
> ```Go
> 			1: {
> 				Tiers: []roachpb.Tier{
> 					{Key: "region", Value: "test"},
> ```

I'd think a more realistic setup would be to have 3 nodes in each region, with three different availability zones.  Also, I'm thinking it might be best to have the regions be "-" delimited and the az's be either numeric or chars to match what AWS, GCP and Azure do.


<!-- Sent from Reviewable.io -->

2020-10-21 18:33 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/logictest/logic.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55784#-MKB9XSZD0f0gbbfH-uu:-MKBOlyO8ncrcOLqZyrx:bs29j0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/facba9ddb99a4c788e7b5800a68be13b2c975a57/pkg/sql/logictest/logic.go#L642)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Seems like it could be error prone to have the map below depend on this size.  Is there some way we can generate regions (and az's) below to match whatever number is up here?  I'm worried that someone will change this number, say to 15, and we'll have a bunch of nodes without localities set.
</blockquote></details>

i can deliberately rename to `multiregion-9node` to avoid this issue. i can also throw an assert.
___
*[pkg/sql/logictest/logic.go, line 647 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55784#-MKB78se7bZ5d9Ec6m5I:-MKBOuaxA9M1q37mu8yp:b-v5visi) ([raw file](https://github.com/cockroachdb/cockroach/blob/facba9ddb99a4c788e7b5800a68be13b2c975a57/pkg/sql/logictest/logic.go#L647)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'd think a more realistic setup would be to have 3 nodes in each region, with three different availability zones.  Also, I'm thinking it might be best to have the regions be "-" delimited and the az's be either numeric or chars to match what AWS, GCP and Azure do.
</blockquote></details>

works for me. the spec had the space.


<!-- Sent from Reviewable.io -->

2020-10-21 19:59 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/logictest/logic.go, line 642 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55784#-MKB9XSZD0f0gbbfH-uu:-MKBjY6i7w1cb9vKAiY7:b-f63vaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/facba9ddb99a4c788e7b5800a68be13b2c975a57/pkg/sql/logictest/logic.go#L642)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i can deliberately rename to `multiregion-9node` to avoid this issue. i can also throw an assert.
</blockquote></details>

Both of those sound good.


<!-- Sent from Reviewable.io -->

2020-10-21 21:27 UTC, ajstorm reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)



<!-- Sent from Reviewable.io -->

2020-10-21 21:28 UTC, ajstorm approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55784)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-10-21 21:29 UTC, ajstorm commented
LGTM

2020-10-21 22:12 UTC, otan commented
thanks!

bors r=ajstorm

2020-10-21 23:33 UTC, merged