Increases the number of types supported for the histogram
cockroachdb/cockroach pull request #55797
Opened 2020-10-21 05:44 UTC by ArjunM98

Previously, non-numeric types like strings/uuid/inet family when filtered would reduce their range by half.
Now we can estimate the range of these non-numeric types by leveraging their byte format.
Additionally, time/timetz data types were also added following previous range estimation methodology.

Release note (performance improvement): Increased range calculation support for more data types in histogram

2020-10-21 05:44 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/55797)
<!-- Reviewable:end -->

2020-10-21 13:08 UTC, rytaft commented
Hi @arjunm98 -- I see that you still have WIP in the description of this PR. Is it ready for review?





<!-- Sent from Reviewable.io -->

2020-10-21 16:05 UTC, ArjunM98 commented
Hi @rytaft, 

I believe so! I still need to add a few end-to-end tests, but my core logic for the additional data types have been unit-tested. I did have a few additional questions for the end-to-end testing: 

1) How do I regenerate the output in files like: [pkg/sql/opt/memo/testdata/stats/select](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/memo/testdata/stats/select). `make testoptlogic` only runs the tests in opt/exec, and I couldn't find any additional commands in the makefile.

2) How do I go about checking the performance impact of this change, are there any tests which highlight this? I noticed in #48580 you checked estimates regenerated in files like: [pkg/sql/opt/memo/testdata/stats_quality/tpch/q01](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/memo/testdata/stats_quality/tpch/q01), should I look into these files as well? Any pointers about this would help a lot. 

Some comments about my current implementation: 

1) After the addition of the new data types in this PR, the only ones not explicitly handled in the histogram filtering code include: 

- Box2D
- Geography
- Geometry
- Interval
- Tuple
- Array
- CollatedString
- BitArray
- Oid
- Enum

Let me know if you'd like me to look into these datatypes as well for this PR (these can be found in `EncodeTableKey`).

2020-10-26 22:05 UTC, rytaft reviewed
Cool! This is impressive stuff! My main critique at the moment is that it's really hard to understand the high level picture of what your code is doing and why. I think you need a big comment somewhere that explains the big picture. For example, your code is doing some manipulation of the byte strings where it strips out the first few bytes or half bytes. Why is that necessary? What could go wrong if you don't do that?

Also, I think this code should work independently of however each type is encoded. Most of the really low-level stuff that's happening in your code should be encapsulated in functions inside the packages where the encoding is defined. 

If you need to reference specific constant byte strings, they should be assigned to a constant with a self-documenting name.

I haven't spent as much time thinking about this problem as you have, but my hunch is that getting down into the nitty-gritty details of the byte encodings should not be necessary. The encodings are already designed so that lexicographically sorting the encoded keys matches the ordering of the unencoded datums. What happens if you ignore the encodings altogether? If what I'm suggesting is not possible, the comments in your code should clearly explain why not and include some examples.

[nit] commit and PR message should use "increase" instead of "increases" (from the [commit messages guidelines](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages): "(recommended) Use the imperative mood in the subject line, but not in the body").

[nit] it's still difficult to understand the change based on the release note. Instead of saying "increased the number of types supported", I'd say something like, "improved the accuracy of histogram calculations for the following types:", and list the types.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MKac0bB6I2EK2KN1pqt:bq4rr8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 1983 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKaen-m0EmKCsTpDrd_:-MKaen-m0EmKCsTpDrda:bautbnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/memo/testdata/stats/select#L1983)):*
> ```
>       └── created:3 = '2020-04-11 06:25:41+00:00' [type=bool, outer=(3), constraints=(/3: [/'2020-04-11 06:25:41+00:00' - /'2020-04-11 06:25:41+00:00']; tight), fd=()-->(3)]
> 
> # Make sure that using a histogram produces correct stats with range calculations for non-numeric types
> ```

[nit] comments should be at most 80 columns wide and end with a period.
___
*[pkg/sql/opt/props/histogram.go, line 749 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKafloS7_awJmaiZEdx:-MKafloS7_awJmaiZEdy:b-4prgly) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L749)):*
> ```Go
> 	) (rangeBefore, rangeAfter float64, ok bool) {
> 
> 		// Utilizes an array to simplify number of repetitive calls
> ```

[nit] comments should end in a period. (here and below)
___
*[pkg/sql/opt/props/histogram.go, line 763 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKahDOJ-cScdUu9XbEk:-MKahDOJ-cScdUu9XbEl:b1n3yjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L763)):*
> ```Go
> 
> 		if lowerBoundBefore.ResolvedType().Family() == types.INetFamily {
> 			// check the format of the INetFamily - ie. IPV4 vs. IPV6
> ```

The stuff here seems way too low-level for this function. Can you add some helper functions in `util/ipaddr/ipaddr.go` that you can call from here so this function doesn't need to know so much about the specific encoding used for IP addresses?
___
*[pkg/sql/opt/props/histogram.go, line 795 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKakSlvBmYWhdAa8MgJ:-MKakSlvBmYWhdAa8MgK:bvbiesc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L795)):*
> ```Go
> 		}
> 
> 		// Remove common prefix and fix length to 4 bytes
> ```

This comment should have a lot more info about what this code is doing and why
___
*[pkg/sql/opt/props/histogram.go, line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKaqqda-OcqprNdXLCM:-MKaqqda-OcqprNdXLCN:bup7wd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L851)):*
> ```Go
> 
> // getCommonPrefix returns the first index where the 4 byte arrays each contain a different value
> // and sets maskUpperByte = True, if the upper 4 bits pointed to by index are the same between all arrays
> ```

[nit] comments should be at most 80 columns wide
___
*[pkg/sql/opt/props/histogram.go, line 857 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKajER61i-IDJa3dTjz:-MKajER61i-IDJa3dTk-:b5q7eo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L857)):*
> ```Go
> // 	[102 111 111]
> //	[98  97  114]
> //  [98  97  122  114]
> ```

the formatting is a bit strange -- can you align these arrays?
___
*[pkg/sql/opt/props/histogram.go, line 860 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKak45iDtwS326ZW98v:-MKak45iDtwS326ZW98w:b-c5m27b) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L860)):*
> ```Go
> //
> // The expected output will be: ind = 0, maskUpperByte = True
> func getCommonPrefix(byteArr1, byteArr2, byteArr3, byteArr4 []byte) (maskUpperByte bool, ind int) {
> ```

Is there any way you can treat these 4 arguments as a single slice of type `[][]byte`?
___
*[pkg/sql/opt/props/histogram.go, line 888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKajRRz9bid0WP-iEv6:-MKajRRz9bid0WP-iEv7:bup7wd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L888)):*
> ```Go
> 
> // fixLenRemovePrefix returns a byte array of size fixLen starting from ind in the original byteArray
> // if maskUpperByte = True, a byte array of size fixLen starting from the lower 4 bits of ind is returned
> ```

[nit] comments should be at most 80 columns wide
___
*[pkg/sql/opt/props/histogram.go, line 916 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKalcD285cYm2B3Diwd:-MKalcD285cYm2B3Diwe:b4qup08) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L916)):*
> ```Go
> 		// 2. If markUpperByte is set, we need to bit shift byte array 4 bits to the right
> 		// 3. Copy byteArr into byteArrFix normally
> 		if byteArr[ind] == 0x00 && (byteArr[ind+1] == 0xff || byteArr[ind+1] == 0x01) {
> ```

Ideally you should call some function from another package that will indicate whether a particular byte is an escape code. You shouldn't need to know what the encodings are here.
___
*[pkg/sql/opt/props/histogram.go, line 946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKas3rx8vCZNboGNe-f:-MKas3rx8vCZNboGNe-g:b7he5r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props/histogram.go#L946)):*
> ```Go
> }
> 
> // subtractByteArr subtracts byteArr1 from byteArr2
> ```

That doesn't match the natural order I would expect. I would expect `subtract(a, b) = a - b`
___
*[pkg/sql/opt/props/histogram.go, line 955 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKasaex9AXFLru0s-jG:-MKasaex9AXFLru0s-jH:bgvtd0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/props [...]

2020-10-27 19:27 UTC, ArjunM98 commented
Hi @rytaft, 

I had a quick clarifying question. When you mention "Also, I think this code should work independently of however each type is encoded", are you referring to the fact that I should try and implement this so that I don't separate numeric and non-numeric types? Or if I shouldn't try and make distinctions within non-numeric types themselves (ie. don't separate string/uuid/inet family)? 

- The reason I separated numeric and non-numeric types is because since we can already calculate the range for numeric types without encoding them first, I thought it would be more efficient to leave it as is. If you'd like it to be uniform, I can definitely look into this. However, in this case I will still need to handle some types differently, ie. Integers. These are encoded using variable length encoding, so the prefix between numbers can be different (the length of the encoding is embedded within the prefix itself), and hence needs to be stripped when calculating the range of the bounds.

- Within non-numeric types, you are correct that I don't need to worry about the prefix for majority of the encodings. However, for the inet family, when the IPV4 and IPV6 formats are mixed, I need to specifically isolate the IPV4 format embedded within the IPV6 format. What I mean by this can be highlighted in the example below: 

When IPV6 and IPV4 formats are mixed, IPV6 is constrained to the lower 4 bytes (the size of the IPV4 format). 

```
196.140.90.20 (IPV4) can be represented as:
- 0:0:0:0:0:0:c48c:5a14 (IPV6) or
- 0:0:0:0:0:ffff:c48c:5a14 (IPV6)

This range can be defined as: [/0:0:0:0:0:0:c48c:5a14 - /198.180.50.30]
```

To properly find the range between these 2 different types of formats, I must compare the lower 4 bytes of IPV6 to the 4 bytes of IPV4. This means I need to strip the leading 0's/f's so that I'm not comparing the leading 0's in IPV6 to the address of IPV4. 

```
I need to compare: c48c:5a14 (196.140.90.20) to 196.140.90.20
ie. 196.140.90.20 - c48c:5a14 (196.140.90.20)
```

Is this style of thinking correct? 

I'll also work on adding better comments and removing any low-level byte manipulations I'm doing within `histogram.go`. Thank you so much for all the feedback!

2020-10-28 16:36 UTC, rytaft reviewed
Hi @arjunm98,

> I had a quick clarifying question. When you mention "Also, I think this code should work independently of however each type is encoded", are you referring to the fact that I should try and implement this so that I don't separate numeric and non-numeric types? Or if I shouldn't try and make distinctions within non-numeric types themselves (ie. don't separate string/uuid/inet family)?

I think it's fine to keep the distinction between numeric and non-numeric types for now, since we already have an implementation that works for numeric types. Maybe in the future it will make sense to treat them all the same, but I don't see a strong reason to do that in this PR.

Regarding all the special processing for INET: although '196.140.90.20' may be semantically equivalent to '0:0:0:0:0:0:c48c:5a14' and '0:0:0:0:0:ffff:c48c:5a14', CRDB sorts IPv4 addresses before IPv6 (see https://www.cockroachlabs.com/docs/stable/inet.html).  You can validate this if you open a SQL shell:

```
demo@127.0.0.1:63245/movr> create table ip (addr inet);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:63245/movr> insert into ip values ('196.140.90.20'), ('198.180.50.30'), ('0:0:0:0:0:0:c48c:5a14'), ('0:0:0:0:0:ffff:c48c:5a14');
INSERT 4

Time: 4ms total (execution 3ms / network 0ms)

demo@127.0.0.1:63245/movr> select * from ip order by addr;
          addr
------------------------
  196.140.90.20
  198.180.50.30
  ::c48c:5a14
  ::ffff:196.140.90.20
(4 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

Therefore I think it's actually incorrect to do the kind of processing you are suggesting. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MKk-Xy91z6vpGq5_6Do:b-e58jjb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98)



<!-- Sent from Reviewable.io -->

2020-11-09 02:11 UTC, ArjunM98 commented
TFTR! 

I made all the necessary changes you outlined. This should be ready for another look!

2020-11-11 19:23 UTC, rytaft reviewed
Nice work! This is looking much better.

Just a process suggestion: have you tried using Reviewable? You can access it with the big purple button near the top of the Conversation tab in the GitHub PR. That will allow you to easily see my comments inline, and respond "Done" to each suggestion as you've addressed it (or respond with something else if you disagree with the suggestion).

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MLsQUZXE_ERqBj24ekY:b-3hwo2f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98)

___
*[pkg/sql/opt/props/histogram.go, line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLs66o29C9pTWiw8fTi:-MLs66o33-q4gBlig35x:b-d22l2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L671)):*
> ```Go
> // (CRDB key representation) to find their range. As we do need a lot of
> // precision in our range estimate, we can remove the common prefix between
> // bucket/span bounds, and limit the byte array to 4 bytes. This also simplifies
> ```

Why 4 bytes? In the example below it doesn't look like you're limiting it to 4 bytes...

edit: oh I see -- it's 4 bytes since you're casting it to a uint32. Might as well at least do 8 bytes and cast to uint64... either way, you should update the comment to make that clear.

You should also include some test cases where `lowerBoundAfter` and `upperBoundAfter` have the same first 4 or 8 bytes, but differ after that, so that `rangeAfter` appears to be 0. You should make sure that we're returning sane results in that case.
___
*[pkg/sql/opt/props/histogram.go, line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLs6Y1l6ZbRSIvC5TNC:-MLs6Y1mB7vxLi7_KEqe:b-rt890p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L680)):*
> ```Go
> //   bear    := [18 98 101 97  114 0   1          ] => [101 97  114 0   0  ]
> //   bobcat  := [18 98 111 98  99  97  116 0   1  ] => [111 98  99  97  116]
> //   bluejay := [18 98 108 117 101 106 97  121 0 1] => [108 117 101 106 97 ]
> ```

[nit] I'd reorder these so that they are sorted lexicographically (i.e., bluejay and boar before bobcat). Makes it easier to see how the bytes correspond to the string.
___
*[pkg/sql/opt/props/histogram.go, line 687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsETbyAoxVL307zToY:-MLsETbz9npNUEkIUr5g:blko99a) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L687)):*
> ```Go
> //
> //   rangeBefore := bobcat [111 98  99  97  116] - bear    [101 97  114 0   0 ]
> //   rangeAfter  := boar   [111 97  114 0   0  ] - bluejay [108 117 101 106 97]
> ```

nice example! I'd also go a step further and actually show what the resulting numeric ranges are (or at least explain how they are calculated)
___
*[pkg/sql/opt/props/histogram.go, line 813 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsQEHmA6FK9CPPXekm:-MLsQEHmA6FK9CPPXekn:b-la05bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L813)):*
> ```Go
> 			if ipv4Addr && ipv6Addr {
> 				for i := range boundArr {
> 					boundArrByte[i] = ipaddr.PadIPv4Encoding(boundArrByte[i])
> ```

after all this padding, won't the important bytes get cut off when you truncate to 4 bytes?
___
*[pkg/sql/opt/props/histogram.go, line 825 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsGC3I-HzE0nBrf5Ln:-MLsGC3I-HzE0nBrf5Lo:b5c86v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L825)):*
> ```Go
> 
> 		rngBefore = float64(binary.BigEndian.Uint32(boundArrByte[1]) - binary.BigEndian.Uint32(boundArrByte[0]))
> 		rngAfter = float64(binary.BigEndian.Uint32(boundArrByte[3]) - binary.BigEndian.Uint32(boundArrByte[2]))
> ```

[nit] lines of code should fit within 100 columns
___
*[pkg/sql/opt/props/histogram.go, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsAxWD1YHElOeZdd7n:-MLsAxWD1YHElOeZdd7o:betjvau) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L868)):*
> ```Go
> // across all byte arrays in byteArr.
> func getCommonPrefix(byteArr [][]byte) int {
> ```

To prevent anyone from using this function incorrectly, you should check that `len(byteArr) > 0`, and if not, panic with `panic(errors.AssertionFailedf("byteArr must have at least one element"))` (feel free to change the error message, but should be something similar). Also mention in the function comment that `byteArr` must have at least one element.
___
*[pkg/sql/opt/props/histogram.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsI6Yf3Q_BO1hAO0T9:-MLsI6Yf3Q_BO1hAO0TA:b-qltrqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L872)):*
> ```Go
> 	currIndMatching := func(ind int) bool {
> 		for i := 1; i < len(byteArr); i++ {
> 			if ind < len(byteArr[0]) && ind < len(byteArr[i]) && byteArr[0][ind] != byteArr[i][ind] {
> ```

shouldn't this function return false if `ind < len(byteArr[0]) && ind < len(byteArr[i])` is false?

edit: oh I see, you've added another function to do that. That seems like overkill -- why not just do it in one function?
___
*[pkg/sql/opt/props/histogram.go, line 880 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsIle50QJebn9OF8M7:-MLsIle60ovVehTVxwUg:b1351ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L880)):*
> ```Go
> 
> 	// checks if the current index is within the bounds of all byte arrays.
> 	curIndSmaller := func(ind int) bool {
> ```

As I mentioned above, this function seems like overkill. You're already checking the bounds in the function above, so why not just combine the logic there?
___
*[pkg/sql/opt/props/histogram.go, line 882 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsIiqWBiFTcgvb0wYc:-MLsIiqWBiFTcgvb0wYd:bkr32ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L882)):*
> ```Go
> 	curIndSmaller := func(ind int) bool {
> 		for i := 0; i < len(byteArr); i++ {
> 			if ind > len(byteArr[i]) {
> ```

shouldn't this be `>=`?
___
*[pkg/sql/opt/props/histogram.go, line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsMZRZ-DUORIJfdNMI:-MLsMZRZ-DUORIJfdNMJ:b-cd0rfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L904)):*
> ```Go
> 	// 1. ind > len(byteArr).
> 	// 2. len(byteArr) < fixLen and needs to be zero extended.
> 	byteArrFix := make([]byte, fixLen)
> ```

I think you can avoid allocating a new array if the existing slice has length at least `fixLen+ind`, and in that case return `byteArr[ind:fixLen+ind]`
___
*[pkg/sql/opt/props/histogram.go, line 907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsNV4kAdC310EaFLnt:-MLsNV4kAdC310EaFLnu:b16wjdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L907)):*
> ```Go
> 
> 	// Copy over values from byteArr starting at ind skipping all escape based
> 	// bytes.
> ```

why are you skipping the escape chars? that seems unnecessarily complicated and possibly incorrect
___
*[pkg/sql/opt/props/histogram.go, line 908 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsNgJpB9yHeyQUeih3:-MLsNgJpB9yHeyQUeih4:b-jokz9y) ([raw file](https://github.com/cockroachdb/cockro [...]

2021-01-04 15:33 UTC, rytaft commented
Hey @arjunm98 -- any chance you'll be able to wrap up this PR some time soon? I think it's really close to being done and it would be awesome to include in our next release. If it's easier, you could split it into two PRs (e.g., the IP address change seems a bit complex so you could focus on the other types first).





<!-- Sent from Reviewable.io -->

2021-01-06 04:19 UTC, ArjunM98 reviewed
Hi @rytaft, really sorry about the delay! I'm still working through your comments. However, I left a few questions I had below. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MQKtXwCAoVD6j5QZzXy:b-fzkfvj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98 and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 813 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsQEHmA6FK9CPPXekm:-MQKqFtA9kzbmJqngqXB:bkajbn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L813)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

after all this padding, won't the important bytes get cut off when you truncate to 4 bytes?
</blockquote></details>

Yes, the important bytes for IPV4 address will get cut off after I truncate. However, the reason for adding the padding was to align the address space for IPV4 and IPV6. I think subtracting the upper bytes of IPV6 with an IPV4 address underestimates the range difference between the two addresses.
___
*[pkg/sql/opt/props/histogram.go, line 907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsNV4kAdC310EaFLnt:-MQKeYlRDKOqzyecLikm:brkyekf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L907)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are you skipping the escape chars? that seems unnecessarily complicated and possibly incorrect
</blockquote></details>

I was skipping over the escape characters because if a null byte 0x00 is encountered within a string/uuid/ip address, an escape character 0xff is appended after the null byte. I believe when finding the rangeBefore & rangeAfter, leaving in this escape character would lead to an inaccurate estimation. 

For example given a UUID span like the following: 
```
[/bbbbbb00-bbbb-bbbb-bbbb-bbbbbbbbbbbb - /cccccccc-cccc-cccc-cccc-cccccccccccc]
```

The corresponding encoded byte representation of the following span is: 
```
\bbbbbb00 ... -> [187 187 187 0 255 ...],  \cccccccc ... [204 204 204 204 204 ...]

rangeAfter := [204 204 204 204 204 ...] - [187 187 187 0 255 ...]
```

The encoded byte representation above contains a 0xff byte after the 0x00 byte in the lower bound. Without skipping over the escape character (0xff), the resulting rangeAfter value would be lower compared to if we had skipped over it. The actual range difference in that span is: 

```
[187 187 187 0 187 ...],  \cccccccc ... [204 204 204 204 204 ...]

rangeAfter := [204 204 204 204 204 ...] - [187 187 187 0 187 ...]

```

Similarly, all byte representations of UUID/strings/IP addresses are terminated by /x00/x01. When we have different sized strings, the additional 0x01 will result in inaccurate estimations for rangeBefore and rangeAfter once again. Which is why I also skip the termination character (0x01), similar to above. 

This is why for your comments below, I had a for loop to skip over the escape/termination characters. Is this a correct way of thinking about it? Or do you think we can still include the escape characters in the byte array? 
___
*[pkg/sql/opt/props/histogram_test.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsSI5T9QmHXia57OFt:-MQKlfIQ56Rs0BaDwMQ2:b-8pky45) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram_test.go#L665)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to add another couple of tests where 
1. the starting value is the same (e.g., start with "a")
2. neither the starting or ending values are the same.
</blockquote></details>

I've encountered a little problem when attempting to filter buckets of type string where the lower bound of the bucket is the same as the lower bound of the span.  

Example: 
```
histBucket := &Histogram{evalCtx: &evalCtx, col: col, buckets: []cat.HistogramBucket{
			{NumEq: 0, NumRange: 0, DistinctRange: 0, UpperBound: getPrevUpperBound(tree.NewDString("a"))},
			{NumEq: 5, NumRange: 10, DistinctRange: 10, UpperBound: tree.NewDString("c")},
		}}

span: "[/a  - /b]"
```

In a situation like this, I get an assertion error : `"span must be fully contained in the bucket"`. 

I've traced it down to the following 2 things: 
1. When constructing the first histogram bucket above, the upperBound is set to: `getPrevUpperBound(tree.NewDString("a"))`. However, `lowerBound.prev()` within `getPrevUpperBound` for a Datum of type of string returns `nill, false`, resulting in the same upper bound of `a`. 
2. Within `TestFilterBucket`, the`setIdx(1)` gets the lowerBound of the 2nd histogram bucket by incrementing the upperBound of the previous histogram bucket calling `getNextLowerBound`. This results in a lower bound slightly larger than `a`.  

For this reason, I get the aforementioned assertion error as the bucket lower bound is larger than the span lower bound. I was wondering if this is expected behaviour for the `prev` and `next` methods associated with the string datum.  


<!-- Sent from Reviewable.io -->

2021-01-11 14:10 UTC, rytaft reviewed
Hi @arjunm98 -- no worries, and sorry for my delay this time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MQlXAqg-oPZYDaJJ1JZ:burik8p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98)

___
*[pkg/sql/opt/props/histogram.go, line 813 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsQEHmA6FK9CPPXekm:-MQlXKEL7L33KYgS4Lwe:blgnsl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L813)):*
<details><summary><i>Previously, ArjunM98 (Arjun Mittal) wrote…</i></summary><blockquote>

Yes, the important bytes for IPV4 address will get cut off after I truncate. However, the reason for adding the padding was to align the address space for IPV4 and IPV6. I think subtracting the upper bytes of IPV6 with an IPV4 address underestimates the range difference between the two addresses.
</blockquote></details>

This is definitely a tricky case. What's important with these kind of stats issues is to balance accuracy with practicality. 

Does increasing to 8 bytes (as I suggested above) fix this problem? If not, I think it's probably fine as-is, although you should note what's happening in a comment. I would guess that it's pretty rare that we would need to handle a case where IPV4 and IPV6 address are mixed together like this, so I'm not too worried this is going to cause major problems.

But if this is in fact a common case where people are mixing IPV4 and IPV6 addresses, we might need to compromise on accuracy slightly for the sake of practicality. In general, throughout the optimizer costing and stats code, we don't care about perfect accuracy. It's much more important that (1) the code is understandable and maintainable, and (2) that relative costs are preserved when possible (i.e., we care more about the fact that x < y than the absolute values of x and y). The potential problem with this code is that it will make two ranges look identical when one is actually slightly larger than the other. If we need to, we can introduce the concept of "epsilon" (i.e., a tiny number like 1e-10) here, to differentiate a partial bucket from a full bucket. For now, just add a comment that this is something to watch out for.
___
*[pkg/sql/opt/props/histogram.go, line 907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsNV4kAdC310EaFLnt:-MQlb89tDPBGP3WjhXzG:b8xmtfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L907)):*
<details><summary><i>Previously, ArjunM98 (Arjun Mittal) wrote…</i></summary><blockquote>

I was skipping over the escape characters because if a null byte 0x00 is encountered within a string/uuid/ip address, an escape character 0xff is appended after the null byte. I believe when finding the rangeBefore & rangeAfter, leaving in this escape character would lead to an inaccurate estimation. 

For example given a UUID span like the following: 
```
[/bbbbbb00-bbbb-bbbb-bbbb-bbbbbbbbbbbb - /cccccccc-cccc-cccc-cccc-cccccccccccc]
```

The corresponding encoded byte representation of the following span is: 
```
\bbbbbb00 ... -> [187 187 187 0 255 ...],  \cccccccc ... [204 204 204 204 204 ...]

rangeAfter := [204 204 204 204 204 ...] - [187 187 187 0 255 ...]
```

The encoded byte representation above contains a 0xff byte after the 0x00 byte in the lower bound. Without skipping over the escape character (0xff), the resulting rangeAfter value would be lower compared to if we had skipped over it. The actual range difference in that span is: 

```
[187 187 187 0 187 ...],  \cccccccc ... [204 204 204 204 204 ...]

rangeAfter := [204 204 204 204 204 ...] - [187 187 187 0 187 ...]

```

Similarly, all byte representations of UUID/strings/IP addresses are terminated by /x00/x01. When we have different sized strings, the additional 0x01 will result in inaccurate estimations for rangeBefore and rangeAfter once again. Which is why I also skip the termination character (0x01), similar to above. 

This is why for your comments below, I had a for loop to skip over the escape/termination characters. Is this a correct way of thinking about it? Or do you think we can still include the escape characters in the byte array? 
</blockquote></details>

Ah, ok. This makes sense. Thanks for the explanation! Similar to what I've said in other places, this type of logic should not live in the histogram code. I would try to use existing functions in `encoding.go` as much as possible. Is there a reason you can't use `DecodeBytesAscending` for this, which is already using similar logic?

If that's not possible, I think I would still stand by my comment below, which it probably going to give you correct results in 99% of cases. And even in the cases where it's not correct, I imagine it's still close enough that it doesn't matter (although please correct me if I'm wrong). I think this is likely one of the cases where practicality outweighs perfect accuracy (see my other comment above).
___
*[pkg/sql/opt/props/histogram_test.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsSI5T9QmHXia57OFt:-MQlh7U722Xj9OgR8ErL:brkxghf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram_test.go#L665)):*
<details><summary><i>Previously, ArjunM98 (Arjun Mittal) wrote…</i></summary><blockquote>

I've encountered a little problem when attempting to filter buckets of type string where the lower bound of the bucket is the same as the lower bound of the span.  

Example: 
```
histBucket := &Histogram{evalCtx: &evalCtx, col: col, buckets: []cat.HistogramBucket{
			{NumEq: 0, NumRange: 0, DistinctRange: 0, UpperBound: getPrevUpperBound(tree.NewDString("a"))},
			{NumEq: 5, NumRange: 10, DistinctRange: 10, UpperBound: tree.NewDString("c")},
		}}

span: "[/a  - /b]"
```

In a situation like this, I get an assertion error : `"span must be fully contained in the bucket"`. 

I've traced it down to the following 2 things: 
1. When constructing the first histogram bucket above, the upperBound is set to: `getPrevUpperBound(tree.NewDString("a"))`. However, `lowerBound.prev()` within `getPrevUpperBound` for a Datum of type of string returns `nill, false`, resulting in the same upper bound of `a`. 
2. Within `TestFilterBucket`, the`setIdx(1)` gets the lowerBound of the 2nd histogram bucket by incrementing the upperBound of the previous histogram bucket calling `getNextLowerBound`. This results in a lower bound slightly larger than `a`.  

For this reason, I get the aforementioned assertion error as the bucket lower bound is larger than the span lower bound. I was wondering if this is expected behaviour for the `prev` and `next` methods associated with the string datum.  
</blockquote></details>

This is expected. Here are the implementations: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/datum.go#L1159-L1167.

To get around this, instead of using the `getPrevUpperBound` function, you can define the span so that it starts at the next value. For example, define the upper bound of the first bucket as "a", and define the span as starting at "a\x00". Does that work?


<!-- Sent from Reviewable.io -->

2021-01-13 22:38 UTC, ArjunM98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ArjunM98 and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 671 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLs66o29C9pTWiw8fTi:-MQxky_yDiSKMLQRIqFx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L671)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why 4 bytes? In the example below it doesn't look like you're limiting it to 4 bytes...

edit: oh I see -- it's 4 bytes since you're casting it to a uint32. Might as well at least do 8 bytes and cast to uint64... either way, you should update the comment to make that clear.

You should also include some test cases where `lowerBoundAfter` and `upperBoundAfter` have the same first 4 or 8 bytes, but differ after that, so that `rangeAfter` appears to be 0. You should make sure that we're returning sane results in that case.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLs6Y1l6ZbRSIvC5TNC:-MQxl2Oj-rAYlWCi1s5a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L680)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd reorder these so that they are sorted lexicographically (i.e., bluejay and boar before bobcat). Makes it easier to see how the bytes correspond to the string.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 687 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsETbyAoxVL307zToY:-MQxlTVT6vnIbQAU5tFZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L687)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nice example! I'd also go a step further and actually show what the resulting numeric ranges are (or at least explain how they are calculated)
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 813 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsQEHmA6FK9CPPXekm:-MQxlc3kBTIs8bxjNNFM:b-mlel6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L813)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is definitely a tricky case. What's important with these kind of stats issues is to balance accuracy with practicality. 

Does increasing to 8 bytes (as I suggested above) fix this problem? If not, I think it's probably fine as-is, although you should note what's happening in a comment. I would guess that it's pretty rare that we would need to handle a case where IPV4 and IPV6 address are mixed together like this, so I'm not too worried this is going to cause major problems.

But if this is in fact a common case where people are mixing IPV4 and IPV6 addresses, we might need to compromise on accuracy slightly for the sake of practicality. In general, throughout the optimizer costing and stats code, we don't care about perfect accuracy. It's much more important that (1) the code is understandable and maintainable, and (2) that relative costs are preserved when possible (i.e., we care more about the fact that x < y than the absolute values of x and y). The potential problem with this code is that it will make two ranges look identical when one is actually slightly larger than the other. If we need to, we can introduce the concept of "epsilon" (i.e., a tiny number like 1e-10) here, to differentiate a partial bucket from a full bucket. For now, just add a comment that this is something to watch out for.
</blockquote></details>

Okay this makes sense. I've removed the extra padding added to the beginning of the IPV4 address when IPV6/IPV4 are mixed. 
___
*[pkg/sql/opt/props/histogram.go, line 825 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsGC3I-HzE0nBrf5Ln:-MQxm5bTDIc780WdC9ML:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L825)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] lines of code should fit within 100 columns
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 868 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsAxWD1YHElOeZdd7n:-MQxmOz857BgDjdZEXj2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L868)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

To prevent anyone from using this function incorrectly, you should check that `len(byteArr) > 0`, and if not, panic with `panic(errors.AssertionFailedf("byteArr must have at least one element"))` (feel free to change the error message, but should be something similar). Also mention in the function comment that `byteArr` must have at least one element.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 872 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsI6Yf3Q_BO1hAO0T9:-MQxmcPKCZmD5bOcwLUc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L872)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't this function return false if `ind < len(byteArr[0]) && ind < len(byteArr[i])` is false?

edit: oh I see, you've added another function to do that. That seems like overkill -- why not just do it in one function?
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 880 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsIle50QJebn9OF8M7:-MQxmhke9taunqlYpBid:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L880)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

As I mentioned above, this function seems like overkill. You're already checking the bounds in the function above, so why not just combine the logic there?
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 882 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsIiqWBiFTcgvb0wYc:-MQxmkPj657rLdbTS4pI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L882)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't this be `>=`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 904 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsMZRZ-DUORIJfdNMI:-MQxmoEFEKrdNphHwx8L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L904)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think you can avoid allocating a new array if the existing slice has length at least `fixLen+ind`, and in that case return `byteArr[ind:fixLen+ind]`
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 907 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MLsNV4kAdC310EaFLnt:-MQxmuF40kUOsCikQplk:b-qzbw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea3d27d7d39e24f77ddb73afa55fc7b5a080a34/pkg/sql/opt/props/histogram.go#L907)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></su [...]

2021-01-15 20:41 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>  really great work!

There are just a few remaining nits below. I think you also need to rebase from master (that should fix the build error). Thanks for all your time on this!

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MR6lCzp4QklzPZQDXPe:bt5fhed)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ArjunM98)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 1983 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKaen-m0EmKCsTpDrd_:-MR6l_nHBUFfJZ4Gfcnb:b-or5uer) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/memo/testdata/stats/select#L1983)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] comments should be at most 80 columns wide and end with a period.
</blockquote></details>

Don't forget this one :)
___
*[pkg/sql/opt/props/histogram.go, line 867 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6evy1-2c7D_y-eXEU:-MR6evy21cw2m68fCPaW:b9pdfo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L867)):*
> ```Go
> 
> // getCommonPrefix returns the first index where the value at said index differs
> // across all byte arrays in byteArr. ByteArr must contain at least one element
> ```

[super nit] ByteArr -> byteArr
___
*[pkg/sql/opt/props/histogram.go, line 903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6h8Gm2vXtYZaRMAJI:-MR6h8Gm2vXtYZaRMAJJ:b-kuxdgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L903)):*
> ```Go
> 	if fixLen <= 0 {
> 		panic(errors.AssertionFailedf("desired fixLen must be greater than 0"))
> 	}
> ```

while you're at it with these checks, might as well check that `ind >= 0 && ind <= len(byteArr)`
___
*[pkg/sql/opt/props/histogram_test.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6idkJ4lJOGdcuFrXN:-MR6idkJ4lJOGdcuFrXO:b-rsyt0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram_test.go#L681)):*
> ```Go
> 				expected: &cat.HistogramBucket{NumEq: 0, NumRange: 4.99, DistinctRange: 4.99, UpperBound: tree.NewDString("b")},
> 			},
> ```

[nit] remove this line
___
*[pkg/sql/opt/props/histogram_test.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6jF_S5NHj9FE1uk6F:-MR6jF_S5NHj9FE1uk6G:b-uwg6jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram_test.go#L698)):*
> ```Go
> 		// The initial 8 bytes for lowerBound and upperBound of the span is the same.
> 		// Hence, the resulting NumRange/DistinctRange should be 0, as rangeAfter
> 		// only considers the first 8 bytes of the bounds.
> ```

nice test case!


<!-- Sent from Reviewable.io -->

2021-01-15 21:25 UTC, ArjunM98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ArjunM98 and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/select, line 1983 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MKaen-m0EmKCsTpDrd_:-MR6njEQC6CfPZXRu9QN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eab72ac193f57ca79d889a71c286ca173392821b/pkg/sql/opt/memo/testdata/stats/select#L1983)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Don't forget this one :)
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 867 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6evy1-2c7D_y-eXEU:-MR6vb-1BSkCInKIA3Ut:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L867)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[super nit] ByteArr -> byteArr
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram.go, line 903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6h8Gm2vXtYZaRMAJI:-MR6vf4X5_5-N8v_5GXz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L903)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

while you're at it with these checks, might as well check that `ind >= 0 && ind <= len(byteArr)`
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/histogram_test.go, line 681 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6idkJ4lJOGdcuFrXN:-MR6viWo1afftYXd1QGY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram_test.go#L681)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] remove this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 21:35 UTC, rytaft requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ArjunM98)

___
*[pkg/sql/opt/props/histogram.go, line 903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6h8Gm2vXtYZaRMAJI:-MR6xzrY1oXcd6hueMNu:br8onjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L903)):*
<details><summary><i>Previously, ArjunM98 (Arjun Mittal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

negating these I think needs to look like:
`if ind < 0 || ind > len(byteArr) {`


<!-- Sent from Reviewable.io -->

2021-01-15 21:41 UTC, ArjunM98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ArjunM98 and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-MR6h8Gm2vXtYZaRMAJI:-MR6zV3x7aVhTZil-Q3r:bi7wr16) ([raw file](https://github.com/cockroachdb/cockroach/blob/933c52cbbd580a0ee43c8940bfd374b71e008b6a/pkg/sql/opt/props/histogram.go#L903)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

negating these I think needs to look like:
`if ind < 0 || ind > len(byteArr) {`
</blockquote></details>

Whoops, my bad


<!-- Sent from Reviewable.io -->

2021-01-15 22:42 UTC, rytaft approved these changes
Awesome! Thanks for the contribution and for sticking with it.

bors r+

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55797#-:-MR72xHxDXWBI4PP4vYa:bho8ux0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ArjunM98)



<!-- Sent from Reviewable.io -->

2021-01-15 23:03 UTC, ArjunM98 commented
np! Thanks for answering all my questions :)

2021-01-19 15:19 UTC, rytaft commented
Looks like a flake.

bors r+





<!-- Sent from Reviewable.io -->

2021-01-19 16:29 UTC, rytaft commented
Trying again

bors r+





<!-- Sent from Reviewable.io -->

2021-01-19 17:37 UTC, merged