flowinfra: fix and extend flow setup benchmark
cockroachdb/cockroach pull request #56220
Opened 2020-11-03 00:49 UTC by yuzefovich

Previously, the flow setup benchmark would fail because we reused the
same internal planner object multiple times, and this is not supported
(it would fail due to memory budget error). This is now fixed by
creating a new internal planner on every iteration.

Additionally, this commit extends the benchmark to try both the
vectorized and row-based flow setups.

Release note: None

2020-11-03 00:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56220)
<!-- Reviewable:end -->

2020-11-03 13:07 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLDCmeNEgtnhnrvcmgK:brvdijf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
> ```Go
> 	// Set the threshold to 0 so that we can control which engine is used for
> 	// the query execution via the vectorize mode.
> 	r.Exec(b, `SET CLUSTER SETTING sql.defaults.vectorize_row_count_threshold=0`)
> ```

Can you pass this as an argument to `StartServer`?  There might be some flakiness involved otherwise.


<!-- Sent from Reviewable.io -->

2020-11-03 13:07 UTC, asubiotto commented
@cathymw handing this review off to you.

2020-11-03 19:06 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLEUAloCe29KG9eoaPy:b-z2idu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you pass this as an argument to `StartServer`?  There might be some flakiness involved otherwise.
</blockquote></details>

I don't think it's possible with a lot of plumbing. I also haven't experienced any flakiness - I think there could be some if we instantiated a multiple node cluster, but we have a single node one.


<!-- Sent from Reviewable.io -->

2020-11-03 22:06 UTC, cathymw requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice! TIL NB == nota bene, so fancy!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-:-MLF4zlz4MTHjvOgiShD:bg6grt0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLF7bmp0zCVfLHQ7OcE:-MLF7bmp0zCVfLHQ7OcF:b7hikpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
> ```Go
> 	// Set the threshold to 0 so that we can control which engine is used for
> 	// the query execution via the vectorize mode.
> 	r.Exec(b, `SET CLUSTER SETTING sql.defaults.vectorize_row_count_threshold=0`)
> ```

I might be missing something here, but is setting the threshold to 0 required in order for the `VectorizeMode` field to take effect? I.e. if it's not set to 0 does setting `VectorizeMode` not work? That's what I got from the comment, but just wanted to clarify how it actually works


<!-- Sent from Reviewable.io -->

2020-11-03 22:19 UTC, cathymw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Oops, meant to approve, not request changes 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-:-MLFAvRYDPm33aH-69on:bq0reoe)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2020-11-03 22:44 UTC, yuzefovich reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-:-MLFFVKvB3licw5rwHlh:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLF7bmp0zCVfLHQ7OcE:-MLFFY1c9F27U_5n8lEq:b5uzhls) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, cathymw wrote…</i></summary><blockquote>

I might be missing something here, but is setting the threshold to 0 required in order for the `VectorizeMode` field to take effect? I.e. if it's not set to 0 does setting `VectorizeMode` not work? That's what I got from the comment, but just wanted to clarify how it actually works
</blockquote></details>

In order for the vectorized engine to be used, two conditions need to be met:
1. we need to estimate that we will read at least `vectorize_row_count_threshold` number of rows from at least one table. The estimate comes from the optimizer, and the goal of this condition is making sure that we have enough data to work with. This was put in-place when the overhead of setting up the vectorized flow and running it was pretty high, and if the threshold is not met, we fallback to using the old row-by-row engine. Removing this threshold is actually the thing that I've been working on for the last couple of weeks - we're now at the point when almost in any case it is not worse and possible better to use the vectorized engine
2. we need to support the flow specifications (some processors cannot be vectorized). This is currently checked by `SupportsVectorized` function which performs a "fake flow setup" for each flow spec.

So if we have `vectorizeMode == VectorizeOn`, but the query doesn't meet the threshold, we still will use the row-by-row engine. And in this benchmark the query is a point lookup, so we estimate that we will read 0 or 1 row, and the threshold is never met. In order to actually run via the vectorized engine, we set the threshold to 0 effectively disabling condition 1 from above.
___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLFGwhH73V6Nfs254rP:b-yj7h7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think it's possible with a lot of plumbing. I also haven't experienced any flakiness - I think there could be some if we instantiated a multiple node cluster, but we have a single node one.
</blockquote></details>

*without a lot


<!-- Sent from Reviewable.io -->

2020-11-03 23:38 UTC, merged

2020-11-05 09:47 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cathymw and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLMnFmH7x1XLAybKy1S:bckyluq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

*without a lot
</blockquote></details>

I don't think so, `TestServerArgs` has a `*cluster.Settings` field.


<!-- Sent from Reviewable.io -->

2020-11-06 00:42 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @cathymw)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLQ-5q9EqT0OLNep7vC:brsbni0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think so, `TestServerArgs` has a `*cluster.Settings` field.
</blockquote></details>

I see, but how would I change anything on this object? Do you have an example in mind? I don't I've ever seen changing a cluster setting in tests without running a SQL statement.


<!-- Sent from Reviewable.io -->

2020-11-06 08:38 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56220)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cathymw and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_test.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56220#-MLDCmeNEgtnhnrvcmgJ:-MLRhAjRBYgdB94u5Fzv:b-ldb6cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf68d541acc5ccfae6118bd1a25b496227c8d3c/pkg/sql/flowinfra/flow_test.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I see, but how would I change anything on this object? Do you have an example in mind? I don't I've ever seen changing a cluster setting in tests without running a SQL statement.
</blockquote></details>

This is how you would do it, but I agree that it's maybe not worth it if we're running a single node
```
--- a/pkg/sql/flowinfra/flow_test.go
+++ b/pkg/sql/flowinfra/flow_test.go
@@ -18,6 +18,7 @@ import (
        "github.com/cockroachdb/cockroach/pkg/base"
        "github.com/cockroachdb/cockroach/pkg/kv"
        "github.com/cockroachdb/cockroach/pkg/security"
+       "github.com/cockroachdb/cockroach/pkg/settings/cluster"
        "github.com/cockroachdb/cockroach/pkg/sql"
        "github.com/cockroachdb/cockroach/pkg/sql/sessiondatapb"
        "github.com/cockroachdb/cockroach/pkg/testutils/serverutils"
@@ -34,14 +35,15 @@ func BenchmarkFlowSetup(b *testing.B) {
        defer logScope.Close(b)
        ctx := context.Background()

-       s, conn, _ := serverutils.StartServer(b, base.TestServerArgs{})
+       st := cluster.MakeTestingClusterSettings()
+       sql.VectorizeRowCountThresholdClusterValue.Override(&st.SV, 0)
+       s, conn, _ := serverutils.StartServer(b, base.TestServerArgs{
+               Settings: st,
+       })
        defer s.Stopper().Stop(ctx)

        r := sqlutils.MakeSQLRunner(conn)
        r.Exec(b, "CREATE DATABASE b; CREATE TABLE b.test (k INT);")
-       // Set the threshold to 0 so that we can control which engine is used for
-       // the query execution via the vectorize mode.
-       r.Exec(b, `SET CLUSTER SETTING sql.defaults.vectorize_row_count_threshold=0`)

        execCfg := s.ExecutorConfig().(sql.ExecutorConfig)
        dsp := execCfg.DistSQLPlanner
```


<!-- Sent from Reviewable.io -->

2020-11-06 22:40 UTC, yuzefovich commented
Oh, thanks, TIL.