hlc: introduce synthetic flag on timestamps
cockroachdb/cockroach pull request #56373
Opened 2020-11-06 17:50 UTC by nvanbenschoten

Informs #52745.
Informs #36431.

This commit introduces an 8-bit `flags` field on the hlc timestamp struct. The flags are used to provide details about the timestamp and its meaning. They do not affect the sort order of Timestamps.

The commit then introduces the first flag: SYNTHETIC. As discussed in #52745, a synthetic timestamp is defined as a timestamp that makes no claim about the value of clocks in the system. While standard timestamps are pulled from HLC clocks and indicate that some node in the system has a clock with a reading equal to or above its value, a synthetic timestamp makes no such indication. By avoiding a connection to "real time", synthetic timestamps can be used to write values at a future time and to indicate that observed timestamps do not apply to such writes for the purposes of tracking causality between the write and its observers. Observed timestamps will be a critical part of implementing non-blocking transactions (#52745) and fixing the interaction between observed timestamps and transaction refreshing (#36431).

The original plan was to reserve the high-order bit in the logical portion of a timestamp as a "synthetic bit". This is how I began implementing things, but was turned off for a few reasons. First, it was fairly subtle and seemed too easy to get wrong. Using a separate field is more explicit and avoids a class of bugs. Second, I began to have serious concerns about how the synthetic bit would impact timestamp ordering. Every timestamp comparison would need to mask out the bit or risk being incorrect. This was even true of the LSM custom comparator. This seemed difficult to get right and seemed particularly concerning since we're planning on marking only some of a transaction's committed values as synthetic to fix #36431, so if we weren't careful, we could get atomicity violations. There were also minor backwards compatibility concerns.

But a separate field is more expensive in theory, so we need to be careful. However, it turns out that a separate field is mostly free in each case that we care about. In memory, the separate field is effectively free because the Timestamp struct was previously 12 bytes but was always padded out to 16 bytes when included as a field in any other struct. This means that the flags field is replacing existing padding. Over the wire, the field will not be included when zero and will use a varint encoding when not zero, so again, it is mostly free. In the engine key encoding, the field is also not included when zero, and takes up only 1 byte when non-zero, so it is mostly free.

----

First two commits from #56190, which is waiting on #55520.

@sumeerbhola I'm hoping you can take a look at the engine-level changes in the `introduce synthetic flag on timestamps` commit (4th commit as of the time of writing). I think the key encoding added here makes sense, but want to make sure you're on board. One possible concern is that we introduce a new 13-byte suffix, which means that combined with a 4-byte sequence number (see https://github.com/cockroachdb/cockroach/issues/41720#issuecomment-548780872), we'd collide with the 17 byte `engineKeyVersionLockTableLen`.

@tbg do you mind being the primary reviewer here? I think you know the most about the motivations for this change and will have a good sense of whether this is the best way to introduce additional state on timestamps.

2020-11-06 17:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56373)
<!-- Reviewable:end -->

2020-11-06 20:30 UTC, tbg commented
Happy to review, but it will be on Tuesday.

On Fri, Nov 6, 2020, 18:50 cockroach-teamcity <notifications@github.com>
wrote:

> This change is [image: Reviewable]
> <https://reviewable.io/reviews/cockroachdb/cockroach/56373>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/56373#issuecomment-723214335>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGXPZCCBYFRNAD6WUSTAN3SOQZPBANCNFSM4TM642XQ>
> .
>

2020-11-09 20:28 UTC, sumeerbhola requested changes
minor comments only -- I haven't yet looked at the last 2 commits which tbg will be reviewing, but I'll try to follow along.

> Reviewed 12 of 12 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 27 of 29 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-:-MLig1rR6j6ZxV0xfmU3:b-2cppr8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/roachpb/data.go, line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLidNbvBDLKgdKjyMv-:-MLidNbvBDLKgdKjyMv0:b3dyo5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/roachpb/data.go#L1101)):*
> ```Go
> 		}
> 
> 		if t.ReadTimestamp == o.ReadTimestamp {
> ```

why is the synthetic bit relevant here?
___
*[pkg/util/hlc/legacy_timestamp.proto, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLibs1L6AJyR7rhguqj:-MLibs1L6AJyR7rhguqk:b5vy290) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/legacy_timestamp.proto#L41)):*
> ```protobuf
>   // == operator). Consider use of the EqOrdering method when testing for
>   // equality.
>   optional uint32 flags = 3;
> ```

is this `nullable` because it will be serialized in `MVCCMetadata` and we don't want to pay the serialized cost when it is not set?
___
*[pkg/util/hlc/timestamp.go, line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_vLY88-8LzUzsmFu:-MLi_vLY88-8LzUzsmFv:b-9ihqpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L272)):*
> ```Go
> func (t *Timestamp) Backward(s Timestamp) {
> 	// TODO(nvanbenschoten): if either timestamp is non-synthetic, we can remove
> 	// the synthetic bit.
> ```

Maybe phrase this TODO as: remove the synthetic bit from the older value if the younger one is non-synthetic.
___
*[pkg/util/hlc/timestamp.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_Oaq72DosKpCs4VA:-MLi_Oaq72DosKpCs4VB:b-5dh99e) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L283)):*
> ```Go
> }
> 
> // ToLegacyTimestamp converts a Timestamp to a LegacyTimestamp.
> ```

Is it possible to get rid of `LegacyTimestamp`?


<!-- Sent from Reviewable.io -->

2020-11-10 03:21 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[pkg/roachpb/data.go, line 1101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLidNbvBDLKgdKjyMv-:-MLk5SwB3ciGk-f7X3HL:b-a323ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/roachpb/data.go#L1101)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why is the synthetic bit relevant here?
</blockquote></details>

It isn't really relevant. This is just switching from `Equal` to `==`, which has the same semantics but it more idiomatic to test for structural equality.
___
*[pkg/util/hlc/legacy_timestamp.proto, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLibs1L6AJyR7rhguqj:-MLk5fBn1Z7MkpESkQuk:b-udq38m) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/legacy_timestamp.proto#L41)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this `nullable` because it will be serialized in `MVCCMetadata` and we don't want to pay the serialized cost when it is not set?
</blockquote></details>

Kind of. It's `nullable` because we need identical encoding below Raft to ensure that all replicas stay bytewise identical even in a mixed version cluster. This is the same reason why we've never been able to completely remove `LegacyTimestamp`. So since the field won't even exist on v20.2 nodes, we need to make sure it doesn't get serialized on v21.1 nodes. 
___
*[pkg/util/hlc/timestamp.go, line 272 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_vLY88-8LzUzsmFu:-MLk74xe3bn6FHSYKJnX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L272)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Maybe phrase this TODO as: remove the synthetic bit from the older value if the younger one is non-synthetic.
</blockquote></details>

Done.
___
*[pkg/util/hlc/timestamp.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_Oaq72DosKpCs4VA:-MLk6HKT7O580jBJwprI:bwgcy0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L283)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is it possible to get rid of `LegacyTimestamp`?
</blockquote></details>

I'm trying, but it's putting up a fight: https://github.com/cockroachdb/cockroach/pull/56190. It's also used in `MVCCMetadata`, which is written to "below Raft" in a number of places. I think we're going to need to run an online migration if we ever want to remove it entirely. 


<!-- Sent from Reviewable.io -->

2020-11-10 14:13 UTC, tbg approved these changes
I'm still anxious that synthetic and regular timestamps will have an opportunity to mix when they shouldn't, given how much existing code is out there. In particular, `.Forward()` and `.Backward()` seem susceptible. I wish we had proper enum types.
From plowing through the code so far, are you worried at all? And/or do you have ideas on getting at least some amount of separation between them back (clearly separate types are not an option)?

> Reviewed 41 of 41 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, 5 of 5 files at r9, 35 of 35 files at r10, 2 of 2 files at r11, 53 of 53 files at r12, 8 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-:-MLmUp5zEdHVa1tSU4Kx:b3ognx0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/util/hlc/legacy_timestamp.proto, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLibs1L6AJyR7rhguqj:-MLmQ43pCZQcpkGI4M3w:bpc3rel) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/legacy_timestamp.proto#L41)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Kind of. It's `nullable` because we need identical encoding below Raft to ensure that all replicas stay bytewise identical even in a mixed version cluster. This is the same reason why we've never been able to completely remove `LegacyTimestamp`. So since the field won't even exist on v20.2 nodes, we need to make sure it doesn't get serialized on v21.1 nodes. 
</blockquote></details>

Mind putting that in the comment?
___
*[pkg/util/hlc/timestamp.go, line 257 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmQRnA74ypQ6EIGiNq:-MLmQRnA74ypQ6EIGiNr:bhkucbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.go#L257)):*
> ```Go
> 
> // Forward updates the timestamp from the one given, if that moves it forwards
> // in time. Returns true if the timestamp was adjusted and false otherwise.
> ```

Clarify the language in the comment:

// Forward replaces the receiver with the argument, if that moves it forwards in time.
___
*[pkg/util/hlc/timestamp.go, line 269 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmQkGvDUuEQJOEoKFZ:-MLmQkGvDUuEQJOEoKF_:bz1wb3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.go#L269)):*
> ```Go
> 
> // Backward updates the timestamp from the one given, if that moves it
> // backwards in time.
> ```

ditto about clarifying language
___
*[pkg/util/hlc/timestamp.proto, line 51 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmRW8a6BKG-nk2f6ng:-MLmRW8a6BKG-nk2f6nh:bmr8ovw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.proto#L51)):*
> ```protobuf
>   // timestamp makes no such indication. By avoiding a connection to "real
>   // time", synthetic timestamps can be used to write values at a future
>   // time and to indicate that observed timestamps do not apply to such
> ```

I feel that nobody will understand this in the future. Perhaps

// Synthetic timestamps are central to non-blocking transactions, which essentially write at "future timestamps". They are also used in observed timestamps, where they indicate versions that were moved from the timestamp at which they were originally written; only synthetic timestamps require observing the full uncertainty interval, whereas readings off the node's clock can tighten it for non-synthetic versions.
___
*[pkg/util/hlc/timestamp_test.go, line 46 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmS8hf8gcAxn-nK05Z:-MLmS8hf8gcAxn-nK05_:b-tatgmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp_test.go#L46)):*
> ```Go
> 	}
> 	a = makeTS(1, 1)
> 	if a.EqOrdering(b) {
> ```

curious why you didn't like `require.False(t, a.EqOrdering(b), "%+v == %+v", a, b)`
___
*[pkg/util/hlc/timestamp_test.go, line 207 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmStK49gNiKcA0yh2X:-MLmStK49gNiKcA0yh2Y:b-ulfdbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp_test.go#L207)):*
> ```Go
> 		assert.Equal(t, c.exp, c.ts.String())
> 
> 		// Flags don't round-trip through parsing, so ignore them.
> ```

Shouldn't they? If not, at least update comment on ParseTimestamp.
___
*[pkg/util/span/frontier.go, line 63 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmTej02ey0i_rx6CG2:-MLmTej02ey0i_rx6CG3:bh0e7n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d9549bfe9faa695c271f38ffad295e876c942e/pkg/util/span/frontier.go#L63)):*
> ```Go
> // Less implements heap.Interface.
> func (h frontierHeap) Less(i, j int) bool {
> 	if h[i].ts.EqOrdering(h[j].ts) {
> ```

Can you leave that `_ func()` field on the struct to disable explicit comparisons going forward on both timestamp types?

```
bytes no_equality = 3 [(gogoproto.nullable) = true, (gogoproto.customname) = "_"];
```

worked nicely in my local testing.


<!-- Sent from Reviewable.io -->

2020-11-10 23:25 UTC, nvanbenschoten reviewed
TFTRs!

> I'm still anxious that synthetic and regular timestamps will have an opportunity to mix when they shouldn't, given how much existing code is out there. In particular, .Forward() and .Backward() seem susceptible. I wish we had proper enum types.
> From plowing through the code so far, are you worried at all? And/or do you have ideas on getting at least some amount of separation between them back (clearly separate types are not an option)?

My current plan is to never allow synthetic timestamps to do any harm by fataling if we ever call `hlc.Update` with a synthetic timestamp. This effectively means that we need to separate out the "transaction time domain" from the "clock time domain", and we'll be made aware pretty quickly if these ever mix. We already have this separation in some places. For instance, we have a `BatchRequest.Timestamp` and a `BatchResponse.Now`, which are independent from the timestamps passed around in `Transaction` objects.

My other thought is that I'm going to split `hlc.Update` into two methods – `hlc.UpdateForStability` and `hlc.UpdateForCausality`. This doesn't directly tie in to the discussion here, but it means that we're going to need to be a little more explicit about when, where, and why we update the hlc clock. I expect that this will uncover cases where timestamps from the "transaction time domain" and leaking back into the "clock time domain".

One more aggressive idea to enforce this separation is to use another flag to indicate which domain a timestamp is part of. A conversion from a "clock timestamp" to a "transaction timestamp" would be allowed, but not the other way around. We could then assert that no "transaction timestamp" (synthetic or otherwise) ever makes its way back into a clock. My primary concern with this would be its impact on performance. We'd probably want to make the transaction domain the zero value for the flag.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-:-MLnWKVd12jD69Ygdywd:bknc8l5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[pkg/util/hlc/legacy_timestamp.proto, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLibs1L6AJyR7rhguqj:-MLnZwt3ESt2w-cSswPj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/legacy_timestamp.proto#L41)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind putting that in the comment?
</blockquote></details>

Done.
___
*[pkg/util/hlc/timestamp.go, line 257 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmQRnA74ypQ6EIGiNq:-MLn_BGvER9Y5Vf5M-LR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.go#L257)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Clarify the language in the comment:

// Forward replaces the receiver with the argument, if that moves it forwards in time.
</blockquote></details>

Done.
___
*[pkg/util/hlc/timestamp.go, line 269 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmQkGvDUuEQJOEoKFZ:-MLn_Bbq5dl0-NsXXiUK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.go#L269)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

ditto about clarifying language
</blockquote></details>

Done.
___
*[pkg/util/hlc/timestamp.proto, line 51 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmRW8a6BKG-nk2f6ng:-MLoRH1FEzrMH90tR7FP:b-gnpy63) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp.proto#L51)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I feel that nobody will understand this in the future. Perhaps

// Synthetic timestamps are central to non-blocking transactions, which essentially write at "future timestamps". They are also used in observed timestamps, where they indicate versions that were moved from the timestamp at which they were originally written; only synthetic timestamps require observing the full uncertainty interval, whereas readings off the node's clock can tighten it for non-synthetic versions.
</blockquote></details>

I combined the two comments. I wanted to keep some more general definition so that we aren't limited in where we use these timestamps, but I like how clear your examples are.
___
*[pkg/util/hlc/timestamp_test.go, line 46 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmS8hf8gcAxn-nK05Z:-MLn_DN5EE2LSfkENlDV:b-dawlpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp_test.go#L46)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

curious why you didn't like `require.False(t, a.EqOrdering(b), "%+v == %+v", a, b)`
</blockquote></details>

Just to stay consistent with the rest of the tests in this file.
___
*[pkg/util/hlc/timestamp_test.go, line 207 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmStK49gNiKcA0yh2X:-MLoPL134liOiOv1ZC9B:bia3b2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb5468d9e1d1d7bea397d48124b6008588481e3b/pkg/util/hlc/timestamp_test.go#L207)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't they? If not, at least update comment on ParseTimestamp.
</blockquote></details>

Yeah, I should have just done this to begin with. Done.
___
*[pkg/util/span/frontier.go, line 63 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLmTej02ey0i_rx6CG2:-MLoPQ6T0L65sQRIyUN3:bsemb3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d9549bfe9faa695c271f38ffad295e876c942e/pkg/util/span/frontier.go#L63)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you leave that `_ func()` field on the struct to disable explicit comparisons going forward on both timestamp types?

```
bytes no_equality = 3 [(gogoproto.nullable) = true, (gogoproto.customname) = "_"];
```

worked nicely in my local testing.
</blockquote></details>

I went back and forth on it. This won't work if we want to continue using proto to generate the struct def:
```
pkg/util/hlc/timestamp.pb.go:139:22: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:174:10: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:177:50: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:178:24: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:204:6: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:206:7: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:300:11: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:432:5: cannot refer to blank field or method
pkg/util/hlc/timestamp.pb.go:433:8: cannot refer to blank field or method
```

But we could do so ourselves using `option (gogoproto.typedecl) = false;`. But I shied away from this for two reasons:
1. it increases the struct size from 16 bytes to 40 bytes. We can do better with a `_ func()`, which limits to growth to 24 bytes, but that's still runtime overhead. And it's more pointers for the GC to chase.
2. it adds yet another dependency on gogoproto that we'll never be able to break away from.

So in the end, I decided it wasn't worth it. It turns out that we don't end up checking for timestamp equality in very many places anyway – we pretty much always use `Less` or `LessEq`.


<!-- Sent from Reviewable.io -->

2020-11-11 14:39 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> for the parts I reviewed

> Reviewed 1 of 36 files at r15, 21 of 54 files at r17, 2 of 8 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-:-MLrjkw1E7dYWUfFZTBV:b-xuzr19)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)



<!-- Sent from Reviewable.io -->

2020-11-12 20:00 UTC, nvanbenschoten commented
TFTRs!

bors r+

2020-11-12 22:13 UTC, nvanbenschoten commented
Strange failure in `version-upgrade`. Don't have time to look now, but canceling this build.

bors r-

2020-11-13 04:22 UTC, nvanbenschoten commented
I can't explain the failure other than some kind of network flake. The "dead" node never actually dies, it just hits a network error:
```
E201112 20:56:24.291372 1 cli/error.go:398 â‹® â€¹ERROR: connection lost.â€º
â€¹admin-set-ui-data: result is ambiguous (error=rpc error: code = Unavailable desc = transport is closing [propagate])â€º
```

We also see this in the stderr:
```
*
* WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
* 
* This mode is intended for non-production testing only.
* 
* In this mode:
* - Your cluster is open to any client that can access 127.0.0.1.
* - Intruders with access to your machine or network can observe client-server traffic.
* - Intruders can log in without password and read or write any data in the cluster.
* - Intruders can consume all your server's resources and cause unavailability.
*
*
* INFO: To start a secure server without mandating TLS for clients,
* consider --accept-sql-without-tls instead. For other options, see:
* 
* - https://go.crdb.dev/issue-v/53404/v20.2
* - https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster.html
*
*
* WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
* 
* This mode is intended for non-production testing only.
* 
* In this mode:
* - Your cluster is open to any client that can access 127.0.0.1.
* - Intruders with access to your machine or network can observe client-server traffic.
* - Intruders can log in without password and read or write any data in the cluster.
* - Intruders can consume all your server's resources and cause unavailability.
*
*
* INFO: To start a secure server without mandating TLS for clients,
* consider --accept-sql-without-tls instead. For other options, see:
* 
* - https://go.crdb.dev/issue-v/53404/v21.1
* - https://www.cockroachlabs.com/docs/v21.1/secure-a-cluster.html
*
*
* ERROR: ERROR: connection lost.
* 
* admin-set-ui-data: result is ambiguous (error=rpc error: code = Unavailable desc = transport is closing [propagate])
*
ERROR: connection lost.

admin-set-ui-data: result is ambiguous (error=rpc error: code = Unavailable desc = transport is closing [propagate])
Failed running "start"
```

I ran `acceptance/version-upgrade` 60 times on this PR and never hit a similar issue, so I don't believe that it has to do with this change.

bors r+

2020-11-13 06:56 UTC, merged

2020-11-19 17:03 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/util/hlc/timestamp.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_Oaq72DosKpCs4VA:-MMWQTzc2lfnv0-wobih:bz0cdx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L283)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm trying, but it's putting up a fight: https://github.com/cockroachdb/cockroach/pull/56190. It's also used in `MVCCMetadata`, which is written to "below Raft" in a number of places. I think we're going to need to run an online migration if we ever want to remove it entirely. 
</blockquote></details>

Where is `MVCCMetadata` written to below Raft? I am adding the bool `txn_did_not_update_meta` field to `MVCCMetadata` and I suppose I will need to make it truly optional.
I wish there was a way with `gogoproto` to make something optional but tell it to not use a pointer, and so avoid an allocation, and not marshal when the value is the default.

Hmm, I see this come up in https://github.com/gogo/protobuf/issues/142, which you referenced in a commit 2 years ago, and proto3 was recommended as the solution. What is our story on proto3 adoption/conversion -- we are using it in some places?


<!-- Sent from Reviewable.io -->

2020-11-19 19:43 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56373)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola and @tbg)

___
*[pkg/util/hlc/timestamp.go, line 283 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56373#-MLi_Oaq72DosKpCs4VA:-MMX-kIfBWdBUZWrlpOd:bgfy1bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/919e44171197b792623e2f35557826b2eddcc889/pkg/util/hlc/timestamp.go#L283)):*
> Where is MVCCMetadata written to below Raft? I am adding the bool txn_did_not_update_meta field to MVCCMetadata and I suppose I will need to make it truly optional.

I believe the calls to `MVCCPutProto` with an empty timestamp in `StateLoader` are responsible for most of the uses below Raft.

> I wish there was a way with gogoproto to make something optional but tell it to not use a pointer, and so avoid an allocation, and not marshal when the value is the default.

This is how proto3 works, but not proto2. We use proto3 in most places, but can't in cases where we need deterministic proto encoding for messages that are written below Raft.

One option would be to split `MVCCMetadata` into a proto3 `MVCCMetadata` without compatibility concerns and a proto2 `LegacyMVCCMetadata` with compatibility concerns. This would mirror what we did with `Timestamp`/`LegacyTimestamp`. I say this having not explored how difficult doing so would be.


<!-- Sent from Reviewable.io -->