kv,storage: add support for child transactions
cockroachdb/cockroach pull request #56588
Opened 2020-11-11 20:03 UTC by ajwerner

This PR adds support for child transactions. Still missing is a flag to ensure that parent writes are not encountered. There are some somewhat rough edges related to error handling. Keeping it a draft for the moment.

Fixes #54633

2020-11-11 20:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56588)
<!-- Reviewable:end -->

2020-12-01 15:33 UTC, ajwerner commented
@nvanbenschoten I still haven't added the flag to disallow interactions between children and their ancestor intents but I'd love if you could give this a pass as I think there's some controversial stuff.

2020-12-14 17:39 UTC, nvanbenschoten reviewed
This is looking good. Sorry for the long delay on the review - it got lost in my inbox.

What were the controversial parts that you wanted to discuss further? Did I catch them in the review or were there others you'd also like to raise and discuss?

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 4 of 4 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MOXJnKs5EFOIZfVAqsz:bc6cfh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/sender.go, line 302 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXIXPs4euj5EfoEbyE:-MOXIXPs4euj5EfoEbyF:b-5gno1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/sender.go#L302)):*
> ```Go
> 	// transaction and must be committed. If the set of read spans
> 	// of the transaction overlaps with the writes of the child (as accounted
> 	// for in InFlightWrites and LockSpans), an error will be returned.
> ```

Oh, that's interesting. So we don't even want to support cases where the parent has already read keys that the child ends up writing? If so, does that simplify the lock table handling?
___
*[pkg/kv/sender.go, line 303 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXIgvm5CrRSPCYWeww:-MOXIgvm5CrRSPCYWewx:b-fy8v5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/sender.go#L303)):*
> ```Go
> 	// of the transaction overlaps with the writes of the child (as accounted
> 	// for in InFlightWrites and LockSpans), an error will be returned.
> 	ForwardToChild(ctx context.Context, child *roachpb.Transaction) error
> ```

My immediate reaction to this signature is "why isn't this `ForwardTimestampAndRefresh`?"
___
*[pkg/kv/txn.go, line 1290 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX3nLw-KoR49jYGWDT:-MOX3nLw-KoR49jYGWDU:by2w39p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1290)):*
> ```Go
> }
> 
> // ChildTxn executes retryable in the context of a distributed transaction. The
> ```

We'll want to say more here about the interaction between the parent txn and the child txn. What happens when the child txn reads a key that the parent txn wrote to? What happens when it writes to the same key as the parent txn? Similarly, what are the answers to those questions in reverse, once the child commits and the parent begins operating again?
___
*[pkg/kv/txn.go, line 1314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWx0L8EkAxRJCS1gRO:-MOWx0L8EkAxRJCS1gRP:ba6seqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1314)):*
> ```Go
> 
> 	// TODO(ajwerner): Validate the state of the parent transaction. It should be
> 	// open (non-terminal), and a root transaction at the very least.
> ```

Yeah, this seems like a good idea.
___
*[pkg/kv/txn.go, line 1317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWxMbmB-D32HBkXcJZ:-MOWxMbmB-D32HBkXcJ_:b-ntc2z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1317)):*
> ```Go
> 
> 	kvTxn := txn.Sender().NewChildTransaction()
> 	childTxn := NewTxnFromProto(ctx, txn.db, txn.gatewayNodeID, kvTxn.ReadTimestamp, RootTxn, kvTxn)
> ```

I'm not quite sure what's going on with `txn.mu.userPriority` in this method, but I'm not sure it's going to behave correctly if `kvTxn` has a min or max priority.
___
*[pkg/kv/txn.go, line 1324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyDg86dQnQDRG2Mps:-MOWyDg86dQnQDRG2Mpt:b-jejnet) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1324)):*
> ```Go
> 	if paErr := (*roachpb.ParentAbortedError)(nil); errors.As(err, &paErr) &&
> 		paErr.ParentTxn.ID == txn.ID() {
> 		return roachpb.NewTransactionRetryWithProtoRefreshError(
> ```

Do we need to call `txn.mu.sender.ManualRestart` or `GenerateForcedRetryableError` to ensure that the parent txn's `TxnCoordSender` itself is restarted?
___
*[pkg/kv/txn.go, line 1332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyj9o5UZuusvR8NTq:-MOWyj9o5UZuusvR8NTr:b-ek7gr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1332)):*
> ```Go
> 	// a higher-level txn to be retried. We don't do this in any of the other
> 	// functions in DB; I guess we should.
> 	if errors.HasType(err, (*roachpb.TransactionRetryWithProtoRefreshError)(nil)) {
> ```

Shouldn't the child transaction have retried in `childTxn.exec` if it saw one of these errors?

Also, is `errors.Wrapf` enough to terminate the error? Won't `errors.HasType` still find the error cause?
___
*[pkg/kv/txn.go, line 1348 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJ24KARpAaHJ2zejd:-MOXJ24KARpAaHJ2zeje:b-p9x6ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/txn.go#L1348)):*
> ```Go
> 	// the child. This will also detect whether the child illegally wrote over
> 	// the parent's reads.
> 	return txn.Sender().ForwardToChild(ctx, childTxn.TestingCloneTxn())
> ```

nit: we shouldn't be using `TestingCloneTxn` in non-testing code.
___
*[pkg/kv/txn_external_test.go, line 229 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWzOFo4rQNgQ-vGG6C:-MOWzOFo4rQNgQ-vGG6D:b-eu5hi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn_external_test.go#L229)):*
> ```Go
> // that requests issued in a child transaction carry the TxnMeta of the
> // parent.
> func TestChildTransactionMetadataPropagates(t *testing.T) {
> ```

Do we need another test for various retry conditions around child and parent txns?
___
*[pkg/kv/txn_external_test.go, line 362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWztcP2h4QkepAFOTd:-MOWztcP2h4QkepAFOTe:b4xyq8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L362)):*
> ```Go
> 	//
> 	// Without any transaction timeouts, the two possible outcomes should be
> 	// either that A and its child success or that B and its child success.
> ```

`s/success/succeed/`
___
*[pkg/kv/txn_external_test.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-1iv-6KqS5BPsLAC:-MOX-1iv-6KqS5BPsLAD:bmv2lwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L365)):*
> ```Go
> 	//
> 	// There are some extreme scenarios which can happen under transaction
> 	// expiration whereby A ends up getting aborted because of a timeout and A1
> ```

What kind of timeout?
___
*[pkg/kv/txn_external_test.go, line 369 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-97y7uO5q5CUXGp6:-MOX-97y7uO5q5CUXGp7:bwoepzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L369)):*
> ```Go
> 	// could happen for both of them. We do not anticipate or allow these
> 	// scenarios.
> 	if (errA == nil && errB == nil) || (errA != nil && errB != nil) {
> ```

nit: `(errA == nil) == (errB == nil)`
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWwQ0PC6VB-vuMrppY:-MOWwQ0PC6VB-vuMrppZ:btpvtfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1153)):*
> ```Go
> 	// TODO(ajwerner): Consider stripping information from the parent proto like
> 	// LockSpans or perhaps  [...]

2020-12-17 18:56 UTC, ajwerner reviewed
Thanks for taking a look. Generally agree with your testing comments. Also agree with being more explicit about some properties in comments. Curious to explore some locking upgrade concepts to make that code clearer. 

I'll come back and take another pass on the code after we discuss some of the things here.

I think the most controversial things were:

* The protobuf design - using the transaction directly and chaining them
* The forwarding APIs - it started as simply as you imagined but being able to detect the difference between a true refresh failure and a real problem due to parent-child conflicts drove me to this API
* The various error types and handling in:
    * lock table when encountering a parent's write in a write-write conflict (or read lock-write conflict I suppose)
    * When the child detects an aborted ancestor in the txnwait.Queue


Another note is that we've come up with a case where we think we're going to want to use these child transactions in 21.1. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MOm0lKgE_oaDxWTGdQr:b-jbqk0c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/sender.go, line 302 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXIXPs4euj5EfoEbyE:-MOlt3w2-BvkoiWdt6Lj:b-gy2mqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/sender.go#L302)):*
If the parent read the keys and then the child writes, it seems that the parent should be doomed to fail. In particular, we want to make sure that the parent never causally precedes the child by the time it commits. If the parent read, then the child wrote, the child will get pushed above the parent because of the timestamp cache. That will force the parent to refresh here leading to certain failure.

>  If so, does that simplify the lock table handling?

What do you mean?
___
*[pkg/kv/sender.go, line 303 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXIgvm5CrRSPCYWeww:-MOlsfs39-nr6H69GsDh:b89wen6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/sender.go#L303)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

My immediate reaction to this signature is "why isn't this `ForwardTimestampAndRefresh`?"
</blockquote></details>

It originally was however there's a funny cases I ran into making sure we can detect bad client behavior. 
___
*[pkg/kv/txn.go, line 1317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWxMbmB-D32HBkXcJZ:-MOluLBb9HDWQh4KZzBQ:bu22ybs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not quite sure what's going on with `txn.mu.userPriority` in this method, but I'm not sure it's going to behave correctly if `kvTxn` has a min or max priority.
</blockquote></details>

The child needs to have priority at least as high as its parent. Otherwise there are some funny live-lock cases that can arise where children get aborted but parents don't and these things end up looping.  
___
*[pkg/kv/txn.go, line 1324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyDg86dQnQDRG2Mps:-MOlvrIg2g-w6eJ2nxR8:bbuzqem) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1324)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to call `txn.mu.sender.ManualRestart` or `GenerateForcedRetryableError` to ensure that the parent txn's `TxnCoordSender` itself is restarted?
</blockquote></details>

ManualRestart I think makes sense. It felt like the SQL layer was dealing with this properly but I may just be misunderstanding how this should work. 
___
*[pkg/kv/txn.go, line 1332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyj9o5UZuusvR8NTq:-MOlvMAi8qkhY6brk3EC:bh3gkui) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1332)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Shouldn't the child transaction have retried in `childTxn.exec` if it saw one of these errors?

Also, is `errors.Wrapf` enough to terminate the error? Won't `errors.HasType` still find the error cause?
</blockquote></details>

I agree this is a problem. I don't really know what error should be returned here. I don't think the parent can handle this. 
___
*[pkg/kv/txn.go, line 1348 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJ24KARpAaHJ2zejd:-MOlvCrS8E8_G0K-kmud:b-paht84) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/txn.go#L1348)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we shouldn't be using `TestingCloneTxn` in non-testing code.
</blockquote></details>

Agreed, I think I want to make it non-testing. Any issues with that or alternative suggestions?
___
*[pkg/kv/txn_external_test.go, line 229 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWzOFo4rQNgQ-vGG6C:-MOm-s5NA36AYqvk-_cu:bzeyjlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn_external_test.go#L229)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need another test for various retry conditions around child and parent txns?
</blockquote></details>

Surely
___
*[pkg/kv/txn_external_test.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-1iv-6KqS5BPsLAC:-MOm-zPy1-WU1XFZAWZ0:b-m8huve) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What kind of timeout?
</blockquote></details>

expiration like because heartbeats aren't working 
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWwQ0PC6VB-vuMrppY:-MOlwew1CfXzLm0PGIb-:b-oaj2m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1153)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A `TxnMeta` doesn't work?
</blockquote></details>

Well, for one, we need the ignored sequence numbers and we need to propagate the entire chain of ancestors. My other concern was that it would make the code that walks the ancestor chain messier. 
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWw5MW0hviLmkH7pS_:-MOlwEKJ5QYbXH2hcKx_:bon59qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't quite understand this comment. Is it assuming that priorities immediately resolve pushes one way or another? That isn't really the case – they mostly just impact who gets aborted once a deadlock has been detected.
</blockquote></details>

Correct, this is entirely in the context of deadlocks. Nevertheless, imagine the above scenario. When deciding to break a deadlock, it's the pusher that makes the determination to do the force push. If both pushers have lower priorities than the transactions which they are pushing, then there's a problem, r [...]

2020-12-17 20:33 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MOmO9mrBDYA-kPFyoLG:bngh18e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I originally just pushed the parent's write timestamp. That will eventually force a refresh. The problem is that if that refresh fails, we won't know whether that's a legitimate serializable restart or a programming bug (this case). Because we can't know which transaction caused the refresh failure, we can't just refresh unless we want all refreshes due to child pushes always fail, which seems unacceptable. 

A test that I wrote ran into this where the parent transaction just retried forever when a child had invalidated one of its reads.

One way out of this would be if we forced parents to run in a pessimistic mode with replicated locks on all reads. Then we could detect any such conflict before it happened rather than after. Of course, that doesn't seem like something that's going to happen. 
</blockquote></details>

Alright, thinking a bit more about this, it seems like if the parent is forced to do a refresh *before* the child commits and proves that that succeeds, then it feels like that could just work. It might be the case that the child gets pushed even further between the refresh and its commit but that's okay because we'll have a proof that the child didn't invalidate any of the parent reads. This also would be better because then the child wouldn't have to commit first. 

This would require:
 1) Building the machinery to force the parent to refresh eagerly
 2) Make sure to propagate a reasonable error when that refresh hits a child's intent
 3) Find a way to ensure that the EndTxn cannot happen before the parent does its stuff. Perhaps the way that happens is by having the child require that the read timestamp of the parent is at least as high as the timestamp of any intent it has written. I don't know how trivial this will be. 


<!-- Sent from Reviewable.io -->

2020-12-18 17:33 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MOquJer6fHnDw9-AY8J:b-wrxgwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Alright, thinking a bit more about this, it seems like if the parent is forced to do a refresh *before* the child commits and proves that that succeeds, then it feels like that could just work. It might be the case that the child gets pushed even further between the refresh and its commit but that's okay because we'll have a proof that the child didn't invalidate any of the parent reads. This also would be better because then the child wouldn't have to commit first. 

This would require:
 1) Building the machinery to force the parent to refresh eagerly
 2) Make sure to propagate a reasonable error when that refresh hits a child's intent
 3) Find a way to ensure that the EndTxn cannot happen before the parent does its stuff. Perhaps the way that happens is by having the child require that the read timestamp of the parent is at least as high as the timestamp of any intent it has written. I don't know how trivial this will be. 
</blockquote></details>

If we do want to push and refresh prior to committing the child, we'll need a way to do that for all of the ancestors. Perhaps this implies a need for tigher coupling of children to parents inside of the txnCoordSender. 


<!-- Sent from Reviewable.io -->

2021-01-04 16:03 UTC, nvanbenschoten reviewed
> The protobuf design - using the transaction directly and chaining them

I'm :thumbsup: on this.

> The forwarding APIs - it started as simply as you imagined but being able to detect the difference between a true refresh failure and a real problem due to parent-child conflicts drove me to this API

Yeah, I'm still not clear what the best option for this is either. It's a tricky problem. I like the idea of using refreshing to detect the conflicts so that we don't need to rely on the client having a precise memory of parent reads and child writes, but getting that to work properly is tough.

> The various error types and handling in:
> lock table when encountering a parent's write in a write-write conflict (or read lock-write conflict I suppose)

Seems like this should just be an assertion failure, right?

> When the child detects an aborted ancestor in the txnwait.Queue

I like the solution you've come up with here for this problem (`ParentAbortedError` + client-side unwinding).

> Reviewed 1 of 1 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MQD72p85qPjn30wTPr6:bs1kjd7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/sender.go, line 302 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXIXPs4euj5EfoEbyE:-MQD5jqs0O8Pt78WH-V-:b-czbj0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/sender.go#L302)):*
> What do you mean?

This was in regard to the discussion we were having in `lock_table.go`. I thought that we had to handle complex cases like Shared locks held by the parent being promoted to Exclusive locks by the child, but it sounds like we don't. In that case, we can throw an error in the lockTable whenever we find conflicts between ancestors, regardless of locking strength.
___
*[pkg/kv/txn.go, line 1317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWxMbmB-D32HBkXcJZ:-MQD6MzW491SB0VIlqKp:b-o843eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1317)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The child needs to have priority at least as high as its parent. Otherwise there are some funny live-lock cases that can arise where children get aborted but parents don't and these things end up looping.  
</blockquote></details>

Right, so what's up with `txn.mu.userPriority = roachpb.NormalUserPriority` in `NewTxnFromProto`? Is that going to break things?
___
*[pkg/kv/txn.go, line 1348 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJ24KARpAaHJ2zejd:-MQD6bpWBPvmZV7EVl8X:b-wqtlex) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/txn.go#L1348)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Agreed, I think I want to make it non-testing. Any issues with that or alternative suggestions?
</blockquote></details>

Nope, that SGTM.
___
*[pkg/kv/txn_external_test.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-1iv-6KqS5BPsLAC:-MQD16SFCj9yfs0FJLzK:b13k13o) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L365)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

expiration like because heartbeats aren't working 
</blockquote></details>

:thumbsup: maybe add that as an example here.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWwQ0PC6VB-vuMrppY:-MQD6iOI3XarmTNmXk2d:b-7rlod2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1153)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Well, for one, we need the ignored sequence numbers and we need to propagate the entire chain of ancestors. My other concern was that it would make the code that walks the ancestor chain messier. 
</blockquote></details>

Ack. I thought the ignored sequence numbers were in the TxnMeta, but it appears that they are not.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWw5MW0hviLmkH7pS_:-MQD1es02woe6swlGPAA:b-p7h6sf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1172)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Correct, this is entirely in the context of deadlocks. Nevertheless, imagine the above scenario. When deciding to break a deadlock, it's the pusher that makes the determination to do the force push. If both pushers have lower priorities than the transactions which they are pushing, then there's a problem, right?
</blockquote></details>

Yeah, I see what you're saying. So it is not safe for a child to have a lower priority than its parent. I guess that intuitively makes sense from a behavioral standpoint, but it's a good catch that this could actually cause a stall in deadlock resolution.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MQD353t-DZRDcFeVU9p:b-q5kdwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
> If we do want to push and refresh prior to committing the child, we'll need a way to do that for all of the ancestors.

We have this problem with the current approach as well, right? We're calling `ForwardToChild` on the child's immediate parent, but we should really be doing this on all of the child's ancestors.

The idea of refreshing each of a child's ancestors before the child commits seems pretty complex, but your point about infinite retries is valid. Is the idea that refreshing earlier gives us the opportunity to detect conflicts while the child's writes are still intents (i.e. still contain its ID) and therefore can still be distinguished from other transactions' intents?
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MQD4KXODyBMI0v6f9VQ:bce92qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like I'm missing something here. 
</blockquote></details>

Me too. My thought was that if we detect the illegal conflict in the lock table already, why do so here as well? We just added the intent to the lock table and we're just about to go back and scan it again.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 432 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXDNo6AE6BUB8ePC9J:-MQD51SRDibILubuPIb0:b-3vvmp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/lock_table.go#L432)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Fundamentally I think if the parent holds an exclusive lock then we should have an assertion failure. I had a hard time understanding how to make that happen so instead I allowed it to happen and then forced the assertion failure in other places. I'd love to make this interaction more explicit and fix any problems here. 
</blockquote></details>

Well all locks today are exclusive, regardless of whether they're replicated or not. I agree that we should try to make this interaction more explicit.


<!-- Sent from Reviewable.io -->

2021-01-04 16:20 UTC, ajwerner reviewed
Thanks for the look. I'm thinking that the biggest sticking point now is the forwarding behavior. I've commented on that thread. I think we should rework it to do a preemptive refresh of all ancestors prior to the committing of the child. We'll still need to forward the immediate ancestor's read timestamp after, just in case the commit still gets pushed, but we don't need that to be preemptive. Any other thoughts before I move in that direction?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MQDBGKp946u0RxY12iY:biyzatk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MQD98Ra-PdEpHhjof9k:bglsthc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
Yeah, that seems right. We currently aren't detecting issues where a grandchild invalidates a grand-parent's read. This seems like a hint that this deferred checking isn't going to cut it.

> Is the idea that refreshing earlier gives us the opportunity to detect conflicts while the child's writes are still intents (i.e. still contain its ID) and therefore can still be distinguished from other transactions' intents?

Exactly. I agree it's pretty complex but it feels like the right thing to do. I'm okay with the child committing and the parent not, there's no way to avoid that. However, I'm not that keen on the possibility of the child committing and the parent not in the case of this egregious assertion failure. I'm starting to think that the right way to spin this is to do some coupling of the child TxnCoordSender to its parent. 

Are you okay with my moving forward with the child `TxnCoordSender` holding a reference to the parent and having an interceptor which grabs the `EndTxn` and forces the parents to refresh? That will simplify the lifecycle handling in the `kv` layer and ensure that any of these bogus conflicts are detected. 


<!-- Sent from Reviewable.io -->

2021-01-05 05:38 UTC, nvanbenschoten reviewed
> Any other thoughts before I move in that direction?

I don't think so. Let's move this PR in that direction and see how it looks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MQG1H2f5SymVUp_gmwn:bdtyjor)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MQG1ZpS2LW7kBDorTOI:bivnqnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yeah, that seems right. We currently aren't detecting issues where a grandchild invalidates a grand-parent's read. This seems like a hint that this deferred checking isn't going to cut it.

> Is the idea that refreshing earlier gives us the opportunity to detect conflicts while the child's writes are still intents (i.e. still contain its ID) and therefore can still be distinguished from other transactions' intents?

Exactly. I agree it's pretty complex but it feels like the right thing to do. I'm okay with the child committing and the parent not, there's no way to avoid that. However, I'm not that keen on the possibility of the child committing and the parent not in the case of this egregious assertion failure. I'm starting to think that the right way to spin this is to do some coupling of the child TxnCoordSender to its parent. 

Are you okay with my moving forward with the child `TxnCoordSender` holding a reference to the parent and having an interceptor which grabs the `EndTxn` and forces the parents to refresh? That will simplify the lifecycle handling in the `kv` layer and ensure that any of these bogus conflicts are detected. 
</blockquote></details>

So is the proposal that we'll augment `RefreshRequest` and `RefreshRangeRequest` with a new "invalid intent ID" field? Or introduce a structured error for it to return in cases where a conflicting value/intent is detected (with a way to distinguish between the two) and then detect the illegal conflicts in the client? All things considered, the second option seems cleaner to me.

Other than that, I think child `TxnCoordSender`s holding a reference to their parent seems ok. Or at least, some slim handle to avoid the possibility of too much coupling.


<!-- Sent from Reviewable.io -->

2021-01-05 05:52 UTC, ajwerner reviewed
> I don't think so. Let's move this PR in that direction and see how it looks.

:thumbsup: let's see how it goes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MQG5b6H4Kyn-FV4Aazk:bh8mmdb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1219 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXJDZzCP4cMWPxL6_5:-MQG5DIK5eJ83g2AxGyZ:b74ibl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a34384406ab95e24106e6f3b759cf5ad7c749a3/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1219)):*
>  Or introduce a structured error for it to return in cases where a conflicting value/intent is detected (with a way to distinguish between the two) and then detect the illegal conflicts in the client? 

A structured error for sure.

>  Or at least, some slim handle to avoid the possibility of too much coupling.

Yep, I was thinking the child would hold onto an interface that allows it to preemptively push the parent and run a refresh. 


<!-- Sent from Reviewable.io -->

2021-01-25 15:36 UTC, ajwerner reviewed
@nvanbenschoten I reworked the pushing bits to have the child push its ancestors. It's honestly pretty messy. I haven't yet gone back to deal with the lock table.  I ended up augmenting the refresh requests to include the set of descendants. It's not terrible. I'd love to get your take on this as it is before making another pass. The interfaces are not making me very happy. You tend to have a way with these things. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MRu9orOC93HRVPpNYqO:b2by4av)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/txn.go, line 1317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWxMbmB-D32HBkXcJZ:-MRs41aV6fNdRa9dwPGi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Right, so what's up with `txn.mu.userPriority = roachpb.NormalUserPriority` in `NewTxnFromProto`? Is that going to break things?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 154 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXGlwE3dZnkeATHsJv:-MRsCjLf59XEr33QPGVr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/lock_table_test.go#L154)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: drop this below `new-txn`
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_history_test.go, line 1007 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX3J5g4sE_-KlZsY4j:-MRs4gdT9a6eKe3FDLNp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e269861f581ba888ce02de7edcf6759fdc5c9b65/pkg/storage/mvcc_history_test.go#L1007)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this below `newTxn`
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 471 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX4zTH5pIQ3jOGpDdq:-MRs4UqU9GuhIWqkFyNl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e269861f581ba888ce02de7edcf6759fdc5c9b65/pkg/storage/pebble_mvcc_scanner.go#L471)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`12`?
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 489 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX4gVg8Cjpo2BDXSpI:-MRs4PggBk20MoRhpTYI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e269861f581ba888ce02de7edcf6759fdc5c9b65/pkg/storage/pebble_mvcc_scanner.go#L489)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The second sentence makes it sound like the return values are only set if the intent is owned by the reading transaction and not one of its parents. Consider updating this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-26 18:29 UTC, nvanbenschoten reviewed
One thing I'm trying to determine is whether we need to take into consideration server-side refreshes, which could raise the commit timestamp of a child transaction after the point at which we refresh all ancestors. If that's an issue, then this kind of pre-commit hook isn't going to work out.

I see why we arrived where we did here, but it's all starting to become pretty heavyweight. This makes me think you may have had things right earlier on, when you compared the write footprint of the child transaction after committing with the refresh spans of each ancestor transaction and called it a day. Since this is all in service of detecting programming errors, it feels a little wrong to be doing something so expensive and to add so much new logic in. Which way are you leaning on all of this? It sounds like you aren't too happy with the recursion in the txn_coord_sender.

> Reviewed 1 of 29 files at r10, 3 of 6 files at r12, 3 of 4 files at r15, 3 of 4 files at r17, 3 of 4 files at r18, 1 of 1 files at r19, 1 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MRzugLX0wNXxi9MbinE:b-yv7oeb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 183 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MRztJ2ICSisTKkke8BX:-MRztJ2ICSisTKkke8BY:b-13d9sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b6645f87fe0f95de385b4fa44aa0f249010a53/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L183)):*
> ```Go
> 		return nil
> 	}
> 	updated, err := tc.interceptorAlloc.forceRefreshLocked(ctx, txn, childrenIDs...)
> ```

nit here and below: calling the method/access fields on the `interceptorAlloc` itself is pretty confusing. Consider referencing the specific interceptor directly, like we do elsewhere in this file.
___
*[pkg/roachpb/api.proto, line 1591 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MRzwlL53VzYzLH6uumq:-MRzwlL53VzYzLH6uumr:bqzbbwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b6645f87fe0f95de385b4fa44aa0f249010a53/pkg/roachpb/api.proto#L1591)):*
> ```protobuf
>   // their descendants. Encountering such an intent must trigger an assertion
>   // failure as it is a programming error.
>   repeated bytes descendant_txns = 4 [(gogoproto.customtype) = "github.com/cockroachdb/cockroach/pkg/util/uuid.UUID"];
> ```

If we're already returning the conflicting intent in a structured `RefreshFailedError`, why do we also need to send this in the request itself? Can't we make a determination about this on the client by looking at the `RefreshFailedError`?


<!-- Sent from Reviewable.io -->

2021-01-26 18:37 UTC, ajwerner reviewed
> One thing I'm trying to determine is whether we need to take into consideration server-side refreshes, which could raise the commit timestamp of a child transaction after the point at which we refresh all ancestors. If that's an issue, then this kind of pre-commit hook isn't going to work out.

Makes sense. I was worried about something like that and was thinking about splitting off the `EndTxn` to deal with it. This is especially a problem if the final batch of contains a write that would do the invalidating. I'm somewhat unhappy with the post-commit hook to forward the parent. I'm not upset about the recursion per se, but I'm upset that the recursion potentially runs recursive RPCs.

What if we did a hybrid of all of this where the child hangs on to a handle to its parent (and thus all of its ancestors) and then, upon commit `EndTxn`, ensures that the set of writes do not invalidate any parent reads. It's almost the same as the old approach except that it removes the crufty API from the `kv.TxnSender`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MRzxrXfDpuHH29olusE:b-9pe4d0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1591 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MRzwlL53VzYzLH6uumq:-MRzyxUmBxw0UqKDk6Lq:bgh8ibf) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b6645f87fe0f95de385b4fa44aa0f249010a53/pkg/roachpb/api.proto#L1591)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we're already returning the conflicting intent in a structured `RefreshFailedError`, why do we also need to send this in the request itself? Can't we make a determination about this on the client by looking at the `RefreshFailedError`?
</blockquote></details>

The issue is that there might be multiple violating intents and we want to make sure to discover the right one. That might just be premature optimization given this is all about detecting a programming error. 


<!-- Sent from Reviewable.io -->

2021-01-26 20:15 UTC, nvanbenschoten reviewed
> What if we did a hybrid of all of this where the child hangs on to a handle to its parent (and thus all of its ancestors) and then, upon commit EndTxn, ensures that the set of writes do not invalidate any parent reads. It's almost the same as the old approach except that it removes the crufty API from the kv.TxnSender.

This approach sounds reasonable to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MS-K-fYAQU4EJxaN1MP:bwh0hsy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1591 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MRzwlL53VzYzLH6uumq:-MS-K8MK6RZ7-tvJqPT9:b-mhrfy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b6645f87fe0f95de385b4fa44aa0f249010a53/pkg/roachpb/api.proto#L1591)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The issue is that there might be multiple violating intents and we want to make sure to discover the right one. That might just be premature optimization given this is all about detecting a programming error. 
</blockquote></details>

Yeah, I would think that we would only need to reject due to a programming error if we _only_ ran into our child's intent. Otherwise, we're also seeing a real conflict, so we're either not in an infinite retry loop (meaning we'll find the programming error after a retry) or we have other real issues.


<!-- Sent from Reviewable.io -->

2021-02-01 07:10 UTC, ajwerner reviewed
Alright, this is RFAL. 

The lock table stuff is now simplified and more explicit but it still deserves more scrutiny. Maybe I can get @sumeerbhola to sign off. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MSRQGON8XYOVvcvny0m:b-4zzje3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn.go, line 1332 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyj9o5UZuusvR8NTq:-MSPk_3w3NrVX8CGhrBZ:b-fhyw18) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1332)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I agree this is a problem. I don't really know what error should be returned here. I don't think the parent can handle this. 
</blockquote></details>

I just removed this. It wasn't doing anything valuable. 
___
*[pkg/kv/txn_external_test.go, line 362 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWztcP2h4QkepAFOTd:-MSPlMP47ZM2iDgQJhoG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L362)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/success/succeed/`
</blockquote></details>

Done.
___
*[pkg/kv/txn_external_test.go, line 365 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-1iv-6KqS5BPsLAC:-MSPlN4IDClVofJtZyEj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:thumbsup: maybe add that as an example here.
</blockquote></details>

Done.
___
*[pkg/kv/txn_external_test.go, line 369 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-97y7uO5q5CUXGp6:-MSPlNiE4GZ9e9Kh48uq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/txn_external_test.go#L369)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `(errA == nil) == (errB == nil)`
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 1172 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWw5MW0hviLmkH7pS_:-MSREA99E-tKj9Ldcm5u:b-unzt6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1172)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I see what you're saying. So it is not safe for a child to have a lower priority than its parent. I guess that intuitively makes sense from a behavioral standpoint, but it's a good catch that this could actually cause a stall in deadlock resolution.
</blockquote></details>

This has been pulled into the TxnCoordSender. 
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 183 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MRztJ2ICSisTKkke8BX:-MSPzKsD6SA_m0lPEi1u:b-cxchxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/18b6645f87fe0f95de385b4fa44aa0f249010a53/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L183)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit here and below: calling the method/access fields on the `interceptorAlloc` itself is pretty confusing. Consider referencing the specific interceptor directly, like we do elsewhere in this file.
</blockquote></details>

No longer relevant.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MSPzTiSE_YPJbxugM21:b-qgf8j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Me too. My thought was that if we detect the illegal conflict in the lock table already, why do so here as well? We just added the intent to the lock table and we're just about to go back and scan it again.
</blockquote></details>

I moved this above adding the discovered lock. I do think this still needs to be here as the lock table doesn't have a complete view. 
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 432 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXDNo6AE6BUB8ePC9J:-MSRDn89EkrgpQ1qw_yd:b-gjpx6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/lock_table.go#L432)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Well all locks today are exclusive, regardless of whether they're replicated or not. I agree that we should try to make this interaction more explicit.
</blockquote></details>

Okay, made it all more explicit.
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 50 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXGujrANG7crKbNftZ:-MSPlmSz8d1g7xncD6jn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/lock_table_test.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment about the new `new-child-txn` directive.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/testdata/lock_table/child_txn, line 3 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHMjk1FjXOq_zgY7n:-MSRDjMe-Pfbw-zSOAAT:bo619dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/testdata/lock_table/child_txn#L3)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Added some more testing and clarified the behavior here. 
___
*[pkg/kv/kvserver/txnwait/queue.go, line 140 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX-Sn09fN6Dt_tyA5x:-MSRGFoQATImD39oQ6iB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/kvserver/txnwait/queue.go#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this line a comment. It's pretty subtle.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/txnwait/queue.go, line 484 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX0JM82ossxibJTzaA:-MSRGgN88RhMLEYkbz70:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5c4165e7fe6f2209cdb35845470007b865fbae7/pkg/kv/kvserver/txnwait/queue.go#L484)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's keep/adapt this comment.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/txnwait/queue.go, line 500 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX0YZa78Y927HaznNJ:-MSRHu8Y2cg5jICobAkI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/263a2e70a3fe42ec549822be6bee7919593469a6/pkg/kv/kvserver/txnwait/queue.go#L500)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider pulling this into a helper and sharing that with `getNumPusherTxnsToTrack`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/txnwait/queue.go, line 683 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOX2Oqx0b3HEyE2wCBA:-MSRI63I1RaadMQLSKvM:b11x3hf) ([raw file](https://github.com/cockroachdb/cockroach/blob [...]

2021-02-01 17:18 UTC, sumeerbhola reviewed
> Reviewed 1 of 4 files at r25, 1 of 7 files at r26, 1 of 6 files at r27.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/txn.go, line 1291 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTUKh78d4XQuMGbejj:-MSTUKh78d4XQuMGbejk:b-rcs7gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1291)):*
> ```Go
> // from recoverable internal errors, and is automatically committed
> // otherwise. The retryable function should have no side effects which could
> // cause problems in the event it must be run more than once.
> ```

does this "run more than once" include "run and committed more than once", i.e., do the writes need to be idempotent?
___
*[pkg/kv/txn.go, line 1300 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTRMVnCZpqjL9nSRe6:-MSTRMVnCZpqjL9nSRe7:bk6qh9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1300)):*
> ```Go
> //
> //   * No concurrent operations may be performed on the parent transaction.
> //   * The child transaction must not invalidate any reads of the parent.
> ```

so it can't write to any keys that the parent has already read? Is this beyond the protection that the ts cache gives us? I am assuming this includes the case where the child txn is writing at a higher timestamp, which the ts cache will allow, but we are explicitly saying it should not do so.

But it could write to keys that the parent will read after the child commits?

Without some documented constraints on the "read set compression", I am not sure how the child txn can do any writes. Can we document them here?

What if the parent has acquired an unreplicated exclusive lock that has been forgotten. We can't guarantee an assertion failure.

In practice do we need many levels of ancestors or will this be used with only 2-levels? If the latter, can the overall code be simplified under that constraint.
___
*[pkg/kv/txn.go, line 1318 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTSu784O3Oye0wmn3O:-MSTSu784O3Oye0wmn3P:bj63ewt) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1318)):*
> ```Go
> //     if the parent is aborted during deadlock detection and the child observes
> //     that it has been aborted, the child will also be aborted and the parent
> //     will encounter a retry.
> ```

This behavior is not needed for correctness, yes?
___
*[pkg/kv/txn.go, line 1323 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTTDFJ9AOh-dWLXltK:-MSTTDFJ9AOh-dWLXltL:b-1gdsag) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1323)):*
> ```Go
> //     timestamp of the parent.
> //   * The child may commit values which the parent subsequently reads. This is
> //     fine and can be desirable.
> ```

These committed values are observable by other unrelated txns that are concurrent, yes?
So is the only thing that makes the parent-child relationship special the one-way information transfer from the parent to the child of writes by the parent being observed by the child? The other direction of information is just whether the child committed or not, which the parent would know about if it used a non-child transaction?

(I'm asking things that were probably documented in the RFC, but I've swapped out some of that state, and I am guessing some things may have changed since the RFC)
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MSTYQGD6bSbFArNB6jQ:b-vcxdeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I moved this above adding the discovered lock. I do think this still needs to be here as the lock table doesn't have a complete view. 
</blockquote></details>

This seems reasonable.
Will the `parentIntentError` cause this `Request` to stop evaluating and call `FinishReq`? Do we want the call to `AddDiscoveredLock` when this error occurs?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MST_ACSCjrwVliktYHs:b8s7g55) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
> ```Go
> // will result in an assertion failure error. This is consistent with the
> // rules of child transactions which state that descendants my not acquire
> // exclusive locks or write underneath the reads or writes of any ancestors.
> ```

What if the descendent is writing above a read of the ancestor? We can't detect it here, yes?

Since the lock table is incomplete wrt both replicated and unreplicated locks, and this write-write conflict seems mainly an error check against our internal use of child transactions, I am wondering whether we need to make any changes to the lock table at all and just treat an ancestor txn lock as equivalent to the child txn already holding the lock. Then the evaluation will pick up any errors via the `parentIntentError` path.

We're also introducing optimistic locking where the checking happens after evaluation https://github.com/cockroachdb/cockroach/pull/58670, so I'm trying to see what changes are essential to the lock table and what are optional (to reduce its complexity as much as possible).

I'm probably missing some subtlety here.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 92 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTVVXH0IMkb04KouM9:-MSTVVXH0IMkb04KouMA:b-3uk17p) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/storage/pebble_mvcc_scanner.go#L92)):*
> ```Go
> // Go port of mvccScanner in libroach/mvcc.h. Stores all variables relating to
> // one MVCCGet / MVCCScan call.
> type pebbleMVCCScanner struct {
> ```

Do we only need changes to `pebbleMVCCScanner` in the MVCC path since the only special handling for child txns is the write => read data transfer from parent to child?
I keep forgetting that even `MVCCGet` uses `pebbleMVCCScanner`. The code comment for this struct is both dated and  insufficient. Could you add another sentence saying that `pebbleMVCCScanner` must be used for all Gets and Scans since it correctly handles child transactions.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 373 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTWPUB1986UrkvZBUn:-MSTWPUC3cgcEVXo0u66:b-ixt8zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/storage/pebble_mvcc_scanner.go#L373)):*
> ```Go
> 	}
> 
> 	ownIntent, epoch, seqNum, ignoredSeqNums := p.ownsIntent()
> ```

How does the `epoch` and `seqNum` of the child txn relate to that of the parent? I am guessing it is derived from the parent since we are continuing to do comparisons like `seqNum >= p.meta.Txn.Sequence` and `epoch == p.meta.Txn.Epoch`. Is this already documented elsewhere in the code (I didn't look at the whole PR)?

And this works because of the "No concurrent operations may be performed on the parent transaction"?


<!-- Sent from Reviewable.io -->

2021-02-01 19:09 UTC, ajwerner reviewed
@sumeerbhola I'm replying to your comments before addressing the ones which indicate the clear action to keep the conversation going. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MSTzkHV0fXYyHRTRN36:bba80ii)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/txn.go, line 1291 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTUKh78d4XQuMGbejj:-MSTyd4NAthYXr2Fd0PX:by0p6fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1291)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

does this "run more than once" include "run and committed more than once", i.e., do the writes need to be idempotent?
</blockquote></details>

No, it does not mean run and commit more than once. It's trying to express the same behavior as `(*kv.DB).Txn()`.
___
*[pkg/kv/txn.go, line 1300 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTRMVnCZpqjL9nSRe6:-MSTiJap6v5x_d_OfoCt:ba4bb71) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1300)):*
> Without some documented constraints on the "read set compression", I am not sure how the child txn can do any writes. Can we document them here?

This is a fair and valid point. If the refresh_span_bytes were to be set to zero, child transactions which get pushed can never commit. If the child never gets pushed, there's no problem. If the child were to invalidate the write of an ancestor, it would have to be pushed.

If I read the span condensing logic correctly, we'll never add span bounds which we've not added. For example, we won't pick up spans which are outside of the spans which were read. Say we had `AB-AC`,`AD-AE`,`AF-AG` We might compress that to `AB-AG` but I don't think we'll ever change the bounds to `A-B`. 

The principle this ends up with is that if you want to be safe, never write to any of the same table spans in child transactions that the parent has read from and even then don't read from tables which might be in-between tables that the parent has read from. This ends up being both quite restrictive and yet good enough for the use-cases I currently envision. We could probably tighten this up to change the span compression logic to not cross table boundaries. 

>In practice do we need many levels of ancestors or will this be used with only 2-levels? If the latter, can the overall code be simplified under that constraint.

I don't have an immediate use-case for more than one layer. @nvanbenschoten proposed the generalization. I'm not sure that it does too much to simplify any of the code. 
___
*[pkg/kv/txn.go, line 1318 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTSu784O3Oye0wmn3O:-MSTiHVd-cjiCqq4xpNp:b-1dcquh) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1318)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This behavior is not needed for correctness, yes?
</blockquote></details>

Correct. 
___
*[pkg/kv/txn.go, line 1323 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTTDFJ9AOh-dWLXltK:-MSTg0os1vf-bCVD0m_8:b-rjaymj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1323)):*
> These committed values are observable by other unrelated txns that are concurrent, yes?

Right

> So is the only thing that makes the parent-child relationship special the one-way information transfer from the parent to the child of writes by the parent being observed by the child? The other direction of information is just whether the child committed or not, which the parent would know about if it used a non-child transaction?

Yes, well that and the parent will be pushed to the child's commit timestamp so that it cannot commit under the parent. Ideally if code needs information to transfer from the child back to the parent, it will do it through the closure. 
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MSTyrjg36JoayNmpKYZ:bf4hpty) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This seems reasonable.
Will the `parentIntentError` cause this `Request` to stop evaluating and call `FinishReq`? Do we want the call to `AddDiscoveredLock` when this error occurs?
</blockquote></details>

Before this most recent revision, we were calling `AddDiscoveredLock`. I don't think it's a correctness problem either way, right?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MSTz-sn8F6LYKUfFFh-:bp5mrke) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What if the descendent is writing above a read of the ancestor? We can't detect it here, yes?

Since the lock table is incomplete wrt both replicated and unreplicated locks, and this write-write conflict seems mainly an error check against our internal use of child transactions, I am wondering whether we need to make any changes to the lock table at all and just treat an ancestor txn lock as equivalent to the child txn already holding the lock. Then the evaluation will pick up any errors via the `parentIntentError` path.

We're also introducing optimistic locking where the checking happens after evaluation https://github.com/cockroachdb/cockroach/pull/58670, so I'm trying to see what changes are essential to the lock table and what are optional (to reduce its complexity as much as possible).

I'm probably missing some subtlety here.
</blockquote></details>

We detect the descendant writing over an ancestor's read at commit time by comparing the writes of the descendant to the read spans of its ancestors. All of this is just a protection against programming errors so I'd like it to be minimally disruptive. 
___
*[pkg/storage/pebble_mvcc_scanner.go, line 92 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTVVXH0IMkb04KouM9:-MSTzJM_ByrCePsFlaC5:b-bqk2nu) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/storage/pebble_mvcc_scanner.go#L92)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we only need changes to `pebbleMVCCScanner` in the MVCC path since the only special handling for child txns is the write => read data transfer from parent to child?
I keep forgetting that even `MVCCGet` uses `pebbleMVCCScanner`. The code comment for this struct is both dated and  insufficient. Could you add another sentence saying that `pebbleMVCCScanner` must be used for all Gets and Scans since it correctly handles child transactions.
</blockquote></details>

Will do. 
___
*[pkg/storage/pebble_mvcc_scanner.go, line 373 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTWPUB1986UrkvZBUn:-MSTzPho5uwpHZr5ga9I:b602j70) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/storage/pebble_mvcc_scanner.go#L373)):*
I'll comment `ownsIntent()` to better explain what's going on. The idea is that the descendant is viewing the parent's writes as though it were the ancestor as of the snapshot of the ancestor when the child is created.

> And this works because of the "No concurrent operations may be performed on the parent transaction"?

Indeed.


<!-- Sent from Reviewable.io -->

2021-02-01 23:44 UTC, nvanbenschoten reviewed
The approach looks good to me now! Thanks for iteratively refining this.

> Reviewed 2 of 32 files at r21, 6 of 6 files at r22, 3 of 7 files at r23, 3 of 4 files at r24, 4 of 4 files at r25, 6 of 7 files at r26, 5 of 6 files at r27, 2 of 2 files at r28.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MSUxfG290o-ub_dgWct:b9exxkf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/txn.go, line 1324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyDg86dQnQDRG2Mps:-MSUyKYJC4_5mDCYulFa:b501o85) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1324)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

ManualRestart I think makes sense. It felt like the SQL layer was dealing with this properly but I may just be misunderstanding how this should work. 
</blockquote></details>

Did you get a chance to confirm that the SQL layer is handling this correctly?
___
*[pkg/kv/txn.go, line 1318 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTSu784O3Oye0wmn3O:-MSTvwVK5XBgV_Pezdti:b-db6d7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1318)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This behavior is not needed for correctness, yes?
</blockquote></details>

I don't think so. It would be impossible to guarantee.
___
*[pkg/kv/txn.go, line 1323 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTTDFJ9AOh-dWLXltK:-MSTwB7J87rbVbqH_STX:bdgaud9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1323)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

These committed values are observable by other unrelated txns that are concurrent, yes?
So is the only thing that makes the parent-child relationship special the one-way information transfer from the parent to the child of writes by the parent being observed by the child? The other direction of information is just whether the child committed or not, which the parent would know about if it used a non-child transaction?

(I'm asking things that were probably documented in the RFC, but I've swapped out some of that state, and I am guessing some things may have changed since the RFC)
</blockquote></details>

The other thing that makes the relationship special is its impact on deadlock detection between transactions. Parent transactions have an implicit dependency on their children transactions.
___
*[pkg/kv/txn_external_test.go, line 233 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUlzatCoPEyAwLRW7O:-MSUlzatCoPEyAwLRW7P:b-ab92i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn_external_test.go#L233)):*
> ```Go
> func TestChildTransactionMetadataPropagates(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	//defer log.Scope(t).Close(t)
> ```

Did you mean to uncomment this?
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 159 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUn1AU2-t49xbJKMZ-:-MSUn1AU2-t49xbJKMZ0:b-1zk30a) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L159)):*
> ```
> both in the txnSpanRefresher
> ```

This part isn't true anymore, right?
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 170 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUmWwr9BpFPmhfoQbA:-MSUmWws05YyNd5JAwq2:b-4p2gji) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L170)):*
> ```Go
> //     error.
> //
> // Note that if the commitCommitTimestamp is equal to the parent's current
> ```

`childCommitTimestamp`
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 828 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUnND9BA5lAVTjqUIQ:-MSUnND9BA5lAVTjqUIR:b-iwpl9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L828)):*
> ```Go
> 		tc.mu.txn.Update(br.Txn)
> 		if justCommitted {
> 			return roachpb.NewError(tc.pushParentUponCommitLocked(ctx))
> ```

It seems like this should live near `maybeSleepForLinearizable`, maybe in some method that handles post-commit actions. And `commitReadOnlyTxnLocked` should also call this post-commit hook.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 2415 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUnr2v-Ax8Qp_Lh4aG:-MSUnr2w44vgvhh5phnU:b-wunvh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2415)):*
> ```Go
> 	require.NotNil(t, child.Parent)
> 	require.Equal(t, parent.ID, child.Parent.ID)
> 	require.Equal(t, parent.Name+" child", child.Name)
> ```

nit: are we ok with the recursive " child"s on grandchildren?
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 275 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUpXoiCKQ4H0eLC977:-MSUpXoiCKQ4H0eLC978:b-mrmv9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L275)):*
> ```Go
> 	ts      hlc.Timestamp
> 	spans   *spanset.SpanSet
> 	readTS  hlc.Timestamp
> ```

I think these are leftovers from a bad rebase. They were removed a few weeks go.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 453 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUq1wA3Yg9lDa0lY57:-MSUq1wA3Yg9lDa0lY58:b-8rwyue) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L453)):*
> ```Go
> // ReadWrite requests due to descendants seeking to acquire locks over ancestors
> // will result in an assertion failure error. This is consistent with the
> // rules of child transactions which state that descendants my not acquire
> ```

"may"
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 55 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUr1Mv8pP4FWXeW4Fa:-MSUr1Mv8pP4FWXeW4Fb:bkfq93b) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table_test.go#L55)):*
> ```Go
>  Creates a Transaction.
> 
> new-child-txn parent=<name> txn=<name> ts=<int>[,<int>] epoch=<int> [seq=<int>]
> ```

Feel free to ignore, but would it be easier and result in less duplicate code to add an optional `parent` field to `new-txn`?
___
*[pkg/kv/kvserver/txnwait/queue_test.go, line 491 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUwks44vgiOAo43LzN:-MSUwks44vgiOAo43LzO:b1cbgk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/txnwait/queue_test.go#L491)):*
> ```Go
> }
> 
> // noopT implements assert.TestingT so that its tests can be used without
> ```

:expandingbrain:
___
*[pkg/roachpb/data.proto, line 410 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUx41p5IbhXNzt7fCx:-MSUx41p5IbhXNzt7fCy:b-w64rgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/roachpb/data.proto#L410)):*
> ```protobuf
>   // STAGING to COMMITTED. Because of this, the set will only ever contain
>   // entries when the transaction is STAGING. For more, see txnCommitter. It
>   // may be the case that InFlightWrites is populated in a transaction which
> ```

Mind changing "in a transaction which" to "in a transaction object which"? This took me a secon [...]

2021-02-02 00:10 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MSV2Hmm9HkHqiLeDx08:b-j0xxwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Before this most recent revision, we were calling `AddDiscoveredLock`. I don't think it's a correctness problem either way, right?
</blockquote></details>

Yes, its harmless to call `AddDiscoveredLock` even if this request is never going to go and wait at that lock.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MSV2tXG2QVUat_kMGSQ:bw3el9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We detect the descendant writing over an ancestor's read at commit time by comparing the writes of the descendant to the read spans of its ancestors. All of this is just a protection against programming errors so I'd like it to be minimally disruptive. 
</blockquote></details>

Are you saying we don't actually need any changes to `lock_table.go` other than making the parent txn appear equivalent to the child wrt the child not waiting on the parent's locks? That is, is my supposition that the detection of bad behavior via `parentIntentError`, actually sufficient?


<!-- Sent from Reviewable.io -->

2021-02-02 06:03 UTC, ajwerner reviewed
Seems like the sticking point here is going to be the lock table changes. I don't feel strongly either way. I think the error propagation changes in the PR are sort of ugly, but they do at least make some of the interactions more explicit. Until we offer lock strengths weaker than exclusive, I think just letting children pass through under locks held by ancestors works well. If the ancestor were to hold a shared lock, I think the interactions get less clear. 

> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-:-MSWKM9NAH9DXeb8hnSy:bk7s8dh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/txn.go, line 1324 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOWyDg86dQnQDRG2Mps:-MSWAYhK8T3G_9gimdvx:bz13z6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4867c78d491b0b3e55788da0c97cc78f2c62c7a/pkg/kv/txn.go#L1324)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you get a chance to confirm that the SQL layer is handling this correctly?
</blockquote></details>

Added a test that shows that it behaves properly. 
___
*[pkg/kv/txn.go, line 1323 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSTTDFJ9AOh-dWLXltK:-MSV7lbS8X-FBBDr7sEs:bg1ek4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn.go#L1323)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The other thing that makes the relationship special is its impact on deadlock detection between transactions. Parent transactions have an implicit dependency on their children transactions.
</blockquote></details>

Right, that's sort of the most important part. 
___
*[pkg/kv/txn_external_test.go, line 233 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUlzatCoPEyAwLRW7O:-MSWAeT_Do2sPvT717sP:b60r506) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/txn_external_test.go#L233)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to uncomment this?
</blockquote></details>

Yes, done.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 159 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUn1AU2-t49xbJKMZ-:-MSWFIfXCLotXWBs9hbA:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L159)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> both in the txnSpanRefresher
> ```

This part isn't true anymore, right?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 170 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUmWwr9BpFPmhfoQbA:-MSWAqKX6fBD9MoAELGb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L170)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`childCommitTimestamp`
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender.go, line 828 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUnND9BA5lAVTjqUIQ:-MSWBLAa81TFwQIZybaW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L828)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It seems like this should live near `maybeSleepForLinearizable`, maybe in some method that handles post-commit actions. And `commitReadOnlyTxnLocked` should also call this post-commit hook.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go, line 2415 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUnr2v-Ax8Qp_Lh4aG:-MSWBO1q4cEUjMjEtE2S:bhwpqsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go#L2415)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: are we ok with the recursive " child"s on grandchildren?
</blockquote></details>

I am. It's at least pretty clear. I don't know when we're going to have grandchildren.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 268 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MOXHU2_74Beo6vBgJ_Q:-MSWBcEJ0jlA48kNU4PF:bp3aow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/30037f1c1ae43a1e9ece698ae5816f8e39462d75/pkg/kv/kvserver/concurrency/concurrency_manager.go#L268)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, its harmless to call `AddDiscoveredLock` even if this request is never going to go and wait at that lock.
</blockquote></details>

Reverted.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 275 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUpXoiCKQ4H0eLC977:-MSWFTpX5iLbEjmA3foh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L275)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think these are leftovers from a bad rebase. They were removed a few weeks go.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 453 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUq1wA3Yg9lDa0lY57:-MSWFdjW2vrIgv_T178B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L453)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"may"
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MSWBiV80bJ4JmZKM0an:b-6lbbhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are you saying we don't actually need any changes to `lock_table.go` other than making the parent txn appear equivalent to the child wrt the child not waiting on the parent's locks? That is, is my supposition that the detection of bad behavior via `parentIntentError`, actually sufficient?
</blockquote></details>

My original implementation was exactly what I think you're saying. It just made child transactions appear equivalent to the parent in the lock table and then any issues were caught in the `HandleWriteIntentError`. @nvanbenschoten felt that this was too implicit so I added the more explicit error checking here. 

This is what that commit looked like (the testing was bogus but otherwise, I do think it was okay and simpler): https://github.com/cockroachdb/cockroach/commit/30037f1c1ae43a1e9ece698ae5816f8e39462d75
___
*[pkg/kv/kvserver/concurrency/lock_table_test.go, line 55 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSUr1Mv8pP4FWXeW4Fa:-MSWCBfEE3WCm-nKFqEB:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table_test.go#L55)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Feel free to ignore, but would it be easier and result in less duplicate code to add a [...]

2021-02-03 16:48 UTC, nvanbenschoten reviewed
> Reviewed 1 of 31 files at r29, 6 of 6 files at r30, 3 of 7 files at r31, 3 of 4 files at r32, 4 of 4 files at r33, 7 of 7 files at r34, 5 of 6 files at r35, 2 of 2 files at r36.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MScjvOEDjIsLzJXxHir:b-tagsr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My original implementation was exactly what I think you're saying. It just made child transactions appear equivalent to the parent in the lock table and then any issues were caught in the `HandleWriteIntentError`. @nvanbenschoten felt that this was too implicit so I added the more explicit error checking here. 

This is what that commit looked like (the testing was bogus but otherwise, I do think it was okay and simpler): https://github.com/cockroachdb/cockroach/commit/30037f1c1ae43a1e9ece698ae5816f8e39462d75
</blockquote></details>

The hazard I was concerned with was allowing a child txn to acquire a replicated lock on top of their parent's unreplicated lock, the `(3) | u | r` case from that ref. The semantics of such a lock acquisition are not clear to me. Do we replace the parent's unreplicated lock with the child's replicated lock? What then happens when the child commits? Does the parent lose its lock? It's not clear how the `lockHolderInfo` structure can even represent such a lock state.

Maybe I missed an implied "we don't care about corrupting a `lockHolderInfo` because this is an error case anyway and no one should be able to commit".

I agree that we should get to a place that we're all happy with here, as @sumeerbhola's point about this needing to interact well with optimistic locking is very valid.


<!-- Sent from Reviewable.io -->

2021-02-03 19:37 UTC, sumeerbhola requested changes
> Reviewed 1 of 4 files at r33, 6 of 7 files at r34.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 464 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdCvk81uL6Zl6vH3rq:-MSdCvk81uL6Zl6vH3rr:bxyfnrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/concurrency_control.go#L464)):*
> ```Go
> 	// The returned error indicates illegal operations by descendant transactions
> 	// interacting with their ancestors' locks. It is illegal for a descendant to
> 	// try to acquire a lock that overlaps with any of its descendants.
> ```

I think the "it is illegal" statement should say that the descendant should not have a `SpanReadWrite` span that overlaps with an Exclusive lock held by an ancestor.
___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 601 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdE3-P8ixV4hpbSiJA:-MSdE3-P8ixV4hpbSiJB:b-o00q55) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/concurrency_control.go#L601)):*
> ```Go
> 	// CurState returns the latest waiting state. It returns an error if the
> 	// lock which was encountered is not allowed as it is due to an ancestor
> 	// transaction.
> ```

(nit: to be more consistent with the earlier comment)

... was encountered is illegal for this descendant transaction to conflict with, since it is held by an ancestor transaction. 
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 168 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdEcKI2oiWeQSi9FUw:-MSdEcKI2oiWeQSi9FUx:b-kpc15d) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/concurrency_manager.go#L168)):*
> ```Go
> 		// Scan for conflicting locks.
> 		log.Event(ctx, "scanning lock table for conflicting locks")
> 		g.ltg, _ = m.lt.ScanAndEnqueue(g.Req, g.ltg)
> ```

why is this ignoring the error return value?
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 274 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdF-nLAEb-2oe1PRbU:-MSdF-nLAEb-2oe1PRbV:b-tr5ocb) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/concurrency_manager.go#L274)):*
> ```Go
> 			wait = true
> 		}
> 		for cur := g.Req.Txn; cur != nil && parentIntentError == nil; cur = cur.Parent {
> ```

Can you add a comment before this for loop
// The lock table detects an illegal conflict with the parent, in a manner similar to this parentIntentError computation.  So usually going back and waiting at the lock table after calling AddDiscoveredLock would be good enough, and we would not need to do this computation here. However, the lockTable may not be enabled, which would prevent that detection. So we make sure by computing parentIntentError.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 454 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MST_ACSCjrwVliktYHr:-MSdLL570pq6qFv5t1cE:b-7ygnck) ([raw file](https://github.com/cockroachdb/cockroach/blob/00101e6d5317ff60c79a500ec4e9ce7d851fbd55/pkg/kv/kvserver/concurrency/lock_table.go#L454)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The hazard I was concerned with was allowing a child txn to acquire a replicated lock on top of their parent's unreplicated lock, the `(3) | u | r` case from that ref. The semantics of such a lock acquisition are not clear to me. Do we replace the parent's unreplicated lock with the child's replicated lock? What then happens when the child commits? Does the parent lose its lock? It's not clear how the `lockHolderInfo` structure can even represent such a lock state.

Maybe I missed an implied "we don't care about corrupting a `lockHolderInfo` because this is an error case anyway and no one should be able to commit".

I agree that we should get to a place that we're all happy with here, as @sumeerbhola's point about this needing to interact well with optimistic locking is very valid.
</blockquote></details>

I see. In light of this I am fine with the change here. It won't complicate optimistic locking, I think. An optimistically evaluated request by a descendant will discover an error due to an unreplicated lock by the ancestor, after it evaluates (when it goes to check the lock table).
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 446 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdHkdVBciIRfftyMjv:-MSdHkdVBciIRfftyMjw:b-k993b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/lock_table.go#L446)):*
> ```Go
> }
> 
> // isAncestorTxn returns true if txn corresponds any of the ancestors of the
> ```

... if txn is an ancestor of the txn in g.
___
*[pkg/kv/kvserver/concurrency/lock_table.go, line 456 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdIRWl0E-LAGPu_35C:-MSdIRWmBp3AeynfxVo0:bz6o3fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/kv/kvserver/concurrency/lock_table.go#L456)):*
> ```Go
> // Note that parent transactions may have replicated exclusive locks on keys
> // due to writes (intents) which are not discovered in the lock table. That is
> // fine and dealt with in HandleWriteIntentError. This is not handled perfectly
> ```

I worry about this "This is not handled perfectly ..." stuff.
Having a descendants unreplicated lock over an ancestor's replicated lock seems as confusing as the hazard @nvanbenschoten was mentioning where the ancestor had the unreplicated lock and the descendant had the replicated one. Given we control what these descendants are doing, can we just ensure (while the only locks are Exclusive locks -- we can revisit when adding support for other strengths) that the descendants don't unnecessarily scan with locks, unless they plan to write to that span. Then we can declare this case as illegal too.

Hmm, maybe I'm misreading this comment. The code in `tryActiveWait` is doing the straightforward thing and not caring whether the currently held lock is replicated or unreplicated.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 441 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/56588#-MSdOBBmEQWQeu5nugTR:-MSdOBBmEQWQeu5nugTS:b6wwo76) ([raw file](https://github.com/cockroachdb/cockroach/blob/00abaee55c9f2039bf9ddbdafbbef532c7d6c820/pkg/storage/pebble_mvcc_scanner.go#L441)):*
> ```Go
> 		if seqNum >= p.meta.Txn.Sequence &&
> 			!enginepb.TxnSeqIsIgnored(p.meta.Txn.Sequence, ignoredSeqNums) {
> 			// 9. We're reading our own txn's intent at an equal or higher sequence.
> ```

would be nice to update all these comments that say "our own".


<!-- Sent from Reviewable.io -->

2026-06-18 17:36 UTC, closed without merging