sql,util,opt: add support for inverted filter with JSON and Array columns
cockroachdb/cockroach pull request #56732
Opened 2020-11-16 14:05 UTC by rytaft

**sql,util: return `noDuplicates` boolean from `EncodeContainingInvertedIndexSpans`**

This commit adds a result parameter for `EncodeContainingInvertedIndexSpans`
called `noDuplicates`. The function returns `noDuplicates=true` if the spans are
guaranteed not to produce duplicate primary keys. Otherwise, returns
`noDuplicates=false`. The logic is based on the fact that spans for a given JSON
or Array datum will not produce duplicate primary keys if there is exactly one
JSON or Array path ending in a scalar (i.e., not an empty object or array).

**sql,opt: add support for inverted filter with JSON and Array columns**

This commit adds support for planning and executing an inverted index
scan + invertedFilter when there is a contains (`@>`) predicate on a JSON or
array column that has an inverted index. Similar to spatial columns, the
optimizer may be able to plan an inverted index scan + invertedFilter
for JSON and Array columns even if the filter condition is complex, with
multiple predicates combined with AND and OR expressions.

Informs #47340

Release note (performance improvement): The optimizer now supports using
an inverted index on JSON or Array columns for a wider variety of filter
predicates. Previously, inverted index usage was only supported for simple
predicates (e.g., `WHERE a @> '{"foo": "bar"}'`), but now more complicated
predicates are supported by combining simple contains (@>) expressions with
AND and OR (e.g., `WHERE a @> '{"foo": "bar"}' OR a @> '{"foo": "baz"}'`).
An inverted index will be used if it is available on the filtered column and
the optimizer expects it to be more efficient than any alternative plan.
This may result in performance improvements for queries involving JSON and
Array columns.

2020-11-16 14:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56732)
<!-- Reviewable:end -->

2020-11-16 14:26 UTC, rytaft commented
Please hold off reviewing this, since there are some plan regressions. Trying to figure out how to fix.





<!-- Sent from Reviewable.io -->

2020-11-19 01:22 UTC, rytaft commented
I think this is finally ready for review. There are still a few minor plan regressions, but I've created issues for them and included TODOs in the test files (#56870, #56868 and #56799). PTAL - thanks!





<!-- Sent from Reviewable.io -->

2020-11-20 00:03 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice! Looks like this was a big lift.

> Reviewed 1 of 5 files at r1, 4 of 19 files at r3, 14 of 25 files at r4, 9 of 10 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MMXxKWkEDQXse5j7KTX:b5ko7tp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMWvUO2-DHVCrNGipi5:-MMWvUO2-DHVCrNGipi6:b1gq89v) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array#L1)):*
> ```
> # Test cases for using invertedFilterer on an inverted json or array index.
> ```

Some of these tests are for zigzag joins. Should all these tests just live in `inverted_index`? I'm not really sure...

Also, there's nothing here that ensures that these tests will continue to use the intended operators (zigzag vs inverted filter) in the future. This has come up before I think in a previous PR. I'm just a little uneasy about it. I don't know of a good solution though.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMWutyt5Cti7TMf2xAS:-MMWutyt5Cti7TMf2xAT:b-grv2a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array#L81)):*
> ```
> 
> query I
> SELECT a FROM json_tab WHERE b @> '1' ORDER BY a
> ```

Is this case the same as above but without an index join?
___
*[pkg/sql/opt/invertedidx/inverted_index_expr.go, line 265 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX2lna0cqHOxWnPQjt:-MMX2lna0cqHOxWnPQju:b1c2kmv) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/inverted_index_expr.go#L265)):*
> ```Go
> // - pre-filterer state that can be used by the invertedFilterer operator to
> //   reduce the number of false positives returned by the span expression.
> func TryFilterInvertedIndex(
> ```

[nit] move this function up directly above `TryJoinInvertedIndex` since this is kind of an "entry point" into this file.
___
*[pkg/sql/opt/invertedidx/inverted_index_expr.go, line 438 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX3iAn4syxUH4dGguN:-MMX3iAn4syxUH4dGguO:b-l31m50) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/inverted_index_expr.go#L438)):*
> ```Go
> // - remaining filters that must be applied if the inverted expression is not
> //   tight, and
> // - pre-filterer state that can be used to reduce false positives.
> ```

It looks like you only return a pre-filterer state if `filterCond` is a leaf expression. Can a pf state not be generated from conjunctions and disjunctions? If not, maybe add a comment here explaining this.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 278 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX56W7Cd1ds-L5kRCW:-MMX56W7Cd1ds-L5kRCX:b-tl4e7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array.go#L278)):*
> ```Go
> ) {
> 	switch t := expr.(type) {
> 	case *memo.ContainsExpr:
> ```

[nit] add TODO to support JSON fetch val operator `->`
___
*[pkg/sql/opt/invertedidx/json_array.go, line 313 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX4Sxy91_F2gebeWA6:-MMX4Sxy91_F2gebeWA7:b-pasihb) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array.go#L313)):*
> ```Go
> 	}
> 	if variable.Typ.Family() == types.ArrayFamily &&
> 		j.index.Version() < descpb.EmptyArraysInInvertedIndexesVersion {
> ```

What's the upgrade story for users to new inverted index versions?

If we took out the current `Scan.Constraint`-based inverted index scanning now, when a user upgrades to 21.1 some of their queries could go from using inverted indexes to full table scans until they upgraded their inverted index versions. 
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 327 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXvEPoD7FBA6xOIA4Y:-MMXvEPoD7FBA6xOIA4Z:busd5ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array_test.go#L327)):*
> ```Go
> 		{
> 			// We cannot guarantee that the span expression is tight when there is a
> 			// nested array.
> ```

Hmmm.. Why not?
___
*[pkg/sql/opt/xform/select_funcs.go, line 866 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXbPLT5AIMTUbKCrZe:-MMXbPLT5AIMTUbKCrZf:b-ben5g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L866)):*
> ```Go
> 
> 		// We scan the PK columns, and the inverted key column if there is an
> 		// inverted filter.
> ```

[nit] => "We scan the PK columns if needed". You could also move the initialization of `needInvertedFilter` here and combine the comments.
___
*[pkg/sql/opt/xform/testdata/rules/select, line 1821 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXqQEr9RDJukM_kpxH:-MMXqQEr9RDJukM_kpxI:bjwa7hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/testdata/rules/select#L1821)):*
> ```
>       └── key: (1)
> 
> # Disjunction.
> ```

:tada: 
___
*[pkg/sql/rowenc/index_encoding.go, line 939 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXsAz7CJXnLtWnHVh2:-MMXsAz7CJXnLtWnHVh3:b-6zrdui) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/rowenc/index_encoding.go#L939)):*
> ```Go
> 		spans[i] = roachpb.Spans{{Key: key, EndKey: endKey}}
> 	}
> 	unique = len(keys) == 1
> ```

[nit] add a comment that reminds the reader that more than 1 key means that there could be duplicate primary keys in an inverted index.
___
*[pkg/sql/rowenc/index_encoding_test.go, line 436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXtH_Z9dYIDrf6aRWP:-MMXtH_Z9dYIDrf6aRWQ:bvuzjsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/rowenc/index_encoding_test.go#L436)):*
> ```Go
> 		{`{NULL}`, `{}`, true, false},
> 		{`{NULL}`, `{NULL}`, false, true},
> 		{`{2, NULL}`, `{2, NULL}`, false, true},
> ```

It's not obvious to me why the spans for `{2, NULL}` would guarantee non-duplicate primary keys (unique=true). For an array with the value `[2, NULL]`, wouldn't there be 2 entries in the inverted index for that row?


<!-- Sent from Reviewable.io -->

2020-11-20 15:05 UTC, sumeerbhola requested changes
> Reviewed 1 of 5 files at r1, 4 of 19 files at r3, 1 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/xform/select_funcs.go, line 857 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa2MTuEXu0ggspXIXy:-MMa2MTuEXu0ggspXIXz:bo2xkkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L857)):*
> ```Go
> 		// INTERSECTION.
> 		needInvertedFilter := spanExpr != nil &&
> 			(!spanExpr.Unique || spanExpr.Operator != invertedexpr.None)
> ```

Based on my earlier comment on `encodeContainingInvertedIndexSpansFromLeaf` I wonder if there is really any case where there is more than one span in a `roachpb.Spans` and unique is true.

I was expecting some unification of the code used in `GenerateInvertedIndexZigzagJoins` and the inverted-filterer, for example using the same `encodeContainingInvertedIndexSpans`. If I remember correctly, these recent PRs have not been changing `indexConstraintCtx.makeInvertedIndexSpansForExpr`. Is that code still correct, in light of the better understanding of NULL semantics? And it seems we wouldn't want to maintain both as we add support for more operators (beyond `ContainsOp`).

We would have something like:
unique (which implies sorted) for each `roachpb.Spans` which would be and-ed as is done now, but not say anything about the length of `[]roachpb.Spans`. These would be used in building a `SpanExpression` which would set unique to false when Or-ing (but not for and-ing).
If unique was true and the len of this slice was >= 2, a zig-zag join would use the two tightest spans (based on stats -- there is a TODO in GenerateInvertedIndexZigzagJoins to use stats). Ideally, we could use the `SpanExpression` for getting the spans rather than returning to these slices, but it aggressively factors the spans, and we don't want that for zig-zag joins. Hmm, we could tweak `SpanExpression` to operate in a mode where it doesn't factor and ignores `SpanExpression` that are being and-ed that have unique=false -- i.e., it would be behaving in a way that would allow us to easily build a zig-zag join. 
___
*[pkg/sql/rowenc/index_encoding.go, line 849 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MM_vIOM-t7550fWHVp-:-MM_vIOM-t7550fWHVp0:b-jvw73y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a416c603374005c73cc85d7867d4cff98a08aec3/pkg/sql/rowenc/index_encoding.go#L849)):*
> ```Go
> //
> // Returns unique=true if the spans are guaranteed not to produce duplicate
> // primary keys. Otherwise, returns unique=false.
> ```

I am having trouble interpreting this statement. If the different `roachpb.Spans` involved in the intersection produce different sets of keys, the intersection will be empty.
Then I thought this meant that the the different spans in each `roachpb.Spans` would be non-overlapping wrt primary keys (which typically means there will be only one span in each `roachpb.Spans`). And maybe the purpose here was to see when zig-zag joins were viable. But that would also require saying something more than unique -- that each `roachpb.Spans` produces keys in sorted order. I suppose uniqueness and sorted are equivalent given our encoding.
I think this needs a longer comment since `[]roachpb.Spans` represents an expression and the existing statement is hard to relate to that.
___
*[pkg/util/json/json.go, line 1069 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa-W2u6e6WJaAU_0qE:-MMa-W2u6e6WJaAU_0qF:bx7ztc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a416c603374005c73cc85d7867d4cff98a08aec3/pkg/util/json/json.go#L1069)):*
> ```Go
> 		// EncodeArrayAscending generates the prefix that is used for all non-empty
> 		// arrays.
> 		keys = append(keys, encoding.EncodeArrayAscending(prefix))
> ```

Can you add a comment like

// The span that will be generated for this key can have duplicate PKs, so unique=false.
___
*[pkg/util/json/json.go, line 1095 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa-nvt2IefwHblvYPq:-MMa-nvt2IefwHblvYPr:b-budpe8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a416c603374005c73cc85d7867d4cff98a08aec3/pkg/util/json/json.go#L1095)):*
> ```Go
> 			// This end key is equal to jsonInvertedIndex + 1.
> 			EndKey: roachpb.Key(prefix).PrefixEnd(),
> 		})
> ```

same comment would be useful here.
___
*[pkg/util/json/json.go, line 1115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa00Mb4KvPE2V_3XOR:-MMa00Mb4KvPE2V_3XOS:b-hpsy64) ([raw file](https://github.com/cockroachdb/cockroach/blob/a416c603374005c73cc85d7867d4cff98a08aec3/pkg/util/json/json.go#L1115)):*
> ```Go
> 			keys = append(keys, arrKeys...)
> 
> 			// Even though we now have two spans, we can guarantee no duplicates
> ```

... no PK duplicates ...

The span for the array will contain duplicate PKs inside it. Worth stating that in this comment, even though we may not care.


<!-- Sent from Reviewable.io -->

2020-11-23 17:22 UTC, rytaft reviewed
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MMpvCfCEY9cdIF1zhEH:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMWvUO2-DHVCrNGipi5:-MMpZQJa1eB-R_0GUjhL:bazltzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array#L1)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Some of these tests are for zigzag joins. Should all these tests just live in `inverted_index`? I'm not really sure...

Also, there's nothing here that ensures that these tests will continue to use the intended operators (zigzag vs inverted filter) in the future. This has come up before I think in a previous PR. I'm just a little uneasy about it. I don't know of a good solution though.
</blockquote></details>

I moved the zigzag join tests to `inverted_index`, and the corresponding `EXPLAIN` tests to the appropriate files. I removed the mention of which plan to choose here, since as you pointed out there's no way to enforce it. But I left the comment about the preferred plan in the two EXPLAIN varieties, so hopefully we'll catch any plan changes there.

I'd like to leave the rest of the tests in this file, since they correspond to the plans in the two EXPLAIN files, and it's easier to test this operator methodically. It also mirrors the geospatial tests. Maybe at some point we can combine them all into one file with multiple subtests, but I think this is easier and less error-prone for now.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMWutyt5Cti7TMf2xAS:-MMpaH3KBngdrrPHe0SJ:b-mlh7un) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array#L81)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is this case the same as above but without an index join?
</blockquote></details>

Yep, added a comment.
___
*[pkg/sql/opt/invertedidx/inverted_index_expr.go, line 265 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX2lna0cqHOxWnPQjt:-MMpaUlU5hfueHqers-V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/inverted_index_expr.go#L265)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] move this function up directly above `TryJoinInvertedIndex` since this is kind of an "entry point" into this file.
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/inverted_index_expr.go, line 438 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX3iAn4syxUH4dGguN:-MMpb18r6BmZ6APqH2p4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/inverted_index_expr.go#L438)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like you only return a pre-filterer state if `filterCond` is a leaf expression. Can a pf state not be generated from conjunctions and disjunctions? If not, maybe add a comment here explaining this.
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 278 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX56W7Cd1ds-L5kRCW:-MMpbCYuCks-0F7uI8pm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array.go#L278)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add TODO to support JSON fetch val operator `->`
</blockquote></details>

Done.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 313 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMX4Sxy91_F2gebeWA6:-MMpceAn8wpMtU0CfrgU:b-pglk2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array.go#L313)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the upgrade story for users to new inverted index versions?

If we took out the current `Scan.Constraint`-based inverted index scanning now, when a user upgrades to 21.1 some of their queries could go from using inverted indexes to full table scans until they upgraded their inverted index versions. 
</blockquote></details>

I had a TODO for this below, but it was an easy fix so I've just done it now. Added a few tests too.
___
*[pkg/sql/opt/invertedidx/json_array_test.go, line 327 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXvEPoD7FBA6xOIA4Y:-MMpdLFXBVmc34oYjwfg:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/invertedidx/json_array_test.go#L327)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmmm.. Why not?
</blockquote></details>

Added a comment.
___
*[pkg/sql/opt/xform/select_funcs.go, line 857 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa2MTuEXu0ggspXIXy:-MMpo5Rf41p5mQjvkEUV:b9oousv) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L857)):*
The one case where you can have two spans and `unique=true` is when the right hand side of the contains expression is a scalar. There is a pretty extensive comment inside `encodeContainingInvertedIndexSpansFromLeaf` that explains that case, but let me know if you think I should also add an example here or elsewhere.

But I think you make a good point that we may be able to make use of the unique boolean in cases where we will need to intersect the results anyway, which will allow us to use this code for zig-zag joins as suggested below. I think this is going to require more thought, though, so I'd rather save that for a future PR if that's ok with you.

> I was expecting some unification of the code used in GenerateInvertedIndexZigzagJoins...

I plan to do that in a follow-on PR. 

> ... these recent PRs have not been changing indexConstraintCtx.makeInvertedIndexSpansForExpr. Is that code still correct ...

`indexConstraintCtx.makeInvertedIndexSpansForExpr` seems to be correct because it explicitly avoids using the index if an array is empty or has nulls. But I definitely plan to get rid of that code as soon as possible once `GenerateInvertedIndexZigzagJoins` uses the new code.

> We would have something like: ... Hmm, we could tweak SpanExpression to operate in a mode ...

This is a good idea, but I think it can wait till the follow-on PR. 
___
*[pkg/sql/opt/xform/select_funcs.go, line 866 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMXbPLT5AIMTUbKCrZe:-MMpvAdr5S2La-1JxqYN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L866)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] => "We scan the PK columns if needed". You could also move the initialization of `needInvertedFilter` here and combine the comments.
</blockquote></details>

Done.
___
*[pkg/sql/rowenc/index_encoding.go, line 849 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MM_vIOM-t7550fWHVp-:-MMphsy-0qF9KY08_hA4:bjtbugq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a416c603374005c73cc85d7867d4cff98a08aec3/pkg/sql/rowenc/index_encoding.go#L849)):*
<details [...]

2020-11-24 15:46 UTC, sumeerbhola approved these changes
looks good! some minor comments.

I remembered that there are no microbenchmarks for `invertedJoiner` and `invertedFilterer` -- there are TODOs in the test files.
I did not see any obvious costly paths when looking at whole node profiles for geospatial queries, but that may be because the number of spans in those queries were causing other costs to be high. Now that we are going to exercise that code with fewer spans, I think it is worthwhile for someone to add microbenchmarks specifically for array and json and see if there are any optimizations possible there. I doubt I will have the time for it in the next month, so perhaps you or someone from sql execution would like to pick that up.

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 30 files at r7, 25 of 29 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MMuuFfMDq977GXWaecq:bgyqdf7)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMukwQLCDc5FdhPAFVx:-MMukwQLCDc5FdhPAFVy:b-oiteff) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L63)):*
> ```
> 
> statement ok
> ALTER TABLE json_tab EXPERIMENTAL_RELOCATE VALUES (ARRAY[1], 1), (ARRAY[2], 10), (ARRAY[3], 20)
> ```

I was expecting split and relocate on the inverted index. What is the purpose of distributing the table?

Though I think we can't do the split and relocate on the index for json since these are not datums. And I think the similar thing in the geospatial tests is now broken for the same reason (since it is no longer using an int datum). I wonder if we should try to extend the `EXPERIMENTAL_RELOCATE` to handle encoded values, though it seems hard to maintain. Another possibility would be to rewrite these tests with multi-column inverted indexes and use the fact that the first column there will be a datum.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 130 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMumPU9Aed543sgQXFh:-MMumPU9Aed543sgQXFi:b-v7i9g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L130)):*
> ```
> ORDER BY a]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html#eJyUklFr2zAUhd_3Ky73pQnTiOUwBnpKu7gsI4szO7CN2BQluu08PMmT5BII-e_DdkPqQbL2xVj33O_oHNAe3Z8SBabRPPq4gtqWcJvEX2AdfV_Or2cLGExn6Sr9Oh_C04rsFn45o--83MC3T1ESwWCwgUlWB8GY4GrN8yshPqfx4mYIcQI9LTxpQ7heTPvo-CyY4UbaDJ_BcTKNErj5ATJHhtooWsjf5FCskWPOsLJmS84Z24z27cJM7VAEDAtd1b4Z5wy3xhKKPfrCl4QCV3JTUkJSkR0FyFCRl0XZ2h5LT-6NuSv0IzJMK6mdgNFTvHfHn9HS0n2xi7QCqRW8B-N_knWYHxia2p-ud14-EAp-YC-PONOPZD2p26L0ZMmOeD_nUY92lQWjYcIFuCYoOC-tFxl-yLIgCJoPz7IgDJvMpwkCafWfrTBD6FdjGNdewISfLRm-pmRqrCc7CvvVJvztWfvxa-wTcpXRjnr255yDQ86Q1AN1T8mZ2m5pac22vaY7xi3XDhQ536m8O8x0JzUBn8P8IhxehsOL8PgfOD-8-RsAAP__85I68g==
> ```

Nice that many of these don't need a JoinReader.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 191 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMunVzU0LrLDgcx2u27:-MMunVzU0LrLDgcx2u28:bbgduc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L191)):*
> ```
> query T
> SELECT url FROM [EXPLAIN (DISTSQL)
> SELECT a FROM array_tab WHERE b @> '{1}' OR a = 1 ORDER BY a]
> ```

will this unioning of (a) scan on the primary index and (b) inverted index+join-reader, also happen if (b) needed an inverted filterer?
___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist, line 93 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMup5uS1eXN6oEsoH0l:-MMup5uS1eXN6oEsoH0m:b-3fesyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist#L93)):*
> ```
> ORDER BY j1.a, j2.a]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzUk01v2kwUhffvr7i67yIQJthjQz5mNUlxJUfUTm1UtUpQZPA0MiUed2xHqRD_vbIhH47CAItK7ZLr-8w554qzwPznHBmGztD5MIJSzeFj4H-Ca-fr1fDc9aA1cMNR-HnYhvXKjHYPCcys7uFqc5bL9LaIJnAewswC1_OcAFzvixOMnAFc-q7XXKHge9BqzWh3AvymNE1bVK9N2nDuDaA5P1jcYHSDDBbL5UH7acPqRlAvTMEy2-AHAyeAi2-Vs6h2Fo2RYCpj4UX3Ikd2jRQJWjgmmCk5FXkuVTVe1Etu_IjMJJikWVlU4zHBqVQC2QKLpJgLZDiKJnMRiCgWyjCRYCyKKJnXTz-F45lK7iP1CwmGWZTmDI4MauJ4SVCWxcvTeRHdCWR0SXaXd9MHoQoRX8okFcqwNjj4LuVtkj4geQacx0xBi_eeL8qt9RVfzRpXZoxdhr530UaCflkw4JRwi3B7YxJrnyRVgvUde1vvOJTyR5nBTCYpyJQBtytTHrR4_51A_T0DEd7fmMneJ1MoVSGUcdzMw-0O4bTzrGoT3iO19kbV3kbVFzGpYqFE_EaLdgi3OzhevmPPk0cyM04bxCYH_YYDunsp6K6lMKh5ZNAz4_8dm7HFw5tm2H9xM7YkedWM_j_TjC2Z1s04-YPNeEc1EHkm01zs9I83q8qI-E6sapbLUk3FlZLTWmb106-5ehCLvFh9pasfbrr6VBl8DVMtbOlhSwvbetjWwr0GTN_CPS18plfua-FjPXyshU_08IkWPtXDp3sdbLz873cAAAD__7iL4aw=
> ```

what is causing this to change?

and more generally, there are many changes to the `inverted_join` testdata files, which I am unclear about -- I thought this PR only touched inverted filter.
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index, line 126 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMuq7212Sz4J_rrJVNj:-MMuq7212Sz4J_rrJVNk:b-i5fy1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index#L126)):*
> ```
> query T
> SELECT url FROM [EXPLAIN (DISTSQL)
> SELECT a FROM array_tab@foo_inv WHERE b @> '{1, 2}' ORDER BY a]
> ```

Same question about doing the relocate above on the table instead of the index. The plan here is not distributed.
___
*[pkg/sql/opt/xform/select_funcs.go, line 857 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa2MTuEXu0ggspXIXy:-MMugftnBVh9iz1eyeZ5:b-7h7bmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L857)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The one case where you can have two spans and `unique=true` is when the right hand side of the contains expression is a scalar. There is a pretty extensive comment inside `encodeContainingInvertedIndexSpansFromLeaf` that explains that case, but let me know if you think I should also add an example here or elsewhere.

But I think you make a good point that we may be able to make use of the unique boolean in cases where we will need to intersect the results anyway, which will allow us to use this code for zig-zag joins as suggested below. I think this is going to require more thought, though, so I'd rather save that for a future PR if that's ok with you.

> I was expecting some unification of the code used in GenerateInvertedIndexZigzagJoins...

I plan to do that in a follow-on PR. 

> ... these recent PRs have not been changing indexConstraintCtx.makeInvertedIndexSpansForExpr. Is that code still correct ...

`indexConstraintCtx.makeInvertedIndexSpansForExpr` seems to be correct because it explicitly avoids using the index if an array is empty or has nulls. But I definitely plan to get rid of that code as soon as possible once `GenerateInvertedIndexZigzagJoins` uses the new code.

> We would have something like: ... Hmm, we could tweak SpanExpression to operate in a mode ...

This is a good idea, but I think it can wait till the follow-on PR. 
</blockquote></details>

Follow-on PR sounds good.
___
*[pkg/sql/rowenc/index_encoding.go, line 855 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMue-sv221LYUlxmVIQ:-MMue-sv221 [...]

2020-11-25 02:09 UTC, rytaft reviewed
TFTR!

> ... I think it is worthwhile for someone to add microbenchmarks ...

Opened #57101

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MMx7hC52rFAhQYSLJgZ:b-2lhnuk)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @RaduBerinde, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMukwQLCDc5FdhPAFVx:-MMwKh5U4ha4eXdRDHhs:b-1ljx0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I was expecting split and relocate on the inverted index. What is the purpose of distributing the table?

Though I think we can't do the split and relocate on the index for json since these are not datums. And I think the similar thing in the geospatial tests is now broken for the same reason (since it is no longer using an int datum). I wonder if we should try to extend the `EXPERIMENTAL_RELOCATE` to handle encoded values, though it seems hard to maintain. Another possibility would be to rewrite these tests with multi-column inverted indexes and use the fact that the first column there will be a datum.

</blockquote></details>

I rewrote the tests using a multi-column inverted index.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 130 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMumPU9Aed543sgQXFh:-MMw-mkS1vtT4mjoqsYc:b-pbdqzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L130)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Nice that many of these don't need a JoinReader.
</blockquote></details>

Agreed!
___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 191 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMunVzU0LrLDgcx2u27:-MMw0PvN6Nfv8lg6W4ef:b6xx3oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L191)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

will this unioning of (a) scan on the primary index and (b) inverted index+join-reader, also happen if (b) needed an inverted filterer?
</blockquote></details>

Yes it will -- Added another test case for that.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist, line 93 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMup5uS1eXN6oEsoH0l:-MMw0nsF6AtoEePCSXZ_:bcz5fqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is causing this to change?

and more generally, there are many changes to the `inverted_join` testdata files, which I am unclear about -- I thought this PR only touched inverted filter.
</blockquote></details>

Now that we support inverted filtering for JSON, the optimizer plans an inverted filter for this query with a non-inverted join. In order to force this query to use an inverted join I added the `INVERTED JOIN` hint, but that also changed the order of the tables.

The other two queries in this file also changed because the optimizer began planning an inverted filter instead of an inverted join. We can't yet force semi and anti joins to use a particular join algorithm, so instead I changed the query so that the inverted join was chosen.
___
*[pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index, line 126 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMuq7212Sz4J_rrJVNj:-MMwKlWmD27J00o8U8St:bf44si6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index#L126)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Same question about doing the relocate above on the table instead of the index. The plan here is not distributed.
</blockquote></details>

Zigzag joins aren't supported yet with multicolumn indexes. I left a TODO in this file to fix it once they are supported.
___
*[pkg/sql/opt/xform/select_funcs.go, line 857 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMa2MTuEXu0ggspXIXy:-MMw1vtU9WXSuob7eY-4:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/977d7e5ced4b9ff1822fba849bc2556f3a142efd/pkg/sql/opt/xform/select_funcs.go#L857)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Follow-on PR sounds good.
</blockquote></details>

Ack.
___
*[pkg/sql/rowenc/index_encoding.go, line 855 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMue-sv221LYUlxmVIQ:-MMwIVQTE9HbwTPTgAPl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/rowenc/index_encoding.go#L855)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add that unique is also set to false when length of spans > 1.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-25 15:28 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 29 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MN-0BYq3EF9DDgDdGIp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist, line 191 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMunVzU0LrLDgcx2u27:-MMzylcf734XSEheMRvG:b-7m74ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_filter_json_array_dist#L191)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yes it will -- Added another test case for that.
</blockquote></details>

nice!
___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist, line 93 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMup5uS1eXN6oEsoH0l:-MN--Bua-yfzw3qmbpS8:b-fr6uv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist#L93)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Now that we support inverted filtering for JSON, the optimizer plans an inverted filter for this query with a non-inverted join. In order to force this query to use an inverted join I added the `INVERTED JOIN` hint, but that also changed the order of the tables.

The other two queries in this file also changed because the optimizer began planning an inverted filter instead of an inverted join. We can't yet force semi and anti joins to use a particular join algorithm, so instead I changed the query so that the inverted join was chosen.
</blockquote></details>

Is this because the heuristic cost we assign to an inverted join using `j1.b @> j2.b` is greater than the estimated cost for doing  `j1.b @> '{"a": {}}'` and ` j2.a < 20` on each side and then doing a hash join?
What is in the plan for 21.1 regarding cost estimation for inverted joins?


<!-- Sent from Reviewable.io -->

2020-11-25 15:56 UTC, rytaft reviewed
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-:-MN-3gNy0OxpvHzVZyzw:b-voiyyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, @rytaft, and @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist, line 93 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/56732#-MMup5uS1eXN6oEsoH0l:-MN-3kOXE9nxHlGfufUe:b-hn9vcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b95dcf56de0696c100f73dc7f06f00997c3124a/pkg/sql/logictest/testdata/logic_test/inverted_join_json_array_dist#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this because the heuristic cost we assign to an inverted join using `j1.b @> j2.b` is greater than the estimated cost for doing  `j1.b @> '{"a": {}}'` and ` j2.a < 20` on each side and then doing a hash join?
What is in the plan for 21.1 regarding cost estimation for inverted joins?

</blockquote></details>

Yea, that's exactly right -- without the hint, the optimizer chooses a hash join with the two sides constrained.

The stats/cost estimation for inverted indexes need a lot of improvement in general. I think improving stats for inverted index scan, inverted filter and inverted join all need to be a priority for this release. Using histograms to estimate the cardinality of joins will be part of the solution for improving inverted joins (right now we just use distinct counts).


<!-- Sent from Reviewable.io -->

2020-11-25 16:53 UTC, merged