sql: Enabling correct pg_class.relPersistence for temporary tables
cockroachdb/cockroach pull request #56827
Opened 2020-11-17 21:45 UTC by mnovelodou

relPersistence at pg_class was displaying 'p' for all tables including temporary
this is incorrect for temporary tables as this tables do not exists when session
ends
Changed the logic that takes a constant for this field and changing the value
when table is temporary

Release note (sql change): Enabling correct relPersistence at pg_class table
for temporary tables

2020-11-17 21:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56827)
<!-- Reviewable:end -->

2020-11-18 16:34 UTC, arulajmani requested changes
Code change looks good, left some minor comments on the logic tests. I also have a nit on your commit message, could you consider rewording that as follows:

```
Previously, the relpersistence column in pg_catalog.pg_class displayed 'p' for all tables regardless of persistence status. This is incorrect for temporary tables and unlogged tables, as they are supposed to have `t` and `u` values respectively. This patch fixes this behavior for temp tables, but leaves it unchanged for unlogged tables (as we don't persist unlogged information past parsing).

Fixes #<issue number> 

Release note (sql change): the relpersistence column in pg_catalog.pg_class now correctly displays `t` as the persistence status for temporary tables.  
```

The `Fixes #<issue number>` allows the PR to be linked to the original issue, and once it merges, will close the issue automatically! We generally tend to do this for all PRs if the issue is resolved. If the issue is not resolved, we use the "Informs" keyword. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-:-MMR8tz_6N8_4CphP4eS:berbkmz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou)

___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR89moBVOmuq94FBCn:-MMR89moBVOmuq94FBCo:b-qozgga) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2788)):*
> ```
> 
> statement ok
> CREATE TEMPORARY TABLE test_temp1 (id UUID PRIMARY KEY);
> ```

nit: 4 temp tables here doesn't really get us anything, you could pare it down to just one. 
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR9WGC0RkjSXke7xK1:-MMR9WGC0RkjSXke7xK2:b4lbji2) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2794)):*
> ```
> 
> query T
> SELECT relname FROM pg_catalog.pg_class WHERE relpersistence = 't'
> ```

We should probably test `relpersistence` for persistent tables and unlogged tables as well. I would recommend creating one of each and ensuring you get the correct relpersistence for each of those tables is `p`. Could you also leave a comment about the unlogged tables test that calls out the wrong behavior and the reason for it, in case we decide to fix it going forward.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR8Lf861d0UNbBHHtj:-MMR8Lf861d0UNbBHHtk:b19camb) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2802)):*
> ```
> 
> statement ok
> DROP TABLE test_temp1;
> ```

nit: You could remove all these `DROP TABLE` statements here. This gets automatically deleted after all the logic tests in the file are run, so we generally abstain from dropping objects unless it tests some functionality. 


<!-- Sent from Reviewable.io -->

2020-11-18 20:52 UTC, mnovelodou reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2788 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR89moBVOmuq94FBCn:-MMS7E9R59eUHNDbAthD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2788)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: 4 temp tables here doesn't really get us anything, you could pare it down to just one. 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR9WGC0RkjSXke7xK1:-MMS79aW1AhVGM3CZUxj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2794)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should probably test `relpersistence` for persistent tables and unlogged tables as well. I would recommend creating one of each and ensuring you get the correct relpersistence for each of those tables is `p`. Could you also leave a comment about the unlogged tables test that calls out the wrong behavior and the reason for it, in case we decide to fix it going forward.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-18 20:53 UTC, mnovelodou reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMR8Lf861d0UNbBHHtj:-MMS7T_n-tcdTQn4Jw5f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c6f6181c865625bbf0436795c72c59fd301536/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2802)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: You could remove all these `DROP TABLE` statements here. This gets automatically deleted after all the logic tests in the file are run, so we generally abstain from dropping objects unless it tests some functionality. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-19 19:30 UTC, arulajmani requested changes
Thanks for making the changes, couple more nits but otherwise looks good to go. 

Now that I'm reading this again, could you update your commit message title as well to `sql: enable correct pg_class.rel_persistence for temporary tables`. We generally try to use present tense (enable vs enabling) for a change, as people might read the commit message after it goes in to figure out what happened here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-:-MMWyadcDo7Dfy0vxZGS:b-6raj8y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @mnovelodou)

___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2789 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMWyLb90qor_kvxeAcq:-MMWyLb90qor_kvxeAcr:bb5fgy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e4973e27e6187910dc5b32ca4aaca381360d83f/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2789)):*
> ```
> statement ok
> CREATE TEMPORARY TABLE test_temp1 (id UUID PRIMARY KEY);
> CREATE UNLOGGED TABLE test_temp2 (id UUID PRIMARY KEY);
> ```

This (and below) aren't temp tables -- I would call this `test_unlogged` (and `test_persistent` below) 
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2793 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMWyZ1T37W1mVqkW8Xj:-MMWyZ1T37W1mVqkW8Xk:bqlm17d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e4973e27e6187910dc5b32ca4aaca381360d83f/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2793)):*
> ```
> 
> # we don't store UNLOGGED beyond the parser at the moment so we expect 'p' for test_temp2
> ```

nit: no new line


<!-- Sent from Reviewable.io -->

2020-11-20 22:45 UTC, mnovelodou reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2789 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMWyLb90qor_kvxeAcq:-MMbpJvi-cHDJpfvI0Mr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e4973e27e6187910dc5b32ca4aaca381360d83f/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2789)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This (and below) aren't temp tables -- I would call this `test_unlogged` (and `test_persistent` below) 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2793 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-MMWyZ1T37W1mVqkW8Xj:-MMbpKfx42A063zpW2gF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e4973e27e6187910dc5b32ca4aaca381360d83f/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2793)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: no new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-23 15:26 UTC, arulajmani approved these changes
Thanks for working through this, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56827#-:-MMphhDWAxZ96S378l9G:b-ibhamp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)



<!-- Sent from Reviewable.io -->

2020-11-23 15:27 UTC, arulajmani commented
bors r=arulajmani

2020-11-23 16:03 UTC, merged