sql: fix SHOW GRANTS for DB-level privileges
cockroachdb/cockroach pull request #56866
Opened 2020-11-18 19:42 UTC by rafiss

The addition of user-defined schemas broke the ability to view
fine-grained privileges on a database.

Release note (bug fix): SHOW GRANTS and the information_schema table did
not include privileges that were granted on a database. Now they do.

fixes #56666

2020-11-18 19:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56866)
<!-- Reviewable:end -->

2020-11-23 16:46 UTC, solongordon requested changes
I think we may want something a bit more subtle here. In Postgres, schemas only support the CREATE and USAGE privileges, and we matched that behavior with user-defined schemas. To limit confusion, we should probably we do the same for other schemas and only inherit those privileges from the parent database.

However there is another wrinkle, which is that we don't support granting USAGE on databases. I think the simplest thing to do for now would be to say that a role has USAGE on the schema if they have SELECT on the database. It looks like that is the logic which is currently encoded into our `has_schema_privilege` built-in (which will need to be updated if you make this change): https://github.com/cockroachdb/cockroach/blob/be5a871b99151b17a93981666f246ae15699cc49/pkg/sql/sem/builtins/pg_builtins.go#L1496-L1502

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56866#-:-MMpy60G5UWSi4W6iEUN:b-wzicvk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)



<!-- Sent from Reviewable.io -->

2020-11-24 04:49 UTC, rafiss commented
@solongordon i'm not sure i follow this:

> In Postgres, schemas only support the CREATE and USAGE privileges, and we matched that behavior with user-defined schemas. To limit confusion, we should probably we do the same for other schemas and only inherit those privileges from the parent database.

so you mean that `SHOW GRANTS ON SCHEMA` should only ever have CREATE and USAGE privilieges?

i think i might be confused -- what does `SHOW GRANTS` without any additional specifiers do? is that an alias for `SHOW GRANTS ON TABLE *`?

2020-11-24 15:53 UTC, solongordon reviewed
Yeah, I'm thinking that `SHOW GRANTS ON SCHEMA` and the `information_schema.schema_privileges` table should only include `CREATE`, `USAGE`, and `ALL` grants because that's what we support on user-defined schemas. `SHOW GRANTS ON DATABASE` should show all grants on the database itself, which could be any privilege except `USAGE`.

`SHOW GRANTS` without any additional specifiers shows the grants for all child objects (schemas, tables, sequences, types) of the current database.

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56866#-:-MMuvJ3d7ru7OwDyF6_F:b-ze15bk)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-11-24 21:18 UTC, rafiss commented
Hmm interesting, so then I guess we would have to re-implement `SHOW GRANTS ON DATABASE` so that it no longer delegates to `information_schema.schema_privileges`. Do you happen to already know of a different system table that has DB-level privileges? If not, then I think the way forward is to make a crdb_internal table that has the info.

2020-11-24 22:05 UTC, solongordon commented
Ah, I didn't realize SHOW GRANTS ON DATABASE also delegated to `schema_privileges`.

I don't know of another table with database-level privileges. If it's straightforward enough to add `crdb_internal.database_privileges` (or somesuch), that seems reasonable to me. If it ends up being annoying we can consider just preserving the old behavior of listing out all the database-level privileges on the `public` schema for now, but I think this will be confusing to users.

2020-12-07 19:01 UTC, rafiss commented
PTAL; this was reworked a lot. I made the fixes with what I think actually makes sense.. but I don't know if the changes in the outputs of information_schema and SHOW GRANTS are safe to put in a 20.2 backport.

I'm hoping to get these changes in for 21.1, and use this to discuss what we can do for 20.2

2020-12-11 01:21 UTC, rafiss commented
one of the failing tests is TestAdminAPIDatabases. However, I think the test has a bug. [The PR that broke SHOW GRANTS](https://github.com/cockroachdb/cockroach/pull/53344/files#diff-e7ca70986c2e3cbe6a52026f65f383a293054dc34f592a4d4c869500f6aaecae) also changed the test so that it was incorrect.

2020-12-14 22:21 UTC, solongordon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with one testing suggestion. Thanks for sorting this out, and yes let's have a discussion about what is appropriate for backporting to 20.2.

> Reviewed 25 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56866#-:-MOYKqAuEdMWSVF8nmP0:bjs70g3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @rafiss, and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/privilege_builtins, line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56866#-MOYJHu4D3K77btPRYJr:-MOYJHu4D3K77btPRYJs:bev303d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8988eb08956bf4e17867077fe23a9fa5a407b86/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L635)):*
> ```
>        has_schema_privilege('testuser', 'test_schema', 'CREATE, USAGE')
> ----
> true  true  true
> ```

Should we also be testing whether this behaves correctly if the user has `ALL` privileges?


<!-- Sent from Reviewable.io -->

2020-12-15 18:12 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56866)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/privilege_builtins, line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56866#-MOYJHu4D3K77btPRYJr:-MObafgNEYqraeZOhcNu:b-vect4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8988eb08956bf4e17867077fe23a9fa5a407b86/pkg/sql/logictest/testdata/logic_test/privilege_builtins#L635)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Should we also be testing whether this behaves correctly if the user has `ALL` privileges?
</blockquote></details>

good call. adding the test


<!-- Sent from Reviewable.io -->

2020-12-15 19:44 UTC, rafiss commented
thanks for the review!

bors r=solongordon

2020-12-15 20:16 UTC, merged