sql: aggregate row counts for EXPLAIN ANALYZE (PLAN)
cockroachdb/cockroach pull request #56929
Opened 2020-11-19 20:03 UTC by RaduBerinde

This change aggregates row counts per logical operator and shows them
in EXPLAIN ANALYZE (PLAN).

This likely doesn't work well with filtering, because the filter is
collapsed into the same processors as the last stage. That issue will
be revisited separately.

Release note: None

2020-11-19 20:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56929)
<!-- Reviewable:end -->

2020-11-20 11:05 UTC, asubiotto requested changes
Nice!

> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-:-MM_K9YkA5PyhsSNQYp7:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_IMQb25GwNZOuHmwY:-MM_IMQb25GwNZOuHmwZ:b6y3yjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L359)):*
> ```Go
> // TODO(radu): we perform similar processing of execution traces in various
> // parts of the code. Come up with some common infrastructure that makes this
> // easier.
> ```

+1 Off the top of my head the similarity is that we always parse a trace and associate it to a custom data structure. We could probably have these custom data structures define a common interface that consumes `ComponentStats` and an accompanying flowID/processorID/streamID.
___
*[pkg/sql/instrumentation.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_Gqza1GOj0n4cfCMb:-MM_Gqza1GOj0n4cfCMc:b-rqyamp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L429)):*
> ```Go
> func (m execNodeTraceMetadata) annotateExplain(plan *explain.Plan) {
> 	var walk func(n *explain.Node)
> 	walk = func(n *explain.Node) {
> ```

nit: I think we should avoid making this a closure to avoid unnecessary allocations
___
*[pkg/sql/instrumentation.go, line 432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_HEBM2poS_yvmk9zi:-MM_HEBM2poS_yvmk9zj:b-ncfxfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L432)):*
> ```Go
> 		wrapped := n.WrappedNode()
> 		meta, ok := m[wrapped]
> 		if ok {
> ```

nit: `if meta, ok := m[n.WrappedNode()]; ok {`
___
*[pkg/sql/instrumentation.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_HqYL8VbCBBgQgnco:-MM_HqYL8VbCBBgQgncp:b-88tqmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L443)):*
> ```Go
> 				rowCount += stats.Output.NumTuples.Value()
> 			}
> 			if !incomplete {
> ```

Might be worth to explain this `incomplete` behavior in a small comment.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_8fz9-g6KeDJm8BK3:-MM_8fz9-g6KeDJm8BK4:b6jh5pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/colfetcher/colbatch_scan.go#L124)):*
> ```Go
> // GetBytesRead is part of the execinfra.IOReader interface.
> func (s *ColBatchScan) GetBytesRead() int64 {
> 	if s.rf.fetcher == nil {
> ```

What do you think of pushing this check into the `fetcher`?
___
*[pkg/sql/logictest/testdata/logic_test/explain_analyze, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_E9sj88G31zHz1Qsr:-MM_E9sj88G31zHz1Qss:b-ajj45o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/logictest/testdata/logic_test/explain_analyze#L59)):*
> ```
> │ columns: (k, v, a, b)
> │ actual row count: 2
> │ estimated row count: 990 (missing stats)
> ```

This is so cool to see.
___
*[pkg/sql/opt/exec/factory.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_EGGT4IXnDY2qa6CP:-MM_EGGT4IXnDY2qa6CQ:b-4yvxn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/opt/exec/factory.go#L295)):*
> ```Go
> // ExecutionStats contain statistics about a given operator gathered from the
> // execution of the query.
> type ExecutionStats struct {
> ```

Can we use `ComponentStats` for this information instead of introducing another struct?


<!-- Sent from Reviewable.io -->

2020-11-20 15:47 UTC, RaduBerinde reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-:-MMaJfn2BDWnOwtaCFAO:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/instrumentation.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_IMQb25GwNZOuHmwY:-MMaH8GP0ofgn_tCZfxJ:byvtf8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L359)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

+1 Off the top of my head the similarity is that we always parse a trace and associate it to a custom data structure. We could probably have these custom data structures define a common interface that consumes `ComponentStats` and an accompanying flowID/processorID/streamID.
</blockquote></details>

Yeah, that's an interesting idea. I was also thinking that we could make the ComponentID a specific type that can encode either a processor or a stream (and can tell which is which), and also add the flowID to `ComponentStats`. That way, we'd never care about the span tags (and we'd be free to have multiple ComponentStats per span which seems like a better fit for vectorized).
___
*[pkg/sql/instrumentation.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_Gqza1GOj0n4cfCMb:-MMaHr5mE5nbiaitt9q9:br8p1jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L429)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think we should avoid making this a closure to avoid unnecessary allocations
</blockquote></details>

It's recursive.. what's the alternative?
___
*[pkg/sql/instrumentation.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_HqYL8VbCBBgQgnco:-MMaJ1Mj7dLrIX5dnTPe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L443)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be worth to explain this `incomplete` behavior in a small comment.
</blockquote></details>

Done.
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_8fz9-g6KeDJm8BK3:-MMaJ91Z4SAeHlEE4AQL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/colfetcher/colbatch_scan.go#L124)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What do you think of pushing this check into the `fetcher`?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/factory.go, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_EGGT4IXnDY2qa6CP:-MMaILh205bBYBGD2mNJ:b2o9lll) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/opt/exec/factory.go#L295)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we use `ComponentStats` for this information instead of introducing another struct?
</blockquote></details>

Interesting.. I was thinking there would be new things here that only make sense when aggregated. Leaving like this for now but I will keep that in mind (and I added a TODO).


<!-- Sent from Reviewable.io -->

2020-11-23 11:27 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 10 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-:-MMoqoLR4OxfKbW3OV3Z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/instrumentation.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_IMQb25GwNZOuHmwY:-MMopJ9pDThNTMSduEiM:bbrl5i3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L359)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, that's an interesting idea. I was also thinking that we could make the ComponentID a specific type that can encode either a processor or a stream (and can tell which is which), and also add the flowID to `ComponentStats`. That way, we'd never care about the span tags (and we'd be free to have multiple ComponentStats per span which seems like a better fit for vectorized).
</blockquote></details>

I like the idea.
___
*[pkg/sql/instrumentation.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56929#-MM_Gqza1GOj0n4cfCMb:-MMopW3x6KmPx_VYDPPC:b-py6de2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed9c74794507ff76094ea5e67edf85bcf45d1d9f/pkg/sql/instrumentation.go#L429)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's recursive.. what's the alternative?
</blockquote></details>

I was thinking a separate method on `execNodeTraceMetadata`. I'm not opposed to keeping it like this either, just wanted to point it out.


<!-- Sent from Reviewable.io -->

2020-11-23 17:11 UTC, RaduBerinde commented
bors r+

2020-11-24 05:03 UTC, RaduBerinde commented
bors r+

2020-11-24 05:43 UTC, merged