colexec: retune hash table constants in all of its uses
cockroachdb/cockroach pull request #56968
Opened 2020-11-20 19:02 UTC by yuzefovich

**colexec: adjust benchmarks to include cases with small number of tuples**

This commit adjusts several benchmarks in order to run them against
inputs with small number of tuples. The reasoning for such change is
that we intend to remove the vectorize_row_count_threshold, so we now
should be paying attention to both small and large input sets.

Release note: None

**colexec: retune hash table constants in all of its uses**

This commit changes the load factor and the initial number of buckets of
the hash table according to the recent micro-benchmarking and running of
TPCH queries. The numbers needed an update since we made the hash table
as well as the operators that use it more dynamic. The benchmarks show
an improvement on the inputs with small sizes, sometimes a regression on
inputs roughly of `coldata.BatchSize()` in size, and mostly improvements
on larger inputs. This trade-off seems beneficial to me.

Release note: None

2020-11-20 19:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56968)
<!-- Reviewable:end -->

2020-11-20 19:04 UTC, yuzefovich commented
Note that I run the benchmarks with #56935 cherry-picked.

The benchmarks are:
- [hash joiner](https://gist.github.com/yuzefovich/0899ff005a6b1f5304a59a8aae4fa23c)
- [hash aggregator](https://gist.github.com/yuzefovich/ba07d7f001a679020b80435b70b48de3)
- [unordered distinct](https://gist.github.com/yuzefovich/76c4f74d554975cc51ebf8c54a026871)

2020-11-23 11:18 UTC, asubiotto requested changes
> Reviewed 4 of 4 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/aggregators_test.go, line 995 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56968#-MMoo7Xr8KGQPfP4KS1R:-MMoo7Xr8KGQPfP4KS1S:b4xsfpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e1a1e79eb0d7e18c6c92ad62bfc60a02634e95/pkg/sql/colexec/aggregators_test.go#L995)):*
> ```Go
> 			Vec:              col,
> 			N:                numInputRows,
> 			NullProbability:  0,
> ```

It's an important change to get rid of null probability in benchmarks, right? What's the reasoning? Could you include it in a commit message?
___
*[pkg/sql/colexec/hashjoiner.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56968#-MMooPK_DS8zMnIeNbQK:-MMooPK_DS8zMnIeNbQL:bu3f4ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7dbafe172625b736181feecefdc7b075d74b08/pkg/sql/colexec/hashjoiner.go#L240)):*
> ```Go
> // This number was chosen after running the micro-benchmarks and relevant
> // TPCH queries using tpchvec/bench.
> var HashJoinerInitialNumBuckets = uint64(256)
> ```

Why `var` instead of `const`? Doesn't look like other packages need to modify this (which I don't think would be good anyway). If they need another value, they just need to pass that into the constructor, right?


<!-- Sent from Reviewable.io -->

2020-11-30 17:32 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56968)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/aggregators_test.go, line 995 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56968#-MMoo7Xr8KGQPfP4KS1R:-MNPB3p45jsYqU0-1C4D:b-6qukhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8e1a1e79eb0d7e18c6c92ad62bfc60a02634e95/pkg/sql/colexec/aggregators_test.go#L995)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It's an important change to get rid of null probability in benchmarks, right? What's the reasoning? Could you include it in a commit message?
</blockquote></details>

The speed of no-nulls and with-nulls cases are roughly the same, so having both doesn't provide us much new information, yet slows down running the benchmark by a factor of 2. Updated the commit message.
___
*[pkg/sql/colexec/hashjoiner.go, line 240 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56968#-MMooPK_DS8zMnIeNbQK:-MNPBu8b7WDBUhb82vDt:b2y2afa) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7dbafe172625b736181feecefdc7b075d74b08/pkg/sql/colexec/hashjoiner.go#L240)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why `var` instead of `const`? Doesn't look like other packages need to modify this (which I don't think would be good anyway). If they need another value, they just need to pass that into the constructor, right?
</blockquote></details>

Good catch. I left it originally like this because at first I had `coldata.BatchSize()` as the value, but after tuning I chose a different one (that can be a `const`). Fixed.


<!-- Sent from Reviewable.io -->

2020-12-01 09:57 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56968#-:-MNSj7MM83jxK7R1aG3Z:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2020-12-01 15:41 UTC, yuzefovich commented
TFTR!

bors r+

2020-12-01 16:57 UTC, merged