sql: format arrays in pg_catalog to match Postgres
cockroachdb/cockroach pull request #56980
Opened 2020-11-20 23:58 UTC by rafiss

Postgres uses the curly brace syntax to display array constants that are
in pg_catalog, like those in default expressions.

CockroachDB stores arrays in descriptors as tree.Array exprs, so in
order to use the curly brace syntax, now we check if the array has any
variables or functions, and if not, we turn the Array expr into a
DArray. The formatting logic for DArrays also is updated to use single
quotes as appropriate, when formatting for pg_catalog.

Release note (sql change): Arrays in pg_catalog tables now are diaplyed
in a format that matches PostgreSQL.

2020-11-20 23:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/56980)
<!-- Reviewable:end -->

2020-12-04 00:21 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56980)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @jordanlewis, and @rafiss)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56980#-MNf4Zpn9ZHfpcVC8cpG:-MNf4Zpn9ZHfpcVC8cpH:be3jebx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a8dc816958a764adea8b54db3f92165118cf563/pkg/sql/catalog/schemaexpr/expr.go#L202)):*
> ```Go
> 		sanitizedExpr, err := SanitizeVarFreeExpr(ctx, expr, typedExpr.ResolvedType(), "FORMAT", semaCtx,
> 			tree.VolatilityImmutable)
> 		if err == nil {
> ```

This `err == nil` could use some commentary. Better yet, are we expecting a particular type of error here in case we want to fall back to the `typedExpr`? If so, can we check for that and be more explicit? 


<!-- Sent from Reviewable.io -->

2020-12-04 16:56 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56980)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @jordanlewis)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56980#-MNf4Zpn9ZHfpcVC8cpG:-MNifG-r51O3u2hatW42:bf6gthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a8dc816958a764adea8b54db3f92165118cf563/pkg/sql/catalog/schemaexpr/expr.go#L202)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This `err == nil` could use some commentary. Better yet, are we expecting a particular type of error here in case we want to fall back to the `typedExpr`? If so, can we check for that and be more explicit? 
</blockquote></details>

i don't think we can check for a specific error. the error could be 
```
pgerror.Newf(pgcode.Syntax,
			"variable sub-expressions are not allowed in %s", context)
```

or anything from the typechecker rejecting the volatility of the expression

agree on commenting!


<!-- Sent from Reviewable.io -->

2020-12-07 16:37 UTC, arulajmani approved these changes
Thanks for making the changes! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> modulo a couple of nits re: the comments for future us! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56980#-:-MNxwfqi4KT-QzcfBYaq:bc8l5mo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @jordanlewis, and @rafiss)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56980#-MNf4Zpn9ZHfpcVC8cpG:-MNxwJub9taHU67NTCiB:b-ezype3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a8dc816958a764adea8b54db3f92165118cf563/pkg/sql/catalog/schemaexpr/expr.go#L202)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think we can check for a specific error. the error could be 
```
pgerror.Newf(pgcode.Syntax,
			"variable sub-expressions are not allowed in %s", context)
```

or anything from the typechecker rejecting the volatility of the expression

agree on commenting!
</blockquote></details>

nit: the comment about an empty EvalContext might be misplaced -- shouldn't it go above the `d, err := sanitizedExpr.Eval(&tree.EvalContext())` line?

nit: Could you also add a nod to the fact that this is best effort and we can fall back on returning an expression if we can't convert it to a constant? 


<!-- Sent from Reviewable.io -->

2020-12-07 16:40 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56980)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @jordanlewis)

___
*[pkg/sql/catalog/schemaexpr/expr.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56980#-MNf4Zpn9ZHfpcVC8cpG:-MNy3gK8EDxmcboosN2u:b-a0jaf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a8dc816958a764adea8b54db3f92165118cf563/pkg/sql/catalog/schemaexpr/expr.go#L202)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: the comment about an empty EvalContext might be misplaced -- shouldn't it go above the `d, err := sanitizedExpr.Eval(&tree.EvalContext())` line?

nit: Could you also add a nod to the fact that this is best effort and we can fall back on returning an expression if we can't convert it to a constant? 
</blockquote></details>

thanks -- i shouldn't have moved that comment. also adding the other one


<!-- Sent from Reviewable.io -->

2020-12-07 19:29 UTC, rafiss commented
bors r=arulajmani

2020-12-07 20:24 UTC, merged