sql: pool SpanBuilders
cockroachdb/cockroach pull request #57010
Opened 2020-11-23 03:13 UTC by jordanlewis

The SpanBuilder is an object that is allocated once per query, along
with slice memory inside of it, making it a good candidate for object
pooling.

```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=false/distribute=false-24    17.8µs ±14%    17.4µs ±12%    ~     (p=0.739 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=false/distribute=false-24    29.8kB ± 0%    28.9kB ± 1%  -3.14%  (p=0.000 n=10+10)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=false/distribute=false-24       216 ± 0%       212 ± 0%  -1.85%  (p=0.000 n=10+10)
```

Release note: None

2020-11-23 03:13 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/57010)
<!-- Reviewable:end -->

2020-11-24 05:26 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/span/span_builder.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MMsf0MRAvX0fTP9UwDd:-MMsf0MRAvX0fTP9UwDe:b-mxvsi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/011d34e1aa2cebeee0b44ba062dd5d9acdb33ab9/pkg/sql/span/span_builder.go#L78)):*
> ```Go
> 		index:          index,
> 		KeyPrefix:      rowenc.MakeIndexKeyPrefix(codec, table, index.ID),
> 		interstices:    s.interstices[:0],
> ```

These are re-initialized below, I'd remove from here
___
*[pkg/sql/span/span_builder.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MMshhlw3kY1ZK4kXl1-:-MMshhlw3kY1ZK4kXl10:besib3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/011d34e1aa2cebeee0b44ba062dd5d9acdb33ab9/pkg/sql/span/span_builder.go#L86)):*
> ```Go
> 		s.interstices = make([][]byte, nInterstices)
> 	} else {
> 		s.interstices = s.interstices[:nInterstices]
> ```

We need to set these to nil, either here or in Release (it makes more sense in Release so they can be garbage collected)
___
*[pkg/sql/span/span_builder.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MMshraF5dlqdn8LSgc-:-MMshraF5dlqdn8LSgc0:b-hhk3gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/011d34e1aa2cebeee0b44ba062dd5d9acdb33ab9/pkg/sql/span/span_builder.go#L94)):*
> ```Go
> 		s.indexColTypes = make([]*types.T, len(columnIDs))
> 	} else {
> 		s.indexColTypes = s.indexColTypes[:len(columnIDs)]
> ```

Should reset the types to nil


<!-- Sent from Reviewable.io -->

2020-11-30 01:59 UTC, jordanlewis reviewed
Done, RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-:-MNLs3p6BQybzeSEM9SW:b-oq29fq)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-11-30 03:23 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-:-MNMAL0ECm-Qh2HBF_eD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-11-30 04:49 UTC, yuzefovich requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/span/span_builder.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MNMR1ee60DZMHFb1yoL:-MNMR1ee60DZMHFb1yoM:bhnnb2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/2918035ca5642cc030d3d8e121b3da67ed48c03e/pkg/sql/span/span_builder.go#L72)):*
> ```Go
> ) *Builder {
> 	s := builderPool.Get().(*Builder)
> 	*s = Builder{
> ```

I thought that such setting of the fields would lose the references to old `interstices`, apparently  I was wrong? Meaning that I'm not seeing something like `interstices: s.interstices,`

Update: actually, I tried it out [here](https://play.golang.org/p/T9Z-26ffg7Y), and it appears that we do lose the references to the memory we're trying to keep below.


<!-- Sent from Reviewable.io -->

2020-12-01 16:52 UTC, RaduBerinde commented
___
*[pkg/sql/span/span_builder.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MNMR1ee60DZMHFb1yoL:-MNUCyd704UnpJV4_giq:b-750sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2918035ca5642cc030d3d8e121b3da67ed48c03e/pkg/sql/span/span_builder.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I thought that such setting of the fields would lose the references to old `interstices`, apparently  I was wrong? Meaning that I'm not seeing something like `interstices: s.interstices,`

Update: actually, I tried it out [here](https://play.golang.org/p/T9Z-26ffg7Y), and it appears that we do lose the references to the memory we're trying to keep below.
</blockquote></details>

Ah, my bad, I suggested this change. You are correct.


<!-- Sent from Reviewable.io -->

2021-10-23 02:52 UTC, yuzefovich reviewed
I rebased on top of master and fixed a problem. @raduberinde PTAL.

> Reviewed 8 of 10 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-:-Mmf2uqC5XrJY5G1y3Qy:b-6vssr8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/span/span_builder.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-MNMR1ee60DZMHFb1yoL:-Mmf2fDt91paEYJAEg4G:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2918035ca5642cc030d3d8e121b3da67ed48c03e/pkg/sql/span/span_builder.go#L72)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, my bad, I suggested this change. You are correct.
</blockquote></details>

Fixed.
___
*[pkg/sql/span/span_builder.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-Mmf2hh68rje7HxC6HjB:-Mmf2hh7-ZerQOMKl6xK:b1tlpsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4becbdc133a7333494d7c646ed4a6e69866d5f95/pkg/sql/span/span_builder.go#L64)):*
> ```Go
> 
> // MakeBuilder creates a Builder for a table and index. The returned object must
> // be Release()d when no longer needed.
> ```

I've thought about returning `s.Release` as a second return argument in order to force the caller to pay attention to the `Release` business, but eventually decided against it. Thoughts?


<!-- Sent from Reviewable.io -->

2021-10-23 04:15 UTC, yuzefovich approved these changes

2021-11-01 18:58 UTC, yuzefovich commented
Friendly ping @RaduBerinde @mgartner

2021-11-08 17:25 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 7 of 10 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-:-Mo-_God2vXDjDgy6_X0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-Mo-Z97i02g1KxX-XHlB:-Mo-Z97j6wDmDakHJwp1:bm93jce) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c46aab2018f49e109011a6d622b69e7ebba579d/pkg/sql/rowexec/joinreader.go#L74)):*
> ```Go
> 	// for Release()'ing it (this is needed because the
> 	// localityOptimizedSpanGenerator uses the same builder in both of its
> 	// generators).
> ```

Would it be simpler to change LOS generator to use two different builders?
___
*[pkg/sql/span/span_builder.go, line 566 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-Mo-ZzLKABhtHqSOXwHh:-Mo-ZzLKABhtHqSOXwHi:b-lco4ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c46aab2018f49e109011a6d622b69e7ebba579d/pkg/sql/span/span_builder.go#L566)):*
> ```Go
> 	*s = Builder{
> 		// Note that the types are small objects, so we don't bother deeply
> 		// resetting the indexColTypes slice.
> ```

What's the harm in resetting each element of indexColTypes? Just the overhead to do so? How do we weigh the overhead vs the benefit of allowing those types to be GC'd?


<!-- Sent from Reviewable.io -->

2021-11-08 17:52 UTC, yuzefovich reviewed
I removed the bits about reusing the slice of `interstices` since that field will be deleted very soon.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-:-Mo-fUoV-pDwIALkaTG_:b-qy6ewe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis, @mgartner, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-Mo-Z97i02g1KxX-XHlB:-Mo-eCnA7ZqZfPpWCQo3:b-p1in6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c46aab2018f49e109011a6d622b69e7ebba579d/pkg/sql/rowexec/joinreader.go#L74)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would it be simpler to change LOS generator to use two different builders?
</blockquote></details>

Yeah, probably it's cleaner, done.
___
*[pkg/sql/span/span_builder.go, line 566 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57010#-Mo-ZzLKABhtHqSOXwHh:-Mo-eJJMAVShowvsQp5S:b-xqd6dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c46aab2018f49e109011a6d622b69e7ebba579d/pkg/sql/span/span_builder.go#L566)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the harm in resetting each element of indexColTypes? Just the overhead to do so? How do we weigh the overhead vs the benefit of allowing those types to be GC'd?
</blockquote></details>

Yeah, I think just the overhead. I think `types.T` are special objects since for most of them we have global singletons, and thus they won't be GCed anyway even if nil the references out. We have used the same approach for types in many places now.


<!-- Sent from Reviewable.io -->

2021-11-08 19:40 UTC, merged

2021-11-09 13:34 UTC, mgartner reviewed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57010)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)



<!-- Sent from Reviewable.io -->