sql, featureflag: [WIP] add schema change feature flag
cockroachdb/cockroach pull request #57040
Opened 2020-11-24 00:30 UTC by angelapwen

PR is a WIP because testing for related features is incomplete. 

The following features need to be tested via their own text fixtures and not logic tests:

- [ ] ANALYZE/CREATE STATISTICS
- [ ] COMMENT ON COLUMN
- [ ] COMMENT ON DATABASE
- [ ] COMMENT ON INDEX
- [ ] COMMENT ON TABLE

The following features are correctly blocked, but surface unexpected error messages when the feature flag is off:

- [ ] RENAME COLUMN (throws ALTER TABLE error message instead of RENAME COLUMN error message)
- [ ] ALTER SEQUENCE RENAME (throws ALTER TABLE error message instead of SEQUENCE error message)
- [ ] ALTER SEQUENCE SET SCHEMA (throws ALTER TABLE error message instead of SEQUENCE error message)
- [ ] DROP SCHEMA (throws DROP DATABASE error message instead of DROP SCHEMA error message)

The following features do not throw an error when the feature flag is off, but (I believe) should:

- [ ] ALTER TABLE UNSPLIT ALL 
- [ ] ALTER INDEX CONFIGURE ZONE DISCARD, ALTER INDEX SPLIT AT

Note that not all variations of these commands, in particular the `ALTER` commands,  have been tested so far. 

The following features have been tested and act as expected:

- [ ] ALTER DATABASE OWNER
- [ ] ALTER DATABASE ADD REGION
- [ ] ALTER DATABASE DROP REGION
- [ ] ALTER DATABASE SURVIVE
- [ ] ALTER TABLE REGIONAL AFFINITY
- [ ] ALTER TABLE SET SCHEMA
- [ ] ALTER SCHEMA
- [ ] ALTER TYPE
- [ ] CREATE DATABASE
- [ ] CREATE INDEX
- [ ] CREATE SCHEMA
- [ ] CREATE TABLE
- [ ] CREATE TYPE
- [ ] CREATE VIEW
- [ ] CREATE SEQUENCE
- [ ] DROP DATABASE
- [ ] DROP INDEX
- [ ] DROP TABLE
- [ ] DROP VIEW
- [ ] DROP SEQUENCE
- [ ] DROP TYPE
- [ ] REASSIGN OWNED BY
- [ ] DROP OWNED BY
- [ ] RENAME DATABASE
- [ ] REPARENT DATABASE
- [ ] RENAME INDEX
- [ ] RENAME TABLE

---Commit message---

This change adds a feature flag via cluster setting for all
designated features that perform schema changes or DDLs. The
feature is being introduced to address a Cockroach Cloud SRE use
case: needing to disable certain categories of features, such as
schema changes, in case of cluster failure.

Release note (sql change): Adds a feature flag via cluster
setting for all schema change-related features. If a user attempts
to use these features while they are disabled, an error indicating
that the database administrator has disabled the feature is
surfaced.

Example usage for the database administrator:
SET CLUSTER SETTING feature.schemachange.enabled = FALSE;
SET CLUSTER SETTING feature.schemachange.enabled = TRUE;

2020-11-24 00:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/57040)
<!-- Reviewable:end -->

2020-11-24 00:38 UTC, otan approved these changes
this is awesome! two small changes requested.

> Reviewed 41 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-:-MMrfgze-Zk5Rl4KRVWT:b-7iq72l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen and @pbardea)

___
*[pkg/sql/alter_database.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMret24ACQ7tfHHXfTc:-MMret24ACQ7tfHHXfTd:ba7tghi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/alter_database.go#L36)):*
> ```Go
> 	if err := featureflag.CheckEnabled(featureSchemaChangeEnabled,
> 		&p.ExecCfg().Settings.SV,
> 		"ALTER DATABASE is part of the schema change category, which",
> ```

if we're including this message for all schema changes, might be worth adding a helper function so you only put ALTER DATABASE here. maybe put the function in this package so the `featureflag` package is schema change agnostic.
___
*[pkg/sql/create_stats.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMrfF77DIuUuc12w7X7:-MMrfF77DIuUuc12w7X8:b3jfezx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/create_stats.go#L55)):*
> ```Go
> 	if err := featureflag.CheckEnabled(featureSchemaChangeEnabled,
> 		&p.ExecCfg().Settings.SV,
> 		"ANALYZE/CREATE STATS is part of the schema change category, which"); err != nil {
> ```

i think these aren't schema changes -- might be worth creating a separate PR and put this as part of the CREATE_STATS or ANALYZE flag.
___
*[pkg/sql/schema_change_cluster_setting.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMrfmUT5yKi6HYCIn3Y:-MMrfmUT5yKi6HYCIn3Z:b-i1535g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/schema_change_cluster_setting.go#L24)):*
> ```Go
> // package?
> var featureSchemaChangeEnabled = settings.RegisterPublicBoolSetting(
> 	"feature.schemachange.enabled",
> ```

can we make this `schema_change` since it is two words?


<!-- Sent from Reviewable.io -->

2020-11-24 00:38 UTC, otan requested changes
oops, premature accept.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-:-MMrfxe6CpXXquuB2AZO:bkswpw5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen and @pbardea)



<!-- Sent from Reviewable.io -->

2020-11-24 00:41 UTC, angelapwen reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pbardea)

___
*[pkg/sql/alter_database.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMret24ACQ7tfHHXfTc:-MMrgPAR3LMpjt4glicT:blzih2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/alter_database.go#L36)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

if we're including this message for all schema changes, might be worth adding a helper function so you only put ALTER DATABASE here. maybe put the function in this package so the `featureflag` package is schema change agnostic.
</blockquote></details>

Yeah, that makes sense. I'll put it under the `schema_change_cluster_setting` package where I register the settings.
___
*[pkg/sql/create_stats.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMrfF77DIuUuc12w7X7:-MMrgYAo0WUGSToD5k74:b-gsvgfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/create_stats.go#L55)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think these aren't schema changes -- might be worth creating a separate PR and put this as part of the CREATE_STATS or ANALYZE flag.
</blockquote></details>

Ah alright!
___
*[pkg/sql/schema_change_cluster_setting.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-MMrfmUT5yKi6HYCIn3Y:-MMrgZUS66duZwFkbDxf:b-7xt2v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71c2db1393fe984206cff02529ed2cc0f9224fb/pkg/sql/schema_change_cluster_setting.go#L24)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we make this `schema_change` since it is two words?
</blockquote></details>

Yes! 


<!-- Sent from Reviewable.io -->

2020-11-25 02:19 UTC, otan reviewed
Looks like two small failures left.

` go test ./pkg/sql/pgwire -run TestPGTest/notice -rewrite` to fix the notice one!

> Reviewed 42 of 42 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-:-MMxBY8GE_Zyz6SKwQWo:b-3r0x97)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)



<!-- Sent from Reviewable.io -->

2020-11-25 02:33 UTC, angelapwen reviewed
Thanks! I think I've addressed the two failures just now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-:-MMxEnwKCmzdoIX-qAJp:bujfkuy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)



<!-- Sent from Reviewable.io -->

2020-11-25 03:53 UTC, angelapwen commented
bors r=otan

2020-11-25 03:55 UTC, otan approved these changes
lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57040#-:-MMxXhBi2gF2qBkQ2Ff4:bb7k0qh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)



<!-- Sent from Reviewable.io -->

2020-11-25 06:50 UTC, angelapwen commented
Flaky roachtest, giving this another go 🙏 

bors r=otan

2020-11-25 07:43 UTC, merged