roachtest: update pgjdbc blocklists
cockroachdb/cockroach pull request #57081
Opened 2020-11-24 20:33 UTC by solongordon

I made the following updates to the pgjdbc blocklists:
- Removed tests which are now passing due to user-defined schema
  support.
- Removed testUpdateSelectOnly since we now support this syntax as a
  no-op.
- Updated some failure reasons to "unknown" for tests which are still
  failing even though the referenced issue was closed.
- Added many BatchExecuteTest.* tests to the ignore list. These tests
  are flaky due to a combination of #54477 and the fact that the tests
  do not run in a deterministic order.

Fixes #53467
Fixes #53738
Fixes #54106

Release note: None

2020-11-24 20:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/57081)
<!-- Reviewable:end -->

2020-11-24 21:48 UTC, rafiss requested changes
lgtm! just a small note about removing the 19.1 stuff

also, just FYI, i believe this will need to backported to each release branch once it is merged. #51897 changed which roachtest binary is used in nightlies

2020-11-24 21:57 UTC, solongordon commented on pkg/cmd/roachtest/pgjdbc_blocklist.go
>  var pgjdbcIgnoreList19_1 = blocklist{
Done. I got rid of all the <19.2 lists.

2020-11-24 21:57 UTC, solongordon commented
Thanks for the heads up about backports!

2020-11-24 22:08 UTC, rafiss approved these changes

2020-11-25 15:11 UTC, solongordon commented
bors r+

2020-11-25 16:19 UTC, merged