sqlproxyccl: add KeepAlive option to BackendConfig
cockroachdb/cockroach pull request #57131
Opened 2020-11-25 17:08 UTC by spaskob

It is useful for clients of sqlproxy server to control if a live
connection should be expired; for example in case the credentials for
this connection are no longer valid or if the end user has to be blocked
immediately from accessing the DB.

To that end, we provide a new `BackendConfig` closure `KeepAliveLoop`
which can be used by sqlproxy clients to define business logic of when a
connection should be expired.

Alternatives considered: we could instead expose a channel that can
signal to clients when a connection is closed and also share the conn
resource outside of the `Proxy` go routine.  This would give users of
proxy much more flexibility of course but on the flip side I see several
problems:
1. `conn` can now be modified outside of the `Proxy` function which
   makes it harder to think about the correctness of the code and could
lead to subtle bugs.
2. We start mixing 2 different concurrency approaches, shared mutable
   resources (`conn`) and message passing. IMO this should be avoided
unless there are good reasons for it. My worry is that the sqlproxy will
be harder to maintain and change in the future if
3. `net.Conn` cannot used anymore and requires wrapping it in another
   struct which is unnecessary for clients that don't need to cancel
connections.

Release note: none.

2020-11-25 17:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/57131)
<!-- Reviewable:end -->

2020-11-25 18:34 UTC, jbowens requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/sqlproxyccl/error.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-dswZAOw11BXIv8H0:-MN-dswZAOw11BXIv8H1:b948bgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/error.go#L67)):*
> ```Go
> 
> 	// CodeExpiredConnection indicates that connection was expired and
>         // should be closed.
> ```

nit: formatting
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-fdppBgFWgzJqsmaG:-MN-fdppBgFWgzJqsmaH:bbwmxm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9d66e5dee429f15d5d27e0f4fa6294f8b9897e4/pkg/ccl/sqlproxyccl/proxy.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Looks like you lost the first line of the copyright notice.
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-dxIaB8kUVH-rJxT3:-MN-dxIaB8kUVH-rJxT4:b8tp3ri) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L37)):*
> ```Go
> 	// KeepAliveLoop is a loop that can be provided to determine if the connection
> 	// should be closed due to external reasons like credentials expiring for
> 	// example. The loop should be canceled is ctx is done.
> ```

s/is ctx is done/if ctx is done/
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-eytJ8qG4Rp7IJYmX:-MN-eytJ8qG4Rp7IJYmY:bzfpdcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L206)):*
> ```Go
> 
> 	ctx, done := context.WithCancel(context.Background())
> 	defer done()
> ```

nit: s/done/cancel/

`context.Context.Done` is its own thing, and calling the cancel function `done` is a little confusing.
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-e0N45z0kdf-CzGnv:-MN-e0N45z0kdf-CzGnw:b-s9lzb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L216)):*
> ```Go
> 	}()
> 	go func() {
> 		if backendConfig.KeepAliveLoop == nil {
> ```

mind as well move this if out of the goroutine to avoid launching a goroutine that will immediately exit.
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-fPN68je0Mv9ZgxXe:-MN-fPN68je0Mv9ZgxXf:b7f4bbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L243)):*
> ```Go
> 		return nil
> 	case err := <-errExpired:
> 		// The connection expired
> ```

nit: missing period
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-e_YV-71zDshOyZAZ:-MN-e_YW9PljtDg4GDU2:bmqc7iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L248)):*
> ```Go
> 			code := CodeExpiredConnection
> 			sendErrToClient(conn, code, err.Error())
> 			return NewErrorf(code, err.Error())
> ```

should be
```
Newerrorf(code, "expired conn: %v", err)
```
so that the `Error()` message isn't interpreted as a format specifier.


<!-- Sent from Reviewable.io -->

2020-11-30 22:43 UTC, jbowens requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/sqlproxyccl/proxy.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-dxIaB8kUVH-rJxT3:-MNQIvqJ9Y1Yscmo4Q1t:bcu7gi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L37)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

s/is ctx is done/if ctx is done/
</blockquote></details>

I think this comment needs some work generally. It should describe that a non-nil error return value signals that the connection should be closed, because  that's a non-obvious use of an error return value. It should probably describe that the function is invoked from its own goroutine when the connection is successfully opened, that it may block indefinitely and that the provided context will be canceled when the proxy closes the connection.


<!-- Sent from Reviewable.io -->

2020-12-02 21:11 UTC, spaskob reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/ccl/sqlproxyccl/proxy.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-fdppBgFWgzJqsmaG:-MNZd1wy0u9jVogUV2XC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9d66e5dee429f15d5d27e0f4fa6294f8b9897e4/pkg/ccl/sqlproxyccl/proxy.go#L1)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Looks like you lost the first line of the copyright notice.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-dxIaB8kUVH-rJxT3:-MNZeJJGCRgvs2Vuf6gO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L37)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

I think this comment needs some work generally. It should describe that a non-nil error return value signals that the connection should be closed, because  that's a non-obvious use of an error return value. It should probably describe that the function is invoked from its own goroutine when the connection is successfully opened, that it may block indefinitely and that the provided context will be canceled when the proxy closes the connection.
</blockquote></details>

Done.
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-e0N45z0kdf-CzGnv:-MNZeoTV19bIjqPovtRM:b-7ag8z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L216)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

mind as well move this if out of the goroutine to avoid launching a goroutine that will immediately exit.
</blockquote></details>

good point -> simplifies the code
___
*[pkg/ccl/sqlproxyccl/proxy.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-MN-e_YV-71zDshOyZAZ:-MNZfpZB7SfQy38fIhIT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb7bb1ef6db18eaece5750210346a5b613f91b75/pkg/ccl/sqlproxyccl/proxy.go#L248)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should be
```
Newerrorf(code, "expired conn: %v", err)
```
so that the `Error()` message isn't interpreted as a format specifier.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 18:45 UTC, spaskob commented
PTAL

2020-12-03 20:23 UTC, jbowens approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57131#-:-MNeGZO1DCf0P4Ie_5PX:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)



<!-- Sent from Reviewable.io -->

2020-12-03 20:37 UTC, spaskob commented
TFTR!

2020-12-03 20:38 UTC, spaskob commented
bors r=jbowens

2020-12-03 21:49 UTC, merged