builtins: add fuzzystrmatch soundex and difference builtin functions
cockroachdb/cockroach pull request #57615
Opened 2020-12-06 15:56 UTC by b41sh

add fuzzystrmatch `soundex` and `difference` builtin functions

Resolves: [#56820](https://github.com/cockroachdb/cockroach/issues/56820)

Release note (sql change): The soundex() and difference() builtin function was added.

2020-12-06 15:56 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=57615) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=57615) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=57615) it.</sub>

2020-12-06 15:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/57615)
<!-- Reviewable:end -->

2020-12-06 21:56 UTC, jordanlewis commented
Thanks for the contribution!

2020-12-07 22:04 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57615)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @b41sh and @jordanlewis)

___
*[pkg/sql/sem/builtins/builtins.go, line 2941 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzAUt-AdSw0SLVe4r-:-MNzAUt-AdSw0SLVe4r0:b-lrld1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/sql/sem/builtins/builtins.go#L2941)):*
> ```Go
> 				return tree.NewDString(t), nil
> 			},
> 			Info:       "Converts a string to its Soundex code.",
> ```

To match the style of other descriptions, can you change "Converts" to "Convert"
___
*[pkg/sql/sem/builtins/builtins.go, line 2946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzAbOf7IV_pngseBZn:-MNzAbOf7IV_pngseBZo:b-jm8437) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/sql/sem/builtins/builtins.go#L2946)):*
> ```Go
> 	),
> 	"difference": makeBuiltin(defProps(),
> 		tree.Overload{
> ```

The name `difference` is confusing, but I see it's actually intentional according to https://www.postgresql.org/docs/current/fuzzystrmatch.html#id-1.11.7.24.6

Could you add a note to that effect in the code comments? Something like "The function is  confusingly named' similarity would have been a better name, but this name matches the name in PostgreSQL. See https://www.postgresql.org/docs/current/fuzzystrmatch.html"
___
*[pkg/sql/sem/builtins/builtins.go, line 2951 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNz9vew-Wk7KcUrQC9-:-MNz9vew-Wk7KcUrQC90:bn0qsu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/sql/sem/builtins/builtins.go#L2951)):*
> ```Go
> 			Fn: func(evalCtx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				s, t := string(tree.MustBeDString(args[0])), string(tree.MustBeDString(args[1]))
> 				ld := fuzzystrmatch.Difference(s, t)
> ```

why the name `ld`? can it be renamed to `diff` to be more clear?
___
*[pkg/sql/sem/builtins/builtins.go, line 2954 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzAd5lCFN7fSc4U8u3:-MNzAd5lCFN7fSc4U8u4:b-lrld1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/sql/sem/builtins/builtins.go#L2954)):*
> ```Go
> 				return tree.NewDInt(tree.DInt(ld)), nil
> 			},
> 			Info:       "Converts two strings to their Soundex codes and then reports the number of matching code positions.",
> ```

To match the style of other descriptions, can you change "Converts" to "Convert"
___
*[pkg/util/fuzzystrmatch/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzAFa29PuuRf8qYjto:-MNzAFa29PuuRf8qYjtp:b-l3svy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/util/fuzzystrmatch/BUILD.bazel#L5)):*
> ```Starlark
> go_library(
>     name = "fuzzystrmatch",
>     srcs = ["soudex.go"],
> ```

typo: soundex.go
___
*[pkg/util/fuzzystrmatch/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzAGeYAO8n1CtRKqFQ:-MNzAGeYAO8n1CtRKqFR:bo8hc6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/util/fuzzystrmatch/BUILD.bazel#L12)):*
> ```Starlark
> go_test(
>     name = "fuzzystrmatch_test",
>     srcs = ["soudex_test.go"],
> ```

typo: soundex_test.go
___
*[pkg/util/fuzzystrmatch/soundex.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzBMwA9tiMCpB2Wb-o:-MNzBMwA9tiMCpB2Wb-p:b-hmw6s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/util/fuzzystrmatch/soundex.go#L18)):*
> ```Go
> )
> 
> const soundexLen = 4
> ```

can you comment this constant?
___
*[pkg/util/fuzzystrmatch/soundex.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzBnhH-_lYL7ymlsz-:-MNzBnhH-_lYL7ymlsz0:b67gwo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/util/fuzzystrmatch/soundex.go#L75)):*
> ```Go
> 
> // Soundex converts source to its Soundex code.
> func Soundex(source string) string {
> ```

why do we need both `soundex` and `Soundex` functions?
___
*[pkg/util/fuzzystrmatch/soundex_test.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-MNzDC_m267R1KmBLEp_:-MNzDC_m267R1KmBLEpa:b-bi7lot) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ab2307993c1256f497447b8609e74b14316579/pkg/util/fuzzystrmatch/soundex_test.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package fuzzystrmatch
> ```

can you also add a new file `pkg/sql/logictest/testdata/logic_test/fuzzystrmatch` and write SQL tests there? they should verify a few representative test cases to make sure it works end to end.

for example, what happens with `SELECT soundex(NULL)`? (In PostgreSQL, it looks like this returns NULL)


<!-- Sent from Reviewable.io -->

2020-12-09 09:39 UTC, b41sh commented
I have fixed the code for review.
PTAL @rafiss

If the string contains non-English characters, `soundex` will return `0x0`. `Difference` will compare these `0x0`s when judging whether they are equal, but `Soundex` will delete these `0x0`s when it finally returned. We need to keep `soundex` to be used both for `Soundex` and `Difference`.

2020-12-10 18:00 UTC, rafiss requested changes
thanks for addressing everything. this looks good, but the tests need an update.

can you run `make testlogic TESTS=fuzzystrmatch TESTFLAGS='-rewrite'`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-:-MOCnoF2E4AF1WYtE9TC:bw779kf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @b41sh and @jordanlewis)



<!-- Sent from Reviewable.io -->

2020-12-11 15:44 UTC, rafiss commented
Once the tests are working, please squash all the commits in the PR into one commit. You can do this with `git rebase -i`

2020-12-11 16:07 UTC, b41sh commented
> Once the tests are working, please squash all the commits in the PR into one commit. You can do this with `git rebase -i`

ok, I will squash it.

2020-12-11 16:32 UTC, rafiss commented
Thanks! you will also need to rebase on top of the latest `master` since there are conflicts now

2020-12-11 16:44 UTC, b41sh commented
> Thanks! you will also need to rebase on top of the latest `master` since there are conflicts now

ok

2020-12-11 21:39 UTC, rafiss approved these changes
thank you very much for your work! :)

bors r+

> Reviewed 1 of 5 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57615#-:-MOIjX0n2ZzvOho0C_43:blmcim3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @b41sh and @jordanlewis)



<!-- Sent from Reviewable.io -->

2020-12-11 22:23 UTC, merged