colexec: fix spilling of unordered distinct
cockroachdb/cockroach pull request #58006
Opened 2020-12-16 22:57 UTC by yuzefovich

In the recent addition of the external distinct we have a bug - we
completely ignored the in-memory state (the hash table) of the in-memory
unordered distinct when the spill occurs. This became problematic with
the recent change to make the unordered distinct streaming-like: we now
probe the hash table to remove all duplicates, add the distinct tuples
into the hash table and emit them into the output. So currently it is
possible for the external distinct to emit tuples that are duplicates of
already emitted ones by the in-memory operator before the spill
occurred.

To go around this issue, without changing the streaming-like behavior of
the in-memory unordered distinct, this commit introduces a special
filterer on the input to the external distinct which removes all
duplicates of tuples already emitted by the in-memory operator. (A side
bonus is that it also removes the duplicates within the batch itself.)

There is another complication that `distinctBuild` method used by the
unordered distinct can panic with an OOM error at different stages, and
in some cases the hash table might be in an inconsistent state (meaning
that some tuples are appended to `ht.vals`, but internal `first` and
`next` slices are not updated accordingly). In order to not get into
such scenario, the unordered distinct now takes in an unlimited
allocator and is responsible for complying with the specified memory
limit.

One notable change is that we will now annotate the OOM error produced
by the memory monitoring infrastructure with the names of all monitors
when propagating it up (e.g. if we have a chain of monitors like
`flow -> txn -> root` and the limit is reached on the root, only the
`root` would be mentioned in the error message, but now all 3 monitors
are mentioned). This change is necessary for the disk-spilling
infrastructure which relies on the appropriate monitor name to be
included in the error message in order to decide whether the OOM error
should be caught.

Fixes: #57858.

Release note: None (no release with this bug)

2020-12-16 22:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/58006)
<!-- Reviewable:end -->

2020-12-17 11:27 UTC, asubiotto requested changes
Instead of using an after-the-fact filtering approach, can we push it one layer down and override the in-memory hash table with the existing one?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-:-MOkOiRp0DuDe0VLv5kt:b2pq1c4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/unordered_distinct.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MOkPax92RjNYNtWkt8G:-MOkPaxA6sbKixG4HQHU:bs49jm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d236d31e7184cbaad45d7652b784284b3cb9e9e2/pkg/sql/colexec/unordered_distinct.go#L32)):*
> ```Go
> 	distinctCols []uint32,
> 	typs []*types.T,
> 	memoryLimit int64,
> ```

I think this needs a more extensive explanation of why this is needed. I wonder if instead of having the operator need to track a memory limit (it's a very unfortunate leak of abstraction that in-memory operators need to worry about memory usage), we should have some way to detect and fix hashtable inconsistency in `ExportBuffered` (i.e. it would act as a trigger to fix the hash table if broken).

There's also the option to lean more into the "override" hash table idea I mentioned above. We'd make sure to fix the hash table in the external operator before passing it to an operator with an unlimited monitor.


<!-- Sent from Reviewable.io -->

2020-12-17 17:36 UTC, yuzefovich reviewed
I have considered such approach and discarded it for a couple of reasons:
- the current infrastructure of `ExportBuffered` method provides us only with a way to emit the full input tuples that the disk-backed operator needs to process. However, the hash table stores only the columns needed for distinctness check of already emitted tuples, so we can use that channel to export it. We would need to create a "side channel" for exporting the in-memory state, and this channel currently would only be used by the external distinct (in the future, it could be used by the external hash aggregator if we are able to export the buckets with intermediate results).
- assuming we have a way to export the hash table, we would need to override `reset` method of the unordered distinct reused by the external distinct to make sure it keeps the tuples that came from the in-memory unordered distinct (which is a separate object). This seems like a broken abstraction to me. One way to go around it would be to inject the hash table state right after every `reset`ting of the unordered distinct used by the external distinct (that would probably be slightly inefficient but wouldn't matter much).

To me, planning a pre-filter seems a lot cleaner given the current spilling infrastructure since it is hidden in the constructor of the external distinct. Additionally, the current filtering approach reduces the number of tuples we have to partition and spill to disk which is a nice to have.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-:-MOlFh_v5z3LPln12Ijn:b4w7kqi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/unordered_distinct.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MOkPax92RjNYNtWkt8G:-MOlje6LCZIJkkNRuYMg:b-51rxmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d236d31e7184cbaad45d7652b784284b3cb9e9e2/pkg/sql/colexec/unordered_distinct.go#L32)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this needs a more extensive explanation of why this is needed. I wonder if instead of having the operator need to track a memory limit (it's a very unfortunate leak of abstraction that in-memory operators need to worry about memory usage), we should have some way to detect and fix hashtable inconsistency in `ExportBuffered` (i.e. it would act as a trigger to fix the hash table if broken).

There's also the option to lean more into the "override" hash table idea I mentioned above. We'd make sure to fix the hash table in the external operator before passing it to an operator with an unlimited monitor.
</blockquote></details>

I prototyped the approach with fixing the hash table, and I think I like it overall more. PTAL.

The complication here is that we have to be careful to not filter out tuples of the batch on which the OOM error occurred - they have been appended to the hash table but not yet emitted into the output, so I introduced a marker type for that.

Overall, I don't think we can fix this issue without some type of customization for the external distinct case due to the streaming nature of the unordered distinct - i.e. it is no longer simply a "buffering" operator, so I think breaking the abstraction is necessary here.

I responded to the "overriding hash table" idea above.


<!-- Sent from Reviewable.io -->

2021-01-07 12:13 UTC, asubiotto commented
Sorry I lost track of this. Is this RFAL?

2021-01-10 22:07 UTC, yuzefovich commented
Yes, it is RFAL (I kept the changes in a separate commit temporarily, for the ease of comparing two approaches).

There is something weird with a unit test going on (I remember I couldn't reproduce the problems), maybe I'll just relax it a bit to not require a specific number of spills.

2021-01-11 11:57 UTC, asubiotto requested changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/unordered_distinct.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MQlIU3q3SnRjDdP0iaN:-MQlIU3q3SnRjDdP0iaO:bu4pd9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb35182625987cde5faf968a30e0d40b9e6e992/pkg/sql/colexec/unordered_distinct.go#L81)):*
> ```Go
> 		// We adjust the allocator to request the amount of memory that should
> 		// exceed the limit of the bound memory account, so this call will
> 		// result in an internal OOM error that will be caught by the disk
> ```

Hmm, why not just panic with an actual OOM? The current approach seems hacky


<!-- Sent from Reviewable.io -->

2021-01-12 01:05 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/unordered_distinct.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MQlIU3q3SnRjDdP0iaN:-MQnzUcp5wuX8WVh892N:bl57kl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb35182625987cde5faf968a30e0d40b9e6e992/pkg/sql/colexec/unordered_distinct.go#L81)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, why not just panic with an actual OOM? The current approach seems hacky
</blockquote></details>

Let me describe the current peculiar situation in a lot of details.

Suppose the in-memory unordered distinct has already read 3 batches `A`, `B`, `C`, appended the distinct tuples from all of them into the hash table and emitted them. Now it reads batch `D` which has some new distinct tuples, but during the appending of these new distinct tuples the hash table reaches its limit.

Here is what happens in `distinctBuild`:
1. batch `D` is updated in-place to remove the duplicate tuples within itself (this doesn't interact with tuples from `A`, `B`, and `C` that are in the hash table)
2. batch `D` is updated in-place again to remove the "global" duplicates. Now `D`'s selection vector only contains tuples that are "globally" distinct which should be emitted into the output
3. however, before we can emit them into the output, we need to update the hash table to include these tuples, and this is where we hit an OOM which could occur for two reasons in `appendAllDistinct`
3.1) because of appending the tuples to `ht.vals`
3.2) because of reallocating internal slices of the hash table (`buildFromBufferedTuples`)
If the former is the case, then the hash table ends up in an inconsistent state, and we'll need to repair it before using.
4. regardless of when exactly an OOM error happened, a panic has occurred and we exited the execution of the in-memory unordered distinct. And what we have is the following: batch `D` contains distinct tuples that need to be emitted into the output and those tuples have been appended to the hash table.

Now the question arises on how to handle the fallback to the external distinct, and the fallback is subject to the following requirements:
1. all tuples of updated in-place batch `D` need to be emitted somehow, without being filtered by the hash table since the filtering of that batch has already occurred
2. all tuples in batch `E` and all consequent ones have to be checked against already emitted tuples from batches `A`, `B`, `C`, and `D` (assuming `D` is somehow emitted).

The second requirement can be satisfied in a relatively clean way by `unorderedDistinctFilterer` planned on top of the input to the disk-backed distinct; however, the first requirement is very tricky to get right. We can emit updated batch `D` in two places - either in the in-memory operator before panicking (this was my original approach) or in the disk-backed operator (after the panic and the fallback have occurred). I like the latter option since the former requires catching OOMs and is very-very hacky in order to not catch OOMs that are coming from other operators.

Assuming that we want to emit batch `D` from the disk-backed operator, we have a conflict with the `unorderedDistinctFilterer` - the hash table already contains all tuples from `D`, so we cannot filter that particular batch against the hash table because then we would never emit tuples from `D`. The solution I'm proposing right now is to have a special marker wrapper around batch `D` that indicates that filtering against the hash table should not be performed on this batch in particular.

An alternative approach would be somehow connecting the in-memory unordered distinct and `unorderedDistinctFilterer` directly so that the former in its `ExportBuffered` method could indicate (by a callback or modifying the filterer's internal state) that the next batch read by the filterer should not be filtered. However, this approach seems even worse.

There are some other complications due to the disk-spilling infrastructure. Here is the diagram of what the setup looks like with the current PR:
```
//        -------------  input  -----------
//       |                ||                | (2nd src)
//       |                ||   (1st src)    ↓
//       |            ----||---> bufferExportingOperator
//       ↓           |    ||                ↓
//       |           |    ||    unorderedDistinctFilterer
// in-memory distinct     ||                ↓
//       |                ||       disk-backed distinct
//       |                ||                |
//       |                ↓↓                |
//        ---------> disk spiller <--------
//                        ||
//                        ||
//                        ↓↓
//                      output
```

The alternative approach would require introducing a connection between `in-memory distinct` and `unorderedDistinctFilterer`.

Unfortunately, I don't see a better way around this issue since it is very subtle and requires careful coordination between several components. Possibly, if we were to change the disk-spilling infrastructure, maybe something better would come up, but I believe this is a one-off issue and having tight coupling of several components seems acceptable to me in this special case (as a reminder, the "specialness" of the case is due to the nature of in-memory unordered distinct having streaming-like behavior).


<!-- Sent from Reviewable.io -->

2021-01-12 02:22 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/unordered_distinct.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MQlIU3q3SnRjDdP0iaN:-MQo8-Iq-x3GFwX38hNn:byzs5kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb35182625987cde5faf968a30e0d40b9e6e992/pkg/sql/colexec/unordered_distinct.go#L81)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Let me describe the current peculiar situation in a lot of details.

Suppose the in-memory unordered distinct has already read 3 batches `A`, `B`, `C`, appended the distinct tuples from all of them into the hash table and emitted them. Now it reads batch `D` which has some new distinct tuples, but during the appending of these new distinct tuples the hash table reaches its limit.

Here is what happens in `distinctBuild`:
1. batch `D` is updated in-place to remove the duplicate tuples within itself (this doesn't interact with tuples from `A`, `B`, and `C` that are in the hash table)
2. batch `D` is updated in-place again to remove the "global" duplicates. Now `D`'s selection vector only contains tuples that are "globally" distinct which should be emitted into the output
3. however, before we can emit them into the output, we need to update the hash table to include these tuples, and this is where we hit an OOM which could occur for two reasons in `appendAllDistinct`
3.1) because of appending the tuples to `ht.vals`
3.2) because of reallocating internal slices of the hash table (`buildFromBufferedTuples`)
If the former is the case, then the hash table ends up in an inconsistent state, and we'll need to repair it before using.
4. regardless of when exactly an OOM error happened, a panic has occurred and we exited the execution of the in-memory unordered distinct. And what we have is the following: batch `D` contains distinct tuples that need to be emitted into the output and those tuples have been appended to the hash table.

Now the question arises on how to handle the fallback to the external distinct, and the fallback is subject to the following requirements:
1. all tuples of updated in-place batch `D` need to be emitted somehow, without being filtered by the hash table since the filtering of that batch has already occurred
2. all tuples in batch `E` and all consequent ones have to be checked against already emitted tuples from batches `A`, `B`, `C`, and `D` (assuming `D` is somehow emitted).

The second requirement can be satisfied in a relatively clean way by `unorderedDistinctFilterer` planned on top of the input to the disk-backed distinct; however, the first requirement is very tricky to get right. We can emit updated batch `D` in two places - either in the in-memory operator before panicking (this was my original approach) or in the disk-backed operator (after the panic and the fallback have occurred). I like the latter option since the former requires catching OOMs and is very-very hacky in order to not catch OOMs that are coming from other operators.

Assuming that we want to emit batch `D` from the disk-backed operator, we have a conflict with the `unorderedDistinctFilterer` - the hash table already contains all tuples from `D`, so we cannot filter that particular batch against the hash table because then we would never emit tuples from `D`. The solution I'm proposing right now is to have a special marker wrapper around batch `D` that indicates that filtering against the hash table should not be performed on this batch in particular.

An alternative approach would be somehow connecting the in-memory unordered distinct and `unorderedDistinctFilterer` directly so that the former in its `ExportBuffered` method could indicate (by a callback or modifying the filterer's internal state) that the next batch read by the filterer should not be filtered. However, this approach seems even worse.

There are some other complications due to the disk-spilling infrastructure. Here is the diagram of what the setup looks like with the current PR:
```
//        -------------  input  -----------
//       |                ||                | (2nd src)
//       |                ||   (1st src)    ↓
//       |            ----||---> bufferExportingOperator
//       ↓           |    ||                ↓
//       |           |    ||    unorderedDistinctFilterer
// in-memory distinct     ||                ↓
//       |                ||       disk-backed distinct
//       |                ||                |
//       |                ↓↓                |
//        ---------> disk spiller <--------
//                        ||
//                        ||
//                        ↓↓
//                      output
```

The alternative approach would require introducing a connection between `in-memory distinct` and `unorderedDistinctFilterer`.

Unfortunately, I don't see a better way around this issue since it is very subtle and requires careful coordination between several components. Possibly, if we were to change the disk-spilling infrastructure, maybe something better would come up, but I believe this is a one-off issue and having tight coupling of several components seems acceptable to me in this special case (as a reminder, the "specialness" of the case is due to the nature of in-memory unordered distinct having streaming-like behavior).

</blockquote></details>

One idea that could simplify things a bit is that we could assume in `unorderedDistinctFilterer` that the first batch it sees is the already filtered one and emit it without filtering. It is possible to make this assumption because the in-memory unordered distinct will export at most one batch, and it will export no tuples only when the hash table is empty (which we can detect in the filterer). I added another commit implementing this idea, and I think it is a bit cleaner that the marker batch wrapper.


<!-- Sent from Reviewable.io -->

2021-01-12 15:22 UTC, asubiotto requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/unordered_distinct.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-MQlIU3q3SnRjDdP0iaN:-MQrAEv-7_QwKAYGojx3:b-z7urir) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb35182625987cde5faf968a30e0d40b9e6e992/pkg/sql/colexec/unordered_distinct.go#L81)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

One idea that could simplify things a bit is that we could assume in `unorderedDistinctFilterer` that the first batch it sees is the already filtered one and emit it without filtering. It is possible to make this assumption because the in-memory unordered distinct will export at most one batch, and it will export no tuples only when the hash table is empty (which we can detect in the filterer). I added another commit implementing this idea, and I think it is a bit cleaner that the marker batch wrapper.
</blockquote></details>

Agreed with the latest suggestion. I think it's nice to keep the specialization as contained as possible. The commit looks good. I'll give this another review in its final state.


<!-- Sent from Reviewable.io -->

2021-01-12 22:36 UTC, yuzefovich commented
Alright, I think I finally stabilized the test (the difficulty was that without limiting the number of tuples, it could take extremely long under stress in very rare circumstances; then I added a limit for max num tuples, and now we might not spill because of it). Anyway, I think it is RFAL.

2021-01-13 11:27 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58006#-:-MQvUzfg2qeogzvmtWcE:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-13 16:15 UTC, yuzefovich commented
TFTR!

bors r+

2021-01-13 17:52 UTC, yuzefovich commented
bors r+

2021-01-13 21:36 UTC, yuzefovich commented
Flake.

bors r+

2021-01-13 22:54 UTC, yuzefovich commented
Another flake (for which I opened a PR).

bors r+

2021-01-14 03:55 UTC, yuzefovich commented
Flake again, rebased on top of master.

bors r+

2021-01-14 04:37 UTC, merged