sql: add qualification prefix for user-defined schema names
cockroachdb/cockroach pull request #58617
Opened 2021-01-07 17:06 UTC by the-ericwang35

Fixes https://github.com/cockroachdb/cockroach/issues/57738.

Previously, event logs were not capturing the qualified schema names
for create_schema, drop_schema, rename_schema and alter_schema_owner events.
This PR changes the event logs to use the qualified schema names.
Tests were also updated to reflect these changes.

Release note (bug fix): add qualification prefix for user-defined schema names.

2021-01-07 17:06 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/58617)
<!-- Reviewable:end -->

2021-01-21 22:57 UTC, ajwerner requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/resolver.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58617#-MRb9gHmBbkerpfL3Mre:-MRb9gHnBiyPIgv_wBiB:bvbio5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/30185114daa2643eeb42de3dac8842e0cf1cf691/pkg/sql/resolver.go#L429)):*
> ```Go
> // schema represented by the provided descriptor.
> func (p *planner) getQualifiedSchemaName(
> 	ctx context.Context, desc catalog.Descriptor,
> ```

this should take `catalog.SchemaDescriptor`


<!-- Sent from Reviewable.io -->

2021-01-21 22:58 UTC, ajwerner reviewed
Other than that one thing <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58617#-:-MRb9lZw-k5foSAJyFnf:b-gpmn5z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @the-ericwang35)



<!-- Sent from Reviewable.io -->

2021-01-21 23:06 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58617)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/resolver.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58617#-MRb9gHmBbkerpfL3Mre:-MRbB_gP7r60zH6r5u-6:bd708mq) ([raw file](https://github.com/cockroachdb/cockroach/blob/30185114daa2643eeb42de3dac8842e0cf1cf691/pkg/sql/resolver.go#L429)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this should take `catalog.SchemaDescriptor`
</blockquote></details>

Done, changed it to `catalog.SchemaDescriptor`


<!-- Sent from Reviewable.io -->

2021-01-22 21:49 UTC, lucy-zhang approved these changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58617)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-01-25 04:25 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58617#-:-MRrmbpz63zzUsnJDFer:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-25 15:07 UTC, the-ericwang35 commented
TFTR!

bors r+

2021-01-25 15:51 UTC, merged