storageccl: implement on-the-fly decrypting remote sst reader
cockroachdb/cockroach pull request #58631
Opened 2021-01-08 01:49 UTC by dt

The chunked encrypted encoding means we can jump to arbitrary chunks and
start decrypting. This allows implementing ReadAt and thus a pebble SST
reader can be created that decrypts on the fly, as it reads.

Release note: none.

2021-01-08 01:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/58631)
<!-- Reviewable:end -->

2021-01-15 20:27 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/storageccl/encryption.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6ebRD2xeSDu478pG7:-MR6ebRD2xeSDu478pG8:b-m27nif) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L225)):*
> ```Go
> 	}
> 
> 	r.chunk = -1 // invalidate the current buffered chunk while we fill it.
> ```

is this needed?
___
*[pkg/ccl/storageccl/encryption.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6g94r2b6spJQPL70s:-MR6g94r2b6spJQPL70t:bpg7493) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L232)):*
> ```Go
> 		return err
> 	}
> 	r.buf = r.buf[:n]
> ```

n could be 0 -- is this a problem (i.e. can we call r.g.Open below?)
___
*[pkg/ccl/storageccl/encryption.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6hQ9Q8yqk3erhNZUO:-MR6hQ9Q8yqk3erhNZUP:bz81hpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L279)):*
> ```Go
> 
> 		// Return EOF if this was the last chunk (<chunksize).
> 		if len(r.buf) < encryptionChunkSizeV2 {
> ```

if I understand correctly, r.buf contains depcrypted 64KB (or less) chunk.
What happens if `p` is say, 10 bytes, and my file was 20 bytes?
I think I'll return `10, eof` here, which is not correct.

Am I wrong?
___
*[pkg/ccl/storageccl/encryption_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6iR00BDAEZJL5efOD:-MR6iR00BDAEZJL5efOE:b3clsdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption_test.go#L150)):*
> ```Go
> 			require.Equal(t, expectedEmptyErr != nil, gotEmptyErr != nil)
> 			require.Equal(t, expectedEmpty, gotEmpty)
> 		})
> ```

Perhaps few more test cases?

Test case for file w/ 1 chunk < 32 bytes; 
   * ReadAt into a large buf (>32)
   * ReadAt into a tiny buffer (1 - 10 bytes)
Test case 1 byte file.


<!-- Sent from Reviewable.io -->

2021-01-15 20:54 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/ccl/storageccl/encryption.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6ebRD2xeSDu478pG7:-MR6josy8UiwJKELyJLw:b-vm1h68) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L225)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

Yes (depending on what callers do if they get an error): `r.chunk` indicated which chunk's data is currently in`r.buf`. Just below this, we're going to overwrite r.buf with first the ciphertext, then the cleartext of a new chunk, and then update r.chunk to reflect what's in it. If we return after we overwrite r.buf but before we successfully load the the new chunk and update r.chunk, we need to make sure we no longer claim to have the previous chunk still loaded. 

This is unlikely to be an issue in practice: if a caller said "readAt(5) and we loaded the chunk containing 5, then said readAt(100) and got an error become someone tampered with some bytes in chunk containing 100, they probably would either a) bubble that error and close/discard this reader entirely, or b) try to read 100 again, but technically, they could ask to read 5 again, in which case we should try to load it again, since it isn't loaded any more.
___
*[pkg/ccl/storageccl/encryption.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6g94r2b6spJQPL70s:-MR6oGsu1G-OMqIrIEkl:b-hucj5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L232)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

n could be 0 -- is this a problem (i.e. can we call r.g.Open below?)
</blockquote></details>

that's fine -- `r.Open(nil)` will fail to authenticate which is what we want (it indicates someone tampered with the file, so failing to authenticate is correct)
___
*[pkg/ccl/storageccl/encryption.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6hQ9Q8yqk3erhNZUO:-MR6nu3m0n8xHQw34Obu:bvundog) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L279)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

if I understand correctly, r.buf contains depcrypted 64KB (or less) chunk.
What happens if `p` is say, 10 bytes, and my file was 20 bytes?
I think I'll return `10, eof` here, which is not correct.

Am I wrong?
</blockquote></details>

If `p` is length 10 and we have 20 bytes of cleartext, we'd have already returned `10, nil` in the case above this one (`if read == len(p)`). We only get here if we ran out of r.buf without filling `p`, and if that happened and r.buf is short, we know we're at EOF.
___
*[pkg/ccl/storageccl/encryption_test.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6iR00BDAEZJL5efOD:-MR6oE1g6kp-LaSNvaNB:ba8m73b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption_test.go#L150)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Perhaps few more test cases?

Test case for file w/ 1 chunk < 32 bytes; 
   * ReadAt into a large buf (>32)
   * ReadAt into a tiny buffer (1 - 10 bytes)
Test case 1 byte file.
</blockquote></details>

the rand test 


<!-- Sent from Reviewable.io -->

2021-01-16 13:38 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/storageccl/encryption.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6ebRD2xeSDu478pG7:-MRAOist2VCiu6NC1FoR:b8bqkaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L225)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Yes (depending on what callers do if they get an error): `r.chunk` indicated which chunk's data is currently in`r.buf`. Just below this, we're going to overwrite r.buf with first the ciphertext, then the cleartext of a new chunk, and then update r.chunk to reflect what's in it. If we return after we overwrite r.buf but before we successfully load the the new chunk and update r.chunk, we need to make sure we no longer claim to have the previous chunk still loaded. 

This is unlikely to be an issue in practice: if a caller said "readAt(5) and we loaded the chunk containing 5, then said readAt(100) and got an error become someone tampered with some bytes in chunk containing 100, they probably would either a) bubble that error and close/discard this reader entirely, or b) try to read 100 again, but technically, they could ask to read 5 again, in which case we should try to load it again, since it isn't loaded any more.
</blockquote></details>

technically, doing anything after an error is illegal and undefined.
I'm okay w/ being paranoid though.
___
*[pkg/ccl/storageccl/encryption.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6g94r2b6spJQPL70s:-MRAP1_Z4YSM3hkGZ7sn:b-tpxi4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L232)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

that's fine -- `r.Open(nil)` will fail to authenticate which is what we want (it indicates someone tampered with the file, so failing to authenticate is correct)
</blockquote></details>

Let's say the caller tries to read way past end of the file -- as the first call.
You would expect to get an io.EOF in that case.  However, reading more than 1 byte past the end could return EINVAL (as in invalid offset) as opposed to EIOF -- and afaik, that happens on linux (I'm not sure what golang might do -- maybe it changes error code).

So, in that case we would return some authentication error -- which I guess is fine, but I just want to make sure that that's what we want.
___
*[pkg/ccl/storageccl/encryption.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6hQ9Q8yqk3erhNZUO:-MRAPn1L-RGr1vTz8-7T:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L279)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

If `p` is length 10 and we have 20 bytes of cleartext, we'd have already returned `10, nil` in the case above this one (`if read == len(p)`). We only get here if we ran out of r.buf without filling `p`, and if that happened and r.buf is short, we know we're at EOF.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2021-01-21 17:56 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/ccl/storageccl/encryption.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6ebRD2xeSDu478pG7:-MRa2V-JC96yiBmMM9Pq:bkgygf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L225)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

technically, doing anything after an error is illegal and undefined.
I'm okay w/ being paranoid though.
</blockquote></details>

I don't think that's quite true -- if you get an error from one `ReadAt` call you're allowed to try it again, try a different one, etc. So we want to make sure we don't have one failed `ReadAt` leave the reader in a state where a future call would return incorrect results. In practice I think most callers presented with an error would bail and close the reader, but they're within their rights to try to readAt again, so this isn't even just paranoia. 
___
*[pkg/ccl/storageccl/encryption.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58631#-MR6g94r2b6spJQPL70s:-MRa2plBBxw5V4aNt8xp:bsh4vuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea81e05dba9d77d159a856872b5af55467cab1be/pkg/ccl/storageccl/encryption.go#L232)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's say the caller tries to read way past end of the file -- as the first call.
You would expect to get an io.EOF in that case.  However, reading more than 1 byte past the end could return EINVAL (as in invalid offset) as opposed to EIOF -- and afaik, that happens on linux (I'm not sure what golang might do -- maybe it changes error code).

So, in that case we would return some authentication error -- which I guess is fine, but I just want to make sure that that's what we want.


</blockquote></details>

Yep, indeed, that is what we want: we're using authenticated encryption, to ensure we detect tampering, so presumably we also care about an attacker truncating the ciphertext file. We only return a real EOF when we decrypt and authenticate the short block that indicates end of cleartext -- anything else could be result of something malicious.  For all we know, our "read way past the end of the file" is only past the end of the tampered file. All we know for sure is that we can't yield some authenticated bytes at that offset.


<!-- Sent from Reviewable.io -->

2021-01-25 19:22 UTC, dt commented
@miretskiy is this good to go?

2021-01-25 21:19 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58631)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)



<!-- Sent from Reviewable.io -->

2021-01-25 21:20 UTC, dt commented
TFTR!

bors r+

2021-01-25 23:22 UTC, merged