colexec,coldata: use Vec.Copy instead of Vec.Append
cockroachdb/cockroach pull request #59030
Opened 2021-01-15 04:20 UTC by yuzefovich

This commit switches several usages of `Vec.Append` method to `Vec.Copy`
instead, the most notable change is in the ordered aggregator. In order
to facilitate that we introduced another temporary batch as a scratch
space for the case when the second part of the internal batch needs to
be moved to the beginning. This also allows us to remove `Vec.SetLength`
method introduced for the use of `Append` in the ordered aggregator.
Usage of `Append` is now prohibited in `sql/col*` packages (enforced by
a linter rule).

The reason for making this change is that in pretty much all cases
whenever we need to copy over some tuples, we already know that there is
enough capacity in the batch, and if that's not the case, it is likely
that `appendOnlyBufferedBatch` should be used.

This commit also removes the updating of the offsets on the source of
`Vec.Append` for Bytes vectors since I believe it is no longer necessary
given the recent fix to `Batch.SetLength`.

Release note: None

2021-01-15 04:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59030)
<!-- Reviewable:end -->

2021-01-15 04:21 UTC, yuzefovich commented
First three commits are in a separate PR. For more details about the interaction between flat bytes and the ordered aggregator see #42070.

2021-01-19 09:48 UTC, asubiotto requested changes
This is a good change

> Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-:-MRP1CZhA0va3TeVsyrl:bzte63)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/vec_tmpl.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-MRP1dHYAmX__yayas9O:-MRP1dHYAmX__yayas9P:b-algzh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6962ba31e8b7e9d74c65f9199d29a9846c087/pkg/col/coldata/vec_tmpl.go#L81)):*
> ```Go
> 				// Note that here we rely on the fact that selection vectors are
> 				// increasing sequences.
> 				fromCol.UpdateOffsetsToBeNonDecreasing(sel[len(sel)-1] + 1)
> ```

Why can we remove this?
___
*[pkg/testutils/lint/lint_test.go, line 1797 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-MRP1Tq6CxPa2d35sVrs:-MRP1Tq6CxPa2d35sVrt:b-4hi7a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a78a117f36686e9167cd40eda9e17275a5d4ff92/pkg/testutils/lint/lint_test.go#L1797)):*
> ```Go
> 	})
> 
> 	t.Run("TestVectorizedAppendToVector", func(t *testing.T) {
> ```

Why can't we just remove the Append method?


<!-- Sent from Reviewable.io -->

2021-01-19 18:52 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59030)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/col/coldata/vec_tmpl.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-MRP1dHYAmX__yayas9O:-MRQy-1rBV2yGJt6hg2A:b-jesgn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5c6962ba31e8b7e9d74c65f9199d29a9846c087/pkg/col/coldata/vec_tmpl.go#L81)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why can we remove this?
</blockquote></details>

As I mentioned in the commit message, I think it is no longer necessary because of the fix to `Batch.SetLength`. It has always been the caller's responsibility to make sure that `Get`ting any element is safe, but because of the bug with `Batch.SetLength` and the selection vectors in #43720 we added the update of offsets here. I think it was misdiagnosed at that time, and we don't have to update offsets here. 

Also, `appendOnlyBufferedBatch.append`'s signature is such that it takes in `coldata.Batch` on which the length must be set (otherwise, we don't know how many tuples to append).
___
*[pkg/testutils/lint/lint_test.go, line 1797 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-MRP1Tq6CxPa2d35sVrs:-MRQxMP6CRfbktrA5_nN:baoljzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a78a117f36686e9167cd40eda9e17275a5d4ff92/pkg/testutils/lint/lint_test.go#L1797)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why can't we just remove the Append method?
</blockquote></details>

We have `appendOnlyBufferedBatch` that uses `Append` method. I think it'd be very annoying to try to change that since in that case we do want the "append" behavior of Golang.


<!-- Sent from Reviewable.io -->

2021-01-20 09:21 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59030#-:-MRU5BvQDQoCRr6scBCs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-20 20:07 UTC, yuzefovich commented
TFTR!

bors r+

2021-01-20 20:56 UTC, merged