sql: add support for dropping regions from a database
cockroachdb/cockroach pull request #59098
Opened 2021-01-18 04:12 UTC by arulajmani

First commit from: https://github.com/cockroachdb/cockroach/pull/58688

See individual commits for details.

2021-01-18 04:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59098)
<!-- Reviewable:end -->

2021-01-18 19:38 UTC, ajstorm requested changes
Very impressive piece of work!  Nice job!  :tada: 

Nits on commit records (all around readability):

> If ascertained, the label is removed from the list of EnumMembers.

When reading this, it's not directly obvious what "ascertained" is referring to.  Instead it might be better to say "If it is confirmed that the label is not in use..."  Additionally, the following sentence could be changed to "If the label is still in use..."

> provided value if it isn't used as a value in any table's row.

Would be good to state what happens if the value is in use.

> as it is susceptible to the value being used in a table expression (such as a computed column)
Not clear what you mean by susceptible here.  It'll fail?  Corrupt the table with the computed column?

> Reviewed 17 of 17 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MRLZOdG43GHWhhDA-b6:b-2fp935)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLrHjMCdWuaguxv_P4:-MRLrHjNBl9sXIAVrY6D:bh6wer8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L273)):*
> ```Go
> 
> 	if !dbDesc.IsMultiRegion() {
> 		return nil, errors.New("database is not multi-region")
> ```

Nit: "database has no regions to drop"?
___
*[pkg/sql/alter_database.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLr_4MEdCIC1jPMWTV:-MRLr_4MEdCIC1jPMWTW:b-ucymbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L277)):*
> ```Go
> 
> 	if dbDesc.RegionConfig.PrimaryRegion == descpb.RegionName(n.Region) {
> 		return nil, errors.New("cannot drop primary region")
> ```

Might be good to add a hint here.  If the users want to drop the primary region, they first have to make another region the primary region.
___
*[pkg/sql/alter_database.go, line 302 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLv8yU73rvQgKjQ_JG:-MRLv8yU73rvQgKjQ_JH:b-xr88je) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L302)):*
> ```Go
> 	}
> 
> 	idx := -1
> ```

Seems like this -1 is only required because we don't know if the above function did anything.  Could we not get `dropEnumValue` to return `dropped` or `found` and if false, skip the rest of this function?  That way we could start the searching for the region from a much nicer `0`.
___
*[pkg/sql/alter_database.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLujHU8yhDisB29pZ0:-MRLujHU8yhDisB29pZ1:b6v4a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L312)):*
> ```Go
> 		n.desc.RegionConfig.Regions[idx+1:]...)
> 
> 	return params.p.writeNonDropDatabaseChange(
> ```

Can we log an event after we write the change?
___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MRLbFFP8AgkOfpC7Tf0:boatbr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
> ```Go
> 		if params.p.SessionData().SafeUpdates {
> 			err = pgerror.DangerousStatementf(
> 				"DROP VALUE is unsafe if the enum label is used in view/default/computed expressions")
> ```

What does "unsafe" mean here?  I think we want to be a bit more descriptive here as to what can happen.
___
*[pkg/sql/alter_type.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLcSzi9-Ag7ZKieyn9:-MRLcSzi9-Ag7ZKieynA:bjkbtmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L184)):*
> ```Go
> 	ctx context.Context, n *alterTypeNode, node *tree.AlterTypeDropValue,
> ) error {
> 	if n.desc.Kind != descpb.TypeDescriptor_ENUM {
> ```

I might be missing something here, but doesn't this also have to include the multi-region enum?  Alternatively, if we're catching that somewhere else, do we need a more specific error message below, in case users try to remove values from the multi-region enum?
___
*[pkg/sql/alter_type.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLd1TJ7rDapjUDP7Pe:-MRLd1TJ7rDapjUDP7Pf:b2drhf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L195)):*
> ```Go
> 		return err
> 	}
> 	return p.writeTypeSchemaChange(ctx, n.desc, tree.AsStringWithFQNames(n.n, p.Ann()))
> ```

Can we write an event log  message here?
___
*[pkg/sql/alter_type.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLw1zQ6Cp9CYwqBnd7:-MRLw1zQ6Cp9CYwqBnd8:bamep4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_type.go#L185)):*
> ```Go
> ) error {
> 	if desc.Kind != descpb.TypeDescriptor_ENUM &&
> 		desc.Kind != descpb.TypeDescriptor_MULTIREGION_ENUM {
> ```

This catches my comment from the previous commit, but I still worry that we may not be 100% complete here.  What prevents a user from dropping a value from the multi-region enum explicitly?
___
*[pkg/sql/descriptor.go, line 261 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLww1289app49EVZ2Y:-MRLww1289app49EVZ2Z:b-o2xg52) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/descriptor.go#L261)):*
> ```Go
> }
> 
> // addActiveRegionToRegionConfig adds the supplied region to the RegionConfig in
> ```

Nit: Comment could use updating.  Only adds if region is active.
___
*[pkg/sql/type_change.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLdol94UhUAiFV1sDw:-MRLdolA-puDb-Fym_z9:bcsjlh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L179)):*
> ```Go
> 					}
> 					if !canRemove {
> 						return errors.Newf("could not remove enum value: %q", member.LogicalRepresentation)
> ```

Nit: Here it would be nice if we returned the first table found which references the enum.  If users really want to get rid of this enum value, they may want to modify rows in the underlying table to clean things up.
___
*[pkg/sql/type_change.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLhyscCmZkcwarDsMl:-MRLhyscCmZkcwarDsMm:b-hmibrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L285)):*
> ```Go
> 		// First, deal with all members that we initially hoped to remove but
> 		// now need to be promoted back to writable.
> 		for i := range typeDesc.EnumMembers {
> ```

Super Nit: This logic is similar to the logic a bit higher up (but in the reverse direction).  I'm wondering if it cleans things up if we create a function to perform this cleanup which takes a function pointer that specifies the direction we're going?  That way we could handle both cases with the same function (but different function pointers).
___
*[pkg/sql/type_change.go, line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLhMRq1rOzXkvRdK6N:-MRLhMRq1rOzXkvRdK6O:b-qt2y32) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L301)):*
> ```Go
> 			}
> 		}
> 		typeDesc.EnumMembers = typeDesc.EnumMembers[:idx]
> ```

Nit: This is very similar logic to above.  Could we not create a function `cleanupTransitioningEnumValues()` which would remove all enum values in the READ_ONLY state?  That should work in both cases, as we deal with the ones we want to keep first.
___
*[pkg/sql/type_cha [...]

2021-01-19 03:38 UTC, arulajmani reviewed
Thanks for the thorough review!  I updated the original PR (linked above) for r1 as well with my changes in response to the comments here (the ones on that commit). I think I got everything bar a couple nits, so this should be RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MRNgVrt4qcyKYbT64gq:b5wblih)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLr_4MEdCIC1jPMWTV:-MRNS_Kf93FIKw5ifvCQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L277)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Might be good to add a hint here.  If the users want to drop the primary region, they first have to make another region the primary region.
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 302 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLv8yU73rvQgKjQ_JG:-MRNTOno4w_KVTe2DGTC:bix1eiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L302)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Seems like this -1 is only required because we don't know if the above function did anything.  Could we not get `dropEnumValue` to return `dropped` or `found` and if false, skip the rest of this function?  That way we could start the searching for the region from a much nicer `0`.
</blockquote></details>

Right now, `dropEnumValue` does return an error if the region isn't found on the enum, so the rest of the function will be skipped and we won't get here. That being said, I'm slightly inclined to keep the -1 and in fact add an explicit check to make sure we did find the region on the database descriptor when attempting to remove it. The reason for this is that keeping the db desc and type descriptor in sync is rather brittle, and if a problem occurs a descriptive error would be better than accidentally deleting the first region or a nil pointer exception. Wdyt? 
___
*[pkg/sql/alter_database.go, line 312 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLujHU8yhDisB29pZ0:-MRN_i9O4ofdfSuaogQ1:bb8dqn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L312)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we log an event after we write the change?
</blockquote></details>

Yup, done! 
___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MRNLDlK4eePO6tvffYI:b-f3xc39) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

What does "unsafe" mean here?  I think we want to be a bit more descriptive here as to what can happen.
</blockquote></details>

They'll stop working :( 
___
*[pkg/sql/alter_type.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLcSzi9-Ag7ZKieyn9:-MRMTH8f7SKTaJ2BMJQW:b-5uf34u) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L184)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I might be missing something here, but doesn't this also have to include the multi-region enum?  Alternatively, if we're catching that somewhere else, do we need a more specific error message below, in case users try to remove values from the multi-region enum?
</blockquote></details>

I think I add to this in the second commit -- the first one was just to add support for regular enums. 
___
*[pkg/sql/alter_type.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLd1TJ7rDapjUDP7Pe:-MRNaQDP9YXO8eEkrNUf:bkacwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L195)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Can we write an event log  message here?
</blockquote></details>

Discussed offline, the generic `ALTER TYPE` event that's logged in the call stack above should be fine for this. 
___
*[pkg/sql/alter_type.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLw1zQ6Cp9CYwqBnd7:-MRN2p49A_PIp3JShWRt:b-fcozop) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_type.go#L185)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

This catches my comment from the previous commit, but I still worry that we may not be 100% complete here.  What prevents a user from dropping a value from the multi-region enum explicitly?
</blockquote></details>

There's a check when creating the AlterType plan node that disallows users from modifying multi-region enums using regular Alter Type commands. This does deserve a test though, now that we have `ALTER TYPE DROP VALUE` implemented -- I'll add one. 
___
*[pkg/sql/type_change.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLdol94UhUAiFV1sDw:-MRN5vko4g0xQ5ljgQWt:b-bb05ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L179)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Here it would be nice if we returned the first table found which references the enum.  If users really want to get rid of this enum value, they may want to modify rows in the underlying table to clean things up.
</blockquote></details>

I've changed return type of `canRemoveEnumLabel` to just an error. Now, it returns a descriptive error if the value can't be removed because it is used by a table. Lemme know what you think!
___
*[pkg/sql/type_change.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLhyscCmZkcwarDsMl:-MRNcSHz316jZTuDF7PP:b-jv0fg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L285)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Super Nit: This logic is similar to the logic a bit higher up (but in the reverse direction).  I'm wondering if it cleans things up if we create a function to perform this cleanup which takes a function pointer that specifies the direction we're going?  That way we could handle both cases with the same function (but different function pointers).
</blockquote></details>

This and the comment below aren't done yet, I'll probably tackle them post demo on the original PR. 
___
*[pkg/sql/type_change.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLiXCaCk6-hG6jsLuC:-MRN9f3HEQFnJIIL4PZF:b-htt06a) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L394)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

For both of these functions, what will happen if the Capability is set, but the caller hasn't specified a Direction?  Can we add assertions to ensure that if Capability is set than Direction has to be set?
</blockquote></details>

Good catch, this definitely deserves some validation checks. Added! 
___
*[pkg/sql/type_change.go, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLxdrvBEfP5dh6hQGy:-MRNdX4G0Qw8d50oV4iU:b-wf1shu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L303)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

This seems like a pretty bad e [...]

2021-01-20 03:45 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 302 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLv8yU73rvQgKjQ_JG:-MRSq-F10h1WQhkFTL9j:b-ad8wdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L302)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Right now, `dropEnumValue` does return an error if the region isn't found on the enum, so the rest of the function will be skipped and we won't get here. That being said, I'm slightly inclined to keep the -1 and in fact add an explicit check to make sure we did find the region on the database descriptor when attempting to remove it. The reason for this is that keeping the db desc and type descriptor in sync is rather brittle, and if a problem occurs a descriptive error would be better than accidentally deleting the first region or a nil pointer exception. Wdyt? 
</blockquote></details>

I'm fine with checking, but I'm not a fan of `-1` meaning "not found".  If you want to check, why not just create a bool called `found` and set it in the loop if you find it?  That way this code reads better. 
___
*[pkg/sql/alter_database.go, line 279 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRSpN1R3QboeSRQvY90:-MRSpN1R3QboeSRQvY91:be1091z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc1d6a73eb894b6e76cbfdd98d6e9b00e0661b8/pkg/sql/alter_database.go#L279)):*
> ```Go
> 		return nil, errors.WithHint(
> 			errors.Newf("cannot drop primary region %q", dbDesc.RegionConfig.PrimaryRegion),
> 			"you must designate another region as the primary region or remove all other regions "+
> ```

Nit: I like the hint, but I find it a bit confusing.  If you designate another region as the primary region, you still can't drop the primary region (you can drop the old primary region, but that's not what this hint is saying).  Might be clearer if you say "before attempting to drop region %q".
___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MRSqT-r1QSPtKOxUDJD:b6psvb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

They'll stop working :( 
</blockquote></details>

can we say that they'll stop working, and what the user will have to do to get out of that (alter column? drop column?)
___
*[pkg/sql/alter_type.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLcSzi9-Ag7ZKieyn9:-MRSqhcH51UT9kVj7EOv:b66xf55) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L184)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think I add to this in the second commit -- the first one was just to add support for regular enums. 
</blockquote></details>

All good, caught with comment below.
___
*[pkg/sql/alter_type.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLw1zQ6Cp9CYwqBnd7:-MRSqpPwCnVPtd1EnSEZ:b63zopr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_type.go#L185)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

There's a check when creating the AlterType plan node that disallows users from modifying multi-region enums using regular Alter Type commands. This does deserve a test though, now that we have `ALTER TYPE DROP VALUE` implemented -- I'll add one. 
</blockquote></details>

cool, thx!
___
*[pkg/sql/type_change.go, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLdol94UhUAiFV1sDw:-MRSr0t8DuOJr3fDuQii:b-aulzgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L179)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I've changed return type of `canRemoveEnumLabel` to just an error. Now, it returns a descriptive error if the value can't be removed because it is used by a table. Lemme know what you think!
</blockquote></details>

me likey
___
*[pkg/sql/type_change.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLiXCaCk6-hG6jsLuC:-MRSrqpA9z8UpnNWGnUM:b-36zztv) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L394)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Good catch, this definitely deserves some validation checks. Added! 
</blockquote></details>

I don't see it, but maybe Reviewable is playing tricks on me?
___
*[pkg/sql/type_change.go, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLxdrvBEfP5dh6hQGy:-MRSrIe6CyR174guixNj:bgf0v0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L303)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

IIUC if there is any error during `OnFailOrCancel` (which calls this `cleanupEnumLabels`), then it'll be periodically retried, If the error was transient, then an eventual retry should succeed. If not, then we're in this bad state where region is left in READ ONLY mode as you note. I don't know if there is much a user can do once they're in this state, but this is no different than any schema change operation failing and the rollback encountering an issue.
</blockquote></details>

Is it worth providing additional context here?  Or will users familiar with CRDB immediately understand how to resolve this (wait and/or retry)?
___
*[pkg/sql/type_change.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLyrih5yGPHleNYda-:-MRSr__PERms0Iy9nbXW:b-3abqc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L407)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

With my changes to the return type of this function, Im now able to return a more descriptive error to the user. 
</blockquote></details>

niiiice
___
*[pkg/sql/type_change_test.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLjXBt7g5c4Taaix9Y:-MRSrv-XB_WSAdp0HtOQ:b2nid0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change_test.go#L160)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Yup, I'll open an issue for this. 
</blockquote></details>

thx
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLm54j05jTRnXojqDc:-MRSsQcM4QxEKWt02WWP:b-qhce0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L351)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

With the `canRemoveEnumLabel` signature changes above this is made slightly better. 
</blockquote></details>

Much better, but I'm wondering if we can do even better?  Could we not say that it's in use and reference the view?  The new error, as written tells the user why, but there's no way to easily fix it.
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLntW09XmlJgxy95-l:-MRSsizeA1OEZIVMUSZR:b-tlbldq) ([raw fi [...]

2021-01-20 18:09 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 302 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLv8yU73rvQgKjQ_JG:-MRVvnz49S_oKi_khWTL:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L302)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'm fine with checking, but I'm not a fan of `-1` meaning "not found".  If you want to check, why not just create a bool called `found` and set it in the loop if you find it?  That way this code reads better. 
</blockquote></details>

Done. 
___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MRVyy_6C21tx4lbrxyB:btrdkm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

can we say that they'll stop working, and what the user will have to do to get out of that (alter column? drop column?)
</blockquote></details>

Yeah, I'll make the change in the original PR. 
___
*[pkg/sql/type_change.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLiXCaCk6-hG6jsLuC:-MRVUdInDoJ_8hWmym7r:b-u4x49u) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L394)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I don't see it, but maybe Reviewable is playing tricks on me?
</blockquote></details>

It's in `type_desc.go`, in the Validate method. 
___
*[pkg/sql/type_change.go, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLxdrvBEfP5dh6hQGy:-MRVxpcnAcLrxO0HR6Ua:brfkjms) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L303)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is it worth providing additional context here?  Or will users familiar with CRDB immediately understand how to resolve this (wait and/or retry)?
</blockquote></details>

I'm inclined to say the latter as we this is no different than any other schema change operation we support today.
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLm54j05jTRnXojqDc:-MRVZXg8DA60aPuLCEd1:bde1scc) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L351)):*
> Could we not say that it's in use

But we don't know this. All we know is that the validation query failed, which can happen for any reason. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLntW09XmlJgxy95-l:-MRVc_VA9LXTU7Rc2DFV:b-g4p6g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L367)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is there any way we can catch this further up the stack and convert it to something more understandable?  I have to imagine that most users who see this will end up opening a support ticket (which will be tricky to resolve on our end), which would be unfortunate if we could avoid that with a bit more work on our side.
</blockquote></details>

I briefly dug into it and it doesn't seem as straight forward -- this error panics in the optimizer, in `resolveAndRequireType`, which is called from a bunch of call sites in addition to the function that adds default values form columns that don't have an explicit value. I don't think we can assume that the error happened because of a bad enum removal. 

It is worth noting that this is temporary -- I do have a couple of ideas on how to solve these cases with views/default exprs, and I hope to prototype that as follow ups. 


<!-- Sent from Reviewable.io -->

2021-01-20 22:27 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 302 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLv8yU73rvQgKjQ_JG:-MRWNH2J8ZYtR9uLWhHr:b3hlmq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/alter_database.go#L302)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done. 
</blockquote></details>

Looks great (at least, to me :-) )
___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MRWu0p1BynQq8wKZTmb:b90a6be) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Yeah, I'll make the change in the original PR. 
</blockquote></details>

Cool.  Where can I see this change?
___
*[pkg/sql/type_change.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLiXCaCk6-hG6jsLuC:-MRWtoL665BgPYWkGj58:bz7x3m2) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L394)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It's in `type_desc.go`, in the Validate method. 
</blockquote></details>

Found it.  Thx.
___
*[pkg/sql/type_change.go, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLxdrvBEfP5dh6hQGy:-MRWgUFV2y_SkfjI2KzW:b6b9snr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L303)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm inclined to say the latter as we this is no different than any other schema change operation we support today.
</blockquote></details>

Could we add some small bread crumbs, like "operation will be automatically retried periodically until resolved?"
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLm54j05jTRnXojqDc:-MRWtF_TAkew95ocjRoN:b90rh4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L351)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Could we not say that it's in use

But we don't know this. All we know is that the validation query failed, which can happen for any reason. 
</blockquote></details>

Is there no way we can see which tables/row returned the offending value?  I'm assuming that's what you mean by "the validation query"
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLntW09XmlJgxy95-l:-MRWtXHSAMZSuAVJB2oI:bczlahs) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L367)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I briefly dug into it and it doesn't seem as straight forward -- this error panics in the optimizer, in `resolveAndRequireType`, which is called from a bunch of call sites in addition to the function that adds default values form columns that don't have an explicit value. I don't think we can assume that the error happened because of a bad enum removal. 

It is worth noting that this is temporary -- I do have a couple of ideas on how to solve these cases with views/default exprs, and I hope to prototype that as follow ups. 
</blockquote></details>

You cool adding a TODO and an associated issue for this?  I just want to ensure we don't lose track of it


<!-- Sent from Reviewable.io -->

2021-02-04 17:43 UTC, arulajmani reviewed
This no longer contains 3 commits, just the one pertaining to dropping a region. Support for `ALTER TYPE .. DROP VALUE` has been merged into master, and the validation refactor was pulled out in a separate PR along with other code cleanup. I've addressed all the remaining comments on this PR, and should be (finally) ready for another look! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MSi7_Qa8yh-Yeedr08I:baglvpe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_type.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLbFFP8AgkOfpC7Tf-:-MShwA7c87PRcBQNz62b:b5pqbnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/alter_type.go#L117)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Cool.  Where can I see this change?
</blockquote></details>

OG PR (now merged): https://github.com/cockroachdb/cockroach/pull/58688. There were quite a few changes that happened on how our type schema changer works since we had a review iteration on this PR. 

Also, a note for getting out of the state -- there isn't a catch all to get out of the state solution, as it depends on the exact situation. For example, if the enum value was used in a default expression, the user doesn't really have to do anything except provide an explicit value (in a sense the default expr no longer exists). We'll document the limitations in the docs though, as there are a bunch around dropping enum values. 
___
*[pkg/sql/type_change.go, line 301 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLhMRq1rOzXkvRdK6N:-MSi6FdI44YDQTlA5PRy:b3pz43a) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/type_change.go#L301)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: This is very similar logic to above.  Could we not create a function `cleanupTransitioningEnumValues()` which would remove all enum values in the READ_ONLY state?  That should work in both cases, as we deal with the ones we want to keep first.
</blockquote></details>

I like this suggestion quite a lot. I've slightly adapted it to take in a "shouldRemove" function as opposed to removing all members in `READ_ONLY` state. IMO this allows us to be more explicit about what needs to be removed when calling the function and the code doesn't make assumptions about the order in which these operations are made, ensuring that if someone decides to refactor this in the future, things don't break. 
___
*[pkg/sql/type_change.go, line 303 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLxdrvBEfP5dh6hQGy:-MShxUgX8F28BkDtG0nV:b-wld8xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4bb5903b99d0d716195d32d48ac6fc53d89eeb0/pkg/sql/type_change.go#L303)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Could we add some small bread crumbs, like "operation will be automatically retried periodically until resolved?"
</blockquote></details>

I don't think this is the right place for this -- the jobs infrastructure handles retriable/non-retriable errors, and it should be the jobs infrastructure that should be logging these things (if it doesn't already). That way, individual components don't have to assume such responsibility. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLm54j05jTRnXojqDc:-MShyCugEmrwsixKTdT9:b-k30b5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L351)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is there no way we can see which tables/row returned the offending value?  I'm assuming that's what you mean by "the validation query"
</blockquote></details>

This was done in the original PR -- we now return the first row that uses an enum value. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_type, line 367 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MRLntW09XmlJgxy95-l:-MSi3b19-picZ4Wc0Z6J:bwtv24q) ([raw file](https://github.com/cockroachdb/cockroach/blob/69bc0948eed2ddd92cd150b90143d3846b6fac06/pkg/sql/logictest/testdata/logic_test/alter_type#L367)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

You cool adding a TODO and an associated issue for this?  I just want to ensure we don't lose track of it
</blockquote></details>

Filed: https://github.com/cockroachdb/cockroach/issues/59807

I don't think this deserves a TODO, as the fix is quite involved and there is no natural place for the TODO to live. 


<!-- Sent from Reviewable.io -->

2021-02-04 19:41 UTC, otan reviewed
> Reviewed 1 of 14 files at r4, 8 of 30 files at r5, 8 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, and @lucy-zhang)

___
*[pkg/sql/alter_database.go, line 266 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiU--X-8NkabXksDSZ:-MSiU--X-8NkabXksDS_:bastkq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L266)):*
> ```Go
> 	); err != nil {
> 		return nil, err
> 	}
> ```

do we need permission checks?
___
*[pkg/sql/alter_database.go, line 274 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiVzIMEnYFDjlBPKlL:-MSiVzIMEnYFDjlBPKlM:bqpwc0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L274)):*
> ```Go
> 
> 	if !dbDesc.IsMultiRegion() {
> 		return nil, errors.New("database has no regions to drop")
> ```

nit: can we return pgerror with a nice error code?
___
*[pkg/sql/catalog/descpb/structured.proto, line 1107 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiY_TJ9MKCkXJw8oR5:-MSiY_TJ9MKCkXJw8oR6:b-nuirn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/catalog/descpb/structured.proto#L1107)):*
> ```protobuf
>       RegionalByRow regional_by_row = 3;
>     }
>     optional uint32 region_enum_id = 4 [(gogoproto.nullable) = false, (gogoproto.customname) = "RegionEnumID", (gogoproto.casttype) = "ID"];
> ```

Seems like we are denormalising region_enum_id. What is the motivating factor? Is there validation? Can we add a comment on the motivation?
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 829 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiWRxZ5JYTI59ijMtM:-MSiWRxZ5JYTI59ijMtN:b-4xw8rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/logictest/testdata/logic_test/multiregion#L829)):*
> ```
> 
> statement error pq: database has no regions to drop
> ALTER DATABASE non_multi_region_db DROP REGION "ca-central-1"
> ```

can we add a test to ensure dropping a value from MULTIREGION_ENUM errors?
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 893 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiXbZx9kNSc0Vod-xm:-MSiXbZx9kNSc0Vod-xn:b7hwut) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/logictest/testdata/logic_test/multiregion#L893)):*
> ```
> # even though it was homed there before the primary region was switched.
> statement ok
> ALTER DATABASE start_off_non_multi_region DROP REGION "ca-central-1"
> ```

are there any tests that handle dropping two regions in the same transaction? curious about other combos too, e.g. dropping a region but then setting it as a primary region whilst the async job completes. it may be worth making a similar assertion in alter primary key that we only allow DROP REGION to occur if there are no other mutations happening.
___
*[pkg/util/log/eventpb/ddl_events.proto, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiWasK7D_vbgrIZrNm:-MSiWasK7D_vbgrIZrNn:bko0n9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/util/log/eventpb/ddl_events.proto#L68)):*
> ```protobuf
>   CommonSQLEventDetails sql = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
>   // The name of the database.
>   string database_name = 3 [(gogoproto.jsontag) = ",omitempty"];
> ```

should we be storing database_id here? what if there's a RENAME in the same transaction?


<!-- Sent from Reviewable.io -->

2021-02-05 14:06 UTC, ajstorm requested changes
Impressive piece of work, and happy to see it's on the verge of being merged.  Main concern below is around storing the EnumID on the table descriptor.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MSmVktiASvFggRiSDO6:bfchiru)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 266 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiU--X-8NkabXksDSZ:-MSmG3i-7Y2vkStRo8k3:bxn7fl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L266)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do we need permission checks?
</blockquote></details>

I would think so.  We should be checking for CREATEDB, as we do elsewhere for multi-region alters.
___
*[pkg/sql/alter_database.go, line 281 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmGVffDYBRbmT2qGkP:-MSmGVfg9nQdqA41brL8:b6hi55q) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L281)):*
> ```Go
> 			errors.Newf("cannot drop primary region %q", dbDesc.RegionConfig.PrimaryRegion),
> 			"you must designate another region as the primary region or remove all "+
> 				"other regions before attempting to drop %q", n.Region,
> ```

Nit: "...before attempting to drop _region_ %q"
___
*[pkg/sql/alter_database.go, line 303 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmH3S9-mBGPoAu0aRT:-MSmH3S9-mBGPoAu0aRU:bafqh2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L303)):*
> ```Go
> 	}
> 
> 	if err := params.p.dropEnumValue(params.ctx, typeDesc, tree.EnumValue(n.n.Region)); err != nil {
> ```

Nit: Might be nice if somewhere in here we walked through (in a comment) at a high level what we need to do here.  The top part of this function has no comments, and I think will be hard to understand for someone not well versed in the the multi-region goings on.
___
*[pkg/sql/alter_database.go, line 317 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmHMTk6m0hwMx2Eupy:-MSmHMTk6m0hwMx2Eupz:b-rmonis) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L317)):*
> ```Go
> 	}
> 	if !found {
> 		return errors.Newf("could not find region %s on the database", n.n.Region)
> ```

Nit: I find the use of "on" here a bit odd (could just be me).  Would suggest something like: "attempting to drop region %s which has not yet been added to database %s".  For bonus points, you could add a hint.  Something like "Only regions which have been previously added to a database can be dropped".   
___
*[pkg/sql/alter_database.go, line 475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmIUL44Rib4LPueBeI:-MSmIUL44Rib4LPueBeJ:b-bfbm3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L475)):*
> ```Go
> 	}
> 
> 	err = addDefaultLocalityConfigToAllTables(params.ctx, params.p,
> ```

Nit: Is there a reason you moved this `err` out of the `if`?
___
*[pkg/sql/alter_type.go, line 148 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmJIB122DcqNXMryQ8:-MSmJIB122DcqNXMryQ9:bhpsp9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L148)):*
> ```Go
> }
> 
> func findMemberByName(
> ```

Nit: I'd add "Enum" to this function name (maybe `findEnumMemberByName`?).

Nit: Do we need to return the bool here?  Can we not key off of `nil`?
___
*[pkg/sql/alter_type.go, line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmKZH77qGaGxFZ1JwD:-MSmKZH77qGaGxFZ1JwE:b-l3r4pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L167)):*
> ```Go
> 	}
> 	// See if the value already exists in the enum or not.
> 	found, member := findMemberByName(desc, node.NewVal)
> ```

Nit: Can we put this in the `if`.
___
*[pkg/sql/alter_type.go, line 171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmKuB24YBnum2R-pUk:-MSmKuB24YBnum2R-pUl:b-mr5m30) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L171)):*
> ```Go
> 		if enumMemberIsRemoving(member) {
> 			return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
> 				"enum label %q is being dropped, try again later", node.NewVal)
> ```

Nit: Is it correct to use "label" here, vs. "member"?  Actually, docs use "value".  Can we use that here?  Also, it this error might be more descriptive if we say "cannot add enum value %q as it is in the process of being dropped".  I'm inclined to remove the "try again later" as that's somewhat implied.
___
*[pkg/sql/alter_type.go, line 176 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmLaay2Po7NdDUBiQt:-MSmLaay2Po7NdDUBiQu:b-gjsvjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L176)):*
> ```Go
> 			p.BufferClientNotice(
> 				ctx,
> 				pgnotice.Newf("enum label %q already exists, skipping", node.NewVal),
> ```

Nit: "label" -> "value"
___
*[pkg/sql/alter_type.go, line 180 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmLf3Y79D3Dcm4V4ht:-MSmLf3Y79D3Dcm4V4hu:b-gjsvjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L180)):*
> ```Go
> 			return nil
> 		}
> 		return pgerror.Newf(pgcode.DuplicateObject, "enum label %q already exists", node.NewVal)
> ```

Nit: "label" -> "value"
___
*[pkg/sql/alter_type.go, line 204 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMBMN8q0wGSPgR-s_:-MSmMBMN8q0wGSPgR-sa:bhsvsso) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L204)):*
> ```Go
> 	if enumMemberIsRemoving(member) {
> 		return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
> 			"enum label %q is already being dropped", val)
> ```

Nit: I'd start here with "cannot drop enum value %q, as it is already being dropped".
___
*[pkg/sql/alter_type.go, line 208 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMN2V8phikrKw0f1M:-MSmMN2V8phikrKw0f1N:bd9gnre) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L208)):*
> ```Go
> 	if enumMemberIsAdding(member) {
> 		return pgerror.Newf(pgcode.ObjectNotInPrerequisiteState,
> 			"enum label %q is being added, try again later", val)
> ```

Nit: Similar comment here - "cannot drop enum value %q as it is a in the process of being added".  I'd also drop the "try again later".
___
*[pkg/sql/create_table.go, line 392 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMmzG06GeQSDINxda:-MSmMmzG06GeQSDINxdb:bik1763) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/create_table.go#L392)):*
> ```Go
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error resolving multi-region enum")
> ```

Nit: I'd think this should be an assertion, no?
___
*[pkg/sql/create_table.go, line 398 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMuJg596XZyPVn0Qt:-MSmMuJg596XZyPVn0Qu:b8xbsr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/create_table.go#L398)):*
> ```Go
> 			params.ctx, typeDesc, "add regional by table back reference")
> 		if err != nil {
> 			return errors.Wrap(err, "error adding backreference to multi-region enum")
> ```

Nit: assertion here too?  When could this fail on a c [...]

2021-02-05 16:48 UTC, arulajmani commented
I'm still in the process of making changes to this thing and testing some of the interesting scenarios that @otan mentioned, but I don't wanna keep folks in suspense about the motivation to store the `RegionEnumID` on the table descriptor :) 

Currently, the type descriptor back-references aren't stored on the table descriptor. Instead, every time a list of references is required, they're rebuilt from the columns of the table. This is in contrast to how references work for other objects (views, sequences), which are stored statically on the table descriptor. Without a virtual region column, this allows us to track type dependencies correctly. If anything, this discussion has made clear that this should be captured in comments and the commit message. Forthcoming, shortly.

2021-02-05 16:59 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 281 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmGVffDYBRbmT2qGkP:-MSn6H7s3ZugDJCj8NJQ:bc3079x) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L281)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: "...before attempting to drop _region_ %q"
</blockquote></details>

nit: Hints (not error messages) should be full sentences with a capital letter at  the beginning and a period at the end.
___
*[pkg/sql/create_table.go, line 373 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSn6fiN-xN1s7An3O5W:-MSn6fiN-xN1s7An3O5X:b-cyal0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/create_table.go#L373)):*
> ```Go
> 		)
> 		if err != nil {
> 			return errors.Wrap(err, "error resolving database for multi-region")
> ```

to the question of whether this should be an assertion (`AssertionFailedWithWrappedErrf(err, ...)`)

Is it possible for the SQL client to issue the statement in such a way that this error can be encountered? e.g. if they make a mistake and omit a clause?
Only the end-user needs to be informed and correct what they did? In that case, use errors.Wrap. 

Is an error here completely unexpected and thus only possible if there was schema corruption, or some other bug in our implementation of this or another DDL statement? Then use an assertion error. We also get a copy of assertion errors in telemetry via Sentry.

ditto below
___
*[pkg/sql/type_change.go, line 374 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSn7Mg77SYn6qETVGt9:-MSn7Mg77SYn6qETVGtA:b-x7pdz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/type_change.go#L374)):*
> ```Go
> 					}
> 					if err := dbDesc.Validate(); err != nil {
> 						return errors.Wrapf(err, "could not re-add region to the db desc")
> ```

nit: avoid abbreviations in error messages, "db desc" -> "database descriptor"

Also see my explanation above about errors vs assertions.


<!-- Sent from Reviewable.io -->

2021-02-06 01:53 UTC, arulajmani reviewed
Changes since the last review:
- EnumID is only stored on the `RegionalByTable` locality config, and only if the table is homed in an explicit region (non-primary region). 

More context in the commit message, but I realized after the last round of reviews that storing it on the locality config for global tables / regional by row tables was unnecessary. Unnecessary for global tables because there is no dependency there, and unnecessary for regional by row tables because they already contain a column with that type to begin with. 

Also, regarding denormalization -- I don't fully appreciate the hesitation here. I think (after the change mentioned above) this is the cleanest way to capture the dependency between regional by table tables and the multi-region enum in the absence of a virtual column. The alternative, which would be to special case regional by table tables in a bunch of places in the code, seems much worse. As such, I wouldn't even call it denormalization -- it's a dependency. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MSoySLQ4kXAA8SQpz7T:b-xhhp2c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @knz, @lucy-zhang, and @otan)

___
*[pkg/sql/alter_database.go, line 266 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSiU--X-8NkabXksDSZ:-MSiacil5tqNXA48AQKX:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L266)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do we need permission checks?
</blockquote></details>

Good catch.
___
*[pkg/sql/alter_database.go, line 317 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmHMTk6m0hwMx2Eupy:-MSo3Co_DFQAOKqBrO1N:belpkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L317)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I find the use of "on" here a bit odd (could just be me).  Would suggest something like: "attempting to drop region %s which has not yet been added to database %s".  For bonus points, you could add a hint.  Something like "Only regions which have been previously added to a database can be dropped".   
</blockquote></details>

Where are my bonus points? :eyes: 
___
*[pkg/sql/alter_database.go, line 475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmIUL44Rib4LPueBeI:-MSnqGhT8z0pFgODxPRq:b-3jun8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_database.go#L475)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Is there a reason you moved this `err` out of the `if`?
</blockquote></details>

I don't think so, maybe a result of a rebase, as I extracted r2 into its own PR? Regardless, moved it back in :) 
___
*[pkg/sql/alter_type.go, line 167 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmKZH77qGaGxFZ1JwD:-MSo1rg49mdq-F9q3Yup:b-4lascv) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L167)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we put this in the `if`.
</blockquote></details>

I don't follow.
___
*[pkg/sql/alter_type.go, line 171 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmKuB24YBnum2R-pUk:-MSo1jG1-X60KDIs_-Se:bq2v7qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L171)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Is it correct to use "label" here, vs. "member"?  Actually, docs use "value".  Can we use that here?  Also, it this error might be more descriptive if we say "cannot add enum value %q as it is in the process of being dropped".  I'm inclined to remove the "try again later" as that's somewhat implied.
</blockquote></details>

"try again later" is in line with what we do when dropping columns. 
___
*[pkg/sql/alter_type.go, line 176 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmLaay2Po7NdDUBiQt:-MSo1hgq2mJ9y68Gvik-:b-896fiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L176)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: "label" -> "value"
</blockquote></details>

Done,
___
*[pkg/sql/alter_type.go, line 180 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmLf3Y79D3Dcm4V4ht:-MSo1gptDXpI1K1fLOXX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L180)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: "label" -> "value"
</blockquote></details>

Done.
___
*[pkg/sql/alter_type.go, line 204 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMBMN8q0wGSPgR-s_:-MSo1eVD5OkVdeLJS8Kw:b-oavmwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L204)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd start here with "cannot drop enum value %q, as it is already being dropped".
</blockquote></details>

See comment below.
___
*[pkg/sql/alter_type.go, line 208 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMN2V8phikrKw0f1M:-MSo1--DAw_yXDSoevpv:b-yfrgkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/alter_type.go#L208)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Similar comment here - "cannot drop enum value %q as it is a in the process of being added".  I'd also drop the "try again later".
</blockquote></details>

This is modelled after the error messaging around dropping columns, I'm inclined to keep it this way for consistency unless you have major concerns. I have s/label/value/ though.
___
*[pkg/sql/create_table.go, line 373 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSn6fiN-xN1s7An3O5W:-MSoxIHQ89lrPAAD_9Xy:b-rilnf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/create_table.go#L373)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

to the question of whether this should be an assertion (`AssertionFailedWithWrappedErrf(err, ...)`)

Is it possible for the SQL client to issue the statement in such a way that this error can be encountered? e.g. if they make a mistake and omit a clause?
Only the end-user needs to be informed and correct what they did? In that case, use errors.Wrap. 

Is an error here completely unexpected and thus only possible if there was schema corruption, or some other bug in our implementation of this or another DDL statement? Then use an assertion error. We also get a copy of assertion errors in telemetry via Sentry.

ditto below

</blockquote></details>

Thanks for the context @knz :) 
___
*[pkg/sql/create_table.go, line 392 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMmzG06GeQSDINxda:-MSnuaDs4qr6Nsj1CRKt:b2kycmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/create_table.go#L392)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: I'd think this should be an assertion, no?
</blockquote></details>

None of the other uses of this method use an assertion failed.
___
*[pkg/sql/create_table.go, line 398 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmMuJg596XZyPVn0Qt:-MSntNzc6ckr [...]

2021-02-07 23:28 UTC, otan reviewed
submitting my review before you update your booboo

> The dataabse

nit: database

> validation is unsuccesful

nit: unsuccessful

> Thischange establishes a dependency between "Regional By Table" tables
> not homed in the primary region and the multi-region type descriptor.
> For one, this dependency is required when validating if a region drop
> is safe.

i'm still not sure why we can't read the database descriptor's region enum id to handle this.

we can do something that is `if table is REGIONAL BY ROW, add database region enum id to dependency tracking list`.

i'm usually wary of denormalisation as it can get messy to handle correctness wise. the performance benefit has to outweigh the cost of not having it, which i'm not sure i see. i'm not fully convinced without it that we don't have a performance penalty.

> Reviewed 9 of 23 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-:-MSymk193xFMhILA9uTl:bgaw1cm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @knz, @lucy-zhang, and @otan)

___
*[docs/generated/eventlog.md, line 316 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSymeao1My9XvtexKOL:-MSymeao1My9XvtexKOM:b3nnp38) ([raw file](https://github.com/cockroachdb/cockroach/blob/5332b764a4aeef5825fb2bcc444852dcea80082d/docs/generated/eventlog.md#L316)):*
> ```Markdown
> | `DescriptorID` | The primary object descriptor affected by the operation. Set to zero for operations that don't affect descriptors. | no |
> | `ApplicationName` | The application name for the session where the event was emitted. This is included in the event to ease filtering of logging output by application. | yes |
> | `PlaceholderValues` | The mapping of SQL placeholders to their values, for prepared statements. | yes |
> ```

o_o where did this come from
___
*[pkg/sql/catalog/descpb/structured.proto, line 1104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSymBYL7sC9n-2Qqh92:-MSymBYM8dGTijtwSxSG:blzpjft) ([raw file](https://github.com/cockroachdb/cockroach/blob/5332b764a4aeef5825fb2bcc444852dcea80082d/pkg/sql/catalog/descpb/structured.proto#L1104)):*
> ```protobuf
>       optional string region = 1 [(gogoproto.casttype)="RegionName"];
> 
>       // RegionEnumID is set if the table table is homed in an explicit region
> ```

nit: table table
also maybe call out it is a type id?
___
*[pkg/sql/catalog/descpb/structured.proto, line 1106 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSymOot3URmgEXyfuO1:-MSymOot3URmgEXyfuO2:b44ypec) ([raw file](https://github.com/cockroachdb/cockroach/blob/5332b764a4aeef5825fb2bcc444852dcea80082d/pkg/sql/catalog/descpb/structured.proto#L1106)):*
> ```protobuf
>       // RegionEnumID is set if the table table is homed in an explicit region
>       // (and not the primary region). A Regional By Table table doesn't have a
>       // column which uses the multi-region Enum to denote locality, yet, if it
> ```

nit: lowercase enum, uppercase REGIONAL BY TABLE.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSmTxFr26hgYkTtSD9E:-MSymUGT9J9Wkvo0Oeo1:b-qxin46) ([raw file](https://github.com/cockroachdb/cockroach/blob/62f42fee718db790c330f09000f4ef209a38897c/pkg/sql/catalog/tabledesc/structured.go#L4240)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

These things are real tongue twisters. Done! 
</blockquote></details>

putting the caps on REGIONAL BY TABLE helps, same for GetMultiRegionEnumDependencyIfExists
___
*[pkg/sql/catalog/tabledesc/structured.go, line 845 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59098#-MSymLSZ0UAEsao_wSRa:-MSymLSZ0UAEsao_wSRb:b-jltxe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5332b764a4aeef5825fb2bcc444852dcea80082d/pkg/sql/catalog/tabledesc/structured.go#L845)):*
> ```Go
> 	}
> 
> 	// Regional by table tables ma
> ```

nit: what are you saying about my mother?


<!-- Sent from Reviewable.io -->

2021-02-09 00:01 UTC, arulajmani commented
Closing this in favour of #59989

2021-02-09 00:02 UTC, closed without merging