colexec: fix memory management of the spilling queue
cockroachdb/cockroach pull request #59274
Opened 2021-01-22 01:32 UTC by yuzefovich

**colexec: clean up spilling queue's dequeue from the disk**

Previously, if the spilling queue was not rewindable, whenever we
dequeued from the disk queue, we would put the batch into the in-memory
buffer and return it from there. This was done in order to reuse some of
the code that updated the internal state to advance the head of the
queue; however, this doesn't make much sense to do so - we can just
return the batch directly (as we do in the rewindable case) with no need
to update almost any internal state. This simplifies things a bit and
will make it easier to add more precise memory accounting in the
follow-up commit.

Release note: None

**colexec: fix memory management of the spilling queue**

To be filled.

Fixes: #59235.

Release note: None

2021-01-22 01:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59274)
<!-- Reviewable:end -->

2021-01-25 10:31 UTC, asubiotto requested changes
Is there more testing we can add to ensure correct spilling queue memory usage? I'm thinking unit tests that test what the allocator says after each call, rather than the integration tests we currently have. I think these would be useful sanity checks and describe the usage convention to a caller.

> Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-:-MRt3wTJ7xXba9AYiGEe:bekwuao)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MRt4wWwBNdfKhDN2Vpe:b22lrqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
> ```Go
> 	// Reduce the memory limit by what the DiskQueue may need to buffer
> 	// writes/reads.
> 	// TODO(yuzefovich): the memory limit should only be reduced by the buffer
> ```

How do you justify this? Assume we have 64MB. If we allow the spilling queue free reign of the memory limit, it'll have 64MB for in-memory items and then the disk queue will also have have a cache of `BufferSizeBytes`, bringing us way over the memory limit specified in `args`.
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MRt2cft3HrWltNFOtO_:b-ll6qcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
> ```Go
> //
> // The ownership of the batch still lies with the caller, so the caller is
> // responsible for accounting for the memory used by batch (although the
> ```

nit: I think this comment makes things more confusing that they should be. I think it's simpler to say that when a caller enqueues a batch, that ownership passes to the spillingQueue since callers will probably discard the batch after enqueueing anyway.
___
*[pkg/sql/colexec/spilling_queue.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt3FZU5orO9BDOWdM1:-MRt3FZU5orO9BDOWdM2:b-jl437x) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L310)):*
> ```Go
> // next call to dequeue(). The memory usage of the returned batch is still
> // retained by the spilling queue's allocator, so the caller doesn't have to be
> // concerned with memory management.
> ```

nit: say something about the safety of this batch, can the batch be used after the next call to dequeue? When is this batch's memory usage released?


<!-- Sent from Reviewable.io -->

2021-01-26 03:29 UTC, yuzefovich reviewed
Added a simple test for the memory accounting. Note that it is not very randomized since it is hard to calculate the expected memory usage when more things are random, but I think it should be sufficient to catch most regressions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-:-MRwizUQ4n4fnWiAkcMZ:b-oaw78l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MRvlKOy24WsMHr_IR3d:b-pphxdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How do you justify this? Assume we have 64MB. If we allow the spilling queue free reign of the memory limit, it'll have 64MB for in-memory items and then the disk queue will also have have a cache of `BufferSizeBytes`, bringing us way over the memory limit specified in `args`.
</blockquote></details>

My general thinking is the following:
- if the caller is the hash router, then we will temporarily overshoot by a bit, but with every `dequeue()` from the in-memory buffer that difference will get smaller (eventually we will empty the in-memory buffer and will start reading from disk; if at some point we fully exhaust the queue but then start enqueueing more batches, then we will use the reduced memory limit)
- for all other callers, we do all enqueues upfront, so we will be exceeding the limit until dequeues start.

True, we will overshoot the limit, but only by a bit - `BufferSizeBytes` is either 128KiB or 64KiB. Our accounting is "after the fact", so it is possible that the in-memory buffer overshoots it too (for example, if the current usage is 63MiB, and then next enqueued batch is 2MiB in size, we will actually use 65MiB for the in-memory buffer). Combining these two observations we see that overshooting by at most 128KiB seems acceptable to me.

Now, if we were to change the constants and increase the buffer size bytes (which we probably won't consider doing for a while) to, say, 4MiB, then I'd say it might be worth reserving that upfront.
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MRviTWcDdYOVhRkvQwo:bxq9zpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I think this comment makes things more confusing that they should be. I think it's simpler to say that when a caller enqueues a batch, that ownership passes to the spillingQueue since callers will probably discard the batch after enqueueing anyway.
</blockquote></details>

I agree the wording is a bit confusing, but what you're saying might not be true - actually, I think most likely is that the caller reuses the batch (allocating it once and resetting before use afterwards), and the caller is free to do so. What you're suggesting is that once enqueued, the caller is no longer able to reuse the batch - that would contradict to how the merge joiner is using the spillingQueue now (as well as to how `cFetcher` is using it deep down too).
___
*[pkg/sql/colexec/spilling_queue.go, line 310 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt3FZU5orO9BDOWdM1:-MRvkZUL6XLnUWlstKmp:bahmuy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L310)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: say something about the safety of this batch, can the batch be used after the next call to dequeue? When is this batch's memory usage released?
</blockquote></details>

In the first sentence of the comment it already talks about the validity of the batch.

I also thought about mentioning the memory usage in the comment but decided against it - the memory accounting logic is now fully enclosing within `enqueue` and `dequeue`, so the caller doesn't need to know the details, only that the caller doesn't need to worry about it. Overall, I find this version to be a lot simpler to reason about.


<!-- Sent from Reviewable.io -->

2021-01-26 11:59 UTC, asubiotto requested changes
> Added a simple test for the memory accounting. Note that it is not very randomized since it is hard to calculate the expected memory usage when more things are random, but I think it should be sufficient to catch most regressions.

Definitely. I wasn't trying to imply adding a randomized test. I meant a straightforward deterministic test, maybe even simpler than what you added.

> Reviewed 7 of 7 files at r4, 7 of 7 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-:-MRyXyKD5aCbr9wIBDM-:b99xs3d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MRyY4K4E-x0ufFyfEVY:b1sdyoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

My general thinking is the following:
- if the caller is the hash router, then we will temporarily overshoot by a bit, but with every `dequeue()` from the in-memory buffer that difference will get smaller (eventually we will empty the in-memory buffer and will start reading from disk; if at some point we fully exhaust the queue but then start enqueueing more batches, then we will use the reduced memory limit)
- for all other callers, we do all enqueues upfront, so we will be exceeding the limit until dequeues start.

True, we will overshoot the limit, but only by a bit - `BufferSizeBytes` is either 128KiB or 64KiB. Our accounting is "after the fact", so it is possible that the in-memory buffer overshoots it too (for example, if the current usage is 63MiB, and then next enqueued batch is 2MiB in size, we will actually use 65MiB for the in-memory buffer). Combining these two observations we see that overshooting by at most 128KiB seems acceptable to me.

Now, if we were to change the constants and increase the buffer size bytes (which we probably won't consider doing for a while) to, say, 4MiB, then I'd say it might be worth reserving that upfront.
</blockquote></details>

But why overshoot the limit at all if we can just keep the behavior where we subtract `BufferSizeBytes` from the spilling queue's memory limit?
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MRyYP9687_VK1G2cT76:b8zbt50) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I agree the wording is a bit confusing, but what you're saying might not be true - actually, I think most likely is that the caller reuses the batch (allocating it once and resetting before use afterwards), and the caller is free to do so. What you're suggesting is that once enqueued, the caller is no longer able to reuse the batch - that would contradict to how the merge joiner is using the spillingQueue now (as well as to how `cFetcher` is using it deep down too).
</blockquote></details>

I guess it depends on your definition of what "resetting" means.
___
*[pkg/sql/colexec/spilling_queue.go, line 138 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRyYlMH-d9Ob95rN8rc:-MRyYlMH-d9Ob95rN8rd:b-n0zqvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1015495b3711eeb4bda2b58c788a3617cf104b08/pkg/sql/colexec/spilling_queue.go#L138)):*
> ```Go
> //
> // WARNING: when using a rewindable queue all enqueue() operations *must* occur
> // before any dequeue() calls.
> ```

nit: maybe add a why


<!-- Sent from Reviewable.io -->

2021-01-26 17:15 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MRzdaEz73gj5pFDthF2:b-2g18v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But why overshoot the limit at all if we can just keep the behavior where we subtract `BufferSizeBytes` from the spilling queue's memory limit?
</blockquote></details>

Alright, removed that commit - to me the code looked a bit cleaner and the behavior was making a bit more sense (if we don't spill, we can use the full memory limit).
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MRzfJ5u6ZskbIOwSmGT:b-spqrfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I guess it depends on your definition of what "resetting" means.
</blockquote></details>

I mean it in `ResetMaybeReallocate` sense.
___
*[pkg/sql/colexec/spilling_queue.go, line 138 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRyYlMH-d9Ob95rN8rc:-MRzefe6C-VzkVbhClwN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1015495b3711eeb4bda2b58c788a3617cf104b08/pkg/sql/colexec/spilling_queue.go#L138)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: maybe add a why
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 08:47 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-:-MS20Yeg2ty8bp10mkcA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MS20N5OEk84QtkTHJiW:b-jtbvxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Alright, removed that commit - to me the code looked a bit cleaner and the behavior was making a bit more sense (if we don't spill, we can use the full memory limit).
</blockquote></details>

Thanks. I think to properly do what you're saying we should reserve the full memory limit and when we spill to disk, enqueue `BufferSizeBytes` worth of in-memory batches to be shared.
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MS2017t3AOq9DG2cpv0:bclouzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I mean it in `ResetMaybeReallocate` sense.
</blockquote></details>

Oops, I think I meant reusing. It's a super common pattern to reuse the variable of course, but what "safe for reuse" means is that you can't expect the data to be uncorrupted (e.g. the `Next` rowexec interface contract) which in my opinion is the same as this.


<!-- Sent from Reviewable.io -->

2021-01-27 22:34 UTC, yuzefovich reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-:-MS4yssZAGdH7Es77DdJ:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/spilling_queue.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt4wWwBNdfKhDN2Vpd:-MS4wMP28gHmaItBmwP4:b-gqak98) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L110)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Thanks. I think to properly do what you're saying we should reserve the full memory limit and when we spill to disk, enqueue `BufferSizeBytes` worth of in-memory batches to be shared.
</blockquote></details>

Hm, indeed, good point - I didn't think of it. I think I'll keep the TODO then and will implement this strategy in a follow-up.
___
*[pkg/sql/colexec/spilling_queue.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59274#-MRt2cft3HrWltNFOtOZ:-MS4xEj6-qb6EGqDtMip:b-ueihqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8657ad41a5552dce80ac39626da63379d0cd2cd/pkg/sql/colexec/spilling_queue.go#L150)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Oops, I think I meant reusing. It's a super common pattern to reuse the variable of course, but what "safe for reuse" means is that you can't expect the data to be uncorrupted (e.g. the `Next` rowexec interface contract) which in my opinion is the same as this.
</blockquote></details>

I'm a bit confused. The meaning I want to convey in the comment for `enqueue` is that the method doesn't impose any limitations whatsoever on how the caller uses the passed-in batch. If that batch was received by calling `Next` on the input's caller, this comment on `enqueue` doesn't  know and doesn't care - it is the caller's responsibility to know the lifecycle of the batch, and calling `enqueue` on it doesn't change it.


<!-- Sent from Reviewable.io -->

2021-01-27 23:05 UTC, yuzefovich commented
A flake.

bors r+

2021-01-28 00:17 UTC, merged