sql: add event logs for privilege changes in crdb_internal.unsafe_xxx
cockroachdb/cockroach pull request #59282
Opened 2021-01-22 04:17 UTC by the-ericwang35

Fixes https://github.com/cockroachdb/cockroach/issues/57573.

Previously, when a user uses a crdb_internal_unsafe_xxx
function to overwrite a descriptor, we did not log owner and
privilege changes.
This patch adds the appropriate logging for these commands.

Release note (bug fix): add event logs for privilege changes
in crdb_internal.unsafe_xxx

2021-01-22 04:17 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59282)
<!-- Reviewable:end -->

2021-01-22 18:39 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[docs/generated/eventlog.md, line 1009 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MRfNlg42KyI29Gd5SO8:-MRfNlg42KyI29Gd5SO9:bemke44) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c9b76c43520f87c501a4df6fc5d43290105c2f/docs/generated/eventlog.md#L1009)):*
> ```
> | `PreviousOwner` |  | yes |
> | `NewOwner` |  | yes |
> | `ChangedPrivileges` |  | yes |
> ```
I'm not sure this is the best idea. I think what we want instead is to issue separate events for each change. Like emit  `alter_*_owner` and `alter_*_privilege` events per change. 


<!-- Sent from Reviewable.io -->

2021-01-24 01:26 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[docs/generated/eventlog.md, line 1009 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MRfNlg42KyI29Gd5SO8:-MRlzl6r2sb1oMwo2zo1:befbixe) ([raw file](https://github.com/cockroachdb/cockroach/blob/86c9b76c43520f87c501a4df6fc5d43290105c2f/docs/generated/eventlog.md#L1009)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> | `PreviousOwner` |  | yes |
> | `NewOwner` |  | yes |
> | `ChangedPrivileges` |  | yes |
> ```
I'm not sure this is the best idea. I think what we want instead is to issue separate events for each change. Like emit  `alter_*_owner` and `alter_*_privilege` events per change. 
</blockquote></details>

Sorry, yeah that seems like a much better idea. I've changed it to emit an event per change (either ownership or privilege change)


<!-- Sent from Reviewable.io -->

2021-01-29 16:24 UTC, ajwerner reviewed
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSDuVERAiul-6BE5J28:-MSDuJhm3uucMnCd8dZ2:b-maiguk) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c8e41112db406143b8f2ae4fba580cbc3268e0/pkg/sql/repair.go#L204)):*
> ```Go
> 		username := oldUser.User().Normalized()
> 
> 		// User still in the UserPrivileges list after upsert, figure out which privileges have changed.
> ```

I think I'd pull this into a closure for readability. I also think I'd just store the map as a set of pointers into the newUserPrivileges slice
How about:

```
newUserMap := make(map[string]*descpb.UserPrivilege, len(previousUserPrivileges))
for i := range newUserPrivileges {
    newU := &newUserPrivileges[i]
    newUserMap[newUser.User().Nomalized()] = newUser
}

// Maybe switch to prev and cur because new is a keyword. Or keep it verbose. 
computePrivilegeChanges := func(old, new *descpb.User) (granted, revoked []string) {
    if new == nil {
        return privilege.ListFromBitField(old.Privileges, objectType).SortedNames()
    }
    // ... do the comparison
}
for i := range previousUserPrivileges {
    old := &previousUserPrivileges[i]
    name := old.Name().Normalized()
    new := newUserMap[name]
    granted, revoked := computePrivlegeChanges(old, new)
    delete(newUserMap, name) // no-op if doesn't exists
    // log events
}
```
___
*[pkg/sql/repair.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSDwvyBAxsnarymu_Yt:-MSDwvyBAxsnarymu_Yu:b9u44tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c8e41112db406143b8f2ae4fba580cbc3268e0/pkg/sql/repair.go#L248)):*
> ```Go
> 
> 	// Any leftovers in the new users map indicate privileges for a new user.
> 	for username, privileges := range newUserPrivilegesMap {
> ```

this is going to be psuedorandomly ordered. Probably better to iterate the slice and then check map membership.


<!-- Sent from Reviewable.io -->

2021-01-29 17:22 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/repair.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSDuVERAiul-6BE5J28:-MSE9UHGDuhSUcYDQckK:b9kair9) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c8e41112db406143b8f2ae4fba580cbc3268e0/pkg/sql/repair.go#L204)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think I'd pull this into a closure for readability. I also think I'd just store the map as a set of pointers into the newUserPrivileges slice
How about:

```
newUserMap := make(map[string]*descpb.UserPrivilege, len(previousUserPrivileges))
for i := range newUserPrivileges {
    newU := &newUserPrivileges[i]
    newUserMap[newUser.User().Nomalized()] = newUser
}

// Maybe switch to prev and cur because new is a keyword. Or keep it verbose. 
computePrivilegeChanges := func(old, new *descpb.User) (granted, revoked []string) {
    if new == nil {
        return privilege.ListFromBitField(old.Privileges, objectType).SortedNames()
    }
    // ... do the comparison
}
for i := range previousUserPrivileges {
    old := &previousUserPrivileges[i]
    name := old.Name().Normalized()
    new := newUserMap[name]
    granted, revoked := computePrivlegeChanges(old, new)
    delete(newUserMap, name) // no-op if doesn't exists
    // log events
}
```
</blockquote></details>

For sure this seems much cleaner, thanks for the suggestion. I've made the change.
___
*[pkg/sql/repair.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSDwvyBAxsnarymu_Yt:-MSE9Z2b2TkkviDJ2Csb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24c8e41112db406143b8f2ae4fba580cbc3268e0/pkg/sql/repair.go#L248)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this is going to be psuedorandomly ordered. Probably better to iterate the slice and then check map membership.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 18:17 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSEMBIdBg5f8xijUQb7:-MSEMBIdBg5f8xijUQb8:b4cayoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f6e2c803a26d389045ab93300393c96a9b41aa/pkg/sql/repair.go#L207)):*
> ```Go
> 
> 		// User still in the UserPrivileges list after upsert, figure out which privileges have changed.
> 		if curPrivileges, ok := curUserMap[username]; ok {
> ```

I don't think this conditional makes any sense anymore. Maybe to make that clearer, move the definition of this function above the definition of `curUserMap`


<!-- Sent from Reviewable.io -->

2021-01-29 18:34 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/repair.go, line 207 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSEMBIdBg5f8xijUQb7:-MSEOwf05q8VNH0DLM8l:b-80rllc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5f6e2c803a26d389045ab93300393c96a9b41aa/pkg/sql/repair.go#L207)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think this conditional makes any sense anymore. Maybe to make that clearer, move the definition of this function above the definition of `curUserMap`
</blockquote></details>

Yeah sorry this condition is redundant now since we're already checking it beforehand, I've removed it and moved the definition of this function above the definition of `curUserMap`


<!-- Sent from Reviewable.io -->

2021-01-29 18:40 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSERR0_0mYh_2h7_e82:-MSERR0_0mYh_2h7_e83:b-7lwb4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L200)):*
> ```Go
> 
> 		// User still in the UserPrivileges list after upsert, figure out which privileges have changed.
> 		if prev.Privileges != cur.Privileges {
> ```

this seems wrong. I don't think you get to do this. This is pointer equality comparison. 


<!-- Sent from Reviewable.io -->

2021-01-29 18:49 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETOwuE4y98dzVbGl1:-MSETOwuE4y98dzVbGl2:b-dfka1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L196)):*
> ```
> 			revoked = privilege.ListFromBitField(prev.Privileges, objectType).SortedNames()
> 			return
> ```
nit: naked returns are frowned upon. return this explicitly.
___
*[pkg/sql/repair.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSERR0_0mYh_2h7_e82:-MSETVCs9ghanzOs96zJ:b9u03sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L200)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this seems wrong. I don't think you get to do this. This is pointer equality comparison. 
</blockquote></details>

my bad. nit: flip the condition:

```
prev.Privileges == cur.Privileges {
   return nil, nil
}
```
___
*[pkg/sql/repair.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETIrRBbCosHz3k_Oy:-MSETIrRBbCosHz3k_Oz:b-y9or7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L225)):*
> ```Go
> 			}
> 		}
> 		return
> ```

nit naked returns are frowned upon. Do `return granted, revoked`


<!-- Sent from Reviewable.io -->

2021-01-29 18:50 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETw2I27g9ybfnGjer:-MSETw2I27g9ybfnGjes:b-lrxx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L192)):*
> ```Go
> 	objectType privilege.ObjectType,
> ) error {
> 	computePrivilegeChanges := func(prev, cur *descpb.UserPrivileges, username string) (granted, revoked []string) {
> ```

Is username used anymore?


<!-- Sent from Reviewable.io -->

2021-01-29 18:56 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/repair.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETw2I27g9ybfnGjer:-MSEUvLo3AABSQ3Nq0HY:btmr5bl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L192)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is username used anymore?
</blockquote></details>

Nope it's not, removed.
___
*[pkg/sql/repair.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETOwuE4y98dzVbGl1:-MSEUzlY32K-mVhTycEx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L196)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			revoked = privilege.ListFromBitField(prev.Privileges, objectType).SortedNames()
> 			return
> ```
nit: naked returns are frowned upon. return this explicitly.
</blockquote></details>

Done.
___
*[pkg/sql/repair.go, line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSERR0_0mYh_2h7_e82:-MSES9BD7yjp5yrZSEIN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L200)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

my bad. nit: flip the condition:

```
prev.Privileges == cur.Privileges {
   return nil, nil
}
```
</blockquote></details>

Done.
___
*[pkg/sql/repair.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSETIrRBbCosHz3k_Oy:-MSEV1COA7uzQXUPW5DD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8720f72883ec1b0b6f7caf0b8430ac1626423001/pkg/sql/repair.go#L225)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit naked returns are frowned upon. Do `return granted, revoked`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-29 18:58 UTC, ajwerner approved these changes
Just the one remaining comment. Thanks for iterating on this, this looks much cleaner. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-:-MSEV6WH3AFp0FlGAryf:b6236ns)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @the-ericwang35)

___
*[pkg/sql/repair.go, line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSEVThf1yvwCWsfzS2F:-MSEVThf1yvwCWsfzS2G:b-xjbms7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d813c9fd697890b98c675aaf3278f1d938ac9a8/pkg/sql/repair.go#L224)):*
> ```Go
> 		// the new privilege set, so they have been revoked.
> 		for priv := range prevPrivilegeSet {
> 			revoked = append(revoked, priv)
> ```

this is now going to be unordered. Do we want to sort this before returning? 


<!-- Sent from Reviewable.io -->

2021-01-29 19:04 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/repair.go, line 224 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-MSEVThf1yvwCWsfzS2F:-MSEWvZhAzE83u0n4blW:b-cx2h2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d813c9fd697890b98c675aaf3278f1d938ac9a8/pkg/sql/repair.go#L224)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this is now going to be unordered. Do we want to sort this before returning? 
</blockquote></details>

Yeah good catch, added in the sort.


<!-- Sent from Reviewable.io -->

2021-01-29 19:06 UTC, ajwerner reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-:-MSEX_szAE4XOZRIvyG_:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)



<!-- Sent from Reviewable.io -->

2021-01-29 19:07 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59282#-:-MSEXe8g3IlcM-rkUvkM:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)



<!-- Sent from Reviewable.io -->

2021-01-29 21:51 UTC, the-ericwang35 commented
> Just the one remaining comment. Thanks for iterating on this, this looks much cleaner.

For sure, thanks for the review!

bors r+

2021-01-29 22:35 UTC, merged