sql: overload nextval to accept a regclass
cockroachdb/cockroach pull request #59396
Opened 2021-01-25 19:28 UTC by the-ericwang35

Previously, the `nextval` function only accepted
a string to refer to the referenced object.
This patch allows `nextval` to accept a `regclass` as well.
To do this, we're just adding new functions to the 
`tree.SequenceOperators interface` to take IDs instead of names.
This is the first step to fix this issue: https://github.com/cockroachdb/cockroach/issues/51090.

Release note (sql change): overload nextval to accept a regclass

2021-01-25 19:28 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59396)
<!-- Reviewable:end -->

2021-01-26 18:51 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MS-1El8673IvSW0GzXx:-MS-1El8673IvSW0GzXy:b-teghn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef6881f9379938852868c4ca0437f61e6885127a/pkg/sql/logictest/testdata/logic_test/sequences#L62)):*
> ```
> 
> query I
> SELECT nextval(53::regclass)
> ```

almost definitely a bad idea to rely on this number being stable. Instead consider `'lastval_test_2'::regclass`. Same goes for all of these. 


<!-- Sent from Reviewable.io -->

2021-01-26 21:13 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59396)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MS-1El8673IvSW0GzXx:-MS-XhvA19ZuERAXhlCr:b8gbdei) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef6881f9379938852868c4ca0437f61e6885127a/pkg/sql/logictest/testdata/logic_test/sequences#L62)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

almost definitely a bad idea to rely on this number being stable. Instead consider `'lastval_test_2'::regclass`. Same goes for all of these. 
</blockquote></details>

I've changed it to use `let` to query and store the IDs in a variable instead


<!-- Sent from Reviewable.io -->

2021-02-02 19:00 UTC, ajwerner requested changes
needs a rebase but generally <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 7 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-:-MSZ6Ogw9WNzE47xDfd9:b-yk9yrv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/sequence.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ5w-F5s3hmzB5yB0I:-MSZ5w-F5s3hmzB5yB0J:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/sequence.go#L85)):*
> ```Go
> 		return 0, err
> 	}
> 	fmt.Printf("ID: %v", descriptor.ID)
> ```

remove
___
*[pkg/sql/sequence.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ628KEYJFdKboXA0d:-MSZ628KEYJFdKboXA0e:b-l6mwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/sequence.go#L213)):*
> ```Go
> 		return err
> 	}
> 	fmt.Printf("ID: %v", descriptor.ID)
> ```

remove
___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ65zm2gXbp0hWDIKy:-MSZ65zm2gXbp0hWDIKz:bbu75jr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/logictest/testdata/logic_test/sequences#L62)):*
> ```
> 
> let $lastval_test_id
> SELECT id FROM system.namespace WHERE name='lastval_test'
> ```

This is fine but maybe `SELECT 'lastval_test'::regclass::int` is a bit better because this would be ambiguous if this sequence were in another database. 


<!-- Sent from Reviewable.io -->

2021-02-02 19:40 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59396)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/sequence.go, line 85 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ5w-F5s3hmzB5yB0I:-MSZFZ4cE71A2O86ToCi:bca9jc2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/sequence.go#L85)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

remove
</blockquote></details>

Whoops sorry, done.
___
*[pkg/sql/sequence.go, line 213 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ628KEYJFdKboXA0d:-MSZFa9j6WWNUc24atKN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/sequence.go#L213)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-MSZ65zm2gXbp0hWDIKy:-MSZFbxu3T8w1mCKFjF0:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8558dd042a49f84e8b8fe8ce02be90e63090e224/pkg/sql/logictest/testdata/logic_test/sequences#L62)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is fine but maybe `SELECT 'lastval_test'::regclass::int` is a bit better because this would be ambiguous if this sequence were in another database. 
</blockquote></details>

Good point, done.


<!-- Sent from Reviewable.io -->

2021-02-05 04:14 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r1, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59396#-:-MSkOOBD8Hx7aG37D5Xt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-02-05 17:35 UTC, the-ericwang35 commented
TFTR!

bors r+

2021-02-05 18:15 UTC, merged