kvserver: teach replicateQueue to handle non-voter addition/removal
cockroachdb/cockroach pull request #59403
Opened 2021-01-25 21:12 UTC by aayushshah15

First commit from #57184, second and third commits from #59389.

This commit primarily teaches the allocator to be able to rank
non-voting replica candidates for addition and removal. This allows us
to have the replicateQueue execute upon the allocator's actions to add
or remove non-voting replicas to a range.

Note that this commit does not deal with _rebalancing_ of non-voting
replicas, just simple additions and removals when a range is over or
under-replicated.

Release note: None

2021-01-25 21:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59403)
<!-- Reviewable:end -->

2021-02-01 18:16 UTC, aayushshah15 commented
I'm still fixing a few broken tests, but I thought I'd open it up for review while I do that.

2021-02-07 21:18 UTC, nvanbenschoten reviewed
Gave the last commit a pass. You mentioned that this is still a WIP and is based on https://github.com/cockroachdb/cockroach/pull/59389. Is this blocked on that PR?

> Reviewed 1 of 7 files at r7, 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-:-MSyLpo6CTo_-d6kgu2f:b-eyk1ls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 544 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyF5q62RIlEjA__aoO:-MSyF5q62RIlEjA__aoP:b-t9cg6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L544)):*
> ```Go
> }
> 
> type chooseReplicaToAddFn func(
> ```

I don't find that the indirection through `chooseReplicaToAddFn` or `chooseReplicaToRemoveFn` provides much clarity, because the corresponding functions (e.g. `allocateVoterCandidates` vs. `allocateNonVotersFromList` and even `allocateVoterCandidates` vs. `allocateNonVoterCandidates`) are almost identical. So this is leading to a lot of code duplication and it's also making it quite difficult to understand where the logic isn't identical. As a reader trying to understand this, I'd like to more easily be able to point to one or two places where this distinction matters (e.g. using `constraint.EmptyAnalyzedConstraints` for voter constraints when allocating a non-voting replica) and know that it doesn't in all other places.

This makes me wonder if we're splitting code paths too early. Did you explore how this code would look with a `voterTarget bool` parameter plumbed through a few of these layers and resorted to targetted branching on this condition?
___
*[pkg/kv/kvserver/allocator.go, line 763 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyHDQfAX6wKw-YOV03:-MSyHDQfAX6wKw-YOV04:bbqdrdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L763)):*
> ```Go
> // set. It first attempts to randomly select a target from the set of stores
> // that have greater than the average number of replicas. Failing that, it
> // falls back to selecting a random target from any of the existing
> ```

"existing voting replicas"
___
*[pkg/kv/kvserver/allocator.go, line 779 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyHFVY7weQVAppnYB-:-MSyHFVY7weQVAppnYB0:b3q91ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L779)):*
> ```Go
> // provided set. It first attempts to randomly select a target from the set of
> // stores that have greater than the average number of replicas. Failing that,
> // it falls back to selecting a random target from any of the existing replicas.
> ```

"existing non-voting replicas"
___
*[pkg/kv/kvserver/allocator_scorer.go, line 1003 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyIBmL9FUSA7DNH5sM:-MSyIBmL9FUSA7DNH5sN:b-xdwbrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator_scorer.go#L1003)):*
> ```Go
> 			valid = true
> 			matchingStores := analyzed.SatisfiedBy[i]
> 			// TODO DURING REVIEW: Not directly related to this patch, but shouldn't
> ```

Reading the comment on the function, I think the idea is that the target store is necessary if "it matches a constraint that is not already fully satisfied by existing replicas". If `len(matchingStores) == int(constraints.NumReplicas)` then the constraint is already satisfied without `store`, assuming `store` itself is not accounted for in `analyzed.SatisfiedBy`. I don't think it is, given the comment on `removeConstraintsCheck`, which says "The difference between this and allocateConstraintsCheck is that this is to be used on an existing replica of the range, not a potential addition.".

Mind leaving a comment?
___
*[pkg/kv/kvserver/replicate_queue.go, line 348 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyJm_V2haZXf2nReE5:-MSyJm_V2haZXf2nReE6:bovxxhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b8019bb07f233609e4e9cd0c27d21b985c0978/pkg/kv/kvserver/replicate_queue.go#L348)):*
> ```
>  /* removeIdx */
> ```

Looks like we accidentally lost this.
___
*[pkg/kv/kvserver/replicate_queue.go, line 429 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyJwaY5_UQQEVSLLJr:-MSyJwaY5_UQQEVSLLJs:b-z1eib5) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b8019bb07f233609e4e9cd0c27d21b985c0978/pkg/kv/kvserver/replicate_queue.go#L429)):*
> ```Go
> 	existingReplicas []roachpb.ReplicaDescriptor,
> 	liveVoterReplicas []roachpb.ReplicaDescriptor,
> 	removeIdx int, // -1 for no removal
> ```

Looks like we lost this comment.
___
*[pkg/kv/kvserver/replicate_queue.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKqZq6VOGrs80dB4P:-MSyKqZq6VOGrs80dB4Q:b-f3gm96) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L123)):*
> ```Go
> 
> // ReplicateQueueMetrics is the set of metrics for the replicate queue.
> // TODO(aayush): Track metrics for non-voting replicas separately here.
> ```

:thumbsup: are you planning to do that in this PR, or should we open an issue to track?
___
*[pkg/kv/kvserver/replicate_queue.go, line 550 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKAbQ4KXO4NZUaYI4:-MSyKAbQ4KXO4NZUaYI5:bxgpy5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L550)):*
> ```Go
> }
> 
> func (rq *replicateQueue) addNonVoter(
> ```

Let's give this a comment.
___
*[pkg/kv/kvserver/replicate_queue.go, line 778 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKgY4DnV0DKC6UQxU:-MSyKgY5331oPpRduKUb:bizczxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L778)):*
> ```Go
> 	}
> 
> 	if err := rq.changeReplicas(ctx, repl,
> ```

nit: let's keep the wrapping the same as in all other callers, so it's easier to see where this differs from them.


<!-- Sent from Reviewable.io -->

2021-02-07 21:34 UTC, aayushshah15 commented
I was intending for it to not be a WIP anymore. It is blocked on #59389 though. 

Your comment regarding the code duplication captures the gist of what I most wanted your opinion on. Thanks for taking a look. I'll make that change. 





<!-- Sent from Reviewable.io -->

2021-02-08 19:28 UTC, aayushshah15 reviewed
Haven't addressed all your comments yet, but this should be good for another pass. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-:-MT25NGX01f5HCMDhtCe:bz0t2ue)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 544 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyF5q62RIlEjA__aoO:-MSzR-go9jydJngE7Trr:b-rlbz2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L544)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't find that the indirection through `chooseReplicaToAddFn` or `chooseReplicaToRemoveFn` provides much clarity, because the corresponding functions (e.g. `allocateVoterCandidates` vs. `allocateNonVotersFromList` and even `allocateVoterCandidates` vs. `allocateNonVoterCandidates`) are almost identical. So this is leading to a lot of code duplication and it's also making it quite difficult to understand where the logic isn't identical. As a reader trying to understand this, I'd like to more easily be able to point to one or two places where this distinction matters (e.g. using `constraint.EmptyAnalyzedConstraints` for voter constraints when allocating a non-voting replica) and know that it doesn't in all other places.

This makes me wonder if we're splitting code paths too early. Did you explore how this code would look with a `voterTarget bool` parameter plumbed through a few of these layers and resorted to targetted branching on this condition?
</blockquote></details>

Made the change, let me know if you don't like it. 
___
*[pkg/kv/kvserver/allocator.go, line 763 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyHDQfAX6wKw-YOV03:-MSzO7zY-ECXEc547ver:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L763)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"existing voting replicas"
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 779 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyHFVY7weQVAppnYB-:-MSzO8kgAE70k2Wm1lk-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator.go#L779)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"existing non-voting replicas"
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 1003 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyIBmL9FUSA7DNH5sM:-MSzQ1wQ9-Q5LP9FiGxy:b-o43hw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/allocator_scorer.go#L1003)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Reading the comment on the function, I think the idea is that the target store is necessary if "it matches a constraint that is not already fully satisfied by existing replicas". If `len(matchingStores) == int(constraints.NumReplicas)` then the constraint is already satisfied without `store`, assuming `store` itself is not accounted for in `analyzed.SatisfiedBy`. I don't think it is, given the comment on `removeConstraintsCheck`, which says "The difference between this and allocateConstraintsCheck is that this is to be used on an existing replica of the range, not a potential addition.".

Mind leaving a comment?
</blockquote></details>

ahh makes sense, thanks. Added a comment.
___
*[pkg/kv/kvserver/replicate_queue.go, line 348 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyJm_V2haZXf2nReE5:-MSzOAGj1-GkfXAy2mkj:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b8019bb07f233609e4e9cd0c27d21b985c0978/pkg/kv/kvserver/replicate_queue.go#L348)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
>  /* removeIdx */
> ```

Looks like we accidentally lost this.
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replicate_queue.go, line 429 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyJwaY5_UQQEVSLLJr:-MSzO_Fw9cpC0xqxEvc7:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/06b8019bb07f233609e4e9cd0c27d21b985c0978/pkg/kv/kvserver/replicate_queue.go#L429)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like we lost this comment.
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replicate_queue.go, line 778 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKgY4DnV0DKC6UQxU:-MSzP9hT8lgXEwwOeLcH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L778)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: let's keep the wrapping the same as in all other callers, so it's easier to see where this differs from them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-11 03:55 UTC, nvanbenschoten reviewed
Nice! The structure of this looks very good now. My primary remaining question is whether we're adding sufficient unit test coverage for this new functionality in the `Allocator`. The new test in `replicate_queue_test.go` looks good, but it's always best to test in layers, as doing so allows for more exhaustive testing. 

> Reviewed 9 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-:-MTED159-Msz6fK1w-AC:btmcmp7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 151 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE86YQ8rwAOFZg3on5:-MTE86YQ8rwAOFZg3on6:bynq7wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L151)):*
> ```Go
> const (
> 	_ targetReplicaType = iota
> 	voters
> ```

I would imagine that `voterTarget` and `nonVoterTarget` would lead to easier reading. For instance, `allocateTarget(..., voters)` looks more strange than `allocateTarget(..., voterTarget)`.
___
*[pkg/kv/kvserver/allocator.go, line 580 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE7x857kbkZBZEUdus:-MTE7x857kbkZBZEUdut:b-52ogtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L580)):*
> ```Go
> 	zone *zonepb.ZoneConfig,
> 	existingVoters, existingNonVoters []roachpb.ReplicaDescriptor,
> 	replicaType targetReplicaType,
> ```

nit: given the name of this method and the use of the param, would `targetType` be a better name?
___
*[pkg/kv/kvserver/allocator.go, line 658 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE8cPLCQFrZkeYoCDf:-MTE8cPLCQFrZkeYoCDg:b-hkmuw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L658)):*
> ```Go
> 		)
> 		// When computing the "diversity score" for a given store for a voting
> 		// replica allocation. We consider the localities of only the stores that
> ```

Should this be one sentence?
___
*[pkg/kv/kvserver/allocator.go, line 764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9UQI26aculL8TaE-:-MTE9UQI26aculL8TaE0:bs6sr95) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L764)):*
> ```Go
> 	options := a.scorerOptions()
> 
> 	var checkFn constraintsCheckFn
> ```

nit: here and above, I would just write out the whole `constraintsCheckFn` for the name of this variable. This enough going on here that this could be lost, and it helps explain what's going on here better.
___
*[pkg/kv/kvserver/allocator.go, line 765 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9lVgBdfdY9mEpvZA:-MTE9lVgBdfdY9mEpvZB:bhwm6xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L765)):*
> ```Go
> 
> 	var checkFn constraintsCheckFn
> 	var replicaSetForDiversityCalc []roachpb.ReplicaDescriptor
> ```

These are existing replicas, right? Should we then name this `existingReplicasForDiversityCalc`?
___
*[pkg/kv/kvserver/allocator_scorer.go, line 407 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9uf133AyINiaau90:-MTE9uf133AyINiaau91:b-89p4dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L407)):*
> ```Go
> }
> 
> type constraintsCheckFn func(s roachpb.StoreDescriptor) (valid, necessary bool)
> ```

Give this type a comment, along with one on each of the impls. On those, please give a bit of an explanation about why the checker behaves the way it does in response to the constraint sources.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 421 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEA0pnAiEYYXSpUXCb:-MTEA0pnAiEYYXSpUXCc:b-1pt80y) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L421)):*
> ```Go
> 
> func nonVoterConstraintsCheckerForAllocation(
> 	overallConstraints, _ constraint.AnalyzedConstraints,
> ```

Any reason to accept the `voterConstraints`, not that we aren't using it and aren't matching an interface? From the caller's side, I was getting confused why this call needed the voter constraints at all. Limiting visibility can often be an easy hint to readers about when various information is needed and when it is not.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 491 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEAead5VyBklAmRBZt:-MTEAead5VyBklAmRBZu:b-tuel6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L491)):*
> ```Go
> }
> 
> func voterConstraintsCheckerForRemoval(
> ```

Should we move this up near the rest of the `constraintsCheckFn`? Or actually, maybe they should all be moved down right above `allocateConstraintsCheck`. Either way, it's useful to group them together so that a reader can see them all together and create a mental model of how they differ.
___
*[pkg/kv/kvserver/allocator_test.go, line 390 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTECY_Q66zEPCdA0HHe:-MTECY_Q66zEPCdA0HHf:b84a5pi) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_test.go#L390)):*
> ```Go
> 
> 	stopper, g, _, a, _ := createTestAllocator(1, false /* deterministic */)
> 	defer stopper.Stop(context.Background())
> ```

I'm a little surprised to see no new test cases in `allocator_scorer_test.go` or in `allocator_test.go`. Are these not where we should be testing the new `Allocator` added in this commit?
___
*[pkg/kv/kvserver/replica_command.go, line 2501 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTECEof6GcYua1yVsc5:-MTECEof6GcYua1yVsc6:blb8zvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/replica_command.go#L2501)):*
> ```Go
> 	addOp, removeOp               roachpb.ReplicaChangeType
> 	relocationTargets             []roachpb.ReplicationTarget
> 	replicaType                   targetReplicaType
> ```

Same point about the naming of this "arg".
___
*[pkg/kv/kvserver/replica_command.go, line 2531 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEBmAr8XNRXot8956z:-MTEBmAr8XNRXot8957-:bsvy41z) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/replica_command.go#L2531)):*
> ```Go
> 		votersToAdd := subtractTargets(voterTargets, desc.Replicas().Voters().ReplicationTargets())
> 		votersToRemove := subtractTargets(desc.Replicas().Voters().ReplicationTargets(), voterTargets)
> 		// If there are no voters to relocate, we relocate the non-voters.
> ```

Give a hint here about what happens if there are voters and non-voters to relocate. The idea is that `relocateOne` will be called again?


<!-- Sent from Reviewable.io -->

2021-02-16 04:17 UTC, nvanbenschoten requested changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9UQI26aculL8TaE-:-MTd1xJF81vDqFp1J6u3:bjmv1ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L764)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: here and above, I would just write out the whole `constraintsCheckFn` for the name of this variable. This enough going on here that this could be lost, and it helps explain what's going on here better.
</blockquote></details>

It looks like this was updated in `allocateTargetFromList`, but not here.


<!-- Sent from Reviewable.io -->

2021-02-17 19:12 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 151 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE86YQ8rwAOFZg3on5:-MTbw19qBVxwmsW2DJGZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L151)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would imagine that `voterTarget` and `nonVoterTarget` would lead to easier reading. For instance, `allocateTarget(..., voters)` looks more strange than `allocateTarget(..., voterTarget)`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 580 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE7x857kbkZBZEUdus:-MTI3r3uA5ZJasFxypnX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L580)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: given the name of this method and the use of the param, would `targetType` be a better name?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 658 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE8cPLCQFrZkeYoCDf:-MTI3mW91_tJQXGckHNB:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L658)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be one sentence?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/allocator.go, line 764 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9UQI26aculL8TaE-:-MTlEmI00uMkVqDes_9C:b1lrtny) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L764)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It looks like this was updated in `allocateTargetFromList`, but not here.
</blockquote></details>

:face_with_head_bandage: should be good now.
___
*[pkg/kv/kvserver/allocator.go, line 765 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9lVgBdfdY9mEpvZA:-MTI4DUKBEsW3ZhXoHxp:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator.go#L765)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

These are existing replicas, right? Should we then name this `existingReplicasForDiversityCalc`?
</blockquote></details>

done.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 407 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTE9uf133AyINiaau90:-MTItC1P7iVX5Vsc2Q-Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L407)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this type a comment, along with one on each of the impls. On those, please give a bit of an explanation about why the checker behaves the way it does in response to the constraint sources.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 421 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEA0pnAiEYYXSpUXCb:-MTIn0Xe2oizl2VTsLxe:bwa8psc) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L421)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any reason to accept the `voterConstraints`, not that we aren't using it and aren't matching an interface? From the caller's side, I was getting confused why this call needed the voter constraints at all. Limiting visibility can often be an easy hint to readers about when various information is needed and when it is not.
</blockquote></details>

Fair point, the extra param only serves to confuse. Removed it.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 491 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEAead5VyBklAmRBZt:-MTIrxg6ChkLuENUZUtg:b-ehir6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_scorer.go#L491)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we move this up near the rest of the `constraintsCheckFn`? Or actually, maybe they should all be moved down right above `allocateConstraintsCheck`. Either way, it's useful to group them together so that a reader can see them all together and create a mental model of how they differ.
</blockquote></details>

Moved them all right above `allocateConstraintsCheck`.
___
*[pkg/kv/kvserver/allocator_test.go, line 390 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTECY_Q66zEPCdA0HHe:-MTkvRTo28kB_ON7NAJK:bsz6v7) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/allocator_test.go#L390)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little surprised to see no new test cases in `allocator_scorer_test.go` or in `allocator_test.go`. Are these not where we should be testing the new `Allocator` added in this commit?
</blockquote></details>

I was lazily deferring to a future PR, my bad. PTAL now. 
___
*[pkg/kv/kvserver/replica_command.go, line 2501 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTECEof6GcYua1yVsc5:-MTbvYBf9DbwXFu7ZQml:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/replica_command.go#L2501)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same point about the naming of this "arg".
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 2531 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTEBmAr8XNRXot8956z:-MTbvSXgA6A5r0kdShfA:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/02447f59a55f889df15f1bc5824b508a98c451b3/pkg/kv/kvserver/replica_command.go#L2531)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give a hint here about what happens if there are voters and non-voters to relocate. The idea is that `relocateOne` will be called again?
</blockquote></details>

Done. 
___
*[pkg/kv/kvserver/replicate_queue.go, line 123 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKqZq6VOGrs80dB4P:-MTlOi7M2HcquzK7M-pN:b-yg1rg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L123)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

:thumbsup: are you planning to do that in this PR, or should we open an issue to track?
</blockquote></details>

Created #60694 to track this. I think doing it in a separate PR might be better in case this ends up causing some testing fallout (perhaps with some roachtests).
___
*[pkg/kv/kvserver/replicate_queue.go, line 550 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MSyKAbQ4KXO4NZUaYI4:-MTbv_g57ttBjxrrgXya:b8gsbv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5634c5338d06f59383259cde5551d9e1ad8b269c/pkg/kv/kvserver/replicate_queue.go#L550)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>
 [...]

2021-02-17 22:51 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-:-MTmBEsNEsF2_bXc9hyt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator_test.go, line 2639 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTmB-PqEs1qbscqZaSl:-MTmB-PqEs1qbscqZaSm:bavp5a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6c8121a6e04ced012c3271d518ef84cd3fd2028/pkg/kv/kvserver/allocator_test.go#L2639)):*
> ```Go
> 		{
> 			[]roachpb.StoreID{1},
> 			[]roachpb.StoreID{2}, []roachpb.StoreID{3, 4}},
> ```

nit: was this intentional?


<!-- Sent from Reviewable.io -->

2021-02-18 17:38 UTC, aayushshah15 reviewed
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-:-MTqD73D2pOXX8os2wGz:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator_test.go, line 2639 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/59403#-MTmB-PqEs1qbscqZaSl:-MTnHPnvBwuDYml2pbHd:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6c8121a6e04ced012c3271d518ef84cd3fd2028/pkg/kv/kvserver/allocator_test.go#L2639)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: was this intentional?
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-02-18 20:23 UTC, merged