sql: add SHOW CREATE TABLES / SHOW CREATE ALL TABLES commands
cockroachdb/cockroach pull request #59412
Opened 2021-01-25 23:46 UTC by RichardJCai

sql: add SHOW CREATE TABLES / SHOW CREATE ALL TABLES commands
Resolves #53488 

Release note (sql change): Add support for SHOW CREATE TABLES [table_list]
and SHOW CREATE ALL TABLES commands.
Both commands output the database_name, schema_name, table_name, and
create_statement for a set of tables.

```
Example usage:
> SHOW CREATE TABLES t, t2;
  database_name | schema_name | table_name |                 create_statement
----------------+-------------+------------+---------------------------------------------------
  movr          | public      | t          | CREATE TABLE public.t (FAMILY "primary" (rowid)
                |             |            | )
  movr          | public      | t2         | CREATE TABLE public.t2 (FAMILY "primary" (rowid)
                |             |            | )
(2 rows)
```

2021-01-25 23:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59412)
<!-- Reviewable:end -->

2021-01-27 01:03 UTC, rafiss requested changes
thanks for the quick turn around!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-:-MS0MJNA93ykob2u7tFd:b-ovgudg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/delegate/show_table.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0KE1T39txPBHGRYGc:-MS0KE1T39txPBHGRYGd:br6yimm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L230)):*
> ```Go
>     ) AS create_statement
> FROM
>     crdb_internal.create_statements
> ```

i think we'd only want to include the results from the current database.

maybe if the current database is `""`, we could include them all? the old `dump` command had a `--dump-all` that i think we'd want to offer a workaround for.
___
*[pkg/sql/delegate/show_table.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0Id-w0cKGD4h7l6rE:-MS0Id-w0cKGD4h7l6rF:beehehx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L278)):*
> ```Go
> //   %[1]s the given table names as SQL string literal.
> //   %[2]s the table IDs.
> func (d *delegator) showTablesDetails(names tree.TableNames, query string) (tree.Statement, error) {
> ```

i feel like there should be a good way to reuse the same function for the old `SHOW CREATE TABLE x` and `SHOW CREATE TABLES x y z`. what do you think?
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0GbVI0lS0P69ko7IS:-MS0GbVI0lS0P69ko7IT:b-p341c4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L2)):*
> ```
> # All querys are separated into SELECT create_statement
> # and SELECT database_name, schema_name, table_name for formatting purposes.
> ```

should the old `SHOW CREATE TABLE x` command also include the new columns too? it seems like it could be confusing for them to differ
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0LCAo6xR2ZMdiqj8f:-MS0LCAo6xR2ZMdiqj8g:b7uw0s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L35)):*
> ```
>    parent_schema_id INT8 NOT NULL,
>    locality STRING NULL
> )
> ```

we toyed with the idea of adding a semicolon to the output here so that tools could more easily consume the output. i think we should do that, and update the old SHOW CREATE stmts too
___
*[pkg/sql/parser/sql.y, line 5051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS05ELd0PG3SC69Y0yw:-MS05ELd0PG3SC69Y0yx:b-4qw8bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/parser/sql.y#L5051)):*
> ```Yacc
> // %Help: SHOW CREATE - display the CREATE statement for a table, sequence or view
> // %Category: DDL
> // %Text: SHOW CREATE [ TABLE | SEQUENCE | VIEW ] <tablename>
> ```

i think we'd need to update some of the help text here


<!-- Sent from Reviewable.io -->

2021-01-27 16:48 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0GbVI0lS0P69ko7IS:-MS3j_v_Dgh_mnDzvXfJ:b-oulesx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should the old `SHOW CREATE TABLE x` command also include the new columns too? it seems like it could be confusing for them to differ
</blockquote></details>

I wasn't sure if it was okay to change the column set but right now I don't think the first column for `SHOW CREATE TABLE x` just returns `x` anyway so I'm not sure how useful that is.

I think it should be okay to change, thoughts?


<!-- Sent from Reviewable.io -->

2021-01-29 21:17 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/delegate/show_table.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0KE1T39txPBHGRYGc:-MSErML1395acsu6Nl5x:b-olhh0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L230)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we'd only want to include the results from the current database.

maybe if the current database is `""`, we could include them all? the old `dump` command had a `--dump-all` that i think we'd want to offer a workaround for.
</blockquote></details>

Done, I think crdb_internal.create_statements defaults to the current database regardless.
___
*[pkg/sql/delegate/show_table.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0Id-w0cKGD4h7l6rE:-MSErQ111pIFYMmdLkri:bcp6akh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L278)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i feel like there should be a good way to reuse the same function for the old `SHOW CREATE TABLE x` and `SHOW CREATE TABLES x y z`. what do you think?
</blockquote></details>

Refactored the function so the logic could be shared.
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0GbVI0lS0P69ko7IS:-MSEzdcm0AuR5_yIyLB1:b9svfx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L2)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I wasn't sure if it was okay to change the column set but right now I don't think the first column for `SHOW CREATE TABLE x` just returns `x` anyway so I'm not sure how useful that is.

I think it should be okay to change, thoughts?
</blockquote></details>

Followup: same as the semi colon one, can we split that into a second issue, easier to make a PR purely for that.
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0LCAo6xR2ZMdiqj8f:-MSEz3kY5m5EnIkJh-4F:bg2q87j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we toyed with the idea of adding a semicolon to the output here so that tools could more easily consume the output. i think we should do that, and update the old SHOW CREATE stmts too
</blockquote></details>

Added a semi colon here, can we update the old SHOW CREATE stmts in a separate issue? There's a lot of logic tests using them, I don't want to balloon this PR, would rather have a separate one for that.
___
*[pkg/sql/parser/sql.y, line 5051 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS05ELd0PG3SC69Y0yw:-MSEzk8GBmafmQrjT-sv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/parser/sql.y#L5051)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we'd need to update some of the help text here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 21:32 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 662 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZZOFb5imW-BaZ4CqD:-MSZZOFb5imW-BaZ4CqE:b-64oj4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/ccl/logictestccl/testdata/logic_test/zone#L662)):*
> ```
>   PARTITION p1 VALUES IN ((1)),
>   PARTITION p2 VALUES IN ((2))
> );;
> ```

interesting, there's a double semicolon here.. 
___
*[pkg/sql/delegate/show_table.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0KE1T39txPBHGRYGc:-MSZbld78Jn-pA1spMfv:b-oqsqh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L230)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done, I think crdb_internal.create_statements defaults to the current database regardless.
</blockquote></details>

yeah it does, but if you are running through the internal executor, then the current database is `""`, and using `"".crdb_internal.create_statements` would show info from all databases
___
*[pkg/sql/delegate/show_table.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZazAX6I6ULBranw4l:-MSZazAX6I6ULBranw4m:btgn3a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L53)):*
> ```Go
>     1, 2;`
> 
> 	return d.populateQueryDetails([]*tree.UnresolvedObjectName{n.Name}, showCreateQuery, false)
> ```

we should document inline constants like this:

```
... , showCreateQuery, false /* onlyQueryCurrentDB */)
```

but also i'm a bit confused -- how does this work if you're allowed to lookup this table name in other databases?
___
*[pkg/sql/delegate/show_table.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZarY_-DOwTgc-IeYq:-MSZarY_-DOwTgc-IeYr:b780e73) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L109)):*
> ```Go
> 	if n.WithComment {
> 		getColumnsQuery += `,
>     col_description(%[6]s, attnum) AS comment`
> ```

wouldn't we want this to be a numeric value still?
___
*[pkg/sql/delegate/show_table.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZbRYrE7Bqjk44K21k:-MSZbRYrE7Bqjk44K21l:b-5urwpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L139)):*
> ```Go
>     LEFT OUTER JOIN pg_attribute
>         ON column_name = pg_attribute.attname
>         AND attrelid = %[6]s`
> ```

also should be numeric still?
___
*[pkg/sql/delegate/show_table.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZaKsr7nlG0nduRFo1:-MSZaKsr7nlG0nduRFo2:b-2owx53) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L252)):*
> ```Go
> //   %[1]s the database name as SQL string literal.
> //   %[2]s the unqualified table name(s) as SQL string literal.
> //   %[3]s the given table name as SQL string literal. Remove.
> ```

is "Remove" an old comment?
___
*[pkg/sql/delegate/show_table.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZaQLe9GDuN-bBqNBQ:-MSZaQLe9GDuN-bBqNBR:b-wuhc1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L254)):*
> ```Go
> //   %[3]s the given table name as SQL string literal. Remove.
> //   %[4]s the database name as SQL identifier.
> //   %[5]s the schema name as SQL string literal. Not used for SHOW TABLES.
> ```

should it say "Not used for SHOW CREATE TABLES"? why is it not used?
___
*[pkg/sql/delegate/show_table.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZcAZW4krpwFSXbQAH:-MSZcAZW4krpwFSXbQAI:b-b8xysh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L295)):*
> ```Go
> 		databaseLiteral = d.evalCtx.SessionData.Database
> 		// DatabaseIdentifier is used in the query, double quote are needed
> 		// in the case where the database name includes spaces.
> ```

it's also needed if the name is mixed-case
___
*[pkg/sql/delegate/show_table.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZcDmg6OLTNsYNJA5d:-MSZcDmg6OLTNsYNJA5e:bwe5rzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L296)):*
> ```Go
> 		// DatabaseIdentifier is used in the query, double quote are needed
> 		// in the case where the database name includes spaces.
> 		databaseIdentifier = strconv.Quote(databaseLiteral)
> ```

i don't think strconv is fully robust... check out `lexbase.EncodeEscapedSQLIdent`
___
*[pkg/sql/delegate/show_table.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZdcrhCTH0mBMV-Gpq:-MSZdcrhCTH0mBMV-Gpr:b-r735ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L306)):*
> ```Go
> 		givenTableName = resNames[0].String()
> 
> 		if !onlyQueryCurrentDB {
> ```

i think this should would make more sense as an "else" condition right after line 296. why do it here?

so is the idea here that you can't do `SHOW CREATE TABLES database.schema.table`?
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0GbVI0lS0P69ko7IS:-MSZZq064lb7dWxI6O6s:b-57rg09) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L2)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Followup: same as the semi colon one, can we split that into a second issue, easier to make a PR purely for that.
</blockquote></details>

ok yeah, can you file the issue? IMO we shouldn't release 21.1 with these differing. it would be a weird user experience
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0LCAo6xR2ZMdiqj8f:-MSZZtzL1QMA0xbkwRwJ:bsvj4e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L35)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Added a semi colon here, can we update the old SHOW CREATE stmts in a separate issue? There's a lot of logic tests using them, I don't want to balloon this PR, would rather have a separate one for that.
</blockquote></details>

sounds good, can you file the issue? (you can use the same the same issue as above)


<!-- Sent from Reviewable.io -->

2021-02-02 22:03 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 662 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZZOFb5imW-BaZ4CqD:-MSZjyqj16c9JOI4Cvao:bcz6rjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/ccl/logictestccl/testdata/logic_test/zone#L662)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

interesting, there's a double semicolon here.. 
</blockquote></details>

Oops, yeah the logic for adding ZONECONFIG adds a semi colon, made sense when it previously didn't have a semicolon
___
*[pkg/sql/delegate/show_table.go, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0KE1T39txPBHGRYGc:-MSZkorlE9kQJOSQXNHx:b-e5ulfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/delegate/show_table.go#L230)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah it does, but if you are running through the internal executor, then the current database is `""`, and using `"".crdb_internal.create_statements` would show info from all databases
</blockquote></details>

Oh fair, makes sense to explicitly specify it here then.
___
*[pkg/sql/delegate/show_table.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZazAX6I6ULBranw4l:-MSZkBSg6ZqyMuqWv7-6:b-r3a50f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should document inline constants like this:

```
... , showCreateQuery, false /* onlyQueryCurrentDB */)
```

but also i'm a bit confused -- how does this work if you're allowed to lookup this table name in other databases?
</blockquote></details>

Searching up the table only applies for the existing SHOW TABLE commands, it's possible to look up tables in other databases by using the fully qualified name.
___
*[pkg/sql/delegate/show_table.go, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZbRYrE7Bqjk44K21k:-MSZkKi7AxF7k0oCmDCR:bjqfdmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L139)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

also should be numeric still?
</blockquote></details>

I changed it so the number is converted to a string in populateQueryDetails.

The reason I changed it to string is because when we have multiple ids, we convert the ids to a string in the format "1,2,3" and to consolidate the logic, even if there is only one id, it gets converted string still.
___
*[pkg/sql/delegate/show_table.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZcDmg6OLTNsYNJA5d:-MSZl4U98kXsqFHfjU4F:b-m8v50i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L296)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think strconv is fully robust... check out `lexbase.EncodeEscapedSQLIdent`
</blockquote></details>

Ah thanks good call
___
*[pkg/sql/delegate/show_table.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZdcrhCTH0mBMV-Gpq:-MSZl8rx3sjXgWJq1Qad:b-xm5wtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L306)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this should would make more sense as an "else" condition right after line 296. why do it here?

so is the idea here that you can't do `SHOW CREATE TABLES database.schema.table`?
</blockquote></details>

Right now, that's valid syntax but searching up tables in other databases won't appear.

Do you think we should make this explicitly invalid syntax?


<!-- Sent from Reviewable.io -->

2021-02-02 22:03 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0GbVI0lS0P69ko7IS:-MSZlP9dCc0-DNp8hvuA:bh4zig1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ok yeah, can you file the issue? IMO we shouldn't release 21.1 with these differing. it would be a weird user experience
</blockquote></details>

yep I'll make sure to get that in with this


<!-- Sent from Reviewable.io -->

2021-02-03 19:44 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 662 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZZOFb5imW-BaZ4CqD:-MSdMm2S2GWoQsm99T-I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/ccl/logictestccl/testdata/logic_test/zone#L662)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Oops, yeah the logic for adding ZONECONFIG adds a semi colon, made sense when it previously didn't have a semicolon
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_table.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZazAX6I6ULBranw4l:-MSdNK0D7eiRiPRr9QWH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L53)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Searching up the table only applies for the existing SHOW TABLE commands, it's possible to look up tables in other databases by using the fully qualified name.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_table.go, line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZaQLe9GDuN-bBqNBQ:-MSdNYmVAalH4nrn1mNC:b-csq8xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L254)):*
> yeah it does, but if you are running through the internal executor, then the current database is "", and using "".crdb_internal.create_statements would show info from all databases
>           21 hours ago
>         RichardJCaiRichard Cai

Removed
___
*[pkg/sql/delegate/show_table.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZdcrhCTH0mBMV-Gpq:-MSdOkkc8HFQEIOLvwbB:b7chpf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L306)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Right now, that's valid syntax but searching up tables in other databases won't appear.

Do you think we should make this explicitly invalid syntax?
</blockquote></details>

Also the reason it isn't an else condition is because it's only applicable to `SHOW CREATE TABLE` commands where theres one table.

This code is a little messy because SHOW CREATE TABLE and SHOW CREATE TABLES differ in which databases can be searched. SHOW CREATE TABLE allows us to query any table in any db whereas SHOW CREATE TABLES currently only supports the current db.

Do you think it would actually be better to split the functions into two again since the underlying logic is actually different enough, it lets us cleanup the code a bit, we can extract the table resolution part thats similar.
___
*[pkg/sql/logictest/testdata/logic_test/show_create_tables, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MS0LCAo6xR2ZMdiqj8f:-MSdQBYN4BoNBYcfKbo4:b-v9wlmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6edca88a6c989f3db442f5b478cae6af67b330/pkg/sql/logictest/testdata/logic_test/show_create_tables#L35)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sounds good, can you file the issue? (you can use the same the same issue as above)
</blockquote></details>

Created issue here: https://github.com/cockroachdb/cockroach/issues/59772


<!-- Sent from Reviewable.io -->

2021-02-03 19:51 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/delegate/show_table.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSZdcrhCTH0mBMV-Gpq:-MSdReVy38L92CuiAyAw:b-mko206) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5560ba43b12ff4c0a8726fbdd9f69ba4f0bae27/pkg/sql/delegate/show_table.go#L306)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Also the reason it isn't an else condition is because it's only applicable to `SHOW CREATE TABLE` commands where theres one table.

This code is a little messy because SHOW CREATE TABLE and SHOW CREATE TABLES differ in which databases can be searched. SHOW CREATE TABLE allows us to query any table in any db whereas SHOW CREATE TABLES currently only supports the current db.

Do you think it would actually be better to split the functions into two again since the underlying logic is actually different enough, it lets us cleanup the code a bit, we can extract the table resolution part thats similar.
</blockquote></details>

yeah i agree, the only part that should be extracted is the part where there's common logic


<!-- Sent from Reviewable.io -->

2021-02-03 19:57 UTC, rafiss approved these changes
overall lgtm! but leaving a suggestion to consider..

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-:-MSdT5Py7SKfOPCRhrvd:bozlbnb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/ccl/logictestccl/testdata/logic_test/zone, line 662 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSdSa_ZCZBfNDg5wia_:-MSdSa_ZCZBfNDg5wiaa:bb91dgi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f00c86708db7a30ca65c8297c95e4002a74fbd1e/pkg/ccl/logictestccl/testdata/logic_test/zone#L662)):*
> ```
>   PARTITION p1 VALUES IN ((1)),
>   PARTITION p2 VALUES IN ((2))
> );;
> ```

does this test need to be updated now?
___
*[pkg/sql/delegate/show_table.go, line 320 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-MSdSntr3UiGfs5ojAnV:-MSdSntr3UiGfs5ojAnW:bogr260) ([raw file](https://github.com/cockroachdb/cockroach/blob/f00c86708db7a30ca65c8297c95e4002a74fbd1e/pkg/sql/delegate/show_table.go#L320)):*
> ```Go
> 
> 	switch {
> 	case len(names) == 1:
> ```

if you feel like the code would be cleaner as two functions, then let's go with that. it's not a good abstraction for a function to have an `if` in the middle that causes divergent behavior in the two conditional branches. only the logic that actually is the same between the two cases should be the part thats extracted as a function.


<!-- Sent from Reviewable.io -->

2021-02-03 21:22 UTC, rafiss approved these changes
thanks for this!

> Reviewed 5 of 8 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59412#-:-MSdlVqb7wREzUhze0p-:b-b4tcva)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-02-12 18:24 UTC, RichardJCai commented
Removing SCHEMA column, realized schemas are always explicitly added to the create statement output anyway.

2021-02-12 20:03 UTC, RichardJCai commented
I realized the logic for SHOW CREATE TABLE with multiple tables is wrong in this PR when it comes to multiple zone configs.

Closing this PR in favor for just adding the alias to the `crdb_internal.show_create_all_tables` builtin.

Will revisit adding SHOW CREATE TABLE for multiple tables if we see value to it in the future, I believe the original usecase for this ticket from #53488 will be covered by the SHOW CREATE ALL TABLES command regardless.

2021-02-12 20:03 UTC, closed without merging

2021-02-12 20:11 UTC, RichardJCai commented
Opened #60539 to handle just the SHOW CREATE ALL TABLES case