opt: create a special type for selectivity to clean up stats code
cockroachdb/cockroach pull request #59413
Opened 2021-01-26 01:42 UTC by angelazxu

Previously, the selectivity of a filter was represented by a float64 type.
There were several places in the statistics code where range checks were
being performed to ensure selectivity was between (0,1].

This change cleans up the statistics code and creates a Selectivity type with
custom methods to replace direct numerical operations, incorporating the range
check to ensure all operations on selectivity return a valid value.

As a result of implementing these changes, there are slight changes to some
values in the test files. The query plans and performance mostly stay the same.

Resolves: #53860

Release note: None

2021-01-26 01:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59413)
<!-- Reviewable:end -->

2021-01-26 06:40 UTC, RaduBerinde reviewed
The differences are very significant in many cases, we need to understand why. I suspect some of the code relies on intermediary values that are out of range.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-:-MRx8UCe-ae2bQ3rSqoM:b-4wzxqj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRxF6ln7Ho1c8zo-I9M:-MRxF6ln7Ho1c8zo-I9N:b5he8kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L830)):*
> ```Go
> 
> 	// Adjust the selectivity so we don't double-count the histogram columns.
> 	s.ApplySelectivity(1.0 / sb.selectivityFromSingleColDistinctCounts(histCols, scan, s))
> ```

This is kind of a misuse of the API - we are passing a Selectivity that we know is > 1
___
*[pkg/sql/opt/memo/statistics_builder.go, line 888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx7DEfE-CiRWa9v4so:-MRx7DEfE-CiRWa9v4sp:b6cpaie) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L888)):*
> ```Go
> 	// was calculated. For example, an index scan or index join created during
> 	// exploration could absorb some of the filter conditions.
> 	selectivity := props.Selectivity(s.RowCount / inputStats.RowCount)
> ```

shouldn't this be `MakeSelectivity`? (same in other places)
___
*[pkg/sql/opt/memo/statistics_builder.go, line 1241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx8pfHAOE-1yagXyvj:-MRx8pfHAOE-1yagXyvk:b-xpdul6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L1241)):*
> ```Go
> 	case opt.AntiJoinOp, opt.AntiJoinApplyOp:
> 		s.RowCount = max(leftStats.RowCount-s.RowCount, epsilon)
> 		s.Selectivity = (1-s.Selectivity).SelectivityInRange()
> ```

This operation should be a method
___
*[pkg/sql/opt/memo/statistics_builder.go, line 2824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx5ue67vuD-ygRSvov:-MRx5ue67vuD-ygRSvow:bg4yz91) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L2824)):*
> ```Go
> )
> 
> func minSelectivity(a, b props.Selectivity) props.Selectivity {
> ```

This belongs with the Selectivity type
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3707 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx9C_BB1bKTESso7Ul:-MRx9C_BB1bKTESso7Um:b-u9p8mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L3707)):*
> ```Go
> 	}
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> ```

remove comment
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3732 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx9Dyi9Q9jtYNHhysd:-MRx9Dyi9Q9jtYNHhyse:b-u9p8mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L3732)):*
> ```Go
> 	})
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> ```

remove comment
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3866 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx9LHq2B9rebMTWmbm:-MRx9LHq2B9rebMTWmbn:b-u9p8mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L3866)):*
> ```Go
> 	selectivity = props.MakeSelectivity(math.Pow(unknownFilterSelectivity, numUnappliedConjuncts))
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> ```

remove comment
___
*[pkg/sql/opt/memo/testdata/stats/join, line 783 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx4mAc6Nu-fQQbnEbo:-MRx4mAc6Nu-fQQbnEbp:bntliyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats/join#L783)):*
> ```
> project
>  ├── columns: x:1(int) y:2(int) s:3(string) d:4(decimal) u:6(int) v:7(int!null) rowid:8(int!null)
>  ├── stats: [rows=10000, distinct(2)=400, null(2)=-49985000, distinct(3)=500, null(3)=-49989900, distinct(6)=500, null(6)=5000, distinct(2,3)=5000, null(2,3)=-49989950, distinct(3,6)=10000, null(3,6)=-24994950, distinct(1,2,8)=10000, null(1,2,8)=0]
> ```

`-49985000` - something is going terribly wrong here :)
___
*[pkg/sql/opt/props/selectivity.go, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx4yE23D6JwWkKkc7J:-MRx4yE23D6JwWkKkc7K:bq1046y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/selectivity.go#L6)):*
> ```Go
> const epsilon = 1e-10
> 
> // Selectivity stores selectivity as a float64, while having custom methods for
> ```

The comment should explain what selectivity means (and should omit things that are immediately obvious from the code). E.g. "Selectivity is a value in the range [epsilon, 1.0] that estimates the fraction of rows that "pass" a given condition."
___
*[pkg/sql/opt/props/selectivity.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx7IPoCH7vKAPXLUx9:-MRx7IPoCH7vKAPXLUxA:blropgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/selectivity.go#L9)):*
> ```Go
> // performing operations and checking that the value is within the range of
> // [epsilon, 1.0].
> type Selectivity float64
> ```

If we want to prevent creating this directly from a float or directly assigning a literal value (which would be a good idea IMO), we could make it a struct with a private float64 member. That would force the use of `MakeSelectivity` everywhere.
___
*[pkg/sql/opt/props/selectivity.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx6UmHElShQcd2KZy1:-MRx6UmHElShQcd2KZy2:b-rze1s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/selectivity.go#L22)):*
> ```Go
> func (s Selectivity) Multiply(other Selectivity) Selectivity {
> 	s *= other
> 	return s.SelectivityInRange()
> ```

It would be cleaner to never have an instance of `Selectivity` that's out of range, e.g. we could do `return MakeSelectivity(float64(s) * float64(other))`
___
*[pkg/sql/opt/props/selectivity.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx6koBBOj74su_OeBy:-MRx6koBBOj74su_OeBz:bunmn4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/selectivity.go#L27)):*
> ```Go
> // Add is a custom method for adding two selectivities and returns the sum in
> // the valid range.
> func (s Selectivity) Add(other Selectivity) Selectivity {
> ```

This API can be error-prone - one could reasonably assume that `x.Add(y)` modifies `x`. I'd either change them so they do modify the receiver (it will need to be a pointer receiver) or rename to`Sum` and 'Product'
___
*[pkg/sql/opt/props/selectivity.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRx5cUy6URHph81E9J2:-MRx5cUy6URHph81E9J3:b-aauj8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/selectivity.go#L29)):*
> ```Go
> func (s Selectivity) Add(other Selectivity) Selectivity {
> 	s += other
> 	return  s.SelectivityInRange()
> ```

[nit] extra space - make sure you have your editor set up to run `gofmt` or `crdbfmt`.
___
*[pkg/sql/opt/props/statistics.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRxPdGTDF8JNmSh0qar:-MRxPdGTDF8JNmSh0qas:b-xum2jd) ([raw file](https://github.com/cockroachdb [...]

2021-01-26 16:52 UTC, rytaft reviewed
Nice job getting all of the tests updated-- looks like a lot of effort! You'll need to rebase from master since this conflicts with the branch right now -- happy to help with that process if you run into issues. Also looks like the plan changed for TPC-H query 7, so that might require running `q07` with `-rewrite-actual-stats=true` as well. But before bothering with that, I'd suggest trying to fix some of the bugs that @raduberinde pointed out, since otherwise you'll probably just need to re-do it.

> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-:-MRzYOBUAqBhfIv7QGg7:b-opkku8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRxF6ln7Ho1c8zo-I9M:-MRzUGWM-9u2q5Ju1F2X:bc5yi4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L830)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is kind of a misuse of the API - we are passing a Selectivity that we know is > 1
</blockquote></details>

Yea.... this was added when I added support for multi-column stats, but still wanted to include info from histograms. We can get rid of this when we support multi-column histograms.

But in the mean time, maybe we should just create a separate function called `ApplyInverseSelectivity` (or something like that) that would take a selectivity as input, and then divide by the value inside the function.
___
*[pkg/sql/opt/memo/testdata/stats/join, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzV97vD7u_088EXc7_:-MRzV97vD7u_088EXc7a:b-3l0bpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats/join#L489)):*
> ```
>       │    ├── columns: x:1(int!null) y:2(int)
>       │    ├── immutable
>       │    ├── stats: [rows=4833.33333, distinct(2)=5.00000056e-07, null(2)=0]
> ```

this distinct count looks wrong
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzWgm2E8BEXBbbdJKc:-MRzWgm2E8BEXBbbdJKd:b-8q3pj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L294)):*
> ```
> 
> ----Stats for q9_scan_6----
> column_names   row_count  distinct_count  null_count
> ```

looks like data didn't get correctly loaded for the supplier table
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzWI1X0_d-sM-xcrDZ:-MRzWI1X0_d-sM-xcrD_:brpn43r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L416)):*
> ```
> {p_partkey}   200000.00      1.00           199241.00           1.00                0.00            1.00
> 
> ----Stats for q9_scan_13----
> ```

looks like the data didn't get correctly loaded for the partsupp table either -- you'll probably have to re-load and try this again :(


<!-- Sent from Reviewable.io -->

2021-01-26 17:23 UTC, RaduBerinde approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRxF6ln7Ho1c8zo-I9M:-MRzhfTS6udJJZkXJe-4:b-mfd9mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/statistics_builder.go#L830)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Yea.... this was added when I added support for multi-column stats, but still wanted to include info from histograms. We can get rid of this when we support multi-column histograms.

But in the mean time, maybe we should just create a separate function called `ApplyInverseSelectivity` (or something like that) that would take a selectivity as input, and then divide by the value inside the function.
</blockquote></details>

Yeah I had the same thought (`UnapplySelectivity` maybe).


<!-- Sent from Reviewable.io -->

2021-01-28 22:58 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzWI1X0_d-sM-xcrDZ:-MSAAWhF9vDdt2mrdlJU:b5j44kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L416)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

looks like the data didn't get correctly loaded for the partsupp table either -- you'll probably have to re-load and try this again :(
</blockquote></details>

Reloaded both q09 and q07,  7 is looking okay now but 9 has some weird stats. A lot of values changed to 0, will look into why that happened :thinking: 
___
*[pkg/sql/opt/props/statistics.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRxPdGTDF8JNmSh0qar:-MSABv6M9qWxgW2LJM5T:bowwkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/props/statistics.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I spent quite some time debugging (out of curiosity) and found this - we are not actually modifying s.Selectivity here. Case in point on my other comment on the API being error-prone.
</blockquote></details>

Ah yes, I just changed the methods to modify selectivity - I think this clears up a lot of the weird stats, there are still some weird numbers in the tpch query stats though.


<!-- Sent from Reviewable.io -->

2021-01-28 23:43 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJ4W0AZbckec0JchY:-MSAJ4W0AZbckec0JchZ:b-iy2qmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/statistics_builder.go#L3509)):*
> ```Go
> 	maxNewDistinct, maxOldDistinct := float64(0), float64(0)
> 	multiColNullCount := -1.0
> 	minLocalSel := math.MaxFloat64
> ```

minLocalSel can also be a Selectivity, and I think it can start at 1
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJBux45ycCeIeRoh_:-MSAJBux45ycCeIeRoha:b5a6mqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/statistics_builder.go#L3523)):*
> ```Go
> 		// Don't bother including columns in the multi-column calculation that
> 		// don't contribute to the selectivity.
> 		if localSel.Get() == 1.0 {
> ```

we could also have a singleton for `OneSelectivity` and compare directly (or add a `IsOne()` method).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3716 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAMmN61tfm6BwHIBAk:-MSAMmN61tfm6BwHIBAl:bosy9uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/statistics_builder.go#L3716)):*
> ```Go
> 			selectivity.Multiply(sb.predicateSelectivity(
> 				props.MakeSelectivity(1.0), /* nonNullSelectivity */
> 				props.MakeSelectivity(0), /* nullSelectivity */
> ```

I think this should be ZeroSelectivity (we know for sure none of the nulls can be selected)
___
*[pkg/sql/opt/memo/testdata/stats/multi-column-inverted-geo, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAKfO5-FuIAAv0DxWL:-MSAKfO5-FuIAAv0DxWM:b-18gv1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/testdata/stats/multi-column-inverted-geo#L228)):*
> ```
>       │              │         └── ["B\xfd\x14\x00\x00\x00\x00\x00\x00\x00", "B\xfd\x14\x00\x00\x00\x00\x00\x00\x00"]
>       │              ├── flags: force-index=m
>       │              ├── stats: [rows=307.105263, distinct(1)=1.99999931e-07, null(1)=0, distinct(3)=2, null(3)=0, distinct(6)=3, null(6)=0, distinct(3,6)=6, null(3,6)=0]
> ```

This is a case to look at - going from 87 to effectively 0 suggests a bug. You can isolate this testcase and run it through the debugger, or sprinkle Printfs in the statistics and selectivity code to see exactly which operations lead to this value.
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 222 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAKBKeARDiYC50Uaxf:-MSAKBKeARDiYC50Uaxg:b-trrd50) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L222)):*
> ```
> ----Stats for q9_inner_join_4----
> column_names       row_count  distinct_count  null_count
> {l_discount}       0          0               0
> ```

The missing stats are not those derived by the optimizer, they are real stats that were gathered. The test tries to carry them over when you rewrite it. I would reset these files to the originals (`git checkout origin/master stats_quality/tpch`) and then run them again with `-rewrite`
___
*[pkg/sql/opt/props/selectivity.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJOxa-eZZKHfiJ-d1:-MSAJOxa-eZZKHfiJ-d2:buwso8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/selectivity.go#L34)):*
> ```Go
> // Get returns the private selectivity field, allowing it to be accessed
> // outside of this package.
> func (s *Selectivity) Get() float64 {
> ```

[nit] I'd rename to `AsFloat()`
___
*[pkg/sql/opt/props/selectivity.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSANN-qCYAR3rV_wHAa:-MSANN-qCYAR3rV_wHAb:b-4ss92t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/selectivity.go#L47)):*
> ```Go
> // the valid range.
> func (s *Selectivity) Add(other Selectivity) {
> 	s.selectivity = SelectivityInRange(s.selectivity * other.selectivity)
> ```

This should be `+`. I'd add some unit tests for this type.
___
*[pkg/sql/opt/props/statistics.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAN7lv69coZOoENtNc:-MSAN7lv69coZOoENtNd:b-to3qfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/statistics.go#L76)):*
> ```Go
> 	if relProps.Cardinality.IsZero() {
> 		s.RowCount = 0
> 		s.Selectivity = MakeSelectivity(0)
> ```

this can be `ZeroSelectivity`
___
*[pkg/sql/opt/props/statistics.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJV1V6ANSk1AwAeab:-MSAJV1V6ANSk1AwAeac:b-fs91kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/statistics.go#L98)):*
> ```Go
> // counts, and histograms.
> func (s *Statistics) ApplySelectivity(selectivity Selectivity) {
> 	s.RowCount *= selectivity.selectivity
> ```

[nit] better to use the API instead of the private field when possible
___
*[pkg/sql/opt/props/statistics.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJcXUAbBDGwrQamAs:-MSAJcXUAbBDGwrQamAt:b3y6z8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/statistics.go#L107)):*
> ```Go
> 	inverseSelectivity := 1.0 / selectivity.selectivity
> 	s.RowCount *= inverseSelectivity
> 	s.Selectivity.selectivity *= inverseSelectivity
> ```

This should be `Multiply()` so that the result is kept in the range


<!-- Sent from Reviewable.io -->

2021-02-01 23:26 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/join, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzV97vD7u_088EXc7_:-MSUrINyDoR9443_Tbdh:b8p69x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats/join#L489)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this distinct count looks wrong
</blockquote></details>

reverted to original distinct count with new changes!
___
*[pkg/sql/opt/memo/testdata/stats/multi-column-inverted-geo, line 228 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAKfO5-FuIAAv0DxWL:-MSUs41fCXAr1NccX3JL:bdfixrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/memo/testdata/stats/multi-column-inverted-geo#L228)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a case to look at - going from 87 to effectively 0 suggests a bug. You can isolate this testcase and run it through the debugger, or sprinkle Printfs in the statistics and selectivity code to see exactly which operations lead to this value.
</blockquote></details>

the counts are now back to the original values with the new changes :)
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzWgm2E8BEXBbbdJKc:-MSUtQqZCF-O7-f71lcT:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L294)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

looks like data didn't get correctly loaded for the supplier table
</blockquote></details>

fixed
___
*[pkg/sql/opt/memo/testdata/stats_quality/tpch/q09, line 416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MRzWI1X0_d-sM-xcrDZ:-MSUtVzU0W71XXi39cDU:b6ecaio) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5d8d51fdd51e72d89f562dcb9fbf7b04d4120ff/pkg/sql/opt/memo/testdata/stats_quality/tpch/q09#L416)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Reloaded both q09 and q07,  7 is looking okay now but 9 has some weird stats. A lot of values changed to 0, will look into why that happened :thinking: 
</blockquote></details>

update: fixed
___
*[pkg/sql/opt/props/selectivity.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSANN-qCYAR3rV_wHAa:-MSUtZqB2J6BKdNF4VFj:b-boovgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/selectivity.go#L47)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be `+`. I'd add some unit tests for this type.
</blockquote></details>

oops - fixed, also added selectivity_test.go
___
*[pkg/sql/opt/props/statistics.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSAJcXUAbBDGwrQamAs:-MSUtiRJ6fzq1uR2pMiL:bmx6we6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4496ddf2a1b703d792d04da51ee29d87516053c7/pkg/sql/opt/props/statistics.go#L107)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be `Multiply()` so that the result is kept in the range
</blockquote></details>

I ended up creating a Divide() method for selectivity, since inverseSelectivity could be > 1 it would be improper for it to be a selectivity type. Instead, we're dividing by selectivity now in here (also updated the method name since I got rid of inverseSelectivity).


<!-- Sent from Reviewable.io -->

2021-02-01 23:54 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/memo/testdata/stats/scan, line 1051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSV-ueY351suS6szIah:-MSV-ueY351suS6szIai:bj9iisj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/testdata/stats/scan#L1051)):*
> ```
>  │         ├── columns: t47742.b:2(bool!null) rowid:3(int!null)
>  │         ├── constraint: /-2/3: [/true - /true]
>  │         ├── stats: [rows=2640.64496, distinct(2)=11, null(2)=0]
> ```

I'm looking at this line right now, not sure what changed distinct(2)=1.00246926 to 11. 


<!-- Sent from Reviewable.io -->

2021-02-02 16:54 UTC, mgartner requested changes
So close! Great work! Let me know if I can help you debug that row count that went from `1.00...` to `11`.

> Reviewed 13 of 52 files at r2, 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-:-MSYeHH49HpRAw4-D99h:b-4bw7yb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3538 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_1PHCEgZAgXWTNyS:-MSY_1PHCEgZAgXWTNyT:b-y62ykt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3538)):*
> ```Go
> 		}
> 		if localSel.AsFloat() < minLocalSel.AsFloat() {
> 			minLocalSel = localSel
> ```

I think this `if` can be simplified to `minLocalSel = props.MinSelectivity(localSel, minLocalSel)`.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_8702R9vr8MVbZcO:-MSY_8702R9vr8MVbZcP:bqxiih9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3605)):*
> ```Go
> 			)
> 			if selLowDistinctCountCols.AsFloat() < minLocalSel.AsFloat() {
> 				minLocalSel = selLowDistinctCountCols
> ```

I think you can use `props.MinSelectivity` to simplify this too.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3659 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_chD6jXVdsIusi7e:-MSY_chD6jXVdsIusi7f:bl7n63s) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3659)):*
> ```Go
> 
> 	// Calculate the selectivity of the predicate.
> 	nonNullSelectivity := props.MakeSelectivity(fraction(newDistinct, oldDistinct))
> ```

`props.MakeSelectivity` guarantees a maximum selectivity of 1, so I think you could get rid of the `fraction` function definition, and make this simply: `props.MakeSelectivity(newDistinct / oldDistinct)`. There's a few places `fraction` is used that you could replace.
___
*[pkg/sql/opt/props/selectivity_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYbnLa8zpLEh2Z0vyG:-MSYbnLb6CcCnMLeVRE-:b9chj3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package props_test
> ```

Was there something preventing you from putting these tests in the `props` package? If you can put the tests in the same package, then you could un-export `SelectivityInRange` by renaming to `selectivityInRange`, which might be nice. It'd also allow you to use the same `epsilon` constant rather than declaring it twice.
___
*[pkg/sql/opt/props/selectivity_test.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYcyibAFS4IO4Aw7P8:-MSYcyibAFS4IO4Aw7P9:b-arwh01) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L23)):*
> ```Go
> 
> func TestSelectivity(t *testing.T) {
> 	test := func(card, expected props.Selectivity) {
> ```

What does `card` stand for here? Would `actual` be a better name?
___
*[pkg/sql/opt/props/selectivity_test.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYdaxc3W98DKXjeDKL:-MSYdaxc3W98DKXjeDKM:bs765bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L88)):*
> ```Go
> 	testMultiply(s(inf), s(inf), props.OneSelectivity)
> 	testMultiply(s(0), s(0.4), s(epsilon * 0.4))
>   testMultiply(props.ZeroSelectivity, s(0.5), s(epsilon))
> ```

Looks like the indenting is off here. make sure to run crlfmt. (let me know if you need help setting it up, there's _some_ guidance here: https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks)


<!-- Sent from Reviewable.io -->

2021-02-02 18:18 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/props/selectivity_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYbnLa8zpLEh2Z0vyG:-MSYxAz08sHBDa8fXA_n:b-28lh42) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Was there something preventing you from putting these tests in the `props` package? If you can put the tests in the same package, then you could un-export `SelectivityInRange` by renaming to `selectivityInRange`, which might be nice. It'd also allow you to use the same `epsilon` constant rather than declaring it twice.
</blockquote></details>

Hmm when I tried using `props` it created an import cycle because I was trying to import `"github.com/cockroachdb/cockroach/pkg/sql/opt/props"` to be able to access `Selectivity`, not sure if there's another way to that though?
___
*[pkg/sql/opt/props/selectivity_test.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYcyibAFS4IO4Aw7P8:-MSYqekj-ThOtt2HGEER:b-5f5q28) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L23)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What does `card` stand for here? Would `actual` be a better name?
</blockquote></details>

Oops, just realized card is short for cardinality 😆 I was looking the cardinality tests while making this. Will change to actual!!


<!-- Sent from Reviewable.io -->

2021-02-02 18:28 UTC, RaduBerinde commented
___
*[pkg/sql/opt/props/selectivity_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYbnLa8zpLEh2Z0vyG:-MSZ-9iO5vCoxvlQwQR1:bwwz045) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L11)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Hmm when I tried using `props` it created an import cycle because I was trying to import `"github.com/cockroachdb/cockroach/pkg/sql/opt/props"` to be able to access `Selectivity`, not sure if there's another way to that though?
</blockquote></details>

If you use `props`, you are already "inside" that package, you can just refer to `Selectivity` directly.


<!-- Sent from Reviewable.io -->

2021-02-02 23:09 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3538 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_1PHCEgZAgXWTNyS:-MSZGgyL76fmBHGPp4LJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3538)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think this `if` can be simplified to `minLocalSel = props.MinSelectivity(localSel, minLocalSel)`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3605 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_8702R9vr8MVbZcO:-MSZGgWbDoDEPw5za_Ai:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3605)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think you can use `props.MinSelectivity` to simplify this too.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3659 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_chD6jXVdsIusi7e:-MSZHIhRCu933UllOk0B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3659)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`props.MakeSelectivity` guarantees a maximum selectivity of 1, so I think you could get rid of the `fraction` function definition, and make this simply: `props.MakeSelectivity(newDistinct / oldDistinct)`. There's a few places `fraction` is used that you could replace.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 1051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSV-ueY351suS6szIah:-MSZz-KE-9bi6odX4Ju7:bymh5c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/testdata/stats/scan#L1051)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

I'm looking at this line right now, not sure what changed distinct(2)=1.00246926 to 11. 
</blockquote></details>

Becca and I spent some time looking at this and turns out this is just a weird test case, so nothing to worry about :)
___
*[pkg/sql/opt/props/selectivity_test.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYbnLa8zpLEh2Z0vyG:-MSZ45gA1El-g8r9bDIp:b-o5hp31) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L11)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If you use `props`, you are already "inside" that package, you can just refer to `Selectivity` directly.
</blockquote></details>

Oh got it, thanks!
___
*[pkg/sql/opt/props/selectivity_test.go, line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSYdaxc3W98DKXjeDKL:-MSZHN5a5CRpwBERAr9R:b-q8g4ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/props/selectivity_test.go#L88)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Looks like the indenting is off here. make sure to run crlfmt. (let me know if you need help setting it up, there's _some_ guidance here: https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/154206209/Goland+Tips+and+Tricks)
</blockquote></details>

Done. ty :D


<!-- Sent from Reviewable.io -->

2021-02-02 23:46 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Awesome!! You'll need to rebase from master to be able to merge this, but otherwise this seems ready to go (just a few nits to fix below).

> Reviewed 14 of 52 files at r2, 5 of 12 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-:-MS_7Qa79DX-4404ZLFg:b5cwrfh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @angelazxu, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3632 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_6mW-1G6zkKCjcvoI:-MS_6mW-1G6zkKCjcvoJ:bng8ai9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3632)):*
> ```Go
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> 	// can end up with weird and inefficient plans if we estimate 0 rows.
> ```

This comment can be removed
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3802 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_77Os4xrlZH79G_2l:-MS_77Ot3AWpCE4q2-MA:bng8ai9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3802)):*
> ```Go
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> 	// can end up with weird and inefficient plans if we estimate 0 rows.
> ```

This comment can be removed
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3850 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_79eG84tPj3NzDbac:-MS_79eG84tPj3NzDbad:bng8ai9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3850)):*
> ```Go
> 
> 	// Avoid setting selectivity to 0. The stats may be stale, and we
> 	// can end up with weird and inefficient plans if we estimate 0 rows.
> ```

This comment can be removed
___
*[pkg/sql/opt/memo/testdata/stats/scan, line 1051 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSV-ueY351suS6szIah:-MS_4Mxu2QbIou_vx1bH:b-3p8e6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/testdata/stats/scan#L1051)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Becca and I spent some time looking at this and turns out this is just a weird test case, so nothing to worry about :)
</blockquote></details>

In case y'all are curious, if you look at the histogram above, you'll see that the "true" bucket has a non-zero range with a large number of distinct values, which would never happen in real life. This was a weird regression test generated by SQLSmith, so I'm not too concerned that we're estimating distinct count=11.
___
*[pkg/sql/opt/props/selectivity.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_1bvr-Sbo1rebE7nE:-MS_1bvr-Sbo1rebE7nF:b-y6se7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/props/selectivity.go#L71)):*
> ```Go
> // SelectivityInRange performs the range check, if the selectivity falls
> // outside of the range, this method will return the appropriate min/max value.
> func SelectivityInRange(sel float64) float64 {
> ```

Is this function ever used outside this package? If not, you can unexport it by renaming it to `selectivityInRange` (looks like @mgartner also suggested this in another comment).
___
*[pkg/sql/opt/props/statistics.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_3ZNgAQhU67aS0pyM:-MS_3ZNgAQhU67aS0pyN:bnem98g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/props/statistics.go#L102)):*
> divides by a given selectivity to the statistics

[nit] this sounds kind of weird, I'd just say "divides the statistics by the given selectivity".


<!-- Sent from Reviewable.io -->

2021-02-02 23:54 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @angelazxu, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3632 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_6mW-1G6zkKCjcvoI:-MS_982G0PCDgRqGA1XQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3632)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment can be removed
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3802 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_77Os4xrlZH79G_2l:-MS_962XCx2NEmJHB7KM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3802)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment can be removed
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3850 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_79eG84tPj3NzDbac:-MS_95k-4Zpce4hcGB56:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/memo/statistics_builder.go#L3850)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This comment can be removed
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/selectivity.go, line 71 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_1bvr-Sbo1rebE7nE:-MS_8hhN00KYjzO8ryTZ:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/props/selectivity.go#L71)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this function ever used outside this package? If not, you can unexport it by renaming it to `selectivityInRange` (looks like @mgartner also suggested this in another comment).
</blockquote></details>

Done!
___
*[pkg/sql/opt/props/statistics.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_3ZNgAQhU67aS0pyM:-MS_8HMR6IQVsDlV2BKp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cdce611f5b4931f170242195ccc925ea97227c0/pkg/sql/opt/props/statistics.go#L102)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> divides by a given selectivity to the statistics

[nit] this sounds kind of weird, I'd just say "divides the statistics by the given selectivity".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 02:56 UTC, mgartner reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you get the build passing. Great job getting this to the finish line!

> Reviewed 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-:-MS_mWt12vl60idQZpRl:bf0wvvv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @angelazxu, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3659 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_chD6jXVdsIusi7e:-MS_lKV45PC6CBP6oH2W:b-paxcpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3659)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `fraction` function defined in this file is now unused and you should delete it. The linter is complaining about it (click on "Details" link next to the "GitHub CI (Cockroach)" check on the Github PR page to view the failing tests and lints).
___
*[pkg/sql/opt/props/selectivity.go, line 4 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MS_nH_x-X2oLOOZLYIl:-MS_nH_x-X2oLOOZLYIm:bluro5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8a5956c8368ef5d57bc2dd062b2c4a20cca6363/pkg/sql/opt/props/selectivity.go#L4)):*
> ```Go
> //
> // Use of this software is governed by the Business Source License included
> // in the file licenses/BSL.txt.
> ```

It looks like the linter is complaining about the license in this file and `selectivity_test.go`. The content looks the same, but the newline in this paragraph is different from others. Try a newline after `License` like this instead:

```
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.txt.
```


<!-- Sent from Reviewable.io -->

2021-02-03 03:01 UTC, rytaft approved these changes
> Reviewed 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @angelazxu, @mgartner, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-02-03 17:41 UTC, mgartner approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @angelazxu, @mgartner, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-02-03 19:03 UTC, rytaft approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @angelazxu, @mgartner, and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-02-04 00:12 UTC, angelazxu commented
bors r+

2021-02-04 00:21 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59413)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @angelazxu, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 3659 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_chD6jXVdsIusi7e:-MSeO0HT1Is6gBdaRGRl:bx9q4f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3659)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The `fraction` function defined in this file is now unused and you should delete it. The linter is complaining about it (click on "Details" link next to the "GitHub CI (Cockroach)" check on the Github PR page to view the failing tests and lints).
</blockquote></details>

I ended up adding the `fraction` function back, since it ensures we're not dividing by 0 (which we can't really add to the MakeSelectivity method since it was an operation between floats). This was causing some issues like infinite row counts in some places which led to MaxCost errors. :)


<!-- Sent from Reviewable.io -->

2021-02-04 00:40 UTC, merged

2021-02-04 02:26 UTC, mgartner commented
___
*[pkg/sql/opt/memo/statistics_builder.go, line 3659 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59413#-MSY_chD6jXVdsIusi7e:-MSeq_9F-z3EES2wITTU:b-42sf3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d89d7e5c961c353a9e30b19fe60b3c2b7ef43ae/pkg/sql/opt/memo/statistics_builder.go#L3659)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

I ended up adding the `fraction` function back, since it ensures we're not dividing by 0 (which we can't really add to the MakeSelectivity method since it was an operation between floats). This was causing some issues like infinite row counts in some places which led to MaxCost errors. :)
</blockquote></details>

Makes sense! One option (which you can do in a follow-up PR if you'd like) is to make a `props.MakeSelectivityFromFraction(a, b)` where `a` and `b` are integers and the logic of `fraction` gets moved to that function.


<!-- Sent from Reviewable.io -->

2021-02-08 21:00 UTC, angelazxu commented
@mgartner Just added it! https://github.com/cockroachdb/cockroach/pull/60012