sql: add escape_string_warning session variable for compatibility
cockroachdb/cockroach pull request #59479
Opened 2021-01-27 15:15 UTC by johnseekins

Relates to #22937

This makes it possible for Zabbix to successfully connect to CockroachDB.
See https://www.postgresql.org/docs/10/runtime-config-compatible.html#GUC-ESCAPE-STRING-WARNING
Release note (sql change): The escape_string_warning session variable from
PostgreSQL was added with compatibility-only support. It defaults to `ON`
and cannot be changed.

2021-01-27 15:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59479)
<!-- Reviewable:end -->

2021-01-27 16:52 UTC, johnseekins commented
Because I messed up my fork for #58870, I've re-submitted this.

2021-01-27 19:45 UTC, otan commented on pkg/sql/vars.go
> +	// Supported for PG compatibility only
nit: period at end of sentence

2021-01-27 19:47 UTC, otan reviewed
Thanks for the contribution!

Can you add tests here:

https://github.com/cockroachdb/cockroach/blob/9a93dafac6e63686fc3668d17b62973e9d3f9579/pkg/sql/logictest/testdata/logic_test/set#L147

You can run these by tests by running ` make testbaselogic FILES='set'`

2021-01-27 20:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59479)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)

___
*[pkg/sql/vars.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59479#-MS4UYQQAdt_ilLAX0uQ:-MS4UYQQAdt_ilLAX0uR:b-v8qd1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9eeabf1a60c821ed1349348d370efb42fff3933/pkg/sql/vars.go#L151)):*
> ```Go
> 		},
> 		Get:           func(evalCtx *extendedEvalContext) string { return "ON" },
> 		GlobalDefault: func(_ *settings.Values) string { return "ON" },
> ```


the code here shouldn't be parsing "on" and "off" directly -- we have helper functions to do that. (the reason is that it's also allowed to use true/false instead of on/off)

to continue the discussion from the other PR i reviewed:

so it seems like it's important for zabbix to be able to set this to "on", even though CockroachDB does not implement the "on" functionality. luckily, according to the PG docs, it seems like this setting only has any effect if standard_conforming_strings is set to off, and right now we only allow standard_conforming_strings to be on. 

so for this patch, we should add a TODO to `standard_confirming_strings` saying that if we add full support, we need to update the logic of `escape_string_warning` to only allow it to be set to `on` ONLY if `standard_confirming_strings` is `off`. something like this. 

and the escape_string_warning definition should just be this:

```
	`escape_string_warning`: makeCompatBoolVar(`escape_string_warning`, true, true /* anyAllowed */),
```


<!-- Sent from Reviewable.io -->

2021-01-27 20:29 UTC, rafiss reviewed
note: to respond to these comments, you can just make the changes, then amend your existing commit. then force-push the commit to your github branch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59479#-:-MS4XFzF9rOkPFcHDwE8:b2gy9j5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)



<!-- Sent from Reviewable.io -->

2021-01-29 05:55 UTC, rafiss reviewed
thank you for your contribution!

bors r+

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59479#-:-MSBhWndCYLnFXH0Hsav:b-3oqivg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)



<!-- Sent from Reviewable.io -->

2021-01-29 05:57 UTC, rafiss commented
bors r- 

didn't notice the tests failing

2021-01-29 06:01 UTC, rafiss requested changes
there are a couple of other tests that need to be updated now that there's a new variable. the test can get updated automatically if you run this:

```
make testlogic FILES='information_schema|pg_catalog|show_source'  TESTFLAGS='-rewrite'`
```

after that then this looks good to go!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59479#-:-MSBiKTdAE9_gP1pwikB:bmmvy6m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @johnseekins)

___
*[pkg/sql/logictest/testdata/logic_test/set, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59479#-MSBi7p022q_jmbWgqCS:-MSBi7p022q_jmbWgqCT:b-thirfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b21b9cf792e78524d494f49bea69b3b382e5c7b6/pkg/sql/logictest/testdata/logic_test/set#L147)):*
> ```
> SET escape_string_warning = 'ON'
> 
> statement error parameter "escape_string_warning" cannot be changed
> ```

this actually should be:

```
statement ok
SET escape_string_warning = 'off'
```

it works because we've used `anyAllowed==true` in the code


<!-- Sent from Reviewable.io -->

2021-02-01 19:04 UTC, rafiss commented
thank you for this change!

bors r+

2021-02-01 19:04 UTC, rafiss approved these changes

2021-02-01 19:39 UTC, merged