sql: hook up multi-region DDL to new zone config attributes
cockroachdb/cockroach pull request #59591
Opened 2021-01-29 18:54 UTC by aayushshah15

After the introduction of #57184, we can constrain voting replicas
separately from non-voting replicas using the new attributes
'num_voters` and `voter_constraints`. This commit connects our
multi-region DDL statements to leverage these new attributes.

Broadly speaking,
- The existing `constraints` and `num_replicas` fields are set at the
database level, to be inherited by table/partition level zone configs.
- The new attributes: `num_voters` and `voter_constraints` (along with
accompanying `lease_preferences` for these voters) are set at the
table/partition level.

This brings the implementation of these DDL statements inline with the
functional specfication.

Fixes #57663

Release note: None

2021-01-29 18:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59591)
<!-- Reviewable:end -->

2021-01-29 19:51 UTC, aayushshah15 commented
I'm still walking through and fixing the tests inside `region_util_test.go`, but the rest should be RFAL. @andreimatei and @nvanbenschoten I've tagged both of y'all in hopes of getting one. Feel free to ignore the review request if you'd prefer.

2021-01-30 19:24 UTC, nvanbenschoten reviewed
Very exciting!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-:-MSJk7Iy12t3XNZVSAYC:bvbyvqt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @andreimatei, and @otan)

___
*[pkg/sql/region_util.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJhxj49em18b7C0rMd:-MSJhxj49em18b7C0rMe:b-w1lh5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L171)):*
> ```Go
> // theoretical (2-2-1) voting replica configuration, where the primary region
> // has 2 voting replicas and the next closest region has another 2. This allows
> // for stable write latencies even under single node failures.
> ```

stable read and write latencies
___
*[pkg/sql/region_util.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiUhd-4QhiW6ce7QT:-MSJiUhd-4QhiW6ce7QU:b-1npw0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L187)):*
> ```Go
> 	switch regionConfig.SurvivalGoal {
> 	case descpb.SurvivalGoal_ZONE_FAILURE:
> 		// numVoters in the region with affinity + 1 replica for every other region.
> ```

I don't know how ambitious you want to be here, but a bit of exposition and maybe even a diagram for each case would be fantastic for any future reader trying to understand the rationale behind these choices. As you well know, there were a lot of considerations that went into them and they're deceptively subtle.
___
*[pkg/sql/region_util.go, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiBeT65slJp28rl1Q:-MSJiBeT65slJp28rl1R:b-da2lve) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L189)):*
> ```Go
> 		// numVoters in the region with affinity + 1 replica for every other region.
> 		numVoters = numVotersForZoneSurvival
> 		numReplicas = numRegions + numVoters - 1
> ```

nit: `numVoters + numRegions - 1` or even `numVoters + (numRegions - 1)` would be a little more clear and would match better with the REGION_FAILURE case.
___
*[pkg/sql/region_util.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJjEK057LWl6vsop56:-MSJjEK057LWl6vsop57:brexuas) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L194)):*
> ```Go
> 		// other region.
> 		numVoters = numVotersForRegionSurvival
> 		numReplicas = numVoters/2 + numRegions - 1
> ```

nit: consider pulling out a helper called `minorityQuorum` or something similar to perform this floor division. Right now, you do it in a few places.
___
*[pkg/sql/region_util.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiQwHDArikO9UYXw9:-MSJiQwHDArikO9UYXwA:boa6p5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L195)):*
> ```Go
> 		numVoters = numVotersForRegionSurvival
> 		numReplicas = numVoters/2 + numRegions - 1
> 		if numReplicas < numVoters {
> ```

Give this a comment.
___
*[pkg/sql/region_util.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJjWLH225pM-23A6EL:-MSJjWLH225pM-23A6EM:b-sumgki) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L218)):*
> ```Go
> 	case descpb.SurvivalGoal_ZONE_FAILURE:
> 		return []zonepb.ConstraintsConjunction{
> 			{
> ```

Could you leave a comment about why we don't need the `NumReplicas` attribute? Basically just copying over the comment on the field and what it means to be unspecified.
___
*[pkg/sql/region_util_test.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJk1tZ58gb0iSl62o4:-MSJk1tZ58gb0iSl62o5:bhznydh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util_test.go#L171)):*
> ```Go
> 	for _, tc := range testCases {
> 		t.Run(tc.desc, func(t *testing.T) {
> 			res, _ := zoneConfigForDatabase(tc.regionConfig)
> ```

Let's check the error using `require.NoError`.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJgned2cbhkWEncK_K:-MSJgned2cbhkWEncK_L:bj37gal) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/logictest/testdata/logic_test/multiregion#L813)):*
> ```
>                             voter_constraints = '[+region=us-east-1]',
>                             lease_preferences = '[[+region=us-east-1]]'
> ```

In a follow-up commit, should we add some extra test cases for setups that aren't exercised here? For instance, I don't think any of these tests have more than 3 regions, which exercises some interesting cases for region survivability.


<!-- Sent from Reviewable.io -->

2021-01-31 03:30 UTC, aayushshah15 reviewed
I'm still in the process of adding a commit to this PR that contains some 5-region logic tests, but this is RFAL besides that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-:-MSLTJwS26w2NKPdsMob:bxk2i7v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/sql/region_util.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJhxj49em18b7C0rMd:-MSKQFP89_rJEMWio4mN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

stable read and write latencies
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiUhd-4QhiW6ce7QT:-MSL7SUcBJd0RvQJsAWs:bt0hnmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L187)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't know how ambitious you want to be here, but a bit of exposition and maybe even a diagram for each case would be fantastic for any future reader trying to understand the rationale behind these choices. As you well know, there were a lot of considerations that went into them and they're deceptively subtle.
</blockquote></details>

I added some exposition along with basic diagrams inside `synthesizeVoterConstraints`, and I moved the `numVotersFor{Region,Zone}Survival` constants to live inside `getNumVotersAndReplicas`. LMK if that's not what you had in mind, or if its missing some bit of insight that you think should be mentioned.
___
*[pkg/sql/region_util.go, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiBeT65slJp28rl1Q:-MSKQGOTE8xkeZOPOq5i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L189)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `numVoters + numRegions - 1` or even `numVoters + (numRegions - 1)` would be a little more clear and would match better with the REGION_FAILURE case.
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJjEK057LWl6vsop56:-MSKQHWr4e4or7DWmXNt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L194)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider pulling out a helper called `minorityQuorum` or something similar to perform this floor division. Right now, you do it in a few places.
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiQwHDArikO9UYXw9:-MSL8k9B4izxn6xamz6S:b-l0mig2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L195)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a comment.
</blockquote></details>

Done. LMK if this is not what you had in mind.
___
*[pkg/sql/region_util.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJjWLH225pM-23A6EL:-MSKQwPk8apnqi9WNiXU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L218)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you leave a comment about why we don't need the `NumReplicas` attribute? Basically just copying over the comment on the field and what it means to be unspecified.
</blockquote></details>

Done.
___
*[pkg/sql/region_util_test.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJk1tZ58gb0iSl62o4:-MSLSctfEot2EPoSYjU3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util_test.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's check the error using `require.NoError`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-31 20:10 UTC, otan reviewed
minor nits for changes in general, makes sense to me but haven't thought about these constraints as deep!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-:-MSP3FEO2gP2hKIBd-BR:b2vzryn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @andreimatei, and @nvanbenschoten)

___
*[pkg/sql/region_util.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2L47Dh556vnnEJtw:-MSP2L47Dh556vnnEJtx:bomlmym) ([raw file](https://github.com/cockroachdb/cockroach/blob/f955d8d86c89028c00de80850cfc67d8a5778f49/pkg/sql/region_util.go#L97)):*
> ```Go
> }
> 
> // zoneConfigFromRegionConfigForDatabase generates a desired ZoneConfig based
> ```

this longer name was deliberate as `zoneConfigForTable` does not make it clear it is for multi region setup. i'd prefer to keep it this way for other function names too.
(unless we moved this to another package which makes this clear /shrug)
___
*[pkg/sql/region_util.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2TgN7GvZtX9izTYD:-MSP2TgN7GvZtX9izTYE:b-55rmmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5f26e2d4f85b4e5d4d5d5727826ad6bd817608c/pkg/sql/region_util.go#L106)):*
> ```Go
> // failure tolerance. This method will generate a ZoneConfig object representing
> // the following attributes:
> // num_voters = 5
> ```

nit: probably feels more natural for these to look like JSON? up to you.
___
*[pkg/sql/region_util.go, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2sF-EyZLgnuwgp40:-MSP2sF-EyZLgnuwgp41:b-f0xw22) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5f26e2d4f85b4e5d4d5d5727826ad6bd817608c/pkg/sql/region_util.go#L309)):*
> ```Go
> var multiRegionZoneConfigFields = []tree.Name{
> 	"num_replicas",
> 	"num_voters",
> ```

nit: any reason to change the sorted order? :P 
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJgned2cbhkWEncK_K:-MSP386S1nKBxzW8dRyK:b-davux6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/logictest/testdata/logic_test/multiregion#L813)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

In a follow-up commit, should we add some extra test cases for setups that aren't exercised here? For instance, I don't think any of these tests have more than 3 regions, which exercises some interesting cases for region survivability.
</blockquote></details>

I would argue these belong to the unit tests instead.


<!-- Sent from Reviewable.io -->

2021-01-31 20:56 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/sql/region_util.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2L47Dh556vnnEJtw:-MSP4UeM-MlPo7AK6E4W:b1eygj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f955d8d86c89028c00de80850cfc67d8a5778f49/pkg/sql/region_util.go#L97)):*
> does not make it clear it is for multi region setup

There aren't any other contexts where we're synthesizing a "zone config for a database" (are there?) and the first godoc comment makes it clear. IMO the previous naming was a bit too long and mutually inconsistent. The method name also doesn't need to include `FromRegionConfig`. The typed function parameter(s) are self-documenting in this regard.
___
*[pkg/sql/region_util.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2TgN7GvZtX9izTYD:-MSP4FFSEFM0YiUhaQ78:b-f1er4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5f26e2d4f85b4e5d4d5d5727826ad6bd817608c/pkg/sql/region_util.go#L106)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: probably feels more natural for these to look like JSON? up to you.
</blockquote></details>

It's just the way these are printed when you do a `SHOW ZONE CONFIGURATION FOR ... `. They aren't JSON and we don't really print these out in JSON-like format anywhere AFAICT.
___
*[pkg/sql/region_util.go, line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2sF-EyZLgnuwgp40:-MSP73vS8W5F8Ny-HQy9:b1bll59) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5f26e2d4f85b4e5d4d5d5727826ad6bd817608c/pkg/sql/region_util.go#L309)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: any reason to change the sorted order? :P 
</blockquote></details>

It's the order in which `SHOW ZONE CONFIGURATION FOR..` prints it to the CLI, except that I didn't realize `global_reads` is before everything else. Fixed now. 


<!-- Sent from Reviewable.io -->

2021-01-31 21:05 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/sql/region_util.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2L47Dh556vnnEJtw:-MSPFUmh8VpByrXXpUWW:bkdqff7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f955d8d86c89028c00de80850cfc67d8a5778f49/pkg/sql/region_util.go#L97)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

> does not make it clear it is for multi region setup

There aren't any other contexts where we're synthesizing a "zone config for a database" (are there?) and the first godoc comment makes it clear. IMO the previous naming was a bit too long and mutually inconsistent. The method name also doesn't need to include `FromRegionConfig`. The typed function parameter(s) are self-documenting in this regard.
</blockquote></details>

i'm used to disappointment when i find a method takes in something i don't have because it's name leads me to believe it does something else ;) in this case i see someone wanting to make a zone config for database only to realise it is only for multiregion only, which the name originally meant to disambiguate.

probably more reason to put this in a separate package (`multiregion` package?), but we can punt on that for now. 
___
*[pkg/sql/region_util.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2TgN7GvZtX9izTYD:-MSPFRR3DlBBlFGKL6XT:b-taq5sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5f26e2d4f85b4e5d4d5d5727826ad6bd817608c/pkg/sql/region_util.go#L106)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

It's just the way these are printed when you do a `SHOW ZONE CONFIGURATION FOR ... `. They aren't JSON and we don't really print these out in JSON-like format anywhere AFAICT.
</blockquote></details>

ah i thought those constraint things were JSON, no woz
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJgned2cbhkWEncK_K:-MSPFLNE4oNK7MeJnUQ8:b-hv7vcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/logictest/testdata/logic_test/multiregion#L813)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I would argue these belong to the unit tests instead.
</blockquote></details>

(These being in region_util_test.go)


<!-- Sent from Reviewable.io -->

2021-01-31 22:18 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, but Oliver should also sign off.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-:-MSPTa435n0LnT_lDUPj:bk0hogh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15, @ajstorm, @andreimatei, and @otan)

___
*[pkg/sql/region_util.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJiUhd-4QhiW6ce7QT:-MSPSxMDETEghYpMgSiP:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/region_util.go#L187)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I added some exposition along with basic diagrams inside `synthesizeVoterConstraints`, and I moved the `numVotersFor{Region,Zone}Survival` constants to live inside `getNumVotersAndReplicas`. LMK if that's not what you had in mind, or if its missing some bit of insight that you think should be mentioned.
</blockquote></details>

Looks great!
___
*[pkg/sql/region_util.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSPU8CSA9iR8GwVOQuC:-MSPU8CSA9iR8GwVOQuD:b-smxs48) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b71b10d596cd2e7b0f985e2dbb81c95f564c7c/pkg/sql/region_util.go#L168)):*
> ```Go
> }
> 
> func minorityQuorum(numVoters int32) int32 {
> ```

Add a note here that this requires `numVoters` to be odd. Or support even and odd voter counts with something like:
```
return ((numVoters + 1) / 2) - 1
```
It would also be nice to define in a comment what this function returns. This is leading me to realize that "minority quorum" might not be the right term, at least not in how it's defined [elsewhere](https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels). What we really want the function to return is "the maximum number of tolerated failures, given a number of total voters" — the `f` in `n=2f+1`. So many `maxToleratedFailures` is a better name. What do you think?
___
*[pkg/sql/region_util.go, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSPSzB0C60syReZw2oa:-MSPSzB0C60syReZw2ob:bogl8y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b71b10d596cd2e7b0f985e2dbb81c95f564c7c/pkg/sql/region_util.go#L214)):*
> ```Go
> // of a multi-region database or the home region of a table in such a database.
> //
> // Under region failure tolerance, we will constrain exactly <quorum - 1> voting
> ```

nit: in a few of these comments, you describe the region failure tolerance behavior first, but then in all of your switch statements, you handle the zone failure tolerance first. Consider switching the comments around.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJgned2cbhkWEncK_K:-MSPTYvWEhmzRPAH2vm0:b-qx45oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/logictest/testdata/logic_test/multiregion#L813)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(These being in region_util_test.go)
</blockquote></details>

That SGTM.


<!-- Sent from Reviewable.io -->

2021-01-31 23:41 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/sql/region_util.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSP2L47Dh556vnnEJtw:-MSPG6ek2z7wizZp0rOy:byes9si) ([raw file](https://github.com/cockroachdb/cockroach/blob/f955d8d86c89028c00de80850cfc67d8a5778f49/pkg/sql/region_util.go#L97)):*
> someone wanting to make a zone config for database only to realise it is only for multiregion

Makes sense, changed the names to indicate that they should only be used for multi-region objects. LMK if you dislike.

> disappointment when i find a method takes in something i don't have

Well we'd run out of the 100 character limit pretty quickly with methods that take a lot of parameters :) 
For instance, how would we rename a method like this? https://github.com/cockroachdb/cockroach/blob/c41a6f68e9e63b1ca5260c63c9f0ae95251d31fa/pkg/kv/kvserver/replica_command.go#L920

Not to bike-shed too much on this, but I'll re-iterate that its the job of the function signature to describe what sort of parameters the function expects, and that's the thing to be looking at to avoid the disappointment.

>probably more reason to put this in a separate package (multiregion package?), but we can punt on that for now.

Agreed, this'd make things cleaner.
___
*[pkg/sql/region_util.go, line 168 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSPU8CSA9iR8GwVOQuC:-MSPmbNhBEpZk0cWKNrr:bm27zve) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b71b10d596cd2e7b0f985e2dbb81c95f564c7c/pkg/sql/region_util.go#L168)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a note here that this requires `numVoters` to be odd. Or support even and odd voter counts with something like:
```
return ((numVoters + 1) / 2) - 1
```
It would also be nice to define in a comment what this function returns. This is leading me to realize that "minority quorum" might not be the right term, at least not in how it's defined [elsewhere](https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels). What we really want the function to return is "the maximum number of tolerated failures, given a number of total voters" — the `f` in `n=2f+1`. So many `maxToleratedFailures` is a better name. What do you think?
</blockquote></details>

I like it, changed. 
___
*[pkg/sql/region_util.go, line 214 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSPSzB0C60syReZw2oa:-MSPn9wd9V965h77semB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40b71b10d596cd2e7b0f985e2dbb81c95f564c7c/pkg/sql/region_util.go#L214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: in a few of these comments, you describe the region failure tolerance behavior first, but then in all of your switch statements, you handle the zone failure tolerance first. Consider switching the comments around.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 813 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSJgned2cbhkWEncK_K:-MSPnBes8FDyzXjyGh54:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b222069fb85ff01042998d3674951bb126347a7b/pkg/sql/logictest/testdata/logic_test/multiregion#L813)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That SGTM.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2021-02-01 02:12 UTC, otan approved these changes
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)



<!-- Sent from Reviewable.io -->

2021-02-01 15:07 UTC, ajstorm requested changes
+1 on exciting!

Left a few comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-:-MST7Kgo8qVBK_a0Hk8v:b-34ki2g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfPxn3Ao2XAOdopwM:-MSSfPxn3Ao2XAOdopwN:b-zhz54) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L58)):*
> ```
>                               num_voters = 3,
>                               constraints = '{+region=ap-southeast-2: 1, +region=ca-central-1: 1, +region=us-east-1: 1}',
>                               voter_constraints = '[+region=ca-central-1]',
> ```

Should there be a `:3` at the end here?  According to the functional spec, this should be set to:

`voter_constraints = {“+region=A”: num_voters}`
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfyXb16Px94GjYr5O:-MSSfyXb16Px94GjYr5P:biltpzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L59)):*
> ```
>                               constraints = '{+region=ap-southeast-2: 1, +region=ca-central-1: 1, +region=us-east-1: 1}',
>                               voter_constraints = '[+region=ca-central-1]',
>                               lease_preferences = '[[+region=ca-central-1]]'
> ```

Nit: I know that you didn't modify this part, but looking at it, I'm wondering if the double `[[]]` is intentional.  Thoughts?
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSkiSa2VX9gHLAu5t0:-MSSkiSa2VX9gHLAu5t1:b-uejv3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L257)):*
> ```
>               num_voters = 3,
>               constraints = '{+region=ap-southeast-2: 1, +region=ca-central-1: 1, +region=us-east-1: 1}',
>               voter_constraints = '[+region=ap-southeast-2]',
> ```

There's a discrepancy here with the functional spec, which says that voter constraints and lease preferences are "Not specified at the table level for GLOBAL tables. Those tables will inherit these fields from the database’s PRIMARY REGION."

Is this difference intentional?  If so, can we update the Function Specification?

BTW, if this was intentional, it will have some implications elsewhere namely, when we change the PRIMARY REGION of a database, we'll have to go through all of the GLOBAL tables and update their zone configs, something we don't do today.
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 344 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSm83A5EvFSSrv5tmv:-MSSm83B9sQr1ffyvJeB:b-nz3gk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L344)):*
> ```
>                                            num_voters = 3,
>                                            constraints = '{+region=ap-southeast-2: 1, +region=ca-central-1: 1, +region=us-east-1: 1}',
>                                            voter_constraints = '[+region=ap-southeast-2]',
> ```

Same comment as above.  I was. under the impression that for REGIONAL BY TABLE tables, we'd inherit the zone configuration from the database.  I know that you didn't change that aspect with this PR, but we put in these placeholders (which we knew weren't 100% accurate) on the hope that we'd clean them up when your changes were complete.  Now that your changes are in, we should have the full discussion.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 429 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSoT-39zAQ01uD1HN4:-MSSoT-39zAQ01uD1HN5:b-l6w817) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L429)):*
> ```
>                                                                    num_replicas = 5,
>                                                                    num_voters = 5,
>                                                                    constraints = '{+region=ap-southeast-2: 1, +region=ca-central-1: 1, +region=us-east-1: 1}',
> ```

Why are we showing the constraints here, when we don't show it above for `SELECT create_statement FROM [SHOW CREATE TABLE regional_by_row_table]`?  Will this cause an issue with roundtriping? 
___
*[pkg/sql/region_util.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStM5E1wsdOPX_R_Ka:-MSStM5F7PEk3ijRqBFP:bleyv0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L101)):*
> ```Go
> // is constrained to each region defined within the given `regionConfig` and
> // some voting replicas are constrained to the primary region of the database
> // depending on its prescribed failure tolerance setting.
> ```

Nit: To be more consistent here, can we say "survivability goal" instead of "failure tolerance setting"?
___
*[pkg/sql/region_util.go, line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStVs06xNsCSATKFJZ:-MSStVs06xNsCSATKFJ_:b-yrg2mn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L104)):*
> ```Go
> //
> // For instance, for a database with 4 regions: A (primary), B, C, D and region
> // failure tolerance. This method will generate a ZoneConfig object representing
> ```

Nit: Can we use survivability here too?
___
*[pkg/sql/region_util.go, line 105 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStlc-4Lw0hlxCbOwj:-MSStlc-4Lw0hlxCbOwk:b-qcxakd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L105)):*
> ```Go
> // For instance, for a database with 4 regions: A (primary), B, C, D and region
> // failure tolerance. This method will generate a ZoneConfig object representing
> // the following attributes:
> ```

I like this description a lot!  What might really allow this to shine though, is a bit more description as to why we're setting each of these the way we are.  I personally find these settings difficult to quickly understand, so the more commentary we have here, the better it will be for future readers of this code.
___
*[pkg/sql/region_util.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSvIIL7qCR65Uy3WN0:-MSSvIIM4G2g8Nu_J2ma:bkhc3ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L140)):*
> ```Go
> 
> // zoneConfigForMultiRegionPartition generates a ZoneConfig stub for a partition
> // that belongs to a (regional by row) table in a multi-region database.
> ```

Super Nit: I'd remove "regional by row" from the parentheses.  It's an important part of this sentence, and not something that can be easily skipped over without losing out on the meaning of the sentence.  Your call though.
___
*[pkg/sql/region_util.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSwZ0_CYR6-PsETgtS:-MSSwZ0_CYR6-PsETgtT:b-ipb92n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L181)):*
> ```Go
> ) (numVoters, numReplicas int32) {
> 	const numVotersForZoneSurvival = 3
> 	// Under region failure tolerance, we us [...]

2021-02-01 16:21 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfPxn3Ao2XAOdopwM:-MST9RyQBp5q5P46IYFl:b-r9fsod) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L58)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Should there be a `:3` at the end here?  According to the functional spec, this should be set to:

`voter_constraints = {“+region=A”: num_voters}`
</blockquote></details>

If we state the constraint as is, without the number of replicas, it applies to all replicas. See: https://www.cockroachlabs.com/docs/v20.2/configure-replication-zones#scope-of-constraints
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfyXb16Px94GjYr5O:-MSTANo83AG2hJvbZoaE:b-3f7nok) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L59)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: I know that you didn't modify this part, but looking at it, I'm wondering if the double `[[]]` is intentional.  Thoughts?
</blockquote></details>

Yup, it's the unfortunate syntax for lease_preferences. See `lease_preferences` in the table here: https://www.cockroachlabs.com/docs/v20.2/configure-replication-zones
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSkiSa2VX9gHLAu5t0:-MSTAszT16Us72jF8rKs:bzalsyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L257)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

There's a discrepancy here with the functional spec, which says that voter constraints and lease preferences are "Not specified at the table level for GLOBAL tables. Those tables will inherit these fields from the database’s PRIMARY REGION."

Is this difference intentional?  If so, can we update the Function Specification?

BTW, if this was intentional, it will have some implications elsewhere namely, when we change the PRIMARY REGION of a database, we'll have to go through all of the GLOBAL tables and update their zone configs, something we don't do today.
</blockquote></details>

It's not a global table at this point in the test. See the line above changing it to a `REGIONAL BY TABLE` table. For posterity's sake, I changed the table name a bit so its less confusing. 
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 344 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSm83A5EvFSSrv5tmv:-MSTDeG47phn2XSlbMPb:b-cnp7s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L344)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Same comment as above.  I was. under the impression that for REGIONAL BY TABLE tables, we'd inherit the zone configuration from the database.  I know that you didn't change that aspect with this PR, but we put in these placeholders (which we knew weren't 100% accurate) on the hope that we'd clean them up when your changes were complete.  Now that your changes are in, we should have the full discussion.
</blockquote></details>

REGIONAL BY TABLE tables were always intended to define their own `voter_constraints` and `lease_preferences` iff they were homed in a different region than the primary region. Did you mean to say GLOBAL in your comment here? Cause global tables are inheriting a lot of fiends from the database's zone config (except, ofcourse, the `global_reads` attribute).
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 429 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSoT-39zAQ01uD1HN4:-MSTEJF60k9nuP7smRTf:b-5azk6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L429)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Why are we showing the constraints here, when we don't show it above for `SELECT create_statement FROM [SHOW CREATE TABLE regional_by_row_table]`?  Will this cause an issue with roundtriping? 
</blockquote></details>

Well these two statements are referring to different things, right? `SHOW CREATE TABLE` is the statement that created the table, `SHOW ZONE CONFIGURATION FOR...` is the statement that shows you the zone config for the object. The former round-trips. The latter isn't really supposed to round-trip as it also shows you the set of fields that are inherited (rather than the ones that are just set at this object's level).
___
*[pkg/sql/region_util.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStM5E1wsdOPX_R_Ka:-MSTFHsuBF3xMozIUdrE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L101)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: To be more consistent here, can we say "survivability goal" instead of "failure tolerance setting"?
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStVs06xNsCSATKFJZ:-MSTFIlxCOoOCPnOcez0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L104)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Can we use survivability here too?
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 105 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStlc-4Lw0hlxCbOwj:-MSTFJa_3xNhyC4zrJyi:b-r5c96f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L105)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I like this description a lot!  What might really allow this to shine though, is a bit more description as to why we're setting each of these the way we are.  I personally find these settings difficult to quickly understand, so the more commentary we have here, the better it will be for future readers of this code.
</blockquote></details>

I added a bit of commentary next to the part that constrains 1 replica per region and a sentence directing readers to `synthesizeVoterConstraints()` for the `voter_constraints` bit.
___
*[pkg/sql/region_util.go, line 140 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSvIIL7qCR65Uy3WN0:-MSTGYp77cJswepO1wmT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L140)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Super Nit: I'd remove "regional by row" from the parentheses.  It's an important part of this sentence, and not something that can be easily skipped over without losing out on the meaning of the sentence.  Your call though.
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 181 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSwZ0_CYR6-PsETgtS:-MSTGdoV3zzLv8QQSgPD:b499q7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util [...]

2021-02-01 19:09 UTC, ajstorm approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfyXb16Px94GjYr5O:-MSTvDNnADutBHQnL6LB:bhrmsax) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L59)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Yup, it's the unfortunate syntax for lease_preferences. See `lease_preferences` in the table here: https://www.cockroachlabs.com/docs/v20.2/configure-replication-zones
</blockquote></details>

I'll have to take your word for it.  That link doesn't seem to have an example where there's only one region in teh lease_preferences.
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSkiSa2VX9gHLAu5t0:-MSTvYLrC3RiLWtMOl8l:b-ttnboo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L257)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

It's not a global table at this point in the test. See the line above changing it to a `REGIONAL BY TABLE` table. For posterity's sake, I changed the table name a bit so its less confusing. 
</blockquote></details>

Ah, I didn't look high enough up.  Looks good.
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 344 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSm83A5EvFSSrv5tmv:-MSTvqEiAy2XgP1exldO:b-7ss89n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L344)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

REGIONAL BY TABLE tables were always intended to define their own `voter_constraints` and `lease_preferences` iff they were homed in a different region than the primary region. Did you mean to say GLOBAL in your comment here? Cause global tables are inheriting a lot of fiends from the database's zone config (except, ofcourse, the `global_reads` attribute).
</blockquote></details>

Agreed, this looks good.  I was mistaken with my comment.  I meant `REGIONAL BY TABLE`, but forgot that those not in the `PRIMARY REGION` would need their own zone config.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 429 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSoT-39zAQ01uD1HN4:-MSTwDc1741ZJASesj0q:bnt2z5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L429)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Well these two statements are referring to different things, right? `SHOW CREATE TABLE` is the statement that created the table, `SHOW ZONE CONFIGURATION FOR...` is the statement that shows you the zone config for the object. The former round-trips. The latter isn't really supposed to round-trip as it also shows you the set of fields that are inherited (rather than the ones that are just set at this object's level).
</blockquote></details>

Interesting, TIL.  I was under the impression that both of them were intended to round-trip.
___
*[pkg/sql/region_util.go, line 105 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSStlc-4Lw0hlxCbOwj:-MSTwcqk4wX4DQU3uXXT:b-6mhyx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L105)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

I added a bit of commentary next to the part that constrains 1 replica per region and a sentence directing readers to `synthesizeVoterConstraints()` for the `voter_constraints` bit.
</blockquote></details>

Great, thanks!
___
*[pkg/sql/region_util.go, line 186 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSx42J7-CtXGpc-wun:-MSTwrTf-CuQH3oB4fcw:b-vs1pr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L186)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Added a blurb talking about the current behavior. Created https://github.com/cockroachdb/cockroach/issues/59650 to track.
</blockquote></details>

Looks good.
___
*[pkg/sql/region_util.go, line 198 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSzLHU07xYtf59Dcmh:-MSTxA9eAHClKfqbHC0U:b-7rijo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L198)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

> We place the maximum concurrent replicas that can fail before a range outage in the home region, and ensure that there's at least one replica in all other regions.

Added.

Changed the name to `maxFailuresBeforeUnavailability`. LMK if you dislike.

The very first point I'm not sure about. I added a pointer to `synthesizeVoterConstraints()` where this is explained properly. 
</blockquote></details>

Looks good.  On the pointer fixes my first part.
___
*[pkg/sql/region_util.go, line 221 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST0Rw65YMn020KqRPg:-MSTxZUcEzxvO5s4kq5h:b-3ay65g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L221)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Would you mind clarifying where else you'd like this to be added?
</blockquote></details>

I think we're good now.  The sprinkling you did above helps a lot.
___
*[pkg/sql/region_util.go, line 231 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST1iJe-TGgvb0QszCF:-MSTxs7e0DsfbtGWiq_t:b-jaohqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L231)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The `NumReplicas` attribute in a `ConstraintsConjunction` defines "the number of replicas that the constraint must be satisfied by". This is different from the `NumReplicas` attribute of a `ZoneConfig`. The latter is the one we're inheriting or not. For this one: 

```
// We don't specify `NumReplicas` here to indicate that we want _all
// voting replicas to be constrained to this one region.
```
</blockquote></details>

Ah, my mistake.  I follow it now.
___
*[pkg/sql/region_util.go, line 331 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST2XR7BnAVvEOCXRod:-MSTypSm1t1HGi4hieK0:b-n1mva2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L331)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

They'll always be over-written by this logic, regardless of what `sql_safe_updates` is set to. The `sql_safe_updates` discussion was about letting the _users_ override these values. Oliver has a TODO for this here: https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L385
</blockquote></details>

The issue was supposed to go both ways.  We also want to prevent overwriting in the system if the user has overridden at any point in the past (unless `sql_safe_updates` is `true`).
 [...]

2021-02-01 19:40 UTC, aayushshah15 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfyXb16Px94GjYr5O:-MSU-VS94NOWiUSAW44p:b-5wrv4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L59)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I'll have to take your word for it.  That link doesn't seem to have an example where there's only one region in teh lease_preferences.
</blockquote></details>

The thing to note is that `lease_preferences` lets you specify an ordered list of preferences, each of those individual preferences is a `Constraint` which is enclosed in those inner `[ ]`. It looks weird in our case because we only have one lease preference. 

Is it hard-to-read / unergonomic? Absolutely. 
___
*[pkg/sql/region_util.go, line 331 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST2XR7BnAVvEOCXRod:-MSU05MzE2eLakGviw6h:bsrk1wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L331)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

The issue was supposed to go both ways.  We also want to prevent overwriting in the system if the user has overridden at any point in the past (unless `sql_safe_updates` is `true`).
</blockquote></details>

This is yours/@otan's call and outside the scope of this PR, but I would think that we wouldn't want to do that. Particularly not based off of `sql_safe_updates` as that's a pretty coarse setting which could be enabled for various other reasons (like a completely unrelated `DROP DATABASE CASCADE`). 

Additionally, imo _not_ overwriting the zone configs when these multi-region DDL statements are issued partly defeats the purpose of adding/removing regions. My understanding was that the reason we need to guard this behind something like `sql_safe_updates` is because _our_ statements can over-write the user's changes and they need to "sign off" on that, but I may not have kept up-to-date on the latest discussions on this subject. 

What do you think?
___
*[pkg/sql/region_util.go, line 339 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST36fD2n0WGAumwyo0:-MSU0_gw1o7MdTKaeChy:bt8zmvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L339)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is that override of `num_replicas` going to happen here?  We only seem to be setting `num_voters` (unless I'm missing something).
</blockquote></details>

Nope, that's at the database level zone config, see `zoneConfigForMultiRegionDatabase`.


<!-- Sent from Reviewable.io -->

2021-02-01 19:48 UTC, aayushshah15 commented
I'm going to merge this the remaining `sql_safe_updates` discussion is orthogonal to the PR. 

Thanks for the detailed reviews @otan, @ajstorm and @nvanbenschoten!

bors r+

2021-02-01 21:00 UTC, merged

2021-02-02 01:21 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @ajstorm, @andreimatei, @nvanbenschoten, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MSSfyXb16Px94GjYr5O:-MSVHQUU2aNlQ9LFUrWo:b-x2xgdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L59)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

The thing to note is that `lease_preferences` lets you specify an ordered list of preferences, each of those individual preferences is a `Constraint` which is enclosed in those inner `[ ]`. It looks weird in our case because we only have one lease preference. 

Is it hard-to-read / unergonomic? Absolutely. 
</blockquote></details>

Yeah, what was throwing me off was that when you go down to one constraint, the `[ ]` is still required.  I'd think that it would be optional at that point.  
___
*[pkg/sql/region_util.go, line 331 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59591#-MST2XR7BnAVvEOCXRod:-MSVI_ZP9kiMqscspjbj:b-3f5omj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b252a253c0e6dd666a690319b3e5851cab50dcd/pkg/sql/region_util.go#L331)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

This is yours/@otan's call and outside the scope of this PR, but I would think that we wouldn't want to do that. Particularly not based off of `sql_safe_updates` as that's a pretty coarse setting which could be enabled for various other reasons (like a completely unrelated `DROP DATABASE CASCADE`). 

Additionally, imo _not_ overwriting the zone configs when these multi-region DDL statements are issued partly defeats the purpose of adding/removing regions. My understanding was that the reason we need to guard this behind something like `sql_safe_updates` is because _our_ statements can over-write the user's changes and they need to "sign off" on that, but I may not have kept up-to-date on the latest discussions on this subject. 

What do you think?
</blockquote></details>

Sorry, I might not have been clear above.  There are two things we want to guard against with `sql_safe_updates`:

1) A user updates a zone configuration and a multi-region DDL statement will overwrite that change.
2) A multi-region zone configuration is in affect and a user wants to update some part of that zone configuration.

In the second case, the user is potentially going to mess up the multi-region configuration, so we want to let them know about that.  In the first case, we're potentially going to overwrite something that is important to the user, so we want to at least let them know about it before we do something bad (from their perspective).

Important to note is that in the first case, the plan isn't to not overwrite the zone config, but instead, fail the DDL statement with an appropriate error message.  I completely agree with you that we don't want an invalid zone configuration in place _after_ we've completed a multi-region DDL statement.


<!-- Sent from Reviewable.io -->

2021-02-02 01:28 UTC, aayushshah15 commented
> Important to note is that in the first case, the plan isn't to not overwrite the zone config, but instead, fail the DDL statement with an appropriate error message

ah I totally misunderstood, makes sense. Thanks for explaining.