sql/catalog/lease: remove limitation regarding dropped descriptors
cockroachdb/cockroach pull request #59606
Opened 2021-01-30 02:29 UTC by ajwerner

Prior to this change, there was an awkward limitation in the lease manager when
requests came in at a timestamp that precedes the timestamp at which a table
was dropped. There were some special cases in the descs.Collection for tables
however, they were not there for databases or schemas. This generalizes the
solution and removes the limitation.

The interaction is so subtle, I don't know that it warrants a release note.

Release note: None

2021-01-30 02:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59606)
<!-- Reviewable:end -->

2021-01-31 01:02 UTC, ajwerner commented
This has a major problem which is that the fallback in these cases lead to a properly classified error and now can lead `ErrDescriptorNotFound` which is :/

2021-02-01 20:06 UTC, ajwerner commented
The major problem has been downgraded to a minor test failure.

2021-02-01 21:56 UTC, postamar requested changes
LGTM but for a few small things.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-:-MSU_viV0g035mvnc0M0:b-xpaik4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/catalog/lease/lease.go, line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUYiHI978JapmP5cF9:-MSUYiHJCLkLGkKrcYPY:bqos6mo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease.go#L913)):*
> ```Go
> 				Descriptor: e.desc,
> 				expiration: e.desc.GetModificationTime(),
> 			}, true); err != nil {
> ```

nit: missing `/* takenOffline */`
___
*[pkg/sql/catalog/lease/lease_test.go, line 2540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUYLukBq2N69UxcOc7:-MSUYLukBq2N69UxcOc8:b-ulf3ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease_test.go#L2540)):*
> ```Go
> 	var descID atomic.Value
> 	descID.Store(descpb.ID(0))
> 	var ts hlc.Timestamp
> ```

CI didn't run so we can't tell for sure but I suspect that `testrace` will complain about races for `ts` if you don't wrap it in an atomic value.
___
*[pkg/sql/catalog/lease/lease_test.go, line 2585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUXyTrCc6-I-hYJpAD:-MSUXyTrCc6-I-hYJpAE:bhsgj8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease_test.go#L2585)):*
> ```Go
> 	}
> 	var tsStr string
> 	tdb.QueryRow(t, `SELECT cluster_logical_timestamp()`).Scan(&tsStr)
> ```

As discussed on slack, don't forget to remove this.


<!-- Sent from Reviewable.io -->

2021-02-01 21:58 UTC, postamar commented
Huh not sure why Reviewable marked this a "changes requested" instead of ✅ sorry about that.

2021-02-01 21:59 UTC, postamar approved these changes

2021-02-09 21:43 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59606)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @postamar)

___
*[pkg/sql/catalog/lease/lease.go, line 913 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUYiHI978JapmP5cF9:-MT7agaB70DD-2HxcTmc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease.go#L913)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: missing `/* takenOffline */`
</blockquote></details>

Done.
___
*[pkg/sql/catalog/lease/lease_test.go, line 2540 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUYLukBq2N69UxcOc7:-MT7alAMBlpT0WL7SjyC:b-24tj8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease_test.go#L2540)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

CI didn't run so we can't tell for sure but I suspect that `testrace` will complain about races for `ts` if you don't wrap it in an atomic value.
</blockquote></details>

Moved it instead to be sent on the channel. 
___
*[pkg/sql/catalog/lease/lease_test.go, line 2585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59606#-MSUXyTrCc6-I-hYJpAD:-MT7bRoFC7jhf8QayCFC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb33c2f53254fe6f11266739976819c931f7f128/pkg/sql/catalog/lease/lease_test.go#L2585)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

As discussed on slack, don't forget to remove this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 03:20 UTC, ajwerner commented
TFTR!

bors r=postamar

2021-02-10 05:30 UTC, merged