storage: limit RevertRange batches to 32mb
cockroachdb/cockroach pull request #59716
Opened 2021-02-02 19:48 UTC by dt

The existing limit in key-count/span-count can produce batches in excess of 64mb,
if, for example, they have very large keys. These batches then are rejected for
exceeding the raft command size limit.

This adds an aditional hard-coded limit of 32mb on the write batch to which keys
or spans to clear are added (if the command is executed against a non-Batch the
limit is ignored). The size of the batch is re-checked once every 32 keys.

Release note (bug fix): avoid creating batches that exceed the raft command limit (64mb)  when reverting ranges that contain very large keys.

2021-02-02 19:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59716)
<!-- Reviewable:end -->

2021-02-03 22:16 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dt)

___
*[pkg/storage/mvcc.go, line 2126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MSdt_GV2hG9D6Uj5IIX:-MSdt_GV2hG9D6Uj5IIY:bj493nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e017b30c5fe518c3d11d0338180b58e4556ce8e/pkg/storage/mvcc.go#L2126)):*
> ```Go
> 	}
> 
> 	const maxBatchByteSize, recheckBatchSizeEvery = 32 << 20, 32
> ```

It is confusing that we already have a `maxBatchSize` parameter and that is set to `MaxSpanRequestKeys`.
I thought `MaxSpanRequestKeys` was to bound the amount of data retrieved for a read. If that is correct, why is it being used here?
Was its purpose to limit the amount of read work or write work? Given that we count a `ClearRange` as 1, I guess it was to limit the amount of write work. Can we unify that with what is being introduced here?
___
*[pkg/storage/mvcc.go, line 2198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MSdutwF6n7DL4zvlQwJ:-MSdutwF6n7DL4zvlQwK:b-glsahc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e017b30c5fe518c3d11d0338180b58e4556ce8e/pkg/storage/mvcc.go#L2198)):*
> ```Go
> 					break
> 				}
> 				recheckBatchSize = 0
> ```

We only write to the `Batch` in `flushClearedKeys`, so if there are 63 K-V pairs that together exceed the 64MB limit, and then we find a non-matching key and call flush, we will not notice that we have exceeded the batch size. I think we could approximate an upper bound on the size of the batch by just adding the key lengths. I think it would be good to push that approximation into `clearMatchingKey` since it knows when it is transitioning from individual clears to clear range.

Even better would be to lift that code out into a `clearBatcher` struct with functions `flushClearedRun`, `clear`, `getCountAndApproxSize` that can be used to cleanly separate the iteration from the write batching. And that would unify this if-block with the preceding one since both are doing the same thing wrt constructing a resume span.
 


<!-- Sent from Reviewable.io -->

2021-02-04 23:19 UTC, andreimatei reviewed
The thing looks good to me, but I'm not the right person to look. Seems like Sumeer's got you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-:-MSjKn77DcyWtP7r3O8z:b1hx96x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)



<!-- Sent from Reviewable.io -->

2021-02-17 03:01 UTC, dt reviewed
Cleaned up a bit and added some tests. RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-:-MThvo4n48mD-q9JqdhG:bg6uhfc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MSdt_GV2hG9D6Uj5IIX:-MTht4nJ2a2F8X1aC14I:b864clw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e017b30c5fe518c3d11d0338180b58e4556ce8e/pkg/storage/mvcc.go#L2126)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is confusing that we already have a `maxBatchSize` parameter and that is set to `MaxSpanRequestKeys`.
I thought `MaxSpanRequestKeys` was to bound the amount of data retrieved for a read. If that is correct, why is it being used here?
Was its purpose to limit the amount of read work or write work? Given that we count a `ClearRange` as 1, I guess it was to limit the amount of write work. Can we unify that with what is being introduced here?

</blockquote></details>

The count is indeed limiting write work, and more generally just limiting work, so that a caller could paginate, persist progress checkpoints, etc.

But the count, while likely a good proxy for how long the request will run, isn't on its own enough to avoid running afoul of the max command size in the fact of giant keys, so we need both it seems.
___
*[pkg/storage/mvcc.go, line 2198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MSdutwF6n7DL4zvlQwJ:-MThtV2l7BGoMPZwQ_Yq:b6qbqk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e017b30c5fe518c3d11d0338180b58e4556ce8e/pkg/storage/mvcc.go#L2198)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We only write to the `Batch` in `flushClearedKeys`, so if there are 63 K-V pairs that together exceed the 64MB limit, and then we find a non-matching key and call flush, we will not notice that we have exceeded the batch size. I think we could approximate an upper bound on the size of the batch by just adding the key lengths. I think it would be good to push that approximation into `clearMatchingKey` since it knows when it is transitioning from individual clears to clear range.

Even better would be to lift that code out into a `clearBatcher` struct with functions `flushClearedRun`, `clear`, `getCountAndApproxSize` that can be used to cleanly separate the iteration from the write batching. And that would unify this if-block with the preceding one since both are doing the same thing wrt constructing a resume span.
 
</blockquote></details>

Since we have an eye to backporting I didn't want to go too far into refactoring and pulling out a new helper just yet.

But I think I fixed the hypothetical 63-giant-keys case, by opting to flush the buffered keys as a clear-range rather than individual even if we didn't reach the 64 key mark that would usually motivate that, but instead if, when we go to flush them one-by-one, their encoded size is too large.

While I was at it, I switched to tracking the size as sum of bytes added, to avoid the type-sniff and intermittent batch size checks, and made the size limit an argument. While I don't want to make it a request param in this change (again, for backport), making it a function arg  at least makes it easier to test.


<!-- Sent from Reviewable.io -->

2021-02-17 22:09 UTC, sumeerbhola requested changes
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2077 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTm-4Kc4jjcC8o2emTg:-MTm-4Kc4jjcC8o2emTh:b-l6iyry) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe6752e3e908c4ca4f237100de9c89d45951d66/pkg/storage/mvcc.go#L2077)):*
> ```Go
> // batch that is too large -- in number of bytes -- for raft to replicate if the
> // keys are very large. So if the total length of the keys or key spans cleared
> // exceeds maxBatchByteSize it will also stop and return a reusme span.
> ```

resume
___
*[pkg/storage/mvcc.go, line 2171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTm0g7ADavSi7kFdfEc:-MTm0g7ADavSi7kFdfEd:bxodwa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe6752e3e908c4ca4f237100de9c89d45951d66/pkg/storage/mvcc.go#L2171)):*
> ```Go
> 						}
> 					}
> 					batchByteSize += encodedBufSize
> ```

shouldn't this be outside the for loop since `encodedBufSize` already reflects all the keys? If yes, can we get some test coverage so we don't have an inadvertent performance regression.


<!-- Sent from Reviewable.io -->

2021-02-18 14:47 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2077 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTm-4Kc4jjcC8o2emTg:-MTpauvzDOwA99R4abYj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe6752e3e908c4ca4f237100de9c89d45951d66/pkg/storage/mvcc.go#L2077)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

resume
</blockquote></details>

Done.
___
*[pkg/storage/mvcc.go, line 2171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTm0g7ADavSi7kFdfEc:-MTpa4B39WxinPr8d9g5:b3wb9gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe6752e3e908c4ca4f237100de9c89d45951d66/pkg/storage/mvcc.go#L2171)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

shouldn't this be outside the for loop since `encodedBufSize` already reflects all the keys? If yes, can we get some test coverage so we don't have an inadvertent performance regression.
</blockquote></details>

yep, indeed. The random test actually already has enough data to catch it, so just needed to add counting on how many resumes it did. 


<!-- Sent from Reviewable.io -->

2021-02-18 17:11 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-:-MTq6sLS8tB23F2-Lmx9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @sumeerbhola)

___
*[pkg/storage/mvcc_test.go, line 2403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTq64vB3dnGEBNwYeEB:-MTq64vB3dnGEBNwYeEC:bircfk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18cfebd26b0a41d49e46167ae7dee21b4e0f777/pkg/storage/mvcc_test.go#L2403)):*
> ```Go
> 			const keyLimit = 100
> 			keyLen := int64(len(roachpb.Key(fmt.Sprintf("%05d", 1)))) + MVCCVersionTimestampSize
> 			maxAttempts := (numKVs * keyLen) / byteLimit
> ```

It's a little hard to see which limit is the bottleneck. Ideally, we should have one test case each where one of the two is the bottleneck.
And how about a `minAttempts` to ensure that things are being broken into batches.


<!-- Sent from Reviewable.io -->

2021-02-18 17:34 UTC, dt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @sumeerbhola)

___
*[pkg/storage/mvcc_test.go, line 2403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-MTq64vB3dnGEBNwYeEB:-MTqAtCO1evzMcj-4Hcn:bgt99fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e18cfebd26b0a41d49e46167ae7dee21b4e0f777/pkg/storage/mvcc_test.go#L2403)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It's a little hard to see which limit is the bottleneck. Ideally, we should have one test case each where one of the two is the bottleneck.
And how about a `minAttempts` to ensure that things are being broken into batches.
</blockquote></details>

It's a bit easier to exercise the specific limits in isolation in the small, static tests above, so added cases there.  I only used the random test for catching the over-counting because it actually had enough data to exceed the buffer-size case.


<!-- Sent from Reviewable.io -->

2021-02-18 19:05 UTC, sumeerbhola reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59716#-:-MTqX2KF7XDSKirrj1uY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-02-18 19:16 UTC, dt commented
TFTR!

bors r+

2021-02-18 23:00 UTC, merged