execstats: fix query level stats calculation
cockroachdb/cockroach pull request #59812
Opened 2021-02-04 18:43 UTC by yuzefovich

**execstats: fix query level contention time calculation**

Previously, we were using an incorrect map to calculate the contention
time.

Release note: None

**execstats: fix GetQueryLevelStats when sub- and post-queries are present**

Previously, `GetQueryLevelStats` would incorrectly calculate the query
level stats when multiple `FlowMetadata` objects are passed in. That is
the case when either sub- or post-queries are present. As a result, we
would return the query level stats only for the last FlowMetadata
object. This is now fixed by aggregating the query level stats of all
FlowMetadata objects.

However, the test is missing since I don't yet see how to do it. It is
left as a TODO.

Additionally, this commit does some cleanup - using "Flows" instead of
"Flow" for metadata to indicate that multiple flows (that are part of
the same physical plan) correspond to a single metadata object (this was
a point of confusion to me), as well as some comments wrapping.

Release note: None

2021-02-04 18:43 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59812)
<!-- Reviewable:end -->

2021-02-08 11:45 UTC, asubiotto requested changes
Re the testing, you could probably add a public testing function to `utils_test.go` that creates a FlowMetadata from specified internal maps. You could create two simple ones (e.g. single processor stats with a dummy kv time) and assert that the result is what you expect.

> Reviewed 2 of 2 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59812#-:-MT0RQGpEcPe5oAXoM5t:bykkjfk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/execstats/traceanalyzer.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59812#-MT0Qb0g7iH0XrWutW2_:-MT0Qb0h1HTFIsd8RkWq:b24mvof) ([raw file](https://github.com/cockroachdb/cockroach/blob/cafb54dc8677101cc7e8da73f8f8a6bc8f6b7085/pkg/sql/execstats/traceanalyzer.go#L113)):*
> ```Go
> 
> // aggregate updates s to include stats from other.
> func (s *QueryLevelStats) aggregate(other QueryLevelStats) {
> ```

If you rebase, I added an `Accumulate` method in a recent PR.


<!-- Sent from Reviewable.io -->

2021-02-09 19:11 UTC, yuzefovich reviewed
Added a simple unit test. I originally thought that we need to inject the stats into the trace and didn't realize we can artificially add component stats directly into the FlowsMetadata objects.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59812#-:-MT7BBAP9aVCC107xe0q:b-oid0z5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/execstats/traceanalyzer.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59812#-MT0Qb0g7iH0XrWutW2_:-MT76_clBr0RSQICnLZJ:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cafb54dc8677101cc7e8da73f8f8a6bc8f6b7085/pkg/sql/execstats/traceanalyzer.go#L113)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you rebase, I added an `Accumulate` method in a recent PR.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2021-02-10 10:40 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks!

> Reviewed 6 of 6 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59812#-:-MTAWk5H5r-G3BW4A0tc:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-02-10 15:08 UTC, yuzefovich commented
TFTR!

bors r+

2021-02-10 15:58 UTC, merged