sql: add schema_name,table_id to crdb_internal.ranges
cockroachdb/cockroach pull request #59865
Opened 2021-02-05 20:56 UTC by jordanlewis

... and crdb_internal.ranges_no_leases

This commit adds schema_name to crdb_internal.ranges and
crdb_internal.ranges_no_leases to ensure that it's possible to
disambiguate between ranges that are contained by a table with the same
name in two different user-defined schemas.

In addition, it also adds the table_id column which allows unambiguous
lookups of ranges for a given table id. This will also enable making a
virtual index on the table_id column later, which should be a nice win
for some introspection commands.

Release note (sql change): add the schema_name and table_id columns to
the crdb_internal.ranges and crdb_internal.ranges_no_leases virtual
tables.

2021-02-05 20:56 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59865)
<!-- Reviewable:end -->

2021-02-10 22:31 UTC, rafiss requested changes

2021-02-10 22:31 UTC, rafiss commented on pkg/sql/crdb_internal.go
> +					schemaName = "public"
nit: can we use the `sessiondata.PublicSchemaName` const from here?

2021-02-12 20:15 UTC, jordanlewis commented
Done!

2021-02-12 20:23 UTC, rafiss approved these changes
lgtme!

2021-02-16 19:29 UTC, rafiss commented
bors r+

2021-02-16 21:25 UTC, merged