sql: add support for dropping regions from multi-region databases (no denormalization)
cockroachdb/cockroach pull request #59989
Opened 2021-02-08 05:39 UTC by arulajmani

WIP

TODO(arul): update commit message.

Release note (sql change): ALTER DATABASE ... DROP REGION is now
implemented.

2021-02-08 05:39 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/59989)
<!-- Reviewable:end -->

2021-02-08 05:41 UTC, arulajmani commented
Creating a WIP after the conversation on #59098. This patch no longer saves the region enum ID on the locality config of REGIONAL BY TABLE table's (homed in an explicit region). Instead, it reads the regionEnumID from the database descriptor instead when accumulating dependencies. I can clean this up if we decide this is the way to go, just looking for feedback on the approach.

2021-02-09 01:15 UTC, otan reviewed
Looks good, if ajstorm approves tomorrow feel free to merge without me.

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-:-MT3LjS06vqJHJ5Y5Tbd:bm9o2y5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @arulajmani)

___
*[pkg/sql/alter_database.go, line 498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3GwuI-eBMfUGQ3Vwz:-MT3GwuI-eBMfUGQ3Vx-:bk5agvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/alter_database.go#L498)):*
> ```Go
> 	}
> 
> 	if err := addDefaultLocalityConfigToAllTables(params.ctx, params.p,
> ```

super nit: these circumstances scream one arg per line to me :P 

```
if err := addDefaultLocalityConfigToAllTables(
  params.ctx,
  params.p,
  &n.desc.Immutable,
  regionConfig.RegionEnumID,
); err != nil {
```

try it you'll never go back.
___
*[pkg/sql/multiregion_test.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3I4sU11HUdjAzZbwm:-MT3I4sU11HUdjAzZbwn:b-57niwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/multiregion_test.go#L98)):*
> ```Go
> 		t.Fatalf("expected error, found nil")
> 	}
> 	if !testutils.IsError(err, `"us-east2" has not been added to the database`) {
> ```

we should probably make a TODO to make it more clear that it is being dropped, rather than not added, if that's feasible.
___
*[pkg/sql/type_change.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3ISNl7nFD0T-mJXFe:-MT3ISNl7nFD0T-mJXFf:b56gg7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L322)):*
> ```Go
> // as dictated by shouldRemove.
> func filterEnumMembers(
> 	typeDesc *typedesc.Mutable, shouldRemove func(member *descpb.TypeDescriptor_EnumMember) bool,
> ```

this function is named a little scarily in that it modifies enums in place.
maybe `applyFilterForEnumMembers`?
___
*[pkg/sql/type_change.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KxtK6WGXyh_OJmjP:-MT3KxtK6WGXyh_OJmjQ:b-4t870o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L461)):*
> ```Go
> 		// constructed and there's nothing to execute. The validation for them is
> 		// handled as a special case below.
> 		if !firstClause {
> ```

it was hard for me to piece together why we needed this if statement here with the var name.
maybe rename `firstClause` to `hasEnumColumn` or something
___
*[pkg/sql/type_change.go, line 490 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3Kn7VEpiKpOkaKB-6:-MT3Kn7VEpiKpOkaKB-7:b-ei8dd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L490)):*
> ```Go
> 
> 		// If the type descriptor is a multi-region enum and the table descriptor
> 		// belongs to a regional (by table) table, we disallow dropping the region
> ```

nit: REGIONAL BY TABLE table
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3Itye9HxapqC8HQ3l:-MT3Itye9HxapqC8HQ3m:b-lz70rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant#L13)):*
> ```
> 0  role_members
> 0  role_options
> 0  system
> ```

o_o why did this change
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 834 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3J-Rw5ikb2RoScw1l:-MT3J-Rw5ikb2RoScw1m:bepprr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L834)):*
> ```
> CREATE DATABASE drop_region_db PRIMARY REGION "ca-central-1" REGIONS "ap-southeast-2", "us-east-1"
> 
> statement error pq: cannot drop region "ca-central-1"
> ```

i usually omit pq: out from these
also seems like we can be more descriptive about why we cannot drop here.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 874 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KOTG6URDmWzXKyrX:-MT3KOTH4964aeM0sHoI:b-942mw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L874)):*
> ```
> 
> statement ok
> ALTER DATABASE drop_region_db DROP REGION "ap-southeast-2"
> ```

is there a test that drops the final region?
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 942 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3K5XpA86_Hw-tMbqQ:-MT3K5XpA86_Hw-tMbqR:b-dxkz11) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L942)):*
> ```
> 
> statement error pq: could not remove enum value "us-east-1" as it is being used by table "east"
> ALTER DATABASE drop_regions_alter_patterns  DROP REGION "us-east-1"
> ```

nit: this and below have extra spacing before DROP


<!-- Sent from Reviewable.io -->

2021-02-09 02:01 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @otan)

___
*[pkg/sql/alter_database.go, line 498 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3GwuI-eBMfUGQ3Vwz:-MT3OcG7AIaKG8Ng-32Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/alter_database.go#L498)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

super nit: these circumstances scream one arg per line to me :P 

```
if err := addDefaultLocalityConfigToAllTables(
  params.ctx,
  params.p,
  &n.desc.Immutable,
  regionConfig.RegionEnumID,
); err != nil {
```

try it you'll never go back.
</blockquote></details>

Done.
___
*[pkg/sql/multiregion_test.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3I4sU11HUdjAzZbwm:-MT3Ogo33fsme7fWje9h:b-yxeesb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/multiregion_test.go#L98)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we should probably make a TODO to make it more clear that it is being dropped, rather than not added, if that's feasible.
</blockquote></details>

I think this will fall out quite well as a result of removing region names from the database descriptor, as trying to double drop a type descriptor value returns a decently worded error message. Single source of truth FTW :D 
___
*[pkg/sql/type_change.go, line 322 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3ISNl7nFD0T-mJXFe:-MT3PKnY6vvQXLvaKgCp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L322)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this function is named a little scarily in that it modifies enums in place.
maybe `applyFilterForEnumMembers`?
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KxtK6WGXyh_OJmjP:-MT3S49a7Ef9eVHw_bIa:b6se43k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L461)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it was hard for me to piece together why we needed this if statement here with the var name.
maybe rename `firstClause` to `hasEnumColumn` or something
</blockquote></details>

That's probably because I'm overloading `firstClause` here -- the initial intention was to use it to construct the validation query. Does the comment not help? I reworded it.
___
*[pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3Itye9HxapqC8HQ3l:-MT3Pxzs44ktxRXtP3I_:b-qxm0yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant#L13)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

o_o why did this change
</blockquote></details>

my guess is we needed to lease the `system` type descriptor because we now need to pass the db desc to `GetAllReferencedTypes`, though I'm not sure on which code path. 
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 834 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3J-Rw5ikb2RoScw1l:-MT3QOl74OxuEVOYUshZ:b-ye8d8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L834)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i usually omit pq: out from these
also seems like we can be more descriptive about why we cannot drop here.
</blockquote></details>

It comes with a hint, that isn't here lol
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 874 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KOTG6URDmWzXKyrX:-MT3QZAZ4-1MtVKjmS_i:b9o9oz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L874)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

is there a test that drops the final region?
</blockquote></details>

Not yet, because we don't support dropping a primary region in this patch -- that's forthcoming. I forgot to copy pasta that blob from my previous commit message, so I'll do that. 


<!-- Sent from Reviewable.io -->

2021-02-09 02:33 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/type_change.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KxtK6WGXyh_OJmjP:-MT3c5GEDpSgM43x8Jf_:by41gjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L461)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

That's probably because I'm overloading `firstClause` here -- the initial intention was to use it to construct the validation query. Does the comment not help? I reworded it.
</blockquote></details>

I'd probably get rid of the NB, i think the var name changing to `hasValidationToDo` or something to make this clear.
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 834 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3J-Rw5ikb2RoScw1l:-MT3ced10oOD46cjcIBK:byzxhv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L834)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

It comes with a hint, that isn't here lol
</blockquote></details>

ah. you can include if you did `\nHINT: blah` if you wanted to ;)


<!-- Sent from Reviewable.io -->

2021-02-09 13:54 UTC, ajstorm requested changes
I like the changes, and it's good to see this convergin' towards mergin'.

Some nits on the commit record:

-  "I call it implicit because " - I'd avoid using "I" in the commit record.  Can be changed to "It is referred to as implicit because..."
- "cofnizant" -> "cognizant"?
- "The semntics around REGIONAL BY TABLE tables and GLOBAL tables are also handled appropriately." - Do you mean the semantics around altering between the two?

Also, the commit record above is very helpful in understanding the code.  Does it make sense to add this to the code somewhere (perhaps where we define the multi-region enum?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-:-MT5oGx4DdcdbsmvlrP8:bhql7a3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5qSpL6_JKuv4HkZcw:-MT5qSpL6_JKuv4HkZcx:b1s8x0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L275)):*
> ```Go
> 	// To drop the region, the user has to have CREATEDB privileges,
> 	// or be an admin user.
> 	if err := p.CheckRoleOption(ctx, roleoption.CREATEDB); err != nil {
> ```

More for my own info, but why the check here, as opposed to in `startExec()`?  That's where we check it for the other alters.
___
*[pkg/sql/alter_database.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5qsq0AOKmmRm2PidS:-MT5qsq0AOKmmRm2PidT:b-c0ppy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L287)):*
> ```Go
> 			errors.Newf("cannot drop region %q", dbDesc.RegionConfig.PrimaryRegion),
> 			"You must designate another region as the primary region or remove all "+
> 				"other regions before attempting to drop %q", n.Region,
> ```

Nit: "...before attempting to drop _region_ %q"?
___
*[pkg/sql/alter_database.go, line 306 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5rG9e0N78X3s55UTf:-MT5rG9e0N78X3s55UTg:b-4dbgrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L306)):*
> ```Go
> 	// dropEnumValue tries to remove the region value from the multi-region type
> 	// descriptor. Among other things, it validates that the region is not in
> 	// use by any tables. A region is considered "in use" if either a Regional By
> ```

Super Nit:  Makes this easier to read if you fully capitalize REGIONAL BY TABLE and REGIONAL BY ROW.
___
*[pkg/sql/alter_database.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5rdR-E0SJEIMjNLtZ:-MT5rdR-E0SJEIMjNLt_:b8732s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L323)):*
> ```Go
> 		}
> 	}
> 	if !found {
> ```

It's a bit strange that this checking logic is _after_ the dropEnum call above.  Are there cases where the drop can succeed and the validation here fails?  Does dropEnumValue no-op when the value is not found?
___
*[pkg/sql/alter_database.go, line 458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5sUAbD8_bL_FxJX9p:-MT5sUAbD8_bL_FxJX9q:bb9x70d) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L458)):*
> ```Go
> 	ctx context.Context, p *planner, desc *dbdesc.Immutable, regionEnumID descpb.ID,
> ) error {
> 	b := p.Txn().NewBatch()
> ```

Can we add a check in here for MultiRegionDb?  If we get in here accidentally for a non-multi-region database, this will corrupt all of the table descriptors.
___
*[pkg/sql/alter_table_locality.go, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5tDZQ8Qa5pQ89mObZ:-MT5tDZQ8Qa5pQ89mOb_:benileq) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_table_locality.go#L407)):*
> ```Go
> 
> // alterTableDescLocalityToRegionalByTable changes the locality of the given tableDesc
> // to Regional By Table homed in the specified region. It also handles the
> ```

Nit: REGIONAL BY TABLE.
___
*[pkg/sql/alter_table_locality.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5vW6IBihpaR_39mS0:-MT5vW6IBihpaR_39mS1:bg56ugv) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_table_locality.go#L414)):*
> ```Go
> 	if tableDesc.GetMultiRegionEnumDependencyIfExists() {
> 		if err := p.removeTypeBackReference(ctx, regionEnumID, tableDesc.GetID(),
> 			fmt.Sprintf("remove back ref no mr-enum %d for table %d", regionEnumID, tableDesc.GetID()),
> ```

Nit: should "no" be "on" here?
___
*[pkg/sql/alter_table_locality.go, line 423 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5vZ16ATbTXwSF1Hze:-MT5vZ16ATbTXwSF1Hzf:bwkst9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_table_locality.go#L423)):*
> ```Go
> 		return p.addTypeBackReference(
> 			ctx, regionEnumID, tableDesc.ID,
> 			fmt.Sprintf("add backref on mr-enum %d for table %d", regionEnumID, tableDesc.GetID()),
> ```

Nit: backref -> back ref.
___
*[pkg/sql/alter_table_locality.go, line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5wHx2E1BisTF0jNND:-MT5wHx2E1BisTF0jNNE:b-yekxf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_table_locality.go#L447)):*
> ```Go
> 
> // setNewLocalityConfig sets the locality config of the given table descriptor to
> // the provided config. It also removes the dependency to the multi-region enum,
> ```

Nit: dependency to -> dependancy on
___
*[pkg/sql/create_table.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5xcjF7rAbEJOERbKj:-MT5xcjF7rAbEJOERbKk:benileq) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/create_table.go#L398)):*
> ```Go
> 			typeDesc.AddReferencingDescriptorID(desc.ID)
> 			err = params.p.writeTypeSchemaChange(
> 				params.ctx, typeDesc, "add regional by table back reference")
> ```

Nit: REGIONAL BY TABLE.
___
*[pkg/sql/type_change.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KxtK6WGXyh_OJmjP:-MT5zfh-9TSNKqOugt1-:b-19xg24) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L461)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I'd probably get rid of the NB, i think the var name changing to `hasValidationToDo` or something to make this clear.
</blockquote></details>

+1 on confusion in overloading `firstClause`
___
*[pkg/sql/type_change.go, line 462 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5zmr1Cl6iAJpiq87g:-MT5zmr1Cl6iAJpiq87h:b-3tegxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/type_change.go#L462)):*
> ```Go
> 		// is handled as a special case below.
> 		if !firstClause {
> 			// We need to override the internal executors current database (which would
> ```

Nit: executor's
___
*[pkg/sql/type_change.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT6-4KP9llMq0B7vWcd:-MT6-4KP9llMq0B7vWce:b-yabv4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/type_change.go#L498)):*
> ```Go
> 			}
> 			if descpb.RegionName(member.LogicalRepresentation) == homedRegion {
> 				return errors.Newf("could not remove enum value %q as it is being used by table %q",
> ```

Might want to say here "as it is the home region for table %q".  "Being used" is a bit ambiguous, as there are [...]

2021-02-09 16:38 UTC, arulajmani reviewed
> Also, the commit record above is very helpful in understanding the code
Thanks, took a few iterations to write it out.

>"The semantics around REGIONAL BY TABLE tables and GLOBAL tables are also handled appropriately." - Do you mean the semantics around altering between the two?
I meant validation semantics -- updated to make it clear. 

What do you think about adding a subset of the commit message (the parts pertaining to `REGIONAL BY TABLE` tables' implicit dependency) in the REGIONAL BY TABLE locality config? I took a shot at writing an abridged version there, lemme know if thats good! 

RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-:-MT6UGHP3NR8-TURByVq:bq4ka50)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, and @otan)

___
*[pkg/sql/alter_database.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5qSpL6_JKuv4HkZcw:-MT6VvBdCMUkKmF1j_Ns:b-gipin6) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L275)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

More for my own info, but why the check here, as opposed to in `startExec()`?  That's where we check it for the other alters.
</blockquote></details>

My thought was that if you're not allowed to do the drop in the first place, that should be the error you get (as opposed to "you must designate a primary region"). You could ask, why not move that check to `StartExec()` as well? This is more in preparation for my upcoming change to allow dropping the primary region. I plan to model this around how `dropTable` works, which "checks" if dependent objects (in my change the type descriptor) can be dropped, and if not fails quick and fails early. 

I'm not sure there is a principled approach we follow, because dropping objects seems to perform the check during planning and as you noted alter database seems to perform the check during execution. Maybe we should unify?
___
*[pkg/sql/alter_database.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5rdR-E0SJEIMjNLtZ:-MT6HsWG9yixS4CdEWcI:b1yguuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L323)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

It's a bit strange that this checking logic is _after_ the dropEnum call above.  Are there cases where the drop can succeed and the validation here fails?  Does dropEnumValue no-op when the value is not found?
</blockquote></details>

Not really, we'd expect the`dropEnum` value to error out if the value doesn't exist and never reach this part of the code. We wouldn't even expect the database descriptor regions to be out of sync with the type descriptor regions, as we validate that. This is mostly a sanity check, that'll go away once we get rid of regions from the database descriptor entirely. 
___
*[pkg/sql/alter_database.go, line 458 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5sUAbD8_bL_FxJX9p:-MT6Z7syCE9TI26rVHGY:b-48vilt) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L458)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we add a check in here for MultiRegionDb?  If we get in here accidentally for a non-multi-region database, this will corrupt all of the table descriptors.
</blockquote></details>

Good call, done!
___
*[pkg/sql/alter_table_locality.go, line 414 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5vW6IBihpaR_39mS0:-MT6JIauBnt51MxYaD3G:bbm7lfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_table_locality.go#L414)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: should "no" be "on" here?
</blockquote></details>

Yeah :P 
___
*[pkg/sql/type_change.go, line 461 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3KxtK6WGXyh_OJmjP:-MT6OEZ9DAncy41r6-Pp:b-gsc6jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/type_change.go#L461)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

+1 on confusion in overloading `firstClause`
</blockquote></details>

Fair point, I created a new variable `validationQueryConstructed`. As for the NB, I do think it is worth keeping around, as this `REGIONAL BY TABLE` case is rather surprising, especially for those who aren't familiar with multi-region like we are. Lemme know if there's a strong objection to removing the comment. 
___
*[pkg/sql/type_change.go, line 498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT6-4KP9llMq0B7vWcd:-MT6NzLK52knwFVlOecn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/type_change.go#L498)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Might want to say here "as it is the home region for table %q".  "Being used" is a bit ambiguous, as there are several ways a table can "use" a region.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 821 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT6-wRl9JC8WjDZXM0K:-MT6KfGJ9naVELaKUF14:b-y3stag) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/catalog/tabledesc/structured.go#L821)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This comment is a bit scary, in that it states the problem, but not the "why" (i.e. REGIONAL BY TABLE tables).  Can we add more detail here so that future readers don't have to guess?

Also, does it make sense to remove the receiver type here?  That way I'd think we'd reduce the likelihood of it being called incorrectly.
</blockquote></details>

Added more context about REGIONAL BY TABLE tables. As for misuse of this function, I think this is prevented (as much as possible) by making the method private. No one outside the `tabledesc` package should be able to use this method. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4022 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT62aQaAE-UTWNtkwhP:-MT6N2io4L9dZgcOn5wU:b2smbl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/catalog/tabledesc/structured.go#L4022)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This also seems dangerous.  Is there a way we could remove this function from the receiver and explicitly pass in the LocalityConfig (to avoid bad callers)?  Same comment for other methods below.
</blockquote></details>

Discussed offline. I completely agree that we need something better here as this is quite sharp an edge to leave around. I'm opening an issue to clean this up in a followup issue. 
___
*[pkg/sql/logictest/testdata/logic_test/multiregion, line 834 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT3J-Rw5ikb2RoScw1l:-MT6RBfnEA3RWHLzh2ad:b-elbhlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8768a4a49517039555b566a6af069339555e9fc3/pkg/sql/logictest/testdata/logic_test/multiregion#L834)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah. you can include if you did `\nHINT: blah` if you wanted to ;)
</blockquote></details>

Done ;) 


<!-- Sent from Reviewable.io -->

2021-02-09 17:11 UTC, ajstorm approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-:-MT6lheACsmS5VoOVPdx:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5qSpL6_JKuv4HkZcw:-MT6kc3F5J1cFX8e8-l5:b-7kfiwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L275)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

My thought was that if you're not allowed to do the drop in the first place, that should be the error you get (as opposed to "you must designate a primary region"). You could ask, why not move that check to `StartExec()` as well? This is more in preparation for my upcoming change to allow dropping the primary region. I plan to model this around how `dropTable` works, which "checks" if dependent objects (in my change the type descriptor) can be dropped, and if not fails quick and fails early. 

I'm not sure there is a principled approach we follow, because dropping objects seems to perform the check during planning and as you noted alter database seems to perform the check during execution. Maybe we should unify?
</blockquote></details>

That makes sense.  All good.
___
*[pkg/sql/alter_database.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5rdR-E0SJEIMjNLtZ:-MT6klROBYo-0zIacmzo:b-g1l5u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L323)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Not really, we'd expect the`dropEnum` value to error out if the value doesn't exist and never reach this part of the code. We wouldn't even expect the database descriptor regions to be out of sync with the type descriptor regions, as we validate that. This is mostly a sanity check, that'll go away once we get rid of regions from the database descriptor entirely. 
</blockquote></details>

Should this be an assertion then?


<!-- Sent from Reviewable.io -->

2021-02-09 17:57 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59989)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_database.go, line 323 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59989#-MT5rdR-E0SJEIMjNLtZ:-MT6wAku9zL5eZvj2u1-:b-dvmajx) ([raw file](https://github.com/cockroachdb/cockroach/blob/213120521599ed592c07865037c6248544fcae40/pkg/sql/alter_database.go#L323)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should this be an assertion then?
</blockquote></details>

Changed, though I can't wait until this is deleted! 


<!-- Sent from Reviewable.io -->

2021-02-09 17:58 UTC, arulajmani commented
TFTRs on this. 

bors r=ajstorm, otan

2021-02-09 18:34 UTC, arulajmani commented
bors r-

2021-02-10 05:52 UTC, otan commented
bors r+

2021-02-10 07:36 UTC, otan commented
you've got the worst luck @arulajmani 

bors r+

2021-02-10 08:44 UTC, otan commented
bors r+

2021-02-10 09:20 UTC, otan commented
last try for you :P 

bors r-

2021-02-10 09:20 UTC, otan commented
bors r+

2021-02-10 09:44 UTC, otan commented
lol another fail https://teamcity.cockroachdb.com/viewLog.html?buildId=2662993&buildTypeId=Cockroach_UnitTests

bors r-

2021-02-10 09:44 UTC, otan commented
bors r+

2021-02-10 10:10 UTC, otan commented
CI is unbelievable

bors r+

2021-02-10 11:02 UTC, merged

2021-02-10 12:31 UTC, arulajmani commented
Thanks for babysitting this @otan 😅

2021-02-10 12:33 UTC, ajstorm commented
You guys make a great team!