cloudimpl: handle special char usernames in userfile
cockroachdb/cockroach pull request #60020
Opened 2021-02-09 02:20 UTC by adityamaru

This change adds support for usernames that contain special
characters when using userfile. Usernames are used in the table name prefix for
the default target userfile operates on. For the table name to be valid
usernames with special characters need to be quoted.

Fixes: #58430

Release note (bug fix): Usernames with special characters would not work
with userfile since they were not appropriately quoted.

2021-02-09 02:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60020)
<!-- Reviewable:end -->

2021-02-09 09:14 UTC, knz requested changes
The approach you've taken is still not correct, see my example test cases you should be using.

Also you're repeating the code in multiple places -- is there a way to ensure the proper implementation is present in just 1 place, then reused everywhere it needs to be?

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-:-MT53KXm1DtUKeDw5zJl:bq5swza)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/cli/userfile.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53E_lEQv9hpnsr5RV:-MT53E_lEQv9hpnsr5RW:b-n7do49) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L162)):*
> ```Go
> 	lex.EncodeUnrestrictedSQLIdent(&sqlUsername, defaultUserfileTablePrefix+user,
> 		lex.EncNoFlags)
> 	return fmt.Sprintf("%s.%s", defaultUserfileDbAndSchema, sqlUsername.String())
> ```

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
___
*[pkg/cli/userfile.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53AMW4hRbbo3Ab5On:-MT53AMW4hRbbo3Ab5Oo:b-n7do49) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L363)):*
> ```Go
> 	targetTable := qualifiedTableName + fileTableNameSuffix
> 	if strings.HasSuffix(qualifiedTableName, "\"") {
> 		targetTable = fmt.Sprintf("%s%s\"", strings.TrimSuffix(qualifiedTableName, "\""),
> ```

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
___
*[pkg/cli/userfiletable_test.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT52i1p1EBR_I4VFhUB:-MT52i1p1EBR_I4VFhUC:boihxy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfiletable_test.go#L511)):*
> ```Go
> 			},
> 			{
> 				"special-char-username",
> ```

please add the following strings too:

```
"this.username",
`this"username`,
`this""username`,
`this\044username`,
`this\xXXusername`,
```
___
*[pkg/storage/cloudimpl/file_table_storage.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT533vy3qFRzNBPw5ZQ:-MT533vz2gmUpB8poMRK:b-n7do49) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/storage/cloudimpl/file_table_storage.go#L59)):*
> ```Go
> 	lex.EncodeUnrestrictedSQLIdent(&sqlUsername, defaultUserfileTablePrefix+user,
> 		lex.EncNoFlags)
> 	return fmt.Sprintf("%s.%s", defaultUserfileDbAndSchema, sqlUsername.String())
> ```

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53HUc55XDN-FETl48:-MT53HUd8MIxIrfRQlTM:b-n7do49) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L184)):*
> ```Go
> func maybeConstructQuotedTableName(tablePrefix, tableSuffix string) string {
> 	if strings.HasSuffix(tablePrefix, "\"") {
> 		return fmt.Sprintf("%s%s\"", strings.TrimSuffix(tablePrefix, "\""), tableSuffix)
> ```

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.


<!-- Sent from Reviewable.io -->

2021-03-22 20:38 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60020)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/cli/userfile.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53E_lEQv9hpnsr5RV:-MWQdfYp0eEZfcIjS0og:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L162)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
</blockquote></details>

Done.
___
*[pkg/cli/userfile.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53AMW4hRbbo3Ab5On:-MWQdgJp6ZrhRlD6nWC5:b-92zivx) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L363)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
</blockquote></details>

This is actually a weird one. If qualifiedTableName is a quoted name egs: `defaultdb.public."foo-foo"`, what we want to do is extend this to `"defaultdb.public."foo-foo_upload_files"`. I don't think tree.TableName can help us in this case?
___
*[pkg/cli/userfiletable_test.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT52i1p1EBR_I4VFhUB:-MWQdQlbC4r4twkw5mKh:b-bm9pid) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfiletable_test.go#L511)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please add the following strings too:

```
"this.username",
`this"username`,
`this""username`,
`this\044username`,
`this\xXXusername`,
```

</blockquote></details>

The latter 4 are all invalid usernames as far as the rules for valid usernames go, are you suggesting expecting errors on these cases?
___
*[pkg/storage/cloudimpl/file_table_storage.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT533vy3qFRzNBPw5ZQ:-MWQddeHAKrlpnBm7GT_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/storage/cloudimpl/file_table_storage.go#L59)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
</blockquote></details>

Done.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53HUc55XDN-FETl48:-MWQe9bcDEXVllI1oZWH:b-1fjwzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L184)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This encoding method is incorrect. You should use `tree.TableName`, populate the fields and and call String on that.
</blockquote></details>

Same explanation as above.


<!-- Sent from Reviewable.io -->

2021-03-22 21:07 UTC, adityamaru commented
@knz apologies this fell down the list of things todo, but I've cleaned it up and left a few comments, I'd appreciate another look 🙂

2021-03-23 15:12 UTC, knz reviewed
Much better thanks! just one comment left

> Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-:-MWUdBEl4t28YwWMClM9:bh76vjg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/cli/userfile.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53AMW4hRbbo3Ab5On:-MWUc7Zi391Vm1z7Y_-W:bw83q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L363)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

This is actually a weird one. If qualifiedTableName is a quoted name egs: `defaultdb.public."foo-foo"`, what we want to do is extend this to `"defaultdb.public."foo-foo_upload_files"`. I don't think tree.TableName can help us in this case?
</blockquote></details>

1. make a TableName
2. add the suffix `_upload_files` to your tablename's `.ObjectName`
4. call String on the TableName to get the properly quoted result.
___
*[pkg/cli/userfiletable_test.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT52i1p1EBR_I4VFhUB:-MWUcJZx5bZpzc-d9b00:b-1x1ye8) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfiletable_test.go#L511)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

The latter 4 are all invalid usernames as far as the rules for valid usernames go, are you suggesting expecting errors on these cases?
</blockquote></details>

these are the rules for SQL-defined usernames but 1) we may change them tomorrow 2) we are soon going to accept username definitions from outside of SQL which may have different rules.

I think the test that would be nice to see is how the names are derived for identifiers that contain arbitrary characters, regardless of whether they are _currently_ valid SQL users.

Also, I forgot an example:

`family`  (or `index`)

these two usernames are valid according to current rules but they are also reserved keywords, and so the test might reveal some additional quoting is necessary.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MWUd4c_6W_pmfd1cuWq:-MWUd4c_6W_pmfd1cuWr:b-8uwr1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a831b9b2d01536e7d0cd470aa13b138d3d3a959c/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L832)):*
> ```Go
> 		lex.EncodeRestrictedSQLIdent(&quotedUsername, user, lex.EncNoFlags)
> 		revokeQuery := fmt.Sprintf(`REVOKE ALL ON TABLE %s, %s FROM %s`,
> 			f.GetFQFileTableName(), f.GetFQPayloadTableName(), quotedUsername.String())
> ```

I think you don't need this `quotedUsername` buffer, you may be able to solve this with `tree.Name(user).String()`?


<!-- Sent from Reviewable.io -->

2021-03-24 13:42 UTC, adityamaru reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60020)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/cli/userfile.go, line 363 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT53AMW4hRbbo3Ab5On:-MWZTEy5-U61l_TKxUUN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfile.go#L363)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1. make a TableName
2. add the suffix `_upload_files` to your tablename's `.ObjectName`
4. call String on the TableName to get the properly quoted result.
</blockquote></details>

Done.
___
*[pkg/cli/userfiletable_test.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT52i1p1EBR_I4VFhUB:-MWXHXNvEeMYuxL67BNA:b46id41) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfiletable_test.go#L511)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

these are the rules for SQL-defined usernames but 1) we may change them tomorrow 2) we are soon going to accept username definitions from outside of SQL which may have different rules.

I think the test that would be nice to see is how the names are derived for identifiers that contain arbitrary characters, regardless of whether they are _currently_ valid SQL users.

Also, I forgot an example:

`family`  (or `index`)

these two usernames are valid according to current rules but they are also reserved keywords, and so the test might reveal some additional quoting is necessary.
</blockquote></details>

Just to clarify, this fix is only to be backported to 20.2 so the set of valid users can't change from beneath us?  In 21.1 we have a much more reliable scheme that we had worked on earlier in this release https://github.com/cockroachdb/cockroach/pull/56046.
Nonetheless, I have added some testing that verifies how we create table names in these cases! Also added `index`.
___
*[pkg/storage/cloudimpl/filetable/file_table_read_writer.go, line 832 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MWUd4c_6W_pmfd1cuWq:-MWXFfkU2yifTwURarZp:bd7zieh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a831b9b2d01536e7d0cd470aa13b138d3d3a959c/pkg/storage/cloudimpl/filetable/file_table_read_writer.go#L832)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think you don't need this `quotedUsername` buffer, you may be able to solve this with `tree.Name(user).String()`?
</blockquote></details>

ah nice, tree.NameString does the appropriate quoting.


<!-- Sent from Reviewable.io -->

2021-03-24 16:01 UTC, knz approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60020)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/cli/userfiletable_test.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60020#-MT52i1p1EBR_I4VFhUB:-MWZy37z18e7cj_-lVJ9:bix20hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/67803717c873d6d91f2709a0b00e901613d531d6/pkg/cli/userfiletable_test.go#L511)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

Just to clarify, this fix is only to be backported to 20.2 so the set of valid users can't change from beneath us?  In 21.1 we have a much more reliable scheme that we had worked on earlier in this release https://github.com/cockroachdb/cockroach/pull/56046.
Nonetheless, I have added some testing that verifies how we create table names in these cases! Also added `index`.
</blockquote></details>

cool that works for me.


<!-- Sent from Reviewable.io -->

2021-03-24 16:49 UTC, adityamaru commented
TFTR!

2021-03-24 16:49 UTC, merged