sql: Allow for multi-region database restores
cockroachdb/cockroach pull request #60257
Opened 2021-02-09 20:48 UTC by ajstorm

Until this commit, restores of multi-region databases failed due to the
fact that the multi-region enum's type ID was changing as part of the
restore.  This commit remaps the enum ID so that the restore succeeds.

The commit also rebuilds the database-level zone configuration.  The
table level zone configurations will be handled in a follow-on PR.

Release note (sql change): Adds support for restore of multi-region
databases.

Resolves #59631.j

2021-02-09 20:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60257)
<!-- Reviewable:end -->

2021-02-09 21:00 UTC, otan approved these changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7_pws1Wa_PdA4OjOS:-MT7_pws1Wa_PdA4OjOT:b-5ibti7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/ccl/backupccl/restore_job.go#L1026)):*
> ```Go
> 	for _, t := range typesByID {
> 		typeDesc := t.TypeDesc()
> 		if typeDesc.GetKind() == descpb.TypeDescriptor_MULTIREGION_ENUM {
> ```

can we assert that there's only one?


<!-- Sent from Reviewable.io -->

2021-02-09 21:04 UTC, otan requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, and @pbardea)

___
*[pkg/sql/region_util.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7aSoHD7T0MXjJtHyp:-MT7aSoHD7T0MXjJtHyq:b-lyw7wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L399)):*
> ```Go
> 	execConfig *ExecutorConfig,
> ) error {
> 	if _, err := writeZoneConfig(
> ```

actually, we need a TODO here to merge this with any existing database config (similar to we do for table).
we can move all this code up to ApplyZoneConfigFromDatabaseRegionConfig since it is now the only user.
___
*[pkg/sql/region_util.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7akbb5ET_gjAP6qgd:-MT7akbb5ET_gjAP6qge:b-58cu74) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L607)):*
> ```Go
> }
> 
> func ApplyZoneConfigFromDatabaseRegionConfig(
> ```

lint will complain you'll need a comment for this one.
___
*[pkg/sql/region_util.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7apiYEGtdQkRQmw45:-MT7apiYEGtdQkRQmw46:b-aspjfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L620)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

we should read the existing zone config, and use `zc.CopyFromZone`


<!-- Sent from Reviewable.io -->

2021-02-10 02:15 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dt, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7_pws1Wa_PdA4OjOS:-MT8Ok_R17QvaICOxjij:bo946qv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/ccl/backupccl/restore_job.go#L1026)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we assert that there's only one?
</blockquote></details>

  Done.
___
*[pkg/sql/region_util.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7aSoHD7T0MXjJtHyp:-MT8QadXAz-y6XkAKEjN:b850sr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L399)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

actually, we need a TODO here to merge this with any existing database config (similar to we do for table).
we can move all this code up to ApplyZoneConfigFromDatabaseRegionConfig since it is now the only user.
</blockquote></details>

Added.  Do we have an issue for this right now?  If not, I'll create one.  
___
*[pkg/sql/region_util.go, line 607 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7akbb5ET_gjAP6qgd:-MT8QoC-6pdzcSe_eSHm:b6za48o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L607)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

lint will complain you'll need a comment for this one.
</blockquote></details>

Already complained.  I added one.
___
*[pkg/sql/region_util.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7apiYEGtdQkRQmw45:-MT8fa1rB46Rqry5_e-B:bkfqjcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L620)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

we should read the existing zone config, and use `zc.CopyFromZone`
</blockquote></details>

TODO added above.  I'm assuming this is what you meant by this comment.


<!-- Sent from Reviewable.io -->

2021-02-10 02:39 UTC, otan approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @otan, and @pbardea)

___
*[pkg/sql/region_util.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7aSoHD7T0MXjJtHyp:-MT8nCng11ddlt_xjkck:bz53tzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L399)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Added.  Do we have an issue for this right now?  If not, I'll create one.  
</blockquote></details>

I would say https://github.com/cockroachdb/cockroach/issues/59631 mentions this, so this isn't a resolves so much as refs :).

Also I meant this function can be deleted, and all this blob of code should move into it's only caller `ApplyZoneConfigFromDatabaseRegionConfig`


<!-- Sent from Reviewable.io -->

2021-02-10 04:52 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @dt, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1024 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9ERIABqOPieZy7RRb:-MT9ERIABqOPieZy7RRc:b-9tfrbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1024)):*
> ```Go
> 	// cluster restores, as they will have the zone configurations restored as
> 	// as the system tables are restored.
> 	foundMREnum := false
> ```

Can we make this a map so that we can ensure every multi-region database has only one multi-region enum in the full cluster backup as well? IIUC the current code only validates it for the single database restore case. 
___
*[pkg/ccl/backupccl/restore_job.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9GXty3sGceZqU6LcY:-MT9GXty3sGceZqU6LcZ:bjudy7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1041)):*
> ```Go
> 
> 				// Update the RegionEnumID to record the new multi-region enum ID.
> 				desc.RegionConfig.RegionEnumID = t.GetID()
> ```

Should we be validating the database descriptor, or does that happen downstream?


<!-- Sent from Reviewable.io -->

2021-02-10 13:30 UTC, pbardea requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, and @otan)

___
*[pkg/ccl/backupccl/restore_job.go, line 1024 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9ERIABqOPieZy7RRb:-MTB4dAhCPwz7Xnw63OC:buu0zzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1024)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we make this a map so that we can ensure every multi-region database has only one multi-region enum in the full cluster backup as well? IIUC the current code only validates it for the single database restore case. 
</blockquote></details>

+1, I would also be in favour of adding a test case that restores 2 multi-region databases.
___
*[pkg/ccl/backupccl/restore_job.go, line 1051 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MTB4L1E4QyjnnxXiypT:-MTB4L1E4QyjnnxXiypU:b-xxmnoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1051)):*
> ```Go
> 						desc.GetID(),
> 						*desc.RegionConfig,
> 						p.ExtendedEvalContext().Txn,
> ```

Let's create these zone configs in the same transaction that creates the descriptors (directly below). Since this job can run in the background, the planner's transaction isn't well defined.


<!-- Sent from Reviewable.io -->

2021-02-10 18:53 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dt, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1024 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9ERIABqOPieZy7RRb:-MTBcJ7X6cZbmWWlkykp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1024)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

+1, I would also be in favour of adding a test case that restores 2 multi-region databases.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/restore_job.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9GXty3sGceZqU6LcY:-MTBd5Xv-FR2z2MSmmgC:b-d60i12) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1041)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we be validating the database descriptor, or does that happen downstream?
</blockquote></details>

We do some light validation that the RegionConfig exists above.  There is some more that happens downstream, which is what caught this problem initially.  Are you thinking we should add enum-dbdesc cross validation here? 
___
*[pkg/ccl/backupccl/restore_job.go, line 1051 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MTB4L1E4QyjnnxXiypT:-MTC9pNHA1B9SgJZuWNW:b-527cgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1051)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Let's create these zone configs in the same transaction that creates the descriptors (directly below). Since this job can run in the background, the planner's transaction isn't well defined.
</blockquote></details>

Done.  I've moved it down to be run in the `details.PrepareCompleted` section.
___
*[pkg/sql/region_util.go, line 399 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT7aSoHD7T0MXjJtHyp:-MTCDn1gBH5JTRcyvWBh:b-t7t6un) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a51e17d05d16ffe73e3d19286d064cbb94fb6aa/pkg/sql/region_util.go#L399)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

I would say https://github.com/cockroachdb/cockroach/issues/59631 mentions this, so this isn't a resolves so much as refs :).

Also I meant this function can be deleted, and all this blob of code should move into it's only caller `ApplyZoneConfigFromDatabaseRegionConfig`
</blockquote></details>

There's still `initializeMultiRegionDatabase()` which calls `applyZoneConfigFromDatabaseRegionConfig`, and a few others in alter_database.go but I cleaned them up and removed this function.


<!-- Sent from Reviewable.io -->

2021-02-10 21:55 UTC, otan approved these changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dt, @otan, and @pbardea)



<!-- Sent from Reviewable.io -->

2021-02-10 22:11 UTC, pbardea approved these changes
LGTM

2021-02-10 22:17 UTC, ajstorm reviewed
TFTRs everyone!

bors r=otan,arulajmani,pbardea

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-:-MTD0Am_CFUKZNuhVFu6:b-l70bjy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @dt, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9GXty3sGceZqU6LcY:-MTD04Ly8-n8uiAXikQB:b42302s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1041)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

We do some light validation that the RegionConfig exists above.  There is some more that happens downstream, which is what caught this problem initially.  Are you thinking we should add enum-dbdesc cross validation here? 
</blockquote></details>

I added the validation you requested here (and that we pair programmed together).  I think that means we're good to go.


<!-- Sent from Reviewable.io -->

2021-02-10 23:01 UTC, ajstorm commented
Failing...

bors r-

2021-02-10 23:01 UTC, ajstorm commented
Attempt 2

bors r=otan,arulajmani,pbardea

2021-02-10 23:28 UTC, ajstorm commented
bors r-

2021-02-11 01:06 UTC, arulajmani approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60257)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @dt, @otan, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 1041 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60257#-MT9GXty3sGceZqU6LcY:-MTDbvITEpKZcvANnVPL:b4z1y2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba4d6fe201f3d9fbe3523710ac77e3948b0c0f5f/pkg/ccl/backupccl/restore_job.go#L1041)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I added the validation you requested here (and that we pair programmed together).  I think that means we're good to go.
</blockquote></details>

Yeah! :D 


<!-- Sent from Reviewable.io -->

2021-02-11 03:02 UTC, ajstorm commented
Now that the log-jam has cleared:

bors r=otan,arulajmani,pbardea

2021-02-11 03:49 UTC, merged