jobs: remove WithTxn
cockroachdb/cockroach pull request #60554
Opened 2021-02-13 01:08 UTC by lucy-zhang

Release note: None

2021-02-13 01:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60554)
<!-- Reviewable:end -->

2021-02-16 23:26 UTC, lucy-zhang commented
I attempted to preserve the existing behavior in this PR, even in places where we seem to have intended to update the job inside a transaction closure using the transaction but neglected to use `WithTxn`. When I tried to "fix" these, I got some semi-consistent CI test timeouts (unclear from which change exactly), and decided that those changes were best made separately. All these places are commented. I don't know if it's worth actually opening a separate issue, but I might take a look if I have time.

@pbardea you were the Bulk IO person automatically assigned, and I don't think you have to review this, but maybe you happen to know something about the job updates in the backfiller and GC job.

2021-02-17 03:19 UTC, ajwerner requested changes
A truly wonderful change!

> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-:-MThzsXd5RBqkMsU35HC:b3xk4er)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThydy31SOs6yRa_bf5:-MThydy4-GXEjA-N8WBP:b7q0v5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L48)):*
> ```Go
> 			return false, err
> 		}
> 		// TODO: This job update should possibly use the txn.
> ```

This should definitely use the txn. `LoadJobWithTxn` used to set the job.txn field to that txn (it did a `WithTxn` using the txn). 
___
*[pkg/sql/backfill.go, line 1273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThzIn61XszCksqOD9E:-MThzIn61XszCksqOD9F:b-n6mvqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/sql/backfill.go#L1273)):*
> ```Go
> 				fractionCompleted := origFractionCompleted + fractionLeft*fractionRangesFinished
> 				// TODO: This job update should possibly use the txn.
> 				if err := sc.job.FractionProgressed(ctx, nil /* txn */, jobs.FractionUpdater(fractionCompleted)); err != nil {
> ```

yes  please, this one is just bad. 
___
*[pkg/sql/create_stats.go, line 535 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThzSwb34NgTKbQspP1:-MThzSwb34NgTKbQspP2:b-yauzpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/sql/create_stats.go#L535)):*
> ```Go
> 			// it can be cleaned up at a higher level.
> 			// TODO: This job update should possibly use the txn.
> 			if jobErr := r.job.FractionProgressed(
> ```

yes please. 
___
*[pkg/sql/gcjob/gc_job_utils.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThzdPLBo689m9UwAT2:-MThzdPLBo689m9UwAT3:ba741h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/sql/gcjob/gc_job_utils.go#L120)):*
> ```Go
> 				return err
> 			}
> 			// TODO: This job update should possibly use the txn.
> ```

the load meant it used to be 
___
*[pkg/sql/gcjob/gc_job_utils.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThzfR3411tw2nUKqlk:-MThzfR3411tw2nUKqll:b-n0tjw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/sql/gcjob/gc_job_utils.go#L264)):*
> ```Go
> 			return err
> 		}
> 		// TODO: This job update should possibly use the txn.
> ```

yes please


<!-- Sent from Reviewable.io -->

2021-02-17 14:04 UTC, pbardea reviewed
:tada: As Andrew pointed out, it looks like the GC job was already using the txn with the loading phase, and the backfiller just missed it - much clearer where we're missing these after this change. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-:-MTkHuLd3p1LcE5JD1U-:b-hu2avw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)



<!-- Sent from Reviewable.io -->

2021-02-17 17:57 UTC, lucy-zhang reviewed
How would the two of you feel about merging this PR which keeps the existing behavior, even where it's incorrect, and making changes in subsequent PRs (possibly during the stability period)? I can open an issue to track this.

I couldn't figure out the test timeouts I was seeing when I did make the changes; nothing seemed obviously hung from the goroutine dump and I wasn't getting the timeouts consistently, so it's possible that combining some things into a single transaction caused more contention and restarts, or something, though that seems kind of implausible. So I think this all deserves more investigation. I can isolate the changes one by one and run the tests on my gceworker (or just in CI), but that will take some time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-:-MTl5q3p6B0QS1IgxfI2:b6qtgsn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThydy31SOs6yRa_bf5:-MTkhYa-928ucZf7IoMW:bd9iljq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L48)):*
> `LoadJobWithTxn` used to set the job.txn field to that txn (it did a `WithTxn` using the txn).

By "used to," do you mean before this PR? I thought the txn specified in `LoadJobWithTxn` only applies to the method itself, because it internally uses `runInTxn`, which has a `defer func() { j.txn = nil }()`. If that's not the case then I will happily make this change.


<!-- Sent from Reviewable.io -->

2021-02-17 18:31 UTC, ajwerner approved these changes
Thanks for uncovering the badness that we didn't even realize we were dealing with. Merge away

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-:-MTlFYc1DKc02HU0NZhm:b-2y27yo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/jobs/jobsprotectedts/jobs_protected_ts.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-MThydy31SOs6yRa_bf5:-MTl8rAA6eYEXMWUt4Vv:b-rpahry) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccec4c8df6de5244cff3a28ab3b99573c99c6cbb/pkg/jobs/jobsprotectedts/jobs_protected_ts.go#L48)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

> `LoadJobWithTxn` used to set the job.txn field to that txn (it did a `WithTxn` using the txn).

By "used to," do you mean before this PR? I thought the txn specified in `LoadJobWithTxn` only applies to the method itself, because it internally uses `runInTxn`, which has a `defer func() { j.txn = nil }()`. If that's not the case then I will happily make this change.
</blockquote></details>

:grimacing: 


<!-- Sent from Reviewable.io -->

2021-02-17 18:31 UTC, ajwerner reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60554#-:-MTlFe_T3tYfbmv6f9j2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang)



<!-- Sent from Reviewable.io -->

2021-02-17 18:44 UTC, lucy-zhang commented
TFTR. I opened an issue (#60690) and the TODOs refer to it now.

bors r+

2021-02-17 21:25 UTC, merged