sql: repartition regional by row tables on region add
cockroachdb/cockroach pull request #60596
Opened 2021-02-15 23:40 UTC by arulajmani

This patch adds functionality to repartition REGIONAL BY ROW tables when
a new region is added to the database. An index can only be partitioned
using an enum value if it is PUBLIC. Thus we only modify partition
descriptors once all transitioning enum members have done so. This
happens in the type schema changer, in a separate txn to the one that
finalized the promotion. Once all indexes of the table have been
repartitioned, the zone configurations are also updated to apply to the
new partitions.

Release note (sql change): ALTER DATABASE ... ADD REGION now
repartitions REGIONAL BY ROW tables and updates the zone configs on
the newly created partitions as well.

2021-02-15 23:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60596)
<!-- Reviewable:end -->

2021-02-15 23:46 UTC, arulajmani commented
The one thing that this PR doesn't handle is what happens if the transaction performing the repartitioning encounters a non-retryable error. By that point, because the enum member promotion/demotion has been finalized, there isn't a way to roll back changes. I'm not sure if there is any way around this right now, though I wonder if it makes sense to repartition individual tables in individual transactions. Would love some thoughts on this stuff and any other tricky scenarios that I may be missing here.

2021-02-15 23:48 UTC, otan requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, and @lucy-zhang)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3gZLEqepsgha-RdV:-MTc3gZLEqepsgha-RdW:b-mejx7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1815)):*
> ```
> 
> statement ok
> CREATE DATABASE add_regions WITH PRIMARY REGION "ca-central-1";
> ```

let's put these in `regional_by_row`
___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4IHh9vTbpDpsluL4:-MTc4IHh9vTbpDpsluL5:b8r5wgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1946)):*
> ```
>                  crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL DEFAULT default_to_database_primary_region(gateway_region())::public.crdb_internal_region,
>                  CONSTRAINT "primary" PRIMARY KEY (crdb_region ASC, pk ASC),
>                  INDEX regional_by_row_i_idx (crdb_region ASC, i ASC),
> ```

this now has crdb_region in front, so it is no longer implicitly partitioned, which is incorrect. see comment about CreatePartitioning below
___
*[pkg/sql/type_change.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3s-m4TAi4VE3mlbZ:-MTc3s-m4TAi4VE3mlb_:b-fvbggf) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L308)):*
> ```Go
> 		// as enum members must be public before we can partition based on those
> 		// values, which happens when the transaction above commits.
> 		if typeDesc.Kind == descpb.TypeDescriptor_MULTIREGION_ENUM && len(t.transitioningMembers) > 0 {
> ```

does this happen on a separate transaction to the enum finalisation? if so, how does rollback / failing txn work?
___
*[pkg/sql/type_change.go, line 354 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc42YY7wuURVtC20eP:-MTc42YY7wuURVtC20eQ:bn0qfb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L354)):*
> ```Go
> ) error {
> 	p, cleanup := NewInternalPlanner(
> 		"repartition-tables",
> ```

nit: repartition-regional-by-row-table
___
*[pkg/sql/type_change.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4N6H36KW0yFRzqCI:-MTc4N6H36KW0yFRzqCJ:b-xfyuk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L393)):*
> ```Go
> 			// dropped.
> 			for _, index := range tableDesc.NonDropIndexes() {
> 				newIdx, err := CreatePartitioning(
> ```

CreatePartitioning on an already implicitly partitioned index will un-implicitly partition the index.
You'll need to add some logic to truncate the implicit column partitioning before redoing it, i.e.

```
indexDesc.ColumnIDs = indexDesc.ColumnIDs[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.ColumnNames = indexDesc.ColumnNames[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.ColumnDirections = indexDesc.ColumnDirections[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.Partitioning = descpb.PartitioningDesc()
```

you'll probably want to make this a method.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3Z6m7CKQ7QEF_8cH:-MTc3Z6m7CKQ7QEF_8cI:be1r23q) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/catalog/tabledesc/structured.go#L4029)):*
> ```Go
> func (desc *wrapper) GetRegionalByRowTableRegionColumnName() (tree.Name, error) {
> 	if !desc.IsLocalityRegionalByRow() {
> 		return "", errors.New("is not REGIONAL BY ROW")
> ```

nit: put the column name in here


<!-- Sent from Reviewable.io -->

2021-02-16 00:28 UTC, otan commented
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3Z6m7CKQ7QEF_8cH:-MTcEG5j0Ie1c_XKpKdR:bsri2o0) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/catalog/tabledesc/structured.go#L4029)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: put the column name in here
</blockquote></details>

i do this in https://github.com/cockroachdb/cockroach/pull/60600


<!-- Sent from Reviewable.io -->

2021-02-16 15:06 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3gZLEqepsgha-RdV:-MTfEnxE723Qrn6mBsyH:bijc1wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1815)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

let's put these in `regional_by_row`
</blockquote></details>

I'm confused that these even work here.  Don't we require CCL to allow REGIONAL BY ROW tables to be created?
___
*[pkg/sql/type_change.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3s-m4TAi4VE3mlbZ:-MTfGHIAAyivMQ8HgJUT:boxweg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L308)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

does this happen on a separate transaction to the enum finalisation? if so, how does rollback / failing txn work?
</blockquote></details>

Is there no way to make this work in the same transaction?  Do we support other operations like this in the same transaction (add column and partition by that column?)
___
*[pkg/sql/type_change.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTfHax_BNaCC_jACLsO:-MTfHaxa6-895I-I8XLF:bxb75vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L346)):*
> ```Go
> }
> 
> func repartitionRegionalByRowTables(
> ```

This function has a fair bit going on in it.  I'd think it would warrant a comment above.
___
*[pkg/sql/type_change.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTfKbQN3xyG3ZvVB5rB:-MTfKbQN3xyG3ZvVB5rC:b-2li6fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L379)):*
> ```Go
> 			return err
> 		}
> 		if tableDesc.IsLocalityRegionalByRow() {
> ```

Nit: We can save one level of indentation if we `continue` here in cases where we're !RBR.  In fact, you could combine this check with the check below to further simplify the code:

```
if !tableDesc.IsLocalityRegionalByRow()  || tableDesc.Dropped() {
   continue
}
```
___
*[pkg/sql/type_change.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4N6H36KW0yFRzqCI:-MTfM2V-C86BaO_vCsUf:b-kh6db6) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L393)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

CreatePartitioning on an already implicitly partitioned index will un-implicitly partition the index.
You'll need to add some logic to truncate the implicit column partitioning before redoing it, i.e.

```
indexDesc.ColumnIDs = indexDesc.ColumnIDs[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.ColumnNames = indexDesc.ColumnNames[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.ColumnDirections = indexDesc.ColumnDirections[indexDesc.PartitioningNumImplicitColumns:]
indexDesc.Partitioning = descpb.PartitioningDesc()
```

you'll probably want to make this a method.
</blockquote></details>

Does this speak to the need to push this code directly into `CreatePartitioning` (or as an optional flag)?  Seems error prone the way it currently exists.


<!-- Sent from Reviewable.io -->

2021-02-16 17:49 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3gZLEqepsgha-RdV:-MTfWd-NAIVfI2MUia1A:b-ist9ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1815)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm confused that these even work here.  Don't we require CCL to allow REGIONAL BY ROW tables to be created?
</blockquote></details>

I think `regional_by_row` is in ccl -- I forgot that existed, I'll move these.
___
*[pkg/sql/type_change.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3s-m4TAi4VE3mlbZ:-MTfmbci9MxuEAmGsmtV:b-u9ahj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L308)):*
> add column and partition by that column

I don't think this is possible unless the column is then used to create an index. The index, once added, isn't visible to the transaction that added it because it isn't public yet. That being said, Im not sure if there's an analogy between what prevents us from using the same txn here (non public enum member) to the scenario I described above. 

As for can we allow partitioning if the enum member is in read only mode? I don't think we can in the general case because members in read only mode may be removed instead of being promoted to public (either because of a rollback or because they're being removed). 

I could use some help around this issue from the Schema team -- cc @ajwerner @lucy-zhang 
___
*[pkg/sql/type_change.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4N6H36KW0yFRzqCI:-MTfnRSG5-BzYqEBAdF4:b-vos0k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L393)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does this speak to the need to push this code directly into `CreatePartitioning` (or as an optional flag)?  Seems error prone the way it currently exists.
</blockquote></details>

I agree w you Adam, I'll push out something to that effect soon. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3Z6m7CKQ7QEF_8cH:-MTfJfY41KFTpjkLYqCY:b-g0mt2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/catalog/tabledesc/structured.go#L4029)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i do this in https://github.com/cockroachdb/cockroach/pull/60600
</blockquote></details>

Assuming you meant table name here? Done.


<!-- Sent from Reviewable.io -->

2021-02-18 15:01 UTC, arulajmani reviewed
This is still missing a test to ensure transactional rollbacks, but before I can add that, I need to fix the fact that currently the type schema changer doesn't handle region add failing too well (it basically leaves the database descriptor and type descriptor out of sync, causing validation failure). This should be fixed once we stop duplicating regions, but until then I'm inclined to merge a bandaid to enable testing. I'll do so in a separate patch, and then rebase this thing.

The code change, however, should be ready for another look! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-:-MTpd4iAElC9p_YgtcbO:b-c5lpl5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3gZLEqepsgha-RdV:-MTlBD8C6CKUa8oJ41pq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1815)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think `regional_by_row` is in ccl -- I forgot that existed, I'll move these.
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTfHax_BNaCC_jACLsO:-MTkupvSBbaxAOAiWr2F:bohqzsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L346)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This function has a fair bit going on in it.  I'd think it would warrant a comment above.
</blockquote></details>

Agreed, done.
___
*[pkg/sql/type_change.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4N6H36KW0yFRzqCI:-MTpcxl832ivI_eaoXm1:bf4hx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/type_change.go#L393)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I agree w you Adam, I'll push out something to that effect soon. 
</blockquote></details>

No longer applicable, as @otan already fixed this! 


<!-- Sent from Reviewable.io -->

2021-02-19 15:51 UTC, ajstorm reviewed
> Reviewed 12 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuuCs_8ZRzBc7gWlbq:-MTuuCsa8AMygz7roBOA:bb5gc6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1272)):*
> ```
> 
> query TT
> SHOW CREATE TABLE regional_by_row_as
> ```

Nit: Not required for this PR, but I'm wondering if we could make these tests more robust by creating a new table with the same columns _after_ the regions have been added, and then diffing their SHOW CREATE TABLE statements (and zone configs, if we move them out of SHOW CREATE TABLE) with the tables that were altered through the ADD REGION process?
___
*[pkg/sql/type_change.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuwM-Z2eYsRBTagJuC:-MTuwM-Z2eYsRBTagJuD:bjeqyf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L331)):*
> ```Go
> 				if errors.Is(err, catalog.ErrDescriptorNotFound) {
> 					// Swallow.
> 					log.Infof(ctx, "assuming repartitioned table %d was dropped and moving on", tbID)
> ```

Nit: Can we be a bit more descriptive in this log record?  Something like "in the process of changing types, table being repartitioned can not be found - assuming repartitioned table..."?
___
*[pkg/sql/type_change.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuwiq29z0lNFl6sKYM:-MTuwiq33QvROyWvIUKa:b5c09kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L337)):*
> ```Go
> 		}
> 
> 		// Finally, make sure all of the leases are updated.
> ```

Nit: To contrast with the previous comment, maybe "...all of the _type_ leases are update"?
___
*[pkg/sql/type_change.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuwwpv8BbxmWtZOuC4:-MTuwwpv8BbxmWtZOuC5:b7u6zam) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L359)):*
> ```Go
> }
> 
> // repartitionRegionalByRowTables takes multi-region enum and re-partitions all
> ```

Nit: "takes _a_ multi-region enum..."
___
*[pkg/sql/type_change.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTux1Sg2_xnJWRJOK4e:-MTux1Sg2_xnJWRJOK4f:bix797d) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L362)):*
> ```Go
> // REGIONAL BY ROW tables in the enclosing database such that there is a
> // partition and corresponding zone configuration for all PUBLIC enum members
> // (regions). Th
> ```

Nit: "Th"?  Don't leave me hanging dude.

Can we also describe the cases where we may find non-PUBLIC enum members here?
___
*[pkg/sql/type_change.go, line 392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuxtK1-WuCZRhnK4pQ:-MTuxtK1-WuCZRhnK4pR:bqokfux) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L392)):*
> ```Go
> 		ctx, txn, typeDesc.ParentID, tree.DatabaseLookupFlags{Required: true})
> 	if err != nil {
> 		return repartitionedTableIDs, err
> ```

Nit: this code might read better if we return a `nil` slice in the error cases.  When I glanced at this first I thought: "wait, why are we returning the slice here?" and then I realized that it's still `nil`.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3Z6m7CKQ7QEF_8cH:-MTuz4-UBmlE2ojmCly_:b-ug82kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/catalog/tabledesc/structured.go#L4029)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Assuming you meant table name here? Done.
</blockquote></details>

Why the change from an assertion?  Are there legitimate cases where we can get in here?


<!-- Sent from Reviewable.io -->

2021-02-19 20:10 UTC, arulajmani reviewed
Added the test I promised, RFAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-:-MTvuZ2sC0QRI84P_yJq:b-kngfj5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuuCs_8ZRzBc7gWlbq:-MTvrwI36hvGqaVddzHT:br3cdzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1272)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Not required for this PR, but I'm wondering if we could make these tests more robust by creating a new table with the same columns _after_ the regions have been added, and then diffing their SHOW CREATE TABLE statements (and zone configs, if we move them out of SHOW CREATE TABLE) with the tables that were altered through the ADD REGION process?
</blockquote></details>

Sounds like a good idea. Maybe instead of comparing the SHOW CREATE TABLE statements, we can instead compare the two descriptors? (In a followup, ofcourse)
___
*[pkg/sql/type_change.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTux1Sg2_xnJWRJOK4e:-MTvlR2b13sAYpZguic-:bywa604) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L362)):*
> Nit: "Th"? Don't leave me hanging dude.

Oops removed.

> Can we also describe the cases where we may find non-PUBLIC enum members here?

I don't think this works as expected until https://github.com/cockroachdb/cockroach/issues/60620 is resolved. One way this scenario can happen is if 2 concurrent transactions try to add a region. In that case, atleast one but maybe both of those transactions could fail. This is because we're constructing the partitioning clause based on the regions on the database descriptor, but the first job that tries to repartition will not be able to partition based on the READ ONLY member the second job is responsible for promoting. 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc3Z6m7CKQ7QEF_8cH:-MTvpZ5X0puENf1MX691:b-ek7b6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/sql/catalog/tabledesc/structured.go#L4029)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why the change from an assertion?  Are there legitimate cases where we can get in here?
</blockquote></details>

Good catch, rebase mishap 


<!-- Sent from Reviewable.io -->

2021-02-19 21:48 UTC, ajstorm reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> but I didn't look too closely at the schema changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-:-MTwFnPl9X1UxYmRViTQ:b-tgcatl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTuuCs_8ZRzBc7gWlbq:-MTwF95M1-nKQqh0CJbC:b-xxz5rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1272)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Sounds like a good idea. Maybe instead of comparing the SHOW CREATE TABLE statements, we can instead compare the two descriptors? (In a followup, ofcourse)
</blockquote></details>

Sure, that works.
___
*[pkg/sql/type_change.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTux1Sg2_xnJWRJOK4e:-MTwFZjJBYnsmC6y3e4P:b33qbz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f65599f4d7b7102ecaa01f96e452e2853c15c88/pkg/sql/type_change.go#L362)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> Nit: "Th"? Don't leave me hanging dude.

Oops removed.

> Can we also describe the cases where we may find non-PUBLIC enum members here?

I don't think this works as expected until https://github.com/cockroachdb/cockroach/issues/60620 is resolved. One way this scenario can happen is if 2 concurrent transactions try to add a region. In that case, atleast one but maybe both of those transactions could fail. This is because we're constructing the partitioning clause based on the regions on the database descriptor, but the first job that tries to repartition will not be able to partition based on the READ ONLY member the second job is responsible for promoting. 

</blockquote></details>

New comment, describing the issue looks good.


<!-- Sent from Reviewable.io -->

2021-02-19 22:02 UTC, arulajmani commented
@ajwerner I know we talked about this approach offline the other day, but the changes in the desc Collection could use a look from you (or @postamar) as folks most familiar with that code.

2021-02-21 19:39 UTC, otan reviewed
> Reviewed 1 of 16 files at r2, 6 of 8 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @lucy-zhang, @otan, and @postamar)

___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row, line 1210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU54KMb4S4M3XNqY6-7:-MU54KMb4S4M3XNqY6-8:bpf5w1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bc9d9118c3d01e2a511f8a10a5d68bc6654426a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row#L1210)):*
> ```
> 
> query TT
> SHOW CREATE TABLE regional_by_row
> ```

to futureproof this, can you add `SELECT target, raw_config_sql FROM crdb_internal.zones WHERE table_name = 't_regional_by_row' ORDER BY target` for each of these `SHOW CREATE TABLE`s?
___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU54_di5ZiP3Q1iL-wW:-MU54_di5ZiP3Q1iL-wX:b-7etfu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bc9d9118c3d01e2a511f8a10a5d68bc6654426a/pkg/ccl/multiregionccl/regional_by_row_test.go#L372)):*
> ```Go
> 	regionNames := make([]string, numServers)
> 	for i := 0; i < numServers; i++ {
> 		// "us-east1", "us-east2"...
> ```

do you mind extracting this cluster setup to a method? i have a feels we'll use this often.
___
*[pkg/sql/planner.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU552on4Ma0oqDlSiU4:-MU552on4Ma0oqDlSiU5:b-uw1x9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bc9d9118c3d01e2a511f8a10a5d68bc6654426a/pkg/sql/planner.go#L248)):*
> ```Go
> 	sessionData sessiondatapb.SessionData,
> 	collection *descs.Collection,
> ) (interface{}, func()) {
> ```

can you use the options pattern for this (as per our style guide), e.g. https://www.sohamkamani.com/golang/options-pattern/


<!-- Sent from Reviewable.io -->

2021-02-22 00:57 UTC, arulajmani reviewed
RFAL 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-:-MU6EUi3BgasegTaiGi0:b-828fno)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @ajwerner, @arulajmani, @lucy-zhang, @otan, and @postamar)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 1946 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MTc4IHh9vTbpDpsluL4:-MU668RT42sb0pWT3T0r:b-ovysv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/18952af86604e153b3e04234692c53e3a1271548/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L1946)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this now has crdb_region in front, so it is no longer implicitly partitioned, which is incorrect. see comment about CreatePartitioning below
</blockquote></details>

Talked offline, adding SHOW ZONE CONFIGURATIONS (which will be re-written later) and a query on SHOW PARTITIONS. 
___
*[pkg/ccl/multiregionccl/regional_by_row_test.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU54_di5ZiP3Q1iL-wW:-MU60B115UQl54qyy8eT:b2f1860) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bc9d9118c3d01e2a511f8a10a5d68bc6654426a/pkg/ccl/multiregionccl/regional_by_row_test.go#L372)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

do you mind extracting this cluster setup to a method? i have a feels we'll use this often.
</blockquote></details>

I agree, done. 
___
*[pkg/sql/planner.go, line 248 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU552on4Ma0oqDlSiU4:-MU6EQeTAA4mZq2d9L5m:b-vlgkwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bc9d9118c3d01e2a511f8a10a5d68bc6654426a/pkg/sql/planner.go#L248)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can you use the options pattern for this (as per our style guide), e.g. https://www.sohamkamani.com/golang/options-pattern/
</blockquote></details>

Done, thanks for the suggestion! 


<!-- Sent from Reviewable.io -->

2021-02-22 01:03 UTC, otan approved these changes
> Reviewed 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @lucy-zhang, @otan, and @postamar)

___
*[pkg/sql/planner.go, line 249 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FFBa11nWkpWdROJ2:-MU6FFBa11nWkpWdROJ3:b-x7m3zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L249)):*
> ```Go
> // WithDescCollection configures the planner with the provided collection
> // instead of the default (creating a new one from scratch).
> func WithDescCollection(collection *descs.Collection) InternalPlannerParamsOption {
> ```

i usually like prefixing the option like so: `InternalPlannerParamsOption(With)DescCollection` so it's searchable easily with just the prefix (but it can be a bit long)
___
*[pkg/sql/planner.go, line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6F8VYDiGBN1jnGu00:-MU6F8VYDiGBN1jnGu01:bi5snti) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L257)):*
> ```Go
> // NewInternalPlanner is an exported version of newInternalPlanner. It
> // returns an interface{} so it can be used outside of the sql package.
> // NewInternalPlanner initializes a new desc.Collection if an ovveride option
> ```

i would nix the new comment, or at the very least, fix the `ovveride` typo :P 
___
*[pkg/sql/planner.go, line 298 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FWR2DuMIX2NlTaq-:-MU6FWR3E429rE8DF1Ha:b-ycfosi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L298)):*
> ```Go
> 	execCfg *ExecutorConfig,
> 	sessionData sessiondatapb.SessionData,
> 	params *InternalPlannerParams,
> ```

can we thread the options into here to avoid this new struct?
___
*[pkg/sql/values_test.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FehQ0wdulqyyA3Rt:-MU6FehQ0wdulqyyA3Ru:bpd1tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/values_test.go#L59)):*
> ```Go
> 		sessiondatapb.SessionData{},
> 	)
> 	return p.(*planner)
> ```

nit: revert
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 148 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6Fh61D82c9J4rMRMg:-MU6Fh62D5R3TtkIkKJW:b77je2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/schemachanger/scbuild/builder_test.go#L148)):*
> ```Go
> 		// way doesn't seem to do what we want.
> 		sessiondatapb.SessionData{},
> 		nil, /* collection */
> ```

will this fail any tests? is the comment still right?


<!-- Sent from Reviewable.io -->

2021-02-22 02:03 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60596)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @lucy-zhang, @otan, and @postamar)

___
*[pkg/sql/planner.go, line 249 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FFBa11nWkpWdROJ2:-MU6MGoP39P7F9wWqtNv:b-ukcyt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L249)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i usually like prefixing the option like so: `InternalPlannerParamsOption(With)DescCollection` so it's searchable easily with just the prefix (but it can be a bit long)
</blockquote></details>

IMO the readability of what I have rn outweighs the searchable aspect, unless you really insist. 
___
*[pkg/sql/planner.go, line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6F8VYDiGBN1jnGu00:-MU6MSUqA9mHv4FyNrsU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L257)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i would nix the new comment, or at the very least, fix the `ovveride` typo :P 
</blockquote></details>

Done.
___
*[pkg/sql/planner.go, line 298 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FWR2DuMIX2NlTaq-:-MU6S6xc8wytaBJatrRV:b-96x1yu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/planner.go#L298)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

can we thread the options into here to avoid this new struct?
</blockquote></details>

Talked offline, threaded the options but made the new struct internal as opposed to getting rid of it (in the hope that people might extend it in the future). 
___
*[pkg/sql/values_test.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6FehQ0wdulqyyA3Rt:-MU6QoKm8VKG1NzqYfEy:b-c6j09p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/values_test.go#L59)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: revert
</blockquote></details>

I need this because I changed the call from `newInternalPlanner`(which returns a planner)  to `NewInternalPlanner` (which returns an interface). Don't really need the switch now that Ive passed the options down, but now that I've cleaned up all accesses to `newInternalPlanner` to go through the public method, Im inclined to just leave it as is.  
___
*[pkg/sql/schemachanger/scbuild/builder_test.go, line 148 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60596#-MU6Fh61D82c9J4rMRMg:-MU6Mlu9DO6M9u1FtHGj:b-7bkejf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f3767d372650807b2486e17145332cbe8faf3ae/pkg/sql/schemachanger/scbuild/builder_test.go#L148)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

will this fail any tests? is the comment still right?
</blockquote></details>

Detritus, fixed. 


<!-- Sent from Reviewable.io -->

2021-02-22 02:07 UTC, arulajmani commented
TFTRs!

bors r=otan,ajstorm

2021-02-22 03:02 UTC, arulajmani commented
bors r+

2021-02-22 03:55 UTC, merged