server: added initial cert utilities for automatic cert generation
cockroachdb/cockroach pull request #60705
Opened 2021-02-17 21:45 UTC by aaron-crl

security: added helper functions to support automatic certificate generation

This doesn't do anything yet but will be updated to trigger off:
https://github.com/cockroachdb/cockroach/pull/60636 when it lands.

Release note: None

2021-02-17 21:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60705)
<!-- Reviewable:end -->

2021-02-18 10:06 UTC, stevendanna reviewed
Neat! I left some comments, but many are for my own edification rather than blockers.

2021-02-18 12:59 UTC, knz reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpBzTu7YneMklv46lA:-MTpBzTu7YneMklv46lB:bb5l6r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L30)):*
> ```Go
> // with cluster auto certificate generation.
> func CreateCACertAndKey(lifespan time.Duration, service string) (certPEM []byte, keyPEM []byte, err error) {
> 	// This function creates a short lived initial CA for node initialization
> ```

nit: here and throughout the PR: comments are to contain only fully formed sentences, with capitals at the beginning and a period at the end.
___
*[pkg/security/auto_tls_init.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-32:-MTpBqIG-SnhLNLzcZI7:b-4mlwj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L32)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I haven't had a chance to read through the RFC yet, but if we are using this cert quickly after creating in a cluster setting where we might have clock drift, we might consider setting this a few seconds in the past to avoid confusing errors.
</blockquote></details>

Agreed with Steven here.
(Also you'll want `timeutil.Now()`  not `time.Now()` - we have clock overrides)
___
*[pkg/security/auto_tls_init.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCRSW1k7G0Wb0xO1e:-MTpCRSW1k7G0Wb0xO1f:b-y20uy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L37)):*
> ```Go
> 	// create random serial number for CA
> 	max := new(big.Int)
> 	max.Exp(big.NewInt(2), big.NewInt(130), nil).Sub(max, big.NewInt(1))
> ```

please extract the generation of these bignums into a helper function and reuse it here and below
___
*[pkg/security/auto_tls_init.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-40:-MTpC7ME3AZbAxZdjHv9:b-8v4stl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L40)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Are we sure we want to use fatal here rather than returning an error?  Fatal will call `os.Exit(1)`.
</blockquote></details>

agreed this deserves an error

also, nit: all the logging and error stuff returns messages that are not sentences, so do not start with a capital and do not end with a period
___
*[pkg/security/auto_tls_init.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCHqLB74giWBEKMsV:-MTpCHqLB74giWBEKMsW:bo18l2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L59)):*
> ```Go
> 
> 	// create private and public key
> 	caPrivKey, err := rsa.GenerateKey(rand.Reader, 4096)
> ```

we don't use magic constants in the code, so this 4096 needs to be extracted into a named constant and documented.
___
*[pkg/security/auto_tls_init.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCOvgCYZu7b-9nnaT:-MTpCOvgCYZu7b-9nnaU:b-aqbkna) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L92)):*
> ```Go
> // This is a utility function to help with cluster auto certificate generation
> func CreateServiceCertAndKey(lifespan time.Duration, service, hostname string, caCertPEM []byte, caKeyPEM []byte) (certPEM []byte, keyPEM []byte, err error) {
> ```

nit: no empty space at the start of functions
___
*[pkg/security/auto_tls_init.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCWzw6OOlT8vRvyaN:-MTpCWzw6OOlT8vRvyaO:b-77yzyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L99)):*
> ```Go
> 	// create random serial number for CA
> 	max := new(big.Int)
> 	max.Exp(big.NewInt(2), big.NewInt(130), nil).Sub(max, big.NewInt(1))
> ```

reuse helper function
___
*[pkg/security/auto_tls_init.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-137:-MTpCcyt9S8NH-WaFrCU:b8uihbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L137)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Are we guaranteed to have a hostname here?  Looking at the callsite that isn't clear to me.

Perhaps we could do something like:

```golang
ip := net.ParseIP(hostname)
if ip != nil {
    serviceCert.IPAddresses = []net.IP{ip}
} else {
    serviceCert.DNSNames = []string{hostname}
}
```
</blockquote></details>

I would recommend passing this via configuration so it can be overridden from the command line. However, for the very first version of the PR, let's just leave a TODO in a comment here, and add a follow up item to #60632. 
___
*[pkg/security/auto_tls_init.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCq1y9zHi0qZu2dWL:-MTpCq1z8E747ggUzTrR:bsir7v1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L144)):*
> ```Go
> 	}
> 
> 	servicePrivKey, err := rsa.GenerateKey(rand.Reader, 4096)
> ```

see comment above about constant
___
*[pkg/server/auto_tls_init.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCwzI5K-vzOOZP5dG:-MTpCwzI5K-vzOOZP5dH:b-e4jrvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/server/auto_tls_init.go#L12)):*
> ```Go
> 
> // TODO(aaron-crl): This uses the CertsLocator from the security package
> // Getting about half way to integration with the certificate manager
> ```

nit: missing period

also throughout the rest of this file
___
*[pkg/server/auto_tls_init.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpD3Pa1n6AAlL0XqHe:-MTpD3Pa1n6AAlL0XqHf:bks8r3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/server/auto_tls_init.go#L80)):*
> ```Go
> 		if _, err = os.Stat(caKeyPath); !os.IsNotExist(err) {
> 			// key exist, this is an error
> 			err = errors.New("found key but not certificate for user auth at " + caKeyPath)
> ```

`errors.Newf("found ... %s", caKeyPath)`

Might want to use `errors.Wrap` / `Wrapf` too.
___
*[pkg/server/auto_tls_init.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpDA4G7BHrF6-rxSvp:-MTpDA4G7BHrF6-rxSvq:b-88jmt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/server/auto_tls_init.go#L134)):*
> ```Go
> 		if _, err = os.Stat(serviceKeyPath); os.IsNotExist(err) {
> 			// cert exists but key doesn't, this is an error
> 			err = errors.New("failed to load service certificate key for " + serviceCertPath + "expected key at " + serviceKeyPath)
> ```

`errors.Newf`, here and below or `Wrapf`


<!-- Sent from Reviewable.io -->

2021-02-18 15:12 UTC, aaron-crl reviewed
Thanks for the feedback @stevendanna and @knz !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MTpgOib19J-e5livv66:bcydn6d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpBzTu7YneMklv46lA:-MTpdqGWDshk2WEEpScG:btgptwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: here and throughout the PR: comments are to contain only fully formed sentences, with capitals at the beginning and a period at the end.
</blockquote></details>

Thanks! I _think_ I got all of these.
___
*[pkg/security/auto_tls_init.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-32:-MTpePMJ3CFo6eTAjlNH:b-d8fu6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L32)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Agreed with Steven here.
(Also you'll want `timeutil.Now()`  not `time.Now()` - we have clock overrides)
</blockquote></details>

Thanks! Addressed both.
___
*[pkg/security/auto_tls_init.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCRSW1k7G0Wb0xO1e:-MTpeSXH9Zx5c_hNmHCR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please extract the generation of these bignums into a helper function and reuse it here and below
</blockquote></details>

Done.
___
*[pkg/security/auto_tls_init.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-40:-MTpeUCWDmAx2yiE_ZCE:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

agreed this deserves an error

also, nit: all the logging and error stuff returns messages that are not sentences, so do not start with a capital and do not end with a period
</blockquote></details>

Thanks, done.
___
*[pkg/security/auto_tls_init.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-55:-MTpe_v3C5u3ORbfjyIA:bj3eodx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L55)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we want `MaxPathLenZero: true` as well? I believe we do if we don't intend to have any intermediate certificates issued.
</blockquote></details>

Fixed, thanks!
___
*[pkg/security/auto_tls_init.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCHqLB74giWBEKMsV:-MTpeck18K3w9dqdAWuZ:blg5hf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L59)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

we don't use magic constants in the code, so this 4096 needs to be extracted into a named constant and documented.
</blockquote></details>

Done as an unexported const. Let me know if we have a different preference for this.
___
*[pkg/security/auto_tls_init.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCOvgCYZu7b-9nnaT:-MTpf1103GrbstULfJLI:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: no empty space at the start of functions
</blockquote></details>

Thanks, fixed.
___
*[pkg/security/auto_tls_init.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCWzw6OOlT8vRvyaN:-MTpf5Xm8x3ofqSguuFy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

reuse helper function
</blockquote></details>

Done.
___
*[pkg/security/auto_tls_init.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-102:-MTpf6gACQgsgPLSyG-q:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L102)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Same question about log.Fatal here.
</blockquote></details>

Fixed.
___
*[pkg/security/auto_tls_init.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-137:-MTpfBaw1-PzQJ7xKHzn:boicpsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L137)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would recommend passing this via configuration so it can be overridden from the command line. However, for the very first version of the PR, let's just leave a TODO in a comment here, and add a follow up item to #60632. 
</blockquote></details>

Added this logic but also placed a comment for follow up as I think that will probably give us the best mileage.
___
*[pkg/security/auto_tls_init.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTlxBWz5ovyHealSX9R-r1-141:-MTpfNNnCNUIHdPuQATE:byyk5b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L141)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need `x509.KeyUsageKeyEncipherment` as well? I ask because I see we support plain RSA key exchange here

https://github.com/cockroachdb/cockroach/blob/8187c2551352a6c28eba021effaebcbfe523d78c/pkg/security/tls.go#L185-L188

(aside: we might consider an issue for making that list configurable or removing the CBC-mode ciphers from the list)

Either way, perhaps a few comments in these template creations to document why or why not might be useful to us in the future?
</blockquote></details>

Good catch, thank you. Updated the KeyUsage for now and left comment regarding consolidation of this with the existing infrastructure.
___
*[pkg/security/auto_tls_init.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCq1y9zHi0qZu2dWL:-MTpfdLQ9UAP0j0XoKWn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/security/auto_tls_init.go#L144)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

see comment above about constant
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init.go, line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpCwzI5K-vzOOZP5dG:-MTpfef91chJzCirwCNR:b-vt7lih) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/server/auto_tls_init.go#L12)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: missing period

also throughout the rest of this file
</blockquote></details>

Think I got all of these.
___
*[pkg/server/auto_tls_init.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTpD3Pa1n6AAlL0XqHe:-MTpfhfm3s-jko_oJbzz:b4855pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5f40ee551f7b579369d3c2706bf2f2c754aa69a/pkg/server/auto_tls_init.go#L80)):*
< [...]

2021-02-18 21:27 UTC, aaron-crl reviewed
I've added the bundler utility function. I'll see if I can get the symmetric unbundler done this evening but that can wait for the next PR.

@knz PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MTr1OTFE6rK-FhA6oQc:b-pn10t7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-02-19 22:01 UTC, itsbilal requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIfIGCKsOD5lsHE3M:-MTwIfIGCKsOD5lsHE3N:b-5hv313) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L117)):*
> ```Go
> 	serialNumber, err := createCertificateSerialNumber()
> 	if err != nil {
> 		return
> ```

It's best not to do unnamed returns as bugs creep in that way; just do `return nil, nil, err` here to make it explicit to the reader.
___
*[pkg/security/auto_tls_init.go, line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIWdW00lVFfz_11Qw:-MTwIWdW00lVFfz_11Qx:b4t2oba) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L138)):*
> ```Go
> 	}
> 
> 	caKey, err := x509.ParsePKCS8PrivateKey(caKeyBlock.Bytes)
> ```

This should be PKCS1 to match the the encode step, right?
___
*[pkg/security/auto_tls_init.go, line 193 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIvwdDGEchBHudrAc:-MTwIvwdDGEchBHudrAd:btorapb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L193)):*
> ```Go
> 	})
> 
> 	return
> ```

`return serviceCertBlock.Bytes(), certPrivKeyPEM.Bytes(), nil` maybe?


<!-- Sent from Reviewable.io -->

2021-02-21 17:18 UTC, aaron-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIfIGCKsOD5lsHE3M:-MU4a9093pl6CKHsmNUj:blsb720) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L117)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It's best not to do unnamed returns as bugs creep in that way; just do `return nil, nil, err` here to make it explicit to the reader.
</blockquote></details>

Thanks, fixed and error behavior made more explicit throughout.
___
*[pkg/security/auto_tls_init.go, line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIWdW00lVFfz_11Qw:-MU4_rEc6DU5SBuFmqQh:b-e1eue4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L138)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This should be PKCS1 to match the the encode step, right?
</blockquote></details>

Thanks, good catch, it should have been PKCS8 everywhere. I've updated accordingly.
___
*[pkg/security/auto_tls_init.go, line 193 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MTwIvwdDGEchBHudrAc:-MU4a0Wu5JHh48sKPbsz:bbwr6sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3707ea80f48df53a905c64f4a7d0f75c6c679689/pkg/security/auto_tls_init.go#L193)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

`return serviceCertBlock.Bytes(), certPrivKeyPEM.Bytes(), nil` maybe?
</blockquote></details>

Thank you and apologies. Fixed and updated errors to be explicit throughout this an related function.


<!-- Sent from Reviewable.io -->

2021-02-21 17:39 UTC, knz reviewed
This is mostly good to go. Thanks for all the polish.
Don't forget to squash everything before this merges though.

> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MU4f9NjAmPcn7j_VdPB:b-qca44t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4e-YH8493TMVlr_1r:-MU4e-YH8493TMVlr_1s:b-ylh2gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L39)):*
> ```Go
> func createCertificateSerialNumber() (serialNumber *big.Int, err error) {
> 	max := new(big.Int)
> 	max.Exp(big.NewInt(2), big.NewInt(130), nil).Sub(max, big.NewInt(1))
> ```

If my reading is right, this generates a random value between 1 and 2^130-1, i.e. between 1 and 1361129467683753853853498429727072845823.

Is that intended? If so, please fix the comment to indicate the actual range.

If you want a 31-bit random number, you can use `rand.Int31()`.
___
*[pkg/server/auto_tls_init.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4els888wV4zieh3A_:-MU4els888wV4zieh3Aa:b-fiifhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L81)):*
> ```Go
> 			// Key exists but cert does not, this is an error.
> 			err = errors.Wrapf(err,
> 				"found key but not certificate for user auth at: %s"+caKeyPath)
> ```

remove the + and replace by a comma.
___
*[pkg/server/auto_tls_init.go, line 247 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4euTLA_Q2PgXqRSBi:-MU4euTLA_Q2PgXqRSBj:b48vypy) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L247)):*
> ```Go
> // cluster. It uses or generates an InterNode CA to produce any missing
> // unmanaged certificates. It does this base on the logic in:
> // https://github.com/aaron-crl/cockroach/blob/rfc20200722_cert_free_secure_setup/docs/RFCS/20200722_certificate_free_secure_setup.md#initial-configuration-establishing-trust
> ```

Please refer to the RFC by PR URL, not this blob path (this will be auto-deleted when the RFC PR is merged).
___
*[pkg/server/auto_tls_init.go, line 253 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4f01b5Mlt2grArm1a:-MU4f01b5Mlt2grArm1b:b-fu4w93) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L253)):*
> ```Go
> 	cl := security.MakeCertsLocator(c.SSLCertsDir)
> 	// TODO(aaron-crl): Put this in the config map.
> 	initLifespan, err := time.ParseDuration("366d")
> ```

No magic constants: extract in a global constant at the top and document. Possibly add a TODO to make it configurable.


<!-- Sent from Reviewable.io -->

2021-02-21 17:49 UTC, knz commented
You can solve the linter failure with `make bazel-generate` and committing the resulting changes to the BUILD.bzl files.

2021-02-21 18:27 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4q-gVAAi-1_BWBzXd:-MU4q-gVAAi-1_BWBzXe:bbzxdm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L139)):*
> ```Go
> 	caCert, err := x509.ParseCertificate(caCertBlock.Bytes)
> 	if err != nil {
> 		err = errors.New("failed to parse valid Certificate from PEM blob")
> ```

errors.Wrap here
___
*[pkg/security/auto_tls_init.go, line 151 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4puwBBVV3kC_oX1nL:-MU4puwBBVV3kC_oX1nM:bmlujrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L151)):*
> ```Go
> 	caKey, err := x509.ParsePKCS8PrivateKey(caKeyBlock.Bytes)
> 	if err != nil {
> 		err = errors.New("failed to parse valid Certificate from PEM blob")
> ```

`errors.Wrap` here too


<!-- Sent from Reviewable.io -->

2021-02-21 18:38 UTC, aaron-crl reviewed
TFTR!

> Don't forget to squash everything before this merges though.

Done.

> You can solve the linter failure with make bazel-generate and committing the resulting changes to the BUILD.bzl files.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MU4rtA--CPHejaaJDnX:b-sdnnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4e-YH8493TMVlr_1r:-MU4s4JV3Pr9C6XozOKy:b-mbmak) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

If my reading is right, this generates a random value between 1 and 2^130-1, i.e. between 1 and 1361129467683753853853498429727072845823.

Is that intended? If so, please fix the comment to indicate the actual range.

If you want a 31-bit random number, you can use `rand.Int31()`.
</blockquote></details>

Updated comment. The intention was to have a crypto random serial with greater than 128 bits of entropy in case we decided to rely on the serial for something at some point in the future.
___
*[pkg/security/auto_tls_init.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4q-gVAAi-1_BWBzXd:-MU4sRrIAXVDAIrU3o7w:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L139)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

errors.Wrap here
</blockquote></details>

Thanks, done.
___
*[pkg/security/auto_tls_init.go, line 151 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4puwBBVV3kC_oX1nL:-MU4sUh5Dktu-nUmMojH:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L151)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.Wrap` here too
</blockquote></details>

Thanks, done.
___
*[pkg/server/auto_tls_init.go, line 81 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4els888wV4zieh3A_:-MU4sWX68DKSbhlGbZID:b-jyyewy) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L81)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

remove the + and replace by a comma.
</blockquote></details>

Good catch, thanks, done.
___
*[pkg/server/auto_tls_init.go, line 247 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4euTLA_Q2PgXqRSBi:-MU4sZlk0w-N3TnXmXBv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L247)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please refer to the RFC by PR URL, not this blob path (this will be auto-deleted when the RFC PR is merged).
</blockquote></details>

Done.
___
*[pkg/server/auto_tls_init.go, line 253 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4f01b5Mlt2grArm1a:-MU4s_xV6AnUWMfZNwod:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/server/auto_tls_init.go#L253)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

No magic constants: extract in a global constant at the top and document. Possibly add a TODO to make it configurable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-21 18:45 UTC, knz approved these changes
LGTM modulo getting the serial number right

> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MU4uDLr9zyyQpostktp:b-nmh7b1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4e-YH8493TMVlr_1r:-MU4tQ7hDS-ejcWb3frU:b-eeb5xx) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L39)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Updated comment. The intention was to have a crypto random serial with greater than 128 bits of entropy in case we decided to rely on the serial for something at some point in the future.
</blockquote></details>

`rand.Int` generates a value between 0 *included* and max *excluded*

I think you want to call `rand.Int`  like you do today, this will generate a value between [0, 2^130-1)
Then *add one to the result* to get a value between [1, 2^130)
___
*[pkg/security/auto_tls_init.go, line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4u2Y6ENFwMp5qXca7:-MU4u2Y6ENFwMp5qXca8:b-wyeho9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e212b6db66fee097b40c62f111150499e7aa10bf/pkg/security/auto_tls_init.go#L36)):*
> ```Go
> 
> // createCertificateSerialNumber is a helper function that generates a
> // random value between 1 and 2^130-1.
> ```

specify whether the bounds are inclusive or exclusive in the comment.
___
*[pkg/security/auto_tls_init.go, line 51 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4u0dw0ZP7lUGJdJfB:-MU4u0dw0ZP7lUGJdJfC:bxkd75d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e212b6db66fee097b40c62f111150499e7aa10bf/pkg/security/auto_tls_init.go#L51)):*
> ```Go
> // with cluster auto certificate generation.
> func CreateCACertAndKey(lifespan time.Duration, service string) (certPEM []byte, keyPEM []byte, err error) {
> ```

nit: remove empty space


<!-- Sent from Reviewable.io -->

2021-02-21 19:16 UTC, aaron-crl commented
I think I got the serial right this time; also added intent to the comments. Thanks for the patience.

2021-02-21 21:55 UTC, knz commented
ok you got yourself some linter errors now

For the unused functions you can have some empty assignments in a `_test.go` file, e.g. `var _ = YourUnusedFunction`

2021-02-22 00:18 UTC, aaron-crl reviewed
Thanks! I wasn't using my local linters right. I'll wait to squash things until we get a green light from the CI linters.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-:-MU64oQB546azGrnNV0F:b-jp7dvs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 39 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4e-YH8493TMVlr_1r:-MU65P5_5QhWx4SYNm1S:bnwgrm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/18ea0eee98f10477fb1f40c42a5ff0136bc363cc/pkg/security/auto_tls_init.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`rand.Int` generates a value between 0 *included* and max *excluded*

I think you want to call `rand.Int`  like you do today, this will generate a value between [0, 2^130-1)
Then *add one to the result* to get a value between [1, 2^130)

</blockquote></details>

Thanks, updated comment and code.
___
*[pkg/security/auto_tls_init.go, line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4u2Y6ENFwMp5qXca7:-MU65MO986c9ULBkf2Iy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e212b6db66fee097b40c62f111150499e7aa10bf/pkg/security/auto_tls_init.go#L36)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

specify whether the bounds are inclusive or exclusive in the comment.
</blockquote></details>

Done.
___
*[pkg/security/auto_tls_init.go, line 51 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60705#-MU4u0dw0ZP7lUGJdJfB:-MU65VV96pDv1tjRzZTl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e212b6db66fee097b40c62f111150499e7aa10bf/pkg/security/auto_tls_init.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: remove empty space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 13:25 UTC, knz reviewed
> Reviewed 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60705)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-02-22 14:20 UTC, aaron-crl commented
bors r=knz

2021-02-22 14:54 UTC, merged