[WIP] server: Implement auto-init handshake to negotiate CA certs between nodes
cockroachdb/cockroach pull request #60766
Opened 2021-02-19 02:36 UTC by itsbilal

This PR implements the init protocol phase of the cert-free setup
described in #51991. A lot of the code is pulled out of Aaron's
reference implementation of this protocol:
https://github.com/aaron-crl/toy-secure-init-handshake/tree/n-way-join

One part of #60632. First couple commits are from #60705.

Ready for review, but these parts are still TODO:
- [ ] Unit tests, or at least manual test steps
- [ ] Address some of the TODOs, including rebasing on latest version of #60705 and only sending over the CAs in the trust bundle.

Release note: None.

2021-02-19 02:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60766)
<!-- Reviewable:end -->

2021-02-19 10:44 UTC, stevendanna reviewed
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @knz)

___
*[pkg/server/init_handshake.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtpH3X5HLuvZaJsz0a:-MTtpH3X5HLuvZaJsz0b:by8b582) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L44)):*
> ```Go
> 
> // internode trust delivery struct
> type nodeTrustBundle struct {
> ```

I believe the RFC calls this the "initialization-bundle".  Would it be useful to use the same name here somewhere or reference it in the comment?
___
*[pkg/server/init_handshake.go, line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtjEg0B3C7EWDjZk_q:-MTtjEg0B3C7EWDjZk_r:b-48tp8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L143)):*
> ```Go
> 		Certificates: []tls.Certificate{serverCert},
> 		RootCAs:      certpool,
> 	}
> ```

It appears that in `pkg/security/tls.go` we have a newBaseTLSConfig.  Might it be worth making some portion of that public so that all TLS servers share the same basic configuration (specifically around cipher suites, minimum TLS version, etc)?
___
*[pkg/server/init_handshake.go, line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtk1pL7j8M3MY5BtID:-MTtk1pL7j8M3MY5BtIE:biv4spt) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L169)):*
> ```Go
> 
> 	if !challenge.validHMAC(t.token) {
> 		http.Error(res, "invalid message", http.StatusBadRequest)
> ```

This error is different from the previous error return.  It might make debugging a bit harder, but would it be prudent to make sure all of the externally emitted errors from this process return something like `http.StatusUnauthorized` to prevent any potential information leakage that could be valuable to an attacker? Or at least all errors returned at and before this point in the function.
___
*[pkg/server/init_handshake.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtqYcr8OxcEG9VD69r:-MTtqYcr8OxcEG9VD69s:bef5ace) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L230)):*
> ```Go
> 		}
> 
> 		peerHostnameAndCa, err := t.getPeerCACert(peerHostname, selfAddress)
> ```

Do we need logging around errors here?  Or rather, how would connectivity issues between the nodes surface to the user?
___
*[pkg/server/init_handshake.go, line 364 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtpQoR-c_6KxRCtrZH:-MTtpQoR-c_6KxRCtrZI:b2oq14z) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L364)):*
The RFC says:

> Once this bundle is created, this node uses the public key for each peer's CA to create strong TLS connections to each peer using their trusted CA and deliver the initialization-bundle in addition to a MAC of the bundle generated with the initialization-token to prove authenticity.

Here, our MAC covers just the CACertificate and CAKey rather than the entire bundle.  I haven't thought through whether that is sufficient. If it is sufficient, we should update the RFC. If it isn't, we should update this code.

It might be nice to have a function on nodeTrustBundle{} that computes the HMAC so we could use it both here and at validTrustBundle().
___
*[pkg/server/init_handshake.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtsfRw4ZXlSEnt-83x:-MTtsfRw4ZXlSEnt-83y:b-h0c2b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L375)):*
> ```Go
> 	}
> 	select {
> 	case <-handshaker.finishedInit:
> ```

What writes to finishedInit in the case of the trustLeader? I'm not seeing it, but perhaps I missed it.


<!-- Sent from Reviewable.io -->

2021-02-19 20:52 UTC, itsbilal reviewed
Thanks for the review, Steven! Addressed most comments, and rebased on the latest iteration of the base branch. I'll add the tests shortly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MTw327s8CjO7t_IWfep:bcvli2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 44 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtpH3X5HLuvZaJsz0a:-MTvz7T-3qVMeUT0eA-e:b-5hqb5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L44)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I believe the RFC calls this the "initialization-bundle".  Would it be useful to use the same name here somewhere or reference it in the comment?
</blockquote></details>

Done. Referenced it in the comment.
___
*[pkg/server/init_handshake.go, line 169 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtk1pL7j8M3MY5BtID:-MTvOJjw2nCsvROt4ZWe:bpdpd7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L169)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

This error is different from the previous error return.  It might make debugging a bit harder, but would it be prudent to make sure all of the externally emitted errors from this process return something like `http.StatusUnauthorized` to prevent any potential information leakage that could be valuable to an attacker? Or at least all errors returned at and before this point in the function.
</blockquote></details>

I wanted to treat the previous one as an internal error, and this one as a user error, but now that I think about it, both are malformed requests so I'll return a 400 bad request and the same message for both of them. 
___
*[pkg/server/init_handshake.go, line 230 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtqYcr8OxcEG9VD69r:-MTvFs6SCQHxR_WCoh9q:br84o7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L230)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Do we need logging around errors here?  Or rather, how would connectivity issues between the nodes surface to the user?
</blockquote></details>

Good point. Added a log message. Currently it'd just wait forever until the timeout, which is way more opaque than it should be.
___
*[pkg/server/init_handshake.go, line 364 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtpQoR-c_6KxRCtrZH:-MTw2ye61X6MNmidhiRJ:bxdny0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L364)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

The RFC says:

> Once this bundle is created, this node uses the public key for each peer's CA to create strong TLS connections to each peer using their trusted CA and deliver the initialization-bundle in addition to a MAC of the bundle generated with the initialization-token to prove authenticity.

Here, our MAC covers just the CACertificate and CAKey rather than the entire bundle.  I haven't thought through whether that is sufficient. If it is sufficient, we should update the RFC. If it isn't, we should update this code.

It might be nice to have a function on nodeTrustBundle{} that computes the HMAC so we could use it both here and at validTrustBundle().
</blockquote></details>

Done. Also did the helper. Thanks for catching that discrepancy.
___
*[pkg/server/init_handshake.go, line 375 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtsfRw4ZXlSEnt-83x:-MTvG-3sA_dGfw4QsZ_w:bt48gid) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L375)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

What writes to finishedInit in the case of the trustLeader? I'm not seeing it, but perhaps I missed it.
</blockquote></details>

Done. Good catch, I meant to add this under an "else" above, but missed it.


<!-- Sent from Reviewable.io -->

2021-02-19 22:54 UTC, itsbilal commented
Also added a unit test for the simple / correct case. Will expand it to include cases where the tokens don't match.

2021-02-21 17:46 UTC, knz reviewed
Very nice. You'll want to rebase to pick up the latest changes from #60705.

> Reviewed 2 of 4 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MU4giAgExeHgebcRJCY:bn55sag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 38 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4fvHg9C5fec3eBgtw:-MU4fvHg9C5fec3eBgtx:bpy07dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L38)):*
> ```Go
> var errInvalidHMAC = errors.New("invalid HMAC signature")
> 
> // Blob used for symetric exchange of node public CA keys.
> ```

nit: symmetric
___
*[pkg/server/init_handshake.go, line 195 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gYZb9IBMHTOhPvF8:-MU4gYZb9IBMHTOhPvF9:bcsupu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L195)):*
> ```Go
> 	var challenge nodeHostnameAndCA
> 
> 	// TODO(aaron-crl): [Security] make this more error resilient to size and shape attacks
> ```

nit: period at end of sentence.
___
*[pkg/server/init_handshake.go, line 208 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4g_Wc0r3Bpi4_K0z5:-MU4g_Wc0r3Bpi4_K0z6:bgbnq1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L208)):*
> ```Go
> 	}
> 
> 	// send the valid node infomation to the trustedPeers channel
> ```

nit: here and below full sentences in comment.
___
*[pkg/server/init_handshake.go, line 257 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gdGSA9mzNNzI31hd:-MU4gdGSA9mzNNzI31he:bcsupu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L257)):*
> ```Go
> 
> func (t *tlsInitHandshaker) getPeerCACert(peerAddress string, selfAddress string) (nodeHostnameAndCA, error) {
> 	// TODO(aaron-crl): [Enhancement] add TLS protocol level checks to make sure remote certificate matches preferred one
> ```

nit: period at end of sentence.
___
*[pkg/server/init_handshake.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gHE8B7ZSZgkjfr6d:-MU4gHE8B7ZSZgkjfr6e:b-jlcc71) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L273)):*
> ```Go
> 	var body bytes.Buffer
> 	_ = json.NewEncoder(&body).Encode(challenge)
> 	res, err := client.Post("https://"+peerAddress+"/trustInit/", "application/json; charset=utf-8", &body)
> ```

Here and below: extract the URL paths in global constants. Also use the same constants in the server URL routing logic.


<!-- Sent from Reviewable.io -->

2021-02-21 18:20 UTC, knz commented
cc @aaron-crl 

As I started working on the next bit of server code, I encountered a design mismatch in the interface of `server.InitHandshake`. Currently this conflates the number of expected peers with the size of the `peer` array.

This a problem: in practice, folk with orchestration can pass the list of peers via a wildcard address. Also we may not have symmetric join lists.  Also we want eventually to support resolution via SRV records.

I think that semantically, the only thing that matters is that _eventually_ there are N nodes connected, where N is the number of expected peers.   If one of the outgoing connect() calls fails, it's not a problem - maybe there were more peer addresses specified than expected. If there are fewer peer addresses than expected peers, that is also OK - perhaps there will be peers connecting back to the node instead.

So I think it would be better to pass the number of expected peers separately from the array of peer addresses.

2021-02-21 18:25 UTC, knz commented
Regarding this last point, I added a commit in #60854 to do the interface change.

2021-02-21 18:28 UTC, knz reviewed
NB: the new test TestInitHandshake fails when rebased on top of the latest #60705 however the error indicates why:
```
--- FAIL: TestInitHandshake (0.38s)
    test_log_scope.go:73: test logs captured to: /tmp/logTestInitHandshake534579817
    test_log_scope.go:74: use -show-logs to present logs inline
    init_handshake_test.go:68:
                Error Trace:    init_handshake_test.go:68
                Error:          Received unexpected error:
                                failed to create certificates: failed to parse valid Certificate from PEM blob: x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)
                                (1) attached stack trace
                                  -- stack trace:
                                  | github.com/cockroachdb/cockroach/pkg/server.InitHandshake
                                  |     /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/server/init_handshake.go:365
                                  | [...repeated from below...]
                                Wraps: (2) failed to create certificates
                                Wraps: (3) attached stack trace
                                  -- stack trace:
                                  | github.com/cockroachdb/cockroach/pkg/security.CreateServiceCertAndKey
                                  |     /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/security/auto_tls_init.go:155
                                  | github.com/cockroachdb/cockroach/pkg/server.createNodeInitTempCertificates
                                  |     /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/server/init_handshake.go:134
                                  | github.com/cockroachdb/cockroach/pkg/server.InitHandshake
                                  |     /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/server/init_handshake.go:363
                                  | github.com/cockroachdb/cockroach/pkg/server.TestInitHandshake.func1
                                  |     /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/server/init_handshake_test.go:55
                                  | runtime.goexit
                                  |     /usr/local/go/src/runtime/asm_amd64.s:1371
                                Wraps: (4) failed to parse valid Certificate from PEM blob
                                Wraps: (5) x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)
                                Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *errors.errorString
                Test:           TestInitHandshake
    panic.go:613: -- test log scope end --

```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MU4qFwJ9BScH66kVsan:b497dwu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-02-22 16:15 UTC, itsbilal reviewed
Thanks for doing that change in your PR! I'll leave the interface unchanged to make it easier for you. And that test seems to be working for me, even post-rebase. Trick is to borrow all of Aaron's changes in `pkg/security` and ditch any that I made in this branch, as they were just a temporary hack. Latest push to this PR has that cleaned up and rebased on master.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MU9VMpVDko9HTLsHz-1:b1yalxr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 143 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MTtjEg0B3C7EWDjZk_q:-MU9Vhcp6Bucth3tKlee:b6y9lwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/314a17ccf13749313aaadfeb6aaad62dca18eee4/pkg/server/init_handshake.go#L143)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

It appears that in `pkg/security/tls.go` we have a newBaseTLSConfig.  Might it be worth making some portion of that public so that all TLS servers share the same basic configuration (specifically around cipher suites, minimum TLS version, etc)?
</blockquote></details>

I can leave this as a TODO for now. It'll require a bit of a refactor of things there.
___
*[pkg/server/init_handshake.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gHE8B7ZSZgkjfr6d:-MU9WMFS95OGwqhtNfRW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L273)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Here and below: extract the URL paths in global constants. Also use the same constants in the server URL routing logic.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 16:29 UTC, aaron-crl requested changes
It looks like you might not have cleanly dropped all changes against `pkg/security`. Maybe you missed a commit?

Also, some of the code copied from my reference implementation has poor comment hygiene (missing capital letter at start and punctuation at the end). Let me know if you want me to toss you a PR fixing that after the rebase is cleaned up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MU9Y8sb9_Y2qwda_tnE:bujj32g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU9XX0l4HPlC9XRKYXK:-MU9XX0l4HPlC9XRKYXL:b-31ev20) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4f3525c17edea5b54d72efaf7dab90cdaaebc2/pkg/security/auto_tls_init.go#L36)):*
> ```Go
> 
> // createCertificateSerialNumber is a helper function that generates a
> // random value between 1 and 2^31.
> ```

It looks like here and throughout the file this has reverted the `pkg/security/auto_tls_init.go` changes against `master`.
___
*[pkg/server/init_handshake.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gHE8B7ZSZgkjfr6d:-MU9Z7OL1Rad4V2hOkYp:bday15n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L273)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Am I misunderstanding or did this change not stick?


<!-- Sent from Reviewable.io -->

2021-02-22 17:23 UTC, itsbilal reviewed
My bad - I didn't drop everything in `pkg/security`. Fixing.

All the comments should be already fixed though. Let me know if I missed some. Also added the mismatching-token case, so I'll drop the WIP moniker from this PR now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MU9_9D5AcSv9pdXGfsd:br3qj32)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @knz, and @stevendanna)

___
*[pkg/security/auto_tls_init.go, line 36 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU9XX0l4HPlC9XRKYXK:-MU9_DkJ2skvfqeYLANS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4f3525c17edea5b54d72efaf7dab90cdaaebc2/pkg/security/auto_tls_init.go#L36)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

It looks like here and throughout the file this has reverted the `pkg/security/auto_tls_init.go` changes against `master`.
</blockquote></details>

Done.
___
*[pkg/server/init_handshake.go, line 273 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU4gHE8B7ZSZgkjfr6d:-MU9_F4w4pvPggVlRgLO:b-dr5tul) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ae7b43ab3a1823450c574eeb33962534c929b92/pkg/server/init_handshake.go#L273)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Am I misunderstanding or did this change not stick?
</blockquote></details>

Yep, my bad. Juggling too many changes here right now.


<!-- Sent from Reviewable.io -->

2021-02-22 21:32 UTC, itsbilal commented
Latest push swaps out `serverListenAddr` and `serverListenPort` for a Listener. Seems like this was necessary to make tests work; TeamCity wasn't liking tests listening on a fixed host/port.

2021-02-22 22:20 UTC, aaron-crl reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 401 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU9mDa_79pQ-8pWHU7e:-MU9mDa_79pQ-8pWHU7f:b-8z77qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f5da2821845558a77f15724ad0befa746fc4fd/pkg/server/init_handshake.go#L401)):*
> ```Go
> 	}
> 
> 	// wait until we have numNodes - 1 valid peers
> ```

nit: Comment should be a complete sentence.
___
*[pkg/server/init_handshake.go, line 254 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnI6L0BPZ1ViGouOL:-MUAnI6L0BPZ1ViGouOM:b8ousmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L254)):*
> ```Go
> 		close(t.finishedInit)
> 	}
> 	// TODO(bilal): Save bundle to certs directory.
> ```

I think you can use `InitializeNodeFromBundle` for this now.
___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUAnc_0E7R5qY6vqufm:b-xacc1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
> ```Go
> 		// For each peer, use its CA to establish a secure connection and deliver the trust bundle.
> 		for p := range peerCACerts {
> 			if err := sendSecret(p, peerCACerts[p], trustBundle); err != nil {
> ```

This is one of the places where a locked cluster may manifest where a peer has restarted or been replaced. If the TLS handshake fails it means that the original node is no longer at that address or there's a man-in-the-middle. We should definitely elevate this error.


<!-- Sent from Reviewable.io -->

2021-02-23 11:32 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDUfav5NCl769NJ3CC:-MUDUfav5NCl769NJ3CD:b-6zc76l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L114)):*
> ```Go
> 	expectedMac := h.Sum(nil)
> 	return hmac.Equal(expectedMac, n.HMAC)
> }
> ```

[nit] Just to avoid having to keep these lists in sync, perhaps something like:

```go
// Computes the HMAC signature based on a signature of all CA
// certificate/keys in the Bundle.
func (n *nodeTrustBundle) computeHMAC(secretToken []byte) []byte {
	h := hmac.New(sha256.New, secretToken)
	h.Write(n.Bundle.InterNode.CACertificate)
	h.Write(n.Bundle.InterNode.CAKey)
	h.Write(n.Bundle.UserAuth.CACertificate)
	h.Write(n.Bundle.UserAuth.CAKey)
	h.Write(n.Bundle.SQLService.CACertificate)
	h.Write(n.Bundle.SQLService.CAKey)
	h.Write(n.Bundle.RPCService.CACertificate)
	h.Write(n.Bundle.RPCService.CAKey)
	h.Write(n.Bundle.AdminUIService.CACertificate)
	h.Write(n.Bundle.AdminUIService.CAKey)
	return h.Sum(nil)
}

// Sets the HMAC signature field in n based on a signature of all CA
// certificate/keys in the Bundle. Converse of validHMAC.
func (n *nodeTrustBundle) signHMAC(secretToken []byte) {
	n.HMAC = n.computeHMAC(secretToken)
}


// Verifies the HMAC signature field set in n to match that of the bundled
// CA certificates and fields. Converse of signHMAC.
func (n *nodeTrustBundle) validHMAC(secretToken []byte) bool {
        expectedMac := n.computeHMAC(secretToken)
	return hmac.Equal(expectedMac, n.HMAC)
}

```
___
*[pkg/server/init_handshake.go, line 117 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDVlSb7g_kcfOtwVTV:-MUDVlSb7g_kcfOtwVTW:b-f5wenr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L117)):*
> ```Go
> 
> // Helper function to extract signatures.
> func pemToSignature(caCertPEM []byte) (signature []byte, err error) {
> ```

[question]  I know the named returns can be nice as a sort of documentation of the return signature, but since we are using explicit returns now, might it be good to avoid the named return arguments here to prevent any unexpected problems in the future?  What is our usual code style here?
___
*[pkg/server/init_handshake.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDYCwaAsQpa9y0Hpvf:-MUDYCwb6Nfb-UIVMy9b:b-nf4gwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L336)):*
> ```Go
> 			// Non-blocking channel send.
> 			select {
> 			case t.errors <- err:
> ```

Whose reading this channel?
___
*[pkg/server/init_handshake.go, line 374 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDYkyM4EOBituhDqrK:-MUDYkyM4EOBituhDqrL:btq4unw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L374)):*
> ```Go
> 		}
> 		var body bytes.Buffer
> 		_ = json.NewEncoder(&body).Encode(caBundle)
> ```

I imagine it would be rare, but any reason not to handle the error here?

Also, I wonder if it would be worth it here to construct a bytes.Reader from this buffer so that we could do this encoding once outside the loop and leek to the beginning on retry.
___
*[pkg/server/init_handshake.go, line 410 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDd1Wi6SpYKIUMu3Ei:-MUDd1Wi6SpYKIUMu3Ej:bh12ym3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L410)):*
> ```Go
> 	default:
> 		return errors.New("unsupported listener protocol: only TCP listeners supported")
> 	}
> ```

As far as I can tell, listenPort and listenAddr/listenHost are only ever used to construct an address in the form of host:port.  I wonder if it would make sense for this function to take a string listenerAddr directly or call `listener.Addr().String()` and use what it returns. I see that this change was made for testing, but I think either of these strategies could work for testing.

I mention this because I'm a bit concerned that constructing addresses with `Sprintf("%s:%d", host, port)` won't work well in IPv6 environments when the user has given us IP addresses rather than hostnames.
___
*[pkg/server/init_handshake_test.go, line 67 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDWe5412rfWAATzeKI:-MUDWe5412rfWAATzeKJ:b-we2yyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake_test.go#L67)):*
> ```Go
> 
> 	listener1, err := net.Listen("tcp", "127.0.0.1:0")
> 	if err != nil {
> ```

You could use `require.NoError` here as you did above.  Similarly for the next few error handling cases below.


<!-- Sent from Reviewable.io -->

2021-02-23 17:18 UTC, itsbilal commented
Sorry for the repeat force-pushes - I was able to isolate the CI failure to just be significantly slower cert generation on teamcity than elsewhere. I'll bump up timeouts to account for that.

I'll ping this PR again when it's ready to review and I've addressed all the open comments.

2021-02-23 19:04 UTC, itsbilal reviewed
I've addressed almost all the comments - this is ready for another look. Thanks for the reviews! I'm also very close to a CI green - the big blockers are now fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFDWJH3o6CBglr9Hjw:brlcgx7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 401 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MU9mDa_79pQ-8pWHU7e:-MUEw4IM5hic8Cu3CuEw:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/44f5da2821845558a77f15724ad0befa746fc4fd/pkg/server/init_handshake.go#L401)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

nit: Comment should be a complete sentence.
</blockquote></details>

Done. Thanks!
___
*[pkg/server/init_handshake.go, line 254 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnI6L0BPZ1ViGouOL:-MUFCRxu9O8UsBHVqIwC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L254)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

I think you can use `InitializeNodeFromBundle` for this now.
</blockquote></details>

Done.
___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUFByHE4dFi4cYAns_R:by9kles) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

This is one of the places where a locked cluster may manifest where a peer has restarted or been replaced. If the TLS handshake fails it means that the original node is no longer at that address or there's a man-in-the-middle. We should definitely elevate this error.
</blockquote></details>

So if I'm understanding this correctly, we shouldn't repeatedly retry sending the bundle but should fail fast if it's a TLS handshake error, right?
___
*[pkg/server/init_handshake.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDUfav5NCl769NJ3CC:-MUEvdqIB0XtgpU97BdX:b7pwhi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L114)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[nit] Just to avoid having to keep these lists in sync, perhaps something like:

```go
// Computes the HMAC signature based on a signature of all CA
// certificate/keys in the Bundle.
func (n *nodeTrustBundle) computeHMAC(secretToken []byte) []byte {
	h := hmac.New(sha256.New, secretToken)
	h.Write(n.Bundle.InterNode.CACertificate)
	h.Write(n.Bundle.InterNode.CAKey)
	h.Write(n.Bundle.UserAuth.CACertificate)
	h.Write(n.Bundle.UserAuth.CAKey)
	h.Write(n.Bundle.SQLService.CACertificate)
	h.Write(n.Bundle.SQLService.CAKey)
	h.Write(n.Bundle.RPCService.CACertificate)
	h.Write(n.Bundle.RPCService.CAKey)
	h.Write(n.Bundle.AdminUIService.CACertificate)
	h.Write(n.Bundle.AdminUIService.CAKey)
	return h.Sum(nil)
}

// Sets the HMAC signature field in n based on a signature of all CA
// certificate/keys in the Bundle. Converse of validHMAC.
func (n *nodeTrustBundle) signHMAC(secretToken []byte) {
	n.HMAC = n.computeHMAC(secretToken)
}


// Verifies the HMAC signature field set in n to match that of the bundled
// CA certificates and fields. Converse of signHMAC.
func (n *nodeTrustBundle) validHMAC(secretToken []byte) bool {
        expectedMac := n.computeHMAC(secretToken)
	return hmac.Equal(expectedMac, n.HMAC)
}

```
</blockquote></details>

Done. Thanks for writing this out!
___
*[pkg/server/init_handshake.go, line 117 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDVlSb7g_kcfOtwVTV:-MUEvg8p9AO8FO-OJMjN:b4mnxug) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L117)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[question]  I know the named returns can be nice as a sort of documentation of the return signature, but since we are using explicit returns now, might it be good to avoid the named return arguments here to prevent any unexpected problems in the future?  What is our usual code style here?
</blockquote></details>

I've seen the named returns in other places as just a marker for what the return values are, but it's definitely less common if it's not being used. I've just ditched the names as it's pretty obvious here (from the function name). Thanks!
___
*[pkg/server/init_handshake.go, line 336 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDYCwaAsQpa9y0Hpvf:-MUEvpAr5BuH66x2KyoV:b-1a8hjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L336)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Whose reading this channel?
</blockquote></details>

It's read down in `InitHandshake` where we also `select` on `trustedPeers`. 
___
*[pkg/server/init_handshake.go, line 374 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDYkyM4EOBituhDqrK:-MUExXDr5-fsyx-6o0GZ:b-6tpzoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L374)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I imagine it would be rare, but any reason not to handle the error here?

Also, I wonder if it would be worth it here to construct a bytes.Reader from this buffer so that we could do this encoding once outside the loop and leek to the beginning on retry.
</blockquote></details>

Done. Thanks for suggesting this!
___
*[pkg/server/init_handshake.go, line 410 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDd1Wi6SpYKIUMu3Ei:-MUFCFAmEGRF-rXo8ujA:b-3q6j87) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L410)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

As far as I can tell, listenPort and listenAddr/listenHost are only ever used to construct an address in the form of host:port.  I wonder if it would make sense for this function to take a string listenerAddr directly or call `listener.Addr().String()` and use what it returns. I see that this change was made for testing, but I think either of these strategies could work for testing.

I mention this because I'm a bit concerned that constructing addresses with `Sprintf("%s:%d", host, port)` won't work well in IPv6 environments when the user has given us IP addresses rather than hostnames.
</blockquote></details>

Done. I changed this to using `listenAddr`. The only place that just needs a host (no port) is createNodeInitialTempCertificates, so that part still exists, but everywhere else it's `addr.String()`.
___
*[pkg/server/init_handshake_test.go, line 67 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDWe5412rfWAATzeKI:-MUEw5kp0sTzof6MKhxn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake_test.go#L67)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

You could use `require.NoError` here as you did above.  Similarly for the next few error handling cases below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 20:09 UTC, aaron-crl reviewed
Had another pass through; left a few organizational thoughts and one security enhancement request. If you don't want to address that in this PR we can pick it up in another one.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFUquVDAFjMX8-63Nk:bpcsheq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUFLQH04cvwUd1ErTvM:b-ets5u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

So if I'm understanding this correctly, we shouldn't repeatedly retry sending the bundle but should fail fast if it's a TLS handshake error, right?
</blockquote></details>

I think so. If we're trying to provision a bundle to a known host with a known cert chain and we get a different cert, either the node we thought we had for quorum is dead and restarted with new certs or we're no longer talking to the original node. The former is unrecoverable and the latter is outside the provisioners ability to define.
___
*[pkg/server/init_handshake.go, line 114 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUDUfav5NCl769NJ3CC:-MUFRr6GAfMQ9297nLSm:b-gsf21k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fde03e3825c107a422b0f650481240a708a46cc/pkg/server/init_handshake.go#L114)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Thanks for writing this out!
</blockquote></details>

Very nice suggestion @stevendanna !
___
*[pkg/server/init_handshake.go, line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFPvrv57kdLSVj4GgT:-MUFPvrw92HP3lyx8Q28:bcsulme) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L36)):*
> ```Go
> const (
> 	initServiceName     = "temp-init-service"
> 	defaultInitLifespan = 5 * time.Minute
> ```

Do we enable setting this anywhere? Five minutes might be a bit tight outside of trivial deployments; I'd default to at least 10 minutes here regardless.
___
*[pkg/server/init_handshake.go, line 205 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFMMHm4A_sIV6vnsjj:-MUFMMHm4A_sIV6vnsjk:b-pyxqik) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L205)):*
> ```Go
> 	var challenge nodeHostnameAndCA
> 
> 	// TODO(aaron-crl): [Security] Make this more error resilient to size and shape attacks.
> ```

I know this was copied from the reference implementation but it should probably be addressed here.

The issue is that an attacker could create an extremely large JSON blob and pass it to the server to eat CPU and memory. Since we know the tokens shape and size we should restrict both on read with something like this:

```golang
req.Body = http.MaxBytesReader(w, req.Body, 4096)

dec := json.NewDecoder(req.Body)
dec.DisallowUnknownFields()
err := dec.Decode(&challenge)
if err != nil {
    // Invalid message received, return BadRequestError.
    ...
}
```

h/t: to https://www.alexedwards.net/blog/how-to-properly-parse-a-json-request-body
___
*[pkg/server/init_handshake.go, line 368 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFTNdj-1WspNbGkCnd:-MUFTNdj-1WspNbGkCne:b-h55gsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L368)):*
> ```Go
> 	rootCAs.AppendCertsFromPEM(peerCACert)
> 
> 	client := t.getClient(false /* insecureSkipVerify */, rootCAs /* rootCAs */)
> ```

This feels dangerous and error prone. Might be better to move the insecure config call to an explicitly named insecure function or instantiate the insecure config at it's only call site above and use the `pkg/security` config elsewhere.


<!-- Sent from Reviewable.io -->

2021-02-23 20:53 UTC, itsbilal reviewed
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFeeKn7Nmh96HKJZH7:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFPvrv57kdLSVj4GgT:-MUFdZsK9f8XlBxY1IFE:b1bohtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L36)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Do we enable setting this anywhere? Five minutes might be a bit tight outside of trivial deployments; I'd default to at least 10 minutes here regardless.
</blockquote></details>

Done. It's 10 mins now. It's currently not configurable at all; open to thoughts on how we can make it so.
___
*[pkg/server/init_handshake.go, line 205 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFMMHm4A_sIV6vnsjj:-MUFdddPBNfg4KV83Z-g:b-deh5ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L205)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

I know this was copied from the reference implementation but it should probably be addressed here.

The issue is that an attacker could create an extremely large JSON blob and pass it to the server to eat CPU and memory. Since we know the tokens shape and size we should restrict both on read with something like this:

```golang
req.Body = http.MaxBytesReader(w, req.Body, 4096)

dec := json.NewDecoder(req.Body)
dec.DisallowUnknownFields()
err := dec.Decode(&challenge)
if err != nil {
    // Invalid message received, return BadRequestError.
    ...
}
```

h/t: to https://www.alexedwards.net/blog/how-to-properly-parse-a-json-request-body
</blockquote></details>

I'll leave this for a future PR if that's fine? This PR has gotten convoluted enough already.


<!-- Sent from Reviewable.io -->

2021-02-23 21:05 UTC, itsbilal reviewed
Looks like Reviewable ate up some of my comments. Adding the rest

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFhIrV0TJn2lL-proO:bqcppxi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUFhHCa9bana-mixZKH:bxboqyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

I think so. If we're trying to provision a bundle to a known host with a known cert chain and we get a different cert, either the node we thought we had for quorum is dead and restarted with new certs or we're no longer talking to the original node. The former is unrecoverable and the latter is outside the provisioners ability to define.
</blockquote></details>

That makes sense. Do you happen to know what the TLS error would be (`handshake error`, `connection reset`, `unrecognized root CA`) , so I can search for it and fail fast?

Currently, the code would hang until the context is cancelled due to timeout, but that's less ideal and less secure.
___
*[pkg/server/init_handshake.go, line 368 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFTNdj-1WspNbGkCnd:-MUFhFq76KEZj93ENLBm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L368)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

This feels dangerous and error prone. Might be better to move the insecure config call to an explicitly named insecure function or instantiate the insecure config at it's only call site above and use the `pkg/security` config elsewhere.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 21:17 UTC, aaron-crl approved these changes
Modulo those two TODO's and TLS error check this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFk3ce4QcDt7RoVKaa:b-al0x66)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUFixE79avb0RIIUC4g:b-wxqg4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
> Do you happen to know what the TLS error would be
Not off the top of my head though `unrecognized root CA` would probably be the best indication of a replaced node since it would still have the same hostname but not the same CA.

You could test for that and leave a TODO to pick up after with our testing (when we generate a test for this case).
___
*[pkg/server/init_handshake.go, line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFPvrv57kdLSVj4GgT:-MUFgI4w29DBMbWxbMiX:b65c8ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L36)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. It's 10 mins now. It's currently not configurable at all; open to thoughts on how we can make it so.
</blockquote></details>

Probably worth it's own CLI flag. I can see this being tuned per environment. Let's drop a TODO to pull it from the Config and pick it up from there.
___
*[pkg/server/init_handshake.go, line 205 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFMMHm4A_sIV6vnsjj:-MUFgZmxBpnJbcO2001T:b-e75n45) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L205)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I'll leave this for a future PR if that's fine? This PR has gotten convoluted enough already.
</blockquote></details>

I can pick it up in my next PR.


<!-- Sent from Reviewable.io -->

2021-02-23 21:26 UTC, itsbilal reviewed
TFTRs! Added the two TODOs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-:-MUFlv0REevzlsT204zv:b-3ssflf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, @knz, and @stevendanna)

___
*[pkg/server/init_handshake.go, line 467 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUAnc_0E7R5qY6vqufl:-MUFlWYfEqD6t_G4lbkP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9f8f8d1bb58870beda0ac8a43e3cf2bf90088c2/pkg/server/init_handshake.go#L467)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

> Do you happen to know what the TLS error would be
Not off the top of my head though `unrecognized root CA` would probably be the best indication of a replaced node since it would still have the same hostname but not the same CA.

You could test for that and leave a TODO to pick up after with our testing (when we generate a test for this case).
</blockquote></details>

Done.
___
*[pkg/server/init_handshake.go, line 36 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/60766#-MUFPvrv57kdLSVj4GgT:-MUFmC6pAANdIsbfgN7v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29fedeffc2b109da877dd58c326452806f6d016/pkg/server/init_handshake.go#L36)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Probably worth it's own CLI flag. I can see this being tuned per environment. Let's drop a TODO to pull it from the Config and pick it up from there.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 00:24 UTC, itsbilal commented
TFTRs!

bors r=aaron-crl

2021-02-24 05:36 UTC, merged