colexec: extract new colexecutils package
cockroachdb/cockroach pull request #60770
Opened 2021-02-19 03:30 UTC by yuzefovich

This commit extracts new `colexecutils` package from `colexec`, and the
new package now contains the following:
- the code for the spilling queue (which has been exported)
- `AppendOnlyBufferedBatch` wrapper (also exported) and
`MakeWindowIntoBatch` utility method.

Additionally, this commit moves `FeedOperator` and `NonExplainable` marker
into the `colexecbase` package and extracts a utility method to generate
random batch size for tests from `colexec` into `colexectestutils`.

Release note: None

2021-02-19 03:30 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/60770)
<!-- Reviewable:end -->

2021-02-22 05:35 UTC, yuzefovich commented
I think this is RFAL. The first commit should be ignored since it is a part of a separate PR.

2021-02-22 17:04 UTC, rickystewart requested changes, later dismissed

2021-02-22 17:04 UTC, rickystewart commented on pkg/sql/colexec/colexecmisc/COLEXECMISC.bzl
> +# NB: The helpers here were grafted from pkg/sql/colexec/COLEXEC.bzl.
I think this is too much code duplication. The helpers should be refactored into a common place. Let me know if you need help with this.

2021-02-22 19:19 UTC, irfansharif reviewed
If there's already a common ("base") package that all these other packages depend on, the common bazel rules can be moved in there, and that would avoid the deduplication. If there isn't, we could create one (even if only for bazel). Ultimately the "bazel stuff" within colexec will be/is already owned by the sql exec team, so I'll defer to y'all for what you think is best. 

In any case, thanks for chopping all of this up, it's pretty great! Very excited to try it out.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60770#-:-MUAAR0z24TtsUp9Q1nt:b-49t729)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-02-22 20:50 UTC, asubiotto commented
> colexecmisc which contains miscellaneous operators that have very
few dependencies and are depended on by other operators that we want
to extract from colexec

can we put the colexecmisc stuff into colexecbase? Seems like both packages serve the same purpose.

> colexecprojsel which contains shared objects between projection and
selection operators (namely, LIKE ops- and default comparison- related
things)

😬  Don't think it's a good idea to have `colexecproj`, `colexecsel`, and `colexecprojsel`. Is there something better we can name it? Maybe `colexeccmp`?

2021-02-22 21:03 UTC, yuzefovich commented
> can we put the `colexecmisc` stuff into `colexecbase`? Seems like both packages serve the same purpose.

No, they serve different purposes. `colexecbase` defines the `Operator` interface whereas `colexecmisc` contains different things implementing that interface. Merging those two would be bad since it would introduce the dependency on the new stuff that `colexecmisc` brings into the users of `colexecbase` (which are pretty much all packages).

> Don't think it's a good idea to have `colexecproj`, `colexecsel`, and `colexecprojsel`. Is there something better we can name it? Maybe `colexeccmp`?

I disagree because both projection and selection operators result in huge amount of generated code, and they become the bottleneck. In fact, we might want to go even further - break down `colexecproj` into `colexecprojconst` and `colexecprojnonconst` or something like that, so that we can separate out huge projection_ops files (but this can wait).

2021-02-22 21:06 UTC, asubiotto commented
> No, they serve different purposes. colexecbase defines the Operator interface whereas colexecmisc contains different things implementing that interface. Merging those two would be bad since it would introduce the dependency on the new stuff that colexecmisc brings into the users of colexecbase (which are pretty much all packages).

Well then let's rename `colexecbase` to be `colexecop` and `colexecmisc` to be `colexecbase`. `misc` feels too vague.

> I disagree because both projection and selection operators result in huge amount of generated code, and they become the bottleneck. In fact, we might want to go even further - break down colexecproj into colexecprojconst and colexecprojnonconst or something like that, so that we can separate out huge projection_ops files (but this can wait).

I'm not talking about the number of packages. I think that's good. I specifically mean changing the `colexecprojsel` name.

2021-02-22 22:04 UTC, yuzefovich commented
Renaming `colexecbase` to `colexecop` sounds good to me. I think I will also extract `colexecerror` outside of `sql/colexecbase` folder and put it in `sql` folder.

I misunderstood your comment about `colexecprojsel`, renaming it sounds good.

2021-02-23 17:39 UTC, yuzefovich commented
First commit is #60993.

I removed the duplication of bazel-related things and renamed `colexecprojsel` to `colexeccmp`.

However, I'm encountering some issues when renaming/moving packages with `make bazel-generate` (first I tried to move `colexecerror` out of `sql/colexecbase` into `sql`, and then independently I tried renaming `colexecbase` to `colexecop`, and both times I'm getting some warnings locally, but the bazel build succeeds). I don't want to just rename `colexecmisc` to `colexecbase` because then we will have package name clash between `sql/colexecbase` and `sql/colexec/colexecbase`, so I think we should proceed with this PR as is and perform the renaming later.

2021-02-23 18:03 UTC, asubiotto commented
OK. To be clear, why will it be easier later? In any case, LGTM. We should probably merge this sooner rather than later to avoid having to rebase too much.

2021-02-23 18:05 UTC, yuzefovich commented
I'm not saying it will be easier to do the rename later, but that we should not wait for it to happen given that rebasing this PR is a pain. I don't understand why I'm seeing those warnings locally, so I'll need help from dev-infra team.

2021-02-23 18:39 UTC, irfansharif commented
> However, I'm encountering some issues when renaming/moving packages with make bazel-generate (first I tried to move colexecerror out of sql/colexecbase into sql, and then independently I tried renaming colexecbase to colexecop, and both times I'm getting some warnings locally, but the bazel build succeeds)

What are the warnings? It'd be helpful if you could show us how to repro it (is it a particular commit + some particular command)? I'm just going to rubber stamp this PR on Alfonso's behalf, reading his last comment.

2021-02-23 18:39 UTC, irfansharif approved these changes

2021-02-23 19:50 UTC, yuzefovich commented
Ok, I figured out the problem with warnings (as it turned out I had old path being imported in a couple of test files, and Goland for some reason couldn't find them when I was doing the search - probably busted caches). Anyway, I added 3 more commits to get to the currently desired state:
1. move `colexecerror` out of `sql/colexecbase` into `sql`
2. rename `sql/colexecbase` to `sql/colexecop`
3. rename `colexec/colexecmisc` to `colexec/colexecbase`.

I'll wait for #60993 to merge and will merge this afterwards.

Thanks for the feedback everyone!

2021-02-24 02:32 UTC, yuzefovich commented
bors r+

2021-02-24 02:32 UTC, yuzefovich commented
Oops, forgot the label.

bors r+

2021-02-24 05:01 UTC, merged