WIP fix to show_create_all_tables builtin
cockroachdb/cockroach pull request #61127
Opened 2021-02-25 17:36 UTC by RichardJCai

2021-02-25 17:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61127)
<!-- Reviewable:end -->

2021-02-26 09:24 UTC, knz reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdCdaALjkz1ILaHRn:-MUSdCdaALjkz1ILaHRo:bws1xkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L359)):*
> ```Go
> 		makeGeneratorOverload(
> 			tree.ArgTypes{
> 				{"dbName", types.String},
> ```

`database_name`
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdah1CYtPkgSlJR0c:-MUSdah1CYtPkgSlJR0d:bv1sbrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1581)):*
> ```Go
> // Start implements the tree.ValueGenerator interface.
> func (s *showCreateAllTablesGenerator) Start(ctx context.Context, txn *kv.Txn) error {
> 	ids, err := getTopologicallySortedTableIDs(ctx, s.ie, txn, s.dbName, s.timestamp)
> ```

That's still not cutting it though -- you're accumulating all the identifiers in RAM before starting anything.

What is needed is to open the internal executor iterator in `Start` and then consume one row from that per invocation of `Next`

Then close the iterator in the SRF close function.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1613 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdIsT7OUXHeh9A2Xa:-MUSdIsT7OUXHeh9A2Xb:b2pnitg) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1613)):*
> ```Go
> 		}
> 		createStmtStr := string(tree.MustBeDString(createStmt))
> 		s.curr = tree.NewDString(fmt.Sprintf("%s;", createStmtStr))
> ```

`createStmtStr + ";"` is more efficient and also clearer
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdOl71AaY6mIhGT-D:-MUSdOl71AaY6mIhGT-E:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1621)):*
> ```Go
> 			alterStmt := tree.MustBeDString(s.alterArr[s.alterArrIdx])
> 			s.curr = tree.NewDString(
> 				fmt.Sprintf("%s;", alterStmt),
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-03-02 00:08 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdCdaALjkz1ILaHRn:-MUkFlOWE_5StD8PRENK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L359)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`database_name`
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdah1CYtPkgSlJR0c:-MUkF-zN5XmHGEURYfAf:b-oedbte) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1581)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

That's still not cutting it though -- you're accumulating all the identifiers in RAM before starting anything.

What is needed is to open the internal executor iterator in `Start` and then consume one row from that per invocation of `Next`

Then close the iterator in the SRF close function.
</blockquote></details>

As discussed offline, I didn't change this and it still holds the ids in ram. We use the same amount of memory to hold the ids / descriptors in ram when creating the vtable for crdb_internal.create_statements. 

Added comments about the reasoning here. I did try to add some memory accounting, although I'm not sure if I'm doing it correctly.

The second commit runs into a panic with the memory accounting because of `Close()` not being called.

The panic happens when testing for local-vec-off due to what seems like `ValuesGenerator.Close()` is not being called. Not familiar with the execution part of the code base but it seems like in `project_set.go` `ConsumerClosed` is not being called for the local-vec-off.

Will keep investigating.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1613 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdIsT7OUXHeh9A2Xa:-MUkEtx_06NBLpPm431R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1613)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`createStmtStr + ";"` is more efficient and also clearer
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUSdOl71AaY6mIhGT-D:-MUkEu8q-D8y4Uqtkan9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/901b3142c933ef933444b96d7f2609e694dfdccc/pkg/sql/sem/builtins/generator_builtins.go#L1621)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 00:11 UTC, RichardJCai commented
Requesting review from @cockroachdb/sql-execution as well since y'all are probably more familiar with the memory accounting and may be able to read more into why local-vec-off is panicking due to the aforementioned:
>The panic happens when testing for local-vec-off due to what seems like ValuesGenerator.Close() is not being called. Not familiar with the execution part of the code base but it seems like in project_set.go ConsumerClosed is not being called for the local-vec-off.

2021-03-02 00:33 UTC, yuzefovich commented
Try the following diff:
```
diff --git a/pkg/sql/rowexec/project_set.go b/pkg/sql/rowexec/project_set.go
index 92186759d2..6e3ba6664e 100644
--- a/pkg/sql/rowexec/project_set.go
+++ b/pkg/sql/rowexec/project_set.go
@@ -92,7 +92,13 @@ func newProjectSetProcessor(
                processorID,
                output,
                nil, /* memMonitor */
-               execinfra.ProcStateOpts{InputsToDrain: []execinfra.RowSource{ps.input}},
+               execinfra.ProcStateOpts{
+                       InputsToDrain: []execinfra.RowSource{ps.input},
+                       TrailingMetaCallback: func(context.Context) []execinfrapb.ProducerMetadata {
+                               ps.close()
+                               return nil
+                       },
+               },
        ); err != nil {
                return nil, err
        }
@@ -278,14 +284,19 @@ func (ps *projectSetProcessor) toEncDatum(d tree.Datum, colIdx int) rowenc.EncDa
        return rowenc.DatumToEncDatum(ctyp, d)
 }
 
-// ConsumerClosed is part of the RowSource interface.
-func (ps *projectSetProcessor) ConsumerClosed() {
-       for _, gen := range ps.gens {
-               gen.Close(ps.Ctx)
+func (ps *projectSetProcessor) close() {
+       if ps.InternalClose() {
+               for _, gen := range ps.gens {
+                       if gen != nil {
+                               gen.Close(ps.Ctx)
+                       }
+               }
        }
+}
 
-       // The consumer is done, Next() will not be called again.
-       ps.InternalClose()
+// ConsumerClosed is part of the RowSource interface.
+func (ps *projectSetProcessor) ConsumerClosed() {
+       ps.close()
 }
 
 // ChildCount is part of the execinfra.OpNode interface.
```
It fixed the panic I observed on `make test PKG=./pkg/sql TESTS=TestCreateStatementType`.

2021-03-02 17:45 UTC, RichardJCai commented
> Try the following diff:
> 
> ```
> diff --git a/pkg/sql/rowexec/project_set.go b/pkg/sql/rowexec/project_set.go
> index 92186759d2..6e3ba6664e 100644
> --- a/pkg/sql/rowexec/project_set.go
> +++ b/pkg/sql/rowexec/project_set.go
> @@ -92,7 +92,13 @@ func newProjectSetProcessor(
>                 processorID,
>                 output,
>                 nil, /* memMonitor */
> -               execinfra.ProcStateOpts{InputsToDrain: []execinfra.RowSource{ps.input}},
> +               execinfra.ProcStateOpts{
> +                       InputsToDrain: []execinfra.RowSource{ps.input},
> +                       TrailingMetaCallback: func(context.Context) []execinfrapb.ProducerMetadata {
> +                               ps.close()
> +                               return nil
> +                       },
> +               },
>         ); err != nil {
>                 return nil, err
>         }
> @@ -278,14 +284,19 @@ func (ps *projectSetProcessor) toEncDatum(d tree.Datum, colIdx int) rowenc.EncDa
>         return rowenc.DatumToEncDatum(ctyp, d)
>  }
>  
> -// ConsumerClosed is part of the RowSource interface.
> -func (ps *projectSetProcessor) ConsumerClosed() {
> -       for _, gen := range ps.gens {
> -               gen.Close(ps.Ctx)
> +func (ps *projectSetProcessor) close() {
> +       if ps.InternalClose() {
> +               for _, gen := range ps.gens {
> +                       if gen != nil {
> +                               gen.Close(ps.Ctx)
> +                       }
> +               }
>         }
> +}
>  
> -       // The consumer is done, Next() will not be called again.
> -       ps.InternalClose()
> +// ConsumerClosed is part of the RowSource interface.
> +func (ps *projectSetProcessor) ConsumerClosed() {
> +       ps.close()
>  }
>  
>  // ChildCount is part of the execinfra.OpNode interface.
> ```
> 
> It fixed the panic I observed on `make test PKG=./pkg/sql TESTS=TestCreateStatementType`.

Thanks that seems to have fixed it.

2021-03-04 15:57 UTC, RichardJCai commented
@yuzefovich Can you double check that the changes I made to `project_set.go` are valid? Thanks

Also @rafiss / @knz can I get another look at this? Specifically the memory monitoring stuff is worth a good look since I'm not familiar with it.

2021-03-04 16:24 UTC, yuzefovich reviewed
Changes in `project_set.go` LGTM. Also, FYI Raphael is on vacation for week and a half.

> Reviewed 1 of 3 files at r2, 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-:-MUy2KOw6tEoNQ9IOVx7:bo4u17)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1789 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy0hJmALyWWtbP4wFT:-MUy0hJmALyWWtbP4wFU:b9j8b1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/generator_builtins.go#L1789)):*
> ```Go
> // Close implements the tree.ValueGenerator interface.
> func (s *showCreateAllTablesGenerator) Close(ctx context.Context) {
> 	s.acc.Clear(ctx)
> ```

This should be `s.acc.Close(ctx)`. The reasoning is that we instantiate a new memory account in the constructor, so `showCreateAllTablesGenerator` is its owner and should close the account once itself is being closed.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy168WAs6V4THOts9K:-MUy168WAs6V4THOts9L:bcg1eax) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L99)):*
> ```Go
> 		// Account for memory of map.
> 		sizeOfKeyValue := int64(unsafe.Sizeof(tid)) + int64(len(refs))*sizeOfInt64
> 		sizeOfMap += sizeOfKeyValue
> ```

Just a note here that using `map` has an overhead. At some point I did some experiments to measure that overhead and came down to approximately 64 bytes per entry in the map: https://github.com/cockroachdb/cockroach/blob/2e04b557628076e2cd740b6c16483445176f3ffb/pkg/sql/rowexec/aggregator.go#L192-L196.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy25m7Ei8Mlmd2dHc3:-MUy25m7Ei8Mlmd2dHc4:b-alex0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L119)):*
> ```Go
> 
> 	// The sort relies on creating a new array for the ids.
> 	acc.Grow(ctx, int64(len(ids))*sizeOfInt64)
> ```

`Grow` will return an error when the memory budget has been exceeded, so we should its return value here and in `topologicalSort`.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy1oZS0ZTUYi7jRT9-:-MUy1oZS0ZTUYi7jRT90:b-1a6yd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L128)):*
> ```Go
> 	// the two arrays should have the same length.
> 	if len(ids) != len(topologicallyOrderedIDs) {
> 		errors.AssertionFailedf("show_create_all_tables_builtin failed. "+
> ```

Seems like a missing `return`.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy1uOz6ulFQosw9kNu:-MUy1uOz6ulFQosw9kNv:b-wj1u5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L152)):*
> ```Go
> 		AS OF SYSTEM TIME %s
> 		WHERE database_name = $1 
> 			AND is_virtual = FALSE
> ```

nit: uneven indentation (likely spaces vs tabs)


<!-- Sent from Reviewable.io -->

2021-03-04 17:24 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, and @yuzefovich)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1789 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy0hJmALyWWtbP4wFT:-MUyG3DR48ImCtIcrsoq:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/generator_builtins.go#L1789)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This should be `s.acc.Close(ctx)`. The reasoning is that we instantiate a new memory account in the constructor, so `showCreateAllTablesGenerator` is its owner and should close the account once itself is being closed.
</blockquote></details>

Done
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy168WAs6V4THOts9K:-MUyG4Oy6166ILfN-Yqs:b1sjvii) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L99)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Just a note here that using `map` has an overhead. At some point I did some experiments to measure that overhead and came down to approximately 64 bytes per entry in the map: https://github.com/cockroachdb/cockroach/blob/2e04b557628076e2cd740b6c16483445176f3ffb/pkg/sql/rowexec/aggregator.go#L192-L196.
</blockquote></details>

Added a var for extra overhead per item, just to double check, is 64 bytes per entry correct? Seems a bit high.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 119 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy25m7Ei8Mlmd2dHc3:-MUyGFEI3iLHBMgO0iAt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L119)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`Grow` will return an error when the memory budget has been exceeded, so we should its return value here and in `topologicalSort`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy1oZS0ZTUYi7jRT9-:-MUyGG1C10WuNdIsCMgk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L128)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Seems like a missing `return`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-04 18:10 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MUy168WAs6V4THOts9K:-MUyP521Cw2L1IYEOe8s:basb3iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8221fca320740eb3825e30ce531849721285384/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L99)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Added a var for extra overhead per item, just to double check, is 64 bytes per entry correct? Seems a bit high.
</blockquote></details>

Yes, in my experiments 64 bytes overhead was per each k-v entry to the map, and 64 bytes doesn't include the memory of `k` or `v`. Well, `map`s are expensive, and that's why we implemented a vectorized hash table :)

It is possible that the number is higher than it actually is (I think I expected it to be more like 32 bytes), and 64 bytes value was making the memory account (as reported by `mon.BoundAccount`) to be what I was observing in the heap profile, but we tend to forget to account for some things, so possibly the "extra" overhead hides missing accounting somewhere else. 


<!-- Sent from Reviewable.io -->

2021-03-05 17:58 UTC, rafiss requested changes
cool! just have some small comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-:-MV2XfzR3cdttCL8Svmw:b-r68x4o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 378 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2S_pkCZF0fXxzCIHR:-MV2S_pkCZF0fXxzCIHS:bpxldqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/generator_builtins.go#L378)):*
> ```Go
> 			showCreateAllTablesGeneratorType,
> 			makeShowCreateAllTablesGenerator,
> 			`Returns a rows CREATE table statements followed by 
> ```

nit: the grammar is mistaken for "Returns a rows CREATE table statements..." missing word maybe?
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2WsqA9t1rWJEzafwD:-MV2WsqA9t1rWJEzafwE:b-g4vm3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L137)):*
> ```Go
> 		}
> 	}
> 	acc.Shrink(ctx, memoryUsed)
> ```

we don't actually clear out the `seen` map here right? why are we shrinking here? (the mem accounting stuff is also a bit unfamiliar to me, so just asking)

i wonder if it would be cleaner if `topologicalSort` returned a `cleanup()` function callback, and the code here could just call the callback rather than having to know about how the topologicalSort uses memory internally. then we wouldn't need the `memoryUsed` counter i think
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2XN30B2fEthf52c4p:-MV2XN30B2fEthf52c4q:bn2o2ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L146)):*
> ```Go
> 			len(ids), len(topologicallyOrderedIDs))
> 	}
> 	acc.Shrink(ctx, int64(len(ids))*sizeOfInt64)
> ```

maybe there should be a comment saying what is shrinking here?
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2VrLg0shruBCZswtS:-MV2VrLg0shruBCZswtT:b-13f3l2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L210)):*
> ```Go
> 	tid int64,
> 	dependsOnIDs map[int64][]int64,
> 	seen map[int64]bool,
> ```

this would use less memory as a `map[int64]struct{}` (and using `_, isPresent := seen[tid]`) to check if a key is present.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 249 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2U3l-2ZDCvwfDLZyl:-MV2U3l-2ZDCvwfDLZym:b-o669me) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L249)):*
> ```Go
> func getCreateStatement(
> 	ctx context.Context, ie sqlutil.InternalExecutor, txn *kv.Txn, id int64, ts string, dbName string,
> ) (tree.Datum, error) {
> ```

is it safer to return a `(tree.DString, error)` here and return an error if the Datum is the wrong type? maybe that's just extraneous though -- if the existing approach is conventional for using internalExecutor we can stick with it
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 282 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2UCPQ0uG48KY7evjJ:-MV2UCPQ0uG48KY7evjK:b-npa74k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L282)):*
> ```Go
> 	dbName string,
> 	statementType string,
> ) (tree.Datum, error) {
> ```

same comment about DString


<!-- Sent from Reviewable.io -->

2021-03-05 18:38 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2WsqA9t1rWJEzafwD:-MV2ZYNb2GTF13XAp5IZ:b3arc5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we don't actually clear out the `seen` map here right? why are we shrinking here? (the mem accounting stuff is also a bit unfamiliar to me, so just asking)

i wonder if it would be cleaner if `topologicalSort` returned a `cleanup()` function callback, and the code here could just call the callback rather than having to know about how the topologicalSort uses memory internally. then we wouldn't need the `memoryUsed` counter i think
</blockquote></details>

I'm working under the assumption here that the seen map gets GC'ed after the call the topologicalSort above, so I thought it would be alright to shrink it after it gets GC'ed. Let me know your thoughts on this.

IMO adding a cleanup() function callback wouldn't be clean because of how the function calls itself recursively. If we added another function that called the recursive function that returned a callback, I think the recursive function for topologicalSort would still have to return or use a int ptr to keep track of how much memory it uses.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2XN30B2fEthf52c4p:-MV2_f_y1OYawNGErQEM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe there should be a comment saying what is shrinking here?
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 210 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2VrLg0shruBCZswtS:-MV2a1oVEzyssQW_MF4i:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L210)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this would use less memory as a `map[int64]struct{}` (and using `_, isPresent := seen[tid]`) to check if a key is present.
</blockquote></details>

Good call, done.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 249 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2U3l-2ZDCvwfDLZyl:-MV2ah5V6X7z_NWjvs5b:b-cql8sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L249)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is it safer to return a `(tree.DString, error)` here and return an error if the Datum is the wrong type? maybe that's just extraneous though -- if the existing approach is conventional for using internalExecutor we can stick with it
</blockquote></details>

I did some digging into this, it seems that the conventional approach for using IE is to use tree.MustBeDString and panic when it isn't the case. Not sure what the reasoning is here for panicking instead of returning an error though


<!-- Sent from Reviewable.io -->

2021-03-05 18:50 UTC, rafiss requested changes
one final comment then lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-:-MV2iRODBgODy0IDAUdB:bq8p790)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2WsqA9t1rWJEzafwD:-MV2i9PFC7lMGHpsZ_Mo:b-ivwor9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L137)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'm working under the assumption here that the seen map gets GC'ed after the call the topologicalSort above, so I thought it would be alright to shrink it after it gets GC'ed. Let me know your thoughts on this.

IMO adding a cleanup() function callback wouldn't be clean because of how the function calls itself recursively. If we added another function that called the recursive function that returned a callback, I think the recursive function for topologicalSort would still have to return or use a int ptr to keep track of how much memory it uses.


</blockquote></details>

well i think technically the `seen` map is on the heap until the end of this getTopologicallySortedTableIDs function. if you want the memory to be available to GC any earlier than that, you'd need to do `seen = make(map[int64]struct{})` again to remove the reference to the old map.

also, i just realized, why do we need `memoryUsed`? can't we just look at the size of `seen` after the topological sort is done and shrink by that amount?


<!-- Sent from Reviewable.io -->

2021-03-05 18:58 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2WsqA9t1rWJEzafwD:-MV2jmJU4n_DngSWF1wA:bit6qwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L137)):*
> technically

Oops yep you're right for point one, I'll update seen to nil to remove the old reference.

For the second point on memoryUsed, the amount we're growing for the map is not actually the exact amount the map uses.

The reason being, we want to allocate and track memory for each entry we are adding when we add it to the map, however we can't exactly estimate the overhead so we roughly estimate it. @yuzefovich came up with a 64 byte overhead per entry. 

When we shrink we needa shrink by the exact amount we allocated which will not be the exact amount we allocated to seen.

Let me know if this logic makes sense to you.


<!-- Sent from Reviewable.io -->

2021-03-05 19:12 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV2WsqA9t1rWJEzafwD:-MV2najbDBr9JwJMjPdO:bwfrhn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e974b23e92ad7eb0ea6007a8f43a45330304cf15/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L137)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

> technically

Oops yep you're right for point one, I'll update seen to nil to remove the old reference.

For the second point on memoryUsed, the amount we're growing for the map is not actually the exact amount the map uses.

The reason being, we want to allocate and track memory for each entry we are adding when we add it to the map, however we can't exactly estimate the overhead so we roughly estimate it. @yuzefovich came up with a 64 byte overhead per entry. 

When we shrink we needa shrink by the exact amount we allocated which will not be the exact amount we allocated to seen.

Let me know if this logic makes sense to you.
</blockquote></details>

Nvm I misunderstood what you meant, updated.


<!-- Sent from Reviewable.io -->

2021-03-05 20:28 UTC, rafiss approved these changes
comment on comments but lgtm! nice stuff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-:-MV33p_i-ueUrvURHMgo:byb7mok)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 209 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV33l6XC14wCQF8kJEZ:-MV33l6XC14wCQF8kJE_:b-qu2fz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b15e9cb6481f934f16d455e61008a630c4356ddd/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L209)):*
> ```Go
> // be enough.
> // memoryUsed is used to determine how much memory is used by the seen map.
> // memoryUsed should be Shrunk after the sort is finished.
> ```

nit: remove the memoryUsed comment now


<!-- Sent from Reviewable.io -->

2021-03-05 20:58 UTC, yuzefovich reviewed
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV3ALp27L8eMBrhQkuD:-MV3ALp27L8eMBrhQkuE:b-zbwj1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/87cc164d7ef51c902d65e6e54e67bf449b9836e4/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L138)):*
> ```Go
> 
> 	// Clear memory used by the seen map.
> 	seen = nil
> ```

Not sure if you're done updating this stuff, but `len(seen)` will return 0 after `seen = nil`.


<!-- Sent from Reviewable.io -->

2021-03-05 21:06 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 138 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV3ALp27L8eMBrhQkuD:-MV3C_EDByNyWJvBWaak:bvndbz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/87cc164d7ef51c902d65e6e54e67bf449b9836e4/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L138)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Not sure if you're done updating this stuff, but `len(seen)` will return 0 after `seen = nil`.
</blockquote></details>

Oops my brain turned off for a moment


<!-- Sent from Reviewable.io -->

2021-03-06 07:18 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV5OP6j-uVpNXt613v1:-MV5OP6j-uVpNXt613v2:b-48o6wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84f70a6eec32899c8238924f629ab104c2608a1/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L140)):*
> ```Go
> 	sizeOfSeen := len(seen)
> 	seen = nil
> 	acc.Shrink(ctx, int64(sizeOfSeen)*sizeOfInt64)
> ```

not quite sure, but should this be `acc.Shrink(ctx, int64(sizeOfSeen)*(sizeOfInt64+mapEntryOverhead))`?

since on line 229 we are growing by `sizeOfInt64+mapEntryOverhead` for each entry that is added.


<!-- Sent from Reviewable.io -->

2021-03-06 20:50 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rafiss, @RichardJCai, and @yuzefovich)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 140 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/61127#-MV5OP6j-uVpNXt613v1:-MV8IQIS2QS9Lzcsj-8l:b-57ls0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f84f70a6eec32899c8238924f629ab104c2608a1/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L140)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not quite sure, but should this be `acc.Shrink(ctx, int64(sizeOfSeen)*(sizeOfInt64+mapEntryOverhead))`?

since on line 229 we are growing by `sizeOfInt64+mapEntryOverhead` for each entry that is added.
</blockquote></details>

yep it should🤦 


<!-- Sent from Reviewable.io -->

2021-03-07 03:19 UTC, RichardJCai commented
Thanks for the reviews!

bors r=rafiss

2021-03-07 03:53 UTC, merged