sql: add version upgrade test for sequences
cockroachdb/cockroach pull request #61126
Opened 2021-02-25 17:26 UTC by the-ericwang35

This patch just adds some version upgrade tests
for sequences. Now that all new sequences are
referenced by ID and can be renamed, we want to test
that previously created sequences are not affected,
and still follow the old rules (i.e. cannot be renamed and
and are referenced by their names.
This test creates some sequences in 20.2.5, upgrades the
cluster, and verifies this behavior.

Release justification:
Release note: None
Release justification: only adds tests for existing functionality

2021-02-25 17:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61126)
<!-- Reviewable:end -->

2021-03-17 12:47 UTC, ajwerner reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/cmd/roachtest/sequence_upgrade.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61126#-MW-D7Rc1GMNewFs943P:-MW-D7Rc1GMNewFs943Q:bwlwb0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/811f90b17849289937b00238987b6e98d74533f4/pkg/cmd/roachtest/sequence_upgrade.go#L37)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	return func(ctx context.Context, t *test, u *versionUpgradeTest) {
> 		db := u.conn(ctx, t, node)
> 		_, err := db.ExecContext(ctx, fmt.Sprintf(`CREATE SEQUENCE %s`, name))
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> 	}
> ```
</details>

thoughts on adding a helper that also makes better errors:

```
func statementStep(stmt string, args ...interface{}) versionStep {
    return func(ctx context.Context, t *test, u *versionUpgradeTest) {
        //... 
        // also use t.Fatalf and put the stmt and args
}
```


<!-- Sent from Reviewable.io -->

2021-03-17 20:55 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/cmd/roachtest/sequence_upgrade.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61126#-MW-D7Rc1GMNewFs943P:-MW0y-hB8ElU3-_FzX8N:b-i0pnf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/811f90b17849289937b00238987b6e98d74533f4/pkg/cmd/roachtest/sequence_upgrade.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	return func(ctx context.Context, t *test, u *versionUpgradeTest) {
> 		db := u.conn(ctx, t, node)
> 		_, err := db.ExecContext(ctx, fmt.Sprintf(`CREATE SEQUENCE %s`, name))
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> 	}
> ```
thoughts on adding a helper that also makes better errors:

```
func statementStep(stmt string, args ...interface{}) versionStep {
    return func(ctx context.Context, t *test, u *versionUpgradeTest) {
        //... 
        // also use t.Fatalf and put the stmt and args
}
```
</blockquote></details>

Yep thanks that's a lot cleaner, added a helper


<!-- Sent from Reviewable.io -->

2021-03-18 14:18 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @the-ericwang35)

___
*[pkg/cmd/roachtest/sequence_upgrade.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61126#-MW-D7Rc1GMNewFs943P:-MW4gg3i8YaZu7j1OBmw:bxces5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/811f90b17849289937b00238987b6e98d74533f4/pkg/cmd/roachtest/sequence_upgrade.go#L37)):*
<details><summary><i>Previously, the-ericwang35 (Eric Wang) wrote…</i></summary><blockquote>

Yep thanks that's a lot cleaner, added a helper
</blockquote></details>

heh I think  you misunderstood what the `args ...interface{}` were for. I think you should format the query string above this call and then you can pass sql args into it.  I only say that because I think it'll be confusing for people used to other sql APIs where the args are to pass to the sql driver. 


<!-- Sent from Reviewable.io -->

2021-03-18 15:02 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61126)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/cmd/roachtest/sequence_upgrade.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61126#-MW-D7Rc1GMNewFs943P:-MW4oDzDBgDA5mDHMPCG:b-vtylu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/811f90b17849289937b00238987b6e98d74533f4/pkg/cmd/roachtest/sequence_upgrade.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

heh I think  you misunderstood what the `args ...interface{}` were for. I think you should format the query string above this call and then you can pass sql args into it.  I only say that because I think it'll be confusing for people used to other sql APIs where the args are to pass to the sql driver. 
</blockquote></details>

Ahh I see, sorry about that :facepalm: Hopefully I got it right this time 


<!-- Sent from Reviewable.io -->

2021-03-18 21:41 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61126#-:-MW6HJThB0svIEHRmKiG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-03-19 14:21 UTC, the-ericwang35 commented
TFTR!

bors r=ajwerner

2021-03-19 15:35 UTC, merged