sql,tree: make ::REGPROC cast efficient
cockroachdb/cockroach pull request #61211
Opened 2021-02-26 22:42 UTC by jordanlewis

Previously, the ::REGPROC cast (which converts an OID of a builtin
function to its name or vice versa) was implemented extremely
inefficiently: via a query from the internal executor that ultimately
has to re-materialize every builtin into memory and filter. This can
lead to pathologic quadratic behavior for some common ORM queries.

Now, both the oid-to-name and name-to-oid directions are made into
constant-time lookups by simply preparing a map of the oid to name and
vice versa at startup time.

Closes #61082.

Release note (performance improvement): introspection queries that use
casts into the REGPROC pseudo-type are made much more efficient: they're
now implemented as a constant-time lookup instead of an internal query.

Release justification: low risk, high benefit changes to existing functionality

2021-02-26 22:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61211)
<!-- Reviewable:end -->

2021-02-26 22:55 UTC, rafiss requested changes
awesome! i think there are enough existing tests for correctness, but could you add a benchmark similar to this one using that activerecord query: https://github.com/cockroachdb/cockroach/pull/59880/files#diff-389fae48c6f52a8edcfdb2f3ef5780fb9e349bfad03480d6271470977a24f2d0

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-:-MUVY4-p9tFO19qNEA2G:b-8opkdf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/sem/tree/casts.go, line 1279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWOSb4YNLjRJR_yK7:-MUVWOSb4YNLjRJR_yK8:b-8j5rfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1279)):*
> ```Go
> 			case oid.T_regtype:
> 				// Mapping an oid to a regtype is easy: we have a hardcoded map.
> 				typ, ok := types.OidToType[oid.Oid(v.DInt)]
> ```

i guess this is separate from your PR, but does this work for user-defined enum types?
___
*[pkg/sql/sem/tree/casts.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWWJJ4JFwAwI_VcDm:-MUVWWJJ4JFwAwI_VcDn:bwn76pg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1291)):*
> ```Go
> 				// from integer to procedure name.
> 				// Mapping an oid to a regtype is easy: we have a hardcoded map.
> 				name, ok := OidToBuiltinName[int(v.DInt)]
> ```

just curious, is there a way we can warn ourselves in the future if we do support user-defined functions?
___
*[pkg/sql/sem/tree/casts.go, line 1299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWLN8A9iyJaVKTzUE:-MUVWLN8A9iyJaVKTzUF:b5e7hiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1299)):*
> ```Go
> 				return ret, nil
> 
> 			default:
> ```

is the default case still used anywhere? it would be nice to remove the `queryOid` function altogether if not!
___
*[pkg/sql/sem/tree/casts.go, line 1315 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVXwOfAO-EsE_RJtBw:-MUVXwOfAO-EsE_RJtBx:bygm63q) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1315)):*
> ```Go
> 			case oid.T_oid:
> 				return &DOid{semanticType: t, DInt: i}, nil
> 			default:
> ```

do we need to look out for this case too?
___
*[pkg/sql/sem/tree/function_definition.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVXi66AhotUXZhGLsS:-MUVXi670ozrffsyNpJa:b4n7ii0) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/function_definition.go#L165)):*
> ```Go
> // to their name. We populate this from the pg_catalog.go file in the sql
> // package because of dependency issues: we can't use oidHasher from this file.
> var OidToBuiltinName map[int]string
> ```

nit: could it be `map[uint32]string` ?
___
*[pkg/sql/sem/tree/overload.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWp3ICWXGKYq9Wihy:-MUVWp3ICWXGKYq9Wihz:b-pkxj8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/overload.go#L91)):*
> ```Go
> 	// Oid is the cached oidHasher.BuiltinOid result for this Overload. It's
> 	// populated at init-time.
> 	Oid DInt
> ```

nit: shouldn't the type here be `DOid`?

i think we want to move in a direction where we are more consistent in the code about the fact that OIDs are always `uint32`s, so i hesitate to make this a DInt


<!-- Sent from Reviewable.io -->

2021-02-26 23:50 UTC, jordanlewis reviewed
Added a test, but not sure how to adjust the expectations file (and that test seems to be skipped too): https://github.com/cockroachdb/cockroach/issues/57771

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-:-MUVjh2y7CehCKcugQao:b-oslh97)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/casts.go, line 1279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWOSb4YNLjRJR_yK7:-MUVf35x4-lgzbZ1IZGo:bm24bzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1279)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i guess this is separate from your PR, but does this work for user-defined enum types?
</blockquote></details>

Apparently not. Definitely something that needs to be fixed! Filed https://github.com/cockroachdb/cockroach/issues/61216
___
*[pkg/sql/sem/tree/casts.go, line 1291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWWJJ4JFwAwI_VcDm:-MUVfmuM5Qgq2Ld8FJdW:bey55i9) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1291)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just curious, is there a way we can warn ourselves in the future if we do support user-defined functions?
</blockquote></details>

Hmm............... I can't think of one. I added it to the tracking issue though. https://github.com/cockroachdb/cockroach/issues/58356
___
*[pkg/sql/sem/tree/casts.go, line 1299 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVWLN8A9iyJaVKTzUE:-MUVg2xc3cQFJyL4wW28:b385nxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1299)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is the default case still used anywhere? it would be nice to remove the `queryOid` function altogether if not!
</blockquote></details>

It is for ::regnamespace. I was thinking about getting rid of this, but we're not ready yet. queryOid is also still used for several other cases.
___
*[pkg/sql/sem/tree/casts.go, line 1315 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUVXwOfAO-EsE_RJtBw:-MUVhEP26ap_tZM9jEvn:b-5bta5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/26eb9f9a4a966d768cc15b598a1d2d35f3f1b014/pkg/sql/sem/tree/casts.go#L1315)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we need to look out for this case too?
</blockquote></details>

Good point! We had some special cases above that were not being done here properly. I've refactored a function out that can be used in both places.


<!-- Sent from Reviewable.io -->

2021-02-26 23:50 UTC, jordanlewis reviewed
I figured out how to adjust the expectations file actually!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-:-MUVk43Y5MMdE74KPKVq:bfxln0y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)



<!-- Sent from Reviewable.io -->

2021-03-01 18:59 UTC, rafiss approved these changes
amazing!! thank you for taking this on

left optional comments about typing choices.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-:-MUj99jA-ZkAzheWNt0c:byo7c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/function_definition.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUj8cNH-sfsy4wbdsV1:-MUj8cNH-sfsy4wbdsV2:b-iae9c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/402acbc4fca5fedd033fe5d277c3714d6786b260/pkg/sql/sem/tree/function_definition.go#L165)):*
> ```Go
> // to their name. We populate this from the pg_catalog.go file in the sql
> // package because of dependency issues: we can't use oidHasher from this file.
> var OidToBuiltinName map[uint32]string
> ```

err i realize i was the one who suggested making the key be `uint32`, but perhaps it should actually be a `oid.Oid` (same as the existing `OidToType` map)
___
*[pkg/sql/sem/tree/overload.go, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUj8xK_-JXmx5KcfKDT:-MUj8xK_-JXmx5KcfKDU:b4v5sus) ([raw file](https://github.com/cockroachdb/cockroach/blob/402acbc4fca5fedd033fe5d277c3714d6786b260/pkg/sql/sem/tree/overload.go#L91)):*
> ```Go
> 	// Oid is the cached oidHasher.BuiltinOid result for this Overload. It's
> 	// populated at init-time.
> 	Oid uint32
> ```

and here, perhaps this should either be a `oid.Oid` or a `DOid`?

i'll leave this up to you


<!-- Sent from Reviewable.io -->

2021-03-01 19:27 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sem/tree/casts.go, line 1274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61211#-MUjFN0M5PYb6cvwIMyR:-MUjFN0M5PYb6cvwIMyS:bdm1kud) ([raw file](https://github.com/cockroachdb/cockroach/blob/402acbc4fca5fedd033fe5d277c3714d6786b260/pkg/sql/sem/tree/casts.go#L1274)):*
> ```Go
> 		switch v := d.(type) {
> 		case *DOid:
> 			return performIntToOidCast(ctx, t, v.DInt)
> ```

oh hmm it seems like something has tripped up the `oid::regclass` cast in the `pgoidtype ` logic test


<!-- Sent from Reviewable.io -->

2021-03-02 21:20 UTC, mgartner commented
@jordanlewis @rafiss do you folks consider this backport-able to 20.2?

2021-03-03 14:44 UTC, jordanlewis commented
`oid.Oid` is a type that lives in a different package. `DOid` has a bunch of extra fields. This is why I didn't use them earlier, but I'll move to `oid.Oid` because we use it elsewhere already.

@mgartner yes, this feels pretty backportable.

2021-03-03 23:02 UTC, jordanlewis commented
@rafiss PTAL

2021-03-04 21:25 UTC, rafiss approved these changes
lgtm!! thank you

2021-03-04 22:05 UTC, jordanlewis commented
bors r+

2021-03-04 23:02 UTC, merged

2021-03-04 23:23 UTC, mgartner commented
@jordanlewis if we can get this backported before the 20.2.6 SHA is picked (I believe on March 8) that would be great. If you're too busy to get to it by then, I can attempt the backport, just LMK!

2021-03-05 01:56 UTC, jordanlewis commented
@rafiss could you provide the decision on whether we can backport this?

2021-03-05 02:32 UTC, rafiss commented
I think this should be backported.

2021-03-05 19:57 UTC, rafiss commented
We tried out the backport, but looks like it depends on https://github.com/cockroachdb/cockroach/commit/db0f4bf3a4211fe3e9b5461a0da8bc2405badde9 which we think is too risky to backport. So this will not be in 20.2.

It's less important to backport because our ActiveRecord adapter will be changed to stop using this cast: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/182