importccl: avoid random_number collisions between KV batches
cockroachdb/cockroach pull request #61214
Opened 2021-02-26 22:57 UTC by pbardea

An import may parallelize the work to convert SQL rows into KVs. During
this phase, default expressions are evaluated. Previously, IMPORT's
implementations of random number generates that are evaluated in default
expressions assumed that all of the given row IDs were contiguous. This
is not the case since 1 row converter may be responsible for converting
several non-contiguous batches of rows. This resulted in random_values
colliding between different batches of KV space.

This commit fixes this bug by feeding in the current position and
resetting the random source backing these methods. This ensures that
import treats a new contiguous batch of rows separately.

Fixes https://github.com/cockroachdb/cockroach/issues/61203.

Release justification: bug fix
Release note (bug fix): Fix a bug where random numbers generated as
default expressions during IMPORT would collide a few hundred rows apart
from eachother.

2021-02-26 22:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61214)
<!-- Reviewable:end -->

2021-02-27 22:14 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 6746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZC7E18-ftJvxhyBUd:-MUZC7E18-ftJvxhyBUe:bhm3x5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/ccl/importccl/import_stmt_test.go#L6746)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 	defer log.Scope(t).Close(t)
> 	defer sqltestutils.SetTestJobsAdoptInterval()()
> ```

i don't think we need anything for jobs here, do we? we're not running detached jobs.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZCL4LDpMoX0mn0qw8:-MUZCL4LDpMoX0mn0qw9:bopbxxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/ccl/importccl/import_stmt_test.go#L6759)):*
> ```Go
> 
> 	sqlDB.Exec(t, `CREATE TABLE data AS SELECT * FROM generate_series(1, 20000);`)
> 	sqlDB.Exec(t, `EXPORT INTO CSV 'userfile://defaultdb.my_files/export' FROM TABLE data;`)
> ```

pull out this path into a const? shorter typing below...
___
*[pkg/sql/row/expr_walker.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZCW0mBrBlFPTVJCxj:-MUZCW0mBrBlFPTVJCxk:b-19ub0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L40)):*
> ```Go
> // Float64() needed upon every resume. Therefore it will be useful to
> // tune this parameter.
> const reseedRandEveryN = 11
> ```

are we okay with this change in general? or did you mean it to make it for a test?
(I suspect it's the test -- so, please introduce TestingSetReseed.... function)
___
*[pkg/sql/row/expr_walker.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZ8Cig-h0sHuZs434X:-MUZ8Cig-h0sHuZs434Y:bixqwkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L50)):*
> ```Go
> type importRand struct {
> 	*rand.Rand
> 	pos importRandPosition
> ```

can you move importRandPosition definition above this struct?
___
*[pkg/sql/row/expr_walker.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZA1acAjhobw2t1ZEM:-MUZA1acAjhobw2t1ZEN:b-koyial) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L159)):*
> ```Go
> 	// Annotations for rand() and gen_random_uuid().
> 	// randSource should not be used directly, but through getImportRand() instead.
> 	randSource         *importRand
> ```

I like the introduction of randomSource interface.  Perhaps a better way to protect against "unauthorized" used of importRand is to have this field be of type randomSource (instead of importRand).
___
*[pkg/sql/row/expr_walker.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZApJR6Ot3W4xThYMx:-MUZApJR6Ot3W4xThYMy:b6nmt7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L193)):*
> ```Go
> 		c.randSource.reseed(pos)
> 	}
> 	if c.newBatch {
> ```

We probably don't need this field, do we? We have to call reset() every time we start next source and/or row.
So, we could basically drop this field and simply call reseed when we call reset.

Alternatively, you can give "*CellInfoAnnotation" to *importRand. Change `advancePos` method to be `advanceToPos` which should be call prior to calling rand() -- that method checks c.rowID/sorce/etc and does the right thing before you call rand function.
This way, everything is entirely encapsulated in importRand.


<!-- Sent from Reviewable.io -->

2021-03-01 23:56 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 6746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZC7E18-ftJvxhyBUd:-MUiLPyF1J7-svRoRiFQ:bj3cj1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/ccl/importccl/import_stmt_test.go#L6746)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i don't think we need anything for jobs here, do we? we're not running detached jobs.
</blockquote></details>

Yep, accidental left-over copy-paste. Done.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 6759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZCL4LDpMoX0mn0qw8:-MUiLalj5iAZVLrIURSr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/ccl/importccl/import_stmt_test.go#L6759)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

pull out this path into a const? shorter typing below...
</blockquote></details>

Done.
___
*[pkg/sql/row/expr_walker.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZCW0mBrBlFPTVJCxj:-MUiLfXR5pi7VaAfkGjW:bjyxzdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L40)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

are we okay with this change in general? or did you mean it to make it for a test?
(I suspect it's the test -- so, please introduce TestingSetReseed.... function)
</blockquote></details>

Yep, was just playing around with some CI failures I was seeing. Changing didn't have an effect, but randomly changing some of these consts may be interesting in tests, will leave for separate PR though.
___
*[pkg/sql/row/expr_walker.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZ8Cig-h0sHuZs434X:-MUiLuTWBgqCelQv87h9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L50)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

can you move importRandPosition definition above this struct?
</blockquote></details>

Done.
___
*[pkg/sql/row/expr_walker.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZA1acAjhobw2t1ZEM:-MUjejTX87yNU2TKPGhN:bkhq3xo) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L159)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I like the introduction of randomSource interface.  Perhaps a better way to protect against "unauthorized" used of importRand is to have this field be of type randomSource (instead of importRand).
</blockquote></details>

Agh, was so close but forgot to change the type signature here -- the most important part!
___
*[pkg/sql/row/expr_walker.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61214#-MUZApJR6Ot3W4xThYMx:-MUkBNB0DnQ69Pxsb4e1:b-nhndpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/153062e81731829d750e965519dac4a6e6a73ab0/pkg/sql/row/expr_walker.go#L193)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

We probably don't need this field, do we? We have to call reset() every time we start next source and/or row.
So, we could basically drop this field and simply call reseed when we call reset.

Alternatively, you can give "*CellInfoAnnotation" to *importRand. Change `advancePos` method to be `advanceToPos` which should be call prior to calling rand() -- that method checks c.rowID/sorce/etc and does the right thing before you call rand function.
This way, everything is entirely encapsulated in importRand.
</blockquote></details>

I went with the something similar to the second suggestion. Instead of `advanceToPos` I went with `maybeReseed` instead since we don't pass the next position but rather the position of the start of the row. I also played around with storing the last source and row inside `importRand` and comparing it that way over checking the distance, but figured that this approach maintained the least state, and was the least invasive change. What do you think?

I also made a brief attempt to move the `randInstancePerRow` count inside the `randomSource`, but the change was a bit more invasive than I would have liked for a backport-able change.


<!-- Sent from Reviewable.io -->

2021-03-02 13:01 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61214)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-03-02 15:01 UTC, pbardea commented
cc @dt

2021-03-03 13:48 UTC, dt approved these changes

2021-03-03 14:44 UTC, pbardea commented
TFTRs!
bors r=miretskiy,dt

2021-03-03 19:51 UTC, pbardea commented
bors r-
importccl is failing now on testrace with `race: limit on 8128 simultaneously alive goroutines is exceeded, dying`. Didn't seem to catch this on CI, but I think this is the only relevant commit in the batch. Going to let the other commits merge, and investigate if some tests need skipping on race.

2021-03-03 19:54 UTC, pbardea commented
Ah, it looks like there was some threadsan unhappiness causing importccl some CI unhappiness. Will likely fail anyway until the fix is merge. Will re-bors then.

2021-03-03 23:02 UTC, pbardea commented
bors r+

2021-03-04 00:20 UTC, merged