execinfra: remove redundant ctx argument from trailingMetaCallback
cockroachdb/cockroach pull request #61347
Opened 2021-03-02 17:22 UTC by yuzefovich

This commit removes redundant context argument from
`trailingMetaCallback` in favor of just using `ProcessorBase.Ctx` when
needed. This was already actually the case since the callback was always
called with `ProcessorBase.Ctx`.

Additionally, a few unnecessary method overwrites are removed.

Release justification: low-risk cleanup.

Release note: None

2021-03-02 17:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61347)
<!-- Reviewable:end -->

2021-03-02 18:49 UTC, asubiotto requested changes
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/ordinality.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoFycr9xrJOgKYpecY:-MUoFycs6igfcAtoaAFR:b-ny8tr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe3d67917f23cad66aceaa651d9c2b33ba2fc7e/pkg/sql/rowexec/ordinality.go#L62)):*
> ```Go
> 			InputsToDrain: []execinfra.RowSource{o.input},
> 			TrailingMetaCallback: func(context.Context) []execinfrapb.ProducerMetadata {
> 				o.ConsumerClosed()
> ```

Should this call `InternalClose`?
___
*[pkg/sql/rowexec/tablereader.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoG3iTBXyVQ7DNujNE:-MUoG3iTBXyVQ7DNujNF:bz9z4i6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca2d65d3c82992538a13a5cf295f4203ff5a618/pkg/sql/rowexec/tablereader.go#L174)):*
> ```Go
> func (tr *tableReader) generateTrailingMeta() []execinfrapb.ProducerMetadata {
> 	tr.close()
> 	return tr.generateMeta(tr.Ctx)
> ```

Hmm I think this is wrong. `close` will overwrite `tr.Ctx` if if calls `InternalClose`, so we might be using the wrong context... This is another subtle problem of storing contexts, they can be overwritten in unexpected ways.
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoGNqN9N6S2FFHna-K:-MUoGNqN9N6S2FFHna-L:bbh7i94) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca2d65d3c82992538a13a5cf295f4203ff5a618/pkg/sql/rowexec/zigzagjoiner.go#L314)):*
> ```Go
> 			TrailingMetaCallback: func() []execinfrapb.ProducerMetadata {
> 				z.close()
> 				return z.generateMeta(z.Ctx)
> ```

Same problem here.


<!-- Sent from Reviewable.io -->

2021-03-03 03:40 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/ordinality.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoFycr9xrJOgKYpecY:-MUq88yN7SQUEfMQEUWh:bx5yiyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe3d67917f23cad66aceaa651d9c2b33ba2fc7e/pkg/sql/rowexec/ordinality.go#L62)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this call `InternalClose`?
</blockquote></details>

Calling `InternalClose` will happen automatically when `TrailingMetaCallback` is not specified. Essentially, calling `InternalClose` is the default action when we're draining trailing meta.
___
*[pkg/sql/rowexec/tablereader.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoG3iTBXyVQ7DNujNE:-MUq8Ku965i7S91r-6I9:b-q6du4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca2d65d3c82992538a13a5cf295f4203ff5a618/pkg/sql/rowexec/tablereader.go#L174)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm I think this is wrong. `close` will overwrite `tr.Ctx` if if calls `InternalClose`, so we might be using the wrong context... This is another subtle problem of storing contexts, they can be overwritten in unexpected ways.
</blockquote></details>

Nice catch, indeed. As it turns out, `tableReader` is the only place where we were doing things correctly, so I updated several other "KV-readers" to follow the same pattern.
___
*[pkg/sql/rowexec/zigzagjoiner.go, line 314 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUoGNqN9N6S2FFHna-K:-MUq8vFU-BEQp2LxC1kv:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca2d65d3c82992538a13a5cf295f4203ff5a618/pkg/sql/rowexec/zigzagjoiner.go#L314)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same problem here.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-03-03 16:25 UTC, asubiotto requested changes
Just a couple of questions left.

> Reviewed 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-:-MUstygD6G04xhJH-YYa:bm8uhrx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstGyN2X60MrEKmcav:-MUstGyN2X60MrEKmcaw:b-f3p78g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/ccl/changefeedccl/changefeed_processors.go#L194)):*
> ```Go
> // Start is part of the RowSource interface.
> func (ca *changeAggregator) Start(ctx context.Context) {
> 	ctx = ca.StartInternal(ctx, changeAggregatorProcName)
> ```

nit: was this new ordering necessary? Why can't we keep `ca.Ctx` as cancellable? Would be less confusing.
___
*[pkg/sql/rowexec/mergejoiner.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstixhCRMx-Un2qjYs:-MUstixhCRMx-Un2qjYt:b-i8tx9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/sql/rowexec/mergejoiner.go#L262)):*
> ```Go
> func (m *mergeJoiner) close() {
> 	if m.InternalClose() {
> 		m.streamMerger.close(m.Ctx)
> ```

Same problem, or am I imagining things? Do we need to capture `m.Ctx` before calling `InternalClose`?


<!-- Sent from Reviewable.io -->

2021-03-03 16:35 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstGyN2X60MrEKmcav:-MUsvCJ7CPlihuhLyTLi:b-pqdomj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/ccl/changefeedccl/changefeed_processors.go#L194)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: was this new ordering necessary? Why can't we keep `ca.Ctx` as cancellable? Would be less confusing.
</blockquote></details>

In `changeAggregator.close` we first call `InternalClose`, and if that returns `true`, then we might use `ca.Ctx` for logging purposes. However, `InternalClose` swaps out `ca.Ctx` to the "original" context - the one passed into `StartInternal` - which is exactly the one `cancel()` will cancel.

I'm not sure whether it is acceptable to use the canceled context, but the updated layout is exactly the same as with all other processors - calling `StartInternal` is the very first action in `Start` implementations. The changeAggregator here is a bit special because it derives another context with context cancellation function, but I still find the existing ordering more confusing (when comparing against all other processors).
___
*[pkg/sql/rowexec/mergejoiner.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstixhCRMx-Un2qjYs:-MUswGLp6EHeE6Zx-BSM:b-cvp0ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/sql/rowexec/mergejoiner.go#L262)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Same problem, or am I imagining things? Do we need to capture `m.Ctx` before calling `InternalClose`?
</blockquote></details>

No, there is no meaningful change here, simply removing the local variable in favor of using `m.Ctx` directly.


<!-- Sent from Reviewable.io -->

2021-03-03 16:47 UTC, asubiotto reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/mergejoiner.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstixhCRMx-Un2qjYs:-MUsz7GUCkqKMN4oHRAK:bidx4rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/sql/rowexec/mergejoiner.go#L262)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

No, there is no meaningful change here, simply removing the local variable in favor of using `m.Ctx` directly.
</blockquote></details>

Even in the previous version, should the local variable have been defined as the first line in close (i.e. before calling `InternalClose`)


<!-- Sent from Reviewable.io -->

2021-03-03 16:51 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/rowexec/mergejoiner.go, line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-MUstixhCRMx-Un2qjYs:-MUszU-uEHSHcRzxmRxK:bp1dlhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab01af3626585d39d6032c646af96f2cfd94d1b3/pkg/sql/rowexec/mergejoiner.go#L262)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Even in the previous version, should the local variable have been defined as the first line in close (i.e. before calling `InternalClose`)
</blockquote></details>

I think the current way is acceptable. True, `m.Ctx` has been swapped out to `origCtx`, but it is ok to use `origCtx` in all of these cases since the tracing span (if any) has already been finished and the recording collected, so I don't see what value using the derived `m.Ctx` would give us over `origCtx`.


<!-- Sent from Reviewable.io -->

2021-03-03 16:52 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61347#-:-MUt-G127g9UT0bQpKz7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)



<!-- Sent from Reviewable.io -->

2021-03-03 17:14 UTC, yuzefovich commented
TFTR!

bors r+

2021-03-03 19:44 UTC, merged