colflow: clean up vectorized stats propagation
cockroachdb/cockroach pull request #61380
Opened 2021-03-03 00:03 UTC by yuzefovich

To be filled.

Release justification: low-risk update to existing functionality.

Release note: None

2021-03-03 00:03 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61380)
<!-- Reviewable:end -->

2021-03-03 16:11 UTC, asubiotto requested changes
> Reviewed 22 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61380)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/colexec/materializer.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsoWiMAeeYKOuW4qYm:-MUsoWiMAeeYKOuW4qYn:b-9lf6qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colexec/materializer.go#L223)):*
> ```Go
> 	// trailing meta callback, so we tell the ProcessorBase to skip trace data.
> 	// If we don't do so, then we would get duplicate traces.
> 	m.SkipTraceData = true
> ```

I don't like this knob. The underlying problem is that we pass on the recording before adding the stats. I think there are two better ways to fix this:
1) Add stats in `drainHelper`'s `ConsumerDone` method above. This will be called before the trailing meta stage.
2) Call `StartInternalNoSpan` on the `ProcessorBase` in `Start` and do manual span management in the materializer.

I think 1) will be cleaner, but I prefer either to having to add a new knob to `ProcessorBase` if we can avoid it, because I see this as a specific need rather than a more general one.
___
*[pkg/sql/colflow/vectorized_flow.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsptVVB3izjdv91fOI:-MUsptVVB3izjdv91fOJ:bmh4353) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/vectorized_flow.go#L365)):*
> ```Go
> 	vectorizedStatsCollectors []vectorizedStatsCollector,
> ) []*execinfrapb.ComponentStats {
> 	result := make([]*execinfrapb.ComponentStats, 0, len(vectorizedStatsCollectors))
> ```

Should we pool this?
___
*[pkg/sql/colflow/vectorized_flow.go, line 992 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsq0BH-1Tc8dCIKLDn:-MUsq0BIDdRQINIzN2gM:bxm0fuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/vectorized_flow.go#L992)):*
> ```Go
> 			// appended to.
> 			vscq := append([]vectorizedStatsCollector(nil), s.vectorizedStatsCollectorsQueue...)
> 			getStats = func() []*execinfrapb.ComponentStats {
> ```

nit: I wonder if keeping this as a callback is the best way forward. It seems a bit hacky when we could just pass down the vectorized stats collectors and they could be finished by the outbox/materializer just like metadata sources are drained explicitly, instead of passing down a callback that will drain metadata sources. I don't feel strongly about this though, but it might be nice to keep "execution" code outside the planning part.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsqhaZ0O47N7-SDFmU:-MUsqhaZ0O47N7-SDFmV:bwnsw4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/colrpc/outbox.go#L306)):*
> ```Go
> 			}
> 		}
> 		o.span.Finish()
> ```

nit: seems like you could also remove these two lines and rely on the defer above since we don't need to `Finish` the span before grabbing the recording.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsdCMT7tL9DmpHUaIQ:-MUsdCMT7tL9DmpHUaIR:byj93tm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial#L64)):*
> ```
>             └── • scan
>                   cluster nodes: <hidden>
>                   actual row count: 4
> ```

:thinking: is this right?


<!-- Sent from Reviewable.io -->

2021-03-03 22:46 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61380)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/colexec/materializer.go, line 223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsoWiMAeeYKOuW4qYm:-MUtyKJa75aLDimTV7BG:b-xflxy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colexec/materializer.go#L223)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't like this knob. The underlying problem is that we pass on the recording before adding the stats. I think there are two better ways to fix this:
1) Add stats in `drainHelper`'s `ConsumerDone` method above. This will be called before the trailing meta stage.
2) Call `StartInternalNoSpan` on the `ProcessorBase` in `Start` and do manual span management in the materializer.

I think 1) will be cleaner, but I prefer either to having to add a new knob to `ProcessorBase` if we can avoid it, because I see this as a specific need rather than a more general one.
</blockquote></details>

Thanks for the suggestions, I implemented option 1.
___
*[pkg/sql/colflow/vectorized_flow.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsptVVB3izjdv91fOI:-MUuG6iI-HYAiMlexcOf:bb0tnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/vectorized_flow.go#L365)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we pool this?
</blockquote></details>

This is a perf optimization that is somewhat orthogonal to the cleanup. Left a TODO for this.
___
*[pkg/sql/colflow/vectorized_flow.go, line 992 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsq0BH-1Tc8dCIKLDn:-MUu0r53AnJe-FHvoM2s:bx4ouvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/vectorized_flow.go#L992)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I wonder if keeping this as a callback is the best way forward. It seems a bit hacky when we could just pass down the vectorized stats collectors and they could be finished by the outbox/materializer just like metadata sources are drained explicitly, instead of passing down a callback that will drain metadata sources. I don't feel strongly about this though, but it might be nice to keep "execution" code outside the planning part.
</blockquote></details>

I prefer the callback because it allows us to hide everything about the stats collectors from all other code. Namely, this allows us to keep the stats code in `colflow` package and expose only this callback to `colexec` and `colrpc`. I think such layout is acceptable because we only two places need to collect stats whereas metadata sources is more general concept which we need to hide behind an interface.
___
*[pkg/sql/colflow/colrpc/outbox.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsqhaZ0O47N7-SDFmU:-MUttGm11p4vQDeEeSI-:b-9cs0am) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/colflow/colrpc/outbox.go#L306)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: seems like you could also remove these two lines and rely on the defer above since we don't need to `Finish` the span before grabbing the recording.
</blockquote></details>

Done. I originally thought that it is a good practice to Finish the span before getting the recording, but it is not necessary.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-MUsdCMT7tL9DmpHUaIQ:-MUttSUYDoGm0c00YvkN:btuuglk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f31dda0b96c5c978b324344cd1ad5bc322137c49/pkg/sql/logictest/testdata/logic_test/inverted_index_geospatial#L64)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:thinking: is this right?
</blockquote></details>

I was also surprised to see this change, and now it is correct (see that `KV rows read: 4`), also confirmed with `vec-off` config.

I didn't dive into why it was wrong before though - the vectorized stats propagation was probably broken in some edge cases.


<!-- Sent from Reviewable.io -->

2021-03-04 14:47 UTC, asubiotto approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 25 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61380#-:-MUxhHC93mmSsgtJsnoA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-03-04 16:25 UTC, yuzefovich commented
TFTR!

bors r+

2021-03-04 17:32 UTC, merged