sql: add drop type to the prepared statement generator
cockroachdb/cockroach pull request #61394
Opened 2021-03-03 08:15 UTC by tharun208

Release justification: fixes for high-priority or high-severity bugs in existing functionality

Previously, prepare statement doesnt have support for drop type
in optimizer, so it panic during execution as no flags are generated.

This patch fixes this by adding dropType to the optimizer.

Resolves #61226

Release note: none

Signed-off-by: Tharun <rajendrantharun@live.com>

2021-03-03 08:15 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61394)
<!-- Reviewable:end -->

2021-03-03 13:02 UTC, tharun208 commented
@rafiss, can you help by re-triggering the ci ?. thanks in advance.

2021-03-03 16:10 UTC, rafiss requested changes
thanks for this fix!

this needs a test. can you add one in `pkg/sql/logictest/testdata/logic_test/drop_type`


the change looks fine, but since it's optimizer-related and we're in stability period, @raduberinde can you please sign off?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-:-MUsqNYf-JcpjUrij_3R:b-rdjocl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tharun208)

___
*[pkg/sql/plan_opt.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUsqIYF3SpLDoOKawaO:-MUsqIYF3SpLDoOKawaP:b-3m7i01) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c0ec3b04669b77b32c2b5d3a50ebc14469c6e81/pkg/sql/plan_opt.go#L64)):*
> ```Go
> 		*tree.CreateStats,
> 		*tree.Deallocate, *tree.Discard, *tree.DropDatabase, *tree.DropIndex,
> 		*tree.DropTable, *tree.DropView, *tree.DropSequence,
> ```

could you add DropType here, closer to the other drop statements?


<!-- Sent from Reviewable.io -->

2021-03-03 16:17 UTC, tharun208 commented
> pkg/sql/logictest/testdata/logic_test/drop_type

@rafiss, I think the test should need to be a part of `prepare statement`

2021-03-03 19:32 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Can you also add DROP TYPE to `TestStatementReuses` ?  This tests that all those statements work with PREPARE and EXPLAIN.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-:-MUtZ_CgEdZo7Yo8wGx6:b-4fiqc3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @tharun208)



<!-- Sent from Reviewable.io -->

2021-03-03 20:18 UTC, tharun208 commented
> <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/341bcbc4fc105a8a54332ced9ba9f1163b5fd81578777fffe7568934ec76d9d7/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67">
> 
> Can you also add DROP TYPE to `TestStatementReuses` ? This tests that all those statements work with PREPARE and EXPLAIN.
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-:-MUtZ_CgEdZo7Yo8wGx6:b-4fiqc3)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @tharun208)

@RaduBerinde done with the changes

2021-03-03 21:14 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @tharun208)

___
*[pkg/sql/plan_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUtwB7x5I6rQUpN3Ip1:-MUtwB7y2Drd_veH8klY:bgdks5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a3cdceb32fbe2f4f4972adf4feb0a0f981e5867/pkg/sql/plan_opt.go#L65)):*
> ```Go
> 		*tree.Deallocate, *tree.Discard, *tree.DropDatabase, *tree.DropIndex,
> 		*tree.DropTable, *tree.DropView, *tree.DropSequence, *tree.DropType,
> 		*tree.Execute, *tree.Explain,
> ```

Adding Explain here is not correct, Explain has result columns and is supported by the optimizer.

I assume you added it because some PREPARE EXPLAIN case was failing?


<!-- Sent from Reviewable.io -->

2021-03-03 21:18 UTC, tharun208 commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @tharun208)
> 
> _[pkg/sql/plan_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUtwB7x5I6rQUpN3Ip1:-MUtwB7y2Drd_veH8klY:bgdks5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a3cdceb32fbe2f4f4972adf4feb0a0f981e5867/pkg/sql/plan_opt.go#L65)):_
> 
> > ```go
> > 		*tree.Deallocate, *tree.Discard, *tree.DropDatabase, *tree.DropIndex,
> > 		*tree.DropTable, *tree.DropView, *tree.DropSequence, *tree.DropType,
> > 		*tree.Execute, *tree.Explain,
> > ```
> 
> Adding Explain here is not correct, Explain has result columns and is supported by the optimizer.
> 
> I assume you added it because some PREPARE EXPLAIN case was failing?

yes, just now checked `EXPLAIN` will return the result columns and yes, I added `*tree.Explain` because, when I tried adding `DROP TYPE` to `TestStatementReuses` , `PREPARE p AS EXPLAIN` of my test `DROP TYPE type_name` failed

2021-03-03 21:22 UTC, RaduBerinde commented
___
*[pkg/sql/plan_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUtwB7x5I6rQUpN3Ip1:-MUtxnHlBXmrn--wYGwk:bk6dn5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a3cdceb32fbe2f4f4972adf4feb0a0f981e5867/pkg/sql/plan_opt.go#L65)):*
<details><summary><i>Previously, tharun208 (Tharun Rajendran) wrote…</i></summary><blockquote>

yes, just now checked `EXPLAIN` will return the result columns and yes, I added `*tree.Explain` because, when I tried adding `DROP TYPE` to `TestStatementReuses` , `PREPARE p AS EXPLAIN` of my test `DROP TYPE type_name` failed  
</blockquote></details>

What was the failure?


<!-- Sent from Reviewable.io -->

2021-03-03 21:26 UTC, tharun208 commented
> _[pkg/sql/plan_opt.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUtwB7x5I6rQUpN3Ip1:-MUtxnHlBXmrn--wYGwk:bk6dn5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a3cdceb32fbe2f4f4972adf4feb0a0f981e5867/pkg/sql/plan_opt.go#L65)):_
> 
> Previously, tharun208 (Tharun Rajendran) wrote…
> What was the failure?

The same stack trace error we got for `DROP TYPE` on prepared statement , `no Annotations found`.

2021-03-03 21:33 UTC, RaduBerinde commented
I think the right fix here is to move the part that uses `.Ann()` in `startExec` instead of `DropType`, similar to how the `drop_table` code does it.

2021-03-03 21:51 UTC, tharun208 commented
> I think the right fix here is to move the part that uses `.Ann()` in `startExec` instead of `DropType`, similar to how the `drop_table` code does it.

yes, I am able to achieve it, without adding `dropType` to the `optimizer`.

2021-03-03 22:15 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @tharun208)

___
*[pkg/sql/drop_type.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu85B3E_5CyVrp9w-o:-MUu85B3E_5CyVrp9w-p:b-vu6u0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L33)):*
> ```Go
> type typeToDrop struct {
> 	desc   *typedesc.Mutable
> 	fqName string
> ```

i believe fqName should be removed now
___
*[pkg/sql/drop_type.go, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu97Xi3WqahgyskZN9:-MUu97Xi3WqahgyskZNA:b1sodat) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L111)):*
> ```Go
> 		// Record these descriptors for deletion.
> 		node.td[typeDesc.ID] = typeToDrop{
> 			desc: typeDesc,
> ```

instead of removing fqName here, does it work with:

```
		fqName, err := getTypeNameFromTypeDescriptor(
			oneAtATimeSchemaResolver{ctx, p},
			typeDesc,
		)
		if err != nil {
			return nil, err
		}
		node.td[typeDesc.ID] = typeToDrop{
			desc:   typeDesc,
			fqName: fqName.FQString(),
		}
```
___
*[pkg/sql/drop_type.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8EcXCgL11NEH8RMp:-MUu8EcXCgL11NEH8RMq:b-a2ig0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L151)):*
> ```Go
> func (n *dropTypeNode) startExec(params runParams) error {
> 	for _, toDrop := range n.td {
> 		typ, fqName := toDrop.desc, toDrop.fqName
> ```

and now this can be changed to

```
fqName := tree.AsStringWithFQNames(n.n, params.Ann())
```
___
*[pkg/sql/drop_type.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8PSaAr9JPEKulTRg:-MUu8PSaAr9JPEKulTRh:b-lr1ed5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L152)):*
> ```Go
> 	for _, toDrop := range n.td {
> 		typ, fqName := toDrop.desc, toDrop.fqName
> 		if err := params.p.dropTypeImpl(params.ctx, typ, tree.AsStringWithFQNames(n.n, params.Ann()), true /* queueJob */); err != nil {
> ```

use fqName as the 3rd argument here


<!-- Sent from Reviewable.io -->

2021-03-03 22:16 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @tharun208)

___
*[pkg/sql/drop_type.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu85B3E_5CyVrp9w-o:-MUu9Qc87_pioq3CBMxe:b-1d7i0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i believe fqName should be removed now
</blockquote></details>

sorry, i didn't mean to publish this comment.
___
*[pkg/sql/drop_type.go, line 151 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8EcXCgL11NEH8RMp:-MUu9Tw0A_mCRdxQteaP:b-un3olc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L151)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

and now this can be changed to

```
fqName := tree.AsStringWithFQNames(n.n, params.Ann())
```
</blockquote></details>

i didn't mean to publish this comment


<!-- Sent from Reviewable.io -->

2021-03-03 22:28 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tharun208)

___
*[pkg/sql/drop_type.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUuB8eFDAsXG80vBvLk:-MUuB8eFDAsXG80vBvLl:b-gkzk95) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de4313ec216161c79fe725fcc31fc87ef1804ea/pkg/sql/drop_type.go#L112)):*
> ```Go
> 		node.td[typeDesc.ID] = typeToDrop{
> 			desc:   typeDesc,
> 			fqName: tree.AsStringWithFQNames(name, p.Ann()),
> ```

I don't get it, now `fqName` is not set in half the cases, but we are using it in startExec.

Why don't we remove the field altogether and just do `getTypeNameFromTypeDescriptor()` in all cases in`startExec` and use `FQString()`


<!-- Sent from Reviewable.io -->

2021-03-03 22:32 UTC, RaduBerinde commented
___
*[pkg/sql/drop_type.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8PSaAr9JPEKulTRg:-MUuCreQ7NR_iERqVeR8:bwisrdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

use fqName as the 3rd argument here
</blockquote></details>

Noete that the third argument is the entire statement, not just the type name. I would move it out of the loop and assign to an aptly named variable, it's silly to reformat for each type.


<!-- Sent from Reviewable.io -->

2021-03-04 07:49 UTC, tharun208 commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tharun208)
> 
> _[pkg/sql/drop_type.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUuB8eFDAsXG80vBvLk:-MUuB8eFDAsXG80vBvLl:b-gkzk95) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de4313ec216161c79fe725fcc31fc87ef1804ea/pkg/sql/drop_type.go#L112)):_
> 
> > ```go
> > 		node.td[typeDesc.ID] = typeToDrop{
> > 			desc:   typeDesc,
> > 			fqName: tree.AsStringWithFQNames(name, p.Ann()),
> > ```
> 
> I don't get it, now `fqName` is not set in half the cases, but we are using it in startExec.
> 
> Why don't we remove the field altogether and just do `getTypeNameFromTypeDescriptor()` in all cases in`startExec` and use `FQString()`

If we do this it will update the `event log` from `defaultdb.public.eventlog_renamed` to `_defaultdb.public.eventlog_renamed`. is that fine ?

2021-03-04 10:30 UTC, tharun208 commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tharun208)
> 
> _[pkg/sql/drop_type.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUuB8eFDAsXG80vBvLk:-MUuB8eFDAsXG80vBvLl:b-gkzk95) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de4313ec216161c79fe725fcc31fc87ef1804ea/pkg/sql/drop_type.go#L112)):_
> 
> > ```go
> > 		node.td[typeDesc.ID] = typeToDrop{
> > 			desc:   typeDesc,
> > 			fqName: tree.AsStringWithFQNames(name, p.Ann()),
> > ```
> 
> I don't get it, now `fqName` is not set in half the cases, but we are using it in startExec.
> 
> Why don't we remove the field altogether and just do `getTypeNameFromTypeDescriptor()` in all cases in`startExec` and use `FQString()`

this will change the `TypeName` in the `event log`. Current changes will not alter the event log` and all necessary cases got passed.

2021-03-04 17:20 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @tharun208)

___
*[pkg/sql/drop_type.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUuB8eFDAsXG80vBvLk:-MUyDAJh5K9g5PzBT-j0:basyl6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6de4313ec216161c79fe725fcc31fc87ef1804ea/pkg/sql/drop_type.go#L112)):*
<details><summary><i>Previously, tharun208 (Tharun Rajendran) wrote…</i></summary><blockquote>

this will change the `TypeName` in the `event log`. Current changes will not alter the event log` and all necessary cases got passed. 
</blockquote></details>

I don't understand.. what I'm suggesting should be equivalent to the latest revision, we would just call `getTypeNameFromTypeDescriptor` from `startExec` instead. Here's a diff (it passes the sql package tests and the drop_type logictest):

https://gist.github.com/RaduBerinde/f78a2b2c17f22cc429734b366f53edc5


<!-- Sent from Reviewable.io -->

2021-03-04 17:22 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @tharun208)

___
*[pkg/sql/drop_type.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8PSaAr9JPEKulTRg:-MUyEip2DMozE1F2GJ6u:b-idasq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L152)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Noete that the third argument is the entire statement, not just the type name. I would move it out of the loop and assign to an aptly named variable, it's silly to reformat for each type.
</blockquote></details>

oh good call. hmm well also this parameter is the job description, which is used in the db console as a display name. so perhaps it would be better for them to have different names anyway.

maybe change to

```
params.p.dropTypeImpl(params.ctx, typ, "dropping type " + fqName, true /* queueJob */)
```


<!-- Sent from Reviewable.io -->

2021-03-04 17:24 UTC, RaduBerinde commented
___
*[pkg/sql/drop_type.go, line 152 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUu8PSaAr9JPEKulTRg:-MUyG9Ia7nk2ueRW7bWK:b-fhdbh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa553b7d1143be184c88e246a5dcd57887a42d2c/pkg/sql/drop_type.go#L152)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

oh good call. hmm well also this parameter is the job description, which is used in the db console as a display name. so perhaps it would be better for them to have different names anyway.

maybe change to

```
params.p.dropTypeImpl(params.ctx, typ, "dropping type " + fqName, true /* queueJob */)
```
</blockquote></details>

Yeah that's probably better


<!-- Sent from Reviewable.io -->

2021-03-04 19:33 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rafiss, and @tharun208)

___
*[pkg/sql/drop_type.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUyiGJgE75yIteE4pfV:-MUyiGJh7gG2DG2-bi-5:b-s1dr2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4fbad4185817b5bd866c7fb865e68c6917d4f6/pkg/sql/drop_type.go#L135)):*
> ```Go
> 	statementStr := tree.AsStringWithFQNames(n.n, params.Ann())
> 	for _, typeDesc := range n.toDrop {
> 		err := params.p.dropTypeImpl(params.ctx, typeDesc, "dropping type "+statementStr, true /* queueJob */)
> ```

please change `"dropping type "+statementStr` to `dropping type "+typeFQName`

and remove the `statementStr` variable entirely


<!-- Sent from Reviewable.io -->

2021-03-04 19:52 UTC, tharun208 commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rafiss, and @tharun208)
> 
> _[pkg/sql/drop_type.go, line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-MUyiGJgE75yIteE4pfV:-MUyiGJh7gG2DG2-bi-5:b-s1dr2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad4fbad4185817b5bd866c7fb865e68c6917d4f6/pkg/sql/drop_type.go#L135)):_
> 
> > ```go
> > 	statementStr := tree.AsStringWithFQNames(n.n, params.Ann())
> > 	for _, typeDesc := range n.toDrop {
> > 		err := params.p.dropTypeImpl(params.ctx, typeDesc, "dropping type "+statementStr, true /* queueJob */)
> > ```
> 
> please change `"dropping type "+statementStr` to `dropping type "+typeFQName`
> 
> and remove the `statementStr` variable entirely

so, this `dropping type "+typeFQName` will be changed to `dropping type "+typeFQName.FQString()`. since both are of different types.

2021-03-04 21:23 UTC, rafiss approved these changes
thank you! this was a nice cleanup

2021-03-04 21:26 UTC, rafiss commented
bors r+

2021-03-04 21:32 UTC, RaduBerinde reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61394#-:-MUz9-nw4eUOk2eDl16Z:b-e7bejd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @tharun208)



<!-- Sent from Reviewable.io -->

2021-03-04 22:22 UTC, merged