sql: move `ALTER TYPE ... DROP VALUE` behind a feature flag
cockroachdb/cockroach pull request #61595
Opened 2021-03-07 01:32 UTC by arulajmani

Previously, `ALTER TYPE ... DROP VALUE` was behind `sql_safe_updates`.
This patch moves it instead behind a feature flag. The session setting
is `enable_drop_enum_value` and the cluster setting is
`sql.defaults.experimental_implicit_column_partitioning.enabled`.

Resolves #61519

Release justification: Low risk patch that gates new functionality
behind a feature flag.
Release note (sql change): `ALTER TYPE ... DROP VALUE` is gated behind
a feature flag. The session setting is called `enable_drop_enum_value`
and the corresponding cluster setting is called
`sql.defaults.experimental_implicit_column_partitioning.enabled`.

2021-03-07 01:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61595)
<!-- Reviewable:end -->

2021-03-08 22:08 UTC, rafiss requested changes
very small nit

and also the commit msg and PR still refers to "sql.defaults.experimental_implicit_column_partitioning.enabled" -- looks like the word experimental should be taken out now

2021-03-08 22:08 UTC, rafiss commented on pkg/sql/alter_type.go
> +						errors.New("ALTER TYPE ... DROP VALUE ... is only supported as an alpha feature"),
nit: change to "only supported as an experimental feature"

i think "alpha" isn't a standard term in this context.

2021-03-09 00:47 UTC, arulajmani reviewed
> "sql.defaults.experimental_implicit_column_partitioning.enabled"

Well, considering this is about `ALTER TYPE ... DROP VALUE`, you could argue the words "implicit column partitioning" could be taken out as well :) Copy paste error, fixed 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61595#-:-MVJP8zh7UnmJ84JuDCE:bzfzosn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @rafiss)

___
*[pkg/sql/alter_type.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61595#-MV9J79qpRAJWwe-e82X-r1-120:-MVJRp6JC3l5WuC3nav3:brrb9px) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cdde424c5f433b763628fd88dda950434f16282/pkg/sql/alter_type.go#L120)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: change to "only supported as an experimental feature"

i think "alpha" isn't a standard term in this context.
</blockquote></details>

discussed on Slack, turns out we'll be having a standard definition of "alpha" in this context soon. 


<!-- Sent from Reviewable.io -->

2021-03-09 04:23 UTC, rafiss approved these changes
lol totally missed the partitioning typo. good catch!

2021-03-09 05:03 UTC, arulajmani commented
TFTR! 

bors r=rafiss

2021-03-09 06:26 UTC, merged