release-21.1: kvserver: don't let closed timestamps squeeze writes
cockroachdb/cockroach pull request #61666
Opened 2021-03-08 22:57 UTC by andreimatei

Backport 3/3 commits from #61559.

/cc @cockroachdb/release

---

Before this patch, we'd close up to the lease expiration. This is
particularly relevant for leading ranges, where the closed timestamp is
in the future of present time. On these ranges, it can easily happen
that, when either the Raft transport or the side transport wants to
close a timestamp, the lease is currently valid (relative to present
time), but the target closed is above the lease expiration. Before this
patch, this would result in closing up to the lease expiration.

This patch makes it so that we never close within the last (full)
nanosecond of the lease. If the lease expires at (10,20), we'll close at
most (9.0). This ensures that there's infinite (logical) time left for
writes to be pushed into, while staying within the lease validity.
Before this patch, writes would have been pushed above the lease
expiration. They would have executed there, which is not ok.

Release note: None
Release justification: Bug fix for new functionality.

2021-03-08 22:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61666)
<!-- Reviewable:end -->

2021-03-09 00:36 UTC, nvanbenschoten requested changes
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61666#-MVJOzrJ8lGXENJSYlSB:-MVJOzrJ8lGXENJSYlSC:bpkyl84) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e6247393b6159677d880fb886024913c689432/pkg/kv/kvserver/replica_proposal_buf.go#L733)):*
> ```Go
> 		}
> 		// We can't close timestamps above the current lease's expiration.
> 		closedTSTarget.Backward(p.leaseStatus.ClosedTimestampUpperBound().WallPrev())
> ```

Do we want to patch in https://github.com/cockroachdb/cockroach/pull/61660 into this backport?
___
*[pkg/util/hlc/timestamp_test.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61666#-MVJPBzKD3m2xZwrnYuc:-MVJPBzL571W8Jkh8BN6:btpehed) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e6247393b6159677d880fb886024913c689432/pkg/util/hlc/timestamp_test.go#L147)):*
> ```Go
> 	}
> 	for _, c := range testCases {
> 		assert.Equal(t, c.expPrev, c.ts.FloorPrev())
> ```

Huh? We aren't actually checking this. Let's not put these in the same test. It's too easy to make mistakes (like this). Let's just create a new `TestTimestampWallPrev` test.


<!-- Sent from Reviewable.io -->

2021-03-10 16:05 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61666)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_proposal_buf.go, line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61666#-MVJOzrJ8lGXENJSYlSB:-MVRsLW85DoUGyobzddj:bvz2u9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e6247393b6159677d880fb886024913c689432/pkg/kv/kvserver/replica_proposal_buf.go#L733)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to patch in https://github.com/cockroachdb/cockroach/pull/61660 into this backport?
</blockquote></details>

added #61660 and #61716
___
*[pkg/util/hlc/timestamp_test.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61666#-MVJPBzKD3m2xZwrnYuc:-MVRsRtX7B8r5LaEZ_oY:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8e6247393b6159677d880fb886024913c689432/pkg/util/hlc/timestamp_test.go#L147)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Huh? We aren't actually checking this. Let's not put these in the same test. It's too easy to make mistakes (like this). Let's just create a new `TestTimestampWallPrev` test.
</blockquote></details>

fixed


<!-- Sent from Reviewable.io -->

2021-03-11 00:16 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61666#-:-MVTd5e5CBmi8TuVVKYF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)



<!-- Sent from Reviewable.io -->

2021-03-11 00:57 UTC, merged