sql: disallow table/view/sequence rename from making cross DB references
cockroachdb/cockroach pull request #61741
Opened 2021-03-09 21:34 UTC by fqazi

Fixes: #55709

Previously, disallowed cross DB references could be created
using a ALTER TABLE/VIEW/SEQUENCE rename operations. This
was inadequate because users could accidentally start using
deprecated functionality. To address this, this patch detects
such scenarios are returns an appropriate error.

Release note (bug fix): ALTER TABLE/VIEW/SEQUENCE can no longer
be used to incorrectly create cross DB references.

2021-03-11 15:37 UTC, ajwerner reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/rename_table.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVWrN1dBVRf3Zw_JmZi:-MVWrN1eA_qNkrUEItR-:b-si0jtd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ed5961aaa7c6a802c6dae15e6289513b2d8ffdf/pkg/sql/rename_table.go#L190)):*
> ```Go
> 		}
> 	}
> ```

nit: this is a pretty big chunk  of new logic. Any interest in reworking this into some functions? It'll also allow for some early returns which I suspect will aid readability. 

One thing I lament is how hard it is to write unit tests for this stuff. The reason is pretty clear: constructing descriptors is *awful*. My sincere dream is that we'll get to a point where we can write SQL strings to build descriptors in memory and then unit test stuff like this. The fact that we go all the way to the logic tests pretty much always makes me 


<!-- Sent from Reviewable.io -->

2021-03-11 15:37 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/rename_table.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVWrN1dBVRf3Zw_JmZi:-MVWvww22KTdaRW5fmd7:b-lomlea) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ed5961aaa7c6a802c6dae15e6289513b2d8ffdf/pkg/sql/rename_table.go#L190)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: this is a pretty big chunk  of new logic. Any interest in reworking this into some functions? It'll also allow for some early returns which I suspect will aid readability. 

One thing I lament is how hard it is to write unit tests for this stuff. The reason is pretty clear: constructing descriptors is *awful*. My sincere dream is that we'll get to a point where we can write SQL strings to build descriptors in memory and then unit test stuff like this. The fact that we go all the way to the logic tests pretty much always makes me 
</blockquote></details>

sad, I was missing the word sad. 


<!-- Sent from Reviewable.io -->

2021-03-11 15:40 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/rename_table.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVWrN1dBVRf3Zw_JmZi:-MVWwWjoDPmHlxv7cYz0:bsn05b0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ed5961aaa7c6a802c6dae15e6289513b2d8ffdf/pkg/sql/rename_table.go#L190)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

sad, I was missing the word sad. 
</blockquote></details>

Let me rework this into different functions, it would aid with readability.


<!-- Sent from Reviewable.io -->

2021-03-11 16:18 UTC, postamar commented on pkg/sql/logictest/testdata/logic_test/rename_table
> +alter sequence s1 rename to test2.public.s1;
This comment applies to all the lines added above: can you please conform the style of your SQL statements & queries to the existing standard? The existing standard is defined by https://sqlfum.pt/ which I'm told was built using the CRDB SQL parser.

2021-03-11 17:09 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/rename_table, line 466 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVNuXQmGyiqMtDQj_XY-r1-466:-MVXF896-c8kI31cY496:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ed5961aaa7c6a802c6dae15e6289513b2d8ffdf/pkg/sql/logictest/testdata/logic_test/rename_table#L466)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This comment applies to all the lines added above: can you please conform the style of your SQL statements & queries to the existing standard? The existing standard is defined by https://sqlfum.pt/ which I'm told was built using the CRDB SQL parser.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-15 14:47 UTC, ajwerner requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/rename_table.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVqJIRH4lmIUypaOZpn:-MVqJIRH4lmIUypaOZpo:bz6ejbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c4ce4f201837ca9e042b1ba1d426ec790713dd/pkg/sql/rename_table.go#L325)):*
> ```
> 
> 					Required: true,
> ```
I think this should skip the cache. Generally in the context of schema changes we want a consistent view of descriptors. 
___
*[pkg/sql/rename_table.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVqJTXa8JuJltpnQl0B:-MVqJTXa8JuJltpnQl0C:b3yesyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c4ce4f201837ca9e042b1ba1d426ec790713dd/pkg/sql/rename_table.go#L429)):*
> ```
> 
> 			allDescriptors, err := p.Descriptors().GetAllDescriptors(ctx, p.txn)
> ```
This feels egregiously expensive. I'm pretty certain we track the backreference on the columns. See `descpb.ColumnDescriptor.OwnsSequenceIDs`


<!-- Sent from Reviewable.io -->

2021-03-15 15:05 UTC, fqazi reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/rename_table.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVqJIRH4lmIUypaOZpn:-MVqPlfo3M4BVWvntHIw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c4ce4f201837ca9e042b1ba1d426ec790713dd/pkg/sql/rename_table.go#L325)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 					Required: true,
> ```
I think this should skip the cache. Generally in the context of schema changes we want a consistent view of descriptors. 
</blockquote></details>

Done.
___
*[pkg/sql/rename_table.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-MVqJTXa8JuJltpnQl0B:-MVqPfXDAEboK4EB-2IP:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9c4ce4f201837ca9e042b1ba1d426ec790713dd/pkg/sql/rename_table.go#L429)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 			allDescriptors, err := p.Descriptors().GetAllDescriptors(ctx, p.txn)
> ```
This feels egregiously expensive. I'm pretty certain we track the backreference on the columns. See `descpb.ColumnDescriptor.OwnsSequenceIDs`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-03-15 16:54 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61741#-:-MVqnsoeAkagWrx4RWcx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)



<!-- Sent from Reviewable.io -->

2021-03-15 16:55 UTC, fqazi commented
bors r+

2021-03-15 17:34 UTC, merged