kvserver: detect and resolve intents in ClearRange
cockroachdb/cockroach pull request #61850
Opened 2021-03-11 16:31 UTC by erikgrinaker

Previously, `ClearRange` would blindly remove a key range. This could
cause it to remove write intents belonging to an implicitly committed
`STAGING` transaction. When that transaction was later recovered, some
intents would be missing, and the entire transaction would be considered
aborted and all writes (even those outside of the cleared range) would
be removed.

This patch changes `ClearRange` to check for any intents and resolve
them before removing the range. It relies on range statistics to detect
intents, and makes use of the separated intents lock table when
possible. It also takes out a range lock to guard against concurrent
transactions.

Release note (bug fix): Fixed a bug that in rare circumstances could
cause an implicitly committed (`STAGING`) transaction to be uncommitted
if some of its writes were removed by a range clear (e.g. when cleaning
up a dropped table).

2021-03-11 16:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61850)
<!-- Reviewable:end -->

2021-03-11 16:36 UTC, erikgrinaker commented
@tbg Since we can rely on range statistics to detect intents (which we're already collecting), I added a fix for the interleaved intents case as well. The assumption is that statistics will rarely be estimates, and that cleared ranges will rarely contain intents. Let me know if you'd still like to punt this to 21.2 and only use separated intents, but I figured if we _can_ fix this for interleaved intents without too much of a performance hit we should.

Also added a few `TODO`s that I'd like some input on before merging this.

2021-03-11 16:46 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVX9nL7BgDvKQh-ZwwF:-MVX9nL7BgDvKQh-ZwwG:b-3qlmah) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L88)):*
> ```Go
> 	// implicitly committed STAGING txns, which would uncommit the txn and its
> 	// writes (even those outside of the cleared range).
> 	maxIntents := int64(10000)
> ```

Can you add a comment about where this constant comes from? It's fine to say that it's just cargo culted from the mvccScanner (if that is the case).
___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVXA7L3E7acS7UkSSf1:b-pakeaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
> ```Go
> //
> // TODO(erikgrinaker): Maybe take a context here and return early if cancelled?
> func ScanIntents(reader Reader, start, end roachpb.Key, max int64) ([]roachpb.Intent, error) {
> ```

Hmm, this could be problematic. If you are dropping a large table (say 1TB) and the GCTTL expires, we'll issue ClearRange on all ranges at the same time, meaning that each node will hit this codepath for many of its ranges simultaneously. We *should* not have many intents on many of these ranges, but surprise surprise: https://github.com/cockroachdb/cockroach/issues/60585 we're not actually so confident this is always true. So it makes me worried to introduce a full scan here.


<!-- Sent from Reviewable.io -->

2021-03-11 16:52 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVXBMg_3Enl-fwG_-SR:bsawsg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, this could be problematic. If you are dropping a large table (say 1TB) and the GCTTL expires, we'll issue ClearRange on all ranges at the same time, meaning that each node will hit this codepath for many of its ranges simultaneously. We *should* not have many intents on many of these ranges, but surprise surprise: https://github.com/cockroachdb/cockroach/issues/60585 we're not actually so confident this is always true. So it makes me worried to introduce a full scan here.
</blockquote></details>

Ok -- I think the alternative would be to just optimistically check the lock table, and close our eyes and hope for the best if we don't find anything. In that case we won't need to use statistics at all. What's your take @sumeerbhola?


<!-- Sent from Reviewable.io -->

2021-03-11 16:57 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVX9nL7BgDvKQh-ZwwF:-MVXCSwKAOhd7DSiZ81Q:b-z77j2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L88)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you add a comment about where this constant comes from? It's fine to say that it's just cargo culted from the mvccScanner (if that is the case).
</blockquote></details>

This was mostly just picked out of the air. I figured keys are small (<100 bytes), so 10000 intents would take ~1 MB memory, and if we need to resolve intents we'd want to do fairly large batches to avoid running multiple scans. Not sure if that's reasonable, I can do some research.


<!-- Sent from Reviewable.io -->

2021-03-11 18:50 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVXUSpW4LeFda4T7HrW:b-kt4fda) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*
> ```Go
> 	// TODO(erikgrinaker): For now, we play it safe and always check for intents
> 	// if the stats are inaccurate. It's possible estimates won't affect the
> 	// intent stats, but we need to verify this.
> ```

I was hoping @tbg would give a decisive answer here. I remember an assertion that `IntentCount` was not affected by estimates, but maybe I had misunderstood.

The other questions I have are related to concurrent activities:
- Can we assume that no ongoing transactions are reading/writing to this range? If yes, it would help me to understand the larger context that makes that true.
-  I had asked earlier about latching and locking, and I am still not quite clear on concurrent intent resolution. I am assuming there won't be concurrent txns doing reads (previous bullet), so perhaps we don't need to worry about concurrent intent resolution triggered by readers, but perhaps we still need to worry about intent resolution by the txn that wrote that intent (can asynchronous intent resolution be arbitrarily delayed?)?
- I see above the change to call `DefaultDeclareIsolatedKeys`, which will cause locking in addition to latching. I am assuming the timestamp does not matter here since intent resolution and this clear range are both doing `SpanReadWrite` so will conflict. The locking will also try to resolve the intent, if it happens to find intents in the in-memory lock table. That seems worthwhile, since it will batch intent resolution. But we usually forget replicated locks (intents) from the in-memory lock table, so it can fall through here and still have intent resolution to do. So this path is going to try to do intent resolution in two places: as a side-effect of locking, and explicitly here. Given the latter is necessary, maybe we don't need to declare the lock spans, and only do latching?
 
___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVXZA9797x3fnMyoyro:b7styx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
> If you are dropping a large table (say 1TB) and the GCTTL expires, we'll issue ClearRange on all ranges at the same time, meaning that each node will hit this codepath for many of its ranges simultaneously. 

This somewhat relates to the problem of overload control, and seems like a background activity that should be "de-prioritized" if there is real user-facing work to do. I hope we will have something for 21.2 there, but one assumption I have been making is that each request is doing a small bounded amount of work. Putting a smaller max would be ok, but better would be to iterate over a certain number of keys and then return with a `ResumeSpan`. Is the caller able to meaningfully handle `ResumeSpans` for  `ClearRangeRequest`? This would a different form of resumption in that the resumption is for the intent scan but not for the clear range itself -- that still needs to operate on the original range, once all intents are gone.


<!-- Sent from Reviewable.io -->

2021-03-12 12:11 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVa3C5l3punldXOoyOT:brm9rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*
>Can we assume that no ongoing transactions are reading/writing to this range?

The current uses of `ClearRange` are during [table GC](https://github.com/cockroachdb/cockroach/blob/6c5acc2af0e3b16dd75c34ce0154154222541c9e/pkg/sql/gcjob/table_garbage_collection.go#L145), [index GC](https://github.com/cockroachdb/cockroach/blob/6c5acc2af0e3b16dd75c34ce0154154222541c9e/pkg/sql/gcjob/index_garbage_collection.go#L98), [schema change backfill]() (to drop indexes), and [CC tenant removal](https://github.com/cockroachdb/cockroach/blob/fe6377c4f1b6e822bb436f64808762e02a815c11/pkg/sql/tenant.go#L235). It seems reasonable to assume that there will be no in-flight txns during these operations, but I am not sure if and how this would be enforced -- will poke around a bit.

But that reminds me that if we _do_ encounter any concurrent txns we probably want to always abort them instead of aborting the `ClearRange` call, since the range is about to be nuked anyway. I'll look into how this could be done.

> can asynchronous intent resolution be arbitrarily delayed?

On txn completion, [CleanupTxnIntentsAsync](https://github.com/cockroachdb/cockroach/blob/23263a3e19507d386ceeacc27fa3fa060a3a0815/pkg/kv/kvserver/intentresolver/intent_resolver.go#L539) will either spawn an asynchronous task immediately, or block until there are free task slots. Not sure how long the caller will wait, but can find out. For inconsistent reads, there is a [30 second timeout](https://github.com/cockroachdb/cockroach/blob/23263a3e19507d386ceeacc27fa3fa060a3a0815/pkg/kv/kvserver/intentresolver/intent_resolver.go#L50) for async resolution.

However, GC will also attempt to [resolve any intents](https://github.com/cockroachdb/cockroach/blob/47e722c64498aa35b64756d83a19a0e6ac22f0e7/pkg/kv/kvserver/gc_queue.go#L465-L491), but skips it if there are no free async task slots, so I suppose this can be arbitrarily delayed.

> maybe we don't need to declare the lock spans, and only do latching?

I'm still learning about our txn/concurrency management, so please correct me if I'm getting this wrong, but won't we have to take out locks to prevent concurrent txns from laying down intents in a part of the range that we've just scanned? Otherwise, we could miss that intent, and remove the range with the intent. Or would latches be sufficient to prevent this? (I'll read up on the concurrency manager)

Now, since range clears are non-MVCC, I suppose the other txn could wait for the clear to complete and then do the write, in which case the new value would get written into the cleared range and there would be no MVCC deletion metadata to conflict with. This seems bad, but I don't know enough about other mechanisms that might prevent this (removal of the table schema would probably cause an MVCC conflict), nor about the implications (just junk data that'll be left behind?).
___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVa0cYh2obR5zIDj8FZ:b-t9yso1) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
> we'll issue ClearRange on all ranges at the same time

Table GC will actually [serialize `ClearRange` calls](https://github.com/cockroachdb/cockroach/blob/6c5acc2af0e3b16dd75c34ce0154154222541c9e/pkg/sql/gcjob/table_garbage_collection.go#L105-L111) in batches of 100, which somewhat mitigates this, but it's still a valid point. And there's no such throttling for e.g. index GC.

> iterate over a certain number of keys and then return with a ResumeSpan.

Interesting idea. However, if we were to rely exclusively on the lock table (as @tbg suggests) then this would be moot, since the previous intents would presumably be removed when we come around for the next scan. I'm starting to lean towards that solution as well, since it's simpler and more robust, and this bug is fairly unlikely to trigger.


<!-- Sent from Reviewable.io -->

2021-03-12 17:00 UTC, tbg reviewed
I think this PR ended up in a good place. The choice of solving the possible but as far as we think and know very unlikely anomaly only when the separate lock table is enabled over solving it in all cases is right, as the latter gives us potential for stability issues in the common case.

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-:-MVbGBTV8qd4WJ6Lam_d:bj0wke2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVX9nL7BgDvKQh-ZwwF:-MVbB3sh-l5RHf85Eo5e:b9wrel9) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L88)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This was mostly just picked out of the air. I figured keys are small (<100 bytes), so 10000 intents would take ~1 MB memory, and if we need to resolve intents we'd want to do fairly large batches to avoid running multiple scans. Not sure if that's reasonable, I can do some research.
</blockquote></details>

100 sounds good - 10k is a good choice for the average case, but people to weird stuff (1mb keys, etc). Really we would want to pass a byte limit here (like TargetBytes for Scan) and then use a max count of 10k,
___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVbBTfQ08vVVNYen-QO:b-c6zeim) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*

@sumeerbhola I haven't looked at the code in a while and hadn't seen `DefaultDeclareIsolatedKeys`. I know this is not your code, but could you suggest an improvement to its comment:

> // DefaultDeclareIsolatedKeys is similar to DefaultDeclareKeys, but it declares
// both lock spans in addition to latch spans. When used, commands will wait on
// locks and wait-queues owned by other transactions before evaluating. This
// ensures that the commands are fully isolated from conflicting transactions
// when it evaluated.

I'm not sure what exactly happens when it declares lock spans. It sounds like it means that evaluation is guaranteed to not run into any intents? But you're describing - I think - that this isn't true in your comment above. 

> I was hoping @tbg would give a decisive answer here. I remember an assertion that IntentCount was not affected by estimates, but maybe I had misunderstood.

In practice I believe that the IntentCount is always exact, but this isn't an invariant insofar as we have spent no time or testing on it so I wouldn't want to build on top of it.

> Can we assume that no ongoing transactions are reading/writing to this range? If yes, it would help me to understand the larger context that makes that true.

Yes, SQL shouldn't allow new txns to touch this range when it issues ClearRange. It shouldn't! But I don't think that is something I would want to assume here. Also, you can always have internal txns accessing the range, or txns for other tables on the same range. They wouldn't overlap with the space that is being ClearRanged, but they are txns on that range (split, merge, etc) so they probably don't matter for your purpose.

> I see above the change to call DefaultDeclareIsolatedKeys, which will cause locking in addition to latching. I am assuming the timestamp does not matter here since intent resolution and this clear range are both doing SpanReadWrite so will conflict. The locking will also try to resolve the intent, if it happens to find intents in the in-memory lock table. That seems worthwhile, since it will batch intent resolution. But we usually forget replicated locks (intents) from the in-memory lock table, so it can fall through here and still have intent resolution to do. So this path is going to try to do intent resolution in two places: as a side-effect of locking, and explicitly here. Given the latter is necessary, maybe we don't need to declare the lock spans, and only do latching?

Hmm, I could go either way. I think your opinion matters most here @sumeerbhola. It feels like the most similar command `DeleteRange` would do exactly the same thing, declare locks and then find any replicated intents as it accesses them. So it seems, at least to me, that ClearRange should also declare the locks and conclusively scan the lock table in its eval.

> Or would latches be sufficient to prevent this?

I think latches would be sufficient. When latched for r/w, overlapping commands will only be allowed to evaluate once the ClearRange is done. They would thus see the outcome of ClearRange. And would lay down an intent! It really doesn't make much sense (in the sense of isolation levels) to write to a range that has been ClearRange'd, but if you did, it would behave as sanely as it could with just latching. The locking is more about preventing ClearRange itself from seeing intents during evaluation (iiuc).
___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVbF_Hl67lQ9zwnOsmh:bpjkbjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
> Interesting idea. However, if we were to rely exclusively on the lock table (as @tbg suggests) then this would be moot, since the previous intents would presumably be removed when we come around for the next scan. I'm starting to lean towards that solution as well, since it's simpler and more robust, and this bug is fairly unlikely to trigger.

Yeah, I'm leaning towards that as well, since I happen to know that ResumeSpan is not on very solid ground and I'm scared to use it for something like this. I think you can get more bang for the buck by giving `ScanSeparatedIntents` a `targetBytes` on top of the `max` and then calling it with `targetBytes=1mb,max=10k` (and scan returns with at least one key, once the first of the limits is hit).


<!-- Sent from Reviewable.io -->

2021-03-12 17:17 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVbPa0E9j2kyGJbdMx1:byj7xrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>


@sumeerbhola I haven't looked at the code in a while and hadn't seen `DefaultDeclareIsolatedKeys`. I know this is not your code, but could you suggest an improvement to its comment:

> // DefaultDeclareIsolatedKeys is similar to DefaultDeclareKeys, but it declares
// both lock spans in addition to latch spans. When used, commands will wait on
// locks and wait-queues owned by other transactions before evaluating. This
// ensures that the commands are fully isolated from conflicting transactions
// when it evaluated.

I'm not sure what exactly happens when it declares lock spans. It sounds like it means that evaluation is guaranteed to not run into any intents? But you're describing - I think - that this isn't true in your comment above. 

> I was hoping @tbg would give a decisive answer here. I remember an assertion that IntentCount was not affected by estimates, but maybe I had misunderstood.

In practice I believe that the IntentCount is always exact, but this isn't an invariant insofar as we have spent no time or testing on it so I wouldn't want to build on top of it.

> Can we assume that no ongoing transactions are reading/writing to this range? If yes, it would help me to understand the larger context that makes that true.

Yes, SQL shouldn't allow new txns to touch this range when it issues ClearRange. It shouldn't! But I don't think that is something I would want to assume here. Also, you can always have internal txns accessing the range, or txns for other tables on the same range. They wouldn't overlap with the space that is being ClearRanged, but they are txns on that range (split, merge, etc) so they probably don't matter for your purpose.

> I see above the change to call DefaultDeclareIsolatedKeys, which will cause locking in addition to latching. I am assuming the timestamp does not matter here since intent resolution and this clear range are both doing SpanReadWrite so will conflict. The locking will also try to resolve the intent, if it happens to find intents in the in-memory lock table. That seems worthwhile, since it will batch intent resolution. But we usually forget replicated locks (intents) from the in-memory lock table, so it can fall through here and still have intent resolution to do. So this path is going to try to do intent resolution in two places: as a side-effect of locking, and explicitly here. Given the latter is necessary, maybe we don't need to declare the lock spans, and only do latching?

Hmm, I could go either way. I think your opinion matters most here @sumeerbhola. It feels like the most similar command `DeleteRange` would do exactly the same thing, declare locks and then find any replicated intents as it accesses them. So it seems, at least to me, that ClearRange should also declare the locks and conclusively scan the lock table in its eval.

> Or would latches be sufficient to prevent this?

I think latches would be sufficient. When latched for r/w, overlapping commands will only be allowed to evaluate once the ClearRange is done. They would thus see the outcome of ClearRange. And would lay down an intent! It really doesn't make much sense (in the sense of isolation levels) to write to a range that has been ClearRange'd, but if you did, it would behave as sanely as it could with just latching. The locking is more about preventing ClearRange itself from seeing intents during evaluation (iiuc).
</blockquote></details>

Looks like returning `WriteIntentError` won't work without taking out locks, since the concurrency manager errors out when resolving them:

```
cannot handle WriteIntentError conflicting intents on "b" for request without lockTableGuard; were lock spans declared for this request?
```
___
*[pkg/storage/engine.go, line 871 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXA7L3E7acS7UkSSf0:-MVbQPEp4Ib312qpmRtQ:b9f84iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/00147f355843c46939ea80deaaef7f624b28ed83/pkg/storage/engine.go#L871)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> Interesting idea. However, if we were to rely exclusively on the lock table (as @tbg suggests) then this would be moot, since the previous intents would presumably be removed when we come around for the next scan. I'm starting to lean towards that solution as well, since it's simpler and more robust, and this bug is fairly unlikely to trigger.

Yeah, I'm leaning towards that as well, since I happen to know that ResumeSpan is not on very solid ground and I'm scared to use it for something like this. I think you can get more bang for the buck by giving `ScanSeparatedIntents` a `targetBytes` on top of the `max` and then calling it with `targetBytes=1mb,max=10k` (and scan returns with at least one key, once the first of the limits is hit).
</blockquote></details>

Well, it occurred to me that if we found 10k intents they could in principle belong to 10k different txns spanning a bunch of ranges, so maybe it'd be better to just go for smaller batches on the order of 100-1000 anyway instead of firing off too much at once. Will add a `targetBytes` as well.


<!-- Sent from Reviewable.io -->

2021-03-13 23:28 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 8 files at r3, 2 of 5 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-:-MVhusKYAcfAtUK17-hk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVhiQCB54uyXktmy8ix:b-hv2kja) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*
> I'm still learning about our txn/concurrency management, so please correct me if I'm getting this wrong, but won't we have to take out locks to prevent concurrent txns from laying down intents in a part of the range that we've just scanned? Otherwise, we could miss that intent, and remove the range with the intent. Or would latches be sufficient to prevent this? (I'll read up on the concurrency manager)

Locking is used when the lock needs to outlive the `BatchRequest`. The situation with ClearRange is slightly peculiar -- we are not, of course, acquiring locks, but we do care about seeing the locks. We perhaps only care about replicated locks, but one could argue that to reduce the possibility of bugs (some txn holding an unreplicated lock suggests someone is going to try to write, which is bad) one should see unreplicated locks. So on second thought, your change to use `DefaultDeclareIsolatedKeys` makes sense. Also, what you discovered with the `WriteIntentError` and concurrency manager further nudges us in that direction, which is all good.

> I'm not sure what exactly happens when it declares lock spans. It sounds like it means that evaluation is guaranteed to not run into any intents? But you're describing - I think - that this isn't true in your comment above.

The use of the lock table to see the replicated locks is unfortunately best-effort at this point (and will stay so for limited scans, which will do optimistic evaluation, even when we have only separated locks), so at evaluation time the request processing has to make sure it doesn't miss the replicated locks, which is happening here too.
___
*[pkg/storage/engine.go, line 890 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVhtABG8u-dDWFSPbkr:-MVhtABG8u-dDWFSPbks:bp2rl0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b38ff01b86a6360b1554e55a1027b28ce71fcd89/pkg/storage/engine.go#L890)):*
> ```Go
> 	valid, err := iter.SeekEngineKeyGE(EngineKey{Key: ltStart})
> 	for ; valid; valid, err = iter.NextEngineKey() {
> 		if max != 0 && int64(len(intents)) >= max {
> ```

can this be merged into the same if block that is comparing with `targetBytes`?
___
*[pkg/storage/engine.go, line 901 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVhstCj5j95f8DJl4zX:-MVhstCk7mvXHPbMIp0M:b-okbohx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b38ff01b86a6360b1554e55a1027b28ce71fcd89/pkg/storage/engine.go#L901)):*
> ```Go
> 			return nil, err
> 		}
> 		if err = protoutil.Unmarshal(iter.Value(), &meta); err != nil {
> ```

we can use `UnsafeValue` here, and below in the length calculation, to avoid allocating byte slices.
___
*[pkg/storage/engine_test.go, line 1632 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVhtuPlBwkR0h1UBePL:-MVhtuPlBwkR0h1UBePM:b-rl78mi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b38ff01b86a6360b1554e55a1027b28ce71fcd89/pkg/storage/engine_test.go#L1632)):*
> ```Go
> 			version := clusterversion.ByKey(clusterversion.SeparatedIntents)
> 			settings := cluster.MakeTestingClusterSettingsWithVersions(version, version, true)
> 			SeparatedIntentsEnabled.Override(&settings.SV, enableSeparatedIntents)
> ```

these 3 lines could be replaced by a call to `makeSettingsForSeparatedIntents(false, enableSeparatedIntents)`


<!-- Sent from Reviewable.io -->

2021-03-15 13:28 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_clear_range.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61850#-MVXUSpW4LeFda4T7HrV:-MVq3Qkr13rDJmUYURor:b-d2tkic) ([raw file](https://github.com/cockroachdb/cockroach/blob/0af0fe2c64ec9f404da70b56c5b053067c10801b/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L93)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I'm still learning about our txn/concurrency management, so please correct me if I'm getting this wrong, but won't we have to take out locks to prevent concurrent txns from laying down intents in a part of the range that we've just scanned? Otherwise, we could miss that intent, and remove the range with the intent. Or would latches be sufficient to prevent this? (I'll read up on the concurrency manager)

Locking is used when the lock needs to outlive the `BatchRequest`. The situation with ClearRange is slightly peculiar -- we are not, of course, acquiring locks, but we do care about seeing the locks. We perhaps only care about replicated locks, but one could argue that to reduce the possibility of bugs (some txn holding an unreplicated lock suggests someone is going to try to write, which is bad) one should see unreplicated locks. So on second thought, your change to use `DefaultDeclareIsolatedKeys` makes sense. Also, what you discovered with the `WriteIntentError` and concurrency manager further nudges us in that direction, which is all good.

> I'm not sure what exactly happens when it declares lock spans. It sounds like it means that evaluation is guaranteed to not run into any intents? But you're describing - I think - that this isn't true in your comment above.

The use of the lock table to see the replicated locks is unfortunately best-effort at this point (and will stay so for limited scans, which will do optimistic evaluation, even when we have only separated locks), so at evaluation time the request processing has to make sure it doesn't miss the replicated locks, which is happening here too.

</blockquote></details>

How does locking then even work for non-transactional requests such as `ClearRange`? When are the locks released?


<!-- Sent from Reviewable.io -->

2021-03-16 18:58 UTC, sumeerbhola commented
> How does locking then even work for non-transactional requests such as ClearRange? When are the locks released?

Did I miss something -- I thought ClearRange was not acquiring any locks. The use of `DefaultDeclareIsolatedKeys` just says that the request is allowed to acquire locks, but it doesn't have to.

2021-03-17 14:34 UTC, tbg commented
> Did I miss something -- I thought ClearRange was not acquiring any locks. Indeed there is no support that I know of for non-transactional requests to acquire locks. The use of DefaultDeclareIsolatedKeys just says that the request is allowed to acquire locks, but it doesn't have to.

Ah, that's what I was missing :+1: Thanks for clarifying.

@erikgrinaker as far as I'm concerned this can land :tada:

2021-03-17 14:35 UTC, erikgrinaker commented
bors r=tbg,sumeerbhola

TFTRs!

2021-03-17 15:10 UTC, merged