roachtest: stop node in disk-full before restarting
cockroachdb/cockroach pull request #61954
Opened 2021-03-12 22:19 UTC by itsbilal

Pebble doesn't have a distinction for fatal background
errors; so `no space left on device` during a flush/compaction
ends up being a suppressed background error. Seeing as this
isn't going to be fixed rightaway, this change updates
the `disk-full` roachtest to stop the node being stressed in
case it hasn't crashed on its own, before attempting to
restart it.

The test still checks for the restarts failing, so it's
still a useful roahctest with this change.

Fixes #59792.

Release note: None.

2021-03-12 22:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/61954)
<!-- Reviewable:end -->

2021-03-12 22:42 UTC, petermattis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-:-MVcaopsEs8xD5igVURW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-03-13 01:50 UTC, sumeerbhola requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61954)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/cmd/roachtest/disk_full.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVdFyxw349UmemZk4tT:-MVdFyxx0BeYT2CPZYdp:b-o49vcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c91578c83bfdc12235b63989652313ef13a4f9b/pkg/cmd/roachtest/disk_full.go#L67)):*
> ```Go
> 					// Pebble treats "no space left on device" as a background error. Kill
> 					// cockroach if it is still running.
> 					_ = c.StopE(ctx, c.Node(1))
> ```

c.Node(n), like the others?
___
*[pkg/cmd/roachtest/disk_full.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVdGCcWDR79KKUNdVIJ:-MVdGCcWDR79KKUNdVIK:bgfppgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c91578c83bfdc12235b63989652313ef13a4f9b/pkg/cmd/roachtest/disk_full.go#L71)):*
> ```Go
> 					// enough along that the monitor detects the death.
> 					m.ExpectDeath()
> 					if err := c.StartE(ctx, c.Node(n)); err == nil {
> ```

I don't quite understand the change. Is it the case that `err != nil` but the node is still running? That is, the background error is popping up all the way back here, as we desire, but not killing the node?
If not, I don't see how we would go the next iteration of this loop (I am assuming the StopE you added was trying the kill the node from the previous iteration).


<!-- Sent from Reviewable.io -->

2021-03-15 17:34 UTC, itsbilal reviewed
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-:-MVqwtU1500h0UjZRySG:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens and @sumeerbhola)

___
*[pkg/cmd/roachtest/disk_full.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVdFyxw349UmemZk4tT:-MVqw3G2-hNqaNpXLxNi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c91578c83bfdc12235b63989652313ef13a4f9b/pkg/cmd/roachtest/disk_full.go#L67)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

c.Node(n), like the others?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/disk_full.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVdGCcWDR79KKUNdVIJ:-MVqw26h1USuWhfwVh2g:b-8qflo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c91578c83bfdc12235b63989652313ef13a4f9b/pkg/cmd/roachtest/disk_full.go#L71)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't quite understand the change. Is it the case that `err != nil` but the node is still running? That is, the background error is popping up all the way back here, as we desire, but not killing the node?
If not, I don't see how we would go the next iteration of this loop (I am assuming the StopE you added was trying the kill the node from the previous iteration).
</blockquote></details>

It's mostly for the node that was started way up in `c.Start(ctx, t, c.Range(1, nodes))`. The test just assumes that that node would have crashed by now.

Lack of errors is checked here already so I'm not worried about the previous-iteration case.


<!-- Sent from Reviewable.io -->

2021-03-16 17:52 UTC, sumeerbhola approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61954)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/cmd/roachtest/disk_full.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVdGCcWDR79KKUNdVIJ:-MVw9H56C0oZtxk9qTlP:b-yf37a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c91578c83bfdc12235b63989652313ef13a4f9b/pkg/cmd/roachtest/disk_full.go#L71)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It's mostly for the node that was started way up in `c.Start(ctx, t, c.Range(1, nodes))`. The test just assumes that that node would have crashed by now.

Lack of errors is checked here already so I'm not worried about the previous-iteration case.
</blockquote></details>

I see. I've added a suggestion to enhance the code comment. It is unclear without that, that there is a distinction between nodes that are already running and the disk fills up, versus nodes that are started after the disk is already full.
___
*[pkg/cmd/roachtest/disk_full.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61954#-MVw9-kTAkJH-JdPYTSr:-MVw9-kU3cf7S-8ujZYC:b-uuqkiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0a574f8b7e4ba47568bcde2f4ed0dc05a35d6f9/pkg/cmd/roachtest/disk_full.go#L66)):*
> ```Go
> 					t.l.Printf("starting %d when disk is full\n", n)
> 					// Pebble treats "no space left on device" as a background error. Kill
> 					// cockroach if it is still running.
> ```

Could you add
// Note that this is to kill the node that was started prior to this for loop, before the ballast was created. Now that the disk is full, any subsequent node starts must fail with an error for this test to succeed.


<!-- Sent from Reviewable.io -->

2021-03-16 20:19 UTC, itsbilal commented
TFTR!

bors r=sumeerbhola

2021-03-16 23:09 UTC, itsbilal commented
Looks like a distsql flake.

bors r=sumeerbhola

2021-03-16 23:46 UTC, merged