opt: make opt tests work in bazel
cockroachdb/cockroach pull request #62109
Opened 2021-03-16 20:37 UTC by RaduBerinde

Under bazel, we have to declare the dependency on test fixtures and we
have to ask bazel for the path of the file.

Fixes #61919

Release note: None

2021-03-16 20:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62109)
<!-- Reviewable:end -->

2021-03-22 18:26 UTC, rickystewart requested changes
Looks like some of the tests are still failing due to GEOS missing. This is a known issue (#61664, #61665). Can you add the `broken_in_bazel` tag back in for those tests that are still broken, so that the Github Optional CI task succeeds? (This change is still valuable and should be checked in, we're not ready to turn the tests on though.)

2021-03-22 19:47 UTC, rickystewart commented
Alternatively incorporate the fix from https://github.com/cockroachdb/cockroach/pull/62071 (rebase after it hits `master`). Either way's fine, just don't want to turn on broken tests at `HEAD` :)

2021-03-22 21:08 UTC, RaduBerinde commented
Thanks, I will try again after #62387

2021-03-23 04:54 UTC, RaduBerinde commented
Ok, they seem to be working now.

2021-03-23 15:30 UTC, rickystewart approved these changes

2021-03-23 15:30 UTC, rickystewart commented
great work :)

2021-03-23 16:56 UTC, RaduBerinde commented
TFTR!

bors r+

2021-03-23 18:00 UTC, merged