sql: Don't require override for multiple MR abstractions in a transaction
cockroachdb/cockroach pull request #62354
Opened 2021-03-22 15:00 UTC by ajstorm

Previously, we required override_multi_region_zone_config to be
specified if multiple add/drop region operations were included in a
single transaction. This was due to the fact that the RegionConfig
would get updated as part of the first operation, but the zone
configurations to which we were comparing were not updated until the
transaction committed. This issue was fixed in part by #62200, but this
PR finishes the job by creating a function which synthesizes a zone
configuration which presents the state of the RegionConfig at the
beginning of the transaction.

Resolves: #61551 

Release note: None

2021-03-22 15:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62354)
<!-- Reviewable:end -->

2021-03-22 15:59 UTC, arulajmani requested changes
One testing request, but otherwise this looks good 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-:-MWPe7Ji7LjFVeuIQ879:b-yo1lvw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/region_util.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdyWaACgJB4K60I65:-MWPdyWaACgJB4K60I66:btvejji) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/region_util.go#L939)):*
> ```Go
> // the database descriptor and multi-region type descriptor. It avoids the cache
> // and is intended for use by DDL statements. It can be called either for a
> // traditional construction, which omits all regions in the OFFLINE state, or
> ```

s/OFFLINE/non-PUBLIC/g
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdNfF-RzPVWPivLun:-MWPdNfF-RzPVWPivLuo:b9rz1gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/catalog/typedesc/type_desc.go#L202)):*
> ```Go
> // enum to make validation with the public zone configs possible. Since the zone
> // configs are only updated at the end of the transaction, this must ignore all
> // regions being added, but it must include all region being dropped.
> ```

Could you add more words about why this is what we want even if some of the transitions were applied by a separate, concurrent transaction? (it is, right?)

Also, I think we should add a test testing this scenario as well. 


<!-- Sent from Reviewable.io -->

2021-03-22 16:35 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/region_util.go, line 939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdyWaACgJB4K60I65:-MWPkXk60gi6jCYD8m-E:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/region_util.go#L939)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/OFFLINE/non-PUBLIC/g
</blockquote></details>

Fixed.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdNfF-RzPVWPivLun:-MWPlxch5J5J5qagrbA4:bnqoq1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/catalog/typedesc/type_desc.go#L202)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you add more words about why this is what we want even if some of the transitions were applied by a separate, concurrent transaction? (it is, right?)

Also, I think we should add a test testing this scenario as well. 
</blockquote></details>

Changed.  There's a test for the two drops in the same transaction in pkg/ccl/logictestccl/testdata/logic_test/multi_region.  The concurrent transaction case should look exactly the same, so I'm not sure that there's much value in testing it separately (as it would be more involved to write).


<!-- Sent from Reviewable.io -->

2021-03-22 16:50 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdNfF-RzPVWPivLun:-MWPos8E557ip0Yu9sF-:b-lntiud) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/catalog/typedesc/type_desc.go#L202)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Changed.  There's a test for the two drops in the same transaction in pkg/ccl/logictestccl/testdata/logic_test/multi_region.  The concurrent transaction case should look exactly the same, so I'm not sure that there's much value in testing it separately (as it would be more involved to write).
</blockquote></details>

I'd feel much better about this patch if we had a test for concurrent transactions -- these things are quite tricky and we should bake in some regression insurance in here. 


<!-- Sent from Reviewable.io -->

2021-03-23 14:07 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdNfF-RzPVWPivLun:-MWUOmuH6j-pQNSkivkK:b-vvzvjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/catalog/typedesc/type_desc.go#L202)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'd feel much better about this patch if we had a test for concurrent transactions -- these things are quite tricky and we should bake in some regression insurance in here. 
</blockquote></details>

Ask (twice), and you shall receive.  I added a new test case in region_test.go.


<!-- Sent from Reviewable.io -->

2021-03-23 14:10 UTC, ajstorm commented
Gah!  Hold off on having another look.  Last minute changes broke the testcase.

2021-03-23 17:35 UTC, ajstorm commented
Thanks for holding off.  RFAL now.

2021-03-23 18:22 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-:-MWVJan-AGBkpwaeL5GU:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWVJDJf8BzrdINzQfJ_:-MWVJDJf8BzrdINzQfJa:bjxp64v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d85a719bf9b5c503bc01516c1830b28e863176/pkg/ccl/multiregionccl/region_test.go#L93)):*
> ```Go
> 
> 	// Validate that both DROP REGION statements completed.
> 	testutils.SucceedsSoon(t, func() error {
> ```

nit: do you still need this `SucceedsSoon`, or will it work deterministically now that you're syncing on `waitForFirstDropRegionToFinish`?
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWPdNfF-RzPVWPivLun:-MWVJSAE5u1qR1vveJ0u:b-ab1jro) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b80e9276259a264917bc034387a7f4db4f92af8/pkg/sql/catalog/typedesc/type_desc.go#L202)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Ask (twice), and you shall receive.  I added a new test case in region_test.go.
</blockquote></details>

Thanks :100: :100: 


<!-- Sent from Reviewable.io -->

2021-03-23 19:34 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62354)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62354#-MWVJDJf8BzrdINzQfJ_:-MWV_GwH0L8uk2jbKuzN:bw5rsfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0d85a719bf9b5c503bc01516c1830b28e863176/pkg/ccl/multiregionccl/region_test.go#L93)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: do you still need this `SucceedsSoon`, or will it work deterministically now that you're syncing on `waitForFirstDropRegionToFinish`?
</blockquote></details>

Good call.  I removed it.


<!-- Sent from Reviewable.io -->

2021-03-23 21:24 UTC, arulajmani approved these changes

2021-03-23 22:40 UTC, ajstorm commented
TFTR!

bors r=arulajmani

2021-03-24 01:11 UTC, otan commented
bors r-

i think this merge conflicts with master

2021-03-24 01:58 UTC, ajstorm commented
Worst part is, I was conflicting with myself.

2021-03-24 03:16 UTC, ajstorm commented
I think I've got it now.

bors r=arulajmani

2021-03-24 04:02 UTC, merged