kv: deflake multi-node kvnemesis
cockroachdb/cockroach pull request #62580
Opened 2021-03-25 03:32 UTC by nvanbenschoten

Fixes #61322.
Prep to address #59062.

#### kv: don't consider Subsume error as assertion failures

These were added in b15e3dd, but that was incorrect. It is valid for a merge that races with another merge or split to hit these case, as the Subsume request is non-transactional.

Also, allow `RHS range bounds do not match` errors in kvnemesis. This is a valid error for the reasons mentioned above.

#### kv: mark error from Replica.GetSnapshot with errMarkSnapshotError

Without it, we see the following errors in kvnemesis:
```
Wraps: (2) error applying x.AdminChangeReplicas(ctx, /Table/50/"244956da", [{ADD_VOTER n2,s2}]) // [n1,s1,r36/1:/Table/{40-50/"ba86b…}]: failed to generate LEARNER_INITIAL snapshot: couldn't find range descriptor
```

#### kv: allow two more errors with TransferLeaseOperation

This deflakes TestKVNemesisMultiNode.

2021-03-25 03:32 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62580)
<!-- Reviewable:end -->

2021-03-26 21:55 UTC, nvanbenschoten commented
This should be passing CI now. PTAL when you get a chance.

2021-03-28 01:36 UTC, aayushshah15 requested changes
LGTM mod that one question.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62580#-:-MWqTGSy3J6_towjbzV2:b-s94ngm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_command.go, line 2331 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62580#-MWqSHR7C2tgJ3mOHhNi:-MWqSHR7C2tgJ3mOHhNj:b-1iiy3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7d2018271ec9c1f552857af7e0f3b58fa507594/pkg/kv/kvserver/replica_command.go#L2331)):*
> ```Go
> 	if err != nil {
> 		err = errors.Wrapf(err, "%s: failed to generate %s snapshot", r, snapType)
> 		return errors.Mark(err, errMarkSnapshotError)
> ```

Are we seeing this because of a race between `AdminChangeReplicas` and a range-merge? Do you think its something like the following sequence of events?

- `AdminChangeReplicas` begins
- Adds a `LEARNER` and tries to generate a snapshot to send to it.
- A range merge begins, and commits (it will remove the `LEARNER` mentioned above).
- The RHS leaseholder that was in the process of generating a snapshot destroys itself (?)
- Boom


<!-- Sent from Reviewable.io -->

2021-03-28 01:37 UTC, aayushshah15 approved these changes

2021-03-30 03:45 UTC, nvanbenschoten commented
@aayushshah15 I actually couldn't fully explain the `failed to generate LEARNER_INITIAL snapshot: couldn't find range descriptor` error, nor could I explain why it suddenly began in https://github.com/cockroachdb/cockroach/issues/61322. So I decided to bisect. This revealed that the error only started firing in a75a28767d. Could you help me try to make sense of why that commit resulted in this new failure mode? Without understanding this better, I don't think that we should merge the second commit here and I think we should consider https://github.com/cockroachdb/cockroach/issues/61322 a `GA-blocker` as a precaution.

2021-03-30 03:50 UTC, aayushshah15 commented
Woah. Thanks for the bisect, I'll try and reproduce. Do you know roughly how frequent this was?

2021-03-30 04:14 UTC, nvanbenschoten commented
> Do you know roughly how frequent this was?

On `master` with `git cherry-pick 2e1bdc0 f7d2018` (the first and third commit here), it takes about 20,000 iterations to reproduce.

2021-03-31 02:27 UTC, aayushshah15 commented
I’m seeing that these `failed to generate snapshot` errors are caused by concurrent `AdminChangeReplicas` requests racing with lease transfers. The first `AdminChangeReplicas` tries to add a voter. However, before it can generate a snapshot to send to it, the leaseholder's lease gets transferred away and then a second `AdminChangeReplicas` instance removes the leaseholder that was generating the snapshot. As expected, running with lease transfers disabled makes the failure mode go away. It seems copacetic. 

I'm going to stress with the two commits from this PR on top of the commit preceeding a75a287 to see what's up.

2021-03-31 02:44 UTC, nvanbenschoten commented
> I'm going to stress with the two commits from this PR on top of the commit preceeding a75a287 to see what's up.

Thanks for looking into this. You will probably also want to patch in https://github.com/cockroachdb/cockroach/pull/61324 or you may hit deadlocks.

2021-03-31 02:45 UTC, aayushshah15 commented
OK, I got a `failed to generate LEARNER_INITIAL snapshot` repro on the commit that precedes a75a287 (i.e. dfcee20f6eea48d35f9241063222e3379fb9aa66) + the first and third commits from here. Interesting that it seems to have taken much longer. Maybe your bisection got unlucky?
```
94015 runs so far, 0 failures, over 3m50s
```

Let me know if something doesn't check out for you, but I _think_ we're fine.

2021-03-31 02:54 UTC, aayushshah15 commented
>I’m seeing that these failed to generate snapshot errors are caused by concurrent AdminChangeReplicas requests racing with lease transfers.

Here is what this looks like:
```
> cat testlogs/out | ag "(AdminChangeReplicas|TransferLease)"  
I210331 02:28:10.986078 3141 kv/kvnemesis/kvnemesis.go:79  [-] 291 +  2 OP  db1.AdminChangeReplicas(ctx, /Table/50/"16d710df", [{ADD_VOTER n4,s4}]) // nil
I210331 02:28:11.075964 3143 kv/kvnemesis/kvnemesis.go:79  [-] 303 +  4 OP  db1.TransferLeaseOperation(ctx, /Table/50/"18af73ad", 4) // nil
I210331 02:28:11.351242 3140 kv/kvnemesis/kvnemesis.go:79  [-] 410 +  1 OP  db0.AdminChangeReplicas(ctx, /Table/50/"064def8d", [{ADD_VOTER n3,s3} {REMOVE_VOTER n1,s1}]) // nil
I210331 02:28:11.999179 3141 kv/kvnemesis/kvnemesis.go:79  [-] 418 +  2 OP  db2.AdminChangeReplicas(ctx, /Table/50/"4aad0453", [{ADD_VOTER n2,s2}]) // [n1,s1,r36/1:/{Table/40-Max}]: failed to generate LEARNER_INITIAL snapshot: couldn't find range descriptor

```

2021-04-08 05:14 UTC, aayushshah15 commented
I'm thinking we should get this in sooner rather than later unless there's flakes that we don't understand. What do you think?

2021-04-08 16:52 UTC, nvanbenschoten commented
> Here is what this looks like:

Thanks! That's very helpful.

I'm still a little concerned that we don't know exactly why https://github.com/cockroachdb/cockroach/issues/61322 started failing so much more regularly on March 2nd, after having been fairly stable since Feb 22nd (https://github.com/cockroachdb/cockroach/issues/59287). Do you have thoughts about that? Is there something that landed around [this time](https://github.com/cockroachdb/cockroach/commits/1b18fc1fa8d9194d5e7f9aaa857425d80f0e4970) that made this race easier to hit? https://github.com/cockroachdb/cockroach/pull/61221 looks potentially related.

2021-04-08 16:59 UTC, nvanbenschoten commented
> #61221 looks potentially related.

I'm taking a look at this now. It's helpful to know that this isn't something new or fundamentally broken, but could have been made more common by a recent change. That changes what I'm looking for and may be why my bisection got messed up.

2021-04-08 18:18 UTC, nvanbenschoten commented
I thought more through the race in https://github.com/cockroachdb/cockroach/pull/62580#issuecomment-810719162 and am more convinced that it's not a new problem. The following patch makes it repro immediately. Furthermore, using the following patch, I was able to get this to reproduce all the way back on 23a4e63, which fixed https://github.com/cockroachdb/cockroach/issues/59287:

```
diff --git a/pkg/kv/kvnemesis/generator.go b/pkg/kv/kvnemesis/generator.go
index 0b4bbfe..2b7ce00 100644
--- a/pkg/kv/kvnemesis/generator.go
+++ b/pkg/kv/kvnemesis/generator.go
@@ -182,12 +182,12 @@ func newAllOperationsConfig() GeneratorConfig {
                        MergeIsSplit:  1,
                },
                ChangeReplicas: ChangeReplicasConfig{
-                       AddReplica:        1,
-                       RemoveReplica:     1,
-                       AtomicSwapReplica: 1,
+                       AddReplica:        10,
+                       RemoveReplica:     10,
+                       AtomicSwapReplica: 10,
                },
                ChangeLease: ChangeLeaseConfig{
-                       TransferLease: 1,
+                       TransferLease: 10,
                },
        }}
 }
diff --git a/pkg/kv/kvserver/replica_command.go b/pkg/kv/kvserver/replica_command.go
index 3b3b638..4985181 100644
--- a/pkg/kv/kvserver/replica_command.go
+++ b/pkg/kv/kvserver/replica_command.go
@@ -1661,6 +1661,10 @@ func (r *Replica) execReplicationChangesForVoters(
                        continue
                }

+               if len(voterRemovals) == 0 {
+                       time.Sleep(1000 * time.Millisecond)
+               }
+
                // Note that raft snapshot queue will refuse to send a snapshot to a learner
                // replica if its store is already sending a snapshot to that replica. That
                // would race with this snapshot, except that we've put a (best effort) lock
```

So something may have messed with the timings here to make this more likely, but it's nothing new, so https://github.com/cockroachdb/cockroach/pull/62580/commits/6ba24697c01db86cb082cf1e1e25593f616b16d8 does seem like the right change.

Thanks for the help with this @aayushshah15!

bors r+

2021-04-08 20:24 UTC, nvanbenschoten commented
Build flake in `Examples-ORMs`.

bors r+

2021-04-08 21:01 UTC, merged