release: publish to RedHat should use explicit tag
cockroachdb/cockroach pull request #62752
Opened 2021-03-29 20:38 UTC by rail

Previously, the publish to RedHat script was trying to compare the
version passed via TeamCity deploy parameters and TC_BUILD_BRANCH to
prevent using wrong commits for the process.

Apparently, the `$VERSION-$BUILD_NUMBER-$SHORT_SHA` style builds only
appear after we create the tag and start building the next version.

Instead, we can use the branch created after the tag is pushed. The name
doesn't contain any suffixes.

Release note: None

This is a screenshot of how the v20.2.7 publish release looks like.

![image](https://user-images.githubusercontent.com/42865/112896483-72d0e700-90ac-11eb-8843-ce0861a928b7.png)

And this is Publish to RedHat:
![image](https://user-images.githubusercontent.com/42865/112897050-2508ae80-90ad-11eb-873b-aaacfcb97237.png)

2021-03-29 20:38 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62752)
<!-- Reviewable:end -->

2021-04-07 01:56 UTC, jlinder requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[build/release/teamcity-publish-redhat-release.sh, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62752#-MXe1ocLE--StiUyKxwM:-MXe1ocLE--StiUyKxwN:b-hr7gu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8489aac0793bad792ede510373dc9c1a724e04/build/release/teamcity-publish-redhat-release.sh#L10)):*
> ```
> # Make sure that the version is a substring of TC branch name (e.g. v20.2.4-57-abcd345)
> # The "-" suffix makes sure we differentiate v20.2.4-57 and v20.2.4-5
> ```

Can you update this comment to reflect the new check?
___
*[build/release/teamcity-publish-redhat-release.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62752#-MXe0XE88z8UBtY754So:-MXe0XE9DWknKeHkPCnz:b-mk14a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8489aac0793bad792ede510373dc9c1a724e04/build/release/teamcity-publish-redhat-release.sh#L11)):*
> ```Shell
> # Make sure that the version is a substring of TC branch name (e.g. v20.2.4-57-abcd345)
> # The "-" suffix makes sure we differentiate v20.2.4-57 and v20.2.4-5
> if [[ $TC_BUILD_BRANCH != ${NAME} ]]; then
> ```

Since we are running this manually from the tag of the release, this change makes sense: "Ensure the tag is the same as the supplied name". However, when we get to modifying "Publish Cockroach Release" so it has a dependency build chain and this script is rolled into that build chain, we'll need to change this comparison. Can you add a comment that we'll need to change this at that time?


<!-- Sent from Reviewable.io -->

2021-04-07 16:17 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/release/teamcity-publish-redhat-release.sh, line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62752#-MXe1ocLE--StiUyKxwM:-MXh6n7U8OPWUZt_yoog:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8489aac0793bad792ede510373dc9c1a724e04/build/release/teamcity-publish-redhat-release.sh#L10)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> # Make sure that the version is a substring of TC branch name (e.g. v20.2.4-57-abcd345)
> # The "-" suffix makes sure we differentiate v20.2.4-57 and v20.2.4-5
> ```

Can you update this comment to reflect the new check?
</blockquote></details>

Done.
___
*[build/release/teamcity-publish-redhat-release.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62752#-MXe0XE88z8UBtY754So:-MXh6ozD2eklzS4JMlZx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb8489aac0793bad792ede510373dc9c1a724e04/build/release/teamcity-publish-redhat-release.sh#L11)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Since we are running this manually from the tag of the release, this change makes sense: "Ensure the tag is the same as the supplied name". However, when we get to modifying "Publish Cockroach Release" so it has a dependency build chain and this script is rolled into that build chain, we'll need to change this comparison. Can you add a comment that we'll need to change this at that time?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 16:20 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62752#-:-MXh7em42E__OVWisCN1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rail)



<!-- Sent from Reviewable.io -->

2021-04-07 16:21 UTC, rail commented
bors r+

2021-04-07 18:34 UTC, merged