console: filter out stats referencing dead nodes
cockroachdb/cockroach pull request #62917
Opened 2021-03-31 23:53 UTC by dhartunian

Previously, nodes could reference nodes we didn't know about in their
stats protos. Our frontend wouldn't know those nodeIDs because they
weren't in the list of known nodes that were returned from the DB and
would fail to render the network stats table.

Now we filter out any nodeIDs that are unknown to us so that we don't
render a broken table.

This is meant to be a targeted fix for a specific problem. Future work
will be done that addresses properly accounting for the various node
liveness states that have been changed on the backend and have not been
fully accounted for in the frontend.

Resolves #59322

Release note (ui change): Fixes a bug where nodes would reference dead
cluster nodes in their network stats and cause the network DB Console
page to crash.

2021-03-31 23:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62917)
<!-- Reviewable:end -->

2021-04-01 18:18 UTC, elkmaster approved these changes

2021-04-07 16:42 UTC, koorosh requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @nathanstilwell)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/62917#-MXhB8c75tP73-CYfOxK:-MXhB8c75tP73-CYfOxL:b6j643e) (no related file):*
Current change looks good to me 👍🏽 but also Network page can crash when network activity items (in node status) don't contain "latency" record. Regarding to code on backend side it is possible case. See `pkg/server/status/recorder.go` Line 401 (`getNetworkActivity` method).

Please take a look on PR with suggested fix: https://github.com/dhartunian/cockroach/pull/2

---


<!-- Sent from Reviewable.io -->

2021-04-15 14:12 UTC, nathanstilwell approved these changes
Given the "quick fix" nature of this PR, LGTM. I think Andrii's proposal is an interesting one, but can imagine a cleaner fix on the backend.

2021-04-16 08:16 UTC, koorosh commented
> Given the "quick fix" nature of this PR, LGTM. I think Andrii's proposal is an interesting one, but can imagine a cleaner fix on the backend.

Agree, this proposal isn't the best one, but probably a quick one  😃 
On backend, `latency` field is represented as `int64` type and cannot be set to `nil`, empty value for it is `0`. It'll indicate zero latency between nodes even when there is no connection between nodes. So probably it'll require extra field to work around this issue.

2021-10-21 22:03 UTC, closed without merging