build: refactor `teamcity-weekly-roachtest.sh` to depend on common code
cockroachdb/cockroach pull request #62987
Opened 2021-04-01 18:12 UTC by rickystewart

We can use the helper functionality here to log into `gcloud`, and the
helper code will clean the credentials up after the fact.

Also use the same pattern to clean up the SSH key after the job exits --
an alternative was also putting this into `teamcity-support.sh`, but
this pattern didn't really seem generally useful enough to bless by
putting it in a common library.

Release note: None

2021-04-01 18:12 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/62987)
<!-- Reviewable:end -->

2021-04-07 01:45 UTC, jlinder requested changes
I added a couple comments.

On testing, if you haven't already done so, I suggest getting this to run for your PR. A hack that could help is to temporarily change the script to only run one short test instead of all the tests (like how it's done in the roachtest nightly AWS build configuration). These tests all run pretty quickly (they are run in the `roachtest` build configuration that is run as part of the cockroach GitHub CI run): `acceptance`, `kv/splits`, `cdc/bank`.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-:-MXdybUk2q2zI69W0GQJ:b6ffz7a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/teamcity-weekly-roachtest.sh, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MXdyOXB1LB8sAJKb6fn:-MXdyOXB1LB8sAJKb6fo:ba6wwfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ba7013debae94a22f340f31abe9afd7a031164/build/teamcity-weekly-roachtest.sh#L9)):*
> ```Shell
> 
> google_credentials="$GOOGLE_EPHEMERAL_CREDENTIALS"
> source "$(dirname "${0}")/release/teamcity-support.sh"
> ```

I think it's better to keep only the scripts in `build/` using the `build/teamcity-support.sh` script and those in `build/release` using the `build/release/teamcity-support.sh` script. How about doing one of:

1. duplicate the function and supporting trap function into `build/teamcity-support.sh`
2. make a base shell file for the two `teamcity-support.sh` files to use and move the function and supporting function for the trap calls in the `teamcit-support.sh` files to call.
___
*[build/teamcity-weekly-roachtest.sh, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MXdySd10qC1wIq_xYiR:-MXdySd10qC1wIq_xYiS:b-5g3sff) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ba7013debae94a22f340f31abe9afd7a031164/build/teamcity-weekly-roachtest.sh#L18)):*
> ```Shell
> fi
> 
> remove_ssh_key_on_exit() {
> ```

Since there are multiple scripts that generate an SSH key that also need to be cleaned up, I think it's better to add a function to generate the SSH key in the `build/teamcity-support.sh` script and do the appropriate cleanup in the function called by `trap` (which isn't there yet) in that file. Then the other scripts can be updated in a separate PR (this is not a request that you make those changes too).
___
*[build/teamcity-weekly-roachtest.sh, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MXdyXdbCysjtHjQ6xap:-MXdyXdbCysjtHjQ6xaq:bkyo1yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ba7013debae94a22f340f31abe9afd7a031164/build/teamcity-weekly-roachtest.sh#L21)):*
> ```Shell
>     rm -f ~/.ssh/id_rsa{,.pub}
> }
> trap remove_ssh_key_on_exit EXIT
> ```

A note on how the slightly funky bash `trap` works. If a script contains multiple `trap` calls, only the function for the last `trap` call that was made will run on exit. Since the `teamcity-support.sh` file contains a `trap` and that file is sourced by this file, this call would come last and overwrite the one from `teamcity-support.sh`.


<!-- Sent from Reviewable.io -->

2021-04-09 20:44 UTC, rickystewart commented
Gonna run a test run, hold on.

2021-04-13 16:36 UTC, rickystewart commented
[Successful build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2874180&).

2021-04-13 18:50 UTC, jlinder reviewed
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62987)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/teamcity-common-support.sh, line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MYBVYyQ9KpNLzEUTOZS:-MYBVYyR4LD-WXcZFYV6:bv0phjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc61c7df12d4828e3310a1ffcc3b696c8d40ae8f/build/teamcity-common-support.sh#L9)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> remove_files_on_exit() {
>   rm -f .google-credentials.json
>   rm -f .cockroach-teamcity-key
>   rm -rf ~/.docker
>   rm -f ~/.ssh/id_rsa{,.pub}
> }
> trap remove_files_on_exit EXIT
> ```
</details>


Suggestion:

An alternative way to putting the `trap` call all the way in the bottom sourced file is to make a function in this file that only cleans up what this file needs cleaned up and then that function is called from `trap` functions in the `*/teamcity-support.sh` scripts. This also makes a pattern where if a `trap` call really needs to be made in a script using a `teamcity-support.sh` script, then the function used in that `trap` call can simply call the trap function from the `teamcity-support.sh` script.

A good name for the function might be `common_support_remove_files_on_exist`?
___
*[build/teamcity-support.sh, line 291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MYBYGqjAsIQWeZTvgBT:-MYBYGqkBk0PRfuY3Rjy:btl6yr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc61c7df12d4828e3310a1ffcc3b696c8d40ae8f/build/teamcity-support.sh#L291)):*
> ```Shell
> generate_ssh_key() {
>     if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
> 	ssh-keygen -q -N "" -f ~/.ssh/id_rsa
> ```

Indent please.


<!-- Sent from Reviewable.io -->

2021-04-13 20:36 UTC, jlinder approved these changes
Left one final note and then LGTM!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-:-MYBweeB8OL7pEshdOgU:b-jjz93r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/release/teamcity-support.sh, line 8 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62987#-MYBwQji4bTvzwDw-2vs:-MYBwQji4bTvzwDw-2vt:bww0rtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3a44ad00684b2ac6b803180d3924ba44e5bfad4/build/release/teamcity-support.sh#L8)):*
> ```Shell
> 
> remove_files_on_exit() {
>   rm -f .google-credentials.json
> ```

Since this file now gets removed in common_support_remove_files_on_exit, it doesn't need to be removed here too.


<!-- Sent from Reviewable.io -->

2021-04-14 15:48 UTC, rickystewart commented
> Since this file now gets removed in common_support_remove_files_on_exit, it doesn't need to be removed here too.

Whoops, you got it.

2021-04-14 15:53 UTC, rickystewart commented
bors r=jlinder

2021-04-14 16:53 UTC, merged