bazel: point to our fork of `rules_go` rather than upstream
cockroachdb/cockroach pull request #63034
Opened 2021-04-02 19:48 UTC by rickystewart

We want the test runner to be verbose about the actual exit code
returned by failing tests; so I added [a commit](https://github.com/cockroachdb/rules_go/commit/2fe8a6256c818840cc9a10cf3f366d8410437245)
to do this, and we point to this commit in `WORKSPACE`.

Release note: None

2021-04-02 19:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63034)
<!-- Reviewable:end -->

2021-04-05 14:36 UTC, rail commented
Can we upstream this?

2021-04-05 14:42 UTC, rail requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63034)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[WORKSPACE, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63034#-MXXTnxd9e4HggQxddP7:-MXXTnxd9e4HggQxddP8:bn6aqqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f850835741a28590bb164acdc29f9fb28512b702/WORKSPACE#L16)):*
> ```Starlark
>     name = "io_bazel_rules_go",
>     commit = "2fe8a6256c818840cc9a10cf3f366d8410437245",
>     remote = "https://github.com/cockroachdb/rules_go",
> ```

Can we use https://github.com/cockroachdb/rules_go/archive/2fe8a6256c818840cc9a10cf3f366d8410437245.tar.gz instead, so we don't pull the whole repo, similar to the original approach?


<!-- Sent from Reviewable.io -->

2021-04-05 15:21 UTC, rickystewart commented
> Can we upstream this?

I don't think this is generally useful. There certainly hasn't been community demand for this one extra line of logging *shrug*

> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63034)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)
> 
> _[WORKSPACE, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63034#-MXXTnxd9e4HggQxddP7:-MXXTnxd9e4HggQxddP8:bn6aqqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f850835741a28590bb164acdc29f9fb28512b702/WORKSPACE#L16)):_
> 
> > ```python
> >     name = "io_bazel_rules_go",
> >     commit = "2fe8a6256c818840cc9a10cf3f366d8410437245",
> >     remote = "https://github.com/cockroachdb/rules_go",
> > ```
> 
> Can we use https://github.com/cockroachdb/rules_go/archive/2fe8a6256c818840cc9a10cf3f366d8410437245.tar.gz instead, so we don't pull the whole repo, similar to the original approach?

Bazel doesn't like this: it yells at me with this error --

    ERROR: error loading package '': in /private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/external/bazel_gazelle/deps.bzl: in /private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/external/bazel_gazelle/internal/go_repository_cache.bzl: Every .bzl file must have a corresponding package, but '@io_bazel_rules_go//go/private:common.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.

I don't think Bazel does a full clone under the hood anyway, and this was never the bottleneck in either case.

2021-04-05 15:23 UTC, rail approved these changes

2021-04-05 15:55 UTC, rickystewart commented
bors r+

2021-04-05 16:45 UTC, merged