opt: index accelerate JSON filters in the forms j->'a' @> '1' and j->'a' <@ '1'
cockroachdb/cockroach pull request #63048
Opened 2021-04-03 00:14 UTC by angelazxu

We previously did not have inverted index support for expressions with a
JSON fetch val operator on the left side of @> (contains) or <@ (contained by)
expressions.

This commit adds support to use the inverted index for query filters with JSON
fetch val and containment operators. These include any contains or contained by
expressions with fetch val or chained fetch val operators on the left side, and
a constant value on the right side, including booleans, strings, numbers,
nulls, arrays, and objects.

Fixes #61430

Release note (performance improvement): Expressions with the -> (fetch val)
operator on the left side of either <@ (contained by) or @> (contains) now
support index-acceleration.

2021-04-03 00:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63048)
<!-- Reviewable:end -->

2021-04-03 00:19 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu)

___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXK4PJFEp89x-6dPOYD:-MXK4PJFEp89x-6dPOYE:bazv1b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1431)):*
> ```
>   estimated row count: 3 (missing stats)
>   table: inv@iv_j_idx
>   spans: /10/"a"/"a"/"b"-/10/"a"/"a"/"b"/PrefixEnd /20/"a"/"a"/"b"-/20/"a"/"a"/"b"/PrefixEnd /30/"a"/"a"/"b"-/30/"a"/"a"/"b"/PrefixEnd
> ```

The (j->'a') virtual column index is not longer used here, possibly because this change now supports j->'a' in general, so the costs might be the same? Not sure if it matters, or if we want to make it so we choose the virtual column when it's available?


<!-- Sent from Reviewable.io -->

2021-04-05 15:00 UTC, rytaft reviewed
Awesome! This is a tricky one but you did a really nice job using the building blocks we already have.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-:-MXXURK050DY_XuFQQf4:b-xmkpba)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXX18LAibzt1A8BXuz:-MXWud2T7jtdkSmkJYVd:b-o2k27x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/logictest/testdata/logic_test/inverted_index#L772)):*
> ```
>   (28, '[{"a": {"b": "c"}}, "d", "e"]'),
>   (29, '{"a": null}'),
>   (30, '{"a": [1, 2, null]}')
> ```

can you add rows with `{}`, `[]`, and NULL?
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 982 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWu6kq5vJufN_I4dfG:-MXWu6kq5vJufN_I4dfH:b-vb9g3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/logictest/testdata/logic_test/inverted_index#L982)):*
> ```
> ----
> {"a": null}
> ```

Can you add a few more tests, just to check the logic with empty arrays/objects:
`SELECT j FROM f@i WHERE j->'a' <@ '{"b": [1, 2]}'`
`SELECT j FROM f@i WHERE j->'a' <@ '[]'`
`SELECT j FROM f@i WHERE j->'a' <@ '{}'`
`SELECT j FROM f@i WHERE j->'a' @> '[]'`
`SELECT j FROM f@i WHERE j->'a' @> '{}'`

Also would be good to add some tests with a couple of different nesting levels of arrays/objects. The logic is pretty tricky here, so in the absence of randomized tests I want to make sure we've covered a wide range of cases.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWv81o-wM9rwreb6fN:-MXWuhwN3Un2qaq07Hx4:buzpsuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L464)):*
> ```
>                   estimated row count: 111 (missing stats)
>                   table: d@foo_inv
>                   spans: /{}-/{}/PrefixEnd /"a"/"b"-/"a"/"b"/PrefixEnd
> ```

It's unfortunate that we need to scan `{}` here, but I'm not sure it's worth the complexity to avoid it...

Might be worth opening an issue to track or at least adding a TODO somewhere in the code
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXPhDh1k6b-c1P1MdS:-MXXPhDh1k6b-c1P1MdT:bmfhduw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L496)):*
> ```
>                   estimated row count: 111 (missing stats)
>                   table: d@foo_inv
>                   spans: /{}-/{}/PrefixEnd /"a"/{}-/"a"/{}/PrefixEnd /"a"/{}-/"a"/{}/PrefixEnd /"a"/"c"/"b"-/"a"/"c"/"b"/PrefixEnd
> ```

Do you know why we're including the spans for `{"a": {}}` twice? Not really a big deal, but maybe we're doing extra work that's not needed?
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXQ2sc9lB15OAG2f93:-MXXQ2sd6evelnIsRsXe:b9r5rfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L552)):*
> ```
>                   estimated row count: 111 (missing stats)
>                   table: d@foo_inv
>                   spans: /{}-/{}/PrefixEnd /"a"/1-/"a"/1/PrefixEnd /"a"/2-/"a"/2/PrefixEnd /"a"/[]-/"a"/{} /"a"/[]-/"a"/{} /"a"/Arr/1-/"a"/Arr/1/PrefixEnd /"a"/Arr/2-/"a"/Arr/2/PrefixEnd
> ```

`{"a": []}` is duplicated here too
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXK4PJFEp89x-6dPOYD:-MXWxfqNASya4dGQv2cs:b36g1sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1431)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

The (j->'a') virtual column index is not longer used here, possibly because this change now supports j->'a' in general, so the costs might be the same? Not sure if it matters, or if we want to make it so we choose the virtual column when it's available?
</blockquote></details>

I think it's ok that we don't choose the virtual column, but it may be a sign that our costing isn't quite right. I'd just update the comment for this test case and change it to a TODO to investigate. If you can find another test case that does use the virtual column then that would be great to include (e.g., what if you change the predicate to <@ instead of @>?), but I don't think it's essential. 
___
*[pkg/sql/opt/invertedidx/json_array.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWzoCsEfMrinW39_3Z:-MXWzoCtDa809jEjOMzX:bubqkgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L387)):*
> ```Go
> 	} else {
> 		if fetch, ok := left.(*memo.FetchValExpr); ok {
> 			// When the expression has a JSON fetch operator on the left, it is handled in extractJSONFetchValCondition.
> ```

do you have any test cases where the fetch val condition is on the right? can we handle that case?
___
*[pkg/sql/opt/invertedidx/json_array.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXX3UvD0s8v-BCs0I6Y:-MXWz68c63UHG7F1-z7j:b-zgderw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L423)):*
> ```Go
> 	left *memo.FetchValExpr,
> 	right opt.ScalarExpr,
> 	equals, containedBy bool,
> ```

The two booleans here is getting a bit awkward... just passing the operator directly might be better, but I also see why you did it this way. Either way, this needs a comment explaining what the parameters mean (and that if `equals` is true then `containedBy` is ignored)
___
*[pkg/sql/opt/invertedidx/json_array.go, line 508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXVlSn67utdc3amQEH:-MXXVHws4W06Gb0_2Hjn:b8p5m27) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L508)):*
> ```Go
> 		return invertedExpr
> 	}
> 	// For Contains and ContainedBy expressions, we may need to build additional
> ```

nit: add a blank line above to separate this out
___
*[pkg/sql/opt/invertedidx/json_array.go, line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXPE-N9CkQs3q8-Hx1:-MXXPE-N9CkQs3q8-Hx2:b89zo1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L517)):*
> ```Go
> 	// We get an inverted expression for each object constructed, and union
> 	// these expressions.
> 	for i := 0; i < len(objs); i++ {
> ```

nit: can do `for i := range objs`
___
*[pkg/sql/opt/invertedidx/json_array.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXW7ejAnGdqv7HWbsY:-MXXW7ejAnGdqv7HWbsZ:b-xo3ak3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L534)):*
> ```Go
> 
> // fetchContainmentObjects constructs new JSON objects based on the value type and
> // whether the expression uses <@ or @>. An array of these JSONs is returned.
> ```

nit: this comment could use a bit more info to explain that the keys and val come from a fetchVal expression, maybe with an example
___
*[pkg/sql/opt/invertedidx/json_array.go, line 540 at r1](https://reviewable.io/reviews/cockroach [...]

2021-04-08 15:35 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 772 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXX18LAibzt1A8BXuz:-MX_weM61zTVT7IqniKe:b-mahidu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/logictest/testdata/logic_test/inverted_index#L772)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can you add rows with `{}`, `[]`, and NULL?
</blockquote></details>

Added - also created the issue I mentioned: #63180 
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 982 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWu6kq5vJufN_I4dfG:-MXiOeGy9qcmnZz9Xo5O:b-it0rrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/logictest/testdata/logic_test/inverted_index#L982)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a few more tests, just to check the logic with empty arrays/objects:
`SELECT j FROM f@i WHERE j->'a' <@ '{"b": [1, 2]}'`
`SELECT j FROM f@i WHERE j->'a' <@ '[]'`
`SELECT j FROM f@i WHERE j->'a' <@ '{}'`
`SELECT j FROM f@i WHERE j->'a' @> '[]'`
`SELECT j FROM f@i WHERE j->'a' @> '{}'`

Also would be good to add some tests with a couple of different nesting levels of arrays/objects. The logic is pretty tricky here, so in the absence of randomized tests I want to make sure we've covered a wide range of cases.
</blockquote></details>

Added the tests you listed and a couple of nested arrays/objects, also rearranged and grouped similar cases so hopefully it's easier to look through! Also - currently two cases are commented out temporarily due to the issue I mentioned above, and will be able to be run after #63196 is merged.
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWv81o-wM9rwreb6fN:-MXaE_eGDb8NcX5YeZgt:bwamme8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L464)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's unfortunate that we need to scan `{}` here, but I'm not sure it's worth the complexity to avoid it...

Might be worth opening an issue to track or at least adding a TODO somewhere in the code
</blockquote></details>

added a TODO above the test case, also created the issue here: #63184  
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXPhDh1k6b-c1P1MdS:-MXaGZ0nCFOmtEwN0guN:bl8a22l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L496)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you know why we're including the spans for `{"a": {}}` twice? Not really a big deal, but maybe we're doing extra work that's not needed?
</blockquote></details>

So for b->'a'->'c' <@ '"b"' we would be constructing {"a": {"c": "b"}}, which means the spans for `{"a": {}}` are created twice somewhere in `encodeContainedInvertedIndexSpans`...
I spent some time stepping through the code and it looks like this is happening:

In the for loop, when the value/child is an object, we call the function twice - on the non-empty child and on an empty child with `prefixWithEnd`.
At the beginning of the function, we create the empty object span with the prefix and union this span with whatever else is created - so the non-empty child function call returns an extra empty object value span.

I was able to fix this and get rid of all the duplicate spans, but I'll put those changes in a separate PR and link it below :)
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXQ2sc9lB15OAG2f93:-MXkbCEbCWQtviAPC8VT:b-8tvjba) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L552)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

`{"a": []}` is duplicated here too
</blockquote></details>

also due to what I mentioned above, will be fixed in that PR!
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXK4PJFEp89x-6dPOYD:-MXaYzdS3nioOr9lQ2vH:b-yphlm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1431)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it's ok that we don't choose the virtual column, but it may be a sign that our costing isn't quite right. I'd just update the comment for this test case and change it to a TODO to investigate. If you can find another test case that does use the virtual column then that would be great to include (e.g., what if you change the predicate to <@ instead of @>?), but I don't think it's essential. 
</blockquote></details>

Ran a test with <@ and it doesn't use the virtual column either, added a TODO 
___
*[pkg/sql/opt/invertedidx/json_array.go, line 387 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWzoCsEfMrinW39_3Z:-MXdYeOz5mFABivm8k6h:bih478l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L387)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you have any test cases where the fetch val condition is on the right? can we handle that case?
</blockquote></details>

Just added support for that case! We will just pass it into `extractJSONFetchValCondition` as the equivalent expression with fetch val on the left and flip the contains/containedby operator. The rest should follow the existing logic, so I just added a few test cases in each of the test files.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXX3UvD0s8v-BCs0I6Y:-MX_Rt-TEOx0gwMmNC7m:b-kjr6g8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L423)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The two booleans here is getting a bit awkward... just passing the operator directly might be better, but I also see why you did it this way. Either way, this needs a comment explaining what the parameters mean (and that if `equals` is true then `containedBy` is ignored)
</blockquote></details>

Ah yes it is kinda awkward, but I wanted  the `containedBy` bool since it's more convenient to use in a lot of places :) added comment!


<!-- Sent from Reviewable.io -->

2021-04-08 18:01 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXX3UvD0s8v-BCs0I6Y:-MXmcoPaDLcb_ZSVjtMO:b-wk93al) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L423)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Ah yes it is kinda awkward, but I wanted  the `containedBy` bool since it's more convenient to use in a lot of places :) added comment!
</blockquote></details>

If you extract `collectKeys` to a separate helper function, then you could have two `extractJSONFetchValCondition...` functions, one for `=` and one for `@>` and `<@`, without too much duplication. That might make things simpler.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXmcJen1rCu6GrXiqsf:-MXmcJen1rCu6GrXiqsg:bwxtlmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2082d5d0e95f2c1c3428ec4ccd901fd4793d56e9/pkg/sql/opt/invertedidx/json_array.go#L539)):*
> ```Go
> 			invertedExpr = expr
> 		} else {
> 			invertedExpr = inverted.Or(invertedExpr, expr)
> ```

Do we need to explicitly set this expr as "not tight" with `invertedExpr.SetNotTight()`? `inverted.Or` returns a `tight=true` expression if both the left and the right input are tight, but in this case where we are manufacturing this union it seems like it would never be tight. Is there a test case that proves this is ok or not?
___
*[pkg/sql/opt/invertedidx/json_array.go, line 551 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXmaa-Q0OA_ysz7oRRm:-MXmaa-Q0OA_ysz7oRRn:b-g4mte0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2082d5d0e95f2c1c3428ec4ccd901fd4793d56e9/pkg/sql/opt/invertedidx/json_array.go#L551)):*
> ```Go
> // {"a", "b"} as keys, "c" as val, and construct {"a": "b": ["c"]}.
> // An array of the constructed JSONs is returned.
> func fetchContainmentObjects(keys []string, val json.JSON, containedBy bool) ([]json.JSON, error) {
> ```

nit: it might be more clear to name this `buildFetchContainmentObjects` or use some verb other than `fetch`. `fetch` sounds like a verb that this function is doing, but it's not "fetching", it's just related to `FetchVal` operators.


<!-- Sent from Reviewable.io -->

2021-04-08 22:00 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/invertedidx/json_array.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXX3UvD0s8v-BCs0I6Y:-MXnLDqWCmluUVa_-CMd:b-f1tbhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/invertedidx/json_array.go#L423)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If you extract `collectKeys` to a separate helper function, then you could have two `extractJSONFetchValCondition...` functions, one for `=` and one for `@>` and `<@`, without too much duplication. That might make things simpler.
</blockquote></details>

Oh!! Changed it :D
___
*[pkg/sql/opt/invertedidx/json_array.go, line 539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXmcJen1rCu6GrXiqsf:-MXnNEBaDif7jG8_4jCE:b-djp2sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2082d5d0e95f2c1c3428ec4ccd901fd4793d56e9/pkg/sql/opt/invertedidx/json_array.go#L539)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we need to explicitly set this expr as "not tight" with `invertedExpr.SetNotTight()`? `inverted.Or` returns a `tight=true` expression if both the left and the right input are tight, but in this case where we are manufacturing this union it seems like it would never be tight. Is there a test case that proves this is ok or not?
</blockquote></details>

So all <@ expressions are not tight, only some of the @>  expressions have `tight=true`, which I think is okay - for example, we convert something like` j->'a'->'b' @> [1]` to `j @> {"a": {"b": [1]}}` which has tight spans, and there wouldn't be any JSONs satisfying the second expression that wouldn't satisfy the first. Based on all the logic tests I've run comparing queries using `j@i` vs. `j@primary`, there hasn't been any cases where tight spans produce incorrect results. I think in cases where the expression has a single scalar/array/object on the right side of @>, the span is tight. For all other cases, it wouldn't be tight, and this is already checked for in `encodeContainedInvertedIndexSpans`/`encodeContainingInvertedIndexSpans`


<!-- Sent from Reviewable.io -->

2021-04-08 23:22 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXPhDh1k6b-c1P1MdS:-MXnmsKSAgSj1OgqsJJl:bbp0coo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L496)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

So for b->'a'->'c' <@ '"b"' we would be constructing {"a": {"c": "b"}}, which means the spans for `{"a": {}}` are created twice somewhere in `encodeContainedInvertedIndexSpans`...
I spent some time stepping through the code and it looks like this is happening:

In the for loop, when the value/child is an object, we call the function twice - on the non-empty child and on an empty child with `prefixWithEnd`.
At the beginning of the function, we create the empty object span with the prefix and union this span with whatever else is created - so the non-empty child function call returns an extra empty object value span.

I was able to fix this and get rid of all the duplicate spans, but I'll put those changes in a separate PR and link it below :)
</blockquote></details>

#63355


<!-- Sent from Reviewable.io -->

2021-04-09 00:30 UTC, mgartner requested changes
> Reviewed 1 of 7 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXnxYzcCqyWge_XQyMR:-MXnxYzcCqyWge_XQyMS:bzdzhn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/logictest/testdata/logic_test/inverted_index#L952)):*
> ```
> 
> query T
> SELECT j FROM f@i WHERE j->'a' <@ '{"b": [1, 2]}' ORDER BY k
> ```

Can you add a row that is `{"a": {"b": []}}` and make sure it is returned for this case? Unless there is another test that is testing something like this already that I'm not seeing.
___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1041 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXnxPYs3JkjBcscL14I:-MXnxPYt5yaBHC7hUbAz:b-gzmfm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1041)):*
> ```
> # query T
> # SELECT j FROM f@i WHERE j->'a' @> '"b"' AND j->'a' <@ '["b", "c", "d", "e"]' ORDER BY k
> # ----
> ```

nit: Add a `TODO(angelazxu): Uncommented these tests once #63180 is fixed.`
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 435 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXnyPhfA5QwIroTz5y1:-MXnyPhfA5QwIroTz5y2:bk635pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L435)):*
> ```
> 
> # TODO(angelazxu): The {} span does not need to be scanned here, but is
>  # included when finding spans contained by {"a": "b"} (see #63184).
> ```

nit: remove space at the beginning of the line
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXK4PJFEp89x-6dPOYD:-MXnz9Rq5G1sj_ipNUpC:b-g512kl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1431)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

Ran a test with <@ and it doesn't use the virtual column either, added a TODO 
</blockquote></details>

I think the actual cost of scanning `iv_jv_idx` and `iv_j_idx` would be the same in this case - the same number of inverted index entries would be scanned in both cases. Or would we consider the former cheaper because the keys are shorter? Would that have a significant impact on the scan performance?

You could just remove your TODO and drop the `iv_j_idx` right before this test so that the test still exercises what it was originally meant to - to verify that we can plan a scan on a multi-column inverted index where the prefix and inverted columns are virtual.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 539 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXmcJen1rCu6GrXiqsf:-MXo0TNm4tsc_B_0zUaS:b6zavvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2082d5d0e95f2c1c3428ec4ccd901fd4793d56e9/pkg/sql/opt/invertedidx/json_array.go#L539)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

So all <@ expressions are not tight, only some of the @>  expressions have `tight=true`, which I think is okay - for example, we convert something like` j->'a'->'b' @> [1]` to `j @> {"a": {"b": [1]}}` which has tight spans, and there wouldn't be any JSONs satisfying the second expression that wouldn't satisfy the first. Based on all the logic tests I've run comparing queries using `j@i` vs. `j@primary`, there hasn't been any cases where tight spans produce incorrect results. I think in cases where the expression has a single scalar/array/object on the right side of @>, the span is tight. For all other cases, it wouldn't be tight, and this is already checked for in `encodeContainedInvertedIndexSpans`/`encodeContainingInvertedIndexSpans`
</blockquote></details>

Makes sense, thanks for the explanation!
___
*[pkg/sql/opt/invertedidx/json_array.go, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo-SYn4Chh_80zutm6:-MXo-SYn4Chh_80zutm7:bq12pgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L547)):*
> ```Go
> func (j *jsonOrArrayFilterPlanner) collectKeys(
> 	currKeys []string, fetch *memo.FetchValExpr,
> ) (keys []string, foundKeys bool) {
> ```

nit: it might be more idiomatic to rename `foundKeys` to `ok`. you could also remove the bool entirely and return empty `keys` in the case that we can't collect any, and check the length of the keys from the call sites.
___
*[pkg/sql/opt/invertedidx/json_array.go, line 552 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo-yeaEe-Y7R688L18:-MXo-yeaEe-Y7R688L19:bgd8aoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L552)):*
> ```Go
> 	// expression.
> 	if !memo.CanExtractConstDatum(fetch.Index) {
> 		return
> ```

nit: make the return values explicit: `return nil, false`
___
*[pkg/sql/opt/invertedidx/json_array.go, line 556 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo06Up1qzfvpe7Cet4:-MXo06Up1qzfvpe7Cet5:b-67e5nw) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L556)):*
> ```Go
> 	key, ok := memo.ExtractConstDatum(fetch.Index).(*tree.DString)
> 	if !ok {
> 		return
> ```

ditto: make the return values explicit: `return nil, false`
___
*[pkg/sql/opt/invertedidx/json_array.go, line 573 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo0d-e78e8ND8gQJvc:-MXo0d-e78e8ND8gQJvd:bitn9yx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L573)):*
> ```Go
> 	if innerFetch, ok := fetch.Json.(*memo.FetchValExpr); ok {
> 		keys, foundKeys := j.collectKeys(keys, innerFetch)
> 		return keys, foundKeys
> ```

If you remove the bool return value (suggested above), these two lines simplify to `return j.collectKeys(keys)`


<!-- Sent from Reviewable.io -->

2021-04-09 01:11 UTC, rytaft reviewed
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu and @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1041 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXnxPYs3JkjBcscL14I:-MXo3n9e5es4f4yN-Vr7:bubvpn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1041)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Add a `TODO(angelazxu): Uncommented these tests once #63180 is fixed.`
</blockquote></details>

Could you also try rebasing this PR on top of #63355 if you haven't already and see if it fixes these tests? I think the duplicate spans you fixed in #63355 had incorrect JSON encodings, and I am wondering if by chance that could be the cause of #63180?
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 464 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXWv81o-wM9rwreb6fN:-MXo64mbAQw-bjzuSWBQ:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L464)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

added a TODO above the test case, also created the issue here: #63184  
</blockquote></details>

Thanks!
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXXPhDh1k6b-c1P1MdS:-MXo6K5Y5utHk_LAJA3Y:b-oxgb06) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L496)):*
<details><summary><i>Previously, angelazxu (Angela Xu) wrote…</i></summary><blockquote>

#63355
</blockquote></details>

Good find!
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 607 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo6gWcD0bo5bm1D6Ly:-MXo6gWcD0bo5bm1D6Lz:b920ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L607)):*
> ```
> 
> query T
> EXPLAIN (VERBOSE) SELECT * from d where '"b"' <@ b->'a'
> ```

did you intend for this to use the inverted index? You could force it with `d@foo_inv` if that was the intention
___
*[pkg/sql/opt/invertedidx/json_array.go, line 537 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo8TJNBGiomCDMmJ1N:-MXo8TJNBGiomCDMmJ1O:brtdr9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L537)):*
> ```Go
> // outer-most fetch val index.
> //
> // Later on, we iterate forward through these keys to build a JSON object
> ```

nit: now that this is a separate function, I'd change "Later on, we" to "Callers of this function should"
___
*[pkg/sql/opt/invertedidx/json_array.go, line 579 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo8w6O334_gz6IXdOj:-MXo8w6O334_gz6IXdOk:b-x9np5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L579)):*
> ```Go
> }
> 
> // fetchContainmentObjects constructs new JSON objects with given keys and val.
> ```

nit: update to match function name


<!-- Sent from Reviewable.io -->

2021-04-11 20:33 UTC, angelazxu reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 1041 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXnxPYs3JkjBcscL14I:-MY13CTIDkAyP_haKrrs:bdj0ccu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/logictest/testdata/logic_test/inverted_index#L1041)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Could you also try rebasing this PR on top of #63355 if you haven't already and see if it fixes these tests? I think the duplicate spans you fixed in #63355 had incorrect JSON encodings, and I am wondering if by chance that could be the cause of #63180?
</blockquote></details>

Added the comment, tried rebasing but still getting the errors (as mentioned in slack)
___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_index, line 607 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo6gWcD0bo5bm1D6Ly:-MY1-SlG7yX3scKUL1bC:b-qsseby) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/exec/execbuilder/testdata/inverted_index#L607)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

did you intend for this to use the inverted index? You could force it with `d@foo_inv` if that was the intention
</blockquote></details>

fixed!
___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 1431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXK4PJFEp89x-6dPOYD:-MY1TndzBxwXJIijtEXS:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ad2ec037f6a742058122f26861f3b1ed89f78f5/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L1431)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the actual cost of scanning `iv_jv_idx` and `iv_j_idx` would be the same in this case - the same number of inverted index entries would be scanned in both cases. Or would we consider the former cheaper because the keys are shorter? Would that have a significant impact on the scan performance?

You could just remove your TODO and drop the `iv_j_idx` right before this test so that the test still exercises what it was originally meant to - to verify that we can plan a scan on a multi-column inverted index where the prefix and inverted columns are virtual.
</blockquote></details>

done!
___
*[pkg/sql/opt/invertedidx/json_array.go, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo-SYn4Chh_80zutm6:-MY0zbePAMYrMD32yxXG:b5gs7ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L547)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: it might be more idiomatic to rename `foundKeys` to `ok`. you could also remove the bool entirely and return empty `keys` in the case that we can't collect any, and check the length of the keys from the call sites.
</blockquote></details>

removed the bool!
___
*[pkg/sql/opt/invertedidx/json_array.go, line 556 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo06Up1qzfvpe7Cet4:-MY0xYTGENkZ_YjTWFxZ:bv4laxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L556)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

ditto: make the return values explicit: `return nil, false`
</blockquote></details>

Done. (`return nil` now since I removed the bool)
___
*[pkg/sql/opt/invertedidx/json_array.go, line 573 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-MXo0d-e78e8ND8gQJvc:-MY0zTBHENSwLqQpR70_:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae73f26228760e8abf65767aed6305fab89cb2f/pkg/sql/opt/invertedidx/json_array.go#L573)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If you remove the bool return value (suggested above), these two lines simplify to `return j.collectKeys(keys)`
</blockquote></details>

done!


<!-- Sent from Reviewable.io -->

2021-04-12 15:53 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Nice work!

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-:-MY5mJLJ4d2CjTOXkXNL:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2021-04-12 18:21 UTC, mgartner approved these changes
Nicely done. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048#-:-MY6JLsBDr9TFDzRK3CH:b-ozfbe9)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)



<!-- Sent from Reviewable.io -->

2021-04-12 19:19 UTC, rytaft approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63048)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @angelazxu)



<!-- Sent from Reviewable.io -->

2021-04-12 19:49 UTC, angelazxu commented
bors r+

2021-04-12 20:40 UTC, merged