sql: wrap CastExpr within IndirectionExpr in a ParenExpr
cockroachdb/cockroach pull request #63103
Opened 2021-04-05 18:05 UTC by the-ericwang35

Fixes https://github.com/cockroachdb/cockroach/issues/63097.

When we type check ParenExpr, we remove the parentheses.
This can cause issues for IndirectionExprs.

For example, something like `('{a}'::_typ)[1]` would
turn into `'{a}'::_typ[1]` after type checking, resulting
in the `[1]` being interpreted as part of the type.
This would result in errors when trying to use these
expressions in default expressions.
This patch checks for this specific case, and if
it finds that there is a CastExpr within an IndirecionExpr,
it will wrap it in a ParenExpr.

Release note: None

2021-04-05 18:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63103)
<!-- Reviewable:end -->

2021-04-05 19:22 UTC, ajwerner reviewed
Can you add some cases into `type_check_test.go`? Here's a case that doesn't require enums: `(('{' || 'a' ||'}')::varchar[])[1]::varchar ;` and `SELECT  (('{' || '1' ||'}')::int[])[1]`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXYTHPUBGJyQpb2uAWf:b-ibfqar)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)

___
*[pkg/sql/sem/tree/type_check.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-MXYSK-6A0-gmuRdx2Ze:-MXYSK-86Zz6Yo8QWJTr:b-8rx3jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd276dccf50b1abe4ea51638d2dcd984d9884b83/pkg/sql/sem/tree/type_check.go#L546)):*
> ```
> 	_, ok := subExpr.(*CastExpr)
> 	if ok {
> ```
nit: put the assignement into the `if`.
___
*[pkg/sql/sem/tree/type_check.go, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-MXYSNWO1Vja6gctt8lD:-MXYSNWO1Vja6gctt8lE:bvuz8pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd276dccf50b1abe4ea51638d2dcd984d9884b83/pkg/sql/sem/tree/type_check.go#L547)):*
> ```Go
> 	_, ok := subExpr.(*CastExpr)
> 	if ok {
> 		subExpr = &ParenExpr{
> ```

For this `ParenExpr` should we populate its `typ` field with the value from the `subExpr`? I'm a tad alarmed that we don't have any testing to assert that this is now typed. 


<!-- Sent from Reviewable.io -->

2021-04-05 19:34 UTC, ajwerner reviewed
An alternative approach would be to make a cast an `operatorExpr`. I think the below patch will work but may introduce parens in a bunch of places. It'd be nice to find out. 

```go
--- a/pkg/sql/sem/tree/expr.go
+++ b/pkg/sql/sem/tree/expr.go
@@ -97,6 +97,7 @@ var _ operatorExpr = &UnaryExpr{}
 var _ operatorExpr = &ComparisonExpr{}
 var _ operatorExpr = &RangeCond{}
 var _ operatorExpr = &IsOfTypeExpr{}
+var _ operatorExpr = &CastExpr{}
 
 // Operator is used to identify Operators; used in sql.y.
 type Operator interface {
@@ -1555,6 +1556,8 @@ type CastExpr struct {
        SyntaxMode castSyntaxMode
 }
 
+func (node *CastExpr) operatorExpr() {}
+
 // Format implements the NodeFormatter interface.
 func (node *CastExpr) Format(ctx *FmtCtx) {
        switch node.SyntaxMode {
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXYWZXMCJJy5zmqEQP_:b-bm116r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)



<!-- Sent from Reviewable.io -->

2021-04-05 19:51 UTC, ajwerner commented
I don't know how to reason about the two approaches. It seems like we decided to format the operator exprs so as to not think about precedence here. One interesting thing is that cast is the highest precedence operator, higher even than the subscripting, *but* I think our problem here is not so much the precedence as the parsing ambiguity. I could be wrong. I wonder if @knz has feelings on this.

2021-04-05 20:04 UTC, ajwerner commented
@rafiss or @otan if y'all have any insights, they would be appreciated!

2021-04-05 20:14 UTC, the-ericwang35 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/sem/tree/type_check.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-MXYSK-6A0-gmuRdx2Ze:-MXYelz-8gUcVDHgoeS7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd276dccf50b1abe4ea51638d2dcd984d9884b83/pkg/sql/sem/tree/type_check.go#L546)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	_, ok := subExpr.(*CastExpr)
> 	if ok {
> ```
nit: put the assignement into the `if`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/type_check.go, line 547 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-MXYSNWO1Vja6gctt8lD:-MXYemZR2kChEadXmnIm:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd276dccf50b1abe4ea51638d2dcd984d9884b83/pkg/sql/sem/tree/type_check.go#L547)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For this `ParenExpr` should we populate its `typ` field with the value from the `subExpr`? I'm a tad alarmed that we don't have any testing to assert that this is now typed. 
</blockquote></details>

Good catch, done.


<!-- Sent from Reviewable.io -->

2021-04-05 20:57 UTC, the-ericwang35 commented
> An alternative approach would be to make a cast an `operatorExpr`. I think the below patch will work but may introduce parens in a bunch of places. It'd be nice to find out.

@ajwerner tried out your approach, and it did seem to introduces a lot of additional parens (see the test failures in the CI).

2021-04-05 21:34 UTC, ajwerner reviewed
Hmm, how about this for another take:

```
 // Format implements the NodeFormatter interface.
 func (node *IndirectionExpr) Format(ctx *FmtCtx) {
-       exprFmtWithParen(ctx, node.Expr)
+       if _, isCast := node.Expr.(*CastExpr); isCast {
+               withParens := ParenExpr{Expr: node.Expr}
+               exprFmtWithParen(ctx, &withParens)
+       } else {
+               exprFmtWithParen(ctx, node.Expr)
+       }
        ctx.FormatNode(&node.Indirection)
 }
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXYxFiA7uBF1ftTHl7T:b-5iknpc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-04-05 21:35 UTC, ajwerner reviewed
err
```
 // Format implements the NodeFormatter interface.
 func (node *IndirectionExpr) Format(ctx *FmtCtx) {
-       exprFmtWithParen(ctx, node.Expr)
+       if _, isCast := node.Expr.(*CastExpr); isCast {
+               withParens := ParenExpr{Expr: node.Expr}
+               ctx.FormatNode(&withParens)
+       } else {
+               exprFmtWithParen(ctx, node.Expr)
+       }
        ctx.FormatNode(&node.Indirection)
 }
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXYxTzk6tebn29YuZ5_:b-lvawh6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)



<!-- Sent from Reviewable.io -->

2021-04-05 22:52 UTC, the-ericwang35 commented
> Hmm, how about this for another take:

Yeah this one passes CI (the one test failure looks completely unrelated).

2021-04-05 22:55 UTC, ajwerner commented
Cool. That's my preference. The idea is that we're encoding precedence inside the formatting of the AST. Thanks for picking this up.

2021-04-05 23:02 UTC, the-ericwang35 reviewed
Yep that makes sense to me, I've removed the code for the other approach.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXZGCn2Eoos-B4gHTdn:b-pio64t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @the-ericwang35)



<!-- Sent from Reviewable.io -->

2021-04-06 18:43 UTC, rafiss requested changes
thanks for this fix! i would be fine with this, but just had a question / vague wondering

in terms of concrete things: could you also test this in `TestParse` in parse_test.go?

2021-04-06 18:43 UTC, rafiss commented on pkg/sql/sem/tree/expr.go
> +		exprFmtWithParen(ctx, &withParens)
interesting, my preference would have been to always wrap CastExpr with parens in `exprFmtWithParen` but too bad that seems to break things...

i don't know if i'm ready to advocate for this yet but: what if we _always_ wrap the inner expr of an IndirectionExpr with parens...? just curious how noisy that gets and if there are major downsides

2021-04-06 23:08 UTC, the-ericwang35 reviewed
> in terms of concrete things: could you also test this in TestParse in parse_test.go?

Yep, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-:-MXdRCVyBpk98KDQVpgG:be9qn27)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/tree/expr.go, line 1632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63103#-MXYe__aHMXDqwlKLSs0-r2-1632:-MXdQmba4OSHTKJJkFiL:bf4q35t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8078d90906473ec2a7295c9a707d10c53ed87153/pkg/sql/sem/tree/expr.go#L1632)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

interesting, my preference would have been to always wrap CastExpr with parens in `exprFmtWithParen` but too bad that seems to break things...

i don't know if i'm ready to advocate for this yet but: what if we _always_ wrap the inner expr of an IndirectionExpr with parens...? just curious how noisy that gets and if there are major downsides
</blockquote></details>

I gave this a try, and it results in a lot of extra parentheses, see https://teamcity.cockroachdb.com/viewLog.html?buildId=2854325&buildTypeId=Cockroach_UnitTests.


<!-- Sent from Reviewable.io -->

2021-04-07 01:20 UTC, rafiss approved these changes
thanks for the fix!

2021-04-07 17:16 UTC, the-ericwang35 commented
TFTRs!

bors r=ajwerner,rafiss

2021-04-07 17:54 UTC, merged

2021-04-13 11:00 UTC, knz commented
I think this would benefit from a backport to the stable release branch(es)