uuid: fix parsing for different uuid formats
cockroachdb/cockroach pull request #63137
Opened 2021-04-06 09:41 UTC by techytoes

Fixes: #60011 
More details about Postgres [UUID data type](https://www.postgresql.org/docs/9.6/datatype-uuid.html)

2021-04-06 09:41 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63137)
<!-- Reviewable:end -->

2021-04-06 09:57 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=63137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=63137) before we can accept your contribution.<br/><hr/>**Rupesh Harode** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=63137) it.</sub>

2021-04-06 15:44 UTC, rafiss requested changes
thanks for this PR!

Can you please update your commit message? The most important change is to include Release Notes. see https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

I left a few more comments in the code

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-:-MXbipcm7AJN-ba0fnOZ:b-orbbps)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @techytoes)

___
*[pkg/util/uuid/codec.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbj1XH1AI6VLl7sMB1:-MXbj1XH1AI6VLl7sMB2:b-guhn20) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L77)):*
> ```Go
> //   "{6ba7b8109dad11d180b400c04fd430c8}",
> //   "urn:uuid:6ba7b8109dad11d180b400c04fd430c8",
> //	 "6ba7-b810-9dad-11d1-80b4-00c0-4fd4-30c8"
> ```

nit: please fix the spacing on this line
___
*[pkg/util/uuid/codec.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXblWL3AdKFEsVvAmHf:-MXblWL3AdKFEsVvAmHg:basbjde) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L158)):*
> ```Go
> 	l := len(t)
> 
> 	if t[0] != '{' || t[l-1] != '}' {
> ```

it seems like this check is now performed in two places (here and line 108)

i think it should be removed from one of the places. actually, we may not even need the `decodeBraced` function anymore
___
*[pkg/util/uuid/codec.go, line 173 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbjZykAdtdXC3Hync_:-MXbjZykAdtdXC3Hynca:b-hvhrxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L173)):*
> ```Go
> 	urnUUIDPrefix := t[:9]
> 
> 	if !bytes.Equal(urnUUIDPrefix, urnPrefix) {
> ```

similar to above, this check is done twice now.

we may not even need the `decodeURN` function anymore
___
*[pkg/util/uuid/codec.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbjB6o4uOJDJ-ffOc6:-MXbjB6o4uOJDJ-ffOc7:boetcey) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L177)):*
> ```Go
> 	}
> 
> 	return u.decodePlain(t[9:total])
> ```

I saw that you updated `decodeBraced` so that it called `decodeHyphenated`

can you also update this part of `decodeURN` so it uses `decodeHyphenated`?

(this comment doesn't apply if you remove the `decodeURN` function as mentioned above)
___
*[pkg/util/uuid/codec.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbpoimDigj6IWtDXUZ:-MXbpoimDigj6IWtDXU_:b72dpt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L205)):*
> ```Go
> 
> 	for _, substring := range unhyphenatedStringsArray {
> 		if len(substring)%4 != 0 || len(substring) < 4 {
> ```

the `len(substring) < 4` check can be removed, since the `len(substring) % 4` check already covers it
___
*[pkg/util/uuid/codec.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbpxzC88jBwQ8hEzzY:-MXbpxzC88jBwQ8hEzzZ:b-j4q7n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L209)):*
> ```Go
> 		}
> 	}
> 	hashLike := strings.Join(unhyphenatedStringsArray, "")
> ```

i think there would be a faster way to construct the string instead of using `strings.Join`

maybe try creating `[]byte` slice and directly appending to it

to confirm what performs best, please run some of the benchmarks. you may need to add a new test case to `BenchmarkFromString`
___
*[pkg/util/uuid/codec_test.go, line 134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbqC0R9QrpBqQJESD8:-MXbqC0R9QrpBqQJESD9:bdqd3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec_test.go#L134)):*
> ```Go
> 	{
> 		input:   "{6ba7-b8109dad11d180b400c04fd4-30c8}",
> 		variant: "BracedExtraHyphens",
> ```

can you also add a test for URNs with extra hyphens?
___
*[pkg/util/uuid/codec_test.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbqH4yA4METlupsISD:-MXbqH4yA4METlupsISE:b-90rbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec_test.go#L169)):*
> ```Go
> 	"(6ba7b810-9dad-11d1-80b4-00c04fd430c8}",
> 	"{6ba7b810-9dad-11d1-80b4-00c04fd430c8>",
> 	"zba7b810-9dad-11d1-80b4-00c04fd430c8",
> ```

can you add an invalid test that has hyphens in the wrong places?

```
6ba7b810-9dad11d180b400c04fd430-c8
6-ba7b810-9dad11d180b400c04fd430c8
6ba7b810-9dad11d180b400c04fd430c8-
-6ba7b810-9dad11d180b400c04fd430c8
```

for example


<!-- Sent from Reviewable.io -->

2021-04-06 16:20 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @techytoes)

___
*[pkg/util/uuid/codec.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbysf_5U7ThyRIFHce:-MXbysf_5U7ThyRIFHcf:b-m86gaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L201)):*
> ```Go
> 	unhyphenatedStringsArray := strings.Split(string(t), "-")
> 	if len(unhyphenatedStringsArray) > 8 {
> 		return fmt.Errorf("uuid: incorrrect UUID length: %s", t)
> ```

change spelling from "incorrrect" to "incorrect"

it's the cause of some of the test failures that are happening


<!-- Sent from Reviewable.io -->

2021-04-06 19:35 UTC, techytoes commented
@rafiss I have resolved the comments. please take another look. Looks like there are still some issues as pointed by CI. How can I resolve these issues? 

Thanks 🙇🏻‍♂️🙏🏻

2021-04-07 22:18 UTC, rafiss requested changes
left another round of comments. almost there!

you need to update your commit message to include release notes (not just the PR description)

also, please add more details and make the commit message title match our conventions

example:

```
uuid: fix parsing for different uuid formats

Release note (sql change): CockroachDB now accepts UUID inputs that
have a hyphen after any group of four digits. This aligns with the UUID
format used by Postgres. For example, `a0ee-bc99-9c0b-4ef8-bb6d-6bb9-bd38-0a11`
is now considered a valid UUID.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-:-MXiOvJ00HXn4aZB-vHu:b9keuww)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @techytoes)

___
*[pkg/util/uuid/codec.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbpxzC88jBwQ8hEzzY:-MXiLyjSDXOjtQxeFRcY:byvutky) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L209)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think there would be a faster way to construct the string instead of using `strings.Join`

maybe try creating `[]byte` slice and directly appending to it

to confirm what performs best, please run some of the benchmarks. you may need to add a new test case to `BenchmarkFromString`
</blockquote></details>

can you add a case to the benchmarks, then run the benchmarks and share them?

you can run the benchmarks like this:

```
make bench PKG=./pkg/util/uuid BENCHES=BenchmarkFromString
```

run it on the old and the new code, then run benchstat to compare results: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat

please post the output of benchstat in this PR.
___
*[pkg/util/uuid/codec.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiO46T3t8K2BbW7vfI:-MXiO46T3t8K2BbW7vfJ:bym2rrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L121)):*
> ```Go
> // decodeCanonical decodes UUID strings that are formatted as defined in RFC-4122 (section 3):
> // "6ba7b810-9dad-11d1-80b4-00c04fd430c8".
> func (u *UUID) decodeCanonical(t []byte) error {
> ```

`decodeCanonical` is not used any more. please remove it
___
*[pkg/util/uuid/codec.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiNdde60eH4ssR7QkU:-MXiNdde60eH4ssR7QkV:b-hdunbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L157)):*
> ```Go
> //  "6ba7b810-9dad-11d1-80b4-00c04fd430c8" or in hash-like format
> //  "6ba7b8109dad11d180b400c04fd430c8".
> func (u *UUID) decodePlain(t []byte) error {
> ```

 `decodePlain` is not used anymore. please remove it, and update any tests that rely on it
___
*[pkg/util/uuid/codec.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiN-qL1-nJEgjgsRob:-MXiN-qL1-nJEgjgsRoc:bxqarle) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L164)):*
> ```Go
> 		return u.decodeCanonical(t)
> 	default:
> 		return fmt.Errorf("uuid: incorrect UUID format %s", t)
> ```

ah i see the issue -- the test is failing because of a missing `:`. change  the format string to be

```
uuid: incorrect UUID format: %s
```
___
*[pkg/util/uuid/codec.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiOF2QAUsCAKMBnN2A:-MXiOF2QAUsCAKMBnN2B:bo9fnu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L174)):*
> ```Go
> 	hashLike := []byte("")
> 	l := len(t)
> 	isHexaDecimal := regexp.MustCompile(`^[A-Fa-f0-9]+$`).MatchString
> ```

this regex is not necessary. the code in `decodeHashed` will already return an error if there's an invalid character
___
*[pkg/util/uuid/codec.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiLeX-1Nflnszi8OTv:-MXiLeX-1Nflnszi8OTw:b3l3l3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L178)):*
> ```Go
> 
> 	if len(unhyphenatedStringsArray) > 8 || l > 40 || !isHexaDecimal(string(t[:4])) || !isHexaDecimal(string(t[l-4:])) {
> 		return fmt.Errorf("uuid: incorrect UUID format %s", t)
> ```

```
uuid: incorrect UUID format: %s
```
___
*[pkg/util/uuid/codec.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiLnt08CG0FSk4Ngxb:-MXiLnt08CG0FSk4Ngxc:b3l3l3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L183)):*
> ```Go
> 	for _, substring := range unhyphenatedStringsArray {
> 		if len(substring)%4 != 0 {
> 			return fmt.Errorf("uuid: incorrect UUID format %s", t)
> ```

```
uuid: incorrect UUID format: %s
```


<!-- Sent from Reviewable.io -->

2021-04-08 01:04 UTC, techytoes reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @techytoes)

___
*[pkg/util/uuid/codec.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbpxzC88jBwQ8hEzzY:-MXj-4WW6dLcq6NO1-A4:b6y632z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L209)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add a case to the benchmarks, then run the benchmarks and share them?

you can run the benchmarks like this:

```
make bench PKG=./pkg/util/uuid BENCHES=BenchmarkFromString
```

run it on the old and the new code, then run benchstat to compare results: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat

please post the output of benchstat in this PR.
</blockquote></details>

Sure, will do this.
___
*[pkg/util/uuid/codec.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiO46T3t8K2BbW7vfI:-MXj-Rx64ucvfi1v9yrs:b-n7i8ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L121)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`decodeCanonical` is not used any more. please remove it
</blockquote></details>

yup, sure.
___
*[pkg/util/uuid/codec.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiNdde60eH4ssR7QkU:-MXj-Mq31xTics6jWjQW:bb7oryy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L157)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

 `decodePlain` is not used anymore. please remove it, and update any tests that rely on it
</blockquote></details>

sure
___
*[pkg/util/uuid/codec.go, line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiN-qL1-nJEgjgsRob:-MXiyft04mavHObzBw1P:b5yjakq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see the issue -- the test is failing because of a missing `:`. change  the format string to be

```
uuid: incorrect UUID format: %s
```
</blockquote></details>

ahh yes, I missed this. will update the changes.
___
*[pkg/util/uuid/codec.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiOF2QAUsCAKMBnN2A:-MXiz0EN36yXSp2zk7Sc:bikpi1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L174)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this regex is not necessary. the code in `decodeHashed` will already return an error if there's an invalid character
</blockquote></details>

This was required for cases like `-6ba7b810-9dad11d180b400c04fd430c8` which will also be returned as valid UUID but they aren't. 


<!-- Sent from Reviewable.io -->

2021-04-08 03:26 UTC, techytoes commented
@rafiss Seems like `strings.Join()` is little better than appending to byte array.
lets go ahead with the `strings.Join()` ?
```
name                      old time/op  new time/op  delta
FromString/canonical-12    306ns ± 0%   325ns ± 0%   ~     (p=1.000 n=1+1)
FromString/urn-12          302ns ± 0%   328ns ± 0%   ~     (p=1.000 n=1+1)
FromString/braced-12       305ns ± 0%   321ns ± 0%   ~     (p=1.000 n=1+1)
FromString/hyphenated-12   303ns ± 0%   334ns ± 0%   ~     (p=1.000 n=1+1)
```

2021-04-08 06:19 UTC, rafiss requested changes
thanks for doing those benchmarks. it looks like those are comparing two different versions of your PR. instead, we should compare the benchmark from before the change to your latest change.

i just thought of one more invalid case! i left a comment inline

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-:-MXk1jC10vfYezOTxpgD:bnfol2k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @techytoes)

___
*[pkg/util/uuid/codec.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXbpxzC88jBwQ8hEzzY:-MXk0oym45KGpkW1aWjV:bsv417h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef49309c7da7919262a6b0b14db1ce35b9ab7314/pkg/util/uuid/codec.go#L209)):*
<details><summary><i>Previously, techytoes (Rupesh Harode) wrote…</i></summary><blockquote>

Sure, will do this.
</blockquote></details>

thank you!
___
*[pkg/util/uuid/codec.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXiOF2QAUsCAKMBnN2A:-MXk-8bs9jT-iEWzeUre:b-yuvmbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c25f9b779ca6274f632cc5ec9605282980388d79/pkg/util/uuid/codec.go#L174)):*
<details><summary><i>Previously, techytoes (Rupesh Harode) wrote…</i></summary><blockquote>

This was required for cases like `-6ba7b810-9dad11d180b400c04fd430c8` which will also be returned as valid UUID but they aren't. 
</blockquote></details>

oh, nice catch. i see that you solved it now by looking at `t[0]` and `t[l-1]`

sorry, but i just thought of one more test case that should be added! a string like `6ba7-b810-9dad--11d1-80b4-00c0-4fd4-30c8` (two hyphens in a row) should also be invalid.

perhaps the best way to check for this is something closer to what you had originally. below when you loop through unhyphenatedStringsArray, the check could be

`if len(substring) == 0 || len(substring)%4 != 0 {`

then you won't need to check `t[0]` and `t[l-1]` specially



also, related to the benchmarking, here's one more idea i thought of for how to do this without strings.Split or strings.Join ... i haven't fully tested this yet but i have a feeling that avoiding both of those functions will be faster

```
func (u *UUID) decodeHyphenated(t []byte) error {
	l := len(t)
	if l < 32 || l > 40 {
		return fmt.Errorf("uuid: incorrect UUID format: %s", t)
	}

	hashLike := make([]byte, 32)
	countSinceHyphen := 0
	i := 0
	for _, c := range t {
		if c == '-' {
			if countSinceHyphen == 0 || countSinceHyphen%4 != 0 {
				return fmt.Errorf("uuid: incorrect UUID format: %s", t)
			}
			countSinceHyphen = 0
			continue
		}
		if i >= len(hashLike) {
			return fmt.Errorf("uuid: incorrect UUID format: %s", t)
		}
		hashLike[i] = c
		i++
		countSinceHyphen++
	}
	return u.decodeHashLike(hashLike)
}
```


<!-- Sent from Reviewable.io -->

2021-04-08 12:59 UTC, techytoes commented
@rafiss Here is the benchmark comparison after using the approach that you suggested in the recent review.
```
name                     old time/op  new time/op  delta
FromString/canonical-12   161ns ± 0%   159ns ± 0%   ~     (p=1.000 n=1+1)
FromString/urn-12         173ns ± 0%   160ns ± 0%   ~     (p=1.000 n=1+1)
FromString/braced-12      171ns ± 0%   157ns ± 0%   ~     (p=1.000 n=1+1)
```
Thanks for helping me out here. 🙇🏻‍♂️

2021-04-08 13:38 UTC, rafiss requested changes
of course, it's been good to work with you!

just realized another case -- so hope i'm not being too confusing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-:-MXlfyqY9taCA-yxmHft:bd544bo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @techytoes)

___
*[pkg/util/uuid/codec.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXlgE-J9ab1XR3cPMhZ:-MXlgE-J9ab1XR3cPMh_:b-f0byw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab650f9cdb226e21349ca8f2cd5eb265f92d59c/pkg/util/uuid/codec.go#L156)):*
> ```Go
> 		i++
> 		countSinceHyphen++
> 	}
> ```

we should add one more check here:

```
if i != len(hashLike) {
  return fmt.Errorf("uuid: incorrect UUID format: %s", t)
}
```

that way we don't have to update the error message expected by existing tests
___
*[pkg/util/uuid/codec_test.go, line 243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXlh1152bExln7zZmY_:-MXlh116Eat3AiAUeaIU:b2an4g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab650f9cdb226e21349ca8f2cd5eb265f92d59c/pkg/util/uuid/codec_test.go#L243)):*
> ```Go
> func TestDecodeHyphenatedWithWrongLength(t *testing.T) {
> 	arg := []byte{'4', '2'}
> 	fmt.Println(len(arg))
> ```

this Println should be removed


<!-- Sent from Reviewable.io -->

2021-04-08 15:08 UTC, techytoes reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/util/uuid/codec.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXlgE-J9ab1XR3cPMhZ:-MXls8YL8e5uyoynb2i8:b-clh6dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab650f9cdb226e21349ca8f2cd5eb265f92d59c/pkg/util/uuid/codec.go#L156)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should add one more check here:

```
if i != len(hashLike) {
  return fmt.Errorf("uuid: incorrect UUID format: %s", t)
}
```

that way we don't have to update the error message expected by existing tests
</blockquote></details>

oh yes, missed this. thanks for reminding this. 🙏🏻
___
*[pkg/util/uuid/codec_test.go, line 243 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63137#-MXlh1152bExln7zZmY_:-MXls0tbBj8gOfdjd0RN:b5ebogj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ab650f9cdb226e21349ca8f2cd5eb265f92d59c/pkg/util/uuid/codec_test.go#L243)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this Println should be removed
</blockquote></details>

ah! forgot to delete this from my last debugging session 🙈


<!-- Sent from Reviewable.io -->

2021-04-08 16:57 UTC, rafiss approved these changes
this looks good to go!

the last step is for you to sign the contributor agreement as noted here https://github.com/cockroachdb/cockroach/pull/63137#issuecomment-813993264

2021-04-08 17:03 UTC, techytoes commented
> this looks good to go!
> 
> the last step is for you to sign the contributor agreement as noted here [#63137 (comment)](https://github.com/cockroachdb/cockroach/pull/63137#issuecomment-813993264)

I have already signed this. not sure why it's not reflecting here.

2021-04-09 04:00 UTC, rafiss commented
thanks for your contribution!

bors r+

2021-04-09 04:33 UTC, merged

2021-04-13 10:52 UTC, knz commented
@rafiss is this a candidate for a backport?