rowexec: fix and optimize the inverted filterer
cockroachdb/cockroach pull request #63196
Opened 2021-04-07 02:34 UTC by yuzefovich

Previously, we could end up in a situation when `routingIndex` becomes
invalid if the encoded routing value happens to be before the first
fragmented span. This could later lead to a crash. Also, previously,
we were ignoring the first return parameter of `prepareAddIndexRow`
which indicates whether we should be adding a row for inverted expr
evaluation which is suboptimal (AFAIU). This is now fixed in addition to
only adding the key row to the row container in case we need to evaluate
the inverted expr.

Fixes: #63180.

Release note: None

2021-04-07 02:34 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63196)
<!-- Reviewable:end -->

2021-04-07 14:34 UTC, sumeerbhola requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MXggjK19cbbDPAKFYRz:b-8h4n7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
> ```Go
> 		// No spans contain the value, so we can short-circuit processing it
> 		// altogether.
> 		return false, nil
> ```

I think this is an error case. Unless the spans generated by the optimizer are not matching what the `invertedFilterer` expects, which could be a correctness issue.
And for the `invertedJoiner` case the spans it fetches are the ones the `batchedInvertedExprEvaluator` tells it to.

Can you reproduce the failure?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgiZczDvAQ4-yThPeI:-MXgiZczDvAQ4-yThPeJ:b4lp9pm) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L239)):*
> ```Go
> 		enc = []byte(*row[ifr.invertedColIdx].Datum.(*tree.DBytes))
> 	}
> 	if shouldAdd, err := ifr.invertedEval.prepareAddIndexRow(enc, nil /* encFull */); err != nil {
> ```

not using `shouldAdd` was an unfortunate oversight by me in https://github.com/cockroachdb/cockroach/pull/54283
Looks like that PR has no test for `invertedFilterer` that would show that pre-filtering is doing something. This is in contrast with PR https://github.com/cockroachdb/cockroach/pull/53963 that added a test in `inverted_joiner_test.go` when making a similar change for `invertedJoiner`. It would be good to rectify this testing oversight in this PR.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgj_wh9DAj0FqBR27e:-MXgj_wh9DAj0FqBR27f:b-ycoiq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L243)):*
> ```Go
> 		return ifrStateUnknown, ifr.DrainHelper()
> 	} else if shouldAdd {
> 		// Transform to keyRow.
> ```

Looks like the code comments here and below were not changed when multi-column inverted indexes were added. 
The `keyRow` is everything other than the inverted column (not just the primary key) , which is fine, but the comments should be updated.


<!-- Sent from Reviewable.io -->

2021-04-13 19:54 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you address @sumeerbhola's comments below. I think #63574 is the right approach to fix #63180, but this PR still seems valuable for performance reasons and to avoid panics due to other bugs.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-:-MYBmLz8E9gMa8zklVmR:b-vqqk3d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @yuzefovich)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MYBluaF5J8o4PWRnPSc:b-2hp06f) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this is an error case. Unless the spans generated by the optimizer are not matching what the `invertedFilterer` expects, which could be a correctness issue.
And for the `invertedJoiner` case the spans it fetches are the ones the `batchedInvertedExprEvaluator` tells it to.

Can you reproduce the failure?
</blockquote></details>

I opened up #63574 with a reproduction of the failure and a fix. So I agree with @sumeerbhola that this should result in an assertion failed error (but I think it's good to add this check so that we avoid a panic in case of future bugs).


<!-- Sent from Reviewable.io -->

2021-04-14 19:01 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MYGUuZU7r6ICOWCBlbr:b-e4mxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I opened up #63574 with a reproduction of the failure and a fix. So I agree with @sumeerbhola that this should result in an assertion failed error (but I think it's good to add this check so that we avoid a panic in case of future bugs).
</blockquote></details>

Added an assertion error.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgiZczDvAQ4-yThPeI:-MYGj4c05BJ9L1fLa6zy:b-v37moh) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L239)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

not using `shouldAdd` was an unfortunate oversight by me in https://github.com/cockroachdb/cockroach/pull/54283
Looks like that PR has no test for `invertedFilterer` that would show that pre-filtering is doing something. This is in contrast with PR https://github.com/cockroachdb/cockroach/pull/53963 that added a test in `inverted_joiner_test.go` when making a similar change for `invertedJoiner`. It would be good to rectify this testing oversight in this PR.
</blockquote></details>

I've stared at the tests and the code for like half an hour and still don't understand how to write a test case for this (in case of the inverted joiner we have access to "disassembled" things like `datumsToInvertedExpr`, but for the inverted filterer we only have the processor spec). Another thing is that, IIUC, this PR only fixes an optimization (but has no influence on the correctness), so the unit test would need to look into some of the internals of the inverted filterer (i.e. something like whether pre-filtered row is added to the container or not) which will require introducing some knobs into the processor.

Am I missing something? Could you provide more details on how to test this?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgj_wh9DAj0FqBR27e:-MYGbK773ZHINPiMo8Jn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L243)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Looks like the code comments here and below were not changed when multi-column inverted indexes were added. 
The `keyRow` is everything other than the inverted column (not just the primary key) , which is fine, but the comments should be updated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-14 19:17 UTC, rytaft approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-04-14 19:39 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-:-MYGtP0s2MqMrt8rwhKH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[pkg/sql/rowexec/inverted_filterer.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgj_wh9DAj0FqBR27e:-MYGsOBb30G_CL8rJWoe:bcfv33v) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L243)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[nit] there's a similar comment that could use updating at line 88.


<!-- Sent from Reviewable.io -->

2021-04-15 13:54 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-:-MYKnkcJ0_ElLNTZeBgN:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MYKinQQ0-n3Jo4NGf0i:b61qj9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Added an assertion error.
</blockquote></details>

How about also adding an assertion that `bytes.Compare(b.fragmentedSpans[i].End, routingEnc) > 0`. I think we can afford to do an additional comparison for the sake of correctness.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgiZczDvAQ4-yThPeI:-MYKlzF3C_BzbiWkfZY0:b-3ob8pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L239)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I've stared at the tests and the code for like half an hour and still don't understand how to write a test case for this (in case of the inverted joiner we have access to "disassembled" things like `datumsToInvertedExpr`, but for the inverted filterer we only have the processor spec). Another thing is that, IIUC, this PR only fixes an optimization (but has no influence on the correctness), so the unit test would need to look into some of the internals of the inverted filterer (i.e. something like whether pre-filtered row is added to the container or not) which will require introducing some knobs into the processor.

Am I missing something? Could you provide more details on how to test this?
</blockquote></details>

I agree that this is messy to test. I was imagining constructing an `invertedFilterer` in the normal way without a prefilter, and then injecting `batchedInvertedExprEvaluator.{filterer,preFilterState}` -- the former is an interface and the latter is `[]interface{}`. We'd need a hook in `ProcessorTest` to give us access to `invertedFilterer` after it is constructed, and before it is used, so we can fiddle with it.

I'm fine with a TODO in `inverted_filterer_test.go`.


<!-- Sent from Reviewable.io -->

2021-04-15 20:37 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MYMEWfx7mrrgjXB5e7X:bvipvot) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How about also adding an assertion that `bytes.Compare(b.fragmentedSpans[i].End, routingEnc) > 0`. I think we can afford to do an additional comparison for the sake of correctness.
</blockquote></details>

Done. The `End` is non-inclusive so that we return an error in case `== 0`, right?
___
*[pkg/sql/rowexec/inverted_filterer.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgiZczDvAQ4-yThPeI:-MYMEkR42hJ8EI-fZ4N4:b-hehui0) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L239)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I agree that this is messy to test. I was imagining constructing an `invertedFilterer` in the normal way without a prefilter, and then injecting `batchedInvertedExprEvaluator.{filterer,preFilterState}` -- the former is an interface and the latter is `[]interface{}`. We'd need a hook in `ProcessorTest` to give us access to `invertedFilterer` after it is constructed, and before it is used, so we can fiddle with it.

I'm fine with a TODO in `inverted_filterer_test.go`.
</blockquote></details>

Sounds good, left a TODO.
___
*[pkg/sql/rowexec/inverted_filterer.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXgj_wh9DAj0FqBR27e:-MYMEwr1-Isn8IxPfF_O:b-xiw2bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_filterer.go#L243)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] there's a similar comment that could use updating at line 88.
</blockquote></details>

Nice catch, done.


<!-- Sent from Reviewable.io -->

2021-04-15 23:19 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-:-MYMpL5wA051WIGoBpOX:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/sql/rowexec/inverted_expr_evaluator.go, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63196#-MXggjK19cbbDPAKFYRy:-MYMpCji26tJBDGGDoTT:b-jp377f) ([raw file](https://github.com/cockroachdb/cockroach/blob/571ee64f8407aa68c691e60fda1eec44824ec4e3/pkg/sql/rowexec/inverted_expr_evaluator.go#L527)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done. The `End` is non-inclusive so that we return an error in case `== 0`, right?
</blockquote></details>

correct


<!-- Sent from Reviewable.io -->

2021-04-15 23:21 UTC, yuzefovich commented
TFTRs!

bors r+

2021-04-16 00:15 UTC, merged