roachtest: update libpq blocklist to ignore TestCopyInBinaryError
cockroachdb/cockroach pull request #63238
Opened 2021-04-07 17:42 UTC by RichardJCai

roachtest: update libpq blocklist to ignore TestCopyInBinaryError

Release note: None

2021-04-07 17:42 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63238)
<!-- Reviewable:end -->

2021-04-07 17:42 UTC, RichardJCai commented
Gonna need to backport this all the way to 20.1 I think.

2021-04-07 18:04 UTC, rafiss requested changes
i think we need a different approach -- the ignore list still runs the test but ignores the result. so we need a way to skip entirely

2021-04-08 00:31 UTC, RichardJCai reviewed
Updated to ignore by generating an "allow list".

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-:-MXisqpUCM2ZHVONDDIv:b-jf5n3s)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-04-08 00:31 UTC, RichardJCai commented
Note that now the ignored tests are not run at all instead of having their results ignored.

2021-04-09 17:07 UTC, rafiss requested changes
awesome -- just some minor cleanups

2021-04-09 17:07 UTC, rafiss commented on pkg/cmd/roachtest/libpq.go
> +		for _, testName := range tests[:len(tests)-1] {
just to be sure we don't miss anything, maybe we could loop over the whole slice, but then add a check like `if testName does not start with "Test"`

2021-04-09 17:07 UTC, rafiss commented on pkg/cmd/roachtest/libpq_blocklist.go
>  var libPQIgnorelist19_2 = blocklist{
the test names in the ignore list here start with pq. also, we maybe can just get rid of the the 19.2 stuff and change the min version of the test to 20.1

2021-04-09 17:07 UTC, rafiss commented on pkg/cmd/roachtest/libpq.go
> +		testListRegex := `"(Test|Example)"`
technically if it's about what the string starts with, should it be `^(Test|Example)` ?

2021-04-12 18:58 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/libpq.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXisqGGU0Fwv_Pi7LqC-r1-94:-MY6Rk1J1Ys2tcPABkNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq.go#L94)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

technically if it's about what the string starts with, should it be `^(Test|Example)` ?
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/libpq.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXisqGGU0Fwv_Pi7LqC-r1-111:-MY6RkQ31IiD5AHpFVPP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq.go#L111)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just to be sure we don't miss anything, maybe we could loop over the whole slice, but then add a check like `if testName does not start with "Test"`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/libpq_blocklist.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-MXhQKNzf9qHXdlNp_Wz-r1-188:-MY6RXHvDycbVVgWaxt8:bbnkggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1eb4ee2ece8b14d5714f092ca83b7c0e3f92601d/pkg/cmd/roachtest/libpq_blocklist.go#L188)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the test names in the ignore list here start with pq. also, we maybe can just get rid of the the 19.2 stuff and change the min version of the test to 20.1
</blockquote></details>

Removed 19.2. The reason I had to remove the pq. here is that the name returned from the `go test -list` does not include pq. and we use that to determine whether we ignore the test or not. 


<!-- Sent from Reviewable.io -->

2021-04-20 15:11 UTC, rafiss approved these changes
lgtm!!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63238#-:-MYjp_yq7lMkBd_GgCVN:b-nzoorr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2021-04-20 15:45 UTC, RichardJCai commented
Thanks! 
bors r=rafiss

2021-04-20 22:49 UTC, merged