[DNM] bazel: wip
cockroachdb/cockroach pull request #63253
Opened 2021-04-07 20:26 UTC by rickystewart

bazci

Release note: None

2021-04-07 20:26 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63253)
<!-- Reviewable:end -->

2021-04-08 15:35 UTC, rickystewart commented
little issue remaining with this, give me a bit...

2021-04-08 18:48 UTC, rickystewart commented
I think that this is actually fully done now lol

2021-04-12 19:20 UTC, rail requested changes
> 1. Test results only appear in TeamCity after all of the tests finish.
>    Obviously, we'd like them to stream such that successes and failures
>    show up in the UI immediately.

This is awesome!

> Reviewed 8 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-:-MXnwVLWEMr4RPwnliRu:bota9d5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[build/bazelbuilder/Dockerfile, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnvG_k76e7PBpOzUEP:-MXnvG_k76e7PBpOzUEQ:bgb3drz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/Dockerfile#L65)):*
> ```Dockerfile
> COPY entrypoint.sh /usr/bin
> ENTRYPOINT ["/usr/bin/entrypoint.sh"]
> CMD ["/usr/bin/bash"]
> ```

A nit. Usually it's `/bin/bash` on Linux.
___
*[build/bazelbuilder/entrypoint.sh, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnvya8DmhgzIEu6Fsr:-MXnvya8DmhgzIEu6Fss:bk9k2rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/entrypoint.sh#L1)):*
> ```Shell
> #!/usr/bin/bash
> ```

A nit. Usually it's `/bin/bash` on Linux. Or even better `#!/usr/bin/env bash`.
___
*[build/bazelbuilder/entrypoint.sh, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnw4IeAzipwInInjEB:-MXnw4IeAzipwInInjEC:b-ld5iau) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/entrypoint.sh#L2)):*
> ```Shell
> #!/usr/bin/bash
> umask 0000
> ```

Can you add comments why we need this?
___
*[pkg/cmd/bazci/bazci.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXo9amd7eNhbekcRapV:-MXo9amd7eNhbekcRapW:bs29w8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/bazci.go#L126)):*
> ```
> func getBuildInfo(args parsedArgs) (*buildInfo, error) {
> ```

Do you really need to return a reference here? I wouldn't worry about copying - it's not a huge structure.
___
*[pkg/cmd/bazci/bazci.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXo4goC-gsYvKavWxwY:-MXo4goC-gsYvKavWxwZ:b-ijbrwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/bazci.go#L147)):*
> ```
> outputSplit := strings.Split(output, " ")
> ```

A nit. I usually use https://golang.org/pkg/strings/#Fields in these cases in case the in input has multiple spaces.
___
*[pkg/cmd/bazci/bazci.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXo7Maz3eALAs-l4abN:-MXo7Maz3eALAs-l4abO:b-s369c5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/bazci.go#L165)):*
> ```
> 			ret.tests = append(ret.tests, strings.Split(allTests, "\n")...)
> ```

This may not work on Windows (I know, we don't support it, but). If the targets don't contain spaces, we can use https://golang.org/pkg/strings/#Fields, otherwise you can replace "\r\n" with "\n" and then split.
___
*[pkg/cmd/bazci/bazci.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6SduB6IbHbZlu-TFa:-MY6SduB6IbHbZlu-TFb:bib4st2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/bazci.go#L187)):*
> ```
> 	completion := make(chan error, 1)
> ```
Can you add comments why we need a buffered channel here. Or maybe try an unbuffered version (no need to pass 1).
___
*[pkg/cmd/bazci/watch.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXoJSmZ-4yPF3nQacVg:-MXoJSmZ-4yPF3nQacVh:b-r4ny6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L65)):*
> ```
> func (w *watcher) Watch() error {
> ```

Do you need to have a mutable receiver here?
___
*[pkg/cmd/bazci/watch.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXoIvoF4aZT-VRZiGso:-MXoIvoF4aZT-VRZiGsp:b-pd6weg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L73)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 			testErr := w.stageTestArtifacts()
> 			// Also stage binary artifacts this time.
> 			binErr := w.stageBinaryArtifacts()
> 			if buildErr != nil {
> 				return buildErr
> 			}
> ```
</details>

Can you add comments, why we postpone the error checking part here.
___
*[pkg/cmd/bazci/watch.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6Uhbr92SjmBNqx9jC:-MY6Uhbr92SjmBNqx9jD:b-yyk9ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L201)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> func copyContentTo(srcContent []byte, outFile *os.File) error {
> 	_, err := outFile.Write(srcContent)
> 	return err
> }
> ```
</details>


I'd use https://golang.org/pkg/io/#Writer instead - it's a very common pattern to pass writers around instead of file contents.
___
*[pkg/cmd/bazci/watch.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6VFskAh3ZPKrv1iE-:-MY6VFskAh3ZPKrv1iE0:bopemrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L244)):*
> ```
> err := os.MkdirAll(path.Dir(destPath), 0777)
> ```
Can you use less permissive version 0755 for directories and 0644 for files please. I don't think we need them world writeble.
___
*[pkg/cmd/bazci/watch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6VhNf4cM5xpAcSOcW:-MY6VhNf4cM5xpAcSOcX:b-es53jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L257)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			contents, err := ioutil.ReadFile(srcPath)
> 			if err != nil {
> 				return err
> 			}
> 			err = stagefn(contents, f)
> ```
</details>


I'd use https://golang.org/pkg/io/#Copy instead of passing the contents around. Unless I missed something here.


<!-- Sent from Reviewable.io -->

2021-04-13 19:19 UTC, rickystewart reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63253)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[build/bazelbuilder/Dockerfile, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnvG_k76e7PBpOzUEP:-MYBZ8NF-OysX5WdI0gH:bf7s2uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/Dockerfile#L65)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

A nit. Usually it's `/bin/bash` on Linux.
</blockquote></details>

Mm, I don't know what the "usually" means here. This is a Dockerfile and the `bash` in this image is `/usr/bin/bash`:

    root@2479962ba9a0:/# which bash 
    /usr/bin/bash
___
*[build/bazelbuilder/entrypoint.sh, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnvya8DmhgzIEu6Fsr:-MYBZGQW1X2pRfjMQX1K:b-mq9m4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/entrypoint.sh#L1)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

A nit. Usually it's `/bin/bash` on Linux. Or even better `#!/usr/bin/env bash`.
</blockquote></details>

As mentioned above -- this script isn't run on any arbitrary system, it's our own bespoke Docker image.
___
*[build/bazelbuilder/entrypoint.sh, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXnw4IeAzipwInInjEB:-MYBZx8RCUfO0l_RP7LA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/build/bazelbuilder/entrypoint.sh#L2)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you add comments why we need this?
</blockquote></details>

Done.
___
*[pkg/cmd/bazci/watch.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MXoIvoF4aZT-VRZiGso:-MYBbMko7DZECTNxd9SR:b-43o9nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L73)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> 			testErr := w.stageTestArtifacts()
> 			// Also stage binary artifacts this time.
> 			binErr := w.stageBinaryArtifacts()
> 			if buildErr != nil {
> 				return buildErr
> 			}
> ```
Can you add comments, why we postpone the error checking part here.
</blockquote></details>

The existing comment is already meant to do that, but I reworded it slightly to make it a little clearer.
___
*[pkg/cmd/bazci/watch.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6Uhbr92SjmBNqx9jC:-MYBcot81jQlDDHv8ZWk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L201)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> func copyContentTo(srcContent []byte, outFile *os.File) error {
> 	_, err := outFile.Write(srcContent)
> 	return err
> }
> ```

I'd use https://golang.org/pkg/io/#Writer instead - it's a very common pattern to pass writers around instead of file contents.
</blockquote></details>

Done.
___
*[pkg/cmd/bazci/watch.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6VFskAh3ZPKrv1iE-:-MYBcp_mEw9hNfJJtG0Q:buhbb9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L244)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> err := os.MkdirAll(path.Dir(destPath), 0777)
> ```
Can you use less permissive version 0755 for directories and 0644 for files please. I don't think we need them world writeble.
</blockquote></details>

No, we do need them. TC will be unable to clean these files up unless they're world-writeable.
___
*[pkg/cmd/bazci/watch.go, line 257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-MY6VhNf4cM5xpAcSOcW:-MYBd2ne9CeTuARO1F3B:b2u3ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/2643e08f1ad9d5d6ffe8b630560e11366bdae773/pkg/cmd/bazci/watch.go#L257)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

> ```
> 			contents, err := ioutil.ReadFile(srcPath)
> 			if err != nil {
> 				return err
> 			}
> 			err = stagefn(contents, f)
> ```

I'd use https://golang.org/pkg/io/#Copy instead of passing the contents around. Unless I missed something here.
</blockquote></details>

That works for the cases where we directly copy the file contents, but we don't always just directly copy the file contents (the XML case).


<!-- Sent from Reviewable.io -->

2021-04-13 23:13 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 16 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63253#-:-MYCTpweEJkccT0Lwynm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)



<!-- Sent from Reviewable.io -->

2021-04-14 15:34 UTC, rickystewart commented
bors r=rail

2021-04-14 16:53 UTC, merged