changefeedccl: Use memory monitor for kafka and cloud sinks.
cockroachdb/cockroach pull request #63406
Opened 2021-04-09 20:47 UTC by miretskiy

Kafka, as well as cloud sinks, use inernal buffering when emitting
events.  Use memory monitor to account for memory used in internal buffers.
If the downstream sink is unavailable for extended periods of time,
memory monitor will ensure that the amount of buffered data does not
grow to cause OOM issues.

Informs #63186
Informs #60697

Release Notes: Kafka and cloud storage sinks use memory monitor
to limit the amount of memory that can be used in internal buffers.

2021-04-09 20:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63406)
<!-- Reviewable:end -->

2021-04-12 22:46 UTC, ajwerner requested changes
nit `inernal` in the commit message

`cdc/bank` roachtest timed out in CI. You should try running it to see what's going on. 

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-:-MY7CTTK54rQ8xIFMAS4:b-v85jd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 205 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7CYVV4Yj1B8UuTKMZ:-MY7CYVV4Yj1B8UuTKM_:b-ytd4y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4558f42b195d516e8f01cd63f80cb0a98e2cf2/pkg/ccl/changefeedccl/changefeed_processors.go#L205)):*
> ```Go
> 
> 	if cfKnobs, ok := ca.flowCtx.TestingKnobs().Changefeed.(*TestingKnobs); ok {
> 		ca.knobs = *cfKnobs
> ```

why copy them out? It is not a pattern used elsewhere. 
___
*[pkg/ccl/changefeedccl/sink.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7CrLHDXSaWBg3H4Aq:-MY7CrLHDXSaWBg3H4Ar:bmfa9gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4558f42b195d516e8f01cd63f80cb0a98e2cf2/pkg/ccl/changefeedccl/sink.go#L91)):*
> ```Go
> 	makeExternalStorageFromURI cloud.ExternalStorageFromURIFactory,
> 	user security.SQLUsername,
> 	acc mon.BoundAccount,
> ```

This needs to be a pointer, right? In fact, I'll go so far as to suggest that we should have a `_ util.NoCopy` inside `mon.BoundAccount`. 
___
*[pkg/ccl/changefeedccl/sink_test.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7FKpL30DPhPMO8hI0:-MY7FKpL30DPhPMO8hI1:bj1gftx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4558f42b195d516e8f01cd63f80cb0a98e2cf2/pkg/ccl/changefeedccl/sink_test.go#L103)):*
> ```Go
> // Returns a function that must be called to stop this consumer
> // to clean up.  The cleanup function must be called before closing asyncProducerMock.
> func (p *asyncProducerMock) consume() func() {
> ```

nit: extra space before `The`

please name this return function `cleanup`. 
___
*[pkg/ccl/changefeedccl/sink_test.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7FZjj58qxWFq6BCGL:-MY7FZjj58qxWFq6BCGM:ba8x3ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4558f42b195d516e8f01cd63f80cb0a98e2cf2/pkg/ccl/changefeedccl/sink_test.go#L158)):*
> ```Go
> const defaultTopicName = ""
> 
> func getBoundAccountWithBudget(budget int64) (mon.BoundAccount, func()) {
> ```

name the return func
___
*[pkg/ccl/changefeedccl/sink_test.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7Fagn1BbYi0Zw5wwJ:-MY7Fagn1BbYi0Zw5wwK:ba8x3ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa4558f42b195d516e8f01cd63f80cb0a98e2cf2/pkg/ccl/changefeedccl/sink_test.go#L174)):*
> ```Go
> 	budget int64,
> 	targetNames ...string,
> ) (*kafkaSink, func()) {
> ```

name the return func


<!-- Sent from Reviewable.io -->

2021-04-12 23:19 UTC, ajwerner reviewed
Let's see how CI goes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-:-MY7NNphDEvzqJGqCtyQ:bykmm39)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 220 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7NKkGDxxTiB4_QWqd:-MY7NKkGDxxTiB4_QWqe:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1477d9eb5bd52cc845d43b68ea31f3e09cb5946/pkg/ccl/changefeedccl/changefeed_processors.go#L220)):*
> ```Go
> 
> 	var err error
> 	// TODO(yevgeniy): getSink is getting to be quite a kitchen sink -- refactor.
> ```

+1
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 934 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7NF9OBuGN4eSP_Bru:-MY7NF9OBuGN4eSP_Brv:b-rtm2nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1477d9eb5bd52cc845d43b68ea31f3e09cb5946/pkg/ccl/changefeedccl/changefeed_processors.go#L934)):*
> ```Go
> 	var nilOracle timestampLowerBoundOracle
> 	var err error
> 	// TODO(yevgeniy): Evaluate if we shoudl add memory monitoring for change frontier.
> ```

nit `shoudl`

I don't see any reason not to. 
___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-MY7NBIeBUnuntAtwh-j:-MY7NBIf2O3GRXdX5I-7:bfvgpdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1477d9eb5bd52cc845d43b68ea31f3e09cb5946/pkg/ccl/changefeedccl/changefeed_stmt.go#L325)):*
> ```Go
> 				ctx, details.SinkURI, p.ExecCfg().NodeID.SQLInstanceID(), details.Opts, details.Targets,
> 				settings, nilOracle, p.ExecCfg().DistSQLSrv.ExternalStorageFromURI,
> 				p.User(), &acc,
> ```

should you just pass `nil` here given nothing uses it?


<!-- Sent from Reviewable.io -->

2021-04-13 22:03 UTC, miretskiy commented
@ajwerner Ready for final review.

2021-04-13 22:42 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63406#-:-MYCOcPi2kutChQ-Uqqm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)



<!-- Sent from Reviewable.io -->

2021-04-13 22:55 UTC, miretskiy commented
tftr
bors r=ajwerner

2021-04-13 23:45 UTC, merged