added new files to the monitoring-dashbords for review
cockroachdb/cockroach pull request #63488
Opened 2021-04-12 20:02 UTC by sai-roach

Added new dashboards on PromQL and grafana for monitoring.

2021-04-12 20:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63488)
<!-- Reviewable:end -->

2021-04-12 23:03 UTC, dhartunian requested changes
Huge thanks for putting these up! These dashboards really need an update. I'll spend some time with these in detail over the next few days but a few comments at a high level:

- Since the dashboards are large JSON file that are difficult to parse through, it would help to have detail in the commit message about what's being added and why. A list of all the dashboards with a quick summary would be helpful here.
- It seems like these are matching up with the dashboard on the DB Console. Is that the intention here? If so, we should state explicitly in the commit message that they're meant to be in sync. If there are differences between the two it would be good to point them out for future dashboard editors.
- You mentioned on Slack that you exported from Chronosphere. That's another thing to mention in the commit message. Were these generated by hand and then exported? Or was there a different process? Would be good to know for the next person that wants to "update the dashboards".

Might help to add a `README.md` in the `grafana-dashboards` directory with this info on how these were generated since it might be a lot for a commit message. Your call. Happy with either at this point.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-MY7FXOh4Oa_b24JQvnf:bh6fo1d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sai-roach)

___
*[monitoring/grafana-dashboards/Changefeeds.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7GhmP3Nu4-w7EMCCr:-MY7GhmQ5xp0IW6mIRdt:bfooxnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Changefeeds.json#L1)):*
> ```JSON
> {
> ```

nit: can we maintain a consistent lower case name on all the dashboard files?
___
*[monitoring/grafana-dashboards/Replication.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7IvAQ9OX6nIOU-wpT:-MY7IvAQ9OX6nIOU-wpU:b-70clyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Replication.json#L1)):*
> ```JSON
> {
> ```

We have a `replicas.json` already. Should this one replace the old dashboards? I'd like to avoid confusion for customers.
___
*[monitoring/grafana-dashboards/sql2.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7J1CT0b_hHUZhNJzh:-MY7J1CT0b_hHUZhNJzi:b7vla6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/sql2.json#L1)):*
> ```JSON
> {
> ```

Similar comment as with `Replication.json`. Should this just replace `sql.json`? We can always point old docs pages to old dashboard commits if the new ones are incompatible. Or we can divide into directories by DB version.


<!-- Sent from Reviewable.io -->

2021-04-13 22:25 UTC, sai-roach commented
Yeah @dhartunian we can add the Read.md file later next week.

2021-05-03 20:52 UTC, abarganier reviewed
Hey Sai, apologies for taking so long to get to this! I am still working on testing these in my local Grafana instance. In the meantime I have a couple initial questions/points for discussion. 

Locally, I'm having some trouble with the `${DS_PROMETHEUS}` variable not being found when importing these dashboards, so I hope to provide some more feedback once I get that resolved on my end.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-MZnzK5l5gxBIXZigroN:b-rkbqoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @sai-roach)

___
*[monitoring/grafana-dashboards/storage.json, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZny7it1QOVedS6BTlh:-MZny7iu5AqCk-eiJ3mV:b1quuqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L808)):*
> ```
> "${DS_Prometheus}",
> ```
Is it intentional to change this to lower-cased `DS_Prometheus` instead of `DS_PROMETHEUS`? It looks like all the other dashboards use the capitalized version of this variable. I think we should aim to keep its use consistent.
___
*[monitoring/grafana-dashboards/storage.json, line 1103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnylxy0iPBzwjFQ2CP:-MZnylxy0iPBzwjFQ2CQ:b1hc8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L1103)):*
> ```
> "datasource": null,
> ```
What are the implications of nullifying a `datasource` like this?
___
*[monitoring/grafana-dashboards/storage.json, line 1336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnz8O4B26Uoq-v33cB:-MZnz8O4B26Uoq-v33cC:b-jrrjr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L1336)):*
> ```
>   "title": "CBDB Console: Storage",
>   "uid": "cbdb-console-storage",
> ```
nit: CRDB
___
*[monitoring/grafana-dashboards/Replication.json, line 1029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnzE6ZD1a2UCW3HMfH:-MZnzE6ZD1a2UCW3HMfI:b-x8xlw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Replication.json#L1029)):*
> ```
>     "title": "CBDB Console:  Replications",
>     "uid": "cbdb-console-replications",
> ```
nit: CRDB


<!-- Sent from Reviewable.io -->

2021-05-05 20:16 UTC, sai-roach commented
@abarganier Sorry for the delay. I can change the name back to 'prometheus' on the files, {DS_PROMETHEUS} is a parameter data source used in dockers and containers. 

Here is more info on this issue

https://github.com/grafana/grafana/issues/10786
https://github.com/litmuschaos/litmus/pull/2548
https://github.com/SUSE/sap_host_exporter/pull/53

2021-05-12 14:40 UTC, abarganier reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @sai-roach)

___
*[monitoring/grafana-dashboards/runtime.json, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-M_W08Ve49gxhyVhRobN:-M_W08Ve49gxhyVhRobO:b-2tta7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac8be55ee65acde026eb4181045ecc293b23787/monitoring/grafana-dashboards/runtime.json#L5)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     {
>       "name": "DS_PROMETHEUS",
>       "label": "Prometheus",
>       "description": "",
>       "type": "datasource",
>       "pluginId": "prometheus",
>       "pluginName": "Prometheus"
>     }
> ```
</details>

Ah! The removal of this input config might be what's causing these "unable to find datasource" issues (just a guess). I'm going to give this another try this week, so I'll see if adding these back in resolves the issue. 


<!-- Sent from Reviewable.io -->

2021-05-21 15:46 UTC, abarganier commented
> Ah! The removal of this input config might be what's causing these "unable to find datasource" issues (just a guess). I'm going to give this another try this week, so I'll see if adding these back in resolves the issue.

Sorry for the delay, Sai. I gave this a try and my "missing datasource" issues went away! So, I think we'll need to go through each file and just make sure that `__inputs` is defined:

```
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
```

2021-06-07 19:25 UTC, kzh commented
(work log) I'm working on ensuring feature parity between the incoming dashboards and the metrics page in db console before merging this PR. This includes doing a QA check on:
- consistent label names
- updated exported prom metrics names
  `container_memory_usage_bytes`
  `sys_host_memory_bytes`
- correct ordering

2021-06-15 18:39 UTC, dhartunian reviewed
@kzh can you update the commit message + PR description to be more verbose and perhaps summarize all the new dashboards being added along with a link to where folks can go to try them out (the README for the docker compose flow)

Also, it would be helpful if you could go through the open comment threads on the PR and respond with where changes were made/not made/ or if the issue is irrelevant now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McFxvwi6XFgaDZOklTf:b-jzxyge)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sai-roach)



<!-- Sent from Reviewable.io -->

2021-06-15 19:49 UTC, kzh reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[monitoring/grafana-dashboards/runtime.json, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-M_W08Ve49gxhyVhRobN:-McGCRPEEYJSKyFVXBkx:b-7c7av8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ac8be55ee65acde026eb4181045ecc293b23787/monitoring/grafana-dashboards/runtime.json#L5)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
>     {
>       "name": "DS_PROMETHEUS",
>       "label": "Prometheus",
>       "description": "",
>       "type": "datasource",
>       "pluginId": "prometheus",
>       "pluginName": "Prometheus"
>     }
> ```
Ah! The removal of this input config might be what's causing these "unable to find datasource" issues (just a guess). I'm going to give this another try this week, so I'll see if adding these back in resolves the issue. 
</blockquote></details>

I was able to use this workaround: https://github.com/grafana/grafana/issues/10786#issuecomment-734447429.
___
*[monitoring/grafana-dashboards/storage.json, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZny7it1QOVedS6BTlh:-McG9kcq3COG3mPz8Elu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L808)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "${DS_Prometheus}",
> ```
Is it intentional to change this to lower-cased `DS_Prometheus` instead of `DS_PROMETHEUS`? It looks like all the other dashboards use the capitalized version of this variable. I think we should aim to keep its use consistent.
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/storage.json, line 1103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnylxy0iPBzwjFQ2CP:-McGD-rs49sZS7A59WcB:b-hw0np5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L1103)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "datasource": null,
> ```
What are the implications of nullifying a `datasource` like this?
</blockquote></details>

When the datasource is null, the configured default is used.
___
*[monitoring/grafana-dashboards/storage.json, line 1336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnz8O4B26Uoq-v33cB:-McG0cbf-LSmjDxI_Q8E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/storage.json#L1336)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
>   "title": "CBDB Console: Storage",
>   "uid": "cbdb-console-storage",
> ```
nit: CRDB
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/sql2.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7J1CT0b_hHUZhNJzh:-McG9YRR6NruxQ4NCnVz:b-nms3mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/sql2.json#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Similar comment as with `Replication.json`. Should this just replace `sql.json`? We can always point old docs pages to old dashboard commits if the new ones are incompatible. Or we can divide into directories by DB version.
</blockquote></details>

The previous `sql.json` was removed.
___
*[monitoring/grafana-dashboards/Changefeeds.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7GhmP3Nu4-w7EMCCr:-McG9Ner2LfPTUOIm0q1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Changefeeds.json#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: can we maintain a consistent lower case name on all the dashboard files?
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/Replication.json, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MY7IvAQ9OX6nIOU-wpT:-McGA8gI-D8t5MMKUAv9:b-u38zqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Replication.json#L1)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

We have a `replicas.json` already. Should this one replace the old dashboards? I'd like to avoid confusion for customers.
</blockquote></details>

The old dashboards (incl.`replicas.json`) have been removed.
___
*[monitoring/grafana-dashboards/Replication.json, line 1029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-MZnzE6ZD1a2UCW3HMfH:-McGAF0S7DjGbkGN_UH7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc53b854935545761d004a5a9a3bcabe6422cd3c/monitoring/grafana-dashboards/Replication.json#L1029)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
>     "title": "CBDB Console:  Replications",
>     "uid": "cbdb-console-replications",
> ```
nit: CRDB
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-15 20:18 UTC, kzh reviewed
How does this look?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McGJO_m4FyIYsfWZIec:blk02gg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)



<!-- Sent from Reviewable.io -->

2021-06-15 21:13 UTC, abarganier reviewed
Thanks, I appreciate you filling this out with some more info - looks good. @dhartunian should we do some quick QA of the dashboards on our own before merging, just to get another pair of eyes on it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McGVya9C6JNV-rxxXW8:b-5c9mmb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)



<!-- Sent from Reviewable.io -->

2021-06-17 16:00 UTC, dhartunian reviewed
Nice work cleaning this up @kzh, I just have a few small nits.

@kzh is it possible to make all the dashboards have the plots at full width?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McPaWpEE_55A8WxOmbP:b-tgo6xk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @sai-roach)

___
*[monitoring/grafana-dashboards/hardware.json, line 459 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPbcs30TE-jGEfH9q8:-McPbcs30TE-jGEfH9q9:bve0j7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L459)):*
> ```JSON
>       "targets": [
>         {
>           "expr": "rate(sys_host_disk_read_count{job=\"cockroachdb\",cluster=~\"$cluster\",instacne=~\"$node\"}[$__rate_interval])",
> ```

`instacne` -> `instance`
___
*[monitoring/grafana-dashboards/hardware.json, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPdYzU8XaOf3FpcxXX:-McPdYzVB1hBl1m7Krud:b-p559wq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L700)):*
> ```JSON
>         "alignLevel": null
>       }
>     },
> ```

Can you add the "Available Disk Capacity" graph here? `cr.store.capacity.available`
___
*[monitoring/grafana-dashboards/hardware.json, line 842 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPdJtk0uE401_ergz8:-McPdJtk0uE401_ergz9:b-37ciq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L842)):*
> ```JSON
>       "targets": [
>         {
>           "expr": "rate(sys_host_net_recv_bytes{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
> ```

`sys_host_net_recv_bytes` -> `sys_host_net_send_bytes`
___
*[monitoring/grafana-dashboards/runtime.json, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPfMAXDQMaRRgAgf1-:-McPfMAXDQMaRRgAgf10:boyu2kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/runtime.json#L15)):*
> ```JSON
>     ]
>   },
>   "editable": true,
> ```

Can we add the "Runnable Goroutines per CPU" graph to this dashboard?
___
*[monitoring/grafana-dashboards/replication.json, line 911 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPf-jfCaDKq4gZHP6-:-McPf-jfCaDKq4gZHP60:b-ylo4r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/replication.json#L911)):*
> ```JSON
>           "$$hashKey": "object:1110",
>           "format": "short",
>           "label": "Reservations",
> ```

I think this second Y Axis object can be removed. Not sure what it's for.


<!-- Sent from Reviewable.io -->

2021-06-17 19:22 UTC, abarganier reviewed
Nice work! I have some small nits, mostly just typos though. Agreed with @dhartunian that full width would be nice to have.

Also, is it possible to default the time range for each dashboard to some value? I noticed when switching from one to the other that sometimes the time range would change (e.g. it was 30m, but then switched to 6h)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McQPi85C1TnPp19-9pe:b-yw4u6k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @sai-roach)

___
*[monitoring/grafana-dashboards/distributed.json, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQMHAw5nbYUzdpmP6g:-McQMHAw5nbYUzdpmP6h:bqya94t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/distributed.json#L288)):*
> ```
>  Lease Holder
> ```
nit: Cluster UI has "Leaseholder" as one word :) 
___
*[monitoring/grafana-dashboards/distributed.json, line 505 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQMbVY5l9MAmdwuMLA:-McQMbVY5l9MAmdwuMLB:b36ovi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/distributed.json#L505)):*
> ```
> "title": "KV Transaction Restarts",
> ```
For this one, I think our time series labels need to be adjusted. Right now Grafana shows the labels for each node, but Cluster UI shows various specific classifications. See example below. Is this something we can replicate in Grafana?

![Screen Shot 2021-06-17 at 3.06.37 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/vyulqgnAxF1FIkafLVnCn9_v/Screen%20Shot%202021-06-17%20at%203.06.37%20PM.png)
![Screen Shot 2021-06-17 at 3.06.31 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/gkKCzuV8VQoH5zt3TdYa9wNz/Screen%20Shot%202021-06-17%20at%203.06.31%20PM.png)
___
*[monitoring/grafana-dashboards/hardware.json, line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQFNYq2MHlzZt2CEjt:-McQFNYq2MHlzZt2CEju:b-5jc117) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L279)):*
> ```
> "title": "Disk Read"
> ```
nit: can we make this "Disk Read MiB/s"? 
___
*[monitoring/grafana-dashboards/hardware.json, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQFWNc7TnMUb4Xkrmo:-McQFWNc7TnMUb4Xkrmp:b-tt5f81) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L374)):*
> ```
> Disk Write"
> ```
nit: same as above, can we make it "Disk Write MiB/s"? I want to make sure it's obvious that this is using the `rate()` fn
___
*[monitoring/grafana-dashboards/queues.json, line 1155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQO5Yc3EY98WMaiNwd:-McQO5Yc3EY98WMaiNwe:b5ltth8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/queues.json#L1155)):*
> ```
> "Successful Actions"
> ```
nit: Cluster UI has this as "Successful Actions / sec"
___
*[monitoring/grafana-dashboards/runtime.json, line 720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQJ3rK840i8irt8zB_:-McQJ3rLB9apB6Iqkibd:b-mo96cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/runtime.json#L720)):*
> ```
> format": "µs",
> ```
nit: Not sure if there's any way around this.... But when hovering over a datapoint it shows `ms` instead of `µs`, although it seems like things are configured as expected here.

![Screen Shot 2021-06-17 at 2.52.19 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/Pb9Hxr2AUFHy-du03ExlC1Vm/Screen%20Shot%202021-06-17%20at%202.52.19%20PM.png)
![Screen Shot 2021-06-17 at 2.52.25 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/8-CqFlaKOQU3o1x9mc_u8Zyn/Screen%20Shot%202021-06-17%20at%202.52.25%20PM.png)
___
*[monitoring/grafana-dashboards/sql.json, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQJinnBb_5ffm1EzD0:-McQJinnBb_5ffm1EzD1:b-cr2wxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/sql.json#L194)):*
> ```
> "label": "connections",
> ```
nit: "transactions" 
___
*[monitoring/grafana-dashboards/overview.json, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQGWQlBEq_f85hWSG8:-McQGWQlBEq_f85hWSG9:bvlwjj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/overview.json#L197)):*
> ```
> "title": "Service Latency: SQL, 99th Percentile",
> ```
This chart looked inconsistent to me compared to what shows up in cluster UI. See below:

![Screen Shot 2021-06-17 at 2.39.58 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/GhMeeBr88sznizWCBrHbh3xK/Screen%20Shot%202021-06-17%20at%202.39.58%20PM.png)
![Screen Shot 2021-06-17 at 2.40.04 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/A8lckp0HFMtChx0rlJM9u90G/Screen%20Shot%202021-06-17%20at%202.40.04%20PM.png)

My main concern here is the difference in value - notice that the 2nd increase in latency is quite a bit larger in Grafana than in Cluster UI. 
___
*[monitoring/grafana-dashboards/replication.json, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQLTfMCdYekIM55DKi:-McQLTfMCdYekIM55DKj:b-49qf2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/replication.json#L529)):*
> ```
> "label": null,
> ```
nit: I think this one should be labeled "logical store size"
___
*[monitoring/grafana-dashboards/replication.json, line 615 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQLf6p7vpauOVSLhrl:-McQLf6qEDX_-fJlkJis:b8lwbfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/replication.json#L615)):*
> ```
> Quiescene
> ```
nit: typo, "Quiescence"
___
*[monitoring/grafana-dashboards/slow_request.json, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQOgrz2x8SUiDZMaAs:-McQOgrz2x8SUiDZMaAt:b-rbftjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/slow_request.json#L263)):*
> ```
> "Slow lease Acquisitions",
> ```
nit: capitalize "Lease"


<!-- Sent from Reviewable.io -->

2021-06-21 18:52 UTC, kzh reviewed
> @kzh is it possible to make all the dashboards have the plots at full width?

Done.

> Also, is it possible to default the time range for each dashboard to some value? I noticed when switching from one to the other that sometimes the time range would change (e.g. it was 30m, but then switched to 6h).

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-Mcjk9aNBRkK3hnRfm0y:b-ccoo5i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @rimadeodhar)

___
*[monitoring/grafana-dashboards/distributed.json, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQMHAw5nbYUzdpmP6g:-McjD3-Z-DdIbHWXk83f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/distributed.json#L288)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
>  Lease Holder
> ```
nit: Cluster UI has "Leaseholder" as one word :) 
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/distributed.json, line 505 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQMbVY5l9MAmdwuMLA:-McjjB5ECZVeMeBtDLoH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/distributed.json#L505)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "title": "KV Transaction Restarts",
> ```
For this one, I think our time series labels need to be adjusted. Right now Grafana shows the labels for each node, but Cluster UI shows various specific classifications. See example below. Is this something we can replicate in Grafana?

![Screen Shot 2021-06-17 at 3.06.37 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/vyulqgnAxF1FIkafLVnCn9_v/Screen%20Shot%202021-06-17%20at%203.06.37%20PM.png)
![Screen Shot 2021-06-17 at 3.06.31 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/gkKCzuV8VQoH5zt3TdYa9wNz/Screen%20Shot%202021-06-17%20at%203.06.31%20PM.png)

</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/hardware.json, line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQFNYq2MHlzZt2CEjt:-McjtI2D-XD2HFIKSyN6:bci8mcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L279)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "title": "Disk Read"
> ```
nit: can we make this "Disk Read MiB/s"? 
</blockquote></details>

Done. I changed it to B/s (bytes/s). Originally I removed this because db console has this feature where the units in the title scale dynamically with the magnitude of the data (ex. KiB/s MiB/s GiB/s). However, this doesn't seem possible in grafana. 
___
*[monitoring/grafana-dashboards/hardware.json, line 374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQFWNc7TnMUb4Xkrmo:-Mcju31Y-00grvexvYPL:bi9gxec) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L374)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> Disk Write"
> ```
nit: same as above, can we make it "Disk Write MiB/s"? I want to make sure it's obvious that this is using the `rate()` fn
</blockquote></details>

Done. I changed it to B/s for the reasons listed in the previous comment.
___
*[monitoring/grafana-dashboards/hardware.json, line 459 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPbcs30TE-jGEfH9q8:-McjfPQc5mXliRNnYXn1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L459)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

`instacne` -> `instance`
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/hardware.json, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPdYzU8XaOf3FpcxXX:-McjfQYn-LNlJUyzMCyS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L700)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you add the "Available Disk Capacity" graph here? `cr.store.capacity.available`
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/hardware.json, line 842 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPdJtk0uE401_ergz8:-McjfPwH8rIa1pwMVB_b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/hardware.json#L842)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

`sys_host_net_recv_bytes` -> `sys_host_net_send_bytes`
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/queues.json, line 1155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQO5Yc3EY98WMaiNwd:-McjfBTc7KMIMngVgcoj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/queues.json#L1155)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "Successful Actions"
> ```
nit: Cluster UI has this as "Successful Actions / sec"
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/runtime.json, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McPfMAXDQMaRRgAgf1-:-McjfGJh07CrEwRRmQIu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/runtime.json#L15)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we add the "Runnable Goroutines per CPU" graph to this dashboard?
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/runtime.json, line 720 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQJ3rK840i8irt8zB_:-McjfICT69-PmOZM6yEX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/runtime.json#L720)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> format": "µs",
> ```
nit: Not sure if there's any way around this.... But when hovering over a datapoint it shows `ms` instead of `µs`, although it seems like things are configured as expected here.

![Screen Shot 2021-06-17 at 2.52.19 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/Pb9Hxr2AUFHy-du03ExlC1Vm/Screen%20Shot%202021-06-17%20at%202.52.19%20PM.png)
![Screen Shot 2021-06-17 at 2.52.25 PM.png](https://files.reviewableusercontent.io/images/reviewable/8194877/8-CqFlaKOQU3o1x9mc_u8Zyn/Screen%20Shot%202021-06-17%20at%202.52.25%20PM.png)
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/sql.json, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQJinnBb_5ffm1EzD0:-McjfLYN0ls7ZBUBLxVq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d145e880ef593668d060ffa3460b64459f8be74/monitoring/grafana-dashboards/sql.json#L194)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> "label": "connections",
> ```
nit: "transactions" 
</blockquote></details>

Done.
___
*[monitoring/grafana-dashboards/overview.json, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-McQGWQlBEq_f85hWSG8:-McjrU7Z48sp1GwkvXKl:b-pha7ji) ([raw file](https://github.com/cockroachdb/cockroach/bl [...]

2021-06-21 22:16 UTC, dhartunian approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> nice work @kzh!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-MckdAqp0qDB7_Vvvs8j:bva8ral)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)



<!-- Sent from Reviewable.io -->

2021-06-22 16:11 UTC, abarganier approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :raised_hands: Thanks for all the work here @kzh

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63488#-:-McoUFxHE_91XFi7H2pD:b9u9idk)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @abarganier and @rimadeodhar)



<!-- Sent from Reviewable.io -->

2021-06-22 16:42 UTC, kzh commented
bors r+

2021-06-22 21:56 UTC, merged