ccl: call rows.Err() when rows.Next() returns false
cockroachdb/cockroach pull request #63543
Opened 2021-04-13 11:05 UTC by stevendanna

This change fixes instances where we failed to rows.Err() after
rows.Next() returned false.

All of the changes are in test code, so it is likely that there wasn't
much user-impact here.

These were found with the rowserrcheck linter.

Informs #61059

Release note: None

2021-04-13 11:05 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63543)
<!-- Reviewable:end -->

2021-04-13 14:46 UTC, miretskiy requested changes

2021-04-14 13:33 UTC, stevendanna commented on pkg/ccl/backupccl/backup_test.go
> +				}
Happy to convert them over to that, but I was generally trying to keep with the existing style in each file.

2021-04-14 13:39 UTC, miretskiy approved these changes

2021-04-14 13:39 UTC, miretskiy commented on pkg/ccl/backupccl/backup_test.go
> +				}
right... Okay.

2021-04-14 15:52 UTC, stevendanna commented
bors r=miretskiy

2021-04-14 17:28 UTC, merged