roachprod: shorten the connection timeout for ssh
cockroachdb/cockroach pull request #63607
Opened 2021-04-14 00:19 UTC by alan-mas

Based on #47567 we need to ensure that roachprod has timeout for ssh connection after 5 seconds.

We add a constant for timeout and using it inside newSSHClient function.

Release note: None

2021-04-14 00:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63607)
<!-- Reviewable:end -->

2021-04-16 02:09 UTC, jlinder requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas)

___
*[pkg/cmd/roachprod/ssh/ssh.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGSo4Cy_73Fa8vTLH:-MYNGSo4Cy_73Fa8vTLI:b-cd2awd) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L40)):*
> ```Go
> var InsecureIgnoreHostKey bool
> 
> const timeout = 5 * time.Second
> ```

If you use a variable to hold the calculated time, I'd suggest keeping it in the `newSSHClient` function so it's closer to where it's used.
___
*[pkg/cmd/roachprod/ssh/ssh.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGuHK604SBbI4eBCT:-MYNGuHK604SBbI4eBCU:bp2nzwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L121)):*
> ```Go
> 
> 	addr := fmt.Sprintf("%s:22", host)
> 	conn, err := net.DialTimeout("tcp", addr, timeout)
> ```

While this timeout should make the connection error out if it takes to long to connect, SSH has its own timeout as well (see [here](https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig)). That can be set in the `ssh.ClientConfig` struct created on the first line of this function. The default SSH timeout is 0, which means there is no timeout. I'd recommend setting that timeout to 5 seconds and this DialTimeout to 8 seconds for these reasons:

- It's not clear to me at the moment how the timeouts interact. Does the DialTimeout length encompass the SSH timeout? Does the SSH timeout override the DialTimeout timeout?
- We want the error to come from SSH since that will produce an expected exit status of 255 from SSH and we want to detect that status code in other places in the code. It's not clear that the DialTimeout timeout would produce an SSH 255 exit code. So we want to try to get the SSH timeout to be the one that wins normally.


<!-- Sent from Reviewable.io -->

2021-04-16 07:58 UTC, tbg reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas and @jlinder)

___
*[pkg/cmd/roachprod/ssh/ssh.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGuHK604SBbI4eBCT:-MYOf8xECPKOumZypL2O:b-yk186x) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L121)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

While this timeout should make the connection error out if it takes to long to connect, SSH has its own timeout as well (see [here](https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig)). That can be set in the `ssh.ClientConfig` struct created on the first line of this function. The default SSH timeout is 0, which means there is no timeout. I'd recommend setting that timeout to 5 seconds and this DialTimeout to 8 seconds for these reasons:

- It's not clear to me at the moment how the timeouts interact. Does the DialTimeout length encompass the SSH timeout? Does the SSH timeout override the DialTimeout timeout?
- We want the error to come from SSH since that will produce an expected exit status of 255 from SSH and we want to detect that status code in other places in the code. It's not clear that the DialTimeout timeout would produce an SSH 255 exit code. So we want to try to get the SSH timeout to be the one that wins normally.

</blockquote></details>

`ssh.ClientConfig.Timeout` has no effect in the code as written, as it is only used by `ssh.Dial` (but we call `NewClientConn` directly). I think we should rewrite this whole method as just

```go
config := ... // same but with Timeout set
// (don't need config.SetDefaults())
return ssh.Dial("tcp", host+":22", config)
```

This won't return the `net.Conn` as the method does today, but there's only one caller who doesn't actually use it.


<!-- Sent from Reviewable.io -->

2021-04-17 00:00 UTC, alan-mas commented
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63607)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas)
> 
> _[pkg/cmd/roachprod/ssh/ssh.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGSo4Cy_73Fa8vTLH:-MYNGSo4Cy_73Fa8vTLI:b-cd2awd) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L40)):_
> 
> > ```go
> > var InsecureIgnoreHostKey bool
> > 
> > const timeout = 5 * time.Second
> > ```
> 
> If you use a variable to hold the calculated time, I'd suggest keeping it in the `newSSHClient` function so it's closer to where it's used.
> 
> _[pkg/cmd/roachprod/ssh/ssh.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGuHK604SBbI4eBCT:-MYNGuHK604SBbI4eBCU:bp2nzwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L121)):_
> 
> > ```go
> > 	addr := fmt.Sprintf("%s:22", host)
> > 	conn, err := net.DialTimeout("tcp", addr, timeout)
> > ```
> 
> While this timeout should make the connection error out if it takes to long to connect, SSH has its own timeout as well (see [here](https://pkg.go.dev/golang.org/x/crypto/ssh#ClientConfig)). That can be set in the `ssh.ClientConfig` struct created on the first line of this function. The default SSH timeout is 0, which means there is no timeout. I'd recommend setting that timeout to 5 seconds and this DialTimeout to 8 seconds for these reasons:
> 
> * It's not clear to me at the moment how the timeouts interact. Does the DialTimeout length encompass the SSH timeout? Does the SSH timeout override the DialTimeout timeout?
> * We want the error to come from SSH since that will produce an expected exit status of 255 from SSH and we want to detect that status code in other places in the code. It's not clear that the DialTimeout timeout would produce an SSH 255 exit code. So we want to try to get the SSH timeout to be the one that wins normally.

Not sure I did understand correctly changes from tbg but I already change go code =) I took away complete other loops and only keep one err and return dial as he suggested =)

2021-04-19 12:39 UTC, petermattis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas and @jlinder)

___
*[pkg/cmd/roachprod/ssh/ssh.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MYNGuHK604SBbI4eBCT:-MYe7Qw7AOvT9JxW6dn8:b-umaqbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/834a479c919c2fb3dd013e08766cca9c8a864c63/pkg/cmd/roachprod/ssh/ssh.go#L121)):*
<details><summary><i>Previously, alan-mas (alanmas) wrote…</i></summary><blockquote>

Not sure I did understand correctly changes from tbg but I already change go code =) I took away complete other loops and only keep one err and return dial as he suggested =)
</blockquote></details>

FYI, the `roachprod/ssh` package is historical detritus. It is currently used. We encountered difficulties with it in the past and switched to fork/exec'ing `ssh` rather than constructing connections like this. The real ssh code is in `newRemoteSession`.

This `ssh` package should probably be deleted to avoid confusing someone else in the future.


<!-- Sent from Reviewable.io -->

2021-04-26 19:35 UTC, jlinder requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alan-mas and @jlinder)

___
*[pkg/cmd/roachprod/install/session.go, line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63607#-MZEd5Yc7KQkRSelPbeL:-MZEd5Yc7KQkRSelPbeM:bm83kza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f160e4766aec1907ff9a5f4954a20253f247710/pkg/cmd/roachprod/install/session.go#L74)):*
> ```
> 		// Adding timeout so the roachtest context cancellation does hide failure
> 		// information by kill hanging processes before they fail.
> ```
Suggesting:

```
  // Timeout long connections so failure information is not lost by the roachtest
  // context cancellation killing hanging roachprod processes.
```


<!-- Sent from Reviewable.io -->

2021-04-28 01:23 UTC, jlinder approved these changes
LGTM

2021-04-29 15:37 UTC, jlinder commented
bors r+

2021-04-29 15:39 UTC, jlinder commented
bors r+

2021-04-29 16:49 UTC, merged