bazel: tweak logic for staging test artifacts in bazci
cockroachdb/cockroach pull request #63767
Opened 2021-04-15 22:21 UTC by rickystewart

Because Bazel aggressively caches build/test artifacts, if we're not
careful, bazci can copy OLD artifacts from previous build/test runs into
the artifacts directory. This is particularly an issue because TeamCity
watches that directory for `test.xml` reports, and if an old `test.xml`
reports a test failure, TeamCity will notice that and report the failure
in the UI -- and importantly, even if we replace that `test.xml` with a
completely different one that reports that the test succeeed, TC will
not amend what's displayed in the UI accordingly. So this can manifest
as reported test failures from unrelated PR's showing up in TC in an
apparently unpredictable (though uncommmon) manner.

We fix this by making bazci a little smarter about when we choose to
stage artifacts:

1. The first time the watcher loops over all the test artifacts, never
   stage anything (the artifacts are probably cached -- not enough time
   has passed for any legitimate artifacts to appear, probably).
2. Only stage artifacts incrementally if their stats have changed since
   the initial round of caching.
3. During the final loop, stage ALL artifacts (if they haven't been
   staged yet), just to make sure we don't miss anything.

Also add lots of comments to make these design decisions and their
motivations a little clearer.

Resolves #63740.

Release note: None

2021-04-15 22:21 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63767)
<!-- Reviewable:end -->

2021-04-15 22:43 UTC, rickystewart commented
Ah, I think this isn't behaving *exactly* how I wanted to, recalling for now :)

2021-04-20 21:30 UTC, rickystewart commented
days later, i realized it's because go switch statements don't work like they do in C 🙃

2021-04-23 02:28 UTC, rail requested changes
In overall it look good to me. There are a couple of small changes.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63767#-:-MYwYNS89XQmp-EA0LPn:b-hrozv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/cmd/bazci/watch.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63767#-MYp_MMa4Wcly2NV56Ts:-MYpZXVX9DR36kXoHOj8:b-no0ms0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb6a4c33743c9dc949d0a1de6566fe7481a5c54/pkg/cmd/bazci/watch.go#L73)):*
> ```
> 	fileToStaged map[string]bool
> ```
I think you can use empty structs here - they are memory friendly than bool. https://dave.cheney.net/2014/03/25/the-empty-struct is a good read about those.
___
*[pkg/cmd/bazci/watch.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63767#-MYwX-YV1lEdopTBHerc:-MYwX-YW5D3gJ7ZeGl2A:b-wkdp66) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb6a4c33743c9dc949d0a1de6566fe7481a5c54/pkg/cmd/bazci/watch.go#L253)):*
> ```Go
> }
> 
> var _ io.WriteCloser = (*cancelableWriter)(nil)
> ```

Did you add this to make sure we implement the interface? Can you add a short comment please.


<!-- Sent from Reviewable.io -->

2021-04-23 16:41 UTC, rickystewart reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[pkg/cmd/bazci/watch.go, line 253 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63767#-MYwX-YV1lEdopTBHerc:-MYzamZ64amdfl1LNGq_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fb6a4c33743c9dc949d0a1de6566fe7481a5c54/pkg/cmd/bazci/watch.go#L253)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Did you add this to make sure we implement the interface? Can you add a short comment please.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 16:55 UTC, rail approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63767)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)



<!-- Sent from Reviewable.io -->

2021-04-23 17:15 UTC, rickystewart commented
bors r=rail

2021-04-23 19:47 UTC, merged