backupccl: add backup_type to SHOW BACKUP
cockroachdb/cockroach pull request #63832
Opened 2021-04-19 01:59 UTC by nihalpednekar

Previously, SHOW BACKUP users had to rely on the NULLness of
start_time to distinguish between full and incremental backups.
This commit makes it explicit by adding a 'backup_type' column,
whose value can be one of 'full' or 'incremental'.

Release note (enterprise change): SHOW BACKUP now shows whether
the backup is full or incremental under the 'backup_type' column.

Release justification: low risk, high benefit change to existing
functionality.

2021-04-19 01:59 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63832)
<!-- Reviewable:end -->

2021-04-20 10:27 UTC, adityamaru requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nihalpednekar)

___
*[pkg/ccl/backupccl/manifest_handling.go, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63832#-MYimoXgCcQGZwkzTKDk:-MYimoXgCcQGZwkzTKDl:bvv6g6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/6afa52148cdd5a6e54bf28e0ee281e42fe72c933/pkg/ccl/backupccl/manifest_handling.go#L114)):*
> ```Go
> // IsIncremental reads a BackupManifest and returns false or true
> // corresponding to the backup being full or incremental.
> func (m *BackupManifest) IsIncremental() bool {
> ```

I don't think this method needs to be exported since show.go is also in backupccl? 


<!-- Sent from Reviewable.io -->

2021-04-20 10:28 UTC, adityamaru commented
We don't need to add a release justification since we are merging this into master, and not backporting to a release branch.

2021-04-20 20:21 UTC, nihalpednekar commented
Made both the fixes, PTAL

2021-04-20 20:34 UTC, nihalpednekar commented
Also quick question about the release note: [this page](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) seems to suggest user facing changes should have a release note?

2021-04-20 21:14 UTC, adityamaru commented
> Also quick question about the release note: [this page](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) seems to suggest user facing changes should have a release note?

Yup! The release note you had previously was good. The docs team uses these release notes to identify what needs to be called out when a feature is being released.

2021-04-20 21:14 UTC, adityamaru approved these changes

2021-04-20 21:15 UTC, adityamaru commented
LGTM once you re-add the release note 👍

2021-04-21 15:22 UTC, nihalpednekar commented
TFTR!

bors r+

2021-04-21 15:38 UTC, nihalpednekar commented
bors r+

2021-04-21 15:39 UTC, nihalpednekar commented
bors r-

2021-04-21 15:40 UTC, nihalpednekar commented
bors r+

2021-04-21 16:25 UTC, merged