stop: break deadlock between Stopper.mu and Replica.mu
cockroachdb/cockroach pull request #63867
Opened 2021-04-19 19:14 UTC by irfansharif

Fixes #63761. As of #61279, it was possible for us to deadlock due to
inconsistent lock orderings between Stopper.mu and Replica.mu. We were
previously holding onto Stopper.mu while executing all closers,
including those that may acquire other locks. Because closers can be
defined anywhere (and may consequently grab any in-scope lock), we
should order Stopper.mu to come after all other locks in the system.

The closer added in #61279 iterated over all non-destroyed replicas,
locking Replica.mu to check for the replica's destroy status (in
Store.VisitReplicas). This deadlocked with the lease acquisition code
path that first grabs an exclusive lock over Replica.mu (see
InitOrJoinRequest), and uses the stopper to kick off an async task
acquiring the lease. The stopper internally locks Stopper.mu to check
whether or not it was already stopped.

Release note: None

2021-04-19 19:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63867)
<!-- Reviewable:end -->

2021-04-19 19:38 UTC, andreimatei requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/kv/kvserver/store.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfcEX_74SOSi4U53d3:-MYfcEX_74SOSi4U53d4:bhni1m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/kv/kvserver/store.go#L474)):*
> ```Go
> 	// obeyed: baseQueue.mu < Replica.raftMu < Replica.readOnlyCmdMu < Store.mu
> 	// < Replica.mu < Replica.unreachablesMu < Store.coalescedMu
> 	// < Store.scheduler.mu < Stopper.mu.
> ```

I don't think including `stopper.mu` in this list is a good idea... That's a library lock not directly related to replica processing.
___
*[pkg/util/stop/stopper.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfbex08fE7E_xx8KCt:-MYfbex08fE7E_xx8KCu:b-z3w30o) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/util/stop/stopper.go#L477)):*
> ```Go
> 	s.mu.Lock()
> 	closers := s.mu.closers
> 	defer s.mu.Unlock()
> ```

mmm I don't think you've fixed what you wanted to fix... We're still calling the closer under the lock. I think you don't want to `defer` the unlock any more.

In fact I think you don't even need to take this lock any more, based on the same argument below about how new closers can't be added any more (and the freezing was done by this thread ).
___
*[pkg/util/stop/stopper.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfcK503a5mJGCjTNSD:-MYfcK503a5mJGCjTNSE:b-ukw6kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/util/stop/stopper.go#L479)):*
> ```Go
> 	defer s.mu.Unlock()
> 
> 	// We can't hold on to Stopper.mu while executing closers. Closers are
> ```

s/Stopper.mu/s.mu (or just "the lock").
___
*[pkg/util/stop/stopper.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfb73FCUMwfilYVm9p:-MYfb73G7LXBxR63xnNq:b-ud9pe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/util/stop/stopper.go#L481)):*
> ```Go
> 	// We can't hold on to Stopper.mu while executing closers. Closers are
> 	// allowed to be defined anywhere, and are allowed to grab any lock
> 	// available. As far as lock ordering is concerned, Stopper.mu comes after
> ```

nit: what does "any lock available" mean? I think this note is generally too verbose; just say "run the closers without holding the lock". Avoiding calling callbacks with locks held is a very common thing.


<!-- Sent from Reviewable.io -->

2021-04-19 19:45 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/store.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfcEX_74SOSi4U53d3:-MYfedEjAzNGbAnPpjfo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/kv/kvserver/store.go#L474)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think including `stopper.mu` in this list is a good idea... That's a library lock not directly related to replica processing.
</blockquote></details>

Done.
___
*[pkg/util/stop/stopper.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfbex08fE7E_xx8KCt:-MYfeeSEBVZBcEK8Abys:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/util/stop/stopper.go#L477)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm I don't think you've fixed what you wanted to fix... We're still calling the closer under the lock. I think you don't want to `defer` the unlock any more.

In fact I think you don't even need to take this lock any more, based on the same argument below about how new closers can't be added any more (and the freezing was done by this thread ).
</blockquote></details>

Done.
___
*[pkg/util/stop/stopper.go, line 479 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-MYfcK503a5mJGCjTNSD:-MYfefIx4DHoE-4uOKBj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48eedde5ab7d46277e183d2cfb90fff0e6fbb169/pkg/util/stop/stopper.go#L479)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/Stopper.mu/s.mu (or just "the lock").
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 21:12 UTC, andreimatei reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63867#-:-MYfy8IG0gjAoqAMmmWc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)



<!-- Sent from Reviewable.io -->

2021-04-20 04:47 UTC, irfansharif commented
bors r+

2021-04-20 05:45 UTC, merged