changefeed,server: changefeed histograms and configurable slow logging
cockroachdb/cockroach pull request #63923
Opened 2021-04-20 13:55 UTC by stevendanna

See the individual commits for details.

Overall, the goal of these changes is to get more information about the ongoing test failures
we are seeing in cdc/ledger and cdc/cloud-sink-gcs roachtests.

A number of log messages we might expect to see when the the changeFrontier is behind
aren't emitted because we auto-calculate a slow logging threshold based on the 
closed_timestamp.target_duration setting which we are increasing in these tests.

Further, the current metrics around emitting and flushing are a single counter, which is fine for 
many purposes because the timeseries database allows us to look at the values over time, but when
trying to debug a test issue after-the-fact, the timeseries database is gone and it would be nice to have the 
histogram data.

2021-04-20 13:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/63923)
<!-- Reviewable:end -->

2021-04-20 14:14 UTC, miretskiy requested changes
> Reviewed 1 of 2 files at r1, 2 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63923)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/metrics.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63923#-MYjaH045M6fPIOpL0rU:-MYjaH045M6fPIOpL0rV:b-ssfnry) ([raw file](https://github.com/cockroachdb/cockroach/blob/204ba407b6ac202d786b2d225a8d5ad4edc36abc/pkg/ccl/changefeedccl/metrics.go#L166)):*
> ```Go
> 	// reconstructed from information in the histogram, I've kept
> 	// the older metrics to avoid breaking historical timeseries
> 	// data.
> ```

nit: This doesn't sound like a todo to me... I think it's totally fine to have histogram + gauge.
I'd just leave this as a comment (minus todo)
___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63923#-MYjcFMi5wRY8uVRx2sY:-MYjcFMi5wRY8uVRx2sZ:b-tvy4m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/204ba407b6ac202d786b2d225a8d5ad4edc36abc/pkg/ccl/changefeedccl/changefeedbase/options.go#L44)):*
> ```Go
> 	OptProtectDataFromGCOnPause = `protect_data_from_gc_on_pause`
> 	OptSlowSpanLogThreshold     = `slow_span_log_threshold`
> ```

The slow span logging threshold seems to be a low level debugging knob. I'm not sure this rises to the
statement level option.  I think having a cluster setting is probably sufficient.
WDYT?


<!-- Sent from Reviewable.io -->

2021-04-20 14:20 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63923)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63923#-MYjcFMi5wRY8uVRx2sY:-MYjdUsPCfBjmHr2crqQ:b-njypi) ([raw file](https://github.com/cockroachdb/cockroach/blob/204ba407b6ac202d786b2d225a8d5ad4edc36abc/pkg/ccl/changefeedccl/changefeedbase/options.go#L44)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

The slow span logging threshold seems to be a low level debugging knob. I'm not sure this rises to the
statement level option.  I think having a cluster setting is probably sufficient.
WDYT?
</blockquote></details>

I agree. I originally implemented this as a statement level option and then when I was actually playing with it I realised "oh, I kinda want to turn it off without restarting the feed" which is why I added the cluster setting.  I think for most cases the cluster setting will be what people want. I'll back out the statement-level configurable.


<!-- Sent from Reviewable.io -->

2021-04-20 16:30 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63923)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeedbase/options.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63923#-MYjcFMi5wRY8uVRx2sY:-MYk6SkR1xmtntanpg3z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204ba407b6ac202d786b2d225a8d5ad4edc36abc/pkg/ccl/changefeedccl/changefeedbase/options.go#L44)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I agree. I originally implemented this as a statement level option and then when I was actually playing with it I realised "oh, I kinda want to turn it off without restarting the feed" which is why I added the cluster setting.  I think for most cases the cluster setting will be what people want. I'll back out the statement-level configurable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-20 18:06 UTC, miretskiy approved these changes
> Reviewed 1 of 9 files at r4, 1 of 6 files at r5, 2 of 2 files at r6, 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63923)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB)



<!-- Sent from Reviewable.io -->

2021-04-22 11:55 UTC, stevendanna commented
bors r=miretskiy

2021-04-22 12:57 UTC, stevendanna commented
Looks like I wasn't rebased on top of eb44d974bbe7f77a1159ea1da8a7676690b8fb04 so we are now hitting an error related to MaxSettings.

2021-04-22 15:01 UTC, stevendanna commented
bors r+

2021-04-22 16:20 UTC, merged