storage: report all encountered intents in sst export error
cockroachdb/cockroach pull request #64131
Opened 2021-04-23 14:35 UTC by aliher1911

Previously, pebbleExportToSst was stopping upon encountering first
intent.

This was causing backups to be very slow if lots of intents build up.
To be able to proceed with export, intent needs to be resolved and
export retried. The result of this behaviour is that export would run
as many times as there were intents in the table before succeeding.

To address this, all intents from the range are collected and reported
in WriteIntentError. They could be resolved efficiently as batch
similar to how GC operates.

Release note (bug fix): Backup no longer resolves intents one by one.
This eliminates running a high pri query to cleanup intents to unblock
backup in case of intent buildup.

2021-04-23 14:35 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/64131)
<!-- Reviewable:end -->

2021-04-23 19:42 UTC, aliher1911 commented
@sumeerbhola Does this change make sense? I'm collecting all intents post failure to export. It is closing and reusing underlying iterator and it technically work fine, but is it conceptually right thing to do?

2021-04-23 19:45 UTC, aliher1911 commented
@nvanbenschoten Makes sense? It makes my repro backup smoothly even with 1000s intents. Needs more tests as discussed in original issue, so draft state for now.

2021-04-26 20:33 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 1675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEoaxoEl7UrGgRVAsC:-MZEoaxoEl7UrGgRVAsD:b-ur3hdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1675)):*
> ```Go
> 	useTBI bool,
> ) ([]byte, roachpb.BulkOpSummary, roachpb.Key, error) {
> 	data, sum, key, err := pebbleExportToFirstFailure(reader, startKey, endKey, startTS, endTS, exportAllRevisions, targetSize, maxSize, useTBI)
> ```

I'm curious to get Sumeer's opinion on this technique, because I'm torn. The approach does work and it comes with a few benefits. The largest benefit seems to be that we don't need to change the `MVCCIncrementalIterator` interface to lift intents up into the iteration loop and force callers to construct a WriteIntentError themselves. It also makes it easier to disable SST creation after the first intent is reached, which would be useless work.

However, there are also some drawbacks here. A second iteration introduces complexity and more room for error as we try to line up the end of the first iteration with the beginning of the second iteration and try to determine which keys are intents. It also introduces some inefficiency, as the second iteration is no longer using timestamp bounds, so it needs to look at every sst in its key range. Both of these issues would be avoided if we continued to collect intents in the first iteration pass.

Did you end up experimenting with the alternative approach? If so, did you run into any unexpected hurdles? Which approach results in cleaner code? Would lifting intents into the `MVCCIncrementalIterator` interface be helpful to other users?

It's also interesting to consider how this should work in a world with a separated lock table. Would we scan the lock table first without time-bound and then scan the MVCC keyspace after with time-bounds?
___
*[pkg/storage/pebble.go, line 1794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEqrBs8DzMf2mX2csl:-MZEqrBt41LKsr9nEgpf:b-29udo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1794)):*
> ```Go
> ) {
> 	if len(error.Intents) == 0 {
> 		// This is not a valid error to restart collection, bail out to avoid panic.
> ```

Should we Fatal here? This doesn't seem like it should be possible, and it doesn't seem like ignoring the error and skipping the iteration is the right thing to do.


<!-- Sent from Reviewable.io -->

2021-04-26 21:13 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 1675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEoaxoEl7UrGgRVAsC:-MZEzgXg1kUYMG3TU2QM:b-ze61wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1675)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm curious to get Sumeer's opinion on this technique, because I'm torn. The approach does work and it comes with a few benefits. The largest benefit seems to be that we don't need to change the `MVCCIncrementalIterator` interface to lift intents up into the iteration loop and force callers to construct a WriteIntentError themselves. It also makes it easier to disable SST creation after the first intent is reached, which would be useless work.

However, there are also some drawbacks here. A second iteration introduces complexity and more room for error as we try to line up the end of the first iteration with the beginning of the second iteration and try to determine which keys are intents. It also introduces some inefficiency, as the second iteration is no longer using timestamp bounds, so it needs to look at every sst in its key range. Both of these issues would be avoided if we continued to collect intents in the first iteration pass.

Did you end up experimenting with the alternative approach? If so, did you run into any unexpected hurdles? Which approach results in cleaner code? Would lifting intents into the `MVCCIncrementalIterator` interface be helpful to other users?

It's also interesting to consider how this should work in a world with a separated lock table. Would we scan the lock table first without time-bound and then scan the MVCC keyspace after with time-bounds?
</blockquote></details>

I did I first go at trying to reuse MVCCIncrementalIterator and change it slightly to resume iteration, but the logic to declare itself invalid once it finds first error seem to be at the core of it so I abandoned that after it became ugly enough. It looked like half of logic to unmarhal and process values has to be abstracted via provided function to make behaviour change doable.
Maybe we can make a "resume" iterator to collect errors from it that would inherit the state and keep iterating further?
___
*[pkg/storage/pebble.go, line 1794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEqrBs8DzMf2mX2csl:-MZF0c-sCuR5s5iKckP5:b-kr7au2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1794)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we Fatal here? This doesn't seem like it should be possible, and it doesn't seem like ignoring the error and skipping the iteration is the right thing to do.
</blockquote></details>

Makes sense, will change that once we converge on general approach.


<!-- Sent from Reviewable.io -->

2021-04-26 21:29 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/storage/pebble.go, line 1675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEoaxoEl7UrGgRVAsC:-MZF0MP2DkZ32qtAOLul:b-jst98e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1675)):*
> introduces some inefficiency, as the second iteration is no longer using timestamp bounds, so it needs to look at every sst in its key range

I think this is important enough to modify `MVCCIncrementalIterator`. I was imagining adding a mode to it where it treats intents as ignorable errors and accumulates them in a `WriteIntentError` and the caller can in each iteration confirm whether there is at least one accumulated intent. If there is at least one intent, the loop here will switch to a mode where it continues to iterate but doesn't add the keys to `sstWriter`.

And we should update the comment in `engine.go` for `ExportMVCCToSst` to say something more informative than `returns an error if an intent is found` -- the caller is relying on it being a `WriteIntentError`.

> It's also interesting to consider how this should work in a world with a separated lock table. Would we scan the lock table first without time-bound and then scan the MVCC keyspace after with time-bounds?

Agreed -- that is how it should work. We should add a TODO here as a reminder.
___
*[pkg/storage/pebble.go, line 1794 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEqrBs8DzMf2mX2csl:-MZF-u8L3nEN8XsMYL0o:b-442rz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1794)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we Fatal here? This doesn't seem like it should be possible, and it doesn't seem like ignoring the error and skipping the iteration is the right thing to do.
</blockquote></details>

This does look like an input invariant violation.


<!-- Sent from Reviewable.io -->

2021-04-28 10:43 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[pkg/storage/pebble.go, line 1675 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZEoaxoEl7UrGgRVAsC:-MZN3o9w9e2be-Dwqmcm:b-ketstd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e299d7a8a3e7ef02c04a34ad2e583022eb77111/pkg/storage/pebble.go#L1675)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> introduces some inefficiency, as the second iteration is no longer using timestamp bounds, so it needs to look at every sst in its key range

I think this is important enough to modify `MVCCIncrementalIterator`. I was imagining adding a mode to it where it treats intents as ignorable errors and accumulates them in a `WriteIntentError` and the caller can in each iteration confirm whether there is at least one accumulated intent. If there is at least one intent, the loop here will switch to a mode where it continues to iterate but doesn't add the keys to `sstWriter`.

And we should update the comment in `engine.go` for `ExportMVCCToSst` to say something more informative than `returns an error if an intent is found` -- the caller is relying on it being a `WriteIntentError`.

> It's also interesting to consider how this should work in a world with a separated lock table. Would we scan the lock table first without time-bound and then scan the MVCC keyspace after with time-bounds?

Agreed -- that is how it should work. We should add a TODO here as a reminder.
</blockquote></details>

As discussed offline, I moved logic into ```MVCCIncrementalIterator``` so that it could keep iterating the data after the first intent, but callers could check if we failed and skip collecting data further while still respecting batching constraints. They could also check that iterator is positioned at proposed intent value if needed.


<!-- Sent from Reviewable.io -->

2021-04-30 00:29 UTC, sumeerbhola requested changes
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @aliher1911)

___
*[pkg/storage/mvcc_incremental_iterator.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUgXyj5isfDMubfwdC:-MZUgXyj5isfDMubfwdD:bspxx80) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L112)):*
> ```Go
> 	EndTime   hlc.Timestamp
> 	// If intent aggregation is enabled, iterator will not fail on first encountered
> 	// intent, but could proceed further. All found intents would be aggregated into
> ```

nit: s/could/will/, s/would/will/
___
*[pkg/storage/mvcc_incremental_iterator.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUhkdR3RaX4vdAg6n8:-MZUhkdR3RaX4vdAg6n9:b2pzygp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L210)):*
> ```Go
> }
> 
> // checkNextAndSaveErr checks if underlying iter is valid after operation and
> ```

nits about missing "the": ... if the underlying iter is valid after the operation and saves the error ... Returns true if the ...
___
*[pkg/storage/mvcc_incremental_iterator.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUiAq_DOFpkznLH-eK:-MZUiAq_DOFpkznLH-eL:b-xre6ei) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L212)):*
> ```Go
> // checkNextAndSaveErr checks if underlying iter is valid after operation and
> // saves error and validity state. Returns true if underlying iterator is valid.
> func (i *MVCCIncrementalIterator) checkNextAndSaveErr() bool {
> ```

should this be called `isValidAndSaveErr`? It doesn't seem to matter that it is called in the context of `Next*()` methods since it is looking only at the current position. 
___
*[pkg/storage/mvcc_incremental_iterator.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUj1YX799G0yTwAoMD:-MZUj1YX799G0yTwAoME:b-3jdloa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L359)):*
> ```Go
> 			}
> 		} else {
> 			i.intents = append(i.intents, roachpb.MakeIntent(i.meta.Txn, i.iter.Key().Key))
> ```

We don't need the if-else-blocks. It is fine to append to a nil slice, so all we need is the code in this else-block.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUjQKq6VmCLRVOaMPA:-MZUjQKq6VmCLRVOaMPB:b-nrstk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L363)):*
> ```Go
> 		// We expect underlying iterator to contain proposed value after the intent, so we
> 		// need to move to that before proceeding to the next key. Proposed KV could be checked
> 		// by caller if needed.
> ```

I'd suggest dropping this checking and leaving it positioned at the intent (contrary to what I mentioned over chat), since (a) most of our code doesn't bother confirming such invariants that are not essential to its purpose, and (b) the code you have here isn't really checking that it is the provisional value -- it is just checking that the iter is valid -- it could be pointing to a different key or a different version of the same key but having a timestamp that does not match what the intent expects.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV7BqD8Tb3GhoQs_ZQ:-MZV7BqD8Tb3GhoQs_ZR:b-o7bkj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L391)):*
> ```Go
> 		// (startTime, endTime] so we do not throw an error, and attempt to move to
> 		// the next valid KV.
> 		if i.meta.Txn != nil && !i.atIntent {
> ```

Do we need this change to `advance` or track `atIntent` and expose `AtIntent()`.
I was imagining the caller would keep looking at `NumIntentErrors()` and as soon as it became > 0, break out of its "key collecting" mode and just use `NextKey` until `NumIntentErrors` crossed some upper bound (or the iterator was exhausted).
___
*[pkg/storage/mvcc_incremental_iterator.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUgo6x9iJkgAxEebUl:-MZUgo6x9iJkgAxEebUm:bdhddzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L490)):*
> ```Go
> }
> 
> // NumIntentErrors returns number of intents encountered intents during iteration.
> ```

... of intents encountered during ...
___
*[pkg/storage/mvcc_incremental_iterator.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUh4JqELJ4PLeW4e4H:-MZUh4JqELJ4PLeW4e4I:byadve2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L497)):*
> ```Go
> 
> // GetIntentError create write intent error with all collected intents that could be
> // used to retry operations.
> ```

nits:
- GetIntentError creates a write ...
- ... that can be used to resolve intents.
  (or perhaps you meant something else by "retry operations")
___
*[pkg/storage/pebble.go, line 1761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV9C6d4k6XEN-ODo7c:-MZV9C6d4k6XEN-ODo7d:bn589zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/pebble.go#L1761)):*
> ```Go
> 			iter.NextKey()
> 		}
> 	}
> ```

All the code in the loop is dealing with accumulating versions in `sstWriter` and size tracking, and the extra `skipData` mode is making it more complicated, and hard to see whether we are doing unnecessary work (e.g. we still seem to be calling `iter.Next` if `exportAllRevisions=true`, even though we don't need to if we are only accumulating intents).
 I think it would be cleaner to break out of that loop and add another loop that just uses `NextKey` to accumulate intents. And then we can more cleanly add a max count limit on intents.


<!-- Sent from Reviewable.io -->

2021-04-30 16:27 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @sumeerbhola)

___
*[pkg/storage/mvcc_incremental_iterator.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUhkdR3RaX4vdAg6n8:-MZXO3TY7S8nog3-f_6H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L210)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nits about missing "the": ... if the underlying iter is valid after the operation and saves the error ... Returns true if the ...
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 212 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUiAq_DOFpkznLH-eK:-MZXOLVw7iM8fzdguj3U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L212)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be called `isValidAndSaveErr`? It doesn't seem to matter that it is called in the context of `Next*()` methods since it is looking only at the current position. 
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 359 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUj1YX799G0yTwAoMD:-MZXOo7v0Ezxzm2pIjxF:biggc4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L359)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We don't need the if-else-blocks. It is fine to append to a nil slice, so all we need is the code in this else-block.
</blockquote></details>

TIL: slice functions are nil safe 😀
___
*[pkg/storage/mvcc_incremental_iterator.go, line 363 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUjQKq6VmCLRVOaMPA:-MZY1mix8FgTIOrAC2Av:bamskys) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L363)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'd suggest dropping this checking and leaving it positioned at the intent (contrary to what I mentioned over chat), since (a) most of our code doesn't bother confirming such invariants that are not essential to its purpose, and (b) the code you have here isn't really checking that it is the provisional value -- it is just checking that the iter is valid -- it could be pointing to a different key or a different version of the same key but having a timestamp that does not match what the intent expects.
</blockquote></details>

Done. The idea to skip here comes from what advance() does when it encounters intent which is outside of time range, it simply skips one entry. But I agree it makes no sense to do it here if we can just let advance do it for us.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 391 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV7BqD8Tb3GhoQs_ZQ:-MZY1JR4Di6yO_7ps5vz:b-uy0cmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L391)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need this change to `advance` or track `atIntent` and expose `AtIntent()`.
I was imagining the caller would keep looking at `NumIntentErrors()` and as soon as it became > 0, break out of its "key collecting" mode and just use `NextKey` until `NumIntentErrors` crossed some upper bound (or the iterator was exhausted).

</blockquote></details>

There would be a side effect of sequential intents always being bundled together as next is always skipping to next valid value. But they could always be re-batched later so most likely ok.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUgo6x9iJkgAxEebUl:-MZY6c1CAkxu3OijzRAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L490)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... of intents encountered during ...
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUh4JqELJ4PLeW4e4H:-MZYAfSkA5CVjP_cudBA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L497)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nits:
- GetIntentError creates a write ...
- ... that can be used to resolve intents.
  (or perhaps you meant something else by "retry operations")

</blockquote></details>

Done.
___
*[pkg/storage/pebble.go, line 1761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV9C6d4k6XEN-ODo7c:-MZYAscq7UhF8utw6lar:bc5ki90) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/pebble.go#L1761)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

All the code in the loop is dealing with accumulating versions in `sstWriter` and size tracking, and the extra `skipData` mode is making it more complicated, and hard to see whether we are doing unnecessary work (e.g. we still seem to be calling `iter.Next` if `exportAllRevisions=true`, even though we don't need to if we are only accumulating intents).
 I think it would be cleaner to break out of that loop and add another loop that just uses `NextKey` to accumulate intents. And then we can more cleanly add a max count limit on intents.
</blockquote></details>

What do you think is the best way to configure max number of intents per error? I tried making it a server setting, it works for pebble and pebblero, but pebblesnapshot doesn't have any references to get those. I currently settled on just having a constant set to an arbitrary chosen constant.


<!-- Sent from Reviewable.io -->

2021-04-30 17:18 UTC, nvanbenschoten reviewed
> Reviewed 2 of 6 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYjGzIC5zMvnTVt0cN:-MZYjGzIC5zMvnTVt0cO:b-i8nacy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L29)):*
> ```Go
> )
> 
> func TestBackupPerformanceRegression(t *testing.T) {
> ```

Let's give this a more specific name, so that it's clear which part of "backup performance" this is related to. Right now, this could be 
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlc8w-uWtniJhJaDx:-MZYlc8w-uWtniJhJaDy:b-ijwg7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L42)):*
> ```Go
> 	// test data transactions. All other transaction commits pass though.
> 	interceptor := func(ctx context.Context, req roachpb.BatchRequest) *roachpb.Error {
> 		if req.Txn == nil || req.Txn.Name != "sql txn" {
> ```

Instead of trying to filter transactions using their name, which isn't particularly stable or targetted, can we explore doing something like https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/client_relocate_range_test.go#L391? Then we wouldn't need nearly as many conditions here.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYm7LR7x3PMqTSQ3UD:-MZYm7LR7x3PMqTSQ3UE:b-17aank) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L69)):*
> ```Go
> 		tx, err := sqlDb.Begin()
> 		require.NoError(t, err)
> 		ps, err := tx.Prepare("insert into foo (v) values ($1)")
> ```

This will be a lot faster to run if you batch these writes. Even if you're just writing 10 rows per statement, I'm guessing you'll see an improvement.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlObU2wd9Oj0X_w1f:-MZYlObU2wd9Oj0X_w1g:b-ocq9ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L76)):*
> ```Go
> 			i++
> 		}
> 		require.NoError(t, tx.Commit())
> ```

Did you look into whether this was causing pushers to need to recover STAGING transactions? Did we want to `tx.Rollback` here instead?
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYmLSc-3Pvt2DT7_jl:-MZYmLSd8U5wfHcTx2GN:b-7b4zaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L84)):*
> ```Go
> 	// Time to cleanup intents differs roughly 10x so some arbitrary number is picked which is 2x higher
> 	// than current backup time on current hardware.
> 	require.WithinDuration(t, timeutil.Now(), start, time.Second*10, "Time to make backup")
> ```

Let's pull this timeout into a constant so that it's clearer what to change if we ever need to re-tune this test.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUgo6x9iJkgAxEebUl:-MZYdSIV5gLxXfN9oLK2:b-qrol0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L490)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is `NumIntentErrors` the right name for this? There's only a single "intent error", but it can contain multiple intents. Maybe `NumIntentsEncountered`?
___
*[pkg/storage/mvcc_incremental_iterator.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUh4JqELJ4PLeW4e4H:-MZYe3qoCSTjQnPyFMLc:bwknfm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L497)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also, consider changing the name slightly to make it more clear that this can be called even when `NumIntentErrors() == 0`. Some alternatives would be `MaybeGetIntentError`, `TryGetIntentError`, or `CheckIntentError`.

Or maybe just return `i.intents` and let the caller construct the `WriteIntentError` if that seems like a cleaner interface to you.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYdlj6BWhC4F9WhNSr:-MZYdlj6BWhC4F9WhNSs:bboi39z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/mvcc_incremental_iterator.go#L474)):*
> ```Go
> // is not enabled, this function returns nil.
> func (i *MVCCIncrementalIterator) GetIntentError() error {
> 	if i.intents == nil {
> ```

nit: it shouldn't make a real difference, but `len(i.intents) == 0` does a slightly better job indicating the desire of this check. It is possible to have a non-nil, empty slice, even though that will never happen here, given the use of append.
___
*[pkg/storage/mvcc_incremental_iterator_test.go, line 271 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYetan5NxMI_PqnIvl:-MZYetan5NxMI_PqnIvm:bflujry) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/mvcc_incremental_iterator_test.go#L271)):*
> ```Go
> 		})
> 
> 		// Export will abort when intent is encountered, so we don't test export in those cases.
> ```

Isn't this what we are intending to fix? Should we be plumbing `expectedIntents` down to `assertExportedKVs` and checking that the `WriteIntentError` contains all expected intents?
___
*[pkg/storage/pebble.go, line 1709 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYfrMT4eymnN2cYLjv:-MZYfrMU6JEyuSSfenO9:bl3thau) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble.go#L1709)):*
> ```Go
> 		}
> 
> 		if iter.NumIntentErrors() > 0 {
> ```

Give this a comment referencing the collection loop below.
___
*[pkg/storage/pebble_test.go, line 547 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgRAXC3lnvEwsBTt-:-MZYgRAXC3lnvEwsBTt0:brykdg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L547)):*
> ```Go
> }
> 
> type TestValue struct {
> ```

Does this type need to be exported?
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgdMP8HjWMWQ3o-Q7:-MZYgdMP8HjWMWQ3o-Q8:bpbomf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
> ```Go
> }
> 
> func TestIntentFailureHandling(t *testing.T) {
> ```

@sumeerbhola is this the right place for this test? Should this go in `mvcc_incremental_iterator_test.go`?
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgg340cAPZueD4nVt:-MZYgg340cAPZueD4nVu:b5lwa2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
> ```Go
> }
> 
> func TestIntentFailureHandling(t *testing.T) {
> ```

This name seems a little broad to me. This is specifically testing the handling of intents with `ExportMVCCToSst`, right? So maybe `TestExportMVCCToSstIntentHandling`?
___
*[pkg/storage/pebble_test.go, line 590 a [...]

2021-05-03 14:59 UTC, sumeerbhola requested changes
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/mvcc_incremental_iterator.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZmbNLu-LGG5R56UUPt:-MZmbNLu-LGG5R56UUPu:b-dl6stu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5844f043aeae2fc15911cd57d08e473dbb10c281/pkg/storage/mvcc_incremental_iterator.go#L92)):*
> ```Go
> 	// Intent aggregation options.
> 	// Configuration passed in MVCCIncrementalIterOptions.
> 	collectIntents bool
> ```

can we call this `enableWriteIntentAggregation` -- easier to read if the name is the same as the one in the options.
___
*[pkg/storage/pebble.go, line 1761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV9C6d4k6XEN-ODo7c:-MZmbxbU1DsM9HK3dAGQ:b-q4xeac) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/pebble.go#L1761)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

What do you think is the best way to configure max number of intents per error? I tried making it a server setting, it works for pebble and pebblero, but pebblesnapshot doesn't have any references to get those. I currently settled on just having a constant set to an arbitrary chosen constant.
</blockquote></details>

I think @nvanbenschoten should comment on that -- I don't know how many unresolved intents have been encountered in the pathological examples we have observed in production. And there is the other concern of blowing up memory if we accumulate too many here.
It would be nice to have a cluster setting since we could dynamically adjust it in a cluster that is suffering from slow exports due to intents. It would be simple to add a `cluster.Settings` pointer to `pebbleSnapshot` and initialize it in `Pebble.NewSnapshot`.
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgdMP8HjWMWQ3o-Q7:-MZmiTp33tkHkYiSknva:b-d6jejq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@sumeerbhola is this the right place for this test? Should this go in `mvcc_incremental_iterator_test.go`?
</blockquote></details>

This is exercising both the changes to `pebbleExportToSst` and to `MVCCIncrementalIterator` so this is the right place.
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgg340cAPZueD4nVt:-MZmjHn22QFTIL6MwIL5:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This name seems a little broad to me. This is specifically testing the handling of intents with `ExportMVCCToSst`, right? So maybe `TestExportMVCCToSstIntentHandling`?
</blockquote></details>

+1
___
*[pkg/storage/pebble_test.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZmitm16oheesq_hVVT:-MZmitm16oheesq_hVVU:brwnaxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5844f043aeae2fc15911cd57d08e473dbb10c281/pkg/storage/pebble_test.go#L605)):*
> ```Go
> 
> 			_, _, _, err := engine.ExportMVCCToSst(key(10), key(10000), ts(999), ts(2000),
> 				true, 0, 0, true)
> ```

I think it would be good to exercise this with `exportAllRevisions`, `useTBI`  set to false too. Maybe randomize those values.


<!-- Sent from Reviewable.io -->

2021-05-03 19:18 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 1761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV9C6d4k6XEN-ODo7c:-MZneX7S1e323D9-qSl3:bgfk6db) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/pebble.go#L1761)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think @nvanbenschoten should comment on that -- I don't know how many unresolved intents have been encountered in the pathological examples we have observed in production. And there is the other concern of blowing up memory if we accumulate too many here.
It would be nice to have a cluster setting since we could dynamically adjust it in a cluster that is suffering from slow exports due to intents. It would be simple to add a `cluster.Settings` pointer to `pebbleSnapshot` and initialize it in `Pebble.NewSnapshot`.

</blockquote></details>

A cluster setting sounds like a good idea to me.

My intuition is that we should tune it to be some fraction of the maximum lock table size. Maybe half the size - 5000?


<!-- Sent from Reviewable.io -->

2021-05-04 10:23 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlc8w-uWtniJhJaDx:-MZqauvn3vVWhwBdJ9Xs:b-cfawyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of trying to filter transactions using their name, which isn't particularly stable or targetted, can we explore doing something like https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/client_relocate_range_test.go#L391? Then we wouldn't need nearly as many conditions here.
</blockquote></details>

Withut ctx keys working, I can only think of using lockspans to target inserted keys, but I'm not sure that would be easier as I need to build keys for particular table here and it still keeps all the assertions about request being end transaction and having lockspans in it.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlObU2wd9Oj0X_w1f:-MZd3uJt7sh1-iXjn9qE:b-om3l23) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you look into whether this was causing pushers to need to recover STAGING transactions? Did we want to `tx.Rollback` here instead?
</blockquote></details>

Oh weird! It must have pushed a wrong version after experimenting with commit/rollback behaviour differences.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 490 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUgo6x9iJkgAxEebUl:-MZdJEFo3eq9DUw0iEVH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L490)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `NumIntentErrors` the right name for this? There's only a single "intent error", but it can contain multiple intents. Maybe `NumIntentsEncountered`?
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZUh4JqELJ4PLeW4e4H:-MZdILuQDdu-8FqdYH6I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/mvcc_incremental_iterator.go#L497)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Also, consider changing the name slightly to make it more clear that this can be called even when `NumIntentErrors() == 0`. Some alternatives would be `MaybeGetIntentError`, `TryGetIntentError`, or `CheckIntentError`.

Or maybe just return `i.intents` and let the caller construct the `WriteIntentError` if that seems like a cleaner interface to you.
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZmbNLu-LGG5R56UUPt:-MZqbd6C4oaUM5hzaPCd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5844f043aeae2fc15911cd57d08e473dbb10c281/pkg/storage/mvcc_incremental_iterator.go#L92)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we call this `enableWriteIntentAggregation` -- easier to read if the name is the same as the one in the options.
</blockquote></details>

Done.
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgdMP8HjWMWQ3o-Q7:-MZ_6xu05tAZM6ixigs9:b-5le50b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@sumeerbhola is this the right place for this test? Should this go in `mvcc_incremental_iterator_test.go`?
</blockquote></details>

We have concrete tests for mvcc_iterator behavior separately, this one was written initially when recreation of iterator was inside export. There's still some logic in exportToSST so we better check that error doesn't fall through the cracks. I think maybe some of tests could be dropped and just a batch size test would be enough?
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYhgT71Er-sQg4mS5F:-MZqrEge0yATdZp-Ueig:boibsjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

After further consideration, I changed actual mvcc iterator test that has similar functionality. It is less readable imho, but I don't want to duplicate code. The only thing left here is intent batching which I would change after adding server config.
___
*[pkg/storage/pebble_test.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZmitm16oheesq_hVVT:-MZqrauPE27jhsNtT0i1:b-t4d0oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5844f043aeae2fc15911cd57d08e473dbb10c281/pkg/storage/pebble_test.go#L605)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it would be good to exercise this with `exportAllRevisions`, `useTBI`  set to false too. Maybe randomize those values.
</blockquote></details>

That would be covered in mvcciterator tests. This might just go away altogether then.


<!-- Sent from Reviewable.io -->

2021-05-04 10:39 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 1761 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZV9C6d4k6XEN-ODo7c:-MZqwYBl0TyEgFPw2csg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e34761417176a2c7c241b7162f8dfcebe301889a/pkg/storage/pebble.go#L1761)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A cluster setting sounds like a good idea to me.

My intuition is that we should tune it to be some fraction of the maximum lock table size. Maybe half the size - 5000?
</blockquote></details>

Done.
___
*[pkg/storage/pebble_test.go, line 590 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYgdMP8HjWMWQ3o-Q7:-MZqwfHuEb9cLVejjdK3:bwfkdf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/storage/pebble_test.go#L590)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

We have concrete tests for mvcc_iterator behavior separately, this one was written initially when recreation of iterator was inside export. There's still some logic in exportToSST so we better check that error doesn't fall through the cracks. I think maybe some of tests could be dropped and just a batch size test would be enough?
</blockquote></details>

I only kept batch test as it is relevant for server settings and overall operation. 
___
*[pkg/storage/pebble_test.go, line 605 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZmitm16oheesq_hVVT:-MZquDaB5LtKht2yEbfl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5844f043aeae2fc15911cd57d08e473dbb10c281/pkg/storage/pebble_test.go#L605)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

That would be covered in mvcciterator tests. This might just go away altogether then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 17:47 UTC, nvanbenschoten reviewed
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 42 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlc8w-uWtniJhJaDx:-MZsLisvE-E0LHkCUpID:ba6kuna) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L42)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Withut ctx keys working, I can only think of using lockspans to target inserted keys, but I'm not sure that would be easier as I need to build keys for particular table here and it still keeps all the assertions about request being end transaction and having lockspans in it.
</blockquote></details>

Ack. Thanks for looking into whether the `ctx` approach would work.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlObU2wd9Oj0X_w1f:-MZsLtCZ2I51SG_3YO0E:b-l13n1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L76)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Oh weird! It must have pushed a wrong version after experimenting with commit/rollback behaviour differences.
</blockquote></details>

I think this is still rejecting the EndTxn before the transaction is aborted, which means that the pushers need to wait for 5 seconds (`TxnLivenessThreshold`) before the transaction is considered abandoned and the pusher is allowed to begin resolving intents. Ideally, it would be allowed to clean up intents immediately.

One approach we could take is to have the interceptor clear the EndTxn's LockSpans, instead of rejecting it entirely. Something like:
```go
interceptor := func(ctx context.Context, req roachpb.BatchRequest) *roachpb.Error {
    et := req.Requests[0].GetEndTxn()
    if et != nil && !et.Commit && len(et.LockSpans) == transactionRowCount {
        // If this is a rollback of one the test's SQL transactions, allow the
        // EndTxn to proceed and mark the transaction record as ABORTED, but strip
        // the request of its lock spans so that no intents are recorded into the
        // transaction record or eagerly resolved. This is a bit of a hack, but it
        // mimics the behavior of an abandoned transaction which is aborted by a
        // pusher after expiring due to an absence of heartbeats.
        et.LockSpans = nil
    }
    return nil
}
```
Does that speed the test up at all?
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsRTFs4E3vzMJlEMhn:-MZsRTFs4E3vzMJlEMho:b-79bw33) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L84)):*
> ```Go
> 	// Time to cleanup intents differs roughly 10x so some arbitrary number is picked which is 2x higher
> 	// than current backup time on current hardware.
> 	require.WithinDuration(t, timeutil.Now(), start, time.Second*10, "Time to make backup")
> ```

Let's `t.Log` this duration as well. So maybe:
```go
after := timeutil.Now()
t.Logf("Backup took %s", after.Sub(start))
require.WithinDuration(t, after, start, time.Second*10, "Time to make backup")
```
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsLSl39qGO4SyUXtI0:-MZsLSl39qGO4SyUXtI1:b-z9ugh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/ccl/backupccl/backup_intents_test.go#L31)):*
> ```Go
> )
> 
> func rangeFromValue(from, size int) []interface{} {
> ```

nit: consider returning a `[]int` if that doesn't run into issues with `ps.Exec(rangeFromValue(i, statementRowCount)...)`.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsPqUv8dsnXEgRipg8:-MZsPqUv8dsnXEgRipg9:bx73ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/ccl/backupccl/backup_intents_test.go#L54)):*
> ```Go
> 	skip.UnderRace(t, "measures backup times not to regress, can't work under race")
> 
> 	// Time to cleanup intents differs roughly 10x so some arbitrary number is picked which is 2x higher
> ```

nit: rewrap this at 80 chars.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 56 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsRi2m8nM5aoP_WrFo:-MZsRi2m8nM5aoP_WrFp:b-kr0dhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/ccl/backupccl/backup_intents_test.go#L56)):*
> ```Go
> 	// Time to cleanup intents differs roughly 10x so some arbitrary number is picked which is 2x higher
> 	// than current backup time on current (laptop) hardware.
> 	const testTimeout = time.Second * 10
> ```

This is a timeout for the backup, not the entire test, right?
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsNGC20qnJD-NRc46X:-MZsNGC20qnJD-NRc46Y:b-p0ot8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/ccl/backupccl/backup_intents_test.go#L58)):*
> ```Go
> 	const testTimeout = time.Second * 10
> 
> 	const rowCount = 10000
> ```

nit: these variables are a little hard to understand. How about:
```go
const totalRowCount = 10000
const perTransactionRowCount = 1000
const perStatementRowCount = 100
```
___
*[pkg/storage/mvcc_incremental_iterator.go, line 470 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsSZLX3TfanLh7YOMl:-MZsSZLX3TfanLh7YOMm:b-erg6qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/mvcc_incremental_iterator.go#L470)):*
> ```Go
> }
> 
> // GetIntentError returns (roachpb.WriteIntentError, true) if intents were encountered
> ```

`(roachpb.WriteIntentError, true)` looks backwards from the method signature. But also, I think it's relatively idiomatic to keep what you had before and return just an `error` that callers can compare against `nil`
___
*[pkg/storage/pebble.go, line 50 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsT0zeCSvx8gQcYeDy:-MZsT0zf9zVsbZHX-QMy:bupy30y) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L50)):*
> ```Go
> const (
> 	maxSyncDurationFatalOnExceededDefault = true
> 	maxIntentsPerWriteIntentErrorDefault  = 5000
> ```

Let's give this some rationale.
___
*[pkg/storage/pebble.go, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsT4ntDcH8L5ubhGLh:-MZsT4ntDcH8L5ubhGLi:b-f4lvs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L73)):*
> ```Go
> )
> 
> var maxIntentsPerWriteIntentError = settings.RegisterIntSetting(
> ```

The name of this variable and the cluster setting itself needs some qualification. This isn't the maximum for all errors, just for those encountered by EXPORT, right?

Though this does bring up an interesting question. Should we have a maximum number of intents per WriteIntentError even for scans? We currently don't.
___
*[pkg/storage/pebble.go, line 1576 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsTU4n5BNhDqIBlMuX:-MZsTU4o9hi3ZwnqXl7_:b4h2n6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L1576)):*
> ```Go
> 	snapshot *pebble.Snapshot
> 	closed   bool
> 	settings *cluster.Settings
> ```

nit: move this up above `closed` so that dependencie [...]

2021-05-04 22:56 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlObU2wd9Oj0X_w1f:-MZtQNdm4XO5wQHzRw6f:bq7cxcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this is still rejecting the EndTxn before the transaction is aborted, which means that the pushers need to wait for 5 seconds (`TxnLivenessThreshold`) before the transaction is considered abandoned and the pusher is allowed to begin resolving intents. Ideally, it would be allowed to clean up intents immediately.

One approach we could take is to have the interceptor clear the EndTxn's LockSpans, instead of rejecting it entirely. Something like:
```go
interceptor := func(ctx context.Context, req roachpb.BatchRequest) *roachpb.Error {
    et := req.Requests[0].GetEndTxn()
    if et != nil && !et.Commit && len(et.LockSpans) == transactionRowCount {
        // If this is a rollback of one the test's SQL transactions, allow the
        // EndTxn to proceed and mark the transaction record as ABORTED, but strip
        // the request of its lock spans so that no intents are recorded into the
        // transaction record or eagerly resolved. This is a bit of a hack, but it
        // mimics the behavior of an abandoned transaction which is aborted by a
        // pusher after expiring due to an absence of heartbeats.
        et.LockSpans = nil
    }
    return nil
}
```
Does that speed the test up at all?
</blockquote></details>

I changed that and now time grows linearly to the same 6 sec for 10k rows. I found a  problem with test though, if I use prep statements and make transaction larger, spans are merged and it becomes impossible to distinguish test transactions from the rest. E.g. initial ddl statements become broken if filter touches them. So I ditched prep statements because the improvements in generation speed are small compared to resolve time.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 31 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsLSl39qGO4SyUXtI0:-MZt0o7P8pfPFtRDH8TU:b-ay9qn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/ccl/backupccl/backup_intents_test.go#L31)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider returning a `[]int` if that doesn't run into issues with `ps.Exec(rangeFromValue(i, statementRowCount)...)`.
</blockquote></details>

That is actually the reason why I had to resort to this ugliness. Exec accepts variadic parameters because they should match actual statement.
___
*[pkg/storage/mvcc_incremental_iterator.go, line 470 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsSZLX3TfanLh7YOMl:-MZtRJzo30gV74Zv95z1:bf1whkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/mvcc_incremental_iterator.go#L470)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`(roachpb.WriteIntentError, true)` looks backwards from the method signature. But also, I think it's relatively idiomatic to keep what you had before and return just an `error` that callers can compare against `nil`
</blockquote></details>

This is fair, but I'm not sure how to convince linter that this is not a standard case of having error as a second argument. I initially did what you are suggesting, but linter is one size fits all and fails the build.
___
*[pkg/storage/pebble.go, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsT4ntDcH8L5ubhGLh:-MZtWq6I79tTBxIMPtyh:bfsz6vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The name of this variable and the cluster setting itself needs some qualification. This isn't the maximum for all errors, just for those encountered by EXPORT, right?

Though this does bring up an interesting question. Should we have a maximum number of intents per WriteIntentError even for scans? We currently don't.
</blockquote></details>

Did we ever saw any problems with scan returning too many intents? Don't we try to keep some balance for backporting? If we want to limit scan, it may be a candidate for separate PR which we don't want to backport necessarily.


<!-- Sent from Reviewable.io -->

2021-05-05 20:02 UTC, nvanbenschoten reviewed
This is getting close!

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-:-MZy6qjs0QA1-vJLfTFs:bmawexq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 76 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZYlObU2wd9Oj0X_w1f:-MZy5kq27VBZ7J43uQpk:b-f9egil) ([raw file](https://github.com/cockroachdb/cockroach/blob/4394e7b8015c779cd9c7caa02345a099cf3207d9/pkg/ccl/backupccl/backup_intents_test.go#L76)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I changed that and now time grows linearly to the same 6 sec for 10k rows. I found a  problem with test though, if I use prep statements and make transaction larger, spans are merged and it becomes impossible to distinguish test transactions from the rest. E.g. initial ddl statements become broken if filter touches them. So I ditched prep statements because the improvements in generation speed are small compared to resolve time.
</blockquote></details>

Got it, that was a nice find.

Also, did we want to include the comment from the code snippet? Or adapt it somehow?
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 47 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZy4siqApmHZ1Uzj6GO:-MZy4siqApmHZ1Uzj6GP:b-o2xoz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/108ca3c306ea540d89444574b4181eccd4402365/pkg/ccl/backupccl/backup_intents_test.go#L47)):*
> ```Go
> 	// test data transactions. All other transaction commits pass though.
> 	interceptor := func(ctx context.Context, req roachpb.BatchRequest) *roachpb.Error {
> 		if req.Txn == nil || req.Txn.Name != "sql txn" {
> ```

I don't think we need this first condition.
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 51 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZy57h293LFvZVAcPgZ:-MZy57h293LFvZVAcPg_:b-kqke76) ([raw file](https://github.com/cockroachdb/cockroach/blob/108ca3c306ea540d89444574b4181eccd4402365/pkg/ccl/backupccl/backup_intents_test.go#L51)):*
> ```Go
> 		}
> 		endTxn := req.Requests[0].GetEndTxn()
> 		if endTxn != nil && !endTxn.Commit && len(endTxn.LockSpans) == perTransactionRowCount*2 {
> ```

Is the `*2` because of the secondary index? Why did we add that? Was it to force the transactions to be multi-range? If so, why was that needed when we're setting `LockSpans` to nil?
___
*[pkg/storage/mvcc_incremental_iterator.go, line 470 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsSZLX3TfanLh7YOMl:-MZy6XdPCUouy6-n0o4Y:bwev8ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/mvcc_incremental_iterator.go#L470)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

This is fair, but I'm not sure how to convince linter that this is not a standard case of having error as a second argument. I initially did what you are suggesting, but linter is one size fits all and fails the build.
</blockquote></details>

Could we just remove the `bool` return value entirely and compare against `nil` at the callers? From what I can tell, we don't even seem to look at the bool anywhere.
___
*[pkg/storage/pebble.go, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsT4ntDcH8L5ubhGLh:-MZy6DPd0UW_EHJ0qDdL:byyzjvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L73)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Did we ever saw any problems with scan returning too many intents? Don't we try to keep some balance for backporting? If we want to limit scan, it may be a candidate for separate PR which we don't want to backport necessarily.
</blockquote></details>

Sorry, to be clear, I wasn't suggesting that we do anything about this in this PR, just that we may consider opening an issue about this.


<!-- Sent from Reviewable.io -->

2021-05-05 21:41 UTC, aliher1911 commented
___
*[pkg/ccl/backupccl/backup_intents_test.go, line 51 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZy57h293LFvZVAcPgZ:-MZySbAR8oGze_wAV2gV:b-gxtt9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/108ca3c306ea540d89444574b4181eccd4402365/pkg/ccl/backupccl/backup_intents_test.go#L51)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the `*2` because of the secondary index? Why did we add that? Was it to force the transactions to be multi-range? If so, why was that needed when we're setting `LockSpans` to nil?
</blockquote></details>

What's happening with added index on v is that resolution time increases 3x for single intent resolutions while generation time stays the same. We must me exporting an index range and it requires as many resolutions as the main range. So it gives more headroom for the test to fail in case we make resolution so efficient that we will miss regression.
I think it makes sense to keep it, I can just add comment on why it is used this way.


<!-- Sent from Reviewable.io -->

2021-05-05 21:49 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 51 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZy57h293LFvZVAcPgZ:-MZyUIuD4NdToSnBz0m4:b-hm8xk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/108ca3c306ea540d89444574b4181eccd4402365/pkg/ccl/backupccl/backup_intents_test.go#L51)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

What's happening with added index on v is that resolution time increases 3x for single intent resolutions while generation time stays the same. We must me exporting an index range and it requires as many resolutions as the main range. So it gives more headroom for the test to fail in case we make resolution so efficient that we will miss regression.
I think it makes sense to keep it, I can just add comment on why it is used this way.
</blockquote></details>

I'm surprised that generation time was impacted less by a secondary index than by doubling the number of rows. My sense is that we should keep this part of the test as simple as possible to avoid extra moving parts that could break unless there's a strong reason to add them, but I'll defer to you.


<!-- Sent from Reviewable.io -->

2021-05-05 21:57 UTC, aliher1911 reviewed
Almost there. Just needs a couple of memes ;-D

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-:-MZyXDeq1TSXkTuT0yL-:b-3di28x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-MZsT4ntDcH8L5ubhGLh:-MZyVxaJ2YS7Sej-JNLD:bshsr19) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e0fabb1483c62655cded777db80425a8ece486/pkg/storage/pebble.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorry, to be clear, I wasn't suggesting that we do anything about this in this PR, just that we may consider opening an issue about this.
</blockquote></details>

I'll create one. Should be trivial to add I believe.


<!-- Sent from Reviewable.io -->

2021-05-05 22:01 UTC, nvanbenschoten commented
> Just needs a couple of memes ;-D

![unnamed](https://user-images.githubusercontent.com/5438456/117215208-e95bb580-adcb-11eb-9ea2-b14215477031.jpeg)

2021-05-05 22:08 UTC, nvanbenschoten commented
> Just needs a couple of memes ;-D

Exactly,

![unnamed](https://user-images.githubusercontent.com/5438456/117215673-90405180-adcc-11eb-9978-1f6bbb88a047.jpeg)

2021-05-06 15:24 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-:-M_1Gb9RBWTyNmTGBkxw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-M_1GPsf03YLvI6Xnuf7:-M_1GPsg5_DAHzcUPysG:bb6ht36) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0f42a9324f233a758c865292f57152bf16557e/pkg/ccl/backupccl/backup_intents_test.go#L1)):*
> ```Go
> // Copyright 2016 The Cockroach Authors.
> ```

2021


<!-- Sent from Reviewable.io -->

2021-05-06 16:17 UTC, aliher1911 commented
Created an issue for configurable intent count in scan: #64783

2021-05-06 17:40 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r6, 3 of 4 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-:-M_1l7to7xWaCgUsSWbd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @aliher1911, and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 38 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-M_1kvXn9LbdZq6KrGjM:-M_1kvXn9LbdZq6KrGjN:b-opiozz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05f1b3337dd40adc9e71616e9f4e483c1ef0261/pkg/ccl/backupccl/backup_intents_test.go#L38)):*
> ```Go
> 	// Time to create backup in presence of intents differs roughly 10x so some
> 	// arbitrary number is picked which is 2x higher than current backup time on
> 	// current (laptop) hardware.
> ```

(just curious) how long does the backup take for this test, without the batched intent resolution changes in this PR?


<!-- Sent from Reviewable.io -->

2021-05-06 18:13 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64131)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @sumeerbhola)

___
*[pkg/ccl/backupccl/backup_intents_test.go, line 38 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/64131#-M_1kvXn9LbdZq6KrGjM:-M_1s34j5nSHS-5iD8BF:brlc1kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b05f1b3337dd40adc9e71616e9f4e483c1ef0261/pkg/ccl/backupccl/backup_intents_test.go#L38)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(just curious) how long does the backup take for this test, without the batched intent resolution changes in this PR?
</blockquote></details>

1 minute without batching vs 7 sec. If i add an index so that each insert touches 2 ranges time bumps to 6 minutes.


<!-- Sent from Reviewable.io -->

2021-05-06 18:15 UTC, aliher1911 commented
bors r=sumeerbhola,nvanbenschoten

2021-05-06 19:50 UTC, merged