roachtest: update version map and fixtures
cockroachdb/cockroach pull request #64142
Opened 2021-04-23 16:53 UTC by alyshanjahani-crl

This commit adds the recently release 20.1.13 to the version map.
And generates test fixtures.

Release note: None

2021-04-23 16:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/64142)
<!-- Reviewable:end -->

2021-04-23 16:57 UTC, alyshanjahani-crl commented
bors r+

2021-04-23 21:34 UTC, pbardea commented
bors r-

2021-04-23 21:35 UTC, pbardea requested changes

2021-04-23 21:36 UTC, pbardea commented
Also nit: the commit message says that it updates the 20.1 fixtures, when the 20.2 fixtures are being updated.

2021-04-26 04:13 UTC, alyshanjahani-crl commented on pkg/cmd/roachtest/versionupgrade.go
> +	if true {
ah my bad, thx for catching that


> Also nit: the commit message says that it updates the 20.1 fixtures, when the 20.2 fixtures are being updated.

fixed, thx!

2021-04-27 15:31 UTC, alyshanjahani-crl commented
Having trouble getting past a flaky test 
```
------- Stdout: -------
=== RUN   TestChangefeedMonitoring/sinkless
    changefeed_test.go:1697: expected > 0 got 0
    --- FAIL: TestChangefeedMonitoring/sinkless (10.83s)
```

2021-04-28 14:47 UTC, alyshanjahani-crl commented
I'm getting a different test failure each time.
Is something up w/ master ? I've tried rebasing to get latest changes multiple times now.

@pbardea any suggestions?

2021-04-28 21:15 UTC, pbardea approved these changes
It looks like that changefeed test failure should be fixed by https://github.com/cockroachdb/cockroach/pull/64270. It looks like this PR isn't rebased on top of that change, giving it one more rebase off latest master should resolve that flake. You could also give it a chance at borsing since the failure is known.

Also as an aside, we typically push to a fork of the repo rather than create more branches in cockroachdb/cockroach and create a PR from the fork.

2021-04-29 21:24 UTC, alyshanjahani-crl commented
bors r+

2021-04-29 22:42 UTC, merged