c-deps/BUILD.bzl: handle cmake targets other than darwin,windows,linux
cockroachdb/cockroach pull request #64720
Opened 2021-05-05 14:20 UTC by knz

First commit from  #64709.

Fixes #64334.

Thanks to @rickystewart for suggesting the right approach.

The new foreign_cc builder has a restrictive view of what constitutes
a valid target:

```python
    if not generator:
        execution_os_name = os_name(ctx)
        if "win" in execution_os_name:
            generator = "Ninja"
        elif "macos" in execution_os_name:
            generator = "Unix Makefiles"
        elif "linux" in execution_os_name:
            generator = "Unix Makefiles"
        else:
            fail("No generator set and no default is known. Please set the cmake `generator` attribute")
```

This commit works around this code by spelling out the generator
explicitly.

2021-05-05 14:20 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/64720)
<!-- Reviewable:end -->

2021-05-05 14:36 UTC, knz commented
NB: the CI failure is from #64709, so fixing that there will fix it here too.

2021-05-05 14:36 UTC, rickystewart requested changes
Can't accept this as-is because it breaks the Bazel builds with the following error:

```
ERROR: While resolving toolchains for target //c-deps:libjemalloc: @platforms//os:windows is not a valid configuration key for @rules_foreign_cc//toolchains:built_make
```

I noticed this the first time I tried the `rules_foreign_cc` upgrade in CI, but haven't had time to investigate it.

The hypothesis that it only works with Bazel 4 is interesting, I can probably investigate that pretty easily.

2021-05-06 22:56 UTC, rickystewart approved these changes
Please rebase against `master` and make sure CI passes.

2021-05-07 09:25 UTC, knz commented
> Please rebase against master and make sure CI passes.

Done

thanks

bors r=rickystewart

2021-05-07 11:52 UTC, merged