sql: only include DML statement in service latency metrics
cockroachdb/cockroach pull request #64893
Opened 2021-05-07 20:09 UTC by Azhng

Previously, we only excluded Bulk IO operations from service latency
metric. However, other operations such as DDL or RangeFeed can also
cause latency spikes in our metrics chart.
We now only include DML statements in our service latency metric.

Addresses #64741

Release note (sql change): SQL Service Latency now only includes metrics
 from DML statements.

2021-05-07 20:23 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/executor_statement_metrics.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-M_7Tc-BBYviIbdneGMR:-M_7Tc-BBYviIbdneGMS:b3in4xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/18a25b43ccf6c72cc418a81422911f60457e401e/pkg/sql/executor_statement_metrics.go#L266)):*
> ```Go
> }
> 
> // We only want to keep track of DML queries in our latency metrics.
> ```

Add the meaning of DML, so `... of DML (Data Manipulation Language) ...`


<!-- Sent from Reviewable.io -->

2021-05-07 20:33 UTC, Azhng reviewed
Updated the PR to include UI change. I didn't realize the metrics chart is in the main repo instead of the cluster-ui repo. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-:-M_7XB4o6PSq0H4il4II:bphqbcd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/sql/executor_statement_metrics.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-M_7Tc-BBYviIbdneGMR:-M_7XA_eDnnPRo0syw9Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18a25b43ccf6c72cc418a81422911f60457e401e/pkg/sql/executor_statement_metrics.go#L266)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Add the meaning of DML, so `... of DML (Data Manipulation Language) ...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-10 13:24 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-M_LRPvl74KtVhpV99S_:-M_LRPvl74KtVhpV99Sa:b-t2xtno) ([raw file](https://github.com/cockroachdb/cockroach/blob/5def9249677e0bf077cbf9a060f5b005a834b241/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx#L76)):*
> ```XML
>           <em>
>             This time does not include network latency between the node and
>             client and includes SELECT, INSERT, UPDATE, and DELETE statements.
> ```

I think a change in the order of the phrase would sound better. E.g. `This time includes (only?) SELECT, INSERT, UPDATE and DELETE statements and does not include network latency between the node and client.`


<!-- Sent from Reviewable.io -->

2021-05-11 04:28 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-M_LRPvl74KtVhpV99S_:-M_OfjC31J_JX_DF0Kit:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5def9249677e0bf077cbf9a060f5b005a834b241/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx#L76)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think a change in the order of the phrase would sound better. E.g. `This time includes (only?) SELECT, INSERT, UPDATE and DELETE statements and does not include network latency between the node and client.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-11 13:12 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64893#-:-M_QYdt72JK2pDpvYi2e:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-05-11 15:52 UTC, merged