Auto-create docs issue when relevant PRs are merged
cockroachdb/cockroach pull request #65006
Opened 2021-05-11 15:49 UTC by yzdocs

Fixes #59546 

Related to #61946 (continuation of work started by @ianjevans)

Implement a GitHub Action that auto-creates an issue in the docs repo when a CRDB PR is merged, and that PR contains at least one commit with at least one valid release note that is not related to bug fix or performance.

Co-author: Ian Evans

Release note: none

2021-05-11 15:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65006)
<!-- Reviewable:end -->

2021-05-11 19:40 UTC, rickystewart requested changes
We do still need to get security's sign-off here.

2021-05-11 19:40 UTC, rickystewart commented on .github/workflows/doc-issues.yml
> +    runs-on: ubuntu-latest
Pinning to a specific version of the Docker image would be good too.

2021-05-11 20:37 UTC, rickystewart commented on .github/workflows/doc-issues.yml
> +                curl -X POST -H 'Authorization: token ${{ secrets.PAT }}' \
Let's give this a more descriptive name instead of `PAT`. Maybe `DEV_INF_GITHUB_PAT`?

2021-05-12 16:48 UTC, rickystewart commented on .github/workflows/doc-issues.yml
> +          command: |
Have you read https://securitylab.github.com/research/github-actions-untrusted-input/? I don't have a repro, but I don't have a great deal of confidence that this isn't vulnerable to any of the abuses described in that article. @yzdocs, can you provide a little clarity here? 

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ is also relevant, but I *think* we're okay from this perspective? I think if this action only runs when pull requests are closed, then GitHub's normal security measures (not passing secrets to actions triggered by pull requests) should probably be fine, although we should do our due diligence there too.

2021-05-12 18:11 UTC, aaron-crl reviewed
Iiuc this workflow can only be triggered when a merge to master is approved and merged and has appropriate doc info?

If that's the case, there is low likelihood for abuse here since it would require a CRL merge credential to action (and not just a public PR).

I think the use of environment variables mitigates the double command risks for the purposes of this flow but I'll acknowledge that GitHub action abuse is still a new exploit vector for me and only have moderate confidence in this assessment.

Very happy to see defense in depth regardless. Thanks for the ping @rickystewart !

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65006#-:-M_Wi64-3MuNFByTK_PN:b-xerjr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ianjevans, @otan, and @yzdocs)



<!-- Sent from Reviewable.io -->

2021-05-12 18:27 UTC, yzdocs commented
Thanks for reviewing, @aaron-crl! Confirming this is correct: "this workflow can only be triggered when a merge to master is approved and merged and has appropriate doc info"

2021-05-12 18:53 UTC, rickystewart approved these changes

2021-05-12 21:31 UTC, yzdocs commented
One more possibility (needs to be thought through and tested): 

Set up a GitHub Action in the *docs repo* instead of the CRDB repo, which will allow us to create issues in the docs repo. I believe (though not sure) we should be able to check out the CRDB repo from an Action within the docs repo. 

We could then set the Action to run once per day (or any other cadence) and grab CRDB pull requests based on `pull_request.merged_at` timestamps.

Just to repeat, this is all conceptual and untested for now.

2021-05-12 21:38 UTC, jseldess commented
Thanks for these updates, @yzdocs, and for the possible paths forward.

I don't think 1 is an option for us. I do think 2 is worth exploring more since we know both scripts more or less work, though even there, there are aspects to spec out. @yzdocs, let's sync up early next week on this.

2021-05-13 01:26 UTC, jlinder commented
There is another option:

- Create a build configuration in TeamCity that runs for every merge to the `master` and `release-*` branches that looks at all the PRs included in the merge and creates a docs ticket for each one.

Dev inf can help guide you on how to do this.

2021-05-24 13:45 UTC, closed without merging