backupccl: allow restoring into multi-region databases
cockroachdb/cockroach pull request #65015
Opened 2021-05-11 20:14 UTC by Elliebababa

Previously, restoring a non-multi-region table in to multi-region database is
not allowed.

This patch unblocks restoring non-multi-region table into multi-region
database and sets the table locality as regional by table to the primary
region of the target database.

Additionally, GLOBAL tables, REGIONAL BY TABLE IN PRIMARY REGION and
REGIONAL BY TABLE IN <region> tables are also supported given that the
<region> is compatible with the target database.

Resolves https://github.com/cockroachdb/cockroach/issues/59804.

Release note (enterprise change): RESTORE now supports restoring
individual tables into a multi-region database. If the table being
restored is also multi-region, REGIONAL BY ROW tables cannot be
restored, and REGIONAL BY TABLE tables can only be restored if their
localities match those of the database they're being restored into.

2021-05-11 20:14 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65015)
<!-- Reviewable:end -->

2021-05-13 14:12 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1iRl2o3VH2pCeeIn:-M_a1iRl2o3VH2pCeeIo:b-i2itl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/backupccl/restore_planning.go#L653)):*
> ```Go
> 				// https://github.com/cockroachdb/cockroach/issues/59804
> 				if parentDB.IsMultiRegion() {
> 					// currently, we allow restore non multi-region table.
> ```

nit: capitalization

I'm also curious if RESTORE returns an error or otherwise fails to do this if you change this to
```
if table.GetLocalityConfig() != nil { return pgerror.Newf... }
```

It looks like `WriteDescriptor` might handle this when IMPORT was updated to support this use case.
___
*[pkg/ccl/backupccl/restore_planning.go, line 658 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1PE280yzA-bLuOwz:-M_a1PE30mRbYmezxPod:b-3k3hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/backupccl/restore_planning.go#L658)):*
> ```Go
> 					} else {
> 						return pgerror.Newf(pgcode.FeatureNotSupported,
> 							"cannot restore an individual multi-region table %s into multi-region database %s",
> ```

nit: I prefer using `%q` here instead of `%s`. It would also be nice to log the table ID in parens afterwards since table names aren't necessarily unique.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup, line 1038 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1Xvg5ZRIHOhpIAih:-M_a1Xvg5ZRIHOhpIAii:blv2r7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L1038)):*
> ```
> 
> query TT
> SHOW ZONE CONFIGURATION FROM TABLE non_mr_table
> ```

Can we also run this command on the non_mr_table on the table that was backed up so that we can compare the zone configs before and after the restore?


<!-- Sent from Reviewable.io -->

2021-05-13 15:13 UTC, Elliebababa reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1iRl2o3VH2pCeeIn:-M_a7BDk08l45FyDwL4U:b-4x97l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/backupccl/restore_planning.go#L653)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: capitalization

I'm also curious if RESTORE returns an error or otherwise fails to do this if you change this to
```
if table.GetLocalityConfig() != nil { return pgerror.Newf... }
```

It looks like `WriteDescriptor` might handle this when IMPORT was updated to support this use case.
</blockquote></details>

Yea, it seems that they are compatible changes.. `WriteDescriptor` should be able to handle this. Updated it.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup, line 1038 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1Xvg5ZRIHOhpIAih:-M_aGrRl1DHNqg33obBz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L1038)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we also run this command on the non_mr_table on the table that was backed up so that we can compare the zone configs before and after the restore?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-13 17:37 UTC, pbardea approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_a1iRl2o3VH2pCeeIn:-M_amVie58YZEntFkKvn:b-185d7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/21a483af142b46605f06707539d35b4edcbc52d7/pkg/ccl/backupccl/restore_planning.go#L653)):*
<details><summary><i>Previously, Elliebababa wrote…</i></summary><blockquote>

Yea, it seems that they are compatible changes.. `WriteDescriptor` should be able to handle this. Updated it.
</blockquote></details>

Instead of this comment, can we update the comment above it? Let's mention that restoring multi-region tables to multi-region databases are disallowed since regions may mismatch.


<!-- Sent from Reviewable.io -->

2021-05-13 17:39 UTC, pbardea reviewed
Looks good to me, but want to get a look from someone from multi-region to give it a stamp to ensure that the MR semantics are what we expect, once the PR is out of `DRAFT`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-:-M_anpkvEx_iIL1GNkQ2:b8e09ug)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_antaWBiONyEp-EAq_:-M_antaWBiONyEp-EAqa:bxsz1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b8ce0399dacddd828d65a087066dd7d1a703f6/pkg/ccl/backupccl/restore_planning.go#L653)):*
> ```Go
> 				// https://github.com/cockroachdb/cockroach/issues/59804
> 				if parentDB.IsMultiRegion() {
> 					// Currently, we allow restore non multi-region table.
> ```

Instead of this comment can we update the one right above? Let's mention that restoring a multi-region table into a multi-region database is disallowed because the regions may not match.


<!-- Sent from Reviewable.io -->

2021-05-13 18:58 UTC, ajstorm requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_antaWBiONyEp-EAq_:-M_b21Bt976YlDLcCSaP:blv83ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b8ce0399dacddd828d65a087066dd7d1a703f6/pkg/ccl/backupccl/restore_planning.go#L653)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Instead of this comment can we update the one right above? Let's mention that restoring a multi-region table into a multi-region database is disallowed because the regions may not match.
</blockquote></details>

Is it possible to allow the restore of `GLOBAL` and `REGIONAL BY TABLE IN PRIMARY REGION` tables and just block `REGIONAL BY ROW` and `REGIONAL BY TABLE IN <region>`?  For bonus points, you could only block the latter after a region check determines that their regions aren't present in the target database.

Or were you planning on addressing this with a follow-on PR?
___
*[pkg/ccl/backupccl/restore_planning.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3Hp3139XF7B1YwGV:-M_b3Hp3139XF7B1YwGW:b-9s4vx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L648)):*
> ```Go
> 				// Long-term we'd want to modify the multi-region table so that it can exist in the
> 				// multi-region database that is compatible with its locality configs.
> 				// https://github.com/cockroachdb/cockroach/issues/59804
> ```

Should this be removed?  I think this is the issue you're addressing with this fix.
___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3lXT9wRj3eQ03ubI:-M_b3lXT9wRj3eQ03ubJ:bzibhp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L653)):*
> ```Go
> 					if table.GetLocalityConfig() != nil {
> 						return pgerror.Newf(pgcode.FeatureNotSupported,
> 							"cannot restore an individual multi-region table %q(%d) into multi-region database %q(%d)",
> ```

Nit: can we add a space between the database name and the id?
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup, line 1068 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b4E_a0TZCyPkFW6jw:-M_b4E_b5CdT_svKbFRW:b-rjx05k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L1068)):*
> ```
> # Verify that the zone configurations of non_mr_table that is restored to a multi-region database are set.
> query TT
> SHOW ZONE CONFIGURATION FROM TABLE non_mr_table
> ```

Can we also run a `SHOW CREATE TABLE` here to see the applied table locality more directly?


<!-- Sent from Reviewable.io -->

2021-05-13 19:28 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @Elliebababa, and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3Hp3139XF7B1YwGV:-M_bBQTp7Luqsi-mn1Nv:biynxqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L648)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Should this be removed?  I think this is the issue you're addressing with this fix.
</blockquote></details>

My reading was that this PR was narrowly tackling the non-MR table -> MR database case, and the issue was to be removed when we fully address other MR tables like you described below. (So yeah, slated for a follow on PR.)


<!-- Sent from Reviewable.io -->

2021-05-21 15:46 UTC, pbardea commented
Just a heads up that I'm going to take over this PR. Going to update the PR to handle restoring `GLOBAL` and `REGIONAL BY TABLES` as well. Will re-request review once those fixes are in.

2021-06-28 13:03 UTC, pbardea commented
This should be RFAL

2021-06-29 12:36 UTC, ajstorm requested changes
Looks great!  Thanks for continuing to persist on this one @elliebababa!

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-:-MdMlDp1Ew_P2W2LUkrp:b-un8hh2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @Elliebababa, and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3Hp3139XF7B1YwGV:-M_bbGXs5ba7o9G23AfM:bpv45sb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L648)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

My reading was that this PR was narrowly tackling the non-MR table -> MR database case, and the issue was to be removed when we fully address other MR tables like you described below. (So yeah, slated for a follow on PR.)
</blockquote></details>

Ahh, ok, in that case we're good.
___
*[pkg/ccl/backupccl/targets.go, line 618 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMgan0EPkpXFRY-pCp:-MdMgan0EPkpXFRY-pCq:b-584eyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L618)):*
> ```Go
> 
> // checkMultiRegionCompatible checks if the given table is compatible to be
> // restored into the given database according to their multi-region localities.
> ```

Nit: their -> its, localities -> locality
___
*[pkg/ccl/backupccl/targets.go, line 619 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMgiSm2NvM7OWrHcyC:-MdMgiSm2NvM7OWrHcyD:b-33vzzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L619)):*
> ```Go
> // checkMultiRegionCompatible checks if the given table is compatible to be
> // restored into the given database according to their multi-region localities.
> // It returns an error describing their incompatibility if not.
> ```

Nit: their -> the
___
*[pkg/ccl/backupccl/targets.go, line 628 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMh1mvD5hn2qeRnxea:-MdMh1mvD5hn2qeRnxeb:b-f5zcli) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L628)):*
> ```Go
> ) error {
> 	// If either the database or table are non-MR then allow it.
> 	if !(database.IsMultiRegion() && table.GetLocalityConfig() != nil) {
> ```

Extremely minor nit: The comment here and the code are slightly mismatched.  It might read better if the code is rewritten as:

```
if !database.IsMultiRegion() || table.GetLocalityConfig() == nil {
```
___
*[pkg/ccl/backupccl/targets.go, line 664 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMiPPc4cL6orBaO7a1:-MdMiPPc4cL6orBaO7a2:bw7hg3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L664)):*
> ```Go
> 
> 		return errors.Newf(
> 			"cannot restore REGIONAL BY TABLE %s (ID: %d) into database %q; locality %q not found in database localities %s",
> ```

"locality/localities" in this error message should be replaced with "region/regions".  We also might want to say `cannot restore REGIONAL BY TABLE %s IN REGION %q (ID: %d)...`
___
*[pkg/ccl/backupccl/targets.go, line 673 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMj71e2TToDhTTyAoe:-MdMj71e2TToDhTTyAof:b-luw03i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L673)):*
> ```Go
> 		)
> 	} else {
> 		return errors.Newf(
> ```

I'd think we should assert here, instead of just returning the error.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup, line 1154 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMjzi09_b-Jzi2Y9bo:-MdMjzi09_b-Jzi2Y9bp:b-wlttlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L1154)):*
> ```
>                    ) LOCALITY GLOBAL
> 
> # Restore individual tables into a database with different localities.
> ```

Nit: worth creating a new `subtest` here?  Something like:

`subtest restore_tables_into_database_with_different_regions`?


<!-- Sent from Reviewable.io -->

2021-06-29 12:36 UTC, ajstorm reviewed
Only a few minor things left.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-:-MdMlNcM40bWp3GYdYhs:bubd7v1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @Elliebababa, and @pbardea)



<!-- Sent from Reviewable.io -->

2021-06-30 20:00 UTC, pbardea reviewed
Thank you for the comments -- this should be RFAL

Just wanted to call out that I updated the PR to support handling all types of MR tables unless the regions were incompatible. Forgot to mention that in my previous comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-:-MdTVK2i4-RRjNwjZHcj:btpl9f1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_antaWBiONyEp-EAq_:-MdSo9eM5N7vo9pPC7gN:b-6cujnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b8ce0399dacddd828d65a087066dd7d1a703f6/pkg/ccl/backupccl/restore_planning.go#L653)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is it possible to allow the restore of `GLOBAL` and `REGIONAL BY TABLE IN PRIMARY REGION` tables and just block `REGIONAL BY ROW` and `REGIONAL BY TABLE IN <region>`?  For bonus points, you could only block the latter after a region check determines that their regions aren't present in the target database.

Or were you planning on addressing this with a follow-on PR?
</blockquote></details>

Updated to handle these cases (see other comment).
___
*[pkg/ccl/backupccl/restore_planning.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3Hp3139XF7B1YwGV:-MdSo-cf5ovbRTBAMnJg:b-thqn2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L648)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Ahh, ok, in that case we're good.
</blockquote></details>

When cleaning up this PR, I updated it to support restoring `GLOBAL`, `REGIONAL BY TABLE IN PRIMARY REGION` and `REGIONAL BY TABLE IN <region>` tables where the region is present in the target database. Removed the comment since this commit should resolve the linked issue.
___
*[pkg/ccl/backupccl/targets.go, line 618 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMgan0EPkpXFRY-pCp:-MdSngkq7w49TLn2G19V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L618)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: their -> its, localities -> locality
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 619 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMgiSm2NvM7OWrHcyC:-MdSnhkB5mHhp_hrUYXd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L619)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: their -> the
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 628 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMh1mvD5hn2qeRnxea:-MdSnjE7EDWgIUw4Tnz_:b-xiw2bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L628)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Extremely minor nit: The comment here and the code are slightly mismatched.  It might read better if the code is rewritten as:

```
if !database.IsMultiRegion() || table.GetLocalityConfig() == nil {
```
</blockquote></details>

Nice catch, done.
___
*[pkg/ccl/backupccl/targets.go, line 664 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMiPPc4cL6orBaO7a1:-MdTV64KAaENMMtvY_QR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L664)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

"locality/localities" in this error message should be replaced with "region/regions".  We also might want to say `cannot restore REGIONAL BY TABLE %s IN REGION %q (ID: %d)...`
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 673 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMj71e2TToDhTTyAoe:-MdSnqE315cq_6w4Uc0C:b5pzcrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L673)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'd think we should assert here, instead of just returning the error.
</blockquote></details>

I upgraded this to an assertion failure; I worry about `panic`ing here in case new MR configs are added without updating support for them in restore. I think we would want restore to return an error rather than panicing in that situation.
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup, line 1154 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMjzi09_b-Jzi2Y9bo:-MdSnyU42p1IQhUgPi6B:b-4sesko) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup#L1154)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: worth creating a new `subtest` here?  Something like:

`subtest restore_tables_into_database_with_different_regions`?
</blockquote></details>

Added a subtest here and above.


<!-- Sent from Reviewable.io -->

2021-07-05 13:51 UTC, ajstorm approved these changes
Looks fantastic!  Thanks for making multi-region whole on the restore side.  

Just nits left.

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-:-MdqvjED2rlX0pKpBUvt:bnw27f)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Elliebababa and @pbardea)

___
*[pkg/ccl/backupccl/restore_planning.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_antaWBiONyEp-EAq_:-MdquObd1rkpBYUErmrg:b9bkkp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b8ce0399dacddd828d65a087066dd7d1a703f6/pkg/ccl/backupccl/restore_planning.go#L653)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Updated to handle these cases (see other comment).
</blockquote></details>

Looks great!
___
*[pkg/ccl/backupccl/restore_planning.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-M_b3Hp3139XF7B1YwGV:-Mdqudo1CFEn7bweWQiT:bccpe8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/5772e2d15e0488b11e9dfce431b0a0742046a4a1/pkg/ccl/backupccl/restore_planning.go#L648)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

When cleaning up this PR, I updated it to support restoring `GLOBAL`, `REGIONAL BY TABLE IN PRIMARY REGION` and `REGIONAL BY TABLE IN <region>` tables where the region is present in the target database. Removed the comment since this commit should resolve the linked issue.
</blockquote></details>

Awesome.
___
*[pkg/ccl/backupccl/targets.go, line 673 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMj71e2TToDhTTyAoe:-MdqtJgsBieZZFQh1_Vq:bjdxdme) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L673)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I upgraded this to an assertion failure; I worry about `panic`ing here in case new MR configs are added without updating support for them in restore. I think we would want restore to return an error rather than panicing in that situation.
</blockquote></details>

Since this is your area of the code, I'll yield to your judgement here.  Just so you know though, we have assertions to catch bad locality configs throughout the multi-region code (create table, alter table, descriptor validation, etc).  It's fairly unlikely that we'd not catch this until restore.  More likely (I'd think) is that the descriptors get corrupted (somehow) during backup, and we try to restore something that's bad.  Either way though, and error is probably fine in that scenario as it would just indicate that the backup image is bad, and not the node.
___
*[pkg/ccl/backupccl/targets.go, line 636 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-Mdqs8AuE2GhQbseqwGk:-Mdqs8AuE2GhQbseqwGl:b-v1r9yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L636)):*
> ```Go
> 		// region.
> 		return nil
> 	} else if table.IsLocalityRegionalByTable() {
> ```

Nit: Since we're returning in the if branch above, this else isn't required.
___
*[pkg/ccl/backupccl/targets.go, line 668 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-Mdqt4Sd634wEldzFwf6:-Mdqt4Sd634wEldzFwf7:b-bcjhhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L668)):*
> ```Go
> 			database.GetName(), regionName, strings.Join(existingRegions, ", "),
> 		)
> 	} else if table.IsLocalityRegionalByRow() {
> ```

Nit: Same comment here about the `else`.
___
*[pkg/ccl/backupccl/targets.go, line 670 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdqupNB1Kzh1QB5rWy1:-MdqupNB1Kzh1QB5rWy2:bk0h4bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L670)):*
> ```Go
> 	} else if table.IsLocalityRegionalByRow() {
> 		return errors.Newf(
> 			"cannot restore REGIONAL BY ROW table %s (ID: %d) individually into a multi-region database %s",
> ```

Nit: Can we return `unimplemented.NewWithIssue` here, and open an issue for restoring `REGIONAL BY ROW` tables?  It'll be tricky to restore them (as we'll have to somehow validate the column values), but it might be something we investigate if there's enough user demand.


<!-- Sent from Reviewable.io -->

2021-07-06 18:18 UTC, pbardea reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65015)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/ccl/backupccl/targets.go, line 673 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdMj71e2TToDhTTyAoe:-MdwQSDg9-uQi6ZmxbMp:b-nus8qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a68a105869956658a8ef4f91121a1d764ba91956/pkg/ccl/backupccl/targets.go#L673)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Since this is your area of the code, I'll yield to your judgement here.  Just so you know though, we have assertions to catch bad locality configs throughout the multi-region code (create table, alter table, descriptor validation, etc).  It's fairly unlikely that we'd not catch this until restore.  More likely (I'd think) is that the descriptors get corrupted (somehow) during backup, and we try to restore something that's bad.  Either way though, and error is probably fine in that scenario as it would just indicate that the backup image is bad, and not the node.
</blockquote></details>

Ack. Will keep it as is for now, since it will fail the restore with a sufficiently descriptive error message, but can look into escalating this in a follow-up. I think we're more likely to introduce this by adding a new MR config on the SQL side and failing to account for it in RESTORE.
___
*[pkg/ccl/backupccl/targets.go, line 636 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-Mdqs8AuE2GhQbseqwGk:-MdwCFDj73d1E-EMBG5s:brg272b) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L636)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Since we're returning in the if branch above, this else isn't required.
</blockquote></details>

Updated throughout this method to reduce nesting.
___
*[pkg/ccl/backupccl/targets.go, line 668 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-Mdqt4Sd634wEldzFwf6:-MdwCLtODXiOLPVzNOXA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L668)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Same comment here about the `else`.
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/targets.go, line 670 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65015#-MdqupNB1Kzh1QB5rWy1:-MdwDxjTAKj93bRnqX5i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68015136e4754a592c08dd4d42d79e38875b6fa8/pkg/ccl/backupccl/targets.go#L670)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Can we return `unimplemented.NewWithIssue` here, and open an issue for restoring `REGIONAL BY ROW` tables?  It'll be tricky to restore them (as we'll have to somehow validate the column values), but it might be something we investigate if there's enough user demand.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-06 21:38 UTC, pbardea commented
TFTR!
bors r+

2021-07-06 22:48 UTC, merged