ui: rework data handling for the job details page
cockroachdb/cockroach pull request #65140
Opened 2021-05-13 16:49 UTC by oeph

Rework the data fetching for the job details page in the admin ui in order to
prevent cases, where the jo details page was stuck showing a loading indicator.

This was caused by the combined data handling of the job table and the details,
leading to loading issues if the job was not listed in the table and therefore
could not be shown in the detail page. (see #64281 for reproduction steps)

The job details page now uses a dedicated api endpoint to fetch the job details
for the given job_id.

Release note: None

Fixes #64281

2021-05-13 16:49 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65140)
<!-- Reviewable:end -->

2021-05-13 19:13 UTC, dhartunian commented
Thanks for your PR @oeph, appreciate you linking to the issue!
We'll get you a review over the next week.

2021-05-19 21:52 UTC, dhartunian requested changes
Nice work on this @oeph. Much appreciated.

You have some lint errors that I've pasted below from TeamCity, they can be hard to decipher from the output:
```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
14:56:00
    src/views/jobs/duration.tsx(19,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/jobDescriptionCell.tsx(14,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/jobDetails.tsx(122,31): error TS2322: Type 'string' is not assignable to type 'Long'.
14:56:00
    src/views/jobs/jobStatus.tsx(15,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/jobStatusCell.tsx(15,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/jobStatusOptions.ts(12,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/jobTable.tsx(24,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
14:56:00
    src/views/jobs/progressBar.tsx(13,40): error TS2724: '"/go/src/github.com/cockroachdb/cockroach/pkg/ui/ccl/src/js/protos".cockroach.server.serverpb' has no exported member named 'JobsResponse'. Did you mean 'IJobsResponse'?
```

You can run `make ui-lint` from the root project directory to reproduce this output.

> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-:-Ma-759j3OIQ4BYtgYR3:b-619a7l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @oeph)

___
*[pkg/server/admin.go, line 1786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-Ma5PZja34At7CAHpLkY:-Ma5PZja34At7CAHpLkZ:b-yuw01g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35593d61d412a4856ec1892562ec6ed216113c8/pkg/server/admin.go#L1786)):*
> ```Go
> 		row := it.Cur()
> 		var job serverpb.JobResponse
> 		scanErr := scanRowIntoJob(scanner, row, &job)
> ```

prefer `err` instead of `scanErr` here.  The use of `retErr` is a special case which is meant to differentiate the "postprocessing" of errors with the regular flow of the function but typically we prefer to just use `err` for all errors.
___
*[pkg/server/admin.go, line 1888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-Ma5_pNf2D6bLRIiWv3a:-Ma5_pNf2D6bLRIiWv3b:brzwbed) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35593d61d412a4856ec1892562ec6ed216113c8/pkg/server/admin.go#L1888)):*
> ```Go
> 
> 	var job serverpb.JobResponse
> 	scanErr := scanRowIntoJob(scanner, row, &job)
> ```

use `err` as suggested above
___
*[pkg/server/serverpb/admin.proto, line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-Ma5bGbHBYVrkS1r3-Oh:-Ma5bGbHBYVrkS1r3-Oi:b-eslrk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35593d61d412a4856ec1892562ec6ed216113c8/pkg/server/serverpb/admin.proto#L544)):*
> ```protobuf
> }
> 
> message JobRequest {
> ```

Add docstring for this payload
___
*[pkg/server/serverpb/admin.proto, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-Ma-6org3J6iwBB5HSAj:-Ma-6org3J6iwBB5HSAk:b-eslrk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35593d61d412a4856ec1892562ec6ed216113c8/pkg/server/serverpb/admin.proto#L548)):*
> ```protobuf
> }
> 
> message JobResponse {
> ```

Add docstring for this payload
___
*[pkg/server/serverpb/admin.proto, line 888 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-Ma-6u4B6aAmh3ksCApn:-Ma-6u4B6aAmh3ksCApo:b-ieulr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35593d61d412a4856ec1892562ec6ed216113c8/pkg/server/serverpb/admin.proto#L888)):*
> ```protobuf
>   }
> 
>   // Job returns the job records for all jobs of the given status and type.
> ```

Edit this comment to match new endpoint


<!-- Sent from Reviewable.io -->

2021-05-20 14:09 UTC, oeph commented
@dhartunian thank you for your comments - i will look into them!

2021-05-27 13:46 UTC, dhartunian approved these changes
Thanks for the second round of changes. LGTM but I'd like the team responsible for the jobs system to take a look as well prior to merge.

@nihalpednekar friendly ping, can you take a look at the server-side changes for the jobs output?

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-:-Mai38AR3GHhA4rfgd4D:b-omnt2x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nihalpednekar)



<!-- Sent from Reviewable.io -->

2021-05-28 03:20 UTC, nihalpednekar approved these changes
Server-side LGTM and thanks for the PR!

2021-05-28 03:20 UTC, nihalpednekar commented on pkg/server/admin.go
> +		return nil, err
It would be useful to add some context here, something like:
`return nil, errors.Wrapf(err, "expected to find 1 job with job_id=%d", request.JobId)`

2021-05-28 20:16 UTC, dhartunian reviewed
>  jo details page
nit: in commit message should be `job` details

once that's in, i'll merge. thx!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65140#-:-MaobKB9-TN2t-tWtXqz:b-lpx2i2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @oeph)



<!-- Sent from Reviewable.io -->

2021-05-29 07:00 UTC, oeph commented
@dhartunian good catch, i fixed the commit message

2021-05-31 14:58 UTC, nihalpednekar commented
bors r=dhartunian,nihalpednekar

2021-05-31 16:10 UTC, merged