sql: pg_sequences implemented on pg_catalog
cockroachdb/cockroach pull request #65420
Opened 2021-05-18 18:50 UTC by mnovelodou

Previously, pg_sequences was added for compatiblity but not implemented
This was inadequate because these tables return values in postgres
To address this, this patch implements pg_sequences

Release note (sql change): pg_sequences table was implemented on pg_catalog

2021-05-18 18:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65420)
<!-- Reviewable:end -->

2021-05-20 00:46 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 2904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DHMc0fl8HrPOnOXZ:-Ma6DHMd4wazmq6px8Zk:b-vm9f7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/pg_catalog.go#L2904)):*
> ```Go
> 				if sequenceValue != opts.Start-opts.Increment {
> 					// Before using for the first time, sequenceValue will be:
> 					// opts.Start - opts.Increment.
> ```

nit: comment should be above the if block
___
*[pkg/sql/pg_catalog.go, line 2911 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DwqyBfc5Vr7FQHYx:-Ma6DwqyBfc5Vr7FQHYy:b-h4bm5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/pg_catalog.go#L2911)):*
> ```Go
> 					tree.NewDString(scName),                 // schemaname
> 					tree.NewDString(table.GetName()),        // sequencename
> 					getOwnerName(table),                     // sequenceowner
> ```

Should this be the sequence owner which is on the sequence opts? Could you check against postgres? 

Also, if I'm correct, it would be worth adding a test which sets a sequence owner.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 3309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DR8205Nyvbc231aX:-Ma6DR8205Nyvbc231aY:b-13waxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/logictest/testdata/logic_test/pg_catalog#L3309)):*
> ```
> SELECT * FROM pg_seclabel
> 
> statement ok
> ```

Could you add a test that sets the CACHE option as well?


<!-- Sent from Reviewable.io -->

2021-05-20 19:05 UTC, mnovelodou reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65420)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 2904 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DHMc0fl8HrPOnOXZ:-MaA14s29epg1ws-EzAz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/pg_catalog.go#L2904)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: comment should be above the if block
</blockquote></details>

Done.
___
*[pkg/sql/pg_catalog.go, line 2911 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DwqyBfc5Vr7FQHYx:-MaA5ksh9x5cOy_hcbqW:b-49gete) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/pg_catalog.go#L2911)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be the sequence owner which is on the sequence opts? Could you check against postgres? 

Also, if I'm correct, it would be worth adding a test which sets a sequence owner.
</blockquote></details>

Nice catch!

I took a look at postgres and seems like there are 2 different things:
"OWNED BY" and "OWNER", You can ALTER SEQUENCE and change both values.
The first one (OWNED BY) refers to a table.column which in case the column or the entire table gets deleted, the sequence will get deleted as well. sequence opts owner refers to this table.column:

type TableDescriptor_SequenceOpts_SequenceOwner struct {
	// Sequence Owner's Column ID
	OwnerColumnID ColumnID `protobuf:"varint,1,opt,name=owner_column_id,json=ownerColumnId,casttype=ColumnID" json:"owner_column_id"`
	// Sequence Owner's Table ID
	OwnerTableID ID `protobuf:"varint,2,opt,name=owner_table_id,json=ownerTableId,casttype=ID" json:"owner_table_id"`
}

Owner refers to the username that owns the sequence. Which in this case is correct, but I will add a test case that will verify this.

Thank you for raising this up!
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 3309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DR8205Nyvbc231aX:-MaA9qaFDFGgEjKDHzrN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/logictest/testdata/logic_test/pg_catalog#L3309)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you add a test that sets the CACHE option as well?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 21:50 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-:-MaAk_dG4QjJSUpTb1ZJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @mnovelodou, and @rafiss)

___
*[pkg/sql/pg_catalog.go, line 2911 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65420#-Ma6DwqyBfc5Vr7FQHYx:-MaAkIaP0Q98YhktGYvy:btmkktm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e9e1b5abf6fcf60725075746baadf5470728/pkg/sql/pg_catalog.go#L2911)):*
<details><summary><i>Previously, mnovelodou (Miguel Novelo) wrote…</i></summary><blockquote>

Nice catch!

I took a look at postgres and seems like there are 2 different things:
"OWNED BY" and "OWNER", You can ALTER SEQUENCE and change both values.
The first one (OWNED BY) refers to a table.column which in case the column or the entire table gets deleted, the sequence will get deleted as well. sequence opts owner refers to this table.column:

type TableDescriptor_SequenceOpts_SequenceOwner struct {
	// Sequence Owner's Column ID
	OwnerColumnID ColumnID `protobuf:"varint,1,opt,name=owner_column_id,json=ownerColumnId,casttype=ColumnID" json:"owner_column_id"`
	// Sequence Owner's Table ID
	OwnerTableID ID `protobuf:"varint,2,opt,name=owner_table_id,json=ownerTableId,casttype=ID" json:"owner_table_id"`
}

Owner refers to the username that owns the sequence. Which in this case is correct, but I will add a test case that will verify this.

Thank you for raising this up!
</blockquote></details>

Thanks for confirming! 


<!-- Sent from Reviewable.io -->

2021-05-20 21:50 UTC, arulajmani commented
bors r+

2021-05-20 22:48 UTC, merged