storage: max number of intents in WriteIntentError during scan
cockroachdb/cockroach pull request #65465
Opened 2021-05-19 15:37 UTC by aliher1911

Previously consistent scan operation could return all encountered
intents from a range which could lead to process running out of memory.
This was the case when trying to cleanup built up intents by a high pri
query.

To address this, limit is added to the scan, to only return so much
intents before aborting.

This limit is controlled by cluster setting
storage.mvcc.max_intents_per_error which is replacing previously
available setting storage.sst_export.max_intents_per_error. New
setting will cover both scan and export commands.

Release note (ops change): Added limit to number of intents
collected by scan before aborting.

2021-05-19 15:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65465)
<!-- Reviewable:end -->

2021-05-19 15:47 UTC, aliher1911 commented
Some context.

Limit is added as env var as
a) we are not likely to change it much
b) currently mvcc doesn't have easy access to cluster config same way as sst export does. refactoring scanner to be a part of reader (similar to mvcciterator) could solve the problem, but that would be hard to backport to older versions.

2021-05-19 19:52 UTC, sumeerbhola reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @nvanbenschoten)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-Ma5AQ9g2r4w32mhgQCF:b-8kxgyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
> ```Go
> 			// that lie before the resume key.
> 			return false
> 		}
> ```

the code here looks peculiar. It is checking `p.results.count` but adding to `p.intents`, so it seems there isn't a limit on `p.intents.Count`.


<!-- Sent from Reviewable.io -->

2021-05-19 21:36 UTC, aliher1911 commented
___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-Ma5XyiKEhQ7MWphZgwo:bjosgjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

the code here looks peculiar. It is checking `p.results.count` but adding to `p.intents`, so it seems there isn't a limit on `p.intents.Count`.
</blockquote></details>

That's the reason I didn't apply limit to inconsistent scans. It should return resumespan which should be after last value key, but should have no intents. Not sure who expects it though as there are quite a lot of call sites ending up in the scan.
To make it work we need to rewind to last key once we hit intent limit or something.


<!-- Sent from Reviewable.io -->

2021-05-20 03:22 UTC, nvanbenschoten reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-Ma6kxasCNzSlvwjLZ7g:b-nfqvyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
> ```Go
> 	}())
> 
> // maxIntentsPerScanError is maximum number of intents returned in
> ```

Is there a reason to keep this separate from the `storage.sst_export.max_intents_per_error` cluster setting? I was imagining that we'd generalize that a little bit. For instance, rename it to `storage.mvcc.max_intents_per_error` and use it in both places.

If the concern is that we don't want to plumb cluster settings down here then we could explore plumbing it through the `MVCCScanOptions`.
___
*[pkg/storage/mvcc_test.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6lZwC6JmCcxqrC7mX:-Ma6lZwC6JmCcxqrC7mY:bye10e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L670)):*
> ```Go
> 
> 			// Limit number of intents per error in consistent scan.
> 			maxIntentsPerScanError = 2
> ```

Setting a global variable like this in a test is an anti-pattern. The effect is that any test that runs after this one in this package will now see the new value, which is not desirable.
___
*[pkg/storage/mvcc_test.go, line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6mU303zkQiIeEXcbI:-Ma6mU303zkQiIeEXcbJ:b-f1269s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L696)):*
> ```Go
> 					expIntents: []roachpb.Intent{
> 						roachpb.MakeIntent(&txn2ts.TxnMeta, testKey4),
> 						roachpb.MakeIntent(&txn2ts.TxnMeta, testKey5),
> ```

Is this test case hitting the limit? Wouldn't we want to make txn2 write 3 intents and show that only two are returned?
___
*[pkg/storage/mvcc_test.go, line 710 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6lyVj4M7hEXGPtwr0:-Ma6lyVj4M7hEXGPtwr1:bf53tw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L710)):*
> ```Go
> 				},
> 				{
> 					name:       "inconsistent--all-keys",
> ```

nit: extra `-`?
___
*[pkg/storage/mvcc_test.go, line 734 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6m5Ss8aF1B-D5QiEh:-Ma6m5Ss8aF1B-D5QiEi:b-v8owp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L734)):*
> ```Go
> 					if wiErr == nil != !scan.consistent {
> 						t.Errorf("expected write intent error; got %s", err)
> 						return
> ```

Now that you're using a subtest, you can change the `t.Errorf` to `t.Fatalf` and you won't have to worry about returning.


<!-- Sent from Reviewable.io -->

2021-05-20 09:16 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-Ma7yjIO11d_M2Srd0-2:b-5543u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to keep this separate from the `storage.sst_export.max_intents_per_error` cluster setting? I was imagining that we'd generalize that a little bit. For instance, rename it to `storage.mvcc.max_intents_per_error` and use it in both places.

If the concern is that we don't want to plumb cluster settings down here then we could explore plumbing it through the `MVCCScanOptions`.
</blockquote></details>

I totally agree with this approach to reuse the same cluster setting and maybe rename it to reflect its broader use. MVCCScanOptions are created in multiple call sites:

pkg/kv/kvserver/replica_raftstorage.go:242:
pkg/kv/kvserver/store.go:1338:
pkg/kv/kvserver/abortspan/abortspan.go:107:
pkg/kv/kvserver/batcheval/cmd_reverse_scan.go:42:
pkg/kv/kvserver/batcheval/cmd_refresh_range.go:62:
pkg/kv/kvserver/batcheval/cmd_scan.go:42:
pkg/kv/kvserver/gc/gc.go:500:
pkg/kv/kvserver/gc_queue_test.go:898:
pkg/cli/debug.go:704:
pkg/cli/debug_check_store.go:241:
pkg/storage/metamorphic/operations.go:366:
pkg/storage/mvcc.go:2326:
pkg/storage/mvcc.go:2618:

and i don't think most of them has immediate access to settings either. They already operate on storage.Reader at that point.
Second thing that I don't like about putting that to options is that this is a safety feature and it should work regardless of scan request options because it is easy to misuse otherwise and pushes burden on the scan user.
Imho to make it proper we could do something similar to what was done with mvcc iterator. Make it specific to underlying storage (it is already is because it is even called pebbleMVCCScanner) and obtain it from reader same way as mvcciterator. In that case we can reuse option and let storage control this in uniform way.
But that would make it hard to backport to 20.2 where it is needed because of rocksdb storage and different code there.
Maybe the right way is to have an env in 20.2 and make it different 21.1 and on with scanner being part of reader contract?
___
*[pkg/storage/mvcc_test.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6lZwC6JmCcxqrC7mX:-Ma7ySoK1e6aQ8eRVrRv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L670)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Setting a global variable like this in a test is an anti-pattern. The effect is that any test that runs after this one in this package will now see the new value, which is not desirable.
</blockquote></details>

Done.
___
*[pkg/storage/mvcc_test.go, line 696 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6mU303zkQiIeEXcbI:-Ma7xym63f3K1mdIiis4:b-2srem5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L696)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this test case hitting the limit? Wouldn't we want to make txn2 write 3 intents and show that only two are returned?
</blockquote></details>

This particular one was not. Added another transaction to the mix.
Done.
___
*[pkg/storage/mvcc_test.go, line 710 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6lyVj4M7hEXGPtwr0:-Ma7yNWF1Io9sKV8vprU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc_test.go#L710)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: extra `-`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 15:08 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-Ma99gzrCFpkwZVtObu2:b-z91y0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

That's the reason I didn't apply limit to inconsistent scans. It should return resumespan which should be after last value key, but should have no intents. Not sure who expects it though as there are quite a lot of call sites ending up in the scan.
To make it work we need to rewind to last key once we hit intent limit or something.
</blockquote></details>

Yes, the "intents should only correspond to KVs that lie before the resume key" seems to tie our hands. Can you add a TODO here that this means that if we see a value, followed by N intents, where N >> maxIntents, we have to keep adding those intents until we see the next value, and this could cause OOMs. We should remember to fix this. I don't know how widespread a change will be needed to fix this since I don't know what semantics we desire from inconsistent scans. Looking at the code here, it seems that if we find an intent for a key, we also want to add a value (if one exists for that key) below that intent. So if all we need is completeness in terms of a resume key representing that all intents and values before that key (for forward scans) have been included, we could fix the enforcement logic locally and that would be sufficient (@nvanbenschoten for clarification).  

And looking more closely, I'm not sure this "now we're adding the resume key" comment is correct. If I am reading correctly, the only place where we do `maxKeys` enforcement is in `addAndAdvance` and in all those cases we immediately unwind out of `getAndAdvance` up to the top-level of `scan` which is calling `getAndAdvance` in a loop. Once the `maxKeys` is reached, that loop terminates and we use `advanceKey` to find the resume key, not `getAndAdvance`, where `advanceKey` doesn't care whether something is an intent or not (it just wants the `roachpb.Key`, and not the timestamp part).

So one relatively clean solution for `maxKeys` and `maxIntents` enforcement for inconsistent scan could be: look at `maxIntents` in the code here, and if exceeded, call `seekVersion` as we do below, but regardless of what value that `seekVersion` returns, return false from `getAndAdvance`. This should work since `seekVersion` will either add a value, or there is no value to add. Either way, we have a safe stopping point.

If I am incorrect of the desired semantics a less complete fix would be: in `addAndAdvance` after adding a value, if `maxIntents` has been exceeded, return false. This is because a value addition is always a safe stopping point before we generate the resume span using `advanceKey`.


<!-- Sent from Reviewable.io -->

2021-05-20 21:41 UTC, nvanbenschoten reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-MaAbjcO6zvY1ssdVOY4:b-syg47h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
@sumeerbhola do you have thoughts about this? Making this specific to the underlying storage feels strange to me, as does using the `storage.Reader` to access cluster settings. How much context do we expect these storage-level interfaces to have? Would we want to expose a `Settings` method on `storage.Reader/Writer`?

> it is already is because it is even called pebbleMVCCScanner

Despite the name, `pebbleMVCCScanner` is actually not a specific pebble implementation. It operates on the `MVCCIterator` interface.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-MaAfmIC7AdUYMSQRSzv:b-5du7vj) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
This analysis (`And looking more closely, ...`) and the proposed solution (`So one relatively clean solution ...`) all appear correct to me.

Although,

> This should work since seekVersion will either add a value, or there is no value to add.

If there is no value to add at this key, this will mean that the iterator will be positioned at the next key, right? So then will the call to `advanceKey` outside of the `getAndAdvance` loop iterate again and skip over the next key?

> That's the reason I didn't apply limit to inconsistent scans.

I don't think the maxIntents limit should be applied to inconsistent scans. Such scans treat intents similar to committed values and don't return WriteIntentErrors. So if anything, we should apply the maxKeys limit to inconsistent scans.


<!-- Sent from Reviewable.io -->

2021-05-26 11:20 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-MabtIij0OUUDXdKlDaq:b-nxkd28) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@sumeerbhola do you have thoughts about this? Making this specific to the underlying storage feels strange to me, as does using the `storage.Reader` to access cluster settings. How much context do we expect these storage-level interfaces to have? Would we want to expose a `Settings` method on `storage.Reader/Writer`?

> it is already is because it is even called pebbleMVCCScanner

Despite the name, `pebbleMVCCScanner` is actually not a specific pebble implementation. It operates on the `MVCCIterator` interface.
</blockquote></details>

Who do you think should be responsible for enforcing the limit in general?
It is either command or the underlying resource in my understanding. We have multiple call sites/code paths that end up in scan. Should they be responsible for pushing the limit here? In that case we should push that up the the request itself and propagate through options down. Alternatively if it is resources responsibility to maintain system health then they should set those limits.
I think it is latter is better because having commands that can break system if they forgot to set limits is bad.
As for the option itself, currently commands operate on reader using request data once they pass down the replica_evaluate and they don't have access to replica or other server components that has notion of configs.
For export command I used information in pebble since export is a method on reader itself and it has all the config references, but scan is better abstracted and it only relies on iterator on reader to do the scan.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-MacOHIBDu9-npVJRp6L:bw9u6nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This analysis (`And looking more closely, ...`) and the proposed solution (`So one relatively clean solution ...`) all appear correct to me.

Although,

> This should work since seekVersion will either add a value, or there is no value to add.

If there is no value to add at this key, this will mean that the iterator will be positioned at the next key, right? So then will the call to `advanceKey` outside of the `getAndAdvance` loop iterate again and skip over the next key?

> That's the reason I didn't apply limit to inconsistent scans.

I don't think the maxIntents limit should be applied to inconsistent scans. Such scans treat intents similar to committed values and don't return WriteIntentErrors. So if anything, we should apply the maxKeys limit to inconsistent scans.
</blockquote></details>

If we apply maxKeys, I assume we want to count results and intents together for that purpose. That would make more sense to me as it is even called keys not max values.


<!-- Sent from Reviewable.io -->

2021-05-26 12:13 UTC, aliher1911 commented
___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-MacYc9d4UeDtzOFhYoR:b-d2ch5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

If we apply maxKeys, I assume we want to count results and intents together for that purpose. That would make more sense to me as it is even called keys not max values.
</blockquote></details>

What is confusing to me in this check is how could we get even get here with this check failing.  getAndAdvance would always return values with addAndAdvance which will perform this check and make getAndAdvance return false and break the scan loop. So we would not get here with those checks passing as true. But I'm sure there's some corner case here which I don't see.


<!-- Sent from Reviewable.io -->

2021-05-26 12:19 UTC, aliher1911 commented
___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-MacbAVb5EsSPCvCx2-q:b8v9hnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

What is confusing to me in this check is how could we get even get here with this check failing.  getAndAdvance would always return values with addAndAdvance which will perform this check and make getAndAdvance return false and break the scan loop. So we would not get here with those checks passing as true. But I'm sure there's some corner case here which I don't see.
</blockquote></details>

Now that i traced thing myself I see what Sumeer is talking about the same thing. :dagger: 


<!-- Sent from Reviewable.io -->

2021-05-27 13:04 UTC, aliher1911 reviewed
I changed the way intent limits are calculated for inconsistent mode. Looking on what we do we iterate certain number of keys and return them regardless if they are values or intents so that we can resolve them before resuming. In that case it doesn't make much sense to count them separately, we only want to count keys and stop once we find desired number of keys among intents and keys.
That would prevent cases where we could collect lots of intents where we don't have a value in the middle and respect the limits that caller set.

The question with how to provide configuration (if at all) for WriteIntentError's is still open. I don't think there's currently an easy way, but do we really need to configure this value? Maybe current "hardcoded" approach would cut it with emergency override vie env?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-Mahu636AYZFrAJPBWcS:b40xrxu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 453 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma5AQ9g2r4w32mhgQCE:-Mah_pJU1dndNPalw-CD:b-nneoa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/760f3bb6ef549b46cf97ff1aa51af31fac792808/pkg/storage/pebble_mvcc_scanner.go#L453)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Now that i traced thing myself I see what Sumeer is talking about the same thing. :dagger: 
</blockquote></details>

So I tried a couple of things and that's the result so far.
So simple solution was not enough because of how logic to set the resume span interacts with seekVersion. Seek version would always push to next key if it can't find value. If it can find value it would stay on the same key if we reached limits or it advances if it doesn't.
I decided that should be explicit then, if we stop at intent then we don't advance second time and just check that underlying iterator is valid. That should cover both cases.


<!-- Sent from Reviewable.io -->

2021-05-27 16:07 UTC, nvanbenschoten reviewed
The approach here looks good. However, I am starting to think that we should split out the pagination of intents in a WriteIntentError from the pagination of intents during an inconsistent scan. These are largely different concerns, and there's a good reason not to combine them into a single PR. To start, the latter change here is making this PR significantly more complex, to the point where we would not feel comfortable backporting this. The code here around counting keys and tracking where the iterator is pointed is just too subtle, and we've seen bugs in this area in the past. We'll also want to check that the latter change is needed (does anyone issue inconsistent scans with limits?) and, if so, that these users are properly written to handle pagination. Finally, I think there's still some uncertainty about the exact semantics we want key limits applied to inconsistent scans to have. Right now, each distinct key that has either a value, an intent, or both, is counted against the limit. There are good reasons for that from an implementation perspective, but do we know that this is what callers want? If I'm issuing an inconsistent scan, am I applying a limit to bound the memory size of the result set, or am I applying a limit to bound the span of keys scanned to N committed values (plus any intents I see along the way)? I don't know the answer to that question, but I could see callers wanting both. So we should understand how this is being used today.

For all of these reasons, I think we'd be better served splitting up the changes.

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-MaiWxxtABZcLlACBuNj:b-eh9q0q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-MaiZAV20ljSBpPnaUhN:b20wm4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
> I think it is latter is better because having commands that can break system if they forgot to set limits is bad.

On the other hand, if a request did not set a key limit and scanned over a keyspace with 10 million committed keys, it would also cause issues. So I don't know that this logic holds in all cases.

> As for the option itself, currently commands operate on reader using request data once they pass down the replica_evaluate and they don't have access to replica or other server components that has notion of configs.

Commands have access to the replica and the settings through the `CommandArgs.EvalContext`.
___
*[pkg/storage/mvcc_test.go, line 1461 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiTtC98X0eugOhgMaY:-MaiTtC98X0eugOhgMaZ:bxgpy5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/mvcc_test.go#L1461)):*
> ```Go
> }
> 
> func TestMVCCScanInconsistentLimits(t *testing.T) {
> ```

Let's give this a comment.
___
*[pkg/storage/mvcc_test.go, line 1473 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiTveuBOkvClhyodaF:-MaiTveuBOkvClhyodaG:bhv53ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/mvcc_test.go#L1473)):*
> ```Go
> 			ts1 := hlc.Timestamp{WallTime: 1}
> 			ts2 := hlc.Timestamp{WallTime: 2}
> 			//ts3 := hlc.Timestamp{WallTime: 3}
> ```

nit: remove the unused vars.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 118 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiVb6u9PP_cvKobOaI:-MaiVb6v5hrc0jyxYYQr:b-lgr5uw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/pebble_mvcc_scanner.go#L118)):*
> ```Go
> 	targetBytes int64
> 	// Stop adding intents and abort scan once maxIntents threshold is reached.
> 	// Ignored if zero or if doing inconsistent scan.
> ```

Mention why it is ignored if doing an inconsistent scan. Something about how the `maxKeys` limit also applies to intent in that case.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 156 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiUuqZClkUkKF0xUU_:-MaiUuqZClkUkKF0xUUa:b-1ds7kj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/pebble_mvcc_scanner.go#L156)):*
> ```Go
> 	// [1, maxItersBeforeSeek] and defaults to maxItersBeforeSeek/2 .
> 	itersBeforeSeek int
> 	// Number of keys collected as values and intents in inconsistent mode.
> ```

s/and intents in inconsistent mode/or intents (if in inconsistent mode)/
___
*[pkg/storage/pebble_mvcc_scanner.go, line 158 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiUlDUESJpA2D3BMbk:-MaiUlDUESJpA2D3BMbl:b7kssod) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/pebble_mvcc_scanner.go#L158)):*
> ```Go
> 	// Number of keys collected as values and intents in inconsistent mode.
> 	// This is different from number of results plus number of intents as we could
> 	// have intent without value and value without intent as well as both.
> ```

"have intent without a value, value without an intent, or keys with both"
___
*[pkg/storage/pebble_mvcc_scanner.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiVDoq0fqSLhOKqSz1:-MaiVDoq0fqSLhOKqSz2:b-4cn7nt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/pebble_mvcc_scanner.go#L160)):*
> ```Go
> 	// have intent without value and value without intent as well as both.
> 	collectedKeys int64
> 	// This flag indicates that last iteration collected only intent, but not
> ```

s/intent/an intent/ throughout.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-MaiVJPB-586ChSnpfBY:-MaiVJPB-586ChSnpfBZ:b-bjw5vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ece185b3629e16cadc1c4dac0476df717f2ede1/pkg/storage/pebble_mvcc_scanner.go#L162)):*
> ```Go
> 	// This flag indicates that last iteration collected only intent, but not
> 	// a preceding value for it. It is set whenever intent is discovered and reset
> 	// back if corresponding value is present. It is used to calculate number of
> ```

s/number/the number/


<!-- Sent from Reviewable.io -->

2021-05-27 17:13 UTC, aliher1911 reviewed
I think the second part didn't work out. Some tests failed and they seem to rely on particular behaviour like if you scan hits intent then it expects to get a subsequent key as a result if it is under limit, so the whole idea that maxkeys could just limit what we return seem flawed. I think scanner behaviour is defined vaguely, so let's not touch it then and limit it to writeintenterror.
Let me revert all the parts that are not relevant to that and I'll push option to config via context.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-MaimT7n2Jv5L6f55hIb:bhiw2i6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-05-27 17:57 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-Maiusx99m4nPSK2o0sK:b-kxtg8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I think it is latter is better because having commands that can break system if they forgot to set limits is bad.

On the other hand, if a request did not set a key limit and scanned over a keyspace with 10 million committed keys, it would also cause issues. So I don't know that this logic holds in all cases.

> As for the option itself, currently commands operate on reader using request data once they pass down the replica_evaluate and they don't have access to replica or other server components that has notion of configs.

Commands have access to the replica and the settings through the `CommandArgs.EvalContext`.
</blockquote></details>
 
Changed to use shared cluster setting.

<!-- Sent from Reviewable.io -->

2021-05-28 14:04 UTC, sumeerbhola requested changes
looks good. A few minor comments.

> Reviewed 4 of 5 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-ManHRr78k3A6K5B_i0g:bj6gf48)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Ma6kxasCNzSlvwjLZ7f:-Man9mA117vf4zzlLYnE:bw2s4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ec07a938fd3534c44060069ad382831a496c870/pkg/storage/mvcc.go#L83)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Unfortunately 
</blockquote></details>

I missed the earlier ping. It seems there are arguments for both ways.
Given this case is one where we are returning an error, and this is just limiting the size of the error, it sounds like a reasonable choice to have it here. Things with resume spans are different -- the caller has to understand the partial result semantics, unlike this error case where the incompleteness of the intent list is irrelevant to the caller.
___
*[pkg/storage/mvcc.go, line 2529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManBQr-0gjw8VT9biHi:-ManBQr-0gjw8VT9biHj:b8nwf74) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/mvcc.go#L2529)):*
> ```Go
> 	// consistent mode. Scanning will stop without reaching MaxKeys if this
> 	// threshold is reached.
> 	// For inconsistent scans number of intents is limited by number of keys
> ```

Is this comment about inconsistent scans still relevant, given the discussion about not making any change to it in this PR?
___
*[pkg/storage/pebble.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManC1oJ-GgL-ravRfjn:-ManC1oJ-GgL-ravRfjo:b-sswbw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eeb35f3ea834228cd724f2a0e01c27b75bb6dd5/pkg/storage/pebble.go#L81)):*
> ```Go
> 	"storage.sst_export.max_intents_per_error",
> 	"maximum number of intents returned in error when sst export fails",
> 	maxIntentsPerSstExportErrorDefault)
> ```

what's our story with changing names of settings? Was the PR that introduced this backported to various versions? Is this fine since this was not public? I've seen warnings in logs before when playing around with settings names in PRs, so I wonder if this change could worry users who see unnecessary warnings.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManFN14ARIwSyhc7E15:-ManFN14ARIwSyhc7E16:btj00mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/pebble_mvcc_scanner.go#L122)):*
> ```
> 	// intents as an error. For inconsistent scans number of intents is limited
> 	// by number of keys scan requests and clients should rely on pagination
> 	// to sensibly process large ranges.
> ```

I find the "For inconsistent scans ..." phrasing confusing. There is no limit on intents there. Whatever limit happens is just a side-effect of counting non-intent keys, and stopping after maxKeys, yes?


<!-- Sent from Reviewable.io -->

2021-05-28 15:44 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManBQr-0gjw8VT9biHi:-Manc0Us0oPHfQ8RJQqm:badmgxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/mvcc.go#L2529)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this comment about inconsistent scans still relevant, given the discussion about not making any change to it in this PR?
</blockquote></details>

I think I can improve the comment, but the discussion was that we need to mention inconsistent scans for completeness here.
___
*[pkg/storage/pebble.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManC1oJ-GgL-ravRfjn:-MancN-x7VSjYPETOAEG:bu358ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eeb35f3ea834228cd724f2a0e01c27b75bb6dd5/pkg/storage/pebble.go#L81)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what's our story with changing names of settings? Was the PR that introduced this backported to various versions? Is this fine since this was not public? I've seen warnings in logs before when playing around with settings names in PRs, so I wonder if this change could worry users who see unnecessary warnings.
</blockquote></details>

@nvanbenschoten can you elaborate? I don't think this option was used by anyone yet and I don't think we encourage tweaking this option unless absolutely necessary. Other option would be not to rename and reuse the same setting, but that would be confusing and harder to find. Or we can have another one, which will also add complexity as you may need to cap both of those values to reduce memory usage in case of intent buildup.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManFN14ARIwSyhc7E15:-Mancfsx4r32Zv1OlKKi:b-91kfvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/pebble_mvcc_scanner.go#L122)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> 	// intents as an error. For inconsistent scans number of intents is limited
> 	// by number of keys scan requests and clients should rely on pagination
> 	// to sensibly process large ranges.
> ```

I find the "For inconsistent scans ..." phrasing confusing. There is no limit on intents there. Whatever limit happens is just a side-effect of counting non-intent keys, and stopping after maxKeys, yes?
</blockquote></details>

That is correct. Caller gets as many intents as fits in between keys. Let me try to make it more clear.


<!-- Sent from Reviewable.io -->

2021-05-28 16:39 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManBQr-0gjw8VT9biHi:-Manq4Mv9txqNJrfFSd-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/mvcc.go#L2529)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

I think I can improve the comment, but the discussion was that we need to mention inconsistent scans for completeness here.
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 122 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManFN14ARIwSyhc7E15:-Manq642CLOalfDSEo4m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/pebble_mvcc_scanner.go#L122)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

That is correct. Caller gets as many intents as fits in between keys. Let me try to make it more clear.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-28 20:12 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-Maoan7xAVc0Sg6pxMe-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911, @nvanbenschoten, and @sumeerbhola)



<!-- Sent from Reviewable.io -->

2021-05-28 21:33 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> looks great!

> Reviewed 3 of 5 files at r5, 5 of 6 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-:-MaotHhR5YCiAsHFwlWL:b-5iv01d)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManBQr-0gjw8VT9biHi:-MaosDPyAvYbM7JpJh9a:bivk0k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/mvcc.go#L2529)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Let's make a note that `MaxIntents is a maximum number of intents collected by scanner in consistent mode before returning a WriteIntentError.`
___
*[pkg/storage/mvcc.go, line 80 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-Maos4944FOGbOom1zwL:-Maos4944FOGbOom1zwM:b-ykb6y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c4caefd7f94ded1fedac69578571a941bf0ffe6/pkg/storage/mvcc.go#L80)):*
> ```Go
> // MaxIntentsPerWriteIntentError sets maximum number of intents returned in
> // WriteIntentError in operations that return multiple intents per error.
> // Currently it is used in Scan and ExportToSST.
> ```

Scan, ReverseScan, and ExportToSST.
___
*[pkg/storage/pebble.go, line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManC1oJ-GgL-ravRfjn:-MaosZbA9LBqSo-Kbg0E:bpwipe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eeb35f3ea834228cd724f2a0e01c27b75bb6dd5/pkg/storage/pebble.go#L81)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

@nvanbenschoten can you elaborate? I don't think this option was used by anyone yet and I don't think we encourage tweaking this option unless absolutely necessary. Other option would be not to rename and reuse the same setting, but that would be confusing and harder to find. Or we can have another one, which will also add complexity as you may need to cap both of those values to reduce memory usage in case of intent buildup.
</blockquote></details>

Usually, the story is that we try not to rename settings and we add the deleted setting name to the `retiredSettings` set to avoid ever creating them again. I agree that we don't expect anyone to have ever set `storage.sst_export.max_intents_per_error`, especially if we backport this to 20.2 and 21.1 when we can, so I don't think there's much of a concern that someone sets it and then its no longer working after an upgrade. My suggestion is to add it to `retiredSettings` and proceed with the rename.


<!-- Sent from Reviewable.io -->

2021-06-01 08:59 UTC, aliher1911 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65465)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/mvcc.go, line 2529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65465#-ManBQr-0gjw8VT9biHi:-Mb2m-WFDaJe71xBygKo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9ad0c3653e91ba6b4b10773030a076fc5da3e62/pkg/storage/mvcc.go#L2529)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's make a note that `MaxIntents is a maximum number of intents collected by scanner in consistent mode before returning a WriteIntentError.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 09:01 UTC, aliher1911 commented
bors r=sumeerbhola,nvanbenschoten

2021-06-01 10:24 UTC, merged