release-20.2: kvcoord: fix sorting of replicas
cockroachdb/cockroach pull request #65470
Opened 2021-05-19 17:37 UTC by andreimatei

Backport 4/4 commits from #64394.

/cc @cockroachdb/release

---

This patch fixes a bug in replica sorting. When it think that a
particular request can be served through follower reads, the DistSender
sorts the replicas by latency, falling back to locality attributes. It
also has a special provision for ordering the local replica(s) first,
but that provision was buggy: the `Less` function was only correctly
comparing a local replica with a non-local one when the local replica
was on the left side of the compairison. This patch fixes the bug by
extracting the prioritization of local replicas out of the main sort,
giving them a dedicate phase for clarity.

Release note: A certain percentage of cases in which a node could
have served a follower read were not handled correctly, resulting in the
node routing the request to another nearby node for no reason. This has
been fixed.

2021-05-19 17:37 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65470)
<!-- Reviewable:end -->

2021-05-19 18:09 UTC, nvanbenschoten requested changes

2021-05-19 18:09 UTC, nvanbenschoten commented on pkg/sql/physicalplan/replicaoracle/oracle_test.go
> +		nil, /* txn */
DId we want this part of the change?

2021-05-20 17:46 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65470)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/sql/physicalplan/replicaoracle/oracle_test.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65470#-Ma4h5Q2kHEQeYXsC7hE-r4-55:-Ma9rlceCK19GE7_SVuf:bnf9crz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e822abb6af8a0c88d109253978fddbdfb929176/pkg/sql/physicalplan/replicaoracle/oracle_test.go#L55)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

DId we want this part of the change?
</blockquote></details>

the change to the test generally is necessary - the test was broken because it was expecting a node other than the local one to be the "closest". With this patch, the local one is chosen if there is a local replica, so the change to the test is to not have a local replica any more.
The patch was not compiling though; rebase issues. Fixed now.


<!-- Sent from Reviewable.io -->

2021-05-25 16:50 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65470#-:-MaZQojSEKbVTwUJMS6c:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)



<!-- Sent from Reviewable.io -->

2021-05-25 17:09 UTC, merged