release: check remote tag before pushing
cockroachdb/cockroach pull request #65555
Opened 2021-05-21 12:29 UTC by rail

Previously, prior to pushing the release git tag, we created and pushed
most of the release artifacts (docker images, s3). If we run the script
multiple times against the same version, it may rewrite the artifacts
and will fail pushing the exiting git tag, leaving the release process
in a partially released state.

This patch adds a check if the release git tag already pushed to the
GitHub repo and fails before any artifacts are created.

Fixes #54814

Release note: None

2021-05-21 12:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65555)
<!-- Reviewable:end -->

2021-05-27 02:04 UTC, jlinder requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[build/teamcity-common-support.sh, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafUX6E2W5af8r_0OQY:-MafUX6E2W5af8r_0OQZ:blwc4er) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/teamcity-common-support.sh#L35)):*
> ```
> git_wrapped() {
>   GIT_SSH_COMMAND="ssh -i .cockroach-teamcity-key" git "$@"
> }
> ```

Why not just make `push_to_git` more generic?
___
*[build/release/teamcity-publish-release.sh, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafYgDi5G68CM0a3zxr:-MafYgDi5G68CM0a3zxs:b7lg5wt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/release/teamcity-publish-release.sh#L62)):*
> ```Shell
> 
> tc_start_block "Check remote tag"
> if git_wrapped ls-remote --exit-code --tags . "${build_name}"; then
> ```

Does the `.` need to be `ssh://git@github.com/cockroachdb/cockroach.git` so it checks the remote repo and not the local repo?


<!-- Sent from Reviewable.io -->

2021-05-27 02:15 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/teamcity-common-support.sh, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafUX6E2W5af8r_0OQY:-MafZWP12CXcPatdssYA:b-qfb40w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/teamcity-common-support.sh#L35)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> git_wrapped() {
>   GIT_SSH_COMMAND="ssh -i .cockroach-teamcity-key" git "$@"
> }
> ```

Why not just make `push_to_git` more generic?
</blockquote></details>

I thought about that, but didn't want to touch multiple invocations. I can easily refactor it for sure.
___
*[build/release/teamcity-publish-release.sh, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafYgDi5G68CM0a3zxr:-MafZiNuCil8HI4rP9SL:b-6tibbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/release/teamcity-publish-release.sh#L62)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Does the `.` need to be `ssh://git@github.com/cockroachdb/cockroach.git` so it checks the remote repo and not the local repo?
</blockquote></details>

`.` works fine, I double checked it by creating a new tag locally and running it. It exited with code 2, what is expected. I can be more explicit and set the remote.


<!-- Sent from Reviewable.io -->

2021-05-27 02:24 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/teamcity-common-support.sh, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafUX6E2W5af8r_0OQY:-MafcWr8BOLrqLFZ7jLM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/teamcity-common-support.sh#L35)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

I thought about that, but didn't want to touch multiple invocations. I can easily refactor it for sure.
</blockquote></details>

Done.
___
*[build/release/teamcity-publish-release.sh, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafYgDi5G68CM0a3zxr:-MafcYqmDw3QN6O6Yrbt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/release/teamcity-publish-release.sh#L62)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

`.` works fine, I double checked it by creating a new tag locally and running it. It exited with code 2, what is expected. I can be more explicit and set the remote.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-27 02:48 UTC, jlinder approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[build/teamcity-common-support.sh, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafUX6E2W5af8r_0OQY:-MafdOxrB9CZSzWrO04j:b4vbbpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/teamcity-common-support.sh#L35)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Cool. I thought that may have been the reason (which I understand).
___
*[build/release/teamcity-publish-release.sh, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafYgDi5G68CM0a3zxr:-Mafb_XU0zbMx0ovfqk-:b-rrb8p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/release/teamcity-publish-release.sh#L62)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hrm. When I tested I got these results:

```
$ git tag -d v21.1.1
Deleted tag 'v21.1.1' (was f6630b3f52)
$ git ls-remote --exit-code --tags . v21.1.1
$ echo $?
2
$ git ls-remote --exit-code --tags ssh://git@github.com/cockroachdb/cockroach.git v21.1.1
f6630b3f524f3a5e52b330220037af01369b1ff2	refs/tags/v21.1.1
$ echo $?
0
```

Is that what you were expecting?

I also remembered that, since the origin repo on this checkout is from `cockroachlabs/release-staging`, the origin remote won't have the tag in it when the tag is in `cockroachdb/cockroach` , so the remote needs to be explicitly stated since git wouldn't know about it otherwise.


<!-- Sent from Reviewable.io -->

2021-05-27 03:29 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65555)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @rail)

___
*[build/release/teamcity-publish-release.sh, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65555#-MafYgDi5G68CM0a3zxr:-MafquSS1asONMFdBzOG:bf2ey93) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6296000cd3128fc96cd10bceb8ed2389d8dde7/build/release/teamcity-publish-release.sh#L62)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Hrm. When I tested I got these results:

```
$ git tag -d v21.1.1
Deleted tag 'v21.1.1' (was f6630b3f52)
$ git ls-remote --exit-code --tags . v21.1.1
$ echo $?
2
$ git ls-remote --exit-code --tags ssh://git@github.com/cockroachdb/cockroach.git v21.1.1
f6630b3f524f3a5e52b330220037af01369b1ff2	refs/tags/v21.1.1
$ echo $?
0
```

Is that what you were expecting?

I also remembered that, since the origin repo on this checkout is from `cockroachlabs/release-staging`, the origin remote won't have the tag in it when the tag is in `cockroachdb/cockroach` , so the remote needs to be explicitly stated since git wouldn't know about it otherwise.
</blockquote></details>

Hmmm, now I don't now how I tested :D 


<!-- Sent from Reviewable.io -->

2021-05-27 03:30 UTC, rail commented
bors r+

2021-05-27 05:18 UTC, merged