sql: use column attrnum as sub_id
cockroachdb/cockroach pull request #65597
Opened 2021-05-23 20:19 UTC by mneverov

sql: use column attrnum as sub_id

Fixes #65568

Previously, CRDB used a column id as objsubid in system.comments and
pg_catalog.pg_description. A column type change creates a new column with a new
column id, so these tables contained comments for old and new columns.

This patch changes column attnum to be used as objsubid instead, to prevent
creation of new entries for altered columns.

Release Notes: None

2021-05-23 20:19 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65597)
<!-- Reviewable:end -->

2021-05-25 17:31 UTC, rafiss approved these changes
thanks for this fix! lgtm

bors r+

2021-05-25 17:53 UTC, rafiss commented
bors r-

sorry, one request. could you add a release note:

```
Release note (bug fix): It is now possible to change the COMMENT on a column after using
ALTER TYPE on that column.
```

2021-05-25 17:53 UTC, rafiss requested changes
marking request for changes

2021-05-25 18:43 UTC, mneverov reviewed
> could you add a release note:
done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65597#-:-MaZpkPTDxFU0WU7Q2pu:b-7f3eke)* status: :shipit: complete! 0 of 0 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-05-25 18:49 UTC, rafiss approved these changes
thank you!

bors r+

2021-05-25 22:25 UTC, merged