sql/pgwire: add telemetry for pgwire extended protcol
cockroachdb/cockroach pull request #65679
Opened 2021-05-25 18:52 UTC by mneverov

sql/pgwire: add telemetry for pgwire extended protcol

This PR adds telemetry counters for parse, bind, describe, and execute commands.

Release note: None

2021-05-25 18:52 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65679)
<!-- Reviewable:end -->

2021-05-25 19:04 UTC, mneverov reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65679)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/65679#-MaZrlx52sYWjCktrPPg:-MaZrlx52sYWjCktrPPh:b-yure7e) (no related file):*
Note to the reviewer: please let me know if counters for close and flush messages should be added.

---


<!-- Sent from Reviewable.io -->

2021-05-26 00:26 UTC, rafiss requested changes
Good catch. Yes, let's add close/flush telemetry

2021-05-26 00:27 UTC, rafiss commented
cc @vy-ton

2021-05-26 19:58 UTC, rafiss approved these changes
thank you!!

bors r+

2021-05-26 20:54 UTC, merged