parser: fix "parenthesized" typo in datadriven test output
cockroachdb/cockroach pull request #65696
Opened 2021-05-25 23:55 UTC by mgartner

Release note: None

2021-05-25 23:55 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65696)
<!-- Reviewable:end -->

2021-05-25 23:56 UTC, otan requested changes
i'm pretty sure it's spelt "parenthesised"

2021-05-25 23:57 UTC, otan approved these changes
i kid

2021-05-26 00:37 UTC, mgartner commented
😆 

bors r+

2021-05-26 03:04 UTC, merged