Surface sampled query plan, database name, and execution nodes to internal node statement statistics table
cockroachdb/cockroach pull request #65782
Opened 2021-05-27 15:47 UTC by THardy98

2021-05-27 15:48 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65782)
<!-- Reviewable:end -->

2021-05-27 16:04 UTC, maryliag requested changes
Great work! 
Just a few comments: 
- the PR should have just one commit, to you can squash the 3 into 1
- the PR name should have the the package name and all lower case, so `sql: surface sampled query....`
- On the description add info about what the PR is about, a link to the issue with `Resolves #number` and a Release note

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-MaiYRvKCER1hU2kBBGi:b-d1x9cx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[pkg/sql/crdb_internal.go, line 948 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaiYzeyAhNAyXofmzGm:-MaiYzeyAhNAyXofmzGn:begocp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/42dd6e46426efb0bbbac2f61d5bf0a723a82ec09/pkg/sql/crdb_internal.go#L948)):*
> ```Go
> 				}
> 
> 				// createSamplePlan is a go closure function that builds a JSON object
> ```

you don't need to get in such details about what type of go function is this, you can go with
```
// createSamplePlan builds a formatted  JSON object from the explain tree nodes.
```


<!-- Sent from Reviewable.io -->

2021-05-27 16:52 UTC, THardy98 reviewed
done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-MaijH-j9Sr1jKUlqZCL:bb7f2mf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)



<!-- Sent from Reviewable.io -->

2021-05-27 17:07 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/sql/crdb_internal.go, line 948 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaiYzeyAhNAyXofmzGm:-Maimu-v1wiPLtZGY2Zr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/42dd6e46426efb0bbbac2f61d5bf0a723a82ec09/pkg/sql/crdb_internal.go#L948)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you don't need to get in such details about what type of go function is this, you can go with
```
// createSamplePlan builds a formatted  JSON object from the explain tree nodes.
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-05-27 17:33 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaisWCu1AU2Vupesg70:-MaisWCu1AU2Vupesg71:bcly2k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L970)):*
> ```Go
> 				// createSamplePlan builds a formatted  JSON object from the explain tree nodes.
> 				var createSamplePlan func(node *roachpb.ExplainTreePlanNode) *json.ObjectBuilder
> 				createSamplePlan = func(node *roachpb.ExplainTreePlanNode) *json.ObjectBuilder {
> ```

I think is better to remove the creation of this function from here, we can even add to a utils so other places can use it too


<!-- Sent from Reviewable.io -->

2021-05-27 17:34 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaisWCu1AU2Vupesg70:-MaisyKDCRjm48l_lTMu:b-3s7vp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L970)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think is better to remove the creation of this function from here, we can even add to a utils so other places can use it too
</blockquote></details>

you can also just moved to the top along with the other functions


<!-- Sent from Reviewable.io -->

2021-05-27 17:47 UTC, Azhng requested changes
Great work! :clap:

Also remember to update the release note section in your commit message. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-Maivuk5DuXeYFJIB7o4:b-eso09l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 968 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mais8e93Lj459hgbf5p:-Mais8eA-YHiABGmDe93:b-nx3h7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L968)):*
> ```Go
> 				}
> 
> 				// createSamplePlan builds a formatted  JSON object from the explain tree nodes.
> ```

nit: extra space here between "formatted" and "JSON"
___
*[pkg/sql/crdb_internal.go, line 969 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaiuANNBcCpl9lF7b6q:-MaiuANNBcCpl9lF7b6r:b-bdrk5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L969)):*
> ```Go
> 
> 				// createSamplePlan builds a formatted  JSON object from the explain tree nodes.
> 				var createSamplePlan func(node *roachpb.ExplainTreePlanNode) *json.ObjectBuilder
> ```

Also, I think you can just return the `json.JSON` object instead of the builder.
___
*[pkg/sql/crdb_internal.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaisWCu1AU2Vupesg70:-MaitzcP0PbfQaJ-Syk3:b-371ghi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L970)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can also just moved to the top along with the other functions
</blockquote></details>

Also it would be nice if you can add some tests for this function once you extracted it.
___
*[pkg/sql/crdb_internal.go, line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaitDNhB-RHsN_SNbHQ:-MaitDNhB-RHsN_SNbHR:bofbqve) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L972)):*
> ```Go
> 				createSamplePlan = func(node *roachpb.ExplainTreePlanNode) *json.ObjectBuilder {
> 
> 					nodePlan := json.NewObjectBuilder(3)
> ```

Two things here:
1. usually if we are passing a constant literal to a function, we usually add an inline comment with the parameter name behind that constant. So in this case, it would be: `json.NewObjectBuilder(3 /* numAddsHint */)`
2. Why 3 in this case? Would be nice to add a comment explaining it.
___
*[pkg/sql/crdb_internal.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaitgqF6ofRztEEqPdx:-MaitgqF6ofRztEEqPdy:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L979)):*
> ```Go
> 
> 					for _, attr := range node.Attrs {
> 						attrBuilder := json.NewObjectBuilder(1)
> ```

ditto
___
*[pkg/sql/crdb_internal.go, line 996 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaivOJQ0gOrx9G1xgg0:-MaivOJQ0gOrx9G1xgg1:bufh0yy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L996)):*
> ```Go
> 				samplePlan := createSamplePlan(&s.mu.data.SensitiveInfo.MostRecentPlanDescription)
> 
> 				execNodeIds := tree.NewDArray(types.Int)
> ```

nit: s/execNodeIds/execNodeIDs/
___
*[pkg/sql/crdb_internal.go, line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Maiv8ZR8TsYBvipgfpJ:-Maiv8ZR8TsYBvipgfpK:bqnvpai) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L997)):*
> ```Go
> 
> 				execNodeIds := tree.NewDArray(types.Int)
> 				for _, nodeId := range s.mu.data.Nodes {
> ```

nit: s/nodeId/nodeID/ 


<!-- Sent from Reviewable.io -->

2021-05-27 18:24 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 968 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mais8e93Lj459hgbf5p:-Maj3NJZ56ZwzHNFHhEa:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L968)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: extra space here between "formatted" and "JSON"
</blockquote></details>

done
___
*[pkg/sql/crdb_internal.go, line 972 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaitDNhB-RHsN_SNbHQ:-Maj3OlKA_i8zQY0CZd0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L972)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Two things here:
1. usually if we are passing a constant literal to a function, we usually add an inline comment with the parameter name behind that constant. So in this case, it would be: `json.NewObjectBuilder(3 /* numAddsHint */)`
2. Why 3 in this case? Would be nice to add a comment explaining it.
</blockquote></details>

done
___
*[pkg/sql/crdb_internal.go, line 979 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaitgqF6ofRztEEqPdx:-Maj3R-J5rbPN4nXyG7Q:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L979)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[pkg/sql/crdb_internal.go, line 996 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaivOJQ0gOrx9G1xgg0:-Maj-Nad8LQiqhuVoRdD:btcsj1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L996)):*
> execNodeIDs
done
___
*[pkg/sql/crdb_internal.go, line 997 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Maiv8ZR8TsYBvipgfpJ:-Maj3S9s6GIBerdXlxy_:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L997)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: s/nodeId/nodeID/ 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-05-27 21:24 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/sql/crdb_internal.go, line 969 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaiuANNBcCpl9lF7b6q:-MajhjGT3INcDsu0nfp-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L969)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Also, I think you can just return the `json.JSON` object instead of the builder.
</blockquote></details>

done
___
*[pkg/sql/crdb_internal.go, line 970 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-MaisWCu1AU2Vupesg70:-MajhGfbCyHq9POmyRyd:b-20rxvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d4469eb34eb50e947db11dac6e90a1d44827f/pkg/sql/crdb_internal.go#L970)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Also it would be nice if you can add some tests for this function once you extracted it.
</blockquote></details>

Extracted function, put it just above the table with other util functions used for the node_statement_statistics (e.g. getSQLStats).
Exported the function so it could be used in the unit testing file.


<!-- Sent from Reviewable.io -->

2021-05-27 21:46 UTC, maryliag requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/sql/crdb_internal_test.go, line 514 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Majk0zx7r2rDWSO0Ozs:-Majk0zy53-zHQBuSFxo:b8yhtgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6acfed5f8d0a29f7cd94b8e90e7eb2c2f5dd37b1/pkg/sql/crdb_internal_test.go#L514)):*
> ```Go
> // correctly builds a JSON object from an ExplainTreePlanNode.
> func TestExplainTreePlanNodeToJSON(t *testing.T) {
> 	// Test using a node with multiple inner children.
> ```

You can organize this by creating one list of objects with your input and expected result, so e.g.
```
testData := []struct {
		explainTree     roachpb.ExplainTreePlanNode
		expected string
	}{
		{	roachpb.ExplainTreePlanNode{.     <-- here is multiInner
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
		{	roachpb.ExplainTreePlanNode{.     <-- here is multiAttr
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
		{	roachpb.ExplainTreePlanNode{.     <--- here is multiChild
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
	}

	for _, test := range testData {
                	resultJSON := sql.ExplainTreePlanNodeToJSON(&test.explainTree)
	                require.Equal(t, test.expected, resultJSON.String())
	}
```


<!-- Sent from Reviewable.io -->

2021-05-27 21:47 UTC, maryliag reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 849 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Majmmlc57knysdbmMiP:-Majmmlc57knysdbmMiQ:b9sfzzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6acfed5f8d0a29f7cd94b8e90e7eb2c2f5dd37b1/pkg/sql/crdb_internal.go#L849)):*
> ```Go
> }
> 
> // explainTreePlanNodeToJSON builds a formatted JSON object from the explain tree nodes.
> ```

nit: capitalize first letter `ExplainTreePlanNodeToJSON`


<!-- Sent from Reviewable.io -->

2021-05-27 22:18 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/sql/crdb_internal.go, line 849 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Majmmlc57knysdbmMiP:-Majtz-E--7aAb7chSad:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6acfed5f8d0a29f7cd94b8e90e7eb2c2f5dd37b1/pkg/sql/crdb_internal.go#L849)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: capitalize first letter `ExplainTreePlanNodeToJSON`
</blockquote></details>

done
___
*[pkg/sql/crdb_internal_test.go, line 514 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Majk0zx7r2rDWSO0Ozs:-Maju0Xg62zl3JgsGFnm:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6acfed5f8d0a29f7cd94b8e90e7eb2c2f5dd37b1/pkg/sql/crdb_internal_test.go#L514)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

You can organize this by creating one list of objects with your input and expected result, so e.g.
```
testData := []struct {
		explainTree     roachpb.ExplainTreePlanNode
		expected string
	}{
		{	roachpb.ExplainTreePlanNode{.     <-- here is multiInner
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
		{	roachpb.ExplainTreePlanNode{.     <-- here is multiAttr
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
		{	roachpb.ExplainTreePlanNode{.     <--- here is multiChild
		Name: "root",.....
,
			`{"attrs": [{"rootKey": "rootValue"}].....`},
	}

	for _, test := range testData {
                	resultJSON := sql.ExplainTreePlanNodeToJSON(&test.explainTree)
	                require.Equal(t, test.expected, resultJSON.String())
	}
```

</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-05-28 17:27 UTC, maryliag requested changes
Changes look good, a few things missing:
- Changing your commit message as Archer mentioned (your commit must have all the info, not just the PR)
- There is some tests failing that you need to update, some about the table `node_statement_statistics` that now has more columns
The tests are on TeamCity: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3023812?
e.g. `pkg/sql/logictest/testdata/logic_test/create_statements` 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-Mao-6n95j9Q81eD1S-E:b-4qe3od)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/sql/crdb_internal_test.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-ManzB_JBybJjLLZOSB_:-ManzB_JBybJjLLZOSBa:bucf8ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8d7e7bd150db2f0b63b60ae28edfe9a1bc4999/pkg/sql/crdb_internal_test.go#L631)):*
> ```Go
> 		explainTreeJSON := sql.ExplainTreePlanNodeToJSON(&testData.explainTree)
> 		expected := testData.expected
> 		require.Equal(t, expected, explainTreeJSON.String())
> ```

there is not need to create the `expected` variable, you can use `testData.expected` directly


<!-- Sent from Reviewable.io -->

2021-05-31 13:43 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/sql/crdb_internal_test.go, line 631 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-ManzB_JBybJjLLZOSB_:-Mb1eQEo55rVupklZKDi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d8d7e7bd150db2f0b63b60ae28edfe9a1bc4999/pkg/sql/crdb_internal_test.go#L631)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

there is not need to create the `expected` variable, you can use `testData.expected` directly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-31 15:55 UTC, Azhng reviewed
Great work! Almost there. Just one more nit from me and seems like you might need to fix more tests in the CI :stuck_out_tongue: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-Mb27YFV37wlhZij-dA7:b30omxx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/sql/crdb_internal_test.go, line 501 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mb26oWk0SQZFG9DOHAc:-Mb26oWk0SQZFG9DOHAd:bykko9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/16172d9387b6ded0a7f14dde20615ee045cf7ff7/pkg/sql/crdb_internal_test.go#L501)):*
> ```Go
> 	var dbName string
> 
> 	_, err := sqlDB.Exec(`SET database = defaultdb`)
> ```

nit: might worth to add additional `require.Equal` before calling `SET database = defaultdb` to ensure the database name is what you expected prior to this statement.  Also, since it seems like this test is checking for SQL outputs of the `crdb_internal.node_statement_statistics` view and it's not really touching the internals of the code, you can simply just use logic test for it. It would be a lot cleaner since you can avoid a lot of boilerplate code. 


<!-- Sent from Reviewable.io -->

2021-05-31 17:20 UTC, THardy98 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/sql/crdb_internal_test.go, line 501 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mb26oWk0SQZFG9DOHAc:-Mb2R5OC2xcwFDSKZnwe:bakv51j) ([raw file](https://github.com/cockroachdb/cockroach/blob/16172d9387b6ded0a7f14dde20615ee045cf7ff7/pkg/sql/crdb_internal_test.go#L501)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: might worth to add additional `require.Equal` before calling `SET database = defaultdb` to ensure the database name is what you expected prior to this statement.  Also, since it seems like this test is checking for SQL outputs of the `crdb_internal.node_statement_statistics` view and it's not really touching the internals of the code, you can simply just use logic test for it. It would be a lot cleaner since you can avoid a lot of boilerplate code. 
</blockquote></details>

Removed the unit test, created a logic test as per your suggestion.


<!-- Sent from Reviewable.io -->

2021-05-31 21:01 UTC, maryliag reviewed
Nice!
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>  from the changes I requested
Make sure you got the approval from Archer from his requests too

@kevin-v-ngo if you don't mind taking a look if you're happy with the format of the plan. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-Mb3DJGhBuOZYzDgCI1c:bsvvaw9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)



<!-- Sent from Reviewable.io -->

2021-05-31 21:11 UTC, Azhng approved these changes
Nice! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Just make sure to wait for kevin to take a final look at plan format. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-Mb3FvPjEW0-CtK0zuB9:bpjst7f)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)



<!-- Sent from Reviewable.io -->

2021-06-07 20:03 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng, @maryliag, and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 854 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mbc3MU6Bw08eAfxYUvO:-Mbc3MU6Bw08eAfxYUvP:b-dyo2nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e6de3b96de7cc5e49431a1adcb196066c9c0c8/pkg/sql/crdb_internal.go#L854)):*
> ```Go
> 	// Create a new json.ObjectBuilder with 3 key-value pairs for the node's name,
> 	// a single node attribute, and the node's children.
> 	nodePlan := json.NewObjectBuilder(3 /* numAddsHint */)
> ```

Should it still be 3 here in this case now that we are just flattening the attribute trees?


<!-- Sent from Reviewable.io -->

2021-06-08 12:37 UTC, THardy98 commented
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)_ status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @Azhng, @maryliag, and @THardy98)
> 
> _[pkg/sql/crdb_internal.go, line 854 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mbc3MU6Bw08eAfxYUvO:-Mbc3MU6Bw08eAfxYUvP:b-dyo2nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e6de3b96de7cc5e49431a1adcb196066c9c0c8/pkg/sql/crdb_internal.go#L854)):_
> 
> > ```go
> > 	// Create a new json.ObjectBuilder with 3 key-value pairs for the node's name,
> > 	// a single node attribute, and the node's children.
> > 	nodePlan := json.NewObjectBuilder(3 /* numAddsHint */)
> > ```
> 
> Should it still be 3 here in this case now that we are just flattening the attribute trees?

No, should be: number of attributes + name + children -> num attributes + 2.
Fixed.

2021-06-08 15:34 UTC, Azhng approved these changes
Awesome work! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-:-MbgFZJG08b67nX7-oj5:bpj8b76)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag and @THardy98)

___
*[pkg/sql/crdb_internal.go, line 854 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65782#-Mbc3MU6Bw08eAfxYUvO:-MbgFIzK38UZRqOensu7:b8isxcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e6de3b96de7cc5e49431a1adcb196066c9c0c8/pkg/sql/crdb_internal.go#L854)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

No, should be: number of attributes + name + children -> num attributes + 2.
Fixed.

</blockquote></details>

NICE 🎉


<!-- Sent from Reviewable.io -->

2021-06-08 15:36 UTC, maryliag approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65782)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @maryliag and @THardy98)



<!-- Sent from Reviewable.io -->

2021-06-08 15:51 UTC, kevin-v-ngo commented
Looks good Thomas! Thanks for updating the format!

2021-06-08 15:56 UTC, THardy98 commented
bors r+

2021-06-08 19:04 UTC, merged