changefeedccl: don't return without calling ctxgroup.Wait()
cockroachdb/cockroach pull request #65789
Opened 2021-05-27 17:57 UTC by stevendanna

In general, we want to be sure to always Wait() on any context
group. In the previous code, we would early return if our context was
cancelled.

The small semaphore implementation here is what was already in the
code, I just moved it out into a few functions to avoid having to use
a break to label. There are a number of these kinds of libraries in
the code already, but all of them are heavier weight than this.

Release note: None

2021-05-27 17:57 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65789)
<!-- Reviewable:end -->

2021-05-27 22:07 UTC, miretskiy requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MajrITu7vG5jIBzjKed:-MajrITu7vG5jIBzjKee:bbk985x) ([raw file](https://github.com/cockroachdb/cockroach/blob/811ec62007aefa59f2af80a083a5d7954ee64bf8/pkg/ccl/changefeedccl/kvfeed/scanner.go#L77)):*
> ```Go
> 	// atomicFinished is used only to enhance debugging messages.
> 	var atomicFinished int64
> 	var semErr error
> ```

Not to thrilled about having semErr outside the loop.
Have you seen `util/limit/limiter.go`?


<!-- Sent from Reviewable.io -->

2021-05-28 08:37 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MajrITu7vG5jIBzjKed:-Mam4-e2By2APwxrn-Ms:bibk8as) ([raw file](https://github.com/cockroachdb/cockroach/blob/811ec62007aefa59f2af80a083a5d7954ee64bf8/pkg/ccl/changefeedccl/kvfeed/scanner.go#L77)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Not to thrilled about having semErr outside the loop.
Have you seen `util/limit/limiter.go`?


</blockquote></details>

I had seem util/limit but shy'd away from it since it creates spans when waiting, which I'm not sure we really wanted.  But, on second thought, we shouldn't be avoiding spans for things like this.

I agree with semErr outside of the loop -- especially because there is an `err` variable in scope so it would be easy to make a mistake.  I've changed things to just call Wait() before the early return.


<!-- Sent from Reviewable.io -->

2021-06-03 09:02 UTC, stevendanna commented
I think this is ready for another look.

2021-06-09 16:07 UTC, miretskiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MblWD-j6CcQLyEjaY14:-MblWD-j6CcQLyEjaY15:b-i2abc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0019f6ffb1cc14f65b5cf744eb4bdabadd5fd6a5/pkg/ccl/changefeedccl/kvfeed/scanner.go#L81)):*
> ```Go
> 		span := span
> 		if err := exportSem.Begin(ctx); err != nil {
> 			return errors.CombineErrors(err, g.Wait())
> ```

Just putting this out to make sure that my understanding is correct.  Up to you if you want to add a comment here....

We don't have to cancel the group context before g.Wait to speed up termination.  The reason afaik, is semaphore returns an error if it's limit is 0 (can't happen -- maxConcurrentExport should be >=1... maybe add panic/check/error?) Or it returns an error if ctx is done (i.e. cancelled) -- but if it is cancelled, then the group should exit as quickly as possible anyway.  So, no need to anything else.


<!-- Sent from Reviewable.io -->

2021-06-09 16:31 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MblWD-j6CcQLyEjaY14:-MblZ9M82M-JAsm6-mwL:bg1edwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0019f6ffb1cc14f65b5cf744eb4bdabadd5fd6a5/pkg/ccl/changefeedccl/kvfeed/scanner.go#L81)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Just putting this out to make sure that my understanding is correct.  Up to you if you want to add a comment here....

We don't have to cancel the group context before g.Wait to speed up termination.  The reason afaik, is semaphore returns an error if it's limit is 0 (can't happen -- maxConcurrentExport should be >=1... maybe add panic/check/error?) Or it returns an error if ctx is done (i.e. cancelled) -- but if it is cancelled, then the group should exit as quickly as possible anyway.  So, no need to anything else.
</blockquote></details>

Ha, well, your understanding matched mine. But, a few days ago the API this package changed, so this code needs to be updated as I doubt it even compiles now.  I'll go fix that and when I do I'll write a comment here if it turns out it is still that we don't need to cancel the context here -- the underlying implementation is now more complicated and it isn't clear to me it only errors in those two cases anymore.


<!-- Sent from Reviewable.io -->

2021-06-10 12:14 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MblWD-j6CcQLyEjaY14:-Mbpq0iBDDqZ1_UnuvF-:b-o1ixz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0019f6ffb1cc14f65b5cf744eb4bdabadd5fd6a5/pkg/ccl/changefeedccl/kvfeed/scanner.go#L81)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Ha, well, your understanding matched mine. But, a few days ago the API this package changed, so this code needs to be updated as I doubt it even compiles now.  I'll go fix that and when I do I'll write a comment here if it turns out it is still that we don't need to cancel the context here -- the underlying implementation is now more complicated and it isn't clear to me it only errors in those two cases anymore.
</blockquote></details>

The new implementation under the hood of ConcurrentRequestLimiter is complex enough that to me it makes sense to cancel here rather than relying on our current reading of the code being correct.


<!-- Sent from Reviewable.io -->

2021-06-10 18:30 UTC, stevendanna commented
bors r=miretskiy

2021-06-11 14:18 UTC, stevendanna commented
bors retry

2021-06-11 14:58 UTC, merged

2021-06-11 15:12 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65789)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ccl/changefeedccl/kvfeed/scanner.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65789#-MblWD-j6CcQLyEjaY14:-MbvcJesAXJq2DJ5aNq1:b-yf0c8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0019f6ffb1cc14f65b5cf744eb4bdabadd5fd6a5/pkg/ccl/changefeedccl/kvfeed/scanner.go#L81)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

The new implementation under the hood of ConcurrentRequestLimiter is complex enough that to me it makes sense to cancel here rather than relying on our current reading of the code being correct.
</blockquote></details>

If the spans upset you, that library is a tiny shim around `quotapool.IntPool` you could just use that thing directly. 


<!-- Sent from Reviewable.io -->