rfcs: default privileges
cockroachdb/cockroach pull request #65794
Opened 2021-05-27 19:11 UTC by RichardJCai

Release note: None

2021-05-27 19:11 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/65794)
<!-- Reviewable:end -->

2021-06-05 09:32 UTC, knz reviewed
I like this RFC very much.
I think you'll want reviews from the schema team too.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-:-MbQW3mtD1i-qOMl6eCP:b3xu15g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVQ5fE5ZJPQuAgqyJ:-MbQVQ5fE5ZJPQuAgqyK:b-wq8wlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L37)):*
> ```Markdown
> 
> In summary about default privileges in Postgres:
> No privileges are granted to PUBLIC by default on tables, table columns, sequences, foreign data wrappers, foreign servers, large objects, schemas, or tablespaces.
> ```

Can you talk a bit more about the emphasis on `public`

Does this mean that tables created in a schema that is not called "public" will not inherit the default privileges?
___
*[docs/RFCS/20210527_default_privileges.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVWO69f9PSMph-d3M:-MbQVWO69f9PSMph-d3N:b-c4n6lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L47)):*
> ```Markdown
> | ----------------------------- | ------------------ | ---------------------------------------------- |
> | Tables                        | None               | None                                           |
> | Table Columns                 | None               | X                                              |
> ```

use "N/A" instead of "X" to clarify.
___
*[docs/RFCS/20210527_default_privileges.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVby-9sIcW4QHKdn3:-MbQVby-9sIcW4QHKdn4:b-n9qdq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L76)):*
> ```Markdown
> 
> **Cons**:
> - Must loop through all object descriptors to create pg_default_acl table
> ```

Also it risks making the descriptors quite large.
___
*[docs/RFCS/20210527_default_privileges.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVfYA02x8MMrTUMHM:-MbQVfYA02x8MMrTUMHN:bwt7364) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L86)):*
> ```Markdown
> 
> **Cons**:
> - Have to query to grab privileges when creating table, at least O(logn) in number of objects
> ```

We can add an index to mitigate this.
___
*[docs/RFCS/20210527_default_privileges.md, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVsgWCq2PQbeDyiLk:-MbQVsgX1_XwcMTQZAmy:b2vbur9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L125)):*
> ```Markdown
> 
> In relation to default privileges, should we ensure all our privileges match 1:1 with Postgres? After supporting default privileges, we should be able to remove the incompatible privileges from being granted to objects. (See table below for incompatibilities).
> Example: currently we support SELECT on Databases for Cockroach, Postgres does not allow granting SELECT on databases. As mentioned before, one part of allowing SELECT on databases was to make our ad-hoc inheritance system work.
> ```

An alternative is to:

- keep the syntax for one more version, and mark it as deprecated
- under the hood, auto-translate it to granting the select default privilege on the db


<!-- Sent from Reviewable.io -->

2021-06-07 13:17 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbabKIM1AHoOtL9jTTD:-MbabKIM1AHoOtL9jTTE:b-xtmk2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L64)):*
> ```Markdown
> To store default privileges, we can continue to use PrivilegeDescriptors (either create a new protobuf field called “DefaultPrivileges” and add them to the object descriptors or we can directly add them to PrivilegeDescriptors. Or we can do what Postgres does and populate the pg_default_acl table which dictates initial privileges for newly created objects. We currently do something similar to this with users, role membership and role options in system.users, system.role_members, and system.role_options.
> 
> #### Option 1: Store default privileges on the object descriptor (protobuf)
> ```

In general, the RFC should present just one option and then should explore other options in a section dedicated to alternative approaches. 
___
*[docs/RFCS/20210527_default_privileges.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVby-9sIcW4QHKdn3:-Mbab08U0djm-ffT4fya:b4kf9pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L76)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also it risks making the descriptors quite large.
</blockquote></details>

However, the default privileges are not likely to be larger than the privileges. Moreover, it's unlikely to be an order of magnitude. 
___
*[docs/RFCS/20210527_default_privileges.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbab0vgCVgRSBj9ySF7:-Mbab0vgCVgRSBj9ySF8:b-hwjvry) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L78)):*
> ```Markdown
> - Must loop through all object descriptors to create pg_default_acl table
> 
> Note: the public schema does not have a SchemaDescriptor, we’ll have to store the public schema’s default privileges on the database descriptor.
> ```

We are planning on doing this migration in this release. I'd feel okay coupling these projects. 
___
*[docs/RFCS/20210527_default_privileges.md, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbabW11DGHaBn1sWfD3:-MbabW11DGHaBn1sWfD4:b1etga) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L93)):*
> ```Markdown
> Intuitively it makes more sense to optimize for performance for object creation since ALTERING DEFAULT PRIVILEGE is likely to happen less frequently than object creation. Also option 1 is more inline with what we currently do with privileges. Hence, overall option 1 is preferable.
> 
> ### New Syntax
> ```

I'd love some discussion of the various `GRANT` statements and note that that is also an area of incompatibility that we could address. Then we can choose not to. 
___
*[docs/RFCS/20210527_default_privileges.md, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVsgWCq2PQbeDyiLk:-MbablWuEEcpPGMFj0eC:bdeewu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L125)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

An alternative is to:

- keep the syntax for one more version, and mark it as deprecated
- under the hood, auto-translate it to granting the select default privilege on the db
</blockquote></details>

I like that approach.


<!-- Sent from Reviewable.io -->

2021-06-07 16:26 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVQ5fE5ZJPQuAgqyJ:-MbbHG606YZ0qXxvXwZ8:bdkr25s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you talk a bit more about the emphasis on `public`

Does this mean that tables created in a schema that is not called "public" will not inherit the default privileges?
</blockquote></details>

Sorry this is in reference to the `public` role and not the schema. I will update to make it clear.
___
*[docs/RFCS/20210527_default_privileges.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVby-9sIcW4QHKdn3:-MbbHLAF8MlOISXLzZAR:b2afikq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L76)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

However, the default privileges are not likely to be larger than the privileges. Moreover, it's unlikely to be an order of magnitude. 
</blockquote></details>

Yes, we discussed this on the Google doc I originally had, I'll send it to you @knz 
___
*[docs/RFCS/20210527_default_privileges.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbab0vgCVgRSBj9ySF7:-MbbHU5M-aJKJaT_Uung:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L78)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We are planning on doing this migration in this release. I'd feel okay coupling these projects. 
</blockquote></details>

SGTM
___
*[docs/RFCS/20210527_default_privileges.md, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbabW11DGHaBn1sWfD3:-MbbHYHO9u39Cx7eO6rX:b-e3yjpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L93)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd love some discussion of the various `GRANT` statements and note that that is also an area of incompatibility that we could address. Then we can choose not to. 
</blockquote></details>

Fair, I think it's more the certain privileges we allow GRANTing and not the overall syntax itself though right? Regardless I'll write in a bit more detail about it.


<!-- Sent from Reviewable.io -->

2021-06-08 14:52 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbfccas04-Uvmg01CCZ:-Mbfccas04-Uvmg01CC_:bqxhs14) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L11)):*
> ```Markdown
> 
> Currently CockroachDB handles privilege “inheritance” on objects in an ad-hoc way.
> When a table-like or schema object is created, it copies it’s privilege descriptor from the parent database and removes any invalid privileges.
> ```

Nit: it's -> its
___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbfdBb97xqsMWQptko9:-MbfdBb97xqsMWQptkoA:bd16h2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L30)):*
> ```Markdown
> The main technical change is to support default privileges. Ideally we want to support default privileges as closely as possible to Postgres’ default privileges.
> 
> Default privileges exist on schemas and databases. Note, Postgres defines default privileges defined for a database as “global” default privileges. Global makes more sense in the Postgres world as you cannot switch databases during a session like you can in CockroachDB.  You can define default privileges for objects that are created by yourself or roles that you are a member of.
> ```

Is one of the goals here to also match the terminology used in Postgres?  Are we planning on calling the default privileges on a database "global default privileges" too?
___
*[docs/RFCS/20210527_default_privileges.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbfdmco3_LgMerhErwU:-Mbfdmco3_LgMerhErwV:b-shq7dx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L41)):*
> ```Markdown
> EXECUTE is granted to public by default for functions and procedures.
> USAGE is granted to public by default for languages / data types (including domains)
> Since CockroachDB does not support all the objects listed, the matrix below does a comparison on which default privileges to public CockroachDB will have.
> ```

Nit: The above sentence might read better if rewritten "...the matrix below does a comparison to show how the default privileges in Postgres (for the PUBLIC role) will map to CockroachDB".  It might also help guide the reader to say something like "When this work is complete, CockroachDB will match Postgres privileges for all supported objects".
___
*[docs/RFCS/20210527_default_privileges.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbg5_GHAHzOoVqB7r2H:-Mbg5_GHAHzOoVqB7r2I:b8lmr6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L83)):*
> ```Markdown
> 
> **Pros**:
> - This is what Postgres does (?) not really a pro
> ```

Agreed, not really a pro.  Wouldn't the reduced materialization cost when querying be a pro?


<!-- Sent from Reviewable.io -->

2021-06-09 17:28 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbfdBb97xqsMWQptko9:-MblnrxU2dr4HM0Zz_9x:b-cetplp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L30)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is one of the goals here to also match the terminology used in Postgres?  Are we planning on calling the default privileges on a database "global default privileges" too?
</blockquote></details>

I believe this is more a docs issue. We can note that default privileges for databases can be worded as global default privileges (for that database).

This is a disconnect between crdb and pg since databases aren't really "global" in the crdb world.
___
*[docs/RFCS/20210527_default_privileges.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbfdmco3_LgMerhErwU:-Mblo8c49hIdpnpgypWQ:b-ttm637) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L41)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: The above sentence might read better if rewritten "...the matrix below does a comparison to show how the default privileges in Postgres (for the PUBLIC role) will map to CockroachDB".  It might also help guide the reader to say something like "When this work is complete, CockroachDB will match Postgres privileges for all supported objects".
</blockquote></details>

Took your wording since I couldn't have written it better myself.

Left the "when this work is complete" part off since this rfc is specific to default privileges, not entirely sure we'll have 100% compatibility on privileges for supported objects even after this work is done.
___
*[docs/RFCS/20210527_default_privileges.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbg5_GHAHzOoVqB7r2H:-MbloRgS1qpfgDCPe9uc:b-ulcfqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L83)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Agreed, not really a pro.  Wouldn't the reduced materialization cost when querying be a pro?
</blockquote></details>

Good call


<!-- Sent from Reviewable.io -->

2021-06-09 17:30 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, and @knz)

___
*[docs/RFCS/20210527_default_privileges.md, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVWO69f9PSMph-d3M:-MbloW-KDOW6zMr_Yp1p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L47)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

use "N/A" instead of "X" to clarify.
</blockquote></details>

Done.
___
*[docs/RFCS/20210527_default_privileges.md, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbabKIM1AHoOtL9jTTD:-Mblol3K7FzN99LdTyR1:bk2r0wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

In general, the RFC should present just one option and then should explore other options in a section dedicated to alternative approaches. 
</blockquote></details>

Restructured RFC to follow this
___
*[docs/RFCS/20210527_default_privileges.md, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVby-9sIcW4QHKdn3:-MblorSP2faxmh98ems9:b-uvrlbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L76)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Yes, we discussed this on the Google doc I originally had, I'll send it to you @knz 
</blockquote></details>

Sorry for not adding this to the RFC but I've added the explanation here as well.
___
*[docs/RFCS/20210527_default_privileges.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVfYA02x8MMrTUMHM:-Mblo_HjDm2ArYraBWvl:b-rsr2hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L86)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

We can add an index to mitigate this.
</blockquote></details>

Even with an index, wouldn't we still need O(logn) to lookup a specific key?
___
*[docs/RFCS/20210527_default_privileges.md, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVsgWCq2PQbeDyiLk:-MblogT_9aqiMVaWtEik:bumkhy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L125)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I like that approach.
</blockquote></details>

Listed as alternative (maybe this will be the preferred approach)


<!-- Sent from Reviewable.io -->

2021-06-17 07:16 UTC, rafiss approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbab0vgCVgRSBj9ySF7:-McNmxlq8qk6FFIHsEpx:b-t0oir) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L78)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

SGTM
</blockquote></details>

issue ref, in case it's useful to include in the document: https://github.com/cockroachdb/cockroach/issues/55793
___
*[docs/RFCS/20210527_default_privileges.md, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McNoOEw8hH01XD-8fzi:-McNoOEw8hH01XD-8fzj:b-f1b1ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L144)):*
> ```Markdown
> 3. In 22.2, remove long running migration. Deprecate syntax for revoking invalid privileges.
> 
> Alternatively
> ```

how do you think we can decide between the first suggestion and this alternative? does it mostly come down to amount of effort?


<!-- Sent from Reviewable.io -->

2021-06-23 20:32 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-McuWoMT0JTFdT0b7_fp:b-7111wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
> ```Markdown
> 
> Alternatively
> 1. In 21.2, continue supporting the syntax for incompatible privileges, however under the hood we will "translate" the incompatible privilege to the corresponding default privilege.
> ```

As I've been thinking more about this migration, I realized that `GRANTing` incompatible privileges that we use for the purpose of inheritance does not translate nicely over to `DEFAULT PRIVILEGES`.

The reason being, `DEFAULT PRIVILEGES` depend on the user creating the an object. Currently, our "inheritance" does not depend on who is creating the object, we'll always inherit the privileges by copying over the valid privileges from the Database onto our new object (table / schema). 

However, `DEFAULT PRIVILEGES` are set by role - the user who CREATEs the object. 
Theres no concept of having a set of DEFAULT PRIVILEGES for any role that creates an object (which is essentially what we were doing before).

To illustrate this further, `ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES to foo` is actually equivalent too `ALTER DEFAULT PRIVILEGES FOR USER current_user GRANT SELECT ON TABLES to foo` and this means any tables `current_user` creates in the current database will have `SELECT` on it for user `foo`. Theres nothing like `ALTER DEFAULT PRIVILEGES FOR ALL`

We could do a workaround by having a "reserved" role that effectively acts as "ALL" and where we translate `GRANTS` over to for the purpose of migration. When creating the PrivilegeDescriptor, we could union the DefaultPrivileges for `ALL` and whoever is creating the object. Having an entry `ALL` as the role in the DefaultPrivilegeDescriptor may be sufficient for this because `ALL` cannot be used as a role name. We would need special syntax, (maybe a function since `ALL` is not a valid role name) to REVOKE default privileges from `ALL` or just reset all `DEFAULT PRIVILEGES` so we can maintain backwards compatibility and the user can reset it if they want to.

`ALL` would also be used to migrate over privileges that we currently have that are used for inheritance as well. 

How this would work is for example in 21.2 when we support DEFAULT PRIVILEGES.
Doing `GRANT SELECT ON DATABASE to foo, bar` is translated as `ALTER DEFAULT PRIVILEGES FOR ROLE ALL GRANT SELECT ON tables TO foo, bar`. Then when a table is created, we union the default privileges for `ALL` and the user creating the table in the database to create the privileges.

Existing `SELECT` grants on the database will also do the same thing.

Open question is then how do we deprecate default privileges for `ALL` as this isn't a concept in Postgres. We would never support the syntax for granting to `ALL` but we will likely have to indefinitely handle this case. Which I think isn't too bad.

Thoughts? @ajstorm @knz @ajwerner 


<!-- Sent from Reviewable.io -->

2021-06-23 21:07 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-Mcug8A324K6w9X8oKde:bkqkm8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

As I've been thinking more about this migration, I realized that `GRANTing` incompatible privileges that we use for the purpose of inheritance does not translate nicely over to `DEFAULT PRIVILEGES`.

The reason being, `DEFAULT PRIVILEGES` depend on the user creating the an object. Currently, our "inheritance" does not depend on who is creating the object, we'll always inherit the privileges by copying over the valid privileges from the Database onto our new object (table / schema). 

However, `DEFAULT PRIVILEGES` are set by role - the user who CREATEs the object. 
Theres no concept of having a set of DEFAULT PRIVILEGES for any role that creates an object (which is essentially what we were doing before).

To illustrate this further, `ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES to foo` is actually equivalent too `ALTER DEFAULT PRIVILEGES FOR USER current_user GRANT SELECT ON TABLES to foo` and this means any tables `current_user` creates in the current database will have `SELECT` on it for user `foo`. Theres nothing like `ALTER DEFAULT PRIVILEGES FOR ALL`

We could do a workaround by having a "reserved" role that effectively acts as "ALL" and where we translate `GRANTS` over to for the purpose of migration. When creating the PrivilegeDescriptor, we could union the DefaultPrivileges for `ALL` and whoever is creating the object. Having an entry `ALL` as the role in the DefaultPrivilegeDescriptor may be sufficient for this because `ALL` cannot be used as a role name. We would need special syntax, (maybe a function since `ALL` is not a valid role name) to REVOKE default privileges from `ALL` or just reset all `DEFAULT PRIVILEGES` so we can maintain backwards compatibility and the user can reset it if they want to.

`ALL` would also be used to migrate over privileges that we currently have that are used for inheritance as well. 

Thoughts? @ajstorm @knz 
</blockquote></details>

How does this work with roles? What happens if you set the default privileges for the role public? 


<!-- Sent from Reviewable.io -->

2021-06-23 21:15 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-McuiK4E8QsB1BNBhcfn:b-82ds05) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
>  schema).

Default Privileges are copied over per role/user. Role memberships are not considered when creating privileges for an object based on the default privileges.

You aren't able to explicitly set default privileges for public or change it. But by default, public always gets certain default privileges.


<!-- Sent from Reviewable.io -->

2021-06-23 21:22 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-Mcuk-dyCJ8LM3G2cwYG:b-vhpido) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

>  schema).

Default Privileges are copied over per role/user. Role memberships are not considered when creating privileges for an object based on the default privileges.

You aren't able to explicitly set default privileges for public or change it. But by default, public always gets certain default privileges.
</blockquote></details>

I feel like the more I learn about the postgres privilege model the less I understand how people actually use it. 


<!-- Sent from Reviewable.io -->

2021-06-23 21:29 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-Mcul0q2C2R2DbPaYz0P:b-ued03z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like the more I learn about the postgres privilege model the less I understand how people actually use it. 
</blockquote></details>

:shrug:

If you were asking about the public role because of role membership considerations, I think it makes sense for default privileges to not consider role membership since it could be part of a role that has the default privilege but not have a certain default privilege itself.

To me, all default privileges are are the set of privileges that a new object should have at creation time. Role membership / privilege checks are completely separate from that.

```
rcai=# CREATE USER u1;
CREATE ROLE
rcai=# CREATE USER u2;
CREATE ROLE
rcai=#
rcai=# GRANT u1 TO u2;
GRANT ROLE
rcai=#
rcai=# ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO u1;
ALTER DEFAULT PRIVILEGES
rcai=# ALTER DEFAULT PRIVILEGES REVOKE SELECT ON TABLES FROM u2;
ALTER DEFAULT PRIVILEGES
rcai=# create table t6();
CREATE TABLE
rcai=# select * from information_schema.table_privileges where table_name = 't6';
 grantor | grantee | table_catalog | table_schema | table_name | privilege_type | is_grantable | with_hierarchy
---------+---------+---------------+--------------+------------+----------------+--------------+----------------
 rcai    | PUBLIC  | rcai          | public       | t6         | INSERT         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | SELECT         | NO           | YES
 rcai    | PUBLIC  | rcai          | public       | t6         | UPDATE         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | DELETE         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | TRUNCATE       | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | REFERENCES     | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | TRIGGER        | NO           | NO
 rcai    | rcai    | rcai          | public       | t6         | INSERT         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | UPDATE         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | DELETE         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | TRUNCATE       | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | REFERENCES     | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | TRIGGER        | YES          | NO
 rcai    | u1      | rcai          | public       | t6         | SELECT         | NO           | YES
(14 rows)
```


<!-- Sent from Reviewable.io -->

2021-06-23 21:29 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McuWoMT0JTFdT0b7_fo:-MculioP-Nt13DVvyG3T:bn1to89) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L145)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

:shrug:

If you were asking about the public role because of role membership considerations, I think it makes sense for default privileges to not consider role membership since it could be part of a role that has the default privilege but not have a certain default privilege itself.

To me, all default privileges are are the set of privileges that a new object should have at creation time. Role membership / privilege checks are completely separate from that.

```
rcai=# CREATE USER u1;
CREATE ROLE
rcai=# CREATE USER u2;
CREATE ROLE
rcai=#
rcai=# GRANT u1 TO u2;
GRANT ROLE
rcai=#
rcai=# ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO u1;
ALTER DEFAULT PRIVILEGES
rcai=# ALTER DEFAULT PRIVILEGES REVOKE SELECT ON TABLES FROM u2;
ALTER DEFAULT PRIVILEGES
rcai=# create table t6();
CREATE TABLE
rcai=# select * from information_schema.table_privileges where table_name = 't6';
 grantor | grantee | table_catalog | table_schema | table_name | privilege_type | is_grantable | with_hierarchy
---------+---------+---------------+--------------+------------+----------------+--------------+----------------
 rcai    | PUBLIC  | rcai          | public       | t6         | INSERT         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | SELECT         | NO           | YES
 rcai    | PUBLIC  | rcai          | public       | t6         | UPDATE         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | DELETE         | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | TRUNCATE       | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | REFERENCES     | NO           | NO
 rcai    | PUBLIC  | rcai          | public       | t6         | TRIGGER        | NO           | NO
 rcai    | rcai    | rcai          | public       | t6         | INSERT         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | UPDATE         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | DELETE         | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | TRUNCATE       | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | REFERENCES     | YES          | NO
 rcai    | rcai    | rcai          | public       | t6         | TRIGGER        | YES          | NO
 rcai    | u1      | rcai          | public       | t6         | SELECT         | NO           | YES
(14 rows)
```
</blockquote></details>

Note in the previous example, `PUBLIC` has all privileges as well, this is because the table is in the `public schema` if it weren't then public would have no privileges.


<!-- Sent from Reviewable.io -->

2021-06-24 12:50 UTC, ajstorm approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Well written and presented.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-:-Mcy3GT50SL8wQJt54hR:b-j2ydtj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbfdmco3_LgMerhErwU:-Mcy06WcBKkaMswBzxyD:bl1eay9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L41)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Took your wording since I couldn't have written it better myself.

Left the "when this work is complete" part off since this rfc is specific to default privileges, not entirely sure we'll have 100% compatibility on privileges for supported objects even after this work is done.
</blockquote></details>

Looks good.  On the last point, can we make any statement about what will be left when we're done this work?  Might be helpful in framing the effort.  What about ""When this work is complete, CockroachDB will match Postgres _default_ privileges for all supported objects"
___
*[docs/RFCS/20210527_default_privileges.md, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbg5_GHAHzOoVqB7r2H:-Mcy312q5fBpmjctZGF_:b-coxjfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L83)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Good call
</blockquote></details>

Looks good.  As a nit, you might want to drop the Postgres pro, as we're not striving for internal compatibility with PG.


<!-- Sent from Reviewable.io -->

2021-06-24 13:06 UTC, knz reviewed
Generally LGTM but I'd really like to see how the remaining open conversations wrap up and their resolution phrased into the body of the RFC.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-:-Mcy7Gdf63xj19AQqV-Z:b-k022xb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVfYA02x8MMrTUMHM:-Mcy6WDJ4CYsXcAnA73b:b-n7fdih) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L86)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Even with an index, wouldn't we still need O(logn) to lookup a specific key?
</blockquote></details>

your sentence is "at least O(logn)" 
we should find a solution so that becomes "at most O(logn)"

is this alternative providing that?
___
*[docs/RFCS/20210527_default_privileges.md, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mcy6OAp3WifcE2xmLKb:-Mcy6OAq2NHQMB3jS2bH:bxq9d3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L85)):*
> ```Markdown
> **Pros**:
> - This is what Postgres does (?) not really a pro
> - Reduced materialization cost when querying the pg_default_acl table.
> ```

nit: please include the identifier between backquotes
___
*[docs/RFCS/20210527_default_privileges.md, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mcy6o-PB7iltsABr__A:-Mcy6o-PB7iltsABr__B:b7rkilo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L90)):*
> ```Markdown
> - Have to query to grab privileges when creating table, at least O(logn) in number of objects
> 
> Note that this is fairly similar to how we store users / role options in system.users / system.role_options.
> ```

nit: add backquotes around the identifiers (otherwise, the preview in reviewable breaks)


<!-- Sent from Reviewable.io -->

2021-06-24 21:26 UTC, ajwerner approved these changes
I like this proposal. I don't think I like postgres's concepts but that's not up to me. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-:-MczuVCp5Wg4H-qwRx6W:b-2b8z3n)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mcy6UNXC56Q6PtF3ALu:-Mcy6UNY1zQIHMH4F-_n:b1wxbzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L32)):*
> Default privileges define the set of privileges on newly created objects in a database or schema.Default privileges are able to be set for specific users. 

In light of what you've taught me recently, I think this description could be expanded. "are able" I think leads me astray.

Default privileges define a set of user privileges on newly created objects in a database or schema for a given user. Like we want some way to say that it's always a mapping from a given user to a map of privileges (which might involve any user). 
___
*[docs/RFCS/20210527_default_privileges.md, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MbQVfYA02x8MMrTUMHM:-McyFs8A14ZE9rkRtPtN:btaq5y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L86)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

your sentence is "at least O(logn)" 
we should find a solution so that becomes "at most O(logn)"

is this alternative providing that?
</blockquote></details>

We aren't moving forward with this approach so I don't think it matters. The approach being proposed is, in a sense, O(N) in the number of default privileges on the relevant schema and database (in that we need to deserialize them). It is not, however, O(N) in the total number of default privileges in the system. 
___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MczrWEMDeUGZksimH1X:-MczrWEMDeUGZksimH1Y:b-80tic5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L30)):*
> ```
> You can define default privileges for objects that are created by yourself or roles that you are a member of.
> ```

I wish we had better language to describe the user in the privilege itself. Like say I'm `u1` and I have `r1` but not `ajwerner`:

```
postgres=> ALTER DEFAULT PRIVILEGES FOR ROLE r1 IN SCHEMA u1 GRANT SELECT ON TABLES TO ajwerner;
ALTER DEFAULT PRIVILEGES
postgres=> ALTER DEFAULT PRIVILEGES FOR ROLE ajwerner IN SCHEMA u1 GRANT SELECT ON TABLES TO r1;
ERROR:  must be member of role "ajwerner"
```

These topics are hard to talk about. 


<!-- Sent from Reviewable.io -->

2021-06-25 07:58 UTC, knz reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MczrWEMDeUGZksimH1X:-Md1A-De4mRl4PNYGK8A:b-kpw5nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L30)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> You can define default privileges for objects that are created by yourself or roles that you are a member of.
> ```

I wish we had better language to describe the user in the privilege itself. Like say I'm `u1` and I have `r1` but not `ajwerner`:

```
postgres=> ALTER DEFAULT PRIVILEGES FOR ROLE r1 IN SCHEMA u1 GRANT SELECT ON TABLES TO ajwerner;
ALTER DEFAULT PRIVILEGES
postgres=> ALTER DEFAULT PRIVILEGES FOR ROLE ajwerner IN SCHEMA u1 GRANT SELECT ON TABLES TO r1;
ERROR:  must be member of role "ajwerner"
```

These topics are hard to talk about. 

</blockquote></details>

I recommend the following vocabulary:

- grantor: the user that runs the GRANT statement
- grantee: the user that is the target of a GRANT statement
- owner: the OWNED BY user on a descriptor
- creator: the user that creates a descriptor

It could be useful to create a table that shows,for each relevant SQL statement, how the 4 participants here benefit from it.


<!-- Sent from Reviewable.io -->

2021-06-25 22:15 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, and @rafiss)

___
*[docs/RFCS/20210527_default_privileges.md, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mcy6UNXC56Q6PtF3ALu:-Md4CaS0-OKBL8IirLxV:b-a4xha8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> Default privileges define the set of privileges on newly created objects in a database or schema.Default privileges are able to be set for specific users. 

In light of what you've taught me recently, I think this description could be expanded. "are able" I think leads me astray.

Default privileges define a set of user privileges on newly created objects in a database or schema for a given user. Like we want some way to say that it's always a mapping from a given user to a map of privileges (which might involve any user). 
</blockquote></details>

It's pretty hard to put this into words.

To use the map concept.
For an object created in a database or schema, you'd look up using the key `object_creator_role`/`object_type` and the value would be the set of user privileges that go on the newly created object.
___
*[docs/RFCS/20210527_default_privileges.md, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbfdmco3_LgMerhErwU:-Md451AT7rt_7hIyJyou:bdrr1tq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L41)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Looks good.  On the last point, can we make any statement about what will be left when we're done this work?  Might be helpful in framing the effort.  What about ""When this work is complete, CockroachDB will match Postgres _default_ privileges for all supported objects"
</blockquote></details>

Added `Once this work is complete, CockroachDB will support Postgres' concept of default privileges for all supported objects.`
___
*[docs/RFCS/20210527_default_privileges.md, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-Mbab0vgCVgRSBj9ySF7:-Md45__BCt6XfZu_LpnX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L78)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

issue ref, in case it's useful to include in the document: https://github.com/cockroachdb/cockroach/issues/55793
</blockquote></details>

Done.
___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MczrWEMDeUGZksimH1X:-Md4DtWB6v5kAmovWpxc:b6y69t1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I recommend the following vocabulary:

- grantor: the user that runs the GRANT statement
- grantee: the user that is the target of a GRANT statement
- owner: the OWNED BY user on a descriptor
- creator: the user that creates a descriptor

It could be useful to create a table that shows,for each relevant SQL statement, how the 4 participants here benefit from it.
</blockquote></details>

I think `creator` makes sense here.
```
ALTER DEFAULT PRIVILEGES
    [ FOR { ROLE | USER } target_role [, ...] ]
    [ IN SCHEMA schema_name [, ...] ]
    abbreviated_grant_or_revoke
```

Looking at the syntax from Postgres, I would say `target_role` can be thought of as `creator` and `grantee` can be the set of users specified in the grant or revoke statement.
___
*[docs/RFCS/20210527_default_privileges.md, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-McNoOEw8hH01XD-8fzi:-Md4CLDrEzOxYtgpmRle:b-gvp27n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L144)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how do you think we can decide between the first suggestion and this alternative? does it mostly come down to amount of effort?
</blockquote></details>

I rewrote this in more detail. I think the alternative is more favourable since we'd maintain backwards compatibility and give users sufficient warning for deprecation.


<!-- Sent from Reviewable.io -->

2021-06-30 12:43 UTC, knz approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, @rafiss, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MczrWEMDeUGZksimH1X:-MdRw0eSA7IqZP4A8tOT:bestt4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6614e3f86f923f19ff2c4c1701f1364ad0d23d2/docs/RFCS/20210527_default_privileges.md#L30)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think `creator` makes sense here.
```
ALTER DEFAULT PRIVILEGES
    [ FOR { ROLE | USER } target_role [, ...] ]
    [ IN SCHEMA schema_name [, ...] ]
    abbreviated_grant_or_revoke
```

Looking at the syntax from Postgres, I would say `target_role` can be thought of as `creator` and `grantee` can be the set of users specified in the grant or revoke statement.
</blockquote></details>

Based on this refreshed understanding, I think it may be worth rephrasing this paragraph in the RFC to clarify a bit what is going on.
___
*[docs/RFCS/20210527_default_privileges.md, line 41 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdRw6HNBCoNd6G8oDI3:-MdRw6HNBCoNd6G8oDI4:bb7phvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2e0b81ef9d635eb1bfa1d149be32767af87f98/docs/RFCS/20210527_default_privileges.md#L41)):*
> ```Markdown
> EXECUTE is granted to the `public` role by default for functions and procedures.
> USAGE is granted to the `public` role by default for languages / data types (including domains)
> Since CockroachDB does tsnot support all the objec listed, the matrix below does a comparison to show how the default privileges in Postgres (for the PUBLIC role) will map to CockroachDB.
> ```

typo
___
*[docs/RFCS/20210527_default_privileges.md, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdRwIhXA5zB-E3IgOY_:-MdRwIhXA5zB-E3IgOYa:bntnou2) ([raw file](https://github.com/cockroachdb/cockroach/blob/da2e0b81ef9d635eb1bfa1d149be32767af87f98/docs/RFCS/20210527_default_privileges.md#L163)):*
> ```Markdown
> There is no concept of having a set of default privileges for any role that creates an object - which is currently how it works in CockroachDB.
> 
> To illustrate this further, `ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES to foo` is actually equivalent too `ALTER DEFAULT PRIVILEGES FOR USER current_user GRANT SELECT ON TABLES to foo` and this means any tables current_user creates in the current database will have SELECT on it for user foo. 
> ```

too -> to

enclose `current_user` into backticks otherwise the remainder of the text becomes misformatted.


<!-- Sent from Reviewable.io -->

2021-07-01 19:53 UTC, piyush-singh requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm, @ajwerner, @knz, @rafiss, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSLrlu6OtYjVYxphgP:-MdSLrlu6OtYjVYxphgQ:b-p408jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L102)):*
> ```Markdown
> Abbreviated_grant_or_revoke
> ```
> ```

Is it worth including a new `SHOW` statement to let users easily inspect default privileges in the sql shell? Perhaps:

```
SHOW DEFAULT PRIVILEGES 
[ FOR { ROLE | USER } role [, ...] ]
[ IN SCHEMA schema [, ...]]
```

PG doesn't have `SHOW` statements (outside of inspecting settings) and MySQL doesn't have default privileges, so this doesn't quite borrow from either. I still think it would be a useful extension for convenience. PG behavior when omitting `FOR ROLE` from the `ALTER` statement is to assume the current role as the context, but for the `SHOW` statement I'd argue omitting the `FOR ROLE` should instead show default privileges for all roles/users. I think matching the `ALTER` statements behavior for `IN SCHEMA` makes sense: omitting it should return the list of global default privileges. 

I think the output could match the pg_default_acl table structure with filters applied as appropriate to roles and schemas.
___
*[docs/RFCS/20210527_default_privileges.md, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdT9SxI9ZjGYHtyylfj:-MdT9SxI9ZjGYHtyylfk:birdja5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L111)):*
> ```
> create the PrivilegeDescriptor as needed
> ```
I'm not as familiar with the ownership migration - does this imply that when there is no PrivilegeDescriptor field we will interpret it as having some default privilege values and continue to omit the field until the user runs an ALERT DEFAULT PRIVILEGES command or we kick off the long running migration?
___
*[docs/RFCS/20210527_default_privileges.md, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdTAQfE02vc-u84P9Yk:-MdTAQfE02vc-u84P9Yl:bozmfv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L119)):*
> ```Markdown
> Overall, I would start with option two as it is less intrusive before performing a long running migration to fully upgrade the descriptors.
> 
> We also have to take into consideration what set of default privileges we want to use if the default privileges are not set for a descriptor. We can either use the unchanged default set of privileges for that object type or we may want to generate the default privileges based on the privileges on the object. For example if we have SELECT on a database, the set of default privileges we create should include SELECT for backwards compatibility reasons, prior to this change, a table created in a database where a user has SELECT privilege would have SELECT privilege on the table.
> ```

In PG, default privileges are scoped to schemas, right? So would we update the defaults for all schemas under a specific DB? Or only user created schemas under the DB? I actually don't know how default privileges are handled in PG for things like the information schema or other DB (non-user-created) schemas.
___
*[docs/RFCS/20210527_default_privileges.md, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSeZZg3d-z6COyEaJE:-MdSeZZg3d-z6COyEaJF:bc4c0ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L160)):*
> ```Markdown
> - **Sequences have the same privilege set as tables in CRDB, this is not true in Postgres, see USAGE**
> ```

Not sure if this is normally included in RFCs, but should we have a section on how we will expose this information in the Cloud and DB consoles? Is there anything we would need to change on the DB side to be able to expose this via the consoles? I assume we would need to modify whatever schema metadata API we have to also include default privilege information. We may also want to think about how we want to represent global privileges unattached to a specific schema. 


<!-- Sent from Reviewable.io -->

2021-07-01 20:12 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65794)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm, @ajwerner, @knz, @piyush-singh, @rafiss, and @RichardJCai)

___
*[docs/RFCS/20210527_default_privileges.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSLrlu6OtYjVYxphgP:-MdYgnLP57L6k_9KOnpk:b-293rjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L102)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

Is it worth including a new `SHOW` statement to let users easily inspect default privileges in the sql shell? Perhaps:

```
SHOW DEFAULT PRIVILEGES 
[ FOR { ROLE | USER } role [, ...] ]
[ IN SCHEMA schema [, ...]]
```

PG doesn't have `SHOW` statements (outside of inspecting settings) and MySQL doesn't have default privileges, so this doesn't quite borrow from either. I still think it would be a useful extension for convenience. PG behavior when omitting `FOR ROLE` from the `ALTER` statement is to assume the current role as the context, but for the `SHOW` statement I'd argue omitting the `FOR ROLE` should instead show default privileges for all roles/users. I think matching the `ALTER` statements behavior for `IN SCHEMA` makes sense: omitting it should return the list of global default privileges. 

I think the output could match the pg_default_acl table structure with filters applied as appropriate to roles and schemas.
</blockquote></details>

Agreed, I'll add a small note on this.
___
*[docs/RFCS/20210527_default_privileges.md, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdT9SxI9ZjGYHtyylfj:-MdYgWTd78Ff7FAXkyMp:b-xnapc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L111)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

> ```
> create the PrivilegeDescriptor as needed
> ```
I'm not as familiar with the ownership migration - does this imply that when there is no PrivilegeDescriptor field we will interpret it as having some default privilege values and continue to omit the field until the user runs an ALERT DEFAULT PRIVILEGES command or we kick off the long running migration?
</blockquote></details>

Yes your first interpretation is correct, in this context, if there is no DefaultPrivilegeDescriptor, we will interpret it as having the predefined set of default privileges by postgres and continue to omit until the user makes a change that requires writing the DefaultPrivilegeDescriptor to disk.
___
*[docs/RFCS/20210527_default_privileges.md, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdTAQfE02vc-u84P9Yk:-MdYfhWy0JznQypF-rlW:b-nrmzgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L119)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

In PG, default privileges are scoped to schemas, right? So would we update the defaults for all schemas under a specific DB? Or only user created schemas under the DB? I actually don't know how default privileges are handled in PG for things like the information schema or other DB (non-user-created) schemas.
</blockquote></details>

They're scoped to either databases (global) or schemas. 

We currently only inherit "USAGE" from schemas to types when we create them in a specifc schema, we'll have to update that. Other than that, schemas won't have default privileges. I think default privileges should work the same for information schema / other non-user-created schemas.

Works in PG
```
rcai=> alter default privileges in schema information_schema grant select on tables to foo;
ALTER DEFAULT PRIVILEGES
```
___
*[docs/RFCS/20210527_default_privileges.md, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSeZZg3d-z6COyEaJE:-MdYfSvxD4iOgPpMzfOh:bo3zeuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L160)):*
<details><summary><i>Previously, piyush-singh (Piyush Singh) wrote…</i></summary><blockquote>

Not sure if this is normally included in RFCs, but should we have a section on how we will expose this information in the Cloud and DB consoles? Is there anything we would need to change on the DB side to be able to expose this via the consoles? I assume we would need to modify whatever schema metadata API we have to also include default privilege information. We may also want to think about how we want to represent global privileges unattached to a specific schema. 
</blockquote></details>

Sorry I'm not familiar with this, do we currently expose any privilege related information through the DB Console / Cloud? I checked the webui and don't see anything.

I think this loops back to your point on `SHOW DEFAULT PRIVILEGES` which we will likely implement.


<!-- Sent from Reviewable.io -->

2021-07-06 18:39 UTC, piyush-singh commented
___
*[docs/RFCS/20210527_default_privileges.md, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSeZZg3d-z6COyEaJE:-Mdx5sQP4pm-YOPbvK_m:b-x9a4fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L160)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Sorry I'm not familiar with this, do we currently expose any privilege related information through the DB Console / Cloud? I checked the webui and don't see anything.

I think this loops back to your point on `SHOW DEFAULT PRIVILEGES` which we will likely implement.
</blockquote></details>

Clicking into a specific table on the databases page reveals the Grants page:

![image.png](https://files.reviewableusercontent.io/images/reviewable/21692034/YJ5DzotTtJcM9FjTNvAHIGNM/image.png)

This will of course have any grants that were set as part of the defaults for specific roles, but would not show the defaults themselves. I think this is more of a nice to have as a way to easily view the defaults, but I don't think it critical. I know you want to push this RFC across the line ASAP, so perhaps it is fine to just file a standalone issue for this as an enhancement.


<!-- Sent from Reviewable.io -->

2021-07-06 18:50 UTC, RichardJCai commented
> _[docs/RFCS/20210527_default_privileges.md, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65794#-MdSeZZg3d-z6COyEaJE:-Mdx5sQP4pm-YOPbvK_m:b-x9a4fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4075c17fddd3860521f0820a47be8ba45c3c467a/docs/RFCS/20210527_default_privileges.md#L160)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> Clicking into a specific table on the databases page reveals the Grants page:
> 
> ![image.png](https://camo.githubusercontent.com/378723490d5e19207caac37a7f41c536cac80a39dd7e24b17641e635e70abf81/68747470733a2f2f66696c65732e72657669657761626c6575736572636f6e74656e742e696f2f696d616765732f72657669657761626c652f32313639323033342f594a35447a6f7454744a634d39466a544e76414849474e4d2f696d6167652e706e67)
> 
> This will of course have any grants that were set as part of the defaults for specific roles, but would not show the defaults themselves. I think this is more of a nice to have as a way to easily view the defaults, but I don't think it critical. I know you want to push this RFC across the line ASAP, so perhaps it is fine to just file a standalone issue for this as an enhancement.

Ah understood, I think this should be fairly straight forward once we have `SHOW DEFAULT PRIVILEGES` working.

2021-07-06 19:26 UTC, RichardJCai commented
bors r+

2021-07-06 21:01 UTC, merged