util/log: extend `logpb.Entry` with more fine grained fields
cockroachdb/cockroach pull request #66096
Opened 2021-06-04 18:46 UTC by knz

Needed for #65633 and #61378.

cc @cockroachdb/server

2021-06-04 18:46 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66096)
<!-- Reviewable:end -->

2021-06-04 20:07 UTC, cameronnunez requested changes
After these minor changes, LGTM! Thanks for your work here.

2021-06-04 20:07 UTC, cameronnunez commented on pkg/util/log/format_crdb_v1_test.go
> +	preambleLength := len(formatEntry(severity.INFO, channel.DEV, t1, 0, "clog_test.go", 136, ``, ""))
Each instance of the string "clog_test.go" in `format_crdb_v1_test.go` and `testdata/crdb_v1` should be changed to the string "format_crdb_v1_test.go"

2021-06-05 10:31 UTC, knz reviewed
nit: if you are only requesting minor changes, then it's better to leave your review disposition as "neutral" instead of "changes requested".
With "changes requested" I have to wait until you complete the review before I can merge the PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66096#-:-MbQiHzu7TfrTAatJXAx:b-vbmgq6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/util/log/format_crdb_v1_test.go, line 32 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66096#-MbNLNYoUDQGWSMWUy4l-r3-32:-MbQhqDyE89Ucfj_1qfF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cc0921781bafc52a555c48404759e4ad6e3654a/pkg/util/log/format_crdb_v1_test.go#L32)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

```suggestion
func TestFormatCrdbV1Decode(t *testing.T) {
```

For consistency, I suggest a slight change to the function name here.
</blockquote></details>

Done.
___
*[pkg/util/log/format_crdb_v1_test.go, line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66096#-MbNLNYoUDQGWSMWUy4l-r3-122:-MbQhqyx-RO3JocBQWfC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cc0921781bafc52a555c48404759e4ad6e3654a/pkg/util/log/format_crdb_v1_test.go#L122)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

Each instance of the string "clog_test.go" in `format_crdb_v1_test.go` and `testdata/crdb_v1` should be changed to the string "format_crdb_v1_test.go"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-07 15:52 UTC, cameronnunez commented
> nit: if you are only requesting minor changes, then it's better to leave your review disposition as "neutral" instead of "changes requested".
> With "changes requested" I have to wait until you complete the review before I can merge the PR.
Understood!

2021-06-07 16:41 UTC, knz commented
You still need to review and change your disposition.
![image](https://user-images.githubusercontent.com/642886/121057860-0404be00-c7c0-11eb-9754-a8d1cdb81153.png)

2021-06-07 16:47 UTC, cameronnunez approved these changes

2021-06-07 16:51 UTC, cameronnunez commented
> You still need to review and change your disposition.
> ![image](https://user-images.githubusercontent.com/642886/121057860-0404be00-c7c0-11eb-9754-a8d1cdb81153.png)

👍 Done.

2021-06-07 16:57 UTC, knz commented
awesome, thank you!

bors r=cameronnunez

2021-06-07 17:54 UTC, merged