rfcs: introduce rfc for multi-tenant zone configs
cockroachdb/cockroach pull request #66348
Opened 2021-06-11 05:25 UTC by irfansharif

Zone configs dictate data placement, replication factor, and GC
behavior; they power CRDB's multi-region abstractions. They're disabled
for secondary tenants due to scalability bottlenecks in how they're
currently stored and disseminated. They also prevent writes before DDL
in the same transaction, implement inheritance and key-mapping by
coupling KV and SQL in an undesirable manner (making for code that's
difficult to read and write), and don't naturally extend to a
multi-tenant CRDB.

This RFC proposes a re-work of the zone configs infrastructure to enable
its use for secondary tenants, and in doing so addresses the problems
above. We introduce a distinction between SQL zone configs (attached to
SQL objects, living in the tenant keyspace) and KV zone configs (applied
to an arbitrary keyspan, living in the host tenant), re-implement
inheritance by introducing unique IDs for each zone configuration
object, and notify each node of updates through rangefeeds.

Release note: None

2021-06-11 05:25 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66348)
<!-- Reviewable:end -->

2021-06-11 12:49 UTC, ajwerner reviewed
Just a quick first pass. I feel good about where this is headed. 

I find the re-use of the term "zone config" in "SQL zone config" and "KV zone config" forces the document to make lots of clarification. How would you feel about introducing a new term that is easier to disambiguate. What if we called the new KV-level config a "span config" (`scfgs`), as you do in the API? I have a feeling it would increase readability both here and in the code. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mbv52IH12Ku6HlJvMfW:b-qlh0od)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @nvanbenschoten)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv3XGE7y18DZYR7qO8:-Mbv3XGE7y18DZYR7qO9:b5p4ejv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L80)):*
> ```Markdown
>    The determination of split points and zone configs is the last remaining
>    use of gossip for the `SystemConfigSpan` (we used to depend on it for table
>    leases, but that's [no longer the
> ```

FYI also cluster settings https://github.com/cockroachdb/cockroach/pull/58362 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-Mbv4bP9AmfJgjN3TSv6:bnm1tq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
> ```Markdown
>    apply over a given key range.
> 
> With multi-tenancy, we have a few more:
> ```

The fact that replication reports, the mechanism by which we understand whether zone configs are fulfilled etc could feature here. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv3rhF5OXQdbUMWIfq:-Mbv3rhF5OXQdbUMWIfr:b530xv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L117)):*
> ```Markdown
>      split points implied by a tenant's zcfgs.
> 6. The optimizer uses zcfgs for [locality-aware
>    planning](https://github.com/cockroachdb/cockroach/blob/692fa83ce377c86cf1b6f865a7583a383c458ce2/pkg/sql/opt_catalog.go#L455-L466).
> ```

nit: consider using "reference style links" which allows you to put long URLs at the bottom to not break the textual flow. https://www.markdownguide.org/basic-syntax/#reference-style-links 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4STjDwz-U2zTiHfK:-Mbv4STjDwz-U2zTiHfL:b-3zl68f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L145)):*
> ```
> When KV decides to promote a given SQL zcfg to a KV one
> ```

I find this language confusing. Isn't it SQL that promotes its zone configs to a KV one via the reconciliation process?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv6MTB1bi1WdtjYRXl:-Mbv6MTB1bi1WdtjYRXm:blm4e7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L282)):*
> ```Markdown
> about it.
> 
> ## Reconciliation between SQL and KV zone configs
> ```

I think this section could use some more tightening in terms of what actually happens upon rangefeed event. I think I'd break this down into various levels of sophistication that an implementation could take on.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv5qQW4ZhEJoG4RuDf:-Mbv5qQW4ZhEJoG4RuDg:bq1kmwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L617)):*
> ```Markdown
> - For sequences, we might want them to be in the same ranges as the tables
>   they're most frequently used in tandem with. Now that we're not
>   unconditionally splitting on tenant boundaries, we could be smarter about
> ```

s/tenant/table/?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 619 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv5yHi41PM8qDm9Rn9:-Mbv5yHi41PM8qDm9RnA:b8xw7zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L619)):*
> ```Markdown
>   unconditionally splitting on tenant boundaries, we could be smarter about
>   this.
>   - For the host tenant we also unconditionally split around the sequence
> ```

One reason I don't think the sequences matter as much is that they are non-transactional; there's no missed 1PC here. 


<!-- Sent from Reviewable.io -->

2021-06-11 22:11 UTC, irfansharif reviewed
> What if we called the new KV-level config a "span config" (scfgs), as you do in the API? 

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mbx76pT1mrEFG8Wegju:bhlfcaf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv3rhF5OXQdbUMWIfq:-Mbx79dG7pQLlESQQ_b2:bydxw1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L117)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: consider using "reference style links" which allows you to put long URLs at the bottom to not break the textual flow. https://www.markdownguide.org/basic-syntax/#reference-style-links 
</blockquote></details>

Nice, TIL. Done.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4STjDwz-U2zTiHfK:-MbwhIEg-7FRiyU5jwAX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L145)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> When KV decides to promote a given SQL zcfg to a KV one
> ```

I find this language confusing. Isn't it SQL that promotes its zone configs to a KV one via the reconciliation process?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-11 22:13 UTC, irfansharif commented
@dt, it'd be useful to have you sanity check the "backup/restore considerations section", talking about how zcfgs would be backed-up/restored (tl;dr -- maintaining the same semantics today around db/table restores vs. full cluster restores).

2021-06-11 23:03 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, and @irfansharif)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-MbwzY7gBVCmqPXCiJnU:b-je71j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The fact that replication reports, the mechanism by which we understand whether zone configs are fulfilled etc could feature here. 
</blockquote></details>

This does raise an interesting question about what source of truth the replication reports should consult in this new world. The decomposition here creates room for kv to be in conformance with a kv-zcfg but for the kv-zcfg to be lagging behind the corresponding sql-zcfg. Is this considered "conformance"? Probably not. But then we either need conformance reports to be aware of sql-zcfgs or for "conformance" to be redefined as a conjunction between kv-cfgs being in conformance and coherence between the kv-zcfgs and sql-zcfgs. How does this impact the UX of conformance reports?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4STjDwz-U2zTiHfK:-Mbx2RcNDSZ6U1d7t8BR:bfifxhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L145)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> When KV decides to promote a given SQL zcfg to a KV one
> ```

I find this language confusing. Isn't it SQL that promotes its zone configs to a KV one via the reconciliation process?
</blockquote></details>

Agreed. I think this should say "When KV is told to ..."
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx2aDz37aYD_yldfx4:-Mbx2aDz37aYD_yldfx5:batq41z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L152)):*
> ```Markdown
> etc).
> 
> TODO: Create a diagram for this overview?
> ```

This would be very helpful
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx32JQ4lX56obb_E9_:-Mbx32JQ4lX56obb_E9a:b-tabpda) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L191)):*
> is later considered by KV

This is hitting the same confusion as above. We should re-word to make the initiator of the action more clear.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx47z0EgDB0Padd2PN:-Mbx47z0EgDB0Padd2PO:br8m9u5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L230)):*
> ```Markdown
> sub-zone in the parent table's zone config. Storing sql-zcfgs in descriptors
> allows us to get rid of the concept of subzones, an index/partition's zcfg can
> be stored in its own descriptor (this is not in the critical path for this RFC).
> ```

IndexDescriptors are stored within TableDescriptors. Are you suggesting that we split them out and give indexes unique IDs? Or just that the IndexDescriptor proto will be given its own SQLZoneConfig field and the reconciliation loop will know how to walk through all possible sql-zcfg locations in a given TableDescriptors?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx4mbA1qa70MVGv5fL:-Mbx4mbB4b3ZHJDpDkp4:b-mwuv5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L235)):*
> ```
> slightly larger
> ```

Only if a zone is actually set on a given descriptor, right? Otherwise the encoding will be identical and we'll pay a mere 8 bytes for the pointer?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5LPW6JLfzc2DC2QX:-Mbx5LPW6JLfzc2DC2QY:b-6qgbue) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L245)):*
> ```Markdown
> [pseudo](https://github.com/cockroachdb/cockroach/blob/ce1c68397db8ebc222ed201fef1f9ca92485ddcd/pkg/keys/constants.go#L379-L385)
> descriptor IDs allocated for them. We'll ensure that all instances where we
> deal with the set of descriptors work with these placeholders. This change will
> ```

Out of curiosity, do we expect the logic necessary to deal with these pseudo-descriptors to be more or less invasive than the logic to deal with the old psuedo-zones?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5wUm5rvUHO4-Vhmf:-Mbx5wUm5rvUHO4-Vhmg:b3eovux) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L272)):*
> ```Markdown
> convenient way to determine what zcfgs apply to a given key/key-range, and also
> helps us conveniently answer what all the split points are: the set of all
> `start_key`s.
> ```

Are we planning on creating a kv-zcfg for all tables in the system tenant? If not, will we no longer mandate splits between their tables?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx8ROI-LQK3jUFW9ux:-Mbx8ROI-LQK3jUFW9uy:bk0953l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L317)):*
> ```Markdown
> 
> The reconciliation loop will only update mismatched entries in kv-zcfgs through
> a streaming RPC, with KV maintaining a txn on the other end. The streaming RPC
> ```

KV will hold open a transaction while waiting on input from SQL? That may not be the best idea, as it means that SQL could hold resources in KV indefinitely. It's probably better to replace a streaming RPC with a batched RPC, where the lifetime of the corresponding txn on the KV side never outlives a single batch.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx9HPWB1SOPf0mBohY:-Mbx9HPWB1SOPf0mBohZ:b-wx4pao) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L351)):*
> ```Markdown
> to what was provided. If the pod finds that the counter was incremented from
> underneath it, it must be the case that another pod acquired the lease from
> underneath it (we'll abandon the reconciliation attempt).
> ```

Want to add this counter to the protos above?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxA7xt8-AfOOIjfxlK:-MbxA7xt8-AfOOIjfxlL:b-vx2us0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L383)):*
> ```Markdown
> `system.span_configurations` directly. The store could also periodically
> persist this cache (along with the resolved timestamp); on restarts it would
> then be able to continue where it left off.
> ```

This section could use a little more detail about the consistency model we expect to expose to clients of the SpanConfig interface. Will updates to spans always be seen in order? Are we using rangefeed checkpoints to guarantee this? Do we no longer need to provide [...]

2021-06-14 03:43 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @irfansharif, and @nvanbenschoten)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-Mc7aqyV3YfzR_T8XI6H:b1z3d2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This does raise an interesting question about what source of truth the replication reports should consult in this new world. The decomposition here creates room for kv to be in conformance with a kv-zcfg but for the kv-zcfg to be lagging behind the corresponding sql-zcfg. Is this considered "conformance"? Probably not. But then we either need conformance reports to be aware of sql-zcfgs or for "conformance" to be redefined as a conjunction between kv-cfgs being in conformance and coherence between the kv-zcfgs and sql-zcfgs. How does this impact the UX of conformance reports?
</blockquote></details>

My current thinking is that for the user (and, to some extent, to not break backwards compatibility) that they should be in terms of SQL zone configs (as they are today) and then we should provide sufficient visibility into understanding what might be going wrong telling KV about the configs. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5wUm5rvUHO4-Vhmf:-Mc7W7q1Dcq3wxGyrAyi:bb5dhp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we planning on creating a kv-zcfg for all tables in the system tenant? If not, will we no longer mandate splits between their tables?
</blockquote></details>

I think that'd be the idea. Or at least, it's one or the other and I'd hope we'd start with the more conservative approach. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc7X1j73wlpOeBLfL3G:-Mc7X1j80Jd-cZh_sudb:bfidfi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L286)):*
> ```Markdown
> In multi-tenant CRDB, each active tenant has one or more SQL pods talking to
> the shared KV cluster. Every tenant will have a single "leaseholder" SQL pod
> responsible for asynchronously<sup>[3](#f3)</sup> reconciling the tenant's
> ```

What if we made the protocol semi-synchronous. It seems reasonable for operations which change zone configs to be able to wait for the relevant reconciliation event and to learn about any possible failures to reconcile? This could be a reasonable use case for an "outbox" of our own. Here's a straw-man sketch of what I have in mind.

```sql


CREATE TABLE system.zone_config_checkpoint (
    k BOOL AS (true) STORED PRIMARY KEY, -- cheeky way to say it's a single row
    lease BYTES,
    checkpoint DECIMAL,
)

CREATE TABLE system.zone_config_events (
    -- have not decided the right primary key here.
    -- could do it as a singleton, probably better not to.
    descriptors INT[]
)

CREATE TABLE system.zone_config_reconciliation_errors (
    timestamp DECIMAL,
    id STRING -- some sort of ID that will help the user
    error STRING -- some error
)
```

The leaseholder registers itself in the first table and then update it with checkpoints when something happens or, periodically, based on checkpoints. The writers of new configs will write the relevant descriptors to the "events" table, which is an "outbox" as people are using that word these days. Then, when reconciliation happens, if any errors occur, they can be written to the errors field. We could imagine having all the nodes watching the checkpoint and errors table and learning about any errors. A nice thing here is that we can bound what needs to get reconciled and we know how caught up we are. Also, we can make sure only the leaseholder moves the checkpoint.

There are other similar approaches to get at the same thing. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx8ROI-LQK3jUFW9ux:-Mc6Rx5iDQGZTsWcqONN:b7k6h4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

KV will hold open a transaction while waiting on input from SQL? That may not be the best idea, as it means that SQL could hold resources in KV indefinitely. It's probably better to replace a streaming RPC with a batched RPC, where the lifetime of the corresponding txn on the KV side never outlives a single batch.
</blockquote></details>

I like that approach. Importantly; I don't think we should ever, in this scheme, need to send a large batch to ensure we have safe updates of the config. It'd be good to lay out what are the safety properties here. In the past we've said that we would like it to be the case that keys in KV always have a config that at some point did indeed apply to them. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx9HPWB1SOPf0mBohY:-Mc7_TGBEzcADw1blmZG:b-genj1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L351)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Want to add this counter to the protos above?
</blockquote></details>

This counter smells a bit to me. I think it needs some further justification. On the whole, this section feels like the area we should most focus on sharpening. Let's understand tradeoffs between fully async and semi-sychronous reconciliaition. Let's understand the difference between partial and full reconciliation. Do we need to run full reconciliation in normal operation? Is it just a sanity check? 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxBrY9-CJtUNM7iQu4:-Mc6SMSyAsex0A57f8Ll:b-u6c4e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L442)):*
> whether their SQL pod will just spin indefinitely trying in vain to update the corresponding kv-zcfg and repeatedly being rejected.

This better not happen. We should not be trying more than once. We should think through the various ways the reconciliation loops responds to KV feedback. Another question is what can operators do to adjust span configs while tenants are not changing anything? 

We need to nail down reconciliation as well as the things that can happen when SQL tells KV about changes. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxH3hj-VcG036u0Ofj:-Mc7_sN0-RjJ64iclYW7:b8xowqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L546)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

@ajwerner do you think this table needs a stable ID?
</blockquote></details>

I don't know about need, but not having a stable ID is likely to mean needing to instead plumb in some container and do a lookup at startup or something. I'd prefer if we did. 
___
*[docs/RFCS/20210610_tenant_zo [...]

2021-06-14 14:21 UTC, ajstorm reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @irfansharif, and @nvanbenschoten)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-Mc9_v6n5S8TCr8C37LG:b-38d1q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My current thinking is that for the user (and, to some extent, to not break backwards compatibility) that they should be in terms of SQL zone configs (as they are today) and then we should provide sufficient visibility into understanding what might be going wrong telling KV about the configs. 
</blockquote></details>

Is the plan that we'll address this UX issue in this RFC (and the first drop of this functionality in 21.2)?  If so, we might need to add a new section to this RFC (unless I've missed something).
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxBrY9-CJtUNM7iQu4:-Mc9o2iX29NoWva4nLXN:baaogob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L442)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> whether their SQL pod will just spin indefinitely trying in vain to update the corresponding kv-zcfg and repeatedly being rejected.

This better not happen. We should not be trying more than once. We should think through the various ways the reconciliation loops responds to KV feedback. Another question is what can operators do to adjust span configs while tenants are not changing anything? 

We need to nail down reconciliation as well as the things that can happen when SQL tells KV about changes. 
</blockquote></details>

+1 for surfacing errors synchronously.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxGKfq2SA1ed54ictP:-Mc9oxXL2PJEaunyf-Hi:bktqgvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L517)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this what we want? I can see an argument that the decoupling of sql-zcfgs and kv-zcfgs allows us to accomplish what we've wanted all along, which is to retain table-level and database-level zone configurations across backups. We would hold on to them in the backup descriptor, and then run the reconciliation loop upon restore to install them. Perhaps @dt could add some color here?
</blockquote></details>

I agree.  We'd likely need to do some light validation to ensure that the zcfg can be applied to the target cluster, but if that validation passes, I'd imagine we'd want to keep the zone configs in the backup image.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxIeTk25GsIWTJQCLz:-Mc9rekU4mX3mfMk1keN:b7r7c78) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L650)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"secondary tenants"

This is a good question. I'm curious to hear @ajstorm's thoughts on the matter.
</blockquote></details>

That would certainly be my preference.  Do we think that this proposal gets us all the way there though?  Do we anticipate that tenants may want/need to set `gc.ttlseconds`?  Range limits?  Replication factor?  I'd imagine in the near term we're going to have to leave open the ability to set zone configs.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9bN6fCOfEqqpeJYCi:-Mc9bN6fCOfEqqpeJYCj:b-n7evx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L159)):*
> ```Markdown
> 
> With multi-tenant zone configs, it's instructive to start thinking about "SQL
> zone configs" (just zcfgs) and "KV span configs" (abbrev. scfgs) as two
> ```

Nit: might just be me, but I worry that people might get confused with `scfgs` as the `s` could be interpreted as referring to SQL.  Does it make sense to be slightly more verbose and go with zonecfgs and spancfgs?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9c7le0HtF1Ct6FZPb:-Mc9c7le0HtF1Ct6FZPc:b-mekwrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L183)):*
> ```Markdown
> it. Given its coupling to SQL descriptors, KV ends up also (unwillingly)
> adopting the same inheritance complexity found in SQL. This needn't be the
> case. Introducing a level of indirection will help us prevent tenants from
> ```

Nit: It may not be immediately obvious to the reader why we'd want to prevent zone config changes from being immediately applied.  You might want to add a bit of additional context to explain.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc7VhgD2AiGNieh-BYL:-Mc9eDMwC3Uxs1gsynvI:b-46247u) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L197)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My sense is this migration and this part of the RFC stands alone and can be a separate RFC altogether. Proposing this change at the same time complicates this document a lot. I think this change is also good, but, more or less, seems independent. That RFC can say that this change is only possible because we will no longer rely on system.zones. 
</blockquote></details>

+1.  Another option is to just move this paragraph further down in the RFC.  It hurts readability to open the "Storing..." section with a description of the optimizer's needs as we'd need to store the `zcfg` in the descriptor regardless.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9gIL06hipjG_vY7Il:-Mc9gIL06hipjG_vY7Im:b-xtb47z) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L239)):*
> ```Markdown
> For distinguished zcfgs (`RANGE DEFAULT`, `RANGE LIVENESS`, ...), now that
> we're storing them in descriptors directly, we'll want to synthesize special
> descriptors also stored in `system.descriptor`. Conveniently, they already have
> ```

Do we really need to synthesize these?  Can we not have the defaults encapsulated in the code?  Or are we worried about the need to migrate defaults at some point down the road?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9iOHx8BKFWsnjp8tp:-Mc9iOHx8BKFWsnjp8tq:bde0fmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L294)):*
> ```Markdown
> apply to each one. To do so, we'll recurse through the set of SQL descriptors
> (within `system.descriptors`), capture their keyspans, and materialize a scfg
> for each one by applying inherited attributes following parent links on the
> ```

Am I reading this correctly in that we're going to scan _all_ descriptors for a given tenant whenever there's any change?  Or will the rangefeed only point to descrip [...]

2021-06-14 15:05 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @irfansharif, and @nvanbenschoten)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 230 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx47z0EgDB0Padd2PN:-Mc9of3u4KFMm5UpK4ks:bdo5vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L230)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

IndexDescriptors are stored within TableDescriptors. Are you suggesting that we split them out and give indexes unique IDs? Or just that the IndexDescriptor proto will be given its own SQLZoneConfig field and the reconciliation loop will know how to walk through all possible sql-zcfg locations in a given TableDescriptors?
</blockquote></details>

The latter -- we would store zcfgs on Index/Partition descriptors. This could reduce some of the complexity around subzone spans that exists today. This isn't in the critical path however. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx4mbA1qa70MVGv5fL:-Mc9qw5-4kYfpCEwXvEO:b-7xixaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> slightly larger
> ```

Only if a zone is actually set on a given descriptor, right? Otherwise the encoding will be identical and we'll pay a mere 8 bytes for the pointer?
</blockquote></details>

Yup! 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5LPW6JLfzc2DC2QX:-Mc9wEol3RSnr9uOOsla:buvun2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L245)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, do we expect the logic necessary to deal with these pseudo-descriptors to be more or less invasive than the logic to deal with the old psuedo-zones?
</blockquote></details>

I think it'll end up being less invasive. Today, KV has to check if a key matches one of these special ranges and if it does, we translate it to a pseudo zcfg ID assigned to that range. We won't need to do this anymore once we introduce the `system.spans_configuration` table. 

We'll still have to seed `system.descriptors` similar to how we seed `system.zones` today. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9gIL06hipjG_vY7Il:-McA-EpA5eV0qtYkfcjx:b-rn041z) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L239)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we really need to synthesize these?  Can we not have the defaults encapsulated in the code?  Or are we worried about the need to migrate defaults at some point down the road?
</blockquote></details>

I think the system tenant is allowed to change zcfgs on these ranges so we'd need to store them on disk. We have code that generates defaults for these today which we'll re-use to seed these pseudo-descriptors. 


<!-- Sent from Reviewable.io -->

2021-06-15 01:00 UTC, otan commented
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McC1kxu1LvubAoSON04:-McC1kxu1LvubAoSON05:bpeacze) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L442)):*
> ```Markdown
> set of zcfgs have been fully applied, or to wait until a zcfg has.
> 
> In the short term, to surface possible errors, we'll make use of in-memory
> ```

(small comment) at the very least can this be written out to logs so e.g. an oncall can look at the issues historically?


<!-- Sent from Reviewable.io -->

2021-06-22 19:30 UTC, irfansharif reviewed
Following recent discussions, I've updated RFC to incorporate a few significant changes. Some of the comments below no longer apply, and some responses too are stale (but included for posterity). The changes are:

- Moving the whole "stash zcfgs in descriptors" section to future work. It's not necessary for the MVP, and the original motivation for it (the optimizer wants a cache of zcfgs) can be more easily served by a dedicated cache, instead of the larger undertaking that stashing zcfgs in descriptors would entail. This also punts the backup/restore discussions around whether or not we should capture zcfgs in backup images to future work.
- Doing some conservative, best-effort limit checking before committing zcfgs/schema changes. Instead of surfacing reconciliation errors, it'd be better if we could prevent committing the bound-to-rejected changes, and I think we can. This drastically reduces the likelihood that we'll get into the scfgs-rejected-by-kv state being discussed below, which also de-emphasizes the need to synchronously return the reconciliation errors as part of the user txn committing zcfgs/schema changes.
- "Jobs"-ify the execution of the reconciliation loop, using the existing infrastructure for checkpointing, observability, and leasing.
- Clarify more of the reconciliation protocol, and eliminate the need to hold O(descriptors) objects in memory. The reconciliation should be "fully paginated" now, PTAL.

> Dismissed @ajwerner from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mcp91q4AmxSPdDyU89J:b-bzaxmg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @irfansharif, @nvanbenschoten, and @otan)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-Mcp4Yxw-ppGha3Gj-0k:b-ml1maq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is the plan that we'll address this UX issue in this RFC (and the first drop of this functionality in 21.2)?  If so, we might need to add a new section to this RFC (unless I've missed something).
</blockquote></details>

I've re-worked some ideas around how likely it is we're going to run into rejected-by-kv errors, which should lower the urgency of fleshing out full conformance observability in the MVP. It's still very important, and I've added some text in the Introspection section below highlighting the need to consider both kinds of conformance ("scfgs are conformed to" and "zcfgs have been successfully reconciled"). I'm curious to hear your thoughts on how much of it is work we can pick up post 21.2, and possibly backport.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4STjDwz-U2zTiHfK:-McA1FWV-Yw5Q4wTrtim:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L145)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Agreed. I think this should say "When KV is told to ..."
</blockquote></details>

Done.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx32JQ4lX56obb_E9_:-McBOeGu6XcNqUH2Rava:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> is later considered by KV

This is hitting the same confusion as above. We should re-word to make the initiator of the action more clear.
</blockquote></details>

Done.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5wUm5rvUHO4-Vhmf:-McAWaUlEurJSaBHHubj:bpkdaqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L272)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think that'd be the idea. Or at least, it's one or the other and I'd hope we'd start with the more conservative approach. 
</blockquote></details>

Yup, we'd be creating a scfg (previously kv-zcfg) for all tables in the system tenant. As for whether or not we split on table boundaries for the host tenant, see text below:

```
We'll post-process this list of non-overlapping spans-to-scfgs to coalesce
adjacent spans with the same effective scfg. This will reduce the number of
splits induced in KV while still conforming to the stated zcfgs. It's worth
noting that this is not how things work today in the host tenant -- we
unconditionally split on all table/index/partition boundaries even if both
sides of the split have the same materialized zcfg. We could skip this
post-processing step for the host tenant to preserve existing behavior, though
perhaps it's a [desirable improvement][66063]. 
```
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 282 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv6MTB1bi1WdtjYRXl:-McGpQjH5cWh1wNyKre1:bzdndbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L282)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this section could use some more tightening in terms of what actually happens upon rangefeed event. I think I'd break this down into various levels of sophistication that an implementation could take on.
</blockquote></details>

I've given this a first pass, being a bit more specific with the protocol itself. Are there details you think are still missing? I feel like I've made the organization here a bit more difficult to follow by breaking it up so finely, so I'd happily take suggestions for how to organize this better.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc7X1j73wlpOeBLfL3G:-Mcp6Sh33158_wokNRYO:b-evmpsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L286)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What if we made the protocol semi-synchronous. It seems reasonable for operations which change zone configs to be able to wait for the relevant reconciliation event and to learn about any possible failures to reconcile? This could be a reasonable use case for an "outbox" of our own. Here's a straw-man sketch of what I have in mind.

```sql


CREATE TABLE system.zone_config_checkpoint (
    k BOOL AS (true) STORED PRIMARY KEY, -- cheeky way to say it's a single row
    lease BYTES,
    checkpoint DECIMAL,
)

CREATE TABLE system.zone_config_events (
    -- have not decided the right primary key here.
    -- could do it as a singleton, probably better not to.
    descriptors INT[]
)

CREATE TABLE system.zone_config_reconciliation_errors (
    timestamp DECIMAL,
    id STRING -- some sort of ID that will help the user
    error STRING -- some error
)
```

The leaseholder registers itself in the first table and then update it with checkpoints when something happens or, periodically, based on checkpoints. The writers of new configs will write the relevant descriptors to the "events" table, which is an "outbox" as people are using that word these days. Then, when reconciliation happens, if any errors occur, they can be written to the errors field. We could imagine having all the nodes watching the checkpoint and errors table and learning about any err [...]

2021-06-23 12:29 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @dt, @irfansharif, @nvanbenschoten, and @otan)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-McspOtb2BdS89417XUJ:b-m56y8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I've re-worked some ideas around how likely it is we're going to run into rejected-by-kv errors, which should lower the urgency of fleshing out full conformance observability in the MVP. It's still very important, and I've added some text in the Introspection section below highlighting the need to consider both kinds of conformance ("scfgs are conformed to" and "zcfgs have been successfully reconciled"). I'm curious to hear your thoughts on how much of it is work we can pick up post 21.2, and possibly backport.
</blockquote></details>

I'm most concerned that we have a feasible design sketched out for the limit enforcement.  Once we have that (and the necessary tables to support such a design) in 21.2, I'm fine with backporting the enforcement logic.

Note that I still have an open comment on the precise mechanism of the limit enforcement.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxGKfq2SA1ed54ictP:-Mcsoxb-BtmwbMQYki4t:bewkc9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L517)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Made a note of this. Do you reckon this is necessary for the 21.2 MVP however? I'd try and gently push back if so, there's already a fair number of moving parts to power through until stability. How do backup/restores with MR schemas work today? Do we re-generate zone configs post-restore? Given the zcfgs, going forward, will be captured as part of the descriptors, we could introduce the "re-apply zcfgs on restored image" behaviour in 22.1. What do you think?

---

Actually, having removed the "stash configs in descriptors" portion of this RFC from the critical path, this all gets relegated to future work that's now possible.
</blockquote></details>

Relegating this to the future makes sense to me.  It was never the core focus of this work anyway.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9nDen-JcNRhjQvn_C:-Mcsn80n-u0_zBgHlp4A:b-9bh5ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L416)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Maximum for all time. Dropping tables/indexes/partitions would help, yes, and so would removing explicit zcfgs from individual tables/indexes/partitions. And yes, the counter would get correctly decremented using this same reconciliation machinery.
</blockquote></details>

Is it possible to briefly explain how this accounting works?  In the per-tenant limits section above you talk about how SQL is going to be transactionally querying the limits table.  Would we also need KV to be writing the actual span configs number to this table?  If so, does that imply "reserved" and "committed" fields in that table?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mcskp9yE-maUmQa0RLR:-Mcskp9yE-maUmQa0RLS:b-s34e9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L269)):*
> ```Markdown
> consult this table for enforcement and update it if accepted. We'll start off
> simple, with a fixed maximum allowed number of tenant-defined splits. If the
> proposed set of scfgs implies a number of splits greater than the limit, we'll
> ```

To get the resultant split count, will we be consulting KV?  I'd think we'd have to, as SQL alone wouldn't know how many splits a given change will cause (because of the impact to neighbouring ranges).  Or perhaps I'm missing something.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McslN5I9sH8YZFr30eg:-McslN5JCFH10BapXuzz:b-yn6y2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L439)):*
> ```Markdown
> Given the client is able to send "batches" of diffs, each executed in its own
> txn, makes it possible for us exceed the per-tenant limit part-way through
> reconciliation even if at the end we would've been well under it. We'll choose
> ```

What does "not do anything about it" here mean?  That we'll discard these reconciliation attempts?  That we'll retry indefinitely?  If all of these diffs occurred in separate transactions at the SQL level, is it possible to order the diffs such that all of the split count decreases occur before we invoke split count increases?  I'd think that could help keep us under the limit.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 495 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McsjeWr1wwR012ZHdC1:-McsjeWr1wwR012ZHdC2:bk4ju1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L495)):*
> ```Markdown
> We'll instead perform a best-effort limit check using the `GetSpanConfigLimits`
> RPC before committing the DDL/zcfg change, ensuring that we'd be well under it,
> and aborting the txn outright if we aren't.
> ```

Nit: Might be too detailed for this RFC, but I'm personally interested in learning more about "ensuring that we'll be well under it".  How will we ensure this in the presence of multiple concurrent transactions creating szcfgs on behalf of a single tenant?


<!-- Sent from Reviewable.io -->

2021-06-23 13:40 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @irfansharif, @nvanbenschoten, and @otan)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 487 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McpnIt40exGkkhKrg4T:-McpnIt55W4mWOiU-Y3z:b-f1dmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L487)):*
> ```Markdown
> 
> For the new `system.span_configurations` table, we'll create it through a
> startup migration. For the rest, we'll use the long-running migrations
> ```

What's the value in a startup migration? I'm pretty sure we're stuck just using the long-running migrations for table changes these days. Startup migrations are on their way out. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxHe7KDO9Gd7i_scIO:-Mcpng072FngijnoN_aO:b-n2llb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L546)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Added to https://github.com/cockroachdb/cockroach/issues/66390.
</blockquote></details>

This raises an interesting idea -- should rangefeed enablement be a property of the zone config? 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McsqWAy8ucXpnftENq4:-McsqWAy8ucXpnftENq5:bnj1e8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L288)):*
> ```Markdown
> 
> When acquiring the lease, the pod will first establish a rangefeed over
> `system.descriptors`. Following a catch-up scan and then following every
> ```

also needs a rangefeed over system.zones.

One thing I want to introduce is that we have an abstraction for CDC that is similar to what you're looking for: https://github.com/cockroachdb/cockroach/blob/aee37412a1998ead1964a20859f114861a6f2654/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L42-L68

We could extend the event taxonomy to include zone config changes. This would be a nice mechanism for modularization. 
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McslN5I9sH8YZFr30eg:-McstnAf1Ra8wh8YE8SY:bq7xjk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L439)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

What does "not do anything about it" here mean?  That we'll discard these reconciliation attempts?  That we'll retry indefinitely?  If all of these diffs occurred in separate transactions at the SQL level, is it possible to order the diffs such that all of the split count decreases occur before we invoke split count increases?  I'd think that could help keep us under the limit.
</blockquote></details>

Yesterday we had a really nice discussion about limits and the possibility for the writing tenant to reserve the resources it will use *before* writing a config change. The more I think about it, the more I like that approach. @ajstorm made the good point that the decision for cockroach to just throw away some desired splits later seems incredibly hard to communicate; instead the rule might just be that if the operator wants to get rid of splits due to a tenant, then they may need to just nuke the tenant. This is such a nice simplification that I'm inclined to say that we should run with it as it gives us a tool to deal with all manner of errors synchronously and pre-commit. 

So, it'd be nice to at least try to work this proposal into two phases of limits:

1) No limits, no failure, retry forever, and assume that zone configs can be converted into span configs. This is the status quo and should be all we need to move forward for an MVP for the host cluster.
2) Limits which must be reserved prior to the transaction commit. 
  * Lots of question here:
      * What do we limit?
          * Number of splits? Bytes in the configs?
      * Where are the limits stored?
          * Are they per-tenant?
      * Where are the values stored?
          * for this and above I could see carving out part of the unaddressable keyspace in the `span_configs` table and either putting another field or making the proto a `oneOf`. 
      * How do we reserve capacity?
      * How do we free reserved capacity that doesn't get used?

All of these seem like things we can deal with. For example, we can just accumulate the worst case cost of applying some zone config and reserve that.  Such a greedy solution might mean that if you've used more than half of your budget then you cannot update everything in one go. That'd be an edge case but I have a feeling we could deal with it with more sophisticated approaches like checking to see what will be freed when overwriting things. 

As for the reservations, I could see a mechanism whereby we lease budget to a pool on a node using the node's session. That way, if something doesn't get used, then it can be cooperatively returned or, if the node dies, it can be revoked. The user transaction then can, in its transaction, take from the node's budget as part of the transaction. There are different schemes for taking from that budget which incur different levels of contention -- having the transactions actually touch the node-level limit (this has some deadlock issues), having the transaction write out an entry that uses some of the limit and then having the acquiring transactions read all of the used values (this has contention problems too). 


<!-- Sent from Reviewable.io -->

2021-06-23 13:41 UTC, ajwerner reviewed
I'd love a high level sketch of some go packages and interfaces. What interfaces will reconciliation hold onto? What new interface will `kvserver` use? Sketching out the pieces will lead to more harmonious development with better testing and clearer boundaries. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mct5QSo3uYetxKKG6gE:b-z027fm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @irfansharif, @nvanbenschoten, and @otan)



<!-- Sent from Reviewable.io -->

2021-06-24 01:10 UTC, awoods187 reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @ajwerner, @dt, @irfansharif, @nvanbenschoten, and @otan)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx2aDz37aYD_yldfx4:-McvXB-p0rThuE9nixc6:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This would be very helpful
</blockquote></details>

+1
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McvXcBg6ssBDUl--kDu:-McvXcBg6ssBDUl--kDv:b-jgeb7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L167)):*
> ```Markdown
>    objects and the corresponding attributes. Updating a zcfg does not guarantee
>    the update will be applied immediately, if at all (see the discussion around
>    [declared vs. applied zone configs](#declared-vs-applied-zone-configs)).
> ```

I understand the not immediately part but I don't understand why "if at all"
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McvYOqZ04HndzIhcnrV:-McvYOqZ04HndzIhcnrW:bjz0bdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L426)):*
> ```Markdown
> 
> With the introduction of per-tenant zcfg limits, it's possible for a tenant's
> proposed set of zcfgs to never be considered by KV. Because the reconciliation
> ```

I think this is problematic for data-domiciling use cases--particularly if this never errors back to the client. We need to be able to answer the current state of data placement and the desired state, and report back if they are not aligned. I think duration is okay because the system is processing the request--but we need to be able to complete it or return an error.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McvYkmt9TDyL-WxyNLx:-McvYkmt9TDyL-WxyNLy:b6u8o8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L463)):*
> ```Markdown
> the declared zone configs. They'll be left unharmed and can provide the same
> functionality for tenants. Some of this might bleed over into future work
> though.
> ```

It's probably worth exploring what this means for the constraint violation reports https://www.cockroachlabs.com/docs/v21.1/query-replication-reports.html#find-out-which-of-your-tables-have-a-constraint-violation


<!-- Sent from Reviewable.io -->

2021-06-24 19:13 UTC, irfansharif reviewed
Now that what's in the critical path for the MVP has been mapped out and we have consensus on the high-level, we're going to start prototyping it all in earnest. We'll use a separate short-lived branch ([`multi-tenant-zcfgs`](https://github.com/cockroachdb/cockroach/tree/multi-tenant-zcfgs), started off with #66402) to figure out what the interfaces and package boundaries should be. As we figure out what these interfaces should look like, we'll discuss them in the PRs that attempt to then introduce those abstractions in master, and then continue on master going forward. For the MVP we won't focus on limit enforcement yet; let's use the space below for what that could look like. An admission-control like scheme with leased out quotas feels aligned with other developments in CRDB (and is described here), but open to seeing if there's something better/simpler. I'll update the text after we've agreed on something.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-MczOav09vueLjt13e6n:b-dmzetp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbv4bP9AmfJgjN3TSv5:-MctoHpo-9o5GKQmnuZi:b60f5vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L95)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

I'm most concerned that we have a feasible design sketched out for the limit enforcement.  Once we have that (and the necessary tables to support such a design) in 21.2, I'm fine with backporting the enforcement logic.

Note that I still have an open comment on the precise mechanism of the limit enforcement.
</blockquote></details>

I'll resolve this comment thread in favor of the one below discussing the possible limit enforcement mechanisms. One thing I've done with this RFC is strip out the implementation strategy/timeline, given that so much is in flux and it rarely tends to age well.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx5LPW6JLfzc2DC2QX:-MctKWbk9Tiv9Zj-1Te2:by6v7d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L245)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think it'll end up being less invasive. Today, KV has to check if a key matches one of these special ranges and if it does, we translate it to a pseudo zcfg ID assigned to that range. We won't need to do this anymore once we introduce the `system.spans_configuration` table. 

We'll still have to seed `system.descriptors` similar to how we seed `system.zones` today. 
</blockquote></details>

This discussion is no longer relevant, all work to move configs into the descriptors themselves has now been bumped to a future synthetic timestamp.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 487 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McpnIt40exGkkhKrg4T:-MctNDhT5ZSR6nFTcpUy:b-x3kd2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L487)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What's the value in a startup migration? I'm pretty sure we're stuck just using the long-running migrations for table changes these days. Startup migrations are on their way out. 
</blockquote></details>

You might've been looking at an earlier revision of the doc, the PR linked that you've seen (#66402) is using the long-running migrations infrastructure to add the new table.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9bN6fCOfEqqpeJYCi:-MctKHk-Bs7DuTlAvsge:by077yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L159)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: might just be me, but I worry that people might get confused with `scfgs` as the `s` could be interpreted as referring to SQL.  Does it make sense to be slightly more verbose and go with zonecfgs and spancfgs?
</blockquote></details>

I'll keep this as is out of laziness and cause this terminology has bled out into other issues/discussions. If others still find it confusing, I'll change it up. Certainly it'll all be clearer in code.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McvXcBg6ssBDUl--kDu:-MczCuJ69EGBJvLRulsD:b-400yr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L167)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

I understand the not immediately part but I don't understand why "if at all"
</blockquote></details>

It might be the case that the committed, declared zone configs imply a number of splits greater than what the tenants are allowed to do. There's discussion in another thread below to basically guarantee that from never happening. That would remove the "if at all" clause.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 288 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McsqWAy8ucXpnftENq4:-MctMPjM2QPcvrtpxO4h:b-6aztf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L288)):*
> also needs a rangefeed over system.zones.

I think you may have been looking at an older revision on reviewable. This was mentioned below. These table events are sweet, looks applicable to us (+cc @arulajmani, who'll be touching this area).
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9nDen-JcNRhjQvn_C:-McttfTZ7xFgY-I48beM:b-mveyhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L416)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Is it possible to briefly explain how this accounting works?  In the per-tenant limits section above you talk about how SQL is going to be transactionally querying the limits table.  Would we also need KV to be writing the actual span configs number to this table?  If so, does that imply "reserved" and "committed" fields in that table?
</blockquote></details>

Merging this comment thread with the one above.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McvYOqZ04HndzIhcnrV:-MczDEMzENgYOReeC21A:ba0y60d) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L426)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

I think this is problematic for data-domiciling use cases--particularly if this never errors back to the client. We need to be able to answer the current state of data placement and the desired state, and report back if they are not aligned. I think duration is okay because the system is processing the request--but we need to be able to complete it or return an error.
</blockquote></details>

Yup, agreed. I'll merge this thread away as another instance of "don't accept zcfgs if they'll be perma rejected", that we're discussing above.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 463 at r2](https:/ [...]

2021-06-24 20:48 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc7X1j73wlpOeBLfL3G:-Mczjd87-8wUFRjEPSvd:b-8a9snk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L286)):*
> As for observability into these rejected-by-kv errors, I'm assuming we can use existing jobs infrastructure to surface in-progress state. I was light on details because I'm a bit unfamiliar with what that would look like, but I assume it's possible.

I don't think we'll be able to do this. Jobs surface errors by transitioning to the "failed" state and writing out the error to `system.jobs`. Our reconciliation task is slightly different from "regular" jobs, in that it can't be cancelled or fail. As such, my plan for the prototype is to initially start off by logging errors and swallowing them. Long term though, we probably want to persist these. I think we should persist them in a new system table instead of using the Progress payload. Mostly because building introspection on top of the progress proto sounds painful. 


<!-- Sent from Reviewable.io -->

2021-06-25 19:05 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mcskp9yE-maUmQa0RLR:-Md3TMve9hfv8hPdNdqz:bea8m2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L269)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

No, we won't need to consult KV; KV's only needed to learn about the current limit. SQL is well aware of the resultant changes because it has access to the set of descriptors/zcfgs that are changing in the SQL txn, and it has access to the current set of _committed_ descriptors/zcfgs. It can assess the impact to neighbouring ranges accordingly.
</blockquote></details>

Does this mean that we're duplicating this determination logic in both KV and SQL?  More of a nit, but would it make more sense from an abstratability perspective to have this logic exist only in KV and SQL call in to get it?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McslN5I9sH8YZFr30eg:-Md3VKxkAHK-wof652qE:bxdbs4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L439)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Merging related comments from other threads. For on-lookers I'll re-iterate that none of the following is in the critical path for the MVP; for 21.2 we can work off the assumption of no limits. We're just making sure we can have a sane story for limiting how many user declared splits (declared through zcfgs/schemas) are accepted by kv, and also having these limits be visible to the sql pods to be able to abort txns declaring new splits that could later get rejected by kv due to this limit enforcement. We want to avoid the awkward "zone config/schema is committed, but will never be accepted by kv, and is hard to recover from" state.

@ajstorm:

> Nit: Might be too detailed for this RFC, but I'm personally interested in learning more about "ensuring that we'll be well under it". How will we ensure this in the presence of multiple concurrent transactions creating zcfgs on behalf of a single tenant?

> Is it possible to briefly explain how this accounting works? In the per-tenant limits section above you talk about how SQL is going to be transactionally querying the limits table. Would we also need KV to be writing the actual span configs number to this table? If so, does that imply "reserved" and "committed" fields in that table?

Just went through @raduberinde's distributed token bucket RFC (#66436) and there are parallels there that we can learn from. Mental model: we have each sql pod for tenant `T` maintaining a pool of "local" quota drawn originally from the host tenant's "global" quota (scoped to tenant `T`). This local quota is a fractional share of the `T`'s global quota that has been effectively "leased" to each pod; the local pool is also periodically re-filled from the global one. This structure allows each pod to acquire quota from the local pool for operations it decides to issue/not issue without having to first reach out to KV. Each operation is then associated with some amount of leased quota; in the case where the operation is received by KV _after_ the quota's lease expiration, it gets accumulated as debt and is cleared by taking away from the subsequent re-fill.

The global quota, sitting on the host tenant, is the authoritative state capturing what's been leased and what's leftover and is settable only by the host tenant. We can reason about decreasing the global quota by first waiting for expiration of all leased out local quotas.  

With zone config limits, we have similar ideas in play. We have a "global" quota set per-tenant, the authoritative state found only on the host tenant, settable only by the host tenant. Where it differs is that we aren't periodically re-filling the pool. As long as a split is accepted by KV, it counts against the tenant's global limit until that split is removed. Because of this, we can't go in-debt, allowing more splits temporarily than the limit allows for; the system cannot remove existing splits to make room for others.

---

We could have each pod lease out a local quota, counting against the tenant's global limit. For N pods of a tenant, and a limit L, we could either lease out partial quotas L/N, or have a single pod lease out L entirely and require all DDLs/zcfgs to through that one pod. The scheme below describes the general case of each pod getting some fractional share of the total quota.  

- When each pod considers a DDL/zcfg txn, before committing it will attempt to acquire a quota from its local leased limit. The quota acquired is an over-estimate of how much the txn will cost (in terms of additional splits induced); we cannot under-estimate as KV could then later reject the committed zcfg.
  - If there's insufficient quota, we'll abort the txn and error out accordingly.
  - If there's sufficient quota, we'll commit the txn and rely on the eventual reconciliation to reliably succeed. We'll queue up a work item for the for the reconciliation job, marking alongside it the lease expiration of the quota it was accepted with. 
- When the local pool runs out of quota and has to request/lease more, it needs to ensure that all the txns that have been committed have been reconciled. We don't want it to be the case that a quota is leased, allocated to an operation in the work queue, it stays in the work queue past its lease expiration date, and we're able to lease the "same" quota again and queue up a second work item that will now get rejected. We need to make sure that when we lease a limit at t, there are no unprocessed work items with leased tokens expiring before t.
- Whenever the work item is processed, the amount we over-estimated by could either be returned to the local quota pool (with the same expiration ts), or we could simply drop it entirely and rely on the local quota pool to eventually re-acquire it from the global pool.

---

Another scheme to achieve similar things is to have KV grant signed tokens for use by pods. Whenever a txn attempts to introduce N splits, it will retrieve a signed token from KV that would essentially reserve the right for the pod to declare those N splits. During the reconciliation process that signature would be validated by KV, and the splits accepted if valid. When handing out tokens, we'd need to ensure that we have sufficient capacity considering the entire set of signed tokens that have not made its way back to KV yet.  

There's some trickiness in this scheme. What if a token is retrieved from KV, decrementing the available limit for future acquisitions, and is failed to be committed by the pod? We'd need a sort of two-phase scheme to actually transfer the token durably. It does however make lowering the limit simpler. We can only lower the limit from L2 to L1 as long as we haven't handed out signed tokens for quota > L1. With the leasing scheme, we'd have to first stop granting leases to tokens > L1, wait for leased tokens > L1 to expire, and finally ensure that all work-items with expired leases have been flushed out.
</blockquote></details>

This additional level of detail is helpful.  Personally, the leasing option seems more straightforward to me, as it appears to more easily handle failure scenarios (lease is acquired but is never acted upon).  The boundary conditions seem undefined though.  What happens if a lease is acquired but expires before the transaction commits (or before reconciliation occurs)?  Will we have to che [...]

2021-06-25 19:19 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mcskp9yE-maUmQa0RLR:-Md3_grGCGof52VWBDwE:b-x240uf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L269)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does this mean that we're duplicating this determination logic in both KV and SQL?  More of a nit, but would it make more sense from an abstratability perspective to have this logic exist only in KV and SQL call in to get it?
</blockquote></details>

I'm not sure. As we're prototyping to figure out the interfaces it'll be apparent to us what should sit where. Still I suspect this will still sit on the SQL side, I think this over-estimated cost is a different kind of determination than what KV is making.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McslN5I9sH8YZFr30eg:-Md3Zl1A6h9s4S25YNOa:b-yes6a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L439)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This additional level of detail is helpful.  Personally, the leasing option seems more straightforward to me, as it appears to more easily handle failure scenarios (lease is acquired but is never acted upon).  The boundary conditions seem undefined though.  What happens if a lease is acquired but expires before the transaction commits (or before reconciliation occurs)?  Will we have to check the leases on transaction commit time?
</blockquote></details>

Yup, exactly. Provided the txn commit time is less than the lease expiration time, future acquisition attempts of that particular token (would necessarily happen after expiration) would see that txn. This is similar to the txn commit deadline idea we're using for the reconciliation job's lease.


<!-- Sent from Reviewable.io -->

2021-06-29 17:40 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-MdNhYMo-ar_dyRFGjXp:b-pusjwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
This says "eschew inheritance for span configs", but the commit message says "re-implement inheritance by introducing unique IDs for each zone configuration object".
Is one wrong?


> Removing inheritance at the KV level does mean that changing the zcfg of a
parent SQL descriptor would potentially incur writes proportional to the number
of child descriptors. We think that's fine, they're infrequent enough
operations that we should be biased towards propagating the dependency to all
descendant descriptor spans. It simplifies KV's data structures, and
inheritance semantics are contained only within the layer (SQL) that already
has to reason about it.

I think doing without inheritance will become a scalability problem. Even with a medium-sized example, the write amplification gets up there: consider 100 tables with 10 indexes per table in a database partitioned across 10 regions -> that's 10k scfgs. Do I really want to update all of them to change a TTL? With inheritance, I think a lot of updates that need the pagination mechanism you describe would no longer need it.


<!-- Sent from Reviewable.io -->

2021-08-03 11:55 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-MgAr17lBeHHH9acs329:b3o3e3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This says "eschew inheritance for span configs", but the commit message says "re-implement inheritance by introducing unique IDs for each zone configuration object".
Is one wrong?


> Removing inheritance at the KV level does mean that changing the zcfg of a
parent SQL descriptor would potentially incur writes proportional to the number
of child descriptors. We think that's fine, they're infrequent enough
operations that we should be biased towards propagating the dependency to all
descendant descriptor spans. It simplifies KV's data structures, and
inheritance semantics are contained only within the layer (SQL) that already
has to reason about it.

I think doing without inheritance will become a scalability problem. Even with a medium-sized example, the write amplification gets up there: consider 100 tables with 10 indexes per table in a database partitioned across 10 regions -> that's 10k scfgs. Do I really want to update all of them to change a TTL? With inheritance, I think a lot of updates that need the pagination mechanism you describe would no longer need it.
</blockquote></details>

Friendly ping. Are you committed to the no inheritance thing?
If we had inheritance, I'm thinking there'd be zone config changes for which the reconciliation would be a simple update, not a job.


<!-- Sent from Reviewable.io -->

2021-08-03 12:32 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-MgAzBA67Yh1SFw32EzY:b-mpykzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Friendly ping. Are you committed to the no inheritance thing?
If we had inheritance, I'm thinking there'd be zone config changes for which the reconciliation would be a simple update, not a job.
</blockquote></details>

I don't see how the job and the simplicity of the update are tightly coupled. The advantage of the job is that it can deal with checkpointing how reconciled the whole thing is. I agree simpler updates would likely propagate faster and have lower cost to write at the detriment of simplicity on the KV side. I don't think it'd be impossible to move to an inheritance based scheme later. 

The first pass eschews inheritance on the KV side entirely. 


<!-- Sent from Reviewable.io -->

2021-08-03 17:13 UTC, irfansharif reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @arulajmani, @awoods187, @irfansharif, @nvanbenschoten, @otan, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-MgC--SX2D1B5wLqDCHv:b-rwoa83) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't see how the job and the simplicity of the update are tightly coupled. The advantage of the job is that it can deal with checkpointing how reconciled the whole thing is. I agree simpler updates would likely propagate faster and have lower cost to write at the detriment of simplicity on the KV side. I don't think it'd be impossible to move to an inheritance based scheme later. 

The first pass eschews inheritance on the KV side entirely. 
</blockquote></details>

Sorry to have not responded here earlier -- I'd meant to but things got out of hand. We did however discuss inheritance in our pod meetings following your prompt; here's roughly where we ended up:
- There's a single forever job running per-tenant, not a job per zone config change (not sure how to interpret "zone config changes [...] would be a simple update, not a job").
- With inheritance I don't feel the update would be "simple", we're transcribing a tree change from SQL to a corresponding tree change in KV, looking to keep both trees in sync. Earlier iterations of this RFC dabbled in introducing unique IDs per zone/span config in order for us to encode the parent-child relations in the RPC messages, but it got too unwieldy compared to the alternative outlined here. We'd also have to maintain a mapping between a tenant's SQL zone configs/descriptors to these IDs in KV. Or be smart about how these IDs are constructured. All together it felt much easier to diff two flattened out trees than diffing the trees directly.
- We're going to be capping the number of splits a tenant can maintain. Given that's proportional to the number of span configs, there's a hard limit to how large the flattened out representation of the tree can get. We care about this size for two things:
    (a) The size of the RPC payload/messages making these updates
    (b) The write amplification in KV where we store these span configs
  For (a), we're still pagination friendly. The consistency guarantees we're looking to provide lets us split off a single zone config change across multiple RPCs. For (b), it feels acceptable given there's a hard limit on how many rows we'd be storing/updating per-tenant.
  This reconciliation process is also happening asynchronously; nothing described above will be in the critical path when users set zone configs.
- Like Andrew mentioned, we could always introduce inheritance within KV afterwards, if we find a need to. Though I feel it unlikely that we would, especially given the code complexity it would necessitate.


<!-- Sent from Reviewable.io -->

2021-08-03 18:25 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-MgCDbl9-HMUSSwVO2vA:btze2rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Sorry to have not responded here earlier -- I'd meant to but things got out of hand. We did however discuss inheritance in our pod meetings following your prompt; here's roughly where we ended up:
- There's a single forever job running per-tenant, not a job per zone config change (not sure how to interpret "zone config changes [...] would be a simple update, not a job").
- With inheritance I don't feel the update would be "simple", we're transcribing a tree change from SQL to a corresponding tree change in KV, looking to keep both trees in sync. Earlier iterations of this RFC dabbled in introducing unique IDs per zone/span config in order for us to encode the parent-child relations in the RPC messages, but it got too unwieldy compared to the alternative outlined here. We'd also have to maintain a mapping between a tenant's SQL zone configs/descriptors to these IDs in KV. Or be smart about how these IDs are constructured. All together it felt much easier to diff two flattened out trees than diffing the trees directly.
- We're going to be capping the number of splits a tenant can maintain. Given that's proportional to the number of span configs, there's a hard limit to how large the flattened out representation of the tree can get. We care about this size for two things:
    (a) The size of the RPC payload/messages making these updates
    (b) The write amplification in KV where we store these span configs
  For (a), we're still pagination friendly. The consistency guarantees we're looking to provide lets us split off a single zone config change across multiple RPCs. For (b), it feels acceptable given there's a hard limit on how many rows we'd be storing/updating per-tenant.
  This reconciliation process is also happening asynchronously; nothing described above will be in the critical path when users set zone configs.
- Like Andrew mentioned, we could always introduce inheritance within KV afterwards, if we find a need to. Though I feel it unlikely that we would, especially given the code complexity it would necessitate.

</blockquote></details>

cc @pbardea @adityamaru @dt @miretskiy 

This came up right now when we're talking about protected timestamps. Namely, it would be totally amazing to be able to protect something like a database. The problem, however, is that if we set this timestamp on a database it's going to be O(N) writes to all the partitions and that might take a long time which is sort of sad. 

If we did have inheritence, this would solve many problems and make protected timestamps pretty chill. 


<!-- Sent from Reviewable.io -->

2021-09-30 04:40 UTC, RaduBerinde reviewed
Very cool RFC (I still have some portions to go through, but the overall idea is very compelling)!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-MkozjvB1mlQ4mN9O_I_:b-c5hkfu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, and @pbardea)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 291 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkoo0W_5kjB2M4vf8b1:-Mkoo0WaEw3jifzBNJKZ:bh0by90) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L291)):*
> ```Markdown
> };
> 
> message GetSpanConfigsRequest {
> ```

What happens if there are a ton of configs (split points) within this span? How can I paginate through that?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 296 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkotWsa5EOt33HMI5RR:-MkotWsa5EOt33HMI5RS:b-njp5ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L296)):*
> ```Markdown
> 
> message GetSpanConfigsResponse {
>   repeated SpanConfigEntry span_configs = 1;
> ```

These are all the spans config that overalp with the given span? So the first scfg's start key could be before the one I asked for, and similar for the last end key?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkoo8Xk7lrTfs7OcYiX:-Mkoo8Xk7lrTfs7OcYiY:beoehlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L299)):*
> ```Markdown
> };
> 
> message UpdateSpanConfigsRequest {
> ```

It's important to flesh out the details of such an API. There should be enough comments here to clarify the following questions:
 - if I try to upsert a config for a range that contains multiple existing configs, is that essentially removing some key splits?
 - if I try to delete a config for a span that starts or ends inside an existing config span, does that introduce a split?
 - I assume the upsert (and respectively delete) spans are non-overlapping.. do they also need to be sorted?
 - can delete spans overlap with upsert spans? (e.g. first delete all configs inside a tenant and recreate them)
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 357 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkovAo7BVmoO4n53bLe:-MkovAo7BVmoO4n53bLf:bu71gmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L357)):*
> ```Markdown
> 
> In multi-tenant CRDB, each active tenant can have one or more SQL pods talking
> to the shared KV cluster. Every tenant will have a single "leaseholder" pod
> ```

[nit] We should avoid reusing the term leaseholder since that already has a very clear use in our system. Could be SQL leader/coordinator/supervisor.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-McslN5I9sH8YZFr30eg:-Mkowk4r08n7fwhXnZ6b:boqwcp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L439)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Yup, exactly. Provided the txn commit time is less than the lease expiration time, future acquisition attempts of that particular token (would necessarily happen after expiration) would see that txn. This is similar to the txn commit deadline idea we're using for the reconciliation job's lease.
</blockquote></details>

Related to limiting split points - to me split points seem most closely related to storage, in that a split should cost no more than having 500MB of data lying around (this amount would require a split anyway). So maybe a split should (from cost/limiting perspective) behave like using some fixed amount of storage (either 500MB or maybe the average range size 320MB), and have that be enforced as part of enforcing storage (which is currently done through periodic monitoring and corresponding adjustments to the available RUs, rather than hard limits).
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkoouPN1qT88XIDPJ0P:-MkoouPN1qT88XIDPJ0Q:brwbmoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L530)):*
> ```Markdown
> It's possible for a KV server to request the span configs for a key where that
> key is not yet declared in the server's known set of scfgs. The spans captured
> `system.span_configurations` are only the "concrete" ones, for known
> ```

I think things would be cleaner if the span configs would not allow "holes". Instead of span/config pairs, we would have key/config pairs, where the config applies up to the next key. Operations can always be thought of as introducing or removing split points.

When setting up a tenant, we would introduce a scfg for the tenant range. That config would be naturally retained by all the "gaps" in the key space and would act as the default until any specific scfgs for table ranges are propagated.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 706 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkosGxv632FzbmBIjey:-MkosGxwEv_V3W1M32Pr:b-atk7dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L706)):*
> ```Markdown
> the observation that most scfgs will be identical, both within a tenant's
> keyspace and across. Referring to scfgs through ID or hash would reduce the
> size of `system.span_configurations`.
> ```

I think this makes a lot of sense. The set of distinct scfgs are likely small enough to always be cached in memory. We could designate the configs as immutable and key them by a SHA of the proto which would make caching coherency trivial.


<!-- Sent from Reviewable.io -->

2021-09-30 04:53 UTC, ajwerner reviewed
@raduberinde you should know that a bunch of this has been implemented, though nothing is enable-able in the system tenant in terms of machinery without jumping through some hoops. See https://github.com/cockroachdb/cockroach/issues/67679. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mkp1oxp-wWd8HoeWxqO:b-b4ve63)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, and @pbardea)



<!-- Sent from Reviewable.io -->

2021-09-30 09:46 UTC, knz reviewed
I like this proposal, but I am surprised (worried?) that the RFC doesn't discuss fault tolerance and performance hotspots much. Some comments to that effect below.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mkq51_l-bu84IrrXWF1:b-ulvwbs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpyUn-BAjs7rIRZZa0:-MkpyUn06wP1nZeXHOnT:b-qz0iu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L154)):*
> ```Markdown
> apply a set of span configs, it will perform relevant safety checks and
> rate-limiting. Each KV server will establish a range feed over the keyspan
> where all span configs will be stored. Whenever there's an update, each store
> ```

What was the rationale for choosing a single keyspan for all span configs, instead of homing the span configs "close" to the keyspace over which they apply?

Also, is there an analysis of what to do if we find a hotspot in the span config range? Presumably, a cluster with many guest tenants will see high zcfg activity due to all the DDL going on concurrently.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpzyuW7y18Queiqhv-:-MkpzyuW7y18Queiqhv0:br0zued) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L210)):*
> ```Markdown
> 
> ```sql
> CREATE TABLE system.span_configurations (
> ```

To follow up on my previous comment: I think we need to split this table, as well as `span_configurations_per_tenant` below, at tenant boundaries..
There are two reasons for this:
- we will want to avoid hotspots, which could cause DDL activity by one tenant to contend with DDL activity by another tenant. We want to design to ensure that tenants are relatively independent from each other.

- we want to design for fault tolerance: if a host system range becomes unavailable, we want to reduce the blast radius and ensures that a minimum number of tenants are affected.

by splitting these system tables at tenant boundaries, we make the tenants independent from each other and ensure that unavailability affects only the tenant configured by the unavailable range.


In a related concern, I would also suggest perhaps partitioning these tables somehow, and ensure (perhaps via a suitably defined zcfg) that each config is homed in the region closest to the "home region" for the tenant being configured. It would be awkward to have a tenant runnning in region-pacific and have the span configs homed in region-europe.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 259 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkpzl922PuS5s2cg_fw:-Mkpzl922PuS5s2cg_fx:b-utergb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L259)):*
> ```Markdown
> 
> ```sql
> CREATE TABLE system.spans_configurations_per_tenant (
> ```

nit: `spans`? why plural?
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mcskp9yE-maUmQa0RLR:-Mkq-xJ59QxTINt_QQIJ:b-12ce0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L269)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm not sure. As we're prototyping to figure out the interfaces it'll be apparent to us what should sit where. Still I suspect this will still sit on the SQL side, I think this over-estimated cost is a different kind of determination than what KV is making.
</blockquote></details>

A related concern: do we trust the SQL layer to count this right? Ideally, we'd like to avoid trusting SQL, to avoid the chance that a compromised SQL pod populate problematic scfgs in the host cluster.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkq1Q5ODObDyQY1O9N1:-Mkq1Q5P3IbKi8YT6D4E:b1xfbmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L432)):*
> ```Markdown
> have the same materialized zcfg. We could skip this post-processing step for
> the host tenant to preserve existing behavior, though perhaps it's a [desirable
> improvement][66063].
> ```

I think a provision should be made to allow zcfgs to specify "forced" splits even if adjacent configs are equivalent.
Why? For two reasons:
- fault tolerance. It's the same story as above: if one table's ranges become unavailable, a tenant may desire to preserve availability of adjacent tables.
- performance. An end-user may wish to use some of their "split budget" to make write-heavy workloads to separate tables become separate ranges so they can be split across separate leaseholder nodes.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkoouPN1qT88XIDPJ0P:-Mkq2RS6E91DJ-2iTFa-:b-5as0qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L530)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think things would be cleaner if the span configs would not allow "holes". Instead of span/config pairs, we would have key/config pairs, where the config applies up to the next key. Operations can always be thought of as introducing or removing split points.

When setting up a tenant, we would introduce a scfg for the tenant range. That config would be naturally retained by all the "gaps" in the key space and would act as the default until any specific scfgs for table ranges are propagated.
</blockquote></details>

I came to this paragraph about to write a comment with the same idea as Radu's :)
i agree that point configs are helpful. It also simplifies the introduction of new split points, by avoiding the need to rewrite existing scfgs.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 551 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkq2kMj-sgLxkJa_8pQ:-Mkq2kMj-sgLxkJa_8pR:b-qeml6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L551)):*
> ```Markdown
> ### Span config consistency guarantees
> 
> For the config applied to a given key, we can summarize it's consistency
> ```

nit: its
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 617 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mkq3OpfAnwJ8gfn0bmW:-Mkq3OpgD4TRsmsvzK6A:boqmxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L617)):*
> ```Markdown
> will still be able to set zone configs for their own `DATABASE system`, which
> only apply to the tenant's own system tables.
> ```

Arguably, a tenant's "own" entries in the host systems' system.span_config tables should be configurable to be homed in a particular region of the customer's choice. What mechanism can we offer for this?


<!-- Sent from Reviewable.io -->

2021-09-30 10:23 UTC, knz reviewed
In fact i just noticed (while looking at #70912 / #70912) that the RFC doesn't talk about data domiciliation enough (towards our GDPR compliance roadmap) see below.

Maybe the RFC should link to https://github.com/cockroachdb/cockroach/issues/70913

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-MkqC2DK7QoBSyV4lVHu:b-phpr1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkqCRf50kUofTy-ldt8:-MkqCRf50kUofTy-ldt9:b-5ecczy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L211)):*
> ```Markdown
> ```sql
> CREATE TABLE system.span_configurations (
>     start_key     BYTES NOT NULL PRIMARY KEY, -- inclusive
> ```

Also, the full data in the key may contain indexed values from the table. For compliance with data domiciliation (GDPR etc) this means that this information must be subject to the same data domiciliation rules as the corresponding partition in the table. 

So this is one more argument iin favor of splitting this table, and guaranteeing that the span configs that correspond to each table partition are homed in that table's region.


<!-- Sent from Reviewable.io -->

2021-11-12 17:29 UTC, knz reviewed
I just had a chance to discuss this with Arul, who challenged me on a couple of my comments. I am updating my comments below based on that discussion (but don't let these threads hold up further work on the MVP).

*Independently from that discussion* I am noticing many open comments that don't have an answer yet. What process are we aiming for to move the convo forward? @irfansharif I'd be curious to know what approach you'd rather take. We can discuss separately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-MoKBBFB3ou5drxqMW5w:bml35ls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @miretskiy, @nvanbenschoten, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpyUn-BAjs7rIRZZa0:-MoK6Y6g94KtjabOHb1K:ba5057l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L154)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What was the rationale for choosing a single keyspan for all span configs, instead of homing the span configs "close" to the keyspace over which they apply?

Also, is there an analysis of what to do if we find a hotspot in the span config range? Presumably, a cluster with many guest tenants will see high zcfg activity due to all the DDL going on concurrently.
</blockquote></details>

To give more color on this comment: a single span config range for all tenants, using a single rangefeed, has multiple operational problems:

- if one tenant has a bunch of zcfgs to be applied, it's going to hold up any zcfg change issued by another tenant (which will be waiting behind in the feed).
- if the one span config range becomes unavailable, then zone configs break for all tenants simultaneously.
- if the scfgs are in a different region than the tenant, range relocations will incur cross-region traffic.
- it's going to make it algorithmically less easy to bill the users (via RUs) for their scfg-allocator constraint resolutions.  (This is, interestingly, already recognized as an unresolved question at the end of the document.)

I understand that there are concerns with the alternative, which is to make the scfgs "decentralized" (see alternate section below). I'll add comments there too.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpzyuW7y18Queiqhv-:-MoKABQd3ZYi36aDR3ZT:b-b30c4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L210)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

To follow up on my previous comment: I think we need to split this table, as well as `span_configurations_per_tenant` below, at tenant boundaries..
There are two reasons for this:
- we will want to avoid hotspots, which could cause DDL activity by one tenant to contend with DDL activity by another tenant. We want to design to ensure that tenants are relatively independent from each other.

- we want to design for fault tolerance: if a host system range becomes unavailable, we want to reduce the blast radius and ensures that a minimum number of tenants are affected.

by splitting these system tables at tenant boundaries, we make the tenants independent from each other and ensure that unavailability affects only the tenant configured by the unavailable range.


In a related concern, I would also suggest perhaps partitioning these tables somehow, and ensure (perhaps via a suitably defined zcfg) that each config is homed in the region closest to the "home region" for the tenant being configured. It would be awkward to have a tenant runnning in region-pacific and have the span configs homed in region-europe.

</blockquote></details>

My interest for "distributed scfgs" notwithstanding, if we keep a single scfg table, splitting the `span_configurations` table would be an intermediate solution, that would restore a little bit of good properties:

- we would be able to home the scfg data close(r) to its tenant, to avoid cross-region traffic
- we would be able to avoid unavailability for 1 tenant affecting that of another (assuming no scfg processing operation requires full table scans), *assuming we use one rangefeed per partition*
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 530 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkoouPN1qT88XIDPJ0P:-MoK25F_8VBUSSvShs-J:b-5oyrsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L530)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I came to this paragraph about to write a comment with the same idea as Radu's :)
i agree that point configs are helpful. It also simplifies the introduction of new split points, by avoiding the need to rewrite existing scfgs.
</blockquote></details>

After discussing this with Arul, we found out that using point configs were undesirable, because it would cause a scfg for one table to automatically "leak" to every table after it in creation order that didn't get a scfg defined yet.  Given the async nature of zcfg propagation, we'd see the data for those tables (possibly, an unbounded number of them) move around as the zcfgs get incrementally applied.
It would also be semantically strange for the user to see tables appearing to be subject to zone configs that were never set on them.

(We accept that there may be transient state around a table that's undergoing a zcfg change, with both the before-state and the after-state be non-deterministically applied, however we really wish to never see a state that's not logically related to the zcfg being applied.)

Coming back to the concern that both Radu and I have (I am presuming Radu's opinion): the text of the RFC *as currently stated at the time of this writing* suggests that the fall back is a global, cluster-wide static scfg. IMHO we want to provide tenants control over the placement of data in the "holes". 
Therefore, the RFC should be updated to mention that there will be a configurable per-tenant fallback, and not a "global, static" fallback.

Arul points out that the KV layer does not currently know about tenant default scfg in this proposal. Although there is an *initial* scfg populated for each tenant, it gets split up as tables get added, and remains the scfg applicable for holes (by construction, *copies* of it remains in-between all the scfgs that were assigned by zcfgs: when a table is added, the initial scfg is duplicated into a pre-table and post-table segment, and the table scfg is inserted in-between). However, we do not have an easy way to *modify* all the copies of the initial scfg that's been propagated to the holes, after it's been split up by tables. If we want to introduce per-tenant fallbacks, we'd need an API between SQL and KV to update all the scfgs in-between those that were derived from zcfgs. This is a new mechanism that we hadn't considered to be in-scope.

TBD: discuss this in the next group meeting around this RFC.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 676 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MoK7qUHDZfj6vLRstGC:-MoK7qUHDZfj6vLRstGD:bojk25) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L676)):*
> ```Markdown
> If zone configs are spread across the keyspace, in each tenant, we'd have to
> establishing T rangefeeds per store -- which feels excessive and
> cost-prohibitive. We'd also need each store to establish rangefeeds for
> ```

"T rangefeeds per store": note that these would be mostly idle - the span con [...]

2021-11-12 18:00 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @knz, @miretskiy, @nvanbenschoten, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpyUn-BAjs7rIRZZa0:-MoKH33nB2QTPVlYb4ZV:b-rdrhcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L154)):*
> if one tenant has a bunch of zcfgs to be applied, it's going to hold up any zcfg change issued by another tenant (which will be waiting behind in the feed).

I think the answer to this should be a rate-limiting mechanism of some form on the writes to the span configs. We definitely, absolutely must have a limiting mechanism on the number of span configs per tenant. That alone doesn't prevent the problem you describe here, but it's possible that we can convince ourselves that the delay due to the largest write we'd allow of a tenant would not incur that much delay.

>if the one span config range becomes unavailable, then zone configs break for all tenants simultaneously.

Same can be said for node liveness and meta1, and, for better or for worse, the tail of `system.rangelog`. I'm not convinced at all that this is a problem. System ranges are highly available. If we aren't getting enough fault-tolerance out of them, we should bump up their replication factors.

> if the scfgs are in a different region than the tenant, range relocations will incur cross-region traffic.

Do you mean when updating them or when reading/subscribing? I'd hope that we can replicate the `system.spanconfig` table enough such that there's a full copy in every region. Rangefeeds can and do run on followers.

> it's going to make it algorithmically less easy to bill the users (via RUs) for their scfg-allocator constraint resolutions. (This is, interestingly, already recognized as an unresolved question at the end of the document.)

This is true, especially without the inheritence scheme originally proposed such that a single row write to the tenant cluster can amplify to touch many spans in the host cluster. If there was a 1:1 mapping, I wouldn't care so much. Yes we'd be off, but not by too much. There's talk of reviving the inheritence proposals, so maybe that'll come into play. More importantly, however, is that we're definitely going to need to be building limits for span configs. Ideally that conversation will take us to talk about both rates as well as absolute numbers. Assuming that limiting infrastructure can talk about rates, then we can imagine it also charging for those writes. We're not optimizing for latency when applying span configs. I could very much see a desire to have the host side implementation of the writing calls of the KVAccessor increment some RU counters somewhere. 


<!-- Sent from Reviewable.io -->

2021-12-04 06:55 UTC, irfansharif reviewed
With https://github.com/cockroachdb/cockroach/pull/71994, we've basically implemented everything from this RFC. There's sure to be some paper cuts here and there but let's merge this as done. I lightly edited the text to reflect some minor changes in our thinking where there was any; everywhere else I annotated it with the actual interfaces we settled on. Having to re-read this uber verbose text again, I'll applaud all youse patience -- this could've been a third of the size knowing what we know now. 

>  What process are we aiming for to move the convo forward? @irfansharif I'd be curious to know what approach you'd rather take

I've responded to everything and we've discussed most things in other forums. I'd sort of treated this as a dead document until now because so much legwork happened elsewhere (sorry!). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-:-Mq37n9uCFdGWPkL1jFM:be6nd6o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajstorm, @arulajmani, @awoods187, @dt, @irfansharif, @knz, @miretskiy, @otan, @pbardea, and @RaduBerinde)

___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mbx2aDz37aYD_yldfx4:-Mq2ytj56iXiC4dccNf5:b-cy9rh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L152)):*
<details><summary><i>Previously, awoods187 (Andy Woods) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done (stole it from the internal presentation a few weeks ago).
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 286 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc7X1j73wlpOeBLfL3G:-Mq2zQDDAfW3nmTMEzFG:b-otkfmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L286)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> As for observability into these rejected-by-kv errors, I'm assuming we can use existing jobs infrastructure to surface in-progress state. I was light on details because I'm a bit unfamiliar with what that would look like, but I assume it's possible.

I don't think we'll be able to do this. Jobs surface errors by transitioning to the "failed" state and writing out the error to `system.jobs`. Our reconciliation task is slightly different from "regular" jobs, in that it can't be cancelled or fail. As such, my plan for the prototype is to initially start off by logging errors and swallowing them. Long term though, we probably want to persist these. I think we should persist them in a new system table instead of using the Progress payload. Mostly because building introspection on top of the progress proto sounds painful. 
</blockquote></details>

Same as other limit related threads; tracked here: https://github.com/cockroachdb/cockroach/issues/70555.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MbxHe7KDO9Gd7i_scIO:-Mq3-Pve0yRSXxlWb6tz:b-xtoxq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2290bc9f2a8d89820633583f75d2a874c1ace211/docs/RFCS/20210610_tenant_zone_configs.md#L546)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This raises an interesting idea -- should rangefeed enablement be a property of the zone config? 
</blockquote></details>

Absolutely it should, tracked in https://github.com/cockroachdb/cockroach/issues/70614.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-Mc9pLY54hP82iF4ozJM:-Mq36_gt1l7wAplQoYVq:b-14raxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/46789256bb27247352efee0b5380d55a60b815b0/docs/RFCS/20210610_tenant_zone_configs.md#L562)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Was this added as a stub?  You've listed drawbacks throughout, which we might want to reiterate down here.
</blockquote></details>

Lazily avoiding touching the RFC text any further.
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MdNhYMo-ar_dyRFGjXo:-Mq2yWx68d6tSAdU-547:b-s5nec2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

cc @pbardea @adityamaru @dt @miretskiy 

This came up right now when we're talking about protected timestamps. Namely, it would be totally amazing to be able to protect something like a database. The problem, however, is that if we set this timestamp on a database it's going to be O(N) writes to all the partitions and that might take a long time which is sort of sad. 

If we did have inheritence, this would solve many problems and make protected timestamps pretty chill. 
</blockquote></details>

Protected timestamps for secondary tenants is coming to a ~future RFC~ theater near you!
___
*[docs/RFCS/20210610_tenant_zone_configs.md, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66348#-MkpyUn-BAjs7rIRZZa0:-Mq3-w-j2OyUaXoRpih7:b3pj0ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0d263a97137cf5d5df794aac0f0049b3cda9fe8/docs/RFCS/20210610_tenant_zone_configs.md#L154)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> if one tenant has a bunch of zcfgs to be applied, it's going to hold up any zcfg change issued by another tenant (which will be waiting behind in the feed).

I think the answer to this should be a rate-limiting mechanism of some form on the writes to the span configs. We definitely, absolutely must have a limiting mechanism on the number of span configs per tenant. That alone doesn't prevent the problem you describe here, but it's possible that we can convince ourselves that the delay due to the largest write we'd allow of a tenant would not incur that much delay.

>if the one span config range becomes unavailable, then zone configs break for all tenants simultaneously.

Same can be said for node liveness and meta1, and, for better or for worse, the tail of `system.rangelog`. I'm not convinced at all that this is a problem. System ranges are highly available. If we aren't getting enough fault-tolerance out of them, we should bump up their replication factors.

> if the scfgs are in a different region than the tenant, range relocations will incur cross-region traffic.

Do you mean when updating them or when reading/subscribing? I'd hope that we can replicate the `system.spanconfig` table enough such that there's a full copy in every region. Rangefeeds can and do run on followers.

> it's going to make it algorithmically less easy to bill the users (via RUs) for their scfg-allocator constraint resolutions. (This is, interestingly, already recognized as an unresolved question at the end of the document.)

This is true, especially without the inheritence scheme originally proposed such that a single row write to the tenant cluster can amplify to touch many spans in the host cluster. If there was a 1:1 mapping, I wouldn't care so much. Yes we'd be off, but not by too much. There's talk of reviving the inheritence proposals, so maybe that'll come into play. More importantly, however, is that we're definitely going to need to be building limits for span configs. Ideally that conversation will take us to talk about both rates as well as absolute numbers. Assuming that limiting infrastructure can talk about rates, then we can imagine it also charging for those writes. We're not optimizing for latency when applying span configs. I could very much see a desire to have the host side implementation of the writing calls of the KVAccessor increment some RU counters somewher [...]

2021-12-06 17:05 UTC, arulajmani approved these changes

2021-12-06 17:06 UTC, irfansharif commented
bors r+

2021-12-06 18:04 UTC, merged