colexecbase: add casts from decimals to ints and floats
cockroachdb/cockroach pull request #66379
Opened 2021-06-11 18:54 UTC by yuzefovich

This commit adds vectorized casts from decimals to ints (of all widths)
and floats.

Release note: None

2021-06-11 18:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66379)
<!-- Reviewable:end -->

2021-06-15 21:59 UTC, jordanlewis requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66379#-:-McGg0iU71tH19iQKGwA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_cast.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66379#-McGfG8NAeXTHkvxX5pj:-McGfG8NAeXTHkvxX5pk:b-75qx5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bc7c91bc141d7235ff6fd2c5f58f205dca1496/pkg/sql/colexec/execgen/cmd/execgen/overloads_cast.go#L176)):*
> ```Go
> 		//
> 		// NOTE: when updating the code below, make sure to update tree/casts.go
> 		// as well.
> ```

Blah, I wish we could find a way to avoid this duplication...


<!-- Sent from Reviewable.io -->

2021-06-15 22:00 UTC, jordanlewis approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66379#-:-McGg3J379MjNLTA3jLH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-06-16 00:48 UTC, yuzefovich reviewed
I had to adjust recently merged logic test.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66379#-:-McHHWRb2-Z7ic4hye4-:b-8covut)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @michae2)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_cast.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66379#-McGfG8NAeXTHkvxX5pj:-McHH6TJ1nmfS5kkINg1:b5spbzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9bc7c91bc141d7235ff6fd2c5f58f205dca1496/pkg/sql/colexec/execgen/cmd/execgen/overloads_cast.go#L176)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Blah, I wish we could find a way to avoid this duplication...
</blockquote></details>

I think we'll have to generate `tree/casts.go` (or relevant parts of it) from a template too :)


<!-- Sent from Reviewable.io -->

2021-06-16 01:54 UTC, merged