kvserver: Add migration for interleaved intents to separated
cockroachdb/cockroach pull request #66445
Opened 2021-06-14 19:23 UTC by itsbilal

Adds a long running migration that relies on a ranged-read
Raft command to leak an engine snapshot, on which we do a
scan and push any txns whose intents were observed to still
be interleaved.

Part of #41720.

Release note: None.

2021-06-14 19:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66445)
<!-- Reviewable:end -->

2021-06-14 19:27 UTC, itsbilal commented
There are still some TODOs here, primarily 1) removing the separatedIntentsEnabled setting, and 2) rate limiting. I'm going to add on a second commit for 1) shortly.

But since this is a pretty involved change, I wanted to get this out early so I can get any opinions on alternative ways to approach this, or things I might have overlooked. Thanks!

2021-06-15 09:31 UTC, erikgrinaker reviewed
Very excited for this!

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-McE-hPqByF_bXp-3XkO:bjtlwv5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDpGk0-j7YYBL88y-u:-McDpGk0-j7YYBL88y-v:b-aghst3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1875)):*
> ```
> interlevaed
> ```

interleaved
___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-McDq06D2nvfZWB_u3V2:b43utcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
> ```Go
> 		}
> 
> 		txnIntents[meta.Txn.ID] = append(txnIntents[meta.Txn.ID], keyAndIntent{
> ```

I think we should limit the number of intents we pull into memory at once, to avoid OOMs.
___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-McDqbFb78qjsH-_PbEJ:b-hb3xig) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
> ```Go
> 		h := roachpb.Header{
> 			Timestamp:    r.Clock().Now(),
> 			UserPriority: roachpb.NormalUserPriority,
> ```

I think we want to push with `MaxUserPriority` so that we always win pushes (i.e. never block).
___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-McDt1E5C3h11xmHy6du:b-wiar7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
> ```Go
> 		// the result.
> 		if mlt := br.Responses[0].GetMigrateLockTable(); mlt != nil {
> 			err := r.migrateLockTable(ctx, ba.Requests[0].GetMigrateLockTable(), mlt)
> ```

I'm curious why we're handling this request here using this engine snapshot registry. There are a few other options that seem more straightforward to me, such as doing the migration during request evaluation or in `executeReadOnlyBatch`, or collecting the intents in the command and returning them in the response (instead of holding onto the engine snapshot). We could even just do a high-priority scan to resolve all the intents, which I think would have the same effect, although perhaps less efficiently unless we're clever about `WriteIntentError` retries.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDxKth6LvIgfyKkmPb:-McDxKth6LvIgfyKkmPc:b-ghumdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/batcheval/cmd_migrate.go#L201)):*
> ```Go
> // separatedIntentsMigration is the below-raft part of the migration for
> // interleaved to separated intents. It is a no-op as the only purpose of
> // running the Migrate command here is to clear out replicas with
> ```

...with what?
___
*[pkg/migration/migrations/separated_intents.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDz-m49LdNEgbo8IEo:-McDz-m49LdNEgbo8IEp:b-kqpvtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/migration/migrations/separated_intents.go#L73)):*
> ```Go
> 			select {
> 			case r, ok := <-m.requests:
> 				if !ok && r.end == nil && r.start == nil {
> ```

Checking `r.end`and `r.start` isn't necessary here -- if `!ok` then `r` will always be a zero value.


<!-- Sent from Reviewable.io -->

2021-06-16 21:05 UTC, sumeerbhola requested changes
nice! still reading -- flushing some comments

> Reviewed 8 of 24 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-McLcyQV3L2KhSQGZL1o:by7orw1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-McLb9HDByDdHR2KpPQm:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think we should limit the number of intents we pull into memory at once, to avoid OOMs.
</blockquote></details>

+1
___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-McLb_Av2zwJlQKk1My0:b-bnbmc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think we want to push with `MaxUserPriority` so that we always win pushes (i.e. never block).
</blockquote></details>

The downside is it could impact user-facing traffic. It may be better to debug a stuck migration versus having users complain about upgrading to 21.2 causing production issues. I would suggest getting some more opinions.
___
*[pkg/kv/kvserver/replica.go, line 1909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLahUC3Qk3wh4dp62C:-McLahUC3Qk3wh4dp62D:b-on8now) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/replica.go#L1909)):*
> ```Go
> 			return err
> 		}
> 		if !key.IsMVCCKey() {
> ```

should this ever be a non-MVCC key. That would mean we are somehow iterating over the local range key space of the lock table. May be worth returning an error instead.
___
*[pkg/kv/kvserver/replica.go, line 1920 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLb-hNA_M1OA6Ucy-B:-McLb-hNA_M1OA6Ucy-C:b-siyjjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/replica.go#L1920)):*
> ```Go
> 			//
> 			// TODO(bilal): Explore seeking here in case there are keys with lots of
> 			// versioned values.
> ```

I think we need a benchmark for this migration.
___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-McL__F72MFV7aam20hv:b-8qiek3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I'm curious why we're handling this request here using this engine snapshot registry. There are a few other options that seem more straightforward to me, such as doing the migration during request evaluation or in `executeReadOnlyBatch`, or collecting the intents in the command and returning them in the response (instead of holding onto the engine snapshot). We could even just do a high-priority scan to resolve all the intents, which I think would have the same effect, although perhaps less efficiently unless we're clever about `WriteIntentError` retries.
</blockquote></details>

I think this is being done here since this is the first place we pop out of `executeBatchWithConcurrencyRetries` which means for this read-only command we've released latches. So this potentially slow migration will not hinder any other operations like range splits, merges etc. 
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLXx-c7Zb1d3Dp164W:-McLXx-c7Zb1d3Dp164X:b-yvphp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L58)):*
> ```Go
> 	latchSpans, lockSpans *spanset.SpanSet,
> ) {
> 	latchSpans.AddNonMVCC(spanset.SpanReadOnly, roachpb.Span{Key: keys.RangeDescriptorKey(rs.GetStartKey())})
> ```

can you add a code comment on why this doesn't need to latch the span of the request. I am assuming that is because we don't care about concurrent writes since they could not be adding interleaved intents.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYRmy8ANHBf0T0h1x:-McLYRmy8ANHBf0T0h1y:byhjrbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L69)):*
> ```Go
> // created as part of the MigrateLockTable command. A singleton instance
> // of this type is stored as lockTableSnapshotRegistry.
> type lockTableSnapshotRegistryType struct {
> ```

mild preference for `lockTableMigrationSnapshotRegistryType` since we aren't really using this snapshot to read the lock table key space.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYgvG3Wo8Tuxam09T:-McLYgvG3Wo8Tuxam09U:b-lja8lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L79)):*
> ```Go
> }
> 
> // GetAndRemoveLockTableSnapshot grabs o lock on the lock table snapshot
> ```

s/o/a/
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYu3zCwuI2PLCdgUs:-McLYu3zCwuI2PLCdgUt:bav00z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L147)):*
> ```Go
> 	ms := cArgs.Stats
> 
> 	if ms != nil && ms.ContainsEstimates == 0 && ms.IntentCount == 0 {
> ```

We're willing to trust stats now?
___
*[pkg/migration/migrations/migrations.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLZSckCqJc6EGv6F9J:-McLZSckCqJc6EGv6F9K:bx87aq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/migrations.go#L72)):*
> ```Go
> 		"move over all intents to separate lock table",
> 		toCV(clusterversion.SeparatedIntentsMigration),
> 		separatedIntentsMigration),
> ```

how will we know when this is complete?
___
*[pkg/migration/migrations/separated_intents.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLcLMyAxu7T_IwEfS3:-McLcLMz0FHJW19xJSrb:blp0taq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L42)):*
> ```Go
> // migrateLockTableRequest represents one request for a migrateLockTable
> // command. This will correspond to one range at the time of running the
> // IterateRangeDescriptors command. As long as
> ```

sentence is incomplete.


<!-- Sent from Reviewable.io -->

2021-06-16 21:09 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McLdMSdBLXyuq-k_WOQ:bhvl5b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
> ```Go
> }
> 
> func separatedIntentsMigration(
> ```

who will run this function and which node will it be run on?
___
*[pkg/migration/migrations/separated_intents.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdrIm-hmlfBzr5-RX:-McLdrIm-hmlfBzr5-RY:b1unl9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L158)):*
> ```Go
> 		}
> 		numMigratedRanges += len(descriptors)
> 		log.Infof(ctx, "[batch %d/??] started lock table migrations for %d ranges", batchIdx, numMigratedRanges)
> ```

how would one figure out if migration was stuck on some ranges? Would one look in the cluster logs?


<!-- Sent from Reviewable.io -->

2021-06-16 21:22 UTC, itsbilal reviewed
TFTRs! Didn't reply to all the comments yet - but pushing out some of the larger changes so far while I get to the others. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-McLKtLe8mJHfmm4QYO5:b-9mkyis)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1875 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDpGk0-j7YYBL88y-u:-McLKuTECvClhsXCH2LH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1875)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

> ```
> interlevaed
> ```

interleaved
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-McLTIB1CAn6ipBeeYIq:b-tbanul) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think we should limit the number of intents we pull into memory at once, to avoid OOMs.
</blockquote></details>

Done. Added a 100-intent limit.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDxKth6LvIgfyKkmPb:-McLfndO35guBJ3NxJU5:b-2t0z5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/batcheval/cmd_migrate.go#L201)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

...with what?
</blockquote></details>

.. interleaved intents :joy: . Done.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYgvG3Wo8Tuxam09T:-McLfeHR3GlNSa5Izs6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L79)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/o/a/
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLcLMyAxu7T_IwEfS3:-McLgIQH3wSd8jRM8wwW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L42)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

sentence is incomplete.
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McLgKFyDmA_Xc2ay9G4:b-6dp1sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

who will run this function and which node will it be run on?
</blockquote></details>

This function will run on one node in the cluster. If it doesn't finish successfully, it could be re-run on any other node on the cluster. The migration framework takes care of this.


<!-- Sent from Reviewable.io -->

2021-06-17 12:37 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McOxuYR8H3VzSi8uYAH:bwca84j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This function will run on one node in the cluster. If it doesn't finish successfully, it could be re-run on any other node on the cluster. The migration framework takes care of this.
</blockquote></details>

is there any checkpointing provided by the migration framework or it needs to start from the beginning?

I realize we currently have the IntentCount==0 fast path that may make restarting from the beginning cheap enough. But if we do have to read all the data in the cluster, it would be beneficial to not have to repeat work.


<!-- Sent from Reviewable.io -->

2021-06-17 21:00 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLahUC3Qk3wh4dp62C:-McQUoq5DUT0jxXiIv8N:buwgprp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/replica.go#L1909)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this ever be a non-MVCC key. That would mean we are somehow iterating over the local range key space of the lock table. May be worth returning an error instead.
</blockquote></details>

That'll always be local then, right? I guess it's worth returning an error here then. Done.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLXx-c7Zb1d3Dp164W:-McQXJn9-H3msnk1SctW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a code comment on why this doesn't need to latch the span of the request. I am assuming that is because we don't care about concurrent writes since they could not be adding interleaved intents.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYRmy8ANHBf0T0h1x:-McQXtUGDqTPdzHxFllv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L69)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

mild preference for `lockTableMigrationSnapshotRegistryType` since we aren't really using this snapshot to read the lock table key space.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYu3zCwuI2PLCdgUs:-McQZl3o0lkrv6iK6SBs:brqhg6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L147)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We're willing to trust stats now?
</blockquote></details>

@tbg made this suggestion, wondering what his thoughts here would be. My understanding here was that intent count would be consistent.
___
*[pkg/migration/migrations/migrations.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLZSckCqJc6EGv6F9J:-McQXvpH7ZjOWmPnd92j:b-ughe1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/migrations.go#L72)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how will we know when this is complete?
</blockquote></details>

This will end up in the `migrations` system table, as that tracks completion.
___
*[pkg/migration/migrations/separated_intents.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDz-m49LdNEgbo8IEo:-McQaqL799VbOshqTCQi:bol6q7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/migration/migrations/separated_intents.go#L73)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Checking `r.end`and `r.start` isn't necessary here -- if `!ok` then `r` will always be a zero value.
</blockquote></details>

I thought `!ok` just means "no more values after this one", but on reading the golang spec, you're right. I don't need to check for the latter. Done.

https://golang.org/ref/spec#Receive_operator
___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McQZSut9WyLrEUzz5se:b1ceyub) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there any checkpointing provided by the migration framework or it needs to start from the beginning?

I realize we currently have the IntentCount==0 fast path that may make restarting from the beginning cheap enough. But if we do have to read all the data in the cluster, it would be beneficial to not have to repeat work.
</blockquote></details>

It'll need to start from the beginning. We could store progress somewhere ourselves, but that could be quite a lifting in itself. I'm leaning hard on the fast-paths letting us skip many ranges we've already migrated.
___
*[pkg/migration/migrations/separated_intents.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdrIm-hmlfBzr5-RX:-McQZhwZ9bV1tC6VW_lZ:b-bv4ce4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L158)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how would one figure out if migration was stuck on some ranges? Would one look in the cluster logs?
</blockquote></details>

I should probably add more verbose logging to help with this, because I can see that being pretty opaque right now. Do you think a log line for every range we start and end a migration on would be too verbose and useless? A better way would be to spin up a separate goroutine that tracks and regularly logs "waiting for migration to complete on X ranges" and if X is low enough, it prints out their range IDs / boundaries at time of seed. 


<!-- Sent from Reviewable.io -->

2021-06-21 12:24 UTC, erikgrinaker reviewed
> Reviewed 3 of 8 files at r2, 11 of 11 files at r3, 24 of 24 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-MciRRS81Zvko83GWN8G:bjafrs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Added a 100-intent limit.
</blockquote></details>

Thanks! Is it worth adding a byte limit as well, in case we encounter large keys? That would allow us to optimistically use a higher intent count limit as well, which should help with throughput in the typical case of small keys.
___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-MciS-RF8v7M16C9CS74:b-osw4vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The downside is it could impact user-facing traffic. It may be better to debug a stuck migration versus having users complain about upgrading to 21.2 causing production issues. I would suggest getting some more opinions.
</blockquote></details>

This is a good point, I don't know how aggressive we want to be here. If we are worried about impacting workloads, I would think we should use `PUSH_TOUCH` instead, which will never abort other txns. `PUSH_ABORT` with `NormalUserPriority` would have a 50% chance of aborting conflicting txns, I believe.
___
*[pkg/kv/kvserver/replica.go, line 1903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MciQuG_AHo4hWB-eBoc:-MciQuG_AHo4hWB-eBod:bkyqna1) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ef67a4fc30d45d63c367116452800a00e18d19/pkg/kv/kvserver/replica.go#L1903)):*
> ```Go
> 
> 	for resumeKey.Key != nil {
> 		iter := snap.NewEngineIterator(storage.IterOptions{
> ```

Is it necessary/desirable to reopen the iterator for each batch? I would imagine it'd be more performant to keep it open, and the cost should be negligible (?).
___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-MciSe4j1sfbtzot1cNO:bx457k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think this is being done here since this is the first place we pop out of `executeBatchWithConcurrencyRetries` which means for this read-only command we've released latches. So this potentially slow migration will not hinder any other operations like range splits, merges etc. 
</blockquote></details>

Right. We could in principle run the request without taking out any latches, which is essentially what we're doing here as well, but the mutexes would hold up splits/merges.

As a straw man, could we not instead run a request that gathers a batch of interleaved intents and returns them in the response, using resume spans until done? We could then resolve those intents either here or in the migration job itself, but without having to use this global Pebble snapshot registry.
___
*[pkg/migration/migrations/separated_intents.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdrIm-hmlfBzr5-RX:-MciVdKw8nfqMR5Yk1Xr:b-2raihw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L158)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I should probably add more verbose logging to help with this, because I can see that being pretty opaque right now. Do you think a log line for every range we start and end a migration on would be too verbose and useless? A better way would be to spin up a separate goroutine that tracks and regularly logs "waiting for migration to complete on X ranges" and if X is low enough, it prints out their range IDs / boundaries at time of seed. 
</blockquote></details>

I don't have a strong opinion either way (would maybe take a cue from other similar migrations), but it would be useful to see which ranges are currently being processed with some frequency, to debug whether it's stuck and what it's stuck on.


<!-- Sent from Reviewable.io -->

2021-06-21 12:27 UTC, erikgrinaker reviewed
Btw, how do we synchronize with ongoing transactions? Is the migration only run after the upgrade is finalized across the entire cluster?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MciXOGy0wy80H5718Vm:b-icpprt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)



<!-- Sent from Reviewable.io -->

2021-06-21 14:26 UTC, tbg reviewed
Have only given this a high-level look and wrote down some of the particulars of the synchronization that we need.

Seeing how complex this migration is, I'd appreciate a much more verbose description of the PR so that I can point out potential holes in the approach and make suggestions without giving this a low-level review yet. What's here is too vague for me to fill in the blanks. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-McixA1c-gY_aBnu9OHD:b38ggpz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/kv/db.go, line 718 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McitM2DAoICSPQ2oGmX:-McitM2E0XJ1PSXSMaW_:b-dzi5hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/db.go#L718)):*
> ```Go
> // local map. At send time, the replica(s) conduct a migration to convert all
> // interleaved intents to separated intents. This command is called with the
> // assumption that no more interleaved intents will be written after this point.
> ```

This is an invariant, but is it upheld? I know it is approximately true because the cluster version that enables separate intents is made active across all nodes before the migration that calls this method starts. But it is, at least in theory, still racy. There might be a goroutine, hanging, that *just* checked for the separated intents and came back wanting to write an inline intent (but hasn't done so yet). The migration to push out the "always write inline intents" comes along, but it's too late. `MigrateLockTable` runs. And now the goroutine unwedges and writes an intent.

Maybe this scenario isn't possible, but this PR needs to document in an appropriate place why this can't be possible.

If I'm reading the code correctly, the determination of inline vs separated intents is made here:

https://github.com/cockroachdb/cockroach/blob/7bca56975f7bd183ede8b0c2d5d937bdf72f66d1/pkg/storage/pebble_batch.go#L98-L99

and this is during evaluation (called from here):

https://github.com/cockroachdb/cockroach/blob/615ddd04f27b5c3729a17be406b143b45dae65a5/pkg/kv/kvserver/replica_write.go#L695-L716

This is good, as evaluation is under the protection of replica latches. To make this airtight, we need:

1. a "barrier" that makes sure that "new" operations will never write separated intents.
2. a way to flush out the "old" side of the barrier, i.e. ops that may have inline intents pending.

The first part is indeed provided by a cluster setting (when active, all nodes have been informed that all new operations must use separated intents, and need to ignore the cluster setting)

But there could be some command hanging out for ages in evaluation that is still writing an inline intent. We need to make sure it is gone. One simple way to do this would be to declare a read at infinity over the entire keyspan (i.e. on each range). This would in effect block on all evaluations that are inflight, meaning that once it's through, nobody is contemplating inline intents anymore (and any inline intents have materialized on the state machines, at least on the leader, though not durably - we need to sync everyone's stores once; the migrations infra does this in its stabilization wrappers, need to make sure we hit that path here).

To avoid the pipeline stall that comes with a scan at infinity, we can also sleep for some time, take the local node's current hlc reading, and then do a read at that timestamp. I *think* that should also work, though now that we have non-blocking txns we need to sleep a little longer. It may not be worth doing this dance and just do the original "read at infinity" strategy.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYu3zCwuI2PLCdgUs:-Mcir-JL4LVJ6JgeaYzb:bbvg2d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L147)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

@tbg made this suggestion, wondering what his thoughts here would be. My understanding here was that intent count would be consistent.
</blockquote></details>

At this point I would avoid trusting the stats, see this comment: https://reviewable.io/reviews/cockroachdb/cockroach/66268#-MblNrQB9zzcli3MQoaW. The stakes are too high here.

Doing the full scan unconditionally does make this migration a lot more expensive, but it also makes it more predictable - when it runs in our tests it will have largely the same cost that it will have in our customers' deployments. This is our first "true" long-running migration, and we need to test it out appropriately. This will be easier if it doesn't have a fast path.


<!-- Sent from Reviewable.io -->

2021-06-21 14:40 UTC, ajwerner reviewed
> how do we synchronize with ongoing transactions? Is the migration only run after the upgrade is finalized across the entire cluster?

Correct, the migration only runs after all nodes in the cluster have locked out older versions. When we introduced the migration framework, we changed to use only even-number versions for named version. The way the migration/version bump works is that it first bumps to the odd version preceding the migration version and proves that that has been set as the cluster version before it proceeds to perform the migration and then set increment the version again. There are some hoops we jump through to make sure that no nodes which are not running the proper version can run.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mcj-bdx7O_mI2YOXbR6:b-2dz5gw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McizXTFCbuGhsLZieoF:b-aa685r) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It'll need to start from the beginning. We could store progress somewhere ourselves, but that could be quite a lifting in itself. I'm leaning hard on the fast-paths letting us skip many ranges we've already migrated.
</blockquote></details>

The jobs frameworks offers checkpointing and checkpoint state storage. It hasn't been plumbed through to the migration jobs. It would not be terribly hard to do so. Happy to guide that if you're interested. It feels like an optimization which could be done as follow-up, no? If we deem it important, then let's file an issue?
___
*[pkg/migration/migrations/separated_intents.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mcj-F7t8nQmx0OonOWb:-Mcj-F7t8nQmx0OonOWc:b-yiq9oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ef67a4fc30d45d63c367116452800a00e18d19/pkg/migration/migrations/separated_intents.go#L175)):*
> ```Go
> 	log.Infof(ctx, "[batch %d/%d] migrated lock table for %d ranges", batchIdx, batchIdx, numMigratedRanges)
> 
> 	// Part 2 - Issue no-op Migrate commands to all ranges. This has the only
> ```

Would it be cleaner if this was a separate migration at the next version? You'd get checkpointing of these two parts for free. Also, why no parallelism here? 


<!-- Sent from Reviewable.io -->

2021-06-22 15:56 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/db.go, line 718 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McitM2DAoICSPQ2oGmX:-McoNklT8X2NBWwYZLCs:b-49v59f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/db.go#L718)):*
> This would in effect block on all evaluations that are inflight, meaning that once it's through, nobody is contemplating inline intents anymore (and any inline intents have materialized on the state machines, at least on the leader, though not durably - we need to sync everyone's stores once; the migrations infra does this in its stabilization wrappers, need to make sure we hit that path here

Doesn't the non-sync optimization in `replica_application_state_machine.go` also rely on the fact that if the node fails no future leaseholder will execute `BatchRequests` before applying all the raft committed entries to its state machine?

>  To avoid the pipeline stall that comes with a scan at infinity, we can also sleep for some time, take the local node's current hlc reading, and then do a read at that timestamp. I think that should also work, though now that we have non-blocking txns we need to sleep a little longer. It may not be worth doing this dance and just do the original "read at infinity" strategy.

The simpler thing, that would avoid any chance of a pipeline stall, would be to add a `WaitForWrites` method on `spanlatch.Manager` that only grabs a snapshot and waits for write latches on the span (without adding its own read latches). The messiness here would be arranging for this to be called -- I don't think we want to plumb this special case through the general framework of `RequestSequencer.SequenceReq`. We could special case this in `executeBatchWithConcurrencyRetries`, prior to the for loop, since a `MigrateLockTableRequest` will be in a `BatchRequest` by itself.
___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-McoI5D_1FjMbdcqbTyh:b9g9kxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This is a good point, I don't know how aggressive we want to be here. If we are worried about impacting workloads, I would think we should use `PUSH_TOUCH` instead, which will never abort other txns. `PUSH_ABORT` with `NormalUserPriority` would have a 50% chance of aborting conflicting txns, I believe.
</blockquote></details>

makes sense -- lets do `PUSH_TOUCH`.
@tbg do you have an opinion?
___
*[pkg/kv/kvserver/replica.go, line 1903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MciQuG_AHo4hWB-eBoc:-McoHwQBC7Y5L1ZqQmvX:b-336wyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ef67a4fc30d45d63c367116452800a00e18d19/pkg/kv/kvserver/replica.go#L1903)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is it necessary/desirable to reopen the iterator for each batch? I would imagine it'd be more performant to keep it open, and the cost should be negligible (?).
</blockquote></details>

I agree -- `pebbleSnapshot` does not reuse iterators under the cover.
___
*[pkg/kv/kvserver/replica.go, line 1921 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoL4Tl81jCgcNXUrQz:-McoL4Tl81jCgcNXUrR-:b11mwna) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/kvserver/replica.go#L1921)):*
> ```Go
> 		intentCount := 0
> 
> 		for ; valid && err == nil; valid, err = iter.NextEngineKey() {
> ```

I think we need to add support for some throttling here in case the scan starts affecting user-facing traffic. Just pausing the migration would be insufficient since we'd want to resume it eventually. This would allow an admin to adjust a cluster setting to slow down the work being done for each range.
___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McoIYwcEccwAZN384np:b-9aql7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The jobs frameworks offers checkpointing and checkpoint state storage. It hasn't been plumbed through to the migration jobs. It would not be terribly hard to do so. Happy to guide that if you're interested. It feels like an optimization which could be done as follow-up, no? If we deem it important, then let's file an issue?
</blockquote></details>

I think the fast-path is nixed now, so we do need checkpointing -- not in this PR, but in a followup.
I assume we would get progress reporting in terms of how many ranges have completed, as part of that checkpointing.
___
*[pkg/migration/migrations/separated_intents.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoK-kR4rUex2u42t2a:-McoK-kR4rUex2u42t2b:b-4u8lia) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/migration/migrations/separated_intents.go#L34)):*
> ```Go
> // happens when the destination replica(s) are sending replies back to the
> // original node.
> const concurrentMigrateLockTableRequests = 4
> ```

Could we get unlucky and all 4 could be ranges with the same leaseholder?
Ideally we  should arrange it such that we run up to k (k=1 default) range per node in the cluster. That way we also scale the number of concurrent ranges being migrated to the cluster size. Fine to leave it as a TODO for a followup PR.


<!-- Sent from Reviewable.io -->

2021-06-22 16:21 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-McoW2Lz0FSePExCvWLm:bq8cuue) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think the fast-path is nixed now, so we do need checkpointing -- not in this PR, but in a followup.
I assume we would get progress reporting in terms of how many ranges have completed, as part of that checkpointing.
</blockquote></details>

It'll be up to the caller of the checkpoint code to indicate % completion. The checkpoint state itself can be whatever, though I think completed spans is likely the most natural choice. I'll ready the plumbing for a subsequent PR to adopt. 
___
*[pkg/migration/migrations/separated_intents.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdrIm-hmlfBzr5-RX:-McoWdSu6efDOYfvBays:bl94ooq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L158)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't have a strong opinion either way (would maybe take a cue from other similar migrations), but it would be useful to see which ranges are currently being processed with some frequency, to debug whether it's stuck and what it's stuck on.
</blockquote></details>

Slow logging?


<!-- Sent from Reviewable.io -->

2021-06-23 20:34 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/db.go, line 718 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McitM2DAoICSPQ2oGmX:-McuWp8H00dngH6A3Phd:b-hdqhxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/db.go#L718)):*
> The first part is indeed provided by a cluster setting (when active, all nodes have been informed that all new operations must use separated intents, and need to ignore the cluster setting)

To clarify, when you say cluster setting, you're referring to the active cluster version, right? The second commit in this PR actually removes the cluster setting that even allows the toggling of separated intents at runtime; as long as all nodes can read separated intents, all writes will write separated intents.

I might be simplifying this as I'm thinking of this from a storage lens, but if it really does come down to a race between the finalization of the cluster version and an `intentDemuxWriter` writing an interleaved intent as it only saw the old cluster version,, can we just remove the caching of cluster versions in the writer if it's older than `SeparatedIntentsMigration` and check the cluster setting on every write? This is expensive (and I don't even have an intuitive sense of how expensive it would be), but it would be a transient state. And even then it might not be airtight enough for our needs.

I'll poke around the code a bit more (thanks Sumeer for the pointers) and get back to this very shortly.
___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-Mcu1O4o4C43UbqVq5Kn:bmm3iiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Thanks! Is it worth adding a byte limit as well, in case we encounter large keys? That would allow us to optimistically use a higher intent count limit as well, which should help with throughput in the typical case of small keys.
</blockquote></details>

Done. Would be good to get your thoughts on the two constants that drive it.
___
*[pkg/kv/kvserver/replica.go, line 1920 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLb-hNA_M1OA6Ucy-B:-Mctc-hqC0SKXqGjW5cu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/replica.go#L1920)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need a benchmark for this migration.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica.go, line 1903 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MciQuG_AHo4hWB-eBoc:-McuNuuQ-T8H1AWIitA3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ef67a4fc30d45d63c367116452800a00e18d19/pkg/kv/kvserver/replica.go#L1903)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I agree -- `pebbleSnapshot` does not reuse iterators under the cover.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica.go, line 1921 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoL4Tl81jCgcNXUrQz:-McuRSaZDXzWiC8KI7db:bw1el2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/kvserver/replica.go#L1921)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need to add support for some throttling here in case the scan starts affecting user-facing traffic. Just pausing the migration would be insufficient since we'd want to resume it eventually. This would allow an admin to adjust a cluster setting to slow down the work being done for each range.
</blockquote></details>

For this, are you thinking of just a `rate.NewLimiter` keyed by a cluster setting that's, say, `kv.separated_intent_migration.max_scan_rate` ? We could occasionally fetch the cluster setting so that we pick up changes from the user, and reset the limiter if it has changed.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLYu3zCwuI2PLCdgUs:-Mcu2KAbBZNWtMXbArkE:bhs5cpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/kv/kvserver/batcheval/cmd_migrate.go#L147)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

At this point I would avoid trusting the stats, see this comment: https://reviewable.io/reviews/cockroachdb/cockroach/66268#-MblNrQB9zzcli3MQoaW. The stakes are too high here.

Doing the full scan unconditionally does make this migration a lot more expensive, but it also makes it more predictable - when it runs in our tests it will have largely the same cost that it will have in our customers' deployments. This is our first "true" long-running migration, and we need to test it out appropriately. This will be easier if it doesn't have a fast path.
</blockquote></details>

Sounds good. Removing the stats-based fast path, thanks!
___
*[pkg/migration/migrations/separated_intents.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdrIm-hmlfBzr5-RX:-McuZtoT5EiZbgH5Fyci:b-q490xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L158)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Slow logging?
</blockquote></details>

Done. Added a new status logging goroutine that runs every 5 seconds.
___
*[pkg/migration/migrations/separated_intents.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mcj-F7t8nQmx0OonOWb:-McuZz0b75zbhkw8DpT4:b-nsx984) ([raw file](https://github.com/cockroachdb/cockroach/blob/70ef67a4fc30d45d63c367116452800a00e18d19/pkg/migration/migrations/separated_intents.go#L175)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would it be cleaner if this was a separate migration at the next version? You'd get checkpointing of these two parts for free. Also, why no parallelism here? 
</blockquote></details>

Done. Lack of parallelism mimics other migrations - I imagine this will be a relatively fast invocation?


<!-- Sent from Reviewable.io -->

2021-06-24 11:52 UTC, erikgrinaker reviewed
> Reviewed 37 of 37 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-Mcxpn2Q8gknXlCH3nAx:b-ip541n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Would be good to get your thoughts on the two constants that drive it.
</blockquote></details>

Thanks! I think we can be more aggressive about this. For `ClearRange`, for example, we pull 1000 intents or 1MB at a time. The GC queue is being changed to pull 5000 intents or 1 MB at a time (but also limits the number of txns to push to 100).

I think something like 1000 intents and 1 MB would make sense here.


<!-- Sent from Reviewable.io -->

2021-06-24 20:36 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/db.go, line 718 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McitM2DAoICSPQ2oGmX:-MczigxQ3Vqz9hxuXFcN:b-bw4ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/db.go#L718)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

> The first part is indeed provided by a cluster setting (when active, all nodes have been informed that all new operations must use separated intents, and need to ignore the cluster setting)

To clarify, when you say cluster setting, you're referring to the active cluster version, right? The second commit in this PR actually removes the cluster setting that even allows the toggling of separated intents at runtime; as long as all nodes can read separated intents, all writes will write separated intents.

I might be simplifying this as I'm thinking of this from a storage lens, but if it really does come down to a race between the finalization of the cluster version and an `intentDemuxWriter` writing an interleaved intent as it only saw the old cluster version,, can we just remove the caching of cluster versions in the writer if it's older than `SeparatedIntentsMigration` and check the cluster setting on every write? This is expensive (and I don't even have an intuitive sense of how expensive it would be), but it would be a transient state. And even then it might not be airtight enough for our needs.

I'll poke around the code a bit more (thanks Sumeer for the pointers) and get back to this very shortly.

</blockquote></details>

Scratch what I said yesterday. I implemented something that's pretty similar to what Sumeer is describing - a `WaitWithoutAcquiring` that waits on conflicting latches without adding itself, and we've defined a read latch at infinity for `MigrateLockTable` so it'll block on all existing writes. I'm new to most of this code so please take a close look in case I missed something. Thanks!
___
*[pkg/kv/kvserver/replica.go, line 1934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDq06D2nvfZWB_u3V1:-MczcedK1CoE23D5DKgW:boyexb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1934)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Thanks! I think we can be more aggressive about this. For `ClearRange`, for example, we pull 1000 intents or 1MB at a time. The GC queue is being changed to pull 5000 intents or 1 MB at a time (but also limits the number of txns to push to 100).

I think something like 1000 intents and 1 MB would make sense here.
</blockquote></details>

Done. Thanks!


<!-- Sent from Reviewable.io -->

2021-06-29 22:07 UTC, sumeerbhola requested changes
This is getting close. I need to make another, more carefu,l pass.
Do we need the second and third commits in this PR? The first one itself has a lot to digest, so if possible I would prefer them to be split out.

> Reviewed 1 of 37 files at r6, 13 of 43 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MdOnXZ7EEK1Nu3QXhk4:b-pb3dcz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1921 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoL4Tl81jCgcNXUrQz:-MdO2DUs2HzcsomdcO51:b-s4z0aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/kvserver/replica.go#L1921)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

For this, are you thinking of just a `rate.NewLimiter` keyed by a cluster setting that's, say, `kv.separated_intent_migration.max_scan_rate` ? We could occasionally fetch the cluster setting so that we pick up changes from the user, and reset the limiter if it has changed.
</blockquote></details>

Yes, that would be fine.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MdOfOufAaO3Sg7jqiJ4:b-9sb5gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> ```Go
> 			// Special case: We do not need to go through SequenceReq to acquire latches
> 			// for this request. We only need to wait for conflicting write latches to
> 			// be complete. Call WaitWithoutAcquiring instead of SequenceReq. The
> ```

The `instead of SequenceReq` part is not quite correct since we will execute the loop.

I have a strong opinion on the code structuring for this, which may actually be a nit, and I'm willing to be convinced otherwise.
This behavior is very special case and I'd like the code and code comments to be very clear about this. Which means
- Adding a new interface, say `ReadLatchBarrierProvider` with a `WaitFor(context.Context, roachpb.Span)` method
- Implement it in `managerImpl` (and include it in the `Manager` interface) and plumb it through to `spanlatch.Manager`. The latter can stuff it into a `SpanSet` so it can reuse its implementation methods.
- Call that here by explicitly plucking out the req.Header.Span() for this migrate request.
- Don't declare the header span in `declareKeysMigrateLockTable` -- we don't want anything about this barrier to look like normal latch acquisition.

@nvanbenschoten in case there is a different opinion.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 63 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOaRd6-KwO9xbE0I2Q:-MdOaRd6-KwO9xbE0I2R:b-w4echl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/batcheval/cmd_migrate.go#L63)):*
> ```Go
> 	// grabbed.
> 	latchSpans.AddMVCC(spanset.SpanReadOnly, req.Header().Span(), hlc.MaxTimestamp)
> 	latchSpans.AddNonMVCC(spanset.SpanReadOnly, roachpb.Span{Key: keys.RangeDescriptorKey(rs.GetStartKey())})
> ```

I'm assuming the RangeDescriptorKey latch is still needed, yes? It would also be good to clarify why we need it -- if I remember correctly we are using the stronger invariant that this range is not being modified, even though we don't need the range descriptor, only because we expect less contention in this manner. @tbg 
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 316 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOkstiESyPZYXGFm8A:-MdOkstiESyPZYXGFm8B:brw7xjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/concurrency/concurrency_manager.go#L316)):*
> ```Go
> 		// help synchronize with other requests.
> 		return false
> 	case req.isSingle(roachpb.MigrateLockTable):
> ```

this change would go away with the structure I was suggesting in the other comment.
___
*[pkg/migration/migrations/separated_intents.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoK-kR4rUex2u42t2a:-MdO3qCf177fF9l1DTlc:bquk34p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/migration/migrations/separated_intents.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could we get unlucky and all 4 could be ranges with the same leaseholder?
Ideally we  should arrange it such that we run up to k (k=1 default) range per node in the cluster. That way we also scale the number of concurrent ranges being migrated to the cluster size. Fine to leave it as a TODO for a followup PR.
</blockquote></details>

reminder about this comment
___
*[pkg/migration/migrations/separated_intents.go, line 176 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdO3YQPEqmop8Cyx7QN:-MdO3YQPEqmop8Cyx7QO:b-iwhwmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L176)):*
> ```Go
> 	stopper := h.Stopper()
> 	if stopper == nil {
> 		// This is a tenant cluster and would not need a migration.
> ```

I don't understand the "tenant cluster" terminology -- is that the cluster with sql-only nodes?
___
*[pkg/migration/migrations/separated_intents.go, line 211 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOItsb4-h2Y8n_m0-g:-MdOItsb4-h2Y8n_m0-h:b-bydim6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L211)):*
> ```Go
> 				continue
> 			}
> 			workerPool.requests <- migrateLockTableRequest{
> ```

We also need to migrate the range local keys since those can have locks too (e.g. local range descriptor keys). We can do that by constructing another range using `MakeRangeKeyPrefix(start)`, `MakeRangeKeyPrefix(end)`.
Also, it would be good to have test coverage that ensures we don't miss such range local keys in the migration.
___
*[pkg/migration/migrations/separated_intents.go, line 235 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOL77B2EwdCdfnbPT4:-MdOL77C6A13dvumpUPd:bbacex4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L235)):*
> ```Go
> 	}
> 
> 	log.Infof(ctx, "[batch %d/%d] migrated lock table for %d ranges", batchIdx, batchIdx, numMigratedRanges)
> ```

could you explain this `[batch %d/%d]` and `[batch %d/??]` scheme being used in these log statements?


<!-- Sent from Reviewable.io -->

2021-07-01 10:39 UTC, erikgrinaker reviewed
If the migration encounters an error, how is it retried? If it involves rerunning the entire migration, do we want to add inner retry loops that can e.g. retry failed txn pushes or intent resolution a few times without starting over from scratch?

> Reviewed 43 of 43 files at r9, 24 of 24 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MdWcWQ29kb7oaHjFzaz:b-mrbx9i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-MdWXFRa0Lhnk7WGh3lB:b8qpynb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

makes sense -- lets do `PUSH_TOUCH`.
@tbg do you have an opinion?
</blockquote></details>

Sorry, I forgot that `PUSH_TOUCH` doesn't block on conflicting transactions, it errors instead. That's not what we want.

I'm a bit unclear on the concurrency guarantees we have when running this migration. If I understand it correctly, we are guaranteed that no new interleaved intents will be written to the range after the timestamp of the migration request, but active transactions can still own interleaved intents that have already been written.

If that's accurate, and we always want to wait for those transactions to complete first to avoid interfering with the workload, then I believe we should use `PUSH_ABORT` with `MinUserPriority`.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 149 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdWd4Nd4-MoU8oMU12M:-MdWd4Nd4-MoU8oMU12N:bve1cdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/85554e133747a73106fa88402c6fff6e58560ab5/pkg/kv/kvserver/batcheval/cmd_migrate.go#L149)):*
> ```Go
> 	ctx context.Context, reader storage.Reader, cArgs CommandArgs, response roachpb.Response,
> ) (result.Result, error) {
> 	snap := cArgs.EvalCtx.Engine().NewSnapshot()
> ```

I believe Pebble snapshots are lazy, which means that the snapshot isn't actually taken until after the first read. Since we're not reading from the snapshot here, I believe that means we don't actually obtain the snapshot until after we've released our latches and mutexes. This seems like it could cause problems with concurrent operations. Should we make sure we actually take the snapshot during the command evaulation, while latches and mutexes are still held?


<!-- Sent from Reviewable.io -->

2021-07-06 21:08 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-MdxbjAQAH_zh46ynefe:bda6cw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Sorry, I forgot that `PUSH_TOUCH` doesn't block on conflicting transactions, it errors instead. That's not what we want.

I'm a bit unclear on the concurrency guarantees we have when running this migration. If I understand it correctly, we are guaranteed that no new interleaved intents will be written to the range after the timestamp of the migration request, but active transactions can still own interleaved intents that have already been written.

If that's accurate, and we always want to wait for those transactions to complete first to avoid interfering with the workload, then I believe we should use `PUSH_ABORT` with `MinUserPriority`.
</blockquote></details>

Done. And yes, you're correct - no new interleaved transactions will be written after the point when this migration starts. That's the guarantee we're relying on. The second commit on this PR goes ahead and removes the cluster setting that would let that happen.

I've made the PUSH_ABORT and MinUserPriority change. Thanks!
___
*[pkg/kv/kvserver/replica.go, line 1921 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoL4Tl81jCgcNXUrQz:-MdxbeHe5wVht1dvORVI:b-ng5rst) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/kv/kvserver/replica.go#L1921)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Yes, that would be fine.
</blockquote></details>

Done. PTAL - especially the constants driving the rate limiting.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-Mdxc4zV7SE4OXFY1lAA:b-dgj16t) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The `instead of SequenceReq` part is not quite correct since we will execute the loop.

I have a strong opinion on the code structuring for this, which may actually be a nit, and I'm willing to be convinced otherwise.
This behavior is very special case and I'd like the code and code comments to be very clear about this. Which means
- Adding a new interface, say `ReadLatchBarrierProvider` with a `WaitFor(context.Context, roachpb.Span)` method
- Implement it in `managerImpl` (and include it in the `Manager` interface) and plumb it through to `spanlatch.Manager`. The latter can stuff it into a `SpanSet` so it can reuse its implementation methods.
- Call that here by explicitly plucking out the req.Header.Span() for this migrate request.
- Don't declare the header span in `declareKeysMigrateLockTable` -- we don't want anything about this barrier to look like normal latch acquisition.

@nvanbenschoten in case there is a different opinion.
</blockquote></details>

Done. Implemented `WaitFor`, and explicitly special-cased MigrateLockTable here. Thanks!
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 63 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOaRd6-KwO9xbE0I2Q:-MdxcB1R7XOrSsCKpx19:b-tux4ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/batcheval/cmd_migrate.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm assuming the RangeDescriptorKey latch is still needed, yes? It would also be good to clarify why we need it -- if I remember correctly we are using the stronger invariant that this range is not being modified, even though we don't need the range descriptor, only because we expect less contention in this manner. @tbg 
</blockquote></details>

Yes. I'll wait for clarification from Tobias on that, but I believed that latch would guarantee range boundaries wouldn't change while this command was being evaluated.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 149 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdWd4Nd4-MoU8oMU12M:-MdxcGk_9J2McdqvDXzO:bllszq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/85554e133747a73106fa88402c6fff6e58560ab5/pkg/kv/kvserver/batcheval/cmd_migrate.go#L149)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I believe Pebble snapshots are lazy, which means that the snapshot isn't actually taken until after the first read. Since we're not reading from the snapshot here, I believe that means we don't actually obtain the snapshot until after we've released our latches and mutexes. This seems like it could cause problems with concurrent operations. Should we make sure we actually take the snapshot during the command evaulation, while latches and mutexes are still held?
</blockquote></details>

I confirmed in the code and they aren't lazy - the snapshot sequence number is inserted into Pebble's map of all active snapshots right when NewSnapshot is called, so that should be it.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 316 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOkstiESyPZYXGFm8A:-MdxcNPV503ETK0whoIx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/concurrency/concurrency_manager.go#L316)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this change would go away with the structure I was suggesting in the other comment.
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McoK-kR4rUex2u42t2a:-MdxcP9nC_4BM3BUlMzL:b-7yd1q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fde721e7c4e0a1854fb81fc110a8ed7ad41b00/pkg/migration/migrations/separated_intents.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

reminder about this comment
</blockquote></details>

Added a TODO.
___
*[pkg/migration/migrations/separated_intents.go, line 176 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdO3YQPEqmop8Cyx7QN:-Mdxd-70-iwO7K4Q2smQ:bje68kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L176)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand the "tenant cluster" terminology -- is that the cluster with sql-only nodes?
</blockquote></details>

Yes. Replaced "tenant cluster" with "SQL only nodes". We should never get here though, as this is a SystemMigration and not a TenantMigration - maybe I should turn this into a panic?
___
*[pkg/migration/migrations/separated_intents.go, line 211 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOItsb4-h2Y8n_m0-g:-Mdxd5KV3opQwgGS06W6:b-6bne1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L211)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We also need to migrate the range local keys since those can have locks too (e.g. local range descriptor keys). We can do that by constructing another range using `MakeRangeKeyPrefix(start)`, `MakeRangeKeyPrefix(end)`.
Also, it would be good to have test coverage that ensures we don't miss such range local keys in the migrat [...]

2021-07-06 23:07 UTC, nvanbenschoten reviewed
> Reviewed 7 of 24 files at r1, 1 of 8 files at r2, 4 of 11 files at r3, 1 of 37 files at r6, 34 of 43 files at r9, 51 of 52 files at r12, 1 of 28 files at r15, 22 of 24 files at r16, 5 of 5 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/cli/debug.go, line 1345 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxW8kq28PjYblZkyKU:-MdxW8kq28PjYblZkyKV:btrua7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/cli/debug.go#L1345)):*
> ```Go
> 	defer iter.Close()
> 	valid, err := iter.SeekEngineKeyGE(storage.EngineKey{Key: roachpb.KeyMin})
> 	for ; valid && err == nil; valid, err = iter.NextEngineKey() {
> ```

nit: consider adding some progress indicator here. Even just printing `scanned n keys` every 100k keys or something would be helpful.
___
*[pkg/cli/debug.go, line 1364 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxWVN87oLoNaleLwGH:-MdxWVN87oLoNaleLwGI:b-kf1ed8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/cli/debug.go#L1364)):*
> ```Go
> 			continue
> 		}
> 		val := iter.Value()
> ```

`iter.UnsafeValue()` to avoid an allocation and copy.
___
*[pkg/cli/debug.go, line 1365 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxWO3y6euy46z_CDIW:-MdxWO3y6euy46z_CDIX:b-9o6wsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/cli/debug.go#L1365)):*
> ```Go
> 		}
> 		val := iter.Value()
> 		meta := enginepb.MVCCMetadata{}
> ```

Hoist this declaration out of the loop to avoid a per-intent allocation.
___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-Mdy2yig3Fo8H-5XKj0p:bqvqjqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
> I've made the PUSH_ABORT and MinUserPriority change. Thanks!

I'm still seeing `PUSH_TOUCH` and `MaxUserPriority`.
___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-Mdxo54I1hzogT_2fjDF:b-2ptw6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
> As a straw man, could we not instead run a request that gathers a batch of interleaved intents and returns them in the response, using resume spans until done? We could then resolve those intents either here or in the migration job itself, but without having to use this global Pebble snapshot registry.

I think this is a very reasonable idea and has the benefit of avoiding custom code. It trades a bit of performance and we'd still need a custom `ScanInterleavedIntents` request type because a `ScanRequest` with `READ_UNCOMMITTED` doesn't give us quite what we want (it returns committed values and separated intents), but it retains the existing code structure instead of introducing some of this new complexity, which is a big win.

This may also allow us to simplify the control flow in the migration handler (`separatedIntentsMigration`). If we treated the migration as a big scan with limits and resume spans then we could scan the entire keyspace, probably with a `READ_UNCOMMITTED` isolation level, resolve batches of intents whenever we hit a limit, and avoid needing to map keys spans to ranges at all. We could also avoid the custom server-side logic.

If we wanted to distribute computation, we should look into extending DistSQL with a new processor type. That's really what it's meant for, and then this would all start to look a lot like how SQL computes table statistics.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MdxkmZ17Tr6Bh6_kokj:b99mand) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Implemented `WaitFor`, and explicitly special-cased MigrateLockTable here. Thanks!
</blockquote></details>

This seems heavyweight for such a specific use case. What led us away from the standard latching approach? The evaluation of this command is currently so efficient that I don't think this would be particularly disruptive. I guess we would need to acquire a non-MVCC read latch to ensure that we properly synchronize with all in-flight writes, but even that seems reasonable.

But also, the synchronization here seems quite subtle and yet not spelled out anywhere in particular. What makes it necessary? What makes it sufficient? We discuss the special case above, but it's not clear how MigrateLockTable interacts with intent writes. Something else is disabling inline intent writes, right? So this is ensuring that this switch has already been flipped and then all writes after this synchronization write separated intents.

One potential hazard I see from this is that it is relying on clock synchronization. If this request is run on a old leaseholder that still thinks it holds a lease due to skewed clocks, the latching won't be enough to ensure no inline intents are written in the future. To ensure that, we'd need to introduce a barrier that goes through Raft.

This all makes me wonder whether coupling this barrier with the MigrateLockTableRequest is a good idea or whether it would be better to handle the barrier separately.
___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 149 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdWd4Nd4-MoU8oMU12M:-MdxkO7L4Wa8PsU42VfT:b-wm5qn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/85554e133747a73106fa88402c6fff6e58560ab5/pkg/kv/kvserver/batcheval/cmd_migrate.go#L149)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I confirmed in the code and they aren't lazy - the snapshot sequence number is inserted into Pebble's map of all active snapshots right when NewSnapshot is called, so that should be it.
</blockquote></details>

Snapshots aren't lazy, but the iterators grabbed by a `pebbleReadOnly` are.
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 240 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxYotnAF6xNAMvQXj3:-MdxYotnAF6xNAMvQXj4:ba8rz2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/spanlatch/manager.go#L240)):*
> ```Go
> // any latches itself. Fast path for operations that only require past latches
> // to be released without blocking new latches.
> func (m *Manager) WaitWithoutAcquiring(ctx context.Context, spans *spanset.SpanSet) error {
> ```

We should add a test for this method.
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 250 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxYi0LA1LkoJH7WJFT:-MdxYi0LA1LkoJH7WJFU:bxmpern) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/spanlatch/manager.go#L250)):*
> ```Go
> 	m.mu.Unlock()
> 
> 	err := m.wait(ctx, lg, snap)
> ```

nit: `return m.wait(ctx, lg, snap)`
___
*[pkg/migration/migrations/separated_intents.go, line 95 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mdxfh6dB_LAfeZ1QEi6:-Mdxfh6dB_LAfeZ1QEi7:br8seuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L95)):*
> ```Go
> 
> 		select {
> 		case <-ctx.Done():
> ```

nit: `if ctx.Err() != nil {`
___
*[pkg/migration/migrations/separated_intents.go, line 103 at r9](https://reviewable.io/reviews/cockroachdb/coc [...]

2021-07-07 10:11 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_migrate.go, line 149 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdWd4Nd4-MoU8oMU12M:-Me-Qpat17DKkhT711R_:b-oeoh0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/85554e133747a73106fa88402c6fff6e58560ab5/pkg/kv/kvserver/batcheval/cmd_migrate.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Snapshots aren't lazy, but the iterators grabbed by a `pebbleReadOnly` are.
</blockquote></details>

Got it, thanks for the clarification. I've heard `Engine.NewReadOnly()` referred to as a snapshot before, and we had some issues with it being lazy, but I see now that this wasn't accurate.


<!-- Sent from Reviewable.io -->

2021-07-07 12:36 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-Me-sl6l8BfGExyrSwdF:b339ekb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> What led us away from the standard latching approach? The evaluation of this command is currently so efficient that I don't think this would be particularly disruptive. I guess we would need to acquire a non-MVCC read latch to ensure that we properly synchronize with all in-flight writes, but even that seems reasonable.

My reasoning (others may vary) was excessive caution that there be no production hiccups introduced by this request. It may be efficient itself, but once it adds a wide latch and starts waiting, everything that comes after is stuck behind it. So if it needs to wait for a while because there happens to be a long running narrow latching request, we've created a problem. We could try to evaluate this optimistically, especially if we limit the scan it will do, which if it succeeds optimistically is ok (since other requests will still wait behind it, but this request will not wait). But there is the pessimistic eval fallback if the opt eval fails, which gets us back in the same situation.

> One potential hazard I see from this is that it is relying on clock synchronization. If this request is run on a old leaseholder that still thinks it holds a lease due to skewed clocks, the latching won't be enough to ensure no inline intents are written in the future. To ensure that, we'd need to introduce a barrier that goes through Raft.

This is interesting. I am assuming a noop pre-migration like we do in `postSeparatedIntentsMigration` would be insufficient since it would still allow this read-only request to land on an old leaseholder (which would be fine if it were truly a read-only MVCC request, which it isn't).
- How do we currently guard against this for read-only non-MVCC requests -- their successful read latch would be a lie if it were executing on an old leaseholder?
- Is there a safety guarantee provided by a cluster version finalization that could help here, or does it not prevent old leaseholders?
- I'm assuming that writes accepted by the old leaseholder can't be making their way slowly through raft and state machine application since their latches are gone and we would break serializability guarantees if we applied them later -- is that correct?
- Would it be sufficient to check that the lease for the range at this node extends beyond cluster-version-finalization+uncertainty?


<!-- Sent from Reviewable.io -->

2021-07-12 14:52 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MeQ5qMwCLLg1UZWFtQ0:bmdkwxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> How do we currently guard against this for read-only non-MVCC requests -- their successful read latch would be a lie if it were executing on an old leaseholder?

The only read-only non-MVCC request that I'm aware of is SubsumeRequest, which is used during range merges. I don't know whether this was intentional or not, but this is correct even in the face of clock skew because it is always sent after a previous delete to the range's local range descriptor. And new leaseholder check for this deletion tombstone before serving requests, and "subsume themselves" when they notice it.

> Is there a safety guarantee provided by a cluster version finalization that could help here, or does it not prevent old leaseholders?

I'm not sure, as I don't fully understand how the main `MigrateRequest` works. This does go through Raft, and I assume this is part of the reason.

But I don't think there is any guarantee that a leaseholder whose lease expired before the cluster version was finalized can never think it is a leaseholder again after the cluster version finalization.

> I'm assuming that writes accepted by the old leaseholder can't be making their way slowly through raft and state machine application since their latches are gone and we would break serializability guarantees if we applied them later -- is that correct?

Yes, that's correct. Each Raft proposal carries the proposer's lease sequence. Below Raft, we perform a compare-and-swap and ignore "committed" raft entries that are not part of the current lease. We also do something similar using the lease applied index to prevent reorderings within a given lease sequence.

> Would it be sufficient to check that the lease for the range at this node extends beyond cluster-version-finalization+uncertainty?

I don't follow what this would get us because I don't know the semantics of "cluster-version-finalization". Is that an agreed-upon timestamp throughout the cluster? Is this just a clock reading after the cluster version is finalized? Regardless, it still sounds like we'd have a dependency on clocks. Is that correct?

----

One interesting observation is that new leases do go through Raft and they act as a barrier that flushes out in-flight evaluation and in-flight proposals. But of course, they are disruptive, as they block on existing requests and block out new requests. In that sense, they act kind of like an operation using a `memory_order_seq_cst` memory order.

As you pointed out, we'd ideally want the barrier here to be cheaper. Specifically, we're ok blocking on existing requests but not blocking out new requests, kind of like a `memory_order_release` memory order. And that's mostly what we have in this PR. But we might consider generalizing this to a `BarrierRequest` that treats latches like we are doing here, but does go through Raft. I imagine this would be a useful primitive to have in a number of these kinds of cases. And since this wouldn't block on new requests, the pass through Raft would be mostly non-disruptive to other requests operating on the Range.

We could even generalize this barrier/fence request further to support different orderings, though I don't know how useful some of the other ordering (e.g. acquire = "don't wait on latches, but acquire latches") would be.


<!-- Sent from Reviewable.io -->

2021-07-12 19:58 UTC, sumeerbhola requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MeRGhdj2UFblq1C2zps:bf5gg6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> Regardless, it still sounds like we'd have a dependency on clocks. Is that correct?

Yes, and I was not thinking straight when I made that suggestion. We of course can't rely on clock sync for fundamental invariants.

> But we might consider generalizing this to a BarrierRequest that treats latches like we are doing here, but does go through Raft.

So wait for write latches like here, then go through raft without holding any latches, and in post-apply grab a snapshot of the engine?

> I imagine this would be a useful primitive to have in a number of these kinds of cases.

Are these other migration cases?


<!-- Sent from Reviewable.io -->

2021-07-13 00:50 UTC, itsbilal reviewed
There are still some major high-level conversations to resolve here, but I've done a pass and fixed merge conflicts while addressing some of the smaller points brought up in the meantime. Thanks y'all for the detailed review!

> Dismissed @erikgrinaker and @sumeerbhola from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MeSKig648GRtfpmIw3f:b-7z243d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @irfansharif, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica.go, line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDqbFb78qjsH-_PbEI:-Me6d2lS030F_ASiRqVQ:b-3tp9wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica.go#L1950)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I've made the PUSH_ABORT and MinUserPriority change. Thanks!

I'm still seeing `PUSH_TOUCH` and `MaxUserPriority`.
</blockquote></details>

Oops, I forgot to take it off the stash when committing. Done now.
___
*[pkg/kv/kvserver/spanlatch/manager.go, line 240 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxYotnAF6xNAMvQXj3:-MeSHRnV0BtXPTB1ps1v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/spanlatch/manager.go#L240)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should add a test for this method.
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 103 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mdxfohv0rEclMQnEUCG:-MeSIZIO5dOGJylrWxwu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L103)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to log the error here?
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 111 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxgHcr7f78E0VmsMrQ:-MeSIgRe5pX4psaoJ_s-:b-8j34k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L111)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we limit how large this error chain can grow to?
</blockquote></details>

Done. Limited it to 16 chains.
___
*[pkg/migration/migrations/separated_intents.go, line 53 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxhSDI4CgZ-OzxstVj:-MeSHj8nAKrjB5T0Drex:b2neb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/828d46e2e0b32997d2737851c8b9748d7ac7291f/pkg/migration/migrations/separated_intents.go#L53)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we remove the `rangeID` entirely then? You are correct that the mapping from `[start, end)` keys to rangeID is inherently racy. We should try to avoid ever pretending that it's not. `h.IterateRangeDescriptors` will give us a consistent snapshot over the range descriptors [1], so the rangeID was correct at some point and there won't be any gaps between key spans. But the range ID could be wrong for a given key span immediately after we grab it. It doesn't look like we're actually using this for anything too important, so I'd be happy with moving this field below the other two and calling it something like `debugRangeID`.

[1] though is this true @irfansharif? We're only scanning meta2 keys for range descriptors in `IterateRangeDescriptors`. What about range descriptors for the meta ranges themselves, which are stored in meta1?
</blockquote></details>

Good point - yes, the range ID is only being stored for logging purposes. IT's not being used in any of the logic. Updated it to `debugRangeID` to make it clear.
___
*[pkg/migration/migrations/separated_intents.go, line 235 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxiiKT9j-Q4Gc6znHB:-MeSJkQJ7bBR_tOuwme3:b-1m4trr) ([raw file](https://github.com/cockroachdb/cockroach/blob/828d46e2e0b32997d2737851c8b9748d7ac7291f/pkg/migration/migrations/separated_intents.go#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this going to block? Will that hold open the txn in `IterateRangeDescriptors` for most of the duration of the migration? That's probably ok because the txn is read-only, but this still may run into issues with a low GC TTL if we're not careful. I wonder whether we should change this structure to look more like a `RangeIterator`. Is there a benefit to the consistent meta2 scan?
</blockquote></details>

Would a RangeIterator-type thing not need a txn / do an inconsistent scan? Currently we rely on the txn to give us one consistent snapshot of range descriptors, but maybe we can cover the entirety of the keyspace without it. You'll know better.


<!-- Sent from Reviewable.io -->

2021-07-15 14:56 UTC, itsbilal reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @irfansharif, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-Meeeeol6HjHANPnD0G_:b-s4s166) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> Regardless, it still sounds like we'd have a dependency on clocks. Is that correct?

Yes, and I was not thinking straight when I made that suggestion. We of course can't rely on clock sync for fundamental invariants.

> But we might consider generalizing this to a BarrierRequest that treats latches like we are doing here, but does go through Raft.

So wait for write latches like here, then go through raft without holding any latches, and in post-apply grab a snapshot of the engine?

> I imagine this would be a useful primitive to have in a number of these kinds of cases.

Are these other migration cases?

</blockquote></details>

I added a `BarrierRequest` that is a write request (so it goes through raft), and calls `WaitFor`. Reviews welcome.


<!-- Sent from Reviewable.io -->

2021-07-15 18:07 UTC, sumeerbhola requested changes
> Reviewed 2 of 43 files at r21.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @irfansharif, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MefK7jVD7bXqN2kz9fZ:bwtgai2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I added a `BarrierRequest` that is a write request (so it goes through raft), and calls `WaitFor`. Reviews welcome.
</blockquote></details>

- is MigrateLockTableRequest always paired with BarrierRequest in the same batch?
- is the snapshot grabbed after the BarrierRequest has successfully committed via raft, so we know that we are on a current leaseholder?
- looks like nothing is added the `storage.ReadWriter` when executing BarrierRequest. Will an empty `storage.Batch` be optimized away to not go through raft?


<!-- Sent from Reviewable.io -->

2021-07-15 18:23 UTC, nvanbenschoten reviewed
> Reviewed 7 of 40 files at r18, 16 of 43 files at r21, 19 of 24 files at r22, 8 of 8 files at r23.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MefJWtrBXUt489kVkkb:bp5xylb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> and in post-apply grab a snapshot of the engine?

I was thinking that we would keep these requests entirely separate, as it looks like Bilal has done. I don't see a compelling reason to couple them together. EDIT: unless the concern there is that splitting the requests permits a hazard where we flush all writes on the real leaseholder but then run the Migration on an old leaseholder due to clock skew. That does seem like a real concern.

One benefit to this is that we can re-use this `BarrierRequest` if we have other cases where we want to flush out in-flight writes.

Another is that if we do this, we have fewer constraints placed on the `MigrateLockTableRequest`. We don't need to acquire any latches for it (other than the range desc key) and it becomes more reasonable to scan the range during evaluation and collect and return a batch of intents with a resume span instead of needing to leak an LSM snapshot. We still wouldn't want to rate limit or resolve intents during evaluation (for similar reasons to https://github.com/cockroachdb/cockroach/issues/66486), but the client-side logic would be a lot more straightforward.

> looks like nothing is added the storage.ReadWriter when executing BarrierRequest. Will an empty storage.Batch be optimized away to not go through raft?

I had the same concern. We'll need to make sure it doesn't get optimized away.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MefN32hEyNFZCYnHNpf:-MefN32hEyNFZCYnHNpg:bkk3811) ([raw file](https://github.com/cockroachdb/cockroach/blob/617337d8b2962be9c9ba83772626d0a7288f7bbd/pkg/kv/kvserver/replica_send.go#L368)):*
> ```Go
> 	for i := range ba.Requests {
> 		if br := ba.Requests[i].GetBarrier(); br != nil {
> 			// Special case: The barrier request needs to wait for
> ```

I think we should try to avoid making this quite as special of a case, at least in terms of control flow in this method. Perhaps we can introduce a new boolean flag on `concurrency.Request` called `LatchBarrier` (or something) and set it to `ba.IsSingleBarrierRequest()`. We could then push this complexity into `(*concurrency.Manager).SequenceReq`.
___
*[pkg/migration/migrations/separated_intents.go, line 235 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxiiKT9j-Q4Gc6znHB:-MefOEyW-RDOB4iIS8Je:b-ovy8kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/828d46e2e0b32997d2737851c8b9748d7ac7291f/pkg/migration/migrations/separated_intents.go#L235)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Would a RangeIterator-type thing not need a txn / do an inconsistent scan? Currently we rely on the txn to give us one consistent snapshot of range descriptors, but maybe we can cover the entirety of the keyspace without it. You'll know better.
</blockquote></details>

A RangeIterator won't necessarily return a consistent snapshot of the meta2 keyspace, but it also won't result in gaps. I can't think of a reason why we need a consistent snapshot of the meta2 keyspace, can you?


<!-- Sent from Reviewable.io -->

2021-07-15 21:05 UTC, sumeerbhola reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MefbJdvEXjM9xMAEDCy:bmmg13z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> unless the concern there is that splitting the requests permits a hazard where we flush all writes on the real leaseholder but then run the Migration on an old leaseholder due to clock skew. That does seem like a real concern.

exactly


<!-- Sent from Reviewable.io -->

2021-07-19 20:54 UTC, itsbilal reviewed
Another fairly large refactor, major changes being:

1) Barrier is actually called now, and is a write command to go through the right leaseholder. Still need to verify if empty batch won't be elided.
2) `MigrateLockTable` is now `ScanInterleavedIntents` and returns intents encountered
3) The pool of workers in the migration code itself is what pushes txns and resolves intents now
4) The benchmark was hard to maintain with the new code structure so I removed it.
5) RangeIterator is now used instead of the consistent scan of range descriptors.

PTAL and thanks for the detailed reviews so far!

> Dismissed @erikgrinaker from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mf-X9VV8clEkKjWrB0W:b-93t07p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-Mf-Xclm4hmnciIX0Iwj:bk89rum) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> As a straw man, could we not instead run a request that gathers a batch of interleaved intents and returns them in the response, using resume spans until done? We could then resolve those intents either here or in the migration job itself, but without having to use this global Pebble snapshot registry.

I think this is a very reasonable idea and has the benefit of avoiding custom code. It trades a bit of performance and we'd still need a custom `ScanInterleavedIntents` request type because a `ScanRequest` with `READ_UNCOMMITTED` doesn't give us quite what we want (it returns committed values and separated intents), but it retains the existing code structure instead of introducing some of this new complexity, which is a big win.

This may also allow us to simplify the control flow in the migration handler (`separatedIntentsMigration`). If we treated the migration as a big scan with limits and resume spans then we could scan the entire keyspace, probably with a `READ_UNCOMMITTED` isolation level, resolve batches of intents whenever we hit a limit, and avoid needing to map keys spans to ranges at all. We could also avoid the custom server-side logic.

If we wanted to distribute computation, we should look into extending DistSQL with a new processor type. That's really what it's meant for, and then this would all start to look a lot like how SQL computes table statistics.
</blockquote></details>

Done. No more snapshot registry or custom send-time logic. There's `ScanInterleavedIntents` now - ptal!
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-Mf-XkglBcEENr17OsZz:b-1ecmym) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> unless the concern there is that splitting the requests permits a hazard where we flush all writes on the real leaseholder but then run the Migration on an old leaseholder due to clock skew. That does seem like a real concern.

exactly
</blockquote></details>

TODO for me: to verify if the empty batch won't be elided away.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MefN32hEyNFZCYnHNpf:-MeftM0G5ccxaZKLdO_f:bwl1qes) ([raw file](https://github.com/cockroachdb/cockroach/blob/617337d8b2962be9c9ba83772626d0a7288f7bbd/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we should try to avoid making this quite as special of a case, at least in terms of control flow in this method. Perhaps we can introduce a new boolean flag on `concurrency.Request` called `LatchBarrier` (or something) and set it to `ba.IsSingleBarrierRequest()`. We could then push this complexity into `(*concurrency.Manager).SequenceReq`.
</blockquote></details>

This is pretty different from the control flow that @sumeerbhola  was desiring - he wanted us to explicitly not go into SequenceReq. I could go ahead and do that, but you can see his argument earlier up on making this seem like an explicitly different code path.
___
*[pkg/migration/migrations/separated_intents.go, line 235 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdxiiKT9j-Q4Gc6znHB:-Mefsza97MS7fGjbWX9K:buqrtv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/828d46e2e0b32997d2737851c8b9748d7ac7291f/pkg/migration/migrations/separated_intents.go#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

A RangeIterator won't necessarily return a consistent snapshot of the meta2 keyspace, but it also won't result in gaps. I can't think of a reason why we need a consistent snapshot of the meta2 keyspace, can you?
</blockquote></details>

Done. Using a RangeIterator now; PTAL.


<!-- Sent from Reviewable.io -->

2021-07-21 20:09 UTC, nvanbenschoten reviewed
The last change was a major improvement! I've left a collection of comments, but this all seems to be moving in the right direction.

> Reviewed 4 of 52 files at r12, 2 of 40 files at r18, 2 of 43 files at r21, 50 of 50 files at r24, 21 of 21 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mf9dnBU4Ng45ajJgXUP:b-h9ag2u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/batch.go, line 821 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9awG47GgfeFWYX5Gg:-Mf9awG47GgfeFWYX5Gh:b2lmv46) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/batch.go#L821)):*
> ```Go
> }
> 
> func (b *Batch) scanInterleavedIntents(s, e interface{}) {
> ```

FWIW, I think it's fine if we want to omit these operations from the "typed" `Batch` interface and force users to use the `AddRawRequest` interface.
___
*[pkg/kv/kvserver/replica.go, line 118 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9X1-99WTcqpDkT3Hk:-Mf9X1-99WTcqpDkT3Hl:b4o3121) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/replica.go#L118)):*
> ```Go
> )
> 
> // SeparatedIntentMigrationScanRate wraps "kv.separated_intent_migration.max_scan_rate".
> ```

Is this still used?
___
*[pkg/kv/kvserver/replica.go, line 132 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9X3h615DAhSuXKt-U:-Mf9X3h615DAhSuXKt-V:b4o3121) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/replica.go#L132)):*
> ```Go
> 
> // Scan rate burst value for the separated intent migration.
> const separatedIntentMigrationBurst = 4 << 20 // 4 MB
> ```

Is this still used?
___
*[pkg/kv/kvserver/replica.go, line 837 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9X9306Bvc07qn9bzA:-Mf9X9306Bvc07qn9bzB:b4o3121) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/replica.go#L837)):*
> ```Go
> }
> 
> // NewLongLivedSnapshot returns a new snapshot of the underlying Engine.
> ```

Is this still used?
___
*[pkg/kv/kvserver/replica_send.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McDt1E5C3h11xmHy6dt:-Mf9fvt9EZ2Qqr0e5pcE:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dce6ed2038be617de6c6235cd193601f5752807/pkg/kv/kvserver/replica_send.go#L137)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. No more snapshot registry or custom send-time logic. There's `ScanInterleavedIntents` now - ptal!
</blockquote></details>

Nice!
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-Mf9a9qmB9lk0ZLBE9tM:b-2ktfs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
> unless the concern there is that splitting the requests permits a hazard where we flush all writes on the real leaseholder but then run the Migration on an old leaseholder due to clock skew. That does seem like a real concern.

I think a solution to this that doesn't require us to merge the `BarrierRequest` and the `ScanInterleavedIntentsRequest` is to return a timestamp from `BarrierRequest` (grabbed during evaluation) and then to set that as the `Timestamp` field in the header of the `ScanInterleavedIntentsRequest`. This will ensure that the leaseholder that evaluates the `ScanInterleavedIntentsRequest` is either the same leaseholder that evaluated the BarrierRequest or a newer one.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MefN32hEyNFZCYnHNpf:-Mf9YdDI2yN4xQeMgMCt:bdms0dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/617337d8b2962be9c9ba83772626d0a7288f7bbd/pkg/kv/kvserver/replica_send.go#L368)):*
> he wanted us to explicitly not go into SequenceReq

We're going into SequenceReq either way, right? This is just a question of whether we call into `latchManager.WaitFor` from within the concurrency manager or not. I agree that we should be explicit about the behavior of a `BarrierRequest`, but I don't think this is the right place to do so. It's expanding the surface area of the concurrency manager (i.e. `ReadLatchBarrierProvider`) and placing a large burden on the user of the interface doing the right thing. It also doesn't parallel some of the special handling we have around lease requests within the concurrency manager (see `shouldAcquireLatches`).

Instead, I would recommend pushing it into `(*managerImpl).sequenceReqWithGuard` through logic that looks like:
```
diff --git a/pkg/kv/kvserver/concurrency/concurrency_manager.go b/pkg/kv/kvserver/concurrency/concurrency_manager.go
index 9cedf1e598..d2987012d0 100644
--- a/pkg/kv/kvserver/concurrency/concurrency_manager.go
+++ b/pkg/kv/kvserver/concurrency/concurrency_manager.go
@@ -174,6 +174,12 @@ func (m *managerImpl) sequenceReqWithGuard(ctx context.Context, g *Guard) (Respo
                return nil, nil
        }

+       // Some requests wait on latches, but don't acquire them.
+       if shouldWaitOnLatchesWithoutAcquiring(g.Req) {
+               log.Event(ctx, "waiting on latches without acquiring")
+               return nil, m.lm.WaitFor(ctx, ...)
+       }
+
        // Provide the manager with an opportunity to intercept the request. It
        // may be able to serve the request directly, and even if not, it may be
        // able to update its internal state based on the request.
@@ -309,6 +315,11 @@ func shouldAcquireLatches(req Request) bool {
        return true
 }

+// shouldWaitOnLatchesWithoutAcquiring ...
+func shouldWaitOnLatchesWithoutAcquiring(req Request) bool {
+       return req.isSingle(roachpb.Barrier)
+}
+
 // FinishReq implements the RequestSequencer interface.
 func (m *managerImpl) FinishReq(g *Guard) {
        // NOTE: we release latches _before_ exiting lock wait-queues deliberately.
```
This allows us to test this more directly in a test like `pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches`.
___
*[pkg/kv/kvserver/replica_send.go, line 48 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9YP1z5WJjGgyyDVpy:-Mf9YP1z5WJjGgyyDVpz:bze417v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/replica_send.go#L48)):*
> ```Go
> }
> 
> type keyAndIntent struct {
> ```

Stale?
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 23 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9apWb-gx8mmk1bwJx:-Mf9apWb-gx8mmk1bwJy:b-m8suqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/batcheval/cmd_barrier.go#L23)):*
> ```Go
> 
> func init() {
> 	RegisterReadWriteCommand(roachpb.Barrier, declareKeysMigrate, Barrier)
> ```

s/declareKeysMigrate/declareKeysBarrier/
___
*[pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go, line 42 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9T9V_8EswUDj5h4aR:-Mf9T9V_8EswUDj5h4aS:b-xp084h) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go#L42)):*
> ```Go
> 	ctx context.Context, reader storage.Reader, cArgs CommandArgs, response roachpb.Response,
> ) (result.Result, error) {
> 	//snap := cArgs.EvalCtx.NewLongLivedSnapshot()
> ```

We can remove this, right? And all references to `NewLongLivedSnapshot()`?
___
*[pkg/kv/kvserver/batcheval/eval_context.go, line 123 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9XCKz2Y8pSPyAsRJi:-Mf9XCKz2Y8pSPyAsRJj:b4o3121) ([raw file](https://github.com/cockroa [...]

2021-07-28 19:20 UTC, itsbilal reviewed
TFTR!

> Dismissed @erikgrinaker and @sumeerbhola from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MfiYtVkDvoDRA5LClzP:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/batch.go, line 821 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9awG47GgfeFWYX5Gg:-MfdL3KZ2reOElWntyyN:bjrj3ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/batch.go#L821)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

FWIW, I think it's fine if we want to omit these operations from the "typed" `Batch` interface and force users to use the `AddRawRequest` interface.
</blockquote></details>

Seems cleaner to leave it in place - unless you feel strongly about this?
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOfOufAaO3Sg7jqiJ3:-MfiLHSCARiZkXKQsSAP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> unless the concern there is that splitting the requests permits a hazard where we flush all writes on the real leaseholder but then run the Migration on an old leaseholder due to clock skew. That does seem like a real concern.

I think a solution to this that doesn't require us to merge the `BarrierRequest` and the `ScanInterleavedIntentsRequest` is to return a timestamp from `BarrierRequest` (grabbed during evaluation) and then to set that as the `Timestamp` field in the header of the `ScanInterleavedIntentsRequest`. This will ensure that the leaseholder that evaluates the `ScanInterleavedIntentsRequest` is either the same leaseholder that evaluated the BarrierRequest or a newer one.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_send.go, line 368 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MefN32hEyNFZCYnHNpf:-MfekteUBeqTlXbXf13O:b770ccz) ([raw file](https://github.com/cockroachdb/cockroach/blob/617337d8b2962be9c9ba83772626d0a7288f7bbd/pkg/kv/kvserver/replica_send.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> he wanted us to explicitly not go into SequenceReq

We're going into SequenceReq either way, right? This is just a question of whether we call into `latchManager.WaitFor` from within the concurrency manager or not. I agree that we should be explicit about the behavior of a `BarrierRequest`, but I don't think this is the right place to do so. It's expanding the surface area of the concurrency manager (i.e. `ReadLatchBarrierProvider`) and placing a large burden on the user of the interface doing the right thing. It also doesn't parallel some of the special handling we have around lease requests within the concurrency manager (see `shouldAcquireLatches`).

Instead, I would recommend pushing it into `(*managerImpl).sequenceReqWithGuard` through logic that looks like:
```
diff --git a/pkg/kv/kvserver/concurrency/concurrency_manager.go b/pkg/kv/kvserver/concurrency/concurrency_manager.go
index 9cedf1e598..d2987012d0 100644
--- a/pkg/kv/kvserver/concurrency/concurrency_manager.go
+++ b/pkg/kv/kvserver/concurrency/concurrency_manager.go
@@ -174,6 +174,12 @@ func (m *managerImpl) sequenceReqWithGuard(ctx context.Context, g *Guard) (Respo
                return nil, nil
        }

+       // Some requests wait on latches, but don't acquire them.
+       if shouldWaitOnLatchesWithoutAcquiring(g.Req) {
+               log.Event(ctx, "waiting on latches without acquiring")
+               return nil, m.lm.WaitFor(ctx, ...)
+       }
+
        // Provide the manager with an opportunity to intercept the request. It
        // may be able to serve the request directly, and even if not, it may be
        // able to update its internal state based on the request.
@@ -309,6 +315,11 @@ func shouldAcquireLatches(req Request) bool {
        return true
 }

+// shouldWaitOnLatchesWithoutAcquiring ...
+func shouldWaitOnLatchesWithoutAcquiring(req Request) bool {
+       return req.isSingle(roachpb.Barrier)
+}
+
 // FinishReq implements the RequestSequencer interface.
 func (m *managerImpl) FinishReq(g *Guard) {
        // NOTE: we release latches _before_ exiting lock wait-queues deliberately.
```
This allows us to test this more directly in a test like `pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches`.
</blockquote></details>

Done. Thanks for the specific suggestion!
___
*[pkg/kv/kvserver/replica_send.go, line 48 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9YP1z5WJjGgyyDVpy:-MfdLVU69EL35odVpt67:b79glk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/replica_send.go#L48)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Stale?
</blockquote></details>

Yep, removed.
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 23 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9apWb-gx8mmk1bwJx:-MfdPLua6lY8DTt63UgI:b-a4wcvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/batcheval/cmd_barrier.go#L23)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/declareKeysMigrate/declareKeysBarrier/
</blockquote></details>

Oops. Done.
___
*[pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go, line 42 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9T9V_8EswUDj5h4aR:-MfdPNmw8xjxh8phklFk:bjg6x97) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/kvserver/batcheval/cmd_scan_interleaved_intents.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We can remove this, right? And all references to `NewLongLivedSnapshot()`?
</blockquote></details>

Yep. Done.
___
*[pkg/migration/migrations/separated_intents.go, line 88 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9eKeB6sipIxODHVt3:-MfdkXvH0IZlqcDBgge6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b2354d6924ad0c08e7ffba02fd3f6c37f8da4/pkg/migration/migrations/separated_intents.go#L88)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is essentially the same thing as `roachpb.Intent`, so if you switch over to using that in `ScanInterleavedIntents`, you won't need it.
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents_external_test.go, line 35 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9d0X81OUa7HjwZiRq:-MfiLK1S46_ZYpiaCRyk:b-374w0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/migration/migrations/separated_intents_external_test.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Have we thought of other ways that we could try to add runtime assertions against bugs in this migration to improve testing coverage? For instance, maybe the GC queue could read the migration key before beginning to process a range and then assert that it finds no inline intents?
</blockquote></details>

The GC queue could be a good place for that check. Another could be to just have the intentInterleavingIter panic if it ever sees an actually-interleaved intent through the mvcc iterator. I could go ahead and add those; we haven't paid too much attention to it yet.
___
*[pkg/migration/migrations/separated_intents_ext [...]

2021-07-29 23:34 UTC, nvanbenschoten reviewed
> Reviewed 26 of 50 files at r26, 24 of 24 files at r27.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @sumeerbhola, and @tbg)

___
*[pkg/kv/batch.go, line 821 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9awG47GgfeFWYX5Gg:-MfoNV0aCvxVizRLUbzM:bhbfq14) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/kv/batch.go#L821)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Seems cleaner to leave it in place - unless you feel strongly about this?
</blockquote></details>

No strong feelings.
___
*[pkg/kv/kvserver/replica_send.go, line 346 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoNnqZDei4SdO_6-y0:-MfoNnqZDei4SdO_6-y1:bkbgnnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/replica_send.go#L346)):*
> ```Go
> 		}
> 	}()
> ```

nit: might as well avoid the diff on this stray line, now that we're down to just one line in this file.
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MfoWgoo7RoYVL4gBsA7:bcj6mm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
> ```Go
> 	// grab these latches. Instead, any conflicting latches with these are waited
> 	// on, but new latches aren't inserted.
> 	latchSpans.AddMVCC(spanset.SpanReadOnly, req.Header().Span(), hlc.MaxTimestamp)
> ```

I think we can use `declareAllKeys` here. One important difference between `declareAllKeys` and the approach here is that `declareAllKeys` includes local spans.

The change in `SpanAccess` also brings up the question of whether this request should only wait on all in-flight writes or whether it should wait on all in-flight reads or writes. My thinking is that it should wait on all reads and writes unless there's a very good reason for it not to.
___
*[pkg/kv/kvserver/concurrency/concurrency_control.go, line 458 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoXR3xAuLmJGFrXdmB:-MfoXR3y-_P2Of0yneX2:b-cmdqsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/concurrency_control.go#L458)):*
> ```Go
> 	WaitUntilAcquired(ctx context.Context, lg latchGuard) (latchGuard, *Error)
> 
> 	// WaitFor waits for write latches on the specified spans without adding any
> ```

"waits for write latches on"

I think this should be "waits for conflicting latches on".
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 356 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoXoNm-LoRk9AfBBk3:-MfoXoNm-LoRk9AfBBk4:b-y32d4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/concurrency_manager.go#L356)):*
> ```Go
> }
> 
> // shouldWaitOnLatchesWithoutAcquiring determines if this is a request that
> ```

nit: move this below `shouldAcquireLatches`, since it's called after.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 368 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoY2W-8KZdl_vqGC3Q:-MfoY2W-8KZdl_vqGC3R:b-tbroql) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/concurrency_manager.go#L368)):*
> ```Go
> // return true for shouldWaitOnLatchesWithoutAcquiring could also return true
> // here, even though latches won't be acquired there.
> func shouldAcquireLatches(req Request) bool {
> ```

Do you think the name of this should be changed since the semantics are a little different now? Maybe `ignoresLatches`?
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches, line 54 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoYjGsCF__eLGn87sZ:-MfoYjGsCF__eLGn87s_:bfpgsn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches#L54)):*
> ```
> 
> # -------------------------------------------------------------
> # Barrier requests do not acquire latches
> ```

Nice. Consider extending this further in the following ways:
- move this to a new `barrier` file
- keep this as the first "subtest"
- add a second subtest that sequences a read, then sequences a barrier and ensures that the barrier latching blocks, then finishes the read and ensures that the barrier completes sequencing
- add a third subtest that does the same with a write
- add a fourth subtest that sequences a barrier and ensures that neither a read on overlapping key nor a write on a different overlapping key block
___
*[pkg/migration/migrations/separated_intents.go, line 275 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9eUsoB9UObwUgNhUq:-MfobDWDCT1zamMKY6yv:b-3vujoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b2354d6924ad0c08e7ffba02fd3f6c37f8da4/pkg/migration/migrations/separated_intents.go#L275)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I wonder whether we would feel better about this testing if we mocked this all just a bit more, such that we could make it all deterministic. Having a test that runs with a test cluster is important, but it's also testing from quite a distance away, and so we're only testing the end-to-end outcome (of a relatively simple setup) and not the steps to get there.

I'd imagine that extracting a few dependencies would allow us to make tighter assertions about the requests that are sent and the migration's behavior in the presence of various edge cases. For instance, it would allow us to test the behavior of the testing harness with resume spans. And allow us to test error handling logic.

I don't know if it's realistic or not, but a north star to aim for would be to mock out the dependencies here sufficiently such that you could test this in a custom data-driven framework.
</blockquote></details>

Did you give any thought to this?
___
*[pkg/migration/migrations/separated_intents_external_test.go, line 35 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9d0X81OUa7HjwZiRq:-MfobA_HC0eMv_N32NJ6:b-m5b9f4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/migration/migrations/separated_intents_external_test.go#L35)):*
> Another could be to just have the intentInterleavingIter panic if it ever sees an actually-interleaved intent through the mvcc iterator.

This sounds like a good idea.
___
*[pkg/migration/migrations/separated_intents_external_test.go, line 125 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9cvuV0ZagU0XWVtm8:-MfobLw49gC0S4Li9xMN:bm4bi0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/migration/migrations/separated_intents_external_test.go#L125)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Any ideas on how we'd do that?
</blockquote></details>

This won't be easy to do through SQL, but if you can get your hands on a `kv.DB` then it should be pretty straightforward.
___
*[pkg/roachpb/api.proto, line 1744 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9XkTG15XTf58eJQBc:-MfoZeax-MoOhwG4ztNh:b-8yvu55) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/roachpb/api.proto#L1744)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I don't see that being used elsewhere in any Response so I went with KeyValue for consistency - but I did replace `keyAndIntent [...]

2021-07-30 17:55 UTC, ajwerner reviewed
Didn't look at the `kvserver` stuff, just the migration stuff. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MfsYbzU0VQBY-nPrGdN:b-z81v23)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/migration/system_migration.go, line 38 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsUHVCAdHmY_CNYlnD:-MfsUHVCAdHmY_CNYlnE:biadxob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/system_migration.go#L38)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	// DB returns access to the kv.
> 	DB() *kv.DB
> 	// DistSender returns access to the DistSender for communicating with the
> 	// kv store.
> 	DistSender() *kvcoord.DistSender
> 	// Stopper returns a reference to a Stopper for spawning new tasks.
> 	Stopper() *stop.Stopper
> ```
</details>

How upset would you be if I asked you to create a new struct `SystemDeps` that was parallel to `TenantDeps` and define it like:

```go
package migration

// SystemDeps are the dependencies of migrations which perform actions at the
// KV layer on behalf of the system tenant.
type SystemDeps struct {
     Cluster Cluster
     DB        *kv.DB
     DistSender *kvcoord.DistSender
     Stopper *stop.Stopper
}

// SystemMigrationFunc is used to perform kv-level migrations. It should only be
// run from the system tenant.
type SystemMigrationFunc func(context.Context, clusterversion.ClusterVersion, SystemDeps) error
```

I don't think we're getting a lot of value in growing the Cluster interface. Having a container for explicit dependencies feels cleaner. This will also give us a place to stick functionality like job checkpointing. 
___
*[pkg/migration/migrations/migrations.go, line 77 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsVZNm1NcDtKtDBUkI:-MfsVZNn4b_hBMlqSBbc:bcqko93) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/migrations/migrations.go#L77)):*
> ```Go
> 	migration.NewSystemMigration(
> 		"move over all intents to separate lock table",
> 		toCV(clusterversion.SeparatedIntentsMigration),
> ```

Just to confirm, we stopped writing interleaved intents before this migration, right? 
___
*[pkg/migration/migrations/separated_intents.go, line 176 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdO3YQPEqmop8Cyx7QN:-MfsW7XUBQIi1SjG4F_c:b-tqo0fp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L176)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes. Replaced "tenant cluster" with "SQL only nodes". We should never get here though, as this is a SystemMigration and not a TenantMigration - maybe I should turn this into a panic?
</blockquote></details>

You should not need this. In fact, I don't like it because you should not need this. `System` migrations are not run on secondary tenants. 
___
*[pkg/migration/migrations/separated_intents.go, line 275 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9eUsoB9UObwUgNhUq:-MfsX8v36ZnXV7KH0GfS:bxayyc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b2354d6924ad0c08e7ffba02fd3f6c37f8da4/pkg/migration/migrations/separated_intents.go#L275)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you give any thought to this?
</blockquote></details>

I think if I were to take a stab at this, I'd do it by using `MakeMockTxnSenderFactory` and mocking out all of kvserver. It'd take some machinery but I have a feeling you could make it bear fruit without too much pain. 
___
*[pkg/migration/migrations/separated_intents.go, line 318 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsWIP35m0asMp9-Cos:-MfsWIP35m0asMp9-Cot:b29kpgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/migrations/separated_intents.go#L318)):*
> ```
> 		// Check if this range only contains timeseries keys. If it is, we can
> 		// just skip it - it will not contain any intents.
> ```
nit: grammar feels a tad off. 
___
*[pkg/migration/migrations/separated_intents.go, line 319 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsWa5N-isK_Yp1uDfB:-MfsWa5N-isK_Yp1uDfC:b19jp7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/migrations/separated_intents.go#L319)):*
> ```Go
> 		// Check if this range only contains timeseries keys. If it is, we can
> 		// just skip it - it will not contain any intents.
> 		if bytes.HasPrefix(start, keys.TimeseriesPrefix) && bytes.HasPrefix(end, keys.TimeseriesPrefix) {
> ```

nit: pull this into a helper


<!-- Sent from Reviewable.io -->

2021-08-03 18:38 UTC, sumeerbhola reviewed
@itsbilal I read through a bunch of this today and it looks like it is nearing the finish line, and looking clean, with most of the remaining stuff related to testing. Let me know if there is something specific you need me to look at.

> Reviewed 1 of 40 files at r18, 3 of 50 files at r24, 11 of 50 files at r26, 3 of 24 files at r27, 3 of 7 files at r28.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgCI54Z7xoUDW2a2kmF:b7p82f1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MgCFcZv07In2By0Z1tk:b-kpeq62) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
> My thinking is that it should wait on all reads and writes unless there's a very good reason for it not to.

I didn't understand this part. Why? Also if we use `SpanReadWrite` here it will wait for reads at higher timestamps, which is none. What am I missing?


<!-- Sent from Reviewable.io -->

2021-08-04 16:45 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @sumeerbhola, and @tbg)

___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MgH1rsl0MP6PFw5ZgWD:bszkvl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
> I didn't understand this part. Why?

To make the Barrier request less special purpose, so that it can become a more general tool for flushing out in-flight requests on a range. But I don't feel strongly about this and I think you could also make an argument that this will never be sufficient to flush out in-flight reads because they could be evaluating on followers if they have a low enough timestamp.


<!-- Sent from Reviewable.io -->

2021-08-05 21:48 UTC, itsbilal reviewed
TFTRs! The only big remaining changes seem to be:

1) Mocked out unit tests for most of the migration's tricky cases (WIP, should be ready soon)
2) Breaking up the `cluster` interface.

Everything else should be ready for a review. Stability period is in sight so I'd rather get this in at some point next week, which means I should wrap up all of the above by end of this week (so, tomorrow). I'm sure none of us are a fan of the time bound, but it is preferable to letting interleaved intents stick around for another release.

> Dismissed @sumeerbhola and @tbg from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgNGqpjDapMMUcGNBOJ:b535iyt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MgM5-36AlU3fDiZtbMa:btm2a7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> I didn't understand this part. Why?

To make the Barrier request less special purpose, so that it can become a more general tool for flushing out in-flight requests on a range. But I don't feel strongly about this and I think you could also make an argument that this will never be sufficient to flush out in-flight reads because they could be evaluating on followers if they have a low enough timestamp.
</blockquote></details>

Isn't another key distinction between `declareAllKeys` and this the fact that `declareAllKeys` will not follow the header's span? Is that preferable to what we have here? I've changed the SpanAccess to `ReadWrite` now, and updated comments.
___
*[pkg/kv/kvserver/concurrency/concurrency_manager.go, line 368 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoY2W-8KZdl_vqGC3Q:-MgM7Dyc6FVV7rzg0Cdk:b-66bmlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/concurrency_manager.go#L368)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think the name of this should be changed since the semantics are a little different now? Maybe `ignoresLatches`?
</blockquote></details>

Good point. It's now `shouldIgnoreLatches`. 
___
*[pkg/migration/migrations/migrations.go, line 77 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsVZNm1NcDtKtDBUkI:-MgM8HJU99Vj_vgTMN-Q:bafevh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/migrations/migrations.go#L77)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Just to confirm, we stopped writing interleaved intents before this migration, right? 
</blockquote></details>

Yes. That change is already checked into master; the one where we made the cluster setting default. This PR removes the ability to even change the cluster setting (in the second commit).
___
*[pkg/migration/migrations/separated_intents.go, line 176 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdO3YQPEqmop8Cyx7QN:-MgM8R2219SuiD_JmDhI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L176)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

You should not need this. In fact, I don't like it because you should not need this. `System` migrations are not run on secondary tenants. 
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 275 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9eUsoB9UObwUgNhUq:-MgNGjFl1Wevws5bkVbR:b-3aq3oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b2354d6924ad0c08e7ffba02fd3f6c37f8da4/pkg/migration/migrations/separated_intents.go#L275)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think if I were to take a stab at this, I'd do it by using `MakeMockTxnSenderFactory` and mocking out all of kvserver. It'd take some machinery but I have a feeling you could make it bear fruit without too much pain. 
</blockquote></details>

Working on this - it's a bit of a lift but I should have this ready by tomorow. 
___
*[pkg/migration/migrations/separated_intents_external_test.go, line 35 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9d0X81OUa7HjwZiRq:-MgMM7OhA-EIvOfsKrY3:b-lwcus6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/migration/migrations/separated_intents_external_test.go#L35)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Another could be to just have the intentInterleavingIter panic if it ever sees an actually-interleaved intent through the mvcc iterator.

This sounds like a good idea.
</blockquote></details>

I would prefer to defer the assertions to a future PR - mostly because this one is already large enough as-is.
___
*[pkg/roachpb/api.proto, line 1744 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9XkTG15XTf58eJQBc:-MgMKUuX2yNDERPoS4aG:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/roachpb/api.proto#L1744)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This isn't a KeyValue in the traditional sense, though. When a ScanResponse includes `intent_rows`, they're not the encoded transaction metadata key, they're the provisional key-values. Here, we're actually returning the metadata key, which is pretty funky.

I don't think there's a problem with returning `roachpb.Intent` in the KV API. That's essentially what `ResolveIntentRequest` carries, it's just not packages up in an `Intent` for compatibility reasons. And it is already part of the KV API in that a few error protos include `roachpb.Intent` fields.
</blockquote></details>

Good point. Done.
___
*[pkg/roachpb/api.proto, line 1748 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mf9XxEa07qnJ3g0NnfG:-MgM9k0S8kmQHN1K_CJB:b-3flzy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac1672aa930fb31aa205361d3e12c4c1eeaed78/pkg/roachpb/api.proto#L1748)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not as much asking what the code currently does, but what it should be doing :) Is there a reason why we only want this to block on writes? Doesn't that limit the utility of the Barrier API?
</blockquote></details>

I agree that that's a good idea - makes the command less special-cased. Done.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches, line 54 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoYjGsCF__eLGn87sZ:-MgMer2E8bBcfxl-O7Tu:bftimf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice. Consider extending this further in the following ways:
- move this to a new `barrier` file
- keep this as the first "subtest"
- add a second subtest that sequences a read, then sequences a barrier and ensures that the barrier latching blocks, then finishes the read and ensures that the barrier completes sequencing
- add a third subtest that does the same with a write
- add a fourth subtest that sequences a barrier and ensures that neither a read on overlapping key nor a write on a different overlapping key b [...]

2021-08-06 20:34 UTC, nvanbenschoten reviewed
Nice!

> Reviewed 46 of 46 files at r29.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgS9vcn2wL_FM0kHy2J:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/kv/db.go, line 754 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRS37Q-GF83hvh3bkg:-MgRS37Q-GF83hvh3bkh:b3fn2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/db.go#L754)):*
> ```Go
> // Barrier is a command that waits for existing writes on the specified key
> // range to finish.
> func (db *DB) Barrier(ctx context.Context, begin, end interface{}, ts hlc.Timestamp) (hlc.Timestamp, error) {
> ```

Do we want to give this a timestamp? I don't think it's needed or used and so it's likely just going to cause confusion.
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MgRUFry3sifAKzd8OME:b-201tcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Isn't another key distinction between `declareAllKeys` and this the fact that `declareAllKeys` will not follow the header's span? Is that preferable to what we have here? I've changed the SpanAccess to `ReadWrite` now, and updated comments.
</blockquote></details>

Good point about the header span. But also, if we are not using `declareAllKeys` then we need to grab the local version of this span as well. Unless we're sending two Barrier requests - one with the global span and one with the local span.

Also, we don't want `h.Timestamp`, right? We want to wait on all overlapping operations, not just those with smaller timestamps. So consider using `AddNonMVCC` to make that clear.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 124 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRYbLp3azB8L_EYvBc:-MgRYbLp3azB8L_EYvBd:bsszkcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L124)):*
> ```
> 
> # -------------------------------------------------------------
> # Barrier requests do not wait for older reads, and do not block future writes.
> ```

I don't understand the "Barrier requests do not wait for older reads" part of this test case. I think it relates to the `h.Timestamp` discussion elsewhere. We want to wait on all prior reads, right?
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 124 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRYwHdC3msXhMbF5te:-MgRYwHeCrlYxghPj1AH:bkcivfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L124)):*
> ```
> 
> # -------------------------------------------------------------
> # Barrier requests do not wait for older reads, and do not block future writes.
> ```

Don't we want to also show that a barrier request doesn't block future reads?
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches, line 54 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoYjGsCF__eLGn87sZ:-MgS9nG17qmUjwGk98-I:b-1lpm0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches#L54)):*
> write shouldn't be blocked by the barrier, right

Yep, and that a read shouldn't be blocked on the barrier. I think we're missing that second part.


<!-- Sent from Reviewable.io -->

2021-08-06 21:32 UTC, itsbilal reviewed
TFTRs!

Datadriven tests implemented, `SystemDeps` implemented. I'm going to address Nathan's last batch of comments on Monday as they're all fairly minor. One last thing that remains to resolve, functionally: I need to turn `Barrier` and `ScanInterleavedIntents` into operations that also act on the corresponding range local keys. Currently we send separate requests for the range local spans, but it fails to address with this error:

```
pq: internal error: running migration for 21.1-124: error when invoking Barrier command: mismatched range suggestion not different from original desc. desc: r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n5,s5):4, (n3,s3):5, next=6, gen=8]. suggested: r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n5,s5):4, (n3,s3):5, next=6, gen=8]. err: key range /Meta1/""-/System/NodeLiveness/
NULL outside of bounds of range /Min-/System/NodeLiveness; suggested ranges: [desc: r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n4,s4):2, (n2,s2):3, (n5,s5):4, (n3,s3):5, next=6, gen=8], lease: repl=(n1,s1):1 seq=2 start=1628285001.307158000,0 exp=1628285028.260060000,0 pro=1628285019.260060000,0, closed_timestamp_policy: LAG_BY_CLUSTER_SETTING desc: r2:/System/NodeLiveness{-Max} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n3,s3):4, (n4,s4):5, next=6, gen=8], lease: repl=(n1,s1):1 seq=2 start=1628285001.307334000,0 exp=1628285028.312727000,0 pro=1628285019.312727000,0, closed_timestamp_policy: LAG_BY_CLUSTER_SETTING]
```

I'm gonna guess that means we can't issue requests to range-local `RKey`s like that, and need to shove it into the same request. Thoughts welcome - I'm new to that side of the code. Either way, that should be a relatively minor change, though it'll change a bunch of the counts in the new datadriven test.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgSLV4p3lt1LrybY3pO:b-5f5ext)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/db.go, line 754 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRS37Q-GF83hvh3bkg:-MgSGXmU64sB7ImzotlP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/db.go#L754)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to give this a timestamp? I don't think it's needed or used and so it's likely just going to cause confusion.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 36 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoWgoo7RoYVL4gBsA6:-MgSG_UR5E5LzHpBmIQy:b-9p8t23) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/batcheval/cmd_barrier.go#L36)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good point about the header span. But also, if we are not using `declareAllKeys` then we need to grab the local version of this span as well. Unless we're sending two Barrier requests - one with the global span and one with the local span.

Also, we don't want `h.Timestamp`, right? We want to wait on all overlapping operations, not just those with smaller timestamps. So consider using `AddNonMVCC` to make that clear.
</blockquote></details>

We are doing two Barrier requests, one for the global and one for the local span. But I might need to change that; see top level comment.
___
*[pkg/migration/system_migration.go, line 38 at r28](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfsUHVCAdHmY_CNYlnD:-MgSJosaAChj4kEuMdVP:bt4ox15) ([raw file](https://github.com/cockroachdb/cockroach/blob/2faad08c5ee5ca1b1a9e4b3386b1722cc0138532/pkg/migration/system_migration.go#L38)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// DB returns access to the kv.
> 	DB() *kv.DB
> 	// DistSender returns access to the DistSender for communicating with the
> 	// kv store.
> 	DistSender() *kvcoord.DistSender
> 	// Stopper returns a reference to a Stopper for spawning new tasks.
> 	Stopper() *stop.Stopper
> ```
How upset would you be if I asked you to create a new struct `SystemDeps` that was parallel to `TenantDeps` and define it like:

```go
package migration

// SystemDeps are the dependencies of migrations which perform actions at the
// KV layer on behalf of the system tenant.
type SystemDeps struct {
     Cluster Cluster
     DB        *kv.DB
     DistSender *kvcoord.DistSender
     Stopper *stop.Stopper
}

// SystemMigrationFunc is used to perform kv-level migrations. It should only be
// run from the system tenant.
type SystemMigrationFunc func(context.Context, clusterversion.ClusterVersion, SystemDeps) error
```

I don't think we're getting a lot of value in growing the Cluster interface. Having a container for explicit dependencies feels cleaner. This will also give us a place to stick functionality like job checkpointing. 
</blockquote></details>

Done. Thanks for the suggestion!


<!-- Sent from Reviewable.io -->

2021-08-09 19:46 UTC, itsbilal reviewed
Addressed the error that I was seeing above. Turns out, `keys.AddrUpperBound` was unintentionally creating an `RSpan` that was outside the range's bounds, which was tripping up some internal assertions. Added a special case in that method where we don't `Next()` the upper bound of an RSpan if the range-local key used to create it was a range key prefix. Thanks @nvanbenschoten and @irfansharif  for the help there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MggRQgw2AaSVEl5VG4K:bbfb8vh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 124 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRYbLp3azB8L_EYvBc:-MggO5PTCfraUAaH5jfV:bfga5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't understand the "Barrier requests do not wait for older reads" part of this test case. I think it relates to the `h.Timestamp` discussion elsewhere. We want to wait on all prior reads, right?
</blockquote></details>

That was just me interpreting the `Manager.wait` method while assuming a timestamp. Changing the span to `NonMVCC` allows us to wait on all reads, so yes.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 124 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgRYwHdC3msXhMbF5te:-MggQPdH2ZN9eqOT4XH-:bx3p8v3) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cc99c6a3fb4878cb121750d8d165c53a58fe7b/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Don't we want to also show that a barrier request doesn't block future reads?
</blockquote></details>

Yep. Added.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches, line 54 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MfoYjGsCF__eLGn87sZ:-MggR-_TAY8-nf5p9g8U:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f410c6463ef2ea5992529aa343dbc0909e8b102f/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/no_latches#L54)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> write shouldn't be blocked by the barrier, right

Yep, and that a read shouldn't be blocked on the barrier. I think we're missing that second part.
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2021-08-09 20:13 UTC, ajwerner reviewed
Thanks for doing infra changes! Also, cool test.

> Reviewed 5 of 20 files at r30, 1 of 11 files at r31.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MggTmRS5m2QTeB3JtmA:bjcrs8w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/mock_transactional_sender.go.orig, line 1 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggUOS137cmJiXEeDG9:-MggUOS137cmJiXEeDGA:bqx9yns) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/kv/mock_transactional_sender.go.orig#L1)):*
> ```
> // Copyright 2019 The Cockroach Authors.
> ```

errant file addition?
___
*[pkg/migration/migrations/separated_intents.go, line 263 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggXEoW8cCQLqHj3icN:-MggXEoW8cCQLqHj3icO:bz80fa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L263)):*
> ```Go
> 
> 			if ranges.Len() > 0 {
> 				log.Infof(ctx, "currently migrating lock table on ranges %s", ranges.String())
> ```

At least as important as which ranges are how many. If you're making progress then it's probably good. Do we have that info?
___
*[pkg/migration/migrations/separated_intents.go, line 338 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggV46EDG4jzLpFkVt0:-MggV46EDG4jzLpFkVt1:bfjonn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L338)):*
> ```Go
> 		case workerPool.requests <- request:
> 		case <-ctx.Done():
> 			return errors.New("lock table migration canceled")
> ```

Almost definitely want to wrap this `errors.Wrap` with `ctx.Err()` here and below
___
*[pkg/migration/migrations/separated_intents.go, line 355 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggUgX7C23RvEEXUtGH:-MggUgX7C23RvEEXUtGI:bcuvo7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L355)):*
> ```Go
> 			return errors.New("lock table migration canceled")
> 		}
> 		numMigratedRanges++
> ```

my sense is that this is begging for a closure or something like that. At least a block. `request2` smells. 
___
*[pkg/migration/migrations/separated_intents.go, line 367 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggXq5e9sxYCZ2OpRMO:-MggXq5e9sxYCZ2OpRMP:bicalgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L367)):*
> ```Go
> 		return err
> 	}
> 	workerPool.startStatusLogger(ctx)
> ```

Don't we want this running while they're doing the work? If so, I think you're going to need a bit more in the way of shutdown synchronization. 
___
*[pkg/migration/migrations/separated_intents_test.go.orig, line 1 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggTzU0DkcLcQit7yut:-MggTzU0DkcLcQit7yuu:b-i5cfwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents_test.go.orig#L1)):*
> ```
> // Copyright 2021 The Cockroach Authors.
> ```

is this file intentional?


<!-- Sent from Reviewable.io -->

2021-08-09 22:24 UTC, nvanbenschoten reviewed
Agreed, very nice testing!

> Reviewed 13 of 20 files at r30, 8 of 11 files at r31, 6 of 6 files at r32.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mgh-SXzAzVhD9xXGVhQ:b-8cfihx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/keys/keys.go, line 561 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggxiQT0HtMc-YUNv9I:-MggxiQT0HtMc-YUNv9J:b7q25j5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/keys/keys.go#L561)):*
> ```Go
> //
> // and so any end key /local/k1/x corresponds to an address-resolved end key of
> // k1\x00.
> ```

Do you mind updating this comment to reflect the fact that k1 and /local/k1 (without a suffix) map to the same address-resolved key and end key?
___
*[pkg/keys/keys_test.go, line 131 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggxzVODRDiDnh9LNP8:-MggxzVODRDiDnh9LNP9:b-vs9me3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/keys/keys_test.go#L131)):*
> ```Go
> 		{roachpb.Key{}, roachpb.RKeyMin},
> 		{roachpb.Key("123"), roachpb.RKey("123")},
> 		{MakeRangeKeyPrefix(roachpb.RKey("foo")), roachpb.RKey("foo")},
> ```

Could we add the new test cases you added here to `TestKeyAddress` as well?
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 44 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggyLUa9BhBigmENzKB:-MggyLUa9BhBigmENzKC:b-icgpak) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/kv/kvserver/batcheval/cmd_barrier.go#L44)):*
> ```Go
> ) (result.Result, error) {
> 	resp := response.(*roachpb.BarrierResponse)
> 	resp.Timestamp = cArgs.EvalCtx.Clock().Now()
> ```

Did we confirm that `BarrierRequest`s go through Raft? You could add a new test case to `TestNoopRequestsNotProposed` to check.
___
*[pkg/migration/migrations/separated_intents_test.go, line 191 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgh-B-B5hw6WaPPXfct:-Mgh-B-B5hw6WaPPXfcu:b-hpdht5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/migration/migrations/separated_intents_test.go#L191)):*
> ```Go
> 						Intents:        intentsToScan[startIdx:endIdx],
> 					})
> 				}
> ```

Do we want to assert that no other request types are issued?
___
*[pkg/migration/migrations/testdata/separated_intents, line 45 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgh-fPw8A3NrMi5mn8a:-Mgh-fPw8A3NrMi5mn8b:b-hk2mpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/migration/migrations/testdata/separated_intents#L45)):*
> ```
> # Same case as above, but with use of resume spans. There should be 4
> # scanInterleavedIntents requests, 3 for the six range replicates keys, and 1
> # for range local keys.
> ```

Are there range local keys in this test case?


<!-- Sent from Reviewable.io -->

2021-08-10 17:37 UTC, itsbilal reviewed
TFTRs! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mgl7ylD0r4CW7GrrsBF:bodi8jh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/keys/keys.go, line 561 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggxiQT0HtMc-YUNv9I:-MgkZPL5-iwOqPDoyN7o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/keys/keys.go#L561)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you mind updating this comment to reflect the fact that k1 and /local/k1 (without a suffix) map to the same address-resolved key and end key?
</blockquote></details>

Done.
___
*[pkg/keys/keys_test.go, line 131 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggxzVODRDiDnh9LNP8:-Mgk_61J7K8z9-USkkgY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/keys/keys_test.go#L131)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we add the new test cases you added here to `TestKeyAddress` as well?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 44 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggyLUa9BhBigmENzKB:-MgkeTt80Kmxhepi4f7g:b-84otpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/kv/kvserver/batcheval/cmd_barrier.go#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did we confirm that `BarrierRequest`s go through Raft? You could add a new test case to `TestNoopRequestsNotProposed` to check.
</blockquote></details>

Done. Had to add a change for it - good catch.
___
*[pkg/migration/migrations/separated_intents.go, line 263 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggXEoW8cCQLqHj3icN:-MgklFrv5-PYF9QfAQIr:b6gcmg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L263)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

At least as important as which ranges are how many. If you're making progress then it's probably good. Do we have that info?
</blockquote></details>

You mean a total count of all ranges in the channels as well as being processed right now? The processed count will always be <=4 as that's the concurrency limit, and it should be pretty easy to observe that by looking at the list. To account for the queue I'd have to add an atomic, but it's doable.
___
*[pkg/migration/migrations/separated_intents.go, line 338 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggV46EDG4jzLpFkVt0:-MgkoEqF591lchHnm9yT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L338)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Almost definitely want to wrap this `errors.Wrap` with `ctx.Err()` here and below
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents.go, line 355 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggUgX7C23RvEEXUtGH:-MgkovHb36tanb0Mg_Gz:b-3uzt8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L355)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

my sense is that this is begging for a closure or something like that. At least a block. `request2` smells. 
</blockquote></details>

`request2` ended up being unnecessary. Added a block anyway.
___
*[pkg/migration/migrations/separated_intents.go, line 367 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggXq5e9sxYCZ2OpRMO:-MgktdDt8kv7IGbRvw75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L367)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Don't we want this running while they're doing the work? If so, I think you're going to need a bit more in the way of shutdown synchronization. 
</blockquote></details>

Done.
___
*[pkg/migration/migrations/separated_intents_test.go, line 191 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgh-B-B5hw6WaPPXfct:-MgkeaVX-rC0UqCm-vSU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/migration/migrations/separated_intents_test.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to assert that no other request types are issued?
</blockquote></details>

Done.
___
*[pkg/migration/migrations/testdata/separated_intents, line 45 at r32](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgh-fPw8A3NrMi5mn8a:-Mgk_RuWEFFLRSs2CFKx:bp8drgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a6daff54ec96848202c719bd4c553b28835e65b/pkg/migration/migrations/testdata/separated_intents#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are there range local keys in this test case?
</blockquote></details>

Nope, those are in the next test case. Clarifying.
___
*[pkg/kv/mock_transactional_sender.go.orig, line 1 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggUOS137cmJiXEeDG9:-Mgk_HBNAUvlYKmzly2u:b-a4wcvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/kv/mock_transactional_sender.go.orig#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

errant file addition?
</blockquote></details>

Oops. Done.
___
*[pkg/migration/migrations/separated_intents_test.go.orig, line 1 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggTzU0DkcLcQit7yut:-Mgktem37a7E6KgXncxh:bvu6wiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents_test.go.orig#L1)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

is this file intentional?
</blockquote></details>

Oops. Removed.


<!-- Sent from Reviewable.io -->

2021-08-11 19:14 UTC, sumeerbhola reviewed
> Reviewed 2 of 46 files at r35, 2 of 27 files at r36.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/intent_reader_writer.go, line 59 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgq_ln37rBtkN-7wtTW:-Mgq_ln37rBtkN-7wtTX:b-caeifb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb9d2830cc277d0891732b9b5aff50213c38eba/pkg/storage/intent_reader_writer.go#L59)):*
> ```Go
> 		// Be resilient to the version not yet being initialized.
> 		idw.clusterVersionIsRecentEnoughCached = !idw.settings.Version.ActiveVersionOrEmpty(ctx).Less(
> 			clusterversion.ByKey(clusterversion.SeparatedIntents))
> ```

if the version is not initialized for some reason, `clusterVersionIsRecentEnoughCached` will say false, which is not distinguishable from the case where the cluster is running 20.2. Isn't there a risk that we will write interleaved intents? And could this happen at a node, after the migration has been run?

Can anyone be running a cluster with 21.2 nodes and 20.2 nodes? I thought that a mixed version cluster is only permitted to run 2 consecutive major versions (is that true, and do we enforce it?). If yes, should we remove all the code that uses the cluster version in deciding whether to write separated intents?


<!-- Sent from Reviewable.io -->

2021-08-11 19:24 UTC, ajwerner reviewed
> Reviewed 1 of 18 files at r33.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/storage/intent_reader_writer.go, line 59 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgq_ln37rBtkN-7wtTW:-Mgqev_w9_7KA7P1t9zl:bwspis9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb9d2830cc277d0891732b9b5aff50213c38eba/pkg/storage/intent_reader_writer.go#L59)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

if the version is not initialized for some reason, `clusterVersionIsRecentEnoughCached` will say false, which is not distinguishable from the case where the cluster is running 20.2. Isn't there a risk that we will write interleaved intents? And could this happen at a node, after the migration has been run?

Can anyone be running a cluster with 21.2 nodes and 20.2 nodes? I thought that a mixed version cluster is only permitted to run 2 consecutive major versions (is that true, and do we enforce it?). If yes, should we remove all the code that uses the cluster version in deciding whether to write separated intents?
</blockquote></details>

Yes please to removing this cluster version key: https://github.com/cockroachdb/cockroach/issues/66544


<!-- Sent from Reviewable.io -->

2021-08-11 19:54 UTC, sumeerbhola requested changes
> Reviewed 1 of 18 files at r33.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/keys/keys.go, line 560 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgqg3pYEuKR5iaxBhkq:-Mgqg3pYEuKR5iaxBhkr:blvb7jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb9d2830cc277d0891732b9b5aff50213c38eba/pkg/keys/keys.go#L560)):*
> ```Go
> // Logically, the keys are arranged as follows:
> //
> // k1 /local/k1/KeyMin ... /local/k1/KeyMax k1\x00 /local/k1/x00/KeyMin ...
> ```

I don't understand this example. What is KeyMin here? Is it `roachpb.KeyMin` which is the empty string. I am assuming `/` represents the \x00\x01 separator added at the end by `EncodeBytesAscending` which is what we call in `MakeRangeKeyPrefix`.

I guess what I am struggling with is "range-local keys exist conceptually in the space between regular keys". And more specifically the range local keys are to the right of the regular key and that is because of the suffix in these range local keys, yes?

And if my original range is [k0, k1) and I am calling this with /local/k1/KeyMax, why would it not be always fine to return k1 (and not k1\x00)? I couldn't quite figure out based on the callers but I am guessing this is because the caller is later converting the returned RKey back to a range-local key and using it to do an engine scan. But then the upper bound returned here is not necessarily tight. Consider:
k1 /local/k1/KeyMin /local/k1/bar /local/k1/foo /local/k1/KeyMax
and we call this function with /local/k1/bar, and get back k1\x00. If we later convert this back to /local/k1\x00/ and do a SeekLT we will pickup /local/k1/foo which was outside the original upper bound. What am I missing?

It would be useful to specify in a code comment the reason for existence of this AddrUpperBound and if the existing use case is different from the new one, perhaps we should have a separate function rather than reuse the same.


<!-- Sent from Reviewable.io -->

2021-08-11 20:31 UTC, itsbilal reviewed
> Dismissed @sumeerbhola from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/keys/keys.go, line 560 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgqg3pYEuKR5iaxBhkq:-Mgqst5Z6r9RRDJR37N3:bi3yd04) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb9d2830cc277d0891732b9b5aff50213c38eba/pkg/keys/keys.go#L560)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand this example. What is KeyMin here? Is it `roachpb.KeyMin` which is the empty string. I am assuming `/` represents the \x00\x01 separator added at the end by `EncodeBytesAscending` which is what we call in `MakeRangeKeyPrefix`.

I guess what I am struggling with is "range-local keys exist conceptually in the space between regular keys". And more specifically the range local keys are to the right of the regular key and that is because of the suffix in these range local keys, yes?

And if my original range is [k0, k1) and I am calling this with /local/k1/KeyMax, why would it not be always fine to return k1 (and not k1\x00)? I couldn't quite figure out based on the callers but I am guessing this is because the caller is later converting the returned RKey back to a range-local key and using it to do an engine scan. But then the upper bound returned here is not necessarily tight. Consider:
k1 /local/k1/KeyMin /local/k1/bar /local/k1/foo /local/k1/KeyMax
and we call this function with /local/k1/bar, and get back k1\x00. If we later convert this back to /local/k1\x00/ and do a SeekLT we will pickup /local/k1/foo which was outside the original upper bound. What am I missing?

It would be useful to specify in a code comment the reason for existence of this AddrUpperBound and if the existing use case is different from the new one, perhaps we should have a separate function rather than reuse the same.
</blockquote></details>

The key point is that `AddrUpperBound` isn't being used to mutate the request's Header (which has raw Keys, not RKeys in it). So no, the caller isn't converting the RKey back to a range-local key; that transformation is inherently impossible to get right. The RKey is only being used to look up the range descriptor and to evict it from the cache if necessary.

The issue I was facing was that if you address a request to the range-local bounds of a range, this method used to mutate the upper bound's RKey just enough to trip up an assertion in the range descriptor cache which would think that the request was out of bounds of the range it was trying to send it to.
___
*[pkg/storage/intent_reader_writer.go, line 59 at r36](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgq_ln37rBtkN-7wtTW:-MgqsYA21vQUD5L0HhB4:b5467la) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eb9d2830cc277d0891732b9b5aff50213c38eba/pkg/storage/intent_reader_writer.go#L59)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes please to removing this cluster version key: https://github.com/cockroachdb/cockroach/issues/66544
</blockquote></details>

Done. Removed all the code to handle pre-SeparatedIntents versions. It's all in the third commit.


<!-- Sent from Reviewable.io -->

2021-08-11 22:20 UTC, nvanbenschoten reviewed
This is getting very close. I'm impressed by the stamina.

> Reviewed 2 of 18 files at r33, 43 of 46 files at r38, 37 of 37 files at r39.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgrIBKl6G7Ktrt8Bhzt:b-9ucmxd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/roachpb/api.go, line 276 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgrHCxD9h3v5-W4un0t:-MgrHCxD9h3v5-W4un0u:b6j3pzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/roachpb/api.go#L276)):*
> ```Go
> // combine() allows responses from individual ranges to be aggregated
> // into a single one.
> type combinable interface {
> ```

Do we need to make both of our new requests combinable? What would happen if a range split below a BarrierRequest? We'd want to learn about the maximum time of the barrier, right? And then what would happen if a range split below a ScanInterleavedIntentsRequest? We'd want to combine the intents, right?

Should we find a way to test these cases?


<!-- Sent from Reviewable.io -->

2021-08-12 02:29 UTC, sumeerbhola requested changes
looks good! just some minor comments,

> Reviewed 1 of 18 files at r33, 40 of 46 files at r38, 31 of 37 files at r39.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgsB5nv-rkUYT9qe3Ev:blj1g6g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 34 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgrwuda68-SjO5OHR2R:-Mgrwuda68-SjO5OHR2S:b-cch5pz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/batcheval/cmd_barrier.go#L34)):*
> ```Go
> 	// Barrier is special-cased in the concurrency manager to *not* actually
> 	// grab these latches. Instead, any conflicting latches with these are waited
> 	// on, but new latches aren't inserted.
> ```

Can you add to the comment here
// This will conflict with all writes and reads over the span, regardless of timestamp. Note that this guarantees that concurrent writes will be flushed out before this request is evaluated, but there is no guarantee regarding flushing out of concurrent reads since they could be getting evaluated on a follower. We don't currently need any guarantees regarding concurrent reads, so this is acceptable.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 167 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs-jGf0z9iBPjq6ltx:-Mgs-jGf0z9iBPjq6lty:b-djqvhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L167)):*
> ```
> 
> # -------------------------------------------------------------
> # Barrier requests do not block future writes or reads.
> ```

do not block any reads or writes, yes?
maybe add both past and future ones below.
___
*[pkg/kv/kvserver/spanlatch/manager_test.go, line 596 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs19OK829FlN9yPGNW:-Mgs19OK829FlN9yPGNX:b-ycl15q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/spanlatch/manager_test.go#L596)):*
> ```Go
> 	lg1 := m.AcquireOptimistic(spans("d", "f", write, zeroTS))
> 	require.True(t, m.CheckOptimisticNoConflicts(lg1, spans("d", "f", write, zeroTS)))
> 	lg1, err := m.WaitUntilAcquired(context.Background(), lg1)
> ```

can't these 3 calls be replaced by m.Acquire()?
___
*[pkg/migration/migrations/migrations.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLZSckCqJc6EGv6F9J:-Mgs2HkW4PBY5DhK6cZh:bpuntf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/migrations.go#L72)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

This will end up in the `migrations` system table, as that tracks completion.
</blockquote></details>

Will https://github.com/cockroachdb/cockroach/pull/66268 need to read from the system table in order to enable the fast path for ranged intent resolution?
___
*[pkg/migration/migrations/separated_intents.go, line 235 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MdOL77B2EwdCdfnbPT4:-Mgs2q49-2CPOlr68yOc:bfv0cik) ([raw file](https://github.com/cockroachdb/cockroach/blob/a154f3cddb1a26d2004b1d556bfc748dc922df04/pkg/migration/migrations/separated_intents.go#L235)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It's the same code as all the other migrations under this framework - each batch is a batch of range descriptors passed in by `IterateRangeDescrriptors`. We don't know the final batch count until the very end, it's why we substitute ?? for the denominator until the migration finishes. Should I add a comment about this?
</blockquote></details>

No need for a code comment.
___
*[pkg/migration/migrations/separated_intents.go, line 335 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs5VvrBraZIOnwAeAL:-Mgs5VvrBraZIOnwAeAM:b-6g2toc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/separated_intents.go#L335)):*
> ```Go
> 					fmt.Fprintf(&ranges, ", ")
> 				}
> 				fmt.Fprintf(&ranges, "%s", roachpb.RangeID(rangeID))
> ```

Is it easy to find historical range ids and figure out what key range they corresponded to? I am wondering if we see a problem and the range id no longer exists due to split/merge whether we will easily be able to figure out which key range to look at.
___
*[pkg/migration/migrations/separated_intents.go, line 341 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs6wpkBSJCe3cugr0m:-Mgs6wpkBSJCe3cugr0n:be8f7gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/separated_intents.go#L341)):*
> ```Go
> 				log.Infof(ctx, "currently migrating lock table on ranges %s", ranges.String())
> 			}
> ```

can we also log how many ranges have been successfully migrated?de
___
*[pkg/migration/migrations/testdata/separated_intents, line 1 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs9HOt3mihld7zJC3_:-Mgs9HOt3mihld7zJC3a:b-j6rd9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/testdata/separated_intents#L1)):*
> ```
> 
> ```

nice test!
___
*[pkg/migration/migrations/testdata/separated_intents, line 143 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs9AbLAtKDoTlc4SYr:-Mgs9AbLAtKDoTlc4SYs:bn502yv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/testdata/separated_intents#L143)):*
> ```
> ----
> 
> # Case where one request is fired per intent. There are 15 keys across 2 ranges,
> ```

one scanInterleavedIntents request ...


<!-- Sent from Reviewable.io -->

2021-08-12 16:00 UTC, itsbilal reviewed
TFTRs!

> Dismissed @sumeerbhola from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mgv4wnQBSpeB1OELLjU:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/cmd_barrier.go, line 34 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgrwuda68-SjO5OHR2R:-MguvcpX0L7J5LhVCMyv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/batcheval/cmd_barrier.go#L34)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add to the comment here
// This will conflict with all writes and reads over the span, regardless of timestamp. Note that this guarantees that concurrent writes will be flushed out before this request is evaluated, but there is no guarantee regarding flushing out of concurrent reads since they could be getting evaluated on a follower. We don't currently need any guarantees regarding concurrent reads, so this is acceptable.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier, line 167 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs-jGf0z9iBPjq6ltx:-Mguve437J6zW5iPNWHw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier#L167)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

do not block any reads or writes, yes?
maybe add both past and future ones below.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/spanlatch/manager_test.go, line 596 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs19OK829FlN9yPGNW:-Mgux7N360t-1cNg-h09:bhutldu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/spanlatch/manager_test.go#L596)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can't these 3 calls be replaced by m.Acquire()?
</blockquote></details>

Yes, but that skips the `CheckOptimisticNoConflicts` check. Just seems safer / follows the same convention as other tests which I copied this from.
___
*[pkg/migration/migrations/migrations.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLZSckCqJc6EGv6F9J:-MguxHozBit0rb9ONuEx:b-4y6qhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/migrations.go#L72)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Will https://github.com/cockroachdb/cockroach/pull/66268 need to read from the system table in order to enable the fast path for ranged intent resolution?
</blockquote></details>

I believe it can just look at the cluster version. The cluster version won't move to `PostSeparatedIntentMigration` until the migration is complete. At least that's how it appears in the tests. Maybe @ajwerner can add more clarity.
___
*[pkg/migration/migrations/separated_intents.go, line 335 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs5VvrBraZIOnwAeAL:-Mgv1-ElBS5hkvUli0mW:b-4pvdmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/separated_intents.go#L335)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is it easy to find historical range ids and figure out what key range they corresponded to? I am wondering if we see a problem and the range id no longer exists due to split/merge whether we will easily be able to figure out which key range to look at.
</blockquote></details>

Not sure about this. Maybe we could also log range boundaries around here.
___
*[pkg/migration/migrations/separated_intents.go, line 341 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs6wpkBSJCe3cugr0m:-Mgv159H-PYwki7e5XlI:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/separated_intents.go#L341)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can we also log how many ranges have been successfully migrated?de
</blockquote></details>

Added.
___
*[pkg/migration/migrations/testdata/separated_intents, line 1 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs9HOt3mihld7zJC3_:-MguzEOW2q-a2zR_yb_Y:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/testdata/separated_intents#L1)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nice test!
</blockquote></details>

thanks!
___
*[pkg/migration/migrations/testdata/separated_intents, line 143 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs9AbLAtKDoTlc4SYr:-Mguzd6e8ANN-NN_EW07:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/testdata/separated_intents#L143)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

one scanInterleavedIntents request ...
</blockquote></details>

Done.
___
*[pkg/roachpb/api.go, line 276 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgrHCxD9h3v5-W4un0t:-Mgv0r2o9_m9jhWYOBJf:b-3077fe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/roachpb/api.go#L276)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to make both of our new requests combinable? What would happen if a range split below a BarrierRequest? We'd want to learn about the maximum time of the barrier, right? And then what would happen if a range split below a ScanInterleavedIntentsRequest? We'd want to combine the intents, right?

Should we find a way to test these cases?
</blockquote></details>

Good point. I made both requests combinable. We probably want to make this testable, but I also don't wanna delay this PR more than necessary - can I punt split/combine testing to a follow-up PR?


<!-- Sent from Reviewable.io -->

2021-08-12 17:05 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 43 of 46 files at r41, 42 of 42 files at r42.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgvJsQW53UM0hzo0w6H:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/roachpb/api.go, line 276 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MgrHCxD9h3v5-W4un0t:-MgvJaEX6bTDVDxnL_B2:bvtw0ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/roachpb/api.go#L276)):*
> can I punt split/combine testing to a follow-up PR?

Yes, absolutely.


<!-- Sent from Reviewable.io -->

2021-08-12 17:58 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 46 files at r29, 8 of 46 files at r41.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-MgvVv7G2vXLL1IbCnkW:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajwerner, @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/spanlatch/manager_test.go, line 596 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs19OK829FlN9yPGNW:-MgvUMzk2SC4i9KDTN0C:b258orn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/spanlatch/manager_test.go#L596)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yes, but that skips the `CheckOptimisticNoConflicts` check. Just seems safer / follows the same convention as other tests which I copied this from.
</blockquote></details>

Those 3 calls are roughly equivalent to calling Acquire, and there shouldn't be any possibility of conflict since this is the first thing the test does. You don't have to change it -- this is a nit.
___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-MgvV01KCXAi7bigyog6:b-y6nzgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It'll be up to the caller of the checkpoint code to indicate % completion. The checkpoint state itself can be whatever, though I think completed spans is likely the most natural choice. I'll ready the plumbing for a subsequent PR to adopt. 
</blockquote></details>

Is there checkpointing now, or is that a TODO for later?


<!-- Sent from Reviewable.io -->

2021-08-12 18:32 UTC, itsbilal reviewed
Thanks so much for all the reviews! My last push addresses the case where we were skipping range-local keys of timeseries ranges. Added a test for it.

A couple outstanding TODOs for future PRs:
1) Checkpointing of migration state
2) Better end-to-end testing (similar to `TestSeparatedIntentsMigration`) but of migration of range-local keys
3) Better testing of range splits under Barrier/ScanInterleavedIntents requests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-:-Mgvc3IK5Sesz7e6oqza:bdqh92p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/spanlatch/manager_test.go, line 596 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs19OK829FlN9yPGNW:-MgvbiSnAh6v39kDXlyd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/kv/kvserver/spanlatch/manager_test.go#L596)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Those 3 calls are roughly equivalent to calling Acquire, and there shouldn't be any possibility of conflict since this is the first thing the test does. You don't have to change it -- this is a nit.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-12 19:30 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66445)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/migration/migrations/migrations.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLZSckCqJc6EGv6F9J:-Mgvp9z58QpmNoMAqu4I:bdyrzgs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/migrations.go#L72)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I believe it can just look at the cluster version. The cluster version won't move to `PostSeparatedIntentMigration` until the migration is complete. At least that's how it appears in the tests. Maybe @ajwerner can add more clarity.
</blockquote></details>

The version is stored in memory. It's just an atomic read to check for activation. The upgrade protocol makes RPCs to all of the nodes to make sure that they have both persisted the new version to disk and updated their in-memory state. All new nodes will also see the new version.
___
*[pkg/migration/migrations/separated_intents.go, line 113 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-McLdMSc0w7i4ddTi_iX:-MgvpYdz-_n20Nn3egoX:b4t4dmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb0d84dfad829bb806c0fedf08bb8cf00e33011c/pkg/migration/migrations/separated_intents.go#L113)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is there checkpointing now, or is that a TODO for later?
</blockquote></details>

Feel free to reach out for guidance on hooking this up. 
___
*[pkg/migration/migrations/separated_intents.go, line 263 at r31](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-MggXEoW8cCQLqHj3icN:-MgvpzG77ep4HsYtcJTZ:b-7ba2gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4537c715120414cfcd4c7e2b53192e260f9e43/pkg/migration/migrations/separated_intents.go#L263)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

You mean a total count of all ranges in the channels as well as being processed right now? The processed count will always be <=4 as that's the concurrency limit, and it should be pretty easy to observe that by looking at the list. To account for the queue I'd have to add an atomic, but it's doable.
</blockquote></details>

No, the total that have been processed ever by this job instance. 
___
*[pkg/migration/migrations/separated_intents.go, line 335 at r39](https://reviewable.io/reviews/cockroachdb/cockroach/66445#-Mgs5VvrBraZIOnwAeAL:-MgvpcSrE1sVbm42Jke1:bqkpueu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8263f6e4ec4534ebd0fa30338ac35efe52e6f99e/pkg/migration/migrations/separated_intents.go#L335)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Not sure about this. Maybe we could also log range boundaries around here.
</blockquote></details>

Every time we make any replication change, we write that change out to `system.eventlog` as part of the same transaction. In that way we have a history. We retain history for 30 days. 


<!-- Sent from Reviewable.io -->

2021-08-12 21:07 UTC, itsbilal commented
Merging this before any more conflicts. Thanks all!

bors r=nvanbenschoten

2021-08-13 01:53 UTC, itsbilal commented
🙏 

bors r=nvanbenschoten

2021-08-13 03:03 UTC, merged