WIP: sql: add tracking for index usage statistics
cockroachdb/cockroach pull request #66451
Opened 2021-06-14 19:58 UTC by Azhng

This commit introduces index usage statistics subsystem. It is
responsible for tracking the index usage by the queries. Currently,
this information is surfaced through crdb_internal.index_usage_statistics
virtual table.

Release note (sql change): introduce crdb_internal.index_usage_statistics
 virtual table to surface index usage statistics.

Addresses #64740

2021-06-14 19:58 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66451)
<!-- Reviewable:end -->

2021-06-16 00:21 UTC, Azhng commented
Recommended review order:

* `pkg/roachpb`: this is where the core protobuf format for index usage stats are defined.
* `pkg/sql/indexusagestats`: this is the subsystem interface. It depends on `pkg/roachpb`
* `pkg/sql/indexusagestats/indexstatslocal`: this is the node-local subsystem that is responsible for collecting index usage stats and surfacing them through reader interface. It depends on `pkg/sql/indexusagestats`
* `pkg/server` and `pkg/sql/indexusagestats/clusterindexusagestats`: together implements RPC fanout for serving cluster-wide index usage stats. Both of them depends on all previous packages.

2021-06-16 00:22 UTC, Azhng commented
Example output: 

```
root@127.0.0.1:26257/movr> select * from  crdb_internal.index_usage_statistics;
  table_id | index_id | full_scans | non_full_scans | lookup_joins | inverted_joins | zigzag_joins |           last_scan           |           last_join
-----------+----------+------------+----------------+--------------+----------------+--------------+-------------------------------+--------------------------------
        53 |        1 |          0 |              0 |            3 |              0 |            0 | NULL                          | 2021-06-16 00:22:05.719929+00
        54 |        1 |          0 |              0 |            1 |              0 |            0 | NULL                          | 2021-06-16 00:22:05.218739+00
        54 |        2 |          0 |              1 |            0 |              0 |            0 | 2021-06-16 00:22:04.640266+00 | NULL
        55 |        1 |          0 |              0 |            1 |              0 |            0 | NULL                          | 2021-06-16 00:22:05.488654+00
        55 |        2 |          0 |              1 |            0 |              0 |            0 | 2021-06-16 00:22:04.914903+00 | NULL
        55 |        3 |          0 |              1 |            0 |              0 |            0 | 2021-06-16 00:22:05.218722+00 | NULL
        56 |        1 |          0 |              1 |            0 |              0 |            0 | 2021-06-16 00:22:05.488652+00 | NULL
        57 |        1 |          0 |              0 |            0 |              0 |            0 | NULL                          | NULL
        58 |        1 |          0 |              1 |            0 |              0 |            0 | 2021-06-16 00:22:05.719928+00 | NULL
(9 rows)

Time: 7ms total (execution 7ms / network 0ms)
```

2021-06-16 16:26 UTC, mgartner requested changes
I did an initial, partial pass and left comments.

I think you'd simplify the review process for yourself and for your reviewers by breaking this up into multiple commits. Your "recommended review order" already suggests there's 4-5 logical pieces that can broken into individual commits, as long as they are ordered correctly to pass CI builds. And there's no reason all these commits need to be in the same PR, either.

> Reviewed 27 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-McKc6Rl-y6x8EZXZZE_:b-7n017y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/cli/zip_cluster_wide.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKUHXPDY8NQAMpXvIm:-McKUHXPDY8NQAMpXvIn:b3dc7jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/cli/zip_cluster_wide.go#L97)):*
> ```Go
> 	"crdb_internal.zones",
> 	"crdb_internal.invalid_objects",
> ```

nit: remove empty line
___
*[pkg/roachpb/index_usage_stats.proto, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKV522-SnqvTTbTTEY:-McKV5236ide0No-bMlJ:bsd74v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L29)):*
> ```protobuf
> 
>   // NonFullScanCount is the number of times non-full scan is being performed on
>   // this index.
> ```

nit: an explanation of what a non-full scan is might be nice
___
*[pkg/roachpb/index_usage_stats.proto, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVUzY8ICvGVcKxiTF:-McKVUzY8ICvGVcKxiTG:b-fhujlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L47)):*
> ```protobuf
>   optional google.protobuf.Timestamp last_scan = 6 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> 
>   // TotalScanRows is the number rows that this index has been scanned through.
> ```

Can you make this more clear? Does this both full-scans and non-full scans? Does it include joins?

Also I think it'd make more sense if it read something like "TotalScanRows is the number of rows in this index that have been scanned. It includes...".
___
*[pkg/roachpb/index_usage_stats.proto, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVL5l2ByOXi9YEK3C:-McKVL5l2ByOXi9YEK3D:bn71svu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L51)):*
> ```protobuf
>   optional uint64 total_scan_rows = 7 [(gogoproto.nullable) = false];
> 
>   // TotalScanRows is the number rows that has been updated in this index.
> ```

This comment doesn't match the field.
___
*[pkg/roachpb/index_usage_stats.proto, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVysz6-WH3KmxOQhS:-McKVysz6-WH3KmxOQhT:b4sppu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L55)):*
> ```protobuf
>   optional uint64 update_counts = 8 [(gogoproto.nullable) = false];
> 
>   // LastScan is the timestamp that this index is last being updated.
> ```

nit: the comment doesn't match the field
___
*[pkg/roachpb/index_usage_stats.proto, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKW3qf47yqwXvdvj5I:-McKW3qf47yqwXvdvj5J:b7hh9yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L59)):*
> ```protobuf
>   optional uint64 total_updated_rows = 9 [(gogoproto.nullable) = false];
> 
>   // LastUpdate is the timestamp that this index is being updated.
> ```

nit: is last being updated => was last updated
___
*[pkg/roachpb/index_usage_stats.proto, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKWHJSAhGRK_BdHD5b:-McKWHJSAhGRK_BdHD5c:b50etr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L63)):*
> ```protobuf
>   optional google.protobuf.Timestamp last_update = 10 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> 
>   // LastJoin is the timestamp that this index is last used for a join.
> ```

You should note whether or not this includes zig-zag joins. I'm not sure what the expected behavior should be because a zigzag join is not produce from JOINs in queries. It's a mechanism for using two indexes to efficiently apply a conjunctive filter to an underlying table:

```
defaultdb> CREATE TABLE t (a INT, b INT, INDEX (a), INDEX (b));
CREATE TABLE

defaultdb> EXPLAIN SELECT * FROM t WHERE a = 1 AND b = 1;
               info
----------------------------------
  distribution: full
  vectorized: true

  • zigzag join
    pred: (a = 1) AND (b = 1)
    left table: t@t_a_idx
    left columns: (a)
    left fixed values: 1 column
    right table: t@t_b_idx
    right columns: (b)
    right fixed values: 1 column
(11 rows)
```
___
*[pkg/server/index_usage_stats.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKYNJx2PlXLkvsYrRk:-McKYNJx2PlXLkvsYrRl:b-s5s7r1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L25)):*
> ```Go
> )
> 
> func (s *statusServer) IndexUsageStatistics(
> ```

Add documentation for this function. It would be good to include how it behaves when `req.NodeID` is set vs unset and when `req.NodeID` is a local vs remote node.
___
*[pkg/server/index_usage_stats.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKXhtX01IZxu2OrFPT:-McKXhtX01IZxu2OrFPU:bgraxum) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L61)):*
> ```Go
> 
> 	// Creating a sink to aggregate all the information.
> 	aggStats := s.sqlServer.pgServer.SQLServer.GetClusterIndexStatisticsProvider()
> ```

I'm not familiar with these structures, so I'm curious why you use `s.admin.server.sqlServer.pgServer.SQLServer` above, but `s.sqlServer.pgServer.SQLServer` here.
___
*[pkg/server/index_usage_stats.go, line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKY-hTAM2ksPYMTkJx:-McKY-hTAM2ksPYMTkJy:b6rn880) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L88)):*
> ```Go
> 	// It's unfortunate that we cannot use paginatedIterateNodes here because we
> 	// need to aggregate all stats before returning. Returning partial result
> 	// yields incorrect result.
> ```

nit: Returning **a** partial result yields **an** incorrect result.
___
*[pkg/server/serverpb/status.proto, line 1089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKZEktE95fbSEjCpcK:-McKZEktE95fbSEjCpcL:br27loq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/serverpb/status.proto#L1089)):*
> ```protobuf
>   string node_id = 1 [(gogoproto.customname) = "NodeID"];
>   bool ordered_table_id = 2 [(gogoproto.customname) = "OrderedTableID"];
>   bool ordered_index_id = 3 [(gogoproto.customname) = "OrderedIndexID"];
> ```

Can you document the meaning of these fields? It's not obvious to me what `ordered_table_id` and `ordered_index_id` are for. And max_limit below?
___
*[pkg/sql/crdb_internal.go, line 4653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKaA6x0kXws8hmZr3Y:-McKaA6x0kXws8hmZr3Z:bb0jr51) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/crdb_internal.go#L4653)):*
> ```Go
> var crdbInternalIndexUsageStatistics = virtualSchemaTable{
> 	comment: `cluster-wide index usage statistics (in-memory, not durable).` +
> 		`This table is wi [...]

2021-06-16 18:37 UTC, Azhng reviewed
Split into 3 commits. I'm not sure if I should split this into multiple PRs, because without the last commit, the first two commits essentially is introducing a lot of dead code that's not being executed at all.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-McKrDaV0_OgbErzAxeb:b-elnuxj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/roachpb/index_usage_stats.proto, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVUzY8ICvGVcKxiTF:-McKskFu4FvP87RfeUa0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L47)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you make this more clear? Does this both full-scans and non-full scans? Does it include joins?

Also I think it'd make more sense if it read something like "TotalScanRows is the number of rows in this index that have been scanned. It includes...".
</blockquote></details>

Done.
___
*[pkg/roachpb/index_usage_stats.proto, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVL5l2ByOXi9YEK3C:-McKslZ-ERuxQPeHJqI-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L51)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This comment doesn't match the field.
</blockquote></details>

Done.
___
*[pkg/roachpb/index_usage_stats.proto, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKWHJSAhGRK_BdHD5b:-McKtjf7CVYBj-FbYyI2:b-19qyaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L63)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You should note whether or not this includes zig-zag joins. I'm not sure what the expected behavior should be because a zigzag join is not produce from JOINs in queries. It's a mechanism for using two indexes to efficiently apply a conjunctive filter to an underlying table:

```
defaultdb> CREATE TABLE t (a INT, b INT, INDEX (a), INDEX (b));
CREATE TABLE

defaultdb> EXPLAIN SELECT * FROM t WHERE a = 1 AND b = 1;
               info
----------------------------------
  distribution: full
  vectorized: true

  • zigzag join
    pred: (a = 1) AND (b = 1)
    left table: t@t_a_idx
    left columns: (a)
    left fixed values: 1 column
    right table: t@t_b_idx
    right columns: (b)
    right fixed values: 1 column
(11 rows)
```
</blockquote></details>

This is a good question. Seems like `zigzag join` is essentially an optimized version of a filter when scanning through two indexes instead of actually joining them together. 
@kevin-v-ngo, do you think it's make sense to surface zigzag join here as part of the stats for join operators?  Or alternatively we should just count it as non full scans?
___
*[pkg/server/index_usage_stats.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKYNJx2PlXLkvsYrRk:-McL-5Ox7KhRweAnYCdu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L25)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Add documentation for this function. It would be good to include how it behaves when `req.NodeID` is set vs unset and when `req.NodeID` is a local vs remote node.
</blockquote></details>

Done.
___
*[pkg/server/index_usage_stats.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKXhtX01IZxu2OrFPT:-McL-6Iy-uwC1D43zzZ8:b8bnyoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L61)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not familiar with these structures, so I'm curious why you use `s.admin.server.sqlServer.pgServer.SQLServer` above, but `s.sqlServer.pgServer.SQLServer` here.
</blockquote></details>

Ah good catch. Both of them should be `s.sqlServer.pgServer.SQLServer`. 

This was  because initially, we only had one `statusServer` that's handling all the RPC requests. Later when we have multi-tenant SQL pod, the tenant's statusServer does not embed `adminServer`. Therefore, in order to serve RPC requests for status APIs,  the `baseStatusServer` that is embedded in both regular statusServer and tenantStatusServer was updated to have a reference to the `SQLServer`. 
___
*[pkg/server/serverpb/status.proto, line 1089 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKZEktE95fbSEjCpcK:-McL2ydNAdEOwxXwXGT6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/serverpb/status.proto#L1089)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can you document the meaning of these fields? It's not obvious to me what `ordered_table_id` and `ordered_index_id` are for. And max_limit below?
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 4653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKaA6x0kXws8hmZr3Y:-McL39sqEPqnd9fOMnhY:bhjihhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/crdb_internal.go#L4653)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Wiping the table is expensive? Why?
</blockquote></details>

What I meant was this is an expensive operation since it triggers a cluster-wide RPC fanout. And this table is wiped periodically. I see how the wording can be confusing, updated.
___
*[pkg/sql/opt_exec_factory.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKalsE9Nc-xzurtgq0:-McL4rJr4h23l6yHFYxE:brt2u7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/opt_exec_factory.go#L104)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm thinking you might want to include a ctx in the `execFactory` struct that is set in `newExecFactory`, rather than using a new context. It looks like the all the call sites of `newExecFactory` have a context that can be used.
</blockquote></details>

Seems like `planner` has `extendedEvalCtx` which has a `.Ctx()` method to return a context.Context here. Can that context be used here? 
Also, I noticed that in this file, there are a lot of other places e.g. `.initTable()` are called with a new context. Is there a reason there? Or it's just we haven't gotten around to fix those `context.TODO()` ? 
___
*[pkg/sql/planner.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKbT9uDFzLAo79_6yo:-McKuvHY4Cu1JaIv-vKB:be0mawb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/planner.go#L428)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

When would it be `nil`? What does a "dummy" index usage stats collector do?
</blockquote></details>

Currently it's only `nil` during the tests. This is because sometimes we create planner by passing an `ExecutorConfig` without creating a full `sql.Server`. 
Dummy index usage stats collector doesn't do anything in this case, since it does not start a stats ingestion loop. It will just discard the stats as it comes in. 

Updated the comments to specify it. 
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKc099DBed7hovVrsW:-McKxqLRCHZrU7v7uEgD:b4yl7u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e9 [...]

2021-06-16 18:56 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/server/index_usage_stats.go, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKXhtX01IZxu2OrFPT:-McLAKcvD_DWddigiOEv:b-q7f2ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/server/index_usage_stats.go#L61)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ah good catch. Both of them should be `s.sqlServer.pgServer.SQLServer`. 

This was  because initially, we only had one `statusServer` that's handling all the RPC requests. Later when we have multi-tenant SQL pod, the tenant's statusServer does not embed `adminServer`. Therefore, in order to serve RPC requests for status APIs,  the `baseStatusServer` that is embedded in both regular statusServer and tenantStatusServer was updated to have a reference to the `SQLServer`. 
</blockquote></details>

Just want to follow up on this. Confirmed with server team. The plan for us is to eventually remove the `adminServer` and `statusServer`. However, there's couple blockers on this so it's not happening soon. 


<!-- Sent from Reviewable.io -->

2021-06-16 22:42 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKc099DBed7hovVrsW:-McLzFgI76oeWernQQ0-:b-wgh9sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/indexusagestats/index_usage_stats.go#L25)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

the `IndexUsageType` is only an enum type here, is there a reason we need a full 64 bit interger? 
</blockquote></details>

Actually just realized I misunderstood. For some reason when i saw `int8` my brain thought it meant 8 bytes :facepalm: . 

Updated. 


<!-- Sent from Reviewable.io -->

2021-06-16 23:32 UTC, mgartner requested changes
> Split into 3 commits. I'm not sure if I should split this into multiple PRs, because without the last commit, the first two commits essentially is introducing a lot of dead code that's not being executed at all.

I don't have any issues with dead code being merged as long as it is "reanimated to undead" imminently. I've used the technique frequently when building larger features.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-McM8G-a8dpsXHNG2EET:b-iwcw0x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt_exec_factory.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKalsE9Nc-xzurtgq0:-McM993o5U4k85LRdHlq:bbua0dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/opt_exec_factory.go#L104)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Seems like `planner` has `extendedEvalCtx` which has a `.Ctx()` method to return a context.Context here. Can that context be used here? 
Also, I noticed that in this file, there are a lot of other places e.g. `.initTable()` are called with a new context. Is there a reason there? Or it's just we haven't gotten around to fix those `context.TODO()` ? 
</blockquote></details>

Great question. Maybe @raduberinde can chime in on why we use `context.TODO()` elsewhere in this file and if it's safe in this case.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKc099DBed7hovVrsW:-McM9Rkc-Jn9iqieyWuP:b-d7wgpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/indexusagestats/index_usage_stats.go#L25)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Actually just realized I misunderstood. For some reason when i saw `int8` my brain thought it meant 8 bytes :facepalm: . 

Updated. 
</blockquote></details>

Haha, it is confusing that Go's `int8` is 8 bits and CRDB's `INT8` is 8 bytes.


<!-- Sent from Reviewable.io -->

2021-06-17 10:04 UTC, RaduBerinde commented
___
*[pkg/sql/opt_exec_factory.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKalsE9Nc-xzurtgq0:-McOP5T8BmAC-f1PFiGe:bfmkqtv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/opt_exec_factory.go#L104)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great question. Maybe @raduberinde can chime in on why we use `context.TODO()` elsewhere in this file and if it's safe in this case.
</blockquote></details>

There are other places that use `ef.planner.extendedEvalCtx.Context`, I think that would be fine. We should probably use that everywhere. `TODO()` means we haven't gotten around to it.


<!-- Sent from Reviewable.io -->

2021-06-17 17:03 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/sql/opt_exec_factory.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKalsE9Nc-xzurtgq0:-McPvKZk7H_hJvlLi7GF:b-7btgr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/sql/opt_exec_factory.go#L104)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There are other places that use `ef.planner.extendedEvalCtx.Context`, I think that would be fine. We should probably use that everywhere. `TODO()` means we haven't gotten around to it.
</blockquote></details>

Updated all `context.TODO()` with the context embedded in the `extendedEvalCtx` in a separate commit. 


<!-- Sent from Reviewable.io -->

2021-06-18 02:33 UTC, jordanlewis commented
> This is a good question. Seems like zigzag join is essentially an optimized version of a filter when scanning through two indexes instead of actually joining them together.

I think that including this extra information in the table might be overwhelming. From a user's perspective, I think the fact that these columns are called `_join` will also be confusing, since they're not really related to "joins" in SQL, right? Let's hash the remaining discussions here out in the original design doc rather than the PR.

I think that @mgartner's suggestion to split into multiple PRs is good. That way, you can start to get some code merged as it's approved, without having to get final consensus on the contents of the virtual tables.

2021-06-18 21:52 UTC, Azhng reviewed
Split up into 3 PRs:

* Current PR: introduce node-local subsystem and integrated into execFactory
* Second [PR](https://github.com/cockroachdb/cockroach/pull/66639): introduced a cluster-variant of the index usage stats provider
* Third [PR](https://github.com/cockroachdb/cockroach/pull/66640): introduced the crdb_internal view.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-McW5nny-px3LXsezz5i:bpgerdq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)



<!-- Sent from Reviewable.io -->

2021-06-30 18:40 UTC, Azhng commented
@mgartner  Updated all three PRs to address the feedback from the index usage stats feature brief.

2021-07-06 21:03 UTC, mgartner requested changes
Thanks for breaking things up. This is a great start!

I left a few comments. My main feedback would be to consider the API you are exposing with the new interface, and make it as user-friendly as possible by providing the absolute minimum of features necessary to end users and clearly documenting each function exposed to users.

> Reviewed 3 of 46 files at r2, 16 of 16 files at r3, 7 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-Mdx_uqM5UMUNoLsz954:b-zcgp2p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, and @mgartner)

___
*[pkg/roachpb/index_usage_stats.go, line 20 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxO8pC6rxfC4MVPGPB:-MdxO8pDCpEBSiAz6HHJ:b-xxn9da) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac8b98384006598d68b983752aaf5e2661722e0/pkg/roachpb/index_usage_stats.go#L20)):*
> ```Go
> type IndexID uint32
> 
> // Add add the fields from other IndexUsageStatistics.
> ```

nit: add => adds
___
*[pkg/roachpb/index_usage_stats.proto, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-McKVL5l2ByOXi9YEK3C:-MdxPGbPA8G-IWFmz0Hh:bbeqcx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7e94bda04fcfd996b191e6b236dd2102589e57a/pkg/roachpb/index_usage_stats.proto#L51)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: "is being written to" => "has been written to".
___
*[pkg/roachpb/index_usage_stats.proto, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxPqHw7AaI-EN3qIu4:-MdxPqHw7AaI-EN3qIu5:bumw3iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac8b98384006598d68b983752aaf5e2661722e0/pkg/roachpb/index_usage_stats.proto#L22)):*
> ```protobuf
> // (*IndexUsageStatistics).Add in roachpb/index_usage_stats.go.
> message IndexUsageStatistics {
>   // TotalReadCount is the number of times this index is being read from.
> ```

nit: "is being read from" => "has been read from"
___
*[pkg/roachpb/index_usage_stats.proto, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxPl6c8gQrF7kexvcG:-MdxPl6c8gQrF7kexvcH:b-6qxv13) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac8b98384006598d68b983752aaf5e2661722e0/pkg/roachpb/index_usage_stats.proto#L25)):*
> ```protobuf
>   optional uint64 total_read_count = 1 [(gogoproto.nullable) = false];
> 
>   // LastRead is the timestamp that this index is last being read from.
> ```

nit: "is last being read from" => "was last read from"
___
*[pkg/roachpb/index_usage_stats.proto, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxPO0y5Q09pmKPKmrd:-MdxPO0y5Q09pmKPKmre:bashv1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac8b98384006598d68b983752aaf5e2661722e0/pkg/roachpb/index_usage_stats.proto#L36)):*
> ```protobuf
>   optional uint64 total_write_count = 4 [(gogoproto.nullable) = false];
> 
>   // LastWrite is the timestamp that this index is last being written to.
> ```

nit: "is last being written to" => "was last written to"
___
*[pkg/roachpb/index_usage_stats.proto, line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxPTr05_CxzubYK5GW:-MdxPTr05_CxzubYK5GX:bbktodq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac8b98384006598d68b983752aaf5e2661722e0/pkg/roachpb/index_usage_stats.proto#L40)):*
> ```protobuf
>   optional google.protobuf.Timestamp last_write = 5 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
> 
>   // TotalRowsWrite is the number rows that has written to this index.
> ```

nit: "that has written" => "that have been written"

Maybe it should be renamed to `total_rows_written`?
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxUiBx-2o6DlA3paak:-MdxUiBx-2o6DlA3paal:b-b5i57d) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L14)):*
> ```Go
> // statistics.
> 
> package indexusagestats
> ```

nit: you could consider a more concise package name, like `idxusage`.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxUE4TCQNTbCPxcQ08:-MdxUE4TCQNTbCPxcQ09:b-mm3jfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L37)):*
> ```Go
> // MetaData is the payload struct that records all the metadata we want to
> // record for a single index usage.
> type MetaData struct {
> ```

nit: metadata is one word, so this can be `Metadata`.

You might consider renaming this. If I understand correctly, this struct tracks a single use of an index, not necessarily any metadata about the use. So you could rename this to something like `IndexUse` or `IndexUsage`.

I think a cleaner API would be to have 2 Record functions for the interface, `RecordWrite` and `RecordRead`. If you need a single struct to place the usages on a single channel, you can define that struct and the ops privately in the implementation of the interface, rather than exposing to the user of the API.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxZ2L_EH_O5qknw89e:-MdxZ2LaD9dl8k0M5sKF:b-n8nclt) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L57)):*
> ```Go
> 	// IngestStats is the method to call to insert a batch of
> 	// roachpb.CollectedIndexUsageStatistics into the Sink.
> 	IngestStats(stats []roachpb.CollectedIndexUsageStatistics)
> ```

It's not clear to me what this is used for. Can you explain more?
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-Mdx_ThS30zeGeVBDQXP:-Mdx_ThS30zeGeVBDQXQ:b-o8ydmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L80)):*
> ```Go
> 	// based on the options specified in IteratorOptions. If an error is
> 	// encountered when calling StatsVisitor, the iteration is aborted.
> 	IterateIndexUsageStats(options IteratorOptions, visitor StatsVisitor) error
> ```

Will this be used outside of tests?
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-Mdx_Y-t1elyU7b2HVg_:-Mdx_Y-t1elyU7b2HVga:b-4kya42) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L82)):*
> ```Go
> 	IterateIndexUsageStats(options IteratorOptions, visitor StatsVisitor) error
> 
> 	// GetLastReset returns the time where the subsystem is last reset.
> ```

nit: "where" => "when", "is" => "was"

Will GetLastReset be used outside of tests? You should include an explanation of what "resetting" means in the context of this struct, and when/how it should be used. 
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxSdlKDJyU8WQc-9XE:-MdxSdlKDJyU8WQc-9XF:bqwplki) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L99)):*
> ```Go
> // Provider provides interfaces to control the overall lifetime of the entire
> // subsystem.
> type Provider interface {
> ```

nit: can you expand on the comment, e.g. what is the purpose of the Provider how is it used (or how should it be used?)

If this is the main interface it might make sense to order the definitions of these interfaces from highest-level to lowest-level, e.g., define Provider, then Storage, then Reader, Writer, Sink.

Also, do y [...]

2021-07-08 03:34 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxUE4TCQNTbCPxcQ08:-Me2-7uJ6-E6OAUuC1dV:bjfvv1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L37)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: metadata is one word, so this can be `Metadata`.

You might consider renaming this. If I understand correctly, this struct tracks a single use of an index, not necessarily any metadata about the use. So you could rename this to something like `IndexUse` or `IndexUsage`.

I think a cleaner API would be to have 2 Record functions for the interface, `RecordWrite` and `RecordRead`. If you need a single struct to place the usages on a single channel, you can define that struct and the ops privately in the implementation of the interface, rather than exposing to the user of the API.
</blockquote></details>

unexported `Metadata` and updated the interface. `RecordWrite` is left as TODO for later once we have the plumbing in the execution engine.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 57 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxZ2L_EH_O5qknw89e:-Me2-QkuEa50twRRfmP3:boa5h60) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L57)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's not clear to me what this is used for. Can you explain more?
</blockquote></details>

This is used for the cluster-wide index usage stats. I moved this to the followup PR.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 80 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-Mdx_ThS30zeGeVBDQXP:-Me2-m9K6y3p0Z7uvbMA:b-nmrp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L80)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Will this be used outside of tests?
</blockquote></details>

Yes, this is used in the next follow up PR for the cluster index usage stats. 
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-Mdx_Y-t1elyU7b2HVg_:-Me2-rEQ-wMePh59HYdS:bp3p3ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L82)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "where" => "when", "is" => "was"

Will GetLastReset be used outside of tests? You should include an explanation of what "resetting" means in the context of this struct, and when/how it should be used. 
</blockquote></details>

Removed `GetLastReset` interface for now as it's not used in the later PRs.
___
*[pkg/sql/indexusagestats/index_usage_stats.go, line 99 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxSdlKDJyU8WQc-9XE:-Me2-vKn0Iwr5FHxGcV8:b-pbzkdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/index_usage_stats.go#L99)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: can you expand on the comment, e.g. what is the purpose of the Provider how is it used (or how should it be used?)

If this is the main interface it might make sense to order the definitions of these interfaces from highest-level to lowest-level, e.g., define Provider, then Storage, then Reader, Writer, Sink.

Also, do you think there is value from splitting up all these interfaces, vs. just having one? A single interface would be easier to understand, so unless there is a specific reason for the split, I'd recommend combining them all together.
</blockquote></details>

Reduced the interface declaration to only `Reader` and `Writer`. Exported the `indexUsageStats` as `LocalIndexUsageStats` and directly exposes methods on the struct. 
___
*[pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxVHdu-gBdjF14jNSv:-Me1ZBdcDQWdIA8oROFO:b-co0mjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Does this need to be in a package separate from `indexusagestats`?
</blockquote></details>

My original intention was so that the local variant of the index usage stats and cluster variant of the index usage stats will be living in separate packages. But I think moving them into a single package is a better idea. 
___
*[pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxYIDLDaVDkOxX6MCY:-Me2-5UG9ez_ubiJBQGG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go#L28)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Some more explanation would be helpful here. You should
</blockquote></details>

Done.
___
*[pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go, line 83 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MdxbvLt030IvLDO9Gq3:-Me0nqM39T3BUNYreUzO:b-po70gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider.go#L83)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Returning an interface type seems like an anti-pattern to me. What advantage does this provide compared to returning an exported `IndexUsageStats` struct?
</blockquote></details>

Exported struct directly. 
___
*[pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider_test.go, line 11 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-Mdx_kQx6i3yNLCZss0h:-Me0njSJBe4gv4OpVlfN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/242fa118e64c2b142058f7094ae3ed090089e96e/pkg/sql/indexusagestats/indexstatslocal/idx_usage_provider_test.go#L11)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you run into an import cycle that required a separate test package?
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-07-12 21:53 UTC, mgartner requested changes
Getting there! I left a few more comments.

> Reviewed 8 of 19 files at r5, 16 of 20 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-MeRhNmn6TmF2IGlHPXi:b-vlnxm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @kevin-v-ngo, and @mgartner)

___
*[pkg/sql/idxusage/index_usage_stats.go, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRdKTo5x3gT4n-FNrX:-MeRdKTo5x3gT4n-FNrY:bpxylic) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/index_usage_stats.go#L37)):*
> ```Go
> 	SortedTableID bool
> 	SortedIndexID bool
> 	Max           *uint64
> ```

Why use a `*uint64` and not `uint64` here?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 66 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRV0-I8Qmrg5LGe7f2:-MeRV0-I8Qmrg5LGe7f3:b-eeoj9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L66)):*
> ```Go
> 		syncutil.RWMutex
> 
> 		usageStats map[roachpb.TableID]*tableIndexStats
> ```

nit: An short explanation of this field would be helpful
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 79 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRV78YBBhKPYX6nVDO:-MeRV78YBBhKPYX6nVDP:bk8lubw) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L79)):*
> ```Go
> 
> 	tableID roachpb.TableID
> 	stats   map[roachpb.IndexID]*indexStats
> ```

ditto: add a short explanation
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 84 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRgiCo3iz4gNK5Nzfa:-MeRgiCo3iz4gNK5Nzfb:bgwjhpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L84)):*
> ```Go
> // indexStats track index usage statistics per index.
> type indexStats struct {
> 	syncutil.RWMutex
> ```

It's difficult to verify that 3 different levels of mutexes are being used properly. I don't have much intuition about whether or not this granularity is necessary for performance reasons. Would a single mutex on `LocalIndexUsageStats` that gets acquired for the duration of all reads and writes be unacceptable?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRWjG-3IZr5NsVeLtk:-MeRWjG-3IZr5NsVeLtl:bf5grz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L139)):*
> ```Go
> 	case is.statsChan <- payload:
> 	default:
> 		if log.V(2 /* level */) {
> ```

I'm conflicted about where the log should be emitted for level `WARNING=2` or `INFO=1`. Based on the description in log.proto it seems like `1` because there's no action for a user to take if this happens:

```
  // INFO is used for informational messages that do not
  // require action.
  INFO = 1;
  // WARNING is used for situations which may require special handling,
  // where normal operation is expected to resume automatically.
  WARNING = 2;
```
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 146 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRf-Yx5629cstDIz1_:-MeRf-Yx5629cstDIz1a:blouezh) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L146)):*
> ```Go
> 
> // GetIndexUsageStats implements the idxusage.Reader interface.
> func (is *LocalIndexUsageStats) GetIndexUsageStats(
> ```

The receiver name and function name are a bit redundant. Would `Get` be enough given that it's being called on a `LocalIndexUsageStats` struct?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRf9Sk3XfUsul7e6ID:-MeRf9Sk3XfUsul7e6IE:b-88ssy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L175)):*
> ```Go
> 
> // IterateIndexUsageStats the idxusage.Reader interface.
> func (is *LocalIndexUsageStats) IterateIndexUsageStats(
> ```

`ForEach` might be a name more consistent with other iterators similar to this.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 193 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRY4m2-9IquMb_BFed:-MeRY4m2-9IquMb_BFee:b6w26ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L193)):*
> ```Go
> 	is.mu.RUnlock()
> 
> 	curIter := uint64(0)
> ```

nit: `var curIter uint64`
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 295 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRdv43ECYUi4itbSty:-MeRdv43ECYUi4itbStz:bt2q8j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L295)):*
> ```Go
> func (t *tableIndexStats) iterateIndexStats(
> 	orderedIndexID bool, curIterVal, max *uint64, visitor StatsVisitor,
> ) (earlyStopped bool, err error) {
> ```

Rather than passing around `*unint64`s, you could return a `uint64` that is `max - <number of indexes iterated over>` or `0` if you've iterated `max` times here. Then in `IterateIndexUsageStats` break out of the loop if the returned value is `0`. In general I think it's best to avoid pointer types unless you need mutation or data type is so large that a copy is significantly expensive - neither is true here.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 332 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRfW5H883tF6yGhSWP:-MeRfW5H883tF6yGhSWQ:brr41qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L332)):*
> ```Go
> 			IndexID: indexID,
> 		}, &statsCopy); err != nil {
> 			return earlyStopped, err
> ```

nit: `return false, err` to be more clear this is an error case. The value of `earlyStopped` shouldn't be relied on in the event of an error by the caller, anyway.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 353 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeR_9RP5z6VTEbDxEJS:-MeR_9RP5z6VTEbDxEJT:b-o9k94m) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L353)):*
> ```Go
> 			case payload := <-is.statsChan:
> 				// If the index usage stats collection is disabled, we abort.
> 				if !Enable.Get(&is.st.SV) {
> ```

If we instead put this check in `record` we can avoid the unnecessary work of sending a message to the channel in the case that stats collection is disabled.
___
*[pkg/sql/idxusage/test_utils.go, line 17 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbMex6BZYMBjVc99z:-MeRbMex6BZYMBjVc9A-:b-p3pfd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L17)):*
> ```Go
> // TestingKnobs is the testing knobs that provides callbacks that unit tests
> // can hook into.
> type TestingKnobs struct {
> ```

You could simplify this to a single callback field in `LocalIndexUsageStats` rather than a struct. Unless you see the number of knobs growing anytime soon.
___
*[pkg/sql/idxusage/test_utils.go, line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbG4A69AKCl4nwayX:-MeRbG4A69AKCl4nwayY:b-e6sad) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L26)):*
> ```Go
> 
> // ModuleTestingKnobs implements base.ModuleTestingKnobs interface.
> func (*TestingKnobs) Module [...]

2021-07-13 16:36 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kevin-v-ngo and @mgartner)

___
*[pkg/sql/idxusage/index_usage_stats.go, line 37 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRdKTo5x3gT4n-FNrX:-MeVK4725KJi9OtqDint:bpv3fxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/index_usage_stats.go#L37)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why use a `*uint64` and not `uint64` here?
</blockquote></details>

This is to be able to tell if `Max` is being set or not. This behaviour is used later in the cluster-wide RPC fanout to instruct the RPC endpoint to short circuit and do not return any serialized stats. (and only update the internal cache instead)
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 84 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRgiCo3iz4gNK5Nzfa:-MeVZRY4Bm1nZ9BxrAYt:bqyjzjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L84)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's difficult to verify that 3 different levels of mutexes are being used properly. I don't have much intuition about whether or not this granularity is necessary for performance reasons. Would a single mutex on `LocalIndexUsageStats` that gets acquired for the duration of all reads and writes be unacceptable?
</blockquote></details>

Since `LocalIndexUsageStats` is a singleton object that lives inside the `sql.Server`, having a single top-level mutex means that a single long running read operation can block the entire node from collecting index usage statistics, or vice versa if a SQL node runs hot. I feel this is a potential risk that we can mitigate early on.

Golang's race detector has been pretty good at catching the unsynchronized accesses of the data when I was working on this PR.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 139 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRWjG-3IZr5NsVeLtk:-MeVLZRE9U8leM-6XKZR:butt4wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L139)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm conflicted about where the log should be emitted for level `WARNING=2` or `INFO=1`. Based on the description in log.proto it seems like `1` because there's no action for a user to take if this happens:

```
  // INFO is used for informational messages that do not
  // require action.
  INFO = 1;
  // WARNING is used for situations which may require special handling,
  // where normal operation is expected to resume automatically.
  WARNING = 2;
```
</blockquote></details>

Changed the log to use `1` and `.Infof()` instead of `.Warningf()`.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 146 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRf-Yx5629cstDIz1_:-MeVM-yzB4w2F1gwYsxN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L146)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The receiver name and function name are a bit redundant. Would `Get` be enough given that it's being called on a `LocalIndexUsageStats` struct?
</blockquote></details>

Done.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 175 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRf9Sk3XfUsul7e6ID:-MeVMGIv7-YbmSECpZiy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L175)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`ForEach` might be a name more consistent with other iterators similar to this.
</blockquote></details>

Done.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 193 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRY4m2-9IquMb_BFed:-MeVMj1m0lhFatTA-4qW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L193)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `var curIter uint64`
</blockquote></details>

Done.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 295 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRdv43ECYUi4itbSty:-MeVPhg94XeVSDEYYkSN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L295)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Rather than passing around `*unint64`s, you could return a `uint64` that is `max - <number of indexes iterated over>` or `0` if you've iterated `max` times here. Then in `IterateIndexUsageStats` break out of the loop if the returned value is `0`. In general I think it's best to avoid pointer types unless you need mutation or data type is so large that a copy is significantly expensive - neither is true here.
</blockquote></details>

Done.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 353 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeR_9RP5z6VTEbDxEJS:-MeVQoRmC8gQoxI6oJJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/local_idx_usage_stats.go#L353)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If we instead put this check in `record` we can avoid the unnecessary work of sending a message to the channel in the case that stats collection is disabled.
</blockquote></details>

Done.
___
*[pkg/sql/idxusage/test_utils.go, line 17 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbMex6BZYMBjVc99z:-MeVhwTJ7UHk79zNSA-Z:bzi0lmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L17)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You could simplify this to a single callback field in `LocalIndexUsageStats` rather than a struct. Unless you see the number of knobs growing anytime soon.
</blockquote></details>

Hmm is this simplification necessary? It feels a bit strange to define an interface method (`base.ModuleTestingKnobs`) on a function. I slightly prefer to have testing knobs to explicitly listed out rather than just having it as a callback in the `LocalIndexUsageStats` fields so that it won't be accidentally misused in the future. 
___
*[pkg/sql/idxusage/test_utils.go, line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbG4A69AKCl4nwayX:-MeVY7Ws5E4b8_imXqkn:b-6pvnw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

What's the reason to implement the `base.ModuleTestingKnobs` interface?
</blockquote></details>

This is so that we can pass this testing knob callbacks into the the test clusters (`serverutils.StartNewTestCluster`) in the unit test. [All](https://github.com/cockroachdb/cockroach/blob/bf04383538c4a2226745dcb98769c9695c489081/pkg/base/testing_knobs.go#L21) the testing knobs for each subsystem implements this interface. 


<!-- Sent from Reviewable.io -->

2021-07-13 23:52 UTC, mgartner requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once you fix the `maxIterationLimit` and add a test for it.

Thanks for dealing with all the back-and-forth!

> Reviewed 6 of 13 files at r8, 13 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-MeXH14O0ydDQt_Kn4a5:b-2bhrdu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @mgartner)

___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeXEROK8K-mXmx9nJC5:-MeXEROK8K-mXmx9nJC6:bolix4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4325fba97a6d89b8e67113b96cd8871a31d6a2a/pkg/sql/idxusage/local_idx_usage_stats.go#L210)):*
> ```Go
> 		}
> 
> 		maxIterationLimit, err := tableIdxStats.iterateIndexStats(options.SortedIndexID, maxIterationLimit, visitor)
> ```

I believe this creates a new  `maxIterationLimit` variable that shadows the original. You can avoid this with:

```
var err error
maxIterationLimit, err = tableIdxStats.iterateIndexStats(...)
```

Your tests should catch this if you add a second index for Table 1. Alternatively, you could add a test with a max of 2 which I believe would incorrectly iterate over 3 indexes.
___
*[pkg/sql/idxusage/test_utils.go, line 17 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbMex6BZYMBjVc99z:-MeXG5n8CA2TRUW2_LIX:bq2d6i1) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L17)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm is this simplification necessary? It feels a bit strange to define an interface method (`base.ModuleTestingKnobs`) on a function. I slightly prefer to have testing knobs to explicitly listed out rather than just having it as a callback in the `LocalIndexUsageStats` fields so that it won't be accidentally misused in the future. 
</blockquote></details>

No, not necessary. However, I still don't see the need to implement `base.ModuleTestKnobs`. An alternative is the name the callback in such a way that makes it obvious that it should only be used for testing, but up to you.
___
*[pkg/sql/idxusage/test_utils.go, line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbG4A69AKCl4nwayX:-MeXG-yI7B7gJKtS0IWZ:bme0jff) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L26)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

This is so that we can pass this testing knob callbacks into the the test clusters (`serverutils.StartNewTestCluster`) in the unit test. [All](https://github.com/cockroachdb/cockroach/blob/bf04383538c4a2226745dcb98769c9695c489081/pkg/base/testing_knobs.go#L21) the testing knobs for each subsystem implements this interface. 
</blockquote></details>

I'm confused. I don't see a place where you're starting a server with this knob.


<!-- Sent from Reviewable.io -->

2021-07-14 16:25 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 210 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeXEROK8K-mXmx9nJC5:-Me_a9DFAOHYpjx7kcLJ:b-oop6dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4325fba97a6d89b8e67113b96cd8871a31d6a2a/pkg/sql/idxusage/local_idx_usage_stats.go#L210)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I believe this creates a new  `maxIterationLimit` variable that shadows the original. You can avoid this with:

```
var err error
maxIterationLimit, err = tableIdxStats.iterateIndexStats(...)
```

Your tests should catch this if you add a second index for Table 1. Alternatively, you could add a test with a max of 2 which I believe would incorrectly iterate over 3 indexes.
</blockquote></details>

Ah good catch. Shadowing is so dangerous :cold_sweat: 
___
*[pkg/sql/idxusage/test_utils.go, line 17 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbMex6BZYMBjVc99z:-Me_cDbW3tZINIUKAIvG:b-mx649p) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L17)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

No, not necessary. However, I still don't see the need to implement `base.ModuleTestKnobs`. An alternative is the name the callback in such a way that makes it obvious that it should only be used for testing, but up to you.
</blockquote></details>

Removed the implementation of `base.ModuleTestKnobs` from this PR and will introduce it in the follow up PR where it implements the cluster RPC fanout.
___
*[pkg/sql/idxusage/test_utils.go, line 26 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MeRbG4A69AKCl4nwayX:-Me_bJ4I89w5F6Zug7UB:b-bek2zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/293d7fe22c529e05cc2245da92acb2f1c0b35e36/pkg/sql/idxusage/test_utils.go#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm confused. I don't see a place where you're starting a server with this knob.
</blockquote></details>

Ah my bad, this is actually used for the next PR after it is being integrated into the `statusServer` where I need to spin up a test cluster to test the API. I'll remove it from this PR for now. 


<!-- Sent from Reviewable.io -->

2021-07-14 19:58 UTC, mgartner approved these changes
Nice work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 13 of 13 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-:-MeaaJwDCmEZBhlyyjQF:bnahwna)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)



<!-- Sent from Reviewable.io -->

2021-07-14 20:02 UTC, Azhng commented
TFTR!

bors r=mgartner

2021-07-14 21:05 UTC, merged

2021-11-10 13:29 UTC, mgartner commented
@Azhng Have you had a chance to look at a profile?

2021-11-10 18:22 UTC, Azhng commented
Sorry this slipped through my radar. From the CPU profile it seems using Golang's channel isn't as cheap as we originally expected. Most of the time it seems like it's waiting on futex? 

<img width="677" alt="Screen Shot 2021-11-10 at 13 19 04" src="https://user-images.githubusercontent.com/9267198/141170721-a8e63e48-4e6f-43f7-b4bf-f8e93a2c3cc7.png">

2021-11-10 18:50 UTC, Azhng commented
I dropped the channel and make the `RecordRead` synchronous, it seems like a lot of the overhead from using Golang's channel is gone:

```
azhng@Archers-MacBook-Pro: ~/src/github.com/cockroach statusccl ⚡
$ benchstat ~/tmp/bundle/bundle/7544b/7544b.bench ~/tmp/bundle/4593c-dirty/bench                     [13:47:58]
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24       216µs ± 3%     213µs ± 2%  -1.42%  (p=0.023 n=10+10)
FlowSetup/vectorize=true/distribute=false-24      205µs ± 1%     205µs ± 1%    ~     (p=0.971 n=10+10)
FlowSetup/vectorize=false/distribute=true-24      201µs ± 3%     203µs ± 2%    ~     (p=0.481 n=10+10)
FlowSetup/vectorize=false/distribute=false-24     202µs ± 3%     194µs ± 2%  -3.78%  (p=0.000 n=10+10)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      35.3kB ± 1%    35.2kB ± 1%    ~     (p=0.730 n=9+9)
FlowSetup/vectorize=true/distribute=false-24     33.3kB ± 0%    33.3kB ± 0%    ~     (p=0.505 n=8+8)
FlowSetup/vectorize=false/distribute=true-24     41.0kB ± 3%    41.1kB ± 3%    ~     (p=0.927 n=10+10)
FlowSetup/vectorize=false/distribute=false-24    38.7kB ± 0%    38.7kB ± 0%    ~     (p=0.721 n=8+8)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         320 ± 0%       320 ± 0%    ~     (all equal)
FlowSetup/vectorize=true/distribute=false-24        302 ± 0%       302 ± 0%    ~     (all equal)
FlowSetup/vectorize=false/distribute=true-24        305 ± 0%       305 ± 0%    ~     (all equal)
FlowSetup/vectorize=false/distribute=false-24       287 ± 0%       287 ± 0%    ~     (all equal)
```



<img width="677" alt="Screen Shot 2021-11-10 at 13 49 10" src="https://user-images.githubusercontent.com/9267198/141174732-8ea64a0d-656f-420a-9d3b-755ccab74602.png">

2021-11-10 18:57 UTC, Azhng commented
I'm not sure if we should jump into the conclusions that we should just directly removes the golang's channel directly.
This flowsetup benchmark runs in a single threaded setup, this will make the overhead introduced by Golang's channel very obvious. Single threaded microbenchmark also won't introduce enough contentions on the mutex (therefore making it take the fastpath) we will see in real life scenario when a gateway node runs hot. 

Having a buffered channel here enable to us to effectively performs load shedding if the gateway node runs hot. I think the decision on changing this design should probably depend on the benchmark result of end-2-end testing.

@yuzefovich  thoughts ?

2021-11-11 05:43 UTC, yuzefovich commented
I agree that we should not base our conclusions exclusively on the result of a micro-benchmark (although this one is kinda an end-to-end benchmark itself). It'd be good to get a sense of the impact of this change on other benchmarks (say KV95 and TPCC), so maybe the next action item is to run those benchmarks with these index usage stats enabled vs disabled and see the impact?

Still, on a quick glance I'm not sure how we can speed things up noticeable while we also probably don't want to remove this feature.

2021-11-11 06:02 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66451)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 188 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoCZU370RzOZVKY5o3l:-MoCZU370RzOZVKY5o3m:b-fpi946) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L188)):*
> ```Go
> 
> 	s.mu.RLock()
> 	var tableIDLists []roachpb.TableID
> ```

Here we can allocate the slice with the exact capacity that we need.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 199 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoCZaQK-Jvk44QyFI2O:-MoCZaQK-Jvk44QyFI2P:b-rpsc5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L199)):*
> ```Go
> 	}
> 
> 	s.mu.RUnlock()
> ```

Should we unlock this before `sort.Slice`?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 243 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoCY02c4aAEYtTO4H-d:-MoCY02c4aAEYtTO4H-e:b-g8y49t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L243)):*
> ```Go
> 	case readOp:
> 		indexStats.TotalReadCount++
> 		indexStats.LastRead = timeutil.Now()
> ```

We could get the time without holding the lock. Seems like a simple minor improvement.
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 255 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoCYTl-4kTNvOHzzzwU:-MoCYTl-4kTNvOHzzzwV:b-3l549f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L255)):*
> ```Go
> 	id roachpb.TableID, createIfNotExists bool,
> ) *tableIndexStats {
> 	if createIfNotExists {
> ```

Hm, I think here it might make sense to always acquire `RLock` first regardless of whether `createIfNotExists` is true or not, and only later if it is true _and_ we didn't find a stats object, then we'd upgrade to `RWLock`.

My thinking is that for a particular index it is much more likely that a particular read/write operation is not the first (in other words, if an index exists, it is likely to be used many times), so it makes sense to encounter some additional overhead on the first operation if it makes all consequent operations faster. I guess an exception would be if we were persisting these index stats objects to disk, but I don't think that's the case.

Thoughts?
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 282 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoC_nU_2PHiSVMxv2gZ:-MoC_nU_2PHiSVMxv2g_:b-4s8u6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L282)):*
> ```Go
> 	id roachpb.IndexID, createIfNotExists bool,
> ) *indexStats {
> 	if createIfNotExists {
> ```

ditto for `RLock`
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 304 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoCZqNL1zgqTplDZ0kI:-MoCZqNL1zgqTplDZ0kJ:b-bncxkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L304)):*
> ```Go
> 	orderedIndexID bool, iterLimit uint64, visitor StatsVisitor,
> ) (newIterLimit uint64, err error) {
> 	var indexIDs []roachpb.IndexID
> ```

ditto for exact slice allocation
___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 349 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66451#-MoC_CMH5zSqFvGIB-Ts:-MoC_CMH5zSqFvGIB-Tt:by7fsg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4593c2f169b1b48a36e41c468df7084f272988dc/pkg/sql/idxusage/local_idx_usage_stats.go#L349)):*
> ```Go
> 	defer t.Unlock()
> 
> 	t.stats = make(map[roachpb.IndexID]*indexStats, len(t.stats)/2)
> ```

Rather than allocating a new map it might be better to clear an old one. I have seen comments in the code somewhere that
```
for k := range t.stats {
  delete(t.stats, k)
}
```
is compiled into a fast `mapclear` call or something, and it might be more efficient overall. Just something to consider (and possibly ask in #go-learners slack channel).


<!-- Sent from Reviewable.io -->

2021-11-25 22:48 UTC, Azhng commented
Spend some times running the TPCC-2500 and seems like we do have some spikes in the tail latency

I did 2 two-hour run for each commit.

Without the subsystem:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    31378.3  97.6%     80.6     44.0    113.2    142.6    201.3  22548.6

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    31356.7  97.5%    112.7     37.7    100.7    121.6    184.5  40802.2
```

With the new subsystem


```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    31299.5  97.4%    150.9     50.3    142.6    167.8    268.4  55834.6

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    31355.9  97.5%    101.8     44.0    113.2    142.6    209.7  38654.7
```


Seems like it's about ~0.1% impact on efficiency and observable impact on the latency. 

I'll address this by switching this to synchronous stats collection in #73179