sql: add ddl_analysis tests for multi-region
cockroachdb/cockroach pull request #66489
Opened 2021-06-15 18:02 UTC by pawalt

Previously, ddl_analysis only tested round trips for single-node setups.
This is inadequate with the addition of multi-region tables and
databases.
This patch adds CCL tests for multi-region DDL statements.

Release note: None

2021-06-15 18:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66489)
<!-- Reviewable:end -->

2021-06-15 22:35 UTC, otan reviewed
> Reviewed 17 of 20 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[go.mod, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGX8lr4h_D50errBF5:-McGX8lr4h_D50errBF6:bfdnbpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/go.mod#L141)):*
> ```XML
> 	github.com/pierrre/geohash v1.0.0
> 	github.com/pkg/browser v0.0.0-20180916011732-0a3d74bf9ce4
> 	github.com/pkg/errors v0.9.1
> ```

this should be deleted
___
*[pkg/ccl/ddl_analysisccl/bench_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGXMoc7yh6veVvCENT:-McGXMoc7yh6veVvCENU:b-kz0dqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/ddl_analysisccl/bench_test.go#L1)):*
> ```Go
> package ddl_analysisccl
> ```

this should be `main.go`.
packages cannot have underscore names in them (i think lint should yell at you, but it's not the standard). probably put it in `pkg/ccl/benchccl/ddlanalysisccl`
___
*[pkg/ccl/ddl_analysisccl/multiregion.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGWqkmAnxaxZZv0rzM:-McGWqkmAnxaxZZv0rzN:beo2ddr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/ddl_analysisccl/multiregion.go#L19)):*
> ```Go
> 
> func init() {
> 	sql.InitializeMultiRegionMetadataCCL = multiregionccl.InitializeMultiRegionMetadata
> ```

you should instead do 
```
import _ "github.com/cockroachdb/cockroach/pkg/ccl"
```

in ddl_analysisccl/main_test.go and you don't need the rest of these lines.
___
*[pkg/ccl/multiregionccl/multiregion.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGX6IJ4lGKvMDZoTKa:-McGX6IJ4lGKvMDZoTKb:b-vrpffs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/multiregionccl/multiregion.go#L29)):*
> ```Go
> func init() {
> 	sql.InitializeMultiRegionMetadataCCL = InitializeMultiRegionMetadata
> 	sql.GetMultiRegionEnumAddValuePlacementCCL = GetMultiRegionEnumAddValuePlacement
> ```

revert this after doing the blank import


<!-- Sent from Reviewable.io -->

2021-06-15 22:38 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[go.sum, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGoNA--AJl-TllTmm-:-McGoNA--AJl-TllTmm0:b-n1arpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/go.sum#L83)):*
> ```
> github.com/Azure/go-autorest/autorest/to v0.3.0/go.mod h1:MgwOyqaIuKdG4TL/2ywSsIWKAfJfgHDo8ObuUk3t5sA=
> github.com/Azure/go-autorest/autorest/validation v0.2.0 h1:15vMO4y76dehZSq7pAaOLQxC6dZYsSrj2GQpflyM/L4=
> github.com/Azure/go-autorest/autorest/validation v0.2.0/go.mod h1:3EEqHnBxQGHXRYq3HT1WyXAvT7LLY3tl70hw6tQIbjI=
> ```

all of the changes in this file should be undone i think as well
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGoamtBjtwsOhKCkFC:-McGoamtBjtwsOhKCkFD:b-tb1j6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L21)):*
> ```Go
> 			Setup: `CREATE DATABASE test PRIMARY REGION "us-east-1"`,
> 			Stmt:  `ALTER DATABASE test ADD REGION "us-central-1"`,
> 			Reset: "DROP DATABASE TEST",
> ```

i think we want a DROP REGIOn test too; especially DROP/ADD REGION with several RBR tables.


<!-- Sent from Reviewable.io -->

2021-06-15 23:29 UTC, arulajmani requested changes
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGxqdm0pX9oH5Ypjbw:-McGxqdn-yRgtB_Nv4D1:b-zf1cg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L36)):*
> ```Go
> )
> 
> type benchmarkResult struct {
> ```

What's the motivation behind moving these functions to a new file?
___
*[pkg/ccl/ddl_analysisccl/ddl_analysis_bench.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGyPvR9cgmokzK2YX_:-McGyPvR9cgmokzK2YXa:b-cmwbam) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/ddl_analysis_bench.go#L61)):*
> ```Go
> 			}
> 
> 			cluster := testcluster.StartTestCluster(b, len(localities), params)
> ```

Could we create this using `TestingCreateMultiRegionCluster` here? 
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 15 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGys645CiBupMw5Sgh:-McGys645CiBupMw5Sgi:b-l6ezhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L15)):*
> ```Go
> 			Setup: "CREATE DATABASE test",
> 			Stmt:  `ALTER DATABASE test SET PRIMARY REGION "us-east-1"`,
> 			Reset: "DROP DATABASE TEST",
> ```

nit: s/TEST/test (here and below)
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGoamtBjtwsOhKCkFC:-McGyjBBDiiyQ7fo8IXQ:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L21)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i think we want a DROP REGIOn test too; especially DROP/ADD REGION with several RBR tables.
</blockquote></details>

+1
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGzOOS6MZikNmsY1BJ:-McGzOOS6MZikNmsY1BK:baqqwqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L57)):*
> ```Go
> CREATE TABLE test2 (p int) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> CREATE TABLE test3 (p int) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> CREATE TABLE test4 (p int) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> ```

Can we include a variety of table patterns here? It also might make sense to lift this setup as a fixture so that we can use it to test ADD/DROP region as well (Otan's comment above). 


<!-- Sent from Reviewable.io -->

2021-06-15 23:32 UTC, otan reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[pkg/ccl/ddl_analysisccl/bench_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGXMoc7yh6veVvCENT:-McH06EG5ggcov512Rda:byfy15d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/ddl_analysisccl/bench_test.go#L1)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this should be `main.go`.
packages cannot have underscore names in them (i think lint should yell at you, but it's not the standard). probably put it in `pkg/ccl/benchccl/ddlanalysisccl`
</blockquote></details>

hmm, i guess `ddl_analysis` already broke this, so ignore the underscore. can you move to `ccl/benchccl` though, just for me? :P


<!-- Sent from Reviewable.io -->

2021-06-16 14:30 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[go.mod, line 141 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGX8lr4h_D50errBF5:-McK85j32sTjjlf4U-8U:bwur0xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/go.mod#L141)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this should be deleted
</blockquote></details>

Yeah something went weird when Goland imported something. Should be fixed now
___
*[go.sum, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGoNA--AJl-TllTmm-:-McK8A53EPjY314z7y4r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/go.sum#L83)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

all of the changes in this file should be undone i think as well
</blockquote></details>

Done.
___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGxqdm0pX9oH5Ypjbw:-McK03Oq4uEM7M1uWF0z:b-jjxvj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L36)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What's the motivation behind moving these functions to a new file?
</blockquote></details>

I need to use them in `ddl_analysisccl`, so I had to move them to a non-test file to be imported from the ccl package.
___
*[pkg/ccl/ddl_analysisccl/bench_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGXMoc7yh6veVvCENT:-McK0ZnxC-0ThRkCcNYf:b2nhtan) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/ddl_analysisccl/bench_test.go#L1)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

hmm, i guess `ddl_analysis` already broke this, so ignore the underscore. can you move to `ccl/benchccl` though, just for me? :P
</blockquote></details>

Yup
___
*[pkg/ccl/ddl_analysisccl/ddl_analysis_bench.go, line 61 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGyPvR9cgmokzK2YX_:-McK7cVn7mYWZZ06T7v_:bqijlqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/ddl_analysis_bench.go#L61)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we create this using `TestingCreateMultiRegionCluster` here? 
</blockquote></details>

Yup I thought I couldn't since it only accepted `*testing.T`, but changing that to `testing.TB` did the trick.
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 21 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGoamtBjtwsOhKCkFC:-McKChe67N4X1yqzf0us:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L21)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

+1
</blockquote></details>

OK
___
*[pkg/ccl/ddl_analysisccl/multi_region_bench_test.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGzOOS6MZikNmsY1BJ:-McKCcgW48oVlaTVOjXF:bxv6w19) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b1ce594918fdb42b6cb37f20f5e2e01de659524/pkg/ccl/ddl_analysisccl/multi_region_bench_test.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we include a variety of table patterns here? It also might make sense to lift this setup as a fixture so that we can use it to test ADD/DROP region as well (Otan's comment above). 
</blockquote></details>

Moved to a fixture with GLOBAL, RBR, and RBT
___
*[pkg/ccl/ddl_analysisccl/multiregion.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGWqkmAnxaxZZv0rzM:-McK81pR3M1mXp8iq7DZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/ddl_analysisccl/multiregion.go#L19)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

you should instead do 
```
import _ "github.com/cockroachdb/cockroach/pkg/ccl"
```

in ddl_analysisccl/main_test.go and you don't need the rest of these lines.
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/multiregion.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGX6IJ4lGKvMDZoTKa:-McK82aG5NqhYGaxEm8A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d327ddfe34bbd5e2df2de4ed326041a654abad8b/pkg/ccl/multiregionccl/multiregion.go#L29)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

revert this after doing the blank import
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-16 14:42 UTC, ajwerner commented
drive-by: if we're renaming this package, can we remove the `ddl` from the whole thing? How about `rttanalysis`?

2021-06-16 16:34 UTC, arulajmani requested changes
> Reviewed 8 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGxqdm0pX9oH5Ypjbw:-McKdpY1-nQG4K5gt3sS:b-zeehaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L36)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I need to use them in `ddl_analysisccl`, so I had to move them to a non-test file to be imported from the ccl package.
</blockquote></details>

Maybe I'm missing something, but aren't all the things that moved over to the new file private? 
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-McKYH3ME0PMiMOOa9A7:b-iadbxs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
> ```Go
> USE test;
> CREATE TABLE test11 (p int) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> CREATE TABLE test12 (p int) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION;
> ```

Might be worth creating some `REGIONAL` tables homed in an explicit region (non-primary) too, as the distinction matters for certain operations. 
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McK_mQU6G_lTzolX1wM:-McK_mQU6G_lTzolX1wN:b-kxrumd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L24)):*
> ```Go
> )
> 
> func BenchmarkAlterDatabaseMultiRegion(b *testing.B) {
> ```

Could we re-organize this a bit? How do you feel about putting the first test under `BenchmarkAlterPrimaryRegionMultipleTables` and renaming that to `BenchmarkAlterPrimaryRegion`? 

The second one could go under `BenchmarkAlterRegions`. 

The hope is to group these tests by the specific `ALTER` operation we're testing so that it's easy to know what you're looking at in the `benchmark_expectations` file.
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McK_Z57-2yBzGa1lPS1:-McK_Z57-2yBzGa1lPS2:bs2sua7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L43)):*
> ```Go
> }
> 
> func BenchmarkAlterRegions(b *testing.B) {
> ```

Could we add a version of ADD/DROP region which operates on a database with no tables inside it? 
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 46 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKZV4V-agP61ATTR3F:-McKZV4V-agP61ATTR3G:bqwpno5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L46)):*
> ```Go
> 	tests := []bench.RoundTripBenchTestCase{
> 		{
> 			Name:  "drop region from many tables",
> ```

nit: s/from/with
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKZXzu5AngSRh7WPPL:-McKZXzu5AngSRh7WPPM:b-f7t8yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L52)):*
> ```Go
> 		},
> 		{
> 			Name:  "add region to many tables",
> ```

nit: s/to/with


<!-- Sent from Reviewable.io -->

2021-06-16 20:33 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGxqdm0pX9oH5Ypjbw:-McLDClWDbwEUGR2ODFM:b-sfkhwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L36)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe I'm missing something, but aren't all the things that moved over to the new file private? 
</blockquote></details>

Sorry the exported functions are in `ddl_analysis_bench.go`, and those exported functions call those in this file.
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-McLRcO-A22Oj86dudII:bf6x5vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Might be worth creating some `REGIONAL` tables homed in an explicit region (non-primary) too, as the distinction matters for certain operations. 
</blockquote></details>

Added extra tables for an ALTER REGION and an ALTER PRIMARY REGION tests
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McK_mQU6G_lTzolX1wM:-McLOoy575bFe3KzeIf5:bqxvtjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L24)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we re-organize this a bit? How do you feel about putting the first test under `BenchmarkAlterPrimaryRegionMultipleTables` and renaming that to `BenchmarkAlterPrimaryRegion`? 

The second one could go under `BenchmarkAlterRegions`. 

The hope is to group these tests by the specific `ALTER` operation we're testing so that it's easy to know what you're looking at in the `benchmark_expectations` file.
</blockquote></details>

Yep that makes sense to me. Just moved
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McK_Z57-2yBzGa1lPS1:-McLLvvl2RL7z_PPjwR1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L43)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we add a version of ADD/DROP region which operates on a database with no tables inside it? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-18 16:02 UTC, arulajmani reviewed
Sorry I got pulled away and forgot to press send. Couple minor requests but other than that this looks very close  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-:-McUqf5cEZLP6cPu0pL3:b-zahkf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/bench/ddl_analysis/validate_benchmark_data.go, line 1 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McLiQZMB_F7nNzYRVp_:-McLiQZMB_F7nNzYRVpa:b-jb9253) ([raw file](https://github.com/cockroachdb/cockroach/blob/e323f71279f3ce3fc27beedd802c032e1c68ef1c/pkg/bench/ddl_analysis/validate_benchmark_data.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

nit: 2021 
___
*[pkg/bench/ddl_analysis/validate_benchmark_data_test.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McGxqdm0pX9oH5Ypjbw:-McUqSAY137Eip8NWaQf:b-c2gzze) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb046e1b8568b2c5ff2e2f4af03cd3c10eb10a21/pkg/bench/ddl_analysis/validate_benchmark_data_test.go#L36)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Sorry the exported functions are in `ddl_analysis_bench.go`, and those exported functions call those in this file.
</blockquote></details>

Ah gotcha. 
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-McLhkoLEGhdQ-8W5iKp:bjbrby1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Added extra tables for an ALTER REGION and an ALTER PRIMARY REGION tests
</blockquote></details>

I wonder if it makes sense to encode it in the fixture itself? That way, all the tests will be able to run with all types of table localities. 
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McUo9xOEMMjyWJJCqOf:-McUo9xOEMMjyWJJCqOg:b-hipg5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e323f71279f3ce3fc27beedd802c032e1c68ef1c/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L9)):*
> ```Go
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> 
> package bench
> ```

Should this be benchccl? Alternatively, you could rename the original package `rttanalysis` and name this `rttanalysisccl`. It'd be nice to clean this up, as these tests are no longer just "ddl analysis tests". Wdyt?


<!-- Sent from Reviewable.io -->

2021-06-21 14:09 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-McipnthBZHyG-x_cQoO:bqfwimk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I wonder if it makes sense to encode it in the fixture itself? That way, all the tests will be able to run with all types of table localities. 
</blockquote></details>

I think that makes sense. I hadn't done that originally because it messes with the "drop us-east2" bench case, but I realize now that I can just alter the us-east2 tables to us-east1 in the setup for that test.
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 9 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McUo9xOEMMjyWJJCqOf:-MciqTKfEUMIlMOBCy1Y:b-8x7hl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e323f71279f3ce3fc27beedd802c032e1c68ef1c/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L9)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be benchccl? Alternatively, you could rename the original package `rttanalysis` and name this `rttanalysisccl`. It'd be nice to clean this up, as these tests are no longer just "ddl analysis tests". Wdyt?
</blockquote></details>

Makes sense to me. I think `rttanalysis` is more accurate


<!-- Sent from Reviewable.io -->

2021-06-21 17:47 UTC, arulajmani requested changes
> Reviewed 4 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/bench/rttanalysis/ddl_analysis_bench.go, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjfQJv6mR9mfujp6is:-McjfQJv6mR9mfujp6it:bp6dicb) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/bench/rttanalysis/ddl_analysis_bench.go#L1)):*
> ```Go
> // Copyright 2020 The Cockroach Authors.
> ```

Should this file now be called rtt_analysis_bench.go instead?
___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-Mcj_AHs8_dMa-5kCR9N:b-z5s1h1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I think that makes sense. I hadn't done that originally because it messes with the "drop us-east2" bench case, but I realize now that I can just alter the us-east2 tables to us-east1 in the setup for that test.
</blockquote></details>

I was hoping we could make this test fixture a constant for all the microbenchmarks that we run. I think it'll make things much easier to follow. Concretely, instead of altering some tables in the "drop us-east2" case, why not add "us-east3" to the fixture and drop "us-east3" instead? (Note that this would mean you would have to change the "add us-east3" test to "add us-east4", but that seems fine.)

Separately, Is there a difference between "drop region with many tables" and "drop region with non-primary tables"? I think we've reorganized these tests a bit now, so it might be worth taking a step back and double checking we're being intentional about what is being tested. 

Additionally, might also be worth revisiting the microbenchmark names to make them uniform. For example, in `BenchmarkAlterRegions`, the first two test names say nothing about the fact that there's no tables in the database. 
___
*[pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjfBPF3ARpRLe1C68t:-McjfBPF3ARpRLe1C68u:b1ltj33) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

Should this file now be called `rtt_analysis_bench`?
___
*[pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go, line 17 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-Mcjf6ZpASC1h8V7P9R5:-Mcjf6ZpASC1h8V7P9R6:b-rh4vg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go#L17)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/base"
> 	ddlbench "github.com/cockroachdb/cockroach/pkg/bench/rttanalysis"
> ```

nit: do you still need this?
___
*[pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjfZcU4DaZaNuAZX0R:-McjfZcU4DaZaNuAZX0S:b-rh4vg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go#L14)):*
> ```Go
> 	"testing"
> 
> 	bench "github.com/cockroachdb/cockroach/pkg/bench/rttanalysis"
> ```

nit: do you still need this?
___
*[pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjZnjM7dMc6K79Wamb:-McjZnjM7dMc6K79Wamc:b-5w580c) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go#L52)):*
> ```Go
> 			Setup: multipleTableFixture + `
> ALTER TABLE test41 SET LOCALITY REGIONAL BY ROW IN "us-east1";
> ALTER TABLE test42 SET LOCALITY REGIONAL BY ROW IN "us-east1";
> ```

I don't think `REGIONAL BY ROW IN "us-east1"` is thing.


<!-- Sent from Reviewable.io -->

2021-06-22 20:48 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-McpTd3V-vADR8Oz0AYe:b-5qu35t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I was hoping we could make this test fixture a constant for all the microbenchmarks that we run. I think it'll make things much easier to follow. Concretely, instead of altering some tables in the "drop us-east2" case, why not add "us-east3" to the fixture and drop "us-east3" instead? (Note that this would mean you would have to change the "add us-east3" test to "add us-east4", but that seems fine.)

Separately, Is there a difference between "drop region with many tables" and "drop region with non-primary tables"? I think we've reorganized these tests a bit now, so it might be worth taking a step back and double checking we're being intentional about what is being tested. 

Additionally, might also be worth revisiting the microbenchmark names to make them uniform. For example, in `BenchmarkAlterRegions`, the first two test names say nothing about the fact that there's no tables in the database. 
</blockquote></details>

I renamed most of the cases and cleaned up any duplicates. Should be more consistent now
___
*[pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjfBPF3ARpRLe1C68t:-McpToZ19zb10NmTbekb:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/ddl_analysis_bench.go#L1)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this file now be called `rtt_analysis_bench`?
</blockquote></details>

Done
___
*[pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go, line 52 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McjZnjM7dMc6K79Wamb:-McpTkUYBOm7Ul0TTATG:b-gd2wqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/88bb7a7817ce6e16e818ffb8a51cfa2f983601c6/pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go#L52)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think `REGIONAL BY ROW IN "us-east1"` is thing.
</blockquote></details>

Lol yep not sure how that happened


<!-- Sent from Reviewable.io -->

2021-06-23 04:04 UTC, arulajmani approved these changes
Nice! Thanks for iterating on this and improving the general structure of this thing. I like where this ended up! Plus, we've got some roundtrips to chase down 

Before merging, could you please re-word your commit message to say "rtt_analysis" instead of "ddl_analysis" as the name has changed now? We should also link the issue in the commit message. If you write `closes #...` or `fixes #...`, the issue will automatically get closed once the PR merges. 

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> once CI is happy   

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-:-Mcr05hC9Y2d-CI0hTDk:bvkrare)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @pawalt)

___
*[pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go, line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-McKYH3ME0PMiMOOa9A6:-Mcr08NM33DcLcLaHpDe:b-ecpsw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4336faf93973e5436d535c02f715d9b96ff5d230/pkg/ccl/benchccl/ddl_analysis/multi_region_bench_test.go#L14)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I renamed most of the cases and cleaned up any duplicates. Should be more consistent now
</blockquote></details>

:100: :100: 
___
*[pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go, line 124 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-Mcr-pBb1FLzN_pt0l8l:-Mcr-pBb1FLzN_pt0l8m:b-cg1g0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfffeefa52450d9c9068b1c5ab30f7f7ec977705/pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go#L124)):*
> ```Go
> 		},
> 		{
> 			Name:  "alter from zone to region",
> ```

nit: alter populated database from zone to region? 
___
*[pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go, line 130 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66489#-Mcr-t2sA11WOmtQq0-9:-Mcr-t2sA11WOmtQq0-A:b-r3trfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfffeefa52450d9c9068b1c5ab30f7f7ec977705/pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go#L130)):*
> ```Go
> 		},
> 		{
> 			Name: "alter from region to zone",
> ```

nit: alter populated database from region to zone? 


<!-- Sent from Reviewable.io -->

2021-06-24 14:06 UTC, pawalt commented
Resolves #65149

2021-06-24 14:10 UTC, pawalt commented
bors r+

2021-06-24 15:01 UTC, arulajmani commented
@pawalt, looks like CI isn't quite happy yet. It's best practice to wait for CI to be green before trying to bors something in.  

bors r-

2021-06-25 17:13 UTC, pawalt commented
bors r+

![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2021-06-25 17:58 UTC, merged