[WIP] sql: add datadriven tests for multiregion tables
cockroachdb/cockroach pull request #66735
Opened 2021-06-22 21:04 UTC by pawalt

Previously, we only had datadriven tests for GLOBAL tables.
This patch adds datadriven tests for regional by [table|row] tables.

Release note: None

2021-06-22 21:04 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66735)
<!-- Reviewable:end -->

2021-06-23 14:52 UTC, pawalt commented
Resolves #66381

2021-06-24 14:56 UTC, arulajmani requested changes
I really like that you put in comments explaining why we're testing what we're testing in the file. I think that's super important when trying to parse a "dry looking test" like this. 

There's a couple other axes worth exploring in this PR: 

- Let's throw some follower reads into the mix? 
- Let's do some tests once we change from ZONE survival to REGION survival?
- Let's throw an add/drop region in there as well and make some assertions using follower reads? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-McyUs2T16LfuwY915ON:b-eypsw7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-McyRvrOBZH39kXn81Cb:bmso9dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
> ```
> ----
> 
> refresh-range-descriptor-cache idx=0 table-name=rbt
> ```

Is this required on the leaseholder node?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyTYOw9HNmXZ8az9pU:-McyTYOw9HNmXZ8az9pV:bcz5z16) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L55)):*
> ```
> LAG_BY_CLUSTER_SETTING
> 
> # Note that eu-central-1 is not a region on the database, therefore it shouldn't
> ```

Even if eu-central-1 was a region on the database, it could never have the leaseholder replica as the table is homed in us-east. Should change this query to do a follower read instead?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyUY3bBR15t2tmozXJ:-McyUY3bBR15t2tmozXK:bz3ha76) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L63)):*
> ```
> 
> exec-sql idx=0
> ALTER TABLE db.rbt SET LOCALITY REGIONAL BY TABLE IN "us-west-1";
> ```

In the test setup above, "us-west" only has one node in it. Running the database under zone failure should want to move all 3 voters into "us-west" when you do this change. Maybe we should setup the test cluster such that this can happen? 


<!-- Sent from Reviewable.io -->

2021-06-28 18:01 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-MdIIGtXC5PM7qtR0ffJ:bak4enq) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is this required on the leaseholder node?
</blockquote></details>

Nope. I was doing it before all reads just to be consistent, but can remove it.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyTYOw9HNmXZ8az9pU:-MdIJ0r55z8BAw7LW_LF:b1g3oum) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L55)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Even if eu-central-1 was a region on the database, it could never have the leaseholder replica as the table is homed in us-east. Should change this query to do a follower read instead?
</blockquote></details>

I think that makes sense. I added a `sleep` directive to make sure we can do the follower read in the proper window. Is that the right way to do things, or is there a no-wait way to run follower reads? I typically don't like putting waits in tests but can't see any other way.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyUY3bBR15t2tmozXJ:-MdIJFIO1CVX935JkwV-:brihcjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L63)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

In the test setup above, "us-west" only has one node in it. Running the database under zone failure should want to move all 3 voters into "us-west" when you do this change. Maybe we should setup the test cluster such that this can happen? 
</blockquote></details>

Agreed we should do this, but I'm not sure how I would test that a non-leaseholder replica is a voter. It seems like right now, all I can test is that a read happened in the following cases:
- locally as leaseholder
- locally as follower read
- remotely

As I understand it, voters and non-voters would have the same behavior in the last two cases.


<!-- Sent from Reviewable.io -->

2021-06-28 19:25 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2Ev0B1e2YmjXEqWQ:-MdJ2Ev0B1e2YmjXEqWR:b-ly40jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/datadriven_test.go#L92)):*
> ```Go
> // table-name argument, the closed timestamp policy is returned.
> //
> // "sleep duration=duration": sleeps for duration time. The duration is parsed
> ```

Instead of giving test writers the ability to randomly sleep for some amount of time, let's instead have a follower read specific timestamp that doesn't take in an arbitrary duration? See the code snippet I linked below for inspiration. 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-MdJ-pmCBshPyokMSWtv:bk9p0ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Nope. I was doing it before all reads just to be consistent, but can remove it.
</blockquote></details>

I think if it isn't required it only serves to confuse. Let's remove it! 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyTYOw9HNmXZ8az9pU:-MdJ1d9D4QQE15wTYPAg:b6dcf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L55)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I think that makes sense. I added a `sleep` directive to make sure we can do the follower read in the proper window. Is that the right way to do things, or is there a no-wait way to run follower reads? I typically don't like putting waits in tests but can't see any other way.
</blockquote></details>

Your hunch is right, but I'm not sure there is a way to do this. At the least, we need to ensure that the table's creation timestamp is below the follower read timestamp. We could quicken things up here, see https://github.com/cockroachdb/cockroach/blob/1b38b77dff11e1da0f016af46fb8e3ab18b627d6/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L551 for an example. 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyUY3bBR15t2tmozXJ:-MdJ2WHh9e0kPryb6KVV:b-n0wg60) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L63)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Agreed we should do this, but I'm not sure how I would test that a non-leaseholder replica is a voter. It seems like right now, all I can test is that a read happened in the following cases:
- locally as leaseholder
- locally as follower read
- remotely

As I understand it, voters and non-voters would have the same behavior in the last two cases.
</blockquote></details>

As discussed on Slack, I don't think we should worry about differentiating between voters/non-voters at this level. 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3KimEY4pf0Or2c6x:-MdJ3KimEY4pf0Or2c6y:b-jc0q3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L1)):*
> ```
> new-cluster localities=us-east-1,us-east-1,us-east-1,us-west-1,us-central-1,eu-central-1
> ```

Should we add 2 more nodes in us-west-1?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ1Pk_-1aJIxH-02Wp:-MdJ1Pk_-1aJIxH-02Wq:bjad0ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L75)):*
> ```
> # a follower read.
> trace-sql idx=5
> SELECT * FROM db.rbt WHERE k = 1
> ```

Does doing a present time read here add much value? As I understand it, we only need to do a follower read here, right?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2wGC7juljO66i5Al:-MdJ2wGC7juljO66i5Am:b-hl5mg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L106)):*
> ```
> LAG_BY_CLUSTER_SETTING
> 
> trace-sql idx=3
> ```

Could you add a comment here explaining this step and why the present time read is served locally? 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3h9D-jy8FnL_pgMJ:-MdJ3h9D-jy8FnL_pgMK:b-u6cq3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L116)):*
> ```
> 
> # Sleep to ensure we can get follower reads post region change.
> sleep duration=6s
> ```

Do we need need another sleep after we've already slept above?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3w3B1_vnn8UCsI0g:-MdJ3w3C8tllLYBrjqc7:bixidwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L139)):*
> ```
> 
> # Sleep to ensure we can get follower reads post region change.
> sleep duration=6s
> ```

Do you need to sleep here to get follower reads post region change?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ4F1o-Sq4j0cnta0S:-MdJ4F1p4VJX2yknfa39:b2f437t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L168)):*
> ```
> ----
> 
> wait-for-zone-config-changes idx=0 table-name=rbt num-voters=3 num-non-voters=3 lease-holder-node=0
> ```

Do you need this? Or can you alter to region survivability and wait just once, at the end?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3VSX1AeX7ZeGsyUd:-MdJ3VSX1AeX7ZeGsyUe:b-n0kwk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L178)):*
> ```
> ----
> 
> wait-for-zone-config-changes idx=0 table-name=rbt num-voters=5 num-non-voters=0 lease-holder-node=0
> ```

We should probably run the follower reads queries from all regions in the `SURVIVE REGION FAILURE` mode as well. 


<!-- Sent from Reviewable.io -->

2021-06-28 22:45 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-MdJSjqn1kRwq3ccUGkF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think if it isn't required it only serves to confuse. Let's remove it! 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyUY3bBR15t2tmozXJ:-MdJSqDT6BWngm3-7Iar:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L63)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

As discussed on Slack, I don't think we should worry about differentiating between voters/non-voters at this level. 
</blockquote></details>

Ack.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3KimEY4pf0Or2c6x:-MdJiThs2EdhuBHN5U6c:bbv80ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L1)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we add 2 more nodes in us-west-1?
</blockquote></details>

I don't think we need to since we're just worried about leaseholder info. We wouldn't be testing anything about those other 2 nodes.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ1Pk_-1aJIxH-02Wp:-MdJSmTf1CZQMr8FiSKB:bj27qlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L75)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Does doing a present time read here add much value? As I understand it, we only need to do a follower read here, right?
</blockquote></details>

Yup fair. Removed.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2wGC7juljO66i5Al:-MdJV5bXENAs8wVukACK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L106)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you add a comment here explaining this step and why the present time read is served locally? 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3h9D-jy8FnL_pgMJ:-MdJVaqMAUGMCxIvpzNZ:b-2empue) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L116)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need need another sleep after we've already slept above?
</blockquote></details>

If I remove that sleep, I get `recording contains > 1 dist sender send messages`. It seems like rehoming the table forces me to wait the closed timestamp duration.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 139 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3w3B1_vnn8UCsI0g:-MdJW1CR-3-jDdr8zhch:b-wqgwkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L139)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you need to sleep here to get follower reads post region change?
</blockquote></details>

See above `dist sender send` comment.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ4F1o-Sq4j0cnta0S:-MdJW4he2TdtncUSDBEf:b-tyx1xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L168)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you need this? Or can you alter to region survivability and wait just once, at the end?
</blockquote></details>

I do this to make it explicit that we're going from 3/3 to 5/0 voters/nonvoters. Since the regions were just added, we haven't validated that we're in a 3/3 configuration, so I just want to make sure of that before changing the survivability.


<!-- Sent from Reviewable.io -->

2021-06-29 15:17 UTC, arulajmani requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-MdNL0Ta4_fqx8s9YEVb:b-l7y1wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we remove the other ones too that aren't required below?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3KimEY4pf0Or2c6x:-MdN6jDT2iHooj6TqG8m:bvtmpa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L1)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I don't think we need to since we're just worried about leaseholder info. We wouldn't be testing anything about those other 2 nodes.
</blockquote></details>

But aren't your constraints unsatisfiable when you re-home the table to `us-west1`? Unsatisfiable constraints have implications on replication and I'd rather we avoid it unless there is a good reason to. 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3h9D-jy8FnL_pgMJ:-MdNK1Bs3isCDTtgVvT8:b-vushtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L116)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

If I remove that sleep, I get `recording contains > 1 dist sender send messages`. It seems like rehoming the table forces me to wait the closed timestamp duration.
</blockquote></details>

That's slightly surprising, do you know why it happens? I think it's worth digging to confirm this is indeed expected. Happy to look over the trace with you, if you want.


<!-- Sent from Reviewable.io -->

2021-07-07 20:27 UTC, rytaft commented
I think you might need to rebase -- looks like you pulled in an unrelated commit





<!-- Sent from Reviewable.io -->

2021-07-12 16:15 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2Ev0B1e2YmjXEqWQ:-MeQTqnl80Wrn4GAjUX_:bulds6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/datadriven_test.go#L92)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of giving test writers the ability to randomly sleep for some amount of time, let's instead have a follower read specific timestamp that doesn't take in an arbitrary duration? See the code snippet I linked below for inspiration. 
</blockquote></details>

If we're assuming that we'll be modifying the follower read time in the test, does this make sense? It feels wrong to have a command that only works as expected if you've already run the proper SQL.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyRvrN2_H61oOlH-g7:-MeQTNWyD2bnw0EGoxa7:b9uoqgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L19)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we remove the other ones too that aren't required below?
</blockquote></details>

Yep I took another pass to reorganize and remove the refreshes where possible.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-McyTYOw9HNmXZ8az9pU:-MeQUGZj5OgKobMLW_Le:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87bb571e58ec82da606badbfc4472bfc8d8a4d56/pkg/ccl/multiregionccl/testdata/regional_by_table#L55)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Your hunch is right, but I'm not sure there is a way to do this. At the least, we need to ensure that the table's creation timestamp is below the follower read timestamp. We could quicken things up here, see https://github.com/cockroachdb/cockroach/blob/1b38b77dff11e1da0f016af46fb8e3ab18b627d6/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L551 for an example. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3KimEY4pf0Or2c6x:-MeQOxHg3TNZDcGzKVRi:b-jwfr7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L1)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

But aren't your constraints unsatisfiable when you re-home the table to `us-west1`? Unsatisfiable constraints have implications on replication and I'd rather we avoid it unless there is a good reason to. 
</blockquote></details>

I've added 3 us-west-1 replicas now that we can test voters vs nonvoters, so should be good here.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3h9D-jy8FnL_pgMJ:-MeQTXOnBCjDVX8Ns0ll:b-234kau) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L116)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

That's slightly surprising, do you know why it happens? I think it's worth digging to confirm this is indeed expected. Happy to look over the trace with you, if you want.
</blockquote></details>

I'm not sure other than seeing some `SystemConfig` lookup. I've included a comment about it in the file. Happy to look over a trace as well.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ3VSX1AeX7ZeGsyUd:-MeQTVMQ0MfRbCPvDenT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/testdata/regional_by_table#L178)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We should probably run the follower reads queries from all regions in the `SURVIVE REGION FAILURE` mode as well. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-12 19:04 UTC, arulajmani reviewed
Thanks for continuing to dig into this! I haven't looked at closely at the test itself yet -- most of my comments are around the updates you've made to the test framework itself. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-MeR4Pp48AkZDH5SrlKb:bt2k747)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2Ev0B1e2YmjXEqWQ:-MeQqgZrBcx-V0Y3FPVM:b-n71psw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/datadriven_test.go#L92)):*
Isn't the amount of time you've to sleep for a follower read constant, regardless of the actual timestamp the read was performed at? Is there a benefit to allow the test writer to sleep for an arbitrary amount of time instead of the follower read timestamp? 

> It feels wrong to have a command that only works as expected if you've already run the proper SQL.
Wdym?  I don't follow.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR2rCC9d1TEwtrBjGf:-MeR2rCC9d1TEwtrBjGg:b2fcizw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L68)):*
> ```Go
> // leaseholder.
> //
> // "wait-for-zone-config-changes idx=server_number table-name=tbName
> ```

this blurb here would need an update too with the new directives that you added. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQveo1DcfIODAkHMn6:-MeQveo1DcfIODAkHMn7:bl8o57r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L73)):*
> ```Go
> // split, replicate, and raftsnapshot queues. If the num-voters or num-non-voters
> // arguments are provided, it then makes sure that the range conforms to those.
> // It also takes input in the form of comma separated pairs of <server_idx>=<replica_type>,
> ```

I think it makes more sense to have <replica_type>=<server_idx ids> as the input directive here. 

Also, what's the motivation behind accepting "not-present"? Can we just infer this as the default? 

Separately, now that we're accepting which node has which replica type, do we still need to accept `num-non-voters` and `num-voters`? Or can we clean this up? 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MeR0P7B8kE83Q_5TMrZ:b6rh597) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
> ```Go
> 						Tiers: []roachpb.Tier{
> 							{Key: "region", Value: localityName},
> 							{Key: "zone", Value: localityName + string(zoneLabel)},
> ```

Did you need this for the test or was this a quality of life improvement?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 217 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQrdAI-Dz8dl3vpzr7:-MeQrdAI-Dz8dl3vpzr8:b-seuqny) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L217)):*
> ```Go
> 					}
> 					rec := <-recCh
> 					t.Log(rec)
> ```

nit: could you add a message string before?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 332 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1vSj8IQGs7J8iert:-MeR1vSj8IQGs7J8ieru:bylx7zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L332)):*
> ```Go
> 					}
> 
> 					// Parse user localities from input.
> ```

I think the term "locality" here and in other places is quite misleading. You're dealing with replica types which are orthogonal to localities. Could you clean up the terminology here and in the helper functions you wrote? 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 336 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR5VoQB0rnwER6tSI8:-MeR5VoQB0rnwER6tSI9:bhwsz9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L336)):*
> ```Go
> 
> 					// If the user specified a leaseholder, transfer range lease to the leaseholder.
> 					for nodeIdx, locality := range expectedLocalities {
> ```

If you construct your map as locality -> nodeIndexes in the helper above you could get rid of this loop as the leaseholder is singular. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 341 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQxbrHDf3Iw-ifzgdi:-MeQxbrHDf3Iw-ifzgdj:bbkz2a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L341)):*
> ```Go
> 							leaseErr := errors.Newf("expected leaseholder %d but got %d", nodeIdx, leaseIdx)
> 
> 							// We want to only initiate a range transfer if our target replica is a voter. Otherwise, this will silently fail.
> ```

s/range transfer/lease transfer/g
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 341 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQyQLt6jMi-mkUqvtR:-MeQyQLt6jMi-mkUqvtS:b-omytim) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L341)):*
> ```Go
> 							leaseErr := errors.Newf("expected leaseholder %d but got %d", nodeIdx, leaseIdx)
> 
> 							// We want to only initiate a range transfer if our target replica is a voter. Otherwise, this will silently fail.
> ```

nit: wrap comments at 80 chars
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 350 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQyW3B9QzM2Z8I8_vz:-MeQyW3B9QzM2Z8I8_w-:bdykvhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L350)):*
> ```Go
> 							}
> 							if !foundVoter {
> 								return errors.CombineErrors(leaseErr, errors.Newf("expected node %s to be a voter but was not", nodeIdx))
> ```

nit: long line, wrap at 100 chars
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 353 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1Dp5DcEq2VA6atPS:-MeR1Dp5DcEq2VA6atPT:b-r2za9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L353)):*
> ```Go
> 							}
> 
> 							// Only want to transfer a lease once.
> ```

Could you say a bit more about why we only want to attempt a lease transfer only once? 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 368 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQyYrdA7jd7WPiyxdA:-MeQyYrdA7jd7WPiyxdB:b-pa92bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L368)):*
> ```Go
> 					}
> 
> 					// Get current locality info from range and validate against user-specified localities
> ```

nit: full stop, 80 chars
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 431 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQydWp6W7Sp6D1X0um:-MeQydWp6W7Sp6D1X0un:b-95pxem) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L431)):*
> ```Go
> 	"leaseholder": replicaTypeLeaseholder,
> 	"voter":       replicaTypeVoter,
> 	"nonvoter":    replicaTypeNonvoter,
> ```

nit: s/nonvoter/non-voter/g
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 437 at r6] [...]

2021-07-14 01:13 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MdJ2Ev0B1e2YmjXEqWQ:-MeVVoY2Abvf4Rpg_fnt:bu8ma8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ba63e1e31781df4093dc8c77f5824146a592471/pkg/ccl/multiregionccl/datadriven_test.go#L92)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Isn't the amount of time you've to sleep for a follower read constant, regardless of the actual timestamp the read was performed at? Is there a benefit to allow the test writer to sleep for an arbitrary amount of time instead of the follower read timestamp? 

> It feels wrong to have a command that only works as expected if you've already run the proper SQL.
Wdym?  I don't follow.
</blockquote></details>

I was talking about the `SET CLUSTER SETTING kv.closed_timestamp.target_duration = '0.4s'` directive, but the comments about adding this automatically on cluster startup fix this.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR2rCC9d1TEwtrBjGf:-MeVRbk73eU4NZyrJEt5:b9s9923) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L68)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

this blurb here would need an update too with the new directives that you added. 
</blockquote></details>

That's done - see the description about comma separated pairs of server_idx/replica_type.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQveo1DcfIODAkHMn6:-MeVRtgoDin7KcBSQJFJ:b-wq85kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L73)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think it makes more sense to have <replica_type>=<server_idx ids> as the input directive here. 

Also, what's the motivation behind accepting "not-present"? Can we just infer this as the default? 

Separately, now that we're accepting which node has which replica type, do we still need to accept `num-non-voters` and `num-voters`? Or can we clean this up? 
</blockquote></details>

Do you mean something like `voter=1,2,3`? I think that makes sense.

We can't infer not-present as default because there are some times where we don't know deterministically what state a server should be in. For example, if you have REGIONAL BY TABLE homed in `us-east-1` and `us-west-1` is in the database with has 2 servers, it's not deterministic which of the 2 servers will become a nonvoter.

We can't drop those `num-*` arguments for this reason as well - we may still want to constrain to 2 nonvoters even if we don't know the server-specific placement of those nonvoters.

Future work might allow us to add a directive to say something like "ensure that exactly one replica in `us-west-1` is a nonvoter", but I think that's better for a future PR.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MeVTSFm3-dVgI_SespT:b5pi2ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did you need this for the test or was this a quality of life improvement?
</blockquote></details>

This is needed for the test - replicas in the same region need to be in different zones. I was getting flakes otherwise; I assume that was to do with zone survivability.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 217 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQrdAI-Dz8dl3vpzr7:-MeVTmI-AU7MmzaLRizX:bl26ztw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L217)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: could you add a message string before?
</blockquote></details>

I was just using this for debugging, so I'll just remove this.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 332 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1vSj8IQGs7J8iert:-MeVldok31xATulM8uiQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L332)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think the term "locality" here and in other places is quite misleading. You're dealing with replica types which are orthogonal to localities. Could you clean up the terminology here and in the helper functions you wrote? 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 336 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR5VoQB0rnwER6tSI8:-MeVwcr73L7uBzck2I82:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L336)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

If you construct your map as locality -> nodeIndexes in the helper above you could get rid of this loop as the leaseholder is singular. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 341 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQxbrHDf3Iw-ifzgdi:-MeVTzuJ9w_FLdhLCVRm:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L341)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/range transfer/lease transfer/g
</blockquote></details>

Thanks
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 353 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1Dp5DcEq2VA6atPS:-MeVZa4O2tbmUaERK_IU:b-cptaup) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L353)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you say a bit more about why we only want to attempt a lease transfer only once? 
</blockquote></details>

Yep added.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 464 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR3TJl1HqKglS-WEn_:-MeVklD_8-PXpMtiGP1v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L464)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

See comment about "localities" being misleading in this context. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 484 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR3Ifd1486YqfFqxb5:-MeVklbz9W5GxZPGs1VY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L484)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

See comment above about "localities" being misleading here. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 514 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR485B1VXVrVoKMUN [...]

2021-07-19 00:18 UTC, arulajmani reviewed
Mostly minor comments, this feels close! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-Mew4CeG80cKFb7rdWc3:b-e1i24g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQveo1DcfIODAkHMn6:-Mew4nBK15efjJabE7Kg:bhwpa33) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L73)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Do you mean something like `voter=1,2,3`? I think that makes sense.

We can't infer not-present as default because there are some times where we don't know deterministically what state a server should be in. For example, if you have REGIONAL BY TABLE homed in `us-east-1` and `us-west-1` is in the database with has 2 servers, it's not deterministic which of the 2 servers will become a nonvoter.

We can't drop those `num-*` arguments for this reason as well - we may still want to constrain to 2 nonvoters even if we don't know the server-specific placement of those nonvoters.

Future work might allow us to add a directive to say something like "ensure that exactly one replica in `us-west-1` is a nonvoter", but I think that's better for a future PR.
</blockquote></details>

Ack, yeah, that makes sense. I think it's worth calling out in this comment here that test writers don't need to provide deterministic constraints for all replicas, just some. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 332 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1vSj8IQGs7J8iert:-MevyIBC6J3Cs3apCV5x:b-42xfhg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L332)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: s/user replica types/user supplied expected replica types/
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 353 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1Dp5DcEq2VA6atPS:-Mew2LHmEtVTW__FVXL9:bc8ya99) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L353)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Yep added.
</blockquote></details>

Wait looks like we're no longer doing this "only attempt transfer lease once" -- is this comment stale then?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 514 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR485B1VXVrVoKMUNk:-MevyU_hD68znNyCYbyn:btb8and) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L514)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: s/parseUserReplicas/parseExpectedReplicasFromInput/
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 68 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MevxiWr8USuCGN4LpZT:-MevxiWr8USuCGN4LpZU:bg1z9lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L68)):*
> ```Go
> // "wait-for-zone-config-changes idx=server_number table-name=tbName
> // [num-voters=num] [num-non-voters=num] [leaseholder=idx] [voter=idx_list]
> // [nonvoter=idx_list] [not-present=idx_list]": finds the
> ```

nit: this needs an update now, it's called non-voter
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew2wKEAIu_nLiFtcOc:-Mew2wKEAIu_nLiFtcOd:buzo049) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L361)):*
> ```Go
> 							// is a voter. Otherwise, this will silently fail.
> 							expectedNodeId := ds.tc.Target(nodeIdx).NodeID
> 							foundVoter := false
> ```

You could move the call to `parseRangeReplicas` above this (outside the if block, right where you're calling parseUserReplicas` to get rid of this for loop. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 443 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew12v34Z7L1KRD-9DV:-Mew12v34Z7L1KRD-9DW:bi1o7wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L443)):*
> ```Go
> 	replicaTypeLeaseholder replicaType = iota
> 	replicaTypeVoter
> 	replicaTypeNonvoter
> ```

s/replicaTypeNonvoter/replicaTypeNonVoter/
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 487 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew-5GcBXq7WXGna1Nk:-Mew-5GcBXq7WXGna1Nl:b6ddmer) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L487)):*
> ```Go
> }
> 
> func validateReplicas(expected map[replicaType][]int, actual map[int]replicaType) error {
> ```

s/validateReplicas/ensureCorrectReplicaPlacement/
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 497 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew0qoQ7OsJjvU6iRuf:-Mew0qoQ7OsJjvU6iRug:bc4aadi) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L497)):*
> ```Go
> 				continue
> 			}
> ```

Do you need a check for the !found case?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1jPv7fDKS-CeB_mt:-Mew1jPv7fDKS-CeB_mu:bdgbz8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L513)):*
> ```Go
> // parseRangeReplicas inspects a range descriptor and returns a map with its
> // leaseholder, voters, and non-voters.
> func parseRangeReplicas(
> ```

Is there a reason why this function returns a `map[int]replicaType` but the function below (parseUserReplicas) returns a `map[replicaType]int[]`? Can we decide on one and make them both return that? I think it'll make the validation function above cleaner. 

Coming back to this, after my comment in the datadriven test to move the call to this function above the if block -- maybe ma[int]replicaType is the correct representation, so `parseUserReplicas` should be the one to change? Your call though.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 526 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1ba45iukjkIh19ES:-Mew1ba45iukjkIh19ET:b9llhgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L526)):*
> ```Go
> 	for _, replica := range desc.Replicas().VoterDescriptors() {
> 		idx := nodeIdToIdx(t, tc, replica.NodeID)
> 		if _, found := replicaMap[idx]; !found {
> ```

What if the thing is found in the replicaMap? Isn't that an assertion failed? 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 556 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MevyoZg6D6k1n1aZT_c:-MevyoZg6D6k1n1aZT_d:b-o1810e) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L556)):*
> ```Go
> 		newReplicas := make([]int, 0, len(rawReplicaList))
> 		for _, rawIndex := range rawReplicaList {
> 			ind, err := strconv.Atoi(rawIndex)
> ```

Do we need a check to ensure that the index is indeed valid?
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 113 at r8](https://reviewable.io/reviews/cockroach [...]

2021-07-19 15:41 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeQveo1DcfIODAkHMn6:-MezHEdF1rjPU7UiShBC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L73)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Ack, yeah, that makes sense. I think it's worth calling out in this comment here that test writers don't need to provide deterministic constraints for all replicas, just some. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 332 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1vSj8IQGs7J8iert:-MezHMdX2ZOCmRUfY3tb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L332)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/user replica types/user supplied expected replica types/
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 353 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR1Dp5DcEq2VA6atPS:-MezJANx7y95Uobd2EKI:bpkd0ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L353)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Wait looks like we're no longer doing this "only attempt transfer lease once" -- is this comment stale then?
</blockquote></details>

It is. Thanks for the catch.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 514 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR485B1VXVrVoKMUNk:-MezNeAV7DRUXuWAVpmu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L514)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/parseUserReplicas/parseExpectedReplicasFromInput/
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 361 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew2wKEAIu_nLiFtcOc:-MezJ4IfCZoljsqtFmh5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L361)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

You could move the call to `parseRangeReplicas` above this (outside the if block, right where you're calling parseUserReplicas` to get rid of this for loop. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 443 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew12v34Z7L1KRD-9DV:-MezJODS9eGo5R518vAt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L443)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/replicaTypeNonvoter/replicaTypeNonVoter/
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 487 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew-5GcBXq7WXGna1Nk:-MezJasW2SXdAjxxVqgD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L487)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/validateReplicas/ensureCorrectReplicaPlacement/
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 497 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew0qoQ7OsJjvU6iRuf:-MezKPxYCnxAHmVvFn5t:bfnzrts) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L497)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you need a check for the !found case?
</blockquote></details>

I didn't have one because the end functionality is the same, but I'll add one so we've got a more descriptive error.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1jPv7fDKS-CeB_mt:-MezKlXRC1GBeUZbPPye:bskhzq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L513)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is there a reason why this function returns a `map[int]replicaType` but the function below (parseUserReplicas) returns a `map[replicaType]int[]`? Can we decide on one and make them both return that? I think it'll make the validation function above cleaner. 

Coming back to this, after my comment in the datadriven test to move the call to this function above the if block -- maybe ma[int]replicaType is the correct representation, so `parseUserReplicas` should be the one to change? Your call though.
</blockquote></details>

I think it actually makes things cleaner for them to have two different signatures because of how we want to interact with each map. 
For the user-inputted map of replicas, I want to know "which replicas are of type X" (`map[replica_type][]server_idx)`; this is particularly helpful when getting leaseholder info. It also makes it easy to loop over replicas of the same type.
With the map gathered from the range, though, I'm using it for validation, so my queries are of the style "what replica type is assigned to server X" (`map[server_idx]replica_type`).
The function signature definitely looks weird, but I think it makes the code more direct.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 526 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1ba45iukjkIh19ES:-MezN2e6EtRhTma_KP3F:b-mnbb54) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L526)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What if the thing is found in the replicaMap? Isn't that an assertion failed? 
</blockquote></details>

It is in the nonvoter case, but in the voter case, the leaseholder will already be in the map, so we have to not error out.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 556 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MevyoZg6D6k1n1aZT_c:-MezO9727nwzg9_lArml:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L556)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we need a check to ensure that the index is indeed valid?
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 113 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew6rwH9R9-4udFkiqA:-MezP_eL-Rp64S2UNFhx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/testdata/regional_by_table#L113)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

:100: :100: 

nit: add a nod to the fact that us-east-1 has 3 replicas and all other regions have 1 each, which is what makes replica placement predictable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-19 17:41 UTC, arulajmani reviewed
This should be ready to go once we make the intermediate representation switch, like we talked about offline. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-Mezql3A8PFfUhNOvmQN:b-rtif7p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MezqUBa-wcQ3Cf_MSDb:b-ywa8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

This is needed for the test - replicas in the same region need to be in different zones. I was getting flakes otherwise; I assume that was to do with zone survivability.
</blockquote></details>

Did we ever get to the bottom of why this was flaking? We briefly spoke about it offline, but I forget what the resolution was here. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1jPv7fDKS-CeB_mt:-Mezp2eRBAko2iFBfkgS:btx29x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L513)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I think it actually makes things cleaner for them to have two different signatures because of how we want to interact with each map. 
For the user-inputted map of replicas, I want to know "which replicas are of type X" (`map[replica_type][]server_idx)`; this is particularly helpful when getting leaseholder info. It also makes it easy to loop over replicas of the same type.
With the map gathered from the range, though, I'm using it for validation, so my queries are of the style "what replica type is assigned to server X" (`map[server_idx]replica_type`).
The function signature definitely looks weird, but I think it makes the code more direct.
</blockquote></details>

Talked offline, let's use a struct to represent the intermediate representation instead, and use that for accesses/the `ensureCorrectReplicaPlacement` method. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 366 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MezqFgO-Cgk9TgRKWTP:-MezqFgP0hejhaRdZ9NW:byazh76) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a994db0a8e183e27bc571ef0141889613f5348/pkg/ccl/multiregionccl/datadriven_test.go#L366)):*
> ```Go
> 							// We want to only initiate a lease transfer if our target replica
> 							// is a voter. Otherwise, TransferRangeLease will silently fail.
> 							if newLeaseholderType := actualReplicaTypes[nodeIdx]; newLeaseholderType != replicaTypeVoter {
> ```

What if `newLeaseholderType` is already the lease holder? Do we need to account for that as well? 
___
*[pkg/ccl/multiregionccl/testdata/regional_by_table, line 190 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MezmuanDi3yXnt_x7xj:-MezmuanDi3yXnt_x7xk:b-kvsc23) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07dbade3db133ff4cb0ab7b7c8e129bac72e6b9/pkg/ccl/multiregionccl/testdata/regional_by_table#L190)):*
> ```
> ----
> 
> # Note that we can't test voter placement in us-east-1 since 2/3 of the nodes will be replicas,
> ```

nit: nodes aren't replicas, the _have_ replicas


<!-- Sent from Reviewable.io -->

2021-07-20 18:12 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-Mf45ytu3ucVR-cv2jr3:b2qrsww) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did we ever get to the bottom of why this was flaking? We briefly spoke about it offline, but I forget what the resolution was here. 
</blockquote></details>

I didn't get to the bottom of this. I made a bunch of changes between when the flakes were happening and now, so it's hard to pinpoint exactly which changed killed the flakes. I know that the current implementation isn't flaking, but I can spend some time and try to pinpoint exactly what did it.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1jPv7fDKS-CeB_mt:-Mf45mx24emg18yOCCzC:blk02gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L513)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Talked offline, let's use a struct to represent the intermediate representation instead, and use that for accesses/the `ensureCorrectReplicaPlacement` method. 
</blockquote></details>

How does this look?
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 366 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MezqFgO-Cgk9TgRKWTP:-Mf45PSM9ED7YBO3syfl:bwbj6sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/90a994db0a8e183e27bc571ef0141889613f5348/pkg/ccl/multiregionccl/datadriven_test.go#L366)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

What if `newLeaseholderType` is already the lease holder? Do we need to account for that as well? 
</blockquote></details>

That's accounted for in line 361 (`if nodeIdx != leaseIdx`). I've changed the variable names to be more explicit about what those mean.


<!-- Sent from Reviewable.io -->

2021-07-21 02:12 UTC, arulajmani reviewed
Mostly nits about line length left now. I do have one request, in the comments, about reverting the extra locality tier and seeing how this does on stress after. As I mentioned below, I don't think it's worth holding this PR open until we get to the bottom of this, but we should identify if a problem exists or not before merging. If after the reverting your zone tier changes this runs smoothly on stress let's check this in like that. 

Thanks again for iterating on this and polishing this up -- you're leaving the code in a much better place than you found it! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-Mf5n0WY2NpMQu63SW-O:bgz98gg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-Mf5mILY-DkKgWNRWukV:b-707u43) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I didn't get to the bottom of this. I made a bunch of changes between when the flakes were happening and now, so it's hard to pinpoint exactly which changed killed the flakes. I know that the current implementation isn't flaking, but I can spend some time and try to pinpoint exactly what did it.
</blockquote></details>

If it isn't too much effort, could we revert this change back to what it was before this PR, and stress this thing? I don't want to hold this PR up any longer, so if it fails under stress without this change, let's file an issue and merge this. If it runs smoothly under stress then we can just check in the reverted code. 

I say because adding an extra locality tier does change the allocator behaviour, so we are actually changing the test. If there is an issue then we should have it filed, even if we don't get to the bottom of right now. Sorry for the trouble! 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 513 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mew1jPv7fDKS-CeB_mt:-Mf5m7_pAsIwMqULSksS:b-kahluk) ([raw file](https://github.com/cockroachdb/cockroach/blob/000eae962ecccc313d9fe773ec73508b9bd6f074/pkg/ccl/multiregionccl/datadriven_test.go#L513)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

How does this look?
</blockquote></details>

This looks great! Thanks for working through on this, this code has ended up in a much nicer place :100: 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 356 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5jUft8vh85FndD1wX:-Mf5jUft8vh85FndD1wY:bxfwu6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L356)):*
> ```Go
> 					actualPlacement := parseReplicasFromRange(t, ds.tc, desc)
> 
> 					// If the user specified a leaseholder, transfer range lease to the leaseholder.
> ```

nit: 80 chars
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 359 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5jeJO1FpEErfrWFqE:-Mf5jeJO1FpEErfrWFqF:b-o7tpi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L359)):*
> ```Go
> 					if expectedPlacement.hasLeaseholder() {
> 						expectedLeaseIdx := expectedPlacement.getLeaseholder()
> 						actualLeaseIdx := nodeIdToIdx(t, ds.tc, leaseHolderInfo.NodeID)
> ```

nit: Now that you have the struct, replacing this with`actualPlacement.getLeaseHolder` would be more readable. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 368 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5k8eR-0Cq4m4t2uiw:-Mf5k8eR-0Cq4m4t2uix:bfmemvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L368)):*
> ```Go
> 								return errors.CombineErrors(
> 									leaseErr,
> 									errors.Newf("expected node %s to be a voter but was %s", expectedLeaseIdx, newLeaseholderType.String()))
> ```

nit: there's a few lines over 100 chars here and around here that could use some formatting. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 481 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5kS9I1J6CPh33HG6-:-Mf5kS9I1J6CPh33HG60:bapptyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L481)):*
> ```Go
> }
> 
> func ensureCorrectReplicaPlacement(
> ```

I think this function is unused now that you've got the whole `replicaType` struct, so you could get rid of it. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 567 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5lhwN4Ffwvsghcr0J:-Mf5lhwN4Ffwvsghcr0K:b5tpfrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L567)):*
> ```Go
> }
> 
> // parseReplicasFromInput constructs a replicaPlacement from user input
> ```

nit: fullstop. 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 590 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5oii17UwZvvznIu0W:-Mf5oii17UwZvvznIu0X:b-imu399) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L590)):*
> ```Go
> 				t.Fatalf("could not parse replica type for index: %v", err)
> 			}
> 			if ind >= tc.NumServers() {
> ```

ind < 0 as well? 
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 618 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5lgF6BNlTRSihsa6L:-Mf5lgF6BNlTRSihsa6M:b-6v8slx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L618)):*
> ```Go
> }
> 
> // parseReplicasFromInput constructs a replicaPlacement from a range descriptor
> ```

nit: fullstop
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 682 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5lnD41cz-ZwqbO6QN:-Mf5lnD41cz-ZwqbO6QO:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L682)):*
> ```Go
> 				continue
> 			} else {
> 				return errors.Newf("expected node %s to not be present but had replica type %s", node, actualRt.String())
> ```

nit: long line
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 687 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5loR6DErH2bEpVJK4:-Mf5loR6DErH2bEpVJK5:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L687)):*
> ```Go
> 
> 		if !found {
> 			return errors.Newf("expected node %s to have replica type %s but was not found", node, expectedRt.String())
> ```

nit: long line
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 691 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5lpznCbVlRWbz8fCt:-Mf5lpznCbVlRWbz8fCu:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L691)):*
> ```Go
> 
> 		if expectedRt != actualRt {
> 			return errors.Newf("expected node %s to have replica type %s but was %s", node, expectedRt.String(), actualRt.String())
> ```

nit: long line
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 698 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5lvuDC5I8ZEGLQe-U:-Mf5lvuDC5I8ZEGLQe-V:bszdx5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/mu [...]

2021-07-21 22:25 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 368 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5k8eR-0Cq4m4t2uiw:-MfA9jFC1UlZ4OnonD0d:b-j9y9rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L368)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: there's a few lines over 100 chars here and around here that could use some formatting. 
</blockquote></details>

I've been able to shorten all lines except 358. When I split it at the semicolon, `crlfmt` makes it one long line again, and I don't think there's another place to split it that makes more sense.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 481 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5kS9I1J6CPh33HG6-:-MfA8asG1S1_gMqOt3r7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L481)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think this function is unused now that you've got the whole `replicaType` struct, so you could get rid of it. 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 590 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-Mf5oii17UwZvvznIu0W:-MfA8vY-1Wg6LI55qhjy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc31382fea1910af18b4d60ebb6344bdc740ce1c/pkg/ccl/multiregionccl/datadriven_test.go#L590)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

ind < 0 as well? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 05:51 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MfBkTu76GUi2R7JT1X4:bi59aol) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

If it isn't too much effort, could we revert this change back to what it was before this PR, and stress this thing? I don't want to hold this PR up any longer, so if it fails under stress without this change, let's file an issue and merge this. If it runs smoothly under stress then we can just check in the reverted code. 

I say because adding an extra locality tier does change the allocator behaviour, so we are actually changing the test. If there is an issue then we should have it filed, even if we don't get to the bottom of right now. Sorry for the trouble! 
</blockquote></details>

Ran stress for an hour, and there doesn't seem to be any problems with the old implementation. What do you think about not doing the zone incrementing I'm doing here but instead just constructing the zone as `{region_name}a`? It'll have the same result in our tests as the localityCfg map that was there before, but all the possible regions don't need to be explicitly mapped out. Unless we want to limit to certain regions or have custom zone info per region, I think it makes more sense to autogenerate the zone name.


<!-- Sent from Reviewable.io -->

2021-07-23 20:01 UTC, arulajmani reviewed
Could you squash both your commits into a single one? Considering your first commit never merged to master the commit message in your second doesn't make much sense. You could, if you wanted to, this PR into two commits -- one that makes the datadriven changes and switches the `global_tables` test to conform to those and a second one that adds the `regional by row` test file. That being said, that sounds like more work than is worth, so if you want to just squash both of these into a single commit and write up a message for it, this PR will be good to go. 

> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-MfJwG2X6MBismeGd733:b-e4bnun)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MfJvVVR5_tsj3E6o8aA:b86rk8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Ran stress for an hour, and there doesn't seem to be any problems with the old implementation. What do you think about not doing the zone incrementing I'm doing here but instead just constructing the zone as `{region_name}a`? It'll have the same result in our tests as the localityCfg map that was there before, but all the possible regions don't need to be explicitly mapped out. Unless we want to limit to certain regions or have custom zone info per region, I think it makes more sense to autogenerate the zone name.
</blockquote></details>

I'm fine either way, whatever is easier/you prefer, your call! You wanna make the change so that I can stamp this PR and we can get it in?


<!-- Sent from Reviewable.io -->

2021-07-26 19:18 UTC, pawalt reviewed
Sounds good; I squashed them into one commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-MfZFCvKDrf9NRNFDmiQ:b-q1l1w1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/datadriven_test.go, line 150 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-MeR0P7B8kE83Q_5TMrY:-MfZF58nD9glbH2BTun8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f283d6f8280c21720863b3a0bbfce834f4bb765/pkg/ccl/multiregionccl/datadriven_test.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I'm fine either way, whatever is easier/you prefer, your call! You wanna make the change so that I can stamp this PR and we can get it in?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 15:31 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

Thanks for persevering through this -- you've improved this framework quite a bit! :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66735#-:-MfhicbuE0tCHm44rQiL:b-h0i0au)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)



<!-- Sent from Reviewable.io -->

2021-07-28 19:48 UTC, pawalt commented
bors r=arulajmani

2021-07-28 21:11 UTC, merged