Alter default privileges 06162021
cockroachdb/cockroach pull request #66785
Opened 2021-06-23 18:45 UTC by RichardJCai

2021-06-23 18:45 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66785)
<!-- Reviewable:end -->

2021-06-30 19:48 UTC, rafiss commented
having trouble following the example from the release notes
```
Example: ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO foo
makes it such that all tables created by the user that executed the
ALTER DEFAULT PRIVILEGES command will have SELECT privilege on the table
for user foo.
```

are the privileges being granted to `foo` or to the user who ran the command?

2021-06-30 19:52 UTC, RichardJCai commented
> having trouble following the example from the release notes
> 
> ```
> Example: ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO foo
> makes it such that all tables created by the user that executed the
> ALTER DEFAULT PRIVILEGES command will have SELECT privilege on the table
> for user foo.
> ```
> 
> are the privileges being granted to `foo` or to the user who ran the command?

Yeah this concept is pretty confusing. So `ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO foo` is equivalent to `ALTER DEFAULT PRIVILEGES FOR ROLE current_user GRANT SELECT ON TABLES TO foo`.

This means any tables that `current_user` creates in the current database will have `SELECT` privilege for `foo`.
`current_user` can be thought of as the `creator` or `object_creator` and `foo` is still the grantee.

2021-07-07 18:06 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @RichardJCai)

___
*[pkg/sql/alter_default_privileges.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MdZU03t-jLD-Tf98EI3:-MdZU03t-jLD-Tf98EI4:b-fu8mau) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/alter_default_privileges.go#L60)):*
> ```Go
> 	if n.Schema != nil {
> 		return nil, unimplemented.New("ALTER DEFAULT PRIVILEGES IN SCHEMA",
> 			"not implemented")
> ```

it might be worth filing an issue for this, just so that we can track ourselves. (and use `NewWithIssue`)
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16v99D86jzlJLae9R:-Me16v99D86jzlJLae9S:bb57oos) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L97)):*
> ```Go
> 		newPrivs.Version = OwnerVersion
> 	}
> 	// TODO (richardjcai): We also have to handle the "public role" for types.
> ```

i'm wondering if we should just create issues for all the TODOs so nothing falls through the cracks? i'll defer to you though - what do you think will be the most helpful?
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me17HeG5DxIvd0xJDVI:-Me17HeHEjQB3nDMiShR:b-dojbrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L117)):*
> ```Go
> 
> // User accesses the role field.
> func (u DefaultPrivilegesForRole) User() security.SQLUsername {
> ```

nit: make the receiver a pointer
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me17R5X5sGm72jGGagZ:-Me17R5X5sGm72jGGag_:b-dojbrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L123)):*
> ```Go
> // findUser looks for a specific user in the list.
> // Returns (nil, false) if not found, or (obj, true) if found.
> func (p DefaultPrivilegeDescriptor) GetDefaultPrivilegesForRole(
> ```

nit: make the receiver a pointer
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me17Rhu7TKMHpqfO8Mw:-Me17Rhu7TKMHpqfO8Mx:b-dojbrg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L135)):*
> ```Go
> // findUserIndex looks for a given user and returns its
> // index in the User array if found. Returns -1 otherwise.
> func (p DefaultPrivilegeDescriptor) findUserIndex(user security.SQLUsername) int {
> ```

nit: make the receiver a pointer
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16IBgBe4Zb7dlIZM4:-Me16IBgBe4Zb7dlIZM5:b-4au2iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/sem/tree/alter_default_privileges.go#L53)):*
> ```Go
> // AlterDefaultPrivilegesTargetObject represents the type of object that is
> // having it's default privileges altered.
> type AlterDefaultPrivilegesTargetObject int
> ```

could this be a uint32 so that we avoid the need for a `ToUint32` method? (or is it more clear with the method either way?)
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16T3l9GSw1HtWCbwe:-Me16T3l9GSw1HtWCbwf:bcolsw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/sem/tree/alter_default_privileges.go#L56)):*
> ```Go
> 
> const (
> 	Tables    AlterDefaultPrivilegesTargetObject = 1
> ```

if we need the explicit number assigning, it is worth adding a comment explaining why

if we don't need it, then we can use `iota` here


<!-- Sent from Reviewable.io -->

2021-07-08 19:19 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @rafiss)

___
*[pkg/sql/alter_default_privileges.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MdZU03t-jLD-Tf98EI3:-Me6Yiih2ie6ehO1IaQr:bb74yfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/alter_default_privileges.go#L60)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it might be worth filing an issue for this, just so that we can track ourselves. (and use `NewWithIssue`)
</blockquote></details>

Done. Opened https://github.com/cockroachdb/cockroach/issues/67376
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16v99D86jzlJLae9R:-Me6YldUBZ3Yi3eB53l7:b-2q8cdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L97)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm wondering if we should just create issues for all the TODOs so nothing falls through the cracks? i'll defer to you though - what do you think will be the most helpful?
</blockquote></details>

Created a couple of TODOs:
https://github.com/cockroachdb/cockroach/issues/67376
https://github.com/cockroachdb/cockroach/issues/67377
https://github.com/cockroachdb/cockroach/issues/67378
https://github.com/cockroachdb/cockroach/issues/67381
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16IBgBe4Zb7dlIZM4:-Me6YtDBCenkoPJ28Rjq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/sem/tree/alter_default_privileges.go#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could this be a uint32 so that we avoid the need for a `ToUint32` method? (or is it more clear with the method either way?)
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 56 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16T3l9GSw1HtWCbwe:-Me6Ytg-C87KV5PKwzHQ:bfraoy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/sem/tree/alter_default_privileges.go#L56)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if we need the explicit number assigning, it is worth adding a comment explaining why

if we don't need it, then we can use `iota` here
</blockquote></details>

It's written to disk so we should keep it as explicitly definied.


<!-- Sent from Reviewable.io -->

2021-07-09 05:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @RichardJCai)

___
*[pkg/sql/catalog/descpb/default_privilege.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me16v99D86jzlJLae9R:-Me8hx-70I3s8J1ZA_sX:bd5l6mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5583c0203b1d238993a627ae8afaa49cf8332360/pkg/sql/catalog/descpb/default_privilege.go#L97)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Created a couple of TODOs:
https://github.com/cockroachdb/cockroach/issues/67376
https://github.com/cockroachdb/cockroach/issues/67377
https://github.com/cockroachdb/cockroach/issues/67378
https://github.com/cockroachdb/cockroach/issues/67381
</blockquote></details>

thanks!
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 178 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8iJmoEPJRlP2AgTKx:-Me8iJmoEPJRlP2AgTKy:b-2aejm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/default_privilege.go#L178)):*
> ```Go
> 
> // Validate returns an assertion error if the default privilege descriptor is invalid.
> func (p DefaultPrivilegeDescriptor) Validate() error {
> ```

nit: make this receiver a pointer
___
*[pkg/sql/catalog/descpb/privilege.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8iMlB2Zq7-Ed1Q5dm:-Me8iMlB2Zq7-Ed1Q5dn:bpq7p87) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/privilege.go#L403)):*
> ```Go
> // found to have invalid privileges and the bits representing the invalid
> // privileges.
> func (p PrivilegeDescriptor) IsValidPrivilegesForObjectType(
> ```

hm, i noticed this one isn't a pointer too, but it looks like all the validation functions don't take pointer receivers. i wonder why
___
*[pkg/sql/catalog/descpb/privilege.proto, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8g_aH2iVaud9IBr_0:-Me8g_aH2iVaud9IBr_1:bexugds) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/privilege.proto#L53)):*
> ```protobuf
>   optional string user_proto = 1 [(gogoproto.nullable) = false,
>     (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/security.SQLUsernameProto"];
>   map<uint32, PrivilegeDescriptor> default_privileges_per_object = 2 [(gogoproto.nullable) = false];
> ```

i think you can do something like

```
map<uint32, PrivilegeDescriptor> default_privileges_per_object = 2 [(gogoproto.nullable) = false,
(gogoproto.castkey) = "github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AlterDefaultPrivilegesTargetObject"];
```

and this way we can also avoid having to do the `uint32(...)` conversions.

(but actually if we use castkey, i'm not sure if the `AlterDefaultPrivilegesTargetObject` type needs to be moved somewhere else)


<!-- Sent from Reviewable.io -->

2021-07-09 05:29 UTC, rafiss reviewed
Looks good! thanks for making those issues. I also made one more for WITH GRANT OPTION: https://github.com/cockroachdb/cockroach/issues/67410

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-Me8jMGs0brO46RSaG3G:b39z7f4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-07-09 19:33 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @rafiss)

___
*[pkg/sql/catalog/descpb/default_privilege.go, line 178 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8iJmoEPJRlP2AgTKx:-MeBjRYa0-EXQ58zgSIW:bdsmbw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/default_privilege.go#L178)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: make this receiver a pointer
</blockquote></details>

I think it does make sense to make this a pointer, not sure why the other validates aren't pointers.
___
*[pkg/sql/catalog/descpb/privilege.go, line 403 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8iMlB2Zq7-Ed1Q5dm:-MeBjWRqBN9htscZWBf6:b-7dxuaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/privilege.go#L403)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, i noticed this one isn't a pointer too, but it looks like all the validation functions don't take pointer receivers. i wonder why
</blockquote></details>

I think it was likely just an oversight looking at the git history.
I'll make a separate PR to change it.
___
*[pkg/sql/catalog/descpb/privilege.proto, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8g_aH2iVaud9IBr_0:-MeBkXaZ7blFk79ZzKxr:b-ovu20q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/privilege.proto#L53)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think you can do something like

```
map<uint32, PrivilegeDescriptor> default_privileges_per_object = 2 [(gogoproto.nullable) = false,
(gogoproto.castkey) = "github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AlterDefaultPrivilegesTargetObject"];
```

and this way we can also avoid having to do the `uint32(...)` conversions.

(but actually if we use castkey, i'm not sure if the `AlterDefaultPrivilegesTargetObject` type needs to be moved somewhere else)
</blockquote></details>

Wow nice I didn't know that. Wasn't sure how to make cast work with keys.


<!-- Sent from Reviewable.io -->

2021-07-15 03:01 UTC, arulajmani reviewed
I still have a few files from the last commit left to review, but I'm stepping away for today. Publishing my intermediate comments in the meantime. 

> Reviewed 7 of 9 files at r1, 23 of 23 files at r3, 14 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-Mec5VzB3SkH4TTHA8_n:bu6ywum)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_job.go, line 2397 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebsHzp1y1wqyHKK3oP:-MebsHzp1y1wqyHKK3oQ:b-4it6tg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/ccl/backupccl/restore_job.go#L2397)):*
> ```Go
> 			}
> 
> 			// Default is to copy privs from restoring parent db, like CREATE {TABLE,
> ```

nit: this could use a reword
___
*[pkg/sql/alter_default_privileges.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebyeuT6JPvqArMae7Q:-MebyeuT6JPvqArMae7R:b-cg0c7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L39)):*
> ```Go
> 	// Only one of dbDesc or schemaDesc should be populated.
> 	dbDesc     *dbdesc.Mutable
> 	schemaDesc *schemadesc.Mutable
> ```

Should this be schemaDescs? 

Separately, this looks unused right now -- consider removing it and introducing the field in the commit that addresses #67376. 
___
*[pkg/sql/alter_default_privileges.go, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebzwXG9KZYVY2X-q3l:-MebzwXG9KZYVY2X-q3m:bpwy6mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L83)):*
> ```Go
> 	}
> 
> 	for _, targetRole := range targetRoles {
> ```

Could we lift this logic that ensures a list of roles exists into a function?  That way we don't have to duplicate this stuff here and below (for grantees)
___
*[pkg/sql/alter_default_privileges.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec1AzD2uEMvkz47CJk:-Mec1AzEDvo0XLuMpRcm:bsc4r5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L155)):*
> ```Go
> 	}
> 
> 	if err := params.p.createNonDropDatabaseChangeJob(params.ctx, n.dbDesc.ID,
> ```

Do you need this after the call above to `writeNonDropDatabaseChange`? 
___
*[pkg/sql/alter_default_privileges.go, line 159 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec1PdECukXuFKmYmVg:-Mec1PdECukXuFKmYmVh:bp2a3y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L159)):*
> ```Go
> 		return err
> 	}
> 	return nil
> ```

nit: you can get rid of the if err := block above and simply return the result of the function 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-Mec3KNpDim9jbw34z_J:b-gspwbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
> ```Go
> 	if desc.DefaultPrivileges == nil {
> 		defaultPrivileges := descpb.DefaultPrivilegeDescriptor{}
> 		desc.DefaultPrivileges = &defaultPrivileges
> ```

it feels weird to me that an accessor on an Immutable database descriptor is modifying the underlying proto. Is there a the database descriptor proto stores a pointer to a DefaultPrivilegeDescriptor? Could we get around this by making the field not-nullable?


<!-- Sent from Reviewable.io -->

2021-07-16 17:10 UTC, arulajmani reviewed
Publishing comments for the parts I didn't get to earlier. 

> Reviewed 9 of 29 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-MekHtCA3YAEYvZMDnr_:b-7gss5i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-MekCvSk-5mj7xaPONc7:b63jrbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
> ```Go
> 	// TODO (richardjcai): We also have to handle the "public role" for types.
> 	//   "Public" has USAGE by default but it can be revoked.
> 	//    We need to use a Version field to determine what a missing Public role
> ```

Looks like we already handle this "public role" getting USAGE privilege in `inheritUsagePrivilegeFromSchema` -- can we move that code in here as part of this PR? 

Looks like this USAGE thing only applies to types being created inside the `public` schema. Your comment seems to imply that we want it for all schemas, user defined and public. Did we get the semantics wrong earlier?  

Separately, could you say more about what you mean by needing a version entry?
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Meju_23DVNlQZQhTFtF:-Meju_23DVNlQZQhTFtG:b-8qxd4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L155)):*
> ```Go
> 		return !p.DefaultPrivileges[i].User().LessThan(user)
> 	})
> 	if idx == len(p.DefaultPrivileges) {
> ```

nit: Could you add a comment saying that if a new user is to be created it must be done while preserving the sorted order?
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MejtVvtC9Ewu9p61mQn:-MejtVvtC9Ewu9p61mQo:b-j6iblv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L177)):*
> ```Go
> }
> 
> // Validate returns an assertion error if the default privilege descriptor is invalid.
> ```

nit: wrap comment to 80 chars
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Meju9Ne71X8nJW3niw0:-Meju9Ne71X8nJW3niw1:btoaamh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L188)):*
> ```Go
> 			}
> 		}
> 	}
> ```

Should we validate that `DefaultPrivileges` is in sorted order as well? 
___
*[pkg/sql/catalog/descpb/privilege.proto, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mek-E-mEJvupgsOIu_N:-Mek-E-mEJvupgsOIu_O:b544o3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/privilege.proto#L60)):*
> ```protobuf
> // DefaultPrivilegeDescriptor describes the set of default privileges for a
> // given role + object type.
> // The default_privileges list must be sorted for fast access and user lookups.
> ```

s/default_privileges list/DefaultPrivilegesList/g
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mek5pVW1UjO8GAZALL7:-Mek5pVW1UjO8GAZALL8:b-a5yilm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema#L71)):*
> ```
> d              s4           admin     ALL
> d              s4           root      ALL
> d              s4           testuser  CREATE
> ```

Capturing our discussion offline, there's a CREATE here because this follows from our old "inheritance" model. This will go away soon, but we've got a test here because this PR hasn't introduced that backwards incompatible change. It'd be worth capturing this in a comment.

Speaking of comments, I think it might be worth sprinkling a few more throughout the logic tests. Imo this privileges stuff is tricky, and a bit more commenting in logic tests would help if we've to ever revisit this code. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekBngEE4iDIugWPUxT:-MekBngEE4iDIugWPUxU:b-xtzj0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema#L78)):*
> ```
> 
> statement ok
> GRANT testuser TO root
> ```

To confirm, you need to do this so that root can alter the default privileges for testuser?
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_sequence, line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mek85hnEgQYVFg3jRbS:-Mek85hnEgQYVFg3jRbT:b-86qtd8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_sequence#L93)):*
> ```
> d              public       s4          admin     ALL
> d              public       s4          root      ALL
> d              public       s4          testuser  CREATE
> ```

Similar to the comment in the schema file, this could use a comment as well. 
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_type, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekGvVS2SGM8DoAPOX9:-MekGvVS2SGM8DoAPOXA:bkqsrwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_type#L73)):*
> ```
> d              public       t4         public    USAGE
> d              public       t4         root      ALL
> d              public       t4         testuser  ALL
> ```

Why does testuser get ALL over here? 
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_type, line 99 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekH7Tk22Ocktm9y5ou:-MekH7Tl4OBlPQk9uxgS:b-z46h7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_type#L99)):*
> ```
> d              public       t5         public    USAGE
> d              public       t5         root      ALL
> d              public       t5         testuser  ALL
> ```

Same question as above
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekHgj11rlA68ntX-l1:-MekHgj11rlA68ntX-l2:b-ciom1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/sem/tree/alter_default_privileges.go#L103)):*
> ```Go
> 	Grantees       NameList
> 	GrantOptionFor bool
> 	Drop           DropBehavior
> ```

Unused?


<!-- Sent from Reviewable.io -->

2021-07-19 16:38 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @dt, and @rafiss)

___
*[pkg/ccl/backupccl/restore_job.go, line 2397 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebsHzp1y1wqyHKK3oP:-Mekgqw1BohUklX_TkAr:bhnemiz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/ccl/backupccl/restore_job.go#L2397)):*
> ```
> Default is to copy privs from restoring parent db, like CREATE
> ```

Yeah this comment isn't applicable anymore. I've removed it. Left the TODO though, not sure if that's applicable or not. cc @dt 
___
*[pkg/sql/alter_default_privileges.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebyeuT6JPvqArMae7Q:-Mekh15TARb59ODb-5Gu:brdjlr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L39)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be schemaDescs? 

Separately, this looks unused right now -- consider removing it and introducing the field in the commit that addresses #67376. 
</blockquote></details>

Yes this is unused at the time, will remove entirely for now.
___
*[pkg/sql/alter_default_privileges.go, line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MebzwXG9KZYVY2X-q3l:-MekipUj9bENd61mJAjh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L83)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we lift this logic that ensures a list of roles exists into a function?  That way we don't have to duplicate this stuff here and below (for grantees)
</blockquote></details>

Done.
___
*[pkg/sql/alter_default_privileges.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec1AzD2uEMvkz47CJk:-Mekiy1b1oVgzSzJJDRz:bf65j4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/alter_default_privileges.go#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you need this after the call above to `writeNonDropDatabaseChange`? 
</blockquote></details>

Nope, seems redundant
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-MekmZh47dTc5Dpj_GWL:b6bpd73) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

it feels weird to me that an accessor on an Immutable database descriptor is modifying the underlying proto. Is there a the database descriptor proto stores a pointer to a DefaultPrivilegeDescriptor? Could we get around this by making the field not-nullable?
</blockquote></details>

This is totally unnecessary, I don't think we have to make the field not-nullable however (would be weird to anyway since we have descriptors in the past where it should be null)
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-MezKMg5ABtlQNLC9__n:bt6w588) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
> Looks like we already handle this "public role" getting USAGE privilege in inheritUsagePrivilegeFromSchema -- can we move that code in here as part of this PR?

That is slightly different and not directly applicable here. Although I don't think this is the right place to write this TODO. I don't think we need this TODO but the issue here is that the Public role should have USAGE set in the default privileges, right now descriptors are created with no entries whereas public should always have an entry with usage. There's some more nuance to it so I'd still rather tackle this in a separate PR. 

The tricky part is how do we determine if the USAGE privilege is set or not. Default privileges are defined for all roles (creator) with the set of privileges users get if the creator creates an object.

My plan is to consider Public missing from the DefaultPrivilegePerRole list entirely as "default" ie, we'd copy USAGE down. If public is in the list, then we'll treat it normally. 
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Meju_23DVNlQZQhTFtF:-MezVYXl25rQaN6V5jCF:bx13bhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L155)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Could you add a comment saying that if a new user is to be created it must be done while preserving the sorted order?
</blockquote></details>

Added it to function header
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 188 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Meju9Ne71X8nJW3niw0:-Mezayrg6AeX2aBK46JV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L188)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we validate that `DefaultPrivileges` is in sorted order as well? 
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/privilege.proto, line 60 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mek-E-mEJvupgsOIu_N:-MezW7r27WDh3pPF3TlS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/privilege.proto#L60)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/default_privileges list/DefaultPrivilegesList/g
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mek5pVW1UjO8GAZALL7:-MekcOML7MPC5kMwh1Lj:b-imuiz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema#L71)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Capturing our discussion offline, there's a CREATE here because this follows from our old "inheritance" model. This will go away soon, but we've got a test here because this PR hasn't introduced that backwards incompatible change. It'd be worth capturing this in a comment.

Speaking of comments, I think it might be worth sprinkling a few more throughout the logic tests. Imo this privileges stuff is tricky, and a bit more commenting in logic tests would help if we've to ever revisit this code. 
</blockquote></details>

Good call, added comment
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema, line 78 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekBngEE4iDIugWPUxT:-MekdzEb0CNdA1NNNUTx:b-t2vq16) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_schema#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

To confirm, you need to do this so that root can alter the default privileges for testuser?
</blockquote></details>

Yep thats correct, added comment
___
*[pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_ [...]

2021-07-20 02:18 UTC, arulajmani requested changes
Thanks for sprinkling a bit more commentary on the logic tests, it made revisiting them a breeze! :100: 

This thing is mostly there for me, especially once you remove the raw proto accesses and replace them with interface methods/setters. 

> Reviewed 3 of 29 files at r4, 30 of 30 files at r7, 11 of 29 files at r8, 14 of 19 files at r9, 9 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-Mf0gwnF9PoeZnojtKiC:b-gwei7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_default_privileges.go, line 125 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0bTxD5ZW1u_IOL1-J:-Mf0bTxD5ZW1u_IOL1-K:bhv98c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L125)):*
> ```Go
> 	}
> 
> 	if n.dbDesc.DatabaseDesc().GetDefaultPrivileges() == nil {
> ```

With the new catalog interfaces, I think the aim is to avoid accessing methods on the raw proto directly. We should add a `GetDefaultPrivileges` method on the `DatabaseDescriptor` interface and have immutable implement it. That way the raw proto access is limited to just that implementation. 

I noticed theres a few places where this PR is following the `dbDesc.DatabaseDesc().DefaultPrivileges()` pattern -- might be worth cleaning those up as well!
___
*[pkg/sql/alter_default_privileges.go, line 126 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0bDN27eOP2tYhPCYy:-Mf0bDN27eOP2tYhPCYz:bk91z4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L126)):*
> ```Go
> 
> 	if n.dbDesc.DatabaseDesc().GetDefaultPrivileges() == nil {
> 		n.dbDesc.DatabaseDesc().DefaultPrivileges = descpb.InitDefaultPrivilegeDescriptor()
> ```

Instead of directly modifying the underlying proto directly here, we should make a setter method on `dbdesc.Mutable` and use that instead. 
___
*[pkg/sql/grant_revoke.go, line 328 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0Xfr383DArUUn-o9t:-Mf0Xfr383DArUUn-o9u:bhm55yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/grant_revoke.go#L328)):*
> ```Go
> 
> // validateGrantees checks that all the grantees are valid users.
> // users should be returned the result of GetAllRoles.
> ```

Can we change the function signature to:

```
func (p *planner) validateGrantees(ctx context.Context, grantees []security.SQLUsername) error
```

Then, this function can make its own call to `GetAllRoles` instead of relying on callers to pass in the output correctly? 

You might need to handle some ugly special casing for the "public" role from one of the call sites. 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-Mf0_xc00h3CQff2BEQL:bj95izp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
>  (would be weird to anyway since we have descriptors in the past where it should be null)

Maybe I was reading it wrong, but I thought you were treating a null default privilege descriptor as an empty privilege descriptor. So making it non-nullable would've achieved the same behaviour, right? 

Regardless, considering we don't need this function anymore, this discussion is kinda moot! 
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-Mf0fuLVAy1XaxvL8aWB:b8z7vds) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

> Looks like we already handle this "public role" getting USAGE privilege in inheritUsagePrivilegeFromSchema -- can we move that code in here as part of this PR?

That is slightly different and not directly applicable here. Although I don't think this is the right place to write this TODO. I don't think we need this TODO but the issue here is that the Public role should have USAGE set in the default privileges, right now descriptors are created with no entries whereas public should always have an entry with usage. There's some more nuance to it so I'd still rather tackle this in a separate PR. 

The tricky part is how do we determine if the USAGE privilege is set or not. Default privileges are defined for all roles (creator) with the set of privileges users get if the creator creates an object.

My plan is to consider Public missing from the DefaultPrivilegePerRole list entirely as "default" ie, we'd copy USAGE down. If public is in the list, then we'll treat it normally. 
</blockquote></details>

I don't think I fully understand what's going on here, but I'll follow it up with you offline. 


<!-- Sent from Reviewable.io -->

2021-07-20 02:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_default_privileges.go, line 95 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0hKJY9ZlR4LzYX9vw:-Mf0hKJY9ZlR4LzYX9vx:b-to9q03) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L95)):*
> ```Go
> 	granteesSQLUsername := make([]security.SQLUsername, len(grantees))
> 	for i, grantee := range grantees {
> 		granteesSQLUsername[i] = security.MakeSQLUsernameFromPreNormalizedString(string(grantee))
> ```

this string isn't actually pre-normalized (as far as I can tell); it should be turned into a username with `security.MakeSQLUsernameFromUserInput(string(grantee), security.UsernameValidation)`  -- see https://github.com/cockroachdb/cockroach/issues/65556 (and also the PR that fixes it)
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 20 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0iTLl34bs1Vz6puAc:-Mf0iTLl34bs1Vz6puAd:bvfqz0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74e9255fb0cf728d628a1b2436f1c618c457370/pkg/sql/sem/tree/alter_default_privileges.go#L20)):*
> ```Go
> // AlterDefaultPrivileges represents an ALTER DEFAULT PRIVILEGES statement.
> type AlterDefaultPrivileges struct {
> 	Roles []security.SQLUsername
> ```

how is this already a `[]SQLUsername`? it seems like it should be a `NameList` and converted into a username later with `security.MakeSQLUsernameFromUserInput(r, security.UsernameValidation)`. (changing would require updating sql.y too)

you should be able to confirm by writing a logic test where the roles are mixed-case, like the test in https://github.com/cockroachdb/cockroach/pull/67625/


<!-- Sent from Reviewable.io -->

2021-07-20 15:29 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 20 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0iTLl34bs1Vz6puAc:-Mf3WnlPCaMS01H8zNfV:b-yty4rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74e9255fb0cf728d628a1b2436f1c618c457370/pkg/sql/sem/tree/alter_default_privileges.go#L20)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how is this already a `[]SQLUsername`? it seems like it should be a `NameList` and converted into a username later with `security.MakeSQLUsernameFromUserInput(r, security.UsernameValidation)`. (changing would require updating sql.y too)

you should be able to confirm by writing a logic test where the roles are mixed-case, like the test in https://github.com/cockroachdb/cockroach/pull/67625/
</blockquote></details>

I was relying on `role_spec_list` which returns a []SQLUsername, seems like this might be buggy though. 2 other states, `DROP OWNED BY` and `REASSIGNED OWNED BY` also currently rely on this.

We should look into fixing this, I'll file a separate issue.


<!-- Sent from Reviewable.io -->

2021-07-20 15:47 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/catalog/descpb/privilege.proto, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Me8g_aH2iVaud9IBr_0:-Mf3aUbl5RXNZyEJNFqf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0dfd9d61ef3a0690d8ce0c21194dd6a142a6d8c/pkg/sql/catalog/descpb/privilege.proto#L53)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Wow nice I didn't know that. Wasn't sure how to make cast work with keys.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/alter_default_privileges.go, line 20 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0iTLl34bs1Vz6puAc:-Mf3aSUs3bikfp8Y0P1g:bqqzdk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74e9255fb0cf728d628a1b2436f1c618c457370/pkg/sql/sem/tree/alter_default_privileges.go#L20)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I was relying on `role_spec_list` which returns a []SQLUsername, seems like this might be buggy though. 2 other states, `DROP OWNED BY` and `REASSIGNED OWNED BY` also currently rely on this.

We should look into fixing this, I'll file a separate issue.
</blockquote></details>

Fixed it by using namelist for now.


<!-- Sent from Reviewable.io -->

2021-07-20 16:12 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, and @rafiss)

___
*[pkg/sql/alter_default_privileges.go, line 95 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0hKJY9ZlR4LzYX9vw:-Mf3aYg26jke7U1qh0ic:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L95)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this string isn't actually pre-normalized (as far as I can tell); it should be turned into a username with `security.MakeSQLUsernameFromUserInput(string(grantee), security.UsernameValidation)`  -- see https://github.com/cockroachdb/cockroach/issues/65556 (and also the PR that fixes it)
</blockquote></details>

Done.
___
*[pkg/sql/alter_default_privileges.go, line 125 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0bTxD5ZW1u_IOL1-J:-Mf3aa2D-SSNm5L54HEi:b-9u02ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L125)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

With the new catalog interfaces, I think the aim is to avoid accessing methods on the raw proto directly. We should add a `GetDefaultPrivileges` method on the `DatabaseDescriptor` interface and have immutable implement it. That way the raw proto access is limited to just that implementation. 

I noticed theres a few places where this PR is following the `dbDesc.DatabaseDesc().DefaultPrivileges()` pattern -- might be worth cleaning those up as well!
</blockquote></details>

Added the function definition to the interface, turns out you don't have to implement it actually, it's considered implemented in `structured.pb.go`
___
*[pkg/sql/alter_default_privileges.go, line 126 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0bDN27eOP2tYhPCYy:-Mf3bSFq4tXtL0GjpKGg:bl158xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/alter_default_privileges.go#L126)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of directly modifying the underlying proto directly here, we should make a setter method on `dbdesc.Mutable` and use that instead. 
</blockquote></details>

Done. Added `SetInitialDefaultPrivilegeDescriptor` on `dbdesc.Mutable`
___
*[pkg/sql/grant_revoke.go, line 328 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf0Xfr383DArUUn-o9t:-Mf3bceT8mOt5e4JYBVT:bpaldin) ([raw file](https://github.com/cockroachdb/cockroach/blob/58933c5becc5425af0703e7926a8e71e3a4fa163/pkg/sql/grant_revoke.go#L328)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we change the function signature to:

```
func (p *planner) validateGrantees(ctx context.Context, grantees []security.SQLUsername) error
```

Then, this function can make its own call to `GetAllRoles` instead of relying on callers to pass in the output correctly? 

You might need to handle some ugly special casing for the "public" role from one of the call sites. 
</blockquote></details>

Changed it to 
````
// validateRoles checks that all the roles are valid users.
// isPublicValid determines whether or not Public is a valid role.
func (p *planner) validateRoles(
	ctx context.Context, roles []security.SQLUsername, isPublicValid bool,
) error {```
```

___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-Mf3d8jL00cxWvyF2Kaq:b6v8lu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
>Maybe I was reading it wrong, but I thought you were treating a null default privilege descriptor as an empty privilege descriptor. So making it non-nullable would've achieved the same behaviour, right?

Actually I'm unsure about one thing, if we set the field to non-nullable, what happens to DatabaseDescriptors created before this version, if we injected an older descriptor would it populate the field?
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-Mf3dR6mDYP7k2hgqJyb:b-by472x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think I fully understand what's going on here, but I'll follow it up with you offline. 
</blockquote></details>

The TLDR version is that the `Public` role has USAGE by default on types when they are created.
The tricky part in handling is that we don't want to create an entry in the DefaultPrivilegesPerRole map such that each Role in CRDB has an entry in the map that is just `Public`: `USAGE ON TYPES`

It's easier and more efficient to handle the absence of this entry as meaningful.


<!-- Sent from Reviewable.io -->

2021-07-21 01:38 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 14 of 16 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-Mf5h_2q0fERDUmfDHqj:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/alter_default_privileges.go, line 94 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5dGxxDHazJW4YjNGH:-Mf5dGxxDHazJW4YjNGI:b-k4f8k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/alter_default_privileges.go#L94)):*
> ```Go
> 	}
> 
> 	granteesSQLUsername := make([]security.SQLUsername, len(grantees))
> ```

nit: s/granteesSQLUsername/granteeSQLUsernames/g
___
*[pkg/sql/alter_default_privileges.go, line 131 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5ez5m-wXJYRIQmb09:-Mf5ez5m-wXJYRIQmb0A:bfmfqsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/alter_default_privileges.go#L131)):*
> ```Go
> 
> 	if n.dbDesc.GetDefaultPrivileges() == nil {
> 		n.dbDesc.SetInitialDefaultPrivilegeDescriptor(descpb.InitDefaultPrivilegeDescriptor())
> ```

nit: If this method is called `SetInitialDefaultPrivilegeDescriptor`, maybe it could take no arguments and make the call to `descpb.InitDefaultPrivilegeDescriptor()` in the function body instead? Alternatively, you could rename this to `SetDefaultPrivilegeDescriptor` instead. 
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-Mf5fvdNEqnmPXMSi__p:bu6n4ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

>Maybe I was reading it wrong, but I thought you were treating a null default privilege descriptor as an empty privilege descriptor. So making it non-nullable would've achieved the same behaviour, right?

Actually I'm unsure about one thing, if we set the field to non-nullable, what happens to DatabaseDescriptors created before this version, if we injected an older descriptor would it populate the field?
</blockquote></details>

Yeah, I think it gets populated to the "0" value, which would be an empty struct in this case?
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 414 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5g47p82qSAdJwLTnM:-Mf5g47p82qSAdJwLTnN:bxfwu6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/catalog/dbdesc/database_desc.go#L414)):*
> ```Go
> }
> 
> // SetInitialDefaultPrivilegeDescriptor sets the initial default privilege descriptor
> ```

nit: 80 chars
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-Mf5g7C06RQvocGWVZ5q:b-p3mpnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

The TLDR version is that the `Public` role has USAGE by default on types when they are created.
The tricky part in handling is that we don't want to create an entry in the DefaultPrivilegesPerRole map such that each Role in CRDB has an entry in the map that is just `Public`: `USAGE ON TYPES`

It's easier and more efficient to handle the absence of this entry as meaningful.
</blockquote></details>

Talked offline, your proposal sounds good to me, thanks for taking the time to explain!  
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 73 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5hP7u9ZdRfih2X0YG:-Mf5hP7u9ZdRfih2X0YH:b-cj76fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/catalog/descpb/default_privilege.go#L73)):*
> ```Go
> // the specified object with the corresponding default privileges and
> // the appropriate owner (node for system, the restoring user otherwise.)
> func CreatePrivilegesFromDefaultPrivileges(
> ```

nit: any reason this is a function instead of a method? 


<!-- Sent from Reviewable.io -->

2021-07-21 14:36 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, @arulajmani, and @rafiss)

___
*[pkg/sql/alter_default_privileges.go, line 131 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5ez5m-wXJYRIQmb09:-Mf8UHwb6Xm_cEPSfMzw:b-7a0jr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/alter_default_privileges.go#L131)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: If this method is called `SetInitialDefaultPrivilegeDescriptor`, maybe it could take no arguments and make the call to `descpb.InitDefaultPrivilegeDescriptor()` in the function body instead? Alternatively, you could rename this to `SetDefaultPrivilegeDescriptor` instead. 
</blockquote></details>

Changed it to `SetDefaultPrivilegeDescriptor`
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 346 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mec3KNpDim9jbw34z_I:-Mf8U2Fm26TLQRSQmIwU:btn5jp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/dbdesc/database_desc.go#L346)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Yeah, I think it gets populated to the "0" value, which would be an empty struct in this case?
</blockquote></details>

Gotcha
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 100 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-MekCvSk-5mj7xaPONc6:-Mf8U4cc2AJtpp992w14:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c93d108cffdd9ee1cb852bbcd1ef8d87cd8d90b1/pkg/sql/catalog/descpb/default_privilege.go#L100)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Talked offline, your proposal sounds good to me, thanks for taking the time to explain!  
</blockquote></details>

Done.
___
*[pkg/sql/catalog/descpb/default_privilege.go, line 73 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-Mf5hP7u9ZdRfih2X0YG:-Mf8UVq29JGBhZZtPLkm:b-wrfyua) ([raw file](https://github.com/cockroachdb/cockroach/blob/175b1e6f7435b378c6dcc81b75ef2d111a4793a3/pkg/sql/catalog/descpb/default_privilege.go#L73)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: any reason this is a function instead of a method? 
</blockquote></details>

This is a function because it's possible for the `DefaultPrivilegeDescriptor` to be nil.


<!-- Sent from Reviewable.io -->

2021-07-21 14:40 UTC, rafiss approved these changes
exciting!

> Reviewed 3 of 9 files at r1, 9 of 29 files at r8, 5 of 19 files at r9, 5 of 9 files at r10, 14 of 16 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66785#-:-Mf8Vf021PkMELIeo0pr:bby1cd1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @ajwerner, @arulajmani, and @rafiss)



<!-- Sent from Reviewable.io -->

2021-07-21 15:59 UTC, RichardJCai commented
Thanks for the reviews!
bors r+

2021-07-21 20:29 UTC, merged