changefeedccl: support interval columns in avro changefeeds
cockroachdb/cockroach pull request #66800
Opened 2021-06-23 21:22 UTC by HonoreDB

We'd delayed implementing interval types in avro, unlike other
time types, because in theory there's an avro spec for durations
but no tooling. However the spec is a bit too limiting, so rather
than wait for tooling, we're just going to encode it as a string,
using the ISO standard for durations.

Adding in @otan since I'm touching the duration util package, and to check my assumption that it makes sense to keep truncating to the microsecond level.

Release note (bug fix): Interval columns are supported in avro changefeeds

2021-06-23 21:22 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66800)
<!-- Reviewable:end -->

2021-06-24 09:26 UTC, stevendanna approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66800)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @otan)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-McxKb-n9yy6_Mz1Eso4:-McxKb-n9yy6_Mz1Eso5:bppbw8u) (no related file):*
Overall this looks good to me.  I left a couple of comments regarding some potential additional tests and points we may want to document.

---
___
*[pkg/util/duration/duration_test.go, line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-Mcx4xwjDeRo1LnWb_hU:-Mcx4xwjDeRo1LnWb_hV:bui2a2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5457a7b3e47317dd5667cd6cb072e2577b78eee3/pkg/util/duration/duration_test.go#L605)):*
> ```
> P-1Y-1MT1.2S
> ```

I don't think you have another choice here because, like PostgreSQL, we allow INTERVALs where different components have different signs. 

But, our handling of negative values might be something to add to the documentation since the ISO8601 standard doesn't seem to mention how they should be handled and various libraries seem to differ on whether they can handle this. I did a quick survey of the libraries I found when I searched for "iso 8601 duration LANG" and didn't find much agreement:

Ruby's ActiveSupport parses negative components:

```
irb(main):001:0> require 'active_support/duration'
=> true
irb(main):002:0> ActiveSupport::Duration.parse('P-1Y-1MT1.2S');
=> -1 years, -1 months, and 1.2 seconds
```

Python's isodate package doesn't:

```
>>> import isodate
>>> isodate.parse_duration('P-1Y-1MT1.2S')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/isodate/isoduration.py", line 91, in parse_duration
    durdt = parse_datetime(datestring[1:])
  File "/usr/local/lib/python3.9/site-packages/isodate/isodatetime.py", line 55, in parse_datetime
    tmpdate = parse_date(datestring)
  File "/usr/local/lib/python3.9/site-packages/isodate/isodates.py", line 203, in parse_date
    raise ISO8601Error('Unrecognised ISO 8601 date format: %r' % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '-1Y-1M'
```

Perl's DateTime::Format package doesn't:

```
> cat test.pl 
use DateTime::Format::Duration::ISO8601;
my $format = DateTime::Format::Duration::ISO8601->new;
my $d = $format->parse_duration('P-1Y-1MT1.2S');
say $d
> perl -I/Users/ssd/perl5/lib/perl5/ ./test.pl 
"P-1Y-1MT1.2S": not a valid ISO 8601 duration string at /Users/ssd/perl5/lib/perl5/DateTime/Format/Duration/ISO8601.pm line 15.
```


Rust's iso8601 doesn't:

```
> cat src/main.rs 
use iso8601;

fn main() {
    let duration = iso8601::duration("P-1Y-1MT1.2S");
    match duration {
        Err(err) => println!("parse failed: {:?}", err),
        Ok(dur) => println!("duration: {:?}", dur)
    };
}
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rust-iso-test`
parse failed: "Parser Error: P-1Y-1MT1.2S"
```

Node's 'iso8601' library mis-parses it:

```
> let iso8601
undefined
> import("iso8601-duration").then(module => { iso8601 = module })
Promise { <pending> }
> iso8601.parse("P-1Y-1MT1.2S")
{
  weeks: 0,
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0
}
```
___
*[pkg/util/duration/duration_test.go, line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-McxDUW63toKBuayEFVi:-McxDUW63toKBuayEFVj:b-s35hg7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5457a7b3e47317dd5667cd6cb072e2577b78eee3/pkg/util/duration/duration_test.go#L615)):*
> ```Go
> 			t.Errorf("ISO8601String output for %v incorrect, expected [%s], got [%s]", test.duration, test.expected, str)
> 		}
> 	}
> ```

:thinking: Would it be useful to have some tests that ensure that these can all round-trip through the 8601 parser we have over in sql/sem/tree/interval?


<!-- Sent from Reviewable.io -->

2021-06-24 18:07 UTC, HonoreDB commented
___
*[pkg/util/duration/duration_test.go, line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-Mcx4xwjDeRo1LnWb_hU:-MczBOak-q5Z1tTE5DT9:bm9vuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5457a7b3e47317dd5667cd6cb072e2577b78eee3/pkg/util/duration/duration_test.go#L605)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> ```
> P-1Y-1MT1.2S
> ```

I don't think you have another choice here because, like PostgreSQL, we allow INTERVALs where different components have different signs. 

But, our handling of negative values might be something to add to the documentation since the ISO8601 standard doesn't seem to mention how they should be handled and various libraries seem to differ on whether they can handle this. I did a quick survey of the libraries I found when I searched for "iso 8601 duration LANG" and didn't find much agreement:

Ruby's ActiveSupport parses negative components:

```
irb(main):001:0> require 'active_support/duration'
=> true
irb(main):002:0> ActiveSupport::Duration.parse('P-1Y-1MT1.2S');
=> -1 years, -1 months, and 1.2 seconds
```

Python's isodate package doesn't:

```
>>> import isodate
>>> isodate.parse_duration('P-1Y-1MT1.2S')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/isodate/isoduration.py", line 91, in parse_duration
    durdt = parse_datetime(datestring[1:])
  File "/usr/local/lib/python3.9/site-packages/isodate/isodatetime.py", line 55, in parse_datetime
    tmpdate = parse_date(datestring)
  File "/usr/local/lib/python3.9/site-packages/isodate/isodates.py", line 203, in parse_date
    raise ISO8601Error('Unrecognised ISO 8601 date format: %r' % datestring)
isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: '-1Y-1M'
```

Perl's DateTime::Format package doesn't:

```
> cat test.pl 
use DateTime::Format::Duration::ISO8601;
my $format = DateTime::Format::Duration::ISO8601->new;
my $d = $format->parse_duration('P-1Y-1MT1.2S');
say $d
> perl -I/Users/ssd/perl5/lib/perl5/ ./test.pl 
"P-1Y-1MT1.2S": not a valid ISO 8601 duration string at /Users/ssd/perl5/lib/perl5/DateTime/Format/Duration/ISO8601.pm line 15.
```


Rust's iso8601 doesn't:

```
> cat src/main.rs 
use iso8601;

fn main() {
    let duration = iso8601::duration("P-1Y-1MT1.2S");
    match duration {
        Err(err) => println!("parse failed: {:?}", err),
        Ok(dur) => println!("duration: {:?}", dur)
    };
}
> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rust-iso-test`
parse failed: "Parser Error: P-1Y-1MT1.2S"
```

Node's 'iso8601' library mis-parses it:

```
> let iso8601
undefined
> import("iso8601-duration").then(module => { iso8601 = module })
Promise { <pending> }
> iso8601.parse("P-1Y-1MT1.2S")
{
  weeks: 0,
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0
}
```

</blockquote></details>

Thank you for the research! I agree that it'll be worth documenting the space of possible outputs here. We're stuck with mixed-sign intervals for compatibility, but hopefully they'll only make it into a database if the rest of the stack supports them.


<!-- Sent from Reviewable.io -->

2021-06-24 18:59 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66800)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @otan, and @stevendanna)

___
*[pkg/util/duration/duration_test.go, line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-McxDUW63toKBuayEFVi:-MczNXSK0MAPwQT7w0uQ:b-civf6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5457a7b3e47317dd5667cd6cb072e2577b78eee3/pkg/util/duration/duration_test.go#L615)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

:thinking: Would it be useful to have some tests that ensure that these can all round-trip through the 8601 parser we have over in sql/sem/tree/interval?
</blockquote></details>

Done, yeah. I'd written the tests that way originally but was foiled because parsing in the util package created an import cycle, but no reason they can't just go in the interval_test file.


<!-- Sent from Reviewable.io -->

2021-06-24 23:10 UTC, otan approved these changes

2021-06-24 23:10 UTC, otan commented on pkg/util/duration/duration.go
> +		d.Months %= 12
super nit: prefer assigning months to a variable and modding that. 
paranoid of `d Duration` becoming `d *Duration` and a subtle bug coming later along.

2021-06-24 23:10 UTC, otan commented on pkg/util/duration/duration.go
> +	// Extract abs(d.nanos). See https://play.golang.org/p/U3_gNMpyUew.
nit: Instead of linking the go playground, can you say `-math.MinInt64` != `math.MaxInt64`

2021-06-24 23:31 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66800)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, @otan, and @stevendanna)

___
*[pkg/util/duration/duration.go, line 457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66800#-Mcuk5dPIqIhrOqWZFGT-r2-457:-Md-MBImEaywCom8f2gA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b2a43492cfe80312e242fd8020e1ff759b05c1/pkg/util/duration/duration.go#L457)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

super nit: prefer assigning months to a variable and modding that. 
paranoid of `d Duration` becoming `d *Duration` and a subtle bug coming later along.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-07 21:34 UTC, otan requested changes
We now have `FormatWithStyle(interval, IntervalStyle_ISO_8601)`, can you reformat this to use that?

2021-07-08 17:18 UTC, HonoreDB commented
@otan well, that certainly simplifies things. I see you implemented the formatting a little differently than I did, but maybe the only functional change is expression 0 as zero seconds instead of zero days?

2021-07-08 20:50 UTC, HonoreDB commented
My tests pass with your implementation, anyway, so I'll trust it :)

2021-07-08 22:22 UTC, otan approved these changes
was someone else's implementation, i just committed it :)

2021-07-09 00:31 UTC, HonoreDB commented
bors r=[stevendanna,otan]

2021-07-09 02:05 UTC, otan commented
bors r-

🚨 bors is busted 🚨

2021-07-09 02:08 UTC, otan commented
bors r=[stevendanna,otan]

2021-07-09 07:20 UTC, merged