cli,storage: add emergency ballast
cockroachdb/cockroach pull request #66893
Opened 2021-06-25 18:33 UTC by jbowens

Add an automatically created, on-by-default emergency ballast file. This
new ballast defaults to the minimum of 1% total disk capacity or 1GiB.
The size of the ballast may be configured via the `--store` flag with a
`ballast-size` field, accepting the same value formats as the `size`
field.

The ballast is automatically created when either available disk space is
at least four times the ballast size, or when available disk space after
creating the ballast is at least 10 GiB. Creation of the ballast happens
either when the engine is opened or during the periodic Capacity
calculations driven by the `kvserver.Store`.

During node start, if available disk space is less than or equal to half
the ballast size, exit immediately with a new Disk Full (10) exit code.

See #66493.

Release note (ops change): Add an automatically created, on by default
emergency ballast file. This new ballast defaults to the minimum of 1%
total disk capacity or 1GiB.  The size of the ballast may be configured
via the `--store` flag with a `ballast-size` field, accepting the same
value formats as the `size` field.

----

This branch is rebased over #66796.

2021-06-25 18:33 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66893)
<!-- Reviewable:end -->

2021-06-28 10:00 UTC, tbg reviewed
Thanks for putting this up Jackson! This looks good to me (I did have some questions and UX comments inline), but I didn't do a nitty-gritty line-by-line review. I don't think Josh will do that either; mind getting a reviewer from `storage` as well for that?

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MdH2nFD8N3HTfhwiyRE:bb5t036)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @joshimhoff)

___
*[pkg/base/store_spec.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH05mP9IBFbTmE-IVq:-MdH05mP9IBFbTmE-IVr:b-shonue) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/base/store_spec.go#L329)):*
> ```Go
> 		case "ballast-size":
> 			var minBytesAllowed int64
> 			var minPercent float64 = 1
> ```

aren't 0.1% etc also allowed?
___
*[pkg/cli/start.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH0T1Q5eDDth8MDHbA:-MdH0T1Q5eDDth8MDHbB:b-425u3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/cli/start.go#L341)):*
> ```Go
> 			return err
> 		} else if isDiskFull {
> 			err := errors.Errorf("store %s: out of disk space", spec.Path)
> ```

nit: you could collect all of the out-of-disk specs across stores, in case multiple are out of space. You could also hint people at the existence of the ballast file or, in the future, at docs on the topic.
___
*[pkg/storage/ballast.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH1Nfv7CVU4HXmH8iH:-MdH1Nfv7CVU4HXmH8iI:b565bt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L36)):*
> ```Go
> 	desiredSizeBytes := BallastSizeBytes(spec, diskUsage)
> 
> 	ballastPath := base.EmergencyBallastFile(fs.PathJoin, spec.Path)
> ```

are these all stable under different ways of starting the same node? For example, I might start it with `--store=./data` one day, and with `--store=/foo/bar/data` the next.

We should also note on `EmergencyBallastFile` that the constants within cannot be changed, or existing ballast files will start getting included in disk usage & new ballast files will be created. More things that would be useful:

1. give devs a way to opt-out of ballast files via an env var. I don't want a 1GB file to be created every time I `./cockroach start-single- node`.
2. similarly, need to make sure that `cockroach demo` doesn't ever do ballast files (I think that's always in-mem, so probably already true)
3. it might be worth putting a `.txt` file next to `EmergencyBallastFile` that has some information about ballast and how to disable it if undesirable.
___
*[pkg/storage/ballast_test.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH1nXm-yqEAlxOwipE:-MdH1nXm-yqEAlxOwipF:bc83fpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast_test.go#L218)):*
> ```Go
> 		path, cleanup := setup(t, 4096)
> 		defer cleanup()
> 		resized, err := maybeEstablishBallast(vfs.Default, path, 4096, vfs.DiskUsage{
> ```

From your experience, are disk capacities static? For example, if a disk reports a capacity of `10TB + rand(0,100) bytes`, will that lead to the ballast file being recreated ~every time (which is probably mildly expensive, or very expensive when the file actually has to be written wholesale)?


<!-- Sent from Reviewable.io -->

2021-06-28 14:37 UTC, joshimhoff reviewed
Also thanks for putting me on the PR. It's really nice to work with y'all directly on solving various problems that have an operational angle / affect oncall life in a big way. That is, DEVOPS (in the deep platonic sense (no buzzwords allowed)).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MdHxFcG-PTPDSj3lPua:bgyn4jf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdI-pHX-792zOjDiR9i:b-cf1j2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
> ```Go
> // IsDiskFull examines the store indicated by spec, determining whether the
> // store's underlying disk is out of disk space. A disk is considered to be
> // full if available capacity is less than half of the store's ballast size.
> ```

Is one of the goals of this PR that after a single crash, all subsequent crashes will have the out of disk exit code, as CRDB will determine that the disk is full by calling this function? What is our confidence that in an out of disk scenario, we will exit with the new code repeatedly? In asking this Q, I am thinking about the possibly of an attempt to write to some log file failing before this check is made, as has happened in CC land (as we use datadir disk for logging currently). Can you say why our confidence is what it is for my learning also? I can imagine deleting the ballast automatically on startup when needed, but continuing to crash as the available disk is ~equal to the ballast, but perhaps that is not necessary as we have the confidence we need already, just for reasons I don't follow yet.

Also, what about the first crash? This will happen in the <=21.1 way, that is, somewhere a write to disk will fail leading to a crash, and we can't say much about the exit code, as it depends where that happens? If that is right, do we generally expect a 100% full disk, that is, no available capacity, rather than a disk that has around 1/2 ballast worth of capacity? In a way this relates to my first Q.


<!-- Sent from Reviewable.io -->

2021-06-28 16:00 UTC, jbowens reviewed
> mind getting a reviewer from storage as well for that?

For sure. I think maybe we should see whether the exit code approach is workable within CC alerting, but then I'll tag storage folks for review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MdILH_IBQDo03Y8oOi_:b-ixcp76)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @joshimhoff, and @tbg)

___
*[pkg/base/store_spec.go, line 329 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH05mP9IBFbTmE-IVq:-MdI9q6gEesaWlR8JkZa:bz7dsrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/base/store_spec.go#L329)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

aren't 0.1% etc also allowed?
</blockquote></details>

Good call, lifted the minimum requirement altogether.
___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdIEKr4BeU-dbT50crc:bz9jyb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
> Is one of the goals of this PR that after a single crash, all subsequent crashes will have the out of disk exit code, as CRDB will determine that the disk is full by calling this function? What is our confidence that in an out of disk scenario, we will exit with the new code repeatedly? In asking this Q, I am thinking about the possibly of an attempt to write to some log file failing before this check is made, as has happened in CC land (as we use datadir disk for logging currently). Can you say why our confidence is what it is for my learning also?

Yeah, we want all subsequent exits to have the disk full exit code. I'm pretty confident that we will always exit with the new code, so long as some other process isn't causing disk usage to fluctuate rapidly. The call to this function happens very early in the node start path, even before we initialize logging. Before we call `IsDiskFull`, we parse command flags, maybe re-execute the process in the background if requested, set a umask and set up signal handlers. That's it.

> I can imagine deleting the ballast automatically on startup when needed, but continuing to crash as the available disk is ~equal to the ballast, but perhaps that is not necessary as we have the confidence we need already, just for reasons I don't follow yet.

In a non-CC setting, we want the user to be able to start up with the newly created ballast headroom and try to recover the node/cluster. Without a separate file or flag to indicate that intent, we need the user to delete the ballast so that the increased available capacity can be the signal.

> Also, what about the first crash? This will happen in the <=21.1 way, that is, somewhere a write to disk will fail leading to a crash, and we can't say much about the exit code, as it depends where that happens? 

I expect the vast majority of first crashes to exit with the `Disk Full` error code, because of a wrapper around the virtual file system used by Pebble and _most_ filesystem writes within CockroachDB. There are definitely some codepaths that directly use the standard library `os` package and an `ENOSPC` in those codepaths potentially could fatal the process with a different exit code. As far as I know, these codepaths are just things like:
* TLS certificate rotation
* writing to external/nodelocal storage (eg, when writing backups to the node's local disk for collecting later; not relevant to CC)
* writing CPU and heap profiles, goroutine dumps, debug.zips
* unfortunately, resizing the ballast itself, for now

> If that is right, do we generally expect a 100% full disk, that is, no available capacity, rather than a disk that has around 1/2 ballast worth of capacity? In a way this relates to my first Q.

We generally expect an available capacity that is just shy of 0. There's some amount of variation in the low-level block allocation requests made by the filesystem, but as far as I know, not a lot. I think there may be more variation on copy-on-write filesystems like btrfs or zfs, but we don't need to worry about that in CC. 
___
*[pkg/storage/ballast.go, line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH1Nfv7CVU4HXmH8iH:-MdIC-FU14Z6ENRJqrU_:b-cjvm65) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L36)):*
> are these all stable under different ways of starting the same node? For example, I might start it with --store=./data one day, and with --store=/foo/bar/data the next.

Yeah, we convert to the store path to an absolute path very early when we construct the `StoreSpec`. We _don't_ have a guarantee that the store directory will exist though, so I updated this to account for that.

> 1. give devs a way to opt-out of ballast files via an env var. I don't want a 1GB file to be created every time I ./cockroach start-single- node.

Good point. I'll follow up with this in a bit.

> 2. similarly, need to make sure that cockroach demo doesn't ever do ballast files (I think that's always in-mem, so probably already true)

I'll double check this.

> 3. it might be worth putting a .txt file next to EmergencyBallastFile that has some information about ballast and how to disable it if undesirable.

Good call.
___
*[pkg/storage/ballast_test.go, line 218 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH1nXm-yqEAlxOwipE:-MdIBlaH22gSkKuwE56c:b-a04di0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast_test.go#L218)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

From your experience, are disk capacities static? For example, if a disk reports a capacity of `10TB + rand(0,100) bytes`, will that lead to the ballast file being recreated ~every time (which is probably mildly expensive, or very expensive when the file actually has to be written wholesale)?
</blockquote></details>

This is a good question — I do expect it to be static, but it's worth verifying that experimentally.


<!-- Sent from Reviewable.io -->

2021-06-28 16:18 UTC, joshimhoff reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdIOjXS-wZP26C6WHs6:b9gxzje) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
Ack! Thanks for explaining. I might suggest that some of above thinking should be in comments in the code, perhaps in `start.go`? I also wonder if we should / can system test the consistent exit code when out of disk, so we don't lose the property down the line?

I will check this out today / tomorrow in the AM; I think it will work; I just want to be paranoid about it.

> For sure. I think maybe we should see whether the exit code approach is workable within CC alerting


<!-- Sent from Reviewable.io -->

2021-06-28 19:16 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff and @tbg)

___
*[pkg/cli/start.go, line 341 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdH0T1Q5eDDth8MDHbA:-MdImAU82ZIBv977qCM9:b9ow35o) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/cli/start.go#L341)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

nit: you could collect all of the out-of-disk specs across stores, in case multiple are out of space. You could also hint people at the existence of the ballast file or, in the future, at docs on the topic.
</blockquote></details>

good call, done.
___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdIoqa385BxiIg5bKRu:b-6xnipl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
added some comments!

> I will check this out today / tomorrow in the AM; I think it will work; I just want to be paranoid about it.

awesome, thank you!


<!-- Sent from Reviewable.io -->

2021-06-29 13:13 UTC, knz approved these changes
looks good to me. just a few nits

> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, 3 of 10 files at r3, 2 of 6 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MdMtdvA3Di3TJLCNxuk:b-a4q4a0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @joshimhoff, and @tbg)

___
*[pkg/base/store_spec.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMr8nD6nra1I-GkBpz:-MdMr8nE9bVDz-h7fQEI:b-bkzplb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L82)):*
> ```Go
> // SizeSpec if it is correctly parsed.
> func NewSizeSpec(
> 	field, value string, bytesRange *intInterval, percentRange *floatInterval,
> ```

maybe make the `field` argument a `redact.SafeString`
___
*[pkg/base/store_spec.go, line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrCfR-Uq-9Jm8KZ2a:-MdMrCfR-Uq-9Jm8KZ2b:br9vfh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L96)):*
> ```Go
> 		size.Percent *= percentFactor
> 		if err != nil {
> 			return SizeSpec{}, fmt.Errorf("could not parse %s size (%s) %s", field, value, err)
> ```

then use `errors.Newf` here and below
___
*[pkg/base/store_spec.go, line 154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrLEE1nDzrOD2b7fd:-MdMrLEE1nDzrOD2b7fe:b-oolqi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L154)):*
> ```Go
> // pflag's value interface.
> func (ss *SizeSpec) Set(value string) error {
> 	spec, err := NewSizeSpec("", value, nil, nil)
> ```

change that empty string to `"specified"` so that the error messages, if any, check out with the flag UX.
___
*[pkg/base/store_spec.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrXCq8gGIi0sa3Pyu:-MdMrXCq8gGIi0sa3Pyv:brighiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L194)):*
> ```Go
> 
> // String returns a fully parsable version of the store spec.
> func (ss StoreSpec) String() string {
> ```

All this would benefit from being turned into a `SafeFormat`.
___
*[pkg/cli/start.go, line 1037 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMs3BVBr6uY3t6PYvR:-MdMs3BW4_HHtA_eyacr:b-wexgv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/cli/start.go#L1037)):*
> ```Go
> 	}
> 	ballastPathsStr := strings.Join(ballastPaths, "\n")
> 	err = errors.WithDetailf(err, `Deleting or truncating the ballast file(s) at
> ```

nit: might be a hint more than a detail
___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdMsP2T2XXYRSnYGXo3:b-lj9yyy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

added some comments!

> I will check this out today / tomorrow in the AM; I think it will work; I just want to be paranoid about it.

awesome, thank you!
</blockquote></details>

Can you also explain the above in the release note thanks. Release notes are the communication channel by which we send information to docs.


<!-- Sent from Reviewable.io -->

2021-06-29 15:33 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @knz, and @tbg)

___
*[pkg/base/store_spec.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMr8nD6nra1I-GkBpz:-MdNLEH3APteejUJhtDM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L82)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

maybe make the `field` argument a `redact.SafeString`
</blockquote></details>

Done.
___
*[pkg/base/store_spec.go, line 96 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrCfR-Uq-9Jm8KZ2a:-MdNLXPF6CXP0V6POcvt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L96)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

then use `errors.Newf` here and below
</blockquote></details>

Done.
___
*[pkg/base/store_spec.go, line 154 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrLEE1nDzrOD2b7fd:-MdNLcuS73W761tG7Rfw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L154)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

change that empty string to `"specified"` so that the error messages, if any, check out with the flag UX.
</blockquote></details>

Done.
___
*[pkg/base/store_spec.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMrXCq8gGIi0sa3Pyu:-MdNNI2u6XxyAWYhHTbF:bkd5ega) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/base/store_spec.go#L194)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

All this would benefit from being turned into a `SafeFormat`.
</blockquote></details>

Added a TODO
___
*[pkg/cli/start.go, line 1037 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdMs3BVBr6uY3t6PYvR:-MdNMocV-2RUJjsoGRAi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5789e922c8a6527c15896b6531bf7cbb8dd3ff6/pkg/cli/start.go#L1037)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: might be a hint more than a detail
</blockquote></details>

Done.
___
*[pkg/storage/ballast.go, line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdI-pHX-792zOjDiR9h:-MdNMxna3HHnBTkVbgqL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b4e38644386d80449c65ceb431b921c91c407d6/pkg/storage/ballast.go#L25)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you also explain the above in the release note thanks. Release notes are the communication channel by which we send information to docs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-29 18:17 UTC, sumeerbhola requested changes
> Reviewed 1 of 10 files at r3, 1 of 6 files at r4, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, @jbowens, @joshimhoff, @knz, and @tbg)

___
*[pkg/storage/ballast.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNtiXaEnDgXdmO28MC:-MdNtiXb-l50BKE775pn:b-s3ega0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L28)):*
> ```Go
> // may want to include `COCKROACH_AUTO_BALLAST=false` in their environment to
> // prevent the automatic creation of large ballast files on their local
> // filesystem.
> ```

Have we already taught our on-prem users to create a ballast file using https://www.cockroachlabs.com/docs/stable/cockroach-debug-ballast.html?
If yes, I assume that the default here would create another one since the existing one could have an arbitrary path that we don't know about.
I can see why we would want to default to true, and possibly all we need is sufficient release documentation -- what I worry about is their being 2 ballast files and no one noticing.
___
*[pkg/storage/ballast.go, line 64 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNvty7DvUwhgzoOnVi:-MdNvty7DvUwhgzoOnVj:b-i2alcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L64)):*
> ```Go
> 	}
> 
> 	// If the ballast is larger than desired, truncate it now in case the
> ```

what if we need to increase it in size? Is there a reason why that would only happen via the `Capacity` periodic logic and not here?
___
*[pkg/storage/ballast.go, line 89 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNvb4b9J2wKatWH80r:-MdNvb4b9J2wKatWH80s:bw8jasf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L89)):*
> ```Go
> // BallastSizeBytes returns the desired size of the emergency ballast,
> // calculated from the provided store spec and disk usage. If the store spec
> // contains an explicit ballast size (either in bytes or as a perecentage of
> ```

percentage
___
*[pkg/storage/ballast.go, line 141 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNwIvT3QpAa0ikX6Ln:-MdNwIvT3QpAa0ikX6Lo:b7dv06x) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L141)):*
> ```Go
> 		// If the user configured a really large ballast, we might not ever
> 		// have >= 4x the required amount available. Also allow extending the
> 		// ballast if we will have 10 GiB available after the extension.
> ```

What is the motivation for this 10GiB logic? Should we log an error instead of potentially taking up too much space? I can see why that would not be satisfactory since no one may notice. A code comment could help here.
___
*[pkg/storage/pebble.go, line 592 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNxPmI9r7Cy2F2V2ua:-MdNxPmI9r7Cy2F2V2ub:b-ppwjdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/pebble.go#L592)):*
> ```Go
> 	// store's capacity is queried periodically. Only try if the store is not
> 	// an in-memory store. vfs.MemFS will error if you retrieve disk usage.
> 	if cfg.Dir != "" /* if not in-memory */ {
> ```

Is this a reliable way of detecting "not in-memory"?
___
*[pkg/storage/pebble.go, line 1027 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNy1dZEGfc8ucIBkT1:-MdNy1dZEGfc8ucIBkT2:b-mh8mow) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/pebble.go#L1027)):*
> ```Go
> 	fsuTotal := int64(du.TotalBytes)
> 	fsuAvail := int64(du.AvailBytes)
> ```

Can you add a code comment about `Capacity` being called periodically.


<!-- Sent from Reviewable.io -->

2021-07-13 19:41 UTC, jbowens reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, @joshimhoff, @knz, @sumeerbhola, and @tbg)

___
*[pkg/storage/ballast.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNtiXaEnDgXdmO28MC:-MeWNNXlBeYB9USif_Vm:bltefb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L28)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Have we already taught our on-prem users to create a ballast file using https://www.cockroachlabs.com/docs/stable/cockroach-debug-ballast.html?
If yes, I assume that the default here would create another one since the existing one could have an arbitrary path that we don't know about.
I can see why we would want to default to true, and possibly all we need is sufficient release documentation -- what I worry about is their being 2 ballast files and no one noticing.
</blockquote></details>

It is featured somewhat prominently on the [production checklist docs](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html). I pinged customer success to see if anyone has a sense of how widespread manually-created ballasts are. This is definitely something that needs to be well-documented in the release docs. I'm not sure what else we can do outside that.
___
*[pkg/storage/ballast.go, line 64 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNvty7DvUwhgzoOnVi:-MeWLGoM6kEANfxhIi-q:bnkn96i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L64)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what if we need to increase it in size? Is there a reason why that would only happen via the `Capacity` periodic logic and not here?
</blockquote></details>

There's just the complication that the data directory might not exist yet. I think it is preferable to establish the ballast here too if available capacity allows. I updated `maybeEstablishBallast`, adding a `MkdirAll` of the data directory before attempting to create/grow the ballast.
___
*[pkg/storage/ballast.go, line 89 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNvb4b9J2wKatWH80r:-MeWB_6q0sNB1XZAA-Vl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L89)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

percentage
</blockquote></details>

Done.
___
*[pkg/storage/ballast.go, line 141 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNwIvT3QpAa0ikX6Ln:-MeWEkaQ6zfC3qjiyY0a:b1jwwph) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/ballast.go#L141)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What is the motivation for this 10GiB logic? Should we log an error instead of potentially taking up too much space? I can see why that would not be satisfactory since no one may notice. A code comment could help here.
</blockquote></details>

The 10 GiB logic exists for users that want the safety of a large ballast. Larger ballast sizes (eg, 5%, 10%) are not unreasonably large, but it's possible that available capacity will never exceed 4x the ballast sizes (eg, 20%, 40%) after recovery. That's especially true on larger clusters where you can use a higher percentage of each individual disk's capacity because the cluster as a whole still has plenty of capacity for rehoming replicas if a node is lost. Added a little more of this explanation as a code comment.
___
*[pkg/storage/pebble.go, line 592 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNxPmI9r7Cy2F2V2ua:-MeW9alx-ygIqRrcWb8r:b-xb6cjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/pebble.go#L592)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this a reliable way of detecting "not in-memory"?
</blockquote></details>

Yeah, it's the check `Capacity` makes, and the check `(*Pebble).InMem()` makes.
___
*[pkg/storage/pebble.go, line 1027 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MdNy1dZEGfc8ucIBkT1:-MeWB1667OQP0tfD02c1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d52735b2f2125a60f139ceea60b3890fad2b10a/pkg/storage/pebble.go#L1027)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add a code comment about `Capacity` being called periodically.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-16 18:34 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 10 files at r3, 1 of 6 files at r5, 9 of 14 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MhFEV_d3gRW5bHGvZFn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick, @itsbilal, @jbowens, @joshimhoff, @knz, @sumeerbhola, and @tbg)

___
*[pkg/cli/start.go, line 1040 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MhF9nvY4Ok6eUfexUgV:-MhF9nvY4Ok6eUfexUgW:besfo88) ([raw file](https://github.com/cockroachdb/cockroach/blob/783ed0bd826fae814ac94dfcae61345164800f42/pkg/cli/start.go#L1040)):*
> ```Go
> 			continue
> 		}
> 		ballastPaths = append(ballastPaths, base.EmergencyBallastFile(vfs.Default.PathJoin, spec.Path))
> ```

how about confirming that this file actually exists and classifying into two categories of errors: can or cannot be rectified by deleting the ballast file. That may be more helpful to an operator who is trying to deal with an emergency situation.
___
*[pkg/storage/ballast.go, line 58 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MhFBjKQBZ45iYoOYCOr:-MhFBjKQBZ45iYoOYCOs:be0og2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/783ed0bd826fae814ac94dfcae61345164800f42/pkg/storage/ballast.go#L58)):*
> ```Go
> 
> 	// Try to resize the ballast now, if necessary. This is necessary to
> 	// truncate the ballast if it a new, lower ballast size was provided, and
> ```

... if a new ...


<!-- Sent from Reviewable.io -->

2021-08-19 19:19 UTC, jbowens reviewed
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-:-MhUqdV_1lkVsAsCPEnw:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick, @itsbilal, @joshimhoff, @knz, @sumeerbhola, and @tbg)

___
*[pkg/cli/start.go, line 1040 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MhF9nvY4Ok6eUfexUgV:-MhQ9LgI5QJrECZ-kPco:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/783ed0bd826fae814ac94dfcae61345164800f42/pkg/cli/start.go#L1040)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

how about confirming that this file actually exists and classifying into two categories of errors: can or cannot be rectified by deleting the ballast file. That may be more helpful to an operator who is trying to deal with an emergency situation.
</blockquote></details>

Done.
___
*[pkg/storage/ballast.go, line 58 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66893#-MhFBjKQBZ45iYoOYCOr:-MhPr8vyD5TyXp9sW5Rd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/783ed0bd826fae814ac94dfcae61345164800f42/pkg/storage/ballast.go#L58)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... if a new ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-19 21:21 UTC, merged