cluster-ui: add "" to whitespace app names
cockroachdb/cockroach pull request #66967
Opened 2021-06-28 14:47 UTC by maryliag

A user can setup the application name as whitespaces and
it's hard to recognize it when selecting the filter.
This commit adds "" to the name.

Resolves: https://github.com/cockroachdb/cockroach/issues/63419

Before:
<img width="299" alt="Screen Shot 2021-06-28 at 10 46 12 AM" src="https://user-images.githubusercontent.com/1017486/123656626-180b7080-d7fe-11eb-9dde-f642c645d5d5.png">

After:
<img width="302" alt="Screen Shot 2021-06-28 at 10 36 13 AM" src="https://user-images.githubusercontent.com/1017486/123656329-cfec4e00-d7fd-11eb-9152-43846b91ae6a.png">

Release note (ui change): Add "" to whitespace application names
on filter selection on statements and transactions page.

2021-06-28 14:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/66967)
<!-- Reviewable:end -->

2021-06-29 15:57 UTC, nathanstilwell requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNTP2AEq41RO57Z7WO:-MdNTP2AEq41RO57Z7WP:bchjx9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L402)):*
> ```XML
>     const apps = appNames.map(app => {
>       const label =
>         app.label.trim().length === 0 ? '"' + app.label + '"' : app.label;
> ```

I hate to be pedantic, but if the `app.label.length` is 0, does it need to be included when returning `""`?

Wouldn't `const label = app.label.trim().length === 0 ? '""' : app.label;` be the same thing?
___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNU2MM40F_FMFdM8Pq:-MdNU2MM40F_FMFdM8Pr:b4n8515) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L418)):*
> ```XML
>               options={apps}
>               onChange={e => this.handleChange(e, "app")}
>               value={apps.filter(app => app.value == filters.app)}
> ```

I know this isn't your change, but while you're here, can your replace that `==` with a `===`? 


<!-- Sent from Reviewable.io -->

2021-06-29 16:10 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNTP2AEq41RO57Z7WO:-MdNWLt7C0wHvx7XZ20Q:b-lwhf9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L402)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I hate to be pedantic, but if the `app.label.length` is 0, does it need to be included when returning `""`?

Wouldn't `const label = app.label.trim().length === 0 ? '""' : app.label;` be the same thing?
</blockquote></details>

I'm using this on cases where we have different sizes of whitespace, you can see I'm doing trim before checking the length, so I wanna differentiate `".."` and `"......."` for example (I'm using `.` to symbolize the space because the preview here keeps changing to single space)
___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNU2MM40F_FMFdM8Pq:-MdNXChc8aHWodM2g0Yh:bahtenf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L418)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I know this isn't your change, but while you're here, can your replace that `==` with a `===`? 
</blockquote></details>

Sure :) 


<!-- Sent from Reviewable.io -->

2021-06-29 19:16 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNU2MM40F_FMFdM8Pq:-MdOBk0y7S-vSMpnJLlJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L418)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Sure :) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-30 13:26 UTC, nathanstilwell approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNTP2AEq41RO57Z7WO:-MdS3OJj6iSIb27LeenX:b-vuhbul) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L402)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I'm using this on cases where we have different sizes of whitespace, you can see I'm doing trim before checking the length, so I wanna differentiate `".."` and `"......."` for example (I'm using `.` to symbolize the space because the preview here keeps changing to single space)
</blockquote></details>

I see, but I believe that `.trim()` will remove all whitespace. So `".."` and `"........."` will both have a length of 0 after `.trim()`. At any rate, this isn't a blocker for me. :smiley: 


<!-- Sent from Reviewable.io -->

2021-06-30 14:09 UTC, maryliag reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell)

___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNTP2AEq41RO57Z7WO:-MdSENUo8NJ0HzXESFcK:b-plm58d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L402)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I see, but I believe that `.trim()` will remove all whitespace. So `".."` and `"........."` will both have a length of 0 after `.trim()`. At any rate, this isn't a blocker for me. :smiley: 
</blockquote></details>

Just leaving an explanation here for future reference: 
I use trim to check if is any only whitespace string, but to create the label itself I use the initial value without the trim, so we can differentiate different sizes of whitespace only string names


<!-- Sent from Reviewable.io -->

2021-06-30 14:09 UTC, maryliag commented
bors r+

2021-06-30 14:50 UTC, merged

2021-06-30 17:20 UTC, nathanstilwell commented
___
*[pkg/ui/cluster-ui/src/queryFilter/filter.tsx, line 402 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66967#-MdNTP2AEq41RO57Z7WO:-MdSviqr0Qa1DKNIuhzU:bwe804i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ecbd0de5047a13f131a4df10ddade4ba12d3e10/pkg/ui/cluster-ui/src/queryFilter/filter.tsx#L402)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Just leaving an explanation here for future reference: 
I use trim to check if is any only whitespace string, but to create the label itself I use the initial value without the trim, so we can differentiate different sizes of whitespace only string names
</blockquote></details>

I finally get it. Thanks for the explanation. :smile: 


<!-- Sent from Reviewable.io -->