sql: implement sqlstats flush
cockroachdb/cockroach pull request #67090
Opened 2021-06-30 21:08 UTC by Azhng

Previous PR: #65374

## First commit

sql: add json encoding/decoding support for stmt/txn stats.

Release note: None

## Second commit

sql: introduce persistedsqlstats subsystem

This commit introduces a new persisted sql stats subsystem
that wraps the existing node-local sql stats subsystem.
This new subsystem is responsible for flushing the in-meory
statistics into the system table periodically, or when it
detects memory pressure.

Release note: None

## Third commit

sql: replace the sqlStats provider in the sql.Server with a persisted
 version

Previously, sql.Server use a node-local in-memory sqlStats provider to
store SQL stats, which is cleared every hour.
This commit replaces that provider with a persisted version that was introduced
in the previous commit to enable all SQL stats to be persisted in the
system tables.

Release note (sql change): SQL stats now can be persisted into
 `system.statement_statistics` and `system.transaction_statistics`
 tables by enabling the `sql.stats.flush.enable` cluster setting.
 The interval of persistence is determined by the new
 `sql.stats.flush.interval` cluster setting which defaults to 1 hour.

2021-06-30 21:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67090)
<!-- Reviewable:end -->

2021-07-14 17:01 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_decoding.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Me_r3H7B1_nLVYNIuuE:-Me_r3H8B-xXnmZQpnH3:b-fubpfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4fef197eb6f39eb9d5bfd89e48cc1358fb87d18/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_decoding.go#L136)):*
> ```Go
> 	metadata json.JSON, result *roachpb.CollectedStatementStatistics,
> ) error {
> 	err := decodeString(metadata, "stmtTyp", &result.Stats.SQLType)
> ```

You've built a lot of machinery here but it still ends up being quite verbose to use. I think I'd rework it to be more composable. You can probably also rearrange it such that the decoding and encoding can be symmetrical for each of your top-level data types. Consider the following approach:

```go
type jsonDecoder interface {
    decodeJSON(js json.JSON) error
}

type decimal tree.DDecimal

func (d *decimal) decodeJSON(js json.JSON) error {
    var ok bool
    decimal := (*apd.Decimal)(d)
    *decimal, ok = field.AsDecimal()
    if !ok {
	return nil, errors.New("unable to decode float64")
     }
    return nil
}

type jsonFloat float64

func (f *jsonFloat) decodeJSON(js json.JSON) error {
        var d apd.Decimal
        if err := (*decimal)(d).decodeJSON(js); err != nil {
            return err
        }
        asFloat, err := d.AsFloat()
        if err != nil {
            return err
        }
        *f = jsonFloat(asFloat)
       return nil
}

func (jf jsonField) (js json.JSON) (err error) {
        defer func() {
            if err != nil {
                err = errors.Wrapf(err, "decoding field %s", field)
            }
        }()
    	field, err := safeFetchVal(js, jf.field)
	if err != nil {
		return err
	}
        return jf.dec.decodeJSON(field)
}

type jsonField struct {
    field string
    dec  jsonDecoder
}

type jsonFields []jsonField

func (jf jsonFeilds) decodeJSON(js json.JSON) error {
    for i := range jf {
        if err := jf[i].decodeJSON(js); err != nil {
            return err
        }
    }
}

func (n *numeric) decodeJSON(obj json.JSON) error {
        fields := [...]jsonField{
            {"mean", (*jsonFloat)(&result.Mean)},
            {"sqDiff", (*jsonFloat)(&result.SquaredDiffs)},
        }
        return (jsonFields)(fields[:]).decodeJSON(obj)
}

//...
```


<!-- Sent from Reviewable.io -->

2021-07-15 04:43 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_decoding.go, line 143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MecSZze4K7o_NBFC600:-MecSZze4K7o_NBFC601:bf9n72a) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb6205b886c5a0f68ec2db3e5d5f143af3c124ea/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_decoding.go#L143)):*
> ```Go
> type txnStats roachpb.TransactionStatistics
> 
> func (t *txnStats) decodeJSON(js json.JSON) error {
> ```

Alright, nice, let's iterate some more. Turns out this array this is not buying us anything. We can replace all of these with:

```
	return jsonFields{
		{"maxRetries", (*jsonInt)(&t.MaxRetries)},
		{"numRows", (*numericStats)(&t.NumRows)},
		{"svcLat", (*numericStats)(&t.ServiceLat)},
		{"retryLat", (*numericStats)(&t.RetryLat)},
		{"commitLat", (*numericStats)(&t.CommitLat)},
		{"bytesRead", (*numericStats)(&t.BytesRead)},
		{"rowsRead", (*numericStats)(&t.RowsRead)},
	}.decodeJSON(js)
```

*but* we can really make this shine a bunch more!

Let's add a new interface to really encoding things. Then, for the top-level types, we can add some method like `jsonFields() jsonFields` which constructs the field objects and use that in the relevant methods. 

```go
type jsonEncoder interface {
    encodeJSON() (json.JSON, error)
}

type jsonMarshaler interface {
    jsonEncoder
    jsonDecoder
}

type jsonField struct {
    field string
    val    jsonMarshaler
}

func (js jsonFields) encodeJSON() (json.JSON, error) {
    builder := json.NewObjectBuilder(len(js))
    for i := range js {
        val, err := js[i].val.encodeJSON()
        if err != nil {
            return errors.Wrapf(err, "encoding field %s", js[i].field)
        }
        builder.Add(js[i].field, val)
    }
    return builder.Build(), nil
}

func (t *txnStats) jsonFields() jsonFields {
    return jsonFields{
		{"maxRetries", (*jsonInt)(&t.MaxRetries)},
		{"numRows", (*numericStats)(&t.NumRows)},
		{"svcLat", (*numericStats)(&t.ServiceLat)},
		{"retryLat", (*numericStats)(&t.RetryLat)},
		{"commitLat", (*numericStats)(&t.CommitLat)},
		{"bytesRead", (*numericStats)(&t.BytesRead)},
		{"rowsRead", (*numericStats)(&t.RowsRead)},
    }
}

func (t *txnStats) decodeJSON(js json.JSON) error  { return t.jsonFields().decodeJSON(js) }
func (t *txnStats) encodeJSON() (json.JSON, error) { return t.jsonFields().encodeJSON() }
```


<!-- Sent from Reviewable.io -->

2021-07-15 13:21 UTC, jordanlewis requested changes
I think the last 2 commits might want to be squashed - I think you reference some stuff in r5 that's introduced in r6? Make sure each commit is atomic and can function on its own, or squash them if it's getting to feel like a waste of time to do that.

> Reviewed 4 of 7 files at r1, 22 of 22 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-:-MeeJkOZ30vSG1VlqN6N:b5qxnx0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/exec_util.go, line 828 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeJbSQ63LlIqyZvzBZ:-MeeJbSQ63LlIqyZvzB_:b-kdb4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34c11cd531f50256a3990c663e08e39d5a08fc5/pkg/sql/exec_util.go#L828)):*
> ```Go
> 	MetaSQLStatsFlushStarted = metric.Metadata{
> 		Name:        "sql.stats.flush.count",
> 		Help:        "Number of times SQL Stats are flushed persistent storage",
> ```

nit: flushed *to* persistent storage
___
*[pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go, line 23 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mee6MOy6sLI8MJ9L-ox:-Mee6MOzCcN042BUK_pN:b4gdihs) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go#L23)):*
> ```Go
> var SQLStatsFlushInterval = settings.RegisterDurationSetting(
> 	"sql.stats.flush.interval",
> 	"this interval controls how often SQL stats are flushed to system table,"+
> ```

nit: make this message more similar to other cluster settings, which don't have the intro part. Say something like "the interval at which SQL execution statistics are flushed to disk".

You don't need to include the default in the help message.
___
*[pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mee6vtY0PVM9a3VzTzG:-Mee6vtY0PVM9a3VzTzH:byfw7wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go#L33)):*
> ```Go
> var SQLStatsFlushEnabled = settings.RegisterBoolSetting(
> 	"sql.stats.flush.enabled",
> 	"this controls whether the SQL statistics are being flushed to system table",
> ```

"if set, SQL execution statistics are periodically flushed to disk"
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeAqzb96Y9HdixlR4f:-MeeAqzb96Y9HdixlR4g:b75gf5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L41)):*
> ```Go
> 		s.mu.state = flushing
> 		s.mu.Unlock()
> 		err := stopper.RunAsyncTask(ctx, "sql-stats-flush-worker", func(ctx context.Context) {
> ```

Let's add a info log message when this happens.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeFGjk6rlP9RDxkop5:-MeeFGjk6rlP9RDxkop6:bd3x3gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L41)):*
> ```Go
> 		s.mu.state = flushing
> 		s.mu.Unlock()
> 		err := stopper.RunAsyncTask(ctx, "sql-stats-flush-worker", func(ctx context.Context) {
> ```

It seems backward to spawn new flush workers each time Flush is called.

The typical pattern that we use elsewhere is to have a single, always-on flush worker. That flush worker will listen on a `time.Ticker` that's configured with the cluster setting.

That way you can get rid of this extra `s.mu.state` thing - I think it will simplify the code significantly.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 63 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeEn5H0lw2pOzk9iVU:-MeeEn5H0lw2pOzk9iVV:b7fpqkn) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L63)):*
> ```Go
> 			// It might be worth it to run them in separately async tasks concurrently
> 			// as a performance optimization if that ever becomes a problem.
> 			err = s.cfg.KvDB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

I don't think we should do these in 1 huge transaction - it's going to be really expensive and have contention issues. Remember, all nodes will be trying to do this stuff at the same time.

What is the value of using a transaction here at all? I think it is perfectly fine to do each flush statement separately.

Also, I'm somewhat concerned about the spikes in cluster load this will generate. It's an anti-pattern to have a big spike of writes and reads (and potentially contention) that occurs at a particular time interval, especially if that's going to be correlated across the cluster (imagine a cluster that restarts all at the same time - it'll all flush at around the same time, which is high load).

There are 2 patterns to deal with this.

1. Jitter the flush interval by adding a random value (-50% to +50%?) of the flush interval on run. This is straightforward, you should definitely do that.

2. We could also consider pacing the flushes. Instead of writing everything in one huge chunk, we could instead have an in-memory queue of stats to flush, and a worker goroutine whose job is simply to sit on the queue and flush each stat as it comes in. Then, we could add pacing to that worker thread, backpressure, etc. It's going to be hard to do that sort of thing the way this is set up right now - it's a very high level, batch API.
Also, this queue will allow some nice observability - we'll be able to see the queue's length in a metric.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHQQGEyFr7NmdvXyQ:-MeeHQQGEyFr7NmdvXyR:b-g5lxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L137)):*
> ```Go
> 		err := s.doInsertElseDoUpdate(ctx, txn, insertFn, readFn, updateFn)
> 		if err != nil {
> 			return errors.Errorf("failed to insert statement %d's statistics: %s", key, err)
> ```

Use errors.Wrap to wrap an error, not string interpolation.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHW5T-0sozF6OkLqU:-MeeHW5T-0sozF6OkLqV:b-mpyvg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L187)):*
> ```Go
> 		err := s.doInsertElseDoUpdate(ctx, txn, insertFn, readFn, updateFn)
> 		if err != nil {
> 			return errors.Errorf("failed to insert statement %d's statistics: %s", stats.ID, err)
> ```

ditto above.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHxzD5xjiYfib8xbv:-MeeHxzD5xjiYfib8xbw:bs7feuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L193)):*
> ```Go
> 	})
> 
> 	if err != nil {
> ```

You can just return err here. Even better, inline the return with the call to IterateStatementStats.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeI4Qp0wT6Ydf5nFUc:-MeeI4Qp0wT6Ydf5nFUd:b-dp74zn) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L220)):*
> ```Go
> 		err = updateFn(ctx, txn)
> 		if err != nil {
> 			return errors.Errorf("failed to insert stats: %s", err)
> ```

wrap, not interpolate.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 252 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeIQV2B_XCz6- [...]

2021-07-15 14:10 UTC, maryliag reviewed
> Reviewed 2 of 7 files at r1, 1 of 22 files at r4, 8 of 14 files at r5, 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @jordanlewis)

___
*[pkg/sql/exec_util.go, line 840 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeePLe53jvy9usjlg9l:-MeePLe53jvy9usjlg9m:b-bxypxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b34c11cd531f50256a3990c663e08e39d5a08fc5/pkg/sql/exec_util.go#L840)):*
> ```Go
> 	MetaSQLStatsFlushDuration = metric.Metadata{
> 		Name:        "sql.stats.flush.duration",
> 		Help:        "Time took to complete SQL Stats flush",
> ```

nit: add the unit to the help too, so it's clear. "Time took in nanoseconds to complete..."


<!-- Sent from Reviewable.io -->

2021-07-16 19:45 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go, line 33 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mee6vtY0PVM9a3VzTzG:-Mefl4lGDiRairJq32Bj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go#L33)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

"if set, SQL execution statistics are periodically flushed to disk"
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeFGjk6rlP9RDxkop5:-Mekfoap6F4UYsPfi3aO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L41)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It seems backward to spawn new flush workers each time Flush is called.

The typical pattern that we use elsewhere is to have a single, always-on flush worker. That flush worker will listen on a `time.Ticker` that's configured with the cluster setting.

That way you can get rid of this extra `s.mu.state` thing - I think it will simplify the code significantly.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 41 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeAqzb96Y9HdixlR4f:-Mekfs-14t8QjCajKau4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L41)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Let's add a info log message when this happens.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 63 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeEn5H0lw2pOzk9iVU:-Meg9UDX-4WEr_6IQypi:b-1wxkwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L63)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think we should do these in 1 huge transaction - it's going to be really expensive and have contention issues. Remember, all nodes will be trying to do this stuff at the same time.

What is the value of using a transaction here at all? I think it is perfectly fine to do each flush statement separately.

Also, I'm somewhat concerned about the spikes in cluster load this will generate. It's an anti-pattern to have a big spike of writes and reads (and potentially contention) that occurs at a particular time interval, especially if that's going to be correlated across the cluster (imagine a cluster that restarts all at the same time - it'll all flush at around the same time, which is high load).

There are 2 patterns to deal with this.

1. Jitter the flush interval by adding a random value (-50% to +50%?) of the flush interval on run. This is straightforward, you should definitely do that.

2. We could also consider pacing the flushes. Instead of writing everything in one huge chunk, we could instead have an in-memory queue of stats to flush, and a worker goroutine whose job is simply to sit on the queue and flush each stat as it comes in. Then, we could add pacing to that worker thread, backpressure, etc. It's going to be hard to do that sort of thing the way this is set up right now - it's a very high level, batch API.
Also, this queue will allow some nice observability - we'll be able to see the queue's length in a metric.
</blockquote></details>

* Introduced jitter in the signal handling goroutine. 
* removed the spawning of the async task during the flush and implements dedicated goroutine that consumes two flush queues (one for stmtStats and one for txnStats)
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHQQGEyFr7NmdvXyQ:-Mefn1c861j_PJj4m1ZF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L137)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Use errors.Wrap to wrap an error, not string interpolation.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHW5T-0sozF6OkLqU:-Mefn2Mh6HbixheBSedt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L187)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto above.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 193 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeHxzD5xjiYfib8xbv:-MefnFci8yz5HZI7wlVj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L193)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You can just return err here. Even better, inline the return with the call to IterateStatementStats.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 220 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeI4Qp0wT6Ydf5nFUc:-Mefn4X-3ZpwZPLjL6fY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L220)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

wrap, not interpolate.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 252 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeIQV2B_XCz6-nxOu8:-MefiG4p25bZS_tBpSU0:bm1lgm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L252)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Rather than this on conflict, can't you instead do a normal insert? A normal insert will fail if it violates any unique constraints, which I think it would in this case, right?
</blockquote></details>

My thought here is that we want to distinguish unique constraints violation VS other type of errors, (e.g. system table unavailable). The `ON CONFLICT DO NOTHING` clause here ensures that if we encounters an error from the internal executor, we can be sure it is not related to unique constraint violation. 
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 482 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeCbQCD9R1tm_600ch:-Mekkq4q6arva9ZcXIBm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954090eacd4b066a0626a26c95/pkg/sql/sqlstats/persistedsqlstats/flush.go#L482)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why do this here but not in all of the places we're casting? Should pick one way or the other. Also, there are functions for this (`tree.MustBeD...`)

Also, this should be an assertion failure.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 534 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MeeDckgASJyg1-vdQZ-:-Mefi5f6CIBMnT0QUfZf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631c4efa67e0b9954 [...]

2021-07-20 03:49 UTC, jordanlewis requested changes
I suggest breaking the JSON stuff out into another PR so you can get it merged. In general I think this PR could be broken up a bit to help ease the review pipeline.

I'm thinking:

1. JSON stuff
2. the SQL methods - insert/update/select
3. the flusher routine and logic

Not a requirement, but I think it might help us get some more forward progress more quickly here, as this is a very large PR.

> Reviewed 4 of 25 files at r7, 1 of 25 files at r9, 25 of 25 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-:-Mf10iQh4cGTLcEWTpVL:b2ffwky)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/statement_statistics, line 4 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf06XTtD-te4F86_7kg:-Mf06XTtD-te4F86_7kh:biwvyop) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/logictest/testdata/logic_test/statement_statistics#L4)):*
> ```
> 
> # Disable SQL Stats flush to prevents stats from being cleared from the
> # in-memory store.
> ```

Why is this necessary?
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 31 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0vd8N3ysXdJbAxn-M:-Mf0vd8OE3wBoZ-8oYu9:bm89g7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L31)):*
> ```Go
> func (s *PersistedSQLStats) startSQLStatsFlushWorker(ctx context.Context, stopper *stop.Stopper) {
> 	_ = stopper.RunAsyncTask(ctx, "sql-stats-flush-worker", func(ctx context.Context) {
> 		for {
> ```

Given that we're processing these stat requests in a tight loop right now, I'm no longer so sure it makes a ton of sense to have this queue at all.

I think the simplest approach would be to remove the 2 extra goroutines after all, and just have the main SQL Stats goroutine do everything sequentially.

Having the extra goroutines... what does it really buy us? I mentioned something about being able to observe the queue length, but I'm not really sure that makes much sense, and you could provide that same metric without the extra goroutines just as easily.

Thoughts? Just trying to keep this code as simple as it can be. The more goroutines and channels, the more places bugs can hide, so if we don't really need the extra complexity, we shouldn't bother.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 55 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0W9bZ9esanUm72gH1:-Mf0W9bZ9esanUm72gH2:b-ne7kgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L55)):*
> ```Go
> 		if err != nil {
> 			s.cfg.FailureCounter.Inc(1)
> 			log.Warningf(ctx, "%s: %s", errMsg, err)
> ```

errMsg appears to always be nil here, unless I'm missing something.
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 449 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-HRs0ws_7OmLCpLM:-Mf1-HRs0ws_7OmLCpLN:b-3q4sbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L449)):*
> ```Go
> 	}
> 
> 	count := tree.MustBeDInt(row[0])
> ```

super nit: remove the newlines between these lines, they're not necessary
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 72 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-hQeAsarGXbTndVl:-Mf1-hQeAsarGXbTndVm:by4kh3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L72)):*
> ```Go
> 	cfg *Config
> 
> 	memoryPressureSignal chan struct{}
> ```

Comment on this.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 78 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-U917DnlpdqpCm3t:-Mf1-U917DnlpdqpCm3u:bw4rwmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L78)):*
> ```Go
> 
> 	mu struct {
> 		syncutil.RWMutex
> ```

There doesn't seem to be any use for this mutex any longer, lastFlushStarted is only written in one place and never read.

Once you re-add the readers if necessary, I don't think you need the complexity of RWMutex here.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 104 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-mo81F95Z5qLCRGS:-Mf1-mo81F95Z5qLCRGT:b-chb5h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L104)):*
> ```Go
> 
> func (s *PersistedSQLStats) startSQLStatsFlushLoop(ctx context.Context, stopper *stop.Stopper) {
> 	_ = stopper.RunAsyncTask(ctx, "sql-stats-signal-handler", func(ctx context.Context) {
> ```

Let's call this `sql-stats-worker`, since "signal handler" usually denotes a UNIX signal.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 121 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0XL3WEL0Vwp4co6iY:-Mf0XL3WEL0Vwp4co6iZ:b-jwad9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L121)):*
> ```Go
> 			var newDeadline time.Time
> 
> 			jitter := SQLStatsFlushJitter.Get(&s.cfg.Settings.SV)
> ```

Include a comment that explains this math.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 127 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf105WwCGzosPnNGF-R:-Mf105WwCGzosPnNGF-S:bua6boc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L127)):*
> ```Go
> 
> 			now := s.getTimeNow()
> 			newDeadline = now.Add(flushInterval)
> ```

Since we've added the jitter, I don't think there's any reason to keep the equality check. I think this should be changed to `resetTimer`, since we'll always be resetting it unless I'm mistaken. Then, you can also get rid of some of this logic and unconditionally do `timer.Reset(flushInterval)`, no?
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 157 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0YIWA5eLn4fR48W0g:-Mf0YIWA5eLn4fR48W0h:bnqkkkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L157)):*
> ```Go
> 
> // StartFlush puts in-memory statistics into a flush queue, which is processed
> // by sql-stats-flush-worker goroutine.
> ```

Add the information about what this function returns.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 159 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0zbSjCM31nOqeZYXd:-Mf0zbSjCM31nOqeZYXe:bmxud2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L159)):*
> ```Go
> // by sql-stats-flush-worker goroutine.
> func (s *PersistedSQLStats) StartFlush(ctx context.Context) uint64 {
> 	log.Infof(ctx, "start to flush sql stats")
> ```

This should have more info - ("flushing %d sql stats after %s", len(stats), time.Since(lastFlush))
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 163 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0Y12xB8FOwpLU9RjP:-Mf0Y12xB8FOwpLU9RjQ:bey1p6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L163)):*
> ```Go
> 	err := s.IterateStatementStats(ctx, &sqlstats.IteratorOptions{}, func(_ context.Context, statistics *roachpb.CollectedStatementStatistics) error {
> 		numOfStatsInQueue++
> 		s.stmtStatsCh <- *statisti [...]

2021-07-21 17:37 UTC, Azhng reviewed
* Split out the JSON encoding PR: #67805. 
* Split out flush logic itself PR: #67866.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-:-Mf8fC609plna-pzIHKV:bfh3ved)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/statement_statistics, line 4 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf06XTtD-te4F86_7kg:-Mf4CNrUBvS1VXDYrknr:b-thwgbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/logictest/testdata/logic_test/statement_statistics#L4)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

This logic test tests the discarding behaviour of in-memory sql-stats when the fingerprint limit has been reached. Specifically, it ensures that when the fingerprint limit has been reached:
1. new fingerprints will be discarded
2. the stats continuously being updated for existing fingerprints

The new flush mechanism will clear out the in-memory stores which makes it difficult to test this behaviour. 
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 31 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0vd8N3ysXdJbAxn-M:-Mf4D1_v4Wcxz73-3eW2:b4wmdel) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L31)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Given that we're processing these stat requests in a tight loop right now, I'm no longer so sure it makes a ton of sense to have this queue at all.

I think the simplest approach would be to remove the 2 extra goroutines after all, and just have the main SQL Stats goroutine do everything sequentially.

Having the extra goroutines... what does it really buy us? I mentioned something about being able to observe the queue length, but I'm not really sure that makes much sense, and you could provide that same metric without the extra goroutines just as easily.

Thoughts? Just trying to keep this code as simple as it can be. The more goroutines and channels, the more places bugs can hide, so if we don't really need the extra complexity, we shouldn't bother.
</blockquote></details>

I think further simplify this into one goroutine is a good idea for this stage to ensure the correctness of the flush logic.

Created additional issue tracking the batching insert idea we discussed offline: https://github.com/cockroachdb/cockroach/issues/67867
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 55 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0W9bZ9esanUm72gH1:-Mf4GUkG432drMu2yIXH:b-r13nwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L55)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

errMsg appears to always be nil here, unless I'm missing something.
</blockquote></details>

`errMsg` is passed in from the arguments and it's always set by either `doFlushSingleStmtStats` or `doFlushSingleTxnStats`. 
___
*[pkg/sql/sqlstats/persistedsqlstats/flush.go, line 449 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-HRs0ws_7OmLCpLM:-Mf4_oWq9awIJaH58ZT9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/flush.go#L449)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

super nit: remove the newlines between these lines, they're not necessary
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 72 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-hQeAsarGXbTndVl:-Mf5bF5O2-9P6kxw4GXi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L72)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Comment on this.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 78 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-U917DnlpdqpCm3t:-Mf4_sZ30bV-Zsnqsh0e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L78)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

There doesn't seem to be any use for this mutex any longer, lastFlushStarted is only written in one place and never read.

Once you re-add the readers if necessary, I don't think you need the complexity of RWMutex here.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 104 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf1-mo81F95Z5qLCRGS:-Mf4_twqCn8OEOb6T8Gc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L104)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Let's call this `sql-stats-worker`, since "signal handler" usually denotes a UNIX signal.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 121 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0XL3WEL0Vwp4co6iY:-Mf8bcCR3lfwjzsAFvNv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L121)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Include a comment that explains this math.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 127 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf105WwCGzosPnNGF-R:-Mf8baisCROY0Smf93Fz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L127)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Since we've added the jitter, I don't think there's any reason to keep the equality check. I think this should be changed to `resetTimer`, since we'll always be resetting it unless I'm mistaken. Then, you can also get rid of some of this logic and unconditionally do `timer.Reset(flushInterval)`, no?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 157 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0YIWA5eLn4fR48W0g:-Mf4n9p01izm9EjA89Xg:bgcw1hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L157)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add the information about what this function returns.
</blockquote></details>

Since `StartFlush()` is now synchronous, it's not returning anything. 
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 159 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-Mf0zbSjCM31nOqeZYXd:-Mf4ow9y7t1bh4VMZyWH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0675c7c7da598a4d4aba5bec905d8ebba03f0728/pkg/sql/sqlstats/persistedsqlstats/provider.go#L159)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This should have more info - ("flushing %d sql stats after %s", len(stats), time.Since(lastFlush))
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 163 [...]

2021-07-26 23:14 UTC, Azhng commented
TPCC-1000 Benchmark on 3-node roachprod (16 vCPU each):

This PR:

```
Audit check 9.2.1.7: PASS
Audit check 9.2.2.5.1: PASS
Audit check 9.2.2.5.2: PASS
Audit check 9.2.2.5.3: PASS
Audit check 9.2.2.5.4: PASS
Audit check 9.2.2.5.5: PASS
Audit check 9.2.2.5.6: PASS

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    12586.2  97.9%     30.3     22.0     28.3     35.7     60.8   4563.4

```



```

Audit check 9.2.1.7: PASS
Audit check 9.2.2.5.1: PASS
Audit check 9.2.2.5.2: PASS
Audit check 9.2.2.5.3: PASS
Audit check 9.2.2.5.4: PASS
Audit check 9.2.2.5.5: PASS
Audit check 9.2.2.5.6: PASS

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 7200.0s    12583.8  97.9%     28.3     21.0     28.3     33.6     58.7   3892.3

```

Seems like the impact increasing the avg latency by 2ms. 

TPCC runs for 2 hours and I changed the flush interval to 15 mins so it's easier to observe through custom time series chart:

Total flush count:

<img width="1025" alt="Screen Shot 2021-07-26 at 19 10 19" src="https://user-images.githubusercontent.com/9267198/127070677-e0e1d184-b8cf-4d5f-80f8-b304c06dde12.png">


Average flush duration: 

<img width="990" alt="Screen Shot 2021-07-26 at 19 10 36" src="https://user-images.githubusercontent.com/9267198/127070712-5bf9aa52-92bd-4d16-8953-2a8907646861.png">

In-memory footprint 

<img width="990" alt="Screen Shot 2021-07-26 at 19 10 41" src="https://user-images.githubusercontent.com/9267198/127070746-ac6a925e-69cb-48af-92bf-63087545b963.png">


cc: @jordanlewis

2021-07-27 14:40 UTC, jordanlewis commented
Very nice!

The average flush duration seems a little suspicious - 20 microseconds is too fast for an entire roundtrip to SQL. Can you double check that?

2021-07-27 16:28 UTC, Azhng commented
Ah good catch. Seems like I used the wrong Histogram. Updated!

<img width="1044" alt="Screen Shot 2021-07-27 at 12 25 02" src="https://user-images.githubusercontent.com/9267198/127191691-91ff1468-a754-402f-ac43-77bdfcece97b.png">

Flush duration chart with 10s flush interval ^

2021-08-03 13:54 UTC, Azhng commented
I gathered more data from the master branch and the flush branch (with different flush interval configured) using TPCC-1000.

It seems like we are not creating too much impact in terms of latency. Master averages 59.05ms p99 latency, the flush15 (15 mins flush interval) and flush60 averages 59.79ms and 60.27ms p99 latency respectively. The increase of p99 latency is below 2ms.

Though I'm choosing to ignore the pMax latency here because it seems like we are seeing a huge fluctuation of its value even on the master branch. So it serves as a poor indicator of the overall performance. 

```
# experiement  elapsed    tpmC     efc       avg(ms)  p50(ms)  p90(ms)  p95(ms)  p99(ms)pMax(ms)
master 1       7200.0s    12583.8  97.9%     28.3     21.0     28.3     33.6     58.7   3892.3
master 2       7200.0s    12588.1  97.9%     31.0     22.0     29.4     33.6     60.8   6979.3
master 3       7200.0s    12588.8  97.9%     30.1     22.0     29.4     35.7     58.7   4563.4
master 4       7200.0s    12585.5  97.9%     33.5     21.0     28.3     33.6     60.8   6442.5
master 5       7200.0s    12589.9  97.9%     28.9     19.9     25.2     30.4     54.5   6710.9
master 6       7200.0s    12592.3  97.9%     29.3     22.0     28.3     33.6     60.8   4295.0

flush 15min 1  7200.0s    12586.2  97.9%     30.3     22.0     28.3     35.7     60.8   4563.4
flush 15min 2  7200.0s    12587.8  97.9%     33.6     21.0     28.3     32.5     58.7   8053.1
flush 15min 3  7200.0s    12589.8  97.9%     27.5     21.0     27.3     31.5     54.5   3758.1
flush 15min 4  7200.0s    12582.1  97.8%     30.3     22.0     29.4     35.7     62.9   4563.4
flush 15min 5  7200.0s    12584.7  97.9%     34.8     22.0     29.4     35.7     62.9   7247.8

flush 60min 1  7200.0s    12586.6  97.9%     30.6     22.0     30.4     37.7     65.0   4563.4
flush 60min 2  7200.0s    12591.6  97.9%     27.9     19.9     26.2     30.4     54.5   4295.0
flush 60min 3  7200.0s    12589.6  97.9%     32.9     21.0     27.3     32.5     56.6   6442.5
flush 60min 4  7200.0s    12587.4  97.9%     29.0     21.0     28.3     33.6     65.0   4563.4

```

Overall I think this is good news for us. I think the next step for me is to try to overload the cluster and see how the performance varies.

2021-08-05 21:42 UTC, matthewtodd requested changes
nit: Maybe remove the big First Commit header from the PR description now?

> Reviewed 5 of 7 files at r23, 23 of 23 files at r24.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-:-MgNCe7u45YrKd_MrLfX:b-vm37on)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @jordanlewis, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 100 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNE4D_Bm9WhX0xivRr:-MgNE4D_Bm9WhX0xivRs:b-nghhad) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L100)):*
> ```Go
> 			select {
> 			case <-resetIntervalChanged:
> 				// Recalculate flush interval.
> ```

IIUC, in this case we stop waiting, flush immediately, and then the post statement of the for loop calculates the next flush interval / wait period, yes? That might be worth spelling out a bit more in this comment. I had to scratch my head for a bit.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 103 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNF9gn2KIFFsSskwjO:-MgNF9gn2KIFFsSskwjP:b-u3l70d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L103)):*
> ```Go
> 				continue
> 			case <-timer.C:
> 				timer.Read = true
> ```

This is the "normal" case, right? Can we put it first in the list?
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 104 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNEk-Z91YEsf4zpGcA:-MgNEk-Z91YEsf4zpGcB:b-f1pigx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L104)):*
> ```Go
> 			case <-timer.C:
> 				timer.Read = true
> 			case <-s.memoryPressureSignal:
> ```

I could use a comment here, too. Would it be something like, "We're experiencing memory pressure, so flush SQL stats to disk immediately, rather than waiting the full flush interval, in an attempt to relieve some of that pressure?"
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 120 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNFWjQAwqGVmIctktE:-MgNFWjQAwqGVmIctktF:b1liij3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L120)):*
> ```Go
> // [(1 - SQLStatsFlushJitter) * SQLStatsFlushInterval),
> //  (1 + SQLStatsFlushJitter) * SQLStatsFlushInterval)]
> func (s *PersistedSQLStats) getWaitPeriod() time.Duration {
> ```

I see how (with the jitter) this is different from the "flush interval," but I wonder if reusing those words would help clarify a little more. So maybe this method could be called `nextFlushInterval` or something?


<!-- Sent from Reviewable.io -->

2021-08-06 16:00 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @maryliag, and @matthewtodd)

___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 100 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNE4D_Bm9WhX0xivRr:-MgR8m_PAhztICq2ldTn:b-1nj3lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L100)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

IIUC, in this case we stop waiting, flush immediately, and then the post statement of the for loop calculates the next flush interval / wait period, yes? That might be worth spelling out a bit more in this comment. I had to scratch my head for a bit.
</blockquote></details>

In this case, we would stop waiting but we **do not** flush immediately. The `continue` here would cause the loop to restart and skip the flush. I'll add a comment here.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 103 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNF9gn2KIFFsSskwjO:-MgRAQZ2Aw-BHev9WJsC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L103)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

This is the "normal" case, right? Can we put it first in the list?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 104 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNEk-Z91YEsf4zpGcA:-MgRAZKQ53jaMXLTYg40:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L104)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I could use a comment here, too. Would it be something like, "We're experiencing memory pressure, so flush SQL stats to disk immediately, rather than waiting the full flush interval, in an attempt to relieve some of that pressure?"
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 120 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNFWjQAwqGVmIctktE:-MgRAjnG9uwdUBXum2Er:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L120)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I see how (with the jitter) this is different from the "flush interval," but I wonder if reusing those words would help clarify a little more. So maybe this method could be called `nextFlushInterval` or something?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 16:26 UTC, matthewtodd reviewed
> Reviewed 7 of 7 files at r25.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @jordanlewis, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 100 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNE4D_Bm9WhX0xivRr:-MgRFP1OERjsbRuE5BuO:boiv8gx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L100)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

In this case, we would stop waiting but we **do not** flush immediately. The `continue` here would cause the loop to restart and skip the flush. I'll add a comment here.
</blockquote></details>

Oh, I see. That's interesting. I'm curious to know if there's a particular reason we don't flush here; is there something we're trying to protect against?


<!-- Sent from Reviewable.io -->

2021-08-06 16:44 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @maryliag, and @matthewtodd)

___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 100 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNE4D_Bm9WhX0xivRr:-MgRL4UO1YbchU-7bkQe:bw7vv9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L100)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Oh, I see. That's interesting. I'm curious to know if there's a particular reason we don't flush here; is there something we're trying to protect against?
</blockquote></details>

The reset interval change occurs when users run `SET CLUSTER SETTING sql.stats.flush.interval = ...` command. I think this would be a bit of unexpected if resetting this cluster setting causes flush to happen, since neither the timer has fired nor has the memory limit has been reached. 


<!-- Sent from Reviewable.io -->

2021-08-06 16:48 UTC, matthewtodd reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/provider.go, line 100 at r24](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-MgNE4D_Bm9WhX0xivRr:-MgRMIP067b8ClKsjqU7:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e64f0cc79c3fcfe287215cbcdca4054e5380d763/pkg/sql/sqlstats/persistedsqlstats/provider.go#L100)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The reset interval change occurs when users run `SET CLUSTER SETTING sql.stats.flush.interval = ...` command. I think this would be a bit of unexpected if resetting this cluster setting causes flush to happen, since neither the timer has fired nor has the memory limit has been reached. 
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2021-08-10 16:48 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67090#-:-MgkqCUB0mnsNzhC6GEW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @maryliag)



<!-- Sent from Reviewable.io -->

2021-08-10 16:50 UTC, Azhng commented
TFTR!

bors r+

2021-08-10 19:54 UTC, merged