rowexec: add comments around joinReaderStrategies
cockroachdb/cockroach pull request #67095
Opened 2021-06-30 22:00 UTC by andreimatei

This patch adds comments around areas I have found confusing in the
joinReader and friends implementation. Particularly around the
management of the ordering guarantees in different cases.
Thanks Sumeer for explaining some things.

Release note: None

2021-06-30 22:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67095)
<!-- Reviewable:end -->

2021-06-30 22:18 UTC, RaduBerinde reviewed
Great explanations, thanks!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-MdU-9KV6oRUr0RVugDW:bq0uran)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @cucaroach, @jordanlewis, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/row/kv_batch_fetcher.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTwYMaEN5QQf74tFWH:-MdTwYMaEN5QQf74tFWI:b-nwci0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/row/kv_batch_fetcher.go#L113)):*
> ```Go
> 
> // getBatchSize returns the max size of the next batch. The size is expressed in
> // number of result rows.
> ```

This is number of keys, not rows (this is what we set `MaxSpanRequestKeys` to)
___
*[pkg/sql/rowexec/joinreader.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTx7iT6BVJrudKPbBD:-MdTx7iT6BVJrudKPbBE:br2ajlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader.go#L233)):*
> ```Go
> 		// parallelism for its lookup batches and setting row and memory limits (due
> 		// to implementation limitations, you can't have both at the same time). We
> 		// choose parallelism when we know that the number of requests in a batch
> ```

[nit] The "relation to" stuff sounds a bit more general than what we're actually doing. I'd say `we choose parallelism when we know that each lookup returns at most one row (i.e. the lookup columns form a "key" in the target table). Note that this is always the case for index joins.`
___
*[pkg/sql/rowexec/joinreader.go, line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTz3hYCztjAopmO49h:-MdTz3hYCztjAopmO49i:b-9qnn0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader.go#L696)):*
> ```Go
> 	}
> 
> 	// Sort the spans for the following cases:
> ```

Did you mean to remove this block of code?
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTzB9H4i67ws9GqheT:-MdTzB9H4i67ws9GqheU:b-dnt32m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader_strategies.go#L35)):*
> ```Go
> // rows from pairs of joined rows.
> //
> // There's 3 implementations of joinReaderStrategy:
> ```

[nit] There are
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTzmJh0K5fV7_369dT:-MdTzmJh0K5fV7_369dU:bwj939s) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader_strategies.go#L376)):*
> ```Go
> // - the input side has rows 1, 2, 3, 4.
> // - the lookup side has rows red, blue.
> // - the join needs to produce the pairs (1, red), (2, blue), (3, blue),
> ```

Cool idea to use numbers for one side and colors for the other.


<!-- Sent from Reviewable.io -->

2021-06-30 22:42 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @jordanlewis, @RaduBerinde, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/row/kv_batch_fetcher.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTwYMaEN5QQf74tFWH:-MdU1a5M9TORY8pqi36k:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/row/kv_batch_fetcher.go#L113)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is number of keys, not rows (this is what we set `MaxSpanRequestKeys` to)
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader.go, line 233 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTx7iT6BVJrudKPbBD:-MdU2DRW01wWvro3xbr3:bgign3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader.go#L233)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] The "relation to" stuff sounds a bit more general than what we're actually doing. I'd say `we choose parallelism when we know that each lookup returns at most one row (i.e. the lookup columns form a "key" in the target table). Note that this is always the case for index joins.`
</blockquote></details>

done, but left the words aroudn `LookupColumnsAreKey` to highlight the difference between exactly-one and at-most-one.
___
*[pkg/sql/rowexec/joinreader.go, line 696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTz3hYCztjAopmO49h:-MdU2WDNDIE0rYRq0p-d:bogsb27) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader.go#L696)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Did you mean to remove this block of code?
</blockquote></details>

yes, thanks
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTzB9H4i67ws9GqheT:-MdU2fMZBOuc8mvL6HYf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader_strategies.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] There are
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdTzmJh0K5fV7_369dT:-MdU2h_G2ZVwOEQXBmqy:b7zrc6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c94600ac3a86815be217cfbad2a62a3f345ae83/pkg/sql/rowexec/joinreader_strategies.go#L376)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Cool idea to use numbers for one side and colors for the other.
</blockquote></details>

Summer kept saying something about red and blue. Took me a minute to figure out what he's talking about :). I thought it's a canonical thing so I searched for red/blue around here, but I couldn't find anything. Maybe that's just how he thinks.


<!-- Sent from Reviewable.io -->

2021-07-01 00:55 UTC, sumeerbhola approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-MdUYL5r6XH_lWFHWaNc:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @cucaroach, @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdUWGj-1yK_zHCUunxi:-MdUWGj-1yK_zHCUunxj:b-ddb01i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L43)):*
> ```Go
> // - joinReaderIndexJoinStrategy: used when we're performing a join between an
> //   index and the table's PK. This guy is the simplest and the most efficient
> //   because it doesn't actually join anything - it directly emits the PK rows.
> ```

Can you add here that this strategy is used for both the ordering and no-ordering case, and is oblivious to it. The ordering is handled by the fact that `joinReader` does not sort the lookup spans.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdUWk-W0S88sNTB3BbD:-MdUWk-W0S88sNTB3BbE:b-ade8iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L89)):*
> ```Go
> // Consider the following example:
> // - the input side has rows 1, 2, 3, 4.
> // - the lookup side has rows red, blue.
> ```

this is a little confusing to me since it is not clear what column we are joining over.
The example I had in mind during our VC (which I wasn't explaining very clearly) was
(1, red), (2, blue), (3, blue), (4, red) on the input, where the join is going to use the color column to do the lookup and the looked up rows are (red, some more stuff), (blue, some more stuff).


<!-- Sent from Reviewable.io -->

2021-07-01 11:45 UTC, cucaroach requested changes
Nice improvements.

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-MdWsbPm79Ap3atmaLEy:b-kzhh65)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWpy58DBdcMIofno7c:-MdWpy58DBdcMIofno7d:b-9r4nju) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L42)):*
> ```Go
> //   more buffering to deal with out-of-order looked-up rows.
> // - joinReaderIndexJoinStrategy: used when we're performing a join between an
> //   index and the table's PK. This guy is the simplest and the most efficient
> ```

Maybe s/guy/one/
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWrrxh-ZNspm_n7Q9X:-MdWrrxh-ZNspm_n7Q9Y:bc4ju7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
> ```Go
> //
> // Say the joinReader looks up rows in order: red, then blue. Once red is
> // fetched, it is handed to joinReaderNoOrderingStrategy.processLookedUpRow(), which will match
> ```

s/joinReaderNoOrderingStrategy/joinReaderOrderingStrategy/.  unless there's some delegation going on that I'm not aware of.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWs8Wo7DAL2oDXlSBP:-MdWs8Wo7DAL2oDXlSBQ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L385)):*
> ```Go
> // (well, (1, red) could be emitted, but we're not smart enough). So, they are
> // buffered until all joined rows are produced. Then the joinReader will hand in
> // blue, for which the joinReaderNoOrderingStrategy produces (2, blue) and (3,
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-07-01 12:49 UTC, rytaft reviewed
Thanks for making this code easier to understand!

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-MdX6DaP-k7wQcS6gdqc:bjlyyw2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX1SRH63qXSmt0g_HH:-MdX1SRH63qXSmt0g_HI:b4ubly7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader.go#L82)):*
> ```Go
> 	// ordering of the input stream. This is applicable to both lookup joins and
> 	// index joins. Maintaining ordering with lookup joins is expensive. With
> 	// index joins, not maintaining ordering allows for optimizations at lower
> ```

By "lower layers" do you mean inside kv? This could also be interpreted as lower down in the query plan.
___
*[pkg/sql/rowexec/joinreader.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX2hJR0uXtMwCF3mz5:-MdX2hJR0uXtMwCF3mz6:b5ufmvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader.go#L682)):*
> ```Go
> 	//    fetcher only accepts a limit if the spans are sorted), and
> 	// b) Pebble has various optimizations for Seeks in sorted order.
> 	if !(jr.readerType == indexJoinReaderType && jr.maintainOrdering) {
> ```

nit: I would change this to `if jr.readerType == indexJoinReaderType && jr.maintainOrdering {` and put the sort in the `else`. I think it would be a bit easier to understand.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX47cKBjcvuVg62TtO:-MdX47cL3kTnCeLS_Irp:bjzaitk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L28)):*
> ```Go
> // cooperates with a joinReaderStrategy to produce joined rows. More
> // specifically, the joinReader processes rows from the input-side, passes those
> // rows to the joinReaderStrategy.processLookupRow() which (usually) holds on to
> ```

nit: processLookupRow() -> processLookupRows()
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX4bGfDd6-xo_82HH2:-MdX4bGfDd6-xo_82HH3:b-uc7zxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L58)):*
> ```Go
> 	// the current batch of input rows.
> 	generatedRemoteSpans() bool
> 	// processLookupRows consumes the rows the joinReader has buffered returns the
> ```

nit: "has buffered returns" -> "has buffered and returns"
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX5NSxE6DIUuJ1Cmvb:-MdX5NSxE6DIUuJ1Cmvc:b-pvnn39) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
> ```Go
> //
> // Say the joinReader looks up rows in order: red, then blue. Once red is
> // fetched, it is handed to joinReaderNoOrderingStrategy.processLookedUpRow(), which will match
> ```

nit: funky line wrapping


<!-- Sent from Reviewable.io -->

2021-07-01 15:59 UTC, RaduBerinde approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-MdXmwF7C0H56VhsahC-:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-07-01 16:16 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @cucaroach, @jordanlewis, @RaduBerinde, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX1SRH63qXSmt0g_HH:-MdXnj-UCvrrt0zYlTM7:bh3pck1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader.go#L82)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

By "lower layers" do you mean inside kv? This could also be interpreted as lower down in the query plan.
</blockquote></details>

I had copied this from the `JoinReaderSpec` proto. I've now clarified the language in both places.
___
*[pkg/sql/rowexec/joinreader.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX2hJR0uXtMwCF3mz5:-MdXoS-61knlMOTc44om:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader.go#L682)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: I would change this to `if jr.readerType == indexJoinReaderType && jr.maintainOrdering {` and put the sort in the `else`. I think it would be a bit easier to understand.
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX47cKBjcvuVg62TtO:-MdXo_0AC6OjP5QIqUVI:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: processLookupRow() -> processLookupRows()
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 42 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWpy58DBdcMIofno7c:-MdXobcK-mK5Jno3XACi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L42)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Maybe s/guy/one/
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdUWGj-1yK_zHCUunxi:-MdXoxzQ8hGG4NuZ1nvb:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L43)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you add here that this strategy is used for both the ordering and no-ordering case, and is oblivious to it. The ordering is handled by the fact that `joinReader` does not sort the lookup spans.
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX4bGfDd6-xo_82HH2:-MdXp14v-GKxI3G6KGHZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L58)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "has buffered returns" -> "has buffered and returns"
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdUWk-W0S88sNTB3BbD:-MdXq4N76V_OuKEA1nsu:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L89)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this is a little confusing to me since it is not clear what column we are joining over.
The example I had in mind during our VC (which I wasn't explaining very clearly) was
(1, red), (2, blue), (3, blue), (4, red) on the input, where the join is going to use the color column to do the lookup and the looked up rows are (red, some more stuff), (blue, some more stuff).
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWrrxh-ZNspm_n7Q9X:-MdXqA-l5jNw-GULW_LM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

s/joinReaderNoOrderingStrategy/joinReaderOrderingStrategy/.  unless there's some delegation going on that I'm not aware of.
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdX5NSxE6DIUuJ1Cmvb:-MdXqBkhAUd1ZEcH9FBx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: funky line wrapping
</blockquote></details>

done
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 385 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-MdWs8Wo7DAL2oDXlSBP:-MdXqDz4ChXmQ_5M4ybR:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9a92fd8f9a198434ae736c8027f61e8886f81ca/pkg/sql/rowexec/joinreader_strategies.go#L385)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-07 19:33 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-Me1STBN33qBSv31R4Pe:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @jordanlewis, @RaduBerinde, @rytaft, @sumeerbhola, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-07-07 19:58 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> sorry just noticed one small thing below

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-Me1Y5L97U1x24z_ADhJ:b-u865my)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei, @cucaroach, @jordanlewis, @RaduBerinde, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-Me1Xlk31do4Ja20rMEE:-Me1Xlk31do4Ja20rMEF:b-p7uh6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28dfe1dbb5efdff3667040e5a8df516daab7b77/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
> ```Go
> // - the lookup side has rows (red, x), (blue, y).
> // - the join needs to produce the pairs (1, x), (2, y), (3, y), (4, x), in any
> //   order.
> ```

nit: shouldn't this say: "in that order" instead of "in any order"?


<!-- Sent from Reviewable.io -->

2021-07-07 20:07 UTC, andreimatei reviewed
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-Me1_AOe2Kujni6bFZXE:b-ydi9aw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei, @cucaroach, @jordanlewis, @RaduBerinde, @sumeerbhola, and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-07-07 20:10 UTC, andreimatei reviewed
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-:-Me1_ptq6nqzG-5V_lHT:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @cucaroach, @jordanlewis, @RaduBerinde, @rytaft, @sumeerbhola, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader_strategies.go, line 380 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67095#-Me1Xlk31do4Ja20rMEE:-Me1_ob56LnGPPU0KU7R:babd9e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e28dfe1dbb5efdff3667040e5a8df516daab7b77/pkg/sql/rowexec/joinreader_strategies.go#L380)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: shouldn't this say: "in that order" instead of "in any order"?
</blockquote></details>

fixed, thanks


<!-- Sent from Reviewable.io -->

2021-07-07 21:44 UTC, merged