builtins: add crdb_internal.read/write_file
cockroachdb/cockroach pull request #67427
Opened 2021-07-09 15:23 UTC by dt

Release note: none.

2021-07-09 15:23 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67427)
<!-- Reviewable:end -->

2021-07-09 15:28 UTC, pbardea approved these changes
LGTM with minor doc comment

2021-07-09 15:28 UTC, pbardea commented on pkg/sql/sem/builtins/builtins.go
> +			Info:       "Read the content of a file at an external storage URI",
This needs updating for Write rather than read

2021-07-10 16:08 UTC, knz requested changes
huh admin only perhaps?

2021-07-10 16:13 UTC, dt commented
@knz heh, yep, that's why I added the blocking label and added reviewer yesterday: going to discuss it next week to determine if we should match `IMPORT` -- admin-only for reads to arbitrary endpoints or using host auth -- or just blanket admin-only.

2021-07-10 16:29 UTC, dt commented
Actually, on second though, this is just a debugging tool -- just always admin-only seems fine rather than bike shedding something more granular/complex.

Updated and RFAL.

2021-07-14 12:17 UTC, knz reviewed
LGTM, but please add a release note with tag "security update" to report that these new admin-only functions can access/write files out of the process.

> Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67427#-:-MeZwcdN1hekeYrX8Z0h:bify0ec)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @ajwerner, and @dt)



<!-- Sent from Reviewable.io -->

2021-07-14 12:17 UTC, knz approved these changes

2021-07-14 13:20 UTC, dt commented
@knz does the fact that an admin could already use IMPORT to read  arbitrary remote files, or use EXPORT to write them, affect your determination as to if we need the extra warning?

2021-07-22 00:28 UTC, dt commented
TFTRs!

bors r+

2021-07-22 02:10 UTC, merged