CRDB sql shell telemetry counter
cockroachdb/cockroach pull request #67606
Opened 2021-07-14 15:29 UTC by e-mbrown

This change allows us to keep track of
connections made using our internal SQl shell.

Release note: None

2021-07-14 15:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67606)
<!-- Reviewable:end -->

2021-07-14 21:05 UTC, arulajmani reviewed
I haven't looked at the change itself, but I have a drive-by comment about the PR title -- by convention, we try to prefix the PR title with the affected package. So in this case, it could look something like `sql: add sql shell telemetry counter`. 

There's a full set of guidelines on the wiki around commit messages https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-:-MeaoKjmDmwCcVSW4oPx:b-7jcxtb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)



<!-- Sent from Reviewable.io -->

2021-07-15 20:05 UTC, rafiss requested changes
i thought a bit more about how to test this:

could you add a test to pkg/sql/telemetry_test.go. it can be named `TestTelemetryRecordCockroachShell` it should work like this:

1. start a test server like this:
```
		var test telemetryTest
		test.Start(t, []base.TestServerArgs{{}})
		defer test.Close()
```
(for example, see similar code in pkg/sql/sqltestutils/telemetry.go `TelemetryTest`)

2. create a connection string that manually sets an application_name of `$ cockroach internal test`
```
sqlutils.PGUrl(t, test.cluster.Server(0).ServingSQLAddr(), "TestTelemetryRecordCockroachShell", url.User("root"))
```
this gives you back a URL, and you can call `url.Query().Add()` to add an "application_name" option


3. create a new connection to the database with this connection string
call `gosql.Open("postgres", url.String())`
you can see an example in pkg/testutils/serverutils/test_server_shim.go `OpenDBConnE`

4. make sure the new counter was incremented
use this to make telemetry get reported
```
reporter := test.server.DiagnosticsReporter().(*diagnostics.Reporter)
reporter.ReportDiagnostics()
```

then look inside of `test.diagSrv.LastRequestData()` to check for the `sql.cockroach_cli` key. this part will be tricky! you will have to read the documentation to understand how to access the data, but let me know if you aren't sure where to look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-:-MefgcnB0HK-UKN4evXp:b-63zpc7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[pkg/sql/pgwire/server.go, line 826 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Meffign2IwJkb906Vlk:-Meffign2IwJkb906Vll:b-i4yzks) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad2a52b55341302b06b22a76d3a4d71bd27d1e3/pkg/sql/pgwire/server.go#L826)):*
> ```Go
> 
> 	if appName, ok := args.SessionDefaults["application_name"]; ok {
> 		if strings.HasPrefix(appName, "$") {
> ```

nit: instead of using the "$" directly, it's better to refer to a constant. (finding the name of that constant can be a whole challenge too..) but in this case, use `catconstants.ReportableAppNamePrefix`
___
*[pkg/sql/sqltelemetry/session.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MefgAH43Re1O2rLbnS0:-MefgAH5-4OvO7cD2EeR:bjeao4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad2a52b55341302b06b22a76d3a4d71bd27d1e3/pkg/sql/sqltelemetry/session.go#L34)):*
> ```Go
> // CockroachCliExec is to be incremented every time a
> //statement is executed via the SQL shell
> var CockroachCliExec = telemetry.GetCounter("sql.cockroach_cli_exec")
> ```

nit: since this PR doesn't add the Exec tracking yet, cane you remove the `exec` counter from this commit?


<!-- Sent from Reviewable.io -->

2021-07-20 15:18 UTC, knz commented
> use this to make telemetry get reported

I would use another of the feature counter tests instead. `ReportDiagnostics` is a bit complicated to use, it's possible to look at the feature counters directly.

2021-07-22 16:41 UTC, rafiss requested changes
pro-tip: in your PR body can you add a line like "Fixes #62208"

this will link your PR to the issue, and when the PR is closed, it will automatically close the issue

see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-:-MfE3hkK41zvJn4jqn7J:bqgc64h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @knz)

___
*[pkg/sql/telemetry_test.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE1D6v3UziH6WhtExl:-MfE1D6v3UziH6WhtExm:b-j8pt69) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L86)):*
> ```Go
> 	q.Add("application_name", "$ cockroach internal test")
> 	pgUrl.RawQuery = q.Encode()
> 	fmt.Println(pgUrl)
> ```

nit: remove this Println
___
*[pkg/sql/telemetry_test.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE-WlA0qNmhABA1TT_:-MfE-WlA0qNmhABA1TTa:b-4cws2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L90)):*
> ```Go
> 	db, err := gosql.Open("postgres", pgUrl.String())
> 	if err != nil {
> 		//return nil, err
> ```

nit: remove commented line
___
*[pkg/sql/telemetry_test.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE-xdhBZBjhYOkXYmz:-MfE-xdhBZBjhYOkXYn-:bx05vzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L95)):*
> ```Go
> 	defer db.Close()
> 
> 	var app string
> ```

nit: it would be more clear to name this `appName`
___
*[pkg/sql/telemetry_test.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE-_Cd-tt_TrKOHzIA:-MfE-_Cd-tt_TrKOHzIB:bymg3ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L96)):*
> ```Go
> 
> 	var app string
> 	db.QueryRow("SHOW application_name").Scan(&app)
> ```

nit: this queries the variable, but doesn't do anything with it
after this you can add a line like 

```
require.Equal("$ cockroach internal test", appName)
```

which will make sure the app is what you expect
___
*[pkg/sql/telemetry_test.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE1yKn0XzuY46NV_GA:-MfE1yKo9XNsWMEeiVPx:bw6jnm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L103)):*
> ```Go
> 	last := diagSrv.LastRequestData()
> 	fmt.Printf("%v", last)
> 	//require.Equal(t, appName, last.)
> ```

thanks to knz's helpful comment, it seems like we have a better way of checking of the feature counter was incremented

you can perform this query:
```
SELECT usage_count
  FROM crdb_internal.feature_usage
 WHERE feature_name = 'sql.cockroach_cli';
```

and verify that `usage_count` is equal to 1.

the way to do this query is very similar to how you did QueryRow above. except instead of using a `string` value in `Scan()` you should use an `int` value.



with this approach, we no longer need the `diagSrv`, the `reporter`, the `tempExternalIODir`, or any of the more complicated setup in the beginning of this test. you should be able to change the cluster setup to just this line

```
	cluster := serverutils.StartNewTestCluster(t, 1, base.TestClusterArgs{})
```

i didn't know we could do it in this simple way before! 
___
*[pkg/sql/sqltelemetry/session.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE0FTTE2MBxGAHF7Lw:-MfE0FTTE2MBxGAHF7Lx:bjvvycd) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/sqltelemetry/session.go#L29)):*
> ```Go
> 
> // CockroachShellCounter is to be incremented every time a
> //client uses the Cockroach SQL shell to access the sql layer
> ```

nit: add a space in between `//` and `client`
___
*[pkg/sql/sqltelemetry/session.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE4nvH69j4BvQ6ROC3:-MfE4nvH69j4BvQ6ROC4:bnrn22x) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/sqltelemetry/session.go#L30)):*
> ```Go
> // CockroachShellCounter is to be incremented every time a
> //client uses the Cockroach SQL shell to access the sql layer
> var CockroachShellCounter = telemetry.GetCounterOnce("sql.cockroach_cli")
> ```

hmm maybe this should be called `sql.cockroach_cli.connection`. let me create a thread with Vy


<!-- Sent from Reviewable.io -->

2021-07-22 16:47 UTC, knz commented
@rafiss when you chat about this with @vy-ton please integrate the following comments:

- we use different values of application_name for every CLI utility that use a SQL connection. For example `cockroach node ls` will connect as `$ cockroach node`. Do you want these values to also increment the counter? If so, you'll need a different (more specific) match.
- the application_name is a value that can be overridden by clients in the conn URL. Someone using our SQL shell can pass a different app_name. Are we OK with losing that connection from the counter? If not, see below.
- We've discussed the problem of properly separating "user-initiated queries" from "automation-initiated queries". Check out [this comment](https://github.com/cockroachdb/cockroach/pull/67809#issuecomment-883543126) and the one after. The suggestion you and Archer made was to rely on a different mechanism than application_name (a special statement issued only by the SQL shell). Maybe that's applicable here too?

2021-07-22 16:49 UTC, rafiss commented
@knz sure -- will get answers to these as well

2021-07-22 16:52 UTC, rafiss commented
> the application_name is a value that can be overridden by clients in the conn URL. Someone using our SQL shell can pass a different app_name. Are we OK with losing that connection from the counter? 

though for this point, it looks like your recent refactors means that a `$ ` will always be prepended to whatever user-supplied appName: https://github.com/cockroachdb/cockroach/blob/5c560905595e3cf13bc349c33635fe8110f99aee/pkg/cli/sql_client.go#L79

there still is the risk that a user will add `$ ` to their own non-cockroach-CLI app's application_name. i'm asking vy about how much this matters

2021-07-22 16:55 UTC, knz commented
>  it looks like your recent refactors means that a $ will always be prepended to whatever user-supplied appName

I don't think that's true?

```
% ./cockroach sql --url 'postgresql://root@kenax:26257?sslmode=disable&application_name=foo' -e 'show application_name';
  application_name
--------------------
  foo
(1 row)
```

The "appName" that you're pointing to in sql_client.go is  the one that is hardcoded by the CLI utilities. If the user provides one in the URL, that takes priority. See `(c *Context) MakeConn` in `cli/clisqlcfg/context.go`.

2021-07-22 16:56 UTC, rafiss commented
I see! thanks for explaining

2021-07-22 18:04 UTC, rafiss commented
Summary from talking with @vy-ton :

- Let's use the name `sql.connection.cockroach_cli` in case we later want to classify other telemetry features under `sql.connection`
- Let's increment the counter only when the full application name matches `$ cockroach sql`. (@e-mbrown when making this change, please use or create new constants to avoid hard-coding the app name)
- Vy is comfortable with the risk of noisy data from people overriding their app name.
- We are deprioritizing the feature counter for number of statements executed in the SQL shell
- Vy pointed out that the DB Console statements page also cannot distinguish which statements are automatic versus user-created. That can be addressed at some future point.

2021-07-26 15:23 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/sql/telemetry_test.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE1yKn0XzuY46NV_GA:-MfYPS7rCoSjsocH9ffk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/telemetry_test.go#L103)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

thanks to knz's helpful comment, it seems like we have a better way of checking of the feature counter was incremented

you can perform this query:
```
SELECT usage_count
  FROM crdb_internal.feature_usage
 WHERE feature_name = 'sql.cockroach_cli';
```

and verify that `usage_count` is equal to 1.

the way to do this query is very similar to how you did QueryRow above. except instead of using a `string` value in `Scan()` you should use an `int` value.



with this approach, we no longer need the `diagSrv`, the `reporter`, the `tempExternalIODir`, or any of the more complicated setup in the beginning of this test. you should be able to change the cluster setup to just this line

```
	cluster := serverutils.StartNewTestCluster(t, 1, base.TestClusterArgs{})
```

i didn't know we could do it in this simple way before! 
</blockquote></details>

Done.
___
*[pkg/sql/sqltelemetry/session.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfE4nvH69j4BvQ6ROC3:-MfYPVZv1Tz7lhxN_un9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aeac9c9246aae1fd64d74994c96d65e0e14abcef/pkg/sql/sqltelemetry/session.go#L30)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm maybe this should be called `sql.cockroach_cli.connection`. let me create a thread with Vy
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 03:09 UTC, rafiss requested changes
this is really close!

I see that there were some test failures, but I don't think it's related to your changes. Can you try rebasing using `git pull --rebase origin master`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-:-Mf_vrb21ORuteA9iHQB:bi0x8fw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @knz, and @rafiss)

___
*[pkg/sql/telemetry_test.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mf_vj2x8fb6RdSJuHj6:-Mf_vj2x8fb6RdSJuHj7:b-nyxy01) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3480a4e7c226c4a79cee723e023a379c256dc6/pkg/sql/telemetry_test.go#L62)):*
> ```Go
> 	q := pgUrl.Query()
> 
> 	q.Add("application_name", "$ cockroach sql")
> ```

nit: update this and the `require` check below to use the `catconstants` too
___
*[pkg/sql/catalog/catconstants/constants.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mf_te294c9VPMURvfpl:-Mf_te294c9VPMURvfpm:b-dq260e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3480a4e7c226c4a79cee723e023a379c256dc6/pkg/sql/catalog/catconstants/constants.go#L33)):*
> ```Go
> const DelegatedAppNamePrefix = "$$ "
> 
> const InternalSqlAppName = "$ cockroach sql"
> ```

small nitpick: could you make it `const InternalSqlAppName = "cockroach sql"`?

I think that's more technically correct. then you should also update this line to use this `InternalSqlAppName` constant: https://github.com/cockroachdb/cockroach/blob/186313accdec63eb1d55098d36d89c207e8289f7/pkg/cli/sql_shell_cmd.go#L52
___
*[pkg/sql/pgwire/server.go, line 827 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mf_unj64UDUqLtfqpqQ:-Mf_unj64UDUqLtfqpqR:b-xtuefn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3480a4e7c226c4a79cee723e023a379c256dc6/pkg/sql/pgwire/server.go#L827)):*
> ```Go
> 
> 	if appName, ok := args.SessionDefaults["application_name"]; ok {
> 		if appName == catconstants.InternalSqlAppName {
> ```

nit: can you add a comment before this if statement, like "The client might override the appName to something else, which would prevent it from being counted in telemetry, but we've decided that this noise in the data is acceptable."

also, with my earlier comment, the condition might need to change to:
```
if appName == catconstants.ReportableAppNamePrefix + catconstants.InternalSqlAppName {
```
___
*[pkg/sql/sqltelemetry/session.go, line 29 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mf_vZ3lEKPhmBlRNzpG:-Mf_vZ3lEKPhmBlRNzpH:b-sr9r7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3480a4e7c226c4a79cee723e023a379c256dc6/pkg/sql/sqltelemetry/session.go#L29)):*
> ```Go
> 
> // CockroachShellCounter is to be incremented every time a
> // client uses the Cockroach SQL shell to access the sql layer
> ```

nit: this comment can say "uses the SQL shell to connect to CockroachDB"


<!-- Sent from Reviewable.io -->

2021-07-28 12:51 UTC, e-mbrown reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/sql/catalog/catconstants/constants.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mf_te294c9VPMURvfpl:-Mfh88Ep64a08tH0TANw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e3480a4e7c226c4a79cee723e023a379c256dc6/pkg/sql/catalog/catconstants/constants.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

small nitpick: could you make it `const InternalSqlAppName = "cockroach sql"`?

I think that's more technically correct. then you should also update this line to use this `InternalSqlAppName` constant: https://github.com/cockroachdb/cockroach/blob/186313accdec63eb1d55098d36d89c207e8289f7/pkg/cli/sql_shell_cmd.go#L52
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 19:24 UTC, rafiss commented on pkg/sql/catalog/catconstants/constants.go
> +const InternalSqlAppName = "cockroach sql"
nit: any public constant like this needs a comment. the comment has to start with the name of the constant (see above for example)

so like
```
InternalSqlAppName is the application_name used by the cockroach CLI by default
```

2021-07-31 04:28 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67606)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown, @knz, and @rafiss)

___
*[pkg/sql/telemetry_test.go, line 47 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfunqUx1jWeLj3HDZco:-MfunqUx1jWeLj3HDZcp:bjhg2ul) ([raw file](https://github.com/cockroachdb/cockroach/blob/957d4ade508311253c1dbebee2b4df5f3f660333/pkg/sql/telemetry_test.go#L47)):*
> ```Go
> 
> func TestTelemetryRecordCockroachShell(t *testing.T) {
> ```

the beginning of the function needs two helpers that are common for all tests (one of the lint errors mentions this)

```
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)
```
___
*[pkg/sql/telemetry_test.go, line 73 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-Mfuo3wK2gEmGGv4KbGt:-Mfuo3wK2gEmGGv4KbGu:b9uiwng) ([raw file](https://github.com/cockroachdb/cockroach/blob/957d4ade508311253c1dbebee2b4df5f3f660333/pkg/sql/telemetry_test.go#L73)):*
> ```Go
> 
> 	var appName string
> 	db.QueryRow("SHOW application_name").Scan(&appName)
> ```

i think there's also a linter for doing error checking on QueryRow. so this needs to become:

```
err = db.QueryRow("SHOW application_name").Scan(&appName)
require.NoError(t, err)
```
___
*[pkg/sql/telemetry_test.go, line 79 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/67606#-MfuoK2C3I5IVeaHksPy:-MfuoK2D2LMtTn-jaeGz:b-nl9w9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/957d4ade508311253c1dbebee2b4df5f3f660333/pkg/sql/telemetry_test.go#L79)):*
> ```Go
> 	db.QueryRow(
> 		"SELECT usage_count FROM crdb_internal.feature_usage WHERE feature_name = 'sql.connection.cockroach_cli'",
> 	).Scan(&counter)
> ```

and this needs to be:

```
err = db.QueryRow(
		"SELECT usage_count FROM crdb_internal.feature_usage WHERE feature_name = 'sql.connection.cockroach_cli'",
	).Scan(&counter)
require.NoError(t, err)
```


<!-- Sent from Reviewable.io -->

2021-08-03 22:36 UTC, rafiss requested changes

2021-08-03 22:36 UTC, rafiss commented on pkg/sql/telemetry_test.go
> +	)
i think i might see the issue. you need to add this line
```
	defer cluster.Stopper().Stop(context.Background())
```

2021-08-04 16:39 UTC, rafiss approved these changes
this looks good to me! feel free to merge

2021-08-04 16:49 UTC, e-mbrown commented
bors r=rafiss,knz,arulajmani

2021-08-04 18:37 UTC, merged