jobs: fix bug where failure to record the trace ID prevents adoption, remove RTT
cockroachdb/cockroach pull request #67671
Opened 2021-07-15 16:59 UTC by ajwerner

In #65322 we added code to record a trace ID into job progress. This code
added a new error return path to runJob which did not unregister the job
from the in-memory state in the registry. This PR fixes that oversight
by deferring that call and allowing jobs to be retried when writing that
trace ID fails.

jobs: only write the trace ID into jobs if nonzero
We don't trace most jobs. It's an extra write to the jobs table for each
run to just mark it as 0.

Release note (performance improvement): Eliminated a round-trip when running
most jobs.

Release note (bug fix): Fixed a bug in jobs where failures to write to the
jobs table can prevent subsequent adoption of a job until the previous
node dies or the jobs is paused.

2021-07-15 17:00 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67671)
<!-- Reviewable:end -->

2021-07-15 20:08 UTC, sajjadrizvi requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67671)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

___
*[pkg/jobs/adopt.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Mefi0zW4PoLaYRC1gt1:-Mefi0zW4PoLaYRC1gt2:bs5fqgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/adopt.go#L255)):*
> ```Go
> 
> 	// Make sure that we remove the job from the running set when this returns.
> 	defer r.unregister(job.ID())
> ```

This part looks OK to me. I am not sure about the changes related to trace and span.
___
*[pkg/jobs/jobs_test.go, line 887 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Meflai07A9MSaGGZH65:-Meflai07A9MSaGGZH66:b9on4df) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/jobs_test.go#L887)):*
> ```Go
> 		rts.check(t, jobs.StatusSucceeded)
> 	})
> 	t.Run("fail setting trace ID", func(t *testing.T) {
> ```

This test looks good to me. The test will not succeed if the error from `BeforeUpdate` is not handled properly.


<!-- Sent from Reviewable.io -->

2021-07-15 20:13 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67671)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @sajjadrizvi)

___
*[pkg/jobs/adopt.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Mefi0zW4PoLaYRC1gt1:-Mefn7_v9jLDONSmgsv1:bxodajl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/adopt.go#L255)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

This part looks OK to me. I am not sure about the changes related to trace and span.
</blockquote></details>

Why is this a blocking comment? What are you asking for?
___
*[pkg/jobs/jobs_test.go, line 887 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Meflai07A9MSaGGZH65:-Mefmy9k5lS2U3IYXotu:b-u4lj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/jobs_test.go#L887)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

This test looks good to me. The test will not succeed if the error from `BeforeUpdate` is not handled properly.
</blockquote></details>

What is this blocking comment asking for?


<!-- Sent from Reviewable.io -->

2021-07-15 20:15 UTC, adityamaru approved these changes
LGTM, thanks for fixing the oversight.

2021-07-15 20:17 UTC, adityamaru commented
You might need to fix import because I merged https://github.com/cockroachdb/cockroach/pull/67243 earlier today, and this PR changes the TraceableJob interface.

2021-07-15 23:13 UTC, sajjadrizvi approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67671)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @sajjadrizvi)

___
*[pkg/jobs/adopt.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Mefi0zW4PoLaYRC1gt1:-MegRPcv8MT65zJH1hZm:b-mu4yun) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/adopt.go#L255)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why is this a blocking comment? What are you asking for?
</blockquote></details>

That's by mistake.


<!-- Sent from Reviewable.io -->

2021-07-15 23:13 UTC, sajjadrizvi approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67671)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/jobs_test.go, line 887 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67671#-Meflai07A9MSaGGZH65:-MegRaei6xIOoEubNSWO:b-9qvi74) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcd9fc46871cc9f8e72395b15e271ab3a134a91d/pkg/jobs/jobs_test.go#L887)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What is this blocking comment asking for?
</blockquote></details>

Again, it's by mistake :)


<!-- Sent from Reviewable.io -->

2021-07-16 00:28 UTC, ajwerner commented
TFTR!

bors r+

2021-07-16 21:55 UTC, ajwerner commented
bors r+

2021-07-16 22:51 UTC, merged