sql: prevent users from being dropped if they have default privileges defined for
cockroachdb/cockroach pull request #67950
Opened 2021-07-22 19:09 UTC by RichardJCai

Release note (sql change): If a user has a default privilege defined for, they cannot
be dropped until the default privilege is removed.

Example:
ALTER DEFAULT PRIVILEGES FOR ROLE test1 GRANT SELECT ON TABLES TO test2;

Neither test1 or test2 can be dropped until performing
ALTER DEFAULT PRIVILEGES FOR ROLE test1 REVOKE SELECT ON TABLES FROM test2;

Trying to drop test1 will error with:
role test1 cannot be dropped because some objects depend on it
owner of default privileges on new relations belonging to role test1

Trying to drop test2 will error with:
role test2 cannot be dropped because some objects depend on it
privileges for default privileges on new relations belonging to role test1

fixes #67880

2021-07-22 19:09 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67950)
<!-- Reviewable:end -->

2021-07-23 12:23 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MfIJA1r4m_bLZA3Mfj5:-MfIJA1r4m_bLZA3Mfj6:b-7b0sag) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f75de89ea5c20308af94524ce7223d9c70de23/pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges#L9)):*
> ```
> ALTER DEFAULT PRIVILEGES FOR ROLE test1 GRANT SELECT ON TABLES TO test2;
> 
> statement error pq: role test1 cannot be dropped because some objects depend on it\nowner of default privileges on new relations belonging to role test1
> ```

Drive by comment: Can we add a hint here to indicate how the user may get out of this problem?  For example, in this case would they need to assign the default privileges to another role?


<!-- Sent from Reviewable.io -->

2021-07-23 18:10 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges, line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MfIJA1r4m_bLZA3Mfj5:-MfJYNx85_FtqjznfviQ:bhp0k6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f75de89ea5c20308af94524ce7223d9c70de23/pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges#L9)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Drive by comment: Can we add a hint here to indicate how the user may get out of this problem?  For example, in this case would they need to assign the default privileges to another role?
</blockquote></details>

I've just copied the Postgres error message for now.
To drop the role, they'll have to run ALTER DEFAULT PRIVILEGES to revoke the privileges that exist.

I'll see if I can easily add a hint in.

It does seem like people get confused by this error.
https://stackoverflow.com/questions/9840955/postgresql-drop-role-fails-because-of-default-privileges

One mechanism that postgres supports is `DROP OWNED BY` but we dont have that yet.


<!-- Sent from Reviewable.io -->

2021-07-27 03:28 UTC, rafiss requested changes
just had some small nits, and I agree that a `notice/hint` sounds like a good idea

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-:-Mfa-HS2AFpNn820piwm:b16slyz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-Mfa-CAJ57UR-Rw6PUfA:-Mfa-CAJ57UR-Rw6PUfB:b4dg08x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f75de89ea5c20308af94524ce7223d9c70de23/pkg/sql/drop_role.go#L154)):*
> ```Go
> 				}
> 			}
> 			if db.GetDefaultPrivileges() != nil {
> ```

nit: could you pull out this if-stmt-block into another function?
___
*[pkg/sql/drop_role.go, line 298 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-Mf_zvA19oxJ2BumeiHG:-Mf_zvA19oxJ2BumeiHH:b4g2vj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f75de89ea5c20308af94524ce7223d9c70de23/pkg/sql/drop_role.go#L298)):*
> ```Go
> 		name := security.MakeSQLUsernameFromPreNormalizedString(names[i])
> 		// Did the user own any objects?
> 		dependantObjects := userNames[name]
> ```

nit: `dependentObjects`


<!-- Sent from Reviewable.io -->

2021-07-28 19:29 UTC, RichardJCai reviewed
Added a hint with the error

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-:-Mfi_xdS0zJHMHzp5oYf:b-dfeucs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/sql/drop_role.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-Mfa-CAJ57UR-Rw6PUfA:-Mfi_vox6wYo4-MSNqwe:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4f75de89ea5c20308af94524ce7223d9c70de23/pkg/sql/drop_role.go#L154)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: could you pull out this if-stmt-block into another function?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-07-29 21:34 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MfoAx2rB1imdccBtYHu:-MfoAx2rB1imdccBtYHv:bvr3zyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0887dac5fbf855471e9bd63e82f7dc2c4e4abce/pkg/sql/drop_role.go#L427)):*
> ```Go
> 								ObjectType: defaultPrivilege,
> 								ErrorMessage: fmt.Sprintf(
> 									"owner of default privileges on new %s belonging to role %s",
> ```

hm, just realized: is this safe w.r.t. error redaction? (specifically the roleName part)

do we need an `errors.Newf` error instead of just a `Sprintf` string?


<!-- Sent from Reviewable.io -->

2021-07-29 21:34 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MfoAx2rB1imdccBtYHu:-MfoBA7ABhRIxORInjtI:b-kq9hih) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0887dac5fbf855471e9bd63e82f7dc2c4e4abce/pkg/sql/drop_role.go#L427)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, just realized: is this safe w.r.t. error redaction? (specifically the roleName part)

do we need an `errors.Newf` error instead of just a `Sprintf` string?
</blockquote></details>

(i'm not sure myself; i'm asking bc i don't know)


<!-- Sent from Reviewable.io -->

2021-08-03 19:23 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @rafiss)

___
*[pkg/sql/drop_role.go, line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MfoAx2rB1imdccBtYHu:-MgCT5sb3KFiTmge_SMa:b4qxhyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0887dac5fbf855471e9bd63e82f7dc2c4e4abce/pkg/sql/drop_role.go#L427)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

(i'm not sure myself; i'm asking bc i don't know)
</blockquote></details>

Changed it to `errors.Newf` I'm pretty sure fmt.Sprintf is not safe. 


<!-- Sent from Reviewable.io -->

2021-08-10 20:43 UTC, rafiss requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnTsQ5q-_SyW_5Dnw:-MglnTsQ5q-_SyW_5Dnx:b-s156xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L276)):*
> ```Go
> 			objects := objectsMsg.CloseAndGetString()
> 			err := pgerror.Newf(pgcode.DependentObjectsStillExist,
> 				"role %s cannot be dropped because some objects depend on it%s",
> ```

nit: missing space before `%s`
___
*[pkg/sql/drop_role.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnG_E5zSmtxKBSEAB:-MglnG_E5zSmtxKBSEAC:b-i1ilqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L277)):*
> ```Go
> 			err := pgerror.Newf(pgcode.DependentObjectsStillExist,
> 				"role %s cannot be dropped because some objects depend on it%s",
> 				name, objects)
> ```

similar to below, if it's done this way then i think the entire `objects` string will get redacted. can we make it more fine-grained?
___
*[pkg/sql/drop_role.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglmoQv3TAVx2mWeaU_:-MglmoQv3TAVx2mWeaUa:bra279n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L447)):*
> ```Go
> 								ErrorMessage: errors.Newf(
> 									"owner of default privileges on new %s belonging to role %s",
> 									objectType, role.Role,
> ```

for these error messages, we should mark the `objectType` as "safe" so it doesn't get redacted. see https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#When-to-use-SafeFormatter-vs-SafeValue


<!-- Sent from Reviewable.io -->

2021-08-11 19:04 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @rafiss)

___
*[pkg/sql/drop_role.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnTsQ5q-_SyW_5Dnw:-MgqXRcvDPlxYILGPArk:b-sfuaby) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L276)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: missing space before `%s`
</blockquote></details>

I think this is fine because objects starts with a newline.
___
*[pkg/sql/drop_role.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnG_E5zSmtxKBSEAB:-MgqXnMK9I1-HCggYeVW:bedyz4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L277)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar to below, if it's done this way then i think the entire `objects` string will get redacted. can we make it more fine-grained?
</blockquote></details>

I didn't change this from how it currently does it, do you know if it is currently redacted? I'm not familiar with this.

Is there any easy way to test log redaction?
___
*[pkg/sql/drop_role.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglmoQv3TAVx2mWeaU_:-MgqYVFVAmFfBRy1DTlR:bxn1p6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L447)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for these error messages, we should mark the `objectType` as "safe" so it doesn't get redacted. see https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#When-to-use-SafeFormatter-vs-SafeValue
</blockquote></details>

Wrapped it with a safestring


<!-- Sent from Reviewable.io -->

2021-08-11 19:07 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @rafiss)

___
*[pkg/sql/drop_role.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnG_E5zSmtxKBSEAB:-Mgqb0Zc2XrjCW-f_tGQ:b-xy5yvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L277)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I didn't change this from how it currently does it, do you know if it is currently redacted? I'm not familiar with this.

Is there any easy way to test log redaction?
</blockquote></details>

Or would it make sense to do 
```
			err := pgerror.Newf(pgcode.DependentObjectsStillExist,
				"role %s cannot be dropped because some objects depend on it"+objects,
				name)
```


<!-- Sent from Reviewable.io -->

2021-08-11 19:40 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnG_E5zSmtxKBSEAB:-MgqiM1A5nlBSWT9L4yh:bimhxqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L277)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Or would it make sense to do 
```
			err := pgerror.Newf(pgcode.DependentObjectsStillExist,
				"role %s cannot be dropped because some objects depend on it"+objects,
				name)
```
</blockquote></details>

that would only be allowed if the `objects` string had no identifiers in it (no user names or db/schema/table/type names)


<!-- Sent from Reviewable.io -->

2021-08-11 19:40 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 277 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglnG_E5zSmtxKBSEAB:-Mgqiev08Ne7mZY_XgBD:bw4u6pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L277)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that would only be allowed if the `objects` string had no identifiers in it (no user names or db/schema/table/type names)
</blockquote></details>

this seems kinda annoying, so i'm fine to leave it as is (redact the whole `objects` string)


<!-- Sent from Reviewable.io -->

2021-08-11 19:50 UTC, RichardJCai reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @rafiss, and @RichardJCai)

___
*[pkg/sql/drop_role.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-MglmoQv3TAVx2mWeaU_:-Mgql1DM0LtZOXHc1cYw:bx4egp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b56e00b80869bdc3c97e0fae9490cfc72ee0c0d0/pkg/sql/drop_role.go#L447)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Wrapped it with a safestring
</blockquote></details>

Nvm, will leave as is and have the entire objects string be redacted right now.


<!-- Sent from Reviewable.io -->

2021-08-11 19:59 UTC, rafiss approved these changes
lgtm!

> Reviewed 1 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67950#-:-Mgqn-0i7Xc0rWRAJbYf:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @rafiss, and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-08-11 22:13 UTC, RichardJCai commented
Thanks for the reviews!
bors r=rafiss

2021-08-11 23:25 UTC, merged