debug: add the detective recreate <bundledir> command
cockroachdb/cockroach pull request #67979
Opened 2021-07-23 13:53 UTC by jordanlewis

This command loads the environment, schema, and stats from an unzipped
statement bundle into a demo cluster for inspection.

Release note (cli change): add the debug detective recreate <zipdir>
command, which allows users to load a statement bundle into an in-memory
database for inspection.

2021-07-23 13:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/67979)
<!-- Reviewable:end -->

2021-07-23 13:58 UTC, knz approved these changes
fun!

2021-07-23 16:14 UTC, mgartner approved these changes
Cool!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-:-MfJ8KuU-thvPORwM9sx:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/cli/cli.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfJ782H6SxWqURYTnuK:-MfJ782H6SxWqURYTnuL:b-xa6ckn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1910f711ad7e64688a1229752a287b44f049eec/pkg/cli/cli.go#L275)):*
> ```Go
> // isDemoCmd returns true iff cmd is a sub-command of `demo`.
> func isDemoCmd(cmd *cobra.Command) bool {
> 	return hasParentCmd(cmd, demoCmd) || hasParentCmd(cmd, debugDetectiveCmd)
> ```

`cockroach debug detective` is a sub-command of `cockroach demo`?


<!-- Sent from Reviewable.io -->

2021-07-23 16:46 UTC, yuzefovich reviewed
Awesome! I'm assuming that fixing up the FK stuff will be in a follow-up?

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-:-MfJFQUn88VPsOpkyXC3:bf5iq4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/cli/detective.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfJEm6E2I4KAwXWhWLE:-MfJEm6E2I4KAwXWhWLF:b-ep724s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1910f711ad7e64688a1229752a287b44f049eec/pkg/cli/detective.go#L33)):*
> ```Go
> 	Long: `
> The debug detective is a suite of tools for debugging and manipulating statement
> bundles created with EXPLAIN ANALYZE (BUNDLE).
> ```

nit: I don't think we have `BUNDLE` option, it's `DEBUG`.
___
*[pkg/cli/detective.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfJFBsK-Ofqjh88sylI:-MfJFBsK-Ofqjh88sylJ:b-orxdop) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1910f711ad7e64688a1229752a287b44f049eec/pkg/cli/detective.go#L151)):*
> ```Go
> # Autostats disabled.
> #
> # Statement was:
> ```

Usually the statement (in `statement.sql`) contains placeholders, will this be the same?


<!-- Sent from Reviewable.io -->

2021-07-23 18:01 UTC, jordanlewis reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[pkg/cli/cli.go, line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfJ782H6SxWqURYTnuK:-MfJL6o_EB6n5PsZngN3:b-dce5pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1910f711ad7e64688a1229752a287b44f049eec/pkg/cli/cli.go#L275)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`cockroach debug detective` is a sub-command of `cockroach demo`?
</blockquote></details>

No, but this needs to be set to avoid some issues with logging. I dunno what to say, I guess i could change the method name.
___
*[pkg/cli/detective.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfJFBsK-Ofqjh88sylI:-MfJLG8W2NpFPezE8J6C:b-rjl1vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1910f711ad7e64688a1229752a287b44f049eec/pkg/cli/detective.go#L151)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Usually the statement (in `statement.sql`) contains placeholders, will this be the same?
</blockquote></details>

Yes, it will. I have plans to improve this.


<!-- Sent from Reviewable.io -->

2021-07-23 20:57 UTC, michae2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-:-MfK9DbV5KBDUqnAFDBU:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)



<!-- Sent from Reviewable.io -->

2021-07-23 20:58 UTC, michae2 requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67979)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @mgartner, and @yuzefovich)

___
*[pkg/cli/BUILD.bazel, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/67979#-MfK9Kja79jwsfHRkUtW:-MfK9Kja79jwsfHRkUtX:b-s42oas) ([raw file](https://github.com/cockroachdb/cockroach/blob/d52df825c6a5c0ab3a75624f2b7f2ed09a95656a/pkg/cli/BUILD.bazel#L28)):*
> ```Starlark
>         "demo.go",
>         "demo_telemetry.go",
>         "detective.go",
> ```

"statement_bundle.go" (thanks for changing the command!)


<!-- Sent from Reviewable.io -->

2021-07-24 01:16 UTC, jordanlewis commented
TFTRs!

bors r+

2021-07-24 02:43 UTC, merged