pprof, ui: request pprofui from any node
cockroachdb/cockroach pull request #68019
Opened 2021-07-23 22:08 UTC by dhartunian

Previously, the links for the `pprofui` commands in the Advanced Debug
section of the DB Console were limited to only displaying data from the
node that served the HTTP request.

This change introduces a query param (`node`) that can be added to
requests under `/debug/pprofui` to request the pprof data from any node
in the cluster. The request handler makes a gRPC call to the `Profile`
endpoint of the relevant node, which has been expanded to handle all
pprof profile types.

Resolves #62841

Release note (ui change, ops change): When requesting the pprofui
endpoints from the Advanced Debug page in DB Console, operators can now
query by node ID in order to request pprofui data from any node in the
cluster without having to connect to its DB Console directly.

[ ] Add a nodeID dropdown in the UI or something to make requesting easier prior to merge

2021-07-23 22:08 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68019)
<!-- Reviewable:end -->

2021-07-26 09:31 UTC, tbg requested changes
Thanks for working on this! As is, this PR is leaving things awkwardly half-way. We're adding a way for pprofui to grab a profile from a remote node. But we're not using that unless we're explicitly requesting from a remote node. Let's go all of the way and use the `Profile` endpoint for every profile we'll ever fetch. Let's try to rip the custom redirection logic here out, and leave that to the `Profile` endpoint as well. Finally, hopefully `s.hook` can go (?) and the whole pprofui setup simplifies somewhat.

It's possible that this will cause issues with multi-tenant (do we have the profile endpoint there?) but then let's work through them. My suggestion to narrow down the Profile call will help here, as you can pass, on tenants, an impl that errors out unless the node is `local`, and implements the relevant code of `Profile` directly (I think we can set things up so that it will call the actual code that produces the profiles in Profile).

Overall, this is moving into the right direction and I'm glad this is happening.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-:-MfX65DUDXYkSDJ0x3L7:beb5di)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/server/tenant.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7yz89mQvSzJ2yrpB:-MfX7yz89mQvSzJ2yrpC:bktm9b1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/tenant.go#L139)):*
> ```Go
> 	if err := args.stopper.RunAsyncTask(ctx, "serve-http", func(ctx context.Context) {
> 		mux := http.NewServeMux()
> 		debugServer := debug.NewServer(args.Settings, nil, nil, s.pgServer.HBADebugFn())
> ```

This will lead to NPEs when `?node` is used? Pass something real here that returns errors when it's used and isn't available. A test would be appreciated, too.
___
*[pkg/server/debug/server.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX4yAd0tcblhf_Y7yU:-MfX4yAd0tcblhf_Y7yV:b-d0tmtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/server.go#L72)):*
> ```Go
> // NewServer sets up a debug server.
> func NewServer(
> 	st *cluster.Settings, gossip *gossip.Gossip, rpcCtx *rpc.Context, hbaConfDebugFn http.HandlerFunc,
> ```

Shouldn't this get a `nodedialer` instead? Or even just a method it can call that takes a NodeID and a request to the Profile endpoint, the result for which it returns? I'd keep the dependency set small (or stop pretending that there is a debug server and just merge it into one of the various other servers, if we have to). Especially passing Gossip here is unfortunate.
___
*[pkg/server/debug/pprofui/server.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX6zvA8mgDayN5_8xp:-MfX6zvA8mgDayN5_8xq:b-v1kd1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L239)):*
> ```Go
> 				return err
> 			}
> 			addr, err := s.gossip.GetNodeIDAddress(nodeID)
> ```

Why not send a request to the local node and ask for the profile to be taken from nodeID? I.e. why reinvent the redirecting wheel here when the endpoint already does it for you?
___
*[pkg/server/debug/pprofui/server.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX6RTs7EZvrbfhd6P_:-MfX6RTs7EZvrbfhd6Pa:brq3kcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L243)):*
> ```Go
> 				return err
> 			}
> 			ctx := context.TODO()
> ```

I think the request has a context. `r.Context()`?
___
*[pkg/server/debug/pprofui/server.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7Ftx2WxUldIvGXt5:-MfX7Ftx2WxUldIvGXt6:b-fl3tea) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L255)):*
> ```Go
> 			resp, err := client.Profile(ctx, &serverpb.ProfileRequest{
> 				NodeId: "local",
> 				Type:   serverpb.ProfileRequest_Type(profileType),
> ```

This seems to ignore all parameters, see the `r.ParseForm` above. I think it's just `?seconds` that matters, but it would be good to error out if there are any parameters in the request that we won't translate into the ProfileRequest.
___
*[pkg/server/debug/pprofui/server.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX5Bn3CclJBVX_PyC7:-MfX5Bn48_LwFNRmQDA6:b-n7nn7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L274)):*
> ```Go
> 			rw := &responseBridge{target: w}
> 
> 			s.hook(profileName, r.Form.Get("labels") != "", func() { fetchHandler(rw, req) })
> ```

We're now being inconsistent between local and remote requests. Remote requests hit the Status endpoint (which always turns on labels) but local requests do it on demand.
I think there should only be one path, and that path should hit the profile endpoint (i.e. here we'd hit it with "local"). That will simplify things and also address your TODO above, as *hopefully* there just isn't a reason for `s.hook` to exist?
___
*[pkg/server/debug/pprofui/storage_mem.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX5jIp0x_3gyLZBghP:-MfX5jIp0x_3gyLZBghQ:b-svc33u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/storage_mem.go#L46)):*
> ```Go
> 	s.mu.Lock()
> 	defer s.mu.Unlock()
> 	records2 := make([]record, len(s.mu.records))
> ```

`return append([]record(nil), s.mu.records...)`


<!-- Sent from Reviewable.io -->

2021-07-28 22:00 UTC, dhartunian reviewed
Thanks for the nudge @tbg, I was able to do a lot more cleanup :)

I'm also thinking that if I rebase this work on top of the pod-to-pod stuff, we could actually implement profile with instanceID dialing capability to support the full feature set. I will keep working on the tenant impl and see what works there.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-:-Mfj3eQ1-pSuSpTdBnNW:b-3oudoy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/server/tenant.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7yz89mQvSzJ2yrpB:-Mfj3ToF74vSSk-FyqGo:b6iru12) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/tenant.go#L139)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This will lead to NPEs when `?node` is used? Pass something real here that returns errors when it's used and isn't available. A test would be appreciated, too.
</blockquote></details>

This raises an interesting question since I'm using `statusServer` to run all the profiling...since we don't have one available, should I extract the implementation and share it with `tenant_status.go` for now?
___
*[pkg/server/debug/server.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX4yAd0tcblhf_Y7yU:-Mfj1OKG-QxJxa3Q1vqs:bj26ff5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/server.go#L72)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't this get a `nodedialer` instead? Or even just a method it can call that takes a NodeID and a request to the Profile endpoint, the result for which it returns? I'd keep the dependency set small (or stop pretending that there is a debug server and just merge it into one of the various other servers, if we have to). Especially passing Gossip here is unfortunate.
</blockquote></details>

Done. These arguments are both gone now that we rely on `statusServer`.
___
*[pkg/server/debug/pprofui/server.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX6zvA8mgDayN5_8xp:-Mfj-bRtERgdzAPKlQDq:b-yopvnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L239)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why not send a request to the local node and ask for the profile to be taken from nodeID? I.e. why reinvent the redirecting wheel here when the endpoint already does it for you?
</blockquote></details>

Ah! I'm getting it now! Yes! Done.
___
*[pkg/server/debug/pprofui/server.go, line 243 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX6RTs7EZvrbfhd6P_:-Mfj1S5u3IbDOrfZrcfv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L243)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think the request has a context. `r.Context()`?
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/server.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7Ftx2WxUldIvGXt5:-Mfj2zZG4n4a1dBh_jDu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L255)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This seems to ignore all parameters, see the `r.ParseForm` above. I think it's just `?seconds` that matters, but it would be good to error out if there are any parameters in the request that we won't translate into the ProfileRequest.
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/server.go, line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX5Bn3CclJBVX_PyC7:-Mfj-sAPDGO2MPxNoP7K:b-jpnt9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L274)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We're now being inconsistent between local and remote requests. Remote requests hit the Status endpoint (which always turns on labels) but local requests do it on demand.
I think there should only be one path, and that path should hit the profile endpoint (i.e. here we'd hit it with "local"). That will simplify things and also address your TODO above, as *hopefully* there just isn't a reason for `s.hook` to exist?
</blockquote></details>

Yes I was able to remove `s.hook`!
___
*[pkg/server/debug/pprofui/storage_mem.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX5jIp0x_3gyLZBghP:-Mfj3CHjE-x6kFOAp7YC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/storage_mem.go#L46)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

`return append([]record(nil), s.mu.records...)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 09:47 UTC, tbg reviewed
> Reviewed 3 of 10 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[pkg/server/tenant.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7yz89mQvSzJ2yrpB:-Mflb-n53HPJRU9mWb09:bm8di5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/tenant.go#L139)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

This raises an interesting question since I'm using `statusServer` to run all the profiling...since we don't have one available, should I extract the implementation and share it with `tenant_status.go` for now?
</blockquote></details>

I think there are three options:

1. what you suggested, extract the impl and make it available here instead of the `nil`
2. wait until we have a status server for tenants (is that the plan after pod-to-pod?) and until then, pass an impl in that returns "unsupported" (bit risky, since we absolutely need to be able to get profiles from tenant pods that we actually deploy to prod)
3. hold this PR open until we can do 2. right away (risk is that this PR misses next release, so we don't get the new functionality

I'm not sure how much of a wait 2) is, so I'd probably do 1) if it's easy enough just to make sure we're not eating any kind of risk.
___
*[pkg/server/debug/server.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX4yAd0tcblhf_Y7yU:-Mflb_3S0bAbN7jXgZZH:b-pusysq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/server.go#L72)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Done. These arguments are both gone now that we rely on `statusServer`.
</blockquote></details>

Can you pass a narrower interface in? This doesn't need the entire StatusServer, just one method on it. That will also allow you to write a unit test without mocking 100 methods you don't particularly care about.
___
*[pkg/server/debug/pprofui/server.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7Ftx2WxUldIvGXt5:-Mflc2Yy46YPJMEgOJYs:bd8mqs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L255)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant more generally *anything* in the form that we can't translate, or is that not an option for some reason?

Btw the status.Profile endpoint will always have labels on, so that might be the one parameter to silently ignore. The problem will be that you can't turn labels off, but so far that hasn't been an issue - the labels are pretty alloc heavy though. Suppose if one cares about that one can hit the raw pprof endpoint directly. But it would be good to ultimately have the labels toggle on the status server endpoint.

I think the labels parameter is also used in a link on the "advanced debug" section, so make sure to make an edit there if needed.
___
*[pkg/server/debug/pprofui/server.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mflbgbx5f5t3IlCM0aa:-Mflbgbx5f5t3IlCM0ab:bkh18st) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server.go#L45)):*
> ```Go
> }
> 
> // TODO(davidh): fix the below docstring to remove hook reference
> ```

Just putting a comment here so this doesn't get forgotten before merge.
___
*[pkg/server/debug/pprofui/server.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MflblVh30WNsVNb2KRe:-MflblVh30WNsVNb2KRf:bbmcxyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server.go#L198)):*
> ```Go
> 		req.Form = r.Form
> 
> 		// TODO(davidh): do we need to support `&si=alloc_objects` for heap?
> ```

The heap profile that is returned contains all sample indexes, so that parameter isn't relevant while fetching, just while visualizing it in the UI.
___
*[pkg/server/debug/pprofui/server_test.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MflcfAp5GHO7mLJGJU9:-MflcfAp5GHO7mLJGJUA:bgxhu6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server_test.go#L95)):*
> ```Go
> 
> 	storage := pprofui.NewMemStorage(1, 0)
> 	s3 := pprofui.NewServer(storage, thirdServer.GossipI().(*gossip.Gossip), thirdServer.RPCContext())
> ```

Needs an update.
___
*[pkg/server/debug/pprofui/server_test.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mfld3u644wZ_2_7q8bs:-Mfld3u644wZ_2_7q8bt:b-qw8vs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server_test.go#L98)):*
> ```Go
> 
> 	for i := 1; i < 4; i++ {
> 		t.Run(fmt.Sprintf("requesting pprof from node %d", i), func(t *testing.T) {
> ```

In a sense most of what this test is doing right now is testing the node redirection, which is now no longer a concern of the pprofui (since that's the statusServer.Profile endpoint's job). I think this test could work provide a mock for the status server endpoint that returns a fixed static heap profile (i.e. a fixture) and then the test really checks that requests to the pprofui server result in appropriate calls to the mocked endpoint, and that it serves up a UI that looks good (i.e. that part stays in the test). There wouldn't be a need to spin up a TestCluster.
___
*[pkg/server/debug/pprofui/storage_mem.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfldWkuC8tWW4AsTPs4:-MfldWkuC8tWW4AsTPs5:b4s0ioq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/storage_mem.go#L43)):*
> ```Go
> }
> 
> func (s *MemStorage) GetRecords() []record {
> ```

Doesn't the linter yell at you here? Returning a private struct from a public method effectively makes the method uncallable from outside the package.
I think you might be able to remove this, since you should be able to put TestServerDifferentNode into the `pprofui` package (not `pprofui_test`) if you make sure that the interface to the `status.profile` endpoint is not too dep-heavy.

If for some reason you're stuck with the `_test` package, the way we usually add these test-only accessors is to make a file `helpers_test.go` and define this method there. That way, it's only there during tests.


<!-- Sent from Reviewable.io -->

2021-08-04 16:23 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/server/tenant.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7yz89mQvSzJ2yrpB:-MgGTLLW1Q8rglNWZM9w:b-emhwvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/tenant.go#L139)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think there are three options:

1. what you suggested, extract the impl and make it available here instead of the `nil`
2. wait until we have a status server for tenants (is that the plan after pod-to-pod?) and until then, pass an impl in that returns "unsupported" (bit risky, since we absolutely need to be able to get profiles from tenant pods that we actually deploy to prod)
3. hold this PR open until we can do 2. right away (risk is that this PR misses next release, so we don't get the new functionality

I'm not sure how much of a wait 2) is, so I'd probably do 1) if it's easy enough just to make sure we're not eating any kind of risk.
</blockquote></details>

Agreed. I implemented 1) with support only for local profiling. Once my fan-out PR is merged we could add that to tenants but I think just supporting profiles in "local" mode should cover most use cases.
___
*[pkg/server/debug/server.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX4yAd0tcblhf_Y7yU:-Mg86EPE21TTYzbG-VVX:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/server.go#L72)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you pass a narrower interface in? This doesn't need the entire StatusServer, just one method on it. That will also allow you to write a unit test without mocking 100 methods you don't particularly care about.
</blockquote></details>

Done
___
*[pkg/server/debug/pprofui/server.go, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7Ftx2WxUldIvGXt5:-MgGSa9jByK1cWtvYlvL:b-k3uo79) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/debug/pprofui/server.go#L255)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I meant more generally *anything* in the form that we can't translate, or is that not an option for some reason?

Btw the status.Profile endpoint will always have labels on, so that might be the one parameter to silently ignore. The problem will be that you can't turn labels off, but so far that hasn't been an issue - the labels are pretty alloc heavy though. Suppose if one cares about that one can hit the raw pprof endpoint directly. But it would be good to ultimately have the labels toggle on the status server endpoint.

I think the labels parameter is also used in a link on the "advanced debug" section, so make sure to make an edit there if needed.
</blockquote></details>

Added support for disabling labels to the Profile method. The flag added is a "disable" flag that's false by default in order to preserve existing functionality as-is.

The `Form` API does not allow iteration through all keys so I can only ask if something's set. I can't easily error out on unsupported query params. This is typical on frontend since query params often contain referrer data for tracking.
___
*[pkg/server/debug/pprofui/server.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mflbgbx5f5t3IlCM0aa:-MgE88NuDhXBhuurGssy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server.go#L45)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just putting a comment here so this doesn't get forgotten before merge.
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/server.go, line 198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MflblVh30WNsVNb2KRe:-MgE85ZaElJiAyPhSS0O:brgurbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server.go#L198)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The heap profile that is returned contains all sample indexes, so that parameter isn't relevant while fetching, just while visualizing it in the UI.
</blockquote></details>

Thanks for the clarification
___
*[pkg/server/debug/pprofui/server_test.go, line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MflcfAp5GHO7mLJGJU9:-MgBKZdo4uiwByJU5xKI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server_test.go#L95)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Needs an update.
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/server_test.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mfld3u644wZ_2_7q8bs:-MgBLeYv2IF-Ybqs0f3L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/server_test.go#L98)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

In a sense most of what this test is doing right now is testing the node redirection, which is now no longer a concern of the pprofui (since that's the statusServer.Profile endpoint's job). I think this test could work provide a mock for the status server endpoint that returns a fixed static heap profile (i.e. a fixture) and then the test really checks that requests to the pprofui server result in appropriate calls to the mocked endpoint, and that it serves up a UI that looks good (i.e. that part stays in the test). There wouldn't be a need to spin up a TestCluster.
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/storage_mem.go, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfldWkuC8tWW4AsTPs4:-MgE7kIXABFKWFY5f5hO:b3fgzol) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bafab1549edbba88a583ea299defb080b94fc4b/pkg/server/debug/pprofui/storage_mem.go#L43)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Doesn't the linter yell at you here? Returning a private struct from a public method effectively makes the method uncallable from outside the package.
I think you might be able to remove this, since you should be able to put TestServerDifferentNode into the `pprofui` package (not `pprofui_test`) if you make sure that the interface to the `status.profile` endpoint is not too dep-heavy.

If for some reason you're stuck with the `_test` package, the way we usually add these test-only accessors is to make a file `helpers_test.go` and define this method there. That way, it's only there during tests.
</blockquote></details>

Done. This ended up working out as you described. Thanks!


<!-- Sent from Reviewable.io -->

2021-08-06 17:52 UTC, rimadeodhar reviewed
Seems fine overall. I find the disableLabels nomenclature confusing so I have some comments around that, but the code looks good.

> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-:-MgRZbdy4aQGXU1njWki:b-fwxdad)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @tbg)

___
*[pkg/server/tenant.go, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MfX7yz89mQvSzJ2yrpB:-MgRUeXI5xl-dm4ScY0O:b-7lgz4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7156e74ca798cc4921d16609bfea202e0404b4f2/pkg/server/tenant.go#L139)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Agreed. I implemented 1) with support only for local profiling. Once my fan-out PR is merged we could add that to tenants but I think just supporting profiles in "local" mode should cover most use cases.
</blockquote></details>

Yes I agree, I think local mode should likely suffice here.
___
*[pkg/server/tenant_status.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_QslAuuJ5iFUb5vX:-MgR_QslAuuJ5iFUb5vY:b-bh4f6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L146)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// This implementation is replacing profiling code that was previously
> 	// embedded in the debug server. In order to preserve the ability to
> 	// request profiles, no additional credential checking is done on
> 	// this level.
> ```
</details>


We should add a comment to this exported method.
___
*[pkg/server/tenant_status.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_e4g1qkVmKLsi2zr:-MgR_e4g1qkVmKLsi2zs:b-ez6a7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L154)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// This implementation is replacing profiling code that was previously
> 	// embedded in the debug server. In order to preserve the ability to
> 	// request profiles, no additional credential checking is done on
> 	// this level.
> ```
</details>

This comment feels a bit unnecessary to me. I think having a documentation style comment for this method should be good enough?
___
*[pkg/server/tenant_status.go, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_kFnDItCYJV0Fy-f:-MgR_kFnDItCYJV0Fy-g:bqcelwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L160)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	local := request.NodeId == "local"
> 	if !local {
> 		return nil, status.Errorf(codes.Unimplemented, "profiling arbitrary tenants is unsupported")
> 	}
> ```
</details>


The `local` variable seems unnecessary. You can just do:
```
if request.NodeId != "local" {
...
}
```
___
*[pkg/server/debug/pprofui/server.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgRZ8bi6EBzNS-XO4vS:-MgRZ8bi6EBzNS-XO4vT:bpvlxaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/debug/pprofui/server.go#L217)):*
> ```Go
> 				return err
> 			}
> 			profileReq.DisableLabels = !labels
> ```

I find the DisableLabels logic very confusing. Why not just call it labels and have it be the same as what is passed in? What does it mean for DisableLabels to be set to false by default? Does it mean labels are enabled by default?
___
*[pkg/server/serverpb/status.pb.go, line 0 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgRX_5M7fn4h21xv1uk:-MgRX_5N1VPOICIZMhoq:buh3o5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/serverpb/status.pb.go#L0)):*
Was this file included by mistake?


<!-- Sent from Reviewable.io -->

2021-08-26 22:22 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[pkg/server/tenant_status.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_QslAuuJ5iFUb5vX:-Mi2hmD30SyJ1qu1Aw2s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L146)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ```
> 	// This implementation is replacing profiling code that was previously
> 	// embedded in the debug server. In order to preserve the ability to
> 	// request profiles, no additional credential checking is done on
> 	// this level.
> ```

We should add a comment to this exported method.
</blockquote></details>

Done.
___
*[pkg/server/tenant_status.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_e4g1qkVmKLsi2zr:-Mi2hl1f0mHSSnh1gv1W:b-ho5wpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L154)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ```
> 	// This implementation is replacing profiling code that was previously
> 	// embedded in the debug server. In order to preserve the ability to
> 	// request profiles, no additional credential checking is done on
> 	// this level.
> ```
This comment feels a bit unnecessary to me. I think having a documentation style comment for this method should be good enough?
</blockquote></details>

Agreed. Done.
___
*[pkg/server/tenant_status.go, line 160 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgR_kFnDItCYJV0Fy-f:-Mi2hs0H8IKxLQ98bFyt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/tenant_status.go#L160)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

> ```
> 	local := request.NodeId == "local"
> 	if !local {
> 		return nil, status.Errorf(codes.Unimplemented, "profiling arbitrary tenants is unsupported")
> 	}
> ```

The `local` variable seems unnecessary. You can just do:
```
if request.NodeId != "local" {
...
}
```
</blockquote></details>

Done.
___
*[pkg/server/debug/pprofui/server.go, line 217 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgRZ8bi6EBzNS-XO4vS:-Mi2i0hm99U4u4_x-8Uo:b-a4mjw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/debug/pprofui/server.go#L217)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

I find the DisableLabels logic very confusing. Why not just call it labels and have it be the same as what is passed in? What does it mean for DisableLabels to be set to false by default? Does it mean labels are enabled by default?
</blockquote></details>

Done. I looked and there there's only one other callsite with a CPU profile (just in debug zip generation) so I flipped the boolean and updated the callsite to set the flag explicitly.
___
*[pkg/server/serverpb/status.pb.go, line  at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-MgRX_5M7fn4h21xv1uk:-Mi2k4ON0w44ZYRx-l5c:b-h4rb9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c4989f90bd4136209af2ccf31a496a6044ee3102/pkg/server/serverpb/status.pb.go#L)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Was this file included by mistake?
</blockquote></details>

Nope, I made proto changes so it's necessary.


<!-- Sent from Reviewable.io -->

2021-08-27 20:51 UTC, tbg approved these changes
Really cool to see what can be done when someone knows both how to write front-end and back-end code. :-)
Looking forward to seeing this in 21.2! This all looks good to me from a high level, I didn't look too closely at the details this time around, let me know if anything needs a closer look.

> Reviewed 3 of 16 files at r3, 1 of 9 files at r4, 16 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-:-Mi8Miok5ljU1ss3u51S:bspvixp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rimadeodhar)

___
*[pkg/server/debug/pprofui/server_test.go, line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mi8M7dW9ifHqvezkQHf:-Mi8M7dX6MTIS8D0qMsq:b4b0992) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca45f22bea63e1d2a96e2fc1a30ff49323e62b07/pkg/server/debug/pprofui/server_test.go#L104)):*
> ```Go
> 		s.ServeHTTP(w, r)
> 
> 		if a, e := w.Code, http.StatusTemporaryRedirect; a != e {
> ```

in case you're interested, we would typically use the more compact `require.Equal(t, e, a)` here and in general.


<!-- Sent from Reviewable.io -->

2021-08-30 16:01 UTC, dhartunian reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar and @tbg)

___
*[pkg/server/debug/pprofui/server_test.go, line 104 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68019#-Mi8M7dW9ifHqvezkQHf:-MiMmgiPDFezmeQx22ym:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca45f22bea63e1d2a96e2fc1a30ff49323e62b07/pkg/server/debug/pprofui/server_test.go#L104)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

in case you're interested, we would typically use the more compact `require.Equal(t, e, a)` here and in general.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 21:34 UTC, rimadeodhar approved these changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68019)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)



<!-- Sent from Reviewable.io -->

2021-09-14 14:03 UTC, dhartunian commented
bors r+

2021-09-14 15:33 UTC, merged

2021-10-04 20:44 UTC, dhartunian commented
blathers backport 21.2