opt: fix bug in lookup join range spans
cockroachdb/cockroach pull request #68214
Opened 2021-07-29 00:31 UTC by cucaroach

multiSpanGenerator.fillInIndexColInfos is a convoluted beast that wasn't
properly initializing multiSpanGeneratorInequalityColInfo's for bounded
inequalities.  Rearrange the code to be a little clearer.

Release note (none)

2021-07-29 00:31 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68214)
<!-- Reviewable:end -->

2021-07-29 16:10 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mfn0dHj0Egefbze7gVZ:-Mfn0dHj0Egefbze7gV_:by2203r) ([raw file](https://github.com/cockroachdb/cockroach/blob/907530af1ff64cbf09a067644e6bca29dd1b9f04/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L486)):*
> ```
> 
> statement ok
> create table order_line (ol_o_id int, ol_i_id int);
> ```

[nit] we try to keep SQL styled the same way throughout these files. You can run it through `cockroach sqlfmt` (or http://sqlfum.pt)


<!-- Sent from Reviewable.io -->

2021-07-30 13:44 UTC, cucaroach reviewed
RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-Mfre8LW6EQ5zn6KUFJJ:b-828fnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mfn0dHj0Egefbze7gVZ:-Mfre-3UE_6shASJ93Bo:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/907530af1ff64cbf09a067644e6bca29dd1b9f04/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L486)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we try to keep SQL styled the same way throughout these files. You can run it through `cockroach sqlfmt` (or http://sqlfum.pt)
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2021-07-30 19:20 UTC, RaduBerinde reviewed
Left some minor comments, please also get a review from someone who reviewed the original change (I'm not familiar with this code at all).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-Mfsqz802kemQrbjloEY:b-bu1xbp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 486 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mfn0dHj0Egefbze7gVZ:-Mfsp8Zd99xZI2a0uMU6:brqro5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/907530af1ff64cbf09a067644e6bca29dd1b9f04/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L486)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

[nit] `;` is not needed
___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mfsp5238-uizBADGe6B:-Mfsp5238-uizBADGe6C:brwxdhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L489)):*
> ```
> INSERT
> INTO
> 	order_line (ol_o_id, ol_i_id)
> ```

[nit] use spaces not tabs in these files
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 856 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspAH3A5k0ImErUh0r:-MfspAH3A5k0ImErUh0s:bb7ozr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L856)):*
> ```
> INSERT
> INTO
> 	order_line (ol_o_id, ol_i_id)
> ```

tabs
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 865 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspAliEfaaPb3v7QRJ:-MfspAliEfaaPb3v7QRK:bb7ozr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L865)):*
> ```
> query T kvtrace(Scan,prefix=/Table/56/2/6463/{)
> SELECT
> 	s_i_id, ol_o_id
> ```

tabs
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspTQj0zo_01bKYOz4:-MfspTQj0zo_01bKYOz5:bfglwzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L518)):*
> ```Go
> 		}
> 
> 		if len(g.indexColInfos) <= idxOrd {
> ```

[nit] this "slice extension" deserves a comment
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspfyvEZzSYbNWXH5X:-MfspfyvEZzSYbNWXH5Y:b-dkl7ea) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L529)):*
> ```Go
> 			var inequalityInfo *multiSpanGeneratorInequalityColInfo
> 			if colInfo != nil {
> 				i, ok := colInfo.(multiSpanGeneratorInequalityColInfo)
> ```

Storing structs directly as interfaces is 99% of the time a bad idea. It incurs an allocation every time we assign an interface to the struct, so a pointer to struct ends up being better.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-MfsqBrUDO7lSG3i8K4l:b-vzi511) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
> ```Go
> 				}
> 			}
> 			info = *inequalityInfo
> ```

Why is inequalityInfo a pointer if we're copying it by value anyway?


<!-- Sent from Reviewable.io -->

2021-07-30 23:57 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mfsp5238-uizBADGe6B:-MftnrLB8zk5F8OJIv2C:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L489)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] use spaces not tabs in these files
</blockquote></details>

Done
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspfyvEZzSYbNWXH5X:-MftpNeqDpRJVL3_7qhd:b-b0lm8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Storing structs directly as interfaces is 99% of the time a bad idea. It incurs an allocation every time we assign an interface to the struct, so a pointer to struct ends up being better.
</blockquote></details>

You might have to elaborate for me.   Are you saying multiSpanGenerator.indexColInfo's shouldn't be a slice of the interface but pointers to the interface?   
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-Mftpvf88gKnFRdZFZy2:b-lcun33) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is inequalityInfo a pointer if we're copying it by value anyway?
</blockquote></details>

Well they are little so I don't think its material but I wanna do whatever is idiomatic so you think this would be better if I just had a slice of multiSpanGeneratorColInfo pointers?


<!-- Sent from Reviewable.io -->

2021-07-31 00:00 UTC, cucaroach reviewed
I won't push until @rytaft chimes in, I think she wrote most of this code, hopefully I didn't defile it too much!   I left her off the review since she was going on vacation but now that she's off I'll put her on, my only concern is that this bug affect ones of the TPCE queries, maybe I should just tell @nvanbenschoten about it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-MftqSK53x_h3bxTEnm1:b-spukxo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)



<!-- Sent from Reviewable.io -->

2021-07-31 15:47 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspfyvEZzSYbNWXH5X:-MfxD3pSBpF2htDKHQEy:byi26nm) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L529)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

You might have to elaborate for me.   Are you saying multiSpanGenerator.indexColInfo's shouldn't be a slice of the interface but pointers to the interface?   
</blockquote></details>

Wait, I am confused. I see now that `multiSpanGeneratorInequalityColInfo` is an interface, I thought it was a struct. I don't understand at all what we're doing here. If indexColInfos[i] (and thus colInfo) is a `multiSpanGeneratorInequalityColInfo`, why are we casting down to it? Seems like a no-op (or a fancy nil check?)

That makes `inequalityInfo` even more sketchy, pointers to interfaces are usually a red flag.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-MfxDE1w03YzHAYIM8n5:b-7t3v0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Well they are little so I don't think its material but I wanna do whatever is idiomatic so you think this would be better if I just had a slice of multiSpanGeneratorColInfo pointers?
</blockquote></details>

Allocations are material - there is a per-object cost regardless of object size. These can easily pile up if we're not paying attention.

AFAICT `inequalityInfo` should just be of `multiSpanGeneratorColInfo` type.


<!-- Sent from Reviewable.io -->

2021-08-02 12:17 UTC, cucaroach reviewed
I added @mgartner to the review, he seems to have reviewed most of the prior work in this area.   TIA Marcus!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-Mfw77eX2pd5o1ruClFx:bl49748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspfyvEZzSYbNWXH5X:-Mg5Y5z5AI4J4uFmAx76:bxp57ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Wait, I am confused. I see now that `multiSpanGeneratorInequalityColInfo` is an interface, I thought it was a struct. I don't understand at all what we're doing here. If indexColInfos[i] (and thus colInfo) is a `multiSpanGeneratorInequalityColInfo`, why are we casting down to it? Seems like a no-op (or a fancy nil check?)

That makes `inequalityInfo` even more sketchy, pointers to interfaces are usually a red flag.
</blockquote></details>

So indexColInfos is a slice of multiSpanGeneratorColInfo which can be one of 3 types, multiSpanGeneratorValuesColInfo, multiSpanGeneratorIndexVarColInfo or multiSpanGeneratorInequalityColInfo.   
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-Mg5b2V67nJhh07SWBLG:buv7j64) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Allocations are material - there is a per-object cost regardless of object size. These can easily pile up if we're not paying attention.

AFAICT `inequalityInfo` should just be of `multiSpanGeneratorColInfo` type.
</blockquote></details>

Sure but in this context its not material, ie fillInIndexColInfos is a setup step called once per multiSpanGenerator init.  multiSpanGeneratorColInfo is the (mostly empty)  interface type of my slice, I don't see anything wrong with the approach but I'm ready to be shown otherwise!     I'm trying to fill in a multiSpanGeneratorInequalityColInfo here and make sure updates to it get back into the indexColInfos slice.   Sometimes we're updating a new one and sometimes we're updating an existing one already in the slice, hence the pointer.   I guess in the colInfo == nil path I could stick the new multiSpanGeneratorInequalityColInfo into the slice and avoid the struct copy, would that make things clearer?


<!-- Sent from Reviewable.io -->

2021-08-02 13:31 UTC, RaduBerinde reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfspfyvEZzSYbNWXH5X:-Mg5xDYJ5gVOxRj7JBu7:bia2jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L529)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

So indexColInfos is a slice of multiSpanGeneratorColInfo which can be one of 3 types, multiSpanGeneratorValuesColInfo, multiSpanGeneratorIndexVarColInfo or multiSpanGeneratorInequalityColInfo.   
</blockquote></details>

Oh, I see, sorry.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-Mg5zPZc7q8VBxKQQKpV:bxbmjfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
> make sure updates to it get back into the indexColInfos slice. Sometimes we're updating a new one and sometimes we're updating an existing one already in the slice, hence the pointer

But we're not - we're modifying `i`, our local copy of the struct. It makes its way back into the slice because we're doing `g.indexColInfos[idxOrd] = info` at the end, not because it's a pointer.

This code incurs two allocations that might not be obvious:
 - one where we put `i` on the heap
 - one where we allocate a new heap copy of `*inequalityInfo` to store it into `info`

I would agree with you that it's probably immaterial (I say probably because "once" still means "once per query") but it's an indication of a poor pattern.

Just making `inequalityInfo` a non-pointer is a simple (and simplifying) change that would get rid of the first allocation:

```diff
-			var inequalityInfo *multiSpanGeneratorInequalityColInfo
+			var inequalityInfo multiSpanGeneratorInequalityColInfo
 			if colInfo != nil {
-				i, ok := colInfo.(multiSpanGeneratorInequalityColInfo)
-				if !ok {
-					panic(errors.AssertionFailedf("unexpected colInfo type"))
-				}
-				inequalityInfo = &i
-			} else {
-				inequalityInfo = &multiSpanGeneratorInequalityColInfo{}
+				inequalityInfo = colInfo.(multiSpanGeneratorInequalityColInfo)
 			}
 
 			if lval != nil {
@@ -555,7 +549,7 @@ func (g *multiSpanGenerator) fillInIndexColInfos(expr tree.TypedExpr) error {
 					inequalityInfo.startInclusive = t.Operator.Symbol == tree.GE
 				}
 			}
-			info = *inequalityInfo
+			info = inequalityInfo
```


<!-- Sent from Reviewable.io -->

2021-08-02 13:48 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MfsqBrUDO7lSG3i8K4k:-Mg66ZPP3PQbh6XmQmhb:bjf8o4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/20bfe58d33b834634837a1c0a169d7651d3f1b1d/pkg/sql/rowexec/joinreader_span_generator.go#L557)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

> make sure updates to it get back into the indexColInfos slice. Sometimes we're updating a new one and sometimes we're updating an existing one already in the slice, hence the pointer

But we're not - we're modifying `i`, our local copy of the struct. It makes its way back into the slice because we're doing `g.indexColInfos[idxOrd] = info` at the end, not because it's a pointer.

This code incurs two allocations that might not be obvious:
 - one where we put `i` on the heap
 - one where we allocate a new heap copy of `*inequalityInfo` to store it into `info`

I would agree with you that it's probably immaterial (I say probably because "once" still means "once per query") but it's an indication of a poor pattern.

Just making `inequalityInfo` a non-pointer is a simple (and simplifying) change that would get rid of the first allocation:

```diff
-			var inequalityInfo *multiSpanGeneratorInequalityColInfo
+			var inequalityInfo multiSpanGeneratorInequalityColInfo
 			if colInfo != nil {
-				i, ok := colInfo.(multiSpanGeneratorInequalityColInfo)
-				if !ok {
-					panic(errors.AssertionFailedf("unexpected colInfo type"))
-				}
-				inequalityInfo = &i
-			} else {
-				inequalityInfo = &multiSpanGeneratorInequalityColInfo{}
+				inequalityInfo = colInfo.(multiSpanGeneratorInequalityColInfo)
 			}
 
 			if lval != nil {
@@ -555,7 +549,7 @@ func (g *multiSpanGenerator) fillInIndexColInfos(expr tree.TypedExpr) error {
 					inequalityInfo.startInclusive = t.Operator.Symbol == tree.GE
 				}
 			}
-			info = *inequalityInfo
+			info = inequalityInfo
```

</blockquote></details>

Nice that is cleaner, thanks!


<!-- Sent from Reviewable.io -->

2021-08-02 15:21 UTC, mgartner reviewed
> Release note (none)

Release notes are automatically aggregated by a script that reads commits. I'm not sure if this will cause problems, but the format for a commit with no release notes is `Release note: None`.

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-Mg6LzDHBOtSVDKZzdqu:b-iecsiv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @RaduBerinde, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/lookup_join_spans, line 485 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6MLQUD9qcsdQqCuA7:-Mg6MLQUD9qcsdQqCuA8:bdogza2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/logictest/testdata/logic_test/lookup_join_spans#L485)):*
> ```
> 1  2020-01-01 00:00:01 +0000 UTC  1  1  1  NULL  cpu
> 
> statement ok
> ```

nit: Add a comment explaining that this is a regression test for #68200 and explain what it's testing.
___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 852 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6MXmKClmKokBGYsyX:-Mg6MXmKClmKokBGYsyY:bth8ngl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L852)):*
> ```
> 
> 
> statement ok
> ```

nit: Add a note that this is a regression test for #68200.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-Mg6QeiR9PEk8rH4dJJz:b-ul3uak) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
> ```Go
> 			var inequalityInfo multiSpanGeneratorInequalityColInfo
> 			if colInfo != nil {
> 				inequalityInfo = colInfo.(multiSpanGeneratorInequalityColInfo)
> ```

Would it ever be possible for this to be a `multiSpanGeneratorIndexVarColInfo` or a `multiSpanGeneratorValuesColInfo`?

The optimizer should normalize something like `a = 1 AND a >= 1` to `a = 1` by the optimizer. But I don't think `a IN (1, 2, 3) AND a > 1` will be normalized to `a IN (2, 3)`. Is it possible that such an expression is chosen as a lookup expression?


<!-- Sent from Reviewable.io -->

2021-08-02 16:24 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 852 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6MXmKClmKokBGYsyX:-Mg6f7cME0WnEzaT6xZT:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L852)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Add a note that this is a regression test for #68200.
</blockquote></details>

:+1: 
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-Mg6b_oP4QS0axFOBCWk:b-uxsnh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would it ever be possible for this to be a `multiSpanGeneratorIndexVarColInfo` or a `multiSpanGeneratorValuesColInfo`?

The optimizer should normalize something like `a = 1 AND a >= 1` to `a = 1` by the optimizer. But I don't think `a IN (1, 2, 3) AND a > 1` will be normalized to `a IN (2, 3)`. Is it possible that such an expression is chosen as a lookup expression?
</blockquote></details>

I hope not!    This fear is the reason behind (https://github.com/cockroachdb/cockroach/issues/65773) and why there's a TODO referencing it at the top of this function.   Currently if you mix an inequality and a const expression like this we won't use the lookupExpr stuff and we'll fall back to the key column equalities with a filter.


<!-- Sent from Reviewable.io -->

2021-08-02 17:01 UTC, mgartner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-Mg6kuEl-BVWdKgFlbvZ:bvxl2tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

I hope not!    This fear is the reason behind (https://github.com/cockroachdb/cockroach/issues/65773) and why there's a TODO referencing it at the top of this function.   Currently if you mix an inequality and a const expression like this we won't use the lookupExpr stuff and we'll fall back to the key column equalities with a filter.
</blockquote></details>

I see. We find constant filters before we search for inequality filters here: https://github.com/cockroachdb/cockroach/blob/e45a521e5cd10441efcd95ed9d89319c2f9e529d/pkg/sql/opt/xform/join_funcs.go#L296-L308

But it does scare me that nothing in [`isCanonicalLookupJoinFilter`](https://github.com/cockroachdb/cockroach/blob/e45a521e5cd10441efcd95ed9d89319c2f9e529d/pkg/sql/opt/xform/join_funcs.go#L628) prevents this type of filter from being chosen.

I've confirmed that if you switch the order so that we search for inequality filters before constant filters, you get a panic during execution.

Can you add on this test case which would catch this bug?

```
query II
SELECT
  s_i_id, ol_o_id
FROM
  stock INNER LOOKUP JOIN order_line ON s_i_id = ol_i_id
WHERE
  ol_o_id IN (19, 20) AND ol_o_id >= 20
----
6463  20
```

I also think we should update `isCanonicalLookupJoinFilter` so that it doesn't allow any expressions that are not supported by execution.

I'd also leave a note here during this conversion to explain why it is safe to assume the type of the `colinfo`.


<!-- Sent from Reviewable.io -->

2021-08-03 17:33 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-Mg7R6b1BfCBmp_esdzi:b-xnf4tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see. We find constant filters before we search for inequality filters here: https://github.com/cockroachdb/cockroach/blob/e45a521e5cd10441efcd95ed9d89319c2f9e529d/pkg/sql/opt/xform/join_funcs.go#L296-L308

But it does scare me that nothing in [`isCanonicalLookupJoinFilter`](https://github.com/cockroachdb/cockroach/blob/e45a521e5cd10441efcd95ed9d89319c2f9e529d/pkg/sql/opt/xform/join_funcs.go#L628) prevents this type of filter from being chosen.

I've confirmed that if you switch the order so that we search for inequality filters before constant filters, you get a panic during execution.

Can you add on this test case which would catch this bug?

```
query II
SELECT
  s_i_id, ol_o_id
FROM
  stock INNER LOOKUP JOIN order_line ON s_i_id = ol_i_id
WHERE
  ol_o_id IN (19, 20) AND ol_o_id >= 20
----
6463  20
```

I also think we should update `isCanonicalLookupJoinFilter` so that it doesn't allow any expressions that are not supported by execution.

I'd also leave a note here during this conversion to explain why it is safe to assume the type of the `colinfo`.
</blockquote></details>

Good call on the test case and I'll beef up the comments.   I'm not sure what to think about isCanonicalLookupJoinFilter ... I guess to ensure correctness we should split it into isCanonicalLookupJoinRangeFilter and isCanonicalLookupJoinConstFilter so we don't get confused by examples like yours.   I think I had over-generalize-itis and tried to merge the two paths too much.


<!-- Sent from Reviewable.io -->

2021-08-03 18:00 UTC, mgartner commented
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-MgC8_U175jKry-2ktIH:bh2yron) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Good call on the test case and I'll beef up the comments.   I'm not sure what to think about isCanonicalLookupJoinFilter ... I guess to ensure correctness we should split it into isCanonicalLookupJoinRangeFilter and isCanonicalLookupJoinConstFilter so we don't get confused by examples like yours.   I think I had over-generalize-itis and tried to merge the two paths too much.
</blockquote></details>

:+1: Ya that sounds like that could be the best solution.

To really catch things like this we could write a test that generates a random expression and if `isCanonicalLookupJoinRangeFilter/isCanonicalLookupJoinConstFilter` returns true, attempts to generate spans with a `multiSpanGenerator` to ensure there are no panics and the output is well-formed. I'm not sure exactly where that test would live (there might be some dependency cycles). It might make sense to move `isCanonicalLookupJoinRangeFilter/isCanonicalLookupJoinConstFilter` to the `rowexec` package to keep them close to the implementation details of span generation, but again, that might create dependency cycles. But this is all just ideas that we might want to pursue, not something needed for this PR.


<!-- Sent from Reviewable.io -->

2021-08-09 19:09 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-MggJQ8UBlQbj0Pw4VLz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 873 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MggGB5760l-2dd_evKr:-MggGB5760l-2dd_evKs:b3pclk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bc004f657ca45059d400c8003c83bfbdd0037c/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L873)):*
> ```
>   ol_o_id BETWEEN 20 AND 100
> ----
> Scan /Table/56/2/6463/{20-101}
> ```

would be good to add the explain output for this query too.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-MggIOAD5Asp05rQsfDR:b-88swdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

:+1: Ya that sounds like that could be the best solution.

To really catch things like this we could write a test that generates a random expression and if `isCanonicalLookupJoinRangeFilter/isCanonicalLookupJoinConstFilter` returns true, attempts to generate spans with a `multiSpanGenerator` to ensure there are no panics and the output is well-formed. I'm not sure exactly where that test would live (there might be some dependency cycles). It might make sense to move `isCanonicalLookupJoinRangeFilter/isCanonicalLookupJoinConstFilter` to the `rowexec` package to keep them close to the implementation details of span generation, but again, that might create dependency cycles. But this is all just ideas that we might want to pursue, not something needed for this PR.
</blockquote></details>

I think it's probably worth checking this and returning an assertion error if it's not the right type. e.g.:
```
inequalityInfo, ok = colInfo.(multiSpanGeneratorInequalityColInfo)
if !ok {
  return errors.AssertionFailedf(...)
}
```


<!-- Sent from Reviewable.io -->

2021-08-11 17:28 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-MgqCSAL073tW91AR0OZ:b-97wzlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think it's probably worth checking this and returning an assertion error if it's not the right type. e.g.:
```
inequalityInfo, ok = colInfo.(multiSpanGeneratorInequalityColInfo)
if !ok {
  return errors.AssertionFailedf(...)
}
```
</blockquote></details>

:+1:   So the difference would be that if we didn't check it we'd get a panic which would terminate our goroutine and the assertion would be passed up the callstack?   How do we think about which to do when?


<!-- Sent from Reviewable.io -->

2021-08-11 19:26 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans, line 873 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-MggGB5760l-2dd_evKr:-MgqfTCv6HSPw8VbzCR5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4bc004f657ca45059d400c8003c83bfbdd0037c/pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans#L873)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

would be good to add the explain output for this query too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-11 20:07 UTC, mgartner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-:-Mgqos3X3zd1Wa8s8RoW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)



<!-- Sent from Reviewable.io -->

2021-08-16 14:19 UTC, rytaft approved these changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-MhEDkHm1sKSkA-c49u9:b-d77ptd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

:+1:   So the difference would be that if we didn't check it we'd get a panic which would terminate our goroutine and the assertion would be passed up the callstack?   How do we think about which to do when?
</blockquote></details>

If you are writing code in the execution engine, you should almost always try to avoid panics and return an error (most functions will include an error in the return params). There are some top-level panic catchers in the execution engine, but it's best not to rely on them. Using `AssertionFailedf` will ensure that the error and stack trace still get logged to sentry and will open a GitHub issue, etc, so there's really no reason to use panics for errors like this in the execution engine. Panics should be reserved for cases where you really want the node to crash, because the server is in an unhealthy state it cannot recover from without restarting.

In the optimizer we often use panics to avoid the constant need to check for errors (panics are caught at the top level of the optimizer), but in a case like this in the optimizer I would still add the check and just call `panic(errors.AssertionFailedf(...))` to ensure all the necessary information was included in the error message. I'd only skip the check if I was *really* confident the type assertion would never fail (obviously there still might be a bug, in which case the panic catcher would catch it too, but we try avoid truly unexpected panics).

As described here, we can catch panics in the optimizer because the code doesn't update shared state or manipulate locks: https://github.com/cockroachdb/cockroach/blob/fff814fca119dbc37f88ea368a554f1613096c9a/pkg/sql/opt/optbuilder/builder.go#L172
Also see https://github.com/cockroachdb/cockroach/issues/63946, which explains how this isn't always accurate.


<!-- Sent from Reviewable.io -->

2021-08-23 16:38 UTC, cucaroach reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68214)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 530 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68214#-Mg6QeiR9PEk8rH4dJJy:-Mhnrw-o6WRWA5oDPeM3:b-wsvasg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1751b25cf312faec31cf6df4e5a1a7da2cf826f4/pkg/sql/rowexec/joinreader_span_generator.go#L530)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

If you are writing code in the execution engine, you should almost always try to avoid panics and return an error (most functions will include an error in the return params). There are some top-level panic catchers in the execution engine, but it's best not to rely on them. Using `AssertionFailedf` will ensure that the error and stack trace still get logged to sentry and will open a GitHub issue, etc, so there's really no reason to use panics for errors like this in the execution engine. Panics should be reserved for cases where you really want the node to crash, because the server is in an unhealthy state it cannot recover from without restarting.

In the optimizer we often use panics to avoid the constant need to check for errors (panics are caught at the top level of the optimizer), but in a case like this in the optimizer I would still add the check and just call `panic(errors.AssertionFailedf(...))` to ensure all the necessary information was included in the error message. I'd only skip the check if I was *really* confident the type assertion would never fail (obviously there still might be a bug, in which case the panic catcher would catch it too, but we try avoid truly unexpected panics).

As described here, we can catch panics in the optimizer because the code doesn't update shared state or manipulate locks: https://github.com/cockroachdb/cockroach/blob/fff814fca119dbc37f88ea368a554f1613096c9a/pkg/sql/opt/optbuilder/builder.go#L172
Also see https://github.com/cockroachdb/cockroach/issues/63946, which explains how this isn't always accurate.
</blockquote></details>

Thanks for the explanation!


<!-- Sent from Reviewable.io -->

2021-08-24 14:17 UTC, cucaroach commented
TFTRs!
bors r+

2021-08-25 13:14 UTC, cucaroach commented
bors r+

2021-08-25 13:56 UTC, merged