changefeedccl: allow changefeeds on regional by row tables
cockroachdb/cockroach pull request #68229
Opened 2021-07-29 11:36 UTC by stevendanna

Previously we explicitly disallowed changefeeds on regional by row
tables because:

1) the Avro encoder lacked enum support,
2) the schema feed did not correctly identify RBR schema changes as
   both a column addition and a primary key change, and
3) we were unsure whether users would be OK seeing the new crdb_region
   column in their changefeed output.

Both (1) and (2) have since been fixed in
8113beda91a6c3791208632ecad075f6ca0a95b6 and
cd687ded12d717032f0966eca37b9c0845ee8d57, respectively.

For (3) we've decided that changefeeds should rather faithfully emit
what KV tells us about. Future work to support projections and
predicate filtering may allow _users_ to filter what gets output, but
until then we want to err on the side of avoiding ad-hoc modifications
to the changefeed output. Thus, we are OK emitting the crdb_region
column as-is both in the row data and as part of the primary key.

Release note (enterprise change): CHANGEFEEDs no longer fail when
started on REGIONAL BY ROW tables. Note that in REGION BY ROW tables,
the crdb_region column becomes part of the primary index. Thus,
changing an existing table to REGIONAL BY ROW will trigger a
changefeed backfill with new messages emitted using the new composite
primary key.

2021-07-29 11:36 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68229)
<!-- Reviewable:end -->

2021-07-29 14:40 UTC, HonoreDB requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-Mfmgi8GA2aGuqncaJ53:-Mfmgi8GA2aGuqncaJ54:btxhkh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbea9dca10d0cd417c96201d4f7116ad1142046/pkg/ccl/changefeedccl/changefeed_test.go#L1560)):*
> ```Go
> 			assertPayloads(t, rbr, []string{
> 				`rbr: {"a":{"long":0},"crdb_region":{"string":"us-east-1"}}->{"after":{"rbr":{"a":{"long":0},"b":null,"crdb_region":{"string":"us-east-1"}}}}`,
> 				`rbr: {"a":{"long":1},"crdb_region":{"string":"us-east-1"}}->{"after":{"rbr":{"a":{"long":1},"b":{"long":2},"crdb_region":{"string":"us-east-1"}}}}`,
> ```

Would you mind adding a test that `ADD REGION` works correctly here? I'm not 100% confident that the schemafeed will pick that up.
___
*[pkg/ccl/changefeedccl/helpers_test.go, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfmgDGE3UjlFYrOU5tl:-MfmgDGE3UjlFYrOU5tm:b-89q77x) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbea9dca10d0cd417c96201d4f7116ad1142046/pkg/ccl/changefeedccl/helpers_test.go#L513)):*
> ```Go
> // RunRandomSink runs the testFn against one of a number of possible
> // sinks. Sinkless is not included in the possible sinks.
> func RunRandomSinkTest(t *testing.T, desc string, testFn cdcTestFn, testOpts ...feedTestOption) {
> ```

Cool!


<!-- Sent from Reviewable.io -->

2021-07-30 10:35 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-Mfmgi8GA2aGuqncaJ53:-MfqyYkw4_-iNBHSIgx8:biixixm) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbea9dca10d0cd417c96201d4f7116ad1142046/pkg/ccl/changefeedccl/changefeed_test.go#L1560)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Would you mind adding a test that `ADD REGION` works correctly here? I'm not 100% confident that the schemafeed will pick that up.
</blockquote></details>

Good call.  Good news is that it looks like it does pick it up correctly.

Testing `ADD REGION` requires a multi-server cluster so that there are multiple live regions in the cluster, so I've added it in a different test function since the setup is a bit bespoke. 


<!-- Sent from Reviewable.io -->

2021-07-30 12:38 UTC, ajstorm reviewed
Nice to see this get done! :tada: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-:-MfrPsNI4Y0zJvwhjhlc:bd7zw29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrP2HA3CVmiyIpCDfb:-MfrP2HA3CVmiyIpCDfc:b-dxf9kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1557)):*
> ```Go
> 				`rbr: {"a":{"long":1}}->{"after":{"rbr":{"a":{"long":1},"b":{"long":2}}}}`,
> 			})
> 			sqlDB.Exec(t, `ALTER TABLE rbr SET LOCALITY REGIONAL BY ROW`)
> ```

Does it make sense to also test `REGIONAL BY ROW AS`?  It should just work, but might be worth validating.


<!-- Sent from Reviewable.io -->

2021-07-30 15:05 UTC, HonoreDB reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrwLWl30XMqHCXnbOt:-MfrwLWl30XMqHCXnbOu:b5kclqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1611)):*
> ```Go
> 	// expect the new rows with the added region to be encoded
> 	// correctly.
> 	sqlDB.Exec(t, `ALTER DATABASE d ADD REGION "us-east2"`)
> ```

Per the test failure there's a race condition here where this statement will fail if the DDL stuff from I guess the ALTER TABLE is still running? But it's weird, you'd think assertPayloads would ensure it was all done by now.


<!-- Sent from Reviewable.io -->

2021-07-30 15:26 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrwLWl30XMqHCXnbOt:-Mfrz5IF0L9pNN6MRs0R:b-hmdb7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1611)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Per the test failure there's a race condition here where this statement will fail if the DDL stuff from I guess the ALTER TABLE is still running? But it's weird, you'd think assertPayloads would ensure it was all done by now.
</blockquote></details>

Yeah, we have some code that can wait for a schema change to run that we can use here, but I'll try to spend a few minutes to at least understand why we are seeing the correct post-schema-change row above yet still getting an error here that the schema change isn't finished.


<!-- Sent from Reviewable.io -->

2021-08-02 11:18 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @HonoreDB, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrP2HA3CVmiyIpCDfb:-Mg5ZSYFDHSGw8E7dX8M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1557)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does it make sense to also test `REGIONAL BY ROW AS`?  It should just work, but might be worth validating.
</blockquote></details>

Done.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1611 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrwLWl30XMqHCXnbOt:-Mg5ZUUz8zu30a9u4b_N:bvflj1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1611)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Yeah, we have some code that can wait for a schema change to run that we can use here, but I'll try to spend a few minutes to at least understand why we are seeing the correct post-schema-change row above yet still getting an error here that the schema change isn't finished.
</blockquote></details>

I moved to using our waitForSchemaChange function on the first schema change. 


<!-- Sent from Reviewable.io -->

2021-08-02 13:09 UTC, miretskiy reviewed
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @HonoreDB, and @stevendanna)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-Mg5y8p78RBSgvh0TeqY:-Mg5y8p78RBSgvh0TeqZ:b6wl4js) ([raw file](https://github.com/cockroachdb/cockroach/blob/037b9e04728a6c42f1c4e8835bd0fe38645956d4/pkg/ccl/changefeedccl/helpers_test.go#L401)):*
> ```Go
> //
> // TODO(ssd): Currently, our testFeed implementations aren't
> // guaranteed to work with a multi-server cluster.
> ```

do you have anything specific that needs to be fixed?


<!-- Sent from Reviewable.io -->

2021-08-02 13:35 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-Mg5y8p78RBSgvh0TeqY:-Mg63oOt1jMPg_NcP-_t:b8p54mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/037b9e04728a6c42f1c4e8835bd0fe38645956d4/pkg/ccl/changefeedccl/helpers_test.go#L401)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you have anything specific that needs to be fixed?
</blockquote></details>

Not yet, thanks for calling this out as I meant to dig into it more.  The kafka feed works but the cloudstroage feed and webhook feed seemed to hang in a basic test and I haven't dug into why yet.


<!-- Sent from Reviewable.io -->

2021-08-03 13:09 UTC, ajstorm approved these changes
Thanks for adding that additional test.  From a MR perspective, this <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-:-MgB7N-l6O-9xTCkaBrF:b-ialo6i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 1557 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-MfrP2HA3CVmiyIpCDfb:-MgB7HTACaAN00nM3LMC:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba69f4e3208477e0135ba1ce611469cf7fda0e59/pkg/ccl/changefeedccl/changefeed_test.go#L1557)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2021-08-04 15:03 UTC, stevendanna reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @HonoreDB, @miretskiy, and @stevendanna)

___
*[pkg/ccl/changefeedccl/helpers_test.go, line 401 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-Mg5y8p78RBSgvh0TeqY:-MgB4ADPB0UNwPVgMVOf:b-9omhs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/037b9e04728a6c42f1c4e8835bd0fe38645956d4/pkg/ccl/changefeedccl/helpers_test.go#L401)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Not yet, thanks for calling this out as I meant to dig into it more.  The kafka feed works but the cloudstroage feed and webhook feed seemed to hang in a basic test and I haven't dug into why yet.
</blockquote></details>

Updated the comment here a bit to just note what you need to be careful of rather than being a TODO.


<!-- Sent from Reviewable.io -->

2021-08-05 13:54 UTC, stevendanna commented
@HonoreDB @miretskiy gentle ping :D

2021-08-05 14:32 UTC, HonoreDB approved these changes
Looks great, thanks for all this reusable cluster testing setup!

> Reviewed 1 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68229#-:-MgLiZZ_EYaikvbUiy-a:bw2xd56)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @stevendanna)



<!-- Sent from Reviewable.io -->

2021-08-05 17:12 UTC, stevendanna commented
bors r+

2021-08-05 17:55 UTC, merged