sql: fix alter sequence statement reparse failures
cockroachdb/cockroach pull request #68251
Opened 2021-07-29 20:46 UTC by e-mbrown

Related to: #60722 

There were issues reparsing alter sequence when literals
were removed. Replacing the underscores with an int solved
the issue.

Release note: None

2021-07-29 20:53 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68251)
<!-- Reviewable:end -->

2021-07-29 21:57 UTC, rafiss requested changes

2021-07-29 21:57 UTC, rafiss commented on pkg/sql/sem/tree/hide_constants.go
> +		case *NumVal:
hmm, looking through the test changes, it seems like this NumVal change didn't actually fix any of the cases. so let's actually take out the NumVal case and could you `-rewrite` the tests again? (this should also address some of the other test issues which seem to have come up with the change)

2021-07-31 03:08 UTC, rafiss requested changes
looking good! just need to get a few more cases

> Reviewed 1 of 27 files at r1, 2 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68251#-:-MfuX6Uf9gETGTChC98r:b-okgc12)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[pkg/sql/parser/testdata/alter_sequence, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68251#-MfuWh6f69x-0Z0Uc_49:-MfuWh6f69x-0Z0Uc_4A:b12uwqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e53308e909e805bbf1880ab2221455718c686673/pkg/sql/parser/testdata/alter_sequence#L70)):*
> ```
> ALTER SEQUENCE IF EXISTS a NO CYCLE CACHE 1
> ALTER SEQUENCE IF EXISTS a NO CYCLE CACHE 1 -- fully parenthesized
> ALTER SEQUENCE IF EXISTS a NO CYCLE CACHE _ -- literals removed
> ```

looks like the CACHE option needs to be updated as well
___
*[pkg/sql/sem/tree/create.go, line 1520 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68251#-MfuWubG39qzreGzA7oR:-MfuWubG39qzreGzA7oS:bi4mswe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e53308e909e805bbf1880ab2221455718c686673/pkg/sql/sem/tree/create.go#L1520)):*
> ```Go
> 			// the cache option supports expressions.
> 			if ctx.flags.HasFlags(FmtHideConstants) {
> 				ctx.WriteByte('_')
> ```

this part needs to be updated too -- as well as any other SequenceOption where a number is turned into `_`
___
*[pkg/sql/sem/tree/create.go, line 1534 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68251#-MfuX4Fw4I0pjnTnjQ6R:-MfuX4FxC2u5RWZR0jvW:b-a2xieb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e53308e909e805bbf1880ab2221455718c686673/pkg/sql/sem/tree/create.go#L1534)):*
> ```Go
> 				// the min/max value options support expressions.
> 				if ctx.flags.HasFlags(FmtHideConstants) {
> 					ctx.WriteByte('_')
> ```

this one too


<!-- Sent from Reviewable.io -->

2021-08-02 17:37 UTC, rafiss approved these changes
this looks good to me!

when you're ready, you can trigger the merge by adding a `bors r+` (or `bors r=rafiss`) comment

2021-08-02 18:15 UTC, e-mbrown commented
bors r=rafiss

2021-08-02 19:03 UTC, merged