builtin: add cardinality builtin function
cockroachdb/cockroach pull request #68263
Opened 2021-07-30 07:40 UTC by jlevesy

To ensure PostgreSQL compatibility, this commit adds a new builtin
function called `cardinality` which returns the total number of elements
present in a given array.

As Cockroach only supports at the moment 1-dimensional arrays, this
function is equivalent to `array_length(array, 1)`.

Fixes: https://github.com/cockroachdb/cockroach/issues/67996

Release note (sql change): Added cardinality builtin function that
returns the total number of elements in a given array.

2021-07-30 07:40 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=68263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=68263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=68263) it.</sub>

2021-07-30 07:40 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68263)
<!-- Reviewable:end -->

2021-07-30 20:18 UTC, rafiss commented
thanks for your contribution! it's not exactly equivalent to array_length, just similar. the important difference is the way it handles empty arrays -- if you are able to try it out on postgres you'll see that cardinality returns 0 while array_length returns null.

please address that and add a test case

2021-07-31 04:17 UTC, rafiss requested changes
this is getting close! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68263#-:-MfulySR2mcODfIlfXCQ:bjzqzm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlevesy)

___
*[pkg/sql/logictest/testdata/logic_test/builtin_function, line 1787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68263#-MfulqCO4uoTj1GEdt67:-MfulqCO4uoTj1GEdt68:bzcfmxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9fae641911207c5c552506f722b44ef3b4f3a79/pkg/sql/logictest/testdata/logic_test/builtin_function#L1787)):*
> ```
> SELECT cardinality(ARRAY[]:::int[])
> ----
> 0
> ```

can you add one more test case for `SELECT cardinality(NULL::int[])` -- it should return NULL
___
*[pkg/sql/sem/builtins/builtins.go, line 3134 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68263#-Mfud2YL45H6cx1b_Wnp:-Mfud2YL45H6cx1b_Wnq:b4ktzmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9fae641911207c5c552506f722b44ef3b4f3a79/pkg/sql/sem/builtins/builtins.go#L3134)):*
> ```Go
> 			Fn: func(_ *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				arr := tree.MustBeDArray(args[0])
> 				return tree.NewDInt(tree.DInt(arr.Len())), nil
> ```

sorry to be nitpicky, but i'm worried that if we ever do support multi-dimensional arrays, this function will not work but we won't realize. can you add a recursive implementation? (here's what i'm thinking, borrowing from the arrayLength code)

```
func cardinality(arr *tree.DArray) tree.Datum {
	if arr.ParamTyp.Family() != types.ArrayFamily {
		return tree.NewDInt(tree.DInt(arr.Len()))
	}
	card := 0
	for _, a := range arr.Array {
		card += int(tree.MustBeDInt(cardinality(tree.MustBeDArray(a))))
	}
	return tree.NewDInt(tree.DInt(card))
}
```


<!-- Sent from Reviewable.io -->

2021-07-31 08:45 UTC, jlevesy commented
Will do! Thanks for your reviews anyway 😄

2021-07-31 14:49 UTC, rafiss approved these changes
thanks for your contribution!

bors r+

2021-07-31 15:37 UTC, merged