[DNM] WIP on the Streamer
cockroachdb/cockroach pull request #68430
Opened 2021-08-04 17:02 UTC by yuzefovich

2021-08-04 17:02 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68430)
<!-- Reviewable:end -->

2021-12-08 18:40 UTC, yuzefovich commented
Some notes for reviewers:
- I haven't done any benchmarking yet because I want to get the correctness first
- there are many TODOs sprinkled in the code, I think only `TODO(RFC)` need to be addressed as part of this PR, others will be addressed later.

2021-12-10 01:26 UTC, rharding6373 requested changes
Wow, nice work! I did an incomplete first pass. I still need to take a closer look at the index join use case and the streamer and work coordinator implementations.

> Reviewed 6 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MqWw6vo77v0wkSEnu0_:b-u0d4lz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVNN857nKZmDzmFlYn:-MqVNN857nKZmDzmFlYo:b-93pkry) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L71)):*
> ```Go
> 	// details).
> 	//
> 	// In InOrder mode, responses will be delivered in reqs order.
> ```

nit: InOrder operation mode?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVNtXr5_vVsw7hqdbC:-MqVNtXr5_vVsw7hqdbD:b-v4pwy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L78)):*
> ```Go
> 	Enqueue(ctx context.Context, reqs []roachpb.RequestUnion, keys []int) error
> 
> 	// GetResults blocks until at least one result is available. If the
> ```

Can you clarify what happens when there are no more outstanding requests?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVOGC1DagaZ63E_mI1:-MqVOGC1DagaZ63E_mI2:b-lqfpl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L83)):*
> ```Go
> 	GetResults(context.Context) ([]Result, error)
> 
> 	// Cancel cancels all in-flight operations and discards all buffered results
> ```

Out of curiosity, does this also block until any requests on remote nodes are cancelled and cleaned up, too?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVOkn45MQ1XO5mxdJk:-MqVOkn45MQ1XO5mxdJl:brlaxoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L98)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// internal out-of-order execution. Out-of-order results might have to be
> 	// dropped (resulting in wasted/duplicate work) when the budget limit is
> 	// reached and the size estimates that lead to too much OoO execution were
> 	// wrong.
> ```
</details>


Super nit: It took me a couple reads to parse this, since I thought this was talking about OutOfOrder mode. Consider some rewording to avoid using "Out-of-order" as frequently.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVQ8FP35Nik82kRdu_:-MqVQ8FP35Nik82kRdua:b1lj1bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L110)):*
> ```Go
> )
> 
> // Remove an unused warning for now.
> ```

nit: add a TODO here when InOrder is supported.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVUFFQ2xRLfWxGwW1Y:-MqVUFFQ2xRLfWxGwW1Z:bk21m70) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L122)):*
> ```Go
> 	GetResp *roachpb.GetResponse
> 	// ScanResp can have a ResumeSpan in it. In that case, there will be a
> 	// further result with the continuation; that result will use the same Key.
> ```

Just to clarify, the streamer handles the continuation, so the user doesn't need to do anything except wait and interpret the results once it gets the continuation?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVXCQV8r-nzzyQjLA-:-MqVXCQV8r-nzzyQjLA0:bsps190) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L239)):*
> ```Go
> }
> 
> func (b *budget) availableLocked() int64 {
> ```

Functions that require a mutex to be held are hard to future-proof. At a minimum, please add a comment here that the mutex must be acquired before calling this function (is the [name]Locked() function name a convention to indicate this that I'm unfamiliar with?). Since the code is so short, my personal preference would be to inline the code and avoid this problem.

Do you know of any golang static thread safety analysis that CRL uses to make sure the lock is held? 
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-MqWBjLB1bCjRc3x0OWJ:b-7cx2k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
> ```Go
> 	accUsed := b.mu.used + bytes
> 	if accUsed > b.limit {
> 		accUsed = b.limit
> ```

Doesn't this mean that we can't support all the bytes requested? Should this be conveyed to the caller or be an error? 

The comment for `b.mu.used` says that it can sometimes be greater than `b.limit`, however I think that this function could always succeed and I don't think that's desirable. Let's say that `b.mu.used + bytes > b.limit` for this call to `Consume`. `accUsed` is set to `b.limit` and that is what `b.mu.acc` is successfully resized to. Ok, now `b.mu.used += bytes` and it's > `b.limit`. Next call to consume some bytes, `b.mu.used > b.limit` therefore again `b.mu.used + bytes > b.limit`. This time we don't need to resize, because `b.mu.acc.Used()` is equal to `accUsed` is equal to`b.limit`. So `b.mu.used` will keep growing, but the memory accounting won't reflect that.

Please correct me if I am misunderstanding the memory accounting.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWLgNu3YtET-59cAxC:-MqWLgNu3YtET-59cAxD:brsncnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L283)):*
> ```Go
> }
> 
> func (b *budget) WaitForBudget(ctx context.Context) {
> ```

It seems like there's a potential race condition here, where while `WaitForBudget` is in the process of being called, `Release` is called and now memory is available. If there's only one caller to `WaitForBudget` I think it's ok, since `b.waitCh` will have something in it to consume and the function will exit. But if there are multiple callers, is it possible for `WaitForBudget` to wait forever even though there's memory available?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWRnvGDld1klPsfe3M:-MqWRnvGDld1klPsfe3N:b-u7f1jy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L346)):*
> ```Go
> 		// been returned by GetResults() yet.
> 		results []Result
> 		err     error
> ```

Why does `err` need mutex protection? (I'm assuming that everything under a `mu struct` is supposed to be mutex protected, please correct me if I'm wrong).
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWSCJB3n204OfQGgiw:-MqWSCJB3n204OfQGgix:b-eqh9qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L362)):*
> ```Go
> // streamerConcurrencyLimit is an upper bound on the number of asynchronous
> // requests that a single Streamer can have in flight. The default value for
> // this setting is chosen arbitrarily as 1/8th of the default value for the
> ```

Out of curiosity [...]

2021-12-10 23:40 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVNtXr5_vVsw7hqdbC:-MqaR2MSCmeDVmkjbGgw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L78)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Can you clarify what happens when there are no more outstanding requests?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVOGC1DagaZ63E_mI1:-MqaR59N-0euyt-mYaf6:b33zy9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L83)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Out of curiosity, does this also block until any requests on remote nodes are cancelled and cleaned up, too?
</blockquote></details>

The streamer running on one node will be issuing requests that might go to any node in the cluster, but the streamer is not aware of whether the KV request is served locally or remotely, so yes, it blocks until all requests, both local and remote, return (in case of a premature cancellation, the requests will see the context cancellation and will short-circuit, so their result will be an error).
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVOkn45MQ1XO5mxdJk:-MqaTuhHCwGK-NgmRo9s:b1o7x64) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L98)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

> ```
> 	// internal out-of-order execution. Out-of-order results might have to be
> 	// dropped (resulting in wasted/duplicate work) when the budget limit is
> 	// reached and the size estimates that lead to too much OoO execution were
> 	// wrong.
> ```

Super nit: It took me a couple reads to parse this, since I thought this was talking about OutOfOrder mode. Consider some rewording to avoid using "Out-of-order" as frequently.
</blockquote></details>

Done, let me know what you think.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVUFFQ2xRLfWxGwW1Y:-MqaVzXZ9IABnFA7wZjz:bkwd00c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L122)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Just to clarify, the streamer handles the continuation, so the user doesn't need to do anything except wait and interpret the results once it gets the continuation?
</blockquote></details>

That's a good question - the comment here was confusing, so I reworded it.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVXCQV8r-nzzyQjLA-:-MqaW_3C25HqzrTUVC-J:b-t22lp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L239)):*
Good point - inlined the function.

> Do you know of any golang static thread safety analysis that CRL uses to make sure the lock is held?

I'm not aware of such things.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-MqaXaZdD_zOsMMW1K04:b1ed4xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
> Doesn't this mean that we can't support all the bytes requested?

Yes, you're totally right here, and your example is correct as well. However, that example should only be possible when mis-using the budget's API. The main idea is that before calling `Consume`, the caller should check how much is `Available`, and if there is not enough, then it doesn't proceed with `Consume`. The only exception is made when the current request is the head of the line in which case the budget goes into debt, yet no new concurrent requests will be issued.

Let's think about our requirements for the budget API:
- we want to stay under the limit (except in degenerate cases of large rows that are put in the response to the head of the line request)
- we want to know when we exceeded the budget already
- if the whole node is already close to OOMing, try to exit.

This should be achieved by the way the streamer cooperates with the budget:
- no new requests are issued if `Available` budget is not sufficient or is negative
- all requests, except for the head of the line, use `TargetBytesAllowEmpty = true` meaning that it is up to the KV to give us a response that doesn't exceed our memory reservation.

I did a TODO for myself to think through this more because `Consume` is currently called in a couple of spots without `Available` check first (although that comes after we made the estimated reservation already). I'll also need to think a bit more about whether we might have some races between concurrent calls to `Available` and `Consume`.

I also decided to unexport `Budget` interface since we do want to tightly couple the `Streamer`'s implementation with the `budget`.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWLgNu3YtET-59cAxC:-MqaflrW0qr4dLTozcrk:b-brssr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L283)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It seems like there's a potential race condition here, where while `WaitForBudget` is in the process of being called, `Release` is called and now memory is available. If there's only one caller to `WaitForBudget` I think it's ok, since `b.waitCh` will have something in it to consume and the function will exit. But if there are multiple callers, is it possible for `WaitForBudget` to wait forever even though there's memory available?
</blockquote></details>

This is called only from a single goroutine. Refactored the code to make it more explicit.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 346 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWRnvGDld1klPsfe3M:-MqafsO77olQC6z8r1Lx:b-b3aq70) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L346)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why does `err` need mutex protection? (I'm assuming that everything under a `mu struct` is supposed to be mutex protected, please correct me if I'm wrong).
</blockquote></details>

Because all concurrent requests as well as the worker coordinator might set this `err`.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWSCJB3n204OfQGgiw:-MqagA4mAada9C2RsjqN:b-l3g7l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L362)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Out of curiosity, why this particular arbitrary value? :-)
</blockquote></details>

No reason, just a power of 2 so that a single streamer would still get some reasonable concurrency, maybe we should go lower still. At the same time I'm not sure whethe [...]

2021-12-11 02:12 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-MqbFEqu345t15if3Iiz:b-74bwgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> Doesn't this mean that we can't support all the bytes requested?

Yes, you're totally right here, and your example is correct as well. However, that example should only be possible when mis-using the budget's API. The main idea is that before calling `Consume`, the caller should check how much is `Available`, and if there is not enough, then it doesn't proceed with `Consume`. The only exception is made when the current request is the head of the line in which case the budget goes into debt, yet no new concurrent requests will be issued.

Let's think about our requirements for the budget API:
- we want to stay under the limit (except in degenerate cases of large rows that are put in the response to the head of the line request)
- we want to know when we exceeded the budget already
- if the whole node is already close to OOMing, try to exit.

This should be achieved by the way the streamer cooperates with the budget:
- no new requests are issued if `Available` budget is not sufficient or is negative
- all requests, except for the head of the line, use `TargetBytesAllowEmpty = true` meaning that it is up to the KV to give us a response that doesn't exceed our memory reservation.

I did a TODO for myself to think through this more because `Consume` is currently called in a couple of spots without `Available` check first (although that comes after we made the estimated reservation already). I'll also need to think a bit more about whether we might have some races between concurrent calls to `Available` and `Consume`.

I also decided to unexport `Budget` interface since we do want to tightly couple the `Streamer`'s implementation with the `budget`.
</blockquote></details>

I think that we'll need to be more careful about holding budget's mutex when calling `available` and `consume` - i.e. we want to couple the streamer and the budget even more. I haven't addressed the corresponding TODO but wanted to push an update about some other refactors I made.


<!-- Sent from Reviewable.io -->

2021-12-13 18:16 UTC, rharding6373 requested changes
Finished reviewing streamer.go, though I want to look at the moving average again. I still need to review the join reader example. One thing that's missing that would be really useful is a series of unit tests for the streamer and friends implementations, so that the invariants and limitations can be tested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MqozCO23EKqMj3cocgD:b-4fftk7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVOkn45MQ1XO5mxdJk:-MqeJg3k9cavxw8Tc7IL:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L98)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Done, let me know what you think.
</blockquote></details>

Thanks!
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVXCQV8r-nzzyQjLA-:-MqeKRU_6CxQZqZWG8Uw:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L239)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point - inlined the function.

> Do you know of any golang static thread safety analysis that CRL uses to make sure the lock is held?

I'm not aware of such things.
</blockquote></details>

Thanks!
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqeLFPpB9Jh4N5l6gii:-MqeLFPpB9Jh4N5l6gij:b-9n9urt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
> ```Go
> // never split across different BatchResponses when TargetBytes limit is
> // exceeded.
> type Streamer interface {
> ```

Something that would be useful here for the future is an example of how to use the API, i.e. a common series of calls to set it up and use it.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 441 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqjjf1M4y-Kq-55WkiE:-Mqjjf1M4y-Kq-55WkiF:bsdeo8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L441)):*
> ```Go
> //
> // The worker coordinator goroutine is started on the first call to Enqueue.
> func (s *streamer) Enqueue(ctx context.Context, reqs []roachpb.RequestUnion, keys []int) error {
> ```

Is there a limit on the size of `reqs` the user should use?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqeUyjs5fzRfOg5g8rF:-MqeUyjs5fzRfOg5g8rG:b99pr8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L463)):*
> ```Go
> 	// acquisitions once pipelining is implemented.
> 	defer s.mu.Unlock()
> 	s.mu.numCompleteRequests = 0
> ```

In the interface description it says that calling Enqueue when there are outstanding requests is prohibited, but it looks like there are no checks here to make sure that is the case. It would be nice to have a check that all results are complete, at least until pipelining is implemented, and a test for it.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqjgnU39BeM44DF2sYg:-MqjgnU39BeM44DF2sYh:bim6400) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L464)):*
> ```Go
> 	defer s.mu.Unlock()
> 	s.mu.numCompleteRequests = 0
> ```

Some other restrictions in the interface description that would be good to check early that don't seem to return errors: 	
* If keys is not nil, it needs to contain one ID for each request
* In OutOfOrder mode it's mandatory to specify keys.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 546 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqjiOQ73YQfHDTB5fSS:-MqjiOQ73YQfHDTB5fST:bbm2phg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L546)):*
> ```Go
> 
> 	// Account for the memory used by all the requests.
> 	if err = s.budget.consume(ctx, totalReqsMemUsage); err != nil {
> ```

Not an ask now, but a potential TODO if it's possible: it seems like this may be a good place to make the memory consumption more fine grained by moving this (and the corresponding `available` call) into the loop, and only enqueuing as many requests as we have memory available. This would require moving the loop somewhere we could resume the work when more memory becomes available. Thoughts?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 562 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqjn1Md0I_A5eKW67_x:-Mqjn1Md0I_A5eKW67_y:b-69t7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L562)):*
> ```Go
> 	err := s.mu.err
> 	s.mu.results = nil
> 	allComplete := s.mu.numCompleteRequests == len(s.enqueueKeys)
> ```

In `InOrder` mode, keys aren't required so `len(s.enqueueKeys)` may be 0, so it seems like `allComplete` would only be true when no requests have completed, and wouldn't actually inform us when all the requests have been processed. Is this the case if no keys are provided?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 625 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqkxPx1-sm9UECR5VxY:-MqkxPx23ffDmDV_oPnG:bpow6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L625)):*
> ```Go
> type singleRangeBatch struct {
> 	reqs []roachpb.RequestUnion
> 	// positions is 1-to-1 mapping with reqs to indicate which ordinal among
> ```

nit:
s/is 1-to-1/is a 1-to-1
s/among/among the
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 646 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqkyEO0D-GfOkQyEmoW:-MqkyEO0D-GfOkQyEmoX:b-jzenqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L646)):*
> ```Go
> }
> 
> func (r *singleRangeBatch) Less(i, j int) bool {
> ```

nit: Add comment to effect of "Less returns true if reqs[i]'s key comes before reqs[j]'s key."
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 727 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mql5ZYQ3tz3Ol3gWFhw:-Mql5ZYQ3tz3Ol3gWFhx:bz1j44r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L727)):*
> ```Go
> 			}
> 			if !targetBytesReservationDenied {
> 				if err = w.s.budget.consume(ctx, targetBytes); err != nil {
> ```

Even if the reservation is denied because we anticipate going over the available memory budget, don't we want to call `consume` so that the budget can track the actual used bytes?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 777 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqlFvf5Do2eVeBY59bS:-MqlFvf5Do2eVeBY59bT:b-xpwn5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L777)):*
> ```Go
> 	// added (we want to preserve an object in hasWork channel if new requests
> 	// are added).
> 	if len(requestsToServe) > 0 {
> ```

I'm curious (since I'm still a bit of a go noob trying to get a handle on channels) why here the channel is only cleared if there were requests, but in streamer `GetResults` the channel is cleared indiscriminately? [...]

2021-12-13 18:34 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 239 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqVXCQV8r-nzzyQjLA-:-Mqp3Suy3-KtJ2PD24NF:b2x3jxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L239)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Yes, there is very much such a thing :) 

A reason we enforce `syncutil.Mutex` is so that we can use [`AssertHeld`](https://github.com/cockroachdb/cockroach/blob/318656406d4408f704dc664c47bedc35f097aa79/pkg/util/syncutil/mutex_sync.go#L34-L35) which we compile to a no-op in production builds but to a check that the mutex is held in race builds. 


<!-- Sent from Reviewable.io -->

2021-12-14 02:34 UTC, yuzefovich reviewed
Thanks for the review! I addressed some of the comments and wanted to push an update for the memory budgeting logic.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Mqqm1J829oZrOM__BoS:b-ebhzdg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-MqqZ9uaCNg7izFQQd8u:bv2dh1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think that we'll need to be more careful about holding budget's mutex when calling `available` and `consume` - i.e. we want to couple the streamer and the budget even more. I haven't addressed the corresponding TODO but wanted to push an update about some other refactors I made.
</blockquote></details>

Alright, I've refactored the code around the usage of the budget.

We currently have three places where we're consuming the budget:
1. in `Enqueue`, after we have converted all requests into `singleRangeBatch`es. Here, we will error if the budget's limit is exceeded even by the requests on their own.
2. in `mainLoop` where we're issuing requests to be evaluated in parallel. Here we need to have tight control of the budget, so we'll acquire the budget's lock and will make sure to not let the budget go into debt, except in the degenerate case of a single large request. All requests get a memory reservation that we estimate that their response will need, and in the degenerate case we will use `TargetBytes: 1` so that the KV gives us only a single row which will be unaccounted for completely until the response arrives.
3. in `performRequestAsync` where we're updating the budget to account for the response's memory usage exactly. We need to account for two parts - the response itself and for the resume spans. As it is written currently, if we don't have the budget to account for not head-of-the-line responses or resume spans, we'll drop them, but for head-of-the-line we're allowing the budget to go into debt.

Curious to hear your thoughts on this proposal.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 441 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqjjf1M4y-Kq-55WkiE:-MqqlpQX7Wg4jnaWfoJi:b-npjcwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L441)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is there a limit on the size of `reqs` the user should use?
</blockquote></details>

Good point, added.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 546 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqjiOQ73YQfHDTB5fSS:-MqqjA6I5vQaGQth5Sda:b188p00) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L546)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Not an ask now, but a potential TODO if it's possible: it seems like this may be a good place to make the memory consumption more fine grained by moving this (and the corresponding `available` call) into the loop, and only enqueuing as many requests as we have memory available. This would require moving the loop somewhere we could resume the work when more memory becomes available. Thoughts?
</blockquote></details>

Hm, the thing is that vast majority in `totalReqsMemUsage` will come from `roachpb.Span` objects that are inside the enqueued `reqs`, so the corresponding memory allocations have already been incurred by the `Streamer`'s caller. I think here we want to be defensive and require that this footprint stays within the limit as well as within `--max-sql-memory` pool. I've refactored the code to behave this way, and I've just added more words that it's the caller's responsibility to `Enqueue` reasonably-sized "chunks" of requests (this is already done by the index joiners, yet it's good to spell it out).
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 727 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mql5ZYQ3tz3Ol3gWFhw:-Mqqjsy9C6EwqopiW-Qw:b-b0a97e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L727)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Even if the reservation is denied because we anticipate going over the available memory budget, don't we want to call `consume` so that the budget can track the actual used bytes?
</blockquote></details>

The code here has been refactored, and please see my other larger comment for context.

Here, if `targetBytesReservationDenied` is `true`, then we have a case of a very large single response. We'll use `TargetBytes` of `1` and will rely on the KV to return exactly one row that will be accounted for in `performAsyncRequest`. There isn't much benefit in consuming from the budget here given that we know that the average response size is very large, and we won't issue any more async requests until this one comes back. Thoughts?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 777 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqlFvf5Do2eVeBY59bS:-Mqql-Lr0JwvZmJ9XBc2:bywolfo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L777)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I'm curious (since I'm still a bit of a go noob trying to get a handle on channels) why here the channel is only cleared if there were requests, but in streamer `GetResults` the channel is cleared indiscriminately?
</blockquote></details>

That's a good catch - I don't think we need the `if` here (seems like a remnant of the refactor). Fixed.


<!-- Sent from Reviewable.io -->

2021-12-14 12:39 UTC, erikgrinaker reviewed
> Reviewed 15 of 20 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqsqtleCvJ_lFDeXtNS:-Mqsqtlf4sYSoeQwyLNu:b-9j6uvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L73)):*
> ```Go
> 	// reqs (i.e. roachpb.Spans inside of the requests) is reasonable. Enqueue
> 	// will return an error if that footprint exceeds the Streamer's limit. As a
> 	// rule of thumb, that footprint should be on the order of MBs, and not tens
> ```

How can callers ensure this when users are free to write fields of arbitrary size?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 901 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqsvPY21DC5G6_II5ap:-MqsvPY21DC5G6_II5aq:brhhm53) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L901)):*
> ```Go
> 			ba.Header.WaitPolicy = w.lockWaitPolicy
> 			ba.Header.TargetBytes = targetBytes
> 			ba.Header.TargetBytesAllowEmpty = !headOfLine
> ```

This parameter is only available on 22.1. With 21.2 nodes, this is ignored, and additionally all requests will always overshoot limits. We may want to disable use of the streamer unless the `TargetBytesAvoidExcess` version gate is enabled, which ensures this setting is effective and limits are not overshot.


<!-- Sent from Reviewable.io -->

2021-12-14 19:38 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqeLFPpB9Jh4N5l6gii:-Mqtc3qD5SJgkHoJDtzz:b-xiragv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Something that would be useful here for the future is an example of how to use the API, i.e. a common series of calls to set it up and use it.
</blockquote></details>

+1. The Streamer definitely needs a big comment
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtbsBmEbZHqmCDwzlv:-MqtbsBmEbZHqmCDwzlw:b-m3lz68) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L21)):*
> ```Go
> 	"unsafe"
> 
> 	pkgKeys "github.com/cockroachdb/cockroach/pkg/keys"
> ```

why did you need to name the import?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtdWsK1b4xQlFIBRIu:-MqtdWsK1b4xQlFIBRIv:b-tkjyjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
> ```Go
> // never split across different BatchResponses when TargetBytes limit is
> // exceeded.
> type Streamer interface {
> ```

Is it actually useful to make this an interface? How many implementations do you have?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 58 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquOdXMEUR5CiL4lXY6:-MquOdXMEUR5CiL4lXY7:b-byrrr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L58)):*
> ```
> 	// In OutOfOrder mode it's mandatory to
> 	// specify keys.
> ```

Why? It seems to me that, just how you're describing below how specifying the same key for multiple requests can be fine, not specifying keys could also be enough for some clients.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 82 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquOHke928_JUqpE5uc:-MquOHke928_JUqpE5ud:b-mqoffl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L82)):*
> ```Go
> 
> 	// GetResults blocks until at least one result is available. If the
> 	// operation mode is OutOfOrder, any result will do. For InOrder, only
> ```

hint at the result keys for `OutOfOrder`
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquO93O3MwqVbMnPQyC:-MquO93O3MwqVbMnPQyD:bqur6wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L88)):*
> ```Go
> 
> 	// Cancel cancels all in-flight operations and discards all buffered results
> 	// if operating in InOrder mode. It blocks until all goroutines created by
> ```

results can also be buffered in OutOfOrder mode, no? Why does this comment call out `InOrder`?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 128 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqte1wX7Qs6ag4v4bba:-Mqte1wX7Qs6ag4v4bbb:b95yjx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L128)):*
> ```Go
> 	// to the respective memory.
> 	GetResp *roachpb.GetResponse
> 	// ScanResp can contain a partial response to a ScanRequest. In that case,
> ```

reference to `ScanComplete`
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 143 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtePob6co0t3an0vK4:-MqtePob6co0t3an0vK5:b-shm8z9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L143)):*
> ```Go
> 	// scan can be delivered out of key order (in addition to results for
> 	// different scans being delivered out of request order).
> 	ScanComplete bool
> ```

did you consider grouping `ScanResp` and `ScanComplete` in an anon struct?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteX2e-gabCIJxV6nO:-MqteX2e-gabCIJxV6nP:b3fk47z) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L147)):*
> ```Go
> 	// mode, a single Result can satisfy multiple identical requests. In InOrder
> 	// mode a Result can only satisfy multiple consecutive requests.
> 	Keys []int
> ```

maybe `RequestKeys` ?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 158 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteqE73NOI5OgKQBC4:-MqteqE73NOI5OgKQBC5:bfg10k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L158)):*
> ```Go
> 	// also contributes to the refcounts.
> 	MemoryTok ResultMemoryToken
> 	// position tracks the ordinal among all originally enqueued requests that
> ```

what if it satisfies multiple, as per `Keys` ?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 167 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquPBPGDUbBdJptyfVn:-MquPBPGDUbBdJptyfVo:b3kq2j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L167)):*
> ```Go
> // use any more so that its memory is returned to the Streamer's Budget.
> //
> // ResultMemoryToken is thread-safe.
> ```

This seems like a very confusing comment to put on this interface, since presumably the recipient is not supposed to call `Release()` more than once on a token?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 191 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquPgLA1rLIOKLNEaZW:-MquPgLA1rLIOKLNEaZX:b-yzff6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L191)):*
> ```Go
> 		// used is the amount of currently used up bytes of this budget. This
> 		// number can exceed limit in degenerate cases (e.g. when a single row
> 		// exceeds the limit), but usually it should not exceed acc.Used().
> ```

I find this comment a bit confusing; consider clarifying it. You say something about a degenerate case, and the relationship with `limit`, and then say *but* and talk about the relationship with `acc.Used()` in the "usual" case. There's also the relationship between `acc.Used()` and `limit` that you talk about in `acc` above... I think more words tying the 3 things together would help.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 196 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquPRkE8Xxa_1tsR-lD:-MquPRkE8Xxa_1tsR-lE:b-shp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L196)):*
> ```Go
> 	// limit is the maximum amount of bytes that this budget can reserve against
> 	// the account.
> 	limit int64
> ```

`limitBytes`. Let's put units in variables/fields.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 207 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MquQThG4BkaDqTOPg4E:-MquQThG4BkaDqTOPg4F:b-jnpj2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L207)):*
> acc should be bound to an unlimited memory monitor

why?

Also generally it's not clear to me from this comment what `acc` repr [...]

2021-12-14 19:49 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtdWsK1b4xQlFIBRIu:-MquUJinCFhtMpKTiPVG:b-z7nex4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is it actually useful to make this an interface? How many implementations do you have?
</blockquote></details>

+1 on making it concrete. Thoughts on pulling the whole thing out into a separate package? What unexported symbols does the streamer implementation rely on? 


<!-- Sent from Reviewable.io -->

2021-12-15 17:01 UTC, rytaft reviewed
This is looking great so far! I've only reviewed a small piece, but will push my current comments and come back to it later today

> Reviewed 1 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Mqz1Nt03ZXNFqiVAHRx:bo5seuq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-MqywX6K0kvcLCjgJJe4:bkxblbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Alright, I've refactored the code around the usage of the budget.

We currently have three places where we're consuming the budget:
1. in `Enqueue`, after we have converted all requests into `singleRangeBatch`es. Here, we will error if the budget's limit is exceeded even by the requests on their own.
2. in `mainLoop` where we're issuing requests to be evaluated in parallel. Here we need to have tight control of the budget, so we'll acquire the budget's lock and will make sure to not let the budget go into debt, except in the degenerate case of a single large request. All requests get a memory reservation that we estimate that their response will need, and in the degenerate case we will use `TargetBytes: 1` so that the KV gives us only a single row which will be unaccounted for completely until the response arrives.
3. in `performRequestAsync` where we're updating the budget to account for the response's memory usage exactly. We need to account for two parts - the response itself and for the resume spans. As it is written currently, if we don't have the budget to account for not head-of-the-line responses or resume spans, we'll drop them, but for head-of-the-line we're allowing the budget to go into debt.

Curious to hear your thoughts on this proposal.
</blockquote></details>

Since `b.mu.acc` isn't actually limited by `b.limit`, feels like we should call `ResizeTo` with the actual number of bytes used, which is `b.mu.used + bytes`. I would think we'd want to error if we're actually close to hitting the memory limit (isn't that the purpose of `b.mu.acc`?)
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 126 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqyjLLu6PRLMeolevBF:-MqyjLLu6PRLMeolevBG:bl4nkm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L126)):*
> ```Go
> 	//
> 	// The responses are to be considered immutable; the Streamer might hold on
> 	// to the respective memory.
> ```

How does the streamer know when it can reuse the memory?

Edit: I see that question is answered below. Maybe add a pointer here to MemoryTok
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 305 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqyy8hv-hbUr_oDitd1:-Mqyy8hv-hbUr_oDitd2:b-5p10et) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L305)):*
> ```Go
> 	if b.limit > b.mu.used {
> 		select {
> 		case b.waitCh <- struct{}{}:
> ```

this could use a comment
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 370 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqyzLDr5ZQNcZ0iW3zA:-MqyzLDr5ZQNcZ0iW3zB:bskbhdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L370)):*
> ```Go
> 	}
> 
> 	atomics struct {
> ```

why is this separate from `mu`?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 386 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqyzk5A1XxM72i3-xZQ:-Mqyzk5A1XxM72i3-xZR:bcbb18l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L386)):*
> ```Go
> // senderConcurrencyLimit.
> // TODO(RFC): would it be preferable to have a global semaphore, similar to the
> // DistSender?
> ```

Seems somewhat preferable -- what do you think are the cons?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 402 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqz-G8Q0nR6KJOgtlyP:-Mqz-G8Q0nR6KJOgtlyQ:b-rpoxvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L402)):*
> ```Go
> // throughput.
> //
> // acc should be bound to an unlimited memory monitor, and the Streamer itself
> ```

But the memory monitor is still ensuring we don't OOM, right? So it must not be truly unlimited...
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 438 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqz06Al4AQcSht8SvJE:-Mqz06Al4AQcSht8SvJF:bilkk1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L438)):*
> ```Go
> 	s.coordinator.asyncSem = quotapool.NewIntPool(
> 		"single Streamer async concurrency",
> 		uint64(senderConcurrencyLimit.Get(&st.SV)),
> ```

should this be `streamerConcurrencyLimit`?


<!-- Sent from Reviewable.io -->

2021-12-16 02:56 UTC, rytaft reviewed
> Reviewed 15 of 20 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rharding6373, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 534 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqzcspq7zkNFfemnH_p:-Mqzcspr8Ay9hiQH21kQ:b-cyuvue) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L534)):*
> ```Go
> 					} else {
> 						s.mu.numRangesLeftPerScanRequest = s.mu.numRangesLeftPerScanRequest[:len(reqs)]
> 						for n := 0; n < len(s.mu.numRangesLeftPerScanRequest); n += copy(s.mu.numRangesLeftPerScanRequest[n:], zeroIntSlice) {
> ```

Can we put the last part of this for loop in the body of the loop (maybe split over a few lines with helpful variable names)? I think it will be clearer what's going on
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 587 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqzeCDeEbPyW15IxjAI:-MqzeCDeEbPyW15IxjAJ:b-zi4olt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L587)):*
> ```Go
> 	// TODO(yuzefovich): it might be better to notify the coordinator once
> 	// one singleRangeBatch object has been appended to s.mu.requestsToServe.
> 	s.coordinator.hasWork <- struct{}{}
> ```

Will this block? (should it?)
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 751 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqzkHcOAlBReklLfCGi:-MqzkHcP573F4D1Olw3A:b-kndboi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L751)):*
> ```Go
> 			// We can just slice here since we only append to requestToServe at
> 			// the moment.
> 			w.s.mu.requestsToServe = w.s.mu.requestsToServe[numRequestsIssued:]
> ```

nit: seems a bit strange that this is the only place in this function where you're updating `w.s.mu.requestsToServe`. Would this be better done inside `w.issueRequestsForAsyncProcessing`?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 781 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqzkwUE2WMEsPoaBmAI:-MqzkwUFDyFW8yshwacY:b-wdi8kx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L781)):*
> ```Go
> 
> // issueRequestsForAsyncProcessing iterates over the given requests and issues
> // them to be served asynchronously until provided there is enough budget
> ```

nit: until provided -> until?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 879 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr04Yke98zp8LDSzJ2L:-Mr04Yke98zp8LDSzJ2M:b-ch1fjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L879)):*
> ```Go
> // - targetBytesReservationDenied indicates whether the reservation of
> // targetBytes from the budget has been denied. This can be true iff headOfLine
> // is true.
> ```

should this be asserted somewhere?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 910 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr05Tpa5mMjJoqpxPIl:-Mr05Tpa5mMjJoqpxPIm:b-38uekq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L910)):*
> ```Go
> 			// have already reserved at least 10KiB when creating the Budget. If
> 			// targetBytesReservationDenied is true, then this request is the
> 			// only one that will be in flight.
> ```

nit: This comment is kind of confusing and assumes that the reader is familiar with a different part of the code that doesn't seem relevant here
___
*[pkg/sql/distsql_running.go, line 449 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqzlqAO1xgWjPitKPx0:-MqzlqAO1xgWjPitKPx1:b7be3ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/distsql_running.go#L449)):*
> ```Go
> 		for _, proc := range plan.Processors {
> 			if js := proc.Spec.Core.JoinReader; js != nil {
> 				if !js.MaintainOrdering && len(js.LookupColumns) == 0 && js.OnExpr.Empty() {
> ```

nit: should we have an `isIndexJoin` helper function somewhere?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 757 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqzm3P21RQ6rwRPLxdP:-Mqzm3P21RQ6rwRPLxdQ:b12mqw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/colexec/colbuilder/execplan.go#L757)):*
> ```Go
> 			)
> 			var streamerBudgetAcc *mon.BoundAccount
> 			if !core.JoinReader.MaintainOrdering {
> ```

add a comment / TODO to explain why you're adding this check
___
*[pkg/sql/row/kv_batch_streamer.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr01TQnBt7eYGzP0EZL:-Mr01TQnBt7eYGzP0EZM:b-9hniqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/row/kv_batch_streamer.go#L174)):*
> ```Go
> 		f.lastResultState.remainingBatches = nil
> 		f.results[0] = kvcoord.Result{}
> 		f.results = f.results[1:]
> ```

these last two lines could use a comment
___
*[pkg/sql/row/kv_batch_streamer.go, line 187 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr01qwe6oIHncII4Hm6:-Mr01qwe6oIHncII4Hm7:b-58bhfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/row/kv_batch_streamer.go#L187)):*
> ```Go
> 
> 	// Get more results from the streamer. The returned results are accounted
> 	// against the streamer's budget, so we don't have to worry about that.
> ```

I think this comment could use a few more words. I'm a bit confused.


<!-- Sent from Reviewable.io -->

2021-12-16 03:14 UTC, rytaft reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @rharding6373, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr0Cpxv9FlKyDikTqL6:-Mr0Cpxv9FlKyDikTqL7:b-xbywcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L789)):*
> ```Go
> // The number of requests issued is returned as well as a boolean that indicates
> // whether the coordinator should exit.
> func (w *workerCoordinator) issueRequestsForAsyncProcessing(
> ```

This function could definitely use some unit tests to try out all the different variations of large /small batches, at head of line / middle of the batch, high / low budget, etc. Since you have the streamer currently designed as an interface (although I see some alternative suggestions above...), you could take advantage of that to mock the streamer for testing purposes.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 1161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr0C2biAzRIxQZWUq0U:-Mr0C2bm1erWorviWUVe:b-m2bi3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L1161)):*
> ```Go
> 	}
> 	w.s.mu.avgResponseSize -= int64(float64(w.s.mu.avgResponseSize) * ratio)
> 	w.s.mu.avgResponseSize += int64(float64(actualMemoryReservation) / float64(len(results)) * ratio)
> ```

checking your calculation of the avgResponseSize seems like something that could be a good opportunity for a unit test


<!-- Sent from Reviewable.io -->

2021-12-30 21:47 UTC, yuzefovich reviewed
Thanks everyone for the feedback! I think I addressed all of the comments.

Quick summary of changes:
- `Streamer` is made concrete and is extracted into a separate package
- the budget logic has been cleaned up
- the estimation of the average response size now uses the simple average
- some unit tests are added
- one commit is added to introduce a helper as suggested by Becca
- another commit is added to make the `joinReader` not exceed the limit on the input batch size which is used to construct spans to lookup. I'm not sure whether we want to keep this commit, or to allow the budget to go into debt based on the memory footprint of the enqueued requests alone. Curious to hear thoughts here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MsCGsUT1BLXr82M_oMR:b11xzav)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/sql/distsql_running.go, line 449 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqzlqAO1xgWjPitKPx0:-Ms7_CZ70rj8gQmUiN9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/distsql_running.go#L449)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: should we have an `isIndexJoin` helper function somewhere?
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 757 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqzm3P21RQ6rwRPLxdP:-Mr5LsRj-hj8Co0F2ShL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/colexec/colbuilder/execplan.go#L757)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

add a comment / TODO to explain why you're adding this check
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_streamer.go, line 174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr01TQnBt7eYGzP0EZL:-Ms6k9LH3QsFfHE0NbBl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/row/kv_batch_streamer.go#L174)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

these last two lines could use a comment
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_streamer.go, line 187 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr01qwe6oIHncII4Hm6:-Ms6ksES28FQMe9JlgO8:bfafclw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/sql/row/kv_batch_streamer.go#L187)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I think this comment could use a few more words. I'm a bit confused.
</blockquote></details>

Expanded, please let me know if it still doesn't make sense.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqWBjLB1bCjRc3x0OWI:-Ms6Y6Az2qWAQZrQYOM3:b-86a6q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1f8a7669cde4ad226ac9875bb1397cd42e004a1/pkg/kv/kvclient/kvcoord/streamer.go#L252)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Since `b.mu.acc` isn't actually limited by `b.limit`, feels like we should call `ResizeTo` with the actual number of bytes used, which is `b.mu.used + bytes`. I would think we'd want to error if we're actually close to hitting the memory limit (isn't that the purpose of `b.mu.acc`?)
</blockquote></details>

Very good point, thanks - I refactored the code to remove `used` field entirely (I think I introduced it when I originally used `acc` that is bound to a limited memory monitor, so we had to track `used` field separately, but now that we're using `acc` bound to an unlimited memory monitor, we can get rid off `used`). I think now the code is more clear.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqeLFPpB9Jh4N5l6gii:-MsCEg4F8PoUqjRncneU:bn5ovlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

+1. The Streamer definitely needs a big comment
</blockquote></details>

Done. Please let me know if I missed some important points in that comment.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqeUyjs5fzRfOg5g8rF:-Ms6itNL9ddU-4vSo-z1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L463)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

In the interface description it says that calling Enqueue when there are outstanding requests is prohibited, but it looks like there are no checks here to make sure that is the case. It would be nice to have a check that all results are complete, at least until pipelining is implemented, and a test for it.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 464 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqjgnU39BeM44DF2sYg:-Ms6jVJPBVAc9F_z_Zm_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L464)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Some other restrictions in the interface description that would be good to check early that don't seem to return errors: 	
* If keys is not nil, it needs to contain one ID for each request
* In OutOfOrder mode it's mandatory to specify keys.

</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 562 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mqjn1Md0I_A5eKW67_x:-Ms6jZ11EpdxXkRvjnNA:bva51sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6e2ee3ac0503b22cfecd6f00792b0a4ea446aed/pkg/kv/kvclient/kvcoord/streamer.go#L562)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

In `InOrder` mode, keys aren't required so `len(s.enqueueKeys)` may be 0, so it seems like `allComplete` would only be true when no requests have completed, and wouldn't actually inform us when all the requests have been processed. Is this the case if no keys are provided?
</blockquote></details>

Good point, added a separate variable to track the number of enqueued requests.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 21 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtbsBmEbZHqmCDwzlv:-Mr58L2-7EC4rDl8lyf3:bgj43ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L21)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why did you need to name the import?
</blockquote></details>

There was a collision with an argument to `Enqueue` named `keys`, refactored.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 43 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqtdWsK1b4xQlFIBRIu:-Mr5CVxe4V9zDUy8ho4H:bbap93q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L43)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

+1 on making it concrete. Thoughts on pulling the whole thing out into a separate package? What unexported symbols does the streamer implementation rely on? 
</blockquote></details>

Good points, made it concrete and pulled it out into a separate package.
___
*[pkg/kv/kvclient/kvcoord/strea [...]

2022-01-05 22:37 UTC, rharding6373 requested changes
This is looking pretty good! I did a pass over the first two commits, budget, Streamer, and some miscellaneous files and tests. I plan to take a closer look at the remaining files and `performRequestAsync` tomorrow.

> Reviewed 13 of 30 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MsgM2c09ogGerMwlLvO:b-jggj2m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 1 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsbDUkr7wbUq_cqLBaA:-MsbDUkr7wbUq_cqLBaB:binbxfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L1)):*
> ```Go
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2022, here and in other new files
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 37 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msfk1LF8lqC2DmOV4hC:-Msfk1LF8lqC2DmOV4hD:b3nik3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L37)):*
> ```Go
> 	// against acc, i.e. acc.Used() should not exceed limitBytes. However, in a
> 	// degenerate case of a single large row, the budget can go into debt and
> 	// acc.Used() might exceed limitBytes.
> ```

optional nit: might be worth mentioning here that the user can use a parameter to indicate that the budget should not go into debt. I'm not sure that this is an appropriate place,   though, thus adding to this comment is optional.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 84 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgMrGO8wSi48IV1s9X:-MsgMrGO8wSi48IV1s9Y:b-lzua08) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L84)):*
> ```Go
> // - allowDebt indicates whether the budget is allowed to go into debt. In other
> // words, if allowDebt is true, then acc's reservation is allowed to exceed
> // limitBytes.
> ```

Coming back to this after reading the Streamer code, I now understand why `allowDebt` is here and how it's used to manage the budget. Since I didn't understand correctly on the first pass (I interpreted it as allow any debt at all, not just for this request), this makes me think that either this comment could be a bit more clear about this parameter, or budget could use a usage comment to identify the correct usage pattern, or both.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 94 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsbHdSS7fyJEgNWD2WI:-MsbHdSS7fyJEgNWD2WJ:b40q6p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L94)):*
> ```Go
> 
> // consumeLocked is the same as consume but assumes that the b's lock is held.
> func (b *budget) consumeLocked(ctx context.Context, bytes int64, allowDebt bool) error {
> ```

Please follow ajwerner's suggestion and call `AssertHeld` at the beginning of this function.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 96 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsbIEXA03q-wKhpsDTV:-MsbIEXA03q-wKhpsDTW:b-no2ez2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L96)):*
> ```Go
> func (b *budget) consumeLocked(ctx context.Context, bytes int64, allowDebt bool) error {
> 	// If we're asked to not exceed the limit (and the limit is greater than
> 	// five bytes - limits of five bytes or less are treated as a special case
> ```

What is a real scenario when disk spilling would occur with the streamer? Since the budget can be exceeded for large rows, it seems like it may never try to spill to disk?
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 100 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfkqaZDOAopPlCnj0o:-MsfkqaZDOAopPlCnj0p:b-x6d32q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L100)):*
> ```Go
> 	// stay within the budget.
> 	if !allowDebt && b.limitBytes > 5 {
> 		if b.mu.acc.Used()+bytes > b.limitBytes {
> ```

Is it the caller's responsibility to ensure that the only time we go into debt is if `acc.Used()` is 0? Otherwise it seems that `consume` allows us to go into unnecessary debt. I would add a comment about what is the user's responsibility here, or add a check to this function that rejects a `consume` request if it goes over the limit and `acc.Used()` is non-zero.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 155 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfpVsD58W5pW7bq_qC:-MsfpVsD58W5pW7bq_qD:b-ym48dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L155)):*
> ```Go
> //    results, err := s.GetResults(ctx)
> //    // err check
> //    if len(results) > 0 {
> ```

What does it mean if `len(results)` is 0?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 184 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfqKbm8LMaGSfUjAQP:-MsfqKbm8LMaGSfUjAQQ:b-ges4ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L184)):*
> ```Go
> // concurrency of the Streamer is limited by its memory limit.
> //
> // The streamer additionally utilizes different optimizations to improve the
> ```

minor nit: s/streamer/Streamer
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msg7puPArzdldgTTegj:-Msg7puPArzdldgTTegk:bo2lbnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L551)):*
> ```Go
> // that other results couldn't be appended which would cause us to miss the
> // notification about that.
> func (s *Streamer) notifyGetResultsLocked() {
> ```

Call `AssertHeld` here.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 569 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msg8Cw95aXvF05mWSl9:-Msg8Cw95aXvF05mWSlA:b-jr6cgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L569)):*
> ```Go
> }
> 
> // Cancel cancels all in-flight operations and discards all buffered results if
> ```

Should it also discard/free the requests from `Enqueue`, since the Streamer owns them?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 662 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgBoX9Ax3vnLYCvbTE:-MsgBoX9Ax3vnLYCvbTF:bguwfp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L662)):*
> ```Go
> 		}
> 		if err != nil {
> 			return
> ```

Should we log the error before returning?

Also, even though it's more verbose, I thought the standard go convention was to check the err right after assigning it and return right away if not nil. Optional to add the err check below each w.getRequests().
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 957 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgKb9U7OvIyFI8FAMU:-MsgKb9U7OvIyFI8FAMV:bkx54lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L957)):*
> ```Go
> 					if !headOfLine {
> 						// Since this is not the head of the line, we'll just
> 						// discard the result and add the request back to be
> ```

Should the request go to the front for better seek behavior?
___
*[pkg/kv/kvc [...]

2022-01-05 23:56 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 37 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msfk1LF8lqC2DmOV4hC:-MsgYJO_35sQKai26ZN_:bcxmpl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L37)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

optional nit: might be worth mentioning here that the user can use a parameter to indicate that the budget should not go into debt. I'm not sure that this is an appropriate place,   though, thus adding to this comment is optional.
</blockquote></details>

I think I won't add anything here since the comment on `consume` should be sufficient.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 84 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgMrGO8wSi48IV1s9X:-MsgYZ4OAg2ixLmdNIvj:b8vx17b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L84)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Coming back to this after reading the Streamer code, I now understand why `allowDebt` is here and how it's used to manage the budget. Since I didn't understand correctly on the first pass (I interpreted it as allow any debt at all, not just for this request), this makes me think that either this comment could be a bit more clear about this parameter, or budget could use a usage comment to identify the correct usage pattern, or both.
</blockquote></details>

I expanded the comment, but the example usage seems like an overkill to me since `budget` only has a constructor with `consume`/`release` calls for usage.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 94 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsbHdSS7fyJEgNWD2WI:-MsgYwlP33x5S09TSMEr:bjb27qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L94)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Please follow ajwerner's suggestion and call `AssertHeld` at the beginning of this function.
</blockquote></details>

Done. I misunderstood what Andrew wrote - I thought that `AssertHeld` is somehow automatically applied when running with `race`.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 96 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsbIEXA03q-wKhpsDTV:-MsgZJGZ-gL8KZYpXM1-:bjnnxo2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L96)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

What is a real scenario when disk spilling would occur with the streamer? Since the budget can be exceeded for large rows, it seems like it may never try to spill to disk?
</blockquote></details>

Here the disk spilling is not applicable to the streamer itself, rather it is a cluster wide thing (for example `fakedist-disk` logic test config). In that case the computation of `distsql_workmem` limit is overridden to be 1, and we use the value of 1 to force all components that can spill to disk to actually spill. Here, for the streamer we use `distsql_workmem` limit value to compute `limitBytes`, but the computations are somewhat different in the row-by-row and vectorized engines, so we allow for a range of small values to be indicative of "forced disk spilling" setup. No one should set actual cluster setting to such a small value in production :) (but if they did, then here the streamer's budget would only be limited by the `--max-sql-memory`).
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 100 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfkqaZDOAopPlCnj0o:-Msg_jriCxgzfcgYiFVl:b-bf9ozf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/budget.go#L100)):*
> Is it the caller's responsibility to ensure that the only time we go into debt is if `acc.Used()` is 0?

Going into debt is allowed whenever `allowDebt` is `true`, regardless of `acc.Used()` value.

Consider the degenerate case of a very large row which includes a very large key to lookup. We first `consume` the bytes needed for the request containing a very large key, at this point the budget can go into debt; then, when the response is received, we will put the budget even into more debt. Such behavior is allowed.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 155 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfpVsD58W5pW7bq_qC:-Msgaa2HBG4o0JR5McBJ:b-l1vzds) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L155)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

What does it mean if `len(results)` is 0?
</blockquote></details>

From the comment on `GetResults`:
```
// Zero-length result slice is returned once all enqueued requests have been responded to.
```
Do you think returning `nil` would be more clear?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 551 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msg7puPArzdldgTTegj:-MsgbGEZ7uBbiU68sdO8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L551)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Call `AssertHeld` here.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 569 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Msg8Cw95aXvF05mWSl9:-MsgbtSz-Mk_Pr9Ir2kq:b9x6pt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L569)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should it also discard/free the requests from `Enqueue`, since the Streamer owns them?
</blockquote></details>

Good point, made the method release all of the resources and renamed it to `Close`.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 662 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgBoX9Ax3vnLYCvbTE:-Msgcihd7gulrWUSHypw:b8fgj55) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L662)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we log the error before returning?

Also, even though it's more verbose, I thought the standard go convention was to check the err right after assigning it and return right away if not nil. Optional to add the err check below each w.getRequests().
</blockquote></details>

The error will still be returned by `GetResults` to the caller, so there is no need to log it. I refactored the code to return `ok == false` in case of an error instead to make this more clear.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 957 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsgKb9U7OvIyFI8FAMU:-MsgczDk9qrJRtgrSe-W:bfd7urg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L957)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should the request go to the front for better seek behavior?
</blockquote></details>

It won't [...]

2022-01-06 18:53 UTC, rharding6373 requested changes
Reviewed the remaining files, and it looks close to me. I'm getting a bit lost though connecting the dots between the Streamer usage example to the join reader example.

> Reviewed 7 of 30 files at r8, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MskiXmGDjaynk-4DUCC:b-ecsnwe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher.go, line 599 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskPth6Bg7vURw4sFdw:-MskPth7CVRcKuEbVvzq:b-50w1jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/colfetcher/cfetcher.go#L599)):*
> ```Go
> 		// keep the remaining quarter for the output batch.
> 		//
> 		// We use +3 here in order to round up.
> ```

Why not use `math.Ceil`?
___
*[pkg/sql/colfetcher/cfetcher.go, line 715 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskT5XbE3ngNoynKZ5o:-MskT5XbE3ngNoynKZ5p:bonnrkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/colfetcher/cfetcher.go#L715)):*
> ```Go
> 	)
> 	rf.streamerInfo.Streamer.Init(
> 		kvstreamer.OutOfOrder,
> ```

Are there plans in the future to lift this to a `StartScanStreaming` parameter when InOrder mode is supported?
___
*[pkg/sql/row/kv_batch_streamer.go, line 44 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mskc55LBuVxj8c2bqpT:-Mskc55LBuVxj8c2bqpU:b-8ynez2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L44)):*
> ```Go
> 
> // TxnKVStreamer handles retrieval of key/values.
> type TxnKVStreamer struct {
> ```

nit: consider renaming the file to reflect the name of the struct implemented here.
___
*[pkg/sql/row/kv_batch_streamer.go, line 77 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskgKhL-THzbafA5sun:-MskgKhM-JaH3N0icP-9:b-utq5cm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L77)):*
> ```Go
> 	keyLocking := getKeyLockingStrength(lockStrength)
> 	reqs := spansToRequests(spans, false /* reverse */, keyLocking)
> 	if err := streamer.Enqueue(ctx, reqs, nil /* enqueueKeys */); err != nil {
> ```

If I understand this right, we create a new TxnKVStreamer every time an operator needs to fetch another batch of spans? So e.g. for the vectorized exec engine we need to start a streaming scan for every batch of spans? This example doesn't seem to follow the usage outlined in the Streamer comment (which suggests to keep enqueueing requests), and I think I'm getting lost trying to reconcile/follow the pattern through these layers between join reader and the Streamer.
___
*[pkg/sql/rowexec/joinreader.go, line 315 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskZM2a5SZIXNRaVtKw:-MskZM2a5SZIXNRaVtKx:bz3gdfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/rowexec/joinreader.go#L315)):*
> ```Go
> 		keyLocking:                        spec.LockingStrength,
> 		lockWaitPolicy:                    row.GetWaitPolicy(spec.LockingWaitPolicy),
> 		usesStreamer:                      readerType == indexJoinReaderType && tryStreamer,
> ```

minor nit: `(readerType == indexJoinReaderType) && tryStreamer`
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 130 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskafTD1esM8z1ulTkp:-MskafTD1esM8z1ulTkq:b15dobb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/kv/kvclient/kvstreamer/streamer_test.go#L130)):*
> ```Go
> 	// - 5000000 is interesting because a single row already exceeds the buffer
> 	// size.
> 	blobSize := []int{3000000, 5000000}[rng.Intn(2)]
> ```

Why not run both blob sizes every test?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 155 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MsfpVsD58W5pW7bq_qC:-MskMGQdDKSF6YZPx5F5:bbiyrq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ee7e746eae63920c901787d15450e3e270e346f/pkg/kv/kvclient/kvstreamer/streamer.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

From the comment on `GetResults`:
```
// Zero-length result slice is returned once all enqueued requests have been responded to.
```
Do you think returning `nil` would be more clear?
</blockquote></details>

Ok, I think that return value is fine.


<!-- Sent from Reviewable.io -->

2022-01-06 22:14 UTC, yuzefovich reviewed
Thanks for the review! You were actually right to get lost there because there were inconsistencies in two users of the Streamer API, now fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MslS7iD4YT17s-G7Rtt:b-darszf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/sql/colfetcher/cfetcher.go, line 599 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskPth6Bg7vURw4sFdw:-Msl5Plz8s9Tt23vHRA2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/colfetcher/cfetcher.go#L599)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why not use `math.Ceil`?
</blockquote></details>

Done.
___
*[pkg/sql/colfetcher/cfetcher.go, line 715 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskT5XbE3ngNoynKZ5o:-Msl5XDZ-OHR7CePFIMS:bygpb8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/colfetcher/cfetcher.go#L715)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Are there plans in the future to lift this to a `StartScanStreaming` parameter when InOrder mode is supported?
</blockquote></details>

The code has just been moved, but in the future it'll be the caller's responsibility (`ColIndexJoin` or `joinReader`) to choose the appropriate mode when initializing the streamer. `cFetcher` should be agnostic of those details.
___
*[pkg/sql/row/kv_batch_streamer.go, line 44 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mskc55LBuVxj8c2bqpT:-Msl5fTt4gbt65FPYj9R:b4153mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L44)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: consider renaming the file to reflect the name of the struct implemented here.
</blockquote></details>

I chose the current naming `kv_batch_streamer.go` since it has `TxnKVStreamer` struct which mirrors `txnKVFetcher` struct from `kv_batch_fetcher.go`. I'll keep it as is, and we can rename both in the future if necessary.
___
*[pkg/sql/row/kv_batch_streamer.go, line 77 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskgKhL-THzbafA5sun:-MslRQsL90oRm3GnCzR3:b3hwqud) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L77)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If I understand this right, we create a new TxnKVStreamer every time an operator needs to fetch another batch of spans? So e.g. for the vectorized exec engine we need to start a streaming scan for every batch of spans? This example doesn't seem to follow the usage outlined in the Streamer comment (which suggests to keep enqueueing requests), and I think I'm getting lost trying to reconcile/follow the pattern through these layers between join reader and the Streamer.
</blockquote></details>

That's a very good catch. Indeed, as the code was written, we would create a new `Streamer` for each set of spans to scan (so for each batch of spans to lookup) in the vectorized index join. The row-by-row joinReader was already behaving as desired, and now the vectorized index join has been fixed.

(I think I ended up with this broken state due to the fact that initially I thought about using the streamer only in the row-by-row engine cause I mistakenly thought a new processor/operator implementation would be needed. Later though I realized that we can only implement the new `TxnKVStreamer` as an adapter, and everything else would just work. However, I incorrectly plumbed that into the vectorized engine. Thanks for catching!)
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 130 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskafTD1esM8z1ulTkp:-Msl7d-FE67ozvF7zpKl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/kv/kvclient/kvstreamer/streamer_test.go#L130)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why not run both blob sizes every test?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-06 22:26 UTC, yuzefovich commented
A little bit of the code movement. Done pushing for now.

2022-01-06 23:42 UTC, rharding6373 submitted a review, later dismissed
Thanks for clarifying! Looks great. It would be nice to have a bit more test coverage of the streamer. I made some suggestions in a comment. Otherwise, the code <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :tada:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Mslk-hB8zb6qqnEio4B:b-wg56tw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/sql/row/kv_batch_streamer.go, line 77 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskgKhL-THzbafA5sun:-MsleTZe3dOQckaKfqM_:b-wlbp84) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L77)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

That's a very good catch. Indeed, as the code was written, we would create a new `Streamer` for each set of spans to scan (so for each batch of spans to lookup) in the vectorized index join. The row-by-row joinReader was already behaving as desired, and now the vectorized index join has been fixed.

(I think I ended up with this broken state due to the fact that initially I thought about using the streamer only in the row-by-row engine cause I mistakenly thought a new processor/operator implementation would be needed. Later though I realized that we can only implement the new `TxnKVStreamer` as an adapter, and everything else would just work. However, I incorrectly plumbed that into the vectorized engine. Thanks for catching!)
</blockquote></details>

Ok, so my current understanding of the vectorized usage is that we will create a new `cFetcher` and `TxnKVStreamer` for every batch of spans, but the `Streamer` will be passed to the new ones so we'll reuse it for subsequent `Enqueue`s. Thanks for clarifying/fixing, it makes more sense now.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 98 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MslcvnHEUtmkwsrwphn:-MslcvnI88uXx2oanG5s:bq9oyaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c145a345bb8a0704deeebbf92a4f0c791218a66c/pkg/kv/kvclient/kvstreamer/streamer_test.go#L98)):*
> ```Go
> // when the keys to lookup are large (i.e. the enqueued requests themselves have
> // large memory footprint).
> func TestLargeKeys(t *testing.T) {
> ```

It would be good to add more tests to streamer_test for better coverage. As a start, some potentially useful tests that come to mind are:
* Happy path typical use case with multiple calls to `Enqueue`
* KV layer returns results out of order
* KV layer returns results in order
* KV layer returns results one at a time
* An input that goes over budget errors as expected
* Similar to `TestLargeKeys`, a test that mixes several small keys (where multiple can be requested at once) before and after one big key to make sure they are handled appropriately. Especially if the KV layer returns results one at a time.


<!-- Sent from Reviewable.io -->

2022-01-08 00:48 UTC, yuzefovich reviewed
Thanks for all the reviews Rachael!

Before merging, I'll give some more time to @andreimatei in case he wants to take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Msr8Lt48Rs1OFXcIWoC:by4pu7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/sql/row/kv_batch_streamer.go, line 77 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskgKhL-THzbafA5sun:-MsqqbmA5JcJEZ3XYR0A:b1vjacw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6f95f2af2809f01d52f2bac5162298ba253c73a/pkg/sql/row/kv_batch_streamer.go#L77)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Ok, so my current understanding of the vectorized usage is that we will create a new `cFetcher` and `TxnKVStreamer` for every batch of spans, but the `Streamer` will be passed to the new ones so we'll reuse it for subsequent `Enqueue`s. Thanks for clarifying/fixing, it makes more sense now.
</blockquote></details>

That's not quite right. We create only a single `cFetcher`, but that `cFetcher` will create a new `TxnKVStreamer` for every batch of spans, and for latter we'll use the same `kvstreamer.Streamer`. I.e. we have `ColIndexJoin` using a single `cFetcher` that on each `StartScanStreaming` call creates a new `TxnKVStreamer` which uses the single `kvstreamer.Streamer`. `TxnKVStreamer` is a light-weight object, so we don't care much about optimizing the allocations of that struct.

For reference, in the old path (i.e. not using the `Streamer`) the sequence is as follows: single `cFetcher` -> many `row.KVFetcher`s each creating new `txnKVFetcher` -> global `DistSender`.
___
*[pkg/kv/kvclient/kvstreamer/streamer_test.go, line 98 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MslcvnHEUtmkwsrwphn:-Msr6Uo67Agzx88Mvrcb:b454iyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c145a345bb8a0704deeebbf92a4f0c791218a66c/pkg/kv/kvclient/kvstreamer/streamer_test.go#L98)):*
Thanks for the suggestions! I incorporated some of them, see my thoughts below.

> Happy path typical use case with multiple calls to Enqueue

I think this is well covered by existing logic tests since an index join is such a ubiquitous operation. If it doesn't work in the happy case, then CRDB will likely not be able to start :)

> KV layer returns results out of order
> KV layer returns results in order

These two are probably well covered already and seem very hard to simulate in a unit test (some ideas that come to mind - introducing some knobs, or mocking out the KV layer).

> KV layer returns results one at a time

I don't know how to simulate this.

> An input that goes over budget errors as expected

Added another unit test for `Enqueue`. Also note there already exists `TestMemoryLimit` which exercises memory limit exceeded scenario in an end-to-end test, and I set it up such that the Streamer API is used.

> Similar to `TestLargeKeys`, a test that mixes several small keys (where multiple can be requested at once) before and after one big key to make sure they are handled appropriately. Especially if the KV layer returns results one at a time.

I, instead, adjusted `TestLargeKeys` to have two different scenarios - "only large keys" (the old one) and "random mix of large and small keys" (the new one). I think this achieves (sometimes) what you described.

----

I think what I'm struggling test-wise is that I don't see an easy way to unit test the Streamer in isolation without using end-to-end tests (which we already have plenty) or having to implement some of the logic that SQL fetchers perform in order to construct valid requests that would be interesting.


<!-- Sent from Reviewable.io -->

2022-01-10 11:02 UTC, erikgrinaker reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqsqtleCvJ_lFDeXtNS:-Mt2_t4X0c8c4INA3zvL:b-u5pneg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L73)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Callers are expected to measure the size of `reqs` they are enqueuing. In a case when a single key to lookup is very large, the streamer now makes an exception and will proceed with processing the corresponding request, even if it puts its budget in debt, but only if the request is alone.

I added a corresponding test which revealed that in the row-by-row engine we currently create such requests that can exceed the streamer's budget on their own, so I added the second commit which adjusted that and brought the row-by-row `joinReader` to be similar to the vectorized `ColIndexJoin` - i.e. buffer requests up to the limit without exceeding it, except in a degenerate case of a single large request.

Another solution is to allow the budget to go into debt all the time based on the footprint of the enqueued requests. Then, all the requests will be processed sequentially with `TargetBytes == 1` until the budget gets out of debt.

I'm not sure what option is better, currently leaning towards allowing the budget to go into debt only if the large request is alone. Thoughts?
</blockquote></details>

Great, thanks. I think that's reasonable, and it matches the default semantics of the KV API.


<!-- Sent from Reviewable.io -->

2022-01-10 18:12 UTC, andreimatei reviewed
I've taken a look and left a couple of comments. There's a bit more here that I can do justice for without taking a lot of time, so feel free to go ahead with me. Unless you particularly want me, in which case I'm happy to review more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Mt4AlzP0-cahSjVzcuA:b-prvs7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 15 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3qOoWAb8jFZ14hGjl:-Mt3qOoWAb8jFZ14hGjm:b88ucnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L15)):*
> ```Go
> // avgResponseEstimator is a helper that estimates the average size of responses
> // received by the Streamer. It is **not** thread-safe.
> type avgResponseEstimator struct {
> ```

I haven't fully followed the flow, but what I imagined we'd want to estimate is the size of a row, (or even a single key, if rows are too complicated).  For scans, the size of a "response" is influenced by the memory limit that we put on the request, right? So 
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 16 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3fyUh5sX7fkDf_FH7:-Mt3fyUh5sX7fkDf_FH8:b-250wyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L16)):*
> ```Go
> // received by the Streamer. It is **not** thread-safe.
> type avgResponseEstimator struct {
> 	actual struct {
> ```

seems weird to me to have a single anonymous struct field. Is there a point to it?
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 17 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3i8P3-BTu9lfbN48g:-Mt3i8P3-BTu9lfbN48h:bhtnilw) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L17)):*
> ```Go
> type avgResponseEstimator struct {
> 	actual struct {
> 		totalSize         int64
> ```

consider `responseBytes`
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 18 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3i23_Bmoe464Ax_fi:-Mt3i23_Bmoe464Ax_fj:b6cw4eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L18)):*
> ```Go
> 	actual struct {
> 		totalSize         int64
> 		totalNumResponses int64
> ```

I think the simpler `numResponses` would be just as good, if not better
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 38 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3hgT0EmJEAZvExs9S:-Mt3hgT0EmJEAZvExs9T:b6tsc5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L38)):*
> ```Go
> // update updates the actual information based on numResponses responses that
> // took up actualResponsesSize bytes and correspond to a single BatchResponse.
> func (e *avgResponseEstimator) update(actualResponsesSize int64, numResponses int64) {
> ```

since you've extracted these helpers into this struct, it seems inappropriate to me to name an argument `actual` here. That suggest a reference to some other quantity, and this struct is unaware of any context. Just call it `responseBytes`.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 23 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3zeMZEiiati7Rh7_7:-Mt3zeMZEiiati7Rh7_8:b-c9cf49) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L23)):*
> ```Go
> // client.
> //
> // This struct is a wrapper on top of mon.BoundAccount because we want to
> ```

`budget` also provides waiting, which `mon.BoundAccount` doesn't, right?
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 50 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt4-6ud6D6VSfqTf4_t:-Mt4-6ud6D6VSfqTf4_u:b-8qpcxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L50)):*
> ```Go
> // The budget itself is responsible for staying under the limit, so acc should
> // be bound to an unlimited memory monitor. This is needed in order to support
> // the case of budget going into debt. Note that although it is an "unlimited
> ```

I think this comment is confusing. `acc's` monitor can be limited (and in fact is limited; the comment says that it's both limited and not limited). The `budget` has its own limit, which is expected to be lower that the monitor's. This budget's relationship to the monitor is not special (is it?) so I don't think it deserves any particular comment.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 67 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt40S6yALf3lVMKzzwI:-Mt40S6yALf3lVMKzzwJ:b-p7ypue) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L67)):*
> ```Go
> 
> // available returns how many bytes are currently available in the budget. The
> // answer can be negative, in case the Streamer has used un-budgeted memory
> ```

make a reference to the "debt" that you talk about in other places
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 82 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt410woBsqHaRB6a5iX:-Mt410woBsqHaRB6a5iY:bcglo7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L82)):*
> ```Go
> // root pool budget is used up such that the budget's limit cannot be fully
> // reserved.
> // - allowDebt indicates whether the budget is allowed to go into debt on this
> ```

please add words here further clarifying that an error can be returned even when `allowDebt` is set.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 338 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3vQB96TU93aHtwSqW:-Mt3vQB96TU93aHtwSqX:b-l0pfs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/streamer.go#L338)):*
> ```Go
> 	}
> 	s.hints = hints
> 	s.coordinator.hasWork = make(chan struct{}, 1)
> ```

Personally, I try to avoid buffered channels whenever I can. They complicated, cause you have to keep track of the possible state of the channel in relation to the state of `requestsToServe`. I think things will likely get simpler if you use a `sync.Cond`.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 476 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3u-FX-g75sbyAilhK:-Mt3u-FX-g75sbyAilhL:b-cwsnng) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/streamer.go#L476)):*
> ```Go
> 		}
> 
> 		s.mu.requestsToServe = append(s.mu.requestsToServe, r)
> ```

I think it's fishy that there's two places that append to `requestsToServe` - this one, and `addRequest()`. I'd try to use `addRequest()` here.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 504 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3uYN58U0T01CzZ38X:-Mt3uYN58U0T01CzZ38Y:betd293) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/streamer.go#L504)):*
> ```Go
> 	}
> 
> 	// This will never block because hasWork is a buffered channel, and new
> ```

`addRequest()` deals with `hasWork` being full. Perhaps the code paths that call `addRequests` need that, [...]

2022-01-10 18:20 UTC, andreimatei reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 15 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3qOoWAb8jFZ14hGjl:-Mt4CDm2C2aaO1VOt_lR:bcx5jtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L15)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I haven't fully followed the flow, but what I imagined we'd want to estimate is the size of a row, (or even a single key, if rows are too complicated).  For scans, the size of a "response" is influenced by the memory limit that we put on the request, right? So 
</blockquote></details>

Scratch this comment, I was confused. But remind me, do we want to support partial scans? If so, how is the estimator supposed to deal with them?


<!-- Sent from Reviewable.io -->

2022-01-11 00:33 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 15 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3qOoWAb8jFZ14hGjl:-Mt526lwAMzdmerfBlSk:b3ibeur) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L15)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Scratch this comment, I was confused. But remind me, do we want to support partial scans? If so, how is the estimator supposed to deal with them?
</blockquote></details>

That's a good question. Yes, we do support partial scans - whenever `TargetBytes` is set too low so that the scan response cannot be complete within a single range, then we'll be receiving partial responses, and we'll currently account each part of the whole response separately, thus, skewing the average to smaller values. This is suboptimal, and I left a TODO to follow up on this.
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 16 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3fyUh5sX7fkDf_FH7:-Mt50vCp4nVL4vGC7pAL:b-t4i6f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L16)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

seems weird to me to have a single anonymous struct field. Is there a point to it?
</blockquote></details>

No point at the moment (this was a remnant of the past when I tried to use an exponential moving average), removed.
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 17 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3i8P3-BTu9lfbN48g:-Mt512nrCxQyuwFP6bxM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L17)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider `responseBytes`
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 18 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3i23_Bmoe464Ax_fi:-Mt513ER4tH-VWZjJWjW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L18)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think the simpler `numResponses` would be just as good, if not better
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/avg_response_estimator.go, line 38 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3hgT0EmJEAZvExs9S:-Mt52d-r7fGQrjl-jHzk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/avg_response_estimator.go#L38)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

since you've extracted these helpers into this struct, it seems inappropriate to me to name an argument `actual` here. That suggest a reference to some other quantity, and this struct is unaware of any context. Just call it `responseBytes`.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 23 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3zeMZEiiati7Rh7_7:-Mt53Baz1E2Vw7SNx4Is:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L23)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`budget` also provides waiting, which `mon.BoundAccount` doesn't, right?
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 50 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt4-6ud6D6VSfqTf4_t:-Mt53YhJ1CypsPQdKdc4:bafk2vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this comment is confusing. `acc's` monitor can be limited (and in fact is limited; the comment says that it's both limited and not limited). The `budget` has its own limit, which is expected to be lower that the monitor's. This budget's relationship to the monitor is not special (is it?) so I don't think it deserves any particular comment.
</blockquote></details>

`acc`'s monitor has to be "unlimited" in a sense that it doesn't have its own local limit, but only inherits the limit from the root SQL monitor (through several "generations" of monitors - something like `budget monitor -> flow monitor -> txn monitor -> root SQL monitor` with all monitors except for the root being "unlimited"). If `acc`'s monitor were to have a local limit (say `distsql_workmem`), then the `budget` wouldn't be able to go into debt above the value of `distsql_workmem` limit (`64MiB` by default).

I think the first two sentences of this paragraph should be kept, but the last sentence could be dropped if you think it'll be less confusing overall. My goal with the last sentence was to alleviate the concern of a reader when they see "unlimited memory monitor" phrase. @andreimatei @rharding6373 please let me know what phrasing you prefer here.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 67 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt40S6yALf3lVMKzzwI:-Mt54oPiCa18sO7ae_QG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L67)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

make a reference to the "debt" that you talk about in other places
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/budget.go, line 82 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt410woBsqHaRB6a5iX:-Mt559s61Zg9a64I6akM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/budget.go#L82)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please add words here further clarifying that an error can be returned even when `allowDebt` is set.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 338 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3vQB96TU93aHtwSqW:-Mt59jDA3Ot11nD8NXJV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/streamer.go#L338)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Personally, I try to avoid buffered channels whenever I can. They complicated, cause you have to keep track of the possible state of the channel in relation to the state of `requestsToServe`. I think things will likely get simpler if you use a `sync.Cond`.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 476 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mt3u-FX-g75sbyAilhK:-Mt59ygo6zR5JJ3EfoMn:b-l4b2qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f9ec58a3060e90bf558d4010458afcd5725121a/pkg/kv/kvclient/kvstreamer/streamer.go#L476)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it's fishy that there's two places tha [...]

2022-01-11 00:46 UTC, yuzefovich reviewed
Andrei, thanks for the review! I know that Becca has some more comments, so I'll definitely wait for her to post the feedback. I'd like to merge this by the end of this week, so there is still some time for folks to review this further if interested.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-Mt5Yv754o2rnoKs35HV:b-t8u225)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)



<!-- Sent from Reviewable.io -->

2022-01-12 02:48 UTC, rytaft reviewed
Looks great! Just a few additional comments.

> Reviewed 27 of 27 files at r6, 1 of 1 files at r7, 19 of 30 files at r8, 6 of 9 files at r9, 1 of 5 files at r10, 1 of 2 files at r11, 1 of 2 files at r12, 2 of 3 files at r13, 2 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MtBAkbm8h7QWLMD8XGx:b-j6b8f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 150 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskCF1h5eECgiOcr-er:-MskCF1h5eECgiOcr-es:b-314k0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L150)):*
> ```Go
> 	// pendingRow tracks the row that has already been read from the input but
> 	// was not included into the lookup batch because it would make the batch
> 	// exceed curBatchSizeBytes.
> ```

curBatchSizeBytes -> batchSizeBytes ?
___
*[pkg/sql/rowexec/joinreader.go, line 707 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskEeG0CRq5Crz5yuC2:-MskEeG0CRq5Crz5yuC3:bpvzfz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L707)):*
> ```Go
> 	var encDatumRow rowenc.EncDatumRow
> 	var meta *execinfrapb.ProducerMetadata
> 	var rowSize int64
> ```

Why do these variables need to be defined outside of the loop? I think it would be a bit clearer (and less error-prone) if they were scoped inside the loop.
___
*[pkg/sql/rowexec/joinreader.go, line 732 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskCM7z8eukTI4EZFpI:-MskCM7z8eukTI4EZFpJ:b-xqbuy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L732)):*
> ```Go
> 			if jr.curBatchSizeBytes > 0 && jr.curBatchSizeBytes+rowSize > jr.batchSizeBytes {
> 				// Adding this row to the current batch will make the batch
> 				// exceed jr.curBatchSizeBytes. Additionally, the batch is not
> ```

curBatchSizeBytes -> batchSizeBytes ?

Also, why does it matter if the batch is not empty?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteX2e-gabCIJxV6nO:-MslRiMV9hCfE7NFvL7C:b-eh5x9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L147)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Used `EnqueueKeys` since I think it is less ambiguous ("request keys" could also be thought of `roachpb.Key`s that are used in `roachpb.RequestUnion`s).
</blockquote></details>

I don't love the name `EnqueueKeys`... any other option that would be a bit more self documenting? Maybe `RequestKeysSatisfied`?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 789 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-Mr0Cpxv9FlKyDikTqL6:-MtB--dbBFDw3ts7B2mY:b-tnnld) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L789)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I switched to concrete implementations for the `Streamer` and `budget`, so it seems a bit difficult to unit test this :/ Any ideas for this without introducing the interfaces back? This `workerCoordinator` is tightly coupled with the `Streamer` too.
</blockquote></details>

I think the tests you added are good. Also I think the logic of this function is easier to understand now so I'm less concerned about unit-testing this specifically.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 180 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtAWa8d3oVCF5MdUYXv:-MtAWa8eBLwSX5xDEZpa:bvabmnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3fde1a6ff9202490aea4285c295006ac347d6/pkg/kv/kvclient/kvstreamer/streamer.go#L180)):*
> ```Go
> // The parallelism is achieved by splitting the incoming requests into
> // single-range batches where each such batch will hit a fast-path in the
> // DistSender (unless there have been range boundaries' changes). Since these
> ```

nit: range boundaries' changes -> changes to range boundaries
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 363 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtAXx-47DiQOcZ0KROF:-MtAXx-47DiQOcZ0KROG:bhbk5sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cb3fde1a6ff9202490aea4285c295006ac347d6/pkg/kv/kvclient/kvstreamer/streamer.go#L363)):*
> ```Go
> // return an error if that footprint exceeds the Streamer's limitBytes. The
> // exception is made only when a single request is enqueued in order to allow
> // the caller proceed when the key to lookup is arbitrarily large. As a rule of
> ```

nit: allow the caller proceed -> allow the caller to proceed
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB14co4wBfUIqzJFd-:-MtB14co4wBfUIqzJFd0:bep4owx) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L778)):*
> ```Go
> 		targetBytes := int64(len(singleRangeReqs.reqs)) * avgResponseSize
> 		if targetBytes > availableBudget {
> 			targetBytes = availableBudget
> ```

This seems suspicious -- is this what is getting accounted for by the memory monitor in the budget? Don't we want that memory monitor to track what we actually expect the size of the response to be?

Seems to me like this is more complicated than it needs to be. Why not just do the following:
```
availableBudget := w.s.budget.limitBytes - w.s.budget.mu.acc.Used()
singleRangeReqs := requestsToServe[numRequestsIssued]
targetBytes := int64(len(singleRangeReqs.reqs)) * avgResponseSize
if availableBudget < targetBytes {
	if !headOfLine {
		// We don't have enough budget available to serve this request,
		// and there are other requests in flight, so we'll wait for
		// some of them to finish.
		break
	}
	budgetIsExhausted = true
}
if err := w.s.budget.consumeLocked(ctx, targetBytes, headOfLine /* allowDebt */); err != nil {
	...
}
```
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 792 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB6IWlAL69OqL81RpS:-MtB6IWlAL69OqL81RpT:b-bcjdm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L792)):*
> ```Go
> 				// other requests are fully processed (i.e. the corresponding
> 				// results are Release()'d), we'll be able to make progress on
> 				// this request too, without exceeding the root memory pool.
> ```

but what if we're actually about to OOM? Is it worth adding a second return value to `consumeLocked` to differentiate?


<!-- Sent from Reviewable.io -->

2022-01-12 04:44 UTC, yuzefovich reviewed
Thanks for the review!

Had to rebase on top of master to resolve merge conflicts and merge skew.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MtBaCrt3wXhLnP8NVbt:b-3914uh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/sql/rowexec/joinreader.go, line 150 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskCF1h5eECgiOcr-er:-MtBXrV42SUostkq-oR1:b-af1832) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L150)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

curBatchSizeBytes -> batchSizeBytes ?
</blockquote></details>

Yep, thanks.
___
*[pkg/sql/rowexec/joinreader.go, line 707 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskEeG0CRq5Crz5yuC2:-MtBY5uG8Pd8CQIulnyh:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L707)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why do these variables need to be defined outside of the loop? I think it would be a bit clearer (and less error-prone) if they were scoped inside the loop.
</blockquote></details>

Good point, done.
___
*[pkg/sql/rowexec/joinreader.go, line 732 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskCM7z8eukTI4EZFpI:-MtBYANt-I8sCckkiHuY:bytnp4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L732)):*
Fixed, thanks.

> Also, why does it matter if the batch is not empty?

If the batch is empty and adding this (first) row would exceed `batchSizeBytes`, then we have a degenerate case of a very large key to lookup. If we don't add this row into the batch, then we'd be stalled - we'd generate no spans, so we'd not perform the lookup of anything.
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteX2e-gabCIJxV6nO:-MtBYkF9B8-kWczMPW2j:b-pjyiwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L147)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't love the name `EnqueueKeys`... any other option that would be a bit more self documenting? Maybe `RequestKeysSatisfied`?
</blockquote></details>

I think currently there is nice symmetry between `Enqueue` calls and `[]Result` returned by `GetResults` - the former has `enqueueKeys` argument and the latter uses those values. I agree that `EnqueueKeys` is not great, and `RequestKeysSatisfied` sounds better in isolation, but it is more confusing when looking at the Streamer API as a whole. I don't feel too strongly about this though, so please let me know if my reasoning doesn't make sense.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB14co4wBfUIqzJFd-:-MtBSGeG4VToecJWammW:b6br1qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L778)):*
> This seems suspicious -- is this what is getting accounted for by the memory monitor in the budget? Don't we want that memory monitor to track what we actually expect the size of the response to be?

Yes, `targetBytes` will be registered with the memory account. Then, for `headOfLine == false` requests the response will not exceed `TargetBytes` limit, so we should be good on the budget usage here.

What you are proposing could work; however, we would not be utilizing the available budget to the fullest and would only expect to receive "full" responses (based on our estimate). As the code written currently, we can issue a request for which we expect to receive a partial result. 

Consider the following scenario: our budget is 3MiB, and we have two requests both of which we expect to take up 2MiB in response. As the code is written, we'll issue the first request with the full 2MiB and the second with 1MiB, so we'll receive the full first response and the half second response; then we'll only need to issue the second half of the second request. (This discussion assumes that we're performing Scans, not Gets, and that we could receive that partial response.) With your proposal we'll be sending out one request at a time, but we'll be receiving full responses every time. I think the strategy with partial responses should be faster. I guess we could also track whether there are only Gets in the request we're about to send out with partial `targetBytes`, and if there are no Scans, then follow your proposal. Our estimate can also be wrong, especially before receiving any responses, so it's probably better to send out more requests given that we're using strict `TargetBytes` limits. Thoughts?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 792 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB6IWlAL69OqL81RpS:-MtBV54J5yb1Th5dTJPU:b59395h) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L792)):*
> but what if we're actually about to OOM?

Here I think we should not be concerned about it - the streamer is within its budget and hasn't pushed the root memory pool past its limit (we're bailing on the request that would have done so). For not head-of-the-line request there are two scenarios how we can get the error here: the node is close to exhausting `--max-sql-memory` (i.e. close to OOM) without this streamer being responsible (when no requests have been issued) or with this streamer playing its part. If it's the latter, I think it's ok to not exit and let the head-of-the-line request make the determination whether to proceed or not. I added more words into the comments. Thoughts?


<!-- Sent from Reviewable.io -->

2022-01-12 15:41 UTC, rytaft reviewed
> Reviewed 30 of 30 files at r16, 1 of 1 files at r17, 29 of 29 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 732 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MskCM7z8eukTI4EZFpI:-MtDQVjz9bD0NhXspDSd:bsjx9dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d4fb2693ab8d8f6df65b4d76b4a86c5eaf17447/pkg/sql/rowexec/joinreader.go#L732)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Fixed, thanks.

> Also, why does it matter if the batch is not empty?

If the batch is empty and adding this (first) row would exceed `batchSizeBytes`, then we have a degenerate case of a very large key to lookup. If we don't add this row into the batch, then we'd be stalled - we'd generate no spans, so we'd not perform the lookup of anything.
</blockquote></details>

Makes sense -- can you clarify the comment a bit?
___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteX2e-gabCIJxV6nO:-MtDR4Gb1hbmq7yHxNRS:b-ym6471) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L147)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think currently there is nice symmetry between `Enqueue` calls and `[]Result` returned by `GetResults` - the former has `enqueueKeys` argument and the latter uses those values. I agree that `EnqueueKeys` is not great, and `RequestKeysSatisfied` sounds better in isolation, but it is more confusing when looking at the Streamer API as a whole. I don't feel too strongly about this though, so please let me know if my reasoning doesn't make sense.
</blockquote></details>

Then maybe `EnqueueKeysSatisfied`? I don't feel too strongly though, feel free to leave it as-is if you prefer.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB14co4wBfUIqzJFd-:-MtDt3rg0zdjL-2te1K8:bokvlo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L778)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> This seems suspicious -- is this what is getting accounted for by the memory monitor in the budget? Don't we want that memory monitor to track what we actually expect the size of the response to be?

Yes, `targetBytes` will be registered with the memory account. Then, for `headOfLine == false` requests the response will not exceed `TargetBytes` limit, so we should be good on the budget usage here.

What you are proposing could work; however, we would not be utilizing the available budget to the fullest and would only expect to receive "full" responses (based on our estimate). As the code written currently, we can issue a request for which we expect to receive a partial result. 

Consider the following scenario: our budget is 3MiB, and we have two requests both of which we expect to take up 2MiB in response. As the code is written, we'll issue the first request with the full 2MiB and the second with 1MiB, so we'll receive the full first response and the half second response; then we'll only need to issue the second half of the second request. (This discussion assumes that we're performing Scans, not Gets, and that we could receive that partial response.) With your proposal we'll be sending out one request at a time, but we'll be receiving full responses every time. I think the strategy with partial responses should be faster. I guess we could also track whether there are only Gets in the request we're about to send out with partial `targetBytes`, and if there are no Scans, then follow your proposal. Our estimate can also be wrong, especially before receiving any responses, so it's probably better to send out more requests given that we're using strict `TargetBytes` limits. Thoughts?
</blockquote></details>

Ok, got it. I re-reviewed the whole file, so now I think I finally have a sense of how this all works. And I see that you re-account for the responses with the actual size after they are received, so this all makes sense.

I think what I was missing is that "targetBytes" is what gets passed to the kv layer to tell it how much data to return. For non-head-of-line requests this is a strict limit, while for head-of-line requests the limit can be exceeded. You sort of hint at that in the comment above where you set availableBudget to 1, but I was definitely missing the bigger picture. You might consider adding a comment somewhere to explain this.

But anyway, no need to change the code, I think what you've done seems reasonable.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 792 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB6IWlAL69OqL81RpS:-MtDvfueC0j6-bDs-dfm:b7e4hsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L792)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

> but what if we're actually about to OOM?

Here I think we should not be concerned about it - the streamer is within its budget and hasn't pushed the root memory pool past its limit (we're bailing on the request that would have done so). For not head-of-the-line request there are two scenarios how we can get the error here: the node is close to exhausting `--max-sql-memory` (i.e. close to OOM) without this streamer being responsible (when no requests have been issued) or with this streamer playing its part. If it's the latter, I think it's ok to not exit and let the head-of-the-line request make the determination whether to proceed or not. I added more words into the comments. Thoughts?
</blockquote></details>

Makes sense, thanks
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 91 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDT_VS88dh04hfLOUW:-MtDT_VS88dh04hfLOUX:b-rq5u28) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L91)):*
> ```Go
> 	}
> 	// EnqueueKeys identifies the requests that this Result satisfies. In
> 	// OutOfOrder mode, a single Result can satisfy multiple identical requests.
> ```

nit: what do you mean by "identical" requests? Different keys that target the same range? Also, for InOrder mode, the consecutive requests would also have to target the same range, correct?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 105 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDUfty1I92Lg4Ubp0B:-MtDUfty1I92Lg4Ubp0C:b-its85b) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L105)):*
> ```Go
> 	MemoryTok ResultMemoryToken
> 	// position tracks the ordinal among all originally enqueued requests that
> 	// this result satisfies. See singleRangeBatch.positions for more details.
> ```

how does `position` relate to `EnqueueKeys`? Consider expanding the comment
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 483 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDcJ9g40apmr0WfE_y:-MtDcJ9h0kwPMLDkGiGW:b-br4742) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L483)):*
> ```Go
> 		s.mu.requestsToServe = append(s.mu.requestsToServe, r)
> 
> 		// Determine next seek key, taking potentially sparse requests into
> ```

Do you have any tests for sparse requests? E.g., if the `reqs` are for  [...]

2022-01-12 18:32 UTC, yuzefovich reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvcoord/streamer.go, line 147 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MqteX2e-gabCIJxV6nO:-MtE6BIX1kEKrivtb8bq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d485a01ebca0ac01c165ec897e6fee3752b28b6/pkg/kv/kvclient/kvcoord/streamer.go#L147)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Then maybe `EnqueueKeysSatisfied`? I don't feel too strongly though, feel free to leave it as-is if you prefer.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 778 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtB14co4wBfUIqzJFd-:-MtENTyc4VeqnImRsgsq:b-p6zkwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/21b5881b330139bb84f24579912081d36355e116/pkg/kv/kvclient/kvstreamer/streamer.go#L778)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Ok, got it. I re-reviewed the whole file, so now I think I finally have a sense of how this all works. And I see that you re-account for the responses with the actual size after they are received, so this all makes sense.

I think what I was missing is that "targetBytes" is what gets passed to the kv layer to tell it how much data to return. For non-head-of-line requests this is a strict limit, while for head-of-line requests the limit can be exceeded. You sort of hint at that in the comment above where you set availableBudget to 1, but I was definitely missing the bigger picture. You might consider adding a comment somewhere to explain this.

But anyway, no need to change the code, I think what you've done seems reasonable.
</blockquote></details>

Sounds good, added more comments into the code.

Note that `TargetBytes` is not a strict limit only when we have head-of-the-line request AND a single large row is returned in the response (because we have to make progress), if there are some full rows that don't exceed `TargetBytes`, then KV will not include the row that would put the response above `TargetBytes` limit.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 91 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDT_VS88dh04hfLOUW:-MtE6nLn9kHBaNNpmC4a:bkcbqyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L91)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: what do you mean by "identical" requests? Different keys that target the same range? Also, for InOrder mode, the consecutive requests would also have to target the same range, correct?
</blockquote></details>

"Identical" requests are exactly the same, regardless of the range boundaries, i.e. the caller had something like `reqs = [2]{Scan('a', 'b'), Scan('a', 'b')}`. At the moment this cannot occur because we only support unique requests, but in the future the streamer will be performing the de-duplication of such requests.

An open question is whether we want to perform this de-duplication within each range separately (i.e. within `singleRangeBatch`), then the comment will need an adjustment. It seems beneficial to me to do this per-range de-duplication, but we could do it only for `OutOfOrder` mode (because for `InOrder` we cannot make the results be consecutive unless the original requests are fully contained within a single range in which case it is the same as "global" de-duplication).
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 105 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDUfty1I92Lg4Ubp0B:-MtEA3fO1g-xSHXELMzp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L105)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

how does `position` relate to `EnqueueKeys`? Consider expanding the comment
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 483 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDcJ9g40apmr0WfE_y:-MtEAm-L01hV3PAmQIz5:b4ic55x) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L483)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you have any tests for sparse requests? E.g., if the `reqs` are for `[/2 - /5]` and `[/21 - /25]`, and we have range boundaries at 10 and 20?
</blockquote></details>

I didn't add any explicit tests for this, but I think we're getting sufficient test coverage with `fakedist` logic test configs. This code (as well as the comment) was also copied from `DistSender.divideAndSendBatchToRanges`.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 928 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDq1EMC_XISURLtQ1_:-MtEBCcbBiXPM-K72WHB:b5hwy2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L928)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Would you ever have a partial result from a `get`? Or is it always all or nothing?
</blockquote></details>

I think by definition `GetRequest` can either receive a full or an empty response because the response is a single Value (from a single key-value pair), and we never break up values across responses.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1105 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDrr6EBB7Yxj_YhkAp:-MtERqIS4vMybBcYDtmM:bi089vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L1105)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

shouldn't this only be incremented if `r.ScanResp.Complete` is true?

Related: do you have any tests for scans that touch multiple ranges?
</blockquote></details>

Nice catch, fixed.

I started thinking about how to add a regression test for this and realized that currently it's not possible because the Streamer at the moment will only process Get requests (because for index joins to issue Scan requests we need to have multiple column families in the primary index). 

Once we add the support of multiple column families, I'll try reverting the fix and checking whether CI would have caught this (I'm pretty sure it would).


<!-- Sent from Reviewable.io -->

2022-01-12 20:01 UTC, rytaft approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Great work!!

> Reviewed 29 of 29 files at r19, 29 of 29 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MtEsG6p-eQv5ZGJawfk:bgu8nsn)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 91 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDT_VS88dh04hfLOUW:-MtEqxak58Z9BvNe2Qf-:bi1metz) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L91)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

"Identical" requests are exactly the same, regardless of the range boundaries, i.e. the caller had something like `reqs = [2]{Scan('a', 'b'), Scan('a', 'b')}`. At the moment this cannot occur because we only support unique requests, but in the future the streamer will be performing the de-duplication of such requests.

An open question is whether we want to perform this de-duplication within each range separately (i.e. within `singleRangeBatch`), then the comment will need an adjustment. It seems beneficial to me to do this per-range de-duplication, but we could do it only for `OutOfOrder` mode (because for `InOrder` we cannot make the results be consecutive unless the original requests are fully contained within a single range in which case it is the same as "global" de-duplication).
</blockquote></details>

You could possibly do it for InOrder too if you buffer results, right? Anyway, up to you if you want to change the comment now or later.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 483 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDcJ9g40apmr0WfE_y:-MtErTu98Nps84SsiE1O:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L483)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I didn't add any explicit tests for this, but I think we're getting sufficient test coverage with `fakedist` logic test configs. This code (as well as the comment) was also copied from `DistSender.divideAndSendBatchToRanges`.
</blockquote></details>

:thumbsup: 
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1105 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDrr6EBB7Yxj_YhkAp:-MtErwIzBYfMt9rSsIaZ:bq0ncok) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L1105)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Nice catch, fixed.

I started thinking about how to add a regression test for this and realized that currently it's not possible because the Streamer at the moment will only process Get requests (because for index joins to issue Scan requests we need to have multiple column families in the primary index). 

Once we add the support of multiple column families, I'll try reverting the fix and checking whether CI would have caught this (I'm pretty sure it would).
</blockquote></details>

sounds good


<!-- Sent from Reviewable.io -->

2022-01-12 21:16 UTC, yuzefovich reviewed
Thanks everyone for the feedback! I'll go ahead and merge this, but in case any feedback comes up, I'm more than happy to address it in a follow-up.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-:-MtF8TK3AKlMIdff5iH3:blk7rkh)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 91 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68430#-MtDT_VS88dh04hfLOUW:-MtF7B4k8EJM8MsxAOUj:bgj3w0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/938a85667671d726c634ad5e553ab0e17c4d3511/pkg/kv/kvclient/kvstreamer/streamer.go#L91)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

You could possibly do it for InOrder too if you buffer results, right? Anyway, up to you if you want to change the comment now or later.
</blockquote></details>

Hm, `EnqueueKeysSatisfied` can only have multiple values in InOrder if a single `Result` satisfies multiple consecutive results, so I think the comment in the code is correct as is. You are right that we can perform buffering (and that we should be doing de-duplication regardless of the mode - my previous comment above was wrong), but the buffered result will be returned later in `InOrder`, through a separate `Result` object.


<!-- Sent from Reviewable.io -->

2022-01-12 22:18 UTC, merged