sql,jobs: create SQL Stats Compaction Job and resumer
cockroachdb/cockroach pull request #68434
Opened 2021-08-04 17:50 UTC by Azhng

## First Commit 

sql,util: refactor checking for running jobs to its own util package

Release note: None

## Second Commit

sql,jobs: create SQL Stats Compaction Job and resumer

This commit introduces the SQL Stats Compaction job type
and a barebone implementation of the SQL Stats compaction.

Followed by #68401

Release note: None

2021-08-04 17:50 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68434)
<!-- Reviewable:end -->

2021-08-11 15:00 UTC, matthewtodd requested changes
:tada: 

> Reviewed 3 of 3 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-MgpidPwBxLwFtTWbBhK:bjwa7hh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpaY_LDSCYgSUiwlhF:-MgpaY_LDSCYgSUiwlhG:b-676qib) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/-- commits#L10)):*
nit: "barebones"
___
*[pkg/sql/compact_sql_stats.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpc0qfBtdw7vIHDKu1:-Mgpc0qfBtdw7vIHDKu2:b-4sts73) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/compact_sql_stats.go#L54)):*
> ```Go
> 	return db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 		if err != nil {
> 			if jobErr := r.Job.FractionProgressed(ctx, txn, func(ctx context.Context, _ jobspb.ProgressDetails) float32 {
> ```

Maybe a comment here, because it's a little unclear to me what this line is doing. Does the literal `0` in the callback mean anything, like are we checking that the job hasn't made any progress? Or are we just using `FractionProgressed` for its error-checking capabilities, but we don't actually care about progress?
___
*[pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpawLnDWxB8J5eamdE:-MgpawLnDWxB8J5eamdF:b-3yvjtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go#L59)):*
> ```Go
> 	"sql.stats.persisted_rows.max",
> 	"maximum number of rows of statement and transaction"+
> 		" statistics will be persisted in the system tables",
> ```

nit: "statistics _that_ will be"
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpdHyG4clndAL7KUwo:-MgpdHyG4clndAL7KUwp:be9yaop) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L41)):*
> ```Go
> // StatsCompactorKnobs can be used to tune the behavior of
> // StatsCompactor.
> type StatsCompactorKnobs struct {
> ```

If these are just for testing, maybe call them `StatsCompactorTestingKnobs`?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpdb5x5eGe8bmMXEJI:-Mgpdb5x5eGe8bmMXEJJ:bjhgah4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L69)):*
> ```Go
> 	}
> 
> 	stmtStatsEntryCnt, txnStatsEntryCnt, err := c.getExistingStmtAndTxnStatsEntries(ctx)
> ```

Is "cnt" a common abbreviation for "count" around here? Maybe spell it out if not?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpdpel6y5Tg1D6Gidk:-Mgpdpem-O0c_7C44Icv:b8cw2yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L87)):*
> ```Go
> 	stmt := "SELECT count(*) FROM system.statement_statistics"
> 	if c.TestingKnobs != nil && c.TestingKnobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.statement_statistics"
> ```

This is the same `stmt` as above, did you mean to make something different happen here?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpeH42Byad4X84yh1I:-MgpeH432wOLK2EGxFrj:bvqbcke) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L103)):*
> ```Go
> 	stmtStatsEntryCnt = int64(tree.MustBeDInt(row[0]))
> 
> 	// stmt = "SELECT count(*) FROM system.transaction_statistics AS OF SYSTEM TIME follower_read_timestamp()"
> ```

Kill this comment, yeah?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpeUJ26R8czA6UYrJJ:-MgpeUJ26R8czA6UYrJK:b-8yo7zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L106)):*
> ```Go
> 	stmt = "SELECT count(*) FROM system.transaction_statistics"
> 	if c.TestingKnobs != nil && c.TestingKnobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.transaction_statistics"
> ```

Ditto, same `stmt` as above.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpefhfAAE0LO-9MvQH:-Mgpefhg0nSEzhp_ygAm:bk4qkq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L138)):*
> ```Go
>   SELECT %[2]s
>   FROM %[1]s
>   ORDER BY aggregated_ts
> ```

Maybe an explicit `ASC` here? I get nervous deleting things, lol.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpgFKP-q0E-iQZTaA-:-MgpgFKP-q0E-iQZTaA0:bvshuhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go#L53)):*
> ```Go
> 
> // CheckExistingCompactionJob checks for existing SQL Stats Compaction job
> // that are either PAUCED, CANCELED, or RUNNING. If so, it returns a
> ```

`PAUSED`
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgphqZcBYrtSyN1P4Eg:-MgphqZcBYrtSyN1P4Eh:bsn7ruk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L54)):*
> ```Go
> 
> 	stopper := stop.NewStopper()
> 	defer stopper.Stop(ctx)
> ```

Just curious, what does this `stopper` stop? I don't see it used below. Does it look for magic stuff in the `ctx`?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgphFNV34jzulLm9XbF:-MgphFNV34jzulLm9XbG:b-9975dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L100)):*
> ```Go
> 	require.Equal(t, maxPersistedRowLimit, len(actualStmtFingerprints))
> 	require.Equal(t, maxPersistedRowLimit, len(actualTxnFingerprints))
> 	for fingerprintID := range actualTxnFingerprints {
> ```

super-nit: This code usually talks about statements, then transactions, so maybe move this for loop down?
___
*[pkg/util/jobutil/job_utils.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpYZu-4yWMT6ivg6qO:-MgpYZu02TWexyS5TjI_:b-z493kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae5f2b1ab41f3b0bbcc827b3f32b5d79da05ef5/pkg/util/jobutil/job_utils.go#L28)):*
> ```Go
> // started earlier than this one. If job is nil, CheckRunningJobsHelper just
> // checks if there are any pending, running, or paused jobs.
> func CheckRunningJobsHelper(
> ```

All makes sense, since this is a pure extraction. I'm thinking about names and wondering if this might be called `RunningJobsExist`?
___
*[pkg/util/jobutil/job_utils.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpZtPd2kl87_YhVVXJ:-MgpZtPd2kl87_YhVVXK:b-qkxssi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae5f2b1ab41f3b0bbcc827b3f32b5d79da05ef5/pkg/util/jobutil/job_utils.go#L30)):*
> ```Go
> func CheckRunningJobsHelper(
> 	ctx context.Cont [...]

2021-08-11 18:40 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/sql/compact_sql_stats.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpc0qfBtdw7vIHDKu1:-MgqPWO63IFaPdX3V1J3:bbcw9o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/compact_sql_stats.go#L54)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Maybe a comment here, because it's a little unclear to me what this line is doing. Does the literal `0` in the callback mean anything, like are we checking that the job hasn't made any progress? Or are we just using `FractionProgressed` for its error-checking capabilities, but we don't actually care about progress?
</blockquote></details>

Hmm I put it here because I saw the automatic create stats job updates the job progress in their resumer. On second thought, since as of now, the compaction job is relatively simple and runs pretty fast, I don't think we need to update the job progress just for the sake of doing so. 

I removed it for now and we can reintroduce it once we start to actually implement the compaction logic. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 69 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpdb5x5eGe8bmMXEJI:-MgqIurj-zGsk74aRKPZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L69)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Is "cnt" a common abbreviation for "count" around here? Maybe spell it out if not?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mgpdpel6y5Tg1D6Gidk:-MgqIv_Z2NKEaRLxG7rq:b-jlnklr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L87)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

This is the same `stmt` as above, did you mean to make something different happen here?
</blockquote></details>

Ah, the original `stmt` should have`AS OF SYSTEM TIME` clause. Fixed .
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 103 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpeH42Byad4X84yh1I:-MgqJ38YDhSJLweBcfoL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L103)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Kill this comment, yeah?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 106 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpeUJ26R8czA6UYrJJ:-MgqJ3s5D_1xQfB3sxM_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L106)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Ditto, same `stmt` as above.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpefhfAAE0LO-9MvQH:-MgqJR_c-lgb_2XV0mqN:b-lgnu0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L138)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Maybe an explicit `ASC` here? I get nervous deleting things, lol.
</blockquote></details>

Ah sounds good :+1:
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgphqZcBYrtSyN1P4Eg:-MgqJo301qgMA4Aw3lMT:b-xcnp1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b8342d0df54f4634affec19a708aaa5fa425e53/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L54)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Just curious, what does this `stopper` stop? I don't see it used below. Does it look for magic stuff in the `ctx`?
</blockquote></details>

Ah this is definitely redundant. Removed. 
___
*[pkg/util/jobutil/job_utils.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpYZu-4yWMT6ivg6qO:-MgqKZSC09CEqMbaqcSx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae5f2b1ab41f3b0bbcc827b3f32b5d79da05ef5/pkg/util/jobutil/job_utils.go#L28)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

All makes sense, since this is a pure extraction. I'm thinking about names and wondering if this might be called `RunningJobsExist`?
</blockquote></details>

Done.
___
*[pkg/util/jobutil/job_utils.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgpZtPd2kl87_YhVVXJ:-MgqLfDK9lCWHJl2io46:b-bzo3b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae5f2b1ab41f3b0bbcc827b3f32b5d79da05ef5/pkg/util/jobutil/job_utils.go#L30)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Would it make sense to just pass the `JobID` here? Or could it be integrated into the filter somehow?
</blockquote></details>

The behavior of the function when `job` is nil is different when the `job` is not nil. If `job` is nil, then this function just check if there are **any** other **running** job that matches the predicate. If the `job` is not nil, the function checks if the provided `job`'s jobID is the earliest **running** job that's created. 

Updated the comment to highlight that. 


<!-- Sent from Reviewable.io -->

2021-08-11 20:03 UTC, matthewtodd approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 18 of 18 files at r3, 10 of 16 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-MgqnpVM-Pw3rKecteFE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)



<!-- Sent from Reviewable.io -->

2021-08-11 20:25 UTC, ajwerner reviewed
Nice job navigating the jobs boilerplate.

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/compact_sql_stats.go
> +	*jobs.Job
Is this embedding buying you anything?

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	c.TestingKnobs.DisableFollowerRead = disallowFollowerRead
It's not often that you see non-testing code setting a `TestingKnob` value. Is the idea that your test is going to verify that the boolean made it through to here? If so, use a callback.

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +func (c *StatsCompactor) Init(
Why `Init` and not just `NewStatsCompactor` so you don't need to stress about whether or not it has been initialized?

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	stmt := `
nit: const

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	err := c.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
I think this can all be `return c.db.Txn(ctx, ...`

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go
> +	return nil
total nit: I might write this

```
if err == nil && exists {
    err = ErrConcurrentSQLStatsCompaction
}
return err

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
> +	firstSQLConn.Exec(t, fmt.Sprintf("SET CLUSTER SETTING sql.stats.persisted_rows.max = %d", maxPersistedRowLimit))
nit: you can pass the value to `Exec` like: 

```go
firstSQLConn.Exec(t, "SET CLUSTER SETTING sql.stats.persisted_rows.max = $1", maxPersistedRowLimit)
```

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
> +	expectedDeletedStmtFingerprints, expectedDeletedTxnFingerprints := getTopSortedFingerprints(t, firstSQLConn, maxPersistedRowLimit)
nit: wrap some long lines

2021-08-11 20:25 UTC, ajwerner commented on pkg/util/jobutil/job_utils.go
> +		jobs.StatusPaused,
I think you want more than just this. Reverting, PauseRequested, CancelRequested. See `jobs.NonTerminalStatusTupleString`.

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	// StatsCompactor. This is used because follower can cause problems in
nit: "because follower **reads**"

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	// possible in real life.
I like the "real life" commentary but perhaps "outside of testing" would be better.

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
> +	c.TestingKnobs.DisableFollowerRead = disallowFollowerRead
After reading more, I think it's that you're trying to tell the compactor to disallow follower reads. But, like, that knob is not going to change throughout the life of the cluster so this seems a little funky. Instead just inject the testing knobs in the appropriate places.

2021-08-11 20:25 UTC, ajwerner commented on pkg/jobs/jobspb/jobs.proto
> +  bool disable_follower_read = 1;
Do we really need this in the job details? From my reading it only comes from a testing knob which should be shared by all of the instances of the job.

2021-08-11 20:25 UTC, ajwerner commented on pkg/sql/compact_sql_stats.go
> +	r.compactionExecutor.Init(ie, db, jobDetails.DisableFollowerRead)
The code uses both `DisableFollowerReads` and `disallowFollerReads`. Can we pick one?

2021-08-11 20:25 UTC, ajwerner commented on pkg/util/jobutil/job_utils.go
> +package jobutil
I don't know that this warrants its own package. `jobs` already depends on all of this stuff. Seems fine to put this file in that package.

2021-08-11 20:25 UTC, ajwerner commented on pkg/util/jobutil/job_utils.go
> +	job *jobs.Job,
Any reason not to just pass the job ID as opposed to the job struct?

2021-08-12 14:34 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @matthewtodd)

___
*[pkg/jobs/jobspb/jobs.proto, line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuG-r5-667:-Mgukbg-CgxivA3gIb-v:b-1azeqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/jobs/jobspb/jobs.proto#L667)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do we really need this in the job details? From my reading it only comes from a testing knob which should be shared by all of the instances of the job. 
</blockquote></details>

Removed. Added package-level variable `disableFollowerReadForTest` instead of passing it through protobuf.
___
*[pkg/sql/compact_sql_stats.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuI-r5-25:-MguksMk4xb0xdnN65Hq:b-vgdvo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/compact_sql_stats.go#L25)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this embedding buying you anything? 
</blockquote></details>

Not really. Removed the embedding. 
___
*[pkg/sql/compact_sql_stats.go, line 52 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuI-r5-52:-Mguku_XC4lM7Fzn3p3M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/compact_sql_stats.go#L52)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The code uses both `DisableFollowerReads` and `disallowFollerReads`. Can we pick one?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuJ-r5-46:-MgulA9LDWmU2add_QTM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L46)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I like the "real life" commentary but perhaps "outside of testing" would be better. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 55 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuJ-r5-55:-MgulBAU1SyAYvupT035:bfxlb9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L55)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Why `Init` and not just `NewStatsCompactor` so you don't need to stress about whether or not it has been initialized?
</blockquote></details>

I was under the wrong impression that all the fields in the `Resumer` need to be initialized before `Resume()` is called. 

Removed `Init` and replace it with `NewStatsCompactor`
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 64 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuJ-r5-64:-MgulVSHC0Fu4OiuUZVg:bquwd2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L64)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

After reading more, I think it's that you're trying to tell the compactor to disallow follower reads. But, like, that knob is not going to change throughout the life of the cluster so this seems a little funky. Instead just inject the testing knobs in the appropriate places.
</blockquote></details>

Replaced it with a package level private variable. Since other parts of the `persistedsqlstats` will eventually start using follower read and having one package level private variable can just disable all the follower reads in the package. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 148 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuJ-r5-148:-Mguc2L1CGKaMfCesA9b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L148)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this can all be `return c.db.Txn(ctx, ...`
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTR10m5UZAUk3hD-r5-79:-MgucBNw3dcpCKg-xb27:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go#L79)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

total nit: I might write this

```
if err == nil && exists {
    err = ErrConcurrentSQLStatsCompaction
}
return err
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 68 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTR10m5UZAUk3hE-r5-68:-MgucJck04OW4ep56Xu7:b2nhoia) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L68)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: you can pass the value to `Exec` like: 

```go
firstSQLConn.Exec(t, "SET CLUSTER SETTING sql.stats.persisted_rows.max = $1", maxPersistedRowLimit)
```
</blockquote></details>

TIL
___
*[pkg/util/jobutil/job_utils.go, line 11 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuE-r5-11:-MguhNS_Cpkm6k33aQvQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/util/jobutil/job_utils.go#L11)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't know that this warrants its own package. `jobs` already depends on all of this stuff. Seems fine to put this file in that package. 
</blockquote></details>

Done.
___
*[pkg/util/jobutil/job_utils.go, line 32 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuE-r5-32:-Mguipal8qujkQMjufnn:bv2ud5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/util/jobutil/job_utils.go#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Any reason not to just pass the job ID as opposed to the job struct? 
</blockquote></details>

Replaced with job ID.
___
*[pkg/util/jobutil/job_utils.go, line 57 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuE-r5-57:-MgukaSi4J_pDo0mp6PJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/util/jobutil/job_utils.go#L57)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think you want more than just this. Reverting, PauseRequested, CancelRequested. See `jobs.NonTerminalStatusTupleString`. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-12 15:05 UTC, ajwerner reviewed
> Reviewed 6 of 19 files at r6, 2 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, and @matthewtodd)

___
*[pkg/jobs/jobspb/jobs.proto, line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuG-r5-667:-MguqpcU4xTxoJpAfFdS:b-yr3q56) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/jobs/jobspb/jobs.proto#L667)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Removed. Added package-level variable `disableFollowerReadForTest` instead of passing it through protobuf.
</blockquote></details>

huh, I don't think that's better. Don't you have access to testing knobs everywhere that you'd need it?
___
*[pkg/sql/create_stats.go, line 651 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgurHus1gx4rMODPoCp:-MgurHus1gx4rMODPoCq:b-95h2bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b62d572203226cecc2d85d6ac4ebc5947f6fb6/pkg/sql/create_stats.go#L651)):*
> ```Go
> 	}
> 
> 	return nil /* retErr */
> ```

you've removed `retErr`
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 34 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgutGpYBTcO6ZZJQo_E:-MgutGpYBTcO6ZZJQo_F:b-9a0fk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3896644452d32116bf470ed891c5b0ee8bcef0d/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L34)):*
> ```Go
> 	ie sqlutil.InternalExecutor
> 
> 	TestingKnobs *StatsCompactorTestingKnobs
> ```

this thing should get passed to NewStatsCompactor and then should exist in the top-level TestingKnobs
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 107 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgurbkJ6feTYvuIXSD8:-MgurbkK3Lh5k4aWUzdD:b-iaecc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3896644452d32116bf470ed891c5b0ee8bcef0d/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L107)):*
> ```Go
> 
> 	if row.Len() != 1 {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, errors.AssertionFailedf("unexpected number of column returned")
> ```

not that it matters but, if you're going to use `AssertionFailedf` maybe report the number of columns?
___
*[pkg/jobs/utils.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mguq_RiDBraQi7KepAI:-Mguq_RjCI3b-a59vF44:b-vous1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b62d572203226cecc2d85d6ac4ebc5947f6fb6/pkg/jobs/utils.go#L39)):*
> ```Go
>   system.jobs
> WHERE
>   status IN ($1, $2, $3, $4, $5, $6)
> ```

you can literally just do the following and lose the args

```
  status IN ` + NonTerminalStatusTupleString +`
```


<!-- Sent from Reviewable.io -->

2021-08-12 15:31 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @Azhng, and @matthewtodd)

___
*[pkg/jobs/jobspb/jobs.proto, line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuG-r5-667:-Mguy-qv74embZ3S4ZMx:bdqzlg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/jobs/jobspb/jobs.proto#L667)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

huh, I don't think that's better. Don't you have access to testing knobs everywhere that you'd need it?
</blockquote></details>

Since the `resumer` creates the `StatsCompactor`,  and the `resumer`'s constructor is registered in `func init()`, I'm not entirely sure how I can inject testing knobs into the resumer? (Since it's privately scoped into the `sql` package because it depends on `JobExecContext`). Any ideas here? 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 107 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgurbkJ6feTYvuIXSD8:-MguxvLAAz8qIs0O-fuN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3896644452d32116bf470ed891c5b0ee8bcef0d/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L107)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

not that it matters but, if you're going to use `AssertionFailedf` maybe report the number of columns?
</blockquote></details>

Done.
___
*[pkg/jobs/utils.go, line 39 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mguq_RiDBraQi7KepAI:-MguwZJdAc61KcnxTIHR:b-12ssyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b62d572203226cecc2d85d6ac4ebc5947f6fb6/pkg/jobs/utils.go#L39)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you can literally just do the following and lose the args

```
  status IN ` + NonTerminalStatusTupleString +`
```
</blockquote></details>

For some reason I thought `NonTerminalStatusTupleString` doesn't have `StatusRunning` and `StatusPaused`. :man_facepalming: 


<!-- Sent from Reviewable.io -->

2021-08-13 19:00 UTC, arulajmani reviewed
> Reviewed 1 of 19 files at r6, 18 of 18 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @Azhng)

___
*[pkg/sql/create_stats.go, line 635 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mh-sL4z-Iw3FG8JkSAx:-Mh-sL5-1pFIFubpA5Dq:biz4m7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6728104aae02a66471e7cb5f0459aeac467898a1/pkg/sql/create_stats.go#L635)):*
> ```Go
> // just checks if there are any pending, running, or paused CreateStats jobs.
> func checkRunningJobs(ctx context.Context, job *jobs.Job, p JobExecContext) error {
> 	var jobID jobspb.JobID
> ```

nit: s/var jobID jobspb.ID/jobID := jobspb.InvalidJobID
___
*[pkg/jobs/utils.go, line 25 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mh-rd6H2dHqWUv5Gh-z:-Mh-rd6I5Xo2D9-fulwV:b-iz2hzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6728104aae02a66471e7cb5f0459aeac467898a1/pkg/jobs/utils.go#L25)):*
> ```Go
> // RunningJobExists checks that whether there are any other jobs (matched by
> // payloadPredicate callback) in the pending, running, or paused status that
> // started earlier than the job with provided jobID.
> ```

Drive by comment -- briefly looking at this code, it seems like this is intended to work even when the jobID does not refer to a real jobID. Am I reading this right? Could you expand on your comment to talk about the case where jobID is InvalidJobID as well?


<!-- Sent from Reviewable.io -->

2021-08-16 19:50 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @Azhng)

___
*[pkg/sql/create_stats.go, line 635 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mh-sL4z-Iw3FG8JkSAx:-MhFVvkcEaKvnB99L_Bt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6728104aae02a66471e7cb5f0459aeac467898a1/pkg/sql/create_stats.go#L635)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/var jobID jobspb.ID/jobID := jobspb.InvalidJobID
</blockquote></details>

Done
___
*[pkg/jobs/utils.go, line 25 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mh-rd6H2dHqWUv5Gh-z:-MhFVoPf2zIgSyWtD2QB:bqum85s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6728104aae02a66471e7cb5f0459aeac467898a1/pkg/jobs/utils.go#L25)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Drive by comment -- briefly looking at this code, it seems like this is intended to work even when the jobID does not refer to a real jobID. Am I reading this right? Could you expand on your comment to talk about the case where jobID is InvalidJobID as well?
</blockquote></details>

Added additional explanation for the `InvalidJobID` case


<!-- Sent from Reviewable.io -->

2021-08-16 20:13 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @arulajmani)

___
*[pkg/jobs/jobspb/jobs.proto, line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgHHSTQKD2MdZ9S7WuG-r5-667:-MhFa1NG5x2R8obb1_HS:b-hgik2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/201d8109a5b5072c4897a7320e4372e61fbc584c/pkg/jobs/jobspb/jobs.proto#L667)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Since the `resumer` creates the `StatsCompactor`,  and the `resumer`'s constructor is registered in `func init()`, I'm not entirely sure how I can inject testing knobs into the resumer? (Since it's privately scoped into the `sql` package because it depends on `JobExecContext`). Any ideas here? 
</blockquote></details>

Nevermind, I can just use the testing knobs that is already in the ExecCfg(). Updated
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 34 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MgutGpYBTcO6ZZJQo_E:-MhFa6xKCMudjC_s-l6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3896644452d32116bf470ed891c5b0ee8bcef0d/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L34)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this thing should get passed to NewStatsCompactor and then should exist in the top-level TestingKnobs
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-17 13:35 UTC, Azhng commented
@ajwerner RFAL

2021-08-17 15:15 UTC, maryliag reviewed
> Reviewed 2 of 19 files at r10, 13 of 17 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @Azhng)

___
*[pkg/jobs/jobspb/jobs.proto, line 680 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJd7qp4WeNuU4lZ6uJ:-MhJd7qp4WeNuU4lZ6uK:bd6uzr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/jobs/jobspb/jobs.proto#L680)):*
> ```protobuf
> 
> message SQLStatsCompactionProgress {
> ```

nit: remove blank line
___
*[pkg/sql/compact_sql_stats.go, line 54 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJdbAGC4hoG9mmcFTD:-MhJdbAGC4hoG9mmcFTE:b-9uzj4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/sql/compact_sql_stats.go#L54)):*
> ```Go
> // OnFailOrCancel implements the jobs.Resumer interface.
> func (r *sqlStatsCompactionResumer) OnFailOrCancel(ctx context.Context, execCtx interface{}) error {
> 	return nil
> ```

what is the goal of this function if is not doing anything here?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 65 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJeTac5WBwlruDQtXR:-MhJeTac5WBwlruDQtXS:b-8guzbk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L65)):*
> ```Go
> }
> 
> func (c *StatsCompactor) getExistingStmtAndTxnStatsEntries(
> ```

nit: you're returning the count not the entries itself, maybe rename the function to reflect that
___
*[pkg/jobs/utils.go, line 27 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJcWhw5aoWND9Tgi4k:-MhJcWhx2YwCOBJN1C3n:bh0jiw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/jobs/utils.go#L27)):*
> ```Go
> // started earlier than the job with provided jobID.
> // If the provided jobID is a jobspb.InvalidJobID, this function checks if
> // there exists any jobs that matches the payloadPredicate.
> ```

nit: checks if exists any jobs...


<!-- Sent from Reviewable.io -->

2021-08-17 17:25 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @maryliag)

___
*[pkg/jobs/jobspb/jobs.proto, line 680 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJd7qp4WeNuU4lZ6uJ:-MhK70T_730_TPThYJGQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/jobs/jobspb/jobs.proto#L680)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: remove blank line
</blockquote></details>

Done.
___
*[pkg/sql/compact_sql_stats.go, line 54 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJdbAGC4hoG9mmcFTD:-MhK71XE7gS4vJlBpeF0:b-r6l4py) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/sql/compact_sql_stats.go#L54)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

what is the goal of this function if is not doing anything here?
</blockquote></details>

It's to implement part of the `jobs.Resumer` interface. Currently this is noop because the job itself right now is almost atomic and fast to run. This will be used later in the next PR to update the scheduled state for the scheduled job. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 65 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJeTac5WBwlruDQtXR:-MhK7jG1D7_sToydTfsS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L65)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you're returning the count not the entries itself, maybe rename the function to reflect that
</blockquote></details>

Done.
___
*[pkg/jobs/utils.go, line 27 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhJcWhw5aoWND9Tgi4k:-MhK6vOtB2GJWkcLxu__:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea43c8630763e7503ca535753f9c14f3b533372c/pkg/jobs/utils.go#L27)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: checks if exists any jobs...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-18 13:25 UTC, ajwerner reviewed
Nice, just minor stuff from me.

> Reviewed 1 of 18 files at r14, 10 of 17 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-MhL4oOO4Ix3N4gE41IH:bb85xjp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @Azhng, and @maryliag)

___
*[pkg/sql/compact_sql_stats.go, line 43 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOO-Em7tmqtpUmLwKy:-MhOO-Em7tmqtpUmLwKz:bw702if) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/compact_sql_stats.go#L43)):*
> ```
> 			return nil
> ```
Should we return an error here to indicate that we didn't actually compact? 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 65 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOOucM0HstZlbEFkkx:-MhOOucM0HstZlbEFkky:b-nyveo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L65)):*
> ```Go
> }
> 
> func (c *StatsCompactor) getExistingStmtAndTxnStatsCount(
> ```

it's interesting that we're going to get the counts that drive our delete query using historical reads. I suspect it's part of the design, but it's still interesting and feels like it deserves commentary.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOQbS83O14aARslJ98:-MhOQbS83O14aARslJ99:b-988hdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L84)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 	row, err := c.ie.QueryRowEx(ctx,
> 		"scan-sql-stmt-stats-entries",
> 		nil,
> 		sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 		stmt)
> 	if err != nil {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
> 	}
> 	if row.Len() != 1 {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, errors.AssertionFailedf("unexpected number of column returned")
> 	}
> 	stmtStatsEntryCount = int64(tree.MustBeDInt(row[0]))
> ```
</details>

factor out a closure to that takes a stmt and returns an `int64, error`. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 124 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOPRxTB6q5O0ap2n5S:-MhOPRxTB6q5O0ap2n5T:bx7jj7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L124)):*
> ```Go
> )
> `
> ```

Are we interested in metric counters on how many of these things we've actually removed?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 147 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOP_WgC9ML0mxOWYcY:-MhOP_WgC9ML0mxOWYcZ:bannq7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L147)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>

> ```
> 		if entriesToRemove := curStmtStatsEntries - maxStatsEntry; entriesToRemove > 0 {
> 			_, err := c.ie.ExecEx(ctx,
> 				"delete-old-stmt-stats",
> 				txn,
> 				sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 				fmt.Sprintf(stmt,
> 					"system.statement_statistics",
> 					"aggregated_ts, fingerprint_id, plan_hash, app_name, node_id",
> 					entriesToRemove))
> 			if err != nil {
> 				return err
> 			}
> 		}
> 		if entriesToRemove := curTxnStatsEntries - maxStatsEntry; entriesToRemove > 0 {
> 			_, err := c.ie.ExecEx(ctx,
> 				"delete-old-txn-stats",
> 				txn,
> 				sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 				fmt.Sprintf(stmt,
> 					"system.transaction_statistics",
> 					"aggregated_ts, fingerprint_id, app_name, node_id",
> 					entriesToRemove))
> 			if err != nil {
> 				return err
> 			}
> 		}
> ```
</details>

my sense is that you can make some closures to clean this up a bit. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 161 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOMDJB2UmQCjTsaxfn:-MhOMDJB2UmQCjTsaxfo:b-1dh10v) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L161)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 	// We wait until the job appears in the system.jobs table.
> 	testutils.SucceedsSoon(t, func() error {
> 		server.JobRegistry().(*jobs.Registry).TestingNudgeAdoptionQueue()
> 		var cnt uint64
> 		row := conn.QueryRow(`SELECT count(*) FROM system.jobs where id = $1`, jobID)
> 		require.NoError(t, row.Scan(&cnt))
> 		if cnt == 0 {
> 			return errors.New("retry")
> 		}
> 		return nil
> 	})
> ```
</details>

do you know about `sqlutils.MakeSQLRunner`? This could be:

```
sqlutils.MakeSQLRunner(conn).CheckQueryResultsRetry(
    t, 
    fmt.Sprintf(`SELECT count(*) FROM system.jobs where id = %d`, jobID), 
    [][]string{{"1"}},
)
```

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 271 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOQIGq8FTQtKfX7zmK:-MhOQIGq8FTQtKfX7zmL:b-p4o3oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L271)):*
> ```Go
> 
> func createStatsRequestFilter(
> 	t *testing.T, allowToProgress *chan struct{},
> ```

I don't see an obvious reason for this chan to be a pointer. You don't seem to ever swap anything into it. 
___
*[pkg/jobs/utils.go, line 28 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhONbei-8EivDW_zayW:-MhONbei-8EivDW_zayX:b-ixdy2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/jobs/utils.go#L28)):*
> ```Go
> // If the provided jobID is a jobspb.InvalidJobID, this function checks if
> // exists any jobs that matches the payloadPredicate.
> func RunningJobExists(
> ```

Would https://github.com/cockroachdb/cockroach/issues/68896 make you happy? I think it would make me happy. Maybe I'll do it. 


<!-- Sent from Reviewable.io -->

2021-08-23 17:51 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @maryliag)

___
*[pkg/sql/compact_sql_stats.go, line 43 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOO-Em7tmqtpUmLwKy:-MhnZWvi2oD0pYWyaPZ5:bjazogh) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/compact_sql_stats.go#L43)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			return nil
> ```
Should we return an error here to indicate that we didn't actually compact? 
</blockquote></details>

Good point. Returning errors.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 65 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOOucM0HstZlbEFkkx:-Mhn_Adw4P4lse1wT3Is:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it's interesting that we're going to get the counts that drive our delete query using historical reads. I suspect it's part of the design, but it's still interesting and feels like it deserves commentary.
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 84 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOQbS83O14aARslJ98:-MhniS-A-SWE_6hRDhdU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L84)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	row, err := c.ie.QueryRowEx(ctx,
> 		"scan-sql-stmt-stats-entries",
> 		nil,
> 		sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 		stmt)
> 	if err != nil {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
> 	}
> 	if row.Len() != 1 {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, errors.AssertionFailedf("unexpected number of column returned")
> 	}
> 	stmtStatsEntryCount = int64(tree.MustBeDInt(row[0]))
> ```
factor out a closure to that takes a stmt and returns an `int64, error`. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 124 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOPRxTB6q5O0ap2n5S:-Mho7I9r0qfVCew7LkuH:bn4f2dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L124)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Are we interested in metric counters on how many of these things we've actually removed?
</blockquote></details>

Done. Introduced a counter.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 147 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOP_WgC9ML0mxOWYcY:-Mhnm8NF9gvsOb4MjM63:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L147)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		if entriesToRemove := curStmtStatsEntries - maxStatsEntry; entriesToRemove > 0 {
> 			_, err := c.ie.ExecEx(ctx,
> 				"delete-old-stmt-stats",
> 				txn,
> 				sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 				fmt.Sprintf(stmt,
> 					"system.statement_statistics",
> 					"aggregated_ts, fingerprint_id, plan_hash, app_name, node_id",
> 					entriesToRemove))
> 			if err != nil {
> 				return err
> 			}
> 		}
> 		if entriesToRemove := curTxnStatsEntries - maxStatsEntry; entriesToRemove > 0 {
> 			_, err := c.ie.ExecEx(ctx,
> 				"delete-old-txn-stats",
> 				txn,
> 				sessiondata.InternalExecutorOverride{User: security.NodeUserName()},
> 				fmt.Sprintf(stmt,
> 					"system.transaction_statistics",
> 					"aggregated_ts, fingerprint_id, app_name, node_id",
> 					entriesToRemove))
> 			if err != nil {
> 				return err
> 			}
> 		}
> ```
my sense is that you can make some closures to clean this up a bit. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 161 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOMDJB2UmQCjTsaxfn:-Mhnoey37Xtbip5cpeNE:b-qqvaq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L161)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// We wait until the job appears in the system.jobs table.
> 	testutils.SucceedsSoon(t, func() error {
> 		server.JobRegistry().(*jobs.Registry).TestingNudgeAdoptionQueue()
> 		var cnt uint64
> 		row := conn.QueryRow(`SELECT count(*) FROM system.jobs where id = $1`, jobID)
> 		require.NoError(t, row.Scan(&cnt))
> 		if cnt == 0 {
> 			return errors.New("retry")
> 		}
> 		return nil
> 	})
> ```
do you know about `sqlutils.MakeSQLRunner`? This could be:

```
sqlutils.MakeSQLRunner(conn).CheckQueryResultsRetry(
    t, 
    fmt.Sprintf(`SELECT count(*) FROM system.jobs where id = %d`, jobID), 
    [][]string{{"1"}},
)

</blockquote></details>

Done. TIL. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_test.go, line 271 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhOQIGq8FTQtKfX7zmK:-MhnpodYCeYDIQ6fM9Bl:bj4j402) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L271)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't see an obvious reason for this chan to be a pointer. You don't seem to ever swap anything into it. 
</blockquote></details>

Good point. Fixed. 
___
*[pkg/jobs/utils.go, line 28 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhONbei-8EivDW_zayW:-MhnZFw6CUgdeV4AfGgl:bhi05d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/11aac5f1b9f90e0aa96b6ffdf54d75e73aff2113/pkg/jobs/utils.go#L28)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would https://github.com/cockroachdb/cockroach/issues/68896 make you happy? I think it would make me happy. Maybe I'll do it. 
</blockquote></details>

Ah nice, this would definitely be great! 


<!-- Sent from Reviewable.io -->

2021-08-23 18:09 UTC, ajwerner reviewed
> Reviewed 1 of 18 files at r16, 3 of 19 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 79 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9Ryy807IOXQ-MczU:-Mho9Ryy807IOXQ-MczV:b7ysubd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L79)):*
> ```Go
> func (c *StatsCompactor) getExistingStmtAndTxnStatsCount(
> 	ctx context.Context,
> ) (stmtStatsEntryCount, txnStatsEntryCount int64, err error) {
> ```

nit: don't name this error, it can get you in trouble. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 80 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9c076P1p1IZdYwIr:-Mho9c076P1p1IZdYwIs:b-8w0a0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L80)):*
> ```Go
> 	ctx context.Context,
> ) (stmtStatsEntryCount, txnStatsEntryCount int64, err error) {
> 	getRowCount := func(ctx context.Context, opName string, stmt string) (int64, error) {
> ```

nit: you could pass in the pointer and simplify things a tad. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 106 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9Gjw0NQBOiF1L367:-Mho9GjxE8_r4P640MpB:b1rhtit) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L106)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
> 	stmt := "SELECT count(*) FROM system.statement_statistics AS OF SYSTEM TIME follower_read_timestamp()"
> 	if c.knobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.statement_statistics"
> 	}
> 	stmtStatsEntryCount, err = getRowCount(ctx, "scan-sql-stmt-stats-entries", stmt)
> 	if err != nil {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
> 	}
> 	stmt = "SELECT count(*) FROM system.transaction_statistics AS OF SYSTEM TIME follower_read_timestamp()"
> 	if c.knobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.transaction_statistics"
> 	}
> 	txnStatsEntryCount, err = getRowCount(ctx, "scan-sql-txn-stats-entries", stmt)
> ```
</details>

nit: put these in separate blocks:

```
{
	stmt := "SELECT count(*) FROM system.statement_statistics AS OF SYSTEM TIME follower_read_timestamp()"
	if c.knobs.DisableFollowerRead {
		stmt = "SELECT count(*) FROM system.statement_statistics"
	}
	stmtStatsEntryCount, err = getRowCount(ctx, "scan-sql-stmt-stats-entries", stmt)
	if err != nil {
		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
	}
}
{
	stmt = "SELECT count(*) FROM system.transaction_statistics AS OF SYSTEM TIME follower_read_timestamp()"
	if c.knobs.DisableFollowerRead {
		stmt = "SELECT count(*) FROM system.transaction_statistics"
	}
	txnStatsEntryCount, err = getRowCount(ctx, "scan-sql-txn-stats-entries", stmt)
        if err != nil 
}
```

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 113 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9PBr8YDCXdTcbCfr:-Mho9PBr8YDCXdTcbCfs:bfldmlu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L113)):*
> ```Go
> 	}
> 
> 	txnStatsEntryCount, err = getRowCount(ctx, "scan-sql-txn-stats-entries", stmt)
> ```

you weren't returning this error. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 118 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhoBJPe9j7RjgV8e4Iu:-MhoBJPe9j7RjgV8e4Iv:bj3p6b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L118)):*
> ```Go
> }
> 
> func (c *StatsCompactor) deleteOldestEntries(
> ```

I feel like the intention behind this pattern does not match reality. Namely, you're providing a number of rows to delete with the idea that you're going to not contend with foreground writes. The logic there would be sound if it weren't for the hash sharded index. The problem is that we're going to end up scanning the number of entries from each shard and we'll have to do a merge join to take the top k. I think what you want is to break this down and find the number of entries to delete on a per-shard basis. Somewhere you should export the shard count and then do this query for each shard specifying the shard column explicitly.

I encourage you to take a look at the query plan and see what the limit pushdown looks like. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 140 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhoAgP36zmoJHM9BIjZ:-MhoAgP36zmoJHM9BIj_:b-g5sjzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L140)):*
> ```Go
> 		txn *kv.Txn,
> 		stmt string,
> 		curRowsCount int64) error {
> ```

nit: wrap this like:

```
	removeRows := func(
		ctx context.Context,
		opName string,
		txn *kv.Txn,
		stmt string,
		curRowsCount int64,
        ) error {
```


<!-- Sent from Reviewable.io -->

2021-08-23 19:54 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 79 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9Ryy807IOXQ-MczU:-MhoT24N9RZUxOA_cp3Z:bfwlwal) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L79)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: don't name this error, it can get you in trouble. 
</blockquote></details>

Done. Is it because of the concern for shadowing variables? 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 80 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9c076P1p1IZdYwIr:-MhoZWas3L7j9nrRIhFP:b-7z1sta) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: you could pass in the pointer and simplify things a tad. 
</blockquote></details>

Hmm I'm not exactly sure what the "pointer" is referring to here. Do you mind clarify? 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 106 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9Gjw0NQBOiF1L367:-MhoTmkrEZjVI6d8Fvqe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	stmt := "SELECT count(*) FROM system.statement_statistics AS OF SYSTEM TIME follower_read_timestamp()"
> 	if c.knobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.statement_statistics"
> 	}
> 	stmtStatsEntryCount, err = getRowCount(ctx, "scan-sql-stmt-stats-entries", stmt)
> 	if err != nil {
> 		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
> 	}
> 	stmt = "SELECT count(*) FROM system.transaction_statistics AS OF SYSTEM TIME follower_read_timestamp()"
> 	if c.knobs.DisableFollowerRead {
> 		stmt = "SELECT count(*) FROM system.transaction_statistics"
> 	}
> 	txnStatsEntryCount, err = getRowCount(ctx, "scan-sql-txn-stats-entries", stmt)
> ```
nit: put these in separate blocks:

```
{
	stmt := "SELECT count(*) FROM system.statement_statistics AS OF SYSTEM TIME follower_read_timestamp()"
	if c.knobs.DisableFollowerRead {
		stmt = "SELECT count(*) FROM system.statement_statistics"
	}
	stmtStatsEntryCount, err = getRowCount(ctx, "scan-sql-stmt-stats-entries", stmt)
	if err != nil {
		return 0 /* stmtStatsEntryCount */, 0 /* txnStatsEntryCount */, err
	}
}
{
	stmt = "SELECT count(*) FROM system.transaction_statistics AS OF SYSTEM TIME follower_read_timestamp()"
	if c.knobs.DisableFollowerRead {
		stmt = "SELECT count(*) FROM system.transaction_statistics"
	}
	txnStatsEntryCount, err = getRowCount(ctx, "scan-sql-txn-stats-entries", stmt)
        if err != nil 
}
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 113 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9PBr8YDCXdTcbCfr:-MhoTvRf2MzXa2qPuKM3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L113)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you weren't returning this error. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 118 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhoBJPe9j7RjgV8e4Iu:-MhoTw4W-_S7xvxgG-ej:bkca99l) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L118)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel like the intention behind this pattern does not match reality. Namely, you're providing a number of rows to delete with the idea that you're going to not contend with foreground writes. The logic there would be sound if it weren't for the hash sharded index. The problem is that we're going to end up scanning the number of entries from each shard and we'll have to do a merge join to take the top k. I think what you want is to break this down and find the number of entries to delete on a per-shard basis. Somewhere you should export the shard count and then do this query for each shard specifying the shard column explicitly.

I encourage you to take a look at the query plan and see what the limit pushdown looks like. 
</blockquote></details>

I see. That makes sense. Changed the code to clean up on per-shard basis. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 140 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhoAgP36zmoJHM9BIjZ:-MhoZPgvEjA97uUH6A6Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L140)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: wrap this like:

```
	removeRows := func(
		ctx context.Context,
		opName string,
		txn *kv.Txn,
		stmt string,
		curRowsCount int64,
        ) error {
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-23 20:24 UTC, ajwerner reviewed
Here's more feedback. Some of it would eliminate the need for other parts of it (like if you broke out the logic per shard, then you definitely don't need the array). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-Mhoflq4B9jAtKHSTXD2:b53s3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 79 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9Ryy807IOXQ-MczU:-MhobbBp0MOHKlbPMWp9:b-z0x7td) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L79)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done. Is it because of the concern for shadowing variables? 
</blockquote></details>

Partially, also so that you can get `unused variable` checking. Like consider the case below where you assigned to `err` but then returned `nil`. The linter didn't catch that. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 80 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mho9c076P1p1IZdYwIr:-MhobmAg9lrlmFi9wkHe:bqstvdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2397132670a7b41e242da5574080e344432680df/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L80)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I'm not exactly sure what the "pointer" is referring to here. Do you mind clarify? 
</blockquote></details>

like, you could pass in a `*int64` and only return an error from this function. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 99 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhockgI1bkwkWIoyWpy:-MhockgJ44XWSQ0iMlv9:bh5e5uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L99)):*
> ```Go
> 	ctx context.Context, opName, tableName, hashColumnName string,
> ) ([]int64, error) {
> 	rowCountPerShard := make([]int64, systemschema.SQLStatsHashShardBucketCount)
> ```

you could use arrays everywhere given this is a constant. Consider:

```go
const shards = systemschema.SQLStatsHashShardBucketCount

func (c *StatsCompactor) getRowCountPerShard(
	ctx context.Context, opName, tableName, hashColumnName string,
) ([shards]int64, error) {
```

and then pass these arrays everywhere. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 116 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhod0BtC8LfwI2Jyam-:-Mhod0BtC8LfwI2Jyam0:bh6z60s) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L116)):*
> ```Go
> 	}
> 
> 	stmt = fmt.Sprintf(stmt, tableName, hashColumnName)
> ```

nit: if you're going to be formatting this anyway, you could just add the follower read clause as another parameter.

```go
stmt = `SELECT count(*) FROM %[1]s WHERE %[2]s = $1%[3]s`
followerReadClause := ` AS OF SYSTEM TIME follower_read_timestamp()`
if c.knobs.DisableFollowerRead {
   followerReadClause = ""
}
stmt = fmt.Sprintf(stmt, tableName, hashColumnName, followerReadClause)
```
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 136 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhodcDOAvWCqjzwlrXs:-MhodcDOAvWCqjzwlrXt:b-rstoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L136)):*
> ```Go
> func (c *StatsCompactor) getExistingStmtAndTxnStatsCount(
> 	ctx context.Context,
> ) ([]int64, []int64, error) {
> ```

I'd name the counts, just `_` for the error. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 188 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhoe5P76IlBR_UH1o62:-Mhoe5P846XUprVQutWU:b2nnj4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L188)):*
> ```Go
> 		} else {
> 			limitPerShard[shardIdx] = maxStatsEntryPerShard
> 		}
> ```

there's a nice trick here I learned once. You can just keep subtracting and dividing and it will all work out nicely:

```go
	limitPerShard := make([]int64, systemschema.SQLStatsHashShardBucketCount)
	maxPersistedRows := SQLStatsMaxPersistedRows.Get(&c.st.SV)
        for i := 0; i < shards; i++ {
            limitsPerShard[i] = maxPersistedRows / (shards - i)
            maxPersistedRows -= limitsPerShard[i]
        }
```
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 195 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhofc6s0ylZIk_rvCXw:-Mhofc6s0ylZIk_rvCXx:bx2tk8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L195)):*
> ```Go
> 
> func (c *StatsCompactor) deleteOldestEntries(
> 	ctx context.Context, stmtStatsRowCountPerShard, txnStatsRowCountPerShard []int64,
> ```

how crazy would it be to pick a timestamp below which you'll be deleting stuff as opposed to picking what amounts to an offset?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 242 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhofF7p1R-unlYonlwT:-MhofF7p1R-unlYonlwU:bqi32x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L242)):*
> ```Go
> 	}
> 
> 	return c.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> ```

I'm anxious about the size of this transaction. Large transactions in cockroach are known for having a bad time. Particularly large deletes which might overlap with foreground traffic. I would:

1) break this transaction out per shard. I think that'll also simplify some of the logic in this file.
2) Put a limit on the number of rows we're willing to delete in a single transaction and then add a loop. 


<!-- Sent from Reviewable.io -->

2021-08-23 22:11 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 99 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhockgI1bkwkWIoyWpy:-Mhp21b98KvFPJ9tZ-9a:b-l56v0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L99)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you could use arrays everywhere given this is a constant. Consider:

```go
const shards = systemschema.SQLStatsHashShardBucketCount

func (c *StatsCompactor) getRowCountPerShard(
	ctx context.Context, opName, tableName, hashColumnName string,
) ([shards]int64, error) {
```

and then pass these arrays everywhere. 
</blockquote></details>

Opted to refactor to implement the logic per shard.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 116 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhod0BtC8LfwI2Jyam-:-Mhojnf3-siI5AP-_VSi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L116)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: if you're going to be formatting this anyway, you could just add the follower read clause as another parameter.

```go
stmt = `SELECT count(*) FROM %[1]s WHERE %[2]s = $1%[3]s`
followerReadClause := ` AS OF SYSTEM TIME follower_read_timestamp()`
if c.knobs.DisableFollowerRead {
   followerReadClause = ""
}
stmt = fmt.Sprintf(stmt, tableName, hashColumnName, followerReadClause)
```
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 136 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhodcDOAvWCqjzwlrXs:-Mhp26-W37JV50cHbYcE:b-8jf3ot) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L136)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'd name the counts, just `_` for the error. 
</blockquote></details>

Opted to implement the logic per shard.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 188 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhoe5P76IlBR_UH1o62:-Mhp1RlB7VLT3XCiAF2w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L188)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

there's a nice trick here I learned once. You can just keep subtracting and dividing and it will all work out nicely:

```go
	limitPerShard := make([]int64, systemschema.SQLStatsHashShardBucketCount)
	maxPersistedRows := SQLStatsMaxPersistedRows.Get(&c.st.SV)
        for i := 0; i < shards; i++ {
            limitsPerShard[i] = maxPersistedRows / (shards - i)
            maxPersistedRows -= limitsPerShard[i]
        }
```


</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 195 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhofc6s0ylZIk_rvCXw:-Mhp2OwI3wMHFyJE-HoU:bjl469m) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L195)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how crazy would it be to pick a timestamp below which you'll be deleting stuff as opposed to picking what amounts to an offset?
</blockquote></details>

I don't quite follow here. Are we talking about the timestamp of the transaction ? 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 242 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-MhofF7p1R-unlYonlwT:-Mhp1TrEDrg4cSwKQwm5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L242)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm anxious about the size of this transaction. Large transactions in cockroach are known for having a bad time. Particularly large deletes which might overlap with foreground traffic. I would:

1) break this transaction out per shard. I think that'll also simplify some of the logic in this file.
2) Put a limit on the number of rows we're willing to delete in a single transaction and then add a loop. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-23 22:32 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-Mhp8Bxx0jrzyem0RM1C:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 195 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhofc6s0ylZIk_rvCXw:-Mhp66CN-dY12fFWR8dx:b-eqex1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L195)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I don't quite follow here. Are we talking about the timestamp of the transaction ? 
</blockquote></details>

It's not important; what you have here is fine.

What I was thinking is that right now you go and find the number of rows in the shard and then you find the number you think should be in the shard and you delete until you think you've deleted enough. Another approach would be to find the `aggregated_ts` of the newest row you want to delete and use that drive the deletions here.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 33 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp86dA51yS7tewIy-g:-Mhp86dA51yS7tewIy-h:b-nzemta) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L33)):*
> ```Go
> const maxDeleteRowsPerTxn = 128
> 
> // StatsCompactor is responsible for compacting older SQL Stats. It is
> ```

my last nit is that this thing doesn't really compact, it just deletes. Is compaction future work?
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 89 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp7n1j2GXmxG3m8KkK:-Mhp7n1k8xqs0KaOWRat:b-hpegfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L89)):*
> ```Go
> 	deleteOldStatsStmt := c.getStatementForDeletingStaleRows(tableName, pkColumnNames, hashColumnName)
> 
> 	for shardIdx := int64(0); shardIdx < systemschema.SQLStatsHashShardBucketCount; shardIdx++ {
> ```

nit: for `shard, limit := range limitPerShard`, I don't think that the `int64` nature of the shard is important for your function signatures. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 169 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp6bq89xDvSxSuHQt7:-Mhp6bq89xDvSxSuHQt8:b-xs3u1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L169)):*
> ```Go
> 			}
> 			if err := c.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 				_, err := c.ie.ExecEx(ctx,
> ```

fun fact, if you pass a `nil` for the `txn` the internal executor will deal with the transaction management for you. I encourage you to do that here. 


<!-- Sent from Reviewable.io -->

2021-08-23 22:43 UTC, Azhng reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, and @maryliag)

___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 195 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhofc6s0ylZIk_rvCXw:-Mhp9eI4Cf7Il5pTKxkm:b8x9dqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/771f764002a85834368c3a7e1cad476ed7af6a66/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L195)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It's not important; what you have here is fine.

What I was thinking is that right now you go and find the number of rows in the shard and then you find the number you think should be in the shard and you delete until you think you've deleted enough. Another approach would be to find the `aggregated_ts` of the newest row you want to delete and use that drive the deletions here.
</blockquote></details>

I see. Interesting :thinking: I suppose we can try out that approach if the current approach becomes problematic. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 33 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp86dA51yS7tewIy-g:-Mhp8lfA4xZ12O5rKKsr:b-vzxaxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L33)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

my last nit is that this thing doesn't really compact, it just deletes. Is compaction future work?
</blockquote></details>

Yes, compaction is future work. 
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 89 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp7n1j2GXmxG3m8KkK:-Mhp9C6k4iZuRLMt5_IK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L89)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: for `shard, limit := range limitPerShard`, I don't think that the `int64` nature of the shard is important for your function signatures. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go, line 169 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-Mhp6bq89xDvSxSuHQt7:-Mhp9Xdr53TOgpH2weqE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/48be052b85cb324e28dac44ce759a32b70673f07/pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go#L169)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

fun fact, if you pass a `nil` for the `txn` the internal executor will deal with the transaction management for you. I encourage you to do that here. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-24 13:24 UTC, maryliag approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 20 of 20 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68434#-:-MhsKFB-CzEG5uOugZjy:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @arulajmani)



<!-- Sent from Reviewable.io -->

2021-08-24 14:24 UTC, Azhng commented
TFTR!

bors r=ajwerner,maryliag

2021-08-24 15:56 UTC, Azhng commented
bors r=ajwerner,maryliag

2021-08-24 17:34 UTC, merged