sql: implemented placement restricted syntax for domiciling
cockroachdb/cockroach pull request #68433
Opened 2021-08-04 17:47 UTC by pawalt

This PR combines the existing restricted placement zone config logic
with the stubbed syntax to create an end-to-end PLACEMENT RESTRICTED
implementation.

Release note: None

Note that the cluster setting for domiciling and telemetry will be added in a later PR.

2021-08-04 17:47 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68433)
<!-- Reviewable:end -->

2021-08-05 18:15 UTC, arulajmani requested changes
> Reviewed 2 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @otan, and @pawalt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMLWk21p2-Z0fXF8Vi:-MgMLWk21p2-Z0fXF8Vj:bdt9m4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L2)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> ```

nit: rename this file to `placement`
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMM27T4kulbzinwZ5d:-MgMM27T4kulbzinwZ5e:b-96bw0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L1)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> ```

nit: rename this file `regional_by_row_placement_restricted`
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMVtKT0w6eeKnp21Mi:-MgMVtKT0w6eeKnp21Mj:bveiip4) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L43)):*
> ```
> # Alter to RESTRICTED and see that we have no non-voter constraints.
> statement ok
> ALTER DATABASE testdb SET PLACEMENT RESTRICTED
> ```

Add tests to add/drop regions and change survival goal to ensure these operations work correctly with `PLACEMENT RESTRICTED`. 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMSho2AUSPvGP2xEGf:-MgMSho2AUSPvGP2xEGg:b-7sutef) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L1)):*
> ```
> # LogicTest: multiregion-9node-3region-3azs multiregion-9node-3region-3azs-vec-off
> ```

Same as above, let's rename this file `regional_by_table_placement_restricted`

Separately, should we have some tests for `global_tables` with `placement_restricted` as well? 
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMV_op8nb-FAM__jWX:-MgMV_op8nb-FAM__jWY:bi4z16r) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L45)):*
> ```
> # Change primary region to ensure zone config is rebuilt on table changes.
> statement ok
> ALTER DATABASE testdb SET PRIMARY REGION "ap-southeast-2"
> ```

Let's add tests that ensure ADD/DROP region continue to work correctly with `PLACEMENT RESTRICTED` as well? 
___
*[pkg/sql/alter_database.go, line 1108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMSy_-1Tf5tMht-qAH:-MgMSy_-1Tf5tMht-qAI:blhia44) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1108)):*
> ```Go
> 	}
> 
> 	// TODO(pawalt): add a check for placement enabled cluster setting
> ```

Mind opening an issue for this to keep track? 
___
*[pkg/sql/alter_database.go, line 1157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMTI4M8yCAzhF3rvTF:-MgMTI4M8yCAzhF3rvTG:bqmefz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1157)):*
> ```Go
> 		return err
> 	}
> 	n.desc.RegionConfig.Placement = newPlacement
> ```

Instead of directly updating the proto like such, let's add a setter method on `dbdesc.Mutable` instead. In general, we try to avoid raw proto accesses/setters -- they should instead be mediated through the specific descriptor interface or `Mutable` type respectively. 
___
*[pkg/sql/alter_database.go, line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMT7izDlhFz23HFsPu:-MgMT7izDlhFz23HFsPv:b-t02sr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1172)):*
> ```Go
> 	}
> 
> 	if err := multiregion.ValidateRegionConfig(regionConfig); err != nil {
> ```

`SynthesizeRegionConfig` gives you a validated `RegionConfig`, so I think you can get rid of this. 
___
*[pkg/sql/alter_database.go, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMUOeb0AEqdZhlxx9U:-MgMUOeb0AEqdZhlxx9V:b-k6tmr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1194)):*
> ```Go
> 	}
> 
> 	// TODO(pawalt): add telemetry/logging for PLACEMENT events.
> ```

Can we open issues for both of these things? 
___
*[pkg/sql/crdb_internal.go, line 253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMUquP1hvnNkri2g5i:-MgMUquP1hvnNkri2g5j:buow6g5) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/crdb_internal.go#L253)):*
> ```Go
> 	regions STRING[],
> 	survival_goal STRING,
> 	data_placement STRING,
> ```

nit: s/data_placement/placement_policy/?


<!-- Sent from Reviewable.io -->

2021-08-06 13:45 UTC, ajstorm requested changes
Nicely done!

> Reviewed 10 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-:-MgQhcBw6MDP9XNNfFLa:b-ao1qb6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQZCVE5iEhqtpdt2LD:-MgQZCVE5iEhqtpdt2LE:b-ojgcub) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/-- commits#L8)):*
I know that we don't want to make this public now, but in the case we need to expose this on short notice, does it make sense to write some basic documentation now?  @rmloveland thoughts?
___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQ_fcv-CCZz32hE4pG:-MgQ_fcv-CCZz32hE4pH:b4fqj73) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L10)):*
> ```
> 
> statement ok
> CREATE DATABASE zone_survivable_strict PRIMARY REGION "ca-central-1" REGIONS "ap-southeast-2", "us-east-1" PLACEMENT RESTRICTED
> ```

Can we both show the zone configurations here, and validate them using the builtin?  I want to ensure that validate holds up even with `PLACEMENT RESTRICTED` set.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQawjU2wfWlPJRASR-:-MgQawjU2wfWlPJRASR0:b2use2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L43)):*
> ```
> # Alter to RESTRICTED and see that we have no non-voter constraints.
> statement ok
> ALTER DATABASE testdb SET PLACEMENT RESTRICTED
> ```

Can we validate with the builtin here too?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQbJwp8BQ2E_qko7Pl:-MgQbJwp8BQ2E_qko7Pm:burzzsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L27)):*
> ```
> # Alter to RESTRICTED and see that we have no non-voter constraints.
> statement ok
> ALTER DATABASE testdb SET PLACEMENT RESTRICTED
> ```

Validate here too?
___
*[pkg/sql/alter_database.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQc0As9TfIn7shpZvb:-MgQc0As9TfIn7shpZvc:b-g3i5k5) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L755)):*
> ```Go
> 	// must be explicitly rebuilt so as to move their primary region.
> 	if updatedRegionConfig.IsPlacementRestricted() {
> 		if err := params.p.updateZoneConfigsForAllTables(params.ctx, n.desc); err != nil {
> ```

Does it make sense to be more precise here?  What I'm worried about is cases where we have 100s or 1000s of tables and only a handful of `GLOBAL` tables.  This will end up rewriting all of their zone configs.  Should we instead create a `updateZoneConfigsForAllGlobalTables` which filters out the other table types?
___
*[pkg/sql/alter_database.go, line 1128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQdf2VBJ0hOpULfobX:-MgQdf2VBJ0hOpULfobY:b-5wxvil) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1128)):*
> ```Go
> 		return errors.WithHintf(
> 			pgerror.New(pgcode.InvalidName,
> 				"database must have associated regions before a survival goal can be set",
> ```

Copy pasta?  Shouldn't this read that the database must have associated regions before the placement goal can be set?  Comment above too.

Also, can we test this case?
___
*[pkg/sql/crdb_internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQfsVOBK7V9P4DYojm:-MgQfsVOBK7V9P4DYojn:btcjue1) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/crdb_internal.go#L294)):*
> ```Go
> 						// unless we know the user wants to use PLACEMENT. Therefore, we
> 						// only add a PLACEMENT clause if we're in restricted mode.
> 						createNode.Placement = tree.DataPlacementUnspecified
> ```

I'm probably missing something, but is there a reason why we want to differentiate between DEFAULT and UNSPECIFIED?  Shouldn't they be the same in practice?


<!-- Sent from Reviewable.io -->

2021-08-09 14:58 UTC, rmloveland reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @otan, and @pawalt)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQZCVE5iEhqtpdt2LD:-MgfO1cN-gw-gooM3h-L:bglosku) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/-- commits#L8)):*
> we need to expose this on short notice

tl;dr: I'd rather just ignore this for now

long version:

if someone really really needs this info ASAP I bet someone could email them instructions how to use it while we get a docs PR ready (est. 1-2 days to write/review/merge)

meta: this convo is part of why I'm knee-jerk anti "put it in the product but don't document it", because then we have to spend time thinking about non-standard workflows like this and maybe end up doing rushed work anyway  (cc @awoods187 with my sudden but inevitable complaint :-D )


<!-- Sent from Reviewable.io -->

2021-08-09 15:02 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @otan, and @pawalt)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQZCVE5iEhqtpdt2LD:-MgfQ_CREqWQHu-F_jKy:b-gn7o94) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/-- commits#L8)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

> we need to expose this on short notice

tl;dr: I'd rather just ignore this for now

long version:

if someone really really needs this info ASAP I bet someone could email them instructions how to use it while we get a docs PR ready (est. 1-2 days to write/review/merge)

meta: this convo is part of why I'm knee-jerk anti "put it in the product but don't document it", because then we have to spend time thinking about non-standard workflows like this and maybe end up doing rushed work anyway  (cc @awoods187 with my sudden but inevitable complaint :-D )
</blockquote></details>

It's a fair (and somewhat expected) complaint.  The reason we voted to have this go into 21.2 is because we're worried that the knee-jerk code-level backfit would be riskier than a knee-jerk doc change, but I'm open to have my mind changed on that.  I confess that I don't have a good sense for the risk involved in these types of doc changes.


<!-- Sent from Reviewable.io -->

2021-08-09 15:28 UTC, rmloveland reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @otan, and @pawalt)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQZCVE5iEhqtpdt2LD:-MgfW-vUBMls36J2RW4-:b-t8beh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/-- commits#L8)):*
> the risk involved in these types of doc changes.

tbh almost no risk from a purely docs POV, it's easy to add when we need it.  I agree with the assessment that changing the code is way riskier/harder

I'm just, like, duty bound to complain about it - because historically CRL doesn't do much of this.  But I have worked at other places where this becomes "the norm", esp. when dealing with big customers.  Work becomes a lot less fun (and harder to do at good quality levels) in those environments.  So I'm worried about the slippery slope.  Because from any customer's (or revenue team member's) POV it's always "Important (tm)"


<!-- Sent from Reviewable.io -->

2021-08-09 15:43 UTC, ajstorm requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @otan, and @pawalt)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQZCVE5iEhqtpdt2LD:-Mgf_225BUCRm-vuS9C5:bk7km9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/-- commits#L8)):*
<details><summary><i>Previously, rmloveland (Rich Loveland) wrote…</i></summary><blockquote>

> the risk involved in these types of doc changes.

tbh almost no risk from a purely docs POV, it's easy to add when we need it.  I agree with the assessment that changing the code is way riskier/harder

I'm just, like, duty bound to complain about it - because historically CRL doesn't do much of this.  But I have worked at other places where this becomes "the norm", esp. when dealing with big customers.  Work becomes a lot less fun (and harder to do at good quality levels) in those environments.  So I'm worried about the slippery slope.  Because from any customer's (or revenue team member's) POV it's always "Important (tm)"
</blockquote></details>

I agree.  This is one of the reasons I was wondering if we wanted a draft PR (or Google Doc) at the ready should such a need arise?  I was thinking that this could make the fire drill less hot if/when it eventually arrives.


<!-- Sent from Reviewable.io -->

2021-08-09 16:47 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/domiciling, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQ_fcv-CCZz32hE4pG:-MgfauM234gSrSZT4-ux:bdgdxrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/domiciling#L10)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we both show the zone configurations here, and validate them using the builtin?  I want to ensure that validate holds up even with `PLACEMENT RESTRICTED` set.
</blockquote></details>

Yup I'll do it at the database level here and at the table level in each table test.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMVtKT0w6eeKnp21Mi:-MgMuJo_9UDxTrVJNvgd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L43)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Add tests to add/drop regions and change survival goal to ensure these operations work correctly with `PLACEMENT RESTRICTED`. 
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQawjU2wfWlPJRASR-:-MgfdBiDCL66oFokxUsX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_domiciling#L43)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Can we validate with the builtin here too?
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMSho2AUSPvGP2xEGf:-MgMv3kz8TywZPwnrETH:b-82mo1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L1)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same as above, let's rename this file `regional_by_table_placement_restricted`

Separately, should we have some tests for `global_tables` with `placement_restricted` as well? 
</blockquote></details>

Yep I'll add tests that ensure global tables get the new non-inherited zone config.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQbJwp8BQ2E_qko7Pl:-MgfdCYF0oEQiM6cdbFf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L27)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Validate here too?
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMV_op8nb-FAM__jWX:-MgMv1PmCqC_rwU2T-Nb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_domiciling#L45)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add tests that ensure ADD/DROP region continue to work correctly with `PLACEMENT RESTRICTED` as well? 
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQc0As9TfIn7shpZvb:-Mgflq5b4_CDhD_qoQvf:b-fqw727) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L755)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Does it make sense to be more precise here?  What I'm worried about is cases where we have 100s or 1000s of tables and only a handful of `GLOBAL` tables.  This will end up rewriting all of their zone configs.  Should we instead create a `updateZoneConfigsForAllGlobalTables` which filters out the other table types?
</blockquote></details>

I think that makes sense. I figure we'll want to do this with RBR/RBT tables as well, so I've added a method that allows you to pass in a filter to only apply changes to table descriptors that match the filter.
___
*[pkg/sql/alter_database.go, line 1108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMSy_-1Tf5tMht-qAH:-MgfhAgU2UDYtWteAfRO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1108)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Mind opening an issue for this to keep track? 
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 1128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQdf2VBJ0hOpULfobX:-MgfidTk-scTiOHdPtnt:b-rfic0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1128)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Copy pasta?  Shouldn't this read that the database must have associated regions before the placement goal can be set?  Comment above too.

Also, can we test this case?
</blockquote></details>

Added testing for creating without a primary region and altering without a primary region.
___
*[pkg/sql/alter_database.go, line 1157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMTI4M8yCAzhF3rvTF:-Mgfmub06wF63A1PG3CC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1157)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of directly updating the proto like such, let's add a setter method on `dbdesc.Mutable` instead. In general, we try to avoid raw proto accesses/setters -- they should instead be mediated through the specific descriptor interface or `Mutable` type respectively. 
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 1172 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMT7izDlhFz23HFsPu:-MgfinGc4Wxp1CBJ7J-I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1172)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

`SynthesizeRegionConfig` gives you a validated `RegionConfig`, so I think you can get rid of this. 
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 1194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgMUOeb0AEqdZhlxx9U:-MgfhBXsDVOmL0FTT9x0:b-qnxul6) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L1194)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we open issues for both of these things? 
</blockquote></details>

#68597
#68598
___
*[pkg/sql/crdb_internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQfsVOBK7V9P4DYojm:-MgfiyWi1xOqoet9DvIR:bpemair) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/crdb_internal.go#L294)):*
<details><summary><i>Previously, ajs [...]

2021-08-10 18:17 UTC, arulajmani requested changes
> Reviewed 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @otan, and @pawalt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/global_placement_restricted, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglG7Hl6SajCLQU5fdw:-MglG7Hl6SajCLQU5fdx:bn642hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/ccl/logictestccl/testdata/logic_test/global_placement_restricted#L100)):*
> ```
>             lease_preferences = '[[+region=ap-southeast-2]]'
> 
> # Alter to DEFAULT and see that our voter constraints are back.
> ```

Were they gone before?
___
*[pkg/sql/alter_database.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglGyoO9es8vjlbbrag:-MglGyoO9es8vjlbbrah:b-qqstyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L265)):*
> ```Go
> 	// RESTRICTED mode, GLOBAL tables will not inherit the database zone config
> 	// and will have to be explicitly rebuilt.
> 	if n.desc.RegionConfig.Placement == descpb.DataPlacement_RESTRICTED {
> ```

Same comment as below. 
___
*[pkg/sql/alter_database.go, line 652 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglGqH79IQUgvbI-vXe:-MglGqH79IQUgvbI-vXf:b-y4uw4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L652)):*
> ```Go
> 	// Update all GLOBAL tables' zone configurations. This is required as in
> 	// RESTRICTED mode, GLOBAL tables will not inherit the database zone config
> 	// and will have to be explicitly rebuilt.
> ```

I see you're doing something similar in the `DatabaseRegionChangeFinalizer`. I may be missing something, but do you need both? 
___
*[pkg/sql/alter_database.go, line 1220 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglDp0xDh3MXu1bOexV:-MglDp0xDh3MXu1bOexW:bn08zd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L1220)):*
> ```Go
> 	}
> 
> 	// Update all GLOBAL tables' zone configurations. This is required as in
> ```

I think there's more to this. I'd reword this as:

```
Update all GLOBAL tables' zone configurations. This is required because GLOBAL table's can inherit the database's zone configuration under the DEFAULT placement policy. However, under the RESTRICTED placement policy, non-voters are removed from the database. But global tables need non-voters to behave properly, and as such, need a bespoke zone configuration. Regardless of the transition direction (DEFAULT -> RESTRICTED, RESTRICTED -> DEFAULT), we need to refresh the zone configuration of all GLOBAL table's inside the database to either carry a bespoke configuration or go back to inheriting it from the database.
```
___
*[pkg/sql/crdb_internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQfsVOBK7V9P4DYojm:-Mgl7WftDa4X8I5v_cXz:byynr0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/crdb_internal.go#L294)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

They are the same in practice, but the formatter doesn't print for UNSPECIFIED but it does for DEFAULT. In this case, we want to always format as UNSPECIFIED so that a user on the DEFAULT behavior doesn't get PLACEMENT leaked to them.
</blockquote></details>

nit: s/if we're in restricted mode/if the database was configured with restricted placement/g
___
*[pkg/sql/create_database.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgl7ksi4ySvdw0hleIy:-Mgl7ksi4ySvdw0hleIz:b-c237c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/create_database.go#L98)):*
> ```Go
> 
> 	if n.Placement != tree.DataPlacementUnspecified {
> 		// TODO(pawalt): add cluster setting checking for placement
> ```

nit: full stop
nit: link the issue here (and above) as well maybe?
___
*[pkg/sql/database_region_change_finalizer.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAPMVBDPYHXOO6EjQ:-MglAPMVBDPYHXOO6EjR:bc1x833) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L39)):*
> ```Go
> 	cleanupFunc         func()
> 	regionalByRowTables []*tabledesc.Mutable
> 	globalTables        []*tabledesc.Mutable
> ```

Does this need to be a field on this struct? Put another way, is there a reason to pre-fetch all global tables?
___
*[pkg/sql/database_region_change_finalizer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAslb5PKTdQMfbpxw:-MglAslb5PKTdQMfbpxx:b47et1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L173)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

Should we add a check to only do this if the database is configured in `PLACEMENT RESTRICTED`? 
___
*[pkg/sql/database_region_change_finalizer.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAgRK299b3QMvjRcY:-MglAgRK299b3QMvjRcZ:b-f0i3sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L175)):*
> ```Go
> 	}
> 
> 	for _, tableDesc := range r.globalTables {
> ```

Do you need to save all global tables on this struct or can you just fetch them here? 
___
*[pkg/sql/descriptor.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBR3R--xPfyAgpDnl:-MglBR3R--xPfyAgpDnm:benxrzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/descriptor.go#L250)):*
> ```Go
> 		return descpb.DataPlacement_RESTRICTED, nil
> 	default:
> 		return 0, errors.Newf("unknown data placement: %d", g)
> ```

Should this be an assertion failed error?
___
*[pkg/sql/region_util.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBx_DCqml5Zk9RGoD:-MglBx_DCqml5Zk9RGoE:b-85bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L150)):*
> ```Go
> 		// placement. Voter placement will be set at the table/partition level to
> 		// the table/partition region.
> 		constraints = nil
> ```

Why did this change?
___
*[pkg/sql/region_util.go, line 816 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglCCZU6W6oUaTvL52t:-MglCCZU6W6oUaTvL52u:b-revhbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L816)):*
> ```Go
> }
> 
> func filterIsLocalityGlobal(t *tabledesc.Mutable) bool {
> ```

Consider making this an option. Have `updateZoneConfigsForTables` take in an optional list of options. By default, the filter function will be a passthrough. Then, you can make a `WithOnlyGlobalTables` option that applies this filter. 

Here's a link in the style guide which talks a bit more about this pattern (if you're unfamiliar): https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Functional-Options
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglD85XCID405qrKgQE:-MglD85XCID405qrKgQF:bdanzny) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/catalog/dbdesc/database_desc.go#L408)):*
> ```Go
> }
> 
> // SetPlacement sets the placement of the region config for a database
> ```

s/of the region config/on the region config/g
___
*[pkg/ccl/logictestccl/tes [...]

2021-08-10 19:35 UTC, awoods187 commented
I'm supportive of documenting this in a Google doc that we can publish in the future. We have plenty of historical evidence of not documenting changes, particularly ones gated behind feature flags.

2021-08-10 21:14 UTC, ajstorm approved these changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @otan, and @pawalt)

___
*[pkg/sql/alter_database.go, line 755 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQc0As9TfIn7shpZvb:-MgluG2dBH--KEpvhYI7:b-89q77x) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/alter_database.go#L755)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I think that makes sense. I figure we'll want to do this with RBR/RBT tables as well, so I've added a method that allows you to pass in a filter to only apply changes to table descriptors that match the filter.
</blockquote></details>

Cool!
___
*[pkg/sql/crdb_internal.go, line 294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgQfsVOBK7V9P4DYojm:-MgluWe117M1kuLZRCZ5:b45z86u) ([raw file](https://github.com/cockroachdb/cockroach/blob/204929de4c4b49a7057f7d9dcf87cb3f2beb74d9/pkg/sql/crdb_internal.go#L294)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/if we're in restricted mode/if the database was configured with restricted placement/g
</blockquote></details>

Gotcha.  I think I saw this in your Gru presentation.


<!-- Sent from Reviewable.io -->

2021-08-11 04:01 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/global_placement_restricted, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglG7Hl6SajCLQU5fdw:-Mgn7zO2BIC5dgBgeZuj:b-oco3c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/ccl/logictestccl/testdata/logic_test/global_placement_restricted#L100)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Were they gone before?
</blockquote></details>

Nope ... not sure what I was trying to say here. Fixed.
___
*[pkg/sql/alter_database.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglGyoO9es8vjlbbrag:-MgnBLX8CMWbtxnpnUlK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L265)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same comment as below. 
</blockquote></details>

Done.
___
*[pkg/sql/alter_database.go, line 652 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglGqH79IQUgvbI-vXe:-MgnBHPkClyNQqICcpIu:b-lnokev) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L652)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I see you're doing something similar in the `DatabaseRegionChangeFinalizer`. I may be missing something, but do you need both? 
</blockquote></details>

Ah I didn't think of that. Removed.
___
*[pkg/sql/alter_database.go, line 1220 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglDp0xDh3MXu1bOexV:-MgnCDWQ5riZ-kidZOl4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/alter_database.go#L1220)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think there's more to this. I'd reword this as:

```
Update all GLOBAL tables' zone configurations. This is required because GLOBAL table's can inherit the database's zone configuration under the DEFAULT placement policy. However, under the RESTRICTED placement policy, non-voters are removed from the database. But global tables need non-voters to behave properly, and as such, need a bespoke zone configuration. Regardless of the transition direction (DEFAULT -> RESTRICTED, RESTRICTED -> DEFAULT), we need to refresh the zone configuration of all GLOBAL table's inside the database to either carry a bespoke configuration or go back to inheriting it from the database.
```
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAPMVBDPYHXOO6EjQ:-MgnGwpn1r-rKw073seS:b-megwz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L39)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Does this need to be a field on this struct? Put another way, is there a reason to pre-fetch all global tables?
</blockquote></details>

Nope I think fetching them later is fine. Changed.
___
*[pkg/sql/database_region_change_finalizer.go, line 173 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAslb5PKTdQMfbpxw:-MgnGzvh43vLD0-TtOjk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L173)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we add a check to only do this if the database is configured in `PLACEMENT RESTRICTED`? 
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 175 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglAgRK299b3QMvjRcY:-MgnH-8s8CiY4PCmIoyR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/database_region_change_finalizer.go#L175)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you need to save all global tables on this struct or can you just fetch them here? 
</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBR3R--xPfyAgpDnl:-MgnHIGZ26goJe0MkA2s:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/descriptor.go#L250)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be an assertion failed error?
</blockquote></details>

Yep
___
*[pkg/sql/region_util.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBx_DCqml5Zk9RGoD:-MgnHQYz05WWyFUjpnJa:b-yb9pnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Why did this change?
</blockquote></details>

I found out that empty constraints get deserialized as nil even if they're created with `[]`, so I changed this so that the generated zone config is the same as the one stored in the database. You get errors otherwise since the multi-region checks think the zone config has been modified by the user.
___
*[pkg/sql/region_util.go, line 816 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglCCZU6W6oUaTvL52t:-MgnMR434YuhljyJ81Ea:b-oyemx) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L816)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Consider making this an option. Have `updateZoneConfigsForTables` take in an optional list of options. By default, the filter function will be a passthrough. Then, you can make a `WithOnlyGlobalTables` option that applies this filter. 

Here's a link in the style guide which talks a bit more about this pattern (if you're unfamiliar): https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Functional-Options
</blockquote></details>

Gave this a shot. Let me know if it looks ok
___
*[pkg/sql/catalog/dbdesc/database_desc.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglD85XCID405qrKgQE:-MgnMaCZ9XZ6DnZ5YpuK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/catalog/dbdesc/database_desc.go#L408)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/of the region config/on the region config/g
</blockquote></details>

Done.
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglGIML4FrfjWuTmw3L:-Mgn8EcB6odnfiTxmA9U:b2nhswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted#L134)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do you mean constraints?
</blockquote></details>

Yep
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_placement_restricted, line 10 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgl6PT_1_WV3Oyx2zV2:-MgnAMu-2ZddspjVFGAB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/ccl/logictestccl/ [...]

2021-08-11 14:39 UTC, arulajmani requested changes
Thanks for making the changes! This is quite close, mostly minor comments left. 

Let's open an issue for the `ADD/DROP REGION` failure case that we talked about offline as well? 

> Reviewed 1 of 10 files at r3, 1 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-:-MgpdblJ-wGZrRrku154:bkeupvk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @otan, and @pawalt)

___
*[pkg/sql/database_region_change_finalizer.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcGlLBzhVY1y_t61Y:-MgpcGlLBzhVY1y_t61Z:b-yqwl8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L81)):*
> ```Go
> 			dbDesc,
> 			func(ctx context.Context, scName string, tableDesc *tabledesc.Mutable) error {
> 				if tableDesc.Dropped() {
> ```

Revert this change?
___
*[pkg/sql/database_region_change_finalizer.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgpcs9y0PTHxYUJ32nI:-Mgpcs9y0PTHxYUJ32nJ:bqaj9fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L160)):*
> ```Go
> // updateGlobalTablesZoneConfig recalculates all global tables' zone configs so
> // that their zone configs are recalculated after a newly-added region goes
> // out of being a transitioning region.
> ```

Could you add a nod here that this is only required when the database has the `PLACEMENT RESTRICTED` policy and why? 

Also can we s/recalculate/refresh/g in the comment for consistency, as that's the word we use in other places?
___
*[pkg/sql/database_region_change_finalizer.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcSWC2_93icb496X0:-MgpcSWC2_93icb496X1:b6cpz9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L181)):*
> ```Go
> 		return err
> 	}
> 	mutableDesc := dbDesc.(*dbdesc.Mutable)
> ```

I don't think this is safe -- you shouldn't be getting an immutable database descriptor and then casting it to mutable descriptor. You should instead ask the descsCol for a mutable database descriptor. 
___
*[pkg/sql/region_util.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBx_DCqml5Zk9RGoD:-MgpaiWZCzSeBZF_GDqi:b-m2zr58) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L150)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I found out that empty constraints get deserialized as nil even if they're created with `[]`, so I changed this so that the generated zone config is the same as the one stored in the database. You get errors otherwise since the multi-region checks think the zone config has been modified by the user.
</blockquote></details>

I see, thanks for the explanation. Let's put this in a `// NB: ` here as well for posterity?
___
*[pkg/sql/region_util.go, line 816 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglCCZU6W6oUaTvL52t:-Mgp_J5n0kObgCw1wXSc:b-eioqcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L816)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Gave this a shot. Let me know if it looks ok
</blockquote></details>

Looks great, thanks for making the change! Is this filter function unused now? Should we get rid of it?
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgpb3f8Eou-aWjCy-N7:-Mgpb3f8Eou-aWjCy-N8:bxypzj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted#L134)):*
> ```
> lease_preferences = '[[+region=us-east-1]]'
> 
> # Alter to DEFAULT and see that our non-voter constraints are back.
> ```

Let's just drop `non-voter` altogether? It's slightly confusing, the way this looks, but the `constraints` field actually applies to both voters and non-voters. 


<!-- Sent from Reviewable.io -->

2021-08-12 16:42 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, and @otan)

___
*[pkg/sql/database_region_change_finalizer.go, line 81 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcGlLBzhVY1y_t61Y:-MgvBLo7Eb0TgNtJTEYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L81)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Revert this change?
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgpcs9y0PTHxYUJ32nI:-MgvBuFy6WbyAlDilSlv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L160)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could you add a nod here that this is only required when the database has the `PLACEMENT RESTRICTED` policy and why? 

Also can we s/recalculate/refresh/g in the comment for consistency, as that's the word we use in other places?
</blockquote></details>

Done.
___
*[pkg/sql/database_region_change_finalizer.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcSWC2_93icb496X0:-MgvD8JLA_FI9NOU04Gr:bo0jbun) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L181)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think this is safe -- you shouldn't be getting an immutable database descriptor and then casting it to mutable descriptor. You should instead ask the descsCol for a mutable database descriptor. 
</blockquote></details>

I did this initially because I didn't want to have to get the database name and then the mutable descriptor (since we only have a `GetMutableDatabaseByName` function). I've added a `GetMutableDatabaseByID` function; let me know if the approach is safe. I think it is because I'm requiring the descriptor to be mutable, but not 100%.
___
*[pkg/sql/region_util.go, line 150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglBx_DCqml5Zk9RGoD:-MgvEPSsAXIe2SIU902L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L150)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I see, thanks for the explanation. Let's put this in a `// NB: ` here as well for posterity?
</blockquote></details>

Done.
___
*[pkg/sql/region_util.go, line 816 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MglCCZU6W6oUaTvL52t:-MgvEQD9DmvQFaAKF85H:b-212uch) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ef652b3a63a90f84b052f2a5edf5d07771bd5a/pkg/sql/region_util.go#L816)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Looks great, thanks for making the change! Is this filter function unused now? Should we get rid of it?
</blockquote></details>

Yep removed
___
*[pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted, line 134 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-Mgpb3f8Eou-aWjCy-N7:-MgvEZNT8Z6vwDmxwfWd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted#L134)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's just drop `non-voter` altogether? It's slightly confusing, the way this looks, but the `constraints` field actually applies to both voters and non-voters. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-12 18:29 UTC, arulajmani reviewed
One last thing before this is good to go! My bad on not realizing about `updateZoneConfigsForAllTables` earlier. 

> Reviewed 1 of 10 files at r4, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-:-MgvbmlL6Y8JOda1jQuQ:bbh1buh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, @otan, and @pawalt)

___
*[pkg/sql/database_region_change_finalizer.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcSWC2_93icb496X0:-Mgv_VbzD9o5EGLLsJoi:b-w3e79v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L181)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I did this initially because I didn't want to have to get the database name and then the mutable descriptor (since we only have a `GetMutableDatabaseByName` function). I've added a `GetMutableDatabaseByID` function; let me know if the approach is safe. I think it is because I'm requiring the descriptor to be mutable, but not 100%.
</blockquote></details>

I think what you have makes sense, but I'm not sure we need to/should expose this API considering:
1. this is the only usage
2. The reason you need it here is slightly dubious (not because of something you did)

Let me say a bit more about what I mean by point 2 here -- I'm looking at this `udpateZoneConfigsForTables` method again and looks like it only needs the database descriptor to synthesize the region config. I don't think it needs a mutable descriptor to begin with considering all its using it for is to synthesize the region config. `SynthesizeRegionConfig` only takes an ID and does so because it wants to read the descriptor from the store so that it gets an up-to-date view of things (as opposed to the leased version). This is all to say that maybe the right thing to do here is to change `updateZoneConfigsForTables` to take in a `catalog.DatabaseDescriptor` instead of a mutable database descriptor. 
___
*[pkg/sql/region_util.go, line 155 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgvHbK36KIEBShhANvF:-MgvHbK36KIEBShhANvG:b90jjqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c130cb9eac9d48f7146803ba844a40c8bec3b48/pkg/sql/region_util.go#L155)):*
> ```Go
> 		// always deserialized as nil. Therefore, if constraints are set as [] here,
> 		// the database will have a difference in its expected constraints vs the
> 		// actual constraints.
> ```

nit: vs the actual constraints when comparing using multi-region validation builitins? 


<!-- Sent from Reviewable.io -->

2021-08-12 19:13 UTC, pawalt reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, and @otan)

___
*[pkg/sql/database_region_change_finalizer.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-MgpcSWC2_93icb496X0:-Mgvl-A3-am-IIiU3BL2:b-4lju2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c82d343303ec3056c543b5210f2e09d26d221c0c/pkg/sql/database_region_change_finalizer.go#L181)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think what you have makes sense, but I'm not sure we need to/should expose this API considering:
1. this is the only usage
2. The reason you need it here is slightly dubious (not because of something you did)

Let me say a bit more about what I mean by point 2 here -- I'm looking at this `udpateZoneConfigsForTables` method again and looks like it only needs the database descriptor to synthesize the region config. I don't think it needs a mutable descriptor to begin with considering all its using it for is to synthesize the region config. `SynthesizeRegionConfig` only takes an ID and does so because it wants to read the descriptor from the store so that it gets an up-to-date view of things (as opposed to the leased version). This is all to say that maybe the right thing to do here is to change `updateZoneConfigsForTables` to take in a `catalog.DatabaseDescriptor` instead of a mutable database descriptor. 
</blockquote></details>

Agreed. Changed to `catalog.DatabaseDescriptor` and removed `GetMutableDatabaseByID`


<!-- Sent from Reviewable.io -->

2021-08-12 19:51 UTC, arulajmani approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68433#-:-Mgvul954rGnvpnucydl:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @awoods187, and @otan)



<!-- Sent from Reviewable.io -->

2021-08-13 19:58 UTC, pawalt commented
bros r=arulajmani

2021-08-13 20:20 UTC, pawalt commented
bors r+

2021-08-15 22:53 UTC, pawalt commented
bors r=arulajmani

2021-08-15 23:58 UTC, merged