release: update cockroach-cloud-images repository location
cockroachdb/cockroach pull request #68483
Opened 2021-08-05 16:29 UTC by DuskEagle

This commit updates the location of the cockroach-cloud-images Docker
repository. For reasons described in https://cockroachlabs.atlassian.net/browse/CC-4667,
we are switching our internal CockroachDB Docker repository to this location,
which is build on top of Google Artifact Registry.

Release note: None

2021-08-05 16:29 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68483)
<!-- Reviewable:end -->

2021-08-09 18:15 UTC, jlinder requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-Mgft1nvDfV8u0LbqRCR:-Mgft1nvDfV8u0LbqRCS:bqlv0ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec24c83d2ac00ba13228178c54852800a48078c/-- commits#L7)):*
> ```
> which is build on top of Google Artifact Registry.
> ```

grammar nit (because build is not past tense). Maybe the following instead?

```
which uses Google Artifact Registry.
```
___
*[build/release/teamcity-make-and-publish-build.sh, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-MgftSTBAfpiwGvHFHK6:-MgftSTBAfpiwGvHFHK7:b-6lvwfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec24c83d2ac00ba13228178c54852800a48078c/build/release/teamcity-make-and-publish-build.sh#L19)):*
> ```Shell
> if [[ -z "${DRY_RUN}" ]] ; then
>   bucket="${BUCKET-cockroach-builds}"
>   google_credentials=$GOOGLE_COCKROACH_CLOUD_IMAGES_CREDENTIALS
> ```

Since versions of this script live in release branches too, I'd like to use a different name for the `GOOGLE_COCKROACH_CLOUD_IMAGES_CREDENTIALS` parameter so we don't break any of the release branches before this change is backported. How about `GOOGLE_COCKROACH_CLOUD_IMAGES_COCKROACHDB_CREDENTIALS`?

Also in the other files that are modified please.


<!-- Sent from Reviewable.io -->

2021-08-09 20:09 UTC, DuskEagle reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68483)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-Mgft1nvDfV8u0LbqRCR:-MggWfyE9G1C3K24GxBz:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec24c83d2ac00ba13228178c54852800a48078c/-- commits#L7)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> which is build on top of Google Artifact Registry.
> ```

grammar nit (because build is not past tense). Maybe the following instead?

```
which uses Google Artifact Registry.
```

</blockquote></details>

Good catch, fixed.
___
*[build/release/teamcity-make-and-publish-build.sh, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-MgftSTBAfpiwGvHFHK6:-MggWbF89tmFXE3S7ZYf:br9ph3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec24c83d2ac00ba13228178c54852800a48078c/build/release/teamcity-make-and-publish-build.sh#L19)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Since versions of this script live in release branches too, I'd like to use a different name for the `GOOGLE_COCKROACH_CLOUD_IMAGES_CREDENTIALS` parameter so we don't break any of the release branches before this change is backported. How about `GOOGLE_COCKROACH_CLOUD_IMAGES_COCKROACHDB_CREDENTIALS`?

Also in the other files that are modified please.

</blockquote></details>

I've made the change, but I am a little confused. If we're creating a new Teamcity build config for the new location, which it seems like we are, doesn't that prevent release branch builds from breaking before this change is backported? The release branch build pipeline would presumably still use the old Teamcity jobs with the old versions of this file?


<!-- Sent from Reviewable.io -->

2021-08-09 20:44 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-:-MggdydX7lWJGIimBRic:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DuskEagle)

___
*[build/release/teamcity-make-and-publish-build.sh, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68483#-MgftSTBAfpiwGvHFHK6:-MggcJjS458a8T1pG67J:bw21u2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec24c83d2ac00ba13228178c54852800a48078c/build/release/teamcity-make-and-publish-build.sh#L19)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

I've made the change, but I am a little confused. If we're creating a new Teamcity build config for the new location, which it seems like we are, doesn't that prevent release branch builds from breaking before this change is backported? The release branch build pipeline would presumably still use the old Teamcity jobs with the old versions of this file?
</blockquote></details>

Ah! It's a new build configuration _template_, not a new build configuration. A template can be attached to a build configuration so the build configuration will inherit whatever properties were defined in the template. This means the pipeline jobs will be the same jobs but they will inherit this new parameter from the new template. 


<!-- Sent from Reviewable.io -->

2021-08-09 20:51 UTC, DuskEagle commented
bors r+

2021-08-09 22:19 UTC, merged