spanconfig: introduce the span config manager
cockroachdb/cockroach pull request #68522
Opened 2021-08-05 23:54 UTC by arulajmani

See individual commits for details.

2021-08-05 23:54 UTC, cockroach-teamcity commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.png" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/cockroach/68522)
<!-- Reviewable:end -->

2021-08-09 15:55 UTC, irfansharif reviewed
LGTM, but I'll defer to others for actual the rubber stamp. My comments are mostly around adding more comments. I think it'd be very helpful to explain in text somewhere what various pieces we're looking to introduce over subsequent PRs and how we expect them to get stitched together. It'd make it easier+faster to review.

To that end, I'd make the commit messages a bit more verbose -- I think it's too little context unless you have it all paged in already. For e.g., explain that this job is running per-tenant, and what it'll eventually be slated to do. Also, refer to https://github.com/cockroachdb/cockroach/issues/67679. We could alternatively create an issue containing all the details + pointers to relevant bits in the prototype branch so we know the final state we're headed towards and how this intermediate PR gets us there.

> Reviewed 5 of 5 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MgfN9oVDl6dm-FyOtiI:b8t4l7s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-MgfQkAs1NZ6mAO1v4Bi:b-x9zpcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
> ```Go
> 		Knobs: base.TestingKnobs{
> 			SpanConfig: &spanconfig.TestingKnobs{
> 				ManagerDisableJobCreation: true,
> ```

Why are we disabling the span config manager in this test? Maybe add an inline comment.
___
*[pkg/server/admin_test.go, line 1437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRJMU8QEG7wtmeeER:-MgfRJMU8QEG7wtmeeES:bvshc71) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/admin_test.go#L1437)):*
> ```Go
> 		Knobs: base.TestingKnobs{
> 			SpanConfig: &spanconfig.TestingKnobs{
> 				ManagerDisableJobCreation: true,
> ```

Ditto. Out of curiosity -- is there anything else that's non-invasive-ish that we can do to generalize these tests to not need to use this knob?
___
*[pkg/server/server_sql.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRjBE6tu7EtSmCGBq:-MgfRjBE6tu7EtSmCGBr:b-4p65dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/server_sql.go#L804)):*
> ```Go
> 	{
> 		knobs, _ := cfg.TestingKnobs.SpanConfig.(*spanconfig.TestingKnobs)
> 		reconciliationMgr := spanconfigmanager.New(
> ```

Add some commentary here explaining how+why these things are stitched together.
___
*[pkg/spanconfig/spanconfig.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfW48GCvgOkRrXXOKi:-MgfW48GCvgOkRrXXOKj:b-rzs89y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfig.go#L17)):*
> ```Go
> // configs with the cluster's.
> type ReconciliationDependencies interface {
> 	// KVAccessor
> ```

If you're making mention of future interfaces here, add some additional commentary. This is not providing the most helpful context I think.
___
*[pkg/spanconfig/testing_knobs.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRvly-l-m4BKo7kLr:-MgfRvly-l-m4BKo7kLs:b-t7l9gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L18)):*
> ```Go
> // for testing.
> type TestingKnobs struct {
> 	ManagerDisableJobCreation bool
> ```

Add a comment, mention it's the auto reconciliation job that's not being created.
___
*[pkg/spanconfig/testing_knobs.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfS4yP37o4BpBsS-28:-MgfS4yP37o4BpBsS-29:b-ukw2to) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L24)):*
> ```Go
> }
> 
> // ModuleTestingKnobs makes TestingKnobs a base.ModuleTestingKnobs.
> ```

// ModuleTestingKnobs is part of the base.ModuleTestingKnobs interface.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfTVxM0NLx7b3cENoZ:-MgfTVxM0NLx7b3cENo_:bx01hnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L28)):*
> ```Go
> )
> 
> // Manager is responsible for ensuring that only one (and only one) span config
> ```

"that one (and only one)"
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfTlwFC3K1ifDQtnmV:-MgfTlwFC3K1ifDQtnmW:b4jywim) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L41)):*
> ```Go
> var _ spanconfig.ReconciliationDependencies = &Manager{}
> 
> // New constructs a new reconciliation manager.
> ```

Drop the "reconciliation manager" language, I think this was a remnant from our earlier package structure with the zcfgreconciler guy.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfU0Gr2xAPkxWN0Ql4:-MgfU0Gr2xAPkxWN0Ql5:b-3ezime) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L61)):*
> ```Go
> }
> 
> // StartJobIfNoneExists will create and start the span config reconciliation job
> ```

s/Exists/Exist?
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfVLFH4mE_lBOSS5lQ:-MgfVLFH4mE_lBOSS5lR:b-fatlai) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager_test.go#L71)):*
> ```Go
> 	manager.StartJobIfNoneExists(ctx)
> 
> 	testutils.SucceedsSoon(t, func() error {
> ```

Is there a way to cleanly test that the concurrent attempts don't do anything? Perhaps making sure there are no outstanding stopper tasks. I think with the test as is it's possible to flake your way into success if it completes before the other StartJobIfNoneExists calls get to do anything. 
___
*[pkg/sql/exec_util.go, line 1022 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfUZlq-EjOEsoLwf6H:-MgfUZlq-EjOEsoLwf6I:b-c2r0lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/sql/exec_util.go#L1022)):*
> ```Go
> 
> 	// StartSpanConfigReconciliationJobHook is called during the SQL server
> 	// startup process, to idempotently create and start a span config
> ```

s/,/
s/reconciliation for the tenant if none exists/reconciliation job
___
*[pkg/sql/exec_util.go, line 1027 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfUkOP1BVwfE6UwrEv:-MgfUkOP1BVwfE6UwrEw:bl1cgv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/sql/exec_util.go#L1027)):*
> ```Go
> }
> 
> // StartSpanConfigReconciliationJobHook is used to create and start the span
> ```

// StartSpanConfigReconciliationJobHook is used to idempotently create and start the span config reconciliation job.
___
*[pkg/sql/delegate/show_jobs.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfO63YANGg69JAGqYC:-MgfO63YANGg69JAGqYD:b-umz0b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b798f072fe7309376fdb5e5c9ffc63691608029/pkg/sql/delegate/show_jobs.go#L66)):*
> ```Go
> 	sqlStmt := fmt.Sprintf("%s %s %s", selectClause, whereClause, orderbyClause)
> 	if n.Block {
> 		// The AutoSpanConfigReconciliation job is never meant to complete so we
> ```

s/never meant/not meant
s/via the WHERE//
___
*[pkg/sql/delegate [...]

2021-08-09 18:46 UTC, ajwerner reviewed
very fast first pass

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MggE2uy1vxAcUbUbl1D:b9nbxwg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggDhITE15SiArx8nz4:-MggDhITE15SiArx8nz5:b-mb7vkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L29)):*
> ```Go
> 
> // Manager is responsible for ensuring that only one (and only one) span config
> // reconciliation job is ever created. It also provides the job with all
> ```

I don't think `is ever created` is the right language. I would think instead it should be something like, is ever running.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggDrum0MtbmEeh_Fbm:-MggDrum0MtbmEeh_Fbn:b-6shjpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L83)):*
> ```Go
> 	}
> 
> 	var startableJob *jobs.StartableJob
> ```

I don't think `StartableJob` is what you're looking for. It's a bit of a hack to get some output into the caller's goroutine. I think you just want a regular ol' job. 


<!-- Sent from Reviewable.io -->

2021-08-09 19:28 UTC, nvanbenschoten reviewed
Things mostly look good. I found myself agreeing with all of Irfan's comments and left a few of my own. It's exciting to see this!

> Reviewed 5 of 5 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MggNHwIACXyoUZd_rHO:b-5jgbus)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @irfansharif)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggKNMYD45_sjpj-Rie:-MggKNMZAoO9T473Y-lQ:b4zd0ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L64)):*
> ```Go
> // iff it hadn't been created already.
> func (m *Manager) StartJobIfNoneExists(ctx context.Context) {
> 	_ = m.stopper.RunAsyncTask(ctx, "create-and-start-reconciliation-job", func(ctx context.Context) {
> ```

Out of curiosity, is there a benefit to pulling all of `createAndStartJobIfNoneExist` into an async task instead of just the job in cases where it doesn't yet exist? I don't think there's a performance concern here, and it's usually easier to use an API that is synchronous for as long as possible. Irfan's comment on the test demonstrates this.

EDIT: beyond what I said here, if you pushed the async part back, you could also return a bool indicating whether the job started or not. This would make testing a breeze compared to what you're doing now.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggM4Aq8y4IVOPhxv7S:-MggM4Aq8y4IVOPhxv7T:b41azd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L122)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn,
> ) (exists bool, _ error) {
> 	const stmt = `
> ```

This query is transactional all the way down to the scan of `system.jobs`, right? I belive so based on a reading of `crdbInternalJobsTable`, but we should confirm, because, without that, the transaction in `createAndStartJobIfNoneExist` isn't enough to provide mutual exclusion and guarantee only one job running at a time.

Is this worth a test? For instance, you could spin up two calls to `createAndStartJobIfNoneExist`, let both get past this point and block in a testing hook, then let them proceed and assert that only one succeeds and the other txn restarts and notices the job. I guess what I'm asking for is a more deterministic version of `TestManagerJobCreation` that doesn't rely on a lucky race to reveal bugs.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggL4SA7cKMpDc5g7Fz:-MggL4SBCNU_F0Z6l24U:b-ugnbqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L126)):*
> ```Go
>          SELECT job_id
>            FROM [SHOW AUTOMATIC JOBS]
>           WHERE job_type = 'AUTO SPAN CONFIG RECONCILIATION'
> ```

Do we want to hard code this 'AUTO SPAN CONFIG RECONCILIATION' string? Should it come from a const defined somewhere?
___
*[pkg/sql/planner.go, line 542 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggJMpF6k2LfttAeOJ_:-MggJMpF6k2LfttAeOJa:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/sql/planner.go#L542)):*
> ```Go
> }
> 
> // SpanConfigReconciliationJobDeps returns the spanconfig.ReconciliationJobDeps
> ```

nit: missing period.
___
*[pkg/sql/delegate/show_jobs.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggGhwx4NMxR6zswC6c:-MggGhwy9tMV4vkPHjHT:b-yqviog) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b798f072fe7309376fdb5e5c9ffc63691608029/pkg/sql/delegate/show_jobs.go#L43)):*
> ```Go
> 		// Display all [only automatic] jobs without selecting specific jobs.
> 		if n.Automatic {
> 			typePredicate = fmt.Sprintf("job_type = '%s' OR job_type = '%s'",
> ```

Is now the time to abstract this by pulling out some kind of `jobspb.AutomaticJobs` static array?

Even if not, use `IN` here and `NOT IN` below to make this a little harder to get wrong.
___
*[pkg/sql/delegate/show_jobs.go, line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfWMfE9IrcGkX-uvay:-MggHZtV5kzTeCl8YZml:b-6yfg3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b798f072fe7309376fdb5e5c9ffc63691608029/pkg/sql/delegate/show_jobs.go#L67)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I'm surprised we need this. What do you mean by not having control over what filter is being applied first? We're filtering out the automatic jobs in the subquery -- aren't we guaranteed to never see them here? Unless the user's trying SHOW AUTOMATIC JOBS WHEN COMPLETE, but even then -- do we want to be smart about it here and filter out an automatic job?
</blockquote></details>

I had the same question. Isn't the filter above sufficient?
___
*[pkg/sql/logictest/testdata/logic_test/auto_span_config_reconciliation_job, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggJW0w679ML5Nk5vDo:-MggJW0w679ML5Nk5vDp:bsr7v7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/sql/logictest/testdata/logic_test/auto_span_config_reconciliation_job#L20)):*
> ```
> 
> # Ensure that the job is not cancelable.
> statement error not cancelable
> ```

Is there a pgcode attached to this?


<!-- Sent from Reviewable.io -->

2021-08-12 00:57 UTC, arulajmani reviewed
RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MgrrJUIDtEn_nJDsgxS:by76qkj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-MgrYfSF19kTM6wLXLyJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Why are we disabling the span config manager in this test? Maybe add an inline comment.
</blockquote></details>

Done.
___
*[pkg/server/admin_test.go, line 1437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRJMU8QEG7wtmeeER:-MgrXv599B8cxI_t-CkU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/admin_test.go#L1437)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Ditto. Out of curiosity -- is there anything else that's non-invasive-ish that we can do to generalize these tests to not need to use this knob?
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRjBE6tu7EtSmCGBq:-Mgr_vZM2sVOFuTWTOVT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/server_sql.go#L804)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Add some commentary here explaining how+why these things are stitched together.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 17 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfW48GCvgOkRrXXOKi:-Mgrb_Z0D7vwnawBQ2pM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfig.go#L17)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

If you're making mention of future interfaces here, add some additional commentary. This is not providing the most helpful context I think.
</blockquote></details>

Done.
___
*[pkg/spanconfig/testing_knobs.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRvly-l-m4BKo7kLr:-MgqK3yIDwKPVEbDdoGH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L18)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Add a comment, mention it's the auto reconciliation job that's not being created.
</blockquote></details>

Done.
___
*[pkg/spanconfig/testing_knobs.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfS4yP37o4BpBsS-28:-MgqK057AaYwkjxd_Eu-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L24)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

// ModuleTestingKnobs is part of the base.ModuleTestingKnobs interface.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfTVxM0NLx7b3cENoZ:-MgphFQn3cTisrBM_IXT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L28)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"that one (and only one)"
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggDhITE15SiArx8nz4:-MgphDNJ78fI4otqwPkD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L29)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think `is ever created` is the right language. I would think instead it should be something like, is ever running.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfTlwFC3K1ifDQtnmV:-MgphOJa84hYnUwfkDPa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L41)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Drop the "reconciliation manager" language, I think this was a remnant from our earlier package structure with the zcfgreconciler guy.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 61 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfU0Gr2xAPkxWN0Ql4:-MgqKSmS-KRS66DiXAhl:b7awl2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L61)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

s/Exists/Exist?
</blockquote></details>

"job" is singular, so it should be exists right?
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggKNMYD45_sjpj-Rie:-MgrnnGm5eyqsyCyA3Kj:b-i9ihoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, is there a benefit to pulling all of `createAndStartJobIfNoneExist` into an async task instead of just the job in cases where it doesn't yet exist? I don't think there's a performance concern here, and it's usually easier to use an API that is synchronous for as long as possible. Irfan's comment on the test demonstrates this.

EDIT: beyond what I said here, if you pushed the async part back, you could also return a bool indicating whether the job started or not. This would make testing a breeze compared to what you're doing now.
</blockquote></details>

I changed a few things around here, most notably I switched from a `StartableJob` to a regular job based on Andrew's comment. There isn't much to do after we've written to `system.jobs` for regular jobs. I'm notifying the registry to pick this new job up but from what I understand this is merely a nudge and not required. 

This `NotifyToAdoptJobs` isn't blocking right now but it could be in the future as it sends things on an unbuffered channel. As such, I have this part in an async task for now. Is this overkill? Should I just make the whole thing synchronous? 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggM4Aq8y4IVOPhxv7S:-Mgqb8KeCJxY5XH9sV7P:b-avnj52) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This query is transactional all the way down to the scan of `system.jobs`, right? I belive so based on a reading of `crdbInternalJobsTable`, but we should confirm, because, without that, the transaction in `createAndStartJobIfNoneExist` isn't enough to provide mutual exclusion and guarantee only one job running at a time.

Is this worth a test? For instance, you could spin up two calls to `createAndStartJobIfNoneExist`, let both get past this point and block in a testing hook, then let them [...]

2021-08-12 20:30 UTC, ajwerner reviewed
I think we need to get some people in a room and make decisions on how to deal with this job stuff.

2021-08-12 20:30 UTC, ajwerner commented on pkg/spanconfig/spanconfigjob/job.go
> +	return errors.AssertionFailedf("span config reconciliation job can never fail or be canceled")
💵 says we get this sentry report before the end of 2022.

2021-08-12 20:30 UTC, ajwerner commented on pkg/spanconfig/spanconfigjob/job.go
> +	return errors.AssertionFailedf("span config reconciliation job can never fail or be canceled")
actually, I don't know how these things end up getting reported. Maybe no report because the jobs system doesn't send them.

2021-08-12 20:30 UTC, ajwerner commented on pkg/spanconfig/spanconfigmanager/manager.go
> +		exists, err := m.checkIfReconciliationJobExists(ctx, txn)
@Azhng has a thing for this coming in https://github.com/cockroachdb/cockroach/pull/68434/, see `RunningJobExists`.

2021-08-12 20:30 UTC, ajwerner commented on pkg/server/server_sql.go
> +	_ = s.execCfg.StartSpanConfigReconciliationJobHook(ctx)
this is a blocking call, I don't know that it belongs in preStart here.

2021-08-12 20:30 UTC, ajwerner commented on pkg/spanconfig/spanconfigmanager/manager.go
> +func (m *Manager) StartJobIfNoneExists(ctx context.Context) bool {
I'm not sure that this synchronous method is really that helpful. What if we just had this thing sit in a loop and periodically, like every hour or something (after startup) go and run the check. If you need a synchronous hook, you can have it poke the loop or something. My guess is that the synchronous thing is handy in testing. Something smells about it being called in preStart.

2021-08-12 20:30 UTC, ajwerner commented on pkg/spanconfig/spanconfigjob/job.go
> +
Is the idea that the implementation of reconciliation will happen here or is is the idea that there will be another injected piece of machinery that gets invoked?

2021-08-12 20:30 UTC, ajwerner commented on pkg/server/server_sql.go
> +	_ = s.execCfg.StartSpanConfigReconciliationJobHook(ctx)
Also, doesn't this need version gating? We can't run this until after we've activated a version where all of the nodes know about this job type.

2021-08-13 15:40 UTC, nvanbenschoten reviewed
> Reviewed 2 of 26 files at r3, 24 of 25 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @RichardJCai)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-Mh-4aN-B5pVNOKB3jYd:b-leuav3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What do you mean by "noise" here? Does the test fail if we don't disable the job creation?
___
*[pkg/jobs/jobspb/wrap.go, line 69 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-4oVn1mjxEJ-G3d-Y:-Mh-4oVo7qNjXwqprSVy:b8ld57j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/jobs/jobspb/wrap.go#L69)):*
> ```Go
> 
> // AutomaticJobTypes is a list of automatic job types that currently exist.
> var AutomaticJobTypes = [2]Type{TypeAutoCreateStats, TypeAutoSpanConfigReconciliation}
> ```

nit: `s/2/.../` to avoid needing to update this length each time a new element is added.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MggM4Aq8y4IVOPhxv7S:-Mh-8oEC99CAyAxAd9p4:b73usdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager.go#L122)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I changed `TestManagerJobCreation` to look like what you described above. Let me know what you think 
</blockquote></details>

I think it looks good. Thanks.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-7xSW4CR3Zh4HgYHu:b3goral) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not sure that this synchronous method is really that helpful. What if we just had this thing sit in a loop and periodically, like every hour or something (after startup) go and run the check. If you need a synchronous hook, you can have it poke the loop or something. My guess is that the synchronous thing is handy in testing. Something smells about it being called in preStart.
</blockquote></details>

The synchronous nature of this method came from a previous comment. This was async back in r2, though still only single-shot. If we want to run this work inside of an async loop then I'd encourage us to push that outside of this API. Interfaces that are internally asynchronous are harder to test and harder to reason about. It means that we can't give any information back to the caller, like whether or not the job started. If a caller wants to call a synchronous method in an async task, it is free to.
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-7_ET5MZED8_1fe4l:-Mh-7_EU9ynaXqgeRLZF:b-7frpqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager_test.go#L71)):*
> ```Go
> 				require.Equal(t, job.Payload().Description, "reconciling span configurations")
> 			},
> 			ManagerAfterCheckedReconciliationJobExistsInterceptor: func(exists bool) {
> ```

We're going to call this twice during the first attempt, right? Because we expect a transaction retry. If so, we should assert that this is called exactly 3 times and that the first two passes `exists=false` and the third passes `exists=true`.
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-6Xfs4s8vTYfYYJKv:-Mh-6Xfs4s8vTYfYYJKw:b-4k4svg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager_test.go#L101)):*
> ```Go
> 		// Only try to start the job once the main testing goroutine has reached the
> 		// blocker and is waiting.
> 		for {
> ```

This loop would be better served using a channel or a condition variable. Some way to avoid spinning on the mutex.

Maybe this should `<-blocker` and the other goroutine in the hook should `close(blocker)` inside of a `sync.Once`.
___
*[pkg/sql/delegate/show_jobs.go, line 59 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-90Z01NG7hAhUWMIq:-Mh-90Z01NG7hAhUWMIr:b-mkblpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/sql/delegate/show_jobs.go#L59)):*
> ```Go
> 				predicate.WriteString("'")
> 			}
> 			predicate.WriteString(")")
> ```

Can we replace some of these single-character strings with `predicate.WriteByte`? That is marginally more efficient.


<!-- Sent from Reviewable.io -->

2021-08-13 15:44 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-Ajnu7eI5JudNy4NR:b33tg1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The synchronous nature of this method came from a previous comment. This was async back in r2, though still only single-shot. If we want to run this work inside of an async loop then I'd encourage us to push that outside of this API. Interfaces that are internally asynchronous are harder to test and harder to reason about. It means that we can't give any information back to the caller, like whether or not the job started. If a caller wants to call a synchronous method in an async task, it is free to.
</blockquote></details>

I get the desire to have the logic be implemented with a synchronous call somewhere for the reasons you indicate. What I'm pushing back against is the idea that we want that synchronous call to happen during server startup 100% of the time. Do we really want to scan the jobs table synchronously on server startup?


<!-- Sent from Reviewable.io -->

2021-08-13 15:51 UTC, nvanbenschoten reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-Bny6A6cMz7RcPfAe:b-dtx6lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I get the desire to have the logic be implemented with a synchronous call somewhere for the reasons you indicate. What I'm pushing back against is the idea that we want that synchronous call to happen during server startup 100% of the time. Do we really want to scan the jobs table synchronously on server startup?
</blockquote></details>

What is the concern with this running on server startup? SQL migrations also run synchronously on server startup. Do you expect this to be expensive because we don't index on `job_type` so this results in a full table scan? If so, that's a fair concern. And beyond this, if we need to periodically check if the job exists, then we'll need some task to do that anyway, so there's no need to also perform this synchronously at startup.


<!-- Sent from Reviewable.io -->

2021-08-13 16:05 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-EYBc8Bcqpvpxa94t:bpvldaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What is the concern with this running on server startup? SQL migrations also run synchronously on server startup. Do you expect this to be expensive because we don't index on `job_type` so this results in a full table scan? If so, that's a fair concern. And beyond this, if we need to periodically check if the job exists, then we'll need some task to do that anyway, so there's no need to also perform this synchronously at startup.
</blockquote></details>

The scan concerns me, yes. Imagine that the jobs table is unavailable because this node cannot start up. I guess we have that problem for startup migrations too. Fortunately those things are (slowly) on their way out.  I filed https://github.com/cockroachdb/cockroach/issues/68896 to index the type because I think generally it's a good idea. Whether we like it or not, there's a movement coming in the 22.1 time frame to cut the number of synchronous, global round trips during sql server startup to a minimum. I'm trying to get ahead of that.

I think having a periodic task to create the job is a good idea. I have fears of the job failing for various reasons and I have fears about people deleting it and everything breaking. 


<!-- Sent from Reviewable.io -->

2021-08-13 16:45 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/server/server_sql.go, line 1019 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VC0-r5-1019:-Mh-OiL18wEKJ9YsdBsJ:basdhui) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/server_sql.go#L1019)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Also, doesn't this need version gating? We can't run this until after we've activated a version where all of the nodes know about this job type. 
</blockquote></details>

I was wrong. `preStart` is effectively start for the sql server. 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-O-xwBMhBobjH1Nin:b6uwz3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The scan concerns me, yes. Imagine that the jobs table is unavailable because this node cannot start up. I guess we have that problem for startup migrations too. Fortunately those things are (slowly) on their way out.  I filed https://github.com/cockroachdb/cockroach/issues/68896 to index the type because I think generally it's a good idea. Whether we like it or not, there's a movement coming in the 22.1 time frame to cut the number of synchronous, global round trips during sql server startup to a minimum. I'm trying to get ahead of that.

I think having a periodic task to create the job is a good idea. I have fears of the job failing for various reasons and I have fears about people deleting it and everything breaking. 
</blockquote></details>

Err ignore me about the startup, this is after we start up the kvserver. 


<!-- Sent from Reviewable.io -->

2021-08-13 17:56 UTC, irfansharif reviewed
Is the periodic job creation attempt the remaining blocker for this PR?

> Reviewed 1 of 26 files at r3, 12 of 25 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-Mh-dUzL7rSMOuXWy5qt:bxr2qm5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @nvanbenschoten, and @RichardJCai)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-Mh-_sgl5IShmIpNSv3F:b81hdo3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What do you mean by "noise" here? Does the test fail if we don't disable the job creation?
</blockquote></details>

Yea, I'm still not sure why we need it (if we do).
___
*[pkg/server/admin_test.go, line 1418 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-UXuy8GLliPgi7iUp:-Mh-UXuzCZX0sHUCvKzK:b-ejo29) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/admin_test.go#L1418)):*
> ```Go
> 	rows := db.Query(
> 		t,
> 		fmt.Sprintf(
> ```

Do we need the fmt.Sprintf? db.Query can parametrize the query string with arguments.
___
*[pkg/server/admin_test.go, line 1508 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-UuwkAujV2imO1Kx1:-Mh-UuwkAujV2imO1Kx2:b-cikhzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/admin_test.go#L1508)):*
> ```Go
> 		{
> 			"jobs",
> 			append(append([]int64{5, 4, 3, 2, 1}, existingSucceededIDs...), existingRunningIDs...),
> ```

This is "all jobs" right? Could instead define a expectedIDs = existingSucceededIDs + existingRunningIDs above.
___
*[pkg/server/server_sql.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRjBE6tu7EtSmCGBq:-Mh-W8Nt1R6OQuBH7q4W:bxlgplw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/server_sql.go#L804)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"Instantiate a span config manager; it exposes a hook to idempotently create the span config reconciliation job and captures all relevant job dependencies."
___
*[pkg/server/server_sql.go, line 1019 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VC0-r5-1019:-Mh-VieiAchecCsvLlO4:bxztoji) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/server_sql.go#L1019)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was wrong. `preStart` is effectively start for the sql server. 
</blockquote></details>

Looks like it fired up an async task internally, though not obvious looking at the signature. +1 to pulling up the async task + forever attempt to keep creating using a synchronous API here at the caller.
___
*[pkg/spanconfig/testing_knobs.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRvly-l-m4BKo7kLr:-Mh-azuK8REr-Z-JoYWE:b-1oxoog) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L18)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"ManagerDisableJobCreation disables creating the auto span config reconciliation job."
___
*[pkg/spanconfig/spanconfigjob/job.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCA-r5-36:-Mh-bkxO3fqc5uQMkeET:b-ndy9qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigjob/job.go#L36)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is the idea that the implementation of reconciliation will happen here or is is the idea that there will be another injected piece of machinery that gets invoked?
</blockquote></details>

The latter, one of the job dependencies will be simply emitting span config changes it observes through SQL. The job exists to simply issue RPCs to KV propagating those changes. It'll also checkpoint internally to make sure when resumed, it's doing the full sync.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh-ZTh29wICeWqZen7T:b-janfbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Err ignore me about the startup, this is after we start up the kvserver. 
</blockquote></details>

Are you saying that we want one instance of the job running at a time, rather than only one job being created that runs forever? Makes sense, a small enough change, but mind explaining why that's preferable? Is it just safeguarding in case we accidentally write code resulting in the forever job failing/entering a terminal state, or us somehow purging the job away? Cool -- makes it a lot less fragile. We did in fact have bugs in our prototype where we returned errors in the job, and this makes it a lot more robust.
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfVLFH4mE_lBOSS5lQ:-Mh-ckg533430hcPsump:b-8qvfcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager_test.go#L71)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Changed this test around to be a bit more deterministic, lemme know what you think. 
</blockquote></details>

Now that StartJobIfNoneExists returns whether or not it was a noop, can we simplify the test to check and see that there's only true returned from concurrent attempts? We could then validate by scanning the jobs table to make sure only one instance exists. I think it should obviate the need for the new testing interceptor and all these extra channels, etc.


<!-- Sent from Reviewable.io -->

2021-08-13 18:01 UTC, ajwerner reviewed
> Is the periodic job creation attempt the remaining blocker for this PR?

Also version gating. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-Mh-f6usDERcZsgFUvms:bgz57z4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigjob/job.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCA-r5-36:-Mh-eGXU4KVgALM2dK6p:b-o5wzs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigjob/job.go#L36)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

The latter, one of the job dependencies will be simply emitting span config changes it observes through SQL. The job exists to simply issue RPCs to KV propagating those changes. It'll also checkpoint internally to make sure when resumed, it's doing the full sync.
</blockquote></details>

Okay, I'll wait for the next PR to talk about what functionality lives where. 


<!-- Sent from Reviewable.io -->

2021-08-13 23:39 UTC, arulajmani reviewed
Added a version gate. I also moved the call to `StartJobIfNoneExists` into an async task during `preStart`. In addition to the first time, this async task will periodically try and create the job in case, for some reason, it has errored out and ended up in the "failed" state. I've added a cluster setting that controls this interval which defaults to 10 minutes.

RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-Mh0rlqa2Ynioz8Kx63w:b-mz58lh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-Mh-nhI1CWzEsE8EjVDG:b9gagis) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Yea, I'm still not sure why we need it (if we do).
</blockquote></details>

This, and other tests in this file, directly modify `system.jobs` and then make assertions over the contents of it. For example, `TestRegistryGCPagination` ensures that old terminal jobs are gc-ed away by asserting no entries are left in `system.jobs`. I could modify the test to add a special case for this auto span config reconciliation job or change the calls to use `SHOW JOBS` instead of querying `system.jobs` directly, but I prefer disabling the job entirely considering these tests shouldn't need to bother with the nuances of this auto job. 
___
*[pkg/server/admin_test.go, line 1418 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-UXuy8GLliPgi7iUp:-Mh01sGr6uo67Fn4R0GS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/admin_test.go#L1418)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Do we need the fmt.Sprintf? db.Query can parametrize the query string with arguments.
</blockquote></details>

Done.
___
*[pkg/server/admin_test.go, line 1508 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-UuwkAujV2imO1Kx1:-Mh01s09EzYkTH4WUDo4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/server/admin_test.go#L1508)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This is "all jobs" right? Could instead define a expectedIDs = existingSucceededIDs + existingRunningIDs above.
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 804 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRjBE6tu7EtSmCGBq:-Mh0mZRK0g8nE9IkgIuG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/server/server_sql.go#L804)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"Instantiate a span config manager; it exposes a hook to idempotently create the span config reconciliation job and captures all relevant job dependencies."
</blockquote></details>

Done.
___
*[pkg/spanconfig/testing_knobs.go, line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfRvly-l-m4BKo7kLr:-Mh0gOn45Wcx1t0DPipl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/testing_knobs.go#L18)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

"ManagerDisableJobCreation disables creating the auto span config reconciliation job."
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigjob/job.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCA-r5-36:-Mh0qh7b8yrVbZF4qohu:bt9th92) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigjob/job.go#L36)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Okay, I'll wait for the next PR to talk about what functionality lives where. 
</blockquote></details>

There's a brief teaser on what is to come in `spanconfig.go`, but let's iterate discuss these things on the PRs that actually introduce those interfaces. 
___
*[pkg/spanconfig/spanconfigjob/job.go, line 43 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCA-r5-43:-Mh0pAGp1GHJrliu2wWI:be2l6su) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigjob/job.go#L43)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

actually, I don't know how these things end up getting reported. Maybe no report because the jobs system doesn't send them.
</blockquote></details>

:sweat_smile: 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-65:-Mh0r6Bq7KhDajcVWJ4u:bkt0b0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L65)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Are you saying that we want one instance of the job running at a time, rather than only one job being created that runs forever? Makes sense, a small enough change, but mind explaining why that's preferable? Is it just safeguarding in case we accidentally write code resulting in the forever job failing/entering a terminal state, or us somehow purging the job away? Cool -- makes it a lot less fragile. We did in fact have bugs in our prototype where we returned errors in the job, and this makes it a lot more robust.
</blockquote></details>

I'm leaving this as is and making the caller of this method (in `preStart`) do so in an async task. This async task will also be responsible for trying to create this job periodically (in case, somehow, the job transitions to the "failed" state). 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgNjHYyVGHkrm645VCD-r5-94:-Mh0qMik6NsvRvMg8-BT:bbm9d8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager.go#L94)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

@Azhng has a thing for this coming in https://github.com/cockroachdb/cockroach/pull/68434/, see `RunningJobExists`. 
</blockquote></details>

Nice, I added a TODO to use that once his PR lands.
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfVLFH4mE_lBOSS5lQ:-Mh0qyA09Pi6lOkw-3Z4:bmrbtgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/spanconfig/spanconfigmanager/manager_test.go#L71)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Now that StartJobIfNoneExists returns whether or not it was a noop, can we simplify the test to check and see that there's only true returned from concurrent attempts? We could then validate by scanning the jobs table to make sure only one instance exists. I think it should obviate the need for the new testing interceptor and all these extra channels, etc.
</blockquote></details>

Discussed offline, we're keeping it as is. 
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-7_ET5MZED8_1fe4l:-Mh0qUG8257cr1_r2W4M:bxdewo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager_test.go#L71)):*
<details><summary><i>Previously,  [...]

2021-08-16 14:40 UTC, irfansharif approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 12 files at r8, 32 of 32 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhEP13O28EhBky-qzNy:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[-- commits, line 14 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEHscxBrcKyl9IIj-4:-MhEHscxBrcKyl9IIj-5:b-wt2x4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/-- commits#L14)):*
Type in commit message (idempootently).
___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-MhEILUvEXXFLGL9Asho:bhvrblq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This, and other tests in this file, directly modify `system.jobs` and then make assertions over the contents of it. For example, `TestRegistryGCPagination` ensures that old terminal jobs are gc-ed away by asserting no entries are left in `system.jobs`. I could modify the test to add a special case for this auto span config reconciliation job or change the calls to use `SHOW JOBS` instead of querying `system.jobs` directly, but I prefer disabling the job entirely considering these tests shouldn't need to bother with the nuances of this auto job. 
</blockquote></details>

It's worth improving the comment here to say as much (and capitalize "disable").
___
*[pkg/server/server_sql.go, line 1037 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEMNOpBGkxUlzdAlel:-MhEMNOpBGkxUlzdAlem:b6f995w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1037)):*
> ```Go
> 			nextTick := timeutil.Now()
> 			for {
> 				nextTickCh := time.After(nextTick.Sub(timeutil.Now()))
> ```

Use time.NewTicker instead. Also, should we attach a SetOnChange hook on the cluster setting to attempt job creation when changed? If the default duration is long, it could come in handy when trying to quickly bounce it. For upgrading clusters it's possible for the reconciliation job to only going to started 10m (or whatever the setting ends up being) after the upgrade has finalized. Is that what we want? I'm not sure what we could do -- maybe a similar cluster setting changed hook for the version setting? Or maybe a "migration" that also tries to idempotently call into this job creation hook?
___
*[pkg/server/server_sql.go, line 1043 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEKqI4838bcNVbnONX:-MhEKqI4838bcNVbnONY:boimfo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1043)):*
> ```Go
> 					// cluster version allows for it.
> 					if s.execCfg.Settings.Version.IsActive(ctx, clusterversion.AutoSpanConfigReconciliationJob) {
> 						_ = s.execCfg.StartSpanConfigReconciliationJobHook(ctx)
> ```

Return + log the error.
___
*[pkg/server/server_sql.go, line 1051 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEJqHCBEED8AhwIPIj:-MhEJqHCBEED8AhwIPIk:b-7b4fth) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1051)):*
> ```Go
> 				}
> 				nextTick = nextTick.Add(
> 					spanconfig.CheckAndStartReconciliationJobInterval.Get(&s.execCfg.Settings.SV),
> ```

Given that this cluster setting is only used in this package, should we move it here instead? Seems like a property of the SQL server, rather than the span config manager.
___
*[pkg/server/server_sql.go, line 1053 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEKsdBE_SBdRK9TQjE:-MhEKsdBE_SBdRK9TQjF:b-spewnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1053)):*
> ```Go
> 					spanconfig.CheckAndStartReconciliationJobInterval.Get(&s.execCfg.Settings.SV),
> 				)
> 				log.Infof(
> ```

Remove this log message.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 64 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhELNJUAtHATyyqH9A3:-MhELNJUAtHATyyqH9A4:b89glaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/spanconfig/spanconfigmanager/manager.go#L64)):*
> ```Go
> 	started, err := m.createAndStartJobIfNoneExists(ctx)
> 	if err != nil {
> 		log.Errorf(ctx, "error starting auto span config reconciliation job: %v", err)
> ```

Return the error to the caller now that this isn't firing off an async task.


<!-- Sent from Reviewable.io -->

2021-08-16 15:44 UTC, ajwerner requested changes
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhEbo3D-lpJQONoYYil:bs3whzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	// Start a background task that starts the auto span config reconciliation job.
> 	// The background task also periodically (as dictated by a cluster setting)
> 	// checks to ensure that the job exists. We don't expect this to happen, but
> 	// if does, we want to start it again.
> 	if err := s.stopper.RunAsyncTask(ctx, "start-span-config-reconciliation-job",
> ```
</details>

This feels out of place here. Why burden the server package with this logic? Can you instead hide this behind a `Start` method on the `Manager` struct.
___
*[pkg/server/server_sql.go, line 1037 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEMNOpBGkxUlzdAlel:-MhEcF7o3FCnEA-ZOJ1f:b-m9n7a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1037)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Use time.NewTicker instead. Also, should we attach a SetOnChange hook on the cluster setting to attempt job creation when changed? If the default duration is long, it could come in handy when trying to quickly bounce it. For upgrading clusters it's possible for the reconciliation job to only going to started 10m (or whatever the setting ends up being) after the upgrade has finalized. Is that what we want? I'm not sure what we could do -- maybe a similar cluster setting changed hook for the version setting? Or maybe a "migration" that also tries to idempotently call into this job creation hook?
</blockquote></details>

I prefer a `timeutil.Timer` over either of those. It's a bit bulkier but strictly more flexible than either. 
___
*[pkg/server/server_sql.go, line 1051 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEJqHCBEED8AhwIPIj:-MhEcQVo75QH0MyTGDHK:baob84u) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1051)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Given that this cluster setting is only used in this package, should we move it here instead? Seems like a property of the SQL server, rather than the span config manager.
</blockquote></details>

I feel more or less the opposite. Can we stop referencing it in the server package?


<!-- Sent from Reviewable.io -->

2021-08-16 16:56 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhEqn7GApxlDhaKNscS:bzh03xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// Start a background task that starts the auto span config reconciliation job.
> 	// The background task also periodically (as dictated by a cluster setting)
> 	// checks to ensure that the job exists. We don't expect this to happen, but
> 	// if does, we want to start it again.
> 	if err := s.stopper.RunAsyncTask(ctx, "start-span-config-reconciliation-job",
> ```
This feels out of place here. Why burden the server package with this logic? Can you instead hide this behind a `Start` method on the `Manager` struct.
</blockquote></details>

Maybe I missed something, but from the discussion around synchronous vs. asynchronous API's I was under the impression that we wanted the caller of this method to be responsible for establishing the async task (as opposed to the async task being part of the API). Is that not what we want? 


<!-- Sent from Reviewable.io -->

2021-08-16 17:56 UTC, ajwerner reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhF5KzYA9KSv3iCXVL3:bl8da8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe I missed something, but from the discussion around synchronous vs. asynchronous API's I was under the impression that we wanted the caller of this method to be responsible for establishing the async task (as opposed to the async task being part of the API). Is that not what we want? 
</blockquote></details>

What @nvanbenschoten  said regarding testability was right. You did add a synchronous API. What I'm hanging on isn't how you structure the async part of this, whether it be some function you call or some struct that you start. What I'm hanging on is where that logic lives. The `server` layer here should be an integration and dependency injection layer. It can have business logic, sure, but that business logic should be about setting up the server given the setting, not as much the concerns of some subsystem itself. 

@nvanbenschoten how far off on outlook are we in terms of what this integration should look like?


<!-- Sent from Reviewable.io -->

2021-08-16 20:00 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhFX6_nAhZlh_ipx25Y:b-3ftg6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
> What I'm hanging on isn't how you structure the async part of this, whether it be some function you call or some struct that you start. What I'm hanging on is where that logic lives. 

Maybe I misunderstood the ask to hide this behind a `Start` method on `Manager`. I was assuming that the `stopper.RunAsyncTask` would be part of the `Start` method. Are you instead suggesting putting _just_ the periodic cluster version check + idempotent job queueing in the `Start` method and still calling that here inside `stopper.RunAsyncTask`?  


<!-- Sent from Reviewable.io -->

2021-08-16 20:57 UTC, nvanbenschoten reviewed
> Reviewed 2 of 12 files at r8, 32 of 32 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-MhFdLoE5DCv9XGCN2tr:bimdc8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

It's worth improving the comment here to say as much (and capitalize "disable").
</blockquote></details>

Agreed. Spell that all out. Otherwise, it will be impossible for anyone to ever convince themselves it's safe to remove this knob in the future, even if parts of the system change.
___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhFdu7_02dC6Bkt_myI:b5xqmbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

> What I'm hanging on isn't how you structure the async part of this, whether it be some function you call or some struct that you start. What I'm hanging on is where that logic lives. 

Maybe I misunderstood the ask to hide this behind a `Start` method on `Manager`. I was assuming that the `stopper.RunAsyncTask` would be part of the `Start` method. Are you instead suggesting putting _just_ the periodic cluster version check + idempotent job queueing in the `Start` method and still calling that here inside `stopper.RunAsyncTask`?  
</blockquote></details>

I think what Andrew is saying is that the async task and the business logic of this retry loop should live inside of the `spanconfig` package (or really anywhere else but `server`). We removed the asynchrony from the `Manager.StartJobIfNoneExists` call to make the inner transaction easier to test, but that doesn't mean the retry logic needs to be fully externalized. We just wanted to split out the core logic in `StartJobIfNoneExists` from the task that was orchestrating it. But that orchestration logic still belongs somewhere inside of the `spanconfig` layer.

The way to look at this is that you want to push async processing as far out as possible, but no further.

It would be very reasonable to add a `(*spanconfigmanager.Manager).Start` method that launches an async task and calls `(*spanconfigmanager.Manager).startJobIfNoneExists` in this loop _but then to test_ `startJobIfNoneExists` directly. That's kind of what you originally had, so maybe I should have just advised to you call `createAndStartJobIfNoneExist` directly from your unit tests.
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 101 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-Mh-6Xfs4s8vTYfYYJKv:-MhFhuGL2sFLDLD6Qi2t:b-tnxl80) ([raw file](https://github.com/cockroachdb/cockroach/blob/0db6eceaa1cbfa42678f517e331fda81d03c4cf6/pkg/spanconfig/spanconfigmanager/manager_test.go#L101)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can't use `blocker` because I'm reassigning it to `unblocker` and closing it to signal back to the first goroutine, but I removed this look and replaced it with a different channel. I don't think I need the `sync.Once` either because of the way the test is setup. 
</blockquote></details>

This still seems overly complex to me. First off, why do we need the mutex? Also, the `blocker`/`unblocker`/`isBlocked` stuff is tough to read and reason about. There's too much state. I think I see why you need two channels, but not the third. I imagine this could be simplified with the following sync primitives:
```go
var firstCheck sync.Once
blockFirstC := make(chan struct{})
unblockFirstC := make(chan struct{})

...
ManagerAfterCheckedReconciliationJobExistsInterceptor: func(exists bool) {
    firstCheck.Do(func() {
      close(blockFirstC)
      <-unblockFirstC
    })
}

...
go func() {
    defer wg.Done()
    <-blockFirstC
    ...
    close(unblockFirstC)
}()
```

Also, nit, but consider using `errgroup` and then returning these `t.Errorf` as errors. Then you can `require.NoError(t, wg.Wait())` at the end.


<!-- Sent from Reviewable.io -->

2021-08-18 01:46 UTC, arulajmani reviewed
RFAL! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhLw0ntCgSTzMmD20-8:by76qkj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/jobs/registry_test.go, line 128 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MgfQkAs1NZ6mAO1v4Bh:-MhKsJS-BehIUGBZtMH-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fbea8cd6ba415dc3d96482cd6162bc023afb58/pkg/jobs/registry_test.go#L128)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Agreed. Spell that all out. Otherwise, it will be impossible for anyone to ever convince themselves it's safe to remove this knob in the future, even if parts of the system change.
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 1033 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEbo3D-lpJQONoYYik:-MhLvVfTAqu8hl8w27uV:b-s4i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1033)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think what Andrew is saying is that the async task and the business logic of this retry loop should live inside of the `spanconfig` package (or really anywhere else but `server`). We removed the asynchrony from the `Manager.StartJobIfNoneExists` call to make the inner transaction easier to test, but that doesn't mean the retry logic needs to be fully externalized. We just wanted to split out the core logic in `StartJobIfNoneExists` from the task that was orchestrating it. But that orchestration logic still belongs somewhere inside of the `spanconfig` layer.

The way to look at this is that you want to push async processing as far out as possible, but no further.

It would be very reasonable to add a `(*spanconfigmanager.Manager).Start` method that launches an async task and calls `(*spanconfigmanager.Manager).startJobIfNoneExists` in this loop _but then to test_ `startJobIfNoneExists` directly. That's kind of what you originally had, so maybe I should have just advised to you call `createAndStartJobIfNoneExist` directly from your unit tests.
</blockquote></details>

I confused myself a bit here, my bad. I think I have it now and this thing looks much nicer! Lemme know what y'all think
___
*[pkg/server/server_sql.go, line 1037 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEMNOpBGkxUlzdAlel:-MhLr5HV2dVBlLpxjKEk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1037)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I prefer a `timeutil.Timer` over either of those. It's a bit bulkier but strictly more flexible than either. 
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 1043 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEKqI4838bcNVbnONX:-MhLrCEq3dvoGmOlYxBq:bxz7z2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1043)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Return + log the error.
</blockquote></details>

I don't think we want to return here, do we? We probably want to try again instead of turning the whole subsystem off, right?
___
*[pkg/server/server_sql.go, line 1051 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEJqHCBEED8AhwIPIj:-MhLrOlO3RbBs0oeX8oK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1051)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I feel more or less the opposite. Can we stop referencing it in the server package?
</blockquote></details>

Done.
___
*[pkg/server/server_sql.go, line 1053 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhEKsdBE_SBdRK9TQjE:-MhKswWd48jsy3ZIWbZH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/server/server_sql.go#L1053)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Remove this log message.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 64 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhELNJUAtHATyyqH9A3:-MhLrULR03v90zsCWVHM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5d1d74a0dfa4d86214a941d28a6396b2d970f11/pkg/spanconfig/spanconfigmanager/manager.go#L64)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Return the error to the caller now that this isn't firing off an async task.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-18 04:46 UTC, nvanbenschoten approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 34 files at r10, 32 of 32 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhM_5Kk8N1QOieU-qSF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 85 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhMZFM33JwwMMIvOF6z:-MhMZFM33JwwMMIvOF7-:b-u8nv6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e72733765d21f6b81d65ac7f1c036bc1458bf48/pkg/spanconfig/spanconfigmanager/manager.go#L85)):*
> ```Go
> 
> 			lastChecked := time.Time{}
> 			timer := timeutil.NewTimer()
> ```

`defer timer.Stop()`
___
*[pkg/spanconfig/spanconfigmanager/manager_test.go, line 81 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhMZMTyDjxPJ0rz4JNk:-MhMZMTyDjxPJ0rz4JNl:b-6g0cb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e72733765d21f6b81d65ac7f1c036bc1458bf48/pkg/spanconfig/spanconfigmanager/manager_test.go#L81)):*
> ```Go
> 					close(isBlocked)
> 					<-unblocker
> 				} else {
> ```

This else branch seems redundant. It's also pretty subtle that the `count` changes between when we first compare/increment and later on. Did you consider a structure along the lines of:
```go
count++
curCount := count
if curCount {
    close(isBlocked)
    <-unblocker
}
...
if curCount <= 2 {
    ...
```


<!-- Sent from Reviewable.io -->

2021-08-18 13:46 UTC, ajwerner reviewed
Just the stuff Nathan pointed out and nits. Also needs a rebase. It will be ready to go in today. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhOVagrAl9JqxwCJToQ:b-2bminf)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, and @RichardJCai)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 74 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhOV2Yc-kTc2haVKayP:-MhOV2Yd4Y5zrgu84MzQ:bp9qaoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e72733765d21f6b81d65ac7f1c036bc1458bf48/pkg/spanconfig/spanconfigmanager/manager.go#L74)):*
> ```Go
> func (m *Manager) Start(ctx context.Context) error {
> 	return m.stopper.RunAsyncTask(ctx, "start-span-config-reconciliation-job",
> 		func(ctx context.Context) {
> ```

nit: buy yourself two layers of indentation by making a method on the `Manager` called `run` that takes a context and just pass it here. 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 178 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhOVQMCCNL29nb9Khc2:-MhOVQMCCNL29nb9Khc3:bwq017p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e72733765d21f6b81d65ac7f1c036bc1458bf48/pkg/spanconfig/spanconfigmanager/manager.go#L178)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	stmt := fmt.Sprintf(`
> SELECT EXISTS(
>          SELECT job_id
>            FROM [SHOW AUTOMATIC JOBS]
>           WHERE job_type = '%s'
> 					AND status IN ('%s', '%s', '%s')
>        );
> `, jobspb.TypeAutoSpanConfigReconciliation.String(), jobs.StatusRunning, jobs.StatusPaused, jobs.StatusPending)
> ```
</details>

for the statuses how about use `jobs.NonTerminalStatusTupleString`?


<!-- Sent from Reviewable.io -->

2021-08-18 15:28 UTC, arulajmani reviewed
Rebased. I was speaking to @irfansharif offline and he mentioned that instead of defining a `spanconfig.Manager` interface we should just use the `spanconfigmanager.Manager` struct in `server_sql.go` -- the new revision includes that change as well. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhOrrti6-bFhQPuy86_:bwmifrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @arulajmani, @Azhng, @irfansharif, @nvanbenschoten, and @RichardJCai)



<!-- Sent from Reviewable.io -->

2021-08-18 15:34 UTC, ajwerner approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, on to the meatier PRs

>  I was speaking to @irfansharif offline and he mentioned that instead of defining a spanconfig.Manager interface we should just use the spanconfigmanager.Manager struct in server_sql.go -- the new revision includes that change as well.

I like that very much. 

> Reviewed 1 of 35 files at r13, 7 of 33 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-:-MhOsXfd8O640XSGvgNL:btn9s5e)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/spanconfig/spanconfig.go, line 31 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhOsmWN1N87ZoJYsWQC:-MhOsmWN1N87ZoJYsWQD:b3htqhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d5b1fbff2b78ff1873c0f0d39fb5e0c386f6a7/pkg/spanconfig/spanconfig.go#L31)):*
> ```Go
> 
> type Manager interface {
> 	Start(ctx context.Context) error
> ```

Now this can be removed from the interface. 
___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 188 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhOt8yy8yd9asQmB6dM:-MhOt8yy8yd9asQmB6dN:b2jixta) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d5b1fbff2b78ff1873c0f0d39fb5e0c386f6a7/pkg/spanconfig/spanconfigmanager/manager.go#L188)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 
> SELECT EXISTS(
>          SELECT job_id
>            FROM [SHOW AUTOMATIC JOBS]
>           WHERE job_type = '%s'
> 					AND status IN %s
>        );
> `, jobspb.TypeAutoSpanConfigReconciliation.String(), jobs.NonTerminalStatusTupleString)
> ```
</details>

total nit: you can do this statically in a var. 


<!-- Sent from Reviewable.io -->

2021-08-18 16:07 UTC, arulajmani reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68522)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @ajwerner, @arulajmani, @irfansharif, @nvanbenschoten, and @RichardJCai)

___
*[pkg/spanconfig/spanconfig.go, line 31 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/68522#-MhOsmWN1N87ZoJYsWQC:-MhOxJ3rAxtvqvSNZyWQ:b-rhzmuu) ([raw file](https://github.com/cockroachdb/cockroach/blob/39d5b1fbff2b78ff1873c0f0d39fb5e0c386f6a7/pkg/spanconfig/spanconfig.go#L31)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Now this can be removed from the interface. 
</blockquote></details>

Was meant to remove the interface entirely. 


<!-- Sent from Reviewable.io -->

2021-08-18 17:19 UTC, arulajmani commented
Thanks for the reviews on this one. 

bors r=ajwerner,nvanbenschoten, irfansharif

2021-08-18 19:22 UTC, merged